### ISSUE TITLE
about RedissonRedLock

### ISSUE THREAD

**Issue by vance1988** [redisson/redisson#1001]
I need a exclusive lock,but it not work,my code is :

    RedissonRedLock lock = getRedLock(lockKey);
    lock.tryLock(-1, 30*1000, TimeUnit.MILLISECONDS);
   

this is work，but i need a leaseTime.
    
    lock.tryLock()

Is that what I'm using not right?

redisson 2.9.4
java 1.7
redis_version 2.8.6

thanks

**Comment by jackygurui** [comment]
确实没看明白你想表达什么？
