### ISSUE TITLE
Class Cast Exception while converting object to RExpirable

### ISSUE THREAD

**Issue by DonHarishAxe** [redisson/redisson#1004]
I'm using an REntity object that I'd like to store in the redis store. And I'd also like to set the expiry time as 30 miutes for the same. But whenever I use the RExpirable function I get the ClassCastException.

The REntity class that I'm using 

```
@REntity
public class Session {
    @RId
    private String id;
    private String api_key;
    private String userid;
    private String ip;
    private Long expirytime;
    private Long sessionexpirytime;

    public Session() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getApi_key() {
        return api_key;
    }

    public void setApi_key(String api_key) {
        this.api_key = api_key;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Long getExpirytime() {
        return expirytime;
    }

    public void setExpirytime(Long expirytime) {
        this.expirytime = expirytime;
    }

    public Long getSessionexpirytime() {
        return sessionexpirytime;
    }

    public void setSessionexpirytime(Long sessionexpirytime) {
        this.sessionexpirytime = sessionexpirytime;
    }

    private final static String key="Bar12345Bar12345";
    private static final String initVector = "RandomInitVector";
    public static String encrypt(String value) {
        try {
            IvParameterSpec iv = new IvParameterSpec(initVector.getBytes("UTF-8"));
            SecretKeySpec skeySpec = new SecretKeySpec(key.getBytes("UTF-8"), "AES");

            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
            cipher.init(Cipher.ENCRYPT_MODE, skeySpec, iv);

            byte[] encrypted = cipher.doFinal(value.getBytes());
            return java.util.Base64.getEncoder().encodeToString(encrypted);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return null;
    }

    public  static String decrypt(String encrypted) {
        try {
            IvParameterSpec iv = new IvParameterSpec(initVector.getBytes("UTF-8"));
            SecretKeySpec skeySpec = new SecretKeySpec(key.getBytes("UTF-8"), "AES");

            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
            cipher.init(Cipher.DECRYPT_MODE, skeySpec, iv);

            byte[] original = cipher.doFinal(java.util.Base64.getDecoder().decode(encrypted));

            return new String(original);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return null;
    }
    /*@Override
    public boolean equals(Object obj) {
        return (obj instanceof Session && UUID.fromString(decrypt(((Session) obj).id)).hashCode() == UUID.fromString(decrypt(this.id)).hashCode());

    }
    @Override
    public int hashCode() {
        return UUID.fromString(decrypt(id)).hashCode();
    }*/

}


```
The function persisting and setting it as RExpirable 

```
RLiveObjectService service = client.getLiveObjectService();
Session session = new Session();
session.setId(encrypt("1345434"));
session.setExpirytime(Utils.getUnixTimeWithAddedMinutes(10));
session.setIp("127.0.0.2");
session.setSessionexpirytime(Utils.getUnixTimeWithAddedMinutes(30));
session.setUserid(encrypt("301237"));
session.setApi_key(encrypt("tSpP"));
service.persist(session);
service.asRExpirable(session).expire(30, TimeUnit.MINUTES);


```
The persist function works as I'm able to retreive the data back. So the redis config is fine. But the following exception is being thrown.

```
Caused by: java.lang.ClassCastException: models.Session cannot be cast to org.redisson.api.RExpirable
	at org.redisson.RedissonLiveObjectService.asRExpirable(RedissonLiveObjectService.java:493) ~[redisson-3.5.0.jar:na]

```
Any help is appreciated. Thanks!

**Comment by jackygurui** [comment]
Try the last two lines as this:

```
session = service.persist(session);
service.asRExpirable(session).expire(30, TimeUnit.MINUTES);
```

**Comment by DonHarishAxe** [comment]
Thanks a lot dude. Now it does work. And I have another doubt regarding the getter and setter of a REntity object. Can we include our logic in the getters and setters? For example in the above Session class, I would like to encrypt the api_key inside the setter function instead of passing the encrypted key as parameter. So my new code looks like 

 public void setApi_key(String api_key) {
        this.api_key = encrypt(api_key);
}

But Redis only stores the non-encrypted api_key everytime.

**Comment by jackygurui** [comment]
The way Live Object works is, in a simple term, to catch the get/set method calls and redirect it to redis. Therefore the code inside the getter or setter from the original class are never executed.

**Comment by DonHarishAxe** [comment]
Yeah, but don't you think it's a necessity for it to give us the room to include our logic? I do not want to encrypt and send the data from anywhere outside this class. So instead I thought of writing a custom function that gets the plain api_key, encrypts it and sets the value using the setter function. In that case I do not want to expose the setter function at all. But it seems like you cannot have a private getter/setter function. Am I right? And is there any other way to do it?

public void storeApi_key(String api_key) {
        setApi_key(encrypt(api_key));
    }

Something like this with setApi_key as a private function doesn't work as well.

**Comment by jackygurui** [comment]
You can implement your own encryption encoder to achieve this fairly easily. This process is also transparent to the POJO class.

**Comment by DonHarishAxe** [comment]
Hey, I'm a beginner in Redis and can't quite get what you're suggesting. Are you asking me to write my own encoder in Redis level or what?

**Comment by jackygurui** [comment]
Redisson "encodes" all the data at the command level before transmitted to Redis. It also "decodes" the data as soon as the Redis replies a request. It is easier, more transparent and less boilerplate code to create a codec like one of [these](https://github.com/redisson/redisson/tree/master/redisson/src/main/java/org/redisson/codec) to handle encryption and decryption. 

Once you have created this crypto codec, you can register it with the codec provider to be used by one of more Live Objects. Other RObjects can also benefit from it.

**Comment by DonHarishAxe** [comment]
Hey thanks for the suggestion.
