### ISSUE TITLE
RMapCache Listener in Cluster Environment

### ISSUE THREAD

**Issue by gkamgang** [redisson/redisson#1005]
Hi,

We have a trouble with Redisson RMapCache in a redis cluster.

Map Initialization

    RMapCache<String, BaseMessage> mapCache = redissonClient.getMapCache("callbackFailedMessages");
    mapCache.addListener((EntryExpiredListener<String, BaseMessage>) entryEvent -> { [listener_code]}
 
Map Update
  
    RMapCache<String, BaseMessage> mapCache = redissonClient.getMapCache("callbackFailedMessages");
    mapCache.put(localMsgId, drMessage, intervalTime, TimeUnit.SECONDS);

With our app configured with one redis, we have no trouble, the listener is called once
But we experienced troubles with a redis cluster with 3 nodes, the listener is called 3 times.
It seems that every node send an expiry event...

Did you have any similar troubles? 

Thanks

**Comment by mrniko** [comment]
Can't reproduce it. Are you sure `mapCache.addListener` had not been called 3 times?

**Comment by gkamgang** [comment]
Oh nice note.. Let me check it..Thanks for the answer

**Comment by gkamgang** [comment]
You were right! It was a bad   bug in our algorithm, sorry for disturbing and thanks for the support.

**Comment by rc452860** [comment]
this problem still on 3.12.3? I have same problem
```
@Test
    public void test() throws InterruptedException {
        RMapCache<String, String> rMapCahce = redissonClient.getMapCache("aaa");
        rMapCahce.addListener(new EntryExpiredListener() {
            @SneakyThrows
            @Override
            public void onExpired(EntryEvent event) {
                log.info("listen1 {}",objectMapper.writeValueAsString(event) );
            }
        });

//
//        rMapCahce.addListener(new EntryExpiredListener() {
//            @Override
//            public void onExpired(EntryEvent event) {
//                log.info("listen2 key:{} ,value: {}", event.getKey(), event.getValue());
//            }
//        });

        rMapCahce.put("a", "hello", 5, TimeUnit.SECONDS);
        rMapCahce.put("b", "hellob", 3, TimeUnit.SECONDS);

        Thread.sleep(10000);
    }
```
it call two times.

output:
```
2020-03-03 13:47:20.539 [redisson-3-2,0,0] INFO  com.citms.RedissExpireTest - listen1 {"Source":{},"Type":"EXPIRED","Key":"b","Value":"hellob","OldValue":null}
2020-03-03 13:47:20.576 [redisson-3-2,0,0] INFO  com.citms.RedissExpireTest - listen1 {"Source":{},"Type":"EXPIRED","Key":"b","Value":"hellob","OldValue":null}
2020-03-03 13:47:25.434 [redisson-3-3,0,0] INFO  com.citms.RedissExpireTest - listen1 {"Source":{},"Type":"EXPIRED","Key":"a","Value":"hello","OldValue":null}
2020-03-03 13:47:25.445 [redisson-3-3,0,0] INFO  com.citms.RedissExpireTest - listen1 {"Source":{},"Type":"EXPIRED","Key":"a","Value":"hello","OldValue":null}
```

**Comment by mrniko** [comment]
@rc452860 

related to https://github.com/redisson/redisson/issues/2397
