### ISSUE TITLE
哨兵模式当某个节点不可用时，客户端如何感知？

### ISSUE THREAD

**Issue by tianyangyang427** [redisson/redisson#1007]
哨兵模式：

当某个节点down调或者新增节点时，客户端如何感知，用以下代码进行测试，获取哨兵监控的redis节点，休眠10s后，停掉某一个redis节点发现和前一次获取的redis节点一样。

Redisson rd=(Redisson) context.getBean("dbbasicRedisson");
			Collection<Node> nodes=rd.getNodesGroup().getNodes();
			
			for (Node node : nodes) {
				System.out.println(node.getAddr()+"\t"+node.getType());
			}
			
			Thread.sleep(10000);
			
			System.out.println("休眠10s================================");
			
			Collection<Node> nodes1=rd.getNodesGroup().getNodes();
			
			for (Node node : nodes1) {
				System.out.println(node.getAddr()+"\t"+node.getType());
			}
Collection<Node> nodes=rd.getNodesGroup().getNodes();
			
			for (Node node : nodes) {
				System.out.println(node.getAddr()+"\t"+node.getType());
			}
			
			Thread.sleep(10000);
			
			System.out.println("休眠10s================================");
			
			Collection<Node> nodes1=rd.getNodesGroup().getNodes();
			
			for (Node node : nodes1) {
				System.out.println(node.getAddr()+"\t"+node.getType());
			}

/192.168.10.109:6439	SLAVE
/192.168.10.109:6429	MASTER
/192.168.10.109:6449	SLAVE
/192.168.10.109:6459	SLAVE
/192.168.10.109:6429	SLAVE
休眠10s================================
/192.168.10.109:6439	SLAVE
/192.168.10.109:6429	MASTER
/192.168.10.109:6449	SLAVE
/192.168.10.109:6459	SLAVE
/192.168.10.109:6429	SLAVE

**Comment by rfyiamcool** [comment]
太狠了，直接上中文.

`Please speak english`

**Comment by jackygurui** [comment]
哨兵模式是通过监听哨兵节点的`+switch-master`，`+sdown`，`-sdown`，`+slave`和`+sentinel`这几个频道来感知节点变化的。

你说的情况应该是哨兵配置上的问题。
