### ISSUE TITLE
DNS monitoring in Replicated mode?

### ISSUE THREAD

**Issue by Yipei** [redisson/redisson#1009]
Hi,

I have a question regarding the DNS monitoring. Looks like the 'dnsMonitoring' can only be set when using single server config, but not in ReplicatedServersConfig. We are currently using AWS elasticache and we found in the AWS document, it highlights that "It is important that client applications are configured to frequently resolve DNS names of cache nodes when they attempt to connect to a cache node endpoint." So does redisson have the ability to detect potential ip changes on endpoints when using Elasticache?

Based on my test, when I 'restored' an endpoint with the same host url but a different ip address, redisson kept using the last known ip address to try connect to that endpoint, but never detected the new one. I tried to change the ttl in java.security and it didn't help.

Please let know if you have any ideas on this one. Thanks.

**Comment by mrniko** [comment]
Good point. I'm doing it

**Comment by mrniko** [comment]
Implemented

**Comment by daniel9x** [comment]
I'm curious if this is somehow related to the issue I'm having. I'm starting up my application instance and it connects to the cache fine, but then after some time I start getting thrown "Unable to resolve" errors for the replicated servers I just connected to. I'm also using ElasticCache but admittedly am not an expert on either technology.

**Comment by mrniko** [comment]
@daniel9x have you tried the latest version? since it has some improvements related to DNS monitoring

**Comment by daniel9x** [comment]
@mrniko Actually shortly after this comment I updated from 3.5.6 to 3.5.7 and have noticed it happening less frequently now!
