### ISSUE TITLE
9.分布式服务 9.22 再比如例子有误

### ISSUE THREAD

**Issue by chenhaipeng** [redisson/redisson#1011]
//RLO对象:
MyLiveObject myLiveObject = service.get(MyLiveObject.class, "1");
MyOtherObject other = new MyOtherObject();
other.setOtherName("ABC");
myLiveObject.setValue(other);
System.out.println(myLiveObject.getValue().getOtherName());
//输出是ABC

//普通Java对象:
MyLiveObject myLiveObject = service.get(MyLiveObject.class, "1");
MyOtherObject other = new MyOtherObject();
other.setOtherName("ABC");
myLiveObject.setValue(other);
System.out.println(myLiveObject.getValue().getOtherName());
//输出是ABC

普通java对象应该是
MyLiveObject myLiveObject  = new MyLiveObject();

the document write here
//Standard Java Object behaviour:
MyLiveObject myLiveObject = service.get(MyLiveObject.class, "1");

the Standard Java Object behaviour,should be:
MyLiveObject myLiveObject  = new MyLiveObject();

**Comment by rfyiamcool** [comment]
哥们，直接上中文呀？ 

`please speak english.`

**Comment by jackygurui** [comment]
@chenhaipeng 感谢指出，麻烦你给改一下呗。

**Comment by jackygurui** [comment]
fixed with https://github.com/redisson/redisson/wiki/9.-分布式服务/_compare/0d8c62205d4ce4a11b570b181a3772c3ac4c2504...ef512c02abba537b2f07d6618185b8e23dd3aadf
