### ISSUE TITLE
【maybe a bug】I use RBatch to read and write bucket data，when redis cluster failover，the old master's ops and cpu ratio become very high 

### ISSUE THREAD

**Issue by fsindustry** [redisson/redisson#1013]
Hi，please check whether this situation is a bug：
1）I use RBatch to read and write bucket data，so that I'can use the redis pipeline mechanism；
2）redis is in cluster mode，the version is 3.2.9; redisson version is 3.5.0；
3）when I killed the redis master instance，until failover，and restart it；now the old master become slave；
4）use info command to observe the old master's cpu ratio and instantaneous_ops_per_sec indicator，I find it's very high；cpu ratio is 400%，and ops is nearly 200,000；
5）I killed the redisson process，and the old master instance become normal；
here is my configuration:
<img width="403" alt="default" src="https://user-images.githubusercontent.com/12935987/29651966-ec6177e8-88d5-11e7-98b5-fbdf32990714.png">
and my code below，I implement codec interface using proto buf as the codec：
<img width="863" alt="default" src="https://user-images.githubusercontent.com/12935987/29646981-3a5dc360-88b9-11e7-988f-ed8ac5ae91f1.png">
<img width="677" alt="default" src="https://user-images.githubusercontent.com/12935987/29646989-445cc8e8-88b9-11e7-9c26-ca316a44f815.png">

**Comment by mrniko** [comment]
I made few changes to resolve #945. Could you try master branch version?

**Comment by mrniko** [comment]
Fixed most likely reason for this issue. Please reopen if it happen again
