### ISSUE TITLE
redisson 3.5.0 clusterServersConfig server can‘t start

### ISSUE THREAD

**Issue by craftlook** [redisson/redisson#1019]
config.class :
        Config config = new Config();
        config.setCodec(new StringCodec());
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        clusterServersConfig.setConnectTimeout(timeout);
        clusterServersConfig.setTimeout(timeout);
        clusterServersConfig.setReconnectionTimeout(4000);
        clusterServersConfig.setScanInterval(2000);
        clusterServersConfig.addNodeAddress("redis://10.0.3.252:7001",
                "redis://10.0.3.252:7002",
                "redis://10.0.3.252:7003",
                "redis://10.0.3.252:7004",
                "redis://10.0.3.252:7005",
                "redis://10.0.3.252:7006");

JDK:1.8   redisson:3.5.0  redisServer:3.0.3

my project can't start. i debug ClusterConnectionManager.class file. connectionFuture is not completed

![image](https://user-images.githubusercontent.com/17558555/29955007-8aed06a0-8f0e-11e7-842d-a863fb949208.png)

redisson:3.3.1 is OK.

**Comment by mrniko** [comment]
Doesn't start without any error?

**Comment by mrniko** [comment]
Could you please help to debug it? Since I can't reproduce it. Problem might be inside `BaseConnectionHandler.channelActive` and `connectionPromise.trySuccess` never invoked. It should be invoked during channel activation phase.

**Comment by craftlook** [comment]
without any error

I try to debug it. I found it stop at the `RedissonPromise.syncUninterruptibly` method `this.join();`

![image](https://user-images.githubusercontent.com/17558555/29962717-b4110e0a-8f36-11e7-9723-06125d3a509f.png)

I make breakpoints at the `BaseConnectionHandler.channelActive` and `RedissonPromise.trySuccess` .  never step into. I feel never invoked.

**Comment by mrniko** [comment]
Interesting. Please also make breakpoints at `RedisConnection c = RedisConnection.getFrom(future.channel());` and `bootstrap.config().group()` lines inside `RedisClient.connectAsync ` method

**Comment by mrniko** [comment]
I see you're using IDE decompiler. It would be better to attach sources jar available in maven repo

**Comment by mrniko** [comment]
Also try to rollback to netty 4.1.8 used in 3.3.1 version.

**Comment by craftlook** [comment]
Sorry to answer you so late.   Netty jar conflict.  Thank you
