### ISSUE TITLE
RAtomicDouble.decrementAndGet()方法会抛出异常RedisException: ERR value is not an integer or out of range.

### ISSUE THREAD

**Issue by JackEggie** [redisson/redisson#1020]
这个方法会报错的原因应该是redis没有提供DECRBYFLOAT命令。
但是执行getAndDecrement()方法是不会报错的。

我看了一下这两个方法的实现差异
decrementAndGet()方法使用的是DECR命令
getAndDecrement()方法则使用的是INCRBYFLOAT -1.0的方式

想问一下这里的实现方式为什么是不一致的，这算不算是一个bug呢？

源码传送门：https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonAtomicDouble.java
decrementAndGet() 71-79行
getAndDecrement() 137-145行

**Comment by mrniko** [comment]
Fixed
