### ISSUE TITLE
Sentinel response timeout defined as retryInterval*retryAttempts in Sentinel Mode

### ISSUE THREAD

**Issue by manishsinghrawat** [redisson/redisson#1023]
In sentinel mode timeout for sentinel response is configured as retryInterval*retryAttempts. This make it impossible to set retryAttempts =0 in sentinel mode.  

Also RBatch retryAttempts cannot be set to zero.

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by manishsinghrawat** [comment]
version we are using in production is 2.9.3

**Comment by mrniko** [comment]
Could you give me some test code to reproduce the problem with RBatch.retryAttempts ?
