### ISSUE TITLE
Monitor calls to redis

### ISSUE THREAD

**Issue by namit081** [redisson/redisson#1029]
Hi, 

We wanted to monitor the calls made by our service to redis. For this, we were currently checking the calls made to RedissonCache get/put/putIfAbsent functions.

Could you please let us know if this is the best approach or we should be monitoring some base method that is ultimately used by all wrappers to execute redis operations.

Thanks

**Comment by Himanshu4** [comment]
👍  We are also monitoring this using new relic where we are using custom instrumentation of new relic https://docs.newrelic.com/docs/agents/java-agent/custom-instrumentation/custom-instrumentation-editor-instrument-ui#manual-instrumentation. 

Please let us know which functions needs to be monitored so that we can track all the commands issued by redisson client to redis servers.

**Comment by mrniko** [comment]
Do you mean monitor commands and lua scripts it self? If you want to get statistics you could use Dropwizard Metrics available for different Redisson objects - https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks/#147-dropwizard-metrics

**Comment by Himanshu4** [comment]
Actually we are already using new relic for our application monitoring. We wanted all the monitoring to be at single place. Thats why, we want the redisson command metrics like
1. No of commands executed with each type of command
2. time taken in executing the command.

in the new relic.

We have also raised a feature request with new relic for redisson.
https://discuss.newrelic.com/t/feature-idea-instrumentation-support-for-redisson-client-in-java-agent/51690

See if you can expedite it.

**Comment by mrniko** [comment]
Since 3.10.0 version Redisson also supports newrelic monitoring system. https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#1410-statistics-monitoring-jmx-and-other-systems
