### ISSUE TITLE
During the load testing got org.redisson.RedissonShutdownException: Redisson is shutdown , but there isn't  start() method to restart it again!

### ISSUE THREAD

**Issue by JerryCai** [redisson/redisson#1030]
My application only use the Redisson lock/unlock feature as below:
```         
redissonClient.getFairLock(name).lockInterruptibly(expiredTime, timeUnit);

 redissonClient.getFairLock(name).unlock();

```

Then I do load testing finally I got the un-recoverable errors as below:
```
org.redisson.RedissonShutdownException: Redisson is shutdown
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:477)
        at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:453)
        at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:395)
        at org.redisson.RedissonFairLock.tryLockInnerAsync(RedissonFairLock.java:126)
        at org.redisson.RedissonLock.tryAcquireAsync(RedissonLock.java:172)
        at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:145)
        at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:114)
```

So I post two issues:
- Issue 1: What does cause the Redisson shutdown without call redissonClient.shutdown() during testing

- Issue 2: It need to provider below API when application encounter this error to restart its connections:

```
redissonClient.start(); 
```
or
```
redissonClient.restart();
```
when encounter this error, but there isn't this method.

**Comment by mrniko** [comment]
You can ensure from code that shutdown process run only during `redissonClient.shutdown` method invocation. Could you share your whole test code?

**Comment by JerryCai** [comment]
@mrniko see below: Only our application shutdown can cause the Redission client shutdown, The problem is our application is working, but get error that Redisson is shutdown
```
@Configuration
public class RedissonConfig {
    public static final String KEY_REDIS_ADDRESS = "asyncmq_redis_address";
    public static final String KEY_REDIS_DB = "asyncmq_redis_database";

    @Autowired
    private RedisProperties redisProperties;


    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        String address = "redis://" + redisProperties.getHost() + ":" + redisProperties.getPort();
        int database = redisProperties.getDatabase();
        System.setProperty(KEY_REDIS_ADDRESS, address);
        System.setProperty(KEY_REDIS_DB, "" + database);
        Config config = new Config();
        config.useSingleServer()
                .setAddress(address)
                .setDatabase(database)
                .setTimeout(redisProperties.getTimeout());
        RedissonClient redissonClient = Redisson.create(config);
        return redissonClient;
    }
}
```

**Comment by JerryCai** [comment]
@mrniko BTW, I used version is 3.5.1 , I will change to 3.5.0 to try again
```
<dependency>
   <groupId>org.redisson</groupId>
   <artifactId>redisson</artifactId>
   <version>3.5.1</version>
</dependency>  
```

**Comment by jackygurui** [comment]
Perhaps a break point on the shutdown method can reveal the secret?

**Comment by johnou** [comment]
@jackygurui if I had to take a guess it's probably the spring context shut down invoking shutdown on the RedissonClient bean prematurely. @JerryCai you will need to control the startup and shutdown sequence of spring beans. Providing a reproducer eg. source code to a small project which demonstrates the issue would be useful for further diagnosis.

**Comment by jackygurui** [comment]
Thanks @johnou this is exactly what I was trying to (indirectly) suggest. Call stack at the breakpoint should reveal everything. ;P

**Comment by JerryCai** [comment]
@johnou @jackygurui You are right! the root cause is trigged by Spring bean destroy, I will mark this issue to closed!

**Comment by YangyangLi0528** [comment]
I had the same problem yesterday,and my version is Redission 2.10.0 + JDK1.7

```
 -org.redisson.RedissonShutdownException: Redisson is shutdown
 - org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:477)
 - org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:453)
 - org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:395)
 - org.redisson.RedissonFairLock.tryLockInnerAsync(RedissonFairLock.java:126)
 - org.redisson.RedissonLock.tryAcquireAsync(RedissonLock.java:172)
 - org.redisson.RedissonLock.tryAcquire(RedissonLock.java:145)
 - org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:114)
 - org.redisson.RedissonLock.lock(RedissonLock.java:99)
```
Thank you for your advices, I‘ll try.
But I am very confused that when I repackaged my project with gradle,
 the Redission shutdown Exception disappeared.

**Comment by RoyLee87** [comment]
> @johnou @jackygurui You are right! the root cause is trigged by Spring bean destroy, I will mark this issue to closed!

could you tell me how to resolve this issue？ thanks

**Comment by RoyLee87** [comment]
> @johnou @jackygurui You are right! the root cause is trigged by Spring bean destroy, I will mark this issue to closed!

could you tell me how to resolve this issue？ thanks

**Comment by RoyLee87** [comment]
> destroy



> My application only use the Redisson lock/unlock feature as below:
> 
> ```
> redissonClient.getFairLock(name).lockInterruptibly(expiredTime, timeUnit);
> 
>  redissonClient.getFairLock(name).unlock();
> ```
> Then I do load testing finally I got the un-recoverable errors as below:
> 
> ```
> org.redisson.RedissonShutdownException: Redisson is shutdown
>         at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:477)
>         at org.redisson.command.CommandAsyncService.evalAsync(CommandAsyncService.java:453)
>         at org.redisson.command.CommandAsyncService.evalWriteAsync(CommandAsyncService.java:395)
>         at org.redisson.RedissonFairLock.tryLockInnerAsync(RedissonFairLock.java:126)
>         at org.redisson.RedissonLock.tryAcquireAsync(RedissonLock.java:172)
>         at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:145)
>         at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:114)
> ```
> So I post two issues:
> 
> * Issue 1: What does cause the Redisson shutdown without call redissonClient.shutdown() during testing
> * Issue 2: It need to provider below API when application encounter this error to restart its connections:
> 
> ```
> redissonClient.start(); 
> ```
> or
> 
> ```
> redissonClient.restart();
> ```
> when encounter this error, but there isn't this method.


could you tell me how to resolve this issue？ thanks

**Comment by RoyLee87** [comment]
I had the same problem two days ago，
could you tell me how to resolve this issue？

**Comment by 0vally1** [comment]
org.redisson.RedissonShutdownException: Redisson is shutdown
我也遇见了这问题，请问解决办法是什么？
我是使用 了Redisson的队列，监听消息时抛的错误

**Comment by huchao-hu** [comment]
> @johnou @jackygurui你说的对！根本原因是Spring bean破坏触发，我将这个问题标记为关闭！

How do you solve the above problems

**Comment by dfontenot** [comment]
> @mrniko see below: Only our application shutdown can cause the Redission client shutdown, The problem is our application is working, but get error that Redisson is shutdown
> 
> ```
> @Configuration
> public class RedissonConfig {
>     public static final String KEY_REDIS_ADDRESS = "asyncmq_redis_address";
>     public static final String KEY_REDIS_DB = "asyncmq_redis_database";
> 
>     @Autowired
>     private RedisProperties redisProperties;
> 
> 
>     @Bean(destroyMethod = "shutdown")
>     public RedissonClient redissonClient() {
>         String address = "redis://" + redisProperties.getHost() + ":" + redisProperties.getPort();
>         int database = redisProperties.getDatabase();
>         System.setProperty(KEY_REDIS_ADDRESS, address);
>         System.setProperty(KEY_REDIS_DB, "" + database);
>         Config config = new Config();
>         config.useSingleServer()
>                 .setAddress(address)
>                 .setDatabase(database)
>                 .setTimeout(redisProperties.getTimeout());
>         RedissonClient redissonClient = Redisson.create(config);
>         return redissonClient;
>     }
> }
> ```

Running into this issue as well. Does anyone know what was the change that was needed to fix this bean declaration?

**Comment by zhaoyanwenqi** [comment]
> @mrniko see below: Only our application shutdown can cause the Redission client shutdown, The problem is our application is working, but get error that Redisson is shutdown
> 
> ```
> @Configuration
> public class RedissonConfig {
>     public static final String KEY_REDIS_ADDRESS = "asyncmq_redis_address";
>     public static final String KEY_REDIS_DB = "asyncmq_redis_database";
> 
>     @Autowired
>     private RedisProperties redisProperties;
> 
> 
>     @Bean(destroyMethod = "shutdown")
>     public RedissonClient redissonClient() {
>         String address = "redis://" + redisProperties.getHost() + ":" + redisProperties.getPort();
>         int database = redisProperties.getDatabase();
>         System.setProperty(KEY_REDIS_ADDRESS, address);
>         System.setProperty(KEY_REDIS_DB, "" + database);
>         Config config = new Config();
>         config.useSingleServer()
>                 .setAddress(address)
>                 .setDatabase(database)
>                 .setTimeout(redisProperties.getTimeout());
>         RedissonClient redissonClient = Redisson.create(config);
>         return redissonClient;
>     }
> }
> ```

Load test, I also encountered this problem. How to solve the problem?

**Comment by zhaoyanwenqi** [comment]
Load test, I also encountered this problem. How to solve the problem?
