### ISSUE TITLE
Huge log messages

### ISSUE THREAD

**Issue by valodzka** [redisson/redisson#1035]
I started testing redisson with my app (Redisson 3.5.1), first issue i discovered:

Writing about ~23mb data to redis map.
Error message generated with size ~180mb when RedisTimeoutException accured.
I guess issue with line that blindly call toString:https://github.com/redisson/redisson/blob/8cad23cdcec19aff04725659cc0af9239053af6b/redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java#L323

**Comment by valodzka** [comment]
Message look like (with long long `result` field): 

09-10 08:45:55     [rn3-11]  WARN o.r.c.handler.CommandDecoder    | response has been skipped due to timeout! channel: [id: 0x51f23a66, ...], command: CommandData [promise=org.redisson.misc.RedissonPromise@cc9939[Completed exceptionally], command=(HGET), params=[...], codec=org.redisson.client.codec.ByteArrayCodec@3e0ea2ee], result: [76, 90, 52, 66, 108, 111, 99, 107, 38, 8, 90, 0, 0, 0, 0, 1, 0, 104, -77, -17, 6, -16, 22, -84, -19, 0, 5, 115, 114, 0, 38, 99, 111, 109, 46, 102, 111, 114, 107, 115, 104, 117, 110, 116, 101, 114, 46, 115, 99, 97, 110, 101, 114, 115, 46, 99, 114, 97, 119, 108, 9, 0, -13, 4, 83, 116, 97, 116, 101, 47, 56, 36, 87, -39, -17, -50, -50, 2, 0, 9, 74, 0, 14, 28, 0, -9, 12, 86, 101, 114, 115, 105, 111, 110, 76, 0, 9, 98, 101, 116, 115, 67, 97, 99, 104, 101, 116, 0, 45, 76, 99, 111, 109, 47, 82, 0, 19, 47, 82, 0, 16, 47, 37, 0, 16, 99, 37, 0, 36, 47, 66, 47, 0, -1, 6, 59, 76, 0"

**Comment by mrniko** [comment]
For big requests I would recommend to increase `Config.timeout` setting.

**Comment by valodzka** [comment]
I already did it, but timeouts still happen sometimes. I think such huge log messages must be never generated anyway.

**Comment by mrniko** [comment]
Fixed
