### ISSUE TITLE
Support for setting maxSize for bounded RedissonMapCache

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#1036]
While implementing support for setMaxSize in RedissonMapCache we noticed a bug in the eviction where it may evict more elements than the value set for max size. Here is our work in progress https://github.com/sulake/redisson/pull/1/files

**Comment by mrniko** [comment]
Is there way to reproduce it?

**Comment by johnou** [comment]
@mrniko yes in the new unit test in the pull request linked above, do you have some cycles to continue with this change set? We are currently in the staging process of our release cycle so I won't be able to take a look until later this week.

**Comment by johnou** [comment]
@mrniko I think I managed to track it down :+1:

**Comment by mrniko** [comment]
I have already did it. :)

**Comment by johnou** [comment]
ta, I'll send a follow-up pull request with some cleanup.
