### ISSUE TITLE
RedissonMapCache merge conflict lost fix for setting large amount of items

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#1037]
@mrniko https://github.com/redisson/redisson/commit/2bdccfccf155765334fe9df68f427e551c11ded0#comments

**Comment by johnou** [comment]
caused by commit https://github.com/redisson/redisson/commit/0f05261db1f01bce78b1b7d219dd31b0d3082685#diff-37335800a0654f7b8dca6699e1f8e152

**Comment by mrniko** [comment]
There is no point to do any fix. Since `RedissonMapCacheTest.testPutAllBig` successfully passed.
