### ISSUE TITLE
RMapCache EntryListener events

### ISSUE THREAD

**Issue by srvanukuri** [redisson/redisson#1040]
I am testing the RMapCache listeners using redisson 2.10.0 release, when I executed the sample code from the wiki of distributed collections, the code is not executed. I am not sure what I am missing here or is this a feature that is only available with Redis Pro, can you please take a look and guide me.

Below is the code

`import org.redisson.Redisson;
import org.redisson.api.RMapCache;
import org.redisson.api.RedissonClient;
import org.redisson.api.map.event.EntryCreatedListener;
import org.redisson.api.map.event.EntryEvent;
import org.redisson.api.map.event.EntryExpiredListener;
import org.redisson.api.map.event.EntryRemovedListener;
import org.redisson.api.map.event.EntryUpdatedListener;
import org.redisson.config.Config;

public class RedissonEvictionListenerTest {

	public static void main(String[] args) {
		
		new RedissonEvictionListenerTest().testRMapCacheEntryListener();
	}
	
	private void testRMapCacheEntryListener(){
		
		Config redisConfig = new Config();
    	redisConfig.useSingleServer().setAddress("redis://127.0.0.1:7001");
    	RedissonClient redisson = Redisson.create(redisConfig);
		
		RMapCache<String, Integer> map = redisson.getMapCache("myMap");
		

		int updateListener = map.addListener(new EntryUpdatedListener<Integer, Integer>() {
		     @Override
		     public void onUpdated(EntryEvent<Integer, Integer> event) {
		    	 System.out.println("onUpdated");
		          event.getKey(); // key
		          event.getValue(); // new value
		          event.getOldValue(); // old value
		          // ...
		     }
		});

		int createListener = map.addListener(new EntryCreatedListener<Integer, Integer>() {
		     @Override
		     public void onCreated(EntryEvent<Integer, Integer> event) {
		    	 System.out.println("onCreated");
		          event.getKey(); // key
		          event.getValue(); // value
		          // ...
		     }
		});

		int expireListener = map.addListener(new EntryExpiredListener<Integer, Integer>() {
		     @Override
		     public void onExpired(EntryEvent<Integer, Integer> event) {
		    	 System.out.println("onExpired");
		          event.getKey(); // key
		          event.getValue(); // value
		          // ...
		     }
		});

		int removeListener = map.addListener(new EntryRemovedListener<Integer, Integer>() {
		     @Override
		     public void onRemoved(EntryEvent<Integer, Integer> event) {
		    	 System.out.println("onRemoved");
		          event.getKey(); // key
		          event.getValue(); // value
		          // ...
		     }
		});

		map.put("test", 1);
		map.put("test", 11);
		map.remove("test");
		
		map.removeListener(updateListener);
		map.removeListener(createListener);
		map.removeListener(expireListener);
		map.removeListener(removeListener);
		
		redisson.shutdown();
	}
	
}
`

**Comment by mrniko** [comment]
Hi!

I have just run your code and got follow output:
```
onCreated
onUpdated
onRemoved
```

**Comment by srvanukuri** [comment]
Thanks much for the verification, I think the issue might be with my
environment, let me investigate.
