### ISSUE TITLE
Single connection sharing

### ISSUE THREAD

**Issue by kringol** [redisson/redisson#1041]
Example context: 
When you have multiple client apps (near 1000) connecting to the same redis nodes and you don't want the redis nodes (or they can't) handle the amount of connections from all those client connections pools (file descriptors, etc).

Besides of course, having small connection pools or having more redis nodes. 
Is there any plan or way to utilize redisson on a single shared connection model?
Like for example other redis libraries [does](https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling)

**Comment by mrniko** [comment]
Sorry, I don't see how lettuce supports for single shared connection for all client apps.
Could you please explain?

You could you redisson even with single connection per app. It's not a problem

**Comment by kringol** [comment]
Team interested in this is no longer pursuing this approach, so no need to think about this for now
