### ISSUE TITLE
Bug/Feature-Request: Non-Expiry updating  boolean add(...)  in RSetCache

### ISSUE THREAD

**Issue by mullinger** [redisson/redisson#1044]
Hello,
I am using RSetCache as a lock for various work item.

If the item is in the Set, somebody is working on it. The worker that "locks" the item has a certain amount of time to finish the work, otherwise the "lock" on the item is removed and some other worker can try to claim the item.

```java
if (rSetCache.add(item, 5, TimeUnit.MINUTES)) {
    // Select item for work
}
```
See
boolean org.redisson.api.RSetCache.add(Long value, long ttl, TimeUnit unit)

Unfortunately, each call to add updates the expiry timestamp of the item, even if add was not successful  because it was already added.
That means that, when the worker is killed/hangs/..., the work will never be picked up after the 5 minutes, because each try to reserve the item fails, but updates the expiry.

It would be great to have an atomic method which:
- Only adds if new
- Only sets expiry if added
- Returns true if value was added

**Comment by jackygurui** [comment]
In your case, a RLock should really be used instead, as it is especially created for this purpose as RSetCache is not.

**Comment by mullinger** [comment]
I guess you are talking about the method
boolean tryLock(long waitTime, long leaseTime, TimeUnit unit) ?
I will try that out and see how it performs.

**Comment by mullinger** [comment]
Just for reference: In my usecase RLock was not the right choice.

I have a single thread that checks for work and, if nobody is doing the work delegates to a worker thread.
Because I am doing the locking in the "check thread", and RLock is multi-entrant for a single thread, the  work would be started multiple times.

The solution seems be the PermitExpirableSemaphore which has a different behaviour.

**Comment by jackygurui** [comment]
Great to know PermitExpirableSemaphore can work for you, let me know how you are getting on.
