### ISSUE TITLE
30 times slower than jedis

### ISSUE THREAD

**Issue by valodzka** [redisson/redisson#1045]
I'm trying to migrate old jedis code to redisson and getting some weird result.

Roughly same code, jedis: 

    pool = new JedisPool(new JedisPoolConfig(), host, port, 20_000)

Later in code, from multiple threads:

    try (Jedis j  = pool.getResource()) {
       v = j.hget(mapName, mapKey);
    }

Redisson:

    Config config = new Config()
    config.useSingleServer()
          .setAddress(address)
          .setConnectTimeout(20_000)
          .setTimeout(20_000);

      RedissonClient c = Redisson.create(config);

Later in code, from multiple threads: 

      RMap<byte[], byte[]> map = c.getMap(mapName, new ByteArrayCodec())
      v = map.get(mapKey)
    
Measurements 95% of queries:

![95%](https://monosnap.com/file/JLVdlZLLJ4nr10uOB0y5IXAjJEsyqg.png)

Am I doing something wrong with redisson?

**Comment by mrniko** [comment]
which version are you trying?

**Comment by valodzka** [comment]
redisson 3.5.1, java 1.8.0_144, redis 4.0.1, debian 9.1

**Comment by mrniko** [comment]
Please try 3.5.0 version due to this regression bug https://github.com/redisson/redisson/issues/1031
What is connections amount for jedis you use?

**Comment by valodzka** [comment]
Based on CLIENT LIST, jedis version ~7-10 connections, redission version 60-70 connections probably.

**Comment by mrniko** [comment]
what is the average size of objects stored in map?

**Comment by mrniko** [comment]
also try to set `Config.useSingelServer().setConnectionPoolSize(10)`

**Comment by mrniko** [comment]
I have just released 3.5.2 version. Give it a try too

**Comment by valodzka** [comment]
Average size of object is about 5-10mb.
Seems like upgrade to 3.5.2 helped:
![Mostly same](https://monosnap.com/file/BCUwhT396RwS2weooLz8DyHGO5Tx4g.png)

**Comment by mrniko** [comment]
You have just updated a version, right? or did you change pool size to 10?

**Comment by valodzka** [comment]
Just update was enough, thank you for help. Can you also comment this https://gitter.im/mrniko/redisson, should i open bug?

**Comment by mrniko** [comment]
@valodzka I have answered. You could try [PRO](https://redisson.pro) if you wanted to be faster :)

**Comment by dekelbz** [comment]
We're facing slowness issues as well:
We use Redis for caching. Each cached object is about 90 KB in size. We set the Redisson timeout for 250 ms. Using JMeter, when more than 10-15 users simultaneously access a web page, which we use Redis to render, we're getting many timeouts from Redisson, and each get request takes much more than numerous ms, which is what I'd expect.
I tried running JMeter from another machine at the same time, to see if it slows down Redisson even more, but it didn't seem to make a difference, so I assume it doesn't have to do with the Redis server, but with Redisson. 
To solve this, following this thread, we upgraded to the latest Redisson and changed all the definitions according to what's defined here, with no success. 
Can you think of another reason for this?
Thanks

**Comment by mrniko** [comment]
@dekelbz 

Could you share the code of your Redis based cache implementation ?

**Comment by dekelbz** [comment]
Thanks for the quick response.
Here's my current code:

`private RedissonClient getRedissonClient() {
        Config config = new Config();
        config.setCodec(new SnappyCodec())
                .useSingleServer()
                .setAddress(redisUrl)
                .setPassword(redisPassword)
                .setTimeout(TIMEOUT);
        try {
            return Redisson.create(config);
        } catch (Exception e) {
            LOG.error("error while connecting to Redis", e);
            return null;
        }
    }`

Previously I tried adding the configurations mentioned here and some more (all together like what I pasted, and also any combination

`private RedissonClient getRedissonClient() {
        Config config = new Config();
        config.setCodec(new SnappyCodec())
                .useSingleServer()
                .setAddress(redisUrl)
                .setPassword(redisPassword)
                .setTimeout(TIMEOUT)
                .setTcpNoDelay(true)
                .setSubscriptionsPerConnection(1024)
                .setConnectionPoolSize(1024);
        try {
            return Redisson.create(config);
        } catch (Exception e) {
            LOG.error("error while connecting to Redis", e);
            return null;
        }
    }`

**Comment by mrniko** [comment]
Which Redisson objects do you use for cache access?

**Comment by dekelbz** [comment]
I use RedissonClient. The .get() is what takes very long

**Comment by mrniko** [comment]
@dekelbz Have you tried to test it locally?
