### ISSUE TITLE
[Feature enquiry] Redisson create throws exception when the redis cluster is not ready.

### ISSUE THREAD

**Issue by PeterStayPool** [redisson/redisson#1047]
I was wondering whether the presence of the redis cluster is must to instantiate the redisson client via Redisson.create(config)).

I am evaluating the Redisson along with Jedis. I noticed that Jedis does not require the redis cluster to reachable when instantiating the client. However, redisson throws exception if there is no redis cluster exists. 

We have the use case where our service is started when redis is not available and we expect the redisson client to retry to connect to redis cluster by itself when it is asked to retrieve value.

Could confirm whether this is supported feature or not?

Sincerely,

Peter

**Comment by pjrt** [comment]
This would be great, we are currently having a similar issue. We have some test that test the system in a black-box manner (we bring up an instance of the application as well as an instance for redis). This works fine except that a lot of the times our application comes up faster than our redis instance, which causes `Redisson.create` is crash and burn. 

Would be great if it retried.

**Comment by tomaspiaggio** [comment]
I have found a workaround to this problem. I added a retry method with exponential backoff. 

```scala
  @tailrec
  private def retryExponentialBackoff[T](timesBeforeBackOff: Int, initialTime: Int)(block: Unit => T): T = {

    @tailrec
    def retry[T](times: Int)(func: Unit => T): Try[T] = Try(func()) match {
      case Failure(_) if times > 1 => retry(times - 1)(func)
      case result => result
    }

    retry(timesBeforeBackOff)(block) match {
      case Failure(_) =>
        println(s"[info] could not connect to redis, trying again in $initialTime milliseconds")
        Thread.sleep(initialTime)
        retryExponentialBackoff(timesBeforeBackOff, initialTime * 2)(block)
      case Success(value) =>
        println("[info] connection to redis successful")
        value
    }
  }
```

And the usage is as follows: 

```scala
val redisson: RedissonClient = retryExponentialBackoff[RedissonClient](10, 1000) { _ =>
    Redisson.create(config)
  }
```

Hope it helps someone. I suggest to do this in the `ConnectionPool`, maybe as a configuration. @mrniko you made implementation, am I right?

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/3042
