### ISSUE TITLE
[Redisson 3.5.0 and 3.5.3]Executor service Error

### ISSUE THREAD

**Issue by Godson2017** [redisson/redisson#1049]
The following call does not return
    APP Client:
    Config config = new Config();
    config.useSingleServer().setAddress("redis://11.1.1.230:6379");
    RedissonClient redisson = Redisson.create(config);
    RExecutorService executorService = redisson.getExecutorService("myExecutor");
    RExecutorFuture<Long> future = executorService.submit(new CallableTaskforLong());
    Long result = future.get();
    System.out.println("result =" + result);

   class CallableTaskforLong implements Callable<Long> {

    @RInject
    private RedissonClient redissonClient;

    @Override
    public Long call() throws Exception {
        RMap<String, Integer> map = redissonClient.getMap("myMap");
        Long result = 0l;
        for (Integer value : map.values()) {
            result += value;
        }
        return result;
       }

       Redisson Node:
       Config.yaml:
       singleServerConfig:
           database: 0
           address: "redis://11.1.1.230:6379"
           threads: 0
           executorServiceWorkers:
               myExecutor: 100

           Errors:
           [pool-1-thread-1] ERROR org.redisson.RedissonRemoteService - Can't process the remote service request.
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (BLPOP) with params: [{myExecutor:org.redisson.executor.RemoteExecutorService}, 0]
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:537)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:745)
[pool-1-thread-1] ERROR org.redisson.RedissonRemoteService - Can't process the remote service request.
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (BLPOP) with params: [{myExecutor:org.redisson.executor.RemoteExecutorService}, 0]
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:537)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:745)
[redisson-3-4] ERROR org.redisson.RedissonRemoteService - Can't execute: RemoteServiceRequest [requestId=0ea8b4ca9200eaadc84aad855d687d11, methodName=executeCallable, signatures=[[
java.lang.String, [B, [B]], args=[org.redisson.example.services.CallableTaskforLong, [B@626e3d45, [B@106f2694], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTi
meoutInMillis=86400000], date=1505282417333]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:276)
        at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:59)
        at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:239)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (HSCAN) with params: [myMap, 0]
        at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:537)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        ... 1 more
       

It neither prints "result" nor returns and Redisson node prints many errors.

I am using Redis 4.0.1 and Resisson 3.5.0

**Comment by Godson2017** [comment]
After I change the config.yaml, node started. But the app encountered new error as following:
config.yaml
singleServerConfig:
  database: 0
  address: "redis://11.1.1.230:6379"
threads: 0
executorServiceWorkers:
  myExecutor: _10_ //100->10

Node Started:
[redisson-netty-1-6] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /11.1.1.230:6379
[redisson-netty-1-7] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /11.1.1.230:6379
[main] INFO org.redisson.RedissonNode - 10 worker(s) for 'myExecutor' ExecutorService registered
[main] INFO org.redisson.RedissonNode - Redisson node started!

APP Error:
[main] INFO org.redisson.Version - Redisson 3.5.0
[redisson-netty-1-4] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /11.1.1.230:6379
[redisson-netty-1-7] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /11.1.1.230:6379
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task rejected. ExecutorService is in shutdown state
	at org.redisson.RedissonExecutorService.execute(RedissonExecutorService.java:541)
	at org.redisson.RedissonExecutorService.execute(RedissonExecutorService.java:252)
	at org.redisson.example.services.ExecutorServiceExamples.main(ExecutorServiceExamples.java:84)

**Comment by Godson2017** [comment]
After I delete myExecutor in the Redis and restart the redisson node, it workes. But there are still two problems.
If it doesnt delete the myExecutor  key in the Redis and also the node doesnt restart 
1、the app recall the method which will returns the "Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task rejected. ExecutorService is in shutdown state".
2、the class in app submits will not be loaded into the redisson node. The redisson node usesd old class.

How to resolve them? 

Thank you!

**Comment by Godson2017** [comment]
Does the redisson node only deal with the number of the executorServiceWorkers amount for the RunnableTask?

If I set the executorServiceWorkers  20, the redssion node will call the RunnableTask 20 times and shutdown. 

I think the redisson node will work until some one to shutdown it, isnt it?

**Comment by Godson2017** [comment]
@mrniko Hello, could you please give help?

Thank you very much!

**Comment by mrniko** [comment]
Hi! Could you please change version to 3.5.2 or 3.5.3 due to this regression bug #1031 appeared in 3.5.0 ?

**Comment by Godson2017** [comment]
@mrniko Does the redisson-all-3.5.0.jar up to 3.5.3?If yes, Where to get the redisson-all-3.5.3.jar?

**Comment by Godson2017** [comment]
@mrniko After I upgrade to 3.5.3, it is the same. Is there any problem with my code or config.yaml?

**Comment by mrniko** [comment]
@Godson2017 to https://github.com/redisson/redisson/issues/1049#issuecomment-329089509 >

Could you please write some test case to reproduce that case?

**Comment by Godson2017** [comment]
@mrniko 
After I delete myExecutor in the Redis and restart the redisson node, it workes ok. But there are still one problem as following:
The redisson node only deal with some request then shutdown by itself. Is this right? Or there is somewhere to config to make the node works permanently?
[redisson-netty-1-5] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /11.1.1.230:7379
[redisson-netty-1-7] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /11.1.1.230:7379
[main] INFO org.redisson.RedissonNode - 10 worker(s) for 'myExecutor' ExecutorService registered
[main] INFO org.redisson.RedissonNode - Redisson node started!
1132111
1132111
[Thread-0] INFO org.redisson.RedissonNode - Redisson node has been shutdown successfully

**Comment by Godson2017** [comment]
@mrniko 
And another problem is 
        node start ............
        RExecutorService e = redisson.getExecutorService("myExecutor");
        e.execute(new RunnableTask());
        e.shutdown();
        node.shutdown();
run it again, it will be error : Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task rejected. ExecutorService is in shutdown state.
After delete myexcutor from redis, it will be okay.

**Comment by mrniko** [comment]
I'll try to reproduce it

**Comment by Godson2017** [comment]
@mrniko As following is the ExecutorServiceExamples.java
        Config config = new Config();
        config.useSingleServer().setAddress("redis://11.1.1.110:7379");
        
        RedissonClient redisson = Redisson.create(config);

        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("myExecutor", 1));
        RedissonNode node = RedissonNode.create(nodeConfig);
        node.start();

        RExecutorService e = redisson.getExecutorService("myExecutor");
        e.execute(new RunnableTask());
        e.submit(new CallableTask());
        
        e.shutdown();
        node.shutdown();

After running, the e will not shutdown and node will shutdown, and then thread is not closesd until you kill it directy.

[main] INFO org.redisson.Version - Redisson 3.5.3
[redisson-netty-1-5] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /11.1.1.110:7379
[redisson-netty-1-7] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /11.1.1.110:7379
[main] INFO org.redisson.Version - Redisson 3.5.3
[redisson-netty-5-4] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for /11.1.1.110:7379
[redisson-netty-5-7] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /11.1.1.110:7379
[main] INFO org.redisson.RedissonNode - 10 worker(s) for 'myExecutor' ExecutorService registered
[main] INFO org.redisson.RedissonNode - Redisson node started!
[main] INFO org.redisson.RedissonNode - Redisson node has been shutdown successfully

**Comment by Godson2017** [comment]
@mrniko I found the problem, this could be closed.
Thank you!

**Comment by Godson2017** [comment]
@mrniko 
I have still two problems.
1、How can I not restart redisson node to make the modification usefully after I modify the implementation of RunnableTask and submit?
2、After I run the following code,  the thread will not shutdown even "e.shutdown". 
        Config config = new Config();
    	config.useSingleServer().setAddress("redis://localhost:7379");
        RedissonClient redisson = Redisson.create(config);
        RExecutorService e = redisson.getExecutorService("myExecutor");
        e.execute(new RunnableTask());
        e.shutdown();

Thank you very much!

**Comment by mrniko** [comment]
@Godson2017 

1. Currently it's not possible to change already submitted tasks. Every new task uses latest version of current task class implementation.
2. Let me check it

**Comment by mrniko** [comment]
@Godson2017 After `e.shutdown();` invocation ExecutorService won't shutdown immediately if any task is running. You you better use `shutdownNow` and check for status of `Thread.currentThread().isInterrupted()` inside task

**Comment by Godson2017** [comment]
@mrniko If use e.shutdownNow() there will be error as follows:
java.lang.UnsupportedOperationException
	at org.redisson.RedissonExecutorService.shutdownNow(RedissonExecutorService.java:377)
	at org.redisson.example.services.ExecutorServiceExamples.main(ExecutorServiceExamples.java:72)

**Comment by Godson2017** [comment]
@mrniko I added "Thread.currentThread().isInterrupted()" into the RunnableTask and Node server console return false. But I think it is okay for the node server, the problem is the client doesnt stop.
public class RunnableTask implements Runnable {
    @RInject
    RedissonClient redisson;
    
    @Override
    public void run() {
    	System.out.println("222222");
        RMap<String, String> map = redisson.getMap("myMap");
        map.put("5110", "11");
        System.out.println("end" + Thread.currentThread().isInterrupted());
    }   
}

**Comment by mrniko** [comment]
@Godson2017 You're right about shutdownNow, I'm going to implement it.

Unable to reproduce your case, here is the test case - https://github.com/redisson/redisson/blob/cb1178c82917945653e38005f7a39cc0747e6baf/redisson/src/test/java/org/redisson/executor/RedissonExecutorServiceTest.java#L234

**Comment by Godson2017** [comment]
@mrniko Can I add you through some IM tool, such as wechat?

**Comment by mrniko** [comment]
@Godson2017 I'm able to talk through gitter.im

**Comment by venbill** [comment]
I met too. Did you solve it?

**Comment by mrniko** [comment]
@venbill 

This was a bug solved in next Redisson version

**Comment by javens0601** [comment]
@Godson2017  你那个问题怎么解决的没有描述，我遇到和你一样的问题，请指教一下。
Task rejected. ExecutorService is in shutdown state

**Comment by javens0601** [comment]
@Godson2017 我解决那个问题了
