### ISSUE TITLE
批量使用fastPutAsync方法会导致redis进程CPU占满，且一直卡死

### ISSUE THREAD

**Issue by lasting0001** [redisson/redisson#1050]
redisson版本:3.5.2
Java版本:1.8
redis版本:3.0.1 windows版
环境:win7x64

代码如下：

`
	public final static void init() {
		Config config = new Config();
	       config.useSingleServer().setAddress("redis://127.0.0.1:10000").setPassword("1SXgvoxF3kQlE8If");
		client1 = Redisson.create(config);
	}

	public static void main(String[] args) {
		init();
		RMap<Object, Object> rmap01 = client1.getMap("red_map01");
		long st = System.currentTimeMillis();
		for (int i = 0; i < 10000; i++) {
			rmap01.fastPutAsync("key01", "value01_" + i);
		}
		long ct = System.currentTimeMillis() - st;
		System.out.println("================== ct:" + ct + "ms");
		System.out.println(JsonUtil.stringify(rmap01));
	}
`

**Comment by jackygurui** [comment]
这其实是使用方法的问题。理解这个现象最好的就是打个比方：你一直往缓冲区写数据，缺不给它冲的机会。这样造成了堆积最后就堵塞了。

正确的方式是用RBatch批量写，或者换成`fastPut`

**Comment by lasting0001** [comment]
但是有些数据，比如日志，就没必要确保一定写入了，调用fastPutAsync性能会高一些

**Comment by lasting0001** [comment]
其实关系也不大，我刚测试了linux版的redis，是不会卡死的，但是每次执行会丢失10次左右数据

**Comment by jackygurui** [comment]
`fastPut`性能本身就够高的了

**Comment by jackygurui** [comment]
`fastPut`本身就不会等待返回结果的，保证命令发送了就返回了。

**Comment by lasting0001** [comment]
恩，用RBatch确实挺快的，正好适用于日志
