### ISSUE TITLE
[Anti-Fraud]Is Redisson suitable for redis to develop the realtime anti-fraud system?

### ISSUE THREAD

**Issue by Godson2017** [redisson/redisson#1055]
@mrniko 
Hi, Master.
Is Redisson suitable for developing the realtime anti-fraud system which needs high performance, such as 10 millisecond to finish the computing? 

Thank you very much!

**Comment by mrniko** [comment]
@Godson2017 
Hi! As you know high performance depends on many factors - network latency, data size, hardware and of course Redisson. If Redisson speed wouldn't be enough we offer you to try [Redisson PRO](https://redisson.pro). It has specially engineered high-performance core.
