### ISSUE TITLE
Is RedissonBoundedBlockingQueue thread safe?

### ISSUE THREAD

**Issue by CaryGao** [redisson/redisson#1057]
I'm confused when I read RedissonBoundedBlockingQueue.takeAsync() as follow
```
@Override
    public RFuture<V> takeAsync() {
        RFuture<V> takeFuture = commandExecutor.writeAsync(getName(), codec, RedisCommands.BLPOP_VALUE, getName(), 0);
        return wrapTakeFuture(takeFuture);
    }
```
the takeAsync method first use BLPOP to take object from redis,then if success will call releaseAsync() to increment capacity, I think that two request is not atomic operation, and will cause concurrent issues?

**Comment by jackygurui** [comment]
If you read in the following method and you should see this block of code:

 ```java
                createSemaphore(null).releaseAsync().addListener(new FutureListener<Void>() {
                    @Override
                    public void operationComplete(Future<Void> future) throws Exception {
                        result.trySuccess(takeFuture.getNow());
                    }
                });
```
And you can see results is only considered successful when the semaphore is released. Until then all of other offerings are blocked still, assuming at the maximum capacity. The maximum capacity always is ensured.

**Comment by CaryGao** [comment]
yes, I'v read it and I see queue size is use for semaphore permits, all of other offerings need permit to get object from redis queue , but createSemaphore(null).releaseAsync() is after BLPOP request operationComplete, am I right? if BLPOP success to take an object and redis queue will push it, then after that server is down or thread is interpreter , releaseAsync do not request redis which means queue size can not increment?  I'm not sure but confused.

```
private RPromise<V> wrapTakeFuture(final RFuture<V> takeFuture) {
        final RPromise<V> result = new RedissonPromise<V>() {
            @Override
            public boolean cancel(boolean mayInterruptIfRunning) {
                super.cancel(mayInterruptIfRunning);
                return takeFuture.cancel(mayInterruptIfRunning);
            };
        };
        
        takeFuture.addListener(new FutureListener<V>() {
            @Override
            public void operationComplete(Future<V> future) throws Exception {
                if (!future.isSuccess()) {
                    result.tryFailure(future.cause());
                    return;
                }
                
                createSemaphore(null).releaseAsync().addListener(new FutureListener<Void>() {
                    @Override
                    public void operationComplete(Future<Void> future) throws Exception {
                        result.trySuccess(takeFuture.getNow());
                    }
                });
            }
        });
        return result;
    }
```

**Comment by jackygurui** [comment]
First of all the code above doesn't handle the thread interrupt status so it won't behave any different with the `interrupt()` signal. The thread will run until the release will be executed, or unless the task is canceled. 

Secondly, the effect of a node crash isn't something we can predict in software, thus there is no effective mitigation strategy can be put in place prior to the event. But this is completely a different matter to thread safety. 

However, as far as the implementation's concern, it is nonetheless thread safe.

**Comment by mrniko** [comment]
RedissonBoundedBlockingQueue successor is [Reliable Queue](https://redisson.pro/docs/data-and-services/queues/#reliable-queue) which has atomicity and durability.
