### ISSUE TITLE
文档有些许错误

### ISSUE THREAD

**Issue by lasting0001** [redisson/redisson#1058]
fieldTransformation - 字段转换模式。如上所述，为了尽可能的保证RLO的用法和普通Java对象**一直**，Redisson会自动将常用的普通Java对象转换成与其匹配的Redisson分布式对象。这是由于字段转换模式的默认值是ANNOTATION_BASED，**修改为ANNOTATION_BASED**就可以不转换。

**Comment by jackygurui** [comment]
感谢指出

**Comment by jackygurui** [comment]
Fixed by https://github.com/redisson/redisson/wiki/9.-%E5%88%86%E5%B8%83%E5%BC%8F%E6%9C%8D%E5%8A%A1/_compare/02db36a30d881ebcfb9bd568a22a52ae11724211...6e10a40a058a75d68ed6f233a2a34a112be7633b

**Comment by yuxiangyang1989** [comment]
Redis命令和Redisson对象匹配列表

SELECT ---Config.setDatabase(); 
应该是 Config.useSingleServer().setDatabase()
