### ISSUE TITLE
Clean stale scheduled tasks

### ISSUE THREAD

**Issue by Hronom** [redisson/redisson#1059]
How properly remove stale tasks if my supervisor(who submits tasks) not gracefully exited - crashed.
Workers(redisson nodes) see submited task, executes them and put result back to redis. So after several crashes of supervisor I'v got alot of staled tasks: around 3k. 
So how gracefully handle this? What you would recommend to handle this situation?

I have used [Distributed scheduled executor service](https://github.com/redisson/redisson/wiki/9.-distributed-services#94-distributed-scheduled-executor-service).

**Comment by mrniko** [comment]
I set response queue expiration time to one hour.
