### ISSUE TITLE
"Too many open files" error when running redisson pro in clustered mode.

### ISSUE THREAD

**Issue by jesseeuton** [redisson/redisson#1062]
We are receiving an issue where we start getting the "too many open files" error in production.  This happens roughly 60 minutes after the application is running.

* Ubuntu 16.04.2
* java:
  * OpenJDK 64-bit Server VM (build 15.131-b11, mixed mode)
  * 1.8.0_131
* Redisson Pro v 3.5.3 (also experience this issue in 3.5.1).

We create a singleton (using Guice) that is injected into relevant classes in our application:

`
@Singleton
public class CacheHelper implements ICacheHelper {

    private Boolean useCache;

    public Boolean getUseCache() {
        return useCache;
    }

    public void setUseCache(Boolean useCache) {
        this.useCache = useCache;
    }
    
    private final String redissonKey;
    private final String cacheNodeAddressList;
    private RedissonClient client;

    @Inject
    public  CacheHelper(@Named("cache.enabled") Boolean useCache, @Named("cache.authKey") String redissonKey, @Named("cache.nodeAddressList") String cacheNodeAddressList) {
        this.useCache = useCache;
        this.redissonKey = redissonKey;
        this.cacheNodeAddressList = cacheNodeAddressList;

        //we will not support redis caching on PAM instances, but are designing the cache layer to seamlessly support it in the future.
        if (useCache) {
            client = createClient();
        }
    }

    private RedissonClient createClient() {
        Config config = new Config();

        config.setCodec(new JsonJacksonCodec(getObjectMapper()));
        config.setRegistrationKey(this.redissonKey);
        config.setNettyThreads(16);
        config.setThreads(16);

        //split the injected urls into an array
        String[] nodeAddressArray = cacheNodeAddressList.split(";");

        //configure cluster addresses.
        for (String address : nodeAddressArray) {
            config.useClusterServers()
                    .addNodeAddress(address);
        }

        //create config
        return Redisson.create(config);
    }

    private ObjectMapper getObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();

        mapper.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, true);
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);

        mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        mapper.setVisibility(mapper.getSerializationConfig().getDefaultVisibilityChecker().withFieldVisibility(JsonAutoDetect.Visibility.ANY).withGetterVisibility(JsonAutoDetect.Visibility.NONE).withSetterVisibility(JsonAutoDetect.Visibility.NONE).withCreatorVisibility(JsonAutoDetect.Visibility.NONE));

        mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
        mapper.addMixIn(Throwable.class, JsonJacksonCodec.ThrowableMixIn.class);

        mapper.findAndRegisterModules();
        mapper.registerModule(new JavaTimeModule());

        return mapper;
    }

    public <T extends BaseTimeEntity> RMap<String, T> getMapCache(String mapName) {
        RMap<String, T> map = client.getMapCache(mapName);
        if (map == null) return null;

        return map;
    }

        public <T extends BaseTimeEntity> T getValueFromMap(String mapName, String key) {
        RMap<String, T> map = client.getMapCache(mapName);
        if (map == null) return null;

        return map.get(key);
    }

    public <T> void setMapCache(String mapName, String key, T entity) {
        RMap<String, T> map = client.getMapCache(mapName);
        if (map == null) return;

        map.put(key, entity);
    }

    public <T> void setMapCache(String mapName, String key, T entity, int lifetime, TimeUnit timeUnit) {
        RMapCache<String, T> map = client.getMapCache(mapName);
        if (map == null) return;

        map.fastPut(key, entity, lifetime, timeUnit);
    }

    public <T> void removeKeyFromMapCache(String mapName, String key) {
        RMap<String, T> map = client.getMapCache(mapName);
        if (map == null) return;

        map.fastRemove(key);
    }

    public <T> void replaceMapCacheKeyValue(String mapName, String key, T entity) {
        RMap<String, T> map = client.getMapCache(mapName);
        if (map == null) return;

        map.fastRemove(key);

        map.fastPut(key, entity);
    }

    public <T> T getObject(CacheKeys key) {
        return getObject(key.getValue());
    }

    public <T> T getObject(String key) {
        RBucket<T> bucket = client.getBucket(key);
        if (bucket == null || bucket.size() < 1) {
            return null;
        }

        T value = bucket.get();

        return value;
    }

    public <T> void setObject(CacheKeys key, T object) {
        setObject(key.getValue(), object);
    }

    public <T> void setObject(String key, T object) {
        RBucket<T> bucket = client.getBucket(key);

        if (bucket != null) {
            bucket.set(object);
        }
    }

    public <T> void setObject(CacheKeys key, T object, Long lifetime, TimeUnit timeUnit) {
        setObject(key.getValue(), object, lifetime, timeUnit);
    }

    public <T> void setObject(String key, T object, Long lifetime, TimeUnit timeUnit) {
        RBucket<T> bucket = client.getBucket(key);
        if (bucket != null) {
            bucket.set(object, lifetime, timeUnit);
        }
    }

    public <T> void deleteObject(String key) {
        RBucket<T> bucket = client.getBucket(key);

        if (bucket == null) return;

        bucket.delete();
    }

    @WebApplicationHook(phase = AppPhase.SHUTDOWN)
    public void shutdown() {
        client.shutdown();
    }
}
`

**Comment by jackygurui** [comment]
Can you do a thread dump and also the exception log please?

**Comment by jesseeuton** [comment]
Thread dump:  https://www.dropbox.com/s/g6gse45xqmt4uqz/catalina_thread_dump.zip?dl=0

Full catalina.out (initially empty, captures logs from the start of tomcat until tomcat runs out of file handles):  https://www.dropbox.com/s/v66p9bm2s0lop7w/catalina_out.zip?dl=0

**Comment by mrniko** [comment]
I see a lot of such exceptions:

```
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:500)
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135)
	at com.isonas.controller.readercommunication.IcControllerResponseMsg.getRawByte(IcControllerResponseMsg.java:194)
	at com.isonas.controller.readercommunication.IcControllerResponseMsg.getResponseStart(IcControllerResponseMsg.java:110)
	at com.isonas.controller.readercommunication.IcControllerResponseMsg.<init>(IcControllerResponseMsg.java:32)
	at com.isonas.controller.readercommunication.controller.IsonasController.processResponse(IsonasController.java:63)
	at com.isonas.controller.core.ConnectionValidator.validateConnection(ConnectionValidator.java:177)
	at com.isonas.controller.core.ConnectionValidator.run(ConnectionValidator.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

According to exception:
```
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.$$YJP$$accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept0(ServerSocketChannelImpl.java)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:453)
	at java.lang.Thread.run(Thread.java:748)
```

`Too many open files` problem related to tomcat

**Comment by jesseeuton** [comment]
Those exceptions are expected.  We listen on a particular port for incoming socket connections.  The load balancer probes that port every 10 seconds to ensure it is still open.

We have been running our app in this way for almost a year with no file handle leak issues.

We can turn redisson on\off in our application based on configuration.  When we turn it on the file leak happens within an hour.  When we turn it off we do not see the file handle leak.

**Comment by jackygurui** [comment]
@jesseeuton @mrniko is going to invite you to a private channel for your confidentiality.

**Comment by jesseeuton** [comment]
Another bit of information.  If I set the JVM option -Dio.netty.leakDetection.level=paranoid the leak does not occur.  If I set it to any lower option (advanced, simple, etc) the leak occurs.

**Comment by mrniko** [comment]
@jesseeuton Could you join to our chat? An invitation has been sent on your gmail email
