### ISSUE TITLE
Spring Cache Too Many Eval Calls and not setting TTL on the keys

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#1064]
We are using redisson with spring cache and setting ttl on our keys. The problem is that we are not seeing any ttl being set on any key. Instead, I can see that some unnecessary keys are present in the redis database.

Here is the result of "keys *" command:
redisson__timeout__set:{acl_user_by_userid}"
 3) "redisson__idle__set:{experiment_FG_mapping_by_release_id}"
 4) "redisson__idle__set:{release}"
 5) "acl_user_by_userid"
 6) "redisson__idle__set:{acl_user_by_userid}"
 7) "release"
 8) "redisson__timeout__set:{experiment_FG_mapping_by_release_id}"
 9) "association_by_releaseid"
10) "acl_org_by_id"
11) "redisson__timeout__set:{business_rules}"
12) "redisson__timeout__set:{acl_org_by_id}"
13) "redisson__timeout__set:{association_by_releaseid}"
14) "business_rules"
15) "redisson__idle__set:{association_by_releaseid}"
16) "redisson__timeout__set:{acl_org_roles_for_user}"
17) "redisson__idle__set:{acl_org_roles_for_user}"
18) "redisson__idle__set:{acl_org_by_id}"
19) "redisson__timeout__set:{release}"

You can see that for a key "release", the redisson creates two more keys "redisson__timeout__set:{release}" and "redisson__idle__set:{release}". Also, there is no ttl present on key "release".

My code is :
 private Map<String, CacheConfig> getCacheConfigs() {
        Map<String, CacheConfig> cacheConfigs = new HashMap<>();
        //Set the ttl in miliseconds
       
        cacheConfigs.put(CACHE_NAME_RELEASE, new CacheConfig(ONE_DAY, ONE_DAY));
        ...
.       ....
       .....
       return cacheConfigs;
    }

    @Bean
    public CacheManager cacheManager() {
        CacheManager cacheManager = new RedissonSpringCacheManager(redissonClient(), getCacheConfigs());
        return cacheManager;
    }

We are using caching here:
    @Override
    @Cacheable(cacheNames = CACHE_NAME_RELEASE, key = "#releaseId", unless = "#result == null")
    public ReleaseQO getReleaseById(Integer releaseId) {
        // Some Code
    }

I can see that redisson is internally using lua scripts for managing the ttl from client side:

(EVAL) with params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 3, client_pv, redisson__timeout__set:{client_pv}, redisson__idle__set:{client_pv}, 1505747133337, pc_KCCC_pv_4.2]

Info commandstats gives me the following result:
info commandstats
# Commandstats
cmdstat_get:calls=16257,usec=43644,usec_per_call=2.68
cmdstat_set:calls=367,usec=2267,usec_per_call=6.18
cmdstat_del:calls=163442,usec=1926658,usec_per_call=11.79
cmdstat_zadd:calls=112389614,usec=489906259,usec_per_call=4.36
cmdstat_zrem:calls=584488,usec=1861150,usec_per_call=3.18
cmdstat_zrange:calls=3,usec=12,usec_per_call=4.00
**cmdstat_zrangebyscore:calls=1086546,usec=4011007,usec_per_call=3.69
cmdstat_zscore:calls=220466356,usec=945053083,usec_per_call=4.29**
cmdstat_hset:calls=111150865,usec=167392674,usec_per_call=1.51
cmdstat_hget:calls=113042156,usec=231292617,usec_per_call=2.05
cmdstat_hdel:calls=295601,usec=668863,usec_per_call=2.26
cmdstat_hlen:calls=5,usec=6,usec_per_call=1.20
cmdstat_hgetall:calls=559,usec=4265,usec_per_call=7.63
cmdstat_hexists:calls=5,usec=9,usec_per_call=1.80
cmdstat_hscan:calls=1,usec=17,usec_per_call=17.00
cmdstat_select:calls=2,usec=2,usec_per_call=1.00
cmdstat_expire:calls=300847,usec=552356,usec_per_call=1.84
cmdstat_keys:calls=313,usec=191647,usec_per_call=612.29
cmdstat_ping:calls=3936569,usec=4360878,usec_per_call=1.11
cmdstat_psync:calls=12,usec=1602,usec_per_call=133.50
cmdstat_replconf:calls=15624259,usec=19486629,usec_per_call=1.25
cmdstat_flushall:calls=69,usec=98473,usec_per_call=1427.14
cmdstat_info:calls=6551875,usec=459090708,usec_per_call=70.07
cmdstat_ttl:calls=4,usec=18,usec_per_call=4.50
cmdstat_pttl:calls=1,usec=2,usec_per_call=2.00
cmdstat_slaveof:calls=1,usec=142,usec_per_call=142.00
cmdstat_config:calls=1571031,usec=30747726,usec_per_call=19.57
cmdstat_publish:calls=1833889,usec=595647,usec_per_call=0.32
cmdstat_client:calls=130970,usec=38079168,usec_per_call=290.75
**cmdstat_eval:calls=113372429,usec=5402870353,usec_per_call=47.66**
cmdstat_command:calls=37,usec=16061,usec_per_call=434.08

We are not using zset and eval commands. But, still the use of these calls are too high from redisson.

Also, I have see that there are almost ~4M sortedSetTypeCommands on the redis cluster from redisson under our peak load which is degrading our performance.

I want to know why redisson is not setting ttl on the key and managing it using sorted sets on the client side. It is not advisable to do it on the client side if the server automatically gives that feature.

Is there any way to disable this ttl management from redisson so that it will just set that on the redis server and these calls are not fired.

PS: We are using AWS elasticache redis server. 

Redisson version: 3.4.2
Redis Version: 3.2.4 with 1 master and 3 slaves.

**Comment by namit081** [comment]
👍

**Comment by mrniko** [comment]
Hi!

Redisson Spring Cache based on MapCache object. This object uses zset Redis objects to track ttl and idle time for each entry in map with prefix names like `redisson__idle__set` and `redisson__timeout__set`. Spring Cache applies ttl to each entry and not whole Spring Cache instance. This is why ttl not set for object.

**Comment by mrniko** [comment]
As workaround to scale eviction process I would recommend you to use Spring Cache with Data Partitioning support. Here the [docs](https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks/#1422-spring-cache-data-partitioning). Since it splits cache to shards this allows to scale eviction process

**Comment by Himanshu4** [comment]
Spring cache applies ttl for the cache_name and not each entry. Suppose if a Hash with name "release" where release have multiple keys "1", "2" and "3". Then spring cache applies ttl (say 24 hours) to "release" only. I think redis allows setting ttl to a hash.

We were using jedis earlier and it creates hash with the above keys and sets ttl to that hash.

Why redisson is not doing so? That way, redisson can reduce a lot of commands on the redis server. The reason I am asking is that we are getting too many redis connection timeouts due to heavy usage of sorted commands and Redis transactions (eval). Since we have already given 25% of max memory to redis (for reserved-memory), I think redis will automatically expire keys in the background when it has enough resources.


Is there a way where you can provide a way to disable this so that we can test out its impact on our performance.

**Comment by mrniko** [comment]
@Himanshu4 

You're right expiration could be applied to whole object rather than each entry.
How about MaxIdleTimeout parameter? Redis unable to provide a way to setup it.

**Comment by Himanshu4** [comment]
@mrniko : What is the maxIdleTimeout Parameter? 
If by "maxIdleTimeout", you mean the maximum idle time the key is present in redis before it is evicted. Then, here you can read about the different policies about how eviction works in redis. 

https://redis.io/topics/lru-cache

That way, the keys will be deleted automatically after sometime (before OOM) even if it stays idle for a period.

**Comment by mrniko** [comment]
@Himanshu4 

Also with your solution TTL won't account each entry only whole cache. In this case no matter when entry has been created it's life time limited by remain time of whole cache object and not individual ttl.

**Comment by mrniko** [comment]
@Himanshu4 

I think spring cache is not the only feature that Redisson used for. Redis builtin Lru-cache evicts all objects and I would able to evict Spring Cache object only, for example.

**Comment by Himanshu4** [comment]
Redis built in cache does not evict all objects. It evicts objects based on the expiry policy applied. 

IF you can set the expiry of the keys (hash names) on the redis, it would be helpful since we want to test the impact on the performance after disabling the ttl management of the redisson.

Also, I am still not convinced why the client has to manage the expiry by itself when the server is already providing it.

Another reason is that the scheduler "org.redisson.eviction.EvictionScheduler" is being run from all the machines and evicting the keys. That is not desirable since the redis server is single threaded. It will increase the number of request / queries on the redis without the application doing anything.

The application should have a way of choosing b/w the two modes so that it has a way to optimize itself.

**Comment by jackygurui** [comment]
@Himanshu4 Redis doesn't provide expiry on individual element inside a collection(hash,set, zset, list) hence why Redisson has to do it itself.

**Comment by Himanshu4** [comment]
Jedis gives an option to go about this by this code:

@Bean
    public CacheManager cacheManager() {
        RedisCacheManager cacheManager = new RedisCacheManager(redisTemplate());
        cacheManager.setExpires(getExpiryTime());
        //Will create the key in format "cachename ~ keyname"
        cacheManager.setUsePrefix(true);
        cacheManager.afterPropertiesSet();
        return cacheManager;
    }

Here the cache keys are converted to simple keys.

The sample snapshot would yield :
redis 127.0.0.1:6379> keys *
1) "aclrole:2"
2) "client:2"
3) "client:1"
4) "aclrole:3"
5) "all_releases:ALL"
6) "acluser_with_role:userid_ukExZTfcqeHWWYi84cpo@AdobeID"
7) "aclrole:1"

Redisson should also provide a way like above and let the TTL handling to the server itself. The application should never handle this logic.

**Comment by Himanshu4** [comment]
@jackygurui : Also, even if the keys are stored in a hash, the better way would be to create a hash and set the expiry on the whole hash. Since we are setting the expiry on the whole hash here:

        private Map<String, CacheConfig> getCacheConfigs() {
        Map<String, CacheConfig> cacheConfigs = new HashMap<>();
        //Set the ttl in miliseconds

    cacheConfigs.put(CACHE_NAME_RELEASE, new CacheConfig(ONE_DAY, ONE_DAY));
    ...
. ....
.....
return cacheConfigs;
}

We are never setting the cache expiry on individual keys. Redisson should also set the ttl on whole hash when it was created and let the redis handle all the expiration logic.

**Comment by jackygurui** [comment]
@Himanshu4 I understand RedisTemplate has taken a different approach, and there are pros and cons with both ways.

Using flat map is simpler to implement by letting redis do the expiring, however the problem that comes with this approach is it uses more memory that storing with hash, and also you can't specify eviction strategy against each cache registry. When you have multiple cache registries form different types applications, letting Redis to perform LFU or LRU invalidation, you may end up with unexpected behaviours from different application's perspective.

Redisson's approach is obviously more complex on client side but it gives us the ability to manage different cache registry in a collective manner while keeping memory usage as small as possible. With recently implemented the LRU / LFU eviction policy on MapCache objects gives us the ability to control the eviction on individual registries, this option is going to be exposed to spring cache implementations soon.

**Comment by namit081** [comment]
@jackygurui @mrniko We have been using redisson as well and facing a similar issue. Our service is making unnecessary calls to Redis and increasing the load even though it's not required.

Does redisson allow clients to configure the interval in which EvictionScheduler runs? I believe this can greatly help in reducing the load on Redis.

**Comment by jackygurui** [comment]
You should not consider the EvictionScheduler to be something evil and the high usage of EVAL command is normal.

EvictionScheduler works similarly to the internal eviction strategy employed in Redis, that is having an extra thread, run around every now and then to look for things that is expired, if it has found some, remove it, if not, come back another time. Redis internally is devoting certain amount of time every second running the eviction on the main thread which is not processing commands, so the side effect of client side eviction is not as severe as it is seemed to. Redisson, on the other hand, runs the eviction process far less frequent than Redis by default, interval expands from 1 second to upto 2 hours. The [documentation about map eviction](https://github.com/redisson/redisson/wiki/7.-distributed-collections#711-map-eviction) has more detail on how often it runs. 

EVAL command is used extensively through out Redisson simply because we need to ensure a group of commands can be executed atomically. At the end of the day, Redisson has provided 40+ different objects and services that are not available in vanilla Redis or any other clients.

**Comment by mrniko** [comment]
@Himanshu4 

I improved MapCacheEvictionTask now it runs once a period of time. Could you please try it?

**Comment by Himanshu4** [comment]
@jackygurui : The things you have mentioned are from the perspective of proving benefits of redisson. 

As I have already stated, 
1. The spring cache is also not allowing us to set the expiry on individual keys. It is allowing us to set expiry on the whole cache_name (hash in case of redisson). 
2. I have not come across any redis client which is doing the expiry handling on the client side. 

I suggest that Redisson should also provide a way( at least an alternative) of turning off this execution scheduler and let the redis handle the expiry.
e.g. jedis has 
        //Will create the key in format "cachename ~ keyname"
         cacheManager.setUsePrefix(true);

This config allows us to configure the way the keys are stored in redis.

Some configuration should be made available to the clients to turn on/off the behaviour.

**Comment by Himanshu4** [comment]
I appreciate the fact that redisson is providing a lot of different objects and services. But, the library should not deviate from the original model (both spring cache and redis). It should allow the client to configure b/w different options.

Cheers!

**Comment by mrniko** [comment]
You can use RedissonSpringCacheV2Manager provided by [PRO](https://redisson.pro) version.

**Comment by abdulwahidpanaroma** [comment]
@Himanshu4  hi .. is this issue fixed ?
