### ISSUE TITLE
Bogus map entries in RMapCache

### ISSUE THREAD

**Issue by asaf-romano** [redisson/redisson#1072]
Using version 3.5.0, we've noticed a very strange behavior in RMapCache map-iteration APIs (keySet,  entrySet, etc). It seems that the map sometimes contains "inverted" entries in which the key looks like a (bogus) instance produced by a value encoder, and the value looks like an (again) bogus instance produced by the key encoder*. When they do, these entries show *alongside* the normal entries. It's only because of Type Erasure that the code doesn't break until one actually calls an iterartion API: Because the original entries are still in place, get, put, etc. works as expected even when the map is in this broken state. We've managed to workaround this issue by using readAllKeys rather than keySet.

_____
* We have a custom extremely type-aware jackson-based codec, which makes this bug very easy to spot.

**Comment by mrniko** [comment]
Could you provide any test case to reproduce it?

**Comment by asaf-romano** [comment]
It has the characteristics of a race condition, so it's going to be hard to provide a test case here. We don't do anything special: it's a RMapCache in which values are put with a 3-hour TTL, bound to a jackson-based codec in which the keyEncoder is set to a specific type, and the valueEncoder is set to some other type (using readValue(v, TypeReference> and writerForType). The map entries are read using keySet in a periodic task running once a minute. Values are written from multiple processes, but keySet is used only in one of those processes.

**Comment by mrniko** [comment]
Unable to reproduce
