### ISSUE TITLE
RedissonSpringCacheManager does not take into account default cache config parameters.

### ISSUE THREAD

**Issue by AliasVector** [redisson/redisson#1073]
Hello, seems there is some tricky code which creates the wrong type of cache map.
RedissonSpringCacheManager has the protected method: 
`protected CacheConfig createDefaultConfig() {
        return new CacheConfig();
    }`

This is a protected method, so it can be overriden, but in the method:
`public Cache getCache(String name) {
        Cache cache = instanceMap.get(name);
        if (cache != null) {
            return cache;
        }
        if (!dynamic) {
            return cache;
        }
        
        CacheConfig config = configMap.get(name);
        if (config == null) {
            config = createDefaultConfig();
            configMap.put(name, config);
            // Here it is not analysed the ttl nor max idle time params of the default config.
            // seems this return must be omitted to let the further code check the values in
            // default config is case if the createDefaultConfig() was overriden
            return createMap(name, config);
        }
        
        if (config.getMaxIdleTime() == 0 && config.getTTL() == 0) {
            return createMap(name, config);
        }
        
        return createMapCache(name, config);
    }`

Also it would be really great to have an ability to set ttl and max idle time by default for all caches.

**Comment by maledeity** [comment]
How can RMap be converted into RMapCache?

**Comment by mrniko** [comment]
@maledeity RMapCache extends RMap
