### ISSUE TITLE
UI - Project Dashboard 

### ISSUE THREAD

**Issue by rakeshbena** [redisson/redisson#1074]
### OS - macOS Sierra 10.12.6

**Issue 1**

**Description** Labels are repeated twice in the column headers.

**Steps to Reproduce**
 1: Open the web application beta.lilt.com and login with authorized credentials.
 2: In the project dashboard page, click on any project and enter to the document select page.
 3: In this observe that header labels are repeated twice for **Translation** and **Review**

**Observation** Observed that  header labels are showing twice

![image](https://user-images.githubusercontent.com/31950827/30801748-dbe7b3b0-a201-11e7-8f07-5a2d7031f38b.png)

**Comment by jackygurui** [comment]
I am sure this isn't related to Redisson project in any way.
