### ISSUE TITLE
Implement proper RedisLoadingException handling during RedisClient reconnection

### ISSUE THREAD

**Issue by valodzka** [redisson/redisson#1075]
Code:

    // redisson 3.5.3
    //  <logger name="org.redisson" level="TRACE"/>
    // config.useSingleServer().setClientName("local-u0")
    RPatternTopic<String> patternTopic = c.getPatternTopic("*", new StringCodec());

    patternTopic.addListener((pattern, channel, msg) -> {
         System.err.println(pattern + ", " + channel + ", " +msg);
    });

Test

    redis-cli PUBLISH aaa 111 # works

Restart redis, log https://gist.github.com/valodzka/5fe65c7cb8cf66747b2850a6601d50c3
Test again:

     redis-cli PUBLISH aaa 111 # never works

**Comment by mrniko** [comment]
According to your log the problem has not been reconnected at all due to long Redis data loading process.

**Comment by valodzka** [comment]
It is bug or function as designed that reconnect/resubscribe never happens (even after redis finish loading)?

**Comment by mrniko** [comment]
Fixed!
