### ISSUE TITLE
RedisConnection can not close

### ISSUE THREAD

**Issue by featherfly** [redisson/redisson#1076]
final RedisClient client = RedisClient.create(clientConfig);
final RedisConnection con = client.connect();
con.closeAsync().addListener(l -> {
            client.shutdownAsync().addListener(cl -> {
                showThreas();
            });
        });

threads info
name - id - state - daemon
Reference Handler - 2 - WAITING - true
Finalizer - 3 - WAITING - true
Signal Dispatcher - 4 - RUNNABLE - true
Attach Listener - 5 - RUNNABLE - true
nioEventLoopGroup-2-1 - 12 - RUNNABLE - false
DestroyJavaVM - 13 - RUNNABLE - false
nioEventLoopGroup-2-2 - 14 - RUNNABLE - false
threadDeathWatcher-3-1 - 15 - TIMED_WAITING - true
nioEventLoopGroup-2-3 - 16 - RUNNABLE - false
ForkJoinPool.commonPool-worker-1 - 17 - TIMED_WAITING - true
globalEventExecutor-1-1 - 18 - RUNNABLE - false

**Comment by nousxiong** [comment]
Bcz RedisClient.hasOwnGroup always == false --> using RedisClient.create(clientConfig); to create RedisClient;

temp fix way: 

final RedisClient client = RedisClient.create(clientConfig);
...
client.shutdown()
clientConfig.timer.stop()
clientConfig.group.shutdownGracefully()

done.

**Comment by mrniko** [comment]
Fixed! @featherfly @nousxiong thanks for report!
