### ISSUE TITLE
RedissonClient with useSentinelServers cannot reconnect resurected slave

### ISSUE THREAD

**Issue by xavierfacq** [redisson/redisson#1077]
Hi,

I'm testing the useSentinelServers connexion. I have 1 master and 1 slave.
If I kill the slave, wait and then restart it, I have the folowing trace in the Tomcat console when
calling redisson.getNodesGroup().getNodes().

```
GRAVE: org.redisson.client.RedisConnectionException: Can't aquire connection to [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@5f8198cc, freeConnectionsAmount=0, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@37aac6d8, freezed=true, freezeReason=SYSTEM, client=[addr=/172.16.50.12:6380], nodeType=SLAVE, failedAttempts=0]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:206)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.getConnection(LoadBalancerManager.java:197)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:431)

```

If I look at the Redisson ConnectionPool.java, I see that the method will never retry a connexion on a freezed slave : 

```
 public  RFuture<T> get(RedisCommand<?> command, ClientConnectionsEntry entry) {
        if (((entry.getNodeType() == NodeType.MASTER && entry.getFreezeReason() == FreezeReason.SYSTEM) || !entry.isFreezed())
                && tryAcquireConnection(entry)) {
            return acquireConnection(command, entry);
        }

        RedisConnectionException exception = new RedisConnectionException(
                "Can't aquire connection to " + entry.getClient().getAddr());
        return connectionManager.newFailedFuture(exception);
    }

```

Question : How can I get Redisson to reconnect the resurected slave ?

My conf:

```
				Config config = new Config();
				config.useSentinelServers()
					.setTimeout(timeout)
					.setConnectTimeout(timeout)
					.setReadMode(ReadMode.SLAVE)
					.setMasterName("MCACHEREDISIMPL")
					.setMasterConnectionPoolSize(20)
					.setMasterConnectionMinimumIdleSize(1)				    
					.setSlaveConnectionPoolSize(20)
					.setSlaveConnectionMinimumIdleSize(1)				    
					.setIdleConnectionTimeout(5000)
					.setReconnectionTimeout(3000)
					.addSentinelAddress(Iterables.toArray(sentinels, String.class));

```

thx,
Xavier

**Comment by mrniko** [comment]
Hi,

Resurrected slave is automatically discovered when Redisson got slave-up event from Sentinel node

**Comment by xavierfacq** [comment]
Hi @mrniko 

Thank you for your answer but I don't have this behavior, may be something is not well configured...

JDK8, Redisson 3.5.3, Redir server  3.2.3, Tomcat 7. I have 1 master and 1 slave, 1 sentinel (testing)

My tomcat is running, when I kill the slave I see in the sentinel log:

`2641:X 27 Sep 16:14:01.580 # +sdown slave 172.16.50.12:6380 172.16.50.12 6380 @ MCACHEREDISIMPL 172.16.50.12 6379`

After a while I restart the slave

```
2641:X 27 Sep 16:16:01.238 * +reboot slave 172.16.50.12:6380 172.16.50.12 6380 @ MCACHEREDISIMPL 172.16.50.12 6379
2641:X 27 Sep 16:16:01.277 # -sdown slave 172.16.50.12:6380 172.16.50.12 6380 @ MCACHEREDISIMPL 172.16.50.12 6379
```
Seems ok.

In my tomcat, I can wait as long as I want, I always have the error message using this code:

`redisson.getNodesGroup().getNodes()
`

got:

`GRAVE: org.redisson.client.RedisConnectionException: Can't aquire connection to [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@214a0365, freeConnectionsAmount=0, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@64489928, freezed=true, freezeReason=SYSTEM, client=[addr=/172.16.50.12:6380], nodeType=SLAVE, failedAttempts=0]
`
Any suggestion will be appreciated

**Comment by xavierfacq** [comment]
The full stack

```
GRAVE: org.redisson.client.RedisConnectionException: Can't aquire connection to [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@214a0365, freeConnectionsAmount=0, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@64489928, freezed=true, freezeReason=SYSTEM, client=[addr=/172.16.50.12:6380], nodeType=SLAVE, failedAttempts=0]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:206)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.getConnection(LoadBalancerManager.java:197)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:431)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:742)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:504)
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:585)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by mrniko** [comment]
There are should be at least two Sentinel nodes

**Comment by xavierfacq** [comment]
I have tried 1 master + 1 node + 2 sentinels monitoring,  but the problem is the same. 
Resurrected slave stays not connected. For me, the ConnexionPool will call tryAcquireConnection()
only for (MASTER + SYSTEM). But not for (SLAVE + SYSTEM).

`GRAVE: org.redisson.client.RedisConnectionException: Can't aquire connection to [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@77620bb7, freeConnectionsAmount=0, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@735d8183, freezed=true, freezeReason=SYSTEM, client=[addr=/172.16.50.12:6380], nodeType=SLAVE, failedAttempts=0]
`


With code is 
`(entry.getNodeType() == NodeType.MASTER && entry.getFreezeReason() == FreezeReason.SYSTEM)`

Another suggestion ?
