### ISSUE TITLE
Many invocations of getEntry and getClient

### ISSUE THREAD

**Issue by rexave** [redisson/redisson#1081]
Hello,

We have performance issue in `org.redisson.connection.MasterSlaveConnectionManager#getEntry(java.net.InetSocketAddress)` 

We did profile the JVM to see what's happening and we have a lot's of invocations in this method.

![image](https://user-images.githubusercontent.com/2827401/31068269-917b0bbe-a757-11e7-9cc8-e914b934069b.png)

While looking at the code, we found a "TODO OPTIMIZE" at the place we have performance issue :) 
https://github.com/redisson/redisson/blob/99827db2f0ec5597efff73283b46b81f0f761ada/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L675

Is there an optimization planned on this part of the lib soon ? Do you have any workaround to fix this ?

Thanks !

**Comment by mrniko** [comment]
Fixed

**Comment by rexave** [comment]
Great ! Thanks for the fast fix.
We produced this test on a standalone server but we planned to use more than 3 nodes.
We'll test the fix asap and let you know.
Do you know when the next release is planned ?

**Comment by rexave** [comment]
We patched the lib with your fix and it's working MUCH faster ! (more than 1000x faster)
Thanks again for the fast fix. Please let me know when you plan the next release.

**Comment by mrniko** [comment]
@rexave It's a great news! I'll publish next release during a week or so.
