### ISSUE TITLE
RLocalCachedMap 

### ISSUE THREAD

**Issue by srvanukuri** [redisson/redisson#1091]
Hi,

I have very large objects that are hard to serialize, so opted for RLocalCachedMap with eviction policy as LRU and Invalidation policy on change. I notice that when I add key, value to the map, both key and value are serialized sent to redis server in serialized format often resulting in errors. Is there any way to preserve the eviction and invalidation and not send the value to redis server with serialization.

`initializeNetworkCache();
		long sTime = System.currentTimeMillis();
		LocalCachedMapOptions options = LocalCachedMapOptions.defaults()
			      // LFU, LRU, SOFT, WEAK and NONE policies are available
			     .evictionPolicy(EvictionPolicy.LRU)
			      // If cache size is 0 then local cache is unbounded.
			     .cacheSize(1000)
			      // if value is `ON_CHANGE`, `ON_CHANGE_WITH_CLEAR_ON_RECONNECT` or `ON_CHANGE_WITH_LOAD_ON_RECONNECT` 
			      // corresponding map entry is removed from cache across all RLocalCachedMap instances 
			      // during every invalidation message sent on each map entry update/remove operation
			     .invalidationPolicy(InvalidationPolicy.ON_CHANGE)
			     // max idle time for each map entry in local cache
			     .maxIdle(10, TimeUnit.MINUTES)
			      // time to live for each map entry in local cache
//			     .timeToLive(10000)
			      // or
			     .timeToLive(2, TimeUnit.HOURS);
			      // max idle time for each map entry in local cache
		RLocalCachedMap<String, List<String>> m = cacheClient.getLocalCachedMap("localMap", options);
		
		List<String> l = new ArrayList<String>();
		l.add("one");
		l.add("two");
		m.put("k1", l);
		
		m.remove("k1");
		cacheClient.shutdown();`

From redis monitor
-------------------
1507592155.240247 [0 172.17.0.1:56610] "SUBSCRIBE" "{localMap}:topic"
1507592155.281269 [0 172.17.0.1:56604] "EVAL" "local v = redis.call('hget', KEYS[1], ARGV[1]); if redis.call('hset', KEYS[1], ARGV[1], ARGV[2]) == 0 then if ARGV[4] == '1' then redis.call('publish', KEYS[2], ARGV[3]); end;if ARGV[4] == '2' then redis.call('zadd', KEYS[3], ARGV[5], ARGV[6]);redis.call('publish', KEYS[2], ARGV[3]); end;end; return v; " "3" "localMap" "{localMap}:topic" "redisson__cache_updates_log:{localMap}" "\"k1\"" "[\"java.util.ArrayList\",[\"one\",\"two\"]]" "{\"@class\":\"org.redisson.cache.LocalCachedMapInvalidate\",\"excludedId\":\"WafQgVF3KraC2OpfcpRcDg==\",\"keyHashes\":[\"0BYDzEh2fI8Kf2PGRxfrdQ==\"]}" "1" "1507592155273" "\xd0\x16\x03\xccHv|\x8f\n\x7fc\xc6G\x17\xebu:\xbb\xd7\x9dY\xd4R\xc4f"
1507592155.281378 [0 lua] "hget" "localMap" "\"k1\""
1507592155.281387 [0 lua] "hset" "localMap" "\"k1\"" "[\"java.util.ArrayList\",[\"one\",\"two\"]]"
1507592155.284735 [0 172.17.0.1:56606] "EVAL" "local v = redis.call('hget', KEYS[1], ARGV[1]); if redis.call('hdel', KEYS[1], ARGV[1]) == 1 then if ARGV[3] == '1' then redis.call('publish', KEYS[2], ARGV[2]); end; if ARGV[3] == '2' then redis.call('zadd', KEYS[3], ARGV[4], ARGV[5]);redis.call('publish', KEYS[2], ARGV[2]); end;end; return v" "3" "localMap" "{localMap}:topic" "redisson__cache_updates_log:{localMap}" "\"k1\"" "{\"@class\":\"org.redisson.cache.LocalCachedMapInvalidate\",\"excludedId\":\"WafQgVF3KraC2OpfcpRcDg==\",\"keyHashes\":[\"0BYDzEh2fI8Kf2PGRxfrdQ==\"]}" "1" "1507592155283" "\xd0\x16\x03\xccHv|\x8f\n\x7fc\xc6G\x17\xebu:\x10_\x15\xfde\xce\xc2\xb0"
1507592155.284837 [0 lua] "hget" "localMap" "\"k1\""
1507592155.284857 [0 lua] "hdel" "localMap" "\"k1\""
1507592155.284863 [0 lua] "publish" "{localMap}:topic" "{\"@class\":\"org.redisson.cache.LocalCachedMapInvalidate\",\"excludedId\":\"WafQgVF3KraC2OpfcpRcDg==\",\"keyHashes\":[\"0BYDzEh2fI8Kf2PGRxfrdQ==\"]}"

**Comment by mrniko** [comment]
Hi,

> I notice that when I add key, value to the map, both key and value are serialized sent to redis server in serialized format often resulting in errors

Have you tried another codec, like FST?

> Is there any way to preserve the eviction and invalidation and not send the value to redis server with serialization

What is the point to use LocalCachedMap then? You could you use simple Map object

**Comment by srvanukuri** [comment]
Thanks for the quick response.

Have you tried another codec, like FST?

I tried Kryo and FST. I spent a decent amount of time on Kryo, it often
errors out with stack over flow and moderate success in increasing the
stack size.  FST also errors out as some of the classes from libraries are
non serializable and final..

What is the point to use LocalCachedMap then? You could you use simple Map
object

The simple Map object doesn't have the invalidation on other servers in
cluster. I thought, I could use the auto invalidation with pub-sub from
LocalCachedMap. Is there any reason why the values need to be sent to redis
server instead of just keys for LocalCachedMap.
