### ISSUE TITLE
RedissonBlockingQueue.take() returns null in case of internal error

### ISSUE THREAD

**Issue by 0x0000-dot-ru** [redisson/redisson#1096]
The take() method in RedissonBlockingQueue uses Future.getNow(), which returns null if an exception occurs. In our case, we have tons of NPEs when the application is stopped.

**Comment by mrniko** [comment]
What does queue consists of? Number?

**Comment by 0x0000-dot-ru** [comment]
We use POJO in the queue.

**Comment by stfnio** [comment]
I think @0x0000-dot-ru meant 'which returns null if an exception occurs'

**Comment by 0x0000-dot-ru** [comment]
Thank you @stfnio, that's what I meant. I fixed the post.

**Comment by mrniko** [comment]
Fixed
