### ISSUE TITLE
Connection Count in Redis Servers increases when Failover happens

### ISSUE THREAD

**Issue by madhawas1** [redisson/redisson#1097]
I am using redisson 2.8.2 with Java 1.7 and redis in Cluster mode. Recently we had an incident related to connection count of redis servers. After further investigation we have found that after each redis failover, connection count from each client to redis servers get increased and not going back to the earlier values. This happens after each failover in the redis servers whose role got change. 

Then eventually connection count reaches maximum connection count and application goes to a freeze state.

**Comment by madhawas1** [comment]
@mrniko Cloud you please check this and let me know a possible way to avoid this behaviour.

**Comment by mrniko** [comment]
Let me reproduce it

**Comment by mrniko** [comment]
Unable to reproduce it with 2.8.2 version. Below is my test:

```java
    @Test
    public void testReconnectionInCluster() throws Exception {
          Config config = new Config();
          config.useClusterServers()
          .setRetryAttempts(100)
          .addNodeAddress("127.0.0.1:7001")
          .setMasterConnectionMinimumIdleSize(1)
          .setMasterConnectionPoolSize(1)
          .setSlaveConnectionMinimumIdleSize(1)
          .setSlaveConnectionPoolSize(1);
          RedissonClient redisson = Redisson.create(config);
        
          int j = 0;
        while (true) {
            for (int i = 0; i < 100; i++) {
                try {
                    redisson.getBucket("" + i).set(i);
                } catch (RedisTimeoutException e) {
                    System.err.println(e);
                    // skip
                }
            }
            System.out.println("iteration " + j++);
        }
    }
```
Cluster configuration
```
050aea792057c134ae04250883ed4053d55cd1c8 127.0.0.1:7004 slave a82f3ed12dbe58ba2ec244648fcb478a689e1b4a 0 1509023644232 3 connected
a82f3ed12dbe58ba2ec244648fcb478a689e1b4a 127.0.0.1:7003 master - 0 1509023645231 3 connected 10923-16383
13276f5986b141e0d4d30d42aaf5bdc9c1fe3aca 127.0.0.1:7006 slave 5dd63102450289910ca7afaaa6114d5fa92f2c90 0 1509023645231 3 connected
97e8486468b02e87956d79fd1ffe1d05e15fa41a 127.0.0.1:7005 slave b62d4066c8101ea4ad09211903af9ab87c727cd6 0 1509023643628 2 connected
b62d4066c8101ea4ad09211903af9ab87c727cd6 127.0.0.1:7001 myself,master - 0 0 1 connected 0-5460
5dd63102450289910ca7afaaa6114d5fa92f2c90 127.0.0.1:7002 master - 0 1509023644430 2 connected 5461-10922
vars currentEpoch 23 lastVoteEpoch 0
```

To reproduce your case I stopped `127.0.0.1:7003` and waited for failover to `127.0.0.1:7004`. I waited for few minutes in current loop. Then I started `127.0.0.1:7003` again and it had been added as slave into cluster. I stopped `127.0.0.1:7004` and waited for failover to `127.0.0.1:7003`. And did it more than ten times. Finally, I didn't get out of connection problem.
