### ISSUE TITLE
启动报Not all slots are covered! Only 10923 slots are avaliable

### ISSUE THREAD

**Issue by felix-laofan** [redisson/redisson#1099]
在集群模式下。偶尔会报Not all slots are covered! Only 10923 slots are avaliable。
通过redis查看。  redis是没有问题的。经过不断的排查。后面发现原来跟serverConfig.addNodeAddress("redis://192.168.0.208:7000","redis://192.168.0.208:7004","redis://192.168.0.208:7003","redis://192.168.0.208:7005","redis://192.168.0.208:7001","redis://192.168.0.208:7002");添加节点地址的顺序有关。我个是三主三从。如果你前面三个全部是主或者全部是从。就会把我上面说的哪种错。

**Comment by liuzhaozhao** [comment]
应该跟顺序没关系，我也是集群三主三从，有可能确实是某个范围的solt的主从节点访问不了

**Comment by jackygurui** [comment]
这是集群的问题，不是Redisson的问题

**Comment by caochenhins** [comment]
确实是和顺序有关,  太奇葩了 ,学习了  谢谢楼主的解决思路
