### ISSUE TITLE
集群模式下针对某次get可以使用主节点读取

### ISSUE THREAD

**Issue by liuzhaozhao** [redisson/redisson#1101]
不好意思，英文不太好，刚过3级
......
RBucket<String> bucket = redisson.getBucket("mykey");
bucket.get();
.....
上面的get读取的主从只能使用readmodel做全局设置，
但是我有场景，在设置完后需要立即读取，主从同步会有延迟，可能导致读不到，
后续是否会考虑针对某次get做主从切换

**Comment by jackygurui** [comment]
前不久增加了wait命令的支持，你可以用这个命令保证从收到同步信息

**Comment by liuzhaozhao** [comment]
好的，多谢

**Comment by liuzhaozhao** [comment]
刚想到一个好的方式，生成两个RedissonClient实例，一个全局设置readmodel=SLAVE，一个全局设置readmodel=MASTER，然后应用内做主从读写区分
