### ISSUE TITLE
Making redisson operation atomic

### ISSUE THREAD

**Issue by Rowen123** [redisson/redisson#1103]
Hi, i have a usecase that i'm trying to implement using redisson. I have 2 redisson instances running on the same server performing the same operation. 
Code snippet of redisson instance 1:
```
Config config = Config.fromJSON(new File("//home//user//SingleNodeConfig.json"));
		RedissonClient redisson = Redisson.create(config);
		
		RMap<String,String> map = redisson.getMap("map");
		map.put("key1", "value1");
```

Code snippet of redisson instance 2:
```
Config config = Config.fromJSON(new File("//home//user//SingleNodeConfig.json"));
		RedissonClient redisson = Redisson.create(config);
		
		RMap<String,String> map = redisson.getMap("map");
		map.put("key1", "value2");
```

My use case is this: At an instant of time both the instances could access the same key and update its value twice. I want to restrict this i.e., if both instances are accessing the same key at the same time, only one update should occur and not both.

My question is this, which would be the best locking mechanism to deal with this or should i handle this on my own???

**Comment by jackygurui** [comment]
First of all the situation you described is not an atomic operation issue. Your instance1 and instance2 both have atomic access to the same field `key1` and that is guaranteed by the underlying Redis.

The use case you described requires a CAS operation, which you can do so using `putIfAbsent` from RMap
