### ISSUE TITLE
集群模式下，readMode=slave，在从节点断开又恢复后读操作不会自动转到从节点

### ISSUE THREAD

**Issue by liuzhaozhao** [redisson/redisson#1106]
测试环境：3主3从，key值为b的数据存在A主节点及D从节点，客户端单线程循环读取key值为b的数据（读取做了异常捕获）

很短时间关闭D从节点再启动，客户端会短时间等待后，继续从D从节点取数据；

稍微长时间关闭D从节点再启动（超过重试时间），客户端在等待超时异常后，继续从A主节点读取数据，后续时间重启D从节点对读操作无影响，证明一直使用的是主节点读取；

关闭A主节点后，在主从切换之前启动A主节点，客户端读取会等待后继续从A主节点读取数据（也没有切换到D从节点）；

长时间关闭A主节点（主从已切换，过程中有报org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries，但是从节点都是可用的），客户端读取操作转到D节点，此时D节点已为主节点；

通过上面的测试发现只要从节点下线超过一定时间，后续的读操作就不会从从节点读取了

期望结果应该是从节点恢复后，读操作可以走从节点，不确定是bug还是配置问题

**Comment by jackygurui** [comment]
如果一个节点断线以后，长时间都不能恢复，Redisson会逐渐延长尝试连接该节点的间隔时间。你需要耐心等待一段时间，就能看到从节点恢复通信。

**Comment by liuzhaozhao** [comment]
多谢回复
