### ISSUE TITLE
Support for Socks proxy?

### ISSUE THREAD

**Issue by stzanakis** [redisson/redisson#1107]
Hi there,

I was looking around and I cannot find if there is socks proxy support.
I am creating the socks Authenticator like this.

` System.setProperty("socksProxyHost", this.host);
    System.setProperty("socksProxyPort", this.port);
    if (StringUtils.isNotEmpty(this.user)) {
      System.setProperty("java.net.socks.username", this.user);
      System.setProperty("java.net.socks.password", this.password);
      this.auth = new SocksProxy.ProxyAuthenticator(this.user, this.password);
      Authenticator.setDefault(this.auth);
    }`

And the RedissonClient is created like so:

`Config config = new Config();
    config.useSingleServer().setAddress(String.format("redis://%s:%s", redisHost, redisPort));
    config.setLockWatchdogTimeout(
        redissonLockWatchdogTimeoutInSecs * 1000L);
    Redisson.create(config);`

But when it tries to initialize the connection it always tries to access the redisHost directly.
Is there support for socks proxy and if so how can I properly enable it?

**Comment by akrepon** [comment]
I have the same issue with the proxy. I tried the same solution as @stzanakis but it does not seem to work. There is also no documentation on this. Could you please tell me how I can make this this work?

Thanks in advance.

**Comment by mrniko** [comment]
You can define own nettyHook object https://github.com/redisson/redisson/wiki/2.-Configuration#nettyhook to add Channel handlers related to socks protocol
