### ISSUE TITLE
好像没有直接的delete,exists方法

### ISSUE THREAD

**Issue by zxj19951029** [redisson/redisson#1111]
因为我想定义一套接口，里面有多个实现，像redisson只能先查找出来，然后再进行该方面的操作，而查询又分为int类型的查询，map类型的查询等等，给统一接口带来一些不便，不知道有没有相应的解决办法，或者是我并不了解相应的api呢？

**Comment by jackygurui** [comment]
有的。所有与key有关的操作Redisson有一个专门的对象。

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonKeys.java
