### ISSUE TITLE
Configuring redisson to work with Azure Redis Cache standard tier

### ISSUE THREAD

**Issue by maltalex** [redisson/redisson#1114]
What's the correct way of setting redisson up to work against a standard tier Azure Redis Cache? I'm asking because the standard tier Redis Cache is replicated, but Azure doesn't provide the connection details for the slave instance.

According to the documentation, Redisson's "replicated mode" requires that 
> All nodes (master and slaves) should be provided.

So do I use "replicated mode" and only specify a single instance, or do I use "single instance mode"?

**Comment by mrniko** [comment]
Seems you're using Azure Redis Cache in Cluster configuration. You should use `Config.useClusterServers()` to define at least one cluster node. Redisson will detect other nodes automatically.

**Comment by MaltAlex** [comment]
@mrniko The Permium tier of the Azure Redis Cache is indeed clustered. But the standard tier is only replicated, not clustered. Should I use `Config.useClusterServers()` anyway?

**Comment by mrniko** [comment]
@MaltAlex If Azure doesn't provide any other node except master then use single instance mode

**Comment by MaltAlex** [comment]
@mrniko  Azure provides automatic master/slave replication, but they don't provide the connection details for the slave node. So there are in fact two instances somewhere in their cloud, but I can connect directly to only one of them.

**Comment by MaltAlex** [comment]
[This answer](https://stackoverflow.com/a/46992577/3199595), for an Azure Redis Cache team member states that:

> ... the service exposes only one endpoint and ensures that any requests to that endpoint hit the correct Master. It is technically possible to connect to Master or Slave, but Azure doesn't expose it and it **requires checks on the client side to ensure that the node is indeed Master or Slave**.

Does single instance mode check whether the instance is a master or a slave? Apparently this is something that Azure expects clients to do.

**Comment by mrniko** [comment]
@MaltAlex In case of failover slave became master under same endpoint name, right? Redisson determines failover case by detecting ip change of host name.

**Comment by MaltAlex** [comment]
@mrniko It's the same name, sure. But it might actually be the same IP too. The DNS record has a TTL of 60 seconds, which is pretty long time to do a failover for a service such as redis.

I suspect that the name and IP address are of some load-balancing/failover service on Azure which dynamically routes requests to the working Redis instance. I'll try forcing a master/slave failover on Azure by rebooting one or both instances. I'll check whether the IP address changes.

**Comment by MaltAlex** [comment]
@mrniko Ok, so I just ran a little experiment. I used a VM within Azure to periodically resolve the redis cache's name while I rebooted the master, slave, or both instances. The resolved IP address never changed. This supports the theory that it's actually the IP address of some Azure load balancer, not of one of the actual redis nodes.

**Comment by mrniko** [comment]
> The resolved IP address never changed. This supports the theory that it's actually the IP address of some Azure load balancer, not of one of the actual redis nodes.

You need to check TTL of your DNS server. It might too big

**Comment by MaltAlex** [comment]
@mrniko It's not my DNS server. I'm talking about Azure's endpoint. It's their DNS server and their DNS record.
When you create a Redis Cache on Azure you get a dns name such as "test.redis.cache.windows.net" (which by the way exists) and Azure tells you that this is your replicated redis endpoint. **That** dns record has a 60 second TTL.

**Comment by mrniko** [comment]
what is the address of dns you use?

**Comment by MaltAlex** [comment]
It doesn't depend on the DNS server. In my small experiment I used Azure's DNS server, which isn't available outside their cloud AFAIK.

The DNS record is created by Azure so its TTL is set by Azure. You can easily verify that by yourself by running `dig test.redis.cache.windows.net` against _any_ DNS server you wish. You'll get something like this:

> ;; ANSWER SECTION:
> test.redis.cache.windows.net. 240 IN    CNAME   wus-7428873503.cloudapp.net.
> wus-7428873503.cloudapp.net. **60** IN      A       0.0.0.0

Note the 60 in the second line - that's the 60 second TTL.

I think that in their implementation they want the client software to check which redis instance the endpoint is connected to using the redis protocol, not anything external like and IP address.

If you'd like, we can switch this conversation to some private channel and I can give you a small replicated redis cache on Azure to play around with for a while.

**Comment by mrniko** [comment]
Redisson checks DNS record in `DNSMonitor.monitorDnsChange` method. You can debug it to unsure that.

Can we use gitter for chat?
