### ISSUE TITLE
org.redisson.client.RedisTimeoutException

### ISSUE THREAD

**Issue by luckterry7** [redisson/redisson#1119]
`org.redisson.client.RedisTimeoutException: Redis server response timeout (10000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, 123, 30000, cb52c4c0-bcf8-49e2-9b27-a68401b43123:147] channel: [id: 0x500b5be9, L:/192.168.1.165:36618 
 - R:/192.168.1.46:6379 
]
at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:696)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
at java.lang.Thread.run(Thread.java:745)`

**redis server 信息**
1，redis 版本 3.0.6，
2，单节点
3，server配置
![default](https://user-images.githubusercontent.com/12081476/32159924-70a2a034-bd8a-11e7-9c46-ae2dbe32ab13.png)

**redisson信息**
1，版本2.10.4
2，配置如下
`SingleServerConfig singleSerververConfig = config.useSingleServer();
singleSerververConfig.setConnectionPoolSize(300);		singleSerververConfig.setConnectionMinimumIdleSize(10);
singleSerververConfig.setConnectTimeout(10000);
singleSerververConfig.setTimeout(10000);
singleSerververConfig.setRetryAttempts(3);
singleSerververConfig.setRetryInterval(1000);	singleSerververConfig.setSubscriptionConnectionMinimumIdleSize(1);
singleSerververConfig.setSubscriptionConnectionPoolSize(25);`

出现RedisTimeoutException是并发量很少的时候，高峰期并没有这样的错误，请帮忙看看是哪里有问题
谢谢

**Comment by jackygurui** [comment]
`Redis server response timeout` 是命令发送出去了，等待回复的时候超时了。你看看你的slowlog里面的内容。

**Comment by luckterry7** [comment]
是命令发出去之后，等待回复超时了。但是redis server
我这边有另外一个项目，使用的是jedis客户端连接同一个redis server，没有类似这样的等待回复超时，
而且，并发量大时，不会出现这个问题。
所以，有没有可能是redison这边，从连接池中取到的是已经过期失效的连接，发命令等待回复超时？
有没有什么方法可以查询到当前实时的连接数量？
谢谢

**Comment by jackygurui** [comment]
> 有没有可能是redison这边，从连接池中取到的是已经过期失效的连接，发命令等待回复超时？

没有这种可能性

> 有没有什么方法可以查询到当前实时的连接数量？

开源版里没有用量统计的功能，在企业版里才有

**Comment by wxdh1987** [comment]
我也碰到了楼主的问题，但是并不是经常出现。而且出现的时候，也是在redis并发不高的情况下。查看redis slowlog并没有看到任何信息。还望回复

**Comment by jackygurui** [comment]
@wxdh1987 slowlog记录的时间并没有将排队时间和网络延时计算在内，而`RedisTimeoutException`指的是整个过程超时。你说的偶尔出现的情况应该和网络抖动有关系，你可以尝试调节一下`timeout`参数。

**Comment by sun-eng** [comment]
楼主问题解决了吗，我也遇到了
