### ISSUE TITLE
从节点断开又恢复时，不会加入到slaveBalancer

### ISSUE THREAD

**Issue by liuzhaozhao** [redisson/redisson#1121]
这个问题之前提过：https://github.com/redisson/redisson/issues/1106

redisson版本：3.5.4

看了下源码，从节点恢复时，会走MasterSlaveEntry.slaveUp方法，但是在判断当前恢复节点不是主节点后，会从slaveBalancer中下线主节点，但是代码却下线了从节点（刚恢复的节点），代码行数：349

**Comment by jackygurui** [comment]
当主节点的唯一从节点断开以后，主节点会把自己作为从节点加入到从节点列表里`slaveUp(master)`。然后等从节点上线以后，再把主节点从从节点列表里删除`slaveDown(master)`。

**Comment by liuzhaozhao** [comment]
嗯，上线从节点的逻辑是你上面说的，但是实际代码却会下线从节点（可能是误写），353行代码
https://github.com/redisson/redisson/blob/d228d4740499106ac92d9aff31e089495e8867dd/redisson/src/main/java/org/redisson/connection/MasterSlaveEntry.java#L343-L357

**Comment by jackygurui** [comment]
嗯，感谢你指出这个问题。

**Comment by mrniko** [comment]
Fixed! Thanks for report
