### ISSUE TITLE
Reset maxIdleTime and ttl on read is not working

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#1123]
I am using redis with elastic cache in my spring application where i am using spring annotations for accessing cache.

I need to reset cache idle time and ttl on read so that i can keep my user active until user goes idle beyond timeout.

But read is not resetting the timeout and cache is evicted as per idle time and ttl set in configuration. Using below annotation in both the cases for creating and reading cache, the issue is same in both single and multiple server configuration.

**@Cacheable(value = TEST_CACHE, key = CACHE_KEY)**

**config**

"singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": ["redis://127.0.0.1:6379"],
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":10,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoring":false,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":null,
   "useLinuxNativeEpoll":false

What is the configuration needed to reset idle time and ttl on read? please advise.

**Comment by mrniko** [comment]
You need to use `maxIdleTime` parameter only, and set ttl to `0`.

**Comment by anilkonduru** [comment]
Thanks @mrniko, that worked.
