### ISSUE TITLE
Redisson not set-up correctly when using JCache API and custom config file 

### ISSUE THREAD

**Issue by mlk5060** [redisson/redisson#1127]
I have a Spring Boot application and a Bean that implements `org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer`, i.e. there is a method that takes a `javax.cache.CacheManager`, and then follows the instructions provided [here](https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#144-jcache-api-jsr-107-implementation). Specifically, I have implemented a mixture of the code snippets for: 

1. "Using config file with custom location"
2. "Using Redisson's config object:"

Essentially, I have the following that does create caches as I would expect on my local Redis instance:

```
@Override
public void customize(javax.cache.CacheManager manager) {
    MutableConfiguration<String, String> jcacheConfig = new MutableConfiguration<>();
    Config redissonCfg = getClass().getResource(expectedRedissonCacheConfigLocation);
    Configuration<String, String> config = RedissonConfiguration.fromConfig(redissonCfg, jcacheConfig);
    Cache<String, String> cache = manager.createCache("namedCache", config);
}
```

However, when I run tests or start/stop the Spring boot application, I always receive the following Log message and the Redis caches are not cleared.  Note that the caches are reset if multiple tests are run in sequence but the data cached in the last test is still present in the Redis instance after the test has been run.

`WARN 10556 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method 'close' failed on bean with name 'jCacheCacheManager': java.lang.NullPointerException`

After debugging, it seems that there is no `org.redisson.Redisson` object created. This appears to be caused by the checks for either a `redisson-jcache.json` and `redisson-jcache.yaml` being on the classpath in `org.redisson.jcache.JCachingProvider#loadConfig(URI uri)`. If these files are not found, the config returned is `null` which means that `org.redisson.jcache.JCachingProvider#getCacheManager(URI uri, ClassLoader classLoader, Properties properties)` does not invoke the code inside the `if` conditional below:

```
Redisson redisson = null;
if (config != null) {
    redisson = (Redisson) Redisson.create(config);
}
manager = new JCacheManager(redisson, classLoader, this, properties, uri);
```

I do not have either a `redisson-jcache.json` and `redisson-jcache.yaml` file on the classpath since my team are trying to develop a way of loading different Redisson configuration files based upon the Spring Boot profile that is used to launch a Spring Boot application.  Configuration files are instead searched for in a specified location with a specified file name (the name of a Spring Boot profile).

**Comment by mrniko** [comment]
To destroy cache in case of absence any config file you should invoke `JCacheManager.destroyCache` method

**Comment by mlk5060** [comment]
Hi @mrniko! I've worked around this issue by defining a `redisson-jcache.yaml` file that contains the default configuration that should be used if a specific application profile YAML file is not defined in a service that uses Redisson. This works well, but my main issue is that the documentation implies that a custom YAML file can be used to set-up Redisson in the same way as it would be set-up if a `redisson-jcache.yaml` file were present on the classpath. This does not seem to be the case, however!

Thank you for responding and all your work on this library though, it has been a tremendous help to our team :+1:

**Comment by mrniko** [comment]
@mlk5060 
You shared code for starting jcache instance in issue description, but I can't find code for shutdown. Could you share it?

**Comment by mlk5060** [comment]
The library I've been building (that makes use of Redisson) doesn't declare any shutdown code. After taking the steps I described above, the Log message I originally posted no longer appears. So, I'm assuming the Redisson object created by virtue of including `redisson-jcache.yaml` on the classpath contains shutdown code?

**Comment by mrniko** [comment]
It's interesting to see that instance got through `org.redisson.jcache.JCachingProvider#getCacheManager` for shutdown. Whereas `javax.cache.Cache` implements `java.io.Closeable` and should be shutdown through `close` method. Could you debug it to understand why `org.redisson.jcache.JCachingProvider#getCacheManager` is invoked ?
