### ISSUE TITLE
Retrieving objects using non-@RId fields

### ISSUE THREAD

**Issue by ashishshinde-quinnox** [redisson/redisson#1128]
I have a Customer object as below

```
            @REntity
            public class Customer {
               @RId
               private String guid;
               private String name;
 
               //Required getter-setter and constructors here...
          }
```

I store this object in Redis using the **persist** method as below: 

```
                Config config = new Config();
		config.useSingleServer().setAddress("redis://127.0.0.1:9000");
		redissonClient = Redisson.create(config);
		RLiveObjectService service = redissonClient.getLiveObjectService();
                service.persist(new Customer("1", "Tom");
```

I can use the `service.get(Customer.class, "1") ` method to retrieve this object based on the guid we pass to it. However, I have following requirements:

- retrieving Customer objects based on the name field, which is not @Rid
- retrieving Customer objects based on combination of guid and name field.

Can you point me to the right api for such requirement?

**Comment by jackygurui** [comment]
Retrieving objects using non-@RId fields is not implemented.

**Comment by mrniko** [comment]
Done. `@RIndex` annotation and `RLiveObjectService.find` method introduced https://github.com/redisson/redisson/wiki/9.-Distributed-services#rindex
