### ISSUE TITLE
Delayed writes

### ISSUE THREAD

**Issue by bhargava-kalathuru** [redisson/redisson#1129]
Hello,
  I was testing the behavior of Redis/Redisson when a network failure happens (say for few minutes) and then recovers. I observed the following unexpected behavior and wondering if there is a way to avoid this scenario.

Observation: 

1. SADD command was issued at 14:46 PM and failed due to RedisTimeoutException. This seems to have happened just about when network failure just started.
2. At 14:50 (A full 4 minutes later), it looks like Redisson heard back from Redis master node but due to client side timeout set, just skipped the response. 

Here are the logs:
```
03 Nov 2017 14:46:39,438 [WARN] ...... org.redisson.client.RedisTimeoutException: Redis server response timeout (25 ms) occured for command: (SADD) with params: [AKC-590000000707, 78af13d0-d00b-4898-9da3-8410236dcfb9] channel: [id: 0x845c3d76, L:/10.0.19.60:39336 - R:/10.1.48.182:6379]

03 Nov 2017 14:50:08,771 [WARN]  (redisson-netty-5-15) org.redisson.client.handler.CommandDecoder: response has been skipped due to timeout! channel: [id: 0x845c3d76, L:/10.0.19.60:39336 - R:/10.1.48.182:6379], command: CommandData [promise=org.redisson.misc.RedissonPromise@3742b67c[Completed exceptionally], command=(SADD), params=[AKC-590000000707, 78af13d0-d00b-4898-9da3-8410236dcfb9], codec=org.redisson.codec.JsonJacksonCodec@438dd2b6], result: true
```

Redis Version: 
Redisson Version: 3.4.1

Client configuration: (For ElastiCache cluster)

```java
    Config config = new Config();
    config.useClusterServers()
        .addNodeAddress(endpoint.getAddress() + ":" + endpoint.getPort())
        .setConnectTimeout(1000)
        .setTimeout(25)
        .setRetryAttempts(1) // client creation fails when set to 0
        .setRetryInterval(25);
```

**Comment by mrniko** [comment]
Hi,

`retryAttempt` and/or `retryInterval` params should be increased to survive failover.

**Comment by bhargava-kalathuru** [comment]
Hi @mrniko , 
  We can increase that but network failures for few minutes are expected and in that case I'm wondering if the behavior observed above is expected. While I totally get that a client might not know something happened or not on server side, strangely this `SADD` command completed after an `SREM` was completed for the value in the set (sorry don't have logs above). Are there any guarantees in ordering in a single shard for a single key? I thought Redis's single-threaded design should be able to handle this.

**Comment by mrniko** [comment]
> Are there any guarantees in ordering in a single shard for a single key? 

There are no any guarantee of order since the nature of TCP. There are two solutions:
1. use RBatch
2. send SREM once SADD has completed successfully.
