### ISSUE TITLE
useSentinelServers in ReadMode of MASTER_SLAVE, the master never got read. 

### ISSUE THREAD

**Issue by nyclei** [redisson/redisson#1130]
### Tried following config 
_initially copied from the document at https://github.com/redisson/redisson/wiki/2.-Configuration#27-sentinel-mode before changing readMode from "SLAVE" to "MASTER_SLAVE"_

---
{ 
   "**sentinelServersConfig**":{
      ... ,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.**RoundRobinLoadBalancer**"
      },
      "readMode":"**MASTER_SLAVE**",
      "sentinelAddresses":[
         "redis://192.168.1.101:26379",
         "redis://192.168.1.101:26379",
         "redis://192.168.1.102:26379"   
      ],
       ...
   }
}

---
I wish both master and 2 slaves could be read (33% chance on RoundRobin algo). But I see the master never got read.

Tried different Balancer and dug into the source, seems that the LB seems only be applied to slaves. The master server is setFreezed(true) and it won't get read unless both slaves get disconnected. 

Looks like ReadMode of "MASTER_SLAVE" is actually same as ReadMode of "SLAVE".

**Comment by mrniko** [comment]
Hi, this issue was fixed in https://github.com/redisson/redisson/commit/45db5cbea454dbcebf9bf9cf7e90f2579606a972

**Comment by ashishshinde-quinnox** [comment]
We're facing same issue while using the MASTER_SLAVE config parameter for our AWS ElastiCache

```
<redisson:cluster-servers  read-mode="MASTER_SLAVE>
<redisson:node-address value="...config endpoint here ..." />

```

**Comment by jackygurui** [comment]
@ashishshinde-quinnox can you try it again with master branch?

**Comment by mrniko** [comment]
fixed in 45db5cb

**Comment by nakamototavarez** [comment]
on cluster mode, i also tested with master_slave mode. read command is going to master but why 'readonly' command is going to the master every time i send read command

**Comment by mrniko** [comment]
@nakamototavarez which Redisson version do you use?

**Comment by nakamototavarez** [comment]
I used redisson latest version 2.6.12, I opend a issue  #1531
