### ISSUE TITLE
Redisson 3.5.5 will not accept "localhost:6379" as address for SingleServerConfig

### ISSUE THREAD

**Issue by mingjunz** [redisson/redisson#1132]
it used to accept "localhost:6379", but now the address seems have to be: "redis://127.0.0.1:6379"

this is because the change in org.redisson.misc.URIBuilder.java.

Should it more developer friendly?

**Comment by jackygurui** [comment]
This change is necessary to support the SSL connection, in which case the prefix needs to be "rediss://"

**Comment by mingjunz** [comment]
then we can close this issue, thanks for quick reply.
