### ISSUE TITLE
timeout configuration in Replicated Mode

### ISSUE THREAD

**Issue by joseduraes** [redisson/redisson#1133]
Hi, i'm using redisson with a Replicated Mode configuration (1 master and 2 slaves).

When attempting to debug an issue, i found that apparently the [timeout](https://github.com/redisson/redisson/wiki/2.-Configuration#timeout-1) configuration parameter is not being used in the implementation as documented.

I was receiving a fair amount of unexpected `RedisTimeoutException: Command execution timeout` messages.
Changing the `retryAttempts` and `retryInterval` allowed to circumvent the issue - but not changing `timeout` - which seemed odd to me, so i decided to dig further.

In [ReplicatedConnectionManager#L123](https://github.com/redisson/redisson/blob/89eff3861e14abc022852e444850f3eeb5ed13f8/redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java#L123),
the parameter passed for _connectionTimeout_ is `cfg.getRetryInterval() * cfg.getRetryAttempts()` (and not `timeout`). 

>         RedisClient client = createClient(
>             NodeType.MASTER, addr,
>              cfg.getConnectTimeout(), 
>               cfg.getRetryInterval() * cfg.getRetryAttempts()  // shouldn't it be cfg.getTimeout() (?)
>         );

A value of 0 for **retryAttempts**, or even a higher number matched with a relatively low **retryInterval** always causes the **RedissonClient** instantiation to fail (due to`Command execution timeout`).

Raising these values can bypass the error on the initial connection and allow the instantiation.
Still, the same applies to subsequent calls: they also won't also use the `timeout` provided in the configuration.

Am i observing this correctly or is there something i'm missing here?

**Comment by mrniko** [comment]
Hi,

`timeout` is only used for Redis response, once command has been sent successfully to the Redis channel. I used `cfg.getRetryInterval() * cfg.getRetryAttempts()` since RedisClient doesn't have command retry logic.
