### ISSUE TITLE
[Performance] Potential performance issue or improvement 

### ISSUE THREAD

**Issue by kringol** [redisson/redisson#1134]
One of our teams has been running some load tests that involve calling deleting keys from a redis cluster among other things. And when they run a profiler they observed that top hot spot was actually related to collection management (ConcurrentHashMap and HashSet) on redisson when getting connection info and copying it for every operation. 
As seen on the following hotspot analysis
![image](https://user-images.githubusercontent.com/98489/32530431-797ee368-c481-11e7-909a-477d31075531.png)

This was tested with redisson 3.4.3, haven't tried with the latest one yet

Is there anything that could be changed from config or improved on the code in future versions?

I believe the same scenario might show up on other operations besides delete

**Comment by mrniko** [comment]
This issue was fixed in https://github.com/redisson/redisson/issues/1081 in 3.5.5 version
