### ISSUE TITLE
SSL it's not fully implemented

### ISSUE THREAD

**Issue by florin-moisa** [redisson/redisson#1135]
Hi,

I was trying to use your library with AWS Clustered mode and figured out it does not work with SSL.
I figured out the problem and fixed it in my fork  but it's a hack what I did.
Basically everywhere you create an address like "redis://" -- you need a way to know if it's SSL and put "rediss://" instead. Since those places have no access to config, unfortunately I changed all to force SSL everywhere.

Do you have in plan a fix for this, or I can do it if you point me to the right way. I am trying to understand your logic and how can I be least invasive to pass a config. The simplest way would be to put a static public flag somewhere -- but that's also a hack I guess, and will only allow one type at one time, or pass a jvm property ...what do you suggest?

Thanks in advance,
Florin Moisa

**Comment by mrniko** [comment]
Hi,

Thanks for report. Actually there is only one place where scheme should be replaced to `rediss` - `org.redisson.client.protocol.decoder.ClusterNodesDecoder`. I have fixed it.

**Comment by florin-moisa** [comment]
Hi,

That was fast 👍. I also figured by debugging initially that was the only place, but it's not the only place.

I would also suggest to take a look here:
```
     public void changeMaster(final URI address) {
                 ....
                slaveDown(URIBuilder.create("redis://" + oldMaster.getClient().getIpAddr()), FreezeReason.MANAGER);
              ......
      }
```

and here:
```
    public RedisClientConfig setAddress(String host, int port) {
        this.address = URIBuilder.create("redis://" + host + ":" + port);
        return this;
    }
```

and here:
```
       public String getRedisServerAddressAndPort() {
            return "rediss://" + getRedisServerBindAddress() + ":" + getRedisServerPort();
        }
```

and here:
```
    public static String getDefaultRedisServerBindAddressAndPort() {
        return "redis://" + defaultRedisInstance.getRedisServerBindAddress()
                + ":"
                + defaultRedisInstance.getRedisServerPort();
    }
```

and here:
```
    private String createAddress(String host, Object port) {
        if (host.contains(":")) {
            host = "[" + host + "]";
        }
        return "redis://" + host + ":" + port;
    }
```

Hope it helps,
Florin Moisa

**Comment by mrniko** [comment]
Have you tried my changes? Does it work now?

**Comment by florin-moisa** [comment]
yes it does 👍, I made exactly the same change, but I figured the other places also need  update since it will fail if master changes and so on.
