### ISSUE TITLE
Java objects - support for search by non-RId fields

### ISSUE THREAD

**Issue by salilgandhi** [redisson/redisson#1136]
Hi,

We have a usecase where we store Java objects in cache and search them by multiple fields. Is there a way to achieve it in Redisson liveObjects? Spring-data-redis provides such functionality but does not support redisson.

Thanks,
Salil Gandhi

**Comment by mrniko** [comment]
@salilgandhi 
Hi,

Do you mean this topic https://docs.spring.io/spring-data/redis/docs/2.0.1.RELEASE/reference/html/#redis.repositories.queries ?

**Comment by salilgandhi** [comment]
@mrniko 
Yes. Exactly.

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/1128
