### ISSUE TITLE
Read-only GEORADIUS support

### ISSUE THREAD

**Issue by racevedoo** [redisson/redisson#1140]
Hi,
Redis 4.0.0 and 3.2.10 introduced read-only GEORADIUS variants(GEORADIUS_RO and GEORADIUSBYMEMBER_RO), as the [docs](https://redis.io/commands/georadius) state. Are there any plans to add this command to redisson?

Thanks in advance!

**Comment by mrniko** [comment]
Hi,

as documentation stated:

> They are exactly like the original commands but refuse the STORE and STOREDIST options

What is the point to support them? GEORADIUS and GEORADIUSBYMEMBER commands are enough, I think

**Comment by racevedoo** [comment]
They are readonly commands, so they can be executed on readonly slaves. [This redis issue](https://github.com/antirez/redis/issues/4084) contains the discussion that led to their creation.

**Comment by mrniko** [comment]
Done
