### ISSUE TITLE
Initialization timeouts leads to performance issues and timeout on batch

### ISSUE THREAD

**Issue by kringol** [redisson/redisson#1143]
Hi, 

I've been fighting for the past week with some weird timeout issue on one of our apps.
The use case is an RBatch operation that execute a bit of getBucket(..).getAsync()
Run scenarios with 1 get or N gets as part of the batch and happens on any.

The issue is basically that after a few minutes after starting the app, some instances of my app start displaying timeouts on that cache operation and thus becoming slow, then i restart that particular node of the app, and maybe it's fine forever, then I restart another instance and maybe now that one starts exhibiting the same problem. Sometimes it add a constant base of 50ms delay (due to timeout and retries) and sometimes it's 150ms or similar. 
We tried with redisson 3.2.0 and 3.5.5 and we can observe the problem on both, we though it might some hardware/network problem on those servers where such apps are running, but after restarting and re-running it works fine (or not) and viceversa on other servers.

The errors we get on the failing app are always like this
`org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:308)
	at org.redisson.command.CommandBatchService.checkConnectionFuture(CommandBatchService.java:379)
	at org.redisson.command.CommandBatchService.access$200(CommandBatchService.java:58)
	at org.redisson.command.CommandBatchService$4.operationComplete(CommandBatchService.java:296)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.cancel(DefaultPromise.java:322)
	at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:225)
	at org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:258)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:748)`

And this what we observe many times
1 app failing out of 10
![image](https://user-images.githubusercontent.com/98489/32650678-042bff2a-c642-11e7-8075-60ffb021e085.png)

1 failing out 3
![image](https://user-images.githubusercontent.com/98489/32650624-da70666c-c641-11e7-96a5-fa63704ec073.png)

3 failing out of 5
![image](https://user-images.githubusercontent.com/98489/32650714-26674860-c642-11e7-97b1-78d8d690d807.png)

Our settings are like the following
`    "clusterServersConfig": {
                    "connectTimeout" : 100,
                    "timeout" : 100,
                    "retryInterval" : 30,
                    "masterConnectionMinimumIdleSize" : 64,
                    "masterConnectionPoolSize": 64,
                    "slaveConnectionMinimumIdleSize" : 64,
                    "slaveConnectionPoolSize": 64,
                    "retryAttempts": 2,
                    "readMode": "MASTER_SLAVE",
                    "nodeAddresses": [
                        "redis://redis001.prod.hnd1.bdd.local:6329",
                        "redis://redis001.prod.hnd1.bdd.local:6339",
                        "redis://redis001.prod.hnd1.bdd.local:6349",
                        "redis://redis002.prod.hnd1.bdd.local:6329",
                        "redis://redis002.prod.hnd1.bdd.local:6339",
                        "redis://redis002.prod.hnd1.bdd.local:6349",
                        "redis://redis003.prod.hnd1.bdd.local:6329",
                        "redis://redis003.prod.hnd1.bdd.local:6339",
                        "redis://redis003.prod.hnd1.bdd.local:6349",
                        "redis://redis004.prod.hnd1.bdd.local:6329",
                        "redis://redis004.prod.hnd1.bdd.local:6339",
                        "redis://redis004.prod.hnd1.bdd.local:6349",
                        "redis://redis005.prod.hnd1.bdd.local:6329",
                        "redis://redis005.prod.hnd1.bdd.local:6339",
                        "redis://redis005.prod.hnd1.bdd.local:6349",
                        "redis://redis006.prod.hnd1.bdd.local:6329",
                        "redis://redis006.prod.hnd1.bdd.local:6339",
                        "redis://redis006.prod.hnd1.bdd.local:6349"
                    ]
                },
                "useLinuxNativeEpoll": true
            }`

This is being used on a very high traffic app, but we can reproduce it with low traffic as well.

Do you have any suggestion or insight on any thing we can try changing on our config and re-run our load test so we can sort out this issue. And we really need the data to be read from redis because the alternative when our cache fails is a much worse system that cannot handle the load or our SLA

We have been trying changes on the servers, running on different hardware, etc but nothing changed yet. Could it be some dead connection or bottleneck on the batch or connection manager that is causing this? Also as you can see on the avg time graph on top, it doesn't happen for every request, but for many of them, but constantly ONLY on that running app of all the total

**Comment by jackygurui** [comment]
There should be cause after that exception. Can you share that too?

**Comment by kringol** [comment]
I see 1 error with an slave at the start, then a few timeouts from the CommandDecoder and then the batch execution logs start to appear from that moment on and those are the only new logs that come from that moment on 
Here's a copy of the log of one failing app instance from the start (trimmed after that as it is the same multiple times after)
https://pastebin.com/D95JNu7m

**Comment by jackygurui** [comment]
Just as I suspected, it is cause by the connection has dropped to a node.

**Comment by kringol** [comment]
Mmm, but having 12 masters and 24 slaves. If one slave connection is lost it will not use the other slave (or master) of the same bucket???
Not sure if it is some sort of bug or if there any way i can make it more lenient or if i should try with more "failedAttempts" to try to overcame it.
Will this only happen at start up or if a connection is lost at some point during normal operation it will also occur?

**Comment by jackygurui** [comment]
As soon as Redisson detects a node failure, it will effectively block that node from being used. However those commands has already sent to it would be lost and hence the exception is thrown.

**Comment by kringol** [comment]
More logs
https://pastebin.com/RgGfvaf1

Likely related to
https://github.com/redisson/redisson/issues/729
https://github.com/redisson/redisson/issues/1010

Would be nice to add more info on the config documentation about how does all the connection/execution timeout parameters interact with other during initialization and normal operation command execution.
For example: 
- connectTimeout
- timeout
- reconnectionTimeout
- lockWatchdogTimeout
- failedAttempts
- retryInterval
- retryAttempts

I though we got all of them clearly, but after seeing this issue and the one on the other linked issues, i am not so sure anymore.

Specially since my app starts fine during our load test, and then after around 60~90 sec (low load) the issue with the timeout appears. Like if it is some thread/connection being stuck or broken somewhere

**Comment by kringol** [comment]
How can we make the initialization procedure more lenient?
Let's said we want a constant size connection pool (min=max) and we don't mind waiting longer for all connections to be available and ready at start time. 
Right now seems it gives up pretty quickly and throws all those warnings or fail entirely

**Comment by kringol** [comment]
Update:

Seems the chances of error are reduced if I switch to a dynamic pool size
Tried with min 32, max 64
And with min 10, max 64
Chances of the client initializing successfully increased, but after repeated restarts sometimes some client get a badly initialized connection (noticeable by the timeout when sending the READONLY command) and then starts having timeouts later on.

But if it starts fine, then no problem is observer ever after (tested on a pro app that has been running with 10 nodes with constant high traffic for 2weeks), 10 nodes (9 good and 1 displaying this issue and constantly having the timeouts)

**Comment by kringol** [comment]
New Update after further tests
Using the default timeout values and my settings (constant pool size) like
`"connectTimeout" : 10000,
  "timeout" : 3000,
  "retryInterval" : 1500,
  "retryAttempts": 3,
  "masterConnectionMinimumIdleSize" : 64,
  "masterConnectionPoolSize": 64,
  "slaveConnectionMinimumIdleSize" : 64,
  "slaveConnectionPoolSize": 64`

And then setting a timeout on the RBatch operation itself, cause 3000ms and those values are unacceptable for our app SLA. (i can only do this workaround for batch operation though)

Therefore 2 conclusions
1) Seems that it's common that some apps have issues initializing connections during startup, maybe due to some warmup or the fact that it runs inside a docker container and might have some network delays at the beginning (just a wild guess) but for whatever reason, seems the initialization stage requires a more lenient timeout strategy like https://github.com/redisson/redisson/issues/729 suggested.
Therefore it will be nice to add some settings for timeouts/retries during init phase

2) Even with the init timeouts, redisson seemed unable to recover later and ended up with some big delays due some reason (dead connections, leaks, whatever)

**Comment by PC-AKumar** [comment]
@kringol Did you eventually figure this out? The problem you described is very close to what I am seeing when using redisson with cluster servers configuration.

**Comment by kringol** [comment]
Hi @PC-AKumar 
No official solution to have separate timeouts for init stage and normal operations yet. Therefore we solved the issue by having big timeout settings on our config file, and then executing our operations on an RBatch (pipeline) operation where we can set a timeout, retry, retrytimeout settings per batch and thus override the config file settings with values that meet our SLA needs.

**Comment by mrniko** [comment]
@PC-AKumar Correct me if I wrong. You moved your EC2 instance to the same AZ as a Redis primary instance has and this instances connected to this primary only?

**Comment by PC-AKumar** [comment]
@mrniko No, it connected to all the nodes in the cluster through the configuration end-point, but only one of the nodes was having issues connecting to it. Moving the instance to the AZ in which the node was seemed to have fixed the issue. Makes me think that redisson-client is storing some sort of state in redis thats not allowing connections to get recycled across instance restarts. Is this true?

**Comment by mrniko** [comment]
@PC-AKumar the only data stored by Redisson is a state of objects used by application.

**Comment by PC-AKumar** [comment]
@kringol Do you use spring caching? i.e., `org.springframework.cache.CacheManager`

**Comment by kringol** [comment]
@PC-AKumar no, we use redisson directly via RBatch commands for bulk get of keys on a cluster setup

**Comment by PC-AKumar** [comment]
@kringol Thanks

**Comment by mrniko** [comment]
Batch result decoding might take a little bit more time. Since data decoding executed by netty threads this may cause other queued commands to get hang with unexpected timeout. To overcome this increase `nettyThreads` param to 32 / 64 / 128.
