### ISSUE TITLE
Netty version issue

### ISSUE THREAD

**Issue by JackEggie** [redisson/redisson#1144]
你好，我发现redisson的jdk1.7的兼容版本（2.10.5）中已经使用了netty的4.1.16版本，该版本在netty官方已经是jdk1.8编译的的版本了。请问用jdk1.7使用这个版本会出现问题吗？

另外，由于代码冲突的原因，我们需要把netty降版到4.0.25，请问哪个redisson的版本是兼容这个netty版本的呢。我直接把最新的redisson中的netty降到该版本会不会有问题？

**Comment by JackEggie** [comment]
Sorry，我试了一下，直接降版会出现如下异常：
java.lang.NoSuchMethodError: io.netty.bootstrap.Bootstrap.config()Lio/netty/bootstrap/BootstrapConfig;

**Comment by jackygurui** [comment]
Redisson 2.6.0也许行，不过这个版本有点太老了吧。

**Comment by JackEggie** [comment]
请问官方有没有对于jdk1.7编译的redisson使用的却是jdk1.8编译的netty的相关说明呢？因为在jdk1.7的环境中跑着jdk1.8编译的netty实在是感觉有风险额。

**Comment by jackygurui** [comment]
Netty官方说1.6以上就没有问题的。

**Comment by jackygurui** [comment]
>另外，由于代码冲突的原因，我们需要把netty降版到4.0.25

请问这是因为HBase引起的吗？

**Comment by JackEggie** [comment]
好的。谢谢，看到netty是用jdk1.8编译为1.6版本的jar了。
我们这边暂时还没有用到HBase，冲突是cat和rocketmq引起的。
