### ISSUE TITLE
Snappy implementation in recent versions throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nebel** [redisson/redisson#1145]
## Summary

Up to and including Redisson version 2.10.1 and 3.5.1, Redisson used the Xerial implementation of Snappy (https://github.com/xerial/snappy-java) for its SnappyCodec.

In versions 2.10.2 and 3.5.2, Redisson was changed to use the internal implementation of Snappy from Netty instead. However, this implementation seems to be designed only for Netty's use cases and cannot encode moderately-sized payloads. In this case, moderately-sized means that payloads of more than 50,000 bytes are very likely to fail.

This results in an error during the encoding step, e.g.

```java
Exception in thread "main" java.lang.IndexOutOfBoundsException: index: -32765, length: 4 (expected: range(0, 8388608))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1358)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1353)
	at io.netty.buffer.AbstractByteBuf.getInt(AbstractByteBuf.java:417)
	at io.netty.handler.codec.compression.Snappy.encode(Snappy.java:127)
	at org.redisson.codec.SnappyCodec$4.encode(SnappyCodec.java:89)
```

## Steps to Reproduce

I have created a repository that shows how and when this bug occurs. I take the last known good versions (2.10.1 and 3.5.1) and compare them with the most recent versions at the time of writing (2.10.5 and 3.5.4).

See the repository here: https://github.com/nebel/netty-snappy-redisson-demo

To run the examples, either run the main method for each module in your IDE, or run each module via the command line with `mvn package exec:java`.

The `redisson-*-snappy-demo` modules show the behavior in the indicated Redisson version. As you can see, the last known good versions (using the Xerial implementation of Snappy) can encode this payload without any problems, whereas the new versions (using the Netty implementation of Snappy) will fail.

The `netty-xerial-snappy-demo` module shows how increasing the size of the encoded payload will soon cause Netty's implementation to reach a breaking point after which all attempts at encoding will fail. When creating the sample data with a random seed of 0, Netty will succeed on a payload of 44,895 bytes and fail on a payload of 44,896 bytes. Changing the seed will change this number, but it will generally fail somewhere between 40,000 to 50,000 bytes.

The Xerial implementation, on the other hand, does not fail at any size I tested (up to 100 million bytes).

## Fix

While it's nice to avoid an additional dependency, I believe the Snappy implementation from Netty should probably be considered an internal implementation since this size limitation makes it unsuitable as a general compression algorithm.

The Xerial implementation seems to be more widely used by more high-profile projects (e.g. Cassanda) and is probably a safer choice.

**Comment by mrniko** [comment]
Could you please create this issue in https://github.com/netty/netty project too?

**Comment by mrniko** [comment]
It's a bug and `io.netty.handler.codec.compression.SnappyFrameEncoder` should be used along with `io.netty.handler.codec.compression.Snappy`

**Comment by johnou** [comment]
@nebel nice find!

**Comment by nebel** [comment]
Thanks for the confirmation @mrniko and @johnou 

By the way, I also investigated `io.netty.handler.codec.compression.SnappyFrameEncoder` and `SnappyFrameDecoder` but from what I tried, they also seemed a little difficult to use. The `encode` and `decode` methods are protected and the decoder is especially awkward because it requires a `io.netty.channel.ChannelHandlerContext` for byte buffer allocation, which I would not expect to initialize manually. So that is one of the reasons that I thought perhaps these classes are mostly for internal use.

**Comment by mrniko** [comment]
Fixed! Thanks for report. I split data to chunks of 32K to handle that case. Like SnappyFrameEncoder does

**Comment by wsfjy19914** [comment]
@mrniko 
We also ran into this problem recently and I noticed that by your solution, we have to migrate all our old keys since they are not compatible with your new chunked compression algorithm. Which means ~2.10.1, 2.10.2~2.10.5, 2.10.6~ are not compatible with each other and it will bring huge impact to our system. Actually after all would you please share the reason why you changed from xerial's to netty's implementation?
Thank you!

**Comment by mrniko** [comment]
@wsfjy19914 I did it to remove external dependency.
