### ISSUE TITLE
Connection distribution upon nodes

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#1147]
Hi,
I have a setup of 3 redis nodes with 3 sentinel nodes.
I am using latest redisson with master_slave read mode.
I see that almost all connections go to the master redis and slaves are not in use.
Also when connecting to redis i see only db0 is being in use.
What am i doing wrong in my redisson config?

Thanks

![image](https://user-images.githubusercontent.com/11013666/32906629-23859674-cb06-11e7-8761-60aa82ac8967.png)

**Comment by jackygurui** [comment]
Can you show us your Redis configs? Most likely you have not configured them correctly. 

In your redisson config, you can specify which database number you want to use by specifying this config option: https://github.com/redisson/redisson/wiki/2.-Configuration#database-2

**Comment by archmisha** [comment]
I am not setting this database parameter, so its the default value of 0.
Does it specify the number of databases to use or a single database index to be used?

Here is my config, its mostly defaults:
```
SentinelServersConfig sentinelServersConfig = config.useSentinelServers();
sentinelServersConfig.setMasterName("redis-cluster");
for (String server : servers) {
                        sentinelServersConfig.addSentinelAddress("redis://" + server + ":" + port);
                    }
sentinelServersConfig.setReadMode(ReadMode.MASTER_SLAVE);
            if (!StringUtils.isBlank(password)) {
                sentinelServersConfig.setPassword(password);
            }
```

**Comment by archmisha** [comment]
Bump.
Any other info I can provide?

**Comment by archmisha** [comment]
Amy help please?

**Comment by mrniko** [comment]
Hi! Could you try latest version? since there was fixed problem with ReadMode.MASTER_SLAVE mode.

**Comment by archmisha** [comment]
Yes it looks better now! Thanks

**Comment by mrniko** [comment]
Great!
