### ISSUE TITLE
OpenTracing support?

### ISSUE THREAD

**Issue by loganvolkers** [redisson/redisson#1148]
Is there any current plans, third party plugins, or a recommended best practice approach to use [Open Tracing](http://opentracing.io) with Redisson?

In particular the remote service invocations seem like they could benefit from the tracing span context propagating across the service boundaries.

I have done some quick googling and didn't find any libraries, documentation, or anything else on the subject.

**Comment by mrniko** [comment]
Work has been started here - https://github.com/opentracing-contrib/java-redisson
Kudos to @malafeev

**Comment by baurchanu** [comment]
hi, @mrniko. [That project](https://github.com/opentracing-contrib/java-redis-client) looks abandoned. How about to integrate open tracing support right into the redisson?

**Comment by malafeev** [comment]
open tracing is abandoned as well, open telemetry is successor of open tracing.

**Comment by mrniko** [comment]
implemented in PRO version
