### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by prehonor** [redisson/redisson#1149]
java.lang.NullPointerException
        at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:174)
        at org.redisson.tomcat.RedissonSessionManager.createSession(RedissonSessionManager.java:116)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2312)
        at org.apache.catalina.connector.Request.getSession(Request.java:2075)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:833)
        at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:844)
        at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:146)
        at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:124)
        at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:107)
        at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:63)
        at org.apache.jsp.testRedis_jsp._jspService(testRedis_jsp.java:45)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:374)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:342)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:267)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
        at java.lang.Thread.run(Thread.java:662)

redis搭建了集群 3主3从,然后项目使用的是jdk1.6 tomcat6 完全按照教程的配置文件使用Tomcat Redis Session Manager管理session 启动tomcat信息:
2017-11-18 21:35:11 org.apache.catalina.core.AprLifecycleListener init
信息: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /home/jdk1.6.0_45/jre/lib/i386/server:/home/jdk1.6.0_45/jre/lib/i386:/home/jdk1.6.0_45/jre/../lib/i386:/usr/java/packages/lib/i386:/lib:/usr/lib
2017-11-18 21:35:12 org.apache.coyote.http11.Http11Protocol init
信息: Initializing Coyote HTTP/1.1 on http-8080
2017-11-18 21:35:12 org.apache.catalina.startup.Catalina load
信息: Initialization processed in 523 ms
2017-11-18 21:35:12 org.apache.catalina.core.StandardService start
信息: Starting service tomcat1
2017-11-18 21:35:12 org.apache.catalina.core.StandardEngine start
信息: Starting Servlet Engine: Apache Tomcat/6.0.18
2017-11-18 21:35:12 com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector <clinit>
警告: Unable to load JDK7 annotation types; will have to skip
WARNING: could not load Java7 Path class
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from /192.168.1.104:7000:
9ede82afe626e38487b46edddbc3427bb6f05eac 192.168.1.104:7002 master - 0 1511012113124 3 connected 10923-16383
a58ca3c53d37fc1a909a8c5402da23b02d62b048 192.168.1.104:7005 slave 9ede82afe626e38487b46edddbc3427bb6f05eac 0 1511012111118 6 connected
82fec9e38ec4e6ee633009cf5366408368ce497b 192.168.1.104:7003 slave 58360c20acaad16bfa651800390b9ec676db265f 0 1511012111619 4 connected
ea942df7f35c28e96154948f08ad214c522a2d32 192.168.1.104:7004 slave 6d4190de16cce92b47e6d38129ecf5723a7b07f3 0 1511012113124 5 connected
6d4190de16cce92b47e6d38129ecf5723a7b07f3 192.168.1.104:7001 master - 0 1511012112120 2 connected 5461-10922
58360c20acaad16bfa651800390b9ec676db265f 192.168.1.104:7000 myself,master - 0 0 1 connected 0-5460

[redisson-netty-1-3] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7004] added for slot ranges: [[5461-10922]]
[redisson-netty-1-2] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7003] added for slot ranges: [[0-5460]]
[redisson-netty-1-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7005] added for slot ranges: [[10923-16383]]
[redisson-netty-1-1] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7005
[redisson-netty-1-1] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7004
[redisson-netty-1-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7001
[redisson-netty-1-3] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-1-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7000
[redisson-netty-1-3] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7000 added for slot ranges: [[0-5460]]
[redisson-netty-1-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7002
[redisson-netty-1-3] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7002 added for slot ranges: [[10923-16383]]
[redisson-netty-1-2] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7004
[redisson-netty-1-4] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7003
[redisson-netty-1-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7003
[redisson-netty-1-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7005
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from /192.168.1.104:7000:
9ede82afe626e38487b46edddbc3427bb6f05eac 192.168.1.104:7002 master - 0 1511012113124 3 connected 10923-16383
a58ca3c53d37fc1a909a8c5402da23b02d62b048 192.168.1.104:7005 slave 9ede82afe626e38487b46edddbc3427bb6f05eac 0 1511012113625 6 connected
82fec9e38ec4e6ee633009cf5366408368ce497b 192.168.1.104:7003 slave 58360c20acaad16bfa651800390b9ec676db265f 0 1511012111619 4 connected
ea942df7f35c28e96154948f08ad214c522a2d32 192.168.1.104:7004 slave 6d4190de16cce92b47e6d38129ecf5723a7b07f3 0 1511012113124 5 connected
6d4190de16cce92b47e6d38129ecf5723a7b07f3 192.168.1.104:7001 master - 0 1511012112120 2 connected 5461-10922
58360c20acaad16bfa651800390b9ec676db265f 192.168.1.104:7000 myself,master - 0 0 1 connected 0-5460

[redisson-netty-5-2] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7003] added for slot ranges: [[0-5460]]
[redisson-netty-5-3] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7004] added for slot ranges: [[5461-10922]]
[redisson-netty-5-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7005] added for slot ranges: [[10923-16383]]
[redisson-netty-5-3] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7004
[redisson-netty-5-2] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7005
[redisson-netty-5-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7000
[redisson-netty-5-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7000 added for slot ranges: [[0-5460]]
[redisson-netty-5-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7003
[redisson-netty-5-3] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7003
[redisson-netty-5-2] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7001
[redisson-netty-5-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7002
[redisson-netty-5-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7002 added for slot ranges: [[10923-16383]]
[redisson-netty-5-2] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-5-1] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7004
[redisson-netty-5-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7005
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from /192.168.1.104:7000:
9ede82afe626e38487b46edddbc3427bb6f05eac 192.168.1.104:7002 master - 0 1511012113124 3 connected 10923-16383
a58ca3c53d37fc1a909a8c5402da23b02d62b048 192.168.1.104:7005 slave 9ede82afe626e38487b46edddbc3427bb6f05eac 0 1511012113625 6 connected
82fec9e38ec4e6ee633009cf5366408368ce497b 192.168.1.104:7003 slave 58360c20acaad16bfa651800390b9ec676db265f 0 1511012114127 4 connected
ea942df7f35c28e96154948f08ad214c522a2d32 192.168.1.104:7004 slave 6d4190de16cce92b47e6d38129ecf5723a7b07f3 0 1511012113124 5 connected
6d4190de16cce92b47e6d38129ecf5723a7b07f3 192.168.1.104:7001 master - 0 1511012114127 2 connected 5461-10922
58360c20acaad16bfa651800390b9ec676db265f 192.168.1.104:7000 myself,master - 0 0 1 connected 0-5460

[redisson-netty-7-2] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7003] added for slot ranges: [[0-5460]]
[redisson-netty-7-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7005] added for slot ranges: [[10923-16383]]
[redisson-netty-7-3] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7004] added for slot ranges: [[5461-10922]]
[redisson-netty-7-3] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7003
[redisson-netty-7-4] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7005
[redisson-netty-7-3] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7004
[redisson-netty-7-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7003
[redisson-netty-7-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7000
[redisson-netty-7-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7000 added for slot ranges: [[0-5460]]
[redisson-netty-7-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7002
[redisson-netty-7-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7001
[redisson-netty-7-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7002 added for slot ranges: [[10923-16383]]
[redisson-netty-7-3] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-7-2] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7004
[redisson-netty-7-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7005
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from /192.168.1.104:7000:
9ede82afe626e38487b46edddbc3427bb6f05eac 192.168.1.104:7002 master - 0 1511012113124 3 connected 10923-16383
a58ca3c53d37fc1a909a8c5402da23b02d62b048 192.168.1.104:7005 slave 9ede82afe626e38487b46edddbc3427bb6f05eac 0 1511012113625 6 connected
82fec9e38ec4e6ee633009cf5366408368ce497b 192.168.1.104:7003 slave 58360c20acaad16bfa651800390b9ec676db265f 0 1511012114127 4 connected
ea942df7f35c28e96154948f08ad214c522a2d32 192.168.1.104:7004 slave 6d4190de16cce92b47e6d38129ecf5723a7b07f3 0 1511012113124 5 connected
6d4190de16cce92b47e6d38129ecf5723a7b07f3 192.168.1.104:7001 master - 0 1511012114127 2 connected 5461-10922
58360c20acaad16bfa651800390b9ec676db265f 192.168.1.104:7000 myself,master - 0 0 1 connected 0-5460

[redisson-netty-9-2] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7003] added for slot ranges: [[0-5460]]
[redisson-netty-9-2] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7003
[redisson-netty-9-3] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7004] added for slot ranges: [[5461-10922]]
[redisson-netty-9-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7005] added for slot ranges: [[10923-16383]]
[redisson-netty-9-2] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7005
[redisson-netty-9-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7000
[redisson-netty-9-4] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7004
[redisson-netty-9-3] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7000 added for slot ranges: [[0-5460]]
[redisson-netty-9-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7003
[redisson-netty-9-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7002
[redisson-netty-9-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7002 added for slot ranges: [[10923-16383]]
[redisson-netty-9-3] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7001
[redisson-netty-9-3] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-9-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7004
[redisson-netty-9-3] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7005
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from /192.168.1.104:7000:
9ede82afe626e38487b46edddbc3427bb6f05eac 192.168.1.104:7002 master - 0 1511012113124 3 connected 10923-16383
a58ca3c53d37fc1a909a8c5402da23b02d62b048 192.168.1.104:7005 slave 9ede82afe626e38487b46edddbc3427bb6f05eac 0 1511012113625 6 connected
82fec9e38ec4e6ee633009cf5366408368ce497b 192.168.1.104:7003 slave 58360c20acaad16bfa651800390b9ec676db265f 0 1511012114127 4 connected
ea942df7f35c28e96154948f08ad214c522a2d32 192.168.1.104:7004 slave 6d4190de16cce92b47e6d38129ecf5723a7b07f3 0 1511012113124 5 connected
6d4190de16cce92b47e6d38129ecf5723a7b07f3 192.168.1.104:7001 master - 0 1511012114127 2 connected 5461-10922
58360c20acaad16bfa651800390b9ec676db265f 192.168.1.104:7000 myself,master - 0 0 1 connected 0-5460

[main] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7003] added for slot ranges: [[0-5460]]
[redisson-netty-11-3] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7003
[redisson-netty-11-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7004] added for slot ranges: [[5461-10922]]
[redisson-netty-11-2] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7004
[redisson-netty-11-1] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7000
[redisson-netty-11-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7001
[redisson-netty-11-1] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7000 added for slot ranges: [[0-5460]]
[redisson-netty-11-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-11-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7005] added for slot ranges: [[10923-16383]]
[redisson-netty-11-2] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7005
[redisson-netty-11-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7003
[redisson-netty-11-1] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7004
[redisson-netty-11-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7002
[redisson-netty-11-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7002 added for slot ranges: [[10923-16383]]
[redisson-netty-11-1] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7005
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from /192.168.1.104:7000:
9ede82afe626e38487b46edddbc3427bb6f05eac 192.168.1.104:7002 master - 0 1511012113124 3 connected 10923-16383
a58ca3c53d37fc1a909a8c5402da23b02d62b048 192.168.1.104:7005 slave 9ede82afe626e38487b46edddbc3427bb6f05eac 0 1511012113625 6 connected
82fec9e38ec4e6ee633009cf5366408368ce497b 192.168.1.104:7003 slave 58360c20acaad16bfa651800390b9ec676db265f 0 1511012114127 4 connected
ea942df7f35c28e96154948f08ad214c522a2d32 192.168.1.104:7004 slave 6d4190de16cce92b47e6d38129ecf5723a7b07f3 0 1511012113124 5 connected
6d4190de16cce92b47e6d38129ecf5723a7b07f3 192.168.1.104:7001 master - 0 1511012114127 2 connected 5461-10922
58360c20acaad16bfa651800390b9ec676db265f 192.168.1.104:7000 myself,master - 0 0 1 connected 0-5460

[redisson-netty-13-4] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7004
[redisson-netty-13-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7004] added for slot ranges: [[5461-10922]]
[redisson-netty-13-2] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7003] added for slot ranges: [[0-5460]]
[redisson-netty-13-4] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7003
[redisson-netty-13-1] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7001
[redisson-netty-13-1] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-13-4] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.104:7005] added for slot ranges: [[10923-16383]]
[redisson-netty-13-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7004
[redisson-netty-13-3] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for /192.168.1.104:7005
[redisson-netty-13-4] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7000
[redisson-netty-13-4] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7000 added for slot ranges: [[0-5460]]
[redisson-netty-13-1] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /192.168.1.104:7002
[redisson-netty-13-1] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.104:7002 added for slot ranges: [[10923-16383]]
[redisson-netty-13-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7003
[redisson-netty-13-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 10 connections initialized for /192.168.1.104:7005
2017-11-18 21:35:14 org.apache.coyote.http11.Http11Protocol start
信息: Starting Coyote HTTP/1.1 on http-8080
2017-11-18 21:35:14 org.apache.jk.common.ChannelSocket init
信息: JK: ajp13 listening on /0.0.0.0:8009
2017-11-18 21:35:14 org.apache.jk.server.JkMain start
信息: Jk running ID=0 time=0/21  config=null
2017-11-18 21:35:14 org.apache.catalina.startup.Catalina start
信息: Server startup in 2944 ms

但访问项目中的jsp就报异常了,请问谁知道为什么,在线等,急~~~~~~

**Comment by jackygurui** [comment]
哪个版本的redisson？

**Comment by prehonor** [comment]
用的是redisson-all-2.10.5.jar 和 redisson-tomcat-6-2.10.5.jar
大神能加个qq什么的吗?我现看源码,看不懂啊,
    public void save() {
        Map<String, Object> newMap = new HashMap<String, Object>();
        newMap.put("session:creationTime", creationTime);
        newMap.put("session:lastAccessedTime", lastAccessedTime);
        newMap.put("session:thisAccessedTime", thisAccessedTime);
        newMap.put("session:maxInactiveInterval", maxInactiveInterval);
        newMap.put("session:isValid", isValid);
        newMap.put("session:isNew", isNew);
        
        for (Entry<String, Object> entry : attrs.entrySet()) {
            newMap.put(entry.getKey(), entry.getValue());
        }
        
        map.putAll(newMap);
        
        if (maxInactiveInterval >= 0) {
            map.expire(getMaxInactiveInterval(), TimeUnit.SECONDS);
        }
    }
看报错应该是map.putAll(newMap)报空指针了,但是我看了看这个map是的new出来的怎么会为空呢

**Comment by jackygurui** [comment]
你的QQ号是多少？

**Comment by prehonor** [comment]
1012896619

**Comment by mrniko** [comment]
Fixed
