### ISSUE TITLE
Out Of Memory When using RScheduledExecutorService.

### ISSUE THREAD

**Issue by yjain3326** [redisson/redisson#1150]
Hi,

We are seeing Out Of Memory Exception when using RScheduledExecutorService.

We are using redisson 3.5.5

These are our settings:
 scanInterval = 5000;
 idleConnectionTimeout = 30000;
 masterIdleConnectionPool = 50;
 masterConnectionPoolSize = 250;
 slaveIdleConnectionPool = 50;
 slaveConnectionPoolSize = 250;
 connectionTimeout = 30000;
 readTimeout = 30000;
 executorWorkerThreads = 10;

This is how we produced it:

`    public static void main(String args[]){

        int duration = 120;
        int totalThreads = 150;
        int delayInMillis = 30000;
        System.out.println("params are: "+duration+" "+totalThreads+" "+delayInMillis);
        init();

        long currentTime = System.currentTimeMillis();
        Calendar time = Calendar.getInstance();
        time.add(Calendar.MINUTE,duration);

        try {
            ExecutorService service = Executors.newFixedThreadPool(totalThreads);
            while(currentTime < time.getTimeInMillis()){
                try{

                    for(int i = 0;i<totalThreads; i++){
                        service.submit(new MessageSender(redissonExecutorService, delayInMillis));
                    }
                    currentTime=System.currentTimeMillis();
                    Thread.sleep(1000);
                }catch(Exception ex){
                    ex.printStackTrace();
                }

            }

            service.shutdown();
            System.out.print("================Done Scheduling..............");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }`

`    public static void init() {
        
        Config config = new Config();

        if (nodeList != null) {
            StringTokenizer nodes = new StringTokenizer(nodeList, DELIMITER);
            while (nodes.hasMoreTokens()) {
                config.useReplicatedServers()
                        .addNodeAddress(nodes.nextToken());
            }
            config.useReplicatedServers().setScanInterval(5000);
            config.useReplicatedServers().setIdleConnectionTimeout(30000);
            config.useReplicatedServers().setMasterConnectionMinimumIdleSize(50);
            config.useReplicatedServers().setMasterConnectionPoolSize(250);
            config.useReplicatedServers().setSlaveConnectionMinimumIdleSize(50);
            config.useReplicatedServers().setSlaveConnectionPoolSize(250);
            config.useReplicatedServers().setConnectTimeout(30000);
            config.useReplicatedServers().setTimeout(30000);

            RedissonNodeConfig nodeCnfig = new RedissonNodeConfig(config);
            nodeCnfig.setExecutorServiceWorkers(Collections.singletonMap("EXECUTORSERVICENAME", 10));
            RedissonNode processingNode  =  RedissonNode.create(nodeCnfig);
            processingNode.start();
            redissonClient = Redisson.create(config);
            redissonExecutorService = redissonClient.getExecutorService("EXECUTORSERVICENAME");

        } else {
            System.out.println("Redis initialization failed due to missing node list");
        }
    }`

`public class MessageSender implements Callable<String> {

    private RScheduledExecutorService redissonExecutorService;
    private int delayInMillis;

    public MessageSender(RScheduledExecutorService service,int delayInMillis){

        this.redissonExecutorService = service;
        this.delayInMillis = delayInMillis;
    }
    public String call(){

        System.out.println("Scheduling...");
        RScheduledFuture<?> future  = this.redissonExecutorService.scheduleAsync(new RedisRunner("Hello World"), delayInMillis, TimeUnit.MILLISECONDS);
        System.out.print(future.getTaskId());

        return null;
    }
}`

`public class RedisRunner implements Runnable {

    private String message;

    public RedisRunner(){
    }

    public RedisRunner(String message){
        this.message = message;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public void run(){

        System.out.println("Processed: "+message);

    }
}`

It would be great if you could help provide some guidance here and help figure out the issue.

Thanks

**Comment by yjain3326** [comment]
@mrniko Could you help provide some guidance?

**Comment by mrniko** [comment]
Hi,

How long should I wait to get OOM if I run your test?

**Comment by mrniko** [comment]
`ExecutorService` created with `Executors.newFixedThreadPool` swallowing exceptions happen in `MessageSender.call`

**Comment by yjain3326** [comment]
@mrniko are you talking about the redissonExecutorService? that is declared static in main class.
This is how main class looks like:
`public class TestRedisConnections {

    private static String nodeList = "redis://localhost:6379";
    private static final String DELIMITER = ",";
    private static int scanInterval = 5000;
    private static int idleConnectionTimeout = 30000;
    private static int masterIdleConnectionPool = 50;
    private static int masterConnectionPoolSize = 250;
    private static int slaveIdleConnectionPool = 50;
    private static int slaveConnectionPoolSize = 250;
    private static int connectionTimeout = 30000;
    private static int readTimeout = 30000;
    private static int executorWorkerThreads = 10;

    private static RedissonClient redissonClient;
    private static RScheduledExecutorService redissonExecutorService;
    private static final String EXECUTORSERVICENAME = "scheduler";

    public static void init() {

        Config config = new Config();

        if (nodeList != null) {
            StringTokenizer nodes = new StringTokenizer(nodeList, DELIMITER);
            System.out.println("1");
            while (nodes.hasMoreTokens()) {
                config.useReplicatedServers()
                        .addNodeAddress(nodes.nextToken());
            }
            System.out.println("2");
            config.useReplicatedServers().setScanInterval(5000);
            config.useReplicatedServers().setIdleConnectionTimeout(30000);
            config.useReplicatedServers().setMasterConnectionMinimumIdleSize(50);
            config.useReplicatedServers().setMasterConnectionPoolSize(250);
            config.useReplicatedServers().setSlaveConnectionMinimumIdleSize(50);
            config.useReplicatedServers().setSlaveConnectionPoolSize(250);
            config.useReplicatedServers().setConnectTimeout(30000);
            config.useReplicatedServers().setTimeout(30000);

            RedissonNodeConfig nodeCnfig = new RedissonNodeConfig(config);
            nodeCnfig.setExecutorServiceWorkers(Collections.singletonMap("EXECUTORSERVICENAME", 10));
            RedissonNode processingNode  =  RedissonNode.create(nodeCnfig);
            processingNode.start();
            redissonClient = Redisson.create(config);
            redissonExecutorService = redissonClient.getExecutorService("EXECUTORSERVICENAME");

        } else {
            System.out.println("Redis initialization failed due to missing node list");
        }
    }
    public static void main(String args[]){

        int duration = 120;
        int totalThreads = 150;
        int delayInMillis = 30000;
        System.out.println("params are: "+duration+" "+totalThreads+" "+delayInMillis);
        init();

        long currentTime = System.currentTimeMillis();
        Calendar time = Calendar.getInstance();
        time.add(Calendar.MINUTE,duration);

        try {
            ExecutorService service = Executors.newFixedThreadPool(totalThreads);
            while(currentTime < time.getTimeInMillis()){
                try{

                    for(int i = 0;i<totalThreads; i++){
                        service.submit(new MessageSender(redissonExecutorService, delayInMillis));
                    }
                    currentTime=System.currentTimeMillis();
                    Thread.sleep(1000);
                }catch(Exception ex){
                    System.out.println("Exception in Main: "+ ex.getMessage());
                    ex.printStackTrace();
                }

            }

            service.shutdown();
            System.out.print("================Done Scheduling..............");

        } catch (Exception e) {
            e.printStackTrace();
        }


    }
}
`

Ran it for more than 2 hours to see the issue.

**Comment by mrniko** [comment]
RedisRunner should be also a static class
