### ISSUE TITLE
Removed entries in RMapCache Through Eviction Process Still able to see through Redis-cli

### ISSUE THREAD

**Issue by manojcv** [redisson/redisson#1151]
I am Using the RMapCache<K,V> and using the Method  putIfAbsent(K key, V value, long ttl, TimeUnit ttlunit) . 
I want to use the Eviction functionality i.e provided so I am giving ttl as 45 Sec. 
After 45 Sec when i check the Entry in the MapCache From the ReddisonClient at runtime i didnt found the entry 
But when i check the same in the Redis-cli using HGETALL i can still able to found this Entry that was Deleted through Eviction Process by Redisson 
SomeTimes even after 5 min i can able to see the Entry in the Redis-cli even Though it can't be able to find from the Redissonclient after 45 Secs

**Comment by mrniko** [comment]
Hi, removing of stale RMapCache entries is not executed in realtime. That's why you able to see stale value through redis-cli

**Comment by manojcv** [comment]
Hi ,

Could you Please Eloberate the statement 
_**removing of stale RMapCache entries is not executed in realtime**_

**Comment by manojcv** [comment]
Hi,

When checking for the above issue I found a similar issue was raised in the below link
https://stackoverflow.com/questions/46824834/expired-redisson-keys-still-visible-in-redis-cli/46838604#46838604
where @Redisson_RuiGu Mentioning that 
Redis does not support individual element eviction out of the box for hashes. So Redisson has built its own solution and named it MapCache.
the hash in the redis-cli eventually will disappear when the Redisson expiration process kicks in.
so Is this Issue because of delay in Redisson expiration process kicks in

Here Redisson expiration process kicks in process means Removing of stale RMapCache entries could you please confirm on this

**Comment by mrniko** [comment]
I confirm that Redisson cleans stale entries of RMapCache and there are no Redis process to handle that

**Comment by manojcv** [comment]
Thank You For Confirming. I am closing this Issue
