### ISSUE TITLE
AvroJacksonCodec vs Avro Direct Binary

### ISSUE THREAD

**Issue by eklinger** [redisson/redisson#1153]
Hello,
Can you please tell me the difference between AvroJacksonCodec in Redisson vs creating my own codec using Avro's BinaryEncoder directly? Does the Jackson codec covert the object to JSON first and then to binary? E.g. is it wrapping my objects in { } and also writing the field names? Thanks

**Comment by mrniko** [comment]
Jackson coverts object directly into Avro format without any intermediate JSON objects.

**Comment by eklinger** [comment]
Hi,
In that case why does Redis show this as my Long value:
"\xe2\xeb\xad\xbc\xf5\xd8\x95\xd4\xaf\x01"
I would expect it to be exactly 8 bytes?
I am using the serializer like so:
    final static AvroJacksonCodec longCodec = new AvroJacksonCodec(Long.class, new AvroSchema(SchemaBuilder.builder().longType()));

Thank you

**Comment by eklinger** [comment]
Looks like this is a result of the zig zag encoding for varints. So it is as expected. Thanks
