### ISSUE TITLE
Redisson will be unable to work after redis cluster reboot.

### ISSUE THREAD

**Issue by shiftyman** [redisson/redisson#1163]
Redisson runs base on redis-cluster mode, and every thing looks cool.  When redis cluster nodes all down, the redisson is unable to work and throws connection exception. Howerer, when the redis cluster recovered, the redisson is still unable to work and throws null pointer exception!!!!!!!

I did this test base on redisson 3.3.0.

**Comment by mrniko** [comment]
Could you please show stacktrace and also try it with latest version?
