### ISSUE TITLE
Redisson Client hangs on creation

### ISSUE THREAD

**Issue by Flakesz** [redisson/redisson#1164]
Hey guys,

currently trying redis + redisson (v3.5.5), so this might be an easy question for some of you. Anyways as soon as I create my Redisson Client (config seems right), the client hangs in the create statement indefinitely without any exception or timeout, etc (waited for over an hour to hopefully see some error, sadly none). 
To the setup: Win10 + Ubuntu subsystem running redis on standard port (6379), single server setup. In its config the redis server is binding to 127.0.0.1 (also tried disabling protected mode). RedisDesktop Manager and Jedis connect just fine without any issues. 

**Code (Kotlin):**
````
val config = Config()
    config.useSingleServer()
            .setAddress("redis://localhost:6379") // redis://127.0.0.1 does not work either
            .setDatabase(0)
            .setSslEnableEndpointIdentification(false)
            .setConnectTimeout(10)

    val redisson = Redisson.create(config)
````

Hope someone can help, as I couldn't find anything related to this anywhere online.

**Stacktrace :** 
```
"main" #1 prio=5 os_prio=0 tid=0x0000000004f46000 nid=0x37450 waiting on condition [0x0000000004f3e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000076b9ae160> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at org.redisson.misc.RedissonPromise.syncUninterruptibly(RedissonPromise.java:168)
        at org.redisson.misc.RedissonPromise.syncUninterruptibly(RedissonPromise.java:39)
        at org.redisson.connection.MasterSlaveConnectionManager.initSingleEntry(MasterSlaveConnectionManager.java:277)
        at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:165)
        at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:32)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:231)
        at org.redisson.Redisson.<init>(Redisson.java:117)
        at org.redisson.Redisson.create(Redisson.java:156)
```

**Comment by jackygurui** [comment]
Can you show us the full thread dump please?

**Comment by Flakesz** [comment]
There you go:
[redissonHang.dump.txt](https://github.com/redisson/redisson/files/1511159/redissonHang.dump.txt)

**Comment by jackygurui** [comment]
It looks very much like so. The workaround `-Dorg.jboss.netty.epollBugWorkaround=true` is only a flag to indicate a different logic is required to work around this issue, and that has to be implementation specific, in this case it is only useful for jboss. Maybe we too need to do something similar. @mrniko can you advice?

**Comment by mrniko** [comment]
Hmm I have never met such problem on Windows 7

**Comment by Flakesz** [comment]
Yeah I was not aware that jboss is an own project and the netty package actually "**io.netty**" is.
Which makes it obvious that that workaround wouldnt fix anything. Anyway they closed that netty ticket as it was for version **3.9** & at that point they had **4.0** on master branch. 

As for Redisson **3.5.5** seems to be using **4.0.23** of netty, which makes it seem like its not fixed.

**Comment by mrniko** [comment]
@Flakesz I'm sorry but Redisson 3.5.5 uses 4.1.16 version of netty

**Comment by Flakesz** [comment]
Strange I see all netty imports in RedisClient referencing to netty 4.0.23. Meanwhile in the pom for redisson it says for all netty components 4.1.16 as ex:

```
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.16.Final</version>
            <scope>provided</scope>
</dependency>
```

Anyways it should be fixed for version 4+. So I guess I wont be able to use Redisson under Win 10 anytime soon.

**Comment by jackygurui** [comment]
I think you may have a version conflict with netty

**Comment by Flakesz** [comment]
Yeah I believed the same and created a clean project with only Redisson as a dependency and it worked. So for the bigger project, I disabled all dependencies and reenabled one by one to find the cause. 

Turns out its was:
`
compile group: 'org.apache.hbase', name: 'hbase-client', version: '1.3.1'`
Was expecting sth like jetty to be the cause but in the end it was the hbase-client.

**Comment by mrniko** [comment]
> So I guess I wont be able to use Redisson under Win 10 anytime soon.
> Overriding netty-all to 4.1.16 seems to work for both 

Do not give up hope :)
