### ISSUE TITLE
java.lang.IndexOutOfBoundsException: fromIndex: 0 toIndex: 2 size: 0

### ISSUE THREAD

**Issue by lxjchengcu** [redisson/redisson#1165]
Caused by: java.lang.IndexOutOfBoundsException: fromIndex: 0 toIndex: 2 size: 0
        at org.redisson.RedissonList.subList(RedissonList.java:572)
        at com.westone.message.processor.RedissionImp.deleteMessage(RedissionImp.java:210)
        at com.westone.message.processor.MessageProcessor.deleteMessage(MessageProcessor.java:484)

The source code is

RList<String> userInboxRList = redisson.getList(rListKey);
int confirmedIndex = userInboxRList.indexOf(confirmedMessageId);
List<String> messageIds = userInboxRList.subList(0, confirmedIndex + 1);

the error occurs when get a sub list from Rlist object, use 'indexOf' to get index number of specified string, it returns 1, it shows that there should be some elements in specified region, but reported no data  
found, did somebody meet same issue? how did it happen?

BTW, the redission version is 3.4.2

**Comment by jackygurui** [comment]
Could it be that between the last two lines, another client has removed the all the element in the list?

**Comment by lxjchengcu** [comment]
No, it is impossible, only one thread would delete data in the list.

**Comment by jackygurui** [comment]
What you are describing is a key on the server side has gone. This might be a result of a deletion or eviction. You should be able to verify by monitor at the server side.

**Comment by lxjchengcu** [comment]
Thank you, I will check it
