### ISSUE TITLE
MapLoader seems to hang if you try to check the same null key, more than once

### ISSUE THREAD

**Issue by bhoover10001** [redisson/redisson#1170]
It looks like the second time you try to get a key that was null through a map loader, the loader will simply hang.

I was able to reproduce this in RedissonMapCacheTest.java with the following code

    @Test
    public void testMapLoaderGetMulipleNulls() {
        Map<String, String> cache = new HashMap<String, String>();
        cache.put("1", "11");
        cache.put("2", "22");
        cache.put("3", "33");
        
        RMap<String, String> map = getLoaderTestMap("test", cache);
        assertThat(map.get("0")).isNull();
        assertThat(map.get("1")).isEqualTo("11");
        assertThat(map.get("0")).isNull(); // This line will never return anything and the test will hang
    }

    // This code will work fine, because the keys without values are different.
    @Test
    public void testMapLoaderGetMulipleNullsDifferentKeys() {
        Map<String, String> cache = new HashMap<String, String>();
        cache.put("1", "11");
        cache.put("2", "22");
        cache.put("3", "33");
        
        RMap<String, String> map = getLoaderTestMap("test", cache);
        assertThat(map.get("0")).isNull();
        assertThat(map.get("1")).isEqualTo("11");
        assertThat(map.get("-1")).isNull(); 
    }

I'm running Windows 10 with Redis Version 3.2.100 64 bit version.  This is happening on Redisson 3.5.5 and the current master branch.

**Comment by mrniko** [comment]
Thanks for report! Fixed
