### ISSUE TITLE
Redisson RScript eval codec is not honored

### ISSUE THREAD

**Issue by valodzka** [redisson/redisson#1172]
Version: 3.5.5, code:

    c.getScript().eval(RScript.Mode.READ_WRITE,
                    new JsonJacksonCodec(),
                    "return redis.call('SET', KEYS[1], ARGV[1]);",
                    RScript.ReturnType.BOOLEAN,
                    ImmutableList.of("test"), "x");

Command executed:

    "EVAL" "return redis.call('SET', KEYS[1], ARGV[1]);" "1" "test" "x"

Expected result: values and/or keys encoded with json codec

**Comment by mrniko** [comment]
Thanks for report! Fixed
