### ISSUE TITLE
redission AtomicObject in debug + breakpoint mode cause a different result

### ISSUE THREAD

**Issue by xuminwlt** [redisson/redisson#1173]
version:3.5.4
```
@Test
    public void cacheLongTest() {
        RAtomicLong rAtomicLong = redissonClient.getAtomicLong("testKey");
        System.out.println(rAtomicLong.isExists());
    }
```
At first,I delete the key,confirm the key not exist.
run this test and debug with no breakpoint the result is : false

secend,  debug + breakpoint at
```
RAtomicLong rAtomicLong = redissonClient.getAtomicLong("testKey");
```
system out the result is : true

why?

我是不是应该用中文。

**Comment by jackygurui** [comment]
This is because the debugger has invoked `get()` method, which has in term initialised the key within Redis. In your case, you should have an initial value of `0` against the `testKey` in Redis.
