### ISSUE TITLE
RedissonRedLock issue

### ISSUE THREAD

**Issue by JackEggie** [redisson/redisson#1175]
你好，
在使用RedissonRedLock发现了一个疑似bug的问题。

首先，redlock的算法中提到：

> 当且仅当从大多数（这里是3个节点）的Redis节点都取到锁，并且使用的时间小于锁失效时间时，锁才算获取成功。

但是RedissonRedLock实际使用中的行为与上面不一致。
将RedissonRedLockTest中的测试用例testLockSuccess修改为如下：

        RLock lock1 = client1.getLock("lock1");
        RLock lock2 = client1.getLock("lock2");
        RLock lock3 = client2.getLock("lock3");
        
        Thread t1 = new Thread() {
            public void run() {
                lock1.lock();
            }
        };
        t1.start();
        t1.join();

        RedissonMultiLock lock = new RedissonRedLock(lock1, lock2, lock3);
        assertThat(lock.tryLock(500, 5000, TimeUnit.MILLISECONDS)).isTrue();
        lock.unlock();

        lock1.delete();

上面代码中的assert只在lock3被锁住的时候能通过，lock1或者lock2被锁住时都assert失败。

这个问题在调用`public boolean tryLock()`方法时则不会出现。

查看了源码以后发现，出现上述现象的原因是，在获取已经被锁住的lock1或者lock2时，waitTime与RedLock的waitTime是一样的（代码在[RedissonMultiLock](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L152)）。所以只要lock1或者lock2获取超时，RedLock就获取超时返回false了。

而redlock的算法中提到：

> 如果服务器端没有在规定时间内响应，客户端应该尽快尝试另外一个Redis实例。

请帮忙看下这个问题该如何解决。谢谢。

参考资料：[Redlock算法](http://redis.cn/topics/distlock.html)

**Comment by jackygurui** [comment]
> 如果服务器端没有在规定时间内响应，客户端应该尽快尝试另外一个Redis实例。

指的是服务端超时，不是加锁加不上吧？

**Comment by JackEggie** [comment]
补充一下我的理解。

> 如果服务器端没有在规定时间内响应，客户端应该尽快尝试另外一个Redis实例。

这里所指的规定时间，应该就是如下方法的waitTime变量。

`public boolean tryLock(long waitTime, long leaseTime, TimeUnit unit)`

如我之前所述，在RedissonMultiLock的144行的循环内（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L144)），会在152行的代码处迭代每一个RLock去尝试加锁（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L152)），而该处的waitTime为整个RedissonRedLock的剩余waitTime（我认为这里的逻辑存在问题）。

这样的逻辑会导致如下问题，假设RedissonRedLock包含3个RLock，分别为lock1，lock2，lock3（假设RLockList中的顺序为[lock1，lock2，lock3]）。

当lock1，lock2成功获取到，lock3被占用导致获取超时失败时，会进入到如下代码段（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L161)），判断条件符合，并且跳出循环，这时会走完整个流程并且返回true。

当lock1被占用而获取超时失败时（或者lock1获取成功，而lock2获取超时失败时），由于获取lock1的等待时间即为RedissonRedLock的获取剩余时间，因此152行的代码处（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L152)）必然会超时，并且跳入181行代码（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L181)），**这时由于lock1获取超时导致整个RedissonRedLock获取超时，将不再会尝试后续的RLock的获取操作**，我认为这里的行为是与Redlock的算法背道而驰的。

也就是说，如果第一个锁获取不到，那也应该去尝试第二个锁，第三个锁等等，而不是第一个锁超时了，就直接返回失败。

**Comment by JackEggie** [comment]
上面是我对RedissonMultiLock的public boolean tryLock(long waitTime, long leaseTime, TimeUnit unit) throws InterruptedException方法的理解。

如果我对该处代码的理解有误，或者是我的测试场景是错误的，麻烦请指出，谢谢。

**Comment by jackygurui** [comment]
> 如果服务器端没有在规定时间内响应，客户端应该尽快尝试另外一个Redis实例。

这里指的不是`waitTime`超时，而是指的该节点宕机或掉线的情况。

看原文的话就应该比较好理解了：
> This prevents the client from remaining blocked for a long time trying to talk with a Redis node which is down: if an instance is not available, we should try to talk with the next instance ASAP.

**Comment by jackygurui** [comment]
> 如我之前所述，在RedissonMultiLock的144行的循环内（代码位置），会在152行的代码处迭代每一个RLock去尝试加锁（代码位置），而该处的waitTime为整个RedissonRedLock的剩余waitTime（我认为这里的逻辑存在问题）。

这正是按照算法描述的第四步里所说的计算方式吧：
> 4. If the lock was acquired, its validity time is considered to be the initial validity time minus the time elapsed, as computed in step 3.

你觉得呢？

**Comment by jackygurui** [comment]
> 这时由于lock1获取超时导致整个RedissonRedLock获取超时，将不再会尝试后续的RLock的获取操作

照你的说法把`testLockSuccess`里的代码换成为里面的`lock1`先加锁，代码运行仍然没问题的。

**Comment by JackEggie** [comment]
> 照你的说法把testLockSuccess里的代码换成为里面的lock1先加锁，代码运行仍然没问题的。

这里直接换成lock1先加锁，测试用例能通过的原因是184行代码（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/RedissonRedLockTest.java#L184)）没有assert，该处的锁实际上没有获取到。

**Comment by JackEggie** [comment]
另外还发现public boolean tryLock(long waitTime, long leaseTime, TimeUnit unit)方法中的194行（[代码位置](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L194)）与redlock算法的原文行为是不一致的。

> If the lock was acquired, its validity time is considered to be **the initial validity time minus the time elapsed**, as computed in step 3.

> 如果取到了锁，key的真正有效时间等于**有效时间减去获取锁所使用的时间**（步骤3计算的结果）。
