### ISSUE TITLE
Eviction Scheduler doesn't remove expired keys from list 

### ISSUE THREAD

**Issue by rexave** [redisson/redisson#1179]
Hello,

[I asked a question on stackoverflow](https://stackoverflow.com/questions/47288183/redisson-eviction-on-set-map) about how to well configure redisson to make eviction scheduler working on set in redis, but no answer yet :(. Could you help us by answering on this post or by improving the wiki about this point ?

Many thanks !

**Comment by jackygurui** [comment]
Please see my answers here: https://stackoverflow.com/questions/46824834/expired-redisson-keys-still-visible-in-redis-cli/46838604#46838604

**Comment by rexave** [comment]
Thanks for your answer but i think this is another subject. I'm not using the same Interface than the one you mentionned in the your answer.

**Comment by jackygurui** [comment]
SetCache is the same as the MapCache in terms of the element eviction.

**Comment by rexave** [comment]
So it doesn't work here. Is there anyway i can use to debug the eviction scheduler, see if it's happening, what it does ? Could you help me to point the checks i should do ?

**Comment by mrniko** [comment]
@rexave 

Done. I added logging for all eviction tasks. Set Logging level to DEBUG to see output.
