### ISSUE TITLE
Redisson is not reading the values set by external redis clients

### ISSUE THREAD

**Issue by ramchris** [redisson/redisson#1180]
I am creating a set through Medis, a Redis client or FastoRedis. When I try to read the same using redissonClient.getSet(key), I see an exception being thrown saying "Unable to evaluate the expression Method threw 'org.redisson.client.RedisException' exception." while debugging the set in IntelliJ. Why can't redisson is reading the value for the key? I noticed one thing when the redisson sets the value, it has quotes. But when you set a string from external clients, it doesn't have any quotes and redisson can't seems to be recognizing it.

**Comment by jackygurui** [comment]
Redisson by default uses JacksonJson as data codec, meaning it will try to use Jackson's ObjectMapper to deserialise the data from Redis. In your case those data were set by Medis client, which is likely not using the same encoding method.

This is the same reason why you see quotes around strings in Redis from Redisson. When Jackson serialise an object to a `VALID` string type in JSON format, it wraps the content around with `"` to comply with the format standard.

**Comment by jackygurui** [comment]
If you don't like to use JSON as the encoding scheme. Try `StringCodec` instead.

**Comment by ramchris** [comment]
I did use and I was able to make progress but ran into another issue.  I modified the key/value pair in the 3rd party client and when Redisson is trying to read the same,  it is throwing the following exception.

`org.redisson.client.RedisException: ERR Error running script (call to f_41086849b5c119624298370915555b51b921688a): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x53f43883, L:/10.214.44.93:53224 - R:/10.160.48.21:6379] command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, HeartBeat, redisson__timeout__set:{HeartBeat}, redisson__idle__set:{HeartBeat}, redisson__map_cache__last_access__set:{HeartBeat}, {HeartBeat}:redisson_options, 1512680397149, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256)]`

**Comment by jackygurui** [comment]
MapCache object is entirely a Redisson's own creation which offers you the ability of individual element eviction and other features that is not available in other clients. If you want to use MapCache related features, you need to use Redisson as the only client. If you want to pass data between different clients, then you need to stay with standard Redis objects such as List, Set, Map, etc.
