### ISSUE TITLE
Add executeSchedule methods to RScheduledExecutorService

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#1185]
executeSchedule methods return void method instead of ScheduledFuture this allow to avoid memory consumption by each schedule.

**Comment by yjain3326** [comment]
@mrniko Thank you for having the request.

**Comment by mrniko** [comment]
Fixed! @yjain3326 Solved with WeakReference technique to track non used futures and release them.

**Comment by yjain3326** [comment]
@mrniko Great! I just tested it and it looks great.
Thank you for  fixing this.
Can you please update here when this is release? we would like to use this asap.

**Comment by mrniko** [comment]
@yjain3326 During a week

**Comment by yjain3326** [comment]
@mrniko does 3.5.6 has this changes?

**Comment by mrniko** [comment]
@yjain3326 No, it doesn't. Please wait for 3.5.7

**Comment by yjain3326** [comment]
@mrniko I saw 3.5.7 was released. Does it have these changes?

**Comment by mrniko** [comment]
@yjain3326 Yes
