### ISSUE TITLE
JVM crashes when using 1000 concurrent redisson threads

### ISSUE THREAD

**Issue by prashantochatterjee** [redisson/redisson#1190]
I am scheduling tasks on a Redisson executor. On every schedule a massive chunk of tasks are submitted on two Redisson executors. I have equal number of workers assigned to each of the two executors 500 and a maximum redisson thread count of 1000. 

I took periodic heap dumps of the JVM and the following was the last dump I captured before the container (my code is running in a docker container) went OOM. It appears to me that the netty's PoolThreadCache continues to increase.
Here is a screenshot of the leak suspect report of the last dump I took:
![redissonnettyerror](https://user-images.githubusercontent.com/33247561/33922416-bdff8a9e-dff0-11e7-9fd5-cbbdefdfd229.png)
I am unable to get the crash dump report of the JVM. Will attach that as soon as I am able to figure out the issue with crash dumps not getting generated.

I am using Redisson 3.5.5. The bundled Netty version is 4.1.16.

**Comment by mrniko** [comment]
Hi!

This issue duplicated with https://github.com/redisson/redisson/issues/1185
Could you try 3.0.0 branch since it's not released yet?

**Comment by prashantochatterjee** [comment]
The issue is not resolved in 3.5.7 release. I did more investigation into it and it appears that its not the JVM that crashes but the container that is restricted to run with an allocated native memory. What is observed is that the native memory usage continues to grow with time until the available memory is exhausted and the container crashes.

I found quite a lot of threads that talk of a native memory leak in Netty threads. I wonder if that is the root cause. I am trying to tweak certain Netty configuration settings to find a fix.

@mrniko Do you want to reopen this issue until we determine the right fix?
