### ISSUE TITLE
Removing class name in serializing an object

### ISSUE THREAD

**Issue by JongLim** [redisson/redisson#1192]
Hi, 

I would like to minimize the data storage in Redis. When putting an Object in a list, I found that the object is serialized and stored in JSON. However, for every field in the json string, it has a class name info "java.lang.String" next a field for example. 

Looking at the source code, https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java#L140, realized that this is added by default. Passing my object mapper to initialize won't work either. 

Is this necessary? Is there a way to disable this? 

Alternatively, I serialized myself an object into a string and put the string into RList<String>. However, then it seems the library serialize one extra time as follow: 

`from "\{\"stepId\":1}\" (application serialize) to "\"{\\\"stepId\\\":1}\"" (how it looks in Redis)`

**Comment by jackygurui** [comment]
The class information is necessary for deserialising non-Jackson-annotated classes. If you want to safe space in Redis, please consider a different codec other than JSON based ones.

**Comment by JongLim** [comment]
Thank you for your reply. In other words, does that mean the class names are unnecessary if all of my applications use Jackson annotation? Could you please recommend one which I can save space and fast?

**Comment by jackygurui** [comment]
> Does that mean the class names are unnecessary if all of my applications use Jackson annotation?

No

> Could you please recommend one which I can save space and fast?

Please refer to  this section in the wiki: https://github.com/redisson/redisson/wiki/4.-data-serialization 

In general, binary codecs outputs are considered more concise than JSON structures. However each has its own problems while bringing in other features. i,e. compression codec can produce smaller result but in expense of some performance. You have to evaluate them yourself based on your own needs.

**Comment by adrian-skybaker** [comment]
I'm unclear why this is a limitation. `JsonTypeInfo` is only needed for polymorphism. If I know the type I am reading into when deserializing, the additional `@class` property is redundant.
