### ISSUE TITLE
failover does not work

### ISSUE THREAD

**Issue by cikezxy** [redisson/redisson#1194]
Hi, 
I'm new to redisson, I setup a redis master-slave environment with 3 sentinels.
But failover does not work when I kill master node, it seems redisson node does not try to connect new master node. I got this exception:
org.redisson.client.RedisConnectionException: MasterConnectionPool no available Redis entries.  Disconnected hosts: [/10.253.119.220:6379]
Here is my redisson configuration, could someone help me? thanks a lot
{
  "masterSlaveServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "password":null,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "loadBalancer":{
      "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveSubscriptionConnectionMinimumIdleSize":1,
    "slaveSubscriptionConnectionPoolSize":50,
    "slaveConnectionMinimumIdleSize":10,
    "slaveConnectionPoolSize":64,
    "masterConnectionMinimumIdleSize":10,
    "masterConnectionPoolSize":64,
    "readMode":"SLAVE",
    "slaveAddresses":[
      "redis://10.253.119.220:6380",
      "redis://10.139.35.32:6380"
    ],
    "masterAddress": "redis://10.253.119.220:6379",
    "database":0
  },
  "sentinelServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "password":null,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "loadBalancer":{
      "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveSubscriptionConnectionMinimumIdleSize":1,
    "slaveSubscriptionConnectionPoolSize":50,
    "slaveConnectionMinimumIdleSize":10,
    "slaveConnectionPoolSize":64,
    "masterConnectionMinimumIdleSize":10,
    "masterConnectionPoolSize":64,
    "readMode":"SLAVE",
    "sentinelAddresses":[
      "redis://10.253.119.220:26379",
      "redis://10.253.119.220:26380",
      "redis://10.139.35.32:26379"
    ],
    "masterName":"mymaster",
    "database":0
  },
  "threads": 0,
  "nettyThreads": 0,
  "codec": null,
  "useLinuxNativeEpoll": false
}

**Comment by mrniko** [comment]
Please Redis configuration and sentinel logs for correct failover handling

**Comment by cikezxy** [comment]
@mrniko Sorry for the late reply
My environment has 1 master(10.253.119.220 6379), 2 slaves(10.253.119.220 6380, 10.139.35.32:26379), 3 sentinels(10.253.119.220 26379,10.253.119.220 26380, 10.139.35.32:26379) 
**_master configuration:_**
protected-mode no
port 6379
daemonize yes
slave-priority 100
logfile "/var/log/redis/redis-6379.log"
_**slave configuration**_
#bind 127.0.0.1
protected-mode no
port 6380
daemonize yes
slaveof 10.253.119.220 6379
slave-priority 90
logfile "/var/log/redis/redis-6380.log"
**_sentinels configuration_**
protected-mode no
port 26379
daemonize yes
sentinel monitor mymaster 10.253.119.220 6379 2
sentinel down-after-milliseconds mymaster 10000
sentinel failover-timeout mymaster 60000 
logfile "/var/log/redis/sentinel-26379.log"
**_sentinel log:_**
20412:X 14 Dec 14:19:05.115 # +try-failover master mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.144 # +vote-for-leader 59d6f2d3e875d8230437f243d11605682b4f0116 20
20412:X 14 Dec 14:19:05.151 # 87d78edf91d9cb3ecda1777cae82dbb0c673ff51 voted for 59d6f2d3e875d8230437f243d11605682b4f0116 20
20412:X 14 Dec 14:19:05.220 # +elected-leader master mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.220 # +failover-state-select-slave master mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.291 # +selected-slave slave 10.139.35.32:6380 10.139.35.32 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.291 * +failover-state-send-slaveof-noone slave 10.139.35.32:6380 10.139.35.32 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.367 * +failover-state-wait-promotion slave 10.139.35.32:6380 10.139.35.32 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.905 # +promoted-slave slave 10.139.35.32:6380 10.139.35.32 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.905 # +failover-state-reconf-slaves master mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:05.960 * +slave-reconf-sent slave 10.253.119.220:6380 10.253.119.220 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:06.235 # -odown master mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:06.705 * +slave-reconf-inprog slave 10.253.119.220:6380 10.253.119.220 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:06.705 * +slave-reconf-done slave 10.253.119.220:6380 10.253.119.220 6380 @ mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:06.805 # +failover-end master mymaster 10.253.119.220 6379
20412:X 14 Dec 14:19:06.805 # +switch-master mymaster 10.253.119.220 6379 10.139.35.32 6380
20412:X 14 Dec 14:19:06.805 * +slave slave 10.253.119.220:6380 10.253.119.220 6380 @ mymaster 10.139.35.32 6380
20412:X 14 Dec 14:19:06.805 * +slave slave 10.253.119.220:6379 10.253.119.220 6379 @ mymaster 10.139.35.32 6380
20412:X 14 Dec 14:19:16.816 # +sdown slave 10.253.119.220:6379 10.253.119.220 6379 @ mymaster 10.139.35.32 6380
20412:X 14 Dec 16:13:10.329 # +sdown slave 10.253.119.220:6380 10.253.119.220 6380 @ mymaster 10.139.35.32 6380
20412:X 14 Dec 16:13:10.329 # +sdown sentinel 87d78edf91d9cb3ecda1777cae82dbb0c673ff51 10.253.119.220 26379 @ mymaster 10.139.35.32 6380

**Comment by mrniko** [comment]
Sorry, I'm unable to reproduce that. Do you see lines like these in Redisson logs during failover:

`[redisson-3-8] INFO org.redisson.connection.MasterSlaveEntry - master 127.0.0.1/127.0.0.1:6389 has changed to /127.0.0.1:6379
[redisson-netty-1-15] INFO org.redisson.connection.pool.MasterConnectionPool - 10 connections initialized for /127.0.0.1:6379`
