### ISSUE TITLE
多线程环境下，线程卡死的情况

### ISSUE THREAD

**Issue by HorizonHero** [redisson/redisson#1196]
我的调用程序启动8个节点实例，每个节点有50个线程，使用RLocalCachedMap。
RLocalCachedMap<Integer, Integer> temp = redissonClient.getLocalCachedMap("tasks", options);
------------
temp.readAllMap();
------------
当执行到readAllMap();时有些线程就卡住了，然后就一直不再执行了。
------------
options是这样的：
LocalCachedMapOptions options = LocalCachedMapOptions.defaults()
                .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.LFU)
                .cacheSize(1000)
                .syncStrategy(LocalCachedMapOptions.SyncStrategy.NONE)
                .timeToLive(10, TimeUnit.SECONDS)
                .maxIdle(10, TimeUnit.SECONDS);

另外，redis使用一主二从，读写都在主上。

**Comment by jackygurui** [comment]
`readAllMap()`方法虽说已经在`RLocalCachedMap`继承了，但是两者的理念有点冲突，使用的时候需要特别注意。

`RLocalCachedMap`的主要目的是让本地的JVM缓存一部分Redis里面的内容。其目的是为了不给下层的Redis造成太多压力。然而`readAllMap()`这个方法是让服务端把所有的内容聚合以后再发过来。这个操作是很消耗服务端性能的。而且由于Redis是单线程的，在执行这条指令的时候是不会处理其他任何指令的，所以会造成有些线程的阻断。集合里的数据越多，阻断时间越长。

如果你需要在你的本地缓存里预先加载所以数据的话，可以使用`preloadCache()`方法代替。
