### ISSUE TITLE
Reading from Elasticache replica nodes 

### ISSUE THREAD

**Issue by icsdev1** [redisson/redisson#1198]
Hello

I'm using Redisson ( `redisson-all-3.5.5.jar` )to connect to AWS Elasticache running in Cluster mode disabled. The cluster has 1 primary and 2 replica nodes.  The application uses Redisson's Spring Cache abstraction support. 
I have configured Redisson in Master-Slave mode providing the primary end-point as master and replica end-points as slaves.
I load the application by making hundreds of simultaneous requests hitting the cache.
When I view CloudWatch metrics, I notice that there are no CacheHits for the replica nodes. All the requests seem to be going only to the master/primary node. 
I have tried `SLAVE` as well as `MASTER-SLAVE` for `read-mode` attribute. I played around with the LoadBalancer class trying out RoundRobin and Random , but to no luck. 
The idea behind using multiple replicas was to distribute read load and not just for high-availability. It is important for us to read from slave nodes. Is there some setting that needs to be enabled to allow Redisson to read from slave nodes ?

**Comment by jackygurui** [comment]
Can you try it again with version 3.5.6 since it contains a fix related read mode?

**Comment by icsdev1** [comment]
Hello,
Changing to 3.5.6 did not help. As you can see from the image below, almost 99% of the calls go to Primary ( node named `dec-20-disabled-001` ). My requirement is to distribute the load equally between primary and replicas.


<img width="1256" alt="screen shot 2017-12-20 at 13 56 47" src="https://user-images.githubusercontent.com/6214197/34197751-d1aa46ea-e58d-11e7-8bd8-18d49565570b.png">


This is the Spring config I'm using.

 ```
<bean id="cacheManager" class="org.redisson.spring.cache.RedissonSpringCacheManager">
		<constructor-arg index="0" ref="master-slave"></constructor-arg>
		<constructor-arg index="1">
			<map>
				<entry key="availability" value-ref="redissonCacheConfig"></entry>
				<entry key="product" value-ref="redissonCacheConfig"></entry>
			</map>
		</constructor-arg>
	</bean>

<redisson:client id="master-slave">
		<redisson:master-slave-servers 
			load-balancer-ref="loadBalancer"
			read-mode="SLAVE"
			master-connection-pool-size="5"
			master-connection-minimum-idle-size="4"
			slave-connection-pool-size="20"
			slave-connection-minimum-idle-size="20"
			master-address="redis://dec-20-disabled-001.xxx.cache.amazonaws.com:6379">
			<redisson:slave-address value="redis://dec-20-disabled-002.xxx.cache.amazonaws.com:6379" />
			<redisson:slave-address value="redis://dec-20-disabled-003.xxx.cache.amazonaws.com:6379" />
		</redisson:master-slave-servers>
	</redisson:client>
	
	<bean 
		id="loadBalancer"
		class="org.redisson.connection.balancer.RoundRobinLoadBalancer"/>
```

**Comment by mrniko** [comment]
Hi! 

You should use `redisson:replicated-servers` instead of `redisson:master-slave-servers`

**Comment by icsdev1** [comment]
Hello Nikita,

I'm still seeing the same behaviour - all cache hits go to primary. 
This is my minimal settings for `replicated-servers` - 

```
<redisson:client id="replicated">
		<redisson:replicated-servers>
			<redisson:node-address value="redis://dec-20-disabled-001.xxx.cache.amazonaws.com:6379" />
			<redisson:node-address value="redis://dec-20-disabled-002.xxx.cache.amazonaws.com:6379" />
			<redisson:node-address value="redis://dec-20-disabled-003.xxx.cache.amazonaws.com:6379" />
		</redisson:replicated-servers>
	</redisson:client>
```

**Comment by mrniko** [comment]
Could you share your test code?

**Comment by mrniko** [comment]
Also you can try to debug it just making a point at `MasterSlaveEntry.connectionReadOp` method

**Comment by icsdev1** [comment]
My test setup consists of three parts - 

1. ElastiCache Redis cluster
2. Spring MVC app with Spring Cache + Redisson client, deployed on a EC2 Tomcat, talking to the above cluster
3. JMeter script to load test the app

Spring MVC app location : https://github.com/icsdev1/redisson-test

**Comment by johnou** [comment]
@icsdev1 are you using a RMapCache?

**Comment by johnou** [comment]
@mrniko looks like RedissonMapCache is fundamentally broken in the sense that it doesn't scale horizontally when adding read replicas, as org.redisson.RedissonMapCache#getOperationAsync uses an eval command it must be executed by master, correct?

**Comment by johnou** [comment]
As I feared, we'll drop Redisson L2 cache for now, at the current rate it won't scale for our service, CPU usage is too high on master, adding replicas doesn't help and it won't scale vertically either as Redis is single threaded.

**Comment by mrniko** [comment]
@johnou Would implementation of `getUnsafe` method help you? This method would be split into two different operations: 
1. read object
2. then update idle time / access time

**Comment by johnou** [comment]
@mrniko I was thinking of the same thing but 2. would still require hitting master with eval no? there might be a better way to deal with eviction.

**Comment by jackygurui** [comment]
@johnou I think to add more shards instead of adding slaves would be a better solution, don't you think?

**Comment by johnou** [comment]
@jackygurui in the long run yes, but with the current SPI Hibernate offers for caching I am not sure how feasible that would be.

**Comment by johnou** [comment]
I just wanted to comment on this issue to say it's a feature, not a bug.

**Comment by jackygurui** [comment]
@johnou Do you think a locally cached map can help?

**Comment by johnou** [comment]
We already had a local cache sitting before the redis map so I am not so sure that would help, if we end up with more than 25k concurrent players I might need to revisit this, let's see what happens :+1:

**Comment by jackygurui** [comment]
@johnou Please let us know how you are getting on.

**Comment by GnanasoundariSoundarajan** [comment]
We are using redisson 3.5.7 version  and aws redis without cluster and 5 replicas. In redisson client config , we are using replicatedServeronfig only.

We are also facing the same issue, all the cache request goes to primary node. Replicas are getting in terms of 10Ks, where as primarynode getting the requests in terms of 100K.

Please let us know how to distribute the load across replicated nodes.

**Comment by jpadilladev** [comment]
Is there any plans to improve _RedissonSpringCacheManager_ to scale horizontally reading and writting on replicas?
I´m using _replicatedServersConfig_ along with Spring Cache, and it fails when there is no Redis master node running.

**Comment by mrniko** [comment]
> Are there any plans to improve RedissonSpringCacheManager to scale horizontally reading and writting on replicas?

replicas are not designated for write operation

**Comment by jpadilladev** [comment]
> replicas are not designated for write operation

So what is in your opinion the best configuration to use Spring Cache + Redisson for HA?

**Comment by mrniko** [comment]
Redis cluster with multiple masters.

**Comment by mabaya-alaa** [comment]
I'm using aws redis without cluster with 2 replicas, using replicatedServeronfig in redisson and facing the same problem, all read operations are using master node only, event thought I specifically configured reamMode to slave.
did anyone find a solution for this?
