### ISSUE TITLE
BitMap (RBitSet) questions

### ISSUE THREAD

**Issue by waseemahmad** [redisson/redisson#1201]
I have two questions.

1. Are there any plans to extend RBitSet index range beyond Integer.MAX_VALUE*2?  Since it supports distributed implementation of BitSet and its operations - having this limitation removed would be very helpful.

2. There have been studies suggesting Roaring Bitmaps as very powerful mechanism to support space-saving fast bitwise operations on bitmaps ( operations are performed on compressed representations). See e.g.  http://db.ucsd.edu/wp-content/uploads/2017/03/sidm338-wangA.pdf. When do we plan to having a roaring bitmap implementation - be it PRO or community version of Redisson.

**Comment by mrniko** [comment]
Hi!

Yes, I plan to implement ClusteredBitSet object for PRO version. And also going to research ability to implement Roaring Bitmap too. Thanks for pointing out!

**Comment by jarrenwe26** [comment]
Help I’m being controld by hackers

**Comment by mrniko** [comment]
ClusteredBitSet implementation based on Roaring Bitmap added to Redisson PRO 2.10.7 / 3.5.7 versions.

**Comment by waseemahmad** [comment]
Hi @mrniko - I have just ordered for the PRO trial version. Looking forward to trying out the ClusteredBitSet implementation. Also - can you please confirm if we need to have CRoaing module built to Redis : https://github.com/aviggiano/redis-roaring?

**Comment by mrniko** [comment]
@waseemahmad current implementation based on lua scripts and doesn't require redis module.

**Comment by waseemahmad** [comment]
Hi @mrniko - Is there a latency downside in not using redis module if we have the ability to do so? Thanks.

**Comment by mrniko** [comment]
@waseemahmad Hi! I didn't compare performance between my implementation and redis-roaring module. I don't think there is a much difference as my implementation based on Redis structures.

**Comment by mrniko** [comment]
@waseemahmad Hi! I have added Roaring Module support to 3.5.7-1 version. It's available through `RedissonClient.getClusteredRoaringModuleBitSet` and `RedissonClient.getRoaringModuleBitSet` methods.

**Comment by waseemahmad** [comment]
Thanks @mrniko - evaluating it.
