### ISSUE TITLE
MapCache listener not working on cross-plateform environment

### ISSUE THREAD

**Issue by ZongoForSpeed** [redisson/redisson#1205]
Hello,

I've encountered a bizarre bug when using MapCache listeners between windows and linux.
My setup:
redisson 3.5.6
redis 3.2.11 on ubuntu 16.04

`Config config = new Config();
    config.useSingleServer().setAddress("redis://************:6379");
    RedissonClient redisson = Redisson.create(config);
    
    RMapCache<String, Integer> mapCache = redisson.getMapCache("test");
    
    mapCache.addListener((EntryCreatedListener) event -> System.out.println("onCreated(" + event.getKey() + ", " + event.getValue() + ")"));
    mapCache.addListener((EntryUpdatedListener) event -> System.out.println("onUpdated(" + event.getKey() + ", " + event.getValue() + ")"));
    mapCache.addListener((EntryRemovedListener) event -> System.out.println("onCreated(" + event.getKey() + ", " + event.getValue() + ")"));
    mapCache.addListener((EntryExpiredListener) event -> System.out.println("onExpired(" + event.getKey() + ", " + event.getValue() + ")"));
    
    // with ttl = 10 seconds
    Integer prevValue = mapCache.put("1", 10, 10, TimeUnit.SECONDS);
    // ... the rest is exactly the same code as in the class MapCacheExamples found in the redisson-examples project
`

When running the test I've got the following errors:
`[redisson-netty-1-4] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: io.netty.buffer.ByteBufInputStream@1fd104f3; line: 1, column: 2]
`
(cf. the attached file for all the callstack
[exception.log.txt](https://github.com/redisson/redisson/files/1584870/exception.log.txt )

The code runs correctly when connecting to a redis server running on windows.

The error seems to come from the class **MapCacheEventCodec**:
`    private Object decode(ByteBuf buf, State state, Decoder<?> decoder) throws IOException {
        int keyLen;
        if (PlatformDependent.isWindows()) {
            keyLen = buf.readIntLE();
        } else {
            keyLen = (int) buf.readLongLE();
        }
        ByteBuf keyBuf = buf.readSlice(keyLen);
        Object key = decoder.decode(keyBuf, state);
        return key;
    }`
the line **PlatformDependent.isWindows()** should not be made regarding to the jvm running environnement but regarding to the redis server.

**Comment by mrniko** [comment]
Fixed
