### ISSUE TITLE
tomcat session使用kryo序列化方式bug

### ISSUE THREAD

**Issue by jqncc** [redisson/redisson#1206]
jre8  tomcat7  包:redisson-all-3.5.5.jar redisson-tomcat-7-3.5.5.jar
问题:进入系统,重启tomcat, 再刷新页面,报异常反序列化失败
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.jasig.cas.client.validation.AssertionImpl
登录集成CAS,拦截器有代码:
Assertion casAssertion = (Assertion) session.getAttribute(AbstractCasFilter.CONST_CAS_ASSERTION);
实现类必须是有参的,所以不可修改.

**Comment by jackygurui** [comment]
这是Kryo的使用问题。在缺少无参构造器的情况下，很多编码器都需要你自己根据需要提供一个序列化和反序列化的方式。或者改用支持JDK序列化方式的编码器
