### ISSUE TITLE
Is there anyway RMapCache can work with other clients?

### ISSUE THREAD

**Issue by fabregaszy** [redisson/redisson#1217]
Our service (Python) shares a redis with some other Java services. We and some Java service put in the data, and another Java service consumes the stored data.

Java services have decided to use redisson RMapCache to store and read the data. And since they both use redisson so there is no issue for them.

But I found if RMapCache can not get the data I hset in redis via redis python client.
It complains that:

> ERR Error running script (call to f_286dd696309f4ab2005d9df55e2410a1170fe3b3): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x4fd1d97c, L:/10.42.202.87:52106 - R:/192.168.2.131:6379] command: CommandData [promise=ImmediateEventExecutor$ImmediatePromise@70038355(incomplete), command=(EVAL), params=[local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[2]); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], ARGV[2], value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), ARGV[2]); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then return nil; end; return val; , 3, b25e7550-0498-43ef-b8f7-c15261791b00, redisson__timeout__set__{b25e7550-0498-43ef-b8f7-c15261791b00}, redisson__idle__set__{b25e7550-0498-43ef-b8f7-c15261791b00}, 1514948157337, [B@42c3188], codec=org.redisson.client.codec.ByteArrayCodec@309fd1aa]

I suppose the data I put didn't follow the RMapCache eviction scheduler data format.
Is there any workaround for this? Or any suggestions on this situation?

**Comment by jackygurui** [comment]
RMapCache packs individual key expiry info into each entry itself before they are persisted in Redis, if you really have to mix the usage with other client, you have to implement such process manually yourself.

**Comment by fabregaszy** [comment]
Thanks.
