### ISSUE TITLE
rangeTailAync and rangeHeadAsync

### ISSUE THREAD

**Issue by ajayrayapati** [redisson/redisson#1218]
I am looking to get a specidic count of data from endString to startstring.
So I have used readTailAsync by providing startString but I am getting data always from startString.
I tried using readHeadSync by providing endString but i still get same data from startString. Is this a bug?
I would like to know how to solve my problem.

RedissonClient redisson = redisUtil.getLocalRedis();;
RLexSortedSet idx2 = redisson.getLexSortedSet("ABCD17434");
idx2.clear();        
Long l = new Long("1506354756000");
for(int i = 0; i< 20000; i++)
{
 l = l+1;
 String s = "DENY"+"\t"+"helloworld_hongqin"+"\t" + Long.valueOf(l);
 idx2.add(s);
}
System.err.println(idx2.count("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354756000",true,"DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354776000",true));
Object a = idx2.rangeHeadAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354756000",true,0,20);
Object b = idx2.rangeTailAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354776000",true,0,20);

**Comment by ajayrayapati** [comment]
Object a = idx2.rangeHeadAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354776000",true,0,20);
Object b = idx2.rangeTailAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354756000",true,0,20);

Resulting same values

**Comment by mrniko** [comment]
It works correctly since you're using 1506354776000 with rangeHeadAsync and not 1506354756000

**Comment by ajayrayapati** [comment]
@mrniko 
Here is my understanding -
readHeadAsync - Should provide me results from "toElement" towards Head(Start) backwards
readTailAsync - should provide results from "fromElement" towards Tail(End) Forward

but my below code provide same results for both. Please let me know if my understanding is incorrect and provide the documentation for these methods.

 RLexSortedSet idx2 = redisson.getLexSortedSet("PAYMENT_INSTRUMENT_riskDecision_userGuid_publishTime_index17436");
        idx2.clear();
        
        Long l = new Long("1506354756000");
        
        for(int i = 0; i< 20000; i++)
        {
            l = l+1;
            String s = "DENY"+"\t"+"helloworld_hongqin"+"\t" + Long.valueOf(l) + "\t"+"helloworld_hongqin";
            idx2.add(s);
            
            
        }
        
        System.err.println(idx2.count("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354756000",true,"DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354776000",true));
        
        
        Object a = idx2.rangeHeadAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354776000",true,0,20);
        Object b = idx2.rangeTailAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354756000",true,0,20);

**Comment by mrniko** [comment]
idx2.rangeHeadAsync("DENY"+"\t"+"helloworld_hongqin"+"\t"+"1506354776000",true,0,20);

returns same result as for Tail since `1506354776000` number more than `1506354756000` and range includes all numbers up to 1506354776000

**Comment by ajayrayapati** [comment]
Please provide the API doc support for these methods
