### ISSUE TITLE
Using RMapCache what combination of ttl & idleTimeout can I use to expire field that is read < those values

### ISSUE THREAD

**Issue by mcacker** [redisson/redisson#1220]
I have a scenario where I have a field that I want to keep as long it the field value is updated at a rate < the idleTime, and expire when the that is not the case.  

What appears to be happening is that as the field is read more frequently than the idleTime, and when a get is performed it updates the idleTime expiration, so that the field is never expired.

I tried the following combinations:
   idleTime=N & ttl=0
   idleTime=N & ttl=N
   idleTime=N & ttl=max long

but none of those combinations work.  Is it even possible?

thanks, Mitchell

**Comment by mrniko** [comment]
I'm sorry, do you mean that combinations below don't allow to keep item in your case?

**Comment by mcacker** [comment]
Actually, what I meant was that the fields were never expiring.  Upon further testing, I found that for idleTime to work, I had to set ttl to the same value.  Can you confirm that is the recommended practice.  It does appear to be working though

**Comment by mrniko** [comment]
Let me check that

**Comment by mrniko** [comment]
Could you provide some test code to reproduce that?

Here is the current test https://github.com/redisson/redisson/blob/ea933127c5c6a10176e9329d12a2780e3fec1b49/redisson/src/test/java/org/redisson/RedissonMapCacheTest.java#L1167
