### ISSUE TITLE
Session object was not updated correctly

### ISSUE THREAD

**Issue by lying1234** [redisson/redisson#1222]
I used redisson session manager to externalize session data into redis server. However, session data will not be updated if the session is an object and the data to be changed without running httpsession.setattribute(..).
For example:
...
User user=(User)session.getAttribute("user"); //user.getName() is test1 after this line
user.setName("test2");
//After this line, ((User)session.getAttribute("user")).getName() still shows test1, not test2 as what is performed under tomcat session manager.
...

I tried Jedis session manager, it works as same as what I expected as tomcat session. Is this a bug in redisson?

**Comment by hans123456** [comment]
I'm not the dev. but it seems that the Jedis Session Manager saves or removes the session after every request.

The RedissonSessionManager doesn't have that feature.

----

As seen here, after every request the finally part is executed.
> https://github.com/jcoleman/tomcat-redis-session-manager/blob/master/src/main/java/com/orangefunction/tomcat/redissessions/RedisSessionHandlerValve.java#L27

It calls the afterRequest method which saves or removes the session.
> https://github.com/jcoleman/tomcat-redis-session-manager/blob/master/src/main/java/com/orangefunction/tomcat/redissessions/RedisSessionManager.java#L664

**Comment by mrniko** [comment]
Hi! Good point! I'll implement that

**Comment by mrniko** [comment]
There is a `readMode` setting for this case. Default value is MEMORY, but you need to switch it to REDIS.

https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#145-tomcat-redis-session-manager

**Comment by lying1234** [comment]
@hans123456 Thanks to find out how  Jedis Session Manager make it work.

@mrniko - I used REDIS readMode in my current setting. Have you implemented to fix the issue as @hans123456 mentioned? Is that the reason this ticket was closed?

**Comment by mrniko** [comment]
@lying1234 I'm sorry, the reason I closed it since RedissonSessionManager already has REDIS readMode.

**Comment by lying1234** [comment]
I'm confused. REDIS readMode doesn't solve the issue I reported.

**Comment by mrniko** [comment]
I have added `UpdateMode.AFTER_REQUEST` for your case. More details here - https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#145-tomcat-redis-session-manager

**Comment by lying1234** [comment]
Thank you for the quick response and your effort. When will you expect the next release be? I'd like to try it out.
