### ISSUE TITLE
Question about RFuture

### ISSUE THREAD

**Issue by JongLim** [redisson/redisson#1223]
Hello, 

I saw that **CompletionStage** interface implementation has been deleted based on the code.
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RFuture.java

Are there a particular reason for the removal? 

Thank you

**Comment by mrniko** [comment]
@JongLim 

Hi,

CompletionStage interface supported only for 3.x version. please have a look at `3.0.0` branch
