### ISSUE TITLE
RLiveObjectService : isExists method : unclear javadoc

### ISSUE THREAD

**Issue by welovelain** [redisson/redisson#1224]
RLiveObjectService has method isExists (which name is grammatically strange already, but "isSomething" is already established expression for boolean variables, so okay)

Javadoc says: Returns true if the RLiveObject does not yet exist in redis
But the same javadoc later says: @return <code>true</code> object exists.

I find this kind of documentation unclear, as I don't understand if it should return if object exists (like method name and @return says) or not (like description says)
  

UPDATE:
I tried to see for myself and got confused even more.
Here's my code:

Lease class:
```
@Data
@NoArgsConstructor
@REntity
public class Lease {
    @RId
    private long id;
    private Rate rate = null;

    private Long serverTime = 0l;
    private Long sum = 0l;
    private Long seq = 0l;

    public Lease(long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return new Gson().toJson(this);
    }
}
```
Testing code:
```
...
RLiveObjectService service = redisson.getLiveObjectService();

Lease lease = new Lease(123);
System.out.println("Exists: " + service.isExists(lease)); // returns "Exists: false"
service.persist(lease); // all good, saves in Redis
System.out.println("Exists: " + service.isExists(lease)); // returns "Exists: false"
service.persist(lease); // java.lang.IllegalArgumentException: This REntity already exists
```

So what exactly "isExists" feature does ?

**Comment by jackygurui** [comment]
@welovelain Thanks for pointing out the java doc error. A new PR has been created to address the issue.

As for the usage, the `service.isExists(obj)` will always return false when the object in question is not an attached instance. The instance becomes attached when you perform `attach` or `persist` so you should check the instance like follows:

```
RLiveObjectService service = redisson.getLiveObjectService();

Lease lease = new Lease(123);
System.out.println("Exists: " + service.isExists(lease)); // Should return "Exists: false"
Lease attachedLease = service.persist(lease); // all good, saves in Redis
System.out.println("Exists: " + service.isExists(lease)); // Should return "Exists: false" because the lease is still a pointer to the unattached instance;
System.out.println("Exists: " + service.isExists(attachedLease)); // Should return "Exists: true" 
```
