### ISSUE TITLE
Can I use RBatch for RPriorityQueue?

### ISSUE THREAD

**Issue by welovelain** [redisson/redisson#1229]
I want to perform RPriorityQueue.remove() and update RBucket as atomic operation. Is it possible? There is no RBatch.getPriorityQueue() method
  
Tried it with getQueue() method like this:
```
RPriorityQueue<TrackMessage> test = redisson.getPriorityQueue("testy");

// ... Fill the queue here

TrackMessage tm = test.peek();

 RBatch rBatch = redisson.createBatch();
 rBatch.getQueue("testy").removeAsync(tm);
 rBatch.execute();
    
assert(!tm.equals(test.peek())); // fails
```
Doesn't work. (and probably shouldn't)

**Comment by jackygurui** [comment]
I think there is a misconception between pipelining and atomic operations. They don't mean the same thing. Putting a bunch of operations in a pipeline doesn't mean they are going to be executed on the server side in an atomic fashion. The only guarantee you will get is those commands will be send together in a defined order.

What you could do is to make your service acquire a distributed lock before executing those subsequent commands or you can write your own Lua script to execute them on server side.

Btw, it is recommended you should never mix different data types with the same key as unexpected behaviours could happen and result in data loss.

**Comment by welovelain** [comment]
Got it, thanks
