### ISSUE TITLE
RScheduledExecutor doesn't restart tasks after crash

### ISSUE THREAD

**Issue by welovelain** [redisson/redisson#1231]
I'm testing fault-tolerance of redisson node. I have 5 Runnable scheduled tasks. When instance crashes, sometimes redisson node resumes these tasks again. Sometimes - not. 

I found that if it resumes tasks, Redis has next keys:
{@executorName.org.redisson.RemoteExecutorService}:counter  == 5
{@executorName.org.redisson.RemoteExecutorService}:tasks == HASH (taskKey:Value)
{@executorName.org.redisson.RemoteExecutorService}:scheduler == ZSET (taskKey: score)

But when it doesn't, {@executorName.org.redisson.RemoteExecutorService}:scheduler  is absent.

Could you provide more information, how reliable task resuming in case of crash can be? If redisson node is shutdown correctly, can I rely that tasks would be resumed? Is it the same case in case of single Redisson node? (with one/multiple ExecutorServices in NodeConfig) 
Is there some strategy to resume these tasks? Or at lease find out they are broken, remove stale data and re-create tasks?

Thanks!

**Comment by mrniko** [comment]
I have added test for your case and didn't encounter any problem. All tasks are stored until the execution moment. So RedissonNode couldn't damage state stored in Redis.
