### ISSUE TITLE
RLock reentrant behaviour over unlock

### ISSUE THREAD

**Issue by erdemasl** [redisson/redisson#1233]
This might be a trivial case/question but according to java specs, a reentrant lock can be acquired  by the owner thread infinite number of times and simple can be unlocked completely with just one unlock call.

What I'm seeing is the opposite of it currently, in RLock implementation. It behaves like a semaphore rather than a reentrant lock. Every unlock call decreases reentrant counter on Redis and in order to unlock it completely, I have to call unlock until the counter hits to zero. Is this the expected behaviour?

**Comment by mrniko** [comment]
Hi!

> according to java specs, a reentrant lock can be acquired by the owner thread infinite number of times and simple can be unlocked completely with just one unlock call.

Could you please point out on it?

Since redisson is fully implements ReentrantLock functionality and `RLock.unlock` method works exactly like descried in comment for `ReentrantLock.unlock()` method
