### ISSUE TITLE
RMapCache'Eviction seems not to be in effect

### ISSUE THREAD

**Issue by Comven** [redisson/redisson#1234]
I used RMapCache in my project,and set the timeout time is 3 minutes，but I found that the size of the ZSET is increasing. and the key  still inside, and not be cleared a day after that。

Here's the way I store key "a" with value "1"，and 3 minutes to live：

RMapCache<String, Integer> mapCache = redissonClient.getMapCache("myMapCache");
mapCache.fastPut(“a”, 1, 3, TimeUnit.MINUTES);

Did i make any mistake？
How can I make the Eviction come into effect？

**Comment by mrniko** [comment]
How many keys did you put into map? Since eviction process managed by Redisson it should be launched during all time.

**Comment by Comven** [comment]
I put 130 key into the map currently. Is it too little?

**Comment by Comven** [comment]
Because the size is not reduced,I'm worried about memory of redis after a period of time.

**Comment by Comven** [comment]
@mrniko It work fine now, I has puted more key into the map, then  it delete the earlier data.thank you！

**Comment by mrniko** [comment]
You're welcome!

**Comment by iamjayant** [comment]
hi @mrniko, RMapCache is not working correctly for me. I have put the timeout of 10 secs but the key-expiry event is coming exactly after 20 secs. Please see the code and correct me if I am wrong.

RMapCache<String, String> mapCache = redisson.getMapCache("myMap");
mapCache.addListener(new EntryExpiredListener<String, String>() {
    @Override
    public void onExpired(EntryEvent<String, String> event) {
	System.out.println(Calendar.getInstance().getTime()+" ==> "+event.getKey() + " " + 
              event.getValue());
     }
});
		
System.out.println(Calendar.getInstance().getTime()+" ==> hi");
mapCache.fastPut("hi", "scott", 10, TimeUnit.SECONDS);

**Comment by mrniko** [comment]
@iamjayant on expired event is not executed in real-time.

**Comment by iamjayant** [comment]
@mrniko can u please suggest me one real-time example where I can test onExpired working properly. I need to write callbacks on onExpired event of keys for mine application.

**Comment by mrniko** [comment]
@iamjayant I can suggest you to use ScheduledExecutorService for precise task/event execution
