### ISSUE TITLE
RSCRIPT LUA timeout and not consistent results

### ISSUE THREAD

**Issue by ajayrayapati** [redisson/redisson#1251]
# RScript LUA timeout/Null Pointer exception

**Description**
When trying to execute EVAL LUA script using Redisson library,  We receive either null Pointer exception or timeout exception and results are not consistent.  If we execute one or two statements then it works fine but when we add a couple then it isn't giving consistent results. When ran eval Lua script directly  in REDIS client it **doesn't timeout** and gives consistent results. Please let us know what the issue is when using redisson library and how to fix it.

## **REDISSON ERROR** same error even when I increased the timeout value
Caused by: java.lang.NullPointerException: null
	at org.redisson.client.handler.CommandDecoder.messageDecoder(CommandDecoder.java:332) ~[redisson-3.5.6.jar:na]

java.util.concurrent.ExecutionException: org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with paramsv

## EVAL --> Below LUA script results correct values when executed in REDIS CLIENT directly
eval "local d = {}; d[1] = redis.call('zrevrangebylex','ABCD17436','[DENY\tTESTREDISSON\t1506524856099','[DENY\tTESTREDISSON\t1506524856000','LIMIT',0,5);  d[2] = redis.call('zrevrangebylex','ABCD17436','[DENY\tTESTREDISSON\t1506524856099','[DENY\tTESTREDISSON\t1506524856000','LIMIT',0,15);  d[3] = redis.call('zrevrangebylex','ABCD17436','[DENY\tTESTREDISSON\t1506524856099','[DENY\tTESTREDISSON\t1506524856000','LIMIT',0,25);  return d;" 0

## 
**REDISSON code that is timing out or giving timeout exception**

                       RedisUtil redisUtil = new RedisUtil();
            RedissonClient redisson = redisUtil.getLocalRedis();;
            
            
           RLexSortedSet idx2 = redisson.getLexSortedSet("ABCD17436");
            idx2.clear();

            
            Long l = new Long("1506524856000");
            for (int i = 0; i < 100; i++) {
                String s = "DENY" + "\t" + "TESTREDISSON" + "\t"
                        + Long.valueOf(l) + "\t" + "helloworld_hongqin";
                idx2.add(s);
                l = l + 1;
            }

            StringCodec codec = new StringCodec();
            String max = "'[DENY" + "\t" + "TESTREDISSON" + "\t" + "1506524856099'";
            String min = "'[DENY" + "\t" + "TESTREDISSON" + "\t" + "1506524856000'";
             String luaScript1= "local d = {}; d[1] = redis.call('zrevrangebylex','ABCD17436'," +max+","+min+",'LIMIT',0,5); ";
             luaScript1=  luaScript1 + " d[2] = redis.call('zrevrangebylex','ABCD17436'," +max+","+min+",'LIMIT',0,15); ";
             luaScript1=  luaScript1 + " d[3] = redis.call('zrevrangebylex','ABCD17436'," +max+","+min+",'LIMIT',0,25); ";
             luaScript1 = luaScript1 + " return d;";
         
            System.err.println(luaScript1);            
      
            Future<Object> r1 = redisson.getScript().evalAsync(Mode.READ_ONLY, codec,
                    luaScript1,
                    RScript.ReturnType.MULTI, Collections.emptyList());            
            Object obj1 = r1.get(5000,TimeUnit.MILLISECONDS);

**Comment by mrniko** [comment]
It's a bug, thanks for report

**Comment by ajayrayapati** [comment]
Currently ZREVRANGEBYLEX isnt supported in redisson - when can we expect that ?

**Comment by mrniko** [comment]
Fixed

**Comment by ajayrayapati** [comment]
@mrniko  Thank you for fixing it 
1) Can you please let us know when the release for this bug would be and what stable version?
2) Also please provide the downloadable link to the snapshot version for me to test this so we can feel comfortable on waiting for the release to happen

**Comment by mrniko** [comment]
@ajayrayapati 

I plan to release it by the end of this month.
Here is the latest snapshot [redisson-3.5.8-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/1659052/redisson-3.5.8-SNAPSHOT.jar.zip)

**Comment by ajayrayapati** [comment]
Thank you do you have any plan to support ZREVRANGEBYLEX  in Redisson currently this is not supported

**Comment by mrniko** [comment]
@ajayrayapati could you please create a separate issue for it?
