### ISSUE TITLE
FST 序列化CPU占用高的问题

### ISSUE THREAD

**Issue by jonwinters** [redisson/redisson#1254]
<img width="971" alt="redison" src="https://user-images.githubusercontent.com/21285645/35225956-be4cafc4-ffc4-11e7-8476-fef54449a6a5.png">

有没有类似的情况？

**Comment by jackygurui** [comment]
好像大部分时间是花在序列化上了，你这个数据有多大？

**Comment by jonwinters** [comment]
@jackygurui  3200个，，对象不大，，全花在序列化上面了 ，我也觉得不对劲 ，有办法解决吗？

**Comment by jonwinters** [comment]
@jackygurui  序列化完 也就3200个 总共320kb不到 两次请求  序列化的开销达到了8秒左右

**Comment by jackygurui** [comment]
看来FST用的时间比较多，FST花了6秒半的时间序列化key去了。你的key也很大？

**Comment by jonwinters** [comment]
@jackygurui  从redis中的数据来看，，key好像就是对象 本身序列化的结果，我这边用的是JPA的二级缓存。 fst 是不是 某些版本存在性能问题，，3200个 讲道理再怎么慢 序列化的时间不至于这么长吧

**Comment by jonwinters** [comment]
@jackygurui  尴尬，，序列化后 key比value还大

**Comment by jonwinters** [comment]
@jackygurui  可以否替换一个序列化实现类 
![image](https://user-images.githubusercontent.com/21285645/35313442-5764f2b6-00fb-11e8-811e-b61ca3ba14ec.png)
![image](https://user-images.githubusercontent.com/21285645/35313502-a9ef2ad8-00fb-11e8-8f94-ded0e9322791.png)
我换成jackson等序列化方式，，缓存写入的时候没问题， 读取的时候 使劲报错

**Comment by jackygurui** [comment]
Jackson的问题应该是你用到的类不是默认Jackson配置支持的，你可以自行配置以后使用啊

**Comment by jonwinters** [comment]
@jackygurui  问题已经解决 更换fst的版本，macos cpu飙升的问题 得到解决

**Comment by grmrb** [comment]
请问楼主fst 版本从多少升到了多少
