### ISSUE TITLE
[Question] Use Rmap as a data member on a singleton or create a new instance for every call

### ISSUE THREAD

**Issue by iddol** [redisson/redisson#1255]
If our server handles lots of Rest calls that access distributed collections, is it safe to keep a single instance of Rmap as a data member on a Singleton bean (and have multiple threads use it concurrently) or is it better to create a new instance of Rmap for every call?
We're not using a local cache, so there's no data supposed to be kept in the Rmap instance, but does it have any concurrency limits we should be aware of?
Is there a significant overhead associated with creating a new instance of Rmap for every call?

**Comment by jackygurui** [comment]
RMap is only a handler instance, it is thread safe by nature.  Just like any other Java objects, there would be a performance impact if you create and destroy lots of it constantly. So you can share one instance if you can if not so be it.
