### ISSUE TITLE
出现了Publish/Subscribe connection pool exhausted!异常

### ISSUE THREAD

**Issue by walleiptXX** [redisson/redisson#1256]
使用redisson版本:2.2.11
使用redisson进行redis操作，在线上跑了几天左右会出现
Publish/Subscribe connection pool exhausted! All connections are busy. Try to increase Publish/Subscribe connection pool size.的情况，
检查了源码片段：
![default](https://user-images.githubusercontent.com/24837540/35268789-2030d44a-0065-11e8-94a0-619a1694baa9.png)
看源码上是只有在entry.isFreezed()连接被冻结的情况下才会出现如上情况(不出现Hosts with fully busy connections)，请问改如何解决！

**Comment by jackygurui** [comment]
请用最新版的试一试，看还有没有问题

**Comment by walleiptXX** [comment]
早安，有办法模拟出来么？需要过测试重现一下




姓名：walleipt
邮箱:：walleipt@163.com
在2018年01月26日 06:06，Rui Gu 写道：

请用最新版的试一试，看还有没有问题

**Comment by jackygurui** [comment]
同问。你能否提供一个重现？
