### ISSUE TITLE
Reddison Spring Cache modifies exception semantics of annotated method

### ISSUE THREAD

**Issue by sLite** [redisson/redisson#1257]
Regarding spring javadoc the spring `Cache` interface demands implementations to throw a `Cache.ValueRetrievalException`. 

> "Wrapper exception to be thrown from `get(Object, Callable)` in case of the value loader callback failing with an exception."

The reddision cache implementations breaks this contract and throws a `ValueRetrievalException` that is wrapped within an `IllegalStateException`. This exception is not handled by Springs `CacheAspectSupport` and thus thrown back directly to the caller of the annotated method. 

Looking at `CacheAspectSupport`, it would also expect a `CacheOperationInvoker.ThrowableWrapper` as cause of the `ValueRetrievalException` which is removed within the reddison cache implementation when constructing the `ValueRetrievalException`.

This behaviour breaks the transparency of the cache abstraction and beaks code that relies on exceptions for control flow (eg. `javax.ws.rs.NotFoundException`). Can you please take a look and this and tell me if that is intended behaviour?

Best Regards
Daniel Selinger

**Comment by mrniko** [comment]
Fixed! Thanks for report!

**Comment by mrniko** [comment]
Correct CacheOperationInvoker.ThrowableWrapper handling https://github.com/redisson/redisson/commit/d7825814fcf57a7006c24c88f4bf6ba374e63d06

**Comment by sLite** [comment]
Nice, thanks for the fast action on this one :) :+1: 

Do you know when this will also propagate to the 3.X versions i assume?
Is there a release schedule when the next 3.X version with this fix will be released?

**Comment by mrniko** [comment]
I plan to release at the end of this month.
