### ISSUE TITLE
Redis Replication Configuration

### ISSUE THREAD

**Issue by cdehankar** [redisson/redisson#1258]
Hi ,
I want to test redis replication scenario on my local machine.

I am using  docker and have below setting
` redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
  
  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - "6380:6380"
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_HOST=redis-master
      - slaveof=127.0.0.1:6379

and my Java config looks like below
`final Config config = new Config();
        config.useReplicatedServers()
                .setScanInterval(redisConfig.getScanInterval())
                .addNodeAddress(redisConfig.getEndpoints())
                .setMasterConnectionMinimumIdleSize(redisConfig.getMinIdle())
                .setMasterConnectionPoolSize(redisConfig.getMaxTotal())
                .setTimeout(redisConfig.getTimeout())
                .setConnectTimeout(redisConfig.getTimeout());
        return config;`

And passing address like "redis://127.0.0.1:6379,redis://127.0.0.1:6380"
From logs I can see master is ready but I am getting below exception

`INFO  [2018-01-23 15:34:57,062] org.redisson.connection.ReplicatedConnectionManager: redis://127.0.0.1:6379 is the master
ERROR [2018-01-23 15:35:01,573] com.rrr.dss.pr.redis.RedisConnectionBuilder: -- build() Exception while creating RedissonClient.
! org.redisson.client.RedisTimeoutException: Command execution timeout for /127.0.0.1:6380
! at org.redisson.client.RedisConnection.await(RedisConnection.java:151)
! at org.redisson.client.RedisConnection.sync(RedisConnection.java:183)
! at org.redisson.client.RedisConnection.sync(RedisConnection.java:169)
! at org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:85)
! at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:242)
! at org.redisson.Redisson.<init>(Redisson.java:115)
! at org.redisson.Redisson.create(Redisson.java:153)`

My all 3 servers are running ...  I tried increasing timeout as well. Can you please tell me what could be the issue or I miss anything..

**Comment by cdehankar** [comment]
Please reply!!

**Comment by jackygurui** [comment]
You should use master-slave connection mode. Replicated mode is mainly for cloud hosted redis instances.

**Comment by cdehankar** [comment]
Ohh.. Okey I will try.. Thanks!!
