### ISSUE TITLE
Spring session annotation support

### ISSUE THREAD

**Issue by voron** [redisson/redisson#1259]
Hello,

I'm following https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#146-spring-session guide, but I get NPE
`Caused by: java.lang.NullPointerException: null
	at org.redisson.spring.session.config.RedissonHttpSessionConfiguration.sessionRepository(RedissonHttpSessionConfiguration.java:54) ~[redisson-2.10.7.jar:na]`
I tried to use `@EnableRedissonHttpSession(maxInactiveIntervalInSeconds = 360)` but still the same NPE. Is this annotation usable or the only option I have to use is xml ? Tried  3.5.7 version.

**Comment by mrniko** [comment]
Hi,

Sorry, I'm unable to reproduce that. Which version of spring session do you use?

**Comment by voron** [comment]
1.3.1 RELEASE
NPE is at https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/spring/session/config/RedissonHttpSessionConfiguration.java#L54 , maxInactiveIntervalInSeconds is null. Who should call setMaxInactiveIntervalInSeconds before sessionRepository ?

**Comment by mrniko** [comment]
It's filled up automatically during initialization with default value if it hasn't been defined https://github.com/redisson/redisson/blob/49096634571d83d7b5b81cfa17984c7b6e21eaf6/redisson/src/main/java/org/redisson/spring/session/config/RedissonHttpSessionConfiguration.java#L71

**Comment by voron** [comment]
In my case `sessionRepository` was required earlier by `@Bean SpringSessionBackedSessionRegistry` . I moved both to class under `@EnableRedissonHttpSession` annotation and problem is resolved. Sorry to bother you.
