### ISSUE TITLE
Deserialization through JCache failing with ClassCastException

### ISSUE THREAD

**Issue by prosonf** [redisson/redisson#1260]
I am using Redisson as Redis client to store a key-value pair `<String, LocalDateTime>`. It's configured to be used through the JCache API (JSR-107).

It's storing values like `2018-01-23T11:59:34.997834` but in the `cache#get` invocation is trying to return a String giving a ClassCastException . It compiles perfectly, `cache#get` returning `LocalDateTime`, but if fails in execution.

Am I missing something here or is there some problem using it with the JCache API?

```java
    @Test
    public void getCacheInline() {
        // Configuration
        Config redissonCfg = new Config();
        redissonCfg
            .setCodec(new JsonJacksonCodec(buildObjectMapper()))
            .useSingleServer()
            .setAddress("redis://redis:6379");

        MutableConfiguration<String, LocalDateTime> jcacheConfig = new MutableConfiguration<String, LocalDateTime>()
            .setTypes(String.class, LocalDateTime.class)
            .setExpiryPolicyFactory((Factory<ExpiryPolicy>) () -> new CreatedExpiryPolicy(new Duration(SECONDS, 100)));

        Configuration<String, LocalDateTime> configuration = RedissonConfiguration.fromConfig(redissonCfg, jcacheConfig);

        // Cache creation
        Cache<String, LocalDateTime> cache = cacheManager.createCache(CACHE_NAME, configuration);

        // Put
        LocalDateTime expectedDateTime = LocalDateTime.now();
        cache.put("testKey", expectedDateTime);

        // Get
        // In this line: java.lang.ClassCastException: java.base/java.lang.String cannot be cast to java.base/java.time.LocalDateTime
        LocalDateTime actualDateTime = cache.get("testKey");
        assertThat(actualDateTime, is(equalTo(expectedDateTime)));
    }

    private ObjectMapper buildObjectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.configure(FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.configure(WRITE_DATES_AS_TIMESTAMPS, false);
        objectMapper.configure(READ_DATE_TIMESTAMPS_AS_NANOSECONDS, false);
        objectMapper.setSerializationInclusion(NON_NULL);
        return objectMapper;
    }

```

**Comment by mrniko** [comment]
You should ensure that JsonJacksonCodec supports LocalDateTime object and/or try another codec

**Comment by prosonf** [comment]
I'm registering JavaTimeModule in Jackson ObjectMapper, that has support for LocalDateTime and all new Java 8 datetime API. Does JsonJacksonCodec add something on that?

It's here [JavaTimeModule.java](https://github.com/FasterXML/jackson-modules-java8/blob/2.9/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/JavaTimeModule.java)
And my dependency:
```xml
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.9.4</version>
        </dependency>
```

**Comment by prosonf** [comment]
I've seen these lines in JsonJacksonCodec

```java

    private final Decoder<Object> decoder = new Decoder<Object>() {
        @Override
        public Object decode(ByteBuf buf, State state) throws IOException {
            return mapObjectMapper.readValue((InputStream)new ByteBufInputStream(buf), Object.class);
        }
    };
```
That `Object.class` is killing it!

Any way to work around it? The idea is to keep using Jackson.

**Comment by prosonf** [comment]
I can't see a way to know the target type at that point. Is there any?

If not at least the integration with JCache API seems broken. It let you specify types, but then aren't used and fails at execution time.

The workaround I can see now is a wrapper around Cache object, doing the serialization/deserialization manually.

**Comment by prosonf** [comment]
I'm seeing that wrapping in another object is working.
```java
    public static class Value {
        private LocalDateTime value;
        ...
    }
```
It serialised a json string with `@class` property, and then at deserialising time it has all the types there.

Anyway, it doesn't work with plain LocalDateTime objects, or any object from Java 8 Time API I would say.

@mrniko, Redisson team,  I leave to you progressing this issue any further. As I cannot wait much longer, I think this workaround will do it for me if not I'll go with something different.

Thanks

**Comment by mrniko** [comment]
I made few improvements to `JsonJacksonMapCodec`. So you can use it to solve this problem. 

Here is the example:
```java
URL configUrl = getClass().getResource("redisson-jcache.json");
Config cfg = Config.fromJSON(configUrl);

ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new JavaTimeModule());
cfg.setCodec(new JsonJacksonMapCodec(String.class, LocalDateTime.class, objectMapper));

Configuration<String, LocalDateTime> config = RedissonConfiguration.fromConfig(cfg);
Cache<String, LocalDateTime> cache = Caching.getCachingProvider().getCacheManager()
                .createCache("test", config);
```
or extend JsonJacksonMapCodec:
```java
    public static class ExtendedJsonJacksonMapCodec extends JsonJacksonMapCodec {
        
        public ExtendedJsonJacksonMapCodec() {
            super(String.class, LocalDateTime.class);
        }
        
        @Override
        protected void init(ObjectMapper objectMapper) {
            objectMapper.registerModule(new JavaTimeModule());
            super.init(objectMapper);
        }
        
    }

URI configUri = getClass().getResource("redisson-jcache.json").toURI();
Cache<String, LocalDateTime> cache = Caching.getCachingProvider()
                         .getCacheManager(configUri, null).createCache("test", config);

```

**Comment by prosonf** [comment]
Tried extending JsonJacksonMapCodec that way and it worked! Thank you very much.

Although it was using Redisson v3.6.1, so not using changes from this issue, I guess.

**Comment by rajendrag** [comment]
I am seeing this issue with RMapCache now. But, in my case, there could be many other object types that could be the values of this map (I have one RMapCache for whole application, this was recommended in one of the redisson documentation). I can not use the JsonJacksonMapCodec.

If I wrap the LocalDate in another object like an ArrayList, it is being serialized with @class and deserializing properly. But, just LocalDate is throwing exception and there is @class or any information about LocalDate for it to use while deserializing it. 

Am I missing something? Any help would be greatly appreciated.
