### ISSUE TITLE
ZREVRANGEBYLEX not supported by redisson

### ISSUE THREAD

**Issue by ajayrayapati** [redisson/redisson#1264]
@mrniko Currently ZREVRANGEBYLEX is not supported by redisson which can pull details in reverse order of the stored values on a key LEX sorted set data structure. Please support this function as soon as possible as we would like to use it. Without that the retrieval of data in reverse order is very cumbersome and not an easy way out. Even LUA script based on discussion with REDIS labs, they say it fecthes data only from one shard and cannot go and look for data in other shards... We want to use this function zrevrangebylex in redis batch execute to retrieve data from multiple sorted set keys at once

**Comment by ajayrayapati** [comment]
@mrniko May I know the timeline for 2.11.1?

**Comment by mrniko** [comment]
Done

**Comment by ajayrayapati** [comment]
@mrniko can you please tell what Redison version would this be available and provide us a downloadable SNAPSHOT link

**Comment by mrniko** [comment]
@ajayrayapati this feature will be available with 2.11.1/3.6.1 versions.

**Comment by ajayrayapati** [comment]
@mrniko can we get a SNAPSHOT version downloadable link for the same

**Comment by ajayrayapati** [comment]
@mrniko  also could you please provide a estimated date of release for this feature

**Comment by mrniko** [comment]
Sure here is it [redisson-2.11.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/1696302/redisson-2.11.1-SNAPSHOT.jar.zip)

Sorry, I don't have estimated date yet.

**Comment by ajayrayapati** [comment]
@mrniko please provide us a timeframe if possible. like this month/next month etc

**Comment by mrniko** [comment]
@ajayrayapati definitely this month

**Comment by ajayrayapati** [comment]
@mrniko Thank you for the snapshot ersion.. it works.. But we are currently using 3.6.0 stable supported release. Hope these changes will be applied to the next release 3.6.1? and any update on the release date?

**Comment by mrniko** [comment]
Sure, this issue is a part of upcoming 3.6.1 release. I plan to release it by friday
