### ISSUE TITLE
Cannot call config.enableMetrics() to initialize Metrics

### ISSUE THREAD

**Issue by nsphung** [redisson/redisson#1266]
Hello,

I'm using Redisson 3.6.0 and want to use the following:
https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#147-jmx-and-dropwizard-metrics

```java
Config config = ... // redisson config object
config.enableMetrics()
      .setRegistryName("myMetrics")
      // enable JMX
      .setJmxEnabled()
      // JMX domain name
      .setJmxDomain();
```

However, the `org.redisson.config.Config` class does not implement `enableMetrics()`. I can't find the implementation in Github source code.

How can one initialize the Metrics as described in the documentation ?

Thanks.

**Comment by mrniko** [comment]
Hi!

This feature is a part of [Redisson PRO](https://redisson.pro/) as mentioned at the end of the page.
