### ISSUE TITLE
RDelayedQueue cannot be delayed

### ISSUE THREAD

**Issue by smxc** [redisson/redisson#1270]
RBlockingQueue<String> blockingFairQueue = redisson.getBlockingQueue("delay_queue");
        RDelayedQueue<String> delayedQueue = redisson.getDelayedQueue(blockingFairQueue);
        
        delayedQueue.offer("1_1_1", 3, TimeUnit.SECONDS);
        delayedQueue.offer("1_1_2", 7, TimeUnit.SECONDS);

        assertThat(delayedQueue.contains("1_1_1")).isTrue();   // true   ???

        Thread.sleep(9000);
        
         assertThat(delayedQueue.contains("1_1_1")).isTrue();

---------------------------------------------------------

pom.xml

			<dependency>
				<groupId>org.redisson</groupId>
				<artifactId>redisson</artifactId>
				<version>2.9.4</version>
			</dependency>

**Comment by mrniko** [comment]
This is an expected behavior. `delayedQueue` contains `1_1_1` for 3 seconds and then transfers it into `blockingFairQueue` as stated in description on wiki page.

**Comment by smxc** [comment]
thank you very much .   

		RedissonClient redissonClient = redisService.getRedissonClient();
		RBlockingQueue blockingFairQueue = redissonClient.getBlockingQueue("delay_queue");
		RDelayedQueue delayedQueue = redissonClient.getDelayedQueue(blockingFairQueue);

	    delayedQueue.offer("1_1_1", 3, TimeUnit.SECONDS);

	    System.out.println(**blockingFairQueue**.contains("1_1_1"));  // true
	    
	    Thread.sleep(9000);
	    
	    System.out.println(**delayedQueue**.contains("1_1_1"));
