### ISSUE TITLE
RedissonSpringLocalCachedCacheManager not found

### ISSUE THREAD

**Issue by xmanOxman** [redisson/redisson#1277]
I want to use RedissonSpringLocalCachedCacheManager  for spring cache.But I can not find RedissonSpringLocalCachedCacheManager and LocalCachedCacheConfig in redisson 3.6.0 version. Is something wrong？

**Comment by mrniko** [comment]
@xmanOxman 
These features are part of [Redisson PRO](https://redisson.pro) version
