### ISSUE TITLE
Redisson issuing undue commands with spring cache

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#1282]
We are using redisson 3.5.2 with spring cache.

When I put the debug on the method,
` @Override
    public ValueWrapper get(Object key) {
        Object value = map.get(key);
        if (value == null) {
            addCacheMiss();
        }else{
            addCacheHit();
        }
        return toValueWrapper(value);
    }
`

I get the following requests when using Monitor on the redis server.

1517915720.885427 [0 127.0.0.1:58162] "HLEN" "client_test"
1517915720.891805 [0 127.0.0.1:58163] "HLEN" "client_test"
1517915720.910285 [0 127.0.0.1:58164] "HLEN" "client_test"
1517915720.914924 [0 127.0.0.1:58165] "HLEN" "client_test"
1517915720.919594 [0 127.0.0.1:58167] "HLEN" "client_test"
1517915720.927470 [0 127.0.0.1:58166] "HLEN" "client_test"
**1517915722.923863 [0 127.0.0.1:58179] "EVAL" "local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[2]); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], ARGV[2], value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), ARGV[2]); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then return nil; end; local maxSize = tonumber(redis.call('hget', KEYS[5], 'max-size')); if maxSize ~= nil and maxSize ~= 0 then    redis.call('zadd', KEYS[4], tonumber(ARGV[1]), ARGV[2]); end; return val; " "5" "client_test" "redisson__timeout__set:{client_test}" "redisson__idle__set:{client_test}" "redisson__map_cache__last_access__set:{client_test}" "{client_test}:redisson_options" "1517915722922" "\"ims_CLIENT_WITH_FR\""**
1517915722.924041 [0 lua] "hget" "client_test" "\"ims_CLIENT_WITH_FR\""
1517915722.924057 [0 lua] "zscore" "redisson__timeout__set:{client_test}" "\"ims_CLIENT_WITH_FR\""
1517915722.924074 [0 lua] "zscore" "redisson__idle__set:{client_test}" "\"ims_CLIENT_WITH_FR\""
**1517915722.924090 [0 lua] "hset" "client_test" "\"ims_CLIENT_WITH_FR\"" "\x00\x00\x00\x00p\x99\x94AR\x01\x00\x00\x00\x00\x00\x00{\"@class\":\"com.db.qo.ClientQO\",\"createdTime\":[\"java.sql.Timestamp\",1511531395000],\"createdUserId\":\"amit\",\"description\":\"Uber JLT\",\"executorType\":\"IMS\",\"id\":4,\"imsClientId\":\"client_with_fr\",\"modifiedTime\":[\"java.sql.Timestamp\",1511531397000],\"name\":\"Uber JLT\",\"pollInterval\":350,\"productCode\":\"PS\",\"productVersion\":\"V2\"}"
1517915722.924167 [0 lua] "zadd" "redisson__idle__set:{client_test}" "1518002122922" "\"ims_CLIENT_WITH_FR\""**
1517915722.924185 [0 lua] "hget" "{client_test}:redisson_options" "max-size"

I am unable to understand why the eval and hset command is sent from redisson when I am getting a key. 
This is creating an issue for us to scale our services since these eval and hset calls will only go to master. Even if, we increase our redis slaves we wont be able to scale our reads since each read results into two writes to redis master.
Other issues are: 
The eval command is taking a lock on redis master.
The hset command is setting the same response in redis master which is being replicated by all the redis slaves. This is resulting in wastage of redis server resources since they are wasting them to replicate the exact same data.

**Comment by mrniko** [comment]
Spring Cache is based on MapCache object. It changes ttl record for requested map entry during get operation execution, this is why lua script used in get is always sent to master. In Redis it's impossible to modify data on slave, only on master. So I would recommend you to use Redis cluster and Clustered version of Spring Cache manager. In Redis Cluster multi-master setup will help you to scale read operations on Spring Cache.

> The eval command is taking a lock on redis master.
I'm afraid you're mistaken, eval is a lock free operation.

**Comment by Himanshu4** [comment]
Okay, But why hset command is used? I think, at least hset can be avoided. There is no need to do hset when doing a get api all.

**Comment by mrniko** [comment]
@Himanshu4 It's a bug. Thanks for pointing out!

**Comment by Himanshu4** [comment]
I think the multiple unwanted HLEN commands and zscore commands also seems to be a bug. Can you please check why these commands are getting sent from redisson and if they can be removed. 
I don't see any rationale behind sending so many HLEN and ZSCORE commands from the redisson.


Also, Are these bugs present in redisson-pro also?

**Comment by mrniko** [comment]
Can't realize the reason of hlen calling, since these commands are not used in lua script and were invoked separately by client. I also don't see any `RMap.size` in `org.redisson.spring.cache.RedissonCache` object. Please check your application for `RMap.size` method invocation.

zscore is used in lua script to get expireDateScore and expireIdle values and can't be avoided.

**Comment by mrniko** [comment]
As for bug with hset I'll fix it and release 3.6.0-5 version

**Comment by Himanshu4** [comment]
I have checked and can confirm that RMAp.size has not been invoked from anywhere in the application code. I am sure that redisson is somewhere calling `RMap.size` internally which is why I am seeing these commands in redis logs.

**Comment by mrniko** [comment]
Please have a look at `org.redisson.spring.cache.RedissonCacheStatisticsProvider` size is called there. You need to remove that been from your application context.

**Comment by Himanshu4** [comment]
I have removed that bean from my application context by using 
`@EnableAutoConfiguration(exclude = {RedissonCacheStatisticsAutoConfiguration.class})`
in my code. But, still the multiple HLEN commands are being issued by redisson. Please check why those commands are being sent

**Comment by mrniko** [comment]
I tried with `org.redisson.spring.cache.RedissonSpringCacheTest` and follow test method:

    @Test
    public void testPutGet() throws InterruptedException {
        SampleBean bean = context.getBean(SampleBean.class);
        bean.store("object1", new SampleObject("name1", "value1"));

        for (int i = 0; i < 1000; i++) {
            SampleObject s = bean.read("object1");
            assertThat(s.getName()).isEqualTo("name1");
            assertThat(s.getValue()).isEqualTo("value1");
            
            Thread.sleep(1000);
        }
    }

I don't see any `hlen` invocation during test execution. The only regular task that it could be is `org.redisson.eviction.MapCacheEvictionTask` but it doesn't use `hlen` command at all.

**Comment by mrniko** [comment]
I deployed `3.6.0-5` version with fix for hset command. Please try it

**Comment by Himanshu4** [comment]
When will this fix be available in open-source version?

**Comment by mrniko** [comment]
During this week.
