### ISSUE TITLE
Redisson 2.9.1 Redis 2.8.17 in sentinel mode, redisson subscriber is not self-healing after restarting all redis boxes

### ISSUE THREAD

**Issue by brother-fu** [redisson/redisson#1284]
**Set Up**
Redisson version: 2.9.1
Redis Version: 2.8.17  Mode: Sentinel

Found this issue in our production, not sure if self-healing is supported by redisson during disaster like all redis servers are down, if it is supported, any specific version ?

**Basic Configuration**
```
       public RedissonClient redissonClient() { 
                Config config = new Config();
		config.setThreads(4);
		SentinelServersConfig sentinelServersConfig = config.useSentinelServers()
					.setMasterName(sentinelClusterName)
					.setTimeout(responseTimeout);
		for (String addr : sentinelAddresses) {
			sentinelServersConfig.addSentinelAddress(addr);			
		}
		return Redisson.create(config);
	   }
```

We initialize the subscriber **once** as following during server startup
```
protected void init() {
		RTopic<HeartbeatEvent> topic = redisson.getTopic("test_topic");
		topic.addListener(new MessageListener<HeartbeatEvent>() {
			@Override
			public void onMessage(String channel, HeartbeatEvent message) {
				String host = (String) ((Map) 
                                     SerializationUtils.deserialize(message.getExtraState()))
						.get(CommonConstants.IMAS_SERVER_INTERNAL_ADDRESS);
				if (host != null) {
					SipURI imasUri = createImasSipUri(host);
				}
			}
		});
	}
```

**Steps to recreate:**

_Scenario A:_ 
1. stop all redis-sentinel service
2. stop all redis-server service
3. wait for 2 min
4. start all redis-server service 
5. start all redis-sentinel service

_Scenario B:_ 
(order is  2, 1, 3, 5, 4)

After this, the client is no longer listening to "test_topic"

**Interesting Finding:** 
1. Redisson 2.2.27 is performing better than 2.9.1 in the sense of re-subscribe
2. Even all Client in 2.9.1 version, sharing the same config as above, some clients are able to re-subscribe

I went through the implementation of 2.9.1, found out that if following Scenario B, while doing `MasterSlaveEntry. reattachPubSubListeners()`, the unsubscribe and resubscribe process is trying in best-effort, which is prone to lose listener for a channel, leading clients unable to resubscribe. What is confusing is in Scenario A, some of the clients were able to reconnect somehow.

Is there any way for redisson to survive a redis disaster failure like this ?

**Comment by mrniko** [comment]
Are you running Redis servers on the same address and port as they were before the shutdown?

**Comment by mrniko** [comment]
This issue related to this one https://github.com/redisson/redisson/issues/1280

**Comment by mrniko** [comment]
Thanks for report! Fixed
