### ISSUE TITLE
Multimap tries to keep the List/Set on the same node, but ignores Key Hash Tags in the given Key

### ISSUE THREAD

**Issue by Flyffies** [redisson/redisson#1286]
As I described in the title, I am trying to utilize Key Hash Tags to accumulate data on the same ClusterNode.
I am using a Multimap and noticed the Key for the Lists/Sets are wrapped in the Key Hash Tags and so they may be placed on another Node.

For example:
The MultiMap key is "{multi.map}.some.key".
An entry in it would be saved in the List/Set "{{multi.map}.some.key}:ADJ...".
So the Hash is not "multi.map" but rather "{multi.map".

For further information see the "Key Hash Tag" section on https://redis.io/topics/cluster-spec

**Comment by mrniko** [comment]
It's a bug! Thanks for report!

**Comment by mrniko** [comment]
Done

**Comment by Flyffies** [comment]
Thanks a lot :)
