### ISSUE TITLE
Multiple JVMs tryLock attempt

### ISSUE THREAD

**Issue by ledbruno** [redisson/redisson#1289]
We have a spring application running in 3 different servers/jvms. Those services receives an event notification with an eventID.

In order to avoid event processing duplication we are trying to use redis lock, to process only one event each time. We have multiple requests with same eventID coming from other services, so this is a very common scenario.

The lock is centralized in one Spring Bean

```
public class RedisDistributedLock implements DistributedLock {

	private static final String PREFIX = "bucketName:";
	private static final int TIMEOUT = 1;

	@Autowired
	private RedissonClient redissonClient;

	public boolean lock(String action, String lockKey) {
		try {
			return redissonClient.getLock( PREFIX + action + ":" + lockKey ).tryLock( 0, TIMEOUT, TimeUnit.MINUTES );
		} catch (InterruptedException e) {
			log.error( "Failed to lock " + lockKey + " for action " + action, e );
			return false;
		}
	}

	public void unlock(String action, String lockKey) {
		redissonClient.getLock( PREFIX + action + ":" + lockKey ).unlock();
	}

}
```

Each time an event comes we first verify if we can lock
```
if (redisDistributedLock.lock(action,eventId))
      eventProcessor.process("eventId")
else
      log.info("cant use, someone else is already processing this event")

```

Our redissonClient is injected by spring
```

       @Bean
 	public RedissonClient buildRedissonClient(@Value("${redis.url}") String url) {
		final Config config = new Config();
		config.useMasterSlaveServers().setMasterAddress( url );
		//config.useSingleServer().setAddress( "redis://master:6666" );
		return Redisson.create( config );
	}

```

We also the singleServer approach (commented above). But in both scenarios events are processed twice, eventually.

We don´t understand what its wrong. Can someone give us a clue?

**Comment by ledbruno** [comment]
Our tests passed.

![image](https://user-images.githubusercontent.com/916289/36036507-2f088870-0da1-11e8-865d-a7af3e77bb4e.png)

I could not execute inside Redisson projecto, so i extracted the test to my project

The setup is:

```
        this.threads = 4;
        this.loops = 1000;
        executor = Executors.newFixedThreadPool(threads);
        final Config config = new Config();
        config.useMasterSlaveServers().setMasterAddress( "redis://myServerAddr:8888 );
        redisson = Redisson.create( config );

```

The output of the test is pretty regular its in this gist
https://gist.github.com/ledbruno/0c0de2ca4c8cb2e21a90fda109af3a00

Are there any amazon Redis special config for Distributed locking? We are using amazon hosted one. Or any different way to instantiate the redisson client?

In our tests the problem occurs very quickly. A python script running 10 simultaneous threads doing 9 requests each to 3 random servers. The servers have the Java code with the locking part. It doesn´t take too much (30 sec max) to see problems (duplications) on the log.

**Comment by mrniko** [comment]
> Are there any amazon Redis special config for Distributed locking? We are using amazon hosted one. Or any different way to instantiate the redisson client?

It works in the same way for other environments like Azure or any other custom Redis setup.

Seems the problem is in your application code. Please make sure that same key is not shared with different Redisson object.

**Comment by ledbruno** [comment]
I think the key is not shared. We use a compose value
 PREFIX + action + ":" + lockKey.
And the lock key is a random UUID, on our test script. The prefix and action is the same for all events, but as far as we know it´s totally different from other keys, used by other services.

**Comment by mrniko** [comment]
Yes, I mean object representation. There were some cases already, when developer used same key for RLock and RBucket object, etc... He deleted bucket object so it deletes the acquired lock itself. Therefore you'll get second phantom lock which could be locked again.

**Comment by mrniko** [comment]
Is it possible that event processing lasts more than one minute (lease timeout in your example) ? If so then you can get such situation

**Comment by mrniko** [comment]
Unable to reproduce it on multiple AWS EC2 and AWS Elasticache instances
