### ISSUE TITLE
RExecutorService - Task resume on another worker doesn't happen, when worker(redisson node) goes down 

### ISSUE THREAD

**Issue by jaxbihani** [redisson/redisson#1291]
Problem: 
----------
We are evaluating Redisson as a distributed task queue manager and as a result the expected behaviour for failure scenario is: 
 -- If a worker starts working on a task and if worker goes down before completing the task then task should be resumed on another worker. 
As per our observation this doesn't happen.
For SIGINT and SIGQUIT signal - Most of the times it finished the running tasks. (We found couple of instances where it didn't happen)
For SIGKILL (when worker is killed using kill -9), executing tasks are lost.

Can you please help us understanding that is the above mentioned 'expected behaviour' correct? Does redisson provide this guarantee? If yes are we missing some configuration? If no, please indicate what is the best practice for using Redisson in this case?

Environment & Setup details:
--------------------------------
Mac OS X 10.10.5
Java version: 1.8.0_141
Redis Version : 2.8.24
Redisson Version : 3.6.0
Redis used in Single Server mode

We have two Redisson Nodes running with the config: 
<img width="436" alt="screen shot 2018-02-09 at 11 15 18 am" src="https://user-images.githubusercontent.com/806775/36013514-98db86f6-0d8a-11e8-94e8-72b9e7a3d090.png">

Here is the code of the the Task : 
`
import org.redisson.api.RedissonClient;
import org.redisson.api.annotation.RInject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.Callable;

public class SleepTask implements Callable<String> {

    @RInject
    private RedissonClient redissonClient;

    private long sleepDurationInMillis;
    public final static Logger logger = LoggerFactory.getLogger(SleepTask.class);

    int threadNo;

    public SleepTask() {
    }

    public SleepTask(long sleepDurationInMillis, int threadNo) {
        this.sleepDurationInMillis = sleepDurationInMillis;
        this.threadNo = threadNo;
    }

    @Override
    public String call() throws Exception {
        try {
            logger.info("Executing  the task for sleep duration of: "+threadNo+" " +sleepDurationInMillis);
            Thread.sleep(sleepDurationInMillis);
            logger.info("Done executing  the task for sleep duration of: "+threadNo+" " +sleepDurationInMillis);
        }
        catch(InterruptedException e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return  "FAILURE:"+sleepDurationInMillis;
        }
        return "SUCCESS:"+sleepDurationInMillis;
    }
}
`

Here is the main code which is invoking it:
`public static void main(String [] args) throws IOException, ExecutionException, InterruptedException {
        App app = new App();
        Config config = Config.fromJSON(app.getConfigFile());

        RedissonClient client = Redisson.create(config);
        RExecutorService executorService = client.getExecutorService("myExecutor1");

        BufferedReader br= new BufferedReader(new InputStreamReader(System.in));
        String input;
        int i=1;
        logger.info("App has moved out of connection phase and active workers are: "+ executorService.countActiveWorkers());
        while((input = br.readLine()) != null) {
            long sleepDuration = Long.parseLong(input);
            logger.info("Adding the task for sleep duration of: "+" " +sleepDuration);
            Future<String> result = executorService.submitAsync(new SleepTask(sleepDuration,i++));
            try {
                logger.info("Added the task for sleep duration of - with result: "+" " +sleepDuration+" ");
            } catch (Exception e) {
                logger.error(e.getMessage());
                e.printStackTrace();
            }
            //executorService.submit(new Producer(sleepDuration,i++));
        }
        //result.get(35000, TimeUnit.MILLISECONDS)
    }`

Commands with which I start two Redisson Nodes are: 
java -jar ~/Downloads/redisson-all-3.6.0.jar /Users/xyz/POCs/src/main/resources/redisson_config.json

Please let me know if any more details are needed.

**Comment by mrniko** [comment]
> For SIGINT and SIGQUIT signal - Most of the times it finished the running tasks. (We found couple of instances where it didn't happen)

Fixed

**Comment by mrniko** [comment]
Done. `ExecutorOptions.taskRetryInterval` setting added
