### ISSUE TITLE
CertificateException while connecting to Azure redis cluster.

### ISSUE THREAD

**Issue by haiS8dn** [redisson/redisson#1296]
I have got CertificateException when Redisson try to connect.

Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 12.34.567.89 found
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:167)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501)
	... 28 more

When i disabled the setSslEnableEndpointIdentification the connection was successfully established.

The scenario is when I'm using useClusterServers config 
the Redisson client sends cluster nodes command to Azure Redis, 
the server responses with a list of IP and port of cluster nodes, then Redisson client try to connect to newly discovered masters, but now the target is IP and Azure doesn't sign the certificate.

Important note:
all the discovered IPs are the same IP resolved by endpoint URL (which provided by Azure).

I saw that other redis clients separate the endpointIdentification for the base connection and cluster node connection.
If we are able to do node cluster endpointIdentification with the base connection verification it will solve the issue.

Thanks

**Comment by mrniko** [comment]
> all the discovered IPs are the same IP resolved by endpoint URL (which provided by Azure).

Why can't you use single server connection mode then?

**Comment by haiS8dn** [comment]
@mrniko 
When I'm using single server.
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=1044, addr=//12.34.567.89:15001, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet

**Comment by mrniko** [comment]
how to get same configuration on Azure hosting?

**Comment by mrniko** [comment]
> the server responses with a list of IP and port of cluster nodes, then Redisson client try to connect to newly discovered masters, but now the target is IP and Azure doesn't sign the certificate.

Could you share result of `cluster info` command for this case?

**Comment by mrniko** [comment]
Please correct me if I wrong. `cluster node` command used to scan cluster state always returns ip addresses. It's impossible to use domain name then. So I think `endpointIdentification` should be always disabled for Redis node connection in this case.

**Comment by haiS8dn** [comment]
When I create Azure redis cluster, Azure supplies an URL and port to establish a connection.
If I'm disabling the endpoint identification, This can lead to security problems.

**Comment by mrniko** [comment]
So `SslEnableEndpointIdentification` could be applied only to endpoint URL?

**Comment by haiS8dn** [comment]
The best solution for this issue is when you build the SSlContext
from RedisChannelInitializer
`SSLEngine sslEngine = sslContext.newEngine(ch.alloc(), config.getAddress().getHost(), config.getAddress().getPort());`
Here if we change the address to the base endPoint instead each node address it solving the issue.
The alternative is to disable SslEnableEndpointIdentification when you connect to each redis nodes after you authenticate with the base endpoint.

**Comment by mrniko** [comment]
Are you able to provide poll request?

**Comment by mrniko** [comment]
Fixed
