### ISSUE TITLE
Support for dnsMonitoring in Sentinel Setup

### ISSUE THREAD

**Issue by leolimajr** [redisson/redisson#1299]
After the fix of https://github.com/redisson/redisson/issues/1280 which improved greatly the resilience of Sentinel setup, it would be great to have **dnsMonitoring**  feature as well because in failover scenarios of sentinels instances, the box can get a different IP and the current implementation caches the dns resolution forever.  It means it never reconnects to new sentinels in the cluster.

**Comment by mrniko** [comment]
Done
