### ISSUE TITLE
Performance issues with updateMode=AFTER_REQUEST

### ISSUE THREAD

**Issue by lying1234** [redisson/redisson#1302]
We are trying to use updateMode=AFTER_REQUEST to make sure all the session data will be saved into Redis server. After reviewing the source code, looks it may cause performance issues since we keep a lot of data in the session, and store function will be called on every request no matter there is session changes or not.

1. Currently when updateMode=AFTER_REQUEST is on, session data will be saved twice in the Redis server if session.setAttribute(..) is called. First time is triggered by setAttribute() method, second time is triggered by AFTER_REQUEST. Can the first insert/update can be removed when AFTER_REQUEST is set?

2. Is it possible put save session data to Redis after tomcat request code to a **separate thread**?

**Comment by ananchen1** [comment]
I'm hoping when updateMode=AFTER_REQUEST, the Redis server connection and data sync should happen only once after tomcat request is done, if this can be put in separate thread without affect main tomcat thread, it can be very helpful to avoid the redis exception not cause the tomcat thread fail which is similar with how tomcat cluster doing.

**Comment by mrniko** [comment]
I removed setAttribute method invocation. Store method now uses putAll to save all session data by one request to Redis.

@ananchen1
> to avoid the redis exception not cause the tomcat thread fail which is similar with how tomcat cluster doing.

Could you please share any code reference?
