### ISSUE TITLE
RedisClient does not override 'hashcode and equals' may cause  redis connections are not closed properly.

### ISSUE THREAD

**Issue by brooklyn-knightley** [redisson/redisson#1304]
I found that in `master-slave` mode, the redis connections on slave servers may not get closed properly.
[Caused by: org.redisson.client.RedisException: ERR max number of clients reached](https://github.com/redisson/redisson/issues/1288)

After reading the source code, I found that the reason is that RedisClient does not override `hashcode` and `equals`.

Consider the following situation：
1. One hostname `slave-hostname` maps to two ip-addresses: `ip1`, `ip2`
1. Firstly, `slave-hostname`  maps to `ip1`, client2Entry will cache new `RedisClient` and `ClientConnectionsEntry` instances: `RedisClient-ip1` and `ClientConnectionsEntry-ip1` 
```
public RFuture<Void> add(final ClientConnectionsEntry entry) {
        RPromise<Void> result = new RedissonPromise<Void>();
        
        CountableListener<Void> listener = new CountableListener<Void>(result, null) {
            public void operationComplete(io.netty.util.concurrent.Future<Object> future) throws Exception {
                super.operationComplete(future);
                if (this.result.isSuccess()) {
                    client2Entry.put(entry.getClient(), entry);
                }
            };
        };

        RFuture<Void> slaveFuture = slaveConnectionPool.add(entry);
        listener.incCounter();
        slaveFuture.addListener(listener);
        
        RFuture<Void> pubSubFuture = pubSubConnectionPool.add(entry);
        listener.incCounter();
        pubSubFuture.addListener(listener);
        return result;
    }
```
3. DNS  changes from `ip1` to `ip2`, all the connections of `ClientConnectionsEntry-ip1` were closed properly.
1. DNS  changes from `ip2` to `ip1`, client2Entry will cache another `RedisClient` and `ClientConnectionsEntry` instances: `RedisClient-ip1-1` and `ClientConnectionsEntry-ip1-1`. `RedisClient-ip1-1` was different from `RedisClient-ip1` as they were not the same instance.
1. DNS  changes from `ip1` to `ip2` again, 
All the connections of `ClientConnectionsEntry-ip1-1` should get closed properly.  When san client2Entry values, it is possible to find `ClientConnectionsEntry-ip1` or `ClientConnectionsEntry-ip1-1`
```
    protected ClientConnectionsEntry getEntry(InetSocketAddress address) {
        for (ClientConnectionsEntry entry : client2Entry.values()) {
            InetSocketAddress addr = entry.getClient().getAddr();
            if (addr.getAddress().equals(address.getAddress()) && addr.getPort() == address.getPort()) {
                return entry;
            }
        }
        return null;
    }
```
The connections of `ClientConnectionsEntry-ip1-1` may not get closed properly.

-------------------------------------------------------
Our `master-slave` model
1. one master server
1. two slave servers, with one slave hostname, DNS changes every twenty seconds.

**Comment by mrniko** [comment]
Thanks for report! The problem was in adding another client with same IP which was already added. Fixed
