### ISSUE TITLE
RBloomFilter.expire only deletes Bloom Filter string, not hash

### ISSUE THREAD

**Issue by prashantgupta24** [redisson/redisson#1305]
### Problem

 If I initialize a bloom filter like this

```
RBloomFilter<String> filter = redissonClient.getBloomFilter("test");
filter.tryInit(10000, 0.01);
filter.expire(1l, TimeUnit.MINUTES);
```

The String `test` is the only thing that gets deleted from Redis after expiration time. The config hash `{test}:config` remains even after expiration.

### Env details

Mac OS X 10.13.2
Java version: 1.8.0_151
Redis server v=4.0.7
Redisson Version : 3.6.0
Redis used in Single Server mode

**Comment by mrniko** [comment]
Thanks for report! Fixed
