### ISSUE TITLE
should not clear channel and listeners when unsubscribe failure

### ISSUE THREAD

**Issue by brother-fu** [redisson/redisson#1309]
This is very likely a bug.
in https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/RedisPubSubConnection.java#L118

Set up:
Redis: Sentinel Mode
Redisson: version 2.9.1   read from slave

Steps to Recreate:
1. shut down all redis-sentinels
2. shut down all redis-servers
3. wait for some time (redisson client initiates enough "GET" command, and connection_pool reset cause maximum failed attempts reached)
4. restart all redis-server
5. restart all redis-sentinel

in step3: slaveDown happens when maximum attempts reached, but it was unable to send "Unsubscribe"

but in https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/RedisPubSubConnection.java#L118, when "UNSUBSCRIBE" failure happens, it removes the channel and remove all the listeners.

my thoughts is when "UNSUBSCRIBE" failure, we should readd the channel, and not executing onMessage()

**Comment by mrniko** [comment]
If unsubscribe couldn't be executed that means that connection is not in active state and thus not subscribed anymore.
