### ISSUE TITLE
Wrong classloader used by TasksRunnerService?

### ISSUE THREAD

**Issue by l0co** [redisson/redisson#1310]
Today I had a lot of work to bind embedded Redisson Node with Spring Boot. [Here](http://lifeinide.com/post/2018-02-18-redisson-node-spring-fixing-classloader-problem/) are the final thoughts and conclusions. In short I believe creating own codec in `TasksRunnerService` using `TasksRunnerService` class loader is a bug. Please review the article for more details.

**Comment by mrniko** [comment]
Hi! Thanks for the article!

It supposed to work correctly in your case. The one thing I didn't get is why `getClass().getClassLoader()` in code below differs from `new SerializationCodec(getClass().getClassLoader());` created in your `RedissonConfiguration`

https://github.com/redisson/redisson/blob/a5c26a13dca405b56138e6da4f4a0c36d8223346/redisson/src/main/java/org/redisson/executor/TasksRunnerService.java#L169

**Comment by l0co** [comment]
In task runner you use `getClass()` from `TaskRunnerService` class to get the class loader. This is different class loader than in my `RedissonConfiguration` bean. The bean is in the project, while task runner comes from library jar and with Spring Devtools autoreloading feature they belongs to different class loaders.

This can be solved in the way I showed, but I'm wondering why [here](https://github.com/redisson/redisson/blob/a5c26a13dca405b56138e6da4f4a0c36d8223346/redisson/src/main/java/org/redisson/executor/TasksRunnerService.java#L71) you have the codec, but you anyway create another instance with different class loader?

**Comment by mrniko** [comment]
I use different class loader to avoid Out of Memory in PermGen or Metaspace area.

**Comment by mrniko** [comment]
Fixed!

**Comment by jasonab** [comment]
I'm experiencing this issue now with the latest Redisson - with devtools, I get codec errors trying to inject Spring beans into Redisson tasks.
