### ISSUE TITLE
Tomcat Session Manager issue to renew session in Load Balance environment

### ISSUE THREAD

**Issue by Leuloch** [redisson/redisson#1311]
Hi!

I'm using Redisson 3.6.0 with redisson-tomcat 3.5.6 with:

1. Elasticache Redis Cluster
2. Spring App deployed on two instances EC2 Tomcat (instance 1 and instance 2)
3. Load Balance with non-sticky session

My session timeout is configured to 30min.

The steps to reproduce the issue:
a. User logged in on instance 1 (a new session is created with timeout of 30 min);
b. After 15 min, an ajax request was made by the application which was managed by 'instance 2' refreshing the session to more 30min;
c. After more 20min the user reload the page, and the load  balance send some requests to 'instance1' and to 'instance 2', but the instance 1 has been idle  for 35minutes and because of that, delete the session that was renewed 20 min ago!

This issue is only reproducible using at least two instances behind a load balance with non-sticky session because the action to delete the session ignores if the session was renewed by other instances.

Is there anything I can do to prevent this behavior?

I think this is related with https://github.com/redisson/redisson/issues/972

**Comment by mrniko** [comment]
I have just tested it with session timeout = 1 min:
Below is my test:

```java
    @Test
    public void testExpiration() throws Exception {
        TomcatServer server1 = new TomcatServer("myapp", 8080, "/src/test/");
        server1.start();

        Executor executor = Executor.newInstance();
        BasicCookieStore cookieStore = new BasicCookieStore();
        executor.use(cookieStore);
        
        write(executor, "test", "1234");
        Cookie cookie = cookieStore.getCookies().get(0);


        TomcatServer server2 = new TomcatServer("myapp", 8081, "/src/test/");
        server2.start();

        Thread.sleep(30000);
        
        read(8081, executor, "test", "1234");

        Thread.sleep(40000);
        
        read(executor, "test", "1234");
        
        Executor.closeIdleConnections();
        server1.stop();
        server2.stop();
   }

    private void write(Executor executor, String key, String value) throws IOException, ClientProtocolException {
        String url = "http://localhost:8080/myapp/write?key=" + key + "&value=" + value;
        String response = executor.execute(Request.Get(url)).returnContent().asString();
        Assert.assertEquals("OK", response);
    }
    
    private void read(Executor executor, String key, String value) throws IOException, ClientProtocolException {
        String url = "http://localhost:8080/myapp/read?key=" + key;
        String response = executor.execute(Request.Get(url)).returnContent().asString();
        Assert.assertEquals(value, response);
    }
    
    private void read(int port, Executor executor, String key, String value) throws IOException, ClientProtocolException {
        String url = "http://localhost:" + port + "/myapp/read?key=" + key;
        String response = executor.execute(Request.Get(url)).returnContent().asString();
        Assert.assertEquals(value, response);
    }


```

**Comment by Leuloch** [comment]
@mrniko Thanks for the reply!!!

I forked this project and I have just tested locally. My output:

![redisson-test](https://user-images.githubusercontent.com/5075742/36390617-77d1c7f4-1582-11e8-98a0-bee29a692b07.png)

**Comment by mrniko** [comment]
Fixed

**Comment by Leuloch** [comment]
Already tested in production! Works like a charm. Thanks!

**Comment by mrniko** [comment]
You're welcome!

**Comment by Leuloch** [comment]
@mrniko May I know the timeline for 3.6.2?

**Comment by mrniko** [comment]
During next month.
