### ISSUE TITLE
is it possible to add a duplicate check when RedisPubsubConnection addListener ?

### ISSUE THREAD

**Issue by brother-fu** [redisson/redisson#1312]
Sorry to open so many issues for the same problem, feel free to close it if you think this is not appropriate.

https://github.com/redisson/redisson/issues/1284
https://github.com/redisson/redisson/issues/1309

We are trying to have the best availability of our service when redis servers in Sentinel mode run into disaster situations (like all redis-server, redis-sentinel are down)

Currently, what we are trying is when Redisson client last received ping is too old, it will try to re-subscribe to the same channel. However, this introduced new problems, when the QPS is high, we added multiple listeners for the same client to the same channel, which is not optimal.

In following two places, there is no duplicate check (if the listener already in the PubsubConnection, don't add the listener)
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/PubSubConnectionEntry.java#L91
 
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/RedisPubSubConnection.java#L61

Is it possible to add a duplicate check that only when the listener is not there, we add the listener to the connection ?

**Comment by mrniko** [comment]
Could you provide code example to reproduce listeners duplication problem?
