### ISSUE TITLE
The cache in redis can not be clear automatic when Redisson resatrt

### ISSUE THREAD

**Issue by Wesly186** [redisson/redisson#1316]
![](https://i.stack.imgur.com/rskyy.png)
```
@Bean
public CacheManager cacheManager(RedissonClient redissonClient) throws IOException {
    Map<String, CacheConfig> config = new HashMap<String, CacheConfig>();
    config.put(CacheNames.XinLianService_getAllAgentData, new CacheConfig(60 * 1000, 60 * 1000));
    config.put(CacheNames.XinlianRoleService_getById, new CacheConfig(2 * 60 * 1000, 60 * 1000));
    return new RedissonSpringCacheManager(redissonClient, config);
}
```

I hava set the ttl and idleTime for cache, the cache can be remove when the app is running, however when I restart app the EvictionScheduler may not work for cache, the cache can not be clear when ttl approach. Does it problem have any solution?

**Comment by jackygurui** [comment]
`the cache can be remove when the app is running` Are you suggesting you are manually removing the hash in Redis?

**Comment by Wesly186** [comment]
Thanks reply! The cache is removed by Redisson itself. @jackygurui

**Comment by jackygurui** [comment]
OK, thanks for the confirmation.

Can you walk me through again in more detail as to how you have come to the conclusion that the EvictionScheduler may not be working and `cache can not be clear when ttl approach`?

**Comment by Wesly186** [comment]
OK, I will replicate the problem by the following steps:

# 1. start the application

![](https://ws1.sinaimg.cn/large/005zqNvmgy1fouxoes2hkj30wz0bjjty.jpg)

# 2. call this method and the cache will be stored in redis with ttl
```java
@Cacheable(cacheNames = CacheNames.XinLianService_getAllAgentData)
public Optional<List<AgentData>> getAllAgentData(String orgId) {
    //...
}
```
![](https://ws1.sinaimg.cn/large/005zqNvmly1fouy2n0mpsj30bm07j3yk.jpg)

# 3. force stop the application
![](https://ws1.sinaimg.cn/large/005zqNvmly1fouy4nv2l5j30af081mxc.jpg)

# 4. restart the application
![](https://ws1.sinaimg.cn/large/005zqNvmgy1fouy5yvkstj308n05uwef.jpg)

# 5. the cache can not be removed automatic when ttl time approach
![](https://ws1.sinaimg.cn/large/005zqNvmgy1fouyarcdvoj30bm07i0ss.jpg)

**Comment by Wesly186** [comment]
I find something else.

the source code of `RedissonMapCache` show that the `EvictionScheduler`  starts work only when a new mapCache was created.
```java
public RedissonMapCache(EvictionScheduler evictionScheduler, CommandAsyncExecutor commandExecutor,
                            String name, RedissonClient redisson, MapOptions<K, V> options) {
        super(commandExecutor, name, redisson, options);
        if (evictionScheduler != null) {
            evictionScheduler.schedule(getName(), getTimeoutSetName(), getIdleSetName(), getExpiredChannelName(), getLastAccessTimeSetName());
        }
}
```
so I call this method when I restart the application and then the `MapCacheEvictionTask.execute()` start work and the cache can be removed from redis.
```java
@GetMapping(value = "testCache")
public void test(){
    redissonClient.getMapCache(CacheNames.XinLianService_getAllAgentData);
}
```

**Comment by Wesly186** [comment]
some suggestions:

1. Is it possible to use redis it own ttl function replace evictionScheduler?
2. Is it possible to automatic start evictionScheduler when application restart rather than after I manually call createCache mtethod?

**Comment by Wesly186** [comment]
@jackygurui

**Comment by Wesly186** [comment]
I find redisson will auto ignore expired cache and clear it in redis when restart, it is not a bug, thanks @jackygurui

**Comment by jackygurui** [comment]
Hi, @Wesly186 

Regarding your suggestion:
> Is it possible to use redis it own ttl function replace evictionScheduler?

It is not possible to do so simply because redis' own ttl only works at the key space level. 

> Is it possible to automatic start evictionScheduler when application restart rather than after I manually call createCache mtethod?

EvictionScheduler is started when Redisson instance is created. See [here](https://github.com/redisson/redisson/blob/dfa3b4c2dd112e68256d20227747ac534a582c5f/redisson/src/main/java/org/redisson/Redisson.java#L116) for details.

**Comment by jackygurui** [comment]
> I find redisson will auto ignore expired cache and clear it in redis when restart, it is not a bug, thanks

Thanks for the confirmation. Just a little more insight on the expiration here: Field level expiration works similar to key expiration in redis, it has both passive and active checks. EvictionScheduler runs periodically to invalidate the elements past the expiry time, an additional check is carried out when an element is requested. If would be evicted if the check has failed.
