### ISSUE TITLE
Redisson 3.6.0 memory leak with cluter batch

### ISSUE THREAD

**Issue by jokoz** [redisson/redisson#1318]
018-02-28 19:56:31,534:io.netty.util.ResourceLeakDetector.reportTracedLeak(ResourceLeakDetector.java:311).LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: .

**Comment by mrniko** [comment]
Is there any way to reproduce that?
