### ISSUE TITLE
Configurable Tomcat Session Key Prefix for Redis

### ISSUE THREAD

**Issue by devel83** [redisson/redisson#1320]
`RedissonSessionManager` uses "redisson_tomcat_session:"  as key prefix, so if multiple tomcat instances are using same "redis" server for storing session data. So need a mechanism to configure default key prefix.

**Comment by devel83** [comment]
I have sent a pull request for [this](https://github.com/redisson/redisson/pull/1321)

**Comment by mrniko** [comment]
Merged
