### ISSUE TITLE
calling getMap() million times creates millions of map instances

### ISSUE THREAD

**Issue by kaniska** [redisson/redisson#1322]
While reading the Redisson tutorial and examples, I am under the impression that I need to always call redisson.getMap() in order to get the latest data from the cache . Right ? 

I have a storm bolt which calls getmap(key) for millions of incoming records 
Looks like millions of instances of RedisonMap being created , leading to pressure on GC

**Comment by jackygurui** [comment]
With each `redisson.getMap()` invocation, it returns an `RMap` instance. This instance can safely shared between each thread, feel free to reuse.

**Comment by kaniska** [comment]
thanks @jackygurui , very urgently I am looking for a solution.

since you have responded so promptly, can you kindly clarify the following --

(A) // create only one instance of a top-level map in my storm-bolt instance-1
RMap<String, Map<String, Integer> userBucket = redisson.getMap("UserBucket")   

(B) // now calling userBucket multiple times through the following function in the storm-bolt instance-1
function checkUserOrderedItem(userId, productCode, Add_Remove_Flg)
  if(userBucket.get(userId) == null) {
    Map<String, Integer> userOrderCount = new HashMap<String, Integer>();
    userOrderCount.put(productCode, 1);
     userBucket.put(userId, **userOrderCount**);
  }// else if Remove_product  and decrement the count in the userOrderCount map for this user

**Questions**
-- I have 8 java-instances running in 8 different threads --
I can declare one static instance of RMap and use in all the 8 bolt-instances or I can have 8 seperate RMaps one per bolt-instance.
 
> which approach is preferable ?
> will I get consistent updates if I create 8 separate RMaps ?
- i.e. if one threads updates the count in its own Rmap , will the thread get the latest count in its Rmap ?
> should I create the inner map userOrderCount as - HashMap / ConcurrentHashmap / RedissonMap (RMap)  ?
> should I acquire RLock before calling  >> redisson.getMap("UserBucket") ? as I am not sure 2 bolt-instances will try to create it at the same time 
> should I acquire RLock inside >> checkUserOrderedItem(..) assuming multiple threads can try to update the userOrderCount in multiple bolt-instances 

Much appreciate your help.

**Comment by jackygurui** [comment]
Err, isn't it just a single `RAtomicLong` will do the trick?
```
RAtomicLong userOrderCount = redisson.getAtomicLong(userId + ":" + productCode);
// increase order;
userOrderCount.incrementAndGet();
// decrease order;
userOrderCount.decrementAndGet();
```

No lock, no map, no buckets, no consistency issues. And as always, thread safe, even cross node.

**Comment by mrniko** [comment]
> (1) will I get consistent updates in each thread in each machine ?

Yes, you will. Since there is a single data source - Redis store. It is updated atomically.

> should I create the inner map userOrderCount as - HashMap / ConcurrentHashmap / RedissonMap (RMap) ?

You could use `RMap.addAndGet` to increment value per key.

**Comment by kaniska** [comment]
Much appreciate the great suggestions. 

Another quick question - How can I ensure that **RScheduledExecutorService** schedules a job only once , when multiple instances of the same parent scheduler class running in different machines and trying to schedule the same job.  
I just want to ensure the job is scheduled only once , I can maintain a counter/boolean flag  in a redis map and check before scheduling the job.

But if RScheduledExecutorService **internally takes care of scheduling only once** OR **provide a way to check if a job already submitted**;  then I will not maintain a separate flag.

Thanks

**Comment by mrniko** [comment]
@kaniska 

> I just want to ensure the job is scheduled only once 

You don't need that RScheduledExecutorService is a queue based. This guarantees that job will be polled only once from tasks queue.

**Comment by kaniska** [comment]
you are awesome ! thanks for making this discussion so lively :-) and I am loving Redisson more :-) .. 

seeking your quick suggestions on couple of things -- 
(1) as per the previous post, whats the advantage of using RScheduledExecutorService over usual Scheduler Service ?

(2) I am following -

> 10.2.
> References to Redisson objects
> It's possible to use a Redisson object inside another Redisson object in any combination. In this case > a special reference object will be used and handled by Redisson

**Can you please confirm if following logic looks correct or if it can be optimized further **

In order to maintain a map of car entry time in a region -- I am creating a reference of Rmap inside another Rmap and reference of RatomicLong inside inner Rmap -- 
RMap regionCarEntryMap <- redisson.getMap(regionId)

if(!regionCarEntryMap.containsKey(carId)){
 regionCarEntryMap.put(carId, redisson.getMap(regionId+carId))
}
RMap carEntryMap = regionCarEntryMap.get(carId)

RAtomicLong carEntryTime <- redisson.getMap(regionId+carId)
carEntryTime.set(System.currentMillisec())
carEntryMap.put(carId,carEntryTime)

Note that - I can't use a single cache (regionid+carId , entryTime) as carEntryMap.size() tells me how many cars are inside a region and I need to dynamically remove the car key from outer map if car leaves the region.

At any point of time, I need to calculate how many cars are in a region and how long a car spent in a region, thats why I need the above structure. 

Thanks again,
Kaniska
