### ISSUE TITLE
Redisson 3.5.7 memory leak with locks

### ISSUE THREAD

**Issue by kaduparag** [redisson/redisson#1326]
I'm using RLock and seeing memory leak via org.redisson.client.handler.CommandPubSubDecoder 
 
![image](https://user-images.githubusercontent.com/443442/37062360-0f201f60-214b-11e8-81a2-d2fab78261c4.png)

Retained objects delta between heap dumps taken apart
![image 1](https://user-images.githubusercontent.com/443442/37062341-01519f12-214b-11e8-8d35-4bc50413fd50.png)

Around 10MB leak per day
![image 2](https://user-images.githubusercontent.com/443442/37062443-5150dfdc-214b-11e8-944f-fb46ec393693.png)

**Comment by mrniko** [comment]
Hi! Could you share your code with Lock object usage?

**Comment by kaduparag** [comment]
We have following class RedisLock invoking the redisson lock api:

    public void acquireLock(final Object object) {
        getLockInstance(object).lock(this.redisConfigManager.getLockTimeoutInMillis(), TimeUnit.MILLISECONDS);
    }
    public void releaseLock(final Object object) {
        getLockInstance(object).unlock();
    }
    public void acquireReadLock(final Object object) {
        getReadWriteLockInstance(object).readLock().lock();
    }
    public void releaseReadLock(final Object object) {
        getReadWriteLockInstance(object).readLock().unlock();
    }
     public void acquireWriteLock(final Object object) {    
         getReadWriteLockInstance(object).writeLock().lock
        (this.redisConfigManager.getLockTimeoutInMillis(),  TimeUnit.MILLISECONDS);
    }
    public void releaseWriteLock(final Object object) {
         getReadWriteLockInstance(object).writeLock().unlock();
    }

    private RLock getLockInstance(final Object object) {
        Assert.notNull(object, "Cannot lock or unlock a null object");

        final RLock rLock = this.redisson.getLock(Integer.toString(object.hashCode()));
        if (rLock == null) {
            throw new IllegalStateException("Cannot get lock instance.");
        }
        return rLock;
    }

    private RReadWriteLock getReadWriteLockInstance(final Object object) {
        Assert.notNull(object, "Cannot lock or unlock a null object");

        final RReadWriteLock rwLock = this.redisson.getReadWriteLock(Integer.toString(object.hashCode()));
        if (rwLock == null) {
            throw new IllegalStateException("Cannot get read write lock instance.");
        }
        return rwLock;
    }

This is used at multiple places with following pattern
       `  try {
            this.redisLock.acquireLock(object);
           //  do work
          } finally {
             this.redisLock.releaseLock(object);
        } `

**Comment by mrniko** [comment]
I confirm, it's a regression since 3.4.4 version. Thanks for report!

**Comment by mrniko** [comment]
Fixed

**Comment by hs2651** [comment]
thank you @mrniko for the confirmation, and the fix! When can we expect this to be released?

**Comment by mrniko** [comment]
@hs2651 in next two weeks or so
