### ISSUE TITLE
我有一个IDEA

### ISSUE THREAD

**Issue by konglz** [redisson/redisson#1328]
我希望redisson能提供一些连接效率和查询效率的统计功能，

并且把这些统计导出到jmx上面，

alibaba开源的druid连接池也有这个功能。

很多开发不清楚他们应该配什么参数，比如connectionPoolSize，

因为各家环境不同，没有1个统一的配置能包打天下

我想，如果提供这个功能，应该能够帮助开发 优化redisson参数配置、诊断线上问题。

@jackygurui

**Comment by jackygurui** [comment]
PRO版里早已经有这个功能。
