### ISSUE TITLE
Old/stale nodes not removed from NodesGroup

### ISSUE THREAD

**Issue by adamdougal** [redisson/redisson#1330]
When trying to implement a healthcheck for a Redis Cluster I'm using code similar to the below to get the list of nodes and ping them to see if they're up.

```
NodesGroup nodesGroup = redisson.getNodesGroup();
Collection<Node> allNodes = nodesGroup.getNodes();
for (Node n : allNodes) {
    n.ping();
}
```

If I redeploy a node and it gets a new IP, the new node is returned by `redisson.getNodesGroup();` but the old one remains and we get an error:

`Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=[addr=redis://OLD.IP.ADD.RESS:6379], redirect=null, entry=null], connection: [id: 0x511b46ea, L:0.0.0.0/0.0.0.0:39616], command: (PING), params: []`

If I failover a slave node then the slave node will be returned by `redisson.getNodesGroup();` as a master (which is correct) but the original master will appear twice as both a master and a slave. If I then failover back to the original master, that node will be returned as a master twice and still as a slave.

When digging into the code it looks like this list/map lives in `MasterSlaveConnectionManager` as `clientEntries` which only gets cleared or removed from during a shutdown.

What I'd expect is for old or stale nodes to be cleared up from this list/map.

**Comment by adamdougal** [comment]
I've also noticed another potentially issue where that the number of connected clients grows for every failover. I think it's because I've not configured my own `ExecutorService` so every time a new `RedisClient` is created and put into `clientEntries` it creates a new one.

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/RedisClient.java#L92

**Comment by mrniko** [comment]
ExecutorService is created by Redisson, if it not defined in config, and passed to RedisClient object. So, all RedisClient use same Executor instance.

**Comment by mrniko** [comment]
Done
