### ISSUE TITLE
Slow down when Redis master switching (sentinel)

### ISSUE THREAD

**Issue by aymhce** [redisson/redisson#1332]
Hi,

We have detect an issue on our redis (sentinel) cluster when there is a redis master switching .
During a performance test, we use PriorityQueue (~ 10 calls / seconds). All transaction are closed on 20-50 milli-seconds.
When master switching, on JConsole we have seen Redisson place some **locks** on redis databases, and all application are slow down... All transaction are closed on 3-10 seconds !

On our Redis cluster we have, 1 master, 5 slaves.

This is our using components versions : 
- redis 3.2.11
- redisson 2.11.0

Also, we have test, redisson 2.11.1, we have the same issue.

We have issue with this config :

```
{
   "sentinelServersConfig":{
      "sentinelAddresses":[
         "redis://***.92:26379","redis://***.93:26379","redis://***.94:26379","redis://***.95:26379","redis://***.96:26379","redis://***.97:26379"
      ],
      "clientName":"***",
      "readMode":"MASTER",
      "timeout":"10000",
      "masterName":"***",
      "database":1,
      "password":null
   }
}
```

And we have apply a fix (work around), it's better running, but it's a huge configuration (on system : lot of connection and open file issue)

```
{
   "sentinelServersConfig":{
      "sentinelAddresses":[
         "redis://***.92:26379","redis://***.93:26379","redis://***.94:26379","redis://***.95:26379","redis://***.96:26379","redis://***.97:26379"
      ],
      "clientName":"***",
      "readMode":"MASTER",
      "timeout":"10000",
      "masterName":"***",
      "database":1,
      "password":null,
      "masterConnectionPoolSize":1024,
      "masterConnectionMinimumIdleSize":256,
      "slaveConnectionPoolSize":256,
      "slaveConnectionMinimumIdleSize":24
   }
}
```

Can you help us please ?

Thanks you

**Comment by mrniko** [comment]
Could you check also with 2.11.2 version. I did improvement - `failedAttempts setting should be applied to Slave nodes only` it should help.

> Redisson place some locks on redis databases

Please clarify here, since Redisson doesn't use locks on redis database during failover.
