### ISSUE TITLE
RedLock Java ambiguous implementation

### ISSUE THREAD

**Issue by robcanini** [redisson/redisson#1333]
Hi,
we should implement a distributed lock system for our clustered Spring Boot application.
We have a Redis "cluster" (no cluster mode enabled) with Sentinel.
Now, reading the documentation it seems that RedissonRedLock should be used as locks wrapper class to use lock/unlock api.
It seems that RedissonRedLock should be used with different RedissonInstance e multiple RLock's.
But what kind of lock should we use to implement single distributed lock with single redisson instance per-node?

**Comment by jackygurui** [comment]
RedLock should only be used in Redis running in cluster mode, as per specification.

**Comment by robcanini** [comment]
Ok. What about configuration with cluster mode enabled?
What are the differences between RedissonRedLock and RLock?
