### ISSUE TITLE
Redisson Spring Elasticache Iteamcount issue

### ISSUE THREAD

**Issue by HelloSouvik** [redisson/redisson#1340]
Hi, 

Apologize, if it's not the right forum to post my concern, kindly let me know so i will remove my post or you could redirect me right direction.

we have one doubt regarding how redisson internally storing data on redis cluster (here we are using AWS elastiCache), because the actual number of items is not the same as we have stored using our cache application.

as per logging it's showing proper Set and Get (the data from/to cache server) but the problem is with the actual item count (number of keys) on AWS, it's too lower tan expected,(e.g   even if we are storing 3K data the count is still showing ~20-30).

we are using spring @Cachable annotation on top of redisson to achive the caching , also for cluster redis environment we are using AWS elastiCache . here are more details,

**Spring redisson config:**
  `<redisson:client name="redissonClient">
		<redisson:cluster-servers
			idle-connection-timeout="1000" 
			ping-timeout="1000" 
			connect-timeout="10000"
			timeout="3000" 
			retry-attempts="3" 
			retry-interval="1500"
			reconnection-timeout="3000" 
			failed-attempts="3"
			subscriptions-per-connection="5"
			client-name="none"
			subscription-connection-minimum-idle-size="1"
			subscription-connection-pool-size="50"
			slave-connection-minimum-idle-size="10" 
			slave-connection-pool-size="64"
			master-connection-minimum-idle-size="10" 
			master-connection-pool-size="64"
			read-mode="SLAVE" 
			subscription-mode="SLAVE" 
			scan-interval="1000">
			<redisson:node-address value="server_ip:port" />
			<redisson:node-address value="server_ip:port" />
		</redisson:cluster-servers>
	</redisson:client>`

**Java Code:**
`@Cacheable(value="CustCacheName", keyGenerator="CustCacheKeyGen")
public Object custMethod(String param1, Object obj) {
...
}

cache mnager:
org.redisson.spring.cache.RedissonSpringCacheManager

`
Thanks

**Comment by mrniko** [comment]
> e.g even if we are storing 3K data the count is still showing ~20-30

Hi! Redisson uses 1 Redis hash structure and 3 set structures per Spring cache. This why key number is not get increased.
