### ISSUE TITLE
Get type of a key in Redis

### ISSUE THREAD

**Issue by Flyffies** [redisson/redisson#1341]
Is it possible to execute the "Type" command and determine which datastructure should be used?

If not could this be Implemented?

Ref: https://redis.io/commands/type

**Comment by Flyffies** [comment]
Ok, found it is available in the RedissonKeys class. 
However, I found its missing in the Wiki. It is not listed in the Command Mappings

**Comment by mrniko** [comment]
Thanks for pointing out! Done
