### ISSUE TITLE
RSortedSet tries to compare wrong types

### ISSUE THREAD

**Issue by Flyffies** [redisson/redisson#1342]
I have a sorted set of longs and try to check if a value is contained.

I use the LongCodec and get the following error:
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at java.lang.Long.compareTo(Long.java:54)
	at org.redisson.RedissonSortedSet$NaturalComparator.compare(RedissonSortedSet.java:63)
	at org.redisson.RedissonSortedSet.binarySearch(RedissonSortedSet.java:432)
	at org.redisson.RedissonSortedSet.contains(RedissonSortedSet.java:197)

I debugged it and also saw that a RedissonList is created in the constructor, but the Codec is not supplied to it. May has something to do with it...

The Values in the list are typed as Integer, which they shouldn't be

**Comment by Flyffies** [comment]
And I just noticed the sorted Set is pretty much non functional.
None of the SubSortedSet operations are working, all throw an UnsupportedOperationException.

Taken from RedissonSortedSet.java, from lines 363 to 375:
```
@Override
    public SortedSet<V> subSet(V fromElement, V toElement) {
        throw new UnsupportedOperationException();
//        return new RedissonSubSortedSet<V>(this, connectionManager, fromElement, toElement);
    }

    @Override
    public SortedSet<V> headSet(V toElement) {
        return subSet(null, toElement);
    }

    @Override
    public SortedSet<V> tailSet(V fromElement) {
        return subSet(fromElement, null);
    }
```

**Comment by mrniko** [comment]
I commented out Set.subSet since it was implemented in a wrong way

**Comment by Flyffies** [comment]
Will it be implemented in the (near) Future?

**Comment by Flyffies** [comment]
Can this issue be closed or is it in Development for one of the next releases?

**Comment by mrniko** [comment]
Please create separate issue regarding Set.subSet implementation

**Comment by Flyffies** [comment]
Ok, will do that. Thanks for the response
