### ISSUE TITLE
Redisson Pub/Sub Successful, But RTopic publish method return 0

### ISSUE THREAD

**Issue by sosojustdo** [redisson/redisson#1343]
hi @mrniko 
    
     redisson use sentinel configure for pub/sub successful，but RTopic publish method return 0；current use version:2.7.0，I have try use last stable version for 2.11.3，this problem still reappearing.
     spring.xml:
     `<bean id="redissonConfig" class="com.cloudyoung.common.tools.redis.RedissonConfig" init-method="init">
	    <constructor-arg index="0" name="model" value="sentinel" type="java.lang.String"/>
	    <constructor-arg index="1" name="dataBase" value="${wx.redis.database.index}" type="int"/>
	    <constructor-arg index="2" name="masterName" value="${redis.sentinel.masterName}" type="java.lang.String"/>
	    <constructor-arg index="3" name="password" value="${redis.password}" type="java.lang.String"/>
	    <constructor-arg index="4" name="nodes" type="java.util.Set">
	        <set>
	            <value>${redis.sentinel1}</value>
	            <value>${redis.sentinel2}</value>
	            <value>${redis.sentinel3}</value>
	        </set>
	    </constructor-arg>
	 </bean>
	  
	 <bean id="redissonTemplete" class="com.cloudyoung.common.tools.redis.RedissonTemplete">
	    <property name="redissonConfig" ref="redissonConfig" />  
	 </bean>`

       RedissonConfig.Java code:
       `public class RedissonConfig {
    
    private final Config config = new Config();
    private RedissonClient redisson;
    
    //common configure
    private String model;
    private int dataBase = 0;
    private String password;
    private int idleConnectionTimeout = 10000;//连接空闲超时，单位：毫秒
    private int connectTimeout = 10000;//连接超时，单位：毫秒
    
    //single special configure
    private String singleNodes;//single地址
    private int connectionPoolSize = 64;//连接池大小
    
    //sentinel special configure
    private String masterName;//masterName
    private Set<String> nodes;//sentinel地址集
    
    //master-slave special configure
    private String masterNodes;//主节点地址
    private Set<String> slaveNodes;//从节点地址集
    
    //cluster special configure
    private int scanInterval;//集群状态扫描间隔时间，单位是毫秒
    private Set<String> clusterNodes;//集群节点地址集
    
    //sentinel、 master-slave、 cluster common configure
    private int slaveConnectionMinimumIdleSize = 10;//从节点最小空闲连接数
    private int slaveConnectionPoolSize = 64;//从节点连接池大小
    private int masterConnectionMinimumIdleSize = 10;//主节点最小空闲连接数
    private int masterConnectionPoolSize = 64;//主节点连接池大小
    
    /**
     * single model construct
     * @param model
     * @param dataBase
     * @param password
     * @param singleNodes
     */
    public RedissonConfig(String model, int dataBase, String password, String singleNodes) {
        super();
        this.model = model;
        this.dataBase = dataBase;
        this.password = password;
        this.singleNodes = singleNodes;
    }
    
    /**
     * sentinel model construct
     * @param model
     * @param dataBase
     * @param masterName
     * @param password
     * @param nodes
     */
    public RedissonConfig(String model, int dataBase, String masterName, String password, Set<String> nodes) {
        super();
        this.model = model;
        this.dataBase = dataBase;
        this.masterName = masterName;
        this.password = password;
        this.nodes = nodes;
    }
    
    /**
     * sentinel model construct, include pool and timeout properties
     * @param model
     * @param dataBase
     * @param masterName
     * @param password
     * @param nodes
     * @param slaveConnectionMinimumIdleSize
     * @param slaveConnectionPoolSize
     * @param masterConnectionMinimumIdleSize
     * @param masterConnectionPoolSize
     * @param idleConnectionTimeout
     * @param connectTimeout
     */
    public RedissonConfig(String model, int dataBase, String masterName, String password, Set<String> nodes, 
            int slaveConnectionMinimumIdleSize, int slaveConnectionPoolSize, 
            int masterConnectionMinimumIdleSize, int masterConnectionPoolSize, int idleConnectionTimeout, int connectTimeout) {
        super();
        this.model = model;
        this.dataBase = dataBase;
        this.masterName = masterName;
        this.password = password;
        this.nodes = nodes;
        this.slaveConnectionMinimumIdleSize = slaveConnectionMinimumIdleSize;
        this.slaveConnectionPoolSize = slaveConnectionPoolSize;
        this.masterConnectionMinimumIdleSize = masterConnectionMinimumIdleSize;
        this.masterConnectionPoolSize = masterConnectionPoolSize;
        this.idleConnectionTimeout = idleConnectionTimeout;
        this.connectTimeout = connectTimeout;
    }
    
    /**
     * master-slave construct
     * @param model
     * @param dataBase
     * @param password
     * @param slaveNodes
     * @param masterNodes
     */
    public RedissonConfig(String model, int dataBase, String password, Set<String> slaveNodes, String masterNodes) {
        super();
        this.model = model;
        this.dataBase = dataBase;
        this.password = password;
        this.masterNodes = masterNodes;
        this.slaveNodes = slaveNodes;
    }
    
    /**
     * cluster construct
     * @param model
     * @param password
     * @param scanInterval
     * @param clusterNodes
     */
    public RedissonConfig(String model, String password, int scanInterval, Set<String> clusterNodes) {
        super();
        this.model = model;
        this.password = password;
        this.scanInterval = scanInterval;
        this.clusterNodes = clusterNodes;
    }

    public void init(){
        if(StringUtils.isBlank(model)){
            throw new IllegalArgumentException("RedissonConfig init method params with:[model] can not be empty......!");
        }
        if(RedisArchModelEnum.SINGLE.getModel().equals(model)){
            this.initSingleRedissonClient();
        }else if(RedisArchModelEnum.MASTERSLAVE.getModel().equals(model)){
            this.initMasterSlaveRedissonClient();
        }else if(RedisArchModelEnum.SENTINEL.getModel().equals(model)){
            this.initSentinelRedissonClient();
        }else if(RedisArchModelEnum.CLUSTER.getModel().equals(model)){
            this.initClusterRedissonClient();
        }else{
            throw new IllegalArgumentException("RedissonConfig init method params with:[model] invalid......");
        }
    }
    
    /**
     * Description: init single redisson client
     * @Version1.0 2017年8月24日 上午10:32:39 by 代鹏（daipeng.456@gmail.com）创建
     */
    private void initSingleRedissonClient(){
        if(StringUtils.isBlank(singleNodes)){
            throw new IllegalArgumentException("redis install mode choice single, must be set singleNodes params......!");
        }
        config.useSingleServer()
        .setPassword(StringUtils.isNotBlank(password)?password:null)
        .setAddress(singleNodes)
        .setDatabase(dataBase)
        .setIdleConnectionTimeout(idleConnectionTimeout)
        .setConnectTimeout(connectTimeout)
        .setConnectionPoolSize(connectionPoolSize);
        redisson = Redisson.create(config);
    }
    
    /**
     * Description: init master slave redisson client
     * @Version1.0 2017年8月24日 上午10:33:02 by 代鹏（daipeng.456@gmail.com）创建
     */
    private void initMasterSlaveRedissonClient(){
        if(StringUtils.isBlank(masterNodes)){
            throw new IllegalArgumentException("redis install mode choice master-slave, must be set masterNodes params......!");
        }
        if(null == slaveNodes || slaveNodes.isEmpty()){
            throw new IllegalArgumentException("redis install mode choice master-slave, must be set slaveNodes params......!");
        }
        config.useMasterSlaveServers()
        .setPassword(StringUtils.isNotBlank(password)?password:null)
        .setDatabase(dataBase)
        .setMasterAddress(masterNodes)
        .addSlaveAddress(slaveNodes.toArray(new String[]{}))
        .setIdleConnectionTimeout(idleConnectionTimeout)
        .setConnectTimeout(connectTimeout)
        .setMasterConnectionPoolSize(masterConnectionPoolSize)
        .setSlaveConnectionPoolSize(slaveConnectionPoolSize)
        .setMasterConnectionMinimumIdleSize(masterConnectionMinimumIdleSize)
        .setSlaveConnectionMinimumIdleSize(slaveConnectionMinimumIdleSize);
        redisson = Redisson.create(config);
    }
    
    /**
     * Description: init sentinel redisson client
     * @Version1.0 2017年8月24日 上午10:33:15 by 代鹏（daipeng.456@gmail.com）创建
     */
    private void initSentinelRedissonClient(){
        if(null == nodes || nodes.isEmpty()){
            throw new IllegalArgumentException("redis install mode choice sentinel, must be set sentinelAddress params......!");
        }
        if(StringUtils.isBlank(masterName)){
            throw new IllegalArgumentException("redis install mode choice sentinel, must be set masterName params......!");
        }
        
        config.useSentinelServers()
        .setMasterName(masterName)
        .setPassword(StringUtils.isNotBlank(password)?password:null)
        .setDatabase(dataBase)
        .setSlaveConnectionMinimumIdleSize(slaveConnectionMinimumIdleSize)
        .setSlaveConnectionPoolSize(slaveConnectionPoolSize)
        .setMasterConnectionMinimumIdleSize(masterConnectionMinimumIdleSize)
        .setMasterConnectionPoolSize(masterConnectionPoolSize)
        .setIdleConnectionTimeout(idleConnectionTimeout)
        .setConnectTimeout(connectTimeout)
        .addSentinelAddress(nodes.toArray(new String[]{}));
        redisson = Redisson.create(config);
    }
    
    /**
     * Description: init cluster redisson client
     * @Version1.0 2017年8月24日 上午10:33:30 by 代鹏（daipeng.456@gmail.com）创建
     */
    private void initClusterRedissonClient(){
        if(null == clusterNodes || clusterNodes.isEmpty()){
            throw new IllegalArgumentException("redis install mode choice cluster, must be set clusterNodes params......!");
        }
        config.useClusterServers()
        .setScanInterval(scanInterval)
        .addNodeAddress(clusterNodes.toArray(new String[]{}))
        .setPassword(password)
        .setSlaveConnectionMinimumIdleSize(slaveConnectionMinimumIdleSize)
        .setSlaveConnectionPoolSize(slaveConnectionPoolSize)
        .setMasterConnectionMinimumIdleSize(masterConnectionMinimumIdleSize)
        .setMasterConnectionPoolSize(masterConnectionPoolSize)
        .setIdleConnectionTimeout(idleConnectionTimeout)
        .setConnectTimeout(connectTimeout);
        redisson = Redisson.create(config);
    }
    
    public RedissonClient getRedissonInstance(){
        return redisson;
    }
    
     }`

         RedissonTemplete.java code:
        `public class RedissonTemplete<V> {

    private RedissonConfig redissonConfig;

    private RedissonClient redisson;

    public RedissonTemplete<V> setRedissonConfig(RedissonConfig config) {
        this.redissonConfig = config;
        this.redisson = redissonConfig.getRedissonInstance();
        return this;
    }
    
    /**
     * Description: 获取RTopic
     * @Version1.0 2018年3月8日 下午5:28:37 by 代鹏（daipeng.456@gmail.com）创建
     * @param objectName
     * @return
     */
    private <M> RTopic<M> getRTopic(String objectName) {
        return redisson.getTopic(objectName);
    }
    
    // -------------------------Pub/Sub Start-----------------------//
    public <M> int subscribe (String objectName, MessageListener<M> msgListener) {
        RTopic<M> rTopic = this.getRTopic(objectName);
        return rTopic.addListener(msgListener);
    }
    
    public <M> void unSubscribe (String objectName, int listenerId) {
        RTopic<M> rTopic = this.getRTopic(objectName);
        rTopic.removeListener(listenerId);
    }
    
    public <M> long publish(String objectName, M msg) {
        RTopic<M> rTopic = this.getRTopic(objectName);
        return rTopic.publish(msg);
    }
    // -------------------------Pub/Sub End-------------------------//    
     }`

**Comment by mrniko** [comment]
Try 2.11.3 version with subscriptionMode = MASTER setting

**Comment by sosojustdo** [comment]
@mrniko  that ok, thank you very much..
