### ISSUE TITLE
redisson jcache.getAll(Set<T>) causes io.netty.util.IllegalReferenceCountException: refCnt: 0

### ISSUE THREAD

**Issue by jeff-johnston** [redisson/redisson#1349]
<dependency>
		    <groupId>org.redisson</groupId>
		    <artifactId>redisson</artifactId>
		    <version>3.6.3</version>
		</dependency>

redisson-jcache.json
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":"secret",
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://127.0.0.1:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoring":false,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
         "class":"org.redisson.codec.JsonJacksonCodec"
      },
   "transportMode":"NIO"
}

I have also tried this with multiple serialization codecs and the result is always the same. We are attempting to convert our EHCache JCache implementation to Redis. Calling JCache.get with a key works but JCache.getAll with a set of keys fails every time. This is essential to a smooth transition for us as we don't want to redesign our application at the same time we are switching technologies. We would like to avoid using native libraries if at all possible.

io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1347)
	at io.netty.buffer.AbstractByteBuf.getInt(AbstractByteBuf.java:415)
	at io.netty.buffer.ByteBufUtil.hashCode(ByteBufUtil.java:162)
	at io.netty.buffer.AbstractByteBuf.hashCode(AbstractByteBuf.java:1306)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at org.redisson.jcache.JCache.getAll(JCache.java:642)
	
Thank you, any help would be appreciated.

**Comment by mrniko** [comment]
Fixed! Thanks for report!
