### ISSUE TITLE
two thread get  the same   RedissonMultiLock  ?

### ISSUE THREAD

**Issue by athinboy** [redisson/redisson#1356]
Is my code has any problem?
there are two different  thread get the same  multilock. 
thanks!

public Lock tryMultiLock(List<String> names, Long waittime, Long expiretime, TimeUnit timeUnit) {
        if (names == null || names.size() == 0) {
            throw new IllegalArgumentException("names is illegal!");
        }
        waittime = Math.max(waittime, this.miniWaitSecond);
        RLock[] rLocksarr = new RLock[names.size()];
        try {
            for (int i = 0; i < names.size(); i++) {
                rLocksarr[i] = this.redisson.getLock(names.get(i));
            }
            RedissonMultiLock lock = new RedissonMultiLock(rLocksarr);
            if (lock.tryLock(waittime, timeUnit.toSeconds(expiretime), TimeUnit.SECONDS) == false) {
                return null;
            }
            for (int i = 0; i < rLocksarr.length; i++) {
                if (false == rLocksarr[i].isHeldByCurrentThread()) {
                    return null;
                }
            }
            return lock;
        } catch (Throwable ex) {
            this.logger.error("获取联锁失败", ex);
            return null;
        }
    }

**Comment by jackygurui** [comment]
Not able to reproduce the problem based on the code you provided.

**Comment by young001** [comment]
![image](https://user-images.githubusercontent.com/391571/37957728-4500b562-31e1-11e8-9da1-ed60e5fe5ec1.png)

![image](https://user-images.githubusercontent.com/391571/37957621-020377e0-31e1-11e8-8f75-37b4da4cee40.png)

this two threads with the same threadId both will get the lock
