### ISSUE TITLE
method putAll throws map value can't be null

### ISSUE THREAD

**Issue by gstripe** [redisson/redisson#1357]
请问redisson-3.4.4开始到最新的版本
putAll方法里面调用的putAllOperationAsync方法，里面会对传入的map的value值进行非空检查，
以致于在==null的时候抛出map value can't be null

我的测试代码
RMap<String, Object> rMap = redissonClient.getMap("test-365-hash");
Map<String, Object> map = new HashMap();
map.put("aaa-1", "AAA 1");
map.put("aaa-2", null);
rMap.putAll(map);

使用在redisson-3.4.4 + 将会抛出异常

如果使用redisson-3.2.0这样的包里面没有对 value进行非空检测
那么测试代码是可以正常执行的

请教一下各位前辈，如果我想用新的版本，也想正常执行上面的测试代码，该如何做？

**Comment by jackygurui** [comment]
RMap继承了ConcurrentHashMap，而ConcurrentHashMap的要求就是key和value都不能是null。所以为了不破坏兼容性，Redisson进行了这样的修改。
