### ISSUE TITLE
Is this a bug

### ISSUE THREAD

**Issue by smartbruce** [redisson/redisson#1363]
RedissonRemoteService.java

protected RFuture<Boolean> removeAsync(String requestQueueName, RequestId taskId) {
    return commandExecutor.evalWriteAsync(name, LongCodec.INSTANCE, RedisCommands.EVAL_BOOLEAN,
            "redis.call('lrem', KEYS[1], 1, ARGV[1]); "
            + "redis.call('hset', KEYS[2], ARGV[1]);"   --may be "hdel"
            + "return 1;",
            Arrays.<Object>asList(requestQueueName, requestQueueName + ":tasks"),
            taskId.toString());
}

**Comment by mrniko** [comment]
It's a bug thanks for pointing out!

**Comment by mrniko** [comment]
Fixed!
