### ISSUE TITLE
Consecutive "Subscribe timeout" for topics utilizing same AsyncSemaphore lock

### ISSUE THREAD

**Issue by Yipei** [redisson/redisson#1364]
Hi there,

Thanks for the quick fix on the ticket #1268 . We tested it and the block on RedissonTopic.removeAllListeners no longer happened. 

However, we started see another issue: After a fairly long time running with the new code, subscriptions( by calling RedissonTopic.addListener) to the topics which are assigned to the same AsyncSemaphore lock from the method MasterSlaveConnectionManager.getSemaphore() are all encountering the same timeout error like "Subscribe timeout 9500ms". It's very consistent. But for other subscription calls to other topics which assigned to different AsyncSemaphore locks, everything works fine.

It's possibly related to #1268. Please help advice how to tune and debug this problem.

Thanks

**Comment by mrniko** [comment]
Could you try 2.11.4 version? I fixed some pubsub related bug and refactored it.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1717
