### ISSUE TITLE
Redisson connected to sentinels works fine - But throws the following error

### ISSUE THREAD

**Issue by auror** [redisson/redisson#1366]
`[ERROR] MSG - o.r.c.SentinelConnectionManager Can't update cluster state`

Hi,

I've RedissonClient connected to Redis Sentinels(Redis 4). Redis commands work fine, but throws the above error. Couldn't figure out the cause of the issue

**Comment by mrniko** [comment]
It seems some of sentinel servers are offline. Right, an error shouldn't appear if Redisson successfully got the information at least from single sentinel server.

**Comment by mrniko** [comment]
Fixed
