### ISSUE TITLE
RedissonScoredSet - contains/remove method - equals and hashcode?

### ISSUE THREAD

**Issue by welovelain** [redisson/redisson#1369]
How is "contains" method (remove, etc) is implemented? I overrided in my object methods "equals" and "hashcode", simplified, they look like this:

```
class Test 
private String id;
private String value;

boolean equals(Object o) { return this.id = o.id}
int hashcode = Objects.hash(super.hashCode(), id);
```

the point is two classes are equal when their id is equal.
But classes with different values (and same id) are not considered to be equal, when I use methods "contains" or "remove" in RScoredSet.
Is it the desired behavior?

**Comment by mrniko** [comment]
`equals` and `hashcode` are not taken into account, only serialized form of inserted/removed object.

**Comment by welovelain** [comment]
I see, thanks.
Though, I think it breaks the interface contracts.
