### ISSUE TITLE
Spring Data integration

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#1373]

**Comment by fl061157** [comment]
Can't write command batch to channel: [id: 0x61e3267f, L:/xxxxxxxx:xxx ! R:xxxxxx/xxxxxx:6379]. I found the tcp.socket not exists。 why we not close it  in  CommandBatchService.checkWriteFuture

**Comment by jackygurui** [comment]
A new milestone for Redisson. Well done, @mrniko

**Comment by mrniko** [comment]
@jackygurui 
Thank you! But it's not finished yet.

**Comment by mrniko** [comment]
Done

**Comment by MikeChen116** [comment]
Is it finished? When does it officially release?

**Comment by mrniko** [comment]
At early next month

**Comment by MikeChen116** [comment]
Well done.
