### ISSUE TITLE
RSet returned by RSetMultimap.get() does not update multimap correctly.

### ISSUE THREAD

**Issue by rwatler** [redisson/redisson#1375]
RSets returned by get() cannot be used to populate RSetMultimap. Multimap key and size information is not managed properly despite get() returning populated sets. See this example:

        RedissonClient redisson = Redisson.create();

        // multimap populated via put() works
        RSetMultimap<String, Integer> multimap0 = redisson.getSetMultimap("myMultimap0");
        multimap0.put("1", 1);
        multimap0.put("1", 2);
        multimap0.put("1", 3);
        multimap0.put("2", 5);
        multimap0.put("2", 6);
        multimap0.put("4", 7);

        logger.error(">>>>>>>>>>>>>> multimap0 - keyset: "+multimap0.keySet());
        logger.error(">>>>>>>>>>>>>> multimap0 - keysize: "+multimap0.keySize());
        logger.error(">>>>>>>>>>>>>> multimap0 - 1: "+multimap0.get("1"));
        logger.error(">>>>>>>>>>>>>> multimap0 - 2: "+multimap0.get("2"));
        logger.error(">>>>>>>>>>>>>> multimap0 - 4: "+multimap0.get("4"));

        // multimap populated via get() does not work
        RSetMultimap<String, Integer> multimap1 = redisson.getSetMultimap("myMultimap1");
        Set<Integer> one = multimap1.get("1");
        Set<Integer> two = multimap1.get("2");
        Set<Integer> four = multimap1.get("4");
        one.add(1);
        one.add(2);
        one.add(3);
        two.add(5);
        two.add(6);
        four.add(7);

        logger.error(">>>>>>>>>>>>>> multimap1 - keyset: "+multimap1.keySet());
        logger.error(">>>>>>>>>>>>>> multimap1 - keysize: "+multimap1.keySize());
        logger.error(">>>>>>>>>>>>>> multimap1 - 1: "+multimap1.get("1"));
        logger.error(">>>>>>>>>>>>>> multimap1 - 2: "+multimap1.get("2"));
        logger.error(">>>>>>>>>>>>>> multimap1 - 4: "+multimap1.get("4"));

        multimap0.delete();
        multimap1.delete();

        redisson.shutdown();

This generates the following output:

        [main] ERROR - >>>>>>>>>>>>>> multimap0 - keyset: [1, 2, 4]
        [main] ERROR - >>>>>>>>>>>>>> multimap0 - keysize: 3
        [main] ERROR - >>>>>>>>>>>>>> multimap0 - 1: [1, 2, 3]
        [main] ERROR - >>>>>>>>>>>>>> multimap0 - 2: [5, 6]
        [main] ERROR - >>>>>>>>>>>>>> multimap0 - 4: [7]
        [main] ERROR - >>>>>>>>>>>>>> multimap1 - keyset: []
        [main] ERROR - >>>>>>>>>>>>>> multimap1 - keysize: 0
        [main] ERROR - >>>>>>>>>>>>>> multimap1 - 1: [1, 2, 3]
        [main] ERROR - >>>>>>>>>>>>>> multimap1 - 2: [5, 6]
        [main] ERROR - >>>>>>>>>>>>>> multimap1 - 4: [7]

Here, multimap1 keyset and keysize are not initialized. Javadoc for the get() method claims:

"Changes to the returned collection will update the underlying multimap, and vice versa."

**Comment by mrniko** [comment]
Fixed! Thanks for report
