### ISSUE TITLE
Why no RMapCacheAsync::fastReplace?

### ISSUE THREAD

**Issue by mcacker** [redisson/redisson#1379]
I am trying to optimize my Redisson throughput, and to do so, am using the MapCache fast methods, where no result is returned for a put or remove, but there is no fastReplace.  Why so?

I created my own one by subclassing RedissonMapCache and adding a method there, and that works fine.  However, now I want to use pipelining, but it will not work with the Batch classes without further modification.

I do see that there is a replaceOperationAsync, which returns a Boolean, so keeps the response message to a minimum, but that is offset by essentially doubling the size of the request by including the value to be replaced, so that is less than ideal for my purposes.

**Comment by mrniko** [comment]
Done

**Comment by mcacker** [comment]
Great, thanks.  Any idea when this will be included in a release?

**Comment by mrniko** [comment]
It's included already

**Comment by mcacker** [comment]
FYI, I updated my pom to specify the latest maven release in maven central - 3.6.5, but it doesn't appear to be in that release.  Should I look elsewhere?

**Comment by mrniko** [comment]
Sorry, this feature is for upcoming 3.7.0 release
