### ISSUE TITLE
Redis server response timeout (3000 ms)

### ISSUE THREAD

**Issue by hulvyou** [redisson/redisson#1382]
version:3.6.5
config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379")
                .setPassword("123456)
                .setDatabase(0)
                .setTimeout(3000)
                .setConnectionPoolSize(64)
                .setConnectionMinimumIdleSize(10)
ERROR
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, lottery_lucky_award_lock, 30000, 74e30927-d36d-40ff-a42e-675f4623cf47:31] channel: [id: 0xce29a7a8, L:/192.168.50.76:52620 - R:/127.0.0.1:6379]
十分钟一次的定时任务只有第一次不会报这个错误执行成功（第一次是程序启动就执行）十分钟之后再次执行就会出现这个错误
期间redis没有访问了量无任务！！！

**Comment by jackygurui** [comment]
Please see [FAQ](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it) regarding RedisTimeoutException

**Comment by sosoeo** [comment]
我遇到了同样的问题，尝试FAQ中的方法也没有解决。

**Comment by rongbo-j** [comment]
我也遇到这个问题了   一直报超时，改成jedis没有问题问题 应该不是redis服务器的问题

**Comment by jackygurui** [comment]
@rongbo-j 请看[FAQ](
https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it)
