### ISSUE TITLE
RedissonSortedSet does not implement ZRANGE commands

### ISSUE THREAD

**Issue by Flyffies** [redisson/redisson#1385]
RedissonSortedSet does throw an UnsupportedOperationException on a call to the headSet, tailSet and subSet methods.

```
    @Override
    public SortedSet<V> subSet(V fromElement, V toElement) {
        throw new UnsupportedOperationException();
//        return new RedissonSubSortedSet<V>(this, connectionManager, fromElement, toElement);
    }

    @Override
    public SortedSet<V> headSet(V toElement) {
        return subSet(null, toElement);
    }

    @Override
    public SortedSet<V> tailSet(V fromElement) {
        return subSet(fromElement, null);
    }
```

They could return the response of the ZRANGE or the ZRANGEBY redis commands.

https://redis.io/commands/zrange

**Comment by mrniko** [comment]
ZRANGE command couldn't be used with Redis list structure used by RedissonSortedSet.

**Comment by Flyffies** [comment]
Why does it even use a list and not the SortedSet structure provided by redis?

**Comment by mrniko** [comment]
SortedSet stores elements using Comparator object and not they state. List structure used to keep elements in insertion order.

**Comment by Flyffies** [comment]
But isn't the name and Mapping in the Command overview a bit misleading? 

I thought the RSortedSet would use the the redis SortedSet datastructure and not a List implementation.

That threw of my scripts and I had to write simple Scripts that use the ZADD, etc. commands to use the ZRANGEBYSCORE command in another script.

**Comment by mrniko** [comment]
I think you confused it with RScoredSortedSet, didn't you?

**Comment by Flyffies** [comment]
Ohhhh, yea, sorry for wasting your time... I, somehow, completly oversaw it...

Thanks, I'll look closer next time
