### ISSUE TITLE
RScheduledExecutorService使用中发现的问题

### ISSUE THREAD

**Issue by justlive1** [redisson/redisson#1387]
当没有registerWorkers的时候，调用countActiveWorkers方法，程序阻塞在semaphore.tryAcquire(subscribers, 10, TimeUnit.MINUTES);

**Comment by justlive1** [comment]
由于计算count是基于订阅模式下的publish触发增加各自worker数到workersCounterAtomicLong
再去获取semaphore，最后返回workersCounterAtomicLong的数值
但是没有worker的时候，publish返回0， 触发不了事件，导致semaphore阻塞
望修复

**Comment by justlive1** [comment]
RSemaphore阻塞的情况是 RSemaphore还未创建，然后调用tryAcquire(0, 10, TimeUnit.MINUTES);
期望应该是立刻返回的

**Comment by mrniko** [comment]
Fixed
