### ISSUE TITLE
Frequent timeout with RedisLabs multi-proxy setup

### ISSUE THREAD

**Issue by gujason721** [redisson/redisson#1388]
In the latest Redislabs cluster, the user can enable multiple proxies, and the DNS query of the cluster would return different IP addresses for load balancing.

From Redisson side, we observe Redisson would have very frequent timeout with DNS monitoring enabled. Seems like for each DNS lookup, if IP address changes, Redisson would try to reconnect with this new IP and lead to unstable system.

Is it possible for Redisson to check the cluster health before trying to connect to the new IP address?

**Comment by mrniko** [comment]
Could you share Redisson configuration?

**Comment by gujason721** [comment]
Please see the Redission conf below.

   "singleServerConfig":{

      "idleConnectionTimeout":10000,

      "pingTimeout":1000,

      "connectTimeout":10000,

      "timeout":3000,

      "retryAttempts":3,

      "retryInterval":1500,

      "reconnectionTimeout":3000,

      "failedAttempts":3,

      "password":xxxxx,

      "subscriptionsPerConnection":5,

      "clientName":null,

      "address": "redis://clustername",

      "subscriptionConnectionMinimumIdleSize":1,

      "subscriptionConnectionPoolSize":50,

      "connectionMinimumIdleSize":32,

      "connectionPoolSize":64,

      "database":0,

      "dnsMonitoring":true,

      "dnsMonitoringInterval":5000

   },

   "threads":0,

   "nettyThreads":0,

   "codec":null,

   "transportMode":"NIO"

}

**Comment by mrniko** [comment]
I'm going to implement a new `proxyServers` mode to support this feature.

**Comment by mrniko** [comment]
Done. Please follow this [link](https://github.com/redisson/redisson/wiki/2.-Configuration#29-proxy-mode) for documentation.
