### ISSUE TITLE
RMI Garbage Collection in Redis

### ISSUE THREAD

**Issue by bhoover10001** [redisson/redisson#1393]
Each of the RMIs seems to be put in a namespace under {redisson_rs}  How are RMIs being garbage collected or do we need to run another process to do our own garbage collection for RMIs?

We are using 3.6.5 on a Redis cluster at Amazon.  

What we appear to be seeing is that the RMI jobs are never purged from the DB.  Most of our RMIs are set and forget.

Our code generally looks something like this:

The server code

       import java.util.concurrent.ExecutorService;
       import java.util.concurrent.Executors;
       import org.redisson.api.RRemoteService;
       import org.redisson.api.RedissonClient;

       int viewJobSize = rmiConfig.getForecastJobPoolSize() ;
       viewJobSize = validatePoolSize("viewJob", viewJobSize, RmiJobConfiguration.MIN_VIEW_JOB_POOL_SIZE );

       ExecutorService forecastExecutor = Executors.newFixedThreadPool(forecastSize);

       remoteService.register(ForecastServices.class, injector.getInstance(ForecastServicesImpl.class), NUM_FORECAST_EXECUTORS, forecastExecutor);

The client code

       import org.redisson.api.RedissonClient;
       import org.redisson.api.RemoteInvocationOptions;
       RedissonClient client ;

       private static final RemoteInvocationOptions triggerForecastBatchJob =
                     RemoteInvocationOptions.defaults().noAck().noResult();
       
       private void submitJob(List<Integer> gwList, String jobId) {
              client.getRemoteService().get(ForecastServicesAsync.class, triggerForecastBatchJob)
                     .triggerDailyForecastBatchJob(gwList, jobId);
              
       }

What we are seeing 

![rmi](https://user-images.githubusercontent.com/1531114/38838481-1eefa568-418b-11e8-8f13-ee814657e814.jpg)

The specific key/value pairs for the RMI seem to grow unbounded, until Redis runs out of memory to process more jobs.  We have been looking for someway to delete the job once it has been completed, but are not sure how to do this.

**Comment by mrniko** [comment]
invocations on proxy object of RemoteService was not thread safe https://github.com/redisson/redisson/issues/1433 and could cause your issue due to incorrect response handling on Redisson side. Please try 3.7.0 version

**Comment by mrniko** [comment]
I confirm, it's a bug

**Comment by mrniko** [comment]
Fixed
