### ISSUE TITLE
java.lang.NoSuchMethodError java/lang/CharSequence

### ISSUE THREAD

**Issue by Tristiisch74** [redisson/redisson#1396]
> Im using Redisson 3.6.5 and Java JDK 8
`public class RedisAccess {

	public static RedisAccess INSTANCE;
	RedissonClient redissonClient;

	public RedisAccess(final RedisCredentials redisCredentials) {
		INSTANCE = this;
		this.redissonClient = this.initRedisson(redisCredentials);
	}

	public RedissonClient getRedissonClient() {
		return this.redissonClient;
	}

	public static void init() {
		new RedisAccess(new RedisCredentials("127.0.0.1", "SBJ2OL9rhXNgDRA1Haw47uSY4HLPvcJh", 6379));
	}

	public static void init(final String serverName) {
		new RedisAccess(new RedisCredentials("127.0.0.1", "SBJ2OL9rhXNgDRA1Haw47uSY4HLPvcJh", 6379, serverName));
	}

	public static void close() {
		RedisAccess.INSTANCE.getRedissonClient().shutdown();
	}

	public RedissonClient initRedisson(final RedisCredentials redisCredentials) {
		final Config config = new Config();

		config.setCodec(new JsonJacksonCodec());
		config.setUseLinuxNativeEpoll(true);
		config.setThreads(8 * 2);
		config.setNettyThreads(8 * 2);
		config.useSingleServer()
		.setAddress(redisCredentials.toRedisURL())
		.setPassword(redisCredentials.getPassword())
		.setDatabase(1)
		.setClientName(redisCredentials.getClientName());
		return Redisson.create(config);

	}
}`

Error:
[https://hastebin.com/ecedabopap.vbs](https://hastebin.com/ecedabopap.vbs)

**Comment by mrniko** [comment]
Please unsure that all netty libs in your classpath have same version

**Comment by jackygurui** [comment]
You may have a netty version conflict with other dependencies.

**Comment by Tristiisch74** [comment]
What is the version of Netty in redisson ?

**Comment by Tristiisch74** [comment]
If someone have the same issue, u need to use the same version of dependance of Redisson of Spigot server.
