### ISSUE TITLE
ClassCastException with StringCodec while testing non sticky session on Tomcat

### ISSUE THREAD

**Issue by gary-chong** [redisson/redisson#1398]
I am getting this error on Tomcat 7 and JDK7:

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	org.redisson.tomcat.RedissonSession.load(RedissonSession.java:192)
	org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:139)
	org.apache.catalina.connector.Request.doGetSession(Request.java:3048)
	org.apache.catalina.connector.Request.getSessionInternal(Request.java:2662)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:431)
	org.apache.catalina.valves.CometConnectionManagerValve.invoke(CometConnectionManagerValve.java:184)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2555)
	org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2544)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

Below is my redisson.conf setting:
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://redis-server:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoring":false,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.client.codec.StringCodec"
   },
   "transportMode":"NIO"
}

Can anyone point out what was the issue?

**Comment by jackygurui** [comment]
`org.redisson.client.codec.StringCodec` as its name suggests, can only handle Strings, not other types of objects. You should use other codecs instead, such as JacksonCodec or FstCodec, for instance.

**Comment by gary-chong** [comment]
@jackygurui The problem is that when I used the default JacksonCodec, the application can't even progress  to the landing page after the authentication. I will post the stack trace later.

**Comment by gary-chong** [comment]
@jackygurui Here is the stack trace if I switched to use JsonJacksonCodec:

com.fasterxml.jackson.core.JsonGenerationException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?)
	com.fasterxml.jackson.databind.ser.impl.FailingSerializer.serialize(FailingSerializer.java:35)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeTypedFields(MapSerializer.java:855)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:575)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:553)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:31)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeTypedFields(MapSerializer.java:857)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:575)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:553)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:31)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:674)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:677)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:568)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeTypedFields(MapSerializer.java:857)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:575)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:553)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:31)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:674)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:677)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:568)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeTypedFields(MapSerializer.java:857)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:575)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:553)
	com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithType(MapSerializer.java:31)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:674)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:677)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:568)
	com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:151)
	com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:25)
	com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serializeWithType(AsArraySerializerBase.java:267)
	com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:674)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:677)
	com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:568)
	com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3631)
	com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2964)
	org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:77)
	org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:236)
	org.redisson.RedissonMap.fastPutOperationAsync(RedissonMap.java:876)
	org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:861)
	org.redisson.RedissonMap.fastPut(RedissonMap.java:881)
	org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:156)
	org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1404)
	org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:156)
	org.springframework.webflow.context.servlet.HttpSessionMap.setAttribute(HttpSessionMap.java:79)
	org.springframework.binding.collection.StringKeyedMapAdapter.put(StringKeyedMapAdapter.java:82)
	org.springframework.webflow.core.collection.LocalAttributeMap.put(LocalAttributeMap.java:225)
	org.springframework.webflow.conversation.impl.ContainedConversation.unlock(ContainedConversation.java:109)
	org.springframework.webflow.execution.repository.support.ConversationBackedFlowExecutionLock.unlock(ConversationBackedFlowExecutionLock.java:55)
	org.springframework.webflow.executor.FlowExecutorImpl.launchExecution(FlowExecutorImpl.java:147)
	org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:193)
	org.springframework.webflow.mvc.servlet.FlowController.handleRequest(FlowController.java:174)
	org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)

**Comment by mrniko** [comment]
@gary-chong could you create a separate issue regarding that?
