### ISSUE TITLE
setDatabase is no use

### ISSUE THREAD

**Issue by geriyoga** [redisson/redisson#1399]
" this.delegate.getConfig().useSentinelServers().setDatabase(dbindex);"

but no use
when getKeys ,it return all keys ,but not the key of one db

**Comment by mrniko** [comment]
Do you try to change database for already initialized Redisson instance?

**Comment by geriyoga** [comment]
yes, is wrong? ...but is my web app,I has the requirement,that i change the database for different business logic

**Comment by geriyoga** [comment]
@mrniko yes, is wrong? ...but is my web app,I has the requirement,that i change the database for different business logic

**Comment by geriyoga** [comment]
@mrniko yes, is wrong? ...but is my web app,I has the requirement,that i change the database for different business logic,what should i do?

**Comment by mrniko** [comment]
Redisson Config object is immutable. I suggest you to create Redisson instance per database and shared eventLoopGroup to avoid many threads.

**Comment by geriyoga** [comment]
@mrniko oh,please tell me,how to shared eventLoopGroup,i am not quite clear about shared eventLoopGroup

**Comment by mrniko** [comment]
It's easy:
```java
// for NIO transportMode
EventLoopGroup eventLoopGroup = new NioEventLoopGroup();
```

**Comment by geriyoga** [comment]
there is a problem, i initialized Redisson is Spring.xml ,how can i initialized Redisson in my code dynamic?

**Comment by geriyoga** [comment]
<redisson:client id="sentinel">
        <redisson:sentinel-servers master-name="mymaster" password="***">
            <redisson:sentinel-address value="redis://***:**" />
            <redisson:sentinel-address value="redis://***:**" />
            <redisson:sentinel-address value="redis://***:**" />
        </redisson:sentinel-servers>
    </redisson:client>

in the redission code ,where can i set the scope of spring ?

**Comment by jackygurui** [comment]
Like this:
https://github.com/redisson/redisson/blob/master/redisson/src/test/resources/org/redisson/spring/support/namespace_wiki_single.xml#L18

and this:
https://github.com/redisson/redisson/blob/master/redisson/src/test/resources/org/redisson/spring/support/namespace.xml

**Comment by geriyoga** [comment]
@jackygurui oh,let me try ,thank you

**Comment by geriyoga** [comment]
@jackygurui is this case,need all the redission client parameter?
id="redisson"
        name="redisson1,redisson2"
        threads="0"
        netty-threads="0"
        codec-ref="myCodec" 
        use-linux-native-epoll="false"
        redisson-reference-enabled="true"
        codec-provider-ref="myCodecProvider"
        resolver-provider-ref="myResolverProvider"
        executor-ref="myExecutor"
        event-loop-group-ref="myEventLoopGroup"

Or I just want some of them.
