### ISSUE TITLE
文档和示例中redis的address格式错误,建议更新文档和注释.

### ISSUE THREAD

**Issue by springrain** [redisson/redisson#1403]
使用javaConfig方式声明redissonClinet实例,环境是JDK8,SpringBoot2.0.1,redisson3.6.4
redisson代码注释中对 redis Server address的说明是
Use follow format -- host:port
使用127.0.0.1:6379会出现Illegal character in scheme name at index 0 错误,
使用 redis://127.0.0.1:6379可以正常,建议更新文档和注释.

**Comment by kingtiger2** [comment]
是的,这是大坑..用spring data redis的sentinel-address 不兼容...2.8.7版本都是好的,为什么后来的版本弄成这样????????????????????????
