### ISSUE TITLE
怎么设置全局的ttl和maxIdleTime啊?避免忘记清理缓存造成缓存一直存在

### ISSUE THREAD

**Issue by springrain** [redisson/redisson#1404]
org.redisson.spring.cache.CacheConfig 默认的ttl和maxIdleTime都是0,就是永不过期,怎么设置一个全局的默认值啊?避免忘记清理缓存造成缓存一直存在

**Comment by jackygurui** [comment]
看这里https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/spring/cache/RedissonSpringCacheShortTTLTest.java#L104

**Comment by mengsm** [comment]
@jackygurui redisson 设置key的ttl  为什么总是-1   过期机制是如何触发的
