### ISSUE TITLE
getKeysByPattern is returning less number of keys in version 3.6.1

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#1406]
Hi,

We were using redisson version 3.5.2 and getKeysByPattern was returning all the keys matched for a particular pattern. When we upgraded to 3.6.1, the method seems to be broken and returning less number of keys than the keys actual present in redis.

**Comment by mrniko** [comment]
Hi, 

Which Redis setup do you use? Any test case to reproduce this problem?

**Comment by Himanshu4** [comment]
We are using ELasticache setup with 1 master and 3 slaves.

**Comment by mrniko** [comment]
It hasn't been changed since 3.5.2 version.

**Comment by Himanshu4** [comment]
There must be some change in related/dependent code as we have reproduced the issue on 3.6.1 version. We have also tested multiple times that the issue is not coming with version 3.5.2.

**Comment by mrniko** [comment]
It would be help if you provide any code to reproduce this.

**Comment by mrniko** [comment]
Did you try latest 3.6.5 version? I did improvement to https://github.com/redisson/redisson/commit/5588748cde615959d944cc5b195e84b0225a2c33 used by getKeysByPattern methon in 3.6.2 version.

**Comment by Himanshu4** [comment]
Here is the sample code. 

chunkSize is 200

`      Long noOfKeysDeleted = 0L;
        Iterable<String> keysIterator = redissonClient.getKeys().getKeysByPattern(pattern, chunkSize);;
        Set<String> keys = new HashSet<>();
        for (String key : keysIterator) {
            keys.add(key);
            //Delete keys in chunks of k
            if (keys.size() % chunkSize == 0) {
                noOfKeysDeleted += redissonClient.getKeys().delete(keys.toArray(new String[keys.size()]));
                keys.clear();
            }
        }
        //Delete remaining keys
        if (!CollectionUtils.isEmpty(keys)) {
            noOfKeysDeleted += redissonClient.getKeys().delete(keys.toArray(new String[keys.size()]));
        }
`

**Comment by mrniko** [comment]
Redis version?

**Comment by Himanshu4** [comment]
Redis version is 3.2.4

**Comment by mrniko** [comment]
Did you try to use `deleteByPattern` method? Your example does the same

**Comment by mrniko** [comment]
Fixed
