### ISSUE TITLE
Publish a request id in a redis event

### ISSUE THREAD

**Issue by mcacker** [redisson/redisson#1407]
This is a feature request.

It's not always easy to associate a redis event with a specific request, e.g., when you don't know whether a put would result in a CREATED or UPDATED event.  It would be nice in a request to optionally provide a request id, which would then included in the published redis event to help with this problem.

thanks, Mitchell

**Comment by mrniko** [comment]
Do you mean these events https://redis.io/topics/notifications ? If so I'm afraid I can't do anything here. Since they are generated on Redis side.

**Comment by mcacker** [comment]
Ok, fair enough, that makes sense.
