### ISSUE TITLE
Why RBitSet.set(...) does not return anything?

### ISSUE THREAD

**Issue by chimmi** [redisson/redisson#1410]
https://redis.io/commands/setbit states that:

> Return value
Integer reply: the original bit value stored at offset.

But _RBitSet.set(...)_ methods are of type _void_ despite their async counterparts having return type of _RFuture\<Boolean\>_.

**Comment by chimmi** [comment]
Am I missing something or this fix was never released?

**Comment by mrniko** [comment]
It was released. Here is the method: https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RBitSet.java#L210

**Comment by chimmi** [comment]
Oh I see, I though you fixed the existing method. This is kinda strange though considering that the point was to make `set` aligned with its async version and underlying Redis command. Also, this:

    private boolean setStatus(RedissonClient client, String key, long offset, boolean status) {
        return client.getBitSet(key).set(offset);
    }

would be much cleaner than:

    private boolean setStatus(RedissonClient client, String key, long offset, boolean status) {
        return status ? client.getBitSet(key).set(offset) : client.getBitSet(key).clear(offset);
    }

**Comment by mrniko** [comment]
Sorry, I don't follow. I fixed the existing method and you can use it.

**Comment by chimmi** [comment]
Sorry for the confusion.  `boolean set(long bitIndex)` is indeed fixed, `void set(long bitIndex, boolean value)` is not. I thought that the first one was added as a fix.

**Comment by mrniko** [comment]
Fixed
