### ISSUE TITLE
setPingConnectionInterval for replicated servers configuration is not propagated to underlying MasterSlaveServersConfig

### ISSUE THREAD

**Issue by avasenin** [redisson/redisson#1415]
Hey,

When I set `setPingConnectionInterval` in the replicated servers configuration it's not propagated to underlying master slave configuration:

```
      config.useReplicatedServers()
          .setPingConnectionInterval(1000)
          .addNodeAddress(nodeAddresses.toArray(new String[0]));
```

My current understand that ReplicatedServersConfig is used to create MasterSlaveServersConfiguration In the MasterSlaveConnectionManager in https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L389.

In this method setPingConnectionInterval is not copied and default value is used in MasterSlaveServersConfiguration.

**Comment by mrniko** [comment]
Hi! Right, Thanks for pointing out.

**Comment by mrniko** [comment]
Fixed
