### ISSUE TITLE
RedissonBoundedQueue expiration seems odd

### ISSUE THREAD

**Issue by vgpetrov** [redisson/redisson#1416]
Could someone help me to understand how expiration works with queue.
I found several `expire` method seems like they working fine, but after expiration it needs to initiate queue with `trySetCapacity` because it is not possible to add element there.
Also i found that `expire` works not per element, it sets for whole queue which i also don't understand, so there could be some strange things if i will set `expire` for 10 seconds and after will try to set for `20` seconds,  every element will be expired after 20 seconds.

I don't say that is a bug i just want to get proper information about expiration in queues.

Thanks for every answers.

**Comment by mrniko** [comment]
> I found several expire method seems like they working fine, but after expiration it needs to initiate queue with trySetCapacity because it is not possible to add element there.

This is expected behaviour. I have just mentioned that on wiki page.

> Also i found that expire works not per element, it sets for whole queue which i also don't understand, so there could be some strange things if i will set expire for 10 seconds and after will try to set for 20 seconds, every element will be expired after 20 seconds.

It's also correct behaviour. As reflected in javadoc of `expire` method it works for whole object and not its elements.

**Comment by vgpetrov** [comment]
@mrniko Thank you!
