### ISSUE TITLE
HOW TO GET REDIS TIME  IN REDISSION?

### ISSUE THREAD

**Issue by geriyoga** [redisson/redisson#1417]
How to get redis server time in redission?

**Comment by Flyffies** [comment]
You can get the redis nodes with the getNodeGroup method.
From there you can choose a specific Node or just any and call the time() method on it.

something like that: 
`Collection<Node> nodes = client.getNodesGroup().getNodes();
 // Get a node
 Node node = nodes.iterator().next();
 long time = node.time();`
