### ISSUE TITLE
Can Redisson KryoCodec default support 0-arg constructor object 

### ISSUE THREAD

**Issue by mumutu66** [redisson/redisson#1420]
As the immutable object is wildly used nowadays can redisson's KryoCodec supports it by default

when get the kryo instance from the pool using following code   `Objenesis` helps do the trick 
```
         Kryo kryo = new Kryo();
        ((Kryo.DefaultInstantiatorStrategy) kryo.getInstantiatorStrategy()).setFallbackInstantiatorStrategy(new StdInstantiatorStrategy());
```

related [issue](https://github.com/redisson/redisson/issues/1206)

**Comment by mrniko** [comment]
I don't see any problem with 0-arg contructor invocation using KryoCodec. Anyway you can your extension code overriding `KryoCodec.createInstance` method.
