### ISSUE TITLE
redis集群 读主的可以，读从的获取不到

### ISSUE THREAD

**Issue by libojacky** [redisson/redisson#1421]
版本3.6.5
1. 配置
Config config = new Config();
        config.useClusterServers()  
        .addNodeAddress("redis://192.168.2.156:6380"))
       .addNodeAddress("redis://192.168.2.156:6380"))
       .addNodeAddress("redis://192.168.2.156:6381"))
       .addNodeAddress("redis://192.168.2.156:6382"))
       .addNodeAddress("redis://192.168.2.156:6383"))
       .addNodeAddress("redis://192.168.2.156:6384"))
       .addNodeAddress("redis://192.168.2.156:6385"))
        .setScanInterval(2000) 
       .setReadMode(ReadMode.MASTER)
       .setSubscriptionMode(SubscriptionMode.MASTER);

如果设置成ReadMode.MASTER  可以读取到集群中的数据

2. 获取
@Resource
private RedissonClient redissonClient;
RBucket<User> userRBucket = redissonClient.getBucket(token);
User user = userRBucket.get();
如果用默认SLAVE就会读取为NULL

谢谢解答！

**Comment by leobelive** [comment]
这个问题是怎么解决的 ？ 我也遇到了 。。。

**Comment by jackygurui** [comment]
还没同步过来吧。

**Comment by leobelive** [comment]
同步过来了 ，看 slave 节点是有数据的，就是取不到

**Comment by leobelive** [comment]
master的节点 能取到

**Comment by jackygurui** [comment]
把你重现这个问题的详细步骤讲一下行吗？

**Comment by leobelive** [comment]
我就是 只使用了 基于 json 格式的 配置文件， 所有参数都是使用 默认 配置，只是 将 3主3从的 节点 配置在 nodeAddresses  这个参数里面， readMode  配置 SLAVE  读不到数据， 只有MASTER 才能读到数据，MASTER _SLAVE  只能偶尔读到数据 ，  序列化 使用的 KryoCodec ，  设置了 一下 密码 参数，  其他没有变，  clientName 没有填写 ，    然后 @Autowired RedissonClient redisson ;   来使用 ， 控制台 有输出 节点 的 master 和 slave 的 属性

2019-05-23 09:36:50.073  INFO 29248 --- [           main] org.redisson.Version                     : Redisson 3.10.7
2019-05-23 09:36:50.338  INFO 29248 --- [           main] o.r.cluster.ClusterConnectionManager     : Redis cluster nodes configuration got from XX.XX.95.35/XX.XX.95.35:7000:
19e67a94aa04b3af24617db9801cce80c36d106c XX.XX.95.35:7002@17002 slave 813b808a02f86bb83ddd17bbf330616a01232b32 0 1558575410000 4 connected
b9e7da21fde0b770e0d472ef8dbfcd215e992ad5 XX.XX.95.36:7001@17001 slave da7335071166af10d8a43fd67ee59bf675e0e8a1 0 1558575410655 5 connected
813b808a02f86bb83ddd17bbf330616a01232b32 XX.XX.95.36:7000@17000 master - 0 1558575409552 4 connected 5461-10922
5541538aa39881ca66e5e6dbc1810a2eb547f6a7 XX.XX.95.36:7002@17002 slave cfb55b6da47c079848d41e93e9ed042a1795f294 0 1558575409000 6 connected
cfb55b6da47c079848d41e93e9ed042a1795f294 XX.XX.95.35:7000@17000 myself,master - 0 1558575408000 1 connected 0-5460
da7335071166af10d8a43fd67ee59bf675e0e8a1 XX.XX.95.35:7001@17001 master - 0 1558575409652 2 connected 10923-16383

**Comment by leobelive** [comment]
> 把你重现这个问题的详细步骤讲一下行吗？

顶一下

**Comment by jackygurui** [comment]
> 同步过来了 ，看 slave 节点是有数据的，就是取不到

你是怎么看到的？

**Comment by leobelive** [comment]
我是 通过 RedisDesktopManager  这个 工具看到的

**Comment by leobelive** [comment]
是在不行 ，我到时 跟踪一下 源代码 ， 能告诉一下  主要看 那个类吗 ？ 谢谢

**Comment by jackygurui** [comment]
有没有什么报错？还是直接返回的空指针？

**Comment by leobelive** [comment]
没有 报错 ， RBucket.get 数据为null

**Comment by leobelive** [comment]
切换到 master  就可以获取到数据

**Comment by leobelive** [comment]
readMode

**Comment by jackygurui** [comment]
你可以通过redis-cli执行monitor命令检测一下吗？

**Comment by leobelive** [comment]
你说 看 slave 节点是否 保存了数据 是吗？

**Comment by jackygurui** [comment]
看看命令是否发过去了

**Comment by leobelive** [comment]
嗯 ，好的 ，我 这样 测试 一下   谢谢

**Comment by leobelive** [comment]
你好 ， 我刚才按照你的方式是了一下，  发现一个问题，  就是  写入到一个 master，和这个 master关联的slave 没有值， 值在另外2个slave 里面，  后台监控 出现了 get 命令 ，但是没有值 ，  我们是采用的redis5 的集群模式

**Comment by leobelive** [comment]
redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 \
127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 \
--cluster-replicas 1   这个集群命令

**Comment by leobelive** [comment]
读取的从节点 ，恰好是 没有数据的 那个 slave ， 其他2个slave 都有数据 。。。

**Comment by jackygurui** [comment]
> 你好 ， 我刚才按照你的方式是了一下， 发现一个问题， 就是 写入到一个 master，和这个 master关联的slave 没有值， 值在另外2个slave 里面， 后台监控 出现了 get 命令 ，但是没有值 ， 我们是采用的redis5 的集群模式

如果通过redis-cli查询关联的slave里面没有数据的话，说明这不是客户端的问题。需要检查一下集群。

**Comment by leobelive** [comment]
嗯 好的 谢谢

**Comment by zhankun** [comment]
我也遇到这个问题了，Redis5.0，redisson3.15.0
从slave节点获取不到数据。直接登录从节点服务器，可以获取到数据，Redirected to slot [4081] located at 主节点

**Comment by bufoon** [comment]
请看这个问题描述   https://blog.csdn.net/ankeway/article/details/118520241
