### ISSUE TITLE
Feature request - I would like the ability to specify redis channel name

### ISSUE THREAD

**Issue by mcacker** [redisson/redisson#1425]
Currently, when subscribing an application to redis events, via adding a listener, there's no easy way to specify a channel name.  The problem with this is that in a clustered environment, where each member of the cluster is responsible for updating the same redis keys, e.g., session keys, then all members of the cluster will receive all notifications for all the updates, even if they are only interested in the updates that they made.

One way to get around this is to specify a unique channel name for each member of the cluster, resulting in only being notified of the updates that it is responsible for.

I have been able to achieve this by subclassing the Redisson class, in my case the RedissonMapCache, and overloading the channel naming methods.  I've demonstrated that this works.  One problem with this is that without additional modifications or extensions to Redisson, it won't work with batching.  Ideally, if one could provide a mechanism for modifying the channel name, that would be great.

thanks, Mitchell

**Comment by jackygurui** [comment]
Consulted in Gitter. Solved with alternative methods.
