### ISSUE TITLE
Spring cache not expired properly

### ISSUE THREAD

**Issue by mkadan** [redisson/redisson#1427]
﻿### Expected behavior
Spring Cache should expire with given TTL making it footprint stay at the same level

### Actual behavior
Spring Cache footprint constantly grows

### Steps to reproduce or test case
The Spring Cache data items seem not to be evicted by Redisson if other keys in the same hash are accessed before in periods lower than Spring Cache expiration time, even if this access is performed for different data items.

E.g. imagine a case where there is a Spring Cache region named "test-cache" with TTL of 5 minutes.
1. At 00:00 an item "test-key-1" is put there.
2. At 01:00 an item "test-key-2" is put there.
3. At 02:00 an item "test-key-2" is accessed.
4. At 04:00 an item "test-key-2" is accessed.
5. At 05:00 I expect an item "test-key-1" to expire, but it does not.
6. At 09:00 (5 minutes after last "test-cache" access) both items are expired.

That leads to a problem of uncontrollable cache grows, as the cache is almost 100% guaranteed to be accessed in the period if individual item's TTL (see screenshot): https://www.dropbox.com/s/jrcfocdsitxhqbm/Screenshot%202018-05-04%2010.59.37.png?dl=0

You can see non-expiring Spring Cache in the following _redis-cli_ output (it is production instance output, so no "test-cache" there, but check "ContentService.findAllByContentGroupOrdered" instead that has grown to 27256 members - should be around 100 in a normal case):
```
MB-40:~$ redis-cli --bigkeys

# Scanning the entire keyspace to find biggest keys as well as
# average sizes per key type.  You can use -i 0.1 to sleep 0.1 sec
# per 100 SCAN commands (not usually needed).

[00.00%] Biggest hash   found so far '{ContentRepository.findAllByContainerContent}:redisson_options' with 1 fields
[00.00%] Biggest zset   found so far 'redisson__timeout__set:{ContentSearchService.search}' with 2 members
[00.00%] Biggest zset   found so far 'redisson__timeout__set:{ContentRepository.findAllByContainerContent}' with 100 members
[00.00%] Biggest zset   found so far 'redisson__idle__set:{ContentService.findAllByContentGroupOrdered}' with 27256 members
[00.00%] Biggest hash   found so far 'ContentSearchService.search' with 2 fields
[30.30%] Biggest hash   found so far 'ContentRepository.findAllByReferralContent' with 81 fields
[30.30%] Biggest hash   found so far 'ContentRepository.findAllByContainerContent' with 100 fields
[63.64%] Biggest hash   found so far 'ContentService.findAllByContentGroupOrdered' with 27256 fields

-------- summary -------

Sampled 33 keys in the keyspace!
Total key length in bytes is 1735 (avg len 52.58)

**Biggest   hash found 'ContentService.findAllByContentGroupOrdered' has 27256 fields
Biggest   zset found 'redisson__idle__set:{ContentService.findAllByContentGroupOrdered}' has 27256 members**

0 strings with 0 bytes (00.00% of keys, avg size 0.00)
0 lists with 0 items (00.00% of keys, avg size 0.00)
0 sets with 0 members (00.00% of keys, avg size 0.00)
17 hashs with 29197 fields (51.52% of keys, avg size 1717.47)
16 zsets with 58376 members (48.48% of keys, avg size 3648.50)
```

### Redis version
3.2.10

### Redisson version
3.6.5

### Redisson configuration
default single server config with FstCodec

```
    @Bean
    public RedissonClient redisson() {
        Config config = new Config();
        config.setCodec(new FstCodec());

        SingleServerConfig singleServerConfig = config.useSingleServer();
        singleServerConfig.setAddress("redis://" + redisProperties.getHost() + ":" + redisProperties.getPort());
        singleServerConfig.setDatabase(redisProperties.getDatabase());

        return Redisson.create(config);
    }

    @Bean
    public CacheManager cacheManager() {
        Map<String, CacheConfig> config = new HashMap<>();
        config.put("test-cache", 300_000L);

        return new RedissonSpringCacheManager(redisson(), config);
    }

    // test method
    @Cacheable(value = "test-cache", sync = true)
    public String renderContent(String key) {
        return "test";
    }
```

**Comment by mrniko** [comment]
Seems the problem is in size of `ContentService.findAllByContentGroupOrdered` could you share used CacheConfig for it?

**Comment by mkadan** [comment]
```
    @PreAuthorize("hasRole('ROLE_USER') and hasPermission(#contentGroup, 'read')")
    @Transactional(readOnly = true)
    @Cacheable(value = CachingConfiguration.CACHE__CONTENT_SERVICE__FIND_ALL_BY_CONTENT_GROUP_ORDERED, sync = true)
    public Page<Content> findAllByContentGroupOrdered(
            @P("contentGroup") @CacheKeyEntityId ContentGroup contentGroup,
            @CacheKeyTruncatedTime Instant time,
            int preferredPositionLimit,
            int preferredPositionLimitSecondary,
            Pageable pageable) {
```

@CacheKeyEntityId and @CacheKeyTruncatedTime there are custom annotations that modify creation of SimpleKey for Spring Cache (use entity id instead on entity instance and round time to 5 minutes boundary respectively).

Expiration is set to 300_000L for this cache region.

**Comment by mrniko** [comment]
you should set maxIdleTime = 0 if you want to use ttl param only

**Comment by mkadan** [comment]
Thx, will do that and check if that helps. I will write down the results here.

**Comment by mkadan** [comment]
It helped, thank you.
https://www.dropbox.com/s/xc5xr8ygt2nlqkt/Screenshot%202018-05-06%2011.43.24.png?dl=0

Could you please provide some inside how setting maxIdleTime may have been affecting evicting of unused items?

**Comment by mrniko** [comment]
With maxIdleTime setting set, when element was requested its life span is increased on maxIdleTime value.
