### ISSUE TITLE
Cannot Read Avro encoded Object from Redis after changing Java Class

### ISSUE THREAD

**Issue by sonoman** [redisson/redisson#1431]
﻿### Expected behavior
I don't know if that's the way it works, but I was expecting that I'm able to add a new field to a class, and the deserialization from Redis would be Backward compatible with the "old" schema for the class.

### Actual behavior
The actual behavior is that the Read operation from Redis (RBucket) explodes, with all kind of deserialization/parsing errors, depending on the type of the new field. But it breaks always.

### Steps to reproduce or test case
I just created a simple Java Class. Then I initialize the codec for my redisson client in this way:

```
private void buildCodec(Class entityClass) {
		AvroMapper am = new AvroMapper();
		am.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		AvroSchema schema = null;
		try {
			schema = am.schemaFor(entityClass);
		} catch (JsonMappingException e) {
			logger.error("Error configuring serialization codec: " + e.getMessage(), e);
		}
		this.codec = new AvroJacksonCodec(entityClass, schema);
	}

```
and I'm able to write and read my object instances from Redis. But After I add a new attribute to my Java Class, then I'm not able to read my saved objects anymore. If I remove the field, then everything starts working again. 

### Redis version
4.0.9

### Redisson version
3.6.5

### Redisson configuration
singleServerconfig

**Comment by mrniko** [comment]
Here is how you can solve it with Kryo codec

https://github.com/redisson/redisson/issues/2402#issuecomment-578385916
