### ISSUE TITLE
Incorrect results from RBitSet.setAsync

### ISSUE THREAD

**Issue by chimmi** [redisson/redisson#1435]
I believe the issue is in RedisCommands SETBIT_TRUE and SETBIT_FALSE that use BitSetReplayConvertor that, by the look of it, is implemented to return true if Redis sends back the same value as was passed to SETBIT. Meanwhile the [docs](https://redis.io/commands/setbit) say:

> Return value
Integer reply: the original bit value stored at offset.

So the implementation should be something like:

    @Override
    public Boolean convert(Object obj) {
        return 1 == (Long)obj;
    }

In fact, you dont event need two different RedisCommands.

**Comment by mrniko** [comment]
Thanks for your suggestion, but this issue was already fixed in https://github.com/redisson/redisson/issues/1410
