### ISSUE TITLE
RedissonListReactive don't implement readAll and there is no method that uses LRANGE

### ISSUE THREAD

**Issue by garciapd** [redisson/redisson#1441]
﻿### Expected behavior
Get all the elements from a list at once using the reactive API (a method that uses LRANGE)

### Actual behavior
I have to use RList to get all the elements at once or the iterator from the RedissonListReactive but that last one take ages.

### Redisson version
3.7.0

**Comment by mrniko** [comment]
Done! Thanks for report.
