### ISSUE TITLE
RLocalCachedMap memory leak when using EvictionPolicy.WEAK

### ISSUE THREAD

**Issue by pawelgrzes** [redisson/redisson#1442]
﻿### Expected behavior
Weak references should be cleared.

### Actual behavior
It seems that even when using static Strings for keys and values and only ```fastPut``` method the OOM error occurs after several thousands of invocations.
  
### Steps to reproduce or test case
I have created a separate repo to easier reproduce the problem:
https://github.com/pawelgrzes/redisson-mem-leak

### Redis version
4.0.9

### Redisson version
3.7.0

### Redisson configuration
```
RedissonClient redissonClient = Redisson.create();

LocalCachedMapOptions ops = LocalCachedMapOptions.defaults()
  .cacheSize(0)
  .timeToLive(0)
  .maxIdle(0)
  .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.CLEAR)
  .syncStrategy(LocalCachedMapOptions.SyncStrategy.INVALIDATE)
  .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.WEAK);

RLocalCachedMap<String, String> map = redissonClient.getLocalCachedMap("sample-cache", ops);
```

**Comment by pawelgrzes** [comment]
I have dug a little deeper. It seems that the problem may be caused when creating a weak reference:
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/cache/ReferenceCachedValue.java#L36

The non-null queue is passed. So when GC is run the references are stored in the ReferenceQueue which is never cleared.
I guess the intention of queue purging was here:
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/cache/ReferenceCacheMap.java#L55
But the implementation anyway is done only for soft references so even if queue is purged a ClassCastException would be thrown.

**Comment by mrniko** [comment]
> But the implementation anyway is done only for soft references so even if queue is purged a ClassCastException would be thrown.

You were right! Thanks for the evaluation of the issue and shared thoughts. Fixed!
