### ISSUE TITLE
How do I get redis server nanoTime？

### ISSUE THREAD

**Issue by langyan1022** [redisson/redisson#1443]
redis cmd time return 
 1)  "1526885762"
 2)  "732568"

but redisson time() method only return 1)  1526885762

I want to get  1)+ 2)  ，please help me

Thank you.

**Comment by mrniko** [comment]
According to the documentation second parameter of command response is time in microseconds. Anyway, I'll extend the Response for this method.

**Comment by mrniko** [comment]
Done
