### ISSUE TITLE
ElasticCache clusterserverconfig - TTL is not working as expected

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#1446]
i am using clusterServersConfig for my ElasticCache Redis Cluster, with redisson 3.2.0. Cluster has 1 shard with 2 nodes. 

The cache is not expiring after 1sec as expected. Also calling CacheEvict explicitly doesn't clear the cache. 

Anything missing in config here?

Cache config is as below mentioned.

**server config:**
{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
--------------------
--------------------
}

**cache-config.yaml**

---
testmap:
  ttl: 1000
  maxIdleTime: 1000

**Comment by jackygurui** [comment]
Have you checked the FAQ relating to this?

https://github.com/redisson/redisson/wiki/16.-FAQ#q-in-mapcachesetcachespringcachejcache-i-have-set-an-expiry-time-to-an-entry-why-is-it-still-there-when-it-should-be-disappeared

**Comment by anilkonduru** [comment]
The entries are not evicted at all, no matter how long it takes

**Comment by anilkonduru** [comment]
never mind, it was a different issue. Different question, what does it mean if TTL is 0 and maxIdleTime is 1000?

**Comment by mrniko** [comment]
ttl = 0 and maxIdleTime = 1000 means that ttl setting won't be applied and entry will be evicted if its idle time reached 1 second.
