### ISSUE TITLE
Job distribution among several RedissonNodes.

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1451]
In case when there are multiple RedissonNodes how the jobs get distributed among them and is it possible that jobs can get executed by both Redisson Nodes (Duplicate execution of scheduled job)

**Comment by mrniko** [comment]
Tasks are stored in a single queue handled by multiple Redisosn Nodes, so duplicated execution is not possible.

**Comment by arpit728** [comment]
And how does the scheduled jobs get distributed among several redisson nodes.

**Comment by mrniko** [comment]
Each Redisson Node poll a task from head of queue in order they requested it.

**Comment by arpit728** [comment]
But when we schedule the job we bind them to the executor service. Does executor service runs inside the redisson node.

Can you refer me to some doc where I can understand the whole picture in detail. Everything about redissonnode, ExecutorService and entire flow of job from creation to execution. I want to know how this components are placed together.

**Comment by mrniko** [comment]
There are no available docs on internal architecture of this ExecutorService. I can offer you to review the code itself and tests:

https://github.com/redisson/redisson/blob/10f8839f2983357a9b8378201bc0bad8708f8d6f/redisson/src/test/java/org/redisson/executor/RedissonScheduledExecutorServiceTest.java

https://github.com/redisson/redisson/blob/10f8839f2983357a9b8378201bc0bad8708f8d6f/redisson/src/test/java/org/redisson/executor/RedissonExecutorServiceTest.java

**Comment by arpit728** [comment]
Thanks for that.

Is it the redissonnode that poll the head of the queue or the workers of executorservice polls the queue.

**Comment by mrniko** [comment]
Workers are polling the head of the queue.

**Comment by arpit728** [comment]
Where does redissonnode and worker sit in the whole picture.

**Comment by mrniko** [comment]
RedissonNode could be located anywhere even on the same JVM as Redisson client.

**Comment by arpit728** [comment]
So does the workers run inside the redissonnode.

**Comment by mrniko** [comment]
Yes

**Comment by arpit728** [comment]
Can you look into [this](https://github.com/redisson/redisson/issues/1456)

**Comment by raftonsea** [comment]
@arpit728   So ,  do you know   how the RedissonNodes  invoke the schedule jobs ? I am so confusing now .. Thanks!

**Comment by arpit728** [comment]
@raftonsea 

It's super simple. 

Redisson Maintains three queues for the jobs one for Upcoming jobs and one for active jobs and one for results.

So whenever the execution time of one job is reached job gets transferred to active queue.

Redisson Node:
You can think of it as bunch of workers that keeps polling the active queue and executes your job.

Let me know if you have any further queries.

**Comment by raftonsea** [comment]
> @raftonsea
> 
> It's super simple.
> 
> Redisson Maintains three queues for the jobs one for Upcoming jobs and one for active jobs and one for results.
> 
> So whenever the execution time of one job is reached job gets transferred to active queue.
> 
> Redisson Node:
> You can think of it as bunch of workers that keeps polling the active queue and executes your job.
> 
> Let me know if you have any further queries.


Thanks !!!  .

For the last sentence .    Redisson node poll the job and execute it . Does it is means Redisson node execute the job in it's process(JVM)  ? If so ,  if the job needs use some Spring Bean  but the Redisson node is running as a  simple main method  (  public static void main (){  ...  redissonnode.start();  }   )  , what happen ??
