### ISSUE TITLE
setPingConnectionInterval for single server configuration is not propagated to underlying MasterSlaveServersConfig

### ISSUE THREAD

**Issue by nigelh-iw** [redisson/redisson#1455]
﻿### Expected behavior
Setting the pingConnectionInterval on a single server config should enable periodic ping on connections.

### Actual behavior
No pings take place.  Similar to #1415, this appears to be due to SingleConnectionManager.create not copying the configured value to the MasterSlaveServersConfig.

### Steps to reproduce or test case
Create single server redisson client with config:
```
        config.useSingleServer()
                .setAddress(nodeAddress)
                .setPingConnectionInterval(5000);
```
### Redis version
Any

### Redisson version
3.7.0

**Comment by mrniko** [comment]
Fixed
