### ISSUE TITLE
RedissonExecutorService 不能序列化DelegatingErrorHandlingRunnable

### ISSUE THREAD

**Issue by langyan1022** [redisson/redisson#1463]
我在使用@Scheduler注解的时候，这样配置了下ScheduledExecutorService，期望使用redisson 的ScheduledExecutorService，
` 
@Bean
public ScheduledExecutorService scheduledExecutorService(RedissonClient redissonClient){
          return redissonClient.getExecutorService("executer");
}
`

但是跟踪到private byte[] encode(Object task) ；方法的这行
 buf = codec.getValueEncoder().encode(task);抛出了异常。
Caused by: java.lang.StackOverflowError: null

序列化使用的是jackson，异常信息太多不方便贴出 。请问是否这样的使用方式不可行？

**Comment by jackygurui** [comment]
能提供一下重现代码吗？另外请按照issue模板里提供运行环境相关信息。谢谢。

**Comment by springboot4** [comment]
怎么解决的？

**Comment by springboot4** [comment]
> 我在使用@Scheduler注意的时候，这样配置了下ScheduledExecutorService，期望使用redisson的ScheduledExecutorService， ` @Bean public ScheduledExecutorService scheduledExecutorService(RedissonClient redissonClient){ return redissonClient.getExecutorService("executer"); }`
> 
> 但是跟踪到private byte[] encode(Object task) ；方法的 这个buf = codec.getValueEncoder().encode(task);抛出异常。 Caused by: java.lang.StackOverflowError: null
> 
> 顺序化使用的是jackson，异常信息太多不方便贴出。请问是否这种使用方式不可行？

请问您是怎么解决的 我也遇到这个问题了。
