### ISSUE TITLE
How does redisson balances load among several RedissonNodes while scheduling jobs.

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1469]

**Comment by jackygurui** [comment]
Jobs are submitted to a RBlockingQueue while workers are all trying to take jobs from the same queue. The RBLockingQueue is effectively implemented based on calling the BLPOP command on a list, you can find the detailed schematics on how BLPOP behaves under contention at here: https://redis.io/commands/blpop#what-key-is-served-first-what-client-what-element-priority-ordering-details

**Comment by arpit728** [comment]
@jackygurui 
Can you please answer the following question :-

1. How does redisson decides which job should be put in which queue? 
2. When does new queue gets created?
3. How many queues are there?
4. Does redisson put all the jobs in the same queue?

**Comment by jackygurui** [comment]
> How does redisson decides which job should be put in which queue?

Based on the name of the service

> When does new queue gets created?

When a new service is created.

> How many queues are there?

3 for each service

> Does redisson put all the jobs in the same queue?

no, different services have different queues.

> Is there any role of RTopic in all this? If yes, where?

Yes, it is used in various places by works, scheduler and the service itself.

**Comment by jackygurui** [comment]
> By name of executor service you mean?

Yes.

>  You mean whenever a new executor service is created three queues are created for it and messages are equally distributed in all of them.

No. Three queues are for different purposes: request, response and scheduling. 

> @mrniko once mentioned here Tasks are stored in the single queue then what is the purpose of other two queues.

See above

> The workers will blindly take the job from the queue, but the job has to be executed at its schedule, how this thing is taken care of?

The workers will check if the job is due before it starts the execution

> What happens when the execution time of job has come?

The worker will try to execute the job.

**Comment by jackygurui** [comment]
> Can you please explain their purpose in more details. And which queues among this worker keeps polling.

The request queue contains tasks needs immediate execution, scheduling queue contains the tasks needs to be executed in the future. Response queue contains results to be sent back.

> Suppose the worker polls the queue and gets one job and suppose the execution of that job has not yet come then what it will do.

Jobs are not due will be kept in the scheduling queue. A separate service is running to check and move the scheduled jobs to the request queue, and only then a worker will pick it up and execute it.
