### ISSUE TITLE
Redisson CROSSSLOT Keys in request don't hash to the same slot. channel

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1471]
I scheduled some jobs first then I run one RedissonNode in standalone mode. and I got this error.

I have used the below code for scheduling the jobs.

```java
public class Main {

    private final static int NO_OF_JOBS = 50;
    static int i = 1;

    public static void main(String[] args) {
        AtomicInteger a = new AtomicInteger(0);
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress("http://127.0.0.1:7000", "http://127.0.0.1:7001", "http://127.0.0.1:7002");
        RedissonClient redisson = Redisson.create(config);
        RExecutorService e = redisson.getExecutorService("d1");//redisson.getExecutorService("w1");
        for (int j = 0; j < NO_OF_JOBS; j++) {
            Calendar calendar = Calendar.getInstance();
            int hour = calendar.get(Calendar.HOUR_OF_DAY);
            int minute = calendar.get(Calendar.MINUTE) + 1;
            //System.out.println("hour, minute" + hour + ", " + minute);
            ((RScheduledExecutorService) e).schedule(new RunnableTask(j + 1), CronSchedule.dailyAtHourAndMinute(hour, minute));
        }
    }
}
public class RunnableTask implements Runnable {

    private int job_no;
    
    RunnableTask(int job_no) {
        this.job_no = job_no;
    }

    public void run() {
        try {
            Thread.sleep(10);
            System.out.println("This is task no " + job_no);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
Previously it was working fine but I have suddenly started getting this issue.

I am running 3 node redis cluster, with one replica
redis version 4.0.9
redisson version 3.7.0

`[redisson-3-20] ERROR org.redisson.RedissonRemoteService - Can't execute: RemoteServiceRequest [requestId=52033463679a97be9bc4248e13a5c090, methodName=schedule, signatures=[[java.lang.String, [B, [B, long, java.lang.String, java.lang.String, java.lang.String]], args=[com.webengage.RunnableTask, [B@b02600d, [B@6703129b, 1528125840000, 0 54 20 ? * *, b00d5604-0e02-4a1a-8ea2-82ece6424caf, 52033463679a97be9bc4248e13a5c090], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=null], date=1528125782651]
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.redisson.RedissonRemoteService.invokeMethod(RedissonRemoteService.java:340)
	at org.redisson.RedissonRemoteService.access$400(RedissonRemoteService.java:66)
	at org.redisson.RedissonRemoteService$2.run(RedissonRemoteService.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0xada13228, L:/127.0.0.1:59757 - R:localhost/127.0.0.1:7003] command: (EVAL), params: [if redis.call('zrem', KEYS[2], ARGV[1]) > 0 then redis.call('hdel', KEYS[6], ARGV[1]); if redis.call..., 6, {{d1:org.redisson.executor.RemoteExecutorService}:org.redisson.executor.RemoteExecutorService}, {d1:org.redisson.executor.RemoteExecutorService}:scheduler, {d1:org.redisson.executor.RemoteExecutorService}:counter, {d1:org.redisson.executor.RemoteExecutorService}:status, {d1:org.redisson.executor.RemoteExecutorService}:termination-topic, {d1:org.redisson.executor.RemoteExecutorService}:tasks, 52033463679a97be9bc4248e13a5c090, 1, ...]`

**Comment by ericwu1** [comment]
Are you executing redis commands on different keys which hash to different nodes in a cluster environment?

**Comment by arpit728** [comment]
I just scheduled the jobs and spawned a redisson node in standalone mode. I don't have idea about how does redisson node internally fetches the job.
I was doing same thing earlier and was working successfully, I don't what went wrong after that.

**Comment by jackygurui** [comment]
Are you able to provide some code samples to reproduce the problem?

**Comment by arpit728** [comment]
@jackygurui
I have update the description with the relevant information, kindly take a look and let me know if any more information is needed.

**Comment by arpit728** [comment]
@mrniko 
Can you please look in this issue as well.

**Comment by mrniko** [comment]
Tried test below, but no luck:

```java
    @Test
    public void testInCluster() throws Exception {
        RedisRunner master1 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner master2 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner master3 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner slot1 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner slot2 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner slot3 = new RedisRunner().randomPort().randomDir().nosave();
        
        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slot1)
                .addNode(master2, slot2)
                .addNode(master3, slot3);
        ClusterProcesses process = clusterRunner.run();
        
        Config config = new Config();
        config.useClusterServers()
        .setLoadBalancer(new RandomLoadBalancer())
        .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);
        
        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("test", 1));
        node = RedissonNode.create(nodeConfig, redisson);
        node.start();
        
        AtomicInteger a = new AtomicInteger(0);
        RExecutorService e = redisson.getExecutorService("d1");//redisson.getExecutorService("w1");
        for (int j = 0; j < 50; j++) {
            Calendar calendar = Calendar.getInstance();
            int hour = calendar.get(Calendar.HOUR_OF_DAY);
            int minute = calendar.get(Calendar.MINUTE) + 1;
            //System.out.println("hour, minute" + hour + ", " + minute);
            ((RScheduledExecutorService) e).schedule(new RunnableTask1(j + 1), CronSchedule.dailyAtHourAndMinute(hour, minute));
        }

        Thread.sleep(120000);
        
        node.shutdown();
        
        redisson.shutdown();
        process.shutdown();
    }
```

**Comment by arpit728** [comment]
@mrniko 
This issue was resolved when I added default constructor to RunnableTask. Can you please share the specs for the class which will represent our task.

**Comment by mrniko** [comment]
Unable to reproduce
