### ISSUE TITLE
RSet can not guarantee element unique.

### ISSUE THREAD

**Issue by lywhlao** [redisson/redisson#1475]
TestBean is
``` java
@Data
@EqualsAndHashCode(of = "id") //use lombok  .This annotation means use **id**  for hashing
public class TestBean {
    long id;
    String name;
}

```
``` java
        RSet<TestBean> set = mRedisClient.getSet("testSet");
        TestBean t1=new TestBean();
        t1.setId(1);
        t1.setName("1");

        TestBean t2=new TestBean();
        t2.setId(1);
        t2.setName("2");

        set.add(t1);
        set.add(t2);
```

﻿###  Expected behavior

set's size is 1

### Actual behavior
set's size is 2, contains {"@class":"com.meta.po.TestBean","id":1,"name":"2"} and
{"@class":"com.meta.po.TestBean","id":1,"name":"1"}

### Redis version
3.2.100
### Redisson version
2.12.1

**Comment by hans123456** [comment]
Did you try check if they really have the same hashcode?

Did you try putting the hashcode and equals manually?

**Comment by jackygurui** [comment]
I am afraid this is the result of the combination of the chosen serialisation method and the characteristics of a Redis set.

Try to turn the TestBean into a LiveObject.

**Comment by lywhlao** [comment]
@hans123456  yes.I am sure they have same hashcode.
here is source code generated by lombok. 
``` java
    public boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof TestBean)) return false;
        final TestBean other = (TestBean) o;
        if (!other.canEqual((Object) this)) return false;
        if (this.getId() != other.getId()) return false;
        return true;
    }

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $id = this.getId();
        result = result * PRIME + (int) ($id >>> 32 ^ $id);
        return result;
    }
```

**Comment by lywhlao** [comment]
@jackygurui  Yes ,that's right. I find Rset is based on Set in Redis. Rset's put method uses SADD. Although t1 and t2 have same hashcode.But they have different encode value generated By JsonJacksonCodec.

**Comment by jackygurui** [comment]
@lywhlao thanks for confirming, have you tried my suggestion?

**Comment by lywhlao** [comment]
@jackygurui  Hmm. Follow your suggestions, It works ,current code is 
``` java
        RLiveObjectService service = mRedisClient.getLiveObjectService();
        RSet<TestBean> set = mRedisClient.getSet("testSet");
        TestBean t1=new TestBean();
        t1.setId(1);
        t1.setName("1");

        TestBean t2=new TestBean();
        t2.setId(1);
        t2.setName("2");

        TestBean lt1 = service.attach(t1);
        TestBean lt2 = service.attach(t2);

        set.add(lt1);
        set.add(lt2);
        System.out.println(set.size());// print 1.

```
Can we add this feature to Rset  ,Because it implement java.util.Set,It will confuse some people if they override hashcode and equals method.

**Comment by jackygurui** [comment]
The live object is the solution to this problem as it has described here: https://github.com/redisson/redisson/wiki/9.-distributed-services#922-usage
