### ISSUE TITLE
RedissonScoredSortedSet uses wrong codec for some score methods

### ISSUE THREAD

**Issue by abel98** [redisson/redisson#1477]
﻿### Expected behavior
The codec specified in the constructor should be used only for values, not for scores.
Redis commands : RedisCommands.ZSCORE and RedisCommands.ZSCORE_CONTAINS

### Actual behavior
Codec for scores sometimes uses LongCodec sometimes uses "codec". For backward data compatibility should always use LongCodec when accessing scores.
### Steps to reproduce or test case
Create a ScoredSortedSet with non default codec and use getScoreAsync / containsAsync methods
### Redis version
4.0.6
### Redisson version
3.7.1

Used to work fine with Redisson Version 3.5.7, when upgraded to 3.7.1 ScoredSortedSet stopped working. Codec 

Works fine with this change:
```
 @Override
        public @Nullable RFuture<Double> getScoreAsync(final @Nullable V o) {
            return commandExecutor.readAsync(getName(), LongCodec.INSTANCE, RedisCommands.ZSCORE, getName(), encode(o));
        }
@Override
        public @Nullable RFuture<Boolean> containsAsync(final @Nullable Object o) {
            return commandExecutor.readAsync(getName(), LongCodec.INSTANCE, RedisCommands.ZSCORE_CONTAINS, getName(), encode(o));
        }

```

**Comment by mrniko** [comment]
Fixed! Thanks for report
