### ISSUE TITLE
Delete/modify scheduled jobs in redisson

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1478]
How can I get control over already scheduled jobs in redisson and do operation such as delete/modify on them.

**Comment by mrniko** [comment]
Use `RExecutorService.cancelTask` to cancel/delete task. Modification of task is unavailable.

**Comment by arpit728** [comment]
@mrniko 
`RExecutorService.cancelTask` takes `taskId` as input, how do I get the `taskId`.

**Comment by mrniko** [comment]
@arpit728 use RExecutorFuture.getTaskId()
> and also mention how can I get the details of all the scheduled jobs.

It's not possible yet.

**Comment by arpit728** [comment]
@mrniko 

Why I am not able to lookup on the basis of this id directly in redis.
