### ISSUE TITLE
单节点锁不住

### ISSUE THREAD

**Issue by liupeng362978375** [redisson/redisson#1482]
SingleServerConfig serverConfig = config.useSingleServer()
            .setAddress("redis://" + redissonProperties.getHost() + ":" + redissonProperties.getPort())
            .setTimeout(redissonProperties.getTimeout())
            .setConnectionPoolSize(redissonProperties.getConnectionPoolSize()).setDatabase(0);
        config.setLockWatchdogTimeout(redissonProperties.getLockWatchdogTimeout());配置

lock.lock(“ceshifangfa”）
TODO
lock.unlock

**Comment by HeroHong** [comment]
![Uploading TIM图片20180627101733.png…]()


单点锁锁不住，改怎么解决
