### ISSUE TITLE
RedissonLocalCachedMap - "readAll*()" and "values()" methods could read from local cache only?

### ISSUE THREAD

**Issue by jsrba** [redisson/redisson#1483]
The performance benefit of using RedissonLocalCachedMap over RedissonMap is negligible when getting all data from the map via `readAllKeySet*()`, `readAllValues*()`, `readAllEntrySet*()` and `values()`. The `readAll*()` methods still gets data from server, `values()` method is not overriden in RedissonLocalCachedMap.

Would it be possible to read data only from the local cache in these cases?

**Comment by jsrba** [comment]
Going through the code, I see that it would depend on the implementation of the local cache - there should be no TTL or cache size constraints. Also `preloadCache` would have to be called.

To solve my needs, I inherited from RedissonLocalCachedMap:
```java
public class LocalCachedMap<K,V> extends RedissonLocalCachedMap<K,V> {

    private Cache<CacheKey, CacheValue> cache;

    public LocalCachedMap(
            CommandAsyncExecutor commandExecutor,
            String name,
            EvictionScheduler evictionScheduler,
            RedissonClient redisson) {
        super(commandExecutor, name, LocalCachedMapOptions.defaults(), evictionScheduler, redisson);

        preloadCache();
    }

    @Override
    protected Cache<CacheKey, CacheValue> createCache(LocalCachedMapOptions<K, V> options) {
        cache = new NoneCacheMap<>(0, 0);
        return cache;
    }

    @Override
    public Collection<V> values() {
        final List<V> result = new ArrayList<V>();
        final List<Object> mapKeys = new ArrayList<Object>();
        for (CacheValue value : cache.values()) {
            mapKeys.add(encodeMapKey(value.getKey()));
            result.add((V) value.getValue());
        }
        return result;
    }
}
```

**Comment by a2232189** [comment]
Same problem.

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/1823
