### ISSUE TITLE
do as the redisson3.7.1 RRateLimiter wiki,but it does not work!

### ISSUE THREAD

**Issue by apple987** [redisson/redisson#1484]
the code blow:
config:
 @Bean
	public RRateLimiter rRateLimiter(RedissonClient redissonClient){
	     RRateLimiter rateLimiter = redissonClient.getRateLimiter("myRateLimiter");
	     System.err.println("初始化流速10设置:"+rateLimiter.trySetRate(RateType.OVERALL, 10, 1,  RateIntervalUnit.SECONDS));          
	     return rateLimiter;
	}
call function:
 @Autowired
  private RRateLimiter rateLimiter;
@ApiOperation(value = "列表",notes = "进入列表页", httpMethod = "GET")
	@RequestMapping(value = "init",method = RequestMethod.GET)
	public String init(){
	    if(rateLimiter.tryAcquire(1,0, TimeUnit.SECONDS)){//获取令牌成功，尝试一次，直接返回
			try {
				System.err.println("获取令牌成功，确定执行时刻:" + new SimpleDateFormat("yyyy-MM-dd hh:mm:ss S").format(new Date()));
				// 模拟执行耗时5秒
				TimeUnit.SECONDS.sleep(5);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
	    }else{
	    	System.err.println("获取令牌失败，拒绝执行时刻:"+new SimpleDateFormat("yyyy-MM-dd hh:mm:ss S").format(new Date()));
	    }
		return "solr/selectSolr";
	}

the RedissonClient init success with cluster model,the console always print 
1.初始化流速10设置:false,
this function "rateLimiter.trySetRate(RateType.OVERALL, 10, 1, RateIntervalUnit.SECONDS)",return false  why?
need code demo for RateLimiter,thanks !

**Comment by mrniko** [comment]
Try 3.7.5 version. It contains a few bug fixes for this object.
