### ISSUE TITLE
tryLock waitTime no valid

### ISSUE THREAD

**Issue by wy545** [redisson/redisson#1485]
hello, I have test the tryLock with waitTime, but find it has bug. My test is as follows:

class MyThread2 extends Thread {
public void run() {
RLock lock = null;
try {
lock = redisson.getLock(lockName);
if (lock.tryLock(5,10,TimeUnit.SECONDS)) {
System.out.println(Thread.currentThread().getName() + "正在执行...");
TimeUnit.SECONDS.sleep(2);
System.out.println("2s结束....");
} else {
System.out.println(Thread.currentThread().getName() + "获取锁失败...");
}
} catch (InterruptedException e) {
e.printStackTrace();
} finally {
if (lock != null) {
lock.unlock();
System.out.println("释放锁...");
} else {
System.out.println("null");
}
}
}

Two threads run the above,the result is as follows:
Thread-512正在执行...
2s结束....
释放锁...
Thread-513获取锁失败...
释放锁...
As you can see, the second thread faild to acquire lock but the lock is released during 2 seconds...please tell me ,thanks

**Comment by wy545** [comment]
hello, I have test the tryLock with waitTime, but find it has bug. My test is as follows:


class MyThread2 extends Thread {
        public void run() {
            RLock lock = null;
            try {
                lock = redisson.getLock(lockName);
                if (lock.tryLock(5,10,TimeUnit.SECONDS)) {
                    System.out.println(Thread.currentThread().getName() + "正在执行...");
                    TimeUnit.SECONDS.sleep(2);
                    System.out.println("2s结束....");
                } else {
                    System.out.println(Thread.currentThread().getName() + "获取锁失败...");
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            } finally {
                if (lock != null) {
                    lock.unlock();
                    System.out.println("释放锁...");
                } else {
                    System.out.println("null");
                }
            }
        }

Two threads run the above,the result is as follows:
Thread-512正在执行...
2s结束....
释放锁...
Thread-513获取锁失败...
释放锁...
As you can see, the second thread faild to acquire lock but the lock is released during 2 seconds...please tell me ,thanks

**Comment by jackygurui** [comment]
能不能请按照模板要求把运行环境提供一下？另外能把完整的代码发出来吗？
