### ISSUE TITLE
jvm create to many HashMap Nodes cause many YGC

### ISSUE THREAD

**Issue by xornono** [redisson/redisson#1487]
## question
java project springboot+redission only, RedisCluster scanInterval 1000ms，jvm create too many HashMap.Node, cause YGC quickly, I see ClusterConnectionManager.java source

private void scheduleClusterChangeCheck(...){
}

   private void checkSlotsChange(cfg, newPartitions) {
       Collection<Integer> newPartitionsSlots = slots(newPartitions); 
      ...
    }

    private Collection<Integer> slots(Collection<ClusterPartition> partitions) {
       // **** create 16384 capacity HashMap.Node ***//
        Set<Integer> result = new HashSet<Integer>(MAX_SLOT);
        for (ClusterPartition clusterPartition : partitions) {
            result.addAll(clusterPartition.getSlots());
        }
        return result;
    }

### 
$ sudo /usr/local/java/jdk/bin/jstat -gc 6623
﻿ S0C    S1C    S0U    S1U      EC	EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
17920.0 19456.0 15506.0  0.0   772608.0 189177.1  165888.0   42155.6   52352.0 51221.4 6528.0 6239.4     14    0.102   2      0.081    0.183
### Expected behavior
null
### Actual behavior  
 num     instances         bytes  class name
   1:       4719787	 151033184  java.util.HashMap$Node
   2:         23692	 118076728  [Ljava.util.HashMap$Node;
   3:        571827	  99347520  [C
   4:        165795	  89233304  [I
   5:       1192658	  19082528  java.lang.Integer
   6:         16348	  16425592  [B
   7:        357968        8591232  java.lang.String
   8:         37014        5820136  [Ljava.lang.Object;
   9:         43160        3798080  java.lang.reflect.Method
  10:         80343        2570976  java.util.concurrent.ConcurrentHashMap$Node
  11:         34579        2213056  java.net.URL
### Steps to reproduce or test case
watch -n1 "sudo /usr/local/java/jdk/bin/jmap -histo pid"
### Redis version
4.0.0+
### Redisson version
3.7.1
### Redisson configuration
// redis-cluster,3M-3S
Config config = new Config();
config.useClusterServers()
    .setScanInterval(1000) 
    .addNodeAddress("redis://127.0.0.1:7001", "redis://127.0.0.1:7002")
    .addNodeAddress("redis://127.0.0.1:7003", "redis://127.0.0.1:7004")
    .addNodeAddress("redis://127.0.0.1:7005", "redis://127.0.0.1:7006")；

RedissonClient redisson = Redisson.create(config);

**Comment by mrniko** [comment]
Fixed
