### ISSUE TITLE
Add CL.THROTTLE command for Redisson Client

### ISSUE THREAD

**Issue by teagy-cr** [redisson/redisson#1492]
I'm using the Redis Cell module for keeping track of rate limits on certain keys. Unfortunately with Redisson this means I have to use the low level client for now but it would be nice to include a method for the CL.THROTTLE command used in Redis Cell module with the high level client.
This is not related to RRateLimiter which to my understanding is for throttling calls to Redis itself.

Redis Cell
https://github.com/brandur/redis-cell

**Comment by jackygurui** [comment]
Quite the contrary, RRateLimiter is a distributed object that uses Redis to throttle other business logics. It currently has two modes and both of which are detailed here: https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RateType.java
