### ISSUE TITLE
Acquire Methods in RedissonRateLimiter Are Not Functional

### ISSUE THREAD

**Issue by teagy-cr** [redisson/redisson#1493]
Issue since Redisson 3.7.1

Line 125 of RedissonRateLimiter.java throws a null pointer exception when the time unit  parameter is null. When you call the acquire methods it passes a null for that parameter. Basic unit tests for the acquire method would have caught this.

` 
@Override
public RFuture<Boolean> tryAcquireAsync(long permits, long timeout, TimeUnit unit) {
        RPromise<Boolean> promise = new RedissonPromise<Boolean>();
        tryAcquireAsync(permits, promise, unit.toMillis(timeout));
        return promise; 
}
`

**Comment by mrniko** [comment]
Fixed! Thanks for report
