### ISSUE TITLE
Redisson Class loading

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1496]
As per my understanding, Redisson serializes the class at the time of scheduling the job and deserializes it at the time of execution of the job. If the class is already in memory at the time of execution of the job  then what does redisson do. 

Kindly explain me this in details and also correct me if my understanding is not correct.

**Comment by mrniko** [comment]
I do agree with you. There is a room to optimize class loading at least for job execution process.

**Comment by arpit728** [comment]
>  If the class is already in memory at the time of execution of the job then what does redisson do?

Since while executing the job redisson will also deserialize the class and load it and also the is already loaded. What will happen in this scenario.

**Comment by mrniko** [comment]
Class is not already loaded since Redisson doesn't store classloader used in task, so it loads it again.

**Comment by arpit728** [comment]
> Class is not already loaded since Redisson doesn't store classloader used in task, so it loads it again.

What do you mean by classloader used in task?

**Comment by mrniko** [comment]
@arpit728 

Each task uses own classloader with lifespan - task execution time.

**Comment by arpit728** [comment]
Suppose my job has dependency on three classes {A,B,C} then does redisson also serializes and deserializes class A, B and C.
