### ISSUE TITLE
How to inject taskId in runnable?

### ISSUE THREAD

**Issue by arpit728** [redisson/redisson#1503]
Since I get `taskId` after scheduling the task, how can I provide `taskId` to the `RunnableTask`, so that I can have `taskId` during execution of task.

**Comment by mrniko** [comment]
Done.

Use RInject and any field with String type.

**Comment by ankitpal11** [comment]
I am not getting  task id that I am sending in schedule task 

  TimerTask task =
                new TimerTask(
                        generateTaskIdentifier(AREQ_TIMER_TASK_IDENTIFIER_KEY, transactionId),
                        this,
                        tracer);
