### ISSUE TITLE
Redisson redlock performance with azure redis cache

### ISSUE THREAD

**Issue by sctest** [redisson/redisson#1505]
Hi I have a distributed application that servers user requests. I want to implement distributed locking to synchronize access to user's data if multiple requests for the same user come in.

I'm using redisson with azure redis cache in cluster mode with 3 masters, 3 slaves for this purpose. My incoming request rate is 700/s, with total request processing times ~30-40ms. I've set the redisson cluster config as below (pool size=320, lock_wait_time=3000ms, lock_expiry_time=3000ms). However, I notice that in spite of tuning the connection pool size from 250-700, a small portion of requests fail while waiting to acquire the lock.

Questions:
1. Is my usage of redisson redlock below correct? 
2. Any recommendations on how I can tune the config to resolve the "failed to acquire lock" errors?
3. The average redisson lock times i'm seeing are ~20-30ms. Is that expected? I also write user data to redis with JedisCluster in the same application and the cache get/set times are ~1-2ms.

**Application algorithm**

//acquire lock (lockname="Lock_"+userid)
//process user's data
//unlock "Lock_"+userid

**My Spring config**

```
<redisson:client
				id="redissonClient"
				name="redissonClient"
				threads="0"
				netty-threads="0"
		>
				<redisson:cluster-servers
				    idle-connection-timeout="10000"
				    ping-timeout="1000"
				    connect-timeout="5000"
				    timeout="3000"
				    retry-attempts="1"
				    retry-interval="1500"
				    password="<my_pwd>"
				    subscriptions-per-connection="0"
				    client-name="none"
				    slave-connection-minimum-idle-size="0"
				    slave-connection-pool-size="0"
				    master-connection-minimum-idle-size="50"
				    master-connection-pool-size="320"
				    read-mode="MASTER"
				    scan-interval="1000"
				>
				    <redisson:node-address value="redis://my_azure_rediscache.windows.net:6379" />
				</redisson:cluster-servers>
		</redisson:client>
```

**Application code snippet for locking**

```
RedissonRedLock redLock = null; 
		RLock rLock = null;
		try
		{
                       String lockName = "Lock_" + userId;
			rLock = redissonClient.getLock(lockName);
			redLock = new RedissonRedLock(rLock);
			if(!redLock.tryLock(3000, 3000, TimeUnit.MILLISECONDS))
			{
	        	throw new MyException("Cannot acquire cache lock for " + lockName);
			}
		}
		catch (InterruptedException e)
		{
			throw new MyException (Lock operation interrupted for " + lockName));
		}
```

Thanks

**Comment by jackygurui** [comment]
You don't need to use RedLock in case you only have 1 RLock.

**Comment by jackygurui** [comment]
> Do I still need to use just RLock and not RedLock?
Yes. I think RLock is what you need.

> Is that incorrect?
No. RedLock uses multiple locks to give you better reliability, meaning each user, in your use case, needs to have a lock on each "shard" to have RedLocks working properly. 

RedLock does not necessarily bounds clusters, although it does work in a cluster environment, it also works in other types of multi-master environments
