### ISSUE TITLE
Mitigating Concurrency Issues 

### ISSUE THREAD

**Issue by CToner3223** [redisson/redisson#1513]
﻿Hi, 

I was wondering what the standard approach is to Mitigate possible Concurrency issues when using Redisson as a spring data source.

I am working on an application that gets information from a source application and then layers updated over the top before delivering the updated information to the client.

The updates in this case are built for several sources, each one has its own queue.

When a new message is placed on any given queue my app reads the message from the queue, and attempts to create or update an updateObject in my redis cache.

My problem stems form the fact that messages are constantly being placed on these queues and updates to the updateObject are likely to come in quick succession.

Im concerned that this will lead to concurrent read write issues:

existing updateObject[id:1, foo:false, bar:false]

msg 1[foo:true]---> get existing updateObject[id:1, foo:false, bar:false]
msg2[bar:true]--> get existing updateObject[id:1, foo:false, bar:false]
msg 1[foo:true]---> update existing updateObject[id:1, foo:true, bar:false]
msg2[bar:true]--> get existing updateObject[id:1, foo:false, bar:true]

resulting updateObject[id:1, foo:false, bar:true]

I have attempted to solve this using @Transactional and the RedissonTransactionManager but it doesn't seem to be halting the second messages update while the first message is still updating.

Any advice would be really appreciated, 
Thank you

**Comment by CToner3223** [comment]
Hi @mrniko, 

Thanks for getting back to me.

The only locking that I can see is during the committing of the transaction, looks like the operations are bundled into a batch update and executed within a semaphore.acquire 

Is that what you mean ?

Thanks

**Comment by mrniko** [comment]
Hi @CToner3223

Are you talking about `RBatch` or `RTransaction` object?

**Comment by CToner3223** [comment]
RTansaction, 

I see now that there is also locking within the TransactionalOperation.commit method

**Comment by mrniko** [comment]
Locking applied on every write operation not only commit method

**Comment by CToner3223** [comment]
is the below correct, or am i misunderstanding ?


message 1 gets picked up <-[id: 123, foo: true, bar: false]
-TransactionStarted-
getCurrentState of id 123 <-[id: 123, foo: false, bar: false]
merge message 1 with currentState <-[id: 123, foo: true, bar: false]
Save <-[id: 123, foo: true, bar: false]
-TransactionEnded-
//engage Lock?
commit Transaction
//disengage Lock?

message 123 is now : [id: 123, foo: true, bar: false]

**Comment by mrniko** [comment]
@CToner3223

Lock aquired during write operation execution not at commit stage:

-TransactionStarted-
getCurrentState of id 123 <-[id: 123, foo: false, bar: false]
merge message 1 with currentState <-[id: 123, foo: true, bar: false]

[Lock acquired by name of object] <<<
Save <-[id: 123, foo: true, bar: false]

-TransactionEnded-

commit Transaction
[Lock released]

**Comment by CToner3223** [comment]
I see, so slightly earlier than I thought.

I don't believe this form of locking is enough to solve my issue. 
I need to the whole transaction to be isolated in a lock so that other operations don't read from redisson while the current one is updating. 

message 1 gets picked (application1)  <-[id: 123, foo: true, bar: false]
-TransactionStarted (application1) -
getCurrentState of id 123 (application1)  <-[id: 123, foo: false, bar: false]

message 2 gets picked (application2)  <-[id: 123, foo: false, bar: true]
-TransactionStarted (application2) -
getCurrentState of id 123 (application2)  <-[id: 123, foo: false, bar: false]

merge message 1 with currentState (application1)  <-[id: 123, foo: true, bar: false]
merge message 2 with currentState (application2)  <-[id: 123, foo: false, bar: true]

[Lock acquired by name of object] (application1) <<<
Save <-[id: 123, foo: true, bar: false] (application1) 
-TransactionEnded (application1) -
commit Transaction (application1) 
[Lock released] (application1)

[Lock acquired by name of object] (application2) <<<
Save <-[id: 123, foo: true, bar: false] (application2) 
-TransactionEnded (application2) -
commit Transaction (application2) 
[Lock released] (application2)  


result : object 123 = [id: 123, foo: false, bar: true]

but logically it should be : [id: 123, foo: true, bar: true]

Does that make sense ?

Thanks again
