### ISSUE TITLE
RMap.readAllValues() returns Number as string

### ISSUE THREAD

**Issue by sheldon-sminq** [redisson/redisson#1516]
﻿### Expected behavior
When we use addAndGetAsync the value of key is incremented or decremented.

### Actual behavior
RMap.readAllValues() should return values as 0-> 1, 1- >2 but instead returns values in the form og
0->"0", 1->"2" where the Number class is a string value.

Iterating through this collection causes a class cast exception.

### Redis version
4.0.10
### Redisson version
3.7.2

**Comment by mrniko** [comment]
Unable to reproduce it with test below, using default codec:

```java
        RMap<String, Integer> mapStr = redisson.getMap("mapStr");
        assertThat(mapStr.put("1", 100)).isNull();

        assertThat(mapStr.addAndGet("1", 12)).isEqualTo(112);
        assertThat(mapStr.get("1")).isEqualTo(112);
        
        Collection<Integer> s = mapStr.readAllValues();
        assertThat(s).contains(112);
```

**Comment by sheldon-sminq** [comment]
@mrniko  i am using SnappyCodec could that be the issue?

**Comment by sheldon-sminq** [comment]
Confirmed issue is because of SnappyCodec, default codec works fine
