### ISSUE TITLE
RedissonRateLimiter acquire() method blocks forever

### ISSUE THREAD

**Issue by teagy-cr** [redisson/redisson#1524]
The acquire method should block until a permit is available, but it blocks indefinitely instead of the remaining time until a new permit becomes available. From my testing I have found that it doesn't acquire a permit when one should be available based on the rate and interval I tested. If I set the rate to 1 every 5 seconds, it should take a loop of 10 single permit acquires approximately 50 seconds to complete. Instead it acquires the first permit, then blocks forever on the next acquires call.

**Comment by mrniko** [comment]
Could you share code to reproduce that?

**Comment by teagy-cr** [comment]
```
@Test
public void testAcquire() {
    RRateLimiter rr = redisson.getRateLimiter("acquire");
    assertThat(rr.trySetRate(RateType.OVERALL, 1, 5, RateIntervalUnit.SECONDS)).isTrue();
    for (int i = 0; i < 10; i++) {
        rr.acquire(1);
    }
    assertThat(rr.tryAcquire()).isFalse();
}
```

This test acquires the first permit in the loop but never returns when the next permit is available.

**Comment by mrniko** [comment]
Fixed
