### ISSUE TITLE
分布式集群如何实现tomcat session共享

### ISSUE THREAD

**Issue by msongs** [redisson/redisson#1525]
一台机器多tomcat实例可以，多台机器不行，请问应该如何实现

**Comment by jackygurui** [comment]
多台机器多tomcat实例的实现方式跟一台机器多tomcat实例情况应该一样。在你提供详细信息以前帮不了你。

**Comment by jackygurui** [comment]
没有新的补充信息，暂时关闭这个帖子。

**Comment by Mayezi** [comment]
您好，我也遇到了这个问题。问题出现在当部署同一个tomcat到多台机器的时候，每台机器分配的session的id是不一致的。

**Comment by jackygurui** [comment]
客户端是怎么被分配到多台机器的？

**Comment by Mayezi** [comment]
> 客户端是怎么被分配到多台机器的？

没太懂您的意思，我分别在两台机器上部署同一套tomcat，tomcat的配置完全一致，在访问其中一台以后，再去访问另外一台机器，对比两个请求的sessionid，发现他们两个的sessionid不一致

**Comment by jackygurui** [comment]
两个tomcat是放在同一个代理后面，然后客户端访问的时候是直接访问代理来实现的？或是两个tomcat是分开独立存在的，客户端分别访问两个不同的tomcat地址来实现的？

**Comment by Mayezi** [comment]
我这边测试的结果如下，
在客户端访问的时候通过代理(nginx)则两台机器的sessionid保持一致，如果不使用代理直接独立进行访问的话则sessionid不一致

**Comment by jackygurui** [comment]
这是正常现象。对于客户端来说，直接独立进行访问两个不同的tomcat相当于访问两个完全不同的网站。一个网站的session信息是不可能传递到其他网站的。如果发生了，这就是很严重的安全问题了。在有代理的情况下，与客户端直接通信的是代理服务器，客户端不会感知到代理服务器后面的结构和变化。对它来讲始终都是同一个网站。

**Comment by taohuangtao** [comment]
肯定是这样啊


 
---原始邮件---
发件人: "张益"<notifications@github.com>
发送时间: 2019年7月10日(星期三) 上午10:45
收件人: "redisson/redisson"<redisson@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [redisson/redisson] 分布式集群如何实现tomcat session共享 (#1525)



我这边测试的结果如下，
 在客户端访问的时候通过代理(nginx)则两台机器的sessionid保持一致，如果不使用代理直接独立进行访问的话则sessionid不一致

**Comment by taohuangtao** [comment]
完全不知道你在说啥。同一个域名下sessionis才会相同啊。


 
---原始邮件---
发件人: "张益"<notifications@github.com>
发送时间: 2019年7月9日(星期二) 下午5:11
收件人: "redisson/redisson"<redisson@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [redisson/redisson] 分布式集群如何实现tomcat session共享 (#1525)


 
客户端是怎么被分配到多台机器的？
  
没太懂您的意思，我分别在两台机器上部署同一套tomcat，tomcat的配置完全一致，在访问其中一台以后，再去访问另外一台机器，对比两个请求的sessionid，发现他们两个的sessionid不一致
