### ISSUE TITLE
why 'readonly' command is going to master everytime i send read operation at ReadMode.Master_Slave

### ISSUE THREAD

**Issue by nakamototavarez** [redisson/redisson#1531]
﻿### Expected behavior

1. 'readonly' command should not go to master everytime i send read operation.
2. 'readonly' command is going to master or slave only onetime at first when making connection.

### Actual behavior
1. 'readonly' command is going to master everytime when i send read operation.
2. because of added 'readonly' command, master is not distributed throughput

### Steps to reproduce or test case
1. make Redissonclient with ReadMode.MasterSlave
2. send read operation 
redissonClient.eval(Mode.ReadOnly, "return redis.call('get', 'something')"...
3. 'monitor' in redis console.
master node=>
'readonly'
[lua] return redis.call('get'.....
slave node =>
[lua] return redis.call('get'.....

### Redis version
4.0.10

### Redisson version
2.12.3  6/28 latest version with java7

### Redisson configuration
AWS elasticache redis cluster enabled
Shard : 1 master / 1 slave
useClusterMode()
ReadMode : Master_Slave
command : eval(Mode.ReadOnly, "return redis.call('get',......

** actually, read operation is distributed propery, but master node get plus 'readonly' command. even though 'readonly' comman is not working at master node and not affecting anything functionally.
however this is big problem which increase throughput and cpu utilization on master node. finally, it is same as not distributed

**Comment by mrniko** [comment]
Use `Config.readMode` param to control read operation execution whether master or slave.

**Comment by nakamototavarez** [comment]
i already used readMode with Master_Slave

Config config = new Config();
            config.setCodec(new StringCodec());
            config.useClusterServers()
                  .setScanInterval(2000)
                  .addNodeAddress(clusterNodesAddress)
                  .setReadMode(ReadMode.MASTER_SLAVE);
            changedRedissonClient = Redisson.create(config);

the point of problem is when sending a query with eval(Mode.READ_ONLY...., query go to master and slave as Roundrobin, but when query go to master, monitor log like below 
'readonly'
 [lua] return redis.call('get'.....
this means 'readonly' needless command also go to master.
2 query go to master.
please deleting 'readonly' query....

**Comment by mrniko** [comment]
Fixed. This issue also revealed more serious one https://github.com/redisson/redisson/issues/1550

**Comment by mrniko** [comment]
Fixed. This issue also revealed more serious one https://github.com/redisson/redisson/issues/1550

**Comment by nakamototavarez** [comment]
Thanks
