### ISSUE TITLE
severe bug !! when sending read operation to new slave loading previous data after failover

### ISSUE THREAD

**Issue by nakamototavarez** [redisson/redisson#1534]
﻿### Expected behavior

### Steps to reproduce or test case
- ReadMode : Slave 
- userClusterServer
- ElastiCache Redis Cluster Enabled. 
- 1 Master / 1 Slave 

SourceCode------------------------------------------------------------
* i make RedissClient when servlet server start up at frist like below.
* i store redissonClient to static variable.

Config config = new Config();
config.setCodec(new StringCodec());
config.useClusterServers()
          .setScanInterval(2000)
          .addNodeAddress(clusterNodesAddress)
          .setReadMode(ReadMode.SLAVE);
redissonClient = Redisson.create(config);

* on each servlet request, i send read command like below to redis, in this case, it is problem. 
result = redissonClient.getScript().eval(Mode.READ_ONLY, script, RScript.ReturnType.VALUE), keyList, argvList.toArray());

* on each servlet request, i send read or write command like below to redis,  in this case, it is ok 
result = redissonClient.getScript().eval(Mode.READ_WRITE, script, RScript.ReturnType.VALUE), keyList, argvList.toArray());
--------------------------------------------------------------------------
1. send read operation each reqeuest on servlet server continusly.
2. read operation is going slave well
3. start failover. 
4. master redis is down.
5. occured error for 60 seconds. 
6. slave is changed to master. 
7. 'cluster nodes' info is changed 1 master.  no slave.
8. redisson recognize changed master correctly and read from master instedad of slave. 
9. read operation is going master well.
10. previous down master is up as slave.
11. 'cluster nodes' info is changed 1 master and 1 slave.
11. redisson recognize new slave
------------------problem is started.
12. slave is loading data for syncing with master. it takes 10 minutes to load all data completely.
13. during 10 minutes, servlet server is going strange behavior and throuput is very lower and don't return any exception. i think some threads is hanging around Redisson connection with new slave loading data.
14. actually i expected returning error with timeout. why it is not returning any error until slave is completed loading data.
15. after 10 minutes which completed load data from slave. it is going back to normal and throuput become higer. 
16.  however, read operation with Mode.ReadOnly is going both master and slave not going to slave only.

* problem.
1. when loading data at slave, redisson is sending read operation to slave. and read opeartion thread is hanging aroud somewhere in redisson.
2. read operation with Mode.ReadOnly is going well to slave only. however after failover, read operation is going both master and slave not going to slave only.

### Redis version
4.0.10

### Redisson version
java 7 latest version 2.12.3 

### Redisson configuration
- ReadMode : Slave 
- userClusterServer
-ElastiCache Redis Cluster Enabled. 
- 1 Master / 1 Slave 
- default options

**Comment by nakamototavarez** [comment]
now i actually avoid this problem.  
i changed method eval(...) --> evalAsync(...) and timeout setting
RFuture<Object> future = redissonClient.getScript().evalAsync(...)
result = future.get(1000, TimeUnit.MILLISECONDS);
this produce TimeoutException when slave load previous bulk data from master.
so, i am planning to make source code on server application which
when exception is occured, i change ReadMode.ReadOnly->ReadWrite
and change ReadWrite -> ReadOnly enough after 1 hour.
even though i avoid slave read problem when loading data, 
there are still problem which query is going to master and slave on ReadOnly Mode. 
so i should create new RedissonClient Object and swap with old RedissonClient Object after 1 hour exception occured.

@mrniko, are you thinking about this is good solution?

of course, 
hopefully, i want 2.12.4 version resolve this problem and upgraded.

**Comment by nakamototavarez** [comment]
i found 1 more bug. 
i run redisson with 2 master / 2 slave, i send query as ReadMode.ReadOnly, but it is just going query to master1, master2, slave2. and query never go to slave1 when ReadMode.ReadOnly. 

when i send query evla("return redis.call('cluster', 'nodes')".... )
it return correctly like below.

14341a4223dda630fabee5082f64da0ff51a5421 11.11.31.34:3001@1122 myself,master - 0 1531225644000 26 connected 0-8191;2d2650f3eea805ed40ae6d13afd1bcf7bce80a90 11.11.34.163:3001@1122 master - 0 1531225646979 25 connected 8192-16383;a71c6b0e2d50866c0e6c1688e6db4c640154d68b 11.11.35.214:3001@1122 slave 14341a4223dda630fabee5082f64da0ff51a5421 0 1531225645974 26 connected;83f0af561eb81d7b90e2ea4ee1e08994835b6b1a 11.11.35.237:3001@1122 slave 2d2650f3eea805ed40ae6d13afd1bcf7bce80a90 0 1531225645000 25 connected

and i saw log when connection is made like below. 
i think log is correct. redisson recognize 2 master and 2 slave correctly 
but it do not send read query to slave2. 

12:17:27,075 ERROR [stderr] (ServerService Thread Pool -- 48) 333 [ServerService Thread Pool -- 48] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from pocformonkey.xxxxxx.cache.amazonaws.com/11.11.31.34:3001:
12:17:27,076 ERROR [stderr] (ServerService Thread Pool -- 48) 14341a4223dda630fabee5082f64da0ff51a5421 11.11.31.34:3001@1122 myself,master - 0 1531225045000 26 connected 0-8191
12:17:27,076 ERROR [stderr] (ServerService Thread Pool -- 48) 2d2650f3eea805ed40ae6d13afd1bcf7bce80a90 11.11.34.163:3001@1122 master - 0 1531225045265 25 connected 8192-16383
12:17:27,077 ERROR [stderr] (ServerService Thread Pool -- 48) a71c6b0e2d50866c0e6c1688e6db4c640154d68b 11.11.35.214:3001@1122 slave 14341a4223dda630fabee5082f64da0ff51a5421 0 1531225042248 26 connected
12:17:27,077 ERROR [stderr] (ServerService Thread Pool -- 48) 83f0af561eb81d7b90e2ea4ee1e08994835b6b1a 11.11.35.237:3001@1122 slave 2d2650f3eea805ed40ae6d13afd1bcf7bce80a90 0 1531225046271 25 connected
12:17:27,078 ERROR [stderr] (ServerService Thread Pool -- 48) 
12:17:27,138 ERROR [stderr] (redisson-netty-1-5) 396 [redisson-netty-1-5] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://11.11.35.214:3001] added for slot ranges: [[0-8191]]
12:17:27,145 ERROR [stderr] (redisson-netty-1-1) 400 [redisson-netty-1-1] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://11.11.35.237:3001] added for slot ranges: [[8192-16383]]
12:17:27,184 ERROR [stderr] (redisson-netty-1-5) 441 [redisson-netty-1-5] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 11.11.34.163/11.11.34.163:3001
12:17:27,208 ERROR [stderr] (redisson-netty-1-6) 466 [redisson-netty-1-6] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 11.11.35.214/11.11.35.214:3001
12:17:27,209 ERROR [stderr] (redisson-netty-1-3) 467 [redisson-netty-1-3] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 11.11.31.34/11.11.31.34:3001
12:17:27,210 ERROR [stderr] (redisson-netty-1-4) 467 [redisson-netty-1-4] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 11.11.35.237/11.11.35.237:3001
12:17:27,222 ERROR [stderr] (redisson-netty-1-7) 479 [redisson-netty-1-7] INFO org.redisson.connection.pool.MasterConnectionPool - 32 connections initialized for 11.11.34.163/11.11.34.163:3001
12:17:27,222 ERROR [stderr] (redisson-netty-1-5) 479 [redisson-netty-1-5] INFO org.redisson.connection.pool.MasterConnectionPool - 32 connections initialized for 11.11.31.34/11.11.31.34:3001
12:17:27,320 ERROR [stderr] (redisson-netty-1-7) 577 [redisson-netty-1-7] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://11.11.34.163:3001 added for slot ranges: [[8192-16383]]
12:17:27,325 ERROR [stderr] (redisson-netty-1-5) 583 [redisson-netty-1-5] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://11.11.31.34:3001 added for slot ranges: [[0-8191]]
12:17:27,328 ERROR [stderr] (redisson-netty-1-4) 586 [redisson-netty-1-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 32 connections initialized for 11.11.35.237/11.11.35.237:3001
12:17:27,329 ERROR [stderr] (redisson-netty-1-5) 586 [redisson-netty-1-5] INFO org.redisson.connection.pool.SlaveConnectionPool - 32 connections initialized for 11.11.35.214/11.11.35.214:3001

**Comment by mrniko** [comment]
`Mode.ReadOnly` doesn't mean that request go to slave only, but means script doesn't contain data modification commands.

**Comment by mrniko** [comment]
> when loading data at slave, redisson is sending read operation to slave. and read opeartion thread is hanging aroud somewhere in redisson.

Could you set logging level to `TRACE` and show log output recorded during that moment?

**Comment by mrniko** [comment]
> hopefully, i want 2.12.4 version resolve this problem and upgraded.

Seems it's time to refactor `RScript` interface and introduce `evalRead` and `evalWrite` methods instead of Mode param. I'm going to work on it in nearest version.

**Comment by nakamototavarez** [comment]
however, 
even though Mode.ReadOnly doesn't mean that request go to slave only,
i configured RedissonClient with ReadMode : Slave,
so i think it should go to slave only because it is just Read Query. 

at the first time, i configured RedissonClient with ReadMode : Master_Slave.
but the same thing is happnning

**Comment by mrniko** [comment]
Could you check it against 2.12.5 version?

**Comment by mrniko** [comment]
> during 10 minutes, servlet server is going strange behavior and throuput is very lower and don't return any exception. i think some threads is hanging around Redisson connection with new slave loading data.

Fixed! Thanks for report
