### ISSUE TITLE
org.redisson.RedissonShutdownException: Redisson is shutdown

### ISSUE THREAD

**Issue by surersen** [redisson/redisson#1537]
﻿### 配置信息
1, lib/
redisson-all-2.11.3.jar

redisson-tomcat-7-2.12.0.jar 

![image](https://user-images.githubusercontent.com/12604070/42483656-57a50b04-8421-11e8-94a3-d632352dc15f.png)

2,conf/content.xml

![image](https://user-images.githubusercontent.com/12604070/42483744-d8925334-8421-11e8-94b5-5386f6d9476c.png)

3,conf/redisson.json

![image](https://user-images.githubusercontent.com/12604070/42483757-f1230d1c-8421-11e8-973b-9dec8720064a.png)

###  项目在tomcat 部署后，系统正常启动
![image](https://user-images.githubusercontent.com/12604070/42483838-71f2e64c-8422-11e8-8fad-63fb6999cb38.png)

### 如果在执行reload 功能后，前端再调用后台服务时error发生了。

![image](https://user-images.githubusercontent.com/12604070/42483871-b7377ac4-8422-11e8-886f-1c602f32b4b3.png)

**Comment by sailsgo** [comment]
遇到同样的问题？是什么原因

**Comment by syoukaihou** [comment]
遇到同样的问题？是什么原因
