### ISSUE TITLE
aliyun redis not support

### ISSUE THREAD

**Issue by zhengzc** [redisson/redisson#1538]
﻿### Expected behavior

### Actual behavior
when i use redissonClient.getMapCache，put any key. get error :ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. only in aliyun redis.

aliyun redis must uses KEYS array in lua. Can you give me some suggestions？
### Redisson version
2.12.3
### Redisson configuration

**Comment by mrniko** [comment]
Hmm, why did they introduce such requirement? All lua scripts needs to be revised.

**Comment by mrniko** [comment]
I have checked lua script of `RedissonMapCache.putOperationAsync` method, you complaining for, but didn't find any key set through non-KEYS params.

**Comment by jackygurui** [comment]
It may have something to do with the proxy in the cluster setup developed by Aliyun.
![tb1yscnqpxxxxxrxfxxxxxxxxxx-1530-1140](https://user-images.githubusercontent.com/2514975/42625597-11a29efa-85c0-11e8-8989-ec087208ea8d.png)

Talking to their developers now and see what options we have.

**Comment by jackygurui** [comment]
@zhengzc Can you provide your aliyun instance ID?

**Comment by flowly** [comment]
@zhengzc u can use aliyun sperate read write instance, it will not check the lua scripts, or u can provide the aliyun instance id we can solve this problem

**Comment by jackygurui** [comment]
@mrniko Now I understand this is an Aliyun protection feature rather than an issue. It is used to stop users from sending cross slot keys in Lua to proxy nodes. However this is unnecessary for Redisson, such feature can be turned off the protection via the admin console. Redisson should then work as expected. 

@zhengzc We have Aliyun engineer @flowly here to help, please follow his advice and try it again.

**Comment by zhengzc** [comment]
@jackygurui @mrniko thank you！I will contact @flowly  with dingding. thank you very much!

@flowly 能不能告诉我你的花名？或者直接在钉钉上联系我（郑志超）谢谢！

**Comment by flowly** [comment]
花名: 白宸

**Comment by xiaoshayun** [comment]
你好,这边使用阿里云的redis的时候也出现了这个问题,请问最后怎么解决的呢?

**Comment by xy83918** [comment]
![image](https://user-images.githubusercontent.com/2715268/92126769-26ce0480-ee33-11ea-8130-cd7ea23ac79e.png)

**Comment by Caratacus** [comment]
楼上正解

**Comment by StackTc** [comment]
> 楼上正解，修改阿里云redis中script_check_enable参数为0即可解决该问题。

这个参数只是去掉阿里云对lua的校验吧？ 如果多个key不在一个slot下面，进行lua脚本会发生什么样的错误呢
