### ISSUE TITLE
求个demo跟springmvc整合的例子，这边应用集群部署操作redis里面的数据

### ISSUE THREAD

**Issue by zhangzhepu** [redisson/redisson#1540]
﻿### Expected behavior
自己加进去一直锁不住，看下哪里有问题么

	@RequestMapping(value="/testLock")
	@ResponseBody
	public Object testLock(){
		String name = "rMap";
		RMap<String, Integer> intMap = redissonService.getRMap(name);
		RLock lock = redissonService.getRLock(name);
		try{
			// 1. 最常见的使用方法
			//lock.lock();
			// 2. 支持过期解锁功能,10秒钟以后自动解锁, 无需调用unlock方法手动解锁
			//lock.lock(10, TimeUnit.SECONDS);
			// 3. 尝试加锁，最多等待3秒，上锁以后10秒自动解锁
			boolean res = lock.tryLock(3, 10, TimeUnit.SECONDS);
			if(res){ //成功
				Integer num = intMap.get("num");
				if(num==null){
					num=0;
				}else{
					num++;
				}
				System.out.println(" 写入 "+intMap. putIfAbsent("num", num));
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		} finally {
			lock.unlock();
		}
		System.out.println(intMap.get("num"));
		return intMap;
	}

**Comment by jackygurui** [comment]
命名冲突了

**Comment by zhangzhepu** [comment]
@jackygurui 你好  可以加个qq吗，有些疑问请教一下您

**Comment by jackygurui** [comment]
你的QQ号是多少？
