### ISSUE TITLE
LiveObjectService - ClassCastException when using multiple ClassLoaders

### ISSUE THREAD

**Issue by Aqu1nt** [redisson/redisson#1545]
﻿### Expected behavior
RedissonLiveObjectService creates proxy objects that are `instanceof` the given entity class.

### Actual behavior
When using a different ClassLoader when loading the Class-To-Proxy for an LiveObject than when loading the Redission library all proxies creations will throw a `ClassCastException`.

```
Caused by: java.lang.ClassCastException: ch.aquint.MyLiveObject$ByteBuddy$EG1hQiP9 cannot be cast to ch.aquint.MyLiveObject
        at ch.aquint.MyService.initService(MyService.java:20) ~[main/:na]

```

**This is most likely due to the line.** https://github.com/redisson/redisson/blob/46e8e8846a260999b6706e331b40943de0ffb813/redisson/src/main/java/org/redisson/RedissonLiveObjectService.java#L693
I think redission should use `entityClass.getClassLoader()` instead to make sure that the generated proxy object will be assignable to the given entity class.
(As soon as `spring-boot-devtools` is removed from the classpath and there is only 1 ClassLoader around everything works perfectly fine)

### Steps to reproduce or test case
I've created a minimal repository that shows the error simply by running `./gradlew run` in the project.
[https://github.com/Aqu1nt/redission-classcastexception](url)  

If [https://github.com/Aqu1nt/redission-classcastexception/blob/master/build.gradle#L18](url) is removed everything works fine.

### Redis version
4.0.10

### Redisson version
3.7.3

### Redisson configuration
```java
@Bean
public RedissonClient redissonClient() {
  return Redisson.create();
}
```

**Comment by mrniko** [comment]
Fixed. Could you test it with latest version from `3.0.0` branch?

**Comment by Aqu1nt** [comment]
Hi, thanks for the quick response.
I just tried it with the `3.0.0` branch and the issue seems fixed. 👍

**Comment by mrniko** [comment]
Thank you!
