### ISSUE TITLE
Redisson threw MOVED redirection loop detected

### ISSUE THREAD

**Issue by pso2yui** [redisson/redisson#1548]
﻿### Expected behavior
node redirect normally
### Actual behavior
![image](https://user-images.githubusercontent.com/23494400/42741763-b19383fa-88e7-11e8-8d83-84d1d3713510.png)

### Steps to reproduce or test case
I updated redisson from 3.6.3 to 3.7.3, and use RLock for distribution system, It had no problem when it was in 3.6.3, but now it threw a exception above.
Feel sorry I have no idea how to reproduce manually. It ran a while and then the exception threw.
### Redis version
3.2.11
### Redisson version
3.7.3
### Redisson configuration
I used ClusterServersConfig as cluster mode configuration by default with just setting scanInterval property.

**Comment by jackygurui** [comment]
Can you print out the cluster info from redis-cli?

**Comment by pso2yui** [comment]
Sorry, I didnt store a snapshot when this exception occured. Can it be ok I snaped just now?
![image](https://user-images.githubusercontent.com/23494400/42792950-5461dac4-89aa-11e8-9a87-a6d6b532eb62.png)

**Comment by jackygurui** [comment]
What I am trying to point out is, this is not a Redisson issue, it is an error reported by Redis Cluster. You need to review the cluster setup when you see this error again.

**Comment by JunjianS** [comment]
@jackygurui  hello , i have the same problem, but redis cluster is running well.

**Comment by jackygurui** [comment]
@JunjianS can you start a new thread?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/pull/1835
