### ISSUE TITLE
RBucket 不能新增数据

### ISSUE THREAD

**Issue by shaopro** [redisson/redisson#1559]
RBucket 是否对 key 长度有限制？
-------------------------------------------------------------------------------------------------
    private static RedisConfig config = new RedisConfig();
    private static RedissonClient redisson = config.getRedisson();
    private static String key1 = "200201:";
    private static String key2 = "460021261799243";
    public static void main(String[] args) {
        RBucket<String> data = redisson.getBucket(key1 + key2);
        data.set("data");
        redisson.shutdown();
    }

### Expected behavior
能够新增数据

### Actual behavior
key2为4600时候可以新增数据

### Redis version
3.2.11
### Redisson version
3.6.5

**Comment by jackygurui** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/2514975/43072555-5badbffa-8e6e-11e8-85d3-283b0bdf8b5a.png">

Can't reproduce it.

**Comment by shaopro** [comment]
我是用 keys *  在 redis 客户端中找不到这个数据，redis 版本:3.2.11，redisson 版本:3.6.5

**Comment by jackygurui** [comment]
集群环境中出问题有可能是你执行keys *的节点不对

**Comment by shaopro** [comment]
keys *是在所有的节点执行了操作。
redis 版本:3.2.11，redisson 版本:3.6.5 集群模式时候 ，发现是有的数据能存储有的不能。
redis 切换4.0.10 ，redisson 切换到3.7.5，目前测试来看没有发现类似问题。
