### ISSUE TITLE
How to get All the Keys from org.redisson.jcache.JCache

### ISSUE THREAD

**Issue by stkggit** [redisson/redisson#1562]
I had implemented cache as per jsr107 by using Redission. 
Can you please guide How can i get All the Keys (Complete set of Keys)from JCache.

Thanks,

**Comment by stkggit** [comment]
Can anyone Help me in this regard

**Comment by mrniko** [comment]
You could use `javax.cache.Cache.iterator` method

**Comment by stkggit** [comment]
Hi Nikita Koksharov,

Thank you so much for your replay. 

I can Use Iterator but it will take more time to iterate  each entry for capturing the key.
is there any other way to do this. 

Tried with client.getMap() it is taking less time.

For the region with  39450 keys

Iterator approach took  6301 ms
rmap.keySet() took 1377 ms

Here my concern is when i use rmap.keySet() i need a new client, i can't use the client in jcahe. Can you Please Suggest any other approach for this.

Please find my code snippet for getting keys in both below.

public List<String> getKeysItr(String region) {
		List<String> keys = new ArrayList<String>();
		Cache<String, Serializable> cache = getCache(region);
		Iterator<Cache.Entry<String, Serializable>> itr = cache.iterator();
		Cache.Entry<String, Serializable> entry = null;
		while(itr.hasNext()){
			entry = itr.next();
			keys.add(entry.getKey());
		}
		return keys;
	}
	
	public List<String> getKeys(String region) {
		RedissonClient client = mizeRedisCacheRedissonManager.getRedissonClient();
		Cache<String, Serializable> cache = getCache(region);
		RMap<String, Serializable> rmap = client.getMap(cache.getName());
		return (rmap != null) ? new ArrayList<String>(rmap.keySet()) : null;
	}

Thanks in advance.
