### ISSUE TITLE
Redis node failover triggers 30x spike in Commands to the failover shard (using RBatch object)

### ISSUE THREAD

**Issue by EXPEbdodla** [redisson/redisson#1567]
Redis node failover triggers 30x spike in Commands to the failover shard

Additional Description: We have Elasticache cluster with 2 shards* 6 nodes in each shard. Whenever a node failover occurs, the commands (HashCommands) that shard processes increases by 30x (For ex: ). No change in the incoming requests to service but the request/ commands processed by Redis goes up by 30x. Once we redeploy service, Redis commands to that shard will come to normal state. 

Updated redisson client to latest version. With redisson client update, we are seeing a performance hit. Latencies are increased by 25%. We haven't verified whether the issue is happening in latest version or not. 

Appreciate any inputs to debug what's happening here. 

Expected behavior: Failover should be handled gracefully

Actual behavior: Failover leads to increase in traffic to Redis

Steps to reproduce or test case:
1) Failover Primary in one of the shard

Redis version: AWS Elasticache Redis 3.2.10

Redisson version: 2.8.2

Redisson configuration:
ScanInterval: 30000
ReadMode: Slave
Load Balancer: Round Robin
timeout: 1000
cluster mode: true

**Comment by mrniko** [comment]
> With redisson client update, we are seeing a performance hit. Latencies are increased by 25%. 

Can you provide some test case to reproduce this?

**Comment by EXPEbdodla** [comment]
Thanks @mrniko for looking into the issue. 
During this process we are not doing any writes. I'll verify the spikes issue in latest Redisson version and update thread. 

Regarding Latency increase, i'll provide additional details.

**Comment by EXPEbdodla** [comment]
@mrniko , Updated Redisson client to 2.12.5 and did the AWS Elasticache Redis node failover. I still see the problem. As i mentioned, we are only doing the reads. 

Refer attached image for Engine CPU Utilization before and after Failover: 
![image](https://user-images.githubusercontent.com/13788369/44290955-3bc9a200-a230-11e8-8ec0-b1c6141d8c49.png)

Refer attached image for change in the incoming requests for Redis (no changes to incoming requests to our service): 
![image](https://user-images.githubusercontent.com/13788369/44290972-50a63580-a230-11e8-8477-19fa60abeb5b.png)

So i can say that this issue is not fixed in the latest version of Redisson library. If i redeploy my service, the Redis CPU utilization and incoming requests will become normal.  

I'm working on getting information about latencies. i'll post that soon.

**Comment by EXPEbdodla** [comment]
Reads are HMGET's. Sample code is below

String elasticacheConfigurationEndpoint = "redis://**********.clustercfg.usw2.cache.amazonaws.com:6379";
        Config config = new Config();
        config.setCodec(new StringCodec());
        config.useClusterServers()
                .setScanInterval(30000)
                .setReadMode(ReadMode.valueOf(readMode))
                .setLoadBalancer(new RoundRobinLoadBalancer())
                .setTimeout(redisTimeout)
                .addNodeAddress(elasticacheConfigurationEndpoint);
        RedissonClient redissonClient = Redisson.create(config);

public List<List<String>> batchHmget(List<RedisHmGet> keyFields) throws Exception {
        List<List<String>> results = new ArrayList<>(keyFields.size());
        List<RFuture<Map<String,String>>> futures = new ArrayList<>();
        RBatch rBatch = redissonClient.createBatch();
        for(RedisHmGet hmget : keyFields) {
            RMapAsync<String, String> map = rBatch.getMap(hmget.getKey());
            futures.add(map.getAllAsync(new HashSet<>(hmget.getFields())));
        }
        rBatch.execute();

        for(int i=0;i<keyFields.size();i++){
            List<String> fields = keyFields.get(i).getFields();
            List<String> result = new ArrayList<>(fields.size());
            Map<String, String> resultMap = futures.get(i).get();
            for(String field : fields) {
                if(resultMap == null) {
                    result.add(null);
                } else {
                    result.add(resultMap.get(field));
                }
            }
            results.add(result);
        }
        return results;
    }

**Comment by mrniko** [comment]
Thanks for the provided details.

> did the AWS Elasticache Redis node failover

Was failover on master or slave node?

**Comment by EXPEbdodla** [comment]
Failover on Master.

**Comment by mrniko** [comment]
Hi @EXPEbdodla 

Thanks for the benchmark results! Could you share your performance test code?

**Comment by EXPEbdodla** [comment]
Hi @mrniko 
I haven't written anything specific for this performance test. Our service will log Redis Retrieval times for each request. Our application uses same code as i shared above to retrieve data from Redis.

**Comment by EXPEbdodla** [comment]
@mrniko It happens for me almost everytime i do the failover. Sometimes after an hour it comes to normal. Sometimes it will continue to receive 30x+ traffic until i redeploy service. Have couple of questions
1. Did you check it with Elasticache in Cluster mode? 
2. Is the Redis cluster taking traffic when the failover triggered?
3. Is it possible to share the test code used?

**Comment by mrniko** [comment]
I confirm, it's a bug. I have finally reproduced it!

**Comment by EXPEbdodla** [comment]
Thanks @mrniko for confirming request spikes during failover as a bug. 

Are you able to reproduce performance issue with latest version?

**Comment by mrniko** [comment]
@EXPEbdodla 
Failover fixed.

**Comment by mrniko** [comment]
Got around 15% performance boost. Also try to set referenceEnabled = false.

**Comment by EXPEbdodla** [comment]
@mrniko Thanks a lot for your action on this. 
How can i test it? Is there any planned release?

**Comment by mrniko** [comment]
@EXPEbdodla 

`referenceEnabled` setting turns on support for reference objects, like RBucket objects stored in RList.

3.8.0 has been released

**Comment by EXPEbdodla** [comment]
@mrniko I'm testing this version now and able to reproduce this issue..

**Comment by mrniko** [comment]
I'll recheck it.

**Comment by mrniko** [comment]
Here is my result with 3.10.1
![image](https://user-images.githubusercontent.com/1104661/51672985-ed3de200-1fdd-11e9-8641-34e5c6eb7b11.png)

![image](https://user-images.githubusercontent.com/1104661/51672990-f464f000-1fdd-11e9-98c4-27d2d6e388f2.png)

**Comment by EXPEbdodla** [comment]
Thanks for checking @mrniko . I'll recheck again on my end and share the details.

**Comment by EXPEbdodla** [comment]
@mrniko I'm able to reproduce it. Redisson version 3.10.1

![image](https://user-images.githubusercontent.com/13788369/51781009-7c272900-20c8-11e9-9713-c374b1325aa2.png)

![image](https://user-images.githubusercontent.com/13788369/51781012-80534680-20c8-11e9-9347-89ae608107ba.png)

Please let me know if you need any additional details.

**Comment by mrniko** [comment]
@EXPEbdodla can you share your test case?

**Comment by EXPEbdodla** [comment]
@mrniko Stress runs are with same request which retrieves 12000 keys (12000 keys = 200 hashes* 60 fields in each hash) per request from Redis with load of 30 constant users for 90 mins. I'm initiating failover on one of the shard after 15 mins of load.

**Comment by EXPEbdodla** [comment]
@mrniko During the failover we also observed that, application (deployed on ECS with auto scaling) health is dropped to 0% when the failover node joins back to the Redis cluster. After ~1 min application health to 0%, auto scaling bring back the application containers. Now things are normal. 

Error we observed in application logs:

DateTime=2019-01-28 19:08:24,008 Application=hops-service Thread=[redisson-netty-1-7] Logger=io.netty.channel.DefaultChannelPipeline Type=WARN An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.util.concurrent.CancellationException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.redisson.misc.RedissonPromise.cancel(RedissonPromise.java:239)
	at org.redisson.command.CommandBatchService$12.run(CommandBatchService.java:830)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	... 1 more

**Comment by mrniko** [comment]
@EXPEbdodla 

> https://github.com/redisson/redisson/issues/1567#issuecomment-458276080

Which Redisson version did you use?

**Comment by EXPEbdodla** [comment]
@mrniko Redisson version is 3.10.1

**Comment by mrniko** [comment]
What is the data amount stored in Redis?

**Comment by EXPEbdodla** [comment]
@mrniko Dataset size is around 120GB.

**Comment by mrniko** [comment]
@EXPEbdodla 

Could you help to test my fix with snapshot below?

[redisson-2.15.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/2821866/redisson-2.15.2-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
@EXPEbdodla 

Please note, that once slave has back online it synced with master, so copying 120Gb of data from master to slave will take a time. My bug fix will avoid threads to hang in this case.

**Comment by EXPEbdodla** [comment]
@mrniko I'll test it and update you. 

120GB is the total data size. Cluster is about 200GB. Each shard holds 20GB maximum (total 10 shards).

**Comment by dbhargav006** [comment]
@mrniko Sorry for delay on the update. I'm working on loading the snapshot to our Repository. Is it possible for you to push the snapshot to maven so i can use this directly?

**Comment by EXPEbdodla** [comment]
@mrniko Sorry for the delay. I can test the next version quickly now. 

I'm able to test the 3.10.2-SNAPSHOT jar. Failover doesn't trigger the incoming Redis request spikes now. But the other problems that i observed are 
1. Service health is degrades to 0 healthy nodes after initiating failover. Error in application logs is
[Redisson-Error2.txt](https://github.com/redisson/redisson/files/2863017/Redisson-Error2.txt)

2. When the failover node joins the cluster, requests are going to the node that is in the sync state. Error during that period is

[Redisson-Error3.txt](https://github.com/redisson/redisson/files/2863016/Redisson-Error3.txt)

Please let me know if you need any additional details.

**Comment by mrniko** [comment]
@EXPEbdodla 

Thanks for your feedback!

First problem - buffer leak was fixed in https://github.com/redisson/redisson/commit/483ac35f6d4848752fc80d1848c255ad00486c2b

Could you re-check it with 3.10.2 release version?

Second problem is a error arise during master slave sync process.

**Comment by EXPEbdodla** [comment]
@mrniko  Thanks for the update. 

Tested 3.10.2 version. I'm not able to reproduce the spike issue anymore. 

But as discussed earlier, average performance of data retrieval is increased by 100ms. We are using ECS containers. Is there any ideal thread count and netty thread count i can use for containers instead of default values set?

Appreciate any additional information on ThreadCount and NettyThreadCount. How they impact?

**Comment by mrniko** [comment]
@EXPEbdodla 

https://github.com/redisson/redisson/wiki/2.-Configuration#nettythreads is used in response decoding. Increasing this value can help to scale Redis response decoding process. 

Could you also try this version?
[redisson-3.10.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/2879237/redisson-3.10.3-SNAPSHOT.jar.zip)
It contains fix for regression in command decoder.

**Comment by dbhargav006** [comment]
@mrniko Tested the 3.10.3-SNAPSHOT, the performance gain is around 10ms only. But the version change from 2.8.2 to 3.10.2 increased the latency by ~100%

**Comment by mrniko** [comment]
@dbhargav006 

Try to set `config.setReferenceEnabled(false)`

**Comment by mrniko** [comment]
@dbhargav006 

Do you use the same test case as https://github.com/redisson/redisson/issues/1567#issuecomment-414008932 ?

**Comment by dbhargav006** [comment]
@mrniko sorry for confusion. @EXPEbdodla  is my organization account. @dbhargav006 is my personal account. I wasn't observing that i'm posting with my personal account.

I tried config.setReferenceEnabled(false). It doesn't boost the performance as expected.

**Comment by mrniko** [comment]
I fixed performance regression of RBatch result object decoding https://github.com/redisson/redisson/issues/1925

Please try new snapshot version below:
[redisson-3.10.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/2884573/redisson-3.10.3-SNAPSHOT.jar.zip)
