### ISSUE TITLE
can we have an extra API on getNodesGroup

### ISSUE THREAD

**Issue by brother-fu** [redisson/redisson#1568]
currently in [Redissn](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/Redisson.java#L645) class, we have the following API
`public NodesGroup<Node> getNodesGroup()`

in [RedisNodes](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedisNodes.java) class, we have both
```
    public Collection<N> getNodes(NodeType type) 
    public Collection<N> getNodes() 
```
can we expose an extra endpoint in Redisson class where we can get only certain Node type like Master?

the request comes up when we are doing healthz check on our system, our system uses healtzh hook which deletes to redisson to check the health status of redis, currently, what we are doing is `redisson.getNodesGroup().pingAll()`
which is not optimal, we would like the system to still work properly even when one slave is down, can we expose an extra API on this ?

**Comment by mrniko** [comment]
you can do that in follow way:
```java
Collection<Node> nodes = getNodes(NodeType.MASTER);
for (Node node : nodes) {
      nodes.ping();
}
```
