### ISSUE TITLE
RMapCache's addListener  become invalid

### ISSUE THREAD

**Issue by xiaojie0505** [redisson/redisson#1572]
I have two redis in one virtual ip by keepalived，and I use RMapCache's addListener monitor data change
### Expected behavior
     everytime datachange can notify me
### Actual behavior
   from sometime，datachange no longer notify me 
### Redisson configuration  
                Config config2 = new Config();
                config2.useSingleServer().setAddress("redis://" + redisAddress).setDatabase(1);
                config2.setNettyThreads(1);
                config2.setThreads(1);

**Comment by mrniko** [comment]
Unable to reproduce
