### ISSUE TITLE
Continuation to the Issue # 1562 (How to get All the Keys from org.redisson.jcache.JCache)

### ISSUE THREAD

**Issue by stkggit** [redisson/redisson#1573]
Hi Nikita Koksharov,

Thank you so much for your replay.

I can Use Iterator but it will take more time to iterate each entry for capturing the key.
is there any other way to do this.

Tried with client.getMap() it is taking less time.

For the region with 39450 keys

Iterator approach took 6301 ms
rmap.keySet() took 1377 ms

Here my concern is when i use rmap.keySet() i need a new client, i can't use the client in jcahe. Can you Please Suggest any other approach for this.

Please find my code snippet for getting keys in both below.

public List getKeysItr(String region) {
List keys = new ArrayList();
Cache<String, Serializable> cache = getCache(region);
Iterator<Cache.Entry<String, Serializable>> itr = cache.iterator();
Cache.Entry<String, Serializable> entry = null;
while(itr.hasNext()){
entry = itr.next();
keys.add(entry.getKey());
}
return keys;
}

public List<String> getKeys(String region) {
	RedissonClient client = mizeRedisCacheRedissonManager.getRedissonClient();
	Cache<String, Serializable> cache = getCache(region);
	RMap<String, Serializable> rmap = client.getMap(cache.getName());
	return (rmap != null) ? new ArrayList<String>(rmap.keySet()) : null;
}

Thanks in advance.

**Comment by SrinivasThodupunuri** [comment]
Hi,
Can you please update your response.

Thanks

**Comment by mrniko** [comment]
Did you set `ExpiryPolicy` option in JCache settings?

**Comment by stkggit** [comment]
Hi Nikita Koksharov,
I'd not set up any ExpiryPolicy, because we are using this for static data and we are using the MutableConfiguration() object's default behavior of Eternal.

Thanks,
srinivas

**Comment by mrniko** [comment]
@stkggit  Could you recheck it with latest changes?

**Comment by stkggit** [comment]
Still iterator approach is taking more time.
Key Size 5000

Method: getKeys() 
Start: Get All Keys
Time taken : 1592

Method: getKeysItr()
Start: Get All Keys
Time taken : 15105 

through iterator, we are iterating and adding to a list, i think that operation is taking more time.

Thanks,

**Comment by mrniko** [comment]
Here is my test:

```java
        RedisProcess runner = new RedisRunner()
                .nosave()
                .randomDir()
                .port(6311)
                .run();
        
        URL configUrl = getClass().getResource("redisson-jcache.json");
        Config cfg = Config.fromJSON(configUrl);
        
        RedissonClient redisson = Redisson.create(cfg);
        RedissonConfiguration<String, String> config = (RedissonConfiguration<String, String>) (Object)RedissonConfiguration.fromInstance(redisson);
        Cache<String, String> cache = Caching.getCachingProvider().getCacheManager()
                .createCache("test", config);
        
        for (int i = 0; i < 5000; i++) {
            cache.put("" + i, "" + i);
        }
        
        RMap<String, String> rmap = config.getRedisson().getMap(cache.getName());
        long s1 = System.currentTimeMillis();
        for (Object entry : rmap.keySet()) {
        }
        System.out.println("RMap iteration time: " + (System.currentTimeMillis() - s1));
        
        long s = System.currentTimeMillis();
        for (Object entry : cache) {
        }
        System.out.println("JCache iteration time: " + (System.currentTimeMillis() - s));
        
        redisson.shutdown();
        runner.stop();
```

and result is:

RMap iteration time: 111ms
JCache iteration time: 62ms

As you can see iteration through JCache object is faster. I think you have such performance difference since JCache deserializes both key and value objects and RMap only key object.
