### ISSUE TITLE
Jcache removeAll(Keys) Method is not working ***

### ISSUE THREAD

**Issue by stkggit** [redisson/redisson#1574]
Hi,
 removeAll (keys) Method is not working for "org.redisson.jcache.JCache".  Keys are still exising in the cache after After the execution of removeAll (keys).

Below Method in org.redisson.jcache.Jcache is returning 0.

 private long removeValues(Object... keys) {
        List<Object> params = new ArrayList<Object>(keys.length);
        encodeMapKeys(params, Arrays.asList(keys));
        return evalWrite(getName(), codec, RedisCommands.EVAL_LONG,
                  "redis.call('zrem', KEYS[2], unpack(ARGV)); "
                + "return redis.call('hdel', KEYS[1], unpack(ARGV)); ",
                Arrays.<Object>asList(getName(), getTimeoutSetName()), params);
    }

remove(key) is working fine.

Please find My code snippet below
public void invalidate(String region, Collection<String> keys) {
		if(keys == null || keys.isEmpty()){
			return;
		}
		Cache<String, Serializable> cache = getCache(region);

		if (cache != null && !Formatter.isEmpty(keys)) {
			cache.removeAll(new HashSet<String>(keys));
		}

	}

Please let me know if anything is Wrong from myside.

Thanks

**Comment by mrniko** [comment]
Fixed! Thanks for report
