### ISSUE TITLE
redisson.getNodesGroup() returns Nodes where both redis-server and redis-sentinel are not running

### ISSUE THREAD

**Issue by brother-fu** [redisson/redisson#1575]
redisson version: 2.11.3

the issue is like https://github.com/redisson/redisson/issues/1330, but they are different.

I am not sure if this issue is being fixed in newer version, but this is for sure reproducible in 2.11.3, following is the steps to reproduce.

1. having 3 redis vms running in Sentinel mode, current redisson.getNodesGroup().size() is 3  ---> as expected
2. bring down one of the redis boxes by shuting down both redis-server and redis-sentinel
    redisson.getNodesGroup().size() is 2 ----> as expected
3. bring the node up agin, redisson.getNodesGroup().size() is 4 ----> something is wrong here.

running steps 1-3 once might not reproduce the issue, but running it twice like following steps 1,2,3,2,3 will surface this issue, in fact it will lead the node size growing into 4, 5 and more.

Following is what I did in the class [RedisNodes.java](https://github.com/redisson/redisson/blob/redisson-2.11.3/redisson/src/main/java/org/redisson/RedisNodes.java)

```
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.FutureListener;
+import org.slf4j.LoggerFactory;
+import org.slf4j.Logger;
 
 /**
  * 
@@ -51,6 +53,8 @@ public class RedisNodes<N extends Node> implements NodesGroup<N> {
 
     final ConnectionManager connectionManager;
 
+    private static final Logger log = LoggerFactory.getLogger(RedisNodes.class);
+
     public RedisNodes(ConnectionManager connectionManager) {
         this.connectionManager = connectionManager;
     }
@@ -116,6 +120,7 @@ public class RedisNodes<N extends Node> implements NodesGroup<N> {
     @Override
     public boolean pingAll() {
         List<RedisClientEntry> clients = new ArrayList<RedisClientEntry>((Collection<RedisClientEntry>)getNodes());
+        log.debug(">>>>>> need to ping size is " + clients.size());
         final Map<RedisConnection, RFuture<String>> result = new ConcurrentHashMap<RedisConnection, RFuture<String>>(clients.size());
         final CountDownLatch latch = new CountDownLatch(clients.size());
         for (RedisClientEntry entry : clients) {

```

**Comment by brother-fu** [comment]
According to logic, nodes freezed because of Manage shoule not be returned in the list.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1480
