### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command

### ISSUE THREAD

**Issue by wmaozhi** [redisson/redisson#1576]
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command:

  RLock rLock = redissonClient.getLock(objectName);
  rLock.tryLock(10, TimeUnit.SECONDS);
  rLock.unlock();

**Comment by jackygurui** [comment]
Please see [FAQ](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it) regarding timeout
