### ISSUE TITLE
Redisson Session Manager for tomcat is not able to serialize/deserialize session object when multiple web application (war file) share same session.

### ISSUE THREAD

**Issue by srkrmandal** [redisson/redisson#1582]
hi, Need a help.

our organization was using oracle web coherence for session management. there are around 15 modules deployed as war files which share the same session with different context for each war file.
Coherence uses :: com.tangosol.coherence.servlet.AbstractHttpSessionCollection$GlobalScopeController in order to Share Session Information Between Multiple Applications. There is no class visibility issue by coherence session manager between applications sharing same session.

see LInk:
https://docs.oracle.com/cd/E15357_01/coh.360/e15829/features.htm#COHCW175

section: 4.2.2.1 Sharing Session Information Between Multiple Applications

Each context places some of its class in the session.setattribute and when using weblogic + coherence there was no issue with class visibility in session when the context gets changed during the user flow.

Now, our organization is trying to migrate to tomcat + RedissonSessionManager. however there are issues with the redisson session manager. one class loaded in one context is not visible by session manager when the context gets changed. So, session manager is complaining about ClassNotFoundException as it does not have visibility to the classes which were loaded in session when the control was in previous session.

Please let me know if there is any feature AVAILABLE in redisson session manager like oracle coherence has which makes it capable of viewing all the classes in the different war files (different contexts).

**Comment by mrniko** [comment]
reference https://github.com/redisson/redisson/issues/771

**Comment by mrniko** [comment]
Done.
`sharedSession` setting added. Read [description](https://github.com/redisson/redisson/blob/master/redisson-tomcat/README.md) for more details
