### ISSUE TITLE
Channel Inactive but  the event not catched by ConnectionWatchdog.channelInactive()

### ISSUE THREAD

**Issue by fl061157** [redisson/redisson#1583]
I find the Channel Inactive , but  the event not catched by ConnectionWatchdog.channelInactive()
so the connection not reconnect . 
then it throw  "org.redisson.client.WriteRedisConnectionException: Can't write command batch to channel"
for the socket not exists

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1811
