### ISSUE TITLE
Command execution timeout when calling CMS.QUERY in CountMinSketch module

### ISSUE THREAD

**Issue by lfzCarlosC** [redisson/redisson#1590]
When applying module CountMinSketch, calling CMS.QUERY using redission client to call CMS.QUERY command to get value, Timeout exception is throwed out.:

```
Exception in thread "main" org.redisson.client.RedisTimeoutException: Command execution timeout for localhost/127.0.0.1:6379
	at org.redisson.client.RedisConnection.await(RedisConnection.java:151)
	at org.redisson.client.RedisConnection.sync(RedisConnection.java:183)
	at com.brandwatch.signals.detector.RedisClientTest.main(RedisClientTest.java:62)
```

I use the code :
```
RedisClientConfig config = new RedisClientConfig();
        config.setAddress("redis://localhost:6379")  
              .setDatabase(0)
              .setGroup(group)
              .setPingConnectionInterval(1000);
        RedisClient client = RedisClient.create(config);
        RedisConnection conn = client.connect();
        RFuture<RedisConnection> connFuture = client.connectAsync();

        RedisCommand query = new RedisCommand("CMS.QUERY");
        Object obj = conn.sync(StringCodec.INSTANCE, query, "key", "item");
```

Before I already ran a command on redis-cli:  CMS.INCRBY  key item 1
And, I ran a command: ```CMS.QUERY key item```  using redis-cli and it returns  ```1) (integer) 1```

I also try sending  the above CMS.INCRBY  command using redission api and  the comand is running successfully.
### Expected behavior
obj can get or contain the value 1 inside.

### Actual behavior
exception as above

### Redisson configuration
set CountMinSketch as a module for redis and launch redis.
I am using redission 3.7.5

**Comment by mrniko** [comment]
Could you set logging level to `trace` for `org.redisson` package and share gotten output?

**Comment by jackygurui** [comment]
closed due to inactivity
