### ISSUE TITLE
In CommandsQueue , the preceding request will block the request behind.  how did you handle it?

### ISSUE THREAD

**Issue by fl061157** [redisson/redisson#1591]
In CommandsQueue , if the previous request was responsed for a long time.
Then the  behind request will block , how did you handle it .

**Comment by jackygurui** [comment]
the "infamous" RedisTimeoutException will kick in and remove it.

**Comment by fl061157** [comment]
@jackygurui  thank you .   I mean it cost a lot of time ,  then the next QueueCommand  in  CommansQueue can not be send ,  until  redis response it in    CommandDecoder ,   then it can be send .    I think if redis  or net block , i should drop all the command .

**Comment by fl061157** [comment]
At last i config the connection.poolSize the same as main thread pool size . then  it will  not overstock in CommandsQueue.queue .
