### ISSUE TITLE
Driver Support for Redis Engine version 4.0.10

### ISSUE THREAD

**Issue by stkggit** [redisson/redisson#1600]
Hi,

I'm using Hibernate-reids library for second level cache, can i point to the redis Engine version 4.0.10 ?
as per the documentation it is mentioned that it has tested this with redis server 3.x. with Redisson 2.3.x.

as per my opinion i'm using Redisson client 2.12.5 and  if Redisson client supports redis Engine version 4.0.10 then Hibernate-reids also should support.

Please provide your inputs.

Thanks in Advance.

Srinivas

**Comment by mrniko** [comment]
Hi!

Redisson is fully compatible with 4.0.10 version and hibernate-redis lib doesn't use any api related to this version. So you can use it safely.

**Comment by stkggit** [comment]
Thank you so much.
