### ISSUE TITLE
unlock fail and expirationRenewal still execute

### ISSUE THREAD

**Issue by xmh51** [redisson/redisson#1602]
### Expected behavior
unlock success

### Actual behavior
unlock  fail

### Steps to reproduce or test case
unlock ()
client -> redis service network problem
unlock throw Exception
network recovery
expirationRenewal still execute

### Redisson version
2.11.5

### Redisson configuration
redisson.connectionPoolSize=5
redisson.connectionMinimumIdleSize=2
redisson.address=
redisson.database=3
redisson.password=
redisson.connectTimeout=3000
redisson.timeout=3000

**Comment by mrniko** [comment]
Fixed
