### ISSUE TITLE
lexicographically sort with ALPHA modifier

### ISSUE THREAD

**Issue by hexmind** [redisson/redisson#1607]
It looks that Redisson doesn't implement ALPHA in sorting. In Redis ALPHA  prevents "ERR One or more scores can't be converted into double" (https://redis.io/commands/sort).
I found ALPHA only in  redisson-spring-data (RedissonConnection.java).

Should I send PR?

### Expected behavior

```
redisson.getScoredSortedSet(key).readSortAlpha(SortOrder.ASC)
```

### Actual behavior

```
redisson.getScoredSortedSet(key).readSort(SortOrder.ASC)
```
readSort returns Set with null

### Redis version
5.0

### Redisson version
3.7.5

**Comment by Pepe-Lu** [comment]
taking care of this

**Comment by mrniko** [comment]
Pull request merged
