### ISSUE TITLE
Unable to find maven artifact

### ISSUE THREAD

**Issue by howardem** [redisson/redisson#1609]
Hi everyone,

This is more a question than an issue. I'm using Spring Boot 1.5.x with Spring Data Redis 1.8 on top of JDK 1.8+ and I'd like to replace the Jedis client with Redisson. I was able to find the artifact org.redisson:redisson:3.7.5 on the Sonatype maven repository but I can't find org.redisson:redisson-spring-data-18:3.x in order to register a RedissonConnectionFactory bean. I forked and compiled the repository locally, but the artifact version I got after the compilation was 2.12.x which targets JDK 1.6+ 

Best,

**Comment by mrniko** [comment]
Spring Data Redis modules are part of 2.13/3.8 version which are not released yet.
