### ISSUE TITLE
RMap.putAll() inside a Rtransaction takes alot of time and finally fails

### ISSUE THREAD

**Issue by shivendra-kumar** [redisson/redisson#1612]
While putting 50000 entries in RMap using putAll method, we are getting the following error:

org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=500, freeConnectionsCounter=500, freezed=false, freezeReason=null, client=[addr=redis://10.0.50.128:6379], nodeType=MASTER, firstFail=0]]], command: (EVAL), command params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('publish', KEYS[2], ARGV[1]); return 1; end;..., 2, {put_test}:arsCJwLIncVScAFr2TIRxQ:lock, redisson_lock__channel:{put_test}:arsCJwLIncVScAFr2TIRxQ:lock, 0, 60224, 3ab74421-f3c9-4962-8383-0034fa219ff4:24] after 3 retry attempts
	org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:531)
	io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	java.lang.Thread.run(Thread.java:745)

Steps to reproduce the issue:

      public void largePutAll() {		
		  for(SomeObject obj: listOfSomeObject)
		         {	
			        accMap.put(obj.getId(), obj);
		         }
		
		RTransaction transaction = redisson.createTransaction(options);
	        RMap map = transaction.getMap("put_test");
		map.putAll(accMap);
               transaction.commit();

		}

Below is my configuration:
Redis 4.0.9

 redisson 3.7.5

 Config config = new Config();
		config.useSingleServer().setAddress("redis://10.0.50.128:6379");

		config.useSingleServer().setRetryAttempts(3);
		config.useSingleServer().setConnectionPoolSize(500);
		config.useSingleServer().setRetryInterval(2000);
		config.useSingleServer().setConnectTimeout(30000);
		FstCodec codec = new FstCodec();
		config.setCodec(codec);
		redisson = (RedissonClient) Redisson.create(config);

		options = TransactionOptions.defaults()

				.syncSlavesTimeout(10, TimeUnit.SECONDS).responseTimeout(10, TimeUnit.SECONDS)
				.retryInterval(5, TimeUnit.SECONDS).retryAttempts(5).timeout(40, TimeUnit.SECONDS);

**Comment by shivendra-kumar** [comment]
@mrniko Please look into this when you have time

**Comment by mrniko** [comment]
Does this happen only on 50K entries? What if you try 10K?

**Comment by shivendra-kumar** [comment]
It runs without any problem for upto 15k entries. But once the number of entries exceeds this it throws the above error.

**Comment by shivendra-kumar** [comment]
Any updates on this yet?

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version
