### ISSUE TITLE
Redis- Master/slave role detection through DNS

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#1621]
### Expected behavior
Master connections should be created on new master.
### Actual behavior
We are using Elasticache with 1 master and 1 slave. The redis endpoints are behind route53 record sets. When we swtich the endpoints in route53 to point to new master and slaves. The redisson is pointing to incorrect slave.
### Steps to reproduce or test case
endpoints=redis://redis-slave-1.dev.com:6379,redis://redis-slave-2.dev.com:6379
where route53 recordsets are pointing redis-slave-1.dev.com to read endpoint of a node which is **master**.
and redis-slave-2.dev.com points to read endpoint of node (**slave**).

If we change the recordset redis-slave-1.dev.com (earlier pointing to **master**) to point to read endpoint of a node which is **slave** and we also switch redis-slave-2.dev.com (earlier pointing to **slave**) to point to read endpoint of node (**master**), then this error comes.

The following logs are found:
[sson-netty-1-16] org.redisson.connection.DNSMonitor       : Detected DNS change. Master redis://redis-slave-1.dev.com:6379 has changed ip from 10.74.43.133 to 10.74.43.138
org.redisson.connection.DNSMonitor       : Detected DNS change. Slave redis-slave-2.dev.com has changed ip from 10.74.43.167 to 10.74.43.179

Then all the writes to redis are returning error with:

org.redisson.client.RedisException: ERR Error running script (call to f_1a2512673a7e300ca9d3d3d069a725acc43a6f4e): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   . channel: [id: 0x730e4414, L:/10.74.43.247:60542 - R:redis-slave-1.dev.com/10.74.43.138:6379] command: 

### Redis version
3.2.4

### Redisson version
3.7.5

### Redisson configuration
@Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        Config config = new Config();
        RedisProperties redisProperties = getRedisProperties();
        config.useReplicatedServers().setLoadBalancer(new RoundRobinLoadBalancer()).setScanInterval(redisProperties.getScanInterval()).
                setSubscriptionConnectionPoolSize(redisProperties.getSubscriptionPoolSize()).setSubscriptionConnectionMinimumIdleSize(redisProperties.getSubscriptionIdleSize()).
                setSubscriptionsPerConnection(redisProperties.getSubscriptionPerConnection()).
                setMasterConnectionPoolSize(redisProperties.getMasterConnectionPoolSize()).setSlaveConnectionPoolSize(redisProperties.getSlaveConnectionPoolSize()).
                setSlaveConnectionMinimumIdleSize(redisProperties.getIdleConnectionSize()).setMasterConnectionMinimumIdleSize(redisProperties.getIdleConnectionSize()).
                setIdleConnectionTimeout(redisProperties.getIdleConnectTimeout()).setReconnectionTimeout(redisProperties.getTimeout()).
                setReadMode(ReadMode.SLAVE).setConnectTimeout(redisProperties.getConnectTimeout()).setTimeout(redisProperties.getTimeout()).addNodeAddress(redisProperties.getRedisHostName());
        return Redisson.create(config);
    }

Please note that redisson is easily able to detect master/slave and able to switch connections when doing promotion of a slave.
It is also able to detect the DNS change successfully if the master endpoint is replaced by another cluster's master endpoint.
**But, when we switch the DNS in a manner so that the earlier recordset which was pointing to a master now points to a slave and vice-versa, redisson is unable to detect it.**

**Comment by Himanshu4** [comment]
This would be a great to have feature.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3736
