### ISSUE TITLE
Does anyone tried integrating mockito with redisson? 

### ISSUE THREAD

**Issue by kevinchwong** [redisson/redisson#1627]
I just tried write an unit test for a function using Redisson, but it seems impossible to return a faked RSet data set only by a mocked RedissonClient. Or, usually which library you all used to mock a Redisson client?

**Comment by mrniko** [comment]
Try http://jmockit.github.io/ it's more powerful alternative to mockito

**Comment by kevinchwong** [comment]
Jmockit looks good. My other question is if this possible to create Faked RSet<>, RMap<> data set in the unit testing without starting the real/ embedded server?

**Comment by Remeic** [comment]
I have the same problem of @kevinchwong , i have to make unit test in isolation, @kevinchwong 
you managed to run the server in embedded mode ?

**Comment by jackygurui** [comment]
The built-in redis runner will be able to start an isolated instance and terminates it after it has finished. All you need is to point it to the location of redis-server

**Comment by Remeic** [comment]
@jackygurui can you show me a code example? I'm blocked in this moment
