### ISSUE TITLE
redisson failed to parse /etc/resolv.conf and/or /etc/resolver

### ISSUE THREAD

**Issue by maregeo** [redisson/redisson#1638]
redisson version：3.8.1
netty version:   4.1.12.Final
OS:window7
JDK 1.8+

redisson config sample:
`
<redisson:client
	    id="redisson"
	    netty-threads="0"
	    threads="0"
	    name="redisson1,redisson2">
	    
	    <redisson:single-server
	        idle-connection-timeout="10000"
	        ping-timeout="1000"
	        connect-timeout="3000"
	        timeout="3000"
	        retry-attempts="1"
	        retry-interval="1500"
	        password="${jedis_pass}"
	        subscriptions-per-connection="5"
	        client-name="none"         
	        address="${redis_server}"
	        subscription-connection-minimum-idle-size="1"
	        subscription-connection-pool-size="50"
	        connection-minimum-idle-size="10"
	        connection-pool-size="64"
	        database="0"
	        dns-monitoring-interval="5000"
    	/>
</redisson:client>
`

**Comment by mrniko** [comment]
Could you please share full exception?

**Comment by maregeo** [comment]
create single-server will use class MasterSlaveConnectionManager .
![image](https://user-images.githubusercontent.com/9401669/45795457-65159c00-bcce-11e8-82e2-cad1fcd5aeb2.png)

![image](https://user-images.githubusercontent.com/9401669/45795467-7068c780-bcce-11e8-96cf-8c8bfe669374.png)

![image](https://user-images.githubusercontent.com/9401669/45795473-7494e500-bcce-11e8-96cf-7afb20e5cf51.png)

on windows system ,the file /etc/resolv.conf not exist,and the directory /etc/resolver not exist too, therefore the   bug is appeared

**Comment by mrniko** [comment]
@maregeo 

Could you address this issue to netty project?

**Comment by maregeo** [comment]
OK

**Comment by mrniko** [comment]
please update your netty version to the latest, it supports windows
