### ISSUE TITLE
support for tomcat websocket session

### ISSUE THREAD

**Issue by jhavinay** [redisson/redisson#1645]
Will existing Redisson tomcat session support tomcat websocket session too?
Tried persisting manually and encountered serialization exception.
Looking into the code it seems redisson session extends standardsession and might not support websocket session. Hence the question. Tried writing my own impl of RedissonWebocketsession, but guess my newbie status with redisson was a stumbling block. Need to learn/understand more before i attempt it.

### Expected behavior
Application is supposed to store websocket session in redis. Can it be done?
### Redis version
Redis server v=4.0.11 sha=00000000:0 malloc=libc bits=64 build=13f90e3a88f770eb
### Redisson version
3.3.0

**Comment by mrniko** [comment]
Could you share exception stacktrace
