### ISSUE TITLE
redisson-spring-boot-starter 3.8.1 doesn't works

### ISSUE THREAD

**Issue by xiejx618** [redisson/redisson#1650]
### Redisson version
3.8.1
### Redisson configuration

Because the file https://github.com/redisson/redisson/blob/master/redisson-spring-boot-starter/src/main/resources/META-INF/spring.factories is encoded as UTF-8+ BOM instead of Utf-8. Causes PropertyLoaderUtils.loadProperties(resource); reading this file is garbled.

the key of the property as follows :
![cb30fc43-a49e-485d-bbe4-c769202e3f78](https://user-images.githubusercontent.com/2609827/46145023-582a1700-c291-11e8-9827-280f1b45a030.png)

**Comment by echooymxq** [comment]
**I also met this question today.**
```xml
<dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson-spring-boot-starter</artifactId>
      <version>3.8.1</version>
</dependency>
```
**java 1.8
spring-boot 1.5.9.RELEASE**  

![redisson](https://user-images.githubusercontent.com/19860963/46184144-c3620080-c306-11e8-93c8-38a7b3947f1d.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by echooymxq** [comment]
> Fixed! Thanks for report

please deploy to mvnrepository, thanks!
