### ISSUE TITLE
Memory leaks with LZ4/FST/netty

### ISSUE THREAD

**Issue by amitabhsh** [redisson/redisson#1652]
### Expected behavior
I'm using LZ4Codec to serialize and deserialize my data. I'm noticing some unclosed streams which are wasting a lot of heap space.
`private Codec compositeCodec = new CompositeCodec(new StringCodec(), new LZ4Codec(),  new SerializationCodec());
RLocalCachedMap<String, CachedObject> simpleMap = (RLocalCachedMap<String, CachedObject>) redisson.getLocalCachedMap("simpleMap", compositeCodec);`

These are the screenshots from the heap dump I took which shows the problem.
![image](https://user-images.githubusercontent.com/2065493/46181862-0c6d7280-c27d-11e8-99b7-631dd4d3dc7d.png)

![image](https://user-images.githubusercontent.com/2065493/46181595-b0561e80-c27b-11e8-90be-93916e57edfb.png)
![image](https://user-images.githubusercontent.com/2065493/46181609-bc41e080-c27b-11e8-98b0-88531f6da53d.png)

### Steps to reproduce or test case
- Using RLocalCacheMap and Composite Codec try to serialize and deserialize a few 100 objects. Do not shutdown redisson.
### Redis version
4.0.1
### Redisson version
2.13.1
### Redisson configuration
SingleServer

**Comment by mrniko** [comment]
Any update?
