### ISSUE TITLE
Time to connect takes around 2 seconds

### ISSUE THREAD

**Issue by SSP16SCM59S** [redisson/redisson#1653]
When I am trying to connect to redis it takes around 2 seconds. This started happening after I upgraded to 3.8.1 maven. This is the code used to connect. I initialize the connection every single time and close it down. Is there something I am doing wrong or is this a bug.

`RedissonClient redisson = null;
Config config = new Config();
config.useSingleServer().setAddress("redis://*.*.*.*:6379").setPassword("Password");
redisson = Redisson.create(config);

redisson.shutdown();
`

**Comment by mrniko** [comment]
Which version did you use before?

**Comment by SSP16SCM59S** [comment]
3.5.*

**Comment by mrniko** [comment]
According to my benchmark with 3.8.1 version initialization time takes ~1300ms.
