### ISSUE TITLE
How to use spring beans inside executor service task

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#1657]
Hi,
Is it possible to access spring beans from within executor service tasks somehow?

**Comment by mrniko** [comment]
Did you try to invoke `SpringBeanAutowiringSupport.processInjectionBasedOnCurrentContext` method first in task body?

**Comment by imbolo** [comment]
@mrniko 

> Did you try to invoke `SpringBeanAutowiringSupport.processInjectionBasedOnCurrentContext` method first in task body?

I met the same problem.
Adding this in task body did not work.

**Comment by mrniko** [comment]
Done. Just define Spring BeanFactory during workers registration and you can use @Autowired and @Value annotations.
