### ISSUE TITLE
Which readMode to use? 

### ISSUE THREAD

**Issue by lying1234** [redisson/redisson#1660]
We have Redis cluster with 6 nodes (3 masters and 3 slaves), and using redisson 3.6.5. In redisson cluster setting, we applied default value (SLAVE ) on readMode. 

Here are some questions on this setting:

1. What will happen if one of slave node fails? Will redisson detect the error and switch to master on Read, or it will try to connect to Slave only and throw exception?

2. If we use MASTER_SLAVE, read operation will go to master/slave randomly or it has a way to go to slave first, and then master when slave fails?

**Comment by mrniko** [comment]
1. Redisson uses MASTER if no SLAVES are available.

2. Load balancer is used defined through `loadBalancer` setting
