### ISSUE TITLE
Unexpected ClassCastException during RBatchReactive execution

### ISSUE THREAD

**Issue by orclev** [redisson/redisson#1661]
### Expected behavior

Calling `RBatchReactive.execute()` should complete successfully.

### Actual behavior

`RBatchReactive.execute()` triggers a ClassCastException to be thrown from `org.redisson.command.CommandBatchService.handleSuccess(CommandBatchService.java:224)` with the message of `org.redisson.misc.RedissonPromise cannot be cast to org.redisson.command.BatchPromise`

### Steps to reproduce or test case

This was occurring in some code that looks like the following gist: https://gist.github.com/orclev/2e70b1bc269d30d79121fd1e3c6da047

Due to the nature of the code in question so mild anonymization has been applied to it.

### Redis version

4.0.10

### Redisson version

3.7.5

### Redisson configuration

1 master, 2 replicas.

```
config.useReplicatedServers()
                    .setTimeout(5000)
                    .setRetryAttempts(15)
                    .setMasterConnectionPoolSize(512)
                    .setMasterConnectionMinimumIdleSize(64)
                    .setSlaveConnectionPoolSize(1025)
                    .setSlaveConnectionMinimumIdleSize(128)
                    .setSubscriptionConnectionPoolSize(16)
                    .setSubscriptionConnectionMinimumIdleSize(1)
                    .setRetryInterval(500)
                    .addNodeAddress(redisHosts.stream()
                            .map(host -> "redis://" + host + ":" + redisPort)
                            .collect(Collectors.toList())
                            .toArray(new String[] {}));
```

**Comment by orclev** [comment]
On a related note, there's no documentation of how batch is supposed to be used with the reactive API. There are examples provided of both the sync and async API beings used with batch. It would be very helpful if an example of the reactive API could be included in the documentation as well.

**Comment by mrniko** [comment]
Fixed! Thanks for report
