### ISSUE TITLE
UnsupportedOperationException thrown when using Spring Actuator

### ISSUE THREAD

**Issue by bulivlad** [redisson/redisson#1663]
I am trying to use Spring Actuator with redis as a single server but I'm getting UnsupportedOperationException at RedisHealthCheck so the application is considering redis DOWN

### Expected behavior
Actuator is able to perform health checks to determine the status of Redis server

### Actual behavior
java.lang.UnsupportedOperationException is thrown when Actuator tries to do the Redis health check

### Steps to reproduce or test case
Add spring actuator to project
Configure RedissonClient as a single server (default configuration from here https://github.com/redisson/redisson/wiki/2.-Configuration#26-single-instance-mode can be used)
Start the application with health check enabled

### Redis version
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d3ebfc7feabc1290
redis_mode:standalone

### Redisson version
redisson-3.8.1

### Redisson configuration
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://127.0.0.1:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.JsonJacksonCodec"
   },
   "transportMode":"NIO"
}
[redisson-stack-trace.log](https://github.com/redisson/redisson/files/2446131/redisson-stack-trace.log)

**Comment by mrniko** [comment]
Thanks for report! Fixed in https://github.com/redisson/redisson/commit/d10be369f1d203422e5c84b82395127e79f2d953
