### ISSUE TITLE
Redis address can not load when I use redisson-spring-boot-starter: 3.8.0/3.8.2

### ISSUE THREAD

**Issue by einarzhang** [redisson/redisson#1670]
When I use the config: spring.redis.cluster.nodes=redis1.test:3000  or redis://redis1.test:3000 or rediss://redis1.test:3000, the application can not startup. 
the env is:
redisson-spring-boot-starter: 3.8.0/3.8.2
spring-boot: 2.0.4
### Expected behavior
startup successfully
### Actual behavior
Got error:  Illegal character in scheme name at index 0: [redis1.test]:3000
### Redis version
4.2
### Redisson version
3.8.2
### Redisson configuration
spring.redis.cluster.nodes=redis1.test:3000

**Comment by einarzhang** [comment]
The error is cause by redisson conflict with spring-boot: 2.0.4, while spring-boot-data-redis mustnot set spring.redis.cluster.nodes like redis://redis1.test:3000, because the below code:

`private RedisNode readHostAndPortFromString(String hostAndPort) {

		String[] args = split(hostAndPort, ":");

		notNull(args, "HostAndPort need to be seperated by  ':'.");
		isTrue(args.length == 2, "Host and Port String needs to specified as host:port");
		return new RedisNode(args[0], Integer.valueOf(args[1]));
	}`

but redisson must config with prefix: redis:// or redisson://. so RedissonAutoConfiguration must process cluster nodes like single node:

now is 
`config.useClusterServers()
                .addNodeAddress(nodesObject.toArray(new String[nodesObject.size()]))
                .setConnectTimeout(timeout)
                .setPassword(redisProperties.getPassword());`

must be like this:
` nodesObject = nodesObject.stream().map(node -> {
                return node.startsWith("redis://") ? node : "redis://" + node;
            }).collect(Collectors.toList());`

**Comment by mrniko** [comment]
Thanks for suggestion! Fixed in https://github.com/redisson/redisson/commit/57e2d6253a0045ba4b73a0b6c34fcd40dc793315
