### ISSUE TITLE
Leader Election Recipe?

### ISSUE THREAD

**Issue by efenderbosch** [redisson/redisson#1674]
Sorry if this isn't the correct forum for this question.

Could redisson be used to perform leader election in a cluster? I don't really feel like adding Zookeeper or Consul to our current mix.

**Comment by mrniko** [comment]
Leader election in a cluster performed by Redis cluster itself. Redisson can't effect on this.

**Comment by efenderbosch** [comment]
I mean for another service, not redis itself. I want a service to participate in leader election.

**Comment by huangyemin** [comment]
Here is a [leader election](http://www.xetlab.com/2019/04/19/%E7%94%A8redisson%E7%9A%84%E5%88%86%E5%B8%83%E5%BC%8F%E9%94%81%E5%AE%9E%E7%8E%B0%E4%B8%BB%E4%BB%8E%E9%80%89%E4%B8%BE%EF%BC%88leader%20election%EF%BC%89/) implemented with RLock, the content is written with chinese, but the full code is given in the end of article.

**Comment by mrniko** [comment]
@huangyemin 

Nice article! Thanks!

**Comment by jackygurui** [comment]
@mrniko Maybe we should start collecting articles written by users such as this one?

**Comment by mwmitchell** [comment]
It's also here in English: https://www.programmersought.com/article/84841605510/
