### ISSUE TITLE
RSemaphore not compatible with java.util.concurrent.Semaphore

### ISSUE THREAD

**Issue by jeskew** [redisson/redisson#1675]
### Expected behavior
```java
import java.util.concurrent.Semaphore;
import org.redisson.Redisson;

Semaphore semaphore = Redisson.create().getSemaphore("foo");
```

### Actual behavior

`Error:(65, 57) java: incompatible types: org.redisson.api.RSemaphore cannot be converted to java.util.concurrent.Semaphore`

Just out of curiosity, why doesn't the `org.redisson.api.RSemaphore` interface extend the `java.util.concurrent.Semaphore` interface?

**Comment by jackygurui** [comment]
`java.util.concurrent.Semaphore` is not an interface. See https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Semaphore.html
