### ISSUE TITLE
Question about clearLocalCache()

### ISSUE THREAD

**Issue by julialiu15** [redisson/redisson#1679]
Thanks for authoring and maintaining this great project.
We are considering moving over to Redisson to make use of it's local cache feature as it provides a performance boost comparing directly retrieving data from redis. Run into this when trying to clear local cache, seems like the cache was not cleared, everything stills stays. Is this the expected behavior, what would be the best to way to clear all caches, could you shed more lights on this please?

### Expected behavior
Clears local cache across all instances
https://static.javadoc.io/org.redisson/redisson/3.6.4/org/redisson/api/RLocalCachedMap.html#clearLocalCacheAsync--

### Actual behavior
Local cache is not cleared, everything in local cache persists

### Steps to reproduce or test case
```
import org.redisson.Redisson;
import org.redisson.api.LocalCachedMapOptions;
import org.redisson.api.RLocalCachedMap;
import org.redisson.api.RedissonClient;

public class RedissonLocalCache {
    private final RLocalCachedMap<String, String> localMap;
    private static RedissonClient client = Redisson.create();


    public RedissonLocalCache() {
        localMap = client.getLocalCachedMap(
                "myMapName",
                LocalCachedMapOptions.defaults()
        );
    }

    public void clearTest() {
        localMap.fastPut("key", "value");
        localMap.clearLocalCache();

        System.out.println("map size after clear: " + localMap.keySet().size());
    }
}
```
To run:
```
RedissonLocalCache test = new RedissonLocalCache();
test.clearTest();
```

### Redis version
4.0.8
### Redisson version
3.8.2
### Redisson configuration
default

**Comment by mrniko** [comment]
`localMap.keySet().size()` outputs size of data stored in Redis and not in local cache

**Comment by julialiu15** [comment]
Thanks for the reply, besides `clearLocalCache() ` is there a way to clear cache in both local cache and redis?

**Comment by julialiu15** [comment]
Did more testing on this, seems like [clearLocalCache()](https://static.javadoc.io/org.redisson/redisson/3.6.4/org/redisson/api/RLocalCachedMap.html#clearLocalCache--) only works on local cache, but [clear()](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html?is-external=true#clear--) does the clear for both local cache and Redis, is this the expected behavior, maybe `clear()` is the way to go if "complete" invalidation is desired?

**Comment by mrniko** [comment]
> does Redisson provide some sort of distributed syncing on local cache with pubsub/listenpush please?

Use SyncStrategy.UPDATE to achieve that.

> but clear() does the clear for both local cache and Redis, is this the expected behavior, maybe clear() is the way to go if "complete" invalidation is desired?

You can clear data located at both local cache and redis by "delete" or "clear" methods
