### ISSUE TITLE
Question regarding codec for Result Set

### ISSUE THREAD

**Issue by kdaham** [redisson/redisson#1686]
Hi I am trying to use redis-graph with redisson and have trouble figuring out how to read the result set that redis-graph (https://github.com/RedisLabsModules/redis-graph) returns.
A typical result set can look like this.

1) (empty list or set)
2) 1) Labels added: 1
   2) Nodes created: 1
   3) "Query internal execution time: 0.625300 milliseconds"

Ive tried a regular bytearray but get only the last line and then it times out.
Any tips?

**Comment by mrniko** [comment]
This module is not supported
