### ISSUE TITLE
redisson-all-2.13.2.jar not compatible with jdk 1.7 version

### ISSUE THREAD

**Issue by azajshaikh** [redisson/redisson#1688]
### Actual behavior : redisson-all-2.13.2.jar not compatible with jdk 1.7 version . It is giving following error when try to run the same with jdk 1.7 version
 java.lang.UnsupportedClassVersionError: org/redisson/api/listener/MessageListener : Unsupported major.minor version 52.0

### Steps to reproduce or test case : redisson-all-2.13.2.jar should work with jdk 1.7 
execute the redisson-all-2.13.2.jar under jdk 1.7 version.

### Redis version : Redis 3.2 (For windows machine)

Please provide same redisson-all-2.13.2.jar 
with jdk 1.7 compiled.

**Comment by mrniko** [comment]
Unable to reproduce it with redisson-all-2.13.2.jar and 
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
