### ISSUE TITLE
ReplicatedConnectionManager shuts down executor it doesn't own

### ISSUE THREAD

**Issue by dsilvasc** [redisson/redisson#1690]
### Expected behavior
When we pass an executor in the redisson config, redisson should never shut it down.

### Actual behavior
ReplicatedConnectionManager calls stopThreads from the parent class MasterSlaveConnectionManager.  The stopThreads method calls `executor.shutdown()` without checking who owns it.

### Steps to reproduce or test case
This example should call stopThreads in the ReplicatedConnectionManager constructor because the config doesn't have any node addresses:

```java
ExecutorService es = Executors.newCachedThreadPool();
Config config = new Config().setExecutor(executorService);
config.useReplicatedServers();
Redisson.create(config);

assert !es.isTerminated();
```

### Redis version
3.2.6

### Redisson version
3.8.2

### Redisson configuration
`config.setExecutor(executorService).useReplicatedServers()`

**Comment by mrniko** [comment]
Fixed! Thanks for report
