### ISSUE TITLE
Command succesfully sent, but channel [..] has been closed

### ISSUE THREAD

**Issue by govindr91** [redisson/redisson#1695]
I have an AWS ElastiCache for Redis server running in non-cluster configuration. The connection is TLS enabled. Once in a while, we get this error when servers try to establish the connection with Redis server. 

### Steps to reproduce or test case
Once in a while whenever the services tried to connect to Redis server, I'm getting this error. 

### Redis version
4.0.10

### Redisson version
3.8.2

### Redisson configuration
AWS Master-Slave Configuration with TLS enabled.

**Comment by rohanagarwal36** [comment]
I see this bug is affecting multiple people. Consider resolving it.

**Comment by mrniko** [comment]
Have you tried this solution ? https://github.com/redisson/redisson/issues/1748#issuecomment-445121826

**Comment by mrniko** [comment]
Fixed.
