### ISSUE TITLE
How to dynamically switch databases

### ISSUE THREAD

**Issue by 89333367** [redisson/redisson#1698]
### Redis version
3.x
### Redisson version
3.8.2
### Redisson configuration
```
@Bean(name = "redisSingleClient", destroyMethod = "shutdown")
    RedissonClient redisSingleClientInit() {
        Config config = new Config();
        config.setCodec(StringCodec.INSTANCE);
        SingleServerConfig singleConfig = config.useSingleServer();
        singleConfig.setAddress("redis://" + url);
        return Redisson.create(config);
    }
```
How to dynamically switch other databases?

**Comment by jackygurui** [comment]
You have to specify the database you desire in the `Config` object before passing it to construct the RedisClient instance.

**Comment by johnou** [comment]
@89333367 consider creating multiple redis clients with a shared event loop.

**Comment by cherrydev** [comment]
I also have a compelling use-case for being able to do this: I'm implementing a large-scale multi-tenancy systems (hundreds of tenants) and would like to have separate databases for each tenant for both efficiency reasons (avoid bloating every key with a tenant-id) and operational reasons (separate backup and restore). One Redis client instance for every single tenant would mean my connection count to the redis server would be multiplied by the number of tenants, which for a micro-service architecture would be unmanageable (service-count x replication-count x tenant-count = ~10k connections).
While it would add an extra redis remote command each time it's used, is there a technical reason why a `SELECT <index>` command couldn't be issued before each command?

**Comment by davidreis97** [comment]
This has been closed since 2018 but I believe there's space for improvement here @mrniko. In my use-case, I have a CRON where I need to replace an existing structure with a different one, and I had the idea of creating a temporary one with the same name in DB 1 and moving it to DB 0 once finished, but the way DBs are currently managed in Redisson makes this pretty unwieldy.
