### ISSUE TITLE
org.redisson.client.RedisConnectionClosedException received. MasterSlaveServersConfig.create function skips setting keepAlive flag.

### ISSUE THREAD

**Issue by bugratari** [redisson/redisson#1700]
### Expected behavior
The value associated with the key
### Actual behavior
org.redisson.client.RedisConnectionClosedException: Command succesfully sent, but channel [xyz] has been closed!
When I debug happy case I am seeing the actual redisClients in connectionFutures in async method of CommandAsyncService have keepAlive = false. I suspect this may the root cause.

The connections seem to go stale after an unknown duration (verified that the server timeout is not affecting this) 
Looking in more detail, I see MasterSlaveServersConfig create(BaseMasterSlaveServersConfig<?> cfg) 
in MasterSlaveConnectionManager.java file is not setting keepAlive flag.

This is extremely hard to repro and I couldn't debug a failure case yet; but it seems like we cannot rely on redisClient abstracting connection handling unless we are missing a config.
Please advise.
### Steps to reproduce or test case
Connect to a redis cluster by setting keepAlive = true
Not performing any actions for a long time ranges between 1h to 10h.
Trigger a getMap with existing key value.

### Redis version
4.0.9
### Redisson version
3.8.2
### Redisson configuration
redissonConfig.useClusterServers()
                .addNodeAddress("host")
                .setMasterConnectionMinimumIdleSize(8)
                .setMasterConnectionPoolSize(1924)
                .setSlaveConnectionMinimumIdleSize(8)
                .setSlaveConnectionPoolSize(1924)
                .setTimeout(20000)
                .setDnsMonitoringInterval(-1)
                .setKeepAlive(true);

**Comment by mrniko** [comment]
Merged

**Comment by bugratari** [comment]
Nikita, thanks for accepting and merging my PR. I wonder when we expect to have the next official release. Did you have a date in mind?

**Comment by mrniko** [comment]
@bugratari 

Tomorrow!

**Comment by bugratari** [comment]
@mrniko Thank you!
