### ISSUE TITLE
RLocalCachedMap是否为线程安全的？

### ISSUE THREAD

**Issue by ghost** [redisson/redisson#1702]
多线程读写是否有可能 fail-fast  错误？

**Comment by jackygurui** [comment]
RLocalCachedMap是线程安全的。你说的`fail-fast错误`具体指的哪些？

**Comment by shaopro** [comment]
> RLocalCachedMap是线程安全的。你说的`fail-fast错误`具体指的哪些？

比如说一个线程对RLocalCachedMap 进行读写 ，另外一个线程对RLocalCachedMap进行遍历 是否可能出现 fail-fast ？

另外 RMapCache  size()  是否是实时的啊 不会有脏数据误读？

**Comment by jackygurui** [comment]
> 比如说一个线程对RLocalCachedMap 进行读写 ，另外一个线程对RLocalCachedMap进行遍历 是否可能出现 fail-fast ？

 不会

> 另外 RMapCache size() 是否是实时的啊 不会有脏数据误读？

不会

**Comment by shaopro** [comment]
Thanks,


`        
RBatch rBatch = client.createBatch(BatchOptions.defaults());
rBatch.getMapCache("RMapCache").addAndGetAsync(1, 1);
rBatch.getMap("RMap").addAndGetAsync(2, 2);
rBatch.execute().getResponses().forEach(System.out::println);
`
MapCache存入 value 是否支持原生类型，尝试了好几种Codec发现都是16进制的

`
127.0.0.1:6379> hgetall  "RMap"
1) "2"
2) "2"
127.0.0.1:6379> hgetall  "RMapCache"
1) "1"
2) "\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x001"
`
如果我要累加RMapCache 所有 value 值，只能所有都取出来for 循环累加么？

Thanks,
