### ISSUE TITLE
What is the best practice for setting local caches ttl against Redis caches?

### ISSUE THREAD

**Issue by bkoroliuk-amplify** [redisson/redisson#1706]
Is it correct if Redis cache ttl is the same as timeToLiveInMillis for local cache?

MY_CACHE: 
 ttl: 300000
 maxIdleTime: 300000
 maxSize: 1000
 
 localCacheOptions:
    evictionPolicy: "LRU"
    reconnectionStrategy: "CLEAR"
    syncStrategy: "INVALIDATE"
    writeMode: "WRITE_THROUGH"
    cacheSize: 1000
    timeToLiveInMillis: 300000
    maxIdleInMillis: 300000

**Comment by mrniko** [comment]
Do you use RMapCache and RLocalCachedMapCache under the same name?

**Comment by bkoroliuk-amplify** [comment]
Yes

**Comment by bkoroliuk-amplify** [comment]
> Do you use RMapCache and RLocalCachedMapCache under the same name?

yes

**Comment by mrniko** [comment]
That's a bad idea, since compatibility between these objects is not guaranteed.

**Comment by bkoroliuk-amplify** [comment]
MY_CACHE:
ttl: 300000
maxIdleTime: 300000
maxSize: 1000

localCacheOptions:
evictionPolicy: "LRU"
reconnectionStrategy: "CLEAR"
syncStrategy: "INVALIDATE"
writeMode: "WRITE_THROUGH"
cacheSize: 1000
timeToLiveInMillis: 0
maxIdleInMillis: 0

**Comment by bkoroliuk-amplify** [comment]
What about this setup?
```
MY_CACHE:
ttl: 300000
maxIdleTime: 300000
maxSize: 1000

localCacheOptions:
evictionPolicy: "LRU"
reconnectionStrategy: "CLEAR"
syncStrategy: "INVALIDATE"
writeMode: "WRITE_THROUGH"
cacheSize: 1000
timeToLiveInMillis: 0
maxIdleInMillis: 0
```

**Comment by mrniko** [comment]
That config looks correct. What is your concerns about it?

**Comment by bkoroliuk-amplify** [comment]
@mrniko No concerns, thank you

**Comment by mrniko** [comment]
@bkoroliuk-amplify 

You're welcome!
