### ISSUE TITLE
RLocalCachedMap fetches results even after disconnected from Redis Server

### ISSUE THREAD

**Issue by shivendra-kumar** [redisson/redisson#1707]
### Redisson configuration:

	config = new Config();
		config.useSingleServer().setAddress("redis://10.0.50.128:6222");
		config.useSingleServer().setPassword("shivendra");
		config.useSingleServer().setDatabase(0);

		config.useSingleServer().setRetryAttempts(3);
		config.useSingleServer().setConnectionPoolSize(500);
		config.useSingleServer().setRetryInterval(2000);
		config.useSingleServer().setConnectTimeout(30000);
		config.useSingleServer().setPingConnectionInterval(5000);
		config.useSingleServer().setPingTimeout(5000);
		FstCodec codec = new FstCodec();
		config.setCodec(codec);
		redisson = (Redisson) Redisson.create(config);

		options = TransactionOptions.defaults()

				.syncSlavesTimeout(5, TimeUnit.SECONDS).responseTimeout(3, TimeUnit.SECONDS)
				.retryInterval(5, TimeUnit.SECONDS).retryAttempts(3).timeout(40, TimeUnit.SECONDS);
	

		map = redisson.getLocalCachedMap("lock_test", LocalCachedMapOptions.defaults().syncStrategy(SyncStrategy.INVALIDATE).reconnectionStrategy(ReconnectionStrategy.CLEAR));
		rMap = redisson.getMap("lock_test");

**Comment by shivendra-kumar** [comment]
As per our requirement we need to stop responding to get requests once Redisson gets disconnected to Redis server and throw an exception.

**Comment by shivendra-kumar** [comment]
@mrniko Can we expect any resolution any time soon? As our further development depends on this.

**Comment by debashishbharali** [comment]
@mrniko  We are also facing the same issue. Please respond.

**Comment by debashishbharali** [comment]
When can we expect the release for this issue?
As per my understanding, the PUB-SUB model that redisson provided is incomplete without this handling?

**Comment by shivendra-kumar** [comment]
@mrniko @jackygurui Any updates on this?

**Comment by mrniko** [comment]
> As per our requirement we need to stop responding to get requests once Redisson gets disconnected to Redis server and throw an exception.

You can handle this case by setting [connectionListener](https://github.com/redisson/redisson/wiki/2.-Configuration#connectionlistener)
