### ISSUE TITLE
All lua script are sent to slot 0 only 

### ISSUE THREAD

**Issue by werder06** [redisson/redisson#1709]
We use Reddison as a client for high load sharded Redis cluster consists of 8 nodes. Main use case -  big number of relatively small lua scripts. We use code like this to do it. (Used version is 3.7.5, but I believe same behavior is in trunk)
```java
RScript script = redisson.getScript();
Long result = script.evalSha(RScript.Mode.READ_WRITE, loadedScript, RScript.ReturnType.VALUE, keys, values);
```
After some performance tests we noticed that load on Redis cluster nodes is uneven - CPU utilization on node which holds '0 slot' was two times higher then on other nodes. It happens because Reddison sends all scripts to '0 slot' and then this node have to 'MOVED' script to correct node for processing. This overloads '0 slot' node.

So we have to find a workaround to send scripts to correct node: 
```java
RedissonScript script = (RedissonScript) redisson.getScript(); // cast to class here to get right method 
Long result = script.evalSha(correctMessageKey, RScript.Mode.READ_WRITE, JsonJacksonCodec.INSTANCE,  loadedScript, RScript.ReturnType.VALUE, keys, values);
```
So I wonder if this a bug or feature?

**Comment by mrniko** [comment]
I agree, method signatures with key param should be exposed via RScript interface.

**Comment by mrniko** [comment]
Already done in https://github.com/redisson/redisson/commit/b83812754a74ce9973fb347f2cdc3959eccfc15c

**Comment by werder06** [comment]
Yep, didn't check latest changes. 

Thnks
