### ISSUE TITLE
Missing code on version 3.8.2 at Maven Central

### ISSUE THREAD

**Issue by arturgaleno** [redisson/redisson#1710]
Hi,

When I debugged the class `MultiDnsAddressResolverGroup` and compared with this commit:

https://github.com/redisson/redisson/blob/f08cac4beb6d98f0538c44cc0ea26cc194ab1cdf/redisson/src/main/java/org/redisson/connection/dns/MultiDnsAddressResolverGroup.java#L58

I found that the code deployed to https://search.maven.org/artifact/org.redisson/redisson/3.8.2/bundle is missing this line (that is supposed solve the issue).

Maybe this code is missing in the compiled version too?

### Redisson version
3.8.2

### Redisson configuration

**Comment by mrniko** [comment]
This change is not included in 3.8.2 but 3.9.0

**Comment by arturgaleno** [comment]
I see! Thank you!
