### ISSUE TITLE
Questions about performance of RLocalCachedMap

### ISSUE THREAD

**Issue by julialiu15** [redisson/redisson#1712]
I'm playing with the Redisson's great feature for near cache, then did some benchmark testing on it.

It brings a huge performance boost compares to directly interacting with redis, however it's takes much longer than "real" local cache, especially for put operation, around 100~200 times longer. For instance, each Redisson fastPutAsync takes around 175536ns, while real local cache finishes in 1060ns; Redisson get takes 9737ns, real local cache takes 151ns. This can become quite noticeable for read/write intensive applications.

From the reading on document/wiki on RLocalCachedMap, it essentially keeps a local copy of the cache in application's memory, performance should be roughly the same as real local cache. Any thoughts / suggestions on the slowness of RLocalCachedMap please?

Thanks.

**Comment by mrniko** [comment]
what do you mean real local cache? Please note, that it uses not usual Map object for local cache but custom with LRU, LFU element eviction algorithms. These algorithms may affect performance.

**Comment by julialiu15** [comment]
Thank you for prompt reply. 

"real local cache" here means without using external data-storage system(like redis or memcached), everything is stored directly in application memory (JVM), like a HashMap, read/write is blazing fast.

Did more testing with eviction policy on(LRU) and off, performance difference are negligible(when cache size hasn't reached limit). Haven't dive deep into the RLocalCachedMap's code, seems like when we're doing `get()`, it first check in local map, if corresponding key is found, returns value immediately(this gives us the performance boost, from Redisson wiki: _up to 45x faster in comparison with usual implementation_); if it's not in local map, then it will make the trip to remote redis (read-through). Thus if the cache is found in local cache, we are expecting similar performance on `get()`, RLocalCachedMap vs. "real local cache"?

**Comment by julialiu15** [comment]
Thanks for confirming that. 
As mentioned in pervious post, they're run with data already in local cache. RLocalCachedMap brings a performance boost compared to directly hitting redis server, but still much slower than a traditional "real local cache".
You have much more in-depth knowledge with Redisson, do you mind shedding some light on the reason behind the scenes / suggestions to improve this?

**Comment by mrniko** [comment]
> much slower than a traditional "real local cache".

Which implementation do you mean here?

**Comment by julialiu15** [comment]
https://github.com/redisson/redisson/issues/1712#issuecomment-435509500
> "real local cache" here means without using external data-storage system(like redis or memcached), everything is stored directly in application memory (JVM), like a HashMap, read/write is blazing fast.

**Comment by mrniko** [comment]
HashMap doesn't have LRU, LFU eviction, so it works much faster
