### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by lbernollin** [redisson/redisson#1713]
### Actual behavior
I got some classCastException :
`Exception in thread "redisson-3-38" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at org.redisson.spring.session.RedissonSessionRepository$RedissonSession.load(RedissonSessionRepository.java:103)
        at org.redisson.spring.session.RedissonSessionRepository.findById(RedissonSessionRepository.java:310)
        at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:252)
        at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:52)
        at org.redisson.PubSubPatternMessageListener.onPatternMessage(PubSubPatternMessageListener.java:80)
        at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:87)
        at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:181)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
` 
Here the payload that redisson trying to decode : 
`1) "\"session:maxInactiveInterval\""
2) "1800"
3) "\"session:lastAccessedTime\""
4) "[\"java.lang.Long\",1540985842940]"
5) "\"session:creationTime\""
6) "[\"java.lang.Long\",1540985842937]"` 

If we check into the source code 
https://github.com/redisson/redisson/blob/redisson-3.7.5/redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java
at l:103 with see that you are trying to cast into a Long. On older version you used to cast it into an Integer.
Unfortunately i cannot decrease my redisson version because i have updated spring session in 2.x.x .
I think you can keep a cast into an Integer. I don't think people will configure the session ttl to more than 2147483647 seconds.
### Redisson version
redisson : 3.7.5
spring boot : 2.0.4.RELEASE
spring session: 2.0.5.RELEASE
### Redisson configuration
`
@Configuration
@EnableRedissonHttpSession
public class RedissonConfig implements BeanClassLoaderAware
{
    @Autowired
    private RedisProperties redisProperties;

    private static final int CONNECTION_TIMEOUT = 3000;
    private static final int TIMEOUT = 10000;
    private static final int THREAD_NUMBER = 4;

    private ClassLoader loader;

    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient()
    {
        if (redisProperties.isSingleServer()) {
            return Redisson.create(singleServer());
        }
        return Redisson.create(sentinelServers());
    }

    private Config baseConfig()
    {
        return new Config()
                .setNettyThreads(THREAD_NUMBER)
                .setThreads(THREAD_NUMBER)
                .setCodec(new JsonJacksonCodec(mapper()));
    }

    private Config sentinelServers()
    {
        final Config config = baseConfig();
        config.useSentinelServers()
                .setConnectTimeout(CONNECTION_TIMEOUT)
                .setTimeout(TIMEOUT)
                .addSentinelAddress(split(redisProperties.getAddresses(), ", "))
                .setMasterName(redisProperties.getMasterName())
                .setPassword(redisProperties.getPassword());
        return config;
    }

    private Config singleServer()
    {
        final Config config = baseConfig();
        config.useSingleServer()
                .setConnectTimeout(CONNECTION_TIMEOUT)
                .setTimeout(TIMEOUT)
                .setAddress(redisProperties.getAddresses())
                .setPassword(redisProperties.getPassword());
        return config;
    }

    @Override
    public void setBeanClassLoader(final ClassLoader classLoader)
    {
        this.loader = classLoader;
    }

    private ObjectMapper mapper()
    {
        final ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        mapper.registerModules(SecurityJackson2Modules.getModules(this.loader));
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
        mapper.setSerializationInclusion(Include.NON_NULL);
        mapper.addMixIn(Throwable.class, JsonJacksonCodec.ThrowableMixIn.class);
        mapper.findAndRegisterModules();
        return mapper;
    }

}`

**Comment by lbernollin** [comment]
To be more helpful. This issue happened when we have a quite heavy load on the application. (Our redis server is not stuck. We got no issue on that side)
redis version : 4.0.2

**Comment by mrniko** [comment]
"session:maxInactiveInterval" stored as int only in 2.x version. Seems your application uses different base lines of Redisson - 2.x and 3.x. I wouldn't recommend that, since they're are not compatible.

**Comment by lbernollin** [comment]
@mrniko  thanks for you reply.
What do you mean "Seems your application uses different base lines of Redisson - 2.x and 3.x" ?
All my application using Redisson client to writte or read into my redis server are in 3.x version (They are always at the same version)
Each time i updated the redisson version i used to clean all my keys into the redis server. I am also confident to be the only one guys to use the redis server.

**Comment by mrniko** [comment]
@lbernollin 

Below is Redisson Spring Session state for 3.9.0 version:

```
18:54:41 [redisson-netty-14-8] TRACE org.redisson.client.handler.CommandDecoder - reply: *8
$29
"session:maxInactiveInterval"
$23
["java.lang.Long",1800]
$26
"session:lastAccessedTime"
$32
["java.lang.Long",1541433281778]
$22
"session:creationTime"
$32
["java.lang.Long",1541433261112]
$6
"test"
$3
"2"
```
As you can see `session:maxInactiveInterval` stored correctly, as long.

**Comment by lbernollin** [comment]
I will try to find who write data as integer.

Thank you for your time

**Comment by lbernollin** [comment]
@mrniko  
Looks like the 3.5.7 version of Redisson is "behaving" like the version 2.
We have actually two different applications.
One was using the 3.7.5 and the other the 3.5.7

We are using redisson in combination with SpringSession and we faced some very strange behaviors with sessions jumping from one application node to another. We would like to know if the exception we faced could be the source of the issue with the sessions.

**Comment by mrniko** [comment]
@lbernollin 

Do you use 3.7.5 and 3.5.7 versions on the same Redis setup? If so, it's better to update it to 3.7.5

**Comment by lbernollin** [comment]
@mrniko  i agree to update it in 3.7.5. For that we need to update the spring session also. 
Istill have a last question .
If i undertstand well i got the ClassCast exception because i am using 3.5.7 and 3.7.5 reading/writting into the same redis. 
Why my app using 3.7.5 reading data writte by my app using 3.5.7 ? it is not the same session key . it should not read data that is not manage by my app.
