### ISSUE TITLE
在腾讯云中Redis使用的时候,所有带Cache的类都会报错

### ISSUE THREAD

**Issue by satanmonkey** [redisson/redisson#1714]
org.redisson.client.RedisException: ERR Error running script (call to f_c7545856d197b86a5f3527597afb440f1edcafa3): @enable_strict_lua:15: user_script:1: Script attempted to access unexisting global variable 'struct' . channel: [id: 0xf83f8de3, L:/172.18.0.10:55606 - R:10.107.48.9/10.107.48.9:6379] command: (EVAL), params: [local insertable = false; local v = redis.call('hget', KEYS[1], ARGV[5]); if v == false then inserta..., 8, UserBindDeviceMap, redisson__timeout__set:{UserBindDeviceMap}, redisson__idle__set:{UserBindDeviceMap}, redisson_map_cache_created:{UserBindDeviceMap}, redisson_map_cache_updated:{UserBindDeviceMap}, redisson__map_cache__last_access__set:{UserBindDeviceMap}, redisson_map_cache_removed:{UserBindDeviceMap},

### Steps to reproduce or test case
使用带Cache字样的类都会触发,
### Redis version
v2.8
### Redisson version
3.7.5
### Redisson configuration

            config.useSingleServer()
                .setAddress(redisServer);
            Redisson.create(config);

**Comment by aieyes** [comment]
同样，因为腾讯云的redis，白使用了...
