### ISSUE TITLE
RLocalCachedMap Subscribe timeout

### ISSUE THREAD

**Issue by titus12** [redisson/redisson#1717]
你好，我在测试关于RLocalCachedMap的功能，发现订阅数的配置数量会引发超时，并且此线程重试读取依然超时。
测试项目如下：
https://github.com/titus12/TestRedissonTemporary2.git
count = 100,会出问题，count < 50 正常，
redisson.yaml 配置中
subscriptionsPerConnection = 5，subscriptionConnectionPoolSize = 10

**Comment by titus12** [comment]
RLocalCachedMap 有模糊话题？

**Comment by titus12** [comment]
“当没有空余连接的情况下，继续追加订阅时，该命令在等待超过了规定时间后，仍然无法取得一个空余连接，此时就会触发超时报错的行为”
我准备试下等超时之后，并且再过一段时间，看看订阅连接是否能被空闲出来

**Comment by titus12** [comment]
测试了，并没有空闲出来

**Comment by jackygurui** [comment]
上面的描述是针对这个报错的解答，针对你的具体情况，只有释放RLocalCachedMap对象才能释放订阅的连接。

**Comment by titus12** [comment]
是不是RLocalCachedMap对象调用他的destroy()方法？

**Comment by jackygurui** [comment]
对

**Comment by jackygurui** [comment]
重现不了。
你是怎么释放的呢？

**Comment by titus12** [comment]
测试代码已经提交到https://github.com/titus12/TestRedissonTemporary2.git，
我是用destroy()方法释放的

**Comment by jackygurui** [comment]
你是不是搞得太复杂了？我的测试代码是这样的：
```
    public static void main(String ... args) {
        int connection = 10;
        int subscription = 5;
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://localhost:6379")
                .setSubscriptionConnectionPoolSize(connection)
                .setSubscriptionsPerConnection(subscription);
        RedissonClient redissonClient = Redisson.create(config);
        final Queue<RLocalCachedMap> queue = new LinkedList<>();
        int i = 0;
        while (true) {
            if (queue.size() == connection * subscription) queue.poll().destroy();
            final RLocalCachedMap<Integer, Integer> map = redissonClient.<Integer, Integer>getLocalCachedMap(++i + "", LocalCachedMapOptions.defaults());
            map.put(i, i);
            queue.offer(map);
            System.out.println(i + " - " + queue.size());
        }
    }
```

**Comment by titus12** [comment]
我明白了，一旦发生了异常再去尝试着释放就不起作用了。你测试下下面的代码：
 public static void main(String ... args) {
        int connection = 10;
        int subscription = 5;
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://localhost:6379")
                .setSubscriptionConnectionPoolSize(connection)
                .setSubscriptionsPerConnection(subscription);
        RedissonClient redissonClient = Redisson.create(config);
        final Queue<RLocalCachedMap> queue = new LinkedList<>();
        int i = 0;
        boolean timeout = false;
        while (true) {
           try{
              if (queue.size() == connection * subscription + 1 || timeout) queue.poll().destroy();
              final RLocalCachedMap<Integer, Integer> map = redissonClient.<Integer, 
                Integer>getLocalCachedMap(++i + "", LocalCachedMapOptions.defaults());
              map.put(i, i);
              queue.offer(map);
              System.out.println(i + " - " + queue.size());
           }catch(Exception e){
                timeout = true;
                e.printStackTrace();
           }
        }
    }

**Comment by mrniko** [comment]
Fixed! Thanks for report
