### ISSUE TITLE
Redisson 2.13.1+ no longer work on Java 1.6

### ISSUE THREAD

**Issue by natecarlson** [redisson/redisson#1719]
### Expected behavior

Per the main README:
https://github.com/redisson/redisson/blob/master/README.md

Redisson 2.14.0 should work on Java 1.6.

### Actual behavior

Redisson 2.13.1 and above have the class files compiled with version 51.0 (Java 1.7), and will no longer work on 1.6.

**Comment by mrniko** [comment]
Fixed! Thanks for report
