### ISSUE TITLE
ZREVRANGEBYSCORE issue

### ISSUE THREAD

**Issue by sheldon-sminq** [redisson/redisson#1720]
### Expected behavior
We use a score sorted set to store our user story timelines, these scores are in the form of timestamps
```
        RScoredSortedSet storyTimeLine = redissonClient.getScoredSortedSet("timeline");
        storyTimeLine.add(timestamp,storyId);
```
### Actual behavior
```
Collection<String> stories = timeline.valueRangeReversed(startDate.intValue(), endDate.intValue());
```
should return the list of stories but it returns empty.

### Steps to reproduce or test case

When i run the same command from the redis terminal it returns the values

```
ZREVRANGEBYSCORE timeline 1541425420 1540785105 withscores limit 0 100
```
### Redis version
4.0.0

### Redisson version
3.8.0

**Comment by mrniko** [comment]
You should use `RScoredSortedSet.valueRange(double startScore, boolean startScoreInclusive, double endScore, boolean endScoreInclusive)` method instead
