### ISSUE TITLE
Jcache public V get(K key) Method

### ISSUE THREAD

**Issue by stkggit** [redisson/redisson#1722]
Hi,
I'm Using Jcache with AWS Redis in replicatedServersConfig, but observed jcache get / put operation is always using  master node to for both read and write operations. 
in my view get request should go to slave (read) node, put request should go to master node.
Please suggest anything to be changed in my configuration / correct me if i'm wrong.
my cache config:
{
   "replicatedServersConfig":{
      "idleConnectionTimeout":600000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":5000,
      "retryAttempts":3,
      "retryInterval":1500,
      "failedSlaveReconnectionInterval":3000,
      "failedSlaveCheckInterval":60000,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "subscriptionConnectionMinimumIdleSize":5,
      "subscriptionConnectionPoolSize":50,
      "slaveConnectionMinimumIdleSize":30,
      "slaveConnectionPoolSize":50,
      "masterConnectionMinimumIdleSize":30,
      "masterConnectionPoolSize":50,
      "readMode":"SLAVE",
      "subscriptionMode":"SLAVE",
      "nodeAddresses":[
        "redis://******.******.*****.cache.amazonaws.com:6379",
        "redis://******.******.*****.cache.amazonaws.com:6379"
      ],
      "scanInterval":3000,
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.SnappyCodec"
   },
   "transportMode":"NIO"
}

**Comment by mrniko** [comment]
It uses master node since it modifies Redis data - writes entry end of life timeout

**Comment by stkggit** [comment]
Hi ,
If it is always going to master node then what is the use of configuring slave node.

Thanks,

**Comment by mrniko** [comment]
Done! Also did some optimizations and got 2x performance boost. Please check
