### ISSUE TITLE
Does RedissonRedLock support Redis cluster Master/Slave mode?

### ISSUE THREAD

**Issue by faceany** [redisson/redisson#1728]
In this issue[https://github.com/redisson/redisson/issues/1333#issuecomment-371817371](https://github.com/redisson/redisson/issues/1333#issuecomment-371817371)  I found that RedissonRedLock supports Redis cluster mode. In the **Redlock algorithm** [https://redis.io/topics/distlock](https://redis.io/topics/distlock),I don't think it supports  Master/Slave mode.The description is:

> In the distributed version of the algorithm we assume we have N Redis masters. Those nodes are totally independent, so we don’t use replication or any other implicit coordination system. 

For example:
The Redis cluster 1 is as follows:
**Master1 Slave1
Master2 Slave2
Master3 Slave3**

The Redis cluster 2 is as follows:
**Master1 
Master2 
Master3**

I am troubled. _**Does it support  type of  Redis cluster 1 ?**_
.If it supports then how do I add a configuration, whether the master and slave are added or only the master configuration is added.
For example :
Add as **type1**
```
Config config = new Config();
config.useClusterServers().addNodeAddress(Master1, Master2,Master3, Slave1,Slave2, Slave3);
RedissonClient redisson = Redisson.create(config);
RLock lock1 = redisson.getLock(lockName + "1");
RLock lock2 = redisson.getLock(lockName + "2");
RLock lock3 = redisson.getLock(lockName + "3");
RLock lock4 = redisson.getLock(lockName + "4");
RLock lock5 = redisson.getLock(lockName + "5");
RLock lock6 = redisson.getLock(lockName + "6");
```
Add as **type2**
```
Config config = new Config();
config.useClusterServers().addNodeAddress(Master1, Master2,Master3);
RedissonClient redisson = Redisson.create(config);
RLock lock1 = redisson.getLock(lockName + "1");
RLock lock2 = redisson.getLock(lockName + "2");
RLock lock3 = redisson.getLock(lockName + "3");
```
Add as **type3**
```
Config config = new Config();
config.useClusterServers().addNodeAddress(Master1, Master2,Master3, Slave1,Slave2, Slave3);
RedissonClient redisson = Redisson.create(config);
RLock lock1 = redisson.getLock(lockName + "1");
RLock lock2 = redisson.getLock(lockName + "2");
RLock lock3 = redisson.getLock(lockName + "3");

```
**_Which type should I choose,or they are all wrong?_**

### Redis version
3.x

**Comment by jackygurui** [comment]
I think they all right, providing the naming scheme (lockName + sequence) is able to distribute the lock evenly one each node.

**Comment by faceany** [comment]
@jackygurui thank you  I will  try it.

**Comment by mrniko** [comment]
@faceany 

In your examples locks won't be spread by nodes automatically. It's up to developer to select proper name located at concrete Redis node.

**Comment by wy545** [comment]
@faceany i think if the node(msater) has slave, and the master is hung, the slave will be changed to master .
And, what is the result of the type1, type2 and type3

**Comment by DarrenJiang1990** [comment]
RLock lock1 = redisson.getLock(lockName + "1");
RLock lock2 = redisson.getLock(lockName + "2");
RLock lock3 = redisson.getLock(lockName + "3");

can not ensure  lock1、lock2、lock3  having lock of  Master1 、Master2 、Master3

**Comment by jackygurui** [comment]
You can use predetermined value in the key name and use `{}` to force the key slot calculation onto your desired node.
