### ISSUE TITLE
sentinel bug ?

### ISSUE THREAD

**Issue by walkersing** [redisson/redisson#1731]
### Expected behavior
![image](https://user-images.githubusercontent.com/4715142/48325213-82803a00-e66f-11e8-9422-296cf3a8aa6a.png)

### Actual behavior
spring.redis.sentinel.nodes=192.168.1.241:26379,192.168.1.241:36379,192.168.1.241:46379

### Steps to reproduce or test case
![image](https://user-images.githubusercontent.com/4715142/48325244-9c218180-e66f-11e8-93fb-b9023ab04c48.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
