### ISSUE TITLE
Add own Hibernate cache implementation

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#1732]
Current 3rd party implementation https://github.com/debop/hibernate-redis seems is not developed anymore and doesn't support hibernate 5.3

**Comment by mrniko** [comment]
@johnou 

Could you please review it and give your feedback?

**Comment by johnou** [comment]
@mrniko it's a shame getLocalCachedMapCache didn't make it into the community edition ;)

**Comment by jackygurui** [comment]
His bread and butter has to come from somewhere.

**Comment by johnou** [comment]
@jackygurui I think Redisson offers many more features which would be important for enterprise customers - in particular 24x7 technical support with SLA. Availability of intermediate releases with hot fixes, and the distributed collections. RedissonLocalCachedMapCache feels like a simple subclass of RedissonLocalCachedMap..

**Comment by zarco** [comment]
Hi guys, do you know when this is going to be available in Maven Central? I couldn't find any version of this artifact anywhere...

**Comment by mrniko** [comment]
@zarco 

Hello! During this month
