### ISSUE TITLE
Unable to send command on Azure Redis

### ISSUE THREAD

**Issue by LukeBolide92** [redisson/redisson#1733]
Hi,
I would like to ask for your help because I experienced a lack of connection with the PaaS Azure element of Redis Cache last Saturday. 
The exception thrown is related to CommandAsyncService, please find in the attachment.
I’m using version 3.6.5 of redisson, in the following you find redisson.conf.
It seems that in that day the tomcat running on a VM could not write on Redis with commands HMSET and DEL, throwing the exception mentioned before. The immediate solution was to restart tomcat service so that connection was re-established.
Do you know if this issue is fixed in later versions? What would you suggest to do in this circumstances?

{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":"TdyTFjnGmdscWoEUy/lgejuMeDD/jIUsWZeLeewHaDs=",
      "subscriptionsPerConnection":5,
      "clientName":"IOTIM-FE-01-PROD",
      "address": "redis://iotim-sl-fe-prod-session.redis.cache.windows.net:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":10,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoring":false,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":null,
   "useLinuxNativeEpoll":false
}
[reddison.log](https://github.com/redisson/redisson/files/2576064/reddison.log)

**Comment by mrniko** [comment]
Set `nettyThreads` value to 32 or 64.
