### ISSUE TITLE
Can redisson allow 1 sentinel with configuration?

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#1735]
Our environment has 3 varieties:
S(SMALL): 1 sentinel + 1 redis master
M(MIDDLE): 3 sentinels + 1 master + 1 slave
L(LARGE): X sentinels + 1 master + Y slave
And our EVN has scaling path: S->M->L
### Expected behavior
In each ENV, redisson works fine. I understand at least 2 sentinels can guarantee master->slave failover, but in our SMALL ENV, we only have 1 master, no HA required. we are forced to use redisson old version(3.6.0) as it allows 1 sentinel. The reason why keep sentinel here is to make it no difference with M and L environment, we can use very same redisson configuration and code in each ENV.

My suggestion is to make it configurable, so that redisson reject 1 sentinel configuration by default but allows user to enable it in case needed.
### Actual behavior

When in SMALL ENV, redisson will throw below exception:
 throw new RedisConnectionException("At least two sentinels should be defined in Redis configuration!")

### Steps to reproduce or test case
Configure 1 sentinel + 1 redis master
### Redis version
any
### Redisson version
3.8.1
### Redisson configuration
1 sentinel + 1 redis master

**Comment by mrniko** [comment]
According to the documentation - https://redis.io/topics/sentinel

`You need at least three Sentinel instances for a robust deployment.`

**Comment by empty117** [comment]
ok, is that possibile to make it configurable? Sometimes we are expecting a minimum set up(in my SMALL ENV), which doesn't require  a robust deployment , but redisson client forced it.

**Comment by GitHubDongChen** [comment]
I agree with @empty117  opinion, make it configurable is better.

**Comment by jackygurui** [comment]
What is the point of having a sentinel when a master has no slaves?

**Comment by empty117** [comment]
@jackygurui :The point is to allow environment  be scalable. Let's say we have 3 sentinels and 1 master + X slaves:

- When slave number can be easily/dynamically change between 0-2 to adapt business load. But whenever slave come to 0, redisson cannot work. Current i did workaround  to overwrite SentinelConnectionManager to allow this. If you can officially support it, that would be better.
