### ISSUE TITLE
RDelayedQueue got delay long time when offer a task with negative time

### ISSUE THREAD

**Issue by RogerFang** [redisson/redisson#1744]
```
RedissonClient redissonClient = redisService.getRedissonClient();
RBlockingQueue readyQueue = redissonClient.getBlockingQueue("delay_queue");
RDelayedQueue delayedQueue = redissonClient.getDelayedQueue(readyQueue );

delayedQueue.offer("1111", -2515194, TimeUnit.SECONDS);
```

### Expected behavior
offer an element with delay time (-2515194, "2018-11-20 20:00:52") when create time is "2018-11-20 20:42:08".

I expect that it transfers to readyQueue right now.

### Actual behavior
but after a long time I got it from the readyQueue at "2018-11-20 21:00:10".

### Redisson version
3.9.0

**Comment by RogerFang** [comment]
Now, I got another problem, the delayQueue seems blocked, which doen't transfer element to readyQueue.

**Comment by mrniko** [comment]
How to reproduce that?

**Comment by aawu** [comment]
it seems like the issue "delayedQueue cannot get elements from blockingQueue #1699".And i have the similar issue which is occurred randomly.And the code below the queue will lost some elements.
**Redisson version**
3.10.1
**Steps to reproduce or test case**
public static void main(String[] args) {
        RedissonClient redissonClient = Redisson.create();
        RBlockingQueue<String> blockingQueue = redissonClient.getBlockingQueue("queue");
        RDelayedQueue<String> delayedQueue = redissonClient.getDelayedQueue(blockingQueue);
        int total = 100;

        ExecutorService putService = Executors.newFixedThreadPool(1);
        putService.execute(new Runnable() {
            @Override
            public void run() {

                for (int i = 0; i < total ; i++) {
                    String trunk = "id"+i;
                    delayedQueue.offer(trunk, 60, TimeUnit.SECONDS);
                }
            }
        });


        ExecutorService pullService = Executors.newFixedThreadPool(1);
        pullService.execute(new Runnable() {
            @Override
            public void run() {
                int counter = 0;
                while (true) {
                    try {
                        counter++;
                        String trunk = blockingQueue.take();
                        System.out.println(trunk);
                        if(counter == total){
                            System.out.println("finish");
                            break;
                        }
                    } catch (InterruptedException e) {
                        break;
                    }
                }

                redissonClient.shutdown();
            }
        });
    }

**Comment by mrniko** [comment]
@aawu 

Unable to reproduce it with 3.10.3 and follow test:

```java
    @Test
    public void test() throws InterruptedException {
        for (int i = 0; i < 5; i++) {
            test1();
        }
    }
    
    public void test1() throws InterruptedException {
        RBlockingQueue<String> blockingQueue = redisson.getBlockingQueue("queue");
        RDelayedQueue<String> delayedQueue = redisson.getDelayedQueue(blockingQueue);
        int total = 1000;

        ExecutorService putService = Executors.newFixedThreadPool(1);
        putService.execute(new Runnable() {
            @Override
            public void run() {

                for (int i = 0; i < total ; i++) {
                    String trunk = "id"+i;
                    delayedQueue.offer(trunk, 60, TimeUnit.SECONDS);
                }
            }
        });


        Set<String> set = Collections.newSetFromMap(new ConcurrentHashMap<>());
        CountDownLatch latch = new CountDownLatch(total);
        ExecutorService pullService = Executors.newFixedThreadPool(1);
        pullService.execute(new Runnable() {
            @Override
            public void run() {
                int counter = 0;
                while (true) {
                    try {
                        counter++;
                        String trunk = blockingQueue.take();
                        set.add(trunk);
                        if(counter == total){
                            latch.countDown();
                            break;
                        } else {
                            latch.countDown();
                        }
                    } catch (InterruptedException e) {
                        break;
                    }
                }
            }
        });        
        
        latch.await();
        assertThat(set).hasSize(total);
    }
```

Which Redis version do you use?
