### ISSUE TITLE
Issues with RBitSet - Value does not stick

### ISSUE THREAD

**Issue by arkothari** [redisson/redisson#1751]
I am new to Redis and Redisson. I am trying to set a RMap<String,BitSet>. I call the put method on my RMap object, but when i do the get, I always get a empty BitSet. If i use RMap<String,RBitSet>, iterating over the map results in a "java.lang.ClassCastException: org.redisson.RedissonReference cannot be cast to org.redisson.api.RBitSet"

RMap<String,BitSet> data = redisson.getMap("data-00");
BitSet bs = new BitSet(10);
		bs.set(5);
		bs.set(7);
data.put("a", bs);

RMap<String,BitSet> data1 = redisson.getMap("data-00");
		for (Map.Entry<String, BitSet> entry : data1.entrySet()) {
			System.out.println(entry.getKey()+" = "+entry.getValue());
		}

**Comment by mrniko** [comment]
Fixed! Thanks for report
