### ISSUE TITLE
The Redisson connection to Redis master node will break down after Redis slave node is up from down

### ISSUE THREAD

**Issue by zhanshen8D** [redisson/redisson#1752]
### Expected behavior
We have application using Redisson to access Redis cluster(3 masters+3 slaves).
We have a test case which is to shutdown one or more Redis slave nodes then take it up.
We don't expect there is any Redisson Connection broken on the master nodes since we only take action on the slave nodes.

### Actual behavior
It is found after Redis slave node is shutdown and taken up, the Redisson connection to its master node will be broken.
By checking the Redisson 3.9.0(also the latest 3.9.1), it is found after a slave node is up, on its master node, Redisson will try to release the connection from all others except this slave node.
Here "all others" has included the connection from the application.
MasterSlaveEntry.java: Function "public boolean slaveUp(URI address, FreezeReason freezeReason)"
Not sure my understanding is correct or not.

### Steps to reproduce or test case
Like above, in a Redis cluster, after restarting the slave nodes, the Redisson connections to the master nodes will be broken. 

### Redis version
4.0.8

### Redisson version
3.9.0

### Redisson configuration
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 15000
  connectTimeout: 10000
#  timeout: 60000
  timeout: 30000
  retryAttempts: 3
  retryInterval: 1500
#  retryInterval: 1500
  reconnectionTimeout: 1000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 2
  slaveConnectionPoolSize: 2
  masterConnectionMinimumIdleSize: 3
  masterConnectionPoolSize: 3
  readMode: "MASTER_SLAVE"
  nodeAddresses:
   - "redis://HOST1:6000"
#  - "redis://[HOST2]:5301"
#  - "redis://[HOST3]:5301"
  scanInterval: 10000
threads: 32
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false

**Comment by mrniko** [comment]
Fixed in 3.10.0
