### ISSUE TITLE
setting to expire time

### ISSUE THREAD

**Issue by tuyu79** [redisson/redisson#1759]
### Description
Hello,i am using spring boot redisson starter in version 3.8.2. I am confusing with the expire() method and remainTimeToLive(). I learned that the remainTimeToLive() method return -1 to indicate the key will never expire,-2 to indicate the key does not exist.However,in the method expire() ,when passing -1 will result in the key not exist,passing -2 will result in the key never expire.

I gets the result by my own test case.I want to know, if that is the design or is a bug?
Thank you!

### Redis version
org.redisson:redisson-spring-boot-starter:3.8.2

**Comment by mrniko** [comment]
Could you please clarify about expire() method? Since it returns boolean type and doesn't allow to use negative value as parameter.
