### ISSUE TITLE
RedisTimeoutException when ha switched

### ISSUE THREAD

**Issue by joytom0591** [redisson/redisson#1760]
### Expected behavior
ha 切换后，（可能短暂中断后），能正常地重新连接redis。
### Actual behavior
ha 切换后，频繁出现RedisTimeoutException，有少量链接可以使用，调用方持续调用大约30分钟恢复正常。
疑似恢复路径
1、调用方调用redisson请求获取缓存
2、redisson从链接池中获取链接A
3、redisson使用链接A发送命令，发现不通，redisson断开链接A
4、redisson从链接池中获取链接B
5、redisson使用链接B发送命令，发现不通，redisson断开链接B
6、redisson从链接池中获取链接C
7、redisson使用链接C发送命令，发现不通，redisson断开链接C
8、重试三次后，报RedisTimeoutException异常。
9、等待链接池中的链接都被重置后，才会恢复正常。
PS：1-8期间偶尔有获取到正常的链接，可以正常访问，越往后几率越高。
### Steps to reproduce or test case
应用通过ha（硬件）访问redis
1、启动redis、应用
2、应用中获取缓存，使链接池中的链接均已建立与redis的链接
3、ha-A宕机，等待1-2分钟，切换到ha-B
4、应用无法连接redis，报RedisTimeoutException
### Redis version 
4.0
### Redisson version 
3.6.5
### Redisson configuration
<redission:client
        id="redissonClient"
        name="redisson1,redisson2"
        threads="0"
        netty-threads="0"
        codec-ref="jdkCodec"
        use-linux-native-epoll="false">
        <redission:sentinel-servers
            idle-connection-timeout="10000"
            ping-timeout="1000"
            connect-timeout="10000"
            timeout="3000"
            retry-attempts="3"
            retry-interval="1500"
            reconnection-timeout="3000"
            failed-attempts="3"
            subscriptions-per-connection="5"
            client-name="none"
            subscription-connection-minimum-idle-size="1"
            subscription-connection-pool-size="50"
            slave-connection-minimum-idle-size="10"
            slave-connection-pool-size="64"
            master-connection-minimum-idle-size="10"
            master-connection-pool-size="64"
            read-mode="SLAVE"
            subscription-mode="SLAVE"
            master-name="mymaster"
            database="0">
            <redission:sentinel-address value="redis://${redis.sentinel.hostname.1}:${redis.sentinel.port.1}"/>
            <redission:sentinel-address value="redis://${redis.sentinel.hostname.2}:${redis.sentinel.port.2}"/>
            <redission:sentinel-address value="redis://${redis.sentinel.hostname.3}:${redis.sentinel.port.3}"/>
        </redission:sentinel-servers>
    </redission:client>

**Comment by jinshubao** [comment]
双十一之前，一直好好的，之后一直超时异常，头疼

**Comment by joytom0591** [comment]
试过最新版，仍然有这个问题。而且设置pingConnectionTimeout参数后，更容易触发这个情况。
我另外一个同事发的issue：
https://github.com/redisson/redisson/issues/1811

**Comment by jackygurui** [comment]
@joytom0591 您那位同事认为该问题 https://github.com/redisson/redisson/issues/1811#issuecomment-453916043 已经被修复了 https://github.com/redisson/redisson/commit/44ea59f9f60ee0d2f586de7b0a5750c74783a33a 

鉴于本帖和 https://github.com/redisson/redisson/issues/1811 属于同一问题，且已经确认被修复，因此暂时将本帖子关闭。

**Comment by joytom0591** [comment]
谢谢！ @jackygurui

**Comment by jackygurui** [comment]
@joytom0591 感谢您和您的同事对我们项目的信赖和支持。
