### ISSUE TITLE
Spring xml file can't set pingConnectionInterval to BaseConfig

### ISSUE THREAD

**Issue by zhwq1216** [redisson/redisson#1761]
The redisson-1.2.xsd file dose not add the pingConnectionInterval(ping-connection-interval) attribute to "baseConfig" , so when using the spring xml can't set the pingConnectionInterval properties to BaseConfig. Can add the pingConnectionInterval attribute to the redisson-1.2.xsd file?

**Comment by zhwq1216** [comment]
The redisson-1.2.xsd sentinel-servers should remove the dns-monitoring attribute, because the SingleServerConfig had removed the dnsMonitoring properties  for the commit (5c68c38c Nikita <abracham.mitchell@gmail.com> on 2018/4/30 at 23:12).

**Comment by mrniko** [comment]
Fixed! Thanks for report
