### ISSUE TITLE
Redis URL not start with redis:// after update to 2.14.1

### ISSUE THREAD

**Issue by a2232189** [redisson/redisson#1772]
### Expected behavior
Run successfully
### Actual behavior
![38330a44a474e0bb63162d229a5744de](https://user-images.githubusercontent.com/14845223/49422967-bc58e200-f7d0-11e8-92d2-237fb0d38284.png)
![8cac75cd93c40e1913c557354d5226ea](https://user-images.githubusercontent.com/14845223/49422971-bfec6900-f7d0-11e8-88fc-067f67765e15.png)
![9bc3980ad9c8f6d144e819d5fe3b9b02](https://user-images.githubusercontent.com/14845223/49422973-c1b62c80-f7d0-11e8-8304-24085f74db31.png)

### Redisson version
2.14.1

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/21ac3d81c17c0488ee33cb87e5e46b3fb893ec93#diff-d983d2e81971a8befbc9bbb7b631610d
