### ISSUE TITLE
3.7.5 , Unable to get connection! Node source: NodeSource Azure Redis Service

### ISSUE THREAD

**Issue by wadechen2003** [redisson/redisson#1776]
### Expected behavior
Connect the Redis service and get the correct value. 
### Actual behavior
Unable to get connection! Node source: NodeSource [slot=15078, addr=//xx.xx.xxx.xx:13005, redisClient=null, redirect=MOVED, entry=null], command: (EVALSHA), command params: [63e016533d95081c5a72cb94a9bd3114ee3a48e1, 1, datakey-:1234567, PooledUnsafeDirectByteBuf(ridx: 0, widx: 725, cap: 4096)] after 3 retry attempts

pardon me covered the address by xx 

### Redis version
3.2.7 , Azure Redis cluster service 
### Redisson version
3.7.5
### Redisson configuration
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: 
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 500
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 1500
  readMode: "MASTER"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  - "redis://azureserviceaddress:6379
  scanInterval: 1000
  pingConnectionInterval: 0
  keepAlive: false

**Comment by wadechen2003** [comment]
update 
we just found, if I used the Lua script with 
redis.call('set', key[1], 'XX') 
will reproduce this issue

**Comment by mrniko** [comment]
Will check that. As a suggestion - you don't need to set so big values for connection pool

**Comment by mrniko** [comment]
MOVED redirection handled correctly. Please ensure that host //xx.xx.xxx.xx:13005 is reachable from application host

**Comment by wadechen2003** [comment]
thanks, all cluster port are available,  
Now I am guessing it was the network issue. 
I will try to move my service to another place. and try again 
thank you very much

**Comment by wadechen2003** [comment]
Pardon me sir, do you plan to add SET command with options LIKE NX|XX ?
