### ISSUE TITLE
JsonParseException: Unrecognized token '': was expecting ('true', 'false' or 'null')

### ISSUE THREAD

**Issue by biniama** [redisson/redisson#1780]
On the `redis-cli`, when I run:
`hgetall id:3bb536598d71`
I see 
```
 1) "id"
 2) "\"811\""
 3) "item"
 4) "[{\"id\": \"4429\", \"validity\": {\"startDate\": \"2018-12-06T00:00:00\", \"endDate\": \"2018-12-08T23:00:00\"}]"
 5) "show"
 6) "true"
```

But when I run:
```
Config config = new Config();
config.useSingleServer().setAddress("redis://127.0.0.1:6379");
RedissonClient client = Redisson.create(config);

RMap<String, Object> map = client.getMap("id:3bb536598d71");
map.readAllEntrySet().forEach(System.out::println);
```

It is throwing an exception.
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'show': was expecting ('true', 'false' or 'null')
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 15]
```

**Comment by jackygurui** [comment]
It appears the field and value of the hash do not have the same encoding scheme. The field seemed to be plain string whereas value were encoded as JSON strings. So trying to decode the plain string field with JSON decoder would no doubt fail since it is not a valid JSON string.

**Comment by zivziv77** [comment]
Hi

This is indeed true what you said but how can convert to json only the value and not the key?

Ziv

**Comment by jackygurui** [comment]
@zivziv77 you can create your own custom codec to handle this.

**Comment by sanwancoder** [comment]
param = JSON.stringify( param )

**Comment by durgeshkhismatrao** [comment]
You need to find what JSON is actually being parsed. Run the application within a debugger, set a breakpoint on the relevant constructor for JsonParseException ... then find out what is in the ByteArrayInputStream that it is attempting to parse
