### ISSUE TITLE
Documentation of custom builds.

### ISSUE THREAD

**Issue by kfh** [redisson/redisson#1784]
If I build the source as-is I get the 2.4.x version of Redissson, but say I want the 3.9.x version instead. What's the correct way to do it? I can't find any documentation about custom builds.

**Comment by jackygurui** [comment]
Please use 3.0.0 branch

**Comment by kfh** [comment]
Ok, thanks. It should probably be mentioned in the docs that custom builds based of master is 2.x and for 3.x use the 3.0.0 branch.
