### ISSUE TITLE
What is equivalent of JPA entity manager in Redisson

### ISSUE THREAD

**Issue by sandeeppilania** [redisson/redisson#1788]
Not an issue looking for some help with Redisson.
I would like to use Redis as a cache manager in order to cache JPA entities coming Coherence Caching. I am new to Redis and with my research found out redisson to be a good solution for the problem. So i am using Redisson Live object as replacement of JPA entities but i dont know to handle those in Redis Cache like JPA entity manager what shall i use in Redisson in my spring boot application

**Comment by mrniko** [comment]
The only JPA implementation supported by Redisson is Hibernate.
