### ISSUE TITLE
can redisson be aware of data change in redis

### ISSUE THREAD

**Issue by a2232189** [redisson/redisson#1790]
### Expected behavior
When I change data in Redis using 3rd Library other than Redisson, e.g., Jedis, I'd like Redisson be aware of that and sync the changes to local cache. 
### Actual behavior
Don't know yet, so I ask.

**Comment by jackygurui** [comment]
Short answer is No. Local cache is purely a Redisson creation, currently it does not work with other libraries without rebuild all the pipeworks using other libraries.
