### ISSUE TITLE
Android URI Fatal ERROR

### ISSUE THREAD

**Issue by WesleyLev** [redisson/redisson#1795]
https://hastebin.com/irariborob.rb

### Redis version
5.X.X
### Redisson version
3.9.1

**Comment by WesleyLev** [comment]
https://pastebin.com/d7dwSgPz

**Comment by WesleyLev** [comment]
When will the problem be solved?

**Comment by mrniko** [comment]
During this week

**Comment by mrniko** [comment]
Fixed

**Comment by WesleyLev** [comment]
Ok, it's update on grade??

(For Android Studio? ->    implementation 'org.redisson:redisson:3.9.1')

**Comment by WesleyLev** [comment]
(Because I always this error: https://pastebin.com/7PmSCrf9 )

**Comment by mrniko** [comment]
this version (3.10.0) is not released yet
