### ISSUE TITLE
Unable to connect Redis with SSL over Route53  in AWS.

### ISSUE THREAD

**Issue by kreezire** [redisson/redisson#1799]
I have created Redis5.0.0 cluster in AWS with in-transit and auth enabled.  I also have entries in Route53 that point to Redis cluster.

When I use Route53 URL, I am unable to connect to redis cluster. When I use direct end points of Redis cluster, connection is successful. 

Issue I identified: While using Route53 URL, certificated were issued by different host as compared to Route53 URL. Thus, certificate could not be validated.

How do we disable SSL certificate verification?

**Comment by kreezire** [comment]
Team - is there an update?

**Comment by mrniko** [comment]
Set `Config.sslEnableEndpointIdentification` = false
