### ISSUE TITLE
redisson-tomcat-8 share session

### ISSUE THREAD

**Issue by SpringStudent** [redisson/redisson#1806]
### Expected behavior
![image](https://user-images.githubusercontent.com/14833956/50039499-93590c80-006e-11e9-88ac-3f864f23a5f1.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/14833956/50039524-db782f00-006e-11e9-9ee5-3a17604bfb97.png)

### Steps to reproduce or test case
1.login the gy-center sys, test some apis
2.wait long time such as 2 hours not to operate gy-center api
3.the 500 Internal Error occurred like screenshot
### Redis version
3.2.10
### Redisson version
redisson-tomcat-8-3.8.2.jar
redisson-all-3.8.2.jar
### Redisson configuration
![image](https://user-images.githubusercontent.com/14833956/50039560-4c1f4b80-006f-11e9-82ec-36184ff94b76.png)

**Comment by SpringStudent** [comment]
ok, i will try, anyway thank you very much

**Comment by mrniko** [comment]
problem with RedisConnectionClosedException was fixed in https://github.com/redisson/redisson/issues/1748
