### ISSUE TITLE
drainTo when only one element exists

### ISSUE THREAD

**Issue by mkurt** [redisson/redisson#1809]
### Expected behavior
queue should be empty after calling drainTo()

### Actual behavior
if only one element exists, after calling drainTo() element still exists in the queue

### Steps to reproduce or test case
1. create a redisson blocking queue
2. add only one element
3. call drainTo on the queue

### Redis version
3.2.10

### Redisson version
3.7.0

### Redisson configuration
![image](https://user-images.githubusercontent.com/1742454/50214522-8baca700-0391-11e9-8f05-dac96b7fb4aa.png)

### More details

drainTo runs command "ltrim key -1 0" under the hood. start index and stop index is the same so element stays in the list. i think this SO question may be helpful: https://stackoverflow.com/questions/40488194/unable-to-ltrim-when-redis-list-is-having-only-one-record

**Comment by mrniko** [comment]
Unable to reproduce it with follow code snippet:

```java
        RBlockingQueue<Integer> queue = getQueue();
        Assert.assertTrue(queue.offer(1));
        Assert.assertEquals(1, queue.size());
        Set<Integer> batch = new HashSet<Integer>();
        int count = queue.drainTo(batch, 1);
        Assert.assertEquals(1, count);
        Assert.assertEquals(1, batch.size());
        Assert.assertEquals(0, queue.size());
```
Redis: 3.2.10, Redisson 3.10.0

**Comment by mrniko** [comment]
Fixed! Thanks for report
