### ISSUE TITLE
The connection not reconnect

### ISSUE THREAD

**Issue by zhwq1216** [redisson/redisson#1811]
related #1583   Channel Inactive but the event not catched by ConnectionWatchdog.channelInactive() 

I think it is the same as #1583 ,  when I use kill -9 redisPid, then restart the redis, it seems work fine. But when the program run one or two days,  this issue appeared. I guess there may be a network problem that caused ConnectionWatchdog.channelActive not to be triggered. Is there any parameter setting to avoid this problem?

The exception stack:
2018-12-19 14:30:24.064 [http-nio-8081-exec-1][10.10.3.117-http-nio-8081-exec-1] ERROR c.b.c.s.w.s.m.m.annotation.HandlerMethodAspect - Throw:
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=10, freeConnectionsCounter=64, freezed=false, freezeReason=null, client=[addr=redis://10.10.3.112:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1662347556 [redisClient=[addr=redis://10.10.3.113:6379], channel=[id: 0xb21f069b, L:/10.10.3.117:50884 ! R:10.10.3.113/10.10.3.113:6379]], command: (HGET), command params: [shiro-activeSessionCache, ��t$afb4da38-cf18-4117-9159-ce16fc61b9d9] after 3 retry attempts
	at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:837)
	at org.redisson.command.CommandAsyncService.access$200(CommandAsyncService.java:92)
	at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:794)
	at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:791)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1104)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1151)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1075)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

### Redis version
4.0.9
### Redisson version
3.9.1
### Redisson configuration
            config.useSentinelServers()
                .setTimeout(2000)
                .setConnectTimeout(10000)
                .setRetryAttempts(3)
                .setRetryInterval(1000)
                .setDnsMonitoringInterval(-1)
                .setDatabase(0)
                .setPingConnectionInterval(10000)
                .setMasterName("mymaster")
                .addSentinelAddress(convert(Arrays.asList(getSentinelNodes().split(","))));

**Comment by davis0511** [comment]
l have the same problem

**Comment by mrniko** [comment]
Which OS and kernel do you use?

**Comment by zhwq1216** [comment]
> Which JDK, OS and kernel do you use?

#JDK
java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

OS
CentOS Linux release 7.2.1511 (Core)

kernel
3.10.0-327.el7.x86_64

**Comment by zhwq1216** [comment]
According the logs, I find the bug was when the watchdog  connect successfully to the redis, but the org.redisson.client.handler.BaseConnectionHandler#channelActive send some init command(AUTH, SELETE, PING...) failed, the watchdog will not work any more.  I had created a pull request  #1856





```
2019-01-13 00:00:58.072 [redisson-netty-1-4][] WARN  org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisConnection@1398065813 [redisClient=[addr=redis://10.10.7.49:6379], channel=[id: 0x4cee2812, L:/10.10.7.32:44090 ! R:10.10.7.49/10.10.7.49:6379]] to 10.10.7.49/10.10.7.49:6379
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), command params: [], Redis client: [addr=redis://10.10.7.49:6379]
        at org.redisson.client.RedisConnection$2.run(RedisConnection.java:214)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```




![ConnectWatchdog](/zhwq1216/redisson/blob/zhwq1216-patch-1/watchdog.jpg)

**Comment by mrniko** [comment]
@zhwq1216 

Thanks for your PR. I suggest more easier way to fix that. Could you review it? https://github.com/redisson/redisson/commit/44ea59f9f60ee0d2f586de7b0a5750c74783a33a

**Comment by zhwq1216** [comment]
> @zhwq1216
> 
> Thanks for your PR. I suggest more easier way to fix that. Could you review it? [44ea59f](https://github.com/redisson/redisson/commit/44ea59f9f60ee0d2f586de7b0a5750c74783a33a)

Yes, it's fine.

**Comment by mrniko** [comment]
Fixed

**Comment by Alex-LiWenhao** [comment]
I have the same problem

**Comment by Alex-LiWenhao** [comment]
I have channel closed

**Comment by Alex-LiWenhao** [comment]
Caused by: io.netty.channel.ExtendedClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

**Comment by chenxiangweifeng** [comment]
I have encountered the same problem today.  The error log:  " java.lang.Exception: org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource ........**after 3 retry attempts**" 
our redisssion version is 3.11.4. The code has the "reconnect codes" 
![image](https://user-images.githubusercontent.com/33818312/167374686-7bcf09ad-bfbf-4026-8e3b-98f9a959879d.png)

However,  after 3 retry attempts , it always failed!...Why？

**Comment by mrniko** [comment]
@chenxiangweifeng 

I recommend you to define pingConnectionInterval

**Comment by mrniko** [comment]
@chenxiangweifeng 

I recommend you to define pingConnectionInterval

**Comment by nishubin** [comment]
> related #1583 Channel Inactive but the event not catched by ConnectionWatchdog.channelInactive()
> 
> I think it is the same as #1583 , when I use kill -9 redisPid, then restart the redis, it seems work fine. But when the program run one or two days, this issue appeared. I guess there may be a network problem that caused ConnectionWatchdog.channelActive not to be triggered. Is there any parameter setting to avoid this problem?
> 
> The exception stack: 2018-12-19 14:30:24.064 [http-nio-8081-exec-1][10.10.3.117-http-nio-8081-exec-1] ERROR c.b.c.s.w.s.m.m.annotation.HandlerMethodAspect - Throw: org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=10, freeConnectionsCounter=64, freezed=false, freezeReason=null, client=[addr=redis://10.10.3.112:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1662347556 [redisClient=[addr=redis://10.10.3.113:6379], channel=[id: 0xb21f069b, L:/10.10.3.117:50884 ! R:10.10.3.113/10.10.3.113:6379]], command: (HGET), command params: [shiro-activeSessionCache, ��t$afb4da38-cf18-4117-9159-ce16fc61b9d9] after 3 retry attempts at org.redisson.command.CommandAsyncService.checkWriteFuture(CommandAsyncService.java:837) at org.redisson.command.CommandAsyncService.access$200(CommandAsyncService.java:92) at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:794) at org.redisson.command.CommandAsyncService$11$1.operationComplete(CommandAsyncService.java:791) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987) at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:869) at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1391) at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38) at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1104) at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1151) at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1075) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: java.nio.channels.ClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
> 
> ### Redis version
> 4.0.9
> 
> ### Redisson version
> 3.9.1
> 
> ### Redisson configuration
> ```
>         config.useSentinelServers()
>             .setTimeout(2000)
>             .setConnectTimeout(10000)
>             .setRetryAttempts(3)
>             .setRetryInterval(1000)
>             .setDnsMonitoringInterval(-1)
>             .setDatabase(0)
>             .setPingConnectionInterval(10000)
>             .setMasterName("mymaster")
>             .addSentinelAddress(convert(Arrays.asList(getSentinelNodes().split(","))));
> ```


> According the logs, I find the bug was when the watchdog connect successfully to the redis, but the org.redisson.client.handler.BaseConnectionHandler#channelActive send some init command(AUTH, SELETE, PING...) failed, the watchdog will not work any more. I had created a pull request #1856
> 
> ```
> 2019-01-13 00:00:58.072 [redisson-netty-1-4][] WARN  org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisConnection@1398065813 [redisClient=[addr=redis://10.10.7.49:6379], channel=[id: 0x4cee2812, L:/10.10.7.32:44090 ! R:10.10.7.49/10.10.7.49:6379]] to 10.10.7.49/10.10.7.49:6379
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), command params: [], Redis client: [addr=redis://10.10.7.49:6379]
>         at org.redisson.client.RedisConnection$2.run(RedisConnection.java:214)
>         at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
>         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)
> ```

你好，问下个问题怎么复现
我生产环境也遇到类似的问题了服务跑一段时间后突然就redis加锁失败了错误信息如下（服务重启后正常不知道以后还会不会出）
 org.redisson.client.RedisTimeoutException:Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=32, freeConnectionsCounter=112, freezed=false, freezeReason=null, client=[addr=redis://redis.public-app-prod.svc:6379], nodeType=MASTER, firstFail=0]]], command: (EVAL), command params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('publish', KEYS..., 2, lock:srm-primary:ADD_VOUCHER, redisson_rwlock:{lock:srm-primary:ADD_VOUCHER}, 1, 30000, f31e3332-4558-4feb-a569-0efaa6bbce11:60464:write] after 3 retry attempts
at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:703)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
at java.lang.Thread.run(Thread.java:748)


我想在本地去复现这个问题却怎么都复现不出来
求大佬指点一二。

**Comment by mrniko** [comment]
@nishubin Can you reproduce it with the latest version?

**Comment by nishubin** [comment]
> reproduce
This problem happens occasionally

The production environment has been running normally for several months. Last night, this problem suddenly occurred. After the service was restarted, it returned to normal.

I don't know if this problem will occur next time.

At present, the difficulty is that I cannot reproduce this problem. The development environment has no reproduction problem at present.

I'm still looking for the cause of the problem.

I'm not sure if the version caused this problem.

Redisson version

3.9.1

**Comment by nishubin** [comment]
> 
thank you

Is there a detailed description of the problem?

I'd like to know the specific causes of this problem and how you solved it.

I know this to improve my coding skills.

In this way, I can have certain judgment ability when I meet similar problems in the future.

**Comment by Resurgam-cwj** [comment]
> I have encountered the same problem today. The error log: " java.lang.Exception: org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource ........**after 3 retry attempts**" our redisssion version is 3.11.4. The code has the "reconnect codes" ![image](https://user-images.githubusercontent.com/33818312/167374686-7bcf09ad-bfbf-4026-8e3b-98f9a959879d.png)
> 
> However, after 3 retry attempts , it always failed!...Why？

So the reason is? I also encounter this problem, but i worried the problem exists even if i update redisson version

**Comment by nishubin** [comment]
我升级版本后就没有出现这个问题了

**Comment by nishubin** [comment]
> > I have encountered the same problem today. The error log: " java.lang.Exception: org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource ........**after 3 retry attempts**" our redisssion version is 3.11.4. The code has the "reconnect codes" ![image](https://user-images.githubusercontent.com/33818312/167374686-7bcf09ad-bfbf-4026-8e3b-98f9a959879d.png)
> > However, after 3 retry attempts , it always failed!...Why？
> 
> So the reason is? I also encounter this problem, but i worry the problem exists even if i update redisson version

我升级版本后问题就没有复现过了，稳定运行一年了

**Comment by mrniko** [comment]
@nishubin 
@Resurgam-cwj 

https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
