### ISSUE TITLE
整个项目复用一个Redisson实例怎么样？

### ISSUE THREAD

**Issue by changfubai** [redisson/redisson#1812]
Redisson.create()每次都是new一个Redisson。那么在使用时复用同一个Redisson实例，和通过线程池生成多个实例同时复用，哪个性能更好？

**Comment by jackygurui** [comment]
Redisson内部已经实现了线程池化和连接池化的工作，并且采用了线程安全的设计。一般情况下推荐全局使用一个RedissonClient实例。

**Comment by changfubai** [comment]
谢谢~ 再问一下~ 有没有beachmark用例或者相关数据结果呢~ 比如标准版redisson和jedis比较。我简单测了一下，redisson性能比jedis损失了20%~50%。我担心是我的错误用例导致的，是否有官方用例呢？

**Comment by jackygurui** [comment]
redisson和其他客户端的功能不同，Redisson中一个API操作里包含了多个Redis操作是很常见的，跟其他的客户端没有可比度，盲目的用一个简单测试去进行比较是没有意义的。
