### ISSUE TITLE
zRevRangeWithScores does not work properly in Spring RedisTemplate

### ISSUE THREAD

**Issue by hqxy** [redisson/redisson#1814]
![image](https://user-images.githubusercontent.com/24350787/50270691-64c3a300-046d-11e9-9e8d-0d33abf43265.png)
I found a problem with the command declared by ZREVRANGE_ENTRY in the RedissonConnection class. It should be ZREVRANGE, not ZRANGE.
redisson version :3.9.1

**Comment by mrniko** [comment]
Fixed. Thanks for report
