### ISSUE TITLE
Wrong command timeout for check master functionality

### ISSUE THREAD

**Issue by johansjoberg** [redisson/redisson#1815]
When using`replicatedServersConfig` configuration you cannot set low `retryAttempts` & `retryInterval` without getting command execution timeouts for the check master functionality, which ensures that the client knows which nodes that are master and which aren't.

The timeout for getting a connection, sending the command and waiting for the response is calculated by `retryInterval * retryAttempts` in the version of redisson that we use currently (2.8.24).

From what I can see the command timeout calculation was introduced in following issue, https://github.com/redisson/redisson/issues/1280 (commit was https://github.com/kinbod/redisson/commit/387ed744b8bb49a49f9cd41adfd500c4592d2027)

It actually seemed to have changed in following commit, https://github.com/redisson/redisson/commit/338f9d00a3081f0b6e70f87f28647994c8c6b0db, which is included in a later version than we use currently. Now the command timeout is instead set by what `timeout` value you have set. This commit would probably get rid of the exceptions for command execution timeout for our application, since it uses `timeout` instead of `retryInterval * retryAttempts`.

I suggest a change to make this a configurable value for the `replicatedServersConfig`. This would make it would be possible to have very low values configured for `timeout`, `retryAttempts` & `retryInterval` without it affecting the check master functionality.

Since checking if a node is master is scheduled to be done periodically in the background it is not that important, at least for us, that this will timeout quickly. It is however important to us that we do timeout quickly for the app/user initiated commands. Making this value configurable would make sure that it possible to configure redisson for such a scenario.

### Expected behavior
The timeout for checking if a node is master or not, using INFO REPLICATION command, should not be shorter than the total time of command timeout and server response timeout for user/app initiated commands. I expected the time for the timeout to be calculated as `(retryInterval * retryAttempts + 1) + timeout` to give it the same amount of time to get a connection, send the command and await the response as user/app initiated commands.

### Actual behavior
The timeout is calculated using `retryInterval * retryAttempts`. This seems wrong since it makes the total timeout shorter compared to an app/user initiated command. I would expect it to be at least the same amount of time by default.

### Steps to reproduce or test case
1. Install toxiproxy (https://github.com/Shopify/toxiproxy)
2. Add a latency toxic higher than 50 ms to one of the redis nodes, and ensure that your java application uses the address and port exposed by toxiproxy.
3. Update your java application to use the redisson configuration defined in this issue.
4. Start your java service..

You will now get exceptions starting with the message text:

> Command execution timeout for command: (INFO REPLICATION)

### Redis version
ElastiCache for Redis 2.8.24

### Redisson version
3.7.5

### Redisson configuration
```
replicatedServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 250
  retryAttempts: 1
  retryInterval: 50
  scanInterval: 5000
  nodeAddresses:
  - "redis://server1:6379"
  - "redis://server2:6379"
```

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4884
