### ISSUE TITLE
Can't execute CLUSTER_NODES,which version solved?

### ISSUE THREAD

**Issue by hisenyuan** [redisson/redisson#1816]
@mrniko hello,i had view some close issues,but i dont know which version  really solved this problem.

redis on port 7001 is master
redisson version:2.8.2

the following is my error log
```
18-12-22.00:10:55.177 [redisson-netty-4-5] ERROR ClusterConnectionManager  - Can't execute CLUSTER_NODES with /xxx.xxx.xxx.xxx:7001
java.lang.IllegalArgumentException: java.net.MalformedURLException: unknown protocol: redis
	at org.redisson.misc.URLBuilder.create(URLBuilder.java:125) ~[redisson-2.8.2.jar:na]
```

**Comment by jackygurui** [comment]
@hisenyuan Please can I ask you to try it again with a later version of Redisson?

**Comment by hisenyuan** [comment]
ok,thank you for your reply. Which version do you recommend?

**Comment by hisenyuan** [comment]
> @hisenyuan Please can I ask you to try it again with a later version of Redisson?

ok,thank you for your reply. Which version do you recommend?

**Comment by jackygurui** [comment]
I would always suggestion the latest version but you should read the release note and make sure you have done all the necessary tasks to ensure your application is compatible.

**Comment by wenzhisheng** [comment]
I am using the latest version of redisson and still have this problem. 3.11.1 and 3.11.2 are the latest

**Comment by mrniko** [comment]
fixed
