### ISSUE TITLE
how to set the 'pingConnectionInterval' attribute in spring xml?

### ISSUE THREAD

**Issue by HuoShaoFeng** [redisson/redisson#1817]

**Comment by HuoShaoFeng** [comment]
how to descripte the following code in the applicationContext.xml :
        ClusterServersConfig csc = new ClusterServersConfig();
        csc.**setPingConnectionInterval**(60 * 1000);

i have try it ,but i can not found any attribute in tab 'redisson:cluster-servers'

**Comment by mrniko** [comment]
Duplicate with https://github.com/redisson/redisson/issues/1761
