### ISSUE TITLE
Why does readAllValues not using local cache in LocalCachedMap?

### ISSUE THREAD

**Issue by a2232189** [redisson/redisson#1823]
### Expected behavior
LocalCachedMap.readAllValues() should be very fast, using local cache and should  not query redis.
### Actual behavior
LocalCachedMap.readAllValues() cost 100ms+ to read 800+ POJO objects.
In redis-cli monitor, I saw incoming query by redisson
### Redisson version
2.14.0

**Comment by mrniko** [comment]
I'll add methods to read data stored in local cache: readAllCachedValues, readAllCachedKeys, readAllCachedEntries.

**Comment by mrniko** [comment]
Done
