### ISSUE TITLE
Redisson will try to connect to removed nodes

### ISSUE THREAD

**Issue by sKabYY** [redisson/redisson#1826]
Redisson seems to keep the connection to the removed node, and try to reconnect after I shutdown the node. As the figures shown, I had removed 11.4.66.112:43791 and the log confirmed the node had been removed. But Redisson was still trying to connect to the node. After resetting and restarting the node, Redisson reconnected to it and leaded "CLUSTERDOWN Hash slot not served" exception.

![image](https://user-images.githubusercontent.com/217475/50471317-09eef600-09ef-11e9-9bad-463f19d31bbc.png)

![image](https://user-images.githubusercontent.com/217475/50471564-3c4d2300-09f0-11e9-9a11-b3d1d416f8bb.png)

### Redis version
5.0.2

### Redisson version
3.9.1

### Redisson configuration
```Kotlin
val serversConfig = config.useClusterServers()
serversConfig.readMode = ReadMode.MASTER_SLAVE
serversConfig.masterConnectionMinimumIdleSize = 50
serversConfig.slaveConnectionMinimumIdleSize = 50
serversConfig.subscriptionConnectionMinimumIdleSize = 5
serversConfig.scanInterval = 5000
serversConfig.masterConnectionPoolSize = 512
serversConfig.slaveConnectionPoolSize = 512
serversConfig.idleConnectionTimeout = 180000
serversConfig.connectTimeout = 30000
serversConfig.timeout = 10000
serversConfig.retryInterval = 1000
```

### BTW
When will Redisson distribute the new version that fixed some bugs about "MOVE"?

**Comment by mrniko** [comment]
I guess this related to https://github.com/redisson/redisson/issues/1746. Could you update to 3.10 version and give your feedback?

**Comment by sKabYY** [comment]
> I guess this related to #1746. Could you update to 3.10 version and give your feedback?

3.10 version has another bug. When I use cmd "cluster failover" to switch Master and Slave, Redisson can't deal with the "MOVED" redirection properly.

> org.redisson.client.RedisException: MOVED redirection loop detected. Node redis://11.4.66.130:43791 has further redirect to redis://11.4.66.130:43791

### Redisson version
git tag redisson-3.10.0

**Comment by sKabYY** [comment]
I found that this exception disappeared after the node was added as Master.

![image](https://user-images.githubusercontent.com/217475/50506609-c068de80-0ab4-11e9-8c15-8b667e411ce3.png)

I guess that this occurs between the time "CLUSTER FAILOVER" takes effect and the next time Redisson check "CLUSTER NODES". At that moment, Redisson try to access the old Master and get a response to redirect to the new Master, but the cluster nodes cache in Redisson indicates that the new Master should redirect to the old Master, and so the loop is formed.

------

> If you comment out line at CommandAsyncService:1010 will that help to resolve issue with MOVED handling?

I tried and the program was stuck after "CLUSTER FAILOVER".

**Comment by mrniko** [comment]
> I tried and the program was stuck after "CLUSTER FAILOVER".

It's a protection against such cases.

**Comment by sKabYY** [comment]
> > I tried and the program was stuck after "CLUSTER FAILOVER".
> 
> It's a protection against such cases.

Isn't there a better strategy to handle such cases?

**Comment by mrniko** [comment]
I'm afraid no. Redisson requires Redis topology info to handle failover correctly, without it it's impossible to know which node should be used.
