### ISSUE TITLE
[注意(notice)]升级3.10.0时需要注意默认Codec变更导致的NPE问题

### ISSUE THREAD

**Issue by anjia0532** [redisson/redisson#1832]
ref [Redisson Releases History#27-Dec-2018 - versions 2.15.0 and 3.10.0 released](https://github.com/redisson/redisson/blob/master/CHANGELOG.md#27-dec-2018---versions-2150-and-3100-released)

> Improvement - default codec changed to FSTCodec

ref [NPE after upgrade to 3.10.0](https://github.com/redisson/redisson/issues/1830)

3.10.0以前的版本默认使用 `org.redisson.codec.JsonJacksonCodec`,而3.10.0改用`FSTCodec`

~~意味着升级后，如果要用历史数据，**必须** 要改代码，改成`redisson.getXX("key",JsonJacksonCodec.INSTANCE)`,否则会报NPE。~~ 
感谢 @jackygurui 指出，在创建redisson对象时，指定默认Codec即可
**并且使用fst后，无法使用redis工具来查询，修改数据**

~~请谨慎升级。~~

~~私认为版本号不应该沿用3.x，而应该改成4.x，或者在changelog上，注明升级后会引起的后果，而不是简单的介绍修改了默认Codec~~

**Comment by jackygurui** [comment]
在创建RedissonClient对象时修改默认codec就可以实现向后支持。RedissonClient对象的默认codec可以通过JSON配置文件、YML配置文件或Spring XML来修改，多数情况下无需修改代码。

**Comment by anjia0532** [comment]
对哈，居然忘记了可以在创建对象时选择默认Codec，对不起，对不起.

可以改成类似，
```yaml
---
xxxxServersConfig:
....
codec: !<org.redisson.codec.JsonJacksonCodec> {}
....
```

参考 https://github.com/redisson/redisson/wiki/2.-Configuration#242-cluster-json-yaml-and-spring-xml-config-format

**Comment by a2232189** [comment]
Would you please explain why you choose FST as default Codec? I searched a lot but still cannot find any latest( non out-of-date) benchmark which shows FST is fater than Jackson. [FST latest benchmark doesn't include Jackson](https://github.com/RuedigerMoeller/fast-serialization/wiki/Benchmark)
