### ISSUE TITLE
RedissonClient still points to failed AWS Elasticache Redis node when failover happens

### ISSUE THREAD

**Issue by jimwang-dtci** [redisson/redisson#1845]
I tested AWS Elasticache Redis failover (manual test). First I started my app which creates one  Redissonclient. It established 67 connections to primary Redis node. Then I manually did failover primary test.
### Expected behavior
All 67 connections point to new primary Redis node.
### Actual behavior
33 connections still point to previous (failed) primary Redis node, 34 connections point to new primary Redis node.
### Steps to reproduce or test case
1. Start my app which creates one Redissonclient.
2. From command line run:   netstat -nt | sort +5 | fgrep .6379 | grep -n ^         This commands show 67 connections to primary Redis node.
3. Go to AWS Console, Elasticache, Redis and select redis cluster you are using. It shows all of nodes of the cluster. Check the primary node, go to Action and select "Failover primary".
4. Wait for a while, run step 2 command, out of 67 connections, half of them are pointing to previous primary node, half of them are pointing to new primary node. 
5. I have a cache called "foo". My code calls redissonClient.getMapCache(foo).size() and it ends up with errors like "SlaveConnectionPool no available Redis entries.  Disconnected hosts: [xxxxx.usw2.cache.amazonaws.com/ipaddress:6379]" The ipaddress here points to previous primary node. 
6. From AWS Console, if you select previous and new Redis primary nodes, then look at "Current Connections" of CloudWatch metrics, you can get the same result: Redisson client points to both previous and new Redis primary nodes. Following screenshot shows Redis primary node failover from 003 to 004.
![image](https://user-images.githubusercontent.com/4614936/50936614-3bbb8000-1425-11e9-98d0-d3607a96f148.png)

### Redis version
3.2.6 (Elasticache on AWS)
### Redisson version
3.10.0
### Redisson configuration
            Config config = new Config();

            ReplicatedServersConfig replicatedConfig = config.useReplicatedServers();
            replicatedConfig.addNodeAddress(Primary Endpoint of redis);
            
            replicatedConfig.setTimeout(3000);
            replicatedConfig.setRetryAttempts(3);
            replicatedConfig.setRetryInterval(1500);
            replicatedConfig.setPingConnectionInterval(5000);

            redissonClient = Redisson.create(config);

**Comment by mrniko** [comment]
Do you use only one master and one slave, right?

**Comment by mrniko** [comment]
In replicated mode all nodes should be defined since there is no way to get all slaves through AWS Primary Endpoint in this mode. All nodes auto works only in cluster mode

**Comment by jimwang-dtci** [comment]
I have one primary node and 3 replica. Primary node is used to write and all nodes are used to read. When failover happens, one of replica is promoted to primary node. AWS suggests you use primary end point for writing. Of course you can use it for read as well.

When failover happens, the following is logged by Redisson:

{"Time":"2019-01-10T16:08:35.968-0800","fullMessage":"Detected DNS change. Master rediss://xxxxx.usw2.cache.amazonaws.com:6379 has changed ip from 10.153.99.49 to 10.153.99.219","loggerName":"org.redisson.connection.DNSMonitor","thread":"redisson-netty-1-12","severity":"INFO"}

It seems to me that Redisson did see the changes. But when I ran " netstat -nt | sort +5 | fgrep .6379 | grep -n ^", I saw Redisson sent "SYN_SENT" to previous primary node even Redisson has already "ESTABLISHED" connection with new primary node. Once failover completed (it took about 10 mins), Redisson "ESTABLISHED" connection with previous primary node as well (33 connections to previous primary node, 34 connections to new primary node)

Another thing I noticed is that the following two calls seem using different connection pools.
redissonClient.getMapCache("foo").get(key) always uses pool which point to new primary node. 
redissonClient.getMapCache("foo").size() always uses pool which point to previous primary node.
After failover happens, in about minute, get(key) starts to work, but size( ) kept on throws "SlaveConnectionPool no available Redis entries" error.

The reason I'm trying not to use individual node is that if we need to add new node or delete a node, I don't want to restart app with new node configuration. We used Redis cluster (cluster mode disabled). The primary node can handle both read and write. The other nodes are mainly for failover.

**Comment by jimwang-dtci** [comment]
Once I specified all 4 nodes (I didn't specify the primary endpoint) for replicated mode, Redisson worked much better. Redisson did discover the new master node (jim-dcs-003) after failover happened. 
Screen shot from AWS:
![image](https://user-images.githubusercontent.com/4614936/51058000-48161900-159c-11e9-8f96-3afbe6c5cdfb.png)

Failover from jim-dcs-004 to jim-dcs-003. I have one question. After failover completed, I found Redisson has only one connection to jim-dcs-004 which was previous master node. You can see that from above screenshot. Also when I checked redissonClient.getNodesGroup().getNodes(), it only returned 3 nodes instead of 4 nodes. Node jim-dcs-004 is missing. But node 004 was back online as a SLAVE. Is this expected behavior?

**Comment by mrniko** [comment]
> Node jim-dcs-004 is missing. But node 004 was back online as a SLAVE. Is this expected behavior?

It was a bug. Now it's fixed

**Comment by jimwang-dtci** [comment]
Thanks.

**Comment by jimwang-dtci** [comment]
I have verified that previous master node was added back as a slave node after failover with release 3.10.1. Thanks for the fix. But the number of connections to the salve is only 1 instead of 34. Is this expected? I tested a couple of times and got the same result. Following screen shot shows two tests. I started the app, Redisson established connections to both 003 and 004. Then I did failover from 003 to 004. After failover was done, there was only one connection to 003. Then I restarted the app to make sure Redisson re-established connections to both 003 and 004. I did failover from 004 to 003. After failover was done, again there was only one connection to 004. ( You can run netstat -nt | sort +5 | fgrep .6379 | grep -n ^   from app box to see the connections)  
<img width="907" alt="image" src="https://user-images.githubusercontent.com/4614936/51627229-52b6a380-1ef6-11e9-9e5b-a47764d2e1d0.png">
