### ISSUE TITLE
Slave connection will not recover from freeze mode after failover

### ISSUE THREAD

**Issue by reimer-eimer** [redisson/redisson#1846]
Hi!
I am testing failover behavior of redisson on AWS Elasticache in replicatedServers mode with one master and one slave. I am using read mode MASTER_SLAVE. After the failover is finished redisson correctly detects the new master and redirects all traffic to the master. The slave needs around 5 minutes to recover on Elasticache. Redisson is continously checking that connection, but after recovering that connection it does not move traffic to the slave. 

### Expected behavior
Traffic should again be load balanced between master and slave after failover is completed.

### Actual behavior
Connections to master and slave are established but all traffic is routed to master.
By debugging i identified that the slave connection will remain freezed with FreezeReason Manager.

### Steps to reproduce or test case
1. Start app with replicateServers mode with one slave and one master
2. Start failover on AWS console and wait until it is finished.
3. Watch traffic on slave. -> nothing

### Redis version
4.0.10

### Redisson version
3.10.0

### Redisson configuration
            config.useReplicatedServers()
                .setReadMode(ReadMode.MASTER_SLAVE)
                .addNodeAddress(connections)
                .setMasterConnectionPoolSize(maxConnections)
                .setSlaveConnectionPoolSize(maxConnections)
                .setScanInterval(1000);

**Comment by mrniko** [comment]
did you define all AWS Elasticache nodes in configuration?

**Comment by reimer-eimer** [comment]
Yes I have added both nodes of course.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1845
