### ISSUE TITLE
Question about api(RMap,RSet....) use

### ISSUE THREAD

**Issue by shizhengchao** [redisson/redisson#1849]
If there are 10000+ values in a RMap。Why do I take all the values out when I use it?
for example:
`RMap<String, String> rmap = redisson.getMap("TEST")`

Then this map is full of all values。But  I just want to store a value in the map, no need to take out all the values. I just want to get a instance of RMap whithout all of value.

**Comment by shizhengchao** [comment]
`RMap<String, String> rmap = redisson.getMap("TEST")`
But when the map exists, This invocation  contains the values previously saved  in my local memory

**Comment by shizhengchao** [comment]
![image](https://user-images.githubusercontent.com/22866465/51025618-81b04980-15c7-11e9-93b0-d268975da73e.png)

this is my debug code

**Comment by mrniko** [comment]
Debugger shows state of Map object by calling `RMap.entrySet` method

**Comment by shizhengchao** [comment]
thank you @mrniko
