### ISSUE TITLE
DefaultSavedRequest cannot be cast to SavedRequest

### ISSUE THREAD

**Issue by zangbo654456** [redisson/redisson#1850]
I did it according to your configuration.But there was a problem：
java.lang.ClassCastException: org.springframework.security.web.savedrequest.DefaultSavedRequest cannot be cast to org.springframework.security.web.savedrequest.SavedRequest。
so，what should i do？
![image](https://user-images.githubusercontent.com/44250108/51028034-4d3f8c00-15cd-11e9-99c5-3cff60ec7175.png)

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1850
