### ISSUE TITLE
Why does RMapCache is designed to use Hash instead of simple key-value structure?

### ISSUE THREAD

**Issue by a2232189** [redisson/redisson#1860]
I am curious why RMapCache is designed to use Hash instead of simple key-value structure? Simple key-value can use TTL while Hash cannot. What benefit does RMapCache get when using Hash compared with using key-value?

**Comment by jackygurui** [comment]
`Simple key-value can use TTL while Hash cannot.` I think you have just answered your own question here. 

There are use cases where string structure would be more suitable than hash and vice versa, RMapCache is here to bridge the gap between them.

**Comment by a2232189** [comment]
Some want to save the data in redis with TTL and some want to save the data in redis forever, so you choose to use a never-out-ouf-date strcture `HASH` to save all data, and run a schedule task to delete those data that are set with TTL. Am my understand right?

If above conclusion is right, then I'd think that you choose to use `hash` instead of simple key-value is because the maintainability. Since it's easier to maintain the code if the data structure is only `hash`, compared with the thought that when user choose to save data with TTL, Redisson use `simple key-value` and when ser choose to save data forever (without TTL), Redisson use `Hash`.

**Comment by a2232189** [comment]
> If my conclusion above is right, I think that you choose to use `hash` instead of simple key-value is because the maintainability. Since it's easier to maintain the code if the data structure is only `hash`, compared with the thought that when user choose to save data with TTL, Redisson use `simple key-value` and when ser choose to save data forever (without TTL), Redisson use `Hash`.

Am my conclusion right here?

**Comment by a2232189** [comment]
Didn't know `RBucket1 before. thanks.
