### ISSUE TITLE
simple type, class java.lang.Object

### ISSUE THREAD

**Issue by heppytt** [redisson/redisson#1862]
Type Exception Report
Message Unexpected exception while processing command
Description The server encountered an unexpected condition that prevented it from fulfilling the request.
Exception
org.redisson.client.RedisException: Unexpected exception while processing command
 org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:403)
 org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:200)
 org.redisson.RedissonObject.get(RedissonObject.java:87)
 org.redisson.RedissonMap.get(RedissonMap.java:281)
 org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:77)
 org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:103)
 com.cloud.icenter.common.filter.SSOFilter.doFilter(SSOFilter.java:91)
 org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
 org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Root Cause
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'com.cloud.icenter.system.login.bean.SSOKey' as a subtype of [simple type, class java.lang.Object]: no such class found
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 11]
 com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
 com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1635)
 com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1187)
 com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:53)
 com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:44)
 com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
 com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.ja

**Comment by heppytt** [comment]
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: "abc@123"
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  # dnsMonitoring: false
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"


上面是我的配置。
请问是怎么回事啊？

**Comment by mrniko** [comment]
I would recommend you to use FSTCodec to solve this problem

**Comment by mrniko** [comment]
@heppytt 

It's similar problem to https://github.com/redisson/redisson/issues/1668. Currently I'm working on resolution

**Comment by mrniko** [comment]
Fixed in 2.15.1 / 3.10.1 versions
