### ISSUE TITLE
Spring cache abstraction with redisson stored all cache data in one map. 

### ISSUE THREAD

**Issue by pratikshah1701** [redisson/redisson#1866]
I am using redis as cachig solution with Redisson as java client client.
I am doing it with sping cahce abstraction.
So my I have noticed redisson sotres data in redis as whole map and inside that map I have all my cahce data.
Is it possible that I can store all data individually as key value directly to redis.

### Actual behavior
Currently,  The way data is stored in redis is:  it has one TestsCacheMap and inside that map all the cahce data is stored

TestsCacheMap
- Key1 value1
- Key2 value2
- Key3 value3

Problem with this: If I am using redis cluster then this map will be stored in one redis node so all my data will indirectly stay on one node at a given time.

### Expected behavior
But I am looking for the way which directly stored key value in redis:
Key1 value1
Key2 value2
Key3 value3

### Steps to reproduce or test case

================================== RedisConfiguration =======================================
public class RedisConfiguration {

    @Bean(destroyMethod = "shutdown")
    RedissonClient redisson() throws IOException {
        Config config = new Config();
        String prefix = "redis://";

        //Redis-cluster configuration
        config.useClusterServers().addNodeAddress(prefix + "10.108.191.127" + ":" + "7000", prefix + "10.108.191.127" + ":" + "7001",
                        prefix + "10.108.191.127" + ":" + "7002");

       
        return Redisson.create(config);
    }

    @Bean
    CacheManager cacheManager(RedissonClient redissonClient) {
        Codec serializationCodec = new SerializationCodec();
        Codec stringCodec = new StringCodec();
        CompositeCodec compositeCodec = new CompositeCodec(stringCodec, serializationCodec);

        Map<String, CacheConfig> config = new HashMap<String, CacheConfig>();

        // create "testMap" cache with ttl = 24 minutes and maxIdleTime = 12 minutes
        config.put("TestsCacheMap", new CacheConfig(24 * 60 * 1000, 12 * 60 * 1000));
        return new RedissonSpringCacheManager(redissonClient, config, compositeCodec);
    }
	
	
	
=================================== CachedTestService ========================================
	
	public class CachedTestService {

    @Autowired
    private TestRepository TestRepository;

    @Autowired
    private RedissonClient redissonClient;

    @CachePut(value = "TestsCacheMap")
    public List<Test> getActiveByKey(String Key) {
        return TestRepository.getActiveByKey(Key);
    }

    @CacheEvict(value = "TestsCacheMap")
    public void removeFromCacheByKey(String Key) {}

    @CacheEvict(value = "TestsCacheMap", allEntries = true)
    public void clearCache() {}

}

### Redis version
4.X

### Redisson version

3.10

**Comment by mrniko** [comment]
Currently there is no way to store data in spring cache as key value instead of map object. Because you can't control maxIdleTime param in this case.

**Comment by CSALS** [comment]
@mrniko is this still not supported?
