### ISSUE TITLE
RateType.PER_CLIENT in RRateLimiter does not work.

### ISSUE THREAD

**Issue by shengjie8329** [redisson/redisson#1870]
### Expected behavior
Each client should acquire their own permission when using RateType.PER_CLIENT in RRateLimiter.
### Actual behavior
When one client acquire the permission, the other client fails to acquire the permission at the same time even though using RateType.PER_CLIENT.
### Steps to reproduce or test case
```
        //Two clients run the test case at the same time,the first client acquires the permission, the other one fails.
        @Test
	public static void test2() throws Exception
	{
		Config config = RedissionConfigBuilder.build();
		RedissonClient redisson = Redisson.create(config);
    	        RRateLimiter rateLimiter = redisson.getRateLimiter("myRateLimiter_client");
    	        rateLimiter.trySetRate(RateType.PER_CLIENT, 5, 5, RateIntervalUnit.SECONDS);
    	        System.out.println(rateLimiter.tryAcquire(5));    	
    	        redisson.shutdown();
	}
```
By the way, I checked the source code of  method "tryAcquireAsync" in class "RedissonRateLimiter" , I found the condition judgment below does not work:
```
+ "if type == 1 then "
   + "valueName = KEYS[3];"
 + "end;"
```
It works when the code is:
```
+ "if type == '1' then "
   + "valueName = KEYS[3];"
 + "end;"
```
### Redis version
3.2.9
### Redisson version
3.8.1
### Redisson configuration
standalone

**Comment by mrniko** [comment]
Fixed. Thanks for report
