### ISSUE TITLE
throws exception when invoke shutdown method in redissionClient

### ISSUE THREAD

**Issue by ThinWonton** [redisson/redisson#1873]
使用springboot starter，当关闭应用时，会回调client的shutdown ，此时会报**“远程强制关闭连接”**异常。虽然说，这是正常关闭连接的现象，但是容易给现场的人造成误会。

现在测试后发现，不是boot starter的原因，是只要调用RedissionClient的shutdown就抛异常。在3.6版本没有这个问题

### Redis version
3.2.100

### Redisson version
3.8.x   3.9.x

### Redisson configuration

# Redis数据库索引（默认为0）

spring.redis.database=0
spring.redis.host=127.0.0.1
spring.redis.port=6379
#spring.redis.password=
spring.redis.timeout=60000

**Comment by jackygurui** [comment]
`远程强制关闭连接`这个问题是网络层面报上来的，应该跟服务端有关。

**Comment by ThinWonton** [comment]
起初我也以为是这样子的，结果测试后感觉不像。
分别用windows redis 3.2.100/3.0.504版本测试，在redisson 3.6.5可以正常关闭，但是在redission  3.8 3.9 3.10 都存在  _远程强制关闭连接_  这个问题。还用过 2.14.1 、2.13.2，也是存在这个问题。

测试代码：
```java
        RedissonClient redissonClient = Redisson.create(config);

        redissonClient.shutdown();
```
