### ISSUE TITLE
"RedisException: MOVED redirection loop detected" is popped out after Redis Master nodes down and up

### ISSUE THREAD

**Issue by zhanshen8D** [redisson/redisson#1882]
### Expected behavior
We have application using Redisson to access Redis cluster(16 masters+16 slaves).
We have a test case which is to shutdown one or more Redis Master nodes then take them up.
We expect after the action above(Redis Master nodes down and up), the Redisson can still find the right node when accessing Redis.

### Actual behavior
For example, there 2 Servers 192.168.0.78 and 192.168.0.79.
There are 8 master Redis nodes on 192.168.0.78 with port 6000-6007, the slaves of the 8 masters are 6100-6107 on 192.168.0.79.
The same, there are 8 master Redis nodes on 192.168.0.79 with port 6000-6007, the slaves of the 8 masters are 6100-6107 on 192.168.0.78.
The test case is that all the Redis nodes on 192.168.0.79  are shutdown then taken up.

So after shutting down, all the Redis nodes on 192.168.0.78 become Master. And after the Redis nodes on 192.168.0.79 are taken up, the Master Role of 6100-6107 on 192.168.0.78 will be switched back to 6000-6007 on 192.168.0.79, which is done by another script according to our function definition.
At that time, Redisson will report the exception like below:
org.redisson.client.RedisException: MOVED redirection loop detected. Node //192.168.0.79:6001 has further redirect to //192.168.0.79:6001
        at org.redisson.command.CommandAsyncService.checkAttemptFuture(CommandAsyncService.java:997)

The below is the information of “monitor” on 192.168.0.78:6103:
1548062216.210669 [0 192.168.0.79:6003] "ZADD" "IDX_SUBSCRIBER_FLUTIME_00000000001579590000_19" "1579598216" "SUBSCRIBER_15712156719" "1579598216" "SUBSCRIBER_15607370919" "1579598216" "SUBSCRIBER_15604880719" "1579598216" "SUBSCRIBER_15606831519" "1579598216" "SUBSCRIBER_15607576519" "1579598216" "SUBSCRIBER_15712158519" "1579598216" "SUBSCRIBER_15712179919" "1579598216" "SUBSCRIBER_15604362119" "1579598216" "SUBSCRIBER_15608353319"
...

It seems the request which should be sent to 192.168.0.79:6003 has been sent to 192.168.0.78:6103, which makes 192.168.0.78:6103 get extra load.

So it means the Redisson sends requests to the wrong Redis nodes after the action above, which is regarded as a wrong behavior.

### Steps to reproduce or test case
Like the "Actual behavior", setup Redis cluster on 2 servers with each having 8 masters + 8 slaves, the slaves should belong to the masters on the other server. Then shutdown and start all the Redis nodes on one server. Meanwhile, keep the Redisson sending requests to the Redis cluster.

### Redis version
4.0.8

### Redisson version
3.9.0

### Redisson configuration
---
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 15000
  connectTimeout: 10000
#  timeout: 60000
  timeout: 30000
  retryAttempts: 3
  retryInterval: 1500
#  retryInterval: 1500
  reconnectionTimeout: 1000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 2
  slaveConnectionPoolSize: 2
  masterConnectionMinimumIdleSize: 100
  masterConnectionPoolSize: 100
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  nodeAddresses:
   - "redis://HOST1:6000"
#  - "redis://[HOST2]:5301"
#  - "redis://[HOST3]:5301"
  scanInterval: 10000
threads: 32
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/pull/1835

**Comment by zhanshen8D** [comment]
Hi,
I have tried the latest table version which is 3.10.2, but the problem seems still there.
Could you please tell me which version includes the solution?
Thanks.

BRs
Zhangmin

**Comment by zhanshen8D** [comment]
Hi,
 I have tried the latest stable version which is 3.10.2, but the problem seems still there.
 Could you please tell me which version includes the solution?
 Thanks.

BRs
 Zhangmin

**Comment by zhanshen8D** [comment]
Hi,
I have tried the latest stable version which is 3.10.2, but the problem seems still there.
Could you please tell me which version includes the solution?
Thanks.
BRs
Zhangmin
