### ISSUE TITLE
13.1.1 创建集群中

### ISSUE THREAD

**Issue by laomolaomo** [redisson/redisson#1895]
以下范例展示了如何创建三主三从的Redis集群。

ClusterNodes clusterNodes = ClusterNodes.create()
.master("127.0.0.1:7000").withSlaves("127.0.0.1:7001", "127.0.0.1:7002")
.master("127.0.0.1:7003").withSlaves("127.0.0.1:7004")
.master("127.0.0.1:7005");
ClusterManagementTool.createCluster(clusterNodes);
主节点127.0.0.1:7000的从节点有127.0.0.1:7001和127.0.0.1:7002。

主节点127.0.0.1:7003的从节点是127.0.0.1:7003。（这里应该是7004）

主节点127.0.0.1:7005没有从节点。

**Comment by jackygurui** [comment]
感谢支出。已经修复了。
