### ISSUE TITLE
Command execution timeout for command: (AUTH) when ElasticCache with TLS

### ISSUE THREAD

**Issue by pakore** [redisson/redisson#1900]
org.redisson.Version - Redisson 3.8.0
Redis version 5.0.0
 "io.netty" % "netty-tcnative-boringssl-static" % "2.0.20.Final"

This piece of code:

```
def clusterConfig = redissonConfig.useClusterServers()
clusterConfig.addNodeAddress(s"redis://clustercfg.rediscluster.XXXXX.use1.cache.amazonaws.com:6379")
```
works with Redis in Elasticache when is configured with

```
Encryption in-transit: No
Redis Auth: No
```

but when adding:

`clusterConfig.setPassword("XXXXXXXXXXXXXXXX")`

and then Redis in Elasticache is configured with:
```
Encryption in-transit: Yes
Redis Auth: Yes
```
Redisson returns:

> Command execution timeout for command: (AUTH).

From the same instance that executed the code above, I can connect to the redis instance with redli:
```
redli --host=clustercfg.redis-cluster.XXXXX.use1.cache.amazonaws.com --port=6379 --auth=XXXXXXXXXXXXXXXX --tls
Connected to 5.0.0
>
```
to discard connection / environment problems.

I could not find in the documentation how to tell redisson that it should use tls. Is it supported at all?

**Comment by mrniko** [comment]
You can find it here https://github.com/redisson/redisson/wiki/2.-Configuration#25-replicated-mode

`use "rediss://" for SSL connection`

**Comment by pakore** [comment]
Thanks a lot, that worked!
