### ISSUE TITLE
Problem with readGroup and messages created before group

### ISSUE THREAD

**Issue by zivziv77** [redisson/redisson#1902]
Hi

I am trying to use the new stream feature of Redis 5.
According to the documentation of Redis when I use xreadgroup and mark > I should get all messages that never sent to any other consumer regardless of the time the group was created. 
On the example on Redisson wiki I get only  the messages that was added after I created the group.
I don’t see an option to call readGroup function in redisson with > sign to get all messages.
Can you help me with that?

Thanks

**Comment by mrniko** [comment]
I added StreamMessageId.NEVER_DELIVERED for this case. Please use it.
