### ISSUE TITLE
Custom codec not working after version 3.10.0

### ISSUE THREAD

**Issue by kfh** [redisson/redisson#1905]
We have been using a custom KryoCodec(overriding the built in one) for a while but after version 3.10.0 this no longer works. The change that affects us are introduced by the following commit: https://github.com/redisson/redisson/commit/37b58db7bcc2bdf586e3ce2e55a37803fcd545fd

I've spent a little bit of time looking into what's going on and it looks like there are issues regarding classloading since we got all sorts of exceptions now, especially lots of `com.esotericsoftware.kryo.KryoException: Unable to find class` on classes that we have been serializing without problems til now. The root cause is of course  `java.lang.ClassNotFoundException:x.y.z`

I've attached the relevant code with the working and non working solution:

**Working**:

```
public class KryoCodec extends org.redisson.codec.KryoCodec {

    private static class KryoPoolImpl extends org.redisson.codec.KryoCodec.KryoPoolImpl {

        KryoPoolImpl(List<Class<?>> classes, ClassLoader classLoader) {
            super(classes, classLoader);
        }

        @Override
        protected Kryo createInstance() {
            Kryo kryo = super.createInstance();
            kryo.setReferences(true);
            UnmodifiableCollectionsSerializer.registerSerializers(kryo);
            kryo.setInstantiatorStrategy(
                    new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy())
            );
            return kryo;
        }

    }

    public KryoCodec() {
        this(Collections.emptyList());
    }

    public KryoCodec(ClassLoader classLoader) {
        this(Collections.emptyList(), classLoader);
    }

    public KryoCodec(List<Class<?>> classes) {
        this(classes, null);
    }

    public KryoCodec(List<Class<?>> classes, ClassLoader classLoader) {
        this(new KryoPoolImpl(classes, classLoader));
    }

    public KryoCodec(KryoPoolImpl kryoPool) {
        super(kryoPool);
    }

}
```

**Non-working**:

```
public class KryoCodec extends org.redisson.codec.KryoCodec {

    private final KryoPoolImpl kryoPool;

    private static class KryoPoolImpl extends org.redisson.codec.KryoCodec.KryoPoolImpl {

        KryoPoolImpl(List<Class<?>> classes, ClassLoader classLoader) {
            super(classes, classLoader);
        }

        @Override
        protected Kryo createInstance() {
            Kryo kryo = super.createInstance();
            kryo.setReferences(true);
            UnmodifiableCollectionsSerializer.registerSerializers(kryo);
            kryo.setInstantiatorStrategy(
                    new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy())
            );
            return kryo;
        }

    }

    public KryoCodec() {
        this(Collections.emptyList());
    }

    public KryoCodec(ClassLoader classLoader) {
        this(Collections.emptyList(), classLoader);
    }

    public KryoCodec(ClassLoader classLoader, KryoCodec kryoCodec) {
        this(kryoCodec.kryoPool.getClasses(), classLoader);
    }

    public KryoCodec(List<Class<?>> classes) {
        this(classes, null);
    }

    public KryoCodec(List<Class<?>> classes, ClassLoader classLoader) {
        this(new KryoPoolImpl(classes, classLoader));
    }

    public KryoCodec(KryoPoolImpl kryoPool) {
        super(kryoPool);
        this.kryoPool = kryoPool;
    }

}
```

The only change on the latter is the addition of the new constructor which now is required.

**Comment by kfh** [comment]
@mrniko Do you have comments on this? There is no mention of this change in the docs, shouldn't it just be working as before? I can provide all our configurations if it's necessary.

**Comment by mrniko** [comment]
@kfh 

Could you share your original KryoCodec extension?

Basically if you don't use Redisson for both application and tomcat then you don't need to worry about it. If you do then constructor with `(ClassLoader classLoader, KryoCodec kryoCodec)` signature should be implemented.

**Comment by kfh** [comment]
The code I already posted is the one we use. The first one is valid for all versions including 3.10.0. 
The latter is the one I tried using for versions after 3.10.0, and as stated the only change is the addition of the new constuctor which Is required:

`public KryoCodec(ClassLoader classLoader, KryoCodec kryoCodec) {
    this(kryoCodec.kryoPool.getClasses(), classLoader);
}`

We are using Redisson with Tomcat. Our **manager** configuration is:

`<Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.base}/conf/redisson.json" readMode="MEMORY" updateMode="AFTER_REQUEST"/>`

and our redisson.json:

`{
  "sentinelServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "failedSlaveReconnectionInterval":3000,
    "failedSlaveCheckInterval":60000,
    "password":null,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "loadBalancer":{
      "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "subscriptionConnectionMinimumIdleSize":1,
    "subscriptionConnectionPoolSize":50,
    "slaveConnectionMinimumIdleSize":32,
    "slaveConnectionPoolSize":64,
    "masterConnectionMinimumIdleSize":32,
    "masterConnectionPoolSize":64,
    "readMode":"SLAVE",
    "subscriptionMode":"SLAVE",
    "sentinelAddresses":[
      "redis://myhost:26379"
    ],
    "masterName":"mymaster",
    "database":0
  },
  "threads":0,
  "nettyThreads":0,
  "codec":{
    "class":"no.finntech.redisson.codec.KryoCodec"
  },
  "transportMode":"NIO"
}`

**Comment by kfh** [comment]
@mrniko Do you need anything else? This should be fairly easy to replicate, the code is minimal. As stated we are only using Redisson on Tomcat level, not from application code. Redisson have been serializing and deserializing objects without any problems up til version 3.10.0. That new constructor which is added is causing problems, it's after all called from within your codebase. If you look at my first post I also provide which commit affects us([37b58db(https://github.com/redisson/redisson/commit/37b58db7bcc2bdf586e3ce2e55a37803fcd545fd)). I've looked through the code and the class loading part is definitely changed, I suspect there is a case which haven't been thoroughly tested.

**Comment by kfh** [comment]
@mrniko I have now tracked down what the problem is, in fact there are `2 problems`, I'll try and summarise my findings in a sound way.

1. Classloading.

As mentioned before we cannot load classes properly with the new constructor that is required after the changes introduced after version 3.10.0. I referred to a commit previously, after more digging, the actual commit which affects us is from `RedissonSessionManager`:

https://github.com/redisson/redisson/commit/79e03e13aac81f1fd94b3cdaa7b4da29817f27ab. 

The relevant code which is removed:

```
try {
	            Config c = new Config(config);
	            Codec codec = c.getCodec().getClass().getConstructor(ClassLoader.class)
	                            .newInstance(Thread.currentThread().getContextClassLoader());
	            config.setCodec(codec);
	            } catch (Exception e) {
	                throw new IllegalStateException("Unable to initialize codec with ClassLoader parameter", e);
	            }
```

The `codec` was previously set with the context class loader from the current thread as we can see, but now after the removal it looks like the class loader being used is the one set one the `configuration` object in the remaining code:

```
protected RedissonClient buildClient() throws LifecycleException {
        Config config = null;
        try {
            config = Config.fromJSON(new File(configPath), getClass().getClassLoader());
        } catch (IOException e) {
            // trying next format
            try {
                config = Config.fromYAML(new File(configPath), getClass().getClassLoader());
            } catch (IOException e1) {
                log.error("Can't parse json config " + configPath, e);
                throw new LifecycleException("Can't parse yaml config " + configPath, e1);
            }
        }
        
        try {
            return Redisson.create(config);
        } catch (Exception e) {
            throw new LifecycleException(e);
        }
    }
```

As we can see the class loader is now retrieved by `getClass().getClassLoader()`. For fun I swapped in the `Thread.currentThread().getContextClassLoader())` here and voila we load classes properly again. I'm not sure if this is the way it should be done but anyways it highlights the problem. 

2. Serialization

After solving the class loader issue I faced yet another problem regarding new code that's been added after version 3.10.0. I'll start by showing you the relevant part from `AttributeMessage`in commit: 

https://github.com/redisson/redisson/commit/ae14dba2fcd3150493a00f1cb97af6620745da70#diff-03d3a626de4bee1a40e901c62f2b4660

```
protected byte[] toByteArray(Object value) throws IOException {
			if (value == null) {
				return null;
			}
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
			ObjectOutputStream out = new ObjectOutputStream(bos);
			out.writeObject(value);
			out.flush();
			return bos.toByteArray();
		}
```

This one baffles me a bit, maybe we are using Redisson wrong or have misunderstood something, but doesn't this code contradict the whole point of us seraliazing using Kryo? If I understand this correctly you are trying to make byte arrays of all attribute messages by serializing it with plain java ? This will basicly fail for all our session data since nothing is implementing serializable and are made up of complex data structures. So my question is, why was this added and should you revert it?

**Comment by mrniko** [comment]
@kfh 

Thanks for your investigation of this problem.

> 1. The relevant code which is removed

The code was removed to solve issue then same Redisson instance is used in both tomcat and application. It was replaced with this code https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/command/CommandAsyncService.java#L806. So this allow to switch classloader dynamically depending on current thread context.

Anyway I'll try to investigate the issue you have with your custom codec.

> 2. Serialization
This one baffles me a bit, maybe we are using Redisson wrong or have misunderstood something, but doesn't this code contradict the whole point of us seraliazing using Kryo

You're right codec specified in Redisson configuration should be used instead of jdk serialization.

@jchobantonov for your information.

**Comment by jchobantonov** [comment]
@kfh if you mark your web application as distributable in your web.xml Tomcat itself will throw you exception if your object that you are trying to put into the session using setAttribute do not implement Serializable, so if you stick something into the session it should be Serializable in order to be replicated, that’s why when we transfer objects between the nodes we use serialization as the objects should implement serializable

From tomcat doc:

```
Whenever Catalina is shut down normally and restarted, or when an application reload is triggered, the standard Manager implementation will attempt to serialize all currently active sessions to a disk file located via the pathname attribute. All such saved sessions will then be deserialized and activated (assuming they have not expired in the mean time) when the application reload is completed.

In order to successfully restore the state of session attributes, all such attributes MUST implement the java.io.Serializable interface. You MAY cause the Manager to enforce this restriction by including the  <distributable> element in your web application deployment descriptor (/WEB-INF/web.xml).
```
So if you just try to add distributable tag into you web app you will see Tomcat throwing you exception that you object is not serializable right when you try to do session.setAttribute

Cc:
@mrniko

**Comment by kfh** [comment]
@jchobantonov You are basicly contradicting the whole point of offering serializing flexibility in Redisson by this statment: ` if you stick something into the session it should be Serializable`.

The quote from the Tomcat doc is pinned to the `standard session manager` used by Catalina, the whole point of Redisson is to be more flexible thus the custom Redisson session manager implementation.  What's even the point of storing state to disk when we have Redis as backend? There's a major flaw with the approach of assuming all objects should be serializable by the standard jdk implementation. If that be the case this whole section https://github.com/redisson/redisson/wiki/4.-data-serialization is irrelevant since you still are forced to comprehend to the jdk serialization contract. 

We bought into Redisson because of the flexibility. We have huge objects graphs on the session that are way too complicated for basic jdk serialization to handle, that's why we are using Kryo. It's nowhere stated in the Redisson docs that you need to implement serializable and the objects should be serializable by standard jdk. The code i referred to basicly makes Redisson after version 3.10.0 unusable for us and probably many others and breaks the design of Redisson Codec flexibility.

**Comment by jchobantonov** [comment]
@kfh ok, you are making a valid point
Just FYI the reason for this change was that if you use RedissonClient as JNDI resource then the thread that actually retrieve the new AttributeMessage objects will not be executed in web app classloader context and it cause ClassNotFoundException issues

@mrniko my suggestion then would be to refactor AttributesPutAllMessage and AttributeUpdateMessage and instead of having byte[] array that represent the Object as serialized version to have compound Object with 2 properties:
String codecClassName;
String byteBufHex;

Where codecClassName will have the codec class used to encode the value and byteBufHex will have hex value of io.netty.buffer.ByteBuf that is the result of using codec encode on the client object
This way when we send the AttributeMessage to Redisson topic, the other host will be able to properly decode the value (outside of web app classloader) and reconstruct AttributeMessage object fully. After that in RedissonSessionManager in updatesTopic.onMessage to get the AtrributeMessage and using getContext().getLoader().getClassLoader() that points to web context classloader to decode the bytebuf to the client object that is been send

@mrniko

**Comment by mrniko** [comment]
Problem with classloading fixed in https://github.com/redisson/redisson/issues/1959

**Comment by mrniko** [comment]
@kfh 

AttributeMessages serialization now use codec provided in Redisson configuration. Thanks for pointing out!
