### ISSUE TITLE
SpringBoot 2.1.2 Hibernate 53 L2 Cache

### ISSUE THREAD

**Issue by rshibley** [redisson/redisson#1909]
I am getting the following error when starting the server: 
**Unable to create requested service [org.hibernate.cache.spi.RegionFactory]**

**build.gradle**
implementation 'org.redisson:redisson-spring-boot-starter:3.10.2'
implementation 'org.redisson:redisson-hibernate-53:3.10.2'
implementation 'org.xerial.snappy:snappy-java:1.1.7.2'
runtime 'javax.cache:cache-api'

**application.yml**

spring:
jpa:
    generate-ddl: false
    show-sql: false
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate:
        ddl-auto: create
        dialect: com.codefish.model.hibernate.MySqlDialect
        generate_statistics: false
        show_sql: false
        use_sql_comments: false
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region_prefix: hibernate
          region.factory_class: org.redisson.hibernate.RedissonRegionFactory
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc.dispatch-options-request: true

**Comment by mrniko** [comment]
Could you share full stacktrace?

**Comment by rshibley** [comment]
The error was coming out of the RegionFactory... couldn't find the redisson.yaml. I had to override the factory and provide my own Config Implementation.

**Comment by mrniko** [comment]
You could set define path to your config through `hibernate.cache.redisson.config` setting
