### ISSUE TITLE
Question: does fair locking work when used from within multiple Java VMs?

### ISSUE THREAD

**Issue by mroloux** [redisson/redisson#1910]
Hi,

I'm interested in using the fair locking feature from Reddison. But it looks like it doesn't work properly when used from within multiple Java VMs. Unless I'm missing something.

The reason: Reddison uses the thread ID when acquiring a lock. A thread ID in Java is not a UUID, but an integer that's unique only within a single VM:

```
public void lockInterruptibly(long leaseTime, TimeUnit unit) throws InterruptedException {
  long threadId = Thread.currentThread().getId();
  Long ttl = tryAcquire(leaseTime, unit, threadId);
  ... 
}
```

Could anyone clarify this please?

**Comment by mrniko** [comment]
RFairLock object could be used by multiple JVMs. threadId is used to enforce unlock method invocation. According to Java Lock specification only thread acquired lock can unlock it.

**Comment by mroloux** [comment]
Ok, thanks. Will look into this.
