### ISSUE TITLE
[Suggestion] Return RxJava2 specific types in RObjectRx

### ISSUE THREAD

**Issue by slisaasquatch** [redisson/redisson#1912]
### Actual behavior
So I recently noticed the existence of `RedissonRxClient` which returns `RObjectRx` with `Flowable`s.
To me this is a missed opportunity. One of the biggest reasons I prefer RxJava2 over Reactor Core is that it has distinct types for 1 element, 0..1 element, and 0 element, instead of just having `Mono`.
IMO `RObjectRx` should be returning RxJava2 specific types. For example, `Flowable<Void> restore(byte[] state);` should be `Completable restore(byte[] state);`, and `Flowable<Boolean> isExists();` should be `Single<Boolean> isExists();`. And if the user wants standard reactive streams types, they still have the option of using `RedissonReactiveClient`, or they can easily call methods like `Single.toFlowable()`.
### Steps to reproduce or test case
N/A
### Redis version
N/A
### Redisson version
3.9.1
### Redisson configuration
N/A

**Comment by mrniko** [comment]
You could simply transform Flowable with `Single.fromPublisher` or `Completable.fromPublisher` method.

**Comment by slisaasquatch** [comment]
Well, that's exactly my point. You can also do that with `RedissonReactiveClient`, so `RedissonRxClient` is not providing much benefit for RxJava2 users over `RedissonReactiveClient`.

**Comment by mrniko** [comment]
Done. Thank you for the suggestion!
