### ISSUE TITLE
Rename RedissonMap then set value in map , the value will put in the old map

### ISSUE THREAD

**Issue by sadanyoyo** [redisson/redisson#1913]
```
        Config config = new Config();
        config.useSingleServer().setAddress("addrss").setPassword("passwd");
        RedissonClient client = Redisson.create(config);
        RMap<String, String> map = client.getMap("aaa");
        map.put("111","222");  // 1
        map.rename("bbb");
        map.put("222222","333333");   // 2
        client.shutdown();
```
the 1 will move into 'bbb' map, but the 2 will put in the 'aaa' map,not the new one 'bbb'.

**Comment by sadanyoyo** [comment]
I am using 3.10.2 with spring session.
When user login, security call session to chang it id. Redisson will tell its map change its name. When this request is finished, security write its context into session. But this context is writen into the old one. So it is lost.

**Comment by mrniko** [comment]
Fixed! thanks for report
