### ISSUE TITLE
Redis stream not working at all in 3.10.2

### ISSUE THREAD

**Issue by zivziv77** [redisson/redisson#1914]
Hello
I am trying to make the stream example work with new redisson version 3.10.2 .
I get ArrayIndexOutOfBounds in class StreamIdDecider.
While it assume having 3 parameters. First one number-number key value.
This is not true input to this class is not these arguments.
Can you take a look?

Thanks

**Comment by mrniko** [comment]
Could you provide code example to reproduce this?

**Comment by zivziv77** [comment]
I am trying exactly the example that in the documentation.
I noticed StreamId was changed to StreamMessageId. I am using the StringDecoder on getStream and getting an exception on StreamIdDecoder when trying to parse the id.
It parses by mistake the key of the stream.
I will try to send you the example later today.
Thanks

**Comment by zivziv77** [comment]
Guys I am sorry I was using non GA version of redis.
When I upgraded to latest GA everything is working as expected.

Thanks
Ziv
