### ISSUE TITLE
Redis create group with empty stream if does not exsist

### ISSUE THREAD

**Issue by zivziv77** [redisson/redisson#1915]
Hi

I think it would be nice and will be much better to give the user an option to use the mkstream when creating a group.

This option create the stream attached to the group if it does not exist.
Please take a look here:

https://github.com/antirez/redis/issues/4824

Thanks
Ziv

**Comment by mrniko** [comment]
Done

**Comment by zivziv77** [comment]
Thank you. Wanna make sure what is the expected release date?

**Comment by zivziv77** [comment]
I just want to make sure that is it optional to create stream if not exist ? Or it is automatically creating the stream?
