### ISSUE TITLE
setPingTimeout deprecated without any note

### ISSUE THREAD

**Issue by aaabramov** [redisson/redisson#1921]
According to [this commit](https://github.com/redisson/redisson/commit/696c2ec8d97c5cc7a775d1bd2c90001827cb38dd#diff-a6b60c28589b4a079639f044228b6b4d) `org.redisson.config.BaseConfig#setPingTimeout` became deprecated. But there is no migration or deprecation note.

Are there any notes on this? Maybe this config option became redundant?

### Redisson version
**3.10.2**

**Comment by mrniko** [comment]
`pingConnectionTimeout` should be used instead

**Comment by mrniko** [comment]
Thanks for pointing out!

The idea is to specify timeout as parameter for `Node.ping` and `Node.pingAll` methods. Just forgot to add these methods.
