### ISSUE TITLE
FSTCodec memory leak

### ISSUE THREAD

**Issue by astmuc** [redisson/redisson#1927]
several puts (5-10) into a MapCache guarded with a Lock seems to accumulate the payloads in thread locals. The payload is large (several Mb) and the pod (dockered spring boot app with 700 Mb max) goes out of heap. The app running with redisson 3.7.5 has no such problems.

redisson 3.10.2

      config
        .useMasterSlaveServers()
        .setMasterAddress(redisHost)
        .addSlaveAddress(redisSlave)
        .setPassword(redisPassword)
        .setTimeout(10000);

redis 4.0.1 (master, slave)

![mat-1](https://user-images.githubusercontent.com/37765839/53153947-d331f800-35b9-11e9-8903-e1e021632545.png)

**Comment by mrniko** [comment]
Could you share code sample to reproduce this?

**Comment by astmuc** [comment]
The bug appears after fresh start doing 5-10 performs which are webservice calls returning each ca. response which is stored in CacheMap in Json format (several MB)


`package cops.backend.service;

import java.io.IOException;
import java.io.Serializable;
import java.util.concurrent.TimeUnit;

import javax.annotation.PostConstruct;

import org.redisson.api.RLock;
import org.redisson.api.RMapCache;
import org.redisson.api.RedissonClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.env.Environment;
import org.springframework.security.core.context.SecurityContextHolder;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import brave.Tracer;
import cops.common.service.AgentSessionsClient;
import cops.common.service.SessionMode;
import cops.model.common.ServerGroup;

/**
 * Contains redis cache, hystrix on-off and service meta-data properties
 * for all {@link BackendServiceOperation} implementations. The redis cache use JSON representation
 * of the response, since not all responses are {@link Serializable}.
 * @author Stiller, Andreas
 *
 * @param <I> input type
 * @param <O> output type
 */
public abstract class BaseBackendServiceOperation<I,O> implements BackendServiceOperation<I, O>{

  protected final Logger log = LoggerFactory.getLogger(getClass());

  private final Class<O> clazz;

  private final ServerGroup serverGroup;

  private final String serviceName;

  private final String operationName;

  private int expirySeconds;

  private int lockTimeoutSeconds;

  protected boolean useHystrix;

  private RedissonClient redisson;

  private ObjectMapper objectMapper;

  private Tracer tracer;

  private RMapCache<String, String> cache;

  private AgentSessionsClient agentSessionsClient;

  private Environment environment;
  
  public BaseBackendServiceOperation(Class<O> clazz,
      ServerGroup serverGroup, String serviceName, String operationName) {
    super();
    this.clazz = clazz;
    this.serverGroup = serverGroup;
    this.serviceName = serviceName;
    this.operationName = operationName;
  }

  /**
   * Override to implement the webservice operation.
   * @param in
   * @param additionalParams
   * @return output payload
   */
  protected abstract O actualOperation(I in, Object ... additionalParams);

  protected boolean useCache() {
    return !environment.getProperty("cops.ignoreRedisCache", Boolean.class, false) && redisson != null;
  }
  
  protected O actualOperation(Context<I> context) {
    return actualOperation(context.param(), context.additionalParams());
  }

  public String marshallAsJson(O response) {
    try {
      return objectMapper.writeValueAsString(response);
    } catch (JsonProcessingException e) {
      log.error("marshall failed", e);
      throw new RuntimeException(e);
    }
  }

  public O unmarshallFromJson(String responseAsJson) {
    O response = null;
    try {
      if (responseAsJson != null) {
        response = objectMapper.readValue(responseAsJson, resultClazz());
      }
    } catch (IOException e) {
      log.error("unmarshall failed", e);
      throw new RuntimeException(e);
    }
    return response;
  }

  public String mockFileNamePattern() {
    return String.format("%s-%s", serviceName(), operationName()) + "-%s";
  }

  @Override
  public Class<O> resultClazz() {
    return clazz;
  }

  @Autowired
  public void setRedissonParameters(
      @Value("${cops.redis.cache-expiry-seconds:300}") int expirySeconds,
      @Value("${cops.redis.lock-timeout-seconds:40}") int lockTimeoutSeconds) {
    this.expirySeconds = expirySeconds;
    this.lockTimeoutSeconds = lockTimeoutSeconds;
  }

  @Autowired
  public void setObjectMapper(ObjectMapper objectMapper) {
    this.objectMapper = objectMapper;
  }
  
  @Autowired
  public void setTracer(Tracer tracer) {
    this.tracer = tracer;
  }
  
  @Autowired(required=false)
  public void setRedisson(RedissonClient redisson) {
    this.redisson = redisson;
  }
  
  @Autowired
  public void setAgentSessionsRestTemplate(AgentSessionsClient agentSessionsClient) {
    this.agentSessionsClient = agentSessionsClient;
  }
  
  @Autowired
  public void setUseHystrix(@Value("${cops.useHystrix:true}") boolean useHystrix) {
    this.useHystrix = useHystrix;
  }
  
  @Autowired
  public void setEnvironment(Environment environment) {
    this.environment = environment;
  }
  
  @PostConstruct
  protected void initCache() {
    if (redisson != null) {
      cache = redisson.<String,String>getMapCache(getMapName());
    }
  }

  protected RedissonClient redissonClient() {
    return redisson;
  }

  protected ObjectMapper objectMapper() {
    return objectMapper;
  }

  public Tracer tracer() {
    return tracer;
  }

  public boolean useHystrix() {
    return useHystrix;
  }

  private String getMapName() {
    return String.format("%s/%s/%s", serverGroup(), serviceName(), operationName());
  }

  /**
   * Implements the perform with redis caching. The algorithm delegates to
   * {@link #actualOperation(Object, Object...)}.
   */
  public O perform( Context<I> context ) {
    O result = null;
    long t1 = System.currentTimeMillis();

    if ( useCache() ) {
      result = unmarshallFromJson(cache.get(context.cacheKey()));
    }
    if (result == null) {

      RLock keyLock = null;
      if ( useCache() ) {
        keyLock = cache.getLock(context.cacheKey());
      }
      try {
        if ( keyLock != null ) {
          keyLock.lockInterruptibly(lockTimeoutSeconds, TimeUnit.SECONDS);
        }
        long t2 = System.currentTimeMillis();
//        log.info("TIMING (lock wait) {}-{}: {}", serviceName, operationName, t2 - t1);

        if ( useCache() ) {
          result = unmarshallFromJson(cache.get(context.cacheKey()));
        }
        if (result == null) {

          result = actualOperation(context);

          long t3 = System.currentTimeMillis();
          log.info("TIMING {}-{}: {}", serviceName, operationName, t3 - t2);

          String resultAsJson = marshallAsJson(result);
//          log.debug("\n{}\n", resultAsJson);
          if ( useCache() ) {
            cache.put(context.cacheKey(), resultAsJson, expirySeconds, TimeUnit.SECONDS);
          }
//          log.info("TIMING (cache-store) {}-{}: {}", serviceName, operationName, System.currentTimeMillis() - t3);
        } else {
          long t3 = System.currentTimeMillis();
          log.info("TIMING (cache-hit, locked) {}-{}: {}", serviceName, operationName, t3 - t2);
          context.trace("cache hit (locked)");
        }
      } catch (InterruptedException e) {
        log.warn("lock for {}-{} interrupted, returning no result", serviceName, operationName);
        // handle this as not found
      } finally {
        if (keyLock != null) {
          keyLock.unlock();
        }
      }
    } else {
      context.trace("cache hit (no lock)");
      long t2 = System.currentTimeMillis();
      log.info("TIMING (cache hit, no lock) {}-{}: {}", serviceName, operationName, t2 - t1);
    }
    return result;
  }

  public ServerGroup serverGroup() {
    return serverGroup;
  }

  public String serviceName() {
    return serviceName;
  }

  public String operationName() {
    return operationName;
  }

  public void writeResultToSession(Context<I> context, String payload) {
    SessionInfo si = context.sessionInfo();
    if (SessionMode.CURRENT.equals(si.sessionMode()) && si.sessionId() != null) {
      try {
        SecurityContextHolder.getContext().setAuthentication(si.authentication());
        agentSessionsClient.writeSessionRawData(si.sessionId(), serviceName(), operationName(), context.cacheKey(), payload);
        log.debug( "written {}/{} payload written to session {}", serviceName(), operationName(), si.sessionId());
      } catch (Exception e) {
        log.warn("write raw data failed", e);
        SecurityContextHolder.clearContext();
      }
    } else {
      log.debug( "writeResultToSession ignored for {}", si);
    }
  }


}
`

**Comment by mrniko** [comment]
Unable to reproduce. Here is my test:

```java
    @Test
    public void testLeak() throws InterruptedException {
        Config config = new Config();
        config.useSingleServer()
              .setAddress(RedisRunner.getDefaultRedisServerBindAddressAndPort());

        RedissonClient redisson = Redisson.create(config);

        Thread.sleep(10000);
        System.out.println("start");
        
        for (int i = 0; i < 10; i++) {
            RMapCache<String, String> cache = redisson.getMapCache("mycache");
            String key = RandomString.make(120);
            RLock keyLock = cache.getLock(key);
            keyLock.lockInterruptibly(10, TimeUnit.SECONDS);
            try {
                cache.put(key, RandomString.make(2*1024*1024), 5, TimeUnit.SECONDS);
            } finally {
                if (keyLock != null) {
                    keyLock.unlock();
                }
            }
        }
        
        System.out.println("done");
    }
```

No memory leaks were found:

![image](https://user-images.githubusercontent.com/1104661/53231189-60984980-3699-11e9-823a-b3d383a2d205.png)

**Comment by astmuc** [comment]
i think its related the nustaq thread locals. They seem to keep huge payloads forever. All heap dumps show that the netty threads hold the big payload in a thread local.

i can control the velocity of going out of memory with the connection pool size. Huge pool means faster out of memory.

If this is true, then it would a "limited memory leak" with a size limit of connectionpoolsize * biggest payload

**Comment by mrniko** [comment]
Fixed. Thanks for report!

I suggest you to consider SnappyCodec or LZ4Codec to compress lot of text data.

**Comment by mrniko** [comment]
Seems it requires to implement own version `org.nustaq.serialization.FSTConfiguration.StreamCoderFactory`  with proper byte array allocation management.

**Comment by mrniko** [comment]
Done

**Comment by brecht-yperman-tb** [comment]
We are seeing a very similar issue using 3.10.7, over 1.4 million instances of FastThreadLocal on 96 FastThreadLocalThreads

![threadlocals](https://user-images.githubusercontent.com/54902265/64267163-2e17b500-cf36-11e9-88b3-034a96e5f4a4.png)
![threads](https://user-images.githubusercontent.com/54902265/64267085-0de7f600-cf36-11e9-8fd3-cb0d20c6a0e8.png)

It's a sentinelServersConfig with 4 addresses and the following global config

```
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"
```

This seemingly results in the old gen heap growing, causing long pauses.

![memory](https://user-images.githubusercontent.com/54902265/64267398-9feffe80-cf36-11e9-9c8b-746098a91403.png)

Maybe there's another leak?
