### ISSUE TITLE
Redisson hibernate entity cache TTL and MaxIdleTime not being set - default region used for entities 2nd level cache

### ISSUE THREAD

**Issue by jayeshnazre** [redisson/redisson#1929]
### Expected behavior

The TTL and MaxIdeltime once set should auto-evict the hibernate entity beans cached in redis.
### Actual behavior
The beans are not auto-evicted when TTL expires and the idle time has elapsed.
### Steps to reproduce or test case
**Step 1)** 
Create a simple entity bean (Say - com.jhipster.demo.blog.domain.Tag) 
**Step 2)** 
Annotate the same with the following
@Cacheable(cacheNames = "com.jhipster.demo.blog.domain.Tag")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
**Step 3)**
Try to set the TTL and config via code
@Configuration
@EnableCaching 
public class CacheConfig {
    @Bean
    CacheManager cacheManager(RedissonClient redissonClient) throws IOException {
        config.put("com.jhipster.demo.blog.domain.Tag", 
        		new CacheConfig(120000, 180000)); //2min TTL and 3min max idle time
        return new RedissonSpringCacheManager(redissonClient, config);
    }

}

**NOTE**: The auto-eviction with TTL set at code level works for Spring cache only not hibernate second level cache for entity.

**Step 4)**
I also tried to set the TTL and max idle time via application.properties file
spring.jpa.properties.hibernate.cache.redisson.entry.eviction.max_entries=2000
spring.jpa.properties.hibernate.cache.redisson.entry.eviction.time_to_live=120000
spring.jpa.properties.hibernate.cache.redisson.entry.eviction.max_idle_time=180000

**NOTE:** I thought of using the application.properties file (since I am using spring boot, this file is auto picked)
I got this idea of overriding the default from the following Redisson link -
https://github.com/redisson/redisson/tree/master/redisson-hibernate

In that link I see default properties being set for  all entity like - 

<property name="hibernate.cache.redisson.entry.eviction.max_entries" value="10000" />
<property name="hibernate.cache.redisson.entry.expiration.time_to_live" value="600000" />
<property name="hibernate.cache.redisson.entry.expiration.max_idle_time" value="300000" />

So I thought I can set the same via spring boot application.properties file 

Anyhow both Step 3/4 does not set the TTL correctly for me and the entity is not auto-evicted.

**NOTE:** The auto-eviction with TTL set at code level works for Spring cache only not hibernate second level cache.

### Redis version
5.0.3
### Redisson version
3.10.2
### Redisson configuration
I am using the single server mode and the configuration is the defualt as outlined in the link below for "singleServerConfig"

https://github.com/redisson/redisson/wiki/2.-Configuration#26-single-instance-mode 

**NOTE**: I am using Hibernate 5.3.7, Spring boot 2.1.2, Redisson 3.10.2 version.

**Comment by mrniko** [comment]
@Cacheable annotation isn't discovered by Hibernate. Currently you need to define default ttl and maxidletime settings through hibernate.cfg.xml file

**Comment by jayeshnazre** [comment]
I understand that @Cacheable is not detectable via hibernate but I am using @Entity as well as @Cache which hibernate recognizes. I am using spring boot annotation for hibernate instead of hibernate.cfg.xml. So my entities are being cached in redis and thats not the problem, its just that I am not able to set the TTL and maxIdletime for them below is a code snippet from my entity class
@Entity
@Table(name = "tag")
@Cacheable(cacheNames = "com.jhipster.demo.blog.domain.Tag")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Tag implements Serializable {

So my question is how to set the TTL and MaxIdleTime for the entity can you point me to the sample code snippet even a pseudo code pointer will help. I also understand that TTL cannot be set via annotation hence asking

Thanks for responding

**Comment by mrniko** [comment]
I need to implement support of hibernate settings defined in spring boot application file first. So your issue could be considered as a feature request in this case.

**Comment by jayeshnazre** [comment]
Aah 
So are you saying that at this point of time I cannot set those values via spring boot application.properties file. Thats a bummer. I am using spring boot and spring data JPA with hibernate and I am finding it hard to now use the hibernate.cfg.xml file as I need to now peel the onion of auto-configuration benefit that I get through spring boot for micro-services. Can you assist in pointing me how to set the TTL and MaxIdeltime with spring boot using the  hibernate.cfg.xml . Thanks

**Comment by jayeshnazre** [comment]
Any help @mrniko ? What I am trying to do here @mrniko is that I have a working spring boot, spring data jpa application with hibernate as the JPA implementation - I am using repositories as well. All other hibernate properties are getting set via application.properties file as per this link

https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html 

So I am not sure how I can now override the default values for TTL and MaxIdeltime using hibernate.cfg.xml just for Redisson. Any pointers. 

I also looked at this link: 
https://github.com/debop/hibernate-redis 

where the person seems to be setting some Redisson/redis properties in application.properties file but that is not working for me, it also looks like an older version of Redisson in use in that example.

Any help will be much appreciated. I am sure at some point you will integrate the setting into spring boot properties file but in the meantime can you provide me with some workarounds.

**Comment by mrniko** [comment]
Are you able to register `org.springframework.orm.hibernate5.LocalSessionFactoryBean`? it allows to define hibernate.cfg.xml

**Comment by jayeshnazre** [comment]
OK so I finally tried to do the spring MVC with  Hibernate 5.4.1.Final, Spring mvc 5.1.5.RELEASE, Redisson 3.10.2 version, removing the use of spring boot and I was able to set hibernate properties via code as follows
        hibernateProperties.setProperty(
                "hibernate.cache.redisson.entry.eviction.max_entries", 
                "200");
        hibernateProperties.setProperty(
                "hibernate.cache.redisson.entry.expiration.time_to_live", 
                "120000");
        hibernateProperties.setProperty(
                "hibernate.cache.redisson.entry.expiration.max_idle_time", 
                "180000");
        
I used h2 database for testing and used the code similar to what is mentioned in link below
https://www.baeldung.com/hibernate-5-spring

I waited for 2 minutes (120000) and my hibernate cache did not delete 
@mrniko - any idea why its not working. The Redisson cache stays for ever which for a large project can be an issue. 
Any pointers?

**Comment by mrniko** [comment]
@jayeshnazre 

You defined both `time_to_live` and `max_idle_time` parameters. In your case max_idle_time took precedence since it has greater value.

**Comment by jayeshnazre** [comment]
@mrniko 
I do not think that is the issue here. I could be mistaken. I waited for 30min and still the hibernate second level cache was not expiring unless you are saying I am doing something wrong here. Can you help as always thanks for responding. NOTE: Spring cache is working with TTL etc. I can see the redisson__tasks scripts being executed in redis just not for any hibernate cache.

SOS.

**Comment by mrniko** [comment]
@jayeshnazre 

Here is the test I use to make sure TTL work properly: 

https://github.com/redisson/redisson/blob/master/redisson-hibernate/redisson-hibernate-52/src/test/java/org/redisson/hibernate/ReadWriteTest.java#L60

**Comment by jayeshnazre** [comment]
@mrniko 
I have enabled hibernate statistics as well as show SQL to see if SQL gets executed or whether hibernate picks data from L2 cache.  I am using stateless REST API via Spring boot RestController (annotation). I am also using redis-commander user interface for redis key lookups.
https://www.npmjs.com/package/redis-commander 
Below is the log snippet of L2 hibernate cache hit after 30 minutes of wait and the hibernate not executing a SQL to get fresh data that’s how I know redisson is not clearing the cache.
    **40559088 nanoseconds spent performing 1 L2C hits;** 

When I try to get data via primary key (ID) for the first time - I see a SQL executed for the first time. after that Hibernate continues to pick from the cache and I see the above log saying L2C hits (and I do wait for 30 minutes)

Any help?

**Comment by mrniko** [comment]
@jayeshnazre 

Could you share your entity model?

**Comment by jayeshnazre** [comment]
@mrniko  -- I have created a sample Spring MVC application without using spring boot. It has one entity Tag and you can use it to test the issue. Let me know thanks and appreciate your help on this

[myspringmvcjpacache_ver3.zip](https://github.com/redisson/redisson/files/2926626/myspringmvcjpacache_ver3.zip)

**Comment by jayeshnazre** [comment]
@mrniko
Any help looking at the source code. Were you able to recreate the problem. Let me know.
SOS. Thanks

**Comment by mrniko** [comment]
@jayeshnazre 

Thank you for the provided demo app! I'm trying to figure out what the problem is.

**Comment by mrniko** [comment]
@jayeshnazre 

I confirm it's a bug. Could you try hibernate 5.2 cache module as well?

**Comment by mrniko** [comment]
@jayeshnazre 

I have found the cause - typo in the documentation.

use _hibernate.cache.redisson.**entity**.eviction.max_entries_ instead of hibernate.cache.redisson.entry.eviction.max_entries

_hibernate.cache.redisson.**entity**.expiration.time_to_live_ instead of hibernate.cache.redisson.entry.expiration.time_to_live

_hibernate.cache.redisson.**entity**.expiration.max_idle_time_ instead of hibernate.cache.redisson.entry.expiration.max_idle_time

**Comment by abdulwhd964** [comment]
Hi 

i tried with the below in the application.properties file

hibernate.cache.redisson.entity.expiration.time_to_live=120000
hibernate.cache.redisson.entity.expiration.max_idle_time=180000
hibernate.cache.redisson.entity.eviction.max_entries=200

but i still the value are picking from the redis cache even after the time has been elasped

2024-12-01 16:57:15.583  INFO 25256 --- [nio-8080-exec-6] com.pamesh.service.impl.UserServiceImpl  : Getting user with id 2
2024-12-01 16:57:15.584 DEBUG 25256 --- [nio-8080-exec-6] o.h.e.t.internal.TransactionImpl         : On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
2024-12-01 16:57:15.584 DEBUG 25256 --- [nio-8080-exec-6] o.h.e.t.internal.TransactionImpl         : begin
2024-12-01 16:57:15.590 DEBUG 25256 --- [nio-8080-exec-6] o.h.e.t.internal.TransactionImpl         : committing
2024-12-01 16:57:15.592  INFO 25256 --- [nio-8080-exec-6] i.StatisticalLoggingSessionEventListener : Session Metrics {
    
2488000 nanoseconds spent performing 1 L2C hits;

attached my project in the below ,, i did everything but it doesnt clear the cache at all, please help me on this

    
[spring-cache-redis.zip](https://github.com/user-attachments/files/17968955/spring-cache-redis.zip)

**Comment by abdulwahidpanaroma** [comment]
@mrniko  please help me on this
