### ISSUE TITLE
Why does LocalCachedMap.readAllValues() need to avoid reading phantom value?

### ISSUE THREAD

**Issue by a2232189** [redisson/redisson#1930]
> This is to avoid reading phatom local values.

_Originally posted by @jackygurui in https://github.com/redisson/redisson/issues/1823#issuecomment-450841454_

However mrniko said If element has been added/removed then invalidation message sent to all LocalCachedMap instances and element evicted in all of them.(https://github.com/redisson/redisson/issues/592#issue-173190357)

What mrniko said means local cache will be synced by Redis pub/sub mechnism. If so, why does jackygurui said LocalCachedMap.readAllValues() need to read redis value to avoid reading local phantom value? Since local cache value will be synced, I think there is no phantom local values.

**Comment by mrniko** [comment]
phantom values could appear if data in redis already changed but it's not yet reflected in local cache because of pub/sub message transfer delay.
