### ISSUE TITLE
RBucket compareAndSet can`t return Boolean.TRUE

### ISSUE THREAD

**Issue by legend91325** [redisson/redisson#1931]
### Expected behavior
I have a method:
 public Boolean compareAndSetTaskBuckets(List<TaskBucket> except ,List<TaskBucket> update){
        RBucket<List<TaskBucket>> taskRunningBucket = redissonClient.getBucket(ROBOT_TASK_RUNNING);
        return taskRunningBucket.compareAndSet(except, update);
    }

I excpet return true,but it still return false;
### Actual behavior
it still return false

### Steps to reproduce or test case
just first set an list object, then call this compareAndSetTaskBuckets method，it always return false。

### Redisson version
3.9.1
### Redisson configuration
singleServerConfig

**Comment by mrniko** [comment]
Unable to reproduce with 3.10.2 version.

Here is my test case:
```java
        List<Integer> list1 = Arrays.asList(1, 2, 3);
        List<Integer> list2 = Arrays.asList(1, 2);
        RBucket<List<Integer>> al = redisson.getBucket("test");
        al.set(list1);
        assertThat(al.compareAndSet(list1, list2)).isTrue();
```
