### ISSUE TITLE
Live Object write/read Bug (分布式实时对象存取异常)

### ISSUE THREAD

**Issue by leerenbo** [redisson/redisson#1934]
![image](https://user-images.githubusercontent.com/6948368/53312319-8ae34480-38ef-11e9-8826-832928136025.png)

![image](https://user-images.githubusercontent.com/6948368/53312346-f6c5ad00-38ef-11e9-8511-0355709786d0.png)

![image](https://user-images.githubusercontent.com/6948368/53312377-be25d380-38ef-11e9-8208-e9877b2cf373.png)

![image](https://user-images.githubusercontent.com/6948368/53312435-f3322600-38ef-11e9-92be-ebe2e709f81d.png)

firstname=aaa   not store in redis。   
looks like bytebuddy proxy has problem。

**Comment by jackygurui** [comment]
Currently RLO only supports JavaBean style POJO beans, doesn't support decorator style POJO beans. Therefore if you change the return type of the setters to `void`, it would work as expected.

**Comment by leerenbo** [comment]
> Currently RLO only supports JavaBean style POJO beans, doesn't support decorator style POJO beans. Therefore if you change the return type of the setters to `void`, it would work as expected.

POJO beans works well.   
hopes add chain programming feature.

考虑增加链式编程的支持吧。这个还是蛮常用的。

**Comment by jackygurui** [comment]
Thanks for confirming it is working for you. Totally understood the usefulness of decorator pattern, the problems is there is no standard naming convension for decorator patterns. Do you have any suggestions as how you want it to work?
