### ISSUE TITLE
redlock unlock fail

### ISSUE THREAD

**Issue by wy545** [redisson/redisson#1937]
redlock采用多个redis实例，避免了主从复制导致的锁丢失问题。
但是好像没有考虑到单台redis实例解锁失败的问题把？
如果单台redis实例解锁成功的概率是0.9，那么有N台实例去解锁，那么成功率肯定会降低的，不知道我的理解对不对？

**Comment by jackygurui** [comment]
>单台redis实例解锁成功的概率是0.9

能具体讲讲解锁成功率的概念吗？

**Comment by wy545** [comment]
应该是这样。现在有3个redis实例，单个redis实例释放锁成功的概率是90%，那么根据redlock算法，如果从超过一半的redis实例中获取锁成功则成功。那么，3个实例中，有两个实例都释放锁成功的概率为：3*0.9*0.9*0.1 = 0.243，3个实例都释放锁成功的概率为：1*0.9*0.9*0.9=0.729===》则总的释放锁成功率为0.243 + 0.729 > 单个redis实例的成功率0.9.  抱歉，我之前好像说错了。
===============================================
但是在分布式环境中，引入了更多的redis实例，意味着有更多的网络交互，那么网络的不确定性会更大，因为网络等原因导致redis实例释放锁失败的可能性会不会也更大呢？

**Comment by jackygurui** [comment]
网络上的不确定性不是归为失败率里面一起计算的吗？
