### ISSUE TITLE
redlock unlock question

### ISSUE THREAD

**Issue by wy545** [redisson/redisson#1940]
你好，看了下redlock实现的源码，发现如果存在下面这种情况是无法解决的：
假设有6个redis节点，client1和client2同时向redis实例获取同一个锁资源，那么可能发生的结果是——client1获得了3把锁，client2获得了3把锁，由于都没有超过半数，那么client1和client2获取锁都失败；

不知道对于这种场景，除了限制节点个数为奇数，还有其他更好的选择么

**Comment by jackygurui** [comment]
> 由于都没有超过半数，那么client1和client2获取锁都失败

这是设计要求，不是问题。

**Comment by wy545** [comment]
redlock源码在加锁的时候，如果返回的是超时异常，那么会让redis释放锁，源码如下：
![image](https://user-images.githubusercontent.com/20380902/53416308-31256c00-3a0e-11e9-81ab-c5a738dd4194.png)

同样，如果客户端1在获取这个锁的时候发生了网络异常，恰巧该redis实例节点上的锁是被其他客户端2获取了，那么客户端1会让redis把这个锁删除，这样不就是有问题了么？？？

**Comment by jackygurui** [comment]
解锁时只会解自己所拥有的锁，不会解其它的锁

**Comment by wy545** [comment]
我是这个意思，client1和client2是获取同一把锁lock1，key=a，value不同；
现在有三个redis1，2和3，client1从redis1上获取了一把锁，client2从redis2上获取了一把锁，现在client1和client2同时向redis3获取锁，client2从redis3成功获取了锁，，但是client1由于网络问题，抛出redisresponsetimeoutexception，因此client1要求redis3释放该锁，即redis3会删除key=a的。。。
不知道我的理解有没有问题？如果是上述这种情况，那么不就会误释放锁了么？？？？

**Comment by jackygurui** [comment]
解锁不等于简单的删除key。不是你的锁，你是释放不了的。

**Comment by wy545** [comment]
不好意思，是的，没有问题的

**Comment by gitstudy007** [comment]
> 解锁时只会解自己所拥有的锁，不会解其它的锁

这个自己是线程维度的，不知道redisson有没有进程维度的加锁解锁方法？譬如在分布式环境下，有多个jvm实例，加锁的时候是某个jvm实例中的某个线程，解锁的时候只要是同一个jvm实例中任意线程都能解锁
