### ISSUE TITLE
Method 'findKeysByPatternAsync' always get all the keys

### ISSUE THREAD

**Issue by handjgit** [redisson/redisson#1946]
For this code 
“RBatch batch = client.createBatch();
Future<Collection<String>> future = batch.getKeys().findKeysByPatternAsync(PATTERN_PREFIX + "*");"

it always return all matching keys?

In case the number of keys is very large , I need to get keys in batches. There seems to be no way out.

**Comment by mrniko** [comment]
`RKeys.findKeysByPatternAsync` method is deprecated. Please use `RKeys.getKeysByPattern` instead it allows to specify batch size.

**Comment by handjgit** [comment]
Although method 'RKeys.getKeysByPattern'  is to get key in batches，But eventually it will put all the keys in  the memory.I mean, is there a method like the cursor  of redis-client?

**Comment by mrniko** [comment]
@handjgit 

No, it doesn't put all the keys in memory. it uses Redis cursor command

**Comment by handjgit** [comment]
So, if a value of 500 is assigned to the 'count' parameter,It only returns 500 keys？but,how can I get the next 500 matching keys? and then next next 500 matching keys? Until I get all the keys.

**Comment by mrniko** [comment]
it will return all keys and request to redis for next 500 keys during iteration once you traversed previous values.

**Comment by handjgit** [comment]
Oh! I see. thank you!

**Comment by mrniko** [comment]
@handjgit 

You're welcome!
