### ISSUE TITLE
Will map got from redisson need to persist after putting new elements?

### ISSUE THREAD

**Issue by a2232189** [redisson/redisson#1947]
For example, got a map from redisson:

```
 Map map = redisson.getMap("mapName");
map.put("name","obama");
redisson.putMap("mapName"); // does this step needed if I want all servers running the same java project get the new inserted element? 
```

To be clarify, If I run:

```
Map map = redisson.getMap("mapName");
map.put("name","obama");
```
on server 1 without `redisson.putMap("mapName")`, can server 2 get` ("name","obama")` when it do
`Map map = redisson.getMap("mapName");`?

**Comment by mrniko** [comment]
Sure it can

**Comment by a2232189** [comment]
How does it work? Does Redisson use technology like proxy( I am thinking about something like Hibernate)? How could Redisson be aware that  the map has been added elements and then sync the changes to redis?

**Comment by mrniko** [comment]
@a2232189 Yes, it might be considered as proxy. Redisson is a stateless client for Redis. It doesn't store state of map on Java. Each map object function mapped to Redis command or Lua-script which may execute multiply commands atomically.
