### ISSUE TITLE
EXCEPTION when deserializing modified class with FST Codec

### ISSUE THREAD

**Issue by rshibley** [redisson/redisson#1949]
### Actual behavior
When trying to de-serialize a modified class ( add/remove field ) it fails and it throws an exception. 

### Expected behavior
When it cannot deserialize an object, it should ignore the cache as if it did not exist and call the method again and cache the new object...

**Comment by buderjoh** [comment]
Is it the same problem as the following?

RBucket<Aggregate> bucket = redisClientConnection.getRedissonClient().getBucket(searchString);
        bucket.set(aggregate, 10, TimeUnit.MINUTES);

![image](https://user-images.githubusercontent.com/20115146/53716167-4bb77500-3e54-11e9-9428-ef5f98182e67.png)
...
![image](https://user-images.githubusercontent.com/20115146/53716198-6a1d7080-3e54-11e9-9421-fb2e553b365a.png)

or should i create a extra issue for that?

**Comment by mrniko** [comment]
I'm afraid fst codec doesn't expose API for clearing internal cache.

**Comment by mrniko** [comment]
You can try to use JBoss Marshalling codec as alternative.
