### ISSUE TITLE
null exception in RedissonLocalCachedMap.java:741

### ISSUE THREAD

**Issue by gmailisgone** [redisson/redisson#1953]
### Expected behavior
no exception in readAllMap

### Actual behavior
NullPointerException happened in 

### Steps to reproduce or test case
run the attached code "RedissonNullException.zip"

### Redis version
Redis server v=4.0.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=9d70bbb410c08012

### Redisson version
3.10.3

### Redisson configuration
        Config redissonConfig = new Config();
        redissonConfig.useSingleServer()
            .setTimeout(1000000)
            .setAddress("redis://192.168.1.123:6379")
            .setDatabase(10)
            .setPassword("123")
            .setConnectionPoolSize(10)
            .setConnectionMinimumIdleSize(2);
        redissonConfig.setCodec(new FstCodec());
        redissonConfig.setLockWatchdogTimeout(5000);
        
        RedissonClient client = Redisson.create(redissonConfig);
        
        LocalCachedMapOptions options = LocalCachedMapOptions.defaults()
               .evictionPolicy(EvictionPolicy.NONE)
               .cacheSize(0)
               .reconnectionStrategy(ReconnectionStrategy.NONE)
               .syncStrategy(SyncStrategy.UPDATE)
               .evictionPolicy(EvictionPolicy.WEAK)
               .timeToLive(0)
               .maxIdle(0);

### Log file
[nullExceptionLog.txt](https://github.com/redisson/redisson/files/2927340/nullExceptionLog.txt)

[RedissonNullException.zip](https://github.com/redisson/redisson/files/2927318/RedissonNullException.zip)

**Comment by mrniko** [comment]
This bug is reproducible with WEAK strategy only

**Comment by gmailisgone** [comment]
> This bug is reproducible with WEAK eviction policy only

do you mean I should use other EvictionPolicy setting except WEAK? 

when I used 3.7.5 without configuring any evictionPolicy, memory leak also exist. 

Anyway, I will try again without WEAK.

**Comment by gmailisgone** [comment]
![_20190306130916](https://user-images.githubusercontent.com/15872156/53857405-1efc8c80-4011-11e9-95e4-b38731b6d46f.png)

redisson 3.10.3
EvictionPolicy.SOFT

still has memory leak issue

**Comment by mrniko** [comment]
Fixed! Thanks for report
