### ISSUE TITLE
memory leak in getLocalCachedMap, redisson version : 3.10.3

### ISSUE THREAD

**Issue by gmailisgone** [redisson/redisson#1954]
### Expected behavior
no memory leak 

### Actual behavior
memory leak 

### Steps to reproduce or test case
run the attached code 

### Redis version
Redis server v=4.0.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=9d70bbb410c08012

### Redisson version
3.10.3

### Redisson configuration
	    Config redissonConfig = new Config();
        redissonConfig.useSingleServer()
            .setTimeout(1000000)
            .setAddress("redis://192.168.1.123:6379")
            .setDatabase(10)
            .setPassword("123")
            .setConnectionPoolSize(10)
            .setConnectionMinimumIdleSize(2);
        redissonConfig.setCodec(new FstCodec());
        redissonConfig.setLockWatchdogTimeout(5000);

    public static final LocalCachedMapOptions options = LocalCachedMapOptions.defaults()
           .evictionPolicy(EvictionPolicy.NONE)
           .cacheSize(0)
           .reconnectionStrategy(ReconnectionStrategy.NONE)
           .syncStrategy(SyncStrategy.UPDATE)
           .evictionPolicy(EvictionPolicy.WEAK)
           .timeToLive(0)
           .maxIdle(0);

[RedissonMemoryLeakTest.zip](https://github.com/redisson/redisson/files/2927568/RedissonMemoryLeakTest.zip)

**Comment by gmailisgone** [comment]
![2](https://user-images.githubusercontent.com/15872156/53752206-02653500-3ee9-11e9-83e8-56ac661099b5.png)
![3](https://user-images.githubusercontent.com/15872156/53752207-02fdcb80-3ee9-11e9-9c80-c4ba6167bea7.png)
![4](https://user-images.githubusercontent.com/15872156/53752208-03966200-3ee9-11e9-8fc2-e327da746589.png)
![1](https://user-images.githubusercontent.com/15872156/53752209-042ef880-3ee9-11e9-8548-31173fef352c.png)

**Comment by mrniko** [comment]
This issue happens because you create a new RLocalCachedMap instance each iteration. Please use it as a singleton object (per key).

**Comment by gmailisgone** [comment]
you mean i should NOT get the LocalCachedMap more than 1 time even the key ("123") are identical.

>> RLocalCachedMap<String, DDD> cachedMap = client.getLocalCachedMap("123", options);

**Comment by mrniko** [comment]
@gmailisgone 

Yes. Also call `RLocalCachedMap.destroy()` method once object isn't used anymore.

**Comment by gmailisgone** [comment]
>> Yes. Also call RLocalCachedMap.destroy() method once object isn't used anymore.
Got it.  I thought the operation is same as redis command. 

But, what will RLocalCachedMap.destroy() do, 
1. Destory the objects in local JVM? (if this one, it will disappeared if I restart the JAVA program)
2. Destory the objects in redis?

**Comment by mrniko** [comment]
@gmailisgone 

Yes, it will clear local cache, but not the data stored in redis

**Comment by gmailisgone** [comment]
@mrniko 
thanks for your reply. 

There is one more thing i want to confirm, 

1. For getLocalCachedMap, I can get only for 1 time, 
but for other redisson data structures, I can get 

2. Is there any document given information like these?
