### ISSUE TITLE
RedisOutOfMemoryException

### ISSUE THREAD

**Issue by kongwf5813** [redisson/redisson#1955]
### Expected behavior
No errors should be thrown after setting maxmemory-policy :volatile-lru, maxmemory:4MB.

### Actual behavior
When I am using two threads to put values through redisson to different database with limited memory(maxmemory-policy :volatile-lru, maxmemory:4MB),  error like **org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'** sprang up, and the database was flushed by redisson.
But I replaced to use Jedis(2.8.0) to test again, no such exceptions came out, and the database was not flushed by Jedis. The items which exceed 4MB  can be deleted by redis automatically because of volatile-lru policy.

### Steps to reproduce or test case
1. Run commands on redis-cli,  config set maxmemory-policy volatile-lru  config set maxmemory 4mb
2. Run the code twice(Two threads) using different database with type to 0.

### Redis version
3.2.4
### Redisson version
3.10.3
### Redisson configuration
singleServer, refer to the codes for details.

### Codes I run
```
import org.redisson.Redisson;
import org.redisson.api.RMap;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;

import java.util.UUID;
import java.util.concurrent.TimeUnit;

import redis.clients.jedis.Jedis;

public class RedisExceptionTest {
    public static void test(int type, int database) {
        int index = 0;
        if (type == 1) {
            Jedis jedis = new Jedis("localhost", 6379);
            jedis.select(database);
            do {
                index++;
                try {
                    jedis.setex("Chemical:" + index, 3 * 60, UUID.randomUUID().toString());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } while (true);
        } else {
            Config config = new Config();
            config.useSingleServer().setAddress("redis://localhost:6379").setDatabase(database);
            RedissonClient client = Redisson.create(config);
            do {
                index++;
                try {
                    RMap<String, String> rMap = client.getMap("Chemical:" + index);
                    rMap.put(String.valueOf(index), UUID.randomUUID().toString());
                    rMap.expire(3L, TimeUnit.MINUTES);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } while (true);
        }
    }
    public static void main(String[] args) {
        //First arg 0 means using redisson, Second arg 1 means using database 1.
        //Please run twice of this application by changing different database.
        RedisExceptionTest.test(0, 1);
    }
}
```

**Comment by mrniko** [comment]
Did you try to use StringCodec ?

**Comment by kongwf5813** [comment]
> Did you try to use StringCodec ?
Hi Mrniko，
No.
Can you reproduce it locally?
Many thanks.

**Comment by mrniko** [comment]
With jedis you use setex command. Similar methods for this command in Redisson are follow: `RBucket.set(); RBucket.setAsync(); RBucketReactive.set();`

Please use RBucket instead of RMap.

**Comment by kongwf5813** [comment]
> With jedis you use **setex** command. If you have a look at [commands mapping](https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping) list you'll see that similar Redisson methods for **setex** command are follow: `RBucket.set(); RBucket.setAsync(); RBucketReactive.set();`
> 
> Please use RBucket with StringCodec instead of RMap

I change to below code, but exception still happens. 
```
Config config = new Config();
config.useSingleServer().setAddress("redis://localhost:6379").setDatabase(database);
RedissonClient client = Redisson.create(config);
do {
	index++;
	try {
		RBucket<String> bucket = client.getBucket("Chemical:" + index);
		bucket.set(UUID.randomUUID().toString(),3L, TimeUnit.MINUTES);
	} catch (Exception e) {
		e.printStackTrace();
	}

} while (true);
```
Please keep my code running twice until the RedisOutOfMemoryException came out.
Note: Please constrain the maxmemory as below bold words.
# Memory
used_memory:4194208
used_memory_human:4.00M
used_memory_rss:7413760
used_memory_rss_human:7.07M
used_memory_peak:4194280
used_memory_peak_human:4.00M
total_system_memory:2076426240
total_system_memory_human:1.93G
used_memory_lua:37888
used_memory_lua_human:37.00K
**maxmemory:4194304
maxmemory_human:4.00M
maxmemory_policy:volatile-lru**
mem_fragmentation_ratio:1.77
mem_allocator:jemalloc-4.0.3

**This should be a terrible bug.**

**Comment by mrniko** [comment]
@kongwf5813 please use StringCodec, since you don't use json codec with jedis.

**Comment by kongwf5813** [comment]
I did you said as below codes, but still can see the errors are keeping throwing out. 
```
Config config = new Config();
config.useSingleServer().setAddress("redis://localhost:6379").setDatabase(database);
RedissonClient client = Redisson.create(config);
do {
	index++;
	try {
		RBucket<String> bucket = client.getBucket("Chemical:" + index, new StringCodec("utf-8"));
		bucket.set(UUID.randomUUID().toString(),3L, TimeUnit.MINUTES);
	} catch (Exception e) {
		e.printStackTrace();
	}

} while (true);
```

See the stacklog as below:
org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'.. channel: [id: 0xe31f6c16, L:/127.0.0.1:61770 - R:localhost/127.0.0.1:6379] data: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3e37d43e(incomplete)], command=(PSETEX), params=[Chemical:15832, 180000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 36, cap: 256)], codec=org.redisson.client.codec.StringCodec]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:348)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:201)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:143)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
@kongwf5813 

With Jedis I'm getting follow error:

`redis.clients.jedis.exceptions.JedisDataException: OOM command not allowed when used memory > 'maxmemory'.`

Running your test code:

```java
        Jedis jedis = new Jedis("localhost", 6379);
        jedis.select(0);
        int index = 0;
        do {
            index++;
            try {
                jedis.setex("Chemical:" + index, 3 * 60, UUID.randomUUID().toString());
            } catch (Exception e) {
                e.printStackTrace();
            }
        } while (true);
```

**Comment by kongwf5813** [comment]
@mrniko 
I guess you havn't config the maxmemory_policy to volatile-lru. Increase the memory is not a good way especially on online sever. It has a limition of server memory. But Redis itself provides the maxmemory_policy to discard LRU keys. 
Can you type the info memory on redis-cli to get the memory of your redis back?

**Comment by mrniko** [comment]
@kongwf5813 

With maxmemory_policy = volatile-lru I'm unable to reproduce the issue.
My redis conf: [redis.conf.zip](https://github.com/redisson/redisson/files/2945524/redis.conf.zip)

Test code is follow:
```java
    @Test
    public void test() {
        Config config = new Config();
        config.useSingleServer().setAddress("redis://localhost:6379").setDatabase(0);
        RedissonClient client = Redisson.create(config);
        int index = 0;
        do {
            index++;
            try {
                RBucket<String> bucket = client.getBucket("Chemical:" + index, new StringCodec("utf-8"));
                bucket.set(UUID.randomUUID().toString(),3L, TimeUnit.MINUTES);
            } catch (Exception e) {
                e.printStackTrace();
            }

        } while (true);
    }
```

**Comment by kongwf5813** [comment]
@mrniko 
Before reproducing the issue, need run the method twice at the same time. So I changed the code a little bit.  And you will find RedisOutOfMemoryException after MasterConnectionPool connections initialized in Junit console.
Way to run : run testRedissonToDatabaseOne first, and then run testRedissonToDatabaseTwo. And need to run testRedissonToDatabaseOne and testRedissonToDatabaseTwo at the same time.
    @Test
    public void testRedissonToDatabaseOne() {
        Config config = new Config();
        config.useSingleServer().setAddress("redis://localhost:6379").setDatabase(1);
        RedissonClient client = Redisson.create(config);
        int index = 0;
        do {
            index++;
            try {
                RBucket<String> bucket = client.getBucket("Chemical:" + index, new StringCodec("utf-8"));
                bucket.set(UUID.randomUUID().toString(), 3L, TimeUnit.MINUTES);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } while (true);
    }

    @Test
    public void testRedissonToDatabaseTwo() {
        Config config = new Config();
        config.useSingleServer().setAddress("redis://localhost:6379").setDatabase(2);
        RedissonClient client = Redisson.create(config);
        int index = 0;
        do {
            index++;
            try {
                RBucket<String> bucket = client.getBucket("Chemical:" + index, new StringCodec("utf-8"));
                bucket.set(UUID.randomUUID().toString(), 3L, TimeUnit.MINUTES);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } while (true);
    }

**Comment by mrniko** [comment]
@kongwf5813 

I thought you'd like to compare clients. What is the point to run both tests using different clients at the same time?

**Comment by kongwf5813** [comment]
@mrniko 
Can't we use different Redisson clients to put items on  the same redis? If not, why Jedis can do such thing.
Our scenario is that we are using redis on production environment,  two more Spring-boot appliations are connected to different databases in the same redis.  The case is that we writes different items in that redis at same time through Redisson client. Even we configured maxmemory policy on expired items,  Redisson always threw RedisOutOfMemoryException.  But from the previous testing, Jedis never threw such exception, and newly added items  can be seen on redis-cli.

**Comment by mrniko** [comment]
@kongwf5813 

Yes you can use different Redisson clients.
I can't reproduce the issue with test you provided:
https://github.com/redisson/redisson/issues/1955#issuecomment-470892372

Could you provide your current test you use?

**Comment by mrniko** [comment]
@kongwf5813 

I managed to reproduce the issue. Jedis uses single channel, so you need to set same settings to Redisson by follow code:

`config.useSingleServer().setConnectionMinimumIdleSize(1).setConnectionPoolSize(1).setAddress("redis://localhost:6379")`

**Comment by kongwf5813** [comment]
@mrniko 
Thank you very much.
I constrainted connectionMinimumIdleSize to 25, the problem was gone by  using below code
```
config.useSingleServer().setConnectionMinimumIdleSize(25).setAddress("redis://localhost:6379")
```
But when I inscrease to more than 25, the issue came out. Decrease below 25, no errors any more. 
The default connectionMinimumIdleSize is 32, that's why this issue happens. 
But I just used one connection which was not in idle status,   I am curious about the root cause, why this parameter cause the items put flushed and RedisOutOfMemoryException was thrown. .

**Comment by jackygurui** [comment]
This is because the memory used for client buffers allocated from data memory space in Redis. This is not an issue with Redisson.

**Comment by mrniko** [comment]
@can-can 

You can use `RMapCache.setMaxSize()` method to limit entries amount

**Comment by can-can** [comment]
Thank you for your response Koksharov.

It's proved to work but we have to expire the current overwhelmed Map
before it works.
