### ISSUE TITLE
Redisson Map Cache Event Notification doesn't work with HPE's NONSTOP OS

### ISSUE THREAD

**Issue by manubusupalli** [redisson/redisson#1956]
Redisson Map Cache Event Notification doesn't work with HPE's NONSTOP OS.
This is because of the endianness.
Below logic is there in MapCacheEventCodec.decode(ByteBuf buf, State state, Decoder<?> decoder) method, 
if (isWindows) {
            keyLen = buf.readIntLE();
        } else {
        	keyLen = (int) buf.readLongLE();
        }

Here, if it is windows, buf.readIntLE() is used, or else buf.readLongLE() is used. But for HPE's NONSTOP OS, buf.readLong() has to be used.

To fix this, two classes has to be modified, 

1. **RedissonMapCache** - Like how isWindows is being set using "Windows" substring, isNonstop boolean also can be initialized using "NONSTOP" substring
if (isNonstop == null) {
            RFuture<Map<String, String>> serverFuture = commandExecutor.readAsync((String)null, StringCodec.INSTANCE, RedisCommands.INFO_SERVER);
            serverFuture.syncUninterruptibly();
            String os = serverFuture.getNow().get("os");
            isNonstop = os.contains("NONSTOP");
        }
Also, while initializing MapCacheEventCodec, need to pass isNonstop boolean.
new MapCacheEventCodec(codec, isWindows, isNonstop) - in all the 4 places

2. **MapCacheEventCodec** - Need to declare isNonstop boolean and initialize(in constructor) based on the isNonstop boolean that is received from ReidssonMapCache

Also, in the decode method, like how isWindows is being checked, need to check isNonstop and use buf.readLong() if it is NONSTOP as given below.
if (isWindows) {
            keyLen = buf.readIntLE();
        }else if (isNonstop) {
            keyLen = buf.readLong();
        } else {
        	keyLen = (int) buf.readLongLE();
        }

Could you please fix this in Redisson code?

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by manubusupalli** [comment]
Thanks for accepting this request.

Everything is proper in the fixed version(3.10.4), except that in MapCacheEventCode, Windows check is placed instead of NONSTOP check.

Below is the code for your reference,

if (osType == OSType.WINDOWS) {
            keyLen = buf.readIntLE();
        } else if (osType == OSType.WINDOWS) {
            keyLen = (int) buf.readLong();
        } else {
            keyLen = (int) buf.readLongLE();
        }

Please change that check to HPNONSTOP. Revised code is given below.

if (osType == OSType.WINDOWS) {
            keyLen = buf.readIntLE();
        } else if (osType == OSType.HPNONSTOP) {
            keyLen = (int) buf.readLong();
        } else {
            keyLen = (int) buf.readLongLE();
        }

**Comment by mrniko** [comment]
Sorry, my mistake. Fixed

**Comment by manubusupalli** [comment]
No Problem. Thanks.
