### ISSUE TITLE
AWS ElastiCache Redis Cluster & Redisson - OOM

### ISSUE THREAD

**Issue by kschroiff** [redisson/redisson#1968]
We are currently facing some issues with ElastiCache/Redisson without being able to determine the root cause so far - thus I'm giving it a try here ...

We've set up ElastiCache in cluster-mode (3 Nodes) - and configured Redisson correspondingly. 
We are using distributed locks and some RMapCaches. The caches have a max-size (thus LRU-eviction) and TTLs set for both lock as well the cache entries.

During the last few months we ran into a couple of out-of-memory-related outages - that is Redis runs OOM, not the client.

The memory consumption is usually staying constant (limited by the LRU policy and TTL) for weeks but then tanks out of of the blue.  Per "step", the memory consumption does pretty much double. The "step down" in memory takes 1-2 hours before stabilizing on a lower level.

According to our statistics, the number of keys remains constant - less than 100 of which 15 belong to the caches and the rest being TTLed-locks. The number of keys (entries) per cache is also constant - with either well below the size ceiling or the LRU is recognized (=ceiling not exceeded).

I'm wondering whether somebody has seen a similar issue?

With Redisson 3.10, there's a new option to determine the size of an RMap - so we'll use that to investigate further - but I suspect that the size of individual cache entries (which, in theory, could cause this) is not the reason. If we had huge entries, we'd expect to see a recovery after the TTL period, but this is not the case.

Just from gut feeling, it feels as if this is somehow related to a replication - that would at least explain those "steps" to some degree.

### Redis version

4.0.10

### Redisson version

3.9.0

### Redisson configuration

Cluster-mode

**Comment by mrniko** [comment]
I think this is the same issue as https://github.com/redisson/redisson/issues/1941. Could you recheck it with Redisson 3.10.4?
