### ISSUE TITLE
Is it  possible to impor  MultiLock  trylock performance?

### ISSUE THREAD

**Issue by athinboy** [redisson/redisson#1970]
This is a extreme situation, I need get a multilock that contain tens of thousands of locks, It will take several minutes, Is it  possible to impor  MultiLock  trylock performance?

**Comment by mrniko** [comment]
You could use RBitSet in this case. Just consider each bit of it as a separate lock.

**Comment by athinboy** [comment]
Frankly,RBitSet can not meet requirement.

**Comment by mrniko** [comment]
Here is the way https://github.com/redisson/redisson/issues/3122#issuecomment-729493022
