### ISSUE TITLE
Bug: Tomcat with 'updateMode=AFTER_REQUEST' will not remove attributes 

### ISSUE THREAD

**Issue by ivarconr** [redisson/redisson#1971]
Hi all! 

We use Redisson with the tomcat-8 integration. Because this is a legacy application with mutable session objects we have to use `updateMode=AFTER_REQUEST`. 

The problem we faces is that this update mode will not be able to sync removed attrbutes to redis and inform other running tomcat instances. This is bad because our other instances of Tomcat ends up using removed attributes. 

It's actually easy to spot the bug if one inspect [RedissonSession.java#L267-L276](https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java#L267-L276):

```java
    protected void removeAttributeInternal(String name, boolean notify) {
        super.removeAttributeInternal(name, notify);
        
        if (updateMode == UpdateMode.DEFAULT && map != null) {
            map.fastRemove(name);
            if (readMode == ReadMode.MEMORY) {
                topic.publish(new AttributeRemoveMessage(redissonManager.getNodeId(), getId(), name));
            }
        }
    }
```

You can see that `removeAttributeInternal` only does publish the removed attribute if `updateMode=DEFAULT`. This would be fine if Redisson somehow stored which attribute names which was removed so that they also was synced in the [store function](https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java#L312-L323) triggered by  the UpdateValve. 

```java
    public void store(HttpSession session) throws IOException {
        if (session == null) {
            return;
        }
        
        if (updateMode == UpdateMode.AFTER_REQUEST) {
            RedissonSession sess = (RedissonSession) super.findSession(session.getId());
            if (sess != null) {
                sess.save();
            }
        }
    }
```
The problem is that store will only save the current attributes ([see RedissonSession.java#L278-L303](https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java#L278-L303)) on the session, and not the removed attributes. Handling removed attributes will require that Redisson  keeps control of both the added and the removed attributes within one request cycle (the same attribute may be added and removed multiple times). 

#### Solution 1: relax AFTER_REQUEST
I would argue that you actually want all session attributes to be synced as soon as possible. But in the rare scenario where you operate on mutable session data you would do an extra force-update after the request completes. 

The proposal would be to replace AFTER_REQUEST mode with FORCE_UPDATE_AFTER_REQUEST. Then all `addAttrbiute` & `removeAttribute` should be synced as soon as possible, the same way you get with the `DEFUALT` mode today. But in addition you will get **all attributes** synced after the request completes. This would be easy to implement as it will only require removal of the if-guard inside the `removeAttributeInternal` function. 

It could also be beneficial if one is able to specify a white-list of attributes known to be immutable. 

#### Solution 2: Redission keeps track of removed attributes
In this solution Redisson needs to keep track a map of removed attributes during a request cycle and make sure to remove these attributes from redis and notify all other tomcat instances. This will be more complex to implement correctly than solution 1.

**Comment by mrniko** [comment]
Fixed! Thanks for report
