### ISSUE TITLE
RedissonMultiLock should implement RLock interface

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#1973]

**Comment by mrniko** [comment]
Done

**Comment by tobiaskohlbau** [comment]
Hello @mrniko is it inteded that this change removes support for `RLock,isExists` and `lock.remainTimeToLive` by dropping `RExpirable` from the interface? I tried to upgrade from an older redisson version and ran into issues with this function not available anymore. If this is intended is there a best upgrade path to use?

**Comment by mrniko** [comment]
@tobiaskohlbau 

Hi! Yes, it was intended. Please use `isLocked` method in replace of `isExists`. I'll add `remainTimeToLive` method to RLock interface.

**Comment by tobiaskohlbau** [comment]
Thanks for the response. I will wait until `remainTimeToLive` is available and try the upgrade path again.

Thanks for your work on redisson.

**Comment by Frankle97** [comment]
Hello, @mrniko 
I was using the expire method of RLock and came here while searching for its history since expire disappeared during migration to the latest version. Is there any alternative to expire?
