### ISSUE TITLE
High memory consumption in netty theads

### ISSUE THREAD

**Issue by shivendra-kumar** [redisson/redisson#1975]
We are on version 3.7.2 and only using RMap, RScoredSet and are facing the same issue in production where netty threads used by redisson consumed 12GB of total 16GB of allocated heap space in one application and 8GB out of 16 GB on another application . One observation i have made is that netty threads had created around 275,000 thread local maps with each consuming around a fixed amount of heap. It all seems to be related with weblogic context aware classloader because it is shared by all the netty threads.
Since the heap dump is quite large I will be attching the screenshots.
@mrniko setting  -Dio.netty.allocator.useCacheForAllThreads=false had no effects
![netty_memory _leak](https://user-images.githubusercontent.com/38030846/54190189-671c2300-44d9-11e9-9fdc-de9f8570bb8c.png)
![netty1](https://user-images.githubusercontent.com/38030846/54190241-79965c80-44d9-11e9-9669-1ff2726b345c.png)
![netty2](https://user-images.githubusercontent.com/38030846/54190243-79965c80-44d9-11e9-9b6b-45d2c3aba388.png)

**Comment by johnou** [comment]
Update Netty, object cleaner was removed as it caused excessive memory consumption.

**Comment by mrniko** [comment]
@shivendra-kumar 

https://github.com/redisson/redisson/issues/1975#issuecomment-472168816 did it help?

**Comment by shivendra-kumar** [comment]
@mrniko It did help when tested locally. Will let you know once I receive and analyze the new heap dump from production after upgrading redisson and netty

**Comment by akshitjain** [comment]
@shivendra-kumar Did upgrading netty helped?
Are you using the mvn redisson https://mvnrepository.com/artifact/org.redisson/redisson or redisson tomcat redisson-all-3.13.5.jar

Which version of netty heped resolved the problem?

**Comment by mrniko** [comment]
netty 4.1.26+

**Comment by akshitjain** [comment]
Hi @mrniko 
I am using 3.13.1 redisson and am seeing memory issues with Netty
This version has already Netty version greater than 4.1.26. 
Any recommendation

**Comment by mrniko** [comment]
which codec do you use?

**Comment by akshitjain** [comment]
@mrniko JsonJacksonCodec

**Comment by mrniko** [comment]
@akshitjain can you share memory dump?

**Comment by lakshyamittal94** [comment]
clear cache memory to run this
