### ISSUE TITLE
RMapCache eviction fails if process is terminated

### ISSUE THREAD

**Issue by arcosgonzalo** [redisson/redisson#1977]
I am using RMapCache to handle my distributed collections.
When adding to the map, i use:

		map.put("DTO1", dto, 20, TimeUnit.SECONDS);

So the key should expire after 20 seconds. This works, if the process is not terminated before the expiration timestamp. However, if the process dies for any reason, the key never expires.

By observing this behavior, I have concluded that is the Java process that makes the Key expire. I would like Redisson to use Redis EXPIRE behavior for keys, so that the Java process is not responsible for expiring the key.

This way, i will know for sure that the key will expire after the given time, even if for any reason the java process dies.

Is this possible to do with Redisson?

**Comment by mrniko** [comment]
> I have concluded that is the Java process that makes the Key expire

Let me clarify. This process is only applied to entries of RMapCache object. Since Redis doesn't support map entries expiration.

> I would like Redisson to use Redis EXPIRE behavior for keys, so that the Java process is not responsible for expiring the key.

This is how `RObject.expire` method work

**Comment by mrniko** [comment]
If you call RObject.expire method for whole Map object then EXPIRE method is invoked.

**Comment by arcosgonzalo** [comment]
> > I have concluded that is the Java process that makes the Key expire
> 
> Let me clarify. This process is only applied to entries of RMapCache object. Since Redis doesn't support map entries expiration.
> 
> > I would like Redisson to use Redis EXPIRE behavior for keys, so that the Java process is not responsible for expiring the key.
> 
> This is how `RObject.expire` method work.
> 
> If you call RObject.expire method for whole RMapCache object then EXPIRE method is invoked.

Thanks a lot for the quick response.

I understand that Redis does not support individual field expiration, but whole hash expiration. However, the behaviour I expected can be achieved with redis, if a separate Hash in Redis is defined for each Key in the Java Map.

Suppose i have a Map:

Map<int, Customer> customersById;

If the hashes are defined in redis as:

customersById:Customer1
..
..
customersById:CustomerN

Then each customer can be evicted independently.

Is there any drawback in modelling the Map in Redis that way? I see no disadvantage. Has Redisson any data structure that simulates what i described? 

Thanks in advance

**Comment by mrniko** [comment]
This leads to more memory consumption and lack of idleTimeout support.

**Comment by arcosgonzalo** [comment]
> idleTimeout



> > Is there any drawback in modelling the Map in Redis that way?
> 
> This would lead to more memory consumption and lack of idleTimeout support.
> 
> > Has Redisson any data structure that simulates what i described?
> 
> Currently it's not available.

You mean more memory consumption due to the overhead of additional entries?

What do you mean by IdleTimeout support? Is it the time that an entry stays in the near cache before being removed? I understand that if I implement the map the way I want I will not have that feature, but i wanted to know if it is that feature you are talking about.

Would redisson be interested in a data structure that has the implementation i described? To know if I do it as a separate project or I prepare a pull request for this change.

Thanks

**Comment by jackygurui** [comment]
MapCache is designed to provide expiration of individual elements. 

The use case you have described (hash within a hash) is classed as nested structures which is already supported by Redisson. 

In addition to nessting standard Redisson objects, you can declare your own custom POJO as Live Object and you can achieve the same behaviour.

**Comment by arcosgonzalo** [comment]
> MapCache is designed to provide expiration of individual elements.
> 
> The use case you have described (hash within a hash) is classed as nested structures which is already supported by Redisson.
> 
> In addition to nessting standard Redisson objects, you can declare your own custom POJO as Live Object and you can achieve the same behaviour.

I did not describe a Hash within a Hash.
What i said is that the RMapCache does exactly what i expect, if the process is not terminated, that is, expire individual elements according to the used TTL.

However, if the process dies before the expiration time, the Key is not removed. I need a solution so that the Key expires even if the process that added it to the map dies, so the logical conclusion is that redis should handle the expiration of said key.

I have no restrictions of the underlying representation of my map in redis, but i NEED this behavior because i cannot afford to let a Key live more time than specified (for security reasons).

Would you mind explaining why is this a Hash within a Hash?

**Comment by jackygurui** [comment]
> the behaviour I expected can be achieved with redis, if a separate Hash in Redis is defined for each Key in the Java Map.

Sorry I might have misunderstood you, this to me sounds like you want a hash in a hash. 

If you are not bothered to store the entire collection of your object in Redis then normal RedissonMap would be good enough. If you are not interested in fetching individual fields of the enclosed object, i.e. always getting all of the fields each time, then you can simply choose the RedissonBucket. 

I hope I understand you correctly this time.

**Comment by arcosgonzalo** [comment]
> > the behaviour I expected can be achieved with redis, if a separate Hash in Redis is defined for each Key in the Java Map.
> 
> Sorry I might have misunderstood you, this to me sounds like you want a hash in a hash.
> 
> If you are not bothered to store the entire collection of your objects in a single Redis structure, then normal RedissonMap would be good enough. If you are not interested in fetching individual fields of the enclosed object, i.e. always getting all of the fields each time, then you can simply choose the RedissonBucket.
> 
> I hope I understand you correctly this time.

Sorry, maybe i was not clear. I understand that my suggestion ends up being a hash in a hash, but it would be a hash with one element in each case. Is just the work around i found to be able to set expiration time of individual keys in the Map, without having to depend on the java process to perform the eviction.

Any other better suggestion is welcomed.

Fetching the entire collection from reddis is not an option, the collection might be huge. RMapCache was perfect for me until i realized that if i kill the process the keys do not expire after its set ttl. I need the keys to expire even if the process dies, which means that it has to be reddis the one expiring the keys of the map.

**Comment by jackygurui** [comment]
I think I understand your requirement, my assumption is based on your example below 
```
Map<int, Customer> customersById;


customersById:Customer1
..
..
customersById:CustomerN

```

My understanding is, you don’t want the entirety of the `customersById` in Java. You don’t want to have the entirety of the `customersById` in one single Redis hash because you don’t want to have a Java process to manage the eviction of individuals. You do have a scheme of retrieving the object through a predefined naming scheme that you don’t have to do a full DB scan to find a particular one. You said a single object could be stored in one field of a hash, indicates you have an object encoding scheme in place. 

Based on those facts, I think the best suitable structure for your case is RedissonBucket.

**Comment by arcosgonzalo** [comment]
thanks a lot for your responses, i close the issue.
