### ISSUE TITLE
CommandAsyncService produces RedisExceptions without a causal exception

### ISSUE THREAD

**Issue by acolomba** [redisson/redisson#1983]
### Expected behavior

```RedisException``` stack traces from ```CommandAsyncService``` should contain a causal exception wrapped inside a Redis exception. At least that's what I would expect from this code in CommandAsyncService:

```
    public <V> V get(RFuture<V> future) {
...
        if (future.isSuccess()) {
            return future.getNow();
        }

        throw convertException(future);
    }
...
    public <V> RedisException convertException(RFuture<V> future) {
        return future.cause() instanceof RedisException
                ? (RedisException) future.cause()
                : new RedisException("Unexpected exception while processing command", future.cause());
    }
```

### Actual behavior

I'm seeing a small number of sporadic ```RedisException``` stack traces without any causal information. This is all there is:

```
org.redisson.client.RedisException: Unexpected exception while processing command
    at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:414)
    at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:211)
    at org.redisson.RedissonKeys.deleteByPattern(RedissonKeys.java:207)
    <my stack trace leading up to a redisson operation>
    <netflix hystrix stack trace> 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

Looking at the redisson code, I can't quite see how we would end up with an unsuccessful future without an exception.

* Is the causal exception swallowed somewhere?
* Are there conditions under which the future can fail without an exception?

### Steps to reproduce or test case

No test case unfortunately.

This happens very sporadically, and only under load.

### Redis version

Azure Redis 3.2.7

### Redisson version

3.10.2

### Redisson configuration

Single server.

```
codec=org.redisson.codec.SerializationCodec 
timeout=300
retryAttempts=3
retryInterval=100
pingConnectionInterval=0
keepAlive=true
dnsMonitoringInterval=5000
connectionPoolSize=64
connectionMinimumIdleSize=32
idleConnectionTimeout=10000
```

**Comment by mrniko** [comment]
Is there any conditions to reproduce this issue?

**Comment by acolomba** [comment]
Just load, or perhaps just chance. I see it happen under load, but the system isn't stressed -- it's just performing many millions of Redis operations/day. Out of the millions, about 10 times a day this happens.

**Comment by wuguanyu** [comment]
Our project use redission, We also meet this issue

**Comment by mrniko** [comment]
@wuguanyu Could you share full stacktrace?
