### ISSUE TITLE
Does redisson use of jackson for serialization of a custom class annotates said class with JsonTypeInfo?

### ISSUE THREAD

**Issue by arcosgonzalo** [redisson/redisson#1985]
According to Redissons documentation, it uses Jackson as JSON codec, using the @class field to store the type.

How does redisson set this configuration to jacksons object mapper? The only way i know is to decorate the class with the @JSonTypeInfo annotation, but this means that for every serialization / deserialization of the class, the @class field will and needs to exist.

I have a rest service that receives a json of a custom class without the @class annotation, so i cannot afford jackson to always require the @class field in deserialization.

Will using said custom class in a RBucket cause my custom class to be annotated by JsonTypeInfo, if not, how does redisson manage to set that for some deserializations of a custom class a @class field is required, but for others it is not?

**Comment by mrniko** [comment]
Type stored automatically per object.
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java#L152

So you don't need to annotate with @Class each class. Anyway you could use https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations to annotate your custom classes without modifiying them.

**Comment by arcosgonzalo** [comment]
thanks i understand now.
Closing the issue.
