### ISSUE TITLE
RBucket does not support GetAndSet with a TTL for the set operation

### ISSUE THREAD

**Issue by arcosgonzalo** [redisson/redisson#1986]
I want to do a get and a set simultaneously but the getandset() method of the RBucket does not support setting a ttl for the key.
I have tried to use an RTransaction and obtaining the bucket from the transaction instead of the client, but calling get() on the bucket always returns the value.

Is there any way to perform a get and a set with ttl using the RTransaction for RBucket types?

**Comment by mrniko** [comment]
getAndSet method with TTL support added. Thanks for suggestion.
