### ISSUE TITLE
Where are configured cache settings ?

### ISSUE THREAD

**Issue by tufgupmi** [redisson/redisson#1993]
Hello,

I am using dropwizard. The factory class and redisson.yaml path  is configured in config.yaml in databsase properties

hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

Where should i configure cache settings, in the same file ? From where redisson read this properties ?

hibernate.cache.redisson.[REGION_NAME].eviction.max_entries - max size of cache. Superfluous entries in Redis are evicted using LRU algorithm. 0 value means unbounded cache. Default value: 0

hibernate.cache.redisson.[REGION_NAME].expiration.time_to_live - time to live per cache entry in Redis. Defined in milliseconds. 0 value means this setting doesn't affect expiration. Default value: 0

hibernate.cache.redisson.[REGION_NAME].expiration.max_idle_time - max idle time per cache entry in Redis. Defined in milliseconds. 0 value means this setting doesn't affect expiration. Default value: 0

Thank you

**Comment by mrniko** [comment]
Hi,

> Where should i configure cache settings, in the same file ? From where redisson read this properties ?

Redisson reads these properties from hibernate settings. Same way as EhCache do. Please define them in the same place where `hibernate.cache.region.factory_class` setting is defined.

**Comment by contentfree** [comment]
@mrniko (Commenting on a closed issue instead of opening a new one as the question is related): 

When specifying the TTL in the Hibernate config do we need to include the `region_prefix` in the property name, eg: `hibernate.cache.redisson.[prefix].[region].expiration.time_to_live`?
