### ISSUE TITLE
Redisson 2.15.2 didn't support jdk6

### ISSUE THREAD

**Issue by Ianwu0812** [redisson/redisson#1995]
### Expected behavior
As the document said, Redisson 2.15.2 should support jdk6.
### Actual behavior
Redisson 2.15.2 didn't support jdk6
### Steps to reproduce or test case
Run Redisson 2.15.2 in jdk6
### Redis version
5.0.2
### Redisson version
2.15.2

**Comment by mrniko** [comment]
Sorry, but development of 2.x.x version has been dropped since February.
