### ISSUE TITLE
RoundRobinLoadBalancer not load balance reads

### ISSUE THREAD

**Issue by subash89** [redisson/redisson#1998]
I am using following basic code to point to elastic cache configuration endpoint. (I have also tried adding all 6 node addresses, but no change of behavior).
I have an elastic cache cluster with, 3 shards (2 nodes each, 1 replica)

When I just put 10,000 to a cache, and later read them, in cloud watch I can see cache hits coming only from one node(first node). But cache size in bytes in each node shows each node keeps replicas of the data set. I would like to distribute the reddison read requests among read replicas. 

Config config = new Config();
config.useClusterServers().addNodeAddress("rediss://clustercfg.xxx-xxxx.amazonaws.com:6379").setReadMode(ReadMode.MASTER_SLAVE);

Cache put code is simple as follows

client.getMapCache("cache1").put(x+i,   x+i);

And cache get code as follows.

client.getMapCache("cache1").get(x+i)

Redis version: 5.0.3

Redisson version: 3.10.1

**Comment by mrniko** [comment]
In your case object located with name "cache1" at one of 3 shards, so only one replica is used. Redis doesn't support data partitioning so you need to handle it on client side, like Redisson PRO version does. Please refer to the documentation - https://github.com/redisson/redisson/wiki/5.-data-partitioning-(sharding)

**Comment by subash89** [comment]
Thank you very much for prompt response. 
You mean "cache1", which is the cache instance(type of map who holds key/value pairs), is only belongs to a single shard forever(assuming cluster remains healthy) ?

My understanding was, Redis cluster shards will take care of it. (each shard has it's own slot/keyspace range). 

So ideally, when I do 100s of keys cache.put(), those keys should belong to different shards. And when I do cache.get(), on Redis cluster node will redirect the client to correct shard or serve the cache.get operation. I am wrong here?

Can you please explain the role of org.redisson.connection.balancer.RoundRobinLoadBalancer ?

**Comment by mrniko** [comment]
> You mean "cache1", which is the cache instance(type of map who holds key/value pairs), is only belongs to a single shard forever(assuming cluster remains healthy) ?

Yes. 

> My understanding was, Redis cluster shards will take care of it. (each shard has it's own slot/keyspace range).

Redis cluster has 16K shards, but one key uses only one shard. Redis doesn't do partitioning, this logic should be made on client do.

> So ideally, when I do 100s of keys cache.put(), those keys should belong to different shards. And when I do cache.get(), on Redis cluster node will redirect the client to correct shard or serve the cache.get operation. Am I wrong here?

I'm afraid you're misunderstending the conception. Map object is a single object no matter how many entries does it have. You could have 1M entries, but it still remains on single shard. If you want to use multiple shards you need to use multiple keys. 

> Can you please explain the role of org.redisson.connection.balancer.RoundRobinLoadBalancer ?

It comes to play if you have multiple slaves per shard.

**Comment by subash89** [comment]
Thank you very much for clarifying. This clears out many things. Looks like one reddison collection object lives as one object on Redis server side which has its own key("cache1"). 

I am more like looking for direct redis set and get commands interface from Redis. Do you have such API or data structure spans across shards where I can use different keys for each entry?

About the RoundRobinLoadBalancer, you are correct, in my shards, each has one master and one slave. But I am using read mode as MASTER_SLAVE. So it should read from both isnt it?

**Comment by mrniko** [comment]
> I am more like looking for direct redis set and get commands interface from Redis.

`RBucket` object offers such API.

> Do you have such API or data structure spans across shards where I can use different keys for each entry?

Basically Redisson PRO does this transparently and you don't need to manage it by your self.

> So it should read from both isnt it?

Yes, it should. It doesn't?

**Comment by subash89** [comment]
yes it works. Even though we keep a reference of the Map "cache1" Object, every time we do map.get("key1"), redis should get a cache hit for the key "cache1" right?

**Comment by formanojhr** [comment]
> > You mean "cache1", which is the cache instance(type of map who holds key/value pairs), is only belongs to a single shard forever(assuming cluster remains healthy) ?
> 
> Yes.
> 
> > My understanding was, Redis cluster shards will take care of it. (each shard has it's own slot/keyspace range).
> 
> Redis cluster has 16K key slots, but one key uses only one key slot. Redis doesn't do partitioning, this logic should be made on client do. Redisson PRO implements it.
> 
> > So ideally, when I do 100s of keys cache.put(), those keys should belong to different shards. And when I do cache.get(), on Redis cluster node will redirect the client to correct shard or serve the cache.get operation. Am I wrong here?
> 
> I'm afraid you're misunderstending the conception. Map object is a single object no matter how many entries it has. It could have 1M entries, but it still remains on single shard. If you want to use multiple key slots you need to use multiple keys.
> 
> > Can you please explain the role of org.redisson.connection.balancer.RoundRobinLoadBalancer ?
> 
> It comes to play if you have multiple slaves per shard.

@mrniko On this sharding question - since RMap does not allow this capability in free version for balancing across shards a single cache,  would something like using RBucket (for each map entry) allow spreading across the shards ? Thx.

**Comment by mrniko** [comment]
@formanojhr 

> using RBucket (for each map entry) allow spreading across the shards ?

It will work.
