### ISSUE TITLE
Redisson 3.10.4 usage with managedexecutor as external executor service gives lifecycle shutdown method errors.

### ISSUE THREAD

**Issue by neerajaustin** [redisson/redisson#1999]
Upgraded from 3.8.2 to 3.10.4 Redisson community version and started seeing this error as we use Redisson in a Jboss application server with managed executor service.

Does this create any issues with Redis behavior?

The managed executor spec considers this as valid behavior.

### Expected behavior
Should not throw an exception.

### Actual behavior
The new code added in the CommandPubSubDecoder decodeResult to check if executor service is shutdown is throwing an IllegalStateException.
### Steps to reproduce or test case
Please use a managed executor for plugging in an external executor service.
Exception trace:

ERROR [redisson-netty-3-12]  org.redisson.client.handler.CommandPubSubDecoder(:80) - Unable to decode data. channel: [id: 0x29e713ad, L:/127.0.0.1:50436 - R:localhost/127.0.0.1:6379], reply: ReplayingDecoderByteBuf(ridx=70, widx=70) java.lang.IllegalStateException: Lifecycle operation not supported

### Redis version
5.0.2
### Redisson version
3.10.4

**Comment by mrniko** [comment]
Which codec do you use? Please note that default codec has changed since 3.10.0 version

**Comment by neerajaustin** [comment]
I use the FSTCodec. But this is related to the managed executor service throwing an exception as well.

**Comment by mrniko** [comment]
Can you provide test code to reproduce this?

**Comment by neerajaustin** [comment]
I will have to get a war file prepared for you to do this. But basically, a managed executor spec states that any lifecycle methods called on it will throw the exception. If you can provide me an idea of this change that you did, then I can try to create a wrapper around my managed executor and handle it in my application.

**Comment by mrniko** [comment]
@neerajaustin 

There are lot of changes have been made since since 3.8.2. Could you try 3.9.1 version for example? Just to realize from which version error starts to appear.

**Comment by neerajaustin** [comment]
@mrniko The check for executor.isShutDown() was introduced right after 3.8.2. At present, I look for the exception and ignore it as I use the library in a Jboss wildfly/eap env with managed executor service.

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by neerajaustin** [comment]
@mrniko I feel this fix is not a clean one. Just my opinion. If you can have a wrapper executor service implementation (which you probably do), then you could handle this exception there and just return false for the shutdown boolean check and for the rest of the lifecycle methods below that gives the same error. Maybe you dont call any of the other methods but still wanted to mention.

isShutdown(), shutdownNow(), awaitTermination(), shutdown(), isTerminated()

**Comment by mrniko** [comment]
@neerajaustin 

Thanks for your feedback!

shutdownNow, isTerminated - aren't used.
awaitTermination(), shutdown - used only if Redisson uses own executor and not one supplied during configuration.
