### ISSUE TITLE
Question :  Redis (cluster mode enabled) Cluster's Endpoints

### ISSUE THREAD

**Issue by deepshiv126** [redisson/redisson#2000]
Hello, 

Its a Question and _NOT_ an issue

Currently we are using Redisson with our _self-compiled and installed Redis Server_ on an ec2 instance and due to scalability concern, we are moving with AWS ElastiCache Redis Cluster.  Already our application is using Redisson Library, not just as a client, but also our application heavily using acquire Lock and Unlock on any given key using either "RLock" or "RReadWriteLock"

Now, I have aws ElastiCache Redis (cluster mode enabled) Cluster's Endpoints and Node Endpoints - but I am unable to connect to Redis Server; 

I followed this Redisson Configuration [Wiki](https://github.com/redisson/redisson/wiki/2.-Configuration) -  I tried

1. Cluster Mode 
2. Replicated Mode 

Neither configuration was able to connect to Redis Cluster. I can connect to these server using Redis CLI, however with Redisson Library, I am not able to connect. 

Please can someone help me with some sample example with Redisson Config to connect Config/Primary Endpoints. 

Redis version- 5.0.3
Redisson version - 3.10.5

**Comment by mrniko** [comment]
> I can connect to these server using Redis CLI, however with Redisson Library, I am not able to connect

Could there be a problem in the security groups settings?
