### ISSUE TITLE
关于JsonJacksonCodec codec的疑问

### ISSUE THREAD

**Issue by kkrgwbj** [redisson/redisson#2001]
你好，这个能否设置下，如果当前是string的话，就不用走json的序列化，因为如果继续走的话，就会出现多了一对""或者\\转义符

**Comment by jackygurui** [comment]
其实有关“多了一对""或者\转义符”的问题根源不在序列化的时候，而是在反序列化的时候。确实，当你在序列化时，你可以判断它的类型并去掉多余的字符。但是在反序列化这个数据时，由于整条数据不符合JSON格式的规范，绝大多数情况下你根本反序列化不了。

**Comment by kkrgwbj** [comment]
嗯是的，你有什么好的方案吗？

**Comment by jackygurui** [comment]
可以考虑放弃JSON格式，采用StringCodec
