### ISSUE TITLE
redisson client  connect sentinel to Read Data

### ISSUE THREAD

**Issue by handjgit** [redisson/redisson#2002]
I init client like this :
"   Config config = new Config();
            String[] servers = new String[conf.getServers().size()];
            config.useSentinelServers()
                    .addSentinelAddress(conf.getServers().toArray(servers))
                    .setMasterName(conf.getMasterName())
                    .setPassword(conf.getAuth())
                    .setTimeout(conf.getTimeout());
            client = Redisson.create(config); "
But error reporting when I run the program , please see the following exception information:
"org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.MasterSlaveEntry@77cbf622], connection: [id: 0x872874f5, L:/172.21.128.61:59850 - R:192.168.27.23/192.168.27.23:6379], command: (EXISTS)"

The server's IP is the sentry machine's IP，What's the problem?

**Comment by mrniko** [comment]
Try to increase connection pool

**Comment by handjgit** [comment]
From the perspective of exception information(connection: [id: 0x872874f5, L:/172.21.128.61:59850 - R:192.168.27.23/192.168.27.23:6379]), it seems to have been connected,but why did the client send a "EXISTS" command to the sentinel server Instead of a master or slave?

**Comment by mrniko** [comment]
Could you check your Redis sentinel configs? I think sentinel could be defined there as slave or master by mistake.
