### ISSUE TITLE
Map entry listener when application scale(multiple replicas)  for RMapCache

### ISSUE THREAD

**Issue by nitinvavdiya** [redisson/redisson#2004]
My application running with multiple replicas, so each replicate have map entry listener
I am doing some task (database update) on entry expire, so in my case, each replica get notify and each replica executes update query in the database.
Any solution/suggestion to avoid this scenario.

**Comment by mrniko** [comment]
Try to use `RBucket.trySet` method in listener. In this way only one listener could execute the task.
