### ISSUE TITLE
Error deserializing Json with Optionals after version 3.10.1. Object mapper behaves unexpectedly 

### ISSUE THREAD

**Issue by cioboteacristian** [redisson/redisson#2010]
### Expected behavior
Deserializing Jsons that contain Optionals. In buckets or maps, with JsonJacksonCodec or TypedJsonJacksonCodec

### Actual behavior
ObjectMapper does not behave as expected, it does not deserialize Optional even though the provided ObjectMapper has the JDK8Module.

The issue resides in org.redisson.command.CommandAsyncService#getCodec. More specifically: 
org/redisson/command/CommandAsyncService.java:833

codecToUse = codec.getClass().getConstructor(ClassLoader.class, codec.getClass()).newInstance(threadClassLoader, codec);

I've managed to trigger NoSuchMethodException (by providing an anonymous class JsonJacksonCodec() {}) there so that  codecToUse = codec; ObjectMapper works this way.

ObjectMapper is replaced in org.redisson.codec.JsonJacksonCodec#createObjectMapper

### Steps to reproduce or test case
Try to deserialize any object that contains an Optional. 

### Redis version
4.0.2

### Redisson version
3.10.1 onwards

**Comment by mrniko** [comment]
> ObjectMapper is replaced in org.redisson.codec.JsonJacksonCodec#createObjectMapper

I'm afraid you're mistaken. `createObjectMapper` method only sets typeFactory property on supplied ObjectMapper

**Comment by mrniko** [comment]
Could you share code example to reproduce this?

**Comment by cioboteacristian** [comment]
Unfortunately, redisson tests are simply not working on my Mac, but you could simply try to upsert a a value to a bucket/mapcache (extended from the TypedJsonJacksonCodecTest$Simple)
`
public static class SimpleWithOptional {
        
        public final String value;
        public final Optional<String> optionalString;

        public Simple(final String value, final Optional<String> optionalString) {
            this.value = value;
            this.optionalString = optionalString;
        }
`
and try to encode it and decode it, will definitely fail, either because optionalString is null OR optionalString is a String. None of them can be mapped to Optional<String>. This is just a a result of Jdk8Module() not kicking in in the ObjectMapper.

So, I just commented out In JsonJacksonCodec:

`    
protected static ObjectMapper createObjectMapper(ClassLoader classLoader, ObjectMapper om) {
//        TypeFactory tf = TypeFactory.defaultInstance().withClassLoader(classLoader);
//        om.setTypeFactory(tf);
        return om;
 }
`
And now, all my classes containing Optionals are being correctly decoded.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/pull/4728
