### ISSUE TITLE
布隆过滤器修改expectedInsertions初始值后，add旧值返回true

### ISSUE THREAD

**Issue by lujun920** [redisson/redisson#2015]
非常抱歉，英语没达到能够准确描述问题的水平，所以，请允许我用中文。

        使用布隆过滤器的测试过程中，初始化expectedInsertions值为100，已经插入了部分值，当发现不够用扩大到1000，发现add已经add过的值依然返回true。后来看代码expectedInsertions的改变将会对hash计算结果slot位置产生影响，最终导致同一个值在调整expectedInsertions值以后，都会返回true的情况。请问下如果想扩容不影响相同值计算结果的slot，重写hash实现的可行性有多少？

### Expected behavior
        字符串“abc”在expectedInsertions初始值10插入后，在expectedInsertions设置为100后，add结果也返回false

### Actual behavior
        字符串“abc”在expectedInsertions初始值10插入后，在expectedInsertions设置为100后，add结果返回了true

### Steps to reproduce or test case
RBloomFilter<String> bloomFilter = client.getBloomFilter("sample");
        bloomFilter.tryInit(1000L, 0.001);
        System.out.println(bloomFilter.add("Abc"));

### Redis version
        单机版4.0.10

### Redisson version
        redisson 开源版 3.10.5

### Redisson configuration
        cache:
  redis:
    address: redis://127.0.0.1:6379
    password:
    expire-time: 30
    pool-config:
      min-idle: 10
      pool-size: 32
      connect-timeout: 15000
      max-wait-timeout: 10000
      retry-attempts: 3
      retry-interval: 1000

**Comment by jackygurui** [comment]
你这种情况可能需要自己去实现Scaleable Bloom Filter了
