### ISSUE TITLE
 LockWatchdogTimeout不会自动续租

### ISSUE THREAD

**Issue by shuo123** [redisson/redisson#2016]
### Steps to reproduce or test case
       `Config config = new Config();
        config.useSingleServer().setAddress("redis://192.168.9.150:6379");
        RedissonClient client = Redisson.create(config);
        try {
            RLock lock = client.getLock("lock");
            lock.lock();
            try {
                Thread.sleep(1000);
            } finally {
                lock.unlock();
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            client.shutdown();
        }`

redis-cli中ttl如下：
127.0.0.1:6379> ttl lock
(integer) 2
127.0.0.1:6379> ttl lock
(integer) 1
127.0.0.1:6379> ttl lock
(integer) 0
127.0.0.1:6379> ttl lock
(integer) -2
127.0.0.1:6379> ttl lock
(integer) -2

### Redis version
3.0.0
### Redisson version
3.10.5
### Redisson configuration
默认配置

**Comment by mrniko** [comment]
In your case operation between lock / unlock doesn't take more than 2 seconds. LockWatchdogTimeout stops execution once lock get unlocked

**Comment by shuo123** [comment]
This is my fault. Don't need 2s. Only because the sleep is too short, I don't have enough time to ttl.
