### ISSUE TITLE
Fetching data from RMap is slow. 11000 entries in RMap taking total 207mb. Is there  a way to make it fast. Every minute my cache is updated. so,I want to fetch all entries in RMap every minute.

### ISSUE THREAD

**Issue by sagarsitap596** [redisson/redisson#2017]
RMap containing 11000 entries (RMap<String, Map<Integer, Data>>) .Total size 207 mb.
Time taken to retrieve all keys - 8-10 seconds.
My Rmap is getting updated every minute. So i need to get data from RMap every minute

Is there a way to fasten get call.

**Comment by mrniko** [comment]
Try to use SnappyCodec and `RMap.readAllMap` method

**Comment by sagarsitap596** [comment]
I am already using RMap.readAllMap with JsonJacksonCodec (since I have third party classes which doen't implement serializable).
SnappyCodec would need all classes to implement Serializable I guess.

**Comment by mrniko** [comment]
you can supply JsonJacksonCodec to SnappyCodec like this: new SnappyCodec(new JsonJacksonCodec())

**Comment by sagarsitap596** [comment]
Tried with SnappyCodec and RMap.readAllMap but still same performance.

**Comment by mrniko** [comment]
Have you tried to use RLocalCachedMap?

**Comment by sagarsitap596** [comment]
I believe RLocalCachedMap will not fit my use case.
My redis cache is going to get updated every minute and eventually it wlll go around 2 - 2.5 gb of data in redis. And also every minute all entries are getting processed. Also, the architecture is such that my instace is supposed to be stateless (no cache).

Is there any way by which all entries in Rmap is fetched in parallel?

**Comment by mrniko** [comment]
> Is there any way by which all entries in Rmap is fetched in parallel?

I'm afraid no.

RMap.readAllMap returns result in one network call

**Comment by sagarsitap596** [comment]
RMap<String, RMap<Integer, Data>> 
So ,in above nested RMap, RMap.readAllMap  will fetch all nested RMap  in single n/w call right?

if so that means its size of data which is making RMap.readAllMap slow?

**Comment by mrniko** [comment]
> So ,in above nested RMap, RMap.readAllMap will fetch all nested RMap in single n/w call right?

No, in this call Redisson will create RMap object for each map value, but won't fetch them.

**Comment by sagarsitap596** [comment]
RMap<String, RMap<Integer, Data>>
So, whne iterated over all entries of outer RMap and RMap.readAllMap on each inner RMap will be a seperate n/w call?

**Comment by jackygurui** [comment]
@sagarsitap596 How does your inner RMap updated? It feels like you are always fetching the entire inner RMap every single time. If you are updating it in the same way then it is the best not to use the nested RMap and replace is with a simple Map instead. This will reduce the total number of calls to the server side. Additionally, you should be able to use `getAll(Set)` or `getAllAsync(Set)` to do reduce the total number of calls even further. Please be aware the bigger a single fetch is, the longer the delay other client/process will experience.

**Comment by sagarsitap596** [comment]
I just get inner map since I know the key to it while updating. 

I tried with normal inner Map. Still it takes same amount of time to fetch whole data.

**Comment by jackygurui** [comment]
Are you using batched fetch by any chance with `getAll(Set)` or `getAllAsync(Set)`?

**Comment by sagarsitap596** [comment]
Nope. 
I am fetching all the data present in RMap.   RMap.readAllMap

**Comment by jackygurui** [comment]
Physically fetching `RMap<String, RMap<Integer, Data>>` including nested RMap shoud be slower than fetching `RMap<String, Map<Integer, Data>>` If you are saying there is no difference between the two, I think something is not quite right here.

**Comment by sagarsitap596** [comment]
Surprisingly but yes both are taking same time.

I am using RMap<String, RMap<Integer, Data>> because my inner RMap is updated by multipe threads and I dont want data to be overridden.

**Comment by jackygurui** [comment]
Can you show a snipet of your code?

**Comment by sagarsitap596** [comment]
{
            Map<String, Map<Integer, String>> result = new HashMap<>();
            RMap<String, RMap<Integer, String>> rMap = redissonClient.getMap("key");
            Map<String, RMap<Integer, String>> localMap = rMap.readAllMap();
            for (Map.Entry<String, RMap<Integer, String>> entry : localMap.entrySet()) {
                Map<Integer, String> map = new HashMap<>();
                String id = entry.getKey();
                map.putAll(entry.getValue().readAllMap());
                result.put(id, map);
            } 
            return result;
}

**Comment by jackygurui** [comment]
```
{
    Map<String, Map<Integer, String>> result = new HashMap<>();
    RMap<String, RMap<Integer, String>> rMap = redissonClient.getMap("key");
    Map<String, RMap<Integer, String>> localMap = rMap.readAllMap();
    for (Map.Entry<String, RMap<Integer, String>> entry : localMap.entrySet()) {
        Map<Integer, String> map = new HashMap<>();
        String id = entry.getKey();
        map.putAll(entry.getValue().readAllMap());
        result.put(id, map);
    }
    return result;
}
```
Have you tried to use RBatch to populate `map.putAll(entry.getValue().readAllMap());`?

**Comment by sagarsitap596** [comment]
Nope. I will try and let you know

**Comment by jackygurui** [comment]
@sagarsitap596 Any update?

**Comment by jackygurui** [comment]
Closed for no further communication.
