### ISSUE TITLE
Tomcat Session Manager issue in Load Balance environment with redMode MEMORY

### ISSUE THREAD

**Issue by WayneAtGC** [redisson/redisson#2020]
We have a 2 instances of tomcat running in front of apache (with sticky session).
We have a single redis instance and we are using the redisson tomcat 8 session manager (setup in the context.xml in the /conf dir). Version redisson-tomcat-8-3.7. Tomcat version 8.0.32.

This is similar to bug #1311 . We have a session timeout of 30mins. 

What is happening:
1) User logs onto instance 1, session created.
2) User uses session on instance 1
3) Apache loadbalancers the request over to instance 2 (perhaps load was too great on instance1)
4) New session created on instance 2 and loaded with session info via redis, user carries on without loosing session. All good so far.
5) 15 mins later user makes another request and apache loadbalancers back to instance 1. User carries on without issue.
6) User keeps using their session on instance 1.
7 ) On instance 2 the session timesout after 30 mins. This then invalidates the session on instance 1 even though the user is still using it and user looses session . This is the problem.

It seems that  in RedissonSessionManager.java -> startInternal() -> onMessage() when receiving a AttributesPutAllMessage is NOT updating the timing on the session (at least in readMode MEMORY)  and then tomcat MangerBase times the session out. I can see session values session:lastAccessedTime and session:thisAccessedTime are sent in the map, however debugging into superSetAttribute() on Tomcat 8 does NOT update these member variables, and therefore the session timesout.

I made a local patch to test my thoery by calling session.superEndAccess() instead:
```
if (msg instanceof AttributesPutAllMessage) {
      AttributesPutAllMessage m = (AttributesPutAllMessage) msg;
                                for (Entry<String, Object> entry : m.getAttrs().entrySet()) {
                                    session.superSetAttribute(entry.getKey(), entry.getValue(), true);
                                    if (entry.getKey().equals("session:lastAccessedTime") ) {
                                    	session.superEndAccess(); // so tomcat doesn't time the session out on this instance
                                    }
                                
                                }
                            }
```

This now works as expected. However I'm not sure this is the best implementation and looking for your guidence/fix. This is consistently reproducable.

Many thanks

Context.xml:
<Manager className="org.redisson.tomcat.RedissonSessionManager" configPath="${catalina.base}/redisson.conf" readMode="MEMORY" updateMode="DEFAULT"/> 

Redisson.conf:
---
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
  pingConnectionInterval: 1000
  keepAlive: true
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Fixed! Thanks for report
