### ISSUE TITLE
asBitSet () 方法为什么不检查null的情况并返回new BitSet呢

### ISSUE THREAD

**Issue by xanderxie** [redisson/redisson#2026]
fromByteArrayReverse方法为什么不检查bytes为null的情况，并返回new BitSet()；
### Expected behavior
if (bytes == null) {
            return new BitSet();
}
### Actual behavior
throw new NullPointerException();
### Redisson version
3.10.5

**Comment by mrniko** [comment]
Fixed! Thanks for report
