### ISSUE TITLE
需要使用大量的Queue怎么处理

### ISSUE THREAD

**Issue by zhou-hao** [redisson/redisson#2028]
业务中可能需要创建大量的队列，测试发现队列数量和`ConnectionPoolSize` 成正比，还有什么其他玩法么。

**Comment by jackygurui** [comment]
队列数量跟`ConnectionPoolSize`没有直接关系。`ConnectionPoolSize`跟并发量有关。

**Comment by zhou-hao** [comment]
BlockQueue会占用连接数的吧？ 如果我要响应式的消费queue，应该怎么用。现在用的`RedissonBlockingQueueRx`，

**Comment by jackygurui** [comment]
创建BlockingQueue不会占用连接数，消费的时候才需要。如果条件允许的话，当需要消费多个队列的时候，可以采用`pollFromAnyAsync`来实现。

**Comment by zhou-hao** [comment]
之前用的take，所以queue数量多了后连接数也增多。后来改成通过topic通知再poll queue和和定时poll()的方式。
