### ISSUE TITLE
WARNING: Illegal reflective access by org.redisson.misc.URIBuilder 

### ISSUE THREAD

**Issue by makarid** [redisson/redisson#2029]
Hello, i have just migrate my project from Java 8 to Java 11 and i have encounter the following warning message when i am loading a redissonClient:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.redisson.misc.URIBuilder (USERFOLDER/.m2/repository/org/redisson/redisson/3.10.5/redisson-3.10.5.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.redisson.misc.URIBuilder
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I am using Intellij IDEA 2019.1 (Community Edition), Java 11, Redisson-3.10.5, on Windows 10 and Ubuntu 18.04. 

Does anyone has the same issue? Thanks

**Comment by fgiannetti** [comment]
Same here

**Comment by agrantdeakin** [comment]
This is a concerning issue that should get some attention.

**Comment by mrniko** [comment]
Fixed
