### ISSUE TITLE
[Promotion] scan get results in an unperdictable order  on redis-cluster mode

### ISSUE THREAD

**Issue by cyq89051127** [redisson/redisson#2036]
### Expected behavior
In  Redis cluster mode, when we use scan to get the keys with in a pattern mode like (test_key*), we want to get the results in a certain order.
### Actual behavior
In  Redis cluster mode, when we use scan to get the keys with in a pattern mode like (test_key*), in on redis instance, we can get the keys in order, bug in different nodes, the order is random.
### Steps to reproduce or test case
1: a redis cluter with 2 master and 2 slave
2 put kv like :
     test_key -> testvalue
     test_key1 -> testvalue1
     test_key2  -> testvalue2
3 : we scan the keys with test_key* in the following way 
         keys = redissonClient.getKeys().getKeysByPattern("test_key*",100);
            iter = keys.iterator();
            i=1;
            while (iter.hasNext()) {
                Object o = iter.next();
                System.out.println( (i++) +") "+o.toString());
            }
     Some times we get the reuslt : 
      1) test_key2
      2) test_key1
        3) test_key

   while some times ,we get the result : 
      1) test_key1
      2) test_key
      3) test_key2
### Redis version
4.0.2

### Redisson version
3.10.5

### Redisson configuration
default;

**Comment by cyq89051127** [comment]
The reason is when we scan the result with a  redisson client, it use a compositeIterator which contains a list of iterators(one of each could help to scan on a redis server) ,  but the order is random. Because it comes from 'commandExecutor.getConnectionManager().getEntrySet()' which is a map of Map<RedisClient, MasterSlaveEntry>, the key 'RedisClient' doesn't have its own method of hashcode, and it use a hashcode method of Object. And in this way , the order of Redisclient is random.

An override of hashcode could help us get an ordered Map. Then when we scan with a pattern, we could get an ordered result.

I could provide a PR for this promotion.

**Comment by mrniko** [comment]
Thanks for you feedback.

Basically it doesn't depend on hashCode number. We know that even unimplemented hashCode works correctly and unique per instance. The problem is that HashMap doesn't store keys in sorted form.

**Comment by cyq89051127** [comment]
Yeah,  i see. A hash Code would not make the scan result in a perfect order. But it's also  of meaning.  If we have three redisclient instance, like (redisclient1,redisclient2,redisclient3). The map (Map<RedisClient, MasterSlaveEntry>)  will have a relative order : 

 when we  do a scan, we'may use redisclient in an oder :  redisclient3 ->  redisclient1 -> redisclient2.   
when we do a scan next time, we also will use  redisclient in the same order :  redisclient3 ->  redisclient1 -> redisclient2.

In this way, for the view of a user, we get the same scan result and it looks in order.

**Comment by cyq89051127** [comment]
https://github.com/redisson/redisson/pull/2090
