### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/type/WritableTypeId

### ISSUE THREAD

**Issue by bowen-yangxiansen** [redisson/redisson#2039]
In springboot 2.1.4 
the jackson-core version is 2.8.7
How can I resolve this version conflict?
I tried to filter the jackson-core in spring json, but it didn't work.
    \- org.redisson:redisson-spring-data-21:jar:3.10.6:compile
       \- org.redisson:redisson:jar:3.10.6:compile
          +- de.ruedigermoeller:fst:jar:2.29:provided (version managed from 2.57; scope managed from compile)
          |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.8.7:compile - version managed from 2.9.8; scope updated from provided; omitted for duplicate)
          +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
          |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.8.7:compile - version managed from 2.9.8; omitted for duplicate)
          \- com.fasterxml.jackson.core:jackson-core:jar:2.8.7:compile

**Comment by mrniko** [comment]
did you try to exclude Redisson's  `com.fasterxml.jackson.core` dependencies?

**Comment by bowen-yangxiansen** [comment]
@mrniko yes i try it，but the problem is that redisson needs a jackson version of 2.9.0 or higher. when i  dependency jackson-core 2.9.8 ，it didn't work. jackson-core's version is still 2.8.7.

**Comment by bowen-yangxiansen** [comment]
@mrniko i

**Comment by mimarko** [comment]
Hi @bowen-yangxiansen, I have similar problem, did you resolve it ?
