### ISSUE TITLE
Redisson RedisCluster trylock 失败

### ISSUE THREAD

**Issue by maskxyz** [redisson/redisson#2049]
通过RedissonClient tryLock RedisCluster 时，如果停止两台Master，在Slave节点升级成Master节点后，后续仍会一直出现加锁失败的情况且不恢复，失败概率大概在2%。

### Steps to reproduce or test case

RLock lock = redissonClient.getLock('lock:'+NO);
bolean lockState = false;
try {
    lockState = lock.tryLock(1, 5, TimeUnit.SECONDS);
    if (lockState) {
        ......
    } else {
        throw new LockException();
    }
} finally {
    if (lockState) {
        if (lockState) {
             lock.unlock();
        }
    }
}

先停止一台Master节点，对应Slave升级成Master节点后，再停止另一台Master，等待对应Slave升级成Master。
继续发送请求，出现部分交易加锁失败的情况，且无法自动恢复(等待2小时)。
重启服务后能恢复。

### Redis version
未知
RedisCluster 3-Master 3-Slave

### Redisson version
3.10.2

### Redisson configuration
Config config = new Config();
ClusterServersConfig clusterConfig = Config.useClusterServers()
clusterConfig.setScanInterval(2000)
clusterConfig.setMasterConnectionPoolSize(150)
clusterConfig.setMasterConnectionMinimumIdleSize(10)
clusterConfig.setSlaveConnectionPoolSize(150)
clusterConfig.setSlaveConnectionMinimumIdleSize(10)
clusterConfig.setConnectionTimeout(2000)
clusterConfig.setTimeout(3000)
clusterConfig.setPassword(...)
for (String clusterNode: clusterNodes) {
    clusterConfig.addNodeAddress("redis://"+clusterNode);
}

**Comment by aawu** [comment]
你可以试试升级到3.10.5，之前redis断网，redisson就出现死锁的问题，是3.10.5修复的。

**Comment by mrniko** [comment]
Fixed in 3.10.5
