### ISSUE TITLE
about helm redis-ha deploy 

### ISSUE THREAD

**Issue by wanghws** [redisson/redisson#2050]
i deploy [https://github.com/helm/charts/tree/master/stable/redis-ha](url) to kubernetes use helm. default values.yaml.
> helm ls
> redis-ha-test         	1       	Wed Apr 17 19:11:04 2019	DEPLOYED	redis-ha-3.3.4           	5.0.3      	test

> redis-ha-test-server-0   2/2     Running   0          39h
> redis-ha-test-server-1   2/2     Running   0          39h
> redis-ha-test-server-2   2/2     Running   2          39h

Redisson Sentinel mode Config:

> ---
> sentinelServersConfig:
>   idleConnectionTimeout: 10000
>   connectTimeout: 10000
>   timeout: 3000
>   retryAttempts: 3
>   retryInterval: 1500
>   failedSlaveReconnectionInterval: 3000
>   failedSlaveCheckInterval: 60000
>   password: null
>   subscriptionsPerConnection: 5
>   clientName: null
>   loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
>   subscriptionConnectionMinimumIdleSize: 1
>   subscriptionConnectionPoolSize: 50
>   slaveConnectionMinimumIdleSize: 32
>   slaveConnectionPoolSize: 64
>   masterConnectionMinimumIdleSize: 32
>   masterConnectionPoolSize: 64
>   readMode: "SLAVE"
>   subscriptionMode: "SLAVE"
>   sentinelAddresses:
>     - "redis://172.21.10.23:26379"
>     - "redis://172.21.4.190:26379"
>     - "redis://172.21.15.162:26379"
>   masterName: "mymaster"
>   database: 0
> threads: 16
> nettyThreads: 32
> codec: !<org.redisson.codec.FstCodec> {}
> transportMode: "NIO"

java client startup error:

At least two sentinels are required

why?

but use Replicated mode it's ok.

**Comment by mrniko** [comment]
> At least two sentinels are required

This is the requirement of Redis specification
