### ISSUE TITLE
redisson以后会支持springboot通过自定义注解实现分布式锁吗？

### ISSUE THREAD

**Issue by subenkun** [redisson/redisson#2051]

**Comment by walkersing** [comment]
你比我想象的还要懒！

**Comment by a5302091** [comment]
你比我楼上的想象还要懒

**Comment by jackygurui** [comment]
@subenkun 能够详细讲讲你的需求吗？

**Comment by subenkun** [comment]
@jackygurui 采用spring支持的注解进行缓存操作，如：
@DistributedLocker(keys = { "#key" }, leaseTime = 2000, waitTime = 5000, lockerPrefix = "addKeyWithLock")
public void setDemo(String key) {
}

**Comment by jackygurui** [comment]
考虑了几种方法，各有各的优势各有各的弊端，

**1. 采用AOP的方式实现的方式**
这种方式的好处是代码内不需要参与分布式锁的控制，AOP适用的范围较为广泛。但是弊端比较明显，1）当有多个AOP影响同一个方法的时候，执行顺序不太好确定。2）不能精确控制分布式锁的开关，重试等逻辑。3）适用范围比较局限，其它的Redisson对象需要其他的方式或注解来实现。

**2. 采用注入方式把需要的Redisson对象以参数的形式注入到`类`或`方法`中**
这种方式的好处是适用几乎所有Redisson对象，使用时可以精确控制每个Redisson对象的操作方式，不受其他AOP的影响。缺点是注入到`方法`的方式适用范围相对小，注入到`类`的方式适用范围大。在代码里需要主动操作相关的Redisson对象，比如加锁解锁这类操作。

用第二个方式实现了，正在自己用，如果第一种方式需求大可能会考虑换一种或两种方式。

**Comment by subenkun** [comment]
@jackygurui 个人喜欢aop的方式

**Comment by jackygurui** [comment]
对AOP执行顺序上有什么好的建议吗？

**Comment by jinshubao** [comment]
注解可能更受欢迎，一般使用分布式锁的场景就是想把方法变串行，在事务开始前锁定，执行完事务解锁。

一个注解，虽然粗暴但是简单好用

**Comment by vergilyn** [comment]
赞成。
如 subenkun 示例，如果是简单的场景，通过annotation将会变得很方便和简洁。
（当然可以自己扩展，例如AOP。但不说重复造轮子，技术不过硬可能引发一些问题，所以希望默认支持 😀）
