### ISSUE TITLE
Redis Cache Read Latency Increase with Time

### ISSUE THREAD

**Issue by turbocv** [redisson/redisson#2054]
We are using ElastiCache Redis (version 5.0.3) as our cache server and Redisson 3.8 as our client.

Here are the write and read code.

Write
RBatch batch = redissonClient.createBatch(BatchOptions.defaults());
batch.getMapCache(key).putIfAbsentAsync(itemKey, itemValue, ttlValue, timeUnit);
batch.execute();

Read
RMapCache<ItemKeyType, ItemValueType> relatedVideosMap = redissonClient.getMapCache(key); 

We find that with time on, the cache read latency will increase, for example, 
after the deployment, in the first 3 days, the latency is almost same, keep 2 to 3 milliseconds.
in the next 3 days, the latency can increase to 20 milliseconds. It will keep increasing.
This latency increase has no relation with traffic.

At the same time, I find that that the redis cluster cache miss provided by AWS (The number of unsuccessful read-only key lookups in the main dictionary. This is derived from keyspace_misses at Redis INFO.) will increase from the very beginning (after the deployment). 

We can do deployment to fix the issue.
After the deployment, the latency and cache miss go to normal.

Please help me to fix the issue.
Thanks.

**Comment by mrniko** [comment]
Could you provide full code for data reading?

In your code you are just getting the RMapCache but don't read it.

**Comment by turbocv** [comment]
@mrniko 
Thanks for your help.
Here is the code for read.
```
public List<String> getFromCache(String key) {
    List<String> stringList = new ArrayList();
    RMapCache<String, List<String>> rMapCache = redissonClient.getMapCache(key);
    if (rMapCache != null && !rMapCache.isEmpty()) {
        if (relatedVideosMap.containsKey(itemKey)) {
            stringList = elatedVideosMap.get(itemKey)    
        }
    }
    return stringList;
}
```

Here is Redisson config.

```
Config config = new Config();
config.setCodec(new JsonJacksonCodec(new ObjectMapper()));
config.setNettyThreads(128)
    .useClusterServers()
    .addNodeAddress(redisUrl)
    .setTimeout(200)
    .setRetryInterval(50)
    .setMasterConnectionPoolSize(128)
    .setSlaveConnectionPoolSize(128)
    .setKeepAlive(true);
RedissonClient redissonClient = Redisson.create(config);
```

**Comment by mrniko** [comment]
Thanks for the information provided. Everything looks fine.

> We find that with time on, the cache read latency will increase, for example,
after the deployment, in the first 3 days, the latency is almost same, keep 2 to 3 milliseconds.
in the next 3 days, the latency can increase to 20 milliseconds. It will keep increasing.

I suppose that the cause could be in memory consumption. Could you get memory dump in that moment and CPU load level?

**Comment by turbocv** [comment]
![Redline,P99Latency](https://user-images.githubusercontent.com/33110813/56569809-901ae380-656e-11e9-9a53-1e63df47ea44.png)
You can find the red line which indicates the P99 latency of cache read

**Comment by turbocv** [comment]
![Screen Shot 2019-04-23 at 2 19 34 AM](https://user-images.githubusercontent.com/33110813/56570029-00296980-656f-11e9-9c8c-d6b75799cad9.png)
Blue means cpu.
Green means memory.

**Comment by turbocv** [comment]
![Screen Shot 2019-04-23 at 2 19 34 AM](https://user-images.githubusercontent.com/33110813/56569932-cce6da80-656e-11e9-8d2d-0fe3af953a16.png)

**Comment by turbocv** [comment]
@mrniko 
I cannot provide memory dump.
Here are our metrics.

**Comment by turbocv** [comment]
I also have one question about RMapCache.
If I have ttl value and unit by using RMapCache.expireasync(), will RMapCache behavior like RMap?

**Comment by mrniko** [comment]
Did you try to profile application during this issue?

> If I have ttl value and unit by using RMapCache.expireasync(), will RMapCache behavior like RMap?

Sorry, I didn't get the question. RMapCache.expireAsync set expiration for whole object. If you're not consider to use ttl or maxidletimeout params per entry then I would recommend to use RMap object instead.

**Comment by turbocv** [comment]
We have already run the system for a long time. 
If I change RMapCache to RMap, then I need to delete the RMapCache entries in Redis and warm cache again.
For RMapCache, the field expire is implemented by EvictionScheduler. 
My question is that the expire of the whole RMapCache (RMapCache.expireasync()) is supported by Redis or Redisson?

**Comment by turbocv** [comment]
I think the high latency is closely related with cache miss. 
![Screen Shot 2019-04-23 at 11 35 27 PM](https://user-images.githubusercontent.com/33110813/56637431-83ef5e80-6620-11e9-96b8-df5e568cf33e.png)

**Comment by mrniko** [comment]
> My question is that the expire of the whole RMapCache (RMapCache.expireasync()) is supported by Redis or Redisson?

RObject.expire method uses Redis expiration approach.

**Comment by turbocv** [comment]
I got the answer, will add it later.

**Comment by dasharbaz** [comment]
What was the resolution @turbocv if you mind?
