### ISSUE TITLE
RListMultimap Listener

### ISSUE THREAD

**Issue by Jemyy-AR** [redisson/redisson#2058]
Hello friends
Actually I'm new at working with Redis and Redisson. I'm going to develop a client server application in which multiple clients send an image(my data type) and a key to a unique server.
So I've selected RListMultimap as my desire data structure. 
Inserting and retrieving data is ok but I need a listener to be fired whenever a new data enters to my RListMultimap.
I've looked for it on the documentations but I haven't found any thing yet.
I'll be thankful if any body helps me.

**Comment by mrniko** [comment]
Done.

https://redisson.org/docs/data-and-services/collections/#listeners_1
