### ISSUE TITLE
connection.sync(RedisCommands.INFO_REPLICATION).get(ROLE_KEY)返回值为空

### ISSUE THREAD

**Issue by rongbo-j** [redisson/redisson#2060]
### Actual behavior
connection.sync(RedisCommands.INFO_REPLICATION).get(ROLE_KEY)返回值为空，报空指针异常
### Steps to reproduce or test case
ReplicatedConnectionManager 构造方法报错
### Redis version
阿里云rds
### Redisson version
3.4.1
### Redisson configuration
 Config config = new Config();
            ReplicatedServersConfig replicatedServersConfig = config.useReplicatedServers();
            replicatedServersConfig.addNodeAddress((String[])this.hosts.toArray(new String[0]));
            replicatedServersConfig.setScanInterval(2000);

**Comment by jackygurui** [comment]
阿里云Redis有自己的VIP，你可以用SingleServerConfig

**Comment by rongbo-j** [comment]
好的 我试一下
