### ISSUE TITLE
Wrong logic for Map in RedissonLiveObjectService:persist method

### ISSUE THREAD

**Issue by liheeng** [redisson/redisson#2061]
In RedissonLiveObjectService class, while copying and persisting map Entities in persist method, the "for" loop just accesses empty Redisson map instead of right map object, it causes no any map entity is copied and persisted into redis.

Class: https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonLiveObjectService.java
Line: #308  , The map instance in line 308 should be replaced with object instance which is created in line 303.
`for (Entry<?, ?> entry : map.entrySet()) {`

**Comment by mrniko** [comment]
Fixed! Thanks for report
