### ISSUE TITLE
Redisson no longer supports auth in sentinel clusters older than Redis 5.0.1

### ISSUE THREAD

**Issue by nand4011** [redisson/redisson#2062]
As of version `3.10.5`, Redisson no longer supports sentinel clusters that have a master password but no sentinel password. The commit 4ee3074dfe4be72557945c851bdaf3581b48f0a3 changed the `MasterSlaveConnectionManager` to set the sentinel and master password to the same thing so if they differ the client will be unable to connect. This breaks any software using Redisson that connects to a sentinel Redis cluster with a password that is older than `5.0.1`, when sentinel auth was added.

A potential solution would be to add a `sentinelPassword` field to the `SentinelServersConfig` class representing the sentinel password and have the existing `password` field only represent the master password. It would change the meaning of the existing password field as well as force the `MasterSlaveConnectionManager` to be aware of the sentinel password, so that fix might require some thought from someone more familiar with the codebase than I am.

### Expected behavior
Redisson should be able to connect to a sentinel cluster with the following configurations:
1. A master password but no sentinel password
2. A sentinel password but no master password
3. Different passwords for the master and sentinels
4. The same password for both the master and sentinels
5. No password for either

Only the last two are currently supported in Redisson. Redis as of version `5.0.1` supports all of them and before version `5.0.1` supports 1 and 5.

### Actual behavior
Attempting to connect to a cluster with a master password but no sentinel password and giving the client the master password results in this error:
`org.redisson.client.RedisConnectionException: At least two sentinels should be defined in Redis configuration! SENTINEL SENTINELS command returns empty result!`
This does not cause an error in `3.10.4`. The same error occurs if the master and sentinel passwords differ and the client is given the master password.

Attempting to connect to a cluster with a sentinel password but no master password and giving the client the sentinel password results in this error:
`org.redisson.client.RedisException: ERR Client sent AUTH, but no password is set. channel: [id: 0xb2a12d21, L:/127.0.0.1:56789 - R:127.0.0.1/127.0.0.1:6380] command: (AUTH), params: (password masked)`
The same error occurs if the master and sentinel passwords differ and the client is given the sentinel password.

### Steps to reproduce or test case
1. Start a redis master/slave cluster with `requirepass` and `masterauth` set to `password`
2. Start 3 sentinels with `auth-pass` set to `password` and either `requirepass` set to `differentpassword` or no `requirepass` set at all.
3. Set the password in the sentinel config to either the master password `password` or, if set, the sentinel password `differentpassword`.
4. Attempt to connect to the Redis cluster.

### Redis version
Tested with Redis `5.0.3`
### Redisson version
Tested with Redisson `3.10.6` and `3.10.4`

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/1332b03ed98bb3aec13db6621386137af395f96f

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1981
