### ISSUE TITLE
Reference leak on timeout of async operations in 3.10.3+

### ISSUE THREAD

**Issue by thewmo** [redisson/redisson#2064]
### Expected behavior

Timeouts of async operations should not produce reference leaks.

### Actual behavior

Timeouts of async operations appear to produce a reference leak, in the form of a listener to the shutdown promise associated with the connection manager.

### Steps to reproduce or test case

Perform async Redisson operation (e.g., BlockingQueue.pollAsync) with a short timeout in a loop (allowing the timout to expire). Observe growth in memory usage over time, and/or inspect with VisualVM or similar.

### Redis version

5.0.3

### Redisson version

3.10.6, issue appears to have been introduced in 3.10.3 in CommandAsyncService.handleBlockingOperations, around line 975. When the AtomicBoolean "skip" flag was introduced, a statement removing the listener from the shutdown promise on timeout was removed. I believe removing the listener would eliminate the leak. Here is a screenshot of visualvm inspecting a heap dump showing the reference chain.

![Screenshot at 2019-04-23 22-05-06](https://user-images.githubusercontent.com/901712/56632000-fce8b900-6614-11e9-87b4-fa3a4de26503.png)

### Redisson configuration

```
val timeout = redisProperties.timeout?.toMillis()?.toInt() ?: 0
config.useSingleServer()
    .setAddress(prefix + redisProperties.getHost() + ":" + redisProperties.getPort())
    .setConnectTimeout(timeout)
    .setDatabase(redisProperties.getDatabase())
    .setPassword(redisProperties.getPassword())
config.codec = FstCodec()
```

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2055
