### ISSUE TITLE
RedisTimeoutException: Unable to get connection / Command execution timeout for command

### ISSUE THREAD

**Issue by DerKlassiker** [redisson/redisson#2069]
I have two types of RedisTimeoutExceptions as below. 

1) 
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), command params: [], Redis client: [addr=redis://10.98.15.87:6379]***\tat org.redisson.client.RedisConnection$2.run(RedisConnection.java:214) [redisson-3.9.1.jar:?]***\tat io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.32.Final.jar:4.1.32.Final]***\tat io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.32.Final.jar:4.1.32.Final]***\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.32.Final.jar:4.1.32.Final]***\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.32.Final.jar:4.1.32.Final]***\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) [netty-transport-4.1.32.Final.jar:4.1.32.Final]***\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]***\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.32.Final.jar:4.1.32.Final]***\tat java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]***\u001b[m org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), command params: [], Redis client: [addr=redis://10.98.15.87:6379]\n\tat org.redisson.client.RedisConnection$2.run(RedisConnection.java:214) [redisson-3.9.1.jar:?]\n\tat io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.32.Final.jar:4.1.32.Final]\n\tat io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.32.Final.jar:4.1.32.Final]\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.32.Final.jar:4.1.32.Final]\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.32.Final.jar:4.1.32.Final]\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) [netty-transport-4.1.32.Final.jar:4.1.32.Final]\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.32.Final.jar:4.1.32.Final]\n\tat java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]\

2)
org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=63, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://10.98.15.87:6379], nodeType=MASTER, firstFail=0]]], command: (PSETEX), command params: [user_0cb1e571-b9af-4af6-9d45-a3895350cb1e_accountSharing_scoringResult, 7776000000, "Ok"] after 3 retry attempts***	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:703) ~[redisson-3.9.1.jar:?]***	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]***	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]***	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]***	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]***[m org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=63, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://10.98.15.87:6379], nodeType=MASTER, firstFail=0]]], command: (PSETEX), command params: [user_0cb1e571-b9af-4af6-9d45-a3895350cb1e_accountSharing_scoringResult, 7776000000, "Ok"] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:703) ~[redisson-3.9.1.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

### Redis version
3.2.10

### Redisson version
3.9.1

### Redisson configuration
Default ClusterServersConfig

Can anyone give me an advice on how to fix this error?

**Comment by mrniko** [comment]
Try to set follow values for `nettyThread` setting: 32, 64, 128

**Comment by mrniko** [comment]
Should be resolved by this fix https://github.com/redisson/redisson/issues/2587
