### ISSUE TITLE
om.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.redisson.codec.FstCodec`, problem: sun/misc/Unsafe

### ISSUE THREAD

**Issue by jikuanyu** [redisson/redisson#2078]
in jboss can't use org.redisson.codec.FstCodec
### Actual behavior
19:53:06,175 ERROR [vcom.youjiao.util.RedissonManager] (ServerService Thread Pool -- 72) com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.redisson.codec.FstCodec`, problem: sun/misc/Unsafe
 at [Source: (String)"{"singleServerConfig":{"idleConnectionTimeout":10000,"pingTimeout":1000,"connectTimeout":10000,"timeout":3000,"retryAttempts":3,"retryInterval":1500,"reconnectionTimeout":3000,"failedAttempts":3,"password":null,"subscriptionsPerConnection":5,"clientName":null,"address":"redis://192.168.163.34:9001","subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"connectionMinimumIdleSize":32,"connectionPoolSize":64,"database":11},"threads":0,"nettyThreads":0,"codec":{"class":"org.r"[truncated 47 chars]; line: 1, column: 524] (through reference chain: org.redisson.config.Config["codec"])
19:53:06,226 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (ServerService Thread Pool -- 72) JBWEB000289: Servlet KsServiceServlet threw load() exception: java.lang.NullPointerException
	at org.redisson.config.Config.<init>(Config.java:100) [redisson-2.15.2.jar:]
	at org.redisson.Redisson.<init>(Redisson.java:119) [redisson-2.15.2.jar:]
	at org.redisson.Redisson.create(Redisson.java:164) [redisson-2.15.2.jar:]
	at vcom.youjiao.util.RedissonManager.<init>(Unknown Source) [classes:]

### Redisson version
redisson-2.15.2
### Redisson configuration
{"singleServerConfig":{"idleConnectionTimeout":10000,"pingTimeout":1000,"connectTimeout":10000,"timeout":3000,"retryAttempts":3,"retryInterval":1500,"reconnectionTimeout":3000,"failedAttempts":3,"password":null,"subscriptionsPerConnection":5,"clientName":null,"address":"redis://192.168.163.34:9001","subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"connectionMinimumIdleSize":32,"connectionPoolSize":64,"database":11},"threads":0,"nettyThreads":0,"codec":{"class":"org.redisson.codec.FstCodec"},"transportMode":"NIO"}

**Comment by mrniko** [comment]
Which JBoss and JDK versions do you use? Use `org.redisson.codec.SerializationCodec` as workaround

**Comment by jikuanyu** [comment]
thank you for your reply. jdk1.7,jboss eap7.1. I use module in jboss for load jar.

**Comment by jikuanyu** [comment]
Use org.redisson.codec.SerializationCodec as workaround is ok.
but why JBoss EAP 6.2.0.GA (AS 7.3.0.Final-redhat-14) can't use other codec? 
module.xml:
<module xmlns="urn:jboss:module:1.1" name="org.redisson">

    <properties>
      
    </properties>

    <resources>
        <resource-root path="redisson-2.15.2.jar"/>
        
	
        <resource-root path="byte-buddy-1.8.22.jar"/>
	     <resource-root path="cache-api-1.0.0.jar"/>
		<resource-root path="fst-2.56.jar"/>
		
		<resource-root path="jackson-annotations-2.9.0.jar"/>
		<resource-root path="jackson-core-2.9.8.jar"/>
		<resource-root path="jackson-databind-2.9.8.jar"/>
		<resource-root path="jackson-dataformat-yaml-2.9.8.jar"/>
		
		<resource-root path="javassist-3.21.0-GA.jar"/>
		
		<resource-root path="jodd-bean-3.7.1.jar"/>
		<resource-root path="jodd-core-3.7.1.jar"/>
		
		<resource-root path="netty-buffer-4.1.33.Final.jar"/>
		<resource-root path="netty-codec-4.1.33.Final.jar"/>
		<resource-root path="netty-codec-dns-4.1.33.Final.jar"/>
		<resource-root path="netty-common-4.1.33.Final.jar"/>
		<resource-root path="netty-handler-4.1.33.Final.jar"/>
		<resource-root path="netty-resolver-4.1.33.Final.jar"/>
		<resource-root path="netty-resolver-dns-4.1.33.Final.jar"/>
		<resource-root path="netty-transport-4.1.33.Final.jar"/>
		
		<resource-root path="objenesis-2.5.1.jar"/>
		<resource-root path="reactive-streams-1.0.2.jar"/>
		
		<resource-root path="reactor-core-2.0.8.RELEASE.jar"/>
		<resource-root path="reactor-stream-2.0.8.RELEASE.jar"/>
		
		<resource-root path="rxjava-2.1.13.jar"/>
		
		<resource-root path="snakeyaml-1.23.jar"/>
		
    </resources>
    <dependencies>
	
        <module name="javax.api" />
        <module name="org.slf4j"/>
        <module name="org.apache.log4j" />
        <module name="org.asm"/> 
    </dependencies>
</module>

**Comment by jikuanyu** [comment]
oh,I found https://developer.jboss.org/thread/203758 ,
https://issues.jboss.org/browse/WFLY-4968?workflowName=GIT+Pull+Request+workflow+&stepId=6
jboss bug.

**Comment by mrniko** [comment]
I see. I'm closing this then.
