### ISSUE TITLE
RedisTimeoutException : Unable to send command! 每个请求都报错

### ISSUE THREAD

**Issue by bgmall** [redisson/redisson#2082]
完整的堆栈

2019-04-28 12:30:39 [pool-6-thread-1] ERROR (RedisService.java:278) - clusterPutByteValue异常,paramName=FIGHTER_ACCOUNT,key=[B@f581ab8

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:0:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:0:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.0.1.16:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@546112941 [redisClient=[addr=redis://10.0.1.16:6379], channel=[id: 0x6387eaf4, L:/10.104.135.249:24836 - R:10.0.1.16/10.0.1.16:6379]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5fd014e8(failure: java.util.concurrent.CancellationException)], command=(EVAL), params=[local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, FIGHTER_ACCOUNT, UnpooledHeapByteBuf(ridx: 0, widx: 16, cap: 16/16), UnpooledHeapByteBuf(ridx: 0, widx: 6259, cap: 6259/6259)], codec=org.redisson.client.codec.ByteArrayCodec], command: (EVAL), command params: [local v = redis.call('hget', KEYS[1], ARGV[1]); redis.call('hset', KEYS[1], ARGV[1], ARGV[2]); retur..., 1, FIGHTER_ACCOUNT, UnpooledHeapByteBuf(ridx: 0, widx: 16, cap: 16/16), UnpooledHeapByteBuf(ridx: 0, widx: 6259, cap: 6259/6259)] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:734)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
	at java.lang.Thread.run(Thread.java:748)

### Redis version
redis 4.0

### Redisson version
redisson 3.10.2

### Redisson configuration
useSingleServer
connectionMininumIdleSize = 1
connectionPoolSize=1
database = 0
subscriptionConnectionMininumIdleSize=1
subscriptionConnectionPoolSize =1
threads=1
nettyThreads=1

1.首先用户名密码没问题，这个其他进程都是正常的
2.出现问题的进程，redisson网络连接状态是正常(netstat查看)，但是任何执行都超时
3.绝对没有出现所谓的高并发，请求量很少
4.关于调大nettyThreads，因为任何执行都没有出现超时，应该不是线程数的问题，感觉就是假死，消息一直发布出去，tcpdump也没有任何流量的痕迹

**Comment by mrniko** [comment]
Please refer to this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by mrniko** [comment]
According to this error you have out of free connections: `freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:0:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:0:queue:0,`

**Comment by bgmall** [comment]
because there is only connectionPoolSize = 1 and subscriptionConnectionPoolSize=1

**Comment by mrniko** [comment]
I suggest you to increase connection pool size

**Comment by bgmall** [comment]
tks, but what's happened for the connection??

**Comment by bgmall** [comment]
very few request, almost nothing

**Comment by mrniko** [comment]
I would say more if you would share code example to reproduce this.

Here is my test code:
```java
        Config config = new Config();
        config.setNettyThreads(1);
        config.useSingleServer()
                .setAddress(RedisRunner.getDefaultRedisServerBindAddressAndPort())
                .setConnectionMinimumIdleSize(1)
                .setConnectionPoolSize(1);

RedissonClient redisson = Redisson.create(config);

RMap<SimpleKey, SimpleValue> map = getMap("simple");
map.put(new SimpleKey("1"), new SimpleValue("2"));
map.put(new SimpleKey("33"), new SimpleValue("44"));
map.put(new SimpleKey("5"), new SimpleValue("6"));

SimpleValue val1 = map.get(new SimpleKey("33"));
Assert.assertEquals("44", val1.getValue());

SimpleValue val2 = map.get(new SimpleKey("5"));
Assert.assertEquals("6", val2.getValue());
```

**Comment by bgmall** [comment]
sorry, i don't know what's happend, can't  reproduce this

**Comment by bgmall** [comment]
> According to this error you have out of free connections: `freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:0:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:0:queue:0,`

when run your test code, freeConnectionsAmount also was 0, so the number can't explication

**Comment by bgmall** [comment]
1. the connection is normal(by netstat)
2. tcpdump can't find any data
3. very few request
4. insight into source code, becasuse channelFuture.writeFuture didn't finish(isDone), so timeout

**Comment by bgmall** [comment]
5. every request was timeout

**Comment by mrniko** [comment]
Try to set `pingConnectionInterval` param to avoid broken channels

**Comment by bgmall** [comment]
tks, i changed config as follows
keepAlive=true
pingConnectionInterval=10000
connectionMinimunIdleSize=1
connectionPoolSize=3
retryInterval=6000
threads = core number
nettyThreads= core number

try again, next update

**Comment by jackygurui** [comment]
@bgmall 最好能够介绍一下你的使用情况或者提供一个重现代码。在Redis的操作里有不少的情形需要用到多个连接，如果硬性将连接池数限制为1，却不能避免占用连接的时候，就会出现这样的问题。

**Comment by bgmall** [comment]
只能是在线上环境重现，目前不知道如何产生的，所以不知道重现方法。我这边的使用情况，主要是与redis建立了2个连接，其中一个负责订阅事件的处理，另外一个负责数据的存取，其中这个存储的数据稍微偏大，不过基本都是10k以下，在实际运行的过程中，出了问题的进程一直都处于假死状态，不知道跟我这个数据的大小是否相关。
        关于占用连接的情况，这个从我这边的应用的访问量来说，是很少的，抢占很少，不是很明白，你说的这个占用的连接，难道不会超时释放吗

**Comment by bgmall** [comment]
> @bgmall 最好能够介绍一下你的使用情况或者提供一个重现代码。在Redis的操作里有不少的情形需要用到多个连接，如果硬性将连接池数限制为1，却不能避免占用连接的时候，就会出现这样的问题。

用到多个连接？？比如我这边有rmap操作存储数据，这个会用到多个连接吗？？

**Comment by bgmall** [comment]
对于同时用到多个连接的情况，这块还真是不太清楚。
在线上的情况，有部分进程是，订阅连接是正常的，但是存储数据的那个连接是否假死状态。当然同时有问题的也存在。

**Comment by jackygurui** [comment]
最终还是跟代码的写法有关，如果能够描述一下调用Redisson的相关代码最好。

**Comment by bgmall** [comment]
> 最终还是跟代码的写法有关，如果能够描述一下调用Redisson的相关代码最好。

好的，这边使用很简单
1.使用的腾讯云集群redis
2.存取数据使用的是getMap putAsync/getAsync，使用的是ByteArrayCodec.INSTANCE
其中存储方法如下：
public void clusterPutByteValue(String mapName, Object key, byte[] value) {
      RMAP<Object, Object> map = clusterRedisss.getMap(mapName, ByteArrayCodec.INSTANCE);
      map.putAsync(key, value).exceptionally(printException);
}
3.订阅使用的是getTopic addListener/publishAsync
其中publish方法如下：
public void clusterPublish(String topicName, Object msg) {
     RTopic topic = clusterRedisson.getTopic(topicName);
     topic.publishAsync(msg).exceptionally(printException)；
}

**Comment by jackygurui** [comment]
这两段代码之间有什么关系吗？这两段代码的并发量有多大？

**Comment by bgmall** [comment]
是这样的，之前存储数据这块是没有hash划分到各个分片上，导致单个redis分片上，最高达到了50qps，流量最高不到2m/s，基本上负载很低了，订阅那个应该是负载到不同的分片上的

**Comment by bgmall** [comment]
补充下， 他们直接没什么关系，业务上也不强关联，就是访问统一集群redis而已

**Comment by jackygurui** [comment]
>是这样的，之前存储数据这块是没有hash划分到各个分片上，导致单个redis分片上，最高达到了50qps，流量最高不到2m/s，基本上负载很低了，订阅那个应该是负载到不同的分片上的

你的意思是之前的代码跟这块不一样？之前没有遇到这样的情况吗？

**Comment by bgmall** [comment]
> > 是这样的，之前存储数据这块是没有hash划分到各个分片上，导致单个redis分片上，最高达到了50qps，流量最高不到2m/s，基本上负载很低了，订阅那个应该是负载到不同的分片上的
> 
> 你的意思是之前的代码跟这块不一样？之前没有遇到这样的情况吗？

不是这个意思，代码还是一样的，我是指我们存储数据这块，线上没有hash分片，本来以为是这个问题，所以做了hash分片，还是一样timeout。

现在的情况是redisson发生这个timeout之后，就没办法正常运行了，除非重起进程

**Comment by bgmall** [comment]
这个代码没有变过，之前在线上正常运行了几天，期间应该是比较少有问题，没有怎么发现，这次更新出去之后，全部爆发了，都是连接是正常的，但是就是发不出消息，一直超时，也看了jstack，没有发现异常，进程的状态也是正常的

**Comment by jackygurui** [comment]
应该是需求大于资源的情况。可以考虑增加连接池，并且如果可能的话，把异步操作换成同步操作也会有帮助。采用fastPut也会有一些帮助。如果异步改成同步的条件不允许，fastPut效果不明显的话，可以考虑Redisson PRO企业版。

**Comment by bgmall** [comment]
fastPut与普通put的主要区别是什么？然后企业版是如何收费的呢：）

**Comment by jackygurui** [comment]
`put`的话会返回旧的值，也就是说先执行`HGET`，然后在执行`HSET`，最后返回`HGET`的结果。相反`fastPut`就只确认写入是否成功，在服务端只会执行一条`HSET`的指令。

有关企业版的信息或申请试用，请访问https://redisson.pro 如果有任何疑问可以联系售前和销售邮箱sales@redisson.pro

**Comment by bgmall** [comment]
好的，谢谢：）

**Comment by jackygurui** [comment]
@bgmall 有什么最新动态吗？

**Comment by bgmall** [comment]
> @bgmall 有什么最新动态吗？

线上目前运行了几天，没有出现问题，只是修改了配置，使用了上面我贴的配置，没有使用fastPut

**Comment by mrniko** [comment]
Good
