### ISSUE TITLE
哨兵模式SentinelServersConfig 的作用的疑问

### ISSUE THREAD

**Issue by tinelion** [redisson/redisson#2092]
初次接触Redisson产生的疑问：哨兵模式、集群 可以在Redis配置文件中配置，这些配置是独立于编程语言的，那么SentinelServersConfig 的作用是什么？SentinelServersConfig 可以取代Redis配置文件？

**Comment by jackygurui** [comment]
Redisson的`SentinelServersConfig`、`ClusterServersConfig`等是用来配置客户端的连接方式。客户端的连接方式需要跟服务端相匹配。

**Comment by tinelion** [comment]
感谢回复！
