### ISSUE TITLE
RedissonConnection的geoRadius方法报错

### ISSUE THREAD

**Issue by lesserPanda** [redisson/redisson#2093]
### Expected behavior
stringRedisTemplate.opsForGeo().radius("location", circle, RedisGeoCommands.GeoRadiusCommandArgs.newGeoRadiusArgs().limit(8).sortAscending().includeDistance().includeCoordinates())
期望返回一定范围内的数据
### Actual behavior
java.lang.IllegalArgumentException: distance is marked @NonNull but is null
### Steps to reproduce or test case
public static void main(String[] args) {
        StringRedisTemplate stringRedisTemplate = new StringRedisTemplate();
        long start = System.currentTimeMillis();
        Point center_point = new Point(116.111, 39.111);
        Point point1 = new Point(116.222, 39.222);
        Point point2 = new Point(116.333, 39.333);
        Point point3 = new Point(116.444, 39.444);
        Map<String, Point> map = new HashMap<>();
        map.put("center_point", center_point);
        map.put("point1", point1);
        map.put("point2", point2);
        map.put("point3", point3);
        // 以坐标形式存入redis
        stringRedisTemplate.opsForGeo().add(Constant.ONE_MINUTE_DATA, map);
        // 以给定坐标点未中心，计算3公里范围内的坐标点
        Distance three = new Distance(300.00, RedisGeoCommands.DistanceUnit.KILOMETERS);
        RedisGeoCommands.GeoRadiusCommandArgs geoRadiusCommandArgs = RedisGeoCommands.GeoRadiusCommandArgs.newGeoRadiusArgs();
        geoRadiusCommandArgs.limit(8).sortAscending().includeDistance().includeCoordinates();
        Circle circle = new Circle(center_point, three);
        GeoResults<RedisGeoCommands.GeoLocation<String>> georesults = stringRedisTemplate.opsForGeo().radius(Constant.ONE_MINUTE_DATA, circle, geoRadiusCommandArgs);
        LOGGER.info("返回坐标点：" + georesults);
    }
### Redis version
5.0
### Redisson version
3.10.6
### Redisson configuration
---
singleServerConfig:
  # address: "redis://redis-server-single-peer:6379"
  # 发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  # 发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  # 最小空闲连接数
  connectionMinimumIdleSize: 32
  # 连接池大小
  connectionPoolSize: 2000
  idleConnectionTimeout: 10000
  connectTimeout: 60000
  database: 1
  password: 123456
  # 重试次数
  retryAttempts: 6
  # DNS监测时间间隔，单位：毫秒
  dnsMonitoringInterval: 5000
  timeout: 60000
threads: 20
nettyThreads: 20

**Comment by mrniko** [comment]
Fixed! Thanks for report
