### ISSUE TITLE
Exception when use RedissonRedLock + RedissonMultiLock

### ISSUE THREAD

**Issue by ezreal-liao** [redisson/redisson#2097]
I'm trying to introduce RedLock algorithm in my project, I have 3 Redis nodes, and I need to lock several keys in each thread. Here is my implementation:

// config1 for node #1, config2 for node #2, config3 for node #3, all of them are using single server.
RedissonClient redission1 = Redisson.create(config1);
RedissonClient redission2 = Redisson.create(config2);
RedissonClient redission3 = Redisson.create(config3);

RLock key11 = redission1.getLock("key1");
RLock key12 = redission1.getLock("key2");
RLock multiLock1 = new RedissonMultiLock(key11, key12);

RLock key21 = redission2.getLock("key1");
RLock key22 = redission2.getLock("key2");
RLock multiLock2 = new RedissonMultiLock(key21, key22);

RLock key31 = redission3.getLock("key1");
RLock key32 = redission3.getLock("key2");
RLock multiLock3 = new RedissonMultiLock(key31, key32);

RLock redLock = new RedissonRedLock(multiLock1, multiLock2, multiLock3);
redLock.tryLock(lockAcquireTimeoutMs, lockExpiryMs, TimeUnit.MILLISECONDS);
### Expected behavior
no exception
### Actual behavior
Got exception with message: ""org.redisson.RedissonMultiLock cannot be cast to org.redisson.RedissonLock""
### Steps to reproduce or test case
the root cause is this code in method tryLock(long waitTime, long leaseTime, TimeUnit unit) of class RedissonMultiLock.java:
RFuture<Boolean> future = ((RedissonLock)rLock).expireAsync(unit.toMillis(leaseTime), TimeUnit.MILLISECONDS);
It trys to cast rLock to RedissonLock, but in my case the rLock is RedissonMultiLock. By this implementation, RedissonMultiLock actually can not group any RLock types but RedissonLock.
### Redisson version
3.10.7

**Comment by jackygurui** [comment]
The RedLock is a subset of multi lock, it is unusual to see them blended together. I can't stop wondering what your intension is to "group" those different locks originated from the same node before used in RedLock? I am asking because in the sense of multi lock the schematics of `(A + B) + (C + D) + (E + F)` isn't the same as `A + B + C + D + E + F`.

**Comment by ezreal-liao** [comment]
Hello jack, it is not (A + B) + (C + D) + (E + F), but (A1 + B1) + (A2 + B2) + (A3 + B3).
Let's say A1, A2, A3 is for key A, but against different nodes. Same for B1, B2, B3.
In my understanding, RedLock used multiple nodes for fault tolerance reason, when the majority of nodes are up, I can acquire the lock successfully. So I acquire the lock for key A against node1, node2 and node3, if I acquired two such as A1 and A2, but A3 result in failure, I can still consider the lock of key A is required.

**Comment by ezreal-liao** [comment]
In my case, I need to acquire the lock of both key A and key B, for fault tolerance reason, i created 3 independt Redis nodes, they are not in a cluster.

**Comment by jackygurui** [comment]
> Hello jack, it is not (A + B) + (C + D) + (E + F), but (A1 + B1) + (A2 + B2) + (A3 + B3).
Let's say A1, A2, A3 is for key A, but against different nodes. Same for B1, B2, B3.

Won't this be two RedLocks, one for A1, A2, A3 and another for B1, B2, B3?

**Comment by ezreal-liao** [comment]
But I need to acquire both key A and B simultaneously, they can't be separated from each other, that's why I use RedissonMultiLock.

**Comment by jackygurui** [comment]
Basically, the As and Bs are two fault tolerant Locks backed by RedLock algrithm. If you want two RedLocks executed in parellel, you can just use the async methods and combine the future.
