### ISSUE TITLE
RedisConnectionException: Not all slots are covered! Only 14044 slots are available

### ISSUE THREAD

**Issue by gauravs140689** [redisson/redisson#2103]
### Expected behavior 
It should work without error.

### Actual behavior
Getting a follwoing error while my application is accessing the redis cluster in aws:

java.lang.RuntimeException: org.redisson.client.RedisConnectionException: Not all slots are covered! Only 14044 slots are available

### Redis version
3.2.10

### Redisson version
3.5.6

**Comment by mrniko** [comment]
Check your cluster configuration it doesn't cover all slots.

**Comment by ryankillory** [comment]
@mrniko,
If I have a cluster with n masters (no failover) and 16384/n slots per master and one of those masters becomes unavailable, how would you advise me to configure Redisson so that it can operate normally on the masters that are still available?

Thank you and apologies if commenting on a closed issue is not the best way to get this question answered.

**Comment by mrniko** [comment]
@ryankillory 

You need to use cluster with at least 3 masters.

**Comment by ryankillory** [comment]
@mrniko,
We have many more than 3 masters in our Redis cluster but are seeing this exception when just one master is unavailable. Should we be adding each master's address to our Redisson config? We are seeing this exception even when the master whose address is in our configuration is available but another master is not.

This can be in issue if we attempt to instantiate a new Redisson client while the cluster isn't fully available. In that case, we'd like to be able to use the client as normal on all available masters.

**Comment by mrniko** [comment]
@ryankillory 

Which exception do you see? ClusterDownException?

**Comment by ryankillory** [comment]
@mrniko 
`RedisConnectionException while refreshing redisson.Not all slots are covered! Only 15872 slots are avaliable. Failed masters according to cluster status: [redis://10.48.211.5:6379]`

Additionally, we're hosting our Redis cluster on Kubernetes, so when a Redis node goes down for an upgrade, it may come back with a new IP (but the same hostname).

**Comment by ryankillory** [comment]
Let's say that I want to instantiate a Redisson instance but the Redis cluster I'm pointing it at has a failed master and some unserved slots. As it is, I think it will fail to instantiate and throw an exception similar to the one I posted above. Ideally, I'd like for Redisson to instantiate cleanly and only throw an exception when it attempts to handle a command operating on one or more of those unserved slots.

Thanks for the help and please let me know if I can clarify my situation further.

**Comment by mrniko** [comment]
> Additionally, we're hosting our Redis cluster on Kubernetes, so when a Redis node goes down for an upgrade, it may come back with a new IP (but the same hostname).

Redisson supports dns monitoring feature for this case.

**Comment by ryankillory** [comment]
Is that feature specific to clusters that implement https://redislabs.com/redis-enterprise-documentation/administering/designing-production/networking/multiple-active-proxy/ ?

Do I have any options in the above scenario if I want to be able to instantiate a Redisson client in cluster mode and perform operations on an incomplete cluster if I'm just using a plain Redis cluster (no proxy)?

Attaching our Redisson cluster config:
`
      clientConfig.setNettyThreads(CLUSTER_NETTY_THREADS);
      ClusterServersConfig clusterServersConfig = clientConfig.useClusterServers();
      clusterServersConfig.addNodeAddress(address);
      clusterServersConfig.setReadMode(ReadMode.MASTER);
      clusterServersConfig.setMasterConnectionPoolSize(MASTER_CONNECTION_POOL_SIZE_CLUSTER);
      clusterServersConfig.setMasterConnectionMinimumIdleSize(MASTER_CONNECTION_MIN_IDLE_SIZE);
      clusterServersConfig.setSlaveConnectionPoolSize(SLAVE_CONNECTION_POOL_SIZE);
      clusterServersConfig.setSlaveConnectionMinimumIdleSize(SLAVE_CONNECTION_MIN_IDLE_SIZE);
      clusterServersConfig.setSubscriptionConnectionPoolSize(SUBSCRIPTION_CONNECTION_POOL_SIZE);
      clusterServersConfig.setSubscriptionConnectionMinimumIdleSize(SUBSCRIPTION_CONNECTION_MIN_DLE_SIZE);
      clusterServersConfig.setClientName(CLIENT_NAME);
`

Thank you!

**Comment by mrniko** [comment]
@ryankillory 

As far as I know such error shouldn't be propagated by RedisLabs nodes as proxy instance hides cluster management logic behind the scene.

Currently Redisson doesn't allow to work with broken Redis cluster during startup.

**Comment by mrniko** [comment]
resolved in #2284
