### ISSUE TITLE
HttpSessionListener#sessionDestoyed isn't invoked (Tomcat 8)

### ISSUE THREAD

**Issue by sibmaks** [redisson/redisson#2104]
### Description
I have two nodes:
* node 1 -> N1
* node 2 -> N2

### Expected behaviour
sessionDestroyed event must be handled by both nodes

### Actual behaviour
sessionDestroyed event handled only by N1

### Steps to reproduce or test case
**WHEN** client log in N1
**THEN** N1 and N2 receive sessionCreated event
**AND** service invalidate session (on N1)
**THEN** sessionDestroyed event handle only N1

### Redis version
Redis server v=3.2.6 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=6135068212e7fc88

### Redisson version
3.10.7

### Redisson configuration
redisson.conf
```json
{
	"singleServerConfig": {
		"idleConnectionTimeout": 10000,
		"pingTimeout": 1000,
		"connectTimeout": 10000,
		"timeout": 3000,
		"retryAttempts": 3,
		"retryInterval": 1500,
		"password": null,
		"subscriptionsPerConnection": 5,
		"clientName": null,
		"address": "redis://some-ip",
		"subscriptionConnectionMinimumIdleSize": 1,
		"subscriptionConnectionPoolSize": 50,
		"connectionMinimumIdleSize": 32,
		"connectionPoolSize": 64,
		"database": 0,
		"dnsMonitoringInterval": 5000
	},
	"threads": 0,
	"nettyThreads": 0,
	"codec": {
		"class": "org.redisson.codec.SerializationCodec"
	},
	"transportMode": "NIO"
}
```

context.xml
```xml
<Manager className="org.redisson.tomcat.RedissonSessionManager"
          configPath="${catalina.base}/conf/redisson.conf" readMode="MEMORY" updateMode="DEFAULT" broadcastSessionEvents="true"/>
```

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by sibmaks** [comment]
@mrniko thanks, we wait for the final version for the check.

**Comment by sibmaks** [comment]
@mrniko hi! We tried to use 3.11.0 version and creation and destroying events got both nodes. But when we tried to invalidate session then the session wasn't removed from redis.

**Comment by sibmaks** [comment]
And it still available by session id

**Comment by sibmaks** [comment]
I looked at your code and as I understood session will be removed only after 1 minute.
I think this is to make the session accessible to other nodes, right?

**Comment by mrniko** [comment]
@sibmaks 

That's correct. This would allow you to have an access to it in HttpSessionListener#sessionDestoyed listener

**Comment by sibmaks** [comment]
@mrniko I rechecked it. And the session wasn't removed from redis after 5 minutes.

**Comment by sibmaks** [comment]
The session was removed only after an hour. I think it's too long

**Comment by sibmaks** [comment]
I found that's the problem. After session invalidate we request the new session:
```java
session.invalidate();
newSession = request.getSession();
```
But we got the old session

**Comment by sibmaks** [comment]
@mrniko
I think that this looks like a bug. Because if I invalidate session on the node then I expect get new a new session. What do you think?

**Comment by JiriFrankCZ** [comment]
I confirm this behaviour. When I invalidate the session, with setup of tomcat session manager same as above, I got the same session, with same attributes. I think, the map with values is populated again from Redis.

**Comment by mrniko** [comment]
@sibmaks 

I confirm this issue.

**Comment by mrniko** [comment]
@sibmaks 

Here is updated version containing fix of the issue. Could you try it and give your feedback?

[redisson-tomcat-8-3.11.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3247841/redisson-tomcat-8-3.11.1-SNAPSHOT.jar.zip)

**Comment by JiriFrankCZ** [comment]
@mrniko 

I tried it and it is not working. Same situation. If i set it without broadcastSessionEvents, it is ok. If set to true then it is not working as expected.

I call:
a) session.getAttribue("abcd") => Object@123 - values - {a: 1, b: 2}
b) session.invalidate();
c) session.getAttributeNames() -> size : 0
**d) session.getAttribue("abcd") => Object@456 - values - {a: 1, b: 2}** but now, it should return null according to my opinion

**Comment by mrniko** [comment]
@JiriFrankCZ 

Did you wait for 60 seconds since session invalidation? 60 is enought time so every HttpSessionListener#sessionDestoyed listener could pickup session and handle it

**Comment by JiriFrankCZ** [comment]
@mrniko 
This is single node run. One tomcat one redis. The sequence of scenario above is executed directly one after other, no wait. There is usecase that, I have something in session, I invalidate it but I have it still in session when i call getAttribute

**Comment by JiriFrankCZ** [comment]
@mrniko 
This is single node run. One tomcat one redis. The sequence of scenario above is executed directly one after other, no wait. There is usecase that, I have something in session, I invalidate it but I have it still in session when i call getAttribute

**Comment by mrniko** [comment]
@JiriFrankCZ 

Thanks for your feedback!

Here is yet another updated version:

[redisson-tomcat-8-3.11.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/3251846/redisson-tomcat-8-3.11.1-SNAPSHOT.jar.zip)

**Comment by JiriFrankCZ** [comment]
On simple setup looks good! :)

**Comment by mrniko** [comment]
@JiriFrankCZ 

Thanks for checking! Fixed
