### ISSUE TITLE
ClusterConnectionManager generate lots of map lead to memory leak/oom

### ISSUE THREAD

**Issue by Roronoa-Zoro** [redisson/redisson#2105]
### Actual behavior
we use redisson as lock, in our test env,  we have 3 master nodes, 3 slave nodes, and we use these jvm arguments.
-Xms512m
-Xmx512m
-Xmn256m
-XX:MetaspaceSize=128m
-XX:MaxMetaspaceSize=128m
-XX:+UseCompressedClassPointers
-XX:CompressedClassSpaceSize=64m
-XX:+UseG1GC
and memory increase over time. look at this.
 
![c4af002dd879d4dd8ada5820cf31633](https://user-images.githubusercontent.com/6747834/57698308-ef5ca700-7687-11e9-9e96-5be784e23c10.png)

and I found there's an scheduled thread to do this every scanInterval(default 5000) ms,
is this a problem?

### Redis version
3.2.11
### Redisson version
3.10.2
### Redisson configuration
we set redis cluster nodes and password only.

**Comment by mrniko** [comment]
Please provide memory dump for investigation. I don't memory leaks in souce code related to cluster state scan.

**Comment by Roronoa-Zoro** [comment]
> Please provide memory dump for investigation. I don't memory leaks in souce code related to cluster state scan.

that file is big, how to upload?

**Comment by mrniko** [comment]
@Roronoa-Zoro 

Use https://anonfile.com/ don't forget to zip before

**Comment by mrniko** [comment]
Done
