### ISSUE TITLE
always use one thread to do cluster change check

### ISSUE THREAD

**Issue by Roronoa-Zoro** [redisson/redisson#2106]
### Steps to reproduce or test case
in our test env, we set log level debug, and there's some output for redisson, I found redisson always use one thread to do clusterChangeCheck, no matter how many times I relaunch.
![73e70667ad623898dd314c4b85110d2](https://user-images.githubusercontent.com/6747834/57698969-778f7c00-7689-11e9-8492-2687e1f8789a.png)

I read source code, and I found default nettyThread is 32, why does redisson just use second thread?
 
### Redis version
3.2.11
### Redisson version
3.10.2
### Redisson configuration
we only set cluster nodes and password.

**Comment by mrniko** [comment]
In your case netty threads amount could be reduced since load is low and minor amount of threads are used.
