### ISSUE TITLE
redission 可能重试机制跟 检查机制有点不符合我们国人的需求

### ISSUE THREAD

**Issue by walkersing** [redisson/redisson#2109]
### Expected behavior
`Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (DEL), params: [quick_pay_api_agent_password_count_16600000001], channel: [id: 0xea739d38, L:/192.168.0.137:61678 - R:192.168.1.38/192.168.1.38:6379]
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (DEL), params: [quick_pay_api_agent_password_count_16600000001], channel: [id: 0xea739d38, L:/192.168.0.137:61678 - R:192.168.1.38/192.168.1.38:6379]
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:935)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.lang.Thread.run(Thread.java:745)`
### Redis version
4.0.3

### Redisson version
3.10.7
### Redisson configuration
`<bean id="stringCodec" class="org.redisson.client.codec.StringCodec"/>
    <redisson:client id="sentinelRedisClient" codec-ref="stringCodec" >
        <redisson:sentinel-servers master-name="${redisson.master_name}"  database="0" retry-attempts="3" retry-interval="1500" password="${redisson.pwd}" connect-timeout="60000" master-connection-pool-size="100" master-connection-minimum-idle-size="10">
            <redisson:sentinel-address value="${redisson.node1}" />
            <redisson:sentinel-address value="${redisson.node2}" />
            <redisson:sentinel-address value="${redisson.node3}" />
        </redisson:sentinel-servers>
    </redisson:client>`

我的需求
1、数据连接池里面，会拥有最小链接数量
2、如果所有链接都断了，链接池数量为0
3、如果连接池数量为0，在用户再次用到RedissonClient，会去重新获取链接，retry-attempts 就应该生效。

现在是 error
redisson 会开启一个线程，维持redis心跳， redis 如果掉线 1500 ms 重试 3次，再获取不到链接的话。RedissonClient就不能用了。

**Comment by jackygurui** [comment]
什么情况能把这个问题上升到民族的高度了？你能紧急发布一下全部报错吗？

**Comment by gududexunli** [comment]
我遇到了和你一样的问题，你解决了吗

**Comment by walkersing** [comment]
> 我遇到了和你一样的问题，你解决了吗

没有。他这种不像我们使用的druid数据库连接池。他好像是维持了一个心跳。

**Comment by walkersing** [comment]
if redis-server shutdown one hour  .  the redissonclient can't be used again!

**Comment by jackygurui** [comment]
@walkersing 好像你对Redisson的各种机制理解有误。

首先Redisson的重试机制跟连接池检查机制是分开的。

连接池里每个连接都有一个watchdog，连接被断开时，首先会将该连接在连接池中设为不可用，然后watchdog会启动自动重连的机制。watchdog里每次重连失败以后，下次尝试的时间会[增长](https://github.com/redisson/redisson/blob/redisson-3.10.7/redisson/src/main/java/org/redisson/client/handler/ConnectionWatchdog.java#L86)。也就是说服务端断线时间越长，重试时间间隔也会相应增加。在实际生产中不推荐使用固定的时间进行重试，也是为了避免大量客户端定时发出连接对重启后的服务端造成冲击。

造成超时的原因主要有三个，
1. 线程池太繁忙，未在规定时间里处理完所有的消息。
2. 连接池太繁忙，在规定时间里列队里的消息未被及时发送出去。
3. 服务端太繁忙，在规定时间里没有及时回复请求。

在有些云上环境或某些防火墙或代理的设置造成了，一个正常连接在一段时间内没有数据发送的时候，会切断连接，但没有经过TCP的断线握手机制。这样会造成客户端无法感知，也无法启动上面介绍的重连机制。这样的情况下就需要开启心跳服务来避免这样的情况出现。

还有一些TCP代理或类似的服务设置不当，造成客户端与代理连接正常，但代理与后端服务的连接断开的情况。这样的情况也会触发服务端超时但不会触发重连机制。

你需要根据自己的情况去判断原因并做相应的配置上的修改，这些情况并不是Redisson能够从代码里解决的。

[FAQ里的第一条](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it)也讲到了超时的事情，你可以了解一下。

**Comment by gududexunli** [comment]
@jackygurui 在有些云上环境或某些防火墙或代理的设置造成了，一个正常连接在一段时间内没有数据发送的时候，会切断连接，但没有经过TCP的断线握手机制。这样会造成客户端无法感知，也无法启动上面介绍的重连机制。这样的情况下就需要开启心跳服务来避免这样的情况出现。

我使用的Azure reids 单节点，业务量并不大，出现的是Responsetimeout，心跳服务是怎么开启的，并没有在文档中找到相关的描述

**Comment by jackygurui** [comment]
@gududexunli https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/BaseConfig.java#L398

**Comment by xiamaohan** [comment]
额，上升到国家高度了。不过和spring boot 2.1.5集成session，要报错，有人解决没？

**Comment by xiamaohan** [comment]
哎呦，我刚看了下，居然是中国人在写，请大神收下我的膝盖。

**Comment by jackygurui** [comment]
项目主要是俄罗斯兄弟在写。我在帮忙。

**Comment by jackygurui** [comment]
> 额，上升到国家高度了。不过和spring boot 2.1.5集成session，要报错，有人解决没？
> 
> 主要是maxInactiveIntervalInSeconds为NULL，然后接收的又是int。

报错是什么内容？Spring Data Redis和redisson-spring-boot-starter的版本有没有冲突？

**Comment by xiamaohan** [comment]
> 
> 
> > 额，上升到国家高度了。不过和spring boot 2.1.5集成session，要报错，有人解决没？
> > 主要是maxInactiveIntervalInSeconds为NULL，然后接收的又是int。
> 
> 报错是什么内容？Spring Data Redis和redisson-spring-boot-starter的版本有没有冲突？

是这样的，把spring boot 改成2.1.5后，RedissonHttpSessionConfiguration里面的setImportMetadata方法没执行，然后就执行了sessionRepository方法，导致maxInactiveIntervalInSeconds为null，然后接收maxInactiveIntervalInSeconds的方法里面的类型为int，导致启动报错。

redisson.version = 3.10.7

**Comment by jackygurui** [comment]
@xiamaohan 如果你有解决方案了能发一个PR给@mrniko吗？

**Comment by xiamaohan** [comment]
> 
> 
> @xiamaohan 如果你有解决方案了能发一个PR给@mrniko吗？

您能帮忙先改改吗？
RedissonSessionRepository
299
public void setDefaultMaxInactiveInterval(int defaultMaxInactiveInterval) {

改为

public void setDefaultMaxInactiveInterval(Integer defaultMaxInactiveInterval) {

可以暂时解决。

主要问题就是不知道为什么升级后ImportAware接口不生效了。

**Comment by zhou-hao** [comment]
#2148   redisson的策略是同一时间只能使用一个链接？在连接不够时, 也会触发重试？ 为啥不直接丢给netty 处理？最近被重试折腾得。。。。

**Comment by walkersing** [comment]
尴尬的一批，我们周五做了一次网络故障演练，把redis 和应用之间的网络断了之后又恢复。结果所有的系统都不能用了，redis 获取不到链接

**Comment by abing0610** [comment]
我也出现了 这种情况。后来怎么解决的？

**Comment by linmingchang** [comment]
Sentinel模式下，当从节点故障时，也出现了一模一样的情况。求解决方案

**Comment by jackygurui** [comment]
@walkersing @abing0610 @linmingchang 希望大家介绍一下生产环境的情况，我相信每个人的情况都不一样。比如节点是否用了VIP，是否用了代理，节点断开多久恢复的等等细节。光是说跟某某一样没用啊

**Comment by linmingchang** [comment]
Redisson版本：3.11.0
redis集群模式：哨兵模式（一主两从，这里假设主节点为A，从节点分别为B1、B2）
情况：
redis从节点B1出现故障
Redisson client至少30分钟内都未能清除到B1的连接，还是不断有命令发送至B1，直到手动重启服务后恢复
报错信息如下：
` exception: org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.16.16.55:6311], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1351206136 [redisClient=[addr=redis://172.16.16.56:6311], channel=[id: 0xdd34b09d, L:/172.16.16.22:26746 - R:172.16.16.56/172.16.16.56:6311], currentCommand=null], command: (GET), params: [2806:eeffe5b8b47a4797ab0973d5ae7a118a] after 3 retry attempts, dubbo version: 2.6.0, current host: 172.16.16.22"`

问题：
Redisson在什么前提下才会丢弃无效连接？尤其是在集群模式下，某台机器不可用是很常见的情况

**Comment by abing0610** [comment]
所有节点都挂掉。主从全部挂掉。断开连接半个小时以上就无法使用了。

**Comment by jackygurui** [comment]
@linmingchang @abing0610 你俩还是按照模板单独开个帖子吧，你们的情况跟楼主都不一样，就你两之间的情况都是相反的。

**Comment by wangbo911** [comment]
这个用来做分布式锁，建议怎么用@jackygurui

**Comment by xiamaohan** [comment]
> 
> 
> 这个用来做分布式锁，建议怎么用@jackygurui

RLock lock = redissonClient.getLock(xxxxxx);
lock.lock(1, TimeUnit.MINUTES);

完事了lock.unlock();

最好是加上finally。

**Comment by iwin4aids** [comment]
这个是很难复现的问题，我认为redisson客户端的稳定性在生产上有很大的风险，我的测试是在3.11.2版本，这个超时问题在系统运行几个小时或者一天后才会发生，开始的时候根本无法测试出现，这个是很头疼的

**Comment by alanland** [comment]
```
org.redisson.client.RedisTimeoutException: Unable to send command!
```

线上连续出现这个问题了，大家有遇到么

**Comment by mrniko** [comment]
@alanland 

Please refer to this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by walkersing** [comment]
我这个问题，好像不存在了。redissonClient 不要重复getConfig() 然后set 一些值，会内存溢出的
