### ISSUE TITLE
RedisResponseTimeoutException

### ISSUE THREAD

**Issue by gududexunli** [redisson/redisson#2111]
config
![image](https://user-images.githubusercontent.com/22949862/57902333-45edff00-789b-11e9-8a7c-ef6915496c48.png)

org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, CAMPAIGN_LOCK_ee3aa6b4-b89f-469e-bf16-83c100ad7262, 300000, bf26bdb9-3584-4cbd-9fc5-dfbed4b2cc52:148], channel: [id: 0x4e899fa3, L:/10.233.80.88:52776 - R:B2B-prd-PPM-redis-0.redis.cache.chinacloudapi.cn/42.159.102.154:6380]

当出现一次这个问题后，后面所有获取锁的代码都会出现这个问题
并且 使用jedis不会出现这个问题

部分服务在重启后，立刻恢复可用。
部分服务在没有重启的情况下，2小时后又重新恢复可用了。
### Redisson version
3.10.6

**Comment by jackygurui** [comment]
与`Redis server response timeout`有关的问题请先看[FAQ第一条](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it)。
