### ISSUE TITLE
RScoredSortedSet 

### ISSUE THREAD

**Issue by asdxiaoqex** [redisson/redisson#2112]
No deletion after removing the last N；

RScoredSortedSet<MemberDiary> set = redissonClient.getScoredSortedSet(RedisLogin.PASSING.getName());
         list=set.pollLast(10);
Which api？

**Comment by mrniko** [comment]
Unable to reproduce this. Below is my test:

```java
RScoredSortedSet<Integer> queue1 = redisson.getScoredSortedSet("queue:pollany");
for (int i = 0; i < 100; i++) {
     queue1.add(i, i);
}
        
for (int i = 0; i < 11; i++) {
     Collection<Integer> s = queue1.pollLast(10);
     System.out.println(s);
}
```

**Comment by asdxiaoqex** [comment]
> 无法复制这个。以下是我的测试：
> 
> ```java
> RScoredSortedSet<Integer> queue1 = redisson.getScoredSortedSet("queue:pollany");
> for (int i = 0; i < 100; i++) {
>      queue1.add(i, i);
> }
>         
> for (int i = 0; i < 11; i++) {
>      Collection<Integer> s = queue1.pollLast(10);
>      System.out.println(s);
> }
> ```
pulllast（N）but don‘t remove

**Comment by mrniko** [comment]
Use `RScoredSortedSet.entryRange` or `RScoredSortedSet.valueRange` methods

**Comment by asdxiaoqex** [comment]
> 使用`RScoredSortedSet.entryRange`或`RScoredSortedSet.valueRange`方法

But I want to take the last N or pagination directly instead of the score interval.

**Comment by mrniko** [comment]
Here is the example how to do it:

```java
        RScoredSortedSet<Integer> set = redisson.getScoredSortedSet("simple");
        set.add(0, 1);
        set.add(1, 2);
        set.add(2, 3);
        set.add(3, 4);
        set.add(4, 5);
        set.add(4, 5);

        Collection<Integer> vals = set.valueRangeReversed(0, -1);
```
