### ISSUE TITLE
启动时AbstractMethodError错误的解决方案

### ISSUE THREAD

**Issue by wangjinhe** [redisson/redisson#2114]
将maven依赖修改为：

` 
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                  <artifactId>redisson-spring-data-21</artifactId>
                    <groupId>org.redisson</groupId>
                    </exclusion>
            </exclusions>
            <version>3.10.6</version>
        </dependency>
        
        <dependency>
            <groupId>org.redisson</groupId>
            
            <artifactId>redisson-spring-data-20</artifactId>
            <version>3.10.6</version>
        </dependency>
`

**Comment by wangjinhe** [comment]
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                  <artifactId>redisson-spring-data-21</artifactId>
                    <groupId>org.redisson</groupId>
                    </exclusion>
            </exclusions>
            <version>3.10.6</version>
        </dependency>
        
        <dependency>
            <groupId>org.redisson</groupId>
            
            <artifactId>redisson-spring-data-20</artifactId>
            <version>3.10.6</version>
        </dependency>

**Comment by jackygurui** [comment]
能把触发的条件介绍一下吗？我这边好记录一下也可以更新一下相关文档。

**Comment by wangjinhe** [comment]
` <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                  <artifactId>redisson-spring-data-21</artifactId>
                    <groupId>org.redisson</groupId>
                    </exclusion>
            </exclusions>
            <version>3.10.6</version>
        </dependency>
        
        <dependency>
            <groupId>org.redisson</groupId>
            
            <artifactId>redisson-spring-data-20</artifactId>
            <version>3.10.6</version>
        </dependency>`

**Comment by wangjinhe** [comment]
https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter
按照上面的说明，添加依赖，直接启动项目，然后启动时报错，不过不影响使用。
原因是：https://github.com/redisson/redisson/issues/1989

By default Redisson Spring Boot module depends on redisson-spring-data-21 module which is compatible spring data 2.1.x. You're using Spring Data 2.0.x, so you need to exclude redisson-spring-data-21 dependency and use redisson-spring-data-20 instead.
