### ISSUE TITLE
Expose async entrySet with keyPattern and count, RedissonMap#scanIteratorAsync?

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#2117]
### Expected behavior

Async API for org.redisson.api.RMap#entrySet(java.lang.String, int)

### Actual behavior

There is only sync API available.

**Comment by johnou** [comment]
ping @mrniko if you can provide a little bit of feedback how the api might look i'm happy to try and implement it.

**Comment by mrniko** [comment]
I think `AsyncIterator` interface should be introduced

**Comment by johnou** [comment]
work in progress here https://github.com/redisson/redisson/compare/master...sulake:async_map_iterator?expand=1

**Comment by mrniko** [comment]
Looks good. Thank you!

Do you plan to implement this feature only for RedissonMap#asyncEntriesIterator method?

**Comment by mrniko** [comment]
As option you could use `RMapReactive.entryIterator` or `RMapRx.entryIterator` method

**Comment by johnou** [comment]
I haven't touched any reactive code so RedissonMap#asyncEntriesIterator is the current goal.

**Comment by mrniko** [comment]
Also use RPromise.onComplete if possible.

**Comment by johnou** [comment]
@mrniko any suggestions on how the entrySetAsync method signature might look?

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/compare/master...sulake:async_map_iterator?expand=1#diff-b18b29be1e06b8e5730d78c7aa4ab069R317

Correct me if I wrong. Shouldn't this method return `AsyncIterator` rather than RFuture object?

**Comment by johnou** [comment]
@mrniko do you have some spare cycles for this?

**Comment by mrniko** [comment]
@johnou 

I couldn't imagine better interface than suggested by Reactive approach.

**Comment by johnou** [comment]
@mrniko don't suppose you have some extra cycles to work on this issue?

**Comment by johnou** [comment]
@mrniko unless it's possible to create a RMapReactive from a normal RMap?

**Comment by mrniko** [comment]
currently there is no other way.

**Comment by johnou** [comment]
@mrniko can we take a more generic approach, like allowing to share connectionManager between an instance of org.redisson.Redisson and org.redisson.RedissonReactive?

**Comment by johnou** [comment]
looks like it might be possible already using useCustomServers...

**Comment by johnou** [comment]
@mrniko is it safe to define Redisson clients like this?

```java
Config config = new Config();

ReplicatedServersConfig clusterConfig = new ReplicatedServersConfig(); //config.useReplicatedServers();
clusterConfig.setScanInterval(2500);
clusterConfig.setDnsMonitoringInterval(2500);
clusterConfig.setDatabase(database);
clusterConfig.setTcpNoDelay(true);
clusterConfig.setKeepAlive(true);
for (String addr : StringUtils.tokenizeToStringArray(redisNodes, ",", true, true)) {
	clusterConfig.addNodeAddress(addSchema(addr));
}
clusterConfig.setTimeout(timeout);
clusterConfig.setRetryAttempts(retryAttempts);
clusterConfig.setRetryInterval(retryInterval);
clusterConfig.setReadMode(ReadMode.SLAVE);
 // shared connection manager
config.useCustomServers(new ReplicatedConnectionManager(clusterConfig, config, UUID.randomUUID()));

config.setCodec(new SnappyCodec());
config.setEventLoopGroup(redisEventLoop.getWorkerGroup());
config.setTransportMode(redisEventLoop.isNativeEpoll() ? TransportMode.EPOLL : TransportMode.NIO);
// inject shared dns address resolver to save memory
config.setAddressResolverGroupFactory((channelType, nameServerProvider) -> dnsAddressResolverGroup);
config.setReferenceEnabled(false);

return new RedissonClientPair(Redisson.create(config), Redisson.createReactive(config));
```

**Comment by mrniko** [comment]
Yes, ConnectionManager-s are thread safe
