### ISSUE TITLE
redis域名绑定ip变更，redissonClient不会切换到新redis地址

### ISSUE THREAD

**Issue by lujun920** [redisson/redisson#2119]
您好，有个问题咨询下，背景是这样的，公司最近在对网络进行大面积调整，现在出现这样的情况，redis域名 redis.xxxx.com 之前绑定在ip A下，网络调整后，切换到IP B，如果应用不重启的话，redissClient无法使用redis.xxxx.com无法自动切换连接到 IP B，异常信息依然是连接IP A。请问下现在redisson 断线重连机制是什么样的？重连时如何刷新InetSocketAddress？
### Expected behavior
redis域名绑定ip变更后，能正常链接到切换后的新ip
### Actual behavior
redis域名变更后连接能切换到新ip redis
### Steps to reproduce or test case
测试通过修改hosts文件，将映射
redis.xxxx.com   ip a
#redis.xxxx.com   ip b
切换后测试redissonClient连接是否正常
### Redis version
redis 4.0.10
### Redisson version
redisson 3.10.6
### Redisson configuration
cache:
  redis:
    address: redis://redis.xxxxxx.com:6379
    password: xxxx
    # 默认缓存有效期：30天
    expire-time: 30
    pool-config:
      min-idle: 10
      pool-size: 32
      connect-timeout: 15000
      max-wait-timeout: 10000
      retry-attempts: 3
      retry-interval: 1000

**Comment by jackygurui** [comment]
netty认为hosts文件里的内容是静态的，启动后就不会再读了。请使用DNS服务。
