### ISSUE TITLE
Memory leak using Sentinel

### ISSUE THREAD

**Issue by jcarlosvale** [redisson/redisson#2120]
I am getting a memory leak when I try to connect to Redis using SentinelServer and the server is unavailable.
I create a separated thread trying to connect in a loop and the memory consumption increase over time. My RedissonWrapper code:
`
@Component
public class RedissonWrapper {

    private  ExecutorService executor;
    private  AtomicReference<RedissonClient> redissonClientSupplier;
    private final NioEventLoopGroup nioEventLoopGroup;

    @Autowired
    public RedissonWrapper(RedisConfig redisConfig) {
        nioEventLoopGroup = new NioEventLoopGroup();
        ThreadFactory schedulerThreadFactory = new ThreadFactoryBuilder().setNameFormat("REDISSON_WRAPPER-%d").build();
        executor = Executors.newSingleThreadExecutor(schedulerThreadFactory);

        executor.submit(() -> {
            redissonClientSupplier = new AtomicReference<>(null);
            RedissonClient redissonClient = null;

            while (redissonClient == null) {
                try {
                    redissonClient = createRedissonClient(redisConfig);
                    if (redissonClient != null) {
                        log.info("Redisson Client successfully created");
                        this.redissonClientSupplier.set(redissonClient);
                        executor.shutdown();
                    }
                } catch (Exception e) {
                    log.error("Error while creating Redis Client with messagee: '{}'. Trying again in 5 seconds...",
                            e.getMessage());
                    log.error("Error while creating Redis Client ", e);
                    System.gc();
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException e1) {
                        e1.printStackTrace();
                    }
                }
            }

        });
    }

    public RedissonClient getRedissonClient() {
        return redissonClientSupplier.get();
    }

    public boolean isRedisUp() {
        RedissonClient redissonClient = getRedissonClient();
        if (redissonClient == null) {
            return false;
        }
        try {
            for (Node node : redissonClient.getNodesGroup().getNodes()) {
                if (node.ping()) {
                    return true;
                }
            }
        } catch (Exception e) {
            log.warn("Exception caught when trying to ping the nodes: {}", e.getMessage());
        }
        return false;
    }

    private RedissonClient createRedissonClient(RedisConfig redisConfig) {
        Config config = new Config();
        config.setEventLoopGroup(nioEventLoopGroup);
        config.setReferenceEnabled(false);
        if (redisConfig.isSentinelEnabled()) {
            SentinelServersConfig sentinelServersConfig = config.useSentinelServers();
            sentinelServersConfig
                    .setDatabase(redisConfig.getDatabase())
                    .setPassword(redisConfig.getPassword())
                    .setMasterName(redisConfig.getMasterName());
            redisConfig.getNodes().forEach(sentinelServersConfig::addSentinelAddress);
        } else {
            config.useSingleServer()
                    .setAddress(redisConfig.getNodes().get(0));
        }
        return Redisson.create(config);
    }
}`

Simulating the error:
1 - Turn Off the REDIS SERVER
2 - Execute the code (Spring Boot)

LOG: [https://anonfile.com/a7Q6ubs8nb/log_demo_redis_txt](https://anonfile.com/a7Q6ubs8nb/log_demo_redis_txt)

<img width="1158" alt="Screen Shot 2019-05-21 at 12 15 44" src="https://user-images.githubusercontent.com/1156767/58091808-7c40bc80-7bc2-11e9-919b-5c15a508a3b5.png">
<img width="1162" alt="Screen Shot 2019-05-21 at 12 16 00" src="https://user-images.githubusercontent.com/1156767/58091821-8367ca80-7bc2-11e9-9474-fa9a475f3104.png">
<img width="1157" alt="Screen Shot 2019-05-21 at 12 16 15" src="https://user-images.githubusercontent.com/1156767/58091825-85ca2480-7bc2-11e9-8679-6c502e77101a.png">

**Comment by mrniko** [comment]
You need to call `redissonClient.shutdown` in exception handling block

**Comment by jcarlosvale** [comment]
But in this case o Redisson.create(config) is a static method and throws the exception without a client, nothing is returned to shutdown.

**Comment by mrniko** [comment]
Unable to reproduce it. Could you show on heap dump which objects belong to Redisson are consuming the memory?
