### ISSUE TITLE
Explanation of Config connection/thread settings

### ISSUE THREAD

**Issue by mayankmmmx** [redisson/redisson#2121]
I am fairly new to Redisson and had a few questions I would like clarified. I read through the documentation, but the description of config settings weren't very helpful to me.

1) For every RedissonClient, a connection pool is created with a set min idle size and max size. How is each connection exactly used? Does each operation use a connection? Are ops batched into one request and sent through the connection?

2) When we set the `threads` parameter (`setThreads`), what are these threads used for? Connecting to redis? Deserializing?

3) When we set the `nettyThreads` parameter, what are these threads used for?

4) What is relationship between `nettyThreads`, `threads`, and `connectionPool`? What are important things to keep in mind while tuning these parameters?

Thank you!

**Comment by mrniko** [comment]
1. Connection is used per operation unless you use RBatch object. It allows to send multiple commands in batch.

2. Defineds `threads` are shared across all listeners of `RTopic` object, invocation handlers of `RRemoteService` object and `RExecutorService` tasks.

3. Netty threads are used for Redis response decoding and command sending.

4. You many need to increase `nettyThreads` if you use big `connectionPool`
