### ISSUE TITLE
Clearer documentation regarding pattern topics

### ISSUE THREAD

**Issue by olasundell** [redisson/redisson#2123]
The following is an excerpt from the documentation regarding pattern topics:
```
// subscribe to all topics by `topic1.*` pattern
RPatternTopic topic1 = redisson.getPatternTopic("topic1.*");
int listenerId = topic1.addListener(Message.class, new PatternMessageListener<Message>() {
    @Override
    public void onMessage(String pattern, String channel, Message msg) {
         Assert.fail();
    }
});
```

The pattern string looks like a regexp even though it is a glob string, which confounded us. 

Please clarify the documentation, both in the code example - for instance by replacing `"topic1.*"` with something like `"topic.x*"` - and the documentation for `RedissonClient.getPatternTopic()`

**Comment by mrniko** [comment]
Fixed! Thanks for pointing out!
