### ISSUE TITLE
RedisTimeoutException: Unable to send batch after 3 retry attempts

### ISSUE THREAD

**Issue by mayankmmmx** [redisson/redisson#2125]
### Expected behavior
With ~800qps from 2 RedissonClients, we do not expect to see ~2qps of error rate with the following error: `RedisTimeoutException: Unable to send batch after 3 retry attempts`. Ideally, we should see no errors, or few errors as this isn't high load.

### Actual behavior
We observe around 2qps errors (`RedisTimeoutException: Unable to send batch after 3 retry attempts`) that increase in a "step" up fashion. See image:

<img width="1587" alt="Screen Shot 2019-05-23 at 12 14 53 PM" src="https://user-images.githubusercontent.com/5217785/58268984-8397cf80-7d54-11e9-8ddf-598107f03eb1.png">

This graph is the traffic sent to redis in the same timespan:
<img width="1592" alt="Screen Shot 2019-05-23 at 12 15 33 PM" src="https://user-images.githubusercontent.com/5217785/58268994-898db080-7d54-11e9-9e26-52b5f4104015.png">

As a side note: we are running 2 kubernetes pods, each with one RedissonClient that cumulatively are making requests/seeing the errors from the graphs above. The interesting thing to note is that for about 9hours after we start the pods (creating a new client in each) and send them traffic, they perform fine for around ~9hours and then the errors begin. We hypothesize that there is some issue in how the connections are managed.

### Steps to reproduce or test case
1. Create 2 RedissonClient instances
2. Send between 400-850qps of traffic (variable) for around a day, where traffic includes batch ADD and PUT commands.
3. Observe failures.

### Redis version
4.0.1

### Redisson version
3.10.7

### Redisson configuration
Cluster mode

Read mode: Master (we do not have slave nodes)
Master connection pool size: 64
Master connection pool minimum idle size: 0
Slave connection pool size: 0
Slave connection pool minimum idle size: 0
Subscription connection pool size: 0 (we do not use pubsub capabilities of redis)
Subscription connection pool minimum idle size: 0
Connect timeout: 500ms
Timeout: 500ms
Retry attempts: 3

**Comment by mrniko** [comment]
Have you followed these suggestions - https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it ?

**Comment by mayankmmmx** [comment]
I've looked into them and we are trying.. would you happen to know why we are experience the "step" pattern of increasing errors? If there was a lack of nettyThreads or connections, wouldn't the errors be more uniform?

**Comment by mayankmmmx** [comment]
Wanted to follow up from some of our trials: we have a separate RedissonClient running in SingleServer Mode with the follow config:

Connection pool size: 64
Connection pool minimum idle size: 0
Subscription connection pool size: 0 (we do not use pubsub capabilities of redis)
Subscription connection pool minimum idle size: 0


We were seeing the same RedisTimeoutException as above for this client, but we followed the FAQ guide above and increased netty threads to 48 and saw this error appear:

`org.redisson.client.RedisException: Unexpected exception while processing command` which further down the stack trace is caused by: `Caused by: java.nio.channels.ClosedChannelException`. Have you ever seen this before / know what it may mean?

**Comment by PaniniGelato** [comment]
Same problem here with 3.10.7

**Comment by mrniko** [comment]
> Caused by: java.nio.channels.ClosedChannelException. Have you ever seen this before / know what it may mean?

This means that connection is closed due to network issue or something.

**Comment by mrniko** [comment]
@PaniniGelato 

Which error? Did you try to follow these steps https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it ?

**Comment by PaniniGelato** [comment]
@mrniko 

got exception during load test(about 1000qps):
```
org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=1021, freeConnectionsCounter=value:1021:queue:0, freezed=false, freezeReason=null, client=[addr=redis://ip:port], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1208598866 [redisClient=[addr=redis://ip:port], channel=[id: 0xe56d57a0, L:/ip:port - R:ip:port], command=CommandsData [commands=[]]], current command in queue: null, command: (GET), params: [my_key:659472150] after 3 retry attempts
```

my config
```
        org.redisson.config.Config cc = new org.redisson.config.Config();
        cc.useSingleServer()
                .setAddress("redis://" + host + ":" + port)
                .setPingConnectionInterval(60*1000)
                .setIdleConnectionTimeout(10*60*1000)
                .setConnectionPoolSize(poolSize)
                .setTimeout(2000)
                .setKeepAlive(true)
                .setTcpNoDelay(true)
                .setRetryAttempts(1)
                .setRetryInterval(500);
        cc.setCodec(StringCodec.INSTANCE);
        cc.setTransportMode(TransportMode.EPOLL);
        cc.setNettyThreads(32);
        cc.setThreads(256);
        cc.setDecodeInExecutor(true);
```

enlarge nettyThreads didn't help me

**Comment by mrniko** [comment]
@PaniniGelato 

Did you try to increase connection pool?

**Comment by PaniniGelato** [comment]
@mrniko 

poolSize=1024

trying nettyThreads=128, come back later

**Comment by PaniniGelato** [comment]
the client died at 784qps with 
```
org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=249, freeConnectionsCounter=value:0:queue:2836, freezed=false, freezeReason=null, client=[addr=redis://ip:port], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@724231806 [redisClient=[addr=redis://ip:port], channel=[id: 0x4633f9d1, L:/ip:port - R:ip:port], command=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@372d746b(failure: java.util.concurrent.CancellationException)], command=(ZREVRANGEBYSCORE), params=[my_key:6938743714, 1560258659198, 0.0, LIMIT, 0, 3], codec=org.redisson.client.codec.StringCodec]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@372d746b(failure: java.util.concurrent.CancellationException)], command=(ZREVRANGEBYSCORE), params=[my_key:6938743714, 1560258659198, 0.0, LIMIT, 0, 3], codec=org.redisson.client.codec.StringCodec], command: (GET), params: [str:cmt:aid:17713828073626568760:cid:6823694158] after 1 retry attempts
```

**Comment by mrniko** [comment]
@PaniniGelato 

`failure: java.util.concurrent.CancellationException` was happen due to earlier cancel of command execution.
try to set retryinterval = 1500

**Comment by mrniko** [comment]
Also make sure you redis instance is not overloaded

**Comment by PaniniGelato** [comment]
```
org.redisson.config.Config cc = new org.redisson.config.Config();
cc.useSingleServer()
        .setAddress("redis://" + host + ":" + port)
        .setIdleConnectionTimeout(10*60*1000)
        .setConnectionPoolSize(poolSize)
        .setTimeout(3000)
        .setPingConnectionInterval(60*1000)
        .setKeepAlive(true)
        .setTcpNoDelay(true);
cc.setLockWatchdogTimeout(1000);// 锁超时1s
cc.setCodec(StringCodec.INSTANCE);
cc.setTransportMode(TransportMode.EPOLL);
cc.setNettyThreads(32);
cc.setThreads(32);
return Redisson.create(cc);
```
using this config is able to finish 800qps load test, no TimeoutException

Are the nettyThreads only use to hand I/O?
Setting it to be cpu nums or twice should be ok for most cases

would try again later...

**Comment by mrniko** [comment]
> Are the nettyThreads only use to handle I/O?

Not only, they also participany in command decoding.

> I am curious that i got freeConnectionsAmount=249 in stack trace which is far from ConnectionPoolSize, and my redis is not overloaded. It just looks like the client is not able to send command

Which poolsize did you set?
