### ISSUE TITLE
RedissonReactiveSubscription 

### ISSUE THREAD

**Issue by Kookey** [redisson/redisson#2126]
redisson-spring-data 
RedissonReactiveSubscription

private final AtomicReference<Flux<Message<ByteBuffer, ByteBuffer>>> flux = new AtomicReference<>();

the document of AtomicReference  is Creates a new AtomicReference with null initial value.

    @Override
    public Flux<Message<ByteBuffer, ByteBuffer>> receive() {
        if (flux.get() == null) {
            return flux.get();
        }
    }

this well always return null

**Comment by mrniko** [comment]
Fixed! Thanks for report
