### ISSUE TITLE
RedissonRedLock设计问题

### ISSUE THREAD

**Issue by tinelion** [redisson/redisson#2127]
首先赞一下作者的耐心，关于RedissonRedLock的实现我的疑问：RedissonRedLock据称是实现了http://ifeve.com/redis-lock/#respond 这篇文章提出的RedLock算法，按照这个算法的意图，加锁操作应该分散在不同的master节点以承受节点宕掉的风险。而RedissonRedLock使用自己提前实例化的RLock，通过联锁的方式实现 ，用户用字符串创建的RLock的key保存在哪个master具有随机性，多个RLock有较大概率保存在同一个master节点，这样有可能一个master节点宕掉就会导致key的丢失数量过半。因此这样设计是否没有达到RedLock算法的意图？

**Comment by xkrivzooh** [comment]
其实你可以搭建5个**完全独立**的redis节点，然后分别创建5个redis连接到这5个redis节点上, 也就是构建5个`Redisson`实例。

加锁的时候，用这5个`Redisson`实例创建5个`RLock`, 然后基于这5个`RLock`再构造`RedissonRedLock`就好了。这样就不存在你描述一个master节点宕机带来的问题了。

**Comment by wangbo911** [comment]
> 首先赞一下作者的耐心，关于RedissonRedLock的实现我的疑问：RedissonRedLock据称是实现了http://ifeve.com/redis-lock/#respond 这篇文章提出的RedLock算法，按照这个算法的意图，加锁操作应该分散在不同的master节点以承受节点宕掉的风险。而RedissonRedLock使用自己提前实例化的RLock，通过联锁的方式实现 ，用户用字符串创建的RLock的key保存在哪个master具有随机性，多个RLock有较大概率保存在同一个master节点，这样有可能一个master节点宕掉就会导致key的丢失数量过半。因此这样设计是否没有达到RedLock算法的意图？

你没理解RedLock的思想。

**Comment by DarrenJiang1990** [comment]
我觉得RedissonRedLock设计有问题，redlock是可以针对一个集群的多主情况，但是本项目设计的redlock却是需要多个redis集群，这明显的有问题

**Comment by jackygurui** [comment]
两则都可以的
