### ISSUE TITLE
RMapCache addListener

### ISSUE THREAD

**Issue by EhsanVahab** [redisson/redisson#2129]
Hi friends,
sorry if my topic is duplicated. I've looked for my question but haven't found any answer yet.

my question :  is RMapCache's onCreate event fired as a multi thread function?
for example: if I have multiple clients that produce data endlessly, is it possible to get produced data concurrently with onCreate event? or it's fired consecutively?

**Comment by mrniko** [comment]
All listeners on RMapCache object are fired concurrently.

**Comment by EhsanVahab** [comment]
thanks for your response.
but I've written an onCreate listener that waits until all instructions become completed to start new event.
I thing something goes wrong with my code.

`
RedissonClient redisson = Redisson.create();
RMapCache<String, Map<String, byte[]>> map = redisson.getMapCache("ImageInputList");
int createListener = map.addListener(new EntryCreatedListener<String, Map<String, byte[]>>() {
		     @Override
		     public void onCreated(EntryEvent<String, Map<String, byte[]>> event) {
//Instructions that take time

}

`

**Comment by mrniko** [comment]
threads amount in this case controlled by `threads` setting
