### ISSUE TITLE
Redis cluster health check fails while cluster is up

### ISSUE THREAD

**Issue by nel10000** [redisson/redisson#2130]
I have a Spring-boot app with Redisson and actuator. 
All system components are up and running: my app, Redis cluster, etc.
The health-check API is being called at "/health" (backed by actuator).
Please note that running the "CLUSTER NODES" command on the cluster (either with one node or several nodes) completes successfully:
ec2e193e101e02518ac64c9ff1ad4f7bcfc20f03 172.31.150.67:7001 slave ee9fcd350dff2ec8ee3044638e5bd2ffd00497ed 0 1558604295100 1 connected
ee9fcd350dff2ec8ee3044638e5bd2ffd00497ed 172.31.150.67:7000 myself,master - 0 0 0 connected 0-16383

### Expected behavior
"status": "UP" is expected
### Actual behavior
"status": "DOWN" is received.
The following detailed message appears:
redis": {
        "status": "DOWN",
        "connectionFactory": {
            "status": "DOWN",
            "error": "org.springframework.data.redis.ClusterStateFailureException: Could not retrieve cluster information. CLUSTER NODES returned with error."
        },
        "redisConnectionFactory": {
            "status": "UP",
            "cluster_size": 1,
            "slots_up": 16384,
            "slots_fail": 0
        }
    }
### Steps to reproduce or test case
Setup a redis cluster with one or more nodes.
### Redis version 
3.0.7
### Redisson version
Happens on both 2.2.12 and 3.10.6
### Redisson configuration
{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,      
      "connectTimeout":1000,
      "timeout":1000,
      "retryAttempts":3,
      "retryInterval":1000,
      "failedSlaveReconnectionInterval":3000,
      "failedSlaveCheckInterval":60000,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":25,
      "slaveConnectionMinimumIdleSize":5,
      "slaveConnectionPoolSize":100,
      "masterConnectionMinimumIdleSize":5,
      "masterConnectionPoolSize":100,
      "readMode":"SLAVE",
      "subscriptionMode":"SLAVE",
      "nodeAddresses":[
"//10.222.222.55:7000",
"//10.222.222.55:7001",
"//10.222.222.54:7000",
"//10.222.222.54:7001",
"//10.222.222.53:7000",
"//10.222.222.53:7001"
      ],
      "scanInterval":1000,
      "pingConnectionInterval":1,
      "keepAlive": false,
      "tcpNoDelay": false
   },
   "threads":16,
   "nettyThreads":32,
   "codec":{
      "class":"org.redisson.codec.FstCodec"
   },
   "transportMode":"NIO"
}

**Comment by mrniko** [comment]
Which redisson-spring-data version do you use?

**Comment by mrniko** [comment]
Unable to reproduce this using this test:

https://github.com/redisson/redisson/blob/master/redisson-spring-data/redisson-spring-data-21/src/test/java/org/redisson/spring/data/connection/RedissonClusterConnectionTest.java#L69

**Comment by nel10000** [comment]
Hello Mr. Niko
The project I'm working on is a few years old, so at first it had only redisson-3.10.6.jar.
Following your question the project was switched to redisson-spring-data-17-3.10.6.jar, but the problem remains.
The project is based on spring-boot 1.4.1.RELEASE which depends on spring-data-redis-1.7.3.RELEASE.

**Comment by nel10000** [comment]
Adding the following bean fixed the problem:
`    @Bean
    public RedissonConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
        return new RedissonConnectionFactory(redisson);
    }`
Thanks for your help!
