### ISSUE TITLE
Permanent kv (ttl=-1) was found in Redis while using Tomcat Session Manager

### ISSUE THREAD

**Issue by hotsun168** [redisson/redisson#2132]
### Expected behavior
All the timeout kv will disappear automaticlly. 

### Actual behavior
Some permanent kv still alive, and whose ttl are -1. 

### Steps to reproduce or test case
Using Tomcat Session Manager normally

### Redis version
2.2

### Redisson version
Newest version

### Redisson configuration
{
    "singleServerConfig": {
        "password": "******",
        "address": "redis://192.168.56.101:6379",
        "database": 8,
        "subscriptionsPerConnection": 3,
        "subscriptionConnectionMinimumIdleSize": 3,
        "subscriptionConnectionPoolSize": 3,
        "connectionMinimumIdleSize": 3,
        "connectionPoolSize": 3,
    }
}

### Details
First of all, after using Tomcat Session Manager for a long time, I found many kv in Redis and their ttl are all -1.
![无标题.png](https://i.loli.net/2019/05/29/5cedffefca74c91644.png)

Then I cleared Redis and did a simple test, first I put config content to tomcat in context.xml, then open a page but not did login action. I found a ttl=-1 kv.
![无标题2.png](https://i.loli.net/2019/05/29/5cee00c8b69e349828.png)

And second I did login with user name and password, I found another kv, but the ttl is session timeout second and was reducing automaticlly.
![无标题3.png](https://i.loli.net/2019/05/29/5cee00f39863a82539.png)

After a while (longer then timeout config value), it disappered. But another kv (ttl=-1) was still alive.
![无标题4.png](https://i.loli.net/2019/05/29/5cee0695dcd8291686.png)

In my expected case, all the kv will disappered automaticlly. That is to say, after a long long time and if nobody do login action, the Redis server will be empty.

Do anybody has some advise for this issue?

**Comment by christian-andersson** [comment]
We are also seeing this, unfortunally for us it have caused us downtime 2 times due to redis OutOfMemoryException.
for us it looks like anytime that tomcat does an invalidate (ie the user presses the logout button, or we call the session.invalidate method) of the session, redisson will either replace the sessionobject in redis with a new one that does not have an TTL, or it deletes all session values excepts its own, and changes the TTL to -1 (ie no ttl)

**Comment by mrniko** [comment]
Was fixed in https://github.com/redisson/redisson/issues/2104

Please update to 3.11.1+ version
