### ISSUE TITLE
Use maven packaging for redisson project as jar instead of bundle

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#2135]
### Redisson version
3.11.1-SNAPSHOT

**Comment by jchobantonov** [comment]
Hi @mrniko , 

Could you change the redisson/pom.xml packaging from bundle to jar - the issue that I'm having is when using Eclipse to import the maven projects it will not understand the packaging of bundle as it is not standard and it will not import the projects correctly, more over when you do have dependency on redisson maven project you are using the jar dependency and not bundle dependency.

I have modified maven-bundle-plugin execution so that it will create a jar file with the correct MANIFEST.MF

here is what the execution looks like:
```
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>  
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive> 
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>3.2.0</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>bundle-manifest</id>
                        <phase>process-classes</phase>
                        <goals>    
                            <goal>manifest</goal>
                        </goals>   
                    </execution>
                </executions>				
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <DynamicImport-Package>*</DynamicImport-Package>
                    </instructions>
                </configuration>
            </plugin>
```

and the explanation how to still use jar packaging and use the maven-bundle-plugin is here:
https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

Here is modified version of the pom file that will still include the correct MANIFEST.MF file for OSGi:

[pom.zip](https://github.com/redisson/redisson/files/3233584/pom.zip)

**Comment by jchobantonov** [comment]
@mrniko here is PR: https://github.com/redisson/redisson/pull/2168

**Comment by mrniko** [comment]
Merged
