### ISSUE TITLE
Purpose of returning RFuture in setupMasterEntry

### ISSUE THREAD

**Issue by pippoflow** [redisson/redisson#2139]
As I'm following through the code, the method `setupMasterEntry` is executed in a single-threaded context, so what is the idea of the `RFuture`? The caller of this method is essentially "blocked" on this method until it's done. Am I understanding this right? If the caller expects a `Future` to be returned immediately, all the heavy-lifting work has to be done by a different thread, which is the basic idea of the `Future/Promise` model. 

Please correct me.

**Comment by mrniko** [comment]
> The caller of this method is essentially "blocked" on this method until it's done. Am I understanding this right?

Could you point out on the code?

**Comment by pippoflow** [comment]
Sorry mrniko I overlooked the fact that the listener registered with `onComplete` is indeed executed in a netty thread pool since a netty promise is wrapped within. Thanks! Closing this issue.

**Comment by pippoflow** [comment]
Sorry mrniko I overlooked the fact that the listener registered with `onComplete` is indeed executed in a netty thread pool since a netty promise is wrapped within. Thanks! Closing this issue.
