### ISSUE TITLE
Redisson warning ，redis sentinel node added and down frequently！

### ISSUE THREAD

**Issue by fanchangjifen** [redisson/redisson#2143]
### Redis version
4.0.6
### Redisson version
3.11.0
### Redisson configuration

![image](https://user-images.githubusercontent.com/9379331/58798170-7f14c600-8634-11e9-861c-0e6d410a37c4.png)

**Comment by mrniko** [comment]
Could you switch logging level to TRACE for `org.redisson` and share the log? It should contain result of SENTINEL SENTINELS command

**Comment by mrniko** [comment]
Fixed! Thanks for report
