### ISSUE TITLE
rateLimiter does not work,since version3.7.2

### ISSUE THREAD

**Issue by apple987** [redisson/redisson#2149]
here is my code:
 ==========================================================
         public @interface RateLimiter {
                   int limit() default 5;//放行数量,5个
                  int timeout() default 1;//限流时间间隔，默认1秒
                  String rateKey() default "";//限流器，自定义key
                String timeUnit() default "SECONDS";//限流器，默认限流时间单位
         }        
 ==========================================================
	@ApiOperation(value = "测试格式化显示", notes = "测试格式化显示", httpMethod = "GET")
	@RequestMapping(value = "/formatCode", method = RequestMethod.GET)
	@RateLimiter(limit = 1,timeUnit=“SECONDS”,timeout =5,rateKey="formatCode")
        public String formatCode(HttpServletRequest req) {
		System.err.println("formatJson");
		return "format_code";
	}
 ==========================================================
  public static boolean tryAcquire(RedissonClient redisClient,
                 String rateKey,long permits,long 
                 timeout,String timeUnit) {
	          RRateLimiter rateLimiter = redisClient.getRateLimiter(rateKey);
		  //初始化,最大流速 = 每1秒钟产生10个令牌
                 rateLimiter.trySetRate(RateType.OVERALL, permits, timeout, 
                          RateIntervalUnit.SECONDS);//1秒permits个token
		return rateLimiter.tryAcquire(1,0, TimeUnit.SECONDS);//间隔一秒，尝试一次
}
 ==========================================================
public class RateLimiterInterceptor extends HandlerInterceptorAdapter {
	
	private Logger logger = LoggerFactory.getLogger(RateLimiterInterceptor.class);
	
	@Autowired
        private RedissonClient redisClient;

	@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)  {
			if(handler instanceof HandlerMethod){
				 HandlerMethod handlerMethod = (HandlerMethod) handler;
		         Method method = handlerMethod.getMethod();
		         RateLimiter rateLimiter = method.getAnnotation(RateLimiter.class);
		         if (rateLimiter != null) {
		             int limit = ObjectUtils.isEmpty(rateLimiter.limit())?RedisRateLimiter.REDISSON_RATE_LIMITER_PERMITS:rateLimiter.limit();
		             long timeout = ObjectUtils.isEmpty(rateLimiter.timeout())?RedisRateLimiter.REDISSON_RATE_LIMITER_TIMEOUT:rateLimiter.timeout();
		             String rateKey=StringUtils.isEmpty(rateLimiter.rateKey())?request.getRequestURI():rateLimiter.rateKey();//key为空判断
		             rateKey=RedisRateLimiter.REDISSON_RATE_LIMITER_KEY+rateKey;
		             String timeUnit=ObjectUtils.isEmpty(rateLimiter.timeUnit())?RedisRateLimiter.REDISSON_RATE_LIMITER_TIMEUNIT:rateLimiter.timeUnit();
		             Boolean isAllow=RedisRateLimiter.tryAcquire(redisClient, rateKey, limit, timeout, timeUnit);
		             if(!isAllow){
		            	 logger.warn("很抱歉，服务器繁忙，请稍后重试!");
		            	 throw new RRException("服务器繁忙，请稍后重试!", HttpStatus.SERVICE_UNAVAILABLE.value());
		             }
		         }
			}
			return true;
		}
}		
 ==========================================================
  when frequent calls  formatCode,this config rateLimiter.tryAcquire(1,0, TimeUnit.SECONDS);
does not work normly above the version 3.7.2,here is the doc
 
current version:3.7.2
   /**
     * Acquires the given number of <code>permits</code> only if all are available
     * within the given waiting time.
     *
     * <p>Acquires the given number of permits, if all are available and returns immediately,
     * with the value {@code true}, reducing the number of available permits by one.
     *
     * <p>If no permit is available then the current thread becomes
     * disabled for thread scheduling purposes and lies dormant until
     * the specified waiting time elapses.
     *
     * <p>If a permits is acquired then the value {@code true} is returned.
     *
     * <p>If the specified waiting time elapses then the value {@code false}
     * is returned.  If the time is less than or equal to zero, the method
     * will not wait at all.
     *
     * @param permits amount
     * @param timeout the maximum time to wait for a permit
     * @param unit the time unit of the {@code timeout} argument
     * @return {@code true} if a permit was acquired and {@code false}
     *         if the waiting time elapsed before a permit was acquired
     */
    boolean tryAcquire(long permits, long timeout, TimeUnit unit);

All code can see  (https://gitee.com/bootstrap2table/boot_master/tree/feature/boot-simple),
need help to fixed this bug,thanks!

**Comment by mrniko** [comment]
Could you provide some test case to reproduce the problem?

**Comment by mrniko** [comment]
Fixed! Thanks for report
