### ISSUE TITLE
redisson RRemoteService.getFreeWorkers api code issue?

### ISSUE THREAD

**Issue by AWaterColorPen** [redisson/redisson#2151]
it seems RRemoteService.getFreeWorkers api code issue?
from the [document](https://static.javadoc.io/org.redisson/redisson/3.10.7/org/redisson/api/RRemoteService.html#getFreeWorkers-java.lang.Class-) `RRemoteService.getFreeWorkers`, I get the follow description
```java
int getFreeWorkers(Class<?> remoteInterface)
Returns free workers amount available for tasks
```

code:
```
      RedissonClient client = Redisson.create(config);
      RRemoteService rpc = client.getRemoteService();
      System.out.println(rpc.getFreeWorkers())
      System.out.println(rpc.getFreeWorkers())
```
print:
```
100
0
```

Then I find the source code
[RedissonRemoteService.java](https://github.com/redisson/redisson/blob/redisson-3.11.0/redisson/src/main/java/org/redisson/RedissonRemoteService.java)

### Expected behavior
```java
    @Override
    public int getFreeWorkers(Class<?> remoteInterface) {
        Entry entry = remoteMap.get(remoteInterface);
        if (entry == null) {
            return 0;
        }
        return entry.getCounter().get();
    }
```

### Actual behavior
```java
    @Override
    public int getFreeWorkers(Class<?> remoteInterface) {
        Entry entry = remoteMap.remove(remoteInterface);
        if (entry == null) {
            return 0;
        }
        return entry.getCounter().get();
    }
```

are you kidding me？
why `remove`? it should be `get`
```
Entry entry = remoteMap.remove(remoteInterface);
```

**Comment by mrniko** [comment]
Sorry, I didn't see your PR right away.

Fixed! Thank for report
