### ISSUE TITLE
Redison Deployment error

### ISSUE THREAD

**Issue by suryathejamamidi** [redisson/redisson#2154]
09-Jun-2019 14:13:21.573 WARNING [main] org.apache.catalina.startup.Catalina.load Permissions incorrect, read permission is not allowed on the file.
09-Jun-2019 14:13:21.573 SEVERE [main] org.apache.catalina.startup.Catalina.start Cannot start server. Server instance is not configured.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=64m; support was removed in 8.0
09-Jun-2019 14:14:06.084 WARNING [main] org.apache.catalina.startup.Catalina.load Unable to load server configuration from [/usr/share/tomcat8/conf/server.xml]

After deploying the following error encounters Please help us to resolve.

**Comment by mrniko** [comment]
How it's related to Redisson?
