### ISSUE TITLE
Containerizing Reddison client for Tomcat

### ISSUE THREAD

**Issue by pabrahamusa** [redisson/redisson#2164]
I am thinking of the possibility of separating out the Reddison client from Tomcat container. Is there any way to do that? or do I always have to use RedissonSessionManager with Tomcat? I am using AWS Elasticache Redis. Thanks.

Redisson version - 3.10

**Comment by mrniko** [comment]
Is there a way to implement Tomcat Session Manager out of Tomcat?

**Comment by pabrahamusa** [comment]
Came across something like this CloudMembershipServiceMBean & wondering whether I can leverage this for Reddison Client? it will good if Reddison Pro have some thing like this.

https://tomcat.apache.org/tomcat-9.0-doc/api/index.html?org/apache/catalina/tribes/membership/cloud/CloudMembershipServiceMBean.html


<Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster">
<Channel className="org.apache.catalina.tribes.group.GroupChannel">
<Membership className="org.apache.catalina.tribes.membership.cloud.CloudMembershipService"/>
</Channel>
</Cluster>

**Comment by mrniko** [comment]
Correct me if I wrong, tribes nodes are completely independent and store state on their own. While all Redisson based Managers use Redis as common storage. Could you explain what benefits will you get with channel group implemented by Redisson?

**Comment by pabrahamusa** [comment]
I was initially thinking of de-coupling the logic to connect to Redis. However, as you have said it seems not necessary as we can define it in context.xml and even though it is tightly coupled it is the way how Tomcat works.

**Comment by pabrahamusa** [comment]
Also if Reddison client is leveraging the context.xml how it will support features like passing a Auth Password and In-Transit Encryption (TLS) ?

**Comment by mrniko** [comment]
through config defined in yaml or json format
