### ISSUE TITLE
All reads happening from Master even in ReadMode.SLAVE

### ISSUE THREAD

**Issue by ankita-dhyani** [redisson/redisson#2165]
### Expected behavior
Reads to be disctibuted across primary + replica servers for ReadMode.Master_Slave and ReadMode.Slave 

### Actual behavior
All the reads are going to primary server 

### Steps to reproduce or test case
We are using Aws elasticCache redis instance ( 1 primary 1 replica ) 
I have tried both useReplicated and useMaterSlave configs below 
config.useReplicatedServers()
                // use "rediss://" for SSL connection
                .setScanInterval(50)
                .addNodeAddress("redis://serverIp")
                .addNodeAddress("redis://serverIp")
                .setReadMode(ReadMode.SLAVE);

config.useMasterSlaveServers()
                // use "rediss://" for SSL connection
                .setMasterAddress("redis://primaryIp")
                .addSlaveAddress("redis://replicaIp")
                .setReadMode(ReadMode.SLAVE);

Also note I have tried both read modes ReadMode.SLAVE and ReadMode.MASTER_SLAVE

### Redis version
tried on two redis version same result 
4.10 
5.0.0 

### Redisson version
3.9.0
### Redisson configuration
config.useReplicatedServers()
                // use "rediss://" for SSL connection
                .setScanInterval(50)
                .addNodeAddress("redis://serverIp")
                .addNodeAddress("redis://serverIp")
                .setReadMode(ReadMode.SLAVE);

config.useMasterSlaveServers()
                // use "rediss://" for SSL connection
                .setMasterAddress("redis://primaryIp")
                .addSlaveAddress("redis://replicaIp")
                .setReadMode(ReadMode.SLAVE);

**Comment by mrniko** [comment]
Could you provide code to reproduce?

**Comment by ankita-dhyani** [comment]
Below is the code : get a key from map 
 RMapCache map = redisson.getMapCache("mapName");
        MerchandisingCacheEntry merchandisingCacheEntry = (MerchandisingCacheEntry) map.get("key");
        ArrayList<String> strings = (ArrayList<String>) merchandisingCacheEntry.getData();
        if(strings!=null){
            System.out.println("got the value" + strings);
        }

**Comment by mrniko** [comment]
RMapCache.get operations modifies data so it can't use slave node. This method updates idletimeout and lasttimeaccess parameters per entry.

You could use RMap object in this case.

**Comment by ankita-dhyani** [comment]
Thanks for the information , i am trying following now 
RMapCache map = redisson.getMap("mapName");
CacheEntry cacheEntry = (CacheEntry) map.get("key");

this gives me following error 
2019-06-13 19:39:27.595 ERROR 29108 --- [nio-7002-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.redisson.client.RedisException: Unexpected exception while processing command] with root cause

java.io.CharConversionException: Invalid UTF-32 character 0xbaff0000 (above 0x0010ffff) at char #2, byte #11)
	at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:195) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:158) ~[jackson-core-2.9.7.jar:2.9.7]

Entry for cache is bellow : 
"\x00\x00\x00\x00\x00\x00\x00\x00\xa7\x00\x00\x00\x00\x00\x00\x00{\"@class\":\"data.layer.cache.CacheEntry\",\"TTL\":[\"java.lang.Long\",14400000],\"data\":[\"java.util.ArrayList\",[]],\"valid\":false}" 

i am able to fetch the key from RMapCache without any issue .

**Comment by mrniko** [comment]
RMapCache map = redisson.getMap("mapName");

getMap returns `RMap` and not `RMapCache` object

**Comment by ankita-dhyani** [comment]
So the issue was as you mentioned   
` Also data stored in RMapCache couldn't be loaded in RMap object` . 
Thanks for the information , i checked LocaleCacheMap also cannot read from objects written in RMapCache . 
So we will have to figure out a way to move our data from RMapCache to RMap .

**Comment by mrniko** [comment]
Try RMapCache.getWithTTLOnly() or RMapCache.getAllWithTTLOnly() methods if you don't set idleTime parameter per entry and maxSize.

**Comment by gitrahul9** [comment]
@mrniko  Hi Nikita, can you please respond to above question, especially, the part where I want to understand 
if I can just replace `RMapCache` with `RMap` objects if I am not using any specific feature from RMapCache
