### ISSUE TITLE
if waitTime == -1 and leaseTime != -1，multiple threads get the lock at the same time

### ISSUE THREAD

**Issue by 543229143** [redisson/redisson#2172]
RedissonRedLock lock = new RedissonRedLock(lock1, lock2, lock3);
boolean res = lock.tryLock(-1, 10, TimeUnit.SECONDS);

if waitTime == -1  and leaseTime != -1，multiple threads get the lock at the same time

Thank you

**Comment by mrniko** [comment]
Fixed! Thanks for report
