### ISSUE TITLE
Hibernate 5.4.3 final

### ISSUE THREAD

**Issue by fortize** [redisson/redisson#2176]
Hi everybody

I'm trying to configure hibernate (5.4.3 final) with redisson (3.11.0). I use RedissonRegionFactory by default but i want that expiration.time_to_live be 10 seconds.

How should the correct configuration be?

hibernate.cache.redisson.RedissonRegionFactory.expiration.time_to_live = 10000 ???

Thanks in advanced.

**Comment by mrniko** [comment]
here is an example how to configure ttl for different hibernate regions:

https://github.com/redisson/redisson/tree/master/redisson-hibernate#default-region-configuration-used-for-all-caches-not-specified-in-configuration

**Comment by fortize** [comment]
Thanks for your answer i try with this property hibernate.cache.redisson.RedissonRegionFactory.expiration.time_to_live but when i check ttl value in redis the value isn't 10000 miliseconds.

**Comment by mrniko** [comment]
what kind of region do you use for `RedissonRegionFactory`?

**Comment by fortize** [comment]
I'm using org.redisson.hibernate.RedissonRegionFactory.

Thanks.

**Comment by mrniko** [comment]
This doesn't mean that region name is RedissonRegionFactory.

Use this instead: 
`hibernate.cache.redisson.entity.expiration.time_to_live`

**Comment by fortize** [comment]
Thanks i'm going to test.

**Comment by fortize** [comment]
These are my hibernate properties:

        <property name="hibernate.cache.region.factory_class">org.redisson.hibernate.RedissonRegionFactory</property>
        
        
		<property name="hibernate.cache.use_second_level_cache">true</property>
		<property name="hibernate.cache.use_query_cache">true</property>

		
		<property name="hibernate.cache.redisson.config">redisson.json</property>
		
		<property name="hibernate.cache.redisson.expiration.time_to_live">10000</property>
		<property name="hibernate.cache.redisson.entity.expiration.time_to_live">10000</property>
		<property name="hibernate.cache.redisson.collection.expiration.time_to_live">10000</property>
		<property name="hibernate.cache.redisson.query.expiration.time_to_live">10000</property>
		<property name="hibernate.cache.redisson.timestamps.expiration.time_to_live">10000</property>	
But i don't see ttl 10 i see -1
![image](https://user-images.githubusercontent.com/22702669/59666144-90251180-91b4-11e9-9c03-1ec1cf03d339.png)

![image](https://user-images.githubusercontent.com/22702669/59666217-b64ab180-91b4-11e9-8e27-f326cad65445.png)

![image](https://user-images.githubusercontent.com/22702669/59666253-c95d8180-91b4-11e9-8213-9e26e9064daa.png)

Thanks.

**Comment by mrniko** [comment]
Redisson uses RMapCache object for hibernate cache. This means it doesn't assign ttl to entire Map object rather uses zset to track Map entry expiration.
