### ISSUE TITLE
usage of weak ReferenceCacheMap on org.redisson.command.CommandAsyncService#CODECS  may cause frequent recreation of codec

### ISSUE THREAD

**Issue by jizhilong** [redisson/redisson#2177]
Hi,
   We noticed recently there are a lot of `org.nustaq.serialization.FSTConfiguration` instances around in our jvm service(with redisson 3.6 installed and FstCodec enabled).But according to the comment in [the javadoc](https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTConfiguration.java#L56), construction of `org.nustaq.serialization.FSTConfiguration` is very expensive, which should be cached and reused.
   After some digging in redisson's code, I get some clue, it may be caused by the implementation type of `org.redisson.command.CommandAsyncService#CODECS `. By design, codec construction should be limited, mostly old ones from the ConcurrentHashMap stored in the ReferenceCacheMap should get returned. But since `CODECS` is a weak reference cache map, the `ConcurrentHashMap` is possible to get removed by GC. And since there is only one possible strong reference to the `ConcurrentHashMap`, which is a local variable in `org.redisson.command.CommandAsyncService#getCodec`,  the possibility of CODECS getting cleared during a GC event is very large.
   the declaration and usage of `org.redisson.command.CommandAsyncService#CODECS ` is included in the following snippet.

```language=java

    private static final Map<ClassLoader, Map<Codec, Codec>> CODECS = ReferenceCacheMap.weak(0, 0);

    protected Codec getCodec(Codec codec) {
        if (codec == null) {
            return codec;
        }

        for (Class<?> clazz : BaseCodec.SKIPPED_CODECS) {
            if (clazz.isAssignableFrom(codec.getClass())) {
                return codec;
            }
        }

        Codec codecToUse = codec;
        ClassLoader threadClassLoader = Thread.currentThread().getContextClassLoader();
        if (threadClassLoader != null) {
            Map<Codec, Codec> map = CODECS.get(threadClassLoader); // this is the only possible strong reference to the ConcurrentHashMap stored in CODECS
            if (map == null) {
                synchronized (CODECS) {
                    map = CODECS.get(threadClassLoader);
                    if (map == null) {
                        map = new ConcurrentHashMap<Codec, Codec>();
                        CODECS.put(threadClassLoader, map);
                    }
                }
            }
            codecToUse = map.get(codec);
            if (codecToUse == null) {
                try {
                    codecToUse = codec.getClass().getConstructor(ClassLoader.class, codec.getClass()).newInstance(threadClassLoader, codec);
                } catch (NoSuchMethodException e) {
                    codecToUse = codec;
                    // skip
                } catch (Exception e) {
                    throw new IllegalStateException(e);
                }
                map.put(codec, codecToUse);
            }
        }
        return codecToUse;
    }
```

**Comment by wjjanning** [comment]
I have also confirmed an issue with this. The FstCodec constructor for (ClassLoader, Codec) as is used in this "getCodec" method creates another instance of FSTConfiguration, but does not copy all the attributes of the configuration over, namely the serialization registry. This in turn breaks registering your own serialization routines as your class cannot be located for readObject / instance deserialization. The only way around this at this point is to clone your own FstCodec class implementation and have it use the FSTConfiguration.getDefaultConfiguration() method instead of the createDefaultConfiguration() method being used. This ensures that the singleton FSTConfiguration is used in lieu of creating multiple FSTConfiguration instances.

`    public FstCodec(ClassLoader classLoader, FstCodec codec) {
        this(copy(classLoader, codec));
    }

    private static FSTConfiguration copy(ClassLoader classLoader, FstCodec codec) {
        FSTConfiguration def = FSTConfiguration.createDefaultConfiguration();
        def.setClassLoader(classLoader);
        def.setCoderSpecific(codec.config.getCoderSpecific());
        def.setCrossPlatform(codec.config.isCrossPlatform());
        def.setForceClzInit(codec.config.isForceClzInit());
        def.setForceSerializable(codec.config.isForceSerializable());
        def.setInstantiator(codec.config.getInstantiator(null));
        def.setName(codec.config.getName());
        def.setPreferSpeed(codec.config.isPreferSpeed());
        def.setShareReferences(codec.config.isShareReferences());
        def.setStreamCoderFactory(codec.config.getStreamCoderFactory());
        def.setVerifier(codec.config.getVerifier());
        return def;
    }
`

**Comment by mrniko** [comment]
@jizhilong 

Thanks for pointing out! I have changed map type to soft reference. Now entries are cleared only in case of low memory event and not after every GC.

**Comment by mrniko** [comment]
@wjjanning

Singleton config can't be used since different classloaders could be used for the same codec.

**Comment by mrniko** [comment]
@wjjanning 

FSTCodec copy method fixed!
