### ISSUE TITLE
Subscribe Timeout Exceptions - After master Re-election  

### ISSUE THREAD

**Issue by alexwatts** [redisson/redisson#2181]
### Expected behaviour

None, or fewer Exceptions (just during failover period)

### Actual behaviour

After a master re-election (and not otherwise) a constant percentage (about 1%) of the requests fail with this exception until the Redisson client is re-initialised manually with a pod bounce.

org.redisson.client.RedisTimeoutException: Subscribe timeout: (60000ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters. at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:167) ~[redisson-3.10.7.jar!/:na] at org.redisson.RedissonLock.lock(RedissonLock.java:183) ~[redisson-3.10.7.jar!/:na] at org.redisson.RedissonLock.lock(RedissonLock.java:157) ~[redisson-3.10.7.jar!/:na] at com.ajw.quondam.redis.RedisConnector.removeKey(RedisConnector.java:53) ~[classes!/:1.0-SNAPSHOT]

### Steps to reproduce or test case

I'm running 3 redis (master, slave, slave) alongside 3 sentinels.

 I'm running a constant load of requests through a redisson client which can run indefinitely without any issue. 

When I introduce a chaos script to trigger a failure of the master and thus a master re-election I start to see the errors, yet only for a very small percentage of the requests (but that percentage remains constant indefinitely until a manual restart of the redisson client happens)

Each request acquires and releases an RLock with a chance of collision with another request being 1 in 100.

If I lower the collision probability to be 1 in 10000 this problem almost completely disappears to the point where I lose only perhaps a single request, during the failover period (which is the expected behaviour for the higher collision case also)

### Redis version
redis_version:4.0.11

### Redisson version
3.10.7

### Redisson configuration

.setSubscriptionsPerConnection(20) 
.setSubscriptionConnectionPoolSize(200) 
.setRetryAttempts(15) 
.setRetryInterval(3000) 
.setSubscriptionConnectionMinimumIdleSize(50) 
.setSlaveConnectionPoolSize(200)
 .setMasterConnectionPoolSize(200)
 .setTimeout(15000)

.setNettyThreads(128)

**Comment by mrniko** [comment]
Fixed

**Comment by alexwatts** [comment]
@mrniko Thanks so much for a fast fix.

I'm trying to verify the fix but see these errors when running the unit tests using maven on OSX

REDIS RUNNER: Starting up default instance...
REDIS RUNNER: Making directory /tmp/redisson/7b8cf2ce-c18d-4e03-a271-dc4b62fda532
REDIS LAUNCH OPTIONS: [/Users/alex/redis-stab/redis-stable/src/redis-server, --dir, "/tmp/redisson/7b8cf2ce-c18d-4e03-a271-dc4b62fda532", --port, 54201]
REDIS PROCESS: 4906:C 20 Jun 2019 21:01:55.824 # Can't chdir to '"/tmp/redisson/7b8cf2ce-c18d-4e03-a271-dc4b62fda532"': No such file or directory

**Comment by alexwatts** [comment]
I was unable to push a branch to illustrate this, but I've written this failing test that replicates the issue I'm having.

``
package org.redisson;

import org.junit.*;
import org.redisson.api.RLock;
import org.redisson.api.RMap;
import org.redisson.api.RedissonClient;
import org.redisson.client.RedisClient;
import org.redisson.client.RedisClientConfig;
import org.redisson.client.RedisTimeoutException;
import org.redisson.client.protocol.RedisStrictCommand;
import org.redisson.config.Config;

import java.io.IOException;
import java.util.Random;
import java.util.UUID;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.IntStream;

public class RedissonLockFailoverHighContentionTest {

    @BeforeClass
    public static void beforeClass() throws IOException, InterruptedException {
        if (!RedissonRuntimeEnvironment.isTravis) {
            RedisRunner.startDefaultRedisServerInstance();
        }
    }

    @AfterClass
    public static void afterClass() throws IOException, InterruptedException {
        if (!RedissonRuntimeEnvironment.isTravis) {
            RedisRunner.shutDownDefaultRedisServerInstance();
        }
    }

    @Before
    public void before() throws IOException, InterruptedException {
        if (RedissonRuntimeEnvironment.isTravis) {
            RedisRunner.startDefaultRedisServerInstance();
        }
    }

    @After
    public void after() throws InterruptedException {
        if (RedissonRuntimeEnvironment.isTravis) {
            RedisRunner.shutDownDefaultRedisServerInstance();
        }
    }

    @Test
    public void testLockReliabilityInFailoverCase() throws Exception {
        RedisRunner.RedisProcess master = new RedisRunner()
                .nosave()
                .randomDir()
                .run();

        RedisRunner.RedisProcess slave1 = new RedisRunner()
                .port(6380)
                .nosave()
                .randomDir()
                .slaveof("127.0.0.1", 6379)
                .run();

        RedisRunner.RedisProcess sentinel1 = new RedisRunner()
                .nosave()
                .randomDir()
                .port(26379)
                .sentinel()
                .sentinelMonitor("myMaster", "127.0.0.1", 6379, 2)
                .sentinelDownAfterMilliseconds("myMaster", 750)
                .sentinelFailoverTimeout("myMaster", 1250)
                .run();

        RedisRunner.RedisProcess sentinel2 = new RedisRunner()
                .nosave()
                .randomDir()
                .port(26380)
                .sentinel()
                .sentinelMonitor("myMaster", "127.0.0.1", 6379, 2)
                .sentinelDownAfterMilliseconds("myMaster", 750)
                .sentinelFailoverTimeout("myMaster", 1250)
                .run();

        RedisRunner.RedisProcess sentinel3 = new RedisRunner()
                .nosave()
                .randomDir()
                .port(26381)
                .sentinel()
                .sentinelMonitor("myMaster", "127.0.0.1", 6379, 2)
                .sentinelDownAfterMilliseconds("myMaster", 750)
                .sentinelFailoverTimeout("myMaster", 1250)
                .run();

        Thread.sleep(5000);

        Config config = new Config();
        config.setNettyThreads(128);
        config.useSentinelServers()
                .addSentinelAddress(sentinel3.getRedisServerAddressAndPort()).setMasterName("myMaster")
                .setSubscriptionsPerConnection(20)
                .setSubscriptionConnectionPoolSize(200)
                .setRetryAttempts(15)
                .setRetryInterval(3000)
                .setSubscriptionConnectionMinimumIdleSize(50)
                .setSlaveConnectionPoolSize(200)
                .setMasterConnectionPoolSize(200)
                .setTimeout(15000);

        RedissonClient redisson = Redisson.create(config);

        ScheduledExecutorService executor1 = Executors.newScheduledThreadPool(1);
        ScheduledExecutorService executor2 = Executors.newScheduledThreadPool(1);
        ScheduledExecutorService executor3 = Executors.newScheduledThreadPool(1);
        ScheduledExecutorService executor4 = Executors.newScheduledThreadPool(1);
        ScheduledExecutorService executor5 = Executors.newScheduledThreadPool(1);

        Random r = new Random();
        String shard = UUID.randomUUID().toString();

        IntStream.range(0, 100).forEach(i -> {
            redisson.getMap(shard).put(i, 0);
        });

        AtomicBoolean exceptionDetected = new AtomicBoolean(false);

        Runnable rLockPayload =
                () -> {
                    try {
                        Integer randomLock = r.nextInt(100);  //If this number is tweaked for lower lock contention (eg. 1 in 10000) the problem is fixed
                        RLock lock = redisson.getLock(randomLock.toString());
                        try {
                            lock.lock(10, TimeUnit.SECONDS);

                            // Wait for 100 seconds and automatically unlock it after 10 seconds
                            boolean res = lock.tryLock(100, 10, TimeUnit.SECONDS);
                            if (res) {
                                try {
                                    RMap<String, Integer> map = redisson.getMap(shard);
                                    if (map.containsKey(randomLock)) {
                                        map.remove(randomLock);
                                    }
                                } finally {
                                    if (lock.isHeldByCurrentThread()) {
                                        lock.unlock();
                                    }
                                }
                            }
                        } catch (InterruptedException e) {
                            System.out.println("A request failed! " + e.getMessage());
                            if (lock.isHeldByCurrentThread()) {
                                lock.unlock();
                            }
                        } finally {
                            if (lock != null && lock.isHeldByCurrentThread()) {
                                lock.unlock();
                            }
                        }
                    } catch (Exception e) {
                        System.out.println("A request failed! " + e.getMessage());
                        exceptionDetected.set(true);
                    }
                };

        //5 separate schedulers, cant replicate with a single scheduler with a pool of 5 threads
        executor1.scheduleAtFixedRate(rLockPayload, 100, 50, TimeUnit.MILLISECONDS);
        executor2.scheduleAtFixedRate(rLockPayload, 100, 50, TimeUnit.MILLISECONDS);
        executor3.scheduleAtFixedRate(rLockPayload, 100, 50, TimeUnit.MILLISECONDS);
        executor4.scheduleAtFixedRate(rLockPayload, 100, 50, TimeUnit.MILLISECONDS);
        executor5.scheduleAtFixedRate(rLockPayload, 100, 50, TimeUnit.MILLISECONDS);

        System.out.println("Constant load for 5 minutes before failover... no Subscribe Timeouts...");
        Thread.sleep(java.time.Duration.ofSeconds(300).toMillis());

        RedisClientConfig masterConfig = new RedisClientConfig().setAddress(master.getRedisServerAddressAndPort());

        //Failover from master to slave
        try {
            RedisClient.create(masterConfig).connect().sync(new RedisStrictCommand<Void>("DEBUG", "SEGFAULT"));
        } catch (RedisTimeoutException e) {
            // node goes down, so this command times out waiting for the response
        }

        //Re-introduce master as slave like kubernetes would do
        RedisRunner.RedisProcess slave2 = new RedisRunner()
                .port(6381)
                .nosave()
                .randomDir()
                .slaveof("127.0.0.1", 6380)
                .run();

        Thread.sleep(java.time.Duration.ofSeconds(15).toMillis());

        System.out.println("Failover Finished, start to see Subscribe timeouts now. Can't recover this without a refresh of redison client ");
        Thread.sleep(java.time.Duration.ofSeconds(300).toMillis());

        Assert.assertFalse(exceptionDetected.get());

        redisson.shutdown();
        sentinel1.stop();
        sentinel2.stop();
        sentinel3.stop();
        master.stop();
        slave1.stop();
        slave2.stop();
    }

}

**Comment by mrniko** [comment]
Thanks for the provided test! Did you try

**Comment by alexwatts** [comment]
@mrniko Yes, this test also fails on redisson-3.11.1

**Comment by mrniko** [comment]
Fixed!

**Comment by alexwatts** [comment]
@mrniko Many thanks!, Verified this fix in master. Great work!!
