### ISSUE TITLE
redisson无法加锁，可以进行集合操作

### ISSUE THREAD

**Issue by ByteDanceWYQ** [redisson/redisson#2182]
### Expected behavior
 期待tryLock返回成功

### Actual behavior
实际每次加锁都会返回false
### Steps to reproduce or test case
每次加锁都会失败
### Redisson version
3.8到3.11都尝试了
### Redisson configuration
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoring: false
  dnsMonitoringInterval: 5000
threads: 10
nettyThreads: 10
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode :NIO

**Comment by mrniko** [comment]
Is there any code sample to reproduce the issue?

**Comment by ByteDanceWYQ** [comment]
查到原因了。redis集群的一些命令被运维重命名了，修改回来了就可以了

发自我的 iPhone
