### ISSUE TITLE
@Transactional and RLock.unlock()

### ISSUE THREAD

**Issue by horsen689** [redisson/redisson#2183]
1.大部分的教程里写的都是：
General usage：
> @Transactional
> try{
>     ①请求加锁（lock）
>     ②执行业务逻辑（business logic)
> }catch(Exception e){
>     //处理异常(handle exception)
> }finally {
>     ③解锁(unlock)
> }

写了一个小例子测试，打印的日志如下：
Write a small sample test and print the following log:

> 当前线程：：154 加锁成功（Current thread:: 154 locks successfully）
> Creating a new SqlSession
> Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a]
> JDBC Connection [com.mysql.jdbc.JDBC4Connection@1f7b84c6] will be managed by Spring
> ==>  Preparing: select * from test_me where id = 1 
> ==> Parameters: 
> <==    Columns: id, total, thread
> <==        Row: 1, 233, null
> <==      Total: 1
> Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a]
> 当前线程：：154 初始值>>>233 最新值>>>234
> Fetched SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a] from current transaction
> ==>  Preparing: update test_me set total = ? where id = 1 
>  Time：16 ms - ID：com.you.order.mapper.TestMeMapper.get
> Execute SQL：
>     select
>         * 
>     from
>         test_me 
>     where
>         id = 1
> ==> Parameters: 234(Integer)
> <==    Updates: 1
> Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a]
>  Time：29 ms - ID：com.you.order.mapper.TestMeMapper.update
> Execute SQL：
>     update
>         test_me 
>     set
>         total = ? 
>     where
>         id = 1
> 当前线程：：154 解锁（Current thread::154 unlock）
> Transaction synchronization committing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a]
> Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a]
> Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5a98c21a]

**》从上面可以看出来事务的提交是发生在解锁操作之后，这样是不是就存在一种可能性，在事务还没有提交完成以前，其他线程由于该线程已经解锁而发生并发问题？？？
（类似于@Transaction和synchronized的并发问题）**
**As can be seen from the above, transaction committing occurs after the unlocking operation. Is there a possibility that other threads will have concurrent problems because the thread has been unlocked before the transaction has been submitted?
(Similar to @transaction and synchronized concurrency issues)**

2.我用jmeter做了测试，却发现好像没有在解锁和提交事务之间发生并发问题，个人疑惑，希望大佬解解惑，谢谢😀
I tested it with JMeter and found no concurrency problems between unlocking and committing transactions.If you know, please let me know. Thank you.😀

**Comment by horsen689** [comment]
I need help~

**Comment by horsen689** [comment]
@mrniko

**Comment by wangbo911** [comment]
> @mrniko

你这一个是线程层面的锁，一个是数据库的锁，二者不相干。 你一个事务的方法，锁的是数据库，lock锁的时候对象，A方法执行完，lock释放后，B方法拿到锁执行时，A还没提交，只不过时数据库锁没释放而已，B方法执行还是会等待数据库锁释放。你都没搞清楚@transactional 是干嘛的。

**Comment by mstao** [comment]
把加锁的代码`lock.lock(); `放到 `try catch`外面，一般是这样写的吧：
 
class X {
    // ...
 
    public void m() {
      lock.lock();  // block until condition holds
      try {
        // ... method body
      } finally {
        lock.unlock()
      }
    }
 }}

**Comment by mstao** [comment]
上面的并发问题是存在的，我用的时候也碰到这个问题，在下面的m方法中（带事务）：

```
class X {
    // ...
   
   @Transactional
    public void m() {
      lock.lock();  // block until condition holds ①
      try {
        // ... method body
      } finally {
        lock.unlock()  //  ②
      }
    }
 }
```

假设现在有三个线程同时到达了`lock.lock(); `位置，此时线程1获取到了锁，其他两个线程需要等待；
当线程1走到` lock.unlock()`的位置，释放了锁，此时线程1的事务还未提交，但锁确实释放了，线程2可以获取到锁，执行业务逻辑。

假设你的业务逻辑里面有对于数据唯一性的要求，那么可能需要通过数据库中的锁来处理，比如 `for update`，`gap locks` 等。

**Comment by horsen689** [comment]
> > @mrniko
> 
> 你这一个是线程层面的锁，一个是数据库的锁，二者不相干。 你一个事务的方法，锁的是数据库，lock锁的时候对象，A方法执行完，lock释放后，B方法拿到锁执行时，A还没提交，只不过时数据库锁没释放而已，B方法执行还是会等待数据库锁释放。你都没搞清楚@transactional 是干嘛的。

...   你可以再读一遍我的问题，我强调的是啥....

**Comment by horsen689** [comment]
> 上面的并发问题是存在的，我用的时候也碰到这个问题，在下面的m方法中（带事务）：
> 
> ```
> class X {
>     // ...
>    
>    @Transactional
>     public void m() {
>       lock.lock();  // block until condition holds ①
>       try {
>         // ... method body
>       } finally {
>         lock.unlock()  //  ②
>       }
>     }
>  }
> ```
> 
> 假设现在有三个线程同时到达了`lock.lock(); `位置，此时线程1获取到了锁，其他两个线程需要等待；
> 当线程1走到` lock.unlock()`的位置，释放了锁，此时线程1的事务还未提交，但锁确实释放了，线程2可以获取到锁，执行业务逻辑。
> 
> 假设你的业务逻辑里面有对于数据唯一性的要求，那么可能需要通过数据库中的锁来处理，比如 `for update`，`gap locks` 等。

嗯，会存在的，我后面采用乐观锁单独处理控制数据库层面的，如果不存在那种极端问题，那就舒服了。谢谢回答~
