### ISSUE TITLE
RedissonSession setAttribute do not check if the value is null before removing the attribute name from removedAttributes collection

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#2187]
RedissonSession setAttribute do not check if the value is null before removing the attribute name from removedAttributes collection

### Redisson version
3.11.1-SNAPSHOT

**Comment by jchobantonov** [comment]
@mrniko In RedissonSession setAttribute looks like this:
```
    @Override
    public void setAttribute(String name, Object value, boolean notify) {
        super.setAttribute(name, value, notify);
        
        if (updateMode == UpdateMode.DEFAULT && map != null && value != null) {
            fastPut(name, value);
        }
        if (updateMode == UpdateMode.AFTER_REQUEST) {
            removedAttributes.remove(name);
        }
    }
```

but it should be like this:
```
    @Override
    public void setAttribute(String name, Object value, boolean notify) {
        super.setAttribute(name, value, notify);
        
        if (value != null) {
            if (updateMode == UpdateMode.DEFAULT && map != null) {
                fastPut(name, value);
            }
            if (updateMode == UpdateMode.AFTER_REQUEST) {
                removedAttributes.remove(name);
           }
       }
    }
```

because if the value is null then the super.setAttribute will actually invoke removeAttributeInternal where we are adding the key into removedAttributes collection so that AFTER_REQUEST we could remove the key - but because there is no check if the value is not null only then to remove the key from removedAttributes when we do setAttribute with null value and UpdateMode.AFTER_REQUEST actually we are not going to remove the key at the end as we will remove the key from removedAttributes

**Comment by mrniko** [comment]
Fixed! Thanks for the suggested changes
