### ISSUE TITLE
Command execution timeout for command: PING

### ISSUE THREAD

**Issue by ggeighty8** [redisson/redisson#2197]
I am experiencing a lot of command execution timeout exceptions mainly for PING as well as other operations intermittently.

I have been back and forth with AWS customer support and I **can conclusively say that there exist no CPU, memory and N/W constraints that were faced during any of the timeouts seen**.

Further, we have captured and analyzed the TCP dump on the client side to reveal nothing on the network side.

Server Setup:
Redis version: AWS elasticache redis 3.2.4. 
Redis node count: 1 Primary and 2 Replicas
Redis instance type: cache.r4.large

Client Setup:
Services connecting to the redis servers are running in docker containers on ec2 instances.
Redisson version: 3.10.6
Redisson configuration:

connectTimeout = 5000
command exection timeout  = 3000
master min connection pool size = 50
slave min connection pool size = 50

Exception seen on the client:
```
"org.redisson.client.RedisTimeoutException: Command execution timeout for command: PING, Redis client: [addr=redis://<aws-redis-endpoint>:6379]
\tat org.redisson.connection.RedisClientEntry.lambda$pingAsync$1(RedisClientEntry.java:85) ~[redisson-3.10.6.jar!/:?]
\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]
\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]
\tat io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]
\tat java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Any help in this regard is much appreciated.

**Comment by mrniko** [comment]
Did you try to follow these steps https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it ?

**Comment by ggeighty8** [comment]
Thanks, @mrniko for the reply. The mentioned FAQ was indeed the first thing I referred post which I increased the timeout and pool sizes to the above-mentioned values. Further, I have set the netty thread to 64 (forgot to mention in my initial post).

**Comment by mrniko** [comment]
did you try increase it further? 128 to threads and connection pool size?

**Comment by ggeighty8** [comment]
I have set the max connection pool size to 200 for slave and master each. I have not increased the netty thread count to more than 64. I was worried that there will be an increase in memory requirements (I have 18 microservices running on the same node, so 18*128 threads in all).

**Comment by mrniko** [comment]
Did you try to turn off ping timeouts?

**Comment by ramakantbadolia-tomtom** [comment]
@mrniko could you please let us know how this issue was fixed? I am facing currently the same issue in production and we currently keep  pingConnectionInterval: 30000.
