### ISSUE TITLE
Add ability to subscribe for keyevents

### ISSUE THREAD

**Issue by damacheng009** [redisson/redisson#220]
```
    Redisson redisson = getClient();
    RTopic<String> topic = redisson.getTopic("__keyevent@0__:expired");
    topic.addListener(new MessageListener<String>() {
        @Override
        public void onMessage(String channel, String msg) {
            // no output,but redis-cli command line tool can work
            System.out.println(channel);
            System.out.println(msg);
        }
    });

    RBucket<String> bucket = redisson.getBucket("message");
    bucket.set("someValue", 1, TimeUnit.SECONDS);
    Thread.sleep(1000 * 10);
    redisson.shutdown();
```

**Comment by mrniko** [comment]
which servers configuration do you use?

**Comment by damacheng009** [comment]
I make sure servers configuration is right because Jedis can work in this situation ：（

**Comment by mrniko** [comment]
i'll take a look at this issue after end of my vacation

**Comment by smigfu** [comment]
I currently have the same problem and I think the problems are the registered codecs: I have tried with the default (Jackson) as well as the SerializationCodec. In the first case you get a com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'set': was expecting ('true', 'false' or 'null') and in the later a java.io.StreamCorruptedException: invalid stream header: 7569645F.

The server-side notifications are neither serialized objects nor Json-encoded but rather plain String-Objects.

**Comment by mrniko** [comment]
with a new api you can do it much easier: `redisson.getTopic("__keyevent@0__:expired", StringCodec.INSTANCE)`

**Comment by smigfu** [comment]
That sounds like a good solution for the problem. Thanks :)

**Comment by mrniko** [comment]
Add `RExpirable.addExpireListener` method

**Comment by manikantag** [comment]
Any update on the `RExpirable.addExpireListener()` ? Thanks.

**Comment by manikantag** [comment]
@mrniko  `RExpirable.expire(long, TimeUnit)` is setting timeout (i.e., returning `true`) only when calling `expire()` after setting at least one value. For example, the below code will **not** set a expiry.

	@Test
	public void testHashExpiryCallback() throws InterruptedException {
		Config config = new Config();
		config
		.useSingleServer()
		.setAddress("redis://192.168.1.5:6379");

		RedissonClient redissonClient = Redisson.create(config);

		redissonClient.<String>getTopic("__keyevent@0__:expired", StringCodec.INSTANCE)
		.addListener(new MessageListener<String>() {
			@Override
			public void onMessage(String channel, String msg) {
				System.out.println(channel);
				System.out.println(msg);
			}
		});

		String keyName = "Test key " + Math.random();

		RMap<String, String> bucket = redissonClient.getMap(keyName);
		System.out.println("Expiry set: " + bucket.expire(1, TimeUnit.SECONDS));
		bucket.put("k1", "v1");
		bucket.put("k2", "v2");

		Thread.sleep(1000 * 3);
	}

If we set call the `expire()` after at least one `put()` call, `expire()` is returning `true` and and the `MessageListener` is working.

Is this behavior enforced by Redis? I couldn't find any documentation about this behavior. If yes, better to document this in `RExpirable.expire(long, TimeUnit)` method Javadocs and other similar methods. I can create a pull request with Javadoc changes if required. Thanks.

**Comment by mrniko** [comment]
@manikantag you're right it's impossible to use `expire` method on empty Redis data structures like map. This limitation should be reflected in javadocs. It would be great if you help with this

**Comment by manikantag** [comment]
@mrniko Once a key is expired, can we get the expired object in any callback?
like any keyevent message?

Somewhere I read/heard about *'you will get expired object for free' (by using some technique internally)*. But not sure if it is about Redisson.

**Comment by mrniko** [comment]
@manikantag 

Let's consider example you provided in https://github.com/redisson/redisson/issues/220#issuecomment-322108454
```java
public void onMessage(String channel, String msg) {
     System.out.println(channel);
     System.out.println(msg);
}
```

msg - is expired key itself. You can get an object just using `redisson.getMap(msg)` method.

**Comment by manikantag** [comment]
@mrniko I'm not sure if I misread your statement. Are you saying that we can get the **expired object** using `.getMap()`? How will it get the value once expired in Redis?

I tried using below code, but the original values are not coming. *(https://github.com/redisson/redisson/issues/220#issuecomment-322108454 code updated)*

	redissonClient.<String>getTopic("__keyevent@0__:expired", StringCodec.INSTANCE)
	.addListener(new MessageListener<String>() {
		@Override
		public void onMessage(String channel, String msg) {
			System.out.println(channel);
			System.out.println(msg);

			RMap<String, String> bucket = redissonClient.getMap(msg);
			System.out.println("k1: " + bucket.get("k1")); // -----> null
			System.out.println("k2: " + bucket.get("k2")); // -----> null
		}
	});

k1 & k2 value are coming as `null`, which is justifiable as it is expired in Redis.

**Comment by mrniko** [comment]
Oh, sorry, I had a hard day. You're right. It's not possible since object is not available anymore.

**Comment by mrniko** [comment]
You could use RMapCache object and add listener on entry expiration like this:
```java
RMapCache.addListener(new EntryExpiredListener() {

     void onExpired(EntryEvent<K, V> event) {
            K expiredKey = event.getKey();
            V expiredValue = event.getValue();
     }
});
```

**Comment by manikantag** [comment]
@mrniko Thanks for your inputs. `RMapCache` may not be of direct use in my case, but I'll try to make it work and will see if there is a better way. Thanks for all your efforts.

**Comment by mrniko** [comment]
`addListener` and `removeListener` methods added to `RObject`, `RObjectAsync`, `RObjectReactive`, `RObjectRx` objects. You can catch Deleted and Expired keyspace events published by Redis with `ObjectDeletedListener` and `ObjectExpiredListener`.

**Comment by vgcnerella** [comment]
i am using RMapCache.addListener(new EntryUpdatedListener()  and RMapCache.addListener( new EntryRemovedListener()

More than one client connects to the server from different machines to access the same mapCache .
When map is updated, only one of the client got notification in some cases.

Clients which did not receive updates for mapCache1 were getting the updates for the other mapCache2 during same time this indicates server connection is alive.

How to find what caused this issue. 

Simple client initialization code

Config config = new Config();
SingleServerConfig serverConfig = config.useSingleServer();
config.setCodec(new JsonJacksonCodec());
serverConfig.setConnectionPoolSize(poolSize);
serverConfig.setConnectionMinimumIdleSize(poolSize / 2);
serverConfig.setTimeout(5000);
serverConfig.setRetryAttempts(3);
serverConfig.setRetryInterval(1000);
serverConfig.setAddress("redis://server:port");
serverConfig.setDatabase(0);
RedissonClient rClient = Redisson.create(config);

mapCache = rClient.getMapCache("CACHE_NAME");

int listener = mapCache.addListener((EntryUpdatedListener) event -> {
String key = event.getKey().toString();
log.info("Updated Key : {} ", key);
});
int listener1 = mapCache.addListener((EntryRemovedListener) event -> {
String key = event.getKey().toString();
log.info("Removed Key {} ", key);
});

Any help very much appriciated.

Thanks

**Comment by mafei-dev** [comment]
you should use the ```getPatternTopic``` from the client. not the ```getTopic```.  this is the sample code.
```java
        this.client.getPatternTopic("__keyevent@*__:expired", StringCodec.INSTANCE)
                .addListener(String.class, new PatternMessageListener<String>() {
                    @Override
                    public void onMessage(CharSequence pattern, CharSequence channel, String msg) {
                        //
                    }
                })
                .subscribe();
```
note*  i am using reactive way. but in the normal way also it should be ```getPatternTopic``` and listener must be implemented from ```PatternMessageListener<T> ```

**Comment by mrniko** [comment]
Done
