### ISSUE TITLE
HGET implementation in Redisson

### ISSUE THREAD

**Issue by rajatppn** [redisson/redisson#2200]
Apologies if this is something simple that I've missed out
Have been trying to figure this out for a while but can't.
Trying to simply get the value associated with field in the hash stored at key as described in the documentation for [HGET](https://redis.io/commands/hget)
The code used is

```
RedissonClient redisson = Redisson.create();
RMap<String, String> map =  redisson.getMap("myhash");
System.out.println(map.get("a"));
```
However, it seems like this implementation fetches all values stored in all fields in 'myHash' instead of just the value stored in field 'a'. Unsure if this fetching of values happens during redisson.getMap ( More likely ) or map.get()

### Expected behavior
Redisson issues only one HGET and retrieves only the value of field 'a' in hash 'myhash'

### Actual behavior
Redisson seems to be fetching values of all fields in 'myhash'

### Steps to reproduce or test case
redis-cli
```
HSET myhash a valueofa
HSET myhash b valueofb
HSET myhash c valueofc
```

java
```
RedissonClient redisson = Redisson.create();
RMap<String, String> map =  redisson.getMap("myhash");
System.out.println(map.get("a"));
```
### Redis version
4.0.9

### Redisson version
3.10.7

### Redisson configuration
Default ( Testing on localhost )

**Comment by jackygurui** [comment]
`Redisson seems to be fetching values of all fields in 'myhash'` How did you manage to observe this behaviour, may I ask?

**Comment by rajatppn** [comment]
> `Redisson seems to be fetching values of all fields in 'myhash'` How did you manage to observe this behaviour, may I ask?

I inspected the value of map using IntelliJ's debugger and found all fields and their values in it

**Comment by jackygurui** [comment]
In your case, it is the debugger initiated the call and retrieved all the value from redis.

**Comment by MingJunDuan** [comment]
Why redisson not suport  fetach the value stored in field?

**Comment by mrniko** [comment]
@MingJunDuan 

Which command do you mean? You can find it here https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping

**Comment by MingJunDuan** [comment]
> @MingJunDuan
> 
> Which command do you mean? You can find it here https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping

hget, RMap.get("fieldKey").getAsync(), it retrieved all the hash field.

**Comment by mrniko** [comment]
RMap.getAsync() uses HGET command
