### ISSUE TITLE
Redisson 3.10.7 & FST 2.57 - Data is not cleared from ThraedLocal while using Serialization of FST library

### ISSUE THREAD

**Issue by ravinirmal10** [redisson/redisson#2206]
When we are saving some data in redis using FST codec then data is not cleared from ThreadLocal after data saved to the redis. This is causing issue of OutOfMemory as tomcat thread's ThreadLocalMap is filled with huge data which was used while FST serialization.

Detail: 
- Main code requested for putting some data in Redis.
- Redisson uses FST serialization to serialize data and then stores into Redis.
- FSTObjectOutput which was used while serialization has stored data in ThreadLocal object and it has not cleared data from ThreadLocal after it was saved in the Redis.

I can see ThreadLocalMap contains all the data which was used while FST serialization. Please see below snapshot of heap dump:
![image](https://user-images.githubusercontent.com/19212373/60440139-ca20f980-9c31-11e9-8050-ba564dfb1142.png)

Ideally it should clear the data from ThreadLocal, once the data stored in Redis.

### Sample Code:

      RMap<String, MyData> sampleMyClassMap;
      Config config = Config.fromJSON(new File("SingleServerConfig.json"));
      RedissonClient redisson = Redisson.create(config);

      Codec compositeCodec =
          new CompositeCodec(new StringCodec(), new LZ4Codec(), new SerializationCodec());
      sampleMyClassMap = redisson.getMap("MyData", compositeCodec);

      MyData myclassObj = new MyData();
      // Create some huge data and save it in Redis
      String a = "a";
      for (int j = 0; j < 26; j++) {
        a += a;
      }

      myclassObj.setName(a);

      sampleMyClassMap.put("Object", myclassObj);

      // Check heap dump before this call, we can see ThreadLocalMap will keep the serialized data in memory
      redisson.shutdown();

**Comment by mrniko** [comment]
FST serializer maintains cache to make process faster. In your case I would suggest to use SerializationCodec.

**Comment by jainyash88** [comment]
@mrniko  Is it possible to flush out the FSTOutputStream in some way from the application or from redisson code (possibly from LZ4Codec class) that holds the instance of FST encoder/decoder?

We can use default Java Serialization Codec however there is a tradeoff in performance as the default serialization is not as fast as FST.

**Comment by jainyash88** [comment]
@mrniko Is there any workaround for this if we still want to use FST?. Also just to understand, how do you plan to fix this. Will you be changing the default serialisation in redisson to Java or you would be clearing the thread locals that FST is using?

**Comment by mrniko** [comment]
> Is it possible to flush out the FSTOutputStream in some way from the application

I added `useCache` setting to FstCodec for this purpose. Also as replacement you could consider a new codec - JBoss Marshaller with defined ClassTable it works at the same speed as FST.
