### ISSUE TITLE
How to disable info logs in tomcat 9.0.21?

### ISSUE THREAD

**Issue by luiszimmermann** [redisson/redisson#2208]
In Tomcat 9.0.20 the setting in `logging.properties` is respected, but in 9.0.21, it is ignored.

### Expected behavior
Don't log INFO. Only Warning, Error, Severe.
### Actual behavior
INFO is logged.
```
02-Jul-2019 11:42:10.381 INFORMAÇÕES [http-nio-8080-exec-19] org.redisson.tomcat.RedissonSessionManager.findSession Session 1814A7D885CC689F6E5734E967E18B3D can't be found
```
### Steps to reproduce or test case
Deploy `.war` to tomcat with redisson installed and `org.redisson.tomcat.RedissonSessionManager.findSession.level = WARNING` added to `logging.properties` 
### Redis version
Tested in 5.0.5 and 5.0.3
### Redisson version
Tested in 3.10.7 and 3.11.1
### Redisson configuration
```yml
{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address": "redis://redis:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.FstCodec"
   },
   "transportMode":"NIO"
}
```

**Comment by mrniko** [comment]
Redisson uses SLF4J logging api so you need to add slf4j adapter for current tomcat logging.

**Comment by luiszimmermann** [comment]
> 
> 
> Redisson uses SLF4J logging api so you need to add slf4j adapter for current tomcat logging.

Will try that, but why in the Tomcat 9.0.20 only the setting in `logging.properties` is sufficient?
