### ISSUE TITLE
how to recover semaphore release failed 

### ISSUE THREAD

**Issue by HzjNeverStop** [redisson/redisson#2213]
if a semaphore release failed (shutdown or net not available)，it's there any way to let the server recover the permits? just like expired in Lock

**Comment by gmailisgone** [comment]
I remembered that the timeout can be set to a semaphore.

**Comment by mrniko** [comment]
Use `RPermitExpirableSemaphore.acquire(long leaseTime, TimeUnit unit)` method for this purpose.
