### ISSUE TITLE
renewExpiration not working when manually delete key

### ISSUE THREAD

**Issue by NeverGiveUp-Max** [redisson/redisson#2215]
### Expected behavior
renewExpiration  normal
### Actual behavior
1.Multiple spring boot services have been started
2.Get the lock every 2 seconds
3.After the lock is acquired, the lock key is removed through the redis client
4.After deletion, the first few times can be normal, or it may not update the expiration event
### Steps to reproduce or test case
```
 @Override
    public void run() {
        try {
            if (!isMaster) {
                isMaster = lock.tryLock(2, TimeUnit.SECONDS);
                if (isMaster) {
                    System.out.println("i am master");
                }
            } else {
                if (!lock.isLocked()) {
                    //when manual delete lock key
                    System.out.println("give up master");
                    isMaster = false;
                    TimeUnit.SECONDS.sleep(2);
                }
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```
### Redis version
2.8
### Redisson-spring-boot-starter
3.11.1  

### Redisson configuration
default

**Comment by NeverGiveUp-Max** [comment]
when manual delete lock key ,unlockAsync(long threadId)  opStatus and e  is null  throw  IllegalMonitorStateException. 
next time  same threadId  trylock(key,unit)  ,put  EXPIRATION_RENEWAL_MAP fail ,renewExpiration not work

is this a bug ? 
i think Before throwing IllegalMonitorStateException, you should do a cancelExpirationRenewal as well

**Comment by mrniko** [comment]
lock can't be unlocked if it was manually deleted. You need to unlock or delete it only through RLock methods.
