### ISSUE TITLE
batch.getKeys().deleteByPatternAsync does not work

### ISSUE THREAD

**Issue by joseph6x** [redisson/redisson#2216]
I am new in Redisson, so probably it is a dumb question. 
Please give it a look.

My code:

`   Config config = new Config();
    config.useSingleServer().setAddress("redis://" + redis.getContainerIpAddress() + ":" + redis.getMappedPort(6379));
    RedissonClient redisson = Redisson.create(config);

    //Random data
    RBucket<Object> bucket = redisson.getBucket("obj.0.a");
    bucket.set("a");
    bucket = redisson.getBucket("obj.0.b");
    bucket.set("b");
    bucket = redisson.getBucket("obj.0.c");
    bucket.set("c");
    bucket = redisson.getBucket("obj.0.d");
    bucket.set("d");

    //Batch delete by patern
    RBatch createBatch = redisson.createBatch();
    RFuture<Long> deleteByPatternAsync = createBatch.getKeys().deleteByPatternAsync("obj.0.*");
    createBatch.execute();
    Thread.sleep(10 * 1000);

    //Test batch delete
    Iterator<String> iterator = redisson.getKeys().getKeysByPattern("obj.0.*").iterator();
    if (iterator.hasNext()) {
      System.out.println("deleteByPatternAsync did not work");
    } else {
      System.out.println("deleteByPatternAsync worked");
    }
    
    //Syn Delete
    redisson.getKeys().deleteByPattern("obj.0.*");
    iterator = redisson.getKeys().getKeysByPattern("obj.0.*").iterator();
    
    //Test syn detelete
    if (iterator.hasNext()) {
      System.out.println("deleteByPattern did not work");
    } else {
      System.out.println("deleteByPattern worked");
    }`

### Expected behavior
Output:
deleteByPatternAsync worked
deleteByPattern worked

### Actual behavior
Output:
deleteByPatternAsync did not work
deleteByPattern worked

### Steps to reproduce or test case
I used testcontainers with the docker image 'redis:3.0.6'

### Redis version
3.0.6
### Redisson version
3.11.1

### Redisson configuration
SingleServer

**Comment by mrniko** [comment]
It's a bug, `createBatch.getKeys().deleteByPatternAsync` method doesn't work in batch.

**Comment by mrniko** [comment]
Fixed!
