### ISSUE TITLE
Local Cache implementation issues

### ISSUE THREAD

**Issue by Akshit62** [redisson/redisson#2220]
Hi, I was trying to implement local cache in my spring application and saw that eviction support is not supported in open source version. But that's okay, I tried to set cacheSize and syncStrategy in LocalCacheOptions, but that also didn't work. 
So my question is are all **options for the local cache are included in the redisson pro pack only**?
Because I was not able to configure the sync strategy. I set it to NONE, but regardless of that, it was syncing to other JVM machines.
Also, some other doubts, in some code provided in your documentation:
 **RLocalCachedMap<String, String> clearMap = redisson.getLocalCachedMap(cacheName,   LocalCachedMapOptions.defaults().cacheSize(1).syncStrategy(SyncStrategy.INVALIDATE));**
This doesnt compile in java spring app.
 Redis version - 5.0.4 

Redisson version  - 3.11.1

### Redisson configuration - default

Please provide the resolution asap!

**Comment by mrniko** [comment]
> This doesnt compile in java spring app.

Please check your dependencies. `RLocalCachedMap` object fully featured in open-source version. 

> I set it to NONE, but regardless of that, it was syncing to other JVM machines.

Ensure all applications deployed on other JVMs has the same config with NONE setting.

**Comment by Akshit62** [comment]
Let me explain what I implemented exactly. I started Redis server on machine A, and ran a java application on the same machine with code:  
```
	RedissonClient rad = Redisson.create();
		  RLocalCachedMap<Object, Object> map2 = rad.getLocalCachedMap("test4", 
	                LocalCachedMapOptions.defaults().cacheSize(1).syncStrategy(SyncStrategy.NONE));
		map2.put(3,4);
		System.out.println(map2.get(3));
```

Result: **4**
Then I connected this Redis server (on machine A) to different machine B, with the following code:
```
      Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://192.168.1.64:6379"); // ip of Machine A
        RedissonClient rad = Redisson.create(config);
        RLocalCachedMap<Object, Object> map2 = rad.getLocalCachedMap("test4",               LocalCachedMapOptions.defaults().syncStrategy(LocalCachedMapOptions.SyncStrategy.NONE));
        System.out.println(map2.get(3));
```

Result: **4**
and the results were the same. Shouldn't it be null for machine B? But it synced.

**Comment by mrniko** [comment]
All values are stored in Redis, SyncStrategy.NONE means that only local cache state won't be synced. But since all state stored in Redis you get the current state stored in Redis if it couldn't be located in local cache.

In your case you can't get null, since you already put 3, 4 map entry into local cache of machine A and Redis. On machine B it fetched from Redis.

**Comment by Akshit62** [comment]
Okay, thanks for the clarification. 
So, basically by setting SyncStrategy.NONE, it didn't save to MachineB JVM memory, but if we try to fetch it regardless, it will fetch it from Redis server itself. This sync configuration simply allows preventing other machines JVM's memory getting occupied with other unnecessary local caches. That's it, right?
