### ISSUE TITLE
Redisson 3.11.1 with Java 11 and JsonJacksonCodec throws FST errors

### ISSUE THREAD

**Issue by bjornharvold** [redisson/redisson#2221]
### Expected behavior
No errors in log

### Actual behavior
I start up my application and this error appears. Why am I getting this when I am not using FST codec?:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/Users/crash/.m2/repository/de/ruedigermoeller/fst/2.57/fst-2.57.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Steps to reproduce or test case
Java 11
Spring Boot 2.1.6
Spring Data
Redisson 3.11.1 Configured to use JsonJacksonCodec

`return new RedissonSpringCacheManager(this.redissonClient, "classpath:/cache-config.json", new JsonJacksonCodec(this.objectMapper));`

### Redis version
5.0.5

### Redisson version
3.11.1

**Comment by mrniko** [comment]
You need to exclude fst dependency manually
