### ISSUE TITLE
How to get the slots range of the ClusterNode

### ISSUE THREAD

**Issue by gaoran10** [redisson/redisson#2222]
### Expected behavior
I want to get the ClusterNodeInfo contains the slots range info.

### Actual behavior
Now i could only get the slots range info by the java reflect.

### Redis version
Redis 3.0.7

### Redisson version
3.10.6

### Redisson configuration
Config config = new Config();
ClusterServersConfig clusterServersConfig = config.useClusterServers();
for (String address : StringUtils.split(addresses, ',')) {
       String redisAddress = generateRedisAddress(address);
       clusterServersConfig.addNodeAddress(redisAddress);
 }
... other config

**Comment by mrniko** [comment]
Here is the code example:

```java
RedisCluster nodes = redisson.getRedisNodes(RedisNodes.CLUSTER);
RedisClusterMaster master = nodes.getMasters().iterator().next();
master.clusterSlots();
```
