### ISSUE TITLE
How can i use redisson If EVAL is disable?

### ISSUE THREAD

**Issue by luwanhua** [redisson/redisson#2225]
### Code
RLock lock = redissonClient.getLock("testLock");
lock.tryLock(10, 30, TimeUnit.SECONDS);

### Expected behavior
No error

### Actual behavior
ERROR o.s.s.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.redisson.client.RedisException: ERR unknown command 'EVAL'. channel: [id: 0xad5fed03, L:/x.x.x.x:58516 - R:x.x.x.x/x.x.x.x:6379] command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, Data_Etl_WrokService, 30000, 5221673a-494b-45f2-b117-e0c4dd4e3bdd:91]

### Redis version
4.0.7

### Redisson version
3.10.5

### Redisson configuration
{
  "singleServerConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":6000,
    "connectTimeout":10000,
    "timeout":10000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "address": "redis://x.x.x.x:6379",
    "subscriptionConnectionMinimumIdleSize":1,
    "subscriptionConnectionPoolSize":50,
    "connectionMinimumIdleSize":32,
    "connectionPoolSize":64,
    "database":0,
    "dnsMonitoringInterval":5000,
    "pingConnectionInterval":30000
  },
  "threads":0,
  "nettyThreads":0,
  "codec":{
    "class":"org.redisson.codec.JsonJacksonCodec"
  },
  "transportMode":"NIO"
}

###
How can I solve this problem if the DBA disable this command EVAL? He will not able this order for security reasons, he said.

**Comment by mrniko** [comment]
I'm afraid it's not possible. Since Redisson heavily uses this command.
