### ISSUE TITLE
evalShaAsync和evalSha执行相同的lua脚本，结果不一致

### ISSUE THREAD

**Issue by shaozhipeng** [redisson/redisson#2228]
### Expected behavior

1) "totalNum"
2) "2"
3) "totalEnergy"
4) "111.32"

The 4) should be a number as 111.32, and evalSha was right.

`
List<Object> obj = script.evalSha(RScript.Mode.READ_ONLY, sha, RScript.ReturnType.MAPVALUELIST, Arrays.asList("yyyyy"), String.valueOf(new BigDecimal(55.66).doubleValue()));
System.out.println(obj);
`

[totalNum, 2, totalEnergy, 111.32]

### Actual behavior

evalShaAsync result:

1) "totalNum"
2) "1"
3) "totalEnergy"
4) "\xfc\x05403.0"

The 4) contains \xfc\x0

RFuture<List<Object>> scriptFuture = script.evalShaAsync(RScript.Mode.READ_ONLY, sha, RScript.ReturnType.MAPVALUELIST, Arrays.asList(key), String.valueOf(pojo.getEnergy().doubleValue()));

scriptFuture.whenComplete((res, exception) -> {
// nothing to println on console
    System.out.println("res: "+res.isEmpty());
    System.out.println("exception.getMessage(): " + exception.getMessage());
    resultFuture.complete(Arrays.asList(res.toString()));
});

### Redisson version
3.11.0

### lua script

local k = KEYS[1]
local e = ARGV[1]
local isExists = redis.call('exists', k)
if not isExists or isExists == 0 then
  redis.call('hmset', k, 'totalNum', 1)
  redis.call('hmset', k, 'totalEnergy', e)
else
  redis.call('hmset', k, 'totalNum', tonumber(redis.call('hget', k, 'totalNum')) + 1)
  redis.call('hmset', k, 'totalEnergy', string.format("%.2f", tonumber(redis.call('hget', k, 'totalEnergy')) + tonumber(e)))
end
return redis.call('hgetall', k)

### Redisson Source Code

@Override
public <R> R evalSha(String key, Mode mode, String shaDigest, ReturnType returnType, List<Object> keys,
            Object... values) {
        return commandExecutor.get((RFuture<R>) evalShaAsync(key, mode, shaDigest, returnType, keys, values));
}

### Debug found... 这是个BUG😊
evalSha:org.redisson.client.codec.StringCodec
return evalAsync(source, true, codec, evalCommandType, script, keys, params);

evalShaAsync:org.redisson.codec.FstCodec
return script.evalShaAsync(key, mode, shaDigest, returnType, keys, values);

最终调用的位置是一样的，Codec不同。
Use getScript(Codec) instead
@Deprecated
带有Codec参数的方法。
然而并没有使用getScript(Codec)里的StringCodec，而是commandExecutor.getConnectionManager().getCodec()为org.redisson.codec.FstCodec。
下面构造方法里的codec为StringCodec。

public RedissonScript(CommandAsyncExecutor commandExecutor, Codec codec) {
        this.commandExecutor = commandExecutor;
        this.codec = codec;
}

@Override
public RScript getScript(Codec codec) {
        return new RedissonScript(connectionManager.getCommandExecutor(), codec);
}

public Config(Config oldConf) {
        setExecutor(oldConf.getExecutor());

        if (oldConf.getCodec() == null) {
            // use it by default
            oldConf.setCodec(new FstCodec());
        }
...
}

### whenComplete有问题，有时候偶尔会执行打印出结果，大部分时候都是没一点反应

scriptFuture.whenComplete(new BiConsumer<List<Object>, Throwable>() {
    @Override
    public void accept(List<Object> objects, Throwable throwable) {
        System.out.println(objects);
    }
});

**Comment by mrniko** [comment]
you need to use redisson.getScript(StringCodec.Instance); Like below:

```java
RScript script = redisson.getScript(StringCodec.Instance);
List<Object> obj = script.evalSha(RScript.Mode.READ_ONLY, sha, RScript.ReturnType.MAPVALUELIST, Arrays.asList("yyyyy"), String.valueOf(new BigDecimal(55.66).doubleValue())); 
System.out.println(obj);
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
