### ISSUE TITLE
Session behaviour mismatch - Redis + AFTER_REQUEST

### ISSUE THREAD

**Issue by JiriFrankCZ** [redisson/redisson#2230]
### Expected behavior
Redisson session manager should return actual value of value persisted to session.

### Actual behavior
Redisson returns null for every value previously saved.

### Steps to reproduce or test case
1) updateMode = AFTER_REQUEST + readMode = REDIS
2) session.setAttribute("abcd", "abcd")
3) session.getAttribute("abcd")  => null, but accroding to my opinion, it should return "abcd"

If I use readMode = MEMORY, it is somehow working but currently, I´m experiencing issues with synchronization => getting outdated session / not latest data. So I tried to use readMode = "REDIS". I would expect session to be on every request fully loaded from Session, during request are made to the memory object and at the end, it should be push to Redis. 

Maybe it is not a bug, not sure, whether it is intended or not. Otherwise, could you advise how to solve? Or tune config somehow to eleminate outdated session data?

### Redis version
3.0.503

### Redisson version
3.11.1

### Redisson configuration
{
  "singleServerConfig": {
    "idleConnectionTimeout": 10000,
    "connectTimeout": 10000,
    "timeout": 3000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "password": null,
    "subscriptionsPerConnection": 5,
    "clientName": "ppe-ib1",
    "address": "redis://localhost:6379",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "connectionMinimumIdleSize": 32,
    "connectionPoolSize": 64,
    "database": 0,
    "dnsMonitoringInterval": 5000
  },
  "threads": 16,
  "nettyThreads": 32,
  "codec": {
    "class": "org.redisson.codec.FstCodec"
  },
  "transportMode": "NIO"
}

**Comment by mrniko** [comment]
Here is the test which verifies your case:

https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-8/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java#L105

Could you provide any test case how to reproduce it?

**Comment by JiriFrankCZ** [comment]
@mrniko Difference will be in session manager setup in this test. Default is updateMode = DEFAULT not AFTER REQUEST. I think this is it.

**Comment by JiriFrankCZ** [comment]
Maybe it has similar point as [(https://github.com/redisson/redisson/issues/1868)]

**Comment by mrniko** [comment]
@JiriFrankCZ 

> Difference will be in session manager setup in this test. Default is updateMode = DEFAULT not AFTER REQUEST. I think this is it.

In this case test passes only if it not test the removal operation. Which fails since attribute will be removed after request finishes.

In other words, follow test passes:

```java
        TomcatServer server = new TomcatServer("myapp", 8080, "src/test/");
        server.start();

        Executor executor = Executor.newInstance();
        
        write(executor, "test", "1234");
        read(executor, "test", "1234");
        remove(executor, "test", "null");
        
        Executor.closeIdleConnections();
        server.stop();
```

**Comment by mrniko** [comment]
Your issue might happen if your read the same attribute written before, but it's not stored yet due to AFTER_REQUEST mode.

**Comment by JiriFrankCZ** [comment]
@mrniko Ok, makes sense, but shoul not return value even though it is not persisted to Redis? From my point of view, it´s quite standard case, that we write to the sessions something and later, int he same request we read from there.

**Comment by mrniko** [comment]
> Ok, makes sense, but shoul not return value even though it is not persisted to Redis?

This is possible only in MEMORY mode.

**Comment by mrniko** [comment]
Fixed! Thanks for report
