### ISSUE TITLE
java.io.IOException: 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by gmailisgone** [redisson/redisson#2231]
### Expected behavior
client should be shutdown without any exceptions

### Actual behavior
client report below exceptions
![image](https://user-images.githubusercontent.com/15872156/61391744-f3a77980-a8ef-11e9-89ff-ee0cf09ac28e.png)

### Steps to reproduce or test case
run RedissonManager.java in below attachment

[RedissonManager.zip](https://github.com/redisson/redisson/files/3402777/RedissonManager.zip)

### Redis version
redis-server-3.2.100

### Redisson version
redisson-all-3.7.5.jar

### Redisson configuration
![image](https://user-images.githubusercontent.com/15872156/61391862-39fcd880-a8f0-11e9-93cb-488e9d42e439.png)

### Redisson version
redis-cli connected to the same redis server during the test, no errors reported.

**Comment by jackygurui** [comment]
出现这个`远程主机强迫关闭了一个现有的连接`问题的原因通常是服务端的问题。服务端关机时`redis-cli`不会报错，仅在下次发送命令时才会报错。

**Comment by gmailisgone** [comment]
@jackygurui 
谢谢你的回复，但是
1. 服务器端没有任何操作，更没有关闭动作

2. redis-cli 在运行RedissonManager.java 之前，之后执行redis-cli 命令均没有任何错误,包括断开再重连。

3. “原因通常是服务端的问题” 
- 如果是redis server配置的参数问题: 能否给个调查的思路或参数？因为其他客户端没有遇到过类似的问题。

- 如果是redis server运行错误：目前只有redisson client报错，而且redisson client没做任何操作。

Thanks

**Comment by publisherfk** [comment]
同问这个问题，我的环境上面也是这样，启动之后，放在那不动，一堆“远程主机强迫关闭了一个现有的连接”报错

**Comment by jackygurui** [comment]
`远程主机强迫关闭了一个现有的连接`这个错误信息已经告知得和明确了，连接是被远端强制断开的，不是客户端主动申请断开的。出现这个问题的原因往往是在服务端，这里说的服务端并不仅仅是redis-server，还包括比如防火墙或代理等等隐藏在中间的各个环节，中间任何一个配置不当造成都有可能造成这个问题。

Redisson的连接池采用的是长连接，他的好处是可以减少频繁开关TCP连接带来的性能损耗，但是问题是有些防火墙的设置并不允许连接过长，当连接超过这个时间没有指令发送时，防火墙便会主动关闭这个连接，客户端就会产生这个报错。但是问题的根源并不在客户端这里。你也观察到报错的时候都是redisson没有任何操作的地方，这种现象也是从侧面证明了问题可能在别处。

这种现象仅仅影响长连接，对那些采用短连接的客户端来讲，并不受影响。或者其它客户端采用长连接但是选择内部消化掉这个报错，不打印出来，这是其他客户端的策略，我这里不方便评论。

Redisson提供了两个配置参数可以用来绕过防火墙的这个限制，一个是`keepAlive`另一个是`pingConnectionInterval`。第一个是通过TCP协议定时发送一个心跳包，用来告知远端服务这个连接需要继续保持。但有些时候防火墙仍然或选择强制关闭。第二个参数是通过Redis协议定时发送一个`ping`命令。某些情况下，你需要两个参数都设置才会有效果。

但是从你发的截图和重现代码里看的出来，当待机时间超过1秒钟时便会出现这个错误。就个人经验来讲，这个设置不太合理，否则大部分的性能都是损耗在保持连接上了，完全失去了长连接的优势。

**Comment by gmailisgone** [comment]
@jackygurui 

1. 抱歉，我没有把问题说清楚。

2. 标题所示问题，**只在调用“ client.shutdown ()” 时发生**，与中间等待多长时间，做什么事(sleep 1)无关。

3. 测试代码，redis-server运行在同一台windows主机，防火墙已经关闭，且没有任何其他安全相关的软件。

**Comment by jackygurui** [comment]
能把你的pom.xml发来看看吗？

**Comment by jackygurui** [comment]
@gmailisgone 能提供一下你的pom.xml或整个工程吗？我有理由怀疑项目里其他的组件造成了这个问题，而不是Redisson。从你发的日志来看，该报错出现的时候Redisson还处于初始化过程中，还在与服务端通信的时候，连接就被莫名的断开了。从代码来看，Spring在关闭容器时才触发的这个报错。有可能在Spring容器关闭过程中触发了其他的事件，造成服务端关机。

你可以做这两个实验看看问题在哪。
1. 在client.shutdown()以后再增加一个等待。
2. 就这段代码，独立在Spring以外运行。

**Comment by yizhixiaotaozi** [comment]
same problem. 同一台机器上起的单机redis，或者是远程的redis，junit 方法跑完，程序停止的时候就报这个错。

**Comment by ynfatal** [comment]
@yizhixiaotaozi 对，程序停止就会出现这种错误。请问你说的@Bean加在什么组件上，为什么要加呢？

**Comment by yizhixiaotaozi** [comment]
> @yizhixiaotaozi 对，程序停止就会出现这种错误。请问你说的@bean加在什么组件上，为什么要加呢？

因为RedissonClient这个类调shutdown方法就会报错，我加这个是不调shutdown，换成调toString(),并不能解决问题

**Comment by jackygurui** [comment]
@yizhixiaotaozi @ynfatal 能把你们的项目代码发一下吗？

**Comment by ynfatal** [comment]
@jackygurui 你可以写个demo试试。就整合redisson就行
```
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <!-- 引入 redisson 依赖 -->
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.11.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
```
这是我的pom.xml
```
public class RedissonTests extends Chapter31ApplicationTests {

    @Autowired
    private RedissonClient redisson;

    /**
     * 测试整合 Redisson
     * @throws InterruptedException
     */
    @Test
    public void fairLockTest() throws InterruptedException {
        RLock fairLock = redisson.getFairLock("anyLock");
        boolean isLock = fairLock.tryLock(100, 10, TimeUnit.SECONDS);
        if (isLock) {
            Thread.sleep(4000);
            fairLock.unlock();
        }
    }

}
```
这是Demo

**Comment by ynfatal** [comment]
补充一下，我使用了 Linux 版本的 redis 之后，就没这个问题了。无解

**Comment by gmailisgone** [comment]
@ynfatal 你提醒了我，我也用的是windows版本的redis, 

@jackygurui

**Comment by Tout-An** [comment]
配置文件如果配置了空的password,在执行rethrowIfFailed的时候会提示ERR Client sent AUTH, but no password is set. channel: [id: 0xb2a1b219, L:/192.168.0.25:57193 - R:192.168.0.223:6379] command: (AUTH), params: (password masked)，最后也会报"你的主机中的软件中止了一个已建立的连接。"，把空的password删了就好了

**Comment by Onglu** [comment]
@jackygurui 我本人写的测试用例执行完毕后，在调用 redissonClient.shutdown() 方法时也遇到了“**java.io.IOException: 远程主机强迫关闭了一个现有的连接**”这个错误，以下为本机的环境说明：
**System：Windows 10 v1903 64bit 
Redis Server：4.0.2
redisson：3.12.1
EventLoop：NIO
Junit：5.5.2
Spring：不依赖**

部分示例代码：
**config = Config.fromYAML(file);
config.useMasterSlaveServers().setKeepAlive(true).setPingConnectionInterval(10000);

// 进行缓存读写操作，且均已成功
...

// 关闭客户端，在此抛出异常：java.io.IOException: 远程主机强迫关闭了一个现有的连接。
redissonClient.shutdown();**

google 了一下，发现很多网友都提到自己遇到了这个问题，结合大家的评论，我粗略地分析了一下，总结了导致出现该问题的大概原因：
由于前面已经执行了客户端的关闭操作了，但 netty 的 FastThreadLocalRunnable 线程依旧还在非阻塞的套接字连接通道上继续监听 ACCEPT 事件，一旦收到此事件，就会在该通道上继续进行 read 操作，由于此时客户端已经关闭，此处的操作便会引发该错误异常。

@ynfatal 前面提到该错误只在 Windows 上出现，在 Linux 上不存在，我本人还未在 Linux 系统上运行过我的测试用例，因此，不好判定，不过，我觉得该错误应该是 netty 框架的设计缺陷（见下面代码片段）:
**if ((readyOps & (SelectionKey.OP_READ | SelectionKey.OP_ACCEPT)) != 0 || readyOps == 0) {
    unsafe.read();
}**

上面的代码在 NioEventLoop 中没有进行锁保护，也没有判断 NioChannel 是否可读，直接进行 read 操作容易引发 java.io.IOException 异常。
