### ISSUE TITLE
关于批量查询的性能问题

### ISSUE THREAD

**Issue by bayernjava** [redisson/redisson#2233]
使用pipeline进行批量查询，10万条查询命令，同样的配置：
        RBatch batch = redissonClient.createBatch(batchOptions);
        ids.stream().forEach(id -> {
            batch.getMapCache(“test”).getAsync(id);
        });
        BatchResult res = batch.execute();
getMapCache 查询缓存耗时： 42097ms
getMap 查询缓存耗时： 3929ms
使用jedis只需要 801ms

为什么性能差异这么大，使用的姿势不正确？求解释

**Comment by jackygurui** [comment]
10万条查询放到一个pipeline里面？
