### ISSUE TITLE
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=null] hasn't been discovered yet

### ISSUE THREAD

**Issue by muradzulfugarov** [redisson/redisson#2234]
Hello. I am using redisson to connect to redis cluster. However, while I am reading from redis (via redisson), I shutdown one of master instance. So I get this error:
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=null] hasn't been discovered yet

### Redis version
        5.0.5
### Redisson version
        3.11.1
### Redisson configuration
       config
                .useClusterServers()
                .setScanInterval(scanInterval)
                .setReadMode(ReadMode.SLAVE)
                .addNodeAddress("redis://10.5.12.10:30001")
                .setConnectTimeout(10000)
                .setRetryAttempts(10)
                .setIdleConnectionTimeout(10000)
                .setPingConnectionInterval(1000)
                .setTimeout(6000)
                .setFailedSlaveCheckInterval(3)
                .setFailedSlaveCheckInterval(30000)
                .setRetryInterval(3000)
                .setMasterConnectionPoolSize(100)
                .setSlaveConnectionPoolSize(100)
                .setFailedSlaveReconnectionInterval(3000)
                .setSubscriptionsPerConnection(5)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionConnectionPoolSize(50)
                .setSlaveConnectionMinimumIdleSize(10)
                .setMasterConnectionMinimumIdleSize(10)
                .setSubscriptionMode(SubscriptionMode.SLAVE)
                .setReconnectionTimeout(reconnectionTimeout);

**Comment by mrniko** [comment]
Could you set logging level to `TRACE` for `org.redisson` package and provide output?

**Comment by mrniko** [comment]
Fixed!

**Comment by muradzulfugarov** [comment]
How can I get and use fixed version?
