### ISSUE TITLE
Live Object List inside LiveObject not expiring

### ISSUE THREAD

**Issue by ajaykumarsaxena** [redisson/redisson#2235]
I have a java.util.List of LiveObjects under a LiveObject. Marking parent LiveObject expires it properly however LiveObjects under the List (inside Parent Live Object)  are not expired and i am explicitly expiring them, is this going to be supported any time soon if not supported already?
[A, B instances are LiveObjects]

```
@REntity
class A {
  @RId 
  String id;
  ..
   List<B>;
}

@REntity
class B{
  @RId 
  String id;
  ..
}
```

Also even if i set expiry of List Objects, List itself remains present in redis DB. 
How to handle such scenario as i don't see an option to add listener for RLiveObjectService persisted Objects?
Also is there a way to have the @RId field part of key (instead of enoded key) in Redis as i need to access the keys from another non java application?
Having key as "redisson_live_object:{fc093839}:com.test.abc.A:Id:java.lang.String" doesn't allow me to build search capability by Id outside java application.

### Redis version
4.0.14
### Redisson version
3.11.1
### Redisson configuration
Default

**Comment by jackygurui** [comment]
While LiveObject allows you to define complex structures through redisson reference, each LiveObject is still independent to each other. i.e. an instance B can exists in multiple instances of A. You need to control the expiriation of LiveObject individually. 

If you don't need the ability to access the nested structure independently, i.e. go straight to B without knowing A first, you can demote B to a standard POJO and they will expire along with A.

The @RId has to be encoded as part of the key name in order to differentiate multiple instances of the same type. You can supply your own [naming scheme](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/liveobject/resolver/NamingScheme.java) though, if you want to use a different format.

**Comment by ajaykumarsaxena** [comment]
@jackygurui   - Even if i demote B to standard POJO, List<B>  in instance of A gets stored as RedissonList which still remains in database, even when expiry set on instance of A.

To address it, I can try to create a RList for List<B> and mark expirable, assign in instance of A.  [I believe this will cause consistency issues due to expiration time mismatch at A vs RList level]
OR is there a better way ?

Thanks for your help.

**Comment by jackygurui** [comment]
> @jackygurui - Even if i demote B to standard POJO, List of B in instance of A gets stored as RedissonList which still remains in database, even when expiry set on instance of A.

You're right, java.util.List will be translated into a RedissonList automatically.

> To address it, I can try to create a RList for List of B and mark expirable, assign in instance of A. [I believe this will cause consistency issues due to expiration time mismatch at A vs RList level]
> OR is there a better way ?

If you want both the nest list and its contained items to be expired at the same time as the instance, this suggests to me that both the lifecycle of those three elements are coupled together. I think in this case LiveObject may not be the best suitable solution to your problem.

You'd better use standard POJO where all the nested elements are encoded together, sharing the same lifecycle.

**Comment by ajaykumarsaxena** [comment]
I have to use LiveObjects as this is distributed data grid, for now using RList but in future may replace redisson with custom implementation or implement it differently. Thanks

**Comment by jackygurui** [comment]
Redisson is still a distributed data grid without the use of LiveObject. LO is just one of the feature it provides. You can still use standard POJO with Redisson. In your case RBucket would be a better than LO.

**Comment by ajaykumarsaxena** [comment]
I am not clear how RBucket would be better in above situation. Can you explain....

**Comment by vortexthedev** [comment]
The problem still persists..... 
```
@Getter @Setter
@NoArgsConstructor
@EqualsAndHashCode(of = "id")
@REntity
public class SocialRequest {

    @RId(generator = UUIDGenerator.class)
    private String id;

    @RIndex
    private Long user;

    @RIndex
    private int code;

    @RIndex
    private UUID player;
    private String domain;
    private String client;
    private Integer version;
    private String ip;

    @RIndex
    private SocialType type;
    @RIndex
    private SocialAction action;
    private String payload;

    private long expiresAt;

}

RLiveObjectService service = ....getRedis().getService();
RLiveObject object = service.asLiveObject(service.persist(request));
object.expire(Duration.ofMillis(5000L));

```

**Comment by vortexthedev** [comment]
@mrniko
