### ISSUE TITLE
How to properly implement rate limiter hasPermits

### ISSUE THREAD

**Issue by efenderbosch** [redisson/redisson#2236]
Using Redisson latest.

We have queues with messages in them to be sent to 3rd party APIs. We are using the rate limit functionality to prevent 429s from the 3rd party APIs. When we do get a 429, we re-queue the message and try again later. After several retries, it ends up in a DLQ. To prevent this we wrote a ``hasPermits`` method on a wrapper around ``RRateLimiter`` and ``RAtomicLong`` where the atomic long points to the ``"{" + rateLimiterName + "}:value"`` key. We then use ``hasPermits`` to test whether we should poll the queue for messages or not.

We are now on our 3rd implementation of this method and want to double check it for correctness and/or ask that it be added to the ``RRateLimter`` interface.

Our 1st implementation simply checked ``RAtomicLong::get > 0`` . This failed because an uninitialized ``RRateLimter`` did not have the corresponding atomic long key and always returned 0.

2nd implementation:
 * call ``RAtomicLong::isExists``
 * If true we returned ``RAtomicLong::get > 0``
 * If false we called ``RRateLimter::tryAcquire(1)`` because ``tryAcquire`` would create the atomic long if it was not present with the correct value and TTL.
 * If ``tryAcquire`` succeeded, we put a token back with ``RAtomicLong:: incrementAndGet``. This caused an edge case where the TTL expired, the key was deleted by Redis and the ``incrementAndGet`` created a key without a TTL.  The value would then get decremented to 0 by the next ``tryAcquire`` and the rate limiter would never show any available tokens. This probably could have been prevented by using a Lua script or a batch/pipeline.

Our 3rd implementation seems correct, but we want to double check since we've had so many issues. We now:
 * check ``RAtomicLong::remainTimeToLive``
 * if -2 (not present), then return true as the next call to ``RRateLimter::tryAcquire`` will (re)create the atomic long with the correct number of permits
 * if -1 (key present, but no TTL), we set the TTL using the configured rate interval. This step would not normally be necessary except to fix the bad atomic long keys created by implementation 2 above.
 * return ``RAtomicLong::get > 0``

We think this 3rd implementation is now correct, but could be improved by using a Lua script or batch/pipeline to perform the check in a single round trip to Redis. Any feedback would be appreciated. If this could be added to the ``RRateLimter`` interface, that would be even better.

Thanks.

**Comment by mrniko** [comment]
`availablePermits` method added to `RRateLimiter` object in https://github.com/redisson/redisson/issues/2537
