### ISSUE TITLE
[CLuster Node]redisson.getPatternTopic only subscribe one master node channel

### ISSUE THREAD

**Issue by codehorde** [redisson/redisson#2237]
private static void testCluster() {
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress("redis://192.168.1.217:7001")
                .addNodeAddress("redis://192.168.1.217:7002")
                .addNodeAddress("redis://192.168.1.217:7003")
                .addNodeAddress("redis://192.168.1.218:8001")
                .addNodeAddress("redis://192.168.1.218:8002")
                .addNodeAddress("redis://192.168.1.218:8003");
        RedissonClient redisson = Redisson.create(config);
        try {
            RPatternTopic topic = redisson.getPatternTopic("__keyspace@0__:x:*", StringCodec.INSTANCE);
            topic.addListener(new PatternStatusListener() {
                @Override
                public void onPSubscribe(String pattern) {
                    System.out.println("onPSubscribe: " + pattern);
                }

                @Override
                public void onPUnsubscribe(String pattern) {
                    System.out.println("onPUnsubscribe: " + pattern);
                }
            });
            PatternMessageListener<String> listener = (pattern, channel, msg) ->
                    System.out.println("pattern: " + pattern + ",channel: " + channel + ",msg: " + msg);
            topic.addListener(String.class, listener);
        } catch (RuntimeException ex) {
            ex.printStackTrace();
        }
    }

### Expected behavior
subscribe all master node pattern topic, e.g.
`__keyspace@0__:x:1`
`__keyspace@0__:x:2`
`__keyspace@0__:x:3`
`__keyspace@0__:x:36`
......

### Actual behavior
only subscribe one master node pattern topic because only use one connection that node map hash slot `__keyspace@0__:x:*`
log:
[main] INFO org.redisson.Version - Redisson 3.11.2.SNAPSHOT
[main] INFO org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from 192.168.1.217/192.168.1.217:7001:
6c213fc49d07e3c940cf1fabbf99c8d66b6b8c80 192.168.1.217:7003 slave 2401416cba50d54b14f1d7dbf1bbdc4c960434a8 0 1563767080947 5 connected
db7f5d9ca84b5627fe39cedc75e89e1d8016c298 192.168.1.218:8001 master - 0 1563767079946 4 connected 0-5460
0d9f9ae91bc640c6c3662a030917eb4b4435572e 192.168.1.218:8003 slave 0237db0f35d31200c74a0d8974375a29790a39db 0 1563767079444 6 connected
2401416cba50d54b14f1d7dbf1bbdc4c960434a8 192.168.1.218:8002 master - 0 1563767080947 5 connected 10923-16383
0237db0f35d31200c74a0d8974375a29790a39db 192.168.1.217:7001 myself,master - 0 0 1 connected 5461-10922
070fa88701353622ad772c9340ed42d0c14fbc0a 192.168.1.217:7002 slave db7f5d9ca84b5627fe39cedc75e89e1d8016c298 0 1563767078943 4 connected

[redisson-netty-2-7] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.217:7002] added for slot ranges: [[0-5460]]
[redisson-netty-2-13] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 192.168.1.217/192.168.1.217:7002
[redisson-netty-2-6] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.217:7003] added for slot ranges: [[10923-16383]]
[redisson-netty-2-22] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 192.168.1.218/192.168.1.218:8001
[redisson-netty-2-20] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 192.168.1.217/192.168.1.217:7003
[redisson-netty-2-7] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 192.168.1.218/192.168.1.218:8002
[redisson-netty-2-2] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [redis://192.168.1.218:8003] added for slot ranges: [[5461-10922]]
[redisson-netty-2-11] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.218:8001 added for slot ranges: [[0-5460]]
[redisson-netty-2-11] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 192.168.1.218/192.168.1.218:8001
[redisson-netty-2-10] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.218:8002 added for slot ranges: [[10923-16383]]
[redisson-netty-2-10] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 192.168.1.218/192.168.1.218:8002
[redisson-netty-2-18] INFO org.redisson.connection.pool.PubSubConnectionPool - 1 connections initialized for 192.168.1.218/192.168.1.218:8003
[redisson-netty-2-2] INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 192.168.1.217/192.168.1.217:7003
[redisson-netty-2-17] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 192.168.1.217/192.168.1.217:7001
[redisson-netty-2-2] INFO org.redisson.cluster.ClusterConnectionManager - master: redis://192.168.1.217:7001 added for slot ranges: [[5461-10922]]
[redisson-netty-2-2] INFO org.redisson.connection.pool.MasterConnectionPool - 24 connections initialized for 192.168.1.217/192.168.1.217:7001
[redisson-netty-2-4] INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 192.168.1.218/192.168.1.218:8003
[redisson-netty-2-5] INFO org.redisson.connection.pool.SlaveConnectionPool - 24 connections initialized for 192.168.1.217/192.168.1.217:7002
onPSubscribe: `__keyspace@0__: x:*` 

### Redis version
3.2.11

### Redisson version
3.11.2.SNAPSHOT

### Redisson configuration
see code

**Comment by qeipwo** [comment]
I also encountered the same problem for you to solve it?

**Comment by codehorde** [comment]
like this, but i'd like redisson give an office answer.

       ```
        Collection<ClusterNode> masterNodes = clusterNodesGroup.getNodes(NodeType.MASTER);
        for (ClusterNode masterNode : masterNodes) {
            InetSocketAddress addr = masterNode.getAddr();
            RedisClientConfig redisClientConfig = new RedisClientConfig()
                    .setAddress(addr.getHostName(), addr.getPort())
                    .setPassword("xxx")
                    ;
            RedisClient redisClient = RedisClient.create(redisClientConfig);
            RFuture<RedisPubSubConnection> pubSubConnectionRFuture = redisClient.connectPubSubAsync();
            pubSubConnectionRFuture.onComplete(new BiConsumer<RedisPubSubConnection, Throwable>() {
                @Override
                public void accept(RedisPubSubConnection pubSubConnection, Throwable throwable) {
                    System.out.println("redisPubSubConnection: " + pubSubConnection + ", throwable: " + throwable);
                    if (throwable != null) {
                        throw new RuntimeException(throwable);
                    }
                    pubSubConnection.addListener(new RedisPubSubListener<Object>() {
                        @Override
                        public boolean onStatus(PubSubType type, CharSequence channel) {
                            System.out.println("type: " + type + ",channel: " + channel);
                            return true;
                        }

                        @Override
                        public void onMessage(CharSequence channel, Object message) {
                            System.out.println("channel: " + channel + ",message: " + message);
                        }

                        @Override
                        public void onPatternMessage(CharSequence pattern, CharSequence channel, Object message) {
                            System.out.println("pattern: " + pattern + ",channel: " + channel + ",message: " + message);
                        }
                    });
                    pubSubConnection.psubscribe(StringCodec.INSTANCE, new ChannelName("__keyspace@0__:x:*"));
                }
            });
        }
```

**Comment by qeipwo** [comment]
It seems that some code is missing. Can I see the whole thing?

**Comment by codehorde** [comment]
Updated, a sample use redisson native RedisClient.

**Comment by mrniko** [comment]
Fixed

**Comment by codehorde** [comment]
> Fixed

👌

**Comment by codehorde** [comment]
> It seems that some code is missing. Can I see the whole thing?

It finally worked out! 
https://github.com/redisson/redisson/commit/1dcce68d413126b5ef8673ed86459db74f740fae
