### ISSUE TITLE
RedisTimeoutException on HMGET

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#2238]
Hello @mrniko 

We are seeing a lot of RedisTimeoutExceptions with below log snippets

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://aw13-redis-001.aw13-redis.xzhogt.apse2.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1060763784 [redisClient=[addr=rediss://aw13-redis-001.aw13-redis.xzhogt.apse2.cache.amazonaws.com:6379], channel=[id: 0x013148d4, L:/10.13.137.15:56611 - R:aw13-redis-001.aw13-redis.xzhogt.apse2.cache.amazonaws.com/10.62.0.182:6379]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3a283224(failure: java.util.concurrent.CancellationException)], command=(HMGET), params=[{babd3080-24a9-4c0d-8c0f-fa2b8e6116d8_prod}_v40:MeasureTables, PooledUnsafeDirectByteBuf(ridx: 0, widx: 49, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 67, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 34, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 64, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 68, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 37, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 62, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 58, cap: 256), ...], codec=org.redisson.codec.CompositeCodec@e17b18bf], command: (HMGET), command params: [{babd3080-24a9-4c0d-8c0f-fa2b8e6116d8_prod}_v40:MeasureTables, PooledUnsafeDirectByteBuf(ridx: 0, widx: 49, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 67, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 34, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 64, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 68, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 37, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 62, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 58, cap: 256), ...] after 3 retry attempts org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=32, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://aw13-redis-001.aw13-redis.xzhogt.apse2.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1060763784 [redisClient=[addr=rediss://aw13-redis-001.aw13-redis.xzhogt.apse2.cache.amazonaws.com:6379], channel=[id: 0x013148d4, L:/10.13.137.15:56611 - R:aw13-redis-001.aw13-redis.xzhogt.apse2.cache.amazonaws.com/10.62.0.182:6379]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3a283224(failure: java.util.concurrent.CancellationException)], command=(HMGET), params=[{babd3080-24a9-4c0d-8c0f-fa2b8e6116d8_prod}_v40:MeasureTables, PooledUnsafeDirectByteBuf(ridx: 0, widx: 49, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 67, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 34, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 64, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 68, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 37, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 62, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 58, cap: 256), ...], codec=org.redisson.codec.CompositeCodec@e17b18bf], command: (HMGET), command params: [{babd3080-24a9-4c0d-8c0f-fa2b8e6116d8_prod}_v40:MeasureTables, PooledUnsafeDirectByteBuf(ridx: 0, widx: 49, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 67, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 34, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 64, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 68, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 37, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 62, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 58, cap: 256), ...] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:734) ~[redisson-2.15.2.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-common-4.1.33.Final.jar:4.1.33.Final]

Can you please help to explain what is going wrong here. Note that we are writing to the maps and then trying to read multiple keys from the local cached maps. We are using AWS Elasticache with redisson 2.15.2

**Comment by mrniko** [comment]
Try to follow these steps https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by jainyash88** [comment]
@mrniko Can you please explain if the exception trace represents a case of redisson client being overloaded(running out of netty threads / connections). Please note that we are not running any performance tests here and the load seems to be quite lighter.

**Comment by mrniko** [comment]
It doesn't depend on performance tests or load. Also as workaround you can use ByteArrayCodec so Redisson won't spent time in decoding and netty threads won't be busy with this task.

**Comment by jainyash88** [comment]
@mrniko Can ByteArrayCodec be replaced simply in place of FST codec? Will there be any performance and/or storage size implications in using ByteArrayCodec?

**Comment by mrniko** [comment]
The disadvantage of approach with ByteArrayCodec is that it allows to work only with byte array.

**Comment by jainyash88** [comment]
@mrniko Thanks for the suggestion but we are storing complex objects and are using FST and Java serialisation for the same. I am not sure if converting the objects to byte arrays and converting them back to objects while receiving them would be easier to implement or not.

I can see there is a property "decodeInExecutor" which is false by default. As per my understanding this will cause the decoding to happen in netty threads. 

Can enabling this property help here?

**Comment by mrniko** [comment]
yes, you can try this option either. Please give your feedback on it

**Comment by jainyash88** [comment]
@mrniko I tried setting decodeInExecutor to true. Now I can see that decoding is happening in redisson threads. Does it have any performance impacts. Also I think the no of redisson threads is defined by the threads parameter of redisson. What is the recommended setting for netty threads and redisson threads.  We currently have default settings enabled. Is there any guideline for keeping nettyThreads, redisson threads and the no of connections in some proportion.

**Comment by jainyash88** [comment]
@mrniko I can see the below default settings when I use Single Server mode

threads : 16
nettyThreads : 32
connectionpoolsize :64
minIdleconnections : 32

Is it advisable to keep the netty threads to be equal to or greater than the number of connections? In our case do you think it should be increased to 64.

As per my understanding each netty thread creates a tcp connection, so having the netty threads equal to 64 might help here.

Also if I enable decodeInExecutor, I would have to increase the Redisson threads configuration as now the decoding is performed in Redisson threads. 

Should the Redisson threads be equivalent to the netty threads here?

**Comment by mrniko** [comment]
> As per my understanding each netty thread creates a tcp connection, so having the netty threads equal to 64 might help here.

No, thanks to async nature of connection handling it's not required to use thread per connection. 

> Should the Redisson threads be equivalent to the netty threads here?

No, Redisson threads are used only in RTopic, RRemoteService and RExecutorService objects.

**Comment by vksaran843** [comment]
@mrniko @jainyash88 please can you share hmget psuedo code...how are you using hmget method....i am not able to find hmget method in redisson ... please can you help me
