### ISSUE TITLE
CROSSSLOT Keys in request don't hash to the same slot. channel

### ISSUE THREAD

**Issue by LakshmikanthQuickRide** [redisson/redisson#2240]
### Actual behavior

CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x2000086d, L:/xx.xx.xx.xx:62238 - R:xx.xx.xx.xx/xx.xx.xx.xx:6379] command: (MGET), params: [RO-61519108549746, RO-61519109582837, RO-61519109822542, RO-61519109835348, RO-61519094769904, RO-61519095943381, RO-61519110418000, RO-61519096754445, RO-61519111380355, RO-61519112387629, ...]

### Redisson configuration 

RedissonClient redisClient=redisClusterCacheUtils.getRedissonClient();
RBuckets rBuckets =redisClient.getBuckets();
Map<String,String> map = rBuckets.get(idsArray);

public RedissonClient getRedissonClient() {
log.debug("getRedissonClient()");
if(redisson ==null)
{
Config config = new Config();
config.useClusterServers().addNodeAddress("redis://"+redisCacheConfigurations.getServerIp()+":"+redisCacheConfigurations.getServerPort());
config.useClusterServers().setMasterConnectionMinimumIdleSize(redisCacheConfigurations.getMinIdle());
config.useClusterServers().setMasterConnectionPoolSize(redisCacheConfigurations.getMaxConnections());
config.useClusterServers().setSlaveConnectionMinimumIdleSize(redisCacheConfigurations.getMinIdle());
config.useClusterServers().setSlaveConnectionPoolSize(redisCacheConfigurations.getMaxConnections());
config.useClusterServers().setConnectTimeout(redisCacheConfigurations.getConnectTimeoutInMillis());
config.useClusterServers().setTimeout(redisCacheConfigurations.getConnectTimeoutInMillis());
config.useClusterServers().setClientName(redisCacheConfigurations.getClientName());
redisson = Redisson.create(config);
}
return redisson;
}

**Comment by mrniko** [comment]
Fixed! Thanks for report
