### ISSUE TITLE
RX and Reactive Set Intersection `java.lang.ClassCastException`

### ISSUE THREAD

**Issue by alexguzun** [redisson/redisson#2241]
### Expected behavior
`Single<Integer> intersection(String... names)`
### Actual behavior
`Single<Long> intersection(String... names)`
### Steps to reproduce or test case
NA
### Redis version
NA
### Redisson version
3.11.1
### Redisson configuration
NA

Both Rx and Reactive versions of `RSet` throw `java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')` when using `intersection(String... names)` method.

I think this is happening because `org.redisson.RedissonSet#intersection` returns an `int`

**Comment by alexguzun** [comment]
I will soon have an PR ready with fix. Running unit tests now (it's slow)

**Comment by mrniko** [comment]
Please apply your PR against master branch

**Comment by alexguzun** [comment]
New PR oppened: https://github.com/redisson/redisson/pull/2247

**Comment by alexguzun** [comment]
@mrniko I am confused. The branch 3.0.0 is for version 3.x. The first PR was approved, merged and then reverted. Can you explain exactly in which branch to fix this issue?
