### ISSUE TITLE
ERR This instance has cluster support disabled.

### ISSUE THREAD

**Issue by eankit** [redisson/redisson#2243]
### Redisson configuration

Adding stacktrace

at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:333)
2cb44108b3c1 PROFILE=dev 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:128)
2cb44108b3c1 PROFILE=dev 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)

**Comment by mrniko** [comment]
This error had been reported by Redis. Please configure your Redis node properly.
