### ISSUE TITLE
请问如何配置哨兵集群?

### ISSUE THREAD

**Issue by lmxy1990** [redisson/redisson#2245]
我看了配置集群的,配置哨兵的.
例如我现在有三个节点:127.0.0.1:26379, 127.0.0.1:26380, 127.0.0.1:26381
我想把127.0.0.1:26379, 127.0.0.1:26380,作为集群来使用, 127.0.0.1:26381做冗余(哨兵)
需要怎样配置呢?

**Comment by lmxy1990** [comment]
另外,请问集群模式下,如果某个节点断开了,是否整个集群不可用了?

**Comment by wangbo911** [comment]
wiki文档上就有自己看
