### ISSUE TITLE
Expect redisson-spring-boot-starter to be more optimized

### ISSUE THREAD

**Issue by Comven** [redisson/redisson#2251]
the redisson-spring-boot-starter ‘s configuration is too simple，Configuration files have to be introduced to configure more features。such as `codec`、`connectionPoolSize` and timeout，It's too complicated to introduce more configuration files, Hopefully it will optimize the configuration in spring-boot environment.
Thank you  verify much!

**Comment by mrniko** [comment]
All Redisson settings could be defined through redisson.yaml or redisson.json config. Path to it should be specified in `spring.redis.redisson.config` spring boot setting
