### ISSUE TITLE
RedissonRedLock 最大续租次数是否有计划支持？

### ISSUE THREAD

**Issue by xkrivzooh** [redisson/redisson#2254]
请问redisson中的RedissonRedLock有考虑增加锁的最大续租时间的限制，或者锁的最大续租次数的限制么？

目前锁的续租是没有最大续租次数限制或者说没有最大续租时间限制的。我们想支持一下锁的最大续租时间，然后发现目前`RedissonLock`类中的`renewExpiration`方法是`private`访问权限的，使得我们不能简单的override它。

因为`redlock`算法描述中提到: `redis延迟重启`的问题，但是具体延迟多久在一定程度上其实是受到锁的最大续租时间限制的。

所以问一下你们是否有这方面的考虑。

**Comment by xkrivzooh** [comment]
rename title

**Comment by wangbo911** [comment]
你说的RedLock的续租时间是说的 trylock方法里的 watchlogtime参数吧，没有设置锁过期时间的情况下，比如我程序还在处理中，超过这个watchlogtime，会继续增加锁过期时间。

**Comment by wangbo911** [comment]
> 请问redisson中的RedissonRedLock有考虑增加锁的最大续租时间的限制，或者锁的最大续租次数的限制么？
> 
> 目前锁的续租是没有最大续租次数限制或者说没有最大续租时间限制的。我们想支持一下锁的最大续租时间，然后发现目前`RedissonLock`类中的`renewExpiration`方法是`private`访问权限的，使得我们不能简单的override它。
> 
> 因为`redlock`算法描述中提到: `redis延迟重启`的问题，但是具体延迟多久在一定程度上其实是受到锁的最大续租时间限制的。
> 
> 所以问一下你们是否有这方面的考虑。
增加锁的续租次数没有意义，你既然要个最大次数，那为啥不设置最大超时时间不就好了。 续租本来就是为不设置超时时间都得情况下。

**Comment by DarrenJiang1990** [comment]
那里可以设置看门狗的最多续租次数，不能无限制延长时间去获取锁吧
