### ISSUE TITLE
redis实例切换后并没有重连

### ISSUE THREAD

**Issue by AsukaSun** [redisson/redisson#2257]
### Expected behavior
redis实例切换后，redisson会重连
### Actual behavior
似乎并没有重连
### Steps to reproduce or test case
redis实例切换后，报出host xxx disconnected due to failedAttempts=3 limit reached的错误，但却似乎一直没有去重连，后续有接口再尝试访问redis就会报
org.redisson.client.RedisConnectionException:MasterConnectionPool no available Redis entries.  Disconnected hosts: [xxxx]\nat org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:196)\nat org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:31)\nat org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:419)\nat 
的错
### Redis version
4.0
### Redisson version
3.5.4
### Redisson configuration
<redisson:client
            id="standalone"
            name="aliasName1,aliasName2"
            threads="8"
            netty-threads="8"
            codec-ref="jsonJacksonCodec"
            codec-provider-ref="defaultCodecProvider"
            use-linux-native-epoll="false"
            redisson-reference-enabled="true"
            resolver-provider-ref="defaultResolverProvider"
            executor-ref="executors"
            event-loop-group-ref="nioEventLoopGroup" >
        <redisson:single-server
                address="redis://${redis.hostname}:${redis.port}"
                subscription-connection-minimum-idle-size="1"
                subscriptions-per-connection="50"
                subscription-connection-pool-size="50"
                connection-minimum-idle-size="10"
                connection-pool-size="64"
                idle-connection-timeout="10000"
                connect-timeout="10000"
                timeout="${redis.timeout}"
                ping-timeout="3000"
                retry-attempts="3"
                retry-interval="1500"
                reconnection-timeout="3000"
                failed-attempts="3"
                database="${redis.database}"
                password="${redis.password}"
                client-name=""
                ssl-enable-endpoint-identification="true"
                ssl-keystore=""
                ssl-keystore-password=""
                ssl-provider="JDK"
                ssl-truststore=""
                ssl-truststore-password=""
                dns-monitoring="false"
                dns-monitoring-interval="5000"/>
    </redisson:client>

**Comment by AsukaSun** [comment]
<xsd:attribute name="reconnection-timeout" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
        Reconnection attempt timeout to Redis server then it has been excluded
        from internal list of available servers.

        On every such timeout event Redisson tries
        to connect to disconnected Redis server.

        @see #failedAttempts

        Default: 3000
             ]]></xsd:documentation>
按照配置的说明，我理解是每隔3秒会重连一次，但实际上并没有？

**Comment by jackygurui** [comment]
redis实例切换是怎么实现的？

**Comment by wangbo911** [comment]
> <xsd:attribute name="reconnection-timeout" type="xsd:string">
> xsd:annotation
> xsd:documentation<![CDATA[
> Reconnection attempt timeout to Redis server then it has been excluded
> from internal list of available servers.
> 
> ```
>     On every such timeout event Redisson tries
>     to connect to disconnected Redis server.
> 
>     @see #failedAttempts
> 
>     Default: 3000
>          ]]></xsd:documentation>
> ```
> 
> 按照配置的说明，我理解是每隔3秒会重连一次，但实际上并没有？

你用的配置是单节点模式的，会切换才怪。
你看看你配置的这个位置：

//
<redisson:single-server
address="redis://${redis.hostname}:${redis.port}"
//
