### ISSUE TITLE
Support for rediss:// when using Sentinel

### ISSUE THREAD

**Issue by dsmithsl** [redisson/redisson#2261]
Just wondering if Redisson officially supports the use of `rediss://` for Sentinel? I can't see the use of that protocol mentioned in the Sentinel setup documentation whereas it is for cluster mode. Also it seems like there are some places where the `redis://` protocol is hardcoded in Sentinel-related code.

For example in [on line 486 of SentinelConnectionManager.java](https://github.com/redisson/redisson/blob/b357e62a5dd0816fd9a03405be256ffbe335e67d/redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java#L486):

```java
    private String createAddress(String host, Object port) {
        if (host.contains(":")){
            String pureHost = host.replaceAll("[\\[\\]]", "");
            host = applyNatMap(pureHost);
            if (host.contains(":")) {
                host = "[" + host + "]";
            }
        } else {
            host = applyNatMap(host);
        }
        return "redis://" + host + ":" + port;
    }
```

**Comment by mrniko** [comment]
Done! Thanks for suggestion
