### ISSUE TITLE
Large number of Connections opened to redis in case of load

### ISSUE THREAD

**Issue by kumar-pratyaksh** [redisson/redisson#2265]
### Expected behavior
Connection count should remain stable even during load due to connection pooling.

### Actual behavior
When the application is load, there is a spike in number of connections to redis. This starts causing redis timeout exceptions in the application.

### Cache manager implementation
Following is how we have implemented the cache manager which is used to handle data transfer to and from redis.

Every time there is a request to get and put things from/in cache we get an instance of RMapCache from redisClient and use that for the operation.

This map is not singleton or pooled. Since this map is instantiated for every request is this causing the spike in connections?

![image001](https://user-images.githubusercontent.com/25146461/63145855-9f8ad480-c016-11e9-91c1-0ee26c3369f7.png)

**Comment by mrniko** [comment]
Could you share Redisson configuration and any code sample to reproduce the issue?

**Comment by johnou** [comment]
@kumar-pratyaksh you are probably using sync operations, look at the async api.

**Comment by kumar-pratyaksh** [comment]
> Could you share Redisson configuration and any code sample to reproduce the issue?

Hi @mrniko 

Following is the code snippet we are using to get the map instance 

`
private static RMapCache<Object, Object> getCache(String cacheMap) {
		if (redissonClient == null) {
			LOGGER.debug("New Redisson connection created");
			createRedissonClient();
		}
		return redissonClient.getMapCache(cacheMap);
	}
`

Following is the configuration

`---
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 10000
  retryAttempts: 5
  retryInterval: 1500
  reconnectionTimeout: 10000
  failedAttempts: 5
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 500
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 200
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 200
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  (@@@@@@@@)
  (@@@@@@@@)
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false
`

**Comment by kumar-pratyaksh** [comment]
> @kumar-pratyaksh you are probably using sync operations, look at the async api.

@johnou Yes all our operations are sync. Will it still be causing this spike in number of connections.

**Comment by johnou** [comment]
@kumar-pratyaksh yes it will.

**Comment by mrniko** [comment]
as option you can reduce connection pool size or set `*ConnectionPoolSize` = `*ConnectionMinimumIdleSize`
