### ISSUE TITLE
when I unlock the lock, accept an exception,

### ISSUE THREAD

**Issue by MrIronMan** [redisson/redisson#2269]
RLock lock = client.getLock(LockKeyResource.getRedisClassTeacherBalancerLock(classId));
lock.lock(15, TimeUnit.SECONDS);
        try {

            // do buesiness

        } finally {
            // 释放锁
            lock.unlock();
        }

exception: java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 9c345276-aa6e-44c1-b478-bf4b14ba1498 thread-id: 805, dubbo version: 2.6.0, current host: 10.0.6.196
java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 9c345276-aa6e-44c1-b478-bf4b14ba1498 thread-id: 805

somebody can help me ?

**Comment by jackygurui** [comment]
能给个重现吗？或者详细讲一下这个问题出现的具体情况，比如是否有节点切换，网络延迟等等细节。

**Comment by Anselzhao** [comment]
redis version: 3.0.504
redisson version：3.11.1

setLockWatchdogTimeout will cause the IllegalMonitorStateException

`
public class LockTest {

    public static final String KEY = "LOCK_KEY";
    
    private static void test() {
        Config config = new Config();
        // setLockWatchdogTimeout this will cause the IllegalMonitorStateException "attempt to unlock lock, not locked by current thread by node id"
         config.setLockWatchdogTimeout(30);
        config.setCodec(new org.redisson.client.codec.StringCodec());
        config.useSingleServer().setAddress("redis://127.0.0.1:6379");
        config.useSingleServer().setConnectionPoolSize(100);
        config.useSingleServer().setConnectionMinimumIdleSize(3);
        RedissonClient redisson = Redisson.create(config);
        RLock lock = redisson.getLock(KEY);
        lock.lock();
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        lock.unlock();
    }

    public static void main(String[] args) {
        test();
    }
}`
