### ISSUE TITLE
延时队列超时

### ISSUE THREAD

**Issue by yzpangu** [redisson/redisson#2270]
java.lang.RuntimeException: org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params:

**Comment by jackygurui** [comment]
请参阅[FAQ第一条](https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it)
