### ISSUE TITLE
RLocalCachedMap  clearLocalCache  getClearSemaphore

### ISSUE THREAD

**Issue by chengzyzy** [redisson/redisson#2273]
### Redisson configuration

org.redisson.RedissonLocalCachedMap#clearLocalCacheAsync

当我使用RLocalCachedMap clearLocalCache  在redis 中会产生许多以下数据
When I use RLocalCachedMap clearLocalCache , generate many  data in redis
![image](https://user-images.githubusercontent.com/30223515/63483867-4ddbc180-c4d0-11e9-95e8-b05a9d55715a.png)
查看源码 
view source code  I Found RSemaphore  
![image](https://user-images.githubusercontent.com/30223515/63483970-a57a2d00-c4d0-11e9-8330-d794ccf3e958.png)
![image](https://user-images.githubusercontent.com/30223515/63483986-b460df80-c4d0-11e9-971a-2fca1da56ea9.png)
从3.11.0 升级至3.11.2 发现了这个问题 
I Found problem when  upgrade redisson version 3.11.0 to 3.11.3 
所以 *clear:* 相关对象 redisson 会做如何管理 
So how does redisson manage data?  for   RSemaphore K*clear:*

**Comment by mrniko** [comment]
RSemaphore is used to sync local cache clearing process across all RLocalCachedMap instances.

**Comment by CatCccC** [comment]
> RSemaphore is used to sync local cache clearing process across all RLocalCachedMap instances.

RSemaphore   still exists after  after local cache clearing process finish ?

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by mrniko** [comment]
@raja2102598 

Fixed. Thanks for report
