### ISSUE TITLE
减少netty 的线程数量

### ISSUE THREAD

**Issue by lovlyhao** [redisson/redisson#2274]
![image](https://user-images.githubusercontent.com/30038949/63583143-02f3a400-c5cd-11e9-8639-36dac81a6e5a.png)

![image](https://user-images.githubusercontent.com/30038949/63583240-359d9c80-c5cd-11e9-80e4-54ec3c40ac8c.png)

怎么减少netty开启的守护线程数量 ，因为现在项目也用的是netty ，现在也用到Redisson

**Comment by jackygurui** [comment]
请修改`threads`和`nettyThreads`这两个参数
