### ISSUE TITLE
the redission can not shutdown

### ISSUE THREAD

**Issue by damoyang** [redisson/redisson#2275]
### Expected behavior
I use single mode redisson to test batch function. However after I have finished the test, I can not shutdown the redissonClient. In the test, if I call rfuture.cancel(), then the redissonclient can not shutdown. If not, it shutdown normally

### Steps to reproduce or test case
class TestRedisson {
    public static void main(String[] args) throws Exception {
        BatchOptions batchOption = BatchOptions.defaults().executionMode(ExecutionMode.IN_MEMORY)//.skipResult()
                .responseTimeout(1, TimeUnit.SECONDS).retryInterval(1, TimeUnit.SECONDS)
                .retryAttempts(2);
        Config config = new Config();
        config.useSingleServer().setAddress("redis://xxxx.eos.grid.xxx.com.cn:50470");
        config.setCodec(StringCodec.INSTANCE);
        RedissonClient redisson = Redisson.create(config);
        String test = "hwc#key";
        String map = "hwc#map";
        RBatch batch = redisson.createBatch(batchOption);
        List<RFuture<?>> futures = new ArrayList<RFuture<?>>();
        for (int i = 0; i < 100; i++) {
            RFuture getFuture = batch.getBucket(test).getAsync();
            RFuture setFuture = batch.getBucket(test).setAsync("" + i);
            getFuture.whenComplete((res, e) -> {
                System.out.println(res);
            });
            setFuture.whenComplete((res, e) -> {
                System.out.println(res);
            });
            getFuture.cancel(true);
        }
        RFuture<BatchResult<?>> batchFuture = batch.executeAsync();
        batchFuture.join();
        long c1 = System.currentTimeMillis();
        System.out.println("cost" + (c1 - c));
        redisson.shutdown();
### Redis version
2.4.20.23
### Redisson version
3.11.2

**Comment by mrniko** [comment]
Fixed! Thanks for report
