### ISSUE TITLE
"ERR max number of clients reached" exception while using redisson jcache

### ISSUE THREAD

**Issue by akhilmad** [redisson/redisson#2276]
I am using Azure c0 redis instance which has maxClients value set to 250 , which cannot be changed. Now I have an application which uses Jcache implementation of REDIS for caching. Below is the code of redis cache creation: 

    @Override
    public CachingProvider getCacheProvider() {
        return Caching.getCachingProvider(getCacheProviderClass(), classLoader);
    }

    @Override
    public CacheManager getCacheManager() {
        return getCacheProvider().getCacheManager(getCacheProvider().getDefaultURI(), classLoader,
                CacheUtils.convertMapToProperties(propertiesMap));
    }
+
    protected <K, V> Configuration<K, FabricCacheEntry<K, V>> updateConfiguration(
            MutableConfiguration<K, FabricCacheEntry<K, V>> mutableConfiguration, Map<String, String> map) {
        String cacheURL = map.get(CacheConstants.CACHE_URL);
        Config config = new Config();
        String cacheMode = map.get(CacheConstants.REDIS_MODE);
        SingleServerConfig singleServerConfig = config.useSingleServer()
                .setAddress(getFullyQualifiedRedisURL(cacheURL));
        if (map.containsKey(CacheConstants.REDIS_PASSWORD)) {
            singleServerConfig.setPassword(map.get(CacheConstants.REDIS_PASSWORD));
        }
        singleServerConfig.setConnectionMinimumIdleSize(getConnectionMinimumIdleSize(map));
        singleServerConfig.setIdleConnectionTimeout(getIdleConnectionTimeout(map));
        RedissonClient redisClient = Redisson.create(config);
        return RedissonConfiguration.fromInstance(redisClient, mutableConfiguration);
    }

But when I do a load testing with just 10 users for 10 minutes on the cache I and facing "ERR max number of clients reached" issue. Here is what I have observed, whenever I create a cache instance through the above code, 32 new clients are being created and that is the default value of "connectionMinimumIdleSize" property in redis. But according to the API doc , this property is 
"Minimum idle Redis connection amount" and I believe that this number of clients shouldnt be created. 

Any help here is appreciated.

### Redis version
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.7.0</version>
		</dependency>

### Redisson version
3.2.7

**Comment by mrniko** [comment]
You need to define redisClient instance as singleton.
