### ISSUE TITLE
default Config constructor not using any Codec

### ISSUE THREAD

**Issue by Lovesmoring** [redisson/redisson#2279]
### Expected behavior
Using FstCodec as default Codec if not specified
### Actual behavior
    public Config() {
        this.transportMode = TransportMode.NIO;
        this.lockWatchdogTimeout = 30000L;
        this.keepPubSubOrder = true;
        this.decodeInExecutor = false;
        this.useScriptCache = false;
        this.minCleanUpDelay = 5;
        this.maxCleanUpDelay = 1800;
        this.addressResolverGroupFactory = new DnsAddressResolverGroupFactory();
    }
### Redis version
5.x
### Redisson version
3.11.2
### Redisson configuration
        Config config = new Config();
        config.setNettyThreads(1000)
                .setThreads(1000)
                .setDecodeInExecutor(true)
                .useClusterServers()
                .addNodeAddress(redisMasterService)
                .setRetryAttempts(RETRY_TIMES)
                .setRetryInterval(redisTimeout)
                .setMasterConnectionPoolSize(1000)
                .setSlaveConnectionPoolSize(1000)
                .setConnectTimeout(10000);
        return config;

**Comment by jackygurui** [comment]
Default codec is checked and assigned when RedissonClient instance is created.
