### ISSUE TITLE
How to access localCachedMap wit RedissonBatch?

### ISSUE THREAD

**Issue by PC-AKumar** [redisson/redisson#2280]
is getLocalCachedMap not available with rBatch? or is rBatch.getMap() and rBatch.getMapCache() good enough to getLocalCachedMap reference?

### Expected behavior
rBatch.getLocalCachedMap() is available
### Actual behavior
Only rBatch.getMapCache() and rBatch.getMap() is avaiable

will using rBatch.getMap() return a local cached reference or will it actually fetch from redis when rBatch.execute is called?

**Comment by PC-AKumar** [comment]
@mrniko @jackygurui Is there something I am missing here? Is local cached map not available with batched command submissions?

**Comment by mrniko** [comment]
Local cached map is not supported yet in RBatch object

**Comment by PC-AKumar** [comment]
@mrniko Is it scheduled to be added in any of the upcoming releases?

**Comment by mrniko** [comment]
@PC-AKumar 

I haven't planned it yet.
