### ISSUE TITLE
why the ansy method can not ensure insert data crectly

### ISSUE THREAD

**Issue by fbin87** [redisson/redisson#2281]
### Expected behavior
inert data fast and crect
### Actual behavior
can not ensure insert data crectly
### Redis version
v5.0.5 docker
### Redisson version
v3.5.4
### Redisson configuration

 I used geospatial method(redisson.getGeo and geo.addAsync) to write data with a data size of 50 million, but found that redisson could not guarantee that all data were written every time.

// the config setting
  static {
            config = new Config();
            config.useSingleServer().setAddress("redis://192.168.3.91:6379").
                    setTimeout(20000).
                    setRetryAttempts(10);
            redisson = Redisson.create(config);
        }

  for (int j = 0; j < gpsdata.length; j++) {
                geoentrys[j] = new GeoEntry(gpsdata[j].getX(), gpsdata[j].getY(), gpsdata[j].getId());
            }
            result.add(geo.addAsync(geoentrys));
        }
// then check the Thread method if it was finished

 for (int i = 0; i < result.size(); i++) {
                    if (result.get(i).isSuccess()) {
                        Thread.sleep(100);
                        count++;
                    } else {
                     i--;
                    }
// finally closed the redisson
System.out.println("completed:"+count);
redisson.shutdown();

//In debug mode, I found the futureTask: some compled normally , completed exceptionly, and some unfinished 

Meanwhile, I also conducted experiments in the multi-node redis environment, and redisson could not guarantee that all data were written.However, it's only when I'm using the geo. Add () method and I'm writing multiple threads based on Thread class that I can make sure that all the data is written properly.

**Comment by fbin87** [comment]
Meanwhile, I also conducted experiments in the multi-node redis environment, and redisson could not guarantee that all data were written.However, it's only when I'm using the geo. Add () method and I'm writing multiple threads based on Thread class that I can make sure that all the data is written properly.

**Comment by mrniko** [comment]
You need to wait for sync with `result.get(i).sync()` method

**Comment by fbin87** [comment]
> You need to wait for sync with `result.get(i).sync()` method
As you suggested, this error occurred while checking to see if it was complete.
  for (int i = 0; i < result.size(); i++) {
                    result.get(i).sync();
                    if (result.get(i).isSuccess()) {
                         count++;
                    }
}
//erro
org.redisson.client.RedisTimeoutException: Unable to send command: (GEOADD) with params: [Ljava.lang.Object;@4fd1f9c0 after 10 retry attempts.

**Comment by mrniko** [comment]
@fbin87 

unable to reproduce the issue with the current Redisson.

**Comment by fbin87** [comment]
> @fbin87
> 
> unable to reproduce the issue with the current Redisson.

@mrniko  thank you, official documentation needs to explain examples of how asynchronous methods can be used safely.This problem occurs when large amounts of data are written asynchronously.The data amount is 20 million track data.

**Comment by mrniko** [comment]
Use RBatch object to make mass insertion. Overwise if you execute 20 million async requests at the same time you'll always get errors `Unable to send command`.
