### ISSUE TITLE
Circuit Break Hibernate L2 cache, if redis is unreachable.

### ISSUE THREAD

**Issue by aayushmishra89** [redisson/redisson#2286]
### Expected behavior 
Redis server becomes unavailable, usage of L2 cache should be bypassed and the application should continue to run.

### Actual behavior
The whole application goes down, Hibernate can't function. Keep getting connection timeouts. 
We have to manually turn off L2 in app config and redeploy the application, this could be prevented by using a circuit breaker.

### Steps to reproduce
While the application is running, kill the redis server.

### Redis version 
5.0.5

### Redisson version
 3.11.1, artifact : redisson-hibernate-53 

### Redisson configuration  
Default Replicated Servers Config

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/1800
