### ISSUE TITLE
Prevent "split brain" scenario with HA-proxy 

### ISSUE THREAD

**Issue by aayushmishra89** [redisson/redisson#2287]
With the use of HAProxy server, Redis Sentinels can be configured to allow for automatic failover between the master and slave Redis replica instances for high availability.

HAProxy comes with built-in TCP health check feature for Redis to perform an automatic failover. To avoid having to change Redis IP/Port in the front-end client application after each failover, I have setup HAProxy with the TCP health check to test if a Redis instance is a master or slave. This setup is needed to make sure it only proxy connections to an active master instance. [More Info here](https://community.pivotal.io/s/article/How-to-setup-HAProxy-and-Redis-Sentinel-for-automatic-failover-between-Redis-Master-and-Slave-servers)

### Actual behavior
Running in the replicated mode, this causes split brain and redisson fails to start with an error "Multiple masters detected".

### Expected behavior
Redisson should to be able to connect to the ha-proxy ports and run without split brain.

### Steps to reproduce or test case
[Use HAProxy and Redis Sentinel for automatic failover](https://community.pivotal.io/s/article/How-to-setup-HAProxy-and-Redis-Sentinel-for-automatic-failover-between-Redis-Master-and-Slave-servers)

### Redis version
5.0.5

### Redisson version
3.11.1

### Redisson configuration
Replicated Servers Config with nodeAddresses of ha proxy port

**Comment by jackygurui** [comment]
If the HAProxy is managing the IP address changes and making the failover transparent to the frontend client, then you should use master-slave config to run Redisson.
