### ISSUE TITLE
集群模式下RLock无法锁住

### ISSUE THREAD

**Issue by liubaochuan** [redisson/redisson#2288]
### Actual behavior
相同的key同一时间都能拿到锁

### Steps to reproduce or test case
 RLock lock = redissonClient.getLock(lockKey);
 if (lock.tryLock(10, 5,TimeUnit.SECONDS)) {
     //......
} 

### Redisson version
3.10.6

### Redisson configuration
springboot 基础redis配置
spring.redis.cluster.nodes=xxx.xxx.xxx.xxx:7000,yyy.yyy.yyy.yyy:7100

**Comment by mrniko** [comment]
Could you provide complete test code to reproduce this?

**Comment by liubaochuan** [comment]
String key = "lock_key"+"ABC"+"_lock";
        RLock lock = redissonClient.getLock(key);
        try {
            if (lock.tryLock()) {
                Thread.sleep(1000);
                System.out.println(key+" 获取锁成功 Thread:"+Thread.currentThread().getName());
            }else {
                System.out.println(key+" 获取锁失败 Thread:"+Thread.currentThread().getName());
            }
        }catch (InterruptedException e){
            System.err.println(e.getMessage());
            Thread.currentThread().interrupt();
        }finally {
            lock.unlock();
        }

**Comment by wangbo911** [comment]
How to be commter

**Comment by wangbo911** [comment]
> String key = "lock_key"+"ABC"+"_lock";
> RLock lock = redissonClient.getLock(key);
> try {
> if (lock.tryLock()) {
> Thread.sleep(1000);
> System.out.println(key+" 获取锁成功 Thread:"+Thread.currentThread().getName());
> }else {
> System.out.println(key+" 获取锁失败 Thread:"+Thread.currentThread().getName());
> }
> }catch (InterruptedException e){
> System.err.println(e.getMessage());
> Thread.currentThread().interrupt();
> }finally {
> lock.unlock();
> }

完成测试代码？

**Comment by liubaochuan** [comment]
测试环境：3个集群 每个集群一主一从  
在每个集群的服务器上运行都一直运行那段代码。会概率性出现同时都能获取锁成功。

**Comment by jackygurui** [comment]
你这三个集群都是相互独立的，在每个集群的服务器上运行都一直运行那段代码。会概率性出现同时都能获取锁成功。这没问题啊？你要想三个独立的集群同时只能有一个锁，那就需要用MultiLock或是RedLock了。

**Comment by liubaochuan** [comment]
能方便提供下MultiLock或是RedLock 使用demo不，或者文档连接。

**Comment by liubaochuan** [comment]
也就是如果搭建一个集群里面多主多从使用默认的锁是可以是不？

**Comment by liubaochuan** [comment]
之前描述有误，不好意思。 是一个集群里面有三主三从，有3个服务器，每个服务器一主一从，但是他们都是属于一个集群。我后面没有使用tryLock 而是使用lock，貌似就没有出现问题。

**Comment by liubaochuan** [comment]
使用lock不是完全没有问题，只是出现的概率比较低，最近分析日志还是会出现。在单节点的情况下没有问题。是否说默认锁在多主集群中不适用？

**Comment by mrniko** [comment]
Which Redis hosting do you use?

**Comment by liubaochuan** [comment]
4.0.9

**Comment by mrniko** [comment]
@liubaochuan 

Did you deploy it on your own servers or use hosting?

**Comment by liubaochuan** [comment]
自己的物理机环境

**Comment by liubaochuan** [comment]
tryLock 出现重复获取锁的概率非常高，后面修改为使用lock后很少出现重复获取锁的问题，但是还是有。

**Comment by mrniko** [comment]
do you use lock method without any parameters?

**Comment by liubaochuan** [comment]
lock.lock(1, TimeUnit.SECONDS);

**Comment by mrniko** [comment]
In your case you set lease timeout to 1 second. If execution of code block guarded by lock takes more than 1 second then it's possible to get lock acquired multiple times.

**Comment by liubaochuan** [comment]
我们仔细测试了下，我们锁内部执行逻辑是低于1秒的。lock.lock(10, TimeUnit.SECONDS);我们换成10秒还是出现同时拿到锁的情况。

**Comment by liubaochuan** [comment]
今天专门测试了下,使用了lock.lock(10, TimeUnit.SECONDS);在这个两个非常接近的时间戳能分别拿到锁 1569409045755 , 1569409045681

**Comment by yinjihuan** [comment]
我今天测试单机加锁，100并发，10秒超时的设置，也出现了同时获取锁
