### ISSUE TITLE
query about Redisson at scale

### ISSUE THREAD

**Issue by ppavan108** [redisson/redisson#2289]
Planning to embed redisson in each of my application instance.  I want to know how redisson behaves in following scenarios.

Q1) a. If application instances scale to a number of 100 or more will there by any challenge from redisson side?
b. Do redisson instances  talk to each other over network? Then such scaling can cause problems.

Q2) If node 1 created a redisson object , are there any restrictions on usage of same object on another node in a big cluster?  

Q3) In a big cluster are there any challenges if some of applications instances are shutdown or terminated abruptly?

**Comment by mrniko** [comment]
No is the answer to all your questions.
