### ISSUE TITLE
LockWatchdogTimeout will cause the IllegalMonitorStateException

### ISSUE THREAD

**Issue by Anselzhao** [redisson/redisson#2292]
redis version: 3.0.504
redisson version：3.11.1

setLockWatchdogTimeout will cause the IllegalMonitorStateException

`
public class LockTest {

    public static final String KEY = "LOCK_KEY";
    
    private static void test() {
        Config config = new Config();
        // setLockWatchdogTimeout this will cause the IllegalMonitorStateException "attempt to unlock lock, not locked by current thread by node id"
         config.setLockWatchdogTimeout(30);
        config.setCodec(new org.redisson.client.codec.StringCodec());
        config.useSingleServer().setAddress("redis://127.0.0.1:6379");
        config.useSingleServer().setConnectionPoolSize(100);
        config.useSingleServer().setConnectionMinimumIdleSize(3);
        RedissonClient redisson = Redisson.create(config);
        RLock lock = redisson.getLock(KEY);
        lock.lock();
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        lock.unlock();
    }

    public static void main(String[] args) {
        test();
    }
}`

_Originally posted by @Anselzhao in https://github.com/redisson/redisson/issues/2269#issuecomment-526424589_

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version. setLockWatchdogTimeout doesn't even contain such check.

**Comment by Anselzhao** [comment]
use Redisson 3.11.3  log。when i using setLockWatchdogTimeout also cause the exception.  i can't figure out... the whole log

`20:19:20.642 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
20:19:20.657 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
20:19:20.657 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
20:19:20.794 [main] INFO org.redisson.Version - Redisson 3.11.3
20:19:20.796 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24
20:19:20.816 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
20:19:20.816 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
20:19:20.835 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
20:19:20.837 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
20:19:20.837 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
20:19:20.838 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
20:19:20.839 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
20:19:20.839 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
20:19:20.840 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
20:19:20.840 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
20:19:20.840 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
20:19:20.840 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
20:19:20.840 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
20:19:20.841 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\ADMINI~1\AppData\Local\Temp (java.io.tmpdir)
20:19:20.841 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
20:19:20.841 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 3782737920 bytes
20:19:20.841 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
20:19:20.842 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
20:19:20.842 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
20:19:20.847 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
20:19:20.934 [main] DEBUG io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider - Default DNS servers: [/172.21.211.250:53, /172.21.211.251:53] (sun.net.dns.ResolverConfiguration)
20:19:20.945 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
20:19:20.945 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
20:19:21.073 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
20:19:21.073 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
20:19:21.236 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
20:19:21.236 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
20:19:21.237 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@24b1d79b
20:19:21.293 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 13284 (auto-detected)
20:19:21.426 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:50:56:ff:fe:c0:00:08 (auto-detected)
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 24
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 24
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
20:19:21.450 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
20:19:21.456 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
20:19:21.456 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
20:19:21.456 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
20:19:21.493 [redisson-netty-2-8] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@1071230718 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xb65e52bb, L:/127.0.0.1:63808 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:21.493 [redisson-netty-2-9] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@694962409 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xfab4b0ac, L:/127.0.0.1:63809 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:21.493 [redisson-netty-2-6] DEBUG org.redisson.connection.ClientConnectionsEntry - new pubsub connection created: RedisPubSubConnection@1591816856 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xfa014024, L:/127.0.0.1:63810 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:21.493 [redisson-netty-2-7] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@1951744626 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x2d24058d, L:/127.0.0.1:63811 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:21.499 [redisson-netty-2-6] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379
20:19:21.499 [redisson-netty-2-7] INFO org.redisson.connection.pool.MasterConnectionPool - 3 connections initialized for 127.0.0.1/127.0.0.1:6379
20:19:21.515 [main] DEBUG org.redisson.connection.DNSMonitor - DNS monitoring enabled; Current masters: {redis://127.0.0.1:6379=127.0.0.1/127.0.0.1:6379}, slaves: {}
20:19:21.548 [main] DEBUG org.redisson.command.RedisExecutor - acquired connection for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, LOCK_KEY, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:99:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using node 127.0.0.1/127.0.0.1:6379... RedisConnection@1071230718 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xb65e52bb, L:/127.0.0.1:63808 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:21.550 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
20:19:21.550 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
20:19:21.550 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
20:19:21.550 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
20:19:21.565 [redisson-netty-2-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
20:19:21.565 [redisson-netty-2-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
20:19:21.565 [redisson-netty-2-2] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@496c2ec2
20:19:21.574 [redisson-netty-2-2] DEBUG org.redisson.command.RedisExecutor - connection released for command (EVAL) and params [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, LOCK_KEY, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=3, freeConnectionsCounter=value:100:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1071230718 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xb65e52bb, L:/127.0.0.1:63808 - R:127.0.0.1/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@40257c31(success)], command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, LOCK_KEY, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1], codec=org.redisson.client.codec.LongCodec]]
20:19:21.648 [pool-1-thread-1] DEBUG org.redisson.command.RedisExecutor - acquired connection for command (EVAL) and params [if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); retu..., 1, LOCK_KEY, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:99:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using node 127.0.0.1/127.0.0.1:6379... RedisConnection@694962409 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xfab4b0ac, L:/127.0.0.1:63809 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:21.660 [redisson-netty-2-4] DEBUG org.redisson.command.RedisExecutor - connection released for command (EVAL) and params [if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); retu..., 1, LOCK_KEY, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=3, freeConnectionsCounter=value:100:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@694962409 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xfab4b0ac, L:/127.0.0.1:63809 - R:127.0.0.1/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@5532ef84(success: false)], command=(EVAL), params=[if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); retu..., 1, LOCK_KEY, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1], codec=org.redisson.client.codec.LongCodec]]
20:19:26.575 [main] DEBUG org.redisson.command.RedisExecutor - acquired connection for command (EVAL) and params [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, LOCK_KEY, redisson_lock__channel:{LOCK_KEY}, 0, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:99:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using node 127.0.0.1/127.0.0.1:6379... RedisConnection@1951744626 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x2d24058d, L:/127.0.0.1:63811 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
20:19:26.577 [redisson-netty-2-3] DEBUG org.redisson.command.RedisExecutor - connection released for command (EVAL) and params [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, LOCK_KEY, redisson_lock__channel:{LOCK_KEY}, 0, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=3, freeConnectionsCounter=value:100:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1951744626 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x2d24058d, L:/127.0.0.1:63811 - R:127.0.0.1/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@668f239(success)], command=(EVAL), params=[if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, LOCK_KEY, redisson_lock__channel:{LOCK_KEY}, 0, 3, ea0fb3b6-09e2-4393-9e82-3b822e5e76c3:1], codec=org.redisson.client.codec.LongCodec]]
Exception in thread "main" java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: ea0fb3b6-09e2-4393-9e82-3b822e5e76c3 thread-id: 1
	at org.redisson.RedissonLock.lambda$unlockAsync$3(RedissonLock.java:577)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.command.RedisExecutor.handleReference(RedisExecutor.java:507)
	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:500)
	at org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:485)
	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:471)
	at org.redisson.command.RedisExecutor.lambda$execute$3(RedisExecutor.java:187)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:82)
	at org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:460)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:455)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:386)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:215)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:153)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by mrniko** [comment]
Accroding to the exception thread you're trying to unlock a lock which wasn't locked by this thread so exception has arise.

**Comment by Anselzhao** [comment]
i understand the exception meaning ,  i just can not figure out why setLockWatchdogTimeout will cause this.

**Comment by wangbo911** [comment]
赵先生，你这测试的用分布式锁的例子写的就有问题。

**Comment by Anselzhao** [comment]
??哪里？怎么改？
