### ISSUE TITLE
Did not get Connect callback in high load

### ISSUE THREAD

**Issue by vivek807** [redisson/redisson#2293]
### Expected behavior
Callback for connect should come after reconnecting

### Actual behavior
Never got connect callback after disconnect CB even server is working fine. (Although Redis server is never disconnected ... I don't know why disconnect CB also come)

### Steps to reproduce or test case
Add Callback listener to Redis nodes.
Add 10k data in 1 second to different keys. and observe.

### Redis version
5.0.5

### Redisson version
3.11.2

### Redisson configuration
config.useSingleServer()
						.setRetryAttempts(Integer.MAX_VALUE)
						.setAddress("redis://127.0.0.1:6379");

**Comment by mrniko** [comment]
I'm sorry, what does CB mean?

**Comment by vivek807** [comment]
Callback/listener... Sorry for the confusion.

I have registered connection callback at nodes using

redisClient.getNodesGroup().addConnectionListener()

Thanks,
Vivek Dhiman

**Comment by mrniko** [comment]
Since 3.15.3 version use `Config.setConnectionListener()` setting to define `connectionListener`. Connection listener defined through getNodesGroup missed listener invocation during Redisson startup.
