### ISSUE TITLE
org.redisson.client.RedisTimeoutException

### ISSUE THREAD

**Issue by Lovesmoring** [redisson/redisson#2296]
org.redisson.client.RedisTimeoutException: 
Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings 
Node source: NodeSource 
[slot=10914, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:1000:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xxxx:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1378785511 [redisClient=[addr=redis://xxxx:6379], channel=[id: 0x13f751a1, L:/xxxx:39232 - R:xxxx/xxxx:6379], currentCommand=null], command: (EXISTS), params: [redis.key:eabf3435c24cc88a508f0f8570ce0838d051e53231727104d2febca92412634b] after 5 retry attempts. [org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715), io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682), io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757), io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485), java.lang.Thread.run(Unknown Source)]

### Expected behavior
Not seeing this error
### Actual behavior
After running for days in hundreds QPS, this kind of error emerges.
### Redis version
5.0.1
### Redisson version
3.11.2
### Redisson configuration
        Config config = new Config();
        config.setNettyThreads(256)
                .setDecodeInExecutor(true)
                .setCodec(new FstCodec())
                .useClusterServers()
                .addNodeAddress(redisMasterService)
                .setRetryAttempts(5)
                .setRetryInterval(3000)
                .setMasterConnectionPoolSize(1000)
                .setSlaveConnectionPoolSize(1000)
                .setConnectTimeout(10000);

**Comment by Lovesmoring** [comment]
Tried increase nettyThreads and threads to 1000, no help.

**Comment by Lovesmoring** [comment]
Our Redis is a stateful set cluster running in kubernetes. We are using kubernetes ClusterIP to access it.

**Comment by mrniko** [comment]
try to set retryInterval = 10000

**Comment by Lovesmoring** [comment]
I tried, but not working. In my case, I have a 40-core machine. Any problem if I set nettyThreads to 256? In my first thought, there may be some leak or dying threads. Otherwise this scenario: 
"Having RedisTimeoutException after running for a while in same work load" is very weird.

> try to set retryInterval = 10000

**Comment by mrniko** [comment]
Try to set nettyThreads to 256. there are no leaks or dying threads.

**Comment by Lovesmoring** [comment]
> Try to set nettyThreads to 256. there are no leaks or dying threads.

I tried, still got this:

org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=15071, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:512:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xxxx:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@618264998 [redisClient=[addr=redis://xxxx:6379], channel=[id: 0x3591f9d7, L:/xxxx:47680 - R:xxxx/xxxx:6379], currentCommand=null], command: (GET), params: [myKey:748795d65772f2a56b284f4d889338dcd75d05f68fa8f082c99210ae2a258006] after 5 retry attempts.
[org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:715), io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682), io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757), io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485), java.lang.Thread.run(Unknown Source)]

I'm using the following config:

        config.setNettyThreads(256)
                .setThreads(256)
                .setDecodeInExecutor(true)
                .setCodec(new FstCodec())
                .useClusterServers()
                .addNodeAddress(redisMasterService)
                .setRetryAttempts(5)
                .setRetryInterval(10000)
                .setMasterConnectionPoolSize(512)
                .setSlaveConnectionPoolSize(512)
                .setConnectTimeout(10000)
                .setTimeout(10000);

I can provide threaddump if it happens again

**Comment by Lovesmoring** [comment]
I used old version 3.8.2 with following config:

        config.setNettyThreads(256)
                .setThreads(256)
                .setCodec(new FstCodec())
                .useClusterServers()
                .addNodeAddress(redisMasterService)
                .setRetryAttempts(5)
                .setRetryInterval(10000)
                .setMasterConnectionPoolSize(512)
                .setSlaveConnectionPoolSize(512)
                .setConnectTimeout(10000)
                .setTimeout(10000);

The exception is gone. Wondering did the version or setDecodeInExecutor cause this.

**Comment by mrniko** [comment]
If decodedInExecutor helped then try to set netty threads 512 for the latest version and decodedInExecutor = false
