### ISSUE TITLE
is this a typo of how to install via pom.xml?

### ISSUE THREAD

**Issue by zhaoxunyong** [redisson/redisson#2297]
### Redisson configuration

I found a typo of how to install via pom.xml in "Used by",  which maybe is missing a letter "r".  
Is there such a version for "redisson-3.11.3" in maven repository? I could't find it in mvn repository.

if this is a typo, please help out revamp.

thanks.

![Snip20190904_1](https://user-images.githubusercontent.com/8733266/64220012-61d4e980-cefa-11e9-82e6-cd9dc48c27f4.png)

**Comment by mrniko** [comment]
Thanks for pointing out! I have sent a request on this to github support.
