### ISSUE TITLE
cluster模式运行一段时间会出现OutOfMemory

### ISSUE THREAD

**Issue by songjiesdnu** [redisson/redisson#2309]
### Expected behavior
长时间运行，不会导致内存泄露

### Actual behavior
长时间运行，导致内存泄露

### Steps to reproduce or test case
1.从spring官网上生成spring boot的demo项目。
2.在pom.xml中增加对redisson的依赖。
```xml
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson</artifactId>
	<version>3.11.3</version>
</dependency>
```
3.debug方式启动spring boot。
4.通过断点观察
![redisson-oom](https://user-images.githubusercontent.com/7113099/64514185-baeab600-d31c-11e9-94d4-47afc7818d4a.jpg)

可以看到redisson所依赖的netty里，这个数组的的大小会不断增大，最终导致oom。

### Redis version
```shell
redis_version:5.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:913214bd6b0ee4ea
redis_mode:cluster
os:Linux 3.10.0-957.1.3.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
```

### Redisson version
3.11.3

### Redisson configuration
我是在spring boot里通过代码的方式配置的。
```java
@SpringBootApplication
public class Test3Application {

    public static void main(String[] args) {
        SpringApplication.run(Test3Application.class, args);
    }

    @Bean
    public RedissonClient getRedisson() {
        Config config = new Config();
        config.useClusterServers()
                .setScanInterval(2000) // cluster state scan interval in milliseconds
                .addNodeAddress("redis://10.193.xxx.xxx:8303");
        RedissonClient redisson = Redisson.create(config);
        return redisson;
    }

}
```

**Comment by mrniko** [comment]
Could you provide memory dump? which object causes outofmemory?

**Comment by songjiesdnu** [comment]
class：io.netty.util.interna.UnpaddedInternalThreadLocalMap
field：Object[] indexedVariables;
![redisson-netty-01](https://user-images.githubusercontent.com/7113099/64516263-c7710d80-d320-11e9-9c79-0ac21af2657c.jpg)
![redisson-netty-02](https://user-images.githubusercontent.com/7113099/64516272-cb049480-d320-11e9-8e02-c6bc54410567.jpg)

if these infomation is enough?

**Comment by mrniko** [comment]
I don't see which object in InternalThreadLocalMap consuming the memory? can you share the dump?

**Comment by mrniko** [comment]
Which netty version do you have in classpath?

**Comment by songjiesdnu** [comment]
you can download the dump from [here:](https://cmoviepic.bj.bcebos.com/production%2Foom%2Fwalle_api_bj-B-01_heap.hprof.tar.gz)

UnpaddedInternalThreadLocalMap is the parent class of InternalThreadLocalMap,and indexedVariables is defined in UnpaddedInternalThreadLocalMap。

the netty version in classpath is :4.1.39

**Comment by zhanglei-1987** [comment]
> I have not try another codec yet。
> which codec do you recommend？

我也遇到了这个问题，最新版的redisson和spring-boot，你解决了吗

**Comment by songjiesdnu** [comment]
@zhanglei-1987 
我最近修改一版redisson的源码，将CommandDecoder对FastTheadLocal的使用改为JDK自带的ThreadLocal，然后在decode方法结束之后调用ThreadLocal的remove方法。我这边还需要观察一段时间，才能确定是否真正解决该问题。但是从dump出来的堆看，已经不存在该问题了。

**Comment by songjiesdnu** [comment]
> @songjiesdnu
> 
> 我也遇到了这个问题，最新版的redisson和spring-boot，你解决了吗
> 
> 我发现FastThreadLocal.detory()可以删除对象，定时调用应该可以解决oom的问题

这个你可以试试，从源代码看，其并不会清理Objcet[]数组。

**Comment by mrniko** [comment]
Fixed!

**Comment by songjiesdnu** [comment]
@mrniko 
I can not find 3.11.4 in mvn repository, when will you upload it?
