### ISSUE TITLE
Tomcat - Error on getSession

### ISSUE THREAD

**Issue by jcgarciasilva** [redisson/redisson#2310]
### Expected behavior
Get saved session
### Actual behavior
Errror on get saved session 

` [http-nio-8080-exec-3] org.redisson.tomcat.RedissonSessionManager.findSession Session 220E103487E92F790688E64E864CE089 can't be found
09/09/19 17:31:22 ERROR hamburgsud.schedule.report.sign.in.controller.SignInController:44
Unable to sign in.
java.lang.IllegalArgumentException: The user cannot be null.
`

### Steps to reproduce or test case
Tomcat configuration Steps
### Redis version
lastest
### Redisson version
3-11-2
### Redisson configuration
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://10.121.224.137:7000"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16

**Comment by mrniko** [comment]
Make sure session 220E103487E92F790688E64E864CE089 stored in Redis

**Comment by jcgarciasilva** [comment]
@mrniko, it's not on redis. I check the keys on my Redis instance. Its not creating the session on redis

**Comment by mrniko** [comment]
All functionally is covered with tests. Could you describe steps how to reproduce the issue?
