### ISSUE TITLE
How to resolve error "ERR unknown command EVAL"?

### ISSUE THREAD

**Issue by SumukhDeshpande** [redisson/redisson#2317]
### Redis version
V 2.2 Provided by PCF.
### Redisson version
3.9.0
### Redisson configuration

		Config config = new Config();
		String url = String.format("%s%s%s%s", "redis://", 127.0.0.1, COLON, 6379);
		config.useSingleServer().setAddress(url).setPassword(password);
		return Redisson.create(config);
The exception I see is:
```
Caused by: org.redisson.client.RedisException: ERR unknown command EVAL, with args beginning with: local value =
  redis.call('hget', KEYS[1], ARGV[2]); if value == false then return
  nil; end;
```

**Comment by mrniko** [comment]
Change your Redis server vendor.
