### ISSUE TITLE
RRateLimiter does not provide way to overwrite config

### ISSUE THREAD

**Issue by pc-mmautner** [redisson/redisson#2322]
## Expected behavior

[`RRateLimiter`](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RRateLimiter.java) does not have a `setRate`/`setRateAsync` method.

It only has `trySetRate`/`trySetRateAsync` methods, so once a rate-limiter's config is persisted to Redis, it cannot be overwritten.

### Actual behavior

Invoking `RRateLimiter.trySetRate` twice with different rate-limiter configuration values does not overwrite, since it uses `HSETNX` instead of `HSET` operation.

### Steps to reproduce or test case

```
RRateLimiter rateLimiter = redisson.getRateLimiter("myRateLimiter");
boolean success;
success = rateLimiter.trySetRate(RateType.OVERALL, 1, 1, RateIntervalUnit.SECONDS);
System.out.println(success); // "true"
success = rateLimiter.trySetRate(RateType.OVERALL, 2, 2, RateIntervalUnit.SECONDS);
System.out.println(success); // "false"
```
There is no way to overwrite the existing `"myRateLimiter"` with a different rate, besides modifying the rate limiter name

### Redis version

4.0.11

### Redisson version

3.11.2

### Redisson configuration

N/A

**Comment by mrniko** [comment]
You can always delete the object

**Comment by pc-mmautner** [comment]
Thanks @mrniko -- I have not found that cleanup is guaranteed when my servers reboot

**Comment by mrniko** [comment]
you can either delete or set expiration on object.

**Comment by pc-mmautner** [comment]
Deleting creates a race condition if there are multiple threads/servers referencing the same object, where overwriting has no race condition

Expiration doesn't provide as much granular control, but I'll look into it

**Comment by kmartin** [comment]
Was this just closed because it became stale? This is an issue that makes using this in production a problem.

**Comment by mrniko** [comment]
@kmartin 

You can delete it and then set config again.

**Comment by pc-mmautner** [comment]
@mrniko that is what I ended up doing, using an `RMap` object w/ the same name as my `RRateLimiter`.

I (and @kmartin I think) were expecting a less janky way to do this, using methods exposed via the `RRateLimiter` interface

**Comment by abhishekc-92** [comment]
+1, this would be nice

**Comment by kmartin** [comment]
I am glad to see this is open again. Deleting and re-creating can work but causes other hosts to error out between the delete and the re-create in a zero-downtime environment.

**Comment by mrniko** [comment]
Merged
