### ISSUE TITLE
java semaphores's performance differs a lot in fair and unfair mode

### ISSUE THREAD

**Issue by huotinghh** [redisson/redisson#2325]
I use a semaphore in a complex system with 300 permits while the background workflow has 1000 concurrent requests. It takes about 7ms for processing after permit acquired.
For unfair semaphore, the delay for acquiring the permit is less than 1ms while delay for fair semaphore is more than 30ms.
I understand unfair semaphore may have a slightly better performance. But why it differs so much?

**Comment by mrniko** [comment]
Redisson doesn't provide fair semaphore. Only non-fair one.
