### ISSUE TITLE
Writing hashmap using redisson client and retrieving same value using redis-cli

### ISSUE THREAD

**Issue by tarunsharmaMG** [redisson/redisson#2330]
Hi  , 
I am using following code :

Config config = new Config();
config.useSingleServer().setAddress("redis://127.0.0.1:6379");
client = Redisson.create(config);
RMapCache<String,String >map = client.getMapCache("TestMap1");
RFuture<String> result =mapCache.putAsync("5","6");

I can get the same value back using redisson , But when i see all values using redis-cli , i see following:
:~$ redis-cli -h 127.0.0.1 -p 6379
127.0.0.1:6379> hgetall  TestMap1
1) "\xf7\x01"
2) "\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\xfc\x03abc"
3) "\x00\x01\x1eorg.redisson.RedissonReference\xfc(org.redisson.client.codec.ByteArrayCodec\xfc\x011\xfc\x1eorg.redisson.api.RBinaryStream\x00"
4) "\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\xfb$\x03abc"

How could i avoid this serialization or encoding of data so that i can access the data using some other redisson client ?

**Comment by mrniko** [comment]
Use StringCodec in follow way:

```java
client.getMapCache("TestMap1", StringCodec.INSTANCE);
```
or supply it during configuration:

```java
config.setCodec(StringCodec.INSTANCE);
```
