### ISSUE TITLE
Difficult with basic operation

### ISSUE THREAD

**Issue by programervn** [redisson/redisson#2332]
Dear all,
I tried to test with redisson lib but I saw lack of basic example.
In redis I set String value, for example SET testkey testvalue.
How can I use redisson to get  the String value of testkey?

Here are my code:

public static void main(String[] args) {
		Config config = new Config();
		// use single Redis server
		config.useSingleServer().setAddress("redis://IP:6379");
		RedissonClient redisson = Redisson.create(config);
		
		// perform operations
		RBucket<String> bucket = redisson.getBucket("testkey");
		System.out.println("Value of testkey: " + bucket.get());
	    
		//shutdown 
		redisson.shutdown();
	}

**Comment by mrniko** [comment]
Please find redis command mippings by follow link https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping
