### ISSUE TITLE
Calling RSet.getSize() returns the correct size of set, but then set is empty afterward

### ISSUE THREAD

**Issue by Steve973** [redisson/redisson#2335]
### Expected behavior
Call RSet.getSize() returns set size of N, and a subsequent call to RSet.iterator(batchSize) allows you to iterate through all N items.

### Actual behavior
Call RSet.getSize() returns set size of N, and a subsequent call to RSet.iterator(batchSize) returns an iterator that has no items to iterate through.  Without (first) getting the size, the iterator will iterate through the set of N elements.  For some reason, getting the size (first) makes the set appear to be empty, and there seems to be no method to "reset" to the head of the set, if this is, indeed, what is happening.  Another detail that may also be notable is that, each time I restart my application, RSet.size() returns the expected size, so the data is not being removed with a call to get the cardinality of the set.

### Steps to reproduce or test case
Get a set by calling RSet<String> testSet = RedissonClient.getSet("testSet");
Add items to the set with testSet.addAll(Arrays.asList("1", "2", "3", "4", "5"));
Get the set size with int testSetSize = RSet.size();
The size of testSetSize == 5.
Get an iterator with testSet.iterator(5);
Attempt to iterate over the set, but there will be no items to iterate over.

### Redis version
4.0.8

### Redisson version
3.11.3

### Redisson configuration
Config config = new Config();
config.setCodec(new KryoCodec)
    .useMasterSlaveServers()
    .setMasterAddress("redis://192.168.0.2")
    .addSlaveAddress("redis://192.168.0.3")
    .addSlaveAddress("redis://192.168.0.4")
    .setReadMode(ReadMode.MASTER_SLAVE)
    .setDatabase(1)
    .setTimeout(FIVE_MINUTES)
return Redisson.create(config);

**Comment by mrniko** [comment]
Unable to reproduce the issue. Could you set TRACE logging level for `org.redisson` package and share the output?

**Comment by mrniko** [comment]
Also make sure that Redis slave are configured properly.

**Comment by Steve973** [comment]
Hello, and thank you for the quick response.  I just tried it with the
configuration using useSingleServer() instead, and everything worked fine,
so I think that you may be right, and that it has something to do with the
slaves.  But what I would like to know is why it consistently works *the
first time* and consistently fails *the next time*.  I.e., I can always get
the set size first, or I can always iterate over the set first, and then
the next operation always implies that the set is empty.

**Comment by mrniko** [comment]
size and iterator executed on different Redis slave nodes. I need the logs https://github.com/redisson/redisson/issues/2335#issuecomment-534049009 to get the cause.
