### ISSUE TITLE
example code to connect to redis in Kubernetes setup

### ISSUE THREAD

**Issue by SameerTi** [redisson/redisson#2336]
In my Kubernetes setup, REDIS pods get created as following..

`
crdb-crdb-redisio-sentinel-0                    1/1     Running                 0          39d    12.18.1.222   samt-worker-02   <none>
crdb-crdb-redisio-sentinel-1                    1/1     Running                 0          54d    12.18.1.147   samt-worker-03   <none>
crdb-crdb-redisio-sentinel-2                    1/1     Running                 0          39d    12.18.1.191   samt-worker-01   <none>
crdb-crdb-redisio-server-0                      3/3     Running                 0          54d    12.18.1.156   samt-worker-03   <none>
crdb-crdb-redisio-server-1                      3/3     Running                 0          39d    12.18.1.187   samt-worker-01   <none>
crdb-crdb-redisio-server-2                      3/3     Running                 0          39d    12.18.1.215   

samt-worker-02   <none> 
`

So 1 master and few slaves

Output of "kubectl get svc" is like:
`
crdb-crdb-redisio                      ClusterIP   10.254.111.38    <none>        6379/TCP                                                                                    54d    app=crdb-crdb-redisio,crdb-dbtype=redisio,csf-component=crdb,csf-subcomponent=redisio,heritage=Tiller,redisio_role=master,release=crdb,type=server

crdb-crdb-redisio-readonly             ClusterIP   10.254.211.116   <none>        6379/TCP                                                                                    54d    app=crdb-crdb-redisio,crdb-dbtype=redisio,csf-component=crdb,csf-subcomponent=redisio,heritage=Tiller,redisio_role=slave,release=crdb,type=server

`

### Expected behavior
I want to connect to both master-slave via Raddison client 
### Actual behavior
I'm not sure how though because there are like following ways!
config.useClusterServers().
config.useSingleServer().
config.useMasterSlaveServers()

### Redis version
not sure

### Redisson version
3.3.0
### Redisson configuration
This is what i am confused with

Could you please provide a sample code on how best to connect to Redis with master slave configuration?

master could become slave and vice versa so how dynamically Raddision would take care of this switch? 
IPs of service needs to be configured or IPs of pods?

**Comment by mrniko** [comment]
Hi,

In your case as you have sentinels you should use sentinel connection mode.

> master could become slave and vice versa so how dynamically Raddision would take care of this switch?

Yes.

> IPs of service needs to be configured or IPs of pods?

IPs

**Comment by SameerTi** [comment]
Thanks for Quick response

So you mean this one

https://static.javadoc.io/org.redisson/redisson/3.4.1/org/redisson/config/SentinelServersConfig.html#SentinelServersConfig--

I see a method
https://static.javadoc.io/org.redisson/redisson/3.4.1/org/redisson/config/SentinelServersConfig.html#addSentinelAddress-java.lang.String...-

What I should be adding here..!??

Regards
Sam

**Comment by mrniko** [comment]
> What I should be adding here..!??

crdb-crdb-redisio-sentinel-0, crdb-crdb-redisio-sentinel-1 ... hosts

**Comment by SameerTi** [comment]
redis://crdb-crdb-redisio-sentinel-0:6379
redis://crdb-crdb-redisio-sentinel-1:6379
redis://crdb-crdb-redisio-sentinel-2:6379

Like this...!?

And that's I as client need not to worry about internal switching among
master/ spave?
Connection pooling..?
Load balance..?
Fail over etc...?


On Mon, 23 Sep 2019 at 11:27 PM, Nikita Koksharov <notifications@github.com>
wrote:poo

**Comment by mrniko** [comment]
> Like this...!?

Yes.

> And that's I as client need not to worry about internal switching among
master/ spave?
Connection pooling..?
Load balance..?
Fail over etc...?

No, it's all done by Redisson.

**Comment by SameerTi** [comment]
Thanks,

Here pasting output of "kubectl get svc -o wide"

*crdb-crdb-redisio-sentinel*             ClusterIP   10.254.116.12
 <none>        26379/TCP
                                54d
 app=crdb-crdb-redisio,crdb-dbtype=redisio,csf-component=crdb,csf-subcomponent=redisio,heritage=Tiller,release=crdb,type=sentinel

I don't think we can add multiple *sentinels the way you suggested, because
what if more **sentinels get added / deleted then how would it reflect on
my client app dynamically?*

so looks like we need to add k8 service name rather than pod(s)

So can i use like below?

Config config = new Config();
config.useSentinelServers().addSentinelAddress("redis://" +
"*crdb-crdb-redisio-sentinel:*"+"26379");
}
this.redisson = Redisson.create(config);


Regards,
Sameer

**Comment by SameerTi** [comment]
Could you please share a sample which is using redis along with sentinels in k8s cluster..!?

**Comment by mrniko** [comment]
> I don't think we can add multiple *sentinels the way you suggested, because
what if more **sentinels get added / deleted then how would it reflect on
my client app dynamically?*

You need to define at least one working sentinel at the moment of application startup. Redisson will get remain list of sentinels and will keep them updated.

**Comment by SameerTi** [comment]
I have asked this question earlier, mentioning again, can i use kubernetes
SERVICE NAME of redis sentinel ?

Here pasting output of "kubectl get svc -o wide"

*crdb-crdb-redisio-sentinel*             ClusterIP   1.24.16.12    <none>
     26379/TCP
                      54d
 app=crdb-crdb-redisio,crdb-dbtype=redisio,xxx-component=crdb,xxx-subcomponent=redisio,heritage=Tiller,release=crdb,type=sentinel

Config config = new Config();
config.useSentinelServers().addSentinelAddress("redis://" +
"*crdb-crdb-redisio-sentinel:*"+"26379");this.redisson =
Redisson.create(config);




Because, in k8 setup IP of pod could get modified and we don't expose IPs
externally !

**Comment by SameerTi** [comment]
I used this code:

Config config = new Config();
config.useSingleServer().setAddress("*redis://crdb-crdb-redisio:6379*");
RedissonClient redisson = Redisson.create(config);

and from K8s setup:

[root@samt-control-01 AAA]# kubectl get svc crdb-crdb-redisio
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
crdb-crdb-redisio   ClusterIP   10.54.17.1   <none>        6379/TCP   6h21m

It connected to redis successfully

I need to know what you think about this solution?
Or you think, i should rather use some other API here?

Regards,
Sameer

**Comment by mrniko** [comment]
If kubernetes handles properly dns resolving then it should work
