### ISSUE TITLE
Redisson session key to much in redis

### ISSUE THREAD

**Issue by 1316151417** [redisson/redisson#2337]
Redisson session key is keeps increasing rapidly, now there are 300,000 key in redis, but HttpSessionListener can't get any sessionCreated even.

### Redis version
4

### Redisson version
2.15.2

### Redisson configuration
ignore

**Comment by mrniko** [comment]
Set `broadcastSessionEvents = true` for Redisson Tomcat Manager

**Comment by 1316151417** [comment]
> Set `broadcastSessionEvents = true` for Redisson Tomcat Manager
The problem remains...

![ktm](https://user-images.githubusercontent.com/30792405/65500877-89fcaa80-def2-11e9-8284-db09bf82f95a.jpg)

**Comment by 1316151417** [comment]
I gets a little events in log, but the redis key also is to much.

**Comment by mrniko** [comment]
There are no things to do on Redisson side if your tomcat instance generate too much sessions.

**Comment by 1316151417** [comment]
I think if tomcat generate session, I will get sessionCreated even.
I was confused why it happens, thank for your reply!
