### ISSUE TITLE
can redisson-lock support on codis or twemproxy or aliyun-redis?

### ISSUE THREAD

**Issue by sjyon** [redisson/redisson#2338]
I found that redisson-lock can not run well on aliyun-redis which cluster by proxy like code or twemproxy. Does anyone occour this problem?

**Comment by wangxingMachine** [comment]
请问你是怎么配置Redisson使用Coddis或者Twemproxy，服务地址是怎么配置的？

**Comment by sjyon** [comment]
> 请问你是怎么配置Redisson使用Codis或者Twemproxy，服务地址是怎么配置的？

现在项目中用的是aliyun-redis集群版，也就是类似于codis或者twemproxy，用的是单机配置直接连接代理节点。
在使用redisson-lock的时候发现sub命令有时候订阅不到消息，导致订阅锁的线程要等leasetime过后才能获取锁。
最后把具体的问题反馈给阿里云了，阿里云那边也发现了这个问题。

**Comment by wittychen** [comment]
> 在使用redisson-lock的时候发现sub命令有时候订阅不到消息，导致订阅锁的线程要等leasetime过后才能获取锁。

请问这个怎么解决的？
