### ISSUE TITLE
Use `Redisson.createBatch` method. It accumulates all invoked commands in one batch command.

### ISSUE THREAD

**Issue by madeeha-khan** [redisson/redisson#2339]
You can use it via `Redisson.createBatch` method. It accumulates all invoked commands in one batch command.

_Originally posted by @mrniko in https://github.com/redisson/redisson/issues/263#issuecomment-150294875_

How can we exactly do that?

**Comment by mrniko** [comment]
Here is an example https://github.com/redisson/redisson/wiki/10.-additional-features#103-execution-batches-of-commands

**Comment by madeeha-khan** [comment]
I am using createRedisBatch() from RedisAccessorBase.java class. Initialised redis client by calling super in my class.

`public class CacheAccessorImpl extends RedisAccessorBase  {
 public (RedisClient redisClient) {
    super(redisClient);
  }

public getListValues(List<String> keys) {
      RBatch rBatch = createRedisBatch();
 for (String key : keys) {
          RBucketAsync<Object> recommendationBucket = rBatch.getBucket(key);
        }
        List<?> result = rBatch.execute();
}
}`

Here, rBatch is always coming as null.
Previously I had used `RBucket<String> recommendationBucket = getRedisBucket("64783")`, from the same class `RedisAccessorBase.java`. It worked fine.

Let me know if I am missing  something.
