### ISSUE TITLE
RedisClient createBatch() returning null

### ISSUE THREAD

**Issue by madeeha-khan** [redisson/redisson#2341]
Here is an example https://github.com/redisson/redisson/wiki/10.-additional-features#103-execution-batches-of-commands

_Originally posted by @mrniko in https://github.com/redisson/redisson/issues/2339#issuecomment-534929733_

I tried using RedissonClient.createBatch(), its returning null. Whereas,     <V> RBucket<V> getBucket(String name) is working fine.

Can't figure out the issue behind this. I am extending RedissonClient and initialised its constructor.

**Comment by mrniko** [comment]
```java
RBatch batch = RedissonClient.createBatch();
```

Unable to reproduce, batch is not null.
