### ISSUE TITLE
ReplicatedServersConfig vs. MasterSlaveServersConfig

### ISSUE THREAD

**Issue by trasa** [redisson/redisson#2343]
While trying to track down an issue we had with AWS Elasticache redis + Redisson and a botched failover, this question came up -- "What is the difference between `config.useReplicatedServers()` and `config.useMasterSlaveServers()`?

The documentation suggests that ReplicatedServers is the right choice for Elasticache but doesn't go into more details. Thoughts?

Thanks
Tony

**Comment by mrniko** [comment]
Which Redisson version do you use? Can you share logs? Is there any exception?

> What is the difference between config.useReplicatedServers() and config.useMasterSlaveServers()

In ReplicatedServers Redisson updates topology but not in MasterSlaveServers.

**Comment by trasa** [comment]
version affected was 3.5.0; we had a hardware failure on an elasticache read node, and for about 20 minutes we had inconsistent results causing users to get login errors. 

![read and write to master 01 and slave 02](https://user-images.githubusercontent.com/1102368/65790925-79784a00-e115-11e9-9992-df4fd562a287.png)

**Comment by mrniko** [comment]
Could you update to the latest version? lot of issues were fixed since 3.5.0 version

**Comment by trasa** [comment]
Yes, we are working on that now, thanks.
