### ISSUE TITLE
listener execute multi times when register multi topics

### ISSUE THREAD

**Issue by Geek-S** [redisson/redisson#2345]
@Component
public class RedisMessageListenerConfig {

    @Bean
    RedisMessageListenerContainer container(RedisConnectionFactory connectionFactory,
                                            @Autowired @Qualifier("cacheHandlerAdapter") MessageListenerAdapter cacheHandlerAdapter,
                                            @Autowired @Qualifier("cacheHandlerAdapter1") MessageListenerAdapter cacheHandlerAdapter1) {
        RedisMessageListenerContainer container = new RedisMessageListenerContainer();
        container.setConnectionFactory(connectionFactory);
        container.addMessageListener(cacheHandlerAdapter, topic());
        container.addMessageListener(cacheHandlerAdapter1, topic1());

        return container;
    }

    @Bean
    MessageListenerAdapter cacheHandlerAdapter(CachePurgeHandler cachePurgeHandler) {
        return new MessageListenerAdapter(cachePurgeHandler);
    }

    @Bean
    MessageListenerAdapter cacheHandlerAdapter1(CachePurgeHandler1 cachePurgeHandler1) {
        return new MessageListenerAdapter(cachePurgeHandler1);
    }

    @Bean
    ChannelTopic topic() {
        return new ChannelTopic("CACHE_PURGE");
    }

    @Bean
    ChannelTopic topic1() {
        return new ChannelTopic("messageQueue");
    }
}

### Expected behavior
the listener execute multi times as the topics` size

### Actual behavior
execute one time

### Steps to reproduce or test case
redis-cli> PUBLISH messageQueue "{\"id\": 4, \"name\": \"xxoo\"}"

### Redis version
newest version

### Redisson version
3.11.4

### Redisson configuration
redis-spring-boot

**Comment by mrniko** [comment]
Fixed! Thanks for report
