### ISSUE TITLE
How can we have replication of Redis from one DC to another, but control the nodes Redissson connects to

### ISSUE THREAD

**Issue by mikebell90** [redisson/redisson#2353]
1. DC's . in LN and US
2. Want primaries + slaves in US, just replicas in LN
3. Want Sentinel HA
4. Want to hit the primaries+slaves in US when runnng service on US, LN would only be used with reconfigure/failover.

But it looks like the connection pool will try to spread over all slaves?

**Comment by mrniko** [comment]
You can use `org.redisson.connection.balancer.WeightedRoundRobinBalancer` or implement your own using `org.redisson.connection.balancer.LoadBalancer` interface
