### ISSUE TITLE
RedissonTopic subscribe lost connection

### ISSUE THREAD

**Issue by lizhyocx** [redisson/redisson#2354]
When using RedissonTopic，subscribe sucess and when publish message, can subscribe message success. Bug after a few days,publish message success, but cannot subscribe message.
I found some errors in redis log:
[22387] 07 Oct 00:00:30.521 - Reading from client: Connection reset by peer
[22387] 07 Oct 00:00:30.521 - Reading from client: Connection reset by peer
[22387] 07 Oct 00:00:30.521 - Reading from client: Connection reset by peer
[22387] 07 Oct 00:00:30.521 - Reading from client: Connection reset by peer

There no error in my application.

redisson version is 3.10.0

RTopic topic = redissonClient.getTopic(CacheKeyUtil.getMyTopic());
listenerId = topic.addListener(RedisTopicModel.class, (channel, topicModel) -> {
	LoggerUtil.info(getClass(), "redis topic listener,channel:{0},msg:{1}", channel, topicModel);
	// do something
});

Is connection reset but no reconnect?How can I resolved ?

**Comment by mrniko** [comment]
define pingConnectionInterval setting

https://github.com/redisson/redisson/wiki/2.-Configuration#pingconnectioninterval

**Comment by huyinmiao** [comment]
old version no pingConnectionInterval  parameter，how I do？
