### ISSUE TITLE
RMapCache Elimination Strategy does not work

### ISSUE THREAD

**Issue by Comven** [redisson/redisson#2358]
redisson version is 2.15.2，In a concurrent environment, the number of maps continues to grow, with 4000,000 pieces of data. When replaced by redisTemplate, only 100,000 pieces of data are run at the same time and remain unchanged. All data is set to an hour timeout

**Comment by mrniko** [comment]
Sorry, it's not clear.

You mean you have 4,000,000 RMapCache objects in Redis? How do you replace ttl and maxIdle functionality with RedisTemplate?

**Comment by Comven** [comment]
> Sorry, it's not clear.
> 
> You mean you have 4,000,000 RMapCache objects in Redis? How do you replace ttl and maxIdle functionality with RedisTemplate?

I changed the storage mode of RMapCache mode to key-value mode of redisTemplate，not use RMapCache。

**Comment by jackygurui** [comment]
You need to have Redisson running to manage the removal of elements inside RMapCache
