### ISSUE TITLE
Determining the number of running tasks for a RScheduledExecutorService

### ISSUE THREAD

**Issue by kaa-ghub** [redisson/redisson#2360]
I have the next example [https://github.com/kaa-ghub/redisson-sheduler](https://github.com/kaa-ghub/redisson-sheduler). 

### Expected behavior
I assume there should be an API with which I could find out if there are running tasks for a given executor manager.

```
RScheduledExecutorService executor = redissonClient.getExecutorService("defaultExecutor");
Map<?> tasks = executor.getTasks();
```

### Actual behavior
Each time when start the application, a new task is added and the running jobs are duplicated.

### Steps to reproduce or test case
Run a example two or more times.
### Redis version
5.0.3
### Redisson version
3.11.2
### Redisson configuration
[https://github.com/kaa-ghub/redisson-sheduler/blob/master/config/application.yml](https://github.com/kaa-ghub/redisson-sheduler/blob/master/config/application.yml)

**Comment by mrniko** [comment]
`RExecutorService.hasTask` method added. You can also use `RExecutorService.getTaskCount` method
