### ISSUE TITLE
HashCode of Value stored as Map differs 

### ISSUE THREAD

**Issue by tarunsharmaMG** [redisson/redisson#2365]
I am using following function code to insert data in redis : 
public List<Map<JioNSSFSnssai, HashSet<String>>> getAmfIdForTaiListSnssaiPair(List<JioNSSFTai> taiList) {

List<Map<JioNSSFSnssai, HashSet<String>>> resMap = new ArrayList<>();
        RBatch batch = redissonClient.createBatch(BatchOptions.defaults());
        for(JioNSSFTai tai :taiList) {
            batch.getMapCache("mapName").getAsync(tai);
        }

        BatchResult<?> res = batch.execute();

        for(int i=0 ;i<res.getResponses().size();i++) {
            Map<JioNSSFSnssai, HashSet<String>>mapData =(Map<JioNSSFSnssai, HashSet<String>>)res.getResponses().get(i);
            resMap.add(mapData);
            
        }
        return resMap;
	}

Value is a Map whose key is : JioNSSFSnssai

and Have defined this class as following with over-riding equals and hashcode :

public class JioNSSFSnssai {

	@SerializedName("sst")
	private Integer sst = null;

	@SerializedName("sd")
	private String sd = null;

	public Integer getSst() {
		return sst;
	}

	public void setSst(Integer sst) {
		this.sst = sst;
	}

	public String getSd() {
		return sd;
	}

	public void setSd(String sd) {
		this.sd = sd;
	}

	@Override
	public String toString() {
		return "JioNSSFSnssai [sst=" + sst + ", sd=" + sd + "]";
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		JioNSSFSnssai snssai = (JioNSSFSnssai) o;
		return com.google.common.base.Objects.equal(sst, snssai.sst) &&
				com.google.common.base.Objects.equal(sd, snssai.sd);
	}

	@Override
	public int hashCode() {
		int resp=com.google.common.base.Objects.hashCode(sst, sd);
		return resp;
	}
}

I see that HashCode of values key(JIONSSFSNSSAI) obtained from redis has changes , not sure whats the reason for it ?

As a result I can't perform operations on the obtained Map since equals and hashcode don't match to the same key.

**Comment by tarunsharmaMG** [comment]
Is it because Batch uses Generics in return type ?

**Comment by mrniko** [comment]
hashcode and equals methods aren't used by Redis

**Comment by gallog** [comment]
> hashcode and equals methods aren't used by Redis

could you link any docs about this spec?
