### ISSUE TITLE
Reads failing on replication mode when attempting to read immediately after write

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#2367]
Hello @mrniko 

We are facing an issue when using redisson with Elasticache with replication.

We are writing some 100K key value pairs to a map and then renaming it. Then we immediately attempt to read the same. It fails and redisson reports that the key does not exist.

Note that we have default values of read mode (SLAVE) and scan interval (1000ms) . Can you please suggest if changing to MASTER_SLAVE read mode can help in this. Also are there any configurations on redisson that we can try with. 

Thanks,
Yash

**Comment by mrniko** [comment]
You need to set readMode = MASTER
