### ISSUE TITLE
Migrate data from a Redis cluster to an other

### ISSUE THREAD

**Issue by bnjdpn** [redisson/redisson#2369]
### Expected behavior
I want to migrate data from an old Redis cluster to a new one programmatically, so I did this :

```
            legacyRedisClient.getKeys()
                .getKeys()
                .forEach(key -> {
                    LOGGER.info("Redis Migration : Migrating key {}", key);
                    Optional.of(legacyRedisClient.getBucket(key))
                            .filter(RObject::isExists)
                            .map(RBucket::get)
                            .ifPresent(value -> {
                                LOGGER.info("Redis Migration : Storing element with key {}", key);
                                RBucket<Object> bucket = encryptedRedisClient.getBucket(key);
                                bucket.set(value);
                                bucket.expire(48L, DAYS);
                            });
                });
```
The problem with this, is that I when I do `RBucket::get`, Redisson try to decode the value with a class that is not necessarily in the classpath (because that was set by an other microservice).

Is there a way to disable decoding in Redisson ? Or a better way to do this ?

### Redis version
3.2.6

### Redisson version
3.11.2

**Comment by mrniko** [comment]
Use getBucket with ByteArrayCodec.INSTANCE codec
