### ISSUE TITLE
保存值的时候，如果key带多个冒号分隔，存到redis里的key带冒号的会重复出现两次

### ISSUE THREAD

**Issue by yumendedao** [redisson/redisson#2375]
### Expected behavior
redis里的key显示为 limit:api:test=123
### Actual behavior
redis里的key显示为： limit:api:limit:api:test=123
### Steps to reproduce or test case

public static String wrap(String key){
 return "limit:api": + key
}

bucket = redisson.getBucket(wrap(“test”), codec)
bucket.set(“123”);

### Redis version
3.2.9
### Redisson version

<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-boot-starter</artifactId>
			<version>${redisson-spring-boot-starter.version.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.redisson</groupId>
					<artifactId>redisson-spring-data-21</artifactId>
				</exclusion>
				<exclusion>
					<artifactId>spring-boot-actuator-autoconfigure</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-data-20</artifactId>
			<version>${redisson-spring-boot-starter.version.version}</version>
		</dependency>
### Redisson configuration

clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  clientName: null
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
    - "redis://risk-redis1:7000"
    - "redis://risk-redis1:7001"
    - "redis://risk-redis2:7002"
    - "redis://risk-redis2:7003"
    - "redis://risk-redis3:7004"
    - "redis://risk-redis3:7005"
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO

**Comment by mrniko** [comment]
Unable to reproduce it with latest Redisson version

**Comment by yumendedao** [comment]
找到 问题了，是自己多封装了一次
