### ISSUE TITLE
[Q] Need details on entry updated

### ISSUE THREAD

**Issue by Flo354** [redisson/redisson#2377]
Hi there,

I am using redisson and just imagined a possible behavior on scaled environments.

I have a Redisson Map like that: 

```java
public abstract class BaseAuthMapEntry implements MyDataSerializable {

    /**
     * The website for the session
     */
    private BaseWebsite website;

    ...

    public BaseWebsite getWebsite() {
        return website;
    }

    public void setWebsite(BaseWebsite website) {
        this.website = website;
    }

    @Override
    public ObjectNode toJson() {
        ObjectNode node = mapper.createObjectNode();
        node.put("website_id", website.getId().toString());

        return node;
    }

    @Override
    public void fromJson(ObjectNode json) {
        verifyString(json, "website_id");
        website = BaseWebsite.getById(json.get("website_id").asText());
    }
}
```
Where `MyDataSerializable` is my custom serializer for redisson.
Where `BaseWebsite` is a bean stored in database

Imagine I have two instances which have in memory this map entry.
Now one of them update the BaseWebsite's object and then do a "map.fastput(id, object);"

Since the website_id didn't change, when the other instance will do "map.get(id);", will the map entry be refetched and the website's object reloaded or not?

Thanks,

**Comment by mrniko** [comment]
The map entry will be reloaded

**Comment by Flo354** [comment]
Thanks for your answer!
