### ISSUE TITLE
Hibernate with Redisson (L2 cache) : invalidate cache when adding a @Column to @Entity

### ISSUE THREAD

**Issue by bnjdpn** [redisson/redisson#2378]
### Expected behavior
When I add a `@Column` on an `@Entity`, I want Redisson to invalidate the cache, so to do this I manually change the `region` property in the `@Cache` annotation.

Is there a better way to do this ?

### Actual behavior
When I add a `@Column` on an `@Entity` with `@Cache`, I got an exception when Redisson try to fetch the entity in Redis.

### Redisson version
3.11.2

**Comment by mrniko** [comment]
You can do it like this:

```java
SessionFactory.getCache().evictEntityRegion()
```

**Comment by bnjdpn** [comment]
> You can do it like this:
> 
> ```java
> SessionFactory.getCache().evictEntityRegion()
> ```

In my case I have a Redis cluster used for Hibernate cache in many applications who have in common my `@Entity` classes, so I don't thnk it will works : 
- Application A starts with a new column in an entitity and evicts cache
- And in parallel if application B use an old version of the entity, I will have an exception in application A when trying to get data in cache.

**Comment by johnou** [comment]
The only solutions I see are either creating a new cache region or using a different encoder eg. JsonJacksonCodec, or KryoCodec ( https://github.com/EsotericSoftware/kryo#compatiblefieldserializer ).
