### ISSUE TITLE
【咨询】Redisson数据结构带来的垃圾数据不过期的问题

### ISSUE THREAD

**Issue by HashZhang** [redisson/redisson#2384]
Redisson的各种数据结构实现还是很精致的，例如Rlock由key，hash还有channel组合而成，RSemaphore由一个key和channel组成。
但是我发现有个疑问，就是假设我用订单id作为key，使用RSemaphore或者RLock，那么就会产生很多不会过期的key，但是这个订单实际上已经处理完了，不会再用到这些key，那么这些key是否只能通过redis自己的LRU过期呢，有没有什么更好的办法？

**Comment by jackygurui** [comment]
通常的讲，一个分布式的数据结构可以被任何节点在任何时间使用，即便现在没有节点使用它，并不代表不会有人使用它。对于Redisson来讲，一个分布式锁不会因为某个节点宕机了，它就没有存在的意义。只有你自己的业务才有这个判断的能力，才知道在什么时候，这个数据结构就不再需要了，这需要你在合适的地方自己去控制，客户端是没有这个判断能力的。

**Comment by HashZhang** [comment]
好的，谢谢
