### ISSUE TITLE
RScheduledExecutorService two usage attention

### ISSUE THREAD

**Issue by zhangdc007** [redisson/redisson#2386]
### Expected behavior
test RScheduledExecutorService as demo:
`
public static void main(String[] args) {
    Config config = new Config();
    config.useClusterServers()
        .addNodeAddress("127.0.0.1:7001", "127.0.0.1:7002", "127.0.0.1:7003");
    
    RedissonClient redisson = Redisson.create(config);

    RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
    nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("myExecutor", 10));
    RedissonNode node = RedissonNode.create(nodeConfig);
    node.start();

    RExecutorService e = redisson.getExecutorService("myExecutor");
    e.execute(new RunnableTask());
    e.submit(new CallableTask());
    e.schedule(new RunnableTask(), CronSchedule.of("0/10 * * * * ?"));
    e.shutdown();
    node.shutdown();
}

`
and run 2 JVM 
Expected: every 10 second only one thread run in one of two JVM
### Actual behavior
has one run thread in both JVM in evety 10 second
shutdown one JVM ,has two run thread in the other JVM.

is that mean: one JVM schedule task , multiple JVM run as woker？
### Redis version
3.2.4
### Redisson version
3.11.5
### Redisson configuration
as demo.

**Comment by zhangdc007** [comment]
other problem ：
the excutorName in redis could be bad
In some situation，the excutorName in redis may be has bad data,and if next debug I run the test ,the RScheduledExecutorService whill be shutdown state in begining ,if submit ,will throw exception:
`
throw new RejectedExecutionException("Task rejected. ExecutorService is in shutdown state");
`

`
 RScheduledExecutorService executorService = client.getExecutorService(excutorName);
`
and if schedule in bad excutorName,will schedual multiple run thread,and can not change frequency

**Comment by zhangdc007** [comment]
中文版：
2个问题
1：e.schedule(new RunnableTask(), CronSchedule.of("0/10 * * * * ?"));
的时候，发现只能一个JVM去启动任务，其他多个JVM作为worker执行，这样才可以保证分布式定时，
但是我们的大部分场景是启动任务的JVM也是多个实例，代码一样，这样的话，会导致多个任务在启动
2：测试发现 RScheduledExecutorService获取的时候，需要一个名字，这个名字是在redis 会创建几个数据，这个数据容易”损坏“，会导致RScheduledExecutorService 以获取就是shutdown状态，不可用，或者导致定时任务无法变更时间等，需要在redis 删除，才正常，那这样，不知道什么原因的损坏数据，在生产中，会变得不敢使用，

**Comment by zhangdc007** [comment]
对于第一个问题，现在理解了，应该是需要一个任务发起的服务去发起，其他的工作者自己工作，需要一个控制台，去管理这些服务
第二个问题，只能说小心一些，应该是只会在调试的时候出问题

**Comment by mrniko** [comment]
you can run RedissonNode in any other JVM and use multiple JVM to schedule task, and multiple JVM to run it.
