### ISSUE TITLE
Redis server response timeout (3000 ms) occured for command: (EVAL) with params

### ISSUE THREAD

**Issue by jaxling** [redisson/redisson#2387]
`org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, redPacket:delivery_reward:userId:1185439964859547664:refSeqId:1189793440456589337:1, 10000, ebe570ad-6760-482a-a0e2-4d46f394963d:474] channel: [id: 0x67e3c291, L:/10.40.4.23:37930 - R:172.16.3.80/172.16.3.80:17001]
at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:711)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471)
at java.lang.Thread.run(Thread.java:748)`

### Redisson configuration：`
        ClusterServersConfig clusterServersConfig = config.useClusterServers();
        clusterServersConfig.setScanInterval(2000);
        List<String> nodes = Arrays.asList(StringUtils.split(redisProp.getClusterNodes(), ','));
        for (String node : nodes) {
            clusterServersConfig.addNodeAddress("redis://" + node);
        }
        clusterServersConfig.setPingConnectionInterval(60);
        //设置对于master节点的连接池中连接数最大为500
        clusterServersConfig.setMasterConnectionPoolSize(1000);
        //设置对于slave节点的连接池中连接数最大为500
        clusterServersConfig.setSlaveConnectionPoolSize(1000);
        //如果当前连接池里的连接数量超过了最小空闲连接数，而同时有连接空闲时间超过了该数值，那么这些连接将会自动被关闭，并从连接池里去掉。时间单位是毫秒。
        clusterServersConfig.setIdleConnectionTimeout(10000);
        //同任何节点建立连接时的等待超时。时间单位是毫秒。
        clusterServersConfig.setConnectTimeout(30000);
        //等待节点回复命令的时间。该时间从命令发送成功时开始计时。
        clusterServersConfig.setTimeout(3000);
        //当与某个节点的连接断开时，等待与其重新建立连接的时间间隔。时间单位是毫秒。
        clusterServersConfig.setIdleConnectionTimeout(3000);
        clusterServersConfig.setPassword(redisProp.getPassword());
        return Redisson.create(config);`

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by jaxling** [comment]
> https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

I'm trying to change nettyThread to fix it ,thank you
