### ISSUE TITLE
RedissonMapCache destroy

### ISSUE THREAD

**Issue by LionOnTheChase** [redisson/redisson#2389]
@Test
    public void testDestroy()
    {
        RMapCache mapCache = null;
        
            mapCache = redissonClient.getMapCache("testDestroy");
           // assertTrue(mapCache.trySetMaxSize(5));

            for(int i=0;i<10;i++){
                mapCache.put("abc"+i, i,1, TimeUnit.DAYS);
            }
            assertEquals(5,mapCache.size());

            for(int i=0;i<5;i++){
                assertNull("Expected "+"abc"+i+" to be evicted",mapCache.get("abc"+i));
            }
            mapCache.destroy();
            Object test = mapCache.get("abc9");
            assertEquals(null,test);

        
    }
### Expected behavior
after mapCache.destroy() any lookup on mapCache should return null.

### Actual behavior
mapCache is not destroyed. It is still returning old values.

### Redisson version
3.11.3

**Comment by mrniko** [comment]
You need to invoke `clear` method as well
