### ISSUE TITLE
CommandAsyncService get 很慢

### ISSUE THREAD

**Issue by jlulimo** [redisson/redisson#2390]
### Expected behavior
每次通过获取一个 集合例如Map，之后Map.get(key)，这一句很慢，因为get 有闭锁 await 每次都要在10ms 左右。
### Actual behavior
怎么能让我的 get 快一些，只是涉及并发读取而已
### Redisson version
3.11.3

**Comment by jackygurui** [comment]
10m太不正常了。把使用方式发出来看看行吗？
