### ISSUE TITLE
Question - LocalCacheMapOptions - Eviction Policy/TTL

### ISSUE THREAD

**Issue by garct** [redisson/redisson#2392]
If I were to set the EvictionPolicy and TimeToLive in the LocalCachedMapOptions when creating a new RLocalCachedMap, does this actually do anything?  
Will each entry added to the map get this TTL set to it?  If so, would I be able to configure the redis server to expire entries whose TTL has past?

It is my understanding that the LocalCachedMap does not actually support eviction unless you are using Redisson Pro.

**Comment by mrniko** [comment]
Yes, EvictionPolicy and TimeToLive are applied to RLocalCachedMap instance if they defined.

> Will each entry added to the map get this TTL set to it? 

Only entry stored in local cache get this ttl not entry stored in Redis.

> If so, would I be able to configure the redis server to expire entries whose TTL has past?

to apply ttl for Redis you need to use RLocalCachedMapCache or RMapCache object (without local cache)
