### ISSUE TITLE
Question - is it possible to configure redisson to use multiple codecs ?

### ISSUE THREAD

**Issue by gbarsky** [redisson/redisson#2394]
is it possible to configure multiple codecs ?
we are trying to use redisson for tomcat session replication . 
not all our session attributes are serializable, so we cannot use codec which relies on java serialization 
i was wondering if we can specify in redisson.yaml list of codecs:
something like that:
codec: !<org.redisson.codec.JsonJacksonCodec> {}, org.redisson.codec.FstCodec  ?

**Comment by mrniko** [comment]
It's not possible to use define multiple codecs in configuration
