### ISSUE TITLE
Improve thread visibility in AsyncSemaphore

### ISSUE THREAD

**Issue by joongsoo** [redisson/redisson#2398]
`counter` variable in `AsyncSemaphore` is not volatile variable.
but `getCounter()` method is public, and not synchronized.

`getCounter()` method is possible access by many thread. (not in now. but may be possible in the future.)
so add `volatile` keyword to `counter` variable.

### Redisson version
redisson-3.11.5 (latest)

**Comment by mrniko** [comment]
Good point! Fixed
