### ISSUE TITLE
Node: NodeSource [slot=1019, addr=redis://*.*.*.*:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet Error Class: class org.redisson.client.RedisNodeNotFoundException

### ISSUE THREAD

**Issue by SaiP061** [redisson/redisson#2401]
# Expected behavior
I am using AWS Elastic cache with cluster mode enabled and after scale out (adding more shards we see below errors from Redisson client on application layer 
with Error Message: Node: NodeSource [slot=1019, addr=redis://*.*.*.*:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet Error Class: class org.redisson.client.RedisNodeNotFoundException

### Actual behavior

New node and slot changes need to be auto discovered and scale out should be seam less without failures.

### Redis version
5.0.4

### Redisson version
3.11.1

**Comment by mrniko** [comment]
hasn't been discovered yet means that AWS cluster info hasn't been updated to that moment. You can also decrease `scanInterval` interval to update cluster state more frequently.

**Comment by SaiP061** [comment]
I don’t think that cluster info is not updated in elasticcache..  because
If I use redis cli and run cluster nodes command  I can see new nodes and
slots Info updated.. also I see expection even after entire cluster Is
marked available

One more observation is that issue goes away if I restart application.. I
am suspecting it has something to do with asynchronous node discovery
handler.. new nodes are not getting autodiscovered

Also current scan interval is 2 sec.. which should be okay guess..

**Comment by mrniko** [comment]
Could you provide logs with `debug` level for `org.redisson` package to clarify this?

**Comment by turaleck** [comment]
@mrniko I am running in this same problem.

Redisson 3.11.2
AWS Redis Engine 5.0.4
Cluster Enable (one shard, two nodes)

I configured Redisson with `useClusterServers` and `addNodeAddress(<configuration endpoint provided by aws console>)`

Here is what I see in the logs: 

```
logger: org.redisson.connection.pool.MasterConnectionPool
message: 24 connections initialized for <config-url>/ip:6379
```

```
logger: org.redisson.connection.DNSMonitor
message: DNS monitoring enabled; Current masters: {rediss://<config-url>}, slaves: {}
```

```
message: Detected DNS change. Master rediss://<config-url>:6379 has changed ip from blah to blah
```

```
logger: org.redisson.connection.pool.MasterPubSubConnectionPool
message: 1 connections initialized for <confi-url>/blah:6379
```

```
logger: org.redisson.connection.SingleEntry
message: master <config-url>/blah:6379 has changed to <config-url>/blah:6379
```

```
exception: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=4632, addr=redis://<node-url>:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:559)
	at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:863)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:671)
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:766)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at java.base/java.lang.Thread.run(Thread.java:834)

   level: ERROR
   message: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=4632, addr=redis://<node-url>:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet
```

**Comment by turaleck** [comment]
A minute after the first `RedisNodeNotFoundException`, the same same exception is still being thrown. I'm not sure what the scan interval is, but I'd expect all the nodes to have been discovered after 1 minute

**Comment by mrniko** [comment]
> I'd expect all the nodes to have been discovered after 1 minute

It depends on cluster node info. If it contains redis node then no exception is thrown.

**Comment by mrniko** [comment]
FIxed in https://github.com/redisson/redisson/issues/2750
