### ISSUE TITLE
Serialization codec

### ISSUE THREAD

**Issue by sheldon-markk** [redisson/redisson#2402]
Question

We are currently using the Kryo serializer, whenever these is a change to the object cached we have to invalidate entire cache else we face serialization errors.

How can we support backwards compatibility for already cached objects?

### Redis version
5.0
### Redisson version
3.11.3

**Comment by sibmaks** [comment]
We have the same issue, but we use `org.redisson.codec.SerializationCodec`. We can't use JSON like codes, because we have some recursive objects links.

**Comment by sibmaks** [comment]
@mrniko can you help with this? Or clarify how we can deal with it. It will be great if at least redisson invalidate session in case of deserialization issue, currently, it returned a null object.

**Comment by sheldon-markk** [comment]
We solved this by creating out own CustomKryoCodec class and adding the following

```
            Kryo kryo = new Kryo();
            if (this.classLoader != null) {
                kryo.setClassLoader(this.classLoader);
            }
            /* versioni*/
            kryo.setDefaultSerializer(VersionFieldSerializer.class);
```

**Comment by mrniko** [comment]
You can extend Kryo5Codec and override `createKryo` method.
