### ISSUE TITLE
Redistribution session sharing, memory leak

### ISSUE THREAD

**Issue by MyGodIT** [redisson/redisson#2408]
### Actual behavior
Redistribution session sharing, memory leak
3.11.4：
![image](https://user-images.githubusercontent.com/29084833/68584936-cbccba80-0478-11ea-86a4-b9ba586914f2.png)

3.11.5（after program run 15min）：
![image](https://user-images.githubusercontent.com/29084833/68584739-57921700-0478-11ea-8097-cde763b8edd6.png)

### Redis version
5.0.4

### Redisson version
3.11.5 & 3.11.4

### Redisson configuration

<redisson:client id="redissonClient"
		codec-ref="fstCodec">
		<redisson:cluster-servers
		   scan-interval="10000"
						password="passwod"
						subscription-connection-minimum-idle-size="100"
						subscription-connection-pool-size="400" 
						slave-connection-minimum-idle-size ="100"
						slave-connection-pool-size="400"
						master-connection-minimum-idle-size ="100"
						master-connection-pool-size="400"
						read-mode="SLAVE"
						subscription-mode="SLAVE">
						
						....
		</redisson:cluster-servers>
</redisson:client>

<bean id="redissonHttpSessionConfiguration" class="org.redisson.spring.session.config.RedissonHttpSessionConfiguration">
    	<property name="maxInactiveIntervalInSeconds" value="180"/>
    </bean>

**Comment by mrniko** [comment]
Could you share the memory dump to clarify the cause?

**Comment by MyGodIT** [comment]
> Could you share the memory dump to clarify the cause?

Hi, I had sent the dump file download url. pls check

**Comment by mrniko** [comment]
Sorry I don't see the link in issue description

**Comment by MyGodIT** [comment]
> Sorry I don't see the link in issue description

I had send to your email.  (yefyufudre@enayu.com)

**Comment by mrniko** [comment]
@MyGodIT 

I didn't get it

**Comment by MyGodIT** [comment]
> @MyGodIT
> 
> I didn't get it

http://47.252.77.90:8080/mydump.dump

**Comment by MyGodIT** [comment]
Hi,this is the download url:
http://47.252.77.90:8080/mydump.dump




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikita Koksharov"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 晚上8:59
收件人:&nbsp;"redisson/redisson"<redisson@noreply.github.com&gt;;
抄送:&nbsp;"红帽"<3112362028@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redisson/redisson] Redistribution session sharing, memory leak (#2408)




@MyGodIT
 
I didn't get it

**Comment by MyGodIT** [comment]
@mrniko 
Hi,
Have you received the dump file？

**Comment by mrniko** [comment]
Unable to open it:
```
Error: Invalid heap dump file.
 Unsupported segment type 0x0 at position 0x40780176
Error: Invalid heap dump file.
 Unsupported segment type 0x0 at position 0x40780176
```

**Comment by MyGodIT** [comment]
@mrniko 
Sorry, I had executed command multiple times( jmap -dump:live,format=b,file=mydump.dump pid ), and load it to MAT or use jhat, it's always show this problem. I haven't found out why.

For memory leak problem, I wonder why ChannelName have so many instances, my program is mainly used for session sharing under high concurrency. Is it possible that the objects stored in HashMap are not removed？

**Comment by mrniko** [comment]
In which hashMap?
