### ISSUE TITLE
redisson cannot close

### ISSUE THREAD

**Issue by zhuyaoming** [redisson/redisson#2410]
my application is jar project not web application project , init redisson run my task, but redisson cannot shutdown.

redisson have Daemon thread?

how ido to shutdown .when my task run over.?

**Comment by mrniko** [comment]
You should shutdown it by `Redisson.shutdown()` method.

**Comment by zhuyaoming** [comment]
> You should shutdown it by `Redisson.shutdown()` method.

need manual do  redisson.shutdown()?

@Bean(destroyMethod = "shutdown")
public RedissonClient redisson(){
}

**Comment by mrniko** [comment]
@zhuyaoming 

yes
