### ISSUE TITLE
Dynamic Lock IDs

### ISSUE THREAD

**Issue by DALDEI** [redisson/redisson#2412]
More a question of use case then an issue -- unless the answer is "Cant do that"

I have some small 'microservice' type processes (running in docker ECS on AWS).  One thing they do is pocess S3 filels on change notificaiton.  Im subscribing to a SNS topic which then gets routeed and load balnced to an avoaible node.   For some operations I want to 'lock' a segment of code identifyed by the S3 Path -- Like a pool of ionotify workers. 
Since the spae of possible key values is large and unknown upfront I cant pre-allocate locks. 
Rather when a node gets an event I want it to 'lock' such that other nodes if they get the ssame event can be (cooperatively) kept from operrating on the same file at th3es ame time.
 (inthe same process or a differnt process) In a period of an hour -- hundreds or thousands of unique keys/files may occur.  The operations while locked may vary from ms to munltiple minutes.  I realize I will likely have to treat these cases differnt -- (keep a map of locked node)

My question is this.  I tried a 'simplistic' approch which carates a NEW lock structure on eveyr eent, passing it the unique IID vailel Then after 'work' is complete releasing the lock.
Other apps may be doing the same thing and they should block in some way sothey dont both operatioe on the same file.   This seems to *work* --but I dont know if its effective.
For exmaple -- how 'expensive' is it to allodate a new lock.
If I simply 'unlock a loc does that delete it from Redis ?   What do I need to do to 'release' the lock  fully?  THen assumign all went well -- what is the latency to examime a lock ot sed if its sill in use ?  
There will be hundreds of uniquie Ids --  Is there a better dataa type for this ?  Maybe a combonation of a Map and Lock ?
Any suggestions welcom.

**Comment by mrniko** [comment]
> how 'expensive' is it to allodate a new lock

Each lock allocates pubsub channel and holds until lock acquisition moment.

> If I simply 'unlock a loc does that delete it from Redis ?

Yes, it does.

> Is there a better dataa type for this ?

I'm afraid no. if you have an idea I'm ready to consider it.
