### ISSUE TITLE
PublishSubscribeService#freePubSubConnections to be per cluster node ?

### ISSUE THREAD

**Issue by lwyza** [redisson/redisson#2413]
### Expected behavior
Subscribe/connect to the cluster node specific to the topic

### Actual behavior
Great chance to subscribe/connect to wrong cluster node

### Steps to reproduce or test case
2-1. subscribe to topic 1, correct cluster node connected/subscribed
2-2. subscribe to topic 2 from different cluster node, but still node of topic 1 is connected/subscribed

### Redis version
5 (@ Elastic Cache)

### Redisson version
3.11.5

### Redisson configuration
new Config().useClusterServers().addNodeAddress( DNS2ElasticCache)

Brainstorming:

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java#L174
has
                PubSubConnectionEntry freeEntry = freePubSubConnections.peek();
                if (freeEntry == null) {
                    connect(codec, channelName, promise, type, lock, listeners);
                    return;
                }

When "freeEntry == null", PublishSubscribeService#connect does the right thing by locating cluster node via topic.

Nonetheless, when "freeEntry != null", topic 2 of above reproduction would use connection to topic 1 cluster node. For example of cluster of 5 nodes, we experienced 80% chance topic 2 appeared successfully subscribed, but never notified.

Maybe PublishSubscribeService#freePubSubConnections can be per cluster node ?

Additionally, ClusterConnectionManager#calcSlot parses key out of "{KEY}..." to locate cluster node, any chance to extend it to support Redis format of "__keyspace*__:KEY" such as the one from redisson/src/test/java/org/redisson/RedissonTopicTest.java please ?

More additionally, any chance to extend ClusterConnectionManager to subscribe/connect to *all* cluster nodes for non-key based topics "__keyevent@*" such as the ones from redisson/src/main/java/org/redisson/RedissonObject.java & redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java please ?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/579
