### ISSUE TITLE
单点模式Redisson，看门狗时间3s，获取锁后断点停留一会，锁自动释放为什么？续借的条件是什么？

### ISSUE THREAD

**Issue by mingsnever** [redisson/redisson#2414]
RLock lock = null;
        try{
            // 2.加锁
            String lockName = new StringBuilder(eConstant.LockInfo.CAPITAL_BUS_ORDER_LOCK_PRE)
                    .append(requestDTO.getMerchNo())
                    .append(requestDTO.getMernsNo()).toString();
            lock = RedissLockUtil.tryGetLock(lockName, 3);
            if (null == lock) {
                System.out.println("【下单】-【mensNo:" + requestDTO.getMerchTransNo() + "】-【lockName:" + lockName + "】-【当前锁被占用】");
                throw new Exception(OrderManageConstant.Enum.ORDER_IN_PROCESS.getCode(), OrderManageConstant.Enum.ORDER_IN_PROCESS.getDetail());
            }
            Integer periods = requestDTO.getPeriods();
            System.out.println("开始处理业务");
            Thread.sleep(periods);//睡一段时间
            System.out.println("结束处理业务1");
            Thread.sleep(3000);//睡一段时间
            System.out.println("1:"+lock.isHeldByCurrentThread());
            System.out.println("结束处理业务2");
            System.out.println("2:"+lock.isHeldByCurrentThread());
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            System.out.println("3:"+lock.isHeldByCurrentThread());
            if (null != lock) {
                System.out.println("【下单】-【mensNo:" + requestDTO.getMernsNo() + "】-【锁被释放】");
                while (lock.isHeldByCurrentThread()){
                    System.out.println("释放锁");
                    RedissLockUtil.unlock(lock);
                }
            }
        }

### Expected behavior
服务正常的情况下，锁应该由RedissLockUtil.unlock(lock);释放吧
### Actual behavior
在 System.out.println("1:"+lock.isHeldByCurrentThread()); 断点停留一会，输出false,该线程已经不持有锁了，看门狗自己释放了锁？看门狗的续期判断条件是什么
### Redis version
aliyun-redis新版本
### Redisson version
3.9.1
### Redisson configuration
redssion.config.address = redis://${spring.redis.host}:${spring.redis.port}
redssion.config.password = ${spring.redis.password}
redssion.config.timeout = 3000
redssion.config.connectionPoolSize = 8
redssion.config.connectionMinSize = 0
redssion.config.watchdogTimeout = 3000

**Comment by mingsnever** [comment]
Redisson单点模式

**Comment by mingsnever** [comment]
//代码中获取锁的方法
public static RLock tryGetLock(String lockKey,int waitTime) {
        RLock lock = redissonClient.getLock(lockKey);
        try {
            boolean isGetLock = lock.tryLock(waitTime, TimeUnit.SECONDS);
            if(isGetLock){
                return lock;
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }

**Comment by mingsnever** [comment]
![1574220317(1)](https://user-images.githubusercontent.com/55399353/69206761-8dc24b80-0b88-11ea-8728-5aab62c393e9.jpg)

**Comment by mingsnever** [comment]
![1574220317(1)](https://user-images.githubusercontent.com/55399353/69206786-a92d5680-0b88-11ea-8634-5aa120e1ee68.jpg)

**Comment by mingsnever** [comment]
Integer periods = busOrderingConfirmRequestDTO.getPeriods();
            System.out.println("开始处理业务");
            Thread.sleep(periods);
            System.out.println("结束处理业务1");
            Thread.sleep(3000);
            System.out.println("1:"+lock.isHeldByCurrentThread());
            System.out.println("结束处理业务2");
            System.out.println("2:"+lock.isHeldByCurrentThread());
在System.out.println("1:"+lock.isHeldByCurrentThread());停留一会

输出：

开始处理业务
结束处理业务1
1:false

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/2.-Configuration#lockwatchdogtimeout

Watchdog removes the lock since you blocked the thread in debug mode. So thread became unresponsive during watchdog timeout interval.

**Comment by patzheng** [comment]
被这个差点搞得自闭

**Comment by patzheng** [comment]
> RLock 锁 = 空； try{ // 2.加锁 String lockName = new StringBuilder(eConstant.LockInfo.CAPITAL_BUS_ORDER_LOCK_PRE) .append(requestDTO.getMerchNo()) .append(requestDTO.getMernsNo()).toString(); lock = RedissLockUtil.tryGetLock(lockName, 3); if (null == lock) { System.out.println("【下单】-【mensNo:" + requestDTO.getMerchTransNo() + "】-【lockName:" + lockName + "】-【当前锁被占用】 "); 抛出新异常（OrderManageConstant.Enum.ORDER_IN_PROCESS.getCode(), OrderManageConstant.Enum.ORDER_IN_PROCESS.getDetail()); } 整数周期= requestDTO.getPeriods（）; System.out.println("开始处理业务"); Thread.sleep(periods);//睡眠 结束System.out.println("处理业务1"); Thread.sleep(3000);//睡睡眠 System.out.println"1:"+lock.isHeldByCurrentThread()); System.out.println("结束处理业务2"); System.out.println("2:"+lock.isHeldByCurrentThread()); }catch (Exception e){ e.printStackTrace(); }finally { System.out.println("3:"+lock.isHeldByCurrentThread()); if (null != lock) { System.out.println("【下单】-【mensNo:" + requestDTO.getMernsNo() + "】-【锁被释放】"); while (lock.isHeldByCurrentThread()){ System.out.println("释放锁"); RedissLockUtil.unlock(lock); } } }
> 
> ### 预期行为
> 服务正常释放的情况下，锁应该由RedissLockUtil.unlock(lock);吧
> 
> ### 实际行为
> 在 System.out.println("1:"+lock.isHeldByCurrentThread()); 断点释放锁一会，输出假，该我已经不抓锁了，看门狗自己了？看门狗的续期判断条件是什么
> 
> ### 重现或测试用例的步骤
> ### Redis版本
> aliyun-redis新版本
> 
> ### 雷迪森版
> 3.9.1
> 
> ### Redisson 配置
> redssion.config.address = redis://${spring.redis.host}:${ spring.redis.port } redssion.config.password = ${ spring.redis.password } redssion.config.timeout = 3000 redssion。 config.connectionPoolSize = 8 redssion.config.connectionMinSize = 0 redssion.config.watchdogTimeout = 3000

解决了吗？
