### ISSUE TITLE
Tomcat Redis Session Manager & Scoped Spring Beans as dependecies problem

### ISSUE THREAD

**Issue by bkurent** [redisson/redisson#2417]
Hi,

I'm using Tomcat Redis Session Manager. Our application uses Spring Beans with scoped beans as dependencies:
https://docs.spring.io/spring/docs/5.1.5.RELEASE/spring-framework-reference/core.html#beans-factory-scopes-other-injection

### Expected behavior

Autowired session scoped bean member of a singleton bean should preserve its state/value inside same session.

### Actual behavior

Autowired session scoped bean member of singleton bean does not preserve its state/value inside same session. Right after setting some (primitive) field of this session bean, it returns empty value (e.g. empty string). 

### Steps to reproduce or test case

Example source code:

```
//singleton class
import org.springframework.beans.factory.annotation.Autowired;
public class TestSingletonBean  {
	
	@Autowired
    private TestSessionBean testSessionBean;
	
	public void manageSessionBean() {
		if (testSessionBean.getValue == null || testSessionBean.getValue.equals("")) {
			testSessionBean.setValue("123");
		} 
		System.out.println("Value : " + testSessionBean.getValue()); //retuns empty string ("") each time!!
	}

}
```

```
//session class
import java.io.Serializable;
public class TestSessionBean implements Serializable {
    private String value = "";

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```

Spring Bean definitions:
```
    <bean id="testSingletonBean" class="com.package.TestSingletonBean">
    </bean>

    <bean id="testSessionBean" class="com.package.TestSessionBean" scope="session">
        <aop:scoped-proxy proxy-target-class="true"/>
    </bean>
```

### Redis version
5.0.6

### Redisson version
3.11.3

### Redisson configuration
redisson.yaml:

sentinelServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 2000
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 128
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  sentinelAddresses:
  - "REDIS_IP_PORT0"
  - "REDIS_IP_PORT1"
  - "REDIS_IP_PORT2"
  masterName: "mymaster"
  database: 0
threads: 16
nettyThreads: 128
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Unable to reproduce. Here are my objects used in test:

```java
@WebServlet(name = "/testServlet", urlPatterns = "/*")
public class TestServlet extends HttpServlet {

    private static final long serialVersionUID = 1243830648280853203L;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        HttpSession session = req.getSession();

        if (req.getPathInfo().equals("/test-session-bean")) {
            WebApplicationContext application = WebApplicationContextUtils.getRequiredWebApplicationContext(getServletContext());
            MyBean testSessionBean = application.getBean(MyBean.class);
            testSessionBean.manageSessionBean();
        }
    }
    
}

@EnableRedissonHttpSession
@Configuration
@ComponentScan({"com.my.bean"})
public class HttpConfig {

    @Bean
    public RedissonClient redisson() {
        return Redisson.create();
    }
    
    @Bean
    public SessionEventsListener listener() {
        return new SessionEventsListener();
    }
    
    @Bean(WebHttpHandlerBuilder.WEB_HANDLER_BEAN_NAME)
    public WebHandler dispatcherHandler(ApplicationContext context) {
        return new DispatcherHandler(context);
    }
    
}

@Service
public class MyBean {

    @Autowired
    private TestSessionBean testSessionBean;

	public void manageSessionBean() {
            if (testSessionBean.getValue() == null || testSessionBean.getValue().equals("")) {
                testSessionBean.setValue("123");
            }
            System.out.println("Value : " + testSessionBean.getValue()); //retuns empty string ("") each time!!
	}

}

@Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
@Service
public class TestSessionBean implements Serializable {

    private String value = "";

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```

**Comment by bkurent** [comment]
Hi @mrniko  
thanks for your response!

I'm not using Spring session library dependency with @EnableRedissonHttpSession configuration like in your last post above. I only use Redis based Tomcat Session Manager (https://github.com/redisson/redisson/tree/master/redisson-tomcat),
everything else is the same as before I switched from in-memory session to Redis Tomcat Session Manager.

Maybe I misunderstood the documentation, but is it necessary to use also Spring Session support (https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#146-spring-session) 
when using Redis based Tomcat Session Manager with application which uses Spring beans with scopes? 

Before I made a transition from in-memory session to Redisson-Tomcat, I didn't use Spring Session library (only Spring-beans, spring-context, spring-aop, spring-web libraries) and this scoped beans and aop proxy mechanism all worked ok.

**Comment by mrniko** [comment]
Sorry, I didn't get. if you don't use EnableRedissonHttpSession then how spring connect session store?

**Comment by spetar** [comment]
Please reopen this issue or merge with: https://github.com/redisson/redisson/issues/2476

**Comment by mrniko** [comment]
@spetar 

I already gave explanation https://github.com/redisson/redisson/issues/2417#issuecomment-557021456
