### ISSUE TITLE
ScoredSortedSet如何批量返回key,value集合，实现zscan功能

### ISSUE THREAD

**Issue by wuxingye** [redisson/redisson#2418]
### Redis version
3.11.3

**Comment by wuxingye** [comment]
zscan是可以批量返回key, value结构的，但是redisson只能返回key

RScoredSortedSet中方法如下
    /**
     * Returns an iterator over elements in this set.
     * Elements are loaded in batch. Batch size is defined by <code>count</code> param.
     * If pattern is not null then only elements match this pattern are loaded.
     * 
     * @param pattern - search pattern
     * @param count - size of elements batch
     * @return iterator
     */
    Iterator<V> iterator(String pattern, int count);

**Comment by mrniko** [comment]
what is the issue?

**Comment by wuxingye** [comment]
Thanks for your response. I wanna ask how i can get sorted set data(key, value) by batch mode. Thank you again!

**Comment by mrniko** [comment]
did you try to define count param in iterator method?

**Comment by wuxingye** [comment]
but this method below

Iterator iterator(String pattern, int count);

just contains value, but score

![image](https://user-images.githubusercontent.com/9107702/69408472-ed178b80-0d41-11ea-8f91-f67a351c9d88.png)

**Comment by mrniko** [comment]
You need to use getScore method

**Comment by wuxingye** [comment]
It works, thank you
