### ISSUE TITLE
how to change the data storage mode from hset to set?

### ISSUE THREAD

**Issue by jiamine** [redisson/redisson#2422]
For example:
   When i execute the monitor command in redis , i find that this is how redisson inserts data into redis:
  "HSET" "redisson:tomcat_session:8857D47589287BA71D31C005908FCCE8.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:FE7EDCA68AD5DB0A01F325879B1AA9D9.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:03400FDD3420684FCC8C32701DDE211E.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:82BC237110D13AACBEA52B87B1AF2ABF.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:3741174D47890E4352DD6BCCC7E76EF9.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:ACDF98FFA873891028FD73A9F2D00620.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:D453DEA42BD6C30A84486DA7C9AFB4F0.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:3B2F751911427DE5D44E81CCF7035414.tc22101-1" "session:isNew" "\xef"
"HSET" "redisson:tomcat_session:C05A623E4E951ABD80AA757165F1D2BF.tc22101-1" "session:isNew" "\xef"
....................................
I want to use 'set'  to insert data into redis instead.
As shown below:
  "SET" "redisson:tomcat_session:8857D47589287BA71D31C005908FCCE8.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:FE7EDCA68AD5DB0A01F325879B1AA9D9.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:03400FDD3420684FCC8C32701DDE211E.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:82BC237110D13AACBEA52B87B1AF2ABF.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:3741174D47890E4352DD6BCCC7E76EF9.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:ACDF98FFA873891028FD73A9F2D00620.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:D453DEA42BD6C30A84486DA7C9AFB4F0.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:3B2F751911427DE5D44E81CCF7035414.tc22101-1" "session:isNew" "\xef"
"SET" "redisson:tomcat_session:C05A623E4E951ABD80AA757165F1D2BF.tc22101-1" "session:isNew" "\xef"

how to do that??????

**Comment by jiamine** [comment]
help!!!!!

**Comment by mrniko** [comment]
You are free to implement own Tomcat Session Manager which store session through set method
