### ISSUE TITLE
data not persisted after application restart

### ISSUE THREAD

**Issue by gcameo** [redisson/redisson#2425]
Just trying out Redisson to see if its right for our product. Whenever I restart my application, all data that I have written to Redis disappear even if the Redis database hasn't itself restarted. Is it because Redisson only works as in-memory and doesn't actually write to the Redis Database?

I am very new to this so excuse me if I am missing something fundamental

Regards

**Comment by mrniko** [comment]
I'm afraid you're mistaken. Redisson is a Java client for Redis database. All objects don't maintain any state on Java side but Redis. Could you're not clear Redis on app startup.

**Comment by gcameo** [comment]
Thanks very much. I tried another client and realised same behaviour. Its my understanding of Redis that is lacking! I will close this issue. Thanks

**Comment by mrniko** [comment]
You can activate Redis persistence https://redis.io/topics/persistence
