### ISSUE TITLE
BloomFiler设置了过期时间，并发较高时不能正常删除

### ISSUE THREAD

**Issue by lzw1017400172** [redisson/redisson#2434]
redis_version:4.0.11
redisson_version:...
问题：对BloomFiler设置过期时间，并发较高时不能正常删除。{key}:config正常清除，key会变成永久有效。
`        
        String key = "test_bloomFilter";
        RBloomFilter<Object> temp = redissonClient.getBloomFilter(key);
        temp.tryInit(550000L, 0.03);
        temp.add("{}");
        temp.expire(5, TimeUnit.SECONDS);
        for(int i = 0;i<10000000;i++){
            temp.add(i);
            //Thread.sleep(500);
        }
`
![image](https://user-images.githubusercontent.com/22362190/69704533-8ffb4b80-112e-11ea-81c5-fb2db10e05b0.png)
到达过期时间之后，test_bloomFilter变为永久存在，并且布隆过滤器正常工作。
降低并发能力，上述问题将不存在。

**Comment by mrniko** [comment]
Similar to https://github.com/redisson/redisson/issues/1305 Which Redisson version do you use?
