### ISSUE TITLE
redisson 中的锁，怎么通过Redis Desktop Manager中看到

### ISSUE THREAD

**Issue by kakukeme** [redisson/redisson#2435]
// 多久会自动释放，
int leaseTime = 60;
int waitTime = 5;
RLock rLock = redisson.getLock(one.getId());
try {
    boolean flag = rLock.tryLock(waitTime, leaseTime, TimeUnit.SECONDS);

    if (flag) {
        log.info("取到锁");
        executorThread.submit(new SinglePipelineContinueRunExecutor(customPipelineHistory));
        rLock.unlock();
        log.info("释放锁");
    }

} catch (Exception e) {
    log.error(e.getMessage());
} finally {
    rLock.unlock();
}

redisson 中的锁，怎么通过Redis Desktop Manager中看到
### Redisson version
3.11.5

**Comment by jackygurui** [comment]
普通的RLock是以HASH的形式保存的

**Comment by walkersing** [comment]
RLock rLock = redisson.getLock(one.getId());
one.getId() 就是key 啊
