### ISSUE TITLE
Redlock implement 

### ISSUE THREAD

**Issue by DarrenJiang1990** [redisson/redisson#2436]
the usage of RedissonMultiLock :

   RLock lock1 = client1.getLock("lock1");
    RLock lock2 = client1.getLock("lock2");
    RLock lock3 = client2.getLock("lock3");

    RedissonMultiLock lock = new RedissonRedLock(lock1, lock2, lock3);

  so ,according to the redlock algorithm, how should i ensoure lock1-lock3 finally  stored in different redis master in redis  cluster

**Comment by mrniko** [comment]
In cluster you need to locate locks manually.
