### ISSUE TITLE
 Redlock implement   #2436

### ISSUE THREAD

**Issue by DarrenJiang1990** [redisson/redisson#2437]
he usage of RedissonMultiLock :

RLock lock1 = client1.getLock("lock1");
RLock lock2 = client1.getLock("lock2");
RLock lock3 = client2.getLock("lock3");

RedissonMultiLock lock = new RedissonRedLock(lock1, lock2, lock3);
so ,according to the redlock algorithm, how should i ensoure lock1-lock3 finally stored in different redis master in redis cluster

@mrniko  do not easily close my issue！

i just want to  ask  how should i  “locate locks manually” ， i have no idea how to ensure   keys of a  RedissonRedLock  distributed throughout redis masters in a redis cluster

that is to say , if i want get a redlock  in a 3 masters-slavses of  redis clusrer， how shoud i define  3 name of key  to implement    redlock by redisson.

lockkey1  -->  master1;
lockkey2  -->  master2;
 lockkey3  -->  master3;

thanks, this is very important  to those use redisson

**Comment by DarrenJiang1990** [comment]
any idea

**Comment by mrniko** [comment]
Just use RLock method it's now in sync with slaves so solve the problem which RedLock tried to solve.
