### ISSUE TITLE
Add feature to get low level details about redis instances using RedissonClient

### ISSUE THREAD

**Issue by kuldeepsidhu88** [redisson/redisson#2439]
### Expected behavior
We should have a way to get low level details(e.g. memory details, client list etc) about redis instances using RedissonClient.
Or
We should be able to get single RedisConnection from pool of connection via RedissonClient.

### Actual behavior
Currently we don't have a way to do it. We can get these details from RedisClient object.

### Steps to reproduce or test case
RedissonClient is injected into spring container on startup. 
I want to get low-level details about redis instances. What could be the best way to do it. 
Can I get single connection from pool of connection to get the details?

### Redis version
5.0+
### Redisson version
3.11.5
### Redisson configuration
I am using `redisson-spring-boot-starter` for connecting to redis instances using RedissonClient.
I am making use of `spring.redis.redisson.config=classpath:redisson.yaml` property for setting the yaml configuration.

https://stackoverflow.com/questions/57375464/connection-pooling-with-redisson#comment104377724_57543993

**Comment by kuldeepsidhu88** [comment]
@mrniko Please have a look. Let me know if more details are required. Please update the issue description if necessary.

**Comment by mrniko** [comment]
Did you try to use info provided by `Node.info` returned by `RedissonClient.getNodesGroup` method ?

**Comment by mrniko** [comment]
You need to use `org.redisson.api.RedissonClient.getRedisNodes()` method for that purpose.
