### ISSUE TITLE
set the max block time for method  lock()

### ISSUE THREAD

**Issue by DarrenJiang1990** [redisson/redisson#2441]
first ，i  set a key “lock” with no expiration in redis。
then  i use  lock  like the following:
`RLock lock=redissonClient.getLock("lock");`
        `try{`
           ` lock.lock();`
            `dosth();`
      `  }`
       ` catch(Exception ex){`
       ` //`
        `}`
      `  finally {`
      `      lock.unlock();`
       ` }`

after running,the program was blocking continuously at the  code line of `lock.lock();`

is this a bug or can i set a parm such as max time of waitting lock?

thanks.

**Comment by mrniko** [comment]
you can use `tryLock` with waitTime parameter

**Comment by DarrenJiang1990** [comment]
> you can use `tryLock` with waitTime parameter


is watch log  effective in this way?
