### ISSUE TITLE
setIdleConnectionTimeout参数不生效

### ISSUE THREAD

**Issue by weifei7544** [redisson/redisson#2443]
redisson json配置
{
  "masterSlaveServersConfig":{
    "idleConnectionTimeout":10,
    "connectTimeout":10000,
    "timeout":10000,
    "retryAttempts":3,
    "retryInterval":1500,
    "failedSlaveReconnectionInterval":3000,
    "failedSlaveCheckInterval":60000,
    "password":null,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "loadBalancer":{
      "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "subscriptionConnectionMinimumIdleSize":1,
    "subscriptionConnectionPoolSize":1,
    "slaveConnectionMinimumIdleSize":10,
    "slaveConnectionPoolSize":15,
    "masterConnectionMinimumIdleSize":10,
    "masterConnectionPoolSize":15,
    "readMode":"SLAVE",
    "subscriptionMode":"SLAVE",
    "database":0,
    "keepAlive": false
  },
  "threads":16,
  "nettyThreads":32,
  "codec":{
    "class":"org.redisson.codec.FstCodec"
  },
  "transportMode":"NIO"
}

 public RedissonCluster(List<RedisPair> redises) {
        this.redises = redises;
        redisClients = new ArrayList<>(redises.size());
        redises.forEach(redisPair -> {
            try {
                System.out.println("start");
                Config config = Config.fromJSON(new File("redisson.json"));
                config.useMasterSlaveServers().setIdleConnectionTimeout(1000);
                config.setAddressResolverGroupFactory(new DnsAddressResolverGroupFactory());
                config.useMasterSlaveServers().setMasterAddress(redisPair.master).addSlaveAddress(redisPair.slave);
                config.setCodec(StringCodec.INSTANCE);
                RedissonClient redisClient = Redisson.create(config);
                redisClients.add(redisClient);
          } catch (Exception e) {
                System.out.println(e);
            }

        });
        batchOptions = BatchOptions.defaults().executionMode(ExecutionMode.IN_MEMORY)
                .responseTimeout(10, TimeUnit.SECONDS).retryInterval(10, TimeUnit.SECONDS).retryAttempts(2);

    }

现象是不断的DNS检测，重新进行初始化，之前建立的连接并没有释放掉，导致redis连接数过多，引起崩溃

**Comment by mrniko** [comment]
You should invoke `config.useMasterSlaveServers()` only once.
```java
config.useMasterSlaveServers().setMasterAddress(redisPair.master).addSlaveAddress(redisPair.slave).setIdleConnectionTimeout(1000);
```
