### ISSUE TITLE
Why ExpirableSemaphore does not expire?

### ISSUE THREAD

**Issue by aaabramov** [redisson/redisson#2444]
@mrniko, could you take a look at this question: https://stackoverflow.com/questions/59073355/is-there-some-kind-of-lock-semaphore-with-idle-ttl?

### Redis version
**3.2**

### Redisson version
**3.11.6**

### Redisson configuration

    singleServerConfig:
      address: redis://127.0.0.1:6379
      timeout: 300
      connectTimeout: 1000
      keepAlive: true
      pingConnectionInterval: 3000
      pingTimeout: 300
      connectionMinimumIdleSize: 8
      connectionPoolSize: 16

**Comment by mrniko** [comment]
zset contains timeout doesn't expire when object expiration was set.

**Comment by mrniko** [comment]
Please provide the test code to reproduce the issue

**Comment by belyal** [comment]
Actually, when I specify TTL, the semaphore key is removed after a while, but not the "{some-key}:timeout".

How to reproduce:
```
  val semaphore = redisson.getPermitExpirableSemaphore("some-key")
  semaphore.trySetPermits(1)
  semaphore.expire(30, TimeUnit.SECONDS)
  val permitId = semaphore.tryAcquire(10, 10, TimeUnit.SECONDS)
```
Check in redis-cli:
```
127.0.0.1:6379> keys *
1) "{some-key}:timeout"
2) "some-key"
127.0.0.1:6379>
```
After a while:
```
127.0.0.1:6379> keys *
1) "{some-key}:timeout"
127.0.0.1:6379>
```
Note: I do not delete the semaphore intentionally.

**Comment by mrniko** [comment]
Fixed

**Comment by aaabramov** [comment]
@mrniko when do you plan to release 3.11.7 version?

**Comment by aaabramov** [comment]
Confirming that fix works:
![image](https://user-images.githubusercontent.com/11317222/73127590-46629c00-3fcb-11ea-93d9-e5915b03b607.png)

**Comment by mrniko** [comment]
@aaabramov 

Thanks for your feedback
