### ISSUE TITLE
请问如何类似于jedis 在操作某个命令时select database

### ISSUE THREAD

**Issue by vagrantBottle** [redisson/redisson#2446]

**Comment by mrniko** [comment]
Use `database` setting

**Comment by vagrantBottle** [comment]
Config config = new Config();        
    config.useSingleServer().
                setAddress("redis://").
                setPassword();
    config.useSingleServer().setDatabase(0).   
		..........


   RedissonClient redissonClient2 = Redisson.create(config);


.....................



    RBucket<String> test = redissonClient2.getBucket("test");
    test.set("testv",60, TimeUnit.SECONDS);
    System.out.println(test.get());//testv
      

    RBucket<String> test2 = this.redissonClient.getBucket("test2");
        test2.set("test2v",160, TimeUnit.SECONDS);
        test2.move(9);

        System.out.println(test2.get());//null
我如何获取test2的值

**Comment by mrniko** [comment]
you need to have separate Redisson instance connected to database with index 9 to read moved value

**Comment by vagrantBottle** [comment]
好的 谢谢,不过希望能够在同一个实例里面切换index
