### ISSUE TITLE
select database  

### ISSUE THREAD

**Issue by vagrantBottle** [redisson/redisson#2447]
Config config = new Config();        
    config.useSingleServer().
                setAddress("redis://").
                setPassword();
    config.useSingleServer().setDatabase(0).   
		..........

   RedissonClient redissonClient2 = Redisson.create(config);

.....................

    RBucket<String> test = redissonClient2.getBucket("test");
    test.set("testv",60, TimeUnit.SECONDS);
    System.out.println(test.get());//testv
      

    RBucket<String> test2 = this.redissonClient.getBucket("test2");
        test2.set("test2v",160, TimeUnit.SECONDS);
        test2.move(9);

        System.out.println(test2.get());//null

我如何获取test2的value

**Comment by vagrantBottle** [comment]
test这个key是要放在0库,test2这个key 放在9库,单机版

**Comment by mrniko** [comment]
Since you set database = 0 in Redisson config it can't be used to read data from any other database.
