### ISSUE TITLE
Update documentation to RMapReactive

### ISSUE THREAD

**Issue by Slava96** [redisson/redisson#2448]
Method 'putIfAbsent' at javadoc says:
    /**
     * Associates the specified <code>value</code> with the specified <code>key</code>
     * only if there is no any association with specified<code>key</code>.
     * <p>
     * If {@link MapWriter} is defined then new map entry is stored in write-through mode.
     *
     * @param key - map key
     * @param value - map value
     * @return <code>null</code> if key is a new one in the hash and value was set.
     *         Previous value if key already exists in the hash and change hasn't been 

But method wrap null as empty Mono and return Mono.empty() instead of null.

Try to check it with this 
Mono<Boolean> mono = redisChecksumRepository.save(“digest”, “id”);
StepVerifier.create(mono)
            .expectComplete()
            .verify();
    }

Redis version - 5.0.4
Redisson version - 3.10.5

**Comment by Slava96** [comment]
Also for 'get' method and other

**Comment by mrniko** [comment]
Fixed
