### ISSUE TITLE
Spring boot with redisson 3.11.5 fails without optional actuator dependency

### ISSUE THREAD

**Issue by ehontoria** [redisson/redisson#2449]
It looks like the file `RedissonCacheMeterBinderProvider` needs a `ConditionalOnClass` annotation, otherwise it isn't working with Spring boot 2 without the optional actuator dependency.

**Comment by ehontoria** [comment]
Relates to pull request https://github.com/redisson/redisson/pull/2450

**Comment by ehontoria** [comment]
It seems like the actuator has caused problems previously and was fixed with a similar pull request here https://github.com/redisson/redisson/issues/852

**Comment by mrniko** [comment]
Merged. Thanks for contribution.
