### ISSUE TITLE
ElasticCache - How to use configuration endpoint instead of node addresses?

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#2456]
Is there a way to use configuration endpoint with clusterServersConfig instead of using individual node addresses?

**Comment by mrniko** [comment]
just define endpoint address

**Comment by anilkonduru** [comment]
I tried following configuration and it didn't work for me.


{
   "clusterServersConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "password":null,
      "subscriptionsPerConnection":5,
      "clientName":"{client.name}",
      "loadBalancer":{
         "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
      },
      "slaveSubscriptionConnectionMinimumIdleSize":1,
      "slaveSubscriptionConnectionPoolSize":50,
      "slaveConnectionMinimumIdleSize":10,
      "slaveConnectionPoolSize":64,
      "masterConnectionMinimumIdleSize":10,
      "masterConnectionPoolSize":64,
      "readMode":"MASTER",
      "nodeAddresses":[
         "{Configuration Endpoint}:6379"
      ],
      "scanInterval":1000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":null,
   "useLinuxNativeEpoll":false
}

**Comment by mrniko** [comment]
What do you mean doesn't work. Does it throw any exception?

**Comment by anilkonduru** [comment]
my bad, i missed redis protocol in the endpoint and adding that worked with above config. Thanks.
