### ISSUE TITLE
默认序列化编码与wiki上的不一致

### ISSUE THREAD

**Issue by QweikChris** [redisson/redisson#2458]
默认序列化编码与wiki上的不一致

wiki写的是 Jackson JSON 编码 默认编码
实际代码是org.redisson.codec.FstCodec
```
 public Config(Config oldConf) {
        setExecutor(oldConf.getExecutor());

        if (oldConf.getCodec() == null) {
            // use it by default
            oldConf.setCodec(new FstCodec());
        }
```

**Comment by falling-w** [comment]
There is the same problem in comments.
`    /**
     * Redis key/value codec. FST codec is used by default
     */
    private Codec codec;`

`/**
     * Redis key/value codec. Default is json-codec
     *
     * @see org.redisson.client.codec.Codec
     * 
     * @param codec object
     * @return config
     */
    public Config setCodec(Codec codec) {
        this.codec = codec;
        return this;
    }`

`    /**
     * Redis 'slave' node minimum idle connection amount for <b>each</b> slave node
     */
    private int slaveConnectionMinimumIdleSize = 24;
`
`  /**
     * Minimum idle connection pool size for subscription (pub/sub) channels
     * <p>
     * Default is <code>10</code>
     * <p>
     * @see #setSlaveConnectionPoolSize(int)
     * 
     * @param slaveConnectionMinimumIdleSize - pool size
     * @return config
     */
    public T setSlaveConnectionMinimumIdleSize(int slaveConnectionMinimumIdleSize) {
        this.slaveConnectionMinimumIdleSize = slaveConnectionMinimumIdleSize;
        return (T) this;
    }`

**Comment by jauadoc** [comment]
+1 
文档写的默认jackson，我们从3.9升级到3.11之后序列化看源码变成了FST，导致数据无法反序列化。

**Comment by jauadoc** [comment]
@QweikChris  试试换成jackson序列化，也就是原来的默认序列化，还没试，不过别人说可行。  https://github.com/redisson/redisson/issues/2262

**Comment by mrniko** [comment]
FSTCodec is default one. Javadocs fixed.
