### ISSUE TITLE
RMap.addAndGet is not compatible with get/put methods by using default codec

### ISSUE THREAD

**Issue by bluelullaby** [redisson/redisson#2460]
By using default codec `FstCodec`, put/get methods is not compatible with `addAndGet` method. When calling `RMap,get` after `RMap.addAndGet`, the program will throw `DecoderException`.
### Expected behavior
return the changed value
### Actual behavior
throw exception
### Steps to reproduce or test case
```java
Config config = new Config();
config.useSingleServer()
	 .setAddress("redis://127.0.0.1:6379");
RedissonClient client = Redisson.create(config);
RMap<String, Integer> map = client.getMap("mykey");
map.addAndGet("count", 1);
System.out.println(map.get("count"));
client.shutdown();
```
### Redis version
5.0.7
### Redisson version
3.11.6
### Redisson configuration
default configuration

**Comment by mrniko** [comment]
This is a limitation. Use StringCodec to overcome it.
