### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.springframework.data.redis.connection.ReactiveRedisConnectionFactory

### ISSUE THREAD

**Issue by wingyiu** [redisson/redisson#2464]
3.11.6 witch spring boot 1.5.7

boot up fail 
````
Caused by: java.lang.ClassNotFoundException: org.springframework.data.redis.connection.ReactiveRedisConnectionFactory
````

**Comment by mrniko** [comment]
please update spring boot to 2.1+

**Comment by xiaoyifang** [comment]
> Integrates Redisson with Spring Boot library. Depends on Spring Data Redis module.

>Supports Spring Boot 1.3.x, 1.4.x, 1.5.x, 2.0.x, 2.1.x, 2.2.x

this means ,it does not support 1.3.x,1.4.x,1.5.x .

**Comment by mrniko** [comment]
as option you can downgrade to `redisson-spring-data-18` for spring boot 1.5.x support

**Comment by sww0825521xy** [comment]
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.13.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.redisson</groupId>
                    <artifactId>redisson-spring-data-22</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-data-18</artifactId>
            <version>3.13.1</version>
        </dependency>
