### ISSUE TITLE
Redisson prints sentinel has down messages frequently

### ISSUE THREAD

**Issue by arunpmohan** [redisson/redisson#2471]
Version 3.11.6

**Expected behavior**
Should not print this logs frequently

**Actual behavior**
When connected to redis deployed in kubernetes and sentinel address is a headless kubernetes SVC.

{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:17:59.945+0000", "timezone":"UTC", "log":"[redisson-netty-2-1]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:17:59.952+0000", "timezone":"UTC", "log":"[redisson-netty-2-14]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.70.93:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:02.296+0000", "timezone":"UTC", "log":"[redisson-netty-2-32]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:03.959+0000", "timezone":"UTC", "log":"[redisson-netty-2-23]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:05.979+0000", "timezone":"UTC", "log":"[redisson-netty-2-1]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:05.985+0000", "timezone":"UTC", "log":"[redisson-netty-2-2]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:07.329+0000", "timezone":"UTC", "log":"[redisson-netty-2-5]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:07.986+0000", "timezone":"UTC", "log":"[redisson-netty-2-1]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:12.330+0000", "timezone":"UTC", "log":"[redisson-netty-2-28]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:14.001+0000", "timezone":"UTC", "log":"[redisson-netty-2-1]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:17.374+0000", "timezone":"UTC", "log":"[redisson-netty-2-15]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:18.009+0000", "timezone":"UTC", "log":"[redisson-netty-2-18]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.53.138:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:20.022+0000", "timezone":"UTC", "log":"[redisson-netty-2-9]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:20.025+0000", "timezone":"UTC", "log":"[redisson-netty-2-21]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.53.138:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:22.421+0000", "timezone":"UTC", "log":"[redisson-netty-2-1]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:24.033+0000", "timezone":"UTC", "log":"[redisson-netty-2-9]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:27.455+0000", "timezone":"UTC", "log":"[redisson-netty-2-20]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:28.042+0000", "timezone":"UTC", "log":"[redisson-netty-2-9]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.53.138:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:34.059+0000", "timezone":"UTC", "log":"[redisson-netty-2-17]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:34.062+0000", "timezone":"UTC", "log":"[redisson-netty-2-29]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.53.138:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:37.545+0000", "timezone":"UTC", "log":"[redisson-netty-2-16]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:38.072+0000", "timezone":"UTC", "log":"[redisson-netty-2-19]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:42.546+0000", "timezone":"UTC", "log":"[redisson-netty-2-24]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:44.085+0000", "timezone":"UTC", "log":"[redisson-netty-2-19]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:47.589+0000", "timezone":"UTC", "log":"[redisson-netty-2-4]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:48.097+0000", "timezone":"UTC", "log":"[redisson-netty-2-9]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:52.629+0000", "timezone":"UTC", "log":"[redisson-netty-2-10]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:54.110+0000", "timezone":"UTC", "log":"[redisson-netty-2-9]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:57.663+0000", "timezone":"UTC", "log":"[redisson-netty-2-13]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:18:58.121+0000", "timezone":"UTC", "log":"[redisson-netty-2-19]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:02.706+0000", "timezone":"UTC", "log":"[redisson-netty-2-19]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:04.134+0000", "timezone":"UTC", "log":"[redisson-netty-2-21]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:06.145+0000", "timezone":"UTC", "log":"[redisson-netty-2-17]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:06.147+0000", "timezone":"UTC", "log":"[redisson-netty-2-25]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:07.740+0000", "timezone":"UTC", "log":"[redisson-netty-2-3]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:08.154+0000", "timezone":"UTC", "log":"[redisson-netty-2-20]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:10.164+0000", "timezone":"UTC", "log":"[redisson-netty-2-19]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:10.167+0000", "timezone":"UTC", "log":"[redisson-netty-2-26]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:12.741+0000", "timezone":"UTC", "log":"[redisson-netty-2-13]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:14.174+0000", "timezone":"UTC", "log":"[redisson-netty-2-17]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:17.778+0000", "timezone":"UTC", "log":"[redisson-netty-2-18]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:18.185+0000", "timezone":"UTC", "log":"[redisson-netty-2-32]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:24.206+0000", "timezone":"UTC", "log":"[redisson-netty-2-17]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:24.212+0000", "timezone":"UTC", "log":"[redisson-netty-2-2]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.15.231:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:27.814+0000", "timezone":"UTC", "log":"[redisson-netty-2-8]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:28.221+0000", "timezone":"UTC", "log":"[redisson-netty-2-4]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:32.853+0000", "timezone":"UTC", "log":"[redisson-netty-2-12]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:34.234+0000", "timezone":"UTC", "log":"[redisson-netty-2-4]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:37.885+0000", "timezone":"UTC", "log":"[redisson-netty-2-16]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:38.243+0000", "timezone":"UTC", "log":"[redisson-netty-2-17]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:42.885+0000", "timezone":"UTC", "log":"[redisson-netty-2-22]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 added " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:44.252+0000", "timezone":"UTC", "log":"[redisson-netty-2-25]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;192.168.53.138:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"WARN ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:48.267+0000", "timezone":"UTC", "log":"[redisson-netty-2-4]  org.redisson.connection.SentinelConnectionManager(:495) - sentinel: redis:&#x2F;&#x2F;10.254.205.39:26379 has down " }
{ "type":"log", "host":"smp0006node07", "level":"INFO ", "systemid":"solemn-llama-smp-core-deployment-c4d4967bc-qbjkw", "system":"SMP", "time":"2019-12-12T17:19:48.270+0000", "timezone":"UTC", "log":"[redisson-netty-2-5]  org.redisson.connection.SentinelConnectionManager(:554) - sentinel: redis:&#x2F;&#x2F;192.168.53.138:26379 added " }

**Redis version**
5.0.5
**Redisson version**
3.11.6

**Comment by mrniko** [comment]
Similar to https://github.com/redisson/redisson/issues/2303

**Comment by liyuntao** [comment]
@mrniko  No, that's misleading. The root cause is one should use headless service when Redis Sentinel is deployed under Kubernetes. Or the lib would lookup to cluster-IP and try to add it again and again, thus disconnect-update logic leads to another sentinel member keeps disconnect. 
Better add it to docs.

@arunpmohan  You should configure headless service name to Redisson's config.

**Comment by mrniko** [comment]
> Better add it to docs.

Could you propose the changes with example for Kubernetes?

**Comment by liyuntao** [comment]
Well, the operation is simple, just replace redisHost to the service name of headless-service in Redisson's config. 

Users may(mostly may not) need to manually add a headless service in Kubernetes first and better have a conceptual understanding of [headless-services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) first.

Mostly, if the Redis-cluster were deployed by official Helm or bitname/charts e.g. [bitnami/charts/redis-cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster), a pre-defined headless-service is ready out of box for usage.

below is mine delployment using bitnami chart. Which I could directly pick the name `redis-cluster-headless` as redisHost in connecting URL.
```bash
kubectl get services -n storage
NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
redis-cluster                             ClusterIP   10.233.16.39    <none>        6379/TCP,26379/TCP   47d
redis-cluster-headless                    ClusterIP   None            <none>        6379/TCP,26379/TCP   47d
```

**Comment by RaickyDerwent** [comment]
@liyuntao Can you please provide an example of how the Redisson config looks like ? I'm having trouble figuring out how to configure the `addSentinelAddress()` methods.
