### ISSUE TITLE
Subscribe timeout  AND Unable to send command AND Redis server response timeout

### ISSUE THREAD

**Issue by zpczpczpc** [redisson/redisson#2473]
Expected behavior
Not seeing this error

Actual behavior
org.redisson.client.RedisTimeoutException: Redis server response timeout (30000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, post_20191213016601000001_lock, 30000, 63992f0b-f210-4490-8777-24c6338a0def:413] channel: [id: 0x02268d01, L:/10.143.92.47:37348 - R:/10.152.10.200:6379]
	at org.redisson.command.CommandAsyncService$11.run(CommandAsyncService.java:696)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:745)

org.redisson.client.RedisTimeoutException: Unable to send command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, post_20191213016601000001_lock, 30000, f01dae77-5e41-4505-ac10-82e1e02dccd9:404] after 3 retry attempts 	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:542) 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663) 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738) 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466) 	at java.lang.Thread.run(Thread.java:745)
--

org.redisson.client.RedisTimeoutException: Subscribe timeout: (39000ms)
--

jedis version
2.8.2

Redisson version
2.10.4

Redisson configuration

 SingleServer
subscriptionConnectionMinimumIdleSize=10
subscriptionConnectionPoolSize=100
connectionMinimumIdleSize=32
connectionPoolSize=128
timeout=30000
retryAttempts=3
retryInterval=3000
subscriptionsPerConnection=10
nettyThreads=200
subscriptionConnectionMinimumIdleSize=20
Other defaults

redis slowlog has some time-consuming commands

use  demo:

 public <T> T tryLock(long waitTime, long leaseTime, TimeUnit timeUnit, boolean fairLock) throws Exception  {
        RLock lock = getLock(getLockName(), fairLock);
        try {
            if (lock.tryLock(waitTime, leaseTime, timeUnit)) {
             //dosomething
            }
            else {
            }
        } catch (Exception e) {
 
        } finally {
            try {
                if (lock != null && lock.isLocked() && lock.isHeldByCurrentThread()) {
                    lock.unlock();
                }
            }
            catch (Exception e)
            {
            }
        }
    }

**Comment by zpczpczpc** [comment]
@jackygurui @mrniko  please help me look at these questions,thx

**Comment by mrniko** [comment]
please refer to this topic https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by zpczpczpc** [comment]
@mrniko thank you for your reply， I have adjusted following this suggestion，should i continue to increase nettyThreads？Or adjust other parameters？

**Comment by mrniko** [comment]
To overcome Subscribe timeout you need to increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters

**Comment by zpczpczpc** [comment]
@mrniko ok,i wiil try,but "org.redisson.client.RedisTimeoutException: Unable to send command" this question how to resolve?

**Comment by mrniko** [comment]
you need also check your network
