### ISSUE TITLE
无法自动删除锁

### ISSUE THREAD

**Issue by 3792274** [redisson/redisson#2477]
**代码如下，无法自动删除锁，锁会一直续命**

 
![image](https://user-images.githubusercontent.com/19231863/70864971-06070b80-1f93-11ea-84a0-47c4cb4336a8.png)

 
`

    @GetMapping("/testLock")
    public void testLock() {
      new Thread(() -> executeRedis()).start();
 
    }
 
    public void executeRedis(){
        final ExecutorService executor = Executors.newSingleThreadExecutor();
        FutureTask<Integer> future = new FutureTask(new RedisCallable(new Date()));
        executor.submit(future);
        try {
            int result = future.get(5L, TimeUnit.SECONDS);
            log.error("=================,Thread Finish，Result：{}",JSON.toJSONString(result));
        } catch (Exception e) {
            log.error("=================,Thread Error：{}",e.getMessage(),e);
        }finally {
            future.cancel(true);
            executor.shutdownNow();
        }
    }

    @Data
    @AllArgsConstructor
    class RedisCallable implements Callable<Integer> {
        private Date date ;
        @Override
        public Integer call(){
            return  redisOpts(date);
        }
    }

    public Integer redisOpts(Date startTimeStamp){
        redisLock(startTimeStamp);
        return 1;
    }

  

    public void redisLock(Date startTimeStamp) {
        boolean isLock = false;
        RLock lock = redisService.getRedisLock("CanNotAutoDeleteLockKey-LOCK");
        try {
            isLock = lock.tryLock(60*1000L, TimeUnit.SECONDS);    
            if (isLock ) {
                   // sleep(15);
                    while( (System.currentTimeMillis()-startTimeStamp.getTime())/1000 <=10){
                        log.error("Execute.......{}" , (System.currentTimeMillis()-startTimeStamp.getTime())/1000  );
                }
            }
        } catch (InterruptedException e) {
            log.error("redisLock-ERROR:{}",e.getMessage(),e);
        } finally {
            if (isLock && lock.isLocked())
                lock.unlock();
        }
    }
`

**Comment by 3792274** [comment]
![image](https://user-images.githubusercontent.com/19231863/70864945-ab6daf80-1f92-11ea-97d7-e4282b9ba951.png)

**Comment by 3792274** [comment]
@mrniko 大概多久？

**Comment by mrniko** [comment]
You defined lease time = 60*1000L seconds, please be attentive.

**Comment by 3792274** [comment]
@mrniko 

> You defined lease time = 60*1000L seconds, please be attentive.
>对不起，是的，我犯了个错，时间单位我现在已经更正，但是问题仍然存在，请问可以再运行一次我上面提交的示例代码吗？（Sorry, yes, I made a mistake. I have corrected the time unit, but the problem still exists. Can I run the sample code I submitted above again?）

**Comment by 3792274** [comment]
@mrniko   > You defined lease time = 60*1000L seconds, please be attentive.

> You defined lease time = 60*1000L seconds, please be attentive.
>对不起，是的，我犯了个错，时间单位我现在已经更正，但是问题仍然存在，请问可以再运行一次我上面提交的示例代码吗？（Sorry, yes, I made a mistake. I have corrected the time unit, but the problem still exists. Can I run the sample code I submitted above again?）

**Comment by 3792274** [comment]
[https://github.com/redisson/redisson/issues/2477#issuecomment-567023018](url)
@mrniko 
> You defined lease time = 60*1000L seconds, please be attentive.



对不起，是的，我犯了个错，时间单位我现在已经更正，但是问题仍然存在，请问可以再运行一次我上面提交的示例代码吗？（Sorry, yes, I made a mistake. I have corrected the time unit, but the problem still exists. Can I run the sample code I submitted above again?）

**Comment by orjuly** [comment]
我也遇到一模一样的问题？ 楼主是否解决了？

**Comment by orjuly** [comment]
> You defined lease time = 60*1000L seconds, please be attentive.

问题依旧，这个问题怎么进行解决？
