### ISSUE TITLE
Redisson数据加载问题

### ISSUE THREAD

**Issue by Alex-Amo** [redisson/redisson#2482]
Redisson每次getList("anyList")的时候, 都是把redis中这个List里面所有的数据都拉取到本地的吗?
队列也是这样的吗?
为什么不能只加载我指定的数据呢? 如果我List或者队里里面数据很多,那岂不是很不合适的吗?

**Comment by mrniko** [comment]
Redisson objects are fully stateless. Object state stored in Redis
