### ISSUE TITLE
RedissonPriorityQueue throws NPE when add() method is called

### ISSUE THREAD

**Issue by zsokolowski** [redisson/redisson#2484]
**Expected behavior**

**Actual behavior**

I'm getting NPE at line 180

         if (res.getIndex() < 0) {

**Steps to reproduce or test case**

I think it is possible looking BinarySearchCode inside the class

please take a  look at the code:

  V res = getValue(index);
            if (res == null) {
                return new BinarySearchResult<V>();
            }

**Redis version**

AMAZON EC

**Redisson version**
3.11.6

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed. Thanks for report
