### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.data.redis.connection.RedisStreamCommands 

### ISSUE THREAD

**Issue by LayJustDoIt** [redisson/redisson#2488]
Hello 
         I just submitted two questions that didn't work. The reason is that I pressed the wrong key(ctrl + enter on windows). I'm sorry to be embarrassed. My problem is that I use springboot version 2.1.11.RELEASE and the redisson-spring-boot-starter version is 3.11.  .6, the error is the same as the title. I checked issue 2478 and suggested that he downgrade to redisson-spring-data-21. If it is redisson-spring-boot-starter, what version should he downgrade to?

**Comment by mrniko** [comment]
You need to downgrade to redisson-spring-data-21 only

**Comment by LayJustDoIt** [comment]
> You need to downgrade to redisson-spring-data-21 only

Yes, I tried to downgrade to this version and the program runs normally, thank you for your suggestions
