### ISSUE TITLE
RedissonBuckets.get(String... keys)   bug

### ISSUE THREAD

**Issue by xinxin188** [redisson/redisson#2492]
redisson 3.11.4 版本 RedissonBuckets类 第86行，mget获取的返回值不应该用ConcurrentHashMap接收，会报空指针异常，希望LZ能改成HashMap

**Comment by xinxin188** [comment]
可以通过反射自己封装一个方法：
 RRateLimiter limiter = client.getRateLimiter("myLimiter");
        Field commandExecutorField = limiter.getClass().getSuperclass().getDeclaredField("commandExecutor");
        commandExecutorField.setAccessible(true);
        Field codecField = limiter.getClass().getSuperclass().getDeclaredField("codec");
        codecField.setAccessible(true);
        CommandAsyncExecutor commandExecutor = (CommandAsyncExecutor) commandExecutorField.get(limiter);
        Codec codec = (Codec)codecField.get(limiter);
        Codec commandCodec = new CompositeCodec(StringCodec.INSTANCE, codec, codec);
        RedisCommand<Map<Object, Object>> command = new RedisCommand<Map<Object, Object>>("MGET", new MapGetAllDecoder(Arrays.<Object>asList(keys), 0));
        Map<String, String> results1 = commandExecutor.get(commandExecutor.readBatchedAsync(commandCodec, command, new SlotCallback<Map<Object, Object>, Map<String, String>>() {
            Map<String, String> results = new HashMap<>();
            @Override
            public void onSlotResult(Map<Object, Object> result) {
                results.putAll((Map<String, String>) (Object) result);
            }
            @Override
            public Map<String, String> onFinish() {
                return results;
            }

            @Override
            public RedisCommand<Map<Object, Object>> createCommand(Object param) {
                return new RedisCommand<Map<Object, Object>>("MGET", new BucketsDecoder(param.toString()));
            }
        }, keys));

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/pull/2461

**Comment by xinxin188** [comment]
其实不是想让你过滤掉null的值，而是想让查询的key对的null的值也存入map，保持redis mget的原生态

**Comment by xinxin188** [comment]
还是希望LZ能改成HashMap 况且只是读取的返回值也不涉及线程安全问题 问什么要用 ConcurrentHashMap呢，还要做判断过滤
