### ISSUE TITLE
为什么RedissonMapCache  清理缓存的定时任务，采用这种策略？

### ISSUE THREAD

**Issue by KinaZhen** [redisson/redisson#2495]
最近使用RedissonSpringCacheManager，缓存清理延迟，看wiki有了说明，但是不明白为什么一次最多清理100条，而且时间有递增，这是出于什么考虑呢？望解惑！

**Comment by mrniko** [comment]
You can control delay between cleanup with `minCleanUpDelay` and `maxCleanUpDelay` settings

**Comment by KinaZhen** [comment]
> You can control delay between cleanup actions with `minCleanUpDelay` and `maxCleanUpDelay` settings

我是想问为什么这么设计呢，是出于性能考虑呢，还是为减少redis请求？

**Comment by mrniko** [comment]
These settings are common. They need to be tuned depending on use case.
