### ISSUE TITLE
takeLastAndOfferFirstTo() does not block until an element is available

### ISSUE THREAD

**Issue by LBoraz** [redisson/redisson#2497]
**Expected behavior**

Calling RBlockingQueue.takeLastAndOfferFirstTo(otherQueue)  should block until an element is available.

**Actual behavior**

When the queue is empty RBlockingQueue.takeLastAndOfferFirstTo(otherQueue) returns null immediately.

**Steps to reproduce or test case**

// running from a Runnable submitted to redisson.getExecutorService()

RBlockingQueue<Object> q = redisson.getBlockingQueue("qName");
Object item = q.takeLastAndOffsetFirstTo("otherQueue");
assert item == null;

**Redis version**

5.0.3

**Redisson version**

3.11.6

**Redisson configuration**

single server configuration - all defaults

**Comment by mrniko** [comment]
Unable to reproduce it. Below is my code:

```java
    public static class Task implements Runnable, Serializable {

        @RInject
        private RedissonClient redisson;

        @Override
        public void run() {
            final RBlockingQueue<Integer> queue1 = redisson.getBlockingQueue("{queue}1");
            final RBlockingQueue<Integer> queue2 = redisson.getBlockingQueue("{queue}2");
            try {
                Integer s = queue1.takeLastAndOfferFirstTo(queue2.getName());
                System.out.println("s " + s);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    @Test
    public void testTakeLastAndOfferFirstToEmpty() throws InterruptedException {
        RScheduledExecutorService e = redisson.getExecutorService("test");
        e.registerWorkers(WorkerOptions.defaults());

        e.execute(new Task());

        Thread.sleep(60000);
    }
