### ISSUE TITLE
RedissonReactiveClient,  should aways invoke next method.

### ISSUE THREAD

**Issue by pengliaoye** [redisson/redisson#2500]
CommandReactiveService.java

always return value, so i can check is exists

**Expected behavior**
                future.onComplete((v, e) -> {
                    if (e != null) {
                        emitter.error(e);
                        return;
                    }

                    emitter.next(v);
                    emitter.complete();
                });
**Actual behavior**
                future.onComplete((v, e) -> {
                    if (e != null) {
                        emitter.error(e);
                        return;
                    }

                    if (v != null) {
                        emitter.next(v);
                    }
                    emitter.complete();
                });
**Steps to reproduce or test case**

**Redis version**

**Redisson version**

**Redisson configuration**

**Comment by mrniko** [comment]
Accroding to Reactive specification null value can't be returned
