### ISSUE TITLE
Tomcat session expires causing session information in redis to be deleted

### ISSUE THREAD

**Issue by 201528013329027** [redisson/redisson#2502]
Background: The use Redis do session sharing. Session is currently shared by three projects
Problem: After logining in to a service, the service does not operate for a long time. When the timeout time set by the service tomcat is reached, even if other services are still in operation, there will be a forced exit. However, as long as one service is still in use, we do not want it to exit because one of the services has reached the timeout period.

Is there a good solution?
Thanks

**Comment by mrniko** [comment]
Please provide redisson logs with logging level set to `TRACE` for `org.redisson` package. Also make sure that other services work with the same session.

**Comment by 201528013329027** [comment]
version: tomcat 7    redisson-tomcat-7-3.11.6  redisson-all-3.11.6

Automatically clear expired session processes：

![image](https://user-images.githubusercontent.com/14332755/71438054-15265000-272f-11ea-9026-8901fa7e8e50.png)

![image](https://user-images.githubusercontent.com/14332755/71438064-2707f300-272f-11ea-9c29-027b9e025ddc.png)

![image](https://user-images.githubusercontent.com/14332755/71438075-371fd280-272f-11ea-9c5f-c6c84932bcb5.png)
![image](https://user-images.githubusercontent.com/14332755/71438088-430b9480-272f-11ea-9029-8c6a354a667a.png)


When the local session expires, the sessionid in redis will also be deleted


Our actual scenario is:
Projects A, B, and C use the first-level domain name for session sharing (using the same redis). If login is not performed for a long time after login on A, the tomcat session expiration policy is triggered, which will cause the data in redis to be synchronously destroyed, resulting in B And C go offline at the same time (B and C are in continuous operation at this time)

**Comment by mrniko** [comment]
> When the local session expires, the sessionid in redis will also be deleted

it's managed by Redis in `RedissonSession.expireSession()` method

**Comment by 201528013329027** [comment]
![image](https://user-images.githubusercontent.com/14332755/71443208-a8b64b80-2744-11ea-962f-2ec43ec2fbb8.png)

At present, even if the service B is operated, it will automatically log out during the operation. But this is not the effect we want. We want to achieve this effect: clear the session only after the user actively logs out or does not use the three services A, B, and C for a long time. Instead of logging out of one of the services for a long time.

Is there any better solution? Or is it caused by our misuse? 

Thank you.

**Comment by mrniko** [comment]
> does not use the three services A, B, and C for a long time

Did you try to extend session expiration timeout?

**Comment by 201528013329027** [comment]
Thank you very much, this is a solution. We haven't found a good solution yet, let's try it

**Comment by zhangxinxf** [comment]
Tomcat manages session sessions based on Java Map. Tomcat will start a thread to scan the session in the scan and will actively trigger the session.isValid () operation. When the local session expires, it will actively trigger the deletion of session information in Redis, which will cause other project sessions to fail.

Here is the tomcat 7.x  source code

ManagerBase.java

public abstract class ManagerBase extends LifecycleMBeanBase implements Manager {

@Override
    public void backgroundProcess() {
        count = (count + 1) % processExpiresFrequency;
        if (count == 0)
            processExpires();
    }

/**
     * Invalidate all sessions that have expired.
     */
    public void processExpires() {

        long timeNow = System.currentTimeMillis();
        Session sessions[] = findSessions();
        int expireHere = 0 ;
        
        if(log.isDebugEnabled())
            log.debug("Start expire sessions " + getName() + " at " + timeNow + " sessioncount " + sessions.length);
        for (int i = 0; i < sessions.length; i++) {
            if (sessions[i]!=null && !sessions[i].isValid()) {
                expireHere++;
            }
        }
        long timeEnd = System.currentTimeMillis();
        if(log.isDebugEnabled())
             log.debug("End expire sessions " + getName() + " processingTime " + (timeEnd - timeNow) + " expired sessions: " + expireHere);
        processingTime += ( timeEnd - timeNow );

    }


StandardSession.java

public class StandardSession implements HttpSession, Session, Serializable {

 /**
     * Return the <code>isValid</code> flag for this session.
     */
    @Override
    public boolean isValid() {

        if (!this.isValid) {
            return false;
        }

        if (this.expiring) {
            return true;
        }

        if (ACTIVITY_CHECK && accessCount.get() > 0) {
            return true;
        }

        if (maxInactiveInterval > 0) {
            long timeNow = System.currentTimeMillis();
            int timeIdle;
            if (LAST_ACCESS_AT_START) {
                timeIdle = (int) ((timeNow - lastAccessedTime) / 1000L);
            } else {
                timeIdle = (int) ((timeNow - thisAccessedTime) / 1000L);
            }
            if (timeIdle >= maxInactiveInterval) {
                expire(true);
            }
        }

        return this.isValid;
    }


public void expire(boolean notify) {

        // Check to see if session has already been invalidated.
        // Do not check expiring at this point as expire should not return until
        // isValid is false
        if (!isValid)
            return;

        synchronized (this) {
            // Check again, now we are inside the sync so this code only runs once
            // Double check locking - isValid needs to be volatile
            // The check of expiring is to ensure that an infinite loop is not
            // entered as per bug 56339
            if (expiring || !isValid)
                return;

            if (manager == null)
                return;

            // Mark this session as "being expired"
            expiring = true;

            // Notify interested application event listeners
            // FIXME - Assumes we call listeners in reverse order
            Context context = (Context) manager.getContainer();

            // The call to expire() may not have been triggered by the webapp.
            // Make sure the webapp's class loader is set when calling the
            // listeners
            ClassLoader oldTccl = null;
            if (context.getLoader() != null &&
                    context.getLoader().getClassLoader() != null) {
                oldTccl = Thread.currentThread().getContextClassLoader();
                if (Globals.IS_SECURITY_ENABLED) {
                    PrivilegedAction<Void> pa = new PrivilegedSetTccl(
                            context.getLoader().getClassLoader());
                    AccessController.doPrivileged(pa);
                } else {
                    Thread.currentThread().setContextClassLoader(
                            context.getLoader().getClassLoader());
                }
            }
            try {
                Object listeners[] = context.getApplicationLifecycleListeners();
                if (notify && (listeners != null)) {
                    HttpSessionEvent event =
                        new HttpSessionEvent(getSession());
                    for (int i = 0; i < listeners.length; i++) {
                        int j = (listeners.length - 1) - i;
                        if (!(listeners[j] instanceof HttpSessionListener))
                            continue;
                        HttpSessionListener listener =
                            (HttpSessionListener) listeners[j];
                        try {
                            context.fireContainerEvent("beforeSessionDestroyed",
                                    listener);
                            listener.sessionDestroyed(event);
                            context.fireContainerEvent("afterSessionDestroyed",
                                    listener);
                        } catch (Throwable t) {
                            ExceptionUtils.handleThrowable(t);
                            try {
                                context.fireContainerEvent(
                                        "afterSessionDestroyed", listener);
                            } catch (Exception e) {
                                // Ignore
                            }
                            manager.getContainer().getLogger().error
                                (sm.getString("standardSession.sessionEvent"), t);
                        }
                    }
                }
            } finally {
                if (oldTccl != null) {
                    if (Globals.IS_SECURITY_ENABLED) {
                        PrivilegedAction<Void> pa =
                            new PrivilegedSetTccl(oldTccl);
                        AccessController.doPrivileged(pa);
                    } else {
                        Thread.currentThread().setContextClassLoader(oldTccl);
                    }
                }
            }

            if (ACTIVITY_CHECK) {
                accessCount.set(0);
            }

            // Remove this session from our manager's active sessions
            manager.remove(this, true);

            // Notify interested session event listeners
            if (notify) {
                fireSessionEvent(Session.SESSION_DESTROYED_EVENT, null);
            }

            // Call the logout method
            if (principal instanceof GenericPrincipal) {
                GenericPrincipal gp = (GenericPrincipal) principal;
                try {
                    gp.logout();
                } catch (Exception e) {
                    manager.getContainer().getLogger().error(
                            sm.getString("standardSession.logoutfail"),
                            e);
                }
            }

            // We have completed expire of this session
            setValid(false);
            expiring = false;

            // Unbind any objects associated with this session
            String keys[] = keys();
            if (oldTccl != null) {
                if (Globals.IS_SECURITY_ENABLED) {
                    PrivilegedAction<Void> pa = new PrivilegedSetTccl(
                            context.getLoader().getClassLoader());
                    AccessController.doPrivileged(pa);
                } else {
                    Thread.currentThread().setContextClassLoader(
                            context.getLoader().getClassLoader());
                }
            }
            try {
                for (int i = 0; i < keys.length; i++) {
                    removeAttributeInternal(keys[i], notify);
                }
            } finally {
                if (oldTccl != null) {
                    if (Globals.IS_SECURITY_ENABLED) {
                        PrivilegedAction<Void> pa =
                            new PrivilegedSetTccl(oldTccl);
                        AccessController.doPrivileged(pa);
                    } else {
                        Thread.currentThread().setContextClassLoader(oldTccl);
                    }
                }
            }
        }
    }

RedissonSessionManager.java
public class RedissonSessionManager extends ManagerBase {

    @Override
    public void remove(Session session, boolean update) {
        super.remove(session, update);
        if (session.getIdInternal() != null) {
            ((RedissonSession)session).delete();
        }
    }

**Comment by zhangxinxf** [comment]
@mrniko

**Comment by mrniko** [comment]
> When the local session expires, it will actively trigger the deletion of session information in Redis, which will cause other project sessions to fail.

This is an expected behaviour, since session is shared

**Comment by mrniko** [comment]
`processExpires` just count expired sessions
