### ISSUE TITLE
Provide classloader incase of FST so that it doesnt get the class loader from current thread

### ISSUE THREAD

**Issue by ALSowjanya** [redisson/redisson#2503]
Do we have a way to provide class loader when using FST codec. we are facing classNotfound exceptions as the FSTConfiguration is picking up the current thread class loader which is used by RedisExecutor as shown in the below stack trace.

> 195, FstCodec (org.redisson.codec)
> <init>:190, FstCodec (org.redisson.codec)
> newInstance0:-1, NativeConstructorAccessorImpl (sun.reflect)
> newInstance:62, NativeConstructorAccessorImpl (sun.reflect)
> newInstance:45, DelegatingConstructorAccessorImpl (sun.reflect)
> newInstance:423, Constructor (java.lang.reflect)
> getCodec:705, RedisExecutor (org.redisson.command)
> execute:132, RedisExecutor (org.redisson.command)
> run:357, RedisExecutor$3 (org.redisson.command)
> expire:663, HashedWheelTimer$HashedWheelTimeout (io.netty.util)
> expireTimeouts:738, HashedWheelTimer$HashedWheelBucket (io.netty.util)
> run:466, HashedWheelTimer$Worker (io.netty.util)
> run:748, Thread (java.lang)__

Our proprietary classes are loaded from our class loader. So wanted to understand if we can set the classloader which is used by FSTCodec.

**Comment by ALSowjanya** [comment]
By debugging further I see that thread name is "pool-19-thread-1". I could not understand from where these items are queued and who is managing the thread pool. Can you please help in understanding the issue here

**Comment by walkersing** [comment]
不要重复new FstCodec ，会内存溢出的。client 和 codec 都只初始化一次就没事

**Comment by ALSowjanya** [comment]
> 不要重复new FstCodec ，会内存溢出的。client 和 codec 都只初始化一次就没事

We are not doing new FstCodec, it is all handled by Redisson itself. Looks like redisson is using a thread pool, where we can see this is causing.

**Comment by mrniko** [comment]
> Do we have a way to provide class loader when using FST codec. we are facing classNotfound exceptions as the FSTConfiguration is picking up the current thread class loader which is used by RedisExecutor as shown in the below stack trace.

Yes, you can just pass classloader into FSTCodec constructor.

**Comment by ALSowjanya** [comment]
@mrniko this is not being created by us. So we dont have an handle to send the codec to constructor. 
This is a bug from Redisson.

**Comment by mrniko** [comment]
> this is not being created by us.

You need to create it with required classloader and pass to Redisson configuration. This is the only way to resolve the issue.

**Comment by ALSowjanya** [comment]
But then Redisson is overriding it again. And more importantly, I am unsure from where this "pool-19-thread-1" thread with above mentioned stacktrace is being created and used. Can you help us understand this.

**Comment by mrniko** [comment]
@jchobantonov

Seems this change causes this issue:

https://github.com/redisson/redisson/blob/f7b3fbc64a422e625f974b23f1d5dfc73542ad1e/redisson/src/main/java/org/redisson/command/RedisExecutor.java#L681

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by ALSowjanya** [comment]
Issue reported has not been fixed, I have tested it with 3.12.1 redisson. I couldnt see a way to reopen this Issue. 
What is the significance of the below code, this was added as a fix to this issue. 

> if (codec.getClassLoader() != codec.getClass().getClassLoader()) {
            return codec;
        }

**What is the issue ?** 
We are observing classNotfound exception due to wrong classloader being considered by the codec.

**What are different classloader coming into picture ?**
PRAppClassLoader(custom classloader) and ParallelWebAppClassLoader(tomcat loader). Classes should always be loaded with PRAppClassLoader.

**What are the sequence of event causing this issue ?**
1. Start the server using tomcat.
2. In the initialization state, we connect to redis. Codec is created and PRAppClassLoader is specified as the classLoader.
3. Some operation is performed on RMap, like get.
4. Now, RedisExecutor is coming into the picture. 
          - It goes to RedisExecutor, check the codec.getclassLoader - PRAppclassLoader is returned
          - It checks for codec.getClass().getClassLoader() - PRAppClassLoader is returned
          - It gets the thread class loader - ParallelWebAppClassLoader( since the thread is created by tomcat for intializing server)
          - It checks for cached codecs, it returns null
          - Now creates the codec with ParallelWebAppClassLoader. Because of which when class.forName() is performed, ClassNotfoundExeception is thrown.

@mrniko , I wanted to understand why the thread class loader is consider when classloader is specified in the codec explicitly. I assume classloader when specified in the codec, should be used irrespective of the thread class loader.

**Comment by jchobantonov** [comment]
@ALSowjanya The thread class loader is considered because of the case where the RedisClient is been bound into Tomcat JNDI tree to be used by multiple web applications. In this case the provided class loader during the creation of the RedisClient is the tomcat system classloader which do not have the web app classes used during serialization. That's why the thread class loader has been considered here.

@mrniko probably it should detect if the RedisClient comes from JNDI only then to apply the thread class loader, or to add some property that says that the provided classloader should be the one to be uses instead of the thread class loader in this case

**Comment by mrniko** [comment]
@jchobantonov 

Thanks for response! I think a new setting like `useThreadClassLoader` should be added.

**Comment by ALSowjanya** [comment]
> @ALSowjanya The thread class loader is considered because of the case where the RedisClient is been bound into Tomcat JNDI tree to be used by multiple web applications. In this case the provided class loader during the creation of the RedisClient is the tomcat system classloader which do not have the web app classes used during serialization. That's why the thread class loader has been considered here.

Thanks for the response @jchobantonov 
Will the code.getClass().getClassLoader() also not have the tomcat system classloader ?

**Comment by mrniko** [comment]
@ALSowjanya 

> Will the code.getClass().getClassLoader() also not have the tomcat system classloader ?

It depends which classloader was used during codec class loading.

**Comment by mrniko** [comment]
Config.useThreadClassLoader setting added

**Comment by ALSowjanya** [comment]
@mrniko do we have a tentative date for 3.12.4 milestone.

**Comment by ALSowjanya** [comment]
> Config.useThreadClassLoader setting added

Can we set this config via yaml file ?

**Comment by mrniko** [comment]
Yes

**Comment by ALSowjanya** [comment]
> Yes

Do we have a tentative dare for 3.12.4 milestone

**Comment by mrniko** [comment]
It's already has been released
