### ISSUE TITLE
Is there a guide for porting from Jedis?

### ISSUE THREAD

**Issue by AdityaAnand1** [redisson/redisson#2506]
After running into some threading/scalability issues I'm moving over redission. Would be great if there was a guide for porting from Jedis.

For example, what is the closest resembling API to the `jedis.get()` and `jedis.set()` methods?

**Comment by mrniko** [comment]
Here is you can find Redis command mapping - https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping
