### ISSUE TITLE
RedissonConnectionFactory does not shutdown RedissonClient on Spring destroy() call

### ISSUE THREAD

**Issue by rlubbat** [redisson/redisson#2509]
Using Redisson PRO 3.11.6.

The destroy() method on RedissonConnectionFactory is empty. When the RedissonConnectionFactory creates its own RedissonClient using the default constructor or the constructor that takes a Config as an argument, it should be responsible for calling shutdown() on the created RedissonClient. The RedissonClient is internal to the class and cannot be shutdown otherwise.

To safely manage resources, we must use the constructor that takes a RedissonClient argument so that the client has an external reference that we can shutdown.

**Comment by mrniko** [comment]
Since Redis connections are handled inside Redisson it's required to shutdown Redisson instance instead.

**Comment by rlubbat** [comment]
I understand that but if I call new RedissonConnectionFactory() or new RedissonConnectionFactory(config) then how can I possibly shutdown the Redisson instance? It is created inside the RedissonConnectionFactory class and is a private member. That is why I am proposing that the destroy() method on RedissonConnectionFactory shutdown the private member in these two usages of the class.

**Comment by mrniko** [comment]
Thanks for clarifying. Will fix that.

**Comment by mrniko** [comment]
Fixed. Thanks for report
