### ISSUE TITLE
No result for read command on redis cluster(version 5.* ) with password 

### ISSUE THREAD

**Issue by cyq89051127** [redisson/redisson#2511]
**Expected behavior**
    
    read from redis cluster  properly

**Actual behavior**
    
    read nothing from redis clsuter

**Steps to reproduce or test case**

    1. redis cluster(5.*) with password 
    2 run the following code. When we use the following code to set an value(CC) for key(cc),when these codes runs on redis version of 4.*,  CC will be printed, But when it runs on redis cluster of version 5.*, null will be printed. But when we use command (get cc) in redis-cli console, we could get the value 'CC' of key 'cc' 

        RBucket rBucket = redisson.getBucket("cc");

        rBucket.set("CC");

        String v = ( String) rBucket.get();

        System.out.println(v);

**Redis version**

    I test on redis 5.0.7 and redis4.0.11

**Redisson version**

     3.12.0

**Redisson configuration**

    no special configuration.

**Comment by mrniko** [comment]
Could you set logging level to `TRACE` for `org.redisson` package and share output?
