### ISSUE TITLE
重复setCode 会撑爆内存

### ISSUE THREAD

**Issue by walkersing** [redisson/redisson#2512]
**Expected behavior**
 public static RedissonClient getRedis() {
        RedissonClient rediss = ApplicationContextKeeper.getAppCtx().getBean(RedissonClient.class);
        rediss.getConfig().setCodec(new FstCodec()); // 会一直撑爆内存
        return rediss;
    }
**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
4.0.1
**Redisson version**
3.11.4
**Redisson configuration**

**Comment by mrniko** [comment]
RedissonClient config settings aren't applied once client instance was created.
