### ISSUE TITLE
并发使用lock.lock出错

### ISSUE THREAD

**Issue by wudongqiang** [redisson/redisson#2513]
org.redisson.client.RedisException,ERR Error running script (call to f_762bfafa6be221431a0b668685dd15c926483619): @user_script:1: user_script:1: attempt to compare nil with number . channel: [id: 0xc180c731, L:/172.31.0.110:52122 - R:xx-api.tflohd.0001.cnn1.cache.amazonaws.com.cn/172.31.25.58:6379] command: (EVAL), params: [while true do local firstThreadId2 = redis.call('lindex', KEYS[2], 0);if firstThreadId2 == false the..., 3, lock:charge:pre:5de9b5bd1b92990740f5114d, redisson_lock_queue:{lock:charge:pre:5de9b5bd1b92990740f5114d}, redisson_lock_timeout:{lock:charge:pre:5de9b5bd1b92990740f5114d}, 500, 371bc7b9-7504-4614-a4e5-747c37fb9580:14401, 5000, 1578030638778]

**Comment by mrniko** [comment]
check that you don't share same name across different objects.

**Comment by wudongqiang** [comment]
一开始没有什么问题,  并发运行一段时间后,才出现的这个错

**Comment by xiaxingit** [comment]
@wudongqiang 请问解决了吗？目前我遇到同样的问题
