### ISSUE TITLE
With spring boot application redisson by default connect to local host even after providing configuration

### ISSUE THREAD

**Issue by manojbsw** [redisson/redisson#2516]
I am creating tiny redis cache library for all running java based microservices using redisson. This library will be used by all spring boot and and non spring boot microservices.
 
I am using below maven dependency for redission:
   ```
<dependency>
		   <groupId>org.redisson</groupId>
		   <artifactId>redisson</artifactId>
		   <version>3.12.0</version>
	</dependency>
```
   

And using below implementation for redisson bean creation

```
@Configuration
public class RedissionClient {

	@Bean
	public RedissonClient init(@Value("${redishostname}") String host, @Value("${redisport}") String port) {
		Config config = new Config();
		String url = "redis://"+ host + ":" + port;
        config.useSingleServer().setAddress(url);
        return Redisson.create(config);
	}
}
```

 Above configuration works well when I use this library with non spring boot based application. 
 
But it fails with spring boot based application. I saw that redissonClient try to connect to local redis instance instead of configuration provided by me in application.properties.
 It works when I used below configration in application.properties
	_spring.redis.host=${redis_host:172.28.221.76}
	spring.redis.port=${redis_port:6379}_
	
But being a common library I can not use above configuration for non spring boot based application.

 Is there a way where I can force redissonClient to be created with custom configuration instead of default configuration ?

**Comment by mrniko** [comment]
Did you try to define `spring.redis.redisson.config` setting instead? Path to config.yaml file

**Comment by manojbsw** [comment]
I tried but no success. Being a common library I don't want to use spring boot specific properties here.  All the required configuration of redis instance will be available as env. variable. So I am expecting redissonClient should be created as below. 

```
@Bean
	public RedissonClient init(@Value("${redishostname}") String host, @Value("${redisport}") String port) {
		Config config = new Config();
		String url = "redis://"+ host + ":" + port;
        config.useSingleServer().setAddress(url);
        return Redisson.create(config);
	}
```

**Comment by mrniko** [comment]
add `@AutoConfigureBefore(RedissonAutoConfiguration.class) ` annotation to your configuration
