### ISSUE TITLE
How to dynamically fetch node addresses from AWS Elasticache?

### ISSUE THREAD

**Issue by AdityaAnand1** [redisson/redisson#2521]
How is redisson meant to be used with AWS Elasticache? Would love to see a full example with multiple shards, dynamically fetching node addresses, failover handling, node health monitoring etc.

[This](https://redisson.org/redis-java-client-for-aws-elasticache.html) link gives a very minimal example, I think a production ready example would be super helpful to anyone using redisson with AWS elasticache.

**Comment by mrniko** [comment]
> Would love to see a full example with multiple shards, dynamically fetching node addresses, failover handling, node health monitoring etc

This all fully managed by Redisson and not by developer.

**Comment by AdityaAnand1** [comment]
Can you please point to a relevant example or tutorial to setup redisson with elasticache?

**Comment by mrniko** [comment]
There are two modes supported by Redisson:

https://github.com/redisson/redisson/wiki/2.-Configuration#25-replicated-mode
https://github.com/redisson/redisson/wiki/2.-Configuration#24-cluster-mode

Basically all you need is just do define Redis endpoint in nodeAddresses setting
