### ISSUE TITLE
Subscriptions become zombies when network lost

### ISSUE THREAD

**Issue by japgolly** [redisson/redisson#2522]
**Steps to reproduce or test case**
1. Establish a connection to a single-server Redis
2. Subscribe to a topic using Redisson
3. Kill the network or restart Redis

**Expected behavior**
1. Existing subscriptions should be closed when connection to Redis is lost
2. (and/or) subscriptions should re-subscribe when connection becomes possible again

**Actual behavior**
The subscriptions are left in a zombie state where they're not connected and will never receive any data. Even if a new connection from the same JVM is established to Redis once it's available again, and it publishes data on the topic, the zombie subscription never receives it.

**Redis version**
5.0.5

**Redisson version**
3.11.6

**Redisson configuration**
`new Config().useSingleServer().setAddress(url)`

**Notes**
It's ok that Redisson doesn't resubscribe when connection becomes available, but at the bare minimum it'd be super helpful if it closes the subscription or gave me an event to listen to or something so that I could handle it myself. I've tried all the options like keep-alive etc and there doesn't seem to be any workaround.

**Comment by mrniko** [comment]
Unable to reproduce it using this test:

https://github.com/redisson/redisson/blob/12e81de984698d06b3dbc236bac00479ec7e3d61/redisson/src/test/java/org/redisson/RedissonTopicTest.java#L629

**Comment by mrniko** [comment]
Is there anything I should improve in test above to reproduce your case?

**Comment by japgolly** [comment]
I've spent the morning trying to provide a reproduction and in doing so, I've discovered that I've made a mistake. My application wasn't doing as I expected because I made a misunderstanding about how Redisson handles this case. Redisson is working perfectly. Thanks and btw, those tests you've got are awesome. :+1:
