### ISSUE TITLE
How to build from source and package as single jar without all optional dependency?

### ISSUE THREAD

**Issue by kitepad** [redisson/redisson#2527]
**Is your feature request related to a problem? Please describe.**
Redission collection is used in my application (single jar) and want to package needed classes without all optional dependencies to reduce app size.

**Describe the solution you'd like**
Split feature (optional dependencies are used) as sub module.
**Describe alternatives you've considered**
Remove all optional dependencies java classes from my jar (Follow dependency document in wiki). But I don't think it is right approach and whether have potential problems.

**Comment by mrniko** [comment]
there is redisson.jar already built from sources. Why can't you use it?

**Comment by kitepad** [comment]
Do you mean redission-all.jar?  
I don't use spring, hibernate and other additional features. And I want to package redission classes with all must have dependencies into single jar. When I trying build redission by maven shade plugin, I got a single jar file which includes all optional dependencies, for example javax.cache.*, org.jodd, net.bytebuddy, io.projectreactor,io.reactivex.rxjava2. I want to remove them to reduce file size. But I cann't do this through maven build.

**Comment by kitepad** [comment]
If I don't use liveobject service, how to remove them? I tried to remove theme from src tree, but I get compile error, some classes are used by others, such as RedissonObjectBuilder. Even I keep them, if we don't include org.jodd/net.bytebuddy, I cann't build successfully. Can I remove these dependencies without errors?

**Comment by kitepad** [comment]
Finally, I want to to use redission distributed collections by sync way/async way. Reactive way/ Rx way will be removed and two ways dependencies will removed at same time.

**Comment by mrniko** [comment]
> Can I remove these dependencies without errors?

No.
