### ISSUE TITLE
redisson-spring-boot-starter RedissonAutoConfiguration customizer

### ISSUE THREAD

**Issue by nikakis** [redisson/redisson#2529]
In Spring Boot RedissonAutoConfiguration there is the need for post customizing the autoconfigured RedissonClient.

Would you consider a pull request with this functionality?

**Comment by mrniko** [comment]
Yes I would consider it. What is the motivation for this?

**Comment by nikakis** [comment]
We would like to keep the RedissonClient autoconfigurated and just override some of the default Config attributes (e.g. the Codec from Fst to Jackson)

**Comment by mrniko** [comment]
You can use `spring.redis.redisson.config` spring setting to define path to redisson yaml config.

**Comment by nikakis** [comment]
Actually we don't want to configure the `RedissonClient` from scratch, we want to keep the default autoconfiguration and implement a customizer interface which will customize some of the default `Config` attributes before the `Redisson.create(config)` invoked.

Maybe i can open a PR to show you what we have in mind ?

**Comment by mrniko** [comment]
Yes, that would be better.

**Comment by nikakis** [comment]
Thanks for you immediate response!!! I will open it asap.

**Comment by nikakis** [comment]
@mrniko 
I opened a pull request, with the enchancements i am proposing.
Thanks !!!

**Comment by nikakis** [comment]
@mrniko Can you take a look at the PR, because i can't figure out what is wrong with the license header? Thanks !!
