### ISSUE TITLE
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float

### ISSUE THREAD

**Issue by rc452860** [redisson/redisson#2531]
**Expected behavior**
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float

**Actual behavior**
No exception is thrown

**Steps to reproduce or test case**

@Test
    public void testBucketFloat(){
        String key = dcsConfigProperties.getRedisPrefix() + ":test:" + "test-bucket-string";
        RBucket<Float> asset = redissonClient.getBucket(key);
        asset.set(42.00F);
        Float a = asset.get();
        Assert.assertEquals(42.00F,a,0.001);
    }
**Redis version**
3.2.11

**Redisson version**
3.11.6

**Redisson configuration**
codec: org.redisson.codec.TypedJsonJacksonCodec

**Comment by mrniko** [comment]
Jackson stores float types as Double. So you need to cast it to Double

**Comment by rc452860** [comment]
new TypedJsonJacksonCodec(Object.class)

**Comment by rc452860** [comment]
Isn't this strange? I setting bucket type is float and get result is double.

**Comment by mrniko** [comment]
Try FST or SerializationCodec codec instead.
