### ISSUE TITLE
关于redisson的watchdog重连机制

### ISSUE THREAD

**Issue by ShosinnFuYW** [redisson/redisson#2532]
最近将redisson版本升到了3.11.5，然后测试了一下redisson的重连机制，然后出现了一个奇怪的现象。在Linux上部署redis集群，然后在本地Windows上进行连接测试。如果使用在Linux上使用iptables切断连接，在连接恢复后不可用连接会重连；但如果在Windows上使用IP安全策略来切断连接，在连接恢复后，不可用连接没有重连。请问一下，这两种方式之间有什么不一样的地方吗？

**Comment by mrniko** [comment]
Did you try to set `setPingConnectionInterval` setting ?

**Comment by ShosinnFuYW** [comment]
> 
> 
> Did you try to set `setPingConnectionInterval` setting to handle such cases?
Thank you,it works fine!
