### ISSUE TITLE
Updating from 3.8.2 to 3.12.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [redisson/redisson#2536]
When I try to upgrade redisson from 3.8.2 to the version after 3.11.2. The following code breaks.
```
public class Demo {
	
	private SingleServerConfig singleServerConfig;
	
	public void test() throws URISyntaxException {
		
		singleServerConfig.setSslKeystore(new URI("test"));
		
	}
}
```

The code should pass, but it throws an error:
```
Demo.java:[15,51] incompatible types: java.net.URI cannot be converted to java.net.URL
```

**Comment by mrniko** [comment]
java.net.URI was changed to java.net.URL

**Comment by SElab2019** [comment]
> java.net.URI was changed to java.net.URL

Thanks for your helping. Would it be better to add a breaking announcement in the release note? Then all other developers who use redisson could know it.
