### ISSUE TITLE
数据类型问题

### ISSUE THREAD

**Issue by MarionSong** [redisson/redisson#2538]
我用spring中的@cacheable时，从数据库中取出来准备序列化存到redis中的数据是Byte类型，但是再从redis中查出来返回的却是Integer，这个是需要修改redisson的数据序列化方式吗？我试了一下包装类Short、Byte都会变成Integer，Character会变成String，Float会变成Double。

**Comment by mrniko** [comment]
Which codec do you use?

**Comment by MarionSong** [comment]
JsonJacksonCodec

**Comment by mrniko** [comment]
Switch to FST, KryoCodec or SerializationCodec

**Comment by MarionSong** [comment]
thank you ，I switch to SerializationCodec
