### ISSUE TITLE
运行时打印错误日志

### ISSUE THREAD

**Issue by laomolaomo** [redisson/redisson#2541]
服务在运行时,打印的错误日志,在工程中只用到了下面代码,但不确定是不是在执行下面的代码报出来的error日志
...
RLock rLock = redissonClient.getLock(LOCK);
...
rLock.tryLock(1, 3, TimeUnit.SECONDS);
...
rLock.unlock();

error日志如下:

[2020-01-09 10:39:45 ERROR] [nioEventLoopGroup-2-9] [CommandDecoder.java:316] - Error message from Redis: ERR handle request, command 'SUBSCRIBE' is not allowed channel: [id: 0x67a5ab14, L:/serverIp: serverPort - R:redis-serverIp/redis-serverIp:redis-serverPort]
[2020-01-09 10:39:46 ERROR] [nioEventLoopGroup-2-9] [CommandDecoder.java:316] - Error message from Redis: ERR handle request, command 'UNSUBSCRIBE' is not allowed channel: [id: 0x67a5ab14, L:/serverIp: serverPort - R:redis-serverIp/redis-serverIp:redis-serverPort]

**Redis version**
3.2.11
**Redisson version**
3.10.0
**Redisson configuration**
    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer().setAddress("redis://" + redis-serverIp + ":" + redis-serverPort);
        config.setEventLoopGroup(new NioEventLoopGroup());
        config.setCodec(JsonJacksonCodec.INSTANCE);
        return Redisson.create(config);
    }

**Comment by mrniko** [comment]
What Redis hosting do you use?

**Comment by laomolaomo** [comment]
for example
redis-serverIp    192.168.*
redis-serverPort  8700

**Comment by laomolaomo** [comment]
> What Redis hosting do you use?

use codis proxy address

**Comment by mrniko** [comment]
I'm afraid codis is not supported

**Comment by laomolaomo** [comment]
> I'm afraid codis is not supported

In what scenario will the error log be printed?
Will my code cause this error log?
SUBSCRIBE and UNSUBSCRIBE are used where locks are used?

**Comment by laomolaomo** [comment]
> I'm afraid codis is not supported

Print 'ERR handle request, command SUBSCRIBE is not allowed' when the SUBSCRIBE command is executed.

**Comment by laomolaomo** [comment]
> I'm afraid codis is not supported

Will it affect the use of locks?

**Comment by mrniko** [comment]
I never tested it with codis
