### ISSUE TITLE
RLock unlock always throw an exception what like 'not lock by current thread'

### ISSUE THREAD

**Issue by chentaoah** [redisson/redisson#2543]
**Expected behavior**
trylock and unlock success

**Actual behavior**
RLock unlock always throw an exception what like 'not lock by current thread'

**Steps to reproduce or test case**
According to the stack information, the underlying asynchronous unlocking may cause the unlocking to throw an exception.This phenomenon can be reproduced 100%.

**Redis version**
4.0.14

**Redisson version**
3.11.x-3.12.0

**Redisson configuration**
standalone mode

**Comment by mrniko** [comment]
By Java Lock specification it should be unlocked in the same thread it was locked before. You can overcome this limitation by using `unlockAsync(long threadId);` method or `RSemaphore` object.

**Comment by chentaoah** [comment]
> 根据Java Lock规范，应在之前锁定的同一线程中将其解锁。您可以通过使用`unlockAsync(long threadId);`方法或`RSemaphore`对象来克服此限制。

I've prepared a simple case. There is only one thread. After locking, unlock it immediately, but still report this error. The same code will not appear in 3.9.1-3.10.5, but in the higher version, it will appear 100%

**Comment by mrniko** [comment]
Could you share the sample?

**Comment by chentaoah** [comment]
> 您可以分享样本吗？

![image](https://user-images.githubusercontent.com/40727549/72500070-983e5000-386e-11ea-9650-f186428649a6.png)
This is my code, just trying to lock and unlock, I'm confused

**Comment by mrniko** [comment]
Here is my test it always passes:

```java
        Lock lock = redisson.getLock("lock1");
        if (lock.tryLock(30, TimeUnit.SECONDS)) {
            lock.unlock();
        }
```

**Comment by chentaoah** [comment]
> Here is my test it always passes:

![image](https://user-images.githubusercontent.com/40727549/72500980-ae4d1000-3870-11ea-9cac-35dee01cbfb7.png)
![image](https://user-images.githubusercontent.com/40727549/72500988-b442f100-3870-11ea-917d-8ca136d20355.png)
In fact, we have made a little encapsulation on the redisson. The API we call is as shown in the figure. What is the passed version?

**Comment by mrniko** [comment]
The latest one.

**Comment by chentaoah** [comment]
> The latest one.

Sorry, the reason is that in the previous version, our incoming expiration time is 0, but in the subsequent version, this exception will be reported. It should be caused by improper use of API
