### ISSUE TITLE
lock.isHeldByCurrentThread() verification  before unlocking Exception

### ISSUE THREAD

**Issue by hulvyou** [redisson/redisson#2544]
RLock 
lock.isHeldByCurrentThread() verification  before unlocking
but sometimes exception

org.redisson.client.RedisException: Unexpected exception while processing command
        at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:400)
        at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:204)
        at org.redisson.RedissonObject.get(RedissonObject.java:94)
        at org.redisson.RedissonLock.isHeldByThread(RedissonLock.java:521)
        at org.redisson.RedissonLock.isHeldByCurrentThread(RedissonLock.java:515)

**Comment by mrniko** [comment]
could you provide full stacktrace?

**Comment by hulvyou** [comment]
public <V> V get(RFuture<V> future) {
        if (!future.isDone()) {
            CountDownLatch l = new CountDownLatch(1);
            future.onComplete((res, e) -> {
                l.countDown();
            });

            boolean interrupted = false;
            while (!future.isDone()) {
                try {
                    l.await();
                } catch (InterruptedException e) {
                    interrupted = true;
                    break;
                }
            }

            if (interrupted) {
                Thread.currentThread().interrupt();
            }
        }

        // commented out due to blocking issues up to 200 ms per minute for each thread
        // future.awaitUninterruptibly();
        if (future.isSuccess()) {
            return future.getNow();
        }

        throw convertException(future);
    }
 No more stacktrace，May be the log level is high
 You can tell me under what circumstances throw convertException(future) ？

**Comment by mrniko** [comment]
> You can tell me under what circumstances throw convertException(future) ？

When `future.isSuccess()` returns false value.
