### ISSUE TITLE
there are dead locks in redis

### ISSUE THREAD

**Issue by hezhiqiang** [redisson/redisson#2547]
in my app, sometimes there are some dead locks in redis

**Comment by mrniko** [comment]
Could you provide stacktrace?

**Comment by hezhiqiang** [comment]
i found this may occur when i use two locks in a method like this:

        RLock readingRecordLock = redisson.getLock(String.format("lock:readingRecord:%d", userId));
        RLock lock = redisson.getLock(String.format("lock:myBook:%d", userId));

        try {
        	RedissonUtil.lock(readingRecordLock);
        	RedissonUtil.lock(lock);

            ...
        } catch (Exception ex) {
		    ...
        } finally {
        	RedissonUtil.unlock(lock);
        	RedissonUtil.unlock(readingRecordLock);
        }

**Comment by mrniko** [comment]
Unable to reproduce it using code below:

```java
        ExecutorService e = Executors.newFixedThreadPool(16);
        for (int i = 0; i < 100000; i++) {
            e.submit(new Runnable() {
                @Override
                public void run() {
                    Lock lock1 = redisson.getLock("lock1");
                    Lock lock2 = redisson.getLock("lock2");
                    lock1.lock();
                    lock2.lock();

                    lock2.unlock();
                    lock1.unlock();
                }
            });
        }

        e.shutdown();
        assertThat(e.awaitTermination(5, TimeUnit.MINUTES)).isTrue();
```

Could you make thread dump next time you encounter it?
