### ISSUE TITLE
Master/Slave mode with master only writer and slaves as reader

### ISSUE THREAD

**Issue by nitinparetha** [redisson/redisson#2552]
I tried Master Slave configuration for redission-mybatis. I want to set 'master' only for writer and 'slave' for read only. But when is set master slave configuration i can see master is also used for reading purpose. 

Can i set configuration in which 'master' work only as writer not reader?

**Comment by mrniko** [comment]
RMapCache.get method uses write operation executed on master node to update idleTime of read map entry.

**Comment by nitinparetha** [comment]
I checked redis commands using redis-cli. Master node is getting 'hget' command but i want only to use it as writer. So, I think master should not get 'hget', all 'hget' command should be executed on 'slave/reader' only. 

How can I configure Master/Slave configuration in which master work as writer (no 'hget' command on master) and Slave work as reader only (slave are set for read-only).

**Comment by mrniko** [comment]
did you set `readMode = SLAVE` in config?

**Comment by nitinparetha** [comment]
My configuration is as below:
masterSlaveServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  slaveAddresses:
  - "<SLAVE_ADDRESS>"
  masterAddress: "<MASTER_ADDRESS>"
  database: 0
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"
useScriptCache: false

**Comment by mrniko** [comment]
> Master node is getting 'hget' command but i want only to use it as writer. 

I think it was listed as part of lua-script which executed on master due to presence of write operation.
