### ISSUE TITLE
delay queue doesn't work after one of cluster node occur master slave switch

### ISSUE THREAD

**Issue by lijy83** [redisson/redisson#2553]
**Expected behavior**
delay queue still work

**Actual behavior**
delay queue doesn't work

**Steps to reproduce or test case**

**Redis version**
3.2.12

**Redisson version**
3.12.0

Configration:
  slaveConnectionMinimumIdleSize: 8
  slaveConnectionPoolSize: 50
  masterConnectionMinimumIdleSize: 8
  masterConnectionPoolSize: 50

throw follow exception continuous, but the the APP host acctualy has ony 7 connection
Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=11834, addr=redis://10.10.14.61:6382, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #exp..., 3, transfer_ttl_queue, redisson_delay_queue_timeout:{transfer_ttl_queue}, redisson_delay_queue:{transfer_ttl_queue}, 1579602478857, 100] after 0 retry attempts
org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=11834, addr=redis://10.10.14.61:6382, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #exp..., 3, transfer_ttl_queue, redisson_delay_queue_timeout:{transfer_ttl_queue}, redisson_delay_queue:{transfer_ttl_queue}, 1579602478857, 100] after 0 retry attempts

thanks.

**Comment by mrniko** [comment]
Please check connection to 10.10.14.61:6382

**Comment by lijy83** [comment]
Hi mrniko, thanks for you reply,
after the failover, the new master also cann't connect, below is log after the failover:
Can't connect to master: redis://10.10.14.61:6382 with slot ranges: [[10924-16383]]

**Comment by mrniko** [comment]
Check network

**Comment by lijy83** [comment]
Got only that one cann't connect error log, the network have no problem, but the redis server's CPU utilization is often above 90%， Therefore, the master and slave should be unavailable at the same time. Even after the failover, the new master is not available at the time. So it throws the following exception after failover:
Can't connect to master: redis://10.10.14.61:6382 with slot ranges: [[10924-16383]]

But, only one record log,
It seems from this exception, Redisson no longer tries to update the cluster information。So keep throwing the following exception

throw follow exception continuous, but the the APP host acctualy has ony 7 connection
Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=11834, addr=redis://10.10.14.61:6382, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #exp..., 3, transfer_ttl_queue, redisson_delay_queue_timeout:{transfer_ttl_queue}, redisson_delay_queue:{transfer_ttl_queue}, 1579602478857, 100] after 0 retry attempts
org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=11834, addr=redis://10.10.14.61:6382, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #exp..., 3, transfer_ttl_queue, redisson_delay_queue_timeout:{transfer_ttl_queue}, redisson_delay_queue:{transfer_ttl_queue}, 1579602478857, 100] after 0 retry attempts ...

**Comment by mrniko** [comment]
> Redisson no longer tries to update the cluster information

Set `DEBUG` logging level for `org.redisson` package to make sure that. Cluster topology will appear in logs
