### ISSUE TITLE
Improve Redisson Eviction Rate

### ISSUE THREAD

**Issue by jharnach** [redisson/redisson#2554]
Our application uses UUIDs for keys and stores them in a RMapCache<String, Boolean>. Clearing 3MB of expired keys currently takes about 10 minutes though even a trivial service load can generate 5-7MB/min. Is there a way to increase the frequency of the eviction task, or increase the batch size of objects that are expired ?

Currently using a default configuration, connecting to a 3-node Redis cluster in Sentinel mode.

Dependencies:
redisson:redisson-spring-boot-starter:3.11.1
org.springframework.boot:spring-boot-starter-parent:2.1.2.RELEASE

**Comment by mrniko** [comment]
reduce `minCleanUpDelay` setting.

**Comment by jharnach** [comment]
This still puts an upper limit on the volume of keys that can be expired in a given interval. Setting the min to 1 second causes us to purge 100 keys a second, which is better, but still not enough to keep up with load. It looks like that limit of 100 is hardcoded in `org.redisson.eviction.EvictionTask`. Are there any other options for improving the purge rate ?

**Comment by jharnach** [comment]
Or alternatively is there a better type to use over RMapCache for high-volume, short-lived keys ?

**Comment by mrniko** [comment]
I set keysLimit to 1000. Please try snapshot version below

[redisson-3.12.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4096311/redisson-3.12.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
`cleanUpKeysAmount` setting introduced https://github.com/redisson/redisson/wiki/2.-Configuration#cleanupkeysamount
