### ISSUE TITLE
Can you use a service to lock and unlock threads?

### ISSUE THREAD

**Issue by Neha287** [redisson/redisson#2557]
I have a redisson lock implementation in my code like:

Distributed lock implementation:

@Autowired
	public DistributedLockerImpl(RedissonClient redissonClient) {
		this.redissonClient = redissonClient;
	}

	@Override
	public RLock lock(String lockKey, long leaseTime) {
		RLock rlock = redissonClient.getFairLock(lockKey);
		rlock.lock(leaseTime, TimeUnit.SECONDS);
		return rlock;
		
	}

	@Override
	public void unlock(String lockKey) {
		RLock rlock = redissonClient.getFairLock(lockKey);
		rlock.unlock();
	}

	@Override
	public void unlock(RLock rlock) {
		rlock.unlock();
	}

And client code is:

RLock lock = distributedLocker.lock(lockKey, 10);
                 try{
                   //logic code
                }
                finally {
                    distributedLocker.unlock(lock);
                    logger.info("Removed lock for id {}", lockKey);
                }

SonarQube complains not having the lock unlocked in the same path as lock. Is there any solution for this? Or can we not have this implementation for redisson locks? It does always execute the unlock but relies on the client to do so.

**Comment by mrniko** [comment]
Did you consider to use RSemaphore object? It's not tied to thread.
