### ISSUE TITLE
zCount 0/-1 instead of -inf/+inf

### ISSUE THREAD

**Issue by OverDrone** [redisson/redisson#2561]
RedissonReactiveZSetCommands.zCount behaves incorrectly if one of range bounds is unbounded.

if lower bound is unbounded:
actual value: 0
expected value: -inf

if upper bound is unbounded:
actual value: -1
expected value: +inf

btw this is how RedissonReactiveZSetCommands.zRangeByScore implemented.

**Comment by OverDrone** [comment]
https://github.com/redisson/redisson/blob/b7fdb7cc7c5c06a71be21a398a3c3e64dc011c9e/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveZSetCommands.java#L352
https://github.com/redisson/redisson/blob/b7fdb7cc7c5c06a71be21a398a3c3e64dc011c9e/redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/RedissonReactiveZSetCommands.java#L353

**Comment by mrniko** [comment]
Fixed! Thanks for report
