### ISSUE TITLE
Dynamically setting TTL

### ISSUE THREAD

**Issue by rezagh** [redisson/redisson#2562]
we set TTL into CacheConfig when the cache is initially created. Is there a way to change that AFTER creation? 

we are caching an api endpoint and would like to return stale objects even after expiry. 
one way to achieve this is to check the downstream api and if not responding then extend ttl to use the existing stale object.

> @Bean("xxCacheManager")
>     CacheManager getCM(RedissonClient redissonClient) {
>         CacheConfig cacheConf = new CacheConfig();
>         cacheConf.setTTL(...);
>         Map<String, CacheConfig> configs = new HashMap<String, CacheConfig>() {{ put("xxCacheManager", cacheConf); }};
>         return new RedissonSpringCacheManager(redissonClient,configs);
>     }

**Comment by mrniko** [comment]
It's not possible at the moment.
