### ISSUE TITLE
Unable to initialize JCache using Redisson's config object

### ISSUE THREAD

**Issue by dimaneg** [redisson/redisson#2567]
**Expected behavior**
When using Redisson with JCache with custom Redisson config, this custom config should be taken into account

From documentation:
```
MutableConfiguration<String, String> jcacheConfig = new MutableConfiguration<>();

Config redissonCfg = ...
Configuration<String, String> config = RedissonConfiguration.fromConfig(redissonCfg, jcacheConfig);

CacheManager manager = Caching.getCachingProvider().getCacheManager();
Cache<String, String> cache = manager.createCache("namedCache", config);
```

**Actual behavior**
When executing Caching.getCachingProvider(), underneath config from default json config is used:

From JCachingProvider.java:
```
public CacheManager getCacheManager(URI uri, ClassLoader classLoader, Properties properties) {
		...
        Config config = this.loadConfig(uri);
        Redisson redisson = null;
        if (config != null) {
          redisson = (Redisson)Redisson.create(config);
		}
		...
```
  
**Steps to reproduce or test case**
Create a simple project with an empty redisson-jache.json(or without the file at all).
Create a cache as explained in the documentation: 14.4 JCache API (JSR-107) implementation -> 3. Using Redisson's config object:

**Redisson version**
3.11.2

**Comment by mrniko** [comment]
with default `redisson-jache.json` you can't use custom config. Delete this file and config object will be `null`.

**Comment by dimaneg** [comment]
Deleting the redisson-jache.json solved the problem. Thank you
