### ISSUE TITLE
Cache performance is less when compared to map.

### ISSUE THREAD

**Issue by Sai-Bhargavi** [redisson/redisson#2568]
We have performed an analysis on how map and cache performs with 50 KB and 1 MB data . As part of it, we observed map performs well compared to cache and also as data size increases the performance is degrading.

But [this ](https://redisson.pro/Redisson%20PRO%20benchmark%20whitepaper.pdf)states better performance with 6 bytes of data even though with open source redisson.

Are there any configuration parameters which will help us to get better performance? If any, please provide the details of those parameters.

Here are the benchmark performance numbers we got for 10000 entries :
**Time in milliseconds.
![image](https://user-images.githubusercontent.com/17794641/73867685-1dfd5c00-486d-11ea-9f33-6f5f615199ee.png)

The redis configuration file, redisson configuration file and the sample program with which the performance numbers are taken are attached below.

[redis_conf.txt](https://github.com/redisson/redisson/files/4161095/redis_conf.txt)
[clusterServersConfig.txt](https://github.com/redisson/redisson/files/4161097/clusterServersConfig.txt)
[TestBenchmarkPerf.txt](https://github.com/redisson/redisson/files/4161098/TestBenchmarkPerf.txt)

**Comment by mrniko** [comment]
Try to compress the data using LZ4Codec or SnappyCodec2. Also network and redis instance are subject for tuning.
