### ISSUE TITLE
How do i specify default permits when creating semaphore object with RMap

### ISSUE THREAD

**Issue by shashanka981** [redisson/redisson#2570]
i am trying to create semaphore using below method from RMap interface. 

**RSemaphore getSemaphore(K key);**

What is the default permits associated with this semaphore ?  i wanted to use Semaphore as an alternate to RLock , so i need a default max permit of 1. I see trySetPermits() method in RSemaphore class.. But is there a way to set default number of permits while creating Semaphore object without having to call trySetPermits() method.
Without a provision to set a default number of permits, how would we achieve the scenario where multiple threads are trying to create a semaphore with same key ? Developer is forced to ensure that everytime a semaphore object is created for a given key,  trySetPermits() method need to be called exactly once in the entire lifecycle of application. Is my understanding right ? what happens in below scenario assuming events happen in same sequence as listed

thread 1 calls rmap.getsemaphore(key1);
thread 1 calls trySetPermits(1); // number of availble permits is 1 
thread 1 calls acquire();  // number of available permits to 0

thread 2 calls rmap.getsemaphore(key1);
thread 2 calls trySetPermits(1); // Will this call sets the available permits to 1 again ? What would happen here?
thread 2 calls acquire() // ideally thread 2 should not acquire permit.  What would happen here?

**Comment by mrniko** [comment]
> how would we achieve the scenario where multiple threads are trying to create a semaphore with same key ?

all RSemaphore methods are thread safe. `trySetPermits` method will set it only once.

**Comment by mrniko** [comment]
right, second call of acquire method will wait for permit.
