### ISSUE TITLE
RedissonLock fails to unsubscribe from channel when a lock is acquired

### ISSUE THREAD

**Issue by oanagoanta-td** [redisson/redisson#2575]
**Expected behavior**
The pub/sub channels that are created while trying to acquire a lock with RedissonLock should be unsubscribed when no longer needed.

**Actual behavior**
Some pub/sub channels are still present (meaning that the client did not unsubscribe) even after some locks are no longer used (either they expired or were unlocked). These channels are never cleaned up (still present after 24h since created). The only workaround to get rid of these is to restart the client.
This was observed because it caused a connection leak. When calling RedissonLock to obtain new locks this returned the error : `Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.` We have increased the limits in order to have a workaround for this bug

**Steps to reproduce or test case**
- use RedissonLock.java implementation with method lockInterruptibly(long leaseTime, TimeUnit unit) to obtain multiple locks simultaneously. 
- use lower limits for  subscription-connection-pool-size and  subscriptions-per-connection to increase the probability to see the bug
- wait until this error shows up `Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.` 
- connect to Redis server and fetch all lock keys and all pub-sub channels. 
- if number of pub-sub channels > active locks , then the bug was reproduced
- if number of pub-sub channels does not decrease at all long after locks are being created, this means that subscriptions have leaked, active long after these are no longer used in RedissonLock implementation

**Redis version**
5.0.5

**Redisson version**
3.11.6

**Redisson configuration**

```
    <redisson:client id="redissonClient">
        <redisson:single-server
            address="${redis.url}"
            idle-connection-timeout="10000"
            ping-timeout="1000"
            connect-timeout="10000"
            timeout="5000"
            connection-pool-size="32"
            connection-minimum-idle-size="12"
            subscription-connection-pool-size="64"
            subscriptions-per-connection="25"
        />
    </redisson:client>
```

**Comment by mrniko** [comment]
> The pub/sub channels that are created while trying to acquire a lock with RedissonLock should be unsubscribed when no longer needed

All channel are unsubscribed in finally code block of lock method.

Unable to reproduce this. Below is my test:

```java
        Config config = new Config();
        config.useSingleServer()
                .setSubscriptionConnectionPoolSize(1)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionsPerConnection(1)
                .setAddress("redis://127.0.0.1:6379");

        RedissonClient redisson  = Redisson.create(config);
        ExecutorService e = Executors.newFixedThreadPool(16);
        for (int i = 0; i < 100000; i++) {
            e.submit(() -> {
                RLock lock = redisson.getLock("lock");
                lock.lock();
                lock.unlock();
            });
        }

        e.shutdown();
        e.awaitTermination(10, TimeUnit.MINUTES);
```
