### ISSUE TITLE
How to know if RedissonMap is created at redis end 

### ISSUE THREAD

**Issue by SushmaReddyLoka** [redisson/redisson#2576]
Is there a way to know if a map with given name is created at redis end. As per understanding, org.redisson.api.RedissonClient.getMap(java.lang.String name) always gives new RedissonMap and only creates interacts with redis when one does any map operations like get/put. 
Which means Using org.redisson.api.RedissonClient.getMap(java.lang.String name) will not send any request to redis ?
So how can i know that if a map with given name already exists at redis end using any of the redisson apis?

**Comment by mrniko** [comment]
use `RMap.isExists` method

**Comment by SushmaReddyLoka** [comment]
Thanks for the response. Along with it can you confirm if my understanding about getMap api is correct ?

**Comment by mrniko** [comment]
> gives new RedissonMap and only creates interacts with redis when one does any map operations like get/put.

Yes, RMap is fully stateless on Redisson side.
