### ISSUE TITLE
I find a bug about Redisson,when I use it to set data into redis server.

### ISSUE THREAD

**Issue by tomcat-boy** [redisson/redisson#2579]
code: 
**redissonClient.getBucket("test123456").set("http://q57u6k1j6.bkt.clouddn.com/7c1da11a-c920-47ac-9b15-a83b3d2daaca");**
I want to set "http://q57u6k1j6.bkt.clouddn.com/7c1da11a-c920-47ac-9b15-a83b3d2daaca" into redis server,but I find that this data become "    Ehttp://q57u6k1j6.bkt.clouddn.com/7c1da11a-c920-47ac-9b15-a83b3d2daaca",when I check redis server with tool——Redis Desktop Manager.

**Comment by mrniko** [comment]
this is the value in serialized state. Use StringCodec.INSTANCE to avoid any serialization.

**Comment by tomcat-boy** [comment]
Thank you very much for helping me.
