### ISSUE TITLE
Add TTL on Comparator

### ISSUE THREAD

**Issue by joeleclems** [redisson/redisson#2580]
**Is your feature request related to a problem? Please describe.**
We works with a lot of priority queue associated with Comparator (method trySetComparator). Result : Redisson create object in database like {akey}:redisson_sortedset_comparator, but never remove them.

**Describe the solution you'd like**
Could you add a parameter to set a TTL on theses objects? perhaps in method trySetComparator?

**Describe alternatives you've considered**
We have to delete these keys regularly, by hand

**Comment by mrniko** [comment]
Fixed. Thanks for report. Now delete and expire methods take in account comparator key.
