### ISSUE TITLE
Behaviour of RPermitExpirableSemaphore

### ISSUE THREAD

**Issue by shashanka981** [redisson/redisson#2581]
few questions on RPermitExpirableSemaphore

1) what is the probability that permit id generated by  acquire() method returns same permit id for different or same key ? In otherwords is there a possiblity of collision of permit Ids in any scenario when acquiring the permit via this interface ?

2) What happens to the permit when redisson node on which the permit was taken has crashed after permit ? Does the permit expire ? Does the LockWatchDogTimeout come into play here as well ?

3) How does LockWatchDog Scheduler works ? Is this a single daemon thread or is there a TimerTask triggered for every lock request ? I am looking to understand implementation details of LockWatchDog . can we get a reference to the java class in Redisson Source code that is responsible for prolonging the expiry of keys

**Comment by mrniko** [comment]
1. for 10^12 hashes probability is 2.93873588×10^−15. Basically zero.
2. that depends on leaseTimeout parameter defined during acquisition.
3. LockWatchDog Scheduler only applied to Lock object. https://github.com/redisson/redisson/blob/f7b3fbc64a422e625f974b23f1d5dfc73542ad1e/redisson/src/main/java/org/redisson/RedissonLock.java#L301

**Comment by shashanka981** [comment]
for 10^12 hashes probability is 2.93873588×10^−15. Basically zero.
   -- is this true for when calculating for same key same mapname

**Comment by mrniko** [comment]
it's true for overall amount of hashes.
