### ISSUE TITLE
Writing to RLocalCachedMaps is seeding the data to redis

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#2584]
Hello Nikita,

In our application we are using RLocalCachedMaps to improve performance. In certain cases we want to persist the data locally and not send it to redis. For that we are writing to RLocalCachedMaps with the assumption that it would not seed the same data to redis. But we see in background that writes to RLocalCachedMaps are also sent to redis. We verified this using Monitor command on Redis Server.

Can you please confirm if we have a way to prevent the writes to RLocalCachedMaps from going to redis. In case if there is any other Map that we should use, kindly let us know about that as well.

Thanks

**Comment by mrniko** [comment]
RLocalCachedMaps always persist data to Redis. Did you try to use separate ConcurrentHashMap instance for this purpose?

**Comment by jainyash88** [comment]
We want to have the maps in sync with redis but use it only for reads. The writes should not persist to redis. I am not sure if we have this ability from any of the redisson maps. Can you please confirm if we can have such a functionality from any of the RMap implementations

**Comment by mrniko** [comment]
> We want to have the maps in sync with redis but use it only for reads. The writes should not persist to redis.

The easiest way is to make it immutable with `Collections.unmodifiableMap(...)`

**Comment by mrniko** [comment]
Done. Use `LocalCachedMapOptions.storeMode = LOCALCACHE`
