### ISSUE TITLE
What happens when Locks are not released because of a thread terminate/crash 

### ISSUE THREAD

**Issue by shashanka981** [redisson/redisson#2590]
1) When using RLock to acquire Lock, Does LockWatchDog releases the lock when the thread that acquired the lock crashes for some reason without unlocking ? 

2) Does Redisson gurantee that taking a permit on semaphore via RPermitExpirableSemaphore/Semaphore is an atomic operation ? Means what happens when Redis or Redisson gets crashed in the process of creating the semaphore object ? Is there any chance that there is some partial state left on the Redis ?

**Comment by mrniko** [comment]
1. in case of crash watchdog doesn't extend lock and it expires/releases automatically.
2. eval script is executed atomically

**Comment by shashanka981** [comment]
is it true for just node crash or thread crash as well ?

**Comment by mrniko** [comment]
watchdog doesn't extend lock expiration time and it expires/releases automatically.

**Comment by shashanka981** [comment]
i tried to reproduce this scenario and i can lock is not released automcatically when thread that taken the lock is no longer alive ? is this expected behavior with a default lock watchdog timeout

 ```
Thread t = new Thread() {
            @Override
            public void run()  {
                RLock lock = redissonClient.getLock("testthread");
                lock.lock(10000, TimeUnit.SECONDS);
            }

        };

        t.start();
        t.join();
        t.stop();
        Thread.sleep(60000);
        RLock lock1 = redissonClient.getLock("testthread");
        System.out.println(lock1.isLocked());   // This returns true while expect this to be released
```

**Comment by mrniko** [comment]
Yes, since Redisson instance is still alive

**Comment by lztry** [comment]
Isn’t it better to judge whether the thread exists before the watchdog extends the time?

**Comment by lztry** [comment]
> Yes, since Redisson instance is still alive

Isn’t it better to judge whether the thread exists before the watchdog extends the time?

**Comment by mrniko** [comment]
@lztry 

This issue will be fixed in https://github.com/redisson/redisson/issues/2714

**Comment by lztry** [comment]
OK, thank you
