### ISSUE TITLE
onConnect, onDisconnect seem doesn't work as expected

### ISSUE THREAD

**Issue by ieiayaobb** [redisson/redisson#2591]
We're using the Redis provided by AWS ElastiCache, Cluster mode and we need to handle some logic once losing connections with Redis, so we implement these 2 methods.

I shutdown the Redis manually in order to test these methods. However, it doesn't work as expected.

onDisconnect() is trigged successfully while onConnect() is also trigged unexpectly. Is there anything wrong inside?

**Comment by willy23martin** [comment]
Hi @ieiayaobb 

Maybe you could check if you have configure the ConnectionListener before create the RedissonClient. 

I understood and also tested that you need first load the Config YAML file (for example) and then add your custom ConnectionListener to the Config object. In my case, once I had those steps completed, I could create the RedissonClient by using the Config object and it is working as I expected. 

I hope it can help you.

**Comment by mrniko** [comment]
connectionListener setting was moved to Config object and works properly.
