### ISSUE TITLE
Is it possible to destroy session on deserialization issue?

### ISSUE THREAD

**Issue by sibmaks** [redisson/redisson#2592]
Redisson version: 3.12.1

We have the next situation:

Sometimes we update some of our entities that stored in a session.

After that we get a lot of exceptions in log:

```
org.redisson.client.RedisException: Unexpected exception while processing command
--
at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:401)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:205)
at org.redisson.RedissonObject.get(RedissonObject.java:94)
at org.redisson.RedissonMap.readAllMap(RedissonMap.java:507)
at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:111)
...
Caused by: java.io.InvalidClassException: com.SomeEntity; local class incompatible: stream classdesc serialVersionUID = 123, local class serialVersionUID = 321
```

We catch this exception when we trying to get some client session parameters.

And it looks strange because the client already in the authorized zone and have a session, but actually session is invalid, so is it possible to invalidate session on deserialization?

**Comment by sibmaks** [comment]
Yes, I forgot to notice, we use org.redisson.codec.SerializationCodec and can't use JSON-like codes, because we have some recursion links.

**Comment by mrniko** [comment]
Please do it with Valve object rather than suggesting patch

**Comment by sibmaks** [comment]
@mrniko hi, we can do it. So currently we built own wrapper above your session manager with these changes.

**Comment by mrniko** [comment]
You could add one Valve object and invalidete session in org.redisson.tomcat.Valve#invoke method

**Comment by sibmaks** [comment]
I think that org.apache.catalina.valves.RequestFilterValve looks better in this case. But the whole solution looks like a crutch because we just have to request any attribute and deny the request on any exception.
Also, in this case, we have to integrate redisson with our app, currently, we don't use redisson in it. Except for the tiny library that fixed this issue.
