### ISSUE TITLE
Listener question / feature

### ISSUE THREAD

**Issue by Aurelien30000** [redisson/redisson#2594]
Hey, sorry for disburbing, is there a way or an event to listen to Object change (for example when I call RBucket.set(something) ? 

If no, what do you advise me to use instead ?

Thanks in advance ! :)

**Comment by mrniko** [comment]
just subscribe to `PUBLISH __keyspace@0__:mykey set` via `RTopic` object

**Comment by Aurelien30000** [comment]
> just subscribe to `PUBLISH __keyspace@0__:mykey set` via `RTopic` object

Thanks again, really good software !

**Comment by mrniko** [comment]
`org.redisson.api.SetObjectListener` added

**Comment by Aurelien30000** [comment]
> `org.redisson.api.SetObjectListener` added

Oh really cool ! Is there just a place to get the jar file or should I build it in my ways ? :)

**Comment by Aurelien30000** [comment]
And just for info, your advise about how to subscribe a value by a key doesn't work correctly for me :/

```
//1
RBucket<Integer> rBucket = redissonClient.getBucket("test");
rBucket.addListener((ExpiredObjectListener) s -> {
    System.out.println("event 1");
});

//2
redissonClient.getPatternTopic("PUBLISH __keyspace@0__:test expired",StringCodec.INSTANCE).addListener(Integer.class, (charSequence, charSequence1, integer) -> {
    System.out.println("event 2");
});

//3
Task.repeat(0, 50, true, (taskId) -> {
    rBucket.set(RandomTools.getRandomInteger(10000), 1, TimeUnit.SECONDS);
});
```

First paragraph represents the registration via the api, works correctly !

Second paragraph represents logically the same registration in another way, following your comment (I also tested with `getTopic()` and oher commands (`del, set, etc`) doesn't work.

Third paragraph should be ignored, just a task from my own mehods, that occurs every 2.5 seconds.

Thanks in advance for your help _and sorry for disturbing if I made a mistake_ ! :)

**Comment by mrniko** [comment]
> getPatternTopic("PUBLISH __keyspace@0__:test expired")

it has wrong topic, try follow: "__keyspace@*:expired"

**Comment by Aurelien30000** [comment]
> > getPatternTopic("PUBLISH **keyspace@0**:test expired")
> 
> it has wrong topic, try follow: "__keyspace@*:expired"

Doesn't work either :/ But don't worry, I'll wait for a release or a jar with SetObjectListener, it's enough for my use :)

**Comment by mrniko** [comment]
Did you set `notify-keyspace-events = E$` Redis setting

**Comment by Aurelien30000** [comment]
Yes ^^ 
![image](https://user-images.githubusercontent.com/43724816/75032469-f7fccc00-54a8-11ea-9f83-31cbd58866c0.png)

**Comment by mrniko** [comment]
Did you try to set `org.redisson.api.ExpiredObjectListener` to catch expired events?

**Comment by Aurelien30000** [comment]
> Did you try to set `org.redisson.api.ExpiredObjectListener` to catch expired events?

Yes, that's the first paragraph of my code above, and it's perfectly working, but I need "manual" catch for events that are not in the api (like set event if you added it) :)

**Comment by Aurelien30000** [comment]
Nevermind, it's working with SetObjectListener, thanks again :)

**Comment by Aurelien30000** [comment]
Hey !

Sorry for reopening this issue / question but whould be great if you could add the same opportunities for a List (when an element is added for example).

Thanks in advance ! :)

**Comment by mrniko** [comment]
Done

**Comment by Aurelien30000** [comment]
Hey, sorry for disturbing,

With the new event `ListRemoveListener`, is there a way to get the deleted element or not ?

Thanks in advance :)

**Comment by mrniko** [comment]
@Aurelien30000 

Just call `RList.removeListener()` method
