### ISSUE TITLE
Map EntryExpiredListener 

### ISSUE THREAD

**Issue by Alex-Amo** [redisson/redisson#2595]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
3.11.2
**Redisson configuration**
Sentinel mode

Map EntryExpiredListener is disabled, which is restored after the application is restarted, but will be disabled again soon.
I found that it would work every half hour during the failure, which should be a clue.

**Comment by mrniko** [comment]
Is there any error in logs?

**Comment by mrniko** [comment]
Unable to reproduce
