### ISSUE TITLE
tryLock()，Machines are not evenly distributed, and one server never gets the lock

### ISSUE THREAD

**Issue by wangqingfan** [redisson/redisson#2596]
Machines are not evenly distributed, and one server never gets the lock.It's going to last forever
redisson 3.12.2

**Comment by mrniko** [comment]
Use `RFairLock` object in this case

**Comment by wangqingfan** [comment]
> `RFairLock`在这种情况下使用对象

So if you have two machines executing alternately, you still can't do about 1:1

**Comment by wangqingfan** [comment]
> Use `RFairLock` object in this case

So if you have two machines executing alternately, you still can't do about 1:1

**Comment by mrniko** [comment]
You will with `RFairLock`

**Comment by wangqingfan** [comment]
> You will with `RFairLock`

So if you have two machines executing alternately, you still can't do about 1:1
