### ISSUE TITLE
Memory leak or misconfigured

### ISSUE THREAD

**Issue by mikemosseri** [redisson/redisson#2597]
We are having an issue using Redisson with Hibernate 5.3.

It appears the items are getting removed correctly due to the TTL, but their is still a Sorted Set that grows without ever getting pruned.

Any of the "redisson__map_cache__last_access__set:{**}" grow without ever having elements removed.

Current properties:
hibernate.cache.redisson.timestamps.expiration.time_to_live: 10
hibernate.cache.redisson.naturalid.expiration.time_to_live: 10
hibernate.cache.redisson.collection.expiration.time_to_live: 10
hibernate.cache.redisson.entity.expiration.time_to_live: 10
hibernate.cache.redisson.query.expiration.time_to_live: 10

Add sensible max. Otherwise they are unbounded.
hibernate.cache.redisson.timestamps.eviction.max_entries: 10000
hibernate.cache.redisson.naturalid.eviction.max_entries: 10000
hibernate.cache.redisson.collection.eviction.max_entries: 10000
hibernate.cache.redisson.entity.eviction.max_entries: 10000
hibernate.cache.redisson.query.eviction.max_entries: 10000

Also tried adding:
hibernate.cache.redisson.timestamps.expiration.max_idle_time: 0
hibernate.cache.redisson.naturalid.expiration.max_idle_time: 0
hibernate.cache.redisson.collection.expiration.max_idle_time: 0
hibernate.cache.redisson.entity.expiration.max_idle_time: 0
hibernate.cache.redisson.query.expiration.max_idle_time: 0

I've traced the code and I don't see any locations where the redisson__map_cache__last_access__set has any elements removed.

In the MapCacheEvictionTask, it does pass in the key, but it is never used in the LUA.

Let me know if I'm missing something in the config. Thanks!

**Comment by mikemosseri** [comment]
Is this a regression bug?

**Comment by mrniko** [comment]
Thanks for report! It's not a regression bug.

**Comment by mrniko** [comment]
Fixed

**Comment by mikemosseri** [comment]
Thank you! Sorry to comment on a closed issue, any change to get a release so soon after the 3.12.2 was released 2 days ago?

**Comment by mrniko** [comment]
Probably I'll make another one in 10 days.
