### ISSUE TITLE
warnings coming from dependent library fst

### ISSUE THREAD

**Issue by xbranko** [redisson/redisson#2599]
**Expected behavior**
This is observed in JDK11 JVM. There should be no warnings, especially those that indicate that code may stop working in a future release.

**Actual behavior**
Warnings issued. See also [(fst 295)](https://github.com/RuedigerMoeller/fast-serialization/issues/295) Reporting here to make redisson committers aware.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/.../fst-2.57.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
**Steps to reproduce or test case**
Running the app that uses redisson

**Redis version**
N/A
**Redisson version**
3.12.2
**Redisson configuration**
N/A

**Comment by mrniko** [comment]
As workaround use Kryo5Codec, JsonJacksonCodec or SerializationCodec
