### ISSUE TITLE
Mocking Redisson

### ISSUE THREAD

**Issue by nareshsankapelly** [redisson/redisson#260]
Is there any library for mocking Redisson? I have a scenario where I do not want to have Redis server running for unit tests. 

There is a library for Jedis. https://github.com/50onRed/mock-jedis.

**Comment by a1u** [comment]
hi, also voting for that feature. Currently I see no way to test service that is using redisson without connecting to live redis env.

**Comment by oleg-gr** [comment]
:+1: 
Had to mock Redisson out myself several times. Having spring cache helps, but for some projects had to create manual stubs

**Comment by diciccom** [comment]
+1

**Comment by vvstej** [comment]
+1

**Comment by melovy** [comment]
+1

**Comment by loic-seguin** [comment]
+1

**Comment by geco82** [comment]
+1

**Comment by tedwarner** [comment]
+1

**Comment by snrklyc** [comment]
+1

**Comment by znck** [comment]
+1

**Comment by johnou** [comment]
@nareshsankapellyfkrt what's your scenario? Frankly I disagree with all of your +1s, I don't see the big deal about running an embedded redis server for tests. Redisson uses lua scripts for a lot of its operations and mocking all of the Java objects and services that it provides would not only be extremely cumbersome but error prone. Redisson has over 1000 functional unit tests for its Java objects and services, if you want to mock Redisson, mock the Java objects and services, if you want an integration test, fire up an embedded redis server and use that.

**Comment by itay-keller** [comment]
+1
I like to have control during the unit test. Working with real Redis will be in the integration test phase.

**Comment by dahiyahimanshu** [comment]
i am using redisson 3.9.1 i am not able to store something in cache by starting the embedded redis server. i think the redis server version is too old for my redisson. So now it seems there is no way out.

**Comment by Remeic** [comment]
There are updates? i have to make unit test in isolation

**Comment by Ikki-Dai** [comment]
+1

may need a redis instance alive for unit test, implement may like [embedded-redis](https://github.com/ozimov/embedded-redis) lib
but it is too old and not embedded higher version to support **Stream** or **Redisson ReliableTopic** feature
