### ISSUE TITLE
Memory leak when using cluster mode to read by RBatch

### ISSUE THREAD

**Issue by wuwangben** [redisson/redisson#2601]
**Expected behavior**
No memory leak
**Actual behavior**
Memory leak
**Steps to reproduce or test case**
`public class CNRedisHandleFactory {
    public static RedissonClient redisson;
    public static BatchOptions options;
    public static void main(String[] args) throws InterruptedException {
//        String clusterAddress = "192.168.11.73:7000||192.168.11.73:7001||192.168.11.83:7000||192.168.11.83:7001||192.168.11.93:7000||192.168.11.93:7001||192.168.11.107:7000||192.168.11.107:7001||192.168.11.111:7000||192.168.11.111:7001||192.168.11.121:7000||192.168.11.121:7001||192.168.11.131:7000||192.168.11.131:7001";
        String ipAddress = "10.253.0.41:7000||10.253.0.41:7001||10.253.0.87:7000||10.253.0.87:7001||10.253.0.112:7000||10.253.0.112:7001||10.253.0.138:7000||10.253.0.138:7001||10.253.0.142:7000||10.253.0.142:7001||10.253.0.159:7000||10.253.0.159:7001||10.253.0.192:7000||10.253.0.192:7001";
        int timeOut = 5000;

        List<String> sp = Arrays.asList(ipAddress.split("\\|\\|"));
        List<String> stringList = sp.stream().map(x->"redis://"+x).collect(Collectors.toList());
        String[] ip=stringList.toArray(new String[stringList.size()]);
        Config config = new Config();
        config.useClusterServers().addNodeAddress(ip)
                .setScanInterval(1000).setReadMode(ReadMode.MASTER_SLAVE)
                .setTimeout(timeOut)
                .setRetryAttempts(0)
                .setMasterConnectionPoolSize(64)
                .setSlaveConnectionPoolSize(64)
                .setMasterConnectionMinimumIdleSize(24)
                .setSlaveConnectionMinimumIdleSize(24)
        ;

        options = BatchOptions.defaults()
                .responseTimeout(timeOut, TimeUnit.MILLISECONDS)
                .retryInterval(1500, TimeUnit.MILLISECONDS)
                .retryAttempts(0);

        redisson = Redisson.create(config);

        int thread = Integer.parseInt(args[0]);
        int sleep = Integer.parseInt(args[1]);
        System.out.println("thread:" + thread + " sleep:" + sleep);

        for (int i = 0; i < thread; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    while (true) {
                        try {
                            Set<String> set = new HashSet();
                            int randomKeyNum = new Random().nextInt(10);
                            for (int loop = 0; loop <= randomKeyNum; ++loop) {
                                set.add(redisson.getKeys().randomKey());
                            }
                            Map<String, byte[]> temp = getByteArrayMap(set.toArray(new String[set.size()]));

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        try {
                            Thread.sleep(sleep);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }).start();
        }

        Thread.sleep(1000000000000L);
    }

    public static Map<String,byte[]> getByteArrayMap(String... keys){
        Map<String, byte[]> res = new HashMap<>();
        RBatch batch = redisson.createBatch(options);
        for (String key : keys) {
            batch.getBucket(key, new ByteArrayCodec()).getAsync();
        }
        List<?> res1 = batch.execute().getResponses();
        for (int i = 0; i < res1.size(); i++) {
            if (res1.get(i) != null) {
                res.put(keys[i], (byte[]) res1.get(i));
            }
        }
        return res;
    }

}
`
**Redis version**
5.0 and cluster with 7 nodes
**Redisson version**
3.12.2
**JDK**
1.8.0_91
**Redisson configuration**
```
Redisson configuration
		config.useClusterServers().addNodeAddress(ip)
        .setScanInterval(1000).setReadMode(ReadMode.MASTER_SLAVE)
        .setTimeout(timeOut)
        .setRetryAttempts(0)
        .setMasterConnectionPoolSize(64)
        .setSlaveConnectionPoolSize(64)
        .setMasterConnectionMinimumIdleSize(24)
        .setSlaveConnectionMinimumIdleSize(24)
;

options = BatchOptions.defaults()
        .responseTimeout(timeOut, TimeUnit.MILLISECONDS)
        .retryInterval(1500, TimeUnit.MILLISECONDS)
        .retryAttempts(0);
```
and request controller, 500 threads and each HTTP GET request will fetch 1-10 RandomKeys from Redis cluster in batch mode then sleep 30ms.
**JVM PARAMS**
`JAVA_OPTS="-Xms400M -Xmx400M -XX:MaxDirectMemorySize=1G "`

**Comment by wuwangben** [comment]
![dump](https://user-images.githubusercontent.com/16200775/74900814-dd105600-53db-11ea-8e4f-a3fed8b0e1b3.png)

**Comment by mrniko** [comment]
Same as https://github.com/redisson/redisson/issues/2574

**Comment by mrniko** [comment]
use `new FstCodec(FSTConfiguration.createDefaultConfiguration(), false)` as codec

**Comment by wuwangben** [comment]
> use `new FstCodec(FSTConfiguration.createDefaultConfiguration(), false)` as codec or try `Kryo5Codec`

Thank you for your reply.
After modification, the problem still exists.
`config.setCodec(new FstCodec(FSTConfiguration.createDefaultConfiguration(), false))`
![QQ图片20200220200442](https://user-images.githubusercontent.com/16200775/74932480-e837a600-541c-11ea-8b2a-63de478c8a67.png)

**Comment by mrniko** [comment]
Which application server do you use to run it?

**Comment by wuwangben** [comment]
> Which application server do you use to run it?

自定义的基于redis的缓存服务
Customized redis based caching service

**Comment by mrniko** [comment]
I mean java application server

**Comment by mrniko** [comment]
Reducing of threads amount will reduce memory consumption. Since coded is bounded per thread classloader.

**Comment by wuwangben** [comment]
> Reducing of threads amount will reduce memory consumption. Since coded is bounded per thread classloader.

High concurrency RPC service developed with netty. 
It's OK to use Redisson version 3.4.2 in sentinel mode

**Comment by wuwangben** [comment]
![testEnv](https://user-images.githubusercontent.com/16200775/74935206-d6590180-5422-11ea-8fb7-53ac2b1a1aef.png)
Test Environment.

**Comment by mrniko** [comment]
Use CompositeCodec as singleton.

**Comment by mrniko** [comment]
Do you create CompositeCodec instance in code?

**Comment by wuwangben** [comment]
> Do you create CompositeCodec instance in code?

NO，I don't

**Comment by wuwangben** [comment]
> use `new FstCodec(FSTConfiguration.createDefaultConfiguration(), false)` as codec or try `Kryo5Codec`
Sorry, Wrong verification before. Use `new FstCodec(FSTConfiguration.createDefaultConfiguration(), false)`  This problem did not reproduce. This problem did not reproduce,Thank you.
