### ISSUE TITLE
Add field "name" to RedissonCache

### ISSUE THREAD

**Issue by KristinaBekker** [redisson/redisson#2602]
Hi, it would be nice to have the ability to set  name for RedissonCache different from map inside cache.

To have different cache in different services with same names in the one redis instance just changing the name of the map inside the cache.

**Comment by mrniko** [comment]
Why can't you use `rename` method?

**Comment by KristinaBekker** [comment]
@mrniko because I used `RedissonSpringCacheManager`. I just create new `RedissonSpringCacheManager `and set config. Now I should to rename cashes in config from microservices and add prefix like 'service_name'.  When Spring call methd `getCache`, 
`RedissonSpringCacheManager.getCache` is called. Into this method  other method is called -> `createMap`.
This is private method, and I can change it, I don't want'to fork all RedissonSpringCacheManager.
I don't understand how method `rename` can help me.

**Comment by mrniko** [comment]
Basically, you want to create some kind of multiple aliases to the same cache?

**Comment by mrniko** [comment]
`RedissonSpringCacheManager.rename` method should be added if you want to rename cache. If you have a PR I would be glad to consider it.

**Comment by KristinaBekker** [comment]
I want to have the same name for caches from different microservices, which have different map inside. Because there is a common Redis instance for all of this. For example two services. First is mesageSender, second is mesageReciever. Both have different caches with same name "allowedEmails". But there are two maps in Redis "mesageSender_allowedEmails" and "mesageReciever_allowedEmails".
It would be nice to be able to set prefixes in configuration like in SpringDataRedis. I don't have PR because I am not sure if you have this feature in the full version. I am using free.
I'd like to try to do this feature and create PR if you don't have this.

**Comment by mrniko** [comment]
> Because there is a common Redis instance for all of this

Did you try to define database? Redis allows to define multiple databases in the same setup.

**Comment by KristinaBekker** [comment]
I can't use multiple database because I save some common settings for all microservices in Redis.
So I have only one common database for all  services.

**Comment by mrniko** [comment]
> It would be nice to be able to set prefixes in configuration like in SpringDataRedis

Could clarify here with code example?
