### ISSUE TITLE
Auto-Reconnect to a Modifed Elasticache Cluster

### ISSUE THREAD

**Issue by eltalkarim** [redisson/redisson#2608]
I am trying to optimize an elasticache cluster clustered mode disabled in productive use by downscaling to a smaller instance type. As we all know, AWS will migrate to new nodes with different IP addresses and the client will need to reconnect.  I would like to configure my redisson client to reconnect fast to the master node so we minimize the downtime as much as possible. What are the best practices to reduce downtime and to connect to new master nodes and slaves as fast as possible? Note that I am using ReplicatedServers to connect to the cluster.

**Comment by mrniko** [comment]
It depends on how fast AWS update topology info returned by `INFO REPLICATION` command. Increase `retryAttempts` and `retryInterval` parameters for exceptionless transition.
