### ISSUE TITLE
Does any form of visibility / metrics / eventing require Redisson Pro

### ISSUE THREAD

**Issue by mikebell90** [redisson/redisson#2609]
From what I can tell it does. I don't think this is justified. No one should be using a library - casually or otherwise - without metrics and a basic eventing system.

There's many fine features of this product that I'd be HAPPY with as commercial only, including most of its task scheduling, but metrics is an absolute no-go.

Of course my needs may be different from others, but I ask you to reconsider this. Even providing a basic eventing system that OSS could build metrics from would be great.

**Comment by mrniko** [comment]
Thanks for sharing your opinion. Unfortunately, this feature can't be part of OSS project. My apologies, if you have to choose the other solution in this case.
