### ISSUE TITLE
In a frequent job , sometime lock.tryLock() can not get lock

### ISSUE THREAD

**Issue by mi13chael** [redisson/redisson#2613]
<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-boot-starter</artifactId>
			<version>2.15.2</version>
		</dependency>
In a spring boot 1.5.6 application , We have a new job which is running every 30 seconds and try to acquire lock to do something . In recent days the job has tried to acquire one specific lock cause of business , We found from 00:13 on Feb 24  the job can not get the lock but after 15:03 the job can get the lock again . The operation on this lock only in this job . 
the code on the lock as below :

        boolean res = lock.tryLock();
        if (res) {
            try {
                ...
            } finally {
                if (lock.isHeldByCurrentThread())
                    lock.unlock();
            }
        } else {
            LockUtils.logLockError(lockName, amount, null, "consume balance");
            msg = String.format("acquire merchant account lock (%s)failed", lockName);
        }

Thanks

**Comment by mrniko** [comment]
I would recommend to remove `if (lock.isHeldByCurrentThread())` this check since unlock should be invoked in any case.

**Comment by mi13chael** [comment]
I think if the lock acquired in another thread , unlock should be invoked in that thread .

**Comment by mrniko** [comment]
I don't see any other reason except dealy in code execution between braces.

**Comment by mrniko** [comment]
> I think if the lock acquired in another thread , unlock should be invoked in that thread .

all the more you don't need to add this check.

**Comment by mi13chael** [comment]
Thanks , I already had this update in the job , will see what happened in the future.

**Comment by mi13chael** [comment]
That is a point to catch who is operating the lock in the meantime.

**Comment by mi13chael** [comment]
the situation have not happened again .
