### ISSUE TITLE
A WARNING

### ISSUE THREAD

**Issue by tomcat-boy** [redisson/redisson#2615]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/D:/tool/dev-java/maven-repository/de/ruedigermoeller/fst/2.57/fst-2.57.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by mrniko** [comment]
Consider to choose different codec
