### ISSUE TITLE
Can RRateLimiter create permits evenly

### ISSUE THREAD

**Issue by MrXionGe** [redisson/redisson#2617]
**Is your feature request related to a problem? Please describe.**
This doesn't seem to be a problem, I just don't think it is elegant enough.

**Describe the solution you'd like**
When I use RRateLimiter:
++++++++++++++++++++++++++++++++++++++++++++++++++++
``` java
limiter.trySetRate(RateType.OVERALL, 2, 1, RateIntervalUnit.SECONDS);
```
Like this, it will be 1 second apart and then create 2 permits in a split second.
++++++++++++++++++++++++++++++++++++++++++++++++++++
``` java
limiter.trySetRate(RateType.OVERALL, 8, 4, RateIntervalUnit.SECONDS);
```
Like this, it will be 4 seconds apart and then create 8 permits in a split second.
I think it is best if it can create 8 permits evenly in 4 seconds. Instead of creating 8 permits in an instant after 4 seconds. I hope it can be smart to create permits every 500ms.
If I use "(RateType.OVERALL, 1, 500, RateIntervalUnit.MILLISECONDS)", this will affect the capacity of the bucket.

**Describe alternatives you've considered**
I didn't think of a good solution, I just hope that he can create permits evenly according to my configuration.

**Comment by mrniko** [comment]
RateLimiter algorithm improved in 3.13.3 version. Now it uses zset to create permits evenly.
