### ISSUE TITLE
RMapCache Cache expiration on a cluster of Redisson clients

### ISSUE THREAD

**Issue by harry9111985** [redisson/redisson#2619]
Hi @mrniko ,

I have a query regarding RMapCache expiration events . I have the following use case

I have a backend API which will push data to redis on an API call from a third party system . I am setting a ttl to the key because I want to initiate a process in the background when the key expires. 
The process to listen to key expiration events sits in a microservice. 

I read in the documentation there is a EntryExpiredListener for RMapCache. 

Now if the microservice sits in a cluster and if I am subscribing to key expiration events on RMapCache through EntryExpiredListener in each of my microservice instance then 

a) if the key is "123" for example , on ttl expiry would all the instances get the key expiration notification ? 

b) if yes , is it possible to shard the key expiration events of RMapCache lets say in 100 expiration events , 50 events go to instance 1 and 50 got to instance 2 ?

c) Whats the performance of key expiration listener if  I have 100000 expiration events to process , if there is only one instance ?  Is there a hard limit in terms of throttling the no of expired events per poll inside redis/redisson?

Regards,
Harish

**Comment by mrniko** [comment]
> a) if the key is "123" for example , on ttl expiry would all the instances get the key expiration notification ?

All the instances get notification

> b) if yes , is it possible to shard the key expiration events of RMapCache lets say in 100 expiration events , 50 events go to instance 1 and 50 got to instance 2 ?

No

> c) Whats the performance of key expiration listener if I have 100000 expiration events to process , if there is only one instance ? Is there a hard limit in terms of throttling the no of expired events per poll inside redis/redisson?

Performance depends on available system resources. There is no throttling since PUB/SUB is used for notification.

**Comment by OS-ramamurtisubramanian** [comment]
Hi @mrniko,

We are using AWS ElastiCache 7.0.7 with cluster mode enabled. We have 2 master and 2 slave nodes.

We have a similar use case where we have 4 instances of the microservice running and all of them are adding an expiry listener to a mapCache. 

According to the above comment, we expect all 4 instances to receive the same expiry events, but only 2 of the instances get them.

Is this a bug or are we missing some configuration?
