### ISSUE TITLE
Redisson entity invalidation with JCache CreatedExpiryPolicy

### ISSUE THREAD

**Issue by gbarbon** [redisson/redisson#2622]
We are experimenting with Redisson through the JCache implementation. We don't understand completely the behaviour of Redisson using the JCache CreatedExpiryPolicy.

**Test**
The test has been conducted using a cache with a TTL of 30 seconds and CreatedExpiryPolicy as expiry policy. An entry was created and put into the cache at the beginning of the tests, and checked using a loop. When the TTL expiration happens, we try to put again the entity in the cache.  To do this, we use another loop that performs retries until it succeeds.

**Actual behavior**
When the entity is invalidated, it is not possible to put again a new entity with the same key for a given amount of time (usually some seconds). We also tried to remove the entity with that given key just after the invalidation, but it is not possible to do that. It seems like the entity is 'freezed' for a given amount of seconds. The duration of this 'freezed' status is not clear to us. 

In particular, during this 'freezed' status we noticed the following:
- on Redis the entity exists (we checked with `redis-cli`) with the new value and the same key;
- Redisson returns 'null' when we try to get the entity;
- the `jcache_timeout_set:{cache-name}` dataset on Redis (that we think is the one used by Redisson in order to keep track of the timestamps) keeps the old timestamp.

**Expected Behaviour**
For our point of view, the entity should also be removed from Redis when the TTL is expired (probably at the very first moment in which one tries to get it from redis).

Is the actual behaviour by design? How is the duration of this 'freezed' status established?

**Comment by mrniko** [comment]
Fixed! Thanks for report
