### ISSUE TITLE
getPatternTopic not working

### ISSUE THREAD

**Issue by wooque** [redisson/redisson#2623]
**Expected behavior**

Receive published data

**Actual behavior**

Listener never receives published data

**Steps to reproduce or test case**

```java
import org.redisson.Redisson;
import org.redisson.api.RedissonRxClient;
import org.redisson.client.codec.StringCodec;

public class RedisTest {
  public static void main(String[] args) {
    RedissonRxClient redissonRx = Redisson.createRx();

    redissonRx.getPatternTopic("test_*", StringCodec.INSTANCE)
      .addListener(String.class, (pattern, channel, message) -> {

        System.out.println(pattern);
        System.out.println(channel);
        System.out.println(message);

      }).flatMap(r -> {

        System.out.println(r);
        return redissonRx.getTopic("test_2").publish("test");

      }).subscribe(
        System.out::println,
        Throwable::printStackTrace
      );
  }
```

**Redis version**
5.0.7
**Redisson version**
3.12.3
**Redisson configuration**
Default

**Comment by mrniko** [comment]
Unable to reproduce. Here the output:
```
205548456
0
```
Try to append this line to your test: `Thread.sleep(1);` to give some time for result prior test termination

**Comment by wooque** [comment]
@mrniko Those are from println in flatMap and subscribe aka results of addlistener and publish singles, but there is no prints from listener.
There should be 3 prints from pattern, channel and message, something like test_*, test_2, test.
If I change to getTopic("test_2") it works (have to adjust listener obviously because in that case it receives 2 arguments)

**Comment by mrniko** [comment]
Fixed
