### ISSUE TITLE
Reddison live Object as RExpired not correctly clean up index

### ISSUE THREAD

**Issue by wangshao** [redisson/redisson#2625]
Persist an Reddison Live Object and cast it as RExpirable. After expiration, the RMap Objects got deleted while the key remains in the index hash object. Find action will still return an empty proxied object.

And delete action on that object will fail because the map no longer exists.

**Comment by nomar22** [comment]
I think this could be solved with **https://github.com/redisson/redisson/issues/3714**

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/85f85d40ebba864aefaad857914a87c9ac6c4e22

**Comment by jamesjallorina** [comment]
Hi @mrniko, this is just a noob question. Is this still an ongoing issue? I have updated redisson to version 3.20.0 but the same issue is still happening. Your help is very much appreciated!

**Comment by AndriusKli** [comment]
@mrniko  So, what's the status of this? The documentation mentions indexes only in passing (and makes no mention of cleanup), yet looking at the source code, there are some hints here and there (plus the above commit, and a few other closed threads) that this should be handled by Redisson itself, yet this ticket has been open for 3 years, so I'm having a hard time understanding, is this a known issue, or is index cleanup an abandoned feature? 

(Tried on 3.21.0, yet indexes are still not cleaned up when the live object expires/is deleted via other methods)

**Comment by mrniko** [comment]
Fixed
