### ISSUE TITLE
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (6000 ms) occured after 3 retry attempts.

### ISSUE THREAD

**Issue by yzzy03** [redisson/redisson#2628]
**Expected behavior**
We use RedissonSessionManager  that we hope will share the session of the application in redis 
and We use the redis sentinel model.

**Actual behavior**
HTTP Status 500 - javax.servlet.ServletException: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (6000 ms) occured after 3 retry attempts. Increase nettyThreads and/or timeout settings. Command: (HMSET), params: [redisson:tomcat_session:80B3AC0ABE27BB8F8FD991DDEF6F7845, PooledUnsafeDirectByteBuf(ridx: 0, widx: 24, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 13, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 1, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 24, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 10, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 27, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 15, cap: 256), ...], channel: [id: 0xddcae404, L:/10.244.74.154:59414 - R:192.168.11.10/192.168.11.10:6312]
type Exception report

**Steps to reproduce or test case**
This exception occurs on the page or in the background of the application after the user is rare or over the weekend. The application returns to normal after you restart it

**Redis version**
 redis：5.0.3
tomcat：8.0.39
jre：1.8
[redis-error.txt](https://github.com/redisson/redisson/files/4305058/redis-error.txt)

**Redisson version**
3.12.1

**Redisson configuration**
<Manager className="org.redisson.tomcat.RedissonSessionManager"  configPath="${catalina.base}/conf/redisson.yml" readMode="MEMORY"/>

---
sentinelServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 6000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: "*****"
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  sentinelAddresses:
  - "redis://192.168..11.10:16311"
  - "redis://192.168..11.10:16312"
  - "redis://192.168..11.10:16313"
  masterName: "master1"
  database: 0
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
specify [pingConnectionInterval](https://github.com/redisson/redisson/wiki/2.-Configuration#pingconnectioninterval) setting
