### ISSUE TITLE
Why is BaseConfig package protected

### ISSUE THREAD

**Issue by thoraage** [redisson/redisson#2631]
That prevents anyone from generalizing their configuration if they have to configure for multiple environments.

**Comment by mrniko** [comment]
Could you please clarify how does baseconfig extending would help?

**Comment by thoraage** [comment]
Say that I have a SingleServerConfig in one environment and a SentinelServersConfig in another then I want to 

```
BaseConfig<?> baseConfig = createSpecificConfigurationSingleServerOrMultipleServers();
baseConfig.setClientName("dummy");
baseConfig.setPassword("secret");
```

... but I can't; because BaseConfig isn't public.

**Comment by mrniko** [comment]
Done
