### ISSUE TITLE
Can't construct a java object for org.redisson.codec.JsonJacksonCodec

### ISSUE THREAD

**Issue by noseparte** [redisson/redisson#2635]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
3.10.5
**Redisson version**
3.10.5
**Redisson configuration**
`singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: battle
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
`
![image](https://user-images.githubusercontent.com/30165939/76737614-12724e80-67a4-11ea-9ba1-3120706759e8.png)

**Comment by noseparte** [comment]
hey! There was an error getting redisson's yaml configuration file from a different environment through the springcloud config component

**Comment by mrniko** [comment]
Do you read redisson's yaml configuration through `Config#fromYAML()` method?

**Comment by noseparte** [comment]
Instead of via the Config#fromYAML() method, it is installed automatically by loading redisson.yaml and then springboot. @mrniko

**Comment by noseparte** [comment]
I also tried to use the following configuration, but it didn't work. It can be loaded locally, but it doesn't work when git is locally from springcloud config-repo.

![image](https://user-images.githubusercontent.com/30165939/76738627-f4a5e900-67a5-11ea-89ea-5d91fecbf477.png)

**Comment by mrniko** [comment]
Could you share full stacktrace?

Seems problem that SnakeYAML thread class loader doesn't see JsonJacksonCodec class

**Comment by mrniko** [comment]
Also try to define it like this

`codec: !!org.redisson.codec.JsonJacksonCodec {}`

**Comment by noseparte** [comment]
[stackoverflow.log](https://github.com/redisson/redisson/files/4337370/stackoverflow.log)
the log by use
`codec: !!org.redisson.codec.JsonJacksonCodec {}`

**Comment by noseparte** [comment]
![image](https://user-images.githubusercontent.com/30165939/76744015-89ace000-67ae-11ea-88c9-0f068c643dda.png)
User data in redis

**Comment by mrniko** [comment]
Could you share the code loading redisson.yaml config?

**Comment by noseparte** [comment]
`singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: admin
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
`

**Comment by noseparte** [comment]
`
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: admin
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
`

**Comment by noseparte** [comment]
![image](https://user-images.githubusercontent.com/30165939/76744625-7fd7ac80-67af-11ea-9dad-0b776be72fd7.png)

**Comment by mrniko** [comment]
I mean how does spring load redisson.yaml file?

**Comment by noseparte** [comment]
oh! sorry.   Through annotation @ImportAutoConfiguration(RedissonAutoConfiguration.class)
![image](https://user-images.githubusercontent.com/30165939/76744912-f1aff600-67af-11ea-99d4-f8498719b112.png)

**Comment by mrniko** [comment]
did you specify `spring.redis.redisson.config=redisson.yaml` setting?

**Comment by noseparte** [comment]
Application-dev.yml is separate from redisson-dev.yml and cannot specify which redisson config.
I think these are two questions.One is the yaml file loading prompt "codec:!< org redisson. Codec. JsonJacksonCodec > {} syntax errors, "the local can be loaded but by springcloud config to dynamically cannot obtain.The second problem is that I use "codec:
Class: "org. Redisson. Codec. JsonJacksonCodec" "encoding does not take effect when this way

**Comment by mrniko** [comment]
Unable to reproduce the issue:

```java
@SpringBootApplication
@EnableCaching
@ImportAutoConfiguration(RedissonAutoConfiguration.class)
public class RedissonApplication {

    public static void main(String[] args) {
        SpringApplication.run(RedissonApplication.class, args);
    }
    
}
```

application.yml
```yaml
spring:
  redis:
    redisson:
      config: classpath:redisson.yaml
```

redisson.yaml
```yaml
singleServerConfig:
  address: "redis://127.0.0.1:6379"
codec: !<org.redisson.codec.JsonJacksonCodec> {}
```

**Comment by mrniko** [comment]
using Spring boot 2.2.0

**Comment by noseparte** [comment]
Note: my premise is to use springcloud config to get the configuration file redisson.yaml on git. Can I use classpath this way?Not a local call to load the file in the resources directory

**Comment by mrniko** [comment]
springcloud config doesn't support classpath prefix

**Comment by fakeYanss** [comment]
May be the version of redisson cause it.
The all property in you yaml file should match with the fields in `org.redisson.config`.
And I find `pingTimeout` was removed in hignest version of redisson.

**Comment by mrniko** [comment]
@fakeYanss 

It's replaced with `pingConnectionInterval` setting

**Comment by contentfree** [comment]
> Also try to define it like this
> 
> `codec: !!org.redisson.codec.JsonJacksonCodec {}`

Can you explain this notation?
