### ISSUE TITLE
LEAK: HashedWheelTimer.release() was not called before it's garbage-collected.

### ISSUE THREAD

**Issue by yugandharadusumilli** [redisson/redisson#2636]
We are getting the below error when trying to bring up the app with has a gradle dependency compile("org.redisson:redisson:3.12.1") 

2019-11-08 11:41:23.476+0000 [] [] [main] ERROR io.netty.util.ResourceLeakDetector - reportTracedLeak : LEAK: HashedWheelTimer.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:284)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:217)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:196)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:178)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:162)
	io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:169)
	io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:532)
	io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:233)
	io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:98)
	io.lettuce.core.RedisClient.<init>(RedisClient.java:87)
	io.lettuce.core.RedisClient.create(RedisClient.java:124)
	org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.lambda$createClient$7(LettuceConnectionFactory.java:977)
	java.base/java.util.Optional.orElseGet(Unknown Source)
	org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.createClient(LettuceConnectionFactory.java:977)
	org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.afterPropertiesSet(LettuceConnectionFactory.java:273)
	org.springframework.cloud.service.keyval.RedisConnectionFactoryCreator.create(RedisConnectionFactoryCreator.java:88)
	org.springframework.cloud.service.keyval.RedisConnectionFactoryCreator.create(RedisConnectionFactoryCreator.java:31)
	org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:288)
	org.springframework.cloud.Cloud.getSingletonServiceConnector(Cloud.java:202)
	org.springframework.cloud.config.java.CloudServiceConnectionFactory.redisConnectionFactory(CloudServiceConnectionFactory.java:260)
	org.springframework.cloud.config.java.CloudServiceConnectionFactory.redisConnectionFactory(CloudServiceConnectionFactory.java:242)
	

Though we are seeing this error,we are not getting blocked and our app is able to run successfully without any issue.

I need to identify whether this is a false message or this has any impact on our application.
Could you please check and identify this.

**Comment by mrniko** [comment]
I'm sorry, but it's related to a different project:

io.netty.util.HashedWheelTimer.(HashedWheelTimer.java:284)
io.netty.util.HashedWheelTimer.(HashedWheelTimer.java:217)
io.netty.util.HashedWheelTimer.(HashedWheelTimer.java:196)
io.netty.util.HashedWheelTimer.(HashedWheelTimer.java:178)
io.netty.util.HashedWheelTimer.(HashedWheelTimer.java:162)
**io.lettuce**.core.resource.DefaultClientResources.(DefaultClientResources.java:169)

**Comment by mrniko** [comment]
Try to exclude `io.lettuce` package from classpath 

https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/keyval/RedisConnectionFactoryCreator.java#L62

**Comment by yugandharadusumilli** [comment]
can you please explain wh i need to exclude io.lettuce

**Comment by mrniko** [comment]
please have a look at source code link I posted

**Comment by yugandharadusumilli** [comment]
as we are using a lettuce redis client not sure how it works if we exclude lettuce itself

**Comment by mrniko** [comment]
I already fixed that message for redisson https://github.com/pepelu0/redisson/commit/12d94a0df44f5098ec069d39defb428b24a08ae1

But can't do anything for lettuce

**Comment by yugandharadusumilli** [comment]
is that a false a message then?
