### ISSUE TITLE
question with RBlockingQueue.poll(timeout, TimeUnit.SECONDS)

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#2639]
Redisson version: 3.12.1
Java version: 1.8

Hi, in one of our environments BLPOP doesn't pop the elements, though there are elements in the queue when queried via redis-cli with LRANGE command. The issue happens only in one of the environments, are there any known issues with `RBlockingQueue.poll(timeout, TimeUnit.SECONDS)` where the timeout is `zero`? This method is called from a while(true) loop, the functionality works for 3-4 hours and then stops popping the elements. As I couldn't reproduce locally I couldn't attach the reproducible code.  

```
          RBlockingQueue<String> queue = redissonClient.getBlockingQueue(queueName);
		try {
                         // some calling methods pass timeout as zero.
			return queue.poll(timeout, TimeUnit.SECONDS); 
		} catch (InterruptedException e) {
			LOG.error(ex.message);
		}
```

**Comment by mrniko** [comment]
Hi,

There are no known issues with BLPOP command. Which Redis vendor do you use?

**Comment by rgampa** [comment]
HI @mrniko It's open source installation. All environments have same infrastructure. My question was if we use `0` timeout will it cause any issue? I will be changing it to `queue.poll()` as there is no point in using BLOP with `0` timeout. But I am curious are there are any known issues?

**Comment by mrniko** [comment]
> My question was if we use 0 timeout will it cause any issue?

No. It's good idea to try to change it with limited timeout. Please let me know if it fix the issue.

**Comment by tigernitw** [comment]
@rgampa : Even I am facing same issue in production. Can you please suggest if there is anything you have done to fix it.

**Comment by rgampa** [comment]
Hi @tigernitw , as far as I remember we have replaced the `0` (infinite) timeout with max 5 sec timeout that time. Currently we don't see this behavior in our environments. Over the time we upgraded Redisson version in our code, currently it's at `3.19.2`.
