### ISSUE TITLE
tomcat 7.0.100 can not load META-INF/services/javax.servlet.ServletContainerInitializer file of webApp jars

### ISSUE THREAD

**Issue by z00407087** [redisson/redisson#2641]
My web app can not be loaded by tomcat when upgrading to version-7.0.100. My start class is loaded by defining in 'META-INF/services/javax.servlet.ServletContainerInitializer'. In tomcat-7.0.100, WebappServiceLoader.java has a bug:
    public List<T> load(Class<T> serviceType) throws IOException {
        String configFile = "META-INF/services/" + serviceType.getName();
        ....
        if (orderedLibs == null) {
            if (loader instanceof URLClassLoader) {               
                resources = ((URLClassLoader)loader).findResources("/" + configFile);
                while(resources.hasMoreElements()) {
                    URL resource = (URL)resources.nextElement();
                    this.parseConfigFile(applicationServicesFound, resource);
                }
            }
7.0.100
resources = ((URLClassLoader)loader).findResources("/" + configFile);
pre-version
resources = loader.getResources(configFile);
why here add a "/" in version-7.0.100, which lead to ServletContainerInitializer can not be load.

**Comment by mrniko** [comment]
How is this related to this project?
