### ISSUE TITLE
RMapCache adds some special characters before

### ISSUE THREAD

**Issue by Slava96** [redisson/redisson#2642]
Redisson version - 3.12.3
Java version - 11

```
final TypedJsonJacksonCodec codec = new TypedJsonJacksonCodec(String.class, JSONObject.class, new ObjectMapper());
JSONObject value = new JSONObject(new HashMap<String, String>() {{
    put("a", "b");
}});
RMapCache<Object, JSONObject> myMapCache = redissonClient.getMapCache("myMapCache", codec);
myMapCache.put("key", value, 14, TimeUnit.DAYS);
RLocalCachedMap<Object, JSONObject> myLocalCachedMap = redissonClient.getLocalCachedMap("myLocalCachedMap", codec, LocalCachedMapOptions.defaults());
myLocalCachedMap.put("key", value);
```

With use of codec:
RMapCache HGETALL returns 
1) "\"key\""
2) "\x00\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00{\"a\":\"b\"}" 
from redis-cli.

RLocalCachedMap returns 
1) "\"key\""
2) "{\"a\":\"b\"}"
from redis-cli.

My question - what is the special characters in RMapCache.
And how can i read json without this characters by call HGET on raw Redis?

**Comment by mrniko** [comment]
it's maxIdleTime and value

**Comment by Slava96** [comment]
I understand - that it's not limited length - so we cannot simply parse this value.
Is i understand correct?

**Comment by mrniko** [comment]
maxIdletime and length values have fixed size

**Comment by asarkar** [comment]
@Slava96 I'm seeing the same behavior. What did you end up doing?

**Comment by jagansankara** [comment]
I'm also facing same issue but for different scenario. Key which inserted through Redission library have additional characters and works fine if I read it again through Redission but not with other platform like Python library or redis-cli.

Our requirement is to read/write same key from different application (here it is SpringBoot & Django).

**Comment by j4velin** [comment]
We ended up dropping the first 16 characters, but that really feels like an unnecessary hack. We will switch to a more predictable redis library soon...
