### ISSUE TITLE
Redisson Configuration For AWS ElastiCache 

### ISSUE THREAD

**Issue by dania-ru** [redisson/redisson#2644]
Hi, we are using redisson with elasticache (Cluster Mode Disabled). We have 3 nodes. There are the primary endpoint, the reader endpoint and 3 node endpoints (https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Endpoints.html). Which URLs to use for ReplicatedServersConfig.addNodeAddress? Should we add all the nodes URLs, without the primary and the reader endpoints?
Thanks

**Comment by mrniko** [comment]
Hi,

You should add all nodes.

**Comment by dania-ru** [comment]
Hi, thanks for quick response. 
Just to clarify I should add only nodes url? 

Primary url is a dns name for master and reader url is a dns name for all  read replicas.

**Comment by mrniko** [comment]
You need to add master endpoint and all replica endpoints.

**Comment by dania-ru** [comment]
Thank you
