### ISSUE TITLE
RExecutorService - Some tasks won't get executed 

### ISSUE THREAD

**Issue by coufalja** [redisson/redisson#2645]
The setup:
Service A -> Producing tasks to executor service
Service B -> Consuming tasks (RedissonNode)
ServiceA static, ServiceB is autoscaled in N replicas

**Expected behaviour**
All tasks put into executor service will get executed, tasks counter is reporting correct value.

**Actual behaviour**
Some tasks won't get executed, the task counter is reporting *negative* numbers.

**Steps to reproduce or test case**
I was trying hard to get a reproducer on this but I am unable to simulate it deterministically. But I tracked it down to shutdown of the redisson node.
The best that could be done for reproducing the issue is to run n replicas of RedissonNode(s) schedule hundreds of tasks to the executor service and then shut down and startup some of these RedissonNodes. If for example the task print some random id or stores it somewhere you will find out that some ids are missing even though the queue is empty (the tasks HASH is empty) and counter is having a negative value of exact number of missing tasks.

My hypothesis is that the issue is in org.redisson.executor.TasksRunnerService#executeCallable
if the RedissonInstance is in shutdown state the finally clause will still decrement the counter but as the exception is not thrown the task is not re-queued. But it is a wild guess.

**Redis version**
Single node non-clustered v5.0.7

**Redisson version**
3.12.3

**Comment by mrniko** [comment]
Done
