### ISSUE TITLE
decodeInExecutor=true isn’t compatible with certain replays

### ISSUE THREAD

**Issue by eager** [redisson/redisson#2646]
**Expected behavior**

Configuring `decodeInExecutor=true` works for all replays

**Actual behavior**

We receive periodic `IndexOutOfBoundsException`s during decoding, because of Netty’s implementation of `ReplayingDecoderByteBuf#copy`.

**Steps to reproduce or test case**

We are using  `RedissonSessionRepository` (Spring Session), and can reproduce by running two application instances. We use `ab` to creating many sessions on one of them. The other instance receives many messages—created, expired, etc.

I don’t have a code test case, but the issue is readily apparent in the debugger. When [the `ByteBuf` is copied for the executor](https://github.com/redisson/redisson/blob/3231b26cddcf42c00d7bcfbb0694fbe079a7685d/redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java#L120), the [copy is of the underlying buffer](https://github.com/netty/netty/blob/99aca1879fcd69e4beecd100dcff5bec61eb2b84/codec/src/main/java/io/netty/handler/codec/ReplayingDecoderByteBuf.java#L155)—the special behavior of `ReplayingDecoderByteBuf` is lost. This means that incomplete messages cause `IndexOutOfBounds` exceptions, rather than having the message rewound and decoding retried once there is more data in the buffer.

**Redis version**

4.x

**Redisson version**

3.12.3

**Redisson configuration**

- Redis cluster
- Fst Codec
- `decodeInExecutor=true`

I’m not sure if this should be considered a bug in Netty, but I’ve filed netty/netty#10122.

**Comment by mrniko** [comment]
Did you try to increase netty threads as alternative of `decodeInExecutor=true` setting?

**Comment by eager** [comment]
@mrniko that’s definitely what we will be doing. Do you think `decodeInExecutor` should be documented as having potential issues, like this one?

**Comment by mrniko** [comment]
I introduced this setting before I came to the solution with netty threads.

Do you encounter this issue only with pubsub?

**Comment by eager** [comment]
> Do you encounter this issue only with pubsub?

I believe so. We’ve been using Redisson for a long time as a client, but only recently started testing `RedissonSessionRepository`, which uses pubsub behind the scenes.

**Comment by eager** [comment]
@mrniko the Netty team’s response to https://github.com/netty/netty/issues/10122 was that copying and decoding in a separate thread is an invalid use for `ReplayingDecoder`. Since we can’t know whether or not a buffer is a complete message, `decodeInExecutor` seems like a feature to deprecate, and only support setting netty threads.

**Comment by mrniko** [comment]
I agree. Will deprecate it
