### ISSUE TITLE
Distlock Mutual exclusion problem ？

### ISSUE THREAD

**Issue by lengrongfu** [redisson/redisson#2648]
1、assume a Redis cluster has a 5 master node; A , B, C ,D ,E representative node name.
2、Client A  lock to A,B,C three node. lock success.
3、This time B，C Node happen Network partition。
4、Client B lock to D,E tow node, lock success，Satisfy N/2 + 1 ，because have A，D，E three node。
5、Violation of mutual exclusion。

**Comment by mrniko** [comment]
I can only suggest to use RedissonMultiLock.
