### ISSUE TITLE
Is it possible to restrict session loading/saving to specific requests?

### ISSUE THREAD

**Issue by jonyt** [redisson/redisson#2650]
I'm working on a legacy project and trying to integrate Redisson Tomcat. The project uses the session object to store lots of data, and doesn't use setAttribute to do it. Because of this I'm forced to use the `AFTER_REQUEST` update mode. Since every page needs multiple calls to the server to render the whole process is very slow as Redisson will load and then save the session on every request. 

Is it possible to restrict session loading/saving to specific requests? I couldn't see a mechanism which enables it so I thought of injecting a valve before the UpdateValve which will skip it in specific cases. Is there a better way?

**Comment by mrniko** [comment]
> Is it possible to restrict session loading/saving to specific requests?

I'm afraid no. Custom Value object is the only way I see.

**Comment by jonyt** [comment]
I don't understand. What do you mean?

**Comment by mrniko** [comment]
Sorry, I meant Custom Valve object. Inside it you need to set note `org.redisson.tomcat.UpdateValve#ALREADY_FILTERED_NOTE` = true so next UpdateValue will skip it's logic.

**Comment by jonyt** [comment]
But UpdateValve doesn't have such a field. Can you explain? What I thought of doing was restrict UpdateValve to a whitelist of requests by injecting a valve before it in the chain. But your idea sounds more interesting, so I'd be grateful if you could elaborate.

**Comment by mrniko** [comment]
Here it is https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/UpdateValve.java#L35

**Comment by jonyt** [comment]
Ah, I'm working with the Tomcat 9 version so that's not possible for me.

**Comment by mrniko** [comment]
It's the same for Tomcat 9

https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/UpdateValve.java#L35

**Comment by jonyt** [comment]
Sorry, I was being stupid. I'm working on redisson-3.10.7 which doesn't have that feature. I'll try to upgrade. Thanks a lot for your help! Great project 😀

**Comment by jonyt** [comment]
So I see that even though I took the UpdateValve out of the pipeline there are still a lot of calls to Redis because of how Redisson accesses the session. Is there a way I can have Redisson access only the session data in Tomcat's memory for certain requests, instead of going to Redis?

**Comment by mrniko** [comment]
I'm afraid no. How about to wrap Redisson Manager?

**Comment by jonyt** [comment]
I would need to create a wrapper for RedissonSession which doesn't go to Redis on `access()` et al. on specific requests. But, since session doesn't have knowledge of the current request I'm stuck.
