### ISSUE TITLE
Handle Redis Cluster memory

### ISSUE THREAD

**Issue by dotrungduchd** [redisson/redisson#266]
Hi @mrniko,

I want to know what Redisson can do with Redis Cluster:
-check Redis Cluster memory
-handle exception when Redis Cluster exceed memory
Thanks & regard

**Comment by mrniko** [comment]
Task added - implement separate exception for OOM https://github.com/mrniko/redisson/issues/413

**Comment by mrniko** [comment]
Getting memory statistics will be implemented in https://github.com/redisson/redisson/issues/3329

**Comment by mrniko** [comment]
Done
