### ISSUE TITLE
DB count not decreased as expected.

### ISSUE THREAD

**Issue by nitinparetha** [redisson/redisson#2666]
Does mybatis-redisson keep on sending query to DB in background? I changed in project from local mybatis cache in distributed env. to redis cache using mybatis but load on DB is still same. I expected load on DB lesser after using redisson-mybatis.

**Comment by mrniko** [comment]
It depends on cache settings you applied to your data model. https://mybatis.org/mybatis-3/sqlmap-xml.html#cache
