### ISSUE TITLE
about reading from replicas

### ISSUE THREAD

**Issue by thesreyas** [redisson/redisson#2667]
**Configuring only few maps for strong consistency:**

Can i configure that few maps are read from the replicas and for others where i need strong consistency are read from the master only?
In this way i get strong consistency and also performance for other maps.

If not, can i have  to have two redisson instances with different configurations (one with read from replicas and other w/o )  for doing this?

**Preventing data loss for map.**
1. have a copy of map and write to it every time when the primary map changes
2. name the map in such way that slot# is on different redis master 
3. when there is a node crash, start using other map as primary map
( we are planning to use elastic cache ,hopefully there is a way to get notified which master failed)

**Comment by mrniko** [comment]
> Can i configure that few maps are read from the replicas and for others where i need strong consistency are read from the master only?

You can do it if you create two Redisson instances which share the same `Config.eventLoopGroup` and `Config.executor` objects.

> when there is a node crash, start using other map as primary map
( we are planning to use elastic cache ,hopefully there is a way to get notified which master failed)

You can get the same with the slave nodes.

**Comment by thesreyas** [comment]
Thanks @mrniko for pointing about RBatch.
Java Doc talks about leveraging it for pipelining multiple requests.

In our usecase, at a time, i only may have single map operation, say map.put().
So to leverage this I need to below 4 operations every time.
Is that correct?

What will be extra cost compared to map.put() w/o RBatch?
Is it simply cost of map.put() and wait() or more.

1. create RBatch
 2. do getMap 
3. do map.put()
 4.batch.execute(()

**Comment by mrniko** [comment]
> So to leverage this I need to below 4 operations every time.
Is that correct?

use BatchOptions.executionMode = IN_MEMORY_ATOMIC to execute them as a single command

**Comment by thesreyas** [comment]
Thanks for your quick response @mrniko 

I was looking to ensure that each map operation is synchronously written to replica as well.
So basically using wait command after every write.

RBatch looks great, it gives provision to sync with replicas.
Question is can if i leverage RBatch like this (Approach 1) or i have to do as in Approach-2
In case of Approach 2, i am doing creation, gettingMap every time.  How much overhead does it had?

`public class MyRedissonMap {
RBatch mBatch = null;
RMap mMap = null;

MyRedissonMap(Redisson redisson, String mapName){
 
 BatchOptions options = BatchOptions.defaults()
 .executionMode(ExecutionMode.IN_MEMORY_ATOMIC)
 .syncSlaves(2, 1, TimeUnit.SECONDS);
 
 mBatch = redisson.createBatch(options);
 mMap = batch.getMap(mapName);

}

void put(String aKey , String aValue){
   mMap.put(aKey,aValue);
   BatchResult result = batch.execute();
   assert result.getSyncedSlaves() ==2;
 }

}
`
**Approach 2**

`public class MyRedissonMap2 {

Redisson redisson = null;
String mapName = null;

MyRedissonMap(Redisson aRedisson, String aMapName){
 redisson = aRedisson;
 mapName=aMapName;
}

void put(String aKey , String aValue){
	BatchOptions options = BatchOptions.defaults()
	 .executionMode(ExecutionMode.IN_MEMORY_ATOMIC)
	 .syncSlaves(2, 1, TimeUnit.SECONDS);
	RBatch batch = redisson.createBatch(options);
	mMap = batch.getMap(mapName);
	mMap.put(aKey,aValue);
	BatchResult result = batch.execute();
	assert result.getSyncedSlaves() ==2;
 }
 
}`

**Comment by mrniko** [comment]
If you use only single command in batch then `ExecutionMode.IN_MEMORY` could be used instead. Approach 2 looks fine.
