### ISSUE TITLE
use redisson make jvm old generation overflow

### ISSUE THREAD

**Issue by zhangchiisgy** [redisson/redisson#2668]
**Expected behavior**
redisson use without problem
**Actual behavior**
old generation overflow, stack exception is 
`"redisson-netty-160-64" #21377 prio=5 os_prio=0 tid=0x00007fc192b01000 nid=0x490b6 runnable [0x00007fbd44645000]`
**Steps to reproduce or test case**
set redisson config connectionMinimumIdleSize =256 connectionPoolSize =512
**Redis version**
4.0
**Redisson version**
3.10.7
**Redisson configuration**
{"singleServerConfig":{"idleConnectionTimeout":10000,"pingTimeout":1000,"connectTimeout":10000,"timeout":6000,"retryAttempts":3,"retryInterval":1500,"reconnectionTimeout":3000,"failedAttempts":3,"password":"","subscriptionsPerConnection":5,"clientName":null,"address":"","subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"connectionMinimumIdleSize":256,"connectionPoolSize":512,"database":0},"threads":0,"nettyThreads":0,"codec":{"class":"org.redisson.codec.JsonJacksonCodec"},"transportMode":"NIO"}

**Comment by mrniko** [comment]
Could you povide more details about the problem and share full stacktrace?

**Comment by zhangchiisgy** [comment]
when i set redisson config param connectionMinimumIdleSize = 256 connectionPoolSize = 512, the old generation stackoverflow,the old generation memory pic is behind
![image](https://user-images.githubusercontent.com/12904624/78315192-f2f26880-758e-11ea-8ea4-801a0d7ed264.png)
i change  connectionMinimumIdleSize = 100 connectionPoolSize = 200 at 2020-04-02 15:00，you can see the old generation is stable。
the stacktrace :
[17703.log](https://github.com/redisson/redisson/files/4424608/17703.log)

**Comment by mrniko** [comment]
Could you share memory dump? Also try to use another codec, since default FstCodec uses caching which may be non-effective in some cases..

**Comment by zhangchiisgy** [comment]
the memory dump has 6g, i can not upload because i am in china and it is so big,i try another codec,when i have a conclusion ，i will tell you.

**Comment by johnou** [comment]
@zhangchiisgy gzip -9?

**Comment by zhangchiisgy** [comment]
> @zhangchiisgy gzip -9?
i zip this to 500 mb，but github support low than 10 mb, what website support up 500 mb file upload

**Comment by mrniko** [comment]
@zhangchiisgy 

Try to use this fileshare hosting https://anonfile.com/

**Comment by zhangchiisgy** [comment]
https://anonfile.com/HdT1a0ocob/service.dump_zip
https://anonfile.com/P9cbbfo0o3/service.dump_z01
https://anonfile.com/rdd0b1o9od/service.dump_z02
https://anonfile.com/Lcd7b8o7o4/service.dump_z03
https://anonfile.com/P7ddbdo3o9/service.dump_z04
https://anonfile.com/Rcd1b8odoc/service.dump_z05
download all，unzip first
