### ISSUE TITLE
RRateLimiter delete

### ISSUE THREAD

**Issue by DingQianWen** [redisson/redisson#2670]
Redisson version:3.11.6

```java
RRateLimiter rateLimiter = redissonClient.getRateLimiter("key");
rateLimiter.trySetRate(RateType.OVERALL, 3, 10, RateIntervalUnit.MINUTES);
//Delete the invalid
rateLimiter.delete();
```

Delete the invalid

**Comment by mrniko** [comment]
unable to reproduce. Could you share exception stacktrace?

**Comment by DingQianWen** [comment]
> unable to reproduce. Could you share exception stacktrace?

No exception information is thrown

**Comment by mrniko** [comment]
Sorry, I don't follow what is the invalid in this case?

**Comment by DingQianWen** [comment]
> Sorry, I don't follow what is invalid in this case?

Delete is performed, but the key and value still exist in redis

**Comment by DingQianWen** [comment]
> Sorry, I don't follow what is invalid in this case?

I'm sorry, I did it wrong

**Comment by mrniko** [comment]
Fixed.
