### ISSUE TITLE
Sentinelconnectionmanageris not correctly in IPv6 dual stack environments

### ISSUE THREAD

**Issue by rexzhong79626** [redisson/redisson#2671]
**Note:this ticket is different from ticket2471 and ticket2303**
I found the following bugs in the SentinelConnectionManager class，my test environment is as follows，three sentinels(node10, node14, noe15)，one master(node14)， one slave(node15), the network environment of each node is IPv6 dual stack, and the IP of each node is as follows：
_[root@clab508node14 ~]# hostname -i
2a00:8a00:4000:20c::8b:e74 10.32.222.115
[root@clab508node15 ~]# hostname -i
2a00:8a00:4000:20c::8b:e75 10.32.222.116
[root@clab508node10 ~]# hostname -i
2a00:8a00:4000:20c::8b:e70 10.32.222.111_

The application program runs in node14 and node15 respectively. The following logs are captured in node14 and printed frequently in the log:
sentinel: redis://2a00:8a00:4000:20c::8b:e74:26379 has down
sentinel: redis://2a00:8a00:4000:20c::8b:e70:26379 has down
sentinel: redis://2a00:8a00:4000:20c:**0:0**:8b:e74:26379 has down
sentinel: redis://2a00:8a00:4000:20c:**0:0**:8b:e70:26379 has down
sentinel: redis://10.32.222.111:26379 has down
sentinel: redis://2a00:8a00:4000:20c::8b:e75:26379 has down
sentinel: redis://2a00:8a00:4000:20c:**0:0**:8b:e75:26379 has down

When the application is initialized, we will get all sentinels in the constructor of SentinelConnectionManager by synchronously call (140 lines)：connection.sync(StringCodec.INSTANCE, RedisCommands.SENTINEL_SENTINELS, cfg.getMasterName())，debug log as below：
ip: 2a00:8a00:4000:20c::8b:e74 
ip: 2a00:8a00:4000:20c::8b:e75 
**client currentAddr: redis://10.32.222.111:26379        // Note that the log is printed through the code: client. Getaddr(). Getaddress(). Gethostaddress(), which is an IPv4 address**
sentinel: redis://2a00:8a00:4000:20c::8b:e74:26379 added
sentinel: redis://10.32.222.111:26379 added
sentinel: redis://2a00:8a00:4000:20c::8b:e75:26379 added

In the function scheduleChangeCheck, we will asynchronously call(446 lines)：sentinelsFuture = connection.async(StringCodec.INSTANCE, RedisCommands.SENTINEL_SENTINELS, cfg.getMasterName()). Get the sentinel of the current time point, and the debug print is as follows:
ip: 2a00:8a00:4000:20c::8b:e75
ip: 2a00:8a00:4000:20c::8b:e70
**client currentAddr: redis://2a00:8a00:4000:20c:0:0:8b:e74:26379           // This log is based on the code: connection. Getredisclient(). Getaddr(). Getaddress(). Gethostaddress(), which is IPv6 address**

Through the above log, you can see that for IPv6 address，in SentinelConnectionManager, some codes get IPv6 addresses without 0(2a00:8a00:4000:20c::8b:e74), and some code get IPv6 addresses with 0(2a00:8a00:4000:20c:0:0:8b:e74)，and some of the code gets the IPv4 address, this will cause the IP address string is not equal in the updateSentinels function**("2a00:8a00:4000:20c::8b:e74" != "2a00:8a00:4000:20c:0:0:8b:e74") ("10.32.222.111" != "2a00:8a00:4000:20c::8b:e70") ("10.32.222.111" != "2a00:8a00:4000:20c:0:0:8b:e70")**, and then call the two functions disconnectNode and shutdownAsync in error. The code is as follows：
for (RedisURI uri : currentUris) {
            RedisClient sentinel = SentinelConnectionManager.this.sentinels.remove(uri);
            if (sentinel != null) {
                disconnectNode(sentinel);
                sentinel.shutdownAsync();
                log.warn("sentinel: {} has down", uri);
            }
        }

Redisson version
org.redisson.Version | Redisson 3.12.2

**Comment by rexzhong79626** [comment]
The above problem occurs in sentinel. I think there should be similar problems in master and slave。

**Comment by mrniko** [comment]
which ip addresses you defined in redisson configuration?

**Comment by mrniko** [comment]
>  SentinelConnectionManager, some codes get IPv6 addresses without 0(2a00:8a00:4000:20c::8b:e74), and some code get IPv6 addresses with 0(2a00:8a00:4000:20c:0:0:8b:e74)

That depends on network settings defined in Redis. Redisson doesn't make any modification to ip addresses.

**Comment by rexzhong79626** [comment]
I have attached the following files:


IPv6 address with or without 0 is the same result in all configuration files with extension "conf":
bind 2a00:8a00:4000:20c::8b:e70 10.32.222.111 127.0.0.1
bind 2a00:8a00:4000:20c::8b:e74 10.32.222.115 127.0.0.1

The file "redisson_config.yaml" is the configuration file of redisson. When the application starts, it will create a redisson client based on this configuration.

In dual stack environment, since there are two IP addresses, I suggest using hostname or other unified IPv6 address format

![redis_node14 conf](https://user-images.githubusercontent.com/33743644/78527312-217e7680-780f-11ea-8d6b-ac1f82da4285.jpg)
![redis_node15 conf](https://user-images.githubusercontent.com/33743644/78527318-23483a00-780f-11ea-8056-d700aa77f58d.jpg)
![redisson_config yaml](https://user-images.githubusercontent.com/33743644/78527321-23e0d080-780f-11ea-8241-9d201a0ce991.jpg)
![sentinel_node10 conf](https://user-images.githubusercontent.com/33743644/78527322-24796700-780f-11ea-8559-3f982400d080.jpg)
![sentinel_node14 conf](https://user-images.githubusercontent.com/33743644/78527325-2511fd80-780f-11ea-811d-facf1e7f2c1e.jpg)
![sentinel_node15 conf](https://user-images.githubusercontent.com/33743644/78527329-25aa9400-780f-11ea-85f0-4935fdebedf8.jpg)

**Comment by mrniko** [comment]
> SentinelConnectionManager, some codes get IPv6 addresses without 0(2a00:8a00:4000:20c::8b:e74), and some code get IPv6 addresses with 0(2a00:8a00:4000:20c:0:0:8b:e74)

I found the cause:

        String ip = "2a00:8a00:4000:20c::8b:e70";
        byte[] add = NetUtil.createByteArrayFromIpAddressString(ip);
        System.out.println("addr: " + Arrays.toString(add));
        InetAddress a = InetAddress.getByAddress(ip, add);

        // returns 2a00:8a00:4000:20c:0:0:8b:e75
        System.out.println(a.getHostAddress());
        // returns 2a00:8a00:4000:20c::8b:e70
        System.out.println(a.getHostName());

**Comment by mrniko** [comment]
I have attached version containing fix for incorrect IPV6 address. Could you try it?

[redisson-3.12.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4436135/redisson-3.12.5-SNAPSHOT.jar.zip)

**Comment by rexzhong79626** [comment]
Ok, I will test it.

**Comment by rexzhong79626** [comment]
I have downloaded a new code, checked and included your just submitted (redisclient.java), added debug log in "SentinelConnectionManager", and found that there are still problems. I attached the SentinelConnectionManager file which contains the debug log and attached the test log. I have changed SentinelServersConfig.scanInterval from 1 second to 10 seconds
[SentinelConnectionManager.zip](https://github.com/redisson/redisson/files/4437142/SentinelConnectionManager.zip)
[knife7.zip](https://github.com/redisson/redisson/files/4437165/knife7.zip)

**Comment by rexzhong79626** [comment]
From the log(knife7.zip), we can see that when the redisson is initialized, there are also IPv4 addresses. Can we use all IPv4 addresses uniformly or all IPv6 addresses.
org.redisson.connection.SentinelConnectionManager | client currentAddr: redis://10.32.222.111:26379

**Comment by mrniko** [comment]
could you bound redis nodes to ipv6 only? There are no way to determine which ip to use v4 or v6 if host bounded to multiple addresses

**Comment by rexzhong79626** [comment]
I don't think this problem will occur in the configuration of one IP, whether IPv6 or IPv4. In other non dual stack environments, i.e. only IPv4 environments, this problem doesn't exist. But our product supports dual stack scenarios, so if redisson can't fix this problem, it should be limited in the configuration. I'll test configuring a single IPv6 tomorrow.

**Comment by mrniko** [comment]
the problem is that `clab508node10` host mapped to ipv4 and ipv6 ip addresss. Host name resolver doesn't have any priority over ips and picks first returned by your dns.

**Comment by rexzhong79626** [comment]
After testing, it seems that the changes have no effect(https://github.com/redisson/redisson/commit/65e4d2c7af2cbd35147ae111ea5a8007e6c028fe)，I have changed the IP address to IPv6 address without 0 in all configuration files，The redisson configuration file is also changed from the original hostname to an IPv6 address without 0，In the test, I found that the address returned by the following statement is still IPv6 address with 0：

SentinelConnectionManager.updateState()
{
    ....................
	RFuture<List<Map<String, String>>> sentinelsFuture = connection.async(StringCodec.INSTANCE, RedisCommands.SENTINEL_SENTINELS, cfg.getMasterName());
    ...................
    Set<RedisURI> newUris = list.stream().filter(m -> {
        String flags = m.get("flags");
        if (!m.isEmpty() && !flags.contains("disconnected") && !flags.contains("s_down")) {
            return true;
        }
        return false;
    }).map(m -> {
        String ip = m.get("ip");
        log.info("ip: {}", ip);  //  ip: 2a00:8a00:4000:20c::8b:e70     ip: 2a00:8a00:4000:20c::8b:e75
        String port = m.get("port");
        return toURI(ip, port);
    }).collect(Collectors.toSet());
    
	InetSocketAddress addr = connection.getRedisClient().getAddr();
    RedisURI currentAddr = toURI(addr.getAddress().getHostAddress(), "" + addr.getPort());
    log.info("client currentAddr: {}", currentAddr);   //  client currentAddr: redis://2a00:8a00:4000:20c:0:0:8b:e74:26379
    ..................
}
[modified_config.zip](https://github.com/redisson/redisson/files/4442837/modified_config.zip)

**Comment by mrniko** [comment]
Could you make sure, that you still use jar I attached before?

**Comment by rexzhong79626** [comment]
I did three tests based on the redisson configuration of IPv6 address without 0:
1. The jar package you provided is compiled based on the new version of redisson. It can't run normally when I deploy it to our environment. Our environment and dependent packages are all based on version 3.12.2. Then I found that you only modified "RedisClient.java", so I made the same changes to the local 3.12.2 code. The result is posted above.
2. After you submit the changes, I downloaded the latest version of redisson code, this latest version code contains the modifications to the "RedisClient.java". I compiled it locally, and then the result of running is the above posted knife7.zip.
3. When I change the code from "RedisURI currentAddr = toURI(addr.getAddress().**getHostAddress**()" to "RedisURI currentAddr = toURI(addr.getAddress().**getHostName**()" in the file "SentinelConnectionManager.java", log will print hostname instead of IP address

The debug logs of first two tests show that IPv6 addresses include 0. I have set all IPv6 addresses without 0 in the redisson configuration.

**Comment by rexzhong79626** [comment]
String ip1 = "2a00:8a00:4000:20c:0:0:8b:e70";
        byte[] add = NetUtil.createByteArrayFromIpAddressString(ip1);
        System.out.println("addr: " + Arrays.toString(add));
        InetAddress a = InetAddress.getByAddress(ip1, add);

        // returns 2a00:8a00:4000:20c:0:0:8b:e75
        System.out.println(a.getHostAddress());
        // returns 2a00:8a00:4000:20c:0:0:8b:e75
        System.out.println(a.getHostName());

**Comment by mrniko** [comment]
two variants of ipv6 addresses with zeros and without are correct. last one is compressed version. I need to unify and use compressed only.

**Comment by rexzhong79626** [comment]
String ipaddress = "2a00:8a00:4000:20c::8b:e70";
        RedisURI addr = new RedisURI(ipaddress);
        RedisClient client = createClient(NodeType.SENTINEL, addr, 10000, 5000, null);
        RedisConnection connection = client.connect();
        // "2a00:8a00:4000:20c:0:0:8b:e70"
        System.out.println(client.getAddr().getAddress().getHostAddress());

**Comment by mrniko** [comment]
this is because jdk InetAddress object decompress IPv6 address.

**Comment by rexzhong79626** [comment]
Yes, this is an IP address compression problem. Could you add compressed IPv6 address in "SentinelConnectionManager".

**Comment by rexzhong79626** [comment]
I use the compression method provided by you to manually compress the IP address in "SentinelConnectionManager". The result is OK, and there is no previous error log.
This method will not compress the IPv4 address, so I suggest that redisson compress the IP address in "SentinelConnectionManager".
The other thing is for sure, redisson calls the command "RedisCommands.SENTINEL_SENTINELS" or other redissom command by synchronously or asynchronously to return IPv6 addresses is in **compressed format**.

**Comment by empty117** [comment]
@eager : May i know if your fix will solve this issue?

**Comment by empty117** [comment]
@mrniko : What's your conclusion for this issue? Are you going to support dual stack environment(one host maps IPV4&IPV6)?

**Comment by mrniko** [comment]
There is nothing to do since InetAddress compress IPv6

**Comment by mrniko** [comment]
@rexzhong79626

Fixed. It now always uses compressed format for IPv6
