### ISSUE TITLE
The idle connection does not be released after redis cluster failover.

### ISSUE THREAD

**Issue by ChePeatio** [redisson/redisson#2672]
In cluster mode, when I called `cluster failover` in redis-cli, the `redis-cli client list` showed that connection number increased than `masterConnectionMinimumIdleSize/ slaveConnectionMinimumIdleSize ` while those connections idle time is larger than `idleConnectionTimeout`. I have tried both redisson verion 3.7.2 and 3.12.4, redis verion 3.2.9 and 5.0.8. **So i wander why the idle connection does not be released after redis cluster failover? It's a feature or the problem of setting or just a bug?** Thanks for reply.

Here is my setting of redisson:
![image](https://user-images.githubusercontent.com/3824661/78524967-3a375e00-7808-11ea-852a-1c1e9f693c3b.png)

Here is my redisson connection count and details, and you can see there are many connection idle time is larger than 10s, cmd is NULL, and connection number is larger than masterConnectionMinimumIdleSize, but is does not release the idle connection.
![image](https://user-images.githubusercontent.com/3824661/78525132-d3667480-7808-11ea-9114-d3764f1d182c.png)
![image](https://user-images.githubusercontent.com/3824661/78525166-f09b4300-7808-11ea-9916-5c31971c0b67.png)

**Comment by ChePeatio** [comment]
Could anyone reply the question? It's a feature or a bug?

**Comment by mrniko** [comment]
Redisson idle connections are remain for elected slave as master. Because this node remains in slave connection pool but in non-active state. These connections are preserved for case when your cluster lost all slaves. In this case master become used as slave and idle-connections become in use.

**Comment by ChePeatio** [comment]
Thanks for replying my question. 
When I do several `master failover` to test, it seems that idle connections would increase and not be released, is there a mechanism for release them?

**Comment by mrniko** [comment]
idle connections to new elected master?

**Comment by mrniko** [comment]
Fixed
