### ISSUE TITLE
Do we have support for Micronaut framework

### ISSUE THREAD

**Issue by rbalusup** [redisson/redisson#2674]

**Comment by mrniko** [comment]
Which Micronaut features you should be supported by Redisson?

**Comment by rbalusup** [comment]
I am looking for the distributed locking feature to be implemented using Micronaut. I am analyzing and comparing the features between lettuce and Redisson.

**Comment by mrniko** [comment]
All you need is to create Redisson instance and use object returned by `RedissonClient.getLock` method.

**Comment by mrniko** [comment]
Let me know if you encounter any issue with Micronaut framework

**Comment by rbalusup** [comment]
Sure, I will! Thank you very much for your time and information!!

**Comment by mrniko** [comment]
implemented in https://github.com/redisson/redisson/issues/3657
