### ISSUE TITLE
RedisNodeNotFoundException after failover in AWS Elasticache

### ISSUE THREAD

**Issue by ALSowjanya** [redisson/redisson#2678]
**Expected behavior** : Redisson should be able to talk to redis without any hiccups while failover is in progress or completed.

**Actual behavior**  : After failover is completed, redisson is throwing exceptions for a slot which is 1684. It also mentions that it is unable to connect to master in logs.
Why we think redisson is causing issue and not redis:
When the application was restarted which means the redisson was disconnected and reconnected to same configuration URL. Redisson worked fine, which tell us the issue was with redisson and not redis. We could see that all slots were covered via redis console and also via redis-cli. We were able to connect and retrieve data from 1684 slot from redis-cli. Cluster nodes and Cluster info command also shows everything is fine. 

Below is the logs of interest:

2020-04-03 05:35:07,946 [ redisson-netty-2-6] [ ] [ ] [ ] (uster.ClusterConnectionManager) ERROR - Can't connect to master: rediss://pega-XXXXXXX-0001-002.pega-XXXXXXX.XXXXX.use1.cache.amazonaws.com:6379 with slot ranges: [[0-5461]]
2020-04-03 05:35:12,698 [ Agent queue Thread] [ ] [ ] [ ] (RedisDistributedMapDiagnostics) ERROR - DMAP [default#com.pega.pegarules.session.internal.async.AgentInfo] Operation [get] failed on key [PZPROCESSREBASE:PEGA-RULEREFACTORING:UTIL-I-0351C91AF120DC92B] with message [Node for slot: 1684 hasn't been discovered yet. Check cluster slots coverage
org.redisson.client.RedisNodeNotFoundException: Node for slot: 1684 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command
at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundFuture(MasterSlaveConnectionManager.java:610) ~[redisson-3.11.3.jar:?]
at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:594) ~[redisson-3.11.3.jar:?]
at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:669) ~[redisson-3.11.3.jar:?]
at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:134) ~[redisson-3.11.3.jar:?]
at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:273) ~[redisson-3.11.3.jar:?]
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[netty-all-4.1.37.Final.jar:?]
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[netty-all-4.1.37.Final.jar:?]
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[netty-all-4.1.37.Final.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Steps to reproduce or test case**:
While the application was running. We have triggered a manual failover from AWS elasticache console. Which resulted in this exception. It is consistently reproducible.

**Redis version** :  Elasticache Redis 5.0.6, cluster mode, ssl enabled, password enabled. Redisson connects using configuration URL provided for redis.

**Redisson version**: 3.11.3

**Redisson configuration** 
clusterServersConfig:
     connectTimeout: 10000
     timeout: 3000
     retryAttempts: 3
     retryInterval: 1500
     password: XXXX
     nodeAddresses: []
     clientName: "PEGA_REDISSON_NODE"
threads: 8
nettyThreads: 16
codec: !<org.redisson.codec.LZ4Codec> {}
useScriptCache: TRUE
keepPubSubOrder: FALSE

**Comment by mrniko** [comment]
The problem is that at the moment of issue CLUSTER NODES didn't have information about node containing 1684 slot.

You could reduce `scanInterval` setting to get cluster topology update faster.

**Comment by ALSowjanya** [comment]
@mrniko the default value for scan interval is 1000 ms(1sec). Do you want us to reduce even further. We were seeing this exception for than 20 hrs. Do you still think the scan interval needs to be reduced.

**Comment by mrniko** [comment]
I assume the cause is CLUSTER NODES didn't have information about node containing 1684 slot.

**Comment by ALSowjanya** [comment]
@mrniko  from the cluster node command I could see the details of the node holding 1684 slot. I was as well able to retrieve the data from that slot from redis-cli. Please check the screenshot, node 0001-002 is now a slave. Looks like redisson was still taking it as a master.
![screenshot3](https://user-images.githubusercontent.com/6973067/78768792-0c8a1a80-79aa-11ea-959f-fa3b923ade05.PNG)

**Comment by ALSowjanya** [comment]
Cluster info and cluster slots commands 
![screenshot2_edited](https://user-images.githubusercontent.com/6973067/78769926-925a9580-79ab-11ea-8a41-243d4aef7831.png)
![Screenshot1_edited](https://user-images.githubusercontent.com/6973067/78769928-938bc280-79ab-11ea-9b0f-307640639335.png)

**Comment by mrniko** [comment]
Could you set `DEBUG` logging level for `org.redisson` package and share output during when this issue happen again?

**Comment by JLP-in-SD** [comment]
FYI: We have been seeing the same issue. I was about to file an issue, but see it has already been done.

**Comment by JLP-in-SD** [comment]
Hi @mrniko, hope you are doing well.
It appears we have the same issue as shown here.
Would you want me to also post logs in this issue, or create a new separate one?

**Comment by ALSowjanya** [comment]
> Could you set `DEBUG` logging level for `org.redisson` package and share output during when this issue happen again and share the complete log including debug info and this exception?

We are trying to get the logging, but since we these are logging heavily we were not able to collect them. We try and get the logs as soon as possible.

**Comment by mrniko** [comment]
You need to increase retryAttempts or retryInterval parameters:

https://github.com/redisson/redisson/wiki/2.-Configuration#retryattempts
https://github.com/redisson/redisson/wiki/2.-Configuration#retryinterval

**Comment by adrian-skybaker** [comment]
Could you explain why the default retry settings are not sufficient (3 x 1500ms)? Especially when the scan interval is 1000ms.

We just did a cluster upgraded in AWS from which our clients running 3.13.6 of Redisson failed to switch to the new master, even after 15-20 minutes.

It's not clear why after even one failure that the new cluster was detected.

Also, adding lengthly or a higher number retries does not seem correct, as it means when a real issue occurs, we cannot fail fast (instead customers simply see timeouts from our API as we continually retry). Even if this is the solution, it doesn't seem desireable that the cluster default settings are therefore incompatible with AWS, resulting in outages and forced restarts to recover from.

**Comment by mrniko** [comment]
> Even if this is the solution, it doesn't seem desireable that Redisson's default cluster settings are therefore incompatible with AWS

Redis setups could be different I don't want to tie config settings to a single vendor.

> Node for slot: 7166 hasn't been discovered yet

Did you check CLUSTER NODES result?

**Comment by adrian-skybaker** [comment]
>Did you check CLUSTER NODES result?

No, however a restart corrected the issue.
