### ISSUE TITLE
Unable to find master entry for local.db.xxx.xx.com/10.80.xxx.xx:6379. Multiple IP bindings for single hostname supported only in Redisson PRO!

### ISSUE THREAD

**Issue by wangqingfan** [redisson/redisson#2682]
We use load balancing to achieve high redis availability,So we're using a domain name to connect to redisson.But now this error occurs:
org.redisson.client.RedisTimeoutException: Unable to get connection! Try to increase 'nettyThreads' and/or connection pool size settingsNode source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:0:queue:1, freeConnectionsAmount=0, freeConnectionsCounter=value:0:queue:322, freezed=false, freezeReason=null, client=[addr=redis://local.db.xxx.xxx.com:6379], nodeType=MASTER, firstFail=0]]], command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, redisson_lock_sync2slave_documents_slave_p1, 30000, a9178bf5-e2c9-4a9e-be75-8a8c1481419d:231] after 0 retry attempts
2020-03-31 00:43:41,196 INFO [org.redisson.connection.DNSMonitor] - Detected DNS change. Master redis://local.db.xxx.xxxx.com:6379 has changed ip from 10.80.xxx.x1 to 10.80.xxx.x2
2020-03-31 00:43:41,196 ERROR [org.redisson.connection.DNSMonitor] - Unable to find master entry for local.db.xxx.xxx.com/10.80.xxx.x1:6379. Multiple IP bindings for single hostname supported only in Redisson PRO!

**Comment by ddekaliuk** [comment]
Had similar issue.
Please try to modify your config with `setDnsMonitoringInterval(-1)`

**Comment by mrniko** [comment]
@ddekaliuk 

Right
