### ISSUE TITLE
ClassCastException between BatchResult<?> and List<Boolean>

### ISSUE THREAD

**Issue by maystrovyy** [redisson/redisson#2685]
**Expected behavior**
No exception
**Actual behavior**
```Caused by: java.lang.ClassCastException: class org.redisson.api.BatchResult cannot be cast to class java.util.List (org.redisson.api.BatchResult is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')```
**Steps to reproduce or test case**
```
private void init() {
	var value = UUID.randomUUID().toString();
    RBloomFilter<String> bf = redissonCli.getBloomFilter(BLOOM_NAME);
    bf.tryInit(40_000_000L, 0.03);
    if (!bf.contains(value)) {
    	bf.add(value);
    }
}
```
**Redis version**
5.0.8
**Redisson version**
3.12.4
**Redisson configuration**
```
@SpringBootConfiguration
public class RedissonConfiguration {

    @Bean(destroyMethod = "shutdown")
    RedissonClient redissonClient() {
        var cfg = new Config();
        cfg.useSingleServer()
                .setTimeout(1000000)
                .setAddress("redis://127.0.0.1:36379");
        return Redisson.create(cfg);
    }

    @Bean
    RedissonConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
        return new RedissonConnectionFactory(redisson);
    }

}
```

**Comment by maystrovyy** [comment]
I found out in practice that this error is not observed on version 3.12.3.

**Comment by maystrovyy** [comment]
3.12.3: ```executorService.execute().getResponses()```
3.12.4: ```executorService.execute()```
3.12.5 (forked): ```executorService.execute().getResponses()```

**Comment by mrniko** [comment]
Fixed in upcoming version
