### ISSUE TITLE
Best method to zero-out Bloomfilter

### ISSUE THREAD

**Issue by champloo11** [redisson/redisson#2688]
I'm wondering what the best approach would be using Redisson to zero-out (remove all entries) residing in the bloomfilter entry generated by Redisson's `RedissonBloomFilter.tryInit()` and `.add` commands?

**Comment by mrniko** [comment]
You can do it with `RBloomFilter.delete` method.

**Comment by champloo11** [comment]
From my understanding `.delete()` will delete the keys associated with the object, not reset the values within it. Causing `RedissonBloomFilter.add()` and `RedissonBloomFilter.exists()` commands to fail. Meaning that there will be downtime for services that are already running that rely on that particular instances. Is that correct?

**Comment by mrniko** [comment]
`RedissonBloomFilter.add()` and `RedissonBloomFilter.exists()` commands will work.
