### ISSUE TITLE
Spring session timeout

### ISSUE THREAD

**Issue by chrisgolle** [redisson/redisson#2695]
The spring session documentation has two spring boot ways of configuring session timeout (spring.session.timeout, server.servlet.session.timeout) Redisson does not make use of either of these, instead you have to set it on the EnableRedissonHttpSession annotation which is not configurable.

**Comment by mrniko** [comment]
you need to define follow properties in spring-boot settings:

```
spring.redis.redisson.config=classpath:redisson.yaml
spring.session.store-type=redis
spring.session.timeout.seconds=900
```
and add `redisson-spring-data-22` dependency.
