### ISSUE TITLE
ClosedChannelException during RPUSH and BLPOP

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#2697]
**Expected: RPUSH should work without any exception**

**Actual: WriteRedisConnectionException/ClosedChannelException occured**

**Steps to reproduce: Intermittent error in production**

**Redis version: 2.8.19**

**Redisson version: 3.12.4**

**Redisson configuration**

```
config.useReplicatedServers()
				.setScanInterval(2000) 
				.setReadMode(MASTER)
				.setTimeout(20000) 
				.setMasterConnectionPoolSize(CacheConstants.MAX_TOTAL_CONNECTIONS)
				.setSlaveConnectionPoolSize(CacheConstants.SLAVE_MAX_TOTAL_CONNECTIONS)
				.setKeepAlive(true)
				.setPingConnectionInterval(CacheConstants.PING_INTERVAL);
```

When doing RPUSH, it's trying on the connection which is busy with BLPOP on entirely on different queue. Can you let me know how to avoid this issues. I have also added ping interval.
This issue is also happening on connections waiting with command BLPOP.

```
org.redisson.client.WriteRedisConnectionException@/kibana-highlighted-field@: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:230:queue:0, freezed=false, freezeReason=null, client=[addr=redis://<host>:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1606408253 [redisClient=[addr=redis://<host>:6379], channel=[id: 0x10f2380a, L:/:58058 ! R:<host>/:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@53692e5c(success)], command=(BLPOP), params=[usermessage_queue2, 60], codec=org.redisson.client.codec.StringCodec]], command: (RPUSH), params: [botresponse_queue-<host>, PooledUnsafeDirectByteBuf(ridx: 0, widx: 140, cap: 512)] after 3 retry attempts\n\tat org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:270)\n\tat org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58)\n\tat org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:155)\n\tat org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:152)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)\n\tat io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)\n\tat io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)\n\tat io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)\n\tat io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1104)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.nio.channels.ClosedChannelException: null\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)\n\t... 12 common frames omitted
```

**Comment by mrniko** [comment]
> it's trying on the connection which is busy with BLPOP on entirely on different queue

Redisson uses connection pool. If connection acquired fro BLPOP it can't be used by other until it finishes.

Can you share your code sample to reproduce it?

**Comment by rgampa** [comment]
@mrniko As mentioned in the description this is intermittent issue in production, can't reproduce it locally. In the exception that I have attached during RPUSH, you can see both commands RPUSH and BLPOP, I don't know what that means.

**Comment by mrniko** [comment]
which Redisson object do you use to invoke BLPOP command?

**Comment by rgampa** [comment]
@mrniko Here is the code to push to queue, and pop from queue.

```
public void pushToQueue(String queueName, String content) {
		RList<String> list = redissonClient.getList(queueName);
		try {
			list.add(content);
		} catch (Exception ex) {
			LOG.error("Error occurred while adding to queue {}", queueName, ex);
		}
	}

public String popFromQueue(int timeout, String queueName) {
		RBlockingQueue<String> queue = redissonClient.getBlockingQueue(queueName);
		try {
			return queue.poll(timeout, TimeUnit.SECONDS);
		} catch (InterruptedException ex) {
			Thread.currentThread().interrupt();
			LOG.error("Error occurred while popFromQueue() with queue {} with timeout {}", queueName, timeout, ex);
			return null;
		}
	}
```

**Comment by rgampa** [comment]
Hi @mrniko Have you found any root cause for this exception? And also I suggest to perform automatic retries on a different connection when netty channel closed error happens, instead of retrying 3 times on same corrupted channel. If it's not in scope of Redisson, then please let me know, I will add retries from code in case of WriteRedisConnectionException.

**Comment by mrniko** [comment]
> Have you found any root cause for this exception? 

Not yet.

> And also I suggest to perform automatic retries on a different connection when netty channel closed error happens, instead of retrying 3 times on same corrupted channel

You can change attempts amount in https://github.com/redisson/redisson/wiki/2.-Configuration#retryattempts setting.

**Comment by rgampa** [comment]
@mrniko Thanks for quick reply. Yes, I am aware of the retry settings, I would like to have it, but is it possible to retry on another connection when it receives netty closure exception?

**Comment by mrniko** [comment]
This is how it works.

**Comment by rgampa** [comment]
@mrniko Ok, but in many exceptions I see after trying for 3 times also client receiving error, it's very rare that at the same time other connections also throwing netty channel closed error.

**Comment by mrniko** [comment]
> after 0 retry attempts 

means at first call

**Comment by mrniko** [comment]
Unable to reproduce the issue. Here is my test

```java
        Config config = createConfig();
        config.useSingleServer().setConnectionMinimumIdleSize(2).setConnectionPoolSize(2).setPingConnectionInterval(100);

        RedissonClient redisson = Redisson.create(config);
        RBlockingQueue<Integer> queue1 = getQueue(redisson);
        AtomicReference<Integer> rr = new AtomicReference<>();
        new Thread(() -> {
            try {
                Integer r = queue1.poll(10, TimeUnit.SECONDS);
                rr.set(r);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
        
        for (int i = 0; i < 10; i++) {
            assertThat(queue1.add(i)).isTrue();
        }

        assertThat(queue1.size()).isEqualTo(9);
        assertThat(rr.get()).isEqualTo(0);
        redisson.shutdown();
```

**Comment by rgampa** [comment]
@mrniko yes understand it’s first attempt from exception, but as per my understanding client should receive error after 3 retry attempts are exhausted.

**Comment by mrniko** [comment]
the first exception is reported https://github.com/redisson/redisson/blob/02befca6de2381dbd7a5e8a843616a7858de5c33/redisson/src/main/java/org/redisson/command/RedisExecutor.java#L188

**Comment by rgampa** [comment]
@mrniko normally in my development unit tests also I don’t receive the error, but in production we are seeing this error intermittently, and Sometimes exception shows BLOP command when doing RPUSH. Sometimes shows 3 retry attempts, sometimes 0 retry attempts. It’s hard to understand where is the issue?

**Comment by rgampa** [comment]
Hi @mrniko Today I see another instance of `org.redisson.client.WriteRedisConnectionException` where `currentCommand=null], command: null,` command itself logged as null. It happened only twice in last 7 days in the production. Any guess when this happens when no command to submit?

**Comment by mrniko** [comment]
Right, could you list all Redisson methods you use?

**Comment by rgampa** [comment]
@mrniko Here are the Redisson methods I am using currently. 
```
redissonClient.getBucket(key).expire(tsMillis, TimeUnit.MILLISECONDS);
redissonClient.getBucket(key).trySet(value);
batch.getBucket(key).setAsync(value, ttl, TimeUnit.MILLISECONDS);
redissonClient.getBucket(key).get();
redissonClient.getBucket(key).isExists();
redissonClient.getBucket(key).delete();
redissonClient.getList(queueName).add(content);
redissonClient.getList(queueName).size()
redissonClient.getBlockingQueue(queueName).poll(timeout, TimeUnit.SECONDS);
```

**Comment by mrniko** [comment]
Unable to reproduce it with the latest version
