### ISSUE TITLE
publish return 0 when redisson as client

### ISSUE THREAD

**Issue by lp2jx0309** [redisson/redisson#2698]
sentinel mode, 3 node
demo code:

	@Inject
	private RedissonService redissonService;

	@PostConstruct
	private void init() throws RedissonException {
		redissonService.getRedissonClient().getTopic
				("lip",new StringCodec()).addListener(String.class, (channel, msg) -> logger.info("msg: " + msg + ": " + channel.toString()));

	}

----------------------------------
result:
![image](https://user-images.githubusercontent.com/21236175/79293892-5a9da180-7f07-11ea-81f5-93f509947f74.png)

**Comment by mrniko** [comment]
Could you describe the issue?

**Comment by lp2jx0309** [comment]
i started redis server in my computer by sentinel mode,used port 6379,6380,6381 . i open two dos redis-cli, one subscribe "hello", the other one publish msg to  "hello" with return value 1.it is correct. but , when i use redisson client subscribe topic "lip"  and  publish msg to  "lip" , the return value is 0, while redisson listener received the msg correcttly,  the return value is expected 1.

**Comment by mrniko** [comment]
invoke MONITOR in redis-cli to check if subscription was really made.

**Comment by lp2jx0309** [comment]
ok， thanks
