### ISSUE TITLE
wheather use the shared instance or a new one, when getting reids object every time ? 

### ISSUE THREAD

**Issue by lp2jx0309** [redisson/redisson#2704]
hi,@mrniko
in the following scenarios, i do not know how to use the API, can you give me some advice?
since the password of the server will be changed, the client needs to get a new redisson object every time to access redis server. then, how to configure the codec？
1、redissonClient.getBucket("a", new JsonJacksonCodec()).set(new Animal());
Whether the above code will cause OOM when used in multiple threads，described in #2574

2、redissonClient.getBucket("a", JsonJacksonCodec.INSTANCE).set(new Animal());
if so, is there performance issue with json serialization and deserialization？
Gilberto Torrezan said "the ObjectMapper is indeed Thread safe. But reusing the same object can decrease the performance of your application, since all - 1 threads can be locked at a given time waiting for the owner of the lock to complete the serialization/deserialization of JSON." in
https://stackoverflow.com/questions/18611565/how-do-i-correctly-reuse-jackson-objectmapper/18615839
and, wheather you provide this  instance(JsonJacksonCodec.INSTANCE) to advise not to new  instance every time?

thanks!

**Comment by mrniko** [comment]
There are no performance inssues with JsonJacksonCodec.INSTANCE it's also fully thread-safe. ObjectMapper is also thread-safe.
