### ISSUE TITLE
org.redisson.client.RedisResponseTimeoutException

### ISSUE THREAD

**Issue by tmaerd** [redisson/redisson#2705]
Environment Info:
--------------------------------------
redis server machine:
net.ipv4.tcp_keepalive_time:1200
--------------------------------------
redis-server version:4.0.11
redis.config:
timeout 300
tcp-keepalive 300
--------------------------------------

redission-version:3.12.0
redission-config:
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  dnsMonitoringInterval: 5000
  natMap: {}
  nodeAddresses:
  - "redis://XXXX"
  - "redis://XXXX"
  - "redis://XXXX"
  - "redis://XXXX"
  - "redis://XXXX"
  - "redis://XXXX"
  scanInterval: 5000
  checkSlotsCoverage: false
  slaveSubscriptionConnectionPoolSize: 50
  slaveSubscriptionConnectionMinimumIdleSize: 1
threads: 16
nettyThreads: 32
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
keepPubSubOrder: true
decodeInExecutor: false
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}
-----------------------------------------------------------------------------------------------------------
Sometimes the following error occurs:
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Increase nettyThreads and/or timeout settings. Command: (EVAL), ......
........
-----------------------------------
problem analysis:
After catching the network packet,we found the reason is the redission client use a closed connection (maybe closed by os tcp or redis-server ) in the ConnectionPool.
![20200417175446](https://user-images.githubusercontent.com/22915482/79557097-9043b580-80d4-11ea-9978-3eb6a284b28d.jpg)
-----------------------------------
question:
Because the connection in the connection pool has not been operated for a long time, it is closed by the server, and the connection pool does not know.
I want to konw whether there is a heartbeat mechanism on the redisson client and redis-server(use the default configuration)?
Is there any problem with this configuration?
Is there any invalid connection detection mechanism?

-----------------------------------
英文可能表述不准确,汉语说下.
经过抓包分析发现,redission客户端使用的连接是被操作系统层面关闭的,
由于相关配置,tcp连接长时间无操作会被强制关闭,而且redis-server也设置5分钟无操作关闭连接,
这样就会导致在连接池中维护的最小连接数的连接,如果长时间无操作,就会被tcp或者redis-server关闭
客户端如果再使用这个连接就会导致超时,org.redisson.client.RedisResponseTimeoutException
目前redisson有这方面的失效连接检测机制吗?

**Comment by mrniko** [comment]
Define pingConnectionInterval setting

https://github.com/redisson/redisson/wiki/2.-Configuration#pingconnectioninterval

**Comment by tmaerd** [comment]
Thank you.It works.
It would be better if this parameter can be enabled by default

**Comment by liuweiweiweiwei** [comment]
你好这个设置的作用的是重新连接还是连接检测

**Comment by tmaerd** [comment]
> 你好这个设置的作用的是重新连接还是连接检测

连接检测,定时发心跳,防止连接空闲过长被关闭

**Comment by liuweiweiweiwei** [comment]
您好，那redisson这边有断开重连的设置么？我发现setretrytemp和setretryinterval没作用
