### ISSUE TITLE
About asynchronous methods in RMapCache

### ISSUE THREAD

**Issue by Aurorai** [redisson/redisson#2711]
Hello, Ask a question:
We want to control the data through redis in a high concurrency scenario, but now we have a problem. After reading the methods inside, all of them are asynchronous. It seems that the data retrieval is not correct. Please ask me how to solve this problem. It is my object. Is it wrong?

**Comment by mrniko** [comment]
You need to chain async method invocations.

**Comment by Aurorai** [comment]
@mrniko 
I looked at the method inside, did not find the relevant API, or can the link address be sent? Thank you.

**Comment by mrniko** [comment]
https://stackoverflow.com/questions/37265253/completablefuture-chaining-results

**Comment by Aurorai** [comment]
@mrniko 
It may be that I didn't make it clear that this scenario is in the case of multi-threading. If the method is asynchronous, will it cause data insecurity, or am I understanding it wrong?
