### ISSUE TITLE
RSetReactive contains not full equals

### ISSUE THREAD

**Issue by pengliaoye** [redisson/redisson#2712]
redis set has element
"131524001193300000012"

RSetReactive.contains("1524001193300000012")
**Expected behavior**
should returen false, because use   redis  SISMEMBER
**Actual behavior**
true
**Steps to reproduce or test case**

**Redis version**
redis-cli 5.0.4
**Redisson version**

**Redisson configuration**

**Comment by mrniko** [comment]
It returns true, since set contains this element

**Comment by pengliaoye** [comment]
but redis SISMEMBER not return true.  how can i  test set has element

**Comment by mrniko** [comment]
make sure you don't have any additional symbols added by codec.

**Comment by pengliaoye** [comment]
using StringCodec working
