### ISSUE TITLE
MapLoader and TTL

### ISSUE THREAD

**Issue by mimarko** [redisson/redisson#2715]
Is it possible to load entry into hash map (e.g. RMapCache) and set TTL for loaded entry? What would be workaround if this feature not exists?
I would like to add entries into cache using read-through strategy but to keep that entries with TTL and evicted after TTL.

Thanks,
Marko

**Comment by mrniko** [comment]
Yes it's possible. See code example part:

https://github.com/redisson/redisson/wiki/7.-distributed-collections#eviction

**Comment by skagedal** [comment]
Hello! Found this old question when googling, and I'm not sure I understand how this answers it. So there is a way to set TTL by using `put`, but that's not what the question asks... or at least not what I am asking. :) I'd like to have a map that that loads entries using a `MapLoader`, and once loaded they should have an eviction strategy. Preferrably settable per item... is anything like that possible?

**Comment by IEnoobong** [comment]
hi @skagedal please where you able to find a way to do this?

**Comment by skagedal** [comment]
@IEnoobong I don't remember, but I don't think so. Sorry!

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/4909
