### ISSUE TITLE
Rbatch String values pre append \x00\

### ISSUE THREAD

**Issue by majidshaikh16** [redisson/redisson#2716]
Hi,
I am using the below code:
RBatch batch = redisson.createBatch(BatchOptions.defaults());
RMapCacheAsync<String, String> map = batch.getMapCache(cdrKey);
map.putAllAsync(batchRequest);
config.setCodec(StringCodec.INSTANCE);

Why are my values appending \x00\x00\x00\x00\x00\x00\x00\ before the XYZ string which is my real value?

**Comment by majidshaikh16** [comment]
For example, my value is a JSON string let take this as an example:
"{'name':Alex'}"
After submitting it to Redis the values become:
"\x00\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00{'name':Alex'}"

**Comment by mrniko** [comment]
default codec is FSTCodec, try to use StringCodec

**Comment by majidshaikh16** [comment]
I am already using it in my Redisson config
 config.setCodec(StringCodec.INSTANCE);
I had also tried RMapCacheAsync<String, String> map = batch.getMapCache(cdrKey,StringCodec.INSTANCE);

Still the same result.

**Comment by majidshaikh16** [comment]
> Hi,
> I am using the below code:
> RBatch batch = redisson.createBatch(BatchOptions.defaults());
> RMapCacheAsync<String, String> map = batch.getMapCache(cdrKey);
> map.putAllAsync(batchRequest);
> config.setCodec(StringCodec.INSTANCE);
> 
> Why are my values appending \x00\x00\x00\x00\x00\x00\x00\ before the XYZ string which is my real value?

If you see I had already done this.

**Comment by majidshaikh16** [comment]
@mrniko Am I missing something?

**Comment by mrniko** [comment]
Could you share complete code example?

**Comment by majidshaikh16** [comment]
@mrniko 
public void addBatch(Map<String, String> batchRequest) {
		RBatch batch = redisson.createBatch(BatchOptions.defaults());
		RMapAsync<String, String> map = batch.getMap(cdrKey);
		map.putAllAsync(batchRequest);
		map.expireAsync(keyExpiry, TimeUnit.MILLISECONDS);
		RFuture<BatchResult<?>> result = batch.executeAsync();
		result.whenCompleteAsync((res, exp) -> {
			boolean success = (boolean) res.getResponses().get(1);
			if (success)
				Constant.REDIS_REQ_BATCH_COUNT.getAndIncrement();
			else
				Constant.REDIS_REQ_BATCH_FAILURE_COUNT.getAndIncrement();
		});
	}

In Redisson config file 
config.setCodec(StringCodec.INSTANCE);

**Comment by majidshaikh16** [comment]
What I notice is:
if change 
RMapCacheAsync<String, String> map = batch.getMapCache(cdrKey,StringCodec.INSTANCE);
to
RMapAsync<String, String> map = batch.getMap(cdrKey);
it works give me the clean json string in value.

**Comment by mrniko** [comment]
MapCached object stores additional info per map entry

**Comment by majidshaikh16** [comment]
But does that affect resulting in different values(one pre appended \X00\ and another a clean as expected string)?

**Comment by mrniko** [comment]
No, because RMap structure is not compatible with RMapCache
