### ISSUE TITLE
tomcat8集成redission后，AAP运行后生成很多FastThreadLocalThread对象，不久OOM

### ISSUE THREAD

**Issue by aonf** [redisson/redisson#2717]
请教个问题，tomcat8集成redission后，AAP运行后生成很多FastThreadLocalThread对象，不久OOM。

33 instances of "io.netty.util.concurrent.FastThreadLocalThread", loaded by "java.net.URLClassLoader @ 0x6c1ae3398" occupy 817,977,408 (68.17%) bytes. 

Biggest instances:
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2499ac8 redisson-netty-2-23 - 41,760,720 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c26866e0 redisson-netty-2-29 - 41,759,680 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2b846a8 redisson-netty-2-7 - 41,759,552 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2af2778 redisson-netty-2-9 - 41,759,488 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2dde1e0 redisson-netty-2-6 - 41,759,432 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2b11718 redisson-netty-2-1 - 41,759,288 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c268f208 redisson-netty-2-28 - 41,759,240 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2579748 redisson-netty-2-4 - 41,759,144 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2c4d858 redisson-netty-2-22 - 41,758,760 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2ca50c0 redisson-netty-2-18 - 41,758,752 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c25689e0 redisson-netty-2-2 - 41,758,448 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c29213a0 redisson-netty-2-15 - 41,741,384 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2664de8 redisson-netty-2-21 - 41,741,200 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c25de460 redisson-netty-2-24 - 41,740,304 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c267d890 redisson-netty-2-32 - 41,740,200 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2994798 redisson-netty-2-27 - 41,740,024 (3.48%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2a35a90 redisson-netty-2-25 - 17,913,472 (1.49%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2799e98 redisson-netty-2-26 - 17,379,360 (1.45%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2cfa1c0 redisson-netty-2-11 - 17,375,328 (1.45%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2e46c58 redisson-netty-2-19 - 17,360,160 (1.45%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c2498428 redisson-netty-2-3 - 17,356,816 (1.45%) bytes. 
•io.netty.util.concurrent.FastThreadLocalThread @ 0x6c27a7df0 redisson-netty-2-20 - 17,355,424 (1.45%) bytes. 

Keywords
io.netty.util.concurrent.FastThreadLocalThread
java.net.URLClassLoader @ 0x6c1ae3398

如下是我们的版本及配置信息
redis version 5.0.3

redisson version 3.12.4

tomcat version 8.0.39
-----------server.xml------------
 <GlobalNamingResources>
    <Resource name="bean/redisson"
              auth="Container"
              factory="org.redisson.JndiRedissonFactory"
              configPath="${catalina.base}/conf/redisson.yaml"
              closeMethod="shutdown"/>
  </GlobalNamingResources>
-----------context.xml------------
<ResourceLink name="bean/redisson"
                  global="bean/redisson"
		  type="org.redisson.api.RedissonClient" />

<Manager className="org.redisson.tomcat.JndiRedissonSessionManager"
         readMode="REDIS"
         jndiName="bean/redisson" />
		 
-----------redisson.yaml-----------
---
sentinelServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 6000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: "xxxx"
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  sentinelAddresses:
  - "redis://"
  - "redis://"
  - "redis://"
  masterName: "xxxx"
  database: 0
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

**Comment by aonf** [comment]
tomcat version 8.0.39
-----------server.xml------------
 <GlobalNamingResources>
    <Resource name="bean/redisson"
              auth="Container"
              factory="org.redisson.JndiRedissonFactory"
              configPath="${catalina.base}/conf/redisson.yaml"
              closeMethod="shutdown"/>
  </GlobalNamingResources>
-----------context.xml------------
<ResourceLink name="bean/redisson"
                  global="bean/redisson"
		  type="org.redisson.api.RedissonClient" />

<Manager className="org.redisson.tomcat.JndiRedissonSessionManager"
         readMode="REDIS"
         jndiName="bean/redisson" />

**Comment by aonf** [comment]
tomcat version 8.0.39

conf/server.xml
 <GlobalNamingResources>
    <Resource name="bean/redisson"
              auth="Container"
              factory="org.redisson.JndiRedissonFactory"
              configPath="${catalina.base}/conf/redisson.yaml"
              closeMethod="shutdown"/>
  </GlobalNamingResources>

conf/context.xml
<ResourceLink name="bean/redisson"
                  global="bean/redisson"
		  type="org.redisson.api.RedissonClient" />

<Manager className="org.redisson.tomcat.JndiRedissonSessionManager"
         readMode="REDIS"
         jndiName="bean/redisson" />

**Comment by aonf** [comment]
**-----------server.xml------------
 <GlobalNamingResources>
    <Resource name="bean/redisson"
              auth="Container"
              factory="org.redisson.JndiRedissonFactory"
              configPath="${catalina.base}/conf/redisson.yaml"
              closeMethod="shutdown"/>
  </GlobalNamingResources>
-----------context.xml------------
<ResourceLink name="bean/redisson"
                  global="bean/redisson"
		  type="org.redisson.api.RedissonClient" />

<Manager className="org.redisson.tomcat.JndiRedissonSessionManager"
         readMode="REDIS"
         jndiName="bean/redisson" />**

**Comment by aonf** [comment]
tomcat version 8.0.39
-----------server.xml------------

-  <GlobalNamingResources>
-     <Resource name="bean/redisson"
-               auth="Container"
-               factory="org.redisson.JndiRedissonFactory"
-               configPath="${catalina.base}/conf/redisson.yaml"
-               closeMethod="shutdown"/>
-   </GlobalNamingResources>

-----------context.xml------------

- <ResourceLink name="bean/redisson"
-                   global="bean/redisson"
- 		  type="org.redisson.api.RedissonClient" />
- 
- <Manager className="org.redisson.tomcat.JndiRedissonSessionManager"
-          readMode="REDIS"
-          jndiName="bean/redisson" />

**Comment by mrniko** [comment]
Try to switch to `MarshallingCodec` instead of current FST

**Comment by mrniko** [comment]
add dependency below:
```xml
<dependency>
            <groupId>org.jboss.marshalling</groupId>
            <artifactId>jboss-marshalling-river</artifactId>
            <version>2.0.9.Final</version>
        </dependency>
```
