### ISSUE TITLE
RedissonReactiveClient getLock and getLexSortedSet is executing on different thread.

### ISSUE THREAD

**Issue by bharti-himanshu** [redisson/redisson#2718]
`return lock.tryLock(100,10,TimeUnit.SECONDS).flatMap(lockk -> {
                   System.out.println(lockk);
                   System.out.println(Thread.currentThread().toString());
                    return redissonReactiveClient.getLexSortedSet(redisKey)
                            .readAll()
                            .flatMap(strings -> { //some map operation using result
                            })
                            .onErrorResume(throwable -> {
                                System.out.println(Thread.currentThread().toString());
`
print result - 
true
Thread[redisson-netty-2-6,5,main]
Thread[redisson-timer-4-1,5,main]
So here lockk is printed as true, but redissonReactiveClient.getLexSortedSet(redisKey) cannot execute and directly goes to onErrorResume as it is executing in different thread than lock.tryLock(). I'm new to this reactive style of programming, I don't know what I'm doing wrong maybe there is a better way to lock and get the sortedset? please help.

**Comment by mrniko** [comment]
you need to pass threadId to `tryLock` method and then the same to `unlock` method, so it would work in different threads.
