### ISSUE TITLE
Storing UUID objects is impossible ?

### ISSUE THREAD

**Issue by Aurelien30000** [redisson/redisson#2719]
Hey !

Everytime I try to store UUIDs on redis (with a List, a Set, a bucket) and I wish to compare them or use them as a keys to get elements in a hashmap for example, this error occurs, UUID is considered as a string, here is the format in redis : 

`"\"88a10822-c3e4-47e8-8f53-1069858fedc4\""`

`Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.UUID`

Maybe JsonJackson can't serialize correctly uuids, I sadly didn't find anything interesting about that :/

Thanks in advance for your answer, and sorry for disturbing with weird questions ^^

**Comment by mrniko** [comment]
Try another codec or change UUID type to string

**Comment by Sovietaced** [comment]
Why can't we use UUIDs with Redis? I am seeing the exact same issue.

**Comment by mrniko** [comment]
you can do it with MarshallingCodec or SerializationCodec

**Comment by Sovietaced** [comment]
Hmm. I will just resort to representing a UUID as a String when I need to use it as a Map key. I was just wondering what is the reason for this behavior as I mentioned, I can use UUIDs as types for fields in objects that are stored as map values. 

I am using `JsonJacksonCodec` by the way.

**Comment by mrniko** [comment]
this is how JsonJacksonCodec handles UUID - converts it into string. MarshallingCodec is now used by default.
