### ISSUE TITLE
Master fail over with AWS ElastiCache with ReplicatedServersConfig 

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#2720]
We have 1 primary and 2 replicas in our production AWS ElastiCache Redis cluster (cluster mode disabled). All three nodes given to ReplicatedServersConfig as mentioned in https://github.com/redisson/redisson/wiki/2.-Configuration#25-replicated-mode. We have set scan interval as 2000, and readMode as MASTER. We are using replicas only for failover, when we tested failover to one of the slaves, the Redisson client still sending the write requests to replica (which is old master) and failing with error `org.redisson.client.RedisException: READONLY You can't write against a read only replica`. 

Does it have to anything to do with readMode? Should we use SLAVE or MASTER_SLAVE? 

With readMode MASTER `redissonClient.getRedisNodes(RedisNodes.MASTER_SLAVE).getSlaves().size()` returns `0`, so I assume it will not have old slaves info in the context.

**Comment by mrniko** [comment]
Could you set `TRACE` logging level for `org.redisson`, reproduce this issue again and share output?

**Comment by rgampa** [comment]
Sure @mrniko I will reproduce and attach the TRACE log soon. Meanwhile in few exceptions I see `Increase nettyThreads and/or retryInterval settings`, here by `nettyThreads` means number of master and slave connections or something in the server system settings?
