### ISSUE TITLE
Use MarshallingCodec by default

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#2722]

**Comment by mrniko** [comment]
Done

**Comment by johnou** [comment]
@mrniko can you share some performance benchmark results?

**Comment by mrniko** [comment]
https://github.com/eishay/jvm-serializers/wiki#full-object-graph-serializers

River marshalling is used by default. It stands next to fst codec by performance.

**Comment by alexey-krylov** [comment]
@mrniko what was a reason to use River instead fst? Should we expect any issues using Fst with latest lib version?

**Comment by mrniko** [comment]
@alexey-krylov 

Much stable and has less issues with serialization.
