### ISSUE TITLE
Question about retryAttempts&retryInterval

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#2726]
In our environment, we see randomly long time access due to some commands go to 1 time or 2 times retry.  ~1500ms(retryInterval) passed after connection acquired but not able to send command and go to attempt. 

Restart Redis server will recover it. 

I wonder to know:
1. In which possible scenarios Redis command can't be sent to Redis server, and enter retry mode?
2. Why restart Redis server can recover?

**Comment by mrniko** [comment]
> In which possible scenarios Redis command can't be sent to Redis server, and enter retry mode?

If connection became broken due to network issue or Redis CPU 100% spike.
Try to set `pingConnectionInterval` setting

**Comment by empty117** [comment]
@mrniko : What's the usage to set "pingConnectionInterval"?
I am sure Redis CPU is not 100% spike. About connections, i set like this:
 -  idleConnectionTimeout: 10000
 - masterConnectionMinimumIdleSize: 32
 - masterConnectionPoolSize: 256

What i understood is if load is not quite high, connection number will back to 32 in case some connections got ldel time more than 10s. But i see connection number  is keeping more than 200 even in very free time.

**Comment by mrniko** [comment]
> But i see connection number is keeping more than 200 even in very free time.

I sure that these connections weren't used for more than 10s? connection pool use them in round robin.

**Comment by empty117** [comment]
@mrniko : When Redisson startup, how many connections will be established? masterConnectionMinimumIdleSize: 32 or masterConnectionPoolSize: 256?

I suppose "pingConnectionInterval" is used to detect broken connections. If this was set, in each connection, redisson will regularly execute PING command. Will it impact the connection IDLE time?

For instance: If i set pingConnectionInterval=5000, idleConnectionTimeout=10000, Does it mean connection will never been IDEL timeout?

**Comment by mrniko** [comment]
> If this was set, in each connection, redisson will regularly execute PING command. Will it impact the connection IDLE time?

It shouldn't since PingConnectionHandler doesn't use conneciton pool

**Comment by empty117** [comment]
thanks, clear to me now.
