### ISSUE TITLE
`tryLock` in redis cluster working not properly

### ISSUE THREAD

**Issue by HayTran94** [redisson/redisson#2727]
**Expected behavior**
`tryLock` of RLock can not return `true` when the lock key still exist in cluster redis.

**Actual behavior**
Sometimes `tryLock` can acquire the lock key although it still exists. Moreover, the TTL of the lock key also is reset. 

**Steps to reproduce or test case**
Invoke `boolean res = lock.tryLock(100, 3600, TimeUnit.SECONDS)` => res = true. Then after 10s, TTL of the key is 3590, in another thread, invoke `boolean res = lock.tryLock(100, 3600, TimeUnit.SECONDS)` => res = true. TTL of the key is 3600

**Redis version**
5.0.7
**Redisson version**
3.12.5

**Comment by mrniko** [comment]
Which Redis vendor do you use?

**Comment by mrniko** [comment]
Unable to reproduce.

Here is my test code:
```java
        RLock lock = redisson.getLock("lock1");
        Assert.assertTrue(lock.tryLock(100, 3600, TimeUnit.SECONDS));

        Thread.sleep(10000);

        // next row  for test renew expiration tisk.
        //Thread.currentThread().sleep(TimeUnit.SECONDS.toMillis(RedissonLock.LOCK_EXPIRATION_INTERVAL_SECONDS*2));
        Thread thread1 = new Thread() {
            @Override
            public void run() {
                RLock lock1 = redisson.getLock("lock1");
                try {
                    Assert.assertFalse(lock1.tryLock(100, 3600, TimeUnit.SECONDS));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        thread1.start();
        thread1.join();

        lock.unlock();
```

**Comment by HayTran94** [comment]
> Unable to reproduce.
> 
> Here is my test code:
> 
> ```java
>         RLock lock = redisson.getLock("lock1");
>         Assert.assertTrue(lock.tryLock(100, 3600, TimeUnit.SECONDS));
> 
>         Thread.sleep(10000);
> 
>         // next row  for test renew expiration tisk.
>         //Thread.currentThread().sleep(TimeUnit.SECONDS.toMillis(RedissonLock.LOCK_EXPIRATION_INTERVAL_SECONDS*2));
>         Thread thread1 = new Thread() {
>             @Override
>             public void run() {
>                 RLock lock1 = redisson.getLock("lock1");
>                 try {
>                     Assert.assertFalse(lock1.tryLock(100, 3600, TimeUnit.SECONDS));
>                 } catch (InterruptedException e) {
>                     e.printStackTrace();
>                 }
>             }
>         };
>         thread1.start();
>         thread1.join();
> 
>         lock.unlock();
> ```

It sometimes occurs, not always. Could you run it multiple times?

**Comment by HayTran94** [comment]
Sorry and thank you so much. I found at the `tryLock` method is invoke by the same thread. The reason is the thread is mock-up from the thread pool.
