### ISSUE TITLE
Connection Pool refresh. Redis ips keep changing. 

### ISSUE THREAD

**Issue by chowmean** [redisson/redisson#2728]
Hi, we have deployed our Redis on Kubernetes and the pods can die. One of our java apps uses redisson. I want to know if there is any setting that if one of my pod dies and a new pod comes up with new IP redisson can get the new IP and refresh the connection pool? 

Extra information: 
Redis Mode: Cluster
Redis Version: 3.2.1

**Comment by mrniko** [comment]
Yes, connections will be reconnected once pod came up

**Comment by WuKongQC** [comment]
I have the similar question. if one redis cluster die, wo set dns to new ips, redisson will not connect to new ips, why ?  how to solve this problem? thanks.

**Comment by mrniko** [comment]
@WuKongQC 

ips should be changed in Redis cluster topology as well.
