### ISSUE TITLE
how to use Redisson Lock if lua 'eval' is forbiddened in Redis Cluster because of not good support ?

### ISSUE THREAD

**Issue by kute** [redisson/redisson#2734]
In Redis Cluster, all keys require in same slot with lua, so 'lua eval' is forbiddened in some case or in company，then how to solve this to use Redisson Lock?

`Caused by: org.redisson.client.RedisException: ERR unknown command 'EVAL'`

**Comment by mrniko** [comment]
I'm afraid there is no any solution in this case.
