### ISSUE TITLE
Different DB of same redis instance share session among tomcat instances which belong  to different apps?

### ISSUE THREAD

**Issue by cloudswindow** [redisson/redisson#2735]
When different tomcat instance which belong to different App use a same redis instance, but not same DB , it looks the session shared among instances ......The  session id of B98D3CB43DC1DF0B40C47EA71B45AED7 (exception as follows ) is belong to user of app A, but the exception throwed in app B.....Is it a bug??  

**org.redisson.tomcat.RedissonSessionManager$2.onMessage Unable to handle topic message
 java.lang.IllegalStateException: Unable to find session: B98D3CB43DC1DF0B40C47EA71B45AED7
        at org.redisson.tomcat.RedissonSessionManager$2.onMessage(RedissonSessionManager.java:316)
*

**Redis version:5.0.1**

**Redisson version:2.12.4**

**Redisson configuration**

context.xml:

<Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.base}/conf/redisson.conf" readMode="MEMORY" updateMode="AFTER_REQUEST" broadcastSessionEvents="true" />

---
redisson.conf of A:
{
    "singleServerConfig":{
        "idleConnectionTimeout":10000,
        "connectTimeout":10000,
        "timeout":3000,
        "retryAttempts":3,
        "retryInterval":1500,
        "password":"pw",
        "subscriptionsPerConnection":5,
        "clientName":null,
        "address": "redis://connectString:6379",
        "subscriptionConnectionMinimumIdleSize":1,
        "subscriptionConnectionPoolSize":5,
        "connectionMinimumIdleSize":5,
        "connectionPoolSize":15,
        "database":2, ## database : 2
        "dnsMonitoringInterval":5000
    },
    "threads":16,
    "nettyThreads":16,
    "codec":{
        "class":"org.redisson.codec.JsonJacksonCodec"
    },
    "transportMode":"NIO"
}

---
 redisson.conf of app B:

{
    "singleServerConfig":{
        "idleConnectionTimeout":10000,
        "connectTimeout":10000,
        "timeout":3000,
        "retryAttempts":3,
        "retryInterval":1500,
        "password":"pw",
        "subscriptionsPerConnection":5,
        "clientName":null,
        "address": "redis://connectString:6379",
        "subscriptionConnectionMinimumIdleSize":1,
        "subscriptionConnectionPoolSize":5,
        "connectionMinimumIdleSize":5,
        "connectionPoolSize":15,
        "database":1, ## database : 1
        "dnsMonitoringInterval":5000
    },
    "threads":16,
    "nettyThreads":16,
    "codec":{
        "class":"org.redisson.codec.JsonJacksonCodec"
    },
    "transportMode":"NIO"
}

Threy use same redis , but different database。 Is it not correct usage of redisson in tomcat  session  manager?

**Comment by mrniko** [comment]
Redisson tomcat session work only with database you defined in configuration. Make sure you configured all instances properly.

**Comment by cloudswindow** [comment]
> Redisson tomcat session work only with database you defined in configuration. Make sure you configured all instances properly.

I check the configs of my apps(only two ),each app only one tomcat instance . The only different between them is database in redisson.conf (A:DB1,B:DB2).... So i have no idea  why the problem happend. As the exception shows up ,the session id not belong to itself , but belong to another instance. Shall  I must config different clientName for different tomcat cluster ?

**Comment by mrniko** [comment]
I think the problem might in Loadbalancer or something which redirects to tomcat instances.

**Comment by cloudswindow** [comment]
> I think the problem might in Loadbalancer or something which redirects to tomcat instances.

I found it ! The broadcastSessionEvents="true" cause all of it. When i set false, everythine is ok ! When a session created in tomcat instance A,  redisson broadcast to all instance in same network , but not all instances belong same app , so they can't find the session not belong itself 。

 So i think the broadcastSessionEvent  need a **Group** to mark as a cluster . Only cluster in same Group handle the events .

**Comment by cloudswindow** [comment]
I check the logs of  22 clusters already running on-line , the broadcastSessionEvent= true cause many exceptions when session created or destroy . They run in k8s , so in same network. It's harmless，but it will be  better if no these exceptions..

**Comment by mrniko** [comment]
That can't happen since topic connected to the same database you defined. Which Redis vendor do you use?

**Comment by cloudswindow** [comment]
> That can't happen since topic connected to the same database you defined. Which Redis vendor do you use?

Redis 5.0, in online case , each cluster connected to Individual redis instance , but that prolbem also happened .

**Comment by mrniko** [comment]
it's Aliyun Reids vendor issue.

**Comment by thomschke** [comment]
If you set broadcastSessionEvents="true", then all tomcat instances will create a web-session in parallel based on broadcasting of SessionCreatedMessage events.

If you defined a session-timeout inside your web.xml too,
then all tomcat-instances will trigger **the termination in parallel** because they were created in parallel :-)

So all tomcat instances will broadcast SessionDestroyedMessage events in parallel, but the underlying web-session no longer exists at the neighborhood.

I think https://github.com/redisson/redisson/blob/31260a32ac04679c9bc8fbae611e1097981fb752/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java#L319 is to strong .
