### ISSUE TITLE
On sentinel failover, connections to the new master are getting doubled

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#2739]
version: 3.12.4
When force failing over the number of connections to the new master are getting doubled. We establish around 6000 connections to redis server across all application servers. We didn't change the default idle connections from 24. After failover we observe 48 idle connection to new master, and it's not coming down till we restart the application servers. Because of this issue we had to change the max connections in redis-server to 20000 from 10000. 

Configuration used.

```
Config config = new Config();
config.setCodec(StringCodec.INSTANCE);

SentinelServersConfig serverConfig = config.useSentinelServers()
	.setMasterName("cb-master")
	.setScanInterval(2000) 
	.setReadMode(ReadMode.MASTER_SLAVE) 
	.setTimeout(20000)
	.setPingConnectionInterval(10000)
	.setCheckSentinelsList(false);
```

**Comment by mrniko** [comment]
Redisson idle connections are remain for elected slave as master. Because this node remains in slave connection pool but in non-active state. These connections are preserved for case when your cluster lost all slaves. In this case master used as slave and idle-connections become in use.

**Comment by rgampa** [comment]
> Redisson idle connections are remain for elected slave as master. Because this node remains in slave connection pool but in non-active state. These connections are preserved for case when your cluster lost all slaves. In this case master used as slave and idle-connections become in use.

Ok, thanks for the info, is it documented somewhere in the documentation? if not please do the same. It has causes our services to fail health checks and took few minutes to figure out to increase the connections in redis server.

**Comment by mrniko** [comment]
I'll add this info on wiki

**Comment by rgampa** [comment]
Thanks, this issue can be closed.

**Comment by mrniko** [comment]
Fixed.
