### ISSUE TITLE
Idle connection is not killed after timeout

### ISSUE THREAD

**Issue by stevenli1217** [redisson/redisson#2740]
clusterServersConfig:
  idleConnectionTimeout: 30000
  pingTimeout: 1000
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 10
  slaveConnectionMinimumIdleSize: 1
  slaveConnectionPoolSize: 2
  masterConnectionMinimumIdleSize: 3
  masterConnectionPoolSize: 4
  pingConnectionInterval: 0
  keepAlive: true

I use the above settings. The connections is always 2 event the idle time is bigger than 20 seconds.
`id=134 addr=172.18.0.1:43642 fd=19 name=MerchantDataService age=1278 idle=1278 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=135 addr=172.18.0.1:43696 fd=20 name=MerchantDataService age=1278 idle=1278 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly`

Did I miss something?

Btw, for the connections in master node, it always 4 and no connection is closed after idleConnectionTimeout.

**Comment by mrniko** [comment]
Redisson opens additional connection per node to retrieve topology information

**Comment by stevenli1217** [comment]
Thank you!
