### ISSUE TITLE
How to custom rules of acquire lock

### ISSUE THREAD

**Issue by SunJiFengPlus** [redisson/redisson#2741]
RLock base on thredId to judge holder, how can i custom rules like base on an income string?
or is there any way to implements ?

**Comment by mrniko** [comment]
try to use string.hashCode method

**Comment by SunJiFengPlus** [comment]
Below is the effect I want to achieve

```  java
// JVM1
RLock lock = client.getRLock("ShareString", "KEY");
// lock success
lock.lock();

// JVM2
RLock lock = client.getRLock("ShareString", "KEY");
// lock success
lock.lock();

// JVM3
RLock lock = client.getRLock("AnotherString", "KEY");
// lock fail
lock.lock();
```

**Comment by mrniko** [comment]
Semaphore objects aren't based on threadId

**Comment by SunJiFengPlus** [comment]
> Semaphore objects aren't based on threadId

Thanks for your reply, i will try this
