### ISSUE TITLE
DNS monitoring for cluster mode

### ISSUE THREAD

**Issue by stevenli1217** [redisson/redisson#2746]
We have a prod env which is using Redis cluster in AWS and aws provide a cluster endpoint. Our redisson configuration is cluster mode. But we just use the cluster endpoint in nodeAddress but not a list of cluster nodes:
```
  nodeAddresses:
    - "redis://my_cluster_endpoing.xxx.clustercfg.usw2.cache.amazonaws.com:6379"
```

When we upgrade Redis cluster,  ip address of all the nodes are  changed. It seems that Redisson cannot figure out the new ip address. It keeps  reconnecting to the old ip addresses and we have to bounce all the micro services to mitigate this issue.

I found that DNS monitoring is not enabled for cluster mode. Do you have any suggestion do solve/work-around this issue?

**Comment by stevenli1217** [comment]
Will this fix [#1213](https://github.com/redisson/redisson/issues/1213) resolve this issue?
Can I enable DNS monitoring in cluster mode?

**Comment by stevenli1217** [comment]
https://github.com/redisson/redisson/issues/1213

Is this a fix for DNS monitoring in cluster mode?

**Comment by mrniko** [comment]
@stevenli1217 Yes.
