### ISSUE TITLE
Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME)

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#2748]
Redisson version: 3.12.4

In production we are seeing intermittent error spikes of background sentinel commands timeout failures like `SENTINEL SENTINELS`, `SENTINEL SLAVES`, `SENTINEL GET-MASTER-ADDR-BY-NAME`. Are these related to available `nettyThreads`? This is happening only in couple of servers, we have around 100+ servers in production with similar settings. At the same time we didn't see any regular application side used commands' redis timeouts. 

```
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL GET-MASTER-ADDR-BY-NAME)
```
Can you let me know what could be reason for these intermittent errors?

**Comment by mrniko** [comment]
Please check Redis instance load and network

**Comment by rgampa** [comment]
@mrniko Yes, checked the redis load and network side of things, they look good. Am curious why only SentinelConnectionManager failing to execute these background sentinel commands intermittently due to timeout. In the sentinel config what's the use of the flag `checkSentinelsList`?

**Comment by mrniko** [comment]
> In the sentinel config what's the use of the flag checkSentinelsList?

It checks for presence of at least 2 sentinels in Redis setup
