### ISSUE TITLE
Distributed scheduled executor service 

### ISSUE THREAD

**Issue by 1985815103** [redisson/redisson#2749]
**Distributed scheduled executor service occur exception：**

`Caused by: java.lang.IllegalArgumentException: java.io.IOException: java.lang.RuntimeException: Class org.redisson.Redisson does not implement Serializable or externalizable`
`	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:383)`
`	at org.redisson.RedissonExecutorService.scheduleAsync(RedissonExecutorService.java:979)`
`	at org.redisson.RedissonExecutorService.schedule(RedissonExecutorService.java:969)`
`	at com.xiaoyun.ws.support.ServerPacketSchedule.scheduleSendPackets(ServerPacketSchedule.java:46)`
`	at com.xiaoyun.ws.support.ServerPacketSchedule.<init>(ServerPacketSchedule.java:35)`
`	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)`
`	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)`
`	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)`
`	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)`
`	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)`
`	... 21 common frames omitted`
`Caused by: java.io.IOException: java.lang.RuntimeException: Class org.redisson.Redisson does not implement Serializable or externalizable`
`	at org.redisson.codec.FstCodec$2.encode(FstCodec.java:279)`
`	at org.redisson.RedissonExecutorService.encode(RedissonExecutorService.java:378)`
`	... 30 common frames omitted`
`Caused by: java.lang.RuntimeException: Class org.redisson.Redisson does not implement Serializable or externalizable`
`	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)`
`	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)`
`	at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:369)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:664)`
`	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:546)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:458)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)`
`	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)`
`	at org.redisson.codec.FstCodec$2.encode(FstCodec.java:271)`

**code as：**
` executorService = redisson.getExecutorService("ServerPacketSchedule");`
` RunnableTask runnableTask = new RunnableTask(bootstrap, redisson );`
` scheduledFuture = executorService.schedule(runnableTask, CronSchedule.of("0/1 * * * * ?"));`

` public static class RunnableTask implements Runnable, Serializable {`
`     private RedissonClient redissonClient;`
`     private TioWebSocketServerBootstrap bootstrap;`
` `
`     public RunnableTask(TioWebSocketServerBootstrap bootstrap, RedissonClient redissonClient) {`
`         this.redissonClient = redissonClient;`
`         this.bootstrap = bootstrap;`
`     }`
`     @Override`
`     public void run() {`
`         RList<Object> list = redissonClient.getList("live:packet-buffer");`
`         if (CollectionUtils.isNotEmpty(list)) {`
`             WsResponse wsResponse = ServerPacket.createBath(list.toArray());`
`             Tio.sendToAll(bootstrap.getTioConfig(), wsResponse);`
`             list.clear();`
`         }`
`     }`
` }`

**redisson-version：3.12.5**

**Comment by mrniko** [comment]
You need to use @Injected annotation instead of passing Redisson as argument.

**Comment by 1985815103** [comment]
> 
> 
> You need to use @injected annotation instead of passing Redisson as argument.

but at charpter in wiki (9.4.4. Scheduling a task with Spring beans) can use Spring's @Autowire, @Value to inject spring bean

**Comment by mrniko** [comment]
Sorry, I meant "@RInject" annotation

**Comment by 1985815103** [comment]
> 
> 
> Sorry, I meant "@RInject" annotation

Thanks，I have one more question as below:


Code:

**Comment by mrniko** [comment]
TaskSuccessListener is global setting and invoked for every task
