### ISSUE TITLE
Tomcat valves need to check getNext() if it is not null first

### ISSUE THREAD

**Issue by jchobantonov** [redisson/redisson#2751]
in UpdateValve,java there is following code (all tomcat valves needs to be checked for such code):
```
getNext().invoke(request, response);
```
and getNext() could return null if there are no additional valves to invoke

**Expected behavior**
No NullPointerException to occur

**Actual behavior**

NullPointerException would occur in Valves that uses getNext().invoke(...), if getNext() return null. 
**Steps to reproduce or test case**

**Redis version**

**Redisson version**

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed
