### ISSUE TITLE
redisson的wiki中文文档解释问题

### ISSUE THREAD

**Issue by cryptoleeks** [redisson/redisson#2755]
[https://github.com/redisson/redisson/wiki/7.-%E5%88%86%E5%B8%83%E5%BC%8F%E9%9B%86%E5%90%88#711-%E6%98%A0%E5%B0%84map%E7%9A%84%E5%85%83%E7%B4%A0%E6%B7%98%E6%B1%B0eviction%E6%9C%AC%E5%9C%B0%E7%BC%93%E5%AD%98localcache%E5%92%8C%E6%95%B0%E6%8D%AE%E5%88%86%E7%89%87sharding](url)这篇文章中对Redisson中本地缓存Map的淘汰策略方式，`SOFT`和`WAKE`的注释是不是写反了

**Comment by XLCYun** [comment]
In the section `Local cache` of  `7.1.1. Map eviction, local cache and data partitioning`  of the Wiki, the comment for `EvictionPolicy` is :
```
      // SOFT - Uses weak references, entries are removed by GC
      // WEAK - Uses soft references, entries are removed by GC
```
Also in Chinese version:
```
      // SOFT - 元素用Java的WeakReference来保存，缓存元素通过GC过程清除。
      // WEAK - 元素用Java的SoftReference来保存, 缓存元素通过GC过程清除。
```
Both has a minor mistake, swap `WeakReference` will `SoftReference` will fix it.

**Comment by mrniko** [comment]
Fixed. Thanks for report
