### ISSUE TITLE
What's the best way to update an attribute outside the normal flow?

### ISSUE THREAD

**Issue by jonyt** [redisson/redisson#2756]
I use Redisson-Tomcat with update mode `AFTER_REQUEST`. I'd like to do an update to a specific session attribute before the request gets to the `UpdateValve`. I think (ignoring for the moment ClassLoader issues) I can do something like `redissonManager.getTopic().publish(new AttributeUpdateMessage(redissonManager.getNodeId(), session.getId(), "qq", "vv", encoder));` but is there a better way?

**Comment by mrniko** [comment]
You can insert your valve before UpdateValve through `getEngine().getPipeline()` API.
