### ISSUE TITLE
Do async operations come with ordering guarantees?

### ISSUE THREAD

**Issue by ilyusha** [redisson/redisson#2759]
Is the order in which async operations are submitted to the Redisson client guaranteed to match the order in which they are actually executed?
For context, I am using `RStream.addAllAsync` to submit items to a stream, and I need the items stream order to exactly match the `addAllAsync` call order. Are there any race conditions possible with rapid calls to this method (1-2ms delays between calls) that would result in out-of-order insertion?

Thanks in advance!

**Comment by mrniko** [comment]
> Is the order in which async operations are submitted to the Redisson client guaranteed to match the order in which they are actually executed?

It might be guaranteed only if you use single connection to Redis

**Comment by johnou** [comment]
@mrniko even then it is not guaranteed because of the retry system. @ilyusha yes OOO is possible unless you chain the next add to the previous future.

**Comment by ilyusha** [comment]
Thanks @mrniko and @johnou! That was my hunch but I wanted to make sure.
