### ISSUE TITLE
RateLimiter Overall configuration across different nodes

### ISSUE THREAD

**Issue by riruvurilp** [redisson/redisson#2762]
Hi,

I have 3 different processes accessing Redis. I am using the below code to make sure only one node gets hold of the resource for the specified time.

RRateLimiter limiter = redisson.getRateLimiter("test");
//1 permit for every 60 seconds
limiter.trySetRate(RateType.OVERALL, 1, 60, RateIntervalUnit.SECONDS);

My understanding here is 1 permit is available for every 60 seconds. If one node is processing the code after acquiring the permit, other nodes trying to call acquire should get as false.
limiter.tryAcquire(1, 2, RateIntervalUnit.SECONDS)

Here, other nodes are able to acquire the lock without 60 seconds delay. Is there something wrong with the usage? Please help me understand how would I hold the access on the resource for the specified time.

**Comment by mrniko** [comment]
> If one node is processing the code after acquiring the permit, other nodes trying to call acquire should get as false.

Yes, this is how it works

> If one node is processing the code after acquiring the permit, other nodes trying to call acquire should get as false.
limiter.tryAcquire(1, 2, RateIntervalUnit.SECONDS)

Could you provide code to reproduce it? Also make sure all nodes connected to the same Redis db.

**Comment by riruvurilp** [comment]
Thanks @mrniko. I tested this again, it is working as per the documentation.
