### ISSUE TITLE
ResissonSessionRepository  create many  redis  key  like  “xxorg.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAMExxx”, but not set ttl, how to deal with?

### ISSUE THREAD

**Issue by liuboflyon145** [redisson/redisson#2763]

**Comment by smirandamedallia** [comment]
@mrniko is there a way to have a TTL set for this ? We are going to start seeing memory problem on our redis server.

**Comment by mrniko** [comment]
ResissonSessionRepository is deprecated. Please read updated documentation https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#147-spring-session
