### ISSUE TITLE
redis主从切换后报错

### ISSUE THREAD

**Issue by liuyi9608** [redisson/redisson#2764]
[local expiredValues = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); if #exp..., 3, timer_queue, redisson_delay_queue_timeout:{timer_queue}, redisson_delay_queue:{timer_queue}, 1588874410282, 100]
org.redisson.client.RedisException: ERR READONLY You can't write against a read only instance. channel:

redisson版本3.10.6

**Comment by mrniko** [comment]
Is there code example to reproduce it?

**Comment by liuyi9608** [comment]
> Is there code example to reproduce it?
init redisson code:
 Config config = new Config();
   config.useSingleServer().setAddress(appProperties.redissonAddress).setPassword(appProperties.redissonPassword)
                .setDatabase(2);
        RedissonClient redissonClient = Redisson.create(config);

**Comment by mrniko** [comment]
I mean command you execute to reproduce it.

**Comment by mrniko** [comment]
> ERR READONLY You can't write against a read only instance.

Single Redis server doesn't have slaves, please check your Redis setup config.
