### ISSUE TITLE
sentinel: redis://xxx was down

### ISSUE THREAD

**Issue by LancasteP** [redisson/redisson#2767]
I use org.redisson:redisson-spring-boot-starter:3.12.5.
When spring-boot app with spring yaml redis section
      redis:
        password: "X"
        sentinel:
          password: "X"
          master: mymaster
          nodes: XXX:26379
started i see in log file

[redisson-netty-2-18] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.110.22.88:26379 was down
09:40:12 [redisson-netty-2-17] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.148.2.50:26379 added
09:40:15 [redisson-netty-2-26] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.110.22.88:26379 added
09:40:16 [redisson-netty-2-2] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.148.11.233:26379 was down
09:40:17 [redisson-netty-2-21] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.110.22.88:26379 was down
09:40:17 [redisson-netty-2-5] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.148.11.233:26379 added
09:40:20 [redisson-netty-2-30] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.110.22.88:26379 added
09:40:21 [redisson-netty-2-26] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.110.22.88:26379 was down
09:40:25 [redisson-netty-2-19] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.110.22.88:26379 added
.....
09:57:38 [redisson-netty-2-10] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.110.22.88:26379 was down
09:57:42 [redisson-netty-2-1] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.110.22.88:26379 added
09:57:43 [redisson-netty-2-10] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.110.22.88:26379 was down
09:57:47 [redisson-netty-2-9] INFO  o.r.c.SentinelConnectionManager lambda$null$7 sentinel: redis://10.110.22.88:26379 added
09:57:48 [redisson-netty-2-11] WARN  o.r.c.SentinelConnectionManager updateSentinels sentinel: redis://10.110.22.88:26379 was down

What's wrong?

**Comment by blacktang** [comment]
me too . do you have any idea to handle it?

**Comment by mrniko** [comment]
Make sure all sentinels has the same list of sentinel addresses

**Comment by uniqueSkeeter** [comment]
Is this a error log or not?

**Comment by nigam3008** [comment]
I am facing a similar issue. Could you please explain "Make sure all sentinels have the same list of sentinel addresses" mean with an example?

**Comment by mrniko** [comment]
`SENTINEL SENTINELS` command returns the same list for all Redis nodes
