### ISSUE TITLE
maxSize on RMapCache

### ISSUE THREAD

**Issue by thesreyas** [redisson/redisson#2769]
https://www.javadoc.io/doc/org.redisson/redisson/latest/org/redisson/api/RMapCache.html#setMaxSize-int-

Does setMaxSize( ) always successfully apply the size limit on cache?
(Why do we have two methods: maxSize and tryMaxSize)

**Comment by mrniko** [comment]
`tryMaxSize()` method sets value only it wasn't set before. `setMaxSize()` always overrides current value.
