### ISSUE TITLE
redis-cli scan 0 COUNT 20 equivalent in redisson

### ISSUE THREAD

**Issue by rautnin1103** [redisson/redisson#2772]
I want to know what is the >redis-cli scan 0 COUNT 20 equivalent in redisson. I have 4  million records in redis and want to iterate through them (with a key pattern)

I tried using Stream<String> getKeysStreamByPattern(String var1, int var2); and Iterable<String> getKeysByPattern(String var1, int var2); but it hangs infinitly.

**Comment by mrniko** [comment]
> I tried using Stream getKeysStreamByPattern(String var1, int var2); and Iterable getKeysByPattern(String var1, int var2); but it hangs infinitly.

These methods are equivalent to scan 0 COUNT 20 command. Did you define 20 as second argument? Do you use the same machine used for invoke command through redis-cli?
