### ISSUE TITLE
RedissonKeys.unlink uses del instead of unlink

### ISSUE THREAD

**Issue by AayushyaVajpayee** [redisson/redisson#2777]
**Expected behavior**
RedissonKeys.unlink(...) should execute unlink command
**Actual behavior**
RedissonKeys.unlink(...) should execute del command
**Steps to reproduce or test case**
Use method RedissonKeys.unlink(...)
**Redis version**
5.0.5
**Redisson version**
3.12.5
**Redisson configuration**
Default single server configuration

**Comment by AayushyaVajpayee** [comment]
i have provided a pull request #2776 for the same

**Comment by mrniko** [comment]
Merged
