### ISSUE TITLE
How to update RateLimiter interval?

### ISSUE THREAD

**Issue by riruvurilp** [redisson/redisson#2780]
Hi,

I have created RRateLimiter instance and want to update interval field. If I call trySetRate() it is not updating.

RRateLimiter limiter = redisson.getRateLimiter("myLimiter");
// Initialization required only once.
// 5 permits per 5 seconds
limiter.trySetRate(RateType.OVERALL, 5, 5, RateIntervalUnit.SECONDS);

// 5 permits per 2 seconds
limiter.trySetRate(RateType.OVERALL, 5, 2, RateIntervalUnit.SECONDS);

If I remove the item and create again it works. Is there a way to update RateLimiter instance without removing the item?

Please let me know.

Thanks,
Ravindra

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/2322
