### ISSUE TITLE
Redisson scalable put on cluster nodes

### ISSUE THREAD

**Issue by bingzhang** [redisson/redisson#2789]
Hello:

I am new to Redis. And I wrote a simple code to test hashmap objects in a Redis cluster of 3 nodes.

    final ClusterServersConfig clusterconfig = config.useClusterServers();
    clusterconfig.addNodeAddress(clusternodeurl1);
    clusterconfig.addNodeAddress(clusternodeurl2);
    clusterconfig.addNodeAddress(clusternodeurl3);
    redisson = Redisson.create(config);
    map = redisson.getMapCache("test");
    map.put("key1", "value1");
    map.put("key2", "value2");

Then I try the redis-cli to get all hashmap objects. it seems that all pairs are stored on the same cluster node instead of round-robin.

192.168.5.66:6379> HGETALL test
-> Redirected to slot [6918] located at 192.168.5.62:6379
1) "\xfc\x04key1"
2) "\x00\x00\x00\x00\x00\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\xfc\x06value1"
3) "\xfc\x04key2"
4) "\x00\x00\x00\x00\x00\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\xfc\x06value2"

However, when I use the redis-cli to put key and value pairs into the cluster, I can see it is round-robin.

May I know how to put hashmap object in the round-robin way?

In my test environment, redission maven
    <dependency>
        <groupId>org.redisson</groupId>
        <artifactId>redisson</artifactId>
        <version>3.12.3</version>
    </dependency>

redis server 6.0.1.

Thanks.

**Comment by mrniko** [comment]
> it seems that all pairs are stored on the same cluster node instead of round-robin.

That's correct since map data belong to a single Redis key.

**Comment by mrniko** [comment]
> However, when I use the redis-cli to put key and value pairs into the cluster, I can see it is round-robin.

It's just redirect call to the node which holds with map

**Comment by bingzhang** [comment]
@mrniko Thank you very much. 

In my user case, I need to store key, value pair into redis cluster. May you please suggest or show me whether there is a way to do scalable put using redission lib? If there is a document or sample code, that will be very helpful.

Thanks.

**Comment by mrniko** [comment]
ClusteredMapCache object available in PRO version
