### ISSUE TITLE
Auto configuration for reactive redis client in Spring Boot

### ISSUE THREAD

**Issue by ChristianIvicevic** [redisson/redisson#2796]
Currently I am using Redisson for locks with the `RedissonClient` that gets automatically configured via the `spring.redis.(host|port|password)` properties in the `application.yaml` which is super convenient.

Now I wanted to include some message handling via reactive topics to return a `Flux` for a websocket-based subscription. Thus I attempted to autowire a `RedissonReactiveClient` and noticed it isn't autoconfigured.

I am curious what the proposed way to expose a `RedissonReactiveClient` bean with the same configuration would look like.

**Comment by ajithalbus** [comment]
Is there any update on this?

**Comment by mrniko** [comment]
Done

**Comment by ajithalbus** [comment]
Thanks @mrniko
