### ISSUE TITLE
redisson 3.12.5 with error of Can't init enough connections amount! Only 0 from 30 were initialized

### ISSUE THREAD

**Issue by hillbun** [redisson/redisson#2797]
redisson 3.12.5
redis 3.2.9

I meet this problem when project startup with multiple replicas in kubernetes, some of replicas with following errors, but some are fine:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'projectModuleServiceImpl': Unsatisfied dependency expressed through field 'redissonClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redissonClient' defined in class path resource [org/maxfaith/config/RedissonConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'getRedissonClient' threw exception; nested exception is org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 30 were initialized. Server: miop-redis/10.233.105.119:6379

**Comment by hillbun** [comment]
redis info:

# Clients
connected_clients:393
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0


protected-mode is no

**Comment by mrniko** [comment]
Unable to reproduce. Please check your network

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4902
