### ISSUE TITLE
org.hibernate.LazyInitializationException: could not initialize proxy - no Session

### ISSUE THREAD

**Issue by siedmohsen2** [redisson/redisson#2798]
I want to use to hibernate level2 cache as flow config.

`@Getter`
`@Entity`
`public class Personnel{`
`@Id`
`@GeneratedValue(strategy = GenerationType.AUTO)`
`private Long id;`
`@Column`
`private String name;`
 `@Id`
  `@GeneratedValue(strategy = GenerationType.AUTO)`
  ` private Long id;`
    `private String name;`
   ` @ManyToOne(fetch = FetchType.LAZY)`
      `private Post post;`
`}`

Now for get object at the first time, all things are ok! (that means I want to load 'post' from personnel)
But when I call this function for a second time, in my personnel object the 'post' is null and I get an error as below:

`Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dozer.util.ReflectionUtils.invoke(ReflectionUtils.java:323)
	... 132 common frames omitted
Caused by: org.hibernate.LazyInitializationException: could not initialize proxy - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:146)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:259)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:73)
	at org.model.core.Post_$$_jvstb54_2a.getId(Post_$$_jvstb54_2a.java)`

Hibernate 5.2
Radisson 3.12.5
spring-boot 2.1.1

**Comment by mrniko** [comment]
Did you try to follow suggested solutions here https://stackoverflow.com/questions/21574236/how-to-fix-org-hibernate-lazyinitializationexception-could-not-initialize-prox ?

**Comment by siedmohsen2** [comment]
thanks for answering @mrniko 
I see that post but my problem is so different!
I think when I use Redis cache, it also saves proxy for all property that is Lazy! and next when I want to load a property that was in lazy mode... hibernate say that session (that used in the previous proxy) is expired! and hibernate has not any valid session for loading my lazy properties.
So I do NOT any idea for that!!

**Comment by mrniko** [comment]
> it also saves proxy for all property that is Lazy

It's just implements Hibernate Cache API nothing more. Did you try to turn off cache and try these steps?

**Comment by siedmohsen2** [comment]
I knew "It just implements Hibernate Cache API nothing more."
but when I used from ehcach I have NOT any problem!! It works very fine.
I was so confused about that!

**Comment by mrniko** [comment]
Could you share both entities definition? Also Personnel has duplicated fields

**Comment by siedmohsen2** [comment]
Personnel has Not duplicated fields! (excuse me... It's my mistake)
```@Getter
@Entity
public class Personnel{
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
private Long id;
private String firstName;
private String lastName;
private String code;
private String fatherName;
@Enumerated
private PersonelKind kind;
@ManyToOne(fetch = FetchType.LAZY)
private Post post;
...
} 
```

**Comment by mrniko** [comment]
Unable to reproduce, below is my test code:

```java
public class LazeTest extends BaseCoreFunctionalTestCase {

    @Entity
    public static class A implements Serializable {
      @Id
      @GeneratedValue(strategy = GenerationType.AUTO)
      private Long id;

      private String firstName;
      private String lastName;
      private String code;
      private String fatherName;
      @Enumerated
      private PersonelKind kind;
      @ManyToOne(fetch = FetchType.LAZY)
      private B post;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

        public String getCode() {
            return code;
        }

        public void setCode(String code) {
            this.code = code;
        }

        public String getFatherName() {
            return fatherName;
        }

        public void setFatherName(String fatherName) {
            this.fatherName = fatherName;
        }

        public PersonelKind getKind() {
            return kind;
        }

        public void setKind(PersonelKind kind) {
            this.kind = kind;
        }

        public B getPost() {
            return post;
        }

        public void setPost(B post) {
            this.post = post;
        }
    }

    public enum PersonelKind {
        A, B;
    }

    @Entity
    @Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
    public static class B implements Serializable {
      @Id
      @GeneratedValue(strategy = GenerationType.AUTO)
      private Long id;

      private String firstName;
      private String lastName;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }
    }

    @Override
    protected Class<?>[] getAnnotatedClasses() {
        return new Class[] { A.class, B.class };
    }

    @Override
    protected void configure(Configuration cfg) {
        super.configure(cfg);
        cfg.setProperty(Environment.DRIVER, org.h2.Driver.class.getName());
        cfg.setProperty(Environment.URL, "jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;");
        cfg.setProperty(Environment.USER, "sa");
        cfg.setProperty(Environment.PASS, "");
        cfg.setProperty(Environment.CACHE_REGION_PREFIX, "");
        cfg.setProperty(Environment.GENERATE_STATISTICS, "true");

        cfg.setProperty(Environment.SHOW_SQL, "true");
        cfg.setProperty(Environment.USE_SECOND_LEVEL_CACHE, "true");
        cfg.setProperty(Environment.USE_QUERY_CACHE, "true");
        cfg.setProperty(Environment.CACHE_REGION_FACTORY, RedissonRegionFactory.class.getName());
    }
    
    @Before
    public void before() {
        sessionFactory().getCache().evictEntityRegions();
        sessionFactory().getStatistics().clear();
    }

    @Test
    public void test() {
        Session s = openSession();
        s.beginTransaction();

        A a = new A();
        a.setFatherName("nameA");
        B b = new B();
        b.setFirstName("nameB");
        a.setPost(b);
        s.save(b);
        Serializable id = s.save(a);
        s.flush();
        s.getTransaction().commit();

        s = openSession();
        s.beginTransaction();
        A a1 = s.load(A.class, id);
        assertThat(a1.getPost().getFirstName()).isEqualTo("nameB");
        s.getTransaction().commit();
    }
    
}
```

**Comment by siedmohsen2** [comment]
thanks
It works very fine
