### ISSUE TITLE
RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable

### ISSUE THREAD

**Issue by NoBugBoy** [redisson/redisson#2800]
Caused by: org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable

I use the 7000 port node to create a redis cluster. When the cluster is running normally, the client connection to the cluster is normal. When the 7000 port is the master, there will be an error. 0-5000 solt cannot be added. But when the 7000 port is the slave, it is normal. But in a moment, there will be three retry failures and the connection problem cannot be found

**Comment by mrniko** [comment]
Could you share cluster info output? it's printed on Redisson start.

**Comment by NoBugBoy** [comment]
> 您可以共享集群信息输出吗？它印在Redisson开始上。

![image](https://user-images.githubusercontent.com/33510892/82975177-525c7a00-a00e-11ea-8721-6eab1a2af69a.png)

![image](https://user-images.githubusercontent.com/33510892/82975245-7cae3780-a00e-11ea-8a22-8bb87a374418.png)

errorinfo
Caused by: org.redisson.client.RedisConnectionException: Not all slots are covered! Only 10923 slots are avaliable

The cluster status is OK. There is no problem. Only a group of solts will fail to connect

**Comment by mrniko** [comment]
Sorry, I mean this output:

```java
2020.05.27 07:48:17.786 INFO  ClusterConnectionManager : Redis cluster nodes configuration got from /127.0.0.1:6890:
9d18663d380384d6ffa2bc6ec470315204539d11 127.0.0.1:6900@16900 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554897000 2 connected
6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 127.0.0.1:6890@16890 myself,master - 0 1590554895000 1 connected 0-5460
9baa91c430c09bf9d6dc09fe083033660cf3672b 127.0.0.1:6903@16903 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554896000 2 connected
e1ebb758705729ad72e96023232294a88d4e028a 127.0.0.1:6902@16902 slave 32b673df66e89646ac5b7622dc8134a0b9e85494 0 1590554896263 4 connected
2bbabb4e33ce9b8e9bcc2ae70a7c38d60f3769b5 127.0.0.1:6901@16901 slave dff311176cb01285d6acb6c53cf0a0fdc19f6590 0 1590554896765 3 connected
dff311176cb01285d6acb6c53cf0a0fdc19f6590 127.0.0.1:6891@16891 master - 0 1590554897000 2 connected 5461-10921
32b673df66e89646ac5b7622dc8134a0b9e85494 127.0.0.1:6892@16892 master - 0 1590554897267 3 connected 10922-16383
```

**Comment by NoBugBoy** [comment]
> Sorry, I mean this output:
> 
> ```java
> 2020.05.27 07:48:17.786 INFO  ClusterConnectionManager : Redis cluster nodes configuration got from /127.0.0.1:6890:
> 9d18663d380384d6ffa2bc6ec470315204539d11 127.0.0.1:6900@16900 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554897000 2 connected
> 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 127.0.0.1:6890@16890 myself,master - 0 1590554895000 1 connected 0-5460
> 9baa91c430c09bf9d6dc09fe083033660cf3672b 127.0.0.1:6903@16903 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554896000 2 connected
> e1ebb758705729ad72e96023232294a88d4e028a 127.0.0.1:6902@16902 slave 32b673df66e89646ac5b7622dc8134a0b9e85494 0 1590554896263 4 connected
> 2bbabb4e33ce9b8e9bcc2ae70a7c38d60f3769b5 127.0.0.1:6901@16901 slave dff311176cb01285d6acb6c53cf0a0fdc19f6590 0 1590554896765 3 connected
> dff311176cb01285d6acb6c53cf0a0fdc19f6590 127.0.0.1:6891@16891 master - 0 1590554897000 2 connected 5461-10921
> 32b673df66e89646ac5b7622dc8134a0b9e85494 127.0.0.1:6892@16892 master - 0 1590554897267 3 connected 10922-16383
> ```
ok




> 抱歉，我的意思是这个输出：
> 
> ```java
> 2020.05 。27  07 ：48 ：17.786  INFO   ClusterConnectionManager  ： Redis的群集节点的配置从得到/ 127.0 。0.1 ：6890 ： 
> 9d18663d380384d6ffa2bc6ec470315204539d11 127.0 。0.1 ：6900 @ 16900从站6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0  1590554897000  2已连接
> 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 127.0 。0.1 ：6890 @ 16890自己，主-  0  1590554895000  1连接0 - 5460 
> 9baa9​​1c430c09bf9d6dc09fe083033660cf3672b 127.0 。0.1 ：6903 @ 16903从站6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0  1590554896000  2已连接
> e1ebb758705729ad72e96023232294a88d4e028a 127.0 。0.1 ：6902 @ 16902从站32b673df66e89646ac5b7622dc8134a0b9e85494 0  1590554896263  4已连接
> 2bbabb4e33ce9b8e9bcc2ae70a7c38d60f3769b5 127.0 。0.1 ：6901 @ 16901从站dff311176cb01285d6acb6c53cf0a0fdc19f6590 0  1590554896765  3已连接
> dff311176cb01285d6acb6c53cf0a0fdc19f6590 127.0 。0.1 ：6891 @ 16891主-  0  1590554897000  2连接5461 - 10921 
> 32b673df66e89646ac5b7622dc8134a0b9e85494 127.0 。0.1 ：6892 @ 16892主-  0  1590554897267  3连接10922 - 16383
> ```
oh sorry 

![image](https://user-images.githubusercontent.com/33510892/82985351-7af06e00-a026-11ea-84fa-e25860da28fb.png)

**Comment by NoBugBoy** [comment]
> Sorry, I mean this output:
> 
> ```java
> 2020.05.27 07:48:17.786 INFO  ClusterConnectionManager : Redis cluster nodes configuration got from /127.0.0.1:6890:
> 9d18663d380384d6ffa2bc6ec470315204539d11 127.0.0.1:6900@16900 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554897000 2 connected
> 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 127.0.0.1:6890@16890 myself,master - 0 1590554895000 1 connected 0-5460
> 9baa91c430c09bf9d6dc09fe083033660cf3672b 127.0.0.1:6903@16903 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554896000 2 connected
> e1ebb758705729ad72e96023232294a88d4e028a 127.0.0.1:6902@16902 slave 32b673df66e89646ac5b7622dc8134a0b9e85494 0 1590554896263 4 connected
> 2bbabb4e33ce9b8e9bcc2ae70a7c38d60f3769b5 127.0.0.1:6901@16901 slave dff311176cb01285d6acb6c53cf0a0fdc19f6590 0 1590554896765 3 connected
> dff311176cb01285d6acb6c53cf0a0fdc19f6590 127.0.0.1:6891@16891 master - 0 1590554897000 2 connected 5461-10921
> 32b673df66e89646ac5b7622dc8134a0b9e85494 127.0.0.1:6892@16892 master - 0 1590554897267 3 connected 10922-16383
> ```

2223966aee940abad51178ceda38e5b8dd20d7f6 39.97.65.22:7004@17004 master - 0 1590560823616 5 connected 10923-16383
45f1feff4063a407ece0ba4407796cf3edc88dd2 172.17.180.102:7001@17001 myself,slave 2223966aee940abad51178ceda38e5b8dd20d7f6 0 1590560824000 2 connected
d7c7cda923bf16195158a560048995714a32751b 39.97.69.53:7002@17002 master - 0 1590560824320 3 connected 5461-10922
06979911b7f8c33c842afe6993c92e7712df8a68 39.97.65.22:7005@17005 slave d7c7cda923bf16195158a560048995714a32751b 0 1590560824819 6 connected
1470f133f7991a889b23306be5c5f2a2fe2d39e1 123.57.151.20:7000@17000 slave 5ed5da51885a5c98a1bc3e91839ce349f0e4a626 0 1590560824000 10 connected
5ed5da51885a5c98a1bc3e91839ce349f0e4a626 39.97.69.53:7003@17003 master - 0 1590560825521 10 connected 0-5460

> Sorry, I mean this output:
> 
> ```java
> 2020.05.27 07:48:17.786 INFO  ClusterConnectionManager : Redis cluster nodes configuration got from /127.0.0.1:6890:
> 9d18663d380384d6ffa2bc6ec470315204539d11 127.0.0.1:6900@16900 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554897000 2 connected
> 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 127.0.0.1:6890@16890 myself,master - 0 1590554895000 1 connected 0-5460
> 9baa91c430c09bf9d6dc09fe083033660cf3672b 127.0.0.1:6903@16903 slave 6cf45bcd04c1f54ea23334f0387c2eb82998b2e6 0 1590554896000 2 connected
> e1ebb758705729ad72e96023232294a88d4e028a 127.0.0.1:6902@16902 slave 32b673df66e89646ac5b7622dc8134a0b9e85494 0 1590554896263 4 connected
> 2bbabb4e33ce9b8e9bcc2ae70a7c38d60f3769b5 127.0.0.1:6901@16901 slave dff311176cb01285d6acb6c53cf0a0fdc19f6590 0 1590554896765 3 connected
> dff311176cb01285d6acb6c53cf0a0fdc19f6590 127.0.0.1:6891@16891 master - 0 1590554897000 2 connected 5461-10921
> 32b673df66e89646ac5b7622dc8134a0b9e85494 127.0.0.1:6892@16892 master - 0 1590554897267 3 connected 10922-16383
> ```

2223966aee940abad51178ceda38e5b8dd20d7f6 127.0.0.1:7004@17004 master - 0 1590560823616 5 connected 10923-16383
45f1feff4063a407ece0ba4407796cf3edc88dd2 127.0.0.1:7001@17001 myself,slave 2223966aee940abad51178ceda38e5b8dd20d7f6 0 1590560824000 2 connected
d7c7cda923bf16195158a560048995714a32751b 127.0.0.1:7002@17002 master - 0 1590560824320 3 connected 5461-10922
06979911b7f8c33c842afe6993c92e7712df8a68 127.0.0.1:7005@17005 slave d7c7cda923bf16195158a560048995714a32751b 0 1590560824819 6 connected
1470f133f7991a889b23306be5c5f2a2fe2d39e1 127.0.0.1:7000@17000 slave 5ed5da51885a5c98a1bc3e91839ce349f0e4a626 0 1590560824000 10 connected
5ed5da51885a5c98a1bc3e91839ce349f0e4a626 127.0.0.1:7003@17003 master - 0 1590560825521 10 connected 0-5460


The IP here is the Internet IP. The node is in the host network mode of docker. The cluster is also created through the Internet IP

**Comment by mrniko** [comment]
> When the 7000 port is the master, there will be an error. 0-5000 solt cannot be added

I think this master doesn't report node with 0-5000 slots

**Comment by NoBugBoy** [comment]
> > 当7000端口是主端口时，将出现错误。不能添加0-5000 solt
> 
> 我认为这个主节点不会报告0-5000个插槽的节点

最开始打错了 is 0 - 5460
