### ISSUE TITLE
Unable to decode data. channel:[id: 0x571044ad, L:/10.0.0.1] message: +PONG +PONG

### ISSUE THREAD

**Issue by huashaofei** [redisson/redisson#2805]
Unable to decode data. channel: [id: 0x571044ad,] message: +PONG
+PONG
+PONG
:2
+PONG
+PONG
*2
$1
0
*0
+PONG
+PONG
+PONG
$-1
+PONG
+PONG
+PONG
+PONG
+PONG
:1
+PONG
+PONG
+PONG
+PONG
+PONG
:2
+PONG
+PONG
:1
+PONG
+PONG
+PONG
:1
+PONG
+PONG
+PONG
$-1
+PONG
+PONG
+PONG
:1
+PONG
+PONG
+PONG
+PONG
+PONG
$-1
+PONG
+PONG
+PONG
:0
+PONG
+PONG
+PONG
+PONG
+PONG
+PONG
$34
+PONG
+PONG
+PONG
......
java.lang.ClassCastException: null

大佬们能帮忙看看redisson在什么情况下才会返回以上这些+PONG的信息，现在一直不能重现上面的返回内容。

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by huashaofei** [comment]
----- 原始邮件 -----
发件人：Nikita Koksharov <notifications@github.com>
收件人：redisson/redisson <redisson@noreply.github.com>
抄送人：huashaofei <huashaofei17@sina.com>,  Author <author@noreply.github.com>
主题：Re: [redisson/redisson] Unable to decode data. channel:[id: 0x571044ad, L:/10.0.0.1] message: +PONG +PONG (#2805)
日期：2020年05月30日 12点31分


Which Redisson version do you use?
