### ISSUE TITLE
redisson lock uncontrolled release 

### ISSUE THREAD

**Issue by mishanius** [redisson/redisson#2807]
Hi all, 
I am facing strange problems with Redisson lock.
I use the lock without expiration - which means is that watchdog mechanism in-charge of updating the lease time of the lock in redis.
Threads that are using the lock, lock it for time ranging from couple of seconds to 300 seconds or even more.
**The problem:**
sometimes when a thread(that acquired it) tries to release the lock the thread receives **IllegalMonitorStateException** , which means that this lock is already released. 

One solution was to increase the watchdog timeout - I increased it to 100 seconds and it decreased the number of errors but they still occur from time to time...

I don't want to increase the timeout even more because this doesn't address the root problem.
How can I solve this? is anyone else encountered this behaviour?

**Comment by mrniko** [comment]
> sometimes when a thread(that acquired it) tries to release the lock the thread receives IllegalMonitorStateException

Please check that you use the same thread to release it.
