### ISSUE TITLE
Batch default values not consistent with RedissonClient

### ISSUE THREAD

**Issue by chenggiant** [redisson/redisson#2812]
Redisson version: 3.12.1

https://github.com/redisson/redisson/blob/0259701922bede00e1b4f8a02593912872b5af41/redisson/src/main/java/org/redisson/api/BatchOptions.java#L88-L101

For example, in comment it says default value is 3000 ms, but it's actually 0. Does this mean RBatch execution will not timeout and could block the netty channel for quite long time?

Should the BatchOptions like timeout, retryAttempts use the values from RedissonClient?

**Comment by mrniko** [comment]
only non-zero params are applied `org.redisson.command.RedisCommonBatchExecutor#RedisCommonBatchExecutor`. Otherwise redisson client default are applied.
