### ISSUE TITLE
AWS Reader DNS being defined as master during failover

### ISSUE THREAD

**Issue by h-ngo** [redisson/redisson#2816]
Scenario:
We configured Redisson with 2 AWS DNS endpoints: Primary and Reader. Primary has one node and Reader has 2.

After failover, one of the read replicas got promoted as the primary. Technically, since this happened behind the scene in AWS, we should not see any change to the Primary and Reader.

However, in Redisson log, we saw the type of the Reader endpoint got changed to be Master

Before failover:
redis://primary.dns - Type: Master

After failover:
redis://reader.dns - Type: Master

Wonder if this is a bug or we didn't configure our Redisson correctly. Any help would be greatly appreciated

Redisson version: 3.10.4
Configuration:
- ReplicatedServers
- ReadMode.MASTER

**Comment by mrniko** [comment]
Could you share full Redisson log output?

**Comment by h-ngo** [comment]
@mrniko Will try to get your the logs as soon as I can. There are some internal info that will need to be filtered out before I can share. Thanks a lot.

**Comment by h-ngo** [comment]
Closing this as we have decided to switch to cluster mode. Testing result looks much more promising than replicated mode.
