### ISSUE TITLE
Support for SETXX operation

### ISSUE THREAD

**Issue by hgeraldino** [redisson/redisson#2817]
I have a use case in which I must update a value only if the key exists. This is supported by the SET `XX` option.

I was wondering if it makes sense to enhance the `RedissonBucket` class to support a `setIfPresent` operation(s) - encapsulating the SET XX command just like `trySet` does for SET NX, or if I should just try to get an instance of `CommandAsyncService` and run the command myself.

I'm happy to contribute to this feature if it's deemed useful.

**Comment by mrniko** [comment]
Sure, contributions are always welcome! Please don't forget also to add it to RBucketReactive and RBucketRx interfaces.

**Comment by mrniko** [comment]
Done

**Comment by hgeraldino** [comment]
Thanks @mrniko. I had something in the works and was going to raise a PR, but thanks for expediting this feature.

Something I think can be improved is having the integration tests working against docker, instead of starting a local redis binary via ProcessBuilder.

How do you feel about that?

**Comment by mrniko** [comment]
I tried that but redis cluster in docker under windows is not stable.
