### ISSUE TITLE
[Cluster] scanning nodes stops if `ClusterConnectionManager#addMasterEntry` fails

### ISSUE THREAD

**Issue by svilenivanovsmule** [redisson/redisson#2822]
**Expected behavior**
Periodic scan of cluster nodes runs forever (every `scanInterval` milliseconds)

**Actual behavior**
Periodic scan of cluster nodes stops when a single master is added to the cluster and Redisson cannot perform `CLUSTER INFO`

**Steps to reproduce or test case**
Failure to perform `CLUSTER INFO` is probably a side effect from another problem but I expect that Redisson can recover.
 
I'm using a 6 nodes cluster in a VM (libvirt) environment on 3 virtual machines. Each VM hosts one master and one slave in way that master and slave happens to be on different VMs (master1 is on VM1, but slave1 is on VM2; master2 is on VM2, while slave2 is on VM3 and master3 is on VM3 while slave3 is on VM1). Hard stop VM2 which effectively disconnects master2 and slave1. Then I bring back VM2. Former master2 is no longer master so I promote it to be master again by executing `CLUSTER FAILOVER` on it. After I do so, Redisson attempts to reconnect to master2 but for unknown reason fails with:
```
201471 [redisson-timer-4-1] ERROR o.r.c.ClusterConnectionManager - Can't execute CLUSTER_INFO for /10.1.1.12:6379
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER INFO), params: [], Redis client: [addr=redis://10.1.1.12:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Redis version**
Redis 6.0.4

**Redisson version**
3.13.0

**Redisson configuration**
All defaults, except `useClusterServer` and one node address.

**Notes** 

I traced back the issue to `org.redisson.cluster.ClusterConnectionManager#checkMasterNodesChange`:
```java
for (ClusterPartition newPart : addedPartitions.values()) {
    RFuture<Collection<RFuture<Void>>> future = addMasterEntry(newPart, cfg);
    future.onComplete((res, e) -> {
        if (e == null) {
            futures.addAll(res);
        }
        
        if (masters.decrementAndGet() == 0) {
            AtomicInteger nodes = new AtomicInteger(futures.size());
            for (RFuture<Void> nodeFuture : futures) {
                nodeFuture.onComplete((r, ex) -> {
                    if (nodes.decrementAndGet() == 0) {
                        result.trySuccess(null);
                    }
                });
            }
        }
    });
}
```

`addMasterEntry` returns failed future (`e` is not `null`) and ` futures.addAll(res);` is never executed. As a result `result` future is never resolved and the next round of scanning is not performed

**Comment by mrniko** [comment]
Thanks for report! Can you suggest a fix?

**Comment by mrniko** [comment]
Could you try attached version?

[redisson-3.13.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4746879/redisson-3.13.1-SNAPSHOT.jar.zip)

**Comment by svilenivanovsmule** [comment]
Thank you for the quick turnaround, trying it now....

**Comment by svilenivanovsmule** [comment]
The provided version fixes the issue! Thank you!

I no longer get `Can't execute CLUSTER_INFO` - looking at the code you provided - it looks like that command is no longer necessary in version 3.13.1. You also took care of resolving the `result` promise `futures.size() == 0`.

Thank you again!

**Comment by mrniko** [comment]
Thanks for feedback! Fixed
