### ISSUE TITLE
RedissonCacheStatisticsAutoConfiguration conditions not matched

### ISSUE THREAD

**Issue by paul-ovchinnikov** [redisson/redisson#2823]
**Expected behavior**
I expect to get metrics of `RedissonSpringCacheManager`

**Actual behavior**
But `RedissonCacheStatisticsAutoConfiguration` not matched to condition `@ConditionalOnBean({CacheManager.class, RedissonCache.class})`
The reason is that there isn't `RedissonCache` bean registered in context.
If you dive deep into `RedissonSpringCacheManager` you can see RedissonCache instance created, but not registered in ApplicationContext and it should not.

`RedissonCacheStatisticsAutoConfiguration":{"notMatched":[{"condition":"OnBeanCondition","message":"@ConditionalOnBean (types: org.springframework.cache.CacheManager,org.redisson.spring.cache.RedissonCache; SearchStrategy: all) did not find any beans of type org.redisson.spring.cache.RedissonCache"}]`

**Steps to reproduce or test case**
Fail case:
1. Configure spring boot cache (see below)
2. Configure spring-boot-starter-data-redis (ip, port, db)
3. Use spring cache annotations on objects an methods
4. check /actuator/metrics
You won't see any cache metrics
 Success case:
1. Repeat all from Fail case (steps 1-3)
2. Register `RedissonCacheMeterBinderProvider` on your own
3. check /actuator/metrics
You will see cache.puts, cache.gets, cache.size metrics

**Redisson version**
redisson-spring-boot-starter - 3.13.0
redisson - 3.13.0

**Redisson configuration**
```
@Configuration
@EnableCaching
public class CacheConfiguration {
    @Bean
    public CacheManager cacheManager(RedissonClient redissonClient, AbacCacheProperties properties) {
        CacheConfig cacheConfig = new CacheConfig(properties.getTtl().toMillis(),
                properties.getMaxIdleTime().toMillis());
        cacheConfig.setMaxSize(properties.getMaxSize());

        Map<String, CacheConfig> configMap = Arrays.stream(CacheName.ALL)
                .collect(Collectors.toMap(Function.identity(), s -> cacheConfig));

        return new RedissonSpringCacheManager(redissonClient, configMap);
    }
}
```
**Solution**
Change conditions from
```
@Configuration
@AutoConfigureAfter(CacheAutoConfiguration.class)
@ConditionalOnBean({ CacheManager.class, RedissonCache.class })
@ConditionalOnClass(CacheMeterBinderProvider.class)
```
to
```
@Configuration
@AutoConfigureAfter(CacheAutoConfiguration.class)
@ConditionalOnBean(CacheManager.class)
@ConditionalOnClass({ CacheMeterBinderProvider.class, RedissonCache.class })
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
