### ISSUE TITLE
volumes for redis replica nodes in docker swaram environment?

### ISSUE THREAD

**Issue by kuldeepsidhu88** [redisson/redisson#2826]
We have an application in which we are using Redis as a small database.

We are using Redis in a master-slave configuration in docker swarm environment. We have **1 master node and 2 replica nodes**.

For persistent storage we have enabled volumes for master/replica nodes in docker swarm environment e.g if container restarts it can pick data from the volumes file on disk.

Few of my doubts are as below -
- Is it necessary to enable volumes for replica nodes?
- If we have volumes enabled for replica nodes, in a scenario when replica docker container restarts, will it pick its data from its volumes file on disk? or it ignores that file and only get data after syncing with master node?

Please let me know if you need more information.

**Comment by mrniko** [comment]
> Is it necessary to enable volumes for replica nodes?

No

> If we have volumes enabled for replica nodes, in a scenario when replica docker container restarts, will it pick its data from its volumes file on disk? or it ignores that file and only get data after syncing with master node?

Replica is synced with master on start.

**Comment by kuldeepsidhu88** [comment]
@mrniko If we add sentinel in this scenario, and I want to have persistence for my redis, in that case do we need to enable volumes for all nodes master and replica ?
I am thinking if actual master goes down and one of the replica becomes master, how can we have persistence in that case if we do not have volumes enabled for replica nodes?
