### ISSUE TITLE
support of aws unique reader endpoint for Redis

### ISSUE THREAD

**Issue by xercasy** [redisson/redisson#2830]
Hello,

Should I use useMasterSlaveServers for an AWS redis (1 master - 2 slaves) with an unique reader endpoint ([Amazon ElastiCache launches reader endpoints for Redis](https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticache-launches-reader-endpoint-for-redis/?nc1=h_ls))

here is my current configuration

    private static RedissonClient getAwsRedisClient(Config config, RedisModel redisModel) {
        DescribeReplicationGroupsRequest describeReplicationGroupsRequest = new DescribeReplicationGroupsRequest()
                .withReplicationGroupId(redisModel.getGroupName());

        NodeGroup nodeGroup = AmazonElastiCacheClientBuilder.defaultClient()
                .describeReplicationGroups(describeReplicationGroupsRequest)
                .getReplicationGroups()
                .stream()
                .map(ReplicationGroup::getNodeGroups)
                .flatMap(List::stream)
                .findFirst()
                .orElseThrow(IllegalArgumentException::new);

        checkArgument(Objects.nonNull(nodeGroup.getPrimaryEndpoint()), "primary endpoint is undefined");
        checkArgument(Objects.nonNull(nodeGroup.getReaderEndpoint()), "reader endpoint is undefined ");

       UnaryOperator<String> ENDPOINT = endpoint -> "redis://" + endpoint + ":" + REDIS_PORT;
        
        config.useMasterSlaveServers()
                .setReadMode(ReadMode.SLAVE)
                .setSlaveConnectionPoolSize(500) // 500
                .setMasterConnectionPoolSize(500)
                .setConnectTimeout(5000)
                .setPingConnectionInterval(1000)
                .setRetryInterval(50)
                .setRetryAttempts(1)
                .setSubscriptionConnectionPoolSize(1)
                .setMasterAddress(ENDPOINT.apply(nodeGroup.getPrimaryEndpoint().getAddress()))
                .setSlaveAddresses(singleton(ENDPOINT.apply(nodeGroup.getReaderEndpoint().getAddress())));

        return Redisson.create(config);
    }

Remember we haven't enabled the cluster mode .. We have only 1 master with 2 slaves. 
However we got 2 troubles

*
![redis](https://user-images.githubusercontent.com/65424314/84361299-bca71a00-abcb-11ea-8134-6f40a1118d4c.jpg)

(redis-2 is the primary, redis-1 and redis-3 are the slaves)
As you can see in the picture, the current connections between the 2 slaves are strange. I know there is load balacing between the 2 slaves. But why the connections fall back to 0 periodically ? Should I increase the maximum idle time of the connections before they are released ? 

* Then after the failover, 2 services failed to reconnect on the master node. Our other services had no problems with  the same configuration.
> 2020/06/09 21:58:45.308 ERROR [redisson-netty-5-10] o.r.c.DNSMonitor | Key= period= - Unable to find master entry for ....

It makes no sense to me because the unique primary endpoint and the unique reader endpoint have not changed ... Should I disabled the dns monitoring interval on the redis client ? 

let me know if you have answers to these troubles
Thanks

**Comment by mrniko** [comment]
You should use useReplicatedServers method instead and list define all redis nodes in configuration.

**Comment by xercasy** [comment]
Thanks for helping
We had some issues in the past after a redis failover with the useReplicatedServers method.
We will follow your advice and try this method again

**Comment by slovvik** [comment]
hi, @mrniko we come across the same issue. It seems like `useReplicatedServers ` is a workaround because when Redis on ElastiCache for some reason get down or restart, Redisson is not able to connect to the nodes again. It is the case when we upgrade the ElastiCache node type. Then we need to restart our application to let Redisson connect again.
