### ISSUE TITLE
Cluster Mode Configuration

### ISSUE THREAD

**Issue by akshitjain** [redisson/redisson#2835]
From this documentation: [https://github.com/redisson/redisson/wiki/2.-Configuration#24-cluster-mode](https://github.com/redisson/redisson/wiki/2.-Configuration#24-cluster-mode)
It is written for cluster mode "**Minimal cluster configuration requires to contain at least three master nodes**"

I want to understand why this limitation is there?
So overall if I have a cluster enable AWS elastic cache with single shard(1 master,2 Replicas) then i can't use cluster mode configuration?

**Comment by mrniko** [comment]
this statement is from Redis docs

**Comment by akshitjain** [comment]
@mrniko right this statement is there in the Redis docs as well. 
But the question still remains and is related to Redisson client:
So overall if I have a cluster enable AWS elastic cache with single shard(1 master,2 Replicas) then i can't use cluster mode configuration?
Also is there any formula on the basis of which shards should be increased eg. multiple of 3 etc.?

**Comment by mrniko** [comment]
No, you can. Since AWS elasticcache replicated differs from AWS elasticcache cluster.

**Comment by formanojhr** [comment]
Follow up on this question. Let us we decide to reshard and increase shards. Do we need to all all those new masters for extra shards?

**Comment by mrniko** [comment]
@formanojhr 

You can use any amount of cluster masters

**Comment by formanojhr** [comment]
@mrniko  is there a min of 3 (based on doc)? Also my question is there auto shard master identification by client or whenever a new shard is added we need to add that to Redisson client initialization?

**Comment by mrniko** [comment]
> Also my question is there auto shard master identification by client or whenever a new shard is added we need to add that to Redisson client initialization?

No, you don't need that. Redisson will detect it automatically.

**Comment by hrachtandilyan** [comment]
@mrniko looks like the requirement of at least three master nodes is removed from the docs recently: https://github.com/redisson/redisson/wiki/2.-Configuration/_compare/ef9c45db596abfa0d7ba2057b4b731e5a9af00d2...b878147c4302dc1d71703a0f8845ee4ebdf61dd5
also my experiments shown that using the **configuration endpoint for the cluster** instead of master nodes endpoints looks to be working as well. Can you please confirm if this is a correct approach of configuration?
