### ISSUE TITLE
Unable to acquire connection when all connections are free and nothing is in queue..

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#2836]
@mrniko on occasion we are seeing timeouts like this..

org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryIntervalNode source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xxx:6379], nodeType=MASTER, firstFail=0]]], command: (ZREVRANK), params: [xx, PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 256)] after 0 retry attempts
	at

from what I gather all connections are free, none are in queue yet it still didn't manage to acquire a connection.. does this indicate all Netty threads are busy decoding a response, in which case we should consider adopting the dedicated executor for decoding, or something else? Currently running redisson-3.11.5

**Comment by mrniko** [comment]
Did you try to increase nettyThreads setting?

**Comment by johnou** [comment]
oh right you marked decodeInExecutor as deprecated :)

**Comment by mrniko** [comment]
Yeah, decodeInExecutor is deprecated because of this https://github.com/redisson/redisson/issues/2646

**Comment by mrniko** [comment]
I reviewed the code and don't see any participant of netty thread here. This is why this setting is not mentioned.

**Comment by johnou** [comment]
@mrniko what ratio do you generally use for connection pool size vs netty event loop threads? docs say default 24 but java source looks like it is 64? https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/BaseMasterSlaveServersConfig.java#L56

**Comment by mrniko** [comment]
netty threads participate not only in connection creation but also writing into connection and Redis response decoding. It's hard to establish ratio

**Comment by johnou** [comment]
alright cool, i'll try tweaking those values and create a new issue if I observe something unexpected. thanks!

**Comment by yogurtzzz** [comment]
have you  solved this problem? @johnou

**Comment by johnou** [comment]
@yogurtzzz I think we helped this by changing the access strategy for a lot of the data fetched from Redis + prefer bulk API eg. https://github.com/redisson/redisson/pull/2999/

**Comment by yogurtzzz** [comment]
alright, I' ll look around and see. thx
