### ISSUE TITLE
AutoDiscover in Redisson

### ISSUE THREAD

**Issue by akshitjain** [redisson/redisson#2837]
I have a cluster mode enabled AWS Elastic cache with current configuration 1 shard(1 master 2 slaves) and i wan't to know that if i increase the shards count say to 2, would Redisson able to auto discover the newly added shard nodes?

As per this: [https://github.com/redisson/redisson/wiki/2.-Configuration#241-cluster-settings](https://github.com/redisson/redisson/wiki/2.-Configuration#241-cluster-settings)  Redisson only take the node addesses but AWS also provides the configuration endpoint but i don't see any option to provide that in Redisson.

**Comment by mrniko** [comment]
> I have a cluster mode enabled AWS Elastic cache with current configuration 1 shard(1 master 2 slaves) and i wan't to know that if i increase the shards count say to 2, would Redisson able to auto discover the newly added shard nodes?

Added nodes will be discovered only in AWS Elasticache Cluster not AWS Elasticache replicated mode
