### ISSUE TITLE
AWS elastic cache Shards support in Redisson

### ISSUE THREAD

**Issue by akshitjain** [redisson/redisson#2838]
I have a sharded AWS cluster enabled elastic cache with multiple shards.
I want to use the Redisson client to interact with my AWS Elastic Cache .
Can this be possible in OpenSource Redisson or it's possible only in Redisson pro?

Also it would be really helpful if you can share a sample code to connect to a sharded AWS elastic Cache using Redisson Client

**Comment by mrniko** [comment]
Just use AWS endpoint as node address in Redisson cluster config.
