### ISSUE TITLE
RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (LPOP) with params: [delayEventQueue-local]

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#2841]
I am getting below error while trying push a message to RDelayedQueue. Using Redission version 3.6.2. Any thoughts?

org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (LPOP) with params: [delayEventQueue-local] channel: [id: 0x1b6f637b, L:/127.0.0.1:50820 - R:/127.0.0.1:6379]

Also, below error pop up sometimes.

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=org.redisson.connection.SingleEntry@52d9b542], connection: [id: 0xb7d5d47c, L:/127.0.0.1:54223 - R:/127.0.0.1:6379], command: (EVAL), command params: [local result = {}; local items = redis.call('lrange', KEYS[1], 0, -1); for i, v in ipairs(items) do ..., 1, redisson_delay_queue:{delayEventQueue-local}] after 3 retry attempts

Below are my settings.

{
  "singleServerConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "password":null,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "address": "redis://127.0.0.1:6379",
    "subscriptionConnectionMinimumIdleSize":1,
    "subscriptionConnectionPoolSize":50,
    "connectionMinimumIdleSize":10,
    "connectionPoolSize":64,
    "database":0,
    "dnsMonitoringInterval":5000
  },
  "threads":16,
  "nettyThreads":32,
  "codec":null,
  "useLinuxNativeEpoll":false
}

**Comment by mrniko** [comment]
set `pingConnectionInterval` instead of `pingTimeout`
