### ISSUE TITLE
How to retrieve DelayedQueue by name using getDelayedQueue

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#2842]
Want to understand how to retrieve delayed queue (RDelayedQueue) by name using getDelayedQueue method on org.redisson.api.RedissonClient. 

Does it require to call redissonClient.getDelayedQueue(destinationQueue) every time before queuing a message as below or retrieve queue once and use it for every message queuing ?

RDelayedQueue..offer(message, delayInMillisFromCurrent, TimeUnit.MILLISECONDS);

**Comment by mrniko** [comment]
No, you can store RDelayedQueue instance and use it.

**Comment by anilkonduru** [comment]
@mrniko Thanks, that helps.
