### ISSUE TITLE
Is it possible to access to the data maintained or written by Redisson in Nodejs? And would it be a bad practice?

### ISSUE THREAD

**Issue by XLCYun** [redisson/redisson#2844]
Hi, I have using Redisson for not a long time, and I realize that I need my old project to access to Redis and retrieve data that is maintained by the current Java code which use Redisson. 
But Redisson is not just a redis client but a In-Memory Data Grid, therefore it's quite different and not compatible friendly for nodejs program for it only has pure redis client tools to use. 
So the idea I have is:
1. Write a Java Redisson program as a proxy and serve data for nodejs program. 
2. Figure out how Redisson save data, for sorted set, and Bucket, and write a package for nodejs to decode data from Redis. 
3. Give up Redisson and use pure redis client, like Redis. 

Is there any other solutions? Or is there any nodejs middleware for Redisson? Would that be difficult to write one for Redisson(I haven't read much source code of Redisson yet)? 
Thanks.

**Comment by mrniko** [comment]
Yes, you can use data stored by nodejs as long as you use the same codecs.

**Comment by mrniko** [comment]
> But Redisson is not just a redis client but a In-Memory Data Grid, therefore it's quite different and not compatible friendly for nodejs program for it only has pure redis client tools to use.

It's still remains redis client and compatible with others as long as they store the data in the same format.

**Comment by XLCYun** [comment]
> > But Redisson is not just a redis client but a In-Memory Data Grid, therefore it's quite different and not compatible friendly for nodejs program for it only has pure redis client tools to use.
> 
> It's still remains redis client and compatible with others as long as they store the data in the same format.

Hi, thanks for you reply. I see that Redisson use `Marshalling` Codec as default codec, and it store `true` as `"\x04P"` and `false` as `"\x04Q"`, and String `"A"` as ""\x04>\x01A"`.
I think these prefixes are added by `MarshallingCodec`, so are you saying I should write a nodejs program to decode these value if it's possible, or I should write a Codec on my own? 
Am I going to the right direction and which one should be preferred by your opinion? Thanks.

**Comment by mrniko** [comment]
You can use json codec, for example.

**Comment by XLCYun** [comment]
Locks maintained by Redisson might be bit tricky to cooperate with in Node.js. Use `JsonJacksonCodec` or other codec is easy for sharing data between different program written in different language. Issue closed, thanks for the help @mrniko .
