### ISSUE TITLE
org.redisson.client.RedisException: BUSY Redis is busy running a script.

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#2848]
We are using redis delay queue and see below error with around 20k message in queue.

org.redisson.client.RedisException: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.. channel: [id: 0x6186980c, L:/127.0.0.1:54603 - R:/127.0.0.1:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@16ae7198[Not completed], command=(LPOP), params=[delayEventQueue-local], codec=org.redisson.codec.JsonJacksonCodec@4631b499]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:266)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:126)

Below is the config.

{
  "singleServerConfig":{
    "idleConnectionTimeout":10000,
    "pingConnectionInterval":1000,
    "connectTimeout":10000,
    "timeout":3000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "password":null,
    "subscriptionsPerConnection":5,
    "clientName":null,
    "address": "redis://127.0.0.1:6379",
    "subscriptionConnectionMinimumIdleSize":1,
    "subscriptionConnectionPoolSize":50,
    "connectionMinimumIdleSize":10,
    "connectionPoolSize":64,
    "database":0,
    "dnsMonitoringInterval":5000
  },
  "threads":0,
  "nettyThreads":0,
  "codec":null,
  "useLinuxNativeEpoll":false
}

**Comment by mrniko** [comment]
I you need to reduce messages amount processed in script.

**Comment by anilkonduru** [comment]
@mrniko this is not a script. Polling for message on RQueue every 1 sec with a scheduler.

RQueue<AppData> readQueue = redissonClient.getQueue("qname");
**AppData data = readQueue.poll();**

I am seeing both issues mentioned below when there are good number (10000) messages on the queue.
1) "BUSY Redis is busy running a script." 
2) org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occurred for command:

**Comment by mrniko** [comment]
try to run SLOWLOG to get more info about slow scripts.
