### ISSUE TITLE
https://github.com/redisson/redisson/4.-data-serialization is broken

### ISSUE THREAD

**Issue by anilkonduru** [redisson/redisson#2850]
https://github.com/redisson/redisson/4.-data-serialization returning 404

**Comment by mrniko** [comment]
Where did you get this url?

**Comment by anilkonduru** [comment]
https://github.com/redisson/redisson/wiki/2.-Configuration

![image](https://user-images.githubusercontent.com/5466028/84978822-81d54280-b0f3-11ea-9bb7-6c5ed7dfbbb0.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
