### ISSUE TITLE
Is Redis Labs Enterprise Cluster (RLEC) officially supported?

### ISSUE THREAD

**Issue by derTobsch** [redisson/redisson#2852]
we are using redisson with en RLEC (https://redislabs.com/blog/introduction-to-redis-labs-enterprise-cluster-rlec/) it does work but not in every case, so the question is does redisson _officially_ support RLEC and when yes how should we configure it? Is there a example somewhere. If there is one and I could not find it, pleas give me a hint :)

**Comment by derTobsch** [comment]
Ok, I found it. (https://redisson.pro/ search for RLEC). So there are two different artifacts and only the pro version can talk to RLEC?

**Comment by mrniko** [comment]
Both versions are RLEC compatible.

**Comment by mrniko** [comment]
> it does work but not in every case

Which cases?

**Comment by derTobsch** [comment]
We do not exactly know at this point, but we are loosing sessions and therefore the redirect url that is saved at the session. I will not dig deeper to hopefully get to know redisson better. If you have a hint for me, that would be great.

**Comment by mrniko** [comment]
They take too much time for exection - about 30 minutes on fast multicore machine.
