### ISSUE TITLE
Issue with config when trying Tomcat Session Management

### ISSUE THREAD

**Issue by mnapoleonv** [redisson/redisson#2855]
I'm attempting to the RedissonSessionManager to handle sessions for tomcat.  I have setup the manager like this in my tomcat context.xml file
`Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="${catalina.base}/conf/redisson.yaml" readMode="MEMORY" updateMode="DEFAULT" />`

and created the following redisson.yaml file

`singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://<removed this>:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"`

With it set like this I get this error,......
`aused by: java.lang.NoSuchMethodError: org.nustaq.serialization.FSTConfiguration.getJsonFieldNames()Lorg/nustaq/serialization/coders/FSTJsonFieldNames;                at org.redisson.codec.FstCodec.copy(FstCodec.java:201)
                at org.redisson.codec.FstCodec.<init>(FstCodec.java:190)                ... 46 more`

I had to manually add the fst-2.47.jar as well as the objenesis-3.1.jar to get this and I'm kind of stuck now.

**Comment by mrniko** [comment]
starting from 3.13.0 MarshallingCodec is used by default and boundled with redisson-all.jar. So you don't need to add this codec manually.

**Comment by mnapoleonv** [comment]
Thanks for the update.
