### ISSUE TITLE
Logging: CommandAsyncService.get(RFuture<V> future) and InterruptedException

### ISSUE THREAD

**Issue by kazetsukaimiko** [redisson/redisson#2856]
We notice with small connection pool sizes under load that some promises seem to be interrupted or time out. This is normal behavior, but the root cause is omitted under the stack trace.

Redisson tries future.await(), catching the InterruptedException. In this case I believe future.isSuccess() is unlikely to return true, and convertException will be called. If InterruptedException is the cause for the future failing, we want to preserve that as part of the cause in the stack trace.

**Comment by kazetsukaimiko** [comment]
By stack trace, I mean the following exception is thrown without the InterruptedException in the cause:
**org.redisson.client.RedisException: Unexpected exception while processing command**

**Comment by mrniko** [comment]
future.isSuccess() can't return true in this case, since it was interrupted before result was set.
