### ISSUE TITLE
Why the redisson reconnected the connection  and still throw exceptions

### ISSUE THREAD

**Issue by 11800222** [redisson/redisson#2863]
config.setCodec(new StringCodec())
                .useSingleServer()
                .setAddress("redis://" + "******" + ":" + "6379")
                .setConnectionMinimumIdleSize(3)
                .setConnectionPoolSize(3)

using the latest version .
After debugging,I found that when the connection lost,redisson will try to reconnect and it do succeed,but it still throw an Exception.
I have try enlarging the timeout options,But it just idel there .Can somebody tell me how to solve this?

////////////////////////////////////////////

2020-06-20 17:41:58.529 [http-nio-18080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet].log:175 - USER: NULL_USER Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception 
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 29. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@491672465 [redisClient=[addr=redis://*******:6379], channel=[id: 0x1a073aa2, L:/192.168.0.111:60488 - R:/1******:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@326e8324(failure: java.util.concurrent.CancellationException)], command=(PSETEX), params=[user:token:secret:13560124863, 2592000000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 29, cap: 256)], codec=org.redisson.client.codec.StringCodec]], command: (PSETEX), params: [user:token:secret:13560124863, 2592000000, PooledUnsafeDirectByteBuf(ridx: 0, widx: 29, cap: 256)] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:200)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by wzh900521** [comment]
**hello, I use Redisson version is 3.13.1。but i can not to acquire lock。constantly refresh in the console**


22:34:26.535 [redisson-netty-8-17] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:26.535 [redisson-netty-8-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:26.613 [redisson-netty-11-17] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:26.613 [redisson-netty-11-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:26.676 [redisson-netty-14-17] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:26.676 [redisson-netty-14-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:31.322 [redisson-netty-2-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:31.322 [redisson-netty-2-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:31.455 [redisson-netty-5-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:31.455 [redisson-netty-5-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:31.537 [redisson-netty-8-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:31.537 [redisson-netty-8-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:31.615 [redisson-netty-11-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:31.615 [redisson-netty-11-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
22:34:31.677 [redisson-netty-14-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
22:34:31.677 [redisson-netty-14-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150

**Comment by 11800222** [comment]
> Which Redisson version do you use?

 3.13.1

**Comment by mrniko** [comment]
Try to set `pingConnectionInterval` setting
