### ISSUE TITLE
redisson 3.13.1 Always connected to redis cluster and can not to acquire lock,but no exception

### ISSUE THREAD

**Issue by wzh900521** [redisson/redisson#2865]
redis version:5.0.8
redisson version: 3.13.1

i have built redis cluster with six instance。and use cluster nodes to view clusters info。

81c9bd0505d0d610f3b059ef5027b8794f96b5bb 192.168.200.150:7004@17004 master - 0 1592836302435 5 connected 13107-16383

e60bd6fbe90da89dad41022a365d4e379b88ce8e 192.168.200.150:7000@17000 myself,master - 0 1592836298000 1 connected 0-3276

336b6c4f860a8a991e64768d4f71bd82e1f8e621 192.168.200.150:7001@17001 master - 0 1592836300420 2 connected 3277-6553

16f3ecdaff94e0bac2b017962107181f7238639b 192.168.200.150:7003@17003 master - 0 1592836301428 4 connected 9830-13106

55c193e6503d06592128a95e33dd422369efd859 192.168.200.150:7002@17002 master - 0 1592836301000 3 connected 6554-9829

but when i try to acquire redissonRedLock, i can not to acquire lock. the IDEA console info:
 [redisson-netty-8-17] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-8-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
 [redisson-netty-11-17] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-11-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
 [redisson-netty-14-17] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-14-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
 [redisson-netty-2-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-2-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
 [redisson-netty-5-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-5-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
 [redisson-netty-8-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-8-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
 [redisson-netty-11-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-11-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150
[redisson-netty-14-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: 192.168.200.150
 [redisson-netty-14-20] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: /192.168.200.150 for master host: 192.168.200.150

**Comment by mrniko** [comment]
RedLock is deprecated now in favor of RLock with slaves sync in clustere environment.
