### ISSUE TITLE
How Redisson figures out the key slot in cluster enabled Redis with multiple shards?

### ISSUE THREAD

**Issue by akshitjain** [redisson/redisson#2868]
Does Redisson maintains a map of all the slots available in each master node. Uses this map to figure out the relevant master for read and write and then queries that master?
Or
Does it queries a random master it gives the answer where the slot lies and then queries again the new master.

what is the hashing algorithm being used in Redisson?Just for confirmation it should be CRC16(Key)?
Does it hash the whole key or partial?

**Comment by mrniko** [comment]
> Does Redisson maintains a map of all the slots available in each master node. Uses this map to figure out the relevant master for read and write and then queries that master?

Here is how distribution model works https://redis.io/topics/cluster-spec#overview-of-redis-cluster-main-components

> Does it queries a random master it gives the answer where the slot lies and then queries again the new master.

It always uses correct master for particular key.

> what is the hashing algorithm being used in Redisson?Just for confirmation it should be CRC16(Key)?

It uses CRC16. Here is how it works https://redis.io/topics/cluster-spec#keys-hash-tags
