### ISSUE TITLE
redisson,The current thread does not release the lock, will hava some problems

### ISSUE THREAD

**Issue by ouyang2312** [redisson/redisson#2870]
yesterday,i test the redisson lock，i use  Apache JMeter to test the concurrency。param: thread number = 1000,  loop = 1。i found when i not release the lock .but other thread can get the lock.  

example:
![image](https://user-images.githubusercontent.com/35208452/85935098-46225000-b91f-11ea-8298-48496e72938f.png)

but i set params : thread number = 10,  loop = 1. No problem ....

**Comment by mrniko** [comment]
> when i not release the lock .but other thread can get the lock.

In your example, you set leaseTime = 30 seconds

**Comment by ouyang2312** [comment]
> > when i not release the lock .but other thread can get the lock.
> 
> In your example, you set leaseTime = 30 seconds

**Comment by ouyang2312** [comment]
> > 当我不释放锁。但是其他线程可以获得锁。
> 
> 在您的示例中，您将leaseTime设置为30秒



> > when i not release the lock .but other thread can get the lock.
> 
> In your example, you set leaseTime = 30 seconds

no i set leaseTime  = 3 ,There will still be problems。you can test it. Concurrent quantity = 1000

**Comment by mrniko** [comment]
in case of 1000 threads and lease time = 3 it's obvious that many of them never won't get the lock, due to small wait time = 5 seconds

**Comment by ouyang2312** [comment]
> in case of 1000 threads and lease time = 3 it's obvious that many of them never won't get the lock, due to small wait time = 5 seconds

but when i test 1000 concurrent ， Almost all threads succeeded in getting the lock

**Comment by mrniko** [comment]
> but when i test 1000 concurrent ， Almost all threads succeeded in getting the lock

Could you share test code example of this test?

**Comment by ouyang2312** [comment]
> > but when i test 1000 concurrent ， Almost all threads succeeded in getting the lock
> 
> Could you share test code example of this test?

![image](https://user-images.githubusercontent.com/35208452/85962789-2c4b4080-b9e5-11ea-8a54-6771abcb3df1.png)

**Comment by mrniko** [comment]
So, with lease time = 3 seconds test always pass?

**Comment by ouyang2312** [comment]
> So, with lease time = 3 seconds test always pass?

yes  As the picture shows

**Comment by mrniko** [comment]
Here is my test:

```java
        ExecutorService pool = Executors.newFixedThreadPool(1000);

        for (int i = 0; i < 1000; i++) {
            pool.execute(() -> {
               RLock lock = r.getLock("testConcurrency_SingleInstance");
               try {
                    if (lock.tryLock(5, 3, TimeUnit.SECONDS)) {
                        lockedCounter.incrementAndGet();
                     }
               } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
               }
            });
        }

        pool.shutdown();
        Assert.assertTrue(pool.awaitTermination(1, TimeUnit.MINUTES));
```
only two of threads will get a lock since at the moment of execution lease timeout didn't happen.

Use unlock method to unlock it in time.

**Comment by ouyang2312** [comment]
i use springboot web . you can test it by springboot . and use apache jmeter test&nbsp; http request .




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikita Koksharov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 下午2:28
收件人:&nbsp;"redisson/redisson"<redisson@noreply.github.com&gt;;
抄送:&nbsp;"欧阳"<1262014533@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [redisson/redisson] redisson,The current thread does not release the lock, will hava some problems (#2870)





 
Here is my test:
         ExecutorService pool = Executors.newFixedThreadPool(1000);         for (int i = 0; i < 1000; i++) {             pool.execute(() -&gt; {                RLock lock = r.getLock("testConcurrency_SingleInstance");                try {                     if (lock.tryLock(5, 3, TimeUnit.SECONDS)) {                         lockedCounter.incrementAndGet();                      }                } catch (InterruptedException e) {                     Thread.currentThread().interrupt();                }             });         }         pool.shutdown();         Assert.assertTrue(pool.awaitTermination(1, TimeUnit.MINUTES));
 
only two of threads will get a lock since at the moment of execution lease timeout didn't happen.
 
Use unlock method to unlock it in time.
