### ISSUE TITLE
RedissonBloomFilter NullPointerException

### ISSUE THREAD

**Issue by Pushuai** [redisson/redisson#2871]
**Expected behavior**
print error message
**Actual behavior**
java.lang.NullPointerException
**Steps to reproduce or test case**
/org/redisson/RedissonBloomFilter.java:185
            try {
                List<Boolean> result = (List<Boolean>) executorService.execute();

                for (Boolean val : result.subList(1, result.size()-1)) {
                    if (!val) {
                        return false;
                    }
                }

                return true;
            } catch (RedisException e) {
                if (!e.getMessage().contains("Bloom filter config has been changed")) {
                    throw e;
                }
            }
ex:
org.redisson.client.RedisMovedException AND message is null

**Redis version**
3.0.7
**Redisson version**
3.11.3
**Redisson configuration**
 ClusterServersConfig clusterServersConfig = config.useClusterServers();

**Comment by Pushuai** [comment]
Should judge whether message is empty

**Comment by mrniko** [comment]
Fixed
