### ISSUE TITLE
Don't release the lock actively, there is a problem in high concurrency

### ISSUE THREAD

**Issue by ouyang2312** [redisson/redisson#2872]
yesterday,i test the redisson lock，i use  Apache JMeter to test the concurrency。param: thread number = 1000,  loop = 1。i found when i not release the lock .but other thread can get the lock.  

example:
![image](https://user-images.githubusercontent.com/35208452/85939571-459eaf00-b949-11ea-9dd6-1767b600917f.png)

but i set params : thread number = 10,  loop = 1. No problem ....

**Comment by ouyang2312** [comment]
![image](https://user-images.githubusercontent.com/35208452/85962789-2c4b4080-b9e5-11ea-8a54-6771abcb3df1.png)

result:Most threads get locks

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/2870#issuecomment-650949288
