### ISSUE TITLE
RedissonAtomicLong#getAndSet throws NullPointerException when value does not exist yet

### ISSUE THREAD

**Issue by StefanLobbenmeier** [redisson/redisson#2874]
**Expected behavior**
Either no Exception (just create the value, getAndSet shoudl be able to create the value as well) or documented behaviour 

**Actual behavior**
Null Pointer Exception, but only during first execution. Reproducible if I manually delete the value in Redis again

**Steps to reproduce or test case**
My code looked like that:
```java
        RAtomicLong counterInDb = redissonClient.getAtomicLong(COUNTER);
        if (counterInDb != null)
            return counterInDb.getAndSet(0);
        else {
            return 0;
        }
```
When the value does not exist yet, counterInDb is not null but calling getAndSet on it without checking isExists as well in the if gives me a NullPointerException at RedissonAtomicLong.java:122. This is quite confusing as 
1) The Null Pointer Exception is from the implicit cast from Long to long, which makes it really hard to spot
2) There is no JavaDoc warning that this might happen

**Redis version**
docker.io/bitnami/redis:6.0.5-debian-10-r10

**Redisson version**
3.13.1

**Redisson configuration**
```java
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://redis-kube-master.default.svc.cluster.local:6379")
                .setPassword(getRedisPassword());
```

**Comment by StefanLobbenmeier** [comment]
For anyone else having this problem a simple check to isExists resolves the issue, but this should be fixed anyway:
```java
        if (counterInDb != null && counterInDb.isExists())
            return counterInDb.getAndSet(0);
        else {
            return 0;
        }
```

**Comment by mrniko** [comment]
Fixed!
