### ISSUE TITLE
Redis native commands are not supported using redisson client

### ISSUE THREAD

**Issue by shashanka981** [redisson/redisson#2877]
I wanted to run Redis Native commands using redisson provided low-level client, However.  Some of the commands i see not exposed from RedisCommands.java are: 

**HASH COMMANDS Not supported** 
HINCRBY
HINCRBYFLOAT
HMGET

**STRING COMMANDS NOT SUPPORTED** 
BITFIELD
BITOPS
DECRBY
SETEX 
STRALGO

I just explored String and Hash commands, however list of commands not supported might be more. 

Usage:
 RedisClient redisClient = RedisClient.create(new RedisClientConfig().setAddress("redis://localhost:6379"));
 RedisConnection conn = redisClient.connect();
 conn.async(StringCodec.INSTANCE, RedisCommands.MSET, "keys1","values1","keys2","values2");

a) Is there are way i can actually run the redis native commands via some interfaces ?
b) Any reason why redisson is not exposing complete set of redis native commands ?  Does Redisson make any effort on a regular basis to support new commands that are offered by Redis   ?

**Comment by mrniko** [comment]
> HASH COMMANDS Not supported

You can see how they used in RedissonMap object.

> STRING COMMANDS NOT SUPPORTED

RedisCommands#BITOP
SETEX is used in RedissonBucket object.

Anyway you can always create RedissonCommand and implement missed command.

**Comment by shashanka981** [comment]
For my usecase, i was actually interested to not do anything beyond inserting a hash entry. However RMap does lot of things which may be a overhead for my usecases.

You said "Anyway you can always create RedissonCommand and implement missed command."
Can you point to some documentation about the usage of this interface. I cant find any interface/class by name RedissonCommand

**Comment by mrniko** [comment]
> Can you point to some documentation about the usage of this interface

I'm afraid there is no such documentation at the moment.

> However RMap does lot of things which may be a overhead for my usecases.

For example?

**Comment by shashanka981** [comment]
"I'm afraid there is no such documentation at the moment."
       Can you give the correct name of the class/interface ?

"However RMap does lot of things which may be a overhead for my usecases."
I was actually looking for a one-one mapping from redis command to redisson command , all exposed from single interface/class so that i am actually sure there we are doing a minimal exection needed. From the code, i see RMap seems to be reasonably doing minimal though. 

Other question i had:
If i had to use RBucket for taking advantage of Redis Strings structure, Which method would actually translate to MGet , Mset -  getting/setting multiple keys in a single invocation

**Comment by khojir** [comment]
> "I'm afraid there is no such documentation at the moment."
> Can you give the correct name of the class/interface ?

There is an interface that its name is "RedisCommands". Maybe it can give you an idea about what you are looking for.
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.15.0</version>
        </dependency>
```
