### ISSUE TITLE
Better support for subclassing RedissonRegionFactory

### ISSUE THREAD

**Issue by MattiasJa** [redisson/redisson#2878]
Hi, to configure redisson for hibernate only using code (like env variables) i subclass the RedissonRegionFactory and override method createRedissonClient. This works great until i want to take advantage of the property `hibernate.cache.redisson.fallback`. This property has private access so i cant alter it in the same way as the base class do. My only way forward is via reflections which is hackish...
Could you provide a protected setter or refactor code for fallback-setting to a protected method? Also allow for inheritance in the future. Thanks!

My code as follow (CacheManager is configured elsewhere)
```
public class CodeConfigRedissonRegionFactory extends org.redisson.hibernate.RedissonRegionFactory {

    @Override
    protected RedissonClient createRedissonClient(Map properties) {
        String host = System.getenv(……..);
        String password = System.getenv(………..);
        Config config = RedisCacheConfig.buildConfig(host, password);
        String fallbackValue = (String) properties.getOrDefault(FALLBACK, "false");

        // Base class has private attributes... Hack until fixed!
        try {
            java.lang.reflect.Field privateField = this.getClass().getSuperclass().getDeclaredField("fallback");
            privateField.setAccessible(true);
            privateField.set(this, Boolean.valueOf(fallbackValue));
        } catch (Exception e) {...}
        return Redisson.create(config);
    }
}
```

**Comment by mrniko** [comment]
Thanks for suggestion! Done
