### ISSUE TITLE
hibernate 2LC, multiple tomcat node is causing flush on each node join to cluster

### ISSUE THREAD

**Issue by 4fath** [redisson/redisson#2880]
hi everybody,

I am experiencing unexpected behaviour(at least from my perspective) when I try to use RedissonRegionFactory. 
what I am trying to do is:
- I have a clustered application and all of my nodes are using same database, and I was configured ehcache for second level cache on each node, and when something happened on one entity, I was sending an event to other nodes for evict their 2LC to keep data consitenct over the cluster.  Now I try to replace that eh_cache + event system with one central 2lc provider. 

for that surpose,  first node is connecting and configuring redis on its startup.
how I am configuring redis:
- providing redisson.yaml
- putting entity and query configurations as follows.;
-- for instance my entity is `com.fatih.example.A` : max-size 100, TTL: 600sec, TTIO: 600sec. I am adding configurations like this: 
`hibernatePropMap.put(hibernate.cache.redisson.com.fatih.example.A.eviction.max_entries, 100) `
`hibernatePropMap.put(hibernate.cache.redisson.com.fatih.example.A.expiration.time_to_live, 600)`
`hibernatePropMap.put(hibernate.cache.redisson.com.fatih.example.A.expiration.max_idle_time, 600)`
-- for some custom queries,
`hibernatePropMap.put(hibernate.cache.redisson.query.customField.eviction.max_entries, 100)`
`hibernatePropMap.put(hibernate.cache.redisson.query.customField.expiration.time_to_live, 1800)`
`hibernatePropMap.put(hibernate.cache.redisson.query.customField.expiration.max_idle_time, 1800)`

after first node startup is completed I put a flag on redis to avoid second configuration from other nodes. like 2lc-applied=true
I am able to see redis keys/values like this:
```
redis-cli > hgetall "com.fatih.example.A"
1) some hex key
2) some hex value
redis-cli > zrange "redisson__idle__set:{com.fatih.example.A}" 0 1
1) "\x04\x04\t>3org.hibernate.cache.internal.CacheKeyImplementation . . ."
redis-cli > zrange "redisson__map_cache__last_access__set:{com.fatih.example.A}" 0 1
1)  "\x04\x04\t>3org.hibernate.cache.internal.CacheKeyImplementation . . ."
```

after started to second node (which is not doing any configuraiton on redis, it is just connecting it via provided rdisson.yaml), when I check keys/values, they are gone as follows;
```
redis-cli > hgetall "com.fatih.example.A"
(empty array)
redis-cli > zrange "redisson__idle__set:{com.fatih.example.A}" 0 1
(empty array)
redis-cli > zrange "redisson__map_cache__last_access__set:{com.fatih.example.A}" 0 1
(empty array)
```

I would be appreciated for any idea advice whatever to help to understand why this behave like this.

**Comment by mrniko** [comment]
Redisson doesn't clear hibernate cache on it's own.

**Comment by 4fath** [comment]
hi @mrniko, thank you for narrowing down to issue.

I did debug and it seems there are some `RedissonStorage#evictData` calls. they are all implict calls on second node, I mean I am not calling anything explicity. just running two different tomcat nodes on same jvm.  also using JPA implementation EntityManagerFactory, not hibernate sessionFactory itself. (idk this is related or not)

**Comment by mrniko** [comment]
Did you trace where this method get invoked?

**Comment by 4fath** [comment]
yes, root point is second node has some **native queries** which does not have `addSynchronizedEntityClass(Class) or addSynchronizedQuerySpace(Sring)` definetions. and whenever one of the native queries are triggered, all caches were flushing.
now, I will try to add `addSynchronizedEntityClass and addSynchronizedQuerySpace` with related entity and query regions. this will probably help a lot.

but now I have another question related with that. native queries were flushing everything, ok. flushing the entity data or query data is okay. however, why is it flushing entity based settings for example redisson_options: max-size? I was aldready defined that settings on entityManagerFactory initialization. after every native query call, should I again connect to redis and put some configuration settings like max-size or ttl for specific entity?

**Comment by mrniko** [comment]
>  why is it flushing entity based settings for example redisson_options: max-size? 

Fixed in https://github.com/redisson/redisson/issues/2884
