### ISSUE TITLE
“SlaveConnectionPool no available Redis entries ”  How to solve this problem（这种报错应该如何解决？）

### ISSUE THREAD

**Issue by hyuans** [redisson/redisson#2881]
情况是这样：我们有6个一样的springboot 服务，其中1个服务报出了这种错误，看源码好像有点像 主节点被当成从节点时，会报这种错误

the situation ：We have six of the same springboot app，One of them reported a mistake，This mistake is a bit like the master node is treated as a slave node by Read the source code

2020-07-01 14:41:33,226 [http-nio-22206-exec-7] ERROR c.s.c.w.e.GlobalExceptionHandler.defaultErrorHandler(GlobalExceptionHandler.java:122) - Unexpected error msg:SlaveConnectionPool no available Redis entries. Master entry host: /172.28.50.76:9001 Disconnected hosts: [/172.28.50.76:9001]
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: /172.28.50.76:9001 Disconnected hosts: [/172.28.50.76:9001]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:218)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:254)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:480)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:641)
        at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:643)
        at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
        at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Redis version**
4.0.14
**Redisson version**
3.13.1
**Redisson configuration**
spring.redis.master.connectionPoolSize = 200
spring.redis.slave.connectionPoolSize = 400
spring.redis.slave.connectionMinimumIdleSize = 100
spring.redis.connectTimeout = 5000
spring.redis.timeout = 5000
spring.redis.slaveFailsInterval = 180000
spring.redis.pingConnectionInterval = 30000

clusterServersConfig.setMasterConnectionPoolSize(this.masterConnectionPoolSize);
clusterServersConfig.setSlaveConnectionPoolSize(this.slaveConnectionPoolSize);
clusterServersConfig.setSlaveConnectionMinimumIdleSize(this.slaveConnectionMinimumIdleSize);
clusterServersConfig.setConnectTimeout(this.connectTimeout);
clusterServersConfig.setTimeout(this.timeout);
Redisson.create(config);

**Comment by hyuans** [comment]
the redis server can reachable
ping 172.28.50.76
PING 172.28.50.76 (172.28.50.76) 56(84) bytes of data.
64 bytes from 172.28.50.76: icmp_seq=1 ttl=63 time=0.237 ms
64 bytes from 172.28.50.76: icmp_seq=2 ttl=63 time=0.222 ms
64 bytes from 172.28.50.76: icmp_seq=3 ttl=63 time=0.243 ms
64 bytes from 172.28.50.76: icmp_seq=4 ttl=63 time=0.326 ms
64 bytes from 172.28.50.76: icmp_seq=5 ttl=63 time=0.260 ms
64 bytes from 172.28.50.76: icmp_seq=6 ttl=63 time=0.214 ms
64 bytes from 172.28.50.76: icmp_seq=7 ttl=63 time=0.261 ms
64 bytes from 172.28.50.76: icmp_seq=8 ttl=63 time=0.267 ms
64 bytes from 172.28.50.76: icmp_seq=9 ttl=63 time=0.268 ms
64 bytes from 172.28.50.76: icmp_seq=10 ttl=63 time=0.308 ms
64 bytes from 172.28.50.76: icmp_seq=11 ttl=63 time=0.487 ms
64 bytes from 172.28.50.76: icmp_seq=12 ttl=63 time=0.286 ms
64 bytes from 172.28.50.76: icmp_seq=13 ttl=63 time=0.251 ms
64 bytes from 172.28.50.76: icmp_seq=14 ttl=63 time=0.267 ms
64 bytes from 172.28.50.76: icmp_seq=15 ttl=63 time=0.312 ms
^C
--- 172.28.50.76 ping statistics ---
15 packets transmitted, 15 received, 0% packet loss, time 14979ms
rtt min/avg/max/mdev = 0.214/0.280/0.487/0.065 ms

**172.28.50.76:9001> info**
# Server
redis_version:4.0.14
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:8eadcbd70c3de51c
redis_mode:cluster
os:Linux 3.10.0-327.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:24685
run_id:bf4debde658d3c99db8c749f0d62093193f0c112
tcp_port:9001
uptime_in_seconds:11329686
uptime_in_days:131
hz:10
lru_clock:16533931
executable:/opt/soft/redis-server
config_file:/usr/local/redis/cluster/redis_9001.conf

# Clients
connected_clients:3773
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:784102584
used_memory_human:747.78M
used_memory_rss:1215586304
used_memory_rss_human:1.13G
used_memory_peak:1081159936
used_memory_peak_human:1.01G
used_memory_peak_perc:72.52%
used_memory_overhead:210400852
used_memory_startup:1444976
used_memory_dataset:573701732
used_memory_dataset_perc:73.30%
total_system_memory:10317406208
total_system_memory_human:9.61G
used_memory_lua:41984
used_memory_lua_human:41.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.55
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:5999
rdb_bgsave_in_progress:0
rdb_last_save_time:1593592198
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:8
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:832917504
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:10
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:862941184
aof_current_size:1118496754
aof_base_size:629449280
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:28227061
total_commands_processed:667449507
instantaneous_ops_per_sec:357
total_net_input_bytes:68710570983
total_net_output_bytes:133818584425
instantaneous_input_kbps:27.31
instantaneous_output_kbps:29.03
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:1
expired_keys:31891462
expired_stale_perc:5.28
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:159458647
keyspace_misses:31907662
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:17582
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:1
slave0:ip=172.28.50.77,port=9004,state=online,offset=69642483237,lag=1
master_replid:d1ffbbedc26bf93ec3fdd6d31670020a98256dcd
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:69642507971
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:69641459396
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:36464.79
used_cpu_user:31424.13
used_cpu_sys_children:15972.36
used_cpu_user_children:163128.12

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=1164465,expires=1164408,avg_ttl=147873388


**172.28.50.76:9001> CLUSTER INFO**
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:7
cluster_my_epoch:1
cluster_stats_messages_ping_sent:11243274
cluster_stats_messages_pong_sent:11279976
cluster_stats_messages_fail_sent:10
cluster_stats_messages_sent:22523260
cluster_stats_messages_ping_received:11279971
cluster_stats_messages_pong_received:11243268
cluster_stats_messages_meet_received:5
cluster_stats_messages_fail_received:2
cluster_stats_messages_auth-req_received:1
cluster_stats_messages_received:22523247

**172.28.50.76:9001> CLUSTER NODES**
26035c60d8fb28c5c89223d16ad0137391ce9215 172.28.50.76:9001@19001 myself,master - 0 1593592288000 1 connected 0-5460
5645e3ec3e36ef18f401638a92e8c4eb50916f74 172.28.50.78:9006@19006 slave 48dab161ad1f1469a5c6e328b27b14f278f794ac 0 1593592288815 6 connected
48dab161ad1f1469a5c6e328b27b14f278f794ac 172.28.50.77:9003@19003 master - 0 1593592287809 3 connected 5461-10922
23f13de551bd4d504899a411bc6322475861ac79 172.28.50.78:9005@19005 master - 0 1593592288000 5 connected 10923-16383
8fdd79d601e026864db2b39e0c781a356c6518c5 172.28.50.77:9004@19004 slave 26035c60d8fb28c5c89223d16ad0137391ce9215 0 1593592289827 4 connected
93c33822d10d104adb76ff3d27cde85bdbde11c8 172.28.50.76:9002@19002 slave 23f13de551bd4d504899a411bc6322475861ac79 0 1593592287000 5 connected

**Comment by mrniko** [comment]
Are there steps to reproduce this?

**Comment by hyuans** [comment]
it is hard to reproduce，This only happens on some servers in the production environment，not all
at first I suspect there is something wrong with the network
but It's a little strange that other applications on the same server are working normally

**Comment by hyuans** [comment]
@Bean
	public RedissonClient redisson() {
		String[] hosts = this.redissonNodes.split(",");
		List<String> nodeList = new ArrayList<String>();
		for (String node : hosts) {
			nodeList.add("redis://" + node);
		}
		Config config = new Config();
		config.setCodec(new org.redisson.client.codec.StringCodec());
		ClusterServersConfig clusterServersConfig = config.useClusterServers().addNodeAddress(nodeList.toArray(new String[nodeList.size()]));
		if (this.redissonPassword != null && !"".equals(this.redissonPassword)) {
			clusterServersConfig.setPassword(this.redissonPassword);
		}
		clusterServersConfig.setMasterConnectionPoolSize(this.masterConnectionPoolSize);
		clusterServersConfig.setSlaveConnectionPoolSize(this.slaveConnectionPoolSize);
		clusterServersConfig.setSlaveConnectionMinimumIdleSize(this.slaveConnectionMinimumIdleSize);
		clusterServersConfig.setConnectTimeout(this.connectTimeout);
		clusterServersConfig.setTimeout(this.timeout);
		return Redisson.create(config);
	}

@Autowired
private RedissonClient redissonClient;

//get hash value
RMap<String, Object> rMap = redissonClient.getMap(“xxxx”);
Object xxx = rMap.get("xxx");

The above code is based on Redisson version 3.10.6

172.28.50.77:9003 is master node

2020-07-01 08:57:19,656 [http-nio-22206-exec-25] ERROR c.s.c.w.e.GlobalExceptionHandler.defaultErrorHandler(GlobalExceptionHandler.java:122) - Unexpected error msg:SlaveConnectionPool no available Redis entries.  Disconnected hosts: [172.28.50.77/172.28.50.77:9003]
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts: [172.28.50.77/172.28.50.77:9003]
        at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:219)
        at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:249)
        at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:482)
        at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:597)
        at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:850)
        at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:670)
        at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:760)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hyuans** [comment]
It recovered after my colleague reinstall redis

**Comment by formyjava** [comment]
i  had the same problem few days ago and my colleague told me ,maybe i should update the config like this
//update the topology changes when the master and slaver swithed
        ClusterTopologyRefreshOptions clusterTopologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .enableAdaptiveRefreshTrigger()
                .enablePeriodicRefresh(Duration.ofSeconds(5))
                .build();

**Comment by mrniko** [comment]
@formyjava 

You need to update to 3.17.6 version which fixes this issue or to the latest one.
