### ISSUE TITLE
sentinel more failure ,You can't write against a read only replica..

### ISSUE THREAD

**Issue by Shmily1018** [redisson/redisson#2889]
use redisson sentinel mode
sentinel 
**Expected behavior**
work fine
**Actual behavior**
org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0xa1a322cd L:/**.**:** - R:********] command: (EVAL), params: [if (redis.call('exists',KEYS[1])==0 then redis.call('hset',KEYS[1],ARGV[2],1)];redis.call('pr... ,1,
**Steps to reproduce or test case**
 Config config = new Config();
        config.useSentinelServers();
....

config file:
redisson:
  sentinel:
    addresses:
      - redis://**:26379
      - redis://**:26379
      - redis://**:26379
    password: ********
    master-name: mymaster
    ping-connection-interval: 5000
    keep-alive: true
    timeout: 10000
    master-connection-minimum-idle-size: 10
    slave-connection-minimum-idle-size: 10
**Redis version**
Redis version=5.0.5, bits=64,
**Redisson version**
3.9.1
**Redisson configuration**

**Comment by mrniko** [comment]
Did you try 3.13.2 version?

**Comment by Shmily1018** [comment]
> Did you try 3.13.2 version?

3.9.1 have some bugs for sentinel mode?

**Comment by mrniko** [comment]
I'm unable to reproduce the issue with 3.13.2 version

**Comment by mrniko** [comment]
Also make sure that Sentinel configured correctly.

**Comment by Shmily1018** [comment]
Let me try
