### ISSUE TITLE
Unable to decode data. channel: [id: 0x34a72ba5, L:/xxxxxxx - R:xxxxxxxx], reply: ReplayingDecoderByteBuf(ridx=88, widx=88) java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by alexpassionate** [redisson/redisson#2892]
spring boot version 2.0.4
redisson version 3.11.6

used redisson  RedissonDelayedQueue

Unable to decode data. channel: [id: 0x34a72ba5, L:/xxxxxxx - R:xxxxxxxx], reply: ReplayingDecoderByteBuf(ridx=88, widx=88) java.lang.NullPointerException: null

thanks for your help

**Comment by mrniko** [comment]
make sure you don't share the same name between different Redisson objects.

**Comment by alexpassionate** [comment]
> make sure you don't share the same name between different Redisson objects.

how to make sure share the same name between different Redisson objects ?

**Comment by mrniko** [comment]
This should be checked on application side not Redisson

**Comment by alexpassionate** [comment]
> This should be checked on application side not Redisson

What represents sharing the same name and being a queue object? What the program should do.

**Comment by alexpassionate** [comment]
Reporting this error can affect data loss.

**Comment by mrniko** [comment]
Can you provide test code to reproduce this?
