### ISSUE TITLE
Redisson stable versions are which are suitable for production environments ? （哪一个版本适用于生产环境）

### ISSUE THREAD

**Issue by yx726843014** [redisson/redisson#2894]

**Comment by mrniko** [comment]
latest version

**Comment by yx726843014** [comment]
redisson too many netty-io thread ,   how to configure

> latest version

**Comment by mrniko** [comment]
there is a reason for this https://github.com/redisson/redisson/wiki/16.-FAQ#q-i-saw-a-redistimeoutexception-what-does-it-mean-what-shall-i-do-can-redisson-team-fix-it

**Comment by yx726843014** [comment]
> latest version

3.12.5  version is stable    ?
Whether there are significant bugs ?

**Comment by mrniko** [comment]
Please review changelog https://github.com/redisson/redisson/blob/master/CHANGELOG.md
