### ISSUE TITLE
RRateLimiter doesn't work

### ISSUE THREAD

**Issue by Johnson-Jia** [redisson/redisson#2895]
Hi,

I have created RRateLimiter instance.  If I call acquire (), it doesn't work.

RRateLimiter limiter = redisson.getRateLimiter("test.rate.limit.do");
// Initialization required only once.
// 5 permits per 50 seconds
limiter.tryAcquire(RateType.OVERALL, 5, 50, RateIntervalUnit.SECONDS);
limiter.acquire();

**Comment by mrniko** [comment]
You need to call `trySetRate` method before and not `tryAcquire`
