### ISSUE TITLE
Strange characters on value when read data in other language

### ISSUE THREAD

**Issue by daviddelucca** [redisson/redisson#2897]
Hey there!

I was wondering if it's possible to perform a simple operation like we do on Redis StackExchange (c#) client:

```
IDatabase db = redis.GetDatabase();
string value = "abcdefg";
var expires = 1000;
db.StringSet("mykey", value, expires);
...
string value = db.StringGet("mykey");
Console.WriteLine(value); // writes: "abcdefg
```

Right now I'm using a Map but I would like to make it simple as this example on C#. 

```
    override fun put(collection: String, key: String, value: String, expiresInSeconds: Long) {
        logger.info("Storing key $key into collection $collection")
        val cacheMap = getMapCache(collection)

        cacheMap.put(key, value, 3600, TimeUnit.SECONDS)
    }

    private fun getMapCache(collection: String) = redissonClient.getMapCache<String, String>("any", StringCodec())
```

When I try to retrieve values fro other clients like C# or Python, I got some strange characters on value like `????????�??????myvalue`.

Is there any option to clear/remove those characters on Redisson and store it as plain string?

Is there any option to store it simple as we do in C#?

**Comment by mrniko** [comment]
Here is how you can do the same with Redisson:

```java
RBucket b = redisson.getBucket("mykey", StringCodec.INSTANCE);
b.set("value", 1, TimeUnit.SECONDS);

b.get(); // = "value"
```

> When I try to retrieve values fro other clients like C# or Python, I got some strange characters on value like ????????��??????myvalue.

Because default Redisson codec is `MarshallingCodec`

**Comment by daviddelucca** [comment]
Is possible to remove those characters or create a custom codec?

**Comment by mrniko** [comment]
You can use StringCodec instead

**Comment by daviddelucca** [comment]
Thank you very much!
