### ISSUE TITLE
Indexes of an RLO in Redis

### ISSUE THREAD

**Issue by eliveltonp95** [redisson/redisson#2900]
I do the Persistence of a RLO with some indexes, and I have a time for it to expire, however the indices, never disappear from the memory of the redis, can anyone help?

```

@REntity
public class MyObject {

    @RId(generator = LongGenerator.class)
    private Long id;

    @RIndex
    private String name;
}

public MyObject save(MyObject obj) {
        RLiveObjectService service = redissonClient.getLiveObjectService();
        var objPersist = service.persist(obj);
        var expireTime = 1L;

        RLiveObject liveObject = service.asLiveObject(objPersist);
        liveObject.expire(expireTime, TimeUnit.MINUTES);
        return objPersist;
}
```

After 1 minute, the object is removed from the redis, OK ... but the indeces are not

**Comment by dengliming** [comment]
@eliveltonp95 Hi~ How do you know it wasn't removed? You only provide the `save` method. Can you provide the code that you tested to see that it was not deleted?

**Comment by yangwn** [comment]
When you set the expire function, it just for LiveObject, rather than Index.
So, if you want to remove its the index, you must remove it manually.

```
LiveParticipant liveParticipant = new LiveParticipant();
liveParticipant.setId(String.valueOf(i));
liveParticipant = liveParticipantTemplate.attach(liveParticipant);
liveParticipantTemplate.removeObject(liveParticipant);
```

MUST BE set the @RID for the LiveObejct.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2625
