### ISSUE TITLE
Why the value of the lock >1?

### ISSUE THREAD

**Issue by 534519560** [redisson/redisson#2903]
redisson-version：3.13.2

I have three servers ,in order to ensure that only one  scheduled task is executed at the same time,
I use lock like this:

` 
@Scheduled(cron = "0/10 * * * * ? ")
    public void saveArticleReading() throws InterruptedException {
        RLock taskLock = redisUtil.getLock("lock:ScheduledTask:saveArticleReading");
        if (taskLock.tryLock()) {
            try {
           //do something
            } finally {
                taskLock.unlock();
            }
        }

    }
`

But after a while, the value of lock >1, 
![image](https://user-images.githubusercontent.com/33799740/86984791-23672580-c1c2-11ea-8f3b-4baa081eee34.png)

Although it will not cause an error.But I'm curious about how it happened.
I use Junit to test it:
`  
@Test
    public void testLock() {

        for (int i = 0; i < 3; i++) {
            new Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    RLock lock = redissonClient.getLock("testLock");
                    if (lock.tryLock()) {

                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        } finally {
                            lock.unlock();
                        }

                    }
                }
            }, 0, 5);
        }

        CountDownLatch latch = new CountDownLatch(1);
        try {
            latch.await();
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
`

But it didn't reappear.

**Comment by yydzxz** [comment]
your thread which id is 185 get the clock. if the 185 thread execute `taskLock.tryLock()` again, the value of lock will increase.
