### ISSUE TITLE
RedissonResponseTimeoutException in HSCAN 

### ISSUE THREAD

**Issue by avisek1269** [redisson/redisson#2913]
The application is throwing RedissonResponseTimeoutException. It is happening when Redisson fires HSCAN command because the code is iterating over HashMap with size of 8.5k entries. Below is the exception message

`org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (6000 ms) occured after 6 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (HSCAN)`

I tried increasing the netty thread to 64 and retryAttempts to 6 and timeout time to 6000.

Redisson version : 3.12.5
Redis version: 5

**Comment by mrniko** [comment]
does it happen only with hscan command? what is the size of data it returns? it might be network delay due to size of transferred data.

**Comment by avisek1269** [comment]
Thanks @mrniko for looking into this. 
I am getting this exception only with HSCAN.
The complete scenario here is - 
I am getting RMap reference and then Iterating over it. This RMap has almost 8.5k entries. So what I suspect is Its making so many network calls to fetch entries to iterate over map and eventually being timedout. What do you suggest @mrniko ?

**Comment by mrniko** [comment]
The problem is that map entries are too big. Try to use `RMap.entrySet(2)` method

**Comment by avisek1269** [comment]
Actually this exception is not consistent. 
Yes, I will try this method and will let you know the result.  Thanks @mrniko .

**Comment by avisek1269** [comment]
So, it seemed it was because of long operation on this huge hashmap. So, in order to handle this, I did refactor the code to reduce.
