### ISSUE TITLE
IllegalArgumentException: RIVER

### ISSUE THREAD

**Issue by huseyincanErbayraktar** [redisson/redisson#2917]
Hello,

I use Redisson with Spring Boot Project. While RedissonClient bean is created, IllegalArgumentException: RIVER is thrown. The problem is at MarshallingCodec.java:214 because my computer's language is Turkish. In Turkish, the lowercase of "I" is "ı"(without a dot) instead of "i"(with a dot). Therefore, "rıver"(without a dot) is not found.

I think, toLowerCase() method at MarshallingCodec.java:214 should be toLowerCase(Locale.ENGLISH).

Have a nice day.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/67f602f2a6278cb794696e1ded67209fde83db0e
