### ISSUE TITLE
Object Listener - question

### ISSUE THREAD

**Issue by uselvvi** [redisson/redisson#2922]
Hi,
Thanks for creating this great library! You also have a great wiki! 

Is there any thing wrong with this code? This is a simple example. 
I expect the delete event should get triggered. But It does not seem to work. 

```
        Config config = Config.fromYAML(new File("config.yaml"));
        RedissonClient redisson = Redisson.create(config);
        RBucket<Object> bucket = redisson.getBucket("bucket");
        bucket.addListener(new DeletedObjectListener() {
            @Override
            public void onDeleted(String s) {
                System.out.println("Deleted :: " + s);
            }
        });
        bucket.set("hi");
        bucket.delete();
```

Thanks.

**Comment by doctorpangloss** [comment]
I have the same issue. Neither `expired` nor `deleted` listeners are getting events for `RBucket`.

**Comment by mrniko** [comment]
set Redis `notify-keyspace-events` =  `Eg`

**Comment by LiviuSabau** [comment]
Thanks, this worked for me!
See here how to do it: https://linuxhint.com/enable-redis-keyspace-notification/
