### ISSUE TITLE
RRatelimiter - Can the method of delete and  trySetRate  support in a transaction ?

### ISSUE THREAD

**Issue by zhangkeyi** [redisson/redisson#2924]
**Problem:**
In a production environment, we often deploy more than one application for high availability (HA). There are two steps: delete and trySetRate when update the RRatelimit object. In HA architecture, there will be such a situation: application 1 delete the object when application 2 trySetRate it,  therefore application 1 will update failed.
The solution i would like is support the update operation(delete and trySetRate) in a transaction.
 The alternatives I have used in my project is locking object globally when update it.  

**Redisson Version: 3.13.0**

**Comment by mrniko** [comment]
use `setRate` method
