### ISSUE TITLE
Neither `expired` nor `deleted` listeners are getting events for `RBucket`

### ISSUE THREAD

**Issue by doctorpangloss** [redisson/redisson#2926]
This is just creating a ticket for https://github.com/redisson/redisson/issues/2922 because it's real.

**Expected behavior**

Listeners for bucket's `deleted` and `expired` should work.

**Actual behavior**

They do not.

**Steps to reproduce or test case**

See https://github.com/redisson/redisson/issues/2922

**Redis version**

6.0.5

**Redisson version**

3.13.2

**Redisson configuration**

Single server.

**Comment by mrniko** [comment]
set Redis `notify-keyspace-events` =  `Exg`
