### ISSUE TITLE
connection leak in sentinelMode and without ssl

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#2929]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
3.11.0

**Redisson configuration**
config.setCodec(getCodec("org.redisson.client.codec.StringCodec"));
config.useSentinelServers()
           .setMasterName("xxxxx")
           .addSentinelAddress(sentinelAddress)
           .setPassword("xxxxx")
           .setPingConnectionInterval(5000)
           .setDatabase(0);
(default masterConnectionMinimumIdleSize,slaveConnectionMinmumIdkeSize is 32, masterConnectionPoolSize,slaveConnectionPoolSize is 64)

when sentinel/master/slave node and client network jitter, master/slaves role switching, masterConnectionPoolSize, slaveConnectionPoolSize can't limit connection, use jmap dump heap, ClientConnectionsEntry.freeConnectionsCounter.counter is bigger than 64!

![企业微信截图_df12bd1e-7247-4f57-9930-38987a422d2d](https://user-images.githubusercontent.com/8215006/87918415-f9a6dc00-caa8-11ea-8eab-efd646b19317.png)

![企业微信截图_9b608a5d-7829-4b6c-a404-52a17d394919](https://user-images.githubusercontent.com/8215006/87919656-b3eb1300-caaa-11ea-931e-f8ee66cc5ad1.png)

all connection is ESTABLISHED 
192.168.0.11    194 connections  slave
192.168.0.10   41   connections   slave
192.168.0.12   65   connections  master

**Comment by mrniko** [comment]
where was connection leak occured during RBatch object usage fixed in 3.12.2. Do you use RBatch object?

**Comment by mikawudi** [comment]
yes i use RBatch in my project, i will update redisson to try fix it,thx~
