### ISSUE TITLE
Bug: LiveObjectService#persist returns empty object

### ISSUE THREAD

**Issue by benyaa** [redisson/redisson#2935]
I'm using the Redisson Live Objects 3.13.2 and I have the following object:

```
@Getter
@ToString
@Builder
@AllArgsConstructor
@NoArgsConstructor
@REntity
public class ReporterObject {
    @RId
    private long id;
    private long rId;
    @RIndex
    @Setter
    private long sId;
    @Setter
    private boolean ac;
    @RIndex
    @Setter
    private Long parId;
    private int type;
    private Long pId;
    @Setter
    private ReporterObject parent; // can be null
    @Setter
    private int n_a = 0;
}
```

**Expected behavior**
`LiveObjectService#delete` removes the object immediately and `LiveObjectService#persist` returns a full object.

**Actual behavior**
So I have two problems:

1. When I do this operation(to override the current object):
```
liveObjectService.delete(ReporterObject.class, reporterObject.getRId());
return liveObjectService.persist(reporterObject);
```
I sometimes get `java.lang.IllegalArgumentException: This REntity already exists.` although I'm performing a deletion beforehand. I can get it even if the cache is totally empty before then.

2. Sometimes after the persist operation supposedly succeed, what I receive is an empty object so when I try to get any field(for example call `ReporterObject#getParent` a `NullPointerException` is  being thrown, and when I debug it I see an empty object or not "fully full" object:
[![enter image description here][1]][1]
. In this example I only have `sId` and `type` but no `id` , no `rId`, no `ac` etc. As I stated, If I try to `getAc()` a `NullPointerException` is thrown. Of course it's not limited to this fields only. Sometimes it's other fields that are missing. Sometimes I get a fully empty object like this one:
[![enter image description here][2]][2]

**Steps to reproduce or test case**
I guess use the same object as me.
It might be important to know that I'm inserting those object concurrently(different objects though - no two objects with the same id at the same time).
**Redis version**
6.0.5
**Redisson version**
3.13.2
**Redisson configuration**
Used this code to config it:
```
Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://server:6379")
                .setClientName("client")
                .setPassword("password")
                    .setConnectionMinimumIdleSize(400)
                .setConnectionPoolSize(10_000)
                .setRetryAttempts(500)
                .setRetryInterval(100);
        return Redisson.create(config);
```

Hope you can help! Thanks

  [1]: https://i.stack.imgur.com/SHS9g.png
[2]: https://i.stack.imgur.com/WGTcH.png

**Comment by mrniko** [comment]
Fixed! Thanks for report
