### ISSUE TITLE
Does redisson support the client side caching which starts with Redis 6.0 ？

### ISSUE THREAD

**Issue by Hongda277** [redisson/redisson#2936]
Does redisson support the **client side caching** which starts with Redis 6.0 ？Or whether it will support the client side caching in the future ?

**Comment by mrniko** [comment]
Client side caching is already supported with RLocalCachedMap object and avialable for all Redis versions.

**Comment by Chenng** [comment]
@mrniko  Hi , do you mean that ``RLocalCachedMap`` support ``Client side caching`` but not ``RESP3`` which Redis achievement?

**Comment by mrniko** [comment]
Yes. For compatiblity purposes with all Redis versions it doesn't use RESP3 for now. Let me know if you see any drawbacks here

**Comment by adrian-skybaker** [comment]
It would still be interesting to see how https://redis.io/topics/client-side-caching might be used.

We had to retire our use of `RLocalCachedMap` because our data structured resulted in a `RLocalCachedMap` instance per-user, which translated into a very high number of subscriptions, eventually exhausting even the increased limits we configured.

**Comment by mrniko** [comment]
@adrian-skybaker 

I'll refactor it to PatternTopic. Single listener is created per Redisson instance. It process events of all local caches.

**Comment by mrniko** [comment]
@adrian-skybaker 

> eventually exhausting even the increased limits we configured

Fixed in https://github.com/redisson/redisson/issues/4064#issuecomment-1008653338

**Comment by adrian-skybaker** [comment]
Thanks for following up - from my brief reading of that fix it fixes a leak, but doesn't change the fundamental implementation of each `RLocalCachedMap` registering its own subscription through to Redis? The issue we had was more one of scalability. If we had millions of active users, each with their own `RLocalCachedMap`, then the number of subscriptions required becomes unmanageably high.

**Comment by mrniko** [comment]
@adrian-skybaker 

Pattern Topic could be shared along all RLocalCachedMap instances.

**Comment by adrian-skybaker** [comment]
That would be more efficient I think, but possibly it would be better still to leverage the native cache notifications added in https://redis.io/topics/client-side-caching ?
