### ISSUE TITLE
org.redisson.client.RedisTimeoutException  use RLock

### ISSUE THREAD

**Issue by tmaerd** [redisson/redisson#2940]
**Environment Info:**

redis-server:4.0.11
redission-version:3.12.0
config:
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 60000
  keepAlive: false
  tcpNoDelay: false
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  dnsMonitoringInterval: 5000
  natMap: {}
  nodeAddresses:
  - "redis://x.x.x.22:6370"
  - "redis://x.x.x.23:6370"
  - "redis://x.x.x.24:6370"
  - "redis://x.x.x.25:6370"
  - "redis://x.x.x.26:6370"
  - "redis://x.x.x.27:6370"
  scanInterval: 2000
  checkSlotsCoverage: false
  slaveSubscriptionConnectionPoolSize: 50
  slaveSubscriptionConnectionMinimumIdleSize: 1
threads: 16
nettyThreads: 32
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
keepPubSubOrder: true
decodeInExecutor: false
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}

**error:**
`org.redisson.client.RedisTimeoutException: Unable to acquire connection! Increase connection pool size and/or retryInterval settings Node source: NodeSource [slot=16255, addr=redis://x.x.x.22:6370, redisClient=null, redirect=MOVED, entry=null], command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, call_job:callLock:4acda4eb2e204e809541e46526400c3b, 30000, 55613171-821a-400b-b56b-0274529ac468:275] after 0 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:191)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)`

The online environment has been running for many days without problems, and the above error has been reported recently and it is normal after restarting.
When the error is reported, the application still has 27 connections to x.x.x.22:6370
Except  the connections to x.x.x.22:6370 has errors, other redis nodes have no errors
The application is using redisClient at the same time, but no error is reported,indicating that there should be no problem with the network

question:
I want to know what are the possible reasons for the above error

**Comment by qertyop** [comment]
I also have almost the same issue

**Comment by mrniko** [comment]
> org.redisson.client.RedisTimeoutException: Unable to acquire connection! 

This error means that all connections are busy.
