### ISSUE TITLE
ExecutorService - how to specify workers

### ISSUE THREAD

**Issue by darknessp** [redisson/redisson#2943]
hi, I wonder what does the workers mean when I register a worker:
```
 WorkerOptions options = WorkerOptions.defaults()
    // Defines workers amount used to execute tasks.
    // Default is 1.
    .workers(2)
```
Do I have to specify all the workers that might be registered into this cluster? The problem is that the auto-scaling strategy makes it hard to specify the number of all workers, because the number varies in runtime.

**Comment by darknessp** [comment]
> it means units used to execute tasks and executed on shared executorService (threads amount defined in threads settings).

what's its scope? jvm or the whole cluster?

**Comment by mrniko** [comment]
jvm
