### ISSUE TITLE
some closed channel in freeConnections after network jitter

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#2947]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
use chaosblade, set losspackage 50% and 200ms delay in redis port, keep 5min
start 50 thread to use redisson to read redis (client.getBucket("testkey").get())
**Redis version**
5.0.8
**Redisson version**
3.11.0 
**Redisson configuration**
config.setCodec(getCodec("org.redisson.client.codec.StringCodec"));
config.useSentinelServers()
.setMasterName("xxxxx")
.addSentinelAddress(sentinelAddress)
.setPassword("xxxxx")
.setPingConnectionInterval(5000)
.setDatabase(0);
(default masterConnectionMinimumIdleSize,slaveConnectionMinmumIdkeSize is 32, masterConnectionPoolSize,slaveConnectionPoolSize is 64)

when chaosblade execute finished,i find 2 bugs:
1) i find there are some closed connection(channel) in the free connection pool
    i use arthas to attach process, and watch org.redisson.command.CommandAsyncService#async(...int attempt, ...)
when chaosblade execute finished,also have method invoke with attempt > 0,than i find async(attempt > 0) only called by org.redisson.command.CommandAsyncService$6(it's a anonymous TimerTask)#run, getconnection() succes and call sendcommand() but netty writefuture not complete,than trigger the TimerTask, and i watch org.redisson.command.CommandAsyncService#sendCommand, find any connections is closed....and i use netstat -nt to confirm the connection is closed, but their also in the freeConnectionPool.....

2) the find freeConnectionCounter is bigger than slaveConnectionPoolSize, and freeConnection, allconnection also unlimit at sometime and sometime freeConnections size is bigger than allConnection......
it just like https://github.com/redisson/redisson/issues/2929#issue-661572762
and i reproduce it without RBatch command

i don't know why not check connection and drop it when getconnection?(
in org.redisson.connection.pool.ConnectionPool#connectTo, poll() get a connection,the connection is not actived,just trySetupFistFail?)

and i want know this bug is fixed in 3.13.xx?
 thanks for you~

**Comment by mrniko** [comment]
3.12.1 - fixes - connections to disconnected Redis nodes aren't removed in sentinel and cluster mode.

I think it's might related to this issue.

**Comment by mikawudi** [comment]
i will update redisson to 3.13 to confirm it,~thanks~(*^▽^*)

**Comment by mikawudi** [comment]
update my test project's redisson to 3.12.2, 3.13.2.......i think the bug is not fixed....
:57839  <-->  52:6316
:58561  <-->  51:6316
the two connection not clean from freeConnections after network jitter 20min....
![arthas](https://user-images.githubusercontent.com/8215006/88906351-ee626600-d289-11ea-94cf-1fc0702a913d.png)
![51](https://user-images.githubusercontent.com/8215006/88906372-f3271a00-d289-11ea-9188-311e781e7b53.png)
![52](https://user-images.githubusercontent.com/8215006/88906380-f5897400-d289-11ea-967f-19af48803c9b.png)

**Comment by mrniko** [comment]
> the two connection not clean from freeConnections

Because all connections are in established state. Connection removed from pool only if pool in shutdown state.

**Comment by mikawudi** [comment]
the 
:57839 <--> 52:6316
:58561 <--> 51:6316
their are not in established state,their not in netstat -nt | grep 6316, you can see my screenshot, but their in freeConnections.
some business thread get thire and sendCommand, will target org.redisson.command.RedisExecutor$2.run(), i traced it by arthas,you can see the arthas command in first screenshot

**Comment by mrniko** [comment]
did you test with setPingConnectionInterval setting? that's strange. Do you see errors reported by `org.redisson.client.handler.PingConnectionHandler` ?

**Comment by mikawudi** [comment]
the closed channel in a RedisConnection, the RedisConnection‘s closed field is true,and i check the code of ConnectionWatchdog‘s channelInactive method, when RedisConnection‘s closed field is true, the RedisConnection can't reconnect ()? why check RedisConnection‘s isClosed() when release RedisConnection into freeConnections in ConnectionPool?

**Comment by mrniko** [comment]
Connection is closed only through `org.redisson.client.RedisConnection#closeAsync()` method

**Comment by tengwei** [comment]
i have a problem.
org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=4103, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1811775937 [redisClient=[addr=redis://10.11.41.25:6002], channel=[id: 0xb261fc0f, L:/10.11.41.203:51670 - R:10.11.41.25/10.11.41.25:6002], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@596cfc2d(failure: java.util.concurrent.CancellationException)], command=(GET), params=[35.72.226.67:reqw:iban], codec=org.redisson.codec.FstCodec]], command: (HSCAN), params: [delivery_ticker24hr_map, 0, COUNT, 10] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:714) ~[nextme-rest.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682) ~[nextme-rest.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757) ~[nextme-rest.jar:?]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485) ~[nextme-rest.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.11.1</version>
        </dependency>

**Comment by mikawudi** [comment]
@tengwei i received your mail and back some suggest by mail~
