### ISSUE TITLE
how to set rmap hashkey Serializer method?

### ISSUE THREAD

**Issue by silloy** [redisson/redisson#2949]
when I use redistemplate, I can do this:

template.setKeySerializer(stringRedisSerializer);
template.setValueSerializer(redisSerializer);
template.setHashKeySerializer(stringRedisSerializer);
template.setHashValueSerializer(redisSerializer);

how can I set Serializer for hashkey or key independently

**Comment by mrniko** [comment]
You can implement `org.redisson.client.codec.Codec` interface or use ready implementations listed here - https://github.com/redisson/redisson/wiki/4.-data-serialization

**Comment by silloy** [comment]
I hava known this method, just like
`RMap<Long, String> rMap = client.getMap("user:info", new JsonJacksonCodec());`
but my hahkey want to use StringCodec, not JacksonCodec, how can I set codec just for hashkey separately.
