### ISSUE TITLE
how to set rmap hashkey Serializer method?

### ISSUE THREAD

**Issue by silloy** [redisson/redisson#2950]
Follow the issue: https://github.com/redisson/redisson/issues/2949

when I use redistemplate, I can do this:

```
template.setKeySerializer(stringRedisSerializer);
template.setValueSerializer(redisSerializer);
template.setHashKeySerializer(stringRedisSerializer);
template.setHashValueSerializer(redisSerializer);
```

I hava known this method, just like
`RMap<Long, String> rMap = client.getMap("user:info", new JsonJacksonCodec());`
but my hahkey want to use StringCodec, not JacksonCodec, how can I set codec just for hashkey separately.

**Comment by mrniko** [comment]
You can do it with `CompositeCodec`:

```java
client.getMap("user:info", new CompositeCodec(StringCodec.INSTANCE, new JsonJacksonCodec()));
```

**Comment by silloy** [comment]
It worked for me, thanks!
