### ISSUE TITLE
Sentinel in junit test.

### ISSUE THREAD

**Issue by savvadem** [redisson/redisson#2952]
Hello
I want to write junit test in redisson to check my problem with Sentinel.
I found test ```org.redisson.RedissonBlockingQueueTest#testTakeReattachSentinel``` and wanted to use it as example for
Sentinel setup, but it's failing to run.

What am i doing wrong?
![image](https://user-images.githubusercontent.com/39496377/89040362-55e0ea00-d34c-11ea-8503-961657a9da4c.png)

all other tests run fine
![image](https://user-images.githubusercontent.com/39496377/89040407-698c5080-d34c-11ea-924c-f89bd319f67c.png)

enviroment: Linux Mint 20 Cinnamon, jdk 11.

**Comment by savvadem** [comment]
any help?

**Comment by mrniko** [comment]
This error means that Redis port is already allocated by other process.
