### ISSUE TITLE
redisson clusterConfig getMap method bug

### ISSUE THREAD

**Issue by Wismyluckstar** [redisson/redisson#2955]
**Expected behavior**
    o is not empty,o1 is not empty;
**Actual behavior**
The first getMap execution result is not empty, and the second getMap execution result is null;

**Steps to reproduce or test case**
@jackygurui 
-----------!!!!
127.0.0.1:6384> cluster slots
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 6384
      3) "4a5c09af2a6d65317216c152a80b9292f0070bfe"
   4) 1) "127.0.0.1"
      2) (integer) 6386
      3) "e80ed5831c610bebd8b799a3811a6d4a4ebd9852"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 6385
      3) "65b4da8b421bdffbe1e3a77809008e26ffc88735"
   4) 1) "127.0.0.1"
      2) (integer) 6387
      3) "1c8583a3254c96f5174f9edd81b9a269608d65d2"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 6383
      3) "5d795b06238ec47845ad8d04aea8bfb285f3bdec"
   4) 1) "127.0.0.1"
      2) (integer) 6388
      3) "86abff0208c1bc528a003345fb6f5ce744f5dfc0"

only keyslot  5461-10922  behavior normal
-----------!!!!
//case1
        String userIdKey = "user:" + 37;
        RBatch batch = redissonClient.createBatch();
        RFuture<Object> async = batch.getMap(userIdKey).getAsync(User.LOGIN);
        BatchResult<?> execute = batch.execute();
        Object o = async.get(); //--not null
        Object o1 = redissonClient.getMap(userIdKey).get(User.LOGIN);
        System.out.println(o1);//-- null

//case2
        String userIdKey = "user:" + 37;
        Object o1 = redissonClient.getMap(userIdKey).get(User.LOGIN);
        RBatch batch = redissonClient.createBatch();
        RFuture<Object> async = batch.getMap(userIdKey).getAsync(User.LOGIN);
        BatchResult<?> execute = batch.execute();
        Object o = async.get(); //--null
        System.out.println(o1);//-- not null
**Redis version**
6.0.5
**Redisson version**
3.13.1
**Redisson configuration**
clusterServersConfig:
        idleConnectionTimeout: 10000
        pingTimeout: 1000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        failedSlaveReconnectionInterval: 3000
        failedSlaveCheckInterval: 3
        password: '123456'
        subscriptionsPerConnection: 5
        clientName: "redisson-demo"
        loadBalancer:
          class: "org.redisson.connection.balancer.RandomLoadBalancer"
        slaveSubscriptionConnectionMinimumIdleSize: 1
        slaveSubscriptionConnectionPoolSize: 50
        slaveConnectionMinimumIdleSize: 32
        slaveConnectionPoolSize: 64
        masterConnectionMinimumIdleSize: 32
        masterConnectionPoolSize: 64
        readMode: "MASTER_SLAVE"
        nodeAddresses:
          - "redis://127.0.0.1:6383"
          - "redis://127.0.0.1:6384"
          - "redis://127.0.0.1:6385"
          - "redis://127.0.0.1:6386"
          - "redis://127.0.0.1:6387"
          - "redis://127.0.0.1:6388"
        scanInterval: 1000
      threads: 0
      nettyThreads: 0
      codec:
        class: "org.redisson.codec.JsonJacksonCodec"
      transportMode: "NIO"

**Comment by mrniko** [comment]
Unable to reproduce.

> The first getMap execution result is not empty, and the second getMap execution result is null;

Becasue readMode: "MASTER_SLAVE" first request went to Master and second to slave. Seems you have wrong configuration and data not replicated to slave node.
