### ISSUE TITLE
XPENDING causes syntax error in redisson-spring-data-23

### ISSUE THREAD

**Issue by KOREAN139** [redisson/redisson#2959]
**Expected behavior**
list of `PendingMessage`

**Actual behavior**
`org.redisson.client.RedisException: ERR syntax error. channel: [id: 0x622755ea, L:/192.168.96.10:58442 - R:redis/192.168.96.5:6379] command: (XPENDING), params: [consumer_group:test, -, +, 2]`

**Steps to reproduce or test case**
use [pending(K key, String group, Range<?> range, long count)](https://github.com/spring-projects/spring-data-redis/blob/c2f20dfa5a7583a2a30f001dff69f3a65e4d8e20/src/main/java/org/springframework/data/redis/core/DefaultStreamOperations.java#L225)
``` java
      redisTemplate
          .opsForStream()
// error occurs regardless of range; Range.from(lowestId, highestId), ...
          .pending(streamName, groupName, Range.unbounded(), count)
```

**Redis version**
`5.0.4`

**Spring boot starter version**
`2.3.2.RELEASE`

**Redisson version**
`3.13.2`

**Redisson configuration**
none (only `spring.redis.host` is set)

Seems like [command for connection](https://github.com/redisson/redisson/blob/aa5813cc7b14942a83d72c675a5a6ed2b9cbb555/redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/RedissonStreamCommands.java#L342-L343) should be `XPENDING_ENTRIES`, not `XPENDING`

**Comment by mrniko** [comment]
Fixed! Thanks for report
