### ISSUE TITLE
FairLock is freezed after run more than 9000 times

### ISSUE THREAD

**Issue by liuwenchang** [redisson/redisson#2960]
int j =0;
    public void Redis() throws InterruptedException {
        int i=0;
        while (i<100) {
            i++;
            Thread ts1 = new Thread(() -> {
                while (true) {
                    RLock lock = redisson.getFairLock("frozen");
                    try {
                        lock.lock(-1, null);
                        log.info(String.valueOf(j++));
                    }finally {
                        if (lock.isHeldByCurrentThread()) {
                            lock.unlock();
                        } else {
                            log.error("获取了锁，但是却不能解锁？？");
                        }
                    }
                }
            });
            ts1.start();
        }
        Thread.sleep(1000000000);
    }
this is my code.the log will not print after a few minute.

**Comment by mrniko** [comment]
update to 3.13.3 version
