### ISSUE TITLE
什么时候能支持流监听呢？

### ISSUE THREAD

**Issue by honestAnt** [redisson/redisson#2962]
类似 https://docs.spring.io/spring-data/redis/docs/2.2.x/api/org/springframework/data/redis/stream/StreamMessageListenerContainer.html 这个；

eg：当消息进入group之后，通知 消费者（当前group下）去处理消息；（类似RTopic的广播）

**Comment by honestAnt** [comment]
现在消息进入group后，需要应用 这边轮循读取数据；这边是否能提供类似监听group中数据变更的方式呢？

**Comment by mrniko** [comment]
I'm afraid no
