### ISSUE TITLE
when i try batch persist, but return result is not correct. please help .thanks.

### ISSUE THREAD

**Issue by tanrui988** [redisson/redisson#2967]
code like as below:
---------------------------------------------------------------------------------------------------
// batch persist
List<XXXXXX> persistResut = RLiveObjectService.persist(XXXXXX1, XXXXX2, XXXXX3);
// story result
Map<XXXXXX> map = RedissonLocalCacheMap;

for(XXXX xxx : persistResut){
	map.put(xxx.id, xxxx);
}
---------------------------------------------------------------------------------------------------
result will throw exception:
Exception in thread java.lang.IllegalArgumentException: REntity should be attached to Redisson before save.

i think ,current object:xxx always java object, not link to redisson object , if i add some code ,will be normal. 
eg:
for(XXXX xxx : persistResut){
        // new link to redisson object
        xxx = RLiveObjectService.get(XXXXX, PersistName);
	map.put(xxx.id, xxxx);
}

so i think batch persist result why not link to redisson object automatic ?

**Comment by mrniko** [comment]
You can't pass RedissonLocalCacheMap as Live objects to `RLiveObjectService.persist` method.
