### ISSUE TITLE
Not able to  remove custom object from RScoredSortedSet JAVA

### ISSUE THREAD

**Issue by kakadiyahardik** [redisson/redisson#2970]
`RScoredSortedSet<CustomObj> set = redisson.getScoredSortedSet(key);
CustomObj obj = new CustomObj(1,2);
set.add(obj);

set.remove(obj); // this is not removing obj from sorted set`

I have code like above in my application. i am not able to remove custom obj from RScoredSortedSet.

**Comment by mrniko** [comment]
Unable to reproduce it. could you share test code?

**Comment by kakadiyahardik** [comment]
public class Data {
    private String id;
    private String type;
    private long expireAt;

    public Data(String id, String type, long expireAt) {
        this.id = id;
        this.type = type;
        this.expireAt = expireAt;
    }

    public Data() {
    }

// gettter & setter

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Data data2 = (Data) obj;
        if (id == null) {
            return data2.id == null;
        } else return id.equals(data2.id);
    }
}

RScoredSortedSet<Data> set = redisson.getScoredSortedSet(key);
Data a = new Data("1","a",0);
set.add(0,a);

Data b = new Data("2","a",0);
set.add(0,b);

Data c = new Data("3","a",0);
set.add(0,c);

// now i am trying to delete data with id =1
set.remove(a);

// its not removing data object with id 1 from set.

**Comment by mrniko** [comment]
Unable to reproduce. I used default codec. Here is my test:

```java
    public static class Data implements Serializable {
        private String id;
        private String type;
        private long expireAt;

        public Data(String id, String type, long expireAt) {
            this.id = id;
            this.type = type;
            this.expireAt = expireAt;
        }

        public Data() {
        }

    // gettter & setter

        @Override
        public boolean equals(Object obj) {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            Data data2 = (Data) obj;
            if (id == null) {
                return data2.id == null;
            } else return id.equals(data2.id);
        }
    }

    @Test
    public void test1() {
        RScoredSortedSet<Data> set = redisson.getScoredSortedSet("test");
        Data a = new Data("1","a",0);
        set.add(0,a);

        Data b = new Data("2","a",0);
        set.add(0,b);

        Data c = new Data("3","a",0);
        set.add(0,c);

        // now i am trying to delete data with id =1
        assertThat(set.remove(a)).isTrue();
    }

```
