### ISSUE TITLE
can i use spring.redis.pool.size to  change connectionPoolSize?

### ISSUE THREAD

**Issue by gaoyang143** [redisson/redisson#2974]
can i use spring.redis.pool.size to  change connectionPoolSize? although use redisson.yaml can set this parameter. however, I want to only set parameters in application.properties, then i can put application.properties in git which used in spring-cloud-config.

**Comment by mrniko** [comment]
I'm afraid no, use redisson.yaml config instead:

spring.redis.redisson.config=classpath:redisson.yaml
