### ISSUE TITLE
Reads only happening from Master Node for Hibernate L2 Cache in Elastic Cache replicated mode

### ISSUE THREAD

**Issue by anujpradhaan** [redisson/redisson#2981]
### **Redis Setup:** 
Nodes: 1 Primary and 2 Replica Nodes 
002 is Primary, rest 2 are replica node. 

### **What I want to acheive**
I want to configure Redis as a distributed l2 cache to improve my application's performance as ~70% of my traffic is read only. I am using hibernate as my ORM, thus don't want to write lots of custom code when there is a standard implementation provided by redisson.  

### **My Configuration:**
```
Config config = new Config()
.setTransportMode(TransportMode.NIO)
.setCodec(new SnappyCodecV2())
.useReplicatedServers()
.setTimeout(10000)
.addNodeAddress(
	String.format("redis://%s:%s", "mercuryredis-002.xxx.cache.amazonaws.com", port), 
        String.format("redis://%s:%s", "mercuryredis-001.xxx.cache.amazonaws.com", port),
	String.format("redis://%s:%s", "mercury-redis-003.xxx.cache.amazonaws.com", port))
.setIdleConnectionTimeout(10000);
```

### **Issue:**
I see all the cache hits are from the master node meaning every write, as well as read, is just happening from the master node. 

I went through all the issues reported till now to find the solution but none of them were around hibernate l2 cache. Finally found https://github.com/redisson/redisson/issues/2165 where its mentioned **"RMapCache.get operations modifies data so it can't use slave node. This method updates idletimeout and lasttimeaccess parameters per entry.
You could use RMap object in this case."**

And After looking at the code [here](https://github.com/redisson/redisson/blob/master/redisson-hibernate/redisson-hibernate-4/src/main/java/org/redisson/hibernate/region/RedissonEntityRegion.java) I found we are using RMapCache<Object,Object> for each region. 

This indicates we can't use it correctly for Hibernate L2 Cache as every time I try to fetch a cached object, redisson will write to the master node and my entire traffic will become dependent on a single master node. Which is not very reliable. 

Please help with this. 

### **Proof**
![image](https://user-images.githubusercontent.com/5353322/90323606-39b28f00-df81-11ea-90a5-039f9667202c.png)

Cache Hit Rate: You can clearly see its just hitting primary node.
![image](https://user-images.githubusercontent.com/5353322/90323564-80ec5000-df80-11ea-9abd-e99be7c4f13f.png) 

Cache Hits: You can clearly see its just hitting primary node.
![image](https://user-images.githubusercontent.com/5353322/90323573-9e211e80-df80-11ea-94d5-7fd71c63a4e9.png)
Cache Misses: 
![image](https://user-images.githubusercontent.com/5353322/90323578-ada06780-df80-11ea-82e5-cfcfa69b10f5.png)

**### Version used:** 
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson</artifactId>
	**<version>3.13.2</version>**
</dependency>
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson-hibernate-4</artifactId>
	**<version>3.13.2</version>**
</dependency>`

Happy to provide more details.

**Comment by anujpradhaan** [comment]
@mrniko Could you check this once you have some time. I am sure you can provide a relevant answer very fast.

**Comment by mrniko** [comment]
RMapCache is since it support ttl and idleTime parameters per entry. RMap doesn't support these params

**Comment by anujpradhaan** [comment]
@mrniko Got it. Could you help with "Why it's not reading from replica servers" or how to actually make it happen?

I assumed in replication mode configurations reads will happen from the read instances. And writes just to write servers.

**Comment by anujpradhaan** [comment]
@mrniko Could you please help.

**Comment by harshamadala** [comment]
@mrniko We are also facing same issue. It is impacting performance badly, could you please help if we have a work around for this? What are these parameters idletimeout and lasttimeaccess used for? We are looking for TTL based eviction only and if these fields are not used for TTL based eviction can we skip writing to these and use replicas for reading?

**Comment by mrniko** [comment]
I think new versions of `get()` and containsKey()` methods could be introduced. They shouldn't check entry's idleTime.

**Comment by mrniko** [comment]
@harshamadala do you use `eviction.max_entries` setting?

**Comment by harshamadala** [comment]
> I think new versions of `get()` and `containsKey()` methods could be introduced. They shouldn't check entry's idleTime.

Yes i think improves performance as readonly commands can go to replica nodes. Any quick solution possible for this? From the code i see that we use commandExecutor.evalRead for scanIterator. Couple of queries
1. Is it possible to use scanIterator to read all values of map (our map generally contains 30-60 entries). Assuming scanIterator goes to replica nodes based on the [code](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMapCache.java#L1410).
2. Is it possible to update logic [here](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMapCache.java#L2514) to use readAsync instead of writeAsync and remove write related commands?

**Comment by harshamadala** [comment]
> @harshamadala do you use `eviction.max_entries` setting?

Thanks for the responses @mrniko . We don't use this setting.

**Comment by mrniko** [comment]
Fixed. Hibernate Cache now uses Redis slave if `expiration.max_idle_time` and `eviction.max_entries` aren't specified.
