### ISSUE TITLE
org.redisson.client.RedisNodeNotFoundException: Node for slot: 7727 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command

### ISSUE THREAD

**Issue by SaiP061** [redisson/redisson#2986]
We have an AWS Elasticache cluster, with cluster mode enabled - multiple shards, NO replicas.
When ever a node is replaced, after new node comes up, Redission is not able to discover the new node, fails with 
RedisNodeNotFoundException 

Exception trace: 
	
org.redisson.client.RedisNodeNotFoundException: Node for slot: 7727 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command
at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundFuture(MasterSlaveConnectionManager.java:613) ~[Redisson-3.11.x.jar:?]
at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:567) ~[Redisson-3.11.x.jar:?]
at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:645) ~[Redisson-3.11.x.jar:?]
at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:116) ~[Redisson-3.11.x.jar:?]
at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:245) ~[Redisson-3.11.x.jar:?]

**Expected behavior**
Redisson to discover new replaced node without any issue
**Actual behavior**
Redisson fails to discover new node with RedisNodeNotFoundException.

**Redis version**
5.0.4
**Redisson version**
3.11.6
**Redisson configuration**

**More logs:**
**During node replacement:**

04:41.9 | 11 Aug 2020 06:04:40,996   [1;31m[ERROR][m    (redisson-netty-5-7) org.redisson.cluster.ClusterConnectionManager:   Can't connect to master: redis://10.0.61.52:6379 with slot ranges:   [[7168-8191]]

04:41.6 | 11 Aug 2020 06:04:40,840   [32m[INFO][m    (redisson-netty-5-5) org.redisson.cluster.ClusterConnectionManager:   slave redis://10.0.61.52:6379 removed for slot ranges: [[7168-8191]]
-- | --

**After node replacement:**
03:47.7 | 11 Aug 2020 06:03:47,711   [32m[INFO][m    (redisson-netty-5-33)   org.redisson.connection.pool.SlaveConnectionPool: 24 connections initialized   for 10.0.61.52/10.0.61.52:6379
-- | --
org.redisson.client.RedisNodeNotFoundException: Node for slot: 7727 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command

---  Put and Deletes are failing

**Comment by honestAnt** [comment]
：https://github.com/redisson/redisson/issues/2750

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2750
