### ISSUE TITLE
HA Failover: Redisson client maintaining the connection with the previous node, unable to read/write to redis.

### ISSUE THREAD

**Issue by saurabhkohli-ril** [redisson/redisson#2994]
Facing the following issue during HA testing the application wtih Redisson Client:::

Redisson Version: 3.11.6

Redis Cluster: 3M + 2S

Steps:
1. Kill one of the masters, the slave becomes the master.
2. Make the master up after a minute, it then becomes the slave.
3. Kill the master node(which was slave), the slave becomes the master.
Sometimes its not reproducible in one shot, need to do this 3-4 times.

At this point, redisson is not able to read/write anything to that redis partition  because the client is still taking the previous master(which was killed) and not the promoted slave node.

As per below logs, port 8000 was the master node, which was killed, and the slave node 9000 was promoted to master. But still Redisson is sending the command to the previous master node. We need to restart the application to make it working or make the previous master up.

Redis Cluster Nodes Command:::
 **10.32.xxx.xx:8000 master,fail - 1597924494641 1597924493739 29 connected**
 10.32.xxx.xx:8002 master - 0 1597924565415 3 connected 10923-16383
 10.32.xxx.xx:9001 slave e0633f21c6a79ad10c9a8696a45991867aabc879 0 1597924566919 2 connected
 10.32.xxx.xx:9000 master - 0 1597924566417 30 connected 0-5460
 10.32.xxx.xx:8001 myself,master - 0 0 2 connected 5461-10922

Logs:::::
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=5048, addr=null, redi
sClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:qu
eue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=**redis://10.32.xxx.xx:8000**], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@427802830 [redisClient=[addr=**redis://10.32.xxx.xx:8000**], channel=[id: 0xda6d
e1f2, L:0.0.0.0/0.0.0.0:35504], currentCommand=null]

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/2802
