### ISSUE TITLE
How can I force Redisson to resolve the Redis server hostname again?

### ISSUE THREAD

**Issue by gdb00** [redisson/redisson#2996]
We had an issue where the IP address of the Redis server changed. We saw logs like these from the DNSMonitor:

Detected DNS change. Master rediss://{host}:{port} has changed ip from IP1 to IP2
Unable to find master entry for host/{IP1}:port. Multiple IP bindings for single hostname supported only in Redisson PRO!

I saw in response to a similar issue the recommendation to disable DNS monitoring. I tried to prototype (with 3.13.3) on a local PC using the hosts file to simulator a DNS change. But Redisson continues to use the earlier resolved IP address instead of resolving the hostname again. I confirmed with InetAddress.getByName() that I can retrieve the updated IP address, but Redisson is still trying to use the old one.

I also tried to detect the connection drop when the IP changes (using ConnectionListener) and then completely recreate the Config and RedissonClient objects with the hostname, but still the older IP is used, and shown in the exception after failure to connect. I guess it remains cached somewhere?
Exception in thread "Thread-0" org.redisson.client.RedisConnectionException: Unable to connect to Redis server: host/{IP1}:6379

Is there any way to force a new attempt to resolve the IP?

**Comment by johnou** [comment]
@gdb00 what's the ttl of your host? the host could be cached at the netty resolver level..

**Comment by mrniko** [comment]
If host has single ip then DNSMonitor changes master correctly. For multiple ips you need PRO version. ConnectionWatchdog is not participating here since instance with outdated IP will be shutdown.

**Comment by gdb00** [comment]
How does Redisson determine that there are multiple IPs? The first of the two logs from DNSMonitor indicates that the server IP is changing from IP1 to IP2. I am using the SingleServerConfig so I'm only expecting the server to have one IP at a time.

Detected DNS change. Master rediss://{host}:{port} has changed ip from IP1 to IP2
Unable to find master entry for host/{IP1}:port. Multiple IP bindings for single hostname supported only in Redisson PRO!

**Comment by mrniko** [comment]
> How does Redisson determine that there are multiple IPs?

when more than one ip is resolved by the same name.

> Unable to find master entry for host/{IP1}:port

Is this node was registered as slave before failover

**Comment by mrniko** [comment]
Could you try it with version attached?

[redisson-3.13.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5127851/redisson-3.13.4-SNAPSHOT.jar.zip)

**Comment by gdb00** [comment]
Unfortunately I won't be able to reproduce with my actual cache, which is an Azure Redis cache. I think this is the first time I noticed it changing its IP address.

I tried to reproduce using a local redis instance on my PC, and switching the IP address in the local hosts file between 127.0.0.1 and the actual IP of my PC (and restarting the redis container to use the corresponding IP). In this test the only way I can get DNSMonitor to notice the change is if I create my own resolver and enable it using Config.setAddressResolverGroupFactory(). Otherwise the netty resolver continues to return the original IP even after I change it.  But once I do that, DNSMonitor catches the change and updates the master correctly, and it reconnects using the new IP.

I was hoping to understand more about why in my original case redisson thinks there are multiple IPs, or if there is some other info I can get from my Azure redis cache to confirm if that is the case somehow.

**Comment by mrniko** [comment]
Since 3.13.4 version master entry for single/sentinel Redis setup can't be null, so you won't get this error.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2965

**Comment by zhaochunxue** [comment]
最后这个问题是怎么解决的,我们线上也出现Multiple IP bindings for single hostname supported only in Redisson PRO,是要更换redission的版本吗?

**Comment by mrniko** [comment]
@zhaochunxue 

Update to 3.13.4 version
