### ISSUE TITLE
Delayed queue cannot store data in the target queue on time in cluster mode, but it is normal in single mode

### ISSUE THREAD

**Issue by chaosyoung97** [redisson/redisson#2997]
In cluster mode, delayed queue can't put the data to the target queue on time. The timeout data will be put into the target queue when the next offer is made

**Comment by mrniko** [comment]
Did you sync time across all application instances which use Redisson client?

**Comment by chaosyoung97** [comment]
Yes, at present, I use rdelayedqueue. Touch () to avoid this problem, but I don't know if it's right to do so

**Comment by mrniko** [comment]
You need to keep RDelayedQueue instance, so it could work.
