### ISSUE TITLE
Get with byte[] Key

### ISSUE THREAD

**Issue by Shabirmean** [redisson/redisson#3002]
Is there an interface I can use to do **_get, set and del_** operations with _byte[]_ keys?

```java
public byte[] get(byte[] key) {
      if (key == null) {
         return new byte[0];
      }
      return redissonClient.getBucket(key);
}

```

**Comment by michael-o** [comment]
Obviously not. Why don't you convert it to a hex string with `0x` prefixed?

**Comment by mrniko** [comment]
Each object bounded to String name. I would recommend you to convert byte[] into hex or base64 string.
