### ISSUE TITLE
When performing failover, RedisConnectionException is thrown when accessing the cache after failover.

### ISSUE THREAD

**Issue by Ryosuke-mm** [redisson/redisson#3005]
Regarding #2932, when we confirmed the effect using 3.12.3, the phenomenon was not resolved.
After the failover is complete, access to the new master keeps failing.

Could you please provide the conditions and details of the bugs that have been corrected?
https://github.com/redisson/redisson/commit/f220d929e052722c79e61776c533fc4a1014089c

I don't know if it is related to this case,
I'm currently using it in a non-cluster mode configuration where Redisson's addNodeAddress specifies the primary endpoint of the node group.

According to the issue below, you are asked to specify the endpoint of each node.
#2644　[Redisson Configuration For AWS ElastiCache]

Is it related to this phenomenon?
※ As a test, I fixed it so that the endpoint of each node was specified, and the phenomenon that it continued to fail after failover did not occur.

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by mrniko** [comment]
In AWS Replication.Endpoints mode you need to specify all nodes.
