### ISSUE TITLE
Correct way for scan via reddison client

### ISSUE THREAD

**Issue by SlandShow** [redisson/redisson#3007]
Hi!

I wan't to use redis `scan` operation via redisson (like in [Jedis](http://javadox.com/redis.clients/jedis/2.4.2/redis/clients/jedis/Jedis.html#scan(int))).

I'm checked next [solution](https://github.com/redisson/redisson/issues/885).

For example, i have **3** objects inside Redis and want to retrieve only **2**
```
 val keysIterator = redissonClient.keys.getKeysByPattern("some-pattern", 2).iterator()
 while (keysIterator.hasNext()) {
        println(keysIterator.next())
}
```

But instead of retriving 2 objects, `getKeysByPattern("some-pattern", 2)` returns all keys from redis.
This behaviour is correct?

Anyway, i'am trying to use `SCAN` operator via Lua scripts.
```
val lua = "return {redis.call('SCAN',ARGV[1],'MATCH',ARGV[2],'COUNT',ARGV[3])}"
redissonClient
                .getScript(StringCodec.INSTANCE)
                .eval<List<List<String>>>(RScript.Mode.READ_ONLY,
                        lua,
                        RScript.ReturnType.MAPVALUELIST,
                        listOf(),
                        0,
                        "some-pattern",
                        2)
```
And this aproach is working one.

But why `keys.getKeysByPattern(pattern, count)` returns all keys instead of count?

**Comment by mrniko** [comment]
getKeysByPattern("some-pattern", 2) as stated in comments to the method second argument is a keys amount loaded per request to Redis it's not limit

**Comment by SlandShow** [comment]
@mrniko so, for such approaches i need to use lua scripts?

**Comment by mrniko** [comment]
Yes, until I add a method to limit output.

**Comment by mrniko** [comment]
Done
