### ISSUE TITLE
Does redisson work with tomcat singlesignon valve 

### ISSUE THREAD

**Issue by ssn2020** [redisson/redisson#3008]
Hi,
If we have configured the org.apache.catalina.authenticator.SingleSignOn valve in our application, does Redisson push the ssoId also to Redis? Do we have to make any other configuration changes other than what's mentioned in redisson-tomcat Readme for this to work?
Thanks

**Comment by mrniko** [comment]
SingleSignOn sets principal as `javax.security.auth.subject` attribute in Session which is stored in Redis. Let me know if you have any issues.
