### ISSUE TITLE
cannot be cast to org.redisson.api.RMap

### ISSUE THREAD

**Issue by mitht** [redisson/redisson#3010]
An error occurred when setting the expiration time ：
   java.lang.ClassCastException: com.model.test.JobRecordRedisEntity cannot be cast to org.redisson.api.RMap

JobRecordRedisEntity entity = new JobRecordRedisEntity();
            entity.setFireInstanceId("q"+i);
            entity.setJobId("111111");
            entity.setFailcount(4);
            entity.setCreatetime(3333333333333l);
            entity.setScheduleFireTime("q");
            entity.setNextFireTime("w");
            entity.setExecutedTime("w"+i);
            entity.setRunningResult("seccess");
            entity.setMisfired("3");
            entity.setRecordId("123456qaz");
         
            boolean exists = service.isExists(service.get(JobRecordRedisEntity.class, entity.getRecordId()));
            if (exists){
                service.merge(entity);
            }else {
                service.persist(entity);
            }

            **service.asRMap(entity).expire(3, TimeUnit.SECONDS);**

**Comment by mrniko** [comment]
Because `JobRecordRedisEntity` doesn't implement `org.redisson.api.RMap` interface. Use proxy object instead like this:
```
entity = service.persist(entity);
```
