### ISSUE TITLE
Tomcat session manager requires serialization or is this a bug?

### ISSUE THREAD

**Issue by cratoo** [redisson/redisson#3012]
After successfully setting up Redisson as Tomcat session manager I get the following exception when trying to access the application:
`java.io.NotSerializableException: de.schlund.pfixxml.serverutil.SessionAdmin`

I also received another exception pointing to jboss-Marschalling also in regards to NotSerializableException.

As far as I understood the documentation, it would not be required to fix application code to move tomcat sessions to Redis via redisson. Am I wrong with my assumption?

Trying to solve this issue with different codecs did not work either.

Tomcat Version: 9.0.22
Redisson Version: all: 3.13.3, tomcat 9-3.10.6

**Comment by mrniko** [comment]
You can use another codec which doesn't require implementation of Serializable interface. For example: `org.redisson.codec.JsonJacksonCodec`

**Comment by cratoo** [comment]
That indeed changed something, but still does not work and I receive error 500 with a stacktrace:
`Request processing failed; nested exception is java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type java.util.concurrent.locks.ReentrantReadWriteLock: Failed to construct BeanSerializer for [simple type, class java.util.concurrent.locks.ReentrantReadWriteLock]: (java.lang.reflect.InaccessibleObjectException) Unable to make field private final java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock java.util.concurrent.locks.ReentrantReadWriteLock.readerLock accessible: module java.base does not "opens java.util.concurrent.locks" to unnamed module @5dc2ac75] with root cause
INFO   | jvm 1    | 2020/08/27 14:12:44 | com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type java.util.concurrent.locks.ReentrantReadWriteLock: Failed to
 construct BeanSerializer for [simple type, class java.util.concurrent.locks.ReentrantReadWriteLock]: (java.lang.reflect.InaccessibleObjectException) Unable to make field private final java.util.concu
rrent.locks.ReentrantReadWriteLock$ReadLock java.util.concurrent.locks.ReentrantReadWriteLock.readerLock accessible: module java.base does not "opens java.util.concurrent.locks" to unnamed module @5dc
2ac75`

and

`[redisson-netty-5-4] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0x7a6169e4, L:/10.30.9.74:53678 - R:ac1csredisbebsattack01.be.server.lan/10.30.9.57:6379], reply: ReplayingDecoderByteBuf(ridx=57, widx=57), command: (HGET), params: [redis:redisson:tomcat_session:EC4B9A0A8245E18C0B2F0B69CC513595.TCbs1b, PooledUnsafeDirectByteBuf(ridx: 0, widx: 14, cap: 256)]
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of de.schlund.pfixxml.util.CacheValueLRU (no Creators, like default constructor, exist): no default constructor found
at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 50]`


That still sounds to me like I would need to change the source?

**Comment by mrniko** [comment]
or write jackson serilizer for `java.util.concurrent.locks.ReentrantReadWriteLock` type

**Comment by cratoo** [comment]
@mrniko but that means, that I'd either need to change the application code or some other code and can't just replace tomcat integrated sessions with redisson redis sessions? The latter is what I understood from the documentation. On my side it won't just be one application, but multiple ones and if the answer is "it depends on each application" that would be quite hard.

**Comment by mrniko** [comment]
> that I'd either need to change the application code or some other code and can't just replace tomcat integrated sessions with redisson redis sessions?

You need to add custom serializer to Jackson if you do then you don't need to change anything in your code. https://www.baeldung.com/jackson-custom-serialization
