### ISSUE TITLE
Redis LiveObject Bulk Initialization

### ISSUE THREAD

**Issue by priyaranjan-b** [redisson/redisson#3014]
Hi There,
I am using Redis library in my application.
Now I am planning to use _RLiveObjectService_  for search page (instead of DB will read from Redis Cache).
I do see that there are methods available  in _RLiveObjectService_ for find , get , detele and instert to update Cache

I am looking for method like **mergeAll** or **persistAll** using which I can initialize cache during application startup.

Is there any way to achieve this.?

Thanks in Advance.

**Comment by mrniko** [comment]
persist method with vararg parameter is already implemented

**Comment by priyaranjan-b** [comment]
I am using redisson with  version '3.13.3'.
What I am looking for is a way to persist collection of _REntity_ .
This will help me initializing cache during start up

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/3014#issuecomment-682486605
