### ISSUE TITLE
Deletion RMap key by pattern

### ISSUE THREAD

**Issue by tarjadil2q** [redisson/redisson#3015]
Hi guys,

I stumble upon a weird issue for my project. I am trying to delete RMap key by a pattern. I follow the documentation and it seems I could do that by getting the keyset and passing the pattern, and delete the found keys via the fastRemove method.
However It does not work for me.

I am using redisson library version 3.12.3 for Java, and the cache is deployed through elastic cache AWS.

The setup is like the following:

the RMap name is `jsonCollectionV3` and the item key inside the map I tried to delete is  `100011176limit5offset2` the pattern I am using is `100011176*`

Please find below the code I am trying to use to fetch the key pattern from the map and using the fastRemove to delete the key retrieved. 

![code](https://user-images.githubusercontent.com/20692311/91536346-efa1b400-e957-11ea-8596-0738a9be9b50.PNG)

However as per log below and entry in Redis desktop manager, the key is not removed from the map, the size still one.

![AfterDelete](https://user-images.githubusercontent.com/20692311/91536433-0a742880-e958-11ea-9f12-a58f5c06a826.PNG)
 
![keyToBeDeleted](https://user-images.githubusercontent.com/20692311/91536271-d26ce580-e957-11ea-87a7-7d50cdfa92d9.png)

If you guys can help me point out where did I do wrong, that will be great! thanks a lot. I have tried changing the key format for storing the records and it is not working as well.

**Comment by mrniko** [comment]
There is might be a replication lag between master and slave. Try to set readMode = MASTER in config

**Comment by tarjadil2q** [comment]
Ok, I'll try that, I think I didn't configure it so by default It is Slave is used as a Read. Will there be a side effect of doing this?

Sorry I forgot to mention my current redis config is using replicated servers.

config.useReplicatedServers()
            .addNodeAddress(address.split(","))
            .setIdleConnectionTimeout(connectTimeout)
            .setConnectTimeout(connectTimeout)
            .setRetryAttempts(retryAttempts)
            .setTimeout(responseTimeoutInMillis);

**Comment by mrniko** [comment]
> Will there be a side effect of doing this?

side effect is the issue you have already.

**Comment by tarjadil2q** [comment]
Hi Nikita,

I tried setting the ReadMode to Master

```
Config config = new Config();
    config.useReplicatedServers()
            .addNodeAddress(lambdaProperties.get(PropertiesKeyEnum.REDISSON_ADDRESS_PROP_KEY.getKeyName()).split(","))
            .setReadMode(ReadMode.MASTER)
            .setMasterConnectionPoolSize(Integer.parseInt(lambdaProperties.get(PropertiesKeyEnum.REDISSON_MASTER_CONNECTION_POOL_SIZE_PROP_KEY.getKeyName())))
            .setSlaveConnectionPoolSize(Integer.parseInt(lambdaProperties.get(PropertiesKeyEnum.REDISSON_SLAVE_CONNECTION_POOL_SIZE_PROP_KEY.getKeyName())))
            .setIdleConnectionTimeout(Integer.parseInt(lambdaProperties.get(PropertiesKeyEnum.REDISSON_IDLE_CONNECTION_TIMEOUT_PROP_KEY.getKeyName())))
            .setConnectTimeout(Integer.parseInt(lambdaProperties.get(PropertiesKeyEnum.REDISSON_CONNECT_TIMEOUT_PROP_KEY.getKeyName())))
            .setRetryAttempts(Integer.parseInt(lambdaProperties.get(PropertiesKeyEnum.REDISSON_RETRY_ATTEMPTS_PROP_KEY.getKeyName())));

    config.setCodec(new JsonJacksonCodec());
    return Redisson.create(config);
```

However the entry still not deleted from the RMap. If I specify the exact key the removal is working, it's just that the getting the keyset from map using pattern does not return me anything. Did you have any other theory on why it could be the case?

Thanks Again,

Leo

**Comment by mrniko** [comment]
try to get map instance like this:

```java
RMap<String, Object> map = redisson.getMap("simple12", new CompositeCodec(StringCodec.INSTANCE, new MarshallingCodec()));
```

To make pattern search work key should be stored as pure string

**Comment by tarjadil2q** [comment]
Hi Nikita, 

Thanks for your reply, it does not work for Object which is serialized using Redisson JsonJacksonCodec. I have two entries for testing, one is key of 1000limit5 which have String as basic value, while the other one 100011176limit5offset2 is a Serialized JavaObject, the first one removal by pattern works using your provided Codec above, however the second one don't.

Code:
 
```
public static void main(String[] args) {
    JsonJacksonCodec jsonJacksonCodec = new JsonJacksonCodec();
    RedissonClient redissonClient = redissonConfig(jsonJacksonCodec);
    RMap<Object, Object> testMap = redissonClient.getMap("jsonCollectionsV3",
                                                         new CompositeCodec(StringCodec.INSTANCE,
                                                                            new MarshallingCodec()));
    testMap.putIfAbsent("1000limit5", "Testing");
    System.out.println("Map size are " + testMap.size());
   /* for (Object key : testMap.keySet()) {
      System.out.println("Key " + key);
    }*/
    Set<Object> objects = testMap.keySet("1000*");
    System.out.println("key set size found base on pattern are " + objects.size());
    for (Object key : objects) {
      System.out.println("Key found is " + key);
      //remove by pattern found
      long resultLong = testMap.fastRemove(key);
      System.out.println("After removing key " + key + " number of removed record(s) size " + resultLong);
    }
    String key = "100011176limit5offset2";
    //exact key remove
    long result = testMap.fastRemove(key);
    System.out.println("After removing key " + key + " number of removed record(s) size " + result);
  }
  public static RedissonClient redissonConfig(JsonJacksonCodec jsonJacksonCodec) {
    Config config = new Config();
    config.setCodec(jsonJacksonCodec);
    config.useReplicatedServers()
            .addNodeAddress(redisAdress.split(","))
            .setIdleConnectionTimeout(3000)
            .setConnectTimeout(3000)
            .setRetryAttempts(2)
            .setTimeout(3000);
    return Redisson.create(config);
  }
```

Output:

```
Map size are 2
key set size found base on pattern are 1
Key found is 1000limit5
After removing key 1000limit5 number of removed record(s) size 1
After removing key 100011176limit5offset2 number of removed record(s) size 0
```

![keyNotDeleted](https://user-images.githubusercontent.com/20692311/91630631-2dfda880-ea16-11ea-927e-9812f76296e6.png)

The second key 100011176limit5offset2 has not matched the pattern, I think it is because we are using Redisson JsonJacksonCodec for our serialization. If you see from output above, direct removal by exact key is not working when I specify the CompositeCodec. What is also weird, when I try to pass in the JsonJacksonCodec instead of MarshallingCodec, it is not working as well, both pattern and direct key removal for 100011176limit5offset2 key.

Hopefully, you can help me with this issue, I am running out of clue.. Thanks!

**Comment by mrniko** [comment]
> I have two entries for testing, one is key of 1000limit5 which have String as basic value, while the other one 100011176limit5offset2 is a Serialized JavaObject, the first one removal by pattern works using your provided Codec above, however the second one don't.

To make pattern search work key should be stored as pure string.

**Comment by tarjadil2q** [comment]
But the first records with key 1000limit5 working Nikita, you mean the key which is 1000limit5 or the value?

**Comment by tarjadil2q** [comment]
Hi Nikita,

I think I understand what you mean now. it is about the double quote that surrounding the key, as when it is serialized it is treated as JSON by the default serializer.

I search the net for a solution and there some suggestions to re-configure Key Serializer to use  StringRedisSerializer to remove the double quote on the key when it is stored on Redis database.
 
https://programmersought.com/article/67461332574/
and https://stackoverflow.com/questions/13215024/why-is-data-getting-stored-with-weird-keys-in-redis-when-using-jedis-with-spring  (this one is for jedis though, but I think the principle the same?)

I have tried configuring those and also configured RedissonConnectionFactory as per this, as the factory is required to get the RedisTemplate. https://github.com/redisson/redisson/tree/master/redisson-spring-data

So I can configure the RedisTemplate and re-configured the Redis key serializer to use StringRedisSerializer.

Here is my config so far.

```
@Bean(destroyMethod = "shutdown", name = "redissonClient")
  public RedissonClient redisson() {
    Config config = new Config();
    config.useReplicatedServers()
            .addNodeAddress(address.split(","))
            .setIdleConnectionTimeout(connectTimeout)
            .setConnectTimeout(connectTimeout)
            .setRetryAttempts(retryAttempts)
            .setTimeout(responseTimeoutInMillis);

    return Redisson.create(config);
  }

  @Bean("wcmsObjectMapper")
  ObjectMapper getObjectMapper(Jackson2ObjectMapperBuilder jacksonObjectMapperBuilder){
    return jacksonObjectMapperBuilder.build();
  }

  @Bean("cacheManager")
  @DependsOn("redisTemplate")
  CacheManager cacheManager(RedissonClient redissonClient,
                            @Qualifier("wcmsObjectMapper")ObjectMapper objectMapper,
                            MeterRegistry meterRegistry) {
    Map<String, CacheConfig> config = new HashMap<>();

    config.put(CapiConstants.CONTENT_CACHE_NAME_V3, new CacheConfig(ttlInMillis, maxIdleTimeInMillis));
    config.put(CapiConstants.DYNAMIC_CONTENT_CACHE_NAME_V3, new CacheConfig(ttlInMillisDynamic, maxIdleTimeInMillis));
    config.put(CapiConstants.COLLECTION_CACHE_NAME_V3, new CacheConfig(ttlInMillisCollection, maxIdleTimeInMillis));
    config.put(CapiConstants.DYNAMIC_COLLECTION_CACHE_NAME_V3, new CacheConfig(ttlInMillisCollectionDynamic, maxIdleTimeInMillis));

    // Codec to apply the configured customer serializers and deserializers
    Codec codec = new JsonJacksonCodec(objectMapper);
    RedissonSpringCacheManager redissonSpringCacheManager = new RedissonSpringCacheManager(redissonClient, config, codec);

    //Configure monitoring
    RedissonCache contentCache = (RedissonCache) redissonSpringCacheManager.getCache(CapiConstants.CONTENT_CACHE_NAME_V3);
    RedissonCache dynamicCollectionCache = (RedissonCache) redissonSpringCacheManager.getCache(CapiConstants.DYNAMIC_COLLECTION_CACHE_NAME_V3);
    RedissonCache dynamicFieldCache = (RedissonCache) redissonSpringCacheManager.getCache(CapiConstants.DYNAMIC_CONTENT_CACHE_NAME_V3);
    RedissonCache staticCollectionCache = (RedissonCache) redissonSpringCacheManager.getCache(CapiConstants.COLLECTION_CACHE_NAME_V3);
    if (contentCache != null && dynamicCollectionCache != null && dynamicFieldCache != null && staticCollectionCache != null) {
      RedissonCacheMetrics.monitor(meterRegistry, contentCache, Tags.empty());
      RedissonCacheMetrics.monitor(meterRegistry, dynamicCollectionCache, Tags.empty());
      RedissonCacheMetrics.monitor(meterRegistry, dynamicFieldCache, Tags.empty());
      RedissonCacheMetrics.monitor(meterRegistry, staticCollectionCache, Tags.empty());
    }
    customCacheErrorHandler = new CustomCacheErrorHandler(meterRegistry);
    return redissonSpringCacheManager;
  }

  @Bean
  @DependsOn("redissonClient")
  public RedissonConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
    return new RedissonConnectionFactory(redisson);
  }

  @Bean("redisTemplate")
  public RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory,
                                                     @Qualifier("wcmsObjectMapper")ObjectMapper objectMapper) {
    Jackson2JsonRedisSerializer<Object> jackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer<>(Object.class);

    objectMapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY);
    objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);
    jackson2JsonRedisSerializer.setObjectMapper(objectMapper);
    RedisTemplate<Object, Object> template = new RedisTemplate<>();
    template.setConnectionFactory(redisConnectionFactory);


    template.setKeySerializer(new StringRedisSerializer());

    template.setValueSerializer(jackson2JsonRedisSerializer);
    template.setHashKeySerializer(jackson2JsonRedisSerializer);
    template.setHashValueSerializer(jackson2JsonRedisSerializer);
    template.afterPropertiesSet();
    return template;

  }

  @Override
  @DependsOn("cacheManager")
  public CacheErrorHandler errorHandler() {
    return customCacheErrorHandler;
  }
```

However, when I run the application I got this error.

```
[2020-08-30 14:54:44.302] [main] []  WARN  DefaultGauge - Failed to apply the value function for the gauge 'cache.size'. Note that subsequent logs will be logged at debug level.
org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:109)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:609)
	at org.redisson.command.CommandAsyncService.readAsync(CommandAsyncService.java:372)
	at org.redisson.RedissonMap.sizeAsync(RedissonMap.java:157)
	at org.redisson.RedissonMap.size(RedissonMap.java:152)
	at org.redisson.spring.cache.RedissonCacheMetrics.size(RedissonCacheMetrics.java:51)
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.lambda$bindTo$0(CacheMeterBinder.java:52)
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54)
	at io.micrometer.core.instrument.Measurement.getValue(Measurement.java:39)


```

I am not sure why is that throwing that exception, appreciate your help and if you can tell me If I am in the right direction or not..



Thanks,
Leo

**Comment by mrniko** [comment]
Seems you invoke RedissonClient shutdown somethere. You could debug it

**Comment by tarjadil2q** [comment]
Hi Nikita,

I am doing an alternative solution right now, and it seems to work.

When getting the map I am using the following:
`redissonClient.getMap(cacheKey, StringCodec.INSTANCE);`
Then when removing entries through pattern I am using the following to find the matching records:
`String pattern = "*" + contentId + "?limit" +"*";`

Above * prefix is to ensure it captures the double quote at the beginning. 

Thanks again for your help Nikita!
