### ISSUE TITLE
Cannot cast object 'UNKNOWN-UNKNOWN' with class 'eu.bitwalker.useragentutils.UserAgent' to class 'eu.bitwalker.useragentutils.UserAgent'

### ISSUE THREAD

**Issue by agusl88** [redisson/redisson#3017]
Hi,

I'm trying to setup redisson for tomcat 8, and i'm getting this exception at the start:

`org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'UNKNOWN-UNKNOWN' with class 'eu.bitwalker.useragentutils.UserAgent' to class 'eu.bitwalker.useragentutils.UserAgent'`

I think it may be related to incorrect dependencies? In order to get the tomcat to start withouth errors, i had to manually add some libraries to the tomcat instance because redisson was failing with multiple exceptions related to classNotFound, these are the dependecies i had to add:

- fst-2.57.jar
- objenesis-3.1.jar
- UserAgentUtils-1.21.jar

This is the redisson.conf i'm using

`{
  "singleServerConfig": {
    "idleConnectionTimeout": 10000,
    "connectTimeout": 10000,
    "timeout": 3000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "password": null,
    "subscriptionsPerConnection": 5,
    "clientName": null,
    "address": "redis://xxxxx.0001.use1.cache.amazonaws.com:6379",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "connectionMinimumIdleSize": 24,
    "connectionPoolSize": 64,
    "database": 0,
    "dnsMonitoringInterval": 5000
  },
  "threads": 16,
  "nettyThreads": 32,
  "codec": null,
  "transportMode": "NIO"
}`

**Comment by mrniko** [comment]
try to update to 3.13.3 version

**Comment by agusl88** [comment]
i'm already using that version, **redisson-all-3.13.3.jar** and **redisson-tomcat-8-3.13.3.jar**

**Comment by mrniko** [comment]
if you didn't define coded then MarshallingCodec is used and this issue is the same as https://github.com/redisson/redisson/issues/2984

**Comment by mrniko** [comment]
Could you try this version https://github.com/redisson/redisson/issues/2984#issuecomment-677187225 ?

**Comment by agusl88** [comment]
the 3.13.4 fixed the problem, thanks!
