### ISSUE TITLE
a question about lock acquisition

### ISSUE THREAD

**Issue by WongJiYong** [redisson/redisson#3018]
**I have a question about lock acquisition.**
assume two services A and B acquire locks to access shared resources.
 1. A has acquired the lock.
 2. When B tries to acquire the lock. it will find the lock is held by other service(A).
 3. So B will subscribe to the channel, for acquiring the lock.
 4. before B subscribe to the channel,A release the lock and publish some messages.
**What happens next?**
B is waiting for the messages that is published by the lock holder(A), but A has published the messages and released the lock.
How did you solve it?

I'm sorry I didn't understand the source code,Thank you very much for your work.

**Comment by mrniko** [comment]
> before B subscribe to the channel,A release the lock and publish some messages.
What happens next?
B is waiting for the messages that is published by the lock holder(A), but A has published the messages and released the lock.
How did you solve it?

It will try to acquire the lock after subscription and then wait for a message on the subscribed pubsub channel.
