### ISSUE TITLE
使用pipeline时抛出UnsupportedOperationException异常

### ISSUE THREAD

**Issue by dwkfxj** [redisson/redisson#3021]
调用代码：
List<String> resultList = redisTemplate.executePipelined((RedisCallback<String>)connection -> {
            for (Long id: idList) {
                connection.get(key.getBytes());
            }
            return null;
        }, redisTemplate.getValueSerializer());
**Expected behavior**

**Actual behavior**
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.remove(AbstractList.java:161)
        at org.redisson.spring.data.connection.RedissonConnection.filterResults(RedissonConnection.java:1534)
        at org.redisson.spring.data.connection.RedissonConnection.closePipeline(RedissonConnection.java:162)
**Steps to reproduce or test case**

**Redis version**
5.0
**Redisson version**
3.13.1
**Redisson configuration**

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by dwkfxj** [comment]
Fixed in 3.13.4？

**Comment by dwkfxj** [comment]
if (result.getResponses().isEmpty()) {
            return;
}

In my case, `result.getResponses()` is not empty,
and the UnsupportedOperationException is thrown by `AbstractList#remove()`.
Are you sure this BUG is fixed?

**Comment by mrniko** [comment]
Yes, since UnsupportedOperationException is thrown only for empty collections.

**Comment by dwkfxj** [comment]
OK,Thanks.
But how to get 3.13.4?
Latest version in `https://mvnrepository.com/search?q=redisson` is 3.13.3

**Comment by mrniko** [comment]
it's not released yet

**Comment by dwkfxj** [comment]
OK, when will it be released? This bug has caused an online problem.
