### ISSUE TITLE
`RBucket.set()` method is fully thread-safe, but I wouldn't recommend to use blocking operations in netty threads

### ISSUE THREAD

**Issue by tatsuya-0714** [redisson/redisson#3024]
@mrniko 

> `RBucket.set()` method is fully thread-safe, but I wouldn't recommend to use blocking operations in netty threads

Doesn't it mean that the blocking operation (such as "RBucket.set()") cannot be thread-managed (multithreaded(parallelization)) only by the logic in redisson without using another library (such as "Spring's ThreadPoolTaskExecutor")?

_Originally posted by @mrniko in https://github.com/redisson/redisson/issues/3022#issuecomment-684689931_

**Comment by mrniko** [comment]
fully thread-safe means multithreaded. RTopic listeners, RRemoteService invocations and RExecutorService tasks are executed in seprate executor service, so you can use any blocking commands there.
