### ISSUE TITLE
sessionDestroyedMessage  and sessionCreatedMessage question

### ISSUE THREAD

**Issue by 201528013329027** [redisson/redisson#3028]
- version: 3.11.6

- config: 

`	<Manager className="org.redisson.tomcat.RedissonSessionManager"
	         configPath="${catalina.base}/src/test/webapp/WEB-INF/redisson.yaml"
			 readMode="REDIS"
			 updateMode="DEFAULT"
	         broadcastSessionEvents="true"/>`

- question:

we have two server: A, B

1.  when `session.setAttribute(key, value);` on A server

2.  `session.invalidate();` on B server.  

3.  `session.setAttribute(key, value);` on A server,

4. now `session.getAttribute(key);` on B server will return null

why this happened?

**Comment by mrniko** [comment]
Could you share redisson logs for both servers? (set logging level = `TRACE` for `org.redisson` package)
