### ISSUE TITLE
Sentinel and Redis Different password

### ISSUE THREAD

**Issue by amirbayan** [redisson/redisson#3030]
There is no configuration for sentinel password, you are using the same password flag to be used for sentinel and redis, and by that way I am obliged to set the same password for redis and sentinel, so can't we have a different yml property special for sentinel password?

**Comment by ghollies** [comment]
We ran into this issue also and were unable to configure a distinct password for sentinel.
I something like https://github.com/redisson/redisson/pull/3097 will work. We are testing out the patch ourselves, but would love for this capability to be included in an upcoming version.

**Comment by amirbayan** [comment]
Hello @ghollies 
Thanks for your reply. so I will wait for the PR to be merged and will use it in the upcoming version.

**Comment by lusu007** [comment]
We ran into this issue too. I think we should be able to set a seperate Sentinel password. In my opinion having no password set in Sentinel is a vulnerability.

**Comment by f-ld** [comment]
Being able to have different password configuration for redis and sentinel is a must.

**Comment by mrniko** [comment]
merged
