### ISSUE TITLE
Is there a fast and efficient way to get a count of all entries in a RMultimap?

### ISSUE THREAD

**Issue by peterlitvak** [redisson/redisson#3032]
With a regular RMap the size() is very quick and efficient but it doesn't seem that there is a way to get the total size of a multimap in the same way. What I mean by total size is the sum of sizes of all of the values (collections) of a multimap.

**Comment by mrniko** [comment]
Just use `RMultimap.size()` method

**Comment by peterlitvak** [comment]
Unfortunately it doesn't count the elements in the RSets that are sure as values

**Comment by mrniko** [comment]
Unable to reproduce it with following test:

```java
        RSetMultimap<String, Integer> multimap = redisson.getSetMultimap("myMultimap1");
        multimap.put("1", 1);
        multimap.put("1", 2);
        multimap.put("1", 3);
        multimap.put("2", 4);
        multimap.put("3", 5);

        assertThat(multimap.size()).isEqualTo(5);
```

**Comment by peterlitvak** [comment]
you are correct, there was probably an issue with my tests that used size() method
