### ISSUE TITLE
Understanding sizeInMemory

### ISSUE THREAD

**Issue by peterlitvak** [redisson/redisson#3033]
I'm wondering what exactly is reported by sizeInMemory() method. The doc says it is "Returns bytes amount used by object in Redis memory".

I'm looking at the numbers this method reports say for the RSet of strings and it is much smaller than byte count of the strings stored in the RSet. Does it mean that the data is stored compressed in REDIS?

Also is my understanding correct that for RSetMultimap to find the total size of it in memory one needs to add value returned by sizeInMemory() for the map itself and then the value returned by sizeInMemory() for all of the RSets stored in that map?

**Comment by mrniko** [comment]
> I'm looking at the numbers this method reports say for the RSet of strings and it is much smaller than byte count of the strings stored in the RSet. Does it mean that the data is stored compressed in REDIS?

probably you use compression codec on Redisson side. For example below I have got size in memory: 236 bytes.

```java
        RSet<String> set = redisson.getSet("set", StringCodec.INSTANCE);
        set.add("test1");
        set.add("test2");
        set.add("test3");
```

You are right regarding `RSetMultimap.sizeInMemory()` method. Currently it doesn't take in account size of all RSet objects. I'm opening a bug https://github.com/redisson/redisson/issues/3034

**Comment by peterlitvak** [comment]
Thank you!
