### ISSUE TITLE
Migration form 3.12 to 3.13. FST to Marshalling Codec migration without downtime

### ISSUE THREAD

**Issue by mimarko** [redisson/redisson#3036]
We have multiple instance of web app and all pointing to same AWS Elasticache (redis). When new version deployed some of them will use old Redisson lib (with previous default codec, FST).
Any suggestion appreciate to deploy new version with new codec smoothly without downtime?

Thanks in advance 
Marko

**Comment by mrniko** [comment]
Just define FST codec in configuration, so MarshailingCodec won't be used. There is no seamless way for such transition.
