### ISSUE TITLE
Allow RedissonClient construction with no redis availability

### ISSUE THREAD

**Issue by kazetsukaimiko** [redisson/redisson#3042]
**Is your feature request related to a problem? Please describe.**
This is for SingleServerConfigs.

Occasionally during deployment the redis instance comes up after our services. When injecting RedissonClients using Spring @Bean or CDI @Produces, the RedissonClient dependency will fail with an exception upon construction.

**Describe the solution you'd like**
When your connection pool minimums are set to 0, RedissonClient instances should be able to be constructed without redis being available.

Any operations with no connections in the pool should attempt a connection. Failing that, fail accordingly. It would be nice to have a "target pool size" in addition to an actual minimum- so that I can have a minimum of 0 but aim to have 10 or more, etc.

**Describe alternatives you've considered**
We'd have to inject some form of Supplier<RedissonClient> instead, this is not ideal. The client is the owner of the pool, us doing that is taking on those connection pool management concerns.

**Comment by mrniko** [comment]
Done. Use [lazyInitialization](https://github.com/redisson/redisson/wiki/2.-Configuration#lazyinitialization) setting
