### ISSUE TITLE
redisson-3.13.1 throws java.lang.ClassCastException for gets when used with AWS Elasticache Cluster mode enabled

### ISSUE THREAD

**Issue by SaiP061** [redisson/redisson#3045]
**Expected behavior**
We currently use Redisson 3.11.5 with AWS Elasticache Cluster mode enabled. Gets using RBuckets works well.
When we tried to upgrade to Redisson 3.13.1, we expected gets should work seemlessly without issue

**Actual behavior**
But When we tried to upgrade to 3.13.1, started to see ClassCastExceptions.

I have tried to look into scenarios on when this was happening.

Looks like it happens whenever redission client is seeing MOVED response from connected redis node

Issue get resovled immediately when we rollback to 3.11.5

questions: 
* is there something different in cluster mode handling in 3.13.1?
* Looks  like 3.11.5 rightly resolve to right slot and node and is able to cast payload correctly. But  with 3.13.1 something is broken.

**Steps to reproduce or test case**

**Redis version**
5.0.6
**Redisson version**
3.13.1
**Redisson configuration**

**Comment by mrniko** [comment]
please share stacktrace and code example to reproduce the issue.
