### ISSUE TITLE
Is there configs suggestions

### ISSUE THREAD

**Issue by ieiayaobb** [redisson/redisson#3049]
Hi, is there any suggestions for configuring these 'size' values based on the config of Redis server
- threads
- nettyThreads
- masterConnectionPoolSize
- masterConnectionMinimumIdleSize
- slaveConnectionPoolSize
- slaveConnectionMinimumIdleSize
- subscriptionConnectionPoolSize
- subscriptionConnectionMinimumIdleSize

For example, my Redis cluster server:
 - 8 vCPU
 - 26 GB memory
 - 4 instances (2 slots) 
 - 50 consumers

I know it may depend on the commands I am using, so I just want to know a basic suggestion.
Is there any formula I can follow for configuring?

**Comment by mrniko** [comment]
I'm afraid there is no formula. Settings depend on each use case.
