### ISSUE TITLE
RBloomfilter need addAll

### ISSUE THREAD

**Issue by ChenYilei2016** [redisson/redisson#3050]
RBloomFilter only have      
boolean add(T object);

**Comment by vaibhavdesai16** [comment]
@mrniko I would like to add code for this issue. Is it a good idea to loop through the list of objects and call boolean add(T object) inside the loop?

public void addAll(List<T> elements) {
       for(T element : elements){
           try{
               add(element);
           }
           catch (RedisException e){
               if (e.getMessage() == null || !e.getMessage().contains("Bloom filter config has been changed")) {
                   throw e;
               }
           }
       }
    }

**Comment by Patrick0308** [comment]
@vaibhavdesai16 It's inefficiency. We need a batch mode to add list.

**Comment by Patrick0308** [comment]
I will work on it.

**Comment by ShepherdZFJ** [comment]
> @vaibhavdesai16 It's inefficiency. We need a batch mode to add list.

Do you have a good solution to this problem?

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/5130
