### ISSUE TITLE
未加unlock()时第十一次返回true,  

### ISSUE THREAD

**Issue by qcncomll** [redisson/redisson#3051]
![image](https://user-images.githubusercontent.com/10806857/93098703-c021d400-f6d9-11ea-8fe0-80241e86bbcb.png)

如上图， 在未加unlock()时， 发送请求第一次lockFlag = true,  第二次到第十次是false，第十一次是true。可以看出每10次时是true，但是没加unclok()，按理来说不管请求多少次都返回false， 这是不是bug？

**Comment by yydzxz** [comment]
> ![image](https://user-images.githubusercontent.com/10806857/93098703-c021d400-f6d9-11ea-8fe0-80241e86bbcb.png)
> 
> 如上图， 在未加unlock()时， 发送请求第一次lockFlag = true, 第二次到第十次是false，第十一次是true。可以看出每10次时是true，但是没加unclok()，按理来说不管请求多少次都返回false， 这是不是bug？

锁是会自动释放的啊,不然获取到锁的线程挂了,不就全完蛋了

**Comment by yydzxz** [comment]
你可以在代码里面打印下`Thread.currentThread().getId()`, 然后你就知道为什么了
