### ISSUE TITLE
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: NA:6379 

### ISSUE THREAD

**Issue by JunjianS** [redisson/redisson#3055]
redisson: 3.13.0

@mrniko 
i see  this issue was fixed in 3.13.3, and there is no problem, after upgraded to 3.13.3. could you please post the cause of the issue ?  and how to reproduce it ?  thank you very much.

**Comment by mrniko** [comment]
you can look at code changes here https://github.com/redisson/redisson/commit/d6c3f64ced346c3833d68b6a6ebf21d38201b27a
