### ISSUE TITLE
tomcat-redisson session.getAttributeNames not honoring loadedAttributes

### ISSUE THREAD

**Issue by ghollies** [redisson/redisson#3057]
**Expected behavior**
When using readMode=REDIS and updateMode=AFTER_REQUEST
session.setAttribute("a","b")
session.getAttributeNames() should include "a"

**Actual behavior**
session.getAttributeNames() does not include values cached in loadedAttributes map, and goes directly to redis, which has not yet received the new information.

**Steps to reproduce or test case**
see https://github.com/redisson/redisson/commit/86ac2aafcda806e2f4c9cb4b59ccb55ec66dea2b for work around that solved the issue

**Redis version**

**Redisson version**
3.14.4

**Redisson configuration**
readMode=Redis
updateMode=after request

**Comment by mrniko** [comment]
Fixed. Thanks for suggested changes. By the way we don't need to remove attrs from removedAttributes, since loadedAttributes updated if attribute removed.
