### ISSUE TITLE
RedissonSession map doesn’t have expiration after changeSessionId is called

### ISSUE THREAD

**Issue by eager** [redisson/redisson#3059]
We noticed a large number of keys in our Redis server had no TTL set and traced it back to the `RMap` that backs the session.

**Comment by mrniko** [comment]
I think I could deprecate my own Spring Session Manager in favour of Spring's implementation. I wrote this Manager when Redisson didn't have spring-data-redis implementation. And now it has it and since Spring's implementation based on it we Redisson Spring Session Manager could be dropped. What do you think?

**Comment by eager** [comment]
> I think I could deprecate my own Spring Session Manager in favour of Spring's implementation

@mrniko this makes sense to me, and it looks like it will be a quick change for us to switch to Spring’s session repository.

We should note that it’s not quite a drop-in change, because the keys don’t quite align: Spring does [`prefix + ":sessions:" + id`](https://github.com/spring-projects/spring-session/blob/e46610f53ada038194bc262857264e62727e4737/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L593), while Redisson does [`prefix + id`](https://github.com/redisson/redisson/blob/287dd1dc416cf300ccfc7ef4952f719549837b85/redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java#L95).

**Comment by eager** [comment]
> > I think I could deprecate my own Spring Session Manager in favour of Spring's implementation
> 
> this makes sense to me, and it looks like it will be a quick change for us to switch to Spring’s session repository.

After a bit more investigation, there’s one blocker for this: Spring’s implementation unconditionally [uses `rename` in `changeSessionID`](https://github.com/spring-projects/spring-session/blob/e6e02de210db41a86f283ece0d9f0b78ed27e864/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L837), which causes `CROSSSLOT` errors (the same as #1897).

It looks like other implementations of `RedisConnection` have special handling for `rename`: if the new key hashes to a different slot, it uses `dump`, `restore` and `del` to emulate the command. I can open a PR, if this sounds reasonable.

**Comment by mrniko** [comment]
> I can open a PR, if this sounds reasonable.

Yeah, I would consider it.

**Comment by eager** [comment]
> > I can open a PR, if this sounds reasonable.
> 
> Yeah, I would consider it.

@mrniko great—let me know what you think of #3141

**Comment by mrniko** [comment]
merged.

Documentation updated https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#147-spring-session
