### ISSUE TITLE
Unexpected ClassCastException

### ISSUE THREAD

**Issue by ieiayaobb** [redisson/redisson#3063]
**Expected behavior**
Return entity or NULL as expecting
**Actual behavior**
Throw ClassCastException
**Steps to reproduce or test case**
This only happens when we upgrade Redisson from 3.10.0 to 3.10.7 and in only happens in one of our environments.
The detail of ClassCastException will be shows like 'Cannot cast 'xxx.yyy.zzz.ClassA' to 'xxx.yyy.zzz.ClassA' (The path are totally the same) or 'org.redisson.spring.cache.NullValue' cannot be cast to '....'
It only happen once and I cannot reproduce from my local.
When I clear the whole Redis, this exception will pause for a while, but after some time, it will happen again
**Redis version**
5.0.0
**Redisson version**
From 3.10.0 to 3.10.7
**Redisson configuration**

**Comment by mrniko** [comment]
Please share exception stacktrace

**Comment by ieiayaobb** [comment]
I cannot share much information because it contains many sensitive messages.
Below are 2 root cases I found in log
```java.lang.ClassCastException: org.redisson.spring.cache.NullValue cannot be cast to java.util.List```
```java.lang.ClassCastException: com.xxx.yyy.core.model.Country cannot be cast to com.xxx.yyy.core.model.Country```

**Comment by mrniko** [comment]
Unable to reproduce the issue with the latest version
