### ISSUE TITLE
Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379

### ISSUE THREAD

**Issue by yanzhisishui** [redisson/redisson#3065]
@Bean
    public RedissonClient redissonClient(){
        Config config = new Config();
        String redisUrl = String.format("redis://%s:%s",redisProperties.getHost()+"",redisProperties.getPort()+"");
        config.useSingleServer().setAddress(redisUrl).setPassword(redisProperties.getPassword());
        config.useSingleServer().setDatabase(3);
        return Redisson.create(config);
    }

请问这是什么问题呢。。。。

**Comment by mrniko** [comment]
check your network

**Comment by yanzhisishui** [comment]
我用Redis客户端都可以连上的，springboot里面也可以使用redistemplate，网络没问题呢。很迷茫 不知道为啥会报这个错误，是不是还有其他配置啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nikita Koksharov"<notifications@github.com&gt;; 
发送时间: 2020年9月21日(星期一) 下午3:59
收件人: "redisson/redisson"<redisson@noreply.github.com&gt;; 
抄送: "Never Part Too"<1481232419@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [redisson/redisson] Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379 (#3065)





 
check your network

**Comment by yanzhisishui** [comment]
找到问题了，我的redis没有密码，把setPassword去掉就行了
