### ISSUE TITLE
Question about fix for issue 2181

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#3067]
Recently we got below error after Redis M/S switchOver at Redisson 3.10.1:
org.redisson.client.RedisTimeoutException: Subscribe timeout: (9500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.

And i saw it was fixed at 3.11.2 by: https://github.com/redisson/redisson/issues/2181 

I have one question about the fix: https://github.com/redisson/redisson/commit/12e81de984698d06b3dbc236bac00479ec7e3d61  

reattachPubSub method was only called in MasterSlaveEntry.slaveDown. What will happen in Redis M/S switchover
in case we configure  "subscriptionMode: "MASTER""? To my understanding:
 slaveDown should not impact subscription as we configured Mode to master.

**Comment by mrniko** [comment]
> reattachPubSub method was only called in MasterSlaveEntry.slaveDown

I'm afraid you're mistaken. Have a look closer. It's invoked in both cases: slave down and master down (failover)

**Comment by empty117** [comment]
@mrniko : Thanks, i was checking 3.12.2 code ,that was called only from "slave Down", now in latest it's from both.

**Comment by empty117** [comment]
@mrniko : I just wonder to confirm if this BUG still existing in 3.12.2 when configure "subscriptionMode: "MASTER""? From code i see fix was applied after 3.12.2(call reattachPubSub  when master down). If my understand is correct, could you help me to know this fix was from which release? Thanks a lot.

**Comment by empty117** [comment]
Well , i found one issue: https://github.com/redisson/redisson/issues/2825 

Seems that fix was from 3.13.1.

**Comment by mrniko** [comment]
I think yes. I would recommend you to update to 3.13.1 version or the latest version
