### ISSUE TITLE
RObjectLiveService#delete: incorrect behavior of delete(Class<PRoxy>, ID... ) method

### ISSUE THREAD

**Issue by GenCloud** [redisson/redisson#3073]
**Expected behavior**
Correct long result with the number of objects removed.

**Actual behavior**
Current call of RLiveObjectService#delete(Class<RProxy>, ID...) raises an error converting the result to type Long.

**Steps to reproduce or test case**
1) Create simple entity with some r-indexes

```java
@REntity
@Data // auto generated getName/setName/getId/setId/equals/hashCode
public class Entity implements Serializable {
    @RId(generator = LongGenerator.class)
    private Long id;
    
    @RIndex
    private int idx1;
    @RIndex
    private int idx2;
}
```

2) Persist and delete entity
```java
public void test() {
        final RLiveObjectService liveObjectService = PersistenceStateManager.getInstance()
                .getSyncClient().getLiveObjectService();
        liveObjectService.registerClass(Entity.class);
        
        Entity entity = new Entity();
        entity.setIdx1(1);
        entity.setIdx2(2);

        entity = liveObjectService.persist(entity);
        liveObjectService.delete(Entity.class, entity.getId());
}
```

3) See throwed exception:
```java.lang.ClassCastException: Boolean to Long``` 

E.g. in debug mode, I see that in the RedissonLiveObjectService #delete(Class<RType>, ID...)#574 method there are 3 commands to delete both the entity and the entity indexes. The commands for deleting indexes return the result "true", and the command for deleting the entity itself - "long", where the next action is the addition of the results of command execution.

```return r.getResponses().stream().mapToLong(s -> s).sum()```

Solutions to the problem:
- to identify commands by type (entity, index, etc.) and give the real result of deleting only the main object. Service commands related to the deleted object - do not take into account, otherwise we get unreliable information)

**Redis version**
6.0.6

**Redisson version**
3.13.4

**Redisson configuration**
standard single server (only host and port)

**Comment by mrniko** [comment]
Fixed! Thanks for report
