### ISSUE TITLE
why traverse all the keys?

### ISSUE THREAD

**Issue by StyleTJy** [redisson/redisson#3079]
https://github.com/redisson/redisson/blob/7eb4c4fb4911cbc52a2c665f3c7b3eac0800941e/redisson/src/main/java/org/redisson/RedissonReadLock.java#L106

here `HKEYS` operation and `for loop` would be very time-comsuing, I thought the KEYS[1] is renewed when the last lock set. is these traverse necessary?

**Comment by mrniko** [comment]
Yes, it's necessary and could be time-consuming in case of thousands of read locks.

**Comment by StyleTJy** [comment]
> Yes, it's necessary and could be time-consuming in case of thousands of read locks.

what if I removed these code, just `return 0` when `hlen KESY[1] > 1`. 
I know one circumstance, when the last key unlocked earlier than any other read keys, the ttl of KEYS[1] would be longer than the longest ttl of `KEYS[4]..':'..key..':rwlock_timeout:'..i`
so what will happen?

**Comment by mrniko** [comment]
we can't remove this code since we need to know `maxRemainTime`
