### ISSUE TITLE
RScript.Mode.READ_ONLY... not read only?

### ISSUE THREAD

**Issue by joshattr** [redisson/redisson#308]
I have a script that deletes some things. Here's how I'm executing it:

``` java
myRScript.evalSha(Mode.READ_ONLY, mySha, ReturnType.BOOLEAN, myKeyNames);
```

It's working (deleting things). This is confusing to me. Shouldn't `Mode.READ_ONLY` not allow that? I think what is happening is this is using redis' [`READONLY`](http://redis.io/commands/readonly) command, which _I think_ is okay with letting me change data, as long as I'm not hitting a slave (which I'm not, because I'm only running one node locally). I think this will cause an issue once I run this on something like [Amazon's ElastiCache](https://aws.amazon.com/elasticache/).

Do you know if my assumptions about what's happening are correct? I wasn't able to figure that out. If so, maybe adding some documentation to [that enum](https://github.com/mrniko/redisson/blob/ca2ea59a9602ebdfdb5665b4fb8b86a400534078/src/main/java/org/redisson/core/RScript.java#L26) would make things less confusing. If not, maybe there's a bug? Anyway I'll start using `Mode.READ_WRITE`, but I thought it was strange that `Mode.READ_ONLY` worked too, so I figured I'd report it.

**Comment by mrniko** [comment]
with Mode.READ_ONLY redisson executes script on slave node. with READ_WRITE it uses master server to execute script. Could you provide your redisson settings?

**Comment by joshattr** [comment]
Ahh, it's not a bug then. Could use a documentation update though (imo) :smile:. Here's my config (though I don't think it's relevant):
```java
@Bean
public Redisson redisson()
{
    Config config = new Config();

    config.useSingleServer().setAddress(redisAddress);
    config.setCodec(new JacksonCodecWithJava8Time());

    return Redisson.create(config);
}
```
