### ISSUE TITLE
ElastiCache fail over with primary/reader endpoints not working with replicatedServersConfig

### ISSUE THREAD

**Issue by dms486** [redisson/redisson#3080]
I'm currently working with an ElastiCache Redis Cluster (cluster mode disabled) and I have 3 nodes (1 primary node and 2 replica nodes). I'm working with an application configured with the Redisson Tomcat Session Manager. I'm currently testing the ElastiCache failover. I had to set the retryAttempts to 30, the retryInterval to 1000, and use the 3 node endpoints in the nodeAddresses, but with that I'm able to successfully fail over the ElastiCache cluster without disrupting the application. However, if I use only the primary endpoint (master) and the reader endpoint (replica) in the nodeAddresses an ElastiCache fail over disrupts the application. Are the primary/reader endpoints not supported with the replicatedServersConfig?

My configuration for the replicatedServersConfig and context.xml is below:

replicatedServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 30
  retryInterval: 1000
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "MASTER"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  "rediss://node-endpoint-1:6379"
  "rediss://node-endpoint-2:6379"
  "rediss://node-endpoint-3:6379"
  scanInterval: 1000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

Manager className="org.redisson.tomcat.RedissonSessionManager"
  configPath="${catalina.base}/redisson.conf" 
  readMode="MEMORY" updateMode="DEFAULT" broadcastSessionEvents="false"
  keyPrefix=""

**Comment by mrniko** [comment]
You need to define all node endpoints in configuration for non-clustered ElastiCache mode.

**Comment by dms486** [comment]
Thanks. If I switch to ElastiCache Redis Cluster (cluster mode enabled) and use clusterServersConfig, will I be able to use the configuration endpoint instead of the node endpoints?

**Comment by mrniko** [comment]
Sure

**Comment by dms486** [comment]
@mrniko is it possible to make this a feature request? Would help with maintenance if we could target the primary endpoint instead of the node endpoints directly

**Comment by mrniko** [comment]
> Would help with maintenance if we could target the primary endpoint instead of the node endpoints directly

You can do it in ElastiCache Redis Cluster
