### ISSUE TITLE
 org.redisson.tomcat.RedissonSessionManager.findSession Session can't be found

### ISSUE THREAD

**Issue by Spring1901** [redisson/redisson#3084]
my version  is redisson-all-3.13.4
redisson-tomcat-8-3.13.4

i have see the close question about this  and try it ,but it does not work.    my webproject is based on SSM+shiro

**Comment by mrniko** [comment]
could you set `TRACE` logging level for `org.redisson` package and share output?

**Comment by Spring1901** [comment]
thank you very much, i have find the question ,it is my question. it is ok now,
