### ISSUE TITLE
Subscribe timeout: (7500ms)

### ISSUE THREAD

**Issue by wittychen** [redisson/redisson#3085]
I Increase two params,but it doesn't work.Can you tell me the reason.

redission version: 3.13.4
error:
`        org.redisson.client.RedisTimeoutException: Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:118) ~[redisson-3.13.4.jar:3.13.4]
	at org.redisson.RedissonLock.lock(RedissonLock.java:185) ~[redisson-3.13.4.jar:3.13.4]
	at org.redisson.RedissonLock.lock(RedissonLock.java:147) ~[redisson-3.13.4.jar:3.13.4]`

my config:
`        Config config = new Config();
        String redisUrl = String.format("redis://%s:%s", redisProperties.getHost() + "", redisProperties.getPort() +
                "");
        config.useSingleServer()
                .setAddress(redisUrl)
                .setDnsMonitoringInterval(-1)
                .setSubscriptionConnectionPoolSize(200)
                .setConnectTimeout(30000).setSubscriptionsPerConnection(5000)
                .setSubscriptionConnectionMinimumIdleSize(64)
                .setPassword(redisProperties.getPassword())
                .setDatabase(redisProperties.getDatabase());`

my code:  Multi thread call
`        RLock lock = redissonClient.getLock(lockBizIdKey);
        try {
            lock.lock();
        } catch (Exception e) {
            log.info("bizTag = {}", bizTag, e);
        } finally {
            lock.unlock();
        }`

I use another redis server ,it works well. which param of redis can effect it?

**Comment by wittychen** [comment]
Maybe caused by Twemproxy.
How can I solve this problem.

**Comment by mrniko** [comment]
Can you reproduce it without twemproxy?

**Comment by wittychen** [comment]
> Can you reproduce it without twemproxy?

It works well without  twemproxy.
Do you have plans to support twemproxy?

**Comment by mrniko** [comment]
I'm afraid no.
