### ISSUE TITLE
org.redisson.tomcat.RedissonSessionManager memory leak

### ISSUE THREAD

**Issue by okskakitani** [redisson/redisson#3087]
It seems org.redisson.tomcat.RedissonSessionManager leaking memory.

**redisson version**
3.13.4

**tomcat**
9

**JDK**
openjdk version "11.0.8"

**tomcat integration**

>             <Manager className="org.redisson.tomcat.RedissonSessionManager"
>              configPath="${catalina.base}/conf/redisson.conf"
>              readMode="REDIS"
>              updateMode="DEFAULT"
>              broadcastSessionEvents="false"
>              keyPrefix=""/>

**redisson configurations.**

> ---
> singleServerConfig:
>   idleConnectionTimeout: 10000
>   connectTimeout: 10000
>   timeout: 10000
>   retryAttempts: 3
>   retryInterval: 1500
>   password: ******
>   subscriptionsPerConnection: 5
>   sslEnableEndpointIdentification: true
>   sslProvider: "JDK"
>   pingConnectionInterval: 0
>   keepAlive: false
>   tcpNoDelay: false
>   address: ******
>   subscriptionConnectionMinimumIdleSize: 1
>   subscriptionConnectionPoolSize: 50
>   connectionMinimumIdleSize: 24
>   connectionPoolSize: 64
>   database: 0
>   dnsMonitoringInterval: -1
> threads: 32
> nettyThreads: 64
> referenceEnabled: true
> transportMode: "NIO"
> lockWatchdogTimeout: 30000
> keepPubSubOrder: true
> decodeInExecutor: false
> useScriptCache: false
> minCleanUpDelay: 5
> maxCleanUpDelay: 1800
> cleanUpKeysAmount: 100
> addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}
> 

First, memory usage increase time by time even we made no access to application.
Is it normal behavior?

![スクリーンショット 2020-09-28 9 39 33](https://user-images.githubusercontent.com/71996614/94384260-16345400-017d-11eb-8ed0-25d114a3880f.png)

![スクリーンショット 2020-09-28 9 55 05](https://user-images.githubusercontent.com/71996614/94384308-3c59f400-017d-11eb-8179-445568d1e231.png)

After performing the load test, memory of RedissonSessionManager is not released.

![スクリーンショット 2020-09-28 10 29 15](https://user-images.githubusercontent.com/71996614/94384615-f6e9f680-017d-11eb-93b6-ed8dfd30b5af.png)

![スクリーンショット 2020-09-28 10 29 00](https://user-images.githubusercontent.com/71996614/94384779-5b0cba80-017e-11eb-8995-1a094a3d5185.png)

Please help!

**Comment by mrniko** [comment]
duplicate with https://github.com/redisson/redisson/issues/1975
