### ISSUE TITLE
duplicated with https://github.com/redisson/redisson/issues/2488

### ISSUE THREAD

**Issue by ms20hj** [redisson/redisson#3089]
duplicated with https://github.com/redisson/redisson/issues/2488

_Originally posted by @mrniko in https://github.com/redisson/redisson/issues/3075#issuecomment-697136904_

**Comment by ms20hj** [comment]
If I downgrade to redisson-spring-data-21, is it support redis sentinel or cluster?

**Comment by mrniko** [comment]
yes
