### ISSUE TITLE
How can I change the command name in RedisCommands.java?

### ISSUE THREAD

**Issue by iwtxokhtd83** [redisson/redisson#3090]
Let's say, if I renamed the sentinel command in sentinel.conf, then the redisson client can't find the sentinel command, can we make the command name configurable? Thanks

**Comment by srividrs** [comment]
Is there an update for this? Even i need a way to refer to renamed commands in Redisson.

**Comment by iwtxokhtd83** [comment]
no, no any update

**Comment by mrniko** [comment]
Hi, this feature isn't supported yet.

**Comment by elrapha** [comment]
Any updates on this?

**Comment by artemik** [comment]
Given that some servers don't allow/rename EVAL, that's kind of important feature, as it may be a blocker for using Redisson.

**Comment by mrniko** [comment]
implemented in https://github.com/redisson/redisson/issues/3998
