### ISSUE TITLE
Can't read after write when data is large

### ISSUE THREAD

**Issue by zjh-coder** [redisson/redisson#3091]
**Expected behavior**
read success after writing into Redis when data is large
**Actual behavior**
can't read data after writing into Redis using redisson when data is large
**Steps to reproduce or test case**
We have a social service in our app, and we store the follower list in the Redis.
When I follow a user, I will delete the follower list of this user on Redis, next time when I load the follower list, I will load data from MySQL first, then call RScoredSortedSet.addAll() to add data to Redis, then call the RScoredSortedSet.valueRangeReversed() to get the data with start and limit.

If a user has a little follower list lower than 1000, it will succeed. But when more than 3000, it will return null first time, and will
return the correct list the second time.

It seems like a consistency issue, but we use the cluster, which will only read data from the master node.
**Redis version**
5.0.7
**Redisson version**
3.13.4
**Redisson configuration**
Spring boot configuration:
```java
@Configuration
public class RedissonClientConfig {

    @Value("${spring.redis.timeout}")
    private String timeoutValue;

    @Value("${spring.redis.cluster.nodes}")
    private String nodes;

    @Bean(destroyMethod = "shutdown")
    @ConditionalOnMissingBean(RedissonClient.class)
    RedissonClient redisson() {
        int timeout = 20000;
        if (StringUtils.isNotBlank(timeoutValue)) {
            timeout = Integer.valueOf(this.timeoutValue.trim().replace("ms", ""));
        }

        List<String> address = new ArrayList<>();
        if (StringUtils.isNotBlank(nodes)) {
            address = Arrays.stream(nodes.split(",")).map(node -> "redis://".concat(node.trim()))
                            .collect(Collectors.toList());
        }

        Config config = new Config();
        config.setCodec(JsonJacksonCodec.INSTANCE);

        if (address.isEmpty()) {
            config.useSingleServer()
                  .setTimeout(1000000)
                  .setAddress("redis://127.0.0.1:6379");
            return Redisson.create(config);
        }

        config.useClusterServers()
              .setTimeout(timeout)
              .addNodeAddress(address.toArray(new String[]{}))
              .setSubscriptionsPerConnection(50)
              .setSubscriptionConnectionPoolSize(100);
        return Redisson.create(config);
    }
}
```

**Comment by zjh-coder** [comment]
Following are the demo code of the read process
```java
public List<Long> queryUserFollowers(Long userId, int start, int limit) {// Whom followed me
        RScoredSortedSet<Long> rFollowers = getRFollowers(userId);
        return new ArrayList<>(rFollowers.valueRangeReversed(start, start + limit - 1));
    }

public RScoredSortedSet<Long> getRFollowers(long followeeId) {
        RScoredSortedSet<Long> rFollowers = redissonClient.getScoredSortedSet(
                                                RedisConstant.PREFIX_SOCIAL_FOLLOWERS_USER + followeeId);
        if (!rFollowers.isExists()) {
            Map<Long, Double> followerMap = userFollowDao.queryFollowers(followeeId);
            rFollowers.addAll(followerMap);
            rFollowers.expire(RedisConstant.EXPIRE_DAYS_FOLLOWERS_USER, TimeUnit.DAYS);
        }
        return rFollowers;
    }
```

**Comment by mrniko** [comment]
> But when more than 3000, it will return null first time, and will return the correct list the second time.

This happens due to master slave replication lag. Try to use readMode = MASTER.

**Comment by zjh-coder** [comment]
@mrniko  so it's the Redisson that decides to read data from which node rather than the cluster itself?

**Comment by mrniko** [comment]
cluster just provides data and you read it using client - from slave or master or both.

**Comment by zjh-coder** [comment]
@mrniko Thank you for your reponse
