### ISSUE TITLE
RedissonClient#getMap(String) throws java.io.IOException: Unsupported protocol version 109

### ISSUE THREAD

**Issue by 4fath** [redisson/redisson#3093]
hello ,

I am trying to retrieve some data from Redis Instance (which **I use it as Hibernate 2LC**), when I try to get some map data it throws **java.io.IOException**, and message is **Unsupported protocol version 109**.

here is my code snippet:

	@Inject
	RedissonClient redissonClient;

	@Test
	public void getMap() {

		String mapKey = "{query.MyClass.myQuery}:redisson_options";
		RMap<Object, Object> map = redissonClient.getMap(mapKey);
		assert !map.isEmpty();

		try {
			map.forEach((key, value) -> {
				System.out.println(key);
				System.out.println(value);
			});

		}catch (Throwable t) {
			System.out.println(
					t.getCause().getMessage()
			);
		}

	}

which mistakes am I doing while retrieving the data from map?
(datas are put to Redis by Hibernate)

**Comment by mrniko** [comment]
I wouldn't recommend to modify hibernate local cache data stored in Redis.

**Comment by 4fath** [comment]
hi @mrniko ,
I just wanted to change max-size option on the file. it worked with the following. the issue is, I needed to give Codec when retrieving data.

        String redisKey = String.format("{%s}:redisson_option", entityOrRegion);

        RMap<Object, Object> map = client.getMap(redisKey, ByteArrayCodec.INSTANCE);

        ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES);
        buffer.putLong(value);

        map.put("max-size".getBytes(), buffer.array());


isn't it strange? Codec was MarshalingCodec when Hibernate doing things, but if I need to get data, I needed to use different codec.
