### ISSUE TITLE
broken connection not detected

### ISSUE THREAD

**Issue by fan0916** [redisson/redisson#3095]
**Expected behavior**

**Actual behavior**
we see some redis tcp connection status is ESTABLISHED, but the file descriptor is missing, the reason is unknown, but if redisson use these connections, netty writeFuture always timeout and we get org.redisson.client.RedisTimeoutException

**Steps to reproduce or test case**
don't know, we experience this twice in last month

**Redis version**
4.0

**Redisson version**
3.13.3
**Redisson configuration**
redisson-spring-boot-starter default

hope redisson can provide testOnBorrow or some method to solve this, thanks

**Comment by mrniko** [comment]
set `pingConnectionInterval` setting

**Comment by fan0916** [comment]
thanks mrniko! this helps a lot
