### ISSUE TITLE
It seems to broadcasting session creation between several tomcat with netty 4.1.52 even if broadcastSessionEvents="false".

### ISSUE THREAD

**Issue by okskakitani** [redisson/redisson#3098]
I have memory leak issue as I posted #3087.
So, I update netty version 4.1.52 according to #1975

This won't happen if I use redisson-all-3.13.5.jar from url below
https://github.com/redisson/redisson/tree/master/redisson-tomcat

> Oct 1   23:29:06 79b9844dd5-hnzbf-webdebug2020/10/01 23:29:06-237   1362693341 [debug] session management :[0]CREATE   :155DB222DF718BD239DC4594374CCA88.79b9844dd5-hnzbf
> Oct 1   23:29:07-79b9844dd5-z82m72020/10/01 23:29:07-715   0039844602 [info ] [null][null]:session management :[0]CREATE   :155DB222DF718BD239DC4594374CCA88.79b9844dd5-hnzbf
> Oct 1   23:29:07-79b9844dd5-hgx9f2020/10/01 23:29:07-739   0610351140 [info ] [null][null]:session management :[0]CREATE   :155DB222DF718BD239DC4594374CCA88.79b9844dd5-hnzbf
> Oct 1   23:29:08-79b9844dd5-hx4w42020/10/01 23:29:08-172   1500661456 [info ] [null][null]:session management :[0]CREATE   :155DB222DF718BD239DC4594374CCA88.79b9844dd5-hnzbf
> Oct 1   23:29:08-79b9844dd5-wgrv82020/10/01 23:29:08-177   1287574294 [info ] [null][null]:session management :[0]CREATE   :155DB222DF718BD239DC4594374CCA88.79b9844dd5-hnzbf
> 

Here is my pom.xml making my own redisson-all-3.13.5 to update netty
(Is this right way to do?)
> 		<dependency>
> 			<groupId>org.redisson</groupId>
> 			<artifactId>redisson</artifactId>
> 			<version>3.13.5</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-common</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-codec</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-buffer</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-transport</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-resolver</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-resolver-dns</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-codec-dns</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>io.netty</groupId>
> 			<artifactId>netty-handler</artifactId>
> 			<version>4.1.52.Final</version>
> 		</dependency>

**Comment by mrniko** [comment]
you can use netty version packaged with redisson-all-3.13.5.jar

**Comment by okskakitani** [comment]
Thanks for quick reply.
my first concern is memory leak suspect issue as I posted as #3087.
Do you mean redisson-all-3.13.5.jar contain the netty version as directed at #1975 ?

**Comment by mrniko** [comment]
yes

**Comment by okskakitani** [comment]
I understand.
Thank you!
