### ISSUE TITLE
RRateLimiter.delete() returns false despite apparently removing the appropriate key

### ISSUE THREAD

**Issue by achadha** [redisson/redisson#3099]
**Expected behavior**
Calling `delete()` on the Rate Limiter instance returns true when the object is removed from the data store.
**Actual behavior**
Sometimes returns true, but is returning false after I have called `tryAcquire()`. Note that the keys are still removed from the store.
**Steps to reproduce or test case**
```
  @Test
  public void testRemove() {
        RRateLimiter rateLimiter = redissonClient.getRateLimiter(TEST_KEY);
        rateLimiter.trySetRate(RateType.OVERALL, 5L, 5L, RateIntervalUnit.MINUTES);
        assertThat(redissonClient.getKeys().count(), is(1L));
        rateLimiter.tryAcquire();

        boolean deleted = rateLimiter.delete();
        assertThat(redissonClient.getKeys().count(), is(0L));
        assertThat(deleted, is(true)); // fails
    }
```
**Redis version**
3.2.12
**Redisson version**
3.13.4
**Redisson configuration**
```
config.useSingleServer().setAddress("redis://HOST:PORT"));
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
