### ISSUE TITLE
I am using redis queues extensively. Every now and then I see a warning from CommandDecoder. 

### ISSUE THREAD

**Issue by amankush510** [redisson/redisson#3100]
The following warning:

response has been skipped due to timeout! channel: [id: 0x7e2cab22, L:/xxx.xxx.xxx.xxx:xxxxx - R:xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:6379], command: (PING), params: []

Can it have any impact on my normal redis functions?

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by amankush510** [comment]
We are using 3.12.4.

**Comment by xchao1995** [comment]
I use is redisson - 2.8.2 version, also appears mandDecoder (org.redisson.client.handler.Com), the response has had skipped due to a timeout!Channel: May I ask how to solve this problem?

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/3107
