### ISSUE TITLE
LocalCacheMap key add or remove notification

### ISSUE THREAD

**Issue by mcacker** [redisson/redisson#3103]
Hi, I would like to use a LocalCacheMap to cache collections of objects, and reduce the number of requests to redis.  Our use case is one where keys are added or removed infrequently, but we iterate over the entire collection very frequently.  

If I understand it correctly, the LocalCacheMap does not add new keys to the local cache when they are added to redis by another application using a LocalCacheMap instance, which means that when we iterate over the collection it requires a SCAN redis command, which is a round trip redis operation.  

Is there a way to update the local cache when object are added to the redis cache?  If there were, it seems like it would eliminate the need for the redis SCAN command when iterating.

Alternatively, is there a way to add an EntryCreatedListener, similar to other collection types?  Or piggy back on the LocalCacheMap's own listener to achieve the same?  If I could do that I would then know all the keys to iterate over the collection.

thanks, Mitchell

**Comment by mrniko** [comment]
You can set `LocalCachedMapOptions.syncStrategy(SyncStrategy.UPDATE);` so local cache state will be synced across all LocalCacheMap instances. Use `RLocalCachedMap.cachedEntrySet()` or `RLocalCachedMap.cachedKeySet()` to traverse cache state.

**Comment by mcacker** [comment]
Great, thank you, that appears to work.

I would say that the documentation is not clear in this regards as it says 

    "UPDATE - Update cache entry across all LocalCachedMap instances on map entry change"

which to me doesn't imply added entries.  I note that the code comment has amended that with 

    "Broadcasts full map entry state (Key and Value objects) to all instances."  

It might be a good idea to update the Wiki accordingly.

Also, as i'm iterating over the entire collection, filtering according to certain rules, I can make significant optimizations if I know when the keys change.  Is it possible to get notification when that occurs?

**Comment by mrniko** [comment]
Done. Use `nameMapper` setting

**Comment by mrniko** [comment]
resolved in https://github.com/redisson/redisson/issues/4686
