### ISSUE TITLE
Failed to switch to the Redis instance during ip address change in DNS

### ISSUE THREAD

**Issue by yinliangan** [redisson/redisson#3104]
**Connect to the Redis instance when it is ready after an ip change in DNS**

**Failed to connect to the new Redis instance forever even if the new Redis is up and running**

** 1) Start Redis server at two hosts, one hosts (hostname: a.org) with ip 192.168.1.8 and the other 192.168.1.9.  2) Config your DNS mapping a.org->192.168.1.8 3) Start Redisson client and connect to a.org 4) stop Redis on 192.168.1.9 and then change DNS to: 192.168.1.9 -- you will see connection failure soon 5) start Redis on 192.168.1.9, and still connection to Redis won't be re-established.  In other words,  if the new Redis server is not ready at the moment of DNS ip change, Redis Client won't be able to setup the connection even if the new Redis server is up and running later **

**All**

**All**

**All**

The problem is in the two classes:
redisson/src/main/java/org/redisson/connection/DNSMonitor.java
redisson/src/main/java/org/redisson/connection/MasterSlaveEntry.java.

In function 'monitorMasters' in DNSMonitor.java, there are two lines:

      masterSlaveEntry.changeMaster(newMasterAddr, entry.getKey());
      masters.put(entry.getKey(), newMasterAddr);

The changeMaster(...) is asynchronized call without return value. So regardless successful or not, the master list is changed to the new Redis. 

The fix can be to add a return value to changeMaster(...), and only when the connection to the new Redis is setup successfully then change the masters list. Otherwise, retry to connect to the new Redis until it is available.

**Comment by mrniko** [comment]
Fixed! Thanks for suggestion
