### ISSUE TITLE
The RSet in RSetMultimap doesn't prevent logically equal objects from being stored in it

### ISSUE THREAD

**Issue by peterlitvak** [redisson/redisson#3105]
I'm not sure if this is by design or a bug so posing this as a question.
For the following code:
```
public class TestEntry {
        private String id;
        private String value;

        public TestEntry(String id, String value) {
            this.id = id;
            this.value = value;
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof TestEntry && id.equals(((TestEntry) obj).id);
        }

        @Override
        public int hashCode() {
            return id.hashCode();
        }

        private TestEntry() {
            // needed by JsonJackson
        }
    }
...
    @Test
    public void test() {

        RSetMultimap<Long, TestEntry> setMultimap = redissonClient.getSetMultimap("key", JsonJacksonCodec.INSTANCE);

        setMultimap.put(1L, new TestEntry("1", "v1"));
        setMultimap.put(1L, new TestEntry("1", "v2"));

        assertThat(setMultimap.get(1L)).hasSize(1);
    }
```
the test will fail.
Of course if you read the set by calling `getAll()` it will have only one entry but the duplicates will be stored in the REDIS memory.
Is there a way to enforce uniqueness on put?

Thank you

**Comment by mrniko** [comment]
`equals` and `hashCode` methods aren't invoked and object state used instead for comparision.

**Comment by peterlitvak** [comment]
could you please elaborate on what exactly the "object state" here means?

**Comment by mrniko** [comment]
object state in serialized form produced with JsonJacksonCodec in your example

**Comment by mrniko** [comment]
I agree that `getAll` method should return two objects in this case.

**Comment by peterlitvak** [comment]
wait, why would getAll return 2 objects, it breaks the contract of the set completely

**Comment by peterlitvak** [comment]
I was hoping there is actually a way to achieve the expected behavior on put

**Comment by peterlitvak** [comment]
just to clarify, when you say object state, do you mean that the bytes of two objects are the same? is this the only comparison that happens on put?

**Comment by mrniko** [comment]
> do you mean that the bytes of two objects are the same? is this the only comparison that happens on put?

Yes.
