### ISSUE TITLE
response has been skipped due to timeout! for PING command

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#3107]
Redisson version: 3.12.4

We are seeing warning log in our production logs 

```
response has been skipped due to timeout! channel: [id: 0x56f28812, L:/<IP>:49586 - R:<IP>/<IP>:6379], command: (PING), params: []
```

We have enabled `keepAlive` and set `pingConnectionInterval` to 5 seconds to keep the connection alive which was suggestion given for another question last year. Looks like this background PING command has 1 second timeout instead of using `timeout` configuration, can you confirm? 

Looks like these timeouts happen on connections running BLPOP command, in that case can you skip doing PING on blocked connections? 

We also gave netty threads equal to max number of connections in the pool, this value varies by service 64, 128, and 256.

**Comment by mrniko** [comment]
> Looks like this background PING command has 1 second timeout instead of using timeout configuration, can you confirm?

Why do you think so? Can you share Redisson configuration

**Comment by mrniko** [comment]
> Looks like these timeouts happen on connections running BLPOP command, in that case can you skip doing PING on blocked connections?

Here is the check https://github.com/redisson/redisson/blob/f73eea3636cdcd9224e8e1c94d0251d02e720bb8/redisson/src/main/java/org/redisson/client/handler/PingConnectionHandler.java#L66

**Comment by mrniko** [comment]
Unable to reproduce using following test:

```java
        RedisProcess runner = new RedisRunner()
                .nosave()
                .randomDir()
                .randomPort()
                .run();

        Config config = new Config();
        config.useSingleServer()
                .setPingConnectionInterval(2000)
                .setAddress(runner.getRedisServerAddressAndPort());

        RedissonClient redisson = Redisson.create(config);
        RBlockingQueue<Integer> queue1 = getQueue(redisson);

        for (int i = 0; i < 10; i++) {
            queue1.poll(1, TimeUnit.SECONDS);
        }

        runner.stop();
        redisson.shutdown();
```

**Comment by rgampa** [comment]
@mrniko If it's not due to blocking command what else could be reason for this warning? The reason I came to the conclusion is we have two redis clusters, this only happens in in one cluster where we use only PUSH and BLPOP commands, these commands only happen on master node, that's how I could isolate the issue to blocking command.

**Comment by mrniko** [comment]
Fixed

**Comment by rgampa** [comment]
Thanks @mrniko for fixing this. From the commit I couldn't figure out the root case, is PING command is still being executed though it supposed to be skipped and just removed WARN log, can you please explain?
Will this be part of next release version `3.13.6`?

**Comment by mrniko** [comment]
I just removed this warning since it doesn't affect anything

**Comment by rgampa** [comment]
@mrniko Ok got it, any reason why timeouts are happening on PING which supposed to be very lightweight. We don't see timeouts on any other commands in production. Do you think the check `commandData.isBlockingCommand()` isn't working as expected or some race condition causing PING command leak on blocking connection?
