### ISSUE TITLE
Redisson upgrade 3.9.1 -> 3.13.4 increased number of Redis processed commands

### ISSUE THREAD

**Issue by XMitya** [redisson/redisson#3112]
Hi,

After upgrade Redisson client from 3.9.1 to 3.13.4 we noticed significantly increased number of processed commands in Redis. This seems doesn't impact Redis cluster CPU load, but looks strange, especially because of big imbalance in Redis nodes:
![Screenshot_20201008_094422](https://user-images.githubusercontent.com/2520475/95424432-4af99580-094b-11eb-8b0a-08c02287203a.png)

What could it be? Application wasn't changed, only Redisson.
Thanks!

**Comment by mrniko** [comment]
which objects and commands do you use?

**Comment by XMitya** [comment]
In most cases we use RBucket and collections. But also other structures. Here is the list:
RBucket, RMap, RSet, RAtomicLong, RSetCache, RPermitExpirableSemaphore, RLock, RSemaphore, RScoredSortedSet, RScript, RKeys

Harder to find all methods, but for bucket is get/set with expiration, then put/delete. add, tryAdd, expireAsync, contains, remove, readAll for collections.

**Comment by mrniko** [comment]
Can we consider it as performance improvement? :)

**Comment by XMitya** [comment]
Maybe improvement, but what change could cause such increase of queries? I'm worrying if it could be an issue under larger load.

**Comment by mrniko** [comment]
Did you check latency?

**Comment by XMitya** [comment]
Only latencies of application, and it haven't changed. If there would be any latency change in Redis queries, we could see it.

**Comment by mrniko** [comment]
you can execute "INFO COMMANDSTATS" to see stats per command
