### ISSUE TITLE
Redisson don't switch read operation properly when slave is down

### ISSUE THREAD

**Issue by neismit** [redisson/redisson#3115]
I configured master-slave configuration for standalone Redis. readMode = ReadMode.MASTER_SLAVE

val server = config.useMasterSlaveServers().apply {
    masterAddress = master.uri
    laves.forEach { addSlaveAddress(it.uri) }
    val weights = mutableMapOf<String, Int>()
    slaves.asSequence()
        .map { it.uri to getReadProbabilityOrDefault(it.readProbability) }
        .toMap(weights)
     weights[master.uri] = getReadProbabilityOrDefault(master.readProbability)
     loadBalancer = RoundRobinLoadBalancer()
     readMode = _ReadMode.MASTER_SLAVE_
}

When I do on slave `debug segfault` there aren't operations in a monitor on a master node. Only after timeout in 180000 ms all operations will start to perform on the master node. My code didn't receive any exception from Redisson.

I can reduce a delay by setting up `failedSlaveCheckInterval = 3000` parameter but why Redisson didn't switch to slave after the first failed command?   
And that more important _why Redisson didn't send any command to the master node_?

**Comment by mrniko** [comment]
> but why Redisson didn't switch to slave after the first failed command?

It waits for topology update. In useMasterSlaveServers mode topology is not updated.

**Comment by neismit** [comment]
> It waits for topology update. In useMasterSlaveServers mode topology is not updated.
How can I avoid pause?
Configure standalone Master-slave with another configuration?

**Comment by mrniko** [comment]
try to use cluster or sentinel mode

**Comment by neismit** [comment]
> try to use cluster or sentinel mode

we use standalone redis without sentinel. Just master node with several read slaves. It's not a cluster.
Redisson don't have any options for that configuration?

**Comment by mrniko** [comment]
In this case Redisson can't update topology without any info about it.
