### ISSUE TITLE
after upgrade redisson-spring-boot-starter to 3.13.5, can`t load config file anymore

### ISSUE THREAD

**Issue by raydl007** [redisson/redisson#3116]
**Expected behavior**
load config file from classpath
**Actual behavior**
applicaton goes error when bootstrap
**Steps to reproduce or test case**
upgrage to 3.13.5 and use spring.redis.reddison.file instead of spring.redis.reddison.config in the application.yml
**Redis version**
5.0.5
**Redisson version**
3.13.5
**Redisson configuration**
{
        "singleServerConfig": {
          "address": "redis://localhost:6379",
          "password": null,
          "pingConnectionInterval": 10,
          "database": 12
        },
        "codec": {
          "class": "org.redisson.codec.JsonJacksonCodec"
        },
        "transportMode": "NIO"
}

**Comment by raydl007** [comment]
![load file](https://user-images.githubusercontent.com/10443318/95643696-567fc480-0ae3-11eb-8431-3d05a6f919dd.png)
![still load conifg from spring.redis.redisson.config rather than spring.redis.config.file](https://user-images.githubusercontent.com/10443318/95643709-68f9fe00-0ae3-11eb-9b77-b3e3c892ad33.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
