### ISSUE TITLE
RMapCache.keySet inconsistent behaviour

### ISSUE THREAD

**Issue by mlemnaru** [redisson/redisson#3117]
Hello,

I am using redisson **3.12.5**

I have this map "REMOTE_SESSIONS" and I am trying to access it using getMapCache ( RMapCache )
After fetching the map I am querying it's keys , using keySet but I am seeing inconsistent behaviour and I am not sure why.

I might be using the library wrong but this is driving me crazy :) 

Here is my code

```
        List<RMapCache> cacheList = new ArrayList<>();
        int count = 10;
        // get 10 caches
        for (int i = 0; i < count; i++) {
            cacheList.add(redissonClient.getMapCache("REMOTE_SESSIONS", StringCodec.INSTANCE));
        }

        // for each one of them print the keyset
        for (int i = 0; i < count; i++) {
            Set set = cacheList.get(i).keySet(100);
            Iterator iterator = set.iterator();
            int actualCount = 0;
            while (iterator.hasNext()){
                iterator.next();
                actualCount++;
            }
            System.out.println("COUNT (from size) = " + set.size() + " - COUNT (actual) = " + actualCount);
        }
```
I am doing the following:

Get 10 instances of REMOTE_SESSIONS cache. For each of them print the count given by size and then the actual count , retrieved via iterator traversal.

And I get the following output:

```
COUNT (from size) = 23 - COUNT (actual) = 23
COUNT (from size) = 23 - COUNT (actual) = 4
COUNT (from size) = 23 - COUNT (actual) = 4
COUNT (from size) = 23 - COUNT (actual) = 4
COUNT (from size) = 23 - COUNT (actual) = 4
COUNT (from size) = 23 - COUNT (actual) = 4
COUNT (from size) = 23 - COUNT (actual) = 23
COUNT (from size) = 23 - COUNT (actual) = 23
COUNT (from size) = 23 - COUNT (actual) = 23
COUNT (from size) = 23 - COUNT (actual) = 23
```

For some reason the actual content of the keySet is varying. This might be related to the fact that under the scenes this is implemented using HSCAN but can't really tell why.

Any idea why this is happening and can I access the keys from a map.

My end goal would be to query the keys using a pattern but that doesn't work consistent either.

Any help is greatly appreciated.
Thanks

**Comment by mrniko** [comment]
Which Redis version do you use?

**Comment by mlemnaru** [comment]
We use **Redislabs** , and from the settings page I see this:

**Redis Version Compliance - 6.0.5**

So I am guessing that is the installed redis version.

We connect to redis using singleServerConfig. Like so:

        Config config = new Config();
        config.setNettyThreads(16);
        config.useSingleServer().setAddress(redisHost + ":" + redisPort)
            .setConnectionPoolSize(connectionPoolSize)
            .setPassword(password);

Btw: **I recently done some more tests locally using the same config , but locally I have redis 6.0.8 installed and there it does not reproduce.** 

Could it have anything to do with how redislabs is setting up their instances ? 

Thanks

**Comment by mrniko** [comment]
Seems hscan used in LUA-script works wrong in Redislabs's Redis implementation.
