### ISSUE TITLE
incremental number of connection over time

### ISSUE THREAD

**Issue by eng7miky** [redisson/redisson#3120]
we face a problem that number of connection to Redis cluster node is increasing until it consumed the max number of open connections (which was set to 4096)

Redisson version: 3.13.2

Config.s: 
```
redis.cluster=true
redis.address=ip1:6379,ip2:6379,ip3:6379
redis.bulk_size=10000
redis.timeout=3000
redis.connection.timeout=10000
redis.idle.connection.timeout=10000
redis.retry.attempts=3
redis.retry.interval=1500
redis.batch.retry.attempts=3
redis.batch.retry.interval=1500
redis.batch.response.timeout=3000
redis.lock.wait.time.milliseconds=1000
redis.lock.lease.time.milliseconds=1000
redis.netty.threads=32
## Redis Cluster Configs ##
redis.cluster.master.pool.size=64
redis.cluster.slave.pool.size=64
redis.cluster.master.minimum.idle.size=24
redis.cluster.slave.minimum.idle.size=24
redis.ping.connection.interval=2000
redis.keep.alive=true
redis.tcp.no.delay=true
```

After a period of running the client, we discovered that number of connections from client to a single redis node (slave one) using lsof is more than 100 connections in some cases it exceeded 200 connection despite the configs are set to 64 (see the attached [connections.log](https://github.com/redisson/redisson/files/5365993/connections.log) for open connections from client to redis node)

Is that a connection leak problem or a configuration issue ?

**Comment by mrniko** [comment]
3.13.3 version has fix for connection leak in Spring Data Redis integration module.

**Comment by sgomaa** [comment]
@mrniko but we are not using Spring Data , we are using RBatch

**Comment by mrniko** [comment]
is there code example to reproduce it?

**Comment by sgomaa** [comment]
@mrniko no reproduce scenario, it happens after leaving app running for days, we start to see the number of redis connection increases ,it happens mainly when master and slave nodes changes their role (slave takes over master and vice versa), in 3.12 the issue was that the application stuck when this happens , when you recommended to upgrade to 3.13 the hanging issue was fixed but now it leaks

**Comment by mrniko** [comment]
Could you share all examples of RBatch usage.

**Comment by sgomaa** [comment]
private void batchKeysWithCodec(List<String> keys, RBatch batch, Codec codec) {
    for (String key : keys) {
      batch.getBucket(key, codec).getAsync();
    }
  }

  private List<Object> getBatchResponses(List<String> keys, Codec codec) {
    List<Object> result = new ArrayList<>();
    try {
      RBatch batch = redissonClient.getBatch();
      if (codec == null) {
        batchKeysWithDefaultCodec(keys, batch);
      } else {
        batchKeysWithCodec(keys, batch, codec);
      }
      List<?> responses = batch.execute().getResponses();
      if (responses.size() != keys.size()) {
        throw new Exception("Batch returned less keys than requested");
      }
      result.addAll(responses);
    } catch (Exception e) {
      ApplicationLogger.logFatal("Exception in retrieving data from Redis", e, LastValueService.class);
    }
    return result;
  }

**Comment by sgomaa** [comment]
try {
            start = System.currentTimeMillis();
            recordState = getAndUpdateState(key, eventType, triggerAfter, stopAfter, expressionResult, lock);
            redisTimes.setRedisSavingTime(redisTimes.getRedisSavingTime() + System.currentTimeMillis() - start);
          } finally {
            start = System.currentTimeMillis();
            unlock(lock, key);
            redisTimes.setLockUnlockingTime(redisTimes.getLockUnlockingTime() + System.currentTimeMillis() - start);
          }


 private EventState getAndUpdateState(String key, EventType eventType, int triggerAfter, int stopAfter, boolean expressionResult, RLock lock) {
    boolean stateUpdated = false;
    RBucket<EventState> bucket = redissonClient.getInstance().getBucket(key, codec);
    EventState eventState = bucket.get();
    if (eventState == null) {
      eventState = new EventState(EventStateEnum.OFF);
    }
    if (eventType == EventType.NON_PAIRED) {
      stateUpdated = updateNonPairedEventState(expressionResult, eventState, triggerAfter, stopAfter);
    }
    if (stateUpdated) {
      if (lock.isHeldByCurrentThread()) {
        bucket.set(eventState);
      } else {
        ApplicationLogger.logError(
            "Lock key " + key + " released before saving, is locked: " + lock.isLocked() + ",Remaining time to live:" + lock.remainTimeToLive(),
            EventStateServiceImpl.class);
      }
    }
    return eventState;
  }



private RLock tryToAcquireLock(String key) throws InterruptedException, RedisException {
    RLock lock = redissonClient.getInstance().getLock(RedisPropertiesConstants.LOCK_PREFIX + key);
    boolean acquired = lock.tryLock(waitTime, leaseTime, TimeUnit.MILLISECONDS);
    return acquired ? lock : null;
  }

  private void unlock(RLock lock, String key) {
    if (lock.isHeldByCurrentThread()) {
      try {
        lock.unlock();
        ApplicationLogger.logInfo("released the lock " + key, EventStateServiceImpl.class);
      } catch (IllegalMonitorStateException e) {
        ApplicationLogger.logError(
            "Exception in unlock key " + key + " Lock is locked: " + lock.isLocked() + " Remaining time to live:" + lock.remainTimeToLive() + " " + e,
            EventStateServiceImpl.class);
      } catch (RedisException e) {
        ApplicationLogger.logFatal("Exception in redis connection while unlock ", e, EventStateServiceImpl.class);
      }
    } else {
      ApplicationLogger.logError(
          "unable to unlock key " + key + ",Lock is locked: " + lock.isLocked() + ",Remaining time to live:" + lock.remainTimeToLive(),
          EventStateServiceImpl.class);
    }
  }

**Comment by sgomaa** [comment]
@mrniko we are using Rbatch and locks in the module ,as you can see above

**Comment by mrniko** [comment]
This might be caused by this issue https://github.com/redisson/redisson/issues/2947. Can you update to the latest version?

**Comment by sgomaa** [comment]
@mrniko ok will upgrade to latest version and let you know, thanks
