### ISSUE TITLE
Don't throw the exception of Bloom filter config has been changed in BloomFilter

### ISSUE THREAD

**Issue by Patrick0308** [redisson/redisson#3129]
https://github.com/redisson/redisson/blob/dcab532b84530f5c64db10826bf8bab03d957568/src/main/java/org/redisson/RedissonBloomFilter.java#L163-L165

If we modify bloomfilter's config in redis, it will make `contains` function cycling constantly.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5130
