### ISSUE TITLE
Getting Error while connecting to sentinel using password.

### ISSUE THREAD

**Issue by ManeeshSharma17** [redisson/redisson#3135]
Getting below error while connecting to sentinel using a password. I have kept the password the same for both Redis and sentinel still getting the issue.
`Can't connect to sentinel server. Unable to connect to: redis://x.x.x.x:26379`
**Expected behavior**
Should be able to connect to sentinel using the same password.
**Actual behavior**
Getting error - `Can't connect to sentinel server. Unable to connect to: redis://x.x.x.x:26379`
**Steps to reproduce or test case**

**Redis version**
Redis: 5.0.8
**Redisson version**
Redisson: 3.13.6
**Redisson configuration**
`{
  "sentinelServersConfig": {
    "idleConnectionTimeout": 10000,
    "connectTimeout": 5000,
    "timeout": 5000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "failedSlaveReconnectionInterval": 5000,
    "failedSlaveCheckInterval": 10000,
    "password": "password",
    "subscriptionsPerConnection": 5,
    "clientName": null,
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "slaveConnectionMinimumIdleSize": 10,
    "slaveConnectionPoolSize": 64,
    "masterConnectionMinimumIdleSize": 10,
    "masterConnectionPoolSize": 64,
    "readMode": "MASTER",
    "subscriptionMode": "MASTER",
    "sentinelAddresses": [
      "redis://X.X.X.X:26379"
    ],
    "checkSentinelsList": false,
    "masterName": "redismaster",
    "database": 1
  },
  "threads": 16,
  "nettyThreads": 32,
  "transportMode": "NIO"
}`

**Comment by ManeeshSharma17** [comment]
Have created a PR to fix this, request you to please review it - [#3134 ](https://github.com/redisson/redisson/pull/3134)

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by winterhalder** [comment]
Any ETA on when 3.13.7 will be released with this fix?

**Comment by mrniko** [comment]
this issue was fixed in 3.14.0 version
