### ISSUE TITLE
Rx API is missing support for cache variants of multimaps

### ISSUE THREAD

**Issue by mlkammer** [redisson/redisson#3139]
**Context description:**
The regular (non-async, non-reactive, non-Rx) API contains cache variants for multimap based collections:

- `RListMultimapCache` for `RListMultimap`, available by calling `RedissonClient.getListMultimapCache()`;
- and `RSetMultimapCache` for `RSetMultimap`, available by calling `RedissonClient.getSetMultimapCache()`

But the Rx-ified version of the API does not have the cache variants:
- `RedissonRxClient` only has `getListMultimap()` and not `getListMultimapCache()`, because `RListMultimapCacheRx` does not exist yet;
- and `RedissonRxClient` only has `getSetMultimap()` and not `getSetMultimapCache()`, because `RSetMultimapCacheRx` does not exist yet

**Our problem:**
The problem we are facing is that we have a code base that heavily relies on Rx interfaces and that we need the expiration/eviction functionality that Redisson offers for set multimaps, but this combination seems to be missing from the API.

**Desired solution**
Additions to the Rx-ified API to be able to instantiate multimap caches, so that we can specify expiration for items in the multimap cache using Rx method calls.

**Alternatives we've considered**
We've considered using the non-Rx-ified APIs, but we'd end up writing our own Rx proxy layer around it since our code base so heavily relies on RxJava. Therefore it seems more logical to add it to Redisson instead, even more so because it looks as though this feature would fill a rather obvious gap in the API (for which there was understandably no time yet, undoubtedly).

**Comment by mrniko** [comment]
merged
