### ISSUE TITLE
Is it able to encapsulate 'isExistsAsync' and 'fastPutAsync' into one Batch

### ISSUE THREAD

**Issue by Honglaisenburg** [redisson/redisson#3142]

**Comment by Honglaisenburg** [comment]
Hi mate,
I am not sure if we could encapsulate 'isExistsAsync' and 'fastPutAsync' into one Batch. Say I need to put some key-value only if some key or hash exists, how could I do so by use of Batch ?
Thanks.

**Comment by mrniko** [comment]
there is no such method in API. But I think it could be added. Like "putIfExists"

**Comment by Honglaisenburg** [comment]
Thanks mate 💯

**Comment by mrniko** [comment]
Done
