### ISSUE TITLE
自动配置问题

### ISSUE THREAD

**Issue by lion000** [redisson/redisson#3143]
使用最新版的redisson，看了一下autoconfig。。。一言难尽啊
比如我在使用druid连接池的时候，为了防止忘记设置某一个值，可以使用EnvironmentPostProcessor来初始化一份配置文件，然后由项目组来根据实际场景修改某一个值。
但是这里的配置是通过yaml文件字符串进行读取，和使用环境变量做替换，这。。。感觉有点别扭了
有计划在哪个版本来升级一下autoconfig吗？

**Comment by mrniko** [comment]
I'm afraid environment variables can't be skipped

**Comment by ShawshankLin** [comment]
> I'm afraid environment variables can't be skipped

现在springboot配置也是，只能放一些通用配置再springboot配置上，如果要定制就要放在redssion配置文件上，但是其实我是想一些基础的配置放在springboot配置，比如host，password这些，因为这些可以通过我的配置中心去存放，但是现在只能配置再redssion配置文件上，而且两种只能选择一种方式，可以考虑两者结合吗？

**Comment by lion000** [comment]
@mrniko 不是说要被忽略，而是说就拿threads这个配置来说，脚手架提供一个默认配置，可能不是8，这个配置是根据不同环境，提供的一个相对合理的值，然后，业务开发的时候，如果发现瓶颈在这个值的时候，可以通过覆盖的方式来指定这个值，这样既满足业务开发的通用性，又满足了一些特殊业务的需要

**Comment by yiyuan0109** [comment]
> > I'm afraid environment variables can't be skipped
> 
> 现在springboot配置也是，只能放一些通用配置再springboot配置上，如果要定制就要放在redssion配置文件上，但是其实我是想一些基础的配置放在springboot配置，比如host，password这些，因为这些可以通过我的配置中心去存放，但是现在只能配置再redssion配置文件上，而且两种只能选择一种方式，可以考虑两者结合吗？@mrniko

老哥有解决办法吗？ 我现在是用redisson配置方式, 在文档 https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#2-add-settings-into-applicationsettings-file 描述说可以用spring boot方式或redisson配置，两者能兼容吗？

**Comment by mrniko** [comment]
Configuration description defined in file by `spring.redis.redisson.file` setting is compatible with "spring.redis.redisson.config"
