### ISSUE TITLE
redisson用阿里云集群版redis的问题

### ISSUE THREAD

**Issue by bean326** [redisson/redisson#3144]
阿里云集群版redis限制了使用EVAL命令，以前也测试过确实会报错，但我现在不知道怎么重现那个错误了，想确认下是不是现在redisson底层处理了什么，让它能用阿里云的集群版redis了

**Comment by mrniko** [comment]
Eval command is necessary for the most Redisson objects.

**Comment by bean326** [comment]
我申请了一个阿里云的集群版redis来测试，但无论存还是取对象都没有报错，一切正常，有点搞不懂了。。。
