### ISSUE TITLE
TimeSeries.iterator() doesn't respect the ordering

### ISSUE THREAD

**Issue by vers85** [redisson/redisson#3145]
**Expected behavior**

Since timeseries is a sorted collection I'd expect iterator() to respect the ordering. There's a range method which in fact returns the values in order, however it returns Mono<Collection<T>> instead of Flux<T> which means entire set is loaded into the memory, while I'd like to read it reactively in chunks.

**Actual behavior**

redisson.getTimeSeries("").iterator().next().block() != redisson.first.block()

**Steps to reproduce or test case**

1. add multiple elements into the timeseries collection
2. open a redis desktop manager or use the cli to check the elements are indeed ordered by score
3. call iterator() method and check the ordering 

I've checked also the non-reactive version and seems to work in the same way.

**Redis version**
5.0.8

**Redisson version**
3.13.4

**Redisson configuration**
singleServerConfig:
	address: "redis://127.0.0.1:6379"
	database: 2

**Comment by mrniko** [comment]
Unable to reproduce the issue using this code:

```
        RTimeSeries<String> t = redisson.getTimeSeries("test");
        t.add(4, "40");
        t.add(2, "20");
        t.add(1, "10");

        t.iterator().next().equals(reactiveClient.getTimeSeries("test").first().block());
```

**Comment by mrniko** [comment]
Could you provide sample code to reproduce this issue?

**Comment by vers85** [comment]
Sure. I'll do it on Monday

> 
> 
> Could you provide sample code to reproduce this issue?

**Comment by vers85** [comment]
Sorry for being late and a lot of noise in the code, but it was not so easy to reproduce. It might be something with those nested data classes, as without them I was unable to demonstrate the issue. Also I ran this on redis 3.0.6 and the result is the same as with redis 5.0.8

`
    @Test
    internal fun redissonTimeserieTest() {
        data class Component(val app: String, val flow: String)
        data class Step(val component: Component, val id: String)
        data class Link(val from: Step, val to: Step)

        fun makeLink(from: String, to: String) = Link(Step(Component("123456", "test"), from), Step(Component("123456", "test"), to))

        val timeserie = Redisson.createReactive().getTimeSeries<Link>(UUID.randomUUID().toString(), TypedJsonJacksonCodec(Link::class.java, jacksonObjectMapper()))

        with(timeserie) {
            add(1, makeLink("a", "b")).block()
            add(2, makeLink("b", "c")).block()
            add(3, makeLink("c", "d")).block()
            add(4, makeLink("d", "e")).block()
            add(5, makeLink("e", "f")).block()
        }

        assertEquals(timeserie.first().block(), timeserie.iterator().blockFirst())
    }
`

The result of the above is:

`expected: <Link(from=Step(component=Component(app=123456, flow=test), id=a), to=Step(component=Component(app=123456, flow=test), id=b))> but was: <Link(from=Step(component=Component(app=123456, flow=test), id=d), to=Step(component=Component(app=123456, flow=test), id=e))>`

**Comment by mrniko** [comment]
Fixed! Thanks for the provided test case
