### ISSUE TITLE
Add ListCache

### ISSUE THREAD

**Issue by vers85** [redisson/redisson#3146]
**Is your feature request related to a problem? Please describe.**

I'd like to have a possibility to set eviction for a given element while inserting into the collection that keeps the insertion order.

**Describe the solution you'd like**

Similar to the MapCache and SetCache I think there's a need for a ListCache as neither of the previous ones keep the ordering.

**Describe alternatives you've considered**
SetCache but it lacks ordering.
TimeSeries but as per [issue 3145](https://github.com/redisson/redisson/issues/3145#issue-726375289) the iterator() method does not return the values according to the score.

**Comment by mrniko** [comment]
I'm closing this one, since issue with TimeSeries iterator is now resolved.
