### ISSUE TITLE
利用Redisson按天做限流，历史生成的限流key不会自动清除

### ISSUE THREAD

**Issue by colddew** [redisson/redisson#3149]
利用Redisson按天做限流，历史生成的限流key不会自动清除，这个如何处理，可以设置缓存过期时间吗？

```java
// rate limit 100 times per day
String date = DateFormatUtils.format(new Date(), BaseConstants.DATE_FORMAT_LEAN);
RRateLimiter timesPerDayRateLimiter = redissonClient.getRateLimiter(String.format(RedisConstants.TOKEN_REFRESH_TIMES_PER_DAY_RATE_LIMIT, date, userId));
timesPerDayRateLimiter.trySetRate(RateType.OVERALL, tokenProperties.getTokenRefreshTimesPerDayRateLimit(), 1, RateIntervalUnit.DAYS);
```

![image](https://user-images.githubusercontent.com/6032545/96854696-5f32ac00-148e-11eb-96b2-4d9c363f122f.png)

该历史缓存会清除
{token:refresh:20201021:68155c4000eb4d79a3f9516bfc51f9c5}:value

该历史缓存未清除
token:refresh:20201021:68155c4000eb4d79a3f9516bfc51f9c5

**Comment by mrniko** [comment]
any code to reproduce it?

**Comment by colddew** [comment]
并没有，类似token:refresh:20201021:68155c4000eb4d79a3f9516bfc51f9c5，昨日生成的key第二天就不会再去使用了，redisson的限流机制难道默认限流key都不清除的？

**Comment by colddew** [comment]
找到解决方案了，限流器的超时时间需要手动设置，默认没有设。设置过程发现一个bug，直接设置1天无效，只能设置24小时才会生效

```java
// 无效
timesPerDayRateLimiter.expire(1, TimeUnit.DAYS);
// 有效
timesPerDayRateLimiter.expire(24, TimeUnit.HOURS);
```

**Comment by jsbzg** [comment]
好的，谢谢

**Comment by mrniko** [comment]
@colddew

Which Redisson version do you use?
