### ISSUE TITLE
UnrecognizedPropertyException: Unrecognized field "sentinelAddresses"

### ISSUE THREAD

**Issue by MumfordSons** [redisson/redisson#3151]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version** 6.0.5

**Redisson version** 3.13.1

**Redisson configuration**
singleServerConfig:
  password: 
  # 连接空闲超时，单位：毫秒
  idleConnectionTimeout: 10000
  # 连接超时，单位：毫秒
  connectTimeout: 10000
  # 命令等待超时，单位：毫秒
  timeout: 3000
  # 命令失败重试次数,如果尝试达到 retryAttempts（命令失败重试次数） 仍然不能将命令发送至某个指定的节点时，将抛出错误。
  # 如果尝试在此限制之内发送成功，则开始启用 timeout（命令等待超时） 计时。
  retryAttempts: 3
  # 命令重试发送时间间隔，单位：毫秒
  retryInterval: 1500
  # 单个连接最大订阅数量
  subscriptionsPerConnection: 5
  # 客户端名称
  clientName: null
  # 发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  # 发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  # 最小空闲连接数
  connectionMinimumIdleSize: 32
  # 连接池大小
  connectionPoolSize: 64
  sentinelAddresses:
  - "redis://192.168.101.153:26379"
  - "redis://192.168.101.153:26380"
  - "redis://192.168.101.128:26379"
  masterName: "mymaster",
  # 数据库编号
  database: 0
  # DNS监测时间间隔，单位：毫秒
  dnsMonitoringInterval: 5000
# 线程池数量,默认值: 当前处理核数量 * 2

**Comment by mrniko** [comment]
unable to reproduce

**Comment by MumfordSons** [comment]
> unable to reproduce

i got the reason。 singleServerConfig ->sentinelServersConfig
