### ISSUE TITLE
CROSSSLOT error when clearing a redis-spring-data cache

### ISSUE THREAD

**Issue by josh-e** [redisson/redisson#3153]
**Expected behavior**
Calling RedissonConnection.del() with multiple keys when using a clustered connection should delete the keys without error
 - public Long del(byte[]... keys) 

**Actual behavior**
"CROSSSLOT" exception is thrown

**Steps to reproduce or test case**

Should be able to reproduce by simply trying to delete multiple keys that aren't in the same slot using a ReddisonConnection that is clustered.

In my example
  - Using redis-spring-data with redisson-spring-data
  - Using clustered connection
  - Using "@CacheEvict(allEntries = true)" annotation
  - This calls 
    - RedisCache.clear()
    -  DefaultRedisCacheWriter.clean()
    -  RedissonConnection.del(byte[][] keys)

**Redis version**

5.0.3 (AWS)

**Redisson version**

redis-spring-data
3.12.5+  ("redisson-spring-data23:3.13.6" is where I have tested)

**Redisson configuration**
Clustered

I ran into this when upgrading from Spring 2.2.x to 2.3.x (Redisson 3.12.0 to 3.13.6)

This appears to have been broken when the check for clustered connection was removed as part of this commit: https://github.com/redisson/redisson/commit/8be90089a36e9aab31121bb0771d25f82d8a65a7

**Comment by mrniko** [comment]
Fixed! Thanks for report
