### ISSUE TITLE
Concurrency issues with RQueue::removeIf / RQueue's iterator

### ISSUE THREAD

**Issue by philmtd** [redisson/redisson#3158]
**Expected behavior**
When having one producer and at least two consumer threads (or instances of an application) I expect RQueue's `removeIf(lambda)` method to remove elements without negative side effects.

I expect the same when using an iterator to iterate over the queue and calling `remove()` on the iterator.

**Actual behavior**
There are multiple types of errors that I observed:
- I've seen NullPointerExceptions inside the `removeIf` lambda (e.g. `q.removeIf(element -> element.getId().equals("id"))`), where `element` is null (we don't add null elements to the queue).
- Other times `removeIf` does not actually remove the elements from the queue, probably because it did not find the elements in the first place.

As the default implementation of `removeIf` uses the iterator my guess is that basically the iterator causes this issue and may not work properly when another consumer of a queue modifies the queue while it is used.

**Steps to reproduce or test case**

I have the following test case which can be used to reproduce the issue. It uses Lombok, Awaitility and Apache's RandomStringUtils for convenience (in case you want to run it without modification). Below I will explain steps to modify the test to get different results.

The test has one producer thread pushing 200 random Strings (wrapped with `QueueEntry` objects) and one or more consumer threads "processing" these objects (parking them in an "in-progress-queue" - which is the problematic queue).

```java
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    static class QueueEntry {
        private String data;
        private UUID uuid;

        public QueueEntry(String data) {
            this.data = data;
            this.uuid = UUID.randomUUID();
        }
    }

    @Test
    void testParallelAccess() {
        final RBlockingDeque<QueueEntry> testQueue = redissonClient.getBlockingDeque("test-queue");
        final RBlockingQueue<QueueEntry> testQueueInProgress = redissonClient.getBlockingQueue("test-queue-in-progress");
        //final RLock inProgressQueueLock = redissonClient.getLock("test-queue-in-progress-lock"); // (1)

        final int items = 200;
        CountDownLatch latch = new CountDownLatch(items);
        Thread producer = new Thread(() -> {
            for (int i = 0; i < items; i++) {
                final String string = RandomStringUtils.random(20, true, false);
                testQueue.addFirst(new QueueEntry(string));
            }
        });
        producer.setDaemon(true);
        AtomicBoolean shouldRun = new AtomicBoolean(true);
        final List<Thread> consumers = new ArrayList<>();
        try {
            for (int i = 0; i < 4; i++) { // (4) set the number to >1 to actually parallelize the test and see it fail
                final Thread t = new Thread(() -> {
                    while (shouldRun.get()) {
                        try {
                            final QueueEntry queueEntry = testQueue.pollLastAndOfferFirstTo("test-queue-in-progress", 1, TimeUnit.MINUTES);
                            Thread.sleep(10); // pretend to process the element
                            //inProgressQueueLock.lock(); // (1)
                            testQueueInProgress.removeIf(entry -> entry.getUuid().equals(queueEntry.getUuid())); // (2)
                            //testQueueInProgress.remove(queueEntry); // (3)
                        } catch (InterruptedException e) {
                            // ok
                        } finally {
                            //inProgressQueueLock.unlock(); // (1)
                        }
                        latch.countDown();
                    }
                });
                t.setDaemon(true);
                consumers.add(t);
            }
            consumers.forEach(Thread::start);
            producer.start();

            latch.await(60, TimeUnit.SECONDS);

            Awaitility.waitAtMost(30, TimeUnit.SECONDS).until(() -> testQueue.isEmpty() && testQueueInProgress.isEmpty());
        } catch (InterruptedException e) {
            fail("Probably failed to consume all events!", e);
        } finally {
            redissonClient.shutdown();
            shouldRun.set(false);
        }
    }
```

If you run the test as it is here it will fail because the "in-progress-queue" is not empty.

*Modifications to change the test results:*
1. Change the number of consumer threads to 1 in the line marked with (4). Now the test should pass. Change the number back to something larger than 1.
2. Comment in the RLock and its usages marked with (1). Now the test should pass. Comment the lines out again.
3. Comment out the `removeIf(...)` statement (marked with (2)) and comment in the `remove(...)` statement (marked with (3)) instead. Now the test should pass.

Instead of using `removeIf()` you could also modify the test to use an iterator and remove elements with it. The results will be similar. 

**Redis version**
6.0.8

**Redisson version**
3.13.6

**Redisson configuration**
Default single server config with JsonJacksonCodec.

**Comment by mrniko** [comment]
I'm afraid this method couldn't be implement. It requires global locking for all queue methods which modify queue.

**Comment by philmtd** [comment]
That would apply to all methods using the iterator and the iterator itself I guess?

Perhaps a hint in the JavaDoc or an `UnsupportedOperationException` would help others to avoid errors by using these methods?

**Comment by mrniko** [comment]
Fixed! Thanks for report
