### ISSUE TITLE
Redisson RMap isEmpty() returns unexpected result

### ISSUE THREAD

**Issue by fletcher142** [redisson/redisson#3159]
I have a map stored in redis cluster. When I try to get this map to know if a given key exists in it, I am using
```
        String key = "mykey";
        RMap<String, String> rmap = redissonClient.getMap("mapK", new StringCodec());
        if(rmap.isEmpty() || rmap.get(key) == null){
            throw new RuntimeException("no value found with key: " + key);
        }
        ....
```
It works at most times. But somehow the RuntimeException I defined above will be throw out sometimes unexpectedly. Which means `rMap.isEmpty` returns true with no exception, while the fact is we do have this key stored in redis.

In addition, I found a exception in another thread,
```
[redisson-timer-4-1] o.r.cluster.ClusterConnectionManager     : Can't execute CLUSTER_NODES with /10.211.63.61:6379
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=redis://10.211.63.61:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.3.jar!/:3.13.3]
        .....
```

Does this exception impact the result when I was calling `rMap.isEmpty()'?  And how can I avoid this problem?

**Comment by mrniko** [comment]
> Does this exception impact the result when I was calling `rMap.isEmpty()'? And how can I avoid this problem?

I this this might happen due to replication lag between master and slave. Try to set readMode = MASTER.

**Comment by fletcher142** [comment]
> > Does this exception impact the result when I was calling `rMap.isEmpty()'? And how can I avoid this problem?
> 
> This might happen due to replication lag between master and slave. Try to set readMode = MASTER.

Probably it's not caused by the replication lag, because the fact is, I will constantly call `rMap.isEmpty()`, and it returns false at previous times which is expected, but suddenly it returns true at one point, even this key has not removed from this map. So is that possible caused by connection issue?

**Comment by mrniko** [comment]
No, since with connection issue you would get an error
