### ISSUE TITLE
Will RList<>.add(V) return false ever? 

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#3164]
Will `RList<>.add(V)` return false ever? 

It looks like `RedisCommands.RPUSH_BOOLEAN` command always return true based on below convertor implementation, can you please let's know will it every return `false` assuming there is no `RedisTimeoutException`? 

```
public class TrueReplayConvertor implements Convertor<Boolean> {
    @Override
    public Boolean convert(Object obj) {
        return true;
    }
}
```

**Comment by mrniko** [comment]
it doesn't return false since element is always added to list, otherwise exception is thrown.
