### ISSUE TITLE
redisson-tomcat does not persistent attribute changes properly using updateMode AFTER_REQUEST

### ISSUE THREAD

**Issue by koelnconcert** [redisson/redisson#3172]
Session attributes modified without calling setAttribute are not stored properly in Redis.

The following snippet sets an empty list as a session attribute ("foo") on the first call. Any subsequent call gets the attribute and appends an item ("bar") to the list without calling setAttribute. 

    public class RedissonTestServlet extends HttpServlet {
      @Override
      protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        final HttpSession session = req.getSession();
        if (session.getAttribute("foo") == null) {
          session.setAttribute("foo", new ArrayList());
        } else {
          List list = (List) session.getAttribute("foo");
          list.add("bar");
          //session.setAttribute("foo", list);
        }
      }
    }

**Expected behavior**

With updateMode AFTER_REQUEST the changes should be persisted to Redis after each request regardless of the missing setAttribute.

So the list should expand by one item on every call. 

**Actual behavior**

In Redis there is always only an empty list.

**Steps to reproduce or test case**

[test project](https://github.com/koelnconcert/redisson-tomcat-test) 

**Redis version**

6.0.8

**Redisson version**

3.13.6

**Redisson configuration**

    <Context>
      <Manager className="org.redisson.tomcat.RedissonSessionManager"
               configPath="redisson.conf"
               readMode="REDIS"
               updateMode="AFTER_REQUEST"
               broadcastSessionEvents="false"
               keyPrefix=""/>
    </Context>

**Comment by claytonhoefer** [comment]
@mrniko we just ran into this also, and, looking at the implementation of ```RedissonSession.save()``` (and also monitoring our redis instance to see what's being written), it appears to be by design:

```
if (readMode == ReadMode.MEMORY) {
            topic.publish(createPutAllMessage(newMap));
            
            if (updateMode == UpdateMode.AFTER_REQUEST) {
                if (!removedAttributes.isEmpty()) {
                    topic.publish(new AttributeRemoveMessage(redissonManager.getNodeId(), getId(), new HashSet<>(removedAttributes)));
                }
            }
        }
```

The moment we switch to readMode ```MEMORY```, all works as expected (everything in the session gets flushed on every request).

Could you help us by chance understand why this is the case?  And would you be open to updating the documentation to indicate that updateMode ```AFTER_REQUEST``` can only be used with readMode ```MEMORY```?

cc @okjaybird

**Comment by claytonhoefer** [comment]
> @mrniko we just ran into this also, and, looking at the implementation of `RedissonSession.save()` (and also monitoring our redis instance to see what's being written), it appears to be by design:
> 
> ```
> if (readMode == ReadMode.MEMORY) {
>             topic.publish(createPutAllMessage(newMap));
>             
>             if (updateMode == UpdateMode.AFTER_REQUEST) {
>                 if (!removedAttributes.isEmpty()) {
>                     topic.publish(new AttributeRemoveMessage(redissonManager.getNodeId(), getId(), new HashSet<>(removedAttributes)));
>                 }
>             }
>         }
> ```
> 
> The moment we switch to readMode `MEMORY`, all works as expected (everything in the session gets flushed on every request).
> 
> Could you help us by chance understand why this is the case? And would you be open to updating the documentation to indicate that updateMode `AFTER_REQUEST` can only be used with readMode `MEMORY`?
> 
> cc @OkJaybird

@mrniko any thoughts?

**Comment by mrniko** [comment]
> updateMode AFTER_REQUEST can only be used with readMode MEMORY?

it works in both modes.

**Comment by claytonhoefer** [comment]
> > updateMode AFTER_REQUEST can only be used with readMode MEMORY?
> 
> it works in both modes. For this issue new setting should be added which stores all attributes for REDIS mode

Thanks for the reply!  That might be where my confusion is... what attributes are stored currently in REDIS mode?

**Comment by mrniko** [comment]
Only updated through `setAttribute()` method.

**Comment by claytonhoefer** [comment]
> Only updated through `setAttribute()` method.

OK, so with readMode ```REDIS```, the updateMode is effectively ```DEFAULT```.  You can't achieve the ```AFTER_REQUEST``` behavior unless you set readMode to ```MEMORY```.  That makes sense, but it would still be helpful to update the README to indicate that ```REDIS``` + ```AFTER_REQUEST``` is effectively not a supported configuration.  You don't get the ```AFTER_REQUEST``` behavior described in the documentation.

**Comment by mrniko** [comment]
If have a look at source code you'll see that `AFTER_REQUEST` works in REDIS mode.

**Comment by mrniko** [comment]
Documentation updated.

**Comment by tmuldoon** [comment]
@mrniko Thank you!
