### ISSUE TITLE
About tomcat context.xml 

### ISSUE THREAD

**Issue by linux0x5c** [redisson/redisson#3176]
I am not very clear about the specific role of readmode="MEMORY". If readmode="MEMORY" should be enabled at the same time broadcastSessionEvents="true" this attribute to ensure the consistency of multiple copies of the session? Does readmode="MEMORY" just store an extra session in the tomcat memory? When I simulate redis downtime, redisson will not directly read the cache from tomcat, but continue to connect to redis to get the session.I need help,thanks.

**Comment by mrniko** [comment]
> broadcastSessionEvents="true" this attribute to ensure the consistency of multiple copies of the session?

`broadcastSessionEvents` broadcasts only session create and destroy events.

in readmode="MEMORY" Redisson read session attributes from memory. If it doesn't exist in memory then Redisson loads it from Redis.
