### ISSUE TITLE
After integrating with spring-data-redis, redisTemplate get  method always returns null

### ISSUE THREAD

**Issue by HengCC** [redisson/redisson#3180]
springboot version : 2.3.3.RELEASE

spring data redis dependency
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
```

**Redis version**
null
**Redisson version**
```
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.13.6</version>
        </dependency>
```
**Redisson configuration**
```
public class RedissonSpringDataConfig {
    @Value("${spring.redis.cluster.nodes}")
    String redisNodes;
    @Value("${spring.redis.password}")
    String redisPass;

    @Bean
    public RedissonConnectionFactory redissonConnectionFactory(RedissonClient redisson) {
        return new RedissonConnectionFactory(redisson);
    }

    @Bean(destroyMethod = "shutdown")
    public RedissonClient redisson() throws Exception {
        if (StringUtils.isEmpty(redisNodes)) {
            throw new Exception("redis cluster nodes must not be null");
        }
        Config config = new Config();
        config.useClusterServers()
                .addNodeAddress(
                        Arrays.stream(redisNodes.split(",")).map(item -> "redis://" + item).toArray(String[]::new)
                ).setPassword(redisPass);
        return Redisson.create(config);
    }

}
```

**Expected behavior**

I want to use redisTemplate and redissonClient at the same time. Based on the above configuration, using redisTemplate can set the value during operation. But the get value is always null

When I remove the RedissonConnectionFactory injected in RedissonSpringDataConfig, redisTemplate will use lettuceConnectionFactory by default. At this time, there is no problem using redisTemplate's get method and set method. The get method can also return normal values.

**Actual behavior**

redisTemplate's get method always return null
**Steps to reproduce or test case**
null

**Comment by HengCC** [comment]
demo
```
 redisTemplate.opsForValue().set("demo", "demo-test", 60, TimeUnit.SECONDS);
 log.info("{}", redisTemplate.opsForValue().get("demo"));  ---> this will return null
```

**Comment by HengCC** [comment]
The cause of this problem may be that the master-slave synchronization of the cluster did not proceed normally. The problem did not reappear after setting readmode to ReadMode.MASTER, close this issue

**Comment by pollux611** [comment]
use StringRedisTemplate instead

**Comment by csgear** [comment]
Define the bean as the following:    

`private final RedisTemplate<Object, Object> redisTemplate ;`

The restTemplate bean defined in 
redisson-spring-boot-starter/src/main/java/org/redisson/spring/starter/RedissonAutoConfiguration.java

`  @Bean
    @ConditionalOnMissingBean(name = "redisTemplate")
    public RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<Object, Object> template = new RedisTemplate<Object, Object>();
        template.setConnectionFactory(redisConnectionFactory);
        return template;
    }`
