### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException even after 3 retry attempts

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#3182]
**Expected behavior**

With retries enabled WriteRedisConnectionException shouldn't happen. 

**Actual behavior**
We have set netty threads and max connections to 250. When Redission is retrying will it use different netty connection, or attempt using same channel which is throwing `newClosedChannelException`/`ClosedChannelException`? It's not clear from below error what other tuning is required in application code.  

`"org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=5, freeConnectionsCounter=value:106:queue:0, freezed=false, freezeReason=null, client=[addr=redis://172.26.45.181:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1729007529 [redisClient=[addr=redis://172.26.45.181:6379], channel=[id: 0xe8e83a99, L:/172.26.134.191:53989 - R:172.26.45.181/172.26.45.181:6379], currentCommand=null], command: (RPUSH), params: [usermessage_queue2, PooledUnsafeDirectByteBuf(ridx: 0, widx: 1281, cap: 4096)] after 3 retry attempts\n\tat org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:270)\n\tat org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:58)\n\tat org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:155)\n\tat org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:152)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)\n\tat io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)\n\tat io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)\n\tat io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762)\n\tat io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1089)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.nio.channels.ClosedChannelException: null\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)\n\t... 12 common frames omitted\n",`

**Steps to reproduce or test case**
Intermittent exception noticed in production logs.

**Redis version**
5.0.6

**Redisson version**
3.12.4

**Redisson configuration**

```
Config config = new Config();
config.setCodec(StringCodec.INSTANCE);
config.setNettyThreads(CacheConstants.MAX_TOTAL_CONNECTIONS);

SentinelServersConfig serverConfig = config.useSentinelServers()
				.setMasterName(CacheConstants.MASTER_NAME)
				.setScanInterval(2000) 
				.setReadMode(READ_MODE)
				.setTimeout(CacheConstants.TIMEOUT) 
				.setMasterConnectionMinimumIdleSize(CacheConstants.MIN_IDLE_CONNECTIONS)
				.setMasterConnectionPoolSize(CacheConstants.MAX_TOTAL_CONNECTIONS)
				.setSlaveConnectionMinimumIdleSize(CacheConstants.MIN_IDLE_CONNECTIONS)
				.setSlaveConnectionPoolSize(CacheConstants.MAX_TOTAL_CONNECTIONS)
				.setKeepAlive(true)
				.setPingConnectionInterval(CacheConstants.PING_INTERVAL)
				.setCheckSentinelsList(false);
```

**Comment by mrniko** [comment]
> When Redission is retrying will it use different netty connection, or attempt using same channel which is throwing newClosedChannelException/ClosedChannelException?

It uses next connection available in pool.

> Unable to write command into connection ... after 3 retry attempts

I would recommend you to increase [retryAttempts](https://github.com/redisson/redisson/wiki/2.-Configuration#retryattempts) parameter.

**Comment by rgampa** [comment]
@mrniko Thanks. I think default 3 retires with 1.5 seconds retryInterval is good enough, that's why I didn't change. As you mentioned if the retries are tried on next available connection then we are good, but it's not convincing why it couldn't find an available connection in 3 retries. In a given day we are observing 2-3 error spikes of 200-300 errors lasts only for a minute. We tried increasing connection pool size to 500, and netty threads to 500, I will create another issue if we observe the issue again. The error spike only happens in one of the application servers at a time, we have checked with our network team, if there is an issue they said it will impact all application servers as they share same subnet.

**Comment by cloudInspire** [comment]
@rgampa This problem have been solved?

**Comment by rgampa** [comment]
@cloudInspire Increasing nettyThreads helped.

**Comment by RafiyaB** [comment]
we are seeing this issue in our system, what exactly need to be done?
