### ISSUE TITLE
Desired TTL is not being set for new cache maps

### ISSUE THREAD

**Issue by ggeighty8** [redisson/redisson#3183]
Hi, 

I am trying to set the TTL on the cache map as shown in the snippet below but I am noticing that the TTL is set to -1 and not the value I am passing. Is this the right way to go about setting the TTL for the cache maps? If not what is the right way?

```
private RedissonClient client;
.
.
.
public <K, V> RMap<K, V> getCachedMap(String key, long expiry, TimeUnit timeUnit) {
    if (!isConnectionAlive()) {
        return null;
    }
    try {
        RMap<K, V> map = client.getMap(key);
        map.expire(expiry, timeUnit);
        return map;
    } catch (RedisTimeoutException | RedisConnectionException e) {
        setConnectionAlive(false);
        logger.error("RedisTimeoutException | RedisConnectionException occurred.", e);
        return null;
    }
}
```

This is what I see on enabling the debug logs: 
```acquired connection for command (PEXPIRE) and params [INTERACTIVE:event.9cf3de43-8c57-4247-a454-78c615cfdf1a.instance.acc38bdd-fdcb-4232-a701-eb7dadda894a..., 86400000] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=50, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=49, freeConnectionsCounter=value:199:queue:0, freezed=false, freezeReason=null, client=[addr=redis://redis:6379], nodeType=MASTER, firstFail=0]]] using node redis/169.254.169.3:6379... RedisConnection@1303942170 [redisClient=[addr=redis://redis:6379], channel=[id: 0x3a5aaba3, L:/169.254.169.30:53094 - R:redis/169.254.169.3:6379], currentCommand=null]```

So looks like it is indeed trying to set the TTL. 

I am using redisson version `3.13.1`

**Comment by mrniko** [comment]
Expiration can't be applied to empty maps. You need to store at least one entry in map and then set expiration time.
