### ISSUE TITLE
How to clear Redis cache when deployed to 2 or more containers?

### ISSUE THREAD

**Issue by pavankjadda** [redisson/redisson#3185]
In my Spring Boot project, I have one redis container deployed in Docker swarm cluster. I use it as Hibernate 2nd level cache for the application. I use Redisson client to manually clear the cache using the following code
```
Config config = new Config();
config.useSingleServer().setAddress("redis://" + redisProperties.getHost() + ":" + redisProperties.getPort());
RedissonClient redisson = Redisson.create(config);
redisson.getKeys().flushdb();
logger.info("Successfully cleared the Redis Cache");
redisson.shutdown();
```

Now I would like to scale it to multiple containers to withstand failover and distribute the load. If I do that, how can I clear the cache in 2 or more containers at the same time?

**Comment by mrniko** [comment]
if containers connected to the same Redis setup then you need to call flushdb once in any container.

**Comment by pavankjadda** [comment]
My swarm cluster has 3 nodes. 1 manager and 2 worker nodes. And I scaled Redis service to 2 containers. Based on what I read, for each container docker swarm creates volumes that are local to each node. So, when I use flushdb in any container, would it clear cache in both?

**Comment by pavankjadda** [comment]
I think I need to create new NFS volume in our organization network and use it in swarm service. When docker starts containers it will load data to local volume from NFS volume. When I clear the cache using Redission, NFS volume will be updated, which then synced to all Redis containers

**Comment by mrniko** [comment]
> So, when I use flushdb in any container, would it clear cache in both?

Yes

**Comment by pavankjadda** [comment]
Okay, I tried it. It's not clearing cache in both containers. One container cache is being cleared and other one not, leaves the data in consistent state.
