### ISSUE TITLE
Behavior of locks vs conditions like network partition

### ISSUE THREAD

**Issue by pnaw94** [redisson/redisson#3187]
Hello everyone,

Couldn't find my answer in docs or by looking briefly at the implementation, so posting the question here.

Let's assume a system, where X instances of the same application are working concurrently on processing some data. In general, the instances can work concurrently, but some specific data items must not be processed at the same time by more than one instance, as this would produce race condition.

To synchronize application instances and avoid race conditions, we've set up a Redis instance, and we use Redisson's locking mechanism to achieve exclusive execution. In general, the workflow for an instance looks like this:
(take a lock A) -> (process data) -> (release lock A)

Then, obviously, the other instances, that want to process the conflicting data item, need to wait for lock A to be released. Processing an item can take anywhere between several seconds and several days. so a lock might be held for a long time (and we use this auto-renewal feature for locks to have the lock prolonged as needed behind the scenes by Redisson).

My question is - what happens if an instance, that is currently holding the lock, loses connectivity to Redis (and therefore the lock times out and is then taken by another instance), and then after some time it regains the connectivity? Will it finish processing the data without holding the lock, and then fail on releasing the lock? Or maybe something else would happen?

I'd really appreciate your feedback on this.

Best Regards,
Paweł

**Comment by mrniko** [comment]
> Will it finish processing the data without holding the lock, and then fail on releasing the lock?

It will finish without holding lock if connectionWatchdogTimeout occured by that moment.

**Comment by pnaw94** [comment]
@mrniko thanks for the answer! I think that's all I need at that point.
