### ISSUE TITLE
Authentication broken for Sentinel configuration

### ISSUE THREAD

**Issue by Godsim** [redisson/redisson#3189]
HI there,

it seems like the Redisson authentication is broken for the current release 3.13.6 in combination with a Redis 6.0.9 and a Sentinel setup. I provide the password with the config object:

`config.useSentinelServers()
                .setMasterName("sentinel-master")
                .addSentinelAddress("redis://127.0.0.1:26379")
                .setPassword("redis");`

I suspect the implementation of the _checkAuth()_ and _createRedisConfig(...)_ methods in **SentinelConnectionManager**.
Since the default of **usePassword** is **false**, this results in the provided password being set to null in _createRedisConfig(..)_, which subsequently causes _checkAuth()_ to fail prematurely on line 213 _client.connect()_ with a RedisConnectionException caused by an RedisAuthRequiredException. Therefore, **usePassword** is never set to true and the Redission Sentinel config is broken for secured Sentinel instances.

**Comment by mrniko** [comment]
Please try version attached

[redisson-3.13.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5492333/redisson-3.13.7-SNAPSHOT.jar.zip)

**Comment by Godsim** [comment]
This jar seems to be missing some class definitions, can't replace 3.13.6 and test with this one.

**Comment by mrniko** [comment]
Here is redisson-all version

[redisson-all-3.13.7-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5500875/redisson-all-3.13.7-SNAPSHOT.jar.zip)

**Comment by Godsim** [comment]
I can confirm that the sentinel authentication works as expected with your provided 3.13.7-snapshot

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3135
