### ISSUE TITLE
Local Cache performance : Cache Key extra operations

### ISSUE THREAD

**Issue by skiran-a** [redisson/redisson#3190]
Hello Everyone,

The Local cache map data types for key is CacheKey and for value is CacheValue. The CacheKey contains the hashed value of encoded original key object. Due to this, when ever redisson tries to retrieve from the local cache, it has to encode the key and convert to hash value and get value from the local cache. 

Is there any specific reason behind this approach? What if the CacheKey stores the original key directly? Will that improves the local cache performance?

Best Regards
Sai

**Comment by mrniko** [comment]
Hash is used to compress state. Data should be compared by state like it's done on Redis side.
