### ISSUE TITLE
Always get a deprecation error log about JSON even though not using

### ISSUE THREAD

**Issue by mikehardenize** [redisson/redisson#3196]
**Expected behavior**

I point RedissonSessionManager at a YAML config file. I don't get a deprecation warning about using JSON config files.

**Actual behavior**

I point RedissonSessionManager at a YAML config file. I do get a deprecation warning about using JSON config files.

**Steps to reproduce or test case**

Point RedissonSessionManager at a YAML config file. Get a deprecation warning about using JSON config files.

**Redis version**

6.0.8

**Redisson version**

3.13.6

**Redisson configuration**

```yaml
singleServerConfig:
  address: "redis://127.0.0.1:${REDIS_PORT:-6379}"
```

**Comment by mikehardenize** [comment]
RedissonSessionManager.buildClient always attempts to parse the config file as JSON before doing anything else. It does this by calling Config.fromJSON, which is marked as deprecated.

**Comment by mikehardenize** [comment]
An associate pointed out to me that JSON is a subset of YAML anyway. So even if you removed the JSON parsing code, people should still be able to write their config using JSON.

**Comment by mrniko** [comment]
Fixed! Thanks for report
