### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads

### ISSUE THREAD

**Issue by pallavab** [redisson/redisson#3203]
Getting below exception intermittently during execution of a multi-threaded batch process.

 org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! **Increase nettyThreads and/or retryInterval settings.** Payload size in bytes: 9. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=4, freeSubscribeConnectionsCounter=value:299:queue:0, freeConnectionsAmount=52, freeConnectionsCounter=value:492:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xx.xx.xx.xxx:xxxx], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1880328440 [redisClient=[addr=redis://xx.xx.xx.xxx:xxxx], channel=[id: 0x7dfdf73d, L:/xx.xx.xx.xxx:xxxx - R:/xx.xx.xx.xxx:xxxx], currentCommand=null], command: (HGET), params: [ABC_CACHE_REGION$ABC_CODE, PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 256)] after 3 retry attempts,

**Comment by mrniko** [comment]
which Redisson version do you use?

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/2559

**Comment by pallavab** [comment]
redisson-3.11.5.jar

**Comment by pallavab** [comment]
redisson-3.11.5.jar

**Comment by pallavab** [comment]
can you please reopen this ticket

**Comment by pallavab** [comment]
@mrniko  : Request you to have a look on this, the challenge is being faced at one one the largest enterprise product and we are nearing our product's GA release this month.

**Comment by mrniko** [comment]
this is a duplicated ticket https://github.com/redisson/redisson/issues/3203#issuecomment-725234590

**Comment by pallavab** [comment]
@mrniko : Thanks for your usual prompt response, since the reference ticket is closed as well yet did not find any closure remarks so no able to figure out exactly what caused the issue , I need your help in following : 
1. was that slowness at network layer , and should I focus there to closes it ?
2. is there any full release after redisson 3.13.0 which has the patch ?
3. do we need to change the code to avoid several get invocations in a row to the same object in order to fix this ?

**Comment by mrniko** [comment]
> is there any full release after redisson 3.13.0 which has the patch ?

It's not an issue of lib. If you read comments to #3203 you'll see that this error arise due to particular use case.
