### ISSUE TITLE
RMap is holding huge memory compared to normal object in Redis

### ISSUE THREAD

**Issue by ravinirmal10** [redisson/redisson#3205]
While working on memory improvements for Redis, I came across with an issue where I have observed that Redis is using huge memory for RMap compared to normal object. 

I have execute below code and I observed below things:
- I could see memory occupied in Redis for key `abcd-abcd:map` is 10728729 bytes(10.72 MB), I have used command `MEMORY USAGE abcd-abcd:map`.
- I could see memory occupied in Redis for key `abcd-abcd` is 1170360 bytes(1.17 MB), I used command `MEMORY USAGE abcd-abcd`

My question is if I am saving one object(`hashmap`) as an `RMap` and saving the same object(`hashmap`) as a value in another `Map` then why the object saved in `RMap` is occupying huge amount of memory compared to other case?

Please note currently I kept `SIZE` as 100000, but in my case I need to save 1-2 million(or more than that) objects in `RMap` and in that case I can see huge memory utilization in Redis.

Can someone please review this and share their thoughts?

```
public class RedisTest {
  
  private static final int SIZE = 100000;
  private static Codec compositeCodec = new 
      CompositeCodec(new StringCodec(), new LZ4Codec(new SerializationCodec()),  new SerializationCodec());
  private static String initId = "abcd-abcd";

  public static void main(String[] args) {
    Config config = new Config();
    config.useSingleServer().setAddress("redis://127.0.0.1:6379");
    RedissonClient redissonClient = Redisson.create(config);
    RMap<String,String> rmap = redissonClient.getMap(initId + ":map", compositeCodec);
    Map<String, String> hashMap = getMap();
    rmap.putAll(hashMap);
    RMap<Object, Object> rootMap = redissonClient.getMap(initId, compositeCodec);
    rootMap.put("object", hashMap);
    redissonClient.shutdown();
  }
  
  private static Map<String, String> getMap() {
    Map<String, String> hashMap = new HashMap<>();
    for (int i = 0; i < SIZE; i++) {
      hashMap.put("keykeykeykeykeykeykeykeykeykeykeykey"+i, "valuevaluevaluevaluevaluevaluevaluevaluevalue"+i);
    }
    return hashMap;
  }

}
```

**Comment by mrniko** [comment]
`rmap` object is greater since it has 100000 entries and `rootMap` has lower size because it has only single entry

**Comment by ravinirmal10** [comment]
> `rmap` object is greater since it has **100000 entries** and `rootMap` has lower size because it has only **one entry**. Moreover map with single entry has repeated strings in value, like "valuevaluevaluevaluevaluevaluevaluevaluevalue" "keykeykeykeykeykeykeykeykeykeykeykey", which are subject for compression with a good ratio.

@mrniko - I understand that due to more number of entries it is occupying higher amount of memory, but the difference is way higher(nearly 800% in this case) compared to single object.

Also, map with single entry and multiple entries have exact same strings i.e. `hashMap` object has exact same amount of data when its stored into `RMap` OR `rootMap`, the only difference is in `RMap` each key-value stored as separate entries and in `rootMap` it is stored as single entry.
