### ISSUE TITLE
default codec MarshallingCodec result in exception "ERR hash value is not a float" when using map.addAndGet

### ISSUE THREAD

**Issue by ymiao** [redisson/redisson#3210]
**Expected behavior**
no exception when use default config
**Actual behavior**
have exception, but if i set codec to JsonJacksonCodec, everything works
**Steps to reproduce or test case**
use defatult config with default MarshallingCodec
**Redis version**
redis 5, 6
**Redisson version**
3.13.0 - 3.13.6
**Redisson configuration**
Config config = new Config();

**Comment by mrniko** [comment]
Because JsonJacksonCodec stores numbers as plain string. MarshallingCodec can't be used in this case.
