### ISSUE TITLE
RMap keySet throw java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by 534519560** [redisson/redisson#3214]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
` RMap<Integer, Classify> map = redissonClient.getMap(RedisNameSpace.PermanentCache.classify);

        for (Map.Entry<Integer, Classify> integerClassifyEntry : map.entrySet()) {  //here is ok
            System.out.println(integerClassifyEntry); // printData:9241=Classify(id=9241)
        }

        for (Integer integer : map.keySet()) { //here will throw java.lang.ClassCastException: java.lang.String cannot be cast to 
                                                                   //java.lang.Integer
            System.out.println(integer); 
        }`
**Redis version**

**Redisson version**
3.13.6
**Redisson configuration**
default config

**Comment by mrniko** [comment]
Unable to reproduce it using test below:

```java
        RMap<Integer, MyObject> map = redisson.getMap("test");

        map.put(1, new MyObject());
        map.put(2, new MyObject());
        map.put(3, new MyObject());

        for (Integer integer : map.keySet()) {
            System.out.println(integer);
        }
```
