### ISSUE TITLE
redis 使用哨兵模式，开启读写分离，redisTemplate.opsForGeo().radius 报错

### ISSUE THREAD

**Issue by ww469644142** [redisson/redisson#3216]
public class RedisTest extends BaseTest {

    @Autowired
    private RedisTemplate redisTemplate;
    
    @Test
    public void testGeo() {
        String key = "test_geo_key";
        Point point = new Point(116.401001, 40.119499);
        redisTemplate.opsForGeo().add(key, point, "a");

        point = new Point(111.545998, 36.133499);
        redisTemplate.opsForGeo().add(key, point, "b");

        point = new Point(111.483002, 36.030998);
        redisTemplate.opsForGeo().add(key, point, "c");
        Circle within = new Circle(116.401001, 40.119499, 80000);
        RedisGeoCommands.GeoRadiusCommandArgs args = RedisGeoCommands.GeoRadiusCommandArgs.newGeoRadiusArgs().includeCoordinates();
        GeoResults<RedisGeoCommands.GeoLocation<String>> res = redisTemplate.opsForGeo().radius(key, within, args);
        System.out.println(res);
    }

}

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by ww469644142** [comment]
你好，我下载master 代码打包测试， 同样报错。 底层使用GEORADIUS 命令，会进行STORE 有写的操作，这样操作从库报错。
![image](https://user-images.githubusercontent.com/19383399/99752640-a6f53380-2b1f-11eb-92eb-c01c7250180d.png)

**Comment by ww469644142** [comment]
@mrniko

**Comment by mrniko** [comment]
Fixed
