### ISSUE TITLE
compatibility with spring-session 2020.0.1

### ISSUE THREAD

**Issue by BigMichi1** [redisson/redisson#3220]
i have seen on the wiki that currently redisson officially supports spring-boot up to version 2.3, the same for spring-session and spring-data. which version of reddisson library should I use when running with spring-boot 2.4.0 and spring-session 2020.0.1?

```
compile 'org.springframework.session:spring-session-core:2.3.1.RELEASE'
compile 'org.redisson:redisson-spring-data-23:3.13.6'
```

**Comment by mrniko** [comment]
Redisson 3.14.0 version. Since it support Spring Data 2.4.0 version used by spring-boot 2.4.0
