### ISSUE TITLE
Adding permit later doesn’t unblock thread

### ISSUE THREAD

**Issue by asarkar** [redisson/redisson#3225]
Thread A:
1. Get semaphore.
2. Set permit = 1.
3. Acquire permit = 2. (Blocks)

Thread B:
1. Get semaphore.
2. Acquire permit = 1. (may block for step `A.2`)
3. Do stuff.
4. Release permit = 1.
5. Add permit = 1.

I expected step `B.5` to unblock thread `A`, but that doesn’t happen.

**Comment by mrniko** [comment]
Fixed. Thanks for report
