### ISSUE TITLE
Rlock not able to handle 200 concurrent requests

### ISSUE THREAD

**Issue by sagar694** [redisson/redisson#3227]
Hi,
I was trying to use distributed lock to do some operations and here I am facing an issue - it wasn't able to handle more than 200 concurrent requests

I am using redis as single server instance for this testing and here is my code

try {
            RLock lock = redisTemplate.getLock("lock");
            boolean lockStatus = lock.tryLock(10000L, 200L,TimeUnit.MILLISECONDS);
            log.info("lock status" + String.valueOf(lockStatus));
            // do some operations - this operation doesn't take more than 100 ms and so the same can be simulated with sleep 
            Thread.sleep(100)
            if(lock.isHeldByCurrentThread()){
                 lock.unlock();
             }
        }catch (Exception e) {
            log.error("Exception Occured " + e);
        }

Please advise on what to look for to handle higher concurrency and handle the required requests per second. Our target was to handle around 1k concurrent requests

**Comment by mrniko** [comment]
performance depends on factors like: network, CPU resources of both application and Redis
