### ISSUE TITLE
redisson-spring-boot-starter， version 3.13.6  

### ISSUE THREAD

**Issue by seart** [redisson/redisson#3229]
<groupId>org.redisson</groupId>
<artifactId>redisson-spring-boot-starter</artifactId>
<version>3.13.6</version>

When I use the following command, an exception is thrown，I tried a lot of high version, the error message is the same.
I use the  version: 3.5.5, It is work. so why the high version doesn't work ?

geo.radiusWithDistance(lon, lat, 3, GeoUnit.KILOMETERS, GeoOrder.ASC, 10);

Exception in thread "main" org.redisson.client.RedisException: ERR unknown command 'GEORADIUS_RO'. channel: [id: 0x85a94190, L:/127.0.0.1:52892 - R:/127.0.0.1:6379] command: (GEORADIUS_RO)

**Comment by mrniko** [comment]
GEORADIUS_RO is used to read data from Redis slave. You need to update to Redis to 3.2.10 version or higher.

**Comment by seart** [comment]
> GEORADIUS_RO is used to read data from Redis slave. You need to update to Redis to 3.2.10 version or higher to get it work.

thanks，I thought 13 was bigger than 2 ， but it was smaller than 2
