### ISSUE TITLE
ElementsSubscribeService

### ISSUE THREAD

**Issue by darknessp** [redisson/redisson#3231]
hi, I'm using redisson's ElementsSubscribeService along with redis BRPOPLPUSH command to subscribe to a redis list, so that I can retrieve an element from the tail of the list (and move that element to the head of the same list) when another client pushes an element to this list.
But when I push an element to the list and consume that element from the same application (spring context), the consumer's redisson operation got blocked during handling.
consumer pseudo code:
```
public class RedissonConsumer implements ApplicationRunner, Consumer<Object>{
   
    // implements Consumer
    @override
    public accept(Object obj){
        redisson.getLock(obj);
        try{
            if(lock.tryLock()){
                // handle this message
            }
        }finally{
            // it got blocked here !!!!
            if(lock.isHeldByCurrentThread()){
                lock.unlock();
            }
        }
    }

    // implements ApplicationRunner
    @Override
    public void run(ApplicationArguments args) throws Exception {
        redisson().getConnectionManager().getElementsSubscribeService()
            // BRPOPLPUSH the same queue
            .subscribeOnElements(() -> blockingQueue().takeLastAndOfferFirstToAsync(queue()), this);
    }
}
```

here is the log right before the consumer got stuck:
`11-21-2020 18:41:02.802 DEBUG [redisson-netty-10-2] [ef6a4d1a805343bb940527ce0b1c2401] o.r.c.RedisExecutor.sendCommand: acquired connection for command (HEXISTS) and params [lock..., f2562a06-3333-de34-91a6-5ce57111892d:26] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:61:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using node /127.0.0.1:6379... RedisConnection@1489204891 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xde7fb2e3, L:/127.0.0.1:64542 - R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@33046ebc(success: {"data":"d1725d293d494bc58a798887febe0f4e"})], command=(BRPOPLPUSH), params=[951fb209-26ed-47ed-b57d-f7f743a51d6b, 951fb209-26ed-47ed-b57d-f7f743a51d6b, 0], codec=org.redisson.codec.JsonJacksonCodec]]
`

log after:
`
11-21-2020 18:41:07.196 DEBUG [redisson-timer-12-1] [] o.r.c.RedisExecutor.lambda$releaseConnection$7: connection released for command (HEXISTS) and params [lock..., f2562a06-3333-de34-91a6-5ce57111892d:26] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=3, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1489204891 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xde7fb2e3, L:/127.0.0.1:64542 - R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@33046ebc(success: {"data":"d1725d293d494bc58a798887febe0f4e"})], command=(BRPOPLPUSH), params=[951fb209-26ed-47ed-b57d-f7f743a51d6b, 951fb209-26ed-47ed-b57d-f7f743a51d6b, 0], codec=org.redisson.codec.JsonJacksonCodec]]
11-21-2020 18:41:07.197 WARN [redisson-netty-10-2] [ef6a4d1a805343bb940527ce0b1c2401] i.n.u.c.DefaultPromise.notifyListener0: An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$769/1780936422.operationComplete()
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=2, freeConnectionsCounter=value:62:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1489204891 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xde7fb2e3, L:/127.0.0.1:64542 - R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@33046ebc(success: {"data":"d1725d293d494bc58a798887febe0f4e"})], command=(BRPOPLPUSH), params=[951fb209-26ed-47ed-b57d-f7f743a51d6b, 951fb209-26ed-47ed-b57d-f7f743a51d6b, 0], codec=org.redisson.codec.JsonJacksonCodec]], command: (HEXISTS), params: [lock..., f2562a06-3333-de34-91a6-5ce57111892d:26] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:200) ~[redisson-3.12.5.jar:3.12.5]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.52.Final.jar:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]`
can you help me with this? many thanks!

**Comment by mrniko** [comment]
ElementsSubscribeService isn't intended for external usage.
