### ISSUE TITLE
Redis elasticache (ReplicatedServersConfig) RW/RO endpoint or all nodes ?

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#3238]
Hi,

I am trying to use redisson to connect to an AWS Elasticache (not cluster) redis,
I can't find a clear answer on what 'nodes' should I list in redisson config.

Should I put : (using AWS front endpoints)
master.myredis.xxxx.usw2.cache.amazonaws.com:6379,
reader.myredis.xxxx.usw2.cache.amazonaws.com:6379

or (all nodes endpoint) :
myredis-001.xxx.usw2.cache.amazonaws.com:6379,
myredis-002.xxx.usw2.cache.amazonaws.com:6379,
myredis-003.xxx.usw2.cache.amazonaws.com:6379,
...

(in the past I used the master.myredis... directly in a node application, didn't dig more into it then).

Thanks.

**Comment by mrniko** [comment]
for non-cluster AWS Elasticache setup (replicated mode) you need to list all nodes in configuration
