### ISSUE TITLE
config sentinelAddresses with k8s service address(ClusterIP) error

### ISSUE THREAD

**Issue by stheart** [redisson/redisson#3246]
may i ask if i can only config the sentinelAddresses with fixed ip address?
in my k8s env,there are three redis sentinel pods(ip may change when restart),these pods match k8s service(clusterIp)：rfs-redisfailover.silot-system.svc.cluster.local:26379
i use this service address to config sentinelAddresses,found constantly error log.

**Expected behavior**
connect redis correct.

**Actual behavior**
constantly log error like
sentinel: redis://10.103.81.250:26379 is down
sentinel: redis://10.103.81.250:26379 added
sentinel: redis://10.103.81.250:26379 is down
sentinel: redis://10.103.81.250:26379 added
sentinel: redis://10.244.12.76:26379 is down
sentinel: redis://10.103.81.250:26379 is down
**Redis version**
5.0.10
**Redisson version**
3.14.0
**Redisson configuration**
spring:
    redis:
      redisson:
        config: |
          sentinelServersConfig:
            password:
            sentinelAddresses:
              - "redis://rfs-redisfailover.silot-system.svc.cluster.local:26379"
            masterName: "mymaster"
            checkSentinelsList: false
          transportMode: "NIO"

**Comment by mrniko** [comment]
This happens when all sentinel servers doesn't have the same list of sentinels.

**Comment by stheart** [comment]
thanks for respond
i have try this:
sentinelAddresses:
- "redis://rfs-redisfailover.silot-system.svc.cluster.local:26379"
three sentinel pods name:
rfs-redisfailover-7c4f4dd978-685xb, rfs-redisfailover-7c4f4dd978-cvrtg, rfs-redisfailover-7c4f4dd978-rgc29
i enter each pod to exec comands:sentinel sentinels mymaster,and found result below
![image](https://user-images.githubusercontent.com/49032936/100626692-1a3d4780-3361-11eb-8d28-98eaef3b84db.png)

**Comment by stheart** [comment]
thanks for respond,i have login in each sentinel to exec command:sentinel sentinels mymaster，it seems that each sentinel got other two sentinel's ip address, and ip is correct
sentinelAddresses:redis://rfs-redisfailover.silot-system.svc.cluster.local:26379

sentinel1:rfs-redisfailover-7c4f4dd978-685xb,ip:10.244.15.254
 exec command:sentinel sentinels mymaster,got result
    1) "name"
    2) "956bddd5956217c94b18790e1f57a27041d410f8"
    3) "ip"
    4) "10.244.17.232"

    1) "name"
    2) "5f79c230f15e7e2d131d37c3c2d315b0eb5b1ad6"
    3) "ip"
    4) "10.244.13.218"

sentinel2:rfs-redisfailover-7c4f4dd978-cvrtg,ip:10.244.17.232
 exec command:sentinel sentinels mymaster,got result
    1) "name"
    2) "b944c6404a09a56d5a583cbf5cb134b7ba48600f"
    3) "ip"
    4) "10.244.15.254"

    1) "name"
    2) "5f79c230f15e7e2d131d37c3c2d315b0eb5b1ad6"
    3) "ip"
    4) "10.244.13.218"

sentinel3:rfs-redisfailover-7c4f4dd978-rgc29,ip:10.244.13.218
 exec command:sentinel sentinels mymaster,got result
    1) "name"
    2) "956bddd5956217c94b18790e1f57a27041d410f8"
    3) "ip"
    4) "10.244.17.232"

    1) "name"
    2) "b944c6404a09a56d5a583cbf5cb134b7ba48600f"
    3) "ip"
    4) "10.244.15.254"

**Comment by mrniko** [comment]
I need to add more debug logging to SentinelConnectionManager to trace this issue

**Comment by stheart** [comment]
@mrniko  thanks for reply,i use k8s headless service address rather than k8s service address to config sentinelAddresses,and the problem is solved, i guess its because k8s service load balance function,it will return one different ip each time,so i use  headless service(this kind of service just like dns,will not load balance) instead.
