### ISSUE TITLE
Client unable to discover cache node because of primary node failure

### ISSUE THREAD

**Issue by UditManiyar** [redisson/redisson#3247]
Our cache cluster has 3 shards with single master in each shard and 0 slaves.

*Expected behavior*
When the Redis cluster node fails aws(elastic cache for redis) will create a new node and replace the failed node. After the replacement is successful client should be able to discover the new node again.

*Actual behavior*
Redisson client is unable to discover the new node. And all the calls are failing until we force the re creation of the client from the start.

*Steps to reproduce or test case*
1. We are working on AWS ElastiCache for Redis
2. Our cache cluster has 3 shards. Each shard has 1 master and 0 replication nodes.
3. When one of the shard’s primary node fails(happens in case maintenance) all the calls which get directed to that particular shard fail after that.
4. This behaviour is observed only when there is some traffic at the time of node failure. If there is no traffic at the time of node failure the client seems to work perfectly fine and serve requests at later time.

I have observed the following log statements:
```
[INFO] (redisson-netty-2-23) org.redisson.connection.pool.PubSubConnectionPool: 1 connections initialized for 10.0.61.135/10.0.61.135:6379
[INFO] (redisson-netty-2-5) org.redisson.cluster.ClusterConnectionManager: slave: redis://10.0.61.135:6379 added for slot ranges: [[0-5461]]
[INFO] (redisson-netty-2-5) org.redisson.connection.pool.SlaveConnectionPool: 24 connections initialized for 10.0.61.135/10.0.61.135:6379
[INFO] (redisson-netty-2-5) org.redisson.cluster.ClusterConnectionManager: slave redis://10.0.61.135:6379 removed for slot ranges: [[0-5461]]
[INFO] (redisson-netty-2-5) org.redisson.cluster.ClusterConnectionManager: 5462 slots removed from redis://10.0.61.135:6379
[ERROR] (redisson-netty-2-13) org.redisson.cluster.ClusterConnectionManager: Can't connect to master: redis://10.0.61.135:6379 with slot ranges: [[0-5461]]
```

Not really sure why a slave with same address is getting added and removed. 
My guess is it is removing the wrong node.

*Redis version*
4.0.10

*Redisson version*
3.12.x;

*Redisson configuration*
```
        String redisUrl = ResourceConfig.REDIS_CLUSTER_CONFIG_MAP.get(domain);
        Config config = new Config();
        config.setCodec(new JsonJacksonCodec(objectMapper));
        config.useClusterServers()
                .addNodeAddress(redisUrl)
                .setTimeout(100)
                .setRetryAttempts(2)
                .setRetryInterval(50)
                .setConnectTimeout(5000);
        return Redisson.create(config);  
```

**Comment by mrniko** [comment]
Can you set logging level to `debug` for `org.redisson` package and share output?

**Comment by UditManiyar** [comment]
The problem is node failure does not happen in every maintenance window. And AWS does not give a way to simulate failover scenario when there are no replica nodes. So I am kind of stuck here.

I will set the logging level to debug but since failover is a chance based event it may take some time for me to get back with the debug output.

Meanwhile I want to understand if anyone has faced this issue previously or if you can find some meaningful insight from the INFO logs ?

**Comment by mrniko** [comment]
I think you need to set `readMode = ReadMode.MASTER` if you don't have any slaves.

**Comment by UditManiyar** [comment]
```
readMode
Default value: SLAVE

Set node type used for read operation. Available values:
SLAVE - Read from slave nodes, uses MASTER if no SLAVES are available.
MASTER - Read from master node,
MASTER_SLAVE - Read from master and slave nodes
```

In SLAVE mode it uses MASTER in case of no SLAVES right?

**Comment by mrniko** [comment]
Yes. Just want to check if the cause in this mode handling.

**Comment by mrniko** [comment]
Here is an example:

```yaml
  redisson: 
    config: |
      sentinelServersConfig:
        checkSentinelsList: false
      threads: 16
      nettyThreads: 32
```
