### ISSUE TITLE
Connection leak while using Redis-Redisson 3.13.6?

### ISSUE THREAD

**Issue by allentofight** [redisson/redisson#3249]
I use Redisson 3.13.6, and connect to redis 5.0

 when started, the connection number is constantly increasing, all connections are established, like the following:

<img width="704" alt="WeChatd990981171276654253682cc0fbcdd92" src="https://user-images.githubusercontent.com/1235483/100614466-26210d80-3351-11eb-9cce-8da5db824a40.png">

the connection number is increasing from dozens to thousands, https://github.com/redisson/redisson/issues/2771 tell us fixed,but  I suspect connection leasing is still exist

this is my redissonconfig

```java
@Bean
public RedissonClient redissonClient(){


        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers();

        clusterServersConfig.addNodeAddress("xxx");
        
        config.setCodec(new StringCodec());

        clusterServersConfig.setPassword("123456");
        clusterServersConfig.setConnectTimeout(2000);
        clusterServersConfig.setTimeout(2000);

        clusterServersConfig.setMasterConnectionPoolSize(5);
        clusterServersConfig.setMasterConnectionMinimumIdleSize(1);
        clusterServersConfig.setSlaveConnectionPoolSize(5);
        clusterServersConfig.setSlaveConnectionMinimumIdleSize(1);
        return Redisson.create(config);
}
```

**Comment by mrniko** [comment]
is there any code to reproduce it?

**Comment by allentofight** [comment]
> is there any code to reproduce it? do you use ssl connection?

we don't use ssl, maybe code to reproduce it is not that easy, it's show in our production environment, we must extract the demo code

**Comment by mrniko** [comment]
Do you see any exceptions in logs?

**Comment by allentofight** [comment]
> Do you see any exceptions in logs?

No, redisson works well,but connection number always increasing

**Comment by mrniko** [comment]
Unable to reproduce it using follow code:

```java
        Config config = new Config();
        config.setCodec(StringCodec.INSTANCE);
        config.useClusterServers()
        .setConnectTimeout(2000)
        .setTimeout(2000)
        .setMasterConnectionPoolSize(5)
        .setMasterConnectionMinimumIdleSize(1)
        .setSlaveConnectionPoolSize(5)
        .setSlaveConnectionMinimumIdleSize(1)
        .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);

        ExecutorService e = Executors.newFixedThreadPool(16);
        e.submit(() -> {
            for (int i = 0; i < 2000000; i++) {
                redisson.getBucket("i" + i).get();
                redisson.getBucket("i" + i).set("");
                redisson.getTopic("topic").publish("testmsg");
            }
        });
        e.shutdown();
        assertThat(e.awaitTermination(10000, TimeUnit.SECONDS)).isTrue();
```

**Comment by mrniko** [comment]
Please try attached version

[redisson-3.14.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5665163/redisson-3.14.1-SNAPSHOT.jar.zip)
