### ISSUE TITLE
Shared session between Tomcat Session Manager and Spring Boot Redis Session

### ISSUE THREAD

**Issue by zixitix** [redisson/redisson#3250]
Hi.
In our organization, we are building a new version of our website on Spring Boot and we are using Redis for session storage via spring session data redis. In our old application, session is stored in tomcat memory. As for now, we are trying make to the application share session data, by updating our old website with Tomcat Session Manager, but we are having an issue with synchronizing data and session expiration strategies and session data.
Spring Session
![image](https://user-images.githubusercontent.com/47761570/100723770-c54b1100-33f4-11eb-9ab9-d73f4243ca70.png)
![image](https://user-images.githubusercontent.com/47761570/100724001-fb889080-33f4-11eb-8906-d1614390f3c6.png)

Tomcat Session Manager
![image](https://user-images.githubusercontent.com/47761570/100723893-e0b61c00-33f4-11eb-85a9-d41c8960907a.png)
![image](https://user-images.githubusercontent.com/47761570/100723959-f0356500-33f4-11eb-9643-f79060cf8be5.png)

Is there any way to synchronize the way, how these modules work with sessions other than writing implementation or put spring boot application in nonembedded mode?

**Comment by mrniko** [comment]
Data format used by Tomcat Session Manager isn't compatible with Spring Session manager.
