### ISSUE TITLE
Problem to deserialize object with jackson

### ISSUE THREAD

**Issue by ArtjomProzorov** [redisson/redisson#3252]
Hey guys could you tell me what i am doing wrong here

I have an interface and it has many different implementations, so for example there is a call create account it should return CreateAccountResponse or any other interface realisation 

   
Could not execute the callcom.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.opngo.nowos.nowos.api.response.DataResponse]: missing type id property 'operation' (for POJO property 'response')
     at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 180] (through reference chain: com.opngo.nowos.nowos.NowOSResponse["response"])
```

Here is my Interface 

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "operation")
    @JsonSubTypes({@JsonSubTypes.Type(value = AuthResponse.class, name = "account_auth")})
    public interface DataResponse {
        ///
    }

Here is one of the response objects that implements the interface mentioned above

   ```
 @RequiredArgsConstructor
    public class AuthResponse implements DataResponse {
    
        @JsonProperty
        private final String accountID;
        @JsonProperty
        private final String authToken;
        @JsonProperty
        private final String language;
    }

Here is main Response that have that interface that should bring correct response object 

public class NowOSResponse {
    
        @JsonProperty
        private final String operation;
        @JsonProperty
        private final String version;
        @JsonProperty
        private final DataResponse response;
        @JsonProperty
        private final String status;
    
    }

And finally just wanted to mention that the goal of such approach and receiving different responses for each call is to test their properties, so i am casting interface to the correct class depending on the call 

 @Test
        void shouldAuthorizeAccount(){
            NowOSResponse response = accountApi.authorizeAccount(new AccountAuth());
            AuthResponse authResponse = (AuthResponse) response.getResponse();
            commonResponseAssertions(response, ACCOUNT_AUTH.getLabel());
            assertFalse(authResponse.getAuthToken().isEmpty());
        }

**Comment by mrniko** [comment]
you need to remove type id field in this case by overriding `org.redisson.codec.JsonJacksonCodec#initTypeInclusion` method.
