### ISSUE TITLE
RedissonLock.evalWriteAsync   did not resolve  WAIT command  result

### ISSUE THREAD

**Issue by qianweichenting** [redisson/redisson#3253]
There is no judgment whether Eval instruction propagates to slave library
没有判断EVAL指令是否传播到从库，也没有等待指令传播到从库。

branch master
RedissonLock.java  Line 349
![image](https://user-images.githubusercontent.com/16182404/100843129-dce9ce80-34b4-11eb-955a-a28b75610db1.png)

**Comment by mrniko** [comment]
which Redis do you use?

**Comment by qianweichenting** [comment]
> which Redis version do you use?

master branch

**Comment by mrniko** [comment]
Sorry, I mean **Redis** version

**Comment by qianweichenting** [comment]
redis-5.0.7

**Comment by qianweichenting** [comment]
> Sorry, I mean **Redis** version

redis-5.0.7.

**Comment by mrniko** [comment]
WAIT command supported in this version

**Comment by qianweichenting** [comment]
how to use the rlock  to  replace the  redlock,  Would you mind show me the config example。

I find this method   " Long ttl = tryAcquire(-1, leaseTime, unit, threadId);"  has not judge the result of wait command or  wait for the return of wait command.
![image](https://user-images.githubusercontent.com/16182404/101112328-01aa8700-3618-11eb-969d-801be530b17c.png)

this is my test case,   the master redis has no slaves  and the command  WAIT 1  1000  will block one second and return zero .
but it got lock in less than one second.

    @Test
    public  void test1() {
        Config config1 = new Config();
        config1.useMasterSlaveServers()
                .setPassword("xx")
                .setConnectTimeout(5000)
                .setTimeout(5000)
                .setRetryAttempts(3)
                .setRetryInterval(300)
                .setClientName("1")
                .setMasterAddress("redis://" + "xxx")
                .setSlaveAddresses(Sets.newHashSet("redis://" + "xxx"));
        RedissonClient redissonClient = Redisson.create(config1);

        RLock lock = redissonClient.getLock("lock1");
        log.info("start lock");
        lock.lock();
        log.info("got lock");
        lock.unlock();
        log.info("release lock");
        redissonClient.shutdown();
    }
log:
2020.12.04 10:16:06.229 INFO  MasterPubSubConnectionPool : 1 connections initialized for /47.104.234.39:6379
2020.12.04 10:16:06.403 INFO  MasterConnectionPool : 24 connections initialized for /47.104.234.39:6379
2020.12.04 10:16:06.504 INFO  PubSubConnectionPool : 1 connections initialized for /47.104.234.39:6379
2020.12.04 10:16:06.664 INFO  SlaveConnectionPool : 24 connections initialized for /47.104.234.39:6379
2020.12.04 10:16:06.743 INFO  LockTest : start lock
2020.12.04 10:16:06.784 INFO  LockTest : got lock
2020.12.04 10:16:06.808 INFO  LockTest : release lock

**Comment by mrniko** [comment]
> but it got lock in less than one second.

Because master doesn't have slaves as you noticed.

**Comment by qianweichenting** [comment]
> > but it got lock in less than one second.
> 
> Because master doesn't have slaves as you noticed.

![image](https://user-images.githubusercontent.com/16182404/101139654-d2623d00-364c-11eb-8854-bd9cea6796eb.png)

the future result of the picture is only the EVAL command.   
it should listen for the batch result like this.   


    protected <T> RFuture<T> evalWriteAsync(String key, Codec codec, RedisCommand<T> evalCommandType, String script, List<Object> keys, Object... params) {
        CommandBatchService executorService = createCommandBatchService();
        RFuture<T> result = executorService.evalWriteAsync(key, codec, evalCommandType, script, keys, params);
        if (!(commandExecutor instanceof CommandBatchService)) {
            RPromise<T> promise = new RedissonPromise<>();
            RFuture<BatchResult<?>> resFuture = executorService.executeAsync();
            resFuture.onComplete((res, e) -> {
                if (e == null) {
                    List<?> responses = res.getResponses();
                    Object o = responses.get(0);
                    promise.trySuccess((T) o);
                } else {
                    promise.tryFailure(e);
                }
            });
            return promise;
        }
        return result;
    }

**Comment by qianweichenting** [comment]
> > but it got lock in less than one second.
> 
> Because master doesn't have slaves as you noticed.

i use wireshark to trace the tcp request,   i find  the EVAL and WAIT COMMAND send in one packet as pipeline.
but the result of eval and wait command received in two packets. since i didnot really set slave，so the client receive
result of wait command  in one second.  the result of executorService.evalWriteAsync is just EVAL result and didnot
wait the all command propagate to the slave

**Comment by mrniko** [comment]
Fixed! Thanks for report
