### ISSUE TITLE
RedissonFairLock.tryLock returns with false after timeout even when lock has been released

### ISSUE THREAD

**Issue by bhavyakv** [redisson/redisson#3254]
We use RedissonFairLock in our application to synchronize across multiple threads. Whenever there are several simultaneous lock attempts on the same lock, one or more of the waiting threads always errors out with tryLock returning false after the `waitTime` configured, which is almost 5 mins, even though I can clearly see that the other threads that were holding the lock have long since released it.
Is there a known issues with RedissonFairLock? Also, would switching to a non-fair lock help (we don't really need fairness guarantees)? 

Code used to obtain lock - 
```
  RLock lock = redissonClient.getFairLock(id);
  // This tells us if lock is being held by another thread
  logRedisLockMetrics(lock, id, eventType);

  if (lock.tryLock(300, 300, TimeUnit.SECONDS)) {
        log.info("[RedisSync%s] Obtained lock for id=%q", eventType, lock.getName());
        return lock;
   } else {
      // failure
   } 
```

Redisson version being used is **v3.13.6**

**Comment by mrniko** [comment]
Fair lock maintains order of waiting threads, and non-fair lock doesn't.
This issue might happen if one of waiting threads was terminated.

**Comment by bhavyakv** [comment]
In this case, all the other threads did complete successfully, without any abrupt termination.

Is there a way to check that the `lock.unlock()` call actually succeeded? I do have Debug logs enabled on Redisson, but didn't find any log to verify this.

**Comment by mrniko** [comment]
it's script starts with `if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then...`

**Comment by bhavyakv** [comment]
@mrniko I don't see the above in logs. Also, we moved away from a FairLock, and we're still seeing the above issue. Any suggestions on what else we could try/debug?

**Comment by mrniko** [comment]
check your code, `lock.unlock()` always executes script above.

**Comment by viren1990** [comment]
@bhavyakv  @mrniko - Struggling with same issue . Somehow while testing on local, does not face however in redis-clustered env. can't figure what could possibly be causing it.
