### ISSUE TITLE
Redisson Multiget - Getting multiple key values in single call form Redisson

### ISSUE THREAD

**Issue by satishbhuria** [redisson/redisson#3255]
I have a redis cache where each key is of type list and from redisson i want to make a map of each list key and their size...

Below code is working fine but I want to make single call to redis cache.

Iterable<String> keys = redissonClient.getKeys().getKeysByPattern(keyPattern);

    Map<String, Integer> map = new HashMap<>();
    for (String key : keys) {
        map.put(key, redissonClient.getList(key).size());
    }
    return map;
}

I don't want to make a call to cache multiple time. Below code should be changed to single call

 ```
for (String key : keys) {
        map.put(key, redissonClient.getList(key).size());
 }
```

Thanks in advance

**Comment by mrniko** [comment]
Use RBatch object - `redisson.createBatch();`

**Comment by satishbhuria** [comment]
Do u have any example where it is being used ?

**Comment by satishbhuria** [comment]
or can i used RedissonBuckets.get(String... keys) which will give me Mget functionality?

**Comment by mrniko** [comment]
yes, this method uses mget Redis command

**Comment by satishbhuria** [comment]
I have written below code and it is not retrieving the Map<String , V> 

`Iterable<String> keys = redissonClient.getKeys().getKeysByPattern(keyPattern);

        String[] cach = StreamSupport.stream(keys.spliterator(), false).toArray(String[]::new);
        RBuckets redissonBuckets = redissonClient.getBuckets();

        Map<String, List<Company>> stringListMap = redissonBuckets.get(cach);

        stringListMap.entrySet().stream().forEach(e ->
                System.out.println("Key : " + e.getKey() + " value : " + e.getValue().size())
        );

        return redissonBuckets.get(cach);`

**Comment by mrniko** [comment]
Here is my test which works:

```java
        redisson.getBucket("test1").set("someValue1");
        redisson.getBucket("test3").set("someValue3");

        Map<String, String> result = redisson.getBuckets().get("test1", "test3");
        Map<String, String> expected = new HashMap<String, String>();
        expected.put("test1", "someValue1");
        expected.put("test3", "someValue3");
```

**Comment by satishbhuria** [comment]
I tried and still not getting it... the main difference is the type of data which I need to query is list not a string... so might be because of that i am not able to get that

**Comment by satishbhuria** [comment]
Hi I have tested again and got **UnsupportedOperationException** Below is the screen shot

![Screen Shot 2020-12-07 at 2 37 19 PM](https://user-images.githubusercontent.com/14160989/101331631-45acbe80-389a-11eb-9faf-2508814b0a94.png)

**Comment by mrniko** [comment]
Which method throws it? could you share code example to reproduce the issue?

**Comment by satishbhuria** [comment]
`Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379");

        RedissonClient client = Redisson.create(config);

        String pattern = "TEST-*-AVAILABLE";

        Iterable<String> keys = client.getKeys().getKeysByPattern(pattern);

        String[] cache = StreamSupport.stream(keys.spliterator(), false).toArray(String[]::new);

        RFuture<Map<String, String>> stringListMap = null;
        try {
            RBuckets rBuckets = client.getBuckets(JsonJacksonCodec.INSTANCE);

            stringListMap = rBuckets.getAsync(Arrays.toString(cache));
        } catch (Exception e) {
            System.out.println("exception occurred");
            System.out.println(e.getMessage());
        }
        System.out.println("execution completed" + stringListMap.getNow());
    }`

**Comment by satishbhuria** [comment]
any updates on above query ?

**Comment by mrniko** [comment]
Unable to reproduce the error using your code

**Comment by satishbhuria** [comment]
is it working for you ?

**Comment by mrniko** [comment]
yes, Redisson version is 3.14.0

**Comment by satishbhuria** [comment]
whatever the keys I am getting from cache after calling this `    Iterable<String> keys = client.getKeys().getKeysByPattern(pattern);
` is a list not a string that might be the issue ?

**Comment by mrniko** [comment]
No, but you can't read RList through RBucket.

**Comment by satishbhuria** [comment]
so any other solution, that I can use in this case.

**Comment by satishbhuria** [comment]
@mrniko Any alternative to fix this issue ? let me know

**Comment by mrniko** [comment]
> whatever the keys I am getting from cache after calling this Iterable<String> keys = client.getKeys().getKeysByPattern(pattern); is a list not a string that might be the issue ?

You can get any type of keys by this code line. But use RList instead RBuckets object if it's a list type.
