### ISSUE TITLE
RPatternTopicReactive.removeListener() not working

### ISSUE THREAD

**Issue by ooga** [redisson/redisson#3258]
**Expected behavior**

After calling `removeListener` with reactive client, we shouldn't trigger the listener anymore

**Actual behavior**

Listener is triggered after calling `removeListener` with reactive client

**Steps to reproduce or test case**

```
@Test
public void testReactiveUnsubscribe() throws InterruptedException {
    final CountDownLatch messageReceived = new CountDownLatch(1);

    final RedissonReactiveClient redisson = Redisson.createReactive(createConfig());
    RPatternTopicReactive topic1 = redisson.getPatternTopic("topic1.*");

    topic1.addListener(Message.class, (pattern, channel, msg) -> {
        Assert.fail();
    }).subscribe(topic1::removeListener);

    topic1.addListener(Message.class, (pattern, channel, msg) -> {
        Assert.assertTrue(pattern.equals("topic1.*"));
        Assert.assertTrue(channel.equals("topic1.t3"));
        Assert.assertEquals(new Message("123"), msg);
        messageReceived.countDown();
    }).subscribe();

    redisson.getTopic("topic1.t3").publish(new Message("123")).subscribe();

    Assert.assertTrue(messageReceived.await(5, TimeUnit.SECONDS));
}
```

**Redis version**
6.0.9

**Redisson version**
3.14.0

**Comment by ooga** [comment]
Not really sure of this solution but I suggest it anyway

In `ReactiveProxyBuilder` shouldn't we auto subscribe if we don't return anything ?

```
Mono<Object> mono = commandExecutor.reactive(...)

if (instanceMethod.getReturnType().equals(Void.TYPE)) {
    return mono.subscribe();
}

return mono;
```

**Comment by ooga** [comment]
⚠️  By doing what I suggest just before we will mask any errors that could occurs

I think the best approach will be to always return a Mono to let the user handling subscription and errors.

This will be a breaking changes for the Reactive API but for now it doesn't work so I'm pretty sure anyone use the impacted methods.

**Comment by mrniko** [comment]
Fixed! Thanks for report
