### ISSUE TITLE
ClassCastException when trying to get count of elements within a range in sorted set for rxjava2

### ISSUE THREAD

**Issue by arun-aswathanarayan** [redisson/redisson#3259]
I am getting a ClassCastException when trying to get the count of elements within the score range in a sorted set using the rxjava2 client.

code snippet:
var count = connectionManager.getRxClient().getScoredSortedSet(key).count(startScore, true, endScore, true).blockingGet();

I get the following exception on blockingGet() - java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in the module java.base of loader 'bootstrap')

redisson version - 3.13.6

**Comment by mrniko** [comment]
Fixed! Thanks for report
