### ISSUE TITLE
ClassCastException when adding elements to sorted set using rxjava2 client

### ISSUE THREAD

**Issue by arun-aswathanarayan** [redisson/redisson#3261]
I am getting a ClassCastException when trying to add multiple elements to a sorted set using the rxjava2 client.

code snippet:
var count = connectionManager.getRxClient().getScoredSortedSet(key).addAll(values).blockingGet();

I get the following exception on blockingGet() or subscribe() - java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in the module java.base of loader 'bootstrap')

redisson version - 3.13.6

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3259
