### ISSUE TITLE
Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings

### ISSUE THREAD

**Issue by tanzheng231** [redisson/redisson#3262]
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 20. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@10358000 [redisClient=[addr=redis://192.168.130.61:7001], channel=[id: 0x707b7cf8, L:/192.168.112.10:62674 - R:/192.168.130.61:7001], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2f6799(failure: org.redisson.client.RedisMovedException)], command=(EVAL), params=[ local a=redis.call('GET',KEYS[1]); local b=redis.call('GET',KEYS[2]); if(a and string.find(a,ARGV[1..., 2, {classRoom_CJTWBS1S600000001119}_ready, {classRoom_CJTWBS1S600000001119}_formal, PooledUnsafeDirectByteBuf(ridx: 0, widx: 20, cap: 256)], codec=org.redisson.client.codec.StringCodec]], command: (EVAL), params: [ local a=redis.call('GET',KEYS[1]); local b=redis.call('GET',KEYS[2]); if(a and string.find(a,ARGV[1..., 2, {classRoom_CJTWBS1S600000001119}_ready, {classRoom_CJTWBS1S600000001119}_formal, PooledUnsafeDirectByteBuf(ridx: 0, widx: 20, cap: 256)] after 3 retry attempts

Redisson version: 3.13.4

This will be the case when you visit redisson every time the project is started，nettyThreads is the default number

**Comment by mrniko** [comment]
Do you use RBatch object?

**Comment by tanzheng231** [comment]
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=30, freeConnectionsCounter=value:498:queue:0, freezeReason=null, client=[addr=redis://192.168.130.61:7006], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@2048284872 [redisClient=[addr=redis://192.168.130.61:7006], channel=[id: 0x5b59abe8, L:/192.168.133.12:54612 - R:192.168.130.61/192.168.130.61:7006], currentCommand=null], command: null, params: null after 3 retry attempts

**Comment by tanzheng231** [comment]
Payload size in bytes: 0

**Comment by tanzheng231** [comment]
yes ,I deleted it, but it still has this problem

**Comment by mrniko** [comment]
what is the error now?

**Comment by mrniko** [comment]
`currentCommand=null`

Can you share code example?
