### ISSUE TITLE
Exception "Unable to write command into connection" throwed after two weeks time running with redisson

### ISSUE THREAD

**Issue by zhuxysun** [redisson/redisson#3263]
The exception stack info is below:
Unable to write command into connection! Node source: NodeSource [slot=13580, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@41548252 [redisClient=[addr=redis://xxx.xxxx.xxx.xxx:6379], channel=[id: 0xdcc1059a, L:0.0.0.0/0.0.0.0:55134 ! R:/xxx.xxxx.xxx.xxx:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@174dc5ee(failure: java.util.concurrent.CancellationException)], command=(EVAL), params=[if redis.call('setnx', KEYS[6], ARGV[4]) == 0 then return -1;end;redis.call('expire', KEYS[6], ARGV[..., 6, task.srm.task.4353929913272631325_product04, redisson__timeout__set:{task.srm.task.4353929913272631325_product04}, redisson__idle__set:{task.srm.task.4353929913272631325_product04}, redisson_map_cache_expired:{task.srm.task.4353929913272631325_product04}, redisson__map_cache__last_access__set:{task.srm.task.4353929913272631325_product04}, redisson__execute_task_once_latch:{task.srm.task.4353929913272631325_product04}, 1606882813929, 100, ...], codec=org.redisson.client.codec.LongCodec]], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); local expireDate = 92233720368547758; if value ~..., 5, task.srm.tep.usage-v1_product04, redisson__timeout__set:{task.srm.tep.usage-v1_product04}, redisson__idle__set:{task.srm.tep.usage-v1_product04}, redisson__map_cache__last_access__set:{task.srm.tep.usage-v1_product04}, {task.srm.tep.usage-v1_product04}:redisson_options, 1606925138829, PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256)] after 3 retry attempts

We can't find the channel port 55134 in the client vm, but other channel worked normally, the redisson version is 3.11.3
I want to known how to lead the ConnectionWatchDog to check the channel in time.

**Comment by zhuxysun** [comment]
Using "netstat -anp | grep 6379", I didn't find the record using 55134. As i think, the watch dog should clear the connection and assign a usable channel.

**Comment by zhuxysun** [comment]
the redisson version is 3.13.3

**Comment by zhuxysun** [comment]
In one of the redisson client where exception happened,  it existed 600 connections while 300 connections in other normal server,  so I suspect if the connection pool size is too big to beyond the ability of WatchDog.

**Comment by zhuxysun** [comment]
no answer

**Comment by mrniko** [comment]
Can you recheck it with version attached? https://github.com/redisson/redisson/issues/3249#issuecomment-741676980

**Comment by zhuxysun** [comment]
Thanks, I'll send result here later.
