### ISSUE TITLE
Redisson used disconnected channel to write data

### ISSUE THREAD

**Issue by zhuxysun** [redisson/redisson#3267]
My redisson version is 3.13.3, and the configuration is :
{
    "clusterServersConfig": {
        "idleConnectionTimeout": 10000,
        "connectTimeout": 10000,
        "timeout": 3000,
        "retryAttempts": 3,
        "retryInterval": 1500,
        "password": "The password",
        "subscriptionsPerConnection": 5,
        "sslEnableEndpointIdentification": true,
        "sslProvider": "JDK",
        "pingConnectionInterval": 0,
        "keepAlive": true,
        "tcpNoDelay": true,
        "loadBalancer": {
            "class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
        },
        "failedSlaveReconnectionInterval": 3000,
        "failedSlaveCheckInterval": 180000,
        **"masterConnectionMinimumIdleSize": 5,
        "masterConnectionPoolSize": 50,**
        "readMode": "MASTER_SLAVE",
        "subscriptionMode": "MASTER",
        "subscriptionConnectionMinimumIdleSize": 1,
        "subscriptionConnectionPoolSize": 50,
        "dnsMonitoringInterval": 5000,
        "natMap": {},
        "nodeAddresses": [
            "redis://xx.xx.xx.xx:6379",
            "redis://xx.xx.xx.xx:6379"
        ],
        "scanInterval": 5000,
        "checkSlotsCoverage": true
    },
    "threads": 16,
    "nettyThreads": 128,
    "codec": {
        "class": "org.redisson.codec.MsgPackJacksonCodec"
    },
    "referenceEnabled": true,
    "transportMode": "NIO",
    "lockWatchdogTimeout": 30000,
    "keepPubSubOrder": true,
    "decodeInExecutor": false,
    "useScriptCache": false,
    "minCleanUpDelay": 5,
    "maxCleanUpDelay": 1800,
    "addressResolverGroupFactory": {
        "class": "org.redisson.connection.DnsAddressResolverGroupFactory"
    }
}
**The slaveConnectionMinimumIdleSize use default value.**

After a two weeks time running, an exception "**Unable to write command into connection**" thrown
The stack info is:
Unable to write command into connection! Node source: NodeSource [slot=13580, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@41548252 [redisClient=[addr=redis://xxx.xxxx.xxx.xxx:6379], channel=[id: 0xdcc1059a, L:0.0.0.0/0.0.0.0:55134 ! R:/xxx.xxxx.xxx.xxx:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@174dc5ee(failure: java.util.concurrent.CancellationException)], command=(EVAL), params=[if redis.call('setnx', KEYS[6], ARGV[4]) == 0 then return -1;end;redis.call('expire', KEYS[6], ARGV[..., 6, task.srm.task.4353929913272631325_product04, redisson__timeout__set:{task.srm.task.4353929913272631325_product04}, redisson__idle__set:{task.srm.task.4353929913272631325_product04}, redisson_map_cache_expired:{task.srm.task.4353929913272631325_product04}, redisson__map_cache__last_access__set:{task.srm.task.4353929913272631325_product04}, redisson__execute_task_once_latch:{task.srm.task.4353929913272631325_product04}, 1606882813929, 100, ...], codec=org.redisson.client.codec.LongCodec]], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); local expireDate = 92233720368547758; if value ~..., 5, task.srm.tep.usage-v1_product04, redisson__timeout__set:{task.srm.tep.usage-v1_product04}, redisson__idle__set:{task.srm.tep.usage-v1_product04}, redisson__map_cache__last_access__set:{task.srm.tep.usage-v1_product04}, {task.srm.tep.usage-v1_product04}:redisson_options, 1606925138829, PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256)] after 3 retry attempts

**We can't find the port 55134 in the client channel**,  why Redisson used the disconnected channel to send data?

**Comment by mrniko** [comment]
Did you check your network?

**Comment by zhuxysun** [comment]
yes，checked by wireshark, no pack lost.

**Comment by mrniko** [comment]
Set `pingConnectionInterval`, so all dead connections will be reconnected
