### ISSUE TITLE
sentinel模式,slave节点重启,连接泄漏

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#3270]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
4
**Redisson version**
3.13.3
**Redisson configuration**

sentinel模式, redis slave节点重启, 从节点进行同步(“LOADING Redis is loading the dataset in memory”), 直到这个节点可用后,发现很多连接泄漏(netstat统计大于这个Ip对应的ClientConnectionsEntry中的allconnections数量,证明有部分连接不在allconnections中),经查,是由于watchdog中重连的代码存在问题导致连接泄漏

**Comment by mrniko** [comment]
can you try this version? https://github.com/redisson/redisson/issues/3249#issuecomment-741676980

**Comment by mikawudi** [comment]
使用master分支最新代码编译了3.14.1-SNAPSHOT,经测试,问题依旧
<img width="1054" alt="p1" src="https://user-images.githubusercontent.com/8215006/101735558-0c27bd80-3afd-11eb-9c72-8df5a040f7a5.png">
![p2](https://user-images.githubusercontent.com/8215006/101735578-10ec7180-3afd-11eb-9fec-1ba5341c0665.png)
可以看下我的PR,经过测试应该解决了这个连接泄漏.
主要问题出现在
1) watchDog重连后,旧的RedisConnection已经被关闭,这时并没有把新创建的RedisConnection以及里面的channel关闭
2) watchDog重连后,旧的RedisConnection未被关闭,但是当新的RedisConnection走完BaseConnectionHandler里的auth,ping,select等等命令,触发connectionPromise,watchDog执行refresh之前,旧的RedisConnection被关闭,但是新的channel还是被refresh()刷进了旧的已经关闭的RedisConnection的channel中
这两个问题导致上图中的,实际连接数>allConnections.size的情况,在redis从节点有几个G的数据,启动的时候需要主从同步个10几秒(Loading Redis .....)的情况下,重启slave节点可以复现(一次不行就多重启几次,概率还是比较高的)
目前测试到应该是这两个问题,并作出修复.

但是我们这边线上环境还出现过ClientConnectionsEntry.freeConnectionsCounter暴增的情况(到过几千)的问题,但是这个我们无法复现,没能定位到问题

**Comment by mikawudi** [comment]
这里还有一个问题,slave的配置是setSlaveConnectionPoolSize(64),但是在重连的时候都是78个连接,在最新的master上能复现,原因大致定位到了,是因为ConnectionPool中initConnections()是按照Math.min(10, minimumIdleSize);进行初始化,后续的14个在前面的连接complite的时候再发起,但是由于“LOADING Redis is loading the dataset in memory”,这前10个连接卡了10几秒,但是在initConnections完全成功之前就已经把ClientConnectionsEntry的freezeReason设置成null了,导致业务上已经可以在这个ClientConnectionsEntry上acquireConnection连接了,导致卡住的10几秒,剩下的56个counter都被业务取走创建连接,直到redis不再“LOADING Redis is loading the dataset in memory”的时候,64个连接都建立好,放入allconnections中,但是initConnections还没完毕,所以继续创建了14个连接,导致了连接泄漏(64+14=78).....
问题已经定位到了,正在想如何修复....修复后会提交一个pr

**Comment by mrniko** [comment]
merged!
