### ISSUE TITLE
Unable to send PING command over channel: [id: 0xcffcc397, L:/10.16.18.65:57542 ! R:/10.18.8.156:6380]

### ISSUE THREAD

**Issue by dhlsoft** [redisson/redisson#3273]
[order-center:10.16.18.65:7003]>>2020-12-07 20:32:31.073>>ERROR>>18357>>[redisson-timer-4-1]>>org.redisson.client.handler.PingConnectionHandler$1:89 -> Unable to send PING command over channel: [id: 0x09d44210, L:/10.16.18.65:57558 ! R:/10.18.8.156:6380]

io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

[order-center:10.16.18.65:7003]>>2020-12-07 20:32:31.073>>ERROR>>18357>>[redisson-timer-4-1]>>org.redisson.client.handler.PingConnectionHandler$1:89 -> Unable to send PING command over channel: [id: 0x1747256d, L:/10.16.18.65:57526 ! R:/10.18.8.156:6380]

io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

[order-center:10.16.18.65:7003]>>2020-12-07 20:32:31.073>>ERROR>>18357>>[redisson-timer-4-1]>>org.redisson.client.handler.PingConnectionHandler$1:89 -> Unable to send PING command over channel: [id: 0x35b04a5a, L:/10.16.18.65:57540 ! R:/10.18.8.156:6380]

io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

**Comment by dhlsoft** [comment]
using 3.14.0

**Comment by mrniko** [comment]
StacklessClosedChannelException - channel is closed

**Comment by dhlsoft** [comment]
> StacklessClosedChannelException - channel is closed

How avoid this problem ?   pingConnectionInterval: 0？

**Comment by pouyakhoshkhoo** [comment]
I've got the same problem. By changing pingConnectionInterval to 10 seconds the error will be solved. I wonder why this error happens in the first place.

**Comment by mrniko** [comment]
define pingConnectionInterval > 0

**Comment by danielgatis-mb** [comment]
Same here using 3.14.1. Why this error happens?

**Comment by mrniko** [comment]
@danielgatis-mb 

> Changing pingConnectionInterval to 10 seconds will resolve the error

Did you try to set it to 10 ?

**Comment by wedtlcy** [comment]
一定要将其设置为 10 ？我设置15还是有这个错

**Comment by zhengquan45** [comment]
Why set it 10 seconds，can work？

**Comment by shiranyosef1** [comment]
`pingConnectionInterval` already set for me to 1000, why is it still happening?

**Comment by mrniko** [comment]
@shiranyosef1 

the root cause is StacklessClosedChannelException - channel is closed. You need to check your network.

**Comment by shiranyosef1** [comment]
@mrniko The network seems ok, we are working with AWS Elasticache. Is that common?
how would you suggest debugging this?
