### ISSUE TITLE
Support TTL for RBuckets.set

### ISSUE THREAD

**Issue by kpadmasola** [redisson/redisson#3274]
Currently `RBucket` supports set with TTL https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/RBucket.java#L134

This is a request for similar support in `RBuckets` for setting multiple key values with specified TTL.

Possible api signature:
```
 void set(Map<String, ?> buckets, long timeToLive, TimeUnit timeUnit);
```
thank you.

**Comment by mrniko** [comment]
Please use `RBatch` object for this purpose.
