### ISSUE TITLE
Can I get and update an object in an RBatch operation?

### ISSUE THREAD

**Issue by steveyegge** [redisson/redisson#3275]
Apologies if this has been asked before, or if this is the wrong forum for this kind of question.

I'd like to update the timestamp field of a java object in an RBucket, keeping the object's other fields as-is.

Can I do this in the context of an RBatch?  It's not super clear from the documentation I've found - I can't tell whether batching only supports pipelining a bunch of writes, or if it can do reads and then writes based on the results of those reads in a single batch operation.

pseudocode for what I'm trying to do:

val batch = redis.client.createBatch()
val bucket = batch.getBucket<MyStruct>(mykey)
val struct = bucket.async.get() ?: createMyStruct(params)
struct.lastUpdated = System.currentTimeMillis()
bucket.setAsync(struct)
if (expireKeys) bucket.expireAsync(24, TimeUnit.HOURS)
batch.executeAsync()

I'm not sure if the batch will wait for the result of the read before updating it and performing the write.

If this isn't the right way to do it, should I just perform a synchronous get followed by an async update?  Thank you.

**Comment by mrniko** [comment]
RBatch can do both read and writes but it's impossible to execute operation depending on read result in the same batch.
