### ISSUE TITLE
Does RLocalCachedMap get invalidated with the changes in Redis-Server ?

### ISSUE THREAD

**Issue by rreddy13Official** [redisson/redisson#3277]
Hi,

My use case:
I have a single node application(**MyApplication**) which uses RLocalCachedMap (say **_testMap_**)to communicate with redis-server and also cache data locally in aplication.
On the other hand there is another Non java application say **anotherApplication**(which we have no control of) will update the data in redis-server on same map testMap.
In which case, does RLocalCachedMap in  MyApplication will invalidate the local cache entries when there is change in redis server ?

```
LocalCachedMapOptions<String, String> options = LocalCachedMapOptions.<String, String>defaults()
                .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.LRU)
                .syncStrategy(LocalCachedMapOptions.SyncStrategy.INVALIDATE)
                .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.CLEAR)
                .storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE_REDIS)
                .cacheSize(1000)
                .cacheProvider(LocalCachedMapOptions.CacheProvider.REDISSON);
```

If not, how would you suggest to implement Redis Server assisted client side caching (https://redis.io/topics/client-side-caching)? 
Is there a way that i can use listen to redis-server invalidation events and keep the local cache in sync with redis-server data (with or without RLocalCachedMap as Its not mandate for use to use RLocalCahedMap). ?
Please suggest.

**Comment by linarin** [comment]
not, RLocalCachedMap sync invalidate msg by redis pubsub topic:  {<map name>}:topic
invalidate msg is: org.redisson.cache.LocalCachedMapInvalidate, which contains invalidated hash keys.
see org.redisson.cache.LocalCacheListener
