### ISSUE TITLE
Does a redisson retry attempt invoke the load balancer again?

### ISSUE THREAD

**Issue by deepak-auto** [redisson/redisson#3278]
Given one master node and multiple replica nodes with Sentinels enabled, Redisson configured to read from replica nodes only, and round robin load balancer and retries enabled. In case of a Redisson retry attempt, does it invoke the load balancer again to determine a new replica node or does it talk to the same replica that it had unsuccessfully communicated with before?

Our use case is such that we see are witnessing a 50% drop in commands processed per second when a single replica node restarts. We have retries enabled in Redisson but they don't seem to be helping so we are wondering if the retries also go to the same failing node.

Redisson version: 3.13.6 Redis version: 5.0.6

The contributing guidelines dont really say anything about where to ask questions so I also created a SO question: https://stackoverflow.com/questions/65223782/does-a-redisson-retry-attempt-invoke-the-load-balancer-again

**Comment by mrniko** [comment]
> does it invoke the load balancer again to determine a new replica node or does it talk to the same replica that it had unsuccessfully communicated with before?

In each attempt it uses load balancer.
