### ISSUE TITLE
After immediate put call get method returned null

### ISSUE THREAD

**Issue by ankitsingh95** [redisson/redisson#3280]
We are using Rmap/RadissonMap , and use fastPut method to put key in cache and immediately after this method call ,Call get method and that return some time null and some time working fine please suggest solution for this issue.

My redis is in master-slave architecture with sentinel.
Redisson client configure as sentinel configurations so my understanding all the put should used master node of redis and all get should use slaves.

Total request=5371
Null return=155
value return=5216

**Comment by mrniko** [comment]
this happens due to sync lag between master and slave. Try to use readMode = MASTER or speedup your Redis/Network.

**Comment by ankitsingh95** [comment]
Any put method available that return sync status between master and slave
