### ISSUE TITLE
redission remote service does not support java8 class Optional serialization

### ISSUE THREAD

**Issue by tnessn** [redisson/redisson#3282]
redission remote service does not support java8 class Optional serialization
![image](https://user-images.githubusercontent.com/5991683/101736906-11860780-3aff-11eb-93a0-2d299c05ba21.png)

**Comment by tnessn** [comment]
I have solved the problem, the document is wrong, the default is not json-codec
![image](https://user-images.githubusercontent.com/5991683/102345138-db052c80-3fd7-11eb-9c89-cdc31ca7a03c.png)

**Comment by mrniko** [comment]
Fixed

**Comment by mrniko** [comment]
@tnessn javadocs were fixed
