### ISSUE TITLE
Command execution timeout for command: (SENTINEL SENTINELS)

### ISSUE THREAD

**Issue by hskycloud** [redisson/redisson#3283]
**Expected behavior**

**Actual behavior**
```
2020-12-10 21:24:49.614 ERROR 12300 --- [isson-timer-4-1] o.r.c.SentinelConnectionManager          : Can't execute SENTINEL commands on /192.168.1.101:26379

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (SENTINEL SENTINELS), params: [mymaster], Redis client: [addr=redis://192.168.1.101:26379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.14.0.jar:3.14.0]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

**Steps to reproduce or test case**
项目启动之后报错
Spring boot version 2.2.0.RELEASE

**Redis version 5.0.5**

**Redisson version 3.13.6跟3.14.0**

**Redisson configuration**
```
sentinelServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 5000
  retryAttempts: 3
  retryInterval: 3000
  subscriptionsPerConnection: 1
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 5
  slaveConnectionPoolSize: 10
  masterConnectionMinimumIdleSize: 5
  masterConnectionPoolSize: 10
  readMode: "SLAVE"
  sentinelAddresses:
    - "redis://192.168.1.100:26379"
    - "redis://192.168.1.101:26379"
    - "redis://192.168.1.102:26379"
  masterName: "mymaster"
  password: "xxx"
  database: 0
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
```

**Comment by luffy51k** [comment]
same problem.

**Comment by mrniko** [comment]
Please check network

**Comment by mrniko** [comment]
When does it happen?

**Comment by 1329544856** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/48055215/102961474-59edee00-451f-11eb-84fa-0e23df0c8545.png)
![image](https://user-images.githubusercontent.com/48055215/102961515-72f69f00-451f-11eb-9e8e-85c24adff213.png)

**Comment by 1329544856** [comment]
I have the same problem.
Spring boot version 2.1.6.RELEASE
Redis version 5.0.3
![image](https://user-images.githubusercontent.com/48055215/102961621-b8b36780-451f-11eb-8a89-a34e33a81a92.png)
![image](https://user-images.githubusercontent.com/48055215/102961578-9cafc600-451f-11eb-88ab-66e84e786cb7.png)
![image](https://user-images.githubusercontent.com/48055215/102961590-a3d6d400-451f-11eb-8c23-e0d6e2520c9f.png)

**Comment by 1329544856** [comment]
![image](https://user-images.githubusercontent.com/48055215/102961726-03cd7a80-4520-11eb-9cdb-8ebaa791125e.png)
My network can connect and I use the under maven by create bean can connect successfully. 
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson</artifactId>
    <version>3.5.0</version>
</dependency>

**Comment by heliang25145** [comment]
I have the same problem.
spring boot version 2.0.3.RELEASE
redis_version:5.0.5
redisson version 3.10.1

**Comment by mrniko** [comment]
Unable to reproduce it

**Comment by zdtdtel** [comment]
> I have the same problem.
> Spring boot version 2.1.6.RELEASE
> Redis version 5.0.3
> ![image](https://user-images.githubusercontent.com/48055215/102961621-b8b36780-451f-11eb-8a89-a34e33a81a92.png)
> ![image](https://user-images.githubusercontent.com/48055215/102961578-9cafc600-451f-11eb-88ab-66e84e786cb7.png)
> ![image](https://user-images.githubusercontent.com/48055215/102961590-a3d6d400-451f-11eb-8c23-e0d6e2520c9f.png)

Lower the version, user 3.11.2, 3.12.5

**Comment by mrniko** [comment]
@zdtdtel 

Can you clarify which latest version works for you?

**Comment by zdtdtel** [comment]
@mrniko 
I don't know which one is more suitable for my project. Running is no problem.
My project structure:
SpringBoot 2.3.1.RELEASE
dubbo-spring-boot-starter 2.7.8
redisson-spring-boot-starter 3.12.4

**Comment by mrniko** [comment]
unable to reproduce it with 3.14.1

**Comment by Dengyren** [comment]
I have the same problem. Have you solved it？

**Comment by zdtdtel** [comment]
@Dengyren 
Try reducing the redisson version, use redisson-spring-boot-starter 3.11.6  or  3.12.4

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3404
