### ISSUE TITLE
Using external EventLoopGroup with the Blocking API

### ISSUE THREAD

**Issue by shaharoliver** [redisson/redisson#3284]
I'm using Redisson RBLoomFilter  over Vert.x and I need to call the contains method, which is blocking (i didn't find any async option)
Is it possible to use Vert.x Netty EventLoopGroup instead of Redisson Netty threads without blocking the eventloop?
The blocking nature of the contains method blocks netty threads? or is it using a different thread pool for blocking operations?

**Comment by mrniko** [comment]
> Is it possible to use Vert.x Netty EventLoopGroup instead of Redisson Netty threads without blocking the eventloop?

It's hard to say, I have never done this.

netty threads aren't blocked by Redisson.

**Comment by shaharoliver** [comment]
> > Is it possible to use Vert.x Netty EventLoopGroup instead of Redisson Netty threads without blocking the eventloop?
> 
> It's hard to say, I have never done this.
> 
> netty threads aren't blocked by Redisson.

thanks,
it's possible with 
`        Config config = new Config();
        config.setEventLoopGroup(vertx.nettyEventLoopGroup())
`
