### ISSUE TITLE
Why does it take RLock nearly 1 second to get the lock?

### ISSUE THREAD

**Issue by popgo-mos** [redisson/redisson#3287]
There are only 10 redission client connected to the redis server, no more than 4 threads competing for the lock.
It is weird that my redis server cpu and memory usage is no more than 10%.
My redisson version is 3.12.5.
Is there any one knows the reason?

**Comment by merzMario** [comment]
Show your configurations

发自我的iPhone

**Comment by popgo-mos** [comment]
Config config = new Config();
        config.useSingleServer().setAddress(nodeAddress)
                .setPassword(password).setDatabase(database);
        config.setCodec(new FstCodec());
        redissonClient = Redisson.create(config);

**Comment by mrniko** [comment]
this happens if it waits for release by current thread.

**Comment by mrniko** [comment]
update to 3.13.1+ version
