### ISSUE TITLE
how to manual change read mode at redis cluster

### ISSUE THREAD

**Issue by poolqa** [redisson/redisson#3288]
I have some high loading action, I hope it can run at SLAVE nodes, and other action at MATER nodes.
ex：
scan key by pattern and mget value by keys at SLAVE nodes.
normal get and set at MASTER nodes
how to assign nodes when I use some high loading action？

**Comment by mrniko** [comment]
the only solution is to create two Redisson instances with shared `eventLoopGroup` and `executor` objects.
