### ISSUE TITLE
RedissonMap.isEmpty is inefficient

### ISSUE THREAD

**Issue by nanw1103** [redisson/redisson#3290]
RedissionMap.isEmpty adopts the default AbstractMap.isEmpty, which checks size()==0. RedissionMap.size() iterates all keys (even with pattern), which is inefficient with large HASH.

Suggest to override RedissonMap.isEmpty() which checks iterator().hasNext() instead.

Not sure whether this optimization applies to other RMap implementation.

Redisson version: 3.13.6

**Comment by nanw1103** [comment]
Without an enhancement, developer needs to use the following workaround:

```java
        String pattern = "mykey-*";
        int batchHint = 1;
        Set<String> keySet = monitorQueue.keySet(pattern, batchHint);

        //The Redisson implementation for "isEmpty" is very in-effective, which iterates all keys.
        //boolean isEmpty = keySet.isEmpty();

        boolean isEmpty = !keySet.iterator().hasNext();
```

**Comment by mrniko** [comment]
Please look closely `RedissonMap.size()` method doesn't iterate all entries. It uses HLEN command.

**Comment by nanw1103** [comment]
Sorry that the description is incorrect.
According to the example, it's RedissonMap.keySet(pattern, batchSizeHint).isEmpty()

**Comment by nanw1103** [comment]
Reopen as https://github.com/redisson/redisson/issues/3298
