### ISSUE TITLE
每次对redis进行读写都会打印 redisson操作的DEBUG 日志, 导致控制台输出过于频繁!

### ISSUE THREAD

**Issue by xaviershl** [redisson/redisson#3296]
[TEMP1.txt](https://github.com/redisson/redisson/files/5707473/TEMP1.txt)
如文件所示 

请问 类似于
20-12-17 14:48:33 DEBUG org.redisson.command.CommandAsyncService - acquired connection for command (EXISTS) and params [APIKEY_sun727_USERNAME_pc_432699d91c614c89bef3f9b193cc3a25_securityLogin] from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]] using node localhost/127.0.0.1:6379... RedisConnection@639223878 [redisClient=[addr=redis://localhost:6379], channel=[id: 0x5e3b8b34, L:/127.0.0.1:55233 - R:localhost/127.0.0.1:6379], currentCommand=null]

这样的打印能否用配置关掉呢?
我不想影响其他的DEBUG级别的日志输出!
谢谢

**Comment by mrniko** [comment]
you need to set `info` logging level for `org.redisson` package.

**Comment by xaviershl** [comment]
thank you !  but  how?

this is my code :


			Config config = new Config();
			
			config.setCodec(new StringCodec());
			
			if(StringUtils.isNotBlank(auth)){
				config.useSingleServer().setAddress("redis://" + host + ":" + port).setPassword(auth);
			}else{
				config.useSingleServer().setAddress("redis://" + host + ":" + port);
			}
			
			redisson = Redisson.create(config);

			redisInitSuccess = true;
			log.info("Redis初始化成功。");

**Comment by xaviershl** [comment]
> org.redisson

ok! thank you!
