### ISSUE TITLE
RedissonMap.keySet(pattern, batchSizeHint).isEmpty() is inefficient

### ISSUE THREAD

**Issue by nanw1103** [redisson/redisson#3298]
`

        RMap myRMap = redisson.getMap("my-map");
        String pattern = "mykey-*";
        int batchHint = 1;
        Set<String> keySet = myRMap.keySet(pattern, batchHint);

        //The implementation of "keySet(pattern).isEmpty()" is very in-effective, which iterates all keys.
        //boolean isEmpty = keySet.isEmpty();

        //A workaround is something like this
        boolean isEmpty = !keySet.iterator().hasNext();
`

**Comment by mrniko** [comment]
Done! Thanks for report
