### ISSUE TITLE
RSet broken for serializable custom pojos  

### ISSUE THREAD

**Issue by Godsim** [redisson/redisson#3300]
**Expected behavior**
When working with multiple service instances and using RSet as a distributed cache, add() will create a duplicate for a custom serializable pojo even though equals() and hashCode() are implemented correctly. Also the contains() method will return false when checking the same pojo from different instances OR from the same instance with a refetched RSet like 

`RSet<SerializablePojo> = redissionClient.getSet(key).`

**Actual behavior**
RSet's contains() method returns false. RSet's add() method will add the same object multiple times.

**Steps to reproduce or test case**
Take any simple serializable pojo, add it to an RSet. Get the RSet again from the redission client and call its contains() or add() method with the same object. contains() will return false, and the same object will be added again.
The size of the RSet will increase with each add(). Using the RSet as a constructor parameter for a native HashSet(), its size will  always be constant, since the duplicates are not added as expected. 

**Redis version**
6.0.9

**Redisson version**
3.14.0

**Redisson configuration**

**Comment by Godsim** [comment]
Now I tested my distributed services with the RQueue and the poll() returns the same job on all instances. Maybe I'm doing something wrong? Or I wrongfully assumed that Redisson is in fact the right choice for distributed, consistent data sets.
I hope someone can help to clarify my problem! Thanks in advance!

**Comment by mrniko** [comment]
> add() will create a duplicate for a custom serializable pojo even though equals() and hashCode() are implemented correctly

Redis doesn't invoke `equals()` and `hashCode()` methods. Objects are compared by serialized state.
