### ISSUE TITLE
First call to RMapCache get() 10 times slower than subsequent calls why?

### ISSUE THREAD

**Issue by fotherda71** [redisson/redisson#3301]
Trying to understand the slow performance of get(). I run a test program:

        RMapCache<String, RedisUserData> userMap = redisson.getMapCache("userMap");

        int NUM_USERS = 10;

        for(int i=0; i<NUM_USERS; i++) {

            Instant start = Instant.now();
            RedisUserData userData = userMap.get("userABC");
            Instant end = Instant.now();

            System.out.println(Duration.between(start, end).toNanos()/1e6 +
                " millis/user");

            Thread.sleep(10000);
        }

The output is:

7.7 millis/user
0.7 millis/user
0.5 millis/user
0.2 millis/user
0.2 millis/user
0.3 millis/user
0.4 millis/user
0.2 millis/user
0.4 millis/user
0.1 millis/user

What is happening on the first call that isn't happening afterwards?

Many thanks for your help.

WHat is happening

**Comment by mrniko** [comment]
which codec do you use?
