### ISSUE TITLE
RBlockingQueue entries are sometimes lost.

### ISSUE THREAD

**Issue by marcusspangenberg** [redisson/redisson#3302]
RBlockingQueue entries are sometimes lost.

**Expected behavior**
All entries added to the queue with put are returned with poll.

**Actual behavior**
Sometimes a queue entry will be lost when poll returns.

**Steps to reproduce or test case**
Minimal code sample used to reproduce: https://gist.github.com/marcusspangenberg/8f4e7047dc0e2465002a8408cca46295

The bug reproduces within 100 iterations in included sample. The poll timeout is set to 1 ms to increase likelihood of the error happening. In a live system I have this set to 5 seconds and I get this error several times a day.

**Redis version**
5.0.10

**Redisson version**
Reproduces in Redisson 3.7.0 -> 3.14.0. Unable to reproduce with Redisson 3.6.5. Using openjdk 11.

**Redisson configuration**
final var singleServerConfig = config.useSingleServer();
singleServerConfig.setAddress("redis://127.0.0.1:6379");

**Comment by mrniko** [comment]
Thanks for the provided test sample, it helped a lot! Fixed

**Comment by devbith** [comment]
Hi @marcusspangenberg  @mrniko 

 In my application, randomly  RBlockingQueue data being lost but I am not able to reproduce it so far but sometime it happens out of nowhere. 


I found this issue and tired to access the this link to see the sample to reproduce but it seems this has been deleted. 
Minimal code sample used to reproduce: https://gist.github.com/marcusspangenberg/8f4e7047dc0e2465002a8408cca46295

Is it possible to share the code sample again ?

**Comment by mrniko** [comment]
@devbith 

Which Redisson version do you use?

**Comment by bishalthapatrustly** [comment]
@mrniko I am using redisson:3.20.0

**Comment by devbith** [comment]
@mrniko  I am using Redission version 3.20.0

**Comment by mrniko** [comment]
which RBlockingQueue method is used?

**Comment by bishalthapatrustly** [comment]
@mrniko I am using the the take() method 

```
TypedJsonJacksonCodec codec = new TypedJsonJacksonCodec(MyDTO.class, new ObjectMapper());
RBlockingQueue<MyDTO> rBlockingQueue = redisson.getBlockingQueue("Orders", codec);
RDelayedQueue<MyDTO> rDelayedQueue = redisson.getDelayedQueue(rBlockingQueue);
```

Added by another thread
``rDelayedQueue.offer(...., 2, TimeUnit.MILLISECONDS);``

Reads by another thread
``rBlockingQueue.take(); ``

**Comment by mrniko** [comment]
@bishalthapatrustly 

Which Redisson version?

**Comment by devbith** [comment]
Version 3.20.0

**Comment by sunxiang0918** [comment]
I also found RBlockingDeque sometimes lost entries. (RBlockingDeque.addFirst and RBlockingDeque.poll  )
but I used redisson which version is 3.12.5.   I will update to 3.21.3, and try again.

**Comment by devbith** [comment]
@mrniko thank you for being actively being concerned about the issue.

Were you able to find something ?

**Comment by mrniko** [comment]
@devbith 

Can you introduce a RAtomicLong counter increased after each data insert into queue and decreased after each data pull call?

**Comment by mrniko** [comment]
@devbith 

Have you got any results?

**Comment by mrniko** [comment]
@devbith 

Any update?

**Comment by devbith** [comment]
Hi @mrniko, After adding the counter with RAtomicLong, the issue is resolved 👍 
thank you

**Comment by anonymous209184** [comment]
> Hi @mrniko, After adding the counter with RAtomicLong, the issue is resolved 👍 thank you
can you give me sample code, Thanks

**Comment by mrniko** [comment]
> I also found RBlockingDeque sometimes lost entries. (RBlockingDeque.addFirst and RBlockingDeque.pollLast ) but I used redisson which version is 3.12.5. I will update to 3.21.3, and try again.

Did you manage to reproduce the issue with 3.21.3 ?

**Comment by jia122477** [comment]
> 嗨，使用RAtomicLong添加计数器后，问题已解决👍谢谢
能提供下实例代码吗 ？

**Comment by jia122477** [comment]
> @devbith
> 
> 有什么更新吗？

您好 这个目前哪个版本修复了这个问题 还是说只能通过RAtomicLong添加计数器来解决呢 ？

**Comment by sunxiang0918** [comment]
> @sunxiang0918 > > > I also found RBlockingDeque sometimes lost entries. (RBlockingDeque.addFirst and RBlockingDeque.pollLast ) but I used redisson which version is 3.12.5. I will update to 3.21.3, and try again. > > Did you manage to reproduce the issue with 3.21.3 ?

No, after updating to 3.21.3+ , I can't reproduce the issue.

**Comment by jia122477** [comment]
> > > > >我还发现 RBlockingDeque 有时会丢失条目。（RBlockingDeque.addFirst 和 RBlockingDeque.pollLast ）但我使用了 redisson，其版本是 3.12.5。我将更新到 3.21.3，然后重试。> > 您是否设法重现了 3.21.3 的问题？
> 
> 不，更新到 3.21.3+ 后，我无法重现该问题。

目前我的项目springboot版本是v2.4.13 ，最大只能使用redisson3.18.0， 无法更新到3.21.3+ ，是不是只能通过RAtomicLong添加计数器来解决 ？ RAtomicLong这种解决方式能提供下简单的示例吗  感谢
