### ISSUE TITLE
Make RxJava/Reactive libraries optional/move them to separate modules

### ISSUE THREAD

**Issue by gokhanoner** [redisson/redisson#3305]
Curently, `redisson` library itself is more than 2MB. When added Netty, another 2.5MB, along with RxJava, +2MB, & Project Reactor, 1.5MB, its nearly 10MB in total dependency size, even without Spring etc. I realized that both `RxJava` &  `Project Reactor` classes are not necessary for all operations, mostly has their own packages for operations/data structures etc. I believe it'd be extremely useful to move them to their own separate modules so anyone who wishes to use them, either one or both, can add specifically, but the core will be free from those dependencies & be more compact.

**Comment by mrniko** [comment]
RxJava & Project Reactor libs are optional.

**Comment by gokhanoner** [comment]
@mrniko unless I read wrong, it doesn't say optional here -> https://github.com/redisson/redisson/blob/master/redisson/pom.xml#L82

Maybe the usage is optional, but are you suggesting I just exclude those dependencies??

**Comment by mrniko** [comment]
yes, just exclude them
