### ISSUE TITLE
RPriorityQueue/RPriorityBlockingDeque peek instance object, update value won't save to redis

### ISSUE THREAD

**Issue by JH-D** [redisson/redisson#3307]
Being confused.
If won't save update changes to redis automatically,  "RPriorityQueue/RPriorityBlockingDeque"  feature is almost no help  personally.

The memory address keep change:

```
RPriorityQueue queue = redisson.getPriorityQueue("anyQueue"); // step 1
Vo topOne = queue.peek(); // step 2
topOne.setUsing(true); // step 3
```

step 1:

![图片](https://user-images.githubusercontent.com/7844108/102867849-58b3b700-4474-11eb-813c-7c21e96a9d7a.png)

step 2:

![图片](https://user-images.githubusercontent.com/7844108/102867870-5ea99800-4474-11eb-9d1a-3b4db225135f.png)

step 3: The head of RPriorityQueue, "using" property still be "false"，no matter get from redis later again .

![图片](https://user-images.githubusercontent.com/7844108/102867913-6cf7b400-4474-11eb-97e3-bf666703cdad.png)

**Comment by mrniko** [comment]
returned value by peek() method isn't a proxy. It doesn't track updated values. You need to update them manually.
