### ISSUE TITLE
AccessorInterceptor#removeIndex: incorrect behavior of removeIndex(RMap<String, Object>, Object, Field) method

### ISSUE THREAD

**Issue by GenCloud** [redisson/redisson#3311]
**Expected behavior**
Correct removed index if exists in cluster mode or not removed if value index does not exists.

**Actual behavior**
Current call of AccessorInterceptor#removeIndex(RMap<String, Object>, Object, Field) raises an NPE if index value does not exists.

**Steps to reproduce or test case**
```java
@REntity
@Data // auto generated getName/setName/getId/setId/equals/hashCode
public class Entity implements Serializable {
    @RId(generator = LongGenerator.class)
    private Long id;
    
    @RIndex
    private int idx1;
    @RIndex
    private int idx2;
}
```

2) Persist and delete entity
```java
public void test() {
        final RLiveObjectService liveObjectService = PersistenceStateManager.getInstance()
                .getSyncClient().getLiveObjectService();
        liveObjectService.registerClass(Entity.class);
        
        Entity entity = new Entity();
        entity.setIdx1(1);
        entity.setIdx2(2);

        liveObjectService.persist(entity);
}
```
3) See throwed exception:
```java.lang.NullPointerException``` in method removeIndex (line 200, liveMap.remove(String) returning null and isn't RLiveObjectInstancee) if idx1 not marked as REntity and using cluster

```java
Object value = liveMap.remove(field.getName()); <-- null
RMultimapAsync<Object, Object> map = new RedissonSetMultimap<>(namingScheme.getCodec(), ce, indexName);
map.removeAsync(
         ((RLiveObject) value).getLiveObjectId(), <-- wtf?
         ((RLiveObject) me).getLiveObjectId()
);
```

Solutions to the problem:

add null check, or store woking functional

**Redis version**
6.0.6

**Redisson version**
3.14.1

**Redisson configuration**
cluster server configuration (3 master, 3 slaves)

**Comment by GenCloud** [comment]
up

**Comment by mrniko** [comment]
Fixed
