### ISSUE TITLE
AccessorInterceptor#removeAsync: incorrect behavior of removeAsync(CommandBatchService, String, String, Codec, Object, String) method

### ISSUE THREAD

**Issue by GenCloud** [redisson/redisson#3312]
**Expected behavior**
Correct removed index.

**Actual behavior**
Current call of AccessorInterceptor#removeAsync(CommandBatchService, String, String, Codec, Object, String) raises an script exception ```ERR Error running script (call to f_7f573e8a56b15c812f93887e04b9fdb40d72f0e6): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value```.

**Steps to reproduce or test case**
```java
@REntity
@Data // auto generated getName/setName/getId/setId/equals/hashCode
public class Entity implements Serializable {
    @RId(generator = LongGenerator.class)
    private Long id;
    
    @RIndex
    private int idx1;
    @RIndex
    private int idx2;
}
```

2) Persist and delete entity
```java
public void test() {
        final RLiveObjectService liveObjectService = PersistenceStateManager.getInstance()
                .getSyncClient().getLiveObjectService();
        liveObjectService.registerClass(Entity.class);
        
        Entity entity = new Entity();
        entity.setIdx1(1);
        entity.setIdx2(2);

        liveObjectService.persist(entity);
}
```

3) See throwed exception:
```ERR Error running script (call to f_7f573e8a56b15c812f93887e04b9fdb40d72f0e6): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value```

**Redis version**
6.0.6

**Redisson version**
3.14.1

**Redisson configuration**
single server configuration

**Comment by GenCloud** [comment]
up

**Comment by mrniko** [comment]
Fixed
