### ISSUE TITLE
need to trigger RLock.unlock() twice to remove lock

### ISSUE THREAD

**Issue by Sirius-Dour** [redisson/redisson#3317]
Hi

i have strange behavior in my program. I am trying to implement something like "getAndLock then PutAndRelease". 
Here is my getAndLock function:
```
            RMap<String, byte[]> rMap = redisson.getMap(mapName);
            redisson.getLock(mapName+"@"+objId).lock();
            byte[] dbValue = rMap.get(objId);
```
Here is my PutAndRelease function: 
```
        RLock rLock = redisson.getLock(mapName + "@" + obj.getKey());
        if (!rLock.tryLock()) throw new DbException("attempt to modify locked data");
        redisson.getMap(mapName).put(obj.getKey(), obj.getValue());
        LOGGER.trace("rLock.isLocked() {}", rLock.isLocked());
        rLock.unlock();
        LOGGER.trace("rLock.isLocked() {}", rLock.isLocked());
        if(rLock.isLocked()) {
            rLock.unlock();
            LOGGER.trace("rLock.isLocked() {}", rLock.isLocked());
        }
```
i can see that after 1-st rLock.unlock(); lock is still alive (presented in reddis and rLock.isLocked() == true)
and after 2-d rLock.unlock() it is released (removed from reddis and rLock.isLocked() == false)

Why is it so? why do i need to trigger rLock.unlock(); multiple times until it finally removes lock?

**Comment by Sirius-Dour** [comment]
i checked what is presented in rediss more precisely and saw that there is some value
```
        RLock lock = redisson.getLock("ololo@ololo");
        lock.lock();
        lock.lock();
        lock.lock();
```
after this value == 3  and lock.isLocked() == true

```
        RLock lock = redisson.getLock("ololo@ololo");
        lock.lock();
        lock.lock();
        lock.lock();

        lock.unlock();
        lock.unlock();
```
after this value == 1  and lock.isLocked() == true

```
        RLock lock = redisson.getLock("ololo@ololo");
        lock.lock();
        lock.lock();
        lock.lock();

        lock.forceUnlock();
```
after this lock is not presented in rediss and lock.isLocked() == false

So looks like to remove lock i have trigger unlock() so many times as i had triggered lock()/tryLock() before
or just trigger forceUnlock() once. but this thing is not checking my permissions

So as i understand best way to unlock is
`if (lock.tryLock()) lock.forceUnlock();`
this will check my permission to manipulate this lock and if i allowed then will remove it

Am i correct? Or it should be done in other way?

**Comment by mrniko** [comment]
> So looks like to remove lock i have to trigger unlock() so many times as i had triggered lock()/tryLock() before

RLock has the same behavior as JDK Lock implementation. Please take this in account before RLock usage.
