### ISSUE TITLE
Issue with redisson - Exception Command still hasn't been written into connection!

### ISSUE THREAD

**Issue by sushantbhat** [redisson/redisson#3318]
Hi, 

We are using AWS elasticache Redis with cluster mode enabled. We are seeing below issue intermittently from Redisson, please guide how to resolve this issue.

Exception Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=6524, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@106880645 [redisClient=[addr=redis://****], channel=[id: 0xdb426022, L:/****:52758 - R:/****:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@6b0e5454(failure: java.util.concurrent.CancellationException)], command=(GET), params=[***], codec=org.redisson.codec.MarshallingCodec]], command: (GET), params: [***] after 5 retry attempts

Below is the cluster configuration:
Config config = new Config();
                config.setNettyThreads(1000);
                config.useClusterServers().addNodeAddress(REDIS_CLUSTER)
                        .setTimeout(30000)
                        .setMasterConnectionPoolSize(1000)
                        .setSlaveConnectionPoolSize(1000)
                        .setRetryAttempts(5)
                        .setRetryInterval(5000);
                redissonCluster = Redisson.create(config);

I have tried increasing netty threads, connection pool size and retry attempts.
Average load on our system is around 500 requests/sec.

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/2559#issuecomment-621652611
