### ISSUE TITLE
RedissonMultiLock#tryLock  The difference between leasetime and newLeasetime

### ISSUE THREAD

**Issue by mapy95** [redisson/redisson#3323]
org.redisson.RedissonMultiLock#tryLock(long, long, java.util.concurrent.TimeUnit)

In this method, both waittime and leasetime are specified. That is to say, the leasetime and waittime of the input parameter are not equal to - 1. When locking, newleasetime is used, which is twice as much as waittime. Why not use the leasetime in the input parameter

version：org.redisson:redisson:3.13.2

**Comment by mrniko** [comment]
waitTime applied only to acquire lock and not connected with leaseTime parameter
