### ISSUE TITLE
What's the best way to iterate through a Mapcache

### ISSUE THREAD

**Issue by xujiaxj** [redisson/redisson#3326]
Looking at this [example](https://github.com/redisson/redisson-examples/blob/master/collections-examples/src/main/java/org/redisson/example/collections/MapCacheExamples.java), there are different ways to iterate though a map

```
Set<String> allKeys = mapCache.readAllKeySet();
Collection<Integer> allValues = mapCache.readAllValues();
Set<Entry<String, Integer>> allEntries = mapCache.readAllEntrySet();
```
In addition, I can also use Java native API
```
for (Map.Entry<String, Integer> entry : mapCache.entrySet()) {
}
```

Suppose the map has millions of entries, what's the best way to iterate through the map to get all key/value pairs, without blocking Redis? 

My understanding is that `KEYS` command may block other clients, so `HSCAN` may be better. Does Redisson support the map iteration based on `HSCAN`?

**Comment by mrniko** [comment]
yes, Redisson uses hscan command for mapcache object.

**Comment by xujiaxj** [comment]
Does it mean the above-mentioned approaches (`readAllKeySet`, `readAllValues`, `readAllEntrySet`, or `entrySet`) all use `hscan` command? Or only some of them do?

**Comment by mrniko** [comment]
only **entrySet** method uses hscan. **read*** methods read all state of map in a single Redis request.

**Comment by xujiaxj** [comment]
Thank!
