### ISSUE TITLE
about slave node down status

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#3345]
flags field that “sentinel slaves xxx” command result contains “s_down” or “disconnected”, manager will freezed the node,
but master-link-status than “sentinel slaves xxx” command result is “err”, slave node is in “LOADING Redis is loading the dataset in memory” status, why not add this condition in slave node state check? just like 
```
String ip = map.get("ip");
String port = map.get("port");
String flags = map.get("flags");
String masterHost = map.get("master-host");
String masterPort = map.get("master-port");
String masterLinkStatus = map.get("master-link-status");

RedisURI slaveAddr = toURI(ip, port);
if (flags.contains("s_down") || flags.contains("disconnected") || masterLinkStatus.contains("err")) {
    slaveDown(slaveAddr);
    continue;
}
```

**Comment by mrniko** [comment]
Can you suggest PR?

**Comment by mrniko** [comment]
merged
