### ISSUE TITLE
The timeout configuration of MapReduce does not work

### ISSUE THREAD

**Issue by honestAnt** [redisson/redisson#3347]
env info：
jdk：1.8
redis：5.0.6
redission: 3.11.5
--------------------------------------
There are two data processing services here. When I use MapReduce to process data, the timeout (30 s) is set. However, when one of the services in the process of reducing data goes down unexpectedly, there is still no response from the map after the timeout, Does the data processed by the down service need to be reallocated to other machines? What is the specific meaning of this timeout? Is there something wrong with my use?

The following pictures are related information:

This is the normal data processing service:
![企业微信截图_07a493e0-edaa-48c3-8783-86116db6f561](https://user-images.githubusercontent.com/15356873/104715040-f1caaa80-5760-11eb-93b0-df54ebe97443.png)

This is a service that has been down unexpectedly:
![企业微信截图_cc100190-d5f6-4109-b723-fd8dc001c191](https://user-images.githubusercontent.com/15356873/104715065-f8592200-5760-11eb-8e98-791ca6ba7c66.png)

This is the configuration code information:
![企业微信截图_d3e64bc2-5725-413a-a4d3-8c0b96e9d343](https://user-images.githubusercontent.com/15356873/104715024-ed9e8d00-5760-11eb-85ec-285d0e7c113d.png)

This is the now time:
![image](https://user-images.githubusercontent.com/15356873/104715174-22aadf80-5761-11eb-825b-b5e57e3235ca.png)

@mrniko   thanks

**Comment by mrniko** [comment]
Default taskRetryInterval is 5 minutes, but for map-reduce it's just cancelled: https://github.com/redisson/redisson/blob/ba31cf09018f05ffa54f017e1027e45f59624ff2/redisson/src/main/java/org/redisson/mapreduce/CoordinatorTask.java#L109

This logic should be reconsidered.

**Comment by honestAnt** [comment]
> Default taskRetryInterval is 5 minutes, but for map-reduce it's just cancelled after timeout:
> 
> https://github.com/redisson/redisson/blob/ba31cf09018f05ffa54f017e1027e45f59624ff2/redisson/src/main/java/org/redisson/mapreduce/CoordinatorTask.java#L109
> 
> This logic should be reconsidered.

OK, thank you for your information. Is there any good practice to compensate MapReduce for timeout or abnormal node calculation?

**Comment by mrniko** [comment]
Fixed. Thanks for report!
