### ISSUE TITLE
Redisson mapwriter

### ISSUE THREAD

**Issue by BhaveshPunjabi** [redisson/redisson#3348]
I am using RMapCache<String,Object> with map option with write mode as WRITE_BEHIND 
now when i put something in cache after particular delay it is getting executed after dealy provided,
but what i need is map writer should pick entry from map unless it is cache but it is not doing so it is only getting executed once.

Can anyone help what can i do in this case or there is any alternative?

**Comment by mrniko** [comment]
MapWriter writes cache entry during put operation execution only.

**Comment by BhaveshPunjabi** [comment]
is there any alternative way in which i can loop my cache entry till the value is not getting evicted?

**Comment by mrniko** [comment]
I'm afraid no.
