### ISSUE TITLE
Spin lock with exponential backoff

### ISSUE THREAD

**Issue by Vorotyntsev** [redisson/redisson#3349]
`RedissonLock` uses pubsub mechanism to get notified about changes to lock. According to the cluster spec (https://redis.io/topics/cluster-spec), currently messages are simply broadcasted to all nodes in the cluster. It makes this lock inefficient in clusters with more than 5 nodes.

It would be great to have a spin lock with exponential backoff, because it works well with Redis's horizontal scaling.

If the idea seems fine to you, I can prepare a PR in a few days, just let me know. If not - sorry for taking your time, feel free to close the feature request.

Best regards,
Danila Varatyntsev

**Comment by mrniko** [comment]
> It makes this lock inefficient in clusters with more than 5 nodes.

Can you clarify here? I don't understand how it affects lock.

**Comment by Vorotyntsev** [comment]
It doesn't affect lock itself, it affects cluster performance. 
We reached a network throughput limit on AWS Redis cluster with 20 nodes, when we tried to aquire and release more than 1.000.000 locks per minute, because messages are distributed to all nodes. When network throughput reaches the limit, Redis engine CPU increases to 100% and service fails to process request. Increasing cluster size makes this problem to happen even earlier, because messages are sent to more nodes. And we couldn't use a cluster with fewer number of nodes, because we used the same cluster for other non-pubsub requests.

**Comment by Vorotyntsev** [comment]
[Here](https://github.com/redis/redis/issues/2672#issuecomment-164376229) antirez wrote that following:
```
In the current naive implementation every message is sent to every node, which is quite an overhead, but by limiting the number of instances to 3/4, the overhead is acceptable
```

**Comment by mrniko** [comment]
Yes, that lock could be interesting feature. Different backoff algorithms could be offered, similar to described in this article https://aws.amazon.com/ru/blogs/architecture/exponential-backoff-and-jitter/

**Comment by mrniko** [comment]
Best implementation is to make base RedissonLock and RedissonSpinLock extending from BaseLock class.

**Comment by mrniko** [comment]
merged
