### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Command still hasn’t been written into connection!  Increase nettyThreads and/or retryInterval settings.

### ISSUE THREAD

**Issue by mraees** [redisson/redisson#3359]
Got this exception continuously for a minute and then became fine. Would like to know what is the root cause of this. 
Using Redisson : 3.13.2

org.redisson.client.RedisTimeoutException: Command still hasn’t been written into connection! 
 Increase nettyThreads and/or retryInterval settings. 
 Payload size in bytes: 0. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry 
 [masterEntry=[freeSubscribeConnectionsAmount=4, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=33, 
 freeConnectionsCounter=value:62:queue:0, freezed=false, 
 freezeReason=null, client=[addr=******], nodeType=MASTER, 
 firstFail=0]]], connection: RedisConnection@145638153 
 [redisClient=[addr=******], channel=[id: 0x20213438, 
 L:/10.20.13.18:45856 - R:*****], currentCommand=null], 
 command: null, params: null after 3 retry attempts

**Comment by mrniko** [comment]
do use async/rx/reactive api?

**Comment by mraees** [comment]
I do use 
final RBatch batchOperation = redissonClient.createBatch();
batchOperation.getAtomicLong(redisKey).incrementAndGetAsync(); -> this is inside a for loop. This is an async API right!!

**Comment by mrniko** [comment]
If you use blocking commands in async listeners this will cause such error.

**Comment by ShanmugamC** [comment]
@mrniko any workaround to avoid this issue for reactive api?

**Comment by mrniko** [comment]
@ShanmugamC 

Can you share code sample?
