### ISSUE TITLE
FstCodec error

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#3363]
Use version redisson-all-3.12.1
Data abnormal under high concurrency
normal data 
"roleId2": "ROLEINFO#7001#21693#4002#4",
Fault data
"roleId2": "com.game.logical.role.beans.OtherHeroBean@5300e72",
"roleId2": [10006,10001,10007,12001],
"roleId2": [],

All of the places we assign are strings

Under what circumstances does this happen to the data or is it a bug that has been fixed? If so, in what version did you change those things

我们有个数据是string  所有赋值的地方也是string  数据会莫名其妙变成对象 不知道是写的问题还是读的问题  取出错误数据后使用会造成jvm宕机 不是必现 有概率出现
什么情况下数据会出现这种情况  还是这是个bug 已经修复  如果已经修复 是在哪个版本 修改了那些东西

**Comment by mrniko** [comment]
fstcodec is a binary codec

**Comment by wl980868110** [comment]
I mean after the parsing

**Comment by wl980868110** [comment]
I mean after deserialization

**Comment by WolfHawk-GITHUB** [comment]
问题的意思是正常使用中。遇到下面的问题。
正常数据格式。"roleId2": "ROLEINFO#7001#21693#4002#4"  不知道什么情况下。数据突然变成了
"roleId2": "com.game.logical.role.beans.OtherHeroBean@5300e72",
"roleId2": [10006,10001,10007,12001],
"roleId2": [],
这样的不可理解的格式。甚至变成了一个代码中的对象。正常使用不可能这样赋值。我也遇到过这样的问题。

**Comment by WolfHawk-GITHUB** [comment]
public class CrossAllStarPopRankRedis extends BaseRedissonDbBean implements Serializable
{
	private static final long serialVersionUID=1L;
	/** 活动id */
	private int activityId;
	/** 排行榜MAP */
	private Map<String,CrossAllStarCommonDataBean> rankMap=new ConcurrentHashMap<>();
	/** 队伍 排行榜MAP */
	private Map<String,CrossAllStarCommonDataBean> teamRankMap=new ConcurrentHashMap<>();
}
public class CrossAllStarCommonDataBean implements Serializable
{
	private static final long serialVersionUID=1L;
	/** 玩家信息主键 */
	private String roleKey;
	/** 积分 */
	private long score;
	/** 战斗 */
	private long battle;
}

比如redis数据CrossAllStarPopRankRedis 。其CrossAllStarCommonDataBean 中的roleKey就会出现上述情况。就是String的偶尔会出现，int，long不会。

**Comment by mrniko** [comment]
Did you try to use another codec?

**Comment by wl980868110** [comment]
no

**Comment by mrniko** [comment]
I recommend to use MarshallingCodec which is default. FstCodec may cause errors during deserialization according to user reports.

**Comment by wl980868110** [comment]
redisson-all-3.4.1  fst  Version 2.57 reduced to 2.47   Why was the version lowered

**Comment by mrniko** [comment]
version isn't reduced since 2.57 > 2.47
