### ISSUE TITLE
RLocalCachedMap with Broadcast Mode tracking

### ISSUE THREAD

**Issue by vipulswarup** [redisson/redisson#3368]
Can RLocalCachedMap be used with Broadcast mode tracking? 
In Redis CLI we would enable this as "CLIENT TRACKING on REDIRECT 10 BCAST PREFIX"

**Comment by mrniko** [comment]
client tracking is not support since it's not supported in Redis cluster and master / slave environments.

**Comment by vipulswarup** [comment]
Thanks - just to clarify - Redis doesn't support Client Tracking in Redis Cluster, or is that a Redisson limitation?

**Comment by mrniko** [comment]
it's not a Redisson limitation, RLocalCachedMap works in Redis cluster.

**Comment by vipulswarup** [comment]
ok - so client tracking is not supported on clusters, hence not supported by Redisson - got it. Then what is the mechanism used by Redisson to invalidate cache keys on local cache and force a re-fetch from remote cache? ... sorry just digging deeper to fully understand this.

**Comment by mrniko** [comment]
it uses redis pubsub channel and two modes are available:

`INVALIDATE` - Default. Invalidate cache entry across all LocalCachedMap instances on map entry change
`UPDATE` - update cache entry across all LocalCachedMap instances on map entry change

**Comment by mrniko** [comment]
Current implementation of [server assisted client side caching](https://redis.io/docs/latest/commands/client-tracking/) doesn't send the field name of Redis hash, but only a key name. This means that invalidation per field isn't possible. Thus "CLIENT TRACKING" doesn't bring any benefits for local cached Redis hash structures.
