### ISSUE TITLE
 The following method did not exist: org.redisson.api.RTopic.removeListener(I)V

### ISSUE THREAD

**Issue by silence934** [redisson/redisson#3371]
![image](https://user-images.githubusercontent.com/49453669/105435528-76a15100-5c98-11eb-880c-c61c6079604a.png)
![image](https://user-images.githubusercontent.com/49453669/105435554-8456d680-5c98-11eb-8507-dd01695c98f3.png)

**Comment by mrniko** [comment]
update netty-socketio to the latest version
