### ISSUE TITLE
Will tasks submitted via redisson ExecutorService be executed after redis instance is restarted?

### ISSUE THREAD

**Issue by mshabunin77** [redisson/redisson#3373]
It's not an issue, it's a question I have not found an answer to in documentation. 
Will tasks that were submitted via redisson ExecutorService be executed if redis instance is restarted?
For example, a task is submitted with a delay 10mins and right after it was submitted, redis is restarted. What will happen with that submitted task?
What if I have AWS ElastiCache with Redis Replication Group and Multi-AZ enabled - will that task be executed if it was successfully replicated to read instances and primary instance failed?

**Comment by mrniko** [comment]
> Will tasks that were submitted via redisson ExecutorService be executed if redis instance is restarted?

Yes.

> What if I have AWS ElastiCache with Redis Replication Group and Multi-AZ enabled - will that task be executed if it was successfully replicated to read instances and primary instance failed?

Task will be picked by tasks queue handler after failover.
