### ISSUE TITLE
time_to_live and max_idle_time doesn't work in redisson as 2 level cache in hibernate

### ISSUE THREAD

**Issue by yeagerrrr** [redisson/redisson#3374]
Hello everybody,
I try to use Redisson  as second level cache in my jpa spring boot application it works fine i see that it cache entities in redis it just i need to set a time to live and time to idle on cache entries i use this configuration below but it doesn't work:

`spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.cache.type=redis

hibernate.cache.redisson.entity.expiration.time_to_live=1000
hibernate.cache.redisson.entity.expiration.max_idle_time=1000
hibernate.cache.redisson.collection.expiration.time_to_live=1000
hibernate.cache.redisson.collection.expiration.max_idle_time=1000

spring.jpa.properties.hibernate.cache.region.factory_class=org.redisson.hibernate.RedissonRegionFactory
spring.jpa.properties.hibernate.cache.redisson.config=redisson/redisson-dev.yaml
spring.jpa.properties.hibernate.cache.redisson.fallback=true
spring.jpa.properties.javax.persistence.sharedCache.mode=ENABLE_SELECTIVE

server.port=8888
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-plateform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
`

i use  redisson-hibernate-53  as dependancy

Any help on this will help ,thank you.

**Comment by mrniko** [comment]
I think spring config file doesn't pickup custom hibernate settings used by Redisson. Try to define them in hibernate config xml file

**Comment by yeagerrrr** [comment]
it works !!!!!
i just use : 

spring.jpa.properties.hibernate.cache.redisson.entity.expiration.time_to_live=1000
spring.jpa.properties.hibernate.cache.redisson.entity.expiration.max_idle_time=1000
spring.jpa.properties.hibernate.cache.redisson.collection.expiration.time_to_live=1000
spring.jpa.properties.hibernate.cache.redisson.collection.expiration.max_idle_time=1000

intead of : 

hibernate.cache.redisson.entity.expiration.time_to_live=1000
hibernate.cache.redisson.entity.expiration.max_idle_time=1000
hibernate.cache.redisson.collection.expiration.time_to_live=1000
hibernate.cache.redisson.collection.expiration.max_idle_time=1000

@mrniko thank you very much for your answer 👍

**Comment by mrniko** [comment]
I'm closing this

**Comment by stefanofalconetti** [comment]
Hello and good day, 

I'm dealing with a Spring Boot 4.0.1 project and with the below config settings I'm still experimenting similar problem (ttl not being set different from -1 that I believe is the default no expiry), with redisson 4.1.0 behind jcache jsr-107, I tried setting in hibernate all possible combination for my region prefix (hrp-dm-filtering) and region name (queryCache) but in no case the TTL is propagated to Redis/Valeky and items are not expiring:


 
        <property name="hibernate.hbm2ddl.auto">validate</property>
        <property name="hibernate.search.autoregister_listeners">true</property>

        
        <property name="hibernate.cache.region.factory_class">org.hibernate.cache.jcache.JCacheRegionFactory</property>
        <property name="hibernate.cache.region_prefix">hrp-dm-filtering</property>
        
        <property name="hibernate.javax.cache.provider">org.redisson.jcache.JCachingProvider</property>
        <property name="hibernate.javax.cache.uri">classpath:runtime-orm-valkey-L2.yaml</property>
        <property name="javax.cache.provider">org.redisson.jcache.JCachingProvider</property>

        <property name="hibernate.cache.redisson.entity.eviction.max_entries">200</property>
        <property name="hibernate.cache.redisson.entity.expiration.time_to_live">10000</property>
        <property name="hibernate.cache.redisson.entity.expiration.max_idle_time">10000</property>
        <property name="hibernate.cache.redisson.query.eviction.max_entries">200</property>
		<property name="hibernate.cache.redisson.query.expiration.time_to_live">10000</property>
		<property name="hibernate.cache.redisson.query.expiration.max_idle_time">10000</property>

        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.time_to_live">10000</property>
        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.max_idle_time">10000</property>
        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.eviction.max_entries">2</property>


        <property name="spring.jpa.properties.hibernate.cache.redisson.entity.expiration.time_to_live">10000</property>
		<property name="spring.jpa.properties.hibernate.cache.redisson.entity.expiration.max_idle_time">10000</property>
		<property name="spring.jpa.properties.hibernate.cache.redisson.collection.expiration.time_to_live">10000</property>
		<property name="spring.jpa.properties.hibernate.cache.redisson.collection.expiration.max_idle_time">10000</property>

		<property name="spring.jpa.properties.hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.time_to_live">10000</property>
		<property name="spring.jpa.properties.hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.max_idle_time">10000</property>
		<property name="spring.jpa.properties.hibernate.cache.redisson.hrp-dm-filtering.queryCache.eviction.max_entries">3</property>

		<property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.time_to_live">13000</property>
        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.max_idle_time">13000</property>
        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.eviction.max_entries">1</property>

		<property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.time_to_live">12000</property>
        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.expiration.max_idle_time">12000</property>
        <property name="hibernate.cache.redisson.hrp-dm-filtering.queryCache.eviction.max_entries">3</property>


Did anything changed with version 4.1.0 ? 

Thanks for the help anyone may be willing to provide.

Good day.

Stefano.

**Comment by mrniko** [comment]
@stefanofalconetti 

This is the root cause. The hibernate.cache.redisson.* properties only work with Redisson's native region factories:

org.redisson.hibernate.RedissonRegionFactory
org.redisson.hibernate.RedissonLocalCachedRegionFactory
org.redisson.hibernate.RedissonClusteredRegionFactory
org.redisson.hibernate.RedissonClusteredLocalCachedRegionFactory

You used `org.hibernate.cache.jcache.JCacheRegionFactory`, Hibernate uses the generic JSR-107 JCache API, which does not read the Redisson-specific Hibernate properties.

**Comment by stefanofalconetti** [comment]
Thanks @mrniko that's clear now, so there is no way to set the same with  JSR-107 JCache ? I'm getting that should be the correct abstracted cache manager for ORM but ORM would still need a ttl set.. is there any other property available to set that ? Because from what I'm understanding JSR-107 is delegating to the specific provider, creating the specs impl but cannot find what jsr expects to get to have something set fot ttl. Am I wrong ?
