### ISSUE TITLE
redisson client configuration when using AWS elastic cache with single end point but with replicas 

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3386]
what the optimal configuration when we use redisson as session manager and as a cache service , and the Redis cache provided by AWS elastic cache with a single endpoint that had replicas in the case of AZ failure ?

**Comment by mrniko** [comment]
Default settings are already optimal. Other settings like `nettyThreads`, `connectionPoolSize` ... depend on data size, Redis speed, network and application load.

**Comment by wdaas** [comment]
hi,
thanks for the replay i currently because I have one endpoint by AWS elastic cache that has replicas for the backup purposes i use as the following is it enough?

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 10000
  retryAttempts: 3
  retryInterval: 1000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://172.16.36.244:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 5
  connectionPoolSize: 250
  database: 0
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.SnappyCodec> {}

**Comment by mrniko** [comment]
I think you can use default pool size, usually it's enough. Set nettyThreads more than 32, since they used in redis decoding process.
