### ISSUE TITLE
RBatch response order with cluster env ?

### ISSUE THREAD

**Issue by waylink** [redisson/redisson#3390]
> In cluster environment batch executed in map\reduce way. It aggregates commands for each node and sends them simultaneously, then result got from each node added to common result list.

```

    /**
     * Executes all operations accumulated during async methods invocations.
     * <p>
     * If cluster configuration used then operations are grouped by slot ids
     * and may be executed on different servers. Thus command execution order could be changed
     *
     * @return List with result object for each command
     * @throws RedisException in case of any error
     *
     */
    BatchResult<?> execute() throws RedisException;
```

Read above tips, I was not sure about responses order for origin commands.
Could you help me make sure about this?

1.When commands send group by slots, but I want know responses order is right with original commands?

thx~

**Comment by mrniko** [comment]
You'll always get correct response, but in cluster environment result in BatchResult can have different order.

**Comment by waylink** [comment]
> You'll always get correct response, but in cluster environment result in BatchResult can have different order.

~~in cluster env result in batchResult have different order.~~

How to understand ?

**Comment by mrniko** [comment]
result has different order since single request spliced into different requests and executed concurrently on different Redis nodes.

**Comment by waylink** [comment]
> result has different order since single request spliced into different requests and executed concurrently on different Redis nodes. If keys of such commands don't belong to the same master node.

all right.

Invoker always get correct response in cluster env.

Only warning : BatchResult[] has different order for execute in cluster env.

**Comment by mrniko** [comment]
It's better to attach handler to each command executed in RBatch rather than use result list:

```java
		RBatch batch = client.createBatch(batchOptions);
		for (int i = 0; i < 10; i++) {
			String key = "" + i;
                        RFuture<Object> t = batch.getBucket(key).getAsync();
                        t.whenComplete((res, ex) -> {
                
                       });
		}
		batch.execute();
```
