### ISSUE TITLE
If readLock is blocked by writeLock then readLock.isLocked() should return true

### ISSUE THREAD

**Issue by Greblys** [redisson/redisson#3391]
**Expected behavior**
If readLock is blocked by writeLock then readLock.isLocked() should return true (see step 4 below)

**Actual behavior**
If readLock is blocked by writeLock then readLock.isLocked() returns false. (see step 4 below)
Note: readlock.tryLock() behaves as expected

**Steps to reproduce or test case**

1. RLock writeLock = redissonClient.getReadWriteLock("some-id").writeLock()
2. RLock readLock = redissonClient.getReadWriteLock("some-id").readLock()
3. writeLock.tryLock(...) 
4. readLock.isLocked() 
5. writeLock.unlock() 

**Redis version**
4.0.14

**Redisson version**
3.14.1

**Redisson configuration**
keepAlive: true
sslEnableEndpointIdentification: true
useSingleServer

**Comment by mrniko** [comment]
ReadLock.isLocked returns false in this case, since it wasn't acquired.

**Comment by Greblys** [comment]
I am sorry for the confusion, but I assumed that in this case ReadLock is acquired by WriteLock because both share the same lock name "some-id" and same Redisson client. Also, I did notice that ReadLock.tryLock() behaviour is blocked until step 5 is executed which is inconsistent with ReadLock.isLocked() behaviour.
