### ISSUE TITLE
Allow password (or any secret) to be set at run time after yaml config read

### ISSUE THREAD

**Issue by granadacoder** [redisson/redisson#3397]
**Is your feature request related to a problem? Please describe.**

Add a "setPassword" method to org.redisson.config.Config;

Motivation:

I'd like to configure everything EXCEPT the password in .yaml.

But allow a programatic setting of just the password after the .yaml config loads.

This way I can pull that "secret" out of a "vault"   ( hashicorp vault, azure key vault, amazon aws kms, etc)...and set it at run time.

https://github.com/redisson/redisson/blob/fe25a7f956ecc388aa196e692b20c6fa92b438c1/redisson/src/main/java/org/redisson/config/BaseConfig.java#L145

**Describe the solution you'd like**

org.redisson.config.Config;

Since we do not have access to the "inner" objects

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/Config.java#L48L56

( private SentinelServersConfig sentinelServersConfig;

    private MasterSlaveServersConfig masterSlaveServersConfig;

    private SingleServerConfig singleServerConfig;

    private ClusterServersConfig clusterServersConfig;

    private ReplicatedServersConfig replicatedServersConfig;)

provide a method on 

org.redisson.config.Config;

for "setPassword"

that will allow the setting of the inner object (if available) 
(or throw exception if not available)

OR

if you want to do it "functionally"...create an overload

 public Config(Config oldConf, String newPassword) {
}

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/Config.java#L110

**Describe alternatives you've considered**

No alternatives.

Below shows the idea:

`
    //import org.redisson.Redisson;
    //import org.redisson.api.RMapCache;
    //import org.redisson.api.RedissonClient;
    //import org.redisson.config.Config;

    public static final String REDISSON_JCACHE_YAML = "/redisson-jcache.yaml";

            Config config = null;
            try {
                // YAML configuration
                URL redissonConfigUri = MyThing.class.getResource(REDISSON_JCACHE_YAML);

                if (null == redissonConfigUri) {
                    throw new NullPointerException("My Message");
                }
                config = Config.fromYAML(redissonConfigUri);

                if (null == config) {
                    throw new NullPointerException("My Other Message");
                }

                String myPassword = /* read from a vault here */;
                config.setPassword(myPassword);

            } catch (Exception ex) {
                throw new RuntimeException("Yet Another Explicit Message", ex);
            }
            RedissonClient client = Redisson.create(config);

`

**Comment by mrniko** [comment]
> Since we do not have access to the "inner" objects

You have it:
```java
config.useClusterServers();
config.useReplicatedServers();
config.useSentinelServers();
config.useSingleServer();
```

**Comment by granadacoder** [comment]
That is the issue.  I don't want to assume which of the concretes I have defined in the .yaml.

I have to **assume** a concrete to code to a concrete (SingleServerConfig in your case).

I want to yml to be any of the concretes.......and still be able to set the password from a vault.

For a local developer my yml may be singleserver.  For production, my yml may be any of the big hitter concretes.
But I would like the code to be the same for setting the password.

**Comment by avcad** [comment]
Not sure if it helps you, but we had a similar requirement. (using encrypted password)
I load the redis_cfg.yaml file into a string first, do the substitutions  and then use:
Config.fromYAML( configInString );
You can have something in the file like
password: <MYPASSWORD>
and replace <MYPASSWORD> in the code before calling Config.fromYAML

**Comment by granadacoder** [comment]
> Not sure if it helps you, but we had a similar requirement. (using encrypted password)
> I load the redis_cfg.yaml file into a string first, do the substitutions and then use:
> Config.fromYAML( configInString );
> You can have something in the file like
> password: !MYPASSWORD!
> and replace !MYPASSWORD! in the code before calling Config.fromYAML

Ok.. that makes sense as a work around.  Thanks for sharing.

**Comment by CyrilDevOps** [comment]
Can we reopen that case ? and have the possibility of setting a password after the Config.fromYaml whatever type of config (single/replicated ...) it is ? and without having to do 'dirty' search and replace pattern ?

We are using spring boot and our redis password is set into the spring boot environment, but all the other redis config come from a yaml file provided by the developer/devops, it can be single server, replicated, or cluster ... we don't have that 'knownledge'. (from the Config after fromYaml, I have no access to the type config and to the password field/setter)

Our redis yaml had a line like :   password: ${redis.password}
And it was using the env variable setup at boot of container, but now we are moving away from env variable (security risk ...). 
The only way I found after looking at redisson code is to do a System.setProperty("redis.password",springbootenvvalue) before doing the config.fromYaml call.

**Comment by mrniko** [comment]
@CyrilDevOps 

Redisson allows to specify environmental variables in config. https://github.com/redisson/redisson/wiki/2.-Configuration#221-yaml-file-based-configuration
