### ISSUE TITLE
Connection leak when redis cluster has "127.0.0.1" in its node list.

### ISSUE THREAD

**Issue by babbottscott** [redisson/redisson#3400]
**Expected behavior**
An exception in adding a cluster member connection should not result in a connection leak

**Actual behavior**
Our redis cluster had two nodes which had configured themselves as "127.0.0.1:6379" in the cluster configuration.  Upon connecting two this cluster, redisson properly threw exception
```
org.redisson.client.RedisConnectionException: Unable to connect to Redis server: /127.0.0.1:6379
```
Later in the logs we find, repeatedly
```
Can't connect to master: redis://127.0.0.1:6379 with slot ranges: [[0-5461]]
```
Each of these subsequent attempts appear to leave a new connection open to the redis node from which redisson is gathering `cluster nodes` information.  Over the course of ~2h, this used the remainder of that redis node's 10k connection limit.

**Steps to reproduce or test case**
I'm not sure how our redis server came to this state originally, but I was able to reproduce by stopping a cluster member, changing the address field in the "myself" line in the cluster config (in our case, /var/lib/redis/redis-6379.conf) from
```172.16.10.11:6379@16379```
to
```127.0.0.1:6379@16379```

**Redis version**
6.0.9

**Redisson version**
3.15.0

**Redisson configuration**
```    @Bean
    fun redissonClient(): RedissonClient {
        val config = Config()
        config.useClusterServers()
            .addNodeAddress("redis://$redisHost")
        config.codec = StringCodec.INSTANCE
        val redisson: RedissonClient = Redisson.create(config)
        val topic: RTopic = redisson.getTopic(testTopic)
        topic.addListener(Any::class.java) { channel, msg ->
            log.info { "$channel - $msg" }
        }
        return redisson
    }
```
Where $redisHost resolves by dns to A records for each node in the redis cluster.

**Comment by mrniko** [comment]
Please try version attached

[redisson-3.15.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/5930452/redisson-3.15.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed

**Comment by mrniko** [comment]
Can you share log output with TRACE logging level for `org.redisson` package?
