### ISSUE TITLE
版本依赖与文档不符

### ISSUE THREAD

**Issue by maxiaodong58** [redisson/redisson#3402]
文档里的依赖描述
![image](https://user-images.githubusercontent.com/28079725/107014247-53b58780-67d6-11eb-9e1a-bf3df4a8f60b.png)

代码里的依赖结果
![image](https://user-images.githubusercontent.com/28079725/107014403-8495bc80-67d6-11eb-900c-76711ed3eb95.png)
![image](https://user-images.githubusercontent.com/28079725/107014421-8a8b9d80-67d6-11eb-8bd3-92087181030e.png)

上面描述的是，24对应Spring Boot 2.4.x，而项目引入的Spring Boot 2.4.1，而下面的却是 redisson-spring-data-23，按照文档应该是redisson-spring-data-24 才对。望改正！

**Comment by mrniko** [comment]
Fixed! Thanks for report
