### ISSUE TITLE
如何使用redisson实现redis list的rpoplpush功能

### ISSUE THREAD

**Issue by sailsgo** [redisson/redisson#3408]
如何使用redisson实现redis list的rpoplpush功能

**Comment by wodahouqi** [comment]
https://github.com/redisson/redisson/wiki/11.-Redis%E5%91%BD%E4%BB%A4%E5%92%8CRedisson%E5%AF%B9%E8%B1%A1%E5%8C%B9%E9%85%8D%E5%88%97%E8%A1%A8
RDeque.pollLastAndOfferFirstTo(), RDeque.pollLastAndOfferFirstToAsync();

**Comment by WangJincheng4869** [comment]
做集合操作，还是springdata香
