### ISSUE TITLE
Redisson api reconverts Stream's linked hash maps into hash maps

### ISSUE THREAD

**Issue by tlamr** [redisson/redisson#3409]
Hi guys!

  thanks a lot for your brilliant product it helped us tremendously. However I believe that we are facing a bug there.

redissonClient.getCommandExecutor().read(name, RedisCommands.XRANGE, name, "-", "+")

returns LinkedHashMap

while 
redissonClient.getStream(name).read(10, new StreamMessageId(0L, 0L));

return HashMap, which is imo wrong.

When using redis streams and XRANGE command, one wants to rely on ordering being exactly the same as ordering on StreamMessageId's.

Would you have some time to check this? 
Thanks,
T

**Comment by mrniko** [comment]
I have checked it with the latest version. 

`redissonClient.getStream(name).read(10, new StreamMessageId(0L, 0L));` returns LinkedHashMap

**Comment by tlamr** [comment]
oh, you are completely right! I though we are on recent version but upgrade to 3.15.0 solved it.
Thanks a lo for your time,
cheers!
T
