### ISSUE TITLE
about addandget API 

### ISSUE THREAD

**Issue by boboanyko** [redisson/redisson#3414]
when i want to use the addandget API,i found the number convert throw a ClassCastException. 
source code:BaseTransactionalMap.java 
``` 
BigDecimal currentValue = BigDecimal.ZERO; 
if (entry != MapEntry.NULL) { 
currentValue = (BigDecimal) entry.getValue(); 
} 
BigDecimal res = currentValue.add(new BigDecimal(value.toString())); 
``` 
the error is on third line 
Can I use new BigDecimal(entry.getValue()) instead?

**Comment by mrniko** [comment]
Did you try to use StringCodec?
