### ISSUE TITLE
Ratomicdouble increases the number of decimal places

### ISSUE THREAD

**Issue by maxiaodong58** [redisson/redisson#3421]
redis version：5.0.9

redisson version：3.15.0

Instance code：
`@RestController
public class TestController {

    @Resource(name = "redisson")
    private RedissonClient redisson;

    @GetMapping("/atomicDouble")
    public void atomicDouble() {
        RAtomicDouble atomicDouble = redisson.getAtomicDouble("test:atomicDouble");
        atomicDouble.set(10.89);
    }

    @GetMapping("/addAtomicDouble")
    public double addAtomicDouble() {
        RAtomicDouble atomicDouble = redisson.getAtomicDouble("test:atomicDouble");
        // 多线程调用该方法，不会造成数据不一致
        return atomicDouble.addAndGet(20.00);
    }
}`

Running results：
![image](https://user-images.githubusercontent.com/28079725/108342261-92efc980-7215-11eb-9e9c-5ced233ded96.png)

**Comment by mrniko** [comment]
This is an issue on Redis side. 

```
2021.02.19 09:29:56.897 TRACE CommandEncoder : channel: [id: 0x45750e67, L:/127.0.0.1:50305 - R:localhost/127.0.0.1:50233] message: *3
$3
SET
$17
test:atomicDouble
$5
10.89

2021.02.19 09:29:56.898 TRACE CommandDecoder : reply: +OK
2021.02.19 09:29:56.898 TRACE CommandEncoder : channel: [id: 0xab285920, L:/127.0.0.1:50300 - R:localhost/127.0.0.1:50233] message: *2
$3
GET
$17
test:atomicDouble

2021.02.19 09:29:56.899 TRACE CommandDecoder : reply: $5
10.89
, channel: [id: 0xab285920, L:/127.0.0.1:50300 - R:localhost/127.0.0.1:50233], command: CommandData 2021.02.19 09:29:56.901 TRACE CommandEncoder : channel: [id: 0x5c82061b, L:/127.0.0.1:50304 - R:localhost/127.0.0.1:50233] message: *3
$11
INCRBYFLOAT
$17
test:atomicDouble
$4
20.0

2021.02.19 09:29:56.901 TRACE CommandDecoder : reply: $20
30.89000000000000057
```

**Comment by maxiaodong58** [comment]
> This is an issue on Redis side.
> 
> ```
> 2021.02.19 09:29:56.897 TRACE CommandEncoder : channel: [id: 0x45750e67, L:/127.0.0.1:50305 - R:localhost/127.0.0.1:50233] message: *3
> $3
> SET
> $17
> test:atomicDouble
> $5
> 10.89
> 
> 2021.02.19 09:29:56.898 TRACE CommandDecoder : reply: +OK
> 2021.02.19 09:29:56.898 TRACE CommandEncoder : channel: [id: 0xab285920, L:/127.0.0.1:50300 - R:localhost/127.0.0.1:50233] message: *2
> $3
> GET
> $17
> test:atomicDouble
> 
> 2021.02.19 09:29:56.899 TRACE CommandDecoder : reply: $5
> 10.89
> , channel: [id: 0xab285920, L:/127.0.0.1:50300 - R:localhost/127.0.0.1:50233], command: CommandData 2021.02.19 09:29:56.901 TRACE CommandEncoder : channel: [id: 0x5c82061b, L:/127.0.0.1:50304 - R:localhost/127.0.0.1:50233] message: *3
> $11
> INCRBYFLOAT
> $17
> test:atomicDouble
> $4
> 20.0
> 
> 2021.02.19 09:29:56.901 TRACE CommandDecoder : reply: $20
> 30.89000000000000057
> ```

Is there a solution?
