### ISSUE TITLE
Cache entries loaded by cache loader are not expired even if TTL is specified

### ISSUE THREAD

**Issue by rchigvintsev** [redisson/redisson#3424]
**Expected behavior**
Cache should respect configured TTL no matter how entry was put in it.

**Actual behavior**
For now if cache loader is configured `RedissonMap` puts loaded entries into cache ignoring specified TTL.

**Steps to reproduce or test case**
Create map cache with some TTL and cache loader, let loader to provide value for some key, wait for TTL and then try to get value from cache again - cache loader won't be used.

**Redis version**
5.0.9

**Redisson version**
3.12.3

**Redisson configuration**
Single Redis instance

**Comment by mrniko** [comment]
Please share code to reproduce the issue.

**Comment by rchigvintsev** [comment]
Sorry for late answer!
Here is a simple example demonstraiting the behaviour described in this issue:

    public static void main(String[] args) throws InterruptedException {
        RedissonClient redisson = Redisson.create();

        try {
            // Let's suppose we want to hold cooked dishes in Redis
            CacheConfig cacheConfig = new CacheConfig();
            // And we do not want to eat spoiled dishes so we configure cache TTL of 3 sec.
            int ttl = 3000;
            cacheConfig.setTTL(ttl);
            MapOptions<String, Dish> mapOptions = MapOptions.<String, Dish>defaults().loader(new Cook());

            RMapCache<String, Dish> cookedDishes = redisson.getMapCache("cooked-dishes", mapOptions);
            cookedDishes.clear();

            // Here we should get fresh-cooked dish
            Dish dish = cookedDishes.get("carrot cake");
            assert !dish.isSpoiled(ttl);

            // This way cache will respect TTL and the assertion below will be passed
            // cache.put("carrot cake", new Dish("carrot cake"));

            // Wait for 5 sec. to be sure that our dish will be stale on next attempt to eat it
            Thread.sleep(5000);

            // Here again we should get fresh-cooked dish but suddenly it is the same dish that we got before
            // and it is already spoiled
            Dish newDish = cookedDishes.get("carrot cake");
            assert !newDish.isSpoiled(ttl);
        } finally {
            redisson.shutdown();
        }
    }

    public static class Dish implements Serializable {
        private final String name;
        private final LocalDateTime cookedAt = LocalDateTime.now();

        public Dish(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public LocalDateTime getCookedAt() {
            return cookedAt;
        }

        public boolean isSpoiled(long timeout) {
            return cookedAt.plus(timeout, ChronoUnit.MILLIS).isBefore(LocalDateTime.now());
        }

        @Override
        public String toString() {
            return name;
        }
    }

    public static class Cook implements MapLoader<String, Dish> {
        private static final Logger log = LoggerFactory.getLogger(Cook.class);

        @Override
        public Dish load(String dishName) {
            log.debug("Cooking a dish \"{}\"", dishName);
            return new Dish((String) dishName);
        }

        @Override
        public Iterable<String> loadAllKeys() {
            return Collections.emptyList();
        }
    }

**Comment by mrniko** [comment]
You need to use value loader of Cache object and not MapCache. Here is a fixed version of your test:

```java
    public static void main(String[] args) throws InterruptedException {
        RedissonClient redisson = Redisson.create();

        redisson.getKeys().flushall();

        try {
            // Let's suppose we want to hold cooked dishes in Redis
            CacheConfig cacheConfig = new CacheConfig();
            // And we do not want to eat spoiled dishes so we configure cache TTL of 3 sec.
            int ttl = 3000;
            cacheConfig.setTTL(ttl);

//            MapOptions<Object, Object> mapOptions = MapOptions.defaults().loader(new Cook());
            RMapCache<Object, Object> mapCache = redisson.getMapCache("cooked-dishes", MapOptions.defaults());
            RedissonCache cookedDishes = new RedissonCache(mapCache, cacheConfig, false);
            cookedDishes.clear();

            String dishName = "carrot-cake";

            //  Here we should get fresh-cooked dish
            Dish dish = (Dish) cookedDishes.get(dishName, new Callable<Dish>() {
                private final Logger log = LoggerFactory.getLogger(Cook.class);
                @Override
                public Dish call() throws Exception {
                    log.info("Cooking a dish \"{}\"", dishName);
                    return new Dish((String) dishName);
                }
            });
            assert !dish.isSpoiled(ttl);

            // This way cache will respect TTL and the assertion below will be passed
            // cookedDishes.put(dishName, new Dish(dishName));

            // Wait for 5 sec. to be sure that our dish will be stale on next attempt to eat it
            Thread.sleep(5000);

            // Here again we should get fresh-cooked dish but suddenly it is the same dish that we got before
            // and it is already spoiled
            Dish newDish = (Dish) cookedDishes.get(dishName, new Callable<Dish>() {
                private final Logger log = LoggerFactory.getLogger(Cook.class);
                @Override
                public Dish call() throws Exception {
                    log.info("Cooking a dish \"{}\"", dishName);
                    return new Dish((String) dishName);
                }
            });
            System.out.println(!newDish.isSpoiled(ttl));
            assert !newDish.isSpoiled(ttl);
        } finally {
            redisson.shutdown();
        }
    }
```

**Comment by rchigvintsev** [comment]
@mrniko Thanks for clarification! Although I understand the design decisions it is still quite inconvenient to use `Callable` every time you want to get missing value from cache. Finally I had to create a cache wrapper that delegates to `get(key, valueLoader)` on calling of `get(key)` method.
