### ISSUE TITLE
Redisson as L2 Hibernate cache in Spring-boot app in CloudFoundry

### ISSUE THREAD

**Issue by kanteshkm** [redisson/redisson#3427]
We are developing a micro-service in spring-boot, which would be deployed in cloud foundry , we want to use redisson as l2 hibernate cache, problem is RedissonRegionFactory expects Config from redisson.json/yaml file,  and
we cannot have file in class path, is it possible read credential from vcap services ? or make redisson-hibernate spring compatible so that we can inject properties to RedissonRegionFactory.

we planning to use redisson as regular cache as well hibernernate l2 cache, please let me know is redisson is suitable for my use-case.

i tried extending the class RedissonRegionFactory and overrite createRedissonClient method to inject vcap peroperties in Config object but before spring creates beans hibernate trying to instantiate RedissonRegionFactory (i could be wrong).

**Comment by mrniko** [comment]
If we talking about Hibernate 5.3+ it's invokes `createRedissonClient` method during `RedissonRegionFactory.start()` method invocation. So `createRedissonClient` method overriding is the only solution here.
