### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! and currentCommand=null

### ISSUE THREAD

**Issue by animjain** [redisson/redisson#3440]
Redisson Version - `3.13.0`

We are noticing following exceptions in our logs and then thread just get hung post that:

org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://*******.cache.windows.net:6380], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@731645844 [redisClient=[addr=rediss://*******.cache.windows.net:6380], channel=[id: 0xe75c7a48, L:/10.113.16.121:38828 - R:*******.cache.windows.net/10.11.12.218:6380], currentCommand=null], command: null, params: null after 3 retry attempts

org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezed=false, freezeReason=null, client=[addr=rediss://*******.cache.windows.net:6380], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@2103578268 [redisClient=[addr=rediss://*******.cache.windows.net:6380], channel=[id: 0x237ae205, L:/10.113.16.121:38756 - R:*******.cache.windows.net/10.11.12.218:6380], currentCommand=null], command: null, params: null after 3 retry attempts

PS - masked the complete addr.

We are using RLock's following implementation to acquire the lock:
```rlock.tryLock(1, 600, TimeUnit.SECONDS)```

The config we are using is default config
```val config = new Config()

      config.useSingleServer()
        .setAddress(s"${REDIS_PROTOCOL}://${REDIS_HOST}:${REDIS_PORT}")
        .setPassword(REDIS_PASSWORD)
```

Trying to understand what is causing this? Especially what does it mean - `currentCommand=null`

**Comment by mrniko** [comment]
Is RLock the only object you use? Do you use async/rx/reactive interfaces?

**Comment by animjain** [comment]
As of now, we use only RLock.

**Comment by mrniko** [comment]
I need more information. Is possible to record session with https://jdk.java.net/jmc/7 and share it?

**Comment by animjain** [comment]
Currently, we are noticing this issue is staging env only. Will see if it can be reproduced locally. However any leads on what can cause this so that we can look parallel into the same? Also, why are we seeing `currentCommand=null` ?

**Comment by mrniko** [comment]
`command=null` might be in batch request used by lock.

**Comment by animjain** [comment]
we are simply trying to acquire the lock as follows:

```rlock.tryLock(1, 600, TimeUnit.SECONDS)```

Due to the above exceptions, the thread gets stuck forever and this exception is never thrown back, and we need to manually restart our service. This is kind of happening probably every 2-3 days now. 

Any suggestions? OTW we might have to move away from Radisson as manual restart is the only way as of now to get rid of this exception.

**Comment by mrniko** [comment]
try to set `pingConnectionInterval` setting

**Comment by animjain** [comment]
And what should be the conf value to try to start with?

**Comment by mrniko** [comment]
30000
