### ISSUE TITLE
RScheduledExecutorService's  WorkerOptions.workers() doesn't work

### ISSUE THREAD

**Issue by poppinlr** [redisson/redisson#3441]
public void executorService(int index) {
        WorkerOptions options = WorkerOptions.defaults()
                .workers(5)
                .taskTimeout(10, TimeUnit.SECONDS);

        RScheduledExecutorService executorService = redissonClient.getExecutorService("index1" + index);
        executorService.registerWorkers(options);
        executorService.submit(new RunnableTask());
    }

```

@Log4j2
public class RunnableTask implements Callable<Long>, Serializable {

    @Override
    public Long call() throws Exception {
        try {
            Thread.sleep(5000);
            log.info("hi");
            return 1L;
        } catch (InterruptedException e) {
            log.error("sleep InterruptedException", e);
            return -1L;
        }
    }
}
```

and i found it will consume 16 thread once instead of 5 
![image](https://user-images.githubusercontent.com/8326338/109277062-c227bb80-7851-11eb-9dda-d070e826bae8.png)

**Comment by mrniko** [comment]
Each worker polls a task from head of Redis queue in order it requested it. It's not a thread. Default ExecutorService is used for task execution if other wasn't defined through WorkerOptions. Threads amount of default ExecutorService defined by `threads` setting.

**Comment by poppinlr** [comment]
> Each worker polls a task from head of Redis queue in order it requested it. It's not a thread. Default ExecutorService is used for task execution if other wasn't defined through WorkerOptions. Threads amount of default ExecutorService defined by `threads` setting.

the `threads` is defined in the config file, is it not possible to customize thread number for each `name`?
```
    public void executorService(int index) {
        WorkerOptions options = WorkerOptions.defaults()
                .taskTimeout(10, TimeUnit.SECONDS);

        redissonClient.getConfig()
                .setThreads(2);

        RScheduledExecutorService executorService = redissonClient.getExecutorService("index1" + index);
        executorService.registerWorkers(options);
        executorService.submit(new RunnableTask());
        executorService.shutdown();
    }

I set the thread but it doesn't work

**Comment by mrniko** [comment]
> I set the thread but it doesn't work

Unable to reproduce. `threads` setting limits default executorService threads amount.

**Comment by mrniko** [comment]
>  is it not possible to customize thread number for each name?

You need to define own `executorService` in `WorkerOptions`

**Comment by poppinlr** [comment]
> > is it not possible to customize thread number for each name?
> 
> You need to define own `executorService` in `WorkerOptions`
```
    public void executorService(int index) {
        WorkerOptions options = WorkerOptions.defaults()
                .taskTimeout(10, TimeUnit.SECONDS)
                .executorService(Executors.newSingleThreadExecutor());

        RScheduledExecutorService executorService = redissonClient.getExecutorService("index2" + index);
        executorService.registerWorkers(options);
        executorService.submit(new RunnableTask());
    }
```

define like this makes the threads more than 16 
I try to define the RedissonClient and make the thread pool success
but if I have 2 server and each server have a RedissonClient bean it will also makes the thread more than 5 
```
    @Bean(destroyMethod = "shutdown")
    public RedissonClient redisson() throws IOException {
        Config config = new Config();
        config.useSingleServer().setAddress("redis://127.0.0.1:6379");
        config.setExecutor(Executors.newFixedThreadPool(5));
        return Redisson.create(config);
    }

**Comment by mrniko** [comment]
> define like this makes the threads more than 16

Default Redisson's ExecutorService has 16 threads.

> but if I have 2 server and each server have a RedissonClient bean it will also makes the thread more than 5

How many?
