### ISSUE TITLE
How can i disable Reddison auto configuration ? There is a test environment where we dont want redis.

### ISSUE THREAD

**Issue by sumitsonkhla** [redisson/redisson#3443]
Spring boot app does not start as we dont have cache in test env.

**Comment by sumitsonkhla** [comment]
> It sounds more like a Spring question than a Redisson one.
> Have you tried using [Spring profiles](https://docs.spring.io/spring-boot/docs/1.2.0.M1/reference/html/boot-features-profiles.html)?

Not sure i can use profile in this case. This autoconfiguration is part of reddiosn starter dependency. There is no way of overriding it .This did not work for me. It is able to exclude only RedisAutoConfiguration i guess.
@SpringBootApplication(exclude = { RedissonAutoConfiguration.class, RedisAutoConfiguration.class })
Mentioned earlier here as well.
https://github.com/redisson/redisson/issues/3165

**Comment by mrniko** [comment]
@sumitsonkhla 
I think your solution is the only way to disable it.
