### ISSUE TITLE
Command still hasn't been written into connection

### ISSUE THREAD

**Issue by danielsuter** [redisson/redisson#3448]
We started receiving the following error multiple times:

> org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase nettyThreads setting. Payload size in bytes: 2832. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1079734857 [redisClient=[addr=redis://redis-x.x.svc.cluster.local:6379], channel=[id: 0xb44bed84, L:/100.67.6.118:34388 - R:rx.svc.cluster.local/172.30.155.10:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2752e551(failure: java.util.concurrent.CancellationException)], command=(PEXPIRE), params=[SUFFIX/d376fe68-4cdf-4fd8-9528-10fae39c695a, 345600000], codec=org.redisson.client.codec.StringCodec]], command: (SET), params: [SUFFIX/40f09edc-7c11-4b5c-a8c3-99c7db33721d, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2832, cap: 4096)] after 3 retry attempts

We do not use the async API. We got the same error for successive commands.

        String redisKey = createKey(cache, key);
        RBucket<Object> bucket = client.getBucket(redisKey);
        bucket.set(value);
        // It's crucial that set comes before expire, otherwise it will not work
        boolean success = bucket.expire(cache.getRetentionInDays(), TimeUnit.DAYS);

Isn't this API blocking and how can we avoid such exceptions?

**Comment by mrniko** [comment]
Please record session with https://jdk.java.net/jmc/7/ and share it.

**Comment by danielsuter** [comment]
Thanks for your answer but that's not possible. It's a productive system where I can't connect to and the error does not always appear. Is my assumption wrong, that set and expire are synchronous and blocking?

**Comment by mrniko** [comment]
Yes, these methods are blocking

**Comment by danielsuter** [comment]
If you look at the stacktrace it seems that it runs in a different thread. So even if the #set command returns it does not mean, that the commands have been sent to the Redis server, correct?

	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:205)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mrniko** [comment]
I'm afraid you're mistaken here since it's always filled out with a result or exception.

**Comment by danielsuter** [comment]
You're of course right. I looked through the code.

The reason I'm asking is that we have a strange situation. We saw the above errors and had an incosistent behaviour. We wrote our state to a RBucket using set. Then we got another request on our backend on the same instance (JVM) which already returned this new state. Afterwards we got another request on a different instance (JVM) which returned the "old" state which makes sense, because Redisson could not write if I interpret the error correctly.
Is there some caching layer within Redisson?

**Comment by mrniko** [comment]
Are you taking into account master-slave replication lag?

**Comment by danielsuter** [comment]
We're using a single node, so this shouldn't be an issue. I also checked if it has been restarted but it has not. Thank you for you fast answers. I'll continue investigating. It only happened once so far but it exactly correlates with the timeout exception.

**Comment by mrniko** [comment]
which Redis vendor do you use?

**Comment by danielsuter** [comment]
We're running Redis on Openshift using the rhel8/redis-5 image.

**Comment by mrniko** [comment]
Did you resolve the issue?

**Comment by danielsuter** [comment]
Unfortunately not but it did not happen again.

**Comment by mrniko** [comment]
I'm closing this for now.
