### ISSUE TITLE
RMap put method return null

### ISSUE THREAD

**Issue by maxiaodong58** [redisson/redisson#3449]
![image](https://user-images.githubusercontent.com/28079725/109957748-572e2700-7d20-11eb-9c2b-9aaf82bc14a1.png)

version：3.15.0

**Comment by mrniko** [comment]
it means that there is no previous value

**Comment by maxiaodong58** [comment]
> it means that there is no previous value

I thought it was to return the current inserted value

**Comment by maxiaodong58** [comment]
If the developer wants to get the old value, he can get it first and then decide whether to put it or not, instead of looking at the old value after putting it.

**Comment by mrniko** [comment]
This is behavior of Map.put() method. It should return previous value.
