### ISSUE TITLE
Command still hasn't been written into connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase nettyThreads setting.

### ISSUE THREAD

**Issue by Exrick** [redisson/redisson#3450]
Exception：
- Command still hasn't been written into connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1499434010 [redisClient=[addr=redis://IP:6379], channel=[id: 0xc449f4ae, L:/172.27.0.11:49048 - R:/IP:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@41262085(failure: java.util.concurrent.CancellationException)], command=(EVAL), params=[local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, KEY, {KEY}:value, {KEY}:value:859ba508-aed6-4344-bd08-ba742535e81b, {KEY}:permits, {KEY}:permits:859ba508-aed6-4344-bd08-ba742535e81b, 1, 1614912037969, 15411819857297036], codec=org.redisson.client.codec.LongCodec]], command: (EVAL), params: [redis.call('hsetnx', KEYS[1], 'rate', ARGV[1]);redis.call('hsetnx', KEYS[1], 'interval', ARGV[2]);re..., 1, KEY, 30, 1000, 0] after 3 retry attempts

- Caused By these codes:
```java
RRateLimiter rateLimiter = redisson.getRateLimiter(XXX);
rateLimiter.trySetRate(RateType.OVERALL, rate, rateInterval, RateIntervalUnit.MILLISECONDS);
rateLimiter.tryAcquire();
rateLimiter.expireAsync(rateInterval * 2, TimeUnit.MILLISECONDS);
```
- Redisson Version: 3.15.0. And I don't think it occurred in previous version

**Comment by mrniko** [comment]
unable to reproduce. Can you record session with https://jdk.java.net/jmc/7/ and share it?
