### ISSUE TITLE
failedAttempts cannot be set zero

### ISSUE THREAD

**Issue by luckywzy** [redisson/redisson#3451]
**Expected behavior**
if failed no Attempts
**Actual behavior**
create redis connect error.
error mesage :Unable to init enough connections amount! Only " + 0 + " from " + 10 + " were initialized
when I read code I found maybe problem appear at org.redisson.connection.pool.ConnectionPool#tryAcquireConnection method.
this compare statement  `entry.getFailedAttempts() < config.getFailedAttempts()` is always true , so connect cannot create success. 
**Steps to reproduce or test case**
**Redis version**
redis-client version is 1.2.2.15-RELEASE
**Redisson version**
3.6.0
**Redisson configuration**

 ```
Config config = new Config();
            config.useSingleServer()
                    .setAddress(new StringBuilder().append("redis://").append(redisUrl).toString())
                    .setFailedAttempts(1)
                    .setConnectTimeout(300)
                    .setRetryAttempts(0)
                    .setTimeout(500);

 redisson = (Redisson) Redisson.create(config);
```

**Comment by mrniko** [comment]
fixed in 3.11.3 version
