### ISSUE TITLE
3.15.1 sentinel execute auth error

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#3453]
update to 3.15.1, run in sentinel model,throw 

2021-03-05 18:12:58.612  ERROR 10479  --- "redisson-netty-2-17" "SentinelConnectionManager.java:322" "org.redisson.connection.SentinelConnectionManager" : "Can't update cluster state"##
org.redisson.client.RedisException: ERR unknown command 'AUTH'. channel: [id: 0xda3d7f5d, L:/192.168.12.114:54379 - R:/192.168.1.21:26379] command: (AUTH), params: (password masked)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:345) ~[redisson-3.15.1.jar:3.15.1]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:177) ~[redisson-3.15.1.jar:3.15.1]

i trace the code,find in MasterSlaveConnectionManager.connectToNode() will createClient(NodeType.MASTER)
but in 3.14.1, MasterSlaveConnectionManager.connectToNode() method called by SentinelConnectionManager.checkState,will pass a RedisClient by createClient(NodeType.SENTINEL)

i think it's a bug
commit info is
55502492ef1769347409667c6fc71d0a7da0c1ec [55502492e]
父级：
42313bab53
作者：
Nikita Koksharov <nkoksharov@redisson.pro>
日期：
2021年2月26日 GMT+8 15:34:49

**Comment by mrniko** [comment]
can you share redisson config?

**Comment by mrniko** [comment]
Please try attached 
[redisson-3.15.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6090356/redisson-3.15.2-SNAPSHOT.jar.zip)
version

**Comment by mrniko** [comment]
this error only appears when `sentinelPassword` is defined

**Comment by mikawudi** [comment]
i sure i  don‘t set sentinelPassword
and i use the last master branch
![bugreport](https://user-images.githubusercontent.com/8215006/110262571-1586d000-7fef-11eb-9b4a-61aac021335c.png)

**Comment by mrniko** [comment]
did you try version attached?

**Comment by mikawudi** [comment]
3.15.0 is fine,
3.15.1 and later, this error is appear

**Comment by mrniko** [comment]
I made some changes, but they aren't in branch yet. Did you try this version?

https://github.com/redisson/redisson/files/6090356/redisson-3.15.2-SNAPSHOT.jar.zip

**Comment by mikawudi** [comment]
i think the bug is import from this commit https://github.com/redisson/redisson/commit/55502492ef1769347409667c6fc71d0a7da0c1ec

![bugrepo](https://user-images.githubusercontent.com/8215006/110300130-7d5e0a80-8031-11eb-8409-13e49ee5b4d8.png)

this client is create by createClient(NodeType.SENTINEL),but when code change it use createClient(NodeType.MASTER)

**Comment by mrniko** [comment]
it's fixed in version I attached to the last comment

**Comment by mikawudi** [comment]
ok~ i wii test  it

**Comment by mikawudi** [comment]
i tested, it fixed ~ thanks~

**Comment by mrniko** [comment]
Fixed
