### ISSUE TITLE
How Redisson's DelayQueue offer same element as one element？

### ISSUE THREAD

**Issue by hehuang139** [redisson/redisson#3459]
As far as I know, Redisson implements delayQueue through zset and list,zset will not add repeatedly for the same member

127.0.0.1:6379> zadd myzset  1 mykey
(integer) 1
127.0.0.1:6379> zadd myzset  2 mykey
(integer) 0
127.0.0.1:6379> zcard myzset
(integer) 1

Below is my code：
`import junit.framework.TestCase;
import org.junit.Test;
import org.redisson.Redisson;
import org.redisson.api.RBlockingQueue;
import org.redisson.api.RDelayedQueue;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;

import java.util.concurrent.TimeUnit;

public class RedissonTest extends TestCase {

    private RedissonClient redisson;

    protected void init() {
        // connects to 127.0.0.1:6379 by default
//        RedissonClient redisson = Redisson.create();

        Config config = new Config();
        config.useSingleServer().setAddress("redis://localhost:6379");
        redisson = Redisson.create(config);
    }

    @Test
    public void testDelayedQueue() throws InterruptedException {
        init();
        RBlockingQueue<String> distinationQueue = redisson.getBlockingQueue("redisson-blocking-test");
        RDelayedQueue<String> delayedQueue = redisson.getDelayedQueue(distinationQueue);
        // move object to distinationQueue in 10 seconds
        delayedQueue.offer("msg1", 13, TimeUnit.HOURS);
        // move object to distinationQueue in 1 minutes
        delayedQueue.offer("msg1", 40, TimeUnit.HOURS);
    }

}`

but there has two elements:
127.0.0.1:6379> keys *
1) "myzset"
2) "redisson_delay_queue:{redisson-blocking-test}"
3) "redisson_delay_queue_timeout:{redission-blocking}"
4) "redission-blocking"
5) "redisson_delay_queue:{redisson-blocking}"
6) "redisson_delay_queue:{redission-blocking}"
7) "redisson_delay_queue_timeout:{redisson-blocking}"
8) "redisson_delay_queue_timeout:{redisson-blocking-test}"
127.0.0.1:6379> zcard redisson_delay_queue_timeout:{redisson-blocking-test}
(integer) 2
127.0.0.1:6379> ZRANGEBYSCORE redisson_delay_queue_timeout:{redisson-blocking-test} -inf +inf
1) "\x0e\xb2\xb6!F[\xd9C\a\x00\x00\x00\x00\x00\x00\x00\x04>\x04msg1"
2) "NH\xef\x7f\x16\xb8\xb2\xc3\a\x00\x00\x00\x00\x00\x00\x00\x04>\x04msg1"

how can i tell redisson they are same member

Thank you for help me!

**Comment by mrniko** [comment]
Queue object allows to keep duplicated elements. So this is expected behaviour
