### ISSUE TITLE
Redisson does not reconnect after failed DNS Monitor change

### ISSUE THREAD

**Issue by ldap4life** [redisson/redisson#3460]
Editing and repurposing this issue after finding the underlying cause. Originally this issue was to improve the error messaging. The underlying problem is a failure to reconnect after a failed DNS change. After this scenario plays out, there are no connections in the pool, and the error message we end up seeing is an ArrayIndexOutOfBoundsException

**Expected behavior**
Reconnection to redis node

**Actual behavior**
after DNS monitor detects a change to an ip it cant reach, subsequent dns change to a good ip does not restore connections.

**Steps to reproduce or test case**
1. connect to a single redis master node
2. add a host file entry for some bogus ip address,
3. watch redis connection failures
4. remove the bogus host file entry, so that DNS monitor gets the good ip address again
5. re connection does not happen

**Redis version**
azure cache for redis 4.0.14

**Redisson version**
3.14.0

**Comment by mrniko** [comment]
please share full stack trace of ArrayIndexOutOfBoundsException

**Comment by ldap4life** [comment]
Tested some more, discovered some difficulty triggering the DNS change via hosts file. Found some workarounds though. This time, redisson did reconnect after i switched my dns back to the good IP. It may have been that there was some DNS caching issue that continually gave the bad IP, i cant say for sure. Anyways, attached are logs after reproducing. In the middle you will see the arrayindexoutofbounds. Redisson configuration is spring-boot default, only hostname and password defined.

[dnschangeredis.log](https://github.com/redisson/redisson/files/6116940/dnschangeredis.log)

**Comment by mrniko** [comment]
> discovered some difficulty triggering the DNS change via hosts file

It's a bad practice, since these entries are cached by netty resolver. Try to use mara dns instead.
