### ISSUE TITLE
Can we set a local cache size for RSetMultimapCache?

### ISSUE THREAD

**Issue by luxe** [redisson/redisson#3461]
Is there a way to set an upper limit on the number of elements that are kept in the local cache?  I don't see a way to do this and our TTLs are very long.  I don't see a way to clear the local cache ourselves either.  Containers like `RLocalCachedMap` have `clearLocalCache()`, but `RSetMultimapCache` does not.
Thanks!

**Comment by mrniko** [comment]
RSetMultimapCache doesn't support local cache feature
