### ISSUE TITLE
Is there a simple way to change node address dynamically?

### ISSUE THREAD

**Issue by catxu** [redisson/redisson#3462]
I try to use redisson(3.7.0) as my redis cluster client, and I need to change the connection address of redisson dynamically, in Spring environment, is there a simple way to do that? Does it need to consider the instance with old connection's recycle?

I tried to get the redisson instance directly and update the node information of its config like:

```java
Redisson redisson = ctx.getBean("redisson");
Config conf = redisson.getConfig();
conf.useClusterServers().getNodeAddresses().clear();
conf.useClusterServers().addNodeAddress("new-address");
```

but it failed(it could work sometimes).

**Comment by mrniko** [comment]
dynamic change of configuration is not supported
