### ISSUE TITLE
Fallback failing for Hibernate-5.2 - nextTimestamp() doesn't have a try-catch

### ISSUE THREAD

**Issue by dkelkhoff** [redisson/redisson#3467]
**Expected behavior**
With an application server up and using redis, and hibernate.cache.redisson.fallback=true, I should be able to kill redis, and continue to use my application server.  

**Actual behavior**
Hibernate+Redisson becomes unusable as soon as redis becomes unavailable - with failures coming from the nextTimestamp method in ~~BaseRegion~~ RedissonRegionFactory.

**Steps to reproduce or test case**
1. Configure hibernate L2 cache with redisson.
2. start application server with redis online
3. stop redis
4. try to use application (hibernate calls) - get errors. 

**Redis version**
redis:latest from docker hub.

**Redisson version**
3.15.0

**Redisson configuration**
redisson.yaml
``` 
singleServerConfig:
  address: "redis://127.0.0.1:6379"
```

persistence.xml
``` 
            <property name="hibernate.cache.use_second_level_cache" value="true"/>
            <property name="hibernate.cache.redisson.config" value="/redisson.yaml" />
            <property name="hibernate.cache.redisson.fallback" value="true" />
```

Entity classes:
```
@Cacheable()
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
```

**Comment by dkelkhoff** [comment]
Comparing the [patch that was made to support fallback for hibernate 5.3](https://github.com/redisson/redisson/commit/be8eccb7008bde5d96246aeb280bd70cb46eb806), I'm seeing that there's no try-catch in the nextTimestamp method in 5.2's BaseRegion class.  

I can attempt to add this myself and submit a PR, if that would be helpful?

**Comment by mrniko** [comment]
Fixed
