### ISSUE TITLE
What's the reason for using a single pub/sub topic in tomcat RedissonSessionManager?

### ISSUE THREAD

**Issue by ilcapatina** [redisson/redisson#3469]
Hi,

We are currently using Redisson 3.13.6 for session management of a java web application deployed in tomcat 7 and sessions stored in ElastiCache. 
RedissonSessionManager is configured with readMode=MEMORY and updateMode=AFTER_REQUEST (due to the way the app is implemented this is the only configuration working for us).

We noticed high network outbound traffic on a single ElastiCache node, followed by CLUSTERDOWN errors because of bandwidth throttling.

I checked the implementation and found that RedissonSessionManager is implemented to use a single topic for pub/sub communication - https://github.com/redisson/redisson/blob/master/redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java#L153

Is there a reason for using a single topic? 
Is it ok to update the implementation to create multiple topics, and use a balancer when accessing them from  RedissonSession?

I understand that the Redis slot is computed based on the topic name, so choosing the name for the topics in such a way that they will end up on different nodes is not that straightforward, but I am interested if there is another reason this approach might not work.

Thanks,
Ilie

P.S. The quick fix was to upgrade the ElastiCache node type to accommodate the traffic, but it's not ideal because of the price of the new instances and because the nodes not handling the pub/sub topic are not using these resources.

**Comment by mrniko** [comment]
Redisson PRO provides `RedissonClusteredSessionManager` to handle this case.

**Comment by ilcapatina** [comment]
Thank you for your reply.
