### ISSUE TITLE
Why redisson lock implements use WAIT command

### ISSUE THREAD

**Issue by deanisty** [redisson/redisson#3474]
I am using redisson lock in my project, but the redis cluster i use in product env forbidden to use WAIT command, so the redisson lock alway ends up to and RedisException with message " wait command not found", I try every lock implements in redisson, all the same, so what should i do to fix this ? change anothe redis or write a lock by myselft ?

**Comment by mrniko** [comment]
wait is used to sync lock state with slaves and increase lock durability. With this feature RedLock isn't needed anymore.

**Comment by deanisty** [comment]
> wait is used to sync lock state with slaves and increase lock durability. With this feature RedLock isn't needed anymore.

So, does "**wait**" command will slow down redis in some circumstance, thus my cloud redis service provider not allow to use "wait" in **cluster** model.

**Comment by mrniko** [comment]
yes, it can. I'm afraid I can't change this behavior due to incomplete implementation of Redis protocol by one vendor.
