### ISSUE TITLE
RedisTimeoutException : Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings

### ISSUE THREAD

**Issue by ck-jesse** [redisson/redisson#3479]
org.redisson.client.RedisTimeoutException : Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=31, freeConnectionsCounter=value:299:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xx.redis.rds.aliyuncs.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@2008593702 [redisClient=[addr=redis://xx.redis.rds.aliyuncs.com:6379], channel=[id: 0x0c40332e, L:/10.11.133.0:49268 - R:xx.redis.rds.aliyuncs.com/xxip:6379], currentCommand=null], command: null, params: null after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:200)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Redisson version: 3.13.0

This problem will appear after every downgrade of redis cluster. Restarting the application can solve this problem at present.
However, how to solve the problem thoroughly?

More information :
1. Examples Code

    RBatch batch = redissonClient.createBatch();
    keyList.forEach((key) -> {
        batch.getBucket(key).getAsync().onComplete((value, exception) -> {
            if (exception == null && null !=value) {
                // Just put the value to map
            }
        });
    });
    batch.execute();

2.Examples redisson.yaml

singleServerConfig:
  address: xxx
  password: xxx
  idleConnectionTimeout: 10000
  connectTimeout: 1000
  timeout: 1000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  clientName: null
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 16
  connectionMinimumIdleSize: 100
  connectionPoolSize: 64
  database: 0
threads: 8
nettyThreads: 32

**Comment by mrniko** [comment]
I need a session recorded with https://jdk.java.net/jmc/7

**Comment by ck-jesse** [comment]
> I need a session recorded with https://jdk.java.net/jmc/7

I changed the code to sample code, Please take another look, Thanks.

**Comment by mrniko** [comment]
You use sync method in async callback. This causes such error. 3.15.1 version has protection against this.

**Comment by ck-jesse** [comment]
> You use sync method in async callback. This causes such error. 3.15.1 version has protection against this.

You mean the following code is sync method?  

if (exception == null && !ObjectUtils.isEmpty(value)) {
      // Just put value to map
 }

And, Is there any solution?

**Comment by mrniko** [comment]
do you use Redisson map to put value?

**Comment by ck-jesse** [comment]
In batch operate, I want to maping key and value to a map, and then return map.
Is there a good way to deal with this kind of scene?

**Comment by mrniko** [comment]
> // Just put value to map

Which type map object do you use here?

**Comment by ck-jesse** [comment]
> do you use Redisson map to put value?

It means RMap? 

The hash type of redis has a big key problem, So I changed to string

**Comment by ck-jesse** [comment]
> > // Just put value to map
> 
> Which type map object do you use here?


Map<String, T> resultMap = new ConcurrentHashMap();
resultMap.put(key, value);

**Comment by mrniko** [comment]
Unable to reproduce it. Can you record session with https://jdk.java.net/jmc/7?

**Comment by mrniko** [comment]
try to set `pingConnectionInterval = 5000`

**Comment by ck-jesse** [comment]
> try to set `pingConnectionInterval = 5000`

Does pingconnectioninterval affect performance?

**Comment by ck-jesse** [comment]
> > try to set `pingConnectionInterval = 5000`
> 
> Does pingconnectioninterval affect performance?

set `pingConnectionInterval = 5000` , the purpose  is to check if the connection is alive?

**Comment by ck-jesse** [comment]
> try to set `pingConnectionInterval = 5000`

set pingConnectionInterval = 5000 , the purpose is to check if the connection is alive?
Does pingconnectioninterval affect performance?

**Comment by mrniko** [comment]
> set pingConnectionInterval = 5000 , the purpose is to check if the connection is alive?

Yes.

> Does pingconnectioninterval affect performance?

Depends on connections amount you have

**Comment by ck-jesse** [comment]
> > set pingConnectionInterval = 5000 , the purpose is to check if the connection is alive?
> 
> Yes.
> 
> > Does pingconnectioninterval affect performance?
> 
> Depends on connections amount you have

OK, I'll try, Thanks.
