### ISSUE TITLE
There may be concurrency problems in org.redisson.RedissonLock#tryLockInnerAsync

### ISSUE THREAD

**Issue by coding-tortoise** [redisson/redisson#3484]
tryLockInnerAsync(long waitTime, long leaseTime, TimeUnit unit, long threadId, RedisStrictCommand<T> command) {
        
        internalLockLeaseTime = unit.toMillis(leaseTime);  

> **if two thread get the same lock subject and run the method at same time, one's leaseTime is -1, and another's leaseTime is bigger than 30, the "-1" thread first cam in and set internalLockLeaseTime, then another thread came in set the internalLockLeaseTime bigger than 30, then if the bigger leaseTime one get the real redis lock! It while cause watchDog invaild and the lock be expired ahead of time**

        return evalWriteAsync(getName(), LongCodec.INSTANCE, command,
                "if (redis.call('exists', KEYS[1]) == 0) then " +
                        "redis.call('hincrby', KEYS[1], ARGV[2], 1); " +
                        "redis.call('pexpire', KEYS[1], ARGV[1]); " +
                        "return nil; " +
                        "end; " +
                        "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then " +
                        "redis.call('hincrby', KEYS[1], ARGV[2], 1); " +
                        "redis.call('pexpire', KEYS[1], ARGV[1]); " +
                        "return nil; " +
                        "end; " +
                        "return redis.call('pttl', KEYS[1]);",
                Collections.singletonList(getName()), internalLockLeaseTime, getLockName(threadId));
    }

**Comment by coding-tortoise** [comment]
and I think, when the leaseTime is -1, the "tryLockInnerAsync" method's leaseTime param should be fixed 30000 mills and the watchDog's timeout period should also be.

**Comment by mrniko** [comment]
> one's leaseTime is -1, and another's leaseTime is bigger than 30, the "-1" thread first cam in and set internalLockLeaseTime, then another thread came in set the internalLockLeaseTime bigger than 30, then if the bigger leaseTime one get the real redis lock! 

It's impossible since LUA-script updates lock lease time only if it was acquired. Two threads can't acquire at the same time. Only lease time of acquired thread is applied.

**Comment by coding-tortoise** [comment]
what I mean is 'internalLockLeaseTime = unit.toMillis(leaseTime)' and LUA-script is not an atomic operation, internalLockLeaseTime's value may be change by another thread

**Comment by coding-tortoise** [comment]
> > one's leaseTime is -1, and another's leaseTime is bigger than 30, the "-1" thread first cam in and set internalLockLeaseTime, then another thread came in set the internalLockLeaseTime bigger than 30, then if the bigger leaseTime one get the real redis lock!
> 
> It's impossible since LUA-script updates lock lease time only if it was acquired. Two threads can't acquire at the same time. Only lease time of acquired thread is applied.

what I mean is 'internalLockLeaseTime = unit.toMillis(leaseTime)' and LUA-script is not an atomic operation, internalLockLeaseTime's value may be change by another thread

**Comment by mrniko** [comment]
Thank you for explanation. I commented your changes

**Comment by coding-tortoise** [comment]
> Thank you for explanation. I commented your changes

Modified according to the specification,  and I think, when the leaseTime is -1, the "tryLockInnerAsync" method's leaseTime param should be fixed 30s and the watchDog's timeout period should also be. what do you think about that?

**Comment by mrniko** [comment]
why it should be fixed to 30s? watchDog timeout controlled by `lockWatchdogTimeout` setting and it's default setting is already 30s.
