### ISSUE TITLE
Abnormal behaviour in redis mapwriter execution

### ISSUE THREAD

**Issue by BhaveshPunjabi** [redisson/redisson#3485]
We have used write behind mode in mapoption,
my code written in write method is executing fine but after some time 
i have observed that i am getting "org.redisson.client.RedisOutOfMemoryException" exception after that my write method of mapwriter is not getting called, 
can yo please help me out in these.

Also observed that after getting any throwable error in write method same behaviour is getting replicate.

**Comment by mrniko** [comment]
RedisOutOfMemoryException means Redis memory is full. Did you check it?

**Comment by mrniko** [comment]
> Also observed that after getting any throwable error in write method same behaviour is getting replicate.

Can you share stacktrace?

**Comment by BhaveshPunjabi** [comment]
com.bmc.ade.saas.tdc.service.data.cache.ConnectorMapWriter.write(ConnectorMapWriter.java:94)
    at org.redisson.MapWriteBehindTask.lambda$null$0(MapWriteBehindTask.java:100)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by BhaveshPunjabi** [comment]
yes i checked memory was getting 100 % utilized

**Comment by mrniko** [comment]
> yes i checked memory was getting 100 % utilized

Redisson stores only data you sent to Redis nothing more. You may try to use compression codecs like SnappyCodec and LZ4
