### ISSUE TITLE
redisson-springboot-starter现在支持从springcloud config/nacos读取配置文件么

### ISSUE THREAD

**Issue by TalkIsCheapGiveMeMoney** [redisson/redisson#3491]
redisson-springboot-starter现在支持从springcloud config/nacos读取配置文件么

**Comment by mrniko** [comment]
yes, since 3.13.5 version. Here is the example https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#2-add-settings-into-applicationsettings-file
