### ISSUE TITLE
with service cluster,a machine have held the lock,another machine will unlock successfully?

### ISSUE THREAD

**Issue by li-shaoke** [redisson/redisson#3492]
the method 'tryAcquireAsync' of RedissonLock class,use current thread IDas redis value.
if two machine have same thread ID,a machine have held the lock,another machine will unlock successfully?
RedissonLock class can use a map to store current application have own Lock,if service reentrant or unlock,
verify that it have the lock before.

**Comment by mrniko** [comment]
> if two machine have same thread ID,a machine have held the lock,another machine will unlock successfully?

No, because every lock owner uses Redisson instance id along with thread id.
