### ISSUE TITLE
Transaction in Redis Live Object Service

### ISSUE THREAD

**Issue by bbartekb** [redisson/redisson#3493]
Hi,

Is it possible to perform transaction on Redis Live Object?
I want write a new instance of MyClass - only if new instance is newer than previous one. 
I need method similar to 'merge' in RMap. 

    @REntity
    public class MyClass {

        @RId
        private String key;

        @RIndex
        public Date createDate;

        @RIndex
        public String externalValue;
     }

So I need to compare dates of old and new objects and then save new object only if it newer. It has be executed in one transaction. In other thread someone can update fields in this object.

**Comment by mrniko** [comment]
Wrap this function with RLock object with name based on object id.

**Comment by bbartekb** [comment]
Thank you for your response!

It works for me with tryLock()

    public void updateLiveObjectEntry(MyClass myObject) {
        RLiveObjectService rLiveObjectService = getRedissonConnection().getClient().getLiveObjectService();
        RLock lock = getRedissonConnection().getClient().getLock(myObject.getKey());

        try {
            lock.tryLock(10, TimeUnit.SECONDS);
            if (myObject.getCreateDate().after(rLiveObjectService.get(MyClass.class, myObject.getKey()).getCreateDate())) {
                rLiveObjectService.merge(myObject);
            }
        } catch (InterruptedException e) {
        } finally {
            lock.unlock();
        }
    }
    
Is my solution correct? 
I think this lock is not connected with my LiveObject, so myObject entry is not locked. It will be work if in all usage I use method updateLiveObjectEntry().

**Comment by mrniko** [comment]
you can use follow lock name: `String lockName = MyClass.class.getName() + ":" + myObject.getKey()`. If you have any doubts about the key uniqueness with different Object classes.

**Comment by bbartekb** [comment]
Ok, thank you.
