### ISSUE TITLE
RetryInterval and "Client Pause" command

### ISSUE THREAD

**Issue by avcad** [redisson/redisson#3494]
Redisson 3.15.1.

I thought of reporting a behavior I see during testing.

If I break connectivity to Redis, retryInterval works as expected, but if I use the CLIENT PAUSE, then 
all retries are done at the same time. retryInterval  is not respected.

Config config = new Config();		
config.useSingleServer().setTimeout( 50 ).setRetryAttempts( 10 ).setRetryInterval( 6000 ).setAddress( "redis://127.0.0.1:6379" );
		
RedissonClient redisson = Redisson.create(config);

// stop with debugger here and run
// redis-cli client pause 60000

System.out.println((new Date()) + " - start");
try {
  redisson.getBucket("bucket").set("value");
} catch ( Exception e ) {
    System.out.println((new Date())  + " - error: " + e.toString());
}
System.out.println((new Date()) + " - end ");

Does 10 attempts but doesn't respect the retry interval of 6000  - fails in the same second

Wed Mar 17 00:39:18 EDT 2021 - start
Wed Mar 17 00:39:19 EDT 2021 - error: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (50 ms) occured after 10 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (SET), params: [bucket, PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 256)], channel: [id: 0xb95d6467, L:/127.0.0.1:50083 - R:/127.0.0.1:6379]
Wed Mar 17 00:39:19 EDT 2021 - end 

If I stop redis then it fails after a minute as expected  ( 10 attempts with 6000  retry interval) 

Wed Mar 17 00:41:32 EDT 2021 - start
Wed Mar 17 00:42:32 EDT 2021 - error: org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@553090556 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x9db03e64, L:0.0.0.0/0.0.0.0:50415], currentCommand=null], command: (SET), params: [bucket, PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 256)] after 10 retry attempts

I don't really use CLIENT PAUSE. I was just trying to simulate latency and noticed this. I reported in case this behavior can impact other/real scenarios

**Comment by mrniko** [comment]
Please try version attached

[redisson-3.15.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6154712/redisson-3.15.2-SNAPSHOT.jar.zip)

**Comment by avcad** [comment]
Hi,

Appears to work. It doesn't come back right away anymore. The message says 
"Command execution timeout for command: (PING)"  - not sure why it shows ping.  It's a SET

Redisson 3.15.1
===============
2021-03-17 11:13:59 INFO org.redisson.Version logVersion Redisson 3.15.1
2021-03-17 11:14:04 INFO org.redisson.connection.pool.ConnectionPool$1 lambda$run$0 1 connections initialized for /127.0.0.1:6379
2021-03-17 11:14:04 INFO org.redisson.connection.pool.ConnectionPool$1 lambda$run$0 24 connections initialized for /127.0.0.1:6379
Wed Mar 17 11:14:23 EDT 2021 - start
Wed Mar 17 11:14:26 EDT 2021 - error: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (200 ms) occured after 10 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (SET), params: [bucket, PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 256)], channel: [id: 0x1c1c61f2, L:/127.0.0.1:50739 - R:/127.0.0.1:6379]
Wed Mar 17 11:14:26 EDT 2021 - end 

Redisson 3.15.2.SNAPSHOT
========================
2021-03-17 11:03:42 INFO org.redisson.Version logVersion Redisson 3.15.2.SNAPSHOT
2021-03-17 11:03:48 INFO org.redisson.connection.pool.ConnectionPool$1 lambda$run$0 1 connections initialized for /127.0.0.1:6379
2021-03-17 11:03:48 INFO org.redisson.connection.pool.ConnectionPool$1 lambda$run$0 24 connections initialized for /127.0.0.1:6379
Wed Mar 17 11:03:56 EDT 2021 - start
Wed Mar 17 11:04:57 EDT 2021 - error: org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@326120563 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x259730cd, L:/127.0.0.1:65373 ! R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@adac35b(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (SET), params: [bucket, PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 256)] after 10 retry attempts
Wed Mar 17 11:04:57 EDT 2021 - end

While my test is running I also get a bunch of these, which is expected
2021-03-17 11:04:48 SEVERE org.redisson.client.handler.PingConnectionHandler$1 run Unable to send PING command over channel: [id: 0xe4483b0a, L:/127.0.0.1:65378 - R:/127.0.0.1:6379]
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6379]

**Comment by mrniko** [comment]
Thanks for help! Fixed
