### ISSUE TITLE
Redisson with AWS IRSA

### ISSUE THREAD

**Issue by imtdeepak** [redisson/redisson#3509]
How can I create redisson client with AWS role based authentication ?

I have used it with redis auth so far but don’t know if I can create redisson if I want to use role based auth.

**Comment by CyrilDevOps** [comment]
Hi, can you point me to the documentation on AWS role based authentification for redis ? 
I didn't know it existed. (I know it only for Aurora).
Thanks

**Comment by imtdeepak** [comment]
Hi,
It’s available with Redis 6 now.
https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-elasticache-redis-support-managed-role-based-access-control/

**Comment by CyrilDevOps** [comment]
it is a user password authentification with the the auth command.
You need to have a username and password defined on your redissonconfig object.
It isn't linked to any 'AWS IAM'.

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.RBAC.html
https://github.com/redisson/redisson/wiki/2.-Configuration#23-common-settings

**Comment by mrniko** [comment]
Which ACL commands do you need to use?

**Comment by mrniko** [comment]
use `username` to define user from ACL

**Comment by imtdeepak** [comment]
Hi,

Managing usernames and passwords becomes tough and has an overhead of rotating them. That's why we want to explore the IRSA way of authenticating it.
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by mrniko** [comment]
@imtdeepak 

Hello,

I assume managing of IRSA available only through AWS API?
