### ISSUE TITLE
redisson用阿里云集群版redis的问题 

### ISSUE THREAD

**Issue by anchuang** [redisson/redisson#3512]
阿里云集群版redis限制了使用EVAL命令。
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. channel

**Comment by mrniko** [comment]
Please contact your Redis vendor to solve the issue.

**Comment by anchuang** [comment]
Okay, thank you
