### ISSUE TITLE
Fixed rate schedules stops after some time

### ISSUE THREAD

**Issue by Vsevolod123** [redisson/redisson#3514]
Hello,

We're using executor service with fixed rate schedules, but the schedules stops after some time.

I've reproduced the issue in a [small standalone project](https://github.com/Vsevolod123/redisson-executor-service-fixed-rate-bug-demo).

**Comment by mrniko** [comment]
use `scheduleWithFixedDelay` as workaround

**Comment by Vsevolod123** [comment]
> use `scheduleWithFixedDelay` as workaround

yes, we're using it now, but fixed delay schedules can't start in parallel

**Comment by mrniko** [comment]
and it shouldn't, it's another bug. You can see the same behavior if you try to use:
```
        ScheduledExecutorService e = Executors.newScheduledThreadPool(10);
        e.scheduleAtFixedRate(task, 1000L, 100L, TimeUnit.MILLISECONDS);
```

**Comment by Vsevolod123** [comment]
> and it shouldn't, it's another bug. You can see the same behavior if you try to use:
> 
> ```
> ScheduledExecutorService e = Executors.newScheduledThreadPool(10);
> e.scheduleAtFixedRate(task, 1000L, 100L, TimeUnit.MILLISECONDS);
> ```

You're right!
Ok, then bug is "fixed rate shouldn't start in parallel", right?

**Comment by mrniko** [comment]
yes

**Comment by mrniko** [comment]
Fixed
