### ISSUE TITLE
addLastIfExistsAsync API in RedissonDeque appending absurd value to the list in redis

### ISSUE THREAD

**Issue by Azkaban153** [redisson/redisson#3519]
**Expected behavior**

rBatch.getDeque(redisKey,StringCodec.INSTANCE).addLastIfExistsAsync(value);

This should append a json string value to the already existing redis list with json strings. The key was created with StringCodec.INSTANCE.

127.0.0.1:7002> lrange redisKey 0 -1
1) "{\"Id\":12345,\"code\":\"ABCD\",\"time\":12345}"
2) "{\"Id\":12346,\"code\":\"ABCE\",\"time\":12346}"

**Actual behavior**

Some absurd value is being appended to the list. No error logs seen regarding command timeout or anything like that.

127.0.0.1:7002> lrange redisKey 0 -1
1) "{\"Id\":12345,\"code\":\"ABCD\",\"time\":12345}"
2) "[PooledUnsafeDirectByteBuf(ridx: 0, widx: 62, cap: 256)]"

**Steps to reproduce or test case**

Insert redis key with : rBatch.getDeque(redisKey,StringCodec.INSTANCE).addAllAsync(values);

Append to the above key with : rBatch.getDeque(redisKey,StringCodec.INSTANCE).addLastIfExistsAsync(value);

**Redis version**

Happening on 5.0.7 as well as 3.0.7

**Redisson version**

3.15.0

**Redisson configuration**

Standard cluster mode configuration

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by Azkaban153** [comment]
> Fixed! Thanks for report

Didn't expect such a swift response and fix 😄 . Thanks a lot!

Any ETA on the next release version?

**Comment by mrniko** [comment]
During next month.
