### ISSUE TITLE
RedissonRateLimiter tryAcquire and availablePermits throw RedisException: too many results to unpack

### ISSUE THREAD

**Issue by haggaimeltzer** [redisson/redisson#3526]
**Expected behavior**
method call should return without exception

**Actual behavior**
A RedisException is thrown:
`org.redisson.client.RedisException: ERR Error running script (call to f_d66032e767a3ea7814ca959c0a81ae0baa165f75): @user_script:1: user_script:1: too many results to unpack . channel: [id: 0xf4ad5dc9, L:/<address> - R:<address>] command: (EVAL), params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, MyRateLimiter_107728585506707301, {MyRateLimiter_107728585506707301}:value, {MyRateLimiter_107728585506707301}:value:b3c4bb40-b4ac-46f8-a6f7-4f8161b4842..., {MyRateLimiter_107728585506707301}:permits, {MyRateLimiter_107728585506707301}:permits:b3c4bb40-b4ac-46f8-a6f7-4f8161b48..., 1, 1617010579119, 606081525...`

**Steps to reproduce or test case**
1. Add more than 8k entries to rate limiter. 
2. Wait for all of them to expire.
3. call availablePermits/tryAcquire.

```
RRateLimiter rateLimiter = redissonClient.getRateLimiter("test");
rateLimiter.setRate(RateType.OVERALL, 10_000, 2, RateIntervalUnit.MINUTES);
for (int i = 0; i < 8_001; i++) {
    rateLimiter.tryAcquire();
}
try {
    Thread.sleep(2*60*1000);
} catch (InterruptedException e) {
    e.printStackTrace();
}
long check = rateLimiter.availablePermits(); //throws the unwanted exception ...
// boolean check = rateLimiter.tryAcquire();  //would also throw the unwanted exception ...
System.out.println("result=" + check);

```

**Redis version**
6.2.1

**Redisson version**
3.14.1

**Redisson configuration**
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 20000
  keepAlive: true
  tcpNoDelay: false
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 2
  connectionPoolSize: 8
  database: 4
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}

**Comment by haggaimeltzer** [comment]
Looks like similar issue was fixed here: https://github.com/redisson/redisson/issues/2014

**Comment by mrniko** [comment]
No, it's a different one. Fixed

**Comment by haggaimeltzer** [comment]
Thanks!
