### ISSUE TITLE
Quarkus integration distributed cache

### ISSUE THREAD

**Issue by mahbodkh** [redisson/redisson#3530]
There isn't any standard way or sample to basic Redisson with Quarkus Integration!
I actually, looking to find a way to handle distributed cache with Redisson. Could you please inform me in this way?

**Comment by mrniko** [comment]
Currently there is no integration with Quarkus.

**Comment by mahbodkh** [comment]
> Currently there is no integration with Quarkus.

how can I manually handle it? because I didn't find any way to load redisson and configure it and connect it to redis.

**Comment by mrniko** [comment]
Done
