### ISSUE TITLE
`RScript.evalShaAsync` prepends additional characters to the first argument. seems to be related to the default `Codec`

### ISSUE THREAD

**Issue by duxing** [redisson/redisson#3535]
Set up:
```
public final CompletionStage<Long> foo(
        String sha,
        String key,
        long expirationSeconds,
        String... elements) {
    String[] keys = {key};
    String[] arguments = new String[elements.length + 1];
    arguments[0] = String.valueOf(expirationSeconds);
    System.arraycopy(elements, 0, arguments, 1, elements.length);

    // calls inside this function are simplified. please ignore redundant allocations / casts.
    Object[] vals = Arrays.copyOf(arguments, arguments.length, Object[].class);

    // RedissonClient client;
    return client
            .getScript()
            .evalShaAsync(RScript.Mode.READ_WRITE, sha, RScript.ReturnType.INTEGER, Arrays.asList(keys), vals);
}
```

where:
 - `sha` is the hash of a loaded script (via `SCRIPT LOAD`) command.
 - `key` is an alphanumeric string. e.g. "123456789"
 - `expirationSeconds` is `3600`
 - `elements` is a single alphanumeric string. e.g. "foobar1234"

the loaded Lua script contains the following lines:
```
if not tonumber(ARGV[1]) then
  return {err="invalid expiration. ARGV[1]="..ARGV[1]}
end
```
in order to parse the expiration.

**Expected behavior**
the `if` check in LUA script should not trigger an error.

**Actual behavior**
script returned error and from the error message `ARGV[1]` is set to `> 3600` with possible whitespace characters (stripped from console output)

**Steps to reproduce or test case**
 - load a script (statically or programmatically) contains the argument parse lines above
 - invoke the method above
 - observe the application output

**Redis version**
`6.0.5` (AWS ElastiCache, cluster mode)

**Redisson version**
`3.15.3`

**Redisson configuration**
```
Config cfg = new Config();
RedisURI uri = new RedisURI("redis", "aws-ec-redis-cluster-endpoint", 6379);
cfg.useClusterServers().addNodeAddress(uri.toString());
cfg.setThreads(4);
cfg.setNettyThreads(8);
RedissonClient client = Redisson.create(cfg);
```
Note on the script:
the same script (without modification) worked with `lettuce-core` in the same application in a production environment (with thousands of calls per minute running 24/7) and has been proven stable.

for some reason the arguments received on Redis server (from `redisson`) contains extra characters for the first argument.

**Update**
I tested a non-default `Codec`: 
`cfg.setCodec(StringCodec.INSTANCE);`
and the issue is addressed. Not sure if this is expected behavior for the default `Codec`

**Comment by mrniko** [comment]
You need to use StringCodec for your case, since default codec is a binary codec.

**Comment by duxing** [comment]
thanks for getting back to me and confirming
