### ISSUE TITLE
Object lost due to TTL

### ISSUE THREAD

**Issue by vipul1231** [redisson/redisson#3537]
We are trying the below approach to get the data from Redis with TTL.

RMap<String, Object> rMap = this.client.getMap(this.getEnvCacheKey(cacheKey));
rMap.expire(this.defaultTTL, TimeUnit.SECONDS);

//Fetch the object
Object object = rMap.get("id");

//Putting the same in list
List<Object> list = new ArrayList<>();
list.add(object);

//Now TTL expires of key and object deleted.

Now list.size == 0 and my application failing due to this since the object fetched in removed from memory.

Please any approach to mitigate this issue.

**Comment by mrniko** [comment]
Please check you code. Since returned object by `get()` is not connected to TTL.

**Comment by vipul1231** [comment]
The same thing is happening with getList as well.

final RList<V> rList = client.getList(getEnvCacheKey(cacheKey));
rList.expire(7L, TimeUnit.SECONDS);

rlist.add("Value1");
rlist.add("Value2");

assertThat(set).containsOnly("Value1", "Value2");

Now after 7 seconds 
set.size() becomes 0

**Comment by mrniko** [comment]
assertion is for `set` object and not `rlist`

**Comment by vipul1231** [comment]
Updated the example.

**Comment by mrniko** [comment]
that's expected behaviour to get empty list after 7 seconds, since ttl is 7 seconds
