### ISSUE TITLE
Handling of shard being down in a Redis cluster

### ISSUE THREAD

**Issue by shaurya10000** [redisson/redisson#3538]
Hi

Does Redisson has any logic for intelligently handling a scenario where a particular shard is down in Redis. Possible 'intelligent' solutions could be to-
1. Avoid calling Redis cluster for keys located over that shard
2. Not keep retrying for keys which are continuously failing

All these solutions may enable it to keep serving the traffic for which ever keys it can from other shards.
This is possible only with some built in knowledge of key distribution across shards, I am not aware if redisson has that context ?

Thanks!

**Comment by mrniko** [comment]
> Avoid calling Redis cluster for keys located over that shard
> Not keep retrying for keys which are continuously failing

You can control that with `retryInterval` setting. No attempts are made if you set it `0`.
