### ISSUE TITLE
Not support BITFIELD friendly

### ISSUE THREAD

**Issue by YooLin** [redisson/redisson#3540]
example:
BITFIELD key get u5 0

can I use redisson client to execute command like this?

**Comment by mrniko** [comment]
use `RBitSet.getByte`/`RBitSet.getShort`/`RBitSet.getInteger`/`RBitSet.getLong` methods

**Comment by YooLin** [comment]
> use `RBitSet.getByte`/`RBitSet.getShort`/`RBitSet.getInteger`/`RBitSet.getLong` methods

tks
i found another way
`bitset.toString()` get all index which is true

**Comment by mrniko** [comment]
`getSigned()`, `setSigned()`, `incrementAndGetSigned()`, `getUnsigned()`, `setUnsigned()`, `incrementAndGetUnsigned()` methods added to `RBitSet` object
