### ISSUE TITLE
Why ExpirationEntry use LinkedHashMap to save threadId

### ISSUE THREAD

**Issue by yukerui** [redisson/redisson#3544]
Reddison watchDog strategy use timerTask to increase key expiration time while set the lock success

    private void renewExpiration() {
        ExpirationEntry ee = EXPIRATION_RENEWAL_MAP.get(getEntryName());
        if (ee == null) {
            return;
        }
        
        Timeout task = commandExecutor.getConnectionManager().newTimeout(new TimerTask() {
            @Override
            public void run(Timeout timeout) throws Exception {
                ExpirationEntry ent = EXPIRATION_RENEWAL_MAP.get(getEntryName());
                if (ent == null) {
                    return;
                }
                Long threadId = ent.getFirstThreadId();
                if (threadId == null) {
                    return;
                }
                
                RFuture<Boolean> future = renewExpirationAsync(threadId);
                ......
       }
   }

  First use **entryName** to get ExpirationEntry object. For the same entryName, other threads can't get the key because locked(ps: same thread can get and counter++)，so why use LinkedHashMap to save thread if there only have one thread?

`public static class ExpirationEntry {

        private final Map<Long, Integer> threadIds = new LinkedHashMap<>();
        private volatile Timeout timeout;

        public ExpirationEntry() {
            super();
        }

        public synchronized void addThreadId(long threadId) {
            Integer counter = threadIds.get(threadId);
            if (counter == null) {
                counter = 1;
            } else {
                counter++;
            }
            threadIds.put(threadId, counter);
        }
}`

**Comment by mrniko** [comment]
in case of readwrite lock there are might be multiple read locks.

**Comment by yukerui** [comment]
> in case of readwrite lock there are might be multiple read locks.

Understood, thank you for your reply
