### ISSUE TITLE
Object not added in RSet

### ISSUE THREAD

**Issue by vipul1231** [redisson/redisson#3546]
In the below code, we are facing intermittent issues where` System.out.println("Your Ids: "+ids1)` is not printed when we add something and RedissionSet reference doesn't contain anything even after adding objects to it.
```
final Set<String> homeIds = platformCache.getSet(Home.fetchProductCacheKey(productId));

List<String> getIds = callToDb.getProductId(productId);

for(String ids : getIds) {
homeIds.add(ids);
}

for(String ids1: homeIds) { // This for loop is not run since homeids were empty sometimes.
System.out.println("Your Ids: "+ids1);
}

```

Are we doing anything wrong? Any help will be appreciated.

**Comment by mrniko** [comment]
Try ReadMode.MASTER setting

**Comment by vipul1231** [comment]
I believe this setting will move reading data to master node ?. This will increase traffic to my master node. Correct me if I am wrong.

**Comment by mrniko** [comment]
This happens due to replication lag between slave/master nodes.

**Comment by vipul1231** [comment]
Ok thanks. Closing this issue.
