### ISSUE TITLE
Setting TTL on existing value

### ISSUE THREAD

**Issue by whleviathan** [redisson/redisson#3556]
We have a use case whereby when we first create objects in our Redis Hashmap, we set a long TTL (e.g. 1 month) to ensure that the data will be cleared out at some point in the future.

However, in general this data is only required for a few days, and for optimization we would like to clear this data out sooner when possible. When our application is made aware that it is safe to clean up this data earlier, we would like to set a new TTL on the entries (e.g. 1 day). 

Unfortunately, I can't see any way to alter the TTL on an existing entry (other than doing a read, followed by a write with the new TTL).

What I was looking for in the API was something similar to:

`public void setTimeToLive(K key, long ttl, TimeUnit ttlUnit);`

or even better, a method which accepts a batch of keys

`public void setTimeToLive(List<K> keys, long ttl, TimeUnit ttlUnit);`

Does anything like this already exist already in Redisson? (or is there some other workaround I can use?)

**Comment by mrniko** [comment]
duplicated with https://github.com/redisson/redisson/issues/3423
