### ISSUE TITLE
How to work with shard?

### ISSUE THREAD

**Issue by eshengit** [redisson/redisson#3557]
in redis in action https://redislabs.com/ebook/part-2-core-concepts/01chapter-9-reducing-memory-use/9-2-sharded-structures/9-2-2-sets/

They have API such as 

conn.hget(shard, key) 
conn.hset(shard, key, value) 
does Redisson has similar API to help Shard automatically? 

of course I can handle shard myself as 
conn.hget("key:shard")

**Comment by mrniko** [comment]
Redisson shards data automatically calculating Redis node from key. If doesn't belong to shard you'll get an error.

**Comment by eshengit** [comment]
@mrniko , 
1. is sharding feature a feature I have to pay or its automatically? 
2. you mentioned that : if it doesn't belong to shard, you will get an error. 
its confusing to me. if I configured cluster server A.  
as long as I inserted data a/b/c and they go to A-shard1 -> A-shardN, when I query them later on, it will never get error. 
I get an error only when I try to query a but I never added them, right?

**Comment by mrniko** [comment]
@eshengit 

> is sharding feature a feature I have to pay or its automatically?

It's automatic, you don't to pay for it.

> as long as I inserted data a/b/c and they go to A-shard1 -> A-shardN, when I query them later on, it will never get error.

You'll get an error if you try to write data by key which doesn't belong to a shard

**Comment by eshengit** [comment]
> You'll get an error if you try to write data by key which doesn't belong to a shard

I am confused. I believe I can't read data by key which does not belong to any shard.  
but why I can't write data by key does not belong to any shard? 
for example, I write data with key XYZ, it will pick a shard based on the current cluster configuration, I assume  it should never get error.

**Comment by mrniko** [comment]
> but why I can't write data by key does not belong to any shard?

You'll get an error from Redis.
