### ISSUE TITLE
The expire method of RedissonReactiveKeyCommands could not work on  Sentinel mode.

### ISSUE THREAD

**Issue by zhanbo0505** [redisson/redisson#3564]
**Redis version 4.0.7**
**Redisson version redisson-spring-data-22:3.12.5**

In ReactiveKeyCommands the method expire was defined as a write operation, but in the RedissonReactiveKeyCommands
the method expire was implement as a read operation. 

ReactiveKeyCommands :

	/**
	 * Set time to live for given {@code key} in seconds.
	 *
	 * @param key must not be {@literal null}.
	 * @param timeout must not be {@literal null}.
	 * @return
	 * @see <a href="https://redis.io/commands/expire">Redis Documentation: EXPIRE</a>
	 */
	default Mono<Boolean> expire(ByteBuffer key, Duration timeout) {

		Assert.notNull(key, "Key must not be null!");
		Assert.notNull(timeout, "Timeout must not be null!");

		return expire(Mono.just(new ExpireCommand(key, timeout))).next().map(BooleanResponse::getOutput);
	}

RedissonReactiveKeyCommands :

    @Override
    public Flux<BooleanResponse<ExpireCommand>> expire(Publisher<ExpireCommand> commands) {
        return execute(commands, command -> {

            Assert.notNull(command.getKey(), "Key must not be null!");

            byte[] keyBuf = toByteArray(command.getKey());
            Mono<Boolean> m = read(keyBuf, StringCodec.INSTANCE, EXPIRE, keyBuf, command.getTimeout().getSeconds());
            return m.map(v -> new BooleanResponse<>(command, v));
        });
    }

When using the reactive redisson to work on Sentinel mode and executing expire command will cause the exception which tips that should not execute write command in a slave instance, because the RedisExecutor was set as readOnlyMode.

When RedisExecutor was set as readOnlyMode, the connectionManager will return a slave connection.

    protected RFuture<RedisConnection> getConnection() {
        RFuture<RedisConnection> connectionFuture;
        if (readOnlyMode) {
            connectionFuture = connectionManager.connectionReadOp(source, command);
        } else {
            connectionFuture = connectionManager.connectionWriteOp(source, command);
        }
        return connectionFuture;
    }

**Comment by mrniko** [comment]
Fixed! Thanks for report
