### ISSUE TITLE
How to print current open connections in redisson client?

### ISSUE THREAD

**Issue by harshamadala** [redisson/redisson#3565]
I am trying to tune redisson client connection pool configuration and I am using cluster mode to connect to ElastiCache. I am trying to analyse what is current connections utilised and other connection pool details. 
Can anyone please help me how to print the information?

**Comment by harshamadala** [comment]
Can anyone please reply? This will help to understand how redisson is behaving internally with respect to connections.

**Comment by mrniko** [comment]
you can set `DEBUG` logging level to `org.redisson` package to see connection acquisition/release.
