### ISSUE TITLE
RMap compute implementation breaks Map contract.

### ISSUE THREAD

**Issue by abishai** [redisson/redisson#3567]
**Expected behavior**
Remapping function result is written to redis and returned.

**Actual behavior**
Remapping function result is only returned, but not saved if object instance remains the same.

**Steps to reproduce or test case**
```
        data class Test(var s1: String, var l1: Long): Serializable
 
        val map = redisson.getMap<String,Test>("test-map-1")
        logger.info {map.getOrPut("test-map-1") { Test("t", 0) }  }
        logger.info { map.computeIfPresent("test-map-1", BiFunction { _, u -> u.l1++; u }) }
        logger.info { map.get("test-map-1") }
```
This snippet prints
```
Test(s1=t, l1=0)
Test(s1=t, l1=1)
Test(s1=t, l1=0)
```

**Redis version**
6.0.11

**Redisson version**
3.15.4

**Redisson configuration**
Empty configuration, with local redis.

**Comment by mrniko** [comment]
unable to reproduce. Here is my test:

```java
        RMap<String, String> map = getMap("map");
        map.put("1", "10");
        map.computeIfPresent("1", (key, value) -> {
            assertThat(value).isEqualTo("10");
            return "12";
        });
        assertThat(map.get("1")).isEqualTo("12");

```

**Comment by abishai** [comment]
In your example, String class is immutable, mine doesn't not.

**Comment by mrniko** [comment]
Sorry, what do you mean?  It's immutable by default.

**Comment by abishai** [comment]
In your example, new reference is returned by BiFunction. In my, reference to the object remains the same, as I increment one of it field.

**Comment by mrniko** [comment]
Fixed! Thanks for report
