### ISSUE TITLE
Broken connection detection

### ISSUE THREAD

**Issue by synologic** [redisson/redisson#3568]
Using 3.15.4 and sentinel connections, when I set the config connection listener, i don't get a connect or disconnect when (all) nodes have failed (e.g. dropping the Redis traffic from firewall to simulate network issues).

When this happens, a .getBucket command is blocking and remains blocked no matter if the connection is restored or not

The config i'm using:
sentinelServersConfig:
  pingConnectionInterval: 500
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 500
  retryAttempts: 3
  retryInterval: 500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 5000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 1
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 1
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  sentinelAddresses:
  - "redis://xxx:16379"
  - "redis://yyy:16379"
  - "redis://zzzz:16379"
  masterName: "redis-cluster"
  database: 0
threads: 0
nettyThreads: 0
codec: !<org.redisson.client.codec.ByteArrayCodec> {}
transportMode: "NIO"

The question i have is how to figure out when the connection is broken ? What am i missing ?
Thanks

**Comment by mrniko** [comment]
How did you define connection listener? through Redisson Config object?

**Comment by synologic** [comment]
Yes, that's right.
I set the connection listener on the config object.

**Comment by synologic** [comment]
Just for info, doesn't seem to work in single server mode either.
Here's the code for reference:

Config config = Config.fromYAML(new File(redisConfigFile));
            redisClient = Redisson.create(config);
            config.setConnectionListener(new ConnectionListener() {
                @Override
                public void onConnect(InetSocketAddress inetSocketAddress) {
                    logger.info("Connection connected !");
                }

                @Override
                public void onDisconnect(InetSocketAddress inetSocketAddress) {
                    logger.info("Connection disconnected !");
                }
            });

**Comment by mrniko** [comment]
It works for single Redis. I'll recheck it for sentinel. Here is the test:

https://github.com/redisson/redisson/blob/ac5b0cba06723dd4c38f4d016190da5166040e76/redisson/src/test/java/org/redisson/RedissonTest.java#L234

**Comment by synologic** [comment]
Thanks for pointing the issue, it works fine for Sentinels as well :)

**Comment by mrniko** [comment]
I'm closing this.
