### ISSUE TITLE
infinty add slaves if cluster nodes are all same ip&port

### ISSUE THREAD

**Issue by deanisty** [redisson/redisson#3571]
```
// src/main/java/org/redisson/cluster/ClusterConnectionManager.java

private void checkSlaveNodesChange(Collection<ClusterPartition> newPartitions) {
        Set<ClusterPartition> lastPartitions = getLastPartitions();
        for (ClusterPartition newPart : newPartitions) {
            for (ClusterPartition currentPart : lastPartitions) {

                /***** this will always be true if all cluster nodes have same ip & port*****/

                if (!newPart.getMasterAddress().equals(currentPart.getMasterAddress())) {
                    continue;
                }

                MasterSlaveEntry entry = getEntry(currentPart.slots().nextSetBit(0));
                // should be invoked first in order to remove stale failedSlaveAddresses

                /*******  more and more slaves will be added if some master don't have any slave  ******/

                Set<RedisURI> addedSlaves = addRemoveSlaves(entry, currentPart, newPart);
                // Do some slaves have changed state from failed to alive?
                upDownSlaves(entry, currentPart, newPart, addedSlaves);

                break;
            }
        }
    }
```

**Comment by mrniko** [comment]
I think all cluster nodes shouldn't have the same ip & port

**Comment by deanisty** [comment]
> I think all cluster nodes shouldn't have the same ip & port

Unfortunately, I am using a cloud redis service which the vendor create a proxy between clients and their backend redis cluster servers, and when the client send a "CLUSTER NODES" command to the proxy, it will response a cluster nodes list in which all node have same ip and port, and even some master node don't have slot information and slave node, this surely lead Redisson to create more and more slave client connections in cluster mode, I found this problem when debug Redisson source code, and now I change Redisson to use single server mode to avoid this situation, but I wonder if it possible to use node_id to compare newPart and currentPart whether belong to same master rather than masterAddress
`
                if (!newPart.getMasterAddress().equals(currentPart.getMasterAddress())) {
                    continue;
                }
                // or may like this
                if (!newPart.getNodeId().equals(currentPart.getNodeId())) {
                    continue;
                }
`

**Comment by mrniko** [comment]
you need to use Redisson with single instance mode in this case. or proxy mode https://github.com/redisson/redisson/wiki/2.-Configuration#29-proxy-mode

Which Redis vendor do you use?

**Comment by deanisty** [comment]
> you need to use Redisson with single instance mode in this case. or proxy mode https://github.com/redisson/redisson/wiki/2.-Configuration#29-proxy-mode
> 
> Which Redis vendor do you use?

Sorry for replying so late, I am using Tencent cloud redis service , and I switched to single instance mode and issue solved, thanks a lot .
