### ISSUE TITLE
Redisson Java Client-RedisCluster-YAML config-RedisNodeNotFoundException

### ISSUE THREAD

**Issue by willy23martin** [redisson/redisson#3574]
Good morning:

I have been working in the implementation of a Redisson client to connect a Java application to Redis cluster defined by a YAML config file (loaded from the Config class) and by using RBucket as a class to put and get key-value pairs.

The connection is primary established by calling Redisson.create(config) method. Sometimes, even if a master is up after an outage, a RedisNodeNotFoundException exception happen saying that we need to increase the value of retryAttempts and/or retryInterval settings.

I really appreciate if you can give me some advices, recommendations about some configuration fields I could have missed, or something about the uses of RBucket or Redisson.create method in order to make it more resilient and to solve that issue.

Thank you so much in advance.

**Comment by mrniko** [comment]
Can you share full stack trace?

**Comment by willy23martin** [comment]
Yes sir.
The message is the following:
![image](https://user-images.githubusercontent.com/13683012/116093185-1392d200-a66c-11eb-91c2-09c75df84751.png)

Do you have any suggestions about the way I manage the Redisson connection. Should I modify something or take into account some strategy you recommend for resilient and HA environments?

Thank you so much for your help.

**Comment by mrniko** [comment]
Do you invoke `Redisson.create(config)` right after cluster initialization?

**Comment by willy23martin** [comment]
Yes @mrniko I invoked that after cluster start. But sometimes RedissonClient loose connection. 
I found yeesterday the use of the interface ConnectionListener with both onConnect and onDisconnect that should be set before Redisson.create(config), as I understood you said in other GitHub issue. That has been working for me because I can monitor the connection. But once is restablished how do you consider it would be manage? I would run all the process from the beginning (loading the config) OR just continue with the current connection. Has the connection a timeout in which it needs to be recreated again? Those are the criteria or suggestions I am looking for in order to make the implementation more resilient. 

I appreciate your suggestions. :)

**Comment by mrniko** [comment]
>  But once is reestablished how do you consider it would be managed? I would run all the process from the beginning (loading the config) OR just continue with the current connection

Redisson reconnects automatically broken channels.
