### ISSUE TITLE
RedissonLock分布式锁冲突无法使用pubsub订阅功能实现等待问题

### ISSUE THREAD

**Issue by zhwq1216** [redisson/redisson#3577]
使用RedissonLock加锁如果对应的资源已经被锁定，需要等待的时候，使用pubsub订阅消息来等待锁资源。当同时等待锁订阅消息达到subscriptionConnectionPoolSize*subscriptionsPerConnection个时，再多来一个锁等待订阅消息，
org.redisson.pubsub.PublishSubscribeService#connect 方法向连接池获取新的分发订阅连接，最终调用到
org.redisson.connection.ClientConnectionsEntry#acquireSubscribeConnection方法的
freeSubscribeConnectionsCounter.acquire(runnable) 
由于freeSubscribeConnectionsCounter信号量已用完（到到了subscriptionConnectionPoolSize），连接一直无法获取导致PublishSubscribeService中的freePubSubLock没有释放。   另外由于PublishSubscribeService向连接池获取连接后是直接缓存下来，不把分发订阅链接释返回给连接池的，因此导致freeSubscribeConnectionsCounter一直等待，出现死锁情况。

最终由于PublishSubscribe.entries不断的积压会导致内存异常

异常堆栈信息：
org.redisson.client.RedisTimeoutException: Subscribe timeout: (5000ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
        at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:171)
        at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:149)
        at org.redisson.RedissonLock.lock(RedissonLock.java:127)

内存泄漏截图：
![image](https://user-images.githubusercontent.com/9948390/116031986-6cc12c80-a691-11eb-8b13-90ddfe666315.png)

**Comment by zhwq1216** [comment]
临时解决方法：  评估锁等待数量，调整subscriptionConnectionPoolSize，subscriptionsPerConnection这两个参数，避免锁等待数量达到subscriptionConnectionPoolSize*subscriptionsPerConnection

修改方案1：
修改org.redisson.pubsub.PublishSubscribeService#connect这个类，判断订阅使用的连接数已经达到subscriptionConnectionPoolSize，则直接抛出异常，不再向连接池获取连接。

修改方案2：
org.redisson.pubsub.PublishSubscribeService#unsubscribe(org.redisson.client.protocol.pubsub.PubSubType, org.redisson.client.ChannelName) 方法中判断对应的连接已经没有关联的订阅内容了，则把连接还给连接池，由连接池对连接做管理。

**Comment by mrniko** [comment]
Merged
