### ISSUE TITLE
why can't i set expiration on RAtomicLong?

### ISSUE THREAD

**Issue by mariokoehler** [redisson/redisson#3579]
I'm using Redisson 3.15.3

In my attached example you see that i try to create (or get an existing) RAtomicLong with a given name and expiration. Everything works apart from the yellow marked line where i try to set the expiration. In this concrete case expiration is 15 and unit is TimeUnit.MINUTES. But the expire() call always returns false.

I'm wondering if i do something wrong or what might be common causes for expire to return false (so i could investigate those further)?

![example](https://user-images.githubusercontent.com/63335677/116059061-c2410d80-a680-11eb-904d-0dac5a0b5b82.JPG)

**Comment by mrniko** [comment]
Make sure you initialized it with value first.

**Comment by mariokoehler** [comment]
aaahh, thats an idea...could it really be this simple? now i feel stupid :-) thanks for the hint!

**Comment by mrniko** [comment]
I'm closing this
