### ISSUE TITLE
Async lock thread affinity

### ISSUE THREAD

**Issue by CatalinAdlerDF** [redisson/redisson#3580]
Hi,

I'm working on a kotlin micronaut web app which is attempting to be fully async and we're using redisson for distributed locks.

I'm somewhat unclear on how to exactly use it correctly.

The official documentation says `RLock object behaves according to the Java Lock specification. It means only lock owner thread can unlock it otherwise IllegalMonitorStateException would be thrown. Otherwise consider to use RSemaphore object.` which sounds weird as in an async context, executing on a specific threads is never guaranteed.

The code I'm using for now, in a kotlin suspendable func, is like this:
``` kotlin
val lock = rediClinet.getLock("lock_name)
try {
    (lock.lockAsync(50, TimeUnit.SECONDS) as CompletionStage<Void>).await()
    //fancy kotlin async code here.
}
finally {
    (lock.unlockAsync() as CompletionStage<Void>).await()
}
```

The unlock line is not guaranteed to execute on the same thread as the lockAsync line.

Thanks!

**Comment by CatalinAdlerDF** [comment]
But what do use as `threadId` ?
Any numbers as long as I use the same number across acquire/release methods?

**Comment by mrniko** [comment]
you need to pass the same id to `lockAsync()` and `unlockAsync()` methods. It might be any id.

**Comment by CatalinAdlerDF** [comment]
ok, thanks.

must say this is a very unexpected design for an distributed lock.
