### ISSUE TITLE
Memory leak in IdleConnectionWatcher

### ISSUE THREAD

**Issue by artkonr** [redisson/redisson#3581]
Hey,

I have a production environment which uses a load balancer over several master Redis instances, so the actual IPs of the Redis instances switch with every request.

I update Redisson from some 3.3.* version to 3.15.3 and started to notice odd memory consumption: something keeps piling up in the Old Generation and never gets garbage-collected. Normally, it would take about a day to reach Old Gen mem cap and in a few days, so when other objects make it to Old Gen, the app just dies with OOM.

I dumped the memory, it looks like when IPs change, new `ClientConnectionsEntry` items are allocated and attached the linked queue in the `IdleConnectionWatcher` which is **never** pruned, unless the client is shut down. I can't tell how many nodes are in those queues, probably too many, because `IdleConnectionWatcher` **is about 30Mb big**. 

Unfortunately, I cannot change the infrastructure I use. Any chance there's any config that could just mitigate it for now?

**Expected behavior**
Application does not run out of memory if connection entries are re-created frequently and dangling objects are cleaned up.

**Actual behavior**
Strong references to previously created objects are retained and keep piling up until the app gets OOM-killed.

**Steps to reproduce or test case**
Tricky: Redis instances should be behind a load balancer, which should have a resolvable hostname. The idea is to make Redisson try to rebuild the connection pool every time it makes a request.

**Redis version**
Idk, because I don't have access to the infrastructure.

**Redisson version**
3.15.3

**Redisson configuration**
1. Clients connect to Master nodes.
2. Clients are single-threaded.
3. Clients attempt to resolve hostname to connect to actual Redis instances.

**Comment by mrniko** [comment]
Can you share memory dump?

**Comment by artkonr** [comment]
@mrniko, is there an email address I could send it over to?

**Comment by mrniko** [comment]
You can drop it here: nkoksharov@kentel.buzz

**Comment by artkonr** [comment]
Unfortunately, I cannot provide the full dump, corporate policy. Maybe there is some alternative?

**Comment by mrniko** [comment]
> IdleConnectionWatcher is about 30Mb big

How many entries does it have in queue?

**Comment by artkonr** [comment]
> How many entries does it have in queue?

Lots, I'm looking at the dump in intellij, so it's hard to say for sure how many nodes are there, bc intellij for some reason does not show the object count. However, given the shallow size of node of about 32 bytes, my guess would be that there must be ~900K nodes.

> How often do Redis IP's change?

Under normal load Redis only supplies the metrics, so IPs rotate once in 5-10 seconds, depending on environment. When there is some work to do for the application (e.g. when it runs a batch job using Redis as pub-sub) - hard to tell, I'd say that we're talking milliseconds, probably.

**Comment by mrniko** [comment]
Fixed

**Comment by artkonr** [comment]
Awesome! Is there a snapshot I could try this out with?

**Comment by artkonr** [comment]
Awesome, thanks! I wonder if there is a snapshot artifact I could try out, there some style check failing on `master`, I can't build it myself.
