### ISSUE TITLE
mget/mset缓存时出现CROSSSLOT错误

### ISSUE THREAD

**Issue by yazifs** [redisson/redisson#3582]
在redisson-spring-data包中，RedissonConnection在**集群模式**中调用`RedissonConnection.mGet`和`mSet`方法时，如果key不在同一个slot中，会抛出CROSSSLOT异常。同样的操作在spring的另外两个实现中`JedisClusterConnection`和`LettuceConnection`中并不会报错（内部自动按slot进行调用），所以想咨询下redisson的mGet和mSet实现出于什么考虑，实现方式与spring的不同，还是说这是一个bug？
- 代码
```java
public class RedisTemplateTest {
    @Autowired
    private RedisTemplate<String, String> redisTemplate;

    @Test
    public void testMGet() {
        Map<String, String> of = Maps.of("TestA", "b", "TestC", "d", "efg", "db");
        redisTemplate.opsForValue().multiSet(of);
    }
}
```
- 依赖版本
redisson: 3.15.4
redisson-spring-boot-starter: 3.15.4

**Comment by mrniko** [comment]
Fixed! Thanks for report
