### ISSUE TITLE
Netty ByteBuf leak, JsonJacksonCodec, batched write

### ISSUE THREAD

**Issue by marcusspangenberg** [redisson/redisson#3583]
We are seeing leaked Netty buffers like this quite frequently in production. In some deployments it causes out of memory errors on our container instances. 

Seen both in Redisson 3.15.2 and 3.13.1. The codec is JsonJacksonCodec as you can see from the allocation call stack. So far I have only seen it with pipelined write operations (RBatch, in memory atomic). No other exceptions or errors during the write operation was seen.

My question is, is there something we should be doing differently to avoid such leaks, or is this a possible bug? Any hints on where to look would be helpful. I have not been able to create a local minimal repro to share unfortunately.

2021-04-16 06:09:56.447 ERROR 28 --- [sson-netty-2-10] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
	org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:77)
	org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:336)
	org.redisson.RedissonMap.putOperationAsync(RedissonMap.java:894)
	org.redisson.RedissonMap.putAsync(RedissonMap.java:881)
	...

**Comment by mrniko** [comment]
> So far I have only seen it with pipelined write operations

Can you provide test code to reproduce?

**Comment by marcusspangenberg** [comment]
Unfortunately I have not been able to reproduce it locally, only in live environments. So I haven't been able to create a small example reproducing it to share.

**Comment by avcad** [comment]
I was running into the same problem when I reported this:
https://github.com/redisson/redisson/issues/3502

I also have batch HSET / atomic, but using Marshalling and String codecs. We didn't have any errors in the log other than the leak message, but noticed that all the leaks were coming from the same function.  All of our functions call a common API that uses Redisson to store in Redis, so I suspected the problem had to do with the data/objects being serialized. We commented the call and the problem went away.

While trying to reproduce the problem I noticed that if the data wasn't serializable, we could reproduce the leak, but in my toolkit I did get a serialization exception while in production I had no application errors, so I suspect the issue was different.  Maybe similar to what you are experiencing. 

While researching the problem and looking for workarounds (as my environment was crashing due to Native OOM), I found this setting. As we commented out the call, I didn't have to use it, and it is likely to degrade performance (no idea by how much) but it could help avoid the OOM 

-Dio.netty.noPreferDirect=true -Dio.netty.allocator.type=unpooled

**Comment by marcusspangenberg** [comment]
@avcad Thanks for your suggestion. I saw the issue you raised, it did seem specific to another codec. 

In this case it happens with several different keys. The value type is sometimes a String and sometimes a simple value object and I am not seeing any serialization exceptions. Maybe similar to what you also saw in production, like you said.

**Comment by mrniko** [comment]
@avcad 

> We commented the call and the problem went away.

Which call you commented out?

**Comment by mrniko** [comment]
@marcusspangenberg 

> pipelined write operations (RBatch

Can yon list operations you execute?

**Comment by marcusspangenberg** [comment]
@mrniko 

Typical usage pattern in pseudo code is something like below. Sometimes a batch will be created but never executed when an unrelated exception happened, and when we do not want to commit the changes.

`final var batchOptions = BatchOptions
	.defaults()
	.executionMode(BatchOptions.ExecutionMode.IN_MEMORY_ATOMIC);
final var batch = redissonClient.createBatch(batchOptions);

final RBucket<String> bucket1 = batch.getBucket(...);
bucket1.putAsync(...);

final RMap<String, SomeValueObject> map1 = batch.getMap(...);
map1.putAsync(...);

final RMap<String, String> map2 = batch.getMap(...);
map2.putAsync(...);

final RMap<String, SomeValueObject> map3 = batch.getMap(...);
map3.putAsync(...);

final RMap<String, SomeValueObject> map4 = batch.getMap(...);
map4.putAsync(...);

final RMap<String, SomeValueObject> map5 = batch.getMap(...);
map5.putAsync(...);

final RMap<String, String> map6 = batch.getMap(...);
map6.putAsync(...);

final RMap<String, String> map7 = batch.getMap(...);
map7.putAsync(...);

final RMap<String, Integer> map8 = batch.getMap(...);
map8.putAsync(...);

final RMap<String, SomeValueObject> map9 = batch.getBucket(...);
map9.deleteAsync(...);

final RMap<String, Long> map10 = batch.getMap(...);
map10.putAsync(...);

final RBucket<SomeValueObject> bucket2 = batch.getBucket(...);
bucket2.putAsync(...);

final RMap<String, SomeValueObject> map11 = batch.getMap(...);
map11.removeAsync(...);

final RBucket<String> bucket3 = batch.getBucket(...);
bucket3.putAsync(...);

batch.execute();`

**Comment by mrniko** [comment]
I'll introduce `cancel()` method to free allocated buffers.

**Comment by marcusspangenberg** [comment]
@mrniko Interesting, so is it that fact that we are creating batches that are sometimes not executed that is the problem?

**Comment by mrniko** [comment]
Yes, that's the problem. Buffers aren't cleaned in this case.

**Comment by marcusspangenberg** [comment]
Understood. Thanks for the quick response @mrniko

**Comment by avcad** [comment]
Hi @mrniko , Let me clarify. 

We have a function "cacheMeInRedis(myObject)" that we call from 100s of places. This function uses batch/fastPut.

In production we noticed that all the LEAK messages were from the same stack, so we removed
the one call to "cacheMeInRedis()", and the problem went away. We are still using "cacheMeInRedis(myObject)"
in 100s of other places.

Our function is wrapped in two try/catch blocks. One specific for the fastPutAsync() method,
and one for the rest.

try {		
	batch.fastPutAsync( "value", myObject );
} catch (Exception e) {
	logger.severe( "error serializing....");
}
try {
...
batch.execute();
...
} catch() {
	logger.severe( "error executing...")
}

In my Eclipse, when I pass a non-serializable object, I do see the warning in the log, but not in production.
This leads me to think that the exception might not have triggered in production. Odd.
Sadly I don't have a way to reproduce the problem anymore.

I think the cancel() method would help. Do we need to use it in the catch only? What if the method was
close() instead, and we use it in the finally block. Could that help check for scenarios where there is
no error but somehow the buffers are still allocated?

**Comment by mrniko** [comment]
Done. discard() method added

**Comment by avcad** [comment]
@mrniko . Thanks!!!

I tested the new code (with sets and hashses) and it seems to work, but there is one buffer that is not removed:
the key for the failing hset entry:

```
[main] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:616)
	org.redisson.codec.MarshallingCodec$ByteOutputWrapper.write(MarshallingCodec.java:129)
	org.jboss.marshalling.UTFUtils.writeUTFBytes(UTFUtils.java:131)
	org.jboss.marshalling.river.RiverMarshaller.writeKnownObject(RiverMarshaller.java:397)
	org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:217)
	org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
	org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
	org.redisson.codec.MarshallingCodec.lambda$1(MarshallingCodec.java:161)
	org.redisson.codec.MarshallingCodec$$Lambda$2.0000000010C30AC0.encode(Unknown Source)
	org.redisson.command.CommandAsyncService.encodeMapKey(CommandAsyncService.java:699)
	org.redisson.RedissonObject.encodeMapKey(RedissonObject.java:306)
	org.redisson.RedissonMap.fastPutOperationAsync(RedissonMap.java:1365)
	org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:1355)
	test.NativeMemoryTest.main(NativeMemoryTest.java:39)
```

Here:
```
    protected RFuture<Boolean> fastPutOperationAsync(K key, V value) {
        String name = getRawName(key);
        return commandExecutor.writeAsync(name, codec, RedisCommands.HSET, name, encodeMapKey(key), encodeMapValue(value));
    }
```
This key is not released.	
```
map.fastPutAsync("myKey3",  Logger.getAnonymousLogger());
```

Thanks!!

**Comment by mrniko** [comment]
@avcad 

Unable to reproduce. Here is my test:

```java
        RBatch batch = redisson.createBatch(batchOptions);
        for (int i = 0; i < 1000; i++) {
            RMapAsync<Object, Object> m = batch.getMap(RandomString.make(10));
            m.fastPutAsync(RandomString.make(200), RandomString.make(2000));
        }
        batch.discard();
```

**Comment by avcad** [comment]
Hi @mrniko,
batch.discard() is working well. 

The problem is here:
```
protected RFuture<Boolean> fastPutOperationAsync(K key, V value) {
        String name = getRawName(key);
        return commandExecutor.writeAsync(name, codec, RedisCommands.HSET, name, encodeMapKey(key), encodeMapValue(value));
    }
```
if encodeMapValue() fails to serialize and throws an exception, the buffer acquired by encodeMapKey() will never be freed:
I think the code should check for IO Exception when executing encodeMapValue, and if one is caught, the key ByteBuf needs to be freed. makes sense?

The way to reproduce is with:
m.fastPutAsync(RandomString.make(200), nonSerializableObject );

**Comment by mrniko** [comment]
I'll resolve this issue in #3502
