### ISSUE TITLE
RedissonConnection#scan query results error in redis cluster

### ISSUE THREAD

**Issue by yazifs** [redisson/redisson#3584]
Hi, In our test case, we store three keys that start with  `test`  in redis cluster, two of which are in the same node, one in the other node, and then using  `RedissonConnection#scan`  method to query   `test*`. we can only query keys on a node, not all nodes.

**Expected behavior**
In Redis cluster mode，when we use `RedissonConnection#scan` to  get the keys with a pattern mode like (test*), we want to get the keys that can be matched by the pattern on all redis cluster nodes

**Actual behavior**
In Redis cluster mode，when we use `RedissonConnection#scan` to get the keys with a pattern mode like (test*) in redis instance，we can only get the keys matched by the pattern on a certain redis node

**Steps to reproduce or test case**
- a redis cluster with 3 master  and 3 slave
- put key-value：
```properties
testa: b
testb: d
testadfdf: db
```
- scan key in the following way
```java
public class RedisTemplateTest {

    @Autowired
    private RedisTemplate<String, String> redisTemplate;

    @Test
    public void testScan() {
        Set<String>  expected = new HashSet<>(Arrays.asList("testa", "testb", "testadfdf"));
       
        Set<String> actual = new HashSet<>();
        try (Cursor<byte[]> test = redisTemplate.executeWithStickyConnection(e -> e.scan(ScanOptions.scanOptions()
                .match("test*").build()))) {
            while (test.hasNext()) {
                actual.add(StringUtils.toEncodedString(test.next(), StandardCharsets.UTF_8));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        assertThat(actual, equalTo(expected));
    }
}

```
- the result we got it
```text
testa
testa
```
or 
```text
testb
testadfdf
testb
testadfdf
```
- position that may cause errors
  - RedissonConnection#scan
```java
                RFuture<ListScanResult<byte[]>> f = executorService.readAsync(client, entry, ByteArrayCodec.INSTANCE, RedisCommands.SCAN, args.toArray());
                ListScanResult<byte[]> res = syncFuture(f);
                long pos = res.getPos();
                client = res.getRedisClient();
                if (pos == 0) {
                    if (entries.hasNext()) {
                        pos = -1;
                        // reset entry but not reset redisClient
                        entry = entries.next();
                    } else {
                        entry = null;
                    }
                }

```

**Redis version**
4.0.2

**Redisson version**
- redisson: 3.15.4
- redisson-spring-data-18: 3.15.4

**Redisson configuration**
```yaml
spring:
  redis:
    cluster:
      nodes: ${nodes}
    password: ${password}
```

**Comment by yazifs** [comment]
@mrniko Is there a milestone for this bug?

**Comment by mrniko** [comment]
this method can't be implemented since `cursorId` can be the same for different nodes.

**Comment by yazifs** [comment]
This means that the `RedissonConnection#scan` method will be removed from the cluster mode later?

**Comment by mrniko** [comment]
It should be overridden in RedissonClusterConnection object and throw something like;

throw new InvalidDataAccessApiUsageException("Scan is not supported accros multiple nodes within a cluster");

**Comment by yazifs** [comment]
thanks for the answer
