### ISSUE TITLE
ConnectionListener configuration

### ISSUE THREAD

**Issue by willy23martin** [redisson/redisson#3585]
Good morning:

I hope you are doing well. 
I would like to know which is the process or thread that is used by the ConnectionListener so that the RedissonClient reconnects to the Redis Server. 

I mean we can get onConnect and onDisconnect events, but I would like to know how Redisson implements reconnection mechanisms so that the listener can trigger the onConnect event. 
Could that mechanisms (process/thread) be configured by using the YAML config? Or have a behavioral properties set by default for all the implementations that use it?

I appreciate your attention and collaboration with the related details about this topic.

**Comment by willy23martin** [comment]
Do you know how RedissonClient re-establishes the connection pool after an outage? After an onDisconnect event received, for example?

I appreciate your help.

**Comment by mrniko** [comment]
> Could that mechanisms (process/thread) be configured by using the YAML config? Or have a behavioral properties set by default for all the implementations that use it?

Why do you need this?

**Comment by willy23martin** [comment]
Thank you @mrniko  for your explanations about the re-establish process . I have been trying to understand how to set properly the YAML config file (or the Config object) so that I can improve resiliancy in the connection to the Redis Cluster.

Thank you so much. I really appreciate that.
