### ISSUE TITLE
Redisson scheduleWithFixedDelay job not running on the configured time

### ISSUE THREAD

**Issue by sriniprash** [redisson/redisson#3586]
## Background:

**Redisson version:** 3.15.0
**Framework:** Spring Boot
**Redis instance type:** Cluster mode ( Azure Cache Premium with 2 nodes )

I am using scheduleWithFixedDelay API of redisson to schedule two kinds of delayed jobs:
- repeat every 2 mins with a initial delay of 5 mins and max execution count of 5 times
- repeat every 2 mins with a initial delay of 15 mins and max execution count of 10 times

I have implemented the logic for the max execution count using RAtomicLong data type.

## Issue

When I schedule using the executor.scheduleWithFixedDelay API, the job is not executed at the expected initial delay configured. To add some more context, I spawned multiple instances of both the delayed job types and **NONE** of them ran at the expected delay ( 5 mins or 15 mins). In fact, all of them ran the next day around the same time with a delay of ~8 hours from their initial creation time.

On the other hand, jobs that I schedule with executor.execute API are running fine without any issues immediately. The problem is happening only with scheduleWithFixedDelay API.

Below is some sample source code of roughly how the delayed jobs look like along with the redissonClient / redisson node creation code.

Highly appreciate any help with this :)

### DelayedJobCreator

```java
@Service
public class DelayedJobCreator {
	@Autowired
	private final RedissonClient redissonClient;

	public void createTypeOne(DelayedJobData jobData) {
		Long initialDelay = 300 L;
		Long repeatedDelay = 120 L;
		RScheduledExecutorService executor = redissonClient
                             .getExecutorService("delayed-job-service");
		executor.scheduleWithFixedDelay(
                             new TypeOneDelayedJob(jobData), initialDelay, repeatedDelay, TimeUnit.SECONDS
                 );
	}

	public void createTypeTwo(DelayedJobData jobData) {
		Long initialDelay = 900 L;
		Long repeatedDelay = 120 L;
		RScheduledExecutorService executor = redissonClient
                             .getExecutorService("delayed-job-service");
		executor.scheduleWithFixedDelay(
                             new TypeTwoDelayedJob(jobData), initialDelay, repeatedDelay, TimeUnit.SECONDS
                 );
	}
}
```

### TypeOneDelayedJob

```java
@Slf4j
@Component
public class TypeOneDelayedJob implements Runnable, Serializable {
	private Long maxCount = 5;
	private Long maxDelay = 1800000; // 30 mins
	DelayedJobData jobData;

	@RInject
	RedissonClient redissonClient;

	@RInject
	String taskId;
	@Override
	public void run() {
		RAtomicLong count = redissonClient.getAtomicLong("countTypeOne:" + taskId);
		Long newValue = count.incrementAndGet();
		Long createdEpoch = jobData.getEpoch();
		Long currentEpoch = System.currentTimeMillis();

		RScheduledExecutorService executor = redissonClient.getExecutorService("delayed-job-service");
		if (newValue > maxCount) {
			log.info("Maximum retries hit for TypeOneDelayedJob with taskId: {}", taskId);
			executor.cancelTask(taskId);
		} else if (currentEpoch - createdEpoch > maxDelay) {
			log.info("Maximum delay TypeOneDelayedJob with taskId: {}", taskId);
			executor.cancelTask(taskId);
		} else {
			// Job logic
		}
	}
}
```

### TypeTwoDelayedJob

```java
@Slf4j
@Component
public class TypeTwoDelayedJob implements Runnable, Serializable {
	private Long maxCount = 10;
	private Long maxDelay = 1800000; // 30 mins
	DelayedJobData jobData;

	@RInject
	RedissonClient redissonClient;

	@RInject
	String taskId;
	@Override
	public void run() {
		RAtomicLong count = redissonClient.getAtomicLong("countTypeOne:" + taskId);
		Long newValue = count.incrementAndGet();
		Long createdEpoch = jobData.getEpoch();
		Long currentEpoch = System.currentTimeMillis();

		RScheduledExecutorService executor = redissonClient.getExecutorService("delayed-job-service");
		if (newValue > maxCount) {
			log.info("Maximum retries hit for TypeTwoDelayedJob with taskId: {}", taskId);
			executor.cancelTask(taskId);
		} else if (currentEpoch - createdEpoch > maxDelay) {
			log.info("Maximum delay TypeTwoDelayedJob with taskId: {}", taskId);
			executor.cancelTask(taskId);
		} else {
			// Job logic
		}
	}
}
```

### Spring bean creation - Configuration class

```java
@Bean
public Config redissonConfig() {
    Config config = new Config();
    config.useClusterServers()
        .addNodeAddress(host)
        .setPassword(password);
    return config;
}

@SneakyThrows
@Bean(destroyMethod = "shutdown")
public RedissonClient redissonClient(Config config) {
    return Redisson.create(config);
}

@Bean(destroyMethod = "shutdown")
public RedissonNode redissonNode(Config config) {
    RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
    nodeConfig.setBeanFactory(beanFactory);
    nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("delayed-job-service", 2));
    RedissonNode node = RedissonNode.create(nodeConfig);
    node.start();
    return node;
}
```

## **Update**

An update to the issue, we noticed few redisson errors in the logs related to Redisson connection timeouts i,e

```
ERROR 6 --- [isson-timer-4-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x6f24e6ea, L:/10.114.48.173:57092 - R:euw-prod-052-fps-ctwr-redis-cluster.redis.cache.windows.net/10.114.49.200:6380]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://euw-prod-052-fps-ctwr-redis-cluster.redis.cache.windows.net:6380]
at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.15.0.jar!/:3.15.0]
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) [netty-common-4.1.58.Final.jar!/:4.1.58.Final]
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) [netty-common-4.1.58.Final.jar!/:4.1.58.Final]
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) [netty-common-4.1.58.Final.jar!/:4.1.58.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.58.Final.jar!/:4.1.58.Final]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

We felt these errors were causing the scheduleWithFixedDelay to not to work properly, so to fix these connection timeouts, we set the following params to the redisson client:

```
pingConnectionInterval: 10000
keepAlive: true 
```

Post doing these configuration changes, we did not notice these timeouts for 2 days and the scheduleWithFixedDelay API did work as expected. However, we started receiving these timeouts after 2 days.

I wanted to know what is a right way to deal with this situation. Also, as mentioned before, this is ONLY happening for scheduleWithFixedDelay usecase and not the execute API. Why is this happening ONLY for the schedule API and not the execute API ?

**Comment by mrniko** [comment]
make sure that all instances have the same system clock time.

**Comment by sriniprash** [comment]
@mrniko , all the instances have the same system clock . There is an update on the issue, please check the description above.

**Comment by sriniprash** [comment]
@mrniko 

Please find the replies:

> Does this issue occur with RedissonNode instances only?

We have a RedissonNode ( embedded mode ) created to handle scheduleWithFixedDelay / execute jobs. We are noticing only the jobs created via scheduleWithFixedDelay were not running. Execute jobs are running fine. You can refer to the post above to see how we create the RedissonNode and RedissonClient from our code.
 
> Do you have any connections amount limit on Azure Cluster? Can you check if it reached at the moment of error?

We are using Azure cache premium so maximum number of connections are 7500. We are no where reaching this limit since we are running a single node ONLY.

**Comment by mrniko** [comment]
issue with ping might be related to this task https://github.com/redisson/redisson/issues/3412 Can you update to 3.15.1 or latest version>

**Comment by sriniprash** [comment]
@mrniko Sure, we can try upgrading the library version, but one question that is unanswered still is that these PING issues were impacting only the scheduleWithFixedDelay jobs. Other redis operations and the execute jobs ran fine during the same time.

**Comment by mrniko** [comment]
it may affect blockingqueue used by jobs executor
