### ISSUE TITLE
Exception in EVALSHA when referring to hash saved using LocalCachedMap

### ISSUE THREAD

**Issue by rvdesaigit** [redisson/redisson#3590]
If I use Redisson `LocalCachedMap `to save into Redis and then refer it using the `LocalCachedMap `it all works OK. 

But If i refer to that same object saved using `LocalCachedMap `in a `EVALSHA `Lua script i get this exception given below. 

If i just use `RMapCache `to save the object and refer it in the same `EVALSHA `Lua script it works OK - so this means the script has no issue. 

The issue seems to be when the script has to `unpack `an object saved using `LocalCachedMap`. 

What is the workaround / solution for this ? 

```
Exception in thread "main" org.redisson.client.RedisException: ERR Error running script (call to f_3ed22d9cfe2ba9d0d8b8f0a790d2ced8cb1ea564): @user_script:24: user_script:24: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x9310621e, L:/192.168.1.9:58359 - R:rdaws.a2omobile.com/18.206.117.202:6001] command: (EVALSHA), params: [3ed22d9cfe2ba9d0d8b8f0a790d2ced8cb1ea564, 2, VId_{NOCAChE7900c1c:5eee4437}_150998044, VPortCache_{NOCAChE7900c1c:5eee4437}, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:365)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:196)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by mrniko** [comment]
> But If i refer to that same object saved using LocalCachedMap in a EVALSHA Lua script i get this exception given below.

Can you share the code?

**Comment by rvdesaigit** [comment]
This code with localCachedMode and gives exception when executing evalSha at line 172 

`package com.redisTest;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.redisson.Redisson;
import org.redisson.api.LocalCachedMapOptions;
import org.redisson.api.LocalCachedMapOptions.EvictionPolicy;
import org.redisson.api.RLocalCachedMap;
import org.redisson.api.RMapCache;
import org.redisson.api.RScript;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.StringCodec;
import org.redisson.codec.TypedJsonJacksonCodec;
import org.redisson.config.Config;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class RedisLocalCache {

	public static void main(String[] args) throws JsonMappingException, JsonProcessingException {

	    final String FILTER_VPORT_CACHE =
	            "-- Gets latest 'n' ports\n"
	            + "-- KEYS : \n"
	            + "-- [1] : owner cache\n"
	            + "-- [2] : port cache\n"
	            + "-- ARGV : \n"
	            + "-- [1] : Number of ports to return\n"
	            + "local vport_table = {}\n"
	            + "local tableIndex = 1\n"
	            + "local vport_list\n"
	            + "local vport_id_list = redis.call(\"ZREVRANGE\", KEYS[1], 0, 99)\n"
	            + "redis.log(redis.LOG_WARNING, \"vport_id_list --->\", #vport_id_list)\n"
	            + "if #vport_id_list > 0 then\n"
	            + "    local step = 7000\n"
	            + "    if (#vport_id_list < step) then\n"
	            + "        step = #vport_id_list\n"
	            + "    end\n"
	            + "    for cnt = 1, #vport_id_list, step do\n"
	            + "        vport_list = redis.call(\"HMGET\", KEYS[2], unpack(vport_id_list, cnt, cnt + step - 1))\n"
	            + "        if vport_list then\n"
	            + "           for i, v in ipairs(vport_list) do\n"
	            + "		   		  redis.log(redis.LOG_WARNING, \"got i  --->\", print(i))\n"
	            + "		   		  redis.log(redis.LOG_WARNING, \"got v  --->\", print(v))\n"
	            + "               if v then\n"
	            + "                   local t, val = struct.unpack('dLc0', v);\n"
	            + "                   vport_table[tableIndex] = val;\n"
	            + "                   redis.log(redis.LOG_WARNING, \"VPort Val --->\", print(val))\n"
	            + "                   tableIndex = tableIndex + 1\n"
	            + "               end\n"
	            + "           end\n"
	            + "        end\n"
	            + "        if (#vport_id_list - tableIndex < step) then\n"
	            + "            step = #vport_id_list - tableIndex\n"
	            + "        end\n"
	            + "    end\n"
	            + "    redis.log(redis.LOG_WARNING, \"total count --->\", #vport_table)\n"
	            + "end\n"
	            + "return vport_table";



	     final String ADD_ID_TO_SET_CACHE =
	            "-- Adds the given vPort Id to the Set Cache. If the size of the cache exceeds the specified limit, \n"
	            + "-- the member with the lowest score is removed from the set before adding the new member \n"
	            + "-- KEYS : \n"
	            + "-- [1] : Name of the Set Cache which has the vPort Ids\n"
	            + "-- ARGV : \n"
	            + "-- [1] : The maximum number of Ids allowed in the Set Cache\n"
	            + "-- [2] : Score( Last Seen timestamp) for the new vPort Id to be added\n"
	            + "-- [3] : The new vPort Id to be added\n"
	            + "-- [4] : Expiration time for Set Cache key in seconds\n"
	            + "local set_length = redis.call(\"ZCARD\", KEYS[1])\n"
	            + "if set_length >= tonumber(ARGV[1]) then\n"
	            + "--  Items are returned from ZRANGE from lowest to highest, or from oldest to latest since\n"
	            + "--  lastSeenTime is the sorting criteria. Therefore the oldest vport is in the first array element.\n"
	            + "--  first_item[1] contains the vport cache key\n"
	            + "--  first_item[2] contains the lastSeenTime\n"
	            + "    local first_item = redis.call(\"ZRANGE\", KEYS[1], 0, 0, \"WITHSCORES\")\n"
	            + "    if first_item[2] < ARGV[2] then\n"
	            + "        local remove_oldest = redis.call(\"ZREM\", KEYS[1], first_item[1])\n"
	            + "    else\n"
	            + "        return\n"
	            + "    end\n"
	            + "end\n"
	            + "local add_set_item = redis.call(\"ZADD\", KEYS[1], ARGV[2], ARGV[3])\n"
	            + "if set_length == 0 then\n"
	            + "    local set_expire = redis.call(\"EXPIRE\", KEYS[1], ARGV[4])\n"
	            + "    redis.log(redis.LOG_VERBOSE, \"set expire for\", KEYS[1], \"to\", ARGV[4], "
	            + "        \"returned\", set_expire)\n"
	            + "end\n";


		final String[] argv = {String.valueOf(0-1)};
		System.out.println("arv = " + argv[0]);

		System.out.println("RedisTest::connecting to server = " + args[0]);
		Config config = new Config();
		if (args.length > 1 ) {
			config.useClusterServers().addNodeAddress(args[0]);
			config.useClusterServers().addNodeAddress(args[1]);
			config.useClusterServers().addNodeAddress(args[2]);
		} else {
			config.useSingleServer().setAddress(args[0]);
		}




		RedissonClient redisson = Redisson.create(config);
        RScript redisScript = redisson.getScript(StringCodec.INSTANCE);
        System.out.println("got script with codec = " + StringCodec.INSTANCE);

        // handle to LUA scripts
        String vportFilterSha = redisScript.scriptLoad(FILTER_VPORT_CACHE);
        String addToVportSha = redisScript.scriptLoad(ADD_ID_TO_SET_CACHE);
        //String fabricVportCheckSha = redisScript.scriptLoad(CHECK_IF_FABRIC_HAS_VPORTS);

        String fabricId = "LOCAL17900c2c:5eee4437";
        String mac = "66:0e:94:d2:9f:ed";
        String vlan = "4098";
        String switchId = "150998044";

        // form a vport
        VPort vport = new VPort(mac, fabricId, vlan);
        String vPortCacheName = "VId" + "_{" + fabricId + "}_" + switchId;

        // save the vport to VPortCache_{<fabID>}
        final RLocalCachedMap<Object, Object> redisMap;
        //final RMapCache<String, Object> redisMap;

        String vkey = "VPortCache" + "_{" + fabricId + "}";
        String vfield = vport.getCacheKey() ;
        System.out.println("Adding to HMap key = " + vkey + " field = " + vfield);
        final TypedJsonJacksonCodec codec = new TypedJsonJacksonCodec(String.class, VPort.class, new ObjectMapper());
        redisMap = redisson.getLocalCachedMap(vkey, codec, LocalCachedMapOptions.defaults());
        //redisMap = redisson.getMapCache(vkey, codec);
        boolean put = redisMap.fastPut(vfield, vport);
        System.out.println("Adding to HMap key = " + vkey + " field = " + vfield + " ret = " + put);

        VPort  vp1 = (VPort) redisMap.get(vfield);
        System.out.println("Got from map vport mac = " + vp1.getMac());


        // save the vport to owner sorted set
        List<Object> keys = new ArrayList<Object>();
        keys.add(vPortCacheName);
        System.out.println("Adding to SortedSet name = " + vPortCacheName + " val = " + vfield);
        List<String> argValues = new ArrayList<String>();
        argValues.add(String.valueOf(1500));
        argValues.add(System.currentTimeMillis()+"");
        vfield = "\"" + vport.getCacheKey() + "\"";
        argValues.add(vfield); //Escaping quotes to match the key stored in cache
        argValues.add(360000+""); // key expiration time in seconds
        System.out.println("Passing argv to evalsha = " + argValues);
        Integer ret = redisScript.evalSha(RScript.Mode.READ_ONLY, addToVportSha,
                RScript.ReturnType.VALUE, keys, argValues.get(0), argValues.get(1), argValues.get(2), argValues.get(3));
        System.out.println("Adding to SortedSet name = " + vPortCacheName + " ret = " + ret);

        // filter the ports from owner sorted set and port cache
        keys = new ArrayList<Object>();
        keys.add(vPortCacheName);
        keys.add("VPortCache" + "_{" + fabricId + "}");
        int count = 100;
        final String[] argValues2 = {String.valueOf(count - 1)};
        System.out.println("calling evalsha switchVportFilterSha with keys = " + keys +
        		" and argValues = " + argValues2[0]);
        List<String> filteredVports = redisScript.evalSha(RScript.Mode.READ_ONLY, vportFilterSha,
                RScript.ReturnType.MULTI, keys, "99");

        System.out.println("Got vports from evalsha  = " + filteredVports);
        for (String s : filteredVports) {
        	VPort vps = new ObjectMapper().readValue(s, VPort.class);
        	System.out.println("Got vp = " + vps.getMac() + " " + vps.getFabricId());
        }

		redisson.shutdown();

	}

}
`
This code is same except using normal (remote) cache and works OK 
`package com.redisTest;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.redisson.Redisson;
import org.redisson.api.LocalCachedMapOptions;
import org.redisson.api.LocalCachedMapOptions.EvictionPolicy;
import org.redisson.api.RLocalCachedMap;
import org.redisson.api.RMapCache;
import org.redisson.api.RScript;
import org.redisson.api.RedissonClient;
import org.redisson.client.codec.StringCodec;
import org.redisson.codec.TypedJsonJacksonCodec;
import org.redisson.config.Config;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class RedisRemoteCache {

	public static void main(String[] args) throws JsonMappingException, JsonProcessingException {

	    final String FILTER_VPORT_CACHE =
	            "-- Gets latest 'n' ports\n"
	            + "-- KEYS : \n"
	            + "-- [1] : owner cache\n"
	            + "-- [2] : port cache\n"
	            + "-- ARGV : \n"
	            + "-- [1] : Number of ports to return\n"
	            + "local vport_table = {}\n"
	            + "local tableIndex = 1\n"
	            + "local vport_list\n"
	            + "local vport_id_list = redis.call(\"ZREVRANGE\", KEYS[1], 0, 99)\n"
	            + "redis.log(redis.LOG_WARNING, \"vport_id_list --->\", #vport_id_list)\n"
	            + "if #vport_id_list > 0 then\n"
	            + "    local step = 7000\n"
	            + "    if (#vport_id_list < step) then\n"
	            + "        step = #vport_id_list\n"
	            + "    end\n"
	            + "    for cnt = 1, #vport_id_list, step do\n"
	            + "        vport_list = redis.call(\"HMGET\", KEYS[2], unpack(vport_id_list, cnt, cnt + step - 1))\n"
	            + "        if vport_list then\n"
	            + "           for i, v in ipairs(vport_list) do\n"
	            + "		   		  redis.log(redis.LOG_WARNING, \"got i  --->\", print(i))\n"
	            + "		   		  redis.log(redis.LOG_WARNING, \"got v  --->\", print(v))\n"
	            + "               if v then\n"
	            + "                   local t, val = struct.unpack('dLc0', v);\n"
	            + "                   vport_table[tableIndex] = val;\n"
	            + "                   redis.log(redis.LOG_WARNING, \"VPort Val --->\", print(val))\n"
	            + "                   tableIndex = tableIndex + 1\n"
	            + "               end\n"
	            + "           end\n"
	            + "        end\n"
	            + "        if (#vport_id_list - tableIndex < step) then\n"
	            + "            step = #vport_id_list - tableIndex\n"
	            + "        end\n"
	            + "    end\n"
	            + "    redis.log(redis.LOG_WARNING, \"total count --->\", #vport_table)\n"
	            + "end\n"
	            + "return vport_table";



	     final String ADD_ID_TO_SET_CACHE =
	            "-- Adds the given vPort Id to the Set Cache. If the size of the cache exceeds the specified limit, \n"
	            + "-- the member with the lowest score is removed from the set before adding the new member \n"
	            + "-- KEYS : \n"
	            + "-- [1] : Name of the Set Cache which has the vPort Ids\n"
	            + "-- ARGV : \n"
	            + "-- [1] : The maximum number of Ids allowed in the Set Cache\n"
	            + "-- [2] : Score( Last Seen timestamp) for the new vPort Id to be added\n"
	            + "-- [3] : The new vPort Id to be added\n"
	            + "-- [4] : Expiration time for Set Cache key in seconds\n"
	            + "local set_length = redis.call(\"ZCARD\", KEYS[1])\n"
	            + "if set_length >= tonumber(ARGV[1]) then\n"
	            + "--  Items are returned from ZRANGE from lowest to highest, or from oldest to latest since\n"
	            + "--  lastSeenTime is the sorting criteria. Therefore the oldest vport is in the first array element.\n"
	            + "--  first_item[1] contains the vport cache key\n"
	            + "--  first_item[2] contains the lastSeenTime\n"
	            + "    local first_item = redis.call(\"ZRANGE\", KEYS[1], 0, 0, \"WITHSCORES\")\n"
	            + "    if first_item[2] < ARGV[2] then\n"
	            + "        local remove_oldest = redis.call(\"ZREM\", KEYS[1], first_item[1])\n"
	            + "    else\n"
	            + "        return\n"
	            + "    end\n"
	            + "end\n"
	            + "local add_set_item = redis.call(\"ZADD\", KEYS[1], ARGV[2], ARGV[3])\n"
	            + "if set_length == 0 then\n"
	            + "    local set_expire = redis.call(\"EXPIRE\", KEYS[1], ARGV[4])\n"
	            + "    redis.log(redis.LOG_VERBOSE, \"set expire for\", KEYS[1], \"to\", ARGV[4], "
	            + "        \"returned\", set_expire)\n"
	            + "end\n";


		final String[] argv = {String.valueOf(0-1)};
		System.out.println("arv = " + argv[0]);

		System.out.println("RedisTest::connecting to server = " + args[0]);
		Config config = new Config();
		if (args.length > 1 ) {
			config.useClusterServers().addNodeAddress(args[0]);
			config.useClusterServers().addNodeAddress(args[1]);
			config.useClusterServers().addNodeAddress(args[2]);
		} else {
			config.useSingleServer().setAddress(args[0]);
		}




		RedissonClient redisson = Redisson.create(config);
        RScript redisScript = redisson.getScript(StringCodec.INSTANCE);
        System.out.println("got script with codec = " + StringCodec.INSTANCE);

        // handle to LUA scripts
        String vportFilterSha = redisScript.scriptLoad(FILTER_VPORT_CACHE);
        String addToVportSha = redisScript.scriptLoad(ADD_ID_TO_SET_CACHE);
        //String fabricVportCheckSha = redisScript.scriptLoad(CHECK_IF_FABRIC_HAS_VPORTS);

        String fabricId = "REMOTE17900c1c:5eee4437";
        String mac = "66:0e:94:d2:9f:ed";
        String vlan = "4098";
        String switchId = "150998044";

        // form a vport
        VPort vport = new VPort(mac, fabricId, vlan);
        String vPortCacheName = "VId" + "_{" + fabricId + "}_" + switchId;

        // save the vport to VPortCache_{<fabID>}
        //final RLocalCachedMap<Object, Object> redisMap;
        final RMapCache<String, Object> redisMap;

        String vkey = "VPortCache" + "_{" + fabricId + "}";
        String vfield = vport.getCacheKey() ;
        System.out.println("Adding to HMap key = " + vkey + " field = " + vfield);
        final TypedJsonJacksonCodec codec = new TypedJsonJacksonCodec(String.class, VPort.class, new ObjectMapper());
        //redisMap = redisson.getLocalCachedMap(vkey, codec, LocalCachedMapOptions.defaults());
        redisMap = redisson.getMapCache(vkey, codec);
        boolean put = redisMap.fastPut(vfield, vport);
        System.out.println("Adding to HMap key = " + vkey + " field = " + vfield + " ret = " + put);

        VPort  vp1 = (VPort) redisMap.get(vfield);
        System.out.println("Got from map vport mac = " + vp1.getMac());


        // save the vport to owner sorted set
        List<Object> keys = new ArrayList<Object>();
        keys.add(vPortCacheName);
        System.out.println("Adding to SortedSet name = " + vPortCacheName + " val = " + vfield);
        List<String> argValues = new ArrayList<String>();
        argValues.add(String.valueOf(1500));
        argValues.add(System.currentTimeMillis()+"");
        vfield = "\"" + vport.getCacheKey() + "\"";
        argValues.add(vfield); //Escaping quotes to match the key stored in cache
        argValues.add(360000+""); // key expiration time in seconds
        System.out.println("Passing argv to evalsha = " + argValues);
        Integer ret = redisScript.evalSha(RScript.Mode.READ_ONLY, addToVportSha,
                RScript.ReturnType.VALUE, keys, argValues.get(0), argValues.get(1), argValues.get(2), argValues.get(3));
        System.out.println("Adding to SortedSet name = " + vPortCacheName + " ret = " + ret);

        // filter the ports from owner sorted set and port cache
        keys = new ArrayList<Object>();
        keys.add(vPortCacheName);
        keys.add("VPortCache" + "_{" + fabricId + "}");
        int count = 100;
        final String[] argValues2 = {String.valueOf(count - 1)};
        System.out.println("calling evalsha switchVportFilterSha with keys = " + keys +
        		" and argValues = " + argValues2[0]);
        List<String> filteredVports = redisScript.evalSha(RScript.Mode.READ_ONLY, vportFilterSha,
                RScript.ReturnType.MULTI, keys, "99");

        System.out.println("Got vports from evalsha  = " + filteredVports);
        for (String s : filteredVports) {
        	VPort vps = new ObjectMapper().readValue(s, VPort.class);
        	System.out.println("Got vp = " + vps.getMac() + " " + vps.getFabricId());
        }

	redisson.shutdown();

	}

}
`

**Comment by mrniko** [comment]
RMapCache value format differs from RLocalCachedMap.

**Comment by rvdesaigit** [comment]
Thanks this fixed the issue, BTW what is the diff between the 2? 
Anyother caveats we need to be aware of if using LocalCachedMode ?  

thanks
