### ISSUE TITLE
Tomcat 9 Redisson keeps hit Redis memory limit

### ISSUE THREAD

**Issue by Ethns** [redisson/redisson#3591]
Description
Hi team,

We're encountering an issue in production env that Redisson client keeps hit the maxmemory limit of Redis, we're using AWS Elasticache Redis with cluster mode disabled, have upgraded the node type from t2.small to cache.t3.medium, but it still too small.
We're wondering if it's an issue that others may also experience, are there any potential solutions for us to try?

Version: 
redisson-all: 3.13.5
redisson Tomcat 9: 3.13.5
Error message from Tomcat log:
```
org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'
```

Redisson config:
```
{
    "singleServerConfig": {
        "idleConnectionTimeout": 10000,
        "connectTimeout": 10000,
        "timeout": 3000,
        "retryAttempts": 3,
        "retryInterval": 1500,
        "password": xxxxxx,
        "subscriptionsPerConnection": 5,
        "clientName": xxxxx,
        "address": "rediss://xxxxxxxxx:6379",
        "subscriptionConnectionMinimumIdleSize": 1,
        "subscriptionConnectionPoolSize": 50,
        "connectionMinimumIdleSize": 24,
        "connectionPoolSize": 64,
        "database": 0
    },
    "threads": 0,
    "nettyThreads": 0,
    "codec": {
         "class": "org.redisson.codec.FstCodec"
     },
     "transportMode": "NIO"
}
```

**Comment by mrniko** [comment]
did you try to look at stored data in Redis?

**Comment by NSGReaper** [comment]
I'm in the same team that is dealing with this issue. We are specifically only using redisson for tomcat session management. There is no direct usage by the application code. There are a suprising number of keys that have no TTL and we are seeing usage creep up over time.

You can see from this AWS CloudWatch chart that each day it spikes with usage but when the spikes recover total usage stays up over the day before.
![image](https://user-images.githubusercontent.com/17676503/117102277-57e44780-adbb-11eb-842a-1ed6547a35b2.png)

Keyspace INFO:
# Keyspace
db0:keys=5661,expires=701,avg_ttl=1355923
I'm not sure I understand why there are so many keys without an expiry/ttl.

Finally the memory breakdown from INFO:
# Memory
used_memory:2674191880
used_memory_human:2.49G
used_memory_rss:2489122816
used_memory_rss_human:2.32G
used_memory_peak:3595889664
used_memory_peak_human:3.35G
used_memory_peak_perc:74.37%
used_memory_overhead:9719458
used_memory_startup:4798648
used_memory_dataset:2664472422
used_memory_dataset_perc:99.82%
allocator_allocated:2688434376
allocator_active:2695032832
allocator_resident:2706841600
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:10527885773
maxmemory_human:9.80G
maxmemory_policy:volatile-lru
allocator_frag_ratio:1.00
allocator_frag_bytes:6598456
allocator_rss_ratio:1.00
allocator_rss_bytes:11808768
rss_overhead_ratio:0.92
rss_overhead_bytes:-217718784
mem_fragmentation_ratio:0.93
mem_fragmentation_bytes:-185028032
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:17106
mem_clients_normal:3488184
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

**Comment by mrniko** [comment]
I mean content of stored data stored by application.

**Comment by mrniko** [comment]
Can you check if these sessions have "session:isExpirationLocked" = true?

**Comment by mrniko** [comment]
Can you attach list of names without ttl?

**Comment by NSGReaper** [comment]
Well, it looks like its the session hashes themselves that don't have a TTL. This is just a sample by picking a key at random. Pardon the weird output, openssl was used rather than a redis client due to not having a redis binary with TLS support.
```
HGETALL pnet:redisson:tomcat_session:7D0A2B5257E70311E9FC6E7FC7BEFACB
*12
$24
session:thisAccessedTime
$10
▒▒▒x
$24
session:lastAccessedTime
$10
▒▒▒x
$13
session:isNew
$1
▒
$27
session:maxInactiveInterval
$2
▒▒
$15
session:isValid
$1
▒
$20
session:creationTime
$2
▒
```

```
TTL pnet:redisson:tomcat_session:7D0A2B5257E70311E9FC6E7FC7BEFACB
:-1
```

I would have expected a TTL between 0 and 30mins (Tomcat's session timeout).

**Comment by mrniko** [comment]
@NSGReaper 

Can you share Session Manager configuration?

**Comment by NSGReaper** [comment]
<Manager className="org.redisson.tomcat.RedissonSessionManager"
          configPath="/tomcat/properties/redisson.json" readMode="MEMORY" updateMode="AFTER_REQUEST" keyPrefix="pnet"/>

The contents of 'redisson.json' is in the original post under "Redisson config"

**Comment by mrniko** [comment]
Are all these session without ttl contain only 6 fields?

**Comment by NSGReaper** [comment]
I sampled a number of random keys found using scan. I did not find any with additional fields. I did find some that had a TTL of a positive number, most were -1.

**Comment by mrniko** [comment]
do you use sticky session?

**Comment by NSGReaper** [comment]
Yes, they are sticky However... the same tomcat container receives UI traffic and webservice traffic. If sessions are being created for the webservice traffic that would explain why there are so many small ones, but I would have thought they would still expire.

**Comment by Ethns** [comment]
There's another Tomcat that shares the same Redis but with a different Session Manager configuration, tho the only difference is this one sets the readMode=`REDIS` instead of `MEMORY`

**Comment by mrniko** [comment]
@NSGReaper 

Can you share web.xml ?

**Comment by NSGReaper** [comment]
I did some more analysis of our keys. There are no sessions with 'session:isExpirationLocked' as a field. There were 11 (out of ~10,000) with 'session:principal' and 'session:authtype' set, and they were keys that had an expiry. The vast majority of the expired sessions have no real session data stored, which makes me suspect they were created by webservice calls. That is unfortunate and unwanted, but I'm not sure it explains why they have no expiry.


web.xml with mimemappings snipped out:
```
<?xml version="1.0" encoding="UTF-8"?>

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                      http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
  version="4.0">

    <servlet>
        <servlet-name>default</servlet-name>
        <servlet-class>org.apache.catalina.servlets.DefaultServlet</servlet-class>
        <init-param>
            <param-name>debug</param-name>
            <param-value>0</param-value>
        </init-param>
        <init-param>
            <param-name>listings</param-name>
            <param-value>false</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet>
        <servlet-name>jsp</servlet-name>
        <servlet-class>org.apache.jasper.servlet.JspServlet</servlet-class>
        <init-param>
            <param-name>fork</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>xpoweredBy</param-name>
            <param-value>false</param-value>
        </init-param>
        <load-on-startup>3</load-on-startup>
    </servlet>

    <!-- The mapping for the default servlet -->
    <servlet-mapping>
        <servlet-name>default</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>

    <!-- The mappings for the JSP servlet -->
    <servlet-mapping>
        <servlet-name>jsp</servlet-name>
        <url-pattern>*.jsp</url-pattern>
        <url-pattern>*.jspx</url-pattern>
    </servlet-mapping>

    <filter>
        <filter-name>httpHeaderSecurity</filter-name>
        <filter-class>org.apache.catalina.filters.HttpHeaderSecurityFilter</filter-class>
        <async-supported>true</async-supported>
        <init-param>
            <param-name>antiClickJackingOption</param-name>
            <param-value>SAMEORIGIN</param-value>
        </init-param>
        <init-param>
            <param-name>hstsIncludeSubDomains</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>hstsMaxAgeSeconds</param-name>
            <param-value>15768000</param-value>
        </init-param>
    </filter>


    <filter-mapping>
        <filter-name>httpHeaderSecurity</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
    </filter-mapping>


    <session-config>
        <session-timeout>30</session-timeout>
    </session-config>

<!--- SNIP MIME MAPPING -->

    <welcome-file-list>
        <welcome-file>index.html</welcome-file>
        <welcome-file>index.htm</welcome-file>
        <welcome-file>index.jsp</welcome-file>
    </welcome-file-list>

</web-app>
```

**Comment by mrniko** [comment]
> suspect they were created by webservice calls. That is unfortunate and unwanted

Does it mean that webservice doesn't use session at all? Did you share global web.xml or webservice's?

**Comment by NSGReaper** [comment]
After much digging I have found what look like real UI sessions with the expected session data stored in them, with a TTL of -1. To confirm, does redisson only set an expire value when it thinks a session has timed out or does it set one when the session is created and then increase it as the session is used?

**Comment by mrniko** [comment]
Session timeout controlled by Session.setMaxInactiveInterval() which is invoked by `org.apache.catalina.session.ManagerBase.createSession()` method. Redisson doesn't invoke it explicitly.

**Comment by NSGReaper** [comment]
That was global. I've attached the application's one. Webservices do not deliberately store or retreive session data, unless Apache Axis is doing something on its own. 

To confirm though, if setMaxInactiveInterval is invoked does redisson honor it by using redis' built in expire feature? Or does it decide a session has expired based on its session:lastAccessedTime or something similar and then set a redis expiry only after Tomcat declares the session expired?

[application-web-xml.txt](https://github.com/redisson/redisson/files/6431989/application-web-xml.txt)

**Comment by mrniko** [comment]
Redisson sets session expiration through PEXPIRE command if setMaxInactiveInterval called by org.apache.catalina.session.ManagerBase.

**Comment by mrniko** [comment]
This is how ManagerBase set timeout:

`session.setMaxInactiveInterval(getContext().getSessionTimeout() * 60);`

Please define it in application-web.xml

**Comment by Ethns** [comment]
> This is how ManagerBase set timeout:
> 
> `session.setMaxInactiveInterval(getContext().getSessionTimeout() * 60);`
> 
> Please define it in application-web.xml

**Comment by NSGReaper** [comment]
Session timeout is defined on line 119 of the file I attached:
```
	<session-config>
		<session-timeout>30</session-timeout>
	</session-config>
```

Is there some other session config you think is missing?

**Comment by mrniko** [comment]
unable to reproduce it. PEXPIRE command is always executed.

**Comment by mrniko** [comment]
@NSGReaper 

Can you share redisson log with `TRACE` logging level for `org.redisson` package?
