### ISSUE TITLE
Duplicated section 6.12 in English documentation (wiki pages)

### ISSUE THREAD

**Issue by c00ler** [redisson/redisson#3592]
**Expected behavior**
There is only one section `6.12 RateLimiter` in the English version of the documentation.

**Actual behavior**
Section `6.12 RateLimiter` is duplicated in the English version of the documentation. 

**Steps to reproduce or test case**
https://github.com/redisson/redisson/wiki/6.-distributed-objects#612-ratelimiter

**Redis version**
N/A

**Redisson version**
N/A

**Redisson configuration**
N/A

**Comment by mrniko** [comment]
Thanks for pointing out! Fixed
