### ISSUE TITLE
When using distributed locks, why not use the JVM locks first to reduce the pressure of redis?

### ISSUE THREAD

**Issue by tanzheng231** [redisson/redisson#3593]
When using distributed locks, why not use the JVM locks first to reduce the pressure of redis?

**Comment by mrniko** [comment]
can you provide more information about what you are trying to accomplish?

**Comment by michael-o** [comment]
> 
> 
> When using distributed locks, why not use the JVM locks first to reduce the pressure of redis?

That's sounds like non-sense, doesn't it?
