### ISSUE TITLE
Setter detection in Jackson codec

### ISSUE THREAD

**Issue by janrieke** [redisson/redisson#3594]
We are using Jackson-based (de)serialization. Our DTOs are immutable and use Lombok's [`@Jacksonized`](https://projectlombok.org/features/experimental/Jacksonized) [`@Builder`](https://projectlombok.org/features/Builder) (so no setters in those classes).
To our surprise, this does not work in all cases. When deserializing with a "pure" Jackson, everything works fine. But when using Redisson, Lombok's `@Builder.Default` breaks deserialization. In this case, the generated builder class does not have a matching field for the JSON property. For instance, a field `String example` in the DTO will result in two fields in the builder: `String example$value` and `boolean example$set`. None of them matches the JSON property `example` (serialized from the DTO). However, there is a matching setter method `example(String)`, which is used by Jackson in that case.

After a bit of debugging, we found the reason why it works with Jackson directly, but not in Redisson: [`JsonJacksonCodec` explicitly switches off the detection of setters](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/codec/JsonJacksonCodec.java#L167), but only relies on fields (which is obviously not sufficient in this case). The solution is easy: We simply use our own codec that extends `JsonJacksonCodec`, switch on the setter detection and everything seems to work again.

However, the question remains: Why does Redisson explicitly deactivate the detection of setters (and getters, too)? Is there any drawback in allowing it, like we did?

**Comment by mrniko** [comment]
Serialization is applied by state - object fields. But you can always extend JsonJacksonCodec to make up it for your needs.

**Comment by janrieke** [comment]
Thanks for your answer.
