### ISSUE TITLE
Connection pooling mechanism in redisson

### ISSUE THREAD

**Issue by ankitgooner** [redisson/redisson#3595]
HI Team,
I had a doubt regarding redisson connection pooling management.

I have an application with a high volume of traffic and hence get a lot of concurrent requests.
Have optimised my connection pool accordingly.But i have the following query

What if a new request arrives and all the connections are busy in case of unprecedented volume.

How does redisson handle such scenarios.Is there a connection request time out , post which it tries to create a new connection if pool is exhausted OR the request is rejected in absence of a connection in the pool .

regards,
AC

**Comment by mrniko** [comment]
> Is there a connection request time out , post which it tries to create a new connection if pool is exhausted OR the request is rejected in absence of a connection in the pool .

Redisson makes a new attempts to execute command according to `retryInterval` and `retryAttempts` settings.
