### ISSUE TITLE
No usable error message when failure parsing redisson-jcache.yaml

### ISSUE THREAD

**Issue by NottyCode** [redisson/redisson#3598]
@edburns was trying to get Open Liberty to persist http session cache data with Redis using redisson-jcache. Something that I (and the Open Liberty team) have not done before. He got the Open Liberty configuration setup correctly, but was getting an exception (see Actual Behaviour section). After much debugging we discovered it was because there was a typo in the yaml meaning there was an exception while parsing it. However the JCachingProvider.loadConfig method is just swallowing all exceptions that occur which means there was no error message anyone could use to determine what went wrong. I managed to track down the problem by inserting a printStackTrace into the IOException catch blocks, but I don't think that would be a PR that the Redisson team would wish to take.

**Expected behavior**
Useful error message like this:

    Unrecognized field "clusterServerConfig" (class org.redisson.config.Config), not marked as ignorable (23 known properties: "eventLoopGroup", "maxCleanUpDelay", "nettyHook", "keepPubSubOrder", "nettyThreads", "threads", "transportMode", "singleServerConfig", "sentinelServersConfig", "reliableTopicWatchdogTimeout", "useScriptCache", "minCleanUpDelay", "connectionListener", "executor", "codec", "replicatedServersConfig", "clusterServersConfig", "useThreadClassLoader", "masterSlaveServersConfig", "addressResolverGroupFactory", "lockWatchdogTimeout", "cleanUpKeysAmount", "referenceEnabled"])

**Actual behavior**
Cryptic exception is thrown:

    java.lang.IllegalStateException: Default configuration hasn't been specified!

**Steps to reproduce or test case**

take the configuration listed in the last section of the bug report and store it in redisson-jcache.yaml then run the following:

        MutableConfiguration<String, String> config = new MutableConfiguration<>();
        config.setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(new Duration(TimeUnit.SECONDS, 1)));
        config.setStoreByValue(true);
        
        URI configUri = getClass().getResource("redisson-jcache.yaml").toURI();
        Cache<String, String> cache = Caching.getCachingProvider().getCacheManager(configUri, null)
                .createCache("test", config);

**Redis version**

6.2.3

**Redisson version**

3.15.4

**Redisson configuration**

    clusterServerConfig:
      password: ${clusterServerConfig.password}
      nodeAddresses:
      - ${clusterServerConfig.nodeAddresses}

**Comment by mrniko** [comment]
Can you share some example how to config Open Liberty with Redisson for http session cache? I would add it to documentation.

**Comment by NottyCode** [comment]
To configure Liberty you would do this:

```
<server>
    <featureManager>
        <feature>servlet-4.0</feature>
        <feature>sessionCache-1.0</feature>
    </featureManager>

    <httpSessionCache uri="file:///${shared.resource.dir}redisson-jcache.yaml">
        <library>
            <fileset dir="${shared.resource.dir}/redisson"/>
        </library>
    </httpSessionCache>
</server>
```

**Comment by mrniko** [comment]
Which jars are contained in "${shared.resource.dir}/redisson" dir ?
