### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Unable to send command

### ISSUE THREAD

**Issue by yanghuijava** [redisson/redisson#3604]
In a production environment, we use the redis is cloud services, in the event of network jitter occurs after org. Redisson. Client. RedisTimeoutException, specific exception is as follows:

`org.redisson.client.RedisTimeoutException: Unable to send command! Try to increase 'nettyThreads' and/or connection pool size settings Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=7, freeConnectionsCounter=value:97:queue:0, freezed=false, freezeReason=null, client=[addr=redis://pro-rdb-142.ms.uu.cc:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@293101102 [redisClient=[addr=redis://pro-rdb-142.ms.uu.cc:6379], channel=[id: 0xf40f1b91, L:/10.2.89.47:23078 - R:pro-rdb-142.ms.uu.cc/10.2.90.142:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7d55c2c0(failure: java.util.concurrent.CancellationException)], command=(EVAL), params=[local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, ms-pcsys:V1:11828:3.8.0, redisson__timeout__set:{ms-pcsys:V1:11828:3.8.0}, redisson__idle__set:{ms-pcsys:V1:11828:3.8.0}, redisson__map_cache__last_access__set:{ms-pcsys:V1:11828:3.8.0}, {ms-pcsys:V1:11828:3.8.0}:redisson_options, 1620636461408, PooledUnsafeDirectByteBuf(freed)], codec=org.redisson.codec.JsonJacksonCodec]], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, ms-pcsys:V1:10313:5.14.0, redisson__timeout__set:{ms-pcsys:V1:10313:5.14.0}, redisson__idle__set:{ms-pcsys:V1:10313:5.14.0}, redisson__map_cache__last_access__set:{ms-pcsys:V1:10313:5.14.0}, {ms-pcsys:V1:10313:5.14.0}:redisson_options, 1620636464643, PooledUnsafeDirectByteBuf(ridx: 0, widx: 38, cap: 256)] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:220)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)`

Once this exception occurs, even if the network is back to normal, this exception will not disappear, can only restart the service.Has anyone ever had this problem?What configuration can be used to solve this problem?

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by yanghuijava** [comment]
We've seen this before, but it doesn't solve our problem

**Comment by yanghuijava** [comment]
@mrniko We've seen this before, but it doesn't solve our problem

**Comment by yanghuijava** [comment]
@mrniko 
redisson.connectionPoolSize=100
redisson.timeout=3000
redisson.connectionMinimumIdleSize=10
The rest is default.

**Comment by yanghuijava** [comment]
In addition, the version of Redisson I use is 3.11.4.

**Comment by yanghuijava** [comment]
@mrniko My phenomenon is similar to this:https://github.com/redisson/redisson/issues/2947，However, we use Arthas to view the closed property of the RedisConnection object as false again.

**Comment by yanghuijava** [comment]
My phenomenon is similar to this:https://github.com/redisson/redisson/issues/2947
However, we use Arthas to view the closed property of the RedisConnection object as false again.

**Comment by yanghuijava** [comment]
My phenomenon is similar to this:
https://github.com/redisson/redisson/issues/2947
However, we use Arthas to view the closed property of the RedisConnection object as false again.

**Comment by yanghuijava** [comment]
@mrniko 
Hi
I set the value of `pingConnectionInterval` to 10000, but the service started with an error：
`Initialization of bean failed; nested exception is org.redisson.client.RedisTimeoutException: Subscribe timeout: (9500ms). 
Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters`
I searched for a long time but couldn't find the problem。
Can you shed some additional information please？

**Comment by mrniko** [comment]
did you try to increase these settings?

**Comment by yanghuijava** [comment]
I've already set it, but it still doesn't work

**Comment by yanghuijava** [comment]
@mrniko I have increased these configurations, but they still don't work

**Comment by mrniko** [comment]
Is there sample code to reproduce the issue?

**Comment by yanghuijava** [comment]
@mrniko Sorry, I stripped our project to reproduce, but it didn't reproduce.In our project, we use a delay queue and use the pingconnectionInterval parameter. It will report an error on startup. I really can't find the reason.

**Comment by jatinshashoo** [comment]
Upgrading to v3.15.5 will probably fix this issue. We have similar logs in our application which connects to Redis on AWS 
 and whenever there is a failover or a network jitter, the application has to be restarted.

I upgraded Redisson to 3.15.5 and have tested Redis failover on Staging and it seems to reconnect automatically. Haven't gone to Production yet.

**Comment by yanghuijava** [comment]
@jatinshashoo Thank you. I have upgraded to version 3.15.5. I will watch it when it goes online
