### ISSUE TITLE
How to isolate MapListener to a single database

### ISSUE THREAD

**Issue by mcacker** [redisson/redisson#3606]
I have some code which adds a listener

`					rmapCache.addListener(new EntryCreatedListener<String, Object>() {
						@Override
						public void onCreated(EntryEvent<String, Object> event) {
							publishRedisEvent(new RedisEvent(cacheKey, event));
						}
					});
`

which works great, apart from the fact that I'm getting notifications on events in databases i'm not using.  I.e., i'm using database 0, but I get events from database 1.  

How can I isolate events to the database that i'm using.

thanks, Mitchell

**Comment by mcacker** [comment]
To answer my own question, I've prefixed the key names with the database number.  It's less than ideal, but seems to work fine.

It would be nice if we could inject a channel name for the events so that wouldn't have to be done.

I'd still like to hear of any alternatives

**Comment by mrniko** [comment]
>  I've prefixed the key names with the database number

I can use `nameMapper` setting for this.
