### ISSUE TITLE
use bitfield get StackOverFlowException

### ISSUE THREAD

**Issue by waterchris** [redisson/redisson#3608]
**Expected behavior**
return 13
**Actual behavior**
java.lang.StackOverflowError
	at org.springframework.data.redis.connection.DefaultedRedisConnection.bitField(DefaultedRedisConnection.java:420)
	
**Steps to reproduce or test case**
String key = "ccc";
        stringRedisTemplate.opsForValue().setBit(key,0,true);
        stringRedisTemplate.opsForValue().setBit(key,1,true);
        stringRedisTemplate.opsForValue().setBit(key,2,false);
        stringRedisTemplate.opsForValue().setBit(key,3,true);
        System.out.println(stringRedisTemplate.opsForValue().getBit(key,2));
        System.out.println(stringRedisTemplate.execute((RedisCallback<Long>) con -> con.bitCount(key.getBytes())).intValue());
        List<Long> longs = stringRedisTemplate.execute((RedisCallback<List<Long>>) con -> con.bitField(key.getBytes(),
                BitFieldSubCommands.create().get(BitFieldSubCommands.BitFieldType.unsigned(63)).valueAt(0)));
        
**Redis version**
6.2.1
**Redisson version**
3.15.0
**Redisson configuration**
redis:
    host: 
    port: 6379
    password: 
    database: 3
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3630
