### ISSUE TITLE
RLocalCachedMap.containsKey doesn't fire loader 

### ISSUE THREAD

**Issue by abishai** [redisson/redisson#3609]
**Expected behavior**
containsKey looks for a key in local cache, then in redis, and, at last, invokes loader. If loader returns entry, put it in cache and report true.

**Actual behavior**
containsKey doesn't invoke loader at all and returns false for cold local cache/redis.

**Steps to reproduce or test case**
I have a map with loader, however for cold local cache and cold redis, this snipped produces different output
```
    final override fun isExists() = instrumentMap.containsKey(instrumentId)
    final fun isExists2() = instrumentMap[instrumentId] != null
```
The first one is false if cache + redis is empty, loader is not invoked. The second call invokes loader and populates cache. Subsequent containsKey calls start to work after that. 
Probably, other Map implementations contains this issue.

**Redis version**
6.0

**Redisson version**
3.15.5
**Redisson configuration**
Single server, LocalCachedMapOptions.defaults() with loader.

**Comment by mrniko** [comment]
Fixed! Thanks for report
