### ISSUE TITLE
RDeque needs popRange()

### ISSUE THREAD

**Issue by Ecauchy** [redisson/redisson#3610]
[RList already got its subList() method](https://github.com/redisson/redisson/issues/2080), but RDeque still could not pop multiple elements at one time.
This limits a lot RDeque's usage, and I have to use RList instead.

Redis realization[python]:
```
import redis
client = redis.Redis()

def batch_lpop(key, n):
    p = client.pipeline()
    p.lrange(key, 0, n - 1)
    p.ltrim(key, n, -1)
    data = p.execute()
    return data

batch_lpop('test_pipeline', 20)
```

**Comment by mrniko** [comment]
You can use `RDeque.poll(int limit)` method instead.

**Comment by Ecauchy** [comment]
Many thanks. It seems that I use a too much outdated version of Redisson.
