### ISSUE TITLE
can dependency on javax.cache be optional?

### ISSUE THREAD

**Issue by BigMichi1** [redisson/redisson#3613]
the pom.xml from org.redisson:redisson pulls in the caching API from javax. as we do not use this in our projects at all, can this one be made optional? or if not is an exclusion on our side safe?

**Comment by michael-o** [comment]
There are many dependencies pointless if not uses, e.g., cache, reactive, etc. That's a pity. The project misses modularity.

**Comment by mrniko** [comment]
cache, reactive and rx libs are optional and can be removed from classpath.

**Comment by michael-o** [comment]
Haha, that's perfect. I will try that. Unfortunately,  the aren't marked as optional in the POM.

**Comment by abishai** [comment]
I've marked as excluded a lot of redisson dependencies and it's still works, so you can do  the same.
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

**Comment by mrniko** [comment]
List of required dependencies described here https://github.com/redisson/redisson/wiki/15.-Dependency-list

**Comment by mrniko** [comment]
> Unfortunately, the aren't marked as optional in the POM.

They aren't optional since users who want to use reactive or rxjava interfaces may face classnotfound in this case.

**Comment by michael-o** [comment]
> 
> 
> List of required dependencies described here https://github.com/redisson/redisson/wiki/15.-Dependency-list

Great one, I can exclude them directly in the Maven Resolver POM.
