### ISSUE TITLE
AWS ElasticCache Redis(Cluster Mode Disabled) Cannot Find Redis Node After Failover

### ISSUE THREAD

**Issue by DarrenChenGo** [redisson/redisson#3615]
We are using Redission to connect AWS ElasticCache Redis(Cluster Mode Disabled), but we found exception below, even we upgraded to the version 3.15.1. And we don't see these exception unit we restart our service. 

Exception:

org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=null, addr=null, redisClient=[addr=redis://xxx.cache.amazonaws.com:6379], redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:999:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:10000:queue:0, freezed=false, freezeReason=null, client=[addr=redis://xxx.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0]]] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
at org.redisson.connection.MasterSlaveConnectionManager.createNodeNotFoundFuture(MasterSlaveConnectionManager.java:647)
at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:629)
at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:643)
at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:115)
at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:243)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

Version:

Redission: 3.15.1
AWS ElasticCache Redis(Cluster Mode Disabled): 5.0.6

Config:

Config config = new Config();
config.useSingleServer().setAddress("redis://" + host + ":" + port)
                .setConnectTimeout(30000)
                .setSubscriptionsPerConnection(5000)
                .setSubscriptionConnectionPoolSize(1000)
                .setConnectionPoolSize(10000)
                .setPingConnectionInterval(1000)
                .setRetryInterval(3000);

Do I need to change the config to useReplicatedServer() or useSingleServer() also can support AWS ElasticCache Redis(Cluster Mode Disabled)

Thanks a lot!

**Comment by mrniko** [comment]
You need to use useReplicatedServer() for non-clustered AWS ElasticCache Redis setup.

**Comment by DarrenChenGo** [comment]
Hi 
I just replace the useSingleServer() with useReplicatedServer(), but now there is another exception is "too many open files" when do the concurrent test, below is my redission config, please take a look, thank you!

Config config = new Config();
        if ("localhost".equalsIgnoreCase(host)) {
            config.useSingleServer().setAddress("redis://" + host + ":" + port)
                    .setConnectTimeout(30000)
                    .setSubscriptionsPerConnection(5000)
                    .setSubscriptionConnectionPoolSize(1000)
                    .setPingConnectionInterval(1000)
                    .setRetryInterval(3000);
        } else {
            List<String> hosts = new ArrayList<>();
            if (StringUtils.isNotBlank(nodes)) {
                hosts.addAll(Arrays.asList(nodes.split(",")));
            } else {
                hosts.add(host);
            }
            ReplicatedServersConfig serverConfig = config.useReplicatedServers();
            hosts.forEach(h  -> serverConfig.addNodeAddress("redis://" + h + ":" + port));
            serverConfig.setConnectTimeout(5000)
                    .setSubscriptionsPerConnection(5000)
                    .setSubscriptionConnectionPoolSize(1000)
                    .setPingConnectionInterval(1000)
                    .setRetryInterval(3000)
                    .setMasterConnectionPoolSize(5000)
                    .setSlaveConnectionPoolSize(5000)
                    .setTimeout(5000);
        }
        config.setEventLoopGroup(new NioEventLoopGroup());
        return Redisson.create(config);

**Comment by mrniko** [comment]
I think you need to decrease connections amount

**Comment by winfet** [comment]
we got the same exception with redisson 3.13.3. Every time after failover we got an RedisNodeNotFoundException.
But the exception only happens when we call RKey.deletebyPattern.  
After update to 3.16.7 the problem not happen again. 
Can someone tell me which commit solved this problem?
