### ISSUE TITLE
Make storeMode = LOCAL to fire loader

### ISSUE THREAD

**Issue by abishai** [redisson/redisson#3617]
My application has caffeine **local** cache and I'd like to use redisson for this, just like normal distributed map. I've configured store mode and provided loader, however loader doesn't start.

I've looked into code and it looks like this option was never considered, so, probably not a bug, however I think, loader and store mode should be compatible with each other.

**Describe the solution you'd like**
Run loader and store result in local cache.

**Describe alternatives you've considered**
Dedicated caffeine instance

**Comment by mrniko** [comment]
Can you share code you tried to use?

**Comment by abishai** [comment]
Sure, here you are: https://github.com/abishai/redisson-local/blob/master/src/main/kotlin/example/Main.kt
I have a local caffeine cache in my application to cache small static database tables I access by primary key and when I found redisson local cache mode, I though I can seamlessly switch to redisson as described https://github.com/redisson/redisson/wiki/7.-distributed-collections#712-map-persistence however I've found that loaders are ignored in this mode. 

I'm not sure if this case is in scope of the project, though, however it would be nice and we already have local cache mode for something.

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by abishai** [comment]
Thanks! This will help to unify some things in my code.
