### ISSUE TITLE
the wiki "11. Redis commands mapping", "CONFIG GET/SET" method is wrong

### ISSUE THREAD

**Issue by h2lin** [redisson/redisson#3620]
wiki "11. Redis commands mapping" 
----- wrong
CONFIG GET -> RedisNode.
			  setConfig()
			  setConfigAsync()

CONFIG SET -> RedisNode.
			  getConfig()
			  getConfigAsync()
----- correct
CONFIG GET -> RedisNode.
			  getConfig()
			  getConfigAsync()

CONFIG SET  -> RedisNode.
			  setConfig()
			  setConfigAsync()

**Comment by mrniko** [comment]
Fixed. Thanks for pointing out
