### ISSUE TITLE
Will RLOS indexed based querying work in cluster enabled Redis?

### ISSUE THREAD

**Issue by mayurgoenka** [redisson/redisson#3626]
When we use cluster enabled Redis like AWS EC, it's possible that objects gets stored on different shards. Will the indexed based querying still work here?

**Comment by mrniko** [comment]
Sharded index supported only in PRO version.

**Comment by mayurgoenka** [comment]
I really appreciate the quick turnaround. You are doing a great job @mrniko. Thanks a lot!

**Comment by mrniko** [comment]
@mayurgoenka 

Thank you!

**Comment by mayurgoenka** [comment]
Hi @mrniko , 
I see that the index is created in the following fashion:
`"redisson_live_object_index:{com.org.application.MyLiveObject}:index_field:<some_hash>"`

I see that we are using hash tag : `{com.org.application.MyLiveObject}` for storing all indices belonging to same class inside same keyslot.

In my use case, m trying to store billions of objects of the same class MyLiveObject and there are multiple indices as well. It's obvious that this won't fit in the same keyslot and will need sharding.

Your comment, "Sharded index supported only in PRO version.", does this mean that the index itself will also get sharded across nodes and above use case will still work in PRO version? Same hashtag `{com.org.application.MyLiveObject}` won't be used in PRO version for indices?

Sorry for the repeated query, but just want to make sure before I finalise my design.

Hope my query is clear.

**Comment by mrniko** [comment]
> does this mean that the index itself will also get sharded across nodes and above use case will still work in PRO version

In this case name will be different to distribute evenly across all Redis master nodes.

> Same hashtag {com.org.application.MyLiveObject} won't be used in PRO version for indices?

This name still will be present in key, but without braces.

**Comment by mayurgoenka** [comment]
Thank you @mrniko , this means that I can safely use RLOS for huge data in redis clustered mode.


Another query is, are there any plans for supporting batch operations and transactions with RLOS objects?

**Comment by mrniko** [comment]
What kind of batch / transaction operations over RLOS do you need? Could you describe some use cases?

**Comment by mayurgoenka** [comment]
Suppose I want to merge 1000s of Live objects into redis cache, like a batch update OR batch insert. I see that we do have rlos.persist(list) but I not sure if its using pipelining inside or not? Also, rlos.merge(list) is what I was primarily looking for. 
These operations are mainly required for warming up the cache in my use case.


Transactions could be required when I want to update 2 different Live objects together or not do them at all. Live objects here can be of same class or different classes.
I need this in my use case because there's a parent-child type of relationship in my application, where if I delete the parent object, child object also needs to get deleted.

**Comment by mrniko** [comment]
`org.redisson.api.RLiveObjectService#persist(T...)` method stores object in a batch. `merge()` method for multiple object isn't implemented yet.

As for transactions, I can recommend you to use RLock object.

**Comment by mayurgoenka** [comment]
yes, thank you for the response @mrniko , appreciate it.
