### ISSUE TITLE
org.redisson.RedissonSemaphore#drainPermits throws java.lang.ClassCastException

### ISSUE THREAD

**Issue by arabczuk-equinix** [redisson/redisson#3627]
Due to bug in RedissonSemaphore#drainPermits implementation, the invocation of this methos throws ClassCastException.

```java
    public RFuture<Integer> drainPermitsAsync() {
        return commandExecutor.evalWriteAsync(getRawName(), IntegerCodec.INSTANCE, RedisCommands.EVAL_LONG,
```

The return type parameter of the method is `Integer` but the argument evalCommandType passed to the commandExecutor is `RedisCommands.EVAL_LONG`

**Comment by mrniko** [comment]
Unable to reproduce it using this test:

```java
    @Test
    public void testDrainPermits() throws InterruptedException {
        RSemaphore s = redisson.getSemaphore("test");
        s.trySetPermits(10);
        s.acquire(3);

        assertThat(s.drainPermits()).isEqualTo(7);
        assertThat(s.availablePermits()).isEqualTo(0);
    }
```

**Comment by arabczuk-equinix** [comment]
@mrniko 
What version are you using? I was using version 3.15.4

**Comment by arabczuk-equinix** [comment]
I can see that on version 3.15.5 the bug is also there: 
https://github.com/redisson/redisson/blob/dd999217a18441ceb97df3cc1a76bc15da4c7fba/redisson/src/main/java/org/redisson/RedissonSemaphore.java#L452

**Comment by arabczuk-equinix** [comment]
```groovy
    def 'test semaphore'() {
        given:
            def semaphore = redissonClient.getSemaphore('testSemaphore')
        when:
            def result = semaphore.drainPermits()
        then:
            result == 0
            semaphore.availablePermits() == 0
    }
```

`Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.redisson.RedissonSemaphore.drainPermits(RedissonSemaphore.java:447)`

**Comment by mrniko** [comment]
Fixed
