### ISSUE TITLE
Trylock causes a deadlock，System restart can be unlocked

### ISSUE THREAD

**Issue by tanzheng231** [redisson/redisson#3629]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
  3.2.9

**Redisson version**
3.5.0

**Redisson configuration**
 redissonConfig.useClusterServers().addNodeAddress(address)
.setTimeout(1000)
                    .setMasterConnectionPoolSize(64)
                    .setSlaveConnectionPoolSize(64)
                    .setIdleConnectionTimeout(10000)
                    .setConnectTimeout(30000)
                    .setIdleConnectionTimeout(3000);

**Use code**
      RLock lock = redissonClient.getLock(String.join("_", "taskExtSyncLock", taskId, classId));
   if (lock.tryLock()) {
try{
      //  ignore code 
  }catch（Exception e）{
   throw e;
}finally{
  if (lock != null && lock.isLocked())
                {
                    lock.unlock();
                }
}
     
}else {
    //  ignore code 
}

** Thread blocking , System restart can be unlocked   **

**The following figure shows the thread stack information **

![image](https://user-images.githubusercontent.com/29850270/120289986-783cee80-c2f4-11eb-92f7-303e41092a61.png)

**Comment by mrniko** [comment]
Unable to reproduce it with latest version.

**Comment by tanzheng231** [comment]
There is no rule to be found, which rarely happens. In the version 3.5.0 of redisson, I tried to switch the master-slave of redis, but this did not happen. I tried to use the latest version and updated it in time when I encountered the same problem

**Comment by tanzheng231** [comment]
What can be determined is the result of a redis operation, because this problem occurs in more than one system at the same time

**Comment by tanzheng231** [comment]
What can be determined is the result of a redis operation, because this problem occurs in more than one system at the same time

**Comment by mrniko** [comment]
Might be related to https://github.com/redisson/redisson/issues/1966

**Comment by tanzheng231** [comment]
No，The same thing happens according to the following code
**********************************************************
  public void deleteByPattern(String pattern) {
    	long start=System.currentTimeMillis();
    	RKeys keys = redissonClient.getKeys();
    	long deletedKeysAmount = keys.deleteByPattern(pattern);
    	long end=System.currentTimeMillis();
    	LOGGER.info("use keys time:"+(end-start)+" deletedKeysAmount:"+deletedKeysAmount);
    }
***************************************************************************
ERROR LOG : 
![QQ浏览器截图20210602164016](https://user-images.githubusercontent.com/29850270/120449549-1fd42280-c3c2-11eb-829d-4a176acf9f82.png)
***************************************************************************
Blocked code  --> CommandAsyncService.java
![QQ浏览器截图20210602163807](https://user-images.githubusercontent.com/29850270/120449721-46925900-c3c2-11eb-9d01-e5d20ecb411e.png)

**Comment by mrniko** [comment]
Did you try the latest version?

**Comment by tanzheng231** [comment]
I adjusted it to the latest version. There is no problem at present. If there is the same problem, I will let you know，Thank you for your help

**Comment by mrniko** [comment]
Please reopen it if you encounter it again.

**Comment by ClearLove007** [comment]
tody I also encountered this problem. The cancelationexception was caught during trylock, which terminated the task and could not be reproduced after restart。My service has been running steadily for a year, which is the first time #3629
