### ISSUE TITLE
Redis Lock - question about edge case

### ISSUE THREAD

**Issue by ninja-** [redisson/redisson#3636]
I am looking to use Redis for exclusive locks of resources.
If they fail and two workers will _think_ they are holding the lock, that can end up in, let's say, really bad data corruption.
I know that a lot of edge cases in Redisson have been covered, however how about this one:

1. Worker1 acquires lock with time of "infinity" (until manual release)
2. Worker1 loses connection to _Redis instance_, while access to everything else still works and it continues operation on data, databases etc....
3. Lock gets removed from the database, because it expired in 30s (lock watchdog timeout), because of no bump by watchdog
4. Worker2 has good connection to Redis and is able to acquire the lock and start it's operation on data (leading to corruption)
5. Worker1 gets Redis connection back, it's watchdog tries to recreate the lock in background ASAP, however it lost the race because the lock was already acquired by Worker2
6. Both Worker1 and Worker2 now think they are holding the lock :(

Looking by the code comments, this seems to be expected behavior/known edge case - one of very few in regards to locks.
If I am correct with this scenario, what would you recommend? Going with non-redis solution like etcd or zookeeper, for example?
_or_ maybe set the watchdog timeout to a value that will always be **more than** the execution time of task under that lock _and_ have some custom code for removing failed locks on boot?
(so if Worker1 is down I either wait for it come back and automatically clean it's locks that are no longer valid **or** manually remove the locks owned by Worker1 assuming I want to safely get rid of it)

And is there a mechanism to check periodically whether watchdog has lost the race to _reacquire_ the lock and allow application to act on it?

**Comment by Cesarla** [comment]
Hi @ninja-, in one of the projects I worked we implemented our own watchdog that periodically checks if the lock `isHeldByCurrentThread()` to avoid scenarios like the one you mentioned.

**Comment by ninja-** [comment]
if that method is actually quering the database instead of checking local state, that might be useful for a solution. thanks :+1:

**Comment by Cesarla** [comment]
It does a lookup against redis:
```
    @Override
    public boolean isHeldByThread(long threadId) {
        RFuture<Boolean> future = commandExecutor.writeAsync(getName(), LongCodec.INSTANCE, RedisCommands.HEXISTS, getName(), getLockName(threadId));
        return get(future);
    }

```
