### ISSUE TITLE
Redisson Rate Limiter -> Hard Limit

### ISSUE THREAD

**Issue by tyrantkhan** [redisson/redisson#3639]
The problem I'm seeing is that I'm setting a Rate Limit of lets say 20/second. If there is a period where 20/s is not reached, it will compensate for that and allow a temporary burst of permits over that threshold.

I was hoping for a configuration change to set a hard limit for a rate limit -- so that irregardless of the average rate, the rate must never exceed this value.

This may be how the rate limiter is already set to function, and i've uncovered a bug, let me know if this is the case and I can attempt to simulate this issue in a test (or at least try).

This is how i'm creating my rate limiter:

```
RRateLimiter rl = sharedRedissonClient.getRateLimiter(this::class.simpleName);
rl.setRate(RateType.OVERALL, 18L, 1L,  RateIntervalUnit.SECONDS);
```

**Comment by mrniko** [comment]
which Redisson version do you use?

**Comment by tyrantkhan** [comment]
I'm using `3.15.4` . For what it's worth, before switching to library we were using Gauva, and we saw this behavior there too. Here's a chart from when the rate was set to 20.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/107844/120897503-880a4a80-c5f4-11eb-9e16-b4cfa1510e8c.png">

**Comment by mrniko** [comment]
Do all microservices have sync time?

**Comment by tyrantkhan** [comment]
They should yeah, they are all spun up on the same kubernetes cluster, though all may not be on the same node.

**Comment by tyrantkhan** [comment]
@mrniko I've confirmed all microservices are using chrony  and syncing to the same ntp server.

**Comment by mrniko** [comment]
@tyrantkhan 

Can you try attached version?

[redisson-3.16.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6952693/redisson-3.16.2-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed

**Comment by tyrantkhan** [comment]
Hi @mrniko thank you for looking into this, sorry I didn't get a chance to test the RC, I don't have a good way to test it unless it's published to maven.

Happy to test it out if you can get it published, In the meantime I will try to see if I can manually upload it to our caching server.
