### ISSUE TITLE
Unable to evaluate the expression Method threw 'org.redisson.client.RedisException' exception.

### ISSUE THREAD

**Issue by lucifercr07** [redisson/redisson#3640]
I'm trying to get values for a stored key from Redis and I am facing above error. I am trying to get the keys using `this.redisson.getSet("TestClass");` and for saving the values to redis I am doing `repo.save(TestClassObject);`

I am not able to retrieve the objects when I try to `this.repo.findAll()` in that case I get values as a list but all elements inside the list are null. I also tried using `getSet` as stated above in that case I get the values but as string only hence not able to call getters as they are not of TestClass object type.

Can anyone please help with this?

**Comment by mrniko** [comment]
Can you share full stacktrace?

> I am trying to get the keys using this.redisson.getSet("TestClass");

Try to use StringCodec or ByteArrayCodec.

**Comment by lucifercr07** [comment]
Have tried using StringCodec or ByteArrayCodec but in that case not able to call class methods on the result elements. 
The issue seems to be similar to https://stackoverflow.com/questions/62427392/spring-redishash-findall-return-null-values/

But to make the solution work mentioned in the SO's link, we need to flushall keys from redis that I can't do. Can you please tell me if there is a way we can fix this without using `@TypeAlias` and flushing all the keys?

**Comment by mrniko** [comment]
> but in that case not able to call class methods on the result elements.

What does it mean? Were elements de-serialized correctly?

**Comment by lucifercr07** [comment]
No they weren’t deserialized correctly

**Comment by mrniko** [comment]
That's related to codec problem. So you need to make sure that elements encoded and decoded using the same codec.

**Comment by lucifercr07** [comment]
Using the default codec hence I don’t think that’ll be a issue

**Comment by mrniko** [comment]
If Spring Data uses Redisson and codec is the same then all should work fine.
