### ISSUE TITLE
Does Redisson support spring-data-mongodb

### ISSUE THREAD

**Issue by ahsanbagwan** [redisson/redisson#3642]
So I've adding redisson to my application. The config looks like what is defined here: https://pamesh12.github.io/spring-boot/spring-cache-redis.html

singleServerConfig: address: "redis://127.0.0.1:6379"

When I try adding Cacheable to the method that call external services using RestTemplate I'm able to see the result cache in redis-cli. Though when I try adding Cacheable to service methods that call underlying Mongo repositoy I'm getting IllegalArgumentException

Could someone explain if its because its not supported? I don;t remember exactly but saw that this is supported in only pro version. And if there are any alternatives I could look at without much code change.

`ERROR com.controller.support.ExceptionController [http-nio-9006-exec-5]: [java.lang.IllegalArgumentException] with error Id, error code and message [[org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:743), org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:305), org.redisson.RedissonMap.fastPutOperationAsync(RedissonMap.java:1375), org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:1365), org.redisson.RedissonMap.fas...`

    ```
@Cacheable("ratings") //cacheManager = "redisCacheManager")
    public List<Entity> filterByRating(List<String> vendor/*, Pageable pageable*/) {
        
        return ratingsRepo.findByIdIn(vendor/*, pageable*/);
    }
```

Config: 
 ```
   @Configuration
public class RedissonSpringDataConfig {

    @Bean
    public RedissonConnectionFactory
    redissonConnectionFactory(RedissonClient redisson) {
        return new RedissonConnectionFactory(redisson);
    }

    @Bean(destroyMethod = "shutdown")
    public RedissonClient
    redisson(@Value("classpath:redission/redisson-dev.yaml") Resource configFile)
            throws IOException {
        Config config = Config.fromYAML(configFile.getInputStream());
        return Redisson.create(config);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redissonConnectionFactory) {
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(redissonConnectionFactory);
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(new StringRedisSerializer());
        return template;
    }

    @Bean(name = "redisCacheManager")
    public CacheManager redisCacheManager(RedissonClient redissonClient) throws IOException {
        //String configFileName = "cache-config-" + activeProfile + ".yml";
        return new RedissonSpringCacheManager(redissonClient);
    }
}
```

**Comment by mrniko** [comment]
It seems to be a problem with data serialization. Did you try another codec?

**Comment by ahsanbagwan** [comment]
Thanks @mrniko same error when I try out:

 ```
template.setKeySerializer(new JdkSerializationRedisSerializer());
 template.setValueSerializer(new JdkSerializationRedisSerializer());
```
and genericjackson2jsonredisserializer as well

**Comment by mrniko** [comment]
`org.redisson.codec.SerializationCodec` should be used with `JdkSerializationRedisSerializer`
