### ISSUE TITLE
Why is `isEvalCacheActive` hardcoded to false inside `CommandBatchService`?

### ISSUE THREAD

**Issue by apinder** [redisson/redisson#3644]
Why is `isEvalCacheActive` hardcoded to false inside `CommandBatchService`?

https://github.com/redisson/redisson/blob/05bbe1c895d1dfe10ef8e6eb043a70d0a69ccc38/redisson/src/main/java/org/redisson/command/CommandBatchService.java#L504-L507

Due to `CommandBatchService` being used by `RedisBaseLock` this means regardless of whether you have `useScriptCache` set to true in the Redisson config all Redisson locks will be sending the whole script across the network for every lock call.

I assume there's a reason for this but is there any way I can use `evalsha` for locks instead?

**Comment by apinder** [comment]
Can anyone answer this question? If not I'll try forking it and attempt to fix it myself, it appears there's nothing that should stop the locks from using `evalsha` over `eval`.

I assume I'm missing something here because sending the script directly over the network every time a lock is called seems like the first optimisation I'd do, so I'd be surprised if this is the expected behaviour for Redisson.

**Comment by mrniko** [comment]
It's not supported yet. All batched eval scripts should be loaded before batch execution.
