### ISSUE TITLE
Storing large object exceeds Redis' max inline read request size.

### ISSUE THREAD

**Issue by dom-suitable** [redisson/redisson#3645]
**Expected behavior**
Store an object of size greater than 64kb as allowable in [docs](https://github.com/redisson/redisson/wiki/6.-distributed-objects#61-object-holder).

**Actual behavior**
Client throws exception `org.redisson.client.RedisException: ERR Protocol error: too big inline request`

**Steps to reproduce or test case**
```java
String baseString = "ba xy";
String dummyString = "";
for (int i = 0; i < ((1024*64)); i++) {
    dummyString = dummyString + baseString;
}
RBucket bucket = client.getBucket("key");
bucket.set(dummyString, 300, TimeUnit.SECONDS);
```

**Redis version**
5.0.12

**Redisson version**
3.15.5

**Redisson configuration**
Single server configuration w/ `sslEnableEndpointIdentification = false`. I've tried with both `StringCodec` and `FstCodec` with no success.

Let me know if there's a configuration to avoid inlining the request, I couldn't find one via the docs.

**Comment by mrniko** [comment]
this error reported by Redis. Unable to reproduce it

**Comment by dom-suitable** [comment]
I'm also receiving the error `org.redisson.client.RedisException: ERR unknown command` if I adapt the test code to (again using `FstCodec`):
```java
String baseString = "x";
String dummyString = "";
for (int i = 0; i < ((1024*200)); i++) {
    dummyString = dummyString + baseString;
}
RBucket bucket = client.getBucket("key");
bucket.set(dummyString, 300, TimeUnit.SECONDS);
```

This gives me the impression my value is not being escaped or isn't a parameter in the command sent to redis. My redis version is a vanilla docker image `redis:5.0.12`, is there additional configuration needed within redis for this library to function? or any advice on where to debug?

**Comment by mrniko** [comment]
Unable to reproduce it. Can you try native implementation?

**Comment by dom-suitable** [comment]
Oddly if I use a native implementation I get the error `Caused by: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (PSETEX)...`.

Redis server logs report:
```
43083:M 11 Jun 2021 18:03:16.854 - Protocol error (too big inline request) from client: id=32 addr=127.0.0.1:57016 fd=8 name= age=40 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=81452 qbuf-free=16852 obl=45 oll=0 omem=0 events=r cmd=ping. Query buffer during protocol error: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' (... more 81324 bytes ...) 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

**Comment by mrniko** [comment]
> Redis server response timeout

Seems Redis instance is too slow
