### ISSUE TITLE
Is order of Operations in a RBatch guaranteed?

### ISSUE THREAD

**Issue by uweschaefer** [redisson/redisson#3654]
Sorry if this is obvious, but i did not find any documentstion about this:

If i am using **RBatch** and create let's say a Bucket from it, and call setAsync on the bucket 100 times before executing the batch, is the order of the operations in the batch guaranteed to be the order in which
```
setAsync(Object)
```
has been called?

In other words, is there any way i could end up with anything but the last value i set to the bucket after the RBatch is executed? For instance if the Marshalling of the 99th value took some time?

Bucket is just an example here, i am also using RMaps the same way.

**Comment by mrniko** [comment]
In this case you need to maintain order on your side, for example using RLock object.

**Comment by uweschaefer** [comment]
Thanks for answering, @mrniko 

is there an example somewhere? i fail to understand how RLock helps me in this case.
Or did you refer to RedissonFairLock ?

thx

**Comment by mrniko** [comment]
In batch list of operations is always ordered. But RBatch object isn't thread-safe.

**Comment by uweschaefer** [comment]
Thanks, this is very good news.
