### ISSUE TITLE
Adding ttl 

### ISSUE THREAD

**Issue by ahsanbagwan** [redisson/redisson#3658]
How do I add the lowest possible TTL to Redisson? Some caches expire after long time. Or would it be better to write `clear()` on Spring application ready event?

This is what the Config looks like:

```
@Bean
public RedissonConnectionFactory
redissonConnectionFactory(RedissonClient redisson) {
    return new RedissonConnectionFactory(redisson);
}

@Bean(destroyMethod = "shutdown")
public RedissonClient
redisson(@Value("classpath:redission/redisson-dev.yaml") Resource configFile)
        throws IOException {
    Config config = Config.fromYAML(configFile.getInputStream());
    return Redisson.create(config);
}

@Bean
public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redissonConnectionFactory) {
    RedisTemplate<String, Object> template = new RedisTemplate<>();
    template.setConnectionFactory(redissonConnectionFactory);
    template.setKeySerializer(new StringRedisSerializer());
    template.setValueSerializer(new StringRedisSerializer());
    return template;
}

@Bean(name = "redisCacheManager")
public CacheManager redisCacheManager(RedissonClient redissonClient) throws IOException {
    //String configFileName = "cache-config-" + activeProfile + ".yml";
    return new RedissonSpringCacheManager(redissonClient);
}
```

**Comment by ahsanbagwan** [comment]
@mrniko Couldn't find any way to set ttl globally in the docs, I was also confusing timeout for ttl.
Did I miss anywhere?

**Comment by mrniko** [comment]
Do you mean ttl for RedissonSpringCacheManager entries?

**Comment by ahsanbagwan** [comment]
In hindsight I reckon this is not applicable to apply to all caches at once
but to individual ones

**Comment by mrniko** [comment]
> In hindsight I reckon this is not applicable to apply to all caches at once
but to individual ones

ttl setting applied to specific cache instance only.

**Comment by ahsanbagwan** [comment]
@mrniko Still not clear. I've code like this

```
@Cacheable(value="cacheName")
public String findFoo(String bar){

}
```
I have as above
`Config config = Config.fromYAML(configFile.getInputStream());`
but not sure how to set it here. Googling suggests there is CacheConfig on which it can be set.

Could you please suggest?
