### ISSUE TITLE
expire(Instant) is not equivalent to expireAt(Date) 

### ISSUE THREAD

**Issue by ngtercet** [redisson/redisson#3660]
In #3399, `RExpirable#expireAt(Date)` is deprecated, and the javadoc said **Use expireAt(Instant) instead** (in latest release it is called expire(Instant)).

But I notice that the implementaions of this two method is not equivalent actually.

This breaks some object expiration, such as `RedissonBloomFilter`.

**Expected behavior**
calling expire(Instant) should expire bloomfilter `name `and `configName `both

**Actual behavior**
only bloomfilter `name` is expired

**Steps to reproduce or test case**
expireAt(Date) calls `expireAtAsync` which is overridden in RedissonBloomFilter which expire `name` and `configName` both
https://github.com/redisson/redisson/blob/5793388f10661aa34baec83b88077e987cf07593/redisson/src/main/java/org/redisson/RedissonExpirable.java#L58
https://github.com/redisson/redisson/blob/5793388f10661aa34baec83b88077e987cf07593/redisson/src/main/java/org/redisson/RedissonBloomFilter.java#L293

expire(Instant) calls` expireAtAsync(instant)` which only expire `name`
https://github.com/redisson/redisson/blob/5793388f10661aa34baec83b88077e987cf07593/redisson/src/main/java/org/redisson/RedissonExpirable.java#L68
https://github.com/redisson/redisson/blob/5793388f10661aa34baec83b88077e987cf07593/redisson/src/main/java/org/redisson/RedissonExpirable.java#L73

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by ngtercet** [comment]
Nice work!
