### ISSUE TITLE
Reactive Client - Key does not expire

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3670]
Why does expire method not work for reactive client?

        RedissonReactiveClient rclient = ....;
        RBucketReactive<String> bucket = rclient.getBucket("demo");
        bucket.set("hello world").subscribe();
        bucket.expire(5, TimeUnit.SECONDS).subscribe();
        rclient.shutdown();

I can still see the keys and values after 10 seconds. Looks like the client should not be shutdown to expire the keys? Can we not set the expire key as part of the expire method invocation itself?

**Comment by mrniko** [comment]
you need to make a request on subscribe.
