### ISSUE TITLE
getLocalCachedMap for reactive client

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3671]
Why do we not have **_getLocalCachedMap_** for a reactive client when the blocking client has it.?

https://www.javadoc.io/doc/org.redisson/redisson/latest/org/redisson/api/RedissonReactiveClient.html

**Comment by ninja-** [comment]
+1

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/3181
