### ISSUE TITLE
Redisson LOS retry configuration

### ISSUE THREAD

**Issue by mayurgoenka** [redisson/redisson#3682]
Hello, I noticed that there's an inbuilt retry mechanism inside Redisson Live Object Service which retries 3 times before throwing the WriteRedisConnectionException exception.
Is there anyway, we can further configure this retry logic? Or switch it off in case we want to implement our own?

**Comment by mrniko** [comment]
You can adjust it using [retryAttempts](https://github.com/redisson/redisson/wiki/2.-Configuration#retryattempts) and [retryInterval](https://github.com/redisson/redisson/wiki/2.-Configuration#retryinterval) settings

**Comment by mayurgoenka** [comment]
Thanks @mrniko . For some reason I missed these while reading that config page.
