### ISSUE TITLE
Connecting to AWS Elasticache cluster using cluster endpoint

### ISSUE THREAD

**Issue by mayurgoenka** [redisson/redisson#3684]
Hello,
AWS EC exposes 2 ways of connecting to multi-node cluster.
It gives us a cluster-endpoint AND it also gives us endpoints for each node.
Now, in redisson I see that there's a cluster connection config which requires each of the node endpoint address alongwith replicase i think.
And then there's singleServerConfig.

I was wondering what's the best way to handle this? If I use single server config with cluster endpoint, will it be okay?

Or I always need to use cluster connection config with all node endpoints registered.

**Comment by mrniko** [comment]
you can use endpoint with AWS EC

**Comment by mayurgoenka** [comment]
thanks @mrniko for confirmation.
