### ISSUE TITLE
How should users debug subscription timeouts? 

### ISSUE THREAD

**Issue by Sovietaced** [redisson/redisson#3686]
I often see this error message when my one of my replicated services is trying to acquire a distributed lock from our AWS Elasticache Cluster. 

> Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.

I followed the suggestion of the message and increased my `subscriptionsPerConnection` from the default to 500. I still see the error message. I looked at the CPU/Memory usage of the AWS Elasticache cluster and it is below 5%. 

I have looked into other issues about this topic and I have not found a good way to root cause what is actually going on. 

**Is there a way that we can validate that we are indeed exceeding the subscriptions per connection or are running out of subscription connections? 
If we are indeed running out of connections is there a way we can dump what subscriptions our connections are using?**

I have enabled DEBUG level logging and I see the following messages. 

> connection released for command null and params null from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:92:queue:0, freezeReason=null, client=[addr=<redacted>], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1767476324 [redisClient=[addr=r<redacted>], channel=[id: 0x7d4b874f, L:/<redacted> - R:<redacted>], currentCommand=null]

What is the difference between the `freeSubscribeConnectionsAmount` and `freeSubscribeConnectionsCounter` ?

**Comment by mrniko** [comment]
> I followed the suggestion of the message and increased my subscriptionsPerConnection from the default to 500. I still see the error message. I looked at the CPU/Memory usage of the AWS Elasticache cluster and it is below 5%.

Can this relate to this issue related https://github.com/redisson/redisson/issues/3577 ?

> Is there a way that we can validate that we are indeed exceeding the subscriptions per connection or are running out of subscription connections?

There is no such way except statistics monitoring. https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#1414-statistics-monitoring-jmx-and-other-systems

> If we are indeed running out of connections is there a way we can dump what subscriptions our connections are using?

All subscriptions share the same pool of subscription connections.

**Comment by Sovietaced** [comment]
> Can this relate to this issue related #3577 ?

I don't believe so considering we are reproducing this issue on Redis 3.15.5. 

> There is no such way except statistics monitoring. https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#1414-statistics-monitoring-jmx-and-other-systems

I'm not sure I'm going to go through the effort to convince my company to purchase PRO. Will fork and add my own logs/instrumentation I guess to see what is going on.

**Comment by mrniko** [comment]
> What is the difference between the freeSubscribeConnectionsAmount and freeSubscribeConnectionsCounter ?

freeSubscribeConnectionsAmount - amount of pubsub connections in pool, freeSubscribeConnectionsCounter  - current amount of available connections for getting from pool or creating.

**Comment by mrniko** [comment]
I'll add type of connection in logs. So you can count amount of acquired in released connections by log records.

**Comment by Sovietaced** [comment]
I spent several hours yesterday digging into the code to try and understand what might be going on. As you mentioned, the `freeSubscribeConnectionsCounter` indicates how many connections remaining connections can be created in order to service requests. Given that I am seeing `freeSubscribeConnectionsCounter` set to 49 we know that there is only one actual connection being used for pub/sub. 

From my testing it appears that if pub/sub channels are added slowly enough they will just be added to an existing connection until the number of subscriptions allowed per connection reaches the maximum, at which point a new connection will be created. 

There may be a bug or there may be a legitimate issue with our environment that does not make it possible to acquire a new connection with the Redis cluster. It should not be an environmental issue given that we've seen our Redis Cluster scale up to 40,000 connections and we typically only use 1,200 at a time. I will admit that the environment we are using is quite complex so it is possible there is some infrastructure or network layer playing a part here. 

An issue I see with the code is that the logic to retrieve a new connection is encapsulated in a future, and there are codepaths that will finish, but never complete the future. For instance, in my testing when I maxed out the possible pub/sub connections new requests will try to create a connection but timeout. What actually happens is the `AsyncSempahore` that allows new connections to be created [silently doesn't execute some codepath](https://github.com/redisson/redisson/blob/ac5b0cba06723dd4c38f4d016190da5166040e76/redisson/src/main/java/org/redisson/pubsub/AsyncSemaphore.java#L70-L73) that would complete the future in some way. 

Given that I've spent some time looking at the code I would be willing to open a PR to add some additional logging and potentially document/cleanup some minor things.

**Comment by mrniko** [comment]
> Given that I've spent some time looking at the code I would be willing to open a PR to add some additional logging and potentially document/cleanup some minor things.

I would be glad to consider it.

**Comment by mrniko** [comment]
> What actually happens is the AsyncSempahore that allows new connections to be created [silently doesn't execute some codepath](https://github.com/redisson/redisson/blob/ac5b0cba06723dd4c38f4d016190da5166040e76/redisson/src/main/java/org/redisson/pubsub/AsyncSemaphore.java#L70-L73) that would complete the future in some way.

Fixed in https://github.com/redisson/redisson/issues/3703
