### ISSUE TITLE
AUTH does not seem to work as expected.

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3687]
Steps:

1. Run this command in redis
`acl setuser dummy on allkeys +get +set nopass`
2. Try to do this in redis. This will fail as the user has no permission to do this operation.
```
AUTH dummy password
sadd numbers 1 2 3
```
3. Now create a redission config.
```
            config
                    .useSingleServer()
                    .setAddress("redis://127.0.0.1:6379")
                    .setUsername("dummy")
                    .setPassword("password");
```
4. Run this. This should ideally fail. but it passes!

```
        RSetReactive<Long> numbers = client.getSet("numbers", LongCodec.INSTANCE);
        Mono<Void> mono1 = Flux.range(1, 10)
                .flatMap(i -> numbers.add(Long.valueOf(i)))
                .then();
        StepVerifier.create(mono1)
                .verifyComplete();
```

**Comment by mrniko** [comment]
`sadd numbers 1 2 3`

will return `NOPERM this user has no permissions to run the 'sadd' command or its subcommand` error since permission wasn't given.
