### ISSUE TITLE
Error message from Redis: ERR invalid command channel: [id: 0x33948139, L:/10.0.3.228:40080 - R:/172.16.1.9:6379]

### ISSUE THREAD

**Issue by dnfhujun** [redisson/redisson#3691]
i user redisson version is 3.13.2

Error message from Redis: ERR invalid command channel: [id: 0x33948139, L:/10.0.3.228:40080 - R:/172.16.1.9:6379]

What does this mean, please?

**Comment by mrniko** [comment]
it means some commands aren't supported by your Redis version.
