### ISSUE TITLE
Redisson complains about multiple masters when two replicated address nodes resolve to the same IP

### ISSUE THREAD

**Issue by Sovietaced** [redisson/redisson#3692]
We are working through issues with using Redisson with AWS Elasticache during upgrade/failover/etc. 

We currently have a replicated cluster of size 2: 1 master and 1 replicated node. 
AWS Elasticache provides us with two DNS endpoints to use:

1. master.`<redacted>`.cache.amazonaws.com:6379
2. replica.`<redacted>`.cache.amazonaws.com:6379

During normal operation both of these DNS entries will resolves to different IP addresses, however during upgrade/failover it is possible that only one cluster node is available and the DNS entries will resolve to the same IP addresses. 

Even when operating the cluster with 1 node I think this should be allowed. This allows infrastructure teams to easily to scale up/down underlying cluster nodes load balanced by DNS without having to modify the application config to include/exclude certain hostnames. 

**Expected behavior**

Redisson should tolerate when more than one node address resolves to the same IP address, that happens to be a master in the cluster. 

**Actual behavior**

> org.redisson.connection.ReplicatedConnectionManager.<init>(ReplicatedConnectionManager.java:80)
> org.redisson.Redisson.<init>(Redisson.java:67)
> org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:199)
> org.redisson.Redisson.create(Redisson.java:108)
> `<redacted>`.main(Application.kt:97)
> Exception in thread "main" org.redisson.client.RedisException: Multiple masters detected

**Steps to reproduce or test case**

Initialize replicated configuration with two DNS entries that resolve to the same IP address. 

**Redis version**

6+

**Redisson version**

3.15.2

**Redisson configuration**

```java 
final Config config = new Config();
final ReplicatedServersConfig replicatedConfig = config.useReplicatedServers();
replicatedConfig.addNodeAddress("AWS Elasticache primary endopoint");
replicatedConfig.addNodeAddress("AWS Elasticache replica endpoint");
```

**Comment by Sovietaced** [comment]
The docs indicate that the `ReplicatedServersConfig` should be used for AWS Elasticache and Azure Redis Cache, however the API interface doesn't seem to adhere to the AWS/Azure best practices documentation for interacting with replication groups. 

When using the primary/replica endpoints provided by AWS or Azure the `ReplicatedServersConfig` no longer needs to detect master/slave changes since that is simplified by AWS so I wonder if it makes any sense to add support for explicit primary/reader endpoints.

**Comment by mrniko** [comment]
> I'm guessing there are some implementation details that have to be worked out with using primary/reader endpoints, but forcing all users to explicitly define all node endpoints is a terrible user experience.

I don't want to make explicit dependency on AWS client lib.

**Comment by mrniko** [comment]
I agree that case when DNS entries resolve to the same IP addresses should be handled correctly.

**Comment by mrniko** [comment]
> I'm guessing there are some implementation details that have to be worked out with using primary/reader endpoints

You can use masterSlaveServers mode. Did you try it? Dns resolver will handle IP changes.

**Comment by mrniko** [comment]
Multiple masters check removed.

**Comment by manjeetsingh87** [comment]
Hi @mrniko, do you know when the fix will be released?

**Comment by mrniko** [comment]
@manjeetsingh87 

By the end of this month.

**Comment by manjeetsingh87** [comment]
Thank you

I had one more question regarding [this](https://github.com/redisson/redisson/blob/c1b19a57cb3ac3c66d599950147ab2344ac41902/redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java#L100) change.

Will the dnsMonitoring feature be available for replicated mode in the next release ?

**Comment by mrniko** [comment]
dnsMonitoring will be disabled, since host name resolution is always executed in config check scheduler. Next release will compare resolved ip and not host name as before to detect master change.
