### ISSUE TITLE
Redisson - remove web dependency. conflicts with WebFlux

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3698]
**Issue:**

I use Spring WebFlux - reactive web stack. When I added Redisson Spring boot starter - I started seeing weird issues in the application. Then I found that it brings this below unnecessary dependency. I can do maven exclude. But ideally , in redisson, this should be a **_test_** scope dependency.

**_spring-boot-starter-web_**.

WebFlux and Web can not be in the same project and it would lead to weird issues.

**Comment by mrniko** [comment]
Fixed! Thanks for report
