### ISSUE TITLE
Stream API enhancement

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3700]
Currently redisson stream read does not seem to be really reactive. It just emits via Mono. 

1. Can we change the **_Map<StreamMessageId, Map<>>_** to a proper data structure?
```
StreamMessage {
         StreamMessageId id;
         String Key;
         T body;
}
```
2. Also stream is never ending data stream. 
```
RStreamReactive<String, String> stream = ....
stream("testGroup", "consumer1", ALL)   // returns Flux<StreamMessage>
      .take(100)
      ...
      .subscribe(process());
```
3. The upstream should listen to downstream demand and emit messages as and when it arrives.
```
Flux.create((emitter) -> {
            emitter.onRequest((n) -> {
          
                // emit n messages
                // emit as and when a message is received

                try {
                    future = (RFuture)supplier.call();
                } catch (Exception var6) {
                    emitter.error(var6);
                    return;
                }

                emitter.onDispose(() -> {
                    future.cancel(true);
                });

                future.onComplete((v, e) -> {
                    if (e != null) {
                        emitter.error(e);
                    } else {
                        if (v != null) {
                            emitter.next(v);
                        }
                    }
                });
            });



```

**Comment by mrniko** [comment]
> Can we change the Map<StreamMessageId, Map<>> to a proper data structure?

Map is correct structure. Multiple fields can be bounded per id.

> The upstream should listen to downstream demand and emit messages as and when it arrives

Let me look at this issue.

**Comment by kitkars** [comment]
@mrniko 
Understood. 

**_Question 1:_**
Do I have an option to read a stream of custom object say **_PaymentEvents_** which could have nested objects?

_**Question 2:**_
I assume you will have only one Map for a given StreamMessageId. So instead of returning Mono of **_Map<StreamMessageId, Map<>>_**, we should return a List or Flux of below object. I believe Stream is supposed to deliver the messages in the order it arrives. The consumer should process the messages in the arriving order. So, I think **_List/Flux_** could be a correct choice.
But you will know better.
```
StreamMessage {
         StreamMessageId id;
         Map<K, V>
}
```

**Comment by mrniko** [comment]
> Do I have an option to read a stream of custom object say PaymentEvents which could have nested objects?

You can store any object into Stream.

>I assume you will have only one Map for a given StreamMessageId. So instead of returning Mono of Map<StreamMessageId, Map<>>, we should return a List or Flux of below object. I believe Stream is supposed to deliver the messages in the order it arrives. The consumer should process the messages in the arriving order. 

It's implemented accoring Redis protocol which allows multiple map entires. LinkedHashMap used as Map implementation.
