### ISSUE TITLE
cannot get redis connection after redis master switch over and found there're memory leak.

### ISSUE THREAD

**Issue by GemGuo** [redisson/redisson#3703]
In my product environment, after some times of redis master switchover (2 redis services + 3 sentinels),  the redisson happens 
 error that cannot acquire connections.

2021-06-23-T12:00:42.166+0300 | server1 | | redisson-netty-2-4 | INFO | org.redisson.connection.SingleEntry | master /10.32.234.164:6379 has changed to /10.32.234.165:6379
2021-06-23-T12:00:42.166+0300 | server1 | | redisson-netty-2-4 | INFO | org.redisson.connection.pool.MasterConnectionPool | 32 connections initialized for /10.32.234.165:6379
2021-06-23-T12:00:42.718+0300 | server1 | | pool-flow.seda.ne3sws-mediation-notification-se-thread-21976 | INFO | NE3SWS_MEDIATION | Start to process notification received from the agent ******
2021-06-23-T12:00:43.109+0300 | server1 | | pool-flow.seda.ne3sws-mediation-notification-se-thread-21977 | INFO | NE3SWS_MEDIATION | Start to process notification received from the agent *******
2021-06-23-T12:00:43.543+0300 | server1 | | ne3sws-pm-upload-timeout-check | ERROR | com.nokia.oss.ne3sws.redisbc.pmupload.PMUploadTimeoutCheckTimer | Check ongoing task failed for
org.redisson.client.RedisTimeoutException: **Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise**@2122bdc6(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (HLEN), params: [NE3SWS-PM-UPLOAD-ONGOING-TASK] after 0 retry attempts
at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:187) ~[redisson-3.15.3.jar:3.15.3]
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Expected behavior**
Expect the redisson work fine the get connection

**Actual behavior**
redisson happens error and cannot ger error.

found memory leak in the heapdump.

![AsyncSemaphore_leak](https://user-images.githubusercontent.com/1321300/123940877-30c98100-d9cc-11eb-92ec-6c60270b3b6e.JPG)

![connectionpool_callback_leak](https://user-images.githubusercontent.com/1321300/123940899-37f08f00-d9cc-11eb-92e3-41df58e48c32.JPG)

![callback_promise](https://user-images.githubusercontent.com/1321300/123940928-3e7f0680-d9cc-11eb-8e28-fc243c071bc9.JPG)

![promise_cancellation_exception](https://user-images.githubusercontent.com/1321300/123940959-46d74180-d9cc-11eb-8790-0f63a134a411.JPG)

**Steps to reproduce or test case**

**Redis version**
redis4

**Redisson version**
redisson 3.15.3

**Redisson configuration**

**Comment by mrniko** [comment]
Can you share memory dump?

**Comment by GemGuo** [comment]
Hi @mrniko 
I cannot share the memory dump  accroding to company policy.
I can check the heapdump if you need more information.
thanks, Br.
Gem

**Comment by GemGuo** [comment]
Hi @mrniko 
We could see there're a mass of objects of classes  'org.redisson.misc.RedissonPromise' 'io.netty.util.concurrent.DefaultPromise.LeanCancellationException', 'org.redisson.connection.pool.ConnectionPool.AcquireCallback',
I **suspect much RedissonPromise objects** are not marked done or CancellatioException in this method  org.redisson.connection.pool.ConnectionPool.acquireConnection(RedisCommand<?>, ClientConnectionsEntry).
but not sure.  
BR.
Gem

**Comment by mrniko** [comment]
Does this occurs with retryAttempts > 0 setting?

**Comment by GemGuo** [comment]
yes, the RetryAttempts >0, attach my sentinelServersConfig:
  #Enable/disable redisson sentinels list checking during redisson start
  checkSentinelsList: false
  #If pooled connection not used for a timeout time and current connections amount bigger than minimum idle connections pool size, then it will closed and removed from pool. Value in milliseconds
  idleConnectionTimeout: 10000
  #Timeout in milliseconds during connecting to any Redis server
  connectTimeout: 10000
  pingConnectionInterval: 60000
  #Redis server response timeout in milliseconds. Starts to countdown when Redis command was successfully sent.
  timeout: 5000
  #Error will be thrown if Redis command can't be sended to Redis server after retryAttempts. But if it sent successfully then timeout will be started.
  retryAttempts: 3
  #Time interval in milliseconds after which another one attempt to send Redis command will be executed
  retryInterval: 1500
  #password can be runtime changed
  password: "xxxxxxxxxxxxxxxxxxxx"
  #Subscriptions per Redis connection limit.
  subscriptionsPerConnection: 5
  clientName: "ne3sws_mediation"
  #Minimum idle subscription (pub/sub) connection amount for each slave node
  subscriptionConnectionMinimumIdleSize: 1
  #Maximum subscription (pub/sub) connection pool size for each slave node
  subscriptionConnectionPoolSize: 50
  #Redis 'slave' node minimum idle connection amount for each slave node
  slaveConnectionMinimumIdleSize: 1
  #Redis 'slave' node maximum connection pool size for each slave node
  slaveConnectionPoolSize: 1
  #Redis 'master' node minimum idle connection amount for each master node
  masterConnectionMinimumIdleSize: 32
  #Redis 'master' node maximum connection pool size
  masterConnectionPoolSize: 256
  #NetAct redis server default masterName
  masterName: "xxxredisMaster"
  #All read/write go to master only to keep data consistency
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  #sentinel address could be replaced at installation/upgrade/scaling time
  sentinelAddresses:
  - "redis://xxxnode10:26379"
  - "redis://xxxnode14:26379"
  - "redis://xxxnode15:26379"
threads: 0
nettyThreads: 0
#default
codec: !<org.redisson.codec.JsonJacksonCodec> {}
#default java NIO implementation
transportMode: "NIO"
useThreadClassLoader: false

**Comment by GemGuo** [comment]
Hello @mrniko ,
I'm looking forward to your comments about this issue.
thanks in advance.

**Comment by GemGuo** [comment]
Hello @mrniko ,
I'm looking forward to your comments about this issue.
thanks in advance.

**Comment by mrniko** [comment]
Try to find instances of any exception in memory dump.

**Comment by mrniko** [comment]
It might be related to https://github.com/redisson/redisson/issues/3581

**Comment by GemGuo** [comment]
Hi @mrniko 
I even cannot reproduce this issue in my local environmont.
so far, I'll try to upgrade  to 3.16.0 version.
thanks .

**Comment by GemGuo** [comment]
BTW, attach those exception list. 
![image](https://user-images.githubusercontent.com/1321300/125589856-0edd6498-ee03-44b7-977a-5b5fcd15e507.png)

**Comment by GemGuo** [comment]
In my environment, the IdleConnectionWatcher works fine, not similar to #3581 
the memory leak probably due to CancellationException pilled up. 

![image](https://user-images.githubusercontent.com/1321300/125593342-953b4c08-e589-4b2e-a0cd-201122a5a085.png)


![image](https://user-images.githubusercontent.com/1321300/125590291-50599390-e7dd-4d47-986c-6287b8c25238.png)

**Comment by mrniko** [comment]
What is the root object holding reference to canceled promises?

**Comment by mrniko** [comment]
Does it occur after master slave failover?

**Comment by GemGuo** [comment]
Hi @mrniko 
yes, it occurs after master slave failover.
the object reference chain is like:

_org.redisson.connection.ClientConnectionsEntry (**holding AsyncSemaphore**) -> 
	org.redisson.connection.pool.ConnectionPool (extends to org.redisson.client.RedisConnection)->
		org.redisson.connection.pool.ConnectionPool.AcquireCallback  ->  
			org.redisson.misc.RedissonPromise （delegate to io.netty.util.concurrent.DefaultPromise)   ->  
				io.netty.util.concurrent.DefaultPromise.LeanCancellationException (Extends to)->  
					java.utils.concurrent.CancellationException_

**Comment by mrniko** [comment]
Can you share content of `AsyncSemaphore.removedListeners` field?

**Comment by GemGuo** [comment]
Hi @mrniko 
I attached  AysncSemaphore state and Listeners/removedListeners Info.
![image](https://user-images.githubusercontent.com/1321300/125752427-430ed772-6d43-4656-a3b0-f5e5cbcb379a.png)
![image](https://user-images.githubusercontent.com/1321300/125752842-d36c4fb4-dc37-4f26-80ef-752c4da6449d.png)
![image](https://user-images.githubusercontent.com/1321300/125753412-43003d53-e09a-4bbd-85b6-6b76458ac7a8.png)
![image](https://user-images.githubusercontent.com/1321300/125753708-8724fdf2-99f8-4833-a617-aaee8e090dc3.png)

**Comment by GemGuo** [comment]
Hi @mrniko 
based on that there're so much AsyncSemaphore Listeners and CancellationExceptions in the heapdump，
I make below assumption, is it possible ?
   at some timespot, an unknow issue cause a operation timeout to tryAcquire  AsyncSemaphore, and it will lead to some 3 retry operations generated (we set the retryattempts=3),  then other operation timeout/cancellation and cause more retry operation /Listeners are added into AsyncSemaphore,  eventually a vicious cycle occurs...

**Comment by mrniko** [comment]
can you calc exactly size of AsyncSemaphore.listeners and AsyncSemaphore.removedListeners fields? You can do it with OQL Console if you open dump in VisualVM.

**Comment by GemGuo** [comment]
Hi, 
attach the size and snapshot.
![image](https://user-images.githubusercontent.com/1321300/125902345-b384f632-5f4b-4460-954c-a9c2641c932f.png)
![image](https://user-images.githubusercontent.com/1321300/125904392-2b7946c9-dc55-41a0-a3a4-79f01d83aa19.png)

AsyncSemaphore.listeners   has 623902 items while AsyncSemaphore.removedListeners has 469838 entries.

**Comment by mrniko** [comment]
> BTW, only when master/slave failover(nodedown), those listeners could be cleared, right ?

These listeners are cleared at line 199 of MasterSlaveEntry class. Before node shutdown.

> is it possbile missed or failed to call nodedown() after failover?

At the moment I don't see how it could happen.

**Comment by mrniko** [comment]
> In my product environment, after some times of redis master switchover

Can you reproduce it and share logs from the beginning?

**Comment by mrniko** [comment]
what is AsyncSemaphore.counter value?

**Comment by GemGuo** [comment]
Hi @mrniko 
the AsyncSemaphore.counter value is 0.
![image](https://user-images.githubusercontent.com/1321300/126429999-c70dc33a-696c-4978-8033-f6bf1f36d2ef.png)

**Comment by mrniko** [comment]
Fixed AsyncSemaphore race condition. https://github.com/redisson/redisson/commit/34d2e4de3a8b6cc9170fe7b5d82d40498fe60f1e
