### ISSUE TITLE
Redisson vs Lettuce - Performance Comparison

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3704]
I was just trying to do a simple performance test to compare Redisson and Lettuce.
I really like Redisson. But Redisson seems to be consistently slower than Lettuce. Is this expected?

**_Redisson throughput = 58K requests / sec
Lettuce throughput = 75K requests / sec_**

    @RepeatedTest(10)
    public void lettucePerformance() throws InterruptedException {
        RedisClient redisClient = RedisClient.create("redis://localhost:6379/0");
        StatefulRedisConnection<String, String> connection = redisClient.connect();
        RedisReactiveCommands<String, String> reactiveCommands = connection.reactive();

        long before = System.currentTimeMillis();
        Mono<Void> mono = Flux.range(1, 500_000)
                .flatMap(i -> reactiveCommands.incr("user:1"))
                .then();

        StepVerifier.create(mono).verifyComplete();
        System.out.println((System.currentTimeMillis() - before)  + " ms");

    }

    @RepeatedTest(10)
    public void redissonPerformance() throws InterruptedException {
        RAtomicLongReactive longReactive = client.getAtomicLong("user:2");

        long before = System.currentTimeMillis();
        Mono<Void> mono = Flux.range(1, 500_000)
                .flatMap(i -> longReactive.incrementAndGet())
                .then();

        StepVerifier.create(mono).verifyComplete();
        System.out.println((System.currentTimeMillis() - before)  + " ms");

    }

My Config:

I tried with this
```
            config
                    .setNettyThreads(0)
                    .useSingleServer()
                    .setAddress("redis://127.0.0.1:6379");
```
and this.
```
            config
                    .useSingleServer()
                    .setAddress("redis://127.0.0.1:6379");
```

**Comment by mrniko** [comment]
[redisson-3.16.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6763596/redisson-3.16.1-SNAPSHOT.jar.zip)

Please try attached version.

**Comment by kitkars** [comment]
@mrniko 
Thanks for looking into this. Unfortunately I could not add this jar directly into the project. there were so many 'dependency missing' issues. do you have any fat jar which you share? or, If you had tested, then it is great. no worries.

**Comment by mrniko** [comment]
@kitkars 

Here is an all-in-one jar.
[redisson-all-3.16.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/6774978/redisson-all-3.16.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Done

**Comment by kitkars** [comment]
@mrniko I could not get back to you. The performance looks good now.

**Comment by mrniko** [comment]
@kitkars 

Thank you for feedback.
