### ISSUE TITLE
Allow to set task id for RScheduledExecutorService

### ISSUE THREAD

**Issue by up-to-you** [redisson/redisson#3707]
**Is your feature request related to a problem? Please describe.**

Currently, there is no "native" way to determine if task is already submitted to Executor in distributed environment, across several Application instances.
It's true when some of the instances restarts and the instance doesn't have any correlation between generated task id (random in current implementation) and actual task.

The new feature will allow to avoid submitting duplicate tasks.

**Describe the solution you'd like**

One of:
- Client can set custom task id for RScheduledExecutorService and verify this task id on startup without need to support additional data structures.
- Client can set custom task id for RScheduledExecutorService and Redisson deduplicates / ignore / reschedule new task with the same id. 

**Describe alternatives you've considered**

I used some sort of workaround and maintain separated HSET to hold actual submitted task, such that application instance calculates the ID from actual task on startup and verify that task already exists in HSET.
This approach is a kind of shame in our codebase, since it requires instances to have distributed lock for task verifying and registration process. It is something like leader election based on lock.

P.s. my thought that this is a crucial part in the library, since it will allow to seamlessly implement "distributed task queue" and get off unmaintained quartz solutions without extra hassles that i had to implement.

**Comment by up-to-you** [comment]
If this feature request will be accepted, maybe it's a point to consider built-in convenient distributed lock solution in ExecutorService itself, such that Client have option to manipulate with tasks in a safe manner across microservice instances (only within single instance at the same time).

**Comment by mrniko** [comment]
You can always check if taskId present using `hasTask()` method.

**Comment by up-to-you** [comment]
Yep, but taskid generates as a random in library, Client is not able to set custom task id, that can represent for example the actual task hash or something that has correlation. With random taskid if application restarts there is no way to restore it to check further.

**Comment by GuanTu** [comment]
Hi @mrniko , Is this feature considered for milestones?

**Comment by mrniko** [comment]
Done
