### ISSUE TITLE
Kotlin objects with JsonJacksonCodec 

### ISSUE THREAD

**Issue by elfogre** [redisson/redisson#3717]
Hi!!

I'm using Redis as a cache provider with the help of Redisson in a kotlin service.

At first I tried to set in redis non Serializable objects and I had to change to a JsonJacksonCodec in order to encode non Serializable objects. However some code at initTypeInclusion from JsonJacksonCode.java is avoiding our jackson to write @class property for kotlin classes (they are closed by default).

I have created a custom Codec in kotlin extending JsonJacksonCodec:

```
package com.bumble.utils.redis.redisson

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator
import org.redisson.codec.JsonJacksonCodec

class JsonJacksonKotlinCodec(objectMapper: ObjectMapper) : JsonJacksonCodec(objectMapper) {

    override fun initTypeInclusion(mapObjectMapper: ObjectMapper) {
        mapObjectMapper.activateDefaultTyping(BasicPolymorphicTypeValidator.builder()
            .allowIfBaseType(Any::class.java)
            .build(), ObjectMapper.DefaultTyping.EVERYTHING)
    }
}
```

And I start redisson with:

```
                val codec = JsonJacksonKotlinCodec(ObjectMapper())
                codec.objectMapper.registerKotlinModule()
                config.codec = codec
                config.useSingleServer().address = redisConfig.host
```

And everything works! Now I can serialize and deserialize kotlin classes into Json and keep them in redis.

However I'm wondering, as we are passing class type to getBucket:

`redisProvider.getClient()?.getBucket<V>(cacheKeyToString(namespace, key))?.get()?.awaitSingleOrNull()`

**Can't we just use that information to indicate Jackson which class should be used to deserialize???**

**Also, did you find OK my JsonJacksonKotlinCodec?**

**Comment by mrniko** [comment]
> Also, did you find OK my JsonJacksonKotlinCodec?

Yes.

> Can't we just use that information to indicate Jackson which class should be used to deserialize???

Unfortunately no, you can look at similar implementation of TypedJsonJacksonCodec. Which allows to specify types in constructor.
