### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource

### ISSUE THREAD

**Issue by githubylw** [redisson/redisson#3719]
1、my redisson version is: 3.12.3

2、my code like this:
RBlockingQueue queue = redissonClient.getBlockingQueue("queue_name");
XXVo = queue.take();

3、my problem is:
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeS
ubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:9:queue:0, freeConnectionsAmount=10, freeConnectionsCounter=value:13:queue:0, freezed=false, freezeReason=null, client=[addr=redis://x.x.x.x
:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@94976719 [redisClient=[addr=redis://x.x.x.x:6379], channel=[id: 0xd7d1fa38, L:0.0.0.0/0.0.0.0:33596], currentCommand=null], command: (BLPO
P), params: [xx_key, 0] after 3 retry attempts

4、additional: 
the queue may have 100 element, 99 take success, but 1 take occurred error above.

**Comment by coolbtoc** [comment]
how to resolution it? thx
