### ISSUE TITLE
org.redisson.client.RedisConnectionClosedException: Command (EVAL), params: [if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); retu..., 1, * * :10, 30000, 961d0a00-de8f-4176-935d-c4b7a71b17e8:911] succesfully sent, but channel [id: 0x96383] has been closed!

### ISSUE THREAD

**Issue by JasonLiuJinC** [redisson/redisson#3725]
项目中引入三个redis相关的依赖，本次新增redisson 3.9.1。
<dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>3.9.1</version>
     </dependency>

    <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-redis</artifactId>
                <version>2.3.0.RELEASE</version>
  </dependency>

     <dependency>
                <groupId>redis.clients</groupId>
                <artifactId>jedis</artifactId>
                <version>2.9.1</version>
       </dependency>

 没有重写redisson配置，使用默认的spring.redis配置

现在线上报有
org.redisson.client.RedisConnectionClosedException: Command (EVAL), params: [if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); retu..., 1, * * :10, 30000, 961d0a00-de8f-4176-935d-c4b7a71b17e8:911] succesfully sent, but channel [id: 0x96383] has been closed! 异常。

并伴有jedis报错
Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

请问是否因为本次引入redisson 导致 无法正常使用jedis。

使用代码如下：
        RLock lock = redissonClient.getLock(MessageFormat.format(ConstantRedis.BATCH_JOB_REDIS_KEY, shardingIndex));
        boolean bool = false;
        try {
            bool = lock.tryLock();
            if (bool) {
                List<TScrmBatchJob> batchJobList = tScrmBatchJobMapper.selectBatchTask(shardingIndex
                        , Lists.newArrayList(BatchJobStatusEnum.STATUS.WAIT.getCode(), BatchJobStatusEnum.STATUS.ING.getCode())
                        , maxSize, MAX_RETRY_COUNT);
                if (CollUtil.isEmpty(batchJobList)) {
                    return;
                } ...

**Comment by mrniko** [comment]
Do you use Redisson or Jedis?
