### ISSUE TITLE
RMapCache

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3727]
hi,
We use RMapCache object to save our data, but we can see that the redisson client gets all the map when we need data and not a specific key on the map.

is there a better way or map to prevent this behaviour and get the key we want instead of all the map and continue having TTL leave map ?

**Comment by mrniko** [comment]
> but we can see that the redisson client gets all the map when we need data and not a specific key on the map.

Please share code to reproduce.

**Comment by wdaas** [comment]
try {
            RMapCache<String, Object> map = this.getCacheMap(mapName);
            if(map != null){
                Object returnValue = map.get(key);
                return returnValue;
            }
        }catch (Exception e) {
            String msg = "failed to retrieve object element from redis cache for  "+currentDBUrl+mapName+" with key "+key;
            logger.error(msg,e);
            TicketingService.createDailyFixedAmountTickets(msg, Category.REDISSON_CACHE_FAILURE,
                    Environment.PRODUCTION, e, null, msg, maxTicketsPerDay);
        }

**Comment by mrniko** [comment]
You can check the code, it doesn't fetch all the data. It uses HGET command in lua-script.
