### ISSUE TITLE
Dynamic cache name when using with spring boot

### ISSUE THREAD

**Issue by hntan** [redisson/redisson#3731]
I'm using Spring Cache as the abstract level for caching and Redisson as the client. Everything works fine, but recently I had a an issue with high cpu and memory when handle a lot of requests. Now i'm searching how to optimize or solve it. I read https://redis.io/topics/memory-optimization and see that Redis hash data type works well only when there is small number of entries in a hash.

This is how I'm using Redisson with Spring Cache.
```
@Bean
public CacheManager cacheManager(RedissonClient redissonClient, ApplicationProperties applicationProperties) {
        Map<String, CacheConfig> config = new HashMap<>();

        long ttlInMinutes = applicationProperties.getRedis().getExpiration();

        config.put("CacheA", getCacheConfig(ttlInMinutes));
        config.put("CacheB", getCacheConfig(ttlInMinutes));

        return new RedissonSpringCacheManager(redissonClient, config);
}
```

And I use spring [Cacheable](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/annotation/Cacheable.html) annotation in my method with the value as "CacheA" or "CacheB".

I checked the source code of RedissonSpringCacheManager, Redisson create a RMapCache instance for every cache names which are mapped to corresponding hash key in Redis. In my example there is two RMapCache instances, one for "CacheA", and one for "CacheB".

Now come to my issue, because my cache object (ex: CacheA) has thousands of entries. My idea is to split it into smaller hashes by altering the cache name dynamically. Example: CacheA-1, CacheA-2,....

But how can I do that in Redisson? Bellow is the code of createMapCache method in RedissonSpringCacheManager.java

```
private Cache createMapCache(String name, CacheConfig config) {
        RMapCache<Object, Object> map = getMapCache(name, config);
        
        Cache cache = new RedissonCache(map, config, allowNullValues);
        Cache oldCache = instanceMap.putIfAbsent(name, cache);
        if (oldCache != null) {
            cache = oldCache;
        } else {
            map.setMaxSize(config.getMaxSize());
        }
        return cache;
    }
```

Thanks,

**Comment by mrniko** [comment]
You won't get memory allocation benefits splitting one hash into multiple.

**Comment by hntan** [comment]
Thank @mrniko, let me try those. Currently I'm using JsonJacksonCodec and maybe the issue is because of it.

**Comment by hntan** [comment]
Is there any reason MarshallingCodec is used inner of SnappyCodecV2/LZ4Codec @mrniko? why not to use MarshallingCodec directly?

**Comment by mrniko** [comment]
MarshallingCodec isn't a compression codec.
