### ISSUE TITLE
Can't parse json config /tomcat/redisson.conf

### ISSUE THREAD

**Issue by JSONY18** [redisson/redisson#3732]
I experienced "The session manager failed to start due to previous errors". It looks "Can't parse json config /tomcat/redisson.conf".

I attached the redisson.conf here. If someone can review the conf file and provide suggestion solving the errors, it would be really appreciated.

_SEVERE [main] org.redisson.tomcat.RedissonSessionManager.buildClient Can't parse json config /opt/tomcat/conf/redisson.conf
	com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "SingleServerConfig" (class org.redisson.config.Config), not marked as ignorable (23 known properties: "eventLoopGroup", "maxCleanUpDelay", "nettyHook", "keepPubSubOrder", "nettyThreads", "threads", "transportMode", "singleServerConfig", "sentinelServersConfig", "reliableTopicWatchdogTimeout", "useScriptCache", "minCleanUpDelay", "connectionListener", "executor", "codec", "replicatedServersConfig", "clusterServersConfig", "useThreadClassLoader", "masterSlaveServersConfig", "addressResolverGroupFactory", "lockWatchdogTimeout", "cleanUpKeysAmount", "referenceEnabled"])
 at [Source: (StringReader); line: 2, column: 23] (through reference chain: org.redisson.config.Config["SingleServerConfig"])_

[catalina_error.log](https://github.com/redisson/redisson/files/6818381/catalina_error.log)

[redisson.conf.txt](https://github.com/redisson/redisson/files/6818450/redisson.conf.txt)

**Comment by mrniko** [comment]
In logs I see Unrecognized field "pingTimeout" error. Rename it to `pingConnectionInterval`

**Comment by JSONY18** [comment]
Thank you to help figure out the issue
