### ISSUE TITLE
Predicate filter on RListReactive list returns non-deterministic result

### ISSUE THREAD

**Issue by christian3042** [redisson/redisson#3734]
**Expected behavior**
["B","B"]

**Actual behavior**
Returned array is non-deterministic way. Values that it can take:
["B"]
["B","B"]
["B","B","B"]

**Steps to reproduce or test case**
I use Redisson RedissonReactiveClient with Spring Boot 2.5.2. I wrote the following example code. When I hit refresh in the browser, I receive different array sizes in a non-deterministic way. The array is always deleted before the execution, so array should always contain the following 4 elements and filtering by "B" should return the two elements of the array, where the result  of the applied predicate is true.
Redis runs dockerized on localhost.
```
    @GetMapping("issue")
    public List<String> issue() {
        redissonReactiveClient.getList("testList").delete().block();
        RListReactive<String> testList = redissonReactiveClient.getList("testList");
        testList.add("A").block();
        testList.add("B").block();
        testList.add("A").block();
        testList.add("B").block();
        Predicate<String> lambdaPredicate = (String s) -> (s.equals("B"));
        Flux<String> ret = testList.iterator().filter(lambdaPredicate);
        return ret.collectList().block();
    }
```
**Redis version**
6.2.4

**Redisson version**
3.16.0

**Redisson configuration**
```
    @Bean
    public RedissonReactiveClient getRedissonClient() {
        Config config = new Config();
        config.useSingleServer()
                // use "rediss://" for SSL connection
                .setAddress("redis://localhost:6379").setPassword(redisPassword);
        RedissonClient redisson = Redisson.create(config);
        RedissonReactiveClient redissonReactive = redisson.reactive();
        return redissonReactive;
    }
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
