### ISSUE TITLE
data consistency

### ISSUE THREAD

**Issue by jokertom231** [redisson/redisson#3737]
分布式锁，以redlock为例
客户端两台：客户端a，客户端b
客户端执行秒杀操作，直接操作redis，
1、首先客户端a，客户端b同时抢锁，
2、最终客户端a获取锁，然后执行业务处理（不需要网络）
3、这时客户端a 网络通信故障，致使客户端b获取到锁了，客户端b正常操作，修改状态数据（redis 数据）
4、之后接着客户端a网络正常了，也直接修改状态数据，（修正状态在lock 之后，但是显然此时客户端a处于无锁状态）

这样数据一致性不就没有保证了吗？

1、a.lock
2、业务逻辑
3、修正状态
4、a.unlock

走的第二步，第三步客户端处于无锁状态的，
一种想法1、后台watchdog 线程，检测到超时后阻塞业务线程 （但是好像没找到阻塞非当前线程的api)
另一种想法2、在unlock 时，假如redis 当前持锁线程非自己时，抛异常（貌似是这么处理的，不过，这样处理的话，那不是正确操作
应当捕获unlock 下的异常，然后对修改状态的操作做补偿了，也好像不太对）。

**Comment by mrniko** [comment]
you need to define big enough `leaseTimeout` value during lock acquisition. So it can survive absence of network.

**Comment by jokertom231** [comment]
define big enough leaseTimeout can solves most situations，optimistic locking can be used in extreme cases.
have studeied ,This is what happens with distributed locks today
finally thanks for your comments.
