### ISSUE TITLE
Batch check the existence of keys in RedissonMap

### ISSUE THREAD

**Issue by MFAshby** [redisson/redisson#3738]
**Is your feature request related to a problem? Please describe.**
I am using RedissonMap to store ... a map! Sometimes I wish to check if a key is present in the map without having to actually get the value. Redis provides a command [HEXISTS](https://redis.io/commands/hexists) to do this, and I can see that in RedissonMap we leverage this command to implement containsKey efficiently. 

However, sometimes I would like to check the presence of _multiple_ keys in the map, sometimes many thousands. The naive solution to simple call `containsKey` ends up round-tripping to redis many times. 

**Describe the solution you'd like**

I would like a batch method (maybe something like containsKeys) which indicates the presence or absence of many keys at once, without round-tripping to redis many times.

**Describe alternatives you've considered**

I can call getAll() and just look at which keys got returned, however this returns all the values as well, which I don't care about in my case and which consume additional network + memory resources.

I could bypass RedissonMap and simply issue a pipelined request for many HEXISTS, but this is extra complexity I have to handle myself and it bypasses the RMap abstraction.

**Comment by MFAshby** [comment]
Reading around, it might be better to just make sure [pipelining](https://redis.io/topics/pipelining) is enabled in my case, rather than doing a multi/exec command. Checking.

**Comment by mrniko** [comment]
Use RBatch object for pipelining.
