### ISSUE TITLE
Question about Redisson pub/sub listeners not re-subscribing after Redis maintenance

### ISSUE THREAD

**Issue by taksamit** [redisson/redisson#3739]
Hi,

I'm fairly new to Redis/Redisson and have a question about an issue that I have encountered during Redis maintenance (planned switchover I think).

My application is running on Azure against Azure Cache for Redis

The application is using Redisson pub/sub listeners but after Redis maintenance only 1 of many listeners re-subscribed and other listeners fail to deliver new messages that are being published.

I'm not sure if I should increase some retries-related configuration to avoid this problem or is more in-depth investigation (including redisson logs) required.

Example of successful re-subscription:
07/07/2021 23:44:50.636 [redisson-netty-2-8] INFO onUnsubscribe vrckc-req-b5da10e2f29cc6c9dd7632279444fc8f
(...)
07/07/2021 23:44:51.702 [redisson-3-4] INFO onSubscribe vrckc-req-b5da10e2f29cc6c9dd7632279444fc8f

Example of failure (extending of RLock lease time) that happens during maintenance
07/07/2021 23:44:54.503 [redisson-timer-4-1] ERROR org.redisson.RedissonBaseLock Can't update lock vrckc-leader expiration
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezeReason=null, client=[addr=rediss://10.151.20.4:15000], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1994070121 [redisClient=[addr=rediss://10.151.20.4:15000], channel=[id: 0xeb6e5b0a, L:0.0.0.0/0.0.0.0:54958], currentCommand=null], command: null, params: null after 1 retry attempts

Redis config that I'm using:

  redisConfig.yaml: |-
    clusterServersConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 15000
      pingConnectionInterval: 5000
      tcpNoDelay: true
      keepAlive: true
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      failedSlaveReconnectionInterval: 3000
      failedSlaveCheckInterval: 60000
      password: ${REDIS_AZURE_PASSWORD}
      subscriptionsPerConnection: 5
      clientName: null
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      slaveConnectionMinimumIdleSize: 24
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 24
      masterConnectionPoolSize: 64
      readMode: "MASTER"
      subscriptionMode: "SLAVE"
      nodeAddresses:
        - "rediss://${REDIS_AZURE_HOSTNAME}:{{ .Values.redis.azure.sslPort }}"
    threads: 16
    nettyThreads: 16
    codec: !<org.redisson.client.codec.StringCodec> {}
    transportMode: "NIO"

I would appreciate any help with this issue.

**Comment by mrniko** [comment]
how long did the maintenance take?

**Comment by taksamit** [comment]
I'm not sure but I think it might have been a failover of master from one node to another

**Comment by mrniko** [comment]
I know, but how long?

**Comment by taksamit** [comment]
from application logs it seems to have taken only a couple of seconds: from the time of the first 'onUnsubscribe' notification from Redisson to successfully locking a RLock was only around 5 seconds

**Comment by mrniko** [comment]
retry time 3*1500 = 4500 ms is not enough in your case. Increase `retryAttempts` parameter

**Comment by taksamit** [comment]
thank you, so retryAttempts parameter will apply to pub/sub listeners resubscribing scenario: correct?
Is there a reasonable value for this parameter to cater for "reasonable" scenarios?
I noticed that out of many status listeners only 1 fired an onUnsubscribe() notification but others didn't (but remained not working, which looks incorrect to me): is there a way to check programmatically if a listener is currently subscribed or not? For instance if all Redisson retries fail and no more retries will be attempted how can an application find out that it needs to create new listeners?

**Comment by mrniko** [comment]
Can you set TRACE logging level for `org.redisson` package and share before after failover.

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by taksamit** [comment]
I use Redisson version 3.15.6

**Comment by mrniko** [comment]
@taksamit 

https://github.com/redisson/redisson/issues/3739#issuecomment-885419869

**Comment by taksamit** [comment]
It will take me a while to get Redisson logs as I don't have access to Azure cluster in my organization: when I get these I'll post them here

**Comment by taksamit** [comment]
in the meantime could you please let me know if there is a way to check programmatically if a listener is currently subscribed or not?

**Comment by mrniko** [comment]
You can only count listeners and subscribers.

**Comment by taksamit** [comment]
I add a fixed set of listeners: one message listener and one status listener. After adding these two listeners topic.countListeners() returns 2.
If during Redis failover these listeners fail to re-subscribe what would topic.countListeners() return: 0 ?

**Comment by mrniko** [comment]
let me check

**Comment by mrniko** [comment]
Unable to reproduce it. Please share logs.

**Comment by raksamit** [comment]
I finally got access to Azure Portal but I'm unable to reproduce the issue by rebooting Azure ports.

From a genuine issue occurrence (where pub/sub listeners fail to notify about new messages) these are the only logs that I have:

2021-08-20T11:19:37.486Z,listeners of 'vrckc-req-84590c512ee100aa8fca3ab6930c7e7c' channel to '[addr=rediss://10.60.20.4:15001]' have been resubscribed
2021-08-20T11:19:37.486Z,startFor() onSubscribe vrckc-req-84590c512ee100aa8fca3ab6930c7e7c
2021-08-20T11:19:37.486Z,listeners of 'vrckc-req-a9eff73848279907b036b8c9493678ee' channel to '[addr=rediss://10.60.20.4:15001]' have been resubscribed
2021-08-20T11:19:37.486Z,startFor() onSubscribe vrckc-req-a9eff73848279907b036b8c9493678ee
2021-08-20T11:19:37.102Z,24 connections initialized for 10.60.20.4/10.60.20.4:15001
2021-08-20T11:19:36.784Z,1 connections initialized for 10.60.20.4/10.60.20.4:15001
2021-08-20T11:19:36.415Z,startFor() onUnsubscribe vrckc-req-84590c512ee100aa8fca3ab6930c7e7c
2021-08-20T11:19:36.414Z,slave: rediss://10.60.20.4:15000 has down for slot ranges: [[0-8191]]
2021-08-20T11:19:36.414Z,startFor() onUnsubscribe vrckc-req-a9eff73848279907b036b8c9493678ee
2021-08-20T11:19:36.414Z,master 10.60.20.4/10.60.20.4:15001 used as slave

Do these shed any light as to the nature of the event that happens? I think now that it might not be a redis node reboot but something completely different. Does the line "master 10.60.20.4/10.60.20.4:15001 used as slave" tell us something meaningful?

**Comment by mrniko** [comment]
@raksamit 

During channel resubscription messages might be lost. Do you miss messages even after successful resubscription?

**Comment by raksamit** [comment]
@mrniko 
Yes, the problem is that from some point in time I don't get ANY messages. Whether listener re-subscription is successful or not I'm not entirely sure i.e. whether resubscription is fine but no events reported or resubscription fails.
I'll try some more times to reproduce this but simply rebooting Redis nodes doesn't seem to easily reproduce the issue. I'm wondering if the issue is caused by some other Azure Cache for Redis activities such as Redis nodes patching.

**Comment by raksamit** [comment]
@mrniko 
one more question if I may: currently I set `subscriptionMode: "SLAVE"` and I'm wondering do I have better chances if I change it to "MASTER" ? 
I see at least some occurrences where the issue happens after (I think) slave goes down, e.g:
`slave: rediss://10.164.20.4:15001 has down for slot ranges: [[0-8191]]`

**Comment by raksamit** [comment]
@mrniko 
In case my application design is incorrect I'd like to clarify my use of Redisson.
I have multiple kubernetes pods which use a single RLock to determine a single pod that becomes the master in the application.
These multiple kubernetes pods also subscribe to and publish to RTopics.
All of the above is happening via a single RedissonClient.
I found [here](https://redis.io/topics/pubsub) this : _A client subscribed to one or more channels should not issue commands_ : is it ok for me then to use a single RedissonClient to interact with RLock, subscribe to RTopics and also publish to RTopics at the same time?

**Comment by raksamit** [comment]
I also found one instance of this issue and the only sign shortly before it happens is a sequence of 29 logs (for different connections/ports) like this one:
`Unable to send PING command over channel: [id: 0xd644d7af, L:/10.193.8.108:41038 - R:10.193.20.4/10.193.20.4:15000]`

**Comment by mrniko** [comment]
> I see at least some occurrences where the issue happens after (I think) slave goes down, e.g:

all messages sent during failover will be lost. You can use `getReliableTopic` which is resistant to failure.

**Comment by mrniko** [comment]
> A client subscribed to one or more channels should not issue commands

It's related to pubsub connection and to whole client instance.

**Comment by mrniko** [comment]
> Unable to send PING command over channel: [id: 0xd644d7af, L:/10.193.8.108:41038 - R:10.193.20.4/10.193.20.4:15000]

Means some problem with channel.
