### ISSUE TITLE
RedissonClient.getList() performance

### ISSUE THREAD

**Issue by awsiv** [redisson/redisson#3741]
Hi,

RedissonClient.getList() currently is doing a count on the list and retrieving every item one by one. We have a dynamic list that increases with time so the response time of the app also increases linearly with as the time to fetch more of the list items get longer.

From AWS xray tracing:
```
Sample LINDEX query:

{
    "default": {
        "db.connection_string": "<redacted>:6379",
        "db.statement": "LINDEX <redacted> 1",
        "db.system": "redis",
        "thread.name": "<redacted>",
        "thread.id": ""
    }
}
```

We have 267 items in the list and the above repeats for all items in the list:

![xray-1](https://user-images.githubusercontent.com/1265825/126747871-6c7a9079-f715-4520-8892-9778b418adaf.png)

If there a way to get all list items in redisson with `LRANGE` instead?

**Comment by mrniko** [comment]
you can find Redis commands mapping here https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping

**Comment by awsiv** [comment]
Thanks @mrniko 

My usecase is to fetch a single list. Looks like these do not support passing the name as an argument?

<html>
<body>


LRANGE | RList.readAll()readAllAsync() | RListReactive.readAll() | RListRx.readAll()
-- | -- | -- | --



</body>
</html>

**Comment by awsiv** [comment]
@mrniko Awesome! Thanks for the quick response :)

This is how it looks now:
![xray-2](https://user-images.githubusercontent.com/1265825/126765010-c2912418-33af-4f53-bf12-2a2562c0b40c.png)


Only 2 requests to redis instead of 270!


Also: This is how the response time used to look like before. Expecting *huge* improvement there
![response-time](https://user-images.githubusercontent.com/1265825/126765261-3ec1e3f7-8166-4b46-97e0-0fc260b55f4d.png)
