### ISSUE TITLE
Command still hasn't been written into connection!

### ISSUE THREAD

**Issue by ddehen** [redisson/redisson#3745]
We are experiencing what at first glance seems like network related errors using the latest version of redisson pro. However we noticed that this error only occurs on LPOP commands.  

```
2021-07-26 09:31:05,547 [trace=,span=] ERROR                    h:221  - Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=4753, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection [entry=[commandsBatch=830, entry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:47:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=rediss://xfv.gnfyko.euw1.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0], commandsBatchSemaphore=value:0:queue:2, sendWorkers=0, connectionsAmount=2], redisClient=[addr=rediss://xfv.gnfyko.euw1.cache.amazonaws.com:6379]], command: (LPOP), params: [prv::V1.0::{playlist.collection}:write-behind-queue] after 3 retry attempts
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0. Node source: NodeSource [slot=4753, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection [entry=[commandsBatch=830, entry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:47:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=rediss://xfv.gnfyko.euw1.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0], commandsBatchSemaphore=value:0:queue:2, sendWorkers=0, connectionsAmount=2], redisClient=[addr=rediss://xfv.gnfyko.euw1.cache.amazonaws.com:6379]], command: (LPOP), params: [prv::V1.0::{playlist.collection}:write-behind-queue] after 3 retry attempts
```

Increasing netty threads has no effect on this, also increasing timeout config did not improve the errors. 

Also when deploying our code (on a test environment without load) we see a heavy increase in cpu usage on redis master nodes. The load increases by 50% and drops very slowly in about 1 hour to <5% 

We are using the RedissonClusteredSpringLocalCachedCacheManager (but the same occurs when using RedissonClusteredSpringCacheManager)

**Comment by mrniko** [comment]
try to set performanceMode = `HIGHER_THROUGHPUT` setting

**Comment by mrniko** [comment]
> Also when deploying our code (on a test environment without load) we see a heavy increase in cpu usage on redis master nodes.

Can you set `trace` logging level for `org.redisson` to examine sent redis commands?

**Comment by mrniko** [comment]
please update to 3.16.0-7 version as well it contains connection leak fix https://github.com/redisson/redisson/commit/34d2e4de3a8b6cc9170fe7b5d82d40498fe60f1e

**Comment by ddehen** [comment]
Hi mrniko,

i've updated the version to 3.16.0-7 but it didn't fix the issue. As you suggested I've tried to enable trace logging on the org.redisson package, however after 30sec of logging it left me with a file of 17GB. I can see the commands that are executed but have no clue why the amount is so large. For what it's worth I've attached a small sample of the logfile.
[redisson-log-sample.txt](https://github.com/redisson/redisson/files/6879313/redisson-log-sample.txt)

Setting performance mode to `HIGHER_THROUGHPUT` did not have any noticable effect.

However I've updated my code to replace RedissonClusteredSpringLocalCachedCacheManager with RedissonSpringLocalCachedCacheManager and the problems are gone when using the latter cache manager. Sadly this is not a fix as we do need the data partitioning of the clustered cache manager.

On attempting to simulate the problem on a test project I've come across something else which I'm not sure if related. It seems that updates do not get propagated to the cache after some time. I've attached a test to reproduce this, the test is expected to update it's local cache every 10 seconds, but already after 20 seconds the old value keeps coming back from cache and never gets updated. When you replace the RedissonClusteredSpringLocalCachedCacheManager with the RedissonSpringLocalCachedCacheManager everything just works. Also when removing the namemapper everything works as expected.
[redisson-test.zip](https://github.com/redisson/redisson/files/6879309/redisson-test.zip)

**Comment by mrniko** [comment]
Thanks for shared code and logs. Will try to run it.

> Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@64639164(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=8616, addr=null, redisClient=null, redirect=null, entry=null], command: (BLPOP)

I see you use executorService which causes connection starvation, due to blpop command usage. BLPOP command allocates connection and can't share it with other commands. It's worth to note that test application doesn't contain executorService usage.

Did you try to set `masterConnectionMinimumIdleSize` = 500 and `masterConnectionPoolSize` = 500 ?

**Comment by mrniko** [comment]
Also MapWriter didn't define but writeBehind settings were defined.

**Comment by mrniko** [comment]
Unable to reproduce the issue using cache with your config:

```java

        final LocalCachedMapOptions<Object, Object> localCacheOptions = LocalCachedMapOptions.defaults()
                .storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE_REDIS)
                .cacheProvider(LocalCachedMapOptions.CacheProvider.CAFFEINE)
                .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.LRU)
                .writeMode(MapOptions.WriteMode.WRITE_BEHIND)
                .timeToLive(10000, TimeUnit.MILLISECONDS)
                .maxIdle(0)
                .cacheSize(10)
                .writeBehindBatchSize(100)
                .writeBehindDelay(3000);

        final LocalCachedCacheConfig cacheConfig = new org.redisson.spring.cache.LocalCachedCacheConfig(
                2000,
                0,
                localCacheOptions);
        cacheConfig.setMaxSize(10);
        final HashMap config = new HashMap<String, org.redisson.spring.cache.LocalCachedCacheConfig>();
        config.put("test", cacheConfig);

        RedissonClusteredSpringLocalCachedCacheManager m = new RedissonClusteredSpringLocalCachedCacheManager(redisson, config);

        for (int i = 0; i < 10000; i++) {
            m.getCache("test").put(i, i);
        }

```

**Comment by mrniko** [comment]
Did you resolve the issue?
