### ISSUE TITLE
not consistent response

### ISSUE THREAD

**Issue by wdaas** [redisson/redisson#3746]
We have 2 application servers (Tomcats) and our application is not sticky which mean that every request can reach different application server.
In our flow we upload data from one server to Redis and then read data from the second server but don't get the uploaded data.
Can the reason for this behavior can be related to local cache implementation in Redisson? Can we disable it per put request or only disable it for all Redisson client requests?

we use to get the data
RMapCache<String, Object> map = redisson.getMapCache 

and to put data 
map.fastPutAsync(key, value, units, timeUnit);

**Comment by mrniko** [comment]
> In our flow we upload data from one server to Redis and then read data from the second server but don't get the uploaded data.

You encounter replication lag between Redis servers. You can use RBatch with `syncSlaves` setting set.

**Comment by wdaas** [comment]
we use putAsync how we can wait to finish?

is there some cache at local server that prevents us to get updated data?

**Comment by mrniko** [comment]
> we use putAsync how we can wait to finish?

Adding feature complete handler.

> is there some cache at local server that prevents us to get updated data?

No, RMapCache object doesn't store data on Java side. You can check source code.
