### ISSUE TITLE
Regression - quarkus native builds fail after updating netty in 3.16.1

### ISSUE THREAD

**Issue by dmitry-scaleswap** [redisson/redisson#3747]
After upgrading to redisson 3.16.1 there are build failures of native quarkus, the stracktrace points to netty. as far as i can see there was a minor version upgrade of netty in the last release, so maybe this is the reason, in 3.16.0 everything works fine.

Quarkus Version: 2.0.3 Final

`Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from jar:file:///project/lib/io.netty.netty-buffer-4.1.65.Final.jar!/META-INF/native-image/io.netty/buffer/native-image.properties). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:545)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:228)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$14(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1`

**Comment by mrniko** [comment]
in 3.16.1 version netty was updated to 4.1.66 version.

**Comment by dmitry-scaleswap** [comment]
As for quarkus - in its latest release they are based on 4.1.65, also having a wrapper-dependency called quarkus-netty, which optimizes nettys classes to use with graal, like here: https://github.com/quarkusio/quarkus/blob/main/extensions/netty/runtime/src/main/java/io/quarkus/netty/runtime/graal/NettySubstitutions.java
maybe it could be a good hint

**Comment by mrniko** [comment]
Can you propose required changes?

**Comment by dmitry-scaleswap** [comment]
I can propose a workaround..after investigating the issue i've found out that the problem was the JsonJacksonCodec that i've set in a custom RedissonClient Bean like this:
`
Config c = new Config();
c.setCodec(new JsonJacksonCodec());
...
redisson = Redisson.create(c);
`
if i use the RedissonClient DefaultBean even with the JsonJacksonCodec configured through the properties, the error doesn't occure. If i understand it correctly this bean is created differently, in the build time or something. So my workaround would be to configure my redisson client purely over configuration properties and not create a custom bean.

**Comment by dmitry-scaleswap** [comment]
I see the problem in this new warmup feature, the warmup function is executed in the constructor of JsonJacksonCodec, and during the warmup following netty classes are initialized:

io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf
io.netty.buffer.ByteBufUtil

While building the native image this initialization fails because the initialization policy of this classes is RUN_TIME and not BUILD_TIME. Maybe we could make this warmup feature parameterized for the codec object construction?

**Comment by mrniko** [comment]
CodecsSubstitution can be added which replaces `private void warmup()` methods.

**Comment by mrniko** [comment]
Fixed
