### ISSUE TITLE
RedisTimeoutException following RedisLoadingException

### ISSUE THREAD

**Issue by theanhdh** [redisson/redisson#3749]
In our setup, we have sharded mode cluster consisting of 6 shares, 2 nodes per shard.
Our redisson client interacts with only the MASTER node in each shard.

Recently we experienced the following exception: "org.redisson.client.RedisLoadingException: LOADING Redis is loading the dataset in memory". Following that exception, we had been getting RedisTimeoutException on majority of the calls until we finally restarted our application services and the problems went away.

Any clue as to what might be the cause of this? I am suspecting this is a problem with the redisson client itself.

Redisson version: 3.11.6-3

**Comment by mrniko** [comment]
This error reported by Redis. https://bobcares.com/blog/error-loading-redis-is-loading-the-dataset-in-memory/

**Comment by theanhdh** [comment]
Thanks @mrniko . We reached out to AWS and they were suggesting upgrading to bigger instance size which supports higher network bandwidth. I'd like to confirm if upgrading to latest Redisson client will resolve the stale Redisson connection.

**Comment by mrniko** [comment]
> I'd like to confirm if upgrading to latest Redisson client will resolve the stale Redisson connection

Can you provide more details about that?

**Comment by theanhdh** [comment]
... we experienced the following exception: "org.redisson.client.RedisLoadingException: LOADING Redis is loading the dataset in memory". Following that exception, we had been getting RedisTimeoutException on majority of the calls until we finally restarted our application services and the problems went away.

**Comment by mrniko** [comment]
RedisTimeoutException occurs if data loading process didn't complete in time. Which is defined by timeout and retry attempts + retry intervals.

**Comment by theanhdh** [comment]
Right, but the problem is that it continued throwing RedisTimeoutException forever until we force the application server to restart and the problem went away. So i am suspecting the connection managed by Redisson became unusable whenever RedisTieoutException occurs; and a restart is needed.

**Comment by mrniko** [comment]
Can you provide logs?
