### ISSUE TITLE
RDeque Or RPriorityDeque Lost data

### ISSUE THREAD

**Issue by 303489429** [redisson/redisson#3751]
version: redisson-3.13.2
add code:
![image](https://user-images.githubusercontent.com/16587700/127636995-4c3a14c0-c7d4-4bbd-963d-dee468cc48a8.png)

consumer code:
![image](https://user-images.githubusercontent.com/16587700/127637252-ca989235-fc1c-4cd6-9759-81965ae8f2cc.png)

add success, but Occasionally, data is not consumed .
There is no recurrence problem in the local stress test, but it occurs occasionally in the production environment

**Comment by mrniko** [comment]
RPriorityDeque isn't compatible with RBlockingDeque object.
