### ISSUE TITLE
Redisson throwing java.io.NotSerializableException when trying to publish something in a topic

### ISSUE THREAD

**Issue by MAXOUXAX** [redisson/redisson#3755]
I'm really confused as to why I got this error, and I might have misunderstood how topics work with objects in Java.

So basically when doing `RedissonClient#getTopic(nameOfTheTopic).publish(objectToPublish)`, I'm getting this NotSerializableException.

The object I'm trying to send is this class:
```java
import java.time.LocalDate;

public class ClassToPublish {

    private final String command;
    private final LocalDate date;

    public ClassToPublish(String command, LocalDate date) {
        this.command = command;
        this.date = date;
    }

    public String getCommand() {
        return command;
    }

    public LocalDate getDate() {
        return date;
    }

}
```

Can't you send classes other than the ones from the JRE or am I missing something that I need to do in order to be able to do so?

**Comment by mrniko** [comment]
default codec is MarshallingCodec. It requires Serializable interface for each object.
