### ISSUE TITLE
the method  RRateLimiter.expire() is incorrect working

### ISSUE THREAD

**Issue by 91diy** [redisson/redisson#3756]
this is my code :
`
            String key = REDISSON_RATE_LIMIT + limit.prefix() + ":" +spel;
            RRateLimiter rRateLimiter = redissonClient.getRateLimiter(key);
            rRateLimiter.trySetRate(RateType.OVERALL, limit.rate(), limit.rateInterval(), limit.unit());

            if (limit.expireSecond() !=-1) {
                rRateLimiter.expire(limit.expireSecond(), TimeUnit.SECONDS);
            }

@RedissonRateLimit(prefix = "trade", spel = "#trade.rootMchId",
            rate = 1, rateInterval = 2, unit = RateIntervalUnit.SECONDS, expireSecond = 5)
    @PostMapping("/trade")
    public ResponseEntity trade(@RequestBody Trade trade) {
        return ResponseEntity.ok("success");
    }
`
 then I fund a bug ：
5 seconds have passed， the  redis key “redisson_rate_limit:trade:rootMchId0001” has removed，but the redis key 
"{redisson_rate_limit:trade:rootMchId0001}:permits" and “{redisson_rate_limit:trade:rootMchId0001}:value ”  still exist.

Who knows you can help me？please...

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2931
