### ISSUE TITLE
Redis Stream Support For Spring Applications

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3759]
@mrniko 

This is a feature request.
Currently Spring supports only **_Kafka_** and **_RabbitMQ_** for cloud stream applications. There is no support for Redis Stream. 

https://github.com/spring-cloud/spring-cloud-stream#binder-implementations

I think Redisson could implement this interface and provide redis binder via redisson.

**Comment by mrniko** [comment]
Done https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks/#149-spring-cloud-stream
