### ISSUE TITLE
Does near cache options also apply to the backing RMap?

### ISSUE THREAD

**Issue by asarkar** [redisson/redisson#3765]
I can set max size, eviction algorithm etc. using `LocalCachedMapOptions`, but it's unclear from the documentation if those options also apply to the backing `RMap`. Given that `RLocalCachedMap` does not subclass `RMapCache`, I'm guessing no, but would like to hear from a maintainer.
You can use this ticket for improving the documentation in this respect.

**Comment by mrniko** [comment]
LocalCachedMapOptions applied only to local cache. Also comment to each settings mention local cache only, not RMap object.

**Comment by asarkar** [comment]
@mrniko Is there a way to apply the same settings both locally and on the server?

**Comment by mrniko** [comment]
Local cache support for MapCache object supported in PRO version only.
