### ISSUE TITLE
Redis operations metrics

### ISSUE THREAD

**Issue by asarkar** [redisson/redisson#3766]
**Is your feature request related to a problem? Please describe.**
I'd like to see metrics for low level Redis operations, like GET, SET etc.

**Describe the solution you'd like**
Expose metrics around these operations. The only available metrics is for `RedissonCache`, and there is no visibility into any of the other data structures.
As a less desirable solution, you may consider providing interceptors for a client to implement and export their own metrics.

**Describe alternatives you've considered**
None

**Comment by mrniko** [comment]
Statistics monitoring is available as separate feature - https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#1414-statistics-monitoring-jmx-and-other-systems

**Comment by asarkar** [comment]
@mrniko That seems like a pro feature and also different from what I'm looking for. Metrics can be published to a listener or event bus, from where the client app may export it to their system of choice. is that possible? This is supported in Lettuce. https://lettuce.io/core/release/reference/#observability

**Comment by mrniko** [comment]
it's not supported yet. There are no lua scripts in lettuce. How do you handle lua scripts in this case?

**Comment by asarkar** [comment]
I’m not sure why do you think metrics are related to lua scripts. That said, Spring Data Redis can execute lua scripts, and they use Lettuce as the default driver, so there must be a way, I just don’t know it.
