### ISSUE TITLE
RedissonReactiveClient limitations

### ISSUE THREAD

**Issue by asarkar** [redisson/redisson#3767]
**Is your feature request related to a problem? Please describe.**
`RedissonReactiveClient` is missing many of the features compared to  `RedissonClient`.
1. Returned `RMapReactive` has no methods to set max size or eviction algorithm.
2. No method to create a `LocalCachedMap` (or perhaps) `LocalCachedMapReactive`. There's an open issue https://github.com/redisson/redisson/issues/3671 for this point only.

**Describe the solution you'd like**
Bring feature parity between blocking and reactive API.

**Describe alternatives you've considered**
Using blocking API.

**Comment by mrniko** [comment]
> Returned RMapReactive has no methods to set max size or eviction algorithm

RMapReactive object doesn't support max size and eviction. I agree that RMapCacheReactive misses method to define eviction algorithm. Will fix that.

**Comment by asarkar** [comment]
@mrniko What about point point 2 (No method to create a LocalCachedMap (or perhaps) LocalCachedMapReactive)?

**Comment by mrniko** [comment]
Reactive LocalCachedMap implemented in https://github.com/redisson/redisson/issues/3181
