### ISSUE TITLE
Flushing write-behind tasks

### ISSUE THREAD

**Issue by Flo0** [redisson/redisson#3768]
So i have set up redis as read-through/write-behind cache for a mongoDB. Now there is data i want to persist when the application stops.
Writing into the cache isnt enough as the MapWriter that writes from redis into mongodb is run by the same application.

If i stop the application and write my data into the cache then my MapWriter wants to wait some seconds to batch write the data from cache into db.
But at this time the application is already stopped and nothing will be persisted.
Is there some way to flush the write-behind tasks in a blocking fashion?

**Comment by mrniko** [comment]
WriteBehind service flashes all tasks if write-behind queue is empty. `org.redisson.MapWriteBehindTask#pollTask`

**Comment by Flo0** [comment]
Ok nice. But the only way i see to get the `WriteBehindService` from my `Redisson` instance is by extending `Redisson` and exposing the `WriteBehindService` with a getter, which is currently not the case.

**Comment by mrniko** [comment]
I fixed that. Tasks are flushed on Redisson shutdown.
