### ISSUE TITLE
Topic listener removal

### ISSUE THREAD

**Issue by asarkar** [redisson/redisson#3777]
Is it necessary to explicitly remove a Topic listener before shutdown, or does shutdown remove it anyway?

**Comment by mrniko** [comment]
No, it's not necessary.

**Comment by asarkar** [comment]
@mrniko Rephrasing as “shutdown removes all local listeners, no need to do it explicitly”, closing this ticket. Thank you.

**Comment by mrniko** [comment]
it doesn't remove listeners, just shutdown network connection to Redis.

**Comment by asarkar** [comment]
I’m confused, isn’t that the same thing? Unless the server keeps a count of the listeners.

**Comment by asarkar** [comment]
For the record, I've verified that the count is local to the JVM.
