### ISSUE TITLE
Listeners unregistered

### ISSUE THREAD

**Issue by Aurelien30000** [redisson/redisson#3778]
Hey

Not sure if this is an issue. I'm using a topic to transit data between two instances. Sometimes, listeners are unregistered randomly, and I don't know why, server is just publishing data, it works 1-5 times and then it breaks :/

Config:
```java
redissonConfig.setCodec(new JsonJacksonCodec())
                .setThreads(8)
                .setNettyThreads(8)
                .useSingleServer());
```

Monitor (first _wave_ it works, second doesn't) :
https://paste.domicraft.fr/vakuxahawa.json

Thanks for your help, if you need more details, tell me!

Redisson 3.16.1 - Redis 6.2.5

**Comment by mrniko** [comment]
I don't see subscribe on voteRewards in your logs. Is it possible to provide code to reproduce it?

**Comment by Aurelien30000** [comment]
Right, didn't copy it, but subscribe is done and works primarily. Operations with locks and ``domiAccount:UUID`` are triggered by listening to ``voteRewards`` topic.

Listener:
```java
redissonClient.getTopic("voteRewards").addListener(Object[].class, (key, args) -> Task.runSync(() -> {
            final String playerName = (String) args[0];
            final int rewardType = (int) args[1];
            final OfflinePlayer offlinePlayer = Bukkit.getOfflinePlayer(playerName);

            switch (rewardType) {
                case 3 -> DomicoinsManager.add(offlinePlayer, 1 + RandomUtils.getRandomDouble(6));
            }
        }));
```

DomicoinsManager stuff:
```java
    public static CompletableFuture<Boolean> add(OfflinePlayer offlinePlayer, double coins) {
            final DomiPlayer domiPlayer = PlayerManager.getPlayer(offlinePlayer.getUniqueId());

            return domiPlayer.modifyAccountAsync(domiAccount -> {
                domiAccount.add(coins);

                return true;
            });
    }
```

DomiPlayer stuff:
```java
    public CompletableFuture<Boolean> modifyAccountAsync(Function<DomiAccount, Boolean> function) {
        final CompletableFuture<Boolean> completableFuture = new CompletableFuture<>();

        getAccountAsync().thenAccept(domiAccount -> {
            try {
                if (function.apply(domiAccount)) {
                    domiAccount.saveToRedis();
                }
                completableFuture.complete(true);
            } catch (Throwable t) {
                t.printStackTrace();
                completableFuture.complete(false);
            } finally {
                final RLock lock = AccountManager.getRLockAccount(uuid);
                lock.unlock();
            }
        });

        return completableFuture;
    }

    public RFuture<DomiAccount> getAccountAsync() {
        final RPromise<DomiAccount> rFuture = new RedissonPromise<>();

        CompletableFuture.supplyAsync(() -> {
                    final RLock lock = AccountManager.getRLockAccount(uuid);
                    lock.lock(10, TimeUnit.SECONDS);
                    return AccountManager.getRAccount(uuid).get();
                }).thenAccept(rFuture::trySuccess);

        return rFuture;
    }
```

AccountManager stuff:
```java
    public static RBucket<DomiAccount> getRAccount(UUID uuid) {
        return RedisManager.getRedissonClient().getBucket("domiAccount:" + uuid);
    }

    public static RLock getRLockAccount(UUID uuid) {
        return RedisManager.getRedissonClient().getFairLock("domiAccountLock:" + uuid);
    }

    public static void saveAccountToRedis(DomiAccount domiAccount) {
        // LogUtils.logToConsole(Level.INFO, "⌛ Saving " + domiAccount.getUsername() + "'s account (" + domiAccount.getUuid() + ") to Redis...");
        getRAccount(domiAccount.getUuid()).set(domiAccount);
        // LogUtils.logToConsole(Level.INFO, "✔ Saved !";
    }
```

Hope you will understand something to reproduce the issue. You mainly have to know that this listener calls a method sync _(on the main app thread from redis listener)_, in order to modify data async _(locks the account lock, reads accounts from redis / constructs object, modifies it, saves account back to redis and unlocks the lock)_.

Ty!

**Comment by mrniko** [comment]
I don't see any issue in code. Topic listeners are executed using separate executorService. What is the state of "redisson" threads? If they stuck listeners won't work.

**Comment by Aurelien30000** [comment]
I did some debug with jstack, threads seem fine (WAITING state), most other topics I use work, but some bucket listeners also _unregister_ themselves.
Don’t know if it’s relevant, but counting listeners of annoying topics using ˋˋRTopic#countListenersˋˋ returns 1 normally and 0 during _failure_. Do you think they got really unregistered or per-haps just stuck?

Ty again.

**Comment by mrniko** [comment]
I don't see in your logs any subscription. It's hard to say when listeners were unsubscribed.

**Comment by Aurelien30000** [comment]
Lot of other stuff here but the full process is described, from subscriptions, working listeners and failure.

Line 55+ => Subscription.
Line 476+ => Working listener, stuff with accounts as I mentioned before with locks and buckets.
Line 1652+ => Listener doesn't work any longer.

https://paste.domicraft.fr/joxazecoqu.json

_Note: Another independent listeners based on buckets does not work either when ``voteRewards`` topic "fails". ``domiServer:A_NAME:serverState``, ``domiServer:A_NAME:*PlayerCount`` Not sure but all object based listener seem broken._

Here is also a thread dump after failure: https://paste.domicraft.fr/emoriqifuv.pl

**Comment by mrniko** [comment]
You provided Redis logs. Can you send Redisson logs as well ?

**Comment by Aurelien30000** [comment]
For sure, here are logs https://paste.gg/p/anonymous/0e7064dea6e9419486cadc8f9c6f9aa1

Published around 124 times and only 68 seem logged in 🤔 

_Sorry for such long logs..._

**Comment by Aurelien30000** [comment]
This problem is in no way a priority, just for information, I found a solution by using Rsemaphores with only one _permission_. However I will do my best to try to help you find a potential problem with Rlocks 👍

**Comment by mrniko** [comment]
Which Redis vendor do you use?

**Comment by Aurelien30000** [comment]
I'm not sure I correctly understood what you're asking for but I use a "default" redis installation, this one especially: https://download.redis.io/releases/redis-6.2.5.tar.gz _built manually_.

**Comment by SplotyCode** [comment]
Might also be #3957
