### ISSUE TITLE
The return value of this method about setIfAbsent is null.

### ISSUE THREAD

**Issue by linglongchen** [redisson/redisson#3780]
The return value of this method about setIfAbsent is null when a key is exist. I think the return value should be false or zero.

`    public V getNow() {
        Object result = this.result;
        return !(result instanceof DefaultPromise.CauseHolder) && result != SUCCESS && result != UNCANCELLABLE ? result : null;
    }
`
![image](https://user-images.githubusercontent.com/31821538/129471250-c059cf77-8939-4395-9aea-211d9630a834.png)

**Comment by linglongchen** [comment]
the version is 3.11.2.
`        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.11.2</version>
        </dependency>`

**Comment by mrniko** [comment]
Which method exactly do you mean? Redisson API doesn't expose setIfAbsent

**Comment by linglongchen** [comment]
This method is `org.redisson.spring.data.connection.RedissonConnection#set(byte[], byte[], org.springframework.data.redis.core.types.Expiration, org.springframework.data.redis.connection.RedisStringCommands.SetOption)`
![image](https://user-images.githubusercontent.com/31821538/129516549-cfc3018f-a18f-44ef-8701-b0add8304b4a.png)
Thank you for your reply.

**Comment by linglongchen** [comment]
This method is `org.redisson.spring.data.connection.RedissonConnection#set(byte[], byte[], org.springframework.data.redis.core.types.Expiration, org.springframework.data.redis.connection.RedisStringCommands.SetOption)`
![image](https://user-images.githubusercontent.com/31821538/129516918-64d4d5aa-5ebb-4b26-a96d-0f5f32c2b281.png)


Thank you for your reply.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2811
