### ISSUE TITLE
`RedisNodeNotFoundException` still exists when redis cluster fail over

### ISSUE THREAD

**Issue by xrayw** [redisson/redisson#3781]
**Expected behavior**
Redisson can detect the cluster nodes change  correctly.

**Actual behavior**
<img width="1091" alt="WX20210813-131248@2x" src="https://user-images.githubusercontent.com/8683703/129670968-98bf2d98-b225-41a9-a172-248ee1eab42f.png">

**Steps to reproduce or test case**
When redis cluster fail over. 
And can not recover by itself. 

**Redis version**
3.2.0

**Redisson version**
3.16.0

**Redisson configuration**
```java

new Config().useClusterServers(xxx);
```

**Comment by mrniko** [comment]
Can you provide logs with debug logging level to check cluster status?

**Comment by UzimakiNaruto** [comment]
It is in our production environment, 
It's hard to reproduce .
We meet it sometimes 😱

**Comment by mrniko** [comment]
Please set `DEBUG` logging level for `org.redisson.cluster.ClusterConnectionManager` class in your production.

**Comment by mrniko** [comment]
Check your logs for presence of `java.lang.NullPointerException`

**Comment by UzimakiNaruto** [comment]
@mrniko hi, No NullPointerException found in log. 
I want to reproduce it, But it hard to do.

**Comment by b2k4j** [comment]
@mrniko I also have this problem.

**Comment by mrniko** [comment]
@b2k4j 

Can you set DEBUG logging level for org.redisson.cluster.ClusterConnectionManager class, reproduce issue and share output ?

**Comment by b2k4j** [comment]
@mrniko I can not reproduce this problem.But I have made memory dump, so I can provide you with it if you need.

**Comment by mrniko** [comment]
You need to upgrade to 3.20.1 or higher
