### ISSUE TITLE
Delay queue message loss

### ISSUE THREAD

**Issue by buhuigundeqiu** [redisson/redisson#3784]
@Slf4j
@Component
public class RedisDelayService {

    @Autowired
    private RedissonClient redissonClient;

    /**
     * 添加到消息队列
     * @param value 添加到队列的对象
     * @param delay 延迟时间
     * @param timeUnit 时间单位
     * @param queueName 队列名称
     * @param <T>
     */
    public <T> void addQueue(T value , long delay, TimeUnit timeUnit, String queueName){
        try {
            log.info("添加到延时队列【{}】【{}】【{}】",value,delay,queueName);
            RBlockingDeque<T> blockingDeque = redissonClient.getBlockingDeque(queueName);
            RDelayedQueue<T> delayedQueue = redissonClient.getDelayedQueue(blockingDeque);
            delayedQueue.offer(value,delay,timeUnit);
        } catch (Exception e) {
            log.error("添加到延时队列失败："+e.getMessage(),e);
            throw new RuntimeException("添加到延时队列失败");
        }
    }

    /**
     * 取值
     */
    public <T> T take(String queueName) throws InterruptedException {
        RBlockingDeque<T> blockingDeque = redissonClient.getBlockingDeque(queueName);
        RDelayedQueue<T> delayedQueue = redissonClient.getDelayedQueue(blockingDeque);
        return blockingDeque.take();
    }
}

@Component
@Slf4j
public class RedisDelayQueueRunner implements ApplicationRunner {

    @Autowired
    private RedissonClient redissonClient;
    @Autowired
    private RedisDelayService redisDelayService;

    @Override
    public void run(ApplicationArguments args) throws Exception {

        ScheduledThreadPoolExecutor scheduledThreadPoolExecutor = new ScheduledThreadPoolExecutor(1);

        scheduledThreadPoolExecutor
                .scheduleWithFixedDelay(
                        () -> {
                            log.info(Thread.currentThread().getName());
                            Employer callCdr = null;
                            try {
                                callCdr = redisDelayService.take("delay_queue");
                            }catch (InterruptedException e){
                                   log.info(e.getMessage());
                                   e.printStackTrace();
                            }
                            log.info("订单取消时间：" + new SimpleDateFormat("hh:mm:ss").format(new Date()) + "==订单生成时间" + callCdr.getPutTime());
                            },
                        1, 1, TimeUnit.SECONDS);

    }

}

**Comment by mrniko** [comment]
is there any code to reproduce the issue?

**Comment by buhuigundeqiu** [comment]
>

**Comment by buhuigundeqiu** [comment]
> is there any code to reproduce the issue?

>Hi, I'm pasting the code here

**Comment by mrniko** [comment]
which Redisson version do you use?

**Comment by buhuigundeqiu** [comment]
> which Redisson version do you use?

>3.13.6

**Comment by mrniko** [comment]
3.15.0 version contains fix for lost messages during blocking queue methods invocation. Please update to the latest version.
