### ISSUE TITLE
Post slave-recovery , GetType commands continue to being sent to master node instead of slave nodes 

### ISSUE THREAD

**Issue by JayTeli** [redisson/redisson#3788]
**Expected behavior**
Master redis node should never get GetType commands. 

**Actual behavior**
After unexpected traffic-load (spike) on redis, redisson starts sending gettype commands to master nodes instead of slave nodes.

**Steps to reproduce or test case**
On sudden spikes , this issue has been observed , its random in nature. Issue goes away after service restart.
(Also , happens very frequently.) 

**Redis version**
5.0.6

**Redisson version**
3.15.0

**Redisson configuration**
```
// Spring boot Java config :
Config config = new Config();
config.setCodec(StringCodec.INSTANCE)
	.useClusterServers()
	.setCheckSlotsCoverage(false)
	.setMasterConnectionPoolSize(64)
	.setMasterConnectionMinimumIdleSize(8)
	.setSlaveConnectionPoolSize(64)
	.setSlaveConnectionMinimumIdleSize(8)
	.setKeepAlive(true)
	.setTcpNoDelay(true)
	.setPingConnectionInterval(10000)
	.setScanInterval(2000)
	.setPassword(password)
	.setTimeout(1000)
	.addNodeAddress(hosts);
client = Redisson.create(config);
```

**Other Details**

- Both client service accessing the redis cluster and the redis cluster are in the same VPC

- Redis cluster : AWS Elastic Cache is used. Cluster is 3 shards with 6 nodes  with each shard containing one master and one replica node. Instance type of each node is r6g.2xlarge 

- Commands used :zadd and zrevRangeByScore only.

- Behaviour of nodes during the problem : 

Set type cmds
1:27 AM -> 0002-002 went out of comission
1:29 AM -> 0002-001 stopped taking incoming commands
1:30 AM -> 0002-001 stil not taking incoming commands
1:31 AM -> 0002-001 recovers
1:31 AM -> 0002-002 recovers
1:32 AM -> 0003-001 reduced number of requests
1:32 AM -> 0003-002 went out of comission
1:33 AM -> 0003-001 starts recovering
1:33 AM -> 0003-002 still out of comission
1:34 AM -> 0003-002 recovered
1:34 AM -> 0003-002 recovered

Get type cmds
1:27 AM -> 0002-002 - went out

1:28 AM -> 0002-002 - same
1:31 AM -> 0002-002 - recovered
1:32 AM -> 0003-002 - went out
1:33 AM -> 0003-002 - still out
1:33 AM -> 0002-001 - get commands started (master)
1:34 AM -> 0003-002 - recovered
1:35 AM -> 0003-001 - get commands started (master)

Since then we are seeing get cmds being run on 0002-001 & 0003-001 , which are master nodes.

- Once the slaves are recovered, instead of using slaves for zrevRangeByScore , we see calls at master for zrevRangeByScore commands. 

![1- isMaster - startOfIssue](https://user-images.githubusercontent.com/13567540/130221552-a16b8e5b-6193-4d45-ab64-ce01502e0a6f.png)
![2 - isMaster - afterRecovery](https://user-images.githubusercontent.com/13567540/130221575-4ccb51cb-76ab-4152-b546-de5cdceb6168.png)
![3 - isMaster - now](https://user-images.githubusercontent.com/13567540/130221596-ed258028-1368-423e-aab3-67d19288a37a.png)
![1 - GetTypeCommands - beforeIssueBegan](https://user-images.githubusercontent.com/13567540/130221615-2d3ee83c-58cc-4bed-b8cb-35864ebbbacb.png)
![2 - GetTypeCommands - IssueBegan](https://user-images.githubusercontent.com/13567540/130221639-2372c5eb-93f4-465c-a382-934a87a44d65.png)
![3 - GetTypeCommands - duringIssueOne](https://user-images.githubusercontent.com/13567540/130221662-91aaa352-3c1f-4905-867f-eb1ae5862543.png)
![4 - GetTypeCommands - duringIssueTwo](https://user-images.githubusercontent.com/13567540/130221669-b31a9893-5e9a-4dc9-a873-009a2ac79828.png)
![5 - GetTypeCommands - duringIssueThree](https://user-images.githubusercontent.com/13567540/130221688-d0299a45-f983-47f5-a50e-3634b050ad20.png)
![6 - GetTypeCommands - duringIssueFour](https://user-images.githubusercontent.com/13567540/130221700-e69396ff-7490-4dd0-8422-313e56aa8e55.png)
![7 - GetTypeCommands - afterRecovery](https://user-images.githubusercontent.com/13567540/130221715-b0ebd3ec-ff01-403e-aab7-c9ed3bdce3c2.png)
![8 - GetTypeCommands - now](https://user-images.githubusercontent.com/13567540/130221725-5202f7d5-927a-49ca-9e53-7dc469ee41d9.png)

**Comment by mrniko** [comment]
I need logs in `DEBUG` logging level

**Comment by JayTeli** [comment]
Hi , this is a production issue and enabling `debug`  level logs`will produce too much quantum of logs.
Also we are unable to reproduce this issue on stage/uat environment due to its random nature.

**Comment by mrniko** [comment]
Hi,

Can you enable debug logs for org.redisson.cluster.ClusterConnectionManager only?

**Comment by JayTeli** [comment]
Yes , in next build , we'll enable debug logs for above class and share.

**Comment by JayTeli** [comment]
We had enabled debug logs for the same in last week,  we'll share the debug logs as soon we encounter the issue again.

**Comment by sohin-keshwani** [comment]
We have made changes to config. Major ones, majorly setting tcpnodelay and keepalive to false. We haven't experienced this issue since then, but we are still keeping our eyes open in case if we encounter the issue again
