### ISSUE TITLE
Why Redission session manager stopped working after new virtual host in Tomcat

### ISSUE THREAD

**Issue by vijaykanta** [redisson/redisson#3790]
Hello, our redisson session manager 3.10.6 has stopped persisting session data. It stays as long as browser session is on, but won't work otherwise, means closing browser and opening.

We are using SHIRO for authentication and authorisation, and redisson usually works in background with session management. However, with a recently introduced virtual host in tomcat and few tweaks in server.xml and nginx (upstream) new server block, the persistence has gone.

On top of it, we are also using BigBlueButton web conference solution which also work with redid-server. It developed some problems of its own, now not storing sessions as well.

This started happening once we introduced new domain and virtual host to the web server.

Below are the technical details
tomcat/lib has redisson 3.10.6 tomcat-all and tomcat-7

tomcat/conf has redisson.conf file
_singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"_

Project maven pom.xml has redisson 3.10.6 dependency
_<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.10.6</version>
		</dependency>_

Shiro.ini has default web session manager set
_sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager_

We made all kinds of changes and combinations, but still cannot make redisson persist our session. Help!

**Comment by mrniko** [comment]
Sorry, I have never used SHIRO and can't help here.
