### ISSUE TITLE
为什么集群部署连接显示检测插槽未满

### ISSUE THREAD

**Issue by Li1274** [redisson/redisson#3791]
![image](https://user-images.githubusercontent.com/57244827/130308980-6f85851c-a260-4536-b693-641fe89cc9a8.png)

检查了redis配置插槽正常工作满足16384，端口也正常

**Comment by Li1274** [comment]
设置不检查插槽后 可以启动 不知道会不会影响分布式锁的使用呢

**Comment by xujinga** [comment]
你有机器ip是内网。把内网那台机器的ip改成外网ip就行了

**Comment by Li1274** [comment]
谢谢！
