### ISSUE TITLE
redisson currently does not fully support the redis lpush command

### ISSUE THREAD

**Issue by roverbeta** [redisson/redisson#3797]
**Currently, the "lpush" command of redis >= 2.4 supports multiple elements at a time, while the corresponding "RDeque.addFirst()" in redisson only supports one element.**
![image](https://user-images.githubusercontent.com/37068575/130920217-506a6568-ed9f-4bf6-aae1-740183aa88e2.png)
[https://redis.io/commands/lpush](url)

**Similar commands that are not fully supported include "rpush", "sadd", "srem".**

**Hope these features are supported, thanks**

**Comment by mrniko** [comment]
Done
