### ISSUE TITLE
Access Denied on Javadoc Search

### ISSUE THREAD

**Issue by asarkar** [redisson/redisson#3801]
1. https://javadoc.io/doc/org.redisson/redisson/latest/index.html.
2. In the search box on the right, type `redisson`.
3. In the  search suggestions, scroll down to the `Types` section (second from the top), and click on `org.redisson.Redisson`.
4. Stare at the error below and wonder why.
```
AccessDeniedAccess Denied1YBT0RFTFR6X25GVLkDrkQL3l4T52jteTAMOSTWvQLTmEgvpARsyLKeTFzJYDrS2/NpAodRRM4AxpfmjY0HDMuMN8n8=
```

**Comment by mrniko** [comment]
Seems search suggestions doesn't work properly. Try to hit enter and use search results page.
