### ISSUE TITLE
Redis Stream XTRIM with MINID strategy is not fully supported: incompatible parameter type

### ISSUE THREAD

**Issue by ivanopagano** [redisson/redisson#3803]
**Is your feature request related to a problem? Please describe.**
The API to trim a redis stream ([see the correspoding XTRIM command](https://redis.io/commands/xtrim)) supports different strategies via the [org.redisson.api.stream.TrimStrategy](https://javadoc.io/doc/org.redisson/redisson/latest/org/redisson/api/stream/TrimStrategy.html) type.
Yet the additional command parameters in the overloaded methods (e.g. trim, trimAsync, trimNonStrictAsync) will allow only `int`s.
Specifically you can now only pass a
* `int threshold` (to say how many messages you want to keep)
* `int limit` (to remove up to a given number of messages)

Those are inconsistent with the `TrimStrategy.MINID` which expects a message Id as input.

Since the message Ids are composed of a timestamp in millis from epoch and a number, the current `int` param won't be able to technically be used for such a job, even ignoring the semantics of the param.
An `int` is not enough to encode a valid millis timestamp which is part of the message Id.

**Describe the solution you'd like**
It would be nice to provide overloaded methods taking an instance of [org.redisson.api.StreamMessageId](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/api/StreamMessageId.java), and - most importantly- a simple `String`, to allow partial matches.

**Describe alternatives you've considered**
I will probably use a work-around by calling the low-level redis client, but the issue is mostly about the current API which is a bit misleading in what it provides.

**Comment by ivanopagano** [comment]
I'm locally testing my fix, but I can't seem to properly run the overall tests as per [instructions](https://github.com/redisson/redisson/blob/1801f6996b3d409db618f7b5ed43e106fc763d12/.github/CONTRIBUTING.md).

Essentially it looks like my mvn installation can't properly pick up the argLine property to feed to the tests, as the default redis binary path is not properly overridden.

This is the starting log when I try to run the mvn tests as per contribution's instructions

```log
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)                                                                                                                                                                                                                  
Maven home: /usr/local/Cellar/maven/3.8.2/libexec                                                                                                                                                                                                                              
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/ivanopagano/.sdkman/candidates/java/11.0.11.hs-adpt                                                                                                                                                               
Default locale: en_IT, platform encoding: UTF-8                                                                                                                                                                                                                                
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```

**Comment by mrniko** [comment]
Done. Thanks for report!
