### ISSUE TITLE
RRateLimiter drift

### ISSUE THREAD

**Issue by alim-akbashev** [redisson/redisson#3804]
Rate limit decreases over the time in highly concurrent environment.
Demo of such drift is on screenshot. Rate there has been limited by only RRateLimiter.
![image](https://user-images.githubusercontent.com/3984166/131498088-fdf162d5-642b-49f3-bc9e-71d795165839.png)

**Expected behavior**
Limit should not change without explicit call of setRate() with new value.

**Actual behavior**
Limit changes over hours. As a workaround I explicitly call setRate() with the same values time to time.

**Steps to reproduce or test case**
Just regular usage, nothing special:
```
    final long limitPerSecond = 115;
    final RRateLimiter limiter = redisson.getRateLimiter(name);
    limiter.setRate(RateType.OVERALL, limitPerSecond, 1000, RateIntervalUnit.MILLISECONDS);
    // ...
    limiter.acquire();
```

**Redis version**
6.0.5

**Redisson version**
3.16.1

**Redisson configuration**
```
    final Config config = new Config();
    config.useSingleServer().setAddress(url);
```

**Comment by mrniko** [comment]
Can you try version attached?

[redisson-3.16.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7083981/redisson-3.16.2-SNAPSHOT.jar.zip)

**Comment by alim-akbashev** [comment]
thank you for a quick response.

i've deployed service with version you've provided, collecting metrics now, will be back with feedback tomorrow

**Comment by alim-akbashev** [comment]
as I can see, the issue still there: 
![image](https://user-images.githubusercontent.com/3984166/131640366-873efdc3-d961-4d46-bbdb-c5a0c70eb678.png)


by checking values in redis, it seems that after some time a cardinality of sorted set `...:permits` stops matching the value `...:value`

**Comment by mrniko** [comment]
Did you make sure that all Redisson instances have synced clock?

**Comment by alim-akbashev** [comment]
not sure about nanoseconds precision, but i'm sure clocks are pretty in sync. all instances are running in the same k8s cluster (amazon eks), all k8s nodes are synced.
 
btw, not sure if it's important, my redis is a managed one - AWS ElastiCache running on m6g.large (64bit arm Graviton).

let me try to build more reproducible sandbox

**Comment by alim-akbashev** [comment]
it's more or less reproducible.
Please check the snippet https://gist.github.com/alim-akbashev/316f56197f099f323ff68cd27b51df78
It's more simple to reproduce dritft when numbers in config are big, like 30k requests per 30 seconds, but issue appears with lower values as well, it just require more time to drift.

just in case, my config i've used to run that snippet: just regular macbook pro (Intel), Redis 6.2.5 in docker, openjdk 16

p.s. while i've been typing this comment, limit has dropped down to 29494, so it takes minutes, not hours with such config

**Comment by mrniko** [comment]
Fixed! Thanks for report
