### ISSUE TITLE
CommandDecoder: Unable to decode data. channel command: (EXISTS) java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by pjcdarker** [redisson/redisson#3808]
`
 Unable to decode data. channel: [id: 0xf59ac8a2], reply: ReplayingDecoderByteBuf(ridx=71, widx=192), command: (EXISTS), params
: [sdk-1st-init:13763:637a436b28846efa]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:27)
	at org.redisson.client.protocol.convertor.BooleanAmountReplayConvertor.convert(BooleanAmountReplayConvertor.java:23)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:432)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:316)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:183)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:122)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
`

Redis version

4.0

Redisson version

3.16.1

codec
  JsonJacksonCodec

**Comment by mrniko** [comment]
Unable to reproduce. Can you share sample code?

**Comment by pjcdarker** [comment]
```
    public boolean isFirstInit(SdkConfigRequest request) {
        try {
            final RBucket<String> bucket = getBucket(request.getAppId(), request.getUid());
            if (bucket.isExists()) {
                return false;
            }

            long ttl = 1440L - LocalDateTime.now().get(ChronoField.MINUTE_OF_DAY);
            bucket.setAsync("1", Math.max(ttl, 1), TimeUnit.MINUTES);

            return true;
        } catch (Exception e) {
            e.printStackTrace();
        }

        return false;
    }

    private RBucket<String> getBucket(Long appId, String uid) {
        return redissonClient.getBucket("sdk-1st-init:" + appId + ":" + uid);
    }

```

It happens occasionally.

**Comment by mrniko** [comment]
Can you share Redisson config?

**Comment by mrniko** [comment]
Still unable to reproduce.

Please share logs in `TRACE` logging level for `org.redisson` package.

**Comment by mrniko** [comment]
test code:

```java
        ExecutorService e = Executors.newFixedThreadPool(10);
        for (int i = 0; i < 16; i++) {
            e.submit(() -> {
                for (int j = 0; j < 100000; j++) {
                    try {
                        RBucket<Object> bucket = redisson.getBucket(RandomString.make(10), new JsonJacksonCodec());
                        long ttl = 1440L - LocalDateTime.now().get(ChronoField.MINUTE_OF_DAY);
                        bucket.setAsync(RandomString.make(1000), Math.max(ttl, 1), TimeUnit.MINUTES);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
        }
        e.shutdown();
        assertThat(e.awaitTermination(100, TimeUnit.SECONDS)).isTrue();
```

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.16.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7144352/redisson-3.16.3-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Unfortunately, snapshot artifacts aren't available in maven. Can you name all Redisson objects you use?

**Comment by pjcdarker** [comment]
re-use version 3.16.1. 
Currently, this problem does not occur.:sweat:

**Comment by mrniko** [comment]
Please update to 3.16.3 version
