### ISSUE TITLE
why send may command when use mget command and all keys in same slot?

### ISSUE THREAD

**Issue by mikawudi** [redisson/redisson#3813]
when i use getBuckets().get("{test}abcd", "{test}bcdf", "{test}efgc");
i trace the code and find the 3 key use hash tags, so their have the same hash code(by connectionManager.calcSlot)
but in executeBatchedAsync, cretae 3 command (mget {test}abcd, mget {test}bcdf, mget {test}efgc ) and run in CommandBatchService

why? and i think send a command (mget {test}abcd, {test}bcdf, {test}efgc) is better than now?

**Comment by mrniko** [comment]
Done. Thanks for pointing out
