### ISSUE TITLE
RExecutorService sometime will stuck and does not resume task anymore

### ISSUE THREAD

**Issue by it-amosho** [redisson/redisson#3814]
I am tring to use RExecutorService in my project.

The test env connect to redis via VPN and the network is slow and unstable.

In my test. sometimes the RExecutorService will stuck and does NOT resume task anymore.

The RExecutorService is named : "redisson-web-online-test-DistSvc"

The RExecutorService will store request in : `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}`

and store task into `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:tasks`

I found the `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}` is empty but the task in `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:tasks` does not processed and remain in `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:tasks` 

relative data store in redis:
`{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:counter` : 1
`{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:retry-interval` : 60000
`{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:scheduler` : 
value=ff0013440745fec575af0b3bff9c3a9f71e3
score=1630914700110

`{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:tasks` :
key : 0013440745fec575af0b3bff9c3a9f71e3

attachement is the debug log for the test:

[java_api.txt](https://github.com/redisson/redisson/files/7114229/java_api.txt)

**Expected behavior**
Task submit into RExecutorService being executed.

**Actual behavior**

The RExecutorService being stick and task remain in `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:tasks` .

**Steps to reproduce or test case**
1. Start my application
2. after started , waiting for 5 minutes.
3. submit task into RExecutorService
4. the task does NOT executed and remain in `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:tasks`
5. `{redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}` is empty
6. value store in {redisson-web-online-test-DistSvc:org.redisson.executor.RemoteExecutorService}:counter is `1`

**Redis version**
5.0.6

**Redisson version**
3.16.1

**Redisson configuration**
        config.useSingleServer()
                .setConnectionMinimumIdleSize(1) //
                .setConnectionPoolSize(64) //
                .setTimeout(2 * 1000)
                .setConnectTimeout(2 * 1000)
                .setIdleConnectionTimeout(10 * 1000)
                .setKeepAlive(false)
                .setRetryAttempts(1)
                .setPingConnectionInterval(1 * 1000)

**Comment by it-amosho** [comment]
There are some strange messages in java_api.txt compare to normal log.

1. 2021-09-06 07:45:19,509 [redisson-3-1] acquired connection `0x016088f9` for command (EVAL)
2. 2021-09-06 07:45:19,543 [main] acquired connection `0x016088f9` for command (BLPOP)
3. 2021-09-06 07:45:19,607 [redisson-netty-2-2] receive reply: $-1 for command (EVAL) from  connection `0x016088f9`
4. 2021-09-06 07:45:19,609 [redisson-netty-2-2] connection `0x016088f9` released for command (EVAL) 
5. After released connection `0x016088f9`. we never reveice reply for BLPOP (step2)

**Comment by mrniko** [comment]
> Start my application

Can you share sample code to reproduce it?

**Comment by it-amosho** [comment]
The attachment is the sample code for the test.

But I can not reproduce the case in local Redis. I can only reproduce the case by connect to remote Redis via VPN.

And in my sample code , the case can only reproduce if  place `@Scope("singleton")` in Test2Controller

[sampleCode.tar.gz](https://github.com/redisson/redisson/files/7119008/sampleCode.tar.gz)

**Comment by mrniko** [comment]
If connection between VPN and Redis is broken then execution of BLPOP 0 command will hang forever. PING command can't be executed while BLPOP is executed.

**Comment by it-amosho** [comment]
So , if this is the reason cause the task sick in queue , may be redisson should NOT use `BLPOP 0` ?

Maybe redisson should use `BLPOP 1` and loop in java side to prevent network issue?

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.16.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/7119527/redisson-3.16.3-SNAPSHOT.jar.zip)

**Comment by it-amosho** [comment]
Sure , I will test 3.16.3 tomorrow, thx.

**Comment by it-amosho** [comment]
3.16.3 SNAPSHOT seems solve the case in my sample code, I will do more test for the issue , thx.

**Comment by mrniko** [comment]
Fixed
