### ISSUE TITLE
Curious to ask, why deprecate the json configuration ?

### ISSUE THREAD

**Issue by roverbeta** [redisson/redisson#3815]
When I used `org.redisson.config.Config#fromJSON(java.lang.String)` to generate Config, I found that this method has been deprecated.

When using `redisson-spring-boot-starter`, the value of `spring.redis.redisson.config` is String. I think json String is less prone to format errors than yaml String.

**Comment by mrniko** [comment]
to remove dependency from jackson json lib in future.
