### ISSUE TITLE
Question about use of Redisson againt Azure Cache for Redis

### ISSUE THREAD

**Issue by raksamit** [redisson/redisson#3825]
We use Azure Cache for Redis.

We configure Redisson as follows:

clusterServersConfig:
   nodeAddresses:
  - "rediss://ixcc-sbx-26-redis.redis.cache.windows.net:6380"
  
In our application log we see Redisson querying cluster nodes details and obtaining info about two specific instances (Master and Replica; ports 15000 and 15001)
  
02/09/2021 12:40:26.570 [main] INFO org.redisson.cluster.ClusterConnectionManager Redis cluster nodes configuration got from ixcc-sbx-26-redis.redis.cache.windows.net/10.226.20.4:6380:
128ecd2830f3ee29d7906c40dc839d15838907cd 10.226.20.4:15000 slave e314c539ea4647b84e1908362cc24e18f8674e57 0 1630586426346 7 connected
e314c539ea4647b84e1908362cc24e18f8674e57 10.226.20.4:15001 myself,master - 0 0 7 connected 0-16383

Based on Redisson logs it seems the library is connecting to specific instances, e.g.:

02/09/2021 12:40:27.174 [redisson-netty-2-7] DEBUG org.redisson.connection.ClientConnectionsEntry new connection created: RedisConnection@1173046334 [redisClient=[addr=rediss://10.226.20.4:15001], channel=[id: 0x87578bff, L:/10.226.9.69:48264 - R:10.226.20.4/10.226.20.4:15001], currentCommand=null]

We're observing issues when there's a scheduled maintenance on Redis instances (github issue 3739).

Microsoft support came back to us with following feedback: _your application is directly connecting to the port 15001 which means it is connecting to specific instance. Please note that it is not a good practice to connect to the specific instance as during patching, if it goes down for an update, you start seeing errors. I would suggest you to connect to Redis over port 6380._

Is it possible to make Redisson follow this recommendation i.e. always connect to port 6380 and not to specific instances?

**Comment by mrniko** [comment]
> Is it possible to make Redisson follow this recommendation i.e. always connect to port 6380 and not to specific instances?

Can you point on Azure documentation regarding this statement? Redisson uses ports provided by Azure and it's unable to "guess" any other port.

**Comment by raksamit** [comment]
Azure support came back to me with this:
_There is no such article to describe about the same, however we suggest it to make sure that you do not connect to an instance that is down for patching._ 
Regarding the same IP I believe this is Azure load balancer IP. Master and slaves are exposed by different ports (e.g. 15000 and 15001) but these are routed to private IPs. As a reference for this load balancer architecture please see this: https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-failover#a-quick-summary-of-cache-architecture

**Comment by mrniko** [comment]
> always connect to port 6380 and not to specific instances?

I think in this case you need to use single mode.
