### ISSUE TITLE
Question about ConnectionListener with AWS ElastiCache for Redis

### ISSUE THREAD

**Issue by nattobean** [redisson/redisson#3827]
Hello,

We have multiple instances of an application running in AWS ECS.

We periodically encounter a scenario where one (not all) container's RedissonClient with ConnectionListener receives onDisconnect calls from previously connected Redis hosts that never connects again. Other containers remain connected to the same hosts and are able to operate as expected.

Hoping for assistance to understand a way to avoid this scenario.

When we run against a docker cluster on our local computers, we are able to restart Redis instances at will and see disconnects and reconnects as we expect. Only in AWS do we find permanent disconnects. Eventually, our RedissonClient is disconnected from Redis completely and cannot make any progress on its work.

Thank you for any help.

Our RedissonClient is created more or less like so:

```
    val redissonConfig = new RedissonConfig
    val clusterConfig  = redissonConfig.useClusterServers

    clusterConfig
      .setConnectTimeout(...)
      .setTimeout(...)
      .setPingConnectionInterval(...)
      .setRetryAttempts(...)
      .setScanInterval(...)
      .setPassword(...)

    for (host <- hosts)
      clusterConfig.addNodeAddress(host)

    redissonConfig.setConnectionListener(new RedisConnectionListener(...))
    val client = Redisson.create(redissonConfig)
```

**Comment by mrniko** [comment]
Can you share logs with `TRACE` logging level for `org.redisson` package?

**Comment by nattobean** [comment]
The logs from my load test are pretty massive. Not sure what parts are most helpful. However, here is what I see just before all the onDisconnect calls:

`[redisson-netty-16-3] 22 Sep 2021 19:24:32,757-0400 DEBUG IdleConnectionWatcher  Connection [id: 0xb06737df, L:/172.17.0.2:58650 ! R:prom-cnrpoc-redlock-2-dev-0001-001.prom-cnrpoc-redlock-2-dev.kct6w1.use1.cache.amazonaws.com/10.147.161.116:5432] has been closed due to idle timeout. Not used for 11015 ms
`
But in AWS, I never see that host reconnect. BTW, that was a master node. What should trigger a reconnect? Is there a way to set the configuration so that connections to master nodes are always maintained?

One reason we are tracking connections with a ConnectionListener is to overcome performance degradation that we saw while doing failover testing. We are using RedissonRedLock (understanding it's deprecated), we are using the ConnectionListener to avoid asking RedLock to try to acquire a lock from a cluster we know is disconnected.

Ideally, we would not have to worry about any of this. But when we triggered a primary failover in AWS, as I mentioned, performance degraded and did not appear to recover.

**Comment by mrniko** [comment]
> What should trigger a reconnect? 

Reconnection is not triggered for closed idle connections.

> Is there a way to set the configuration so that connections to master nodes are always maintained?

You need to increase `masterConnectionMinimumIdleSize` setting.
