### ISSUE TITLE
Multiple connection pools created to failover slave while redis server rebooted

### ISSUE THREAD

**Issue by Azkaban153** [redisson/redisson#3832]
**Expected behavior**
When a master/slave fails over, the appropriate connection pool should only reconnect once and no. of connections on redis server should be 2X at max.

**Actual behavior**

Seeing multiple connection pools being initialised and repeatedly a pub sub connection being initialised, making failover redis node unresponsive due to connection exhaustion.

Logs from a single application server, **initialising slave pool 20 times, in less than 4 seconds**

`16-09-2021;13:16:27.222 [redisson-netty-18-7] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:27.403 [redisson-netty-18-21] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:27.443 [redisson-netty-15-19] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:27.852 [redisson-netty-18-15] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.104 [redisson-netty-18-25] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.342 [redisson-netty-18-1] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.343 [redisson-netty-15-16] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.431 [redisson-netty-15-28] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.476 [redisson-netty-15-1] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.577 [redisson-netty-15-29] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.781 [redisson-netty-15-25] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.970 [redisson-netty-18-31] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:28.993 [redisson-netty-15-19] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:29.158 [redisson-netty-18-9] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:29.181 [redisson-netty-15-29] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:29.601 [redisson-netty-15-25] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:29.803 [redisson-netty-15-18] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:29.825 [redisson-netty-18-32] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:29.998 [redisson-netty-18-17] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:30.154 [redisson-netty-15-11] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:30.197 [redisson-netty-15-4] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002
16-09-2021;13:16:30.266 [redisson-netty-18-28] INFO  o.r.c.pool.SlaveConnectionPool - 24 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:9002`

**Steps to reproduce or test case**

Not sure, as it was an unexpected outage of redis server. But you can try failing multiple redis nodes at once.

**Redis version**
6.2.1
**Redisson version**
3.16.1

**Redisson configuration**
config.useClusterServers();
for (String hostAndPort : hostAndPorts) {
LOGGER.info("Configuring RedissonUtil with Redis Server Response timeout : {}",timeout);
config.useClusterServers().addNodeAddress("redis://"+hostAndPort)
		.setTimeout(timeout)
		.setScanInterval(200)
		.setRetryInterval(100);
}

**Comment by mrniko** [comment]
Does this log contain records for the same Redis node?

**Comment by Azkaban153** [comment]
Yes. It's to the same redis node in the cluster.

**Comment by bhavikambani** [comment]
We are also facing same issue while any REDIS failover is happening.
REDIS Version # 6.2.1 & 3.2.6
Redisson version # redisson-3.16.1

**Comment by mrniko** [comment]
switch to 3.16.0 version

**Comment by Azkaban153** [comment]
If I may ask, what's causing this issue?

Can we rely on 3.16.0 to not cause this, as it's a production dependency.

**Comment by mrniko** [comment]
3.16.1 introduced a connection leak due to connection pool optimization.

**Comment by Azkaban153** [comment]
Sure. We'll downgrade in the meantime. Thanks for the update!

**Comment by mrniko** [comment]
fixed in 3.16.3
