### ISSUE TITLE
Pub Sub connections being initialised repeatedly after redis server VM became unresponsive

### ISSUE THREAD

**Issue by Azkaban153** [redisson/redisson#3833]
**Expected behavior**
If a redis server goes down, maximum of 2x connections should be seen on the failover node, with no change needed in pub sub connections.

**Actual behavior**
We are seeing much more connections than 2x (Reaching 50k connected clients in this case) and pub sub connections being initialised repeatedly to the nodes on the unreachable server.

**Does redisson require pub sub pool for any internal functions or can the pool size be set to 0, effectively disabling it?**

`16-09-2021;18:30:59.829 [redisson-netty-11-31] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:00.728 [redisson-netty-11-15] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:01.111 [redisson-netty-11-24] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:03.032 [redisson-netty-11-22] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:03.224 [redisson-netty-11-8] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:03.643 [redisson-netty-11-26] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:04.060 [redisson-netty-11-17] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:04.697 [redisson-netty-11-14] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:04.806 [redisson-netty-8-20] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:05.784 [redisson-netty-8-4] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:05.951 [redisson-netty-11-1] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:06.359 [redisson-netty-11-7] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:06.360 [redisson-netty-11-25] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:07.830 [redisson-netty-8-1] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:08.214 [redisson-netty-8-24] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:08.475 [redisson-netty-11-19] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:08.857 [redisson-netty-11-6] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:08.857 [redisson-netty-8-10] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:09.564 [redisson-netty-8-14] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:09.756 [redisson-netty-11-1] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:10.347 [redisson-netty-8-32] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:10.353 [redisson-netty-11-5] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:12.180 [redisson-netty-8-27] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:12.232 [redisson-netty-8-27] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:12.232 [redisson-netty-8-19] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:12.375 [redisson-netty-11-26] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:12.695 [redisson-netty-8-24] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:13.079 [redisson-netty-8-28] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:13.334 [redisson-netty-11-20] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:13.469 [redisson-netty-11-19] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:14.054 [redisson-netty-8-21] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:14.166 [redisson-netty-8-1] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:14.224 [redisson-netty-8-19] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:14.224 [redisson-netty-11-27] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:14.224 [redisson-netty-11-9] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:14.586 [redisson-netty-8-9] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:15.007 [redisson-netty-8-17] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:15.869 [redisson-netty-11-22] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:16.679 [redisson-netty-8-3] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:17.052 [redisson-netty-11-12] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:17.886 [redisson-netty-11-20] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:18.767 [redisson-netty-8-5] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:19.353 [redisson-netty-8-18] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:19.383 [redisson-netty-11-16] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:19.616 [redisson-netty-11-25] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:19.740 [redisson-netty-11-26] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:19.745 [redisson-netty-11-28] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:19.838 [redisson-netty-11-8] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:20.262 [redisson-netty-8-14] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:20.825 [redisson-netty-11-13] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:20.883 [redisson-netty-11-27] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:20.903 [redisson-netty-11-30] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:21.208 [redisson-netty-8-4] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:21.722 [redisson-netty-11-20] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:21.727 [redisson-netty-11-28] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:22.803 [redisson-netty-11-16] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:23.195 [redisson-netty-11-31] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:23.512 [redisson-netty-11-4] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:23.592 [redisson-netty-8-31] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:25.181 [redisson-netty-8-13] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:25.289 [redisson-netty-8-26] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:25.628 [redisson-netty-11-17] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:25.705 [redisson-netty-8-24] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:26.137 [redisson-netty-8-7] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:26.358 [redisson-netty-8-8] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:27.288 [redisson-netty-8-16] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:28.224 [redisson-netty-8-11] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:29.504 [redisson-netty-11-12] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
16-09-2021;18:31:29.701 [redisson-netty-11-6] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7003
16-09-2021;18:31:29.745 [redisson-netty-11-11] INFO  o.r.c.pool.PubSubConnectionPool - 1 connections initialized for IP_OF_REDIS_SERVER/IP_OF_REDIS_SERVER:7001
`

**Steps to reproduce or test case**
1 VM was running 3/18 cluster nodes in the redis cluster.  It became unresponsive and we saw a surge in connections to that VM after that.

**Redis version**
3.2.6

**Redisson version**
3.16.1

**Redisson configuration**
config.useClusterServers();
for (String hostAndPort : hostAndPorts) {
LOGGER.info("Configuring RedissonUtil with Redis Server Response timeout : {}",timeout);
config.useClusterServers().addNodeAddress("redis://"+hostAndPort)
.setTimeout(timeout)
.setScanInterval(200)
.setRetryInterval(100);
}

**Comment by mrniko** [comment]
switch to 3.16.0 version

**Comment by mrniko** [comment]
fixed in 3.16.3
