### ISSUE TITLE
Inconsistent Performance Retrieving Data From Redis with Redisson

### ISSUE THREAD

**Issue by packley1** [redisson/redisson#3834]
We have Redis setup in as a Master with 2 Slaves.  Generally it works well.  Occasionally when we pull a large cached object from Redis, the time to pull the data from the cache is 50-60 seconds.  The good times we have seen are 3-6 seconds to pull the same data.  Is their anything we can do to make it more consistent (obviously we want it to be in the 3-6 seconds range).  The data is stored in an RList.  This particular case the data is very large, 16-17MB.  This is an unusual case, but we need to be faster nonetheless.

I have run the latency checks on the server, no issues there.

I will add that we are constantly adding new items to the cache.  These items expire after 60 minutes (ttl).  The cache typically has about 1600 items in it at any given time (during peak usage hours).  Redis is running inside a Kubernetes environment, as is the client application (same K8S environment).  Memory usage for the 3 Redis instances is hovering around 70-80MB we have allocated 2G for each (max).

Is there anything you can think of that would cause a request for cached item to suddenly take 50-60 seconds?

**Comment by mrniko** [comment]
try to set retryInterval to 7 seconds
