### ISSUE TITLE
spring boot 2.4.10 with redisson 3.16.2 : zadd command will throw stackoverFlow error

### ISSUE THREAD

**Issue by cdk8s-zelda** [redisson/redisson#3836]
## Spring Boot 2.4.10

![image](https://user-images.githubusercontent.com/51701412/133771229-175514fb-0a13-49ea-9677-2d4c6a583199.png)

```
@Slf4j
@SpringBootTest
class Demo1ApplicationTests {
	@Autowired
	private RedisTemplate redisTemplate;

	@Test
	void testString() {
		redisTemplate.opsForValue().set("keyString", "222");
	}

	@Test
	void testZSet() {
		redisTemplate.opsForZSet().add("keyZSet", "11", 1.0D);
	}


}
```

- This is simple demo.
- string is ok.

-------------------------------------------------------------------

## Spring Boot 2.5.4

![image](https://user-images.githubusercontent.com/51701412/133773576-e2e43ce4-91b7-4dc5-b86a-eae91555c3bd.png)

- This is ok

**Comment by cdk8s-zelda** [comment]
Spring Boot 2.4.x only support redisson 3.15.x

**Comment by mrniko** [comment]
fixed in https://github.com/redisson/redisson/issues/3623
