### ISSUE TITLE
How does spring boot1.5x upgrade the redisson version from 3.8.x to 3.11.x?

### ISSUE THREAD

**Issue by pengfeng01** [redisson/redisson#3838]
![image](https://user-images.githubusercontent.com/66997341/133916042-0c80af05-04ea-4fba-bd57-f18eefd26d95.png)

From the dependency of redisson 3.11.3 version, we can see that the spring boot used is 2x, and now our project uses spring boot 1.5.9, how should I upgrade to redisson 3.11.3 version? The following is a screenshot of the error report

![image](https://user-images.githubusercontent.com/66997341/133916087-15d8e153-c956-4ea6-a616-3c24e0e0f025.png)

![image](https://user-images.githubusercontent.com/66997341/133916095-fa5007c2-d381-4326-86ac-169c576056c2.png)

The reason for the upgrade is to fix the bugs of versions before 3.9.1
#1811

**Comment by mrniko** [comment]
You need to exclude redisson-spring-data dependency and define redisson-spring-data-18 for spring boot 1.5.x
