### ISSUE TITLE
Stream - DS

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3839]
Let's imagine a stream created like this.

`RStreamReactive<String, PaymentEvent> stream = redissonReactiveClient.getStream("payment-stream", new TypedJsonJacksonCodec(String.class, PaymentEvent.class));`

  I thought I should be able to add a list of payment events into the stream. But looks like I need to always convert it into a map to add it to the stream.

```
  StreamAddArgs.entry()
  StreamAddArgs.entries(....)
```

  My point is - each stream entry is for 1 event. Not for collection of events.
  I have to add it like this.

```
  for(paymentevent : events){
  	StreamAddArgs.entry("unnessaryKey", paymentevent);
  	.....
  }
```
If we see, the key is basically unnecessary here.

 Can you please explain the reason behind the such data structure? Is it because redis's limitation? Or do we have any other better use case?

**Comment by mrniko** [comment]
> Can you please explain the reason behind the such data structure? Is it because redis's limitation? 

This structure used by Redis

**Comment by kitkars** [comment]
Ok Thanks @mrniko
