### ISSUE TITLE
RMapCache.fastRemove throws RedisException: too many results to unpack

### ISSUE THREAD

**Issue by sumanentc** [redisson/redisson#3841]
Redisson Version : 3.16.1
Redis : 6.0.5

Getting the below error when trying to remove cache entries in bulk(more than 10000) in Redis. 

 org.redisson.client.RedisException: ERR Error running script (call to f_9b685e1701377cfef2bd44d1c23770aaa4143fbf): @user_script:1: user_script:1: too many results to unpack . channel: [id: 0x6145c965, L:/100.72.9.98:39942 - R:ampm-redis-cluster-0001-002.ampm-redis-cluster.a8y5su.use1.cache.amazonaws.com/100.72.14.183:6379] command: (EVAL), params: [local maxSize = tonumber(redis.call('hget', KEYS[6], 'max-size')); if maxSize ~= nil and maxSize ~= ..., 6, INST_CACHE, redisson__timeout__set:

**Comment by mrniko** [comment]
Fixed! Thanks for report
