### ISSUE TITLE
How can I execute BGREWRITEAOF command from RedissonClient?

### ISSUE THREAD

**Issue by xinzheyang** [redisson/redisson#3842]
Does Redisson expose an interface to execute any Redis command? Thanks.

**Comment by mrniko** [comment]
Yes.

Here it is https://github.com/redisson/redisson/wiki/10.-additional-features#107-low-level-redis-client

**Comment by xinzheyang** [comment]
Thank you! Just to clarify, this will have to be a separate Redis client connection from the RedissonClient? i.e. can't re-use the underlying RedisClient from RedissonClient ?

**Comment by mrniko** [comment]
It creates a separate Redis client connection.
