### ISSUE TITLE
 keys.getKeysByPattern cost too much time

### ISSUE THREAD

**Issue by wyg0405** [redisson/redisson#3844]
RKeys keys = redissonClient.getKeys();
		Iterable<String> keysByPattern = keys.getKeysByPattern("district:city:name:*" + name + "*");
		List<Object> objects = new ArrayList<>();
		keysByPattern.forEach(key->{
			RBucket<Object> bucket = redissonClient.getBucket(key);
			Object o = bucket.get();
			if (o!=null){
				objects.add(o);
			}
		});

why this code cost 42047ms,but only 6000+ keys in my redis,redisson ver 3.16.1

**Comment by mrniko** [comment]
search keys by pattern is always time consuming operation.
