### ISSUE TITLE
Master slave mode vs Replicated mode

### ISSUE THREAD

**Issue by akshagr** [redisson/redisson#3849]
@mrniko 
How is master slave mode different from replicated mode, after keep aside AWS EC support ?
Is it possible to do sharding using redisson across multiple standalone servers (non clustered) ?

**Comment by mrniko** [comment]
Replicated mode uses INFO REPLICATION command to detect current node role and thus failover.

Master slave mode unable to detect failover (master replacement with slave).

> Is it possible to do sharding using redisson across multiple standalone servers (non clustered) ?

Yes it's possible with ShardedRedisson instance
https://github.com/redisson/redisson/wiki/5.-data-partitioning-(sharding)#2-partitioning-sharding-of-redis-setup

**Comment by akshagr** [comment]
Thanks @mrniko for prompt reply !! I have some more questions.

In case of failover(master replacement with slave) do we have to restart application for connection re-establishment or it will done automatically in some interval (which we will provide) ? Failover support.

Can we provide only reader and primary endpoint for connection using redisson client ?

**Comment by mrniko** [comment]
> In case of failover(master replacement with slave) do we have to restart application for connection re-establishment or it will done automatically in some interval (which we will provide) ? Failover support.

Failover handling is done automatically.

> Can we provide only reader and primary endpoint for connection using redisson client ?

You can specify one master and one slave for master/slave and replicated modes.

**Comment by akshagr** [comment]
@mrniko 
This ShardedRedisson [client side sharding] is available only in Redisson PRO ? 
Isn't there anything else for client side sharding for non clustered servers ?

**Comment by mrniko** [comment]
@akshagr I'm afraid no.
