### ISSUE TITLE
How does PING influences the BATCH command?

### ISSUE THREAD

**Issue by mircea-pop** [redisson/redisson#3860]
I'm doing a batch command in the following way:

```
...
  final RBatch rBatch = redissonClient.createBatch();
        for (final String key : keys) {
            rBatch.getMap(key, StringCodec.INSTANCE).getAsync(fieldName);
        }
  final List<?> responses = rBatch.execute().getResponses();
 ...
```
From time to time we get the following Timeout exception:
```
org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (20 ms) occured after 0 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: null, params: null
```

I'm wondering about the *Try to define pingConnectionInterval setting.* in the WARN message. We use the default setting for PING (the 30s interval). What is the meaning of that sentence in the message? Is the PING necessary? Could we disable the PING?  How does the PING influences the batch command? Any suggestions how this WARN can be avoided?

Redis: 5.0.5
Redisson: 3.16.3

**Comment by mrniko** [comment]
I think in your case it's just a network delay due to response size.

**Comment by mircea-pop** [comment]
so the message in this case is not specific, but rather a "catch all" approach.
Thanks!

**Comment by mircea-pop** [comment]
would it be OK to completely disable the PING? is there some documentation on how the PING influences the connection pool?

**Comment by mrniko** [comment]
yes, you can disable PING. It's recommended only if your Redis setup is behind of proxy and it doesn't propagate connection interruptions.

**Comment by mircea-pop** [comment]
thank you!
