### ISSUE TITLE
Quarkus extension seems to only use config from build time

### ISSUE THREAD

**Issue by luke-gee** [redisson/redisson#3861]
Weve had to revert to using reddison and creating the client ourselves as it seems only config used at build time is injected into the client, which is then causing issues for the native build. Looking [here](https://github.com/redisson/redisson/blob/4bc53fd54d3838f89e2949a2c96ea6a8d930b6e6/redisson-quarkus/redisson-quarkus-20/deployment/src/main/java/io/quarkus/redisson/client/deployment/QuarkusRedissonClientProcessor.java#L89) it seems this may be the case. Is this to be expected, or am i missing something here. we need this to read from an external yaml file thats managed in kubernetes.

**Comment by luke-gee** [comment]
@mrniko request that this one be re opened. Just getting around to looking at re using this lib and although it now supports external file, it seems to me the config is still baked in at build time. We need to support building the same artifact and deploying it in may places with different config.

**Comment by mrniko** [comment]
@luke-gee 

It's loaded during runtime since it marked with @Record(ExecutionTime.RUNTIME_INIT)

**Comment by mrniko** [comment]
I did some changes. Can you try build from master?

**Comment by mrniko** [comment]
Done
