### ISSUE TITLE
redisson-spring-boot-starter has compile time dependency on test artifacts (junit and assertj)

### ISSUE THREAD

**Issue by BigMichi1** [redisson/redisson#3863]
**Expected behavior**
adding `redisson-spring-boot-starter` as a dependency should not pull in junit and assertj as compile-time dependencies. these artefacts should not be deployed to a productive environment

currently pom.xml defines this:

```xml
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
```

**Actual behavior**
`pom.xml` should define this:

```xml
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
```

**Steps to reproduce or test case**
1. create a spring-boot project
2. add `redisson-spring-boot-starter` as a dependency
3. build war file
4. war file includes junit and assertj

**Redis version**
6.0.3

**Redisson version**
3.16.3

**Redisson configuration**
`unconfigured`

**Comment by mrniko** [comment]
Fixed! Thanks for report.
