### ISSUE TITLE
Exception on heavy load in springboot

### ISSUE THREAD

**Issue by kanteshkm** [redisson/redisson#3868]
we are using springboot-starter redisson client on cloud foundry and using AWS Redis cluster, 99% operations are read only, i am using RMapCache<String, String>  and I am using default config, not changed threads/nettry threads etc.

 During load testing (max 200 requests per second), getting below different exception intermittently (DNS , out of memory, readtimout) and once we get these exception , they are not recovered.

Could please let me know how we can fine tune the configs to support heavy reads?.

**DNS Logs:**
_java.net.UnknownHostException: failed to resolve 'clustercfg.rg-guid.iroxbd.dc.cache.amazonaws.com'
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/169.22.0.3:98] failed to send a query via UDP (no stack trace available)_

**Read timeout Logs:**
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 57. 

 ERROR [redisson-netty-2-20] - [org.redisson.client.handler.ErrorsLoggingHandler] [] - Exception occured. Channel: [id: 0xf41c0518, L:/10.129.202 ! R:rg-c-0001-001.rg-cbc.cache.amazonaws.com/:1473]
java.lang.OutOfMemoryError: Direct buffer memory
at java.base/java.nio.Bits.reserveMemory(Unknown Source)
at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)

**Comment by mrniko** [comment]
which netty version do you use?
