### ISSUE TITLE
Reddison 3.16.3 is using netty-common 4.1.68.Final and netty-handler 4.1.68.Final but when I upgrade latest version of reddison is still using netty 4.1.66 version

### ISSUE THREAD

**Issue by constantinirimia** [redisson/redisson#3873]
Hi Everyone!

I am using in my pom.xml the latest version of ```reddison - 3.16.3``` which is supposed to use the latest versions of ```netty-handler``` and ```netty-codec```, but when I run ```mvn dependency:tree -Dincludes=io.netty:netty-codec``` and ```mvn dependency:tree -Dincludes=io.netty:netty-handler``` I see it is using ```4.1.66 version``` instead of ```4.1.68 version```.

Can we take a look at this please?

Thank you.

**Comment by tntstn** [comment]
Hello, I have the same issue for 3.16.4. I am using gradle and I updated my redissson version from 3.10.4 to 3.16.4 to solve a CVE. But when I checked the dependencies I realised that some how I do not know why, the versions were downgraded from 4.1.68 to 4.1.65 for netty-transport (it comes with redisson).

Could you take a look, please?

Thank you.

Here is the output;

+--- org.redisson:redisson:3.16.4
|    +--- io.netty:netty-common:4.1.68.Final -> 4.1.65.Final
|    +--- io.netty:netty-codec:4.1.68.Final -> 4.1.65.Final
|    |    +--- io.netty:netty-common:4.1.65.Final
|    |    +--- io.netty:netty-buffer:4.1.65.Final
|    |    |    \--- io.netty:netty-common:4.1.65.Final
|    |    \--- io.netty:netty-transport:4.1.65.Final
|    |         +--- io.netty:netty-common:4.1.65.Final
|    |         +--- io.netty:netty-buffer:4.1.65.Final (*)
|    |         \--- io.netty:netty-resolver:4.1.65.Final
|    |              \--- io.netty:netty-common:4.1.65.Final
|    +--- io.netty:netty-buffer:4.1.68.Final -> 4.1.65.Final (*)
|    +--- **io.netty:netty-transport:4.1.68.Final -> 4.1.65.Final (*)**
|    +--- io.netty:netty-resolver:4.1.68.Final -> 4.1.65.Final (*)
|    +--- io.netty:netty-resolver-dns:4.1.68.Final -> 4.1.65.Final
|    |    +--- io.netty:netty-common:4.1.65.Final
|    |    +--- io.netty:netty-buffer:4.1.65.Final (*)
|    |    +--- io.netty:netty-resolver:4.1.65.Final (*)
|    |    +--- io.netty:netty-transport:4.1.65.Final (*)
|    |    +--- io.netty:netty-codec:4.1.65.Final (*)
|    |    +--- io.netty:netty-codec-dns:4.1.65.Final
|    |    |    +--- io.netty:netty-common:4.1.65.Final
|    |    |    +--- io.netty:netty-buffer:4.1.65.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.65.Final (*)
|    |    |    \--- io.netty:netty-codec:4.1.65.Final (*)
|    |    \--- io.netty:netty-handler:4.1.65.Final
|    |         +--- io.netty:netty-common:4.1.65.Final
|    |         +--- io.netty:netty-resolver:4.1.65.Final (*)
|    |         +--- io.netty:netty-buffer:4.1.65.Final (*)
|    |         +--- io.netty:netty-transport:4.1.65.Final (*)
|    |         \--- io.netty:netty-codec:4.1.65.Final (*)
|    +--- io.netty:netty-handler:4.1.68.Final -> 4.1.65.Final (*)

**Comment by tntstn** [comment]
@constantinirimia I have faced same problem, did you solve it and how?

**Comment by philbrock** [comment]
> @constantinirimia I have faced same problem, did you solve it and how?

Are you using Spring Boot at all? Spring Boot uses Maven's "dependency management" to define the versions of a whole lot of different dependencies via the `spring-boot-dependencies` POM, linked to by the `spring-boot-start-parent` POM, including the Netty libs. If you're finding expected versions of things are being replaced with older versions, *and* you're using Spring Boot, it's almost certainly why.
