### ISSUE TITLE
Low ScanInterval burns CPU  

### ISSUE THREAD

**Issue by DanilaVaratyntsev** [redisson/redisson#3886]
Hello.
We tried to scale cluster under the load, but we got a lot of `Node hasn't been discovered yet` exceptions. To prevent them we changed `scanInterval` to 25ms. It helped, but according to JFR 30+% of CPU is burned to refresh cluster state:
![image](https://user-images.githubusercontent.com/23168642/137093385-8620f007-d5f1-42bd-b447-ed4236500056.png)
![image](https://user-images.githubusercontent.com/23168642/137092186-f2bf0d76-73aa-42ad-9efc-ee3dbacf5561.png)
![image](https://user-images.githubusercontent.com/23168642/137093330-d6d22894-7554-4d67-927f-e4f73bbc5da0.png)

For me it seems that `ClusterConnectionManager.checkMasterNodesChange` has a O(n^2) complexity and can be simplified to O(n) using map instead of inner loop.

Are there any recommendations what values should `scanInterval` have? And how can we update it on the fly to scale cluster?

**Comment by mrniko** [comment]
ElastiCache failover in some rare cases may take up to 5 hours.
