### ISSUE TITLE
Unreleased Resources

### ISSUE THREAD

**Issue by hehaoNo1** [redisson/redisson#3889]
RedissonRegionFactory   125line   classLoader.getResourceAsStream(filename)

**Comment by SplotyCode** [comment]
Are you sure? The scanner is closed https://github.com/redisson/redisson/blob/6bb333299610ff1ef173cc18f584ab799e9eaa14/redisson/src/main/java/org/redisson/config/ConfigSupport.java#L92 witch should close the InputStreamReader from here https://github.com/redisson/redisson/blob/6bb333299610ff1ef173cc18f584ab799e9eaa14/redisson/src/main/java/org/redisson/config/ConfigSupport.java#L174 witch should then close the input stream right?
