### ISSUE TITLE
Redis keep the keys even if they are expired

### ISSUE THREAD

**Issue by mmorel-35** [redisson/redisson#3890]
Hi !

I'm using Redisson 3.16.1 with a RMapCache with a MaxIdleTime, a TTL and a MaxSize in LRU mode

The key of the cached value in the map contains a date so it won't be called the next day.

I was expecting for those keys to disapear after the TTL has expired but it doesn't seems to work this way. I can reduce the number of keys per cache but that's quite weird

My understanding is that the framework wait for the key to be called to clean up.

Notice that I have activated  :
useScriptCache: true
cleanUpKeysAmount: 1000

Thank you for your help

**Comment by mrniko** [comment]
You can speedup cleanup process with https://github.com/redisson/redisson/wiki/2.-Configuration#mincleanupdelay and https://github.com/redisson/redisson/wiki/2.-Configuration#maxcleanupdelay settings

**Comment by mrniko** [comment]
Can you provide test code to reproduce it?

**Comment by mmorel-35** [comment]
How can I help you reproduce this? I have used the springcachemanager with complete cacheconfig, some composite encoders and codecs (composition of snappy and msgpack).
The key are maps (before encoding) and the value are complexe pojos.
