### ISSUE TITLE
Is RBatch a single get/put call to Redis server using MGET/MSET functionality

### ISSUE THREAD

**Issue by mevemula** [redisson/redisson#3892]
RBuckets uses MSET/MGET functionality but RBuckets.set() doesn't have an option to set TTL for entries.

From documentation of RBatch, it was mentioned: RBatch requests are batched to separate queue and could be executed later with execute(). Does this mean each request in batch gets executed at once or is MSET/MGET functionality used to execute all requests of batch at once?

@mrniko Can you please confirm if results of batch.execute() is in order and if value is not present in cache for get request, does it return null?

**Comment by mrniko** [comment]
`MSET` command doesn't allow to define TTL.

RBatch is executed only if execute() method invoked. MSET/MGET functionality is used only if RBuckets methods were invoked.
