### ISSUE TITLE
BloomFilter false judgment does not meet expectations

### ISSUE THREAD

**Issue by szz0104** [redisson/redisson#3898]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version 4.0.13**

**Redisson version 3.16.0**

**Redisson configuration**

`RBloomFilter<String> bloomFilter = redisson.getBloomFilter("sample");
        bloomFilter.tryInit(55000000L, 0.5);
        // return true，why?
        boolean containsA = bloomFilter.contains("a");
        // add two element
        bloomFilter.add("a");
        bloomFilter.add("b");
        // return true
        boolean containsC = bloomFilter.contains("c");
        for (int i = 1000; i < 1999; i++) {
            bloomFilter.add(String.valueOf(i));
        }
        int falseCount = 0;
        for (int i = 0; i < 1000; i++) {
            // always return true
            if (!bloomFilter.contains(String.valueOf(i))) {
                falseCount++;
            }
        }
        // falseCount = 0
        System.out.println(falseCount);`

**Comment by szz0104** [comment]
When the misjudgment rate is small, it is judged as normal, such as 0.03

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5129
