### ISSUE TITLE
RRateLimit 限流器使用到的Lua脚本在阿里云集群版Redis无法执行有没有解决方案？

### ISSUE THREAD

**Issue by dwkfxj** [redisson/redisson#3900]
执行tryAcquire方法时报错：
org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression
阿里云Redis集群版相关限制参考：https://help.aliyun.com/document_detail/145968.htm?spm=a2c4g.11186623.0.0.4000355bX1WVOf#title-sx3-bjk-1sf
请问有没有其他解决方案？

**Comment by mrniko** [comment]
It's a vendor specific issue. Redis doesn't have such limitation.
