### ISSUE TITLE
Is it possible to have batch/bulk getWithTTLOnly and getWithTTLOnlyAsync methods in RMapCache?

### ISSUE THREAD

**Issue by calvincodes** [redisson/redisson#3907]
Hi! We are using `RMapCache` object to store key-value pair with TTL per key in an AWS ElactiCache cluster mode enabled setup. In this setup, we have multiple shards and at least one replica per shard and we want the application reads to strictly be from the replica nodes for performance reasons. We were earlier using `RMapCache.getAllAsync` method and realized that, as explained in https://github.com/redisson/redisson/issues/2165, this method will always read from the primary node. Upon further reading, we came across https://github.com/redisson/redisson/issues/2981, which mentions the `RMapCache.getWithTTLOnly` method that can serve the reads from replica nodes.

In our use case, we will be reading multiple keys from the RMapCache all at once. In the case when the values for these keys are not present in `RMapCache` object, we will be making one network call for each missing key to Redis. Hence we wanted to understand if it would be possible to have bulk/batch variants of these methods, similar to other `getAll` and `getAllAsync`?

Happy to share more details.

**Comment by mrniko** [comment]
Done
