### ISSUE TITLE
How do sentinel round reconnect to when all are down ?

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#3920]
Hello, when redisson work in scheme 1 master and 2 slave with sentinel daemon on each, then 2 slave go down, some time master go down too, and then one or two of slaves go up, but redisson try connect to master only sentinel/redis node.
Question: How to do round-reconnect to sentinels servers if no one server not avialable ?

**Comment by mrniko** [comment]
Redisson will continue to connect to sentinels which were returned in the last result of SENTINEL SENTINELS command.
