### ISSUE TITLE
Redisson client should be created even without all connections being initialized

### ISSUE THREAD

**Issue by mircea-pop** [redisson/redisson#3928]
The problem we are facing now with Redisson is that we create the Redisson client at the application start-up and quite often we get an error like the following:
```
Unable to init enough connections amount! Only 49 of 50 were initialized.
```

or for a different use case:
```
Unable to init enough connections amount! Only 1 of 2 were initialized.
```
This leads to the client not being created.
We don't want to retry synchronously because it would slow down the application start-up which in turn would slow down the AutoScalingGroup outscaling.

We would like to get an instance of the Redisson client even if none of the connections are initialized. There should be some async retry mechanism for re-establishing the connections.

We currently use a Dummy client as a fallback (when the Redis is not critical)) or manage the client creation async retry by ourselves, but we need to replicate this retry mechanism for each Redisson client (we have different use cases with different Redis clusters).
Would be very useful to have such a functionality built-in. We used to have Aerospike before Redis and Aerospike had such a functionality (you were able to set [this](https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/policy/ClientPolicy.java#L206) property to false)

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4902
