### ISSUE TITLE
FstCodec

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#3931]
String deserialization with high concurrency "{}"  or Object reference  "[com.game.logical.global.bean.DropRateData@2ab839d5]"

**Comment by mrniko** [comment]
FstCodec is deprecated. Please use MarshallingCodec instead.

**Comment by wl980868110** [comment]
MarshallingCodec is three times larger than FstCodec serialization

**Comment by mrniko** [comment]
As alternative you can use Kryo5Codec. You can also try to use compression codec like SnappyCodecV2 or LZ4Codec.

**Comment by tanglz** [comment]
Can we use Kryo5Codec to read old data which use FstCodec?

**Comment by mrniko** [comment]
You need to extend Kryo5Codec class
