### ISSUE TITLE
Problems founded with jcache license file

### ISSUE THREAD

**Issue by KononenkoKonstantin** [redisson/redisson#3933]
Hi!
In your application you use jcache 1.0.0 version. This version has not correct license file. This page https://github.com/jsr107/jsr107spec/commits/master/LICENSE.txt shows that license was change on Oct 11, 2015 and than was corrected from **JSR-000107 JCACHE 2.9 Public Review - Updated Specification** to **Apache License, Version 2.0** on Oct 14, 2016.
Release jcache 1.0.0 was on 18 March 2014. LICENSE file version was: https://github.com/jsr107/jsr107spec/blob/v1.0.0/LICENSE.txt
This causes some problems with other users using your application. Using jcache 1.1.0 version or higher will help to resolve this problem.

**Comment by mrniko** [comment]
In cache-api-1.0.0.jar reference to the license is in META-INF\MANIFEST.MF file.

`Bundle-License: https://raw.github.com/jsr107/jsr107spec/master/LICENSE.txt`

current content of this file is Apache License, Version 2.0

**Comment by KononenkoKonstantin** [comment]
I know that, and our OSS department writes:  "The license of a released third party artifact remains constant, even if there is a later release which re-licenses it to a different license."

**Comment by mrniko** [comment]
I have updated the lib.

**Comment by KononenkoKonstantin** [comment]
Thank you
