### ISSUE TITLE
Leak of connection leads to redisson unable to perform action correctly

### ISSUE THREAD

**Issue by axelczk** [redisson/redisson#3934]
**Expected behavior**
The connection pool remain stable and keep the number of opened connection to the minimum.

**Actual behavior**
Connection pool is full of blocked connection and redisson can't open another connection to perform any request. 

**Steps to reproduce or test case**
We have not idea what was the cause of this. The only thing we know is: 
- We have one service that use redisson and on both instance of this service the number of opened connection has increased since 10 days without any connection being freed. When we restarted the two instances of the service, the number of open connections on our redis dropped by 80. On the JVM side, there is no thread stuck during this period. 

![image](https://user-images.githubusercontent.com/62662702/140339371-1f9a0bea-3aa1-4b94-b6f4-7a544fe20f7a.png)

We are using redisson for distributed task using the RScheduledExecutorService. It's possible to have task that are cancelled during execution. 

**Redis version**
5.0.6

**Redisson version**
3.15.6

**Redisson configuration**
Replicated server with a node config containing one worker group of 5 with 8 redis thread, 16 netty thread and a the default MasterPubSub connection pool (24min, 64 max)

Here is some log about the problem after the connection pool is full of blocked connection:

```
Oct 30, 2021 @ 03:07:01.382 | ERROR | redisson-timer-4-1 | Can't process the remote service request with id 018e66f563eb11b7a9bbc0c6cab625427c | 
Oct 30, 2021 @ 03:06:48.782 | ERROR | redisson-timer-4-1 | Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3bb0d6ab(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (EVAL), params: [local expiredTaskIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); local ..., 4, {timerExecutor:org.redisson.executor.RemoteExecutorService}, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler-channel, {timerExecutor:org.redisson.executor.RemoteExecutorService}:retry-interval, 1635556002381, 50] after 0 retry attempts | 
Oct 30, 2021 @ 03:06:37.282 | ERROR | redisson-timer-4-1 | Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f42e81b(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (EVAL), params: [local expiredTaskIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); local ..., 4, {timerExecutor:org.redisson.executor.RemoteExecutorService}, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler-channel, {timerExecutor:org.redisson.executor.RemoteExecutorService}:retry-interval, 1635555990882, 50] after 0 retry attempts | 
Oct 30, 2021 @ 03:06:24.382 | ERROR | redisson-timer-4-1 | Can't send response: RemoteServiceResponse [result=null, error=org.redisson.client.RedisTimeoutException: Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4e06c5e7(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (EVAL), params: [local scheduled = redis.call('zscore', KEYS[5], ARGV[3]);if scheduled == false then redis.call('hdel..., 6, {timerExecutor:org.redisson.executor.RemoteExecutorService}:counter, {timerExecutor:org.redisson.executor.RemoteExecutorService}:status, {timerExecutor:org.redisson.executor.RemoteExecutorService}:termination-topic, {timerExecutor:org.redisson.executor.RemoteExecutorService}:tasks, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler, {timerExecutor:org.redisson.executor.RemoteExecutorService}:retry-interval, 1, 2, ...] after 0 retry attempts] for request: RemoteServiceRequest [requestId=0142cded9f752cac200a1f5479f3bc7518, methodName=scheduleCallable, signature=[3143983607692024834, -697753227114447020], args=[org.redisson.executor.params.ScheduledParameters@5e6a753c], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=3600000], date=1635555941133] |
Oct 30, 2021 @ 03:06:18.030 | ERROR | redisson-3-3 | Can't execute: RemoteServiceRequest [requestId=0142cded9f752cac200a1f5479f3bc7518, methodName=scheduleCallable, signature=[3143983607692024834, -697753227114447020], args=[org.redisson.executor.params.ScheduledParameters@5e6a753c], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=3600000], date=1635555941133] |
Oct 30, 2021 @ 03:06:11.583 | ERROR | redisson-3-3 | [org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:187), io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669), io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744), io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base/java.lang.Thread.run(Thread.java:830)]
```

**Comment by mrniko** [comment]
Do you have a memory dump? Can you check for any failover case before this issue arise?

**Comment by axelczk** [comment]
Since the service was restarted, we don't have any dump sorry. Before this, we haven't any failover case visible in our logs.

**Comment by mrniko** [comment]
yes, here it is fx1x2sq@btcmod.com

**Comment by axelczk** [comment]
Sent it this morning. Tell me if you didn't receive it or if you have any information to help us.

**Comment by mrniko** [comment]
In your dump I see only 66 RedisConnections

**Comment by axelczk** [comment]
The dump was taken during this peek:
![image](https://user-images.githubusercontent.com/62662702/142834368-830010b2-54c7-4bdf-b535-1226072e5488.png)

Indeed there is less connection than last time because we restarted the service before reaching the connection pool maximum limit. The service is configured to have something like 48 connection on idle. And most of the time it does not need more. 

But there is an edge case that can occurs and this happen, I think Redisson is not able to free the connection or the execution thread and so on. 

We have enabled the redisson debug logs maybe we can give you extra info if you tell us what we need to find ?

**Comment by mrniko** [comment]
Do you see any output from ConnectionWatchdog class in your logs?

**Comment by axelczk** [comment]
No not at all.

**Comment by mrniko** [comment]
do you execute tasks on the same JVM which scheduled it?

**Comment by axelczk** [comment]
Yes it's highly possible

**Comment by axelczk** [comment]
After some research, all the lost connexion are related to BLPOP command executed during the execution of a task.

**Comment by mrniko** [comment]
blocking queue is used per executorService instance which is registered for tasks execution.

**Comment by axelczk** [comment]
Here is the config we used: 
`      Config config = new Config();
        config.useReplicatedServers().addNodeAddress(props.getHost().toArray(new String[0]));
        config.setThreads(8);
        config.setNettyThreads(16);

        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setBeanFactory(factory);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap("name", 5));

        RedissonClient redissonClient = Redisson.create(config);
        RedissonNode node = RedissonNode.create(nodeConfig, redissonClient);
        node.start();
`

On our logs, there is 31 BLPOP command with unreleased connection all related to one of the 8 threads named redisson-X-X.

**Comment by mrniko** [comment]
Unable to reproduce it.

> On our logs, there is 31 BLPOP command with unreleased connection all related to one of the 8 threads named redisson-X-X.

Can you share these logs?

**Comment by nladuguie** [comment]
Hello, could you please reopen this ticket as we observe exactly the same behavior as described: one service using queue on Redisson is leaking connections all related to BLPOP commands.
Moreover, we observe that the connections are often released right after the BLPOP command timeout is over, but sometimes the connection is released several minutes after this BLPOP timeout.


> **Expected behavior** The connection pool remain stable and keep the number of opened connection to the minimum.
> 
> **Actual behavior** Connection pool is full of blocked connection and redisson can't open another connection to perform any request.
> 
> **Steps to reproduce or test case** We have not idea what was the cause of this. The only thing we know is:
> 
> * We have one service that use redisson and on both instance of this service the number of opened connection has increased since 10 days without any connection being freed. When we restarted the two instances of the service, the number of open connections on our redis dropped by 80. On the JVM side, there is no thread stuck during this period.
> 
> ![image](https://user-images.githubusercontent.com/62662702/140339371-1f9a0bea-3aa1-4b94-b6f4-7a544fe20f7a.png)
> 
> We are using redisson for distributed task using the RScheduledExecutorService. It's possible to have task that are cancelled during execution.
> 
> **Redis version** 5.0.6
> 
> **Redisson version** 3.15.6
> 
> **Redisson configuration** Replicated server with a node config containing one worker group of 5 with 8 redis thread, 16 netty thread and a the default MasterPubSub connection pool (24min, 64 max)
> 
> Here is some log about the problem after the connection pool is full of blocked connection:
> 
> ```
> Oct 30, 2021 @ 03:07:01.382 | ERROR | redisson-timer-4-1 | Can't process the remote service request with id 018e66f563eb11b7a9bbc0c6cab625427c | 
> Oct 30, 2021 @ 03:06:48.782 | ERROR | redisson-timer-4-1 | Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3bb0d6ab(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (EVAL), params: [local expiredTaskIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); local ..., 4, {timerExecutor:org.redisson.executor.RemoteExecutorService}, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler-channel, {timerExecutor:org.redisson.executor.RemoteExecutorService}:retry-interval, 1635556002381, 50] after 0 retry attempts | 
> Oct 30, 2021 @ 03:06:37.282 | ERROR | redisson-timer-4-1 | Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@3f42e81b(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (EVAL), params: [local expiredTaskIds = redis.call('zrangebyscore', KEYS[2], 0, ARGV[1], 'limit', 0, ARGV[2]); local ..., 4, {timerExecutor:org.redisson.executor.RemoteExecutorService}, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler-channel, {timerExecutor:org.redisson.executor.RemoteExecutorService}:retry-interval, 1635555990882, 50] after 0 retry attempts | 
> Oct 30, 2021 @ 03:06:24.382 | ERROR | redisson-timer-4-1 | Can't send response: RemoteServiceResponse [result=null, error=org.redisson.client.RedisTimeoutException: Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4e06c5e7(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], command: (EVAL), params: [local scheduled = redis.call('zscore', KEYS[5], ARGV[3]);if scheduled == false then redis.call('hdel..., 6, {timerExecutor:org.redisson.executor.RemoteExecutorService}:counter, {timerExecutor:org.redisson.executor.RemoteExecutorService}:status, {timerExecutor:org.redisson.executor.RemoteExecutorService}:termination-topic, {timerExecutor:org.redisson.executor.RemoteExecutorService}:tasks, {timerExecutor:org.redisson.executor.RemoteExecutorService}:scheduler, {timerExecutor:org.redisson.executor.RemoteExecutorService}:retry-interval, 1, 2, ...] after 0 retry attempts] for request: RemoteServiceRequest [requestId=0142cded9f752cac200a1f5479f3bc7518, methodName=scheduleCallable, signature=[3143983607692024834, -697753227114447020], args=[org.redisson.executor.params.ScheduledParameters@5e6a753c], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=3600000], date=1635555941133] |
> Oct 30, 2021 @ 03:06:18.030 | ERROR | redisson-3-3 | Can't execute: RemoteServiceRequest [requestId=0142cded9f752cac200a1f5479f3bc7518, methodName=scheduleCallable, signature=[3143983607692024834, -697753227114447020], args=[org.redisson.executor.params.ScheduledParameters@5e6a753c], options=RemoteInvocationOptions[ackTimeoutInMillis=null, executionTimeoutInMillis=3600000], date=1635555941133] |
> Oct 30, 2021 @ 03:06:11.583 | ERROR | redisson-3-3 | [org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:187), io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669), io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744), io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base/java.lang.Thread.run(Thread.java:830)]
> ```

Did you find any way to fix that, or is there still this connection leak in your service?

**Comment by axelczk** [comment]
We were able to mitigate the problem changing the idleConnectionTimeout to 1000 ms. 

I think the problem behind this it that some command doesn't use already opened connection and try to open another one instead. These connection then stay idle and are used by ping command so the pool never decrease. 

With this parameter setted to 1000 ms, connection are released faster and the pool is never full.

**Comment by mrniko** [comment]
@nladuguie 

Can you reproduce it with sample code?

**Comment by mrniko** [comment]
@nladuguie 

Please share your Redisson config

**Comment by mrniko** [comment]
Can you try version attached?

[redisson-3.17.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8798375/redisson-3.17.4-SNAPSHOT.jar.zip)

**Comment by nladuguie** [comment]
@mrniko unfortunately, we are not able to run our service correctly with this JAR embedded.
Issues like `java.lang.NoClassDefFoundError: org/redisson/misc/RPromise` are happening.
Can you try to built this JAR another way ?

**Comment by mrniko** [comment]
@nladuguie 

RPromise and RedissonPromise internal classes were removed.

**Comment by mrniko** [comment]
Sorry, I meant 3.17.3 version

**Comment by nladuguie** [comment]
@mrniko thank you, the jar worked fine even with 3.17.2, but issue is still there unfortunately.
One more thing to note is that connections leaking often concern blpop command with remote_execution params.
Can we know what means this remote_execution exactly?
Is this related to Redisson internal behavior?

**Comment by nladuguie** [comment]
Ok understood.
So our use case is more related to a TransferQueue more than the BlockingQueue we are also using. 
Because I guess this remote_response comes from the TransferQueue implementation for signaling to the producer that the consumer effectively consumed the element from the queue.
Will test your version, thank you.

**Comment by nladuguie** [comment]
@mrniko good news, with this latest version you provided me this morning, it seems to fix the issue.
I will run more tests today, but we are on the right track.
Thank you for your help.
Do you plan to deliver that fix in 3.17.4 ? And if so, what is the targeted release date ?

**Comment by mrniko** [comment]
@nladuguie 

I replaced blpop with forever waiting interval to 60 seconds. Here is the commit https://github.com/redisson/redisson/commit/ab9e6dc7a74ea2bf139ef18ace245917301233da

**Comment by mrniko** [comment]
during this month
