### ISSUE TITLE
Redis Sentinel doesn't add resurrected master back into node cluster  unless one of the sentinel is restarted externally in Redisson setup

### ISSUE THREAD

**Issue by varunbh79** [redisson/redisson#3937]
Explored and Tried lot of ways to automate redis sentinel process of auto discovering failed/resurrected master node in Master Slave Setup.  Tried this setup in containerized environment, unless I manually restart one of the sentinels the old master node will be discovered by the sentinels and would be converted as slave in the new master.

Need immediate help for this issue

Sample Snippet of Redisson Sentinel Setup

  @Bean
    @Qualifier("redissonSentinelClient")
    public RedissonClient redissonSentinelClient() {
        Config config = new Config();
        List<String> sentinelAddresses = List.of(redisUrl+"redis-sentinel-1:26380",redisUrl+"redis-sentinel-2:26380",
                redisUrl+"redis-sentinel-3:26380");
        config.setCodec(new JsonJacksonCodec());
        config.useSentinelServers()
              .setMasterName(master)
              .setSentinelAddresses(sentinelAddresses);
        this.redissonClient = Redisson.create(config);
        return redissonClient;
    }

sample docker compose file for sentinel setup 

  redis-sentinel-1:
    image: redis
    container_name: redis-sentinel-1
    command: >
      bash -c "echo 'port 26380' > sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      echo 'sentinel monitor mymaster master 6378 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 300' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 200' >> sentinel.conf &&
      echo 'protected-mode no' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    #ports:
    #  - 26380:26380
    depends_on:
      - master
      - slave-a
      - slave-b

Please let me know what I'm missing in the setup and provide workaround at the earliest 

Thanks
Varun

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/3938
