### ISSUE TITLE
Issue with adding resurrected master as slave after master is restarted back from failover

### ISSUE THREAD

**Issue by varunbh79** [redisson/redisson#3938]
**Expected behavior**
Redis Sentinel should auto reconfigure the resurrected master from failover and be placed as slave under new master. This setup is working only when I manually restart one of the sentinel node

**Actual behavior**
Resurrected master from failover is not added back into master slave setup and becomes an independent node unless one of the sentinel node is restarted and old master becomes a slave to the new master

**Steps to reproduce or test case**

1.  Setup a RedissonClient with Sentinel setup 
      @Bean
    @Qualifier("redissonSentinelClient")
    public RedissonClient redissonSentinelClient() {
        Config config = new Config();
        List<String> sentinelAddresses = List.of(redisUrl+"redis-sentinel-1:26380",redisUrl+"redis-sentinel-2:26380",
                redisUrl+"redis-sentinel-3:26380");
        config.setCodec(new JsonJacksonCodec());
        config.useSentinelServers()
              .setMasterName(master)
              .setSentinelAddresses(sentinelAddresses);
        System.out.println("The Sentinel Address are : " + config.useSentinelServers().getSentinelAddresses());
        System.out.println("The Sentinel Master name is : " + config.useSentinelServers().getMasterName());
        this.redissonClient = Redisson.create(config);
        return redissonClient;
    }
2.  Add Redis-sentinel as service in docker compose file 
     redis-sentinel-1:
    image: redis
    container_name: redis-sentinel-1
    command: >
      bash -c "echo 'port 26380' > sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      echo 'sentinel monitor mymaster master 6378 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 300' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 200' >> sentinel.conf &&
      echo 'protected-mode no' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    #ports:
    #  - 26380:26380
    depends_on:
      - master
      - slave-a
      - slave-b

**Redis version**
   6.2.6

**Redisson version**
    3.16.4

**Redisson configuration**

   @Bean
    @Qualifier("redissonSentinelClient")
    public RedissonClient redissonSentinelClient() {
        Config config = new Config();
        List<String> sentinelAddresses = List.of(redisUrl+"redis-sentinel-1:26380",redisUrl+"redis-sentinel-2:26380",
                redisUrl+"redis-sentinel-3:26380");
        config.setCodec(new JsonJacksonCodec());
        config.useSentinelServers()
              .setMasterName(master)
              .setSentinelAddresses(sentinelAddresses);
        System.out.println("The Sentinel Address are : " + config.useSentinelServers().getSentinelAddresses());
        System.out.println("The Sentinel Master name is : " + config.useSentinelServers().getMasterName());
        this.redissonClient = Redisson.create(config);
        return redissonClient;
    }

 @Bean
    public RMapCache<Long, Employee> employeeRMapCache() {
        MapOptions<Long,Employee> options =  MapOptions.<Long,Employee>defaults().loader(mapLoader());
        final RMapCache<Long, Employee> EmployeeRMapCache = redissonSentinelClient().getMapCache(CACHE_NAME,options);
        return EmployeeRMapCache;
    }

**Comment by mrniko** [comment]
> Redis Sentinel should auto reconfigure the resurrected master from failover and be placed as slave under new master.

Sentinel should be properly configured. If Sentinel doesn't report master node then Redisson can't do anything.

**Comment by varunbh79** [comment]
Hi thanks for responding. Please can you help me out with proper sentinel configuration so I could test this out and close the issue. Thanks

**Comment by varunbh79** [comment]
> > Redis Sentinel should auto reconfigure the resurrected master from failover and be placed as slave under new master.
> 
> Sentinel should be properly configured. If Sentinel doesn't report master node then Redisson can't do anything.

Can you help me out with redis sentinel configuration I'm unable to find proper resource to fix this issue

**Comment by mrniko** [comment]
Here is the doc https://redis.io/topics/sentinel#quick-start
