### ISSUE TITLE
Significant performance drop and loss of scalability after Redisson client upgrade

### ISSUE THREAD

**Issue by nel10000** [redisson/redisson#3939]
Hello,
There is a significant performance drop and loss of scalability after upgrading Redisson client from 2.2.12 to 3.10.6.
The performance (throughput - number of requests per second) dropped by almost 40% and the scalability of the Spring-boot app using it was lost, meaning that adding more instances of the Spring-boot app doesn't increase the system's throughput.
### Some technical details:
Redis 3.0.7 64 bit in cluster mode - 3 masters and 3 slaves.
Spring-boot 1.4.1.RELEASE (12 instances, one on its own machine)
Please find attached redisson.json file [redisson-3.10.6.json.txt](https://github.com/redisson/redisson/files/7494883/redisson-3.10.6.json.txt)
The reason why the client was originally upgraded was because of the following error that appeared in the log:

> ERROR - An error occurred when opening a session. Error: Can't aquire connection to /10.110.195.54:7000 org.redisson.client.RedisConnectionException: Can't aquire connection to /10.110.195.54:7000
                at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:180)

With the previous client version the performance was excellent and the solution was scalable.
Please advise.
Regards,
Nethanel

**Comment by mrniko** [comment]
Did you try to check it with a profiler?

**Comment by nel10000** [comment]
Yes. A significant amount of the CPU time is spent in redisson. 
The only difference between the two versions of the spring-boot app is the redisson client.
Is there some kind of configuration in redisson.json that should be done?
It seems there is some kind of bottleneck across the whole system.

**Comment by mrniko** [comment]
Can you record a session with https://jdk.java.net/jmc/8 and share it?

**Comment by nel10000** [comment]
I'll try to do it at my earliest and let you know.
In the meanwhile, is there any configuration modification that can be done in order to improve the performance?

**Comment by mrniko** [comment]
Did you try to reduce pool size to 100?

**Comment by nel10000** [comment]
The performance issue was solved by reverting back to Redisson 2.2.12.
Due to time constraints with the customer, the alternative paths could not be investigated.
Thanks for your help.
