### ISSUE TITLE
redisson-quarkus-20 can't get config from envirement variable

### ISSUE THREAD

**Issue by naah69** [redisson/redisson#3943]
can't get  envirement variable config,@BuildStep is Before it
![5b18a6fd696e68f303968f19ab93ceb](https://user-images.githubusercontent.com/25682169/141300439-8a86b5ba-18ea-45d7-beb3-3d83fd555361.png)
![image](https://user-images.githubusercontent.com/25682169/141300503-4eb9a6e0-35b9-42f5-920d-bd68f0160e73.png)

**Comment by mrniko** [comment]
which Config source object is used in this case?

**Comment by mrniko** [comment]
can you share full source code to reproduce it?

**Comment by naah69** [comment]
it is dynamic config in extension-deployment test.
the reason i think is get config in build time.it runs before application start.
can u move it to runtime

**Comment by naah69** [comment]
the error will occur while use dynamic config center ,command line parameter and envirement variable too.

**Comment by naah69** [comment]
> `QuarkusRedissonClientProcessor.build()` method is already marked with `@Record(ExecutionTime.RUNTIME_INIT)`

yes，it is @Record,it run in buildtime.it is before static code block

**Comment by naah69** [comment]
yes,but it run before static code block

**Comment by mrniko** [comment]
Fixed
