### ISSUE TITLE
ttl key with no expire time , return 0

### ISSUE THREAD

**Issue by zhongyuanyidiankeng** [redisson/redisson#3944]
when i  use stringRedisTemplate.getExpire(key, TimeUnit) to judge key is not set expire time, i expect -1, but it return 0.however i user spring-boot-starter-data-redis, it return -1 with expect. here is the environment: 

the redis i use is sentinel , and redisson version is 3.16.1 or 3.11.1, springboot version 2.1.6.RELEASE

here is the test case and result:

![image](https://user-images.githubusercontent.com/18180357/141399289-d0b0eb4c-2723-4cb8-896f-f0e887db9f67.png)

**Comment by SplotyCode** [comment]
This is expected with spring -1 = key exists but there is no ttl.
This is different then https://redis.io/commands/TTL. If the key would no exists at all your mono would be empty.
Look at https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/ReactiveRedisTemplate.html#getExpire-K-

**Comment by SplotyCode** [comment]
This is expected with spring 0 = key exists but there is no ttl.
This is different then https://redis.io/commands/TTL. If the key would no exists at all your mono would be empty.
Look at https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/ReactiveRedisTemplate.html#getExpire-K-

**Comment by zhongyuanyidiankeng** [comment]
@SplotyCode thanks, i just found redission is Based on high-performance async and lock-free Java Redis client and Netty framework.
