### ISSUE TITLE
Redisson Client AWS Elastic Cache Configuration Best Practice

### ISSUE THREAD

**Issue by harshitshah4** [redisson/redisson#3947]
I want to configure Redisson Client to connect it to AWS ElasticCache. There is not much documentation that what's the best practice to do so.

AWS ElasticCache provides Primary Endpoint and Reader Endpoint for writes and reads respectively.
Now instead of mentioning each nodes endpoint I would prefer to use Primary Endpoint and Reader Endpoint. 
But from what I saw in multiple github issues in this repo, it was advises to use node endpoints directly. Why was that ? Reader Endpoint helps me to add more servers to Redis without changing the code base. Will Redisson pick up more servers automatically ? 

Thanks

**Comment by mrniko** [comment]
starting from 3.16.2 version hostnames are also supported in replication mode. I would recommend update to the latest version. It allows you to define Primary Endpoint and Reader Endpoint and scan them for changes.

**Comment by yotov** [comment]
And what are the recommended settings for DNSMonitor when the Reader endpoint is used? By default, the interval is set to 5 seconds and there are many logs for Detected DNS change between reader nodes. Is it a good practice to disable DNSMonitor for the reader endpoint?

**Comment by mrniko** [comment]
dnsMonitor isn't used, since domains are resolved during nodes scan. You can change scan interval using `scanInterval` setting.

> By default, the interval is set to 5 seconds and there are many logs for Detected DNS change between reader nodes

as far as I know AWS Reader Endpoint returns only single node. Which hosting do you use?

**Comment by yotov** [comment]
I use AWS and it returns a single node, but according to documentation:
> A reader endpoint is not a load balancer. It is a DNS record that will resolve to an IP address of one of the replica nodes in a round robin fashion.

And I see too often a log this log:
```
org.redisson.connection.DNSMonitor       : Detected DNS change. Master redis://***.0001.euc1.cache.amazonaws.com:6379 has changed ip from 10.0.xxx.xxx to 10.0.yyy.yyy
```
which makes me things that using a DNS monitor is not useful for the reader endpoint

**Comment by mrniko** [comment]
I agree, but in case of slave failure you won't detect it and Redisson will continue to reconnect to it. Or for example if slave node failed due to network problem with master. It's still reachable but disconnected from the master node. Hostname resolver should be checked in any case. I don't know why did AWS Team decided to implement Reader Endpoint in such way.

**Comment by harshitshah4** [comment]
This is problematic even in cases of Redis Sentinel deployment, when running in Kubernetes some instances/pods can go down and gets replaced with some other instances, whose ip may differ but they still are pointed by the same host name.

So to solve this, Redisson should stop reconnecting the same ip in cases when hostnames provided by developer resolve to different ip address.

**Comment by mrniko** [comment]
> Redisson should stop reconnecting the same ip in cases when hostnames provided by developer resolve to different ip address

It works since 3.16.2 version

**Comment by yotov** [comment]
> I agree, but in case of slave failure you won't detect it and Redisson will continue to reconnect to it. 

Are you sure about this one? I read the docs of Elasticache Replication Endpoints again https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Endpoints.html, and my understandings are that we can choose between primary, reader endpoint, and node endpoints. In the case when I decide to use node endpoint, I think that you are right. But when I choose the reader endpoint and a failure occurs, I expect that AWS DNS will resolve to a different node and reconnect to it.

**Comment by mrniko** [comment]
> Are you sure about this one? 

I meant this example: if slave node failed due to network problem with master

**Comment by mrniko** [comment]
As better alternative I recommend to define all Redis hosts.
