### ISSUE TITLE
UnsatisfiedDependencyException ProxyCachingConfiguration NoSuchFieldError cacheManager

### ISSUE THREAD

**Issue by billwenboli** [redisson/redisson#3949]
Hi,

I tried integrating redisson into our springboot project, but got the following error upon adding the dependency:

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheConfig': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalJCacheAdvisor' defined in class path resource [org/springframework/cache/jcache/config/ProxyJCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.interceptor.BeanFactoryJCacheOperationSourceAdvisor]: Factory method 'cacheAdvisor' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheOperationSource' defined in class path resource [org/springframework/cache/jcache/config/ProxyJCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.jcache.interceptor.JCacheOperationSource]: Factory method 'cacheOperationSource' threw exception; nested exception is java.lang.NoSuchFieldError: cacheManager`

Here are all the Redis-related dependencies we have:

implementation "redis.clients:jedis:3.6.1"
implementation "org.springframework.boot:spring-boot-starter-data-redis:2.5.2"
implementation "org.redisson:redisson:3.16.4"

Before adding redisson dependency, there was no error. I was wondering if there is any conflict between these dependencies or their versions? Thanks.

**Comment by mrniko** [comment]
> Factory method 'cacheOperationSource' threw exception; nested exception is java.lang.NoSuchFieldError: cacheManager

This usually caused by different versions of spring modules in classpath. They should have the same version.
