### ISSUE TITLE
Distributed iterator

### ISSUE THREAD

**Issue by Vorotyntsev** [redisson/redisson#3953]
Hello.
We have a huge sorted set (1m+ elements), that should be processed in parallel by different application instances. We came up to the idea to have a LUA script that will call a `ZSCAN` command using a saved cursor to return each element to app only once. Due to single-threaded nature of Redis engine, it would make a iterator, shared across all clients. 
I didn't find anything like it in Redisson. If you think that this feature would be useful, I can prepare a PR in a week. If not - sorry for disturbance

**Comment by mrniko** [comment]
Hi,

It would be great if you share a PR for this feature.

**Comment by mrniko** [comment]
Done
