### ISSUE TITLE
Connection configuration for a replicaset behind anycasted address: 

### ISSUE THREAD

**Issue by alexanderad** [redisson/redisson#3955]
Hi!

First of all, thanks for an amazing library! 🌟 

I'm looking for advice here on the client configuration for the following setup:

Redis 4 instance consists of:
* 1 master
* 2 slaves
* sentinels

All servers are, so to say, ephemeral, and hence in front of the instances, there is `haproxy` server + `bird2` that together achieve anycast advertisement of a fixed IP address and proxy traffic to the _current master_. Users are instructed to connect to master only and given the DNS entry for the anycast IP. Slaves are not in use and are only there to pick up the role of master in the event of the failover. Setup is similar to what is described in [haproxy blog](https://www.haproxy.com/blog/haproxy-advanced-redis-health-check/).

As a result, for Redission client I have only a single `host:ip` endpoint to use in configuration. I tried configuring Redission with both:

* [`useSingleServer().setAddress("redis://anycasted-ip:port")`](https://github.com/redisson/redisson/wiki/2.-Configuration/#26-single-instance-mode) and 
* [`useReplicatedServers().addNodeAddress("redis://anycasted-ip:port")`](https://github.com/redisson/redisson/wiki/2.-Configuration/#25-replicated-mode)

It seems neither of these two appear to be able to detect a failover event. When failover happens and a new master is elected, Redission keeps using existing established connections trying to write to what now became a slave, and getting:
```
READONLY You can't write against a read-only slave
```
My question is: isn't `useReplicatedServers()` supposed to periodically check the actual `ROLE` of a server it is connected to, so that when such a "silent" change in topology happens behind haproxy? Could it be that it is a problem on `haproxy` side, that keeps proxying traffic through open connections to previously connected node? I'd expect exactly a periodic `ROLE` check to address this. 

Thank you.

**Comment by mrniko** [comment]
> READONLY You can't write against a read-only slave

This message proves that "elected master" still remains in slave role. You need to fix this in Redis configuration.
