### ISSUE TITLE
Unintelligible symbols in YAML config format

### ISSUE THREAD

**Issue by mihmig** [redisson/redisson#3958]
In https://github.com/redisson/redisson/wiki/2.-Configuration#242-cluster-yaml-config-format
i see parameter and its value (codec and the class that implements it):

**codec: !<org.redisson.codec.MarshallingCodec> {}**

But what do the symbols mean:
1. ! (exclamation mark)
2. <> (angle brackets)
3. {} (curly brackets)

?

**Comment by SplotyCode** [comment]
This does not come from redisson but jackson as it is yaml standarts. 
Single exclamation mark: means Local data type (double would be build in type)
angle brackets: Allows to specify user tag by uri schemas rather then name (in case of jackson fully classified java class name)
curly brackets: Just normal yaml map can be used everywere in this case paramters for the user type.
