### ISSUE TITLE
Returning Null Value  from  redissonClient.getMapCache(CLIENT_MAP).get(key)  in replicated  multinode cluster. 

### ISSUE THREAD

**Issue by Reshmakoganti** [redisson/redisson#3961]
Hello,

I am trying to fetch  a value for a particular key from a replicated  multinode cluster.  This cluster has 2 nodes. Node1, Node2 with authentication on. I am inserting values and trying to fetch the same value.  
 Key-value pair insertion happened in node1. And while fetching the same key-value pair , I am suspecting it it trying to get it from node2. 

Please find my code below

--configuration
 Config config = new Config();
                    config.useReplicatedServers()
                            .addNodeAddress(node1).addNodeAddress(node2).setUsername(userName).setPassword(password)
                            .setReadMode(ReadMode.MASTER_SLAVE);
                    multiInstanceClient = Redisson.create(config);

---storig
 if (redissonClient != null) {
            RMapCache<String, String> cache = redissonClient.getMapCache(CLIENT_MAP, StringCodec.INSTANCE);
            cache.put(tokenId, tokenValue,ttl,  TimeUnit.SECONDS);
            return true;
        }

--- fetching the value

if (redissonClient != null) {
            RMapCache<Object, Object> cache = redissonClient.getMapCache(CLIENT_MAP);
            if (!cache.isEmpty()) {    // size is 3 and the key is present in the list but still returning null on cache.get(key)
               return cache.get(key) != null ? cache.get(key).toString() : null;
            }
        }

From redis cli I had to do readonly on node2 inorder to c the keys. If readonly is only option to fetch the key-value pair from java code, how to code it?

Help is appreciated . Thank you in advance.

**Comment by mrniko** [comment]
slave node may return null value in case of replication lag.

**Comment by Reshmakoganti** [comment]
Thank you for your reply. How much lag time we can except? cache.get(key) is returning null consistently.

**Comment by mrniko** [comment]
It depends on network throughput and data size

**Comment by Reshmakoganti** [comment]
Thank you for your input.
