### ISSUE TITLE
I want save lock state with redis instance failover. What configuration for lock and redis can do this?

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#3965]
Hello, i search distributed lock, that if one redis instance crash all setted locks can be transfered and accessed from other redis instances. 
I think this situation is solved only by redlock or multilock with 3 redis master nodes but not cluster ? 
```
In documentation:
8.4. RedLock
This object is deprecated. RLock operations now propagated to all Redis slaves.
```
Is a blocking redundancy scheme possible with master-slave replication(sentinel, not cluster) ?

**Comment by mrniko** [comment]
Yes, it works for both Sentinel and Cluster setups
