### ISSUE TITLE
Too much log

### ISSUE THREAD

**Issue by kitkars** [redisson/redisson#3967]
How to get rid of this too much log? I use this dependency. i do not have anything else. `logging.level.root=off` does not help.

```
		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-boot-starter</artifactId>
			<version>3.16.2</version>
		</dependency>
```

15:14:56.022 [redisson-netty-2-13] DEBUG org.redisson.connection.ClientConnectionsEntry - new pubsub connection created: RedisPubSubConnection@1592540002 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x00142ce9, L:/127.0.0.1:65416 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.025 [redisson-netty-2-15] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@1511803612 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x73552984, L:/127.0.0.1:65411 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.027 [redisson-netty-2-16] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@108778343 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xd6f062fe, L:/127.0.0.1:65412 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.027 [redisson-netty-2-17] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@1763894632 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x3bda704e, L:/127.0.0.1:65409 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.031 [redisson-netty-2-23] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@405954248 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xadaf551e, L:/127.0.0.1:65414 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.030 [redisson-netty-2-21] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@1967836677 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x7d0af250, L:/127.0.0.1:65417 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.029 [redisson-netty-2-18] DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection@722387409 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x96a31b96, L:/127.0.0.1:65410 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null]
15:14:56.037 [redisson-netty-2-13] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 127.0.0.1/127.0.0.1:6379

**Comment by mrniko** [comment]
you need to set INFO logging level for `org.redisson` package.

**Comment by kitkars** [comment]
Does not help at all.
Redission seems to do this!! 
```
11:56:29.896 [redisson-netty-2-29] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-29
11:56:29.897 [redisson-netty-2-5] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-5
11:56:29.898 [redisson-netty-2-8] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-8
11:56:29.899 [redisson-netty-2-12] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-12
11:56:29.901 [redisson-netty-2-30] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-30
11:56:29.902 [redisson-netty-2-11] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-11
11:56:29.902 [redisson-netty-2-2] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-2
11:56:29.903 [redisson-netty-2-7] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-7
11:56:29.905 [redisson-netty-2-3] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-3
11:56:29.906 [redisson-netty-2-14] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-14
11:56:29.906 [redisson-netty-2-27] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-27
11:56:29.908 [redisson-netty-2-4] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-4
11:56:29.908 [redisson-netty-2-10] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-10
11:56:29.908 [redisson-netty-2-31] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-31
11:56:29.909 [redisson-netty-2-26] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: redisson-netty-2-26
11:56:29.912 [redisson-netty-2-9] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-9
11:56:29.912 [redisson-netty-2-25] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-25
11:56:29.912 [redisson-netty-2-24] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: redisson-netty-2-24
```

**Comment by lbornov2** [comment]
I get the same thing.  App built with spring boot but running in a tomcat container.
