### ISSUE TITLE
Is pipeline response list ordered?

### ISSUE THREAD

**Issue by Hailprob** [redisson/redisson#3973]
```
for(String key:keys){ 
batch.getMap(key).readAllMapAsync(); 
}
BatchResult<?> result = batch.execute(); 
pipelineMapList = (List<Map<String, String>>) result.getResponses(); 
```
Are pipelineMapList and keys kept the same order? If not, is there a way to get ordered result with response to the keys order.

**Comment by mrniko** [comment]
result list maintains the same order as commands were invoked.
