### ISSUE TITLE
Unable to send PING command over channel

### ISSUE THREAD

**Issue by qq502361472** [redisson/redisson#3974]
redisson:3.16.3

2021-11-23T09:19:58.498Z APP 2021-11-23 09:19:58.445 [redisson-timer-4-1] ERROR org.redisson.client.handler.PingConnectionHandler - Unable to send PING command over channel: [id: 0x47a3d5e2, L:/1**.**.118.**:38562 - R:**.6.79.87/**.6.79.87:6381]
2021-11-23T09:19:58.499Z APP  at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:255)
2021-11-23T09:19:58.499Z APP org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://**.6.79.87:6381]
2021-11-23T09:19:58.500Z APP  at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
2021-11-23T09:19:58.500Z APP  at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
2021-11-23T09:19:58.500Z APP  at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
2021-11-23T09:19:58.501Z APP  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-11-23T09:19:58.501Z APP  at java.lang.Thread.run(Thread.java:748)

**Comment by qq502361472** [comment]
3主3从

**Comment by mrniko** [comment]
> Command execution timeout for command

It means network connection problem. Command sent, but response wasn't sent back.

**Comment by qq502361472** [comment]
但是日志显示它一直重试同一台服务器，没有按照轮询负载去重试其它服务器

**Comment by qq502361472** [comment]
> 

但是日志显示它一直重试同一台服务器，没有按照轮询负载去重试其它服务器

**Comment by mrniko** [comment]
ping handler tries to ping the same connection again and again if it fails to get response.

**Comment by qq502361472** [comment]
明白了，谢谢

**Comment by qq502361472** [comment]
redis限制了集群的线程池大小，下面是redis的配置，这样会影响redisson默认配置的主和从的线程池吗？这样会不会导致网络超时？

redis:
################### redis 单机版 start ########################## 
    host: ${summary.redis.host}
    port: ${summary.redis.port}
    password: ${summary.redis.password}
    timeout: 6000
    database: 8
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms

**Comment by brucewuu520** [comment]
我单机也是这个错误

**Comment by brucewuu520** [comment]
其他服务是用lettuce没问题

**Comment by mrniko** [comment]
try to set `pingConnectionInterval` = 0

**Comment by qq502361472** [comment]
我调整了redisson集群的连接池大小以及线程数，增大了redis的连接池大小，异常没了

**Comment by wangjunhan2018** [comment]
@qq502361472 请问能发下你的redis和redisson的配置参考下吗？

**Comment by qq502361472** [comment]
@wangjunhan2018 你需要哪个配置参考？

**Comment by qq502361472** [comment]
@wangjunhan2018 不报错的那个吗？要等周一去公司才能复制给你

**Comment by wangjunhan2018** [comment]
对，不报错的。我也遇到了类似的问题，而且就是本机程序往本机哨兵发。
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/37608036/143592085-eaa0ce80-a0dc-4f35-9e02-9f2e815b3571.png">

**Comment by qq502361472** [comment]
@wangjunhan2018 你参考一下吧，我这里是cluster集群3主3从的，你的是sentinel集群，可能会有一些区别，最开始我是调节这个参数pingConnectionInterval，它报错就没了
threads:0
nettyThreads:10
pingConnectionInterval:10  #调节这个参数影响这个报错
ScanInterval:2000
RetryInterval:1000
SlaveConnectionPoolSize：8
SlaveConnectionMinimumIdleSize：4
MasterConnectionPoolSize：16
MasterConnectionMinimumIdleSize：4


```java
@Bean@ConditionalOnProperty(name = "redis.model", havingValue = "cluster", matchIfMissing = false)
public RedissonClient redissonCluster(RedisProperties redisProperties, RedissonProperties redissonProperties) {    
    log.info("===> 加载集群模式的redisson ...");
    String[] nodes = redisProperties.getCluster().getNodes().stream()
            .map(node -> REDIS_PROTOCOL_PREFIX + node).toArray(String[]::new);
    Config config = new Config();
    config.setCodec(JsonJacksonCodec.INSTANCE) // 序列化方式
            .setThreads(redissonProperties.getThreads())
            .setNettyThreads(redissonProperties.getNettyThreads());
    ClusterServersConfig clusterServersConfig = config.useClusterServers().addNodeAddress(nodes);
    clusterServersConfig.setPassword(redisProperties.getPassword())//设置密码            
             .setPingConnectionInterval(redissonProperties.getPingConnectionInterval())            
             .setScanInterval(redissonProperties.getScanInterval())
            .setRetryInterval(redissonProperties.getRetryInterval())
            .setTimeout(redissonProperties.getTimeout())
            .setSlaveConnectionPoolSize(redissonProperties.getSlaveConnectionPoolSize())
            .setSlaveConnectionMinimumIdleSize(redissonProperties.getSlaveConnectionMinimumIdleSize())
            .setMasterConnectionPoolSize(redissonProperties.getMasterConnectionPoolSize())
            .setMasterConnectionMinimumIdleSize(redissonProperties.getMasterConnectionMinimumIdleSize());
    return Redisson.create(config);}
```

```yaml
redis:
    cluster: ****:7000,****:7001
    timeout: 6000
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms
```
