### ISSUE TITLE
Getting Out of memory error while reading RMap, Map contains over 200k data

### ISSUE THREAD

**Issue by Ravik5** [redisson/redisson#3975]
Code  : 
`RMap.readAllValues().stream().forEach` => OOM Getting here..

Can someone please help me out, Is any available solution to read this load data in RMap, or will have to be read in batches ??

**Comment by Ravik5** [comment]
Do I need to get the complete size if RMap and run through loop to get data in batches or Redission will take care itself?

**Comment by mrniko** [comment]
Redisson will take care itself.

**Comment by Ravik5** [comment]
Thanks for the quick reply, Once more help I need since my RMap data size will vary from 10K to 250K, What would be the ideal batch size :
`RMap<String, Object>.values(CACHE_BATCH_READ_SIZE).forEach` 

CACHE_BATCH_READ_SIZE ??

**Comment by mrniko** [comment]
that depends on data size
