### ISSUE TITLE
Insertion order is not preserved when JSONJackson codec is used in RMap or RMapCache

### ISSUE THREAD

**Issue by varunbh79** [redisson/redisson#3976]
**Expected behavior**
Insertion order should be preserved regardless of codecs configuration but unfortunately it is working only for StringCodec . The problem with string codec is during retrieval it will display the contents as "to string" implementation of java . So need resolution for JSONJackson Codec for preserving insertion order

**Actual behavior**
Currently it is not working for JSONJackson Codec , it is only working for String codec

**Steps to reproduce or test case**

Just Create a Bean of RedissonClient and then setup a RMap or RMapCache Bean with JSONJacksonCodec instance and try to insert the contents into redis the latest item is placed first and the previous one to the last no insertion order is maintained

**Redis version**
 6.2.6

**Redisson version**
3.16.3

**Redisson configuration**

 @Bean
    public RedissonClient redissonClient() {
        
        
        Config    config = new Config();
            config.useSingleServer().setAddress("redis://127.0.0.1:6379");
 
        this.redissonClient = Redisson.create(config);
        return redissonClient;
    }

 @Bean
    public RMap<Long, Employee> employeeRMapCache() {
        final RMap<Long, Employee> employeeRMapCache = redissonClient().getMap(CACHE_NAME, JsonJacksonCodec.INSTANCE, MapOptions.<Long, Employee>defaults()
                .writer(getMapWriter())
        return employeeRMapCache;
    }

**Comment by mrniko** [comment]
RMap and RMapCache objects don't guarantee insertion order. Codec change won't help here. Use queue object instead.

**Comment by varunbh79** [comment]
Thanks for response but how can i use RQueue in place of Map if you can see my scenario I'm caching based on key value pair with Long as key and employee as object
