### ISSUE TITLE
Local cache not working as expected when executing get, put and get operations on the same key

### ISSUE THREAD

**Issue by ipalbeniz** [redisson/redisson#3978]
This is a extension of the issue #3966 because we could not reproduce the problem with the provided test.
So, we are trying to provide a new test trying to reproduce the actual issue that we observed on our application.

**Expected behavior**

We execute these operations on a local cache that points to a redis map already initialized:
1. get initial value
2. put new value
3. get new value

We expect to receive the **new value** on the third operation.

**Actual behavior**

Sometimes we get the **initial value** on the third operation.

**Steps to reproduce or test case**

A test to reproduce the issue:
```java
@Test
public void testLocalCacheGetAndPut() {
    int numberOfKeys = 5_000;

    initializeRedis(numberOfKeys);

    RMap<String, String> localCachedMap = redisson.getLocalCachedMap("test", LocalCachedMapOptions.defaults());
    for (int i = 0; i < numberOfKeys; i++) {
        localCachedMap.get("key" + i);
        localCachedMap.put("key" + i, "value-" + i);
        String cachedValue = localCachedMap.get("key" + i);
        assertThat(cachedValue).isEqualTo("value-" + i);
    }
}

private void initializeRedis(int numberOfKeys) {
    RMap<String, String> map = redisson.getMap("test");
    for (int i = 0; i < numberOfKeys; i++) {
        map.put("key" + i, "initial-value");
    }
}
```

It fails on different iterations when you execute the test more than once:
```
org.opentest4j.AssertionFailedError: 
expected: "value-377"
 but was: "initial-value"

(...)

org.opentest4j.AssertionFailedError: 
expected: "value-1109"
 but was: "initial-value"

(...)

org.opentest4j.AssertionFailedError: 
expected: "value-0"
 but was: "initial-value"
```

**Redis version**

Redis 5.0.7

**Redisson version**

3.16.5-SNAPSHOT

**Redisson configuration**

Default configuration

**Comment by mrniko** [comment]
I'm afraid your test is incorrect since you use getMap() in initializeRedis. Please use same type of object for same name.

**Comment by ipalbeniz** [comment]
> I'm afraid your test is incorrect since you use getMap() in initializeRedis method. Please use same type of object for same name.

We only want to show that redis should have some data **before** starting the test.
If you know how to initialize redis before starting the test, could you tell us how to do it?
It is mandatory not to use the `localCachedMap` to initialize the data because the initialization process could interfere with the test. That is why we used a `map` to initialize the data.

**Comment by ipalbeniz** [comment]
@mrniko I've reimplemented the test to avoid initializing redis from the test code. 

Now it waits 20 seconds for a manual redis initialization executing this command (replacing the redis port with the current port) with this file: [redis_data.txt](https://github.com/redisson/redisson/files/7596677/redis_data.txt):
```
cat redis_data.txt | redis-cli --pipe -p port

All data transferred. Waiting for the last reply...
Last reply received from server.
errors: 0, replies: 1001
```

The test:
```java
@Test
public void testLocalCacheGetAndPut() throws InterruptedException {
    System.out.println("waiting for manual redis initialization: \"cat redis_data.txt | redis-cli --pipe -p port\"");
    Thread.sleep(20_000);
    System.out.println("testing local cache");

    RMap<String, String> localCachedMap = redisson.getLocalCachedMap("test", new StringCodec(), LocalCachedMapOptions.defaults());
    for (int i = 0; i < 1_000; i++) {
        localCachedMap.get("key" + i);
        localCachedMap.put("key" + i, "value-" + i);
        String cachedValue = localCachedMap.get("key" + i);
        assertThat(cachedValue).isEqualTo("value-" + i);
    }
}
```

It fails on different iterations:
```
waiting for manual redis initialization: "cat redis_data.txt | redis-cli --pipe -p port"
testing local cache

org.opentest4j.AssertionFailedError: 
expected: "value-363"
 but was: "initialvalue"
```

```
waiting for manual redis initialization: "cat redis_data.txt | redis-cli --pipe -p port"
testing local cache

org.opentest4j.AssertionFailedError: 
expected: "value-0"
 but was: "initialvalue"
```

```
waiting for manual redis initialization: "cat redis_data.txt | redis-cli --pipe -p port"
testing local cache

org.opentest4j.AssertionFailedError: 
expected: "value-534"
 but was: "initialvalue"
```

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by ipalbeniz** [comment]
Thank you @mrniko, it looks very promising!
Would it be possible to release the 3.16.5 PRO version on the current month?
We are eagerly waiting for the local cache fixes included in that release.

**Comment by mrniko** [comment]
@ipalbeniz 
I'll release it during next week.
