### ISSUE TITLE
 org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries

### ISSUE THREAD

**Issue by TeamHuddle** [redisson/redisson#3980]
Specification we are using:

AWS Elasticache- Redis 5.0.6 (Cluster Mode with master and slave)
Redisson library; 3.16.4
connectTimeout: 3000
timeout: 1000
retryAttempts: 1
slaveConnectionMinimulIdleSize: 24
slaveConnectionPoolSize: 64
masterConnectionMinimulIdleSize: 24
masterConnectionPoolSize: 64
nodeAddres: clusterendpoint:6379
readmode: SLAVE
using: ClusterServers and RBucket to set and get

We are intermittently facing the below error. I think this is because the Master instance is loosing connection to the slave instance. 
org.redisson.client.**RedisConnectionException**: **SlaveConnectionPool no available Redis entries**. **Master entry host**: XX.XXX.XXX/XX.XXX.XXX:6379 **Disconnected hosts**: [XX.XXX.XXX/1XX.XXX.XXX:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:216)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:273)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:499)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionReadOp(MasterSlaveConnectionManager.java:549)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:555)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:121)
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

If we check the elasticache, all instance in the cluster are in available status.

Only way to resolve is to redeploy the application.
Any idea on configuration that should be tweaked? Or does redisson provides any time interval to refresh the connection to avoid this?

I checked the other post but looks it is closed but doesn't have an answer to the question.

**Comment by mrniko** [comment]
Can you set debug logging level for `org.redisson.cluster.ClusterConnectionManager` and share output before this issue?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3983

**Comment by mrniko** [comment]
Fixed

**Comment by mrniko** [comment]
Additional fix added.

**Comment by LarrySha** [comment]
This problem occurs in version 3.20.0

**Comment by mrniko** [comment]
@kit-lee 

https://github.com/redisson/redisson/issues/3980#issuecomment-1471659155

**Comment by mrniko** [comment]
Additional fix has been made

**Comment by SHxKM** [comment]
This is happening to us on version `3.23.4` with an Elasticache.

**Comment by SHxKM** [comment]
@mrniko Here's the stacktrace for Redisson with `3.23.4`:

```
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: master.XXXXXX.use1.cache.amazonaws.com/X.X.X.30:6379 Disconnected hosts: [master.XXXXX.use1.cache.amazonaws.com/X.X.X.30:6379, replica.XXXX.use1.cache.amazonaws.com/XX.XX.XX.30:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:187)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:281)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:582)
	at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:746)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:670)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:317)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by SHxKM** [comment]
@mrniko Unfortunately this is all we have. But I can add two more details:

- While the DNS is different for `replica` and `master`, it (the DNS) resolves to the same machine (this is temporary procedure we have until we have a true reader). Can this cause these errors? it shouldn't, right?
- We are also using Jedis in this app, this is my attempt to promote Redisson in my org. Can the two collide?

What can we do to debug this?

**Comment by mrniko** [comment]
@SHxKM 

> While the DNS is different for replica and master, it (the DNS) resolves to the same machine (this is temporary procedure we have until we have a true reader). Can this cause these errors? it shouldn't, right?

Do you mean that at some moment replica and master have same ip and port?

> We are also using Jedis in this app, this is my attempt to promote Redisson in my org. Can the two collide?

I don't think so

**Comment by SHxKM** [comment]
> Do you mean that at some moment replica and master have same ip and port?

At all points, at the moment. Would this be the reason?

**Comment by SHxKM** [comment]
@mrniko We have tested with `Jedis` and no such problem occurs when using a `JedisPool` that is separate per writer / reader. We have no problem if the error only occurs in Redisson when the actual IPs are identical, but can you confirm whether this would be the reason?

**Comment by mrniko** [comment]
@SHxKM 

I didn't test the case when master and slave the same address

**Comment by mrniko** [comment]
@Crystala 

Thanks for shared details. Can you share Redisson log from the application start moment with `trace` logging level for `org.redisson` package?

**Comment by Crystala** [comment]
@mrniko I'll have a try, but it may take some time, as my working experience with java application developing is nearly 0 :(

**Comment by Crystala** [comment]
@mrniko Log Generated.
Error displayed in browser:
```
ERROR: org.springframework.data.redis.RedisConnectionFailureException: SlaveConnectionPool no available Redis entries. Master entry host: 10.19.1.37/10.19.1.37:32195 Disconnected hosts: [10.19.1.37/10.19.1.37:32195]
```
[redisson_trace.zip](https://github.com/redisson/redisson/files/15023102/redisson_trace.zip)

**Comment by mrniko** [comment]
@Crystala 

Thanks for the provided logs.

Redis reports `MASTERDOWN Link with MASTER is down and replica-serve-stale-data is set to 'no'` check your Redis configuration.

**Comment by Crystala** [comment]
> @Crystala
> 
> Thanks for the provided logs.
> 
> Redis reports `MASTERDOWN Link with MASTER is down and replica-serve-stale-data is set to 'no'` check your Redis configuration.

I fully understand that, at certain points during the replication of this bug (Step 8~15), redis' configuration (masterauth) is wrong at certain points.
Actually, this is what triggers the bug. It is intended to be so.
But, by the end of the replication (Step 16~), all redis nodes' masterauth are correct, and all nodes can function normally.

This is where the bug appears: in most cases, redisson can recognize that redis' status is back to normal and provide services as usual; but sometimes it cannot and keeps throwing exceptions, which is why it is a bug.

**Comment by Crystala** [comment]
@harshalthakre 
My apologies for being unable to reply for almost a whole month!
I was temporarily being transferred to another project, not until now could I have some free time to test the latest version.
:( Work work

------

According to the time of your reply, I used redisson 3.29.0 for this test.

Result: the bug is still there.

```
ERROR: org.springframework.data.redis.RedisConnectionFailureException: SlaveConnectionPool no available Redis entries. Master entry host: 10.19.1.37/10.19.1.37:32196 Disconnected hosts: [10.19.1.37/10.19.1.37:32196]
```

I noticed that, in the update log, redisson mentioned: 
```
Fixed - Slave node in cluster mode isn't shutdown properly if readMode = MASTER and subscribeMode = MASTER
```
But this bug was produced while using ```readMode = SLAVE```. Not sure if it is relative, just a reminder.

This is the config file used, and the log file.
[redisson-config.json](https://github.com/redisson/redisson/files/15315393/redisson-config.json)
[redisson_trace.log](https://github.com/redisson/redisson/files/15315398/redisson_trace.log)

In the log file, command GET FOO and GET FOO4 keeps appearing even after GET FOO2 disappears, which is when the bug shows itself: redisson cannot execute GET FOO2 because ```SlaveConnectionPool no available Redis entries.```
P.S.: Can still access GET FOO2 on 10.19.1.37:32196 by redis-cli.

**Comment by mrniko** [comment]
@Crystala 

I don't see the `SlaveConnectionPool no available Redis entries` error in your logs.

**Comment by Ccccccai777** [comment]
我使用3.18.0的版本也出现了此问题 在redis集群宕机后重启就出现了以下错误  redis集群重启后ip和端口并未发生变化 redis集群也是正常可以访问  在我的java应用重启后解决了此问题
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 
.........................
