### ISSUE TITLE
Redisson locks can consistency guarantee ?

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#3982]
Redisson locks can consistency guarantee as raft consensus protocol (ex:hazelcast) with schemes cluser and master+slave(sentinel) ? It dont have problems as has hazelcast before cp-subsystem(ver3.12) "at least once" https://docs.hazelcast.org/docs/3.11.2/manual/html-single/index.html#exactly-once-at-least-once-or-at-most-once-execution

**Comment by mrniko** [comment]
Redisson Lock uses sync slaves command to guarantee sync with slaves. 

Raft protocol is planned for support in upcoming Redis 7.0

**Comment by alexworkgit** [comment]
In raft all nodes can be write for locks ? Unlike redis only master.  I am right understood ?

**Comment by mrniko** [comment]
In Redis cluster with multiple masters each key bounded to own master. Hazelcast and Redis have different architecture.

**Comment by alexworkgit** [comment]
Thanks

**Comment by mrniko** [comment]
Basically Redis doesn't need master-master sync due to sharding objects across masters.
