### ISSUE TITLE
 Inquire about the distributed scheduling task service (Scheduler Service), how to achieve that only one of the multiple worker servers (worker) executes tasks at a time?

### ISSUE THREAD

**Issue by elevenkongqian** [redisson/redisson#3991]
Inquire about the distributed scheduling task service (Scheduler Service), how to achieve that only one of the multiple worker servers (worker) executes tasks at a time?

My code is as follows:
Configuration code:

    @Bean(destroyMethod = "shutdown")
    public RedissonNode redissonNode(@Qualifier("redissonConfig") Config config, @Qualifier("redissonClient") RedissonClient redissonClient) {
        RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
        nodeConfig.setExecutorServiceWorkers(Collections.singletonMap(GoogleRefundService.executorServiceName, 1));
        RedissonNode node = RedissonNode.create(nodeConfig, redissonClient);
        node.start();
        return node;
    }

Schedule task code:

    @Value("${sdk.payment.thirdparty.google.refund.cronSchedule:0/5 * * * * ?}")
    private String refundCronSchedule;

    @PostConstruct
    public void initGoogleRefundSchedule() {
        ExecutorOptions options = ExecutorOptions.defaults();
        // 设定为0则不进行重试
        options.taskRetryInterval(0, TimeUnit.MINUTES);
        RScheduledExecutorService executorService = redissonClient.getExecutorService(executorServiceName, options);
        int taskCount = executorService.getTaskCount();
        log.info("initGoogleRefundSchedule taskCount:{}", taskCount);
        if (taskCount == 0) {
            executorService.schedule((Runnable & Serializable) () -> log.info("task has been executed!"), CronSchedule.of(refundCronSchedule));
        }
    }

According to the configuration, log("task has been executed!") will be output every 5 seconds. It is currently started on a single server, and the scheduled task service can run.
But if you start the service on multiple servers, the process on each server will output every 5 seconds, but what I want to achieve is: on multiple workers (workers), only one of them (or Random, or polling, or preemption) execute a task every 5 seconds.
How should I configure the distributed scheduling task service to achieve this effect?

**Comment by elevenkongqian** [comment]
![Uploading image.png…]()
screenshot:
Three of the servers, at 15:06:10, two of the servers performed distributed tasks

**Comment by mrniko** [comment]
Current implementation supports uses all available workers for tasks execution in queue.

**Comment by elevenkongqian** [comment]
Thank you, I have found the problem. The time synchronization must be ensured between the cluster servers. I used "chrony" to do the time synchronization and found that the problem was solved!

**Comment by ns-qasim** [comment]
@elevenkongqian can you please elaborate how exactly did you fixed it? I am using multiple tomcat nodes and facing the same issue

`RScheduledExecutorService executorService = client.getExecutorService("runnableExecutorService");
			executorService.registerWorkers(options);
			executorService.scheduleAtFixedRate(new RunnableTask(), 0, 5, TimeUnit.SECONDS);`

Following code get executed on both tomcats after 5 seconds.
