### ISSUE TITLE
Redis vendor rename command 'eval' to 'xxx_eval‘, redisson throws exception when I use it.

### ISSUE THREAD

**Issue by 913761236** [redisson/redisson#3998]
Can I configure this command somewhere?

**Comment by DexYang** [comment]
really need this....

**Comment by 913761236** [comment]
For security，vendor  has renamed these potentially dangerous commands and gave us a mapping table.
Like this , 'flushall' ->  'joYAPNXRPmcarcR4ZDgC81TbdkSmLAzRPmcarcR', one table for dev, one table for pro

**Comment by DexYang** [comment]
I rewrite the `org.redisson.client.protocol.RedisCommands` interface and change all "EVAL" to "EVAL_NEW"(in your case is change 'flushall' to '...'), it currently works for me but i don't know if there are any unknown side effects

**Comment by 913761236** [comment]
That's what i did, didn't find any problem until now. Maybe I'm not using all the features. if it works, do not touch it.

**Comment by mrniko** [comment]
[commandName](https://github.com/redisson/redisson/wiki/2.-Configuration#commandmapper-1) setting added.

**Comment by 913761236** [comment]
Thanks

**Comment by DexYang** [comment]
> [commandName](https://github.com/redisson/redisson/wiki/2.-Configuration#commandmapper-1) setting added.

sorry i can't find it.... i use 3.21.3 version... the only mapper i can find in Config is "setNameMapper"

**Comment by JokerDevops** [comment]
@mrniko  How to use command Mapper?

Can you give a configuration example?

For example, my redis server has del set to del_new.
