### ISSUE TITLE
结合 Spring Boot restore方法设置replace参数为true的时候，还是抛出异常

### ISSUE THREAD

**Issue by xiaopanghhh** [redisson/redisson#3999]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
6.2.1
**Redisson version**
3.16.4
**Redisson configuration**

结合 StringRedisTemplate 使用   restore  的时候，
当恢复的 KEY 已经存在的时候，
replace 参数传 false 时，数据没有被修改抛出 org.redisson.client.RedisBusyException 异常。

replace 参数传 true 时，数据被修改 但是也 抛出 org.redisson.client.RedisBusyException 异常。

不知道是不是源代码这里出了问题， restore(key, ttlInMillis, serializedValue);   是不是应该是在 else 里面的呀。

![image](https://user-images.githubusercontent.com/24469601/144192304-0254dd59-3f5c-485d-bb82-4ccc19833d50.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
