### ISSUE TITLE
Reddison 3.16.4 is using netty-transport 4.1.68.Final but when I upgrade to 3.16.4 of reddison is still using netty-transport 4.1.65 version

### ISSUE THREAD

**Issue by tntstn** [redisson/redisson#4000]
**When upgrade the redisson version from 3.10.4 to 3.16.4**

**netty-transport should be 4.1.68**

**just upgrade the redisson version 3.16.4 in a gradle project**

**3.16.4**

Hello, I have the same issue for 3.16.4. I am using gradle and I updated my redissson version from 3.10.4 to 3.16.4 to solve a CVE. But when I checked the dependencies I realised that some how I do not know why, the versions were downgraded from 4.1.68 to 4.1.65 for netty-transport (it comes with redisson).

Could you take a look, please?

Thank you.

Here is the output;

+--- org.redisson:redisson:3.16.4
| +--- io.netty:netty-common:4.1.68.Final -> 4.1.65.Final
| +--- io.netty:netty-codec:4.1.68.Final -> 4.1.65.Final
| | +--- io.netty:netty-common:4.1.65.Final
| | +--- io.netty:netty-buffer:4.1.65.Final
| | | --- io.netty:netty-common:4.1.65.Final
| | --- io.netty:netty-transport:4.1.65.Final
| | +--- io.netty:netty-common:4.1.65.Final
| | +--- io.netty:netty-buffer:4.1.65.Final ()
| | --- io.netty:netty-resolver:4.1.65.Final
| | --- io.netty:netty-common:4.1.65.Final
| +--- io.netty:netty-buffer:4.1.68.Final -> 4.1.65.Final ()
| +--- io.netty:netty-transport:4.1.68.Final -> 4.1.65.Final (*)
| +--- io.netty:netty-resolver:4.1.68.Final -> 4.1.65.Final ()
| +--- io.netty:netty-resolver-dns:4.1.68.Final -> 4.1.65.Final
| | +--- io.netty:netty-common:4.1.65.Final
| | +--- io.netty:netty-buffer:4.1.65.Final ()
| | +--- io.netty:netty-resolver:4.1.65.Final ()
| | +--- io.netty:netty-transport:4.1.65.Final ()
| | +--- io.netty:netty-codec:4.1.65.Final ()
| | +--- io.netty:netty-codec-dns:4.1.65.Final
| | | +--- io.netty:netty-common:4.1.65.Final
| | | +--- io.netty:netty-buffer:4.1.65.Final ()
| | | +--- io.netty:netty-transport:4.1.65.Final ()
| | | --- io.netty:netty-codec:4.1.65.Final ()
| | --- io.netty:netty-handler:4.1.65.Final
| | +--- io.netty:netty-common:4.1.65.Final
| | +--- io.netty:netty-resolver:4.1.65.Final ()
| | +--- io.netty:netty-buffer:4.1.65.Final ()
| | +--- io.netty:netty-transport:4.1.65.Final ()
| | --- io.netty:netty-codec:4.1.65.Final ()
| +--- io.netty:netty-handler:4.1.68.Final -> 4.1.65.Final (*)

**Comment by tntstn** [comment]
I also upgrade the redisson version to 3.16.5 and now it's downgrading from 4.1.70 to 4.1.65. Could you check is please?

**Comment by mrniko** [comment]
I checked dependency tree. It looks correct for 3.16.5 version.

[INFO] +- io.netty:netty-transport-native-kqueue:jar:4.1.70.Final:provided
[INFO] |  +- io.netty:netty-transport-native-unix-common:jar:4.1.70.Final:provided
[INFO] |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.70.Final:provided
[INFO] +- io.netty:netty-transport-native-epoll:jar:4.1.70.Final:provided
[INFO] |  \- io.netty:netty-transport-classes-epoll:jar:4.1.70.Final:provided
[INFO] +- io.netty:netty-common:jar:4.1.70.Final:compile
[INFO] +- io.netty:netty-codec:jar:4.1.70.Final:compile
[INFO] +- io.netty:netty-buffer:jar:4.1.70.Final:compile
[INFO] +- io.netty:netty-transport:jar:4.1.70.Final:compile
[INFO] +- io.netty:netty-resolver:jar:4.1.70.Final:compile
[INFO] +- io.netty:netty-resolver-dns:jar:4.1.70.Final:compile
[INFO] |  \- io.netty:netty-codec-dns:jar:4.1.70.Final:compile
[INFO] +- io.netty:netty-handler:jar:4.1.70.Final:compile

**Comment by tntstn** [comment]
Thank you.
