### ISSUE TITLE
Read operations are not evenly distributed among all the redis nodes in replicated mode and master_slave read mode.

### ISSUE THREAD

**Issue by ipalbeniz** [redisson/redisson#4001]
**Expected behavior**

We use redisson to connect to 3 redis nodes in **replicated** mode and **MASTER_SLAVE** read mode (AWS ElastiCache).
We expect to distribute the redis read operations **evenly** among the 3 redis nodes.

**Actual behavior**

Since the upgrade of redisson to version 3.16.15 PRO we notice that our application does not distribute the redis read opeations evenly to all the nodes, and only one redis node receives almost 100% of the read operations.

Yesterday at 20:40 we deployed our application with only one change: upgrade redisson from 3.16.4 to 3.16.5.
And today at 11:10 we rolled back our application to the redisson 3.16.4 version.
This graph shows:
- Until 20:40 the 3 redis nodes received the read operations evenly (redisson 3.16.4)
- From 20:40 just one redis node receives almost all the read operations (upgrade to redisson 3.16.5)
- From 11:10 the 3 redis nodes receive the read operations evenly again (rollback to redisson 3.16.4)
![2021-12-01_11-43](https://user-images.githubusercontent.com/7996927/144223347-20674814-a785-401c-823a-f987425c8f2f.png)

**Steps to reproduce or test case**

Connect to 3 nodes in replicated mode and MASTER_SLAVE read mode. 
Execute multiple read operations. 
Check redis read operations metrics.

**Redis version**

Redis 5.0.7

**Redisson version**

3.16.15 PRO

**Redisson configuration**

- **replicated** mode 
- **MASTER_SLAVE** read mode
- 3 AWS ElastiCache nodes (1 master + 2 slaves)

**Comment by mrniko** [comment]
Can you share logs generated by `org.redisson.connection.ReplicatedConnectionManager` class from start?

**Comment by ipalbeniz** [comment]
We only have WARN and ERROR logs. 

This is an ERROR log message that appears when deploying the application with Redisson 3.16.15:
```
Timestamp: Nov 30, 2021 @ 20:39:08.997
Logger: org.redisson.connection.ReplicatedConnectionManager
Level: ERROR
Thread: redisson-timer-4-1
Message: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://vega-pull-002.qaecwn.0001.euw1.cache.amazonaws.com:6379]
Exception: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (INFO REPLICATION), params: [], Redis client: [addr=redis://x-002.x.x.x.cache.amazonaws.com:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:251)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

If you need all the DEBUG, INFO, WARN and ERROR messages we could prepare a test environment in a few days.

**Comment by mrniko** [comment]
Fixed! Thanks for report
