### ISSUE TITLE
Can MessageListener annotated with @FunctionInterface for java8 ?

### ISSUE THREAD

**Issue by Ikki-Dai** [redisson/redisson#4002]
**Is your feature request related to a problem? Please describe.**

MessageListener can be annotated by `FunctionalInterface` to use lambda?

**Describe the solution you'd like**
`java.lang.FunctionalInterface`
**Describe alternatives you've considered**

this interface have only one method  `onMessage`  now

**Comment by mrniko** [comment]
Done
