### ISSUE TITLE
RateLimiter - Can't expire RateLimiter value/permits although can expire config?

### ISSUE THREAD

**Issue by okue** [redisson/redisson#4007]
When using [`RRateLimiter.expire()`], [`RRateLimiter`] sets TTL to config Hash set, but doesn't set TTL to `value` and `permits`.

IIUC, `value` and `permits` consumes more memory compared to config Hash set.
Is there a way to expire `value` and `permits`?

NOTE:
- config = key returned by`getRawName()`
- `value` = key returned by https://github.com/redisson/redisson/blob/redisson-3.16.6/redisson/src/main/java/org/redisson/RedissonRateLimiter.java#L53-L55
- `permits` = key returned by https://github.com/redisson/redisson/blob/redisson-3.16.6/redisson/src/main/java/org/redisson/RedissonRateLimiter.java#L45-L47

[`RRateLimiter.expire()`]: https://github.com/redisson/redisson/blob/redisson-3.16.6/redisson/src/main/java/org/redisson/api/RExpirable.java#L39
[`RRateLimiter`]: https://github.com/redisson/redisson/blob/redisson-3.16.6/redisson/src/main/java/org/redisson/RedissonRateLimiter.java

**Comment by mrniko** [comment]
Can you provide a test code?

**Comment by okue** [comment]
I initialized `RRateLimiter` and set expire as follow.

```java
RRateLimiter rateLimiter = redisson.getRateLimiter(RATE_LIMITER_NAME);
rateLimiter.setRate(RateType.OVERALL, 10, 60, RateIntervalUnit.SECONDS);
rateLimiter.expire(3600, TimeUnit.SECONDS);
```

**Comment by DirZhang** [comment]
org.redisson.api.RExpirable#expire(java.time.Instant)

**Comment by DirZhang** [comment]
this api org.redisson.api.RExpirable#expire(java.time.Instant) ;
rateLimiter.expire(Instant.now().plusMillis(TimeUnit.SECONDS.toMillis(5))) ；
Only the hash will be deleted after 5 seconds ; 
STR and Zset are not deleted

**Comment by DirZhang** [comment]
> 能提供测试代码吗？

rateLimiter.expire(Instant.now().plusMillis(TimeUnit.SECONDS.toMillis(5))) ；

**Comment by okue** [comment]
Does redisson have a plan to support delete `STR` and `Zset` (`value` and `permits`)?

**Comment by mrniko** [comment]
Unable to reproduce.

```java
        RRateLimiter rateLimiter = redisson.getRateLimiter("test");
        assertThat(redisson.getKeys().count()).isZero();
        rateLimiter.setRate(RateType.OVERALL, 10, 60, RateIntervalUnit.SECONDS);
        rateLimiter.acquire(5);
        rateLimiter.expire(Instant.now().plusMillis(TimeUnit.SECONDS.toMillis(5)));
        Thread.sleep(6000);
        assertThat(redisson.getKeys().count()).isZero();
```

**Comment by okue** [comment]
Sorry for the inadequate explanation.
Let me describe more in detail later.

**Comment by t6489609** [comment]
@mrniko, I believe the issue is if you get a RateLimiter but never acquire permit, then the {key}:value TTL is not set and never expires.

Please investigate.

**Comment by mrniko** [comment]
@t6489609 

Unable to reproduce with the test below.

```java
        RRateLimiter rateLimiter = redisson.getRateLimiter("test");
        assertThat(redisson.getKeys().count()).isZero();
        rateLimiter.setRate(RateType.OVERALL, 10, 60, RateIntervalUnit.SECONDS);
        rateLimiter.expire(Instant.now().plusMillis(TimeUnit.SECONDS.toMillis(5)));
        Thread.sleep(6000);
        assertThat(redisson.getKeys().count()).isZero();
```

Please share your code example.

**Comment by t6489609** [comment]
```
    public long testRateLimiterExpire(String key, long rate, long interval, long expire) {
        RedissonClient client = getClient();
        RRateLimiter rateLimiter = client.getRateLimiter(key);
        boolean isNew =  rateLimiter.trySetRate(RateType.OVERALL, rate, interval, RateIntervalUnit.SECONDS);
        rateLimiter.expire(Duration.ofSeconds(expire));
        return rateLimiter.availablePermits();
    }
```
```
        System.out.println(redisTestBed.testRateLimiterExpire("test", 5, 60, 30));
```

**Comment by t6489609** [comment]
I apologize. Forgot to add that my code called availablePermits().
