### ISSUE TITLE
Read Only (not writable_ access from redisson

### ISSUE THREAD

**Issue by lokeshg98** [redisson/redisson#4009]
We want to enforce that Application can only read the data from Redis Master node but is not able to write or make into modifications into the Redis Master node in replicatedServerConfig. Can you please inform how can we do that?  Is that using readMode :MASTER ? Can you please provide the yaml configuration for that ?

**Comment by mrniko** [comment]
readMode=MASTER is used for your case. Write operation is always executed on master node.

**Comment by lokeshg98** [comment]
Thanks for your prompt response
