### ISSUE TITLE
ClientConnectionsEntry.getFreeAmount() removed?

### ISSUE THREAD

**Issue by matmazur** [redisson/redisson#4010]
Hey guys. 

When moving from version 3.16.3 to 3.16.5 I've noticed compilation issues due to the missing method **getAmount()** which underneath was running **freeConnectionsCounter.getCounter()**:

https://github.com/redisson/redisson/blob/redisson-3.16.3/redisson/src/main/java/org/redisson/connection/ClientConnectionsEntry.java#L155-L157

My question is was that intentional and is there a substitute method somewhere? I couldn't find a quick solution for this.

**Comment by mrniko** [comment]
It's removed since it's not used internally. You can use reflection to get access to `freeConnectionsCounter` field.
