### ISSUE TITLE
what's the difference between 'Replicated mode' with other mode?

### ISSUE THREAD

**Issue by IcebergXTY** [redisson/redisson#4012]
The document said 'Replicated mode' is for Azure or AWS, but these cloud service can also use jedis as client which just has single or cluster mode.
So what's the difference if I use the 'Replicated mode' instead of the 'single mode'?

文档里说云托管模式是用来连接云计算运营商提供的Redis云服务，但是这些云服务厂商也可以通过jedis直接连接，而jedis只有常规的单机或者集群连接，是没有这种云托管模式的。
所以使用云托管模式的话，跟用单机或者集群的方式有什么区别吗

**Comment by mrniko** [comment]
In Replicated mode failover is monitored. As well as slave adding/removing.
