### ISSUE TITLE
get LocalCachedMap lead to OOM

### ISSUE THREAD

**Issue by MirsDong** [redisson/redisson#4013]
**Expected behavior**
not hope to oom;
**Actual behavior**
  home get  redissonClient.getLocalCachedMap() can olny single entity,but evrytime get a new new RedissonLocalCachedMap<K, V>(xxxx)，more request lead to OOM
**Steps to reproduce or test case**

**Redis version**

**Redisson version**

**Redisson configuration**

**Comment by mrniko** [comment]
Each LocalCachedMap maintains own local cache. You need to keep a single instance of it per name.

**Comment by MirsDong** [comment]
thanks,I try that's is ok

**Comment by BigMichi1** [comment]
maybe also this issue: #3996 ?
