### ISSUE TITLE
redisson-mybatis - Application still works if Redis does not respond

### ISSUE THREAD

**Issue by aleabalo** [redisson/redisson#4019]
Hi, We are looking to configure redisson-mybatis, so that when for some reason Redis does not respond, the application can be running without problems.
The idea is to leave a trace of the connection error, but that the application executes the sentences and continues working.

I found this similar report, but for Tomcar. [Issue](https://github.com/redisson/redisson/issues/1651)

The question is if this behavior is possible, and if not, could I report a feature?

Thanks for your time

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/3042
