### ISSUE TITLE
Mention that classes need to be Serializable in guides and documentation

### ISSUE THREAD

**Issue by jacekgajek** [redisson/redisson#4026]
We've wasted way to much time searching for a problem in our codebase. I think it won't hurt to add a note in the official guide :)

Here:
https://redisson.org/articles/redis-integration-with-micronaut.html

and here:
https://github.com/redisson/redisson/tree/master/redisson-micronaut

**Comment by mrniko** [comment]
It depends on Codec you use. Default codec requires it. JsonJacksonCodec doesn't.
