### ISSUE TITLE
hibernate-redisson4 expire time configuration not working

### ISSUE THREAD

**Issue by 321vka** [redisson/redisson#4030]
### **I am trying to integrate redis with hibernate 4.1.3.Final. But expire time configuration not working.**
**Here are my redission configuratio:**
{
  "singleServerConfig": {
    "idleConnectionTimeout": 10000,
    "connectTimeout": 10000,
    "timeout": 5000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "password": null,
    "subscriptionsPerConnection": 5,
    "clientName": null,
    "address": "redis://${REDIS_PORT:-127.0.0.1:6379}",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 50,
    "connectionMinimumIdleSize": 10,
    "connectionPoolSize": 64,
    "database": 0,
    "dnsMonitoringInterval": 5000
  },
  "threads": 0,
  "nettyThreads": 0,
  "codec": null
}

**Hibernate configuration:**

                <prop key="hibernate.default_schema">${hibernate.default_schema}</prop>
                <prop key="hibernate.dialect">${hibernate.dialect}</prop>
                <prop key="hibernate.show_sql">false</prop>
                <prop key="hibernate.format_sql">true</prop>
                <prop key="hibernate.generate_statistics">true</prop>
                <prop key="hibernate.cache.use_query_cache">true</prop>
                <prop key="hibernate.cache.use_structured_entries">true</prop>
                <prop key="hibernate.cache.use_second_level_cache">true</prop>
                <prop key="hibernate.javax.cache.missing_cache_strategy">create</prop>
                <prop key="hibernate.cache.redisson.fallback">true</prop>
                <prop key="hibernate.cache.region.factory_class">org.redisson.hibernate.RedissonRegionFactory</prop>
                <prop key="hibernate.cache.redisson.config">/redisson.json</prop>
                <prop key="hibernate.cache.redisson.my_object.eviction.max_entries">10000</prop>
                <prop key="hibernate.cache.redisson.my_object.expiration.time_to_live">18000000</prop>
                <prop key="hibernate.cache.redisson.my_object.expiration.max_idle_time">12000000</prop>

**Comment by mrniko** [comment]
Did you define my_object as the fully qualified class name?

**Comment by 321vka** [comment]
I am trying to query result not an entity, this is code:

```
  Criteria criteria = getHibernateTemplate().getSessionFactory()
                .getCurrentSession().createCriteria(getPersistentClass());
        criteria.setCacheable(true);
        criteria.setCacheRegion("my_query");

        for (Criterion criterion : criterions) {
            criteria.add(criterion);
        }
        return findByCriteria(criteria, skippedChecks);
```

**Comment by mrniko** [comment]
Hibernate resets query cache after each write in entity tables used in query.

**Comment by mrniko** [comment]
You can set `trace` logging level for `org.hibernate.cache` package to make sure that result was cached.

**Comment by 321vka** [comment]
Ok got it. But how do we set the expire time and max entries for query cache ?.

**Comment by mrniko** [comment]
```xml
            <prop key="hibernate.cache.redisson.my_query.eviction.max_entries">10000</prop>
            <prop key="hibernate.cache.redisson.my_query.expiration.time_to_live">18000000</prop>
            <prop key="hibernate.cache.redisson.my_query.expiration.max_idle_time">12000000</prop>
```

You can check hibernate logs to make sure that cache works properly. https://github.com/redisson/redisson/issues/4030#issuecomment-997154192

**Comment by 321vka** [comment]
Thank you @mrniko. One quick question:

**Comment by mrniko** [comment]
Here is the example: https://github.com/redisson/redisson/tree/master/redisson-hibernate#default-region-configuration-used-for-all-caches-not-specified-in-configuration
