### ISSUE TITLE
RLocalCachedMap sometime does not sync data from Redis

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#4034]
Hi,
I have 2 servers that use the same RLocalCachedMap. Server A I use to put data and Server B just use to query data.
I'm facing with issue that sometime Server A updates data but Server B data is still old (cached value is not updated). I checked log but no Redisson exception there.

If I invoke `localCachedMap.preloadCache()` on server B (via SOS REST call), data of server B will be updated.

I'm using Redisson 3.16.5
This is my LocalCacheOptions
`LocalCachedMapOptions.defaults()
            .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
            .cacheSize(0)
            .syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE)
            .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.NONE)
            .writeMode(MapOptions.WriteMode.WRITE_BEHIND);`
This is my RedissonConfig
`config.useSentinelServers()
                .setMasterName(****)
                .setPassword(****)
                .setReadMode(ReadMode.SLAVE)
                .setSubscriptionMode(SubscriptionMode.SLAVE)
                .setKeepAlive(true)
                .setTcpNoDelay(true)
                .addSentinelAddress(redisUri)
                .setSubscriptionsPerConnection(100)
                .setSlaveConnectionPoolSize(1000)
                .setMasterConnectionPoolSize(1000);`

Please help me to point out some ways to investigate and resolve this issue.
Thanks

**Comment by mrniko** [comment]
Did you try to change syncStrategy to SyncStrategy.INVALIDATE ?

**Comment by lehuuthanh5** [comment]
Thanks for replying.
I had not try yet. SyncStrategy.INVALIDATE will make getting data slowdown.
Does Redisson have any method that can detect the problem? and I can trigger preloadCache.
Thanks

**Comment by mrniko** [comment]
there is no such method

**Comment by xyqshi** [comment]
> 

If a message is dropped, wouldn't INVALIDATE also not work?

**Comment by lehuuthanh5** [comment]
It may not work. 
Anyway, using the latest version of Redisson will fix this problem, It's more stable with RLocalCachedMap right now.
