### ISSUE TITLE
SlaveConnectionPool enabled when use single server

### ISSUE THREAD

**Issue by chuckz1321** [redisson/redisson#4042]
**Expected behavior**
There should be just MasterConnectionPool enabled when useSingleServer. 

**Actual behavior**
When trying to connect to Redis containing one node, slave connection pool will also be created. 

**Steps to reproduce or test case**
Connect to single redis server. 

3.16.6 version 

org.redisson.connection.MasterSlaveEntry#setupMasterEntry#154

there is a addSlave() call when single server is used. 
This maybe edited for creating slave connection correctly in some cases. But it will also create a pool when using single server. 

![image](https://user-images.githubusercontent.com/33536264/147175035-017be704-2333-4296-85e7-d0b553c46a8a.png)

**Redis version**
4&6
**Redisson version**
After 3.16.5
**Redisson configuration**
config.useSingleServer()

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4011
