### ISSUE TITLE
How to use Reactive/RxJava api?

### ISSUE THREAD

**Issue by Gieted** [redisson/redisson#4047]
Unfortunately, the docs doesn't contain any information about Reactive and RxJava Redisson apis. How you even use them?

For example, `RMapRx#get(K)` returns `Maybe<V>`, how it can be considered reactive? Shouldn't it be an `Observable<V>`? How it is any more useful than just returning something like a `CompletableFuture<V>`?
What is the use case of these apis? 

Also, `.getLocalCachedMap()` is unavailable in reactive and rx apis, why?

**Comment by mrniko** [comment]
Maybe type is suitable for result if it can be null. More details described here https://medium.com/mindorks/rxjava-types-of-observables-404d75605e35

getLocalCachedMap() for reactive and rx apis isn't implemented yet.

**Comment by Gieted** [comment]
A standard use of RxJava is observing a data change, not just a single value. For e.g:
```java
Observable<String> userName = getUserName();
userName.subscribe(name -> updateView(name));
```

Can something like this be achieved with RxJava/Reactive Redisson apis?

**Comment by mrniko** [comment]
You can do it like this:

```java
        Maybe<Integer> s = map.get(1);
        s.subscribe(v -> {
            System.out.println("value " + v);
        });
```

**Comment by Gieted** [comment]
Ok.
However, why would you limit it to a `Maybe<V>` which produces just a single value, when you could return an `Observable<V>` instead? Observable much better reflects the map entry's value nature, because it can be overridden multiple times.

E.g.
```java
RedissonClient redisson = Redisson.create(config);
RedissonRxClient redissonRx = redisson.rxJava();
RMapRx<String, Integer> rMap = redissonRx.getMap("ints");
rMap.get("1").subscribe(System.out::println);
rMap.put("1", 1);  // will be printed
rMap.put("2", 2);  // will not printed
```

**Comment by mrniko** [comment]
RMap get method isn't based on pubsub as well as Redis hget method. So this won't work.

**Comment by Gieted** [comment]
But what about RMapCache? It already has a feature to add some listeners, so it would be possible to made observable of it
![obraz](https://user-images.githubusercontent.com/35242233/147353989-0401e4aa-a171-4921-8b19-2fe6a41ce86c.png)
