### ISSUE TITLE
Allow specifying class instance each time when deserializing

### ISSUE THREAD

**Issue by Gieted** [redisson/redisson#4051]
Currently, if you deserialize an object it will always be created using the same class instance as when it was serialized. This will result in a `ClassCastException` if you serialize and deserialize from classes loaded by different class loaders (which is a case when using something like hot code reload). 

The proposed solution is to add a type parameter in every method that deserializes an object, e.g.
```java
MyClass value = rMap.get("key", MyClass.class);
```
Which is the same as in a popular GSON library.

**Comment by mrniko** [comment]
You can do it custom codec, supplied in getMap() method.

**Comment by Gieted** [comment]
But won't getting a new map each time cause performance issues (especially which local cache)?

**Comment by mrniko** [comment]
You can define `Map<String, Object>` and then cast it to required class: MyClass cc = (MyClass) map.get("key");

**Comment by Gieted** [comment]
Unfortunately, this causes exactly the same `ClassCastException`

**Comment by mrniko** [comment]
Try to set `useThreadClassLoader = false` setting
