### ISSUE TITLE
What If RLock Implement java.io.Closeable?

### ISSUE THREAD

**Issue by Ikki-Dai** [redisson/redisson#4052]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

auto unlock with `try...with...resource`

maybe code like this
```java
RLock lock = redisson.getLock("KEY");

try{
    if(lock.tryLock(3, Timeunit)){
        // do your biz
    }
} catch(Exception e) {
  e.printStackTrace();
} finally {
lock.unlock
}
```

if implement Closeable interface, code like below
```java

lock.tryLock(3, Timeunit)
try (RLock lock = redisson.getLock("KEY")) {
    if(lock.tryLock(3, Timeunit)){
     // do your biz
    }
} catch(Exception e) {
  e.printStackTrace();
}
```

**Describe alternatives you've considered**
haha. just make code eaiser.

**Comment by mrniko** [comment]
Closeable interface is used for resources.
