### ISSUE TITLE
Time to live for cache elements from both Local and Redis in Near Cache

### ISSUE THREAD

**Issue by mlakshminara** [redisson/redisson#4060]
How can I evict cache elements based on time to live and idle time from both Local and Redis cache for RLocalCachedMap (near-cache). As of now, is this possible in open source edition (or) do I need to buy Pro license.

It would be a great feature if its available in open source edition.

**Comment by mlakshminara** [comment]
Is it possible to set Time to live for both Local cache and also for cache elements stored in Redis cluster when RLocalCachedMap is used ? Can anyone let me know how to do this setup ?

**Comment by mlakshminara** [comment]
Can anyone answer or provide some explanation to this question

**Comment by mrniko** [comment]
This feature is available only in PRO version
