### ISSUE TITLE
clusterSlots() Method Throwing Type Exception (Redisson 3.16.7)

### ISSUE THREAD

**Issue by elakian** [redisson/redisson#4062]
**Expected behavior**
No exceptions expected when querying for clusterSlots:

**Actual behavior**
Get the following exception:
`class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')`

**Steps to reproduce or test case**
- Use Redisson in clustered mode
Call the following code:
```
    redissonClient.getRedisNodes(RedisNodes.CLUSTER).getMasters().forEach(e -> {
      System.out.println(" e.clusterSlots(): " +  e.clusterInfo());
      System.out.println(" e.getAddr().getAddress() " +  e.getAddr().getAddress());
      e.clusterSlots().forEach((key, val) -> {
        System.out.println("key: " + key);
        System.out.println("val: " + val);
      });
    });
```

**Redis version**
6.0.5
**Redisson version**
3.16.7
**Redisson configuration**
```
    Config redissonConfig = new Config();
    redissonConfig.useClusterServers()
        .addNodeAddress(uri);
    return Redisson.create(redissonConfig);
```

**Comment by mrniko** [comment]
Unable to reproduce.

**Comment by elakian** [comment]
This is literally throwing the same exception:
I am using the configuration endpoint for redis cluster as the uri
```
  @Singleton
  @Named("clusterClient")
  RedissonClient clusterClient(
      @Property(name = "cluster.uri") String uri
  ) {
    Config redissonConfig = new Config();
    redissonConfig.useClusterServers()
        .addNodeAddress(uri);
    var client =  Redisson.create(redissonConfig);
    var y = client.getRedisNodes(RedisNodes.CLUSTER).getMasters();
    y.forEach(master -> {
      System.out.println("master.clusterSlots()" + master.clusterSlots());
    });
    return client;
  }
```

**Comment by elakian** [comment]
When modifying the code here (RedisNode.java), it fixes the error:

```
    @Override
    public RFuture<Map<ClusterSlotRange, Set<String>>> clusterSlotsAsync() {
        CompletableFuture<Map<ClusterSlotRange, Set<String>>> promise =
            commandExecutor.readAsync(client, StringCodec.INSTANCE, RedisCommands.CLUSTER_SLOTS).thenApply(
                output -> {
                    List<Object> objs = (List<Object>) output;
                    Map<ClusterSlotRange, Set<String>> map = new HashMap<>();
                    for (Object obj : objs) {
                        List<Object> nodePayload = (List<Object>) obj;
                        Long startSlot = (Long) nodePayload.get(0);
                        Long endSlot = (Long) nodePayload.get(1);
                        ClusterSlotRange range = new ClusterSlotRange(startSlot.intValue(), endSlot.intValue());
                        map.put(range, new HashSet<>());
                        for (int i = 2; i < nodePayload.size(); i++) {
                            map.get(range).add(String.valueOf(nodePayload.get(i)));
                        }
                    }
                    return map;
                }
            ).toCompletableFuture();
        return new CompletableFutureWrapper<>(promise);
    }
```

**Comment by elakian** [comment]
Added the PR: https://github.com/redisson/redisson/pull/4066

**Comment by mrniko** [comment]
Unable to reproduce. Can you share full stacktrace?

**Comment by mrniko** [comment]
Also please share log output in `trace` logging level for `org.redisson` package.

**Comment by elakian** [comment]
The Redis CLUSTER_SLOTS returns a list of objects/strings, so I would expect this error.
Here's the logs:
[output.txt](https://github.com/redisson/redisson/files/7847443/output.txt)

**Comment by mrniko** [comment]
Sorry, I don't see Redis output in your log.

**Comment by elakian** [comment]
@mrniko , I added the following to the logback.xml:    ` <logger name="org.redisson" level="INFO" />`. Not sure what else I can give here? 
Here's a potentially better stack trace: 
[output (1).txt](https://github.com/redisson/redisson/files/7848340/output.1.txt)

**Comment by mrniko** [comment]
Sorry, I asked to define `trace` logging level.

**Comment by elakian** [comment]
Sorry, here is the trace logging:
[output3.txt](https://github.com/redisson/redisson/files/7855746/output3.txt)

**Comment by elakian** [comment]
@mrniko, any update here?

**Comment by elakian** [comment]
@mrniko, any update here?

**Comment by elakian** [comment]
just checking in again, @mrniko. Thanks

**Comment by mrniko** [comment]
Fixed! Thanks for report
