### ISSUE TITLE
Requirement of Insertion Order in RMap Data Structure in Redisson

### ISSUE THREAD

**Issue by varunbh79** [redisson/redisson#4063]
**Is your feature request related to a problem? Please describe.**
Currently have been using RMap for Read-through and Write through Caching Operations and have leveraged benefits out of it. The only benefit we still need is the requirement of Insertion order in RMap as per implementation it is using HashMap . 

**Describe the solution you'd like**
So can insertion order requirement be considered using LinkedHashMap Implementation, which will be most beneficial to many of us

**Describe alternatives you've considered**
We considered going for dequeue, list and other ds but they didn't provide flexibility and performance offered by RMap DataStructure.

**Comment by mrniko** [comment]
RMap uses Redis hash structure which doesn't support insertion order.

**Comment by varunbh79** [comment]
I got your point but how come RListMultiMap is able to preserve the insertion order . My only request is why can't that same implementation be done to RMap.

Thanks
Varun

**Comment by mrniko** [comment]
RListMultiMap preserves the insertion order only for multiple values stored per key.

**Comment by maradanasai** [comment]
How to make RMap behaves like LinkedHashMap in java?
