### ISSUE TITLE
How to use 'zAdd'?

### ISSUE THREAD

**Issue by Jabwin** [redisson/redisson#4065]
How to use 'RedisZSetCommands.zAdd(byte[] key, double score, byte[] value)'?
not implemented？

**Comment by mrniko** [comment]
It's implemented in all versions. Starting from Spring Data Redis 2.5.0 it's routed to `zAdd(byte[] key, double score, byte[] value, ZAddArgs args)` method. Which is also implemented.

**Comment by Jabwin** [comment]
Thank you!
