### ISSUE TITLE
How to use multiple entities with AvroJacksonCodec

### ISSUE THREAD

**Issue by drive55555** [redisson/redisson#4067]
I have two entities in a package.
I try to use AvroJacksonCodec(ClassLoader classLoader), the classLoader is got from one entity.
When I try to save data to Redis.
It has the error
java.lang.IllegalStateException: Can not write Avro output without specifying Schema

How should I resolve it?
Or the AvroJacksonCodec only for one entity for a RedissonClient?

**Comment by mrniko** [comment]
Avro codec requires schema. You need to supply it through AvroSchema class.

**Comment by drive55555** [comment]
So it can't assign two entities and schemas in one AvroJacksonCodec?

**Comment by mrniko** [comment]
I'm afraid no. You can use `CompositeCodec` if you need to specify different key value codecs for map.

**Comment by drive55555** [comment]
OK! I have another question about the AvroJacksonCodec.
After the Avro schema changed, it can't read old data with the new schema.
I found out that you provide two approaches.
1. You provide an "AvroVersionedJacksonCodec" in "redisson-3.15.2-SNAPSHOT". But it doesn't in another release.
2. You suggest using the "Kryo" in [2402(comment)](https://github.com/redisson/redisson/issues/2402#issuecomment-578385916) But could not find any working demo. Could you help to provide a working demo?

**Comment by mrniko** [comment]
AvroVersionedJacksonCodec was an experimental codec. Which could solve the issue. VersionFieldSerializer in demo isn't provided by Redisson.
