### ISSUE TITLE
Why list has all value, but redisson get one by index from the list will reconnect Redis?

### ISSUE THREAD

**Issue by SongTing0711** [redisson/redisson#4071]
RList<String> list = redissonClient.getList(k);
String s = list.get(0);
1、List has all values, but when get by index redisson will reconnect redis.
2、Isn't it dangerous to get all the data of the list in memory？

**Comment by mrniko** [comment]
Unable to reproduce. Please share logs in `trace` logging level for `org.redisson` package.

**Comment by SongTing0711** [comment]
> Unable to reproduce. Please share logs in `trace` logging level for `org.redisson` package.

Sorry,i don't understand.
Do you know what i mean? This problem does not occur in some special scenarios, so there are no logs.

**Comment by SongTing0711** [comment]
> Unable to reproduce. Please share logs in `trace` logging level for `org.redisson` package.

This problem does not occur in some special scenarios,.
Only the redisson fetch list is fully fetched and placed in the Java object.However, when retrieving data from the RList object, redisson will retrieve the data according to the index link redis.
This should be a problem for the  architecture design of data retrieval.

**Comment by mrniko** [comment]
> This should be a problem for the architecture design of data retrieval.

Redisson doesn't cache data. Every method calls Redis command. If you need to fetch full list use `readAll()` method.

**Comment by SongTing0711** [comment]
> > This should be a problem for the architecture design of data retrieval.
> 
> Redisson doesn't cache data. Every method executes Redis command. If you need to fetch full list use `readAll()` method.

But RList cache data.

**Comment by SongTing0711** [comment]
> > This should be a problem for the architecture design of data retrieval.
> 
> Redisson doesn't cache data. Every method executes Redis command. If you need to fetch full list use `readAll()` method.

I mean, through RList<String> list = redissonClient.getList(k), redisson gets the list and puts all the data in the Java object, which may lead to memory overflow.

**Comment by mrniko** [comment]
> But RList cache data

No, it doesn't. You can check the source.

> RList list = redissonClient.getList(k), redisson gets the list and puts all the data in the Java object, which may lead to memory overflow.

Then you need to iterate it, get data by index or by ranges.

**Comment by SongTing0711** [comment]
> 
![image](https://user-images.githubusercontent.com/90837835/149731167-22b888e1-9097-4b4c-8950-b4cb9c6a6921.png)

You can see the picture,RList cache all the data.

**Comment by mrniko** [comment]
since debugger invokes list iterator.
