### ISSUE TITLE
Hi @ybonda  facing similar issue. Could you please provide more details what the issue was in Redis configuration?

### ISSUE THREAD

**Issue by shrutig0510** [redisson/redisson#4075]
Hi @ybonda  facing similar issue. Could you please provide more details what the issue was in Redis configuration?

_Originally posted by @Lakshmihm in https://github.com/redisson/redisson/issues/474#issuecomment-322793385_

**Comment by ybonda** [comment]
Hi @shrutig0510 it's been long time ago... 
I documented the configuration process here : [Configuring and Running Redis Cluster on Linux](https://codeflex.co/configuring-redis-cluster-on-linux/)
Hope it will help.
