### ISSUE TITLE
RedissonMap keySet() is inefficient

### ISSUE THREAD

**Issue by william00179** [redisson/redisson#4077]
This feature request is partially driven by a problem we are having and our attempts to fix it. 

We have multiple services and are utilizing LocalCachedMap's for various write once read many use-cases. The problem arises when a different service needs to invalidate keys in those LocalCachedMap's without the required keys in the class path. We started out with this looking like 

```java
localCacheMap.fastRemove(localCacheMap.keySet("pattern*").toArray(String[]::new));
```

But were getting `ClassNotFoundException` as Redisson is executing an HSCAN which is returning both the Key and Value and these were being run through the Codec leading to this error. 

Currently our workaround is to use a custom codec that just discards the value to avoid this issue.

The only reason I call this a workaround and not a solution is because the values we have in the map are vary large when compared to the keys, so there is an overhead to moving those all over the network that would be great to be able to avoid. 

Currently it looks like in `RedissonMap` the `keyIterator(...)` will use a `RedissonMapIterator` and just grab the key and do nothing with the value. 

It may be possible to use a Lua script such as the one found [here ](https://stackoverflow.com/questions/57921543/is-there-a-method-to-use-hscan-in-jedis-to-retrieve-keys-without-values) to only actually return the keys from the HSCAN call and prevent the overhead of moving them over the network and unmashalling them.

A new iterator `RedissonMapKeyIterator` could be implemented for this specific use case.

**Comment by mrniko** [comment]
Done
