### ISSUE TITLE
Add configuration to MasterSlaveServersConfig to manually set syncSlaves 

### ISSUE THREAD

**Issue by aterleto** [redisson/redisson#4083]
Hello,

I'm using a `MasterSlaveServersConfig` with `readMode=”SLAVE”` and Redis Enterprise. While this configuration works with Redis OSS, it is not always applicable to Redis Enterprise since read-replicas are scaled-out at the database-level; not shard. 

Redis Enterprise can guarantee HA with a single replica shard however the throughput requires multiple read-replicas. This mismatch between the total `slaveAddresses` registered in the configuration and total shards used for HA causes a timeout in the `WAIT` command issued by `Redisson Transactions`.

I checked Redisson’s code and found that the `MasterSlaveServersConfig` is passed to the `MasterSlaveEntry` which is used by `BatchOptions` to set `syncSlaves` based on the amount of `slaveAddresses` configured. When a `Redisson Transaction` is executed, the amount of `syncSlaves` determines how many HA replica shards are needed to respond before the `WAIT` command releases its lock. With the mismatch, this means that they will always timeout.

As a workaround, I'm using a single `slaveAddress` in `MasterSlaveServersConfig` which points to a reverse-proxy for load-balancing of reads between two separate Redis Enterprise database endpoints. Those databases are kept in-synch using Redis Enterprise's `replica-of` and it worked. However, this is not an optimal solution since it adds an extra network-hop and deployment complexity.

So, my feature request is to add a new optional field in the `MasterSlaveServersConfig` to set `syncSlaves` manually which will allow users to pass multiple `slaveAddresses` without impacting the use of the WAIT command on the master database/shard. Since the `freeze` logic is run in other connection related methods, there would still be protection to handle unavailable read-replicas.

Thanks, Allen

**Comment by mrniko** [comment]
Hello Allen,

I'll add syncSlaves field to TransactionOptions object. Default value 0 which means availableSlaves and -1 means no sync at all. 

Code example:
```java
TransactionOptions.defaults().syncSlaves(1);
```

**Comment by aterleto** [comment]
Thanks @mrniko. Would this change be exposed through configuration so we don't need to ask HCL to change the way they are using the API?

**Comment by mrniko** [comment]
@aterleto 

Yes.

@avcad 

BatchOptions already has `syncSlaves` setting

**Comment by mrniko** [comment]
Done

**Comment by aterleto** [comment]
Thanks @mrniko however I don't see a change to either base config. Can you explain how this new option can be set from the config? 

I was expecting something like -

```
masterSlaveServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  **syncSlaves: 1**
```

**Comment by mrniko** [comment]
This setting is applied only to Transaction object. masterSlaveServersConfig has settings applied to Redis client itself. I don't think it's a good API design to put some object settings to masterSlaveServersConfig.

**Comment by aterleto** [comment]
But the setting is related to deployment options, therefore is configuration specific, since one environment might have 1 syncSlaves (production) and a different environment might have 0 (development). It would be an anti-pattern to hard-code anything specific to environment config.

**Comment by mrniko** [comment]
the same settings is also present in BatchOptions. I'm afraid I can't add the same setting per object.

**Comment by avcad** [comment]
Hi @mrniko, Thanks!
I meant this option TransactionOptions.syncSlaves: "Default slaves value is 0 which means available slaves"

For BatchOptions , 0 means no sync, while in TransactionOptions it is available slaves.
Could BatchOptions  be changed for 0 to mean all available slaves as well?
(although that might break backward compatibility)

**Comment by mrniko** [comment]
@avcad 

It's a breaking change. I think to introduce it in next major version.

**Comment by aterleto** [comment]
> This setting is applied only to Transaction object. masterSlaveServersConfig has settings applied to Redis client itself. I don't think it's a good API design to put some object settings to masterSlaveServersConfig.

@mrniko MasterSlaveServersConfig is passed to the MasterSlaveEntry which is used by BatchOptions to set syncSlaves based on the amount of slaveAddresses configured. So there is already precedent for client settings to impact the use of the WAIT Command. If we cannot set syncSlaves through configuration then it does not solve our scenario where the use of the Redisson API is encapsulated within 3rd party code and only the config is exposed to the user.

If MasterSlaveServersConfig can set BatchOptions then why can't it also ensure the current encapsulated code does not force timeouts when using the WAIT command?

**Comment by mrniko** [comment]
@aterleto 

MasterSlaveEntry.getAvailableSlaves() - is not a config setting, but a calculated value.

**Comment by aterleto** [comment]
@mrniko Correct. But getAvailableSlaves() is calculated using slaveAddresses in MasterSlaveServersConfig alone. If I am not mistaken these slaveAddresses are not used in this configuration type for HA/failover. So when there is a mismatch between HA shards and read-replica shards you will always have a timeout. Since the #HA shards can vary per environment it makes sense to configure this instead of hard-coding it at the API level. Based on that logic, shouldn't it factor into the calculated value of BatchOptions since its setting the parameters for the WAIT command?

**Comment by mrniko** [comment]
@aterleto 

> So when there is a mismatch between HA shards and read-replica shards you will always have a timeout

I think in this case it's a misconfiguration. This configuration assumes that all slaves should be defined. In this case getAvailableSlaves() calculated correctly.
