### ISSUE TITLE
how to loadAllKeys  into redis stream?

### ISSUE THREAD

**Issue by wubigo** [redisson/redisson#4085]
The following MapLoader can load all key into redis map,

but my quesiton is : how  loadAllKeys  into redis stream?

`MapLoader<Object, Object> mapLoader = new MapLoader<Object, Object>() {

            @Override
            public Iterable<Object> loadAllKeys() {
                List<Object> list = new ArrayList<>();
                Statement statement = null;
                try {
                    statement = conn.createStatement();
                    ResultSet result = statement.executeQuery("SELECT id FROM values");
                    while (result.next()) {
                        list.add(result.getString(1));
                    }
                } catch (Exception e) {
                } finally {
                    try {
                        statement.close();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }

                return list;
            }
`

**Comment by mrniko** [comment]
RStream object doesn't support MapLoader.

You can load it like this: 
Map entries = new HashMap();
stream.add(id, StreamAddArgs.entries(entries));
