### ISSUE TITLE
can not cast to JSONObject

### ISSUE THREAD

**Issue by woshi496964902** [redisson/redisson#4089]
Error message after storing data
String is stored

{
  "className": "com.alibaba.fastjson.JSON",
  "lineNumber": 229,
  "fileName": "JSON.java",
  "methodName": "parseObject",
  "nativeMethod": false
},
{
  "className": "com.gdmain.core.PXRedisson",
  "lineNumber": 100,
  "fileName": "PXRedisson.java",
  "methodName": "getJSONObject",
  "nativeMethod": false
},
{
  "className": "com.gdmain.core.PXRedisson",
  "lineNumber": 91,
  "fileName": "PXRedisson.java",
  "methodName": "get",
  "nativeMethod": false
},
{
  "className": "com.gdmain.core.PXRedisson",
  "lineNumber": 96,
  "fileName": "PXRedisson.java",
  "methodName": "get",
  "nativeMethod": false
},

**Comment by woshi496964902** [comment]
![image](https://user-images.githubusercontent.com/53846502/150804222-030e6794-1f57-4092-82b1-3c85fbb429e1.png)

**Comment by woshi496964902** [comment]
![image](https://user-images.githubusercontent.com/53846502/150804358-78729227-d13c-41bd-8838-0db397135061.png)

**Comment by woshi496964902** [comment]
why the storage is a string or the conversion error

**Comment by mrniko** [comment]
you need to use StringCodec instead. Default is JbossMarshalling.
