### ISSUE TITLE
[BUG]#2 to 'unpack' (data string too short) Exception in RRateLimiter

### ISSUE THREAD

**Issue by gOODiDEA2002** [redisson/redisson#4090]
#2 to 'unpack' (data string too short) Exception in RRateLimiter
---
ERR Error running script (call to f_a23369f7eb133a5016039b245b3fd2482bcafcc3): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x2094b9e2, L:/192.168.97.199:51774 - R:cache-qa.XXX.cn/192.168.3.243:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@69acd0e0[Not completed, 1 dependents], params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, l-r-lark-example-api-test-api-order-1000, {l-r-lark-example-api-test-api-order-1000}:value, {l-r-lark-example-api-test-api-order-1000}:value:fc56ddcc-eac1-45cf-b7ca-0ae0d3a92e2c, {l-r-lark-example-api-test-api-order-1000}:permits, {l-r-lark-example-api-test-api-order-1000}:permits:fc56ddcc-eac1-45cf-b7ca-0ae0d3a92e2c, 1, 1643103042790, [-74, 79, -99, -40, -27, -122, 42, -53]]

**Steps to reproduce or test case**

        RRateLimiter rateLimiter = redissonConfig.redissonClient().getRateLimiter( "l-r-lark-example-api-test-api-order-1000" );
        boolean trySetRateResult = rateLimiter.trySetRate(RateType.OVERALL, 1, 60, RateIntervalUnit.SECONDS);

        boolean acquireResult = rateLimiter.tryAcquire();  <- Exception throw

**Redis version**

5.0.12

**Redisson version**

3.16.8

**Redisson configuration**

Config config = new Config();
        config.useSingleServer().
                setAddress( String.format( "redis://%s:%s", host, port ) ).
                setPassword( password ).
                setConnectionMinimumIdleSize( 1 ).
                setConnectionPoolSize( 2 );
        return Redisson.create(config);

**Comment by mrniko** [comment]
Unable to reproduce. Try to invoke `redisson.getKeys().flushall();` before your test.

**Comment by gOODiDEA2002** [comment]
it's ok after delete redis key. 

How to avoid recurrence?
--
RRateLimiter rateLimiter = redisson.getRateLimiter( "l-r-lark-example-api-test-api-order-1000" );
//-->
if ( rateLimiter.isExists() ) {
        rateLimiter.delete();
}

**Comment by mrniko** [comment]
don't share the same name with Redisson object of other type.
