### ISSUE TITLE
spring boot application with redisson for spring cache usig aws elasticache redis

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#4092]
Our redis nodes seems to use lots of cpu, how can we find more information about why that much cpu ?
And what sort of redisson configuration we can do to help that ?
Having bigger instances in AWS would not sove it as redis is still limited to one cpu core.

we use redisson for caching with spring boot cache. One cache is caching 'big' data  (heavy structure for pagination), another one has more smaller entries but lots of potential cache check/write.

What sort of metrics we can get from redisson to get a better understanding of the cpu use in redis ?

**Comment by mrniko** [comment]
You can use SLOWLOG Redis command to log the long running commands.
