### ISSUE TITLE
For ReplicatedServers, Reads still going to Master with default settings

### ISSUE THREAD

**Issue by elakian** [redisson/redisson#4095]
**Expected behavior**
Reads only go to Slaves (read replicas)

**Actual behavior**
Reads go to Master node as well. 

**Steps to reproduce or test case**
1. Use replicated servers, have 1 master with 4 replicas in AWS ElastiCache
2. Observe read load on Master Node, it is way above non-zero. 

**Redis version**
6.0.5

**Redisson version**
3.16.9 (lastest commit)

**Redisson configuration**
```
    redissonConfig
        .useReplicatedServers()
        .setReadMode(ReadMode.SLAVE)
        .setTimeout(5000)
        .setNodeAddresses(addressList);
```

**Comment by elakian** [comment]
Here's some trace logs: 
[redis_output.txt](https://github.com/redisson/redisson/files/7944491/redis_output.txt)

**Comment by elakian** [comment]
Figured out that getAtomicLong().getAsync() defaults to the master node, so switced to getBucket.

Is this expected? This was unknown expectation from my end so potentially others. @mrniko

**Comment by mrniko** [comment]
AtomicLong uses master to avoid replication lag. Same for RLock object.
