### ISSUE TITLE
RedissonLocalCachedMap throws NullPointerException

### ISSUE THREAD

**Issue by lasting0001** [redisson/redisson#4096]
RedissonLocalCachedMap init ,it may throws NullPointerException

**Expected behavior**
behavior normal

**Actual behavior**
![image](https://user-images.githubusercontent.com/10528816/151289682-eb419c56-d3f4-4611-b6f5-9dbd5729dc87.png)
![image](https://user-images.githubusercontent.com/10528816/151290190-04e5255c-f7b6-4d67-947e-40d9b6c3e465.png)

**Steps to reproduce or test case**
RedissonLocalCachedMap is in init，and the listener received msg at the same time，it throws NullPointerException just like the picture
**Redis version**
5.0.8
**Redisson version**
3.15.0
**Redisson configuration**

**Comment by mrniko** [comment]
Fixed! Thanks for report
