### ISSUE TITLE
Introduce WAIT command to RPermitExpirableSemaphore

### ISSUE THREAD

**Issue by randomVariable2** [redisson/redisson#4097]
**Is your feature request related to a problem? Please describe.**
In [Issue 2669](https://github.com/redisson/redisson/issues/2669), Redlock was deprecated by integration of WAIT command to RLock. However, the problems caused by out of synchronization nodes still exist for semaphores.
**Describe the solution you'd like**
It could be helpful to introduce the WAIT command to RPermitExpirableSemaphore.
**Describe alternatives you've considered**
Couldn't find many alternatives other than implementing a Redlock like algorithm for semaphores.

**Comment by mrniko** [comment]
Done
