### ISSUE TITLE
RPermitExpirableSemaphore memory not released after expiration

### ISSUE THREAD

**Issue by randomVariable2** [redisson/redisson#4100]
**Expected behavior**
If RPermitExpirableSemaphore with a single permit is acquired but never released, the memory is released after TLL is over.
**Actual behavior**
RPermitExpirableSemaphore is not released after expiration time. Probably keys with `resource-name`, and `{resource-name}:timeout` are not cleaned up.
**Steps to reproduce or test case**
A load test with only random name acquires but no releases shows memory usage increasing. After the test is over, Redis memory usage level stays the same and does not decrease.  The line chart below shows Redis memory usage of 2 consecutive load tests with a pause interval between them.

![memusage](https://user-images.githubusercontent.com/24752888/151752981-e7a2e544-e7e6-4a54-abc5-1beebc32e20f.png)

Below is the graph for number of keys for the same tests:
![image](https://user-images.githubusercontent.com/24752888/151757229-6668a516-4fcd-40a9-97d0-dedd61ea9f19.png)

**Redis version**
6.2
**Redisson version**
3.16.7
**Redisson configuration**
Single instance

**Comment by mrniko** [comment]
cleanup processing could be added to tryReleaseAsync() method as well. Will resolve this issue?

**Comment by randomVariable2** [comment]
Would it make sense to call `PEXPIRE` and update the TTL of the parent `resource-name` when the TTL requested in `tryAcquireAsync` is bigger than the current TTL of the `resource-name`? (It should be set directly if the parent TTL is null)

**Comment by mrniko** [comment]
Right, this is how it can be fixed.

**Comment by mrniko** [comment]
The only solution I can suggest here is to set expire value.

```java
        RPermitExpirableSemaphore semaphore = redisson.getPermitExpirableSemaphore("some-key");
        semaphore.trySetPermits(1);
        semaphore.expire(3, TimeUnit.SECONDS);
```

**Comment by mrniko** [comment]
I reduced size of allocated data in Redis. https://github.com/redisson/redisson/commit/40d2e37c1ee052214b5e0c6b6267cfec3096be61

**Comment by randomVariable2** [comment]
> The only solution I can suggest here is to set expire value.
> 
> ```java
>         RPermitExpirableSemaphore semaphore = redisson.getPermitExpirableSemaphore("some-key");
>         semaphore.trySetPermits(1);
>         semaphore.expire(3, TimeUnit.SECONDS);
> ```

Thank you, I implemented something similar.

**Comment by ryukato** [comment]
I appreciate if you let me now there is any update on release plan?

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/4100#issuecomment-1032328086
