### ISSUE TITLE
Support CH option in addIfLess and addIfGreater for ScoredSortedSet

### ISSUE THREAD

**Issue by agav** [redisson/redisson#4102]
RedissonScoredSortedSet _addIfLess_ and _addIfGreater_ methods don't support **CH** option.
Is that possible to add such support?

E.g. introduce new methods _changeIfLess_ and _changeIfGreater_ which will run ZADD command with both **CH** and **XX** options

**Comment by mrniko** [comment]
Fixed! Thanks for report
