### ISSUE TITLE
TimeSeries - does not handle same values for different timestamps 

### ISSUE THREAD

**Issue by shlomiken** [redisson/redisson#4107]
The problem as it is described in redis documents here. https://redis.com/blog/unlocking-timeseries-data-redis/

Trying to add 1000 same values to different timestamps yield a 558 items only as a result of `RANGE` command.
here is the tail of that command.
```
zrange KS400:100:my-same-value-metric 0 -1 
553) "\xf3g\xd4\xcf~\x01\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x04>\tmy-value "
554) "\xf4g\xd4\xcf~\x01\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x04>\tmy-value "
555) "\xf5g\xd4\xcf~\x01\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x04>\tmy-value "
556) "\xf6g\xd4\xcf~\x01\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x04>\tmy-value "
557) "\xf7g\xd4\xcf~\x01\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x04>\tmy-value "
558) "\xf8g\xd4\xcf~\x01\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x04>\tmy-value "
```

**Expected behavior**
all 1000 items to be returned. 

**Actual behavior**
only 558 items returned as a result of the problem 

**Steps to reproduce or test case**
```
 RTimeSeries<V> ts = redissonClient.getTimeSeries("KS400:100:my-same-value-metric");
for (int i=0;i<1000;i++){
    ts.add(System.currentTimeMillis(), "my-value",60,TimeUnit.DAYS);
}
```

**Redis version**
redis:4.0.9-alpine docker official image

**Redisson version**
org.redisson:redisson:3.13.1

**Redisson configuration**
using docker on localhost , single server

**Comment by shlomiken** [comment]
Update- there is no real problem here, since my test added the items very quickly (same millisecond)  , the uniqueness which is built on top of timestamp(score) was not working, adding a small sleep of 2 milliseconds between adds solved it . 
i believe this is the source that make sure the uniqueness is built on timestamp .
```
"local val = struct.pack('LLc0', tonumber(ARGV[i+1]), string.len(ARGV[i+2]), ARGV[i+2]); " +
```

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by mrniko** [comment]
@shlomiken 

I added 128 random which solves this issue completely.

**Comment by shlomiken** [comment]
@mrniko - thanks , i didn't see any PR
