### ISSUE TITLE
Disable DNS caching

### ISSUE THREAD

**Issue by Ulinay1** [redisson/redisson#4110]
Is it possible to customize DnsResolver and disable caching ?

**Comment by kaeskers** [comment]
What is the response to the issue?

**Comment by mrniko** [comment]
You can override org.redisson.connection.SequentialDnsAddressResolverFactory.create() and use NoopDnsCache, NoopDnsCnameCache objects in this method.

**Comment by kaeskers** [comment]
@mrniko 
Is it okay to configure it like this?
<img width="785" alt="image" src="https://github.com/redisson/redisson/assets/148040265/87e3a3e9-8aee-4569-b944-fbfe4ab90279">

**Comment by mrniko** [comment]
yes

**Comment by kaeskers** [comment]
@mrniko 
The default DNS caching time in Netty is known to be Integer.MAX_VALUE. Without overriding caching settings, it's possible that changes in IP addresses may not be detected in cluster mode.
In the attached image, the code snippet highlighted in red appears to be unable to retrieve the IP of the new node.
What are your thoughts on this?

<img width="934" alt="image" src="https://github.com/redisson/redisson/assets/148040265/d9bc2cec-c49c-40ef-ada7-d19b68825ea7">
