### ISSUE TITLE
How the increase of the memory/key usage cause the Redis timeout exception ?

### ISSUE THREAD

**Issue by RunzhongHuang** [redisson/redisson#4123]
Hi community,

I am using a 3-master and 3-slave redis cluster. The redisson client version is 3.15.1.

Previously the memory usages is approx. 20G, and the total keys are approx. 20million. And I didn't encounter a single exception. 
Recently the memory usage is increased to 40G, and the total keys are around 40million. Now I start to get following exceptions randomly

For example: 
```
com.spcapitaliq.realtime.common.module.commonservice.main.exceptions.RedisException: org.redisson.client.RedisTimeoutException: Unable to acquire connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase connection pool size. Node source: NodeSource [slot=248, addr=redis://<redis-address>, redisClient=null, redirect=MOVED, entry=null], command: (PEXPIRE), params: [<key>, 0] after 0 retry attempts
```
and 
```
com.spcapitaliq.realtime.common.module.commonservice.main.exceptions.RedisException: java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Unable to acquire connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase connection pool size. Node source: NodeSource [slot=14186, addr=redis://<redis-address>, redisClient=null, redirect=MOVED, entry=null], command: (SUNION), params: [key1, key2, key3... keyN] after 0 retry attempts
```

There are other exceptions relate to other redis command, but the common part is "**Unable to acquire connection! Avoid to use blocking commands in Async/JavaRx/Reactive handlers. Try to increase connection pool size**".

The code is same, the only difference that I can see is the increase memory & key usage. Could this be the culprit which causing these issues? And why?

Thanks ahead for your time!

**Comment by mrniko** [comment]
These errors can be cause by bottleneck in network/cpu on Redis/Java side. Which cause more time spending on Redis command execution as a result holding redis connection longer than usual, so you may see situations when connection pool exhausted. Also you can examine Redis slowlog output for slow eval scripts.
