### ISSUE TITLE
reliableTopicWatchdogTimeout is 10, which is not divisible by 3

### ISSUE THREAD

**Issue by workhard-12** [redisson/redisson#4124]
https://github.com/redisson/redisson/blob/3c69c8d4c38f86bdccfffe2f7755836119655ef9/redisson/src/main/java/org/redisson/RedissonReliableTopic.java#L347

The default value of `reliableTopicWatchdogTimeout` is 10, which is not divisible by 3. I remember it was 30 before, did i remember wrong?
Thanks ahead for your time!

**Comment by mrniko** [comment]
It's fine since wesult will be 3333
