### ISSUE TITLE
java.lang.IllegalStateException: Batch already executed!

### ISSUE THREAD

**Issue by wubigo** [redisson/redisson#4127]
add redis stream in batch with batch=10000,

the first 3 batch always succeed , then report  Batch already executed

**Expected behavior**

**Actual behavior**
java.lang.IllegalStateException: Batch already executed!
        at org.redisson.command.CommandBatchService.executeAsync(CommandBatchService.java:216)
        at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:200)
        at org.redisson.RedissonBatch.execute(RedissonBatch.java:207)
        at wubigo.RediStream.produce(RediStream.java:204)
        at wubigo.RediStream.main(RediStream.java:255)

**Steps to reproduce or test case**

while (result.next()) {                        
                        entries.put("pid", result.getString("pid"));
                        entries.put("sid", result.getString("sid"));
                        entries.put("vs", gson.toJson(vs));
                        entries.put("pt", result.getString("pt"));
                        wStream.addAsync(StreamAddArgs.entries(entries));
                        records++;
                        if (records % BATCH == 0) {                          
                            BatchResult<StreamMessageId> res = (BatchResult<StreamMessageId>)batch.execute();
                            int batchSize = res.getResponses().size();
                            if ( batchSize == BATCH)
                                log.info("stream batch successfully");
                            else
                                log.error("stream batch partial successfully:"+batchSize);
                        }
                }
            }

**Redis version**

5.0.7

**Redisson version**

3.16.8

**Redisson configuration**
singleServerConfig:
  idleConnectionTimeout: 10000
  pingConnectionInterval: 5000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://10.166.44.217:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 128
  database: 0
threads: 0
nettyThreads: 0
# codec: !<org.redisson.codec.FstCodec> {}

**Comment by mrniko** [comment]
Batch object can't be reused.

**Comment by wubigo** [comment]
it works, many thanks
