### ISSUE TITLE
Redisson doesn't clean idle connections

### ISSUE THREAD

**Issue by Ulinay1** [redisson/redisson#4129]
I use the next configuration:
```
        config.useSingleServer().setAddress(endpoint)
        .setIdleConnectionTimeout(2000)
        .setConnectionPoolSize(10)
        .setConnectionMinimumIdleSize(3)
        .setPingConnectionInterval(0);
```
Why idle connections does not clearing by redisson ?
![Capture](https://user-images.githubusercontent.com/82771650/153390685-e4d013e7-70d0-439e-b1f8-9ab5420199b6.PNG)

**Comment by mrniko** [comment]
Unable to reproduce. Can you set debug logging level for org.redisson.connection.IdleConnectionWatcher and share output?

**Comment by Ulinay1** [comment]
I can see that validateAmount method is always return false result. And don't go down to check idleTimeout. 
![Capture](https://user-images.githubusercontent.com/82771650/153404528-3fcbfdf7-902a-4b6e-b8c8-efa1b5c3265a.PNG)
![Capture1](https://user-images.githubusercontent.com/82771650/153404532-aa80117c-eaee-4e8f-926e-970101c615c4.PNG)

**Comment by mrniko** [comment]
minimumAmount is 3 as well as connections amount. IdleConnectionWatcher won't close connections until idle connections amount became greater than 3.
