### ISSUE TITLE
Engine CPU Regression when using Redisson (compared to other libraries)

### ISSUE THREAD

**Issue by elakian** [redisson/redisson#4132]
**Expected behavior**
There seems to be an elevated Engine CPU when switching to Redisson from Lettuce. 
Not sure this is due to increase in connection count due to to each instance connecting to all replicas.  

**Actual behavior**
### ![image](https://user-images.githubusercontent.com/854143/153488276-b73ac4fa-9dc4-45bd-b6f0-210f86760550.png)

![image](https://user-images.githubusercontent.com/854143/153488785-47d141a0-3698-4f30-b499-7b7a85d441d9.png)

**Steps to reproduce or test case**
1. Switch from lettuce to Redisson (we are using Micronaut)

**Redis version**
3.16.5

**Redisson version**
3.16.8

**Redisson configuration**

```
    redissonConfig
        .useReplicatedServers()
        .setPingConnectionInterval(5000)
        .setTimeout(5000)
        .setNodeAddresses(addressList);
```

**Comment by mrniko** [comment]
Is first graph for Redis or JVM? Is there any code to reproduce it? You can set the same connections amount you used with Lettuce.

**Comment by elakian** [comment]
> Is first graph for Redis or JVM? Is there any code to reproduce it? You can set the same connections amount you used with Lettuce.

@mrniko, The first graph is the redis engine CPU (elasticache). 
I will try to modify the connections counts to see if they work.
The code is fairly standard:

```
  public CompletableFuture<Boolean> func1() {
    return sonicClient.getMap("key", StringCodec.INSTANCE).getAsync("index").thenApply(x -> {
      if (status == x) {
        return false;
      }
      return status.equals("y");
    }).toCompletableFuture().orTimeout(TIMEOUT_MS, TimeUnit.MILLISECONDS);
  }

  @SneakyThrows
  public CompletableFuture<TierAndCapInfo> func2() {
    RMapAsync<String, String> map = sonicClient.getMap("key", StringCodec.INSTANCE);

    RFuture<String> y = map.getAsync("y");
    RFuture<String> z = map.getAsync("z");
    return CompletableFutures.combine(y, z, (yy, zz) ->
      new Pair(yy, zz)
    ).toCompletableFuture().orTimeout(TIMEOUT_MS, TimeUnit.MILLISECONDS);
  }

```

**Comment by mrniko** [comment]
Did you try to set the same connections amount used with Lettuce?
