### ISSUE TITLE
Entry.connections is always equals to minimumAmount

### ISSUE THREAD

**Issue by hehor** [redisson/redisson#4133]
This is my configuration: 
![Capture1](https://user-images.githubusercontent.com/82771650/153548081-d7bc016b-0266-4f33-8fa8-b8e95bea4d9b.PNG)

I have problem with IdleConnectionWatcher, method validateAmount is always return false, because Entry.connections size is always equals to minimumIdleAmount. How can I fix it ?
![Capture](https://user-images.githubusercontent.com/82771650/153548211-b8ada6aa-052a-401f-b447-0ae96bdf4b5a.PNG)

**Comment by connection1** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已经收到您的来信，请放心。我将尽快给您回复！

**Comment by Ulinay1** [comment]
Now I have the same situation. 
![Capture](https://user-images.githubusercontent.com/82771650/153549328-d558f8eb-c37f-4750-9ff7-10e607370176.PNG)

**Comment by mrniko** [comment]
you have zero connections. Nothing to close.

**Comment by Ulinay1** [comment]
But why my connections depends from ConnectionMinimumIdleSize ? If I setConnectionMinimumIdleSize(2) I will have 2 connections, if I set setConnectionMinimumIdleSize(5) I will have 5 connections.

**Comment by mrniko** [comment]
сonnectionMinimumIdleSize setting allows to will keep idle connections in pool.

**Comment by mrniko** [comment]
entry.connections is the connections list in pool. Unable to reproduce it.
