### ISSUE TITLE
Redisson LZ4 decoder encounter java.lang.IllegalArgumentException: initialCapacity

### ISSUE THREAD

**Issue by RunzhongHuang** [redisson/redisson#4140]
Hi,

I am trying to use LZ4 encoding in my **python** code to **write** data to the Redis cluster, and my **Java** app **reads** it. 

The issue happens when I try to use the Redisson LZ4 Codec to decompress the LZ4 encoded data from Redis. And the Redisson client start to give "java.lang.IllegalArgumentException: initialCapacity -2147483648 (expected: >= 0)" exception. 

This exception happens if the original String is more than 127 characters (include space). If the original String shorter or equal to 127 characters, then decompression works fine and no exception.

========== Detail and Sample Code =============
Here is the detail of the python app where I use to write the data:

**Main Library**:
Python lz4 3.1.10 - https://python-lz4.readthedocs.io/en/stable/intro.html
Redis-py-cluster 2.1.3 - https://github.com/Grokzen/redis-py-cluster

**Sample Code**:
```
from rediscluster import RedisCluster
import lz4.block

redis_client = RedisCluster(startup_nodes=[{"host": "<Redis_host>", "port": "<Port>"}], decode_responses=True)
# Total amount of 'a' is 127, and add one extra 'b' to make it fail in the Java side
# If you keep length of this string smaller or equal to 127, then no exception will happen in java side.
str_val = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"
lz4_compressed_value = lz4.block.compress(str_val.encode('utf-8'))
redis_client.set("test", lz4_compressed_value)
```

Here is the detail of the java app where I use to read and decode the data:

**Main Library**:
Redisson 3.15.1
lz4-java 1.8.0 (If I don't include this dependency in maven, then it will throw "**NoClassDefFoundError: net/jpountz/lz4/LZ4Factory**" exception)

**Sample Code**: 
```
public class RedissonTest {

    public static void main(String[] args) throws Exception {

        try {
            Config config = new Config();
            config.useClusterServers().addNodeAddress("redis://<Redis_host:port>");
            RedissonClient redisson = Redisson.create(config);

            RBucket<String> bucket = redisson.getBucket("test", new LZ4Codec(new StringCodec()));
            String res = bucket.get();
            System.out.println(res);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
```

Here is the exception I encountered:
```
[redisson-netty-2-29] ERROR org.redisson.client.handler.CommandDecoder - Unable to decode data. channel: [id: 0xc6b22b36, L:/10.152.141.73:11468 - R:/10.24.87.48:6360], reply: ReplayingDecoderByteBuf(ridx=22, widx=22), command: (GET), params: [test]
java.lang.IllegalArgumentException: initialCapacity: -2147483648 (expected: >= 0)
```
=================================

After digging into the code, the value "-2147483648" is coming from the function "**buf.readInt()**" in "**LZ4Codec.java**" .
```
public LZ4Codec(Codec innerCodec) {
        this.factory = LZ4Factory.fastestInstance();
        this.decoder = new Decoder<Object>() {
            public Object decode(ByteBuf buf, State state) throws IOException {
                int decompressSize = buf.readInt();
                ByteBuf out = ByteBufAllocator.DEFAULT.buffer(decompressSize);
```

If the original string contains 127 or fewer characters, this "buf.readInt()" will return a positive number.
If the original string contains more than 127 character, this "buf.readInt()" will return the negative number as shown above. And "ByteBufAllocator.DEFAULT.buffer(decompressSize)" failed with the exception above.

Both python lz4 library and the lz4-java that I use are based on Yann Collet's LZ4 library written by C. I would like to ask for help if there is anything that I am doing wrong.

Thanks for your time!

**Comment by mrniko** [comment]
Did you resolve the issue?

**Comment by RunzhongHuang** [comment]
Hi @mrniko , not yet exactly and I switch to snappy compression instead of LZ4 for now. I will close this issue now, and if I come across the same issue again, I will update this issue.

**Comment by SHxKM** [comment]
Experiencing the same issues two years later with `org.redisson:redisson:3.23.4` and `org.redisson:redisson:3.25.2`

**Comment by nsingh1983** [comment]
Hi SHxKM, did you fix the issue, i am having same issue.

**Comment by SHxKM** [comment]
> Hi SHxKM, did you fix the issue, i am having same issue.

Yes. It’s because Redisson expects lz4 but lz4 is unavailable at runtime. Including lz4 as separate dependency solved the issue. Not sure @mrniko is aware though.

**Comment by mrniko** [comment]
@SHxKM 

Do you mean this https://github.com/lz4/lz4-java/releases dependency?

**Comment by SHxKM** [comment]
@mrniko yes
