### ISSUE TITLE
设置对象,最后一直在等待

### ISSUE THREAD

**Issue by hjhhjhhjh** [redisson/redisson#4141]
redisson version 3.15.6 

生产环境线程运行到这里停住了,然后最后导致了OOM ,
用的是单机redis , redis没有开日志

然后就想问问有可能是什么原因导致这样停止不动呢?

![1644919048(1)](https://user-images.githubusercontent.com/25640720/154038101-841451ee-943b-477b-9355-cd63f4d1fa46.jpg)

**Comment by mrniko** [comment]
Do you have a memory dump as well?

**Comment by hjhhjhhjh** [comment]
这个是多天前让同事截的图,,并且里面有涉及到敏感数据,,我自己也拿不到堆转储文件,

**Comment by mrniko** [comment]
is there any way to reproduce it?

**Comment by hjhhjhhjh** [comment]
很遗憾,在本地开发环境暂时没有办法重现
我想了解一下,如果再次出现,可以从哪些方面去排查?
或者建议我可以从哪些方向去查这个问题?

**Comment by hjhhjhhjh** [comment]
我已经找到问题了,是系统其它问题,导致oom, 
碰巧redisson执行到当前位置,导致怀疑堵塞.现在已经排查清楚

感谢
