### ISSUE TITLE
DNSMonitor doesn't see changes.

### ISSUE THREAD

**Issue by Ulinay1** [redisson/redisson#4143]
Hi, I'm testing case in which domain name change IP. So I start my application when file hosts has 127.0.0.1 redis.test. 
Then after starting I change to 128.0.0.1 redis.test. DNSMonitor doesn't see this changes. Also TTL set to 10 java.security.Security.setProperty("networkaddress.cache.ttl", "10");

![Capture](https://user-images.githubusercontent.com/82771650/154243533-efec1163-3b37-46b9-8e07-bb656fd1bbc3.PNG)

**Comment by mrniko** [comment]
Netty dns resolver doesn't monitor hosts file for changes.

**Comment by Ulinay1** [comment]
But it send request to redis.test, why old ip returned ?

**Comment by mrniko** [comment]
hosts file is loaded once, but it's not monitored for changes.

**Comment by xiankris156** [comment]
怎么能监控到host的变化呢，我现在在生产环境更改了dns对应的ip，redission也不能观察到其变化。
