### ISSUE TITLE
ClusterConnectionManager频繁打印slots added,slots removed

### ISSUE THREAD

**Issue by zgyin** [redisson/redisson#4146]
出现这个日志的时候会造成一部分key找不到指定的node
通过加日志调试怀疑是这个位置的问题
![企业微信截图_16450865295226](https://user-images.githubusercontent.com/5373560/154436541-fe73c20c-a0e9-46b7-ba98-17af670f9562.png)
之后我修改源码使用HashSet替换BitSet后就正常了
![企业微信截图_16450869393471](https://user-images.githubusercontent.com/5373560/154436987-005f8041-4e06-457a-8a89-d017e1e526f7.png)

**Comment by mrniko** [comment]
BitSet should also work. It consumes less memory than HashSet. It's unclear why doesn't it work in some cases.

**Comment by mrniko** [comment]
Can you try to set org.redisson.cluster.ClusterPartition#slots field to `new BitSet();` instead of `new BitSet(MAX_SLOT);` and reproduce the issue again?

**Comment by zgyin** [comment]
> Can you try to set org.redisson.cluster.ClusterPartition#slots field to `new BitSet();` instead of `new BitSet(MAX_SLOT);` and reproduce the issue again?

![image](https://user-images.githubusercontent.com/5373560/154600339-e9c51a89-7849-4ef6-a2bd-cc282d0fb165.png)
我将槽字段设置为new BitSet()并没有起作用
![image](https://user-images.githubusercontent.com/5373560/154600415-9c9c9aec-5f3f-46cd-bc08-131536e004c5.png)

**Comment by zgyin** [comment]
以下是机器所处的环境
redis-5.0.4
redisson 3.12.0
aliyun vm (centos 7.9)

**Comment by mrniko** [comment]
Can you also try to replace copySlots() method to:

```java
    public BitSet copySlots() {
        BitSet bs = new BitSet();
        slots.stream().asLongStream().forEach(slot -> {
            bs.set((int)slot);
        });
        return bs;
    }
```

**Comment by zgyin** [comment]
![image](https://user-images.githubusercontent.com/5373560/154647425-a37e89c1-7d6e-4ac3-b89f-79532fcd9b1d.png)
我尝试这样做但还是没能解决！

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/2105 this issue is the reason why I introduced BitSet.

**Comment by mrniko** [comment]
Can you try attached version (zip)? 
[redisson-3.16.9-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8095691/redisson-3.16.9-SNAPSHOT.jar.zip)

**Comment by zgyin** [comment]
使用redisson-3.16.9-SNAPSHOT.jar.zip后问题已经得到解决

**Comment by mrniko** [comment]
Thanks for testing!
Here is the commit https://github.com/redisson/redisson/commit/c409f74370b0a936778fb19216f266ca67a6f731

**Comment by mrniko** [comment]
Fixed
