### ISSUE TITLE
org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=7188, addr=//1.1.1.7:8992, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet

### ISSUE THREAD

**Issue by ankits114** [redisson/redisson#4150]
Hi Team,

We are getting below error while using elasticache redis cluster. While update or save values we are getting this error everytime.

It is not the case of failover. All nodes are active and i can see slot 7188 is also available.

**Redisson version - 3.7.5**

org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=7188, addr=//1.1.1.7:8992, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:550)
	at org.redisson.command.CommandAsyncService.getConnection(CommandAsyncService.java:644)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:499)
	at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
	at java.lang.Thread.run(Thread.java:748)

CLUSTER NODES
2faa414bf9c563ea5db3c4cecb3c470a5695c437 1.1.1.2:8992@1122 myself,slave f8c6bdc58a17c2aa196d88dcba6ea31297bcb88c 0 1645461237000 12 connected
811513819033d8128e29967fe865e40999c71275 1.1.1.3:8992@1122 slave 9e50425e4db917c8c09f201dfd708b955f9793ba 0 1645461238000 4 connected
4b54e8949673ff50f416ba99c90edee59ab174c9 1.1.1.4:8992@1122 slave 616ccd8f07fc64e275e2f8d730ae2c395d53be69 0 1645461237000 3 connected
616ccd8f07fc64e275e2f8d730ae2c395d53be69 1.1.1.5:8992@1122 master - 0 1645461239704 3 connected 8192-10142 12873-16383
9e50425e4db917c8c09f201dfd708b955f9793ba 1.1.1.6:8992@1122 master - 0 1645461238700 4 connected 3768-6498 10143-12872
f8c6bdc58a17c2aa196d88dcba6ea31297bcb88c 1.1.1.7:8992@1122 master - 0 1645461238000 12 connected 0-3767 6499-8191

Could you please help to look into the issue on priority.

Thanks,

**Comment by mrniko** [comment]
Can you provide logs with `trace` logging level for `org.redisson` package? Did you try to recreate the cluster?

**Comment by ankits114** [comment]
I have set log level as Trace but didn't found any additional log.
We have not recreated cluster because we don't have permission to do that directly and issue is reproducible so we want to find the solution for the same.

Could you please help on this issue.
