### ISSUE TITLE
redisson-spring-data: RedissonConnection execute codec bug?

### ISSUE THREAD

**Issue by turboPointLee** [redisson/redisson#4155]
the execute method does not compare the parameter length and parameter type. When a method is overloaded,such as the ttl method, it may cause java.lang.IllegalArgumentException exceptions.

 @Override
    public Object execute(String command, byte[]... args) {
        for (Method method : this.getClass().getDeclaredMethods()) {
            if (method.getName().equalsIgnoreCase(command) && Modifier.isPublic(method.getModifiers())) {
                try {
                    Object t = execute(method, args);
                    if (t instanceof String) {
                        return ((String) t).getBytes();
                    }
                    return t;
                } catch (IllegalArgumentException e) {
                    if (isPipelined()) {
                        throw new RedisPipelineException(e);
                    }

                    throw new InvalidDataAccessApiUsageException(e.getMessage(), e);
                }
            }
        }
        throw new UnsupportedOperationException();
    }

    private Object execute(Method method, byte[]... args) {
        if (method.getParameterTypes().length > 0 && method.getParameterTypes()[0] == byte[][].class) {
            return ReflectionUtils.invokeMethod(method, this, args);
        }
        if (args == null) {
            return ReflectionUtils.invokeMethod(method, this);
        }
        return ReflectionUtils.invokeMethod(method, this, Arrays.asList(args).toArray());
    }

**Comment by mrniko** [comment]
Can you share some test code to confirm this issue?

**Comment by mrniko** [comment]
Fixed. Thanks for report!
