### ISSUE TITLE
Regression: 3.16.8 refactor on deleteByPattern does not always delete keys correctly.

### ISSUE THREAD

**Issue by mcowger** [redisson/redisson#4157]
**Expected behavior**
All keys matching pattern are deleted

**Actual behavior**
Keys are not deleted

**Steps to reproduce or test case**
```
internal fun purge() {
        client.keys.deleteByPattern("$metadataNamespace*")
        client.keys.deleteByPattern("$valueNamespace*")
    }
 ```

The above code works correctly on 3.16.7 to delete all keys matching 2 patterns we pass in.  On 3.16.8 the keys are not deleted.

**Redis version**
6.2.6

**Redisson version**
3.16.8 

**Redisson configuration**

```
RedisDataShelf.Builder(
        "test",
        defaultTtl,
        client,
        NullCryptApi(),
        TemporaryFileStore(Files.createTempDirectory("RedisDataShelfTest"))
    )
    ```

**Comment by tyrantkhan** [comment]
I can also reproduce this -- running redis 6.2.2 and redisson 3.16.8

**Comment by mrniko** [comment]
Do you use Redis Cluster?

**Comment by mrniko** [comment]
Fixed. Thanks for report!
