### ISSUE TITLE
Is Rbatch excute operation atomic?

### ISSUE THREAD

**Issue by jianwenl** [redisson/redisson#4160]
I have keys in array of ByteArray (ByteArray for each key) and I am wondering if redisson enable returning value/timeout/null(miss) for different key with batch execute. Would batch support this? Or batch.execute() is just an atomic operation and will fail for all batch once a key is missed?

eg:

```
val batch = redissonClient.createBatch();
keys.foreach(key -> batch.getBucket(key).async.get();
val vals = batch.excute().getResponse()
```

**Comment by mrniko** [comment]
> Would batch support this? Or batch.execute() is just an atomic operation and will fail for all batch once a key is missed?

RBatch execution depends on `BatchOptions.executionMode` setting. If any batched command executes with error it won't cancel execution of other succeeded commands.
