### ISSUE TITLE
Respecting serialVersionUID 

### ISSUE THREAD

**Issue by gishroni** [redisson/redisson#4166]
I am saving and later retrieving a serialized object using an RBucket. When doing so, the serialVersionUID has no effect - redisson tries to retrieve and de-serialized the object and throws an exception it this fails. Is this done this way deliberately? Is there a way to make redisson respect the serialVersionUID, or do I need to serialize and de-serialize  the object myself?

**Comment by mrniko** [comment]
> Is this done this way deliberately? Is there a way to make redisson respect the serialVersionUID, or do I need to serialize and de-serialize the object myself?

No. It depends on codec you use.
