### ISSUE TITLE
Session Attributes not synced  - 2 tomcats without sticky session - Read mode REDIS

### ISSUE THREAD

**Issue by arivazhagan-jeganathan** [redisson/redisson#4170]
https://github.com/redisson/redisson/blob/e0d9c18e06e5e58e717e1698beef2cdabf8076fa/redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java#L483

Is this condition here restricting REDIS read mode from syncing attributes between tomcats utilizing same JSESSIONID for the same user?

1. Have two tomcats running same application. Sticky session disabled.
2. Redission tomcat session manager configured (version 3.16.4)
3. Scenario:
Tomcat1 --> updates a attribute in Session.
After 1 second, Tomcat2 --> reads the same attribute in session but do not have updated value but instead it reads the old value.

@mrniko could you please help?
Please help on fixing this scenario.

**Comment by mrniko** [comment]
can you share RedissonSessionManager settings?

**Comment by anubha16** [comment]
We appear to be facing a similar issue.

For this use case do we need to set broadcastSessionEvents="true"?
