### ISSUE TITLE
Redisson threw MOVED redirection loop detected

### ISSUE THREAD

**Issue by trajano** [redisson/redisson#4171]
There's an existing closed bug https://github.com/redisson/redisson/issues/1548 that seems to be manifesting in my installation.  I'm using AWS Managed Redis CLUSTER with Hibernate.

> ERROR [mylj,6221345d0f4ad9a5bd79127fd4f5f470,ef81dea77c5f0729] 1 --- [nio-8080-exec-2] org.redisson.hibernate.RedissonStorage : MOVED redirection loop detected. Node redis://10.95.240.133:6379 has further redirect to redis://10.95.240.133:6379

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/4144
