### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by guojian0614** [redisson/redisson#4174]
org.redisson.connection.SentinelConnectionManager
row  175   break;  is bug 
 it let this code always error.
     throw new RedisConnectionException("SENTINEL SENTINELS command returns less than 2 nodes! At least two sentinels should be defined in Redis configuration. Set checkSentinelsList = false to avoid this check.", lastException);

**Comment by mrniko** [comment]
`Set checkSentinelsList = false to avoid this check`

**Comment by guojian0614** [comment]
> `Set checkSentinelsList = false to avoid this check`
but I want to use redis sentinel config  auto set redission sentinel config
and not this property in redis sentinel config .

**Comment by guojian0614** [comment]
> sentinel

![image](https://user-images.githubusercontent.com/29422500/156980213-673ccf17-8d12-4851-94bd-fec3b191e9e2.png)
this is my RedisProperties ，i want if take effect on redisson

**Comment by guojian0614** [comment]
> `Set checkSentinelsList = false to avoid this check`

https://github.com/redisson/redisson/issues/4174#issuecomment-1060194722

this is my redis config, i want it take effect on redisson and no other config.

**Comment by guojian0614** [comment]
> `Set checkSentinelsList = false to avoid this check`

spring.redis.sentinel.master=mymaster
spring.redis.sentinel.nodes=ip:port
spring.redis.sentinel.password=pass

this is my redis config, i want it take effect on redisson and no other config.
