### ISSUE TITLE
Get values of all keys matching a given pattern

### ISSUE THREAD

**Issue by lucifercr07** [redisson/redisson#4175]
Is there a way to retrieve the value of all the keys matching the given pattern?
Also, can it be generalised to any key type? I'm able to get keys matching the pattern but how can we get all the values at once too?
Below is code snippet, however here I'm calling get for each key:
```
public void getRateLimiterKeyValues() {
        String pattern = API_RATE_LIMITER_KEY.concat("*");
        Iterable<String> keys = redisson.getKeys().getKeysByPattern(pattern);
        String[] cache = StreamSupport.stream(keys.spliterator(), false).toArray(String[]::new);

        for (String key : cache) {
            log.info("Key: {} value: {}", key, redisson.getRateLimiter(key).getConfig().toString());
        }
    }
```

**Comment by mrniko** [comment]
> Is there a way to retrieve the value of all the keys matching the given pattern?

This feature isn't supported by Redis
