### ISSUE TITLE
when i set waitTime=0 in multi lock , it fail

### ISSUE THREAD

**Issue by hachikozjq** [redisson/redisson#4177]
about [issue#4033](https://github.com/redisson/redisson/issues/4033),I don't need to wait,so i set waittime=0,but the result is failure,why Rlock set waittime=0 result is successful?i need get the lock fail,end business at once.
see source code,when waitime=0,leaseTime assignment zero.
![image](https://user-images.githubusercontent.com/36358868/157382007-ddc898c9-df54-46cd-b542-31dfaf57ba89.png)

**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
6.2.6
**Redisson version**
3.16.8
**Redisson configuration**

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4033
