### ISSUE TITLE
See the following error intermittently when trying to initialize the redisson client during the start of our Spring Application : "Unable to decode data. channel""

### ISSUE THREAD

**Issue by acharyaparag** [redisson/redisson#4180]
Redisson version : 
![image](https://user-images.githubusercontent.com/5388113/157700787-6c1c4370-61b1-44c4-9b1a-7011e88886d5.png)

To create Redisson Client : 

        // 1. Create config object
        Config config = new Config();
        config.setNettyThreads(64);
        config.useSingleServer().setAddress("redis://"+redisAddress+":"+redisPort).setPassword(redisPassword);
        return Redisson.create(config);

We have the following RMapCache beans that will basically create the RMapCache for us : 

@Configuration
public class RedisConfig {

    private final RedissonClient redissonClient;

    public RedisConfig(RedissonClient redissonClient) {
        this.redissonClient = redissonClient;
    }

    @Bean
    RMapCache<String, List<LocalizedData>> localizedDataCache (){return redissonClient.getMapCache(Constants.LOCALIZED_DATA_REDIS_HASH);}

    //MarketHierarchyRedisHash is the mapCache name
    @Bean
    RMapCache<String, MarketHierarchy> marketHierarchyCache (){return redissonClient.getMapCache(Constants.MARKET_HIERARCHY_REDIS_HASH);}

    @Bean
    RMapCache<String, MarketHierarchy> marketHierarchyCacheOld (){return redissonClient.getMapCache(Constants.MARKET_HIERARCHY_REDIS_HASH_OLD);}

 

}

Stacktrace : 

![image](https://user-images.githubusercontent.com/5388113/157709887-edc774b1-309a-4eb8-88e7-9c99d2395b01.png)

Expected : 
For our spring application to start without any issues.  The application fails to start because the redisson client cannot be initialized. This error is intermittent and difficult to reproduce all the time

**Comment by mrniko** [comment]
Please share log with `trace` logging for `org.redisson` package.

**Comment by acharyaparag** [comment]
Was able to reproduce the issue today . Please find the attached stacktrace with trace logging. I have noticed this issues occurs more often if I am trying to fetch data from Redis within a parallel stream. Is redisson client not thread safe?

**Comment by acharyaparag** [comment]
[redisson_stacktrace3.docx](https://github.com/redisson/redisson/files/8670494/redisson_stacktrace3.docx)
[redisson_stacktrace2.docx](https://github.com/redisson/redisson/files/8670497/redisson_stacktrace2.docx)

**Comment by mrniko** [comment]
It's caused by classNotFound exception. Check your classpath or specify correct classLoader in codec.
