### ISSUE TITLE
Reisson delay queue execution throw “ERROR org.redisson.QueueTransferTask -Unable to acquire connection! ”

### ISSUE THREAD

**Issue by newbieroutine** [redisson/redisson#4182]
Reisson version： 3.16.5
Redis: 5.0.3
In the process of using reisson, when reisson delay queue is normally used, it will be thrown during operation
![image](https://user-images.githubusercontent.com/28468501/158186357-5fd4bf8c-485c-4c68-a317-063d2d16afe3.png)
I confirm that the redis service is normal because there is no problem with another redisson delay queue. Normal after service restart

What are the possible causes of this problem? Is it because the connection is suddenly unavailable?
I need your help

**Comment by mrniko** [comment]
Try to increase connection pool size
