### ISSUE TITLE
[AWS ElastiCache Redis Cluster] Client is (sometimes) not recovering after packet loss

### ISSUE THREAD

**Issue by jakobjaks** [redisson/redisson#4196]
**Expected behaviour**
The Redisson client we have should recover to a 100% pre outage performance after a few minutes.

**Actual behaviour**
On some cases the Redisson client is unable to recover fully. The symptoms vary from occasion to occasion:
SET commands recover, but GET commands do not recover
SET and GET both recover, but with a 20% less throughput as the 20% keeps on failing.

Example where the GETs dont recover
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/33862541/159865378-f6635782-42f2-4e74-89b3-08feb981ae6d.png">

Example where the recovery is with less throughput
![image](https://user-images.githubusercontent.com/33862541/159865564-69a21be5-6efd-40b4-a47a-90a369bcf3ed.png)

Our configuration settings

      clusterModeEnabled: true
      connectionTimeout: 4000
      requestTimeout: 250
      retryAttempts: 1
      retryInterval: 200
      failedSlaveCheckInterval: 2000
      failedSlaveReconnectionInterval: 2000
      pingConnectionInterval: 250
      sslEnableEndpointIdentification: false
      keepAlive: false
      nettyThreads: 64
      failLimit: 5
      retryDelay: 15
      
The connection is done to a clustered elasticache redis with encryption in transit.
Redisson version 3.16.8.
The errors we have in the logs are the following

<pre>
! org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=9595, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1979550348 [redisClient=[addr=rediss://xx.xxx.xx.xxx:6379], channel=[id: 0x880b853b, L:/xx.xxx.xx.xxx:38332 ! R:xx.xxx.xx.xxx/1xx.xxx.xx.xxx:6379], currentCommand=null, usage=0], command: (PEXPIRE), params: [SS8d0b1981fe97fa771010c523cef1f2c1, 14400000] after 1 retry attempts
! at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:281)
! at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:61)
! at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:164)
! at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
! at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
! at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
! at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
! at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
! at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
! at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
! at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1017)
! at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:878)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
! at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
! at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
! at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
! at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
! at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
! at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
! at java.base/java.lang.Thread.run(Thread.java:829)
! Caused by: io.netty.channel.StacklessClosedChannelException: null
! at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
</pre>

<pre>
! org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@53c799c4[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size. Node source: NodeSource [slot=
9595, addr=null, redisClient=null, redirect=null, entry=null], command: (GET), params: [SS8d0b1981fe97fa771010c523cef1f2c1] after 1 retry attempts
! at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:189)
! at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
! at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
! at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
! at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
! at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
! at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

Could this be related to our configuration settings? We have tried multiple variants with alternating threads, attempts, timeouts etc. This configuration listed here seems to provide the best performance so far (less likely to not recover), but it still happens from time to time. We are not observing it in production environment yet, as its not rolled out, but we are mimicing outages by creating 5-10 minutes of 100% packet loss and then removing it.

**Comment by mrniko** [comment]
Did you try to increase connection pool size?

I need logs in `trace` logging level for `org.redisson` package.

**Comment by jakobjaks** [comment]
After bumping the thread count from 64 to 256 we saw a bit of an improvement, but after the 7th outage in a row there was an issue with recovering to a single node with GET commands.

<img width="916" alt="image" src="https://user-images.githubusercontent.com/33862541/159905869-aa1ec32c-0413-40f4-a559-0098e7c49e30.png">

Trace logs:

<pre>
DEBUG [2022-03-24 11:21:40,264] [][] o.r.c.ClusterConnectionManager: slot 9595 for SS8d0b1981fe97fa771010c523cef1f2c1
DEBUG [2022-03-24 11:21:40,264] [][] o.r.c.RedisExecutor: acquired connection for command (SET) and params [SS8d0b1981fe97fa771010c523cef1f2c1, PooledUnsafeDirectByteBuf(ridx: 0, widx: 992, cap: 1024)] from slot NodeSource [slot=9595, addr=null, redisC
lient=null, redirect=null, entry=null] using node 10.208.70.233/10.208.70.233:6379... RedisConnection@1186591432 [redisClient=[addr=rediss://10.208.70.233:6379], channel=[id: 0x570fb025, L:/10.208.69.86:39656 - R:10.208.70.233/10.208.70.233:6379], curr
entCommand=null, usage=0]
! org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@449fca4a[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size. Node source: NodeSource [slot=
9595, addr=null, redisClient=null, redirect=null, entry=null], command: (GET), params: [SS8d0b1981fe97fa771010c523cef1f2c1] after 1 retry attempts
! at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:189)
! at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
! at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
! at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
! at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
! at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
! at java.base/java.lang.Thread.run(Thread.java:829)
INFO  [2022-03-24 11:21:40,264] [][] DefaultTwimlProcessorModule: {"logLevel":"INFO","timestamp":"2022-03-24T04:21:40.264-0700","service":"message-processor","correlationId":"SM4d17c916ed2a44e78d59ad864e8de517","sid":["AC90cb241f3c604df7b9eb9508b5d5bcb4"],"tags":[],"nonTwilioIdentity":"","body":"","message":"[TwimlProcessor]Response={Method='POST' Response Code='200' Body length='0'}"}
DEBUG [2022-03-24 11:21:40,264] [][] o.r.c.ClusterConnectionManager: slot 9595 for SS8d0b1981fe97fa771010c523cef1f2c1
DEBUG [2022-03-24 11:21:40,264] [][] o.r.c.RedisExecutor: acquired connection for command (PEXPIRE) and params [SS8d0b1981fe97fa771010c523cef1f2c1, 14400000] from slot NodeSource [slot=9595, addr=null, redisClient=null, redirect=null, entry=null] using node 10.208.70.233/10.208.70.233:6379... RedisConnection@1233375658 [redisClient=[addr=rediss://10.208.70.233:6379], channel=[id: 0x99d2aee4, L:/10.208.69.86:39612 - R:10.208.70.233/10.208.70.233:6379], currentCommand=null, usage=0]
TRACE [2022-03-24 11:21:40,264] [][] o.r.c.h.CommandEncoder: channel: [id: 0xaa32703b, L:/10.208.69.86:38574 - R:10.208.69.81/10.208.69.81:6379] message: *2
$3
GET
$34
SS8d0b1981fe97fa771010c523cef1f2c1
</pre>

**Comment by mrniko** [comment]
I suggest to you to increase retryAttempts parameter in this case. Big enough value allows to survive failover without errors.

**Comment by jakobjaks** [comment]
But do you know why we might struggle to connect to a single node like this?

**Comment by mrniko** [comment]
it's a connection pool starvation. Try to increase connection pool size. If you see this problem only related to a single Redis node this might be connected to slower network link to this node and/or slower Redis node itself.
