### ISSUE TITLE
Add INFO command

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#420]

**Comment by jackygurui** [comment]
I have already done it as part of the travis-ci feature 

https://github.com/mrniko/redisson/blob/master/src/main/java/org/redisson/client/RedisClient.java#L161

**Comment by mrniko** [comment]
I thought to add it to `org.redisson.core.Node` object

**Comment by jackygurui** [comment]
OK. Will look into that.

**Comment by mrniko** [comment]
Done
