### ISSUE TITLE
Unreachable node not getting removed from quorum of redission

### ISSUE THREAD

**Issue by saravind-hotstar** [redisson/redisson#4203]
Redisson client of version of 3.10.0 is using 3 nodes of non clustered redis setup i.e 1 master and 2 slaves of AWS Elastic Cache using replicatedManager via DNS.

Observation
1 slave went was restarted off, we observed traffic to flow to 1 slave for more than 15 minutes without traffic flowing to second slave for longer duration. We have provided all 3 IPs using replication config

Please can you let us know the criteria for the nodes to be kept in exclusion list, is it just client timeouts after retries or what exactly.

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` package and share log output?
