### ISSUE TITLE
Listening to expiration or removal of entries

### ISSUE THREAD

**Issue by Flo0** [redisson/redisson#4205]
I would like to write a service that has the job of listening for expired/removed entries and persisting
them in a database. However i couldnt find a good approach because the RMapCache listeners are local.

Is there maybe a Redisson abstraction for listening to Redis keyspace notifications?

**Comment by mrniko** [comment]
You can use `org.redisson.api.listener.MapPutListener` or `org.redisson.api.listener.MapRemoveListener` listeners
