### ISSUE TITLE
The BlockingQueue listener can not be called and run?

### ISSUE THREAD

**Issue by TianqiHo** [redisson/redisson#4209]
My code :

![1648185747(1)](https://user-images.githubusercontent.com/52030959/160059629-dd8e5ef9-6edf-4d88-a341-51a2ec1711ed.jpg)

![image](https://user-images.githubusercontent.com/52030959/160059716-c9fbb986-3678-4999-8761-e8be0b28cbcd.png)

The two images is all my service code.
when i am testing for it, the log can not print. in picture 2 !!!!! Did I use it wrong? and where? Thanks a lot

my test code:
 
  
![image](https://user-images.githubusercontent.com/52030959/160061775-fb119c13-2757-4bd3-abd9-4cf45f7f8e24.png)

the queque is BlockingQueue

  
![image](https://user-images.githubusercontent.com/52030959/160061905-b58a7d43-3bc3-4313-a98d-9fd041bde339.png)

**Comment by mrniko** [comment]
Redis server `notify-keyspace-events` setting should contain El letters.
