### ISSUE TITLE
RLock.tryLock throw CancellationException

### ISSUE THREAD

**Issue by ClearLove007** [redisson/redisson#4210]
My service has been running steadily for a year. Recently, the redisson client has been upgraded  3.13.4 ---> 3.16.8. 
Then there are sometimes throw CancellationException when i tried to use RLock.tryLock()
`java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:235)`

This is the sample code I used
`redissonClient.getLock(WAIT_QUEUE_LOCK + i + "#").tryLock(3, 15, TimeUnit.SECONDS);`

I didn't find this problem in the test environment and pre production environment. And this problem never occurred on 3.13.4.

I don't know if I can make this clear, so what are the possible causes of this problem.

**Comment by ClearLove007** [comment]
Hi

**Comment by mrniko** [comment]
Can you share full stacktrace?

**Comment by mrniko** [comment]
Fixed! Thanks for report
