### ISSUE TITLE
RedissonLock in master/slave situation without wait

### ISSUE THREAD

**Issue by ZZhongge** [redisson/redisson#4211]
**Is your feature request related to a problem? Please describe.**
1. In our project, we use RedissonLock in master/slave redis. When the sync time bewteen master and slave goes high, the time that wait command cost get out of controll. In my env, it is between 20ms - 300ms, which influence the QPS of system, and other command. 
2. In master/slave architecture, the connection rebuild when master changed is automatic, could offer some hooks to let us do something when it happens ?
**Describe the solution you'd like**
1. could it become a setting ? we could decide that when we need wait command to garantee the consitency.
**Describe alternatives you've considered**

**Comment by mrniko** [comment]
You can use [slavesSyncTimeout](https://github.com/redisson/redisson/wiki/2.-Configuration#slavessynctimeout) setting
