### ISSUE TITLE
Partial/dupe keyspace notifications from redis-cluster when "SubscriptionsPerConnection" is higher than 1

### ISSUE THREAD

**Issue by fcbm** [redisson/redisson#4213]
**Expected behavior**
When connected to a redis-cluster and SubscriptionsPerConnection>1, the client should receive keyspace notifications regardless of the key hash slot

**Actual behavior**
The behavior is not systematic, these are the observed cases: 
- keyspace notifications are correctly received from all master nodes
- keyspace notifications are not received from a subset of the master nodes
- keyspace notifications are received multiple times from a master node

**Steps to reproduce or test case**
Setup a redis cluster as explained in : 
- https://redis.io/docs/manual/scaling/#creating-and-using-a-redis-cluster
- https://redis.io/docs/manual/scaling/#initializing-the-cluster

For each node provide the following configuration (port number varies from 7000 to 7005):
```
port 700[0-5]
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
notify-keyspace-events E$
protected-mode no
```

Run the following test:
```
Config config = new Config();
ClusterServersConfig clusterServersConfig = config.useClusterServers();
clusterServersConfig.setNodeAddresses(Arrays.asList(
        "redis://127.0.0.1:7000",
        "redis://127.0.0.1:7001",
        "redis://127.0.0.1:7002",
        "redis://127.0.0.1:7003",
        "redis://127.0.0.1:7004",
        "redis://127.0.0.1:7005"));
// clusterServersConfig.setSubscriptionsPerConnection(1);
RedissonClient c = Redisson.create(config);

c.getPatternTopic("__keyevent@*__:*", StringCodec.INSTANCE).addListener(String.class, new PatternMessageListener<String>() {
    @Override
    public void onMessage(CharSequence pattern, CharSequence channel, String msg) {
        System.out.println("Received event pattern " + pattern + " channel " + channel + " msg " + msg);
    }
});
Thread.sleep(600_000);
```

Connect to the redis cluster and update keys on all the master nodes:
```
127.0.0.1:7001> set a 1
-> Redirected to slot [15495] located at 127.0.0.1:7002
OK
127.0.0.1:7002> set b 1
-> Redirected to slot [3300] located at 127.0.0.1:7000
OK
127.0.0.1:7000> set c 1
-> Redirected to slot [7365] located at 127.0.0.1:7001
OK
```

When line "clusterServersConfig.setSubscriptionsPerConnection(1);" is commented (default 5) some notifications are lost ("c" key), some are dupe ("b" key). But the behavior is not systematic (see "Actual behavior"):
```
Received event pattern __keyevent@*__:* channel __keyevent@0__:set msg a
Received event pattern __keyevent@*__:* channel __keyevent@0__:set msg b
Received event pattern __keyevent@*__:* channel __keyevent@0__:set msg b
```

**Additional comments**
I may be wrong but, after some debugging, I had the feeling that the issue originates from the fact that keyspace notifications are handled as regular pubsub notifications. Instead, as reported in https://redis.io/docs/manual/keyspace-notifications/#events-in-a-cluster , the client should connect to every node (probably to every master would be enough).

**Redis version**
Redis server v=6.2.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=40f6d3ded4e576d9

**Redisson version**
3.17.0

**Redisson configuration**
See "Steps to reproduce or test case"

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5039
