### ISSUE TITLE
response timeout cause memory leak

### ISSUE THREAD

**Issue by sh-learn** [redisson/redisson#4215]
In my product environment,  the redisson happens error that cannot acquire connections. I increase the connection pool size but the same problem still occurs。

09:19:58.638 [redisson-timer-7-1] ERROR error - cache exception
org.redisson.client.RedisTimeoutException: Unable to acquire connection! RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@13d7b9a3(failure: java.util.concurrent.CancellationException)]Increase connection pool size. Node source: NodeSource [slot=15500, addr=null, redisClient=null, redirect=null, entry=null], command: (GET), params: [s_02240d6cf214b6fa5cd2cd9026b6d53703303de2bad16db01cf496ed2f3cfc7b19] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:189) [redisson-3.16.6.jar!/:3.16.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

I dump the jvm memory，analyze and find that there are many **RedissonPromise** object which hold cancel exception and exception stacktrace。these RedissonPromise object are held by the acquire connection callback runnable  objects in ConnectionPool. 

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/13534089/161363248-2d3601c7-0897-488e-8d59-240577fbbb79.png">

![image](https://user-images.githubusercontent.com/13534089/161363302-c103474a-bee3-4a86-9ad6-0ed35e8302e6.png)

I see that the callback will put in the listener queue of **AsyncSemaphore**  in source code,so I guess maybe a large number of Promises that acquired the connection were cancelled due to timeout for some reason, plus the retry situation, but corresponding 
 callback objects could not be released in the queue, which caused a memory leak.

And it is also observed that once it occurs, it cannot be recovered, and the jvm old age area gradually increases until the memory overflows.

### Expected behavior
Expect the redisson work fine the get connection

### Actual behavior
redisson happens error and cannot ger error，and found memory leak in the heapdump.

### Environment
JDK 1.8
Redisson 3.16.6
Redisson config：
![image](https://user-images.githubusercontent.com/13534089/161363886-86671518-fb85-4238-9e36-e544f88d7d0e.png)

I find my problem similar to the issue [#3703 ：](https://github.com/redisson/redisson/issues/3703)，but  my Redisson version higher.

This question has troubled me for a long time, I hope someone can reply, thank you very much.

**Comment by mrniko** [comment]
Fixed. Now it skips canceled tasks in the same thread and doesn't schedule it to a different thread which might be busy.

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.17.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8494163/redisson-3.17.1-SNAPSHOT.jar.zip)
