### ISSUE TITLE
Unable to acquire subscription lock

### ISSUE THREAD

**Issue by stillSahil** [redisson/redisson#4216]
During relatively high load (~150-250 requests per minute), I often see this error

```
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 3000ms. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribe.lambda$subscribe$2(PublishSubscribe.java:69)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I doubled the `subscriptionsPerConnection` from 5 to 10, the `subscriptionConnectionPoolSize` from 50 to 100, and the `connectionPoolSize` from 64 to 128, but it doesn't seem to have helped.

How can I go about diagnosing/debugging this? Do I need to just keep increasing these parameters till it works?

**Redis version**

6.x

**Redisson version**

3.16.8

**Redisson configuration**

```kotlin
config.useSingleServer().apply {
    path.toIntOrNull()?.also {
        database = it
    } ?: run {
        logger.warn { "Unable to parse database number: $path from redis configuration" }
    }
    
    subscriptionsPerConnection = 10
    subscriptionConnectionPoolSize = 100
    connectionPoolSize = 128
    timeout = 6000
}
config.nettyThreads = 64
```

I have also tried using Redisson versions 12.0, 13.0, 14.0, 15.0, 16.0 and 17.0 without luck.

**Comment by astmuc** [comment]
same problem after upgrading from a 3.11.x to 3.16.8. We had to fallback to old version. I can reproduce it with a jmeter high load scenario. But i have not yet an example project. We are using a RMap as cache and associated locks as guards of the cache. Concurrent accesses for the same cache key seems to trigger it. Means, one threads tries to fill the cache, one thread (another jvm) tries same and waits for the lock.

**Comment by mrniko** [comment]
@astmuc @stillSahil 

Example project will be useful to fix it.

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.17.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8449106/redisson-3.17.1-SNAPSHOT.jar.zip)

**Comment by astmuc** [comment]
i was able to start my stress-test with the SNAPSHOT jar and used the 3.17.0 pom. But either the memory requirements increased heavily or there is a memory-leak. The services went out of memory after few seconds.

**Comment by mrniko** [comment]
Can you share a memory dump and JMC session record (https://www.oracle.com/java/technologies/javase/products-jmc8-downloads.html) ?

**Comment by astmuc** [comment]
![image](https://user-images.githubusercontent.com/37765839/162577405-daba0075-9843-4582-a207-fec4819dff9f.png)

**Comment by astmuc** [comment]
we are using 
`    lock.lockInterruptibly(lockTimeoutInSeconds, TimeUnit.SECONDS);`
and this stress test provokes many cancels of a waiting thread like this. The cancel will create InterruptedException.

**Comment by stillSahil** [comment]
I used the SNAPSHOT jar, but the problem still remains.

Any tips on how I can go about diagnosing/debugging this would be much appreciated.

**Comment by mrniko** [comment]
@stillSahil 

Please try another version.

[redisson-3.17.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8494122/redisson-3.17.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
@astmuc 

Can you share any test code to reproduce it?

**Comment by mrniko** [comment]
@astmuc 

Unable to reproduce memory leak with this version https://github.com/redisson/redisson/issues/4216#issuecomment-1099871912

Here is my test:

```java
        ExecutorService e = Executors.newFixedThreadPool(16);
        for (int i = 0; i < 1000000; i++) {
            e.execute(() -> {
                RLock l = redisson.getLock("test");
                try {
                    l.lockInterruptibly(5, TimeUnit.SECONDS);
                    l.unlock();
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            });
        }
        e.shutdown();
        e.awaitTermination(100000, TimeUnit.SECONDS);
```

![image](https://user-images.githubusercontent.com/1104661/163528963-6d51a0b7-5843-4d56-be7d-e3ed46d44e08.png)

**Comment by CatalinAdlerDF** [comment]
Hi @mrniko 

We're facing the same problem as @stillSahil .
We're using redisson for distributed locks at a non trivial rate; we're using micronaut with kotlin and have attempted our best to keep everything async.

I do not know what triggered this storm of faults, all marked as `unable to acquire subscription lock` in xxx ms; we've tried bumping up to more than 10s timeout w/o any luck. 

Tried 17.1 w/o any luck as well.

We're on a managed redis and i plan to isolate 1 locking use case away to a separate, dedicated redis instance to rule out redis as the culprit.

Any suggestions on how to even diagnose this?

Thanks!

**Comment by stillSahil** [comment]
@mrniko I tried the other version as well, but no luck.

One strange thing I noticed is the timeout in the error message is inconsistent.
I see `Unable to acquire subscription lock after 123000ms` as well as `Unable to acquire subscription lock after 9000ms`, but I configured the timeout to 6000ms.

**Comment by CatalinAdlerDF** [comment]
I am also noticing a lot of WAITING states for threads, even though we're also using the async methods; makes me think there are some blocking calls under the hood.
For now i'll double check the thread pool configuration and bump up; we're on k8s & jvm17 with configured cpu requests and i'm thinking it might affect default thread pool configuration

**Comment by mrniko** [comment]
@astmuc 

These entries in LockPubSub object are created per unique subscription.

**Comment by mrniko** [comment]
@astmuc 

Unable to reproduce this case. Below is the test:

```java
        RedisRunner.RedisProcess runner = new RedisRunner()
                .port(RedisRunner.findFreePort())
                .nosave()
                .randomDir()
                .run();

        Config config = new Config();
        config.useSingleServer()
                .setSubscriptionConnectionPoolSize(1)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSubscriptionsPerConnection(1)
                .setAddress(runner.getRedisServerAddressAndPort());

        RedissonClient redisson  = Redisson.create(config);
        ExecutorService e = Executors.newFixedThreadPool(32);
        AtomicInteger errors = new AtomicInteger();
        AtomicInteger ops = new AtomicInteger();
        for (int i = 0; i < 500000; i++) {
            int j = i;
            e.submit(() -> {
                try {
                    String lockKey = "lock-" + ThreadLocalRandom.current().nextInt(1000);
                    RLock lock = redisson.getLock(lockKey);
                    lock.lockInterruptibly(5, TimeUnit.SECONDS);
                    Thread.sleep(ThreadLocalRandom.current().nextInt(100));
                    lock.unlock();
                    ops.incrementAndGet();
                } catch (Exception exception) {
                    exception.printStackTrace();
                    if(exception instanceof RedisTimeoutException){
                        return;
                    }
                    errors.incrementAndGet();
                }
            });
        }

        e.shutdown();
        assertThat(e.awaitTermination(150000, TimeUnit.SECONDS)).isTrue();
        assertThat(errors.get()).isZero();
```

**Comment by astmuc** [comment]
If you look into the test program attached you will see that the
subscriptions are implicitly declared by the MapCache locks. And the locks
are unlocked in a finally block.

Am Do., 21. Apr. 2022 um 11:38 Uhr schrieb Nikita Koksharov <
***@***.***>:

**Comment by mrniko** [comment]
@stillSahil 

> I see Unable to acquire subscription lock after 123000ms as well as Unable to acquire subscription lock after 9000ms, but I configured the timeout to 6000ms.

Overall timeout is calculating as follows: `config.getTimeout() + config.getRetryInterval() * config.getRetryAttempts();`

**Comment by mrniko** [comment]
@CatalinAdlerDF 

> I am also noticing a lot of WAITING states for threads, even though we're also using the async methods; makes me think there are some blocking calls under the hood.

Can you share a thread dump?

**Comment by mrniko** [comment]
@astmuc 

Still no luck.

```java
        for (int i = 0; i < 500000; i++) {
            int j = i;
            e.submit(() -> {
                try {
                    String map = "map-" + ThreadLocalRandom.current().nextInt(100);
                    RMapCache<Object, Object> m = redisson.getMapCache("map:" + map);
                    String lockKey = "lock-" + ThreadLocalRandom.current().nextInt(1000);
                    RLock lock = m.getLock(lockKey);
                    lock.lockInterruptibly(5, TimeUnit.SECONDS);
                    Thread.sleep(ThreadLocalRandom.current().nextInt(100));
                    lock.unlock();
                    ops.incrementAndGet();
                } catch (Exception exception) {
                    exception.printStackTrace();
                    if(exception instanceof RedisTimeoutException){
                        return;
                    }
                    errors.incrementAndGet();
                }
            });
        }
```

**Comment by astmuc** [comment]
Again: these simple tests are not the scenario I was speaking of. I
prepared this scenario as a test program for you and attached it in my
post. For me it was important: timeouts during lock and multiple jvms.

Am Do., 21. Apr. 2022 um 12:06 Uhr schrieb Nikita Koksharov <
***@***.***>:

**Comment by mrniko** [comment]
@astmuc 

> But one can see a kind of memory leak, when the pub-sub connection-pool is kept intentionally small

This is what I tried to reproduce from your description.

**Comment by stillSahil** [comment]
[Here](https://pastebin.com/6rAhYyRF) is a thread dump, showing many redisson threads in waiting states.

**Comment by CatalinAdlerDF** [comment]
In my case, this happens; this is the redisson exeuctor.

`Running, pool size = 128, active threads = 0, queued tasks = 5340, completed tasks = 3022`

i do not think it's related to the redis server as  i have multiple k8s pods working over the same redis and when i get a storm of exception on one pod, i do not have them on the others (or at least this is what i've observed till now).
So my thoughts are this is smth related to the jvm; my stacks look similar to @stillSahil s

This really smells of a thread starvation issue, but can't prove it.

**Comment by mrniko** [comment]
> Are there any processes happening from redisson against redis that can lead to blocking redis for enough time that commands timeout?

No. Can you share a jar with your classes so I could run them for test?

**Comment by CatalinAdlerDF** [comment]
> > Are there any processes happening from redisson against redis that can lead to blocking redis for enough time that commands timeout?
> 
> No. Can you share a jar with your classes so I could run them for test?

Not possible; proprietary code.
What else can I do to help?

**Comment by mrniko** [comment]
This issue may also cause this error https://github.com/redisson/redisson/issues/4294

**Comment by CatalinAdlerDF** [comment]
Any hopes to be able to address this soon?
It's still hurting our system.

**Comment by mrniko** [comment]
Please try 3.17.4 version

**Comment by Sovietaced** [comment]
> Please try 3.17.4 version, since it has fix for #4294

We have been experiencing this issue for years. I had raised a similar [thread](https://github.com/redisson/redisson/issues/3686) a while ago. It started happening to us again recently so I decided to search again and found this thread. 

For us the indication that something was very obviously broken on the client side is that the operation would timeout immediately despite claiming that the timeout was many seconds. 

> {"@timestamp":"2022-07-29T17:56:07.021Z","log.level":"TRACE","log.logger":"<redacted>","message":"Acquiring lock for fleet-info-cache:fleet-info-sync-task task...","process.thread.name":"fleet-info-cache:fleet-info-sync-task-0","context-str":"BvUGXmIa"}
> 
> {"@timestamp":"2022-07-29T17:56:07.021Z","log.level":"ERROR","log.logger":"<redacted>","message":"Encountered ExecutionContextException while acquiring lock and running task. Will reschedule...","error.type":"org.redisson.client.RedisTimeoutException","error.stack_trace":"org.redisson.client.RedisTimeoutException: Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters. 	at org.redisson.command.CommandAsyncService.syncSubscriptionInterrupted(CommandAsyncService.java:100) 	at org.redisson.RedissonLock.lock(RedissonLock.java:105) 	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:87) 	at io.opentracing.contrib.redis.redisson.TracingRLock.lambda$lockInterruptibly$5(TracingRLock.java:109) 	at io.opentracing.contrib.redis.common.TracingHelper.decorateThrowing(TracingHelper.java:261) 	at io.opentracing.contrib.redis.redisson.TracingRLock.lockInterruptibly(TracingRLock.java:109) 	at <redacted>.RedisExecutionContext.lockInterruptibly(RedisExecutionContext.java:46) 	... 9 common frames omitted Wrapped by:<redacted>.ExecutionContextException: Failed to lock lock 	at <redacted>.RedisExecutionContext.lockInterruptibly(RedisExecutionContext.java:50) 	at <redacted>.ScheduledTask.acquireLockAndRun(ScheduledTask.java:270) 	at <redacted>.ScheduledTask.taskLoop(ScheduledTask.java:250) 	at <redacted>.ScheduledTask.tracedTaskLoop(ScheduledTask.java:237) 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 	at java.util.concurrent.FutureTask.run(Unknown Source) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 	at java.lang.Thread.run(Unknown Source) ","error.message":"Subscribe timeout: (7500ms). Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.","process.thread.name":"fleet-info-cache:fleet-info-sync-task-0","context-str":"BvUGXmIa"}

We had very similar issues where seemingly only some of our kubernetes pods would experience this issue. It would remain throughout reboots. 

So I took this opportunity to try upgrading to 3.17.5 and it appears to have solved the problem!

**Comment by mrniko** [comment]
@Sovietaced 

Thanks for feedback!

**Comment by kanesee** [comment]
I am experiencing this issue. I'm on version `3.17.7`

**Comment by mrniko** [comment]
@kanesee 

Couple of PubSub connection handling issues were fixed in 3.19.0. Can you try it or the latest version?

**Comment by CheckWallet** [comment]
I am experiencing this issue. I'm on version 3.32.0.
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/4d4160d1-21e0-419c-b2e7-29b183aea25e">

**Comment by CheckWallet** [comment]
I am experiencing this issue. I'm on version 3.32.0.
![WX20241022-161347@2x](https://github.com/user-attachments/assets/277d1a6a-3b61-44a0-bd21-98dcd983bf37)

**Comment by mrniko** [comment]
You need to increase `subscriptionConnectionPoolSize` setting

**Comment by CheckWallet** [comment]
Ok, Thanks!  I have solve it.

**Comment by CheckWallet** [comment]
> You need to increase `subscriptionConnectionPoolSize` setting


Ok, Thanks! I have solve it.

**Comment by alianlyy** [comment]
how did you solve it

**Comment by nowindexman** [comment]
@CheckWallet   hi, how did you solve it

**Comment by mkulak** [comment]
I have the same issue in `3.52.0`.

**Comment by mradulqb** [comment]
I am facing the same issue in `Redisson 3.27.1` with these settings 
```
          .setScanInterval(2000)
          .setSubscriptionsPerConnection(50)
          .setSubscriptionConnectionPoolSize(400)
          .setSubscriptionConnectionMinimumIdleSize(30)
          .setSubscriptionTimeout(10000)
          .setTimeout(10000)
```
