### ISSUE TITLE
RExecutorService sometimes will stuck and cannot pickup task in 3.15.6

### ISSUE THREAD

**Issue by yeah007** [redisson/redisson#4220]
After Redission was upgraded to 3.15.6 from 3.14.1， it seems that sometimes RExecutorService sometimes will stuck and cannot pickup task. But in previous version, this issue didn't happen.

I see that there is a bug fixed in 3.16.3. Is that bug also in 3.15.6? Thanks.

**Comment by yeah007** [comment]
I tried to upgrade to 3.16.8 but blocked by interface change.
It seems that this function is not supported:
cronSchedule.getExpression().setTimeZone()

Any suggestions?

**Comment by mrniko** [comment]
> I tried to upgrade to 3.16.8 but blocked by interface change.
It seems that this function is not supported:
cronSchedule.getExpression().setTimeZone()

Fixed in 3.17.1 version

**Comment by mrniko** [comment]
Is it still reproducible?

**Comment by yeah007** [comment]
Will update later. Thanks.
