### ISSUE TITLE
ReadWriteLock aliyun not support

### ISSUE THREAD

**Issue by Zyred9** [redisson/redisson#4221]
aliyun.com:6379[5]> eval "redis.call('set', KEYS[1] .. ':1', 1)" 1 {oh}my_god
(error) ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression

aliyun.com:6379[5]> eval "local key=KEYS[1]..':1'; redis.call('set', key, 1)" 1 {oh}my_god
(error) ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression

aliyun.com:6379[5]> eval "KEYS[1]=KEYS[1]..':1'; redis.call('set', KEYS[1], 1)" 1 {oh}my_god
(nil)

aliyun.com:6379[5]>eval "return redis.call('get', KEYS[1])" 1 {oh}my_god:1
"1"

thinks!

**Comment by mrniko** [comment]
Please contact your Redis vendor. According to Redis spec there is are restrictions for keys generation in lua script.
