### ISSUE TITLE
Timezone of cron schedule is not supported in 3.16.8

### ISSUE THREAD

**Issue by yeah007** [redisson/redisson#4225]
I tried to upgrade to 3.16.8 but blocked by interface change.
It seems that this function is not supported:
cronSchedule.getExpression().setTimeZone()

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by yeah007** [comment]
Is this issue fixed?

**Comment by mrniko** [comment]
timezon isn't a part of CronExpression anymore. Here is how you can apply it: `org.redisson.api.CronSchedule#of(java.lang.String, java.time.ZoneId)`
