### ISSUE TITLE
RedissonLock.unlock

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#4227]
redisson-all-3.16.1 After the version
We have a lock on the line that has not been released

error log
java.lang.IllegalStateException: Sync methods can't be invoked from async/rx/reactive listeners
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:108)
	at org.redisson.RedissonObject.get(RedissonObject.java:82)
	at org.redisson.RedissonLock.unlock(RedissonLock.java:306)

java.lang.IllegalStateException: Sync methods can't be invoked from async/rx/reactive listeners
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:108)
	at org.redisson.RedissonObject.get(RedissonObject.java:82)
	at org.redisson.RedissonLock.tryAcquire(RedissonLock.java:143)
	at org.redisson.RedissonLock.lock(RedissonLock.java:97)
	at org.redisson.RedissonLock.lock(RedissonLock.java:69)

3.12.1  version
  @Override
    public <V> V get(RFuture<V> future) {
        try {
            future.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        if (future.isSuccess()) {
            return future.getNow();
        }

        throw convertException(future);
    }
    
3.16.1
@Override
    public <V> V get(RFuture<V> future) {
        if (Thread.currentThread().getName().startsWith("redisson-netty")) {
            throw new IllegalStateException("Sync methods can't be invoked from async/rx/reactive listeners");
        }

        try {
            future.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RedisException(e);
        }
        if (future.isSuccess()) {
            return future.getNow();
        }

        throw convertException(future);
    }

Why add this judgment
  if (Thread.currentThread().getName().startsWith("redisson-netty")) {
            throw new IllegalStateException("Sync methods can't be invoked from async/rx/reactive listeners");
        }

**Comment by mrniko** [comment]
Usage of sync methods in async/rx/reactive listeners causes delays in netty threads which in turn cause timeouts in Redis commands handling.

**Comment by wl980868110** [comment]
If the synchronous command is executed for a long time, the asynchronous Netty thread will time out
If the synchronous command execution time is very short, the asynchronous netty thread is normal

**Comment by wl980868110** [comment]
If the synchronous command is executed for a long time, the asynchronous Netty thread will time out
 If the synchronous command execution time is very short, the asynchronous netty thread is normal


I'm sorry, I didn't make myself clear




If the synchronous command execution time is very short, it doesn't affect the asynchronous Netty thread and it doesn't need to be determined. Are you doing this to prevent user actions from affecting your Redisson connection thread?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redisson/redisson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redisson/redisson] RedissonLock.unlock (Issue #4227)





 
Closed #4227.

**Comment by lengjiaxin** [comment]
这个有解决方案么，是否有配置可以放开限制。

**Comment by lengjiaxin** [comment]
Is there a solution for this problem? Is there a configuration that can release restrictions.

**Comment by wl980868110** [comment]
> Is there a solution for this problem? Is there a configuration that can release restrictions.

no

**Comment by wl980868110** [comment]
> Is there a solution for this problem? Is there a configuration that can release restrictions.

Direct restrictions, no configuration controls

**Comment by wl980868110** [comment]
> > Is there a solution for this problem? Is there a configuration that can release restrictions.
> 
> Direct restrictions, no configuration controls
You can take a look at the new edition
