### ISSUE TITLE
Support for Spring Data 3.0

### ISSUE THREAD

**Issue by theigl** [redisson/redisson#4236]
**Is your feature request related to a problem? Please describe.**

We are in the process of migrating our application to Spring 6, Spring Boot 3 and Spring Data 3. All of these dependencies are still pre-releases, but we would like to create a CI branch that tracks Spring development, so we can report any issues as soon as possible. There are many API incompatibilities, so Redisson doesn't work with Spring Data 3.x.

**Describe the solution you'd like**

Please add a `redisson-spring-data-30` module that can be used to test against Spring Data 3.x.

**Comment by olivierboudet** [comment]
As Spring Boot 3.0 is at RC1 and GA is planned for November, would it be possible to have also a pre-release of org.redisson:redisson-spring-boot-starter ? Thanks

**Comment by mrniko** [comment]
@olivierboudet 

I don't see this module in maven central

**Comment by YashchenkoN** [comment]
Spring Boot 3.0 has been officially released yesterday. Is there any timeline for `redisson-spring-data-30` release? Thanks in advance

**Comment by mrniko** [comment]
@YashchenkoN 

During next month

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/4689
