### ISSUE TITLE
java.lang.ClassCastException: class io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException cannot be cast to class java.lang.RuntimeException

### ISSUE THREAD

**Issue by lucianoRM** [redisson/redisson#4246]
The problem is in the MasterSlaveConnectionManager, initSingleEntry() method. If the catch catches a CompletionException with a cause that is not a RuntimeException, this happens.

**Expected behavior**
Throw the actual exception

**Actual behavior**
ClassCastException is thrown because CompletionException cause is not a RuntimeException

**Steps to reproduce or test case**
Try to connect to an unexistent host (something.com) with a MasterSlave configuration

**Redis version**
Not used

**Redisson version**
3.17.0

**Comment by mrniko** [comment]
Please share full stacktrace

**Comment by mrniko** [comment]
Fixed! Thanks for report
