### ISSUE TITLE
Example/API for ReJSON module

### ISSUE THREAD

**Issue by jagansankara** [redisson/redisson#4247]
Hi,

Is there any class or example code for read/write json data to redis which is stored using ReJSON module. I don't see any command related to ReJSON module in current Redission library.

Ex. Commands:
JSON.GET
JSON.SET

Am I missing the doc or is there work around to read JSON data type from Redis?

**Comment by mrniko** [comment]
Here it is https://github.com/redisson/redisson/wiki/6.-Distributed-objects#615-json-object-holder

**Comment by mrniko** [comment]
You can find JSON commands mapping on this page https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping
