### ISSUE TITLE
How to set expire for key in transaction

### ISSUE THREAD

**Issue by zengbotang** [redisson/redisson#4249]
if set expire for key in transaction, redisson will throw an Exception :
java.lang.UnsupportedOperationException: expire method is not supported in transaction

**Comment by mrniko** [comment]
try to use getAndSetAsync with timeToLive parameter.

**Comment by zengbotang** [comment]
> try to use getAndSetAsync with timeToLive parameter.

RBucket is ok, but RSet without this method
