### ISSUE TITLE
RMap.get() return String NOT Integer after RMap.addAndGet()

### ISSUE THREAD

**Issue by JisaKun** [redisson/redisson#4251]
Redisson version is 3.17.0 ,Here's code
``` java 
RMap<String, Integer> map = redissonClient.getMap("123", StringCodec.INSTANCE);
        Integer v1 = map.addAndGet("456", 1);
        Integer v2 = map.get("456");    // throws Excption
```

When dubug ,it shows that get() returin String 
![image](https://user-images.githubusercontent.com/10906570/164391623-2c9bea91-977d-4cfe-baa9-d2b91e82e1ef.png)

**Comment by mrniko** [comment]
You can't use addAndGet with StringCodec. Use IntegerCodec instead.
