### ISSUE TITLE
How to start Spring Boot application with Redisson when Redis Server is down/unreachable

### ISSUE THREAD

**Issue by rubasace** [redisson/redisson#4255]
One of our applications use `org.redisson:redisson-spring-boot-starter` dependency to apply some distributed locking against a single server Redis instance.

Recently, we ran into a bug in our IaC setup that caused the Redis instance to change its IP, causing this app to report itself as unhealthy because of the Redis `HealthContributor` implementation (as Redisson wasn't able to connect to the server anymore).

We disabled that contributor as stated on the documentation. The problem we are facing now is that new instances won't be able to start as the creation of the `Redisson` bean on `RedissonAutoConfiguration` fails if the address isn't reachable. This is a problem as it means that if the IP ever changes again or if Redis goes completely down, we won't be able to spin up new instances should we need to scale up the application.

Is there any way we can tell redisson to start regardless of the connection issues? This cache is an optimization on the main workflow but it shouldn't be blocking our apps by any means.

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/3042
