### ISSUE TITLE
How to provide Redis server's username and password when using with Sentinels?

### ISSUE THREAD

**Issue by AllwynJesu** [redisson/redisson#4260]
Hi,

I am using Redis 6.0 with 3 Server nodes and 3 sentinel nodes setup. There is no username and password configured for Sentinels but the Redis server requires a username and password i.e. Redis server uses a new ACL feature. From the [document](https://github.com/redisson/redisson/wiki/2.-Configuration/),  I can see there is an option to provide a username and password for cluster mode but I don't see it for sentinel mode. 

Below is my existing code

```
@Bean
	public RedissonClient createRedissonClient() {
		Config config = new Config();
		Integer conTimeOutInSecs = Integer.valueOf(env.getProperty(Constant.REDIS_CONNECT_TIMEOUT_KEY));
		Integer idleConnTimeout = Integer.valueOf(env.getProperty(Constant.REDIS_IDLE_CONN_TIMEOUT_KEY));
		String[] allSentinelNodesInfo = Arrays.stream(env.getProperty(Constant.REDIS_HOST_KEY).
				split(SENTINEL_NODES_DELIMITER)).map(String::trim).toArray(String[]::new);

		SentinelServersConfig sentinelConfig = config.useSentinelServers().setMasterName(env.getProperty(Constant.REDIS_MASTER_NAME_KEY))
				.addSentinelAddress(allSentinelNodesInfo);
		sentinelConfig.setClientName(env.getProperty(Constant.APPLICATION_NAME_KEY)).setConnectTimeout(conTimeOutInSecs).
				setIdleConnectionTimeout(idleConnTimeout);

		// This parameter is only used if lock has been acquired without
		// leaseTimeout parameter definition.
		config.setLockWatchdogTimeout(Long.valueOf(env.getProperty(Constant.LOCK_WATCHDOG_TIMEOUT_KEY)));
		RedissonClient client = Redisson.create(config);
		return client;
	}
```

BTW I am using Redisson 3.17.0 version.

**Comment by mrniko** [comment]
Here it is https://github.com/redisson/redisson/wiki/2.-Configuration/#password-3

**Comment by AllwynJesu** [comment]
@mrniko thanks for the link but it still does not take username. As you know, Redis ACL allows certain connections to be limited in terms of the commands that can be executed by user (username + password). Seems Redisson only supports **default user** in sentinel mode.
