### ISSUE TITLE
Search domain query failed

### ISSUE THREAD

**Issue by bharathkopparapu** [redisson/redisson#4263]
redisson version:-  redisson-3.17.1-SNAPSHOT.jar. connecting from on-prem to AWS

flink-oracle-taskexecutor-10-eqhttplrd001.out:05:28:56 | | ERROR | org.redisson.cluster.ClusterConnectionManager | Unable to resolve rediss://eqhv-prod-redis-sh-0002-002.maskedIP:6379
flink-oracle-taskexecutor-10-eqhttplrd001.out:io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'eqhv-prod-redis-sh-0002-002.maskedIP' failed to resolve 'eqhv-prod-redis-sh-0002-002.maskedIP'
flink-oracle-taskexecutor-18-eqhttplrd001.out:16:19:54 | | ERROR | org.redisson.cluster.ClusterConnectionManager | Unable to resolve rediss://eqhv-prod-redis-sh-0003-002.maskedIP:6379
flink-oracle-taskexecutor-18-eqhttplrd001.out:io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'eqhv-prod-redis-sh-0003-002.maskedIP' failed to resolve 'eqhv-prod-redis-sh-0003-002.maskedIP'
flink-oracle-taskexecutor-19-eqhttplrd001.out:01:40:01 | | ERROR | org.redisson.cluster.ClusterConnectionManager | Unable to resolve rediss://eqhv-prod-redis-sh-0002-001.maskedIP:6379
flink-oracle-taskexecutor-19-eqhttplrd001.out:io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'eqhv-prod-redis-sh-0002-001.maskedIP' failed to resolve 'eqhv-prod-redis-sh-0002-001.maskedIP'
flink-oracle-taskexecutor-1-eqhttplrd001.out:04:23:49 | NK-1mfla6redis4u | WARN | NBIDeviceInformEvent | ProcessInform_Flink_v2;497;Insert:219,UpdateSTBDtls:262,
flink-oracle-taskexecutor-1-eqhttplrd001.out:04:23:49 | NK-1mfla6redis4u | WARN | NBIDeviceInformEvent | ProcessInform_Flink_v2;171;PopulateFlowStatus:149,
flink-oracle-taskexecutor-2-eqhttplrd001.out:16:07:59 | | ERROR | org.redisson.cluster.ClusterConnectionManager | Unable to resolve rediss://eqhv-prod-redis-sh-0002-002.maskedIP:6379
flink-oracle-taskexecutor-2-eqhttplrd001.out:io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'eqhv-prod-redis-sh-0002-002.maskedIP' failed to resolve 'eqhv-prod-redis-sh-0002-002.maskedIP'
flink-oracle-taskexecutor-5-eqhttplrd001.out:17:49:02 | | ERROR | org.redisson.cluster.ClusterConnectionManager | Unable to resolve rediss://eqhv-prod-redis-sh-0003-002.maskedIP:6379
flink-oracle-taskexecutor-5-eqhttplrd001.out:io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'eqhv-prod-redis-sh-0003-002.maskedIP' failed to resolve 'eqhv-prod-redis-sh-0003-002.maskedIP'

**telnet looks good for the above dns.. only TCP is enabled at AWS for on prem servers not ping protocol. Do i need to disable anything?**

**Comment by mrniko** [comment]
Use this solution https://github.com/redisson/redisson/issues/4248#issuecomment-1107424810
