### ISSUE TITLE
Redisson 3.16.8 version occur MOVED redirection loop deleted exception when using Aliyun Redis Cluster.

### ISSUE THREAD

**Issue by Lacxner** [redisson/redisson#4267]
<img width="768" alt="redis" src="https://user-images.githubusercontent.com/35280133/165872211-39eb2738-9720-4d2e-bf5c-7f638890e80d.png">

**Comment by mrniko** [comment]
I need Redisson logs. Please set trace logging level for org.redisson package and share output.
