### ISSUE TITLE
How to connect to Redis Service using service name running in PCF cloud.

### ISSUE THREAD

**Issue by rohtashh** [redisson/redisson#4270]
Hi, We have a redis client project which is using Redisson client for all the operations, we are connecting it by providing redis://ip:port
But in higher environment we have the application configure on PCF cloud and there we have a redis service running with the name of **redis-service**. 
So, is there a way to connect to redis by just using this service name instead of ip:port?

**Comment by mrniko** [comment]
You can try natMapper for manual host:port binding.
