### ISSUE TITLE
CPU increase to 100% after a X period of time

### ISSUE THREAD

**Issue by ricardodocchio** [redisson/redisson#4274]
Hi

I'm using Redisson (v3.17.0) with a Redis (v6.2.6) in Sentinel Configuration. I am having this issue in which after a certain period of time our applications using Redisson get their CPU usage raised to 100%. This happens on three applications at different time and is always after certain amount of time after the deployment. The pod after a few minutes  of High CPU usage restarts because of the Liveness/Readiness probe

![imagen](https://user-images.githubusercontent.com/57111928/166470407-3c1f9a16-607e-423c-aa4f-0a8c103ba85a.png)

- I've deployed one of these applications without forwarding traffic to it and still the problem appeared
- I've deployed one of these applications without livenesss/readiness probe and executed manually the program and when the CPU went 100%, i saw that data was getting queued in the Receive Buffer Queue as the application was unable to get the data for **only one** of the connections to Redis, like one getting stuck make the others unusable. I was able to see this with the netstat command
- The logs only say that Redisson was unable to send Ping commands over the Channel for only one Redis  Node (the others connections seems to work ok)
![imagen](https://user-images.githubusercontent.com/57111928/166476064-240e3916-2ff5-4396-bb28-3316852a8f39.png)
- Setting nettyThreads to 16, 32 and 64 made this issue appear 7 hours after the program execution, setting it to 128 made it appear 12 hours instead of 7.

### I went through the FAQ section but we couldn't make it any better:
    All netty threads are busy, leading to delays in both Redis response decoding and sending commands to Redis 
I've increased the amount of nettyThreads but it doesn't fix the problem, only mitigate it.

    All connections are busy
I think the problem is only one connection that get stuck, but i dont know really how it works

    Redis server takes too long to respond the request.
The incident appears in a application while the others continue working without any problem. Also Redis can be queried manually without any visible problem.

    Sync methods invocation in async/reactive/rx listeners.
I dont think this is a problem because we deployed the application without forwarding traffic to it, and the only operations that it was executing were the one related to Sentinel Sync

### Configuration:
- This error appeared with the default settings, we only set sentinelAdresses, Username, Password & MasterName
- I tried to increase the amount of nettyThreads from 32, 64 and 128 but the error continues.
- I decreased the amount Slave Connections to 10 and Master connections to 5

I saw this problem is similar to others treated in this Bug tracker but the solution applied didnt worked for us, and instead of blindly changing configuration parameters i wanted to ask where you think this problem would come from:

**Comment by mrniko** [comment]
Did you try to record a session with JMC https://openjdk.java.net/projects/jmc/8/ ?

**Comment by mrniko** [comment]
Any update?
