### ISSUE TITLE
Redisson throwing exceptions after redis master fail over

### ISSUE THREAD

**Issue by spathros** [redisson/redisson#4278]
Hi,

We are using Redisson 3.17.0 and redis version 6.0.8. We have redis cluster mode setup with 3 masters and each master has about 4-5 replicas. When redis master fail over happens, redisson starts throwing exceptions that it is unable to write command into connection. Even after fail over completes (which is ~30s or so), the exceptions don't stop. Only a bounce of the instance that runs redisson resolves this error. This is affecting high availability of our service. We have pingConnectionInterval set to 5000 ms. Our read mode is only from Masters.

org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 81. Node source: NodeSource [slot=10354, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1578264320 [redisClient=[addr=rediss://-:6379], channel=[id: 0xb0f98c8c, L:/-:55678 - R:-/-:6379], currentCommand=null, usage=1], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, tenancyOcidToTenancyDoCache, redisson__timeout__set:{tenancyOcidToTenancyDoCache}, redisson__idle__set:{tenancyOcidToTenancyDoCache}, redisson__map_cache__last_access__set:{tenancyOcidToTenancyDoCache}, {tenancyOcidToTenancyDoCache}:redisson_options, 1652069836580, PooledUnsafeDirectByteBuf(ridx: 0, widx: 81, cap: 256)] after 2 retry attempts

Following is our redisson client config:
redisClientConfig: {
  endPoint: "rediss://$HOST_IP:6379"
  scanInterval: 1000
  masterConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  sslEnableEndpointIdentification: false
  idleConnectionTimeout: 30000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 2
  retryInterval: 300
  pingConnectionInterval: 5000
  keepAlive: true
  tcpNoDelay: true
  dnsMonitoringInterval: 5000
  threads: 16
  nettyThreads: 32
}

How can redisson recover from these exceptions without application restart? We tried increasing netty threads etc, but redisson does not recover from the fail over

**Comment by mrniko** [comment]
Could you set `TRACE` logging level for `org.redisson` package, run failover and share output?

**Comment by spathros** [comment]
[TraceLogs.log.zip](https://github.com/redisson/redisson/files/8665269/TraceLogs.log.zip)
@mrniko , here are the trace logs during failover which happens at 18:23 UTC. The logs are captured for 20 mins.
We notice that the old master that comes up as replica after fail over is bombarded with connection requests and has connection timeout errors

**Comment by mrniko** [comment]
The problem is that cluster state returns master node as slave which is still failed. But in cluster state this status is absent this is why Redisson continue to connect to this node.

**Comment by spathros** [comment]
oh, does redisson look at cluster nodes or cluster info command for this? Because cluster nodes provides status information as well
`6a5f2fb700ddf44a5a8c8938885fa2b0a2e8306b 10.5.130.245:6379@16379 slave,fail bc918b4bf7b97c76bb5d66cbe9b9c2052b970482 1652207010929 1652207008354 126 connected`

Currently, we are working around this issue by having a background thread, that pings masters every 60 secs and if not able to, it creates a new redisson client and shuts down the previous one

**Comment by spathros** [comment]
@mrniko Also we tried changing read mode to MASTER_SLAVE, however, latency of gets from cache shoot up with this read mode. Any ideas on why this could be so? Also, would this read mode help with auto recovery in case of fail over as opposed to read mode as MASTER?

**Comment by mrniko** [comment]
@spathros 

> does redisson look at cluster nodes or cluster info command for this?

Yes it does. According to your logs cluster state returns that slave isn't failed, so Redisson continue reconnecting.

**Comment by mrniko** [comment]
Please try attached version.

[redisson-3.17.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8727739/redisson-3.17.2-SNAPSHOT.jar.zip)

**Comment by spathros** [comment]
sure, will try this one out. Also, do you have any recommendations on why we see latency increase when we change the read mode to MASTER_SLAVE

**Comment by mrniko** [comment]
it might be because of replication lag

**Comment by waykar-prashant** [comment]
@mrniko is this fix pushed to master?

**Comment by mrniko** [comment]
@waykar-prashant It's already there. Update to the latest version

**Comment by spathros** [comment]
@mrniko we used redisson 3.17.3 version, now during failover we no longer see 'Can't add slave exception'. However, we see the below errors:
Unable to execute (CLUSTER NODES):
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (CLUSTER NODES), params: [], Redis client: [addr=rediss://10.5.110.35:6379]
at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)

and all cache operations fail with

Exception from getCheckDo:
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=770, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1727862963 [redisClient=[addr=rediss://10.5.110.35:6379], channel=[id: 0x0e7d508e, L:0.0.0.0/0.0.0.0:60034], currentCommand=null, usage=1], command: (HLEN), params: [checkNameToCheckCache] after 1 retry attempts
at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:281)

**Comment by spathros** [comment]
Redisson does not recover from fail over until we restart the application, any guidance on how to resolve this?

**Comment by mrniko** [comment]
@spathros Can you share trace logs?

**Comment by spathros** [comment]
[application.log.zip](https://github.com/redisson/redisson/files/8943928/application.log.zip)
@mrniko here are the trace logs from one of the hosts

**Comment by mrniko** [comment]
according to log node 10.5.130.229:6379 seems unstable. Redisson reconnected to it at 21:51:03. First timeout at 21:51:12 then we have `Can't connect to master` error at 21:51:29. It was marked as failed at 21:51:39

**Comment by mrniko** [comment]
I recommend to recreate the cluster

**Comment by spathros** [comment]
@mrniko that's the master node that had the failover. After the failover, redisson still tries to connect to it, instead of the new master.

**Comment by spathros** [comment]
@mrniko any ideas on how to get a smooth failover recovery from redisson ?

**Comment by mrniko** [comment]
try to increase retry attempts.

**Comment by spathros** [comment]
Increasing retry attempts/timeout won't work for us as we have scenarios where we need to fail fast and fall back to DB. Our cache lookups in API hot path and latency is important to us. Our timeout is set to 3s already and retry attempt is 1, which means it takes around 6s to fail already

**Comment by spathros** [comment]
@mrniko does redisson do exponential backoff in case of failure to connect to redis server?

**Comment by mrniko** [comment]
@spathros 

Can you create a separate issue on this?
