### ISSUE TITLE
Redis is changed to access with password, and trylock takes more time

### ISSUE THREAD

**Issue by XTUxiongda** [redisson/redisson#4281]
Redis used to access without password, and then upgraded to access with password. It was found that trylock took more than one second。
redisson version is 3.16.0
The configuration is as follows：
`config.useClusterServers()
                    .setPassword(password)
                    .setScanInterval(2000)
                    .addNodeAddress(xxxxx);
            return Redisson.create(config);`
so, I tried to reduce the reission version to 3.11.6, and the time consumption decreased significantly
I don't know what caused this. Is it the wrong way to use the new version?

**Comment by mrniko** [comment]
It was caused by introduction of WAIT command to sync with slaves. It seems that sync takes much time in your case.

**Comment by XTUxiongda** [comment]
> It was caused by introduction of WAIT command to sync with slaves. It seems that sync takes much time in your case.
Is there any way to solve it? I found this problem after version 3.14.1. Or can I only use the old version, and the new version all has this problem?

**Comment by XTUxiongda** [comment]
And My waittime input parameter is 0

**Comment by mrniko** [comment]
Could you set `TRACE` logging level for `org.redisson` package and share output?

**Comment by XTUxiongda** [comment]
[basic-porter-tadata-x.x8.31.50-0000] 2022-05-10 21:14:28.554 DEBUG 25384 [http-nio-8080-exec-6] [ClusterConnectionManager.java:751] slot 2875 for sync_tadata_lock
[basic-porter-tadata-x.x8.31.50-0000] 2022-05-10 21:14:28.555 DEBUG 25384 [http-nio-8080-exec-6] [ClusterConnectionManager.java:751] slot 2875 for sync_tadata_lock
[basic-porter-tadata-x.x8.31.50-0000] 2022-05-10 21:14:28.949 DEBUG 25384 [redisson-netty-2-2] [ClusterConnectionManager.java:466] cluster nodes state got from x.x.x.x/x.x.x.x:7001:
a45ecb9201e0bf48665ed7e5a9846cbe6d753x5 x.x.x.x:7006@17006 slave f5d943dbd5806937e204ee35ea5f6aa65e46a6ca 0 1652188467214 6 connected
40e866c9d83596f7d50ff09ee92370f580c9add9 x.x.x.x:7001@17001 myself,master - 0 1652188467000 1 connected 0-5460
f226329e04bda39971a532552f18a32bb2c1b7a8 x.x.x.x:7005@17005 slave ced813a2fd0db10432dbc999befd3709ac2234a2 0 1652188468217 5 connected
ced813a2fd0db10432dbc999befd3709ac2234a2 x.x.x.x:7002@17002 master - 0 1652188465208 2 connected 5461-10922
f5d943dbd5806937e204ee35ea5f6aa65e46a6ca x.x.x.x:7003@17003 master - 0 1652188466212 3 connected 10923-16383
eccdd6be867c3fc36a27f2c1cc105c98c2d08879 x.x.x.x:7004@17004 slave 40e866c9d83596f7d50ff09ee92370f580c9add9 0 1652188465000 4 connected

[basic-porter-tadata-x.x8.31.50-0000] 2022-05-10 21:14:30.415 DEBUG 25384 [redisson-netty-2-5] [RedisExecutor.java:522] connection released for command null and params null from slot NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=redis://xxx.xx.xxx.xxx:7001], nodeType=MASTER, firstFail=0]]] using connection RedisConnection@1857575476 [redisClient=[addr=redis://xxx.xx.xxx.xxx:7001], channel=[id: 0xd41a442c, L:/xx.xxx.xxx.xx:59598 - R:xxx.x.x.x/x.x.x.x:7001], currentCommand=null]

**Comment by XTUxiongda** [comment]
@mrniko can you help me on this queston?

**Comment by mrniko** [comment]
I reproduced your case only if masterauth is not set for slave nodes.

**Comment by XTUxiongda** [comment]
> I reproduce your case only if masterauth is not set for slave nodes.

thank you very much !  That's why.
