### ISSUE TITLE
Web UI for Jobs/Workers

### ISSUE THREAD

**Issue by 1cg** [redisson/redisson#4289]
Hi There,

I am looking at redisson as infrastructure for a Job-running system I am building and one thing I would like is a nice web UI that shows all the jobs and their current state (Queue, Running, Complete).

Looking at the code it looks like I would need to build infrastructure for Job state on top of the current RExecutorService.  I am perfectly fine with that, I just want to make sure I'm not replicating work!  Can you confirm that for me?

Secondly, I'd like to have "named" cron jobs that are sync'd with a cron tab file on server startup.  It looks very easy to create new cron-style jobs with Reddison, but is there a way to find existing cron jobs or a certain type so we can unschedule them if they have been removed (or renamed) in the crontab file?

Thank you, Redisson looks like an amazing piece of software.

**Comment by mrniko** [comment]
You can now specify task id https://github.com/redisson/redisson/issues/3707

Does it resolve the issue?

**Comment by 1cg** [comment]
Yep!  Thank you!
