### ISSUE TITLE
RMapCache - no way to listen for reconnection

### ISSUE THREAD

**Issue by ninja-** [redisson/redisson#4290]
**Is your feature request related to a problem? Please describe.**

I noticed that RMapCache allows subscribing to created/expired/removed/update events, which is useful, but there is no way to detect connection loss or reconnection, that means events have been missed, and the user doesn't know when to re-synchronize this state from scratch.

Also, I noticed that it's not allowed to implement several Entry*Listeners in one object because only first interface will be registered in addListener and others will be silently dropped.

**Describe the solution you'd like**
It would be useful to add onSubscribed()/onUnsubscribed() to MapEntryListener to allow to detect this in the same way as using `StatusListener` on the (hidden) underlying RTopics.

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Did you try to define https://github.com/redisson/redisson/wiki/2.-Configuration#connectionListener ?

**Comment by ninja-** [comment]
hmm I think I was afraid of a case when only one subscription connection drops and others are fine? or will this listener trigger on all kinds of connection disruptions?

**Comment by mrniko** [comment]
It's triggered on any kind of connection disruptions.

**Comment by ninja-** [comment]
then it looks like it solves my use case. thanks for help
