### ISSUE TITLE
How much blocking is there in the Synchronous API?

### ISSUE THREAD

**Issue by eoh-bse** [redisson/redisson#4292]
Hi my team is looking to switch to a non-blocking Redis client library. We are debating between Redisson and Lettuce. The important feature we are looking for is the non-blocking API.
I came across [this documentation for Lettuce](https://github.com/lettuce-io/lettuce-core/wiki/Asynchronous-API#impact-of-asynchronicity-to-the-synchronous-api). It basically mentions that Lettuce's synchronous API blocks the caller (as it should) but the layer below that (connection) is still non-blocking so other commands can still be executed on the same connection.
This can be very useful for us because this means we do not have to refactor our cache interfaces to be non-blocking and just switch the implementation to be able to get a lot of the benefits of a non-blocking API.
I am expecting a similar implementation by Redisson but I could not find an explicit documentation explaining this.
Would you be able to provide a thorough clarification on this topic?
Thank you

**Comment by mrniko** [comment]
All commands executed asynchronously and each sync method is only waiting the result. All works even with a single connection.
