### ISSUE TITLE
Redisson can't find slave in slave list after some app restarts

### ISSUE THREAD

**Issue by flavioschuindt** [redisson/redisson#4295]
**Expected behavior**

Redis deployed in sentinel mode in a Kubernetes cluster using bitname redis chart version ```16.8.9```(which uses redis server ```6.2.7```). After cluster restart, we should always have redis working as expected with no failures to find slaves.

**Actual behavior**

So, here is my setup:

I am using [netflix conductor](https://github.com/Netflix/conductor) which internally uses Redisson ```3.13.3``` inside a spring boot app. I am using version ```16.8.9```  of redis bitnami chart (which uses redis server ```6.2.7```) to deploy redis in a Kubernetes cluster in sentinel mode.

Things just work fine. Until eventually I restart the cluster...It nos always, but in some of the cluster reboots, sometimes I see those messages in redisson:

```java
2022-05-13 06:08:51.859 [redisson-netty-2-11] WARN  io.netty.util.concurrent.DefaultPromise [] - An exception was thrown by org.redisson.misc.RedissonPromise$$Lambda$1877/0x0000000840a9f040.operationComplete()
java.lang.IllegalStateException: Can't find conductor-redis-node-2.conductor-redis-headless.wo.svc.cluster.local/172.168.41.134:6379 in slaves! Available slaves: [[addr=redis://conductor-redis-node-0.conductor-redis-headless.wo.svc.cluster.local:6379], [addr=redis://conductor-redis-node-1.conductor-redis-headless.wo.svc.cluster.local:6379]]
```

Apparently, one of the slaves node is not reachable anymore and this is causing all communications to fail. Conductor simply can't rely on redis anymore to do any kind of operation as this stack trace is everywhere.

**Steps to reproduce or test case**

* Install a kubernetes cluster;
* Deploy Netflix conductor 3.4.1 (or any spring boot app that uses redisson ```3.13.3```);
* Restart the cluster multiple times;
* Try to do any operation in redis and there is a chance that above issue will show up after some restarts.

Conductor here is just one example. I believe this could happen with any app that is using redisson ```3.13.3```backend by redis ```6.2.7``` in a sentinel mode. I don't believe bitnami charts plays a role here as stack trace is coming directly from redisson, therefore I am opening this ticket here. Unless there is a hidden magic configuration in bitnami redis chart that I am not aware of.

**Redis version**

6.2.7

**Redisson version**

3.13.3

**Redisson configuration**

Programatic configuration

**Comment by mrniko** [comment]
Could you please try it with the latest version.
