### ISSUE TITLE
Is there an option to Read only and not write to master

### ISSUE THREAD

**Issue by lokeshg98** [redisson/redisson#4296]
Hi,
We are using Redisson replicatedServerConfig to connect to ElasticCache Redis. we want to only read from Replica/master and not write any data. Is there a way to disallow write using redisson client configuration or code. we are using the following server configuration.

`replicatedServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 30000
  retryAttempts: 15
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  scanInterval: 1000
  dnsMonitoringInterval: 1000
  pingConnectionInterval: 10000
threads: 16
nettyThreads: 32
codec: !<org.redisson.client.codec.StringCodec> {}
transportMode: "NIO"`

Thanks
Lokesh

**Comment by mrniko** [comment]
Your configuration is fine. Just don't use write operations.

**Comment by mrniko** [comment]
You can limit it with ACL https://redis.io/docs/manual/security/acl/
