### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#43]

**Comment by michelbetancourt** [comment]
Hi, Since this has been open for some time now, I am curious to know if this is actively being worked or if this is just a feature that is being considered?

**Comment by jackygurui** [comment]
@michelbetancourt If you are referring the feature to using Watch/Multi/Exec commands. I am afraid this is considered (close) to be depreciated by redis. [It is discouraged by the redis author](http://redis.io/topics/transactions#redis-scripting-and-transactions). 

You can use RLock to mimic the transaction behaviour and you will get much better performance. @mrniko has recently removed the last remaining internal usage of these commands and observed up to 400% performance gain. mrniko/redisson@4fcd54ec8cc7457434d0eb50de52274658625f3c

I can't see this feature been actually implemented any time in the near future, in my opinion.

**Comment by ittaiz** [comment]
How do you get performance gain when going from pessimistic locking (RLock) to optimistic locking (Watch)? Assuming you have rare collisions

**Comment by jackygurui** [comment]
In rare collision case, performance gain came from reduced network round trip.

**Comment by ittaiz** [comment]
Thanks for replying!
Don't you have similar network round trips when using RLock (lock/unlock)?

**Comment by jackygurui** [comment]
When use Lua script, the network round trip happens only once, and considering how fast redis is, network round trips can be the bottleneck for performance.

**Comment by ittaiz** [comment]
I see. I read the above command as moving to programatic RLock in jvm code and not to Lua script. I now understand.
Thanks!

**Comment by jackygurui** [comment]
Superseded with https://github.com/redisson/redisson/issues/1242
