### ISSUE TITLE
How does RRateLimiter set the expiration time of permits and values?

### ISSUE THREAD

**Issue by wubucheng** [redisson/redisson#4301]
Looking at the source, try converting RRateLimiter to RedissonRateLimiter and then use its expireAsync method:
```java
    public RFuture<Boolean> expireAsync(long timeToLive, TimeUnit timeUnit, String param, String... keys) {
        return super.expireAsync(timeToLive, timeUnit, param, new String[]{this.getRawName(), this.getValueName(), this.getClientValueName(), this.getPermitsName(), this.getClientPermitsName()});
    }
```
```java
   protected RFuture<Boolean> expireAsync(long timeToLive, TimeUnit timeUnit, String param, String... keys) {
        return this.commandExecutor.evalWriteAsync(this.getRawName(), LongCodec.INSTANCE, RedisCommands.EVAL_BOOLEAN, "local result = 0;for j = 1, #KEYS, 1 do local expireSet; if ARGV[2] ~= '' then expireSet = redis.call('pexpire', KEYS[j], ARGV[1], ARGV[2]); else expireSet = redis.call('pexpire', KEYS[j], ARGV[1]); end; if expireSet == 1 then result = expireSet;end; end; return result; ", Arrays.asList(keys), new Object[]{timeUnit.toMillis(timeToLive), param});
    }
```
This method seems to set the expiration time of permits and value, but it is found to be invalid after experiments, and only the expiration time of the current limiter can be set. Is there a way to deal with it?

**Comment by mrniko** [comment]
Can you describe the issue? Why expire methods RExpirable interface isn't enough?

**Comment by wubucheng** [comment]
First I use the method.like:
```java
rRateLimiter.expire(24, TimeUnit.HOURS);
```
But only the expiration time of the current limiter is valid
![image](https://user-images.githubusercontent.com/11130313/168976609-0a90fd0c-b1fb-42e6-a532-3dafb7ab5694.png)

I want to set  expiration time of the "permits" and "value",but they  expiration time is -1:
![image](https://user-images.githubusercontent.com/11130313/168977185-ba0a5cff-936b-47b9-bbc4-4d335a663858.png)
![image](https://user-images.githubusercontent.com/11130313/168977219-802af16c-3c93-449a-8f3b-326c4ab4dc39.png)

Is so much key in my redis, but want to invalidate them.
I had tried another method,like 
```java
expireAsync(long timeToLive, TimeUnit timeUnit, String param, String... keys) 
```
but also not work

**Comment by wubucheng** [comment]
> Which Redisson version do you use?

3.17.1

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test code.

```java
        RRateLimiter rateLimiter = redisson.getRateLimiter("test1");
        rateLimiter.trySetRate(RateType.OVERALL, 10, 10, RateIntervalUnit.SECONDS);
        rateLimiter.acquire();

        rateLimiter.expire(15, TimeUnit.SECONDS);

        Thread.sleep(20000);

        assertThat(redisson.getKeys().count()).isZero();
```

**Comment by wubucheng** [comment]
My test code,
```java
        RRateLimiter rateLimiter = redissonClient.getRateLimiter("test1");
        rateLimiter.trySetRate(RateType.OVERALL, 10, 10, RateIntervalUnit.SECONDS);

        
        rateLimiter.expire(100, TimeUnit.SECONDS);

        rateLimiter.acquire();

        Thread.sleep(20000);
```
initialized rateLimiter and set expiration time before invoke acquire method.
think that rateLimiter should be initialized expiration time first ,then use acquire or tryAcquire method.

**Comment by mrniko** [comment]
Fixed. Thanks for report
