### ISSUE TITLE
Task was picked up again if the task running time was more than 5 minutes

### ISSUE THREAD

**Issue by yeah007** [redisson/redisson#4302]
The default value of taskRetryInterval was configured to 5 minutes. If the task runs more than 5 minutes, this task with same executionId will be picked up again even same task is running in another thread. 

executor.schedule(task, 10000, TimeUnit.MILLISECONDS, 15552000000, TimeUnit.MILLISECONDS);

If don't configure task delay, this issue will not happen.
Is this behavior as expected if synchronously schedules a Runnable task with task delay?

I think we need task exclusive lock to prevent another thread same task.

@mrniko Thanks

**Comment by nanw1103** [comment]
The same issue as #4306
