### ISSUE TITLE
nly 0 of 1 slaves were synced

### ISSUE THREAD

**Issue by zsokolowski** [redisson/redisson#4305]
**Expected behavior**

no Exceptions

**Actual behavior**

level | ERROR
-- | --
loggerName | org.redisson.RedissonBaseLock
logMessage | Can't update lock {CURRENTLY_PROCESSED_ITEMS}:XQkzsm4yLHcuG8LoUKmxBQ:fairlock expiration
thread | redisson-netty-2-19
thrown.cause.class | java.lang.IllegalStateException
thrown.cause.localizedMessage | Only 0 of 1 slaves were synced
thrown.cause.message | Only 0 of 1 slaves were synced

We are using RedisQueues to read items 

**Steps to reproduce or test case**

**Redis version**

AWS 

**Redisson version**

3.17.0 and 3.17.1

**Redisson configuration**

```
        Config redissonConfiguration = new Config();
        redissonConfiguration
                .setNettyThreads(redisConfigurationModel.getNettyThreads())
                .useClusterServers()
                .setNatMapper(mapper)
                .setConnectTimeout(redisConfigurationModel.getConnectionTimeout())
                .setRetryAttempts(redisConfigurationModel.getRetryAttempts())
                .setMasterConnectionPoolSize(redisConfigurationModel.getConnectionPoolSize())
                .setRetryInterval(redisConfigurationModel.getRetryInterval())
                .setTimeout(redisConfigurationModel.getTimeout())
                .addNodeAddress(redisConfigurationNodeAddress);
```

I can provide exact values

**Comment by mrniko** [comment]
You need to set `checkLockSyncedSlaves = false`. If for some reason sync with slaves doesn't work.
