### ISSUE TITLE
RScheduledExecutorService.schedule(): duplicated task run

### ISSUE THREAD

**Issue by nanw1103** [redisson/redisson#4306]
**Expected behavior**
Scheduled task run once, with log:
One line of "MyTask start"
One line of "MyTask exit"

**Actual behavior**
The task is picked up twice:

> 18:37:52.013 [redisson-3-4] INFO MyTask - MyTask start: thread=redisson-3-4
> 18:37:57.064 [redisson-3-6] INFO MyTask - MyTask start: thread=redisson-3-6
> 18:38:02.014 [redisson-3-4] INFO MyTask - MyTask exit: thread=redisson-3-4

**Steps to reproduce or test case**
Run the following code:

```java
import lombok.extern.slf4j.Slf4j;
import org.redisson.Redisson;
import org.redisson.api.*;
import org.redisson.config.Config;

import java.io.Serializable;
import java.util.concurrent.TimeUnit;

@Slf4j
final class MyTask implements Runnable, Serializable {
    @Override
    public void run() {
        log.info("MyTask start: thread={}", Thread.currentThread().getName());
        try {
            Thread.sleep(10 * 1000);    // Task execution time > taskRetryInterval
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        log.info("MyTask exit: thread={}", Thread.currentThread().getName());
    }
}

public class Test {

    public static void main(String[] args) throws Exception {

        Config config = new Config();
        config.useSingleServer().setAddress("redis://127.0.0.1:6379");
        RedissonClient redisson = Redisson.create(config);

        ExecutorOptions executorOptions = ExecutorOptions.defaults()
                .taskRetryInterval(5, TimeUnit.SECONDS);    //taskRetryInterval < task execution time
        RScheduledExecutorService exec = redisson.getExecutorService("test", executorOptions);
        WorkerOptions workerOptions = WorkerOptions.defaults()
                .workers(2);    // If worker is 1, no bug. If worker is more than 2, does not increase the duplication.
        exec.registerWorkers(workerOptions);

        Runnable task = new MyTask();

        //RExecutorFuture future = exec.submit(task);   // If using submit(), no bug.
        RExecutorFuture future = exec.schedule(task, 1, TimeUnit.SECONDS);  //<--- problem here
        //RExecutorFuture future = exec.scheduleWithFixedDelay(task, 0, 20, TimeUnit.SECONDS);  //<--- problem here

        future.get();
        System.exit(0);
    }
}
```
**Redis version**
7.0.0

**Redisson version**
3.17.1

**Redisson configuration**
Default configuration with local single-node Redis server.

**Additional notes**

1. For method RScheduledExecutorService.submit(...), there's no such bug.
2. The bug applies to all delayed execution, including schedule, schedule with corn, scheduleAtFixedRate, scheduleWithFixedDelay.
3. The condition to reproduce the bug is, the taskRetryInterval must be smaller than task execution time, and there are more than 1 worker.
4. If there are more than 2 workers, the duplication number does not increase.

**Comment by yeah007** [comment]
Any ideas? Same issue happened for me.

**Comment by mrniko** [comment]
The problem is that retry interval is less than delay defined in task. After 5 seconds Redisson checks task status and run it again if it wasn't finished.

**Comment by djession** [comment]
@mrniko   Use @nanw1103 test case.Set retry interval 6 minutes,the problem still happened.....

**Comment by djession** [comment]
use RScheduledExecutorService.scheduleWithFixedDelay no problem. but use RScheduledExecutorService.schedule duplicated task run

**Comment by djession** [comment]
use 
`RScheduledExecutorService.scheduleWithFixedDelay` 
no problem. but use 
`RScheduledExecutorService.schedule (task, CronSchedule.of(""0/5 * * * * ?""))`
duplicated task run

**Comment by yeah007** [comment]
This issue does not only happen in 3.17.1, it also occurs in previous builds.

**Comment by mrniko** [comment]
With task retry timeout lower than actual task execution time this issue is always happen even with scheduleWithFixedDelay method.

Solution is to specify task retry timeout greater than expected task execution.

**Comment by yeah007** [comment]
Do we have other solutions to avoid this issue? We don't want to take long time to pick up failure tasks.

**Comment by yeah007** [comment]
I see that you have add this to the milestone 3.17.3? So I think we can figure out one solution to fix it in 3.17.3. Is it correct? Thanks.

**Comment by mrniko** [comment]
There is no solution except I suggested above.

**Comment by nanw1103** [comment]
@mrniko Could you please share some technical details to help us understand the rationale?

**Comment by mrniko** [comment]
the questions is how to determine "is the task still alive"

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/4306#issuecomment-1138275125
