### ISSUE TITLE
Command execution timeout for command: (AUTH), params: (password masked) - Redisson client

### ISSUE THREAD

**Issue by MuqtharMohammed** [redisson/redisson#4311]
I am trying to connect to redis server using redisson client in spring boot application. While connecting to redis using user name and password, getting the below exception

> Command execution timeout for command: (AUTH), params: (password masked), Redis client: [addr=redis://<host-name>:<port>]

**But I am able to connect to same redis instance with same credentials using redis insight but facing issue while accessing from spring boot application using redisson client.** 

I am using bitnami master slave redis set up. Loading the redis configurations as below

    Config config = new Config();
    
    config.useSingleServer().setAddress("redis://" + serverURI).setUsername("username").setPassword("password");
    
    return Redisson.create(config);

Providing the password as a normal string.

I tested with Lettuce redis client with the same host name and credentials. It is working fine. Looks like, this issue is with redisson client only. I am using redisson dependency as below ` 

<dependency>
 <groupId>org.redisson</groupId> 
  <artifactId>redisson-spring-data-26</artifactId>
 <version>3.17.1</version> 
</dependency>

Do we need to mask or unmask the password?

**Comment by MuqtharMohammed** [comment]
Today, I have added connection pool and time out configuration. Now the spring boot application is connecting to redis 5 out of 10 times. 

Getting intermittent time out issue. 

Do I need to add any other configurations??

		config.useSingleServer().setAddress("redis://" + serverURI).setUsername(userid).setPassword(password)
				.setClientName("client").setDatabase(0).setConnectionMinimumIdleSize(3).setConnectionPoolSize(5)
				.setIdleConnectionTimeout(300).setConnectTimeout(3000).setTimeout(3000);

**Comment by djession** [comment]
I resolved this problem.change your password format.

**Comment by MuqtharMohammed** [comment]
As of now, it is alphanumeric characters. Are you suggesting any specific format?
I am wondering why I am getting intermittent connectivity issue. I thought of network issue but I tested with Jedis/Lettuce client for the same host with the same credentials, it is working all the time without any issue.

**Comment by mrniko** [comment]
You need to specify password as plain text.

**Comment by mrniko** [comment]
> I am wondering why I am getting intermittent connectivity issue

Can you set `TRACE` logging level for `org.redisson` package and share output?

**Comment by MuqtharMohammed** [comment]
Since yesterday evening, i am not getting connectivity issue. I don't understand how it is working now. I have not changed any configurations.
I will keep an eye on this for couple of days and let you know the update.

**Comment by MuqtharMohammed** [comment]
> > Do we need to mask or unmask the password?
> 
> You need to specify password as plain text.

Yes. I am providing password as plain text only.

**Comment by MuqtharMohammed** [comment]
> Can you try version attached?
> 
> [redisson-3.17.3-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8777212/redisson-3.17.3-SNAPSHOT.jar.zip)

what is the change in 3.17.3 compare to previous versions?

**Comment by mrniko** [comment]
Class ConnectionPool:88 change: `Math.min(2, minimumIdleSize);`

**Comment by MuqtharMohammed** [comment]
Thanks for your swift response. Is this connection pool size will cause intermittent connectivity issue?
Now I am not getting any issue. It was intermittent issue but now it is working fine.
I will check for couple of days and provide you an update on this.

**Comment by mrniko** [comment]
@MuqtharMohammed 

> Is this connection pool size will cause intermittent connectivity issue?

This how similar issue https://github.com/redisson/redisson/issues/4245 was resolved

**Comment by MuqtharMohammed** [comment]
Yes. I saw this issue #4245, then only I tried with 3.17.1 version but no luck.

**Comment by mrniko** [comment]
Can you try attached version above?

**Comment by mrniko** [comment]
this version is already in maven repo - 3.17.3

**Comment by MuqtharMohammed** [comment]
I tested with 3.17.3 and it is working fine.
Hope this will fix the intermittent connectivity issue.
Thank you so much for your timely response and appreciate you help @mrniko

**Comment by mrniko** [comment]
Which Redis vendor do you use?

**Comment by MuqtharMohammed** [comment]
I am using redis bitnami with master slave along with redis sentinel.

**Comment by mrniko** [comment]
Thank you for clarifying. Fixed.
