### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by weiailuxueqi** [redisson/redisson#4312]
>  maven version

`
artifactId=redisson
groupId=org.redisson
version=3.17.1

`

>  error log:

`
      [ERROR] 2022-05-24 12:36:21.472 [redisson-netty-2-14] ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:171)
        io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:105)
        org.redisson.client.codec.StringCodec$1.encode(StringCodec.java:43)
        org.redisson.command.CommandAsyncService.encode(CommandAsyncService.java:680)
        org.redisson.RedissonObject.encode(RedissonObject.java:299)
        org.redisson.RedissonObject.encode(RedissonObject.java:264)
        org.redisson.RedissonList.addAllAsync(RedissonList.java:187)
        com.test.demo.OrderDataAsyncService.cacheOrderData(OrderDataAsyncService.java:90)
        com.test.demo.OrderDataAsyncService.redisPipelineHandlerCache(OrderDataAsyncService.java:57)
        com.test.demo.OrderDataAsyncService$$FastClassBySpringCGLIB$$9b796bcf.invoke(<generated>)
        org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        org.apache.skywalking.apm.plugin.spring.async.SWCallable.call(SWCallable.java:47)
        java.util.concurrent.FutureTask.run(Unknown Source)
        java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        java.lang.Thread.run(Unknown Source)

`

>  java simple code

`
final List<String> orderJsonList = Arrays.asList("001","002","003");

RBatch batch = redissonClientWrite.createBatch();
batch.getQueue("queue1001").addAllAsync(orderJsonList);
batch.getQueue("queue1002").addAllAsync(orderJsonList);
batch.execute();
`

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test:

```java
        for (int i = 0; i < 100000; i++) {
            List orderJsonList = Arrays.asList("001","002","003");
            RBatch batch = redisson.createBatch();
            batch.getQueue("queue1001").addAllAsync(orderJsonList);
            batch.getQueue("queue1002").addAllAsync(orderJsonList);
            batch.execute();
        }
```

**Comment by weiailuxueqi** [comment]
@mrniko Hello, this operation is accidental. I found that the previous version 3.15 also had this problem. Can we use discard?

**Comment by mrniko** [comment]
I managed to reproduce the issue only if RBatch execute method wasn't called. You need to call `discard()` method to cancel it.
