### ISSUE TITLE
Connections initialize endlessly

### ISSUE THREAD

**Issue by Fagam32** [redisson/redisson#4314]
Hello. We're using Redis in Sentinel mode. After upgrade from 3.15.4 to 3.16.6 and then to 3.17.2 we faced an issue with connections. 
![image](https://user-images.githubusercontent.com/43648449/170090112-eba0cd0c-efbe-45d0-87b4-4bba82582487.png)

We have some instances of application, but connections are increasing only on one instance. Netstat shows this on it. While others have 60 +- 4 
![image](https://user-images.githubusercontent.com/43648449/170090623-86a93a22-df66-46e6-b5a5-a6a3c3fb04f5.png)
Heap dump shows this
![image](https://user-images.githubusercontent.com/43648449/170226866-49cd0946-03aa-46ac-8db9-6b9039e96076.png)

Also, it spams to logs almost every second  `"24 connections initialized for <host>"`. It fixes by redeploying only

Configuration is default
```
  @Bean
  fun redisson(
    @Value("\${redis.hosts}") hosts: String,
    @Value("\${redis.password}") pass: String,
    @Value("\${redis.cluster-name}") clusterName: String,
    @Value("\${redis.port}") port: Int,
  ): RedissonClient {
    val config = Config().apply {
      useSentinelServers().apply {
        masterName = clusterName
        sentinelAddresses = hosts.split(",").map { host -> "redis://$host:$port" }
        password = pass
      }
    }
    return Redisson.create(config)
  }
```
UPD: 
Setting these values helped. But problem still exists
```
pingConnectionInterval = 0
masterConnectionMinimumIdleSize = 0
slaveConnectionMinimumIdleSize = 0
subscriptionConnectionMinimumIdleSize = 0
```

**Comment by mrniko** [comment]
Can you set `TRACE` logging level for `org.redisson` package and shout output from application start until you get this issue?

**Comment by Fagam32** [comment]
> Can you set `TRACE` logging level for `org.redisson` package and shout output from application start until you get this issue?

Ok. Do it asap

**Comment by Fagam32** [comment]
> Can you set `TRACE` logging level for `org.redisson` package and shout output from application start until you get this issue?

It spams 
`Skipped slave up redis://<slave1>:6379 for master redis://<master>:6379 differs from current redis://<master>:6379`
`Skipped slave up redis://<slave2>:6379 for master redis://<master>:6379 differs from current redis://<master>:6379`

**Comment by mrniko** [comment]
Check your Redis settings. Slave reports master which isn't the same as current one.
