### ISSUE TITLE
timer scheduler cannot work after several times

### ISSUE THREAD

**Issue by TDtianzhenjiu** [redisson/redisson#4324]
Config config=new Config();
        config.useSingleServer().setAddress("redis://localhost:6379").setPassword("redis");
        RedissonClient redissonClient=Redisson.create(config);
        RScheduledExecutorService rScheduledExecutorService
                =redissonClient.getExecutorService("service");

        rScheduledExecutorService.scheduleAtFixedRate((Runnable & Serializable)()->{
            log.info("running-----------");
        } ,0,3, TimeUnit.SECONDS);
        
        
        The code above shows

**redisson version: 3.17.3** 
after running several times it cannot print the log
the logs only show :
23:30:26.876 [redisson-netty-2-21] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: localhost/127.0.0.1 for master host: localhost
23:30:31.880 [redisson-netty-2-18] DEBUG org.redisson.connection.DNSMonitor - Request sent to resolve ip address for master host: localhost
23:30:31.880 [redisson-netty-2-21] DEBUG org.redisson.connection.DNSMonitor - Resolved ip: localhost/127.0.0.1 for master host: localhost

**BTW, Is there any diagram of the timer scheduler? how does it work?**

**Comment by mrniko** [comment]
Did you register workers?

**Comment by mrniko** [comment]
Can you share the code to reproduce it?
