### ISSUE TITLE
Annotation for listeners

### ISSUE THREAD

**Issue by Rostyslav26** [redisson/redisson#4332]
This may be a duplicate, but I did not find such a question. Is it possible to use annotations to better handle listeners, something like in RabbitMQ?

Example: 
```java
@RabbitListener(queues = "${name}") 
public void receiveMessage(Object message, Channel channel) {
// do something
}
```

Thank you!

**Comment by mrniko** [comment]
Does this annotation work only in Spring application?

**Comment by Rostyslav26** [comment]
Yep'org.springframework.amqp', name: 'spring-rabbit'
