### ISSUE TITLE
Exception in ali-cloud aliyuncs redis

### ISSUE THREAD

**Issue by kanteshkm** [redisson/redisson#4334]
Hi ,
I am getting below exception while connecting to ali-cloud redis, i am using redission to cache jpa entities , please let me know if there is any issue with default configs , i have just configured  entity as  `@Cache(region = "ProductEntityCache", usage = CacheConcurrencyStrategy.READ_WRITE) )`

**Exception:**
`nested exception is org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. channel: [id: 0x862b9d69, L:/18 - R:r-uf60a3ea4.redis.rds.**aliyuncs**.com/43.36.13.486:90] command: (EVAL), promise: RedissonPromise [promise=ImmediateEventExecutor`

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/1538#issuecomment-826583188
