### ISSUE TITLE
 Hope to support Redisearch

### ISSUE THREAD

**Issue by clover2022** [redisson/redisson#4337]
**Is your feature request related to a problem? Please describe.**

https://redis.io/docs/stack/search/
https://redis.com/blog/search-benchmarking-redisearch-vs-elasticsearch/

Redissearch+redisjason seems to replace elasticsearch

**Describe the solution you'd like**

Hope to support Redisearch

**Describe alternatives you've considered**

Currently used  https://github.com/dengliming/redis-modules-java/tree/master/redisearch

**Comment by bell0521** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> https://redis.io/docs/stack/search/ https://redis.com/blog/search-benchmarking-redisearch-vs-elasticsearch/
> 
> Redissearch+redisjason seems to replace elasticsearch
> 
> **Describe the solution you'd like**
> 
> Hope to support Redisearch
> 
> **Describe alternatives you've considered**
> 
> Currently used https://github.com/dengliming/redis-modules-java/tree/master/redisearch

**Comment by mrniko** [comment]
Done
