### ISSUE TITLE
Publish only to certain clients

### ISSUE THREAD

**Issue by Rostyslav26** [redisson/redisson#4339]
My application uses publish/subscribe with a many-to-many relationship, which means the sender can be a listener on the same channel. What this is for: I have two application instances and when some things are updated in one application, it needs to notify the second Redis client to do the same. Now I have a crutch with this. Is there a way to solve this with the library or the Redis commands themselves?

**Comment by mrniko** [comment]
Why can't you use RTopic?

**Comment by Rostyslav26** [comment]
unless the topic is published to all clients?

**Comment by Rostyslav26** [comment]
unless the topic is published to all clients?

**Comment by mrniko** [comment]
You could use topic per clients pair

**Comment by Rostyslav26** [comment]
how to do it?

**Comment by Rostyslav26** [comment]
how to do it?

**Comment by mrniko** [comment]
RTopic topic = getTopic("client1client2")
