### ISSUE TITLE
"Unable to write command into connection!" error and lack of documentation

### ISSUE THREAD

**Issue by artemik** [redisson/redisson#4342]
Hi,

I got `Unable to write command into connection!`  error (IP addresses hidden):

> Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@2122322579 [redisClient=[addr=redis://x.x.x.x:6379], channel=[id: 0xf906a399, L:/y.y.y.y:58729 ! R:x.x.x.x/x.x.x.x:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@49faaac(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://x.x.x.x:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (EXISTS), params: [my-lock:123456789] after 3 retry attempts

**Redisson configuration**
```
      .useSentinelServers()
      .setMasterName("redis-cluster")
      .setSlaveConnectionMinimumIdleSize(6)
      .setMasterConnectionMinimumIdleSize(6)
      .addSentinelAddress(...3 sentinels...);
```

**Steps to reproduce or test case**

From Redisson, I'm using only locking functionality in the following way. Nothing else is used:
```
    var lock = redissonClient.getLock(lockName);
    if (lock.isLocked()) {
      // ...
    }

    var lockTaken = lock.tryLock(60, 40, SECONDS);

    // ...

    lock.unlock();
```

As you can see, I only specified minimum connections size. I expect the max sizes to have default values of 24, as per documentation. I have ~10 max concurrent users. Pool sizes of 24 should be more than enough to cover it.

Like many others here, no luck resolving it. The advise I've seen on other tickets - increase nettyThreads - doesn't make sense, because 32 threads should be already enough to handle 10 concurrent users, and we can't just increase some random threads in production without realizing what implications are (documentation says nothing about it).

---

1. Please advise what could be the issue.

2. Please improve documentation, as it's far from clear on what's going on with pools and threads. These are the questions I get from the doc currently:

    1. What's the difference between connection pool size (default max 64) vs subscription connection pool size (default max 50)? Does it mean at max load I'll only have `64 - 50 = 14` connections available to non pub-sub requests? Or are they completely independent pools from each other?
    2. What's the difference between `nettyThreads` (default 32) vs `threads` (default 16)? Does one exhaust/use another?
    3. How `nettyThreads` or `threads` correlate to connections? If I have a lock request blocked waiting for another user to release the lock, does it mean it holds 1 pub-sub connection and 1 thread? Which thread? 10 blocked locks = 10 pub-sub connections and 10 threads?
    4. Why is default `nettyThreads` value 32 not set enough to cover max pub-sub connections of 50? (and neither max general connections of 64)? Am I misinterpreting (well, docs has zero info on that) usage of nettyThreads? What happens if I use all 50 pub-sub concurrently? Same question about `threads`.
    5. `masterConnectionMinimumIdleSize`:
        1. `Redis 'master' node minimum idle connection amount for each slave node.` - Why "each slave"? Aren't we talking about master here? It is a typo?
        2. `Redisson idle connections are remain for elected slave as master.` - "are remain" English grammar error (it just adds to overall confusion).
        3. `Because this node remains in slave connection pool but in non-active state.` - Node can not be in connection pool, because, well, only connection can be in connection pool? What master node has anything to do with slave connection pool? There are different settings for slave pool. What's non-active state?

Due to lack of these important questions, I'm completely unable to diagnose ``Unable to write command into connection!`` error myself. Since several users also reported the same error and claimed to have low load as well, and couldn't fix it, I hope this ticket gets a special attention.

Thanks.

**Redis version**
6.2.1

**Redisson version**
6.16.0

**Comment by mrniko** [comment]
> What's the difference between connection pool size (default max 64) vs subscription connection pool size (default max 50)? Does it mean at max load I'll only have 64 - 50 = 14 connections available to non pub-sub requests? Or are they completely independent pools from each other?

They are completely independent.

> What's the difference between nettyThreads (default 32) vs threads (default 16)? Does one exhaust/use another?

Please read wiki https://github.com/redisson/redisson/wiki/2.-Configuration#nettythreads https://github.com/redisson/redisson/wiki/2.-Configuration#threads

> How nettyThreads or threads correlate to connections? If I have a lock request blocked waiting for another user to release the lock, does it mean it holds 1 pub-sub connection and 1 thread? Which thread? 10 blocked locks = 10 pub-sub connections and 10 threads?

**nettyThreads** used for decoding/encoding data and **threads** used for topic listener invocation used by lock object.

> Command execution timeout for command: (PING)

It seems like there is a some problem with connection or all nettyThreads are busy at that moment.

**Comment by mrniko** [comment]
nettyThreads vs threads pools aren't connected to each other. Netty threads don't have state like "waiting for response", they just process it. The only reason netty threads  might be blocked - busy at Redis response decoding and command sending.  

If all nettyThreads are taken you'll get response timeout exception which may cause in turn unable get connection exception.

> Does it mean that once there are no slaves available, requests will go to master node and different connection pool? (with masterConnectionMinimumIdleSize and masterConnectionPoolSize settings)?

Yes.

> And, why then don't we have the same pool division for pub/sub connections pool?

Master node used as slave also has separate slave's pub/sub connection pool

**Comment by mrniko** [comment]
> I.e. a threads from threads pool calls a thread from nettyThreads pool and becomes blocked while waiting for the response. It means nettyThreads becomes a bottleneck here. P.S. Do threads become blocked at all or they just "schedule" the PING command to be sent for netty and then they're free to do anything else useful?

There are no blocking threads except user threads waiting for response. NettyThreads could be blocked only by long response decoding or data sending.

> If all nettyThreads are taken, would command fail immediately and be retried after 1500ms (as per the docs and default values)?

It will be faild on next retryAttempt.

**Comment by artemik** [comment]
@mrniko 
1. Earlier you explained `nettyThreads used for decoding/encoding data and threads used for topic listener invocation used by lock object`. Does it mean that besides user thread, there will be another internal redisson thread which will be blocked waiting for notification? Then, it means 1 blocked thread per 1 pub\sub connection. But then why default settings (thread=16, max pub\sub pool size = 64) don't match? It has no benefit having more threads than connections, does it?
2. Please clarify, when there are no nettyThreads available at the moment, redisson "thread" will fail the command immediately (internally) and try again as per retry attempt settings? It means when it's at max usage, when all threads are busy and therefore want some nettyThread, then count of nettyThreads pool size should be as much as there are threads? What benefit/sense does  it make to have more nettyThreads than threads? In what condition would a thread hold multiple nettyThreads?
3. In relation to the above point, as I noted, I'm using default settings for nettyThreads (32) and threads (16). I don't see how recommendation to increase nettyThreads helps here, because I already have them more than threads themselves.

**Comment by mrniko** [comment]
> Does it mean that besides user thread, there will be another internal redisson thread which will be blocked waiting for notification?

There are no blocking threads except user threads waiting for response. NettyThreads could be blocked only by long response decoding or data sending.

> Please clarify, when there are no nettyThreads available at the moment, redisson "thread" will fail the command immediately (internally) and try again as per retry attempt settings?

request will retain in tasks queue for nettyThreads.

> What benefit/sense does it make to have more nettyThreads than threads?

more free workers to handle tasks queue for nettyThreads

> In what condition would a thread hold multiple nettyThreads?

Thread doesn't hold multiple nettyThreads.
