### ISSUE TITLE
Redis server response timeout while trying to readAllKeySet from RMapCache

### ISSUE THREAD

**Issue by spathros** [redisson/redisson#4358]
We use redisson 3.17.0 and redis version 6. We have redis cluster set up. We have a RMapCache that has about 600k entries in it. We have a use case to read all keys into memory from this cache. However, the readAllLKeySet() fails with

org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 1 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (EVAL), params: [local s = redis.call('hgetall', KEYS[1]); local maxSize = tonumber(redis.call('hget', KEYS[5], 'max-..., 5, sotuDeviceCache, redisson__timeout__set:{sotuDeviceCache}, redisson__idle__set:{sotuDeviceCache}, redisson__map_cache__last_access__set:{sotuDeviceCache}, {sotuDeviceCache}:redisson_options, 1654927476566], channel: [id: 0x392893e0, L:/10.5.120.153:42932 - R:10.5.130.41/10.5.130.41:6379]

Our redis cluster config is as below

scanInterval: 1000
  masterConnectionPoolSize: 128
  masterConnectionMinimumIdleSize: 128
  sslEnableEndpointIdentification: false
  idleConnectionTimeout: 30000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 1
  retryInterval: 300
  readMode: "MASTER"
  pingConnectionInterval: 60000
  keepAlive: true

What is the recommended approach to read all keys from a cache which has many entries, without hitting a timeout?

**Comment by spathros** [comment]
Tried increasing timeout to 60000 , now the error we see is

org.redisson.client.RedisException: ERR Error running script (call to f_90fcfdb05f5b74bd69bd486619d1a8beeb29bf1b): @user_script:1: @user_script: 1: -READONLY You can't write against a read only replica.. channel: [id: 0xbf7856fa, L:/10.5.120.4:43012 - R:10.5.120.168/10.5.120.168:6379] command: (EVAL), promise: java.util.concurrent.CompletableFuture@3b140f41[Not completed, 1 dependents], params: [local s = redis.call('hgetall', KEYS[1]); local maxSize = tonumber(redis.call('hget', KEYS[5], 'max-..., 5, sotuDeviceCache, redisson__timeout__set:{sotuDeviceCache}, redisson__idle__set:{sotuDeviceCache}, redisson__map_cache__last_access__set:{sotuDeviceCache}, {sotuDeviceCache}:redisson_options, 1655093416087]

**Comment by mrniko** [comment]
can you share logs with `trace` logging level for `org.redisson` package?
