### ISSUE TITLE
Unfreeze failed with redis in kubernetes Part 2

### ISSUE THREAD

**Issue by mingjie-li** [redisson/redisson#4361]
this is a follow up of issue #4356 
I use the DNS class provided in the previous issue, but error not fixed.
reason is the ip is already resovled in the SentinelConnectionManager class and in the RedisClient.java we only connect with IP not the hostname, so the manipulation on the DNS TTL will not work as in RedisClient we resolve ip to ip.
Here is the new [trace.log](https://github.com/redisson/redisson/files/8889819/trace.log)

**Comment by mrniko** [comment]
`SENTINEL SLAVES` command returns host names according to your logs.

**Comment by mingjie-li** [comment]
```
I have no name!@test-redis-2:/$ redis-cli -h test-redis -p 26379 --user test --pass test sentinel slaves mymaster
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1)  1) "name"
    2) "test-redis-2.test-redis-headless:6379"
    3) "ip"
    4) "test-redis-2.test-redis-headless"
    5) "port"
    6) "6379"
    7) "runid"
    8) "9475c09b96641c338ab7f2fd49f9d20be09bbad7"
    9) "flags"
   10) "slave"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "266"
   19) "last-ping-reply"
   20) "266"
   21) "down-after-milliseconds"
   22) "60000"
   23) "info-refresh"
   24) "4568"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "2193237"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "ok"
   33) "master-host"
   34) "test-redis-0.test-redis-headless"
   35) "master-port"
   36) "6379"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "68525888"
   41) "replica-announced"
   42) "1"
2)  1) "name"
    2) "test-redis-1.test-redis-headless:6379"
    3) "ip"
    4) "test-redis-1.test-redis-headless"
    5) "port"
    6) "6379"
    7) "runid"
    8) "b8135318f6aa7a1648742358cc63d8d083b1a1ce"
    9) "flags"
   10) "slave"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "266"
   19) "last-ping-reply"
   20) "266"
   21) "down-after-milliseconds"
   22) "60000"
   23) "info-refresh"
   24) "679"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "2223403"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "ok"
   33) "master-host"
   34) "test-redis-0.test-redis-headless"
   35) "master-port"
   36) "6379"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "68526968"
   41) "replica-announced"
   42) "1"
```

**Comment by mingjie-li** [comment]
and this is the new [trace.log](https://github.com/redisson/redisson/files/8890223/trace.log) after applying the fix

**Comment by mrniko** [comment]
> I have no name!

    3) "ip"
    4) "test-redis-2.test-redis-headless"

    3) "ip"
    4) "test-redis-1.test-redis-headless"

**Comment by mingjie-li** [comment]
yes, this is the host name of the sentinel and redis server, the ip behind it can be changed, so we should not use ip directly in the connection manager or redisclient but use the hostname

**Comment by lbornov2** [comment]
@mingjie-li  - can't easily test that fix w/o a jar, so need it to be available in some maven repo before I can test on our side.

**Comment by mrniko** [comment]
@mingjie-li 

It will cause errors if host bounded to multiple ips and resolver returns a new ip each return. Also resolve IP each time may cause dns domain vendor throttling.

**Comment by mrniko** [comment]
Please provide dns logs from netty lib

**Comment by mrniko** [comment]
@mingjie-li 

All RedisClient instances are created with IP not hostname. I don't clue why it's not working

**Comment by mingjie-li** [comment]
> @mingjie-li
> 
> All RedisClient instances are created with IP not hostname. I don't clue why it's not working. When a new IP resolved by hostname sentinel add it as a new slave.

cause IP in the same host name can be changed if it's not static, think the vm is in a DHCP network. in kubernetes too, once the redis server get killed for some reason and be recreated later, it will not have same ip as before, but it will still have same hostname (like test-redis-2.test-redis-headless)
I will provide the trace.log for netty later tonight.

**Comment by mingjie-li** [comment]
> @mingjie-li
> 
> It will cause errors if host bounded to multiple ips and resolver returns a new ip each return. Also resolve IP each time may cause dns domain vendor throttling.

maybe we can add a new connectionmanager as a config for dynamic ip env ?

**Comment by mingjie-li** [comment]
> I need to understand what is missed in sentinel manager. Once hostname changes IP sentinel manager will discover it during scan.

it will, but the old ip is not removed, seems redisson try to slaveup the old ip too

**Comment by mrniko** [comment]
It shouldn't if resolver returned a new IP. Can you debug `org.redisson.connection.SentinelConnectionManager#checkSlavesChange` to figure out what is the reason?

**Comment by mingjie-li** [comment]
sure, will do it tonight and give you the nettty trace with
thank you for help

**Comment by mingjie-li** [comment]
Hi, i did some debug, and i think i found the reason, but i cannot 100% confirm.


**the scanInterval is 1 sec by default. it's maybe too small**


so when a redis server is down, it's could be marked as down by one sentinel server but still marked up by another.

in this case, first call of checkSlavesChange will freeze the node. but second call may try to unfreeze, (this also could be caused by some racing condition between async job)
during the unfreeze caused by the 2nd `checkSlavesChange`, as the node is dead, the connection failed so the unfreeze failed in exception, but the code here will bring some infinity loop 

https://github.com/redisson/redisson/blob/redisson-3.17.3/redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java#L145-L147

I try to set scanInterval to 5s this help, i don't see exception anymore
I also create a PR to fix this infinity loop.

**Comment by mrniko** [comment]
Thanks for your investigation. Let me try to reimplement this part.

**Comment by mrniko** [comment]
Please try version attached.

[redisson-3.17.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/8896963/redisson-3.17.4-SNAPSHOT.jar.zip)

Files patch

[fix_patch.txt](https://github.com/redisson/redisson/files/8896971/fix_patch.txt)

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/commit/45549df0bcba14fe0ada0b7cdb44699170547c56

Thanks much for testing. I'll make a release during this week.

**Comment by lbornov2** [comment]
@mrniko  thanks, will wait for the official release before re-testing.
