### ISSUE TITLE
Potential Refactoring

### ISSUE THREAD

**Issue by alvintanjianjia** [redisson/redisson#4363]
Hi,

I am currently doing some research on Estimating Time Taken for Software Refactoring. Redisson is one of my case studies being a highly popular project.

I have identified some packages with refactoring potential and their estimated time to refactor. Would appreciate your kind feedback on the appropriateness of the estimated time to refactor.

1. org.redisson.api - 354 hours
2. org.redisson - 274 hours
3. org.redisson.transaction - 94 hours
4. org.redisson.client.protocol.decoder - 92 hours
5. org.redisson.rx - 91 hours

I am specifically looking at potential for refactoring, such as breaking functions that are too long into shorter functions, or to remove code duplication.

Would you agree that there could be some modification to the code to make it better in the listed packages? And if so, is the estimated time appropriate to carry out the improvement? I will be grateful for any help you can provide.

Thank you.

Regards,
Alvin

**Comment by mrniko** [comment]
I usually refactor code time to time. I would be grateful if you find code which needs to be refactored.

**Comment by alvintanjianjia** [comment]
Hi @mrniko, 

Thanks for your reply! I would greatly appreciate if you would allow me to capitalize on your previous refactoring experiences.
## Developer's Experience
Can I trouble you to get a sample list of refactoring operations that you have previously carried out?
- Commit hash which the refactoring was carried out.
- Estimated time needed for the refactoring operation.

## Suggestions for code to be refactored
I am probably not qualified and experienced enough to point out the exact code needs to be refactored, given my limited knowledge of the project and codebase. Using **org.redisson.api** as an example, my model detects high coupling between org.redison.api and other packages.
Some suggestions based off the results from my model for **org.redisson.api** : 

1. org.redisson.api to be further broken down into smaller packages
- e.g. 1 smaller package RList, 1 smaller package RMap

2. To shift the api code back within the package, having each individual package manage its own api
- Moving RListRxJava back within io.reactivex.rxjava3.core to remove some dependencies

Once again, these are just suggestions based off the results from my model, which may not be contextually accurate. Would appreciate if you could provide some feedback.

Thank you very much in advance for your help!

Regards,
Alvin
