### ISSUE TITLE
Redisson brings whole RMap in in-memory while retrieving data

### ISSUE THREAD

**Issue by Pragya001** [redisson/redisson#4376]
Hi Team,
I was integrating my application to use Redis Server and used Redisson as a client to interact with Redis.
The data size that I have in Redis for a particular map is around 80K entries where each entry is around 20kb. 

I tried fetching the data by creating an RMap and fetching the key out of the Redis Cache and what I noticed is, redisson brings whole 80k entries in in-memory and then fetches out the key required.

I don't want Redisson to get all the entries first and get only the key from the Redis server. Is there a way I can achieve this? 

Can I only have the instance of my RMap in my application and fetch the entry directly from Redis Server instead of performing this find operations in my applications in-memory?

**Comment by mrniko** [comment]
> I tried fetching the data by creating an RMap and fetching the key out of the Redis Cache and what I noticed is, redisson brings whole 80k entries in in-memory and then fetches out the key required.

Please share code to reproduce it.

> Can I only have the instance of my RMap in my application and fetch the entry directly from Redis Server instead of performing this find operations in my applications in-memory?

Redisson doesn't fetch whole memory until you invoke method like readAllMap()

**Comment by Pragya001** [comment]
Following is the way I am reading the data from cache:

`public class MyCache {

    private static final String TQC_PRODUCT_STANDARDS_CACHE = "tqcProductStandardsCache";

    private final RMap<String, ProductStandards> tqcProductStandardsMap;

    public MyCache(@Autowired RedissonClient redissonClient) {

        MapOptions<String, ProductStandards> commentSubscriptionOptions = MapOptions.<String, ProductStandards>defaults()
                .writeMode(WRITE_THROUGH);

        tqcProductStandardsMap = redissonClient.getMap(TQC_PRODUCT_STANDARDS_CACHE, commentSubscriptionOptions);
    }

    public Map<String, ProductStandards> getCache() {
        return tqcProductStandardsMap.readAllMap();
    }

    public void putCache(String key, ProductStandards productStandards) {
        tqcProductStandardsMap.put(key, productStandards);
        log.info("TQC product standards entry updated for key {}", key);
    }

    @Synchronized
    public void clearCache() {
        log.info("Clearing TQC product standards cache");
        tqcProductStandardsMap.clear();
        log.info("TQC product standards cache cleared");
    }

    public ProductStandards getCacheByKey(String tqcProductStandardsKey) {
        return tqcProductStandardsMap.get(tqcProductStandardsKey);
    }

}`


Following are the configurations done to setup redisson:

`@Configuration
public class RedisConfigurations {

    @Autowired
    private Configurations configurations;

    private static final String LOCAL = "local";
    private static final String CLUSTER = "cluster";

    @Bean
    public RedissonConnectionFactory redissonConnectionFactory(RedissonClient redissonClient) {
        return new RedissonConnectionFactory(redissonClient);
    }

    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient(Config config) {
        return Redisson.create(config);
    }

    @Bean
    public CacheManager cacheManager(RedissonClient redissonClient) {

        Map<String, CacheConfig> cacheConfig = new HashMap<>();

        cacheConfig.put(TQC_PRODUCT_STANDARDS.getName(), new org.redisson.spring.cache.CacheConfig(0L, 0L));

        return new RedissonSpringCacheManager(redissonClient, cacheConfig);
    }

    @Bean
    public Config redissonConfig() {
        var config = new Config();

        if (LOCAL.equals(configurations.getRedis().getConnectionMode())) {
            var singleServerConfig = config.useSingleServer();
            singleServerConfig.setAddress(configurations.getRedis().getHost())
                    .setTimeout(configurations.getRedis().getTimeout())
                    .setConnectTimeout(configurations.getRedis().getConnectTimeout())
                    .setPingConnectionInterval(configurations.getRedis().getPingConnectionInterval())
                    .setKeepAlive(configurations.getRedis().isKeepAlive());
            Optional.ofNullable(configurations.getRedis().getPassword()).ifPresent(singleServerConfig::setPassword);
        } else if (CLUSTER.equals(configurations.getRedis().getConnectionMode())) {
            config.useClusterServers()
                    .addNodeAddress(configurations.getRedis().getHost())
                    .setPassword(configurations.getRedis().getPassword())
                    .setTimeout(configurations.getRedis().getTimeout())
                    .setConnectTimeout(configurations.getRedis().getConnectTimeout())
                    .setPingConnectionInterval(configurations.getRedis().getPingConnectionInterval())
                    .setKeepAlive(configurations.getRedis().isKeepAlive());
        }
        config.setUseThreadClassLoader(false);
        return config;
    }
}`

**Comment by mrniko** [comment]
```java
public Map<String, ProductStandards> getCache() {
    return tqcProductStandardsMap.readAllMap();
}
```

How I expected. You use  readAllMap() method.
