### ISSUE TITLE
Expiration time does not take effect

### ISSUE THREAD

**Issue by ycy1991** [redisson/redisson#4382]
When the transition time is set for atomlong, the inexplicable time becomes -1. Looking at the source code incr will not modify the time. The local multi-threaded test does not find it. After the project is sent to the development environment and runs for a period of time, the time will be set to -1. Submitting with Rbatch didn't work either
eg:
        RAtomicLong atomicLong = redissonClient.getAtomicLong(commonKey);
        if (atomicLong.isExists()) {
            atomicLong.incrementAndGet();
        } else {
          // Multiple threads may enter this step at the same time
            RBatch batch = redissonClient.createBatch();
            RAtomicLongAsync longAsync = batch.getAtomicLong(commonKey);
            longAsync.incrementAndGetAsync();
            longAsync.expireAsync(Duration.ofMinutes(1));
            batch.execute();
        }
how to solve this problem

**Comment by mrniko** [comment]
TTL isn't cleared after incrementation
