### ISSUE TITLE
add missing documentation for `sentinelsDiscovery` configuration property

### ISSUE THREAD

**Issue by philmtd** [redisson/redisson#4392]
I just found out about the `sentinelsDiscovery` configuration property in #3681. It was added in 2cd42449223cb3202de2f290c5f2630a91439b23.

It should be documented/mentioned on this page: https://github.com/redisson/redisson/wiki/2.-Configuration#27-sentinel-mode

Unfortunately I cannot submit PRs to the documentation or I would have edited it myself.

**Comment by mrniko** [comment]
Done
