### ISSUE TITLE
Update the frontend using Long Polling & Websocket

### ISSUE THREAD

**Issue by Exnadella** [redisson/redisson#4397]
I had a call with Redis Labs for a functionality request to update the Website (Front End) when a SortedSet is updated with the Counts.

They have suggested using the socket.io and Redis-adapter along with WebSocket & engine.io to implement a script that does the long polling to update the frontend continuously.  They also suggested that the requested feature is widely used and it should be possible to use pub/sub for the above scenario.

Can you provide us a sample that does this functionality using Redisson, Spring Boot & WebSocket?

https://socket.io/docs/v4/redis-adapter/
https://rsocket.io/guides/rsocket-js/client/rsocket-websocket-client

**Comment by mrniko** [comment]
I'm afraid there is no such example. It's more frontend related task
