### ISSUE TITLE
Allow injecting custom ConnectionManager

### ISSUE THREAD

**Issue by dvbobrov** [redisson/redisson#440]
Use case:
Redis clustering is implemented using [twemproxy](https://github.com/twitter/twemproxy), and its location should be discovered and monitored using Consul, etcd or whatever else. Currently I have to either use DNS monitoring (which is not an option in some cases) or wrap Redisson instances into a proxy to implement this. It would be better to have an option to implement such behavior in custom ConnectionManager.
I can make pull request with implementation, if anyone else needs this.

**Comment by mrniko** [comment]
OK, I'll think about it this issue. Could you please share your implementation?
Кстати, я вроде видел тебя на Joker-е осенью )

**Comment by dvbobrov** [comment]
I will, as soon as I write it, hopefully today.
Да, я там был

**Comment by dvbobrov** [comment]
OK, my idea is pretty straightforward, you can see the draft [here](https://github.com/ML-Works/redisson/commit/43fa605f9efc54e17e759752dbb729a5ab10f15f)

**Comment by mrniko** [comment]
I think it would be useful for Redisson to has twemproxy support. Then custom connectionManager is not needed. You will be able to config it like:
```java
Config config = new Config();
config.useTwemproxy()....
```

**Comment by dvbobrov** [comment]
Yes, that would work, too. But be aware, that using proxied connection will disable any multi-key, pub/sub and lots of other commands [full list](https://github.com/twitter/twemproxy/blob/master/notes/redis.md)

**Comment by mrniko** [comment]
Oh, man. Why do you use it then?

**Comment by mrniko** [comment]
implemented in https://github.com/redisson/redisson/pull/802
