### ISSUE TITLE
tryAcquire waits the entire timeout if the semaphore key is not already in redis

### ISSUE THREAD

**Issue by stevenhay** [redisson/redisson#4401]
```java
var semaphore = redissonClient.getSemaphore("accessTokenSemaphore");
var got = semaphore.tryAcquire(10, TimeUnit.MINUTES);
```

Using the above code, if the key 'accessTokenSemaphore' is not already in the redis cache, tryAcquire will wait the entire 10 minutes before returning false. After which I add some data to redis using:

```java
RBucket<SerializableToken> tokenCacheBucket = redissonClient.getBucket("token");
var token = tokenCacheBucket.get();

if (token == null || token.getAccessToken() == null || token.getExpiryEpoch() <= System.currentTimeMillis()) {
    token = getToken();
    tokenCacheBucket.set(token);
}
```

The second attempt at tryAcquire adds the key to Redis and returns true immediately. Am I missing something or doing something wrong? Thank you,

**Comment by Aurelien30000** [comment]
I can confirm this issue with a _new_ semaphore, might be caused by https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonSemaphore.java#L335

**Comment by Aurelien30000** [comment]
After more investigation you sould ensure that permits are correctly set, otherwise it _blocks_.
Adding ``RSemaphore#trySetPermits(1)`` fixed the issue for the semaphore creation.

**Comment by mrniko** [comment]
in your case `RSemaphore.trySetPermits()` or `RSemaphore.setPermits()` methods should be called before attempting an acquisition.
