### ISSUE TITLE
Questions related with connection pooling 

### ISSUE THREAD

**Issue by soyef** [redisson/redisson#4402]
What is the difference between **masterConnectionMinimumIdleSize** and **masterConnectionPoolSize**? 
Let say.. if we have 
masterConnectionMinimumIdleSize = 10
masterConnectionPoolSize=30

1. So these 10 idle connections are part of that master 30 connections or these 10 connections are excluded from the master connection pool?
2. If we have a master pool of 30, it means 30 connections will be initialized at the bootup time. At max, 30 concurrent connections can communicate with Redis.
In AWS elastic cache metrics, we can see the **total number of connections** graph around 50-100 times the connection pool.
What is the lifecycle of the connections in the connection pool? When and how new connections are created ?

3. What should be the ideal nettyThreads value for a 2-core Redis machine and 16-core application instance machine?
@mrniko

**Comment by mrniko** [comment]
> So these 10 idle connections are part of that master 30 connections or these 10 connections are excluded from the master connection pool?

They are part of 30 connections. There are 20 more could be established.

> If we have a master pool of 30, it means 30 connections will be initialized at the bootup time. At max, 30 concurrent connections can communicate with Redis.

Only idle connections will be initialized at the bootup time.

> What is the lifecycle of the connections in the connection pool? When and how new connections are created ?

They are created either at boot time or when more connections needed and pool isn't full or during reconnection.

> What should be the ideal nettyThreads value for a 2-core Redis machine and 16-core application instance machine?

It depends on how big is Redis data decoded by netty thread. Netty thread might be busy at data decoding. If you usually use small amount of data per response/request. Then connections amount/2 value is fine.
