### ISSUE TITLE
Questions about AWS MemoryDB compatibility

### ISSUE THREAD

**Issue by bigsky-033** [redisson/redisson#4404]
Hi team. I'm thinking about using AWS MemoryDB with Redisson. AWS says MemoryDB is compatible with Redis. But before adopting it, I would like to ask to Redisson team first.

- Have you ever tested the use of AWS MemoryDB with Redisson before?
- Is there some known issue on AWS MemoryDB with Redisson?
- Even if redisson team haven't tested it before, is there anything team can expect/suggest to be careful about?

Thanks.

**Comment by mrniko** [comment]
Redisson is compatible with MemoryDB. Let me know if you have any issues with it.
