### ISSUE TITLE
Cannot read value into a POJO while using TypedJsonJacksonCodec()

### ISSUE THREAD

**Issue by palaknagda** [redisson/redisson#4409]
I am trying to store a map in redis which is of the type RMap<String, JavaObject>
Here the value should be stored in a json format and while reading I should be able to convert the value back to JavaObject

My code:
```
//config
Config config = new Config();
config.setCodec(new TypedJsonJacksonCodec(String.class));

//init
RMap<String, Catalog> catalogRedisMap = redissonClient.getMap(REDIS_CATALOG_MAP);

//implementation
Catalog catalog = catalogRedisMap.get("sku");  //Gives ClassCastException

```

How do I ensure that I can read the value and deserialize in my POJO?

**Comment by yyy** [comment]
Try to use two-argument TypedJsonJacksonCodec constructor:
`config.setCodec(new TypedJsonJacksonCodec(String.class, Catalog.class));`

**Comment by palaknagda** [comment]
Thanks @yyy I can now read those values and deserialize directly in objects
