### ISSUE TITLE
Best Practices around Redis Cluster Configuration

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#4411]
Hi @mrniko 

We are using AWS Elasticache redis server in cluster mode with 3 shards and each shard having 1 primary and 1 replica (6 nodes in total).
As part of redisson client configuration, we have defined the nodesList containing the 3 master servers' endpoint.

Can you please suggest for the best practices around this. Should we include all the nodes as part of configuration(i.e both primary and replica nodes). I am asking this because we faced an issue when the elasticache cluster went to failover and it could not come out of failover as the redisson client was making a lot of connections and was not allowing primary to step down.

We are suspecting that since elasticache cluster went to failover and primary was stepping down (or getting decomissioned), redisson client kept on creating TCP connections with primary only and that caused a further delay in completing the failover.
Please suggest if we should go ahead to define all the nodes as part of redisson client configuration

**Comment by mrniko** [comment]
Even a single cluster node is enough to specify in configuration. 
Can you share logs with `trace` logging level for `org.redisson` package to get more info about the issue?

**Comment by jainyash88** [comment]
Thanks @mrniko for the response. I do not have the trace logs when the issue occured. The issue occured when AWS Elasticache cluster went in to failover and it remained in the failover state for a long time. Will collect the trace logs if we can reproduce the issue again. However if we specify just one or two nodes and if those nodes are down (while the cluster is still up), does that affect the client connectivity?

**Comment by mrniko** [comment]
> However if we specify just one or two nodes and if those nodes are down (while the cluster is still up), does that affect the client connectivity?

No
