### ISSUE TITLE
Is there a corresponding relationship between redisson and redis versions?

### ISSUE THREAD

**Issue by dengchenwei1981** [redisson/redisson#4413]
Is there a corresponding relationship between redisson and redis versions?

Can I use the lower version of redis but the highest version of redisson

**Comment by terryzxx** [comment]
> Based on [Netty](http://netty.io/) framework. [Redis](http://redis.io/) 3.0+ and JDK 1.8+ compatible.

**Comment by mrniko** [comment]
Yes, you can.
