### ISSUE TITLE
No data available in cache after Redisson version upgrade from 3.9.1 to 3.17.4

### ISSUE THREAD

**Issue by krishnakumarakurathi** [redisson/redisson#4419]
Dear Team,

We have upgraded our **Redisson Java client** version from 3.9.1 to 3.17.4. Post upgrade we noticed that the redisson java client is reporting **"No data in cache"** even though the data is available in the cache. To confirm this, we have issued direct redis-cli commands and found that the data is available in the redis cache. Your support on this issue would be of great help because this has a direct impact on workloads.

Thanks in advance for your support in this regard.

**Comment by mrniko** [comment]
Default codec has changed since 3.10 version. Now it's MarshallingCodec.

**Comment by krishnakumarakurathi** [comment]
Hi @mrniko, Thanks so much for your response.
I am a little confused about the next steps. 
Kindly advise us on how to resolve this issue.

**Comment by mrniko** [comment]
you can back to 3.9.1 version and then read data using default codec and store it into structures using MarshallingCodec manually.

**Comment by mrniko** [comment]
You can copy its source from the current version.
