### ISSUE TITLE
In the high concurrency scenario, the current RRatelimiter will cause the QPS of redis single node to be too high, which may lead to a crash

### ISSUE THREAD

**Issue by hitmm** [redisson/redisson#4421]
**Expected behavior**
The CPU utilization of redis nodes is relatively balanced

**Actual behavior**
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/13416145/179163110-6855600d-71eb-467b-a2dc-0bb1beedd5e3.png">

**Steps to reproduce or test case**

**Redis version**
4.x
**Redisson version**
3.15.5
**Redisson configuration**

**Comment by mrniko** [comment]
RateLimiter had an issue when limit decreases in high concurrency. Fixed in 3.16.4 version. Please update to the latest version.

**Comment by hitmm** [comment]
您好，邮件我已经收到，我会尽快查收~
