### ISSUE TITLE
Redisson does not write session data into Redis database, session is written into SESSIONS.ser instead.

### ISSUE THREAD

**Issue by Backpackstudio** [redisson/redisson#4426]
I'm using [Tomcat installer for macOS and Linux](https://github.com/Backpackstudio/tomcat-installers). Have tested with different versions of Tomcat and Redisson but the same outcome:

**Redisson does not write session data into Redis, but into SESSIONS.ser instead.**

Tested on macOS and also on Ubuntu, but on both the same result.

Are there some undocumented settings, which shall be added to Redisson ?

context.xml:

```xml
<Context reloadable="true" crossContext="true" sessionCookiePath="/">
	<ResourceLink name="redissonsess" global="redissonsess" type="org.redisson.api.RedissonClient" />
	<Manager className="org.redisson.tomcat.JndiRedissonSessionManager" readMode="REDIS" jndiName="redissonsess" updateMode="AFTER_REQUEST" broadcastSessionEvents="true" keyPrefix="tms" />

```

server.xml:

```xml
  <GlobalNamingResources>

		<Resource name="redissonsess" auth="Container" factory="org.redisson.JndiRedissonFactory" configPath="${catalina.base}/conf/redisson.yaml" closeMethod="shutdown" />
```

redisson.yaml:

```yaml
singleServerConfig:
 address: "redis://127.0.0.1:6379"
 database: 0
```

Redisson `redisson-all` and  `redisson-tomcat` libraries are added into ./lib folder. Tested different versions.

```
redisson-all-3.17.4.jar
redisson-tomcat-9-3.17.4.jar
```

**Comment by mrniko** [comment]
It's a configuration issue. It works as expected and pass tests for tomcat 9.

**Comment by Backpackstudio** [comment]
> It's a configuration issue. It works as expected and pass tests for tomcat 9. RedissonSessionManager can write only to Redis

Thank you for response. What I shall change?

**Comment by mrniko** [comment]
Check your config files for presence of default session manager
