### ISSUE TITLE
Add "username" setting support to Sentinel mode

### ISSUE THREAD

**Issue by georgelupu** [redisson/redisson#4439]
**Is your feature request related to a problem? Please describe.**
Latest Redis (6+) servers have ACL support which allows us to have in the database other users than the default one, but the current redisson client driver implementation does not allow to provide the "username" under Sentinel Settings. As result only default db user can be used with the redisson driver with Sentinel.

**Describe the solution you'd like**
I see here (https://github.com/redisson/redisson/wiki/2.-Configuration#24-cluster-mode) that Redisson Cluster Mode does provide "username" functionality support. Please port it to Sentinel mode as well. Thank you!

**Describe alternatives you've considered**
No alternatives are available for Sentinel mode at the moment except using the "default" redis db user for everything.

**Comment by mrniko** [comment]
You can use username for Sentinel as well. Documentation is missing that parameter.

**Comment by mrniko** [comment]
Done
