### ISSUE TITLE
RiverUnmarshaller codec?

### ISSUE THREAD

**Issue by zsokolowski** [redisson/redisson#4443]
**Expected behavior**

Not throwing  any exception, I need any hints. I don't use for sure this codec

**Actual behavior**

<html><body>
<span>

Field | Value
-- | --

@message | {"timeStamp":"2022-07-25T12:16:20.570Z","loggerName":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]","logMessage":"Servlet.service()  for servlet [dispatcherServlet] in context with path [] threw exception  [Request processing failed; nested exception is  org.redisson.client.RedisException: Unexpected exception while  processing command] with root  cause","thread":"http-nio-8081-exec-8","level":"ERROR","thrown":{"cause":null,"stackTrace":[{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"start","fileName":"RiverUnmarshaller.java","lineNumber":1375,"className":"org.jboss.marshalling.river.RiverUnmarshaller","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"lambda$new$0","fileName":"MarshallingCodec.java","lineNumber":145,"className":"org.redisson.codec.MarshallingCodec","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"CommandDecoder.java","lineNumber":383,"className":"org.redisson.client.handler.CommandDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decodeList","fileName":"CommandDecoder.java","lineNumber":427,"className":"org.redisson.client.handler.CommandDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"CommandDecoder.java","lineNumber":392,"className":"org.redisson.client.handler.CommandDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decodeCommand","fileName":"CommandDecoder.java","lineNumber":198,"className":"org.redisson.client.handler.CommandDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"CommandDecoder.java","lineNumber":137,"className":"org.redisson.client.handler.CommandDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"CommandDecoder.java","lineNumber":113,"className":"org.redisson.client.handler.CommandDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decodeRemovalReentryProtection","fileName":"ByteToMessageDecoder.java","lineNumber":510,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"callDecode","fileName":"ReplayingDecoder.java","lineNumber":366,"className":"io.netty.handler.codec.ReplayingDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"ByteToMessageDecoder.java","lineNumber":279,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":357,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"unwrap","fileName":"SslHandler.java","lineNumber":1372,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decodeJdkCompatible","fileName":"SslHandler.java","lineNumber":1235,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"SslHandler.java","lineNumber":1284,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"decodeRemovalReentryProtection","fileName":"ByteToMessageDecoder.java","lineNumber":510,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"callDecode","fileName":"ByteToMessageDecoder.java","lineNumber":449,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"ByteToMessageDecoder.java","lineNumber":279,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":357,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"DefaultChannelPipeline.java","lineNumber":1410,"className":"io.netty.channel.DefaultChannelPipeline$HeadContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"DefaultChannelPipeline.java","lineNumber":919,"className":"io.netty.channel.DefaultChannelPipeline","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"read","fileName":"AbstractNioByteChannel.java","lineNumber":166,"className":"io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"processSelectedKey","fileName":"NioEventLoop.java","lineNumber":722,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"processSelectedKeysOptimized","fileName":"NioEventLoop.java","lineNumber":658,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"processSelectedKeys","fileName":"NioEventLoop.java","lineNumber":584,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"NioEventLoop.java","lineNumber":496,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"SingleThreadEventExecutor.java","lineNumber":995,"className":"io.netty.util.concurrent.SingleThreadEventExecutor$4","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"ThreadExecutorMap.java","lineNumber":74,"className":"io.netty.util.internal.ThreadExecutorMap$2","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"FastThreadLocalRunnable.java","lineNumber":30,"className":"io.netty.util.concurrent.FastThreadLocalRunnable","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"11.0.15","methodName":"run","fileName":"Thread.java","lineNumber":829,"className":"java.lang.Thread","nativeMethod":false}],"message":"Unsupported  protocol version 0","suppressed":[],"localizedMessage":"Unsupported  protocol version 0"},"class":"java.io.IOException"}
@timestamp | 1658751380571
class | java.io.IOException
level | ERROR
loggerName | org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]
logMessage | Servlet.service()  for servlet [dispatcherServlet] in context with path [] threw exception  [Request processing failed; nested exception is  org.redisson.client.RedisException: Unexpected exception while  processing command] with root cause
thread | http-nio-8081-exec-8
thrown.localizedMessage | Unsupported protocol version 0
thrown.message | Unsupported protocol version 0
thrown.stackTrace.0.className | org.jboss.marshalling.river.RiverUnmarshaller
thrown.stackTrace.0.fileName | RiverUnmarshaller.java
thrown.stackTrace.0.lineNumber | 1375
thrown.stackTrace.0.methodName | start
thrown.stackTrace.0.nativeMethod | 0
thrown.stackTrace.1.className | org.redisson.codec.MarshallingCodec
thrown.stackTrace.1.fileName | MarshallingCodec.java
thrown.stackTrace.1.lineNumber | 145
thrown.stackTrace.1.methodName | lambda$new$0
thrown.stackTrace.1.nativeMethod | 0
thrown.stackTrace.2.className | org.redisson.client.handler.CommandDecoder
thrown.stackTrace.2.fileName | CommandDecoder.java
thrown.stackTrace.2.lineNumber | 383
thrown.stackTrace.2.methodName | decode
thrown.stackTrace.2.nativeMethod | 0
thrown.stackTrace.3.className | org.redisson.client.handler.CommandDecoder
thrown.stackTrace.3.fileName | CommandDecoder.java
thrown.stackTrace.3.lineNumber | 427
thrown.stackTrace.3.methodName | decodeList
thrown.stackTrace.3.nativeMethod | 0
thrown.stackTrace.4.className | org.redisson.client.handler.CommandDecoder
thrown.stackTrace.4.fileName | CommandDecoder.java
thrown.stackTrace.4.lineNumber | 392
thrown.stackTrace.4.methodName | decode
thrown.stackTrace.4.nativeMethod | 0
thrown.stackTrace.5.className | org.redisson.client.handler.CommandDecoder
thrown.stackTrace.5.fileName | CommandDecoder.java
thrown.stackTrace.5.lineNumber | 198
thrown.stackTrace.5.methodName | decodeCommand
thrown.stackTrace.5.nativeMethod | 0
thrown.stackTrace.6.className | org.redisson.client.handler.CommandDecoder
thrown.stackTrace.6.fileName | CommandDecoder.java
thrown.stackTrace.6.lineNumber | 137
thrown.stackTrace.6.methodName | decode
thrown.stackTrace.6.nativeMethod | 0
thrown.stackTrace.7.className | org.redisson.client.handler.CommandDecoder
thrown.stackTrace.7.fileName | CommandDecoder.java
thrown.stackTrace.7.lineNumber | 113
thrown.stackTrace.7.methodName | decode
thrown.stackTrace.7.nativeMethod | 0
thrown.stackTrace.8.className | io.netty.handler.codec.ByteToMessageDecoder
thrown.stackTrace.8.fileName | ByteToMessageDecoder.java
thrown.stackTrace.8.lineNumber | 510
thrown.stackTrace.8.methodName | decodeRemovalReentryProtection
thrown.stackTrace.8.nativeMethod | 0
thrown.stackTrace.9.className | io.netty.handler.codec.ReplayingDecoder
thrown.stackTrace.9.fileName | ReplayingDecoder.java
thrown.stackTrace.9.lineNumber | 366
thrown.stackTrace.9.methodName | callDecode
thrown.stackTrace.9.nativeMethod | 0
thrown.stackTrace.10.className | io.netty.handler.codec.ByteToMessageDecoder
thrown.stackTrace.10.fileName | ByteToMessageDecoder.java
thrown.stackTrace.10.lineNumber | 279
thrown.stackTrace.10.methodName | channelRead
thrown.stackTrace.10.nativeMethod | 0
thrown.stackTrace.11.className | io.netty.channel.AbstractChannelHandlerContext
thrown.stackTrace.11.fileName | AbstractChannelHandlerContext.java
thrown.stackTrace.11.lineNumber | 379
thrown.stackTrace.11.methodName | invokeChannelRead
thrown.stackTrace.11.nativeMethod | 0
thrown.stackTrace.12.className | io.netty.channel.AbstractChannelHandlerContext
thrown.stackTrace.12.fileName | AbstractChannelHandlerContext.java
thrown.stackTrace.12.lineNumber | 365
thrown.stackTrace.12.methodName | invokeChannelRead
thrown.stackTrace.12.nativeMethod | 0
thrown.stackTrace.13.className | io.netty.channel.AbstractChannelHandlerContext
thrown.stackTrace.13.fileName | AbstractChannelHandlerContext.java
thrown.stackTrace.13.lineNumber | 357
thrown.stackTrace.13.methodName | fireChannelRead
thrown.stackTrace.13.nativeMethod | 0
thrown.stackTrace.14.className | io.netty.handler.ssl.SslHandler
thrown.stackTrace.14.fileName | SslHandler.java
thrown.stackTrace.14.lineNumber | 1372
thrown.stackTrace.14.methodName | unwrap
thrown.stackTrace.14.nativeMethod | 0
thrown.stackTrace.15.className | io.netty.handler.ssl.SslHandler
thrown.stackTrace.15.fileName | SslHandler.java
thrown.stackTrace.15.lineNumber | 1235
thrown.stackTrace.15.methodName | decodeJdkCompatible
thrown.stackTrace.15.nativeMethod | 0
thrown.stackTrace.16.className | io.netty.handler.ssl.SslHandler
thrown.stackTrace.16.fileName | SslHandler.java
thrown.stackTrace.16.lineNumber | 1284
thrown.stackTrace.16.methodName | decode
thrown.stackTrace.16.nativeMethod | 0
thrown.stackTrace.17.className | io.netty.handler.codec.ByteToMessageDecoder
thrown.stackTrace.17.fileName | ByteToMessageDecoder.java
thrown.stackTrace.17.lineNumber | 510
thrown.stackTrace.17.methodName | decodeRemovalReentryProtection

</span>
</body>
</html>

**Steps to reproduce or test case**

```
 final ConcurrentMap<String, RQueue<T>> allRQueues = new ConcurrentHashMap<>();

        RKeys keys = redissonClient.getKeys();
        for (String key : keys.getKeysByPattern(keyPatternProvider.getTopicName() + WILDCARD)) {
            allRQueues.put(key, redissonClient.getQueue(key));
        }

        allRQueues
                .forEach((queueName, rQueue) -> {
                    final Flowable<Boolean> removalProcess = Flowable
                            .fromIterable(rQueue.readAll())
                            .filter(item -> redisEntryCleanupPredicate.itemToRemove(item, configurationName))
                            .map(rQueue::remove)
                            .subscribeOn(ioScheduler)
                            .map(deleted -> {
                                if (Boolean.TRUE.equals(deleted)) {
                                    removedItemsCounter.incrementAndGet();
                                } else {
                                    notRemovedItemsCounter.incrementAndGet();
                                }
                                return deleted;
                            });

                    removalProcess.subscribe(
                            result -> {
                            },
                            error -> LOG.error("Error while cleaning up configuration {} in Redis", configurationName, error),
                            () -> LOG.info("While cleaning up configuration: {}, {} items were removed, {} items retained.",
                                    configurationName, removedItemsCounter.get(), notRemovedItemsCounter.get())
                    );
                });
    }
```

**Redis version**

AWS 6.2.6

**Redisson version**

3.17.4 

**Redisson configuration**
 Config redissonConfiguration = new Config();
        redissonConfiguration
                .setNettyThreads(redisConfigurationModel.getNettyThreads())
                .useClusterServers()
                .setNatMapper(mapper)
                .setConnectTimeout(redisConfigurationModel.getConnectionTimeout())
                .setRetryAttempts(redisConfigurationModel.getRetryAttempts())
                .setMasterConnectionPoolSize(redisConfigurationModel.getConnectionPoolSize())
                .setRetryInterval(redisConfigurationModel.getRetryInterval())
                .setTimeout(redisConfigurationModel.getTimeout())
                .addNodeAddress(redisConfigurationNodeAddress);

**Comment by mrniko** [comment]
Try to use a different codec

**Comment by lianyiwuming** [comment]
Maybe you set and get with a different data struct! I  just had the same problem .

> Try to use a different codec

Maybe it's reason that set and get with a different data struct via same key! I  just had the same problem.
