### ISSUE TITLE
redissonClient.getBuckets().get("foo") with NameMapper set doesn't apply NameMapper

### ISSUE THREAD

**Issue by chaimmintz** [redisson/redisson#4444]
I have a `NameMapper` that adds a prefix to all keys during map (and removes the prefix during unmap). Let's say the prefix is "prefix.` for the purposes of this submission.

Expected behavior
`redissonClient.getBuckets().get("foo")` with `NameMapper` set should retrieve the `prefix.foo` key

Actual behavior
`redissonClient.getBuckets().get("foo")` with `NameMapper` set retrieves the `foo` key (without the expected prefix)

Not sure if `set`/`trySet` in RedissonBuckets.java have similar issues.

As a workaround, `redissonClient.getBucket(key).get()` does apply the `NameMapper` correctly (but it doesn't support bulk lookup)

Redis version
6.0.1

Redisson version
3.17.5 (latest)

Redisson configuration
With a NameMapper that adds `prefix.` to all keys.

**Comment by mrniko** [comment]
Fixed. Thanks for report
