### ISSUE TITLE
can RedissonBloomFilter support batch add objects function

### ISSUE THREAD

**Issue by Helmsman-Lab** [redisson/redisson#4447]
when I init the bloomfilter, i need to initialize some data to the filter,the current add method will loop many times that will cause lots of IO expend，so is that be fine to support batchAdd function? 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/issues/5130
