### ISSUE TITLE
How to read all values of a large map as fast as possible?

### ISSUE THREAD

**Issue by kombuch** [redisson/redisson#4450]
I am trying to read all the values from a map with ~400,000 entires of 900bytes encoded objects each, as fast as possible. Currently reading values from a map of 100,000 objects takes 3 seconds, while 200,000 takes 10. the scaling is worse than linear.

```
RBatch batch = this.redissonClient.createBatch(BatchOptions.defaults()
                                                                   .executionMode(BatchOptions.ExecutionMode.IN_MEMORY_ATOMIC);

RFuture<Collection<Object>> futureCollection = batch.getMap("KEY").readAllValuesAsync();

batch.execute();

Collection<Object> collection = null;
        try {
            collection = futureCollection.get();
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }
```

this is the config I'm using:

config.useSingleServer()
              .setAddress(REDIS_SERVER_ADDRESS)
              .setConnectionPoolSize(128)
              .setTimeout(20000);
        config.setNettyThreads(128);
        config.setCodec(new FstCodec());

**Comment by lehuuthanh5** [comment]
Hi, I think you have the best way to read data from Redis.
If you want to speed up your application, I think you can try RedissonLocalCacheMap for availability of data.

**Comment by kombuch** [comment]
Done
