### ISSUE TITLE
Releasing a semaphore when JVM crashes. 

### ISSUE THREAD

**Issue by borisdainson** [redisson/redisson#4462]
Hi. 

I want to use Redisson Semaphore. Sometimes my processes get stopped or killed before semaphore gets released and this locks up the semaphore. I cannot restart my service and acquire such semaphore again. Locks have a watchdog (configurable via setLockWatchdogTimeoutthat ) that will release a lock if process crashes or stops. Is there a reason same or similar watchdog mechanism is not available for semaphores? Can it be added? It is not clear to me how to use semaphores without such automatic release in case of a crash. 

Thank you

**Comment by November22** [comment]
I have the same problem

**Comment by FanHuaRan** [comment]
I have the same problem !

**Comment by Piotr-Gorski-Ringier** [comment]
you can use getPermitExpirableSemaphore. This way your semaphore will be released some time  after a crash. 
availablePermits will return a wrong number but you will be able to acquire and release a new semaphore.
