### ISSUE TITLE
Keys not getting deleted from AWS redis which is creating memory issue

### ISSUE THREAD

**Issue by MokshaPadsalgi** [redisson/redisson#4465]
Hello,

I'm using Redisson with two Tomcat, each one in a virtual instance behind a Load Balancer on AWS.

Everything works great, both Tomcat can create and store session on Redis (I can easily see keys/values serialized on Redis) and both can retrieve the stored session correctly.

My issue/question is: should Tomcat be able to delete keys automatically from Redis when the session invalidated? I'm sure that Tomcat is destroying/invalidating the session internally, but keys keep staying on Redis. Why are keys from redis are not getting deleted and freeing the memory ?

Because of this behaviour, we are getting memory issue/alert from Redis.

Can you tell me what can I do to remove/delete expired session keys from Redis?

Thanks.
Moksha

**Comment by mrniko** [comment]
Did you set session-timeout in tomcat configuration?
