### ISSUE TITLE
Is it possible for only some of the commands in a batch to execute?

### ISSUE THREAD

**Issue by kombuch** [redisson/redisson#4466]
If I am doing a batch with Execution Mode : REDIS_WRITE_ATOMIC,
Is it possible for my batch to fail halfway, and have only made half the changes for example? Or if it fails in the middle will all of the changes be undone?

**Comment by mrniko** [comment]
> Is it possible for my batch to fail halfway, and have only made half the changes for example? Or if it fails in the middle will all of the changes be undone?

No, it's not supported by Redis batch.
