### ISSUE TITLE
Redisson throw out of memory 

### ISSUE THREAD

**Issue by eng7miky** [redisson/redisson#4474]
We are running the application while using Redisson to read and write values and after a while the memory utilization of the application grows incrementally and then it throws out of memory

**Expected behavior**
No Memory leaks.

**Actual behavior**
- Application threw out of memory and after analyzing the dump file, Redisson is found to consume the largest portion of the memory 
-![redisson issue1](https://user-images.githubusercontent.com/2690942/183398326-933ebe9a-fc8f-43dc-8b82-89239b73504e.png)
and this screenshot also give more details about the Redisson objects
![redisson issue](https://user-images.githubusercontent.com/2690942/183398320-e4cc2acf-40ba-4598-87df-b973016ac6a9.png)

**Steps to reproduce or test case**

**Redis version**
5.0.5-1

**Redisson version**
3.15.0

**Redisson configuration**

**Comment by mrniko** [comment]
Two issues related to AsyncSemaphore memory leak there resolved since then.

https://github.com/redisson/redisson/issues/4215
https://github.com/redisson/redisson/issues/3703

Please update to the latest version
