### ISSUE TITLE
Delay queue message lost

### ISSUE THREAD

**Issue by xiaochangbai** [redisson/redisson#4481]
**Expected behavior**

Listen to the message and consume

**Actual behavior**

No message was heard

**Steps to reproduce or test case**

1、Start consumers first
     
    @Test
    public void listener() throws IOException {
        String qName = "test";
        RedissonClient redissonClient = TestRedissonClient.redisson();
        RBlockingQueue<Object> blockingFairQueue = redissonClient.getBlockingQueue(qName);
        new Thread(()->{
            while (true) {
                try {
                    log.info("Start delay queue processing thread");
                    Object message = blockingFairQueue.take();
                    log.info("Message received: {}",message);
                } catch (Exception e) {
                    log.error("Delay queue service processing exception!",e);
                }
            }
        }).start();
        log.info("Consumer startup completed");
        System.in.read();
    }

2、Restart producer

    @Test
    public void t1() {
        String qName = "test";
        RedissonClient redisson = TestRedissonClient.redisson();
        RBlockingQueue<String> blockingFairQueue = redisson.getBlockingQueue(qName);
        RDelayedQueue<String> delayedQueue = redisson.getDelayedQueue(blockingFairQueue);
        delayedQueue.offer("hello-1", 1, TimeUnit.SECONDS);
    }

**Redis version**

redis_version:5.0.5

**Redisson version**
3.17.5 and 3.17.0
**Redisson configuration**

        Config config = new Config();
        SingleServerConfig useSingleServer = config.useSingleServer();
        useSingleServer.setAddress(redissonUrl);
        useSingleServer.setPassword(StringUtils.isNotBlank(password)?password:null);
        useSingleServer.setConnectionPoolSize(500);
        useSingleServer.setIdleConnectionTimeout(10000);
        useSingleServer.setConnectTimeout(30000);
        useSingleServer.setTimeout(3000);

note:  We noticed that this problem can be solved by adding an empty message after the consumer starts. The code is as follows:

    @Test
    public void listener() throws IOException {
        String qName = "test";
        RedissonClient redissonClient = TestRedissonClient.redisson();
        RBlockingQueue<Object> blockingFairQueue = redissonClient.getBlockingQueue(qName);
        new Thread(()->{
            while (true) {
                try {
                    log.info("Start delay queue processing thread");
                    Object message = blockingFairQueue.take();
                    log.info("Message received: {}",message);
                } catch (Exception e) {
                    log.error("Delay queue service processing exception!",e);
                }
            }
        }).start();
        RDelayedQueue<Object> delayedQueue = redissonClient.getDelayedQueue(blockingFairQueue);
        delayedQueue.offer(null, 0, TimeUnit.SECONDS);
        log.info("Consumer startup completed");
        System.in.read();
    }

**Comment by sachinlala** [comment]
We're facing the same issue with following versions combination:
> org.redisson:redisson-spring-boot-starter:3.19.0
> redis.clients:jedis:4.3.1
> org.springframework.boot:2.7.3
> Java 11

Redis server deployed in AWS Elastic Cache: version `7.0.4`

Researching further. Would like to avoid the empty message approach.

**Comment by sachinlala** [comment]
Init/empty message is not required as long as we ensure that an instance of `RDelayedQueue` is available during subscription too.

We started experiencing the issue since a week back after upgrading to `3.19.0`.

Sharing relevant code snippet:

`  public void subscribeMessage(EventProcessor<Q> eventProcessor) {
    Q queueMessage = null;
    try {
      RBlockingQueue<Q> blockingQueue = subscriber.getBlockingQueue(this.getOrderQueue());
      RDelayedQueue<Q> delayedQueue = subscriber.getDelayedQueue(blockingQueue);
      log.info("Awaiting next message from queue: {}", this.topicForQueuedOrders);
      queueMessage = blockingQueue.take();
      eventProcessor.processEvent(queueMessage);
      log.info("Processed message: {}", queueMessage);
    } catch (InterruptedException e) {
      log.error(String.format("Exception in processing message: [%s] --> ",
          this.getMessageString(queueMessage)), e);
    }
  }
`

**Comment by mrniko** [comment]
@sachinlala unable to reproduce

**Comment by Alok-Kumar-9** [comment]
We are also facing this issue with redisson under high write load. We are on the redisson version 3.23.5
I am using this code snippet-
`public TestRedisDelay(RedissonClient managedClient, String queuePrefix, ObjectMapper objectMapper) {
    this.destinationQueue = managedClient.getBlockingQueue(queuePrefix + "test");
    this.delayedQueue = managedClient.getDelayedQueue(this.destinationQueue);

    this.objectMapper = objectMapper;
  }

public void pushToDelayedQueue(TestRequest testRequest) {
      try {
        String jsonTestRequest = objectMapper.writeValueAsString(testRequest);
        this.delayedQueue.offer(jsonTestRequest, 5L, TimeUnit.MINUTES);
      } catch (Exception e) {
        log.error("ERR_CONVERTING_TO_JSON_NODE :: {} :: REQ- {}", e.getMessage(), testRequest);
      }
  }

public TestRequest fetchRequests() {
      TestRequest testRequest = null;
      try {
        String revampedQueueRequest = destinationQueue.poll();
        if(!Strings.isEmpty(revampedQueueRequest)) {
          testRequest = objectMapper.readValue(revampedQueueRequest, TestRequest.class);
        }
      } catch (Exception e) {
        log.error("ERR_FETCHING FROM QUEUE :: {}", e.getMessage());
      }

    return testRequest;
  }`

When I am testing this with a 20-30TPS request for 30-40 minutes, it is starting to break.
I am using AWS Elasticache t3.small instance for redis.

**Comment by mrniko** [comment]
RDelayedQueue successor is [Reliable Queue](https://redisson.pro/docs/data-and-services/queues/#reliable-queue) with delay parameter.
