### ISSUE TITLE
The value serialization results of rmap and rmapcache are inconsistent

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#4485]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
The value serialization results of rmap and rmapcache are inconsistent. Rmapcache will force the serialized value to undergo binary conversion again. This is not the result I want. I hope it can be fixed
**Redis version**

**Redisson version**

**Redisson configuration**

**Comment by JavaLionLi** [comment]
There are two serialization formats in a key hash

**Comment by mrniko** [comment]
RMapCache keys has additional info about entry idle time. This can't be changed
