### ISSUE TITLE
When the amount of data is large, the add() of RBloomfilter is inefficient, and addAll() should be provided to add in batches

### ISSUE THREAD

**Issue by ShepherdZFJ** [redisson/redisson#4488]
// foreach add data
        for (Integer i = 0; i < 100000000; i++) {
            bloomFilter.add(i);
        }

**Comment by SplotyCode** [comment]
See #4043 and #4447

**Comment by mrniko** [comment]
implemented in https://github.com/redisson/redisson/issues/5130
