### ISSUE TITLE
Redisson Spring Cache not getting cache info

### ISSUE THREAD

**Issue by splurring** [redisson/redisson#4490]
I have configured my Redisson instance:
```
@Bean
RedissonClient redisson() {
        Config config = new Config();
        config.useSingleServer()
              .setAddress("redis://127.0.0.1:6379");
        return Redisson.create(config);

RedissonClient redisson = Redisson.create(config);
```
I have also configured the cacheManager
```
 @Bean
    CacheManager cacheManager(RedissonClient redissonClient) {
        Map<String, CacheConfig> config = new HashMap<>();

        // create "testMap" spring cache with ttl = 24 minutes and maxIdleTime = 12 minutes
        config.put("testMap", new CacheConfig(24*60*1000, 12*60*1000));
        return new RedissonSpringCacheManager(redissonClient, config);
    }
```

I then in the service layer have a method that puts in keys. `redison.getMapCache("test").put("1",1)`

When I try to get the value of the key doing `redison.getMapCache("test").get("1")`, the value 1 is returned.

HOWVER, I then have a SEPARATE method that tries to gets the keys and when i do `redison.getMapCache("test").get("1")`, i get returned null.

What is the issue?

**Comment by JavaLionLi** [comment]
没遇见过 一切正常
