### ISSUE TITLE
What's the different implementation for RScheduledExecutorService.submit and RScheduledExecutorService.schedule()

### ISSUE THREAD

**Issue by yeah007** [redisson/redisson#4491]
In my test environments, the tasks created  RScheduledExecutorService.submit can be picked up but the task created by RScheduledExecutorService.schedule() cannot.  
Even after several hours, the scheduled tasks still cannot be picked up. During the time, these tasks created  RScheduledExecutorService.submit can be executed successfully.

**Comment by yeah007** [comment]
Refer to https://github.com/redisson/redisson/issues/4383

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4499
