### ISSUE TITLE
Can't add master: redis://**.*.**.**:6380 for slot ranges

### ISSUE THREAD

**Issue by qq502361472** [redisson/redisson#4492]
启动时提示Command execution timeout for command: (AUTH), params: (password masked), 。
这个问题我提问很多次了，说是网络问题，连接数问题。我降低连接数还是同样的问题。我感觉应该是网络问题，但是我想知道问题发生的原因。因为我这里用lettuce和jedis连接池非常稳定，不会发生这样的错误。我修改了timeout到10s，同样还是会发生这个错误。我想确认是由于什么原因导致的问题。附件是报错的trace日志，辛苦作者帮我看一看。我和另外一位中国的用户有着同样的问题。
[错误trace.txt](https://github.com/redisson/redisson/files/9357346/trace.txt)

**Comment by awp-hadoop** [comment]
大致看了下，整个日志先提示了redis集群slot覆盖不全，后redisson提示redis集群不可用，建议排查如下：
（1）检查redis集群部署里配置“cluster-require-full-coverage”，默认值 yes 表示当负责一个插槽的主库下线且没有相应的从库进行故障恢复时，集群不可用。估计你部署的集群里某个节点已经无slave，那么就不对外提供redis服务了，建议设置为no；
（2）redisson进群配置里有个方法setCheckSlotsCoverage，可以设置属性checkSlotsCoverage，避免因部分slot不可用导致的整个redis服务不可用，默认为TRUE，建议设置为FALSE，相关源码如下：
if (cfg.isCheckSlotsCoverage() && lastPartitions.size() != MAX_SLOT) {
stopThreads();
if (failedMasters.isEmpty()) {
throw new RedisConnectionException("Not all slots covered! Only " + lastPartitions.size() + " slots are available. Set checkSlotsCoverage = false to avoid this check.", lastException);
} else {
throw new RedisConnectionException("Not all slots covered! Only " + lastPartitions.size() + " slots are available. Set checkSlotsCoverage = false to avoid this check. Failed masters according to cluster status: " + failedMasters, lastException);
}
}
（3）问题重点是排查redis集群是否已经不可用，如果能容忍部分slot不可用时候，应用仍然可用，建议采用上面（1）和（2）的配置。

**Comment by qq502361472** [comment]
我debug发现是在发送命令时发生了java.nio.channels.ClosedChannelException,想知道为什么Channel会被关闭呢

**Comment by mrniko** [comment]
Update to 3.17.1 or 3.17.3 version it should resolve the issue
