### ISSUE TITLE
Recommended configuration for AWS Elasticache Global Datastore 

### ISSUE THREAD

**Issue by Sovietaced** [redisson/redisson#4493]
Hello! We are currently using Redisson with AWS Elasticache and it works well. We are currently using it in a single cluster in one region and we use the `ReplicatedConnectionManager`. 

We plan to deploy AWS Elasticache in multiple regions with their [global datastore](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Redis-Global-Datastore.html) feature. With global datastore there can be two or more clusters but only one will accept writes. The other clusters will operate with a "passive" master. 

Looking at the `ReplicatedConnectionManager` [code](https://github.com/redisson/redisson/blob/608625a3bd8a5442b3c23840d2a202f7fb782bd1/redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java#L67-L108) I'm a bit concerned whether it will detect "passive" masters as nodes that can accept writes when those nodes cannot accept writes.

We will experiment with this soon but I figured I would document the question/experience for others.

**Comment by mrniko** [comment]
This feature uses Redis Cluster so ClusterConnectionManager should be used. Redisson instance should be created per cluster.

**Comment by Sovietaced** [comment]
Thanks for the response @mrniko 

I think using two Redisson instances will not be very elegant. I imagine that any reference like a Map or a Lock will be tied to the Redisson instance so it's not clear to me how our application would failover and re-acquire those references without modifying our application logic quote heavily. 

I haven't dabbled with the global datastore yet but I'm wondering how the underlying AWS implementation actually works. Perhaps a connection manager could be made/augmented if the "passive" master is exposed somehow. Or maybe we could implement a connection manager that relies on AWS APIs to determine the cluster master.
