### ISSUE TITLE
worsened performance for versions > 3.16.2

### ISSUE THREAD

**Issue by hishamhayat** [redisson/redisson#4504]
I'm tried running the following test using spring boot  and redisson :

@Autowired
  private RedissonReactiveClient client:

  @RepeatedTest(3)
  void redisson() {
    RAtomicLongReactive atomicLong = client.getAtomicLong("usr:2:visit");
    Mono<Void> mono = Flux.range(1, 500_000)
        .flatMap(i -> atomicLong.incrementAndGet())
        .then();
    Instant startTm=Instant.now();
    StepVerifier.create(mono).verifyComplete();
    Duration duration = Duration.between(startTm, Instant.now());
    System.out.println(duration.toMillis()+ " ms");
  }

when I use redisson version 3.16.1 or 3.16.2, my test executes in 8-9 ms.
But when I use a higher version, tried from 3.16.3 to 3.17.5, the tests executes in 22-24 ms; which is significantly slower.

**Actual behavior**
use redisson 3.16.1 or 3.16.2

**Steps to reproduce or test case**
switch to a version > 3.16.2

**Redis version**
7.0.4

**Redisson version**
3.16.3 and higher

**Redisson configuration**
my pom file:

"<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.7.3</version>
    <relativePath/> 
  </parent>
  <groupId>org.test.redisspring</groupId>
  <artifactId>redis-spring</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>redis-spring</name>
  <description>redis-spring</description>
  <properties>
    <java.version>17</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson-spring-boot-starter</artifactId>
      <version>3.16.2</version>

      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-aop</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-resolver-dns-native-macos</artifactId>
      <version>4.1.79.Final</version>
      <scope>runtime</scope>
      
      <classifier>osx-aarch_64</classifier>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>2.7.3</version>
        <configuration>
          <excludes>
            <exclude>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>"

**Comment by mrniko** [comment]
Unable to reproduce:

```
2022.08.23 09:30:46.871 INFO  Version : Redisson 3.16.2
2022.08.23 09:30:47.081 INFO  MasterPubSubConnectionPool : 1 connections initialized for 127.0.0.1/127.0.0.1:6379
2022.08.23 09:30:47.100 INFO  MasterConnectionPool : 24 connections initialized for 127.0.0.1/127.0.0.1:6379
4997 ms
```

```
2022.08.23 09:51:59.754 INFO  Version : Redisson 3.17.5
2022.08.23 09:51:59.917 INFO  MasterPubSubConnectionPool : 1 connections initialized for 127.0.0.1/127.0.0.1:6379
2022.08.23 09:51:59.927 INFO  MasterConnectionPool : 24 connections initialized for 127.0.0.1/127.0.0.1:6379
3829 ms
```
