### ISSUE TITLE
Null exception deserializing with JsonJacksonCodec

### ISSUE THREAD

**Issue by lmiranda** [redisson/redisson#4507]
I trying to use redisson as SessionManager on tomcat with an legacy app.
I get `java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException)` 
I don´t wanna change the legacy code, so i want to know if there's some way to configure JsonJacksonCodec to ignore Null values, outside app code (ie context,xml, redisson.conf...)

**Comment by mrniko** [comment]
Here is how you can do it https://www.baeldung.com/jackson-ignore-null-fields
