### ISSUE TITLE
Unable to get connection! Try to increase 'nettyThreads' and/or connection pool size settings

### ISSUE THREAD

**Issue by zhubozhujinyao** [redisson/redisson#4517]
I am not very unstand it .

Version：3.11.0
Class：CommandAsyncService.java       
=================================================
         if (details.getConnectionFuture().cancel(false)) {
                    if (details.getException() == null) {
                        details.setException(new RedisTimeoutException("Unable to get connection! Try to increase 'nettyThreads' and/or connection pool size settings"
                                    + "Node source: " + source
                                    + ", command: " + LogHelper.toString(command, details.getParams()) 
                                    + " after " + details.getAttempt() + " retry attempts"));
                    }
                }

**Comment by zhubozhujinyao** [comment]
@jackygurui

**Comment by SplotyCode** [comment]
It is a timeout for the future. If we can cancel the future was still running https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#cancel(boolean). Not sure what exactly you want to know

**Comment by zhubozhujinyao** [comment]
In the Scenario of Redis Cluster Master-Slave Switching（1 master, 2 slaves , and 3 sentinels），after the switchover, the cluster is ok。
But when performing the set operation，redisson has an exception：
"Unable to get connection! Try to increase 'nettyThreads' and/or connection pool size settings" .

The code snippet is the following:
     if (details.getConnectionFuture().cancel(false)) {
                if (details.getException() == null) {
                    details.setException(new RedisTimeoutException("Unable to get connection! Try to increase 'nettyThreads' and/or connection pool size settings"
                                + "Node source: " + source
                                + ", command: " + LogHelper.toString(command, details.getParams()) 
                                + " after " + details.getAttempt() + " retry attempts"));
                }
            }

so ,i want to known, why is that ?

Netty thread : 32

**Comment by mrniko** [comment]
In this case you need to increase retryAttempts amount to survive failover without errors.

**Comment by zhubozhujinyao** [comment]
> In this case you need to increase retryAttempts amount to survive failover without errors.

so , i want to known , what are the possible causes of the problem ?

**Comment by mrniko** [comment]
"Unable to get connection" usually means lack of connections in pool

**Comment by zhubozhujinyao** [comment]
@mrniko 
Caused by: org.redisson.client.RedisTimeoutException: Unable to get connection! 
Try to increase 'nettyThreads' and/or connection pool size settingsNode source: 
NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry 
[masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, 
freeConnectionsAmount=32, 
freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, 
client=[addr=redis://10.233.91.171:6379], nodeType=MASTER, firstFail=0]]], 
command: (SET), params: [[99, 111, 110, 110, 101, 99, 116, 105, 111, 110, ...], [34, 111, 107, 34]] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	... 1 common frames omitted
---------------------------------------------------
**From the question above：**

- freeConnectionsAmount=32, 
- freeConnectionsCounter=value:64:queue:0,

I wonder/don't know why this mistake appeared.

**Comment by zhubozhujinyao** [comment]
public void acquire(Runnable listener, int permits) {
        boolean run = false;
        synchronized (this) {
            if (counter < permits) {
                listeners.add(new Entry(listener, permits));
                return;
            } else {
                counter -= permits;
                run = true;
            }
        }
        if (run) {
            listener.run();
        }
    }

-----------------------------
Is this: Accounter is less than 1 ? But, from the source code , on change master: the code could set up a new masterEntry ，so, the accounter is still poolmaxsize .

**Comment by zhubozhujinyao** [comment]
> ## Caused by: org.redisson.client.RedisTimeoutException: Unable to get connection!
> Try to increase 'nettyThreads' and/or connection pool size settingsNode source:
> NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry
> [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0,
> freeConnectionsAmount=32,
> freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null,
> client=[addr=redis://10.233.91.171:6379], nodeType=MASTER, firstFail=0]]],
> command: (SET), params: [[99, 111, 110, 110, 101, 99, 116, 105, 111, 110, ...], [34, 111, 107, 34]] after 3 retry attempts
> at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:703)
> at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
> at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
> at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
> ... 1 common frames omitted
> **From the question above：**
> 
> * freeConnectionsAmount=32,
> * freeConnectionsCounter=value:64:queue:0,
> 
> I wonder/don't know why this mistake appeared.

Caused by: org.redisson.client.RedisTimeoutException: Unable to get connection!
Try to increase 'nettyThreads' and/or connection pool size settingsNode source:
NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry
[masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0,
freeConnectionsAmount=32,
freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null,
client=[addr=redis://10.233.91.171:6379], nodeType=MASTER, firstFail=0]]],
command: (SET), params: [[99, 111, 110, 110, 101, 99, 116, 105, 111, 110, ...], [34, 111, 107, 34]] after 3 retry attempts
at org.redisson.command.CommandAsyncService$6.run(CommandAsyncService.java:703)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
... 1 common frames omitted
-------------------------------------
From the question above：

freeConnectionsAmount=32,
freeConnectionsCounter=value:64:queue:0,

so ,i wonder/don't know why this mistake still appeared .

**Comment by mrniko** [comment]
@zhubozhujinyao 

This code was removed and not used anymore.

**Comment by zhubozhujinyao** [comment]
> @zhubozhujinyao
> 
> This code was removed and not used anymore.

@mrniko 
Can you tell me why this piece of code was removed ？Is there a bug ?
Upgrading the version will bring a lot of testing, so i don't want to upgrade it yet .

**Comment by mrniko** [comment]
> Can you tell me why this piece of code was removed ？Is there a bug ?

Because of refactoring.
