### ISSUE TITLE
Open the protected Config methods

### ISSUE THREAD

**Issue by jonathannaguin** [redisson/redisson#4518]
Hello,

The methods https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/Config.java#L302 and https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/Config.java#L222 are protected and therefore we can't customise them from a RedissonAutoConfigurationCustomizer class.

Would it be possible to change its visibility to be public?

Thanks

**Comment by mrniko** [comment]
They should remain protected.
