### ISSUE TITLE
SentinelConnectionManager.java stores `currentMaster` ipv6 address without square braces

### ISSUE THREAD

**Issue by xormrr** [redisson/redisson#4520]
Hi! I assume SentinelConnectionManager may be not working correctly with ipv6 DNS resolver. It constantly spams with `Skipped slave up redis://<slave1>:6379 for master redis://<master>:6379 differs from current redis://<master>:6379` message and repeatedly establishes new connections.

It was broken after committing changes to this line https://github.com/redisson/redisson/commit/1801f6996b3d409db618f7b5ed43e106fc763d12#diff-a757589f29014dde014891b0f1a07b19d21f4decf40d52e248567eeb8d646d30R128
So in the current Redisson version the `currentMaster` field is an instance of `RedisURI` with the `host` field value that is not wrapped in square braces.

The problem is that function `isUseSameMaster` [compares the current master](https://github.com/redisson/redisson/blob/705f68e8689ad5215b2aa74c086ebbfe86b6957e/redisson/src/main/java/org/redisson/connection/SentinelConnectionManager.java#L634) to `slaveMasterAddr` using `equals` and always gets `false` for two equal addresses because `slaveMasterAddr` is always instantiated with the other `RequestURI` constructor which adds square braces to the `host` value.

It was working correctly at version 3.15.6 and we can't upgrade to the newer version.
Spotted this while I was debugging the issue: https://github.com/redisson/redisson/issues/4314

![2022-08-30_16-15-43](https://user-images.githubusercontent.com/21213004/187456353-d1cc654a-887c-4f63-aefd-717669cd8bbf.png)

![2022-08-30_16-33-01](https://user-images.githubusercontent.com/21213004/187456399-e4b62027-2340-498c-a99e-9d9aec5076d7.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
