### ISSUE TITLE
设置 NameMapper 之后 BoundedBlockingQueue trySetCapacity key不正确 导致后续报错

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#4521]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
NameMapper 设置为 test
![image](https://user-images.githubusercontent.com/31852897/187665472-6a3321d7-9800-41a7-b929-fad78a3e549c.png)
![image](https://user-images.githubusercontent.com/31852897/187665627-5c0c008a-1298-4148-b2df-e56d55ad158a.png)
![image](https://user-images.githubusercontent.com/31852897/187665584-b72d30b6-74d2-443d-bfa2-39ab8da08d6f.png)
trySetCapacity 设置的key 与 offer使用的key不同 导致报错未设置

**Redis version**
6.2.7
**Redisson version**
3.17.6
**Redisson configuration**

**Comment by JavaLionLi** [comment]
![image](https://user-images.githubusercontent.com/31852897/187837865-cc1732e9-ae81-45ac-87fb-7ed168e3015a.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
