### ISSUE TITLE
Config parsing exception in JDK17 by jackson with afterburner module

### ISSUE THREAD

**Issue by semistone** [redisson/redisson#4522]
**Expected behavior**
could use jackson with afterburner to parse json string to SingleServerConfig in JDK17 (JDK11 is fine)

**Actual behavior**
throw exception
`Exception in thread "main" java.lang.IllegalAccessError: class rapid.shaded.org.redisson.config.SingleServerConfig$Creator4JacksonDeserializer19093950 tried to access method 'void rapid.shaded.org.redisson.config.SingleServerConfig.<init>()' (rapid.shaded.org.redisson.config.SingleServerConfig$Creator4JacksonDeserializer19093950 is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @71c3b41; rapid.shaded.org.redisson.config.SingleServerConfig is in unnamed module of loader 'app')`

**Steps to reproduce or test case**

HashMap<String, Object> map = new HashMap<>();

HashMap<String, String> map2 = new HashMap<>();
map2.put("address", "test");
map.put("singleServerConfig", map2);
new ObjectMapper().registerModule(new AfterburnerModule()).convertValue(map, Config.class);

**Redis version**

**Redisson version**
3.17.0
**Redisson configuration**

This is a minor issue, but just need to add public constructor in SingleServerConfig
https://github.com/redisson/redisson/blob/ac5b0cba06723dd4c38f4d016190da5166040e76/redisson/src/main/java/org/redisson/config/SingleServerConfig.java#L62

**Comment by samuelmanaluhdoc** [comment]
Any updates?

**Comment by mrniko** [comment]
Redisson doesn't use AfterburnerModule
