### ISSUE TITLE
setIfAbsent fail is empty

### ISSUE THREAD

**Issue by zhuangzibin** [redisson/redisson#4523]
Hi!
I use : JDK17、spring-boot-starter-data-redis-reactive、redisson-spring-boot-starter、WebFlux

```
@Test
public void test() {
    reactiveStringRedisTemplate.opsForValue()
        .setIfAbsent("TEST", "1").block();

    reactiveStringRedisTemplate.opsForValue()
        .setIfAbsent("TEST", "1")
        .map(bool -> {
            // do not execute
            System.out.println(bool);
            return bool;
        })
        .defaultIfEmpty(true)
        .map(bool -> {
            // return 'true'
            System.out.println(bool);
            return bool;
        })
        .block();
}
```
When i depend 'spring-boot-starter-data-redis-reactive'.'setIfAbsent' was fail and it return false.
But when i depend 'spring-boot-starter-data-redis-reactive' and 'redisson-spring-boot-starter',i think will return 'false',but it return 'Mono.empty()'.

**Comment by zhuangzibin** [comment]
PR:https://github.com/redisson/redisson/pull/4531

**Comment by zhuangzibin** [comment]
PR:https://github.com/redisson/redisson/pull/4547/files

**Comment by mrniko** [comment]
merged
