### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException

### ISSUE THREAD

**Issue by CharlesZCB** [redisson/redisson#4526]
redis---->
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
redissson---->
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.11.0</version>
</dependency>

Question:
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=29, freeConnectionsCounter=value:61:queue:0, freezed=false, freezeReason=null, client=[addr=redis://127.0.0.1:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@597586931 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xa7aa7bc5, L:/127.0.0.1:62043 ! R:127.0.0.1/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4ed81d14(failure: java.util.concurrent.CancellationException)], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec]], command: (EVAL), params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, key, 30000, 291023d7-83f5-47b5-ba8e-d69619fe48ea:94] after 3 retry attempts

**Comment by a25017012** [comment]
如果还需要，加下我wx demo给我下？

**Comment by mrniko** [comment]
Try to follow these steps: https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
