### ISSUE TITLE
What if number of RedissonLocalCachedMap > subscriptionConnectionPoolSize?

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#4528]
Any problem if number of RLocalCachedMap > subscriptionConnectionPoolSize?
My application has 2000 RLocalCachedMap but subscriptionConnectionPoolSize is 50 by default. 
Is it ok?
This is my config
`config.useSentinelServers()
            .....
                .setSubscriptionsPerConnection(100)
                .setSlaveConnectionPoolSize(1000)
                .setMasterConnectionPoolSize(1000);`
Any advice on the configuration? 
Thanks

**Comment by mrniko** [comment]
You can just increase `subscriptionsPerConnection` in that case.
