### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Command execution timeout for command: (EVAL)

### ISSUE THREAD

**Issue by alexfarm** [redisson/redisson#4532]
# Phenomenon description
Our service is using Redisson to connect to Redis cluster.Recently when encountering sudden high concurrent traffic, there were many RedisTimeoutExceptions: command execution timeout for command (EVAL)... (the omitted part is Lua's lock and unlock logic). After several days of observation, it will generally automatically recover.
We found that with the rise of traffic, the count of client connection of the Redis node will remain in a platform stage. At this stage, the most errors are reported, and then it quickly rises to a value. At this time, the error will automatically recover. The following is the curve of client connection and the curve of error reporting.
![1](https://user-images.githubusercontent.com/17567534/188770396-be1de1a7-0e86-4530-a3ca-dabbe8242fb6.jpeg)
![2](https://user-images.githubusercontent.com/17567534/188770413-aefeb445-4b8f-4757-807a-10292fefc0d3.jpeg)

# Version
Redisson 2.9.2 
redis is in sentinel mode with 1 master and 2 slave.
There are 8 nodes for application 
The maximum number of threads configured for redis client is 100, that is 800. 
The minimum number of idle threads is 20. The initial number in the figure is more than 300, because other applications share the redis cluster.

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, ...
org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:538)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)\n\tat java.lang.Thread.run(Thread.java:745)

Please help,Thank you!

**Comment by mrniko** [comment]
Try this steps https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
