### ISSUE TITLE
after service startup,  redisson occupies about 150 local ports

### ISSUE THREAD

**Issue by LiouChong** [redisson/redisson#4533]
we config redisson like this
```
@Bean
  public RedissonClient redisson() {
    String[] nodeArray = clusterNodes.split(",");
    for (int i = 0; i < nodeArray.length; i++) {
      nodeArray[i] = "redis://" + nodeArray[i];
    }

    Config config = new Config();
    ClusterServersConfig clusterServersConfig =
        config.useClusterServers().addNodeAddress(nodeArray);
    if (password != null && !password.isEmpty()) {
      clusterServersConfig.setPassword(password);
    }
    return Redisson.create(config);
  }
```
the variable clusterNodes is redis ip and port, value like this```
clusterNodes 
 = "10.0.2.151:7000,10.0.2.152:7001,10.0.2.153:7002,10.0.2.154:7003,10.0.2.155:7004,10.0.2.156:7005".```
and in out project, we  also use Lettuce to save value in redis. But after the service startup, there is a problem that **we use `netstat -nap ` will find a large number of redis connections（about 150+）, and  a large number of port is occupied.** 
![image](https://user-images.githubusercontent.com/37368428/189036707-616512c4-8e5a-4d2d-a002-f734707519d4.png)

![image](https://user-images.githubusercontent.com/37368428/189035185-05c0e6a9-24d5-42cc-b95b-9a31047972d1.png)

But after we remove redisson config bean, and remove the code dependency on redisson, the problem will not appear. 
The redisson version is 3.17.4,

**Comment by mrniko** [comment]
reduce connection pool size for both master and slave nodes.
