### ISSUE TITLE
Redisson connecting to Redis Instance via hostname

### ISSUE THREAD

**Issue by DavidDev21** [redisson/redisson#4534]
Does Redisson support connecting to a redis server via hostname or is it strictly limited to using static IP addresses?

I am attempting to use the hostname to connect but it seems like Reddisson is having difficulty resolving the hostname.
I can ping the server from the same machine perfectly fine with the hostname, yet Redisson cannot resolve the hostname.

The server and my machine are on the same network.

Exception message:
Exception in thread "main" org.redisson.client.RedisConnectionException: java.netUnknownHostException: Failed to resolve '[hostname]' after 6 queries

**Comment by a25017012** [comment]
Which version is used

**Comment by MXinH** [comment]
版本3.17.0

**Comment by mrniko** [comment]
Sure it supports hostnames. You need to check your dns resolver
