### ISSUE TITLE
Thread never returns

### ISSUE THREAD

**Issue by ycy1991** [redisson/redisson#4535]
my cod is:
     ThreadPoolExecutor updateLogWorkerExecutorService = new ThreadPoolExecutor(8,
              40,
              1000, TimeUnit.MILLISECONDS,
              new LinkedBlockingQueue<>(UPDATE_EXECUTOR_MAX_QUEUE_SIZE),
              new ThreadFactory() {
                  private final AtomicLong index = new AtomicLong();

                  @Override
                  public Thread newThread(Runnable r) {
                      return new Thread(r, String.format("UpdateLogWorker-%d", index.incrementAndGet()));
                  }
              }, new ThreadPoolExecutor.AbortPolicy());

      // 50ms插入一条记录 1s=20*20=400条
      ScheduledThreadPoolExecutor pullExecutorService = new ScheduledThreadPoolExecutor(1, r -> new Thread(r, "PullExecutorService"));

  class PullCallbackCacheMessageThread implements Runnable {
        @Override
        public void run() {
            try {
                if (!CLOSE_EVENT.get() && updateLogWorkerExecutorService.getQueue().size() <= UPDATE_EXECUTOR_MAX_QUEUE_SIZE) {
                    List<CallbackDTO> callbackDTOS = poll();
                    if (log.isDebugEnabled()) {
                        log.info("Pull from queue:{}", callbackDTOS.size());
                    }
                    if (CollUtil.isNotEmpty(callbackDTOS)) {
                      // new threadpool
                        updateLogWorkerExecutorService.execute(new UpdateWorkerThread(callMap));
                    }
                }
            } catch (Throwable e) {
                log.error("Pull callback message  error", e);
            }
        }
     private List<CallbackDTO> poll() {
                String realKey = CacheUtil.getCommonKey(RedisCacheKeys.CALLBACK_CACHE_LIST_NEW_KEY);
                RBlockingQueue<CallbackDTO> queue = redissonClient.getBlockingQueue(realKey);
                List<CallbackDTO> callbackDTOS = new ArrayList<>(callbackProperties.getPollLimit());
                queue.drainTo(callbackDTOS, callbackProperties.getPollLimit());
                return callbackDTOS;
            }
}

After going to k8s, it often occurs that messages cannot be consumed, check the thread stack, the thread has been waiting for redis to return messages
![image](https://user-images.githubusercontent.com/16506338/189293549-5a00e720-a8b4-401f-addd-3fdb6f405614.png)

I don't know why there is a situation where the thread waits forever and cannot return

**Comment by mrniko** [comment]
Can you reproduce it with the latest version?

**Comment by ycy1991** [comment]
I am using version 17.1. I have checked the fix of recent versions, but I can't see the code adjustment of the corresponding module. Do you think the new version has been fixed when you let me use the latest version?

**Comment by mrniko** [comment]
3.17.6 has fix for threads blocking issue

**Comment by ycy1991** [comment]
![image](https://user-images.githubusercontent.com/16506338/192245745-a3c3017b-8bdf-491a-a89b-51c4ca576b99.png)
        private List<CallbackDTO> poll() throws ExecutionException, InterruptedException, TimeoutException {
            String realKey = CacheUtil.getCommonKey(RedisCacheKeys.CALLBACK_CACHE_LIST_NEW_KEY);
            RBlockingQueue<CallbackDTO> queue = redissonClient.getBlockingQueue(realKey);
            List<CallbackDTO> callbackDTOS = new ArrayList<>(callbackProperties.getPollLimit());
            RFuture<Integer> future = queue.drainToAsync(callbackDTOS, callbackProperties.getPollLimit());
            future.get(500, TimeUnit.MILLISECONDS);
            return callbackDTOS;
        }
The new version still has problems, and a timeout period has been added, which occasionally occurs.

**Comment by ycy1991** [comment]
![image](https://user-images.githubusercontent.com/16506338/192246414-d19e00ad-65d4-4abf-ba83-7482e022e12e.png)
If this script has a query bottleneck, another thread that monitors the size should not query the data

**Comment by ycy1991** [comment]
![image](https://user-images.githubusercontent.com/16506338/192246759-ee5bac12-f701-4238-a368-4f5c6a1f1ae3.png)
Monitor thread print information

**Comment by ycy1991** [comment]
![image](https://user-images.githubusercontent.com/16506338/192247165-9a2cfc12-950f-4ac4-bec5-cc815e1eb28e.png)
Monitor thread print information

**Comment by mrniko** [comment]
> If this script has a query bottleneck, another thread that monitors the size should not query the data

Sorry, I don't follow which thread that monitors the size? Can you provide an example?
