### ISSUE TITLE
RedissonLocalCachedMap.computeIfAbsent() is 10X slower after upgrading v3.13.4 to v3.13.5

### ISSUE THREAD

**Issue by saeidN** [redisson/redisson#4540]
The reason for this slowdown appear to be this feature:

`Feature - merge(), compute(), computeIfAbsent(), computeIfPresent() methods implemented for RMap-based objects`

The above enhancement uses Lock which according to my profiler takes half a second to acquire a lock. That's very slow!
Is there a way to speed this up? We cannot upgrade to any higher version because of this.

**Comment by mrniko** [comment]
without introducing these locks methods were non thread-safe.

**Comment by saeidN** [comment]
But is it expected behavior that it should take about 500ms delay to acquire lock even when the lock is free?

**Comment by mrniko** [comment]
That depends on network and Redis. At first Redisson tries to acquire it ASAP. You can set debug mode and check which scripts executed

**Comment by saeidN** [comment]
Debugging let me to this script in RedissonLock class:

```
    <T> RFuture<T> tryLockInnerAsync(long waitTime, long leaseTime, TimeUnit unit, long threadId, RedisStrictCommand<T> command) {
        internalLockLeaseTime = unit.toMillis(leaseTime);

        return evalWriteAsync(getName(), LongCodec.INSTANCE, command,
                "if (redis.call('exists', KEYS[1]) == 0) then " +
                        "redis.call('hincrby', KEYS[1], ARGV[2], 1); " +
                        "redis.call('pexpire', KEYS[1], ARGV[1]); " +
                        "return nil; " +
                        "end; " +
                        "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then " +
                        "redis.call('hincrby', KEYS[1], ARGV[2], 1); " +
                        "redis.call('pexpire', KEYS[1], ARGV[1]); " +
                        "return nil; " +
                        "end; " +
                        "return redis.call('pttl', KEYS[1]);",
                Collections.singletonList(getName()), internalLockLeaseTime, getLockName(threadId));
    }
```

**Comment by saeidN** [comment]
Question: how come `RedissonLocalCachedMap.computeIfAbsent()` needs lock but `RedissonLocalCachedMap.get()` and `RedissonLocalCachedMap.put()` don't need lock?

**Comment by mrniko** [comment]
put and get operations are atomic

**Comment by saeidN** [comment]
Thank you. Then I found solution to my problem. I will replaced `computeIfAbsent` with a pair of `get` and `put` since we don't care about `computeIfAbsent` executing as atomic operation.

Perhaps you should document it somewhere that `computeIfAbsent` is significantly slower than alternatives.
