### ISSUE TITLE
Removing certain object from RQueue doesn't seem to be working

### ISSUE THREAD

**Issue by pawelszyntar** [redisson/redisson#4541]
Hi,

I have a certain amount of items meeting some condition in Redis queues that I want to remove.
The general approach I am using:

```
public class CleanRedis<T> {

    private final RedissonClient redissonClient;

    public CleanRedis(RedissonClient redissonClient) {
        this.redissonClient = redissonClient;
    }

    public void removeFromQueues(boolean predicate) {
        List<String> keys = redissonClient.getKeys()
                .getKeysStreamByPattern("somePattern")
                .collect(Collectors.toList());

        for (String key : keys) {

            RQueue<T> queue = redissonClient.getQueue(key, new FstCodec());
            List<T> items = queue.readAll();

            for (T item : items) {
                if (predicate) {
                    queue.remove(item);
                }
            }
        }
    }
}
```

The problem is that this item is not removed and false is being returned..
When calling RQueue.contains(T item) I get false, even thought the item is in the queue, as its details are printed in logs.

I don't know if that helps, but I was testing this on a queue that has only one item. I wanted to remove that single item from the queue.

Can you please take a look at this?

Thanks

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test:

```java
        RQueue<Integer> queue = redisson.getQueue("test");
        queue.add(1);

        List<Integer> tt = queue.readAll();

        for (Integer integer : tt) {
            assertThat(queue.remove(integer)).isTrue();
        }
        assertThat(queue.size()).isZero();
```

FstCodec is deprecated

**Comment by pawelszyntar** [comment]
What other codec can I use instead?
Class is not annotated as deprecated though.
