### ISSUE TITLE
atomicLong.expireIfNotSet  error

### ISSUE THREAD

**Issue by Peterppan** [redisson/redisson#4542]
i want to set a key expire like that   
public boolean isIncrKeySuccess(String key){
        RAtomicLong atomicLong = redissonClient.getAtomicLong(key);
        long l = atomicLong.incrementAndGet();
        if(l == 1L){
            atomicLong.expireIfNotSet(Duration.ofSeconds(keyExpire));
        }
        return false;
    }

then

org.redisson.client.RedisException: ERR Error running script (call to f_3fd750e0b43af99dbd223e5523718f18cded3664): @user_script:1: @user_script: 1: Wrong number of args calling Redis command From Lua script. channel: [id: 0xca667048, L:/172.168.0.150:55593 - R:172.168.0.210/172.168.0.210:7001] command: (EVAL), promise: java.util.concurrent.CompletableFuture@1481b82e[Not completed, 1 dependents], params: [local result = 0;for j = 1, #KEYS, 1 do local expireSet; if ARGV[2] ~= '' then expireSet = redis.cal..., 1, 123, 30000, NX]

how to fix it ,please.

**Comment by Peterppan** [comment]
by the way the redisson version is 

           <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>3.17.1</version>
            </dependency>

**Comment by mrniko** [comment]
Which Redis version?

**Comment by Peterppan** [comment]
Redis version is 6.2.4
