### ISSUE TITLE
RedisTimeoutException:Unable to get connection! Node source: NodeSource

### ISSUE THREAD

**Issue by nishubin** [redisson/redisson#4544]
Expected behavior
Should work without any exception.

Actual behavior

Random exception I can't reproduce
Calling Rlock.ulock() after the server has been running for a period of time (days or months?) will throw the following exception:

org.redisson.client.RedisTimeoutException:Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=32, freeConnectionsCounter=112, freezed=false, freezeReason=null, client=[addr=redis://redis.public-app-prod.svc:6379], nodeType=MASTER, firstFail=0]]], command: (EVAL), command params: [local mode = redis.call('hget', KEYS[1], 'mode'); if (mode == false) then redis.call('publish', KEYS..., 2, lock:srm-primary:ADD_PUR_TASK, redisson_rwlock:{lock:srm-primary:ADD_PUR_TASK}, 1, 30000, f31e3332-4558-4feb-a569-0efaa6bbce11:29275:write] after 3 retry attempts
at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:703)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
at java.lang.Thread.run(Thread.java:748)

The exception is that redisTemplate can still work normally to get data
Calling Rlock.ulock() or Rlock.trylock() will cause an exception
Service restarts back to normal

Redisson version
3.9.1

Redisson configuration
single node
redisson initialized via redisson-spring-boot-starter

Why does this exception occur, and how to reproduce this exception stably?
How to fix this exception?

**Comment by mrniko** [comment]
[Did you try to increase [con](https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception)](https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception)
