### ISSUE TITLE
createGroupAsync results in multiple XGROUP CREATE calls if the stream already exists

### ISSUE THREAD

**Issue by dfontenot** [redisson/redisson#4548]
**Expected behavior**:
`XGROUP CREATE...` to only be called once

**Actual behavior**
From redis `MONITOR` command:
```
1663629851.942440 [0 172.17.0.1:56630] "XGROUP" "CREATE" "stream4" "stream4:consumergroup" "$" "MKSTREAM"
1663629853.488140 [0 172.17.0.1:56626] "XGROUP" "CREATE" "stream4" "stream4:consumergroup" "$" "MKSTREAM"
1663629855.089791 [0 172.17.0.1:56642] "XGROUP" "CREATE" "stream4" "stream4:consumergroup" "$" "MKSTREAM"
1663629856.690298 [0 172.17.0.1:56640] "XGROUP" "CREATE" "stream4" "stream4:consumergroup" "$" "MKSTREAM"
```

**Steps to reproduce or test case**
Tested via unit test (simplified):
1. Create redisson client for URL "redis://127.0.0.1:6379"
2. `client.getStream().createGroupAsync()`
3. create 1 consumer for the consumer group
4. write a value to the stream
5. read a value from the stream

redis monitor results show 1 call to XGROUP CREATE. Re-run test-case, see 4 calls. Not seeing multiple calls happening behind the scenes for any other redis command used.

**Redis version**
Redis 6.2

**Redisson version**
3.17.6

**Redisson configuration**
```
val config = Config()
config.useSingleServer().address = url
return Redisson.create(config)
```

Please let me know this if expected behavior of either redisson or redis itself.

**Comment by mrniko** [comment]
Unable to reproduce it.
