### ISSUE TITLE
Receiving REntity already exists on liveobject persist intermittently

### ISSUE THREAD

**Issue by jkotelly1** [redisson/redisson#4552]
Our system uses RLiveObjects to store individual tasks which are annotated with 1 @RId and 2 @RIndex. When invoking persist on many tasks under load, we intermittently receive an IllegalArgumentException with the text "This REntity already exists." We have proven that the ID we are attempting to persist has not been added previously, as we performed a get() just prior to persisting with the same id.
After the exception, if we perform a get(), we receive back a task with the same id but the remainder of the task data null, indicating that the ID was hashed in but not the other indexes or the rest of the class.

Is this a known issue ?  We are using <redisson.spring.data.version>3.17.3</redisson.spring.data.version>.

**Comment by mrniko** [comment]
Try to use lock to avoid parallel id creation between `get` and `persist` methods invocations
