### ISSUE TITLE
How to create secondary index in REDIS using Reddison

### ISSUE THREAD

**Issue by dunstanmillwright** [redisson/redisson#4564]
We are using RMAP for write through cache. How we can secondary index some attributes of entity object for querying?

Person {
 Long   id;  //Primary Key
 String  name ; //Secondary Index to do search based on this.
}

Do i have to use Redistemplate to send commands to REDIS to create Index?

**Comment by mrniko** [comment]
You can use LiveObjects https://github.com/redisson/redisson/wiki/9.-distributed-services/#923-search-by-object-properties
