### ISSUE TITLE
CVEs in Netty dependency

### ISSUE THREAD

**Issue by wilkina** [redisson/redisson#4565]
There are multiple moderate security issues in the netty version (4.1.59.Final) brought in by the Redisson library. See https://github.com/netty/netty/security/advisories where 4.1.77.Final is the most recent version with fixed CVEs (4.1.82.Final is absolute latest right now).

This may not generally be an issue when communicating with trusted Redis servers, but brought into an application that also uses netty with other sources, it could be harder to use a safe version of netty.

**Expected behavior**
n/a

**Actual behavior**
n/a

**Steps to reproduce or test case**
mvn dependency:tree | grep netty
Any with 4.1.59.Final

**Redis version**
n/a

**Redisson version**
3.17.6

**Redisson configuration**
n/a

**Comment by mrniko** [comment]
Redisson 3.17.6 uses netty 4.1.79
