### ISSUE TITLE
Exceptions when updating redis engine in AWS Elasticache on the fly

### ISSUE THREAD

**Issue by NikitaLos** [redisson/redisson#4567]
We tried to update redis engine from 6.0.5 to 6.2.5  in our Elasticache Redis cluster. When AWS starts updating we see lots of <html>

```
org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://<ipaddres_of_node>:6379 has further redirect to rediss://<dns_name_of_node>:6379
```

Before this exception start to happen i see such logs 

```
14:18:08,349 [redisson-netty-10-2] INFO  o.r.c.ClusterConnectionManager - slave: rediss://<ipaddres_of_node>:6379 added for slot ranges: [[8194-8739]]

14:18:08,349 [redisson-netty-10-2] INFO  o.r.c.p.PubSubConnectionPool - 1 connections initialized for <ipaddres_of_node>/<ipaddres_of_node>:6379

14:18:08,370 [redisson-netty-10-3] INFO  o.r.c.ClusterConnectionManager - slave rediss://<ipaddres_of_node>:6379 removed for slot ranges: [[8194-8739]]

14:18:08,400 [redisson-netty-10-3] INFO  o.r.c.p.MasterPubSubConnectionPool - 1 connections initialized for <ipaddres_of_node>/<ipaddres_of_node>:6379

14:18:08,445 [redisson-netty-10-4] INFO  o.r.c.ClusterConnectionManager - master: rediss://<ipaddres_of_node>:6379 added for slot ranges: [[8194-8739]]

14:18:08,446 [redisson-netty-10-4] INFO  o.r.c.p.MasterConnectionPool - 16 connections initialized for <ipaddres_of_node>/<ipaddres_of_node>:6379
```

**Redis version**
6.0.5
**Redisson version**
3.17.4
**Redisson configuration**
idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 30000
  keepAlive: true
  tcpNoDelay: true
  nameMapper: !<org.redisson.api.DefaultNameMapper> {}
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 0
  slaveConnectionPoolSize: 0
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 16
  masterConnectionPoolSize: 64
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  dnsMonitoringInterval: 5000
  natMapper: !<org.redisson.api.DefaultNatMapper> {}
  scanInterval: 25
  checkSlotsCoverage: true
threads: 16
nettyThreads: 4
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: true
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: true
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory>

**Comment by NikitaLos** [comment]
I executed test again with enabled TRACE logs for ClusterConnectionManager. Here these logs along with error logs, started several minutes before i launched engine upgrade in AWS.
[redisson.txt](https://github.com/redisson/redisson/files/9666239/redisson.txt)

**Comment by mrniko** [comment]
@NikitaLos 

I'm sorry but there is no TRACE log entries in your log

**Comment by NikitaLos** [comment]
@mrniko I enabled trace level for org.redisson.cluster and that is all that i received.

**Comment by mrniko** [comment]
@NikitaLos 

Please enable it for `org.redisson`

**Comment by mrniko** [comment]
@NikitaLos 

I need logs with cluster state from ClusterConnectionManager and MOVED responses and all corresponding requests

**Comment by servionsolutions** [comment]
This may be related to a problem I am seeing during maintenance or failover test.  Please see https://github.com/redisson/redisson/issues/4653

I was able to craft a small sample application to reproduce the issue, and included all the TRACE logs for org.redisson.  Hopefully this helps solve the problem

**Comment by mrniko** [comment]
MOVED redirection loop error fixed in https://github.com/redisson/redisson/issues/4656
