### ISSUE TITLE
How to safely add field to an object which is already used ? 

### ISSUE THREAD

**Issue by zengbotang** [redisson/redisson#4570]
for example,I have an object name Foo with tow fields
`class Foo {`
`private int id;`
`private String name;`
`}`

and store in `RSet<Foo>`.

Later I have to add a field to the Foo as follow
`class Foo {`
`private int id;`
`private String name;`
`private int age;`
`}`

then I found that I can not remove Foo instance from `RSet` even though the instance is get from `RSet`,because there are many older instances without age field.

So I confuse that How to add field to an object and the new object can still compatible with values in redisson?  Thanks a lot.

redisson version: 3.16.8
codec: `org.redisson.codec.MarshallingCodec`

**Comment by mrniko** [comment]
RSet (as well as Redis Set object) uses serialized state to check object uniqueness
