### ISSUE TITLE
Locking Against AWS MemoryDB Cluster Fails with: ERR WAIT cannot be used with replica instances 

### ISSUE THREAD

**Issue by lopez-ufarte** [redisson/redisson#4573]
We are using Redisson and AWS MemoryDB cluster for locking.  We are running into intermittent failures during locking operations.  The error from Redis is:

`ERR WAIT cannot be used with replica instances. Please also note that since Redis 4.0 if a replica is configured to be writable (which is not the default) writes to replicas are just local and are not propagated.. channel: [id: 0xee5d2134, L:/172.30.80.188:52884 - R:10.51.142.62/10.51.142.62:6379] command: (WAIT), promise: java.util.concurrent.CompletableFuture@2a48dc53[Not completed], params: [1, 1000]`

We are configuring the Redisson client programmatically:

 ```
org.redisson.config.Config config = new org.redisson.config.Config();
        config.useClusterServers()
                .addNodeAddress(redisUrl)   
                .setUsername(user)
                .setPassword(password)
                .setRetryAttempts(5)
                .setRetryInterval(5000)
                .setTimeout(10000);

```
the redisUrl is a typical MemoryDB cluster URL specified by AWS that looks like this:

`clustercfg.<our-cluster-name>.0cfvkh.memorydb.us-east-1.amazonaws.com:6379 `

Do we need to change our client configuration to get around this? Any help with this issue would be appreciated.

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` and share output?

**Comment by lopez-ufarte** [comment]
Hi, sorry for the delay getting back with logs.  Look for the following to find the locking errors.  Thanks for any help you can provide.

`Unexpected error getting lock for account-id=`
[sms-syndicator (3).txt](https://github.com/redisson/redisson/files/9709458/sms-syndicator.3.txt)

**Comment by mrniko** [comment]
Thanks for the logs. This is an issue of AWS where the same hosts redirects to itself. You need to contact reach their support.

**Comment by lopez-ufarte** [comment]
Hi @mrniko 
We are still having this issue in out set up.  I posted in AWS as suggested.  Here is their response:

https://repost.aws/questions/QUGjBeYP81SZmymwWC_2YcLA/locking-against-aws-memory-db-cluster-fails-with-err-wait-cannot-be-used-with-replica-instances

We would like to find a solution to this before moving on to a different client.  Thanks for any help you can provide

**Comment by dropofwill** [comment]
Closing the loop on this it turns out this was caused by our Istio setup, which was making the Redisson code think it was in a redirect loop. For our case setting `resolution: NONE` fixed it, exactly like what was reported here: https://github.com/redisson/redisson/issues/4144#issuecomment-1057050238

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/6223
