### ISSUE TITLE
Possibility of key conflict when using JndiRedissonFactory for Tomcat Sessions

### ISSUE THREAD

**Issue by kokhoor** [redisson/redisson#4575]
When storing tomcat session, the key is:

`String name = keyPrefix + separator + "redisson:tomcat_session:" + sessionId;`

Using global context.xml means a keyPrefix cannot be added automatically based on context name.

Will it be possible a session id in one context say /a overwrites a session id in another context say /b?

If yes, should the key generation be amended to following instead?

`String name = keyPrefix + separator + "redisson:tomcat_session:" + sessionId + ":" + getContext().getName();`

Thanks.

**Comment by mrniko** [comment]
> Will it be possible a session id in one context say /a overwrites a session id in another context say /b?

I don't think so since session id is 128 bits by default and generated by Secure Random generator
