### ISSUE TITLE
ByteBuf leak if any exception comes from Codec

### ISSUE THREAD

**Issue by BamDoo** [redisson/redisson#4576]
In RedissonMap `putAll` if encoding fails for 1 of the key or value, it doesn't not release already allocated bytebufs.

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMap.java#L776
```
    protected RFuture<Void> putAllOperationAsync(Map<? extends K, ? extends V> map) {
        List<Object> params = new ArrayList<>(map.size()*2 + 1);
        params.add(getRawName());
        for (java.util.Map.Entry<? extends K, ? extends V> t : map.entrySet()) {
            checkKey(t.getKey());
            checkValue(t.getValue());

            params.add(encodeMapKey(t.getKey()));
            params.add(encodeMapValue(t.getValue()));
        }

        RFuture<Void> future = commandExecutor.writeAsync(getRawName(), codec, RedisCommands.HMSET, params.toArray());
        return future;
    }
```

If there are 2 entries, and encoding of key/value allocated bytebufs for 1st entry, and if it fails for 2nd entry...then bytebufs allocated for 1st entry are not released.

**Expected behavior**
Library should release all bytebuf in case of exception.

**Actual behavior**
It's not releasing already allocated bytebufs.

**Steps to reproduce or test case**
1. get RMap instance with some custom codec
2. call putAll("a", "foo", "b", "bar").... in custom codec throw exception if value.equals("bar")

**Redis version**
6.x

**Redisson version**
3.17.6

**Redisson configuration**
library default configuration

**Comment by mrniko** [comment]
All Codecs release ByteBuf if data can't be encoded

**Comment by BamDoo** [comment]
Yes, All codecs can and will release the bytebuf it created while encoding current input. However, it can't release bytebufs already created for previous inputs.

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonMap.java#L776
```
 for (java.util.Map.Entry<? extends K, ? extends V> t : map.entrySet()) {
            checkKey(t.getKey());
            checkValue(t.getValue());

            params.add(encodeMapKey(t.getKey()));
            params.add(encodeMapValue(t.getValue()));
        }
```

in this for loop, where params is holding the bytebuffs allocated for entry1, how and who will be responsible for releasing bytebuffs in `params` list, if lets say encoding fails for the 2nd entry in this loop.

**Comment by BamDoo** [comment]
@mrniko  - is the issue clear or do you need some sample code to generate this issue ?

**Comment by mrniko** [comment]
Fixed. Thanks for report.
