### ISSUE TITLE
Frequent timeouts in production while accessing redis cache using redisson

### ISSUE THREAD

**Issue by SaiSingamsetty** [redisson/redisson#4579]
We are using redisson 3.17.6 in spring boot 1.5 application to communicate with AWS's Elasticache redis nodes.
The service experience lot of traffic at times for a few APIs which call redis (2500-4000 requests per minute)
During these spikes, at times we experience a lot of RedisResponseTimeoutException, RedisTimeoutException, etc

We have increased our netty thread count to 64. other parameters are set to defaults.
We do not see much detailed info on netty threads, we have increased from 32 to 64 & still seeing the issue. Not sure about the impact if it is brought to 128 or more. How do we calculate this ?

**Below are the stack traces**

`org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://10.0.6.83:6379]\
\	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:244) ~[redisson-3.17.6.jar!/:3.17.6]\
\	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) [netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) [netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) [netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) [netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) [netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]\`

`org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts, is non-idempotent command: false Check connection with Redis node: 10.0.6.94/10.0.6.94:6379 for TCP packet drops.  Try to increase nettyThreads and/or timeout settings. Command: (HGET), params: [paymentGatewaySettingsRedisMap, PooledUnsafeDirectByteBuf(ridx: 0, widx: 105, cap: 256)], channel: [id: 0xf4128aa1, L:/10.0.236.33:40056 - R:10.0.6.94/10.0.6.94:6379]\
\	at org.redisson.command.RedisExecutor.lambda$scheduleResponseTimeout$8(RedisExecutor.java:387) ~[redisson-3.17.6.jar!/:3.17.6]\
\	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]\
\	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]",`

**Comment by qqwangxiaow** [comment]
I met the same problem when I update redisson verson from 3.13.4 to 3.16.7.

org.redisson.client. RedisResponseTimeoutException: Redis server response timeout (200 ms) occured after 0 retry attempts, is non-idempotent command: false Check connec tion with Redis node: 172.20.108.12/172.20.108.12:6821 for TCP packet drops. Try to increase nettyThreads and/or timeout settings. Command: (RANGE), params: [r:og_r cm_recall: 1076214287:[ranklist]::o, 0, -1], channel: [id: 0x4e0181d4, L:/172.23.114.38:53202 - R:172.20.108.12/172.20.108.12:6821]
at org. redisson. command. RedisExecutor. lambdaSscheduleResponseTimeoutS8(RedisExecutor. java:387) at org.redisson.connection.MasterSlaveConnectionManagerS2.run(MasterSlaveConnectionManager.java:664) at io.netty.util.HashedWheelTimerSHashedWheelTimeout.run(HashedWheelTimer.java:715) at io.netty.util.concurrent. ImmediateExecutor.execute(ImmediateExecutor. java: 34)) at io.netty.util.HashedWheelTimerSHashedWheelTimeout.expire(HashedWheelTimer.java:703) at io.netty.util.HashedWheelTimerSHashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) at io.netty.util.HashedWheelTimerSWorker.run(HashedWheelTimer.java:503) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Thread. java:834)

**Comment by qqwangxiaow** [comment]
> SaiSingamsetty
Hi，Have you solved the problem？

**Comment by SaiSingamsetty** [comment]
@qqwangxiaow We have upgraded the spring boot to 2.3.12 for some other purpose - graceful shutdown & Radisson to the latest version. Since then, we did not see these issues luckily.
