### ISSUE TITLE
ClusterConnectionManager removes slots in case of errors while parsing partitions

### ISSUE THREAD

**Issue by subbotinkv** [redisson/redisson#4581]
**Expected behavior**
In case of any errors while cluster topology scanning ClusterConnectionManager should reschedule it.

**Actual behavior**
In case of errors (e.g. DNS resolution errors) while parsing partitions got from CLUSTER NODES command, ClusterConnectionManager continue processing and updates cluster topology with partially parsed partitions which leads to removing slots from known cluster topology and errors while performing reading/writing ops on removed slots. 

**Steps to reproduce or test case**

1. Set up big enough (100+ nodes) Redis Cluster /w TLS (or ElastiCache cluster) enabled (it will return DNS names instead of IPs for CLUSTER NODES commands);
2. Run application doing some reading/writing ops on the cluster;
3. Wait till getting DNS resolution errors (or emulate any other errors) while cluster topology scanning and partitions parsing;

**Redis version**
6.2.6

**Redisson version**
3.17.6

**Comment by mrniko** [comment]
Fixed. Problems with DNS resolution will be fixed in https://github.com/redisson/redisson/issues/1625

**Comment by subbotinkv** [comment]
Hey, @mrniko. It is mostly about DNS issues, but not only. As far as I can see, you've already substituted `handle` to `thenApply` while I was creating a PR, but there is  some additional error handling in my one, please, take a look: https://github.com/redisson/redisson/pull/4604. Hope, you will find it useful.
