### ISSUE TITLE
Redisson Client creating more connections to Redis (Elastic cache cluster) than expected

### ISSUE THREAD

**Issue by samanthjain** [redisson/redisson#4585]
We are using Redisson client(**3.11.5 version**) for distributed lock use-case.
We are using 8 primary and 8 replica in AWS Elastic cache.
Redisson is a singleton object in our Java application instance.

We are noticing Redisson client creating more than max connections configured.  Noticed that 24K+ active connections were created from single application instance
Max master connections configured was 1000.

{code}

@Bean
public Redisson clusterServerRedisson() {
        final StringBuilder serverAddress = new StringBuilder()
                .append("rediss://")
                .append(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_HOST))
                .append(":")
                .append(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_PORT, Integer.class));
        final String redisPassword = this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_PASSWORD);

        final Config config = new Config();

        final ClusterServersConfig clusterServersConfig = config.useClusterServers();
        clusterServersConfig.addNodeAddress(serverAddress.toString());
        if (StringUtils.isNotBlank(redisPassword)) {
            clusterServersConfig.setPassword(redisPassword);
        }
        // Redis cluster scan interval in milliseconds.
        clusterServersConfig.setScanInterval(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CLUSTER_SCAN_INTERVAL_TIMEOUTMILLIS, int.class));

        // Redis 'master' node maximum connection pool size
        clusterServersConfig.setMasterConnectionPoolSize(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CONNECTION_MAX_POOL_SIZE, int.class));

        // Redis 'master' node minimum idle connection amount for each master node
        clusterServersConfig.setMasterConnectionMinimumIdleSize(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CONNECTION_MIN_IDLE_SIZE, int.class));

        // Timeout in milliseconds during connecting to any Redis server.
        clusterServersConfig.setConnectTimeout(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CONNECTION_TIMEOUTMILLIS, int.class));

        // Operation timeout - counter starts once command has been sent to the redis server
        // Redis server response timeout in milliseconds. Starts to countdown when Redis command was succesfully sent.
        clusterServersConfig.setTimeout(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_OP_TIMEOUTMILLIS, int.class));

        clusterServersConfig.
        // For connection failures outside of the (jedis) pool
        clusterServersConfig.setRetryAttempts(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CONNECTION_MAX_RETRY_COUNT, int.class));
        clusterServersConfig.setRetryInterval(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CONNECTION_RETRY_DELAYMILLIS, int.class));

        // Since we use redis primarily as a messaging conduit (PubSub), we tune the following items
        clusterServersConfig.setSubscriptionsPerConnection(
                this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_SUBSCRIPTION_PER_CONNECTION_SIZE, int.class));
        clusterServersConfig.setSubscriptionConnectionPoolSize(
                this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_SUBSCRIPTION_CONNECTION_MAX_POOL_SIZE, int.class));

        clusterServersConfig.setClientName(this.environment.getRequiredProperty(RedisPropertyConstants.REDIS_REDISSON_CONNECTION_NAME, String.class));

        return (Redisson)Redisson.create(config);
    }

{code}
## Redisson Client for Redis
redis.redisson.cluster.scan.interval.timeoutMillis=30000
redis.redisson.connection.name=MY-APP-REDISSON-POOL
redis.redisson.connection.max.pool.size=1000
redis.redisson.connection.max.retry.count=10
redis.redisson.connection.min.idle.size=100
redis.redisson.connection.retry.delayMillis=1500
redis.redisson.connection.timeoutMillis=60000
redis.redisson.idle.connection.timeoutMillis=10000
redis.redisson.lock.timeoutMillis=10000
redis.redisson.op.timeoutMillis=30000
redis.redisson.subscription.connection.max.pool.size=50
redis.redisson.subscription.per.connection.size=10

public class RedisLock implements DistributableLock {

    private final RedisConfigManager redisConfigManager;
    private final Redisson redisson;

    public RedisLock(final Redisson redisson) {
        this.redisson = this.redisConfigManager.getRedisson();
    }

    @Override
    public void acquireLock(final Object object) {
        getLockInstance(object).lock(this.redisConfigManager.getLockTimeoutInMillis(), TimeUnit.MILLISECONDS);
    }

    @Override
    public void releaseLock(final Object object) {
        getLockInstance(object).unlock();
    }

    @Override
    public boolean tryWriteLock(final Object object) {
        return getReadWriteLockInstance(object).writeLock().tryLock();
    }

    @Override
    public void acquireReadLock(final Object object) {
        getReadWriteLockInstance(object).readLock().lock();
    }

    @Override
    public void releaseReadLock(final Object object) {
        getReadWriteLockInstance(object).readLock().unlock();
    }

    @Override
    public void acquireWriteLock(final Object object) {
        getReadWriteLockInstance(object).writeLock().lock(this.redisConfigManager.getLockTimeoutInMillis(), TimeUnit.MILLISECONDS);
    }

    @Override
    public void releaseWriteLock(final Object object) {
         getReadWriteLockInstance(object).writeLock().unlock();
    }

    private RLock getLockInstance(final Object object) {
        Assert.notNull(object, "Cannot lock or unlock a null object");

        final RLock rLock = this.redisson.getLock(Integer.toString(object.hashCode()));
        if (rLock == null) {
            throw new IllegalStateException("Cannot get lock instance.");
        }
        return rLock;
    }

    private RReadWriteLock getReadWriteLockInstance(final Object object) {
        Assert.notNull(object, "Cannot lock or unlock a null object");

        final RReadWriteLock rwLock = this.redisson.getReadWriteLock(Integer.toString(object.hashCode()));
        if (rwLock == null) {
            throw new IllegalStateException("Cannot get read write lock instance.");
        }
        return rwLock;
    }

}

Any help would be highly appreciable. Thanks in advance.

**Comment by mrniko** [comment]
Multiple problems with connections were resolved since 3.11.5. Especially in versions 3.12.2, 3.13.3, 3.14.1... You need to update to the latest version.
