### ISSUE TITLE
RBatch and RTransaction with RLocalCachedMap

### ISSUE THREAD

**Issue by shivangmittal01** [redisson/redisson#4587]
I understand that all the changes which needs to be in sync with local cache should be done through RLocalCachedMap. But how can RLocalCachedMap be used with RBatch? If we need to update all the items updated via RBatch or RTransaction in local cache, is there a way to notify the pub-sub?

```
RBatch batch = redissonClient.createBatch(BatchOptions.defaults().responseTimeout(150, TimeUnit.SECONDS).skipResult());

     RMapAsync<String, ItemInventory> map = batch.getMap("MyMap", inventoryCodec);
      bulkList.forEach(t -> map.fastPutAsync(t.getKey(), t));
     batch.execute().getResponses();
```

**Comment by mrniko** [comment]
You need to use transactions instead https://github.com/redisson/redisson/wiki/10.-additional-features/#104-transactions
