### ISSUE TITLE
compareAndSet on JsonBucket with path deletes whole document 

### ISSUE THREAD

**Issue by alxgrk** [redisson/redisson#4592]
**Expected behavior**

When calling `compareAndSet("$.foo", false, null)`, it should delete the property matching the path expression.

**Actual behavior**

Instead, it deletes the whole document.

**Steps to reproduce or test case**
_(more or less pseudo-code)_

```kotlin
redisson.getJsonBucket("test", StringCodec.INSTANCE).set("""{"foo": false, "bar":true}""")
redisson.getJsonBucket("test", StringCodec.INSTANCE).compareAndSet("$.foo", false, null)
val result = redisson.getJsonBucket("test", StringCodec.INSTANCE).isExists()
// result should equal true, but equals false
)
```

**Possible solution**

The problematic line in the code seems to be the following: https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonJsonBucket.java#L299

Instead of `+ "redis.call('json.del', KEYS[1]); "` it should probably be `+ "redis.call('json.del', KEYS[1], ARGV[1]); "`.

**Redis version**

6.2.7

**Redisson version**

3.17.6

**Redisson configuration**

**Comment by mrniko** [comment]
Thanks for report. Fixed
