### ISSUE TITLE
Question about Redission Set Conversion in Quarkus native

### ISSUE THREAD

**Issue by firdy94** [redisson/redisson#4593]
1) Create a reactive redission client using
- Redission.create(config).reactive()

2) Using that reactive client to retrieve a RSet
- reactiveClient.getSet<String>("running_set")

3) Next i convert the RSet Into a Kotlin Flow
reactiveClient.getSet<String>("running_set").iterator().asFlow()

The above steps is working fine in normal JVM mode but when running in quarkus native version 2.12.3

i am getting the following execption
java.lang.ClassCastException: org.redission.RedissionSet$1 cannot be cast to reactor.core.publisher.Flux

Any idea why this is happening?

Redission Version that i tried working on both giving same error
implementation('org.redisson:redisson-quarkus-20:3.17.7')
implementation('org.redisson:redisson-quarkus-20:3.17.4')

**Comment by mrniko** [comment]
Fixed. Thanks for report
