### ISSUE TITLE
Scheduling tasks on the gap between timezone and utc problem

### ISSUE THREAD

**Issue by pedromcs99** [redisson/redisson#4600]
Here is my problem:
I have a task that needs to be run every Thursday at a specific timezone.
But it seems to be a bug on redisson task scheduling when the timezone the task is set is not UTC and the now (TZ) time is between the chosen timezone and UTC.

`
RExecutor.schedule(new Task(), CronSchedule.of("0 0 16 * * 4", zoneId));
`

For example, the schedule is going to be to run at 16h (UTC+1) Thursday 13th of October and the time UTC is 15h and the current time is 15h30.

**Expected behaviour**
Schedule task Thursday 20th of October at 16h

**Actual behaviour**
Schedules the task in the past so the task is never run and it is not scheduled other task

Is this a redisson bug? Is there any workaround for this issue?

**Redis version** redis_version:4.0.2
**Redisson version** 3.17.7
**Redisson configuration** Default

**Comment by mrniko** [comment]
Can you try this version https://github.com/redisson/redisson/issues/4546#issuecomment-1277345009

**Comment by pedromcs99** [comment]
I tested with the **redisson-3.17.8-SNAPSHOT.jar** and the problem seems to be fixed. Thanks for your help!

However, I had to change the way the cron expressions were being built as this version seems to have a new parameter on the expressions. Updating the library to this version can break the expression building, so I would advise against making this change on a minor version.
