### ISSUE TITLE
Does Redisson client auto-recovers in case of master failover in Redis cluster mode

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#4606]
Using latest Redisson 3.17.x and Redis 7.x versions. 

Earlier we were using Redis sentinel mode where Redisson supports in case of failovers. Now we are migrating to Redis cluster mode with multiple masters, so does Redission auto recovers in case of master failover by Redis cluster bus or manual failover by Redis DBA?

**Comment by mrniko** [comment]
Yes

**Comment by rgampa** [comment]
Thanks @mrniko for prompt reply.
