### ISSUE TITLE
RateLimiterConfig should have  default values

### ISSUE THREAD

**Issue by Tanky-Zhang** [redisson/redisson#4609]
**Is your feature request related to a problem? Please describe.**
When I use the limiter, I find that if the limiter is not initialized or has been deleted，now "NumberFormatException" occurs if I invoke "limiter.getConfig().getRate()".
example:
![image](https://user-images.githubusercontent.com/48041180/196321565-53b00659-84da-4015-832f-a74d8843d947.png)
![image](https://user-images.githubusercontent.com/48041180/196321809-7a51bcfc-adcf-440a-b5a9-939680881802.png)

**Describe the solution you'd like**
After debuging, it was found that there is no nullifying process for map in the source code. I think there should be a better way to handle it, such as giving the default value or throwing an exception where the limiter does not exist, so I modified it and submitted pr.
https://github.com/redisson/redisson/pull/4608

**Comment by cy** [comment]
I'm also running into this issue - maybe instead of throwing or returning a default value it could simply return null?

**Comment by Tanky-Zhang** [comment]
> I'm also running into this issue - maybe instead of throwing or returning a default value it could simply return null?

yes,"return null" is also suitable,maybe more suitable,but it seems that maintiners don‘t  think this is a problem.

**Comment by mrniko** [comment]
merged
