### ISSUE TITLE
How to verify that expiration is occurring?

### ISSUE THREAD

**Issue by contentfree** [redisson/redisson#4617]
I have expiration configured for 10,000 milliseconds by a property in hibernate.cfg.xml, eg. `<property name="hibernate.cache.redisson.veryShortTerm.expiration.time_to_live">10000</property>`

How can I verify (with redis-cli) that expiration is happening? On what schedule does the "scheduled cleanup" occur and is that configurable (is that max_idle_time?)

**Comment by mrniko** [comment]
You can do it by monitoring size of Map objects stored in Redis.
