### ISSUE TITLE
Rmap values()  Data error

### ISSUE THREAD

**Issue by wl980868110** [redisson/redisson#4619]
![图片](https://user-images.githubusercontent.com/10094985/197151234-5509c826-9ad4-465c-8770-079389880da0.png)
![图片](https://user-images.githubusercontent.com/10094985/197151262-d5dd55aa-6363-4006-bb8f-c6a255c1a94f.png)
  String sectionInfo = Manages.serverMineManager.buildServerMineSectionGroupInfo(serverMineEntity);
    String cityMineMapKey = Manages.serverMineManager.buildCityMineMap(sectionInfo, cityId);
    RMap mineRDataMap = RedissonUtils.redisson.getRedissonClient().getMap(cityMineMapKey);
    List mineInfoAllList = new ArrayList(mineRDataMap.values());
    for (Iterator localIterator = mineInfoAllList.iterator(); localIterator.hasNext(); ) { Object object = localIterator.next();

      MineRData mineRData = (MineRData)object;

      if ((mineId == 0) || (mineId == mineRData.getMineId())) {
        mineInfoList.add(mineRData);
      }
    }
    if (mineInfoList.size() > 0) {
      redisInfo = LLJsonHelper.getJsonStringFromCollection(mineInfoAllList) + "<p/>" + LLJsonHelper.getJsonStringFromCollection(mineInfoList);
    }
mineInfoList.size() value is 2

Rmap  
values() 单个objet 变成了 数组
MarshallingCodec

**Comment by mrniko** [comment]
Please share the code to reproduce it

**Comment by wl980868110** [comment]
String sectionInfo = Manages.serverMineManager.buildServerMineSectionGroupInfo(serverMineEntity);
String cityMineMapKey = Manages.serverMineManager.buildCityMineMap(sectionInfo, cityId);
RMap mineRDataMap = RedissonUtils.redisson.getRedissonClient().getMap(cityMineMapKey);
List mineInfoAllList = new ArrayList(mineRDataMap.values());
for (Iterator localIterator = mineInfoAllList.iterator(); localIterator.hasNext(); ) { Object object = localIterator.next();

  MineRData mineRData = (MineRData)object;

  if ((mineId == 0) || (mineId == mineRData.getMineId())) {
    mineInfoList.add(mineRData);
  }
}
if (mineInfoList.size() > 0) {
  redisInfo = LLJsonHelper.getJsonStringFromCollection(mineInfoAllList) + "<p/>" + LLJsonHelper.getJsonStringFromCollection(mineInfoList);
}

**Comment by mrniko** [comment]
I mean test code which I can run to reproduce it.
