### ISSUE TITLE
Suggestions about RedissonMultiLock

### ISSUE THREAD

**Issue by TavenYin** [redisson/redisson#4628]
https://github.com/redisson/redisson/blob/34bcddc0121e1c5c447c2e3f68399fccd33f7b77/redisson/src/main/java/org/redisson/RedissonMultiLock.java#L343

I think it should be

```java
if (locks.size() - acquiredLocks.size() <= failedLocksLimit()) {
   break;
}
```
When I use the red lock, even though I have acquired enough locks, I still need to try in the next instance.

For example, I now have 7 Redis instances.

Failed to acquire the lock for the 6th time, and according to the current code, I will try it for the 7th time.
***
Or this way, I think it will be more perfect.
```java
            if (lockAcquired) {
                acquiredLocks.add(lock);
                if (locks.size() - acquiredLocks.size() == failedLocksLimit()) {
                    break;
                }
            } else {
                if (failedLocksLimit == 0) {
                    unlockInner(acquiredLocks);
                    if (waitTime <= 0) {
                        return false;
                    }
                    failedLocksLimit = failedLocksLimit();
                    acquiredLocks.clear();
                    // reset iterator
                    while (iterator.hasPrevious()) {
                        iterator.previous();
                    }
                } else {
                    failedLocksLimit--;
                }
            }
```

**Comment by mrniko** [comment]
RedLock is deprecated. Use Fenced Lock instead https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers/#810-fenced-lock
