### ISSUE TITLE
GCP Memorystore Standard Failover and SingleServer Mode expected to be recoverable?

### ISSUE THREAD

**Issue by cseverino789** [redisson/redisson#4633]
Trying to understand if this should be expected behavior or potentially a bug.

GCP Standard supports failover with non-read replica as described https://cloud.google.com/memorystore/docs/redis/high-availability. In this mode, the client applications should only need to worry about connecting to a single IP as there is no exposed replica IP.

When running a redisson client with the default SingleServerConfig, using stream i.e. (XREADGROUP) does not recover from the failover. The application detects the failover and exception is thrown:

`caused by: org.redisson.client.RedisException: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?). channel: [id: 0x7a0d3644, L:/10.0.0.219:54872 - R::6379] command: (XREADGROUP), promise: java.util.concurrent.CompletableFuture@224c1509[Not completed, 1 dependents], params: [GROUP, , , BLOCK, 100, STREAMS, [65, 100, 100, 72, 105, 116], >]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370) ~[redisson-3.17.7.jar!/:3.17.7]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198) ~[redisson-3.17.7.jar!/:3.17.7]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.17.7.jar!/:3.17.7]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[redisson-3.17.7.jar!/:3.17.7]`

The application has to be restarted even though the connection is restored ( Other calls PING, PENDING continue to occur). 

Should this case be handled by redisson? Or is this expected behavior and application code must be updated to handle it or run with read replicas when using blocking calls.

Reproducible with Redisson 3.17.7, GCP Standard 6.X. and issue manual failover using the gcp client as described https://cloud.google.com/memorystore/docs/redis/manual-failover-overview.

**Comment by mrniko** [comment]
It's a Redis setup issue. Redis instance you are connected to is acting as a slave, this is why you get that error.

**Comment by mrniko** [comment]
> On reconnect, your application is automatically redirected to the new primary node using the same connection string or IP address. You do not need to update your application after a failover.

Can you provide logs for `org.redisson` with `trace` logging level to check that IP has changed?
