### ISSUE TITLE
RQueue equals/remove issue (MarshallingCodec & FstCodec examples)

### ISSUE THREAD

**Issue by pawelszyntar** [redisson/redisson#4634]
Hi there,
I am getting an unusual behavior when removing item from RQueue.
It looks like it very much depends on the Codec and actual object reference being passed to remove(Object o) method invoked on RQueue.

Say we have a data object with getters, setters, all-args and empty constructors, equals, hashCode, toString implemented.
Class looks like this, no boilerplate code to simplify.
```
public class TestModel implements Serializable {
    private String key;
    private String traceId;
    private long createdAt;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TestModel message = (TestModel) o;
        return createdAt == message.createdAt && Objects.equal(key, message.key) && Objects.equal(traceId, message.traceId);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(key, traceId, createdAt);
    }
}
```
------------------------------------------
**Expected behavior**
remove(Object o) invoked on RQueue removes specified object

**Actual behavior**
remove(Object o) works differently depending on two factors: Codec used and object reference that is passed into the remove(Object o) method
When calling remove with object created in test - method works fine
When object is retrieved from queue it does not work as desired with MarshallingCodec

**Steps to reproduce or test case**
```
@Test
    public void removeTest() throws InterruptedException {
        System.err.println("Codec: " + redissonClient.getConfig().getCodec());
        System.err.println("==============");

        RQueue<TestModel> queue = redissonClient.getQueue("queue");

        TestModel msg = new TestModel("key", "traceId", 0L);
        System.out.println("Adding msg: " + msg + " to queue: " + queue.add(msg));
        System.out.println("Queue: " + queue);
        System.out.println("queue.peek(): " + queue.peek());
        System.out.println("queue.contains(queue.peek()): " + queue.contains(queue.peek()));
        System.err.println("msg.equals(queue.peek()): " + msg.equals(queue.peek()));
        System.out.println("queue.contains(msg): " + queue.contains(msg));
        System.err.println("queue.remove(queue.peek()): " + queue.remove(queue.peek()));
        System.out.println("Queue: " + queue);
        System.out.println("queue.remove(msg): " + queue.remove(msg));
        System.out.println("Queue: " + queue);

        Thread.sleep(10);
        System.err.println("==============");

        TestModel msg2 = new TestModel("key1", "traceId1", 0L);
        System.out.println("Adding msg2: " + msg2 + " to queue: " + queue.add(msg2));
        System.out.println("Queue: " + queue);
        System.out.println("queue.peek(): " + queue.peek());
        System.out.println("queue.contains(queue.peek()): " + queue.contains(queue.peek()));
        System.err.println("msg2.equals(queue.peek()): " + msg2.equals(queue.peek()));
        System.out.println("queue.contains(msg2): " + queue.contains(msg2));
        System.err.println("queue.remove(queue.peek()): " + queue.remove(queue.peek()));
        System.out.println("Queue: " + queue);
        System.out.println("queue.remove(msg2): " + queue.remove(msg2));
        System.out.println("Queue: " + queue);
    }
```

TESTS RESULTS:

MarshallingCodec:
![marshalling_codec_test](https://user-images.githubusercontent.com/43874019/198024442-ec576b20-8e03-4625-b556-de4b92f0d3f6.JPG)

FstCodec:
![fst_codec_test](https://user-images.githubusercontent.com/43874019/198024434-e267ad9a-57a3-4089-9fee-1d819cb2c4e5.JPG)

**Redis version**
redis:6.2.7-alpine

**Redisson version**
3.17.7

**Redisson configuration**
```
NatMapper natMapper = uri -> {
            return new RedisURI(uri.getScheme(), dockerHost, uri.getPort() + PORT_OFFSET);};
final var masterUrl = "redis://" + dockerHost + ":" + REDIS_MASTER_PORT;

config.useClusterServers()
                .setScanInterval(2000)
                .setNatMapper(natMapper)
                .addNodeAddress(masterUrl);
redissonClient =  Redisson.create(config);

**Comment by zsokolowski** [comment]
@mrniko this issue is something which could even critical for my project, could you take a look? Thanks

**Comment by will-guo-ncino** [comment]
@mrniko Getting the same issue with ScoredSortedSet. Could you take a look

**Comment by avcad** [comment]
As MarshallingCodec is working fine for us so far, it would be interesting if there are benchmarks available to compare it with Kryto. I guess we'll plan a performance test to compare them and see if it makes sense to move.

**Comment by mrniko** [comment]
@avcad 

I'll make Kryo5Codec default since next version.
