### ISSUE TITLE
Unable to write command into connection! 

### ISSUE THREAD

**Issue by white-balls** [redisson/redisson#4644]
Hello, when I used the API RBatch provided by Redison (version: 3.15.6) to add data to Redis, Redison prompted the following error:
Unable to write command into connection!  Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:63:queue:0, freezeReason=null, client=[addr=redis://], nodeType=MASTER, firstFail=0]]], connection:  RedisConnection@186126  [redisClient=[addr=redis://], channel=[id: 0xffb, ], currentCommand=null], command: null, params: null after 3 retry attempts"
I used a timed task. I called this method once an hour to add 4000 pieces of data to Redis. After testing for a week, this error occurred six times in total. I hope someone can help me answer this question. What should I do?

**Comment by mrniko** [comment]
Try to increase nettyThreads amount.

**Comment by white-balls** [comment]
> Try to increase nettyThreads amount.
OK, thank you for your reply
