### ISSUE TITLE
ERR unknown command 'WAIT

### ISSUE THREAD

**Issue by guozongkang** [redisson/redisson#4645]
tryLock method err  lockKey:metax:invest:user:asset:update:0x67d3d6232b58d7ac3b8ec56d1c363391a224a4fa err:org.redisson.client.RedisException: ERR unknown command 'WAIT'. channel: [id: 0x595e50ea, L:/10.2.9.40:43798 - R:/10.2.0.56:6379] command: (WAIT), params: [1, 1000]

**Comment by guozongkang** [comment]
Aliyun Cloud

**Comment by mrniko** [comment]
This command supported since Redis 3.0. You need to contact your vendor.
