### ISSUE TITLE
when I config timeout value in yaml ,but this value was set in connect_timeout

### ISSUE THREAD

**Issue by ywyg** [redisson/redisson#4647]
Hello !! 
when I config timeout value in yaml ,like :

> spring:
>   redis:
>     host: 127.0.0.1
>     port: 6379
>     timeout: PT40S
>     connect-timeout: PT50S

but when run Redisson.create, i found 
```
 config.useSingleServer()
                .setAddress(prefix + redisProperties.getHost() + ":" + redisProperties.getPort())
                .setConnectTimeout(timeout)
                .setDatabase(redisProperties.getDatabase())
                .setPassword(redisProperties.getPassword());
```
timeout value is  40000
as we all know ,config has attributes like timeout, i don not know why use timeout value set into connect_timeout
version : 'org.redisson:redisson-spring-boot-starter:3.16.3'

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4826
