### ISSUE TITLE
What's the actual mechanism for clearing locks?

### ISSUE THREAD

**Issue by claym** [redisson/redisson#4650]
Question - not a problem :)

We were planning on using redisson for a distributed lock, and when looking into various edge cases, we were wondering how the timed lock release was enforced? The possible case was if it was for a lock to NOT be cleared, requiring manual intervention? 

Or if the lock is not unlocked naturally, and things crash, the next time a lock is checked, does redisson say "oh, the lock's still here but it expired X seconds ago, so we'll release it anyway"?

Just trying to determine if we need that break glass procedure. Thank you!

**Comment by mrniko** [comment]
You can use `forceUnlock()` method in this case
