### ISSUE TITLE
localCachedMap pubsub/updates broken after elasticache cluster maintenance or failover test

### ISSUE THREAD

**Issue by servionsolutions** [redisson/redisson#4653]
**Expected behavior**
Updates to RMap data which include a local cache should propagate changes to all nodes, including local caches, as cluster topology changes occur.  When AWS elasticache maintenance occurs, or failover happens, as topology changes occur or as nodes change from master to slave: RLocalCachedMap pubsub subscriptions should be reestablished, and any updates to localCache values should be captured and continue to be propagated across all redisson instances.  

AWS elasticache cluster uptime is maintained throughout all maintenance operations: redisson should follow topology changes, node type changes (master/slave) and re-establish pubsub connections for RLocalCachedMaps to continue to keep data synchronized with local caches.

**Actual behavior**
RLocalCachedMap local cache values are no longer updated on remote redisson clients when performing cluster maintenance.  Subsequent changes to RLocalCachedMaps can be stale in local cached data for redisson nodes that did not originate the new data, even when data changes are pushed after full cluster topology is recovered.  This causes stale/different datasets for the same keys across multiple nodes using local caches.

**Steps to reproduce or test case**
1. Create elasticache redis cluster with cluster mode enabled, multiAZ enabled
2. Create and connect 2 instances of Redisson, and create common RLocalCachedMap
3. Trigger aws elasticache maintenance/failover test: 
`aws elasticache test-failover --replication-group-id dev-generic-failtest --node-group-id 0001`

**Redis version**
6.2.6, 6.0.5

**Redisson version**
3.17.7

**Redisson configuration**
- Using a TLS/SSL connection via "rediss://" connection string to the AWS elasticache configuration endpoint
- We are also using a nameMapper:
`

        Config config = new Config();
        ClusterServersConfig clusterServers = config.useClusterServers()
                .setRetryInterval(3000)
                .setTimeout(30000)
                .setReadMode(ReadMode.MASTER_SLAVE)
                .setNameMapper(new NameMapper() {
                    @Override
                    public String map(String name) {
                        return KEY_PREFIX_COLON + name;
                    }

                    @Override
                    public String unmap(String name) {
                        return name.replace(KEY_PREFIX_COLON, "");
                    }
                });
`
- Default values for everything else.

I created a simple test application to confirm and reproduce this issue.  I can to publish the entire repo if desired, here is the pertinent code:
`

    MainApp() {
        LOG.info("Starting up test...");

        int count = -1;
        RLocalCachedMap<Object, Object> testMap = redissonConnection.getRedisson()
                .getLocalCachedMap("cachedmap", LocalCachedMapOptions.defaults().syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE));
        testMap.preloadCache();
        String shortId = redissonConnection.getRedisson().getId().substring(0, 7);

        testMap.put(shortId + "_increasing", ++count);
        testMap.put(shortId + "_timestamp", System.currentTimeMillis());
        Map<Object, Object> localCachedMap = testMap.getCachedMap();

        LOG.info("starting main loop in " + this.getClass().getName());
        Thread printingHook = new Thread(testMap::clear);
        Runtime.getRuntime().addShutdownHook(printingHook);

        while (true) {
            try {
                Thread.sleep(5000);
                LOG.info("mynode: {}, current time: {} local cache:", shortId, System.currentTimeMillis());
                localCachedMap.forEach((key, value) -> LOG.info("{}: {}", key, value));

                LOG.info("mynode: {}, current time: {} real cache:", shortId, System.currentTimeMillis());
                testMap.forEach((key, value) -> LOG.info("{}: {}", key, value));

                testMap.put(shortId + "_increasing", ++count);
                testMap.put(shortId + "_timestamp", System.currentTimeMillis());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
`

With this test, I run 2 copies of this same application.  In the logs you can see that that after the test-failover occurs, the redisson instances stop getting new values in their local cache that originated in the other node.

I have enabled TRACE logging for org.redisson and have included the logs generated for both of these instances (same code running in 2 different JVMs).
[app02.log](https://github.com/redisson/redisson/files/9941267/app02.log)
[app01.log](https://github.com/redisson/redisson/files/9941269/app01.log)

Here is a pertinent section of app02.log: 
Notice how the local cache for the data originating at the remote node is old and stale.  You can see the local cache staying correct on both nodes, and local cache stops working during failover test.
![image](https://user-images.githubusercontent.com/10375942/200054253-82436ccc-c8a0-48e4-b430-a289829ee1ec.png)

**Comment by mrniko** [comment]
You need to specify LocalCachedMapOptions.reconnectionStrategy setting

**Comment by servionsolutions** [comment]
Aah - I was not aware of those options, good to know.  I have repeated this test with the CLEAR reconnectionStrategy, unfortunately I don't see any different behavior.  As I read the docs and the code, it looks like it is supposed to clear the near/local cache once connection is re-established, is that correct?

Unfortunately I ran the test and still see the that the local cache exists, is stale and has not been cleared:

![image](https://user-images.githubusercontent.com/10375942/200675529-c08df336-232a-4036-8622-f2720e58161e.png)

I've attached the latest TRACE logs from both instances using the same simple test-bed app, with the addition of:

`.reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.CLEAR));`

[app02_test2.log](https://github.com/redisson/redisson/files/9965298/app02_test2.log)
[app01_test2.log](https://github.com/redisson/redisson/files/9965299/app01_test2.log)

**Comment by servionsolutions** [comment]
@mrniko I have tried further testing, and I believe that there is a problem somewhere with respect either to re-establishing pubsub connections after AWS elasticache failover/maintenance, AND/OR ReconnectionStrategy not working as documented.

I have attempted the CLEAR strategy as mentioned above, but no change.  The ReconnectionStrategy.CLEAR never causes the local cache to actually be cleared, and appears to have no effect at all on the local near cache.  After failover the local cache holds an old object from before failover and is stale on one of the nodes.

My observation is as follows:

- All is fine until failover
- During beginning of failover, I see `org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size.` (same error as https://github.com/redisson/redisson/issues/4658)
- During failover, I can see the subscriptions move from the failing **master** node to the **slave** node
- Once master fully recovers, one subscription is removed tom the slave node (total subscriptions from 2 -> 1)
- No subscriptions are established to the master, leaving total subscriptions down from 2 -> 1, and local caches are unaffected still populated, and stale for one node, using ReconnectionStrategy.CLEAR)

I wrote a script use redis-cli to query all nodes of the cluster, (3 shards, 1 read replica per shard) and to poll the redis command `PUBSUB NUMSUB <channel name>`.  Here is the output in the offending time period:
![image](https://user-images.githubusercontent.com/10375942/201199095-73b3fe09-4e23-40ce-ad95-b1e3294af880.png)
Please note the AWS event log for the cluster, this issue occurs during recovery of the listed nodes:
![image](https://user-images.githubusercontent.com/10375942/201199477-36e0767c-08b5-465e-808b-b0baccd4833f.png)

I have also included the polling of PUBSUB NUMSUB call to each node in the cluster, and both logs of the same test app depicted above, where 1 instance in log: **app02_test03.log** loses subscription and does not have near cache cleared. 

[subs_test03.log](https://github.com/redisson/redisson/files/9984477/subs_test03.log)
[app01_test03.log](https://github.com/redisson/redisson/files/9984478/app01_test03.log)
[app02_test03.log](https://github.com/redisson/redisson/files/9984480/app02_test03.log)


I am happy to share all of this code/scripts, it is very easy and 100% repeatable to reproduce this problem.  Please do let me know if there is any testing or other things I can do to be of help, I believe this to be an important issue.

**Comment by servionsolutions** [comment]
@mrniko I think I found the source of the problem! This seems to be due to some odd behavior coming from AWS Elasticache 'CLUSTER NODES' command when the command is issued to the failed cluster node during failover.

It looks like there is a small window of time during elasticache failover, where the CLUSTER NODES command, **when sent to the failing node** (i.e. failing node == myself) will have a strange behavior.  The reply:
- Has "master" flag
- Does not have a "fail" flag (even though it has that fail flag when querying other nodes in the cluster)
- Has no slots
- Has 0 for all of the `<ping-sent> <pong-recv> <config-epoch>` values
- **No other nodes are listed in the response**

![image](https://user-images.githubusercontent.com/10375942/203162529-555729ee-8413-450d-848d-40ae6f08ad77.png)


Here is the order of events as I can see them from these logs:
1. We trigger failover (aws elasticache cli)
2. A master node is marked as failing, redisson acts properly
3. During a small window of time when the failed master is being removed from the cluster, before it is converted to a slave, if the failing node is queried it can sometimes respond to 'CLUSTER NODES' in this manner (with no other nodes listed)
4. This single-node reply causes redisson to think ALL slots have been removed, and it re-adjusts its the cluster topology by disconnecting, then re-connecting all nodes - at which time, it does not re-establish pubsub connections properly

It appears that this only happens when the CLUSTER NODES command is sent to the failing node, and during a small window of time - after that it is converted to slave and everything works out.  For clients that do not receive this single-line CLUSTER NODES response, the redisson does not remove all slots and re-adjust, and everything actually works properly - pubsub is re-established with the "new slave" (previous master) once its ready and all things work properly.  It looks like every 5 seconds the CLUSTER NODES command is called, and some clients never get this single-node response.  Those clients do not have these failover issues.

Perhaps it is possible to modify redisson to ignore these single-line CLUSTER NODE responses when all  `<ping-sent> <pong-recv> <config-epoch>` values are zero?  I can find no other record during the numerous tests of this where a CLUSTER NODES command has this single-line response, and if it is skipped/missed, cluster topology is still represented fine and all things appear to continue to work properly after failover.

**Comment by mrniko** [comment]
Thank you for the analysis.

Can you ask AWS Team to comment this case?

**Comment by mrniko** [comment]
Please try attached version.

[redisson-3.18.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/10065610/redisson-3.18.1-SNAPSHOT.jar.zip)

**Comment by servionsolutions** [comment]
@mrniko - I'm happy to help!

I was able to test this update with my testbed application as well as our real-world application. Initial testing is that it has fixed this issue within this testbed application, it has survived 3x failover tests without issue!  It would be great if you could get this as a part of your next milestone release :)

My real-world application is still having resiliency issues, seeing exceptions when creating a localCachedMap instance in a redisson node which did not have one previously but does exist in redis.  However I am not certain if it is the same root cause or something else, as I am utilizing other more complex scenarios with redisson (such a RLock, and initializing new localCachedMap after this scenario).

```
...
Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 39000ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.lambda$timeout$7(PublishSubscribeService.java:242) ~[redisson-3.18.1-SNAPSHOT.jar:3.18.1-SNAPSHOT]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:719) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:707) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:794) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:507) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
```

I will attempt to re-create this failure in the testbed application and see if I can duplicate the issue, and share further results.

I have opened up a support ticket with AWS to understand the meaning/expectations around this strange 'CLUSTER NODES' response.  Often they take a few days to reply but I will update you once I hear something.

**Comment by mrniko** [comment]
Thank you for help! Fixed
