### ISSUE TITLE
Subscription failure after DNS resolution exception

### ISSUE THREAD

**Issue by urjitdavenasdaq** [redisson/redisson#4659]
We ran into an issue that might be related to https://github.com/redisson/redisson/issues/4610 and/or https://github.com/redisson/redisson/issues/4074

**System description**
We operate on a publisher consumer model where the publishers will create the local cached maps and populate the maps. The consumer only consumes i.e. never writes to a map. If a map does not exist on redis, the consumer will close out the local cached map to reduce memory consumption and excessive subscriptions. on a new request, we go through the same process again.
This issue only happens on the consumer and not the producer(s)
We use Spring boot and the redisson spring boot starter

**Expected behavior**
- An empty local cached map is created on the consumer

**Actual behavior**
- Subscription timeout exception is thrown
- 
**Steps to reproduce or test case**
- DNS Resolution failure in cluster connection manager
- Slots removed after failure to account for the failed shard
- Slots added back
- Request a local cached map on a consumer, one that has not been requested before, and doesn't exist on Redis

**Redis version**
AWS Elasticache, engine version 6.2.6

**Redisson version**
3.17.4, 3.17.5

**Redisson configuration**
    redisson: |
        clusterServersConfig:
            clientName: <id>
            password: <redis_password>
            nodeAddresses:
              - rediss://<cluster_address>:6379
            pingConnectionInterval: 0
            keepAlive: true
            tcpNoDelay: true
            timeout: 12000
            retryAttempts: 30
            retryInterval: 500
            slaveConnectionMinimumIdleSize: 48
            slaveConnectionPoolSize: 128
            masterConnectionMinimumIdleSize: 48
            masterConnectionPoolSize: 128
        nettyThreads: 64
        codec: !<custom-sub-class-of-org.redisson.codec.Kryo5Codec> {}

Thread dump when requests are getting subscription timeout
[redisson_subscription_failure.log](https://github.com/redisson/redisson/files/9954425/redisson_subscription_failure.log)

**Comment by mrniko** [comment]
Can you try 3.18.0 version? It has a fix for DNS resolver.

**Comment by urjitdavenasdaq** [comment]
thank you for the update. Looks better. Don't see any slots removed when the DNS resolution failed earlier today with 3.18.0. Will keep an eye out as this is difficult to reproduce.

**Comment by mrniko** [comment]
Thank you for your feedback.

You can try to tune SequentialDnsAddressResolverFactory to avoid DNS Resolution failures completely. Try to to find optimal concurrencyLevel param.

**Comment by wangsenyan** [comment]
> r
still having 3.28.0

**Comment by wangsenyan** [comment]
still having 3.18.0

**Comment by mrniko** [comment]
@wangsenyan 

Try SequentialDnsAddressResolverFactory with concurrencyLevel = 2

**Comment by cnudroid** [comment]
We observed the same exception even with 3.19.1 jar
`Caused by: org.redisson.client.RedisTimeoutException: Subscription timeout after 5000ms. Check network and/or increase 'timeout' parameter.
	at org.redisson.pubsub.PubSubConnectionEntry.lambda$subscribe$0(PubSubConnectionEntry.java:181)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)`
