### ISSUE TITLE
How to avoid deadlock in fairlock?

### ISSUE THREAD

**Issue by petercheon** [redisson/redisson#4661]
Hello,
I'm using redission 3.17.7 and I want to using fair lock.
Normally it works perfectly
But, In case of unexpected application termination or deploy, the pending two key(redisson_lock_queue, redisson_lock_timeout)  remains.
So after deployment, even if you try to preempt the lock, you can't preempt it.
Is there any way to release for 2 keys (redisson_lock_queue, redisson_lock_timeout) ?

It happens in the following scenarios:

This is simple code in SpringBoot.
```
@RestController
public class TestController {
...
    @GetMapping("v1/test")
     public void peterTest() {
         String lockKey = "test";
         RLock lock = redissonClient.getFairLock(lockKey)
         lock.tryLock(10000, 2000, TimeUnit.MILLISECONDS);
         Thread.sleep(1000);
         lock.unlock();
   }
}
```
1. Application start and execute the send a request in multiple terminal window below. 
```
curl -X 'GET' 'http://localhost:8080/v1/test'
```
2. Check 2 keys ( redisson_lock_queue, redisson_lock_timeout ). and application shut down.  You can check if the data is still there.
3. waiting a minute.
4. Application start.
5. Send a Request (http://localhost:8080/v1/test) but always false in tryLock()
6. 2 keys (redisson_lock_queue, redisson_lock_timeout) still have values

How to acquire a lock in the following situations?

Thank you.

**Comment by masarykadam** [comment]
Hi, have you found any workaround for this by any chance? We are planning to user Redisson for synchronization using fair-locks but this issue prevents us from doing so, because it can break whole backend.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4153. Please upgrade to 3.31.0 or higher version
