### ISSUE TITLE
TryLock CancellationException issue

### ISSUE THREAD

**Issue by yinyansheng** [redisson/redisson#4662]
hello,

i met a problem, i have about 200 instances try get a distribute lock by use redisson client, 
and one instances will occur CancellationException after running a period time,  and can not recover. 

version: 3.17.6
server: aws elasticahe redis cluster

java.util.concurrent.CancellationException
    at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2468)
    at org.redisson.RedissonLock.tryLock(RedissonLock.java:235)

code as below:
` 

       RLock lock;
        try {
            lock = redissonService.getRedissonClient().getLock(LEASE_COORDINATOR_LOCK_KEY);

            if (!lock.tryLock(3_000, 60_000, TimeUnit.MILLISECONDS)) {
                //log something
                return;
            }

            //do something....

        } catch (InterruptedException e) {
            //log something
        } catch (Exception e) {
            //log something
        } finally {
            //here ignore unlock to ensure execute only once in specific period time
            //lock.unlock();
        }`

**Comment by Barrios596** [comment]
Hello,

I'm having the same issue that @yinyansheng reported after upgrading from Redisson client 3.16.1 to version 3.17.6

```
java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:235)
```

The issue is happening with a sample code similar to the one posted by @yinyansheng, when calling the `tryLock()` method.

**Redisson version**

3.17.6

Seems to be similar to this issue https://github.com/redisson/redisson/issues/4216

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by andreas-ajaib** [comment]
@mrniko which version can I use to fix this problem? Also, is it safe to upgrade from version `3.15.x` or `3.17.x`?

**Comment by mrniko** [comment]
3.18.1

**Comment by wenbochang888** [comment]
@mrniko What is causing this issue? thank you
