### ISSUE TITLE
Regarding definition of nettyThreads

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#4667]
`nettyThreads` is defined as _Threads amount shared between all internal redis clients used by Redisson._

For e.g. my application connects to 3 different Redis clusters (2 sentinel based clusters, 1 multi-master cluster), all of them are initialized with different connections pool sizes and nettyThreads size. Should I keep  `nettyThreads` same across the redis clients here?

**Comment by mrniko** [comment]
You can define shared EventLoopGroup through `eventLoopGroup` setting to use a single netty threads pool.

**Comment by rgampa** [comment]
Thanks for the tip.
