### ISSUE TITLE
How to set cache properties for Hibernate scond level cache?

### ISSUE THREAD

**Issue by AseelAbushhadeh** [redisson/redisson#4670]
I'm working on a Java spring project where I have multiple entities to be cached using `@Cache` annotation, ex:
`@Cache(usage = CacheConcurrencyStrategy.READ_WRITE ,region = "cache1")`

I have set ` spring.jpa.properties.hibernate.cache.region.factory_class` to be RedissonRegionFactory

As I'm using Redis cache as Hibernate second Level cache, I want a way to customize the properties of each cache region in a Java class, by properties I mean the TTL and maxEntriesLocalHeap.

**Comment by OdaybatLFC** [comment]
Hello @AseelAbushhadeh , what I have done in my project is configure each cached entity with my own configuration class. I am also open to hear if there is another way of achieving this.

**Comment by mrniko** [comment]
@OdaybatLFC 

Why can't you use spring.jpa.properties.hibernate.cache... settings?

```java
spring.jpa.properties.hibernate.cache.redisson.entity.expiration.time_to_live=
spring.jpa.properties.hibernate.cache.redisson.entity.expiration.max_idle_time=
spring.jpa.properties.hibernate.cache.redisson.collection.expiration.time_to_live=
spring.jpa.properties.hibernate.cache.redisson.collection.expiration.max_idle_time=
```

**Comment by AseelAbushhadeh** [comment]
thanks for the suggestion, I can use it but this will apply to all caches, I want to customize the properties for each cache individually.

**Comment by AseelAbushhadeh** [comment]
> Hello @AseelAbushhadeh , what I have done in my project is configure each cached entity with my own configuration class. I am also open to hear if there is another way of achieving this.

Hi, I think it is a good solution, can you elaborate more ?

**Comment by mrniko** [comment]
You can specify region name as well.
```
spring.jpa.properties.hibernate.cache.redisson.my_object.expiration.time_to_live=
spring.jpa.properties.hibernate.cache.redisson.my_object.expiration.max_idle_time=
spring.jpa.properties.hibernate.cache.redisson.my_collection.expiration.time_to_live=
spring.jpa.properties.hibernate.cache.redisson.my_collection.expiration.max_idle_time=
```

**Comment by AseelAbushhadeh** [comment]
> You can specify region name as well.
> 
> ```
> spring.jpa.properties.hibernate.cache.redisson.my_object.eviction.max_entries=
> spring.jpa.properties.hibernate.cache.redisson.my_object.expiration.time_to_live=
> spring.jpa.properties.hibernate.cache.redisson.my_object.expiration.max_idle_time=
> 
> spring.jpa.properties.hibernate.cache.redisson.my_collection.expiration.time_to_live=
> spring.jpa.properties.hibernate.cache.redisson.my_collection.expiration.max_idle_time=
> ```

Thanks it works!! 
Hoping I can find a way to do that in a java class.
