### ISSUE TITLE
Expire RRateLimiter

### ISSUE THREAD

**Issue by pat246** [redisson/redisson#4674]
I want to delete RRateLimiter hash from redis, post rate interval is over. e.g. I set rate interval of 10 sec then hash must be removed post 10 sec.
Is there any built in api for this functinality exists?

**Comment by mrniko** [comment]
You need to use `expire()` method

**Comment by pat246** [comment]
Thanks.
Actually we are using redisson 3.12.x version, hence I was unable to call `expire()` method. However as workaround I've tried to expire using `RMap`  with expiry value of "rate interval" as below


`RRateLimiter limiter = redis.getRateLimiter(name);`
`RMap<Object, Object> keyMap = redis.getMap(name);`
`keyMap.expire(10, TimeUnit.SECONDS); // 10 sec is rate interval of limitter`
