### ISSUE TITLE
Support getTotalPermits and idempotent setPermits on semaphores

### ISSUE THREAD

**Issue by kscaldef** [redisson/redisson#4679]
**Is your feature request related to a problem? Please describe.**

We would like to know how many clients are currently holding a permit on the semaphore.  The existing `availablePermits` method can be used to calculate this, but only if you also know how many total permits there are.  Depending on how the size of the semaphore is managed, that information might not be known to all of the clients.

Additionally, for semaphores which can update their size, the non-idempotent nature of `addPermits` introduces complications.  It would be preferable for us to have an idempotent `setPermits` methods which can be called at any time, not just on initialization of the semaphore

**Describe the solution you'd like**

It seems like both of these request could be satisfied by adding an additional value which stores the current limit.  `getTotalPermits` is then just a simple read of this value.  `setPermits` would require a little bit of Lua to update both the total and available values, and notify the channel.  A convenience method like `getClaimedPermits` might also be provided that computed the difference `total - available`.

If this FR seems acceptable, I can work on a PR to implement it.

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
merged
