### ISSUE TITLE
"org.redisson.client.RedisException: ERR Error running script

### ISSUE THREAD

**Issue by adaboinanagarro** [redisson/redisson#4680]
Hi,

I am facing below issue , please advice me on this also i am copying code snippet that i am using

Code
ApplicationRunner throttlingInitializer() {
        return args -> {
            log.info("Rate limits: {} {} {} {}", kv("client", clientDefaultRequestRateLimit),
                    kv("incoming", incomingRequestRateLimit), kv("lbs", lbsRequestRateLimit),
                    kv("unit", rateLimitUnit));

            // Clear rate limiters to ensure rate limit updates take effect

            log.debug("Resetting incoming rate limiter");
            redisson.getRateLimiter(INCOMING_RATE_LIMITER_NAME).delete();

            // TODO: Re-evaluate this. Though it is a simple solution to ensure client rate limits are updated, it
            //  may not be a scalable one.
            clientService.listClients().subscribe(client -> {
                log.debug("Resetting client rate limiter for {}", client.getClientId());
                redisson.getRateLimiter(CLIENT_RATE_LIMITER_NAME_PREFIX + client.getClientId()).delete();
            });

            log.debug("Resetting LBS rate limiter");
            redisson.getRateLimiter(SERVICE_RATE_LIMITER_NAME_PREFIX + SERVICE_ID_LBS).delete();
        };

Issue

{"@timestamp":"2022-10-26T18:10:18.862Z","@version":"1","message":"[35f54d06-1] 500 Server Error for HTTP POST \"/mlp/\"","logger_name":"org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler","thread_name":"redisson-netty-8-9","level":"ERROR","level_value":40000,"stack_trace":"org.redisson.client.RedisException: ERR Error running script (call to f_a23369f7eb133a5016039b245b3fd2482bcafcc3): @user_script:1: user_script:1: attempt to perform arithmetic on a nil value. channel: [id: 0x0e54249e, L:/10.128.82.240:37290 - R:redis-11111.internal.c16265.us-east-1-mz.ec2.cloud.rlrcp.com/10.0.0.39:11111] command: (EVAL), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@640d6897(incomplete)], params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, request_rate_limiter:client:12601245, {request_rate_limiter:client:12601245}:value, {request_rate_limiter:client:12601245}:value:e6c49a0c-2958-46d0-b3c8-8964628ed07a, {request_rate_limiter:client:12601245}:permits, {request_rate_limiter:client:12601245}:permits:e6c49a0c-2958-46d0-b3c8-8964628ed07a, 1, 1666807818861, [-73, 28, 44, 105, -92, -126, 100, -99]]\n\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)\n\tSuppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \nError has been observed at the following site(s):\n\t*_checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ HTTP POST \"/mlp/\" [ExceptionHandlingWebHandler]\nOriginal Stack Trace:\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)\n\t\tat org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)\n\t\tat io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\t\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\t\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\t\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\t\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\t\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\t\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t\tat java.base/java.lang.Thread.run(Unknown Source)\n"}
{"@timestamp":"2022-10-26T18:09:53.853Z","@version":"1","message":"Uncaught exception","logger_name":"com.verizon.msz.gateway.exception.GlobalExceptionHandler","thread_name":"redisson-netty-8-29","level":"ERROR","level_value":40000,"stack_trace":"org.redisson.client.RedisException: ERR Error running script (call to f_a23369f7eb133a5016039b245b3fd2482bcafcc3): @user_script:1: user_script:1: attempt to perform arithmetic on a nil value. channel: [id: 0xf9570d69, L:/10.128.82.240:37374 - R:redis-11111.internal.c16265.us-east-1-mz.ec2.cloud.rlrcp.com/10.0.0.39:11111] command: (EVAL), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@249da0e8(incomplete)], params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, request_rate_limiter:incoming, {request_rate_limiter:incoming}:value, {request_rate_limiter:incoming}:value:e6c49a0c-2958-46d0-b3c8-8964628ed07a, {request_rate_limiter:incoming}:permits, {request_rate_limiter:incoming}:permits:e6c49a0c-2958-46d0-b3c8-8964628ed07a, 1, 1666807793852, [-82, -20, 86, 58, 5, -58, 63, -118]]\n\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)\n\tSuppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \nError has been observed at the following site(s):\n\t*_checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ HTTP POST \"/mlp\" [ExceptionHandlingWebHandler]\nOriginal Stack Trace:\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)\n\t\tat org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)\n\t\tat io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\t\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\t\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\t\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\t\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\t\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\t\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t\tat java.base/java.lang.Thread.run(Unknown Source)\n"}
{"@timestamp":"2022-10-26T18:09:53.853Z","@version":"1","message":"Uncaught exception","logger_name":"com.verizon.msz.gateway.service.LoggingService","thread_name":"redisson-netty-8-29","level":"ERROR","level_value":40000,"stack_trace":"org.redisson.client.RedisException: ERR Error running script (call to f_a23369f7eb133a5016039b245b3fd2482bcafcc3): @user_script:1: user_script:1: attempt to perform arithmetic on a nil value. channel: [id: 0xf9570d69, L:/10.128.82.240:37374 - R:redis-11111.internal.c16265.us-east-1-mz.ec2.cloud.rlrcp.com/10.0.0.39:11111] command: (EVAL), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@249da0e8(incomplete)], params: [local rate = redis.call('hget', KEYS[1], 'rate');local interval = redis.call('hget', KEYS[1], 'inter..., 5, request_rate_limiter:incoming, {request_rate_limiter:incoming}:value, {request_rate_limiter:incoming}:value:e6c49a0c-2958-46d0-b3c8-8964628ed07a, {request_rate_limiter:incoming}:permits, {request_rate_limiter:incoming}:permits:e6c49a0c-2958-46d0-b3c8-8964628ed07a, 1, 1666807793852, [-82, -20, 86, 58, 5, -58, 63, -118]]\n\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)\n\tSuppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \nError has been observed at the following site(s):\n\t*_checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]\n\t*_checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ HTTP POST \"/mlp\" [ExceptionHandlingWebHandler]\nOriginal Stack Trace:\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)\n\t\tat org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)\n\t\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)\n\t\tat io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)\n\t\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\t\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\t\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\t\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\t\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\t\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\t\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\t\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\t\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\t\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t\tat java.base/java.lang.Thread.run(Unknown Source)\n","error_message":"Uncaught exception","error_type":"SYSTEM_FAILURE","event":"SYSTEM_ERROR"}

**Comment by mrniko** [comment]
Unable to reproduce

**Comment by yan11xiang** [comment]
like this issue : https://github.com/redisson/redisson/issues/229

**Comment by mrniko** [comment]
@yan11xiang 

Did you check it https://github.com/redisson/redisson/issues/229#issuecomment-215351803 ?
