### ISSUE TITLE
How to set hibernate cache properties?

### ISSUE THREAD

**Issue by AseelAbushhadeh** [redisson/redisson#4682]
I'm using Hibernate second level cache in a Java spring project and RedissonRegionFactory as a cache provider, in order to set cache properties like ttl I added this line to `application.properties` file:

`spring.jpa.properties.hibernate.cache.redisson.entity.expiration.time_to_live=10000`

However I have different cache regions and I want to set for each one a special ttl, instead of setting a general one for all caches. How can I customize cache properties individually, and is it possible to do this in java class instead of the `application.properties` file? 
Any help is appreciated!

**Comment by mrniko** [comment]
Use setting below for entity `my_object`

`hibernate.cache.redisson.my_object.eviction.max_entries`
