### ISSUE TITLE
support springboot3

### ISSUE THREAD

**Issue by wang-xiaowu** [redisson/redisson#4683]
**Is your feature request related to a problem? Please describe.**

https://github.com/redisson/redisson/issues/4675

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lWoHvYe** [comment]
I think there may be a redisson-spring-data-30 in the feature.  the #4675 is because that spring-data-redis have moved some class to another package.

**Comment by wang-xiaowu** [comment]
> I think there may be a redisson-spring-data-30 in the feature. for that `Feature - compatibility with Spring Boot 3` is for autoconfiguration. the #4675 is because that spring-data-redis have moved some class to another package [commit](https://github.com/spring-projects/spring-data-redis/commit/b45d358abfc7ebcc15a3fdd331f8a19fe68a0dba)

yes
