### ISSUE TITLE
Distributed lock consistency via fencing tokens

### ISSUE THREAD

**Issue by rocketraman** [redisson/redisson#4684]
**Is your feature request related to a problem? Please describe.**

Distributed locks do not appear to be consistent (at least per the documentation) because they do not implement fencing tokens. See documentation on the Redis site here: https://redis.io/docs/manual/patterns/distributed-locks/#disclaimer-about-consistency.

**Describe the solution you'd like**

Implement (optional) fencing tokens for consistent distributed locks as recommended by Redis. For users that are using locking for correctness, this is important.

**Describe alternatives you've considered**

Custom solutions, or HazelCast FencedLock.

**Comment by mrniko** [comment]
The documentation you pointing at is related to RedLock algorithm. Which is deprecated in Redisson. Instead lock acquisition is now synchronized with slaves during lock method invocation.

**Comment by mrniko** [comment]
Thank you for clarifying.

With FencedLock you need to write LUA scripts and check fence id each time along with command execution. Is it acceptable for you?

**Comment by rocketraman** [comment]
> With FencedLock you need to write LUA scripts and check fence id each time along with command execution. Is it acceptable for you?

I would expect to check the fence id within my lock consumer, and pass it / validate it on every write to any persistent storage. I don't know what you mean by writing LUA scripts though.

**Comment by mrniko** [comment]
Done

**Comment by rocketraman** [comment]
Thank you! I'll experiment with this soon.
