### ISSUE TITLE
Listener for RLocalCachedMap invalidate message received

### ISSUE THREAD

**Issue by workmaster2n** [redisson/redisson#4686]
We have 2 nodes of our software running, connected to one redis server.  These nodes share a Map that we implement as an RLocalCachedMap.  Occasionally, one of the 2 nodes will modify an entry in that map.  On 2 occasions, we have seen the other node fail to get the update, and on hundreds of other instances we have seen the second node receive the update.  Our best guess at the moment is that the second node misses an occasional pub/sub message.

To try and diagnose this issue, we'd like to be able to have a listener running on both nodes that will log a message when an invalidate message is received on the map (in other words, when the map in Redis is modified).  Is it possible to implement such a listener?  We attempted to implement some of the listeners defined on other RMap types, but nothing seemed to do the trick.

We define our Map as follows: 

```
@Bean("customRoutes")
    override fun getCustomMap(): MutableMap<String, CustomRoute> {
        return redissonClient.getLocalCachedMap(CUSTOM_MAP, LocalCachedMapOptions.defaults())
    }

**Comment by mrniko** [comment]
You need to create RTopic object with org.redisson.cache.LocalCacheListener#getInvalidationTopicName() as name.

RTopic invalidationTopic = RedissonTopic.createRaw(LocalCachedMessageCodec.INSTANCE, commandExecutor, getInvalidationTopicName());

**Comment by mrniko** [comment]
Please keep me updated on this issue.

**Comment by ofir-popowski** [comment]
@mrniko I have a similar requirements as OP. I would like to execute some logic after an `RLocalCachedMap` local instance has been updated. Say I have 5 instances using the same map, I'd like each of them to perform some calculation based on the key, and whether it was updated or invalidated

I am unsure how to use the example code snippet you have provided.
1. `getInvalidationTopicName()` is not available to call on instances of `RLocalCachedMap`
2. how do I obtain an instance of `commandExecutor`?
3. is it possible to deserialize the message and get the key?

**Comment by mrniko** [comment]
Done
