### ISSUE TITLE
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List

### ISSUE THREAD

**Issue by ybbhswcy** [redisson/redisson#4688]
**Expected behavior**
   public List<Entry<byte[], byte[]>> hRandFieldWithValues(byte[] key, long count) {
        Assert.notNull(key, "Key must not be null!");
        return (List)this.read(key, ByteArrayCodec.INSTANCE, RedisCommands.HRANDFIELD, key, count);
    }

**Actual behavior**
return LinkedHashmap;

**Redis version**
7.0.5

**Redisson version**
3.18.0

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed. Thanks for report
