### ISSUE TITLE
SSL endpoint identification not working with AWS elasticache Redis when using CNAME

### ISSUE THREAD

**Issue by shivam2146** [redisson/redisson#4691]
While using Redisson in one of my Spring boot projects with AWS Elasticache for Redis, when using the CNAME of the Redis, the SSL endpoint identification does not work. whereas if I use the AWS Elasticache endpoint itself it works. 
When using CNAME with SSL enabled with other libraries like Jedis, it is working fine. 
Is there any config required? or some change needs to be made for this to work?

**Comment by mrniko** [comment]
It seems to be a known netty issue https://github.com/netty/netty/issues/11364

**Comment by shivam2146** [comment]
okay. Is there any workaround for that as of now? Coz it's forcing us to disable SSL endpoint identification or use the endpoint directly instead of CNAME.
Both are kind of bad as disabling SSL endpoint identification in prod is not recommended and not using CNAME has its own disadvantages.

**Comment by mrniko** [comment]
I asked the same question in netty issue
