### ISSUE TITLE
The order of CommandData and ByteBuf does not match

### ISSUE THREAD

**Issue by bgrooot** [redisson/redisson#4693]
**Expected behavior**
- if an exception (RedissTImeoutException, RedisResponseTimeoutException) occurs, not misread data from the buffer.
- When an error occurs, in the [syntax below](https://github.com/redisson/redisson/blob/4d3ae58f0e81924a79f943d764daaff549884308/redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java#L107), it is necessary to distinguish whether data is in the buffer or not.
```
// org.redisson.client.handler.CommandDecoder.java#L107
if (data.isExecuted()) {
    in.readerIndex(endIndex);
    sendNext(ctx.channel());
    return;
}
```

**Actual behavior**
- Even if there is no data, `in.readerIndex(endIndex)` is executed and the index is skipped.
- So, in the case of a GET command, the response of another command (ex. PSETEX) is read and `ClassCastException` occurs.

**Steps to reproduce or test case**
- Calls to read the 2nd level entity repeatedly. (GET Command)
- This is more likely to happen if you shorten the `timeout` or `retryInterval` or entity TTL setting.

**Redis version**
- 7.0.5

**Redisson version**
- 3.18.0

**Redisson configuration**

**Comment by mrniko** [comment]
> the response of another command (ex. PSETEX) is read and ClassCastException occurs

Can you clarify how it can be if the previous response was skipped by readerIndex() method invocation?

**Comment by mrniko** [comment]
> Even if there is no data

Then endIndex matches with current readerIndex.

**Comment by bgrooot** [comment]
> Can you clarify how it can be if the previous response was skipped by readerIndex() method invocation?

The command peeked from `Queue<QueueCommandHolder>` and the data in the buffer do not match. In my case, the `RedisCommand` of `QueueCommandHolder` was 'GET' command, but the `result` parameter of the `completeResponse` method read from the buffer was 'OK'. (Originally, serialized object data should come.)

**Comment by mrniko** [comment]
> > Can you clarify how it can be if the previous response was skipped by readerIndex() method invocation?
> 
> The command peeked from `Queue<QueueCommandHolder>` and the data in the buffer do not match. In my case, the `RedisCommand` of `QueueCommandHolder` was 'GET' command, but the `result` parameter of the `completeResponse` method read from the buffer was 'OK'. (Originally, serialized object data should come.)

How it could be if result of previous command was skipped and can't be read?

**Comment by bgrooot** [comment]
@mrniko 
Please let me know if you need additional information. (anytime, whatever)

**Comment by mrniko** [comment]
Sorry, unable to reproduce it.

The error appears only if I comment out "in.readerIndex(endIndex);" line after "if (data.isExecuted()) {" line.

**Comment by bgrooot** [comment]
This is the code I tested. 
- CODE: https://github.com/bgrooot/redisson-bucket-test/blob/main/RedissonTest.kt
- CONFIG: https://github.com/bgrooot/redisson-bucket-test/blob/main/redisson.yaml

Timeout values are set very short to occur an exception. Alternatively, the easiest way to trigger a timeout is to run in debugger mode and set a breakpoint.

**Comment by bgrooot** [comment]
@mrniko 
Could it have been reproduced?

**Comment by mrniko** [comment]
I managed to reproduce. Thank you!

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by bgrooot** [comment]
@mrniko 
I have a one question.
What is the role of this code?

https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java#L104

**Comment by mrniko** [comment]
@bgrooot 

It's a error simulation to make a new attempt for data decoding
