### ISSUE TITLE
Setting cache region properties programmatically

### ISSUE THREAD

**Issue by AseelAbushhadeh** [redisson/redisson#4697]
So I have been trying to set caches properties like max_idle_time, the only official way to set them is by adding these properties 
`spring.jpa.properties.hibernate.cache.redisson.entity.localcache.max_idle_time= 300000`
However I needed to set them programmatically in a java class but I can't find a direct way.
The work around I did was to override createRedissonClient which will be called before buildDomainDataRegion :
```
  @Override
    protected RedissonClient createRedissonClient(Map properties) {
         //scan and put properties
        properties.put("hibernate.cache.redisson.entity.expiration.time_to_live","7000");
        return this.redissonClient;
    }
```

**Comment by mrniko** [comment]
This is the best way
