### ISSUE TITLE
In an istio environment, if one of the redis slave nodes down, the system cpu will surge

### ISSUE THREAD

**Issue by wenjin87** [redisson/redisson#4699]
**Expected behavior**
The cpu and bandwidth should be normal

**Actual behavior**

In istio environment,when a salve node down in Sentinel mode, redisson seems to desperately try to connect to the down node, causing cpu and network bandwidth anomalies.

**Steps to reproduce or test case**
deployment project with istio，and kill redis one of salve node.

**Redis version**
7.0
**Redisson version**
3.17.1 and 1.18.0
**Redisson configuration**
default

**Comment by mrniko** [comment]
Please share some profiler results

**Comment by wenjin87** [comment]
@mrniko 
![image](https://user-images.githubusercontent.com/119024510/203937326-5807bef8-abc6-47bf-a68e-ba58787519ca.png)

bandwidth : 1M/s

**Comment by mrniko** [comment]
can you share the logs and config?

**Comment by wenjin87** [comment]
hi @mrniko the redis config like this. and for RedissonClient i create it use java code.
```
spring:
  redis:
    database: 0
    timeout: 10000
    sentinel:
      master: mymaster
      nodes:
        - "10.16.11.xxx:26379"
        - "10.16.11.xxx:26379"
        - "10.16.11.xxx:26379"
```

```
   @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {
        Config config = new Config();
        String redis = "redis://";

        if(StringUtils.isNotEmpty(redisConfigProperties.getSentinel().getTransportMode())) {
            config.setTransportMode(TransportMode.valueOf(redisConfigProperties.getSentinel().getTransportMode()));
        }

        for (String node : redisConfigProperties.getSentinel().getNodes()) {
            config.useSentinelServers().addSentinelAddress(node.contains(redis) ? node : redis + node);
        }

        if (StringUtils.isNotEmpty(redisConfigProperties.getPassword())) {
            config.useSentinelServers().setPassword(redisConfigProperties.getPassword());
        }
        config.useSentinelServers().setDatabase(redisConfigProperties.getDatabase());
        config.useSentinelServers().setMasterName(redisConfigProperties.getSentinel().getMaster());
        config.useSentinelServers().setTimeout(redisConfigProperties.getTimeout());
        return Redisson.create(config);
    }
```

a large number of logs appeared when i set the log level with debug after some redis slave node kill by test

**Comment by mrniko** [comment]
can you share some test application which I can run?

**Comment by wenjin87** [comment]
@mrniko there is no business code,I just brought redisson into my project and then kill one of slave redis node.it's happend.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4902
