### ISSUE TITLE
redisson.tryLock(long waitTime, TimeUnit unit) throw java.util.concurrent.CancellationException: null

### ISSUE THREAD

**Issue by xyq8921** [redisson/redisson#4700]
redisson version 3.17.4
sometime throw CancellationException：
![image](https://user-images.githubusercontent.com/35992486/204124937-79c1b022-5db1-4695-82d5-607a70814117.png)

what should I do？ Thanks in advance

**Comment by mrniko** [comment]
Will be fixed in https://github.com/redisson/redisson/issues/4662

**Comment by zjs-cool** [comment]
你好，这种问题我最近也遇到了，请问一般是什么原因导致的呢
