### ISSUE TITLE
When RMapCache is used, a large number of MapCacheEvictionTask objects are created 

### ISSUE THREAD

**Issue by GodloveJoseph** [redisson/redisson#4707]
After RMapCache is used, a large number of MapCacheEvictionTask objects are created when the expiration date is expired, and the memory is gradually increased. What is the problem?
The version is:
`<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.17.7</version>
 </dependency>`

config:
` String cluster = "10.19.220.36:7019,10.19.220.36:37019,10.19.220.40:7019,10.19.220.40:37019,10.19.220.47:7019,10.19.220.47:37019";
      String[] nodes = cluster.split(",");
        for (int i = 0; i < nodes.length; i++) {
            nodes[i] = "redis://" + nodes[i];
        }
		
        Config config = new Config();
        config.useClusterServers()
                .setScanInterval(10000)
                .setPassword(properties.getPassword())
                .addNodeAddress(nodes);
        RedissonClient redisson = Redisson.create(config);`

my code:
`@Autowired
  private RedissonClient redissonClient;

  @Override
    public boolean isExist(String key) {
        RMapCache map = redissonClient.getMapCache(key);
        return map.get(key) != null ? true : false;
    }

    @Override
    public void putEntry(String key, String value) {
        RMapCache map = redissonClient.getMapCache(key);
        map.put(key, value, 300, TimeUnit.SECONDS);
    }`
hprof analysis:
![截取图片_20221130172428](https://user-images.githubusercontent.com/38186395/204759635-88c987b8-dc87-4753-bc85-f988fcd5d57e.png)

![20221130172449](https://user-images.githubusercontent.com/38186395/204759361-a2eb37ca-c65e-430e-b893-662002eca51f.png)

![20221130172503](https://user-images.githubusercontent.com/38186395/204759281-2315210b-742d-461c-b22b-c6fb58f3950e.png)

![20221130172553](https://user-images.githubusercontent.com/38186395/204758857-f360c09d-02fa-48e7-acc0-cff2ccdcd59f.png)

**Comment by mrniko** [comment]
You need to call RMapCache.destroy() method once you finished it's usage or use a single instance.

**Comment by GodloveJoseph** [comment]
你好，来信收到！

**Comment by GodloveJoseph** [comment]
> You need to call RMapCache.destroy() method once you finished it's usage or use a single instance.

But I don't know when it finished 。Maybe I should use redis to store it.

**Comment by GodloveJoseph** [comment]
```
RMapCache map = redissonClient.getMapCache(key);
        map.put(key, value, expireTime, TimeUnit.SECONDS);
        map.destroy();
```
Will the data be stored in redis if used this way? Then the expiration redis will be automatically eliminated
@mrniko
