### ISSUE TITLE
"Redis Cluster + Custom NameMapper + RedissonPermitExpirableSemaphore " combination is caused "CROSSSLOT Keys in request don't hash to the same slot."

### ISSUE THREAD

**Issue by kjho80** [redisson/redisson#4708]
Hi.
I used RedissonPermitExpirableSemaphore with "Redis Cluster + Custom NameMapper".

But below error is occured.
"CROSSSLOT Keys in request don't hash to the same slot."

So I reviewed "RedissonPermitExpirableSemaphore.java" source, I found something that thought to be a problem.

When using nameMapper, all redis operation key is applied nameMapper, but timeoutName is not applied.

```
    public RedissonPermitExpirableSemaphore(CommandAsyncExecutor commandExecutor, String name) {
        super(commandExecutor, name);
        this.timeoutName = suffixName(name, "timeout");
        this.commandExecutor = commandExecutor;
        this.semaphorePubSub = commandExecutor.getConnectionManager().getSubscribeService().getSemaphorePubSub();
    }
```

So All other operation is going to "A" cluster slot, but timeout operation is going to "B" cluster slot.
Finally "CROSSSLOT Keys in request don't hash to the same slot." is occured. 

I think below line need to change.
```
AS-IS : 
        this.timeoutName = suffixName(name, "timeout");
TO-BE:
        this.timeoutName = suffixName(getRawName(), "timeout");
```

**Comment by mrniko** [comment]
Fixed! Thanks for report
