### ISSUE TITLE
Topic Listener does not trigger

### ISSUE THREAD

**Issue by Ikki-Dai** [redisson/redisson#4715]
topic listener method doesn't triggered, i'm sure the jvm instance received the message which published from another one.
because while i use diffenet codec from publish end, the receiver can throw exception as expected
but while use the matched codec, the listener method with simple print out doesn't not trigger

**Expected behavior**

topic listener method should be triggered

**Actual behavior**

method not tirggered

**Steps to reproduce or test case**
redission.getTopic('topic')
topic.addListener((clazz, ()->{System.out.println()} ))

**Redis version**
3.0.7 Cluster
**Redisson version**
3.17.7 ~ 3.18.1
**Redisson configuration**

spring.redis.cluster.nodes=xxxx

**Comment by Ikki-Dai** [comment]
I've enable `org.redission.client.handler.CommandPubSubDecoder` log to `trace`, the data have been print.out

**Comment by Ikki-Dai** [comment]
it is a serializer issue, while try jackson codec, can print object correctly

**Comment by mrniko** [comment]
Did you try kryo5Codec ? It's the default one now.

**Comment by Ikki-Dai** [comment]
kryo5Codec doesn't work

**Comment by mrniko** [comment]
Please share the test code

**Comment by Ikki-Dai** [comment]
- publish
```java
@SpringBootTest(webEnviroment=SpringBootTest.WebEnvironment.NONE)
public class CacheEventPublishTest{

@Autowired
RedissionClient redissionClient;

 @Test
 public void publishTest() throws InterruptedException {
  RTopic topic = redissonClient.getTopic(TOPIC);
  Event event = new Event();
  event.setName("name");
  event.setParams(new Object[]{1000, "paramsA"})
  long l = topic.publish(event)

 }

}
```

- listener
```java
@Component
public class EventListener {
    private final RedissionClient redissonClient;

    @PostConstruct
    public void listener() {
          topic = redissonClient.getTopic(TOPIC);
          int listenerNum = topic.addListener(Event.class, (msg, event) -> {
               System.out.println(msg+ ":"+ event);
          });
    }

}

```

**Comment by mrniko** [comment]
Seems like `public class EventListener` isn't called at all. Please check your code.
