### ISSUE TITLE
RedissonPromise not found post upgrade to 3.18.1

### ISSUE THREAD

**Issue by kaushalarora04** [redisson/redisson#4717]
I am attempting to upgrade redisson version from 3.15.4 to 3.18.1.
I was using RedissonPromise from the package org.redisson.misc.RedissonPromise, with version 3.15.4, however, this class seems to have been removed in 3.18.1.
I cannot find any details about this in the change logs, or release notes.

Please share the alternative for RedissonPromise when upgrading version, or how, to work without RedissonPromise.

I am using RedissonPromise as below when running unit test cases, to return a mock instance of RFuture -

Mockito.when(rbucket.compareAndSetAsync("", "world")).thenReturn(RedissonPromise.newSucceededFuture(Boolean.TRUE));

**Comment by mrniko** [comment]
RedissonPromise was an internal class like others from misc package. Dropped after refactoring. 
Use `new CompletableFutureWrapper(true)` instead.
