### ISSUE TITLE
Redisson 3.17.5 issue with Open JDK version “17.0.5” 2022-10-18 LTS

### ISSUE THREAD

**Issue by DMIC123** [redisson/redisson#4718]
Unable to start application getting issue as NoClassDefFoundError 

org.jboss.marshalling.river.ClassDescriptors.
……
org.redisson.codec.MarshallingCodec(MarshallingCodec.java:146

 This is with Open JDK 17.

**Redis version** 3.17.15 

**Redisson configuration**
Config conf= newConfig;
conf.useSingleServer().
        .setAdress(redis connection url)
        .setPassword(pwd);

Is there any compatibility issue of Redisson with Open JDK 17? The same application runs perfectly fine with Open JDk11. We just upgraded image to JDK 17.

**Comment by DMIC123** [comment]
No i did not. What would be the syntax to use Kryo5 or Serialization codec? 

Currently i am using default which is Marshalling Codec.

With default codec/ configuration- seeing these two type of errors: 

1. java.lang.NoClassDefFoundError: Could not initialize class org.jboss.marshalling.river.ClassDescriptors
at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor( RiverMarshallet.java:1268)
……..

2. java.lang.ExceptionInInitializerError
org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor( RiverMarshallet.java:1268)
…….
Caused by: java.lang.reflecf.InaccessibleObjectException:Unable to make protected java.util.AbstractMap() accessible:module java.base does not “opensjava.util” to unnamed module @1c655221
……..

**Comment by mrniko** [comment]
you need to specify Kryo5 codec in settings like:

```java
conf.setCodec(new Kryo5Codec());
```
