### ISSUE TITLE
members方法超时

### ISSUE THREAD

**Issue by dantqf** [redisson/redisson#4721]
项目加入redisson后，原先的redisTemplate.opsForSet().members方法报超时错误，数据量一百万左右，设置pingConnectionInterval以及更新版本均无法解决，有大神知道原因吗

**Comment by mrniko** [comment]
increase redisson timeout setting

**Comment by dantqf** [comment]
非常感谢：更新到最新版本，并延长超时时间之后解决问题，但是为何耗时增长了5倍左右


澹台穹风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redisson/redisson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redisson/redisson] members方法超时 (Issue #4721)





 
increase redisson timeout setting
