### ISSUE TITLE
Distributed Locks use Thread.id

### ISSUE THREAD

**Issue by MykolaPogorilyi** [redisson/redisson#4724]
Hi. I'm using Redisson 3.17.7 Java client (with Java 17). 
I have N pods of the same service in Kuber and I need to synchronize them on some objects UUID. 
I came into situation when few pods are trying to acquire the same lock and they have same thread id (Thread.currentThread().getId()). Such thing happened as each pod is different JVM and thread id is consecutive number (++threadSeqNumber). 
As a result few pods/Services/JVMs acquired the same lock. 

Is there any workaround or fix may be advised? 

I think this must be handled on Redis server side (not lib). When different Redis clients are trying to acquire the same lock with the equal thread id, client ID, must be taken into account, mustn't it?

**Comment by mrniko** [comment]
If thread id and client ID are equal the lock owner is considered the same.

> few pods are trying to acquire the same lock

You can try to use Redisson client per pod. Each Redisson client has unique client ID.
