### ISSUE TITLE
Unable to connect to Redis sentinel servers

### ISSUE THREAD

**Issue by HQCND** [redisson/redisson#4726]
I have no problem connecting using redis-cli and connecting using other clients，but using java client is failed

**Redisson version**
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson</artifactId>
    <version>3.13.4</version>
</dependency>

**Redisson configuration**
<img width="512" alt="image" src="https://user-images.githubusercontent.com/76543659/206404779-e53915a4-ba3d-472a-b560-4db55831cfa1.png">

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/76543659/206403351-b5278fd8-d1a2-49e7-9bf3-d2b3b0dd138b.png">

**Comment by HQCND** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/76543659/206403510-baeeef07-8bb4-4c66-b33f-3f34977026cc.png">

**Comment by HQCND** [comment]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/76543659/206403602-29709d0e-fd00-4219-a7e9-9aec1b8fba55.png">

**Comment by mrniko** [comment]
Try to reduce connection pool size.
