### ISSUE TITLE
Track if a replica is down?

### ISSUE THREAD

**Issue by tafrick** [redisson/redisson#4727]
I'm using an Azure redis instance with a master-slave cluster configuration. Is there a way to keep track of the replicas in a cluster and raise an alert if one of the replicas has gone down for a period of time such as half an hour? The CLUSTER NODES command seemed like it would be able to keep track of that information, but looking at this [page](https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping) I don't see an API for it in redisson. I thought one approach would be to use the following, but it doesn't seem right and reading up on the CLUSTER INFO command it seems to mostly provide information about masters. Are there any Azure metrics or redisson APIs that can help determine if the replica is healthy or down?
![Screenshot 2022-12-08 at 11 14 48 AM](https://user-images.githubusercontent.com/40805049/206546694-528cdd2d-e264-4816-8be7-156712b0f708.png)

**Comment by mrniko** [comment]
getSlaves() and getMasters() return only available servers. So you can track changes of these collections.
