### ISSUE TITLE
Redisson JCache (JSR-107) Get operation spending sporadically 3s-5s in Unsafe:park

### ISSUE THREAD

**Issue by eiselems** [redisson/redisson#4734]
Hi,

we are in the middle of migration from switching from EHCache as our JCache Provider towards Redis (using Redisson-Spring Data).
### Dependencies:
```
        dependency('org.redisson:redisson-spring-boot-starter:3.17.6')
        dependency('org.redisson:redisson-spring-data-25:3.17.6') // for Spring Data Redis v.2.5.x
        dependency('org.redisson:redisson-hibernate-53:3.17.6') // for Hibernate 5.3+
```

Trying to update to 3.17.7 as we speak.

## Expected: 
- Get operations from within the Application take at most a few milliseconds

## Observed:
- Slowlog contains only a few requests that took up to 11ms (nothing like the 3s-5s)
- AppDynamics confirmed that the requests using Redisson are rather fast, by observing "org.redisson.command.RedisExecutor.sendCommand", this kind of matches what we see on the Redis side - see the previous point
![screenshot](https://user-images.githubusercontent.com/5188694/207088268-d7476f82-77c9-4e93-816b-d20044790c9f.png)

## Code:

```
        private Cache cache;
        ....
        cache = cacheManager.getCache("cacheName");
        ....
        
        List<SomeEntity> entity = cache.get(cacheId, ArrayList.class); // this is line 187 in the screenshot
```

We are using RedisCacheConfiguration from `org.springframework.boot.autoconfigure.cache` also the `RedissonAutoConfiguration`.

Setting up the Cache using a BeanPostProcessor:

```
@Configuration
@ComponentScan(basePackages = { "somePackage" }, excludeFilters = {
        @ComponentScan.Filter(type = FilterType.CUSTOM, classes = TypeExcludeFilter.class) })
public class CacheConfigurer implements BeanPostProcessor {

    @Autowired
    RedissonClient redissonClient;

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
        if (bean instanceof JCacheCacheManager) {
            initCaches(((JCacheCacheManager) bean).getCacheManager());
        }
        return bean;
    }

    private void initCaches(CacheManager cacheManager) {
        javax.cache.configuration.Configuration<Object, Object> configuration = RedissonConfiguration.fromInstance(redissonClient);
        createCacheIfNotExists("cacheName", configuration, cacheManager);
    }

    private void createCacheIfNotExists(String cacheName, javax.cache.configuration.Configuration<Object, Object> configuration,
            CacheManager cacheManager) {
        if (cacheManager.getCache(cacheName) == null) {
            cacheManager.createCache(cacheName, configuration);
        }
    }

}
```

## Asking for help

Hope somebody can shed some insight what might be causing this - currently I am a bit out of ideas.
Looking at the trace it could be that Redisson takes some time to aquire a Lock or for some reason it is really slow to pack the task on an executor.

Any idea how I can better verify what is causing this?

**Comment by mrniko** [comment]
Hi,

According to the trace I don't see which lock is used and where.

**Comment by mrniko** [comment]
JCache doesn't use locks if it runs in application and not a testing bundle
