### ISSUE TITLE
StreamGroup does not support entries-read and lag

### ISSUE THREAD

**Issue by alexcatit** [redisson/redisson#4735]
Starting with Redis version 7.0.0, command XINFO GROUPS returns the entries-read and lag fields.

https://redis.io/commands/xinfo-groups/

`RStream.listGroups()` returns list of common info about groups belonging to this stream, a list of `StreamGroup`.
But `StreamGroup` lacks the newly added information.

These new data can be added to StreamGroup?

**Comment by mrniko** [comment]
Done! Thanks for pointing that out.
