### ISSUE TITLE
RedissonSet.readUnionAsync use writeAsync instead of readAsync

### ISSUE THREAD

**Issue by victorGS18** [redisson/redisson#4742]
**Expected behavior**
The command sunion read from slaves

**Actual behavior**
The command sunion alwayrs read from master

**Reason**
The method readUnionAsync of class RedissonSet use a writeAsync instead of readAsync

**Comment by mrniko** [comment]
We don't need to use writeAsync in readUnionAsync since it doesn't modify the data

**Comment by victorGS18** [comment]
@mrniko, Has the change been made in the end? in which version will it be available?

**Comment by victorGS18** [comment]
@mrniko, I have not seen that the change has been made, why has the issue been closed?

**Comment by mrniko** [comment]
@victorGS18 

https://github.com/redisson/redisson/issues/4742#issuecomment-1400247712

**Comment by victorGS18** [comment]
@mrniko 
But the problem is not that I want to use writeAsync, it's that writeAsync is being used right now.
![Selección_386](https://user-images.githubusercontent.com/61154590/222112324-62143a87-586f-47be-935e-26204e98fd99.png)

**Comment by mrniko** [comment]
Fixed! Thanks for report
