### ISSUE TITLE
when using NameMapper ,bloomfilter's bitset can't be expire and delete

### ISSUE THREAD

**Issue by javed119** [redisson/redisson#4746]
**Expected behavior**
after the name mapper set，bloomfilter's bitset can be delete and expire normally
**Actual behavior**
can not delete and expire the bloomfilter bitset, then redis OOM
**Steps to reproduce or test case**
1. setNameMapper 
![image](https://user-images.githubusercontent.com/35559286/208074456-9d1720af-81f7-45bd-99f4-f4fef59536e1.png)
2. set BloomFilter
![image](https://user-images.githubusercontent.com/35559286/208072763-51a2126a-c8a0-4dfb-a54a-f25c13f4186e.png)
3. result
![image](https://user-images.githubusercontent.com/35559286/208074415-dc351f82-147b-4391-8999-a5048ef0a0d9.png)

**Redis version**
5.0
**Redisson version**
3.17.4
**Redisson configuration**

**Comment by mrniko** [comment]
merged
