### ISSUE TITLE
Sessions getting mixed up between different users

### ISSUE THREAD

**Issue by cyril-d** [redisson/redisson#4747]
We are using redisson 3.15.0 with tomcat 9.0.56. The redis version is 9.0.56 (aws elasticcache). Our backend app is a spring MVC app using JSF running on aws eks.

In the last month, we had 3 reported incidents across 3 weeks where a user logs into their account and sees somebody else's data in their session. Both users whose data (and sessions) is getting mixed up access the site within 30 secs of each other in all 3 cases. And they end up on the same eks pod. Any hints or clues will be appreciated. We cant reproduce this at all in our test environment

**Comment by cyril-d** [comment]
I explored the possibility of the same session id getting generated twice. Looking at tomcat's implementation (16*2 hex characters session id length) and our site volume (6000 hits a day), the chance of a session id clash is 10^-12. So it seems extremely unlikely. 

Tomcat seems to recycle request objects and clears them (including their session references) before reusing. So I was suspecting that maybe it served the same session to a different user due to a bug. But from their code and our logs, I cant really find a code path which indicates that

**Comment by mrniko** [comment]
is it possible that cookie was sent for a different user?

**Comment by cyril-d** [comment]
Not at all. These users were in different cities.

**Comment by mrniko** [comment]
Unable to reproduce it.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4381. Update to Redisson 3.19.2+

**Comment by unasd** [comment]
> Fixed in #4381. Update to Redisson 3.19.2+

The fix you mentioned doesn't include anything about session mix. Are there release notes for session mix fixes?

**Comment by mrniko** [comment]
it's related to possible responses mix which can also cause session mix
