### ISSUE TITLE
Cache synchronization issue with RLocalCachedMap

### ISSUE THREAD

**Issue by kaisernick** [redisson/redisson#4749]
I'm running version 3.17.7 of the Redisson client in a mircoservice architecture (see image attached). I'm using the `RLocalCachedMap` in my services.  When updating a value that exists in all local caches of Service-A through an API call on Service-A Pod-1, that update is not being reflected in Pod-2. The value does not get updated until the expiration hits and the local cache fetches from the remote Redis cache.

Also seeing this in the logs:
"Unable to acquire subscription lock after 7500 ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters."

We are using the defaults for these parameters. Can you explain what these properties do? Could an incorrect configuration of them be related to the cache synchronization problem I'm seeing?

![B827F3AE-22DE-4181-AD5F-9273CEEAA190](https://user-images.githubusercontent.com/61715981/208251443-1e6bc8e6-fbc0-4400-8586-87b44d2eaa65.jpeg)

**Comment by mrniko** [comment]
Each RLocalCachedMap instances requires topic channel for local cache update across all instances. So in your case I would recommend to increase 'subscriptionsPerConnection' parameter.

**Comment by kaisernick** [comment]
Thanks for the reply. 
Does this mean that a single instance is using more than 50 subscriptions to a given topic? 

Can we see how many subscriptions are currently used in order to come up with a good value for 'subscriptionsPerConnection'?

**Comment by mrniko** [comment]
You can check it with https://redis.io/commands/pubsub-channels/ command
