### ISSUE TITLE
Redisson 3.18.1+ tests breaks Java11 support

### ISSUE THREAD

**Issue by jordanrmerrick** [redisson/redisson#4756]
**Expected behavior**
Redisson 3.18.1+ compiles and has its tests run with Java 11.

**Actual behavior**
Redisson 3.18.1+ does not have its tests run with Java 11. [This change](https://github.com/redisson/redisson/commit/1de67f7388b359faaee0a453a4a8908774f3efec) breaks support by upgrading to Tomcat 10.x, and using `jakarta.servlet.*` in some tests. These tests require `spring-web`, which now expects to use Tomcat 10.x. This, in turn, requires spring-web 6.x, which requires java 17+.

**Steps to reproduce or test case**
Build Redisson 3.18.1 or 3.19.0 on Java 11.

**Redis version**
N/A
**Redisson version**
3.19.0
**Redisson configuration**
N/A

**Comment by jordanrmerrick** [comment]
Can we release a hotfix to use Tomcat <10.x? My use case includes Redis Functions, so I would need the fix from #4730 (hence why I can't use 3.18.0).

**Comment by mrniko** [comment]
Just skip RedissonSessionManagerTest. Redisson Spring Session implementation was deprecated long ago. Now it uses native Spring implementation.
