### ISSUE TITLE
upgrade to 3.19.0 and Kryo5Codec compatible doubt

### ISSUE THREAD

**Issue by yinyansheng** [redisson/redisson#4767]
i see the change log and find the breaking change,  default codec changed to Kryo5Codec.

I want to confirm the new Kryo5Codec compatible with the old data that may serialized by the other methods

if i want to upgrade to the latest version, is there anything need to consideration

thank you

**Comment by mrniko** [comment]
data serialized with Kryo5Codec isn't compatible with data serialized with MarshallingCodec
