### ISSUE TITLE
Classfile version 61 (Java17) change intended?

### ISSUE THREAD

**Issue by uweschaefer** [redisson/redisson#4768]
Is it an intended or accidental change to publish redisson compiled with java17 target and thus break everyone not yet lucky enough to be on 17?
If so, wouldn't a change like this be good to be documented as incompatible in the release notes?

Also i was expecting such a drastic thing to be a major, rather than a minor change (in terms of SemVer).

**Comment by mrniko** [comment]
Can you point on that class? All classes compiled with java 8 target

```
public class org.redisson.Redisson implements org.redisson.api.RedissonClient
  minor version: 0
  major version: 52
```

**Comment by uweschaefer** [comment]
my bad. I rechecked all classes from 3.18,19.0 and 19.1... Don't know what i saw... :blush:
