### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Can't decode replay: \u0015\u0003\u0001\u0000\u0002\u0002

### ISSUE THREAD

**Issue by kaviarasupgk** [redisson/redisson#4772]
Getting this issue when trying to connect the Gcloud redis from websphere liberty app. This issue is similar to the github request number: https://github.com/redisson/redisson/issues/4333 Kindly provide the solution and that would be helpful.

Caused by: java.lang.IllegalStateException: Can't decode replay: \u0015\u0003\u0001\u0000\u0002\u0002F
org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:281)
org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:95)
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
00000068 id= io.netty.channel.DefaultChannelPipeline W onUnhandledInboundException An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/4333#issuecomment-1145553345

**Comment by kaviarasupgk** [comment]
After adding the trace log with org.redisson, I can able to identify that my application is not able to connect the GCP redis instance.
Can you please provide any standalone java app with redisson client for connecting redis in GCP?

**Comment by mrniko** [comment]
Can you share the logs?

**Comment by mrniko** [comment]
Unable to reproduce.

**Comment by priyankgosalia** [comment]
We're getting the same error while connecting to Redis on GCP. Was there ever a solution to this issue? Any leads would be helpful.

**Comment by mrniko** [comment]
@priyankgosalia 

Can you set `TRACE` logging level for `org.redisson` package and share the logs from the application start moment?
