### ISSUE TITLE
Are Redis Functions supported and used to manage tasks like eviction?

### ISSUE THREAD

**Issue by nicdard** [redisson/redisson#4775]
In Redis 7 they introduced the possibility to use redis functions: https://redis.io/docs/manual/programmability/functions-intro/

I find this interesting especially for eviction related complex logic, I see in the comments of the `RMapCache` that you use a `complex lua script` to manage expiration of the entries. I was wondering whether you use those redis functions when available and if it makes sense in your opinion to add support for them when those are not already used. (I think this approach could be used in other places as well)

**Comment by nicdard** [comment]
I was wondering for example at why you use an `EVAL` command in some eviction tasks, which requires sending the script everytime to the server, instead of something like `EVALSHA` or a function.

Another thing I am wondering about is whether there is any difference when having multiple services connecting to the same redis instance for the same data in case we have a TTL set for the keys, is the eviction script scheduled by all the clients (and sent to the server multiple times, cached multiple times if using `EVALSHA`)? One thing I noticed is that with the functions the script is preloaded and shared by all the clients

**Comment by mrniko** [comment]
@nicdard 

You can set `useScriptCache` = true to activate lua script caching. 

There is a tasklatch key which prevents script from execution by multiple clients at once. It's checked at the beginning of the script.

**Comment by nicdard** [comment]
@mrniko 

In case multiple clients are using the same lua scripts, do the scripts happen to be loaded multiple times in redis?

**Comment by mrniko** [comment]
no

**Comment by nicdard** [comment]
Thanks!
