### ISSUE TITLE
Logging WARN --  Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: org.redisson.spring.starter.RedissonAutoConfiguration

### ISSUE THREAD

**Issue by bugoverflow-fix** [redisson/redisson#4778]
Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: org.redisson.spring.starter.RedissonAutoConfiguration

SpringBoot 3.0.1

Redisson 3.19.0

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/4757
