### ISSUE TITLE
why ClassCastException happened when  I use Rlist.readAll()

### ISSUE THREAD

**Issue by qqwangxiaow** [redisson/redisson#4779]
I met some error when I deploy my app.
verison 3.17.6
java.Lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap") at org. rediss on. RedissonList.readAlI(RedissonList.java:102)

**Comment by mrniko** [comment]
Which codec do you use?

**Comment by qqwangxiaow** [comment]
we change to kryo 4.0.2

**Comment by qqwangxiaow** [comment]
@mrniko we use kryo 4.0.2 always，but this prolem happens when we update redisson from 3.13.4 to 3.17.6

**Comment by mrniko** [comment]
> java.lang.String and java.util.List are in module java.base of loader 'bootstrap"

Did you try to add `--add-opens=java.base/java.util=ALL-UNNAMED` argument to JVM ?
