### ISSUE TITLE
Kryo5Codec with redisson-3.19.1 clarification

### ISSUE THREAD

**Issue by mzhafez** [redisson/redisson#4780]
Release notes read:
```
Breaking change - Kryo5Codec uses own serializators to serialize UUID, URI and Pattern objects
```
Could you clarify what this means and implies?

**Comment by mrniko** [comment]
It means that if you serialized object which has UUID, URI or Pattern with previous version. You won't be able to decode them with new version. Since serialization method has changed for these object.
