### ISSUE TITLE
Is it possible to set concurrency level for SequentialDnsAddressResolverFactory in Quarkus extension?

### ISSUE THREAD

**Issue by sara-han** [redisson/redisson#4781]
We're using Quarkus extension 3.18.1, and we observed DnsNameResolverTimeoutException occasionally. We have a lot of k8s pods connecting to AWS Elasticache cluster. We'd like to try to tune the concurrency level of SequentialDnsAddressResolverFactory as suggested in [#4577](https://github.com/redisson/redisson/pull/4577). 

Is it possible to configure the concurrency level of SequentialDnsAddressResolverFactory in Quarkus extension?

**Comment by mrniko** [comment]
I'm afraid no. You need to create a subclass of SequentialDnsAddressResolverFactory  and specify it in config
