### ISSUE TITLE
Why does RedissonFunction.load(...) send "Lua" and libraryName as params under the hood?

### ISSUE THREAD

**Issue by gimboleo** [redisson/redisson#4782]
I'm having problems with loading a function to Redis - I'm getting a `org.redisson.client.RedisException: ERR Unknown option given: Lua.`

Redis documentation states that `FUNCTION LOAD` only takes an optional `REPLACE` modifier and a single `function-code` parameter that starts with a shebang statement containing the engine name (Lua) and the library name.

Where's the discrepancy coming from? Any help would be appreciated.

**Comment by mrniko** [comment]
Fixed! Thanks for report
