### ISSUE TITLE
there is exception that Cannot assign requested address:  connect: ip/ip:0 after redisson upgrade from 3.16.8 to 3.19.1 when springboot startup

### ISSUE THREAD

**Issue by jiushiweisuo** [redisson/redisson#4784]
I upgrade redissson-spring-boot-starter from  3.16.8 to 3.19.1。but there is exception that Cannot assign requested address:  connect: ip/ip:0。I saw 3.16.8  and 3.19.1 source code，I find there is same exception in 3.16.8 that is not throw it。so wanna ask：
What does port 0 do and how do I configure it？
and can I ignore it？
thank you for your help

**Comment by mrniko** [comment]
It's related to netty library update.
