### ISSUE TITLE
Question about RMapCache and containsKey

### ISSUE THREAD

**Issue by rrourke** [redisson/redisson#4786]
I am trying to figure out how redisson takes a custom object and makes that into a key.  In my code I have implemented hashCode and equals method but when my subclass is saved as a key and then the parent class is used to try and access it, containsKey returns false even though both equals and hashcode are implemented and equal each other.  

Ive tried using custom writeObject and readObject but that didn't work either.

When coming from caffeine we just had to implement a comparator and that worked but I'm not sure if I can do something similar for this.

Example class:
```
public class BytesKey extends ... implements Comparable<BytesKey>, Serializable {
protected int hashCode;
public BytesKey(byte[] bytes) {
    super(bytes);
    this.hashCode = super.hashCode();
  }

@Override
  public int hashCode() {
    return hashCode;
  }
@Override
  public boolean equals(Object o) {
    int test = o.hashCode();
    return this.hashCode == o.hashCode();
  }

  private void writeObject(ObjectOutputStream oos) throws Exception
  {
    oos.writeObject(bytes);
    oos.writeObject(hashCode);
  }

  private void readObject(ObjectInputStream ois) throws Exception
  {
    // performing default deserialization of Account object
    bytes = (byte[]) ois.readObject();
    hashCode = (int) ois.readObject();
  }
}
```

Subclass
```
private static class InternedBytesKey extends BytesKey implements Serializable {
InternedBytesKey(byte[] bytes) {
      super(bytes);
    }
...
}
```

**Comment by rrourke** [comment]
Just to follow up, I'm trying to figure out how Redisson determines how to convert an object into a key?

**Comment by mrniko** [comment]
`hashCode()`/`equals()` methods of key object aren't used, instead it uses hash of serialized state.
