### ISSUE TITLE
SpringBoot use 3.19.1 exception

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#4790]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
![image](https://user-images.githubusercontent.com/31852897/211995178-009f8f12-13d0-4d1c-9fb5-0493c3a41d81.png)
![image](https://user-images.githubusercontent.com/31852897/211995225-4c2acffa-1876-4a83-8a6c-1a2ab5537a4e.png)
![image](https://user-images.githubusercontent.com/31852897/211995317-4ff0a50f-1804-4759-a087-71c563805eab.png)

不清楚为啥SpringBoot2.X 会引入  redisson-spring-data-30 
看官网写的 springboot2.X应该对应 redisson-spring-data-20
是否为 3.19.1 版本已经不支持 boot2了 我看默认的依赖已经改成了 boot3
![image](https://user-images.githubusercontent.com/31852897/211995468-51d66420-b48f-4115-b730-76772b8c807f.png)

**Redis version**
6.2.7
**Redisson version**
3.19.1
springboot 2.7.7
**Redisson configuration**

**Comment by mrniko** [comment]
You need to check classpath for class presence

**Comment by JavaLionLi** [comment]
> You need to check classpath for class presence

回退到 3.18.0 对接boot3之前就是正常的

**Comment by JavaLionLi** [comment]
排除 redisson-spring-data-30 引入 redisson-spring-data-27
redisson 版本不变 3.19.1 问题解决了
你们这个有兼容性问题 本地测试正常 打包之后就不正常了

**Comment by mrniko** [comment]
You need to use redisson-spring-data-27 for springboot 2.7.x as stated in table https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#1-add-redisson-spring-boot-starter-dependency-into-your-project
