### ISSUE TITLE
Untrusted data deserialization mitigation

### ISSUE THREAD

**Issue by Gregory-Widmer** [redisson/redisson#4793]
Hello,

As always in development, deserializing data is a sensitive point in terms of security. Based on Zero-trust models, I assume that everything that I deserialize contains malicient payload and must be checked before usage.

Here, I'd like to make sure that Redisson won't deserialize a Payload that I don't approve.

One (and probably the best one as far as I know/can imagine) approach would be to make deserialization secured by default. It means you can't deserialize anything which has not been explicitely declared as accepted for deserialization.

This whitelist feature would be a by-default setting that ensures that the developer does not introduce an attack vector (e.g an entrypoint for deserialization chains - check [YSoSerial project](https://github.com/frohoff/ysoserial) for an example of what could be done with unsecure deserialization).

Is there any documentation on what Redisson offers in terms of security practices regarding Serialization/Deserialization ?

Let's take this use case : 
 - I want to use Redis to cache some objects
 - I have my `Dummy` class, implementing the `Serializable` interface. 
 - I am using a `RList<Dummy>` object to store it in a cache.
 - If an attacker compromises my Redis cluster, injects a serialized object that could be deserialized by my runtime (class available), it could run malicious code, hence creating a Remote-Code Execution vulnerability.

Is there any information on how we can handle it and if Redisson mitigates that ?

**Comment by mrniko** [comment]
> Here, I'd like to make sure that Redisson won't deserialize a Payload that I don't approve.

You can solve it by implementation of custom codec
