### ISSUE TITLE
"addressResolverGroupFactory" or "nettyHook" can't be configured by "quarkus.redisson.xxx" settings

### ISSUE THREAD

**Issue by sara-han** [redisson/redisson#4794]
**Expected behavior**
Using this kind of configuration in Quarkus should work:
`quarkus.redisson.address-resolver-group-factory=org.redisson.connection.SequentialDnsAddressResolverFactory`

**Actual behavior**
Got error:
"Could not resolve subtype of [simple type, class org.redisson.connection.AddressResolverGroupFactory]: missing type id property 'class' (for POJO property 'addressResolverGroupFactory')\n at [Source: (StringReader); line: 1, column: 30] (through reference chain: org.redisson.config.Config[\"addressresolvergroupfactory\"])"

**Redisson version**
3.18.1

This might be the problem. 
Here it gets the configurations from Quarkus configurations and generates config yaml for Redisson:
https://github.com/redisson/redisson/blob/master/redisson-quarkus/redisson-quarkus-20/runtime/src/main/java/io/quarkus/redisson/client/runtime/RedissonClientProducer.java#L67

Then it gets here where only "codec" and "load-balancer" is formatted to represent class objects. "address-resolver-group-factory" is treated as a string:
https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/config/PropertiesConvertor.java#L97

**Comment by mrniko** [comment]
Fixed! Thanks for report
