### ISSUE TITLE
Write to Read Reentrance

### ISSUE THREAD

**Issue by david-laurentino** [redisson/redisson#4796]
My Application enters a deadlock when a thread that has read access tries to acquire write access too.

I noticed that RedissonWriteLock support **Write to Read** reentrance, as you can see in RedissonReadLock.java line 69:
if (mode == 'read') or (**mode == 'write' and redis.call('hexists', KEYS[1], ARGV[3]) == 1**) then
(if the thread has the write permission, read access is granted)

but it doesn't seem to support **Read to Write** reentrance, as you can see in RedissonWriteLock.java line 65:
`if (mode == 'write') then`
(only write to write reentrance allowed?)

If the thread is the only read on the lock, shouldn't write access be granted? That is:
`if (mode == 'write') or (mode == 'read' and redis.call('hget', KEYS[1],  ARGV[2]) == 1) then`

**Comment by mrniko** [comment]
It's by design. Write lock can't be acquired while read locks are acquired.
