### ISSUE TITLE
Make sync with replica configurable when using distributed lock. 

### ISSUE THREAD

**Issue by jgaoIXL** [redisson/redisson#4798]
**Is your feature request related to a problem? Please describe.**
We are using redisson for our distributed lock. We were seeing issues with unlock latency jumping to more than 1000 ms when we do live cluster configuration where replicas were brought down and up. After reading the code, I saw that this is due to a wait command being issued so that it only returns after 1 second timeout or all replicas of the master were synced. Form what I understand, the purpose of syncing with replicas is to increase consistency? However, this is not ideal for our use cases. 

**Describe the solution you'd like**
Can we make the sync slaves number of replicas and timeout configurable? 
`        BatchOptions options = BatchOptions.defaults()
                                            .syncSlaves(availableSlaves, 1, TimeUnit.SECONDS);`
                                            
**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Can you try 3.18.1+ version? It now checks 'connected_slaves' property of redis node

**Comment by jgaoIXL** [comment]
Yes, but ideally we would still want to be able to configure sync slaves behavior, the timeout and number of slaves.

**Comment by jgaoIXL** [comment]
> Can you try 3.18.1+ version? It now checks 'connected_slaves' property of redis node

Yes, but ideally we would still want to be able to configure sync slaves behavior, the timeout and number of slaves.

**Comment by mrniko** [comment]
I'll introduce a `lockSyncedSlavesTimeout` setting

**Comment by jgaoIXL** [comment]
> I'll introduce a `lockSyncedSlavesTimeout` setting

Awesome, thank you, is there going to be a timeline for this change to a release version? If that takes too long, I need to consider incorporate your change to a forked redisson, and build our own version.

**Comment by jgaoIXL** [comment]
Hi @mrniko, just want to check in on this, I see now it is marked to 3.21.X, is there any timeline for a release with this change?

**Comment by mrniko** [comment]
Hi @jgaoIXL, during next week
