### ISSUE TITLE
Does RLock.lock remove key from redis?

### ISSUE THREAD

**Issue by Totoro101** [redisson/redisson#4805]
When i do RLock.lock, i found that key on the redis will be disappear with given lease time (if not set up then it will be 30 secs).
This is what i saw on redis log, which it using "pexpire" on the key, from what i know, this command will remove the key after the given time. 
![image](https://user-images.githubusercontent.com/123137767/213609007-24d0414a-caa6-4305-a04d-d241dc237256.png)

Should remove the lock only right not the key.
may i know is this true action from RLock.lock or is this a bug

here is my code
RReadWriteLock rwlock = redisson.getReadWriteLock(key);
RLock lock = rwlock.writeLock();
lock.tryLock(0, 5, TimeUnit.SECONDS);

**Comment by mrniko** [comment]
`pexpire` command invoked by RLock object. Can you provide more details about the issue?

**Comment by Totoro101** [comment]
appreciate for your reply.
I think i got wrong idea of lock.
I will close this question
