### ISSUE TITLE
LinkedHashSet serialization

### ISSUE THREAD

**Issue by julien-echasserieau** [redisson/redisson#4807]
Hello,
		
Since redisson 3.19, we experience an issue regarding **LinkedHashSet** serialization.
This kind of object is not instantiated correctly and this leads to a NullPointerException. 
In redisson 3.19, it looks like the instantiator Strategy is not the same as before.
Do you know if this change can be related to the LinkedHashSet error we have ? 
Thank you for your help,

**Comment by mrniko** [comment]
Caused by migration to a Kryo5Codec. As temporary workaround you can comment out this line https://github.com/redisson/redisson/blob/1019909c8309bbe921950bbde8b71d2b292cc96e/redisson/src/main/java/org/redisson/codec/Kryo5Codec.java#L90

**Comment by mrniko** [comment]
Fixed! Thanks for report
