### ISSUE TITLE
in a JCache Read-Through calling Cache.getAll(...)  doesn't call CacheLoader.loadAll(...), is this a normal behaviour?

### ISSUE THREAD

**Issue by fedxyz** [redisson/redisson#4810]
Hi,

I am using JCache with Redisson, I configured the cache as Read-Through and setup a CacheLoader.

What I noted is that calling `Cache.getAll(...)` doesn't call the `CacheLoader.loadAll(...)` method to load values, is still use the `CacheLoader.load(...)`.

Is this the expected behaviour?

Thanks for the help.

**Comment by fedxyz** [comment]
Just to add a note, on the specification page of [JCache JSR107 (JCache)](https://github.com/jsr107/jsr107spec) on the Google doc linked there about specification, at the table on page 65 (the Read-Through Caching section) it's written:

`Map<K,V> getAll(Collection<? extends K> keys)         Yes. Invokes loadAll()`

**Comment by mrniko** [comment]
Fixed! Thanks for report
