### ISSUE TITLE
Optimize rateLimiter

### ISSUE THREAD

**Issue by dongmaxiang** [redisson/redisson#4813]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Set the expiration time for the keys used in traffic limiting to prevent the number of keys from increasing

**Describe alternatives you've considered**
Set expiration time

**Comment by mrniko** [comment]
I don't think it's a good idea. Limiter stops work after rateInterval time according to your code.

**Comment by dongmaxiang** [comment]
Why not a good idea? Isn't it common to limit traffic according to user ID and IP? If you control by code, there will be inconsistency. What if server goes down? Isn't key immortal?

**Comment by mrniko** [comment]
> Isn't it common to limit traffic according to user ID and IP? 

I'm afraid no.

> What if server goes down? Isn't key immortal?

You can use `expire` method to set expiration for whole limiter.
