### ISSUE TITLE
ClientConnectionsEntry returns empty connections queue for master node (entry)

### ISSUE THREAD

**Issue by wormock** [redisson/redisson#4816]
Hello, I'm trying to see the number of open connections from the connection pool for each redis node. For slave nodes it's ok. Open connections for slave node is equal for slaveConnectionMinimumIdleSize, but masterConnectionMinimumIdleSize. Also redisson logger print to console that all connections were opened. I'm using 3.19.1 version of Redisson
`(redisson as RedissonReactive).connectionManager.entrySet
        .forEach {
            it.allEntries.forEach { entry ->
                entry.allConnections.filter { it.isOpen }.size.also { println("$it CONNECTIONS for ${entry.client.addr.hostName}") }
            }
        }`
<img width="334" alt="image" src="https://user-images.githubusercontent.com/17675200/214518509-bfd238ff-5ae5-430a-a952-b46b611eee4e.png">
4 opened connections for each slave node, 0 connections for master node.
<img width="983" alt="image" src="https://user-images.githubusercontent.com/17675200/214518683-f09dea1f-fb00-4d94-a1b5-33bc596606fc.png">

**Comment by mrniko** [comment]
Can you describe what is the issue exactly?

**Comment by wormock** [comment]
i'm trying get info about connections by connection manager. I get from ConnectionManager entry set and for each element get all entries. and entry for master node doesn't have any connections.
queue of connections for master node in ClientConnectionsEntry are empty, but exactly 24 connections was opened for master node. also this node is freezed by SYSTEM.
`connections: [], [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:64:queue:0, freezeReason=SYSTEM, client=[addr=someAdress:6379], nodeType=MASTER, firstFail=0]`

**Comment by mrniko** [comment]
Sorry, this is an internal API and not designed for usage.
