### ISSUE TITLE
Single RLock  instance can acquire lock with previous leaseTime when leaseTime is not specified

### ISSUE THREAD

**Issue by vladimirkl** [redisson/redisson#4818]
**Expected behavior**

When using single RLock instance for acquiring and releasing lock multiple times lock is always aqcuired  with expected lease time or without it if not specified. Previous lock acquisitions do not affect subsequent.   

**Actual behavior**

Suppose we use single RLock instance and acquire lock with leaseTime, then unlock it. After this we acquire lock with same instance but without leaseTime. In this case RLock uses previous leaseTime saved in `internalLockLeaseTime` variable and creates Redis key with it. Then it starts renewal and eventually sets TTL to lock watchdog timeout. But if app failed immediately  after acquiring lock, key stays in Redis with TTL from previous acquisition.

**Steps to reproduce or test case**
```java
RedissonClient redisson = Redisson.create(config);
RLock lock = redisson.getLock("test-lock:1");
lock.lock(1, TimeUnit.HOURS);
lock.unlock();
lock.lock();
System.out.println(lock.remainTimeToLive()); // prints value close to 1 hour
System.exit(0);
```
**Redis version**
5.0.7
**Redisson version**
3.19.1
**Redisson configuration**
Sentinel or local

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by victornoel** [comment]
Hey @mrniko, since this bugfix, I had a change of behavour related to locking and I was wondering if this is expected or if this fix introduced a different bug.

My use case is the following:
```java
RedissonClient redisson = Redisson.create(config);
RLock lock = redisson.getLock("test-lock:1");
lock.lock(2, TimeUnit.MINUTES);
System.sleep(1000)
lock.lock(2, TimeUnit.MINUTES);
System.out.println(lock.remainTimeToLive()); // prints value close to 2 minutes
```

Before 3.19.2, the remainTimeToLive would be 1 minute instead!

**Comment by mrniko** [comment]
@victornoel 

Can you create a separate issue?

**Comment by victornoel** [comment]
@mrniko yes and I think my example is not correct, I will try to build a real repro to be sure I'm explaining the problem correctly!
