### ISSUE TITLE
RecomputeFieldValue.ArrayBaseOffset automatic substitution failed - Quarkus native build

### ISSUE THREAD

**Issue by denysandriyanov** [redisson/redisson#4820]
During qarkus native build getting following warnings:

Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of com.esotericsoftware.kryo.unsafe.UnsafeUtil. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.

**Comment by mrniko** [comment]
Is there any way to reproduce it?

**Comment by denysandriyanov** [comment]
I am using quarkus native build
    GRADLE_STEPS: clean build 
    GRADLE_EXTRA_ARGS:
      -Dquarkus.package.type=native
      -Dquarkus.native.container-build=true
      -Dquarkus.native.container-runtime=docker

Using     implementation 'org.redisson:redisson-quarkus-20:3.19.1'

Using Rbucket and RLock

**Comment by mrniko** [comment]
`Disable unsafe on GraalVM with -Dkryo.unsafe=false.`
