### ISSUE TITLE
The connectTimeout attribute of redisson is set incorrectly

### ISSUE THREAD

**Issue by neko-11** [redisson/redisson#4826]
In the redisson-spring-boot-starter dependency package

org.redisson.spring.starter.RedissonAutoConfiguration#redisson

![image](https://user-images.githubusercontent.com/32889558/215420065-d2ce23d8-36b0-4e13-b920-0e36562fa4ff.png)

Read the timeout of RedisProperties, set it as the connectTimeout of BaseConfig, why not use the connectTimeout of RedisProperties？

**Comment by mrniko** [comment]
Meaning of this setting has been changed since 2.4.0 version

**Comment by mrniko** [comment]
Fixed! Thanks for report
