### ISSUE TITLE
Node: NodeSource [slot=6128, addr=null, redisClient=null, redirect=null, entry=null] can't be found

### ISSUE THREAD

**Issue by silencefan** [redisson/redisson#4828]
Error reporting method：org.redisson.connection.MasterSlaveConnectionManager#releaseWrite()
Exception information：Node: NodeSource [slot=6128, addr=null, redisClient=null, redirect=null, entry=null] can't be found
redission version：3.15.1
I don't know how this error was caused.

**Comment by mrniko** [comment]
can you share logs before this error?

**Comment by HugoYip** [comment]
Hi there, I got the same issue as above, and I had totally check my production redis cluster, could cetrain that is healthy and no network issue. below is my running logs, please help to check the error, thanks
![logs](https://github.com/user-attachments/assets/971cc917-42f6-429c-bbde-c9dd07ddef17)

**Comment by mrniko** [comment]
@HugoYip 

Which Redisson version is used?
Can you share the stack trace of that error?

**Comment by HugoYip** [comment]
> @HugoYip
> 
> Which Redisson version is used? Can you share the stack trace of that error?

Hi, version is 3.40.2, and redis is 7.4.1. sorry that not able to stop the server and add stack trace param

**Comment by mrniko** [comment]
@HugoYip 

I'm afraid you're using an old Redisson version, since there is no MasterSlaveConnectionManager.releaseWrite() method. Please clarify the version.

**Comment by HugoYip** [comment]
> @HugoYip
> 
> I'm afraid you're using an old Redisson version, since there is no MasterSlaveConnectionManager.releaseWrite() method. Please clarify the version.

You mean it is removed in new version? Thanks for your help, I will check my reference in maven.

**Comment by mrniko** [comment]
@HugoYip 

Yes
