### ISSUE TITLE
Redisson Cluster Master-Slave Switchover Issue

### ISSUE THREAD

**Issue by sray3546** [redisson/redisson#4829]
******************************************************************************************************************************************************************************************
Expected Scenario, Everthings works fine
    Sentinels
    vm-16 (Master)
    vm-17
    vm-18
App_instance_1 in vm15 -> Redission client is connected to vm-16
App_instance_2 in vm14 -> Redission client is connected to vm-16

Expected Behaviour
    After the redis master switch over the client connections are refreshed correctly

******************************************************************************************************************************************************************************************

Current Scenario, A swithover is triggered as vm-16 is rebooted
    Sentinels
    vm-16 
    vm-17 (Master)
    vm-18
App_instance_1 in vm15 -> Redission client is still connected to vm-16
App_instance_2 in vm14 -> Redission client is connected to vm-17
Calls from App_instance_2 is succuessful where as calls from App_instance_1 is failing as write is not allowed. The switchover in the redission client was visible only in App_instance_2

Current Behaviour
    Only in one instance the refresh was visible and not in the other instance. Only when App_instance_1 was restarted it started to work as it got connected to the right master.

Redisson version - 3.16.2
******************************************************************************************************************************************************************************************

**Comment by mrniko** [comment]
3.16.1, 3.16.2 has connection leak problem. You need to update version
