### ISSUE TITLE
Redis transaction works in JVM but not native

### ISSUE THREAD

**Issue by yuyujiejie** [redisson/redisson#4833]
**Expected behavior**
Able to add a key within a redis transaction in quarkus native build

**Actual behavior**
Behaviour is throwing ClassCastException (Boolean to Mono) when calling add() method for RSetReactive

**Steps to reproduce or test case**
- Create reactive client
- Create RTransactionReactive object
- Call getSet<String> with some key
- Call add() method 
- Get ClassCastException
`"java.lang.ClassCastException: java.lang.Boolean cannot be cast to reactor.core.publisher.Mono `

**Redis version**

**Redisson version**
3.17

**Redisson configuration**

**Comment by yuyujiejie** [comment]
stack trace is here
"stackTrace": [ "java.lang.ClassCastException: java.lang.Boolean cannot be cast to reactor.core.publisher.Mono
\n\tat com.sun.proxy.$Proxy383.add(Unknown Source)
\n\tat com.dbs.dbatch.gui.helper.actionmessage.RemoteJobExecuteUtils$Companion.addOrRemoveJobUidToCriticalRunningAndAssignedSet(RemoteJobExecuteUtils.kt:134)
\n\tat com.dbs.dbatch.gui.helper.actionmessage.RemoteJobExecuteUtils$Companion.addJobUidToCriticalRunningAndAssignedSet(RemoteJobExecuteUtils.kt:72)
\n\tat com.dbs.dbatch.gui.service.DBatchService.executeRemoteCommand$suspendImpl(DBatchService.kt:187)
\n\tat com.dbs.dbatch.gui.service.DBatchService$executeRemoteCommand$1.invokeSuspend(DBatchService.kt)
\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
\n\tat org.jboss.resteasy.reactive.server.runtime.kotlin.VertxDispatcher.dispatch$lambda$0(ApplicationCoroutineScope.kt:43)
\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
\n\tat io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
\n\tat java.lang.Thread.run(Thread.java:829)
\n\tat com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:600)
\n\tat com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)\n" ], "stackTrace.keyword": [ "java.lang.ClassCastException: java.lang.Boolean cannot be cast to reactor.core.publisher.Mono
\n\tat com.sun.proxy.$Proxy383.add(Unknown Source)
\n\tat com.dbs.dbatch.gui.helper.actionmessage.RemoteJobExecuteUtils$Companion.addOrRemoveJobUidToCriticalRunningAndAssignedSet(RemoteJobExecuteUtils.kt:134)
\n\tat com.dbs.dbatch.gui.helper.actionmessage.RemoteJobExecuteUtils$Companion.addJobUidToCriticalRunningAndAssignedSet(RemoteJobExecuteUtils.kt:72)
\n\tat com.dbs.dbatch.gui.service.DBatchService.executeRemoteCommand$suspendImpl(DBatchService.kt:187)
\n\tat com.dbs.dbatch.gui.service.DBatchService$executeRemoteCommand$1.invokeSuspend(DBatchService.kt)
\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
\n\tat org.jboss.resteasy.reactive.server.runtime.kotlin.VertxDispatcher.dispatch$lambda$0(ApplicationCoroutineScope.kt:43)
\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
\n\tat io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
\n\tat java.lang.Thread.run(Thread.java:829)
\n\tat com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:600)
\n\tat com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)\n" ]

**Comment by mrniko** [comment]
Fixed. Thanks for report
