### ISSUE TITLE
why does add() and contains() method in RBloomFilter take so long?

### ISSUE THREAD

**Issue by longslee** [redisson/redisson#4840]
I just wanna try how does redisson bloomfilter cost , the weird thing is that it took 36 seconds to insert 1000 elements, also took 30 seconds to show contains in a loop. Even I set expectedInserctions 1000, and falseProbability just 0.1.

Other informations: OpenJDK-11,  Redis-Server 6.2.7, Redisson 3.17.0

code:
```
long begin = System.currentTimeMillis();
        RBloomFilter<String> bloomFilter = redissonClient.getBloomFilter("adm:perm:token:test");
        bloomFilter.delete();
        bloomFilter.tryInit(1000, 0.1);
        //add 1000 elements
        for (int i = 0; i < 1000; i++) {
            bloomFilter.add("tom " + i);
        }
        System.out.println("duration:" + (System.currentTimeMillis() - begin));
```
duration:36231

Add:

After upgrading to version 3.9.12, still exists.

**Comment by mrniko** [comment]
expectedInserctions setting doesn't affect on insertion speed

**Comment by mrniko** [comment]
Check your data size/network/redis speed

**Comment by longslee** [comment]
> 
size 1000, network & redis works well

**Comment by mrniko** [comment]
Try to use add() method with element collection support executed in a batch https://github.com/redisson/redisson/issues/5130
