### ISSUE TITLE
Eviction by key for RMap

### ISSUE THREAD

**Issue by ls-rein-martha** [redisson/redisson#4842]
**Is your feature request related to a problem? Please describe.**
If I set the RMap with write-behind, then I can't evict a key manually without affecting my storage. 

**Describe the solution you'd like**).
RMap to have `evict` method that will only evict from Redis without affecting external storages when using the write-behind strategy.

**Describe alternatives you've considered**
Possibly can be solved by adding `evict(key)` and simply calling `removeOperationAsync` (that is protected encapsulation thus no simple workaround).

**Comment by mrniko** [comment]
you can do it with Map object acquired without defined MapWriter

**Comment by ls-rein-martha** [comment]
> you can do it with Map object acquired without defined MapWriter

HI, @mrniko thank you for the suggestion. It indeed solves the problem.
So maybe this is just a suggestion to make it easier, not really a blocker.

**Comment by mrniko** [comment]
Sorry, this doesn't fit in architecture of RMap object.
