### ISSUE TITLE
How to upgrade Redisson client in an application using LZ4Codec

### ISSUE THREAD

**Issue by sara-han** [redisson/redisson#4857]
The current Redisson client version in our application is 3.18.1. After upgrading the client version to 3.19.3, deserialization failure happened when reading the data that was saved by version 3.18.1. We use the Redisson client extension for Quarkus. We use LZ4Codec to read and write data. The configuration is "quarkus.redisson.codec=org.redisson.codec.LZ4Codec".

The value that is saved to Redis is a string like this:
"1675896840000:{2126=42448.0, 2127=103265.0, 2128=168.0, 2129=230.0};1675896840000:{2128=0.0667, 2129=0.0833, 2126=7.2167, 2127=90.0667}"

The error message when reading the data is "java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.String". 

We suspect that this breakage is caused by the change of the default codec to Kryo5Codec, as it's mentioned in the documentation that the LZ4 codec uses Kryo5codec for serialization. 

We would like our data to be interpreted correctly when we upgrade to a newer library version. Please suggest what options are available to us.

**Comment by mrniko** [comment]
You need to extend LZ4Codec and specify old MarshallingCodec in constructor.
