### ISSUE TITLE
In extreme cases, two threads will not acquire the same lock at the same time

### ISSUE THREAD

**Issue by ShaddockCyan** [redisson/redisson#4863]
**Is your feature request related to a problem? Please describe.**
Hello, developer. We all know that whether you use Redison, Zookeeper or Redlock, you will encounter a problem. In extreme cases, if full gc occurs, or for network reasons, two threads will acquire the lock at the same time.
**Describe the solution you'd like**
Solve the problem that distributed locks will be acquired by two threads at the same time in extreme scenarios
**Describe alternatives you've considered**
I have an immature idea. If we use long links when interacting with Redis, we can solve this problem by only letting the locking thread notify Redis to release the lock. If it is detected that the lock has not been released, it is assumed that the thread is disconnected or suspended for network reasons, and we will not release the lock. At the same time, when the suspended thread resumes execution, the daemon thread will immediately suspend the main thread and try to resume the link, and then continue to execute the main thread until the link is resumed. So in extreme scenarios, only one line of code will be executed by two threads at the same time, and we can also judge and obtain which line of code is executed. We can ask the developer to define reverse operation or roundabout operation for each write operation in the code to solve this problem. In addition, if establishing long links is very resource-consuming, we may be able to open up multiple channels in one connection.

**Comment by mrniko** [comment]
You need to use FencedLock https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers/#810-fenced-lock
