### ISSUE TITLE
Releasing the lock when the lock is determined to be acquired. Why does this error occur? IllegalMonitorStateException - Attempt to unlock read lock, not locked by current thread

### ISSUE THREAD

**Issue by shawnwhale** [redisson/redisson#4871]
```
RLock lock = lockService.getLock(TOPICNAME_LOCK_PREFIX + topicPrefix);
        if (lock.tryLock(5, TimeUnit.SECONDS)) {
            try {
                // Process business CODE

            } catch (Exception e) {
               throw new ServiceException(String.format("error: %s！", e));
            } finally {
                lock.unlock();
            }
        }
        // No lock obtained CODE

```
lockService code：

```
    private static RedissonClient redissonClient;
    private static synchronized void initClient(String url) {
        if (redissonClient == null) {
            try {
                URI uri = new URI(url);
                Config config = new Config();
                SingleServerConfig srvConfig = config.useSingleServer().
                setAddress(String.format("%s://%s:%s", uri.getScheme(), uri.getHost(), uri.getPort()));
                if (StringUtils.isNotBlank(uri.getUserInfo())) {
                    srvConfig.setPassword(uri.getUserInfo());
                }
                config.setLockWatchdogTimeout(10000);
                redissonClient = Redisson.create(config);
            } catch (Exception e) {
                log.error(String.format("cannot init redisson client by %s", url), e);
            }
        }
    }

    @PostConstruct
    private void init() {
        initClient(redisProperties.getUrl());
    }


    public RLock getLock(String key) {
        initClient(redisProperties.getUrl());
        return redissonClient.getLock(key);
    }
```

```
<dependency>
        <groupId>org.redisson</groupId>
        <artifactId>redisson</artifactId>
        <version>3.17.7</version>
 </dependency>
```
redis version 4.0

Exceptions sometimes occur：
`java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: ?? thread-id: ?? at org.redisson.RedissonBaseLock.lambda$unlockAsync$2(RedissonBaseLock.java:328) at ...`

The business logic is that only one task is allowed in a certain range, so it needs to acquire the lock first, and other tasks are waiting. If it does not obtain the lock after waiting for 5 seconds, another set of logic will be executed.

_This set of code has almost no errors, because lock.unlock() is only executed if lock.tryLock(5, TimeUnit.SECONDS) returns true._

However, for certain business peak hours, the above exceptions sometimes occur. The specific performance is that many tasks report errors: java.lang.IllegalMonitorStateException: attempt to unlock, not locked by current thread by node id: SameId thread id: DifferentThreadId.The above error reports occur in a centralized manner. Many threads release the same lock within a few seconds.

Is this caused by network? Or is there a problem with the code?

**Comment by shawnwhale** [comment]
My biggest question is, since it has been determined that [lock. unlock () is only executed if lock. tryLock (5, TimeUnit. SECONDS) returns true.], why do dozens of threads still have exceptions when unlocking in a few seconds?

**Comment by mrniko** [comment]
Check for keys eviction policy https://redis.io/docs/reference/eviction/

**Comment by mrniko** [comment]
Fixed. Thanks for report
