### ISSUE TITLE
aws elastic cache one shard alone storing / loading most workload

### ISSUE THREAD

**Issue by formanojhr** [redisson/redisson#4874]
We are in stabilization phase of using redisson client with aws redis elastic cache in clustered mode with two shards. 
1. We are **configuring Redisson connection endpoint to use the configendpoint** recommended by AWS. https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html. 
In the redisson clustered doc, it looks like **all node endpoint**s are mentioned https://github.com/redisson/redisson/wiki/2.-Configuration

2. We see shard 002(other is 001) seems to take most the data(69% vs 001 is 0.5% which is big difference in usage)  written while seeing AWS elastic cache metrics. This can be observed in dbmemoryusage  percent metric. 
We are using this redisson RMapCache
private RMapCache<byte[], SOME JAVA POJO> redisCache;

It clearly looks like one shard alone is taking most of the data. **Why is the distribution imbalanced**? Any pointers or documentation on this problem for recommendation would help.

**Comment by mrniko** [comment]
> In the redisson clustered doc, it looks like all node endpoints are mentioned

Could you point where exactly? `Add Redis cluster node address in host:port format. Multiple nodes could be added at once. At least one node from Redis Cluster should be specified. Redisson discovers automatically cluster topology.`

> Why is the distribution imbalanced?
That depends on key name of each RMapCache object. It's content isn't partitioned across master nodes. This feature is only supported in PRO version. https://github.com/redisson/redisson/wiki/5.-data-partitioning-(sharding)

**Comment by formanojhr** [comment]
> > In the redisson clustered doc, it looks like all node endpoints are mentioned
> 
> Could you point where exactly? `Add Redis cluster node address in host:port format. Multiple nodes could be added at once. At least one node from Redis Cluster should be specified. Redisson discovers automatically cluster topology.`
> 
> > Why is the distribution imbalanced?
> > That depends on key name of each RMapCache object. It's content isn't partitioned across master nodes. This feature is only supported in PRO version. https://github.com/redisson/redisson/wiki/5.-data-partitioning-(sharding). 

_Thanks @mrniko  ! This helps. So, it is about the key spread problem we might be having._  So can the pro version support paritioning the values inside the RMap cache? To be specific in my eg. private RMapCache<byte[], SOME JAVA POJO> redisCache the SOME JAVA POJO part? 

In terms where in the redisson doc, here is is : written https://github.com/redisson/redisson/wiki/2.-Configuration#24-cluster-mode . In the sample code, it shows```
 // use "rediss://" for SSL connection
    .addNodeAddress("redis://127.0.0.1:7000", "redis://127.0.0.1:7001")
    .addNodeAddress("redis://127.0.0.1:7002"); 
```
While in our example we only use only one addNodeAddress `config.useClusterServers().addNodeAddress(AWSRedisCacheConfigEndpoint)`. 
_Is the assumption based on your comment that the redisson client would auto discover all the shards provisioned? It seems like from your answer yes.

**Comment by mrniko** [comment]
> So can the pro version support paritioning the values inside the RMap cache?

Yes.

> Is the assumption based on your comment that the redisson client would auto discover all the shards provisioned?

In cluster mode you need to specify at least Redis node from cluster. Redisson will autodiscover other nodes.
