### ISSUE TITLE
Support for JDK17:  Kryo's serialization isn't compatibility with JDK 17+

### ISSUE THREAD

**Issue by quangdanh** [redisson/redisson#4877]
**Actual behavior**
It seems that Kryo is currently not compatible with JDK17. It just has a new release [kryo-5.4.0](https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-5.4.0) with some improvements compatibility with JDK 17+
Team please update Kryo dependency to make Redisson compatibility with JDK 17+

**Redisson version**
3.19.3

**Comment by mrniko** [comment]
it's already done

**Comment by quangdanh** [comment]
Thank you. I'm looking forward a new release.

**Comment by mrniko** [comment]
Has been fixed since 3.19.1 version
