### ISSUE TITLE
the best practice for unlock redisson's lock should be  isHeldByCurrentThread!

### ISSUE THREAD

**Issue by cxyxd** [redisson/redisson#4878]
the best practice for unlock redisson's lock should be  isHeldByCurrentThread!

just use lock.isLocked() will meet some error, please see #4876 

but at https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers
the example code is still lock.isLocked()

please consider my suggestion

**Comment by mrniko** [comment]
> the best practice for unlock redisson's lock should be isHeldByCurrentThread!

That's correct in your case.

> the example code is still lock.isLocked()

Can you point out where?

**Comment by cxyxd** [comment]
so sorry，i can not find lock.isLocked()  at https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers。 Maybe I was wrong。

but， now I still have some questions。
jest as following code（it comes from https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers ）
before you unlock the redisson lock,why didn't you check the status of the lock？may be at some case，this thread try to unlock the  redisson lock in 12 second（just over 10 second!）
```

RLock lock = redisson.getLock("myLock");

// traditional lock method
lock.lock();

// or acquire lock and automatically unlock it after 10 seconds
lock.lock(10, TimeUnit.SECONDS);

// or wait for lock aquisition up to 100 seconds 
// and automatically unlock it after 10 seconds
boolean res = lock.tryLock(100, 10, TimeUnit.SECONDS);
if (res) {
   try {
     ...
   } finally {
       lock.unlock();
   }
}
```

so i suggest fix the example code ,just as  following :

```

RLock lock = redisson.getLock("myLock");

// traditional lock method
lock.lock();

// or acquire lock and automatically unlock it after 10 seconds
lock.lock(10, TimeUnit.SECONDS);

// or wait for lock aquisition up to 100 seconds 
// and automatically unlock it after 10 seconds
boolean res = lock.tryLock(100, 10, TimeUnit.SECONDS);
if (res) {
   try {
     ...
   } finally {
      if (lock.isHeldByCurrentThread()){
         lock.unlock();
      }
       
   }
}
```

**Comment by mrniko** [comment]
You need to make sure that leaseTime is enough to execute the wrapped logic. Otherwise there is no reason to use lock.

**Comment by JohnNt97** [comment]
I dont think so. Because the method "unlock" has checked if the lock it will unlock belongs to the current thread. And, the code above, `isHeldByCurrentThread` and `unlock` are not atomical.
