### ISSUE TITLE
What is the difference between Remote Service and Distributed executor service?

### ISSUE THREAD

**Issue by 1Mark** [redisson/redisson#4880]
What is the difference between Remote Service and Distributed executor service from the eyes of someone that just wants  job processing with retries?

Remote service worked great but I couldn't see how to enable retries?

E.g like this image
![image](https://user-images.githubusercontent.com/15360245/220317072-09a28d55-8002-4178-abfa-b07f50e3bd4e.png)

**Comment by mrniko** [comment]
Try ExecutorService. It has org.redisson.api.ExecutorOptions#taskRetryInterval option.
