### ISSUE TITLE
Switching from Redis 4 to 6, will Redisson have compatibility issues?

### ISSUE THREAD

**Issue by zhangyunbo1994** [redisson/redisson#4890]
Hi team, 

We are going to upgrade Redis 4 to Redis 6. I would like to ask team if there will be compatibility issues between Redission and Redis 6 after upgrading 4 to 6. Or do you know of any known Redission incompatibilities due to Redis 6 upgrades?
According to redission documentation, Redission supports Redis 4 and 6. Does this mean that we don't need to modify any client code? 

Many thanks for your support!

**Comment by mrniko** [comment]
Hi,

Redisson is fully compatible with 3.x up to 7.0.x version. No code modification is needed.

**Comment by zhangyunbo1994** [comment]
Thank you!
