### ISSUE TITLE
Use JNI version (liblz4-java.so) of lz4-java and/or improve logging of lz4codec for Tomcat 9

### ISSUE THREAD

**Issue by ivanbaldo** [redisson/redisson#4895]
I was able to use the org.redisson.codec.LZ4Codec (the stream looks compressed and takes less traffic than with the default) but it doesn't seem to use the JNI implementation provided by liblz4-java.so since it isn't mapped in the Tomcat 9 process.

That implementation is 33% faster at compression so it would be nice to make sure that it is using it.

The Redisson + Tomcat logs don't show any error or information regarding the lz4codec and which implementation it is using.

On RockyLinux 8 tried to put the liblz4-java.so in /usr/local/lib64, /usr/lib64 and in the same place as the Redisson JAR's, run ldconfig, disabled SELinux, etc.

Thanks!!!

**Comment by mrniko** [comment]
Thanks for pointing out.

I updated dependency to lz4-java 1.8.0
