### ISSUE TITLE
The reason  for linux nofiles leak

### ISSUE THREAD

**Issue by tubei** [redisson/redisson#4898]
I have a project that use old redission version 3.5.0，In the project i used redis sentinel mode, when i added redis slave node，the count of nofile increment and never reduced. There are a lot of anon pipe and eventpoll file descriptors.
I tested a lot of redission versions and find the minimum fix version is 3.5.5, but i read the changelog and can not find relevant code. Can anyone tell me the reason ？ I want to find relevant code.

project dependencies:
Spring-boot: 1.5.9
redisson: 3.5.0
OS: CentOS Linux release 7.9.2009

P.S.
when the nofile count incremented , there a lot of warning log:
o.r.c.SentinelConnectionManager          : Skipped slave up …… for master …… differs from current redis ……

**Comment by mrniko** [comment]
Sorry, can't help here
