### ISSUE TITLE
Invalid union and diff operations for ScoredSortedSet

### ISSUE THREAD

**Issue by trifolium-wang** [redisson/redisson#4900]
I couldn't use union or diff when I used the ScoredSortedSet provided by redission.
code:
`redissonClient.getScoredSortedSet(unionKey).union(RScoredSortedSet.Aggregate.MAX,
                                followUpNode.toArray(new String[0]));`
A unionKey collection is not created.

**Comment by trifolium-wang** [comment]
version: 3.17.7, redis version: 6.2.6

**Comment by trifolium-wang** [comment]
When tested, the reason is that NameMapper is used, but the key prefix is not automatically concatenated in functions such as diff and union. I don't understand if this is a bug or a feature

**Comment by mrniko** [comment]
Fixed! Thanks for report
