### ISSUE TITLE
Redis4 cluster, redisson RQueue poll  jedis lpush data , Occasional data loss

### ISSUE THREAD

**Issue by ljq-dmr** [redisson/redisson#4905]
<dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>3.16.1</version>
</dependency>

<dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>3.2.0</version>
</dependency>

**Comment by mrniko** [comment]
Redisson 3.16.1 has a connection leak issue. Please update to the latest version
