### ISSUE TITLE
Command still hasn't been written into connection! Increase nettyThreads and/or retryIntervalNode source:

### ISSUE THREAD

**Issue by coolbtoc** [redisson/redisson#4906]
Hi，i used redisson-spring-boot-starter in springboot 2.1.12-release with redis Sentinel mode ,1 master and 2 slave. The following error log is encountered while the program is running.  how can i fix this? thanks !
my configration like this:
spring:
  redis:
    host: 192.168.11.11
    port: 6378
    password:  redis
    sentinel:
      master: mymaster
      nodes: 192.168.11.11:26379, 192.168.11.12:26379, 192.168.11.13:26379
    lettuce:
      pool:
        max-active: 32
        max-wait: 10000ms
        max-idle: 32
        min-idle: 0

org.springframework.dao.InvalidDataAccessApiUsageException: Command still hasn't been written into connection! Increase nettyThreads and/or retryIntervalNode source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:0:queue:64, freezed=false, freezeReason=null, client=[addr=redis://192.168.21.11:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@2115931524 [redisClient=[addr=redis://192.168.21.12:6379], channel=[id: 0x64f5fb71, L:/172.18.0.2:52154 - R:192.168.21.12/192.168.21.12:6379], currentCommand=null], command: (HGET), params: [[53, 69, 56, 57, 53, 48, 48, 51, 45, 57, ...], [54, 69, 54, 55, 52, 68, 53, 69, 45, 48, ...]] after 3 retry attempts; nested exception is org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryIntervalNode source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=1, freeConnectionsCounter=value:0:queue:64, freezed=false, freezeReason=null, client=[addr=redis://192.168.21.11:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@2115931524 [redisClient=[addr=redis://192.168.21.12:6379], channel=[id: 0x64f5fb71, L:/172.18.0.2:52154 - R:192.168.21.12/192.168.21.12:6379], currentCommand=null], command: (HGET), params: [[53, 69, 56, 57, 53, 48, 48, 51, 45, 57, ...], [54, 69, 54, 55, 52, 68, 53, 69, 45, 48, ...]] after 3 retry attempts
        at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)
        at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:224)
        at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:219)
        at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:449)

Ps：the version of redis is 5.0.8
Thanks

**Comment by mrniko** [comment]
Did you try to increase nettyThreads?

**Comment by coolbtoc** [comment]
sorry , 1 don't know how to config  the nettyThreads of Sentinel mode.
it like follow config?
spring:
  redis:
    nettyThreads: 100

**Comment by coolbtoc** [comment]
some body help me ,thanks

**Comment by mrniko** [comment]
> 1 don't know how to config the nettyThreads of Sentinel mode.
it like follow config?

common spring boot settings don't allow to do this. You need to either use Redisson config file or Redisson settings. Examples are here https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter
