### ISSUE TITLE
Retry a different replica if one is unavailable

### ISSUE THREAD

**Issue by ofir-popowski** [redisson/redisson#4910]
I was wondering if it is possible to make retry attempts perform a round robin between different replicas if one of them is unavailable.

I'm using AWS ElastiCache (no cluster mode), 1 master with 3 replicas. Our configuration uses replicated mode, and when setting it up we're adding 2 node addresses: one for the primary endpoint, and one for the reader endpoing `addNodeAddress("master.REDACTED.cache.amazonaws.com:6379", "replica.REDACTED.cache.amazonaws.com:6379")`.

A couple of days ago, we performed migration of the cluster, upgrading the engine version in our live production environment. We expected some connection issues when fetching data from the cluster, but assumed that because the client is configured with retry attempts, that in case a replica was unavailable, it would try a different one. This did not work, and quite a lot of operations fails for us.

1. How should the replicated server configuration look like? Is it correct to use the primary and reader endpoints listed in the AWS ElastiCache dashboard? Or are we supposed to list all 4 nodes direct addresses instead? The documentation isn't clear on that
2. Is it possible to make retry attempts try a different replica for such cases? Sort of round robin between them in case of failure until all attempts are exhausted

**Comment by mrniko** [comment]
You need to specify all slave nodes in replicated configuration. Don't use "replica.REDACTED.cache.amazonaws.com" hostname. since it resolved only a single slave IP address
