### ISSUE TITLE
Getting this Exception in AWS java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()Z

### ISSUE THREAD

**Issue by sathishkumars-nd** [redisson/redisson#4911]
We are trying to upgrade redisson version from 3.10.0 to 3.19.1
Elasticcache engine version as 5.0.6
Netty version : 4.1.88.Final (Latest Stable)
Getting below error in the logs. Please help me whats the issue here ?

[redis-exception.txt](https://github.com/redisson/redisson/files/10917241/redis-exception.txt)

**Comment by mrniko** [comment]
Make sure you did it properly and there are no two different netty versions in classpath.
