### ISSUE TITLE
RPromise and Redisson Promise alternative in latest version

### ISSUE THREAD

**Issue by Dev-Shubham17** [redisson/redisson#4915]
Hi,
We are using Redisson Client version 3.17.0 currently and planning to upgarde to 3.19.1.
We are using **RedissonPromise** and **RPromise** class's **tryFailure(Throwable)** and **trySuccess(T)** function, and which looks like is not available in latest versions.

What could be the alternative for using its functionalities?

Thanks!!

**Comment by mrniko** [comment]
Use `java.util.concurrent.CompletableFuture` instead

**Comment by dineshmadhwal** [comment]
We would also like to know how to replace PPromise usage in our code. We are trying to upgrade Redisson version from 3.10.2 to 3.22.0, but we can't find this Rpromise class in this new version. So, the code written using 3.10.2 is throwing error as its not able to find this class. @mrniko. Can you please help to let us know what alternative we can use and how to use it? 

It would be great if you can help to point out to any resources mentioning this transition as I can't seem to find anything regarding the removal of this class. I can see that this class was removed in 3.17.2 version, but the changelog doesn't mention it.

I would also like to know regarding the alternatives for  Node and RedisNodes classes. We are using these to perform the health check.

**Comment by mrniko** [comment]
@dineshmadhwal 

RRomise was an internal class. You need to use CompletableFuture object instead.

**Comment by dineshmadhwal** [comment]
@mrniko. Is there any resource or documentation I can refer to to make this change?

Also, how about the replacement for classes like Node and RedisNodes? These are also marked as deprecated?

**Comment by dineshmadhwal** [comment]
@mrniko . Can you please help us to clear this doubt?

We are stuck with this issue and cannot migrate to new version.

I have also attached the pics of the current code that is giving the issue after upgrading the version of Redisson. It would be great if you can have a look at it and suggest us how to proceed. 

![20231022_005914](https://github.com/redisson/redisson/assets/24225240/0055c391-7d14-424d-888f-574a5426b5ff)
![20231022_010009](https://github.com/redisson/redisson/assets/24225240/a3849e88-de1b-4d00-b330-5ec0fcaa7cff)
![20231022_010025](https://github.com/redisson/redisson/assets/24225240/6584ca07-69cb-4486-8eb9-5d9c669d207b)

**Comment by mrniko** [comment]
> @mrniko. Is there any resource or documentation I can refer to to make this change?
> 
> Also, how about the replacement for classes like Node and RedisNodes? These are also marked as deprecated?

Use `org.redisson.api.RedissonClient#getRedisNodes()` method instead.

**Comment by dineshmadhwal** [comment]
@mrniko . Thank you for replying! I understand that you might be busy, but it would be great if you can have a look at the code below and suggest us on how can we proceed with this. These are the errors we get in the class file after we change the Redisson version to 3.2022.0
