### ISSUE TITLE
Upgrading Redission causes org.redisson.client.RedisException

### ISSUE THREAD

**Issue by sathishkumars-nd** [redisson/redisson#4918]
New to redis. We are upgrading redisson version from 3.10.0 to 3.20.0
Netty from 4.1.56 to 4.1.89
Build failed org.redisson.client.RedisException.
Please let me know how to fix this issue. 
PS : Everything works fine if we use old versions

Logs : 
[redis-exception.txt](https://github.com/redisson/redisson/files/10957845/redis-exception.txt)

![image](https://user-images.githubusercontent.com/102959733/224723895-f2a3f26c-8776-49e5-937e-b05f58db7bb1.png)
![image](https://user-images.githubusercontent.com/102959733/224724013-853eb528-6de0-40c5-a171-93bc0f92a49e.png)

**Comment by mrniko** [comment]
data codec has been changed since 3.13.0 version. You need to specify JacksonJsonCodec explicitly or clear Redis database or migrate old data with a new codec Kryo5Codec.
