### ISSUE TITLE
Sharded Pub/Sub subscriptions only reach master nodes

### ISSUE THREAD

**Issue by marcelja** [redisson/redisson#4919]
We're running a few tests with sharded pub/sub. When using Redisson (with default cluster config) to subscribe topics/channels, the application seems to receive all messages from the master nodes. The replica nodes don't report outgoing messages.

Is this expected? The default subscriptionMode value is SLAVE https://github.com/redisson/redisson/wiki/2.-Configuration/#subscriptionmode

**Comment by mrniko** [comment]
pubsub messages are propagated to slave nodes from master.

**Comment by marcelja** [comment]
Yes, then Redisson should be able to subscribe the slave nodes, right? Apparently, it's not doing that in our tests.

**Comment by mrniko** [comment]
Can you share Redisson logs with `trace` logging level for `org.redisson` package?

**Comment by marcelja** [comment]
[trace.log](https://github.com/redisson/redisson/files/11404028/trace.log)
Yes. I have a local 3 shard cluster. 6380 is the master and 6384 the replica. As far as I can tell, Redisson gets the message for key `test.key` from 6380.

**Comment by marcelja** [comment]
But to be fair, Redis also redirects me to 6380 when using redis-cli to ssubscribe. Unless I'm on 6384

**Comment by mrniko** [comment]
Sorry, it's a mistake in the documentation. Thanks for pointing out
