### ISSUE TITLE
How to connect to Azure cache for Redis to avoid connection spikes.

### ISSUE THREAD

**Issue by zhangyunbo1994** [redisson/redisson#4920]
Hello team, I would like to ask a question about connecting to Azure redis.

Redission version: 3.16.8

We are using the Azure redis standard C1 pricing tier, the C1 pricing tier only allows a maximum of 1000 connections. And Azure Redis will be upgraded periodically, and a failover will occur during the upgrade. The failover will cause the Redission client to reconnect.

We use the C1 pricing tier. Before failover, the number of connections reaches about 960~970. Redis failover will cause Redission to reconnect, which may cause each connection pool of the client to reach the maximum number of connections, but the C1 pricing tier only allows a maximum of 1000 connections. In this way, when a failover occurs, Redis will be in an unhealthy state during failover, which may cause Unable to switch successfully.

Therefore, what means can we avoid such problems from happening? I know we can upgrade the pricing tier (like C2, C3) to solve this problem, high pricing tier can support more connections. But in the future, how many connections do we need to reserve, such as the C1 pricing tier, we need to reserve 500 connections to avoid problems caused by Redission reconnection spikes.

Thanks!

**Comment by zhangyunbo1994** [comment]
Another information, I known Redission connection work on a pool, so for Redission connection pool, we used default configuration.
https://github.com/redisson/redisson/wiki/2.-Configuration/#262-single-instance-yaml-config-format

**Comment by mrniko** [comment]
I think it's connected to this issue https://github.com/redisson/redisson/issues/4716#issuecomment-1344272648

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.20.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11108425/redisson-3.20.2-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Updated.

[redisson-3.20.2-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11109623/redisson-3.20.2-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4716

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4716

**Comment by zhangyunbo1994** [comment]
Hi @mrniko 

Thanks for your quick fix, I try yo import to my project but report some errors:
![image](https://user-images.githubusercontent.com/44389598/232982417-20e3528a-b928-4366-b2cb-0b04d653d478.png)

DO you know why this happen?
