### ISSUE TITLE
Specifying read endpoint for clustered mode

### ISSUE THREAD

**Issue by formanojhr** [redisson/redisson#4923]
We are using elastic cache AWS clustered mode and we provide the config endpoint which AWS prodvides which allows for topology discovery. 
Main question, if we use the multi az read replica for elastic cluster and we have separate deployments of the service using redisson in two AZs **can we provide redisson config read endpoint url so that we can control which endpoint that redisson client directs its reads alone** ? (No writes)

**Comment by mrniko** [comment]
You can use [Multi cluster mode](https://github.com/redisson/redisson/wiki/2.-Configuration/#210-multi-cluster-mode)

**Comment by formanojhr** [comment]
@mrniko we use a single elastic cache cluster for our use case but share between two az deployments but AWS elastic cache for a single cluster provides read replicas with two az. So we want to configure read endpoint specific to app's az to talk to the read endpoint of the cluster in the specific az. So not multi cluster.

**Comment by mrniko** [comment]
Does cluster info

**Comment by mrniko** [comment]
Can you clarify if `cluster nodes` command reports read replicas with two az ?

**Comment by formanojhr** [comment]
Sounds good. @mrniko . Is there way to debug log? How to observe? thanks

**Comment by mrniko** [comment]
You need to set `trace` logging level for `org.redisson` package in your application.

**Comment by mrniko** [comment]
You need to set `trace` logging level for `org.redisson` package in your application.

**Comment by mrniko** [comment]
You can use [`org.redisson.connection.balancer.WeightedRoundRobinBalancer`](https://github.com/redisson/redisson/blob/5c8c5486ffa7a09c2608d85b29f8a71d30b9a12c/redisson/src/main/java/org/redisson/connection/balancer/WeightedRoundRobinBalancer.java#L36) defining weights per hostname. Hostnames will be supported in 3.23.5+ version.
