### ISSUE TITLE
why redisson doesn't support WATCH

### ISSUE THREAD

**Issue by serjsamoshkin** [redisson/redisson#4924]
I didn't find any article or discussions why redisson doesn't support WATCH as part of transaction. 
It seems to be organic part of transaction and should be faster then redlock (if I'm not mistaken of course).
So just out of curiosity why it's not implemented in RedissonClient, but implemented in RedisConnection which is part of Spring boot redisson integration?
Thanks!

**Comment by mrniko** [comment]
redlock was deprecated in favor of fencedlock https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers/#810-fenced-lock

in term of performance it's better to acquire a lock instead / use lua-script / use RTransaction object
