### ISSUE TITLE
FairLock 死锁

### ISSUE THREAD

**Issue by AK9527AK** [redisson/redisson#4929]
断开连接后键xxxxxxx存活时间到了被redis清楚后redisson_lock_queue:{xxxxxxx}和redisson_lock_timeout:{xxxxxxx}两个键还存在会导致下次上锁时死锁或者无法上锁

**Comment by 18792709261** [comment]
FairLock上锁后正在执行业务逻辑，服务突然重启，再次启动无法获取锁，redisl锁的key失效但是队列还存在导致获取锁失败，
![1707289378146](https://github.com/redisson/redisson/assets/34979292/878c2d64-755d-4475-9c04-03e1032d27a2)
