### ISSUE TITLE
In mode cluster, Command 'scan' misses scanning data

### ISSUE THREAD

**Issue by dongmaxiang** [redisson/redisson#4932]
**Expected behavior**
Expect to scan all data

**Actual behavior**
misses scanning data

**Steps to reproduce or test case**
read_mode：Master and slave
master：scan 0 COUNT 1 --> 16384 --> to binary：100000000000000
slaver  ：scan 0 COUNT 1 --> 12288 --> to binary：10000000000000

> It is preliminarily speculated that the capacity expansion mechanisms of the master and slave nodes of Redis are different, resulting in different cursors returned by the master and slave scan commands
>> So when doing the scan command, can redisson disable master-slave switching?

**Redis version**
all

**Redisson version**
all

**Redisson configuration**

read_mode：Master and slave
Other normal

**Comment by mrniko** [comment]
Scanning data is always executed on the same node used at first invocation.

**Comment by dongmaxiang** [comment]
> 
I'm not at a good time, but I can remember the general content


In mode cluster，Three masters and three followers

Configuration file content：
read_mode：Master and slave

Then use spring data's scan command

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test case.

```java
        RedisRunner master1 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner master2 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner master3 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner slave1 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner slave2 = new RedisRunner().randomPort().randomDir().nosave();
        RedisRunner slave3 = new RedisRunner().randomPort().randomDir().nosave();


        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slave1)
                .addNode(master2, slave2)
                .addNode(master3, slave3);
        process = clusterRunner.run();

        Config config = new Config();
        config.useClusterServers()
                .setReadMode(ReadMode.MASTER_SLAVE)
        .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());

        redisson = Redisson.create(config);
        RedissonConnectionFactory factory = new RedissonConnectionFactory(redisson);
        RedissonConnection connection = factory.getConnection();

        Map<byte[], byte[]> map = new HashMap<>();
        for (int i = 0; i < 10000; i++) {
            map.put(("" + i).getBytes(StandardCharsets.UTF_8), ("" + i).getBytes(StandardCharsets.UTF_8));
        }
        connection.mSet(map);

        Cursor<byte[]> b = connection.scan(ScanOptions.scanOptions().build());
        int counter = 0;
        while (b.hasNext()) {
            b.next();
            counter++;
        }
        assertThat(counter).isEqualTo(map.size());
```

You can check the code. Redisson doesn't switch from master to slave. This issue might be cause by replication lag.
