### ISSUE TITLE
Redisson hibernate not reading codec data from config yaml

### ISSUE THREAD

**Issue by purti-rajpal** [redisson/redisson#4933]
We are trying to use redisson hibernate with the following gradle dependency:
'org.redisson:redisson-hibernate-53:3.16.8'

and below redisson config file:
{
  "clusterServersConfig": {
    "idleConnectionTimeout": 10000,
    "connectTimeout": 240000,
    "timeout": 180000,
    "retryAttempts": 3,
    "retryInterval": 1500,
    "failedSlaveReconnectionInterval": 3000,
    "failedSlaveCheckInterval": 60000,
    "subscriptionsPerConnection": 5,
    "clientName": "test",
    "subscriptionConnectionMinimumIdleSize": 1,
    "subscriptionConnectionPoolSize": 250,
    "slaveConnectionMinimumIdleSize": 24,
    "slaveConnectionPoolSize": 512,
    "masterConnectionMinimumIdleSize": 24,
    "masterConnectionPoolSize": 512,
    "readMode": "SLAVE",
    "subscriptionMode": "SLAVE",
     "scanInterval": 1000,
    "pingConnectionInterval": 30000
  },
  "threads": 16,
  "nettyThreads": 32,
    "codec": !<org.redisson.codec.Kryo5Codec> {}
  "transportMode": "NIO"
}

We are getting below error and application fails to start:

com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.redisson.client.codec.Codec]: missing type id property 'class' (for POJO property 'codec')

Not sure why is it not reading codec from config file. Please help.

**Comment by mrniko** [comment]
Can you share the full stacktrace?

**Comment by Maktoublwx** [comment]
I have the same problem, have you solved it
