### ISSUE TITLE
Should the default-update-timestamps-region be cleared/deleted when evictAllRegions is called on the Hibernate Cache

### ISSUE THREAD

**Issue by alewis001** [redisson/redisson#4937]
Hi,

I have a Spring application that is using Hibernate with Redisson backed L2 Cache. The application is running in Kubernetes, and in particular it's possible for the duration of a rollout that there are mixed versions of cached Entities; the new version of the application being deployed replaces each "old" pod in turn.

To avoid "deserialization" issues when reading Entities from the cache, I have experimented with using a region prefix (`hibernate.cache.region_prefix`) that uses a "dynamic" value that is generated at build time of the application. As such, when a new deployment begins, that new deployment starts with fresh cache/entity regions as they now have a different prefix to the "old" pods/app instances.

However, in this rollout process, the "old" regions need to be cleaned up in order to avoid a leak in Redis. The simplest approach I've tried is to call `evictAllRegions` on the Hibernate Cache to clear up all the cache regions on application shutdown. I realise that remaining "old" instances would keep repopulating the cache until the last pod shuts down.

In this process, `evictAllRegions` appears to be clearing everything _except_ the `default-update-timestamps-region` which, in my case is called `<prefix>.default-update-timestamps-region` in Redis.

My question is, should I expect `evictAllRegions` to also clear/delete out the `default-update-timestamps-region` entry in Redis?

Thanks for any help you may be able to provide.

Cheers,
Alex

**Comment by mrniko** [comment]
you can look at org.hibernate.Cache#evictAllRegions() implemetation. It doesn't clear timestamps region.

You can clear like this sessionFactory.getCache().getTimestampsCache().clear();

**Comment by alewis001** [comment]
@mrniko Apologies if I'm missing something but there isn't a `getTimestampsCache` method on `org.hibernate.Cache`, which is the class returned by `org.hibernate.SessionFactory`. That method does exist on `org.hibernate.cache.spi.CacheImplementor` which appears to be on the SPI interface between Hibernate and Redisson. 

I've tried going through the Hibernate/Redisson code but I can't find a way to access the TimestampsCache as an Application. Am I missing something? 

If this is now more of a question for Hibernate rather than Redisson, then no problem I can go there instead but, thank you for your help regardless.

**Comment by mrniko** [comment]
> @mrniko Apologies if I'm missing something but there isn't a getTimestampsCache method on org.hibernate.Cache, which is the class returned by org.hibernate.SessionFactory. That method does exist on org.hibernate.cache.spi.CacheImplementor which appears to be on the SPI interface between Hibernate and Redisson.

I thought you use Hibernate 5.3 version and higher. Can you update Hibernate?

**Comment by alewis001** [comment]
I'm using Hibernate 5.6.9 (`hibernate-core-5.6.9.Final.jar`).

**Comment by alewis001** [comment]
There doesn't appear to be a way to access `SessionFactoryImplementor` or, at least, not on Hibermate's public api. `SessionFactoryImplementor` is part of the SPI API (`org.hibernate.engine.spi`) and so it isn't on the public API exposed to clients.

**Comment by alewis001** [comment]
I had originally thought that evicting the Query region, either directly via `Cache#evictDefaultQueryRegion` or via `evictAllRegions` would have evicted both the query region itself and the associated timestamp region but that doesn't appear to happen.

**Comment by alewis001** [comment]
I can see in `org.hibernate.cache.internal.QueryResultsCacheImpl` that calling `clear` (there's a default implementation on the interface it implements which calls `getRegion().clear()`) which ends up clearing the main region but it does nothing with the Timestamps Cache that `QueryResultsCacheImpl` also has a reference to.

This might be a question for Hibernate as Redisson is doing all the necessary things according to the SPI. I don't want to take up too much of your time.
