### ISSUE TITLE
org.redisson.client.codec.JsonJacksonMapCodec not found

### ISSUE THREAD

**Issue by CollectBugs** [redisson/redisson#4942]
question ：
Introduce redisson dependency in java project through mavan method，result is org.redisson.client.codec.JsonJacksonMapCodec not found

```
<dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.20.1</version>
        </dependency>
```

![image](https://user-images.githubusercontent.com/32507511/228888668-57311677-952a-4da5-8c64-6cdadb07b41f.png)

**Comment by mrniko** [comment]
it was replaced with TypedJsonJacksonCodec

**Comment by CollectBugs** [comment]
thank you

**Comment by CollectBugs** [comment]
> it was replaced with TypedJsonJacksonCodec

thank you
