### ISSUE TITLE
Is problem the kv service does not support pub/sub and use  redisson to lock a scheduled task?

### ISSUE THREAD

**Issue by Jeannia** [redisson/redisson#4943]
our self-bulit kv service does not support pub/sub command. I have a service use redssion lock in a scheduled task (with @schedule in Spring) and our service is deployed with a cluster, we found that there are more than 1 service will run the task after just deployment,and after a period of time,there is only one will run the task and always the same one,  and the log shows :
org.redisson.client.RedisException: Unexpected exception while processing command
at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:257)
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:102)
at org.redisson.command.CommandAsyncService.evalWrite(CommandAsyncService.java:84)

I want to know it is because pub/sub failed?

**Comment by mrniko** [comment]
`RedissonClient.getLock()` wasn't tested without properly working pubsub command.

In this case you need to use `Redisson.getSpinLock()`
