### ISSUE TITLE
equivalent of Spring's `computePrefixWith` in Redisson??

### ISSUE THREAD

**Issue by andreas-ajaib** [redisson/redisson#4945]
Is there any equivalent of Spring cache's `computePrefixWith` in Redisson?
```java
RedisCacheConfiguration.defaultCacheConfig()
    .computePrefixWith(cacheKeyPrefix);
```

**Comment by mrniko** [comment]
NameMapper - https://github.com/redisson/redisson/wiki/2.-Configuration#namemapper
