### ISSUE TITLE
        localizedMessage: Node for slot: 4058 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings. 

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#4948]
This error popups during the application of the aws security update on our cluster elasticache redis.
It is a one shard, 1 writer, 2 read replica cluster,
the error popuped during the update of one of the read replica, the writer node hasn't been touch yet.
It is a one shard cluster so all the slot are in the only shard.

**Expected behavior**
no error

a few error like :
Node for slot: 4058 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings. 

**Steps to reproduce or test case**

**Redis version**
6.2.6

**Redisson version**
3.20.1

**Redisson configuration**
clusterServersConfig:

  # If pooled connection not used for a timeout time and current connections amount bigger
  # than minimum idle connections pool size, then it will closed and removed from pool.
  # Value in milliseconds.
  # Default value: 10000
  idleConnectionTimeout: 120000

  # Timeout in milliseconds during connecting to any Redis server.
  # Default value: 10000
  connectTimeout: 10000

  # Redis server response timeout in milliseconds.
  # Starts to countdown when Redis command was succesfully sent.
  # Default value: 3000
  timeout: 3000

  # Error will be thrown if Redis command can't be sended to Redis server after retryAttempts.
  # But if it sent succesfully then timeout will be started.
  # Default value: 3
  retryAttempts: 1

  # Time interval in milliseconds after which another one attempt
  # to send Redis command will be executed.
  # Default value: 1500
  retryInterval: 750

  # Interval of Redis Slave reconnection attempt when it was
  # excluded from internal list of available servers.
  # On each timeout event Redisson tries to connect to disconnected Redis server.
  # Value in milliseconds.
  # Default value: 3000
  failedSlaveReconnectionInterval: 3000

  # Redis Slave node failing to execute commands is excluded from the internal
  # list of available nodes when the time interval from the moment of
  # first Redis command execution failure on this server reaches defined value.
  # Value in milliseconds.
  # Default value: 60000
  failedSlaveCheckInterval: 60000

  # Password for Redis server authentication.
  password: ${REDIS_DEDUPE_PASSWORD}

  # Subscriptions per subscribe connection limit.
  # Used by RTopic, RPatternTopic, RLock, RSemaphore, RCountDownLatch,
  # RClusteredLocalCachedMap, RClusteredLocalCachedMapCache, RLocalCachedMap,
  # RLocalCachedMapCache objects and Hibernate READ_WRITE cache strategy.
  # Default Value: 5
  subscriptionsPerConnection: 5

  # Name of client connection.
  # Default value: null
  clientName: null

  # Сonnection load balancer for multiple Redis servers. Available implementations:
  # org.redisson.connection.balancer.WeightedRoundRobinBalancer
  # org.redisson.connection.balancer.RoundRobinLoadBalancer
  # org.redisson.connection.balancer.RandomLoadBalancer
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}

  # Redis 'slave' node minimum idle subscription (pub/sub) connection amount for each slave node
  # Default value: 1
  subscriptionConnectionMinimumIdleSize: 1

  # Redis 'slave' node maximum subscription (pub/sub) connection pool size for each slave node
  # Default value: 50
  subscriptionConnectionPoolSize: 50

  # Redis 'slave' node minimum idle connection amount for each slave node
  # Default value: 24
  slaveConnectionMinimumIdleSize: 24

  # Redis 'slave' node maximum connection amount for each slave node
  # Default value: 64
  slaveConnectionPoolSize: 64

  # Redis 'master' node minimum idle connection amount for each slave node.
  # Redisson idle connections are remain for elected slave as master.
  # Because this node remains in slave connection pool but in non-active state.
  # These connections are preserved for case when your cluster lost all slaves.
  # In this case master used as slave and idle-connections become in use.
  # Default value: 24
  masterConnectionMinimumIdleSize: 64

  # Redis 'master' node maximum connection pool size
  # Default value: 64
  masterConnectionPoolSize: 64

  # Set node type used for read operation. Available values:
  # SLAVE - Read from slave nodes, uses MASTER if no SLAVES are available.
  # MASTER - Read from master node,
  # MASTER_SLAVE - Read from master and slave nodes
  # Default value: SLAVE
  readMode: "SLAVE"

  # Set node type used for subscription operation. Available values:
  # SLAVE - Subscribe to slave nodes,
  # MASTER - Subscribe to master node
  # Default value: SLAVE
  subscriptionMode: "SLAVE"

  # Add Redis cluster node address in host:port format. Multiple nodes could be added at once.
  # At least one node from Redis Cluster should be specified.
  # Redisson discovers automatically cluster topology.
  # Use rediss:// protocol for SSL connection.
  nodeAddresses:
    - "rediss://cluster....cache.amazonaws.com:6379"

  # Redis cluster scan interval in milliseconds.
  # Default value: 1000
  scanInterval: 1000

  # This setting allows to detect and reconnect broken connections using PING command.
  # PING command sending interval defined in milliseconds.
  # Useful in cases when netty lib doesn't invoke channelInactive method for closed connections.
  # Set 0 to disable.
  # Default value: 30000
  pingConnectionInterval: 30000

  # Enables TCP keepAlive for connection.
  # Default value: false
  keepAlive: false

  # Enables TCP noDelay for connection.
  # Default value: false
  tcpNoDelay: false

# Threads amount shared across all listeners of RTopic object,
# invocation handlers of RRemoteService, RTopic object and RExecutorService tasks.
# Default value: 16
threads: 16

# Threads amount shared between all internal redis clients used by Redisson.
# Netty threads used in Redis response decoding and command sending.
# Default value: 32
nettyThreads: 64

# Redis data codec. Used during read and write Redis data.
# Default value: org.redisson.codec.Kryo5Codec
codec: !<org.redisson.codec.MarshallingCodec> {}

# Available values:
# TransportMode.NIO,
# TransportMode.EPOLL - requires netty-transport-native-epoll lib in classpath
# TransportMode.KQUEUE - requires netty-transport-native-kqueue lib in classpath
# Default value: TransportMode.NIO
transportMode: "NIO"

**Comment by mrniko** [comment]
This error may arise during failover. You can increase `retryAttempts` and `retryInterval` to resolve it.
