### ISSUE TITLE
We are experiencing the error what seems like network related errors using the 3.12.4 version of redisson.

### ISSUE THREAD

**Issue by wangbo456** [redisson/redisson#4953]
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:49:queue:0, freeConnectionsAmount=23, freeConnectionsCounter=value:37:queue:0, freezed=false, freezeReason=null, client=[addr=redis://:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1389282959 [redisClient=[addr=redis://:6379], channel=[id: 0x082c6960, L:/1:57832 - R:/1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@626c5845(failure: java.util.concurrent.CancellationException)], command=(GET), params=[area:list_2], codec=org.redisson.codec.FstCodec]], command: (GET), params: [arSAAea:list_1] after 3 retry attempts

**Comment by mrniko** [comment]
Please refer to this answer https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by wangbo456** [comment]
After reviewing the problem list, there is no available information

**Comment by wangbo456** [comment]
Or is it related to the version
