### ISSUE TITLE
Why RSetCache extends Set instead of RSet

### ISSUE THREAD

**Issue by timnick-snow** [redisson/redisson#4954]
`RMapCache` extends `RMap`
```java
public interface RMapCache<K, V> extends RMap<K, V>, RMapCacheAsync<K, V>, RDestroyable {}
```

but `RSetCache` extends `Set`
```java
public interface RSetCache<V> extends Set<V>, RExpirable, RSetCacheAsync<V>, RDestroyable {}
```

RMapCache is an enhancement to RMap that allows you to set ttl for each entry, and it inherits all the methods of RMap.
Why this behavior is not consistent in RSetCache ?

When I use RSetCache, I will not be able to use some ops like diff, union, intersection.

**Comment by mrniko** [comment]
Done
