### ISSUE TITLE
Is RBlockingDeque.take() exactly-once delivery?

### ISSUE THREAD

**Issue by marclallen** [redisson/redisson#4957]
Sorry for bothering you but I just can't seem to find any documentation on this.

I have a three-node Redis cluster and about 20 independent services, all pulling from the same queue.  It appears that, occasionally, multiple of these services pull the exact same message at virtually the exact same time, using the .take() routine. There are multiple providers as well, but I've pretty much confirmed that the messages are not being deposited twice to the queue.  

I just want to verify whether this is something that can happen or not.

If it is, are there any tips (aside from moving away from the queue system and into streams) on how to stop it or is the queue system more of an at-least-once system?

Thanks for your time.

**Comment by mrniko** [comment]
> I just want to verify whether this is something that can happen or not.

That's not possible. take() is exactly-once delivery method
