### ISSUE TITLE
Maximum connections from redisson client

### ISSUE THREAD

**Issue by Deeksha411** [redisson/redisson#4969]
Error: "message" -> Unable to acquire connection! Increase connection pool size and/or retryInterval settings 

On analysis, we found that we were facing this issue because of too many connections/connection bombardments to redis from our applications. Due to this reason, redis was not able to recover.

We already have the following configurations at our end 
masterConnectionPoolSize: 10
slaveConnectionPoolSize: 10
failedSlaveReconnectionInterval : 3 seconds.

However, we could see application connections as high as 450 in some cases. Is there some way to limit the maximum number of connections through Redisson clients,?

**Comment by mrniko** [comment]
Which Redisson version?

**Comment by Deeksha411** [comment]
@mrniko  we are using 3.14.0

**Comment by mrniko** [comment]
is there a way to reproduce it?

**Comment by mrniko** [comment]
3.14.1, 3.15.3 versions has fixes for possible connection leaks issues.

**Comment by Deeksha411** [comment]
Steps to reproduce : 

Redis Infra: using sentinel mode
1 master, 2 slaves

Applications:  2 services with 20 pods(Kubernetes) each

1. Load tests using relatively higher payloads (~150-200KB),  we are performing PUT and GET at almost ~5k/s and 6k/s respectively.
2. After running this load for almost ~20-25 minutes, we restarted one of the slave nodes.
3. Once the slave node is out of sync, we observe that recv-q is quite high at the redis server due to connection bombardment.

Note: We have also observed that this issue only occurs when there are more than 20-25 pods running. When the number of pods is 2-3, the redis slave server recovers and no issues are found on our application level. 

Dug deeper and found that each pod had more connections than the ones defined in our properties.

**Comment by mrniko** [comment]
Can you try to reproduce it with the latest version?

**Comment by Deeksha411** [comment]
Sure, let us quickly run few tests and get back

**Comment by mrniko** [comment]
> we observe that recv-q is quite high at the redis server due to connection bombardment

It's connected to this issue https://github.com/redisson/redisson/issues/4716 it's not released yet.

You can also try the build from master branch.

**Comment by Deeksha411** [comment]
Issue is not reproducible after upgrade, closing the issue.
