### ISSUE TITLE
Redis Cluster with password do not set TTL for MapCache

### ISSUE THREAD

**Issue by mohsentaheris** [redisson/redisson#4970]
I had a REDIS cluster without password and everything worked perfectly, after security force me to set a password problems shows one by one, my new problem that I can't find any solution is that setting TTL for MapCache doe's not affected, but TTL for Bucket sets correctly.
I have redisson version 3.20.1 and Redis version 7.0: this is a example code:

    package org.example.test;

    import org.redisson.Redisson;
    import org.redisson.api.RedissonClient;
    import org.redisson.config.Config;

    import java.util.ArrayList;
    import java.util.List;
    import java.util.concurrent.TimeUnit;

    public class redis {
        public static RedissonClient redisson;

        static {
            Config redisConfig = new Config();
            List<String> redisServers = new ArrayList<>();
            redisServers.add("redis://192.168.3.53:6379");
            redisServers.add("redis://192.168.3.54:6379");
            redisServers.add("redis://192.168.3.55:6379");

            redisConfig.useClusterServers().setNodeAddresses(redisServers);
           redisConfig.useClusterServers().setPassword("myPassword");

           redisson = Redisson.create(redisConfig);
        }

       public static void main(String[] args) {

           redisson.getBucket("BucketKey").set("BucketValue", 1, TimeUnit.MINUTES);
           redisson.getMapCache("MyMapTopic").put("MyMapKey", "MyMapValue", 1, TimeUnit.MINUTES);
           System.exit(0);
        }

    }

I check TTL with Another Redis Desktop Manager the "BucketKey" TTL is 60 but "MyMapTopic" is -1

**Comment by mrniko** [comment]
for RMapCache object ttl param is applied per map entry and not a whole object as it done for RBucket

**Comment by mohsentaheris** [comment]
I find the way to set TTL for whole RMapCache:

    RMapCache<String, String> map = redisson.getMapCache(topic, StringCodec.INSTANCE);
    map.expireAsync(Instant.now().plus(RedisExpire, ChronoUnit.MINUTES));
