### ISSUE TITLE
Why does Redisson's lock not support cross-thread addition and unlocking?

### ISSUE THREAD

**Issue by livelyRyan** [redisson/redisson#4975]
Among Redisson's various distributed locks, why not support the case of A thread locking and B thread unlocking, and what are the considerations?

**Comment by mrniko** [comment]
Java lock implementation doesn't allow this. However you can RLock.unlockAsync(threadId) for this case. ThreadId here is the id of the thread owner. Also you can use RSemaphore or RPermitExpirableSemaphore objects with a single permit.
