### ISSUE TITLE
Add support for Micrometer's new Observation API

### ISSUE THREAD

**Issue by marcingrzejszczak** [redisson/redisson#4976]
With [Micrometer](https://micrometer.io/) 1.10.0 (I'm a maintainer), a new API was released called the [Observation API](https://micrometer.io/docs/observation). It lets users instrument their components once and then get multiple benefits out of it e.g.: metrics, distributed tracing, (audit) logs, publishing arbitrary events, etc.

We also released [Micrometer Tracing](https://github.com/micrometer-metrics/tracing) (it's a new project) which is not a must but plays nicely with the Observation API and it can bridge calls to OpenTelemetry or OpenZipkin's Brave.

*Use cases*
The use cases are quite wide, the goal of the Observation API is to be able to cover a lot of the Observability needs of the users, for example:

* Users want metrics in their apps (they can use micrometer metrics or other libraries, e.g.: dropwizard-metrics)
* Users want distributed tracing in their apps (they can use Micrometer Tracing with Brave/OTel or other libraries)
* Users want both metrics and distributed tracing in their apps
* Users want to listen to and publish custom events in their applications and emit logs, write an audit DB, etc.

The implementation should be similar to the current usage of Micrometer Timer but instead of starting/stopping a Timer, we need to start/stop an Observation. See migration guide here: https://github.com/micrometer-metrics/micrometer/wiki/Migrating-to-new-1.10.0-Observation-API

**Comment by mrniko** [comment]
Thank you for suggestion! It's done https://github.com/redisson/redisson/wiki/16.-Observability#162-tracing

**Comment by marcingrzejszczak** [comment]
Hey, thanks for doing this! :) It seems from the wiki page that only micrometer tracing support was added. Are you planning to add Micrometer Observation support too? That would allow you to instrument your code only once and you would get both metrics and tracing (e.g. using Micrometer Tracing) support!

**Comment by mrniko** [comment]
It's implemented through Micrometer Observer. I'll correct the link to https://micrometer.io/docs/observation. Thanks for pointing out.

**Comment by marcingrzejszczak** [comment]
Oh fantastic! Great to hear that!
