### ISSUE TITLE
RlocalcacheMap Behaviour

### ISSUE THREAD

**Issue by amarendrar** [redisson/redisson#4980]
Hi, 
Could you please explain more on the LocalCachedMapOptions.StoreMode options(LOCALCACHE_REDIS,LOCALCACHE),

I have tried using these two options with multiple instance of JVMs(different pods). LOCALCACHE_REDIS mode is working for read, write, delete options from  multiple Jvms but with LOCALCACHE  write/read from multiple JVMs is not working.  

Could please also confirm that LOCALCACHE_REDIS always read from Redis or it look first in local JVM before fetching from Redis 

Below is code which I trying to write from one JVM and read from another JVM.

`   
 private LocalCachedMapOptions options = LocalCachedMapOptions.defaults()
            .cacheProvider(LocalCachedMapOptions.CacheProvider.REDISSON)
            .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.SOFT)
            .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.LOAD)
            .syncStrategy(LocalCachedMapOptions.SyncStrategy.INVALIDATE)
            .storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE_REDIS);
            `

    public String getLocalData(String key) {

        RLocalCachedMap localCachedMap =  redisson.getLocalCachedMap("Test-Appcache",options);

        localCachedMap.get(key);

        return (String) localCachedMap.get(key);

    }

    public String writeLocalData(String key) {

        RLocalCachedMap localCachedMap =  redisson.getLocalCachedMap("Test-Appcache",options);

        localCachedMap.put(key,key+"-value");

        return (String) localCachedMap.get(key);

    }

    public void deleteLocalData(String key) {

        RLocalCachedMap localCachedMap =  redisson.getLocalCachedMap("Test-Appcache",options);

        localCachedMap.remove(key);

    }
            `

**Comment by mrniko** [comment]
LOCALCACHE mode doesn't store data in Redis.
