### ISSUE TITLE
Is there a bug with concurrent lock failure in Redisson3.17.6？

### ISSUE THREAD

**Issue by yangkangquan123** [redisson/redisson#4982]
We used version 3.17.6 of Redisson in our project, and found that every day when concurrent locking occurs, one request will acquire the lock timeout, which feels like another request has not released the lock after acquiring it. Does anyone know the reason?

`RLock lock;
boolean lockSuccess = lock.tryLock(waitTime, LEASE_TIME, TimeUnit.MILLISECONDS);`

**Comment by yangkangquan123** [comment]
Another request returned success in a few milliseconds, and the code also released the lock in the finally code section. But the timeout request still cannot obtain the lock within 3 seconds

**Comment by mrniko** [comment]
Unable to reproduce it.
