### ISSUE TITLE
The dnsMonitoringInterval config didn't work sometimes

### ISSUE THREAD

**Issue by Foxssss** [redisson/redisson#4983]
I set the dnsMonitoringInterval to default value (5000ms) in my application and ran the application in different machines at the same time.
As I changed the dns config of the gateway for all application machines, I expect all application should connect to new ip address of redis after a while.
However, a few applications (like 3 out of 44) still used the old ip address of redis for a long time, why is that?

**Comment by Foxssss** [comment]
> Which Redisson version?

3.17.7
Was using Replicated mode with config as below. This problem didn't happen when I use Single instance mode.

`replicatedServersConfig:
  masterConnectionPoolSize: 64
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 20
  slaveConnectionMinimumIdleSize: 20
  readMode: "SLAVE"
  connectTimeout: 10000
  database: 15
  dnsMonitoringInterval: 5000
  idleConnectionTimeout: 10000
  timeout: 3000
  retryAttempts: 1
  retryInterval: 0
  pingConnectionInterval: 10000
  nodeAddresses:
    - "redis://xxx:6379"
    - "redis://xxx-slave:6379"
codec: !<org.redisson.codec.FstCodec> {}`

**Comment by Foxssss** [comment]
Well.. Sadly there wasn't any logs produced by redisson, nor did I add any logs about the ip address which the application was using. I may have to add some relative logs to make it more clear.

I was using Springboot 2.2.13, Redisson 3.17.7. Simply created a `redissonClient` as below.
```
    @Bean(name = "defaultRedissonClient", destroyMethod = "shutdown")
    @Primary
    public RedissonClient redissonClient() throws IOException {
        Config config = Config.fromYAML(ResourceUtils.getURL(getDefaultRedis().getRedissonConfig()));
        log.info("read redisson config for defaultRedissonClient : {}", config.toYAML());
        return Redisson.create(config);
    }
```

I find out that result by simply querying redis - some data was sitll written to the redis with old ip address.

**Comment by Foxssss** [comment]
Is there a way that I can mannually trigger dnsMonitoring?

**Comment by mrniko** [comment]
I need more logs to understand what is the issue is.
