### ISSUE TITLE
List of Redisson object and Redis commands it uses.

### ISSUE THREAD

**Issue by andreas-ajaib** [redisson/redisson#4989]
I want to see what Redis commands are used on each Redisson object. For example, `RRateLimiter` might use `INCR` & `EXPIRE`.

We want to see which Redisson objects are compatible or not. It is because our system uses https://github.com/twitter/twemproxy which does not support all Redis command. We have had bad experience when using Redisson's `RLockReactive` which apparently uses `SUBSCRIBE` command that is supported.

**Comment by mrniko** [comment]
Here is the Redis commands mapping list https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping

> We have had bad experience when using Redisson's RLockReactive which apparently uses SUBSCRIBE command that is supported. 

I suggest you to use `RedissonReactiveClient#getSpinLock()` which doesn't use pubsub.

**Comment by andreas-ajaib** [comment]
@mrniko any complete list for other objects? we also want to use other objects, but not sure if that's compatible.

**Comment by andreas-ajaib** [comment]
Hi @mrniko thank you for the suggestion and the list. However, I see it's still not solving my query. I see that the list only map Redis commands to Redisson objects and it doesn't contain all objects. For example, right now I want to use `RRateLimiter`, but I am unable to find what Redis commands it uses.

**Comment by mrniko** [comment]
@andreas-ajaib 

Unfortunately, there is no such commands map for lua scripts used by Redisson.
