### ISSUE TITLE
Cluster Mode and Replicated Servers

### ISSUE THREAD

**Issue by rrourke** [redisson/redisson#4991]
Currently we are using aws elastic cache in cluster mode as well has having additional replicas.
For example we have master1: node1, slave1: node2, slave3: node3.  Master2: node4, slave4: node5, slave 5: node6.
I noticed that using ```config.useClusterServers(config endpointaddress)``` it doesnt seem like the slaves are being read from, traffic is still being read from the master.

Is there something additional that needs to be done 
![image](https://user-images.githubusercontent.com/104800794/234331829-23944567-194a-4efb-9676-fbcd0c74bbaf.png)
![image](https://user-images.githubusercontent.com/104800794/234332195-1196dbad-6017-4782-bfae-53fa3ca73843.png)

From the above images you can see that requests for cache are going to the master and not the read replica and when the master changes the reads change to the new master.

**Comment by rrourke** [comment]
Additionally we are using RMapCache

**Comment by rrourke** [comment]
Is this related to https://github.com/redisson/redisson/issues/2165 but of note we are using redisCache.getAll(keySet) instead of get so I think we are dependent on this https://github.com/redisson/redisson/issues/3907

**Comment by mrniko** [comment]
Thanks for reminder. #3907 has been resolved.
