### ISSUE TITLE
Quarkus 3 compatibility

### ISSUE THREAD

**Issue by alexcatit** [redisson/redisson#4993]
Latest Redisson version 3.20.1 is not compatible with the latest Quarkus version 3.0.1.Final.

I think the problem is that RedissonClientProducer and maybe other classes still uses `javax.*` instead of `jakarta.*`
![image](https://user-images.githubusercontent.com/18626945/234630817-bff5f76a-2800-4ff2-bb1e-c13f3628bcc9.png)

**Comment by mrniko** [comment]
Done.

**Comment by yaroslav-skakun** [comment]
what are the compatible versions for quarkus and redisson?
