### ISSUE TITLE
RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host

### ISSUE THREAD

**Issue by vishaljain790** [redisson/redisson#4997]
We are using the Redisson Client 3.20.1 to connect to Elastic Cache Cluster. When we performed the service update on the elastic cache then we started to face following error at redisson side.

We have our elastic cache cluster within VPC, so AWS makes sure that DNS and it's IP of nodes will not be changed. 
https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ClientConfig.DNS.html

Error:
o.r.c.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: <Host> Disconnected hosts: <List of hosts>
	at o.r.c.p.ConnectionPool.get(ConnectionPool.java:211)
	at o.r.c.p.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at o.r.c.b.LoadBalancerManager.nextConnection(LoadBalancerManager.java:315)
	at o.r.c.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:583)
	at o.r.c.RedisExecutor.connectionReadOp(RedisExecutor.java:745)
	at o.r.c.RedisExecutor.getConnection(RedisExecutor.java:669)
	at o.r.c.RedisExecutor.execute(RedisExecutor.java:128)
	at o.r.c.RedisExecutor$1.run(RedisExecutor.java:317)
	at i.n.u.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at i.n.u.c.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at i.n.u.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at i.n.u.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at i.n.u.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at i.n.u.c.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by vishaljain790** [comment]
@mrniko The above document I shared talks about Memcached but we are using redis so IP might get changed. What configuration changes do you recommend so whenever there is IP changes then Redisson will resolve it automatically.

**Comment by vishaljain790** [comment]
I can see inside the logs that IP got changed from IP1 to IP2.

**Comment by vishaljain790** [comment]
I can see the below logs where Redisson was able to resolve the new IP but was not able to get the data when calling get a call to Redis.

o.r.c.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: point to new IP, Disconnected hosts: [point to older IP].
I assume the get call was using the same older connection not new one. So as per my understanding, the possible solution could be to catch this exception and rebuild the connection and use it again, or any way to set this up using the config itself?

**Comment by mrniko** [comment]
try to increase retryAttempts parameter to overcome errors during failover.

**Comment by vishaljain790** [comment]
@mrniko What is the default value for retryAttempts? And the exception we are facing says that connection was not available in the pool, so do you think increasing the retryattempts will resolve this connection issue?

**Comment by vishaljain790** [comment]
At our application side, we manually set up the master connection and slave ones. So I am little surprised how the retryAttempts will resolve this issue. We faced this issue for a long time, so if retry could help then it would have been resolved by the time but restarting the application helped us in this case. Curious to know from your side.

**Comment by vishaljain790** [comment]
@mrniko One question: If we use masterSlave config then does redisson automatically detect the change of primary or master node and underlying IP address of the node during the failover? Or should we go with replicated ones?

**Comment by mrniko** [comment]
> If we use masterSlave config then does redisson automatically detect the change of primary or master node and underlying IP address of the node during the failover?

It will detect ip change of master/slave nodes.

**Comment by vishaljain790** [comment]
@mrniko More concisely, The client library did react to the updated topology but after 5-7 mins and then later ran into connection pooling limit errors.

**Comment by mrniko** [comment]
I need logs with `trace` logging level for `org.redisson` package to understand the cause.

**Comment by musicallyvk** [comment]
@vishaljain790  hey brother did you solve this issue ?
agar ho gaya ho to bata do bhaai, mera task kaafi din se pending hai, same error tha
