### ISSUE TITLE
RedissonLocalCachedMap.clear sometimes doesn't clear immediately

### ISSUE THREAD

**Issue by saeidN** [redisson/redisson#5009]
I'm facing a problem where I clear redis but somehow it is not empty when I access it shortly after:

```
RedissonLocalCachedMap redis;
redis.clear();
redis.clearLocalCache();
List result = redis.get("key"); // result is usually empty but sometimes not empty
```
Does calling `.clear()` guarantee that subsequent call to `.get()` will return empty result?
If so, then what could be the cause of this issue?

**Comment by mrniko** [comment]
after `clearLocalCache` local cache should be cleared on all instances.

Unable to reproduce.

```java
        RLocalCachedMap<String, String> localCachedMap = redisson.getLocalCachedMap("udi-test",
                LocalCachedMapOptions.defaults());
        for (int i = 0; i < 100; i++) {
            localCachedMap.put("1", "2");
            localCachedMap.clear();
            localCachedMap.clearLocalCache();
            String v = localCachedMap.get("1");
            assertThat(v).isNull();
        }
```

**Comment by saeidN** [comment]
Thanks @mrniko 
Yes it's difficult to reproduce it locally. In our case it only occurs when multiple servers make calls to redis at same time.
Question: What will happen if one server calls `.clear()` and another server calls `.put("1", "2")` at same time. Is there some sort of locking to prevent them from running at same time. Or is the behavior undefined in this case?

**Comment by mrniko** [comment]
> What will happen if one server calls .clear() and another server calls .put("1", "2") at same time.

In this case of course you can get data inserted right after put method call since they aren't synchronized. You can try to use RLock object to avoid this.
