### ISSUE TITLE
Not recovering from ElastiCache Redis failover

### ISSUE THREAD

**Issue by marcelja** [redisson/redisson#5018]
**Expected behavior**

Successful requests after the failover

**Actual behavior**

I'm requesting hash records and subscribing/unsubscribing sharded pub/sub channels. When I trigger a manual failover, all new requests start to fail.

```
GOT SOMETHING FROM REDIS {1=2, 3=4}
GOT SOMETHING FROM REDIS {1=2, 3=4}
ERRR org.redisson.client.RedisClusterDownException: CLUSTERDOWN The cluster is down. channel: [id: 0x672e84dd, L:/10.0.91.149:45516 - R:10.0.12.108/10.0.12.108:6379] data: CommandData [promise=java.util.concurrent.CompletableFuture@4fbca7d6[Not completed, 1 dependents], command=(HMGET), params=[test.key, PooledUnsafeDirectByteBuf(ridx: 0, widx: 1, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 1, cap: 256)], codec=org.redisson.client.codec.StringCodec]
17:12:15.357 [redisson-netty-2-24] INFO  o.r.c.p.MasterPubSubConnectionPool - 5 connections initialized for 10.0.12.108/10.0.12.108:6379
17:12:15.756 [redisson-netty-2-1] INFO  o.r.c.pool.MasterConnectionPool - 24 connections initialized for 10.0.12.108/10.0.12.108:6379
ERRR org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 10.0.12.108/10.0.12.108:6379 Disconnected hosts: [10.0.12.108/10.0.12.108:6379]
ERRR org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 10.0.12.108/10.0.12.108:6379 Disconnected hosts: [10.0.12.108/10.0.12.108:6379]
ERRR org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 10.0.12.108/10.0.12.108:6379 Disconnected hosts: [10.0.12.108/10.0.12.108:6379]
```

**Steps to reproduce or test case**

I was not able to reproduce it in a local Redis cluster. Only when using ElastiCache. Without the sharded pub/sub listeners, it seems to reconnect without a problem.

```kotlin
    val redisMap: RMapAsync<String, String> = redisClient.redisson.getMap(key, StringCodec.INSTANCE)

    fun subscribe() {
        val future = redisMap.getAllAsync(setOf("1", "3"))
        future.whenComplete { result, exception ->
            if (exception == null) {
                println("GOT SOMETHING FROM REDIS $result")
                val topic: RShardedTopicAsync = redisClient.redisson.getShardedTopic(key, StringCodec.INSTANCE)
                topic.addListenerAsync(String::class.java) { _, message: String ->
                    println("GOT PUBSUB MESSAGE $message")
                }
            } else {
                println("ERRR $exception")
            }
        }
    }

    fun unsubscribe() {
        val topic: RShardedTopicAsync = redisClient.redisson.getShardedTopic(key, StringCodec.INSTANCE)
        topic.removeAllListenersAsync()
    }

    repeat(100) {
        subscribe()
        Thread.sleep(1000)
        unsubscribe()
        Thread.sleep(1000)
    }
```

**Redis version**

7.0.7 (AWS ElastiCache)

**Redisson version**

3.21.0

**Redisson configuration**

```
 redisConfig
                .useClusterServers()
                .addNodeAddress("rediss://$host:$port")
                .setPassword(password)
                .setSubscriptionsPerConnection(1000)
                .setSubscriptionConnectionPoolSize(10)
                .setSubscriptionConnectionMinimumIdleSize(5)
```

**Comment by mrniko** [comment]
Can you share Redisson logs with `trace` logging level for `org.redisson` package from application start moment?

**Comment by marcelja** [comment]
[trace.log](https://github.com/redisson/redisson/files/11403954/trace.log)

**Comment by mrniko** [comment]
Thanks for provided logs. I can't find the failover moment.

**Comment by mrniko** [comment]
Can you try to run attached version and share log output?

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11422087/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
[trace-redisson-3.21.1-SNAPSHOT.log](https://github.com/redisson/redisson/files/11422567/trace-redisson-3.21.1-SNAPSHOT.log)

**Comment by mrniko** [comment]
More logging added. Please try version below.

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11423124/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
[trace-redisson-3.21.1-SNAPSHOT-2.log](https://github.com/redisson/redisson/files/11423641/trace-redisson-3.21.1-SNAPSHOT-2.log)

**Comment by mrniko** [comment]
Even more logging has been added.

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11423948/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
[trace-redisson-3.21.1-SNAPSHOT-3.log](https://github.com/redisson/redisson/files/11428206/trace-redisson-3.21.1-SNAPSHOT-3.log)

**Comment by marcelja** [comment]
Yes, because I only printed the exception. I just changed it to `logger.error("ERRR", exception)`

[trace-redisson-3.21.1-SNAPSHOT-4.log](https://github.com/redisson/redisson/files/11430646/trace-redisson-3.21.1-SNAPSHOT-4.log)

**Comment by marcelja** [comment]
Yes, because I only printed the exception. I just changed it to `logger.error("ERRR", exception)`

[trace-redisson-3.21.1-SNAPSHOT-4.log](https://github.com/redisson/redisson/files/11430646/trace-redisson-3.21.1-SNAPSHOT-4.log)

**Comment by mrniko** [comment]
Please try a new version

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11430847/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
[trace-redisson-3.21.1-SNAPSHOT-5.log](https://github.com/redisson/redisson/files/11432937/trace-redisson-3.21.1-SNAPSHOT-5.log)

**Comment by mrniko** [comment]
new build - new logs added

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11433186/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
[trace-redisson-3.21.1-SNAPSHOT-6.log](https://github.com/redisson/redisson/files/11433401/trace-redisson-3.21.1-SNAPSHOT-6.log)

**Comment by mrniko** [comment]
more logs added. Seems localized the code block causing the issue - org.redisson.cluster.ClusterConnectionManager#addEntry

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11433581/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
[trace-redisson-3.21.1-SNAPSHOT-7.log](https://github.com/redisson/redisson/files/11439209/trace-redisson-3.21.1-SNAPSHOT-7.log)
I didn't capture for too long because it's quite a lot of logs.

Did you add more logs or also change something else? I just triggered the failover twice and it continued to work afterwards.

**Comment by mrniko** [comment]
the problem was in incorrect exception handling. But the problem is still exists. new logs added

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11441087/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
It should work now.

[redisson-3.21.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/11442806/redisson-3.21.1-SNAPSHOT.jar.zip)

**Comment by marcelja** [comment]
That's great! Here's the log file in case you want to take another look:
[trace-redisson-3.21.1-SNAPSHOT-9.log](https://github.com/redisson/redisson/files/11444022/trace-redisson-3.21.1-SNAPSHOT-9.log)

**Comment by marcelja** [comment]
Looks good
```
16:28:26.332 [redisson-netty-2-32] TRACE o.r.c.handler.CommandPubSubDecoder - reply: *3
$10
ssubscribe
$8
test.key
:1
, channel: [id: 0x9e4537a3, L:/10.0.60.137:35528 - R:10.0.12.108/10.0.12.108:6379], command: null
16:28:27.245 [redisson-netty-2-32] TRACE o.r.c.handler.CommandPubSubDecoder - reply: *3
$8
smessage
$8
test.key
$4
1234
, channel: [id: 0x9e4537a3, L:/10.0.60.137:35528 - R:10.0.12.108/10.0.12.108:6379], command: null
16:28:27.247 [redisson-3-6] INFO  redisson.reconnect.App - GOT PUBSUB MESSAGE 1234
```

**Comment by mrniko** [comment]
Fixed! Thanks for testing

**Comment by marcelja** [comment]
Nice, thank you too!
