### ISSUE TITLE
How to disable retries for batch

### ISSUE THREAD

**Issue by avcad** [redisson/redisson#5021]
Redisson 3.21.0

I am trying to execute a batch without retries:

BatchOptions.defaults().executionMode(ExecutionMode.IN_MEMORY).responseTimeout( timeout, TimeUnit.MILLISECONDS)
			.retryAttempts(0);

but if I set retry attempts to 0,  the system uses the default number of retries (3)
...currentCommand=null, usage=1], command: null, params: null after 3 retry attempts

I think the code is ignoring the option when set to 0:
        if (options.getRetryInterval() > 0) {
            this.retryInterval  = options.getRetryInterval();
        }

shouldn't 0 be allowed? Thanks!

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by avcad** [comment]
@mrniko  Thanks!
I haven't tested the code yet, but wouldn't it be needed to set BatchOptions
 private int retryAttempts = -1;
 for this to work? Otherwise I think it will always set the retries to 0 instead of using the configured/default value?

**Comment by mrniko** [comment]
@avcad 

You're right. Thanks for pointing out.
