### ISSUE TITLE
REDIS configuration and Sentinel configuration wrong Entry

### ISSUE THREAD

**Issue by sayseng** [redisson/redisson#5022]
In both redis nodes Redis configuration file is having replicaof entry.Ideally  only in replica node should have the replicaof entry.Thats why Sentinal configurations file is also having  wrong entry .
**sentinel known-replica netactMaster 2a00:8a00:4000:20c::1e:c5 6379
sentinel known-replica netactMaster 10.91.214.82 6379
sentinel known-replica netactMaster 2a00:8a00:4000:20c::1e:c6 6379
sentinel known-replica netactMaster 10.91.214.83 6379**

**Comment by mrniko** [comment]
What is the issue on Redisson side?
