### ISSUE TITLE
Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 0.

### ISSUE THREAD

**Issue by chencanping** [redisson/redisson#5023]
redis:
  redisson:
    server-mode: cluster_servers
    threads: 16               
    netty-threads: 32             
    common-config:
    common-cluster-config:
      master-connection-minimum-idle-size: 32
      master-connection-pool-size: 64
      slave-connection-minimum-idle-size: 32
      slave-connection-pool-size: 64
      subscription-connection-minimum-idle-size: 8
      subscription-connection-pool-size: 32

**Comment by chencanping** [comment]
version：3.17.3

**Comment by mrniko** [comment]
You need refer to this section https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception
