### ISSUE TITLE
Timeout value incorrect/?

### ISSUE THREAD

**Issue by nickcodefresh** [redisson/redisson#5026]
I've noticed the timeout calculation is https://github.com/redisson/redisson/blob/c851bafc70bb2cfa517488c47aec74daa48a8669/redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java#L266 (as well as other places in that class).

Should this be `int timeout = (config.getTimeout() + config.getRetryInterval()) * config.getRetryAttempts();`?

Event if not, I think the following is clearer  `int timeout = config.getTimeout() + (config.getRetryInterval() * config.getRetryAttempts());`.

**Comment by mrniko** [comment]
The value is correct.
