### ISSUE TITLE
Difference in storing data with RMapCache

### ISSUE THREAD

**Issue by yoda06** [redisson/redisson#5032]
Currently using the free version of Redisson 3.15.4.
My config is as follows:

```
Config config = new Config();
config.setCodec(new JsonJacksonCodec(jackson2ObjectMapperBuilder.build()));
config.useSingleServer().setAddress("rediss://host:port").setPassword(pwd);
```

I am using RLocalCacheMap and RMapCache for a different caches. 
I wanted to store the data as Json but I wanted to remove the reference to the package as "@class" field and so I used the TypedJsonJacksonCodec. 
This works perfectly fine while using with RLocalCacheMap and I am able to see the redis data as json key and value.

However when I use the same with RMapCache, I see additional hexadecimal data added in front of the data in the value. This then isn't read properly as per the type and I get an exception while reading or writing this data.

```
Caused by: java.lang.IllegalArgumentException: Cannot deserialize Class com.example.demo.CacheConfig$1 (of type local/anonymous) as a Bean
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.isPotentialBeanType(BeanDeserializerFactory.java:883)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
```

Example of data in Redis for RMapCache:
`\x00\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00\x00\x00\x00\x00"2023-05-11T22:30:18.961"`

In the above case, even though its just a string, the hex data is appended at the start.

Is this expected for RMapCache and how to overcome this and get the data without the Hex values.

**Comment by mrniko** [comment]
RMapCache stores extra data to track idle timeout of entry.

**Comment by yoda06** [comment]
Does this mean I will not be able to use it along with the TypedJsonJacksonCodec(CustomKey.class, CustomValue.class) or do I need to add some changes to make it work?

**Comment by mrniko** [comment]
Can you share the code to reproduce the issue?

**Comment by yoda06** [comment]
`
@Bean(name = CUSTOM_CACHE_KEY)
public RMapCache<CustomKey, CustomeValue> getCustomCache() {
    return redisson.getMapCache(KEY_NAME, new TypedJsonJacksonCodec(CustomKey.class, CustomValue.class));
}
`
    
This is the current code I am using. Do I also need to some options along with these

**Comment by mrniko** [comment]
Unable to reproduce the issue with the code below

```java
        RMapCache<Test1, Test2> mapCache = redisson.getMapCache("test", new TypedJsonJacksonCodec(Test1.class, Test2.class));
        Test2 t2 = new Test2();
        t2.setVal("t2");
        Test1 t1 = new Test1();
        t1.setValue("t1");
        mapCache.put(t1, t2);
        Test2 t = mapCache.get(t1);
        assertThat(t.getVal()).isEqualTo("t2");
```

**Comment by nkasridhar** [comment]
@mrniko I am facing similar issue. I have created a separate question ticket as well https://github.com/redisson/redisson/issues/6800

I am facing the issue even with below code example 

 Example :
		
  public class Test {

    String name ;
    String value ;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
   }


     Test test = new Test();
      test.setName("test name)");
      test.setValue("test_value");

      String key = "test-ttl-expiration";
      long ttlSeconds = 120;

        RMapCache<String, com.pdi.risev2.datastore.cache.Test> mapCache = redissonClient.getMapCache(TEST_CACHE_NAME, createRedissonJsonCodec());
        mapCache.put(key, test, ttlSeconds, TimeUnit.SECONDS);
		
		    static JsonJacksonCodec createRedissonJsonCodec() {
        JsonJacksonCodec codec = new JsonJacksonCodec();
        codec.getObjectMapper()
                .registerModule(new Jdk8Module())
                .registerModule(new JavaTimeModule())
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
        return codec;
    }

**Comment by mrniko** [comment]
@nkasridhar 

I left a comment in https://github.com/redisson/redisson/issues/6800
