### ISSUE TITLE
tryLock with leaseTime allows multiple lock acquisitions on same lock name

### ISSUE THREAD

**Issue by maxfd3v** [redisson/redisson#5033]
**Expected behavior**
Must only acquire 1 lock

**Actual behavior**
Typically returns between 5 and 9 locks (varies)
Works when attempted lock count is <10

**Steps to reproduce or test case**
See
[RedissonLeaseLockTest2.java.txt](https://github.com/redisson/redisson/files/11461828/RedissonLeaseLockTest2.java.txt)

**Redis version**
7.0.5
6.x.x

**Redisson version**
3.17.7
3.21.0

**Redisson configuration**
useSingleServer()
redisson.timeout.ms=10000
redisson.threads=8
redisson.netty-threads=8
redisson.connection-pool-size=256
redisson.connection-minimum-idle-size=2

**Comment by gill-ratcu** [comment]
I ran your test and fist I though that you found a nasty bug.
But it is not a bug. The lock is reentrant so the same thread will acquire the lock.
Check the logs and you will see that each time the lock is acquired, it is by the same thread.

**Comment by mrniko** [comment]
That's correct the lock is reentrant.

**Comment by maxfd3v** [comment]
Noted Tx

**Comment by mrniko** [comment]
`log.info("acquring lock {}", lockName);` in a wrong place it should be here:

```java
                if (b) {
                    log.info("acquring lock {}", lockName);
                    counter.incrementAndGet();
                }
```

**Comment by gill-ratcu** [comment]
Besides wrong log place, the test is not correct. I will increment the counter more than once since the same thread will get the chance to re-acquire the lock due to reentrance.

**Comment by 706716244** [comment]
I think we can use lock.isLocked() method to forbid redisson in same thread get a same RLock .
