### ISSUE TITLE
Redis Cluster nodes configuration randomly missing IP addresses

### ISSUE THREAD

**Issue by thehammeranderson** [redisson/redisson#5034]
Our old Redisson/Redis setup was one Master and two Slaves and has been working perfect with the exception of the setup unable to scale for our needs.  I have created a new AWS EKS cluster, installed Redis Cluster (for scaleability) via Helm chart, and have 24 microservices that scale up/down and all use Redisson to store maps and subscribe to topics.  More often than not, the microservices come up fine, the client is setup properly and our topic listeners are created.  We are seeing random failures with cluster state not being able to be retrieved because of DNS lookup (which i think i solved by checking every 5 min instead of every 2 seconds), and a strange issue where the nodes configuration that is retrieved is missing a random node IP.  I have attached a segment of our log showing the issue.  I was wondering if there is any configuration that I could tweak or if there are any ideas on how to resolve this?
[cluster nodes config incomplete.txt](https://github.com/redisson/redisson/files/11466619/cluster.nodes.config.incomplete.txt)

**Comment by mrniko** [comment]
That's expected since you got `:0@0 master,noaddr - 1681749336848 1681749336848 7 disconnected 0-5460` in cluster topology. Slots 0-5460 weren't mapped

**Comment by thehammeranderson** [comment]
The question is why it didn't retrieve an IP address.  And furthermore, why did I get a different node without an IP address on the second call.  Then on the third call all IP addresses were returned.  These IP addresses haven't changed in the K8S cluster and yet many service that comes up initially have this odd missing IP address behavior.  The majority of them don't have any issue at all.  Seems like some timing issue when the Redisson clients are initialized, but I don't know what to do about it.

**Comment by thehammeranderson** [comment]
Because of this, we have also discovered that even though all the slots are covered that we fail to be able to get a proper client and use it because the node that has an IP address but was unable to be retrieved causes the following error when we try to use it:
Not all slots covered! Only <number> slots are available. Set checkSlotsCoverage = false to avoid this check

**Comment by mrniko** [comment]
> The question is why it didn't retrieve an IP address

Did you try to reach out AWS Support?

**Comment by mrniko** [comment]
> Because of this, we have also discovered that even though all the slots are covered that we fail to be able to get a proper client and use it because the node that has an IP address but was unable to be retrieved causes the following error when we try to use it:

Can you share the log for this case? Because if IP reachable then the error shouldn't appear.

**Comment by thehammeranderson** [comment]
The log is in my original post.  You can see that the final cluster query returned all the IP addresses.  Those IP addresses have never changed since the time when I deployed the Redis cluster, yet several cluster queries as shown in the logs get a missing IP address on a different master node for some reason.
