### ISSUE TITLE
Is there a way to delete `BinaryStream` in a batch operation?

### ISSUE THREAD

**Issue by sergiy-sc** [redisson/redisson#5036]
I'm trying to do something like this:
```
final RBatchRx batch = rxClient.createBatch();
final var deleteMapOp = batch.getMap("map1").delete().ignoreElement();
final var deleteStreamOp = batch.getBinaryStream("blob1").delete().ignoreElement();
...
```
But it looks like `RBatchRx` is missing `getBinaryStream()` method (or anything similar).
Is it not implemented or is there another way to do that?

**Comment by mrniko** [comment]
RBinaryStream interface doesn't contain reactive compatible methods. You can use `RBucket<byte[]>` instead.
