### ISSUE TITLE
Provides a compatible parsing scheme for RedissonDelayedQueue internal data format changes

### ISSUE THREAD

**Issue by timnick-snow** [redisson/redisson#5040]
We noticed a breaking change RedissonDelayedQueue internal data format changed  in 3.21.1. 
It's fine to use the new format processing for new data, but for old data that has already been added, can you fall back to the old parsing scheme when parsing fails with the new format.

Consider adding configuration or system env to enable compatibility resolution. To facilitate compatibility upgrades

**Comment by mrniko** [comment]
It would complicate the logic and introduce issues.

Below is the script you can use with RScript object to read old data.

```java
        return commandExecutor.evalReadAsync(getRawName(), codec, RedisCommands.EVAL_LIST,
                "local result = {}; " +
                "local items = redis.call('lrange', KEYS[1], 0, -1); "
              + "for i, v in ipairs(items) do 
                   + "local timeout = redis.call('zscore', KEYS[2], v);"
                   + "local randomId, value = struct.unpack('dLc0', v); "
                   + "table.insert(result, timeout);"
                   + "table.insert(result, value);"
              + "end; "
              + "return result; ",
           Collections.singletonList("redisson_delay_queue:" + queueName, "redisson_delay_queue_timeout:" + queueName));
```
