### ISSUE TITLE
Looking for some examples about the fenced lock.

### ISSUE THREAD

**Issue by bjcodereview3** [redisson/redisson#5044]
Hi maintainers!

I found this code snippet on the [documentation](https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers#810-fenced-lock):

```java
RFencedLock lock = redisson.getFencedLock("myLock");

// traditional lock method
Long token = lock.lockAndGetToken();

// or acquire lock and automatically unlock it after 10 seconds
token = lock.lockAndGetToken(10, TimeUnit.SECONDS);

// or wait for lock aquisition up to 100 seconds 
// and automatically unlock it after 10 seconds
Long token = lock.tryLockAndGetToken(100, 10, TimeUnit.SECONDS);
if (token != null) {
   try {
     // check if token >= old token
     ...
   } finally {
       lock.unlock();
   }
}
```

what does this line comment mean?

> check if token >= old token

Where is an old token in the code context? Do I need to manually check the token somewhere in my code or it just a internal techinque that redisson uses to keep track of the lock status? And where can I find the source code about how redisson uses the token mechanism? Thanks.

**Comment by mrniko** [comment]
Token validity tracking is on the developer side.
