### ISSUE TITLE
Will you use shared pubsub instead of pubsub in Lock?

### ISSUE THREAD

**Issue by HuiWang1995** [redisson/redisson#5047]
**Is your feature request related to a problem? Please describe.**

not  related to a problem.

**Describe the solution you'd like**

May uesing shared pubsub which new in redis 7.0 to replace pubsub in redisson`s lock?

That means we can reduce network traffic use.

**Describe alternatives you've considered**

It can be a new Lock solution for redis 7.

**Comment by mrniko** [comment]
Done
