### ISSUE TITLE
I want to optimize the redisson-spring-boot-starter module. I don't know if it is possible

### ISSUE THREAD

**Issue by poo0054** [redisson/redisson#5048]
I want to optimize the redisson-spring-boot-starter module. I don't know if it is possible

**Comment by mrniko** [comment]
Neither do I. Is there any suggestions?

**Comment by poo0054** [comment]
I want to decouple Config and RedissonClient, RedissonAutoConfiguration does not force a dependency on spring-data-redis.
Mainly modify the RedissonAutoConfigurationl class. I don't know if I can try

**Comment by poo0054** [comment]
I'd like to incorporate the redisProperties fetch into the spring lifecycle, rather than making a determination when creating a redisson
