### ISSUE TITLE
RRingBuffer unexpected TTL behaviour

### ISSUE THREAD

**Issue by rafall-rak** [redisson/redisson#5051]
**Expected behavior**
Setting TTL on `RRingBuffer` should affect every key created by the `RRingBuffer`. 

**Actual behavior**
Setting TTL on `RRingBuffer` affects only the list itself and doesn't set expiration date on an associated `redisson_rb` key.

**Steps to reproduce or test case**
With the code snippet as follows:

```
RRingBuffer<ByteString> buffer = redissonClient.getRingBuffer(ringBufferKey);
...
buffer.trySetCapacity(desiredCapacity);
buffer.expire(Instant.now().plus(ttlHours, ChronoUnit.HOURS));
```

Two keys are created in redis: `ringBufferKey` and `redisson_rb:{ringBufferKey}`. Correct TTL is set for the `ringBufferKey` but `redisson_rb:{ringBufferKey}` doesn't ever expire causing database bloat.

**Redis version**
7.0.7

**Redisson version**
3.21.0

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed. Thanks for report
