### ISSUE TITLE
About RLongAdder Use，redisson how and when to clean the 'semaphore' key

### ISSUE THREAD

**Issue by michelQ** [redisson/redisson#5055]
Hello！Recently, I use Redisson RLongAdder function。I found the RLongAdder will create a samphore object when invoke sum function, but not found how and when to clean the samphore key. After a long time,  may be create many samphore object keys if ivoke 
RLongAdder sum function many times. 

![202305](https://github.com/redisson/redisson/assets/15917374/bbd14b2c-4d11-4f25-808c-6bc11d637fe6)

![image](https://github.com/redisson/redisson/assets/15917374/e63c9893-0fd2-42de-8bb7-f1deb73bfe16)

**Comment by mrniko** [comment]
Fixed in 3.16.8 version. You need to update to the latest version
