### ISSUE TITLE
Spring Boot 3.1 to support RedisProperties new structure

### ISSUE THREAD

**Issue by nico-arianto** [redisson/redisson#5056]
**Is your feature request related to a problem? Please describe.**
Follow up from https://github.com/redisson/redisson/commit/c7b7080c27733270b675660a9bca56248e01365f that in the latest Spring Boot 3.1.x, the `RedisProperties` have been updated for the `ssl` to `ssl.isEnabled` and there is a bundle config also.

**Describe the solution you'd like**
Enhance https://github.com/redisson/redisson/blob/d4d100f7dcca8e1fc26ea0acef39d6bbab35f1dd/redisson-spring-boot-starter/src/main/java/org/redisson/spring/starter/RedissonAutoConfiguration.java#LL228C29-L228C29 to
* Updated to match with the `RedisProperties` new structure
* Support SSL bundle also

**References**
* https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.nosql.redis.connecting

**Comment by mrniko** [comment]
Done

**Comment by nico-arianto** [comment]
Thanks @mrniko
