### ISSUE TITLE
Unable to get the data of session object

### ISSUE THREAD

**Issue by vk185160** [redisson/redisson#5057]
We are using liferay in our project and now we are integrating redis with our liferay application. we directly couldn't use redisson as a dependency as we were facing deserialisation issues so we decided to use the following project which internally uses redisson. with this project we are able to store our session as a redis key but now we want to update that session object(we want to add attributes to the respective session objects) but we are not able to fetch the session object we are seeing the issue(screenshot attached) could you let us know what exactly the issue is? what's the solution?

https://github.com/marianoalvarosaiz/liferay-utilities
https://github.com/marianoalvarosaiz/liferay-utilities/blob/master/modules/redis-redisson-integration/src/main/java/com/liferay/redis/redisson/integration/tomcat/LiferayRedissonSessionManager.java

<img width="1154" alt="Screenshot 2023-05-23 at 11 17 02 AM" src="https://github.com/redisson/redisson/assets/76038799/b0ecb176-b932-4950-b4fe-31462c4f8cc5">

**Comment by mrniko** [comment]
Sorry, what is the issue?

**Comment by vk185160** [comment]
As you can see in the attached screenshot I am trying to read the session object that's stored while creating the session redisson:tomcat_session:FF08BA6C4E8C3AD67E26F02BAB874728.ap-main-dev1-wug02-alpha-ddcb.
while reading that value using RMap, I am seeing that Unable to evaluate the children renderer expression Method threw 'org.redisson.client.RedisException' exception

**Comment by mrniko** [comment]
Can you share the full stacktrace in log and not in IDE?
