### ISSUE TITLE
Memory leak Tomcat 8.5.45 or Tomcat 9.0.73

### ISSUE THREAD

**Issue by pSzymek** [redisson/redisson#5062]
**Actual behavior**
Getting memory leaks while using Redisson with Tomcat. 
Logs from console: 
SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7966baa7]) and a value of type [io.netty.util.internal.InternalThreadLocalMap] (value [io.netty.util.internal.InternalThreadLocalMap@7e8dcdaa]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Steps to reproduce or test case**
```
@PostConstruct
	public void init() {
		try {
			Config config = new Config();
			config.useSingleServer().setAddress("redis://localhost:6379");
			redissonClient = Redisson.create(config);
		} catch (Exception e) {
			logger.error("[REDIS] Error during initializing redis connection {}", e);
		}
	}

	@Produces
	public RedissonClient redissonClient() {
		return redissonClient;
	}

	@PreDestroy
	public void destroy() {
		redissonClient.shutdown();
	}

```

**Redis version**
Server
redis_version:6.2.12

**Redisson version**
redisson:3.21.3
But i get the same errors on every redisson version
**Redisson configuration**
Above /|\

**Comment by mrniko** [comment]
Please attach the memory dump
