### ISSUE TITLE
Why is there no validation in the release method of RedissonSemaphore, and instead it directly performs an incr action?

### ISSUE THREAD

**Issue by WLittleBug** [redisson/redisson#5066]
public RFuture<Void> releaseAsync(int permits) {
        if (permits < 0) {
            throw new IllegalArgumentException("Permits amount can't be negative");
        }
        if (permits == 0) {
            return new CompletableFutureWrapper<>((Void) null);
        }

        RFuture<Void> future = commandExecutor.syncedEval(getRawName(), StringCodec.INSTANCE, RedisCommands.EVAL_VOID,
                "local value = redis.call('incrby', KEYS[1], ARGV[1]); " +
                        "redis.call('publish', KEYS[2], value); ",
                Arrays.asList(getRawName(), getChannelName()), permits);
        if (log.isDebugEnabled()) {
            future.thenAccept(o -> {
                log.debug("released, permits: {}, name: {}", permits, getName());
            });
        }
        return future;
    }

Here is the code for the release() method in version 3.21.0. There is no check to see if the key exists, and there is no check to see how many permits the semaphore can release. It simply performs an incr action. If another client performs a duplicate release() operation, it will release many permits that should not have been released.

**Comment by mrniko** [comment]
This is how JDK implementation works. It's expected behaviour.
