### ISSUE TITLE
KryoCodec Issue with Redisson 3.21.3 in Multi-thread Environment

### ISSUE THREAD

**Issue by starryeye** [redisson/redisson#5072]
Hello,

I've encountered an issue while using Redisson 3.21.3 in a multi-thread environment within the same JVM. The default codec, KryoCodec, appears to have a problem with serializing/deserializing integers.

Here's an excerpt of my code where I use Redisson:
```
private int getCurrentStock(String key) {
    return redissonClient.<Integer>getBucket(key).get();
}

private void setStock(String key, int value) {
    redissonClient.getBucket(key).set(value);
}
```

When executing the code in a multi-thread environment, I encounter the following exception:
```
Exception in thread "pool-3-thread-14" org.redisson.client.RedisException: Unexpected exception while processing command
    ...
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 47
    ...
```

I tried changing the RedissonClient's codec from KryoCodec to JsonJacksonCodec, and the issue no longer persists.
```
Config config = new Config();
config.setCodec(new JsonJacksonCodec());
...
RedissonClient redissonClient = Redisson.create(config);
```

Considering that the default codec in version 3.21.3 is KryoCodec, I believe this is a potential bug that needs to be addressed. Please look into this issue.

Thank you.

**Comment by mrniko** [comment]
Can you share full stacktrace?

**Comment by mrniko** [comment]
Unable to reproduce.

Below is the test.

```java
        redisson.getBucket("test").set(123);
        ExecutorService e = Executors.newFixedThreadPool(16);
        for (int i = 0; i < 1000000; i++) {
            e.submit(() -> {
                try {
                    redisson.getBucket("test").get();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
        }

        e.shutdown();
        assertThat(e.awaitTermination(20, TimeUnit.SECONDS)).isTrue();
```

**Comment by starryeye** [comment]
I apologize for taking up your time... I misunderstood the test case.

The actual error occurred when serializing with the lettuce Client default Serializer(StringCodec) and deserializing using the redisson Client default codec(Kryo5Codec).

This link is the test code where I matched the Codecs of the two Redis Clients and tested it. 

[The original code that led to the misunderstanding via the issue](https://github.com/starryeye/redis/blob/main/DistributedLock/src/test/java/dev/practice/DistributedLock/service/InventoryServiceTest.java)
-> @Test void reduceStockTestWithLock()

[The test code used for issue tracking](https://github.com/starryeye/redis/blob/main/IssueTracking/src/test/java/dev/practice/IssueTracking/InventoryServiceTest.java)
-> @Test void push_using_lettuce_get_using_redisson()

If you find any mistakes when you have time, I'd appreciate it if you could let me know. 
I'm a junior developer who hasn't been studying Redis for even a month... XD

Thank you.
감사합니다.
