### ISSUE TITLE
RStream.read blocks indefinitely if the stream is empty

### ISSUE THREAD

**Issue by Alex-Glasser-Imprivata** [redisson/redisson#5076]
Hello,

I'm facing an issue with `RStream.read` and `RStream.readGroup` when the stream has no entries. The timeout that I am providing seems to be ignored:

```
StreamMessageId offset = StreamMessageId.ALL;
int maxResults = 1;
Duration timeout = Duration.of(50, MILLIS);
// hangs
stream.read(
  StreamReadArgs
    .greaterThan(offset)
    .count(maxResults)
    .timeout(timeout));
```

I can work around this in this specific case by checking the size of the stream:
```
StreamMessageId offset = StreamMessageId.ALL;
int maxResults = 1;
Duration timeout = Duration.of(50, MILLIS);
if (stream.size() == 0) {
  return Map.of();
}
stream.read(
  StreamReadArgs
    .greaterThan(offset)
    .count(maxResults)
    .timeout(timeout));
```

However, this won't work for multiple consumers in the same group, because `stream.size()` will not return 0 if those messages have been acknowledged by another consumer.

I see there is a test in `RedissonStreamTest` called `testReadEmpty` for this case, but that does not provide a timeout and therefore does not reproduce the issue.

**My question:**
Am I using this API incorrectly, or is this a defect? What is a good way to work around this issue given that my current workaround does not work with the `readGroup` API?

**Comment by Alex-Glasser-Imprivata** [comment]
It seems like the offending code in `RedissonStream` is:

```
if (rp.getTimeout() != null) {
  params.add("BLOCK");
  params.add(toSeconds(rp.getTimeout().getSeconds(), TimeUnit.SECONDS)*1000);
}
```

Because I was passing 50 milliseconds, this was floored to 0. I assume this means "wait indefinitely" which is why it never returned. Providing a 1 second timeout resolved this issue—should've tried this before I opened an issue!

**Comment by petermyers** [comment]
I ran into this same issue yesterday. Is it documented somewhere that I missed that the minimum granularity for the duration is seconds? Seems like it will always get floored, so even passing in something like `Duration.of(1500, MILLIS)` would result in a timeout of 1 second.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/4819
