### ISSUE TITLE
Make MKSTREAM optional when creating consumer group.

### ISSUE THREAD

**Issue by petermyers** [redisson/redisson#5081]
**Describe the solution you'd like**
Some years ago in [this commit](https://github.com/redisson/redisson/commit/c16a31b09bf3eec3df0abd4b50ab11bf273c16ed), `MKSTREAM` was hardcoded into the create group command.

I think it would be reasonable to make that optional. For example, in my use case I have a producer to the stream that I would like to be solely responsible for creating the stream if it does not exist, in attempting to create a consumer group, I would like that to fail if the stream does not exist yet.

Making this optional would also make it consistent with `StreamAddArgs` where I can prevent it from creating the stream on the writer side if needed by calling `noMakeStream()`

**Comment by mrniko** [comment]
Done. Thanks for pointing out.
