### ISSUE TITLE
Difference between sentinel and replicated mode

### ISSUE THREAD

**Issue by kapilgarg1996** [redisson/redisson#5087]
Hi @mrniko ,
I wanted to understand the difference between redisson sentinel mode and redisson replicated mode.

As per my understanding, 
1. both the modes support automatic switch to new masters in failover.
2. In sentinel mode, redisson uses sentinels to query the new master whereas in replicated mode, redisson queries the nodes directly to find the new master. Upon discovery of new master, it switches over to new master.
3. In both sentinel and replicated mode, there can be a single master and multiple replicas. 

Is there any benefit of using sentinel mode in redisson over replicated mode ?

**Comment by mrniko** [comment]
replicated mode is implemented by Redis vendor, whereas sentinel is available out of box.
