### ISSUE TITLE
in cluster mode,the cluster-state check has one hard to find flaw should be avoid。

### ISSUE THREAD

**Issue by JUNFN70783660042** [redisson/redisson#5091]
![企业微信截图_16862082691881](https://github.com/redisson/redisson/assets/18289387/edea8feb-8aeb-4590-ae20-f8c8c08a8839)
i think we shuld check the variable of cfg.scanInterval when it is 0 or too min，the servers（cluster-servers）`s CPU will achieve 100%。

**Comment by mrniko** [comment]
Fixed. Thanks for report
