### ISSUE TITLE
Netty conflicts

### ISSUE THREAD

**Issue by AoElite** [redisson/redisson#5095]
I'm using redisson along side of another library using netty. I recently upgraded from Redisson 3.21.0 to 3.22.0 and now I've been getting netty errors such as `io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: inflate data is bad`. I think netty might need to be shaded & relocated within redisson to prevent conflicts of other libraries also using their own netty.

**Redis version**
7.0

**Redisson version**
3.22.0

**Comment by mrniko** [comment]
Why Redisson and not another library? :)

**Comment by AoElite** [comment]
@mrniko Are you saying to not use Redisson? I don't understand.

**Comment by mrniko** [comment]
I mean why another library can't shade netty?

**Comment by AoElite** [comment]
@mrniko They would likely ask the same question. However, it makes sense for Redisson to do this to prevent conflicts, as it is a utility library expected to be used in high-performance environments, where Netty is often used.

**Comment by mrniko** [comment]
I don't think I can do that as it deprives users of the ability to upgrade netty.

**Comment by AoElite** [comment]
@mrniko What do you mean? That would do the opposite.
