### ISSUE TITLE
Redisson Live Object; Fields annotated with @RIndex not persisted; Collections not cleaned up

### ISSUE THREAD

**Issue by AndriusKli** [redisson/redisson#5103]
Redisson 3.22.0.
Official 7.0.10 image for Redis itself.

Excuse me if these should be separate tickets, but I've seemingly found the following problems after a brief trial. Let's say I have the following object.

```
@REntity
public class SomeObject {

    @RId
    String someId;
    @RIndex
    String someField;
    List<Long> someCollection;

    public SomeObject() {
    }

    public SomeObject(String someId, String someField, List<Long> someCollection) {
        this.someId = someId;
        this.someField = someField;
        this.someCollection = someCollection;
    }

<getters, setter, equals/hash>
```

```
 RLiveObjectService liveObjectService = redissonClient.getLiveObjectService();
 SomeEntity someEntity = new SomeEntity("1", "5", List.of(1, 2, 3));
 liveObjectService.persist(someEntity);
```

 At this point, if I look at Redis, the indexed 'someField' is NOT persisted. To double check, if I retrieve the object via `liveObjectService.detach(liveObjectService.get(SomeEntity.class, "1"));`, the field appears to be null.

 Second issue is related to lists (and probably other collections, did not try). Using the same entity as above: 

```
 liveObjectService.persist(someEntity);
 liveObjectService.delete(someEntity, "1");
 liveObjectService.persist(someEntity);
```

And now, if I retrieve the object, `someCollection` contains the elements `[1, 2, 3, 1, 2 ,3]`. Exact same result if the live object has an expiry set -- the associated list elements are not cleaned up either.

**Comment by mrniko** [comment]
Can you try to set `someField`, `someCollection` values via setters and not a constructor?

**Comment by AndriusKli** [comment]
My bad, it was the setters, they were generated as a builder. 
```
public SomeObject setSomeId(String someId) {
        this.someId = someId;
        return this;
    }
```
Switching to regular setters resolved said issues.    

HOWEVER, there remains the issue with what I initially came looking for, namely secondary index expiry/cleanup, [which appears there was a bug fix for in 3.22.0](https://github.com/redisson/redisson/issues/2625) . 

E.g., after this RLO expires or is deleted, the indexed fields are not cleaned up, and I am able to retrieve the object by the indexed field (every other field is null). Perhaps I am missing something, or is it still bugged? (Should probably move this inquiry to one of the previous bug tickets, excuse the confusion).

```
        SomeObject someObject = liveObjectService.persist(new SomeObject("1"));
        someObject.setSomeField("5");
        someObject.setSomeCollection(List.of(1L, 2L, 3L));
        liveObjectService.asLiveObject(someObject).expire(Duration.of(30, ChronoUnit.SECONDS));
```

**Comment by AndriusKli** [comment]
Thank you! Got it working. The value that I needed in the end for the above mentioned setting was `AKE`, as per Redis docs.

Perhaps it would be worth adding a few sentences about this under the RLO documentation? As a fresh user, I wasn't aware of keyspace events. Quite a major pitfall if you're looking at that section, especially @RIndex.

**Comment by mrniko** [comment]
Added a comment at the bottom of `Search by Object properties` section.

**Comment by AndriusKli** [comment]
Sorry, premature celebration, one more inquiry. Despite the `AKE` (same deal with the suggested `Ex`) parameter, which should cover most keyspace events, I can see that the associated list entries are never removed, be it expiry or deletion of the RLO. Save the object with [1, 2], delete it, save it with [2, 3], and now the collection consist of [1, 2, 2, 3], since it was never removed.

**Comment by AndriusKli** [comment]
Additionally, it appears the index cleanup on expiry is not a thorough as I initially though - the hash table entry for the index remains, only the related set entry is removed. Simply deleting the RLO deletes both just fine, for example.

**Comment by mrniko** [comment]
> Additionally, it appears the index cleanup on expiry is not a thorough as I initially though - the hash table entry for the index remains, only the related set entry is removed.

Fixed

**Comment by mrniko** [comment]
> I can see that the associated list entries are never removed, be it expiry or deletion of the RLO

Fixed
