### ISSUE TITLE
RedissonSearch search(), error report "Parameters must be specified in PARAM VALUE pairs"

### ISSUE THREAD

**Issue by wapthen** [redisson/redisson#5106]
read source code, maybe a problem in RedissonSearch:searchAsync function,  PARAMS number is wrong, the number should include key and value。

For function：
public RFuture<SearchResult> searchAsync(String indexName, String query, QueryOptions options) {
..........
        if (!options.getParams().isEmpty()) {
            args.add("PARAMS");
            args.add(options.getParams().size()); // <==== should be "options.getParams().size() * 2"
            for (Map.Entry<String, Object> entry : options.getParams().entrySet()) {
                args.add(entry.getKey());
                args.add(entry.getValue());
            }
        }
..........
}

**Comment by wapthen** [comment]
For example:
QueryOptions queryOptions = QueryOptions.defaults()
                .params(Map.of("key", "value"));
finally, redisearch command should be PARAMS 2 key value. But for redisson 3.22.0,  is PARAMS 1 key value.
redis report:  (error) Parameters must be specified in PARAM VALUE pairs

**Comment by mrniko** [comment]
Fixed. Thanks for report
