### ISSUE TITLE
Retrieving parent live object by nested indexed field?

### ISSUE THREAD

**Issue by AndriusKli** [redisson/redisson#5112]
Example:

```
@REntity
public class ParentObj {
    @RId
    Long id;

    @RCascade(RCascadeType.ALL)
    List<NestedObj> nestedObjs;
}

....

@REntity
public class NestedObj {
    @RId
    Long nestedId;

    @RIndex
    Long nestedIndex;
}
```

Is there any out-of-the-box way of finding the ParentObj(s) by an indexed field of a nested object? Something like along the lines of

`rloService.find(ParentObj.class, Conditions.eq("nestedIndex", 5L))`

Were it not a list, you could chain the find()'s and find your parent object, but that does not seem possible if the field in question is a data structure of any type, unless I am missing something.

**Comment by mrniko** [comment]
Currently no. You could store parentId in NestedObj
