### ISSUE TITLE
pubsub subscriber OOM

### ISSUE THREAD

**Issue by adamsau** [redisson/redisson#5117]
![image](https://github.com/redisson/redisson/assets/5195810/55bfaf51-727e-44a9-ae2f-f3965da9c14e)

if the subscriber is set to keepAlive to true, the message will be append to the unbounded ConcurrentLinkedQueue. If the application polls/process message at a slow speed (i.e. application bug), will it cause the application to go OOM?

**Comment by mrniko** [comment]
That's correct. Though it's another bug `isKeepPubSubOrder` should be used for the check

**Comment by mrniko** [comment]
Let me know if you can suggest the solution
