### ISSUE TITLE
Codec Issue when upgrading from version 3.18.1 to 3.19.0

### ISSUE THREAD

**Issue by ArvinEsmailzadeh** [redisson/redisson#5119]
When upgrading the version of the dependency we noticed that the default codec was changed in version 3.19.0 from MarshallingCodec  to Kyro5Codec. Now we are seeing errors in regards to:
 `Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.String (java.lang.Float and java.lang.String are in module java.base of loader 'bootstrap')`

We have manually set the codec to MarshallingCodec  but this is not optimal as MarshallingCodec  is deprecated. Is there any advice anyone can give?

**Comment by mrniko** [comment]
The only way is to copy data from old object to a new one with a new codec.

**Comment by andreas-ajaib** [comment]
Hi @mrniko I am having similar issue after upgrading to the current version. Will object expiration via TTL solve the issue?
