### ISSUE TITLE
Map entrySet and Maps entries

### ISSUE THREAD

**Issue by seffieschwartz** [redisson/redisson#5121]
Do entrySet() and entries() method return all elements at once?   In other words might they cause memory problems
Also the other methods such as keySet().

One other question: Is there a keyCounts() method - where the keys and the number of values per key is returned.

**Comment by mrniko** [comment]
> Do entrySet() and entries() method return all elements at once? In other words might they cause memory problems
Also the other methods such as keySet().

No, they use iterator.

> One other question: Is there a keyCounts() method

YOu can use size() method instead
