### ISSUE TITLE
RMapCache shouldn't emit events if no listeners added

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#5125]

**Comment by mrniko** [comment]
Done

**Comment by davidreis97** [comment]
Hi @mrniko, awesome work on the optimization - everything is working like a charm. 

However, it did lead me on a wild goose chase for about an hour trying to figure out why my listeners stopped working after a FLUSHALL on my local Redis instance (it didn't cross my mind that the two things could even be related 😂).

So it got me thinking it might be helpful to have this documented a little more thoroughly?
