### ISSUE TITLE
RedissonBloomFilter

### ISSUE THREAD

**Issue by yangsen-cn** [redisson/redisson#5129]
**Error code**
  RedissonBloomFilter.java
  Line 123 and Line 174
  for (Boolean val : result.subList(1, result.size()-1)) {
  **shouldn't** Minus 1
  Because of the parameters of this method is “toIndex” ，not “length”

**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
7.0.11

**Redisson version**
3.20.1

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed. Thanks for report
