### ISSUE TITLE
Redis settings in redisson-spring-boot-starter README is deprecated.

### ISSUE THREAD

**Issue by Pengfei-Lu** [redisson/redisson#5138]
**Expected behavior**
Redis settings in redisson-spring-boot-starter [README](https://github.com/Pengfei-Lu/redisson/blob/master/redisson-spring-boot-starter/README.md?plain=1#L43) is inconsistent with latest SpringBoot [RedisProperties](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisProperties.java) (related RedisProperties update [PR](https://github.com/spring-projects/spring-boot/issues/11574)).

**Actual behavior**
Redis settings in redisson-spring-boot-starter [README](https://github.com/Pengfei-Lu/redisson/blob/master/redisson-spring-boot-starter/README.md?plain=1#L43) is deprecated.
![image](https://github.com/redisson/redisson/assets/7485400/afa7272f-42b4-4c07-896d-7db8135b372c)

**Comment by mrniko** [comment]
Thanks for contribution.
