### ISSUE TITLE
引入redis的发布订阅,出现异常

### ISSUE THREAD

**Issue by zys870135491** [redisson/redisson#5145]
![image](https://github.com/redisson/redisson/assets/54832250/678c8fa5-be07-4a31-86b4-85f99544d9d5)
引入了redis的发布订阅功能，出现了如下报错
![image](https://github.com/redisson/redisson/assets/54832250/a924b097-2333-49de-a7eb-e3c26e37890b)
此时项目还是可以正常启动，但是redis发布的消息消费不到

**Comment by mrniko** [comment]
You need to check your classpath. Since `SubscriptionListener` class is missed.
