### ISSUE TITLE
RedisConnection `close()` private but mentioned in documentation

### ISSUE THREAD

**Issue by cortlepp-intershop** [redisson/redisson#5154]
I am currently trying to use the low-level redis client to send some command (BGSAVE) to my redis server.

I have found [this](https://github.com/redisson/redisson/wiki/10.-additional-features#108-low-level-redis-client) documentation, and I was trying to do this synchronously. The problem I ran into is that the `conn.close()` method used in the example is private, i.e. I cannot use it.

(How) should one close such a connection then, or should I just use the async methods?

Whatever the answer, the documentation should be updated too.

**Comment by mrniko** [comment]
Fixed. Thanks for report
