### ISSUE TITLE
How to convert kryo5 object to string in redis function?

### ISSUE THREAD

**Issue by tmdonalds** [redisson/redisson#5155]
I have a redis function that takes a list of arguments and executes HGET. The problem that I have is that the first argument is a time to live. This argument gets encoded by Kryo5 and sent to the redis function as an argument. I am not sure how to convert it in my redis function from the encoded string to an integer. 

```
Object[] args = new Object[3];
args[0] = 123456;
args[1] = "some key";
args[2] = "the key value";
redisson.call(FunctionMode.WRITE, "test", FunctionResult.Value, List.of("map"), args);

...

local function do_something(keys, args)
    redis.log(redis.LOG_WARNING, args[1]) -- this is not an integer. This is an encoded kryo5 representation of the integer. 
end
```

**Comment by mrniko** [comment]
You need to use org.redisson.client.codec.ByteArrayCodec#INSTANCE instead and encode each param manually to byte array.

**Comment by tmdonalds** [comment]
Thank you @mrniko . Just to be clear there is no way to convert the Kryo5 object in redis to an integer? In order to do what I am trying to do, I would have to convert the object into a byte array and then decode it back into a string?

**Comment by mrniko** [comment]
> Just to be clear there is no way to convert the Kryo5 object in redis to an integer? 

You can do it only on Java side
