### ISSUE TITLE
Command execution timeout for command: (AUTH), params: (password masked) - Redisson client

### ISSUE THREAD

**Issue by leo-li1990** [redisson/redisson#5156]
If you use Redisson to access the Redis cluster, one of the SALVE nodes in the cluster goes down, and Redison keeps trying to reconnect, prompting the above error message

Redis version
redis_version:6.2.6
Redisson version
Redisson 3.22.1

**Comment by mrniko** [comment]
Unable to reproduce. Please share log output with `trace` logging level for `org.redisson` package
