### ISSUE TITLE
Introduce MapCacheOptions object with removeEmptyEvictionTask() method.

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#5161]
This method removes RMapCache eviction task from memory if map is empty upon entries eviction process completion.

**Comment by mrniko** [comment]
Implemented in https://github.com/redisson/redisson/commit/e784c0588559ac73354df9861d39391ae0d5e2ca

**Comment by gitrahul9** [comment]
@mrniko  We tried using this method to reduce memory usage and avoid memory leak,  by the following way, with every get/put call from the client. 
```
final RMapCache<String, String> cacheMap = redissonClient.getMapCache(key, MapCacheOptions.<String, String>defaults().removeEmptyEvictionTask());
```
but it increased the heap usage on client side and redis cluster connections and CPU usage. 

Anything that we misunderstood or implemented incorrectly in this regards? Any  suggestion for improvements ?

**Comment by Yazwa** [comment]
@mrniko I can see that from version 3.26.0, the method which we are calling above as mentioned by @gitrahul9 is deprecated as per: https://www.javadoc.io/doc/org.redisson/redisson/3.26.0/org/redisson/api/RedissonClient.html#getMapCache(java.lang.String,org.redisson.api.MapCacheOptions) . 

Can you help us understand how can we solve the memory leak in this case?
