### ISSUE TITLE
Issue of forced float type of addAndGetOperationAsync() in RedissonMap

### ISSUE THREAD

**Issue by harry-jang** [redisson/redisson#5163]
https://github.com/redisson/redisson/blob/3ca17bd12b11b874f3aff2cffba7f344bdc1b5d3/redisson/src/main/java/org/redisson/RedissonMap.java#L1556

When I save a Map with field value of Integer to redis and attempt to change the field by calling the `addAndGet` method with delta value : Integer value of 1, the following error occurs.

**hmset**
``` java
public void deleteAndHmset(String key, Map<String, Integer> fieldMap) {
        RTransaction transaction = redissonClient.createTransaction(TransactionOptions.defaults());

        try {
            RMap<String, Integer> map = transaction.getMap(key, codec);

            map.delete();
            map.putAll(fieldMap);

            transaction.commit();
        } catch (Throwable e) {
            log.warn("CacheClient setAll occurred : key={}, fieldMap={}", key, fieldMap, e);
            transaction.rollback();
        }
    }
```

**hincrby**
``` java
public void hincrby(String key, Object field, int delta) {
        try {
            redissonClient.getMap(key).addAndGet(field, Integer.valueOf(delta));
        } catch (Exception e) {
            log.warn("CacheClient hincrby exeption occurred : key={}, field={}, delta={}", key, field, delta, e);
        }
    }
```
```
org.redisson.client.RedisException:` ERR hash value is not a float. 
command: (HINCRBYFLOAT), promise: java.util.concurrent.CompletableFuture@30723056[Not completed, 1 dependents], params: [allocated_count:testGameCode:testGroupCode, PooledUnsafeDirectByteBuf(ridx: 0, widx: 18, cap: 256), 1]
```

I intended to run the `HINCRBY` command on redisson, but seeing that `HINCRBYFLOAT` is running, it seems like `HINCRBYFLOAT` was forced, is there a reason why you worked like this?

FYI, I'm using redisson 3.21.1 version and it happens on the default codec, org.redisson.codec.Kryo5codec. (It doesn't happen on JsonJacksonCodec.)

**Redis version**
5.0.7
**Redisson version**
3.21.1

**Comment by mrniko** [comment]
this method doesn't work with binary codec

**Comment by harry-jang** [comment]
> this method doesn't work with binary codec
@mrniko 
No, when I follow the debug mode, I get an error in that method.
