### ISSUE TITLE
Redis server response timeout

### ISSUE THREAD

**Issue by dingdaiming** [redisson/redisson#5166]
Problem: Redis is in cluster mode, and then a master node is abnormal, resulting in a re election, Then the server keeps showing "(String), 1 (String), {" errcode ": 0," note ":" INTERNAL: Redis server response timeout (4000 ms) occurred after 3 retry attachments. Increase netyThreads and/or timeout settings. Try to define pingConnectionInterval settings. Command: null, params: null, channel: [id: 0x1acce179, L: 10.100.32.219:16119- R: 10.100.32.88/10.100.32.88: 7003] "," code ": -1," totalPage ": -1, 'totalRecord ': -1}' error message. Could you please analyze how to reproduce this problem and how to solve it

**Comment by dingdaiming** [comment]
redis version:3.0.5
redisson version:3.15.1

**Comment by mrniko** [comment]
you need to increase `retryAttempts` setting to handle failover without errors.

**Comment by dingdaiming** [comment]
I want to reproduce this problem. How should I handle it
