### ISSUE TITLE
Connection and ConnectionPool

### ISSUE THREAD

**Issue by moa-oma** [redisson/redisson#5171]
Hello, I would like to inquire about redisson's network connection and connection pool problem:

1. I found that redisson would initiate a lot of web links, about two dozen. Why isn't there a single network link designed to be reusable?

2. I see the code about link pool from SingleServerConfig file. Does it manage these network connections?

**Comment by mrniko** [comment]
> Why isn't there a single network link designed to be reusable?

You can set by setting pool size to 1.

> Does it manage these network connections?

Network connections are managed by connection pool service.
