### ISSUE TITLE
Issue with keys missing from RLocalCachedMap 

### ISSUE THREAD

**Issue by k1sneha** [redisson/redisson#5173]
We are using `RLocalCachedMap` to cache a `Map<Int, Configuration>`. 
On Production environments we are observing some `keys` missing from `Map<Int, Configuration>` . This happens at random intervals. Why would this happen ? 

Also, due to usage of `RLocalCachedMap`, the cache still references a local copy that may be stale or corrupted. As a result, the corresponding database call to retrieve the data is not being executed.

Adding corresponding code for the cache definition.

**Provider**

```
class ConfigurationCacheProvider @Inject constructor(
    configurationLoader: ConfigurationLoader,
    redissonClient: RedissonClient,
) : Provider<RLocalCachedMap<Int, Configuration>> {

    private val cache: RLocalCachedMap<Int, Configuration> = redissonClient.getLocalCachedMap(
        ConfigurationCache, SerializationCodec(), defaults<Int, Configuration>()
            .loader(configurationLoader)
            .syncStrategy(UPDATE)
    )

    override fun get(): RLocalCachedMap<Int, Configuration> = cache

}
```

**Loader**

```
@Singleton
class ConfigurationLoader @Inject constructor(
    private val configurationDao: ConfigurationDao,
) : MapLoader<Int, Configuration> {

    override fun load(configurationId: Int): Configuration {
        return configurationDao.tryFetch(configurationId).orElse(null)
    }

    override fun loadAllKeys(): List<Int> {
        TODO("No implementation required here since we don't have any use case to load all keys at once")
    }

}
```

Please let me know if any more input is required.

**Comment by mrniko** [comment]
> On Production environments we are observing some keys missing from Map<Int, Configuration> . This happens at random intervals. Why would this happen ?

Logs analysis may help here. Or code example so I could reproduce it.

> Also, due to usage of RLocalCachedMap, the cache still references a local copy that may be stale or corrupted. As a result, the corresponding database call to retrieve the data is not being executed.

You need to set reconnectionStrategy = ReconnectionStrategy.CLEAR

**Comment by k1sneha** [comment]
> Logs analysis may help here. Or code example so I could reproduce it.

@mrniko  We are unable to replicate it (we do not know why this would happen). There is nothing helpful in logs (no exceptions, or errors ) to indicate the said issue.  

>You need to set reconnectionStrategy = ReconnectionStrategy.CLEAR

Will try this out. Thank you for the quick response.

**Comment by k1sneha** [comment]
@mrniko The Reconnection Strategy does not work in this case.

Steps to replicate the issue of cache still pointing to a local cache or stale one :

1. Connect to Redis
2. Initialise a RLocalCachedMap<Int, Configuration> with config below
```
private val cache: RLocalCachedMap<Int, Configuration> = redissonClient.getLocalCachedMap(
        ConfigurationCache, SerializationCodec(), defaults<Int, Configuration>()
            .loader(configurationLoader)
            .syncStrategy(UPDATE)
            .reconnectionStrategy(CLEAR)
    )
```
4. To replicate the issue of key missing in Redis, manually delete the cache from Redis (using CLI) 
5. Check the Map data using `cache.get(key)`

**Expected**
 The Map should not have any entries when using `cache.get()`
**Actual**
The Map still has all the values. The cache does not get cleared.

**Comment by mrniko** [comment]
@k1sneha 

> To replicate the issue of key missing in Redis, manually delete the cache from Redis (using CLI)

That's an incorrect usage. Data should be deleted through Redisson only.
