### ISSUE TITLE
Reduce the scope of key event subscriptions

### ISSUE THREAD

**Issue by OS-tariqabbasi** [redisson/redisson#5179]
**Is your feature request related to a problem? Please describe.**

We are using `RLocalCachedMap` in an environment where we need to restrict user access to certain keys/channels via Redis ACLs with prefixes.

In a recent version of Redisson it appears that this particular map implementation was changed so that it subscribes to `__keyevent@*:expired`, unfortunately there doesn't seem to be any way to disable this or modify the subscription.
The lack of a prefix before the wildcard means that we can no longer use `RLocalCachedMap` in our application.

**Describe the solution you'd like**

Reduce the scope of the pattern so that it only gets key events for keys of the same map (perhaps by prefixing keys with the name of the map?)

**Comment by mrniko** [comment]
Done
