### ISSUE TITLE
Use SUBSCRIBE instead of PSUBSCRIBE in LocalCacheListener

### ISSUE THREAD

**Issue by OS-tariqabbasi** [redisson/redisson#5183]
**Is your feature request related to a problem? Please describe.**

This issue is related to https://github.com/redisson/redisson/issues/5179, specifying Redis ACLs for `PSUBSCRIBE` is not possible if the pattern is dynamic / unknown when defining the rules because the ACL pattern must be exactly the same as the `PSUBSCRIBE` pattern.

Unfortunately in our use the `RLocalCachedMap` has a dynamic suffix at runtime so we are still unable to use it together with ACLs.

**Describe the solution you'd like**

It seems that `LocalCacheListener` no longer needs the extra features of `PSUBSCRIBE` because the topic does not contain any pattern matching characters, would it be possible to use a regular `SUBSCRIBE` instead? This would allow us to specify an ACL rule with a prefix followed by `*` to match all possible names of the map.

**Comment by mrniko** [comment]
Done

**Comment by mrniko** [comment]
You need to set useKeyEventsPattern = false to activate it.
