### ISSUE TITLE
Elasticache connectivity issue when the cluster goes in to recovery for patch

### ISSUE THREAD

**Issue by jainyash** [redisson/redisson#5189]
Hello @mrniko 

We are facing an issue on our production environment. We are using redisson version 3.18.0. When the elasticache cluster had a failover and AWS applied some patching, we ran in to the below issue that brought down our service that was dependent on redis cluster

org.redisson.client.RedisNodeNotFoundException: Node for slot: 8093 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.

 org.redisson.client.RedisNodeNotFoundException: Node for slot: 11040 hasn't been discovered yet. Check cluster slots coverage using CLUSTER NODES command. Increase value of retryAttempts and/or retryInterval settings.

Please note that when we connected to the same cluster via redis-cli, it showed that all the slots were correctly covered. However it seems that redisson went to bad state and could not recover.

Can you please help in this regard.

**Comment by mrniko** [comment]
This is a temporary issue which may arise during failover. You need to increase retryAttempts setting so a new attempts will be made.

**Comment by jainyash** [comment]
@mrniko Is there any recommended value for retryAttempts parameter?
