### ISSUE TITLE
StackOverflowError in AggregationOptions.groupBy() due to recursion

### ISSUE THREAD

**Issue by petekmet** [redisson/redisson#5192]
**Expected behavior**
AggregationOptions.getDefaults().groupBy(GroupBy("id") returns AggregateOptions object

**Actual behavior**
StackOverflowError in groupBy() due to recursive calls of itself.

**Steps to reproduce or test case**
See https://github.com/redisson/redisson/blob/27f270488556effe9d1333a1d75e60c448aa0461/redisson/src/main/java/org/redisson/api/search/aggregate/AggregationOptions.java#L76C1-L76C1

**Redis version**
6.22

**Redisson version**
master

**Redisson configuration**
n/a

**Comment by mrniko** [comment]
Fixed. Thanks for report
