### ISSUE TITLE
Why not Support protobuf

### ISSUE THREAD

**Issue by goule666** [redisson/redisson#5195]

**Comment by mrniko** [comment]
Contributions are always welcome.

**Comment by JavaLionLi** [comment]
Hope to support protobuf, Use protostuff to generate dynamically

**Comment by smilefisher** [comment]
would you mind give more infomation?

**Comment by dumbbell-5kg** [comment]
> Hope to support protobuf, Use protostuff to generate dynamically

Does "dynamic generation" mean that when your class fields change, using protostuff can generate new protobuf bytes?

**Comment by mrniko** [comment]
Merged
