### ISSUE TITLE
RedissonLocalCachedMap.putAllOperationAsync class java.lang.Integer cannot be cast to class io.netty.buffer.ByteBuf

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#5201]
Hi,
**Expected behavior**
No exception thrown
**Actual behavior**
RedissonLocalCachedMap.putAll throw class java.lang.Integer cannot be cast to class io.netty.buffer.ByteBuf
**Steps to reproduce or test case**
`rLocalCachedMap1 = redissonClient.getLocalCachedMap("znMapTest1", LocalCachedMapOptions.defaults()
                .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
                .cacheSize(0)
                .syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE)
                .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.NONE)
                .writeMode(MapOptions.WriteMode.WRITE_BEHIND));
        Map<String, String> map = new HashMap<>();
        map.put("test", "123");
        rLocalCachedMap1.putAll(map);`
**Redisson version**
3.23.1
**Redisson configuration**
Thanks

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by lehuuthanh5** [comment]
Hi @mrniko, May I know when is 3.23.2 released?
Thanks

**Comment by mrniko** [comment]
@lehuuthanh5 

Hi,
It has already been released.

**Comment by lehuuthanh5** [comment]
Thanks
