### ISSUE TITLE
How to monitor drift/replication lag between nodes in LocalCachedMap?

### ISSUE THREAD

**Issue by nvinhphuc** [redisson/redisson#5204]
Using LocalCachedMap with LOCALCACHE only mode (without data stored in Redis)
Question 1: Is there any way to monitor drift between nodes? 
Question 2: How can we know if a node is out of sync and behind other node? (So we can quickly remove the out-of-sync node)

**Comment by lehuuthanh5** [comment]
What is the node that you mean? It is Redis node or your application node?

**Comment by nvinhphuc** [comment]
> What is the node that you mean? It is Redis node or your application node?

I mean the Redisson clients

**Comment by lehuuthanh5** [comment]
Redisson does not have any implementation that supports monitoring replication lag between nodes. You may need to track slow logs on the Redis server.
To check if a node is out of sync:
- You can use `LocalCacheUpdateListener` and `LocalCacheInvalidateListener` to monitor changes on local cache updates.
- You can run a job to compare values between the local cache and the Redis server (I'm using this way). The Redis Server data is always updated.
Anyway, the Redisson on RLocalCachedMap is more stable now. Please try the latest Redisson version, and keep updating if it has any change

**Comment by mrniko** [comment]
> Is there any way to monitor drift between nodes?

No.

> How can we know if a node is out of sync and behind other node? (So we can quickly remove the out-of-sync node)

This can be possible due to network issues. Use ReconnectionStrategy = CLEAR or LOAD to resolve this.
