### ISSUE TITLE
Do LOCALCACHE StoreMode in RedissonLocalCachedMap guarantee eventual consistency between Redisson clients?

### ISSUE THREAD

**Issue by nvinhphuc** [redisson/redisson#5206]
In my use case, I need to use LOCALCACHE mode only (without saving data in Redis). I see that RedissonLocalCachedMap use Redis pub/sub, which as I know is not reliable, so I wonder if LOCALCACHE StoreMode in RedissonLocalCachedMap guarantee eventual consistency between Redisson clients?

**Comment by nvinhphuc** [comment]
Ok, I tested it and seems like the node has to be alive when another node publishes the change if it want to receive the update.

**Comment by mrniko** [comment]
You can set `reconnectionStrategy` setting to LOAD so that you don't miss missed updates

**Comment by nvinhphuc** [comment]
> You can set `reconnectionStrategy` setting to `LOAD` so that you don't miss missed updates

Does the `reconnectionStrategy` work with `SyncStrategy.Update`, cause I tested it and it doesn't work.
