### ISSUE TITLE
Sync all data from Redis map into local cache map using RLocalCachedMap

### ISSUE THREAD

**Issue by nvinhphuc** [redisson/redisson#5207]
In our use case, we need to keep the consistency of the local cache within a small interval (5s). Do we have any way to sync all the data in Redis to local cache in LOCALCACHE_REDIS mode?

**Comment by mrniko** [comment]
You can update them using RTransaction.getLocalCachedMap() object. It guarantees that every instance will be updated but it will be slow.

**Comment by nvinhphuc** [comment]
Is there any way to do it for single instance? As it somehow keep other nodes availability and eventually reach consistency.

**Comment by nvinhphuc** [comment]
Ah, I mean for the `RTransaction.getLocalCachedMap()`, does it block the access to the local cache when it happen?

**Comment by nvinhphuc** [comment]
Seems like when an instance is disconnected with Redis, all the cached data is cleared and we currently doesn't have any method to rebuild the cached data with Redis data.
Our use case is to build something like replicated local cache. So 2 things that important is:
- A `reconnectionStrategy.LOAD_FROM_REDIS`
- `RLocalCached.loadAllFromRedis()` method

**Comment by nvinhphuc** [comment]
Hmm, after more testing, I can load data from Redis using `RLocalCachedMap.getAll(RLocalCachedMap.keySet)`.
However, seems like all the `ReconnectionStrategy` does not support to load from Redis when reconnecting.

**Comment by nvinhphuc** [comment]
Ok, after testing, I can do things like this:
```
val transaction = redisson.createTransaction(TransactionOptions.defaults())
val tCache = transaction.getLocalCachedMap(cache)
tCache.getAll(tCache.keySet())
transaction.commit()
```

However, seems like we don't have any options to load from Redis for `ReconnectionStrategy`?

**Comment by nvinhphuc** [comment]
I see, it also has `readAllMap()` which loads all entries from Redis. However, does this result in "dirty read"?

**Comment by mrniko** [comment]
> Another I can think of is to use cache.getAll(cache.keySet), which might result in inconsistency between nodes.

This is why synchronization mode is used in INVALIDATE or UPDATE mode.

> However, does this result in "dirty read" and does it flood the Redis pub/sub topic?

There are no dirty reads if you don't use Redisson transactions. No pub/sub flood.
