### ISSUE TITLE
why cancel connectionFuture?

### ISSUE THREAD

**Issue by kfbug365** [redisson/redisson#5215]
Redisson  version：3.20.1

RedisExecutor execute
![image](https://github.com/redisson/redisson/assets/49931739/0cbeae1b-efed-43f4-92c1-82025880e276)
![image](https://github.com/redisson/redisson/assets/49931739/6ac7b221-5f88-4b2a-867d-fb98a975d021)

why cancel connectionFuture?it means cancel this redis connection or it throw exception?

**Comment by mrniko** [comment]
to execute logic below:

```java
            if (connectionFuture.isCancelled()) {
                connectionManager.getServiceManager().getShutdownLatch().release();
                return;
            }
```

**Comment by kfbug365** [comment]
> to execute logic below:
> 
> ```java
>             if (connectionFuture.isCancelled()) {
>                 connectionManager.getServiceManager().getShutdownLatch().release();
>                 return;
>             }
> ```

if command can not execute finally，the connectionFuture cancel, it will feedback “Unable to acquire connection!”，Is that correct？

**Comment by mrniko** [comment]
That's correct. It means you need to increase connection pool

**Comment by kfbug365** [comment]
> That's correct. It means you need to increase connection pool

Is there any other cause “Unable to acquire connection!” ? Such as  command execute over timeout config or redis server response over timeout config（default 3 seconds）
