### ISSUE TITLE
Unable to send PING command over channel

### ISSUE THREAD

**Issue by aslammohammd** [redisson/redisson#5217]
We are using spring boot 3.1.2 reactive(spring-boot-starter-webflux) with org.redisson:redisson-spring-boot-starter:3.20.0.

We recently migrated from azure to GCP and started facing error saying 'Unable to send PING command over channel'.

**2023-08-01 06:59:10,450 [redisson-timer-5-1] ERROR o.r.c.handler.PingConnectionHandler  - Unable to send PING command over channel: [id: 0x8a006106, L:/10.200.0.10:44816 - R:post-order-redis.pp.xxxxx.in/10.210.1.139:6379]**

The same code was working fine with azure managed vm but automatically broken on GCP vm. Please help. Thanks

**Comment by mrniko** [comment]
It seems to be an environment issue? Did you try to recreate GCP Redis and app node?

**Comment by aslammohammd** [comment]
Yes also tried running application on k8s, same error is coming.

**Comment by mrniko** [comment]
is it possible that wrong ip address resolved by the host name?

**Comment by rookieOfIT** [comment]
I met the same problem as you, my redisson version is 3.18.0, 3.17.3. All containers on k8s report errors：Unable to send PING command over channel

**Comment by mrniko** [comment]
You can set `pingConnectionInterval` = 0 to disable if it doesn't work in this environment.

**Comment by mrniko** [comment]
Can you share full stacktrace?
