### ISSUE TITLE
Unable to acquire subscription lock after upgrading to Redisson 3.23.1

### ISSUE THREAD

**Issue by ipalbeniz** [redisson/redisson#5219]
When we upgraded Redisson from version 3.23.0 to 3.23.1 our application started crashing with this error message:
```
Unable to acquire subscription lock after 33000ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
```

Our application uses the default values for timeout, subscriptionsPerConnection and subscriptionConnectionPoolSize. Furthermore, we have verified that these values are not changed between versions 3.23.0 and 3.23.1

Our application uses Redisson Local Cache for Map.

**Expected behavior**

Our application should run without "Unable to acquire subscription lock" errors.

**Actual behavior**

The application crashes with "Unable to acquire subscription lock" error after a few seconds of execution.

**Steps to reproduce or test case**

Upgrade Redisson from version 3.23.0 to 3.23.1 and use Local Cache for Map, after a while some "Unable to acquire subscription lock" errors should appear.

**Redis version**

6.2.6

**Redisson version**

3.23.1

**Redisson configuration**

- Replicated servers 
- 3 nodes
- readMode: MASTER_SLAVE
- timeout: 3000
- subscriptionConnectionPoolSize: 50
- subscriptionsPerConnection: 5

**Comment by mrniko** [comment]
fixed in 3.23.3
