### ISSUE TITLE
Why is it that when I use RedissonMultiLock, when a redis machine breaks down, the lock cannot be used all the time, and I need to reconnect the broken machine before I can continue to use it

### ISSUE THREAD

**Issue by HFFZZZ** [redisson/redisson#5220]
This is my java code

java
config
@Value("${redisson.single.address1}")
    private String address1;
    @Value("${redisson.single.address2}")
    private String address2;
    @Value("${redisson.single.address3}")
    private String address3;

    @Bean("redissonClient1")
    public RedissonClient redissonClient1() {
        Config config = new Config();
        config.useSingleServer()
                .setDatabase(0)
                .setAddress(address1)
                .setTimeout(3000);
        return Redisson.create(config);
    }
    @Bean("redissonClient2")
    public RedissonClient redissonClient2() {
        Config config = new Config();
        config.useSingleServer()
                .setDatabase(0)
                .setAddress(address2)
                .setTimeout(3000);
        return Redisson.create(config);
    }
    @Bean("redissonClient3")
    public RedissonClient redissonClient3() {
        Config config = new Config();
        config.useSingleServer()
                .setDatabase(0)
                .setAddress(address3)
                .setTimeout(3000);
        return Redisson.create(config);
    }

    @Bean
    public RedissonMultiLock redissonMultiLock(){
        Config config = new Config();
        config.useClusterServers().addNodeAddress(address1,address2,address3);
        return new RedissonMultiLock(
                redissonClient1().getLock("redissonLock"),
                redissonClient2().getLock("redissonLock"),
                redissonClient3().getLock("redissonLock"));
    }

service
@Autowired
    private RedissonMultiLock redissonMultiLock;

    public String buyRedissonMultiLock() {
        String message = "";
        redissonMultiLock.lock();
        try {
             log.info("redissonLock be in use")
             message="redissonLock be in use";
            Thread.sleep(30000);
        } finally {
            redissonMultiLock.unlock();
        }
        return message;
    }

If one of the redis is down, it will cause that the lock cannot be used all the time. The machine that is down needs to restart to use the lock normally, otherwise it will always be blocked

**Comment by mrniko** [comment]
That's expected since all locks should be acquired to mark RedissonMultiLock as aquired.

**Comment by HFFZZZ** [comment]
@mrniko Thank you. I thought the redisson distributed lock was fault tolerant

**Comment by mrniko** [comment]
@HFFZZZ 

It is. If multilock is used then all locks should be acquired.
