### ISSUE TITLE
Is it normal that a thread can get the lock before lease time had past?

### ISSUE THREAD

**Issue by cuipengfei** [redisson/redisson#5221]
```mermaid
sequenceDiagram
    thread 1->>+redisson: try get lock, wait 20, lease time 20
    redisson-->>-thread 1: ok

    thread 1->>thread 1:runs for 15 seconds

    thread 2->>+redisson: try get lock, wait 20, lease time 20
    redisson-->>-thread 2: immediate ok

    note over redisson,thread 2:is this normal? lease time has not past yet<br>shouldn't thread 2 wait for 5 seconds then get the lock?
   
```

https://github.com/cuipengfei/Spikes/blob/22a9896137dd62bda5f030f5a3d33c67fba67310/jpa/spring-jdbc-distributed-lock-issue/src/test/java/com/github/spring/example/LockTest.java#L38C9-L49

the above junit test can reproduce this.

```shell
docker run -p 6379:6379 -d redis:7.0.12 --requirepass "mypass"

docker run -e POSTGRES_USER=localtest -e POSTGRES_PASSWORD=localtest -e POSTGRES_DB=orders -p 5432:5432 -d postgres:15.3

# start this docker container before running the above junit test
```

If I run these 2 threads in 2 jvms, then the lease thread 2 can only get lock after lease time is past.
But if I run them in the same jvm, then thread 2 can get lock before lease time is past.

Is this by design?

**Comment by mrniko** [comment]
RLock object is re-entrant. Same thread can get acquire the same lock multiple times. You can check that the second thread is the same thread.

**Comment by cuipengfei** [comment]
> https://github.com/cuipengfei/Spikes/blob/22a9896137dd62bda5f030f5a3d33c67fba67310/jpa/spring-jdbc-distributed-lock-issue/src/test/java/com/github/spring/example/LockTest.java#L38C9-L49

It is not.

You can run this code to reproduce: https://github.com/cuipengfei/Spikes/blob/22a9896137dd62bda5f030f5a3d33c67fba67310/jpa/spring-jdbc-distributed-lock-issue/src/test/java/com/github/spring/example/LockTest.java#L38C9-L49  

This code's log output shows thread numbers, they are different.

**Comment by cuipengfei** [comment]
Just ran the junit test again, it is strange, this time thread 2 only gets the lock after lease time of thread 1 is past, which makes sense.

Not sure why the results were different previously.

**Comment by mrniko** [comment]
Unable to reproduce with the code below.

```java
        Thread t1 = new Thread() {
            @Override
            public void run() {
                RLock lock = redisson.getLock("lock");
                try {
                    if (lock.tryLock(20, 20, TimeUnit.SECONDS)) {
                        System.out.println("acquired " + Instant.now() + " " + Thread.currentThread().getName());
                    } else {
                        System.out.println("unable to acquire " + Instant.now() + " " + Thread.currentThread().getName());
                    }
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
        };

        Thread t2 = new Thread() {
            @Override
            public void run() {
                RLock lock = redisson.getLock("lock");
                try {
                    if (lock.tryLock(20, 20, TimeUnit.SECONDS)) {
                        System.out.println("acquired " + Instant.now() + " " + Thread.currentThread().getName());
                    } else {
                        System.out.println("unable to acquire " + Instant.now() + " " + Thread.currentThread().getName());
                    }
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
        };

        t1.start();
        t2.start();

        Thread.sleep(60000);
```

**Comment by cuipengfei** [comment]
> Unable to reproduce with the code below.
> 
> ```java
>         Thread t1 = new Thread() {
>             @Override
>             public void run() {
>                 RLock lock = redisson.getLock("lock");
>                 try {
>                     if (lock.tryLock(20, 20, TimeUnit.SECONDS)) {
>                         System.out.println("acquired " + Instant.now() + " " + Thread.currentThread().getName());
>                     } else {
>                         System.out.println("unable to acquire " + Instant.now() + " " + Thread.currentThread().getName());
>                     }
>                 } catch (InterruptedException e) {
>                     throw new RuntimeException(e);
>                 }
>             }
>         };
> 
>         Thread t2 = new Thread() {
>             @Override
>             public void run() {
>                 RLock lock = redisson.getLock("lock");
>                 try {
>                     if (lock.tryLock(20, 20, TimeUnit.SECONDS)) {
>                         System.out.println("acquired " + Instant.now() + " " + Thread.currentThread().getName());
>                     } else {
>                         System.out.println("unable to acquire " + Instant.now() + " " + Thread.currentThread().getName());
>                     }
>                 } catch (InterruptedException e) {
>                     throw new RuntimeException(e);
>                 }
>             }
>         };
> 
>         t1.start();
>         t2.start();
> 
>         Thread.sleep(60000);
> ```

I can not reproduce this again with my own code either.
I guess the first time when I saw this issue, there might be something wrong with my code or env.
Should be ok to close this ticket.

**Comment by cuipengfei** [comment]
https://stackoverflow.com/questions/76856466/spring-integration-distributed-locks-conceptual-consistency-of-ttl-as-compared

@mrniko  @jackygurui   It would be much appreciated if you could take a look at the above stackoverflow question, which is trying to find out the design rationale of Redisson's lease time vs Spring Integration's TTL. 

I have written down my own interpretation in the SO question, it could very well be off the mark since I am not that famaliar with the source code of both libs. Would be great to get your thoughts on this question.
