### ISSUE TITLE
Each AddressResolver uses a different DNSCache instance

### ISSUE THREAD

**Issue by adamleantech** [redisson/redisson#5222]
We have a Redis Sentinel setup and use RedissonClient to connect to this.  All AddressResolverGroupFactory implementations provided by the library have implementations that do not share a DNSCache instance between AddressResolverGroup instances (see use of DnsAddressResolverGroup).  The impact of this is that we observe a lot of unnecessary DNS queries to resolve the addresses of the sentinel nodes from their configured hostnames (note that Netty does not use the JVM DNS cache).

One solution would be to update SequentialDnsAddressResolverFactory to be constructed with a DNSCache instance and this is used when creating the DnsAddressResolverGroup (via its Builder).

**Comment by mrniko** [comment]
Thanks for pointing out. Done.
