### ISSUE TITLE
Redisson command get stuck after Redis failure

### ISSUE THREAD

**Issue by Mortega5** [redisson/redisson#5225]
**Expected behavior**

Throw an exception indicating that the command could not be executed successfully.

**Actual behavior**

The thread that is executing the command gets stuck because the command never finishes executing.
In the example the thread tries to send the command 3 times and then blocks and never executes again.

This problem also occurs with any command that executes synchronously or asynchronous ones that do not use a timeout (`RFuture.get()`) to get the result.

In addition, when it uses 3 sentinels and 3 redis nodes, the retry is always done against the same node. This happens even when a new master has been elected.

I think it should try it against any of the available nodes (depending on the configuration) and not always against the same one.

**Steps to reproduce or test case**

Deploy Redis using docker compose

```yaml
version: '3.7'
services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
```

Execute the following Main

```java
package test;

import org.redisson.Redisson;
import org.redisson.api.RAtomicDouble;
import org.redisson.api.RedissonClient;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class Main {

	public static void main(String[] args) {

		RedissonClient redissonClient = Redisson.create();

		String numberName = "testNumber";
		RAtomicDouble number = redissonClient.getAtomicDouble(numberName);
		number.set(0);

		ScheduledExecutorService executor =
				Executors.newSingleThreadScheduledExecutor();

		executor.scheduleAtFixedRate(() -> {
			System.out.println("Updating value");
			RAtomicDouble atomicDouble =
					redissonClient.getAtomicDouble(numberName);
			System.out.println("AtomicDouble available");
			double value = atomicDouble.addAndGet(1);
			System.out.println("Current value after update: " + value);
		}, 0L, 1000L, TimeUnit.MILLISECONDS);
	}
}
```

Once it is running we stop redis and restore it after 5 seconds (enough to do the 3 attempts).
```sh
docker-compose stop -t 0;sleep 5;docker-compose up -d redis
```

Redisson is able to reconnect but the command does not finish or run again and the thread gets stuck.

**Redis version**
6.2.6

**Redisson version**

3.23.2

**Redisson configuration**

Default Redisson configuration. The same thing also happens using 3 sentinel and 3 redis deployed in kubernetes. In this case, I used
the following configuration:

```yaml
sentinelServersConfig:
  database: 1
  masterName: master
  sentinelAddresses:
  - redis://redis-sentinel-svc:26379
```

**Comment by mrniko** [comment]
You don't catch the exception thus whole task fails. Below is the correct test.

```java
        RedissonClient redissonClient = Redisson.create();

        String numberName = "testNumber";
        RAtomicDouble number = redissonClient.getAtomicDouble(numberName);
        number.set(0);

        ScheduledExecutorService executor =
                Executors.newSingleThreadScheduledExecutor();

        executor.scheduleAtFixedRate(() -> {
            try {
                System.out.println("Updating value");
                RAtomicDouble atomicDouble =
                        redissonClient.getAtomicDouble(numberName);
                System.out.println("AtomicDouble available");
                double value = atomicDouble.addAndGet(1);
                System.out.println("Current value after update: " + value);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, 0L, 1000L, TimeUnit.MILLISECONDS);
```
