### ISSUE TITLE
Client returns `"PONG"` for some cache keys after experiencing `RedisTimeoutException`, causing `ClassCastException` (+ potential memory leak?)

### ISSUE THREAD

**Issue by mcanalesmayo** [redisson/redisson#5227]
When having heavy load on our app, ocassionally we get some `RedisTimeoutException`'s, like below one
```
org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@55a80971[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=redis://{{OUR_MASKED_REDIS_IP}}], nodeType=MASTER, firstFail=0]]], command: null, params: null after 2 retry attempts
```

Then we start getting the following exception for many different cache keys:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class {{OUR_MASKED_CLASS}} (java.lang.String is in module java.base of loader 'bootstrap'; {{OUR_MASKED_CLASS}} is in unnamed module of loader 'app')
```

We've been experiencing this for at least 4 years, so recently we added some logs before another load test, and found out that Redisson is in these cases returning a string `"PONG"` instead of the actual object stored in the Redis cache.

The same app is deployed to many nodes and all of them read the same cache keys, but the `ClassCastException` only happens in the nodes where we got the `RedisTimeoutException`. These are the symptoms in those "misbehaving" nodes even 24h after load test is finished and load on the app is back to normal:
- `ClassCastException` keeps happening some times even a few hours after the load on the app decreased to normal values
- Mean response time for Redis requests are very high forever, between 100x-500x more than usual, depending on the object type
- Number of file descriptors increases by 10% and stays like that forever
- Memory pattern changes significantly forever, GC runs much more frequently

It looks like there could be a memory leak.
We usually have to manually restart these "misbehaving" nodes as a fix.

May be related to this issue https://github.com/redisson/redisson/issues/3927

**Expected behavior**
Object stored in Redis returned for all cache keys.

**Actual behavior**
String "PONG" returned for some of the cache keys, only happening in specific faulty nodes.

**Steps to reproduce or test case**
Cannot reproduce, it happens intermittently when having heavy load triggering many requests to Redis.

**Redis version**
3.2.8

**Redisson version**
3.17.6, with codec Kryo 5.3.0

**Redisson configuration**
```
connectTimeout = 10000
timeout = 200
retryInterval = 50
retryAttempts = 4
masterConnectionMinimumIdleSize = 24
masterConnectionPoolSize = 64
slaveConnectionMinimumIdleSize = 24
slaveConnectionPoolSize = 64
keepAlive = true
tcpNoDelay = true
readMode = MASTER_SLAVE
nodeAddresses = [ {{18 Redis nodes}} ]
```

**Comment by mrniko** [comment]
Can you try 3.19.2 version? it has a fix for "command replies don't match if exception is thrown in CommandEncoder" issue

**Comment by mrniko** [comment]
I will wait for your feedback

**Comment by mcanalesmayo** [comment]
@mrniko we upgraded to 3.23.2 and had another load test, it did not happen this time
I'll close this issue, thanks for your support
