### ISSUE TITLE
How to set codec in redisson-spring-data-27

### ISSUE THREAD

**Issue by purti-rajpal** [redisson/redisson#5228]
Hi,
Please let me know how to set up codec in redisson-spring-data library.

I have added below dependency to the project:
implementation 'org.redisson:redisson-spring-data-27:3.18.0'

I need to test Kryo5Codec and I have set it via redisson config, but I dont think it is picking up the codec. 
Is SringCodec overriding the config settings. 

Thanks.

**Comment by mrniko** [comment]
It can be set through redisson config.

**Comment by purti-rajpal** [comment]
Below are the config settings that we are doing. Can you please check once. 
config.useClusterServers().setReadMode(ReadMode.MASTER_SLAVE);
config.setCodec(new Kryo5Codec());

**Comment by mrniko** [comment]
this config is enough. Can you share the code to reproduce the issue?
