### ISSUE TITLE
Create Cache Issue -Multi Node issue

### ISSUE THREAD

**Issue by atiwari-hw** [redisson/redisson#5229]
Currently we are using JCache implementation through Redisson in a multi node application. We create cache when each application node is started. 

**Expected behavior**

The expected behaviour is that one node should create the cache and rest of the nodes should get `CacheException` while getting started as the previous node has already created the cache with that name. Refer - `org.redisson.jcache.JCacheManager#createCache`

**Actual behavior**
All the application nodes are able to create the cache successfully with the same name. We are not getting the exception.  
This is how we are initializing and creating a cache - 
```
 private static final CacheManager cacheManager =
            Caching.getCachingProvider(JCachingProvider.class.getName()).getCacheManager();
 MutableConfiguration<String, byte[]> jcacheConfig = new MutableConfiguration<String, byte[]>()
                .setTypes(String.class, byte[].class)
                .setExpiryPolicyFactory((Factory<ExpiryPolicy>) () -> new CreatedExpiryPolicy(timeToLive))
                .setStatisticsEnabled(true)
                .setManagementEnabled(true)
                .setStoreByValue(true);
 Configuration<String, byte[]> configuration =
                RedissonConfiguration.fromInstance(CacheClientConfiguration.getRedissonClient(), jcacheConfig);
Cache<String, byte[]> cache = cacheManager.createCache(cacheName, configuration);

```

We are suspecting it could be because you check the existence of a cache against a map which is not distributed. we are referring to this map -  
```
org.redisson.jcache.JCacheManager#caches

```

**Steps to reproduce or test case**
- Create a cache in multi node environment. Use at least two application node with the same code. 

**Redis version**
- 7.0.11

**Redisson version**
- 3.19.0

**Redisson configuration**

**Comment by agupta-hw** [comment]
@mrniko Could you please let us know if this is an intentional behavior?

**Comment by mrniko** [comment]
> The expected behaviour is that one node should create the cache and rest of the nodes should get CacheException while getting started as the previous node has already created the cache with that name

This check is implemented for the same JVM only. According to the specification.

**Comment by atiwari-hw** [comment]
@mrniko For a DistributedCache, CacheManager interface doesn't seem to be distributed. When we do createCache() it doesn't throw exception even though the cache exists in Redis. The getCache() also fails as it doesn't exist in that HashMap but the cache exists in Redis. 

This means CacheException will never be thrown in a Distributed Environment for any Production Use cases. All the methods where we try to get hold of the Cache are failing since the Cache object reference is not deterministic in every node. For nodes that have it, it works but others it doesn't which means our code is not reliable.
