### ISSUE TITLE
Getting startup error when trying out TomcatSessionManager

### ISSUE THREAD

**Issue by manaspandey45** [redisson/redisson#5233]
Caused by: java.lang.LinkageError: loader constraint violation:
when resolving method "io.reactivex.Flowable.fromPublisher(Lorg/reactivestreams/Publisher;)Lio/reactivex/Flowable;"
the class loader (instance of org/apache/catalina/loader/ParallelWebappClassLoader) of the current class,
org/springframework/core/ReactiveAdapterRegistry$RxJava2Registrar, and the class loader (instance of java/net/URLClassLoader)
for the method's defining class, io/reactivex/Flowable, have different Class objects for the type org/reactivestreams/Publisher used in the signature

**Comment by mrniko** [comment]
You need to check your classpath. It may have different versions of the same library.
