### ISSUE TITLE
Connection fails with enabled lazyLoading feature

### ISSUE THREAD

**Issue by DovydasJur** [redisson/redisson#5236]
**Expected behavior**
Redisson should be able to connect to Redis even if it was unreachable during application startup.

**Actual behavior**
Redisson fails to connect to Redis cluster. Exception is thrown:
`Aug  8 14:45:17 ip-10-4-55-182 server: org.redisson.client.RedisConnectionException: Can't connect to servers!
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.connection.ReplicatedConnectionManager.connect(ReplicatedConnectionManager.java:102)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.connection.MasterSlaveConnectionManager.lazyConnect(MasterSlaveConnectionManager.java:171)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.connection.MasterSlaveConnectionManager.getEntry(MasterSlaveConnectionManager.java:402)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.connection.MasterSlaveConnectionManager.getWriteEntry(MasterSlaveConnectionManager.java:409)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.command.RedisExecutor.getEntry(RedisExecutor.java:778)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.command.RedisExecutor.connectionWriteOp(RedisExecutor.java:750)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:672)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:535)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:499)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:777)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.RedissonMap.putAllAsync(RedissonMap.java:716)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.RedissonMap.putAll(RedissonMap.java:669)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.tomcat.RedissonSession.save(RedissonSession.java:428)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.tomcat.RedissonSessionManager.add(RedissonSessionManager.java:226)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.session.StandardSession.setId(StandardSession.java:359)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.session.StandardSession.setId(StandardSession.java:342)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.session.ManagerBase.createSession(ManagerBase.java:695)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.redisson.tomcat.RedissonSessionManager.createSession(RedissonSessionManager.java:133)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.connector.Request.doGetSession(Request.java:3143)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.connector.Request.getSession(Request.java:2507)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)
Aug  8 14:45:17 ip-10-4-55-182 server: at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:908)
Aug  8 14:45:17 ip-10-4-55-182 server: at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)
Aug  8 14:45:17 ip-10-4-55-182 server: at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)`

**Steps to reproduce or test case**
1. Make sure that Redis is not available.
2. Start application with lazyLoading = true.
3. Spin up the Redis cluster.
4. Try to make connection to Redis from application. (Without restarting app)

**Redis version**
6.2.6

**Redisson version**
3.23.0

**Redisson configuration**
replicatedServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 7000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 30000
  failedSlaveCheckInterval: 60000
  subscriptionsPerConnection: 5
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "rediss://xxx"
  scanInterval: 1000
  dnsMonitoringInterval: 5000
  monitorIPChanges: true
threads: 16
nettyThreads: 256
lazyInitialization: true
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Unable to reproduce it. Below is the test.

```java
        Config config = new Config();
        config.setLazyInitialization(true);
        config.useClusterServers()
                .setConnectTimeout(10000)
                .setTimeout(7000)
                .setReadMode(ReadMode.SLAVE)
                .setScanInterval(1000)
                .setSubscriptionMode(SubscriptionMode.SLAVE)
                .addNodeAddress("redis://127.0.0.1:6890");

        RedissonClient redisson = Redisson.create(config);
        assertThat(redisson).isNotNull();

        Thread.sleep(5000);

        System.out.println("start Redis");

        RedisRunner master1 = new RedisRunner().port(6890).randomDir().nosave();
        RedisRunner master2 = new RedisRunner().port(6891).randomDir().nosave();
        RedisRunner master3 = new RedisRunner().port(6892).randomDir().nosave();
        RedisRunner slave1 = new RedisRunner().port(6900).randomDir().nosave();
        RedisRunner slave2 = new RedisRunner().port(6901).randomDir().nosave();
        RedisRunner slave3 = new RedisRunner().port(6902).randomDir().nosave();

        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slave1)
                .addNode(master2, slave2)
                .addNode(master3, slave3);
        ClusterProcesses process = clusterRunner.run();

        RBucket<String> b = redisson.getBucket("test");
        b.set("1");
        for (int i = 0; i < 10; i++) {
            assertThat(b.get()).isEqualTo("1");
        }

        redisson.shutdown();
```

**Comment by mrniko** [comment]
Unable to reproduce it. Below is the test.

```java
        Config config = new Config();
        config.setLazyInitialization(true);
        config.useReplicatedServers()
                .setConnectTimeout(10000)
                .setTimeout(7000)
                .setReadMode(ReadMode.SLAVE)
                .setScanInterval(1000)
                .setSubscriptionMode(SubscriptionMode.SLAVE)
                .addNodeAddress("redis://127.0.0.1:6379", "redis://127.0.0.1:6380", "redis://127.0.0.1:6381");

        RedissonClient redisson = Redisson.create(config);
        assertThat(redisson).isNotNull();

        Thread.sleep(5000);

        System.out.println("start Redis");

        RedisRunner.RedisProcess master = new RedisRunner()
                .nosave()
                .randomDir()
                .run();
        RedisRunner.RedisProcess slave1 = new RedisRunner()
                .port(6380)
                .nosave()
                .randomDir()
                .slaveof("127.0.0.1", 6379)
                .run();
        RedisRunner.RedisProcess slave2 = new RedisRunner()
                .port(6381)
                .nosave()
                .randomDir()
                .slaveof("127.0.0.1", 6379)
                .run();
        RedisRunner.RedisProcess sentinel1 = new RedisRunner()
                .nosave()
                .randomDir()
                .port(26379)
                .sentinel()
                .sentinelMonitor("myMaster", "127.0.0.1", 6379, 2)
                .run();
        RedisRunner.RedisProcess sentinel2 = new RedisRunner()
                .nosave()
                .randomDir()
                .port(26380)
                .sentinel()
                .sentinelMonitor("myMaster", "127.0.0.1", 6379, 2)
                .run();
        RedisRunner.RedisProcess sentinel3 = new RedisRunner()
                .nosave()
                .randomDir()
                .port(26381)
                .sentinel()
                .sentinelMonitor("myMaster", "127.0.0.1", 6379, 2)
                .run();

        RBucket<String> b = redisson.getBucket("test");
        b.set("1");
        for (int i = 0; i < 10; i++) {
            assertThat(b.get()).isEqualTo("1");
        }

        redisson.shutdown();
```
