### ISSUE TITLE
How do I get a value from RTimeSeries<V,L> when I added using RTimeSeries<V> object. 

### ISSUE THREAD

**Issue by swapnil2001-master** [redisson/redisson#5242]
I tried to update my redisson version but stuck at this.
Facing this error
org.redisson.client.RedisException: ERR Error running script @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short).

**Comment by mrniko** [comment]
RTimeSeries format has been changed since 3.18.0 version

**Comment by swapnil2001-master** [comment]
So I cannot get the previous data using this version

**Comment by mrniko** [comment]
I can suggest you to store data using `org.redisson.api.RTimeSeries#entryRange(long, long)` into elsewhere and then using a new version store it back using `org.redisson.api.RTimeSeries#add(long, V)` method.
