### ISSUE TITLE
does `MapWriter` acquire distributed lock?

### ISSUE THREAD

**Issue by SHxKM** [redisson/redisson#5250]
I'm trying to understand if `MapWriter` acquires a distributed lock when the `write()` method is called. 

I've got a microservice with N instances and my write behind cache should support both `Db.create()` and `Db.update()` operations.

My (non-scientific) tests are non conclusive.

When I run multiple instances, sometimes it seems that Redisson _is_ acquire a distributed lock to prevent other `write()` methods for running, and then if the `write()` method that acquired is taking too long, will call it from another instance.

But in other tests it seems that two different instances can access the `write()` method concurrently.

So is there any distributed locking happening here?

**Edit:** after some further testing it seems that the `write()` method does not acquire any distributed locks and is therefore single-threaded only in the context of 1 instance. 

What are my options here in case two instances are racing to create the same object? Write through is not an option since it’s going to result in too many separate DB calls.

**Comment by SHxKM** [comment]
It seems like it may be possible to do leader election (so only 1 instance runs `write()`) here with overriding `WriteBehindService`? however the API doesn't expose a `MapOptions` ctor that allows overriding it.

**Comment by SHxKM** [comment]
I guess, in other words, is I wish that the map sent to the write() method was itself a shared object somewhere in Redis.

**Comment by SHxKM** [comment]
@mrniko would holding `RMap<String, RBucket<MyObj>>` instead of `RMap<String, MyObj>` make any difference here?

**Comment by mrniko** [comment]
@SHxKM 

No, you can acquire redisson lock right in the org.redisson.api.map.MapWriterAsync#write() method.

**Comment by SHxKM** [comment]
@mrniko Thanks, that still does not guarantee though that the `write()` acquiring the lock second, will not see that a certain object is not in `NOT_IN_DB` (and therefore it needs to create it), after the first lock-acquirer has already created it and changed its status to `IN_DB`. `map` is not backed by the real map it's just a snapshot/diff at a certain time so we're gonna have to look at an alternative method. Any ideas? A queue maybe?

**Comment by mrniko** [comment]
if you use the same Redisson lock sharing the same name then it should work.
