### ISSUE TITLE
RedissonBoundedBlockingQueue  delete  bug

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#5253]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**
![image](https://github.com/redisson/redisson/assets/31852897/75617f85-3690-49db-8b41-655b142a0e96)
![image](https://github.com/redisson/redisson/assets/31852897/cc30c829-58d6-4f23-9045-bd7b8e3a3f69)

**Redis version**
6.2.6

**Redisson version**
3.23.1

**Redisson configuration**

**Comment by mrniko** [comment]
Unable to reproduce. You need to provide the test code

**Comment by JavaLionLi** [comment]
> Unable to reproduce. You need to provide the test code

RedissonBoundedBlockingQueue.delete is not added NameMapper

**Comment by JavaLionLi** [comment]
> Unable to reproduce. You need to provide the test code

set NameMapper after , key of delete is inconsistent with that of try.
Failed to set capacity again after deletion
![image](https://github.com/redisson/redisson/assets/31852897/845c32e2-4549-4b0c-898f-73908f3c6edb)

**Comment by mrniko** [comment]
KeyPrefixHandler isn't a part of Redisson. Please share the code instead of screenshots.

**Comment by JavaLionLi** [comment]
> KeyPrefixHandler isn't a part of Redisson. Please share the code instead of screenshots.

NameMapper spliced a prefix

```
public class KeyPrefixHandler implements NameMapper {

    private final String keyPrefix;

    public KeyPrefixHandler(String keyPrefix) {
        //前缀为空 则返回空前缀
        this.keyPrefix = StringUtils.isBlank(keyPrefix) ? "" : keyPrefix + ":";
    }

    /**
     * 增加前缀
     */
    @Override
    public String map(String name) {
        if (StringUtils.isBlank(name)) {
            return null;
        }
        if (StringUtils.isNotBlank(keyPrefix) && !name.startsWith(keyPrefix)) {
            return keyPrefix + name;
        }
        return name;
    }

    /**
     * 去除前缀
     */
    @Override
    public String unmap(String name) {
        if (StringUtils.isBlank(name)) {
            return null;
        }
        if (StringUtils.isNotBlank(keyPrefix) && name.startsWith(keyPrefix)) {
            return name.substring(keyPrefix.length());
        }
        return name;
    }

}
```

**Comment by JavaLionLi** [comment]
After adding the prefix, there is really a problem with deleting it. One less data was deleted, resulting in the inability to reallocate capacity. I hope this can be fixed

**Comment by mrniko** [comment]
Fixed. Thanks for report
