### ISSUE TITLE
Unable to acquire connection, disappears after a period of stable operation

### ISSUE THREAD

**Issue by XuLeiGithub** [redisson/redisson#5255]
My redis cluster have 96 master nodes、96 slave nodes.
When I start the program, it reports a large number of errors about not being able to get a connection, ranging from dozens to hundreds, on some machines very few, on others many. When the program has been started for some time, the error report will disappear.
## configuration
The redisson configuration is as follows:
`clusterServersConfig:
      connectTimeout: 1000 
      slaveConnectionMinimumIdleSize: 64
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 64
      masterConnectionPoolSize: 64
      pingConnectionInterval: 1000`
## exception
The error message is as follows:
`java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@a0845d9[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size or timeout. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=64, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=redis://172.24.20.104:6816], nodeType=MASTER, firstFail=0]]], command: null, params: null after 0 retry attempts 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) 	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423) 	at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1144) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) 	at org.redisson.client.protocol.CommandData.tryFailure(CommandData.java:87) 	at org.redisson.client.protocol.BatchCommandData.tryFailure(BatchCommandData.java:55) 	at org.redisson.command.CommandBatchService.lambda$executeAsync$6(CommandBatchService.java:281) 	at java.base/java.util.concurrent.LinkedBlockingDeque.forEachFrom(LinkedBlockingDeque.java:1323) 	at java.base/java.util.concurrent.LinkedBlockingDeque.forEach(LinkedBlockingDeque.java:1291) 	at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:281) 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) 	at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:166) 	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:524) 	at org.redisson.command.RedisExecutor.lambda$execute$4(RedisExecutor.java:176) 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) 	at org.redisson.command.RedisExecutor.lambda$scheduleConnectionTimeout$5(RedisExecutor.java:195) 	at org.redisson.connection.MasterSlaveConnectionManager$2.run(MasterSlaveConnectionManager.java:664) 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.base/java.lang.Thread.run(Thread.java:834) Caused by: org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@a0845d9[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size or timeout. Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=64, freeConnectionsCounter=value:64:queue:0, freezeReason=null, client=[addr=redis://172.24.20.104:6816], nodeType=MASTER, firstFail=0]]], command: null, params: null after 0 retry attempts 	at org.redisson.command.RedisExecutor.lambda$scheduleConnectionTimeout$5(RedisExecutor.java:192) 	... 6 more
--`
Ask for help on how to solve it😭😭😭

**Comment by mrniko** [comment]
"Increase connection pool size or timeout"

Did you do that?

**Comment by XuLeiGithub** [comment]
Yes, and we use pipeline to decrease connection. Because we find the `RedissonBuckets` use to much connections.
But now we find another question.
```
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.24.20.104/172.24.20.104:6882 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=18, freeConnectionsCounter=value:42:queue:0, freezeReason=null, client=[addr=redis://172.24.20.104:6882], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1690891941 [redisClient=[addr=redis://172.24.20.104:6882], channel=[id: 0xaf5fec8e, L:/172.23.96.11:55692 - R:172.24.20.104/172.24.20.104:6882], currentCommand=null, usage=1], command: null, params: null after 0 retry attempts
	at org.redisson.command.RedisExecutor.lambda$scheduleWriteTimeout$6(RedisExecutor.java:215)
	at org.redisson.connection.MasterSlaveConnectionManager$2.run(MasterSlaveConnectionManager.java:664)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
In log message，we find command = null, so wired. And I cannot figure out.

**Comment by XuLeiGithub** [comment]
> "Increase connection pool size or timeout"
> 
> Did you do that?

Yes, and we use pipeline to decrease connection. Because we find the `RedissonBuckets` use to much connections.
But now we find another question.
```
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Check connection with Redis node: 172.24.20.104/172.24.20.104:6882 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=18, freeConnectionsCounter=value:42:queue:0, freezeReason=null, client=[addr=redis://172.24.20.104:6882], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1690891941 [redisClient=[addr=redis://172.24.20.104:6882], channel=[id: 0xaf5fec8e, L:/172.23.96.11:55692 - R:172.24.20.104/172.24.20.104:6882], currentCommand=null, usage=1], command: null, params: null after 0 retry attempts
	at org.redisson.command.RedisExecutor.lambda$scheduleWriteTimeout$6(RedisExecutor.java:215)
	at org.redisson.connection.MasterSlaveConnectionManager$2.run(MasterSlaveConnectionManager.java:664)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
In log message，we find command = null, so wired. And I cannot figure out.

**Comment by mrniko** [comment]
RedissonBuckets uses map reduce in cluster. It may issues multiple commands per Master in Cluster per method call

**Comment by mrniko** [comment]
> command = null, so wired. And I cannot figure out

It means RBatch object usage.

**Comment by XuLeiGithub** [comment]
> > command = null, so wired. And I cannot figure out
> 
> It means RBatch object usage.

Yes, this is my usage.
```
        var rBatch = redissonClient.createBatch();
        Map<String, RFuture<V>> redisResultFutureMap = new HashMap<>(32);
        ids.stream()
            .distinct()
            .forEach(id -> {
                var key = keyConverter.apply(id);
                RBucketAsync<V> rBucket = rBatch.getBucket(key);
                redisResultFutureMap.put(key, rBucket.getAsync());
            });
        rBatch.execute();
```

**Comment by XuLeiGithub** [comment]
> > command = null, so wired. And I cannot figure out
> 
> It means RBatch object usage.

why use RBatch the command is null?

**Comment by XuLeiGithub** [comment]
> > command = null, so wired. And I cannot figure out
> 
> It means RBatch object usage.

How can I solve this problem?

**Comment by mrniko** [comment]
> > > command = null, so wired. And I cannot figure out
> > 
> > 
> > It means RBatch object usage.
> 
> why use RBatch the command is null?

Because there are multiple commands

**Comment by mrniko** [comment]
> > > command = null, so wired. And I cannot figure out
> > 
> > 
> > It means RBatch object usage.
> 
> How can I solve this problem?

Try to increase netty threads as suggested in the error

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by XuLeiGithub** [comment]
> > > > command = null, so wired. And I cannot figure out
> > > 
> > > 
> > > It means RBatch object usage.
> > 
> > 
> > How can I solve this problem?
> 
> Try to increase netty threads as suggested in the error

In my configuration. nettyThreads is 64. so I need to increase continue?

**Comment by mrniko** [comment]
> > > > > command = null, so wired. And I cannot figure out
> > > > 
> > > > 
> > > > It means RBatch object usage.
> > > 
> > > 
> > > How can I solve this problem?
> > 
> > 
> > Try to increase netty threads as suggested in the error
> 
> In my configuration. nettyThreads is 64. so I need to increase continue?

Yes, as option try to reduce batch size.

**Comment by XuLeiGithub** [comment]
> > > > > > command = null, so wired. And I cannot figure out
> > > > > 
> > > > > 
> > > > > It means RBatch object usage.
> > > > 
> > > > 
> > > > How can I solve this problem?
> > > 
> > > 
> > > Try to increase netty threads as suggested in the error
> > 
> > 
> > In my configuration. nettyThreads is 64. so I need to increase continue?
> 
> Yes, as option try to reduce batch size.

so the reason is one pipeline contains to many commands? That means we should reduce batch size?

**Comment by XuLeiGithub** [comment]
> > > > > > command = null, so wired. And I cannot figure out
> > > > > 
> > > > > 
> > > > > It means RBatch object usage.
> > > > 
> > > > 
> > > > How can I solve this problem?
> > > 
> > > 
> > > Try to increase netty threads as suggested in the error
> > 
> > 
> > In my configuration. nettyThreads is 64. so I need to increase continue?
> 
> Yes, as option try to reduce batch size.

In fact, NetyThread 64 is already large enough, do you think it needs to be increase?

**Comment by XuLeiGithub** [comment]
> > > > > > command = null, so wired. And I cannot figure out
> > > > > 
> > > > > 
> > > > > It means RBatch object usage.
> > > > 
> > > > 
> > > > How can I solve this problem?
> > > 
> > > 
> > > Try to increase netty threads as suggested in the error
> > 
> > 
> > In my configuration. nettyThreads is 64. so I need to increase continue?
> 
> Yes, as option try to reduce batch size.

How many commands would you recommend for a batch?

**Comment by mrniko** [comment]
> > > > > > > command = null, so wired. And I cannot figure out
> > > > > > 
> > > > > > 
> > > > > > It means RBatch object usage.
> > > > > 
> > > > > 
> > > > > How can I solve this problem?
> > > > 
> > > > 
> > > > Try to increase netty threads as suggested in the error
> > > 
> > > 
> > > In my configuration. nettyThreads is 64. so I need to increase continue?
> > 
> > 
> > Yes, as option try to reduce batch size.
> 
> How many commands would you recommend for a batch?

depends on data size

**Comment by XuLeiGithub** [comment]
> > > > > > > > command = null, so wired. And I cannot figure out
> > > > > > > 
> > > > > > > 
> > > > > > > It means RBatch object usage.
> > > > > > 
> > > > > > 
> > > > > > How can I solve this problem?
> > > > > 
> > > > > 
> > > > > Try to increase netty threads as suggested in the error
> > > > 
> > > > 
> > > > In my configuration. nettyThreads is 64. so I need to increase continue?
> > > 
> > > 
> > > Yes, as option try to reduce batch size.
> > 
> > 
> > How many commands would you recommend for a batch?
> 
> depends on data size

Are there any recommended data indicators? For example, how many KB/MB per batch? I understand that it also depends on the network speed

**Comment by XuLeiGithub** [comment]
> > > > > > > > > command = null, so wired. And I cannot figure out
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It means RBatch object usage.
> > > > > > > 
> > > > > > > 
> > > > > > > How can I solve this problem?
> > > > > > 
> > > > > > 
> > > > > > Try to increase netty threads as suggested in the error
> > > > > 
> > > > > 
> > > > > In my configuration. nettyThreads is 64. so I need to increase continue?
> > > > 
> > > > 
> > > > Yes, as option try to reduce batch size.
> > > 
> > > 
> > > How many commands would you recommend for a batch?
> > 
> > 
> > depends on data size
> 
> Are there any recommended data indicators? For example, how many KB/MB per batch? I understand that it also depends on the network speed

The last question, after using RBatch, I found that there were no Slowlogs counted on the Redis Cluster side. However, there will still be the error of over reporting as mentioned above. Is it because the quantity of a single batch is too large and the command is stuck locally?

**Comment by mrniko** [comment]
> > > > > > > > > command = null, so wired. And I cannot figure out
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It means RBatch object usage.
> > > > > > > 
> > > > > > > 
> > > > > > > How can I solve this problem?
> > > > > > 
> > > > > > 
> > > > > > Try to increase netty threads as suggested in the error
> > > > > 
> > > > > 
> > > > > In my configuration. nettyThreads is 64. so I need to increase continue?
> > > > 
> > > > 
> > > > Yes, as option try to reduce batch size.
> > > 
> > > 
> > > How many commands would you recommend for a batch?
> > 
> > 
> > depends on data size
> 
> Are there any recommended data indicators? For example, how many KB/MB per batch? I understand that it also depends on the network speed

It also depends on application CPU

**Comment by mrniko** [comment]
> The last question, after using RBatch, I found that there were no Slowlogs counted on the Redis Cluster side. However, there will still be the error of over reporting as mentioned above. Is it because the quantity of a single batch is too large and the command is stuck locally?

`Command still hasn't been written into connection` means that data hasn't yet been written into channel or hasn't even begun to be written

**Comment by XuLeiGithub** [comment]
> 

Thank you very much! So only writing commands can cause this error(`Command still hasn't been written into connection`), while reading command error messages is a different expression?

**Comment by XuLeiGithub** [comment]
> > > > > > > > > > command = null, so wired. And I cannot figure out
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It means RBatch object usage.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > How can I solve this problem?
> > > > > > > 
> > > > > > > 
> > > > > > > Try to increase netty threads as suggested in the error
> > > > > > 
> > > > > > 
> > > > > > In my configuration. nettyThreads is 64. so I need to increase continue?
> > > > > 
> > > > > 
> > > > > Yes, as option try to reduce batch size.
> > > > 
> > > > 
> > > > How many commands would you recommend for a batch?
> > > 
> > > 
> > > depends on data size
> > 
> > 
> > Are there any recommended data indicators? For example, how many KB/MB per batch? I understand that it also depends on the network speed
> 
> It also depends on application CPU

Thank you very much. About this we try to adjust configuration and one batch size.
