### ISSUE TITLE
lock with isCheckLockSyncedSlaves() (WAIT)

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#5256]
1. Hello i am want use lock with 'isCheckLockSyncedSlaves()' options that add WAIT and check replied slaves, but why in only ( getReadMode() == ReadMode.MASTER && getSubscriptionMode() == SubscriptionMode.MASTER), i use redis with replics but want read only from master. Can do feature or fix for work in MASTER mode ?

CommandAsyncService.java
```
   @Override
    public <T> RFuture<T> syncedEval(String key, Codec codec, RedisCommand<T> evalCommandType, String script, List<Object> keys, Object... params) {
        CompletionStage<Map<String, String>> replicationFuture = CompletableFuture.completedFuture(Collections.emptyMap());
        if (!getServiceManager().getConfig().isSlaveNotUsed()) {
            replicationFuture = writeAsync(key, RedisCommands.INFO_REPLICATION);
...<skip>...

```

2. In the case of three servers, when I set locks with the isCheckLockSyncedSlaves() option, then after the write command(lock) and the wait command will return the number of responded replicas.
If we have at least one responded replica, then at least two (master, slave) servers are alive.

But if:
1. Master send data to two replics
2. One replica answer.
3. Master return us WAIT answer reply slave = 1.
4. Master is crash.
5. Two replics electing new master.
6. Replica without our lock become new master.
7. New master synchronize with second replica with setted our lock, and erase it.
8. We acquired lock, but in redis it not present.

How to be in this situation ? Check lock variable in redis after set lock ?

**Comment by mrniko** [comment]
Done. Thanks for pointing out.

**Comment by alexworkgit** [comment]
@mrniko What about second question ? Do you know any resolution ?

P.S: Thank for add feature.

**Comment by mrniko** [comment]
Did you try to add a delay?
