### ISSUE TITLE
延迟队列到时间不消费，后端服务重启后才消费

### ISSUE THREAD

**Issue by guwenxiang** [redisson/redisson#5266]
以下是我的代码
    public <T> T getDelayQueue(@NonNull String queueCode) {
        if (StringUtils.isBlank(queueCode)) {
            return null;
        }

        RBlockingDeque<Objects> blockingDeque = redissonClient.getBlockingDeque(queueCode);
        redissonClient.getDelayedQueue(blockingDeque);
        return (T) blockingDeque.poll();
    }

**Comment by guwenxiang** [comment]
现象：线上部署两个后端服务，服务上线后，延迟任务到时间正常消费了几条，后面新建的延迟任务到点都不消费，重启其中一台后端服务后能消费到之前过期的任务，但是新建的任务到点又不消费了，又得重启后端服务才行。。。

**Comment by guwenxiang** [comment]
Phenomenon: Two monitoring services are deployed online. After the service is launched, delaying tasks until the deadline consumes several items normally. The newly created delayed tasks do not consume them until the deadline. Restarting one of the monitoring services can consume tasks before the expiration, but the newly created tasks do not consume them until the deadline, and the desktop service needs to be restarted to proceed

**Comment by guwenxiang** [comment]
问题出在redis集群，redis单机没问题

**Comment by mrniko** [comment]
how did you resolve the issue?
