### ISSUE TITLE
How to set the hash slot or node about specific key?

### ISSUE THREAD

**Issue by ReasonH** [redisson/redisson#5268]
In our production environment, we use Redis cluster (5master / 5slave). I applied RedissonRegionFactory for my Hibernate second-level entity cache. There are 8 entity caches and they should withstand a very high number of calls in production.

The problem is that we couldn't set the hash slot (or node) about entity cache. The hash slot algorithm is not interested in the actual number of entries in that entity cache (Redis HASH object), or how many entity caches exist on a node. So if a few keys are crowded on a particular node, the load will be very high.

For example, 
**Node A** 
- Entity1 / 1milion 
- Entity3 / 0.6milion

**Node B**
- No entity cache

**Node C** 
- Entity2 / 100k of entry

The Node A will go through high request.
Is there any idea?
I think an alternative would be to have the ability to specify a slot for the cache.

**Comment by mrniko** [comment]
you can migrate required Redis slots into different master nodes. https://imzye.com/NoSQL/Redis/redis-slot-migration/

**Comment by ReasonH** [comment]
Using the migrate command directly requires a separate action via the cli for each new entity added. 
Is there any chance of a related feature being added to the Redisson client?

**Comment by mrniko** [comment]
Sorry, which feature?

**Comment by mrniko** [comment]
You can try PRO version which uses data partitioning algorithm for clustered objects. This can resolve the issue.
