### ISSUE TITLE
Redisson throws "org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries." and doesn't recover

### ISSUE THREAD

**Issue by pbneamtu** [redisson/redisson#5269]
Context:
Our service is using Redisson to connect to an Azure Redis cluster. We are using the library for both caching and locking and usually thing are working as expected. 

In the past few month we updated the Redisson library version from 3.17.6 to 3.22.0 and we started to face an increased number of RedisConnectionException exceptions. 

There are times when the application throws the following Redis exception for periods of up to 45 minutes:

`org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: XX.XXX.XXX/XX.XXX.XXX:15001 Disconnected hosts: [XX.XXX.XXX/XX.XXX.XXX:15001]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:187)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:321)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:597)
	at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:745)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:669)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:317)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)`

<img width="801" alt="Screenshot 2023-08-21 at 20 09 36" src="https://github.com/redisson/redisson/assets/81512499/c0bc7872-957b-49c6-ab77-c7b968afc614">

**Expected behavior**
When both the primary and secondary Redis shards are active, the Redisson library should be able to restore the connection.

**Actual behavior**
Several Spring Boot service instances throw this error while trying to connect to a particular Redis shard instead of being able to create the connection. 

**Steps to reproduce or test case**
This incident happened either when Microsoft was updating the Host OS or during the Redis maintenance window, initially throwing `java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: XX.XXX.XXX/XX.XXX.XXX:15001` or randomly without having an update before. 

**Redis version**
6.0
Azure Redis Premium 52 GB (4 x 13 GB)

**Redisson version**
3.22.0

**Redisson configuration**
clusterServersConfig:
  idleConnectionTimeout: ${REDIS_IDLE_CONNECTION_TIMEOUT:-10000}
  connectTimeout: ${REDIS_CONNECTION_TIMEOUT:-15000}
  timeout: ${REDIS_TIMEOUT:-15000}
  retryAttempts: ${REDIS_RETRY_ATTEMPTS:-10}
  retryInterval: ${REDIS_RETRY_INTERVAL:-1500}
  failedSlaveReconnectionInterval: ${REDIS_FAILED_SLAVE_RECONNECTION_INTERVAL:-3000}
  failedSlaveCheckInterval: ${REDIS_FAILED_SLAVE_CHECK_INTERVAL:-60000}
  password: ${REDIS_PASSWORD:-null}
  subscriptionsPerConnection: ${REDIS_SUBSCRIPTIONS_PER_CONNECTION:-5}
  clientName: ${REDIS_CLIENT_NAME:-null}
  loadBalancer: ${REDIS_LOAD_BALANCER:-!<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}}
  subscriptionConnectionMinimumIdleSize: ${REDIS_SUBCRIPTION_CONNECTION_MINIMUM_IDLE_SIZE:-1}
  subscriptionConnectionPoolSize: ${REDIS_SUBSCRIPTION_POOL_SIZE:-50}
  slaveConnectionMinimumIdleSize: ${REDIS_SLAVE_CONNECTION_MINIMUM_IDLE_SIZE:-12}
  slaveConnectionPoolSize: ${REDIS_SLAVE_CONNECTION_POOL_SIZE:-64}
  masterConnectionMinimumIdleSize: ${REDIS_MASTER_CONNECTION_MINIMUM_IDLE_SIZE:-12}
  masterConnectionPoolSize: ${REDIS_MASTER_CONNECTION_POOL_SIZE:-64}
  readMode: ${REDIS_READ_MODE:-"SLAVE"}
  subscriptionMode: ${REDIS_SUBSCRIPTION_MODE:-"SLAVE"}
  scanInterval: ${REDIS_SCAN_INTERVAL:-1000}
  pingConnectionInterval: ${REDIS_PING_CONNECTION_INTERVAL:-0}
  keepAlive: ${REDIS_KEEP_ALIVE:-false}
  tcpNoDelay: ${REDIS_TCP_NO_DELAY:-false}
threads: ${REDIS_THREADS:-64}
nettyThreads: ${REDIS_NETTY_THREADS:-128}
codec: ${REDIS_CODEC:-!<org.redisson.codec.FstCodec> {}}
transportMode: ${REDIS_TRANSPORT_MODE:-"NIO"}

**Comment by mrniko** [comment]
Can you try 3.23.3 version? I fixed an issue with "SlaveConnectionPool no available Redis entries error" in 3.23.2 version.

**Comment by pbneamtu** [comment]
Sure. I will update it and monitor the services over the next few days and come back with a status.
Thanks!

**Comment by pbneamtu** [comment]
Hello!  
I updated the library to the version you mentioned and it stopped the exceptions. 
Thanks!
