### ISSUE TITLE
Why bloomfilter max size is Integer.MAX_VALUE*2

### ISSUE THREAD

**Issue by safetys123** [redisson/redisson#5270]
I want to use bloomfilter  and my expectedInsertions size is 800_000_000, and call this method tryInit() error, the error info is 
""" Bloom filter size can't be greater than " + getMaxSize() + ". But calculated size is  """
Why the maxSize is  Integer.MAX_VALUE*2
If my expectedInsertions is to big, fo example, 1B, how can I use the bloomfilter

**Comment by mrniko** [comment]
since redis object can't store more than 512Mb of data

**Comment by safetys123** [comment]
If I have 1B or 10B datas, how can I use the  redis bloomfilter ? For example, I want to save id  1~999,999,999, Can you give me  some advice ?

**Comment by mrniko** [comment]
you can use ClusteredBloomFilter in PRO version.
