### ISSUE TITLE
The stream queue documentation is too sparse to use at all

### ISSUE THREAD

**Issue by anpbszzz** [redisson/redisson#5271]
When the message has not been acked because the consumer crashed, will Redisson automatically process the pending message and send it again? Or do developers need to regularly poll pending and process pending messages by themselves?

**Comment by mrniko** [comment]
Do you mean RStream object?

**Comment by mrniko** [comment]
> When the message has not been acked because the consumer crashed, will Redisson automatically process the pending message and send it again? Or do developers need to regularly poll pending and process pending messages by themselves?

You need to request pending messages through pendingRange() method. I added into examples. Redisson doesn't know which logic should be executed before ack
