### ISSUE TITLE
Support sprint boot @ServiceConnection annotation in tests

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [redisson/redisson#5273]
**Is your feature request related to a problem? Please describe.**

In Spring Boot 3.1, test containers support has improved - https://spring.io/blog/2023/06/23/improved-testcontainers-support-in-spring-boot-3-1

Basically, this should be enough to configure a working integration test:

```java
@SpringBootTest
@Testcontainers
class MyIntegrationTests {

    @Container
    @ServiceConnection
    static Neo4jContainer<?> neo4j = new Neo4jContainer<>("neo4j:5");

    @Test
    void myTest() {
        // ...
    }

}
```

However, this doesn't work with Redisson Spring Boot starter as there are changes needed from the framework to make it work.

I haven't check the details, but it turns out that Spring Boot introduced a new class - `RedisConnectionDetails` that is an interface holding connection details. This interface is created automatically by Spring Boot whenever `ServiceConnection` annotation is used. 

**Describe the solution you'd like**

Redisson auto configuration should use `RedisConnectionDetails` when configuring connection factory.

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Fixed

**Comment by AleksanderBrzozowski** [comment]
@mrniko I don't understand how is this suppose to work 🤔 

Shouldn't you use `PropertiesRedisConnectionDetails` when creating Redisson client?

**Comment by mrniko** [comment]
How ? I think it should be just present in Spring Context.

**Comment by AleksanderBrzozowski** [comment]
Yeah, but there are two classes `RedisProperties` which holds values from `spring.data.redis` properties, and `RedisConnectionDetails` that holds only connection details. 

When `Redisson` client is created, it uses `RedisProperties` to configure connection, but it should use `RedisConnectionDetails`, right?

**Comment by mrniko** [comment]
> When Redisson client is created, it uses RedisProperties to configure connection, but it should use RedisConnectionDetails, right?

Why? RedisConnectionDetails is created from RedisProperties

**Comment by AleksanderBrzozowski** [comment]
I expect this test to connect to Redis instance on port `1234`:

```java
@SpringJUnitConfig
@SpringBootTest(classes = RedissonApplication.class)
@Import(RedissonConnectionDetailsTest.RedissonConnectionDetailsConfig.class)
public class RedissonConnectionDetailsTest {

    @TestConfiguration
    static class RedissonConnectionDetailsConfig {

        @Bean
        RedisConnectionDetails redisConnectionDetails() {
            return new RedisConnectionDetails() {
                @Override
                public Standalone getStandalone() {
                    return Standalone.of("localhost", 1234);
                }
            };
        }
    }

    @Autowired
    private RedissonClient redisson;

    @Test
    public void testConnectionDetails() {
        redisson.getConfig();
    }
}
```

However, it tries to connect to:

```
Caused by: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://localhost:6379]
```

**Comment by mrniko** [comment]
Fixed
