### ISSUE TITLE
ClusterConnectionManager.this.getLastPartitions() appear out of memory

### ISSUE THREAD

**Issue by myceciliababy** [redisson/redisson#5276]
![1](https://github.com/redisson/redisson/assets/130133943/dace6a7b-9fc0-4dc1-9ec4-c5dde8108125)
![2](https://github.com/redisson/redisson/assets/130133943/9bf7a221-0db8-452f-88ea-e5c1bca58bfd)
![3](https://github.com/redisson/redisson/assets/130133943/43b22a01-17af-4d80-baee-ff6a13a32ede)

**Comment by myceciliababy** [comment]
<version>3.13.4</version>

**Comment by mrniko** [comment]
you provided a command execution timeout. I need a memory dump to check it.

**Comment by myceciliababy** [comment]
I understand that the reason for the exception is that there is a problem with the redis connection，memory dump is the data stored in redis?

**Comment by myceciliababy** [comment]
I used cluster mode with a total of 10 nodes and used the default configuration for the number of connections

**Comment by mrniko** [comment]
> I understand that the reason for the exception is that there is a problem with the redis connection，memory dump is the data stored in redis?

I meant JVM memory dump
