### ISSUE TITLE
org.springframework.dao.QueryTimeoutException: Redis server response timeout (3000 ms) occured after 0 retry attempts

### ISSUE THREAD

**Issue by anekar3416** [redisson/redisson#5277]
I am using Redisson version 3.20.0 with the following connection properties:
ClusterServersConfig Redisson client with-
connectionTimeout: 3000, 
timeout: 3000, 
retry attempts: 3, 
idleConnections: 48, 
maxConnections: 128

I am using RedisTemplate to execute Redis queries in my code:
```
private RedisTemplate createRedisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate redisTemplate = new RedisTemplate();
        redisTemplate.setDefaultSerializer("A CUSTOM SERIALIZER");
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.afterPropertiesSet();
        return redisTemplate;
}
```
The Redis connection factory object is configured with 3 Retry attempts.

Even though the Retry count is set to 3, sometimes the Redis query is getting timed out after 0 retry attempts only.

Can someone help me understand why is it not retrying 3 times?

**Comment by mrniko** [comment]
can you share a full error message?

**Comment by mrniko** [comment]
for non-idempotent commands a new attempt can't be made after Redis response timeout. You can find their list here org.redisson.client.protocol.RedisCommands#NO_RETRY_COMMANDS and org.redisson.client.protocol.RedisCommands#NO_RETRY
