### ISSUE TITLE
RediSearch: Error when creating a JSON TAG field index with both SORTABLE and CASESENSITIVE options set

### ISSUE THREAD

**Issue by kgopin** [redisson/redisson#5278]
**Steps to reproduce or test case**

Try to create a JSON TAG field index which is both SORTABLE and CASESENSITIVE:
```
IndexOptions indexOptions = IndexOptions.defaults()
    .on(IndexType.JSON)
    .prefix(List.of("items"));

FieldIndex[] fields = new FieldIndex[]{
    FieldIndex.tag("$.name")
        .caseSensitive()
        .sortMode(SortMode.NORMALIZED)
        .as("name")
};
...
redissonSearch.createIndex("itemIndex", options, fields);
```
 
**Expected behavior**

The FT.CREATE command should succeed.

**Actual behavior**

The FT.CREATE command fails with: 
```
Field `CASESENSITIVE` does not have a type
```

**Redis version**
redis_version:6.2.12
...
module:name=search,ver=20609,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=ReJSON,ver=20407,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=timeseries,ver=10810,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=graph,ver=21010,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=bf,ver=20405,api=1,filters=0,usedby=[],using=[],options=[]

**Redisson version**
3.16.6

**Redisson configuration**
default

** Additional info **

The following command fails with `Field CASESENSITIVE does not have a type`:
```
FT.CREATE itemIndex ON JSON PREFIX 1 items: SCHEMA  $.name AS name TAG SORTABLE CASESENSITIVE
```

The following command  succeeds.
```
FT.CREATE itemIndex ON JSON PREFIX 1 items: SCHEMA  $.name AS name TAG CASESENSITIVE SORTABLE
```

The only difference is the order of SORTABLE and CASESENSITIVE. Apparently, the order matters and CASESENSITIVE needs to be before SORTABLE. It seems the issue is in Redisson's query builder, which set these two in the wrong order: https://github.com/redisson/redisson/blob/1534386fbc0a42b8f6f3c9bd375fcfb723aa1cc1/redisson/src/main/java/org/redisson/RedissonSearch.java#L248

**Comment by mrniko** [comment]
Fixed. Thanks for report
