### ISSUE TITLE
Unable to send command! Node source

### ISSUE THREAD

**Issue by ykrenz** [redisson/redisson#5282]
org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=31, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://10.8.137.108:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1152922437 [redisClient=[addr=redis://10.8.137.108:6379], channel=[id: 0x76d81725, L:/10.7.74.23:53758 - R:10.8.137.108/10.8.137.108:6379]], command: (EVAL), command params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pe..., 1, InventorySycLock--1001-YY101131449719808386739, 1800000, 1ab08d95-f14d-4d90-b8bf-7f6b0533bf07:856] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:715)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at java.lang.Thread.run(Thread.java:748)

redisson version: 3.9.1
singleServerConfig: 
 address: xxx
 database: xxx
 password: xxx 
 pingConnectionInterval: 30000

other conifg is default;

**Comment by ykrenz** [comment]
I want to know if this is a bug or if there are some configuration errors?

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by ykrenz** [comment]
I don't know how to solve it，Can you give me some advice

**Comment by mrniko** [comment]
Try to set nettyThreads=32

**Comment by ykrenz** [comment]
I need to update the version of redission?

**Comment by mrniko** [comment]
I would update. Since 3.9.1 is 5 years old.

**Comment by ykrenz** [comment]
Which version is currently the most stable and recommended for use.

**Comment by wynn5a** [comment]
@ykrenz 
You can find it in release page  https://github.com/redisson/redisson/releases/
