### ISSUE TITLE
RediSearch can not create Vector field

### ISSUE THREAD

**Issue by kaqiu-zi** [redisson/redisson#5284]
Hello，, I encountered an issue while using Redisson（version:3.23.3). I want to use RSearch to create Vecctor field, but it throw a Exception.

![2023-08-30-001](https://github.com/redisson/redisson/assets/66356174/39301865-da44-497c-a180-26dbd91e2ab3)

 I traced the source code in `org.redisson.RedissonSearch#addFlatVectorIndex`

![2023-08-30-002](https://github.com/redisson/redisson/assets/66356174/6d7744e1-8b19-4c67-bef1-7522e9ab420e)

The count counter of FlatVectorIndexParams seems to be incorrect

In the class `org.redisson.api.search.index.FlatVectorIndexParams`, the count counter can only reach a maximum of 5

But the example I found in the [official Redis document](https://redis.io/docs/interact/search-and-query/search/vectors/) seems to have a count counter of at least 6

![2023-08-30-003](https://github.com/redisson/redisson/assets/66356174/befaf930-ec6a-47e9-80ec-3fc6afedb15f)

Here is the reproducing code:

```java
private void testSearch() {
        final RBucket<String> one = redissonClient.getBucket("one");
        one.set("test");

        RJsonBucket<TestClass> b = redissonClient.getJsonBucket("doc:1", new JacksonCodec<>(TestClass.class));
        final List<Float> vector = Arrays.asList(
            -0.019021913F,
            -0.019021913F,
            0.016990183F,
            -0.028907854F);
        b.set(new TestClass(vector,
            "test"));


        RSearch s = redissonClient.getSearch(StringCodec.INSTANCE);
        s.createIndex("text_index", IndexOptions.defaults()
                .on(IndexType.JSON)
                .prefix(Arrays.asList("doc:")),
            FieldIndex.flatVector("$.vector")
                .type(VectorTypeParam.Type.FLOAT32)
                .dim(vector.size())
                .distance(VectorDistParam.DistanceMetric.COSINE),
            FieldIndex.text("$.content").as("content"));
    }

    @Data
    @AllArgsConstructor
    public static class TestClass {
        private List<Float> vector;
        private String content;
    }
```
----

In addition, this is a [Python example](https://github.com/openai/openai-cookbook/blob/main/examples/vector_databases/redis/redisjson/redisjson.ipynb) I found about redisearch vector field
![2023-08-30-004](https://github.com/redisson/redisson/assets/66356174/efdb4080-9a84-4a91-86aa-34a2dc25bbc4)
it seems possible to add an alias to FlatVectorIndex like TextIndex ?

**Comment by mrniko** [comment]
Fixed. Thanks for report
