### ISSUE TITLE
RSorted Map comparator not working correctly

### ISSUE THREAD

**Issue by nkant17** [redisson/redisson#5285]
Trying to create a sorted map with a custom comparator for duplicate detection. For some reason  comparator is set, however duplicates are getting added to the sorted set.  

public class RedissonMessagingMgrTest {

    private static MessagingMgr mgr = null;

    @BeforeAll
    public static void setUp() {
       try {
          mgr = new RedissonMessagingMgr("127.0.0.1",6379,"nishi");
       }
       catch (Exception exception) {
          exception.printStackTrace();
       }
    }

    @Test
    public void  testPublishNoDupQueue100() {
        String queueName = "NoDupQueue100";
        int msgCount=1;
        boolean isPublished = false;
        String str = "This is my string as bytes";
        
        mgr.createNoDupQueue(queueName, new TestMsgComparator());
        byte[] bytes = null;
        int i=0;
        for ( i=0;i<msgCount;i++) {
            str =  str + i;
            bytes = str.getBytes();
            TestMsg msg = new TestMsg(i,bytes, System.currentTimeMillis() );
            isPublished = mgr.publishNoDupQueue(queueName,msg);
        }
        isPublished = mgr.publishNoDupQueue(queueName,new TestMsg(0,bytes, System.currentTimeMillis()));  
        assertFalse(isPublished,"No Duplicates Allowed");
    }

}
   
My Comparator class is as below:-

import java.util.Comparator;

public class TestMsgComparator implements Comparator<TestMsg> {
    
    @Override
    public int compare(TestMsg a, TestMsg b)
    {
        return a.number  - b.number;
    }
}

The sorted set will contain objects of TestMsg

public class TestMsg implements PubSubMessage,  Serializable {
    private byte[] data;
    public int number;
    private long timestamp;

    public TestMsg(int number, byte[] data, long ts) {
        this.number = number;
        this.data = data;
        this.timestamp = ts;
    }

    public long getNumber() {
        return number;
    }

    public byte[] getData() {
        return data;
    }

    public long getSortedScore() {
        return timestamp;
    } 
}

public class RedissonMessagingMgr implements MessagingMgr {

   private static Logger log = LoggerFactory.getLogger(RedissonMessagingMgr.class);
   private RedissonClient client = null;

   public RedissonMessagingMgr(String host, int port, String password) throws 
   ConnectException {
      log.info("[IN] RedissonMessagingMgr Constructor");
      Config config = new Config();
      StringBuilder messagingAddress = new StringBuilder("redis://");
      messagingAddress.append(host).append(":").append(Integer.toString(port));
      config.useSingleServer().setAddress(messagingAddress.toString());
      config.useSingleServer().setPassword(password);
      config.setNettyThreads(0);
      
      log.info("[OUT] RedissonCache Constructor");
   }
}

public boolean createNoDupQueue(String name,Comparator comp ) {
      boolean returnValue = false;
      //RScoredSortedSet<PubSubMessage> sortedset = client.getScoredSortedSet(name);
      RSortedSet<PubSubMessage> sortedset = client.getSortedSet(name);
      
      System.out.println("Comparator:"+sortedset.comparator().getClass().getName());

      try {
         boolean set = sortedset.trySetComparator(comp);
         System.out.println("Comparator:"+sortedset.comparator().getClass().getName());

      }
      catch(RedisException exception) {
         // ignoring the exception and invoking trySetComparator multiple time will raise this 
         // exception.
         exception.printStackTrace();
      }
      if (sortedset != null)  {
         returnValue = true;
      }
      return returnValue;
   }

public boolean publishNoDupQueue(String queueName,PubSubMessage message) {
      RScoredSortedSet<PubSubMessage> noDupQueue = client.getScoredSortedSet(queueName);
      return noDupQueue.add(message.getSortedScore(),message);
   }
}

**Comment by mrniko** [comment]
Unable to reproduce.

```java
    public static class TestMsg {

        int number;

        String str;

        public TestMsg(int number, String str) {
            this.number = number;
            this.str = str;
        }

        public int getNumber() {
            return number;
        }

        public String getStr() {
            return str;
        }

        @Override
        public String toString() {
            return "TestMsg{" +
                    "number=" + number +
                    ", str='" + str + '\'' +
                    '}';
        }
    }

    public static class TestMsgComparator implements Comparator<TestMsg> {

        @Override
        public int compare(TestMsg a, TestMsg b)
        {
            return a.number  - b.number;
        }
    }

    @Test
    public void test12() {
        RSortedSet<TestMsg> set = redisson.getSortedSet("set");

        set.trySetComparator(new TestMsgComparator());
        set.add(new TestMsg(1, "1"));
        set.add(new TestMsg(1, "2"));
        set.add(new TestMsg(3, "3"));
        set.add(new TestMsg(4, "4"));

        assertThat(set).containsExactly(new TestMsg(1, "1"), new TestMsg(3, "3"), new TestMsg(4, "4"));
    }
```

**Comment by nkant17** [comment]
Working now
