### ISSUE TITLE
[Redisearch] Vector field not support to set alias when create index with JSON schema

### ISSUE THREAD

**Issue by kaqiu-zi** [redisson/redisson#5286]
Hello,  I encountered an issue while using Redisson (version:3.23.3)

In [Official Redis document](https://redis.io/docs/interact/search-and-query/indexing/)

![2023-08-30-005](https://github.com/redisson/redisson/assets/66356174/40c7f798-4632-4e09-aea9-556c9002aa2e)

it support to use the AS option to specify an alias for the indexed field

But I can not find any method to set it in Redisson. 

I read the source code, it is seem not support to set alias.  it should be allowed to set alias in indication. just like add numeric field

![2023-08-30-006](https://github.com/redisson/redisson/assets/66356174/471ed4c1-1a86-4cf1-ad80-85fcb49a6b26)

**Comment by mrniko** [comment]
Fixed. Thanks for report
