### ISSUE TITLE
redission使用increment的时候报错，类型错误

### ISSUE THREAD

**Issue by 2574021892** [redisson/redisson#5289]
` public static Long increment(String key, long val) {
        return redisTemplate.opsForValue().increment(key, val);
    }`
    我已经使用了StringRedisTemplate 序列化类是正确的，但是仍然报错
    ramework.dao.InvalidDataAccessApiUsageException: ERR value is not an integer or out of range.
    command: (INCRBY), promise: java.util.concurrent.CompletableFuture@24c4bac6[Not completed, 1 dependents], params: [[65, 74, 46, 67, 65, 80, 84, 67, 72, 65, ...], 1]
    
    key是一个String value是Long 排查不出其他问题

**Comment by mrniko** [comment]
This issue arise if non-integer value was stored before by the same key.
