### ISSUE TITLE
Class initialization issue with redisson 3.23.3 on Java 1.8

### ISSUE THREAD

**Issue by vasigorc** [redisson/redisson#5293]
**Expected behavior**
The program to start.

**Actual behavior**
The program exits with `java.lang.NoClassDefFoundError: Could not initialize class org.redisson.config.Config` 

**Steps to reproduce or test case**
- Use java 8 version, I used SDK to choose `8.0.372-amzn`
- Use Redisson versioin 3.23.3, I used sbt so the syntax looks like this: `"org.redisson" % "redisson" % "3.23.3"`

**Redis version**
7.0.12

**Redisson version**
3.23.3

**Redisson configuration**
This is how we initialize the config, it is the first line that throws the error actually:

```scala
    val redisClientConfig = new redisson.config.Config()
    redisClientConfig
      .setNettyThreads(0) // number of processors * 2
      .useSingleServer()
      .setAddress(formattedConnectionString)
      .setConnectionMinimumIdleSize(settings.minPoolSize)
      .setConnectionPoolSize(settings.maxPoolSize)
      .setTimeout(settings.timeout)
      .setDnsMonitoringInterval(settings.dnsCacheCheckInterval)

    Redisson.create(redisClientConfig)
```

Here is how are redis settings look in HOCON:

```hocon
  redis {
    host = "localhost"
    host = ${?PRODUCTION_ENDPOINT}
    port = 6379
    min-pool-size = 10
    max-pool-size = 30
    timeout-ms = 10000
    dns-check-interval-in-ms = 10000
  }
```

Not that the issue goes away and the code runs once I use java 11+ (I've also successfully tried 17). Successful versions were in particular: `11.0.19-tem` and `17.0.7-tem`.

**Comment by mrniko** [comment]
What was the cause?

**Comment by vasigorc** [comment]
> What was the cause?

I don't have access to that code base now so I can't go back to that commit.., but it was something related to multiple sbt modules and a different dependency.
