### ISSUE TITLE
Caused By: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 14500ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.

### ISSUE THREAD

**Issue by ratnashanker** [redisson/redisson#5299]
Hi Team,

After increasing subscription value, issue still comes same times with same redis load. We flushed redis in every run without restarting redis.  Following are the details:

Redisson Version : 3.20.0
subscriptionsPerConnection=50
timeout=10000
subscriptionConnectionPoolSize =1200

Exception:

Caused By: org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 14500ms. Try to increase 'timeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$5(PublishSubscribeService.java:219)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)

Please suggest solution.

Regards
Ratna Shanker Mishra

**Comment by mrniko** [comment]
What is the use case?

**Comment by ratnashanker** [comment]
Hi Nikita,

We are storing non-transactional DB data into redis in the from of key-value pair at the time of system startup.
There is no change in the volume of data in every run. We are flushing redis cache before every run without restarting  redis.
 
We are using Sentinel redis setup and issue is coming frequently.

Please suggest some solution.

Regards
Ratna Shanker Mishra

**Comment by mrniko** [comment]
Sorry, I mean which Redisson objects do you use.

**Comment by ratnashanker** [comment]
Hi Nikita,

We are using below Redisson libraries for mentioned usecase :

1. RLocalCachedMap
2. RBatch
3. RMapAsync
4. RScoredSortedSetAsync
5. RFuture

Regards
Ratna Shanker Mishra

**Comment by mrniko** [comment]
do you use RLocalCachedMap as a singleton per unique name?

**Comment by ratnashanker** [comment]
Yes Nikita, we are creating unique  RLocalCachedMap  object based on key there is no duplicate RLocalCachedMap  creation call for same key. Following is the code.
redisson.getLocalCachedMap(getCacheName(),codec, options)

Here getCacheName() return unique key and above code will not call for same key inside same JVM.

One point that we have multi node application setup, Each node is creating 135 unique cache through above call. 
Please refer attached diagram.
![RedisTimeoutException](https://github.com/redisson/redisson/assets/67097208/55964f81-92be-4949-a855-2c53568f8139)

**Comment by mrniko** [comment]
Is there any Redis connections amount limit?
