### ISSUE TITLE
jdk17 3.23.4 Redis Cluster startup failed

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#5301]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
6.2.7
**Redisson version**
3.23.4
**Redisson configuration**

https://gitee.com/dromara/RuoYi-Vue-Plus/issues/I80I97
https://gitee.com/dromara/RuoYi-Vue-Plus/issues/I7ZSGD

**Comment by mrniko** [comment]
What is the issue?

**Comment by mrniko** [comment]
Fixed. Thanks for report
