### ISSUE TITLE
ClusterConnectionManager accumulates millions of RedisExecutor timer task entries over 1 day

### ISSUE THREAD

**Issue by dgolombek** [redisson/redisson#5303]
**Expected behavior**

ClusterConnectionManager should keep a reasonable number of tasks 

**Actual behavior**

After ~24 hours, we see ~8M RedisExecutor tasks in ClusterConnectionManager's timer task wheel, addressing ~4GB of memory.

From the heap dump (which I can share privately), I see:

8,458,475 instances of org.redisson.command.RedisExecutor, loaded by org.springframework.boot.loader.LaunchedURLClassLoader @ 0x423800000 occupy 3,432,318,904 (21.11%) bytes. 

```
[io.netty.util.concurrent.FastThreadLocalThread]
  [org.redisson.cluster.ClusterConnectionManager]
    [io.netty.util.HashedWheelTimer]
      [io.netty.util.internal.shaded.org.jctools.queues.MpscUnboundedArrayQueue]
        [java.lang.Object[]]
          *At least another 100 layers of object arrays, MAT elides the depth beneath that*
            [io.netty.util.HashedWheelTimer$HashedWheelTimeout]
              [org.redisson.command.RedisExecutor$1]
```

**Steps to reproduce or test case**

Our use of Redisson is relatively complex and I haven't yet been able to narrow this down yet. I suspect this is connected to reconnecting to Redis after the many disconnects we see, but I have no proof. I'm just starting to dig into this, but wanted to share the details early to get any suggestions on how to track this down or any obvious bugs in our configuration.

As mentioned above, we're seeing ~1000 disconnects per-day, across 8 AWS instances. That's clearly abnormal, I haven't started looking at what's going on there -- our timeouts and retries are already on the very high side. I'm looking to this separately, and that's probably on our side, but could very easily contribute to this issue.

This is connecting to AWS ElastiCache, so we're probably getting IP changes as well the disconnects. We're connecting to the cluster IP in main configuration.

**Redis version**

AWS ElastiCache with either 6.2.6 and 7.0.7

**Redisson version**

3.19.1

**Redisson configuration**

We have two different Redis instances that we're connected to, each of which is configured like below:

```
        Config config = new Config();
        config.setCodec(new JsonJacksonCodec());
        config.setKeepPubSubOrder(false);
        config.setNettyThreads(128);
        config.useClusterServers();
        config.setMasterConnectionPoolSize(25);
        config.setMasterConnectionMinimumIdleSize(12);
        config.setSubscriptionsPerConnection(10);
        config.setSubscriptionConnectionPoolSize(100);
        config.addNodeAddress(new String[] { getRedisAddress() });
        config.setTimeout(90000);
        config.setRetryAttempts(600);
        config.setRetryInterval(1000);
        if (StringUtils.isNotBlank(getPassword())) {
            serverConfig.setPassword(getPassword());
        }

        return Redisson.create(config);
```

Then we create at least 4 long-lived RLocalCachedMap and 3 long-lived RMapCache using those 2 clients.

**Comment by mrniko** [comment]
Can you share Redisson logs? Is it connected to this issue https://github.com/redisson/redisson/issues/4338 ?

**Comment by mrniko** [comment]
I think this is because of too big retryAttempts value = 600

**Comment by dgolombek** [comment]
Is [fx1x2sq@btcmod.com](mailto:fx1x2sq@btcmod.com) the correct email to send you the trace logs at? Thanks. I'm working on a deploy with reduced retries, that'll probably take a day to get to prod.

**Comment by dgolombek** [comment]
@mrniko you tagged this for 3.23.5, which I see just came out, but I don't see anything related to it in that release. Is there something I'm missing in the release notes, or should the milestone be updated? We're finishing a release with an updated Redisson version and decreased retryAttempts (as well as better timeout and retryInteval values), hopefully I'll have results of that shortly.

**Comment by mrniko** [comment]
I don't have enough information to get the cause.

**Comment by dgolombek** [comment]
Sorry I couldn't share the full heap dump, we were unable to reproduce in staging environment and didn't want to leak customer data from a full heap dump. I can confirm your suspicion that this was tied to the crazy number of retries, possibly also impacted by the very high timeout with low retryInterval.

I'll note that those numbers were tied to the lack of exponential back-off (see https://github.com/redisson/redisson/issues/5325) -- we have another non-clustered Redis setup that has encountered some really long failover times.

This can potentially be closed, since we've found a work around, and it's not clear that there's a true bug here. But definitely something for others to be aware of.
