### ISSUE TITLE
Can I have a way to query whether a JSON PATH exists

### ISSUE THREAD

**Issue by minesunny** [redisson/redisson#5304]
https://github.com/RedisJSON/RedisJSON/issues/1063; 
it says that I can use command JSON.TYPE 
<img width="931" alt="image" src="https://github.com/redisson/redisson/assets/98507458/2fb822c7-2c27-4288-9153-6f77fa826763">
but using redison, it will throw a nullpointer exception,if json path not exist;can I have another solution to achive my aim ?
<img width="1365" alt="image" src="https://github.com/redisson/redisson/assets/98507458/24ebef93-9f96-4e62-add2-a8fcb27aef22">

**Comment by minesunny** [comment]
org.redisson.client.protocol.convertor.JsonTypeConvertor
<img width="790" alt="image" src="https://github.com/redisson/redisson/assets/98507458/d9f2e9cb-50a1-4ab7-9556-f90de5165f8b">
<img width="1459" alt="image" src="https://github.com/redisson/redisson/assets/98507458/4356cf97-8a6f-4b19-8846-3e05ebb91c51">

**Comment by mrniko** [comment]
Fixed. Thanks for report
