### ISSUE TITLE
Kryo5Codec ByteBuf memory leak causing OOM

### ISSUE THREAD

**Issue by sitakanta2006** [redisson/redisson#5307]
Our Service was failed with "java.lang.OutOfMemoryError: Direct buffer memory". Added the jvm arguments "-Dio.netty.leakDetection.level=advanced" to find the code which is causing the leak. With this flag, we see the ByteBuffer is created in below code at org.redisson.codec.Kryo5Codec$5.encode() but it was not released.

2023-09-13 11:50:05.082 ERROR 1 [] [] --- [redisson-netty-2-29] ? ? : [traceId:] [spanId:] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
#1:
        io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:617)
        io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:67)
        com.esotericsoftware.kryo.io.Output.flush(Output.java:207)
        org.redisson.codec.Kryo5Codec$5.encode(Kryo5Codec.java:163)
        org.redisson.command.CommandAsyncService.encode(CommandAsyncService.java:633)
        org.redisson.RedissonObject.encode(RedissonObject.java:314)
        org.redisson.RedissonBucket.getAndSetAsync(RedissonBucket.java:305)
        com.ril.feedgenerator.kafka.service.cache.strategy.socialEngagement.contentConsumer.PostContentOnlyCacheUpdateService.lambda$updateUserWiseSeenAndUnseenPostIds$2(PostContentOnlyCacheUpdateService.java:136)
        java.base/java.util.HashMap$KeySet.forEach(HashMap.java:929)
        com.ril.feedgenerator.kafka.service.cache.strategy.socialEngagement.contentConsumer.PostContentOnlyCacheUpdateService.updateUserWiseSeenAndUnseenPostIds(PostContentOnlyCacheUpdateService.java:64)
        com.ril.feedgenerator.kafka.service.cache.strategy.socialEngagement.contentConsumer.PostContentOnlyCacheUpdateService.updateCache(PostContentOnlyCacheUpdateService.java:39)
        ..................
        ..................
        ..................
        org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1366)
        org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1257)
        java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        java.base/java.lang.Thread.run(Thread.java:829)
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:403)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:174)
        io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:108)
        org.redisson.codec.Kryo5Codec$5.encode(Kryo5Codec.java:158)
        org.redisson.command.CommandAsyncService.encode(CommandAsyncService.java:633)
        org.redisson.RedissonObject.encode(RedissonObject.java:314)
        org.redisson.RedissonBucket.getAndSetAsync(RedissonBucket.java:305)
        com.ril.feedgenerator.kafka.service.cache.strategy.socialEngagement.contentConsumer.PostContentOnlyCacheUpdateService.lambda$updateUserWiseSeenAndUnseenPostIds$2(PostContentOnlyCacheUpdateService.java:136)
        java.base/java.util.HashMap$KeySet.forEach(HashMap.java:929)
        com.ril.feedgenerator.kafka.service.cache.strategy.socialEngagement.contentConsumer.PostContentOnlyCacheUpdateService.updateUserWiseSeenAndUnseenPostIds(PostContentOnlyCacheUpdateService.java:64)
        ................
        ................
        
In below code  https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/codec/Kryo5Codec.java , In method enocode(), we are not releasing the ByteBuf created at line "ByteBuf out = ByteBufAllocator.DEFAULT.buffer();". 

We are releasing only on exception. Ideally we should release it in the finally block.

 private final Encoder encoder = new Encoder() {
        @Override
        @SuppressWarnings("IllegalCatch")
        public ByteBuf encode(Object in) throws IOException {
            Kryo kryo = kryoPool.obtain();
            Output output = outputPool.obtain();
            ByteBuf out = ByteBufAllocator.DEFAULT.buffer();
            try {
                ByteBufOutputStream baos = new ByteBufOutputStream(out);
                output.setOutputStream(baos);
                kryo.writeClassAndObject(output, in);
                output.flush();
                return baos.buffer();
            } catch (RuntimeException e) {
                out.release();
                throw e;
            } finally {
                kryoPool.free(kryo);
                outputPool.free(output);
            }
        }
    };

Thanks,
SKP, SRE Team

**Comment by mrniko** [comment]
ByteBuf is released automatically upon write operation executed in CommandEncoder.

**Comment by sitakanta2006** [comment]
Thanks @mrniko for your prompt response.. Can you please help me explaining where we are leaking and how to fix it.

LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html

Thanks.

**Comment by mrniko** [comment]
Can you share a memory dump?

**Comment by mrniko** [comment]
3.18.0 version has fix - `ByteBuf leaks when one of multiple parameters can't be encoded`. Try to upgrade to this version.

**Comment by sitakanta2006** [comment]
Thanks a lot @mrniko  for the fix. Can you please also share the link to the class which contains just this fix.

**Comment by sitakanta2006** [comment]
@mrniko We are in 3.20.1 version and observing the issue.

**Comment by mrniko** [comment]
It may happen if thread was delayed between encoding and writing into channel.

**Comment by sitakanta2006** [comment]
Do we have a fix for the above scenario (Thread was delayed between encoding and writing into channel.)

**Comment by mrniko** [comment]
Is this issue appears only for RedissonBucket.getAndSetAsync() method?

**Comment by sitakanta2006** [comment]
yes.. All the stack trace of OOM have RedissonBucket.getAndSetAsync() method.

**Comment by mrniko** [comment]
Are there any exceptions in logs?
