### ISSUE TITLE
Kryo5Codec putAll() Number format value issue

### ISSUE THREAD

**Issue by harry-jang** [redisson/redisson#5310]
**Expected behavior**
When the putAll() method is called, the numeric values should be correctly stored in the hash set, and when the addAndGet() method is called, each numeric value should accumulate correctly.

**Actual behavior**
When the putAll() method is called, the numeric values are stored as "," and when the addAndGet() method is called, an error occurs with the message "ERR hash value is not a float."

**Steps to reproduce or test case**

``` java
Map<Object, Object> countCacheMap = new HashMap<>();
countCacheMap .put("test", 1);
countCacheMap .put("test2", 1);

redissonClient.getMap(key).putAll(countCacheMap);

redissonClient.getMap(key).addAndGet("test", 1);
```

**Redis version**
5.0.7
**Redisson version**
3.21.1

**Redisson configuration**
 ``` java
            Config config = new Config();

            String redisAddress = "redis://127.0.0.1:52533";
            String redisMasterName = "test";

            String[] sentinelHosts = getSentinelAddresses(redisAddress);

            config.useSentinelServers()
                    .setMasterName(redisMasterName)
                    .addSentinelAddress(sentinelHosts)
                    .setReadMode(ReadMode.MASTER)
                    .setSubscriptionMode(SubscriptionMode.SLAVE)
                    .setCheckSentinelsList(false);

            RedissonClient client = Redisson.create(config);
```

**Comment by mrniko** [comment]
This method uses HINCRBYFLOAT Redis command which supports only plain values. It works with JsonJacksonCodec, StringCodec or any NumberCodec.
