### ISSUE TITLE
Redisson sentinels check connection state or exclude connecting time from trylock time.

### ISSUE THREAD

**Issue by alexworkgit** [redisson/redisson#5311]
Hello, I am using redisson sentinel config for 3 redis servers, please tell me how I can understand whether there is an established connection at this moment or connection in an error state in the RedissonClient for operations? I am use call tryLockAndGetToken(10, 4 * 60, TimeUnit.SECONDS); and i dont want await time 10sec that include
 time of connection establishing.

**Comment by mrniko** [comment]
> please tell me how I can understand whether there is an established connection at this moment or connection in an error state in the RedissonClient for operations?

sorry, at which moment?

**Comment by alexworkgit** [comment]
>>> please tell me how I can understand whether there is an established connection at this moment or connection in an error state in the RedissonClient for operations?
>> 
>> sorry, at which moment?

Any, how get state of redisson instance connected or fail (in reconnecting) ?
>> 
>> > and i dont want await time 10sec that include time of connection establishing.
>> 
>> What can you suggest instead this?

If not connected or reconnecting, throw exception for lock.

**Comment by mrniko** [comment]
You can check connection with the code below.

```java
        RedisSentinelMasterSlave nodes = redisson.getRedisNodes(RedisNodes.SENTINEL_MASTER_SLAVE);
        nodes.pingAll();
```
