### ISSUE TITLE
How to timeout specific call only

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [redisson/redisson#5316]
I saw that Redisson supports setting`timeout` and `connectTimeout` via config.

What we lack in here is the ability to set timeout only for a specific command - for example, to override a default timeout for a specific call only. Of course, we can create two different clients, but this means that these clients need to maintain a separate pool of connections, monitor state of the cluster and so on. 

Furthermore, if we set `command timeout` to a very low value, this means that other calls for this client will use this value too, for example I saw that during initialization, a client sends command `INFO` to the cluster.

Since Redisson provides async API, we can leverage `Future` capabilities to cancel call when timeout passes, like below:

```kotlin
        try {
            future.get(1L, TimeUnit.SECONDS)
        } catch (e: TimeoutException) {
            // handle timeout
        } finally {
            val mayInterruptIfRunning = true
            future.cancel(mayInterruptIfRunning)
        }
```

I wonder if we should set `mayInterruptIfRunning` to `true`? 

And if we cancel future, does it release Netty thread responsible for call?

**Comment by mrniko** [comment]
netty thread isn't bounded per call. You can call RFuture.cancel to cancel request.

**Comment by mrniko** [comment]
Done. Below is the usage example

```java
        RBucket<String> al = r.getBucket(PlainOptions.name("test")
                                                                    .timeout(Duration.ofSeconds(100)));
```
