### ISSUE TITLE
How to setup nettyThreads and connections in a config

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [redisson/redisson#5317]
I read documentation about [configuration](https://github.com/redisson/redisson/wiki/2.-Configuration) of Redisson, and I have few questions regarding `nettyThreads` and connection pool.

We use Redisson in a blocking manner with cluster mode enabled and with default settings for number of Netty threads and connection pool.

I wonder how `nettyThreads` corresponds to the number of connections, for example, let's say that we have one call that writes data to the Redis, if we use default value of `masterConnectionPoolSize` which is `24`, does it mean that there can be only `24` concurrent writes, even though `nettyThreads` is `32`? Basically, is a connection bounded to the Netty thread?

**Comment by mrniko** [comment]
nettyThreads isn't bounded to connections amount. You need to increase it if you get a lot of Redis timeouts.

**Comment by AleksanderBrzozowski** [comment]
@mrniko Could you elaborate what it means? When I got a lot of Redis timeouts, then why I should increase number of nettyThreads? It seems that in such case I should check if the data that is fetched isn't too large 🤔

**Comment by mrniko** [comment]
> if we use default value of masterConnectionPoolSize which is 24, does it mean that there can be only 24 concurrent writes,

Yes, it works like send request and wait for response per connection. If connection pool size is less 10 then requests and responses are handled in parallel and not sequentially per connection. 

As for timeouts there are might be a different reasons https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by AleksanderBrzozowski** [comment]
@mrniko thanks
