### ISSUE TITLE
RedissonAutoConfiguration.class error while connecting to AWS Redis Cluster

### ISSUE THREAD

**Issue by sanketkeskar** [redisson/redisson#5318]
Hi,

My Springboot application does not start when I am trying to configure Redisson with AWS Redis endpoint. Getting below error:

> Error creating bean with name 'redisTemplate' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Unsatisfied dependency expressed through method 'redisTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redissonConnectionFactory' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Unsatisfied dependency expressed through method 'redissonConnectionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisson' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379

PFA my pom.xml, RedisConfig.java and Log files.
[Logs.txt](https://github.com/redisson/redisson/files/12672637/Logs.txt)
[RedisConfig.txt](https://github.com/redisson/redisson/files/12672603/RedisConfig.txt)
[pom.txt](https://github.com/redisson/redisson/files/12672604/pom.txt)

![image](https://github.com/redisson/redisson/assets/144234952/f2382087-d53c-401e-9712-8add7275576b)

I am assuming that I am able to connect to my AWS Redis Cluster endpoint but something is breaking. Which is causing the error shown above and application to #stop.

Assistance on the above issue will help me a lot. Waiting for response.
#4685 #2796 #4207 
Thanks 
Sanket Keskar

**Comment by AleksanderBrzozowski** [comment]
Well, are you sure that a proper address is chosen? I see that redis tries to connect to a localhost

Basically, I think that Redisson creates a client based on `spring.data.redis` properties, and since you haven't provided any properties, it tries to connect to localhost.

Can't you use properties for configuration? Redisson should create `RedisClient` object for you.

**Comment by adnanammanullah** [comment]
Hi did you got any solution for this?
