### ISSUE TITLE
Replicated Servers on ElastiCache elects both endpoints as master, emits error log.

### ISSUE THREAD

**Issue by SHxKM** [redisson/redisson#5320]
We are using AWS ElastiCache. When using `useReplicatedServers()`, I'm getting the following logs:

```
rediss://master.XXX.YYY.use1.cache.amazonaws.com:6379 is the master
rediss://replica.XXX.YYY.use1.cache.amazonaws.com:6379 is the master 👈 ???
ReadMode = SLAVE, but slave nodes are not found! Please specify all nodes in replicated mode.
```

Notice: currently `master.` and `replica.` point to the same IP, Jedis works without issues in this configuration. Does Redisson not support this?

**Expected behavior**

No error log.

**Actual behavior**

Getting these logs:

```
rediss://master.XXX.YYY.use1.cache.amazonaws.com:6379 is the master
rediss://replica.XXX.YYY.use1.cache.amazonaws.com:6379 is the master 👈 ???
ReadMode = SLAVE, but slave nodes are not found! Please specify all nodes in replicated mode.
```

**Steps to reproduce or test case**

```java
// where server addresses is a List consisting of master (primary endpoint) and replica (replica) DNS addresses provided by AWS
config.useReplicatedServers().setPassword(password).setTimeout(timeout).getNodeAddresses().addAll(serverAddresses);
Redisson.create(config);
```

**Redis version**

7.0.7

**Redisson version**

Redisson 3.23.4

**Redisson configuration**

Detailed above.

**Comment by SHxKM** [comment]
I guess I should close this, I want to use ElastiCache as designed by AWS with `main` and `replica` endpoints, but I guess `useReplicatedServers` wants the individual **_node_** addresses, which is subject to faults if a node is removed / added / changed.

**Comment by mrniko** [comment]
AWS replica hostname changes IP address in round robin. This causes constant slave add/remove
