### ISSUE TITLE
"master-slave" setup (ElastiCache): RedisConnectionException: SlaveConnectionPool no available Redis entries

### ISSUE THREAD

**Issue by SHxKM** [redisson/redisson#5323]
We are running Redis through AWS ElastiCache with **1 node**, non-cluster mode. 

The only thing even remotely "special" (it's just good practice) about this set-up is that we have 1 node, but we've set-up our application configurations in a way that prepares for additions of new nodes. Perhaps this is why we're getting issues?

So our hosts are basically:

```
[
    master.global-cache-XXX.neqbp1.use1.cache.amazonaws.com/10.10.YY.30:6379,  👈 different DNS, same IP
    replica.global-cache-XXX.neqbp1.use1.cache.amazonaws.com/10.10.YY.30:6379   👈 different DNS, same IP
]
```

ElastiCache uses a `primary` and `reader` endpoints. We are using the `primary` endpoint as the `master` in Redisson, and `reader` endpoint as the `slave`, like so:

```java
config.useMasterSlaveServers()
.setPassword(password)
.setTimeout(2000)
.setMasterAddress(elasticCachePrimaryEndpointAndPort)
.setSlaveAddresses(elasticCacheReaderEndpointAndPort);
```

**Expected behavior**

It should work.

**Actual behavior**

There are countless logs like this in our log stash: (I've omitted some fields for privacy)

> Caused by: org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: master.global-cache-XXX.neqbp1.use1.cache.amazonaws.com/10.10.YY.30:6379 Disconnected hosts: [master.global-cache-XXX.neqbp1.use1.cache.amazonaws.com/10.10.YY.30:6379, replica.global-cache-XXX.neqbp1.use1.cache.amazonaws.com/10.10.YY.30:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:187)
	at org.redisson.connection.pool.SlaveConnectionPool.get(SlaveConnectionPool.java:30)
	at org.redisson.connection.balancer.LoadBalancerManager.nextConnection(LoadBalancerManager.java:281)
	at org.redisson.connection.MasterSlaveEntry.connectionReadOp(MasterSlaveEntry.java:582)
	at org.redisson.command.RedisExecutor.connectionReadOp(RedisExecutor.java:746)
	at org.redisson.command.RedisExecutor.getConnection(RedisExecutor.java:670)
	at org.redisson.command.RedisExecutor.execute(RedisExecutor.java:128)
	at org.redisson.command.RedisExecutor$1.run(RedisExecutor.java:317)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted

This happens pretty much once the application goes up, and happens faster if there is load. There are no logs prior that indicate any kind of problem. The connections are initialized just fine.

When we switch back to `useSingleServer()`, things just work regularly but obviously this is not feasible long-term.

**Steps to reproduce or test case**

All specified above.

**Redis version**

`7.0.7`

**Redisson version**

`org.redisson:redisson:3.23.4`

**Redisson configuration**

```java
Config config = new Config();
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
config.setCodec(new JsonJacksonCodec(objectMapper));
// define reader, writer addresses, password, timeout here
config.useMasterSlaveServers()
.setPassword(password)
.setTimeout(2000).setMasterAddress(elasticCachePrimaryEndpointAndPort)
.setSlaveAddresses(elasticCacheReaderEndpointAndPort);
```

**Comment by SHxKM** [comment]
The reason we are not using Redisson’s useReplicated is that we’d like to take advantage of AWS ElastiCache’s features when it comes to failover, adding/removing nodes, etc…

**Comment by mrniko** [comment]
AWS reader endpoints dns resolution has a wired implementation. It resolves a new ip each time. So if you have 2 slaves reader endpoints hostname will resolve only a single IP each time in round robin mode.

**Comment by mrniko** [comment]
As for the error can you share Redisson log since 10 minutes before it started to appear?

**Comment by SHxKM** [comment]
> As for the error can you share Redisson log since 10 minutes before it started to appear?

There are no such logs. Do I need to do something special to obtain them? Let me know and I'll try to get them. This is a bit challenging as this issue only manifests in our production environment.


> AWS reader endpoints dns resolution has a wired implementation. It resolves a new ip each time. So if you have 2 slaves reader endpoints hostname will resolve only a single IP each time in round robin mode.

Does this mean it's basically impossible to pool connections when using this DNS? So the official recommendation when working with Redisson is to use `useReplicatedServers` and specify the node IDs?

One thing remains unexplained even if the DNS resolves only to one host at a time, I don't think it should cause disconnection in `main-secondary` ("master-slave") configuration.

**Comment by mrniko** [comment]
> Does this mean it's basically impossible to pool connections when using this DNS? 

Since hostname resolves only to a single IP you'll constantly get node added/removed.

> So the official recommendation when working with Redisson is to use useReplicatedServers and specify the node IDs?

Yes

> One thing remains unexplained even if the DNS resolves only to one host at a time

for replica it changes each DNS call

**Comment by SHxKM** [comment]
> for replica it changes each DNS call

I am not sure I explained myself well, I wrote:

> One thing remains unexplained even if the DNS resolves only to one host at a time, I don't think it should cause disconnection in main-secondary ("master-slave") configuration.

For example we are already using Jedis with `writer`/`reader` endpoints with AWS Elasticache (separate Jedis clients), and it is not failing like Redisson:

```
JedisPool jedisReaderPool = new JedisPool(new GenericObjectPoolConfig<>(), readerHost, readerPort,
                readerTimeout, password, shouldUseSsl);

JedisPool jedisWriterPool = new JedisPool(new GenericObjectPoolConfig<>(), writerHost, writerPort,
                writerTimeout, password, shouldUseSsl);
```

**Comment by mrniko** [comment]
Does JedisPool scan readerHost for ip changing?
