### ISSUE TITLE
some problem about using NameMapper

### ISSUE THREAD

**Issue by zhangrenbin** [redisson/redisson#5327]
I use nameMapper for append default prefix to erver key. but there is some mistake when i do it with RedissonSortedSet. 
the “add” operation is ok，but "get" operation does’t work. I flow the source code, and found there a RedissonList member in RedissonSortedSet, when construct the RedissonList instance, it is do the "NameMapper.map" again, so there make double prefix.

**Comment by mrniko** [comment]
Fixed. Thanks for report
