### ISSUE TITLE
RedissonPriorityQueue add cause NullPointException

### ISSUE THREAD

**Issue by zhangchiisgy** [redisson/redisson#5328]
**Expected behavior**
 do not cause NullPointException
**Actual behavior**
![image](https://github.com/redisson/redisson/assets/12904624/353c5f87-493d-44ef-ae3b-04c154fefef1)

**Steps to reproduce or test case**
not sure 
**Redis version**
V5.0
**Redisson version**
3.10.7

**Redisson configuration**
![image](https://github.com/redisson/redisson/assets/12904624/94b3ca6f-a5d5-466c-8df3-414770cb27c4)
if return  new BinarySearchResult<V>();
then 
![image](https://github.com/redisson/redisson/assets/12904624/99d0a55c-084c-44f6-b2d6-9b43ed56652b)
cause npe
BinarySearchResult index should have a default val

**Comment by zhangchiisgy** [comment]
which redisson version should i upgradation, which is stable

**Comment by mrniko** [comment]
Can you share a full stacktrace?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/2484
