### ISSUE TITLE
Azure Cache for Redis Not Connecting 

### ISSUE THREAD

**Issue by mifrasmm** [redisson/redisson#5337]
### Discussed in https://github.com/redisson/redisson/discussions/5336

<div type='discussions-op-text'>

<sup>Originally posted by **mifrasmm** September 26, 2023</sup>
Hi Team,

im looking to Azure Cache for Redis connection string for redisson , im trying below but some reason not working same i tried with Redis its working what im missing ? please help

{
   "singleServerConfig":{
      "idleConnectionTimeout":10000,
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "retryAttempts":3,
      "retryInterval":1500,
      "password":"myapassword=",
      "subscriptionsPerConnection":5,
      "clientName":null,
      "address":"redis://myhostname.redis.cache.windows.net:6379",
      "subscriptionConnectionMinimumIdleSize":1,
      "subscriptionConnectionPoolSize":50,
      "connectionMinimumIdleSize":32,
      "connectionPoolSize":64,
      "database":0,
      "dnsMonitoringInterval":5000
   },
   "threads":0,
   "nettyThreads":0,
   "codec":{
      "class":"org.redisson.codec.SerializationCodec"
   },
   "transportMode":"NIO"
}
</div>

**Comment by mrniko** [comment]
Can you share the exception stacktrace?

**Comment by mifrasmm** [comment]
im new to this anyway i can enable the log on same config ? please advice

**Comment by mrniko** [comment]
that depends on logging framework you use. you need to configure it for `org.redisson` package

**Comment by nkant17** [comment]
Do you have network connectivity from application to Azure? Normally, its established through a Private Link .
