### ISSUE TITLE
memory leak when press test

### ISSUE THREAD

**Issue by ZhongGuoDragon** [redisson/redisson#5339]
![微信截图_20230928170124](https://github.com/redisson/redisson/assets/68063139/be9992fe-1eed-4750-8c66-9cb3e62a1cb9)

**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
  <dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson-spring-boot-starter</artifactId>
      <version>3.23.1</version>
  </dependency>

**Redisson configuration**

**Comment by mrniko** [comment]
According to the trace buffer leak caused by apache dubbo
