### ISSUE TITLE
Remote Services Catastropically start to fail after decoding error

### ISSUE THREAD

**Issue by bhoover10001** [redisson/redisson#5340]
We've been trying to upgrade to 3.21.3, but keep having the same issue.

Remote Services will work for a few minutes, and then we get a decoder error, with an unregistered class, mostly in Kryo5, and then all Remote Services on that server stop working.  So far we have been unable to figure out call is actually throwing the error, or what class is unable to be decoded.

This only happens when the servers are under load.

Before this time, other RMIs are working correctly.  After this error, all RMIs for the server start throwing a "No Response after [[timeout]]ms" error

The errors that we are getting:
ERROR|2023-09-28 15:28:00,571|redisson-netty-2-20|org.redisson.client.handler.ErrorsLoggingHandler|Exception occured. Channel: [id: 0x0ecc6df6, L:/10.99.46.186:49930 - R:10.99.41.139/10.99.41.139:6379]
! io.netty.handler.codec.DecoderException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 121
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
! at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
!  [1 skipped]
! Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 121
! at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
! at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
! at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [7 skipped]
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! ... 17 common frames omitted

ERROR|2023-09-28 15:28:00,571|redisson-netty-2-20|org.redisson.remote.SyncRemoteProxy|Can't get response from {remote_response}:86c6c518-ed2a-460a-83b3-853610142cd5:redisson_rs
! com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 121
! at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
! at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
! at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [7 skipped]
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
! at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
!  [1 skipped]

ERROR|2023-09-28 15:28:00,571|redisson-netty-2-20|org.redisson.client.handler.CommandDecoder|Unable to decode data. channel: [id: 0x0ecc6df6, L:/10.99.46.186:49930 - R:10.99.41.139/10.99.41.139:6379], reply: ReplayingDecoderByteBuf(ridx=2774, widx=2774), command: (BLPOP), promise: java.util.concurrent.CompletableFuture@65750e8b[Not completed, 1 dependents], params: [{remote_response}:86c6c518-ed2a-460a-83b3-853610142cd5:redisson_rs, 60]
! com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 121
! at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
! at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:758)
! at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:869)
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [7 skipped]
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
! at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
!  [1 skipped]

**Comment by mrniko** [comment]
What version did you upgrade from?

**Comment by bhoover10001** [comment]
We were moving from 3.19.0 to 3.21.3 and trying to use Kryo5Codec to replace FSTCodec.

**Comment by mrniko** [comment]
Kryo5Codec isn't compatible with FSTCodec. You need to migrate the data or clear database.
