### ISSUE TITLE
Query - Spring Data And Kryo Version Compatibility

### ISSUE THREAD

**Issue by nnanda2016** [redisson/redisson#5346]
Hi @mrniko ,

We are in the process of upgrading Redisson version in our app but struggling with version mismatch. That is because we are using Spring StateMachine;  both Redisson and SSM use Kryo.

Appreciate if you could help us with following questions?
1. Can the latest Redisson client library (say `3.22.x` or `3.23.x`) work with `redisson-spring-data-27`?
2. Can the latest Redisson client library (say `3.22.x` or `3.23.x`) work with Kryo 4.x? 

Thank you.

**Comment by mrniko** [comment]
Hi @nnanda2016,

Yes, to all questions.

**Comment by nnanda2016** [comment]
While I understand it is not good to comment on closed issues, I am putting one of my findings here for everyone else's info. This is related to my second question. Even if the author has said `YES`, but in reality latest version of Redisson does not work with Kryo 4.x. The application breaks with following error 
```java
java.lang.IllegalStateException: Failed to load ApplicationContext
[.... omitting the details ...]
Caused by: java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/util/Pool
	at org.redisson.config.Config.<init>(Config.java:108)
	at org.redisson.Redisson.<init>(Redisson.java:67)
	at org.redisson.Redisson.create(Redisson.java:114)

```
This is expected as Kyro4 defines `KryoPool` in `.pool` package, whereas Kryo5 defines `Pool` under `.util` package.

With due respect to the author, I differ from his answer to my second question. The correct answer should be `NO`.

**Comment by mrniko** [comment]
You need to exclude kryo dependency from Redisson and then define kryo 4.0.3 dependency in your project.

**Comment by nnanda2016** [comment]
Much appreciated @mrniko for your response. That's how I tested and saw the `NoClassDefFoundError`.
