### ISSUE TITLE
Reddison live Object as RExpired not correctly clean up index

### ISSUE THREAD

**Issue by abishai** [redisson/redisson#5351]
**Expected behavior**
All traces of expired RLO is cleared

**Actual behavior**
Index is left and search methods still finds  such entries.

**Steps to reproduce or test case**
1. Create RLO object
2. Cast it to RExpirable, set expiration and check Redis entries
3. Verify that index is left, while object deleted

**Redisson version**
3.23.5

**Redisson configuration**
Single instance.

This issues still exits https://github.com/redisson/redisson/issues/2625 I think, something else is expiring RLO entries - expiration code is not running, but main entry is still removed.

**Comment by mrniko** [comment]
Make sure that Redis `notify-keyspace-events` setting contains the letters Kx
