### ISSUE TITLE
Auto configuration with Spring Boot 3.x

### ISSUE THREAD

**Issue by kjthorpe18** [redisson/redisson#5352]
With Spring Boot 3.0, the `spring.factories` method of autoconfiguration was removed in favor of using `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`. Also mentioned in the [SB 2.7 guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration) is annotating auto configuration classes with the `@AutoConfiguration`. 

Should the annotation on [RedissonAutoConfiguration](https://github.com/redisson/redisson/blob/2669597d81683ab2fb7ba70d1ba974ed3b52984a/redisson-spring-boot-starter/src/main/java/org/redisson/spring/starter/RedissonAutoConfiguration.java#L63) be changed from `@Configuration` to `@AutoConfiguration`? I also noticed that `spring.factories` is still hanging around. 

I noticed this when upgrading my application to Spring Boot 3.0 and integration tests are failing:
```
Failed to load ApplicationContext ...
...
Caused by: java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
        - org.redisson.spring.starter.RedissonAutoConfiguration
```
The application in question sets up a custom configuration and excludes the AutoConfiguration like so:
```
spring.autoconfigure.exclude=org.redisson.spring.starter.RedissonAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
