### ISSUE TITLE
Redis Server Response Timeout

### ISSUE THREAD

**Issue by prateekj0710** [redisson/redisson#5357]
I am using Redisson 3.17.5 version. I am getting frequent Redis server response timeout errors. I tried everything mentioned on this thread(https://github.com/redisson/redisson/issues/4381) but still getting issues. Following is my configuration for Redis:

config.setNettyThreads(256)
.useClusterServers().addNodeAddress( node )
.setConnectTimeout(1000)
.setMasterConnectionPoolSize(500)
.setSlaveConnectionPoolSize(t500)
.setTimeout(1000)
.setIdleConnectionTimeout(10000)
.setRetryAttempts(0)
.setRetryInterval(100)
.setSslEnableEndpointIdentification(false)

I set retryAttempts to 0 as we don't want Redis to take too long to respond. By doing so, if I cannot get the response on the first try, then I call my service to fetch the response. Also, in most of the cases, I get my response in under 50 ms time frame, which is why I set the timeout to 1000 ms.

Can anyone help to identify what's wrong with my configuration?

Getting the following message from Redis:

Redis server response timeout (1000 ms) occured after 0 retry attempts, is non-idempotent command: false Check connection with Redis node: x.x.x.x/x.x.x.x:6379 for TCP packet drops.  Try to increase nettyThreads and/or timeout settings. Command: (EVAL), params: [if redis.call('setnx', KEYS[6], ARGV[4]) == 0 then return -1;end;redis.call('expire', KEYS[6], ARGV[..., 6, 100049015200039887600001, redisson__timeout__set:{100049015200039887600001}, redisson__idle__set:{100049015200039887600001}, redisson_map_cache_expired:{100049015200039887600001}, redisson__map_cache__last_access__set:{100049015200039887600001}, redisson__execute_task_once_latch:{100049015200039887600001}, 1696916962377, 100, ...], channel: [id: 0xd9d0e22b, L:/172.21.235.4:39612 - R:172.21.235.90/172.21.235.90:6379]

**Comment by prateekj0710** [comment]
@mrniko can you please help?

**Comment by mrniko** [comment]
Here is the answer https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by F1ncyJ** [comment]
## Java File
```java

@Configuration
@ConditionalOnClass({ Redisson.class, RedisOperations.class })
@EnableConfigurationProperties({ RedisProperties.class, CustomRedissonConfig.CustomRedissonProperties.class }) // Properties load
public class CustomRedissonConfig {

    /**
     * Spring original configuration
     */
    private final RedisProperties redisProperties;
    /**
     * Enhance Redisson configuration
     */
    private final CustomRedissonProperties redissonProperties;

    public CustomRedissonConfig(RedisProperties redisProperties, CustomRedissonProperties redissonProperties) {
        this.redisProperties = redisProperties;
        this.redissonProperties = redissonProperties;
    }

    @Bean
    public RedissonAutoConfigurationCustomizer timeoutConfigurationCustomizer() {
        return new TimeoutConfigurationCustomizer(redisProperties, redissonProperties);
    }

    /**
     * Enhance the Config class
     */
    public static class TimeoutConfigurationCustomizer implements RedissonAutoConfigurationCustomizer {
        private final RedisProperties redisProperties;
        private final CustomRedissonProperties redissonProperties;

        public TimeoutConfigurationCustomizer(RedisProperties redisProperties, CustomRedissonProperties redissonProperties) {
            this.redisProperties = redisProperties;
            this.redissonProperties = redissonProperties;
        }

        @Override
        public void customize(Config config) {
            int timeout = Optional.ofNullable(redissonProperties.getTimeout()).orElse(3000); // default = 3000 ms

            // 选择模式
            Method clusterMethod = ReflectionUtils.findMethod(RedisProperties.class, "getCluster");
            if (clusterMethod != null && ReflectionUtils.invokeMethod(clusterMethod, this.redisProperties) != null) {
                config.useClusterServers().setTimeout(timeout);
            } else {
                config.useSingleServer().setTimeout(timeout);
            }
        }
    }

    /**
     * Enhanced Redisson configuration
     */
    @Getter
    @Setter
    @ConfigurationProperties(value = "spring.redisson.config") // 前缀
    public static class CustomRedissonProperties {
        /**
         * response read time out (ms)
         */
        private Integer timeout;
    }
}

```

## Properties File Example：
```properties
spring.redisson.config.timeout=5000 
```
