### ISSUE TITLE
Question - Implement optimistic locking 

### ISSUE THREAD

**Issue by nnanda2016** [redisson/redisson#5360]
Hi @mrniko , could you help me understand following question? I am little confused.

We are using Redisson (open source) v3.17.7 and in the process of migrating to the latest version. For Redis, we are using GCP MemoryStore 6.x in standard tier (no cluster). We have a use case in which we execute following steps
1. Save data to a keyspace `ks1`
2. Read data from another keyspace `ks2`
3. Update the data read in step-2
4. Save it back with the same key (which was used in step-2)

We have to guarantee atomicity of above steps. Is there any API in redisson which uses `WATCH` command? Or should we use a distributed lock to achieve the atomicity?

Thank you.

Best,
NN

**Comment by mrniko** [comment]
It's better to use the distributed lock.
