### ISSUE TITLE
AddressResolverGroupFactory breaking change is not reflected in the newly released version number

### ISSUE THREAD

**Issue by pieshkin** [redisson/redisson#5362]
You made a breaking change in AddressResolverGroupFactory, which must be reflected as a major change when releasing a new version.
[redisson/src/main/java/org/redisson/connection/AddressResolverGroupFactory.java](https://github.com/redisson/redisson/commit/75a6cf25d211b5de9961816603530297ad7906fa#diff-7fb3f98cf7bf388a1383555a5d2b63e40494cc2fe1a464c12ff7515efa42c81e)

At least assuming that you use https://semver.org/

**Comment by mrniko** [comment]
My mistake. Will do.
