### ISSUE TITLE
Client shutdown can take much longer than timeout

### ISSUE THREAD

**Issue by dgolombek** [redisson/redisson#5367]
**Expected behavior**

MasterSlaveConnectionManager(0, 2, TimeUnit.SECONDS); should complete in at most 2 seconds.

**Actual behavior**

shutdown(0, 2, TimeUnit.SECONDS); can take an almost unbounded amount of time

**Steps to reproduce or test case**

Create a bunch of async tasks that are pretty slow (in our case I saw several RedisNodes.pingAll() commands still outstanding after 30s, there were probably ~20-30 running commands when we started shutdown). Then call shutdown().

By code inspection of https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L478
you can see that we use the same timeout for all entries to shutdown, and the service manager, and the event loop group. Instead, we should probably be decrementing the time taken from timeout after each step, such that the total time for shutdown is roughly the provided timeout.

**Redis version**

Any

**Redisson version**

3.25.5

**Redisson configuration**

Doesn't matter

**Comment by dgolombek** [comment]
I'm happy to submit a patch for this if you agree with my proposal.

**Comment by mrniko** [comment]
That would be great.
