### ISSUE TITLE
Is ReadWriteLock fair?

### ISSUE THREAD

**Issue by sp00m** [redisson/redisson#5379]
Your [FairLock](https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers#82-fair-lock) states:

> Fair lock guarantees that threads will acquire it in is same order they requested it.

What's the related behaviour of your [ReadWriteLock](https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers#85-readwritelock)? Is it fair too?

In other words, for a ReadWriteLock, if the WriteLock is taken and two other threads wait for it to be released, which thread will get it first once released?

**Comment by JupiterFeng** [comment]
https://www.javadoc.io/doc/org.redisson/redisson/3.4.3/org/redisson/api/RReadWriteLock.html
Works in non-fair mode.
