### ISSUE TITLE
RPromise class not found

### ISSUE THREAD

**Issue by dineshmadhwal** [redisson/redisson#5386]
@mrniko. 

We are trying to upgrade Redisson version from 3.10.2 to 3.22.0, but we can't find this RPromise class in this new version. So, the code written using 3.10.2 is throwing error as its not able to find this class. Can you please help to let us know what alternative we can use and how to use it? We would also like to know how to replace PPromise usage in our code.

It would be great if you can help to point out to any resources mentioning this transition as I can't seem to find anything regarding the removal of this class. I can see that this class was removed in 3.17.2 version, but the changelog doesn't mention it.

I would also like to know regarding the alternatives for  Node and RedisNodes classes. We are using these to perform the health check. These classes are marked as deprecated, but I can't seem to find any mention of alternatives for these classes. It would be great if you can help us as we are not able to upgrade the version.

**Comment by mrniko** [comment]
> We are trying to upgrade Redisson version from 3.10.2 to 3.22.0, but we can't find this RPromise class in this new version

`RPromise` was an internal call. Replaced with CompletableFuture,

> I would also like to know regarding the alternatives for Node and RedisNodes classes

Use `org.redisson.api.RedissonClient#getRedisNodes()` instead

**Comment by dineshmadhwal** [comment]
@mrniko .. Thank you for replying! I understand that you might be busy, but it would be great if you can have a look at the code below and suggest us on how can we proceed with this. These are the errors we get in the class file after we change the Redisson version to 3.2022.0

![20231022_005914](https://github.com/redisson/redisson/assets/24225240/72d66be2-abff-458b-abb1-494503e79520)
![20231022_010009](https://github.com/redisson/redisson/assets/24225240/c7e96118-b188-4806-9fd2-6faf8e12d7f8)
![20231022_010025](https://github.com/redisson/redisson/assets/24225240/43370cc2-d8d9-4c4f-9bc1-e04681547123)

**Comment by 906798724** [comment]
@dineshmadhwal hello, have you solve this problem? we meet this error in our codes also
