### ISSUE TITLE
KryoException. Stackoverflow occured because of infinite recursion

### ISSUE THREAD

**Issue by ArekSzyszkowski** [redisson/redisson#5389]
Hi,

I have a project where I use RedissonSpringCacheManager with RedissonClient default configuration.
I am using @Cacheable annotation to cache Entities (unfortunatelly for now I can't change Entities to DTOs because the project is too big).

Please check sample code to better explain the issue I have:
Entities:
```
@Entity
public class User implements Serializable {
    @Id
    @Column(name = "user_id")
    private Long id;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.ALL)
    private Set< Address> addresses
}

@Entity
@Table(name = "address")
public class Address implements Serializable {
    @Id
    private Long id;
    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = false)
    private User user;
}
```
Cache configuration:
```
@Bean
CacheManager cacheManager(RedissonClient redissonClient) {
    Map<String, CacheConfig> config = new HashMap<>();
    config.put("users", new CacheConfig(liveTime, idleTime));
    return new RedissonSpringCacheManager(redissonClient, config);
}
```

Method used for caching:
```
@Cacheable(cacheNames = users, key = "#p0", condition = "#p0 != null", unless = "#result == null")
public User findById(Long id) {
    return userRepository.findById(id);
}
```

The caching was correctly working with Redisson version 3.17.1 
After upgrading to redisson 3.23.1 I have such exception on serialization of entity, (when trying to add User into cache, by invoking method findById): 

com.esotericsoftware.kryo.KryoException: A StackOverflow occurred. The most likely cause is that your data has a circular reference resulting in infinite recursion. Try enabling references with Kryo.setReferences(true). If your data structure is really more than 1320 levels deep then try increasing your Java stack size.
Serialization trace:
addresses (com.test.User)
user (com.test.Address)
addresses (com.test.User)
user (com.test.Address)
addresses (com.test.User)
...

Is there any known workaround?

**Comment by mrniko** [comment]
Did you try to set suggested Kryo.setReferences(true). ?
