### ISSUE TITLE
After the AWS security update, when attempting to unfreeze the connections to the deleted nodes, an error occurs.

### ISSUE THREAD

**Issue by kaeskers** [redisson/redisson#5390]
**Expected behavior**
The connections to the deleted nodes should be released and should not be unfreezed.

**Actual behavior**
Trying to unfreeze the connections to the deleted nodes.

**Steps to reproduce or test case**

**Redis version**
AWS elasticache engine version 6.2.6

**Redisson version**
3.20.1

**Redisson configuration**
cluster server mode.
connect using the configuration endpoint, which means that only one value is entered for the node address.
scanInterval : 2000
All other configuration values are set to their default values.

**Error Logs**
<img width="1013" alt="image" src="https://github.com/redisson/redisson/assets/148040265/752975ba-a2d8-4427-8374-691719c11b91">
<img width="1074" alt="image" src="https://github.com/redisson/redisson/assets/148040265/014d03cc-6aef-49c8-8dcc-d97af0eb96f1">

The IP address '10.60.1.21' shown in the error log is the previous node's address.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/3980. Please update to 3.23.2 or the latest version
