### ISSUE TITLE
Error happen: attempt to unlock lock, not locked by current thread by node id: XXX

### ISSUE THREAD

**Issue by ngophuhung96** [redisson/redisson#5391]
When I upgraded Redisson to `3.24.1` and `3.24.2`, the error happened in my JUnit test cases:

> java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: c03a291c-52a8-48eb-8094-9ea91e0ad577 thread-id: 1
> 	at org.redisson.RedissonBaseLock.lambda$unlockAsync0$2(RedissonBaseLock.java:292)
> 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
> 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
> 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
> 	at org.redisson.command.CommandBatchService.lambda$executeAsync$7(CommandBatchService.java:371)
> 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
> 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
> 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
> 	at org.redisson.command.CommandBatchService.lambda$execute$9(CommandBatchService.java:486)
> 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
> 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
> 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
> 	at org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:610)
> 	at org.redisson.command.RedisCommonBatchExecutor.handleResult(RedisCommonBatchExecutor.java:164)
> 	at org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:568)
> 	at org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:202)
> 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
> 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
> 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
> 	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:326)
> 	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:217)
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
> 	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
> 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:840)

Here is my test class:

```java
import com.github.fppt.jedismock.RedisServer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.redisson.Redisson;
import org.redisson.api.RLock;
import org.redisson.api.RedissonClient;
import org.redisson.config.Config;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class RedisTest {

    private RedisServer redisServer;
    private RedissonClient redissonClient;

    @BeforeEach
    void beforeTest() throws Exception {
        redisServer = RedisServer.newRedisServer();
        redisServer.start();

        Config config = new Config();
        config.useSingleServer().setAddress("redis://" + this.redisServer.getHost() + ":" + this.redisServer.getBindPort());
        redissonClient = Redisson.create(config);
    }

    @AfterEach
    void afterTest() throws IOException {
        redisServer.stop();
    }

    @Test
    public void testMethod() {
        String key = "an-example-key";
        RLock rLock = this.redissonClient.getLock(key);

        rLock.lock();
        assertTrue(rLock.isLocked());
        rLock.unlock();
        assertFalse(rLock.isLocked());
    }
}
```

This won't happen when I use `3.23.5` version. I can't find out the cause of the problem.
Can anyone help me with this? Thank you

**Comment by mrniko** [comment]
Unable to reproduce it. Try it with the real Redis server.

**Comment by ngophuhung96** [comment]
> Unable to reproduce it. Try it with the real Redis server.

@mrniko I added an example project to reproduce it. Could you please check this? Thank you
https://github.com/ngophuhung96/demo

**Comment by mrniko** [comment]
In your demo you still use Redis mock, but you need to use a real Redis server.

**Comment by ngophuhung96** [comment]
@mrniko Thanks for the response. So from version `3.24.1` onwards, I have no choice but to write JUnit using real Redis instead of embedded Redis, right? This is quite inconvenient. Version `3.23.5` still supports it. Do you have any plans for embedded Redis support in the future?

**Comment by mrniko** [comment]
Redisson isn't tested with mocked Redis.
