### ISSUE TITLE
RedisConnectionException: SlaveConnectionPool no available Redis entries

### ISSUE THREAD

**Issue by howetong** [redisson/redisson#5395]
RedisConnectionException: SlaveConnectionPool no available Redis entries. Master entry host: 192.168.xx.xx/192.168.xx.xx:6379 Disconnected hosts: [192.168.xx.xx/192.168.xx.xx:6379].

Redisson Version: 3.20.0
Redis Server: AWS ElastiCache Redis, 2 Shards(each have 1 master and 2 salves)
Redisson Configuration: 
**********	
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 1000
  timeout: 1000
  retryAttempts: 1
  retryInterval: 100
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  subscriptionsPerConnection: 5
  loadBalancer:
    class: org.redisson.connection.balancer.RoundRobinLoadBalancer
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: SLAVE
  subscriptionMode: SLAVE
  keepAlive: true
  nodeAddresses:
    - "redis://xxxxx.amazonaws.com.cn:6379”
  scanInterval: 2000
threads: 16
nettyThreads: 32
transportMode: NIO
**********

In our production environment, the AWS ElastiCache Redis had a failover, and switched the slave node to master node in one minute.

As a rule, I think the redisson client can recognize the topological structure of server side after the failover, but it’s not. It seems many read requests send to the new master node and reported errors. The IP address in the error messages is the new master node.

So why this happend? Should I need to upgrade the redisson version? Do you have some advises? Thanks!  @mrniko

**Comment by mrniko** [comment]
Should be fixed in https://github.com/redisson/redisson/issues/3980. Can you try 3.23.3 version or the latest one?

**Comment by mrniko** [comment]
I'm looking forward to your feedback.

**Comment by howetong** [comment]
I tried failover manually or kill the master node in test environment, but didn’t repeat the same error. I'm not sure whether the AWS official maintaining is just simple operation of failover. 

Anyway, I will try to upgrade the redission version in production environment. Hope it's useful.

**Comment by musicallyvk** [comment]
> I tried failover manually or kill the master node in test environment, but didn’t repeat the same error. I'm not sure whether the AWS official maintaining is just simple operation of failover.
> 
> Anyway, I will try to upgrade the redisson version in production environment. Hope it's useful.

@howely  Hi dear, i have the same issue, exactly same issue.  How to fix this bro. please confirm.  thanks already man. @mrniko

**Comment by howely** [comment]
> > I tried failover manually or kill the master node in test environment, but didn’t repeat the same error. I'm not sure whether the AWS official maintaining is just simple operation of failover.
> > Anyway, I will try to upgrade the redisson version in production environment. Hope it's useful.
> 
> @howely Hi dear, i have the same issue, exactly same issue. How to fix this bro. please confirm. thanks already man. @mrniko



> > I tried failover manually or kill the master node in test environment, but didn’t repeat the same error. I'm not sure whether the AWS official maintaining is just simple operation of failover.
> > Anyway, I will try to upgrade the redisson version in production environment. Hope it's useful.
> 
> @howely Hi dear, i have the same issue, exactly same issue. How to fix this bro. please confirm. thanks already man. @mrniko

Hi @musicallyvk 

After upgrading to newest version, it seems to be working. 
Hope it can help you.

**Comment by pingweiqiang** [comment]
@howely  Could you please tell me which version upgrade resolved this Redis connection issue?
