### ISSUE TITLE
Does #4908 affect AWS ElastiCache clusters as well?

### ISSUE THREAD

**Issue by narendravardi** [redisson/redisson#5396]
Hi Team, 

I wanted to check the issue listed in https://github.com/redisson/redisson/issues/4908 affects ElastiCache Cluster mode disabled ?

I have multi_az enabled with ElastiCache Cluster mode disabled and use Java spring with redisson client `3.23.5`.

When ever we are applying patch upgrades on the cluster, our service is noticing `READONLY You can't write against a read only replica`. If we do a restart of the service, then the writes are happening without any issue. 

So, wanted to check if this is something is fixed as part of #4908

**Comment by mrniko** [comment]
Can you share Redisson logs for this case in `debug` logging level?

**Comment by narendravardi** [comment]
Hi @mrniko, getting all logs would be tough for me. Any specific string matches you want me to provide?

**Comment by narendravardi** [comment]
Here are few logs I could get:


{
  "@timestamp": "2023-10-25T14:54:36.796+05:30",
  "@version": "1",
  "message": "connection released for command (RPUSH) and params [testFailOverQueueTopic, PooledUnsafeDirectByteBuf(ridx: 0, widx: 7, cap: 256)] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@745534504 [redisClient=[addr=redis://changed-name-non-clustered-replicated.1isnxi.ng.0001.aps1.cache.amazonaws.com:6379], channel=[id: 0xcf1f309c, L:/172.0.77.43:56168 - R:changed-name-non-clustered-replicated.1isnxi.ng.0001.aps1.cache.amazonaws.com/172.0.101.242:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@582cb8d4[Completed exceptionally: org.redisson.client.RedisException: READONLY You can't write against a read only replica.. channel: [id: 0xcf1f309c, L:/172.0.77.43:56168 - R:changed-name-non-clustered-replicated.1isnxi.ng.0001.aps1.cache.amazonaws.com/172.0.101.242:6379] command: (RPUSH), promise: java.util.concurrent.CompletableFuture@582cb8d4[Not completed, 1 dependents], params: [testFailOverQueueTopic, PooledUnsafeDirectByteBuf(ridx: 0, widx: 7, cap: 256)]], command=(RPUSH), params=[testFailOverQueueTopic, PooledUnsafeDirectByteBuf(ridx: 0, widx: 7, cap: 256)], codec=org.redisson.codec.Kryo5Codec], usage=0]",
  "logger_name": "org.redisson.command.RedisExecutor",
  "thread_name": "redisson-netty-2-14",
  "level": "DEBUG",
  "level_value": 10000
}



{
  "@timestamp": "2023-10-25T14:54:36.796+05:30",
  "@version": "1",
  "message": "acquired connection for command (LPOP) and params [testFailOverQueueTopic] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node changed-name-non-clustered-replicated.1isnxi.ng.0001.aps1.cache.amazonaws.com/172.0.101.242:6379... RedisConnection@475740480 [redisClient=[addr=redis://changed-name-non-clustered-replicated.1isnxi.ng.0001.aps1.cache.amazonaws.com:6379], channel=[id: 0xc18ffa8f, L:/172.0.77.43:56176 - R:changed-name-non-clustered-replicated.1isnxi.ng.0001.aps1.cache.amazonaws.com/172.0.101.242:6379], currentCommand=null, usage=1]",
  "logger_name": "org.redisson.command.RedisExecutor",
  "thread_name": "refund-workers-thread-pool11",
  "level": "DEBUG",
  "level_value": 10000
}

**Comment by mrniko** [comment]
I need topology change logs

**Comment by narendravardi** [comment]
Not sure about topology logs.

Any code links you can share to check which logs to provide?

**Comment by narendravardi** [comment]
I was talking about the Replicated Config Mode - Whenever there is an upgrade of redis-engine (Redis Cluster Mode Disabled AWS), writes and read would fail with `READONLY You can't write against a read only replica`

When enabled debug logs, this is the error: `No master available among the configured addresses, please check your configuration.`

Beyond this point, there's not much debug logs I could notice. 

```
redisson client: 3.17.3
redis_engine upgrade from: 6.0 to 6.2 with Multi-AZ enabled. 
```

Is this something to do with AWS on how they are handling it? 

To replicate these steps, all you have to do is to:
* Create ElastiCache with MultiAZ enabled (Cluster Mode Disabled) 
* Use redisson dependency to talk to redis cluster during the upgrade process, by using replicated config. 

This is something I am checking with AWS team as well. Meanwhile, wanted to check if this is something you are aware/noticed prior. 

Thanks

**Comment by mrniko** [comment]
> No master available among the configured addresses, please check your configuration.

This issue appears until AWS assign a new master node.

**Comment by mrniko** [comment]
Fixed. Thanks for report
