### ISSUE TITLE
Redisearch get index info throws NumberFormatException

### ISSUE THREAD

**Issue by languanghao** [redisson/redisson#5398]
When get index info use redisson
```
 val search = client.getSearch(StringCodec.INSTANCE)
 val info = search.info("MY_INDEX_NAME")
```

**Expected behavior**
Return correct index info.

**Actual behavior**
![image](https://github.com/redisson/redisson/assets/3765379/fa10d0c0-2245-470d-a11a-a51e242f16f7)

![image](https://github.com/redisson/redisson/assets/3765379/d729cafc-aff4-4048-8a6d-0a456016a6aa)

This problem because `records_per_doc_avg` is a double value.

**Steps to reproduce or test case**

**Redis version**
![image](https://github.com/redisson/redisson/assets/3765379/a2379561-3dc2-482b-8d69-8833c91d3c69)

**Redisson version**
3.23.2

**Redisson configuration**

**Comment by mrniko** [comment]
Fixed. Thanks for report
