### ISSUE TITLE
Why does not use ConcurrentMap<K, V> as local cache for RedissonLocalCacedMap?

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#5406]
Hi,
I'm using RedissonLocalCacedMap and just read data from local use `getCachedMap().get(objectKey)` and I just facing with slow response time on PROD environment.
The root cause: Netty version 4.1.94.Final makes `localCacheView.toCacheKey(key)` run into slowness and `getCachedMap().get(objectKey)` becomes slow. Upgrading netty to 4.1.100.Final helps to fix the problem.
And I just wonder that in RedissonLocalCacedMap.class why doesn't Redisson use `private ConcurrentMap<K, V> cache;`  instead of `private ConcurrentMap<CacheKey, CacheValue> cache;`? It will help the local run faster than the current.

Thank you

**Comment by mrniko** [comment]
> private ConcurrentMap<K, V> cache; instead of private ConcurrentMap<CacheKey, CacheValue> cache;

To avoid serializing the entire key key during cache invalidation.
