### ISSUE TITLE
ContainsKeyAsync does not complete the promise if loader is not defined causing storeCacheMiss to be ineffective

### ISSUE THREAD

**Issue by ashishkf** [redisson/redisson#5411]
This causes an issue:

`RLocalCachedMap<Long, Boolean> cache = _client.getLocalCachedMap(s,
                        LocalCachedMapOptions.<Long, Boolean>defaults()
                                .storeCacheMiss(true);
Boolean b = cache.containsKey("test", 123); // Fetches the key from redis server
b = cache.containsKey("test", 123); // Fetches the key from the redis server again.
`

https://github.com/redisson/redisson/blob/047e9661de9215c0912affa7c8b215c5753c611e/redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java#L237
The promise defined in the above code that updates local cache is never invoked by the code below:

https://github.com/redisson/redisson/blob/047e9661de9215c0912affa7c8b215c5753c611e/redisson/src/main/java/org/redisson/RedissonMap.java#L561C1-L562C1

**Comment by ashishkf** [comment]
The same problem is there in get also.

**Comment by ashishkf** [comment]
Worse, the containsKey installs a "null" value in the cache: https://github.com/redisson/redisson/blob/047e9661de9215c0912affa7c8b215c5753c611e/redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java#L239

So, the next get will return "null" value and next containsAsync will return false.

**Comment by mrniko** [comment]
Can you try it with attached version?

[redisson-3.24.4-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/13264436/redisson-3.24.4-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed. Thanks for report
