### ISSUE TITLE
org.redisson.client.RedisTimeoutException

### ISSUE THREAD

**Issue by Jhsrk** [redisson/redisson#5414]
双云链接redis，其中一云链接redis专线波动 后续恢复，但redisson未恢复。

redisson版本：3.12.0

org.redisson.client.RedisTimeoutException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=31, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=http://10.10.2.63:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1549162433 [redisClient=[addr=http://10.10.2.63:6379], channel=[id: 0xa410caf6, L:/10.61.147.131:40254 - R:10.10.2.63/10.10.2.63:6379]], command: (EXISTS), command params: [activity_redisLock_carbon_activity_send_reward:DQ0000200512311071XSA01] after 5 retry attempts

**Comment by mrniko** [comment]
Unable to reproduce with the latest version. Failover handling has been improved since 3.12.0 version.

**Comment by Jhsrk** [comment]
Do you have any good suggestions

**Comment by Jhsrk** [comment]
> Unable to reproduce with the latest version. Failover handling has been improved since 3.12.0 version.

Do you have any good suggestions

**Comment by eldarbogdanov** [comment]
@Jhsrk The implied suggestion is to upgrade Redisson client version to a more recent one.
