### ISSUE TITLE
Multiple Redisson Clients that talk to different clusters

### ISSUE THREAD

**Issue by narendravardi** [redisson/redisson#5418]
After coming across the following issue: https://github.com/redisson/redisson/issues/4870, I have an idea to use two Redisson clients in my application to avoid down time in case of ElastiCache migration. 

My plan is to migrate from `Cluster Mode Disabled` to `Cluster Mode Enabled`.

Currently using `3.17.3` version of redisson client. 

Can you please let me know if there are any known problems that I should be aware of, in case of using two clients in the same application (other than setting up proper config for the respective clients) ?

**Comment by narendravardi** [comment]
@krinklesaurus and @ble180 will you be able to help with above query?

**Comment by mrniko** [comment]
You can use Redisson clients connected to different Redis deployments.

**Comment by narendravardi** [comment]
I have also tested with two different clusters on a single spring boot application. This works, thanks!
