### ISSUE TITLE
为啥 3.24.3 中使用 netty 的 4.1.34.Final 然后这个里面 没有 DnsNameResolverBuilder.socketChannelType 这个 method ，直接报错了

### ISSUE THREAD

**Issue by 1650987523** [redisson/redisson#5421]
nested exception is java.lang.NoSuchMethodError: io.netty.resolver.dns.DnsNameResolverBuilder.socketChannelType(Ljava/lang/Class;)Lio/netty/resolver/dns/DnsNameResolverBuilder;

**Comment by mrniko** [comment]
You need to update netty libraty.
