### ISSUE TITLE
Is the getLock method thread-safe?

### ISSUE THREAD

**Issue by tianmingxing** [redisson/redisson#5437]
I would like to know if the following method is thread-safe and if it is then there is no need to create a new instance on every request?

```java
org.redisson.api.RedissonClient.getLock(...)
```

If you can reuse instances you don't need to recreate them every time a request comes in!

```java
    @Override
    public RLock getLock(String name) {
        return new RedissonLock(connectionManager.getCommandExecutor(), name);
    }
```

**Comment by mrniko** [comment]
It's fully thread-safe.
