### ISSUE TITLE
CROSSSLOT keys in request don't has to same slot

### ISSUE THREAD

**Issue by laxman-edara** [redisson/redisson#5449]
I am using the following configuration 
Config config = new Config();
MasterSlaveServerConfig clusterServerConfig = config.useMasterSlaveServers().setMasterAddress("redis://127.0.0.1:7000").addSlaveAdddress("redis://127.0.0.1:7001", "redis://127.0.0.1:7002");
RedissonClient client = Redisson.create(config);

 TestIndexed item1 = new TestIndexed("1");
        item1.setName1("testnma");
        item1.setName2("gfgfgf");
        item1.setNum1(123);

        TestIndexed item2 = new TestIndexed("2");

        List<TestIndexed> s = liveObjectService.persist(item1, item2);

@REntity
    public static class TestIndexed implements Serializable {
        
        @RId
        private String id;
        @RIndex
        private String name1;
        @RIndex
        private String name2;
        @RIndex
        private Integer num1;
        @RIndex
        private Boolean bool1;
        @RIndex
        private TestIndexed obj;
        @RIndex
        private int num2;

        private List<Long> coll;

        protected TestIndexed() {
        }
        
        public TestIndexed(String id) {
            super();
            this.id = id;
        }

        public String getId() {
            return id;
        }

        public List<Long> getColl() {
            return coll;
        }

        public void setColl(List<Long> coll) {
            this.coll = coll;
        }

        public Boolean getBool1() {
            return bool1;
        }
        public void setBool1(Boolean bool1) {
            this.bool1 = bool1;
        }

        public String getName1() {
            return name1;
        }
        public void setName1(String name1) {
            this.name1 = name1;
        }

        public Integer getNum1() {
            return num1;
        }
        public void setNum1(Integer num1) {
            this.num1 = num1;
        }

        public TestIndexed getObj() {
            return obj;
        }
        public void setObj(TestIndexed obj) {
            this.obj = obj;
        }

        public String getName2() {
            return name2;
        }

        public void setName2(String name2) {
            this.name2 = name2;
        }

        public int getNum2() {
            return num2;
        }

        public void setNum2(int num2) {
            this.num2 = num2;
        }
    }

=========================
Getting the following exception
org.redisson.client.RedisException: CROSSSLOT keys in request don't has to same slot.

**Comment by mrniko** [comment]
Which Redisson version?

**Comment by mrniko** [comment]
Did you try useClusterServers() config?

**Comment by laxman-edara** [comment]
I tried useClusterServers() from config, keep getting a debug message from multiple slots from the cluster and data is not inserting in Redis. So I changed to useMasterSlaveServers(), then getting that message.

**Comment by mrniko** [comment]
> I tried useClusterServers() from config, keep getting a debug message from multiple slots from the cluster and data is not inserting in Redis.

Can you share the log since the start moment?

**Comment by laxman-edara** [comment]
Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.useClusterServers()
                .addNodeAddress("redis://127.0.0.1:7000"); // using cluster on 7000, 70001, 7002
        config.setAddressResolverGroupFactory(new DnsAddressResolverGroupFactory());
        clusterServersConfig.setScanInterval(2000);
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());
        JsonJacksonCodec codec = new JsonJacksonCodec(mapper);
        config.setCodec(codec);
        RedissonClient redisson = Redisson.create(config);

        RTransaction rTransaction = redisson.createTransaction(TransactionOptions.defaults());

        RLiveObjectService liveObjectService = redisson.getLiveObjectService();
        TestIndexed item1 = new TestIndexed("1");
        item1.setName1("testnma");
        item1.setName2("gfgfgf");
        item1.setNum1(123);

        TestIndexed item2 = new TestIndexed("2");

        List<TestIndexed> s = liveObjectService.persist(item1, item2);
        rTransaction.commit();

**Comment by laxman-edara** [comment]
This is the log statement
=======================================
09:05:22.795 [redisson-netty-2-2] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7000:
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 myself,master - 0 1700834721000 1 connected 0-5460
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 master - 0 1700834721214 2 connected 5461-10922
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 master - 0 1700834722219 3 connected 10923-16383

09:05:27.799 [redisson-netty-2-7] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7001:
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 master - 0 1700834726739 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834727241 1 connected 0-5460
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 myself,master - 0 1700834726000 2 connected 5461-10922

09:05:32.803 [redisson-netty-2-7] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7001:
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 master - 0 1700834732261 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834732000 1 connected 0-5460
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 myself,master - 0 1700834729000 2 connected 5461-10922

09:05:37.808 [redisson-netty-2-8] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7002:
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 master - 0 1700834736283 2 connected 5461-10922
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 myself,master - 0 1700834736000 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834737288 1 connected 0-5460

09:05:42.813 [redisson-netty-2-7] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7001:
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 master - 0 1700834742313 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834742000 1 connected 0-5460
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 myself,master - 0 1700834740000 2 connected 5461-10922

09:05:47.817 [redisson-netty-2-8] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7002:
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 master - 0 1700834747331 2 connected 5461-10922
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 myself,master - 0 1700834746000 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834746327 1 connected 0-5460

09:05:52.822 [redisson-netty-2-7] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7001:
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 master - 0 1700834751349 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834752354 1 connected 0-5460
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 myself,master - 0 1700834751000 2 connected 5461-10922

09:05:57.826 [redisson-netty-2-7] DEBUG org.redisson.cluster.ClusterConnectionManager - cluster nodes state got from 192.168.56.105/192.168.56.105:7001:
c47c707d696bee17e308375c0fb5b10a1875cff1 192.168.56.105:7002@17002 master - 0 1700834757373 3 connected 10923-16383
f569ac1c7b3e3c619c035d58c2b542df4e3be047 192.168.56.105:7000@17000 master - 0 1700834756369 1 connected 0-5460
97b1305d4e27e7769ace17999cd06894ed28ecc1 192.168.56.105:7001@17001 myself,master - 0 1700834754000 2 connected 5461-10922

**Comment by laxman-edara** [comment]
org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x1934ae98, L:/192.168.56.1:65129 - R:192.168.56.105/192.168.56.105:7000] command: (EVAL), promise: java.util.concurrent.CompletableFuture@708cf433[Not completed], params: [local oldArg = redis.call('hget', KEYS[2], ARGV[2]);if oldArg == false then return; end;redis.call('hdel', KEYS[2], ARGV[2]); local hash = redis.call('hget', KEYS[1], oldArg); local setName = KEYS[1] .. ':' .. hash; local res = redis.call('srem', setName, ARGV[1]); if res == 1 and redis.call('scard', setName) == 0 then redis.call('hdel', KEYS[1], oldArg); end; , 2, redisson_live_object_index:{net.jpmchase.sample.service.TestIndexed}:name2, redisson_live_object:{223122}:net.jpmchase.sample.service.TestIndexed, PooledUnsafeDirectByteBuf(ridx: 0, widx: 3, cap: 256), PooledUnsafeDirectByteBuf(ridx: 0, widx: 7, cap: 256)]

	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:381)
	at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:279)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:217)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by laxman-edara** [comment]
The login in the library is hung up when I tried with clustered configuration. 
It is hung up in the following location of the code

ClassIntrospector.get.rest();
batchService.execute();

**Comment by mrniko** [comment]
Fixed. Thanks for report
