### ISSUE TITLE
Unable to write command into connection! Increase nettyThreads setting.

### ISSUE THREAD

**Issue by turtoise** [redisson/redisson#5450]
Hi，my redisson version is 3.24.3, the  config is as follows :
![image](https://github.com/redisson/redisson/assets/19393229/0fce86e4-eb2f-40eb-a441-8657bf18c62c)

My program occasionally encounters the following error：
![Uploading image.png…]()

I already increase nettyThreads to 128,but it still doesn't work! Can anyone help solve the problem?

**Comment by mrniko** [comment]
can you share a full stacktrace?

**Comment by mrniko** [comment]
Did you check CPU usage of the JVM at that moment?
