### ISSUE TITLE
Large number of org.redisson.PubSubMessageListener objects

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#5451]
@mrniko We are seeing a large number of PubSubPatternMessageListener objects that are causing OutOfMemory issues.
We are using redisson version 3.23.5. 
Can you please let us know when do we create PubSubMessageListener objects. We have quite a large number of them >1000k that are holding references to heavier objects that we have otherwise discarded from our end but seems that the pubsubmessage listener is holding references to them causing OOM.

When analysing OOM, we check for the GC root for the pub sub message listener object and we see some Concurrent Hash Map Node. Not sure if there is any static map that is causing this issue.

**Comment by mrniko** [comment]
PubSubPatternMessageListener might be created by RLocalCachedMap instance

**Comment by jainyash88** [comment]
@mrniko We are using RLocalCachedMap from beginning. So it was there even with 3.18. However we see the GC root for the objects that are held by the NoneCacheMap inside of PubSubPatternMessageListener holding this. Is there a way that we can ensure this would not be used and or cleared?

**Comment by mrniko** [comment]
Is there any way to reproduce it?
