### ISSUE TITLE
java.util.concurrent* objects are not compatible with JDK-17

### ISSUE THREAD

**Issue by nikhil-sec** [redisson/redisson#5452]
For a junit, trying to create a redis object with atomic variable. It's failing on jdk17.
**Expected behavior**
Should work without any exception.
**Actual behavior**
Throws an exception:
```
com.esotericsoftware.kryo.KryoException: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile int java.util.concurrent.atomic.AtomicInteger.value accessible: module java.base does not "opens java.util.concurrent.atomic" to unnamed module @2abf4075
```

**Steps to reproduce or test case**
1. Pojo Object
```
@Data
@NoArgsConstructor
public class MyObject implements Serializable {
   private AtomicInteger count = new AtomicInteger(0);
}
```
3. Create map
```
MyObject myObject = new MyObject();
RMap<String, MyObject> mapOfCount = redisson.getMap("count");
mapOfCount.put("count", myObject);
```
**Redis version**
Jedis: 3.5.1
jedis-mock: 1.0.2
**Redisson version**
3.23.5
**Redisson configuration**
```
Config rconfig = new Config();
String raddr = "redis://localhost:8888";
rconfig.useSingleServer().setAddress(raddr);
redisson = Redisson.create(rconfig);
```

Reference: https://github.com/EsotericSoftware/kryo/issues/885#issuecomment-1359599242

**Comment by mrniko** [comment]
you can either change the codec or add JVM args `--add-opens java.base/java.util.concurrent=ALL-UNNAMED`
