### ISSUE TITLE
lettuce and redission-spring-boot-starter cannot be used at the same time

### ISSUE THREAD

**Issue by OakLi** [redisson/redisson#5453]
The redisTemplate originally built by LettuceConnectionFactory in the project could not be started after the redission-spring-boot-starter was introduced. After the analysis, LettuceConnectionFactory and RedissonConnectionFactory in RedissonAutoConfiguration cannot exist at the same time, is there a way to solve the problem of this redisTemplate using lettuce and then using redission

**Comment by activx** [comment]
Hi!, I resolved this issue using the following approach:

`
@Configuration
@AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE) // Or other priorities
@Import(RedisAutoConfiguration.class)
public class RedisAutoConfigOrderConfiguration {
}
`
I added empty configuration with HIGHEST  order, and imported RedusAutoConfig

**Comment by WangJincheng4869** [comment]
> Hi!, I resolved this issue using the following approach:
> 
> ```
> @Configuration
> @AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE) 
> @Import(RedisAutoConfiguration.class)
> public class RedisAutoConfigOrderConfiguration {
> }
> ```
> 
> I added empty configuration with HIGHEST order, and imported RedusAutoConfig

使用这种方法目前最大的弊端是导致无法自定义 RedisTemplate，我目前使用以下方式临时解决。

```
    /**
     * 通过 BeanPostProcessor 修改自动配置的 redisTemplate 的序列化器
     * 不产生 Bean 名称冲突，不需要开启覆盖
     */
    @Bean
    public static BeanPostProcessor redisTemplateCustomizer() {
        return new BeanPostProcessor() {
            @Override
            public Object postProcessAfterInitialization(@NonNull Object bean, @NonNull String beanName) throws BeansException {
                if ("redisTemplate".equals(beanName) && bean instanceof RedisTemplate<?, ?> redisTemplate) {
                    redisTemplate.setKeySerializer(RedisSerializer.string());
                    redisTemplate.setValueSerializer(RedisSerializer.json());
                    redisTemplate.setHashKeySerializer(RedisSerializer.string());
                    redisTemplate.setHashValueSerializer(RedisSerializer.json());
                    redisTemplate.afterPropertiesSet();  // 重要：重新初始化
                }
                return bean;
            }
        };
    }
```
