### ISSUE TITLE
Unable to send PING command over channel

### ISSUE THREAD

**Issue by lcvg** [redisson/redisson#5454]
When using  redission 3.13.1 , find this problem When the application is running normally .
Under what circumstances would this problem occur?

exception log：
o.r.c.handler.PingConnectionHandler     |Unable to send PING command over channel: [id: 0x6be72845, L:/195.161.226.24:49486 - R:/10.104.129.24:6379]
io.netty.util.concurrent.DefaultPromise$LeanCancellationException: null
io.netty.util.concurrent.DefaultPromise.cancel(...)(Unknown Source)

**Comment by mrniko** [comment]
Did you resolve it?

**Comment by wjdxw** [comment]
@lcvg  can you tell me how to fix this question? i has the same problems

**Comment by lcvg** [comment]
> @lcvg can you tell me how to fix this question? i has the same problems

You can try setting the pingConnectionInterval and nettyThreads parameters larger.
