### ISSUE TITLE
Heapdump for Redisson version 3.23.5 shows PubSubPatternMessageListener objects that are holding references to other large objects in redis no longer used

### ISSUE THREAD

**Issue by jainyash88** [redisson/redisson#5465]
Hello @mrniko 

Please note that we are seeing some OOM issues when upgrading to redisson version 3.23.5. On checking the heap dump, we see that the dump is having references to objects as part of the NoneCacheMap inside of the PubSubPatternMessageListener. We do NOT see the same when using redisson version 3.18.*

![Redisson-3 23-HeapDumpImage](https://github.com/redisson/redisson/assets/52423527/5c4ebf83-b831-4c81-bf62-559d04f5467c)

Can you please help to check if these NoneCacheMaps as part of PatternMessageListener are holding references that are causing them NOT to be Garbage Collected.

Please note that we are running in to this on our Production application that is causing significant outages.

**Comment by mrniko** [comment]
you need to set useKeyEventsPattern = false

**Comment by mrniko** [comment]
do you invoke RLocalCachedMap.destroy() method if instance is no longer needed?

**Comment by jainyash88** [comment]
@mrniko We invoke clearLocalCache() method on the RLocalCachedMaps. Do we need to invoke destroy also in addition to clearLocalCache()?

Also we use a n RMap also and I can see from code that it is also inheriting from `RDestroyable`. Do we need to invoke destroy on RMap as well?

**Comment by mrniko** [comment]
>  Do we need to invoke destroy also in addition to clearLocalCache()?

Only if this particular map instance isn't used anymore.

> Do we need to invoke destroy on RMap as well?

Only if this writeMode = WRITE_BEHIND for this map instance.

**Comment by jainyash88** [comment]
Hello @mrniko 

We are still facing OOM even after destroying the RLocalCachedMap. We see a lot of instances of PubSubPatternMessageListener that are reserving the heap space causing an OOM.

![Screenshot 2024-01-08 101449](https://github.com/redisson/redisson/assets/52423527/f440eee2-acd2-4e8e-ae38-6e1b348d74ff)

![Screenshot 2024-01-08 101247](https://github.com/redisson/redisson/assets/52423527/e9c2d823-47b1-4974-a934-0a6aaae3907c)

![Screenshot 2024-01-08 101123](https://github.com/redisson/redisson/assets/52423527/1fe255d5-bd2f-4999-ba1b-569b405184cc)

As shown in above screenshot, we see that the references to PubSubPatternMessageListener are somehow held by some map. When I tried looking at the code, I could see that `channelListeners ` instance might hold the PubSubPatternMessageListener objects but I am not sure.

Below is the class that I am referring to 

`public class PubSubConnectionEntry {

    private final AtomicInteger subscribedChannelsAmount;
    private final RedisPubSubConnection conn;

    private final ConcurrentMap<ChannelName, SubscribeListener> subscribeChannelListeners = new ConcurrentHashMap<ChannelName, SubscribeListener>();
    private final ConcurrentMap<ChannelName, Queue<RedisPubSubListener<?>>> channelListeners = new ConcurrentHashMap<ChannelName, Queue<RedisPubSubListener<?>>>();
`

Can you please help to understand the problem and if there is anything that we can do about this. Please note this is affecting our production systems after upgrading to 3.23

**Comment by mrniko** [comment]
try to upgrade to 3.23.3 version. It disables RedissonPatternTopic usage by default

**Comment by jainyash88** [comment]
@mrniko Do we have a way to disable the usage of listeners for RLocalCachedMaps? We see that listeners are the ones that are causing us the issues mostly. We do not want to listen to the updates for the map entries since our use case is such that we do not  have updates to the map after its seeded. Do we have any such mode/configuration for RLocalCachedMap that it does not create any listeners and it just stores values locally in a bounded fashion when it is fetched the first time?

**Comment by mrniko** [comment]
listener is used to monitor `expired` Redis event. It occurs when the map object has expired.

**Comment by jainyash88** [comment]
@mrniko Regarding your comment to use 3.23.3 version, please note that we are already using 3.23.+ in our gradle. So we are using the latest for 3.23.x version which is 3.23.5 I believe.

**Comment by mrniko** [comment]
@jainyash88 

make sure that useKeyEventsPattern = false for your local cache instance.

**Comment by mrniko** [comment]
@jainyash88 

I'll introduce a setting to disable listening for expiration events.

**Comment by jainyash88** [comment]
@mrniko I checked the source code and I could see that if we set useKeyEventsPattern = false, we are still creating RedissonTopic for the CacheListener which will still listen to expiryEvents. Not sure if that will still have these Listener Objects being created

**Comment by jainyash88** [comment]
@mrniko Does the RedissonTopic also create listener objects similar to the RedissonPatternTopic?

**Comment by mrniko** [comment]
@jainyash88 

> @mrniko I checked the source code and I could see that if we set useKeyEventsPattern = false, we are still creating RedissonTopic for the CacheListener which will still listen to expiryEvents. Not sure if that will still have these Listener Objects being created

https://github.com/redisson/redisson/issues/5465#issuecomment-1881031095

**Comment by mrniko** [comment]
@jainyash88 

`LocalCachedMapOptions.expirationEventPolicy` setting added
