### ISSUE TITLE
Scheduled tasks abruptly stop being scheduled and executed

### ISSUE THREAD

**Issue by 110Sw1t** [redisson/redisson#5467]
**Expected behavior**

Scheduled tasks should be scheduled continuously.

**Actual behavior**

Some scheduled tasks stop being executed after a while, lets say we have task that is scheduled every 5 minutes, task gets scheduled normally every 5 minutes according to a cron expression "0 0/5 * * * ?", after a couple of weeks its seen that this task abruptly stops being scheduled.

**Steps to reproduce or test case**
It's an intermittent issue.

**Redis version**
6.0.5

**Redisson version**
3.17.0

**Redisson configuration**
conf.setNettyThreads(32);
conf.setCodec(new JsonJacksonCodec());
conf.useSingleServer()

**Comment by mrniko** [comment]
Do you see any exceptions in logs?
