### ISSUE TITLE
org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot.

### ISSUE THREAD

**Issue by iridescenceZz** [redisson/redisson#5479]
I encountered the following issues while using RQueue#V pollLastAndOfferFirstTo(String queueName).

Redis version 6.2.6
Redisson version 3.23.5
Mode cluster

Config config = new Config();
        config.useClusterServers().setTimeout(5000);
        String url = "redis://172.XX.XX.XXX:6666";
        String url1 = "redis://172.XX.XX.XXX:6666";
        String url2 = "redis://172.XX.XX.XXX:6666";
        config.useClusterServers().addNodeAddress(url, url1, url2);
        config.useClusterServers().setPassword("abc");
        RedissonClient redissonClient = Redisson.create(config);

        String key1 = "redis_key_1";
        RDeque<String> deque = redissonClient.getDeque(key1);
        deque.addFirst("aaaa");
        String key2 = "redis_key_2";
        RDeque<String> deque1 = redissonClient.getDeque(key1);
        Object o = deque1.pollLastAndOfferFirstTo(key2);

 ERROR:org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x6617f095, L:/XXX.XX.XX.XXX:54612 - R:XXX.XX.XX.XXX/XXX.XX.XX.XXX:6666] command: (RPOPLPUSH), promise: java.util.concurrent.CompletableFuture@6b7aa9b3[Not completed, 1 dependents], params: [redis_key_1, redis_key_2]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:381)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:205)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:144)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:120)

**Comment by mrniko** [comment]
both keys should be located on the same slot.

**Comment by iridescenceZz** [comment]
> both keys should be located on the same slot.

I know ，I can set two keys on the same slot by using redis_key_{xxx}, but this is not friendly to the business.

**Comment by mrniko** [comment]
I'm afraid there is no other way to do it.
