### ISSUE TITLE
Support for the new AWS Serverless ?

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#5483]
I know it is a generic question, and AWS Serverless is a very very new offering.

Are you looking at the compatibility between redisson and AWS Serverless ?
And document how to connect to it ?

Thanks

**Comment by mrniko** [comment]
I don't see any difference between AWS Elasticache and AWS Elasticache Serverless in terms of Redis API. https://aws.amazon.com/elasticache/features/#Serverless

Is there any issue?
