### ISSUE TITLE
What are the benefits of using resp3? There is no explanation in the document. I hope you can listen to the author's explanation. Thank you

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#5485]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Improvements in the protocol and https://redis.io/docs/latest/commands/client-tracking/ support. You can use it by adding 
 `org.redisson.api.listener.TrackingListener` to RBucket and other objects.
