### ISSUE TITLE
Hope to support virtual threads, or provide an interface that can rewrite the thread pool

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#5486]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Can you clarify which thread pool you need to rewrite?

**Comment by mrniko** [comment]
It's done.

Below is the code example.

```java
Config c = redisson.getConfig();
c.setNettyExecutor(Executors.newVirtualThreadPerTaskExecutor());

RedissonClient r = Redisson.create(c);
```
