### ISSUE TITLE
RateLimiter's tryAcquire not working when being used with setRate

### ISSUE THREAD

**Issue by andreas-ajaib** [redisson/redisson#5487]
I have this implementation of Redisson's rate limiter on my reactive Spring Boot app. The rate limiter initially was working when using `trySetRate`. However when we switch to `setRate`, the `tryAcquire` no longer working.
**UPDATE:** apparently it's also affecting non-reactive object.

**Expected behavior**
`tryAcquire` returns false when permit should be ran out.

**Actual behavior**
`tryAcquire` returns true even though permit should be ran out.

**Steps to reproduce or test case**
***not working***
reactive
```java
private Mono<Boolean> getPermit(String userId) {
    RRateLimiterReactive limiter = businessRedis.getRateLimiter("rate-limit:" + userId);
    return limiter.setRate(RateType.OVERALL, rateLimitRate, rateLimitInterval, getRateLimitIntervalUnit())
            .then(Mono.defer(limiter::tryAcquire));
}
```
non-reactive
```java
final var rateLimiter = client.getRateLimiter("test");
rateLimiter.setRate(RateType.OVERALL, 5, 1, RateIntervalUnit.MINUTES);
rateLimiter.tryAcquire(); // hit 6 times still true
```

***working***
reactive
```java
private Mono<Boolean> getPermit(String userId) {
    RRateLimiterReactive limiter = businessRedis.getRateLimiter("rate-limit:" + userId);
    return limiter.trySetRate(RateType.OVERALL, rateLimitRate, rateLimitInterval, getRateLimitIntervalUnit())
            .then(Mono.defer(limiter::tryAcquire));
}
```
non-reactive
```java
final var rateLimiter = client.getRateLimiter("test");
rateLimiter.trySetRate(RateType.OVERALL, 5, 1, RateIntervalUnit.MINUTES);
rateLimiter.tryAcquire(); // hit 6 times, the 6th is false
```

**Redis version**

**Redisson version**
3.17.7, 3.25.0

**Redisson configuration**
```java
public RedissonReactiveClient redis() {
    Config config = new Config();
    config.useSingleServer().setAddress(redisHost);
    config.useSingleServer().setPassword(redisPassword);

    RedissonClient redisson = Redisson.create(config);
    return redisson.reactive();
}
```

**Comment by andreas-ajaib** [comment]
So, it needs to be used with trySetRate? setRate cannot be used independently? In my case I used setRate only without trySetRate

**Comment by mrniko** [comment]
use setRate if you don't want to check if settings have already been set.
