### ISSUE TITLE
NoClassDefFound io/netty/channel/kqueue/KQueueSocketChannel

### ISSUE THREAD

**Issue by dBransky** [redisson/redisson#5491]
**Expected behavior**
There should be no error building the latest version

**Actual behavior**
when importing class RedisClient from org.redisson.client.RedisClient and trying to build version 3.25 the build fails with error 
NoClassDefFound io/netty/channel/kqueue/KQueueSocketChannel

**Steps to reproduce or test case**
in pom.yml file 
<dependency>
        <groupId>org.redisson</groupId>
        <artifactId>redisson</artifactId>
        <version>3.25.0</version>
    </dependency>
then create a java class that imports org.redisson.client.RedisClient create a simple redis client 
 RedisClientConfig config = new RedisClientConfig();
 config.setAddress(SERVERLESS_ENDPOINT,6379);
 redisClient = RedisClient.create(config);

**Redis version**
Elasticache serverless redis 7

**Redisson version**
3.25

**Redisson configuration**
as stated above

**Comment by dBransky** [comment]
hello, 
the problem still persists 
````<dependencies>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-bom</artifactId>
        <version>${netty.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    <dependency>
        <groupId>io.netty</groupId>
        <version>${netty.version}</version>
        <artifactId>netty-transport-native-kqueue</artifactId>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
<dependency>
        <groupId>org.redisson</groupId>
        <artifactId>redisson</artifactId>
        <version>[3.0,4.0)</version>
    </dependency>``

**Comment by mrniko** [comment]
Can you import suggested jar and not a pom?
