### ISSUE TITLE
redisson 3.25.0 occured exception：Unable to send PING command over channel

### ISSUE THREAD

**Issue by danfengqingyi** [redisson/redisson#5493]
redisson 3.12.3 is OK
After upgrading to version 3.25.0，an exception  of  Unable to send PING command over channel will occur
Change points：
1、		<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.25.0</version>
		</dependency>
2、Updated from pingTimeout: 1000 to pingConnectionInterval: 1000 ，and deleted the tow configurations of reconnectionTimeout: 3000 and failedAttempts: 3 in singleServerConfig

**Comment by mrniko** [comment]
`failedSlavesReconnectionTimeout` and `failedAttempts` weren't applied

**Comment by mrniko** [comment]
Can you share Redisson config?

**Comment by danfengqingyi** [comment]
> Can you share Redisson config?

singleServerConfig:
  idleConnectionTimeout: 10000
  #  pingTimeout 更新为 pingConnectionInterval: 1000
  pingConnectionInterval: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  #  reconnectionTimeout: 3000  已经没有了
  #  failedAttempts: 3  已经没有了
  password:
  subscriptionsPerConnection: 5
  clientName: null
  address: "@redisson.address@"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 3
  #  dnsMonitoring: false
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
#useLinuxNativeEpoll: false

**Comment by danfengqingyi** [comment]
> Can you share Redisson config?

singleServerConfig:
  idleConnectionTimeout: 10000
  #  pingTimeout 更新为 pingConnectionInterval: 1000
  pingConnectionInterval: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  #  reconnectionTimeout: 3000  已经没有了
  #  failedAttempts: 3  已经没有了
  password:
  subscriptionsPerConnection: 5
  clientName: null
  address: "@redisson.address@"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  database: 3
  #  dnsMonitoring: false
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
#useLinuxNativeEpoll: false

**Comment by mrniko** [comment]
can you share full stacktraces you see in the log?

**Comment by shiranyosef1** [comment]
I'm seeing the same behavior
```

<#f452eaaa> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://master.gong-prod.frethq.use1.cache.amazonaws.com:6379] 	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) 	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.lang.Thread.run(Thread.java:829)
--



```
with version `3.25.0`

**Comment by shiranyosef1** [comment]
I'm seeing the same behavior

<#f452eaaa> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=rediss://redis1...com:6379] 	at org.redisson.client.RedisConnection.lambda$async$0(RedisConnection.java:256) 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) 	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790) 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.lang.Thread.run(Thread.java:829)




```
with version `3.25.0`

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.26.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/14081605/redisson-3.26.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed. Thanks for report
