### ISSUE TITLE
The RTopic listener under the redis cluster cannot receive messages after a period of time

### ISSUE THREAD

**Issue by yanhuilin** [redisson/redisson#5501]
redisson version：3.15.6
redis cluster version：5.0.4

Hello, when we recently used redisson to connect to the redis cluster, we found that the RTopic listener always failed to receive messages after the service had been running for a period of time. This problem did not occur when we used sentinel mode before, and in redis It doesn't happen when the pressure is low. Is there any solution?

**Comment by yanhuilin** [comment]
This problem has been solved. We increased the number of idle subscription connections and the number of subscriptions per connection. The reason may be that extensive use of RLock results in insufficient connections. Each RLock will apply for an RTopic. At this time, a problem is triggered. After the subscription is disconnected, it will not continue to reconnect, resulting in the resident listener not being able to get the connection to receive information.

**Comment by mrniko** [comment]
Is there any code sample to reproduce it?

**Comment by mrniko** [comment]
With the latest version I'm getting the error below in case of subscription connections starvation. I recommend to update the Redisson version.

`Unable to acquire connection for subscription after 3 attempts. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.`
