### ISSUE TITLE
Thread block when use FairLock if lock unlock

### ISSUE THREAD

**Issue by UncleJuJu** [redisson/redisson#5503]
when i use fairlock，

if 2 thread come in，
if Thread-1 service spend more time (like 40s， watchdog 30s fresh)，
after a while Thread-2 will have to count a negative ttl，
then it will call `future.getNow().getLatch().acquireUninterruptibly();`.

When Thread-1 unlock, the quere which in redis will be remove, but Thread-2 will always block.

i don't know it right thing? Why Thread-2 have to block?

My redisson version is 3.12.0

**Comment by mrniko** [comment]
Is there any code to reproduce it?

**Comment by mrniko** [comment]
Try 3.32.0 version has a fix for the issue with incorrect calculation of the remaining ttl.
