### ISSUE TITLE
Make 

### ISSUE THREAD

**Issue by sumlittle** [redisson/redisson#5512]
My production environment is installed with jdk1.8.0_11. Recently I found that when I upgraded the redission version from 3.23.5 to 3.24.3, the program could not be started. After investigation, I found that there is no ExtendedSocketOptions class in jdk 1.8.0_11, so I would like to ask if there is a specific corresponding version of redission and jdk
![20231219113613](https://github.com/redisson/redisson/assets/95095875/4b0fa340-c815-443f-b4e8-b4a58c3d5d42)

**Comment by mrniko** [comment]
Can you try 3.25.1 version?

**Comment by sumlittle** [comment]
Ok. I will try.

**Comment by sumlittle** [comment]
I changed the version to redisson-spring-boot-starter 3.25.1 and redisson-spring-data-21 3.25.1 also. When i started the jar found the error like this:
![image](https://github.com/redisson/redisson/assets/95095875/3c2927e6-26bf-45c0-a817-aff1593a863e)

**Comment by sumlittle** [comment]
I changed the 3.25.1. And it can use
