### ISSUE TITLE
Redis SCAN cursor exceeds Long.MAX_VALUE resulting in NumberFormatException

### ISSUE THREAD

**Issue by vimalesh** [redisson/redisson#5517]
Redis SCAN cursor exceeds Long.MAX_VALUE resulting in NumberFormatException. The issue with Java signed long value decoding/parsing with Redis scan unsigned long cursor id. (https://github.com/spring-projects/spring-data-redis/issues/2796)

**Expected behavior**
SCAN command must work without any errors or exceptions

**Actual behavior**
Throws below exceptions
java.lang.NumberFormatException: For input string: "9286422431637965696"
org.redisson.client.RedisException: Unexpected exception while processing command

**Steps to reproduce or test case**
We are cleaning up Redis cache on System startup using RedissonClient.getKeys().getKeysByPattern("abc*", 1000); 
**Redis-cli output**
somevalue.serverless.use1.cache.amazonaws.com:6379> SCAN 0 MATCH "abc*" COUNT 100
1) "9286422431637964944"
2) 1) "abc-715E466A-3090-4DB7-A8A5-0E242B60DD06"
   2) "abc-8AD311AA-C36A-48AE-A431-C7DF57497439"

**Redis version**
We are using AWS Elasticache Redis 7.1 Serverless

**Redisson version**
Redissson v3.20.0 and v3.24.0
For Redisson v3.25.0 and v3.25.1 throws RedisTimeoutException/RedisConnectionException - The same configuration is working for Redissson v3.20.0 and v3.24.0 

**Redisson configuration**
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 120000
  retryAttempts: 3
  retryInterval: 1500
  username: null
  password: null
  subscriptionsPerConnection: 0
  clientName: ReeferServiceClient
  address: rediss://somevalue.serverless.use1.cache.amazonaws.com:6379
  subscriptionConnectionMinimumIdleSize: 25
  subscriptionConnectionPoolSize: 100
  connectionMinimumIdleSize: 24
  connectionPoolSize: 100
  database: 0
  dnsMonitoringInterval: 5000
  pingConnectionInterval: 30000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: NIO
lockWatchdogTimeout: 20000

**Comment by mrniko** [comment]
Fixed. Can you try the master branch?
