### ISSUE TITLE
Running Mapreduce example of the documentation 9.5.2 stucked in infinite loop and failed to get result!

### ISSUE THREAD

**Issue by sdzy00** [redisson/redisson#5530]
Hi!
I tried to running the mapreduce example in section 9.5.2 of the documentation. I didn't modify any code, but it was always blocked on 
`Map<String, Integer> mapToNumber = mapReduce.execute();`, and it seems to have entered an infinite loop.

I tried using `.timeout(30, TimeUnit.SECONDS)` after reducer but it didn't work.

Please tell me the reason, thanks a lot!

![微信图片_20231223121257](https://github.com/redisson/redisson/assets/58126114/e93ceb1b-a0e2-4efc-a3c0-3da02537172b)
![微信图片_202312231212571](https://github.com/redisson/redisson/assets/58126114/5da39593-65e8-4d27-a654-ae4710e1d7d1)
![微信图片_202312231212572](https://github.com/redisson/redisson/assets/58126114/23310396-7478-4bcf-9002-744f1bb65019)
![微信图片_202312231212573](https://github.com/redisson/redisson/assets/58126114/48ebf67e-abac-4aa3-8df9-292f3913658f)

**Comment by sdzy00** [comment]
It works on Windows but not on MacOS.
'Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.'

**Comment by mrniko** [comment]
this a classloader issue
