### ISSUE TITLE
lua script calc SHA error

### ISSUE THREAD

**Issue by quanchangnai** [redisson/redisson#5531]
Using LUA scripts in non English speaking regions may result in errors.
script.getBytes().The encoding here should be changed to UTF-8

   public class ServiceManager{

        public String calcSHA(String script) {
            return SHA_CACHE.computeIfAbsent(script, k -> {
                try {
                    MessageDigest mdigest = MessageDigest.getInstance("SHA-1");
                    byte[] s = mdigest.digest(script.getBytes());   //The encoding here should be changed to UTF-8
                    return ByteBufUtil.hexDump(s);
                } catch (Exception e) {
                    throw new IllegalStateException(e);
                }
        });
    }

}

**Comment by mrniko** [comment]
Fixed. Thanks for report
