### ISSUE TITLE
Can't pass each value as separate vm-argument using spring-boot-starter

### ISSUE THREAD

**Issue by Basavakumar-Raddi** [redisson/redisson#5542]
Was trying the [spring-boot-starter]((https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter) ) setup and want to setup the connection 

1. without passing the values in application.yaml 
2. not do the programatic approach of connecting to the redis, 

But finding it a bit odd that we have to pass the whole config object to connect. 

As example 
we need to pass the values like this if passing a vm-argument. Could be also configured from system-properties, config files, environment variables etc.
`-Dspring.redis.redisson.config="{ "singleServerConfig": { "address" : "redis://localhost:6379", "connectTimeout": 5555, "pingConnectionInterval": 150000, "connectionMinimumIdleSize": 57, "subscriptionConnectionMinimumIdleSize": 7 }, "nettyThreads": 55 }"` 

But wondering if I am missing something or dont know how to do it 🤷. If i want to just customise only one value lets say ping connection interval is it possible to pass it something like this ? `spring.redis.redisson.config.singleServerConfig.pingConnectionInterval = 10000 `

Currently as far as i have played around we have to pass the whole object(yaml as string) as above. Any inputs in this regard are welcome.

**Comment by mrniko** [comment]
You can do it through configuration variables https://redisson.org/docs/configuration/#variable-syntax
