### ISSUE TITLE
In read-write separation mode, how to ensure that the data read is the latest?

### ISSUE THREAD

**Issue by liuxinwen** [redisson/redisson#5544]
Hello everyone, does redission support the scenario of writing first and then reading data immediately in the same thread like Apache ShardingSphere, forcing the data to be read from the main library? This is done to solve the problem that the delay in master-slave replication data causes the read operation to obtain data that is not the latest.

**Comment by mrniko** [comment]
you can do it with RBucket.getAndSet() method
