### ISSUE TITLE
Continuously reconnecting to a removed slave node in cluster mode

### ISSUE THREAD

**Issue by guihuoliuying** [redisson/redisson#5547]
**Expected behavior**
Not to reconnect the removed slave node Continuously

**Actual behavior**
Reconnect the removed slave node Continuously

**Steps to reproduce or test case**
Redis is deployed in cluster mode(3 master and 3 slave), and Redisson is default configuration. When I remove a slave node and add a slave node at a certain moment, the dns resolution reflect the ip changes immediately, Redisson will continuously reconnecting to the removed slave node. Oppositely, there is no such issue with the same operation on master node. It seems that slave connection is out of management when redisson is in default configuration which means BaseMasterSlaveServersConfig.isSlaveNotUsed() == true.
Steps:
1. Redisson choose one slave node to send cluster nodes command(the connection kept in org.redisson.connection.MasterSlaveConnectionManager#nodeConnections).
2. Remove the slave node in step 1 and add another slave instead, and hostname resolution will reflect all the ip changes immediately.
3. ConnectionWatchdog will reconnect the slave node continuously. (Next time, Redisson call scheduleClusterChangeCheck(), it won't see the ip of removed slave node. So it won't connect the removed slave node, then lose the chance to close the connection kept in MasterSlaveConnectionManager#nodeConnections)

**Redis version**
6.2.11

**Redisson version**
3.25.2

**Redisson configuration**
Default

**Comment by mrniko** [comment]
Do you change ip resolved by hostname of a single slave node?

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by guihuoliuying** [comment]
@mrniko 
I have checked this fix in the release version 3.26.1 and 3.27.1, but the issue seems to be still there. What I think is that:
1. the actual type of MasterSlaveEntry is SingleEntry when isSlaveNotUsed() == true.
2. SingleEntry.getEntry() with slave address will always return null which cause MasterSlaveEntry.slaveDown() always returning false.
3. As the result, the disconnectUri() will be not executed.

I do the same test with the modification of moving the disconnectUri() outside the if statement, the issue seems to be disappeared.

**Comment by mrniko** [comment]
@guihuoliuying 

Fixed. Thanks for the update
