### ISSUE TITLE
Redisson with AWS Iam Auth credential with CredentialsResolver, limitations ?

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#5549]
Hi,
I made some code to connect to our redis elasticache with IAM authentication and CredientialsResolver,
very similar to your documentation
https://redisson.org/articles/how-to-connect-to-redis-using-elasticache-iam-credential-provider.html

AWS list some limitations when connecting to redis this way :
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html#auth-iam-limits
Mostly : IAM authentication is not supported in MULTI EXEC commands.

Is it a problem for some of the redisson features ?

Thanks

**Comment by mrniko** [comment]
Good point.

This affects RBatch objects with executionMode != IN_MEMORY
