### ISSUE TITLE
io.netty.channel.StacklessClosedChannelException连接泄露【bug】

### ISSUE THREAD

**Issue by sunwuxiang** [redisson/redisson#5553]
<img width="698" alt="1704554213226" src="https://github.com/redisson/redisson/assets/30144714/7fcaa754-6871-4a92-9a87-5cec734d32f1">

代码如上，version：3.16.4
分布式锁的时候，在断网后网络恢复后无法自动恢复

<img width="624" alt="1704554279810" src="https://github.com/redisson/redisson/assets/30144714/8392a4c4-f561-4572-b5ad-0f2ea051b9fd">

通过arthas分析，发现ClientConnectionsEntry里的allConnections和freeConnections都是空的了，但是freeConnectionsCounter还是3，如下图：
<img width="655" alt="4c74629319cc5da4314e31cf235b284" src="https://github.com/redisson/redisson/assets/30144714/523ce7b2-32ca-4f42-abd1-bae1c0e82213">

查看RedisConnection对象，发现有5个，但是我设置的连接池的min和max都是3，怎么会出来5呢，而且这几个连接的channel的isActive都是false
<img width="947" alt="fd551f28656f65134b777797fe2033c" src="https://github.com/redisson/redisson/assets/30144714/49ec20e5-2549-40d3-a3eb-4cee9f0ab74e">

**Comment by mrniko** [comment]
Unable to reproduce the issue with the latest version and test below.

```java
    @Test
    public void testFailoverInCluster() throws Exception {
        RedisRunner master1 = new RedisRunner().port(6890).randomDir().nosave();
        RedisRunner master2 = new RedisRunner().port(6891).randomDir().nosave();
        RedisRunner master3 = new RedisRunner().port(6892).randomDir().nosave();
        RedisRunner slave1 = new RedisRunner().port(6900).randomDir().nosave();
        RedisRunner slave2 = new RedisRunner().port(6901).randomDir().nosave();
        RedisRunner slave3 = new RedisRunner().port(6902).randomDir().nosave();
        RedisRunner slave4 = new RedisRunner().port(6903).randomDir().nosave();

        ClusterRunner clusterRunner = new ClusterRunner()
                .addNode(master1, slave1, slave4)
                .addNode(master2, slave2)
                .addNode(master3, slave3);
        ClusterRunner.ClusterProcesses process = clusterRunner.run();

        Thread.sleep(7000);

        Config config = new Config();
        config.useClusterServers()
                .setMasterConnectionPoolSize(3)
                .setMasterConnectionMinimumIdleSize(3)
                .setSlaveConnectionPoolSize(3)
                .setSlaveConnectionMinimumIdleSize(3)
                .setReadMode(ReadMode.MASTER)
                .addNodeAddress(process.getNodes().stream().findAny().get().getRedisServerAddressAndPort());
        RedissonClient redisson = Redisson.create(config);

        RedisRunner.RedisProcess master = process.getNodes().stream().filter(x -> x.getRedisServerPort() == master2.getPort()).findFirst().get();

        Deque<Boolean> status = new ConcurrentLinkedDeque<>();
        ExecutorService ee = Executors.newFixedThreadPool(8);
        Thread t = new Thread() {
            public void run() {
                for (int i = 0; i < 1000000; i++) {
                    ee.submit(() -> {
                        try {
                            redisson.getLock("lock").tryLock(3, 10, TimeUnit.SECONDS);
                            status.add(true);
                        } catch (Exception e) {
                            status.add(false);
                            e.printStackTrace();
                        }
                    });
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                }
            };
        };
        t.start();
        t.join(1000);

        Set<InetSocketAddress> oldMasters = new HashSet<>();
        Collection<RedisClusterMaster> masterNodes = redisson.getRedisNodes(org.redisson.api.redisnode.RedisNodes.CLUSTER).getMasters();
        for (RedisClusterMaster clusterNode : masterNodes) {
            oldMasters.add(clusterNode.getAddr());
        }

        master.stop();
        System.out.println("master " + master.getRedisServerAddressAndPort() + " has been stopped!");

        Thread.sleep(TimeUnit.SECONDS.toMillis(90));

        Thread.sleep(TimeUnit.SECONDS.toMillis(80));

        Awaitility.await().atMost(Duration.ofSeconds(60)).untilAsserted(() -> {
            assertThat(status.size()).isGreaterThan(2000);
        });

        assertThat(status.getLast()).isTrue();

        long success = status.stream().filter(s -> s).count();
        long errors = status.stream().filter(s -> !s).count();

        redisson.shutdown();
        process.shutdown();

        System.out.println("errors " + errors);
        System.out.println("success " + success);

    }
```

**Comment by sunwuxiang** [comment]
<img width="587" alt="微信图片_20240122184300" src="https://github.com/redisson/redisson/assets/30144714/a7361f0f-0337-4dd5-91d4-796552386778">

我发现，当redisclient的close为true的连接还在连接池被拿出来使用并放回去，但是当这个连接的channel因为网络抖动close的时候，这个连接无法恢复，因为在ConnectionWatchdog的tryReconnect中判断当redisclient的close为true，跳出重连，但是这个连接还在连接池被使用

<img width="506" alt="微信图片_20240122184613" src="https://github.com/redisson/redisson/assets/30144714/751d843a-adae-49db-a6cd-0b33364f8f2b">

是否可以在放回连接的时候判断当redisclient的close为true的时候，不放回连接，并且关闭连接，代码如：
<img width="449" alt="微信图片_20240122184835" src="https://github.com/redisson/redisson/assets/30144714/f6bce326-0dd7-4b8a-903f-319d3e130633">


我发现在这个连接在最开始被创建的时候redisclient的close就是true，应该在启动的时候就有bug，但是我没找到

**Comment by sunwuxiang** [comment]
提供这个连接创建时的日志供参考：

<img width="901" alt="1" src="https://github.com/redisson/redisson/assets/30144714/d13d86a5-41e0-4a92-ae9e-9f4afe1d1f6a">

<img width="905" alt="2" src="https://github.com/redisson/redisson/assets/30144714/ba5d6c46-680c-46ac-bce8-6c424a06449a">

<img width="879" alt="3" src="https://github.com/redisson/redisson/assets/30144714/f0467781-ee7f-43e1-99bf-9fea26196911">

**Comment by sunwuxiang** [comment]
不行，这个方案不行，他还是会重复初始化连接，还得从创建连接得时候找到问题原因

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/5553#issuecomment-1880535555

Can you try with the latest version?

**Comment by mrniko** [comment]
Which Redis vendor do you use? The actual problem that topology isn't refreshed.

**Comment by sunwuxiang** [comment]
https://github.com/redisson/redisson/assets/30144714/46f40527-4bac-4f79-a0f5-e6acc83136be

使用最新的3.29.0版本复现了，网络恢复后无法自动恢复，请看附件视频

操作步骤：启动，断开网络，过一会重连，如果自动恢复，再重新启动，断网重连，如果重复启动、断网、重连，基本三四次就可复现
<dependency>
			<groupId>org.redisson</groupId>
			<artifactId>redisson</artifactId>
			<version>3.29.0</version>
		</dependency>

`System.out.printf("133");
        SpringApplication.run(RedissonTest.class, args);
        System.out.printf("33");
        Config config = new Config();
        ClusterServersConfig clusterConfig = config.useClusterServers().setScanInterval(2000)
                .setKeepAlive(true).setMasterConnectionPoolSize(8).setMasterConnectionMinimumIdleSize(1)
                .setSlaveConnectionPoolSize(8).setSlaveConnectionMinimumIdleSize(1).setReadMode(ReadMode.valueOf("MASTER"));
        clusterConfig.setPingConnectionInterval(3000);
        clusterConfig.addNodeAddress("redis://common_microservice_redis-01_test.cowelltech.com:6379");
        config.setCodec(new JsonJacksonCodec());
        System.out.printf("22");
        RedissonClient redisson = Redisson.create(config);
        Executor pool = Executors.newFixedThreadPool(8);
        while(true) {
            if(rediscall == 1){
                pool.execute(() -> {
                    try {
                        boolean rLock = redisson.getLock("mike-test").tryLock(3, 10, TimeUnit.SECONDS);
                        System.out.println(rLock);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                });
            }

            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }`

**Comment by sunwuxiang** [comment]
@mrniko 麻烦看看

**Comment by mrniko** [comment]
Do you restart whole cluster 3-4 times?

**Comment by sunwuxiang** [comment]
restart the java application 3-4 time，not redis  cluster

**Comment by sunwuxiang** [comment]
restart the java application 3-4 time，not redis  cluster

**Comment by sunwuxiang** [comment]
操作的一直是client端的应用启动，端的也是client端的wifi网络，然后重连wifi，redis server一直不动

目前的redisson在启动的时候有一定概率使得连接的redisclient的shutdown等于true（应该和客户端的一堆散列node的并发逻辑没处理好有关系），在网络抖动是，这些edisclient的shutdown等于true的连接就不会被watchdog重试

**Comment by mrniko** [comment]
When does the issue happen? at Redisson start moment?

**Comment by mrniko** [comment]
Unable to reproduce. Below is the test.

```java
        testInCluster(client -> {
            for (int k = 0; k < 10; k++) {
                System.out.println("iteration " + k);
                Config config = client.getConfig();
                config.useClusterServers()
                        .setKeepAlive(true).setMasterConnectionPoolSize(8).setMasterConnectionMinimumIdleSize(1)
                        .setSlaveConnectionPoolSize(8).setSlaveConnectionMinimumIdleSize(1).setReadMode(ReadMode.valueOf("MASTER"));
                RedissonClient redisson = Redisson.create(config);

                Executor pool = Executors.newFixedThreadPool(8);
                for (int i = 0; i < 10; i++) {
                    pool.execute(() -> {
                        try {
                            boolean rLock = redisson.getLock("mike-test").tryLock(3, 10, TimeUnit.SECONDS);
                            System.out.println(rLock);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    });

                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }

                redisson.shutdown();
            }
        });
```

**Comment by sunwuxiang** [comment]
在一定概率的启动异常+后续网络断开，就会复现

**Comment by sunwuxiang** [comment]
<img width="871" alt="微信图片_20240520190329" src="https://github.com/redisson/redisson/assets/30144714/d6b508b3-a309-43fc-9058-aa22b433c9a6">
从日志看是并发导致的，一会shutdown，一边又当作新的entity放进去
以下方法是否可以解决这个问题，当entity放进去的时候判断redisclient的shutdown是true，就改成false
<img width="602" alt="微信图片_20240520190343" src="https://github.com/redisson/redisson/assets/30144714/dc1b58e6-2700-4de0-984e-85f3e1c0e9b5">
![Uploading 微信图片_20240520190347.png…]()

**Comment by mrniko** [comment]
Can you try attached version?

[redisson-3.31.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/15529923/redisson-3.31.1-SNAPSHOT.jar.zip)

**Comment by DaGuo776** [comment]
I'm encountering the same issue as sunwuxiang when using `redissonClient.getLock()` for distributed locking, especially after switching networks, which consistently reproduces this problem. Presently, my only recourse is to restart my client to deal the issue. I will keep an eye on responses from experts and look forward to potential solutions.
<img width="1192" alt="StacklessClosedChannelException20240613151230" src="https://github.com/redisson/redisson/assets/85333853/91e2064f-e0c0-47ab-a18a-b492c83bb36b">

**Comment by sunwuxiang** [comment]
> Can you try attached version?
> 
> [redisson-3.31.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/15529923/redisson-3.31.1-SNAPSHOT.jar.zip)

这个包没有出现问题，都能自动恢复，这个包可以

**Comment by sunwuxiang** [comment]
@mrniko 有没有针对3.16.4的fix部分，不想升级到最新版本，因为我们最新版本少了很多方法，升级很多代码要修改

**Comment by mrniko** [comment]
> 这个包没有出现问题，都能自动恢复，这个包可以

Thanks for testing. Fixed.

**Comment by mrniko** [comment]
> @mrniko 有没有针对3.16.4的fix部分，不想升级到最新版本，因为我们最新版本少了很多方法，升级很多代码要修改

Unfortunately, I can't help here. Please use consider using the latest version.

**Comment by mrniko** [comment]
@Zelda33 

Can you try 3.32.0 version?

**Comment by youngledo** [comment]
我佩服你，用只言片语的中文让他反复回答！

最后你是怎么修复的？使用了最新的版本？
