### ISSUE TITLE
Slow locks, subscriptionConnectionPoolSize, and nettyThreads

### ISSUE THREAD

**Issue by SHxKM** [redisson/redisson#5554]
We are experiencing quite a slow response time from our Redisson setup with Elasticache, sometimes locks  (`lock()`) wait for acquisition for 100ms+, and we also see times like 1.5-2 seconds. The average even if in the same AZ is 20-40ms which seems a bit high.  Nothing in the AWS metrics indicates a bottleneck. 

The process that is locked is actually checking if the item is in the cache or not, so should be super quick.

using the following settings:

```java
Config config = new Config();
JsonJacksonCodec codec = new JsonJacksonCodec(objectMapper);
config.setCodec(codec);
config.useReplicatedServers()
                .setPassword(someConfig.getPassword())
                .setTimeout(someConfig.getTimeout())
                .addNodeAddress(nodeAddressArray); // 2 nodes, 1 main, 1 secondary, quite beefy

config.setNettyThreads(128);
```

I'm investigating whether raising the following (all or some) may help:

- `masterConnectionPoolSize` (at default: 64)
- `slaveConnectionPoolSize` (at default: 64)
- threads (at default: 16)
- And especially: `subscriptionConnectionPoolSize` (at default: 50)

I came across[ this answer](https://stackoverflow.com/questions/69946925/is-the-number-of-connections-used-by-redisson-sum-of-subscriptionconnectionpools) on SO which states:

> Redis nodes amount * (subscriptionConnectionPoolSize + connectionPoolSize)

In my case I guess the answer is:

```
(masterConnectionPoolSize * M masters) + (slaveConnectionPoolSize * N secondaries) + (subscriptionConnectionPoolSize * N secondaries)
```

Is that correct? If so, I was wondering which ones I may want to raise, and how do they all tie back to `nettyThreads`? should `nettyThreads` be > than the sum of connections? is it an upper bound? What about `threads`?

Appreciate any advice.

Redisson version: `redisson:3.23.4`

**Comment by mrniko** [comment]
> sometimes locks (lock()) wait for acquisition for 100ms+, and we also see times like 1.5-2 seconds. 

That depends on contention level.

**Comment by SHxKM** [comment]
@mrniko Thanks, yes I've read the documentation. What would you recommend to raise in this situation?
I don't think we're experiencing lock contention, I think it's more a general load of many (different) locks being acquired/released.

**Comment by mrniko** [comment]
> locks (lock()) wait for acquisition for 100ms+

Do you use async lock?
