### ISSUE TITLE
Creating health check/indicator

### ISSUE THREAD

**Issue by andreas-ajaib** [redisson/redisson#5555]
I have been using RedissonClient/ReactiveRedissonClient on my Spring Boot apps. Now I want to create health check/indicator by just sending `PING` command. I don't see any method to do that. Is that possible to send some custom Redis command using RedissonClient?

**Comment by mrniko** [comment]
Here is how you can do it.

```java
        RedisSingle nodes = redisson.getRedisNodes(RedisNodes.SINGLE);
        RedisMaster node = nodes.getInstance();

        node.ping();
        // or
        nodes.pingAll();
```
