### ISSUE TITLE
redissonClient getPriorityBlockingQueue poll

### ISSUE THREAD

**Issue by 397688551** [redisson/redisson#5558]
hi, When I use redissonClient getPriorityBlockingQueue , there is a problem, this is the source code:
redissonClient.getPriorityBlockingQueue("xxxxxx").poll();
When poll was called, it blocked，
![image](https://github.com/redisson/redisson/assets/37072662/dd5bfa75-432b-44d3-b74f-bd51c830dca0)
This thread 2 is WAITING, threads 1 and 3 are normal, Unless restarted。
This thread 2 remains in the WAITINGstate until it is restarted，
redisson 3.11.5 redis 2.1.9

**Comment by mrniko** [comment]
Unable to reproduce with the latest version.
