### ISSUE TITLE
Bug: when `Bucket#set(V, Duration)` is used inside a transaction, `PSETEX` is called before `MULTI`

### ISSUE THREAD

**Issue by SHxKM** [redisson/redisson#5561]
Using `redisson-3.25.2`.

```
transaction = redisson.createTransaction(TransactionOptions.defaults());
transaction.getBucket(key).put(value, ttl);
transaction.getSet(setKey).add(otherStringValue);
transaction.commit()
```

In my redis-cli `monitor` logs, I can see that `PSETEX` for the bucket `value` is ran before `MULTI`. Is that by design? If so, what do I gain from the transaction?

Also, there is no `WATCH` command being issues (which is good in my case), but given the above surprise, I want to ask if that's by design as well.

**Comment by mrniko** [comment]
there is no need for `multi` `watch` since transactions are executed atomically.

**Comment by SHxKM** [comment]
@mrniko so why does Redisson issue a MULTI command at all then? If buck set happens before the MULTI call, why make the SADD inside the MULTI? It doesn’t make sense

**Comment by mrniko** [comment]
Sorry, only `multi` command is used for atomicity. I corrected my answer.

**Comment by SHxKM** [comment]
> Sorry, only `multi` command is used for atomicity. I corrected my answer.

It’s OK thank you. It’s still weird for me that PSETEX happens before the MULTI when it’s clearly part of the Redisson transaction. I’m less concerned a bout atomicity and more about saving the network round trip (I’m aware of pipelines and scripting)

**Comment by mrniko** [comment]
I have checked it with the code below.

```java
        RTransaction transaction = redisson.createTransaction(TransactionOptions.defaults().timeout(3, TimeUnit.SECONDS));
        RBucket<String> bucket = transaction.getBucket("test");
        bucket.set("234", 10, TimeUnit.SECONDS);
        transaction.commit();
```

Redis command

```
$5
MULTI
*4
$6
PSETEX
$4
test
$5
10000
$4
23�
*11
$4
EVAL
$471
local val = redis.call('get', KEYS[3]); if val ~= false then return tonumber(val);end; if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); redis.call('set', KEYS[3], 0, 'px', ARGV[5]); return 0; else redis.call('del', KEYS[1]); redis.call(ARGV[4], KEYS[2], ARGV[1]); redis.call('set', KEYS[3], 1, 'px', ARGV[5]); return 1; end; 
$1
3
$21
test:transaction_lock
$46
redisson_lock__channel:{test:transaction_lock}
$78
redisson_unlock_latch:{test:transaction_lock}:acc0aa51061a1b27b4bd9eed9f9da226
$1
0
$5
30000
$71
7edb284c-41a1-4332-a94c-2adb990b5a89:1:073491d878dc8b4542acdad7d6128c8a
$7
PUBLISH
$5
13500
*1
$4
EXEC
```

**Comment by SHxKM** [comment]
Hmm that doesn’t match my test results. Will run it again and post my results (any idea how to filter the many ping lines?)

**Comment by SHxKM** [comment]
@mrniko Below are screenshots of the order of things when I execute the code I post in my original post (I'm using JacksonCodec and `defaults()` by the way, the calls are consecutive with no code that could delay exeuction):

1:
![redisson-transaction-1](https://github.com/redisson/redisson/assets/6573474/6b9ba7f4-85a7-4cd5-add5-f673d62d481a)



2:
![redisson-transaction-2](https://github.com/redisson/redisson/assets/6573474/72d06bbc-3e54-4b8a-9feb-d9a227eddfe0)

**Comment by mrniko** [comment]
this psetax is related to transaction lock. Which is acquired independently.

**Comment by SHxKM** [comment]
@mrniko thats incorrect. It is 100% the value for the bucket I just blurred it because there is some sensitive data. I can share the screenshot again less blurred.

**Comment by SHxKM** [comment]
@mrniko Is this enough to reopen the issue? As you can see, same timestamp as screenshot 1 above. You can see the value is a long JSON string, it's not a lock or something.

![reddison-1-3](https://github.com/redisson/redisson/assets/6573474/b6e112a1-d4da-4108-8d04-4f59f31a0257)

I've also checked everything between `MULTI` and `EXEC`, there is no `PSETEX` there, or any other command that sets the value of the key we see.

**Comment by SHxKM** [comment]
@mrniko Since you aren't convinced, I dug a bit more, and found the likely cause.

```
 RTransaction transaction = redisson.createTransaction(TransactionOptions.defaults().timeout(3, TimeUnit.SECONDS));
        RBucket<String> bucket = transaction.getBucket("test");
        bucket.set("234", 10, TimeUnit.SECONDS);
        transaction.commit();
```

This does not indeed work, even with a set interaction before the `commit()` call. But I think the issue is with method `set(T, Duration)`. What happens if you use the non-deprecated method of `bucket#set`, example:

```
Duration ttl = Duration.ofSeconds(43200);
transaction = redisson.createTransaction(TransactionOptions.defaults());
transaction.getBucket(key).put(value, ttl);
transaction.getSet(setKey).add(otherStringValue);
transaction.commit();
```

So either the issue with `bucket#set(T, Duration)`, or the issue with the duration itself (being too long? I don't know).

@mrniko can you please recheck?

**Comment by SHxKM** [comment]
@mrniko any plan to look into this?

**Comment by SHxKM** [comment]
Hi @mrniko, I’m still able to reproduce this. Should we just use the deprecated method for now?

**Comment by SHxKM** [comment]
Is it possible to change the label on this to `bug` so it's better tracked?

**Comment by mrniko** [comment]
merged
