### ISSUE TITLE
If there is already a key with value of type String, using the Redisson try lock method will result in an exception

### ISSUE THREAD

**Issue by lionel-xiu** [redisson/redisson#5565]
Redisson version:3.18.0
![image](https://github.com/redisson/redisson/assets/43173442/33561635-61d0-455c-adc2-695c26a1f7e9)
Before using the hexists command,should first verify the type, otherwise an exception will be prompted

**Comment by mrniko** [comment]
Two different type of objects can't share the same name.

**Comment by lionel-xiu** [comment]
If I had previously implemented the lock function using Jedis myself, this issue would occur during the process of switching to Redisson later on
