### ISSUE TITLE
Why the org.redisson.spring.data.connection.RedissonConnection method RedisSetCommands setCommands() return null?

### ISSUE THREAD

**Issue by DarkDance** [redisson/redisson#5566]
I'm not sure it's a bug, but other method all return "this", so why only this method return null? from version 3.23.2 ~3.25.2
<groupId>org.redisson</groupId>
<artifactId>redisson-spring-boot-starter</artifactId>
<version>${redisson.version}</version>

**Comment by mrniko** [comment]
Fixed. Thanks for report
