### ISSUE TITLE
redis cluster扩容后之前存储的数据部分取值为null

### ISSUE THREAD

**Issue by BQDMDMN** [redisson/redisson#5569]
redis cluster扩容之前是3主3从，存储很多数据，扩容到4主4从发现部分数据取值为null
个人理解为节点发生变化后，槽点也发生了变化，之前存储数据的部分槽点移动到了新的节点上，springboot本地缓存没有实现动态拓扑刷新，但是日志中可以看到集群节点增加了，槽点也发生了移动等日志，可是就是部分数据取值为null，并且更奇怪的是重新对所有的key存储数据，部分取值仍然为null
rediession版本：3.20.1
redis版本：7.2.4
springboot版本2.3.3.release

**Comment by BQDMDMN** [comment]
原始集群为6381,6382,6383,6384,6385,6386，扩容的节点为：6387,6388
扩容后循环取值结果：
test959
test960
test961
null
test963
test964
test965
null
test967
test968
test969
test970
null
test972
test973
test974
null
test976
test977
test978
null
null
test981
test982
test983
null
test985
test986
test987
null
test989
test990
test991
test992
null
test994
test995
test996
null
test998
test999
test1000
并且重启也解决不了取值为null的问题。
但是直接连接redis服务端采用命令的方式在扩容的节点上查这些为null的key是有值的：
127.0.0.1:6387> get testv1-997
"test997"
127.0.0.1:6387> get testv1-993
"test993"

**Comment by BQDMDMN** [comment]
private StringRedisTemplate redisTemplate;
set值redisTemplate.opsForValue().set(key, value);
取值redisTemplate.opsForValue().get(key);

**Comment by mrniko** [comment]
it might be cause by ongoing replication process.

**Comment by BQDMDMN** [comment]
扩容完，过了十几小时都一直是这个情况，进去取值部分依然为null

**Comment by JUNFN70783660042** [comment]
你这个怀疑是刷新拓扑配置的问题，可以检查一下你客户端刷新拓扑相关的配置
