### ISSUE TITLE
Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null

### ISSUE THREAD

**Issue by miteshjain24** [redisson/redisson#5574]
Hi, 
I am using redisson 2.15.2 and intermittently getting below error-

Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=24, freeConnectionsCounter=value:64:queue:0, freezed=false, freezeReason=null, client=[addr=redis://10.226.121.54:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1660219782 [redisClient=[addr=redis://10.226.121.215:6379], channel=[id: 0x7e3dffbd, L:/10.221.181.46:46922 - R:10.126.120.215/10.126.120.215:6379]], current command in queue: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@571d4d36(failure: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), command params: [], Redis client: [addr=redis://10.226.120.215:6379])], command=(PING), params=[], codec=org.redisson.client.codec.StringCodec], command: (HGET), command params: [some_key, PooledUnsafeDirectByteBuf(ridx: 0, widx: 11, cap: 256)] after 3 retry attempts

**Expected behavior**
It should not give such error

**Actual behavior**
Giving above mentioned error

**Steps to reproduce or test case**
Its intermittent issue, occuring  some time

**Redis version**
redis_version:6.2.6

**Redisson version**
Redisson 2.15.2

**Redisson configuration**
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "My remote cluster redis"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
threads: 16
nettyThreads: 32
#codec: !<org.redisson.codec.Kryo5Codec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Caused by PING command timeout. Try to upgrade to the latest Redisson version.
