### ISSUE TITLE
Task not firing on the next executor if app was killed

### ISSUE THREAD

**Issue by Deliel** [redisson/redisson#5577]
I think I have similar problem like this:
https://github.com/redisson/redisson/issues/2308

**Expected behavior**
I have 2 app instances with distributed executor services.
I expect, that if one instance will be killed another instance will start executing the task after specified time (taskRetryInterval property). 
So it works sometimes. Sometimes it's not.

**Actual behavior**
If task had been submitted on executor and app instance was killed it doesn't works. 
But after restarting the instance the feature starts working correctly. If the instance with submitted task was killed another one starts executing it.

Also sometimes I'm getting duplication of tasks. But this happens very rarely, I can't reproduce it.

**Steps to reproduce or test case**
1. Start first app instance
2. Start second app instance
3. Submit task
4. Stop app instance which executing the task
5. Awaiting that second app instance will start executing the task. But nothing happens
6. Start killed app instance
7. Random instance starts executing the task. After that case not reproducing and it's working correctly. But only for this task

Redisson 
3.26.0

KeyDB  
6.3.3
```java
    // Spring config
    @Bean(destroyMethod = "")
    public RScheduledExecutorService executorService(RedissonClient redissonClient) {
        ExecutorOptions executorOptions = ExecutorOptions.name("test-1")
                .taskRetryInterval(Duration.ofSeconds(10));

        RScheduledExecutorService executorService = redissonClient.getExecutorService(executorOptions);

        WorkerOptions workerOptions = WorkerOptions.defaults();
        workerOptions.executorService(Executors.newFixedThreadPool(3));
        workerOptions.workers(3);
        workerOptions.taskTimeout(0, TimeUnit.SECONDS);

        executorService.registerWorkers(workerOptions);

        return executorService;
    }

    // Task execution
    public void run() {
        executorService.submitAsync(new Task(UUID.randomUUID()));
    }

    // Task
    @Data
    @AllArgsConstructor
    public class Task implements Callable<Long>, Serializable {

        private UUID uuid;

        @Override
        public Long call() {
            System.out.println("started");
            System.out.println(uuid);
            try {
                TimeUnit.HOURS.sleep(2);
            } catch (Exception e) {
                e.printStackTrace();
            }

            System.out.println("finished");

            return 1L;
        }
    }
```

**Comment by Deliel** [comment]
Manual message in executor's scheduler channel starts task executing on another instance if first one was down.
E.g.
```java
redissonClient.getTopic("{test-1:org.redisson.executor.RemoteExecutorService}:scheduler-channel", new LongCodec())
        .publish(System.currentTimeMillis());
```

**Comment by mrniko** [comment]
Merged
