### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection!

### ISSUE THREAD

**Issue by RafiyaB** [redisson/redisson#5578]
Hi All,

Please let me know who can help me on this.

I have EKS cluster
Redis master -1 pod
Redis Replica -1 pod
application pods are 2
Postgress db is also there

I will be keep on getting below error in redis replica pods and master is unable to connect to redis. Application gets failing and we have netflix conductor whose workflows keeps on failing and struck. Please let me know the fix.
Error:

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection!

**Comment by mrniko** [comment]
You need to check the network and Redis configuration.
