### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection!

### ISSUE THREAD

**Issue by sunwuxiang** [redisson/redisson#5581]
org.redisson.client.WriteRedisConnectionException: Unable to write command into connection!
连接恢复后，连接无法自动恢复，需要重启服务

<img width="587" alt="微信图片_20240122184300" src="https://github.com/redisson/redisson/assets/30144714/a7361f0f-0337-4dd5-91d4-796552386778">

我发现redisclient的close为true的连接还在连接池被拿出来使用并放回去，但是当这个连接的channel因为网络抖动close的时候，这个连接无法恢复，因为在ConnectionWatchdog的tryReconnect中判断当redisclient的close为true，跳出重连，但是这个连接还在连接池被使用

<img width="506" alt="微信图片_20240122184613" src="https://github.com/redisson/redisson/assets/30144714/751d843a-adae-49db-a6cd-0b33364f8f2b">

是否可以在放回连接的时候判断当redisclient的close为true的时候，不放回连接，并且关闭连接，代码如：
<img width="449" alt="微信图片_20240122184835" src="https://github.com/redisson/redisson/assets/30144714/f6bce326-0dd7-4b8a-903f-319d3e130633">

我发现在这个连接在最开始被创建的时候redisclient的close就是true，应该在启动的时候就有bug，但是我没找到

**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
version：3.16.4

**Redisson configuration**

**Comment by mrniko** [comment]
Sorry, which code changes do you suggest?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5553
