### ISSUE TITLE
redisson connect to the fail slave node in redis cluster

### ISSUE THREAD

**Issue by ZengyiZhao** [redisson/redisson#5582]
I have a redis cluster, with 3 masters and 3 slaves. And there is another slave that I have already stopped for a long time.
The redis cluster nodes show as below with a fail slave node, and the cluster slots didn't contains this fail slave.

![image](https://github.com/redisson/redisson/assets/95901773/049734ee-f524-435c-b462-08bc2536340a)

When I use the version 3.3, there is no exception. But when I upgrade to 3.25,  there are many exceptions of connecting to the fail slave.

If there is any config param or something that I missed.

Thank you very much.

**Comment by mrniko** [comment]
Please set `trace` logging level for `org.redisson` package and share the logs since application start moment till the exception appearance.
