### ISSUE TITLE
RSearchReactive#dropIndex AssertionError (expected: onComplete(); actual: onNext(OK))

### ISSUE THREAD

**Issue by vavisha** [redisson/redisson#5591]
**Expected behavior**
Test passed
**Actual behavior**
09:25:55.917 [Test worker] DEBUG org.redisson.command.RedisExecutor -- acquired connection for command (FT.DROPINDEX) and params [test-index] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node 127.0.0.1/127.0.0.1:6379... RedisConnection@910063148 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xc0477c6c, L:/127.0.0.1:53475 - R:127.0.0.1/127.0.0.1:6379], currentCommand=null, usage=1]
09:25:55.924 [redisson-netty-1-2] DEBUG org.redisson.command.RedisExecutor -- connection released for command (FT.DROPINDEX) and params [test-index] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@910063148 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0xc0477c6c, L:/127.0.0.1:53475 - R:127.0.0.1/127.0.0.1:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@36dcbfdc[Completed normally], command=(FT.DROPINDEX), params=[test-index], codec=org.redisson.client.codec.StringCodec], usage=0]

expectation "expectComplete" failed (expected: onComplete(); actual: onNext(OK))
java.lang.AssertionError: expectation "expectComplete" failed (expected: onComplete(); actual: onNext(OK))
	at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
	at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
	at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
	at reactor.test.MessageFormatter.failOptional(MessageFormatter.java:88)

**Steps to reproduce or test case**
```
import org.junit.jupiter.api.Test;
import org.redisson.Redisson;
import org.redisson.api.search.index.FieldIndex;
import org.redisson.api.search.index.IndexOptions;
import org.redisson.api.search.index.IndexType;
import org.redisson.client.codec.StringCodec;
import org.redisson.config.Config;
import reactor.test.StepVerifier;

import java.util.Arrays;

public class DropIndexTest {

    @Test
    public void should_drop_index() {
        final var config = new Config();
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6379");
        final var redissonReactiveClient = Redisson.create(config).reactive();
        final var search = redissonReactiveClient.getSearch(StringCodec.INSTANCE);

        search.createIndex(
                        "test-index",
                        IndexOptions.defaults().on(IndexType.JSON).prefix(Arrays.asList("test-key")),
                        FieldIndex.text("$..key").as("key")
                )
                .as(StepVerifier::create)
                .verifyComplete();

        search.dropIndex("test-index")
                .as(StepVerifier::create)
                .verifyComplete();
    }
}
```
**Redis version**
7.2.0 (redis/redis-stack:7.2.0-v7)
**Redisson version**
3.26.0
**Redisson configuration**
final var config = new Config();
config.useSingleServer().setAddress("redis://127.0.0.1:6379");

**Comment by mrniko** [comment]
Fixed. Thanks for report
