### ISSUE TITLE
RLocalCachedMap ttl and eviction 

### ISSUE THREAD

**Issue by cgpoh** [redisson/redisson#5606]
I use RLocalCachedMap in my spring boot application to boost the performance. One thing I observed when I’m writing my unit test is in order to make ttl or max idle time working, I need to set a value (> 0) to the cache size. The ttl or max idle time settings will only kick in when the cache is full and a new entry is added. Is this the intended behavior?

Setting the cache size to 0 doesn’t seem to activate the ttl and max idle time behavior. The RLocalCachedMap.cachemap.size will keep increasing.

**Comment by mrniko** [comment]
> Is this the intended behavior?

Yes.

You can use CAFFEINE implementation instead.

```java
LocalCachedMapOptions opts = LocalCachedMapOptions.name("test").cacheProvider(CacheProvider.CAFFEINE);
```
