### ISSUE TITLE
The start-up project appears

### ISSUE THREAD

**Issue by huanmin123** [redisson/redisson#5609]
【20ad97776fec4bb48323bb6bf2649ebe】 2340 - 2024-02-06 00:19:23.714 - [main] INFO  [org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.prepareWebApplicationContext - 285]  - Root WebApplicationContext: initialization completed in 980 ms
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.3.1 
【f27d8f7560f849088fc42fdb7d88d7de】 3209 - 2024-02-06 00:19:24.583 - [main] WARN  [org.springframework.security.access.intercept.AbstractSecurityInterceptor.afterPropertiesSet - 159]  - Could not validate configuration attributes as the SecurityMetadataSource did not return any attributes from getAllConfigAttributes()
【558266dd4e7b4526ac8885aac8136334】 3227 - 2024-02-06 00:19:24.601 - [Finalizer] WARN  [io.lettuce.core.resource.DefaultClientResources.finalize - 603]  - io.lettuce.core.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit) 
【da9896a329014ca39866fbedce5d5b3a】 3692 - 2024-02-06 00:19:25.066 - [main] INFO  [org.redisson.Version.logVersion - 41]  - Redisson 3.24.2
【3b0149db84f74d939487920406e1a173】 4184 - 2024-02-06 00:19:25.558 - [main] ERROR [io.netty.util.ResourceLeakDetector.reportTracedLeak - 320]  - LEAK: HashedWheelTimer.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:275)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:218)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:197)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:179)
	io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:163)
	io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:183)
	io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:562)
	io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:247)
	io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:105)
	io.lettuce.core.RedisClient.<init>(RedisClient.java:90)
	io.lettuce.core.RedisClient.create(RedisClient.java:127)
	org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.lambda$createClient$7(LettuceConnectionFactory.java:1084)
	java.util.Optional.orElseGet(Optional.java:267)
	org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.createClient(LettuceConnectionFactory.java:1084)
	org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.afterPropertiesSet(LettuceConnectionFactory.java:283)
	com.gitee.huanminabc.utils_tools.redis.redisTemplate.config.RedisTemplateConfig.createLettuceConnectionFactory(RedisTemplateConfig.java:159)
	com.gitee.huanminabc.utils_tools.redis.redisTemplate.config.RedisTemplateConfig$$EnhancerBySpringCGLIB$$7fbf33bf.CGLIB$createLettuceConnectionFactory$4(<generated>)
	com.gitee.huanminabc.utils_tools.redis.redisTemplate.config.RedisTemplateConfig$$EnhancerBySpringCGLIB$$7fbf33bf$$FastClassBySpringCGLIB$$c8b6995d.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	com.gitee.huanminabc.utils_tools.redis.redisTemplate.config.RedisTemplateConfig$$EnhancerBySpringCGLIB$$7fbf33bf.createLettuceConnectionFactory(<generated>)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:212)
	org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:361)
	org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:334)
	com.gitee.huanminabc.utils_tools.redis.redisTemplate.config.RedisTemplateConfig$$EnhancerBySpringCGLIB$$7fbf33bf.createLettuceConnectionFactory(<generated>)
	com.gitee.huanminabc.utils_tools.redis.redisTemplate.config.RedisTemplateConfig.afterPropertiesSet(RedisTemplateConfig.java:169)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:408)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
	org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getObject(DefaultListableBeanFactory.java:1906)
	org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration.setRedisConnectionFactory(RedisHttpSessionConfiguration.java:209)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:755)
	org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:408)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:538)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:211)
	org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:202)
	org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:96)
	org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:85)
	org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:255)
	org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:229)
	org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53)
	org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128)
	org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
	org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
	org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:437)
	org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191)
	org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178)
	org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	com.gitee.huanminabc.utils_server.WebApplication.main(WebApplication.java:30)

**Comment by huanmin123** [comment]
How to solve it? This is a memory leak

**Comment by mrniko** [comment]
It's caused by the class from `io.lettuce.core.resource` package.
