### ISSUE TITLE
When using locks, reddison may call too many info command internally, resulting in poor performance of redis

### ISSUE THREAD

**Issue by org-kepe** [redisson/redisson#5614]
such as 
![image](https://github.com/redisson/redisson/assets/95668826/b3bfb850-4511-4c0b-91e7-6280e15ac277)

**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version**
4.0
**Redisson version**
3.26.0
**Redisson configuration**

**Comment by mrniko** [comment]
Info command is used to get actual amount of slaves. Let me know if you can suggest a better solution

**Comment by org-kepe** [comment]
1. The number of slaves can be obtained and cached through timing and other methods

2. If config.setCheckLockSynchedSlaves(false) is set, there is no need to obtain the number of slave nodes

3.Even if config.setCheckLockSynchedSlaves(true) is set and the number of slave nodes must be obtained in real time, configuration should be provided to retrieve from the cache, as the number of slave nodes generally does not change

4. Based on the current performance statistics of using distributed locks in production, the time consumption of using INFO REPLICATION is 120 times that of the SET command and 5 times that of the EVAL command, which is currently the culprit causing the performance degradation of Redis

**Comment by mrniko** [comment]
Done. Thanks for the suggested improvement.
