### ISSUE TITLE
Repeated new connections with Elasticache Serverless - 3.26.1-SNAPSHOT

### ISSUE THREAD

**Issue by nkasridhar** [redisson/redisson#5621]
Team.. We are in the process of migrating from hosted Redis to Serverless Elasticache. We are waiting for the release of 3.26.1 version as this has the fix for the issue #5589 . While waiting we built the latest 3.26.1-SNAPSHOT version and tried to test pointing to serverlesss elasticache, we still see Redisson making repeated connections, please find attached sample logs.

Can you please confirm if issue #5589 has been fixed in the latest 3.26.1-SNAPSHOT version or if the above noted issue is a different issue?

**Comment by nkasridhar** [comment]
[Repeated_Connections.txt](https://github.com/redisson/redisson/files/14217026/Repeated_Connections.txt)

Attached logs

**Comment by mrniko** [comment]
I need Redisson config and logs with `debug` logging level for `org.redisson` package since the application start moment till the first issue appearance.

**Comment by nkasridhar** [comment]
Below is the config used for testing

  redisConfig.useSingleServer()
                .setDatabase(0)
                .setAddress(elastiCacheUrl)
                .setTimeout(10000)
                .setConnectionPoolSize(200)
                .setIdleConnectionTimeout(5000)
                .setConnectTimeout(10000)
                .setConnectionMinimumIdleSize(30);

Attached here with the debug logs

[Debug_logs.txt](https://github.com/redisson/redisson/files/14223316/Debug_logs.txt)

**Comment by mrniko** [comment]
What is the Redis setup configuration? Is it just a single master node or multiple master nodes?

**Comment by mrniko** [comment]
Also please execute the code below for this host and share output.

```java
        String hostname = ...
        
        NioEventLoopGroup ee = new NioEventLoopGroup();
        SequentialDnsAddressResolverFactory f = new SequentialDnsAddressResolverFactory();
        AddressResolverGroup<InetSocketAddress> g = f.create(NioDatagramChannel.class, NioSocketChannel.class, DnsServerAddressStreamProviders.platformDefault());
        AddressResolver<InetSocketAddress> r = g.getResolver(ee.next());
        AddressResolver<InetSocketAddress> r2 = DefaultAddressResolverGroup.INSTANCE.getResolver(ee.next());
        List<InetSocketAddress> ips = r.resolveAll(InetSocketAddress.createUnresolved(hostname, 6379)).get();
        System.out.println(hostname + " SequentialDnsAddressResolverFactory ips " + ips);
        List<InetSocketAddress> ips2 = r2.resolveAll(InetSocketAddress.createUnresolved(hostname, 6379)).get();
        System.out.println(hostname + " DefaultAddressResolverGroup ips " + ips2);
        ee.shutdownGracefully();
```

**Comment by nkasridhar** [comment]
> Also please execute the code below for this host and share output.
> 
> ```java
>         String hostname = ...
>         
>         NioEventLoopGroup ee = new NioEventLoopGroup();
>         SequentialDnsAddressResolverFactory f = new SequentialDnsAddressResolverFactory();
>         AddressResolverGroup<InetSocketAddress> g = f.create(NioDatagramChannel.class, NioSocketChannel.class, DnsServerAddressStreamProviders.platformDefault());
>         AddressResolver<InetSocketAddress> r = g.getResolver(ee.next());
>         AddressResolver<InetSocketAddress> r2 = DefaultAddressResolverGroup.INSTANCE.getResolver(ee.next());
>         List<InetSocketAddress> ips = r.resolveAll(InetSocketAddress.createUnresolved(hostname, 6379)).get();
>         System.out.println(hostname + " SequentialDnsAddressResolverFactory ips " + ips);
>         List<InetSocketAddress> ips2 = r2.resolveAll(InetSocketAddress.createUnresolved(hostname, 6379)).get();
>         System.out.println(hostname + " DefaultAddressResolverGroup ips " + ips2);
>         ee.shutdownGracefully();
> ```

Below is the output

hostname SequentialDnsAddressResolverFactory ips [hostname/IP1:6379, hostname/IP2:6379, hostname/IP3:6379, hostname/IP4:6379, hostname/IP5:6379, hostname/IP6:6379]
hostname DefaultAddressResolverGroup ips [hostname/IP4:6379, hostname/IP5:6379, hostname/IP1:6379, hostname/IP3:6379, hostname/IP6:6379, hostname/IP2:6379]

**Comment by mrniko** [comment]
What is the Redis setup configuration? Is it just a single master node or multiple master nodes?

**Comment by cmrichardson1** [comment]
> What is the Redis setup configuration? Is it just a single master node or multiple master nodes?

We are using AWS Elasticache serverless, so the Redis configuration setup is only a single endpoint and port provided by AWS. To our understanding, the node clustering and data replication is handled behind-the-scenes by AWS.

Does this answer your question?

**Comment by mrniko** [comment]
Try master branch. By the way, with [proxy mode](https://github.com/redisson/redisson/wiki/2.-Configuration/#29-proxy-mode) you can use all IP addresses.

**Comment by nkasridhar** [comment]
> Try master branch. By the way, with [proxy mode](https://github.com/redisson/redisson/wiki/2.-Configuration/#29-proxy-mode) you can use all IP addresses.

Tested with the master branch and the issue now seems to be resolved. May i know when the new version of the build will be released ?

**Comment by mrniko** [comment]
During this month.

**Comment by modigopal** [comment]
@nkasridhar  @mrniko  Can you guys please tell the exact version in which this issue got fixed.  I have tried with 3.32.0 version. But still see the same issue

**Comment by mrniko** [comment]
@modigopal 

Can you share Redisson config and logs with debug logging level for org.redisson package since the application start moment till the first issue appearance?
