### ISSUE TITLE
Multiple locking of RLock reset remainTimeToLive to config default

### ISSUE THREAD

**Issue by victornoel** [redisson/redisson#5623]
**Actual behavior**

My use case is the following:
```java
RedissonClient redisson = Redisson.create(config);
RLock lock = redisson.getLock("test-lock:1");
lock.lock(10, TimeUnit.SECONDS);
lock.lock(10, TimeUnit.SECONDS);
lock.unlock();
System.out.println(lock.remainTimeToLive()); // prints something close to the config default of 30 000
```

**Expected behavior**

I am not exactly sure but the behaviour changed between 3.19.1 and 3.19.2 most certainly because of https://github.com/redisson/redisson/issues/4818

I would expect that remainTimeToLive is closer to 10 seconds.

**Redis version**

Version 7

**Redisson version**

3.19.2 to 3.26.0

**Comment by victornoel** [comment]
A variation on the example given above is:
```java
RedissonClient redisson = Redisson.create(config);
RLock lock = redisson.getLock("test-lock:1");
lock.lock(10, TimeUnit.SECONDS);
Thread.sleep(5000);
lock.lock(10, TimeUnit.SECONDS);
lock.unlock();
System.out.println(lock.remainTimeToLive());
```

Should the remainTimeToLive be 10 seconds or 5 seconds?

**Comment by victornoel** [comment]
Hi @mrniko, do you know if there is some plan to fix this in a next patch version? Or is there something I can do to help?

**Comment by mrniko** [comment]
> A variation on the example given above is:
> 
> ```java
> RedissonClient redisson = Redisson.create(config);
> RLock lock = redisson.getLock("test-lock:1");
> lock.lock(10, TimeUnit.SECONDS);
> Thread.sleep(5000);
> lock.lock(10, TimeUnit.SECONDS);
> lock.unlock();
> System.out.println(lock.remainTimeToLive());
> ```
> 
> Should the remainTimeToLive be 10 seconds or 5 seconds?
> 
> Another one:
> 
> ```java
> RedissonClient redisson = Redisson.create(config);
> RLock lock = redisson.getLock("test-lock:1");
> lock.lock(10, TimeUnit.SECONDS);
> lock.lock(5, TimeUnit.SECONDS);
> lock.unlock();
> System.out.println(lock.remainTimeToLive());
> ```
> 
> Should the remainTimeToLive be 10 seconds or 5 seconds?

first example is about 10 seconds. Second example is about 5 seconds. I have checked your examples. Results are correct.

**Comment by victornoel** [comment]
> I have checked your examples. Results are correct.

Ok, so you didn't reproduce the problem I was experiencing where lock, lock, unlock would result with a time to live to be the default 30seconds instead?

I will check again with latest version and close this if it's all good. Thank you for looking into it.

**Comment by victornoel** [comment]
So, yes, indeed, it works as expected, so I'm not sure what happens in my particular environment (because I have built abstractions on top of Redisson and I had tests that are now failing with 3.19.2+).

I will close this ticket then and reopen one if needed. Sorry again for the noise :)

**Comment by victornoel** [comment]
Well, that was fast, actually the bug is really there, the repro is the same as in the description but with a twist:
```java
RedissonClient redisson = Redisson.create(config);
RLock lock = redisson.getLock("test-lock:1");
lock.lock(10, TimeUnit.SECONDS);
lock.lock(10, TimeUnit.SECONDS);
lock.lock(10, TimeUnit.SECONDS);
lock.unlock();
lock.unlock();
System.out.println(lock.remainTimeToLive()); // prints something close to the config default of 30 000
```

**Comment by mrniko** [comment]
Fixed. Thanks for report
