### ISSUE TITLE
JsonCodecWrapper defeats CODECS LRUCacheMap cache

### ISSUE THREAD

**Issue by adrian-skybaker** [redisson/redisson#5625]
When using a high number (eg hundreds of thousands/millions) of RedissonJsonBucket instances, I found that the use of the JsonCodecWrapper generates an enormous number of values being entered into org.redisson.command.RedisExecutor#CODECS .

This is because a copy of the codec is created for every bucket, which then appears to the executor as a new codec for every single bucket.

I'm unclear on what the wrapper is achieving, especially the org.redisson.codec.JsonCodecWrapper#JsonCodecWrapper(org.redisson.codec.JsonCodec<?>) variant that simply presents the underlying codec unchanged, but perhaps it could implement hashCode/equals.

**Comment by mrniko** [comment]
Is contextClassLoader is different per call? You can simply set `useThreadClassLoader = false`.

**Comment by adrian-skybaker** [comment]
No it's not - I'll use that to workaround the issue, however I believe the issue still remains if left at the default `true` configuration.

**Comment by mrniko** [comment]
Fixed. Thanks for report.
