### ISSUE TITLE
Frequently cluster state updates in AWS Serverless

### ISSUE THREAD

**Issue by timigv** [redisson/redisson#5627]
Hi. I use the 3.24.3 version lib with Amazon serverless Elasticache. I see constant cluster updates and connections initializing. This happens dozens of times per minute. The logs:
`o.r.cluster.ClusterConnectionManager - cluster nodes state got from ***`
`o.r.cluster.ClusterConnectionManager - ***:6379 master and related slaves: [addr=***:6380] removed`
`o.r.cluster.ClusterConnectionManager - master: ***:6379 added for slot ranges: [[0-16383]]`
`o.r.cluster.ClusterConnectionManager - slaves: ***: 6380 added for slot ranges: [[0-16383]]`
`o.r.c.pool.MasterConnectionPool - 24 connections initialized for ***`
My config is
```
Config config = new Config();
config.setCodec(new JsonJacksonCodec(configureObjectMapper()))
   .useClusterServers()
   .addNodeAddress(redisUrl)
   .setCredentialsResolver(sessionIamAuthTokenResolver);
return Redisson.create(config);
```
Could you explain what's going on and why updates happen so frequently?

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5589
