### ISSUE TITLE
Method Redisson#create keeps running Netty thread even if it fails to create a client instance

### ISSUE THREAD

**Issue by astsiapanay** [redisson/redisson#5631]
**Expected behavior**

All non daemon threads should be stopped if the method Redisson#create fails to create a client

**Actual behavior**

At least one Redisson Netty thread keeps running although the client is not created due to wrong configuration provided.

**Steps to reproduce or test case**

Run the code snippet below:

```
public static void main(String[] args) throws Exception {
        String conf = """
                {
                    "clusterServersConfig" : {
                        "nodeAddresses": []
                    }
                }
                """;
        ConfigSupport support = new ConfigSupport();
        Config config = support.fromJSON(conf.toString(), Config.class);
        Redisson.create(config);
 }
```

**Redis version**

Redis server is not required to reproduce the issue

**Redisson version**

Redisson 3.25.1

**Redisson configuration**

```
{
                    "clusterServersConfig" : {
                        "nodeAddresses": []
                    }
                }
```

**Comment by astsiapanay** [comment]
One more thing.
I've noticed that MasterSlaveConnectionManager attempts to create connection to Redis even if the list of node addresses is empty. It could be failed without any retries.

**Comment by mrniko** [comment]
Fixed. Thanks for report
