### ISSUE TITLE
Question - I have a question about the way you implemented locks

### ISSUE THREAD

**Issue by akfls221** [redisson/redisson#5632]
I understand that redisson uses the pub/sub method to implement distributed locks, but I'm wondering if that's correct? The documentation doesn't seem to mention it, and I don't get the impression that it uses pub/sub in the code. 

If you have any clarification or references on this, I'd appreciate it if you could reply :)

**Comment by raja2102598** [comment]
@akfls221 check this out, https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers#89-spin-lock

**Comment by mrniko** [comment]
There are multiple Lock implementations.

https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers#81-lock - uses pub/sub
https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers#89-spin-lock - uses loop
