### ISSUE TITLE
Will already authenticated connections continue to work after refreshing credentials via credentialsResolver dynamically? 

### ISSUE THREAD

**Issue by rgampa** [redisson/redisson#5633]
Will already authenticated connections continue to work after refreshing credentials via credentialsResolver dynamically? 

The javadoc for credentialsResolver say, so my question is will already authenticated old connections continue to work when the password is rotated?

```
* Credentials resolver object which is invoked during connection/reconnection process.
 * It makes possible to specify dynamically changing Redis credentials.
 ```
When using retryAttempts > 1, for example the old connection stopped working due to expired credentials, will Redission internally create new connection by calling resolve() method before throwing exception to client?

**Comment by mrniko** [comment]
> will already authenticated old connections continue to work when the password is rotated?

On WRONGPASS error a connection will be reconnected with authentication data got from credentialsResolver. It was fixed in 3.26.0 version.
