### ISSUE TITLE
When using RMapCache to save data, \x00 appears

### ISSUE THREAD

**Issue by lizesi** [redisson/redisson#5642]
demo project
springboot: 2.7.18
redisson: 3.26.1 / 3.21.0
redis: redis-windows-7.2.3 / redis-5.0.5

redisson codec: JsonJacksonCodec / StringCodec 

![image](https://github.com/redisson/redisson/assets/33739881/83cd9bc2-6e94-4660-9431-931f7a16df0b)
#1 When using StringRedisTemplate to save data, it is available
#2 When using RMapCache to save data, \ x00 appears, unavailable

I tracked the code and found that the error occurred after executing the Lua script
![image](https://github.com/redisson/redisson/assets/33739881/07b99933-61e2-43b8-a5c5-24a87e16a3c9)

eval "return struct.pack('dLc0', 0, string.len(ARGV[1]), ARGV[1])" 0 "test"
![image](https://github.com/redisson/redisson/assets/33739881/bd7cb65b-a512-4458-9dbd-07ddcaf98316)

How should I handle it

**Comment by JavaLionLi** [comment]
前面的那些东西是过期时间 RMapCache是带过期时间的
你不想要那些东西可以用RMap

**Comment by JavaLionLi** [comment]
Those things in front are expired RMapCache with expired time.
You don't want those things you can use RMap

**Comment by mrniko** [comment]
I agree if you don't need ttl or idlemaxtime per map entry then use RMap object

**Comment by lizesi** [comment]
意思是，前面那些 \x00 是正常存在的东西，一定会有。是吗？
