### ISSUE TITLE
Exception in redission netty thread throw java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by maliksajidhussain** [redisson/redisson#5651]
Hi Guys,

I am using redis: 3.26.0 using JSON config with a single redis instance (I am using OpenJDK 17). After running for many hours, I get a crash with the following exception. What could be the cause? Is it due to some bug in redisson OR wrong configurations?

`21-Feb-2024 21:04:09.134 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8081"]
21-Feb-2024 21:04:09.144 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio2-0.0.0.0-8443"]
21-Feb-2024 21:04:09.146 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [100710] milliseconds
Assertion failed: jSessionInfoObject != 0, file ../../common/src/util_conversion.c, line 1002
Exception in thread "http-nio-8081-Poller" java.lang.OutOfMemoryError: Java heap space
22-Feb-2024 04:23:53.506 SEVERE [http-nio-8081-exec-25824] org.apache.coyote.AbstractProtocol$ConnectionHandler.process Failed to complete processing of a request
	java.lang.OutOfMemoryError: Java heap space
Exception in thread "redisson-netty-1-6"`

Config
-------------
 {
	"singleServerConfig": {
		"idleConnectionTimeout": 20000,
		"connectTimeout": 15000,
		"timeout": 3000,
		"retryAttempts": 3,
		"retryInterval": 1000,
		"pingConnectionInterval": 10000,
		"password": null,
		"subscriptionsPerConnection": 5,
		"clientName": null,
		"address": "redis://192.168.103.71:6379",
		"subscriptionConnectionMinimumIdleSize": 1,
		"subscriptionConnectionPoolSize": 50,
		"connectionMinimumIdleSize": 10,
		"connectionPoolSize": 64,
		"database": 0,
		"dnsMonitoringInterval": 5000
	},
	"threads": 16,
	"nettyThreads": 32,
	"codec": null
}

**Comment by mrniko** [comment]
I need a memory dump. Without that it's hard to know the cause.
