### ISSUE TITLE
When readMode is used ?

### ISSUE THREAD

**Issue by CyrilDevOps** [redisson/redisson#5659]
Hi
I don't understand when the readMode configuration is used.

If I am using 'advanced' redisson object like RBucket, RedissonMap (spring boot cache) ...
will redisson go to the correct node so I don't get stale data ?
Or will it go to a slave node if readMode is SLAVE, for a 'get' operation and I can get stale data because of the redis replication lag ?

Thanks

**Comment by mrniko** [comment]
If readMode = SLAVE then getting stale data is possible.

**Comment by Sableng001** [comment]
Maka Data bisa Di gunakan kembali
