### ISSUE TITLE
在使用redssion(3.16.1)框架过程中 遇见问题

### ISSUE THREAD

**Issue by Eason0803** [redisson/redisson#5660]
org.redisson.client.RedisException: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression. channel: [id: 0x1de471a8, L:/192.168.18.52:41918 - R:r-2ze4114ca3030d64pd.redis.rds.aliyuncs.com/39.97.25.119:6565] command: (EVAL), params: [local insertable = false; local v = redis.call('hget', KEYS[1], ARGV[5]); if v == false then inserta..., 8, DF:test:cancel:queue1127, redisson__timeout__set:{DF:test:cancel:queue1127}, redisson__idle__set:{DF:test:cancel:queue1127}, redisson_map_cache_created:{DF:test:cancel:queue1127}, redisson_map_cache_updated:{DF:test:cancel:queue1127}, redisson__map_cache__last_access__set:{DF:test:cancel:queue1127}, redisson_map_cache_removed:{DF:test:cancel:queue1127}, {DF:test:cancel:queue1127}:redisson_options, ...]

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/1538#issuecomment-826583188
