### ISSUE TITLE
FlushListener receives duplicate events for a single flush determined by the amount of listeners

### ISSUE THREAD

**Issue by numsu** [redisson/redisson#5664]
**Expected behavior**
Each listener should receive a single event for a single flush.

**Actual behavior**
Each listener receives N flush events for a single flush where N is the amount of FlushListener instances.

**Steps to reproduce or test case**
1. Add more than one instance of FlushListener to RKeys
2. Flush Redis

**Redis version**
7.0.10

**Redisson version**
3.27.1

**Redisson configuration**
---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: "NIO"
protocol: RESP3

This can be easily circumvented on my end, but this doesn't seem like intended behavior.

**Comment by mrniko** [comment]
Fixed. Thanks for report
