### ISSUE TITLE
Redisson RBucket addListener功能没效果

### ISSUE THREAD

**Issue by sunyuanfeng** [redisson/redisson#5665]
RBucket<RedisReqVO> bucketRedisVo = redissonClient.getBucket("redisson:bucket:listener:object");
bucketRedisVo.addListener(new SetObjectListener() {
    @Override
    public void onSet(String name) {
        log.info("Key:{} Object设置了", name);
    }
});

如上代码，在set值时，监听器没有反应，在redis-cli中也没有查询到相应的topic。是我对RBucket的监听理解有问题吗？

**Comment by mrniko** [comment]
You need to define `notify-keyspace-events` setting in Redis configuration. It may have `KEA` value.
