### ISSUE TITLE
MapOptions<K,V> - Deprecated

### ISSUE THREAD

**Issue by andreilisa** [redisson/redisson#5668]
According to [javadoc ](https://www.javadoc.io/doc/org.redisson/redisson/3.27.0/org/redisson/api/MapOptions.html) the MapOptions<K,V> class is deprecated. There is nothing else in description what I have to use instead of it.

Shall I use `MapCacheOptions<K,V>` , subclass of  `MapOptions<K,V>` that is not deprecated ?
What could be the breaking changes of this migration ?

**Comment by mrniko** [comment]
You need to use `org.redisson.api.options.MapOptions` instead

**Comment by andreilisa** [comment]
@mrniko Thank you

 What about updating wiki and javadoc ?
 I could work on it.

**Comment by mrniko** [comment]
I updated javadocs. I would appreciate it if you would update the wiki.

**Comment by andreilisa** [comment]
Yes, it’s on me. Thank you one more time.
