### ISSUE TITLE
When redis switches master/slave in sentinel mode, the blockingqueue.take() blocking causes the queue to be unreadable.

### ISSUE THREAD

**Issue by jgdxl** [redisson/redisson#5670]
Redis sentinel mode is deployed in the cloud environment, and the server where the master node is located simulates the network disconnection and performs reboot, so that the cluster switches from master to slave. However, under redis version 3.10.1 and 3.18.0, there are messages in the queue but cannot be read, and newly added messages cannot be consumed. Unless the project is restarted, the messages in the queue can be re-consumed.
eg：String requestStr = redisson.getBlockingQueue(RedisKey.FILE_REQUEST_QUEUE).take();
The above code has been blocked, and new messages cannot be consumed unless the application is restarted. How to solve this problem?

**Comment by mrniko** [comment]
Unable to reproduce it with the [testTakeReattachSentinel()](https://github.com/redisson/redisson/blob/a3d78a3699f719632de9b1e9ff99e05a26d1b383/redisson/src/test/java/org/redisson/RedissonBlockingQueueTest.java#L212) and the latest Redisson version.

Can you share the logs with `trace` logging level for `org.redisson` package?

**Comment by jgdxl** [comment]
[app.log](https://github.com/redisson/redisson/files/14518274/app.log)
The log has been provided, and the master-slave switch occurred around 09:48 on March 7, 2024. The master node switched from 10.51.66.7 to 10.51.66.8

**Comment by mrniko** [comment]
Thanks for the provided log.
Can you share Redisson config?

**Comment by jgdxl** [comment]
![Screenshot_20240307_201110](https://github.com/redisson/redisson/assets/53468781/6bd3fa01-392c-413d-8052-8c6c75d3fa4a)
Sure, do you need anything else?

**Comment by mrniko** [comment]
do you use nameMapper setting?

**Comment by jgdxl** [comment]
What does nameMapper setting refer to? Can you give an example?

**Comment by mrniko** [comment]
Can you try the latest version?

**Comment by jgdxl** [comment]
I have used both 3.10.1 and 3.18.0+, but I have not used the latest version because it is too difficult to modify the project using the latest version and the environment does not support it. Can we solve this problem through other methods?

**Comment by mrniko** [comment]
> The sentinel address configured in the configuration file is the address discovered by the cloud environment sentinel cluster service

Can you share more details?

**Comment by jgdxl** [comment]
In the current deployment of Redis Sentinel mode in the cloud environment, the reboot master node must encounter this situation

**Comment by mrniko** [comment]
I don't see BLPOP command in your logs. Can you share the log since the application start moment and till the issue appear? (trace logging level for org.redisson)

**Comment by jgdxl** [comment]
[redisson.log](https://github.com/redisson/redisson/files/14557242/redisson.log)
[stack.log](https://github.com/redisson/redisson/files/14557246/stack.log)
Yes, this is the redisson log and redis basic information for the master-slave switch.
 redis sentinel configuration 10.51.155.4, 10.51.155.5, 10.51.155.6
 redis master: 10.51.155.3 slave: 10.51.163.3, 10.51.163.4
 redis master: 10.51.163.3 slave: 10.51.155.3, 10.51.163.4
 redisson. log is the entire log from the project restart (17:50) to the simulation of the master node disconnection and the master-slave switch (about 17:55) and the stack log after the switch.

**Comment by mrniko** [comment]
@jgdxl 

Sorry, I don't see BLPOP command. Master has been changed properly.

```
[2024-03-11 17:55:36.670] INFO [EMC,esb-receiver,default,service-esb-receiver][redisson-netty-1-1][][][][] o.r.connection.MasterSlaveEntry.operationComplete:470 - master 10.51.155.3/10.51.155.3:6379 has changed to 10.51.163.3/10.51.163.3:6379
```

**Comment by jgdxl** [comment]
https://github.com/redisson/redisson/issues/5670#issuecomment-1988144877
Sorry for the log advantages, I am also testing other methods to see if they are available. The log and stack log above are tested by getQueue(RedisKey.FILE_REQUEST_QUEUE).poll() through a timing task to read, and it is found that this scheme can not read data, and take() log will be provided later.

**Comment by jgdxl** [comment]
@mrniko 
Excuse me, could you give me some suggestions on how to fix this?

**Comment by mrniko** [comment]
I add debug messages which can help to resolve the issue

**Comment by jgdxl** [comment]
https://github.com/redisson/redisson/commit/9ff61997953047e3a9222edb497901b1ff35c720
The master branch version is too high, which is not suitable for our system. Can we add the corresponding debug on the 3.10.1 version? If so, where should we add it?

**Comment by mrniko** [comment]
@jgdxl 

You can look at the commit.

**Comment by jgdxl** [comment]
@mrniko 

Version 3.10.1 does not have the reattachBlockingQueue method, and the project is not compatible with the latest version，Can  add corresponding logs on 3.10.1?

**Comment by mrniko** [comment]
Unfortunately no, only to the latest version. 3.10.x isn't supported

**Comment by JWLiu1** [comment]
i've met the same question, use redisson 3.14.0;  redis master is down , the new master is ready ; can normally offer message to RDelayedQueue ,but the RBlockingQueue cannot be consume normally

**Comment by JWLiu1** [comment]
i've seach redisson 3.27.0 and latest 3.34.0,but not found reattachBlockingQueue in org.redisson.api.RedissonClient; so which version of redisson offer the reattachBlockingQueue method?
