### ISSUE TITLE
redisson-3.27.1 OSGi MANIFEST.MF imports package jdk.net which is not available under Java 8

### ISSUE THREAD

**Issue by axeluhl** [redisson/redisson#5674]
When using the OSGi-enabled redisson-3.27.1 JAR I cannot properly do the Tycho/OSGi build with Java 8:

[ERROR]   Missing requirement: redisson 3.27.1 requires 'java.package; jdk.net 0.0.0' but it could not be found

Checking the manifest, I see it has an Import-Package for jdk.net. The OSGi system bundle correctly doesn't export that for Java 8. But the redisson manifest also states:

Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"

so should work with Java 8. Should the jdk.net dependency be "Optional" maybe?

**Comment by mrniko** [comment]
Fixed. Thanks for report
