### ISSUE TITLE
ZPOPMIN\ZPOPMAX to count members error

### ISSUE THREAD

**Issue by bimslab** [redisson/redisson#5678]
**Expected behavior**
return Set<Tuple> result

**Actual behavior**
return Tuple result, internal cast exception

**Steps to reproduce or test case**
Object abc = redisTemplate.opsForZSet().popMin("key" , 2);

**Redis version**
7.0.12

**Redisson version**
3.27.1

**Redisson configuration**

**Comment by bimslab** [comment]
#5679 thinks

**Comment by mrniko** [comment]
merged
