### ISSUE TITLE
UDP ports are kept open during DNS monitoring

### ISSUE THREAD

**Issue by gergelylekorozsa** [redisson/redisson#5686]
**Expected behavior**

Redisson is configured with single server config. DNS monitoring is used with a 5 seconds TTL interval. We expect that every new DNS request opens a new UDP port, and closes it, so the subsequent DNS request is not using the same ephemeral UDP port.

**Actual behavior**

The UDP port is kept open, and is visible on the nmap scan. This is considered a security risk.
![DNS-queries](https://github.com/redisson/redisson/assets/163829028/3bfae129-fbf1-42db-8be2-ee4be92a0057)

**Steps to reproduce or test case**

Enable DNS monitoring with single server config

**Redisson version**

redisson:jar:3.25.0

**Redisson configuration**

     [singleServerConfig:](url)
     * idleConnectionTimeout: 10000
     * connectTimeout: 10000
     * timeout: 3000
     * retryAttempts: 3
     * retryInterval: 1500
     * password: null
     * subscriptionsPerConnection: 5
     * clientName: null
     * address: "redis://127.0.0.1:6379"
     * subscriptionConnectionMinimumIdleSize: 1
     * subscriptionConnectionPoolSize: 50
     * connectionMinimumIdleSize: 24
     * connectionPoolSize: 64
     * database: 0
     * dnsMonitoringInterval: 5000
     * threads: 16
     * nettyThreads: 32
     * codec: !<org.redisson.codec.MarshallingCodec> {}
     * transportMode: "NIO"

**Comment by michael-o** [comment]
What security risk?

**Comment by mrniko** [comment]
DNS connections are pooled to avoid "too many open files" issue.
