### ISSUE TITLE
Redisson's RRateLimiter is not working properly, permits are not refreshing every second 

### ISSUE THREAD

**Issue by SanyaSingh-Groww** [redisson/redisson#5687]
I am using RRateLimiter in this way, the pemits are not updating it seems every second. I am doing load test from locust and what ever tps it is showing rate limit is breaking before that.

 boolean rateLimitPassed =
                    rateLimiter.getRateLimitToken(GB_YES_DEBIT_INIT_1.name(), GB_YES_DEBIT_INIT_1, 150);
            if (!rateLimitPassed) {
                log.info(
                        "Rate limit exceeded for Yes Bank debit request -> payoutRequest : {}",payoutRequest);
                throw new RateLimitingException();
            }

public boolean getRateLimitToken(String key, RateLimitConfig rateLimitConfig, long timeoutInMillis) {

        try {
            RRateLimiter rateLimiter = redisUtil.getRateLimiter(key, rateLimitConfig.getConfiguration(), rateLimitConfig.getIntervalUnit());
            log.info(TRYING_TO_ACQUIRE_RATE_LIMITING_TOKEN_FOR_TIMEOUT_AVAILABLE_PERMITS, key, timeoutInMillis, rateLimiter.availablePermits());
            return rateLimiter.tryAcquire(timeoutInMillis, TimeUnit.MILLISECONDS);

        } catch (Exception exception) {
            //return true in case of redis error
            return true;
        }
    }

public RRateLimiter getRateLimiter(String key, RateLimiterConfig rateLimiterConfig, RateIntervalUnit rateIntervalUnit) {
        key = getRedisKey(key);
        RRateLimiter rateLimiter = redissonClient.getRateLimiter(key);
        rateLimiter.trySetRate(rateLimiterConfig.getRateType(),
                rateLimiterConfig.getRate(),
                rateLimiterConfig.getRateInterval(),
                rateIntervalUnit);
        return rateLimiter;
    }

**Comment by SanyaSingh-Groww** [comment]
REDISSION VERSION : 3.26.0

**Comment by mrniko** [comment]
Unable to reproduce with the test below.

```java
        RRateLimiter rr = redisson.getRateLimiter("test");
        assertThat(rr.trySetRate(RateType.OVERALL, 10, 1, RateIntervalUnit.SECONDS)).isTrue();
        
        Queue<Long> queue = new ConcurrentLinkedQueue<Long>();
        AtomicLong counter = new AtomicLong();
        ExecutorService pool = Executors.newFixedThreadPool(8);
        for (int i = 0; i < 8; i++) {
            pool.execute(new Runnable() {
                @Override
                public void run() {
                    while (true) {
                        if (rr.tryAcquire(100, TimeUnit.SECONDS)) {
                            if (counter.incrementAndGet() > 500) {
                                break;
                            }
                            queue.add(System.currentTimeMillis());
                        }
                        try {
                            Thread.sleep(ThreadLocalRandom.current().nextInt(10));
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        
                    }
                }
            });
        }
        
        pool.shutdown();
        assertThat(pool.awaitTermination(1, TimeUnit.MINUTES)).isTrue();
        
        int count = 0;
        long start = 0;
        for (Long value : queue) {
            if (count % 10 == 0) {
                if (start > 0) {
                    assertThat(value - start).isGreaterThan(940);
                }
                start = value;
            }
            count++;
        }
```

What is missed?

**Comment by mrniko** [comment]
@SanyaSingh-Groww 

Can you try attached version?

C:\Devel\projects\redisson\redisson\target\redisson-3.30.1-SNAPSHOT.jar.zip
[redisson-3.30.1-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/15466167/redisson-3.30.1-SNAPSHOT.jar.zip)

**Comment by mrniko** [comment]
Fixed
