### ISSUE TITLE
Allow disabling the sharding feature

### ISSUE THREAD

**Issue by uilton-oliveira** [redisson/redisson#5690]
**Is your feature request related to a problem? Please describe.**
We're facing many problems every time we try to upgrade to >= 3.23.0, probably due to the sharding: https://github.com/redisson/redisson/issues/5473#issuecomment-1867037208

**Describe the solution you'd like**
Be able to disable the sharding usage, maybe expose the setShardingSupported(true) and if set, disable the detectSharding method

**Describe alternatives you've considered**
We already tried many times upgrade the redisson, but without success, we are really stuck at the 3.22.1 version currently..

**Comment by mrniko** [comment]
Done. Use `shardedSubscriptionMode` setting
