### ISSUE TITLE
how to use `lazyInitialization` in springboot2.7.14?

### ISSUE THREAD

**Issue by xdewx** [redisson/redisson#5692]
[https://github.com/redisson/redisson/issues/5338](https://github.com/redisson/redisson/issues/5338)

It seems that the bug was fixed at 3.24.1, but i am using springboot-2.7.14 which can only use at most 3.18.0

**Comment by mrniko** [comment]
even Redisson latest version can use springboot-2.7.14. Please try it

**Comment by mrniko** [comment]
You can upgrade `redisson-spring-boot-starter` to the latest version and then exclude `redisson-spring-data-32` module and add `redisson-spring-data-27`
