### ISSUE TITLE
Unoptimized progressive allocations of primitive objects during boxing

### ISSUE THREAD

**Issue by GenCloud** [redisson/redisson#5695]
When profiling my application, I identified the vast majority of garbage produced using the 

![image](https://github.com/redisson/redisson/assets/7953029/fe255adb-7398-4d9c-9469-2a2bf0ff8c99)

It all comes down to the fact that garbage is produced by boxing primitives both in RedisURI#hashCode itself and in grouping the map by hashcode.

Options for solving boxing problems
- collections based on explicitly primitive types without the use of object wrappers

Potential replacement option:
- https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/util/containers/ConcurrentIntObjectMap.java

**Comment by mrniko** [comment]
Done. Please try and give your feedback.

**Comment by GenCloud** [comment]
Where i can find snaphot repo or just build master branch for self?

**Comment by mrniko** [comment]
just build the master branch

**Comment by GenCloud** [comment]
I'll wait for the release and give feedback after. There is no time to test yet.
