### ISSUE TITLE
Does Redisson-Cluster-Mode support RPriorityBlockingQueue?

### ISSUE THREAD

**Issue by senolatac** [redisson/redisson#5702]
When I try to use RPriorityBlockingQueue in cluster-mode, I get some lock errors.
`Caused by: java.lang.IllegalStateException: None of slaves were synced. Try to increase slavesSyncTimeout setting or set checkLockSyncedSlaves = false.`

and my code looks like:

`redissonClient.getPriorityBlockingQueue(queueName, codec).offer(data);`

Am I missing something? or RPriorityBlockingQueue doesn't work on cluster-mode?

**Comment by mrniko** [comment]
Unable to reproduce the issue with the latest version.

RPriorityBlockingQueue is cluster compatible.

**Comment by mrniko** [comment]
Since locks are used by RPriorityBlockingQueue. you need to set `checkLockSyncedSlaves = false` setting or add a slave node.
