### ISSUE TITLE
redisson_delay Prefix disappears

### ISSUE THREAD

**Issue by chen9ian9** [redisson/redisson#5703]
I use redission as the delay queue in my project, but after a period of normal operation, the generated delay queue does not have the prefix redisson_delay_queue:, only the queue code given.
< dependency >.
< groupId > org.redisson < / groupId >.
< artifactId > redisson-spring-boot-starter < / artifactId >.
< version > 3.16.2 < / version >.
< / dependency >

**Comment by mrniko** [comment]
What is the value for maxmemory-policy setting?
