### ISSUE TITLE
How does Redisson-hibernate 2nd level caching cache data

### ISSUE THREAD

**Issue by zoroglu** [redisson/redisson#5721]
How does it cache data? So, does it put the entity's id as the key? I didn't see it in the document.

**Comment by mrniko** [comment]
Hibernate may use different objects as key. Redisson is able to store any of them.

https://github.com/redisson/redisson/blob/master/redisson-hibernate/redisson-hibernate-6/src/main/java/org/redisson/hibernate/RedissonStorage.java#L120
