### ISSUE TITLE
SearchDomainUnknownHostException with ElastiCache

### ISSUE THREAD

**Issue by namsic6460** [redisson/redisson#5726]
Hello, I've created an issue card related to Redisson as the error message keeps appearing. The error is as follows:

DnsResolveContext$SearchDomainUnknownHostException
Failed to resolve 'xxx.xxx.xxx.apn2.cache.amazonaws.com' [A(1)] and search domain query for configured domains failed as well: [ap-northeast-2.compute.internal]

Upon investigation, I found that there have been many issue cards related to this matter. It has been noted that there are various attempts that can be made, such as tweaking the Config or reducing the number of DNS queries. However, I do not believe these are fundamental solutions. Could there be a definitive solution I haven't found? Currently, we are using the Redisson project very successfully in our live services. While the above error does not seem to directly affect the service, if possible, I would like to eliminate the error, hence I am leaving this issue card.

For your reference, the specs being used are as follows:

- ECS/EC2
- amazoncorretto:11
- Springboot 2.7.16
- Redisson 3.23.1
- Netty 4.1.91.Final (Mentioning this as a dependency due to claims of a Netty bug)

(The translation might be awkward since it's from a translator. If there are parts you don't understand, please leave a comment)

**Comment by mrniko** [comment]
Did you try to define SequentialDnsAddressResolverFactory with concurrencyLevel = 1

Yaml config example:

```yaml
singleServerConfig:
  address: "redis://xxx:xxx"
addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> 1
```

**Comment by namsic6460** [comment]
If the limit on DNS query counts is the issue, then this could be a fundamental solution.
I will try with the above settings and let you know!

**Comment by namsic6460** [comment]
After applying the settings, I confirmed that the error has not occurred for about three weeks

**Comment by musicallyvk** [comment]
Hi,
thanks for replying again,

firstly it is using replicatedServersConfig .
secondly on AWS it is only using primary endpoint and reader endpoint  ( it has  4 nodes with 1 primary and 3 replica, also i do not know if this info helps you ), Configuration endpoint
 colum is empty on aws redis cache cluster.

so what do you suggest , what should i change.

**Comment by mrniko** [comment]
`addressResolverGroupFactory` setting is applied to all Redis configurations.

```
replicatedServersConfig:
  ...
addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> 1
```

**Comment by musicallyvk** [comment]
value for    addressResolverGroupFactory :  will remain the same which is given below or do i have to change it according to my code ?

!<org.redisson.connection.SequentialDnsAddressResolverFactory> 1

**Comment by mrniko** [comment]
yes, just define addressResolverGroupFactory as I suggested

**Comment by musicallyvk** [comment]
Hey @mrniko  

Hope You are having a good time, 
just wanted to ask , i am using .properties file , and i am not sure if it will take 1 as a value,

my .properties file will look like below
"addressResolverGroupFactory" :  "!<org.redisson.connection.SequentialDnsAddressResolverFactory>"

what to do with this 1.

will this cause any error issue, or is it fine if i write 1 also inside inverted commas in the value part ?

thanks a Ton!

**Comment by mrniko** [comment]
@musicallyvk 

Hi. Redisson doesn't support properties file. Yaml only

**Comment by namsic6460** [comment]
@musicallyvk Below is a part of my code. After applying this setting, the error mentioned occurred only once in about two months. I hope this helps.

`@Configuration
@RequiredArgsConstructor
public class RedissonConfig {

    private final RedisProperties redisProperties;

    @Bean
    public RedissonClient redissonClient() {
        String prefix = "redis";
        if (BooleanUtils.isTrue(this.redisProperties.getSsl())) {
            prefix += "s";
        }

        Config config = new Config();
        config.setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory(1));
        config.useSingleServer()
            .setAddress(prefix + "://" + this.redisProperties.getHost() + ":" + this.redisProperties.getPort())
            .setPassword(this.redisProperties.getPassword())
            .setDatabase(this.redisProperties.getDatabase());

        return Redisson.create(config);
    }
}`

**Comment by musicallyvk** [comment]
> @musicallyvk
> 
> Hi. Redisson doesn't support properties file. Yaml only

as per your reply, my project is using .properties files only for redission, and it is working

**Comment by musicallyvk** [comment]
> @musicallyvk Below is a part of my code. After applying this setting, the error mentioned occurred only once in about two months. I hope this helps.
> 
> ```
> private final RedisProperties redisProperties;
> 
> @Bean
> public RedissonClient redissonClient() {
>     String prefix = "redis";
>     if (BooleanUtils.isTrue(this.redisProperties.getSsl())) {
>         prefix += "s";
>     }
> 
>     Config config = new Config();
>     config.setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory(1));
>     config.useSingleServer()
>         .setAddress(prefix + "://" + this.redisProperties.getHost() + ":" + this.redisProperties.getPort())
>         .setPassword(this.redisProperties.getPassword())
>         .setDatabase(this.redisProperties.getDatabase());
> 
>     return Redisson.create(config);
> }
> ```

Hi @namsic6460  Thank You Very Much For Replying . i am using replicated server config and also i am using .properties file and yaml both files are there, i do not understand because @mrniko  said that redission only uses yaml. 
I am very new to this , can you please help @namsic6460  as it is already working for you.
also i need the config or yaml file of yours if you dont mind please.
or else i have already shared my config file above somewhere already,  please check that what is wrong in this.

thak you very much

**Comment by namsic6460** [comment]
@musicallyvk 
I did not use .yml or .properties files for these settings. The code I posted is all there is, and it is configured through a bean.

**Comment by musicallyvk** [comment]
> config.setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory(1));

@namsic6460 
at this line     config.setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory(1));
i am getting an error, this new SequentialDnsAddressResolverFactory(1), where are you importing this from ? is there any library you added for this or created a class or what , because this new SequentialDnsAddressResolverFactory(1) is giving me not specified.

please Help!

**Comment by namsic6460** [comment]
@musicallyvk Class is defined in redisson
https://github.com/redisson/redisson/blob/9e211c93c52eb0f73dc0aedacbba5e30e89f2326/redisson/src/main/java/org/redisson/connection/SequentialDnsAddressResolverFactory.java#L43

**Comment by musicallyvk** [comment]
Hi @namsic6460  Thanks Man, i think My Redisson version does not have this class
<img width="1728" alt="Screenshot 2024-06-10 at 11 20 00 AM" src="https://github.com/redisson/redisson/assets/139149466/92f7b1b8-5aa4-4dda-955a-26933acde946">

so do i need to update redisson or can i add something else here like DnsAddressResolverGroupFactory  or  RoundRobinDnsAddressResolverGroupFactory

**Comment by mrniko** [comment]
@musicallyvk 

It's better to updated version

**Comment by musicallyvk** [comment]
> SequentialDnsAddressResolverFactory

shall i change it to the latest version which is 3.30.0. or to some specific version,
i am little afraid because my project is so huge , i wonder if it impacts any other stuff.

but still what version would be better guys?

**Comment by namsic6460** [comment]
@musicallyvk 
It is generally advisable to use the latest version. Of course, there will be many changes to review, but the initial verification is the responsibility of the developers of this project, and the final verification is up to you.
