### ISSUE TITLE
Executing multiple RSet.add and RSet.contains methods within the same transaction results in the LEAK error.

### ISSUE THREAD

**Issue by przeswid** [redisson/redisson#5728]
**Expected behavior**
No error should occur when executing multiple RSet.add and RSet.contains methods within the same transaction.

**Actual behavior**
When executing many RSet.add and RSet.contains methods within the same transaction ERROR log appears in the system logs:

> ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:404)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:174)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:108)
	org.redisson.codec.Kryo5Codec$5.encode(Kryo5Codec.java:167)
	org.redisson.command.CommandAsyncService.encode(CommandAsyncService.java:834)
	org.redisson.RedissonObject.encode(RedissonObject.java:325)
	org.redisson.transaction.BaseTransactionalSet.isEqual(BaseTransactionalSet.java:414)
	org.redisson.transaction.BaseTransactionalSet.containsAsync(BaseTransactionalSet.java:134)
	org.redisson.transaction.RedissonTransactionalSet.containsAsync(RedissonTransactionalSet.java:129)
	org.redisson.RedissonSet.contains(RedissonSet.java:77)
	p.swida.RedissonTests$LeakByteBuf.reproduceLeakProblem(RedissonTests.java:233)

Although the data in Redis remains correct, this error message suggests the possibility of future issues arising.

**Steps to reproduce or test case**
Execute any RSet modification operation (`add`, `remove`) and `contains` within the same transaction. In our system, we have a more complex scenario, but I managed to isolate the error using the simplified code below. The issue occurs only when a certain quantity of operations needs to be executed. In the code snippet below, I referred to this quantity as `arbitraryElementsCount`

```java
int arbitraryElementsCount = 1000;

RTransaction tx = redissonClient.createTransaction(TransactionOptions.defaults());
RSet<Integer> testSet = tx.getSet("testSet");

for (int index = 0; index < arbitraryElementsCount; index++) {
   testSet.add(index);
    // .. Here should be the code that will make the following line make sense ;)
   if (testSet.contains(index)) {
       // ...
   }
}
tx.commit();
```

**Redis version**
7.2.4

**Redisson version**
3.27.2

**Redisson configuration**
```java
Config config = new Config();
config.useSingleServer().setAddress("redis://127.0.0.1:6379");
```

**Comment by mrniko** [comment]
Merged
