### ISSUE TITLE
Create a Serializer using Spring IoC

### ISSUE THREAD

**Issue by jrx-amf** [redisson/redisson#5729]
Hi,

I'm evaluating Redisson as an alternative to Hazelcast in a spring boot application, and at the moment I'm using Kryo5Codec.

Taking as reference the example from the documentation:

```
public class AddressSerializer extends Serializer<Address> {

     @Override
     public void write(Kryo kryo, Output output, Address address) {
         output.writeString(address.getStreet());
         output.writeString(address.getCity());
         output.writeString(address.getCountry());
     }

     @Override
     public Address read(Kryo kryo, Input input, Class<Address> type) {
         return new Address(input.readString(), input.readString(), input.readString());
     }
}
```

I would like to know if it is possible to inject dependencies with @Autowired at field, constructor or setter level. I have been doing several tests based on the Kryo5Codec class itself, but still without success. 

Thanks in advance,
Antonio

**Comment by mrniko** [comment]
Sorry, it's a question about Kryo5 and Spring integration. Can you refer it to Kryo Team?

**Comment by jrx-amf** [comment]
Hi @mrniko, yes of course. Thanks for your time & attention.
