### ISSUE TITLE
Connection pool exhausted

### ISSUE THREAD

**Issue by INM0722** [redisson/redisson#573]
When set rertyAttemps to 0. connection pool size is 100. use 100 threads to read the redis cluster,it will throw exception like "Connection pool exhausted! for slots: [[8192-12287]] Disconnected hosts: [/10.2.30.72:6389] Hosts with fully busy connections: [/10.2.30.70:6381]".
In my point of view,it's caused by LoadBalance.

**Comment by mrniko** [comment]
I think when rertyAttempts is 0 then retry logic should be completely turned off

**Comment by mrniko** [comment]
What `readMode` value did you set? how many slaves do you have for 8192-12287?

**Comment by INM0722** [comment]
ReadMode is ReadMode.SLAVE,just one slave for the slots

**Comment by mrniko** [comment]
> In my point of view,it's caused by LoadBalance.

Why this can be caused by LoadBalance if you have only one slave?

**Comment by INM0722** [comment]
With the Round Robin LoadBalancer, one thread may get two master connections,but both of them are freezed,could't get the connection.

**Comment by INM0722** [comment]
Sorry,not two master connectiones,it's two master entries

**Comment by mrniko** [comment]
if I understand correctly 10.2.30.72:6389 - is master and 10.2.30.70:6381 - slave for this master?

**Comment by INM0722** [comment]
yeah，the code is :
```
for (int j = entries.size() - 1; j >= 0; j--) {
            ClientConnectionsEntry entry = getEntry();
            if (!entry.isFreezed() && tryAcquireConnection(entry)) {
                return connectTo(entry);
            }
        }
```
In concurrent cases，`getEntry()` may never return any slave entries...so the code:`connectTo(entry);` will never be executed,then,run the code 
```
List<InetSocketAddress> zeroConnectionsAmount = new LinkedList<InetSocketAddress>();
        List<InetSocketAddress> freezed = new LinkedList<InetSocketAddress>();
        for (ClientConnectionsEntry entry : entries) {
            if (entry.isFreezed()) {
                freezed.add(entry.getClient().getAddr());
            } else {
                zeroConnectionsAmount.add(entry.getClient().getAddr());
            }
        }

        StringBuilder errorMsg;
        if (connectionManager.isClusterMode()) {
            errorMsg = new StringBuilder("Connection pool exhausted! for slots: " + masterSlaveEntry.getSlotRanges());
        } else {
            errorMsg = new StringBuilder("Connection pool exhausted! ");
        }
```
finally,throw the exception.

**Comment by mrniko** [comment]
ClientConnectionsEntry - is a connection holder object for each Redis node.
If all connections were acquired but haven't released then such exception will arise.

**Comment by mrniko** [comment]
I would recommend you to increment connection pool size

**Comment by pengfei-xu** [comment]
@mrniko when I switch  Master/slave with redis server . it also will cause it . RetryAttempts set 25.
MasterConnectionPoolSize set 200.

**Comment by mrniko** [comment]
Another cause of such issue is network delays for response/request redis

**Comment by mrniko** [comment]
This issue resolved here https://github.com/redisson/redisson/issues/680
