### ISSUE TITLE
Do Redisson supports ElasticCache Serverless? Are there any different Configs?

### ISSUE THREAD

**Issue by rishiCS** [redisson/redisson#5730]

**Comment by rishiCS** [comment]
Hi @mrniko Why in single mode and not in Cluster?

**Comment by mrniko** [comment]
Single mode works with a single master instance only. Multiple master nodes resolved by a single hostname supported only in [Proxy mode](https://github.com/redisson/redisson/wiki/2.-Configuration/#29-proxy-mode)

**Comment by rishiCS** [comment]
Hi @mrniko , Still it's not clear to me. 
We're currently using Cluster mode with Cluster mode ON. And we're using version - 3.24.1
If we want to move to Serverless how the configs will look like for Redisson and which version to use?
We're currently using `clusterServersConfig` of Redisson.
