### ISSUE TITLE
enables references  to the same object and cyclic graphs to be serialized 

### ISSUE THREAD

**Issue by yarivMobitti** [redisson/redisson#5743]
I'm trying to save a recursive object in Redis. For example:

`public Test(){
Test test;
}`
I noticed that the codec implementation is Kryo5Codec, which is set with kryo.setReferences(false); when initializing the Kryo object:

`    protected Kryo createKryo(ClassLoader classLoader) {
        Kryo kryo = new Kryo();
        if (classLoader != null) {
            kryo.setClassLoader(classLoader);
        }
        kryo.setInstantiatorStrategy(new SimpleInstantiatorStrategy());
        kryo.setRegistrationRequired(false);
        kryo.setReferences(false);
        kryo.addDefaultSerializer(Throwable.class, new JavaSerializer());
        kryo.addDefaultSerializer(UUID.class, new DefaultSerializers.UUIDSerializer());
        kryo.addDefaultSerializer(URI.class, new DefaultSerializers.URISerializer());
        kryo.addDefaultSerializer(Pattern.class, new DefaultSerializers.PatternSerializer());
        return kryo;
    }`
    
    
To solve this, I overrode it like so:

    
    `public class CustomKryoCodec extends Kryo5Codec {

	@Override
	protected Kryo createKryo(ClassLoader classLoader) {
		Kryo kryo = super.createKryo(classLoader);
		kryo.setReferences(true);
		return kryo;
	}

}`

and set the Redisson config with:

`config.setCodec(new CustomKryoCodec());`

Is there native support in Redisson for working with recursive objects?

 Redisson version: 3.23.2

**Comment by mrniko** [comment]
`useReferences` setting added in 3.36.0 version
