### ISSUE TITLE
ElasticCache Serverless

### ISSUE THREAD

**Issue by rishiCS** [redisson/redisson#5745]
We're currently using Cluster mode with Cluster mode ON. And we're using version - 3.24.1
If we want to move to Serverless how the configs will look like for Redisson and which version to use?
We're currently using clusterServersConfig of Redisson.

**Comment by mrniko** [comment]
AWS Serverless mode provides a single hostname resolved to multipe nodes. Use single mode if you want to use a single node of all nodes. Use [Proxy mode](https://github.com/redisson/redisson/wiki/2.-Configuration/#29-proxy-mode) if you want to use all nodes.
