### ISSUE TITLE
java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/serializers/DefaultSerializers$UUIDSerializer

### ISSUE THREAD

**Issue by lchaofu** [redisson/redisson#5748]
redisson version: 3.27.2

code
```code
  Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://host")
                .setPassword("xxxxxx")
                .setDatabase(0);
        RedissonClient client = Redisson.create(config);
```

exception: 
java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/serializers/DefaultSerializers$UUIDSerializer

	at org.redisson.config.Config.<init>(Config.java:114)
	at org.redisson.Redisson.<init>(Redisson.java:69)
	at org.redisson.Redisson.create(Redisson.java:116)

The error occurs starting from version 3.19.1

**Comment by vithu30** [comment]
@lchaofu how did u resolve the above issue?

**Comment by lchaofu** [comment]
> @lchaofu how did u resolve the above issue?

The codec version in the project is inconsistent with the Redisson codec version
