### ISSUE TITLE
Rbatch excute() method miss command

### ISSUE THREAD

**Issue by AaronFeng2014** [redisson/redisson#5756]
When I use Rbatch to save some value into hash, i found that sometime the command in rbatch is not be excuted completely, and miss some command, because I query the value in immediately, but is is not the value I saved before

redis cluster,
code 
<img width="1111" alt="image" src="https://github.com/redisson/redisson/assets/13704237/c99d7447-66ac-4c5e-ae8b-c1b6a89fcc44">

**Comment by mrniko** [comment]
Can you share the code to reproduce it?

**Comment by mrniko** [comment]
> I query the value in immediately, but is is not the value I saved before

That can be caused by master slave replication lag. Try to use readMode = MASTER
