### ISSUE TITLE
OSGi MANIFEST.MF headers should specify optional dependencies

### ISSUE THREAD

**Issue by TomasTokaMrazek** [redisson/redisson#5774]
Optional packages listed in https://github.com/redisson/redisson/wiki/15.-Dependency-list should also be optional under `Import-Package` header. Right now basically every dependency is needed at runtime in OSGi environments, even if unused.

Simmilar issue already merged and closed.
https://github.com/redisson/redisson/issues/5674

**Comment by TomasTokaMrazek** [comment]
I am currently wrapping redisson in custom OSGi bundle.

Kryo, Reactor, Jackson and Netty libraries are part of classpath as separate bundles.

This is my wrapper configuration for `bnd`. I guess the same can be added to pom.
```
Import-Package: \
    io.reactivex.rxjava3.*;resolution:=optional, \
    javax.cache.*;resolution:=optional, \
    jodd.*;resolution:=optional, \
    net.bytebuddy.*;resolution:=optional, \
    org.jboss.marshalling.*;resolution:=optional, \
    org.springframework.*;resolution:=optional, \
    *
```
The `Import-Package` clausule is missing packages for Reactor and Kryo library, as they are already availible in classpath. If Kryo packages should be marked as optional or required is up to debate.

**Comment by mrniko** [comment]
Thanks for pointing out and the details. Fixed

**Comment by TomasTokaMrazek** [comment]
@mrniko Just a heads up, looking at the commit. Package `io.projectreactor` should also be included as optional per https://github.com/redisson/redisson/wiki/15.-Dependency-list.

It was missing from my example, becuase I had the package in classpath.

**Comment by mrniko** [comment]
Fixed
