### ISSUE TITLE
Lua throwing error for bitmap operations

### ISSUE THREAD

**Issue by ShashankSByakod37** [redisson/redisson#5785]
Use case : We are using BITMAP on one of our use case, where we are sending the key array and ARG array as arguement for the evalSHA. 
On lua script, it gonna iteratively traverse the ARG array and set the corresponding bit on the redis.

LUA script

`local key = KEYS[1]
local cntr = 0
for _, userId in ipairs(ARGV) do
    local bitIndex = tonumber(userId)
    redis.call('SETBIT', key, bitIndex, 1)
    cntr = cntr + 1
end
return cntr`

Client Redisson v3.27.2
Mode : Master-slave

Sample code 

On post construct we are loading the lua script to the redis server

audienceDataRedisSha = redissonClient.getScript(BitSetCodec.INSTANCE).scriptLoad(luaScript);

`redissonClient
            .getScript(BitSetCodec.INSTANCE)
            .evalSha(
                redisKey,
                RScript.Mode.READ_WRITE,
                audienceDataRedisSha,
                RScript.ReturnType.INTEGER,
                Collections.singletonList(redisKey),
                1234,
                12343,
                8655,
                92949,
                23344242,
                234434,
                8888,
                22);`

I have tried executing the lua script directly on the redis cli, that worked with expected result.
java.lang.UnsupportedOperationException: null
	at org.redisson.client.codec.BitSetCodec.getValueEncoder(BitSetCodec.java:61)
	at org.redisson.command.CommandAsyncService.encode(CommandAsyncService.java:834)
	at org.redisson.RedissonScript.encode(RedissonScript.java:201)
	at org.redisson.RedissonScript.evalShaAsync(RedissonScript.java:234)
	at org.redisson.RedissonScript.evalSha(RedissonScript.java:258)

**Comment by ShashankSByakod37** [comment]
@mrniko Can you pls help here?

**Comment by mrniko** [comment]
BitSetCodec class is for internal purposes only.

**Comment by ShashankSByakod37** [comment]
@mrniko I even tried with the different classes too, still getting the same result. What should be the ideal codec for this?
