### ISSUE TITLE
when use JDK 1.8.0_202 , commandExecutor cause CPU load high

### ISSUE THREAD

**Issue by crossdawn** [redisson/redisson#5799]
cause:
**commandExecutor.get(future)
return future.toCompletableFuture().get();**

java.util.concurrent.CompletableFuture#get()
private Object waitingGet(boolean interruptible) {
            spins = (Runtime.getRuntime().availableProcessors() > 1) ?
bug:
  https://bugs.openjdk.org/browse/JDK-8227019
suggestion:
 **get(long timeout, TimeUnit unit)**

**Comment by crossdawn** [comment]
> get(long timeout, TimeUnit unit)



> 谢谢你的建议。不幸的是，它没有考虑阻止呼叫。它需要更多的努力来实现，而不是升级 JDK8 构建。

how about    get(Integer.MAX_VALUE, TimeUnit.MILLISECONDS)

**Comment by crossdawn** [comment]
> Thank for suggestion. Unfortunately, it doesn't take in account blocking calls. It requires much more effort for implementation rather than upgrading JDK8 build.

how about get(Integer.MAX_VALUE, TimeUnit.MILLISECONDS)

**Comment by mrniko** [comment]
Why do we need to adopt the project to this old JDK8 build?
