### ISSUE TITLE
I use aggregate apply ，error come Unknown argument

### ISSUE THREAD

**Issue by yinjiajin1990** [redisson/redisson#5800]
my code is:
String geoDistance =  String.format("geodistance(@location, %s,%s)", publicPlaceAndParkingQo.getLongitude(), publicPlaceAndParkingQo.getLatitude());
        RSearch search = redissonClient.getSearch(StringCodec.INSTANCE);
        AggregationResult aggregate = search.aggregate("public_place_parking_idx", "*", AggregationOptions.defaults()
                .load("$.location", "as", "location", "$.*", "as", "$").apply(new Expression(geoDistance, "dist"))
                .limit(0, 1000));
error is：
org.redisson.client.RedisException: Unknown argument `dist` at position 11 for <main>. channel: [id: 0x81404a7b, L:/10.254.0.113:55593 - R:10.10.2.74/10.10.2.74:6379] command: (FT.AGGREGATE), promise: java.util.concurrent.CompletableFuture@7d5e020c[Not completed, 1 dependents], params: [public_place_parking_idx, *, LOAD, 6, $.location, as, location, $.*, as, $, ...]

**Comment by mrniko** [comment]
Fixed. Thanks for report
