### ISSUE TITLE
aggregate load , i can not get all data i want

### ISSUE THREAD

**Issue by yinjiajin1990** [redisson/redisson#5808]
my code is:
```
        String geoDistance = String.format("geodistance(@location, %s,%s)", publicPlaceAndParkingQo.getLongitude(), publicPlaceAndParkingQo.getLatitude());
        RSearch search = new MyRedissonSearch(StringCodec.INSTANCE, ((Redisson)redissonClient).getCommandExecutor());
        AggregationResult aggregate = search.aggregate("public_place_parking_idx", "*", AggregationOptions.defaults()
                .load("$.location", "as", "location", "$.*", "as", "data").apply(new Expression(geoDistance, "dist"))
                .limit(0, 1000));
```
i want get all data, so i use "$.* as data" . but the "data" filed not return true all data , only $.address return 。please help me ,how to get all data.

![image](https://github.com/redisson/redisson/assets/28622180/ad07ed31-0e50-4686-9041-ce85db873690)

![image](https://github.com/redisson/redisson/assets/28622180/6afc7815-22ee-4ff0-b2f1-7889bd06ccad)

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by yinjiajin1990** [comment]
> Which Redisson version do you use?

i use redisson-spring-boot-starter 3.28.0

**Comment by mrniko** [comment]
use 3.29.0 version. Several issues in aggregate() method has been fixed in this version.

**Comment by yinjiajin1990** [comment]
> 3.29.0 version

3.29.0 version also has the same problem.please help !
![image](https://github.com/redisson/redisson/assets/28622180/79b7e020-91c0-46be-a7fb-518cf2d13e1c)


```
        RSearch search1 = new RedissonSearch(StringCodec.INSTANCE, ((Redisson)redissonClient).getCommandExecutor());
        AggregationResult aggregate1 = search.aggregate("public_place_parking_idx", "*", AggregationOptions.defaults()
                .load("$.location", "as", "location", "$.*", "as", "data").apply(new Expression(geoDistance, "dist"))
                .limit(0, 1000));
```
![image](https://github.com/redisson/redisson/assets/28622180/7cd406aa-605d-4a2a-a839-f0ecc6e98c8d)

**Comment by mrniko** [comment]
Can you provide a sample project so I could reproduce the issue?

**Comment by yinjiajin1990** [comment]
> Can you provide a sample project so I could reproduce the issue?

i see you have test case . but i can not run it . you can run it please.

![image](https://github.com/redisson/redisson/assets/28622180/00471e34-2e86-4a5f-9289-ba6fc55381a8)
