### ISSUE TITLE
Register a module with JsonJacksonCodec within YAML configuration

### ISSUE THREAD

**Issue by dandan2611** [redisson/redisson#5810]
Hello!

Regular user of Redisson here. I wanted to use the external configuration from YAML. I always initialized my `Config` from code.

Everything is working perfectly! But I wondered if there was any documentation on the `codec` field?

I am using the `JsonJacksonCodec` with the following config entry:
```YAML
codec: !!org.redisson.codec.JsonJacksonCodec {}
```

I want to register custom modules, such as the `JavaTImeModule` (`com.fasterxml.jackson.datatype.jsr310.JavaTimeModule`). I inspected the source code and saw that this field is maybe using some really deep Jackson features to construct a class from a configuration.

Is any configuration sample or example provided? Or is there any Jackson article who explains this feature?

I am using the latest Redisson version.

After getting an answer, I'll make sure to PR some documentation additions in order to cover this case correctly :)

Thanks a lot!
Adam.

**Comment by raja2102598** [comment]
Hi @dandan2611, I think there is no direct way to register custom modules from yaml file.


Other option is override the JsonJacksonCodec and register your modules then give your customClass in the yaml config.

**Comment by dandan2611** [comment]
Alright, I'll do that. Thank you!
