### ISSUE TITLE
How do i disable Redisson Cache mechanisam

### ISSUE THREAD

**Issue by ygravikiran** [redisson/redisson#5813]
Am using EhCache in my sprint boot Hibernate application.

Now am using Redission library to store the data to Redis.

Am getting Multi-Cache exception when both EhCache and Reddison being used together.
Caused by: javax.cache.CacheException: Multiple CachingProviders have been configured when only a single CachingProvider is expected

Is there a way to avoid Redission Caching and use only EhCache.

**Comment by mrniko** [comment]
the only way is to delete META-INF\services\javax.cache.spi.CachingProvider file in jar
