### ISSUE TITLE
SentinelConnectionManager stops scheduling change check / dns check after error

### ISSUE THREAD

**Issue by chengyiuchun** [redisson/redisson#5818]
**Expected behavior**
SentinelConnectionManager should continue to perform change check and dns check after encountering transient DNS issue like resolve hostname failure.

**Actual behavior**
Once there is an error (e.g. DNS resolution error), all future calls to SentinelConnectionManager.scheduleChangeCheck and SentinelConnectionManager.scheduleSentinelDNSCheck will be suppressed.

From a high level view, looks like it's due to the next schedule call is called inside .thenAccept. It probably should be .whenComplete.

**Steps to reproduce or test case**

```
Redisson.create(
   new Config()
    .useSentinelServers()
    .setMasterName("mymaster")
    .addSentinelAddress("redis://temporarily-unavailable-hostname:26379")
)

```
We can see that scheduleSentinelDNSCheck is called once and never again, similarly for scheduleChangeCheck .

**Redis version**
7.0

**Redisson version**
3.27.2

**Redisson configuration**
Like in above test case

**Comment by mrniko** [comment]
Thanks for pointing out. Fixed
