### ISSUE TITLE
Inconsistency in Redisson's RLiveObjectService.find() Method: Retrieving Outdated Data Despite Updates

### ISSUE THREAD

**Issue by karthik2020mind** [redisson/redisson#5827]
**Issue Description:**
The RLiveObjectService.find() method in Redisson is returning objects with outdated status values, despite the status being updated in the Redis cache. The search should be conducted based on the latest value of the status field, but it continues to retrieve objects with older status values, leading to inconsistency in the retrieved data.

In the given code snippet, an instance of RLiveObjectService is obtained from the Redisson client using the getLiveObjectService() method:

`RLiveObjectService service = redisson.getLiveObjectService();`

This service is used to interact with live objects stored in Redis, allowing for seamless integration between Java objects and Redis data structures.

Next, the find() method of the RLiveObjectService is invoked to search for instances of the MyCustomObject class based on a specified condition. The condition is constructed using the Conditions class to ensure that only objects with a status field equal to "processing" are retrieved:

`List<MyCustomObject> results = service.find(MyCustomObject.class, Conditions.and(Conditions.eq("status","processing")));`

The expectation is that the find() method should return a list of MyCustomObject instances where the status field is "processing". However, the observed behavior contradicts this expectation, as the returned list contains MyCustomObject instances with statuses other than "processing".

Upon further investigation, it is discovered that although the initial status of the MyCustomObject instances stored in Redis was "processing", some of them were later updated to a different status, such as "completed". Despite this update, the find() method continues to return objects with the outdated "processing" status.

The expectation is that the search should be conducted based on the latest value of the status field in the Redis cache. However, it is unclear why the find() method is returning objects with older status values, even after they have been updated.

This discrepancy raises concerns about the consistency and accuracy of the search functionality provided by the RLiveObjectService, as it appears to be retrieving outdated data from the Redis cache.

**expected result:** [{"field1":"val",.......,"status":"processing"},{"field1":"val",.......,"status":"processing"},{"field1":"val",.......,"status":"processing"}]
**actual result  :** [{"field1":"val",.......,"status":"completed"},{"field1":"val",.......,"status":"completed"},{"field1":"val",.......,"status":"processing"}]

**RedissonClient Configuration**

 ```
@Bean(destroyMethod = "shutdown")
    public RedissonClient redisson() throws IOException {
       
        Config config = new Config();
        config.useReplicatedServers().addNodeAddress("rediscluster-node-endpoint");
        
        config.setMinCleanUpDelay(5); 
        config.setMaxCleanUpDelay(60); 
        config.setCleanUpKeysAmount(1000); 

        return Redisson.create(config);
    }
```

**MyCustomObject.class**

```
@Data
@REntity
public class MyCustomObject {
    private String field1;
    private String field2;
    private String field3;
    @RIndex
    private String field4;
    @RIndex
    private String status;
    @RId
    private String id;
}
```
**Code Snippet used to store and update** 

```
 RLiveObjectService service = redisson.getLiveObjectService();
 myCustomObject = service.merge(myCustomObject);
 service.asRMap(myCustomObject).expire(config.getTtl(), TimeUnit.DAYS);
```

**Redis Engine version : 7.1.0
redisson version : 3.29.0**

**Comment by mrniko** [comment]
> The search should be conducted based on the latest value of the status field, but it continues to retrieve objects with older status values, leading to inconsistency in the retrieved data.

you need to define `readMode = MASTER` setting in Redisson configuration.

**Comment by karthik2020mind** [comment]
Hi @mrniko Thanks for your reply, I believe default readmode would be a MASTER, anyway i tried with updating readMode to MASTER, but still issue exists.

**Comment by mrniko** [comment]
Please set `trace` logging level for `org.redisson` and share the log output

**Comment by karthik2020mind** [comment]
@mrniko Thanks..! I understand your request for trace logging level output for org.redisson. However, due to the sensitive nature of the information contained within the logs—particularly regarding connection host-related entries—I am unable to share the entire log file.
In lieu of sharing the complete logs, I would like to highlight specific observations we have made during our debugging process. 
```
 if (cond instanceof EQCondition) {
                EQCondition eqc = (EQCondition)cond;
                indexName = namingScheme.getIndexName(entityClass, eqc.getName());
                if (eqc.getValue() instanceof Number) {
                    values = new RedissonScoredSortedSet(namingScheme.getCodec(), this.commandExecutor, indexName, (RedissonClient)null);
                    eqNumericNames.put(values, (Number)eqc.getValue());
                } **else {
                    RSetMultimap<Object, Object> map = new RedissonSetMultimap(namingScheme.getCodec(), this.commandExecutor, indexName);
                    RSet<Object> values = map.get(eqc.getValue());
                    eqNames.add(((RedissonObject)values).getRawName());
                }**
            }

```
in **org.redisson.liveobject.LiveObjectSearch.class** Within this segment of else block(line 61), the instantiation of the 'map' object using the RedissonSetMultimap constructor indicates the retrieval of a set multimap indexed under a specific 'indexName'. Subsequently, the 'values' variable, representing the retrieved set, undergoes further processing.

However, it has come to my attention that the 'values' set contains entries encompassing older keys, some of which may have already expired. Additionally, the presence of keys associated with object values marked with a status of 'completed' is notable, particularly in scenarios where the queried 'eqc.getValue()' evaluates to 'processing'.

This discrepancy raises concerns regarding the integrity of the data retrieval process and suggests potential inconsistencies within the system's behavior.

I appreciate your understanding of this limitation and your willingness to collaborate in resolving this matter effectively. Please let me know if there are specific log excerpts or details you require, and I will do my utmost to provide them promptly.

**Comment by mrniko** [comment]
> However, it has come to my attention that the 'values' set contains entries encompassing older keys, some of which may have already expired

you need to define Redis `notify-keyspace-events` setting contains the letters `Kx`.
