### ISSUE TITLE
Why RedissonMap#containsKey() return true，but get() method return an null value?

### ISSUE THREAD

**Issue by happymlz** [redisson/redisson#5831]
Redisson : 3.24.2
Redis : deploy only one node, not cluster or sentinel.
My Code:
```java
RMap rMap = redissonClient.<String, Object>getMap("some-key");
// other codes here 
Set<String> set = new HashSet<>();
if (rMap.containsKey("my-key")) {
    set = (Set<String>) rMap.get("my-key");
}
set.add("my-value");
```
When I run code, NPE Error happened at "set.add("my-value")".  Why?

**Comment by mrniko** [comment]
it can be deleted by that moment.

**Comment by happymlz** [comment]
> it can be deleted by that moment.

But I never call remove method.

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` package and share the output?

**Comment by happymlz** [comment]
> Can you set `trace` logging level for `org.redisson` package and share the output?

OK. I will try again as you said.  thank you!
