### ISSUE TITLE
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts:{IPS}

### ISSUE THREAD

**Issue by miteshjain24** [redisson/redisson#5832]
Intermittent issue
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts:{IPS}

**Expected behavior** : If any ips of slave change it should adjust it.

**Actual behavior** Intermittently getting issue : Intermittent issue
org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries.  Disconnected hosts:{IPS}

**Steps to reproduce or test case** 

**Redis version** 6.x

**Redisson version** 2.1.5.2

**Redisson configuration**

**Comment by mrniko** [comment]
Can you upgrade to 3.23.2 version?

**Comment by miteshjain24** [comment]
Will version 3.21.3 works? Does version 3.21.3  has resolution of this issue?

**Comment by miteshjain24** [comment]
[mrniko](https://github.com/mrniko)

Can you please get chance to reply on my above comment of version?

**Comment by mrniko** [comment]
@miteshjain24 

3.23.3 version should resolve the issue.
