### ISSUE TITLE
为啥maven依赖引入不了，有没有什么好的解决办法？

### ISSUE THREAD

**Issue by Wwh-SoEximious** [redisson/redisson#5839]
Why can't maven dependencies be introduced, is there any good solution?

![111](https://github.com/redisson/redisson/assets/131334531/32d167a4-3d6c-4708-91c5-97e33d2f71a7)

**Comment by Wwh-SoEximious** [comment]
已经解决！settings文件里加了个镜像

**Comment by mrniko** [comment]
It's not a pom, but jar file
