### ISSUE TITLE
Which version is the current stable version?

### ISSUE THREAD

**Issue by sunnan211** [redisson/redisson#5849]
Which stable version of Redisson is currently recommended for production use, or which version has been verified in online production environments, and what is considered the relatively optimal version?

**Comment by mrniko** [comment]
the latest one.

**Comment by sunnan211** [comment]
I have another question to consult. The current version of Redis we are using in our company is 6.2.6, while the latest version available online is 7.4.2. If I do not change the version of Redis but only upgrade Redisson, will the functionalities mentioned in the fix log be effective? Or is there a need for the versions of Redisson and Redis to be consistent with each other in some way?

**Comment by mrniko** [comment]
> If I do not change the version of Redis but only upgrade Redisson, will the functionalities mentioned in the fix log be effective? 

yes
