### ISSUE TITLE
Intermittent + org.redisson.client.RedisConnectionException: SlaveConnectionPool no available Redis entries. Disconnected hosts:{ip1,ip2}

### ISSUE THREAD

**Issue by JohnDoeTech1121** [redisson/redisson#5851]
**Expected behavior**

**Actual behavior** 

**Steps to reproduce or test case**

**Redis version** 6.x

**Redisson version** 2.14.1

**Redisson configuration**

clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "redis addresss"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
threads: 16
nettyThreads: 32
#codec: !<org.redisson.codec.Kryo5Codec> {}
transportMode: "NIO"

Can i use Redisson 3.21.3 ? as my other services are using this version and i dont see this issue there. Do we have resolution of this issue in Redisson 3.21.3?

**Comment by mrniko** [comment]
I would recommend to upgrade to 3.23.2 or later
