### ISSUE TITLE
Intermittent + Unable to send command! Node source: NodeSource [slot=15623, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1179865693 

### ISSUE THREAD

**Issue by miteshjain24** [redisson/redisson#5852]
**Expected behavior**

**Actual behavior**

**Steps to reproduce or test case**

**Redis version** 6.X

**Redisson version** 2.15.2

**Redisson configuration**

clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "Redis address"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
threads: 16
nettyThreads: 32
#codec: !<org.redisson.codec.Kryo5Codec> {}
transportMode: "NIO"

**Comment by mrniko** [comment]
Sorry, 2.15.2 version isn't supported. Unable to reproduce it with the latest version
