### ISSUE TITLE
RedissonLiveObjectService find sometimes return incorrect result

### ISSUE THREAD

**Issue by Hlorry** [redisson/redisson#5861]
redisson version :3.17.7 or 3.25.2
redis version: 

List<UserForFindDTO> user =
                new ArrayList<>(
                        liveObjectService.find(
                                UserForFindDTO.class,
                                Conditions.and(
                                        Conditions.eq(PBX_ID_FIELD_NAME, pbxId),
                                        Conditions.eq(ACCOUNT_ID_FIELD_NAME, accountId),
                                        Conditions.eq(fieldName, value))));
        if (user.isEmpty()) {
            return null;
        }
logger.info("findUser users={}", user);

I use userid to find result ( the userid is unique ), but sometimes it return result  that is the three fields's SUNION not SINTER, but the debug log is 
<img width="1679" alt="企业微信截图_81d8d2d5-b3a9-44b5-94af-08ed50fc85bd" src="https://github.com/redisson/redisson/assets/10164567/cf47f140-f760-45d8-b412-041ed327f9ca">
<img width="1679" alt="企业微信截图_cd1ce431-76bb-4f60-a930-d040111106ab" src="https://github.com/redisson/redisson/assets/10164567/4856b46b-26fb-481f-93f7-e7fafeab8d03">
SINTER.  Then i  use redis-cli  to execute the log sinter command but the result is correct.

**Comment by mrniko** [comment]
Can you share the code to reproduce it?

**Comment by Hlorry** [comment]
> Can you share the code to reproduce it?

I use same data in my test environment，but it works right;

<img width="849" alt="image" src="https://github.com/redisson/redisson/assets/10164567/1e565208-2983-44d6-a80b-4230ee8cb7c8">

**Comment by mrniko** [comment]
can you reproduce it with readMode = MASTER ?

**Comment by Hlorry** [comment]
> can you reproduce it with readMode = MASTER ?

I use cloud redis，the default configuration is read from master.

**Comment by Hlorry** [comment]
thank you mrniko，the bug is from the cloud redis.
