### ISSUE TITLE
Readmode setting invalid

### ISSUE THREAD

**Issue by hongkong9771** [redisson/redisson#5871]
**Expected behavior**

**Actual behavior**
I set the readmode to slave, and get operations such as getbit and hgetall are only performed on the slave node, but srandmember is only performed on the master node. The Redis version is redisson spring root starter: 3.12.5

**Steps to reproduce or test case**

**Redis version**
5.0.5  
sentinel mode

**Redisson version**
redisson-spring-boot-starter：3.12.5

**Redisson configuration**
config.useSentinelServers()
        .addSentinelAddress(sentinelsAddresses.toArray(new String[0]))
        .setMasterName("mymaster")
        .setDatabase(1)
        .setPassword("123456")
        .setReadMode(ReadMode.SLAVE)

**Comment by mrniko** [comment]
Fixed. Thanks for report
