### ISSUE TITLE
Missing entries in reflect-config.json

### ISSUE THREAD

**Issue by Ivan1pl** [redisson/redisson#5874]
Some entries are missing in reflect-config.json, which causes the application to crash when running as a native image (native Spring Boot application). Encountered with `org.redisson.RedissonLock`, other entries may also be missing.

**Expected behavior**
Invoking `org.redisson.api.RLockReactive.isLocked()` returns correct value.

**Actual behavior**
Invoking `org.redisson.api.RLockReactive.isLocked()` causes `java.lang.NoSuchMethodException: org.redisson.RedissonLock.isLocked()`

**Workaround**
As a workaround, adding the following entry to `reflect-config.json` resolves the issue:
```json
  {
    "name": "org.redisson.RedissonLock",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "allPublicClasses": true
  }
```

**Steps to reproduce or test case**
I am not able to provide the full code, but the following code snippet causes the issue:
```java
    public Mono<Boolean> doSth(/* ... */) {
        // ...
        RLockReactive lock = redissonReactiveClient.getLock(/* ... */);
        return lock.isLocked();
    }
```
Resulting stacktrace points to the line where `return lock.isLocked();` is used. Part of the stacktrace above this entry:
```
Caused by: java.lang.NoSuchMethodException: org.redisson.RedissonLock.isLocked()
	at java.base@21.0.2/java.lang.Class.checkMethod(DynamicHub.java:1075)
	at java.base@21.0.2/java.lang.Class.getMethod(DynamicHub.java:1060)
	at org.redisson.misc.ProxyBuilder.getMethod(ProxyBuilder.java:112)
	at org.redisson.misc.ProxyBuilder.access$000(ProxyBuilder.java:37)
	at org.redisson.misc.ProxyBuilder$1.invoke(ProxyBuilder.java:76)
	at jdk.proxy4/jdk.proxy4.$Proxy66.isLocked(Unknown Source)
```

**Redis version**
3.0.7

**Redisson version**
3.29.0

**Redisson configuration**
Just host and port (via `redisson-spring-boot-starter`)
```yaml
spring:
  data:
    redis:
      host: redis
      port: 6379
```

**Comment by mrniko** [comment]
Strange issue. I though allDeclaredMethods include allPublicMethods

Fixed. Thanks for report
