### ISSUE TITLE
Here’s the issue we encountered with `redisson-3.11.5.jar`

### ISSUE THREAD

**Issue by githuailoveyou** [redisson/redisson#5882]
Our service connects to the SLB (Server Load Balancer) using a domain name, which maps through a port to the Redis server nodes.

For example:
- Service IP --> Domain A:2700 --> EIP (10.75.10.20):27000 --> Redis server: 10.65.10.30:27000

The Redis sentinel nodes are:
- 10.65.10.30:27000
- 10.65.10.40:27000
- 10.65.10.50:27000

Redisson performs two types of checks: `scheduleSentinelDNSCheck` and `scheduleChangeCheck`. These checks result in the following situations:

- `redis://10.75.10.20:27000 added`
- `redis://10.75.10.20:27000 was down`
- `redis://10.65.10.30:27000 added`
- `redis://10.65.10.30:27000 was down`

This causes a polling effect, even though they ultimately point to the correct sentinel nodes.

**Comment by githuailoveyou** [comment]
scheduleSentinelDNSCheck will add 10.75.10.20 to the sentinels.
scheduleChangeCheck (when it uses 10.65.10.30:27000 to connect and retrieve other sentinels: redis://10.65.10.30:27000, redis://10.75.10.40:27000 and add 10.65.10.30:27000 to a newUris list to form a new set of three sentinels) will remove 10.75.10.20 from the sentinels.

**Comment by mrniko** [comment]
because 10.65.10.30 doesn't have 10.75.10.20 in sentinel list. You can verify this by setting `trace` logging level for `org.redisson` package.

**Comment by githuailoveyou** [comment]
Yes, it seems that Redisson doesn't fully support this SLB-based connection method, right? Although it doesn't directly impact business functionality, it does lead to continuous adjustments in the sentinels variable, otherwise we'll keep seeing "down added" occurrences. Now, the issue we're facing is that the service logs continue to record these changes persistently. How should I address this? Should we consider abandoning the use of SLB?

**Comment by mrniko** [comment]
Did you try `natMapper` setting ? to resolve EIP to a real Redis node IP

**Comment by githuailoveyou** [comment]
> 这是否意味着使用 SLB 时同一个 Redis 节点有两个 IP？一个是在sentinel配置中定义的，另一个是用于SLB的？

"Yes, the reason we use SLB (Server Load Balancer) is because we have multiple Redis instances deployed on the same machine, each with 2 IP addresses.

All services are connected via domain names. Most of the Redis instances are in master-slave mode to ensure failover. Therefore, we adopt the SLB approach. We dynamically modify the server addresses under the SLB port after detecting master-slave switches."

**Comment by githuailoveyou** [comment]
> Does it mean that with SLB the same Redis node has two IPs ? one is defined in sentinel configs and another is used for SLB?

"Yes, the reason we use SLB (Server Load Balancer) is because we have multiple Redis instances deployed on the same machine, each with 2 IP addresses.

All services are connected via domain names. Most of the Redis instances are in master-slave mode to ensure failover. Therefore, we adopt the SLB approach. We dynamically modify the server addresses under the SLB port after detecting master-slave switches."

**Comment by githuailoveyou** [comment]
> 你尝试`natMapper`设置了吗？将EIP解析为真实的Redis节点IP



> 你尝试`natMapper`设置了吗？将EIP解析为真实的Redis节点IP

**Comment by githuailoveyou** [comment]
> Did you try `natMapper` setting ? to resolve EIP to a real Redis node IP

Doesn't seem to make any sense

**Comment by mrniko** [comment]
Unfortunately, it's a specific case. You can define natMapper like below.

```java
                .setNatMapper(new NatMapper() {
                    @Override
                    public RedisURI map(RedisURI uri) {
                        if (uri.getHost().equals("10.75.10.20")) {
                            return ew RedisURI(uri.getScheme(), "10.65.10.20", uri.getPort());
                        }
                        ...
                    }
                })
```

**Comment by githuailoveyou** [comment]
> 不幸的是，这是一个具体案例。您可以像下面一样定义 natMapper。
> 
> ```java
>                 .setNatMapper(new NatMapper() {
>                     @Override
>                     public RedisURI map(RedisURI uri) {
>                         if (uri.getHost().equals("10.75.10.20")) {
>                             return ew RedisURI(uri.getScheme(), "10.65.10.20", uri.getPort());
>                         }
>                         ...
>                     }
>                 })
> ```

thank you

**Comment by mrniko** [comment]
Another solution is to use `org.redisson.api.HostNatMapper` implementation.

```java
Map<String, String> map = new HashMap<>();
map.put("10.75.10.20", "10.65.10.20");

config.setNatMapper(new HostNatMapper(map))
```
