### ISSUE TITLE
AWS RedisCache Failover requests

### ISSUE THREAD

**Issue by musicallyvk** [redisson/redisson#5890]
Hi Everyone, Hope everyone is doing great!
so i have a 3 replica and 1 primary on aws elasticache redisCache using version 4.0,  with the redis config file on the application level which has a load balancer with round robbin and using replicatedServersConfig. and many other things like retry , failedSlaveCheckInterval,timeout, readMode , subscriptionMode and many things. 

if you need more details on config then - 

des.redisson.config={"replicatedServersConfig":{"idleConnectionTimeout":10000,"connectTimeout":10000,"timeout":30000,"retryAttempts":3,"retryInterval":1500,"failedSlaveReconnectionInterval":3000,"failedSlaveCheckInterval":60000,"password":"*****","subscriptionsPerConnection":5,"clientName":"myClientName","loadBalancer":{"class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"},"subscriptionConnectionMinimumIdleSize":1,"subscriptionConnectionPoolSize":50,"slaveConnectionMinimumIdleSize":24,"slaveConnectionPoolSize":64,"masterConnectionMinimumIdleSize":24,"masterConnectionPoolSize":64,"readMode":"SLAVE","subscriptionMode":"SLAVE","nodeAddresses":["rediss:\/\/Node1,Node2,Node3,Node4"],"scanInterval":1000},"threads":16,"nettyThreads":32,"codec":{"class":"org.redisson.codec.LZ4Codec"},"transportMode":"NIO"}

now the thing is if a failover happens then some requests are still being routed to that failed node,  how to get it resolved, anyone please help me. i am stuck with this for months.
Thanks Already !

**Comment by musicallyvk** [comment]
Hi, Thanks For replying,

on application, the pom.xml says  
            <version>3.13.2</version>


and on aws - the reds cache is using  Engine version
4.0.10

**Comment by mrniko** [comment]
Can you share Redisson logs?

**Comment by musicallyvk** [comment]
this is the exception i see on splunk logs, if not this then 
what exactly you need 


2024-05-19 16:23:01.227 [redisson-netty-2-15] [ERROR] intuit_tid= correlationId= http_request_path= http_query_string= intuit_offeringid= intuit_docid= appid= authid= vendor= app_class=org.redisson.connection.ReplicatedConnectionManager app_method=: - org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'myNodeName-004.myNodeName.dnqsqq.usw2.cache.amazonaws.com' [A(1)] and search domain query for configured domains failed as well: [fdp-docmgmt-comprehensionprovidersvc-usw2-qal.svc.cluster.local, svc.cluster.local, cluster.local]
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'desredisecachee2ea-004.desredisecachee2ea.dnqsqq.usw2.cache.amazonaws.com' [A(1)] and search domain query for configured domains failed as well: [fdp-docmgmt-comprehensionprovidersvc-usw2-qal.svc.cluster.local, svc.cluster.local, cluster.local]

**Comment by mrniko** [comment]
https://github.com/redisson/redisson/issues/5726#issuecomment-2019515521
