### ISSUE TITLE
Redisson getRateLimiter use expireIfSet  get Error

### ISSUE THREAD

**Issue by DoNotBugPlz** [redisson/redisson#5891]
**Expected behavior**

**Actual behavior**
ERR Error running script (call to f_3fd750e0b43af99dbd223e5523718f18cded3664): @user_script:1: @user_script: 1: Wrong number of args calling Redis command From Lua script . channel: [id: 0xcc3db189, L:/32.1.4.125:49341 - R:32.1.14.148/32.1.14.148:7480] command: (EVAL), promise: java.util.concurrent.CompletableFuture@41570a81[Not completed, 1 dependents], params: [local result = 0;for j = 1, #KEYS, 1 do local expireSet; if ARGV[2] ~= '' then expireSet = redis.call('pexpire', KEYS[j], ARGV[1], ARGV[2]); else expireSet = redis.call('pexpire', KEYS[j], ARGV[1]); end; if expireSet == 1 then result = expireSet;end; end; return result; , 5, LIMIT_PREFIX_KEY:1784406473620062209, {LIMIT_PREFIX_KEY:1784406473620062209}:value, {LIMIT_PREFIX_KEY:1784406473620062209}:value:96c32869-f959-4c7f-bc4e-052dbebe477f, {LIMIT_PREFIX_KEY:1784406473620062209}:permits, {LIMIT_PREFIX_KEY:1784406473620062209}:permits:96c32869-f959-4c7f-bc4e-052dbebe477f, 300000, NX]
**Steps to reproduce or test case**

**Redis version**
6.0
**Redisson version**
3.29.0
**Redisson configuration**
defualt

**Comment by arenick001** [comment]
failed with Redis 7.0+as also
**redis_version**:7.2.4
**redisson version**: 3.29.0
 ----------------------------------
by the way,when I use redisson-micronaut-40(3.30.0),it can't find a Config.class bean. @mrniko

**Comment by mrniko** [comment]
> redis.call('json.set', KEYS[1], '$', ARGV[1]);

make sure that `json.set` is supported by Redis vendor

**Comment by mrniko** [comment]
@arenick001

> when I use redisson-micronaut-40(3.30.0),it can't find a Config.class

Is there any code sample to reproduce it?

**Comment by arenick001** [comment]
> @arenick001
> 
> > when I use redisson-micronaut-40(3.30.0),it can't find a Config.class
> 
> Is there any code sample to reproduce it?

I use docker image `redis/redis-stack-server:latest`. the code is following:
```
redissonClient.getJsonBucket(key, new JacksonCodec<>(SimpleObject.class))
  .set(obj, Duration.of(2,TimeUnit.MINUTES.toChronoUnit()))
```
actually I am trying to use [RediSearch](https://github.com/redisson/redisson/wiki/9.-distributed-services/#96-redisearch-service) and copy the code from the sample @mrniko

**Comment by arenick001** [comment]
> Is there any code sample to reproduce it?

```
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson-micronaut-40</artifactId>
    <version>3.29.0</version>
</dependency>
 ```
just replace 3.29.0 with 3.30.0. @mrniko

**Comment by mrniko** [comment]
This is the result of incorrect configuration. Try to add `@Requires(beans = Config.class)`

**Comment by arenick001** [comment]
> This is the result of incorrect configuration. Try to add `@Requires(beans = Config.class)`

thx!
 
> make sure that `json.set` is supported by Redis vendor

finally I found I need a RedisJSON module in  Redis. haha~
