### ISSUE TITLE
RLocalCachedMap local cache use?

### ISSUE THREAD

**Issue by KYV365** [redisson/redisson#5893]
if the data change on redis server，can we get the new data in local cache? or the server will info client the change?

**Comment by KYV365** [comment]
> pubsub message should be send after change if data updated without Redisson client.

but the new data can not get by method cachedValues()

**Comment by mrniko** [comment]
you need to set `syncStrategy = UPDATE` local cache setting

**Comment by KYV365** [comment]
> you need to set `syncStrategy = UPDATE` local cache setting

thanks for your reply
