### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by KYV365** [redisson/redisson#5895]
**Actual behavior**
[NettyClientWorkerThread_2] ERROR [io.netty.util.ResourceLeakDetector] [TID: N/A] - [dbu-mod-fms] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
	org.redisson.codec.JsonJacksonCodec$1.encode(JsonJacksonCodec.java:81)
	org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:654)
	org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:344)
	org.redisson.RedissonLocalCachedMap.broadcastLocalCacheStore(RedissonLocalCachedMap.java:121)
	org.redisson.RedissonLocalCachedMap.putAllOperationAsync(RedissonLocalCachedMap.java:667)
	org.redisson.RedissonMap.putAllAsync(RedissonMap.java:713)
	org.redisson.RedissonMap.putAll(RedissonMap.java:666)

**Steps to reproduce or test case**
scheduled call RedissonLocalCachedMap putAll() or call fastRemove() and then call putAll()

**Redisson version**
3.18.0

**Redisson configuration**
options = LocalCachedMapOptions.defaults()
                .storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE)
                .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
                .cacheSize(0)
                .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.NONE)
                .syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE);

Thanks for your reply!

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5086
