### ISSUE TITLE
RRateLimiter.trySetRate does not reset all rate limiter state despite documentation

### ISSUE THREAD

**Issue by bbbert** [redisson/redisson#5900]
**Expected behavior**
`RRateLimiter.trySetRate`'s [docstring](https://github.com/redisson/redisson/blob/7d30272b393c2d5354f3b5d30e9d56de218d1e85/redisson/src/main/java/org/redisson/api/RRateLimiter.java#L29) claims that it:

> Initializes RateLimiter's state and stores config to Redis server.

and that it will

> @return {@code true} if rate was set and {@code false} otherwise

Hence, one would expect that whether or not the rate config was updated, the rate limiter state would be reset.

**Actual behavior**
However, `RedissonRateLimiter.trySetRate` [does not delete](https://github.com/redisson/redisson/blob/7d30272b393c2d5354f3b5d30e9d56de218d1e85/redisson/src/main/java/org/redisson/RedissonRateLimiter.java#L241) the value and permit keys (`{xxx}:permits` and `{xxx}:value`), [unlike](https://github.com/redisson/redisson/blob/7d30272b393c2d5354f3b5d30e9d56de218d1e85/redisson/src/main/java/org/redisson/RedissonRateLimiter.java#L255) `RedissonRateLimiter.setRate`. Hence, it is possible for the value and permit state to remain un-reinitialized and invalid even after calling `trySetRate`. This causes issues when, for example, upgrading redisson to a version where there have been changes to the permits serialization format.

**Steps to reproduce or test case**

Code snippet:
```
RRateLimiter rateLimiter = redisson.getRateLimiter(ofRateLimiter);
if (!rateLimiter.trySetRate(RateType.OVERALL, 10L, 1L, RateIntervalUnit.HOURS)) {
  RateLimiterConfig currentConfig = rateLimiter.getConfig();
  boolean rateLimiterConfigLooksFine = currentConfig != null
    && currentConfig.getRateType() == RateType.OVERALL
    && currentConfig.getRate().equals(10L)
    && currentConfig.getRateInterval().equals(RateIntervalUnit.HOURS.toMillis(1L));
  
  if (!rateLimiterConfigLooksFine) {
    rateLimiter.setRate(RateType.OVERALL, 10L, 1L, RateIntervalUnit.HOURS);
  }
}

// In 3.16.3, adds permit values in the struct format `fI`.
// In 3.30.0, expects permit values in the struct format `Bc0I`, which fails and throws RedisException: bad argument #2 to 'unpack'.
rateLimiter.acquire();
```

1. Install a `redisson` version prior to a rate limiter internal state format change, e.g. `3.16.3` which was before [this change](https://github.com/redisson/redisson/commit/d30a63686286650379c9250292eaf5d5495cbb7f#diff-93205df1bb98d26abf7cc7731cc328101591f8d7739ed342553e4c032ab68b68).
2. Run the snippet, then keep Redis running.
3. Upgrade the `redisson` version to a version after that internal state format change, e.g. `3.30.0`.
4. Run the snippet without having restarted Redis.

**Redis version**

6.x

**Redisson version**

Upgrading from `3.16.3` to `3.30.0`.

**Redisson configuration**

N/A

**Thoughts**

Both of these options seem reasonable here, not sure if there's a better way:
- Either update the documentation for `trySetRate` to call out that the state could be invalid if it returns false (if it returns true the rate limit is not present and is created fresh).
- Or update `trySetRate` to also delete the permits and values keys just like `setRate`.

**Comment by hfxu** [comment]
I have same issue with rate limiter by upgrade redisson from `3.16.1` to `3.30.0`.
There does not seem to be a straightforward solution. So I tried this by catch the` RedisException` and then call `setRate` to reset the rate limiter, although the previous rate limiter data would be lossed.

```java
public boolean tryGetToken(String redisKey, int rateIntervalSeconds, int rate) {
    RRateLimiter rateLimiter = redissonClient.getRateLimiter(redisKey);

    rateLimiter.trySetRate(RateType.OVERALL, rate, rateIntervalSeconds, RateIntervalUnit.SECONDS);


    try {
        return rateLimiter.tryAcquire(1);
    } catch (RedisException ex) {
        // 1. check the exception is bad argument?
        // reference: https://github.com/redisson/redisson/issues/5900
        if (ex.getMessage().startsWith("ERR user_script:1: bad argument #2 to 'unpack' (data string too short)")) {
            log.info("Rate limiter {} initialized by old version redisson, as the exception is: {}", redisKey, ex.getMessage());
            rateLimiter.setRate(RateType.OVERALL, rate, rateIntervalSeconds, RateIntervalUnit.SECONDS);

            // 2. call acquire again.
            return rateLimiter.tryAcquire(1);
        } else {
            throw ex;
        }
    }
}
```

**Comment by mrniko** [comment]
> the rate limiter state would be reset.

state can be cleared only if rate was updated. I'll update javadocs. In your case setRate usage is the only right solution.
