### ISSUE TITLE
Redisson with redis-cluster worse performance than redis standalone

### ISSUE THREAD

**Issue by stefanofalangone** [redisson/redisson#5917]
At my company, we have an installation of **Redis standalone** (no replicas) which we are considering as a shared point for a _microservices architecture_ running on a _Kubernetes Cluster_.
We wish to achieve scalability, and to do so, we thought it was appropriate to use **Redis-Cluster** instead, considering that we are dealing with hundreds of pods in r/w.

After the installation of redis-cluster, we run multiple tests, but **we had worse performances** in comparison of the standalone one.

Currently, we are tracking multiple insertion times and taking them as statistics. 
Our pods are Java microservices using Redisson as the preferred client pointing to a Kubernetes Service.
The way we are building the connection is this:
`config.useClusterServers().addNodeAddress("redis://redis-cluster.redis-cluster.svc.cluster.local:6379").setPassword("myPwd").setRetryAttempts(10);`
where we point at a service that redirects the connections to {redis-cluster-0, ... , redis-cluster-5}. Is this approach correct from Redisson or using a service instead of specifing the addresses of redis-cluster-0, ... redis-cluster-5 causes a performance decrease?
Is there some configuration we could change to increase performance in Redisson? 

Thank you in advance for you help and time.

**Comment by WPCode** [comment]
Following. We encountered the exact same performance issue here as well. We have 3000 hashes which are shared across 5 redis nodes deployed in k8s statefulset. Writing the same data took double the time (4min) it took for standalone single redis server (2min). We are not sure whether it's due to redisson library or something else. Any suggestions?

**Comment by mrniko** [comment]
it might be caused by Redis cluster redirects. Can you set `trace` logging level for `org.redisson` package and share output?

**Comment by stefanofalangone** [comment]
I can confirm it was most probably due to redirects, as stated by @mrniko. 
@WPCode I suggest you try putting the addresses of the nodes deployed rather than that of the service and see if it solves.
