### ISSUE TITLE
ClusterConnectionManager seems to lose track of the cluster

### ISSUE THREAD

**Issue by sclasen** [redisson/redisson#5931]
### Redis version

6.x

### Redisson version

3.30.0

### Redisson configuration

```
        Config config = new Config();
        config.setCheckLockSyncedSlaves(false);
        config.useClusterServers()
                .addNodeAddress(String.format("redis://%s:%d", props.host(), props.port()))
                .setScanInterval(2000)
                .setReadMode(ReadMode.MASTER) 
                .setSubscriptionMode(SubscriptionMode.MASTER);
```

### What is the Expected behavior?

   RedisCluster redisCluster = ((RedisCluster) redissonClient.getRedisNodes(redisNodes));
   redisCluster.getMasters() reports the same master nodes as running `CLUSTER NODES`
   redisCluster.getSlaves() reports the same standby nodes as running `CLUSTER NODES`

### What is the Actual behavior?

As the cluster continues to change its topology, at some point the number of masters falls our of sync with `CLUSTER NODES` and at some point the redissonClient gets wedged and thinks the master(s) its connected to does not have slots assigned. Running `CLUSTER NODES` from the same host as redisson shows a healthy cluster with slot ranges assigned.

retarting the jvm running redisson repairs everything since its seems to boostrap initially from the data in `CLUSTER NODES` but somehow diverges over time.

all the master and standby nodes report roughly the same number of connections, so some part of the topolgy change is occurring correctly.

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` and share log output?

**Comment by mrniko** [comment]
Please try attached build.

[redisson-3.31.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/15543304/redisson-3.31.1-SNAPSHOT.jar.zip)

**Comment by sclasen** [comment]
we'll try and get those trace logs.  is that snapshot publised in maven central or in redisson's maven repo? it will be difficult to directly use the linked artifact.

Thanks!

**Comment by sclasen** [comment]
also a bit more context, there are multiple jvms with redisson clients connected to the cluster and we typically see only one of them 'go bad' at a time so seems race-conditiony/non deterministic

**Comment by mrniko** [comment]
Fixed. Thanks for report
