### ISSUE TITLE
Please provide the support for quarkus redis annotations while integrating with redisson-quarkus.

### ISSUE THREAD

**Issue by nitinty** [redisson/redisson#5943]
Hello!

We are trying to integrate redisson-quarkus in our application, But It doesn't support quarkus redis annotations (@CacheResult, @CacheInvalidate, @CacheInvalidateAll, @Cachekey) as of now.

Would you consider providing the support for redis annotations or recommend an approach to achieve it ?

Thank you in advance!

**Comment by nitinty** [comment]
@mrniko

**Comment by mrniko** [comment]
Thanks for the suggested feature. Done.

https://github.com/redisson/redisson/blob/master/redisson-quarkus/README.md#cache-usage
