### ISSUE TITLE
Execute lua script on all nodes without providing key

### ISSUE THREAD

**Issue by WPCode** [redisson/redisson#5946]
**Is your feature request related to a problem? Please describe.**

I have a use case that all hashes are split across redis nodes in cluster, the hashes may contain common fields. I want to get all the keys of hashes which contain a given field. For example:

node1: hash1 <1, "a">
node2: hash2 <1, "b">
node3: hash3 <2, "c">

Given 1, it will return key name of hash1 and hash2.

**Describe the solution you'd like**

I want to use Lua script to do that. But lua script requires providing a key, which I don't know in advance unless fetching all keys from redis first. If no key provided, it will send lua script to slot 0. I want to send the lua script to all nodes and then aggregate the result.

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Can be implemented with a new `RScript.eval(Mode mode, String luaScript, ReturnType returnType, Object... values)` method.

**Comment by mrniko** [comment]
Done
