### ISSUE TITLE
从3.17.0升级到3.28.0后，所有缓存的对象序列化都失败了

### ISSUE THREAD

**Issue by qiuyueovo** [redisson/redisson#5967]
springboot版本从 2.7.x 升级到 3.2.x 。
redission版本从：3.17.0 升级到 3.28.0 。
jdk从 8 升级到 21
其他未变。
缓存序列化对象都是失效了。取值出来是异常的。

**Comment by qiuyueovo** [comment]
3.17.0 的序列化方法为：oldConf.setCodec(new MarshallingCodec());
3.28.0 的序列化方法为： oldConf.setCodec(new Kryo5Codec());

**Comment by qiuyueovo** [comment]
目前我的处理方法是：从 3.17版本中复制出 MarshallingCodec。然后引用这个方法理论上来讲是可以的。我只测试了一个类

**Comment by mrniko** [comment]
all you need to do is just to specify MarshallingCodec as a codec explicitly.

**Comment by qiuyueovo** [comment]
Yes, that's how I handle it now. Before, all settings were default, and no serialization method was set. Through other people's issue comments, I found a similar problem. I looked at the source code and now it has been successfully solved. Thank you

**Comment by 1em0n9527** [comment]
> Yes, that's how I handle it now. Before, all settings were default, and no serialization method was set. Through other people's issue comments, I found a similar problem. I looked at the source code and now it has been successfully solved. Thank you

请问具体方法是什么样的， 是 MarshallingCodec 类以及相关的 其他依赖导入进来吗？

**Comment by qiuyueovo** [comment]
> > Yes, that's how I handle it now. Before, all settings were default, and no serialization method was set. Through other people's issue comments, I found a similar problem. I looked at the source code and now it has been successfully solved. Thank you
> 
> 请问具体方法是什么样的， 是 MarshallingCodec 类以及相关的 其他依赖导入进来吗？

不是，直接 c 过来就好了，然后改一下 redis  存值的设置。

**Comment by 1em0n9527** [comment]
this is my sollution:

MarshallingCodec codec = new MarshallingCodec();
config.setCodec(codec).useSingleServer()

with below maven dependency
```
        <dependency>
            <groupId>org.jboss.marshalling</groupId>
            <artifactId>jboss-marshalling</artifactId>
            <version>2.0.11.Final</version>
        </dependency>

        <dependency>
            <groupId>org.jboss.marshalling</groupId>
            <artifactId>jboss-marshalling-river</artifactId>
            <version>2.0.11.Final</version>
        </dependency>
```

springboot config did not test, i will check it later

**Comment by 1em0n9527** [comment]
redisson springboot starter auto config  is not suit for codec (because if read redisson config then ignore redis config) 

here is my sollution:

use new RedissonAutoConfigurationCustomizer with 
```
    @Bean
    public RedissonAutoConfigurationCustomizer redissonAutoConfigurationCustomizer() {
        return config -> {
            config.setCodec(new MarshallingCodec());
        };
    }
```
