### ISSUE TITLE
Encoded user/password in URL should be accepted

### ISSUE THREAD

**Issue by keithcys1** [redisson/redisson#5983]
### Redis version

7.2.5-alpine

### Redisson version

3.21.3

### Redisson configuration

```
singleServerConfig:
    address: "redis://default:myP%40ss@redis:6379"
```

### What is the Expected behavior?

encoded URL should be accepted

### What is the Actual behavior?

it use encoded password as actual password

### Additional information

https://github.com/redisson/redisson/blob/15a14c8e657ff806f7119fd9dc1153c982c92c2d/redisson/src/main/java/org/redisson/misc/RedisURI.java#L59-L67

**Comment by mrniko** [comment]
Which encoding did you apply to the password?

**Comment by mrniko** [comment]
Fixed. Thanks for report
