### ISSUE TITLE
Unable to find master entry for {}. Multiple IP bindings for single hostname supported only in Redisson PRO!

### ISSUE THREAD

**Issue by jejass** [redisson/redisson#5997]
Hello there,

I am using Redisson 3.11.4 to connect Azure Redis with private endpoint. I found the error as title was reported frequently. From network trace, I found 2 IPs were returned. one is public IP and the other one is private IP. The private IP should be correct one. The public IP was returned 1-2 times. but the error was returned more frequent than the public IP returned times.

I accessed the Redis instance with url. The url has CNAME in Azure. for private IP, the CNAME structure is like below.

Redis endpoint 
       private Redis endpoint -> CNAME
                private IP ->   A Record

for public IP, the CNAME structure is like below.

Redis endpoint
      private Redis endpoint -> CNAME
              **Redis host -> CNAME**
                  public IP -> A Record

I can see multiple DNS query for **Redis host**  individually. from Redisson code, I understand it is using Netty to resolve endpoint. It will use CNAME cache to resolve the IP. That may explain why it returned public IP frequently.
![image](https://github.com/redisson/redisson/assets/32087564/6ba5c444-33c0-4fab-813a-b3273c590a00)

Ask:
Could anyone help to check if that is the cause of Redisson resolve endpoint with the **'Redis host'**? is this enhanced in the latest version?

thank you very much.

**Comment by mrniko** [comment]
This message was remove in the latest version
