### ISSUE TITLE
StacklessClosedChannelException happend after redis instance switching.

### ISSUE THREAD

**Issue by feilix** [redisson/redisson#6023]
### Redis version

5.0.14

### Redisson version

3.32.0

### Redisson configuration

Everything is set to default, except for using single server configuration and setting the DNS monitoring interval to 2000.
![图片](https://github.com/redisson/redisson/assets/55008613/33c9e06c-e84c-4845-bad0-6a05e0f2e33b)

### What is the Expected behavior?

There is a Redis instance switching operation in our application, and an unexpected error occurred. Here is what happened：
1. Start the application and subscribe to topic A.
2. Update the DNS record: change the original Redis host from IP_C to IP_D.
3. Wait for Redisson to detect the DNS change and establish new connections.
4. Subscribe to topic B.
5. In my opinion, Redisson should correctly subscribe to both topic A and topic B in the new Redis instance, or at least successfully subscribe to topic B. Is that right? If not, please correct me.

### What is the Actual behavior?

1. Start the application and subscribe to topic A.
2. Update the DNS record: change the original Redis host from IP_C to IP_D.
3. Wait for Redisson to detect the DNS change and establish new connections,  as indicated in the logs..
![图片](https://github.com/redisson/redisson/assets/55008613/d68e3c40-814e-421b-8b6f-5696de07c2e9)
4. Subscribe to topic B.
5. An error occurred: io.netty.channel.StacklessClosedChannelException
![error](https://github.com/redisson/redisson/assets/55008613/eb8b0c88-66a0-4f6d-953d-16e1fca44487)

### Additional information
Actually, we use version 3.28. We tested versions 3.29, 3.30, 3.31, and 3.32, but they all failed.
It seems like Redisson is holding onto a bad connection without releasing it.

**Comment by Mortega5** [comment]
It looks like the bug was introduced in the version 3.27.0. I've rolled back to 3.26.1 and it's working fine again, but all newer versions are still broken (including 3.39.0).

**Comment by avcad** [comment]
Hi @mrniko,

I created a quick test to reproduce with 3.40.0 
It gets a topic and then in a loop, adds a listener, does publish, and then removes the listener.
I change the IP of redis by deleting and re-creating the redis services.
After recreating the service, Redisson notices the DNS change and reconnects, pub/sub continues to work but then
the test fails

org.redisson.client.RedisTimeoutException: Remove listeners operation timeout: (7500ms) for Topic1 topic
	at org.redisson.pubsub.PublishSubscribeService.lambda$removeAllListenersAsync$56(PublishSubscribeService.java:1010)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:713)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:701)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:788)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:501)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:857)

SEVERE: Test failed
org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 7500ms. Try to increase 'subscriptionTimeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.lambda$subscribe$18(PublishSubscribeService.java:414)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:713)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:701)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:788)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:501)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:857)

I collected traces:
[trace.log](https://github.com/user-attachments/files/18002706/trace.log)

![image](https://github.com/user-attachments/assets/9b52a78e-1cc1-4b1a-8150-7c82f29ca7cd)

**Comment by mrniko** [comment]
@avcad 

Unable to reproduce it with the code below. You can find SimpleDnsServer [here](https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/SimpleDnsServer.java)

```java
    @Test
    public void testAddListenerFailover() throws Exception {
        GenericContainer<?> redis = createRedis();
        redis.start();

        SimpleDnsServer s = new SimpleDnsServer();

        Config config = new Config();
        config.setProtocol(protocol);
        config.setAddressResolverGroupFactory(new SequentialDnsAddressResolverFactory() {
            @Override
            public AddressResolverGroup<InetSocketAddress> create(Class<? extends DatagramChannel> channelType, Class<? extends SocketChannel> socketChannelType, DnsServerAddressStreamProvider nameServerProvider) {
                return super.create(channelType, socketChannelType, hostname ->
                                            DnsServerAddresses.singleton(SocketUtils.socketAddress("127.0.0.1", 55)).stream());
            }
        });
        config.useSingleServer()
                .setAddress("redis://simplehost:" + redis.getFirstMappedPort());
        RedissonClient redisson = Redisson.create(config);

        RTopic topic = redisson.getTopic("topic");

        Logger logger = LoggerFactory.getLogger("out");

        for (int i = 0; i < 100; i++) {

            if (i == 3) {
                s.updateIP("127.0.0.2");
            }

            for (int j = 0; j < 60; j++) {
                topic.publish("test" + j);
                Thread.sleep(100);
            }
            topic.removeAllListeners();

            logger.info("step1 " + i);
        }

        redisson.shutdown();
        redis.stop();
    }
```

**Comment by mrniko** [comment]
Hi @avcad 

I managed to reproduce the issue. Thanks for the test code.
