### ISSUE TITLE
nodes (ip/port) that leave the cluster and then rejoin are never reflected in redison cluster topology, but are in CLUSTER NODES

### ISSUE THREAD

**Issue by sclasen** [redisson/redisson#6028]
### Redis version

6.x

### Redisson version

3.32.0

### Redisson configuration

Cluster Configuration

### What is the Expected behavior?

When a master is detected as suspect and removed from the cluster and its standby promoted, and then the same master node ip/port is re-added to the cluster, and re-promoted to master, redisson's cluster topology should reflect the current state of the cluster as returned by CLUSTER NODES

### What is the Actual behavior?

The new master is not present in redisson's cluster topology and the old master continues to be attempted to be used.

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! 

### Additional information

it appears to be happening because `ClusterConnectionManager.lastUri2Partition` does not have entries removed when nodes leave the cluster.  Then, when the node rejoins and is re-promoted to master, `masterFound == true` and the logic for adding partitions does not run.

```
ClusterPartition currentPart = (ClusterPartition)this.lastUri2Partition.get(newPart.getMasterAddress());
boolean masterFound = currentPart != null;
...
if (!masterFound && !newPart.isMasterFail()) {
    addedPartitions.put(newPart.getMasterAddress(), newPart);
}
```

**Comment by mrniko** [comment]
Can you share Redisson logs in debug mode?

**Comment by mrniko** [comment]
Duplicated with https://github.com/redisson/redisson/issues/5972

**Comment by sclasen** [comment]
https://gist.github.com/sclasen/17907cb2433d0163b6384eb430ee2f42

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/5972. Thanks for the provided logs
