### ISSUE TITLE
Settings into application.properties file.

### ISSUE THREAD

**Issue by todeia** [redisson/redisson#6035]
### Redis version

7.0.7

### Redisson version

redisson-quarkus-30:3.32.0

### Redisson configuration

quarkus.redisson.file=my-file-inside-of-resources-dir

### What is the Expected behavior?

Correctly read the file from my resources.

### What is the Actual behavior?

The file is not read the quarkus app do not start.

### Additional information

I was looking at the source code and found this.

```
if (configFile.isPresent()) {
    configStream = getClass().getResourceAsStream(configFile.get());
} else {
    configStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("redisson.yaml");
}
```
If use the line  if the config file is present works fine:

```
Thread.currentThread().getContextClassLoader().getResourceAsStream(configFile.get());
```

Is it possible to make this improvement?
Thank you in advance for adding this functionality. It helps me not have to keep code on my side :)

**Comment by mrniko** [comment]
Done
