### ISSUE TITLE
Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. 

### ISSUE THREAD

**Issue by cuifanjian** [redisson/redisson#6038]
org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 0. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@160411613 [redisClient=[addr=redis://10.224.144.30:25277], channel=[id: 0xdc6688bd, L:/10.206.230.245:50252 - R:/10.224.144.30:25277], currentCommand=null], command: (HEXISTS), params: [un:inv:pay, 57ab1259-e122-4ebd-85bc-24d462c58276:55] after 3 retry attempts
	at org.redisson.command.RedisExecutor$2.run(RedisExecutor.java:201) ~[redisson-3.13.4.jar!/:3.13.4]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
	
	
	
I have tried adding nettyThread and retroInterval, but still have this issue, and my workload is not heavy. It is executed every two minutes in scheduled tasks, just a regular distributed lock, version 3.13.4. The configuration and code are as follows:

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
    retryAttempts: 3
  retryInterval: 1500
  #  reconnectionTimeout: 3000
  #  failedAttempts: 3
  password: 2f0b9e0035ad333d
  subscriptionsPerConnection: 5
  clientName: unPay
  address: redis://10.224.144.30:25277
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 1
  dnsMonitoringInterval: 5000
  pingConnectionInterval: 30000
threads: 16
nettyThreads: 256
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode : "NIO"

@Scheduled(cron = "0 */2 * 12-31 * ?")
    @Override
    public Result doPay() {
        Result result = new Result(true);
        RLock rLock = null;
        try {
            rLock = RedissonUtil.getRLock("un:inv:pay");
            boolean acquired = rLock.tryLock(300, TimeUnit.MILLISECONDS);
            if (!acquired) {
                result.setSuccess(false);
                return result;
            }
            result = admPayManager.doPay(payCount);
        } catch (Exception e) {
            result.setSuccess(false);
            result.setMessage( ExceptionUtils.getRootCauseMessage(e));
        } finally {
            if (rLock != null && rLock.isHeldByCurrentThread()) {
                rLock.unlock();
            }
        }
        return result;
    }

**Comment by cuifanjian** [comment]
@mrniko help

**Comment by mrniko** [comment]
Please refer to https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by cuifanjian** [comment]
> Please refer to https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

@mrniko 
I have seen this before and it has not been resolved。I have now resolved it by upgrading to version 3.13.6. It is obvious that this is a bug that exists in Redisson version 3.13.4
