### ISSUE TITLE
Issue related to redis and redisson

### ISSUE THREAD

**Issue by arman-nurniyazov** [redisson/redisson#6039]
I get this error even though I don't use it in code directly (java spring boot)

org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@18982198 [redisClient=[addr=redis://localhost:6379], channel=[id: 0x44b2f829, L:/127.0.0.1:59046 ! R:localhost/127.0.0.1:6379], currentCommand=null], command: (EVAL), params: [local value = redis.call('hget', KEYS[1], ARGV[3]); if value == false then return nil; end; local ex..., 3, TERMINAL_BY_TYPE_CACHE, jcache_timeout_set:{TERMINAL_BY_TYPE_CACHE}, jcache_removed_channel:{TERMINAL_BY_TYPE_CACHE}, -1, 1721386681898, PooledUnsafeDirectByteBuf(ridx: 0, widx: 63, cap: 256)] after 3 retry attempts

Redis version: 7.2.5
Redisson version: 3.15.6
singleServerConfig (default configuration)

**Comment by mrniko** [comment]
Please refer to https://github.com/redisson/redisson/wiki/16.-FAQ#q-what-is-the-cause-of-redistimeoutexception

**Comment by arman-nurniyazov** [comment]
I removed cache config and usages from code, but I still have above mentioned issue. How is it possible and how can I fix it?
