### ISSUE TITLE
Reactive API usage unclear for unlocking

### ISSUE THREAD

**Issue by mariusgiger** [redisson/redisson#6046]
The [documentation](https://github.com/redisson/redisson/wiki/8.-Distributed-locks-and-synchronizers) regarding reactive usage is unclear. As `lock.unlock()` returns a `Publisher`, `doOnFinally` will never release the lock. Further, when unlocking using a reactive operator (e.g. `then`), Redisson complains that not the same threadId is used to unlock `redisson attempt to unlock lock, not locked by current thread by node id`. 

not working (current):
```
RedissonReactiveClient redisson = redissonClient.reactive();
RLockReactive lock = redisson.getLock("myLock");

Mono<Void> lockMono = lock.lock();

// or acquire lock and automatically unlock it after 10 seconds
Mono<Void> lockMono = lock.lock(10, TimeUnit.SECONDS);

// or wait for lock aquisition up to 100 seconds 
// and automatically unlock it after 10 seconds
Mono<Boolean> lockMono = lock.tryLock(100, 10, TimeUnit.SECONDS);

lockMono.doOnNext(res -> {
   // ...
})
.doFinally(lock.unlock())
.subscribe();
```

Is the intended usage as follows?
```
RedissonReactiveClient redisson = redissonClient.reactive();
RLockReactive lock = redisson.getLock("myLock");

var threadId = Thread.currentThread().getId();

Mono<Void> lockMono = lock.lock(threadId);

// or acquire lock and automatically unlock it after 10 seconds
Mono<Void> lockMono = lock.lock(10, TimeUnit.SECONDS, threadId);

// or wait for lock aquisition up to 100 seconds 
// and automatically unlock it after 10 seconds
Mono<Boolean> lockMono = lock.tryLock(100, 10, TimeUnit.SECONDS, threadId);

lockMono.doOnNext(res -> {
   // ...
})
.doFinally(lock.unlock(threadId).subscribe())
.subscribe();
```

**Comment by mrniko** [comment]
Thanks for pointing out. The documentation has been fixed.

**Comment by mariusgiger** [comment]
> Thanks for pointing out. The documentation has been fixed.

Thanks! please note that subscribing is usually not the way to go in a reactive context and only for documentation purposes. A more suitable example could be considered in the future.

**Comment by k631583871** [comment]
@mrniko I personally understand that Reactive will not be unlocked in the same thread. Should we remove this verification.
