### ISSUE TITLE
r.getJsonBucket(JsonBucketOptions options) does not return RJsonBucket with specified timeout/retryAttempts/retryInterval

### ISSUE THREAD

**Issue by jhezzzz** [redisson/redisson#6049]
Hi, 

Upon upgrading to 3.32.0 from 3.23.1, a new [feature](https://github.com/redisson/redisson/commit/db2f746aed8d7d319ab1762ff8d80541416a5013) was introduced to specify retryInterval, retryAttempts, timeout per Redisson object. However, this functionality was not introduced for the RJsonBucket when executing JSON commands ([code link](https://github.com/redisson/redisson/blob/d1bf2860e53318a14892dd4bc46986b0d1393401/redisson/src/main/java/org/redisson/Redisson.java#L293)). I believe it should be `commandExecutor.copy(params)` to give the `commandExecutor` the overridden parameters from JsonBucketOptions. Can you confirm whether this is expected behavior to not invoke `copy(params)`? Thanks!

Also, a question on how `connectTimeout` is configured and behaves. If we specify a connectTimeout of 5000ms on client configuration (due to the scale of our Redis cluster for client initialization) and a timeout of 30ms (we are a latency sensitive service), what does this look like in terms of latency incurred on a request (i.e. a connection is not available in the connection pool, Redis server is unavailable, etc.)?

i.e. For retryAttempt = 2, will it always be requestTimeout == (Timeout + RetryInterval + Timeout + RetryInterval + Timeout) as the upper bound on max time on the API call (i.e. bucket.get())

Please let me know, I would be happy to provide any additional data to clarify :)

Best,
Jonathan

**Comment by mrniko** [comment]
Fixed in 3.35.0 version

As for timeout it will look like as you described. You need to take in account that some methods can't be resent after response timeout, thus won't be retried at all after the first attempt.
