### ISSUE TITLE
Redisson does not recover from DNS failures on master resolution for single-shard clusters

### ISSUE THREAD

**Issue by barreeeiroo** [redisson/redisson#6061]
### Affected Versions

3.32.0 onwards. Validated with 3.31.0 and it was not present; 3.32.0, 3.33.0 and current `master` as of now are affected.

### Redis Cluster Details

* AWS ElastiCache
* Redis 6.2.6
* Instance t3.micro
* Cluster Configuration
    * 1 Shard (aka 1 Master)
    * 2 Slaves

### Issue Isolation

* Tried with different instances size; behaviour did not change.
* Tried with different amount of slaves; behaviour did not change.
* Tried with different amount of shards; behaviour DID change.

The issue is only reproducible on single-shard clusters.

### Issue Description

If Redisson detects a DNS resolution failure on the master node for a cluster, and there is only a single master (single shard), it never connects back again despite the DNS issue being fixed.

To reproduce, the following code was introduced into `ServiceManager.resolveAll` promise:

```
            String host = uri.getHost();
            if (host.contains("-001.")) {  // Target only masters
                if (!attemptCounter.containsKey(host)) {
                    attemptCounter.put(host, 0);
                }

                Integer attempt = attemptCounter.get(host);
                log.info("ATTEMPT {} for {}", attempt, host);
                attemptCounter.put(host, attempt + 1);

                if (attempt > 1 && attempt < 4) {
                    log.error("FORCING DNS FAILURE for {}", uri, f.cause());
                    result.completeExceptionally(new RuntimeException("Dummy"));
                    return;
                }
            }
```

The following was observed:

* On DNS success, everything works fine.
* When DNS failure occurs, it fails all connections.
* When DNS issue is mitigated, it resolves correctly the IP, but it does not connect back and from a Redisson client perspective, you cannot fetch any keys anymore.

I did try to replicate failure for ALL masters in multi-shard, but it connected back again correctly.

The initialization of Redisson is as follows:

```
        Config config = new Config();

        // Only one node of cluster configuration endpoint need to be specified - all other nodes are auto detected
        // SLAVE - Read from slave nodes, uses MASTER if no SLAVES are available.
        // MASTER - Read from master node,
        // MASTER_SLAVE - Read from master and slave nodes
        config.useClusterServers()
                .setReadMode(ReadMode.MASTER_SLAVE)
                .addNodeAddress(REDIS_DATABASE_URL)
                .setTimeout(REDIS_TIMEOUT)
                .setRetryAttempts(REDIS_RETRY_ATTEMPT)
                .setRetryInterval(REDIS_RETRY_INTERVAL)
                .setConnectTimeout(REDIS_CONNECTION_TIMEOUT);

        return Redisson.create(config);
```

**Comment by mrniko** [comment]
Thanks for report. Are there any errors in logs?

**Comment by barreeeiroo** [comment]
@mrniko here are the logs: https://pastebin.com/xARR04A3 (sent in Pastebin because they are extensive and it would overload the comments here)

`TestClient` is just a dummy Java program with an infinite loop:

```
        RedissonClient client = testClient.getClient();

        while (true) {
            try {
                RMap<String, String> map1 = client.getMap("test");
                map1.put("a", "b");

                RMap<String, String> map2 = client.getMap("test");
                String value = map2.get("a");
                log.info("Retrieved from cache: {}", value);

                RMap<String, String> map3 = client.getMap("test");
                map3.remove("a");

            } catch (Exception e) {
                log.error("Exception");
                e.printStackTrace();
                // break;
            }

            Thread.sleep(2000);
        }
```

**Comment by mrniko** [comment]
Can you try attached version or build from master branch?

[redisson-3.33.1-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16400063/redisson-3.33.1-SNAPSHOT.jar.zip)

**Comment by barreeeiroo** [comment]
@mrniko thanks, but would it be possible to share the git patch instead? I am simulating the master nodes DNS resolution failure by directly modifying Radisson source code, so I cannot mimic the failure if I have the compiled JAR file.

**Comment by mrniko** [comment]
Here is the commit - https://github.com/redisson/redisson/commit/7d9b899fa139053134057cca7d18be741bb36b01

**Comment by barreeeiroo** [comment]
@mrniko thank you, just confirmed that this commit has fixed the issue:

* On single-shard, a DNS failure on master nodes does not prevent Redisson from fully fail to access Redis:
    * During DNS failure, Redisson falls back to previously known nodes (not sure if it is going to slaves or using the "previously known IPs").
    * After DNS failure, Redisson recovers.
* Multi-shard cluster behaves the same way:
    * Same as single shard...
    * The NPE fix seems to also have worked, because on multi-shard we were getting NPE even after DNS recovery (it was not affecting reading or writing though).

It looks like the behaviour is restored to the previous version. Thank you again for the quick fix!

**Comment by mrniko** [comment]
Thanks much for testing!
