### ISSUE TITLE
Attempt to fully sync to 'CLUSTER NODES' after some timeout where the cluster is not healthy from the client perspective

### ISSUE THREAD

**Issue by sclasen** [redisson/redisson#6064]
**Is your feature request related to a problem? Please describe.**

We've seen the ClusterConnectingManager get into some weird states with different permutations of nodes joining and leaving, that are always resolvable by restarting the service using redisson, which is less than desirable.

**Describe the solution you'd like**

When ClusterConnectionManager sees the cluster as not having full slot coverage for some configurable period of time, attempt to restart the ClusterConnectionManager subsystem as if starting a fresh redissonClient, i.e. throw away all cluster topology / connections and do a full resync from 'CLUSTER NODES'

**Describe alternatives you've considered**

based on redisson / redis health checking, stop / throwaway / recreate the whole redissonClient instance. This is perhaps doable but kind of annoying in a spring boot based service where the redissonClient is typically shared and autowired everywhere

**Comment by mrniko** [comment]
`CLUSTER NODES` command is executed periodically. If it returns topology that doesn't have full slot coverage then even a full restart won't help.

**Comment by sclasen** [comment]
i think maybe my description was not detailed enough. Weve seen several scenarios where ClusterConnectionManager's view of the topology does not match CLUSTER NODES.  ClusterConnectionManager's thinks slot coverage is missing, when CLUSTER NODES says slots are covered.

This would be a timeout/backstop, where if ClusterConnectionManager sees missing slot coverage for some timeout, it throws away all state and resyncs from CLUSTER NODES, which in our case would have fixed the issue every time, just as restarting the service with the redissonClient does.

**Comment by sclasen** [comment]
we have reported the ones we've seen so far, thank you so much for the fixes.   This is just an idea for having a backstop in case of similar situations happening.

**Comment by mrniko** [comment]
I think since cluster topology issues were fixed it can be closed now.
