### ISSUE TITLE
Method to force fetch value in RLocalCachedMap from Redis?

### ISSUE THREAD

**Issue by sggts04** [redisson/redisson#6065]
I have been experimenting with RLocalCachedMap to sync a critical cache map across multiple pods. 

As I increase the scale of my tests, I have started noticing some misses in cache invalidation events from one pod to another. And that is fine, I know to a small extent that is possible and expected. This is the config I'm using:

```java
LocalCachedMapOptions.defaults().storeCacheMiss(true).reconnectionStrategy(ReconnectionStrategy.CLEAR);
getRedissonClient().getLocalCachedMap("UserCache", cachedMapOptions);
```

But there are few critical sections in my code where I can't afford an inconsistent state and am willing to fetch the latest value directly from Redis even with the cost of efficiency.
Is there any way I can do this through RLocalCachedMap where I forcefully fetch a key from Redis and not from whatever is locally cached?
Something along the lines of `((RLocalCachedMap<String, User>) userCache).getFromRedis(userId)` ?

One hacky implementation I was thinking of was keeping an RMap<> with the same name as my RLocalCachedMap and fetching through it when I need the Redis state, will that work? Will Redisson support that?

Or perhaps a method which invalidates local cache for a particular key in RLocalCachedMap? I can do that before fetching to achieve this, but couldn't find such a method in the docs

**Comment by raja2102598** [comment]
@sggts04 set the cacheSize to -1, it will disable the localcache and always fetch the data from redis, but doing this will affect the entire localcachemap not particular key.

[JavaDoc](https://www.javadoc.io/static/org.redisson/redisson/3.33.0/org/redisson/api/options/LocalCachedMapOptions.html#cacheSize(int))

**Comment by sggts04** [comment]
That I am aware of, if I wanted to affect all keys I could have just done .clearLocalCache()

**Comment by raja2102598** [comment]
One option is to use the RMap along with RLocaCacheMap, but there will be inconsistencies if the RMap is updated and RLocalCacheMap's CachedMap is not cleared.  
Other one is, get the cachedMap and remove that particular key from the cache, then get that key again.

**Comment by sggts04** [comment]
> get the cachedMap and remove that particular key from the cache

This is what I'm curious about, I couldn't find a direct method to do this.

Does this work: `cachedMap.cachedKeySet().remove(userId);` ? Or is there some other way to achieve this

@raja2102598

**Comment by raja2102598** [comment]
i checked it, this doesn't work, because cachedKeySet() gives new reference.

Go with Rmap or use multiple RLocalCachedMap instances (LocalCache Enabled/ Disabled)

**Comment by sggts04** [comment]
Does seem like its removing key from cache when I remove from LocalKeySet (which is returned by cachedKeySet())

![image](https://github.com/user-attachments/assets/cd2f3fa4-0900-4558-86b5-d37853effa7d)

and the cache in RedissonLocalCachedMap is fetched from this LocalCacheView instance only

![image](https://github.com/user-attachments/assets/d5b10045-a42e-44b2-80d4-de7287f6b41e)

Also wrote a test to check if removing key from this keyset does any change in time taken to fetch key after that.

```java
RLocalCachedMap<String, User> cachedMap = redissonClient.getLocalCachedMap("myRLCMap", LocalCachedMapOptions.defaults());
        cachedMap.put("1", new User("1"));
        cachedMap.put("2", new User("2"));

        getRuntime("RLocalCachedMap GET 10k times", () -> {
            for (int i=0; i<10000; i++) {
                cachedMap.get("1");
                cachedMap.get("2");
            }
        });

        getRuntime("RLocalCachedMap Removing from Local KeySet 10k times", () -> {
            for (int i=0; i<10000; i++) {
                cachedMap.cachedKeySet().remove("1");
                cachedMap.cachedKeySet().remove("2");
            }
        });

        getRuntime("RLocalCachedMap GET 10k times while Removing from Local KeySet", () -> {
            for (int i=0; i<10000; i++) {
                cachedMap.cachedKeySet().remove("1");
                cachedMap.cachedKeySet().remove("2");
                cachedMap.get("1");
                cachedMap.get("2");
            }
        });
```

These are the results

```
RLocalCachedMap GET 10k times took: 30 ms
RLocalCachedMap Removing from Local KeySet 10k times took: 21 ms
RLocalCachedMap GET 10k times while Removing from Local KeySet took: 1425 ms
```

These results do suggest it is refetching from Redis?

**Comment by raja2102598** [comment]
Yes, i think it's fetched from redis, you can do monitor command in redis-cli to verify it's calling the redis for get operation.

**Comment by sggts04** [comment]
Verified by monitoring Redis, this works! Thanks
