### ISSUE TITLE
I hope I can support apache fury serialization to support better cross-language performance.

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#6066]
I hope I can support apache fury serialization to support better cross-language performance.
https://github.com/apache/fury

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by mrniko** [comment]
Done

**Comment by theigl** [comment]
@mrniko Fury has been renamed to Fory. Package and artifact names have changed and many improvements and fixes have been released. Could you please add a `ForyCodec` as well?

**Comment by mrniko** [comment]
@theigl Please create a separate issue on that
