### ISSUE TITLE
Will fencedLock be added to the redisson-spring-boot-starter module?

### ISSUE THREAD

**Issue by Gyuchool** [redisson/redisson#6076]
When I looked at the [docs](https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers/#810-fenced-lock) and [commit](https://github.com/redisson/redisson/commit/b9513bc12286b151c999a29b495ef6e4515e8470), I confirmed that redisson supports fencedLock. When I actually used the `org.redisson:redisson` dependency, I confirmed that fencedLock could be used. 
However, when I used the `org.redisson:redisson-spring-boot-starter` dependency, fencedLock could not be used. 
I wonder if fencedLock is scheduled to be added to the spring boot starter module. Or is there a reason for not to add it?

**Comment by mrniko** [comment]
redisson-spring-boot-starter depends org.redisson:redisson dependency. So all locks and objects are available

**Comment by Gyuchool** [comment]
Um... when I added the redisson-spring-boot-starter dependency like this picture, 
![image](https://github.com/user-attachments/assets/31263b9a-78ed-4249-9063-719c4f6c8f44)
it couldn't be used like this
![image](https://github.com/user-attachments/assets/3b0739db-8fa2-41fc-bf12-1cd446c2b497)
![image](https://github.com/user-attachments/assets/2fb7b24f-147a-4447-9853-17dffe1ad093)
 Is the method I'm using wrong?

**Comment by mrniko** [comment]
Try to set the same version as for redisson dependency.
