### ISSUE TITLE
What's the difference of LocalCachedMap between open source version and pro version?

### ISSUE THREAD

**Issue by jaggerwang** [redisson/redisson#6088]
As it said only pro version support ultra-fast read/write, what does it mean？

**Comment by mrniko** [comment]
Another Redis commands processing engine is used

**Comment by jaggerwang** [comment]
In the same usage scenario, how many times is the performance of the Pro version compared to the open source version? The open source version does indeed use local caching to accelerate, right.

**Comment by mrniko** [comment]
> how many times is the performance of the Pro version compared to the open source version?
2 or 4. depending on the use case.

> The open source version does indeed use local caching to accelerate, right.
Right, but Redis commands processing acceleration isn't available in the open-source version.
