### ISSUE TITLE
Redisson client failed to successfully reconnect, After the Redis service went down and then recovered

### ISSUE THREAD

**Issue by fanmindnn** [redisson/redisson#6091]
My Redis service went down at 2024-08-15 13:00, and recovered after 1 minute, but the Java application kept reporting 'Redis server response timeout (3000 ms) occurred after 3 retry attempts.' The issue persisted for 15 minutes without automatic recovery, and the application only recovered after a restart. Upon examining the logs, I found that the Redis channel was not performing ping checks, closing, and rebuilding. Below is an excerpt from the error log of one channel.
<img width="639" alt="image" src="https://github.com/user-attachments/assets/66d75f7e-9260-4fee-a607-77bb96dd980d">
<img width="687" alt="image" src="https://github.com/user-attachments/assets/ef289fdd-7f8a-4f43-80ad-c6e99d58218f">

From 13:00 to 13:12, this channel kept reporting errors until it was finally closed after a Ping check 12 minutes later. I did not set the pingConnectionInterval parameter, so it should have initiated a Ping check within 30 seconds by default, but it ultimately took 12 minutes.

**Please help me avoid this kind of problem！**

**redisson version:3.17.3**

**Comment by fanmindnn** [comment]
I have several other Java applications using the same version of the Redisson client, but their exceptions recover normally. The difference is that the problematic application has a high Redis access volume, while the others have lower access volumes. Could this be related?

**Comment by mrniko** [comment]
@fanmindnn

3.17.6 version has fixes ping handling:

Fixed - PingConnectionHandler should close channel on RedisLoadingException, RedisTryAgainException, RedisClusterDownException, RedisBusyException
Fixed - Connection pinging works incorrectly if new connections were created in pool

I recommend you to update.

**Comment by shakunahuja** [comment]
Is this issue exist in redisson 3.24.3 version as well as we are facing similar kind of scenario?
