### ISSUE TITLE
LocalCacheView.toCacheKey Method Optimization

### ISSUE THREAD

**Issue by raja2102598** [redisson/redisson#6095]
Hi, 

For every get() we are creating the cacheKey and this takes some time, Is there any way i can optimize this toCacheKey method? 

Can we just store the calculated hash value once and reuse it again?

![image](https://github.com/user-attachments/assets/0f044554-7780-4cc5-89b0-397ed7c77825)

**Comment by mrniko** [comment]
Redis doesn't use equals, hashCode but serialized state for map entry lookup by key. This is why local cache uses the same principle.

**Comment by mrniko** [comment]
You need to use `useObjectAsCacheKey` setting
