### ISSUE TITLE
jvm crash when redisson FstCodec decode

### ISSUE THREAD

**Issue by GuiminZHOU** [redisson/redisson#6103]
we just have several times jvm crash, and from the hs_err_pid.log, it seems that it occurs a problem during redisson decode
【env】3.11.5 with FstCodec

【log】
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa4cc9c31e2, pid=1, tid=0x00007fa29c7e7700
#
# JRE version: OpenJDK Runtime Environment (8.0_232-b09) (build 1.8.0_232-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.232-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 58601 C2 sun.reflect.GeneratedMethodAccessor4337.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (66 bytes) @ 0x00007fa4cc9c31e2 [0x00007fa4cc9c3160+0x82]
#
# Core dump written. Default location: xxxxxx
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x00007fa2a40b1f40):  JavaThread "redisson-netty-2-27" [_thread_in_Java, id=172, stack(0x00007fa29c6e7000,0x00007fa29c7e8000)]

【stack】
Stack: [0x00007fa29c6e7000,0x00007fa29c7e8000],  sp=0x00007fa29c7e5f90,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 58601 C2 sun.reflect.GeneratedMethodAccessor4337.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (66 bytes) @ 0x00007fa4cc9c31e2 [0x00007fa4cc9c3160+0x82]
J 48808 C2 org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;Ljava/lang/Object;Lorg/nustaq/serialization/FSTClazzInfo;Ljava/lang/Class;)V (254 bytes) @ 0x00007fa4cd49af14 [0x00007fa4cd4998c0+0x1654]
J 52498 C2 org.nustaq.serialization.FSTObjectInput.readObjectCompatible(Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;Lorg/nustaq/serialization/FSTClazzInfo;Ljava/lang/Object;)Ljava/lang/Object; (35 bytes) @ 0x00007fa4cd8f6650 [0x00007fa4cd8f6600+0x50]
J 33542 C2 org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(Ljava/lang/Class;Lorg/nustaq/serialization/FSTClazzInfo;Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;I)Ljava/lang/Object; (272 bytes) @ 0x00007fa4ca698f5c [0x00007fa4ca698dc0+0x19c]
J 30101 C2 org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;)Ljava/lang/Object; (189 bytes) @ 0x00007fa4ca282258 [0x00007fa4ca281d20+0x538]
J 33108 C2 org.nustaq.serialization.FSTObjectInput.readObjectFields(Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;Lorg/nustaq/serialization/FSTClazzInfo;[Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;Ljava/lang/Object;II)V (538 bytes) @ 0x00007fa4cab2538c [0x00007fa4cab25240+0x14c]
J 33542 C2 org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(Ljava/lang/Class;Lorg/nustaq/serialization/FSTClazzInfo;Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;I)Ljava/lang/Object; (272 bytes) @ 0x00007fa4ca698f30 [0x00007fa4ca698dc0+0x170]
J 30101 C2 org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;)Ljava/lang/Object; (189 bytes) @ 0x00007fa4ca282258 [0x00007fa4ca281d20+0x538]
J 34559 C2 org.nustaq.serialization.serializers.FSTArrayListSerializer.instantiate(Ljava/lang/Class;Lorg/nustaq/serialization/FSTObjectInput;Lorg/nustaq/serialization/FSTClazzInfo;Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;I)Ljava/lang/Object; (71 bytes) @ 0x00007fa4cafe9448 [0x00007fa4cafe9040+0x408]
J 30101 C2 org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(Lorg/nustaq/serialization/FSTClazzInfo$FSTFieldInfo;)Ljava/lang/Object; (189 bytes) @ 0x00007fa4ca2821a8 [0x00007fa4ca281d20+0x488]
J 60337 C2 org.redisson.codec.FstCodec$1.decode(Lio/netty/buffer/ByteBuf;Lorg/redisson/client/handler/State;)Ljava/lang/Object; (98 bytes) @ 0x00007fa4cec350fc [0x00007fa4cec34c80+0x47c]
J 70637 C2 org.redisson.client.handler.CommandDecoder.decode(Lio/netty/buffer/ByteBuf;Lorg/redisson/client/protocol/CommandData;Ljava/util/List;Lio/netty/channel/Channel;ZLjava/util/List;)V (750 bytes) @ 0x00007fa4cfc80344 [0x00007fa4cfc80140+0x204]
J 78205 C2 org.redisson.client.handler.CommandDecoder.decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Lorg/redisson/client/protocol/QueueCommand;)V (137 bytes) @ 0x00007fa4ce8219d4 [0x00007fa4ce821840+0x194]
J 60572 C2 org.redisson.client.handler.CommandDecoder.decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V (142 bytes) @ 0x00007fa4c91ee470 [0x00007fa4c91ee280+0x1f0]
J 70635 C2 io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V (115 bytes) @ 0x00007fa4cbbc0dd4 [0x00007fa4cbbc0d80+0x54]
J 45102 C2 io.netty.handler.codec.ReplayingDecoder.callDecode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V (297 bytes) @ 0x00007fa4c949b084 [0x00007fa4c949aee0+0x1a4]
J 57328 C2 io.netty.handler.codec.ByteToMessageDecoder.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (311 bytes) @ 0x00007fa4ce5f34c4 [0x00007fa4ce5f32c0+0x204]
J 34200 C2 io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (9 bytes) @ 0x00007fa4c8368b8c [0x00007fa4c83689a0+0x1ec]
J 82178 C2 io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized()V (99 bytes) @ 0x00007fa4d06e747c [0x00007fa4d06e6c60+0x81c]
J 39444% C2 io.netty.channel.nio.NioEventLoop.run()V (236 bytes) @ 0x00007fa4ca784d54 [0x00007fa4ca784b00+0x254]
j  io.netty.util.concurrent.SingleThreadEventExecutor$6.run()V+44
j  io.netty.util.internal.ThreadExecutorMap$2.run()V+11
j  io.netty.util.concurrent.FastThreadLocalRunnable.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6349ce]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xf2e
V  [libjvm.so+0x631e64]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x2a4
V  [libjvm.so+0x632469]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x59
V  [libjvm.so+0x67408e]  thread_entry(JavaThread*, Thread*)+0x8e
V  [libjvm.so+0x9a5d22]  JavaThread::thread_main_inner()+0x1f2
V  [libjvm.so+0x85e202]  java_start(Thread*)+0xf2
C  [libpthread.so.0+0x7e25]  start_thread+0xc5

anyone has the same prob? save my life pl, tks in advance!

**Comment by mrniko** [comment]
FSTCodec has been deprecated. Try to use Kryo5Codec
