### ISSUE TITLE
Enum Deserialization with Kyro5Codec 

### ISSUE THREAD

**Issue by Akanksha441** [redisson/redisson#6104]
I have recently upgraded to redisson version 3.32.0 and chosen **Kryo5Codec**.

Now if I try to read any object from cache that has nested Enum in it, it throws ClassCastException while deserialising Enum.

Is it a known issue? Is there any planned release/fix for this?

**Comment by mrniko** [comment]
Unable to reproduce. Can you share the code sample?

**Comment by Akanksha441** [comment]
So the Issue is specifically while using EnumMap with Kyro5Codec and it fails in Serialization/DeSerialization.
My system was using MarshallingCodec and usage of EnumMap was working fine. Since MArshalling is deprecated, I m using Kyro5Codec which brings this issue.
Uploaded Sample Code at https://github.com/Akanksha441/Sample

**Comment by mrniko** [comment]
@theigl 

Is it a bug?

**Comment by theigl** [comment]
There is an `EnumMapSerializer` in Kryo but it needs to be registered manually:

https://github.com/EsotericSoftware/kryo/blob/1d7a5ad14cd78120071a01fae50d0a88cf551b0c/test/com/esotericsoftware/kryo/serializers/MapSerializerTest.java#L76-L85

I was not aware of this until now and had to look it up myself. I think the reason for this is that it isn't possible to access the `keyType` of an `EnumMap` without reflection.

**Comment by mrniko** [comment]
Fixed.

**Comment by Akanksha441** [comment]
@mrniko Will this fix be available in [3.36.0]?

**Comment by mrniko** [comment]
@Akanksha441 

Yes
