### ISSUE TITLE
Apply should be before SortBy in RedissonSearch.class

### ISSUE THREAD

**Issue by yinjiajin1990** [redisson/redisson#6107]
![image](https://github.com/user-attachments/assets/dce189d5-3358-4531-b2af-cd7e443a5bf7)

Apply should be before SortBy in RedissonSearch.class ?

For example I use command:
FT.AGGREGATE public_place_parking_idx "@enableStatus:[1 1]" load 2 $ location apply "geodistance(@location, 114.058663,22.543096)/1000" as distance sortby 2 @distance asc limit 1 10

**Comment by mrniko** [comment]
Can you share the code to reproduce the issue?

**Comment by distance** [comment]
I'm sorry, I don't remember what it was about? Nor do I remember what website or software it happened on. So I can't reproduce the code for you

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Nikita Koksharov ***@***.***>
发送时间: Friday, August 23, 2024 2:40:48 PM
收件人: redisson/redisson ***@***.***>
抄送: distance ***@***.***>; Mention ***@***.***>
主题: Re: [redisson/redisson] Apply should be before SortBy in RedissonSearch.class (Issue #6107)


Can you share the code to reproduce the issue?

―

**Comment by mrniko** [comment]
unable to reproduce
