### ISSUE TITLE
getMapCache with MapCacheOptions

### ISSUE THREAD

**Issue by ramarro123** [redisson/redisson#6110]
hi, it seems that the method here

https://github.com/redisson/redisson/blob/84a2359693a608d44a579cb73c5a64600efbf875/redisson/src/main/java/org/redisson/api/RedissonClient.java#L301

is deprecated

how can i set the eviction policy passing MapCacheOptions to this call if it's deprecated to be "future proof" and let's say avoid deprecated method?

what is the best practice to do that?

**Comment by mrniko** [comment]
you need to use this instead
`<K, V> RMapCache<K, V> getMapCache(org.redisson.api.options.MapCacheOptions<K, V> options);`
