### ISSUE TITLE
RedissonListMultimapCache Memory Leak

### ISSUE THREAD

**Issue by marlondu** [redisson/redisson#6111]
I read the code and I got questions.
when call Redisson.getListMultimapCache it create a MultimapEvictionTask instance and put it to  EvictionScheduler.tasks.

So my question is when MultimapEvictionTask instance will be removed or collected by gc?
thank you.

**Comment by mrniko** [comment]
It should be released on the destroy() method call, but it isn't.

**Comment by mrniko** [comment]
Fixed. Thanks for report
