### ISSUE TITLE
3.35.0 use fury error

### ISSUE THREAD

**Issue by JavaLionLi** [redisson/redisson#6116]
### Redis version

7.2.6

### Redisson version

3.35.0

### Redisson configuration

![image](https://github.com/user-attachments/assets/b1edce5b-8ba3-422b-8117-2056ec664b3f)
![image](https://github.com/user-attachments/assets/4d21974a-5db7-4f4e-b521-dc017b25269d)

![image](https://github.com/user-attachments/assets/ab1b655e-1d01-4086-bf9f-7524090a17c6)
![image](https://github.com/user-attachments/assets/7edbb9d2-af07-45d4-b4e2-e0c7fa21680a)

idea to see that the class exists, but the class cannot be found after running keeps getting an error

### What is the Actual behavior?

1

**Comment by JavaLionLi** [comment]
![image](https://github.com/user-attachments/assets/2639b1d8-426b-4641-abd9-e74577da7bc1)
![image](https://github.com/user-attachments/assets/829768ea-b62e-4ceb-89bd-64fd1bd97641)

Tested separately is useful

**Comment by mrniko** [comment]
It's an optional dependency. Did you check your classpath?

**Comment by JavaLionLi** [comment]
> It's an optional dependency. Did you check your classpath?

I'm in the same module, in the same class, using main to test successfully

**Comment by mrniko** [comment]
It might be a problem with the class loader.

**Comment by JavaLionLi** [comment]
> It might be a problem with the class loader.

![image](https://github.com/user-attachments/assets/1f67dbaf-50d7-4d3a-ac58-df05637fd432)
Normal is springboot boot bean configuration Nothing special

**Comment by JavaLionLi** [comment]
> > It might be a problem with the class loader.
> 
> ![image](https://private-user-images.githubusercontent.com/31852897/360818607-1f67dbaf-50d7-4d3a-ac58-df05637fd432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTU3NTQsIm5iZiI6MTcyNDM5NTQ1NCwicGF0aCI6Ii8zMTg1Mjg5Ny8zNjA4MTg2MDctMWY2N2RiYWYtNTBkNy00ZDNhLWFjNTgtZGYwNTYzN2ZkNDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiODYxNjQyY2M2OTI1NDEzZDU2NWQ0MjhhZWQ2YzQwM2Y0YTc4MmY4N2YyYzc3ZTFiNGEzOTExMWYwMWE3OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6DRC8s9WneBBLpJkQBFUGQUQjtrNZcxCefsLPz17WE) Normal is springboot boot bean configuration Nothing special

It is not clear how to solve this problem

**Comment by JavaLionLi** [comment]
> It might be a problem with the class loader.

Key points were discovered
As long as it is used inside SpringBoot AutoConfiguration, the class cannot be found
Put it outside and let SpringBoot scan it automatically without any problem

**Comment by mrniko** [comment]
Can you try the same with Kryo5Codec?

**Comment by JavaLionLi** [comment]
> Can you try the same with Kryo5Codec?

Tried it and there was no problem
I also get an error when I initialize fury's bean separately in starter
Externally, let spring scan automatically is normal

**Comment by chaokunyang** [comment]
Maybe fury init failed dubb to some class conflict. Could you add try catch when  unit Fury by yourself and print stacktrace. If class init failed, jvm just throw classnodef error. I guess it's a guava dependency conflict

**Comment by JavaLionLi** [comment]
Changed the computer and it worked well, it should be the new version of idea maven refresh problem
