### ISSUE TITLE
Caused by: org.redisson.client.RedisException: java.lang.InterruptedException

### ISSUE THREAD

**Issue by harshalthakre** [redisson/redisson#6117]
`Caused by: org.redisson.client.RedisException: java.lang.InterruptedException | at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:113) | at org.redisson.RedissonObject.get(RedissonObject.java:83) | at org.redisson.RedissonObject.isExists(RedissonObject.java:234) | at com.x.x.x.caching.facade.impl.RedisElastiCache.getFromCache(RedisElastiCache.java:103) | ... 195 more | Caused by: java.lang.InterruptedException | at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347) | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) | at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:109) `

We are seeing this exceptions multiple times lately for Redisson 3.18
Which metrics we should be checking & how to fix this issue ?

**Comment by mrniko** [comment]
Something is interrupting the caller thread.

**Comment by mrniko** [comment]
Can you share a full stacktrace?
