### ISSUE TITLE
Support for hostnames in Cluster mode redisson client

### ISSUE THREAD

**Issue by tharunsikhinam** [redisson/redisson#6121]
**Context:** 

Starting from redis 7.x. two new properties `cluster-preferred-endpoint-type` and `cluster-announce-hostname` properties have been added. When` cluster-preferred-endpoint-type` is set to `hostname`, Moved and Ask responses contain the hostnames. 
When `cluster-announce-hostname` is set, cluster nodes outputs the hostname along with the Ip. https://redis.io/docs/latest/commands/cluster-nodes/

cluster nodes output
```
07c37dfeb235213a872192d90877d0cd55635b91 127.0.0.1:30004@31004,hostname4 slave e7d1eecce10fd6bb5eb35b9f99a514335d9ba9ca 0 1426238317239 4 connected
```

latest versions of lettuce, jedis connect to the individual nodes in the cluster via hostnames instead of Ips if hostnames are present.

**Problem:** 

When the nodes in the cluster have announced hostnames. Redisson should parse the hostnames instead of IPs from cluster nodes output and connect to the nodes via hostnames. 
By default, Redisson runs cluster nodes and uses the IPs to make connections to the individual nodes. This integration will not work when the nodes are behind a proxy/NAT gateway.

https://github.com/redisson/redisson/blob/d938ae50c5951c747037afbb25b156d734f802f0/redisson/src/main/java/org/redisson/client/protocol/decoder/ClusterNodesDecoder.java#L72

Looking at the above line of code it looks like we only use IPs and ignore the hostnames even if they are present.

**Solution:** 

Suggesting Redisson makes connections via hostnames if available and default to IPs if not present. The fix would be to adjust the parsing logic in ClusterNodesDecoder to take into account hostnames as well.  

Any objections if I raise a PR to address this issue ?

**Comment by mrniko** [comment]
Oh, I see now. ip address + hostname isn't parsed. Only if there are only hostname or ip.

Sure, I'll consider a PR.

**Comment by mrniko** [comment]
Fixed. Thanks for report!
