### ISSUE TITLE
redissonClient.getAtomicLong(key).addAndGet(delta) ERR value is not an integer or out of range.

### ISSUE THREAD

**Issue by hanxiang-li** [redisson/redisson#6127]
### Redis version

7.2.4 macos

### Redisson version

3.35.0

### Redisson configuration

```
redis:
  config: |
    singleServerConfig:
      password: 
      address: "redis://localhost:6379"
      database: 3
```

```
    private static final RedissonClient redissonClient;

    static {
        RedissonClientOriginalSupplier originalSupplier = Solon.cfg().getBean("redis", RedissonClientOriginalSupplier.class);
        redissonClient = originalSupplier.withConfig(config -> {
            config.setCodec(new JsonJacksonCodec());
        }).get();
    }
    public static long increment(String key, long delta) {
// delta=1
        return redissonClient.getAtomicLong(key).addAndGet(delta);
    }
```

### What is the Expected behavior?

The value of the corresponding key increases

### What is the Actual behavior?

org.redisson.client.RedisException: ERR value is not an integer or out of range. channel: [id: 0x83e40da5, L:/127.0.0.1:60651 - R:localhost/127.0.0.1:6379] command: (INCRBY), params: [key, 1], promise: java.util.concurrent.CompletableFuture@5b3a9848[Not completed, 1 dependents]

Viewing the stored data as a string '1'

**Comment by mrniko** [comment]
Unable to reproduce.

```java
        Config c = createConfig();
        c.setCodec(new JsonJacksonCodec());

        RedissonClient r = Redisson.create(c);
        RAtomicLong al = r.getAtomicLong("test");
        assertThat(al.addAndGet(10)).isEqualTo(10);
```

**Comment by hanxiang-li** [comment]
[solon-test.zip](https://github.com/user-attachments/files/16790693/solon-test.zip)
Reproduce the code as above，

get - http://127.0.0.1:8000/captcha/test == ok
post - http://127.0.0.1:8000/captcha/get, parameter：captchaType=blockPuzzle == error
