### ISSUE TITLE
After the redisson version was upgraded, the memory usage became 2-3 times the original

### ISSUE THREAD

**Issue by bitkbitk** [redisson/redisson#6129]
Redisson version was upgraded from 3.11.1 to 3.14.0. Why did the memory usage become 2-3 times the original? After analysis, it was found that the default encoding changed from FstCodec to MarshallingCodec. Is this related?

**Comment by mrniko** [comment]
It might be. Both are buggy. Did you try Kryo5Codec?

**Comment by bitkbitk** [comment]
> Both are buggy

You mean the official recommendation is to use Kryo5Codec？

**Comment by mrniko** [comment]
Yes
