### ISSUE TITLE
memory leak 3.17.1

### ISSUE THREAD

**Issue by jmilktea** [redisson/redisson#6131]
### Redis version

5.0

### Redisson version

3.17.1

### Redisson configuration

Config config = new Config();
config.useSingleServer().setAddress("redis://" + host + ":" + port).setDatabase(database).setPassword(password);
redissonClient = Redisson.create(config);

### What is the Actual behavior?

this is mycode：
```
public class RedissonUtil {
    private final RedissonClient redissonClient;

    public RedissonUtil(RedissonClient redissonClient) {
        this.redissonClient = redissonClient;
    }

    public boolean tryLock(String lockKey, long waitTime, long expireTime, TimeUnit timeUnit) {
        RLock lock = this.redissonClient.getLock(lockKey);

        try {
            return lock.tryLock(waitTime, expireTime, timeUnit);
        } catch (InterruptedException var9) {
            Thread.currentThread().interrupt();
            return false;
        }
    }

    public void unlock(String lockKey) {
        RLock lock = this.redissonClient.getLock(lockKey);
        if (lock.isLocked() && lock.isHeldByCurrentThread()) {
            lock.unlock();
        }
    }
}
```

The code that caused the problem：
```
        String date = DateUtils.getFormatDate(SF_NO_SYMBOL);
        String redisKey = RedisUtils.generateKey(key, date);
        String lockKey = RedisUtils.generateKey(RedisKey.DeviceUuidLogs.DEVICE_UUID_GENERATE_REDIS_ID_LOCK, date);
        String incrementId = null;
        int retryCount = 0;
        
        try {
            while (StringUtils.isEmpty(incrementId) && retryCount < refreshScopeConfig.getTraceIdMaxRetries()) {
                if (redissonUtil.tryLock(lockKey, 50, 100, TimeUnit.MILLISECONDS)) {
                    //other code...

                    incrementId = String.format("%0" + length + "d", increment);
                }
                retryCount++;
            }
        } catch (Exception e) {
            return snowFlakeId();
        } finally {
            try {
                redissonUtil.unlock(lockKey);
            } catch (Exception e) {
                return snowFlakeId();
            }
        }

        return StringUtils.isEmpty(incrementId) ? snowFlakeId() : date + incrementId;
```

After the program has been running for a while, perhaps several days, the memory usage gradually increases, and it is observed that it is always in fullgc.
After I dumped the memory, I found that there were many redisson related objects and a memory leak occurred.
What is the problem？

![redisson-issue-1](https://github.com/user-attachments/assets/51238314-4dcb-430c-881b-9a32d0e92174)

Before the memory usage continued to increase, about a day ago, the redis server experienced network jitter. Is this related?
![image](https://github.com/user-attachments/assets/718ab126-a5d8-44fd-bbe4-7bf3e29193e5)

**Comment by jmilktea** [comment]
@mrniko please help

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/pull/5038 - too many pubsub topics may cause memory leak

You need to upgrade to 3.21.2 or higher

**Comment by jmilktea** [comment]
Could you tell me the details? Thanks @mrniko
