### ISSUE TITLE
Add method computeIfAbsent with TTL for RMapCache

### ISSUE THREAD

**Issue by mvkirillov** [redisson/redisson#6136]
RMapCache

https://www.javadoc.io/doc/org.redisson/redisson/3.3.2/org/redisson/api/RMapCache.html

Currently there is a computeIfAbsent method from ConcurrentMap. There are specific methods with TTL putIfAbsent and put. It would be great to have a computeIfAbsent method with the ability to set TTL.

Currently you have to call computeIfAbsent and then expireEntryIfNotSet, but if the application crashes after computeIfAbsent, the key will not have a TTL set

**Comment by mvkirillov** [comment]
Hi @mrniko , do you think it will be possible to implement it? If yes, when?

**Comment by mrniko** [comment]
Yes, it's possible. No schedule for now.

**Comment by lyrric** [comment]
Why not use fastPutIfAbsent? The mappingFunction can not be invoke in advance？

**Comment by mrniko** [comment]
merged
