### ISSUE TITLE
The RSetCache.tryAdd(long ttl, TimeUnit unit, V... values) method has been deprecated，which method can instead ?

### ISSUE THREAD

**Issue by lyrric** [redisson/redisson#6140]
redisson version：3.35.0 
I wanted to use RSetCache.tryAdd(long ttl, TimeUnit unit, V... values)  to lock multiy values, but i found it had been deprecated. and i can not find any method can  instead.

The documentation suggest to use {@link #addIfAbsent(Duration, Object)} instead, which is incorrect because the functionality of this method does not match the functionality of the deprecated method.

The method int addAllIfAbsent(Map<V, Duration> objects) can not instand .
- support multiy value 
- support ttl
- support all success or all fail

I hope to get  some suggestions，thanks.

**Comment by mrniko** [comment]
Merged
