### ISSUE TITLE
Redisson causing timeouts randomly 

### ISSUE THREAD

**Issue by sahilhindwani-harness** [redisson/redisson#6155]
Hi Team,

We encountered an issue with the Redisson library on one of our Azure clusters using redis sentinel, where we observed random timeouts occurring on a Redis instance that had no load. To verify this, we ran two applications—one in Go and the other using Redisson. The application with Redisson experienced random timeouts, whereas the Go application did not. We also tested with the Lettuce library and found no timeouts there either.

We are using the latest version of Redisson, and there is no load on Redis.

Here are the error logs we are receiving: 

`2024-08-28 05:56:43,707 [32m[redisson-timer-10-1][0;39m [39mDEBUG[0;39m [36morg.redisson.client.handler.ConnectionWatchdog[0;39m - reconnecting RedisConnection@901736170 [redisClient=[addr=redis://], channel=[id: 0xbcb5390f, L:/:57606 ! R:redis-sentinel-announce-2.staging.svc.cluster.local/:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7e78d17(failure: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 3 retry attempts. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (EVALSHA), params: [b8abd8c5j6518e08e31322574f10df3126860402a, 3, hCache/pmsMetricsCache, jcache_timeout_set:{hCache/pmsMetricsCache}, jcache_expired_channel:{hCache/pmsMetricsCache}, 1724824589309, 100], channel: [id: 0xbcb5390f, L:/:57606 - R:redis-sentinel-announce-staging.svc.cluster.local/172.16.147.161:6379])], command=(EVALSHA), params=[b8abd8c56518e0k8e31322574f10df3126860402a, 3, hCache/metricsCache, jcache_timeout_set:{hCache/metricsCache}, jcache_expired_channel:{hCache/metricsCache}, 1724824589309, 100], codec=org.redisson.client.codec.LongCodec]] to redis-sentinel-announce-2.staging.svc.cluster.local/:6379 [33m[0;39m`

We tried increasing the Netty threads, but the problem persists. Any insights would be greatly appreciated. Could this be due to network issues?

More details:

Redisson library Version:  3.35.0
We were using redis-sentinel, moving to azure cache fixes the issue but we wanted to understand as to what could be the reason for it failing randomly on redis-sentinel.
Java version - 17.0.7
Redis version - 6.2.14

**Comment by sahilhindwani-harness** [comment]
We are running this code to validate the failures: [HealthCheck](https://github.com/jasonmcintosh/bug-reports/blob/main/redisson-sentinel-perf-issues/src/main/java/io/harness/redis/tester/RedisHealthChecker.java)

We are able to see random failures even without any load on redis. 
Any help will be appreciated.

**Comment by mrniko** [comment]
It's a network issue since org.redisson.client.handler.ConnectionWatchdog makes "reconnecting ..." logs

**Comment by lasdox** [comment]
Hello @mrniko , im working with @sahilhindwani-harness debugging this issue.

When a network failure happens, is it expected that subsequent retries also would fail? From the log we can see that 3 retries happened with 1.5 second interval.

- does Redisson has any known integration problems with redis sentinel?
- does Redisson has any known problems with limited network bandwidth?

As Sahil pointed out, this issue does not happen when using go-redis or lettuce, so we are thinking it could be related to some config.

Things we have already tried:
- increasing netty threads
- increasing timeout
- changing pingConnectionInterval to happen more and less frequent
- providing more cpu/memory to redis instance

**Comment by mrniko** [comment]
Hello @lasdox,

> does Redisson has any known integration problems with redis sentinel?
does Redisson has any known problems with limited network bandwidth?

No

Did you try to reduce connections pool size?
