### ISSUE TITLE
Redisson 3.31.0 couldn't detect nodes IP changes after an Azure Redis failover

### ISSUE THREAD

**Issue by Alekseych4** [redisson/redisson#6158]
Azure Redis cache had a failover which resulted in lost connection and change of IP addresses for nodes.
Our client app tried to connect to Redis nodes three times (retryAttempts are set to 3) having following exceptions:

`org.redisson.client.RedisTimeoutException: Unable to acquire connection! java.util.concurrent.CompletableFuture@7d303a35[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size. Node source: NodeSource [...], command: (EVALSHA), params: [...] after 3 retry attempts|`

Afterwards, client tried to connect using stale IP addresses, hence couldn't recover from a failover. In parallel we made the CLUSTER NODES request from a console which was showing a different set of IPs in contrast to what our client tried to use for a connection. For around an hour we were seeing below exceptions until we decided to manually restart our service.

`org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=13622, addr=rediss://OLD_IP+PORT_BEFORE_A_FAILOVER, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.`

Btw, our client provides cluster host:port through nodeAddresses config parameter.

Is it something what was fixed in a recent version?

**Comment by mrniko** [comment]
I need Redisson logs with `trace` logging level

**Comment by Alekseych4** [comment]
Unfortunately, It happened on production, so there were no time to change log level and collect traces. 

The https://github.com/redisson/redisson/issues/5931 looks similar to me. Could you elaborate more on what was fixed there?

**Comment by mrniko** [comment]
> Unfortunately, It happened on production, so there were no time to change log level and collect traces.
> 
> The #5931 looks similar to me. Could you elaborate more on what was fixed there?

In some cases topology may return empty nodes list which causes next updates impossible.

**Comment by mrniko** [comment]
Can you try 3.32.0 version?

**Comment by Alekseych4** [comment]
We have updated to 3.36.0. I'll let you know if we find something
