### ISSUE TITLE
Why is optional dependency spring actuator mandatory in redisson-spring-boot-starter?

### ISSUE THREAD

**Issue by pingu8007** [redisson/redisson#6169]
We are not using actuator at the moment, and the actuator is optional in `org.redisson:redisson` package.
While investigating I found the `redisson-spring-boot-starter` has a mandatory dependency to `spring-boot-starter-actuator`. There is no actuator usage found in redisson starter.

Should this dependency optional to keep consistency? Or can I have the reason why is the dependency required?

**Comment by TsukasaHwan** [comment]
Yes, I agree.

**Comment by TsukasaHwan** [comment]
Yes, I'm in favor.
