### ISSUE TITLE
Can I use ConcurrentHashMap<Object, Object> for RLocalCachedMap instead of Map<CacheKey, CacheValue>?

### ISSUE THREAD

**Issue by lehuuthanh5** [redisson/redisson#6189]
Hi,

I'm trying to improve the performance of my application. I profiled my app and can see the RLocalCachedMap.get is taking CPU time to encode the key to CacheKey.
As the title, can I do it? Is there any potential issue there?

This is my RLocalCachedMap config
```
LocalCachedMapOptions LOCAL_CACHED_MAP_OPTIONS = LocalCachedMapOptions.defaults()
            .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
            .cacheSize(0)
            .syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE)
            .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.NONE)
            .writeMode(MapOptions.WriteMode.WRITE_BEHIND);
```
RedisClient config
```
config.useSentinelServers()
                .setMasterName("")
                .setPassword("")
                .setReadMode(ReadMode.SLAVE)
                .setSubscriptionMode(SubscriptionMode.SLAVE)
                .setKeepAlive(true)
                .setTcpNoDelay(true)
                .addSentinelAddress(redisUri)
                .setSubscriptionsPerConnection(getSubscriptionPerConnection())
                .setSlaveConnectionPoolSize(getSlaveConnection())
                .setMasterConnectionPoolSize(getMasterConnection());
```
Thanks

**Comment by mrniko** [comment]
Redis doesn't use equals, hashCode but serialized state for map entry lookup by key. This is why local cache uses the same principle.

**Comment by johnou** [comment]
What object are you using for the key? you could potentially improve things by simplifying the key object or changing the key encoder.

**Comment by lehuuthanh5** [comment]
Hi @mrniko ,
Thanks for the quick response. I mean the local cache behind the RedissonLocalCacheMap is `ConcurrentMap<CacheKey, CacheValue> cache;`. Can it be `ConcurrentMap<Object, Object> cache;`?
You replied on my thread [https://github.com/redisson/redisson/issues/5406#issuecomment-2100279108](link) before. 

> To avoid serializing the entire key key during cache invalidation.

However, I cannot reproduce this case with my configuration. Can you help me provide a test case to make the error?
Thanks

Hi @johnou 
Below is a simple test. We get better performance if we get the data directly from the ConcurrentHashMap.
```
RedissonClient client = client();
RLocalCachedMap<Object, Object> localCachedMap = client.getLocalCachedMap("test-cache", new KryoCodec(List.of(Object.class)), LocalCachedMapOptions.defaults()
        .evictionPolicy(LocalCachedMapOptions.EvictionPolicy.NONE)
        .cacheSize(0)
        .syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE)
        .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.NONE)
        .writeMode(MapOptions.WriteMode.WRITE_BEHIND));
long start = System.currentTimeMillis();
Map<Object, Object> cachedMap = localCachedMap.getCachedMap();
for (int i = 0; i < 10000; i++) {
    cachedMap.get(new Object());
}
System.out.printf("getCachedMap.get() takes time: %sms%n", System.currentTimeMillis() - start);
start = System.currentTimeMillis();
Map<Object, Object> cHashMap = new ConcurrentHashMap<>();
for (int i = 0; i < 10000; i++) {
    cHashMap.get(new Object());
}
System.out.printf("concurrentHashMap.get() takes time: %sms%n", System.currentTimeMillis() - start);
```
and the result is
```
getCachedMap.get() takes time: 120ms
concurrentHashMap.get() takes time: 1ms
```
Let's take a look on getCachedMap().get() implementation
```
public V get(Object key) {
    CacheKey cacheKey = toCacheKey(key);
    CacheValue e = cache.get(cacheKey);
    if (e != null) {
        return (V) e.getValue();
    }
    return null;
}
```
The difference from ConcurrentHashMap.get is this line code `CacheKey cacheKey = toCacheKey(key);`. But this will make the slow here.
Thanks alot.

**Comment by lehuuthanh5** [comment]
Hi @johnou, in my test case, you can see before I get value from RLocalCacheMap, I have this line code `Map<Object, Object> cachedMap = localCachedMap.getCachedMap();`, I try to get value from the cached map and this will not hit Redis. It only gets data from the local cache
