### ISSUE TITLE
Command execution timeout for command: (PING)

### ISSUE THREAD

**Issue by admincopm** [redisson/redisson#6190]
Hello, when I was in use or the problems: org. Redisson. Client. RedisTimeoutException: Command execution the timeout for the Command: (PING), params: [], Redis client: [addr=redis://127.0.0.1:6379] 
Redisson version:
3.17.6
springboot.version
2.7.1
![image](https://github.com/user-attachments/assets/8d030461-8969-4a28-aa19-8c8d41393d9b)
 
What is strange is that I have no problem running in the normal mode of Intellij idea, but this problem occurs when I run the project in the debug mode. I don't know what causes it. If you know some reasons, could you please tell me some possible reasons

**Comment by mrniko** [comment]
You need to upgrade to 3.26.1 version or higher

**Comment by strelchm** [comment]
We have 3.45.0 version and have such errors sometimes, but the are no problems with other commands (when we had old version we  have had such error with SENTINEL commands)
