### ISSUE TITLE
Incorrect validation of idleTime instead of minIdleTime in xClaim command causing NPE

### ISSUE THREAD

**Issue by jinia91** [redisson/redisson#6192]
### Redis version

7.0

### Redisson version

3.36.0

### Redisson configuration

plain

### What is the Expected behavior?

In the xClaim command of Redisson, the validation is incorrectly applied to the idleTime parameter instead of the minIdleTime parameter, leading to a NullPointerException (NPE). This issue arises when using the xClaim command with minIdleTime as intended, causing unexpected failures.

### What is the Actual behavior?

work xclaim

### Additional information

```kotlin
            redisTemplate.opsForStream<String, String>()
                .claim("stream-key", "group", "consumer1", java.time.Duration.ofMillis(1000), it.id)
```

![image](https://github.com/user-attachments/assets/bdee445f-c3a9-4576-a988-dc7692d81459)

**Comment by mrniko** [comment]
merged
