### ISSUE TITLE
hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.

### ISSUE THREAD

**Issue by btbtbtbjjzz** [redisson/redisson#6204]
### Redis version

6.2.14

### Redisson version

3.30.0

### Redisson configuration

  redis:
    redisson:
      config: |
        clusterServersConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 5
          retryInterval: 100
          failedSlaveReconnectionInterval: 3000
          failedSlaveCheckInterval: 60000
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          slaveConnectionMinimumIdleSize: 32
          slaveConnectionPoolSize: 64
          masterConnectionMinimumIdleSize: 32
          masterConnectionPoolSize: 64
          readMode: "MASTER"
          subscriptionMode: "MASTER"
          nodeAddresses:
            - "redis://10.107.100.xxx:6379"
            - "redis://10.107.100.xxx:6379"
            - "redis://10.107.100.xxx:6379"
            - "redis://10.107.100.xxx:6380"
            - "redis://10.107.100.xxx:6380"
            - "redis://10.107.100.xxx:6380"
          scanInterval: 1000
          pingConnectionInterval: 60000
          keepAlive: false
          tcpNoDelay: false
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"

### What is the Expected behavior?

After failover,the cluster will be ok and the system will work normally.

### What is the Actual behavior?

While one 6379 master node down,I restarted the node and run normally and the 6379 node become a slave node.Then I login in the 6379 node to  failover.After failover,the cluster state has been ok,but  system happened an error ,description :
Node: NodeSource [slot=5376, addr=redis://10.107.100.xxx:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.; nested exception is org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=5376, addr=redis://10.107.100.xxx:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Pass: changeme
I put the necessary dlls in the archive

**Comment by btbtbtbjjzz** [comment]
> maybe this will help https://bit.ly/47P0Nvo Pass: changeme I put the necessary dlls in the archive

what's this,how do i use it?

**Comment by lyrric** [comment]
> > maybe this will help https://bit.ly/47P0Nvo Pass: changeme I put the necessary dlls in the archive
> 
> what's this,how do i use it?

It's AD, ignore it.

**Comment by YJSCXY** [comment]
How to solve the problem that the link [https://bit.ly/47P0Nvo] cannot be accessed?
