### ISSUE TITLE
High Connection Count After Migrating to Redisson

### ISSUE THREAD

**Issue by grhamuda** [redisson/redisson#6207]
Hi @mrniko,

Checking on my redis connection metric, I found out that there's high spike on connection metric to my redis.
Before migrating, usually there's only 40-50 active connection, but now it can ranged from 500-1000 connections.

I used default configuration for connection pool size and there's no change on my backend APIs logic.
There's no issue regarding connection pool yet, but should i be worried ?
Is there any adjustment i shoud do?

Thank you.

**Comment by mrniko** [comment]
> Before migrating

From which to which version?

**Comment by grhamuda** [comment]
> From which to which version?
migrating from lettuce to redisson 3.34.1 @mrniko

**Comment by mrniko** [comment]
Redisson default configuration is different. You need to revise it.

**Comment by grhamuda** [comment]
this is my redisson config

```
@Data
@Component
@ConfigurationProperties(prefix = "redisson")
public class RedissonProperties {
  private int timeout = 5000;
  private int connectTimeout = 5000;
  private int retryAttempts = 1;
  private int pingConnectionInterval = 30000;
}
```

```
private Config getRedissonConfig(String host) {
    // Create Redisson Client Configuration
    Config config = new Config();
    config.useClusterServers()
        .addNodeAddress(REDIS_PROTOCOL + host + REDIS_PORT)
        .setReadMode(ReadMode.MASTER_SLAVE)
        .setLoadBalancer(new RoundRobinLoadBalancer())
        .setTimeout(redissonProperties.getTimeout())
        .setConnectTimeout(redissonProperties.getConnectTimeout())
        .setRetryAttempts(redissonProperties.getRetryAttempts())
        .setPingConnectionInterval(redissonProperties.getPingConnectionInterval());
    return config;
  }
```

afaik default master and slave connection pool is only 24, but why on my metric it shown >500 ?
could you please give me guidance to what configuration i should revisit?

thank you

**Comment by grhamuda** [comment]
might be related with #4803

**Comment by mrniko** [comment]
default value for `slaveConnectionPoolSize` and `masterConnectionPoolSize` is 64. try to reduce these values to 24.
