### ISSUE TITLE
Redisson master slave mode and kubernetes headless service for slaves

### ISSUE THREAD

**Issue by jhamalainen** [redisson/redisson#6214]
Should it be possible to use kubernetes headless service for slave connections when using Redisson in master slave mode?

I tried that but I see all the time this kind of logs:

05.10.2024 18:05:59.274 [INFO] org.redisson.connection.DNSMonitor Detected DNS change. Slave redis-replicas.test.svc.cluster.local has changed ip from x.x.x.x to y.y.y.y
05.10.2024 18:05:59.284 [INFO] org.redisson.connection.ConnectionsHolder 1 connections initialized for redis-replicas.test.svc.cluster.local/y.y.y.y:6379]
05.10.2024 18:05:59.538 [INFO] org.redisson.connection.ConnectionsHolder 24 connections initialized for redis-replicas.test.svc.cluster.local/y.y.y.y:6379]

The ips in the log messages  are the actual pod ips, which you get from the headless service. 

The configuration for the slaveAddresses:
"slaveAddresses": [
      "rediss://redis-replicas.test.svc.cluster.local:6379"
    ],

**Comment by mrniko** [comment]
You need to use a single mode https://redisson.org/docs/configuration/#single-mode

**Comment by mrniko** [comment]
You need to upgrade to 3.32.0 version or higher
