### ISSUE TITLE
What config to use for multi-master replication?

### ISSUE THREAD

**Issue by arulned** [redisson/redisson#6221]
We are using keydb(redis fork) servers with multi-master setup: https://docs.keydb.dev/docs/multi-master/
The catch is that the keydb endpoint is a DNS name that resolves to 3 IPs of the underlying master nodes which are replicated with each other.
What is the config type to use when connecting to the endpoint? ReplicatedServerConfig or MasterSlaveConfig or something else. I feel like I should use the ReplicatedServerbut worried that that I would end up in a loop because the each master is listed as a slave of the other two in the CLUSTER INFO command. Any help is greatly appreciated.

**Comment by mrniko** [comment]
https://redisson.org/docs/configuration/#proxy-mode
