### ISSUE TITLE
Eagerly trying to connect to running redis server

### ISSUE THREAD

**Issue by zenith7781** [redisson/redisson#6230]
Hi, I have a spring boot project (spring boot version 3.2.10) with redisson 3.17.1 initially. Whenever the server used to start, it used to connect to a running redis server only when the value of "spring.cache.type" was redis in application.properties file. But since my upgradation to 3.30.0, it tries to connect to running redis server even if the spring.cache.type value is something else or the property isn't there at all. Can anyone please highlight the exact release and the documentation where this eager nature of connecting to redis server is mentioned? 
@mrniko Any guidance will be appreciated.

**Comment by mrniko** [comment]
You can disable it. https://redisson.org/docs/integration-with-spring/#faq

**Comment by zenith7781** [comment]
Hi @mrniko, I am aware of disabling redisson at runtime. My question was from which release the redisson was trying to eagerly connect during spring boot startup ? Or is this behaviour present from the starting (1st release) of redisson?.... Thanks..

**Comment by mrniko** [comment]
It's the default behavior. It doesn't depend on `spring.cache.type`
