### ISSUE TITLE
Intercept Redis Commands

### ISSUE THREAD

**Issue by skincer** [redisson/redisson#6235]
Would there be a way to intercept (for logs, metrics, analysis) the actual commands sent to Redis in code (Spring) beyond simply setting the log level to DEBUG? Would we look at AOP around the RedisExecutor class perhaps?

Thanks in advance for any suggestions.

**Comment by mrniko** [comment]
There are not only commands but a lot of scripts. You can consider using these metrics: https://redisson.org/docs/observability/
