### ISSUE TITLE
How do I remove elements from redis map when they expire, not only local cache?

### ISSUE THREAD

**Issue by fodded** [redisson/redisson#6237]
I use Redisson 3.26.1 and I have been attempting to make RLocalCachedMap remove elements from local cache and redis at the same time. I figured out that if I apply timeToLive and maxIdle settings to LocalCachedMapOptions, it only affects cached map implementation, but the element is still shared among RLocalCachedMap map instances.

Here is something of what I've already tried, I believe that there is a setting available to remove elements from redis when they expire.
```
private final RLocalCachedMap<String, UUID> generatedCodes;

LocalCachedMapOptions<String, UUID> options = LocalCachedMapOptions.<String, UUID>name("test")
                .storeMode(LocalCachedMapOptions.StoreMode.LOCALCACHE_REDIS)
                .cacheProvider(LocalCachedMapOptions.CacheProvider.REDISSON)
                .reconnectionStrategy(LocalCachedMapOptions.ReconnectionStrategy.CLEAR)
                .writeMode(WriteMode.WRITE_BEHIND)
                .cacheSize(0)
                .writeRetryAttempts(5)
                .timeToLive(Duration.ofMillis(300))
                .maxIdle(Duration.ofMillis(300))
                .syncStrategy(LocalCachedMapOptions.SyncStrategy.UPDATE);
generatedCodes = redisson.getLocalCachedMap(options);```

**Comment by mrniko** [comment]
You need to use getLocalCachedMapCache() which is part of PRO version.

**Comment by dtshit** [comment]
@mrniko I think this is a poor design. To set the initial expiration time, you need to add a meaningless element, and you can't even delete it immediately after adding it. I also found that when the elements in the Map are cleared, the corresponding Key in Redis is also deleted. Suppose I need the Map structure to expire within a limited time—no matter what modifications are made during that period—then I need to set its expiration time when creating this Map. If the Map is cleared during use, it will cause the expiration time to be refreshed the next time it is used.

我认为这是一个糟糕的设计，为了设置初始的过期时间，需要添加一个无意义的元素，甚至不能添加后立刻删除。因为我还发现当Map中的元素清空后，Redis中对应的Key也会被删除。假设我需要Map结构需要限定时间内过期——无论期间做出什么修改，那么我需要在创建这个Map的时候就设置它的过期时间。如果Map在使用过程中被清空，就会导致下一次使用时重新刷新过期时间。
