### ISSUE TITLE
Client unable to discover new slaves after node type upgrade

### ISSUE THREAD

**Issue by Gaurang-nits** [redisson/redisson#6243]
Our cache cluster has 1 shard with 2 read replicas.

Expected behavior
When the Redis cluster node type got upgraded in aws(elastic cache for redis), it will update the cluster with new node type and IPs. After the replacement client should be able to discover the new nodes(master and slave) again.

Actual behavior
Redisson client is unable to discover the new slave nodes. And it is still trying to connect to old read replicas.

We are seeing below logs in output-
```
Address: <IP Address of Old Read Replica>:<Redis Port>
Command execution timeout (1000ms) for command: PING, Redis client: [addr=rediss://<IP Address of Old Read Replica>:<Redis Port>]
```

**Comment by mrniko** [comment]
Which Redisson version?
Can you share the logs with `trace` logging level for `org.redisson` from application start moment till the failover?

**Comment by Gaurang-nits** [comment]
@mrniko We are using 3.37.0 version of Redisson.
We didn't had `trace` logging level for `org.redisson` enabled from application so unfortunately we won't have the log from the live environment. 
I am trying to check if i can reproduce the same in development or local env.

**Comment by Gaurang-nits** [comment]
I was not able to reproduce in Dev environment. Also no logs published in trace mode for `org.redisson`.

**Comment by mrniko** [comment]
> Also no logs published in trace mode for org.redisson.

You need to make sure that logger is setup properly

**Comment by mrniko** [comment]
Any update?
