### ISSUE TITLE
Redisson reconnection error ?

### ISSUE THREAD

**Issue by Breathtak** [redisson/redisson#6247]
k8s cluster deployment  java service（user Redisson connection redis cluster），has 6 nodes ，this 6 nodes tarted successfully and run for some time ,suddenly two nodes connection error，other 4 nodes are running properly. this two nodes reconnection fail.
error mesage as follow:
`
Caused by: org.redisson.client.RedisNodeNotFoundException: Node: NodeSource [slot=392, addr=redis://10.233.66.20:6379, redisClient=null, redirect=MOVED, entry=null] hasn't been discovered yet. Increase value of retryAttempts and/or retryInterval settings.
`

**redisson config as follow:**

`

   @Primary
   @Bean
    private Redisson create(){
        log.info("Redisson init start...");

        List<String> clusterNodes = new ArrayList<>();
        for (int i = 0; i < redisProps.getCluster().getNodes().size(); i++) {
            clusterNodes.add("redis://" + redisProps.getCluster().getNodes().get(i));
        }
        Config config = new Config();
        ClusterServersConfig clusterServersConfig = config.setConnectionListener(new RedissonConnectionListener())
                .useClusterServers()
                .setReadMode(ReadMode.MASTER)
                .setSubscriptionMode(SubscriptionMode.MASTER)
                .addNodeAddress(clusterNodes.toArray(new String[clusterNodes.size()]));
        clusterServersConfig.setPassword(redisProps.getPassword())
                .setTimeout(redisProps.getTimeout());
        return (Redisson) Redisson.create(config);
    }
`

`
@Data
@Component
@ConfigurationProperties(prefix = "spring.redis")
public class RedisProps {
    /**
     * timeout
     */
    private Integer timeout;
    /**
     * password
     */
    private String password;
    /**
     * cluster nodes
     */
    private Cluster cluster;

    public static class Cluster {
        private List<String> nodes;

        public List<String> getNodes() {
            return nodes;
        }

        public void setNodes(List<String> nodes) {
            this.nodes = nodes;
        }
    }
}
`

**yml as follow:**

`
spring:
  cache:
    type: redis
  redis:
    cluster:
      nodes:  ${REDIS_CLUSTER}
    timeout: 15000
`

**Comment by mrniko** [comment]
Can you set `trace` logging level for `org.redisson` package and share output since the application start moment?
