### ISSUE TITLE
Regarding org.redisson.client.RedisException: java.lang.InterruptedException

### ISSUE THREAD

**Issue by mailniranjan** [redisson/redisson#6253]
I am using Redisson session tomcat manager to save session information in redis. When doing session.getAttribute, we are facing the below problem.

org.redisson.client.RedisException: java.lang.InterruptedException
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:180)
	at org.redisson.RedissonObject.get(RedissonObject.java:94)
	at org.redisson.RedissonMap.get(RedissonMap.java:597)
	at org.redisson.tomcat.RedissonSession.getAttribute(RedissonSession.java:121)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:101)

Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:176)
	... 30 more"

Redisson version: 3.33.0

Tomcat version: 9.0.94

Netty version: 4.1.66.Final

Redisson configuration yaml file:

---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  subscriptionTimeout: 7500
  retryAttempts: 3
  retryInterval: 1500
  password: "..."
  credentialsResolver: !<org.redisson.client.DefaultCredentialsResolver> {}
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  sslTruststore: "..."
  sslTruststorePassword: "..."
  pingConnectionInterval: 30000
  keepAlive: false
  tcpKeepAliveCount: 0
  tcpKeepAliveIdle: 0
  tcpKeepAliveInterval: 0
  tcpUserTimeout: 0
  tcpNoDelay: true
  nameMapper: !<org.redisson.api.DefaultNameMapper> {}
  commandMapper: !<org.redisson.config.DefaultCommandMapper> {}
  address: "rediss://..."
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.Kryo5Codec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: true
slavesSyncTimeout: 1000
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> {}
lazyInitialization: false
protocol: "RESP3"

Please help me to troubleshoot the issue.

Please look at the log from bottom to top.

[Redisson-Netty-Trace-logs.log](https://github.com/user-attachments/files/17539741/Redisson-Netty-Trace-logs.log)

**Comment by mrniko** [comment]
It means that Tomcat threads are interrupted for some reason
