### ISSUE TITLE
[Spring] RedisCacheManager @Cacheable sync parameter not working with reactive types (mono) or completableFuture

### ISSUE THREAD

**Issue by mvkirillov** [redisson/redisson#6256]
### Redis version

latest

### Redisson version

3.37.0

### Redisson configuration

Redisson bean from spring boot autoconfiguration 
Redis in docker, signle node

### What is the Expected behavior?

First concurrently request takes lock, evaluates method, and other requests reuse cached data

### What is the Actual behavior?

Method return Mono<String> + @Cacheable(sync = true) or CompletableFuture<String> + @Cacheable(sync = true) 
when more 1 concurrently request method, then all stucking

### Additional information
spring boot 3.3.5

    @Bean
    @Primary
    CacheManager redissonCacheManager(RedissonClient redissonClient) {
        Map config = new HashMap<>();

        // create "testMap" spring cache with ttl = 24 minutes and maxIdleTime = 12 minutes
        config.put("testMap", new CacheConfig(24 * 60 * 1000, 12 * 60 * 1000));
        return new RedissonSpringCacheManager(redissonClient, config);
    }   

 // RedisUseCase.java
    @Cacheable(
            cacheNames = "example",
            cacheManager = "redissonCacheManager",
            sync = true
    )
    public Mono<String> withCaching() {
        return longActionUseCase.getMono();
    }

// LongActionUseCase.java
    public Mono<String> getMono() {
        return Mono.delay(Duration.ofSeconds(1))
                .map(i -> "Hello world")
                .log();
    }

Test

    @SpyBean
    LongActionUseCase spyCase;

    @Test
    void redissonReactiveTest() {
        int count = 2;

        List<Mono<String>> answers = new ArrayList<>(count);

        IntStream.range(0, count).forEach(i -> answers.add(
                        redisUseCase.withCaching()
                )

        );

        // await all
        Flux.fromIterable(answers)
                .flatMap(Function.identity())
                .then()
                .onErrorContinue((throwable, o) -> {
                    //just ignore it we've already caught all errors
                })
                .block();

        Mockito.verify(spyCase).getMono();
    }

------------------
When method return String, then @Cacheable(sync = true) working correctly

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by mvkirillov** [comment]
@mrniko There is no more hang. However, if you run 100 threads in parallel at the same time, the method will be called 100 times

**Comment by mvkirillov** [comment]
@mrniko I think you can't use the thread ID as an ID in this case, because in the case of reactive, the same thread can be used. You need to use a random number may be?
