### ISSUE TITLE
[Spring] RedisCacheManager @Cacheable sync parameter not working with reactive types (mono) or completableFuture v2

### ISSUE THREAD

**Issue by mvkirillov** [redisson/redisson#6257]
### Redis version

latest

### Redisson version

3.38.0

### Redisson configuration

same with previous issue https://github.com/redisson/redisson/issues/6256

### What is the Expected behavior?

There is no more hang. However, if you run 100 threads in parallel at the same time, the method will be called 100 times

I think you can't use the thread ID as an ID in this case, because in the case of reactive, the same thread can be used. You need to use a random number may be?

### What is the Actual behavior?

First concurrently request takes lock, evaluates method, and other requests reuse cached data

### Additional information

https://github.com/redisson/redisson/issues/6256

previous issue

**Comment by mrniko** [comment]
Good point. Fixed
