### ISSUE TITLE
Extremely high CPU utilization and eviction failures with `RMapCache`

### ISSUE THREAD

**Issue by SHxKM** [redisson/redisson#6269]
**version:** `org.redisson:redisson:3.25.2`

We are using Redisson's per-key expiry mechanism with `RMapCache`. Below is some more details, code snippet, and configurations. Any help is appreciated.

- Using `ReplicatedServersConfig` with AWS ElastiCache, 2 nodes, we are witnessing close 100% Engine CPU utilisation at all times. Also, we get the following exception: `[KEY]'...Increase connection pool size`. However, I'm not sure increasing the connection pool size will help when CPU is already at 100%?
- I'm wondering if this has to do with the fact that we are connecting to this server from two clients (two microservices - one only actually reads data), which may be taxing the Redis engine a bit too much in terms of contention on the eviction process that Redisson manages?
- Is Redisson OK with two microservices/clients using the RMapCache and there evictions attempted from of those clients (we see the errors and exceptions on both microservices that reference this `RMapCache`)
- When we saw the ElastiCache cluster was at 100% CPU, we doubled its size since we thought this is just due to scale, but the new ElastiCache cluster, which had double the CPU, also quickly reached 100% CPU.
- ElastiCache connections show about **3K** connections (I'm starting to suspect this, but Redisson suggest _increasing_ the connection pool size, confused...). Database capacity is < 10%.

Relevant default overrides:

```
subscriptionConnectionMinimumIdleSize: 25
nettyThreads: 128
subscriptionConnectionPoolSize: 100
masterConnectionPoolSize: 128
```

relevant code snippet:

```java
private static final LZ4Codec redissonCodec = new LZ4Codec();
RMapCache<String, String> map = redisClient.getMapCache(mapKey, redissonCodec);

map.putAllAsync(val, ttlMillis, TimeUnit.MILLISECONDS).thenRun(() -> {
    Duration hashExpiryDuration = Duration.of(960000 * 2, ChronoUnit.MILLIS); // 16 minutes
    map.expire(hashExpiryDuration);
});
```

Any ideas how to alleviate this?

**Comment by mrniko** [comment]
Can you upgrade to 3.37.0? It contains this fix: `Fixed - 100% CPU usage by CommandsQueue in rare cases`

**Comment by SHxKM** [comment]
> Can you upgrade to 3.37.0? It contains this fix: `Fixed - 100% CPU usage by CommandsQueue in rare cases`

Thanks! I will try. In case it's not that, any of the other parameters stand out?

**Comment by mrniko** [comment]
you can try to increase `minCleanUpDelay` parameter

**Comment by SHxKM** [comment]
Unfortunately upgrading to `3.37.0` did not help. Cluster even after doubling the size is still at close to 100% Engine CPU utilization. Something that did help a bit with reducing the errors is reducing the # of connections from around 3.5k to 2.5k (several microservice with multiple pods each).

I will also try to increase minCleanupDelay. I guess at scale per key expiry is just hard, or should it be scalable?

**Comment by mrniko** [comment]
the putAll() method can take a lot of time to execute. Did you try to put data with smaller chunks?

**Comment by mrniko** [comment]
Also try to set `useScriptCache` = `true`

**Comment by SHxKM** [comment]
> the putAll() method can take a lot of time to execute. Did you try to put data with smaller chunks?

Thanks. Your hypothesis that the CPU pressure comes from writes and not the eviction task?

> Also try to set useScriptCache = true

Will read up on this as well. Thanks.

**Comment by SHxKM** [comment]
> Also try to set `useScriptCache` = `true`

Unfortunately this did not help either.

> the putAll() method can take a lot of time to execute. Did you try to put data with smaller chunks?

I think I will try this next

**Comment by SHxKM** [comment]
> the putAll() method can take a lot of time to execute. Did you try to put data with smaller chunks?

@mrniko Unfortunately this seems to have an opposite effect.  We still see many eviction errors, and CPU utilization is very high.

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/814abebe-aab8-4e4d-951f-db98f6a74ae4">


We have tried so far:

- `useScriptCache = true`
- Upgrading to `3.37.0`
- Doubling `minCleanUpDelay` from `5` to `10`

@mrniko are there any other parameters I can use? maybe I have too many/too few resources?

Here are the default overrides (some names MAY be different, but they are assigned correctly):

```yml
subscriptionConnectionMinimumIdleSize: 25 # default is 1
nettyThreads: 128 # default is 32
subscriptionConnectionPoolSize: 75 # default is 50
masterConnectionPoolSize: 100 # default is 64
minCleanUpDelay: 10 # default is 5
useScriptCache: true
```

And maybe using this smart single-key expiration is not suitable for high throughput?

**Comment by mrniko** [comment]
> And maybe using this smart single-key expiration is not suitable for high throughput?

@SHxKM 
I would offer you to try RMapCacheV2 which is part of PRO version and handles expiration on Redis side. This reduces CPU load on Engine. As option you can try RMapCacheNative but it requires Redis 7.4

**Comment by SHxKM** [comment]
> > And maybe using this smart single-key expiration is not suitable for high throughput?
> 
> @SHxKM I would offer you to try RMapCacheV2 which is part of PRO version and handles expiration on Redis side. This reduces CPU load on Engine. As option you can try RMapCacheNative but it requires Redis 7.4

Thanks. We will consider `RMapCacheV2` after I take a look at pricing, how much better is it?
Regarding `RMapCacheNative`, unfortunately AWS ElastiCache does not support that. Do you think there are no more optimizations to try? what about `threads`, or other parameters?

Also, do you think the problem now lies mostly with the eviction task itself, or the writing to the map?

**Comment by mrniko** [comment]
@SHxKM 

> Thanks. We will consider RMapCacheV2 after I take a look at pricing, how much better is it?

Email at sales@redisson.pro

> Also, do you think the problem now lies mostly with the eviction task itself, or the writing to the map?

Some customers notice about 60% lower CPU load and halving nodes amount.

**Comment by CJRMedeiros123** [comment]
Hello @SHxKM do you have sucess to fix?
