### ISSUE TITLE
How can we print connection pool statistics

### ISSUE THREAD

**Issue by ramazangirgin** [redisson/redisson#6277]
For investigating the following Kubernetes - Redis cluster connection issue with redisson,

`java.util.concurrent.CompletableFuture@6b13e4ea[Completed exceptionally: java.util.concurrent.CancellationException]Increase connection pool size. Node source: NodeSource [slot=3053, addr=null, redisClient=null, redirect=null, entry=null], command: (HMSET), params: [[114, 101, 100, 105, 115, 115, 111, 110, 58, 115, ...], [108, 97, 115, 116, 65, 99, 99, 101, 115, 115, ...], [-84, -19, 0, 5, 115, 114, 0, 14, 106, 97, ...]] after 3 retry attempts`,

we want to see/log connection pool statistics from the redisson client.

Yes, we can enable logging for all org.redisson to see acquiered / released connection logs but this still doesn't provide information regarding redisson connection pool status. ( ref https://github.com/redisson/redisson/issues/3565 )

We want to have better way to see the pool statistics for investigating the issue.

Thanks in advance
Ramazan

**Comment by mrniko** [comment]
connection metrics are available here: https://redisson.org/docs/observability/#metrics-list

**Comment by ramazangirgin** [comment]
@mrniko so you mean without [Redisson PRO](https://redisson.pro/), we can not have Connection metrics, right ?

**Comment by vipul-mykaarma** [comment]
@mrniko any updates ?
