### ISSUE TITLE
redisson-spring-boot-starter当redis链接中LVS机器部分链接挂掉以后无法主动剔除异常链接。

### ISSUE THREAD

**Issue by hubalong** [redisson/redisson#6289]
### Redis version

3.17.0

### Redisson version

3.17.0

### Redisson configuration

spring:
  redis:
    host: 127.0.0.1
    port: 5105
    password: XXX

### What is the Expected behavior?

期望redssion可以感知哪些链接失效并且主动剔除，而不是等待系统tcp链接机制剔除链接。

### What is the Actual behavior?

redisson使用单节点singleServer模式，rediss链接对应的LVS中一个节点挂掉对应的请求不可用，此时redisson客户端发送超时。例如对应的channelId=123 请求异常，期望是将channelId=123 链接被剔除连接池。实际表现是链接始终存在，等待系统tcp链接的超时剔除以后客户端才正常。
可以通过netstat 查看端口对应的下游链接，发现异常链接始终存在。如果我们tcp超时链接参数设置的是15min超时，我们redisson客户需要等待15min后才会恢复正常。请问我们有相关设置可以保证链接发生异常以后被提出连接池吗？

**Comment by lyrric** [comment]
redisson客户端发送超时有可能是网络一时波动导致的，如果此时马上就将链接移除掉，可能会丢了西瓜捡了芝麻。

**Comment by mrniko** [comment]
You can reduce ping
