### ISSUE TITLE
RSetMultimap not creating entry in main structure when getting one of the inner RSet 

### ISSUE THREAD

**Issue by davidreis97** [redisson/redisson#6294]
### Redis version

7.2.5

### Redisson version

3.38.1

### Redisson configuration

Basic cluster config:

```java
Config config = new Config();
config.useClusterServers()
         .addNodeAddress("redis://127.0.0.1:8000", "redis://127.0.0.1:8001","redis://127.0.0.1:8002",
                "redis://127.0.0.1:8003", "redis://127.0.0.1:8004", "redis://127.0.0.1:8005","redis://127.0.0.1:8006",
                "redis://127.0.0.1:8007", "redis://127.0.0.1:8008", "redis://127.0.0.1:8009");
```

### What is the Expected behavior?

When getting a RSet from the RSetMultimap, I would expect it to be created in the main data structure. Since it isn't created, the following strange behaviour happens:

```java
RedissonClient redisson = Redisson.create(config);

RSetMultimap<String, String> multimap = redisson.getSetMultimap("multi");

String setName = multimap.get("set").getName();
redisson.getSet(setName).add("Hello World");

// Expected: [set] Actual: []
System.out.println(multimap.readAllKeySet());
```

### What is the Actual behavior?

No entry in the main RSetMultimap Redis structure is created.

### Additional information

I would create the entry in the main structure when `multimap.get("set")` happens. 

@mrniko Let me know your opinion on this, I would love to contribute if you also feel this makes sense.

**Comment by davidreis97** [comment]
Thinking about this further, I think another option could be to have a "touch" operation where the entry is created in the main hash. Currently we've solved this by doing a `multimap.put("set", "")` which is not ideal.

**Comment by mrniko** [comment]
`getSet()` isn't compatible with `getSetMultimap()` If you use RSetMultimap object then you need to interact with only through its interface and RSet.

**Comment by davidreis97** [comment]
Understood! 

In our use case, we have an `RSetMultimap` that is constantly being queried. When we need to update one of its sets, we create a separate temporary set, populate it with the new data, and then replace the existing set within the `RSetMultimap` using the `RENAME` command. 

Is there a way to perform this update using the current `RSetMultimap` API, without `getSet()`, so that the main `RSetMultimap` structure is properly updated?

**Comment by davidreis97** [comment]
Of course!

```java
RedissonClient redisson = Redisson.create(config);

RSetMultimap<String, String> multimap = redisson.getSetMultimap("multi");
String setName = multimap.get("set").getName();

// Update a temporary set to avoid disturbing production data
RSet<String> tmpSet = redisson.getSet(setName + ":tmp");
tmpSet.add("entry");

// Rename the temporary data-structure to the final set
tmpSet.rename(setName);

// Expected: [set] Actual: []
System.out.println(multimap.readAllKeySet());
```

**Comment by mrniko** [comment]
Did you use `RMultimap.replaceValues()` method?

**Comment by davidreis97** [comment]
`replaceValues` is multiple orders of magnitude slower, as the structures we're replacing are quite big. That's why we're ensuring that the temporary structure is on the same partition as the final one and doing a `RENAME`.

**Comment by mrniko** [comment]
I guess this is due to result. It returns previous values. I can introduce a new method to resolve that

**Comment by davidreis97** [comment]
Indeed it is! That would be great. I'm happy to contribute if I can help.

**Comment by mrniko** [comment]
Sure, contributions are always welcome! The new method should return void.
