### ISSUE TITLE
Some version conflict issues asked

### ISSUE THREAD

**Issue by Noel443** [redisson/redisson#6306]
My jdk version is 1.8.241, spring boot version is 2.6.6, and redisson-spring-boot-starter version is 3.38.1. The production boot was successful. But once you access redis through redisson, java.lang.NoClassDefFoundError appears: Could not initialize class org. Redisson. Spring.. The data connection. RedissonConnection, want to ask is how to return a responsibility? I checked the version documentation and found that I need to upgrade to spring boot3.x.Can I fix this problem without upgrading the spring boot version? Because 3.38.1 has some features that will be used

**Comment by mrniko** [comment]
you need to exclude redisson-spring-data-xx dependency from redisson-spring-boot-starter and add redisson-spring-data-26
