### ISSUE TITLE
Redisson hibernate entity cache TTL and MaxIdleTime not being set - default region used for entities 2nd level cache

### ISSUE THREAD

**Issue by abdulwhd964** [redisson/redisson#6309]
### Redis version

latest from Docker

### Redisson version

3.20.1

### Redisson configuration

hibernate.cache.redisson.entity.expiration.time_to_live=120000
hibernate.cache.redisson.entity.expiration.max_idle_time=180000
hibernate.cache.redisson.entity.eviction.max_entries=200

### What is the Expected behavior?

cache should be cleared from redis

### What is the Actual behavior?

Cache is not clearing after time is elasped

### Additional information

added the sample project in the existing issue : https://github.com/redisson/redisson/issues/1929

**Comment by mrniko** [comment]
You need to set settings like below:

**spring.jpa.properties**.hibernate.cache.redisson.entity.expiration.time_to_live=120000
**spring.jpa.properties**.hibernate.cache.redisson.entity.expiration.max_idle_time=180000
**spring.jpa.properties**.hibernate.cache.redisson.entity.eviction.max_entries=200

**Comment by mrniko** [comment]
Also you need to remove the setting below:

spring.jpa.properties.hibernate.cache.provider_class

**Comment by abdulwhd964** [comment]
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_ONLY, region = "employee")
public class Employee { //should be expired after 2 hours

}

spring.jpa.properties.hibernate.cache.redisson.employee.expiration.time_to_live=1200000
spring.jpa.properties.hibernate.cache.redisson.employee.expiration.max_idle_time=1800000
spring.jpa.properties.hibernate.cache.redisson.employee.eviction.max_entries=2000

i can use this way ? @mrniko i was referring to this https://github.com/redisson/redisson/issues/4670 .. let me know your thoughts

**Comment by mrniko** [comment]
@abdulwhd964 

The settings looks fine
