### ISSUE TITLE
Redisson is shutdown

### ISSUE THREAD

**Issue by LHH7049** [redisson/redisson#6315]
### Redisson Version
3.13.2

### What is the Actual behavior?
an error is reported by refreshing the local cache through Redis when the k8s pod is destroyed

### Redisson configuration

    @Bean
    public StringRedisTemplate stringRedisTemplateMenu() {
        StringRedisTemplate template = new StringRedisTemplate();
        template.setConnectionFactory(redissonMenuConnectionFactory());
        return template;
    }
    @Bean
    public RedisConnectionFactory redissonMenuConnectionFactory() {
        return new RedissonConnectionFactory(redissonMenu());
    }
    @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonMenu() {
        if (StringUtils.isBlank(redissonMenuProperties.getSingleServerConfig().getPassword())) {
            redissonMenuProperties.getSingleServerConfig().setPassword(null);
        }
        Config config = null;
        try {
            config = Config.fromJSON(JSON.toJSONString(redissonMenuProperties));
        } catch (Exception e) {
            log.error("spring.redisson-menu 配置异常:{}", e.getMessage(), e);
            throw new BaseBizException(BaseErrorEnum.UNKNOW_SYSTEM_ERROR, "spring.redisson-menu 配置读取异常");
        }
        config.setCodec(new org.redisson.client.codec.StringCodec());
        return Redisson.create(config);
    }

### Additional information
`nested exception is org.redisson.RedissonShutdownException: Redisson is shutdown org.springframework.dao.InvalidDataAccessApiUsageException: Redisson is shutdown; nested exception is org.redisson.RedissonShutdownException: Redisson is shutdown\n\tat org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:48)\n\tat org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)\n\tat org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)\n\tat org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:217)\n\tat org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:212)\n\tat org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:378)\n\tat org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:759)\n\tat org.redisson.spring.data.connection.RedissonConnection.get(RedissonConnection.java:493)\n\tat org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:404)\n\tat org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)\n\tat org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)\n\tat org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)\n\tat org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)\n\tat org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)\n\tat org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)\n ...`

**Comment by mrniko** [comment]
This is an expected behavior since pod is shutdown.

**Comment by LHH7049** [comment]
> This is an expected behavior since pod is shutdown.

fine, thanks
