### ISSUE TITLE
RMapCache#get return null, but value exists

### ISSUE THREAD

**Issue by MrNeuronix** [redisson/redisson#6325]
### Redis version

KVRocks latest

### Redisson version

3.32.0

### Redisson configuration

    public Config config(@Value("${redis.kvrocks.master}") String redisMaster,
                         @Value("${redis.kvrocks.sentinels}") String redisSentinels,
                         @Value("${redis.kvrocks.sentinel.port}") int port,
                         @Value("${redis.kvrocks.sentinel.password}") String sentinelPassword,
                         @Value("${redis.kvrocks.password}") String redisPassword,
                         @Value("${redis.kvrocks.ping.interval.ms}") int pingIntervalMs,
                         @Value("${redis.kvrocks.timeout.ms}") int timeoutMs,
                         @Value("${redis.kvrocks.retry.attempts}") int retryAttempts,
                         @Value("${redis.kvrocks.transport.epoll}") boolean useEpoll,
                         @Value("${redis.kvrocks.read.mode}") int readMode,
                         @Value("${redis.kvrocks.min.idle.size}") int minIdleSize,
                         @Value("${redis.kvrocks.netty.threads.size}") Integer nettyThreads,
                         @Value("${redis.kvrocks.max.pool.size}") Integer maxPoolSize) {

        Config config = new Config();

        Optional.ofNullable(nettyThreads).ifPresent(config::setNettyThreads);

        config.setCodec(jsonJacksonCodec());

        config.setTransportMode(useEpoll ? TransportMode.EPOLL : TransportMode.NIO);

        SentinelServersConfig sentinelServersConfig = config.useSentinelServers();

        sentinelServersConfig
                .setMasterName(redisMaster);

        getRedisSentinels(redisSentinels, port)
                .forEach(sentinelServersConfig::addSentinelAddress);

        sentinelServersConfig.setRetryAttempts(retryAttempts);
        sentinelServersConfig.setMasterConnectionMinimumIdleSize(minIdleSize);

        Optional.ofNullable(sentinelPassword).ifPresent(sentinelServersConfig::setSentinelPassword);
        Optional.ofNullable(redisPassword).ifPresent(sentinelServersConfig::setPassword);

        Optional.ofNullable(maxPoolSize).ifPresent(sentinelServersConfig::setMasterConnectionPoolSize);
        Optional.ofNullable(maxPoolSize).ifPresent(sentinelServersConfig::setSlaveConnectionPoolSize);

        sentinelServersConfig.setTimeout(timeoutMs);
        sentinelServersConfig.setPingConnectionInterval(pingIntervalMs);

        sentinelServersConfig.setSubscriptionMode(SubscriptionMode.MASTER);

        switch (readMode) {
            case 1: {
                sentinelServersConfig.setReadMode(ReadMode.MASTER);
                break;
            }
            case 2: {
                sentinelServersConfig.setReadMode(ReadMode.MASTER_SLAVE);
                break;
            }
            case 3: {
                sentinelServersConfig.setReadMode(ReadMode.SLAVE);
                break;
            }
            default: {
                sentinelServersConfig.setReadMode(ReadMode.MASTER);
            }
        }

        return config;
    }

### What is the Expected behavior?

I have cache

`
RMapCache<CacheKey, IMenu> MENU_CACHE = redissonClient.getMapCache("doMenuCache", menuCodec);
`

menuCodec is a sort of JsonJacksonCodec

Tries to get some existing value from cache

`
IMenu menu = MENU_CACHE.get(cacheKey);
`

expect to have not null value

### What is the Actual behavior?

Got null value

### Additional information
If I do

`
MENU_CACHE.readAllEntrySet().stream().filter(e -> e.getKey().equals(cacheKey)).findFirst().get()
`

it is return expected value.

There is no exceptions or errors. CacheKey have valid hashCode/equals. Only few keys was produce this behavior.

**Comment by MrNeuronix** [comment]
Looks like Redission compare keys by calling toString(). In my case sometime toString() may produce different text.

**Comment by mrniko** [comment]
No, comparison is made on Redis or Valkey side using serialized state stored by Redisson
