### ISSUE TITLE
Documentation: `ConfigSupport.createConnectionManager` to `ConnectionManager.create` in release 3.40.1

### ISSUE THREAD

**Issue by nfatob** [redisson/redisson#6336]
Commit https://github.com/redisson/redisson/commit/01919c7bbcbb01129777457de6e313423933f963 removed the method `createConnectionManager` from `ConfigSupport` and placed it inside `create` in `ConnectionManager`.

This is a breaking change for anyone using `createConnectionManager` and should be documented in the release notes and the changelog as such. 

E.g.: 

"Breaking change - Removed `ConfigSupport.createConnectionManager` and added equivalent `ConnectionManager.create`"

**Comment by mrniko** [comment]
This is an internal API
