### ISSUE TITLE
Topic listeners leakage

### ISSUE THREAD

**Issue by vladnosiv** [redisson/redisson#6345]
### Redis version

7.2

### Redisson version

3.40.3-SNAPSHOT

### Redisson configuration

Production config:

sentinelServersConfig:
  checkSentinelsList: false
  sslEnableEndpointIdentification: false
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  subscriptionConnectionPoolSize: 100
  subscriptionsPerConnection: 10
  subscriptionTimeout: 1000
  sentinelAddresses:
    - "${redis_hosts_0}"
    - "${redis_hosts_1}"
    - "${redis_hosts_2}"

### What is the Expected behavior?

all listeners are cleared after removal

### What is the Actual behavior?

some subscribers remain active after removal

### Additional information

We kept catching an error like this on production:
```
org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after Nms. Try to increase 'subscriptionTimeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
```

We raised the pool of subscribers and subscription timeout to 15 seconds (although in our scenario we would generally want to wait 100-200 milliseconds at most). 
But errors still appeared, but not immediately, but after a few days of work.
It is important to note that at the same time on the server now about 0-2 subscribers, so there should not be a race for the subscription lock.

Began to suspect a subscriber leak, found several places with the leak in ours business logic, and the following test was found to reproduce the leak in redisson itself:
```java
public class RacePubSubTest extends RedisDockerTest {

    @Test
    public void testSubscriptionsRaceWithLambda() throws ExecutionException, InterruptedException {
        final PublishSubscribeService subscribeService = ((Redisson) redisson)
                .getConnectionManager().getSubscribeService();
        assertThat(subscribeService.countAllListeners()).isZero();

        final RTopic topic = redisson.getTopic("topic");

        final int tasksCount = 100;
        final Runnable task = () -> {
            final MessageListener<Object> listener = (a, b) -> {};
            final int listenerId = topic.addListener(Object.class, listener);
            topic.removeListener(listenerId);
        };

        try (final var pool = Executors.newFixedThreadPool(2)) {
            final List<Future<?>> futures = IntStream.range(0, tasksCount)
                    .mapToObj(i -> task)
                    .map(pool::submit)
                    .collect(Collectors.toList());
            for (final Future<?> future : futures) {
                future.get();
            }
            pool.shutdown();
        }

        assertThat(subscribeService.countAllListeners()).isZero();
    }

}
```

This test failed (sometimes flap, if you increase the number of threads and tasks will fail constantly) on a fresh master on a branch from this pr: https://github.com/redisson/redisson/pull/6344

The most interesting thing is that to fix the test, all you have to do is replace the lambda:
```
final MessageListener<Object> listener = (a, b) -> {};
```
With an explicit instant:
```
final MessageListener<Object> listener = new MessageListener<Object>() {
    @Override
    public void onMessage(CharSequence channel, Object msg) {
    }
};
```

I discovered that the subscription service uses `System.identityHashCode` as id of listener and in this example jvm optimizes lambda creation and uses exactly 1 object with identical `System.identityHashCode`.
But I also see that in the library code the raw listener is wrapped in another object with explicit creation and supposedly there shouldn't be a problem with the same hashcode after that, but it seems there is. So far I haven't been able to figure out what exactly is going wrong here, so I bring an issue rather than a PR with fixing it.

I have also reproduced this bug with amazon coretto, openjdk, and liberica (21 versions if it matters).

Unfortunately even after fixing our leaks and replacing lambda with an explicit instance we still keep getting the subscription lock error, so I'm also attaching a PR (https://github.com/redisson/redisson/pull/6344) adding a way to calculate the number of active subscribers across all channels to set up monitoring and either confirm the existence of some other source of the leak or confirm that we need to dig in a different direction.

**Comment by mrniko** [comment]
> But I also see that in the library code the raw listener is wrapped in another object with explicit creation and supposedly there shouldn't be a problem with the same hashcode after that, but it seems there is. 

hashcode of the listener and not a wrapper is used

**Comment by mrniko** [comment]
It's a race-condition issue.

**Comment by vladnosiv** [comment]
and there is the path of new listener:

. raw at RedissonTopic.addListener
-> raw at public RedissonTopic.addListenerAsync
-> wrapper at protected RedissonTopic.addListenerAsync

and in protected RedissonTopic.addListenerAsync 
`return System.identityHashCode(pubSubListener);` for already wrapper pubSubListener and because of the identity hash code the hash code override from the wrapper is not used

Maybe I'm not seeing something, but with debugger I also see that the identity hash code from the wrapper is called

**Comment by mrniko** [comment]
> and in protected RedissonTopic.addListenerAsync
return System.identityHashCode(pubSubListener); for already wrapper pubSubListener and because of the identity hash code the hash code override from the wrapper is not used

You're right. This is the cause.

**Comment by vladnosiv** [comment]
> hashcode of the listener and not a wrapper is used

by the way it would seem logical to me if the code above worked correctly, i.e. using the same object as a listener many times looks useful especially in the context of jvm optimizations
especially if the listener is stateless too

otherwise, having written a lambda here, when using the lambda hashcode, I could spend a very long time debugging a test where I would get, for example, 0 subscribers after deleting only one of the many ones

**Comment by mrniko** [comment]
duplicated hashcodes are allowed by JVM specification and we finally got them :)

**Comment by mrniko** [comment]
I'll fix it

**Comment by vladnosiv** [comment]
@mrniko 
Today I ruled out the existence of a leak at our place by monitoring the number of subscriptions in the redis server itself

But I think I've been able to replicate what's going on here.
Here's a test bench where the listener creation time is severely degraded. We have some kind of non-zero duration call going on in the listener. That seems to be the issue here. I think we stole the redisson thread. Here is a code sample:

```java
public class PubSubTest extends RedisDockerTest {

    public static class TopicWorker implements Runnable {
        private final RedissonClient redisson;

        public final Deque<Long> latencies = new ConcurrentLinkedDeque<>();

        public TopicWorker(RedissonClient redisson) {
            this.redisson = redisson;
        }

        @Override
        public void run() {
            try {
                final RTopic topic = redisson.getTopic(UUID.randomUUID().toString());
                final MessageListener<Object> listener = new MessageListener<Object>() {
                    @Override
                    public void onMessage(CharSequence channel, Object msg) {
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                            throw new RuntimeException(e);
                        }
                    }
                };
                final Instant start = Instant.now();
                final int listenerId = topic.addListener(Object.class, listener);
                final Instant end = Instant.now();
                topic.publish(new Object());

                topic.removeListener(listenerId);
                latencies.addLast(Duration.between(start, end).toMillis());
            } catch (Throwable t) {
                System.out.println("Error: " + t);
            }
        }
    }

    @Test
    public void pubSubLatencyTest() {
        final int numTasks = 100;
        final int numThreads = 20;

        final TopicWorker worker = new TopicWorker(redisson);
        try (final var pool = Executors.newFixedThreadPool(numThreads)) {
            for (int i = 0; i < numTasks; ++i) {
                pool.submit(worker);
            }
            pool.shutdown();
        }

        final List<Long> latencies = new ArrayList<>(worker.latencies);
        latencies.sort(Long::compareTo);

        System.out.println("Subscribe latency:");
        final List<Double> percentiles = List.of(
                0.5,
                0.75,
                0.9,
                0.95,
                0.99,
                0.999,
                1.0
        );
        for (final Double percentile : percentiles) {
            final int index = Math.min(latencies.size() - 1, (int) Math.ceil(percentile * latencies.size()));
            System.out.println("q " + percentile + ": " + latencies.get(index) + " ms");
        }
    }

}
```

Output:
```
Subscribe latency:
q 0.5: 3 ms
q 0.75: 13 ms
q 0.9: 19 ms
q 0.95: 21 ms
q 0.99: 1013 ms
q 0.999: 1013 ms
q 1.0: 1013 ms
```

In this example, if the subscription timeout was 1 second, we would get an error 1% of the time in production.
```
org.redisson.client.RedisTimeoutException: Unable to acquire subscription lock after 1000ms. Try to increase 'subscriptionTimeout', 'subscriptionsPerConnection', 'subscriptionConnectionPoolSize' parameters.
```

Apparently it's bad to have long calls inside the listener, seems like it should be highlighted in the documentation

**Comment by mrniko** [comment]
You can try to set Executors.newVirtualThreadPerTaskExecutor() for `executor` setting

**Comment by vladnosiv** [comment]
> did you try to remove `Thread.sleep(1000);` from the listener?

That slip is actually the problem
On the bench without the slip everything works extremely fast, it was just confusing when trying to figure out our problem.
But in our service listener can be relatively long, which I am demonstrating here by adding the slip.
In general, this bench shows that you **can't do long jobs in the listener**, because it can affect other requests -- the latency of subscribing to some **other random topic suffers** here.

**Comment by mrniko** [comment]
To mitigate the problem with delays in listeners you need to apply the settings below:

```java
        c.setKeepPubSubOrder(false); // messages order makes sequential handling and introduces a delay
        c.setThreads(64); // absence of free threads is also introduces a delay
```

**Comment by mrniko** [comment]
Fixed
