### ISSUE TITLE
Redisson takes a long time to start

### ISSUE THREAD

**Issue by Mortega5** [redisson/redisson#6347]
### Redis version

7.2.5

### Redisson version

3.40.2

### Redisson configuration

singleServerConfig:
  address: redis://x.x.x.x:yyyyy

### What is the Expected behavior?

Redisson should start faster

### What is the Actual behavior?

Since version 3.31.0, creating a Redisson instance using Redisson.create(config) takes several minutes. This only happens during test execution. The problem seems to be inside the ConnectionManager.create(config) function, although I haven't been able to pinpoint what exactly is causing it.

I'm not sure if it's an issue with Redisson itself or with some dependency in the project's pom. If I downgrade to a previous version, for example, 3.30.0, the issue does not occur.

I have reviewed the changelog and the source code changes between the two versions (3.31.0 and 3.30.0) but haven't been able to identify what might be causing the issue.

The tests are run in a Docker container with openjdk-21+35-2513. The test is the following

```java
@Testcontainers
class RedissonTest {

  private static final String REDIS_IMAGE = "redis:7.2.5";

  @Container
  private static final RedisContainer redis = new RedisContainer(REDIS_IMAGE);

  private static Config config;

  @BeforeAll
  static void setup() {
    config = new Config();
    config.useSingleServer().setAddress(redis.getRedisURI());
  }

  @ParameterizedTest
  @ValueSource(ints = {10, 100, 200, 500})
  void createRedisson(int instances) {

    for (int i = 0; i < instances; i++) {

      long start = System.currentTimeMillis();
      RedissonClient redissonClient = Redisson.create(config);
      long end = System.currentTimeMillis() - start;
      System.out.println("Redisson started: " + end + " ms");
      redissonClient.shutdown(0, 0, TimeUnit.MILLISECONDS);
    }
  }
}
```
```
Redisson started: 845 ms
Redisson started: 23 ms
Redisson started: 82233 ms
Redisson started: 112645 ms
Redisson started: 98921 ms
Redisson started: 117661 ms
Redisson started: 158821 ms
Redisson started: 65618 ms
Redisson started: 207615 ms
Redisson started: 214237 ms
Redisson started: 210947 ms
```

Could there be a dependency affecting this? I've analyzed the dependencies with Maven and there’s nothing overriding netty. I’ve tried with version 3.40.2, and the issue still occurs.

Is there something I might be overlooking?

**Comment by Mortega5** [comment]
I solved the issue by updating the Linux kernel and rebooting the VM

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/6307
