### ISSUE TITLE
RemoteService calls do not throw RemoteServiceTimeoutException, leaving threads stuck.

### ISSUE THREAD

**Issue by ThaisaZambanini** [redisson/redisson#6361]
### Redis version

7.4.12

### Redisson version

3.41.0

### Redisson configuration

 @Bean(destroyMethod = "shutdown")
    public RedissonClient redissonClient() {

        Config config = new Config();
        config.useSingleServer().setAddress("redis://localhost:6379");
        config.setNettyThreads(64);
        config.useSingleServer().setConnectionPoolSize(32);
        return Redisson.create(config);

    }

### What is the Expected behavior?

We have a client that makes calls to a service using RRemoteService.
This client has a ThreadPoolExecutor to make 1 call at a time for each key.
In the service/consumer, there is processing. In the example, we include a sleep to simulate time.
It is expected that if the service takes a long time to return, a RemoteServiceTimeoutException will be thrown.

[log-ok.log](https://github.com/user-attachments/files/18254950/log-ok.log)

### What is the Actual behavior?

When there is a delay in the service/consumer returning, the threads on the client get stuck.
The RemoteServiceTimeoutException exception is not thrown.

[log-error.log](https://github.com/user-attachments/files/18254952/log-error.log)

To visualize the problem and reproduce it, there is this example below.
**https://github.com/leandronsousa/redisson**

### Additional information

Up to version 3.28.0 the behavior works as expected.

**Comment by mrniko** [comment]
Merged. Thanks for report
