### ISSUE TITLE
RLexSortedSet.addAll(Collection) doesn't work

### ISSUE THREAD

**Issue by davidtinker** [redisson/redisson#640]
If I try to call addAll I get a RedisException:

    redisson.getLexSortedSet("mash:active-accounts").addAll(Arrays.asList("foo"))

I am using 2.4.0.

    RedisException: ERR wrong number of arguments for 'zadd' command. channel: [id: 0xf5b079ba, L:/127.0.0.1:54944 - R:/127.0.0.1:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@6cca2408, command=(ZADD), params=[mash:active-accounts, [Ljava.lang.Object;@36cc628b], codec=org.redisson.client.codec.StringCodec@4b03c104]
    ->>  265 | decode    in org.redisson.client.handler.CommandDecoder
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |    125 | decode    in     ''
    |    367 | callDecode in io.netty.handler.codec.ReplayingDecoder
    |    248 | channelRead in io.netty.handler.codec.ByteToMessageDecoder
    |    366 | invokeChannelRead in io.netty.channel.AbstractChannelHandlerContext
    |    352 | invokeChannelRead in     ''
    |    345 | fireChannelRead in     ''
    |     86 | channelRead in io.netty.channel.ChannelInboundHandlerAdapter
    |    366 | invokeChannelRead in io.netty.channel.AbstractChannelHandlerContext
    |    352 | invokeChannelRead in     ''
    |    345 | fireChannelRead in     ''
    |   1294 | channelRead in io.netty.channel.DefaultChannelPipeline$HeadContext
    |    366 | invokeChannelRead in io.netty.channel.AbstractChannelHandlerContext
    |    352 | invokeChannelRead in     ''
    |    911 | fireChannelRead in io.netty.channel.DefaultChannelPipeline
    |    131 | read      in io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe
    |    611 | processSelectedKey in io.netty.channel.nio.NioEventLoop
    |    552 | processSelectedKeysOptimized in     ''
    |    466 | processSelectedKeys in     ''
    |    438 | run       in     ''
    |    140 | run . . . in io.netty.util.concurrent.SingleThreadEventExecutor$2
    |    144 | run       in io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator
    ^    744 | run . . . in java.lang.Thread

**Comment by mrniko** [comment]
Done
