### ISSUE TITLE
RedissonSetCache TTL not updated if element already present

### ISSUE THREAD

**Issue by RobyZ** [redisson/redisson#646]
When using RedissonSetCache.add(value, ttl, unit) method, TTL is not updated if the element is already in the set. I think the problem is in the addAsync(value, ttl, unit) method, in the script passed to redis:

"local expireDateScore = redis.call('zscore', KEYS[1], ARGV[3]); "
                + "if expireDateScore ~= false and tonumber(expireDateScore) > tonumber(ARGV[1]) then "
                    + "return 0;"
                + "end; " +
                "redis.call('zadd', KEYS[1], ARGV[2], ARGV[3]); " +
                "return 1; "

If I'm getting it right, when the element is not expired the script returns 0 without calling ZADD and updating the TTL. I would expect 'false' return code (according to Set interface), but also TTL to be updated.

**Comment by mrniko** [comment]
Thanks for report! Fixed
