### ISSUE TITLE
MasterConnectionPool exhausted

### ISSUE THREAD

**Issue by pengfei-xu** [redisson/redisson#663]
redis use  Sentinel when switch master slave  where cause it

2016-10-11 19:10:26.625 WARN  o.r.c.SentinelConnectionManager.onNodeDown:272 master: 10.116.192.13:7091 has down

2016-10-11 19:10:27.666 WARN  o.r.c.SentinelConnectionManager.slaveDown:286 slave: 10.116.192.13:7091 has down

2016-10-11 19:10:42.937 WARN  o.r.c.SentinelConnectionManager.slaveDown:286 slave: 10.116.192.13:7091 has down

2016-10-11 19:12:18.385 WARN  i.n.c.DefaultChannelPipeline.warn:151 An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
org.redisson.client.RedisConnectionException: MasterConnectionPool exhausted!  Disconnected hosts: [10.25.63.47/10.25.63.47:7091]

**Comment by pengfei-xu** [comment]
this is my redisConfig .

Config redisConfig = new Config();
        redisConfig.useSentinelServers().addSentinelAddress(StringUtils.split(StringUtils.trim(getServer()), ","))
                .setMasterName(StringUtils.trim(getMasterName()))
                .setDatabase(getDatabase()).setRetryAttempts(100).setFailedAttempts(100)
                .setMasterConnectionMinimumIdleSize(10).setSlaveConnectionMinimumIdleSize(10)
                .setMasterConnectionPoolSize(250).setSlaveConnectionPoolSize(250)
                .setTimeout(TIME_OUT).setReadMode(ReadMode.MASTER);
        redisConfig.setThreads(threadNum);
        RedissonClient redissonClient = Redisson.create(redisConfig);

**Comment by pengfei-xu** [comment]
only when I restart my webServer can solve it

**Comment by mrniko** [comment]
How do I reproduce it?

**Comment by pengfei-xu** [comment]
redis use sentinel mode when switch master/slave where cause it.

**Comment by mrniko** [comment]
Can you reproduce it with test like below in comment?
https://github.com/redisson/redisson/issues/550#issuecomment-232905142

**Comment by pengfei-xu** [comment]
yes!  my config is  redisConfig.useSentinelServers()
          .addSentinelAddress(10.168.69.58:26379).addSentinelAddress(10.252.86.241:26379)
          .addSentinelAddress(10.171.211.81:26379).
 master server is 10.116.192.13:7091  slave server is 10.25.63.47:7091
when I switch master/slave , stop 10.116.192.13:7091 and wait one minute start  10.116.192.13:7091
can cause it

**Comment by pengfei-xu** [comment]
I use redisson with  netty-socketio ，when operations person switch  master/slave can cause it .
this will cause me must to restart netty-socketio server can solve it .

**Comment by mrniko** [comment]
I have reproduced it. Sometimes failover doesn't work after master has switched. I'll investigate it

**Comment by pengfei-xu** [comment]
ok,thanks!  I have reproduced it each time by production environment

**Comment by mrniko** [comment]
@pengfei-xu Which Redis version do you use?

**Comment by pengfei-xu** [comment]
2.4.0

**Comment by mrniko** [comment]
I mean Redis server version

**Comment by pengfei-xu** [comment]
redis-2.8.19-1.el6.remi.x86_64

**Comment by mrniko** [comment]
Please check

**Comment by pengfei-xu** [comment]
thanks!

**Comment by pengfei-xu** [comment]
I have reproduced it again by production environment! @mrniko 
![image](https://cloud.githubusercontent.com/assets/15759076/19998283/fb254a90-a2a6-11e6-92ef-cb9983a66f6e.png)

**Comment by pengfei-xu** [comment]
![image](https://cloud.githubusercontent.com/assets/15759076/19998346/4c08ebd8-a2a7-11e6-86ef-9a956676d29b.png)

**Comment by mrniko** [comment]
First screenshot looks strange. Because it seems like Redisson instance goes shutdown. I don't know any other reason why HashedWheelTimer stopped except this.

As for second screenshot. Is this related to PUBLISH commands only ?

**Comment by pengfei-xu** [comment]
yes,redisson is used for pub/sub .second screenshot is caused by  I switch master/slave redis server。the first screenshot is follow second screenshot。it also caused by switch master/slave.

**Comment by pengfei-xu** [comment]
I used it with netty-socketio.

**Comment by pengfei-xu** [comment]
@mrniko

**Comment by mrniko** [comment]
@pengfei-xu I haven't resolved it yet

**Comment by pengfei-xu** [comment]
thanks! you can reproduce it ?  I use redisson with netty-socketio ，when operations person switch master/slave can cause it .this will cause me must to restart netty-socketio server can solve it .

**Comment by mrniko** [comment]
Could you provide logs from Sentinel nodes too?
