### ISSUE TITLE
Runtime dependencies

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#668]
Is it safe to exclude the byte-buddy dependency, or is it required at runtime?

**Comment by jackygurui** [comment]
The byte-buddy library is used to provide live object service, so it is required at runtime.

**Comment by johnou** [comment]
@jackygurui so it should be safe to exclude if I am not using live objects?

**Comment by jackygurui** [comment]
In theory yes, although I have not tried that myself. I am curious though, what makes you trying hard to avoid having this library?

**Comment by johnou** [comment]
The size of it.

**Comment by jackygurui** [comment]
Ah, I see.

**Comment by mrniko** [comment]
I think it should work well without byte-buddy

**Comment by johnou** [comment]
Thanks!

**Comment by johnou** [comment]
@jackygurui did you consider transforming the classes at compile time instead of runtime?

**Comment by jackygurui** [comment]
As far as I am aware, the byte-buddy library is only a runtime code generation library.

**Comment by johnou** [comment]
Aha so it is, thanks again.
