### ISSUE TITLE
Always timeout when get/set objects from/to redis within onMessage handler.

### ISSUE THREAD

**Issue by Mavlarn** [redisson/redisson#684]
In our micro services system, we use RTopic process messages between services. In the onMessage method, I need to get data from redis, or set data. But in the test env, when it got or set data from/to redis, there ware always timeout errors (maybe one error for 2 tests). When I commented the code, no more errors.  
So, is there any handling time limitation in onMessage method for RTopic? Or any limitation to interact with redis in onMessage method?

**Comment by mrniko** [comment]
Which Redisson version do you use? Since 2.4.0 version Redisson has separate executor for RTopic listeners execution.

**Comment by Mavlarn** [comment]
I use 2.2.27. 
I fixed this problem in this way now: in onMessage method, call the service method in async way.
I will try later with new version when I have time.
