### ISSUE TITLE
How to use Redisson to upload byte array?

### ISSUE THREAD

**Issue by porunov** [redisson/redisson#688]
Hello,

I haven't found an explanation about how to upload pure array of bytes. Redisson has a RBitSet but it manages an array of bits not bytes. How to store a byte array by using Redisson?

Here is my configuration:
```
Config config = new Config();

LoadBalancer loadBalancer = new RoundRobinLoadBalancer();

config.useClusterServers()
        .setScanInterval(5000) // cluster state scan interval in milliseconds
        .addNodeAddress("192.168.0.14:6379", "192.168.0.15:6379")
        .setReadMode(ReadMode.MASTER_SLAVE)
        .setLoadBalancer(loadBalancer)
        .setPassword("bTFBx1NYYWRMTUEyNHhsCg")
        .setSlaveConnectionPoolSize(10)
        .setMasterConnectionPoolSize(10);

RedissonClient redisson = Redisson.create(config);
```

**Comment by jackygurui** [comment]
You can supply a custom codec to achieve this.

**Comment by porunov** [comment]
Could you please help me with it?
Do you know how to use it?

I see that redisson already has a `ByteArrayCodec` but I don't know how to use it.
Here is the codec:
`Codec codec = new org.redisson.client.codec.ByteArrayCodec();`

How to use it to upload a byte array?
To upload a long right now I am using the next code:
```
RAtomicLong longObject = redisson.getAtomicLong("myLong");
longObject.set(3);
```

**Comment by mrniko** [comment]
If you want to store binary array. You could you use follow code snippet:

```java
RBucket<byte[]> bucket = redisson.getBucket("myBucket", ByteArrayCodec.INSTANCE);
byte[] myarray = ...
bucket.set(myarray);
```

**Comment by porunov** [comment]
Hello Nikita,

Thank you very much for help! It works like a charm :)
I am closing the issue as you have answered the question.

Sincerely,
Alexandr
