### ISSUE TITLE
Redisson JUnit tests due leaks connections/clients/threads

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#693]
If you run the JUnit tests for Redisson a lot of client and their associated connections/threads are leaking because they are not properly shutdown. This will prevent the build to be successful on system with limited number of user-processes/open-files (i.e. MacOS El Capitain).

To verify this, build the project with an attached debugger and watch the constantly growing amount of threads.

**Comment by smigfu** [comment]
I am preparing a PR to fix this.

**Comment by mrniko** [comment]
Good! It would be nice to have a look at this

**Comment by mrniko** [comment]
@smigfu Could you please check it again? I think I fixed it.

**Comment by smigfu** [comment]
Looks good, though some of the ExecutorServices are also leaking (maybe you could cherry-pick https://github.com/redisson/redisson/commit/bd12c45 of my orginal PR). Though the ExecutorServices aren't as severe since they will shutdown themselves in finalize (which was the motivation for https://github.com/redisson/redisson/pull/709).

Thanks for fixing this.
