### ISSUE TITLE
Expires for RMapCache/RSetCache entries and restarting java

### ISSUE THREAD

**Issue by giantninja** [redisson/redisson#715]
Not really an issue per say, more of a clarification really.  I'm about to launch a new feature that will be making use of the expires for individual entries in RMapCache and RSetCache, and I was wondering how that works regarding restarting the Java process that created/set it.  Will they be expired on shutdown, not touched at all and the expire is lost?

Just want to be sure of what is expected when I restart my Java service.

Thanks!

**Comment by mrniko** [comment]
> Will they be expired on shutdown, not touched at all and the expire is lost?

Redisson maintains expiration state only in Redis. So in your case entries start to expire as soon as you restart application and call getMapCache/getSetCache method.
