### ISSUE TITLE
RedissonBaseIterator.hasNext() doesn't return false on Object based RedissonSet.

### ISSUE THREAD

**Issue by chilicookie** [redisson/redisson#718]
I encountered an issue on using `RedissonBaseIterator`.

Inside of `RedissonBaseIterator.hasNext()`, it checked the end of iteration by `lastValues.removeAll(firstValues)` when scanned result is larger than default scan count `10`.

It failed to return `true` on `lastValues.removeAll(firstValues)` when values are in custom object type since `ArrayList.removeAll()` uses `Object.equals()`. An object not implementing equals causing infinite loop while processing the iterator. 

I'd rather check `nextIterPos == 0 && nextIter != null && !nextIter.hasNext()` at the start of `hasNext()` method.

**Comment by mrniko** [comment]
I agree it should be fixed and `ByteBuf` should be used instead of objects comparison like it made in RedissonBaseMapIterator

**Comment by mrniko** [comment]
Done
