### ISSUE TITLE
Config can not handle underscore in host

### ISSUE THREAD

**Issue by wenerme** [redisson/redisson#722]
Redisson 3.1.0

![image](https://cloud.githubusercontent.com/assets/1777211/20747762/4e6dbfc8-b726-11e6-89aa-7c6afdea0965.png)

![image](https://cloud.githubusercontent.com/assets/1777211/20747782/5cfb4c7c-b726-11e6-97de-304ba4b2da92.png)

**Comment by wenerme** [comment]
java URI can not parse underscore hostname, so, maybe use a custom object to hold host and port ?

**Comment by mrniko** [comment]
Didn't know about such bug. Here is workaround for this http://stackoverflow.com/questions/28568188/java-net-uri-get-host-with-underscores

**Comment by jackygurui** [comment]
Technically speaking, underscore in URI is not allowed. Based on the standard, it should be encoded.

See: https://tools.ietf.org/html/rfc3986#section-2.3

**Comment by wenerme** [comment]
According to [this](http://stackoverflow.com/a/2183140/1870054), underscore in domain name is very common , especially in docker.

Here is my nasty workaround

```java
    static URI createUri(String host, int port) {
        checkNotNull(host, "No host");
        checkArgument(port >= 0, "Port is negative");
        String h = host;
        if (h.contains("_")) {
            h = "127.0.0.1";
        }
        URI uri = URI.create("//"+h + ":" + port);
        if (host.contains("_")) {
            Reflect.on(uri).set("host", host);
        }
        return uri;
    }

SingleServerConfig conf = c.useSingleServer()
//                .setAddress(config.getString("host") + ":" + config.getInt("port"))
                .setRetryInterval(10000)
                .setTimeout(60000)
                .setConnectTimeout(60000);
            Reflect.on(conf).set("address", ImmutableList.of(Helper.createUri(config.getString("host"), config.getInt("port"))));
```

**Comment by jackygurui** [comment]
In the reference you provided, please take a look at the last paragraph:

> Other RFC mentioned here deal with different things. The original question was for domain names. If the question is for host names (or for URLs, which include a host name), then this is different, the relevant standard is RFC 1123, section 2.1 "Host Names and Numbers" which limits host names to letters-digits-hyphen.

**Comment by wenerme** [comment]
Event I create a uri with underscore, but this uri can not pass to underground config.

So, how can I use redission in docker ?

**Comment by jackygurui** [comment]
Either replace the underscore with a hyphen in your docker naming or use a nasty workaround. :D

**Comment by wenerme** [comment]
@mrniko redis-cli can handle underscore in hostname, but redission will not, so, I can use redis-cli but not redission.antirez never told the user change there hostname, because most of time this is impossible.

The workaround will not works for redisson, because address in single server will never pass to underlying MasterSlaveServersConfig, in `org/redisson/connection/SingleConnectionManager.java:71` 

```java
    private static MasterSlaveServersConfig create(SingleServerConfig cfg) {
        MasterSlaveServersConfig newconfig = new MasterSlaveServersConfig();
        // recreate uri will lost the uri host info
        String addr = cfg.getAddress().getHost() + ":" + cfg.getAddress().getPort();
        newconfig.setRetryAttempts(cfg.getRetryAttempts());
        newconfig.setRetryInterval(cfg.getRetryInterval());
        newconfig.setTimeout(cfg.getTimeout());
        newconfig.setPingTimeout(cfg.getPingTimeout());
        newconfig.setPassword(cfg.getPassword());
        newconfig.setDatabase(cfg.getDatabase());
        newconfig.setClientName(cfg.getClientName());
        newconfig.setMasterAddress(addr);
```

**Comment by wenerme** [comment]
BTW, jedis can handle underscore in host too, why redisson user should handle this ?

```java
Jedis jedis = new Jedis("local_host");
System.out.println(jedis.ping());
```

**Comment by wenerme** [comment]
Finally find a workaround

```
.setAddress(Helper.resolveHostIfContainUnderscore(config.getString("host")) + ":" + config.getInt("port"))
```

**Comment by mrniko** [comment]
I agree underscore should be allowed

**Comment by mrniko** [comment]
Fixed. Please check

**Comment by dstarcev** [comment]
The problem is back.

```
package org.redisson.config;

import org.junit.Test;

public class SingleServerConfigTest {
    @Test
    public void testUnderscoreHostname() {
        new SingleServerConfig().setAddress("redis://underscored_host:6379"); // exception here
    }
}
```

**Comment by mrniko** [comment]
@dstarcev please use config file as workaround

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/1367
