### ISSUE TITLE
URL.setURLStreamHandlerFactory(new URLStreamHandlerFactory()) causes throw new Error("factory already defined");

### ISSUE THREAD

**Issue by atouchingsong** [redisson/redisson#734]
public SingleServerConfig setAddress(String address) {
        if (address != null) {
            this.address = URLBuilder.create(address);
        }
        return this;
    }

when called setAddress("127.0.0.1:6379"), it would invoke URLBuilder.init method and then URL.setURLStreamHandlerFactory(new URLStreamHandlerFactory()) which causes throw new Error("factory already defined");

Because the tomcat server already registered a URLStreamHandlerFactory, and jvm did not allow a second registration for the URLStreamHandlerFactory.

**Comment by mrniko** [comment]
Fixed
