### ISSUE TITLE
DistributedLock - Lock is getting acquired by multiple threads.

### ISSUE THREAD

**Issue by sinusekhar** [redisson/redisson#738]
We are using distributed lock to ensure that only one thread can take a particular action, among a group of threads spread across multiple EC2 instances.

Here is a snippet that represents what we are doing.

@PostConstruct
public void init(){
    //We are using elasticache redis cluster
    client = Redisson.create(config);
    lock = client.getLock("OurJobLock");
}

	@Scheduled(cron = "${cron.expression.schedule.ourjob}")
	public void execute() {
		try {
			if (lock.tryLock(lockWaitTimeInSeconds, lockLeaseTimeInSeconds,TimeUnit.SECONDS))
			{
				ourjob();
			}
		} catch (Exception e) {
			//Print error
		}
		finally{
                  if(lock.isHeldByCurrentThread()) {
                      lock.unlock();
                  }
		}
	}

lockWaitTimeInSeconds=3
lockLeaseTimeInSeconds=120 (our job processing finishes within this time)

The issue is that we are seeing multiple threads from being able to acquire and do the job.

What might be the issue? Do you see an error in the way we are using distributed locks...is there a better way to solve this problem? 

Our goal is to ensure that for every job run...only one thread gets to do the job.

**Comment by sinusekhar** [comment]
By the way, i am using redisson 2.2.7

**Comment by mrniko** [comment]
I would recommend to update to latest 2.2.27 version of 2.2.x line (if you can't update to new major version) due to Lock related bugs there fixed in 2.2.16, 2.2.17, 2.2.24 versions. https://github.com/redisson/redisson/blob/master/CHANGELOG.md#12-jun-2016---version-2216-released

**Comment by sinusekhar** [comment]
Thanks @mrniko . I will go ahead and upgrade.
