### ISSUE TITLE
Divide by zero error in RedissonBloomFilter contains() when bloom filter is empty

### ISSUE THREAD

**Issue by jortman** [redisson/redisson#739]
If a user of Redisson sets up a RBloomFilter (the bloom filter has been successfully initialized) but does not populate it with any values, a call to the contains() method will throw a Divide By Zero exception.  The exception occurs within the hash() method when an attempt is made to use the mod operation with a size of zero.  

_(hash & Long.MAX_VALUE) % size;_

A value of false should be returned instead.  It is reasonable that a bloom filter would be created but might be populated after application startup with values encountered by the running application.

Using Redisson 3.2.2

**Comment by mrniko** [comment]
I added restrictions for RBloomFilter parameters, so size couldn't be zero anymore.
