### ISSUE TITLE
3.2.1 regression "Could not initialize class org.redisson.misc.URLBuilder" @ Tomcat

### ISSUE THREAD

**Issue by lwyza** [redisson/redisson#741]
3.2.0 doesn't have this issue, seems a regression (@ Tomcat "8.0.28" @ Java "1.8.0_112" @ Mac OS "10.12.2"):

java.lang.NoClassDefFoundError: Could not initialize class org.redisson.misc.URLBuilder
        at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:130)

URLBuilder.init() seems registering a protocol handler which could cause SecurityException. Just trying to help brainstorm: any chance to catch & log/warn & move on? Above Error prevents Redisson from being loaded/used, not just that particular protocol handling...

**Comment by mrniko** [comment]
This issue was fixed in 3.2.2 version
