### ISSUE TITLE
Right usage of persist since getOrCreate is deprecated

### ISSUE THREAD

**Issue by tlopo** [redisson/redisson#742]
Hi There,

What's the right usage of `persist` method since `getOrCreate` was deprecated on #639 ? 

Thanks,
Tiago

**Comment by mrniko** [comment]
Hi!

`persist` method should be invoked to store a state of non-persisted Object and returns LiveObject instance of it. `get` method checks LiveObject existence and returns LiveObject instance.

**Comment by tlopo** [comment]
@mrniko Got it. thanks!

One more question, are javadocs being published anywhere online? The latest I can find is 1.0.4

**Comment by mrniko** [comment]
If you're talking about redisson-javadocs.jar you can find it in repo. https://repo1.maven.org/maven2/org/redisson/redisson/3.2.2/

**Comment by tlopo** [comment]
I've found it. That link you can download, but the link below we can browse: 

http://www.javadoc.io/doc/org.redisson/redisson/3.2.2

**Comment by mrniko** [comment]
Nice! I'll add it to main page
