### ISSUE TITLE
Wiki sidebar is a bit difficult to use

### ISSUE THREAD

**Issue by kag0** [redisson/redisson#743]
The wiki is a great resource, but currently the sidebar is rather difficult to use. There are two things I think might be improved.

First, the wiki sidebar is sorted lexically, so the items appear in the order 1, 10, 11, 12 ... 2, 20, 21 ... I don't think github has an option to change how the pages are sorted so it's probably easy to just prefix each single digit page number with a 0, so 01, 02, ... 09, 10, 11 ... The table of contents could also be 00 to make it appear as the first item in the sidebar.

Second, every page is also in Chinese. I think it's awesome that the documentation has multi language support, but github doesn't have good support for wikis in multiple languages. Since both English and Chinese pages are side-by-side in the sidebar, only 7 pages are easily accessible without expanding the sidebar all the way. This obviously doesn't scale well as docs are added for more languages. Perhaps we could prefix the page number with an identifying code for the language so that the lexical sorting groups them together?

Thoughts? @jackygurui

**Comment by jackygurui** [comment]
@kag0 I think I may have to make a custom side bar. Thanks for pointing it out.

**Comment by jackygurui** [comment]
Done

**Comment by mrniko** [comment]
@jackygurui  Wow! Looks much better now. Thank you!

**Comment by kag0** [comment]
@jackygurui that's awesome!
