### ISSUE TITLE
Guava RateLimiter Redisson implementation.

### ISSUE THREAD

**Issue by doggie1989** [redisson/redisson#75]

**Comment by doggie1989** [comment]
@mrniko 
any ideas on this function?

**Comment by mrniko** [comment]
@doggie1989 which rates you need to limit? requests amount per sec from redisson to server?

**Comment by doggie1989** [comment]
Guava RateLimiter can only limit rate on local machine.
what I want is a distributed  RateLimiter.
for example, you have 10 consumers machines ,the speed of each one is 50~100 per second which depends on network or other reasons and the total consume rate is from 500~1000,but the rate must under 600.
Do you know what I mean?

**Comment by mrniko** [comment]
You need RateLimiter which applies to each node. Am I right?

**Comment by mrniko** [comment]
@doggie1989 ping

**Comment by doggie1989** [comment]
@mrniko 
Sorry for the delay.

Yes,Mate.
Also a global RateLimited for all machines.

**Comment by bwzhang2011** [comment]
@mrniko, any update with such issue ? maybe it's related to such info: http://redis.io/commands/INCR#pattern-rate-limiter

**Comment by mrniko** [comment]
Done - https://github.com/redisson/redisson/wiki/6.-distributed-objects#612-ratelimiter

**Comment by anjia0532** [comment]
@bwzhang2011 u can use the `RScoredSortedSet` .
```java
RScoredSortedSet<Long> set = redisson.getScoredSortedSet(key,LongCodec.INSTANCE);
set.add(System.currentTimeMillis(),System.currentTimeMillis()+RandomUtils.nextLong(0, 1000));

// set expire
redisson.getScoredSortedSet(key,LongCodec.INSTANCE) .removeRangeByScore(0,true , System.currentTimeMillis() - 1000*seconds, false);

// limit
redisson.getScoredSortedSet(key,LongCodec.INSTANCE).size()<limit;
```

redis list or incr can not set expire to every request.
e.g. 

```
SET key 0
EXPIRE 60000  # 1 min
INCR key  #*60 every sec
GET key # 60

## after 1min+1sec

GET key # null not 59.
```

**Comment by mrniko** [comment]
Now it's part of OS version.

**Comment by anjia0532** [comment]
@mrniko cool !
