### ISSUE TITLE
Reusing submited tasks

### ISSUE THREAD

**Issue by vestverg** [redisson/redisson#750]
Hello, 

I'm trying to use redisson for distributed task scheduling, but i have some problems with that. 

For each app restarting executorService.scheduleAtFixedRate pushing new task to Redis, but  i want to reuse it, is there any way to solve it?

`
@Component
public class RedisTest {
    private final Logger logger = LoggerFactory.getLogger(RedisTest.class);
    @Autowired
    private RedissonNode redissonNode;

    @Autowired
    private RedissonClient redissonClient;

    private RScheduledExecutorService executorService;

    @PostConstruct
    public void init() {
        redissonNode.start();
        executorService = redissonClient.getExecutorService(new JsonJacksonCodec(), "scheduler");
        ScheduledFuture<?> scheduledFuture = executorService.scheduleAtFixedRate(new RunnableTask(10), 0, 5, TimeUnit.SECONDS);
    }

    @PreDestroy
    public void preDestroy() throws InterruptedException {
        if (executorService != null) {
            executorService.awaitTermination(1, TimeUnit.SECONDS);
            executorService.shutdownNow();
        }
        redissonNode.shutdown();
    }
}
`

`
public class RunnableTask implements Runnable, Serializable {
    private static final long serialVersionUID = 2105094575950438867L;

    @RInject
    private RedissonClient redissonClient;

    public RunnableTask() {
    }
    @Override
    public void run() {
        RQueue<Object> shed = redissonClient.getQueue("queue");
        shed.offer("r:"+ Calendar.getInstance().getTime().toString());
    }

}
`

**Comment by mrniko** [comment]
Hi!

You mean not to serialized same task again and again?

**Comment by vestverg** [comment]
My case is about scaling artifact with embeded RedisNode. For example if we start three instances with same scheduled jobs, then all three jobs will be executed, but I expect that only one will be executed. I dont think to not serialize task again is the right way, may be providing custom requestId may help, but idont know how to do it.

**Comment by mrniko** [comment]
You could use RSet to store unique Id given from task and check if it there already. If so, then not to schedule task.
