### ISSUE TITLE
Redisson get api  is very slow !!!!

### ISSUE THREAD

**Issue by nratta** [redisson/redisson#753]
I am using Redisson client with Redis and implemented Redisson as JSR 107 .
I am simply calling a cache through jsp but it is taking a lot of time in CountDownLatch.await().
This wait is common for every single request , so what is the possible reason for this wait ?????
Is there any client side or server side setting effecting it....
Please find Jprofiler snapshot showing Api call trace.

![issue1](https://cloud.githubusercontent.com/assets/25316959/22237529/6fa04454-e232-11e6-9c76-314ff0d45b62.png)
****
And please find attached code test code.

public  void getmodulemapTime() throws Exception
  {
	long w_start_time = System.nanoTime();
  	String w_existingMap = (String)CacheService.get(CacheConstants.CACHEKEY.MODULE_CKEY_GLOBAL_MAP, "MODULEMANAGER_GLOBAL_MODULE_MAP_KEY");
  	long w_end_time = System.nanoTime();
  	double w_difference = (w_end_time - w_start_time)/1000000;
  	System.out.println("Get Time in ms for MODULE *****" + w_difference);
  }

**Comment by mrniko** [comment]
Hi!

I run test below and got only 7ms per call.

```java
    @Test
    public void testMapPutGet() throws InterruptedException, IllegalArgumentException, URISyntaxException {
        MutableConfiguration<String, String> config = new MutableConfiguration<>();
        config.setStoreByValue(true);
        
        URI configUri = getClass().getResource("redisson-jcache.json").toURI();
        Cache<String, String> cache = Caching.getCachingProvider().getCacheManager(configUri, null)
                .createCache("test", config);

        long startTime = System.nanoTime();
        cache.get("123");
        long spentTime = System.nanoTime() - startTime;
        System.out.println("get spentTime: " + spentTime);
    }
```

**Comment by nratta** [comment]
Hi Nikita,

I ran my code with this change:
*m_config.setStoreByValue(true);*

But still it is taking a lot of time.
Time taken around *30ms.*

Please find the below attachments :
1. Data set in the form of JSON that is actually Cache value.(Value i fetch
from redis server)
2. Jprofiler snapshot

Thanks and Regards
Nilesh Ratta

**Comment by mrniko** [comment]
Something wrong with your Redis environment. I run my test locally and you?

**Comment by nratta** [comment]
Even my Jboss server and Redis server on same machine.
Ans result is same even if both servers are on different machine.
*Note : Can u validate with my data set  !!!!!!*

Because i am getting same response time for almost all of my cache.....




Thanks and Regards
Nilesh Ratta

**Comment by mrniko** [comment]
What is your test data?

**Comment by nratta** [comment]
[Test_Data.txt](https://github.com/redisson/redisson/files/726192/Test_Data.txt)

Hi ,
Please find attached data and even send on mail......

**Comment by mrniko** [comment]
I see threads amount set too low. Could you rise it at least to 4?

**Comment by nratta** [comment]
I tried with following cases : 
 a.  "threads":4 ,  "nettyThreads": 4
 b.  "threads":8 ,  "nettyThreads": 8

But still the time is around 25 - 30 ms for a single request....
I am not getting why '**CommandAsyncService.get**  is calling **CountDownLatch.await**'
and for which thread is my process is waiting !!!!!!!!!

**Comment by mrniko** [comment]
> I am not getting why 'CommandAsyncService.get is calling CountDownLatch.await'

Redisson is fully async framework, but JCache working in sync mode. So Redisson have to wait till each command complete using CountDownLatch object.

**Comment by nratta** [comment]
**Have u tested with my data set !!!!**
**So what approach shall i take** .
TestCase 1: When i am calling single cache request from JSP it is taking around 30 ms.
TestCase 2: When that cache is getting called through application it is taking even more time....

**Comment by mrniko** [comment]
> Have u tested with my data set !!!!

How to parse it and load to Redisson?

**Comment by nratta** [comment]
hi,

I am sending u one of my test example :- 
Please  find attached java file to fetch data from Test1_Cache .
and json data in redis server is as below 
**"\"{\\\"id\\\":123,\\\"frstName\\\":\\\"First\\\",\\\"lstName\\\":\\\"Last\\\"}\""** 
**Time in ms : 30**

[RedisClient1.txt](https://github.com/redisson/redisson/files/726370/RedisClient1.txt)

**Comment by nratta** [comment]
waiting for ur suggestion !!!!

**Comment by mrniko** [comment]
which OS do you use?

**Comment by nratta** [comment]
i am using windows7 , 64 bit and 8 GB ram

**Comment by mrniko** [comment]
please switch to linux

**Comment by nratta** [comment]
Ok sure, will get back to u. Once it will be done.

**Comment by mrniko** [comment]
Any news?

**Comment by nratta** [comment]
Will let u know by today or tomorrow

**Comment by nratta** [comment]
HI , 
I have  tested on Ubuntu [Release 12.04  , 64 Bit  15.6 GB ram].
Output remains same .
Please find jprofiler snapshot to fetch cache value having size around 700KB (Same tested on Windows)
**Time taken to fetch single key value :  around 40 - 50 ms**
![ubuntu1](https://cloud.githubusercontent.com/assets/25316959/22459390/65e7dfb4-e7c6-11e6-9187-84567c5953a2.png)

**And also find redis :- redis.conf file.**
[redis.conf.txt](https://github.com/redisson/redisson/files/741548/redis.conf.txt)

**Comment by mrniko** [comment]
Is it the same with RMap object?

**Comment by nratta** [comment]
Not checked , gv me some time...

**Comment by nratta** [comment]
HI , 
**Note : Time reamains same......**
   **Cache value size : around 700KB**
**Please find my RMap code :**  

public void RMapTest() throws IOException
    {
    	RedissonClient w_redisson = Redisson.create(Config.fromJSON(new File("D:/digite/WorkSpace/RedisCacheDemo/src/com/client/MyCache.json")));
    	ObjectMapper w_mapper = new ObjectMapper();
    	long w_start_time = System.nanoTime();
    	RMap<Object, Object> w_Empmap = w_redisson.getMap("Test1_Cache");
    	long w_end_time = System.nanoTime();
    	double w_difference = (w_end_time - w_start_time)/1000000;
    	System.out.println("Difference in Rmap11111: " + w_difference);
    	String w_key = "Test1234";
    	long w_start_time1 = System.nanoTime();
    	String w_empp = (String)w_Empmap.get(w_key);
    	long w_end_time1 = System.nanoTime();
    	double w_difference1 = (w_end_time1 - w_start_time1)/1000000;
    	System.out.println("Difference in Rmap: " + w_difference1);
    	
    }

Console : 
16:39:47,616 INFO  [STDOUT] Difference in Rmap11111: 0.0
16:39:47,653 INFO  [STDOUT] Difference in Rmap: 37.0

**Comment by mrniko** [comment]
Oh, you didn't say about value size is 700Kb. Of course it will took some time on read/write operation. As solution I could suggest you to try SnappyCodec. One of our customers it helped a lot to reduce payload size and increase speed of read/write operation.

**Comment by nratta** [comment]
HI, 
I had already mentioned my cache size . 
No problem , i will try with that Codec and let u know....

**Comment by mrniko** [comment]
> I had already mentioned my cache size .

Sorry, I did not noticed it at first time.

**Comment by nratta** [comment]
I think we re  on right track ...
Is there any configuration tuning that i am missing.....

**Comment by mrniko** [comment]
Is it still the same as you provided in comment above https://github.com/redisson/redisson/issues/753#issuecomment-274753116

If so, I don't see anything required to change.

**Comment by nratta** [comment]
Yup, config is same as above provided. and one thing I have seen snappy code...
Can i store byte[] directly as a cache value and can directly fetch byte[] as value using get api !!!!!!

**Comment by mrniko** [comment]
Of course you can. Use `org.redisson.client.codec.ByteArrayCodec`

**Comment by mrniko** [comment]
Any update?

**Comment by nratta** [comment]
hi ,
I am having some issues with Snappy codec , trying to resolve that ,
As i am using java 6 . SO i am using snappy-java-1.0.5.jar.

Can u help me in below code :-   
**static FSTConfiguration m_conf = FSTConfiguration.createDefaultConfiguration();
public void addinBytes() throws Exception
   {
	   String w_existingMap = "Test12344555";
	   byte barray[] = m_conf.asByteArray(w_existingMap); 
	   CacheService.put(CacheConstants.CACHEKEY.Test1_Cache, "Test1234", barray);
	   byte[] w_map = (byte[])CacheService.get(CacheConstants.CACHEKEY.Test1_Cache, "Test1234");
	   
   }**
i am getting classcast exception.
So how can i  use ByteArraycodec. 
can u provide some snippet code for that....

**Comment by mrniko** [comment]
you have to define it in config

**Comment by nratta** [comment]
Hi , 
For  ByteArrayCodec Testing :- 
My Config file : - 
{
"singleServerConfig":{
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "address":[
         "//192.168.100.166:6379"
      ]
   },
   "threads":8,
   **"codec":!<org.redisson.codec.ByteArrayCodec>{},**
   "nettyThreads":8
}
And Test java file :- 

[RedisClientTest.java.txt](https://github.com/redisson/redisson/files/744744/RedisClientTest.java.txt)

Error: 

java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalArgumentException: Can't parse config file:/D:/digite/WorkSpace/RedisCacheDemo/bin/com/client/MyCache.json
	at org.redisson.jcache.JCachingProvider.getCacheManager(JCachingProvider.java:85)
	at org.redisson.jcache.JCachingProvider.getCacheManager(JCachingProvider.java:116)
	at com.client.RedisClient1.<clinit>(RedisClient1.java:28)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: YAML decoding problem: while scanning a tag
 in 'reader', line 13, column 12:
       "codec":!<org.redisson.codec.ByteArrayCo ... 
               ^
expected ' ', but found '{' (123)
 in 'reader', line 13, column 48:
     ... g.redisson.codec.ByteArrayCodec>{},

**Comment by mrniko** [comment]
You defined it in wrong way. Use this definition:

```
codec: {"class":"org.redisson.codec.ByteArrayCodec"},
```

**Comment by nratta** [comment]
Hi, 
Still getting Error :- 
Invalid type id 'org.redisson.codec.ByteArrayCodec' (for id type 'Id.class'): no such class found (through reference chain: org.redisson.config.Config["codec"])

Config file : - 

{
"singleServerConfig":{
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "address":[
         "//192.168.100.166:6379"
      ]
   },
   "threads":8,
   "codec": {
   "class":"org.redisson.codec.ByteArrayCodec"
   },
   "nettyThreads":8
}

**Comment by mrniko** [comment]
it has different package `org.redisson.client.codec.ByteArrayCodec` and not a `org.redisson.codec`

**Comment by nratta** [comment]
HI ,
**I am simply trying to store String value in cache using byte array codec,**
My Understanding : Codec will simply convert object in to byte array to store it on redis server
                                 And once again reconvert it into objects while fetching it from Redis Sever.
 No Extra code will be required for this .... Right !!!!!!!

**Comment by nratta** [comment]
But getting Exception : -
My code : -

public void testRedis() throws InterruptedException, IllegalArgumentException, URISyntaxException {
        MutableConfiguration<Object, Object> config = new MutableConfiguration<Object, Object>();
        config.setStoreByValue(true);
        
        URI configUri = getClass().getResource("RedisDummy.json").toURI();
        Cache<Object, Object> cache = Caching.getCachingProvider().getCacheManager(configUri, null)
                .createCache("Redis_Test27", config);
        String w_str = "Redis as String Data";
       // byte[] w_arr = w_str.getBytes();
        cache.put("Key11", w_str);
        long startTime = System.nanoTime();
       // cache.get("123");
        long spentTime = System.nanoTime() - startTime;
        System.out.println("get spentTime: " + spentTime);
    }

And my confg file : -

{
"singleServerConfig":{
      "pingTimeout":1000,
      "connectTimeout":10000,
      "timeout":3000,
      "reconnectionTimeout":3000,
      "failedAttempts":3,
      "address":[
         "//192.168.100.166:6379"
      ]
   },
   "threads":8,
  codec: {"class":"org.redisson.client.codec.ByteArrayCodec"},
   "nettyThreads":8
}

**Comment by mrniko** [comment]
ByteArrayCodec works with byteArrays only. So you have to change code line `cache.put("Key11", w_str);` to `cache.put("Key11".getBytes(), w_str.getBytes());`

**Comment by nratta** [comment]
ok thanks .
I have written code  using  SnappyCodec  . But needs to test for web app !!!
So will confirm u by tomorrow related to slowness issue.
**Can u please verify my approach for SnappyCodec !!!!!!!** 
And it will be right way to handle large  data value !!!!!!!

1.  **My Config file  having codec attribute as :-** 
    codec: {"class":"org.redisson.codec.SnappyCodec"},

2.  **And  java api** : -

public void testRedis() throws InterruptedException, IllegalArgumentException, URISyntaxException {
        MutableConfiguration<Object, Object> config = new MutableConfiguration<Object, Object>();
        config.setStoreByValue(true);
        
        URI configUri = getClass().getResource("RedisDummy.json").toURI();
        Cache<Object, Object> cache = Caching.getCachingProvider().getCacheManager(configUri, null)
                .createCache("Redis_Test38", config);
        HashMap<String, String> w_map = new HashMap<String, String>();
        w_map.put("Name", "User1");
        w_map.put("City", "Mum");
        w_map.put("Comp", "Digite");
        cache.put("Key11", w_map);
       HashMap<String,String> w = (HashMap)cache.get("Key11");
    }

**Comment by mrniko** [comment]
Looks right at first glance

**Comment by nratta** [comment]
thanks ..

**Comment by nratta** [comment]
HI , 
I am implementing Snappy on WildFly 10 with Java 8.
So these set up is taking some time.
**I have one doubt as I am not using Redis persistence**
**Even still snappy codec will be helpful na !!!!!!**

**Comment by mrniko** [comment]
> I am implementing Snappy on WildFly 10 with Java 8.

Why? it's already implemented. Just add artifact below:

            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
             <version>1.1.2.6</version>

**Comment by nratta** [comment]
No i do not mean that.

Actually when i am using snappy-java jar file with Redisson  jar file in my application.
I am getting  jdk compatbility issue 
**As my application is using Jboss 6 and Java 6.**

**For that i ma upgrading my application to WildFly 10 and Java 8.....**
