### ISSUE TITLE
Documentation on locks

### ISSUE THREAD

**Issue by johnjaylward** [redisson/redisson#755]
I was wondering if the documentation could be clarified on what happens to each of the lock types should one redisson node request a lock, then die before releasing it while another node is waiting on it.

i.e.
```java
Node1:
Lock lock = redisson.getLock("LOCK-1");
lock.lock();
try{
  //do something but the jvm is hard killed externally (power loss, reboot, etc)
} finally {
 lock.unlock();
}

Node2: called after node1 enters the lock, but before node 1 dies
Lock lock = redisson.getLock("LOCK-1");
lock.lock();
try{
  //do something
} finally {
 lock.unlock();
}
```

If the documentation could also note suggested ways to prevent deadlocking in such cases (should deadlocking occur) that would be good too. It's not clear if the distributed locking takes into account the loss of a node while holding a lock.

https://github.com/redisson/redisson/wiki/8.-distributed-locks-and-synchronizers

**Comment by mrniko** [comment]
Hi,

> what happens to each of the lock types should one redisson node request a lock, then die before releasing it while another node is waiting on it

If node crashes but the lock has been already acquired then it hangs forever until you delete it manually. To avoid this I would recommend to use `leaseTime` parameter with lock method. After specified interval locked lock will be released automatically.

> ways to prevent deadlocking 

Do you mean deadlock with single or multiple locks?

**Comment by johnjaylward** [comment]
I specifically meant single with this case. Multiple lock deadlock conditions are well documented elsewhere I think.  It would only be useful to document here if it changed for some reason due to the distributed nature of the locks.

**Comment by mrniko** [comment]
Could you provide some example of deadlock with single lock?

**Comment by johnjaylward** [comment]
Just this example of a node holding a lock and dying. Even if the node comes back up (JVM restart), it would have a different thread ID and would be unable to unlock the lock. this would deadlock the same node as well as other nodes as the lock resource is never released.

Other than that I can't think of any.

**Comment by mrniko** [comment]
`leastTime` resolves your case

**Comment by johnjaylward** [comment]
Yes, and I've updated my code to match that. I was just hoping to update the documentation to note that Node loss while a lock is open could lead to a permanent lock.

**Comment by mrniko** [comment]
Done. Documentation has been updated
