### ISSUE TITLE
Allow to specify Redisson instance/config during JCache cache creation

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#759]

**Comment by mrniko** [comment]
Done. JCache documentation [updated](https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#143-jcache-api-jsr-107-implementation)

**Comment by jackygurui** [comment]
Chinese wiki updated [accordingly](https://github.com/redisson/redisson/wiki/14.-第三方框架整合#143-java缓存标准规范jcache-api-jsr-107)
