### ISSUE TITLE
NullPointerException on some weird Redis cluster status

### ISSUE THREAD

**Issue by ylorenza** [redisson/redisson#761]
Hi,

I use redisson 3.2.3 on my project. I try to do some Resilience test and sometimes i had this exception : 

```
2017-02-03 13:01:44.318  WARN   --- [redisson-netty-1-6] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by org.redisson.cluster.ClusterConnectionManager$5.operationComplete()

java.lang.NullPointerException: null
	at org.redisson.cluster.ClusterConnectionManager.checkMasterNodesChange(ClusterConnectionManager.java:514)
	at org.redisson.cluster.ClusterConnectionManager.access$1400(ClusterConnectionManager.java:65)
	at org.redisson.cluster.ClusterConnectionManager$5.operationComplete(ClusterConnectionManager.java:394)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
```

This is my test : 
 insert value continously
 kill master
 wait 15s
 restart my node
 wait 5
 start from the begining.

The last cluster status print by ClusterConnectionManager.java:390 (log.debug("cluster nodes state from {}:\n{}", connection.getRedisClient().getAddr(), nodesValue);) is

```
2017-02-02 16:01:37,585|DEBUG|sogood |redisson-netty-1-91|||o.r.c.ClusterConnectionManager|cluster nodes state from /10.98.67.184:52000:
b7c355273d2c09eab72bb13b0111463f6c7e82df 10.98.68.16:52000 master - 0 1486123810474 247 connected 13107-16383
49f64bd7c6749a78fe20bbe8b8d4edbf8b2ed711 10.98.67.177:52000 slave 888724ee5ace06c9df65f2ea78e34df9960d3df7 0 1486123808464 254 connected
2cdd5ca8c9d406469d6147c386d5ccbca8d9f771 10.98.68.14:52000 slave b7c355273d2c09eab72bb13b0111463f6c7e82df 0 1486123809472 247 connected
f1a64ada3b196f0ede36f9c76f3e9b68e51d9e1f 10.98.68.15:52000 slave 888724ee5ace06c9df65f2ea78e34df9960d3df7 0 1486123812486 254 connected
56b94b881bd65c2a5a4afad813e86834343c79c5 10.98.68.11:52000 slave ffccc1ce6b77f0001bdbf50c46a48a5210272517 0 1486123811480 251 connected
26ffe21713c32342dc5205d6df2fe705b5a36bf9 10.98.68.13:52000 master - 0 1486123809469 253 connected 3277-6553
f19eb78f3165b800f8b2189f307c1ba1d3563476 10.98.68.7:52000 slave 3f0de04cfedfbedd7d33f6e97b10651cbb33f0ef 0 1486123812481 256 connected
19e401763468351ea5fd4a427e79036a622f1dfa 10.98.67.180:52000 slave ffccc1ce6b77f0001bdbf50c46a48a5210272517 0 1486123808464 251 connected
ffccc1ce6b77f0001bdbf50c46a48a5210272517 10.98.67.184:52000 myself,master - 0 0 251 connected 0-3276
79fa0a09c3c2f49f816843fcd4e762f428d96984 10.98.67.175:52000 slave 26ffe21713c32342dc5205d6df2fe705b5a36bf9 0 1486123810474 253 connected
299302f881862c83c4f4046df9da28a068b76b40 10.98.68.17:52000 slave f19eb78f3165b800f8b2189f307c1ba1d3563476 0 1486123809469 201 connected
3f0de04cfedfbedd7d33f6e97b10651cbb33f0ef 10.98.68.12:52000 master - 0 1486123812481 256 connected 6554-9829
888724ee5ace06c9df65f2ea78e34df9960d3df7 10.98.68.10:52000 master - 0 1486123812481 254 connected 9830-13106
9377d08613f8e0717488fa383535182a561e1693 10.98.68.9:52000 slave 26ffe21713c32342dc5205d6df2fe705b5a36bf9 0 1486123810474 253 connected
f20f77ed851c01ed34c9d91bbea0e512616f5430 10.98.67.182:52000 slave b7c355273d2c09eab72bb13b0111463f6c7e82df 0 1486123808464 247 connected
```

As you can see, node 299302f881862c83c4f4046df9da28a068b76b40 is slave of f19eb78f3165b800f8b2189f307c1ba1d3563476 which is a another slave (Maybe a redis bug ?)

So ClusterConnectionManager.parsePartitions generate for that slave a line like that
` ClusterPartition [nodeId=f19eb78f3165b800f8b2189f307c1ba1d3563476, masterFail=false, masterAddress=null, slaveAddresses=[redis://10.98.68.17:52000], failedSlaves=[], slotRanges=[]]`

And in ClusterConnectionManager.checkMasterNodesChange we have NullPointer on that if
```
if (!newPart.getMasterAddress().equals(currentPart.getMasterAddress())) {
                        continue;
                    }
```

I'm not sur how, but it seem after that there is no other scheduleClusterChangeCheck and  this is a big probleme.

I hope this is clear. (Sorry about my english, i'm a french guy).
I'm going to to do a PR for this particular problem, but i want help to understand why this NullPoint completly kill the scheduleClusterChangeCheck thread

**Comment by mrniko** [comment]
Are you sure that Redis Cluster initialized properly?

**Comment by ylorenza** [comment]
Pretty sure, but i can reproduce this monday and get redis logs if you want

**Comment by mrniko** [comment]
This would be nice to have

**Comment by ylorenza** [comment]
Sorry i'm late

I can reproduce this bug on my computer here all the elements

I have 15 redis node, 5 master and 10 slave. Here is one of my config file (all the same except for port)
[redis_10000.conf.txt](https://github.com/redisson/redisson/files/757141/redis_10000.conf.txt)

I launch a unit test to insert data into my cluster with redisson
[RedisTest.java.txt](https://github.com/redisson/redisson/files/757160/RedisTest.java.txt)

When this test is running i launch a script which kill a random master, wait for 15s, relaunch my redis node, wait 5s et do it again.
[kill-random-redis-master_local.sh.txt](https://github.com/redisson/redisson/files/757555/kill-random-redis-master_local.sh.txt)

And  this is the full log of my test. At the end we have the null pointer exception
[spring.log.txt](https://github.com/redisson/redisson/files/757569/spring.log.txt)

**Comment by mrniko** [comment]
Which command are you using to create Redis cluster?

**Comment by ylorenza** [comment]
This is my init script
[init_local_cluster.sh.txt](https://github.com/redisson/redisson/files/757640/init_local_cluster.sh.txt)

**Comment by mrniko** [comment]
Could you please build it with 3 nodes only and send me configs? 1 master and one slave and another slave of slave.

**Comment by ylorenza** [comment]
I dont understand why you need this but i did it
[3nodescluster.tar.gz](https://github.com/redisson/redisson/files/760639/3nodescluster.tar.gz)

**Comment by mrniko** [comment]
Thanks! It helped a lot. I have fixed this bug. Please check it too.
