### ISSUE TITLE
Problem with Rlock - unlock not releasing lock to waiting threads

### ISSUE THREAD

**Issue by swilson11** [redisson/redisson#763]
I am seeing an intermittent issue with Rlocks. I am implementing what is basically a distributed cyclic barrier using Redisson.

I am running multiple instances of a service on different virtual machines. Each instance receives multiple HTTP REST api requests, handled by multiple threads. As each request is received it waits at a redisson count down latch until the threshold for # of requests has been reached.

At this point, I need one thread to calculate the results and store it in redis so it can be available to all the other threads across all instances. So each thread tries to acquire an Rlock (with TTL of 5 seconds). One thread gets the lock, does the calculation, and stores the result back to redis. It then releases the Rlock.

Now all the other threads that are waiting on the Rlock can (one at a time) acquire the lock, see that the data is already in redis, and simply release the lock and send the result back via HTTP, without repeating the calculation.

We are using a master/slave redis cluster with 1 master and 2 or more slaves. As well as using redisson for the countdown latch and rlock, we use jedis for standard redis reads and writes, but never using the same keys as we use for the latch and locks.

This is all working about 99% of the time. However periodically, I can see that after the Rlock is released, none of the threads that are waiting for it are able to acquire the lock. I was originally using lock(), and finding that HTTP threads were hanging forever. I switched to using trylock, and this returns, but it returns false, indicating a timeout waiting for the lock.

I have added logging to be 100% sure that unlock is being called on the lock in the failure case. Any suggestions on how I can debug this issue, or any known problems with our configuration that might be causing it? 

We are running Redisson 3.2.3 and redis 3.2.5

Thanks for the help,

Sue

**Comment by mrniko** [comment]
Which Redis configuration do you use?

**Comment by swilson11** [comment]
I tried updating Redis to 3.2.7 but the problem is still there. When it happens, it seems to happen frequently for windows of about 40 minutes or so, then go away for days at a time. I looked at the redis and redis sentinel logs and I don't see any activity around the time of the failures, so I don't think it's related to any failover scenarios. There are also no java Exceptions in the logs. I've attached the redis configuration file.

Thanks for the help.

Sue
[redis.txt](https://github.com/redisson/redisson/files/791177/redis.txt)

**Comment by mrniko** [comment]
PubSub by default connects to slaves. I think it's time to add option for master too. Hope this help in your case

**Comment by swilson11** [comment]
Sorry, I didn't quite follow what you meant - is there a configuration setting you think I need to change, so that PubSub will always go though the master?

**Comment by mrniko** [comment]
No, I'm just planning to add it. Anyway redis pubsub on any node listen all events, I didn't get why it doesn't work in your case.

**Comment by mrniko** [comment]
I have added `subscriptionMode` option. You can set it to `MASTER` and try in your environment. This should help

**Comment by swilson11** [comment]
Thanks, will try this out.
