### ISSUE TITLE
compatible with Netty5.0.x?

### ISSUE THREAD

**Issue by alexanderlc** [redisson/redisson#767]
when to?

**Comment by alexanderlc** [comment]
org.redisson.connection.MasterSlaveConnectionManager
Line 183:
new NioEventLoopGroup(cfg.getNettyThreads(), new DefaultThreadFactory("redisson-netty"));
java.lang.NoSuchMethodError: io.netty.channel.nio.NioEventLoopGroup
not compatible with Netty5.0.x!

**Comment by mrniko** [comment]
development of netty 5.x was abandoned

**Comment by alexanderlc** [comment]
Got it！Thanks

**Comment by johnou** [comment]
https://github.com/netty/netty/issues/4466
