### ISSUE TITLE
Lz4 or Snappy ?

### ISSUE THREAD

**Issue by lpatil44** [redisson/redisson#769]
Which one gives better compression result when used with redisson in our application ?
Description :
1- I have tested both compression algorithms by importing their .jar files.
2- I have written one java program which creates a hashmap for 15000 entries.
3- I have compressed this hashmap with both algorithm and in that following is the result .

Snappy Output for hashMap with 15000 entries Object
original size :172780(bytes)
compressed size : 8109
uncompressed size :172780
Snappy Version : 1.1.2

LZ4 Output for hashMap with 15000 entries Object

original size :172780
compressed size  : 688
uncompressed size :172780

Which one would be a better option for us in a longer run in terms of performance and code compatibility?

**Comment by lpatil44** [comment]
Any updates ?

**Comment by mrniko** [comment]
It mostly depends on your objects structure and environment. I'm afraid there is no right answer to your question. Although most of Redisson users prefer Snappy

**Comment by johnou** [comment]
https://github.com/google/snappy

Snappy is a compression/decompression library. **It does not aim for maximum
compression**, or compatibility with any other compression library; instead,
it aims for very high speeds and reasonable compression. For instance,
compared to the fastest mode of zlib, Snappy is an order of magnitude faster
for most inputs, but the resulting compressed files are anywhere from 20% to
100% bigger. (For more information, see "Performance", below.)

As @mrniko stated it depends on your application requirements, but you are likely to get higher throughput with the tradeoff of cache size and the opposite with LZ4.
