### ISSUE TITLE
Redisson Sentinel and pub/sub

### ISSUE THREAD

**Issue by giantninja** [redisson/redisson#772]
Is there a simple way I'm missing to get the current master from redisson setup using sentinel?  I'd like to subscribe to channels/topics but only on the current master as reported via sentinel.  When I subscribe to a topic, it chooses a server randomly, but I'd like to keep it to the master so I can get the number of subscribers and number of received publishes (external app doing the publishing to communicate with Java app via redis pub/sub), which doesn't work when you publish to master and subscribe on a slave (although the message is received, just no stats).

I figure either one of two solutions would work.  Query sentinel for the current master and then setup singleServer client to that master or would setting the `SentinelServersConfig` to read from master work to limit the redissonClient to master only?

i.e.
```java
Config config = new Config();
SentinelServersConfig sentinelConfig = config.useSentinelServers();

sentinelConfig
    .setMasterName(SENTINEL_MASTER_NAME)
    .setPassword(SENTINEL_PW)
    .setDatabase(REDIS_DB)
    .setReadMode(ReadMode.MASTER);
```

What would be the ideal way to setup the redisson client to subscribe to channels/topics so the publisher (ext app) can see those nubmers for subscribers and msg received etc ?

As always, thanks for any help you provide

**Comment by giantninja** [comment]
Just came back to report that configuring the sentinel client to read from master is essentially letting me use sentinel but restrict to a single server (master) like so:

```java
Config config = new Config();
SentinelServersConfig sentinelConfig = config.useSentinelServers();

sentinelConfig
    .setMasterName(SENTINEL_MASTER_NAME)
    .setPassword(SENTINEL_PW)
    .setDatabase(REDIS_DB)
    .setReadMode(ReadMode.MASTER);

// loop through our sentinels and add them to the configuration
for (String sentinel : SENTINELS) {
    sentinelConfig.addSentinelAddress(sentinel);
}
RedissonClient pubSubClient = Redisson.create(config);
...
```

and subscribing to topic/channel like this:
```java
RTopic<String> apiSendJsonTopic = pubSubClient.getTopic(apiChannel, StringCodec.INSTANCE);
apiSendJsonTopic.addListener((channel, msg) -> {
    // process msgs published on apiChannel
});

```

This is working as I had hoped/expected, but I just would like to confirm, since I can't really test the failover yet since the current sentinel setup is live in production, but in the case of the current master going down and one of the slaves being promoted to the new master, will the listener be automatically re-subscribed? or is there an event I need to listen for to resubscribe to the new master?

Thanks again.

**Comment by mrniko** [comment]
> This is working as I had hoped/expected, but I just would like to confirm, since I can't really test the failover yet since the current sentinel setup is live in production, but in the case of the current master going down and one of the slaves being promoted to the new master, will the listener be automatically re-subscribed?

Of course.

`subscriptionMode` setting was added. Please use it if you want subscribe to master only
