### ISSUE TITLE
Redisson connects to slaves of other masters

### ISSUE THREAD

**Issue by mabn** [redisson/redisson#774]
When sentinel announces a new slave:

`+slave slave 1.1.1.1:6379 1.1.1.1 6379 @ redis-master-A 2.2.2.2 6379`

redisson adds this slave to its configuration but it **does not** check if it's a slave of the master used by redisson. As a result redisson attempts to connect to another cluster.

The issue is in `SentinelConnectionManager.onSlaveAdded`

**Comment by mrniko** [comment]
Interesting. Do you use multi-master sentinel configuration?

**Comment by mabn** [comment]
Yes. There's one sentinel cluster managing many redis masters. Each master has a slave. 
Masters (and their slaves) belong to different projects, have different passwords, different configuration and should have nothing in common.

**Comment by mrniko** [comment]
Fixed

**Comment by mabn** [comment]
Thank you!
