### ISSUE TITLE
Indefinite lock lost during master failover

### ISSUE THREAD

**Issue by MrThomasWagner** [redisson/redisson#775]
I've found my indefinitely held locks will sometimes disappear after a master/slave failover.  The block [here](https://github.com/redisson/redisson/blob/6f7f43716aa78c99ec4572685f55accc0f6816f7/redisson/src/main/java/org/redisson/RedissonLock.java#L219) will not reschedule a renewal if the attempt of the update fails.  

The update can fail during a failover, in which case the lock is gone for good.

The exception that gets thrown when the update fails:

```
org.redisson.RedissonLock: Can't update lock {chaos:pixel-gun}:/2rQnzwnEeOcovlp1fBZCw:key expiration
org.redisson.client.RedisTimeoutException: Redis server response timeout (3000 ms) occured for command: (EVAL) with params: [if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); retu..., 1, {chaos:pixel-gun}:/2rQnzwnEeOcovlp1fBZCw:key, 30000, 3edaecd7-8b5a-4c47-bdc6-fff775044369:82] channel: [id: 0x48ee8af7, 0.0.0.0/0.0.0.0:56264]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:647) ~[redisson-3.2.3.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) [netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:656) [netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) [netty-all-4.0.23.Final.jar:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by mrniko** [comment]
Do you think it's important to give it another try?

**Comment by MrThomasWagner** [comment]
I created the behavior numerous times, so no.  

That method I linked to explains the behavior better than I can with words.  Don't you think?  It doesn't hit the block commented with ``` // reschedule itself``` in the event of failure.

I'm instantiating the lock with a lease time of ```-1``` for the indefinite behavior.

I'm triggering the failover by giving the master ```debug sleep n``` with ```n > failover time limit ```

**Comment by MrThomasWagner** [comment]
I imagine there could be a race condition with reacquiring the lock in the case where you fail to renew it before it expires.  

Is this expected functionality because of this? If so, I'd really appreciate a fore-warning in the docs somewhere.

**Comment by mrniko** [comment]
Default LOCK_EXPIRATION_INTERVAL_SECONDS is 30 seconds, so if your failover process longer than this period of time you'll lose your lock. I would recommend to set `leaseTime` parameter to several hours or so.

**Comment by MrThomasWagner** [comment]
Thanks for the feedback. In our case, we have our threads continue to use the indefinite behavior but routinely check to make sure they still have ownership of the lock.

**Comment by mrniko** [comment]
> I imagine there could be a race condition with reacquiring the lock in the case where you fail to renew it before it expires.

Lock owner are always checked before lock renewal https://github.com/redisson/redisson/blob/6f7f43716aa78c99ec4572685f55accc0f6816f7/redisson/src/main/java/org/redisson/RedissonLock.java#L206

**Comment by MrThomasWagner** [comment]
Do you think it'd be worth it to make LOCK_EXPIRATION_INTERVAL_SECONDS configurable and/or add a warning in the documentation?  I'd be happy to help with an update like that, and will plan to give that a shot this weekend.

**Comment by mrniko** [comment]
I appreciate any help! I would add global setting like `lockExpirationInterval` to `org.redisson.config.Config` object.

**Comment by mrniko** [comment]
lockWatchdogTimeout config parameter added.
