### ISSUE TITLE
When try to define some variable throught redisson, it will read all value ofthe key! (当通过 redisson定义变量的时候，redisson会读取redis中当前key所有的值)

### ISSUE THREAD

**Issue by tonychenz** [redisson/redisson#778]
when using the codes such as nether( found it when debug) :
RMap<String, Integer> testMapAnother = redisson.getMap("testMap");
RList<Integer> test = redEnRedis.getList("test");

Redisson will read all the value of the key(bucket will not), I think there is no need to read values from redis when the just define the variable. We don't want the data that time, but redisson read all values of the key and this will cause some problem especially when the key values is big! So if there any config or what should i do so that i can  avoid this? Currently I am useing the version 2.6.0

中文:
当使用 redisson 定义变量的时候, 会去读取redis中key的所有value，下面这样(debug 模式下发现的)：
RMap<String, Integer> testMapAnother = redisson.getMap("testMap");
RList<Integer> test = redEnRedis.getList("test");

个人认为这个其实没有必要，因为这个时候还么有操作redis中的数据，下面具体的get啊之类的语句才去操作redis中的数据！那么是不是有那个配置或者升级版本可以 规避这个问题呢？目前使用版本 2.6.0

**Comment by mrniko** [comment]
That must be some mistake, because no map or list load all values of key till you execute `readAll`, `readAllKeySet`, `readAllValues` or `readAllEntrySet` methods.

**Comment by tonychenz** [comment]
@mrniko Is there any way I can contact with u? Cause when debugint I actually found that! and I have a screenshot for this, Plese see it bellow! Thx a lot.
Config file:
{
  "sentinelServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":5000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,
    "password":"XXXXXXX",
    "subscriptionsPerConnection":5,
    "clientName":"XXXXXX",
    "loadBalancer":{
      "class":"org.redisson.connection.balancer.RoundRobinLoadBalancer"
    },
    "slaveSubscriptionConnectionMinimumIdleSize":1,
    "slaveSubscriptionConnectionPoolSize":50,
    "slaveConnectionMinimumIdleSize":5,
    "slaveConnectionPoolSize":250,
    "masterConnectionMinimumIdleSize":5,
    "masterConnectionPoolSize":250,
    "readMode":"MASTER",
    "sentinelAddresses":[
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX"
    ],
    "masterName":"XXXXXXXX",
    "database":0
  },
  "codec":null,
  "useLinuxNativeEpoll":false
}

![redisson](https://cloud.githubusercontent.com/assets/8817853/23155417/79e38d8c-f84d-11e6-9fff-76517b01bfe9.png)
![redissonconfig](https://cloud.githubusercontent.com/assets/8817853/23155518/dc6bbf38-f84d-11e6-81c2-d871b8c5679e.png)

**Comment by mrniko** [comment]
Debug uses iterator, of course it read all value through it.

**Comment by mrniko** [comment]
> Is there any way I can contact with u? 

Via gitter chat session

**Comment by tonychenz** [comment]
@mrniko It means that it is normal that when debuging I see the values? It is great that getting help from u! thx u

**Comment by mrniko** [comment]
@tonychenz yes

**Comment by jackygurui** [comment]
@tonychenz  这是IDE在你调试的时候通过Iterator方式自动获取的。如果你的鼠标不放上去他是不会主动获取值的。

**Comment by tonychenz** [comment]
@jackygurui 嗯，明白了，谢谢

**Comment by jackygurui** [comment]
@tonychenz OK，那我先把这个贴关了。
