### ISSUE TITLE
Intermittent issue with MapCache

### ISSUE THREAD

**Issue by China-Bill-Git** [redisson/redisson#779]
org.redisson.client.RedisException: ERR Error running script (call to f_286dd696309f4ab2005d9df55e2410a1170fe3b3): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0xafbb4b7e, L:/192.168.50.18:63163 - R:/10.10.10.14:7000] command: CommandData [promise=org.redisson.misc.RedissonPromise@3b015ec9, command=(EVAL), params=[local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t, val = struct.unpack('dLc0', value); local expireDate = 92233720368547758; local expireDateScore = redis.call('zscore', KEYS[2], ARGV[2]); if expireDateScore ~= false then expireDate = tonumber(expireDateScore) end; if t ~= 0 then local expireIdle = redis.call('zscore', KEYS[3], ARGV[2]); if expireIdle ~= false then if tonumber(expireIdle) > tonumber(ARGV[1]) then local value = struct.pack('dLc0', t, string.len(val), val); redis.call('hset', KEYS[1], ARGV[2], value); redis.call('zadd', KEYS[3], t + tonumber(ARGV[1]), ARGV[2]); end; expireDate = math.min(expireDate, tonumber(expireIdle)) end; end; if expireDate <= tonumber(ARGV[1]) then return nil; end; return val; , 3, Flag_LoadMerTranSum2Redis, redissontimeoutset{Flag_LoadMerTranSum2Redis}, redissonidleset{Flag_LoadMerTranSum2Redis}, 1483429282335, Risk_tranSum_init_string], codec=org.redisson.codec.FstCodec@56f5fc62]

**Comment by mrniko** [comment]
This issue occurs when RMap and RMapCache objects are bonded to the same name

**Comment by h920526** [comment]
how to fix it ?
