### ISSUE TITLE
Tomcat Manger App still showing session count

### ISSUE THREAD

**Issue by rajeshdhanana** [redisson/redisson#781]
Hi,

I am have implemented redisson tomcat session manager. I am able to see sessions created on redis-server.  But when I verify tomcat manager app - I am seeing number of sessions there as well. As session being stored in redis - i believe tomcat manager app should show **0** number of session. Please let me know if this fine.

Regards,
Rajesh.

**Comment by rajeshdhanana** [comment]
Any Update on this?

**Comment by mrniko** [comment]
Because all sessions are registered in Tomcat's context
