### ISSUE TITLE
Redisson Client Memory Issues

### ISSUE THREAD

**Issue by HarryTheHawk** [redisson/redisson#782]
Hello,

I've been stress-testing Redis using Redisson as the client in single server mode and am experiencing steady memory consumption as I increase the client transaction rate, to the point of memory exhaustion.  Indeed, it appears Redisson connections are using gigabytes of memory.  I'm performing simple batch gets (see code snippet below).

I'm initializing and sharing the Redisson client via a simple singleton:

```java
public final class RedissonConnectionProvider {

    public static final String IP_KEY = "RedisIP";
    public static final String DEFAULT_IP = "localhost";

    private static final String REDIS_IP;
    private static final String DEFAULT_PORT = "6379";

    private static final int CONNECTION_POOL_SIZE = 200;
    private static final int CONNECTION_POOL_MIN_IDLE_SIZE = 100;

    private static final RedissonConnectionProvider INSTANCE = new RedissonConnectionProvider();
    private static final Config REDISSON_CONFIG = buildStandaloneConfig();
    private static final RedissonClient REDISSON_CLIENT = Redisson.create(REDISSON_CONFIG);

    public static synchronized RedissonConnectionProvider getInstance() {
        return INSTANCE;
    }

    public static synchronized RedissonClient getRedissonClient() {
        return REDISSON_CLIENT;
    }

    private RedissonConnectionProvider() {}

        private static Config buildStandaloneConfig() {

        Config config = new Config();

        SingleServerConfig singleServerConfig = config.useSingleServer();

        singleServerConfig.setAddress(REDIS_IP + ":" + DEFAULT_PORT);

        singleServerConfig.setConnectionPoolSize(CONNECTION_POOL_SIZE);
        singleServerConfig.setConnectionMinimumIdleSize(CONNECTION_POOL_MIN_IDLE_SIZE);

        // we are storing values as raw strings...
        config.setCodec(StringCodec.INSTANCE);

        return config;
    }
}
```

How I'm using batch:

```java
...
...
Map<String, Object> m = new HashMap<>();

final RBatch batch = noSQLClient.createBatch();

keys.forEach((k) -> batch.getBucket(REDIS_KEY_PREFIX + k).getAsync());

final RFuture<List<?>> response = batch.executeAsync();

final RFuture<List<?>> future = response.sync();

final Iterator<?> responseIter = future.getNow().iterator();

final Iterator<String> keyIter = keys.iterator();

while (responseIter.hasNext() && keyIter.hasNext()) {
    Object obj = responseIter.next();
    String key = keyIter.next();
    if (obj != null) {
        m.put(key, obj);
    }
}
...
...
```

My Redis instance has about 54 million keys and uses about 20GB of memory. 

<pre>
XX.XXX.XXX.XXX:6379> info clients
# Clients
connected_clients:102
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
</pre>

Any advice you could provide would be much appreciated.

Thanks!

HarryTheHawk

**Comment by mrniko** [comment]
Hi, could you please attach heap dump?

**Comment by mrniko** [comment]
How did you get keys collection?

**Comment by HarryTheHawk** [comment]
The key generation scheme has been in place for a long while in production; it is not likely related. I think the main thing I was looking for was confirmation that I wasn't misusing Redisson as far as how I initialize and share the Redisson client and then use it for conducting trivial batch queries in a high transaction rate, multi-threaded application.

Meanwhile, I'll gather and take a closer look at a current heap dump.

Thanks!

**Comment by mrniko** [comment]
> Meanwhile, I'll gather and take a closer look at a current heap dump.

Thank you! I'm looking forward to it

**Comment by HarryTheHawk** [comment]
Hello,

After further testing and heap dump analysis I've determined that there is no memory leak occurring. It appears that there is additional/unexpected memory consumption occurring outside of the Redisson client itself. I've yet to isolate it, but at this point I've ruled out Redission as a contributor.

Thanks!

**Comment by mrniko** [comment]
@HarryTheHawk Cool! It's nice to know that
