### ISSUE TITLE
Using redisson as JCache implementation AND for session replication

### ISSUE THREAD

**Issue by JanDoerrenhaus** [redisson/redisson#784]
We want to use redisson for JCache and for Tomcat session replication.

However, if we place the two jars inside the /lib folder (as explained by the documentation), the serialization of cached objects fails (ClassNotFoundException). And if we place them in the application, the application will not start because the application context initialization cannot find the RedissonSessionManager.

How can we configure redisson for both use cases?

**Comment by mrniko** [comment]
Have you tried to put jars inside /lib folder and webapp?

**Comment by JanDoerrenhaus** [comment]
Yes, if we put the jars inside both the /lib folder and webapp, we get the exception [this guy also has](https://github.com/redisson/redisson/issues/783):

`com.fasterxml.jackson.databind.JsonMappingException: Class org.redisson.codec.SerializationCodec not subtype of [simple type, class org.redisson.client.codec.Codec] (through reference chain: org.redisson.config.Config["codec"])`

**Comment by mrniko** [comment]
You could try to set <Loader delegate="true"/> like mentioned in docs https://travelmaps.state.gov/docs/config/loader.html

**Comment by JanDoerrenhaus** [comment]
While this may solve the immediate problem, I was rather hoping for a solution on a redisson configuration level. Something that is not so potentially disastrous as to change the entire class loading order.

Using two fully supported features of redisson should not rely on radically changing the container configuration, I think. Is there any other way?

**Comment by schroenser** [comment]
Setting `<Loader delegate="true"/>` is not the solution. This messes with class loading in such a way that our EE container (TomEE) does no longer resolve beans correctly `(javax.enterprise.inject.UnsatisfiedResolutionException`).

**Comment by mrniko** [comment]
@JanDoerrenhaus @schroenser Thanks guys! I'm working on solution

**Comment by mrniko** [comment]
Fixed! Please check

**Comment by schroenser** [comment]
Yes, it works. Thank you.
