### ISSUE TITLE
Use PSETEX for time to live with precision of less than second

### ISSUE THREAD

**Issue by kringol** [redisson/redisson#791]
Right now only usage of SETEX is mapped. 
Therefore even though the API allows setting ttl using value(long) and TimeUnit.
Using values like 1500ms gets translated into 1s, since it's using SETEX command which only takes seconds.
And using values like 700ms gets translated to 0s, which makes the command fail by being an invalid SETEX parameter ("ERR invalid expire time in setex").

Unless there is performance/memory implication i am not aware, using PSETEX for higher precision should cover that
https://redis.io/commands/psetex

**Comment by mrniko** [comment]
Quite important remark! I'll replace setex usage with psetex

**Comment by kringol** [comment]
Thanks @mrniko.
If so, please keep also in mind EXPIRE vs PEXPIRE
https://redis.io/commands/pexpire

**Comment by mrniko** [comment]
Yeah, I'm aware about PEXPIRE and other similar command. They already used in RedissonExpirable object

**Comment by mrniko** [comment]
Done
