### ISSUE TITLE
More modular/optional dependency management

### ISSUE THREAD

**Issue by smigfu** [redisson/redisson#793]
We are using Redisson in an OSGi environment and have a lot of trouble with updating to new versions due to additional dependencies being introduced for optional features.

In OSGi we have to make sure that appropriate bundles are available for each mvn-dependecy (whether they are only compile time or runtime) b/c the mvn-bundle-plugin will generate "Import-Packages" for these. As said that had been kind of a burden in the past b/c not all dependencies are available as OSGi-bundles.

By optional features I am mostly talking about different compression-, serialization-algorithms, javax.cache-api, Spring-Cache, etc. 

I have somewhat two ideas around this:

1. (simplistic, short term): mark dependencies for "optional" features as an optional mvn-dependeny. By that the mvn-bundle-plugin will also mark the "Import-Packages" as optional.

2. (sophisticated, long term): split up the redisson library into a core-library which contains only the core functionality. Create separate projects for each compression and serialization. Which only contain the implementation of the CODEC, etc. The same for Spring- and javax.cache: they should really be two different libraries which build upon the core library. Every user can then decide which libraries need to be added to the project.

**Comment by smigfu** [comment]
https://github.com/redisson/redisson/pull/794 is an example for what we are currently using in our environment. If would be a start for the short term solution.

**Comment by mrniko** [comment]
Short term solution looks cool! Merged
