### ISSUE TITLE
Setting expiry

### ISSUE THREAD

**Issue by bjdodo** [redisson/redisson#8]
Hi 
I could not find a way to set expiry for the contents of the cache from within Java. Is this true, or did I miss something?

Thank you
Jozsef

**Comment by ketankhairnar** [comment]
@mrniko I tried to implement RExpirable interface but there is no way to create connection-manager. I referred RedissonExpirable and other objects extending from it. 

It seems that Connection Manager etc are well encapsulated. Can you point to me to any example where RExpirable is implemented outside Redisson code base.

thanks in advance.

**Comment by mrniko** [comment]
@silver2k yes, now it's implemented in a new `RCache` object. Try it.
