### ISSUE TITLE
add attribute distribution lock to "LiveObject"

### ISSUE THREAD

**Issue by kelespring** [redisson/redisson#803]
MyLiveObject myLiveObject = service.get(MyLiveObject.class, "1");
//distribution lock
lock(myLiveObject.GetPressKey()){
       if(myLiveObject.GetPressKey()==“”){
           do something...
           myLiveObject.setPressKey("A");
       }else{
           System.out.println("you already press key");
       }
}finally{
     //releaseLock
     releaseLock(myLiveObject.GetPressKey()))
}

**Comment by mrniko** [comment]
@jackygurui Any thoughts?

**Comment by jackygurui** [comment]
Will be implemented by using getLock(K key) method from RMap
