### ISSUE TITLE
auto config between 'dev' and 'prod' environment

### ISSUE THREAD

**Issue by huigesv123** [redisson/redisson#804]
This is my application-dev.yml file
`spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
    singleServerConfig:
      idleConnectionTimeout: 10000
      pingTimeout: 1000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      reconnectionTimeout: 3000
      failedAttempts: 3
      password: 12345678
      subscriptionsPerConnection: 5
      clientName: null
      address: "redis://127.0.0.1:6379"
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      connectionMinimumIdleSize: 10
      connectionPoolSize: 64
      database: 0
      dnsMonitoring: false
      dnsMonitoringInterval: 5000
    threads: 2
    nettyThreads: 2
    useLinuxNativeEpoll: true`

How can i config this in Application.java in Spring-boot?

**Comment by mrniko** [comment]
You can define redisson as usual bean, like this:
```java
    @Bean(destroyMethod="shutdown")
    RedissonClient redisson() throws IOException {
        Config config = new Config();
        config.useClusterServers().addNodeAddress(configuration.getRedisNodes());
        return Redisson.create(config);
    }
```
