### ISSUE TITLE
xml schema not working

### ISSUE THREAD

**Issue by thoslin** [redisson/redisson#805]
So I am setting up redisson with spring per the doc https://github.com/redisson/redisson/wiki/14.-Integration%20with%20frameworks#141-spring-framework. However the schema doesn't seem to be working. I'm getting 301 and is redirected to the homepage of redisson. Am I missing something? 
Please check following links:
http://redisson.org/schema/redisson
http://redisson.org/schema/redisson/redisson.xsd

Thanks!

**Comment by jackygurui** [comment]
Hi, this feature is will be available in the next release. I just finished the documentation in preparation for it. Meanwhile you can checkout the master branch and use it in the same way as the tests were used. https://github.com/redisson/redisson/blob/master/redisson/src/test/resources/org/redisson/spring/support/namespace.xml

**Comment by mrniko** [comment]
Fixed. Please reset cache before the try.
