### ISSUE TITLE
what cause the wrong?

### ISSUE THREAD

**Issue by boying52** [redisson/redisson#806]
{"success":false,"message":"ERR Error running script (call to f_286dd696309f4ab2005d9df55e2410a1170fe3b3): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0xc42f8263, L:/10.28.11.46:57841 - R:/10.4.19.105:5002] command: CommandData [promise=org.redisson.misc.RedissonPromise@187b0930[Not completed], command=(EVAL), params=[local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 3, quickQueryCount, redisson__timeout__set__{quickQueryCount}, redisson__idle__set__{quickQueryCount}, 1489468477463, fa2512ba3ddae61295cff5528449149d], codec=org.redisson.codec.FstCodec@472b2094]"}

I have a issue,blew the exception it's what mean?

**Comment by mrniko** [comment]
Seems you're using two different types of Redisson objects with same name

**Comment by boying52** [comment]
means  FstCodec Serialize conficts?

**Comment by jackygurui** [comment]
It means you may have a situation where the key 'abc' is used as a RedissonMapCache in one place but later it is used as a RedissonMap in other places.

**Comment by boying52** [comment]
哦，不好意思英文蹩脚了，最近项目中发现，偶尔会报错，但是我查了一下基本没有问题，但是发现一个问题，就是出现这个错误时都是tomcat重新部署的时候

**Comment by jackygurui** [comment]
这个问题出现的原因是因为同一个key在不同的地方被用作为不同的Redisson类了，比如'abc'在某一个地方是作为RedissonMapCache在使用，但是在其他的地方却作为RedissonMap来使用。这种情况下就会出现上面提到的错误。

**Comment by boying52** [comment]
RedissonMapCache：我刚刚找了一遍，为了保证产生一直的配置
我们这样做了
public class AistRedissonConfigMap<K, V> extends HashMap<K, V>{
    
    private static final long serialVersionUID = -680695743692664715L;

    private String defaultCacheConfigName = "";
    
    @Override
    public V get(Object key) {
        V v = super.get(key);
        if(v == null && key instanceof String){
            v = super.get(defaultCacheConfigName);
            super.put((K) key, v);
        }
        return v;
    }

    public void setDefaultCacheConfigName(String defaultCacheConfigName) {
        this.defaultCacheConfigName = defaultCacheConfigName;
    }
}


 @Bean(name = "redisCacheManager")
    public CacheManager redisCacheManager(RedissonClient redissonClient) throws IOException {
        RedissonSpringCacheManager cacheMange = new RedissonSpringCacheManager(redissonClient,
            getRedissonConfig(redisCacheManagerConfig));
        return cacheMange;
    }


-------------
 @Value("${redisson.cache.defaultCacheName.config}")
    private String       defaultCacheConfigName;
 private Map<String, CacheConfig> getRedissonConfig(String cacheConfigFile) {

        Map<String, CacheConfig> defaultConfig = null;
        Resource resource = new ClassPathResource(cacheConfigFile);
        try {
            defaultConfig = CacheConfig.fromYAML(resource.getInputStream());
        } catch (IOException e1) {
            throw new BeanDefinitionStoreException(
                "Could not parse cache configuration at [" + cacheConfigFile + "]", e1);
        }

        AistRedissonConfigMap<String, CacheConfig> config = new AistRedissonConfigMap<String, CacheConfig>();
        config.setDefaultCacheConfigName(defaultCacheConfigName);
        
        if (null != defaultConfig && !defaultConfig.isEmpty()) {
            config.putAll(defaultConfig);
        }
        return config;
    }
_____YAML文件
#redisson
redisson.cluster.config=/redisson/prod/cluster.yaml
redisson.cache.redisCacheManager.config=/redisson/prod/redisCacheManager.yaml
redisson.cache.shiroSessionRedisManager.config=/redisson/prod/shiroSessionRedisManager.yaml
redisson.cache.redisLongCacheManager.config=/redisson/prod/redisLongCacheManagerConfig.yaml
redisson.cache.defaultCacheName.config=defaultMap

**Comment by boying52** [comment]
但是还是偶尔会发生上述问题

**Comment by boying52** [comment]
上述就是为了保证一个defaultMap的存在，如果我们忘记配置文件，那么至少还有一个默认的TTL，但是我们发现偶尔重启tomcat之后会发生以上错误。

**Comment by jackygurui** [comment]
你能给我发一个重现吗？

**Comment by boying52** [comment]
我这几天重写之后给你，因为昨日测试reddison驱动，测试环境3次这样。带下次出现再贴出来

**Comment by jackygurui** [comment]
好的，谢谢。能不能麻烦你把它做成一个test case的形式发给我？就是能让我在我这里也能模拟出这个情况？

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/853

**Comment by 17623733539** [comment]
遇到同样问题，要死人了

**Comment by 0utman1** [comment]
后续有解决吗？
