### ISSUE TITLE
session data stored successfully but cannot  be reused after restart: Session xxx has already been invalidate

### ISSUE THREAD

**Issue by wuhao000** [redisson/redisson#807]
I have configured redisson in my tomcat and ran an web application successfuly，after an ajax request，
the session data  has been stored in redis successfully，but when I restarted tomcat and called the ajax request again，an error occured and the request responsed with error code 500, then I called the ajax request again, a new session has bean created.

the stacktrace:

ava.lang.IllegalStateException: setAttribute: Session [2D3B8D8630A3EC8B89D10B63CB912382] has already been invalidated
	org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1463)
	org.redisson.tomcat.RedissonSession.setAttribute(RedissonSession.java:130)
	org.redisson.tomcat.RedissonSession.load(RedissonSession.java:182)
	org.redisson.tomcat.RedissonSessionManager.findSession(RedissonSessionManager.java:121)
	org.apache.catalina.connector.Request.doGetSession(Request.java:2922)
	org.apache.catalina.connector.Request.getSessionInternal(Request.java:2575)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:431)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1524)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
Hi! There is a test for you case `RedissonSessionManagerTest.testSwitchServer` it passes. Can you try it too?

**Comment by bruceLiHanFei** [comment]
me too

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/974
