### ISSUE TITLE
Allow separate Master/Slave password configuration

### ISSUE THREAD

**Issue by shmosel** [redisson/redisson#81]

**Comment by yogeshkaushik** [comment]
Can we expect this feature in any of the release? I have setup different passwords for my master and slave redis. Another question is, how does redisson connects to slave? Using Master password? (does it expect both the passwords should be same?)  -or-  No password? (does it expect no password set on slave).

**Comment by mrniko** [comment]
Use `credentialsresolver` setting. https://github.com/redisson/redisson/wiki/2.-Configuration#credentialsresolver
