### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Redis server response timeout

### ISSUE THREAD

**Issue by sinusekhar** [redisson/redisson#820]
We are seeing an increase in the number of timeouts lately when we try to use SET or SETX commands lately with Elasticache. Here are some details about our setup.

We use a 4 node cache.m3.xlarge Elasticache Redis cluster.

Our Redisson initialization code:
                `StringTokenizer nodes = new StringTokenizer(nodeList, DELIMITER);

                Config config = new Config();
                while(nodes.hasMoreTokens()) {
                    config.useElasticacheServers()
                            .setConnectTimeout(connectTimeout)
                            .setTimeout(readTimeout)
                            .addNodeAddress(nodes.nextToken());
                }
                config.useElasticacheServers().setScanInterval(redisScanInterval);

                client = Redisson.create(config);`

- nodeList is a comma separated list of all nodes (master and slaves)
- readTimeout is 5000ms
- connectTimeout is 5000ms
- redisScanInterval is 1000ms

Exception thrown:
`Error occurred in cache put
org.redisson.client.RedisTimeoutException: Redis server response timeout (5000 ms) occured for command: (SET) with params: [Foo.bar.xxx.2, com.xxx.mobile.png.api.cbo.SenderApp@1224aee8] channel: [id: 0x192c6979, L:/10.81.229.161:47068 - R:png-prod-cache01-002.ni8ion.0001.usw2.cache.amazonaws.com/10.81.229.186:6379]
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:529) ~[redisson-2.2.27.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385) ~[netty-common-4.0.39.Final.jar:4.0.39.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

We are using Redisson client version: 2.2.27

Is 5 second timeout too low for EC2? We are operating within a VPC. All EC2 instances and cache is running within the same VPC.

Any help/guidance will be very helpful...please do let me know if i can provide any additional info.

**Comment by pY4x3g** [comment]
I also get an increase in this timeout exception when using SUBSCRIBE withing redisson. But it only occurs after 300+ simultaneous active subscriptions. Then some subscriptions fail but other run successfully. Perhaps its something similar?

**Comment by andrewmilkowski** [comment]
is this cause to worry ? we will have similar high traffic/subscription model, thanks

**Comment by sinusekhar** [comment]
We are not using subscriptions, but still running into this problem. 

We see this for SET command typically.

**Comment by jackygurui** [comment]
@sinusekhar @pY4x3g @andrewmilkowski There are a couple of factors that can contribute to this issue: Redis node's load and network speed. Depending on your own situation and your average payload size, you should always do some tests to find out the most optimum value for the following config options: connection pool size, subscription pool size, timeout, retry count and retry interval.

**Comment by somendraraj** [comment]
Couldn't find any result how to fix this below problems

org.redisson.client.RedisTimeoutException: Redis server response timeout (15000 ms) occured for command: (EXISTS) with params: [csss.lock.xxxxx] channel: [id: 0xab59df9a, L:/10.144.91.34:50155 - R:/10.144.102.40:6079]

**Comment by jackygurui** [comment]
Perhaps a look into the slow log?

**Comment by jikuanyu** [comment]
t]2019-05-06 13:25:12,531 ERROR org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (30000 ms) occured after 3 retry attempts. Command: (HGET), params: [KS_MP_CACHE, PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 256)], channel: [id: 0xc4e805db, L:/192.168.144.77:52055 - R:192.168.119.10/192.168.119.10:9001] | PublicResInfoAction.publicResInfo(1106)
this problem may occur intermittently。
redisson-2.15.2
