### ISSUE TITLE
Can Scheduled executor run non-serializable tasks?

### ISSUE THREAD

**Issue by riyyaz** [redisson/redisson#822]
I have a non-serializable task to schedule. The executor is failing to submit this task with a NotSerializableException. The task is available to the worker node in its classpath. Is there a way I can execute these kind of tasks on the worker node.

```
public class NonSerializableTask implements Runnable {
    
    @RInject
    private RedissonClient redissonClient;

    // several members which are non-serializable

    @Override
    public void run() {
        
    }    
}
```

**Comment by mrniko** [comment]
Which codec do you use? Default is json codec and it serializes non-serializable objects

**Comment by riyyaz** [comment]
Yes actually to begin with I was using the default json codec which produced this error

`
java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError)`

Since I could not make it work, I was trying to play around with different codecs but without any success.
Please any suggestion would be helpful.

**Comment by riyyaz** [comment]
One more bizarre thing is that the json recursion is happening between these classes

`
java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.security.ProtectionDomain["classloader"]->sun.misc.AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]->sun.misc.AppClassLoader["defaultDomain"]->java.security.ProtectionDomain["classloader"]`

**Comment by mrniko** [comment]
> Yes actually to begin with I was using the default json codec which produced this error
java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError)

Could you share your test code to reproduce it?

**Comment by riyyaz** [comment]
Sorry for a late response...

Unfortunately I cannot share the actual Task code, but here is what I did to reproduce the problem

This code generates the exception

```
       JsonJacksonCodec jjc = new JsonJacksonCodec();
        try {
            byte[] b = jjc.getValueEncoder()
                    .encode(new NonSerializableTask());
       
        } catch (IOException e1) {
        
            e1.printStackTrace();
        }
```

This one works fine

```
        ObjectMapper om = new ObjectMapper();

        try {
            om.writeValueAsBytes(new NonSerializableTask());
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
```

**Comment by mrniko** [comment]
Try to use another codec as workaround

**Comment by mrniko** [comment]
Can't reproduce it. Here is my test code: 
```java
    public static class MyClass {
        
    }
    
    public static class NonSerializableTask implements Runnable {

        @RInject
        private RedissonClient redissonClient;
        
        private MyClass clazz = new MyClass();
        
        @Override
        public void run() {
            // TODO Auto-generated method stub
            
        }
        
    }
    
    @Test
    public void test() throws IOException {
        JsonJacksonCodec jjc = new JsonJacksonCodec();
        byte[] b = jjc.getValueEncoder().encode(new NonSerializableTask());
       
    }

```

**Comment by riyyaz** [comment]
This is how I was able to reproduce it

```
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.redisson.api.RedissonClient;
import org.redisson.api.annotation.RInject;
import org.redisson.codec.JsonJacksonCodec;

import com.fasterxml.jackson.databind.ObjectMapper;

public class TestProgram {

    public static void main(String[] args) throws FileNotFoundException {

        JsonJacksonCodec jjc = new JsonJacksonCodec();
        try {
            byte[] b = jjc.getValueEncoder().encode(new NonSerializableTask());
            System.out.println(new String(b, StandardCharsets.UTF_8));
        } catch (IOException e1) {
            e1.printStackTrace();
        }

    }

}

class NonSerializableTask implements Runnable {

    @RInject
    private RedissonClient redissonClient;

    private ObjectMapper mapper = new ObjectMapper();

    @Override
    public void run() {

    }

}
```

**Comment by riyyaz** [comment]
@mrniko Never mind, find out the original issue here http://stackoverflow.com/questions/9567103/make-jackson-objectmapper-serializable...  Thanks a lot for taking a look into this issue.

**Comment by mrniko** [comment]
Why don't you create it right in `run` method?

**Comment by johnou** [comment]
or mark it transient, or even better, create a static helper to return a singleton (it is thread safe).
