### ISSUE TITLE
How can I get ttl by key directly?

### ISSUE THREAD

**Issue by QiuMing** [redisson/redisson#823]
Is there a way to get ttl like `jedis.ttl(key)` in redisson?

**Comment by jackygurui** [comment]
The method you are looking for is `remainTimeToLive` which is part of the RExpirable API that provides key expiration related operations. Just about every Redisson provided objects implemented this.

For Redis commands mapping please refer to the wiki document https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping

**Comment by QiuMing** [comment]
@jackygurui  Thanks your answer ,I have see this doc before ,and I also find ttl in redisson code.And now I can get ttl use this method:
```
public long getTTL(RedissonClient redissonClient, String key) throws Exception {
        RType rtype = redissonClient.getKeys().getType(key);
        long ttl;
        if (null == rtype) {
            throw new Exception("NOT FOUND TYPE");
        }
        switch (rtype) {
            case OBJECT:
                ttl = redissonClient.getBucket(key).remainTimeToLive();
                break;
            case MAP:
                ttl = redissonClient.getMap(key).remainTimeToLive();
                break;
            case LIST:
                ttl = redissonClient.getList(key).remainTimeToLive();
                break;
            case SET:
                ttl = redissonClient.getSet(key).remainTimeToLive();
                break;
            case ZSET:
                ttl = redissonClient.getScoredSortedSet(key).remainTimeToLive();
                break;
            default:
                throw new Exception("NOT FOUND TYPE");
        }
        return ttl;
    }
```
En...It seems too much trouble ,So,I want to know ,is there a better way to get ttl key?

**Comment by jackygurui** [comment]
@QiuMing It is an odd situation that, when using Redisson, you are still a situation where the type of the key is unknown. To me this feels like you are trying to use the Redisson in the same way as the Jedis. If you prefer to the low level client, you can try the RedisClient instance.

**Comment by jackygurui** [comment]
@QiuMing I think the question is how did you end up with a key name instead of a RObject instance in the first place?

**Comment by mrniko** [comment]
I think it's better to add method like `RKeys.remainTimeToLive`

**Comment by jackygurui** [comment]
@mrniko That is good idea.

**Comment by jackygurui** [comment]
Although the current usage is not going to help him to enjoy all the benefits the Redisson brings.

**Comment by QiuMing** [comment]
Yea..The method above is too odd.And my needs is that I could get key's ttl while I did not its type.And  add method like `RKeys.remainTimeToLive` could solve my problem.Hope Redisson could add this method.

**Comment by jackygurui** [comment]
This issue should stay open until it is resolved.

**Comment by mrniko** [comment]
Done

**Comment by cmhsu-cs** [comment]
In redisson, can we get a key that wasn't set by redisson? I have a simple string that I stored in a redis key. Can I use redisson to retrieve this even though it wasn't set by redisson? @mrniko @jackygurui @QiuMing

**Comment by mrniko** [comment]
@cmhsu-cs Sure you can - `redisson.getBucket("yourKey")` don't forget to use same data codec used by non-Redisson client.
