### ISSUE TITLE
Can RedissonFairLock work if my application was deployed on more than one server

### ISSUE THREAD

**Issue by shixiangweii** [redisson/redisson#833]
For example, i deploy my application on 3 servers
now, 
the first request as req1 processed by server1
the secoind request as req2 processed by server2
the third request as req3 processed by server3
will RedissonFairLock works to make sure three requests be synchronized and the process order is
req1,req2,req3?

**Comment by mrniko** [comment]
Yes, it can. Because fairlock state stored in Redis and not on Redisson side (client side)

**Comment by shixiangweii** [comment]
thank you for you answer very much!
