### ISSUE TITLE
Configuration in cloud

### ISSUE THREAD

**Issue by Mrinal-Bhattacharya** [redisson/redisson#834]
Hi Team,

We are planning to use redisson in pivotal cloud foundry. Can you please help me to configure that.
if you guys can provide some example it will be nice.

* We are using redis as a service.

**Comment by mrniko** [comment]
Does PCF provides Redis in master/slave, cluster or any other specific configuration? 
for master/slave use `Config.useReplicatedServers` and for cluster `Config.useClusterServers`

**Comment by Mrinal-Bhattacharya** [comment]
Hi Nikita,

We are using as single server and we are able to connect thanks for the quick response.
