### ISSUE TITLE
schema error in Integration with Spring  by namespack

### ISSUE THREAD

**Issue by shixiangweii** [redisson/redisson#835]
in doc https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks,
the chart 14.1. Spring Framework，the that:
http://redisson.org/schema/redisson
http://redisson.org**_/schema/redisson/redisson.xsd_**
but it comes to error, the spring can not find "redisson.org/schema/redisson/redisson.xsd"

i unzip the redisson.jar，and find the in the file "spring.schemas" only that:
http\://redisson.org**_/schema/redisson.xsd_**=org/redisson/spring/support/redisson-1.0.xsd
http\://redisson.org/schema/redisson-1.0.xsd=org/redisson/spring/support/redisson-1.0.xsd

i use "redisson.org/schema/redisson.xsd", it comes ok

difference:

"http://redisson.org/schema/redisson.xsd"                                   in spring.schemas
"http://redisson.org/schema/redisson/redisson.xsd"                     in online doc

**Comment by jackygurui** [comment]
should only be closed when the issue is resolved

**Comment by shixiangweii** [comment]
ok~

**Comment by mrniko** [comment]
Fixed
