### ISSUE TITLE
Bean property 'address' is not writable or has an invalid setter method

### ISSUE THREAD

**Issue by somejavadev** [redisson/redisson#837]
Hi,
I have configured a plain single server install of Redis. When I configure the Redisson client within my spring XML config with a simple single-server configuration. Spring gives the following error: 

> Bean property 'address' is not writable or has an invalid setter method.

 I had a look at the file SingleServerConfig.java file and I noticed that it has both a public `SingleServerConfig setAddress(String address)` method as well as a void `setAddress(URL address)` method. I am not sure if this is what is causing the configuration error. I have created a gist with my [XML config](https://gist.github.com/somejavadev/1a510bfda1daf2ad529249f225c6533a).
    
Spring Version: 3.1.3.RELEASE
Java Version: 1.7
Redisson Version: 2.8.2

**Comment by jackygurui** [comment]
The `void setAddress(URL address)` method does not have the `public` modifier so it is not visible to spring. The test case passes with your config xml. I am going to try and see if it is spring version related issue.

**Comment by somejavadev** [comment]
Thank you, I am also trying to update to the latest version 3 of spring to see if this resolves the issue. I will let you know what I find. Just busy trying to sort out all the dependency issues when changing the version since this is quite an old project.

**Comment by jackygurui** [comment]
It seems the problem was fixed in spring 3.2.7.RELEASE, anything below are affected.

**Comment by somejavadev** [comment]
Excellent thank you.

**Comment by jackygurui** [comment]
A bit more insight about this issue, I think this is a spring's [bug](https://jira.spring.io/browse/SPR-11361) which [affects 3.2.6 and below and as well as 4.0.0](https://github.com/spring-projects/spring-framework/commit/ac3c670f704ee56be5b6e0db80a8a32b1d75ff53). 

This [method](https://github.com/spring-projects/spring-framework/blob/v3.2.7.RELEASE/spring-beans/src/main/java/org/springframework/beans/BeanWrapperImpl.java#L491) was modified in 3.2.7 and it is [changed](https://github.com/spring-projects/spring-framework/blob/v3.2.7.RELEASE/spring-beans/src/main/java/org/springframework/beans/BeanWrapperImpl.java#L494) to use `td.getType()` to get the required type before passing it to `convertIfNecessary` method. 

In 3.2.6, this [method](https://github.com/spring-projects/spring-framework/blob/v3.2.6.RELEASE/spring-beans/src/main/java/org/springframework/beans/BeanWrapperImpl.java#L494) was using `pd.getPropertyType()` to get the required type before passing it to `convertIfNecessary` method. 

The difference is `TypeDescriptor.getType` give out the correct type which is String.class in this case whereas `PropertyDescriptor.getPropertyType()` give out the wrong type needed, which was URL.class

**Comment by somejavadev** [comment]
Thanks for the decent feedback. I have updated the version of spring to 3.2.8 and sorted the related dependencies and I can confirm it has resolved the issue.
