### ISSUE TITLE
SSL connection (Azure Redis Cache)

### ISSUE THREAD

**Issue by janovicst** [redisson/redisson#842]
Hello! 
I would like connect to Azure Redis Cache service with redisson, but I didn't find how to connect over ssl. I searched here in the redisson wiki, looked up more forums, but I didn't find anything. Can you show me a descriptoin or code sample!
Thank you! 
Tamas

**Comment by mrniko** [comment]
SSL support is not implemented yet, although Netty offers own SSL implementation faster than JVM's

**Comment by janovicst** [comment]
Okay, thank you! Than I will try it.

**Comment by mrniko** [comment]
Done
