### ISSUE TITLE
redisson with spring 

### ISSUE THREAD

**Issue by baiguantao** [redisson/redisson#844]
hey,gays.
i want use redisson with spring 
here(https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks#141-spring-framework),
just say set it in spring xml,like this:
   <redisson:client id="redisson">
         <redisson:single-server address="127.0.0.1:6379"/>
    </redisson:client>
after it, i want get it's instance ,just like under pseudocode
@Service
public class RedissonUtils {
    @Autowired
    private RedissonClient redissonClient;
    {

        System.out.println(redissonClient.toString());
    }
}
how to do?

**Comment by jackygurui** [comment]
You code doesn't work because the Spring's auto wiring process happens after instance initialization. Try the following:

```java
@Service
public class RedissonUtils implements InitializingBean {
    @Autowired
    private RedissonClient redissonClient;

    @Override
    public void afterPropertiesSet() {
        System.out.println(redissonClient.toString());
    }
}
```

**Comment by baiguantao** [comment]
@jackygurui  thank you !
