### ISSUE TITLE
 RMap with byte[] key ?

### ISSUE THREAD

**Issue by athinboy** [redisson/redisson#846]
RMap<String, byte[]> map = redisson.getMap("anyMap");
        for (int i = 0; i < 10; i++) {
            map.put(String.valueOf(i), String.valueOf(i).getBytes());
        }
        byte[] o = map.get("2"); //java.lang.ClassCastException: java.lang.String cannot be cast to [B

Is it wrong way  to use RMap?

**Comment by jackygurui** [comment]
You need to specify a codec. By default redisson uses Jackson to serialise your data into string and then convert it to byte[] before passing them to redis. If you wish to operate the raw byte[] you have to choose a relevant codec like this one https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/client/codec/ByteArrayCodec.java for redisson to use

**Comment by athinboy** [comment]
@jackygurui 
Thanks!
but ,I put byte[] into  ,  redisson should return byte[] , why do i must specify a codec ?

**Comment by mrniko** [comment]
Jackson handles byte[] correctly. Should check your case

**Comment by athinboy** [comment]
@mrniko 

 i am a beginner .

but , code bellow can work.

 
        RMap<byte[], byte[]> mapbs = redisson.getMap("anyMapbs",ByteArrayCodec.INSTANCE);
        for (int i = 0; i < 10; i++) {
            mapbs.put(String.valueOf(i).getBytes(), String.valueOf(i).getBytes());
        }
        byte[] o = mapbs.get("2".getBytes());
        System.out.println(new String(o));

**Comment by mrniko** [comment]
More research required on this. Custom array serializator required. Because Jackson can't differ String object from Array.

**Comment by mrniko** [comment]
Now you can define map key/value types through JsonJacksonMapCodec like this:

```java
RMap<String, byte[]> map = redisson.getMap("anyMap", new JsonJacksonMapCodec(String.class, byte[].class));
```

**Comment by avhirupc** [comment]
The latest version dont support JsonJacksonMapCodec . Whats the alternative to the behaviour ?

**Comment by mrniko** [comment]
@avhirupc 

Use `TypedJsonJacksonCodec` instead.
