### ISSUE TITLE
Spring boot with redisson 3.3.2, 2.8.2 fails without optional actuator dependency 

### ISSUE THREAD

**Issue by usultis** [redisson/redisson#852]
Actuator is an optional feature in Spring Boot, there are a lot of projects that do not use actuator due to additional dependencies and complexity.
Redisson 3.3.1 worked fine without actuator but 3.3.2 fails to start with ClassNotFoundException for org.springframework.boot.actuate.cache.CacheStatisticsProvider.
Suggested change registers Redisson AutoConfiguration only if actuator is in the classpath

Pull request https://github.com/redisson/redisson/pull/851
That pull request is only for 3.0.0 but change changes apply for the master branch

**Comment by mrniko** [comment]
Fixed
