### ISSUE TITLE
How do I register a Module on the Jackson ObjectMapper instance Redisson is using under the covers so it can handle Java8 time types?

### ISSUE THREAD

**Issue by pluttrell** [redisson/redisson#86]
We are using Java8 java.time.Instant as the type in our objects, and running into this problem:

com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class java.time.Instant]: can not instantiate from JSON object (need to add/enable type information?)

And according to the Jaxson question I asked here: https://github.com/FasterXML/jackson-docs/issues/3 I need to register a Module on the ObjectMapper instance that Redisson is using. How do I do that?

**Comment by joshattr** [comment]
Sorry to resurrect an old thread. @pluttrell I'm having troubles with this. Mind sharing your solution? It seems adding the following to my subclass didn't do the trick:
 ```java
@Override
protected void init(ObjectMapper mapper)
{
    mapper.setSerializationInclusion(Include.NON_NULL);
    mapper.setVisibilityChecker(mapper.getSerializationConfig().getDefaultVisibilityChecker()
            .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
            .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
            .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
            .withCreatorVisibility(JsonAutoDetect.Visibility.NONE));
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    mapper.configure(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN, true);
    mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
    mapper.registerModule(new JavaTimeModule()); // <----------------------------------------
}
```

@mrniko I wonder if there's a way to detect if if there are any jackson plugins and use them? It'd save some configuration/subclassing

**Comment by joshattr** [comment]
I spoke too soon. There must have been something wrong with my local setup. That code appears to be working now. Sorry to bother you.

**Comment by joshattr** [comment]
Ok. I got it working. I think I had some stray spring configuration that was causing my `Redisson` instance to be re-created when it shouldn'tve been. Sorry for all the confusion (it's really fixed now!).

**Comment by gpcmol** [comment]
@Bean
    public ObjectMapper mapper() {
    	ObjectMapper mapper = new ObjectMapper();

    	mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		mapper.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, true);
		mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
		mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);

		mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
		mapper.setVisibility(mapper.getSerializationConfig().getDefaultVisibilityChecker().withFieldVisibility(JsonAutoDetect.Visibility.ANY).withGetterVisibility(JsonAutoDetect.Visibility.NONE).withSetterVisibility(JsonAutoDetect.Visibility.NONE).withCreatorVisibility(JsonAutoDetect.Visibility.NONE));
		mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
		mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
		mapper.addMixIn(Throwable.class, JsonJacksonCodec.ThrowableMixIn.class);

		mapper.findAndRegisterModules();
		mapper.registerModule(new JavaTimeModule());

    	return mapper;
    }
    
	@Autowired
	@Bean
	public RedissonClient redissonClient(ObjectMapper mapper) {
		Config config = new Config();
		config.useSingleServer().setConnectTimeout(30000).setTimeout(30000).setAddress(host + ":" + port);
		config.setNettyThreads(4);
		config.setThreads(4);
		config.setCodec(new JsonJacksonCodec(mapper));
		
		RedissonClient redissonClient = Redisson.create(config);
		return redissonClient;
	}
