### ISSUE TITLE
Jackson annotation @JsonDeserialize does not worked

### ISSUE THREAD

**Issue by chenyusong** [redisson/redisson#861]
Hi, I used redisson to keep my tomcat session, and deserializing session error when the tomcat was restart.
The error info is 'the class missing default constructor or creator, or perhaps need to add/enable type information'.
So I add jackson annotation JsonDeserialize to my class, but it does not worked.
Can you help me solve this problem?

I have try deserializing the class with Jackson, and it can working

The code:
`@JsonDeserialize(using = UsernamePasswordAuthenticationTokenSerializer.class)`
`public class UsernamePasswordAuthenticationTokenExt extends UsernamePasswordAuthenticationToken {`

**Comment by mrniko** [comment]
Here is an example of JsonDeserialize usage http://www.davismol.net/2015/06/05/jackson-using-jsonserialize-or-jsondeserialize-annotation-to-register-a-custom-serializer-or-deserializer/

**Comment by chenyusong** [comment]
It is not i want. Thank you all the same. I have solved it by other way.
