### ISSUE TITLE
DnsMontioring not available in Master Slave Mode

### ISSUE THREAD

**Issue by sachinstar2010** [redisson/redisson#864]
One of our use case requires that if there is a failover, we reconnect automatically to another node. This is available in single server config as DnsMonitoring but not in Master Slave mode. Is there a specific reason for this? Can there be a support added? @mrniko

**Comment by mrniko** [comment]
Yes, it's possible to implement

**Comment by sachinstar2010** [comment]
If that is the case, then dnsMonitoring can be added for both the master and the slave right?

**Comment by mrniko** [comment]
Yes

**Comment by sachinstar2010** [comment]
Can this be implemented by you? I am trying to go through the code base as well.

**Comment by sachinstar2010** [comment]
@mrniko Any update on this issue?

**Comment by mrniko** [comment]
I think it will be implemented in June's release

**Comment by sachinstar2010** [comment]
Has this been released yet?

**Comment by mrniko** [comment]
Implemented
