### ISSUE TITLE
redisson cluster startup very slow (1.5 sec) in AWS Lambda with AWS Elasticache Redis

### ISSUE THREAD

**Issue by dheepak** [redisson/redisson#867]
Hello,
   I'm trying to use redisson for my project that will run on AWS lambda and will use AWS Elasticache Redis Cluster. I have the following snippet:
					URL redissonConfig = RedisCacheClient.class.getResource("/redisson.yaml"); 				
					logger.debug("URL is " + redissonConfig);
					File configFile = new File(redissonConfig.toURI());
					Config config;
					config = Config.fromYAML(configFile);
					logger.debug("Configuration Input is" + config.toJSON());
					client = Redisson.create(config);
					logger.debug("Client Created");

The configuration is 
---
clusterServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
  - "redis://usercache-0001-001.awtwec.0001.use1.cache.amazonaws.com:6379"
  - "redis://usercache-0001-002.awtwec.0001.use1.cache.amazonaws.com:6379"
  - "redis://usercache-0001-003.awtwec.0001.use1.cache.amazonaws.com:6379"
  scanInterval: 1000
threads: 4
nettyThreads: 4
codec: !<org.redisson.codec.JsonJacksonCodec> {}
useLinuxNativeEpoll: false

I had the threads and nettyThreads as 0 and that was even worse. I now set it up to 4... and the startup is about 1440 ms.

Can someone please advise the right cluster configuration for Redisson in AWS Lambda?
Rgds.
Dheepak

**Comment by dheepak** [comment]
I'm using 3.3.0 version of Redisson client and primarily use the RMAP function ... the read / write performance is fine (sub 30 secs acceptable). However, the startup performance really aggravates the already troubling cold start times.

**Comment by dheepak** [comment]
Anyone? Can someone help me isolate this performance issue?

**Comment by pohlmarcus** [comment]
Hey @dheepak,
same problem here. Lambda stays alive for 2sec, but only 100ms internal operating time.

I solved it. The problem is the blocking shutdown method of redisson.
Set timeout as parameter and all is fine and will close the connection in about 26ms.

**Comment by xintellion** [comment]
Did you ever find a solution for this problem? Just ran into this myself.

@pohlmarcus what timeout do you mean? And what value should it be set to.

**Comment by mrniko** [comment]
Fixed
