### ISSUE TITLE
RMap.addAndGet(key,number)  threw 'org.redisson.client.RedisException' exception.

### ISSUE THREAD

**Issue by HorizonHero** [redisson/redisson#870]
My RedissonClient codec is Config config = new Config().setCodec(new KryoCodec());
use this codec. Get RMap via RedissonClient, and then call RMAP's addAndGet method. Can be successful, but I then throw out the RMap when the exception thrown: Throws an exception: Unable to evaluate the expression Method threw 'org.redisson.client.RedisException' exception.
p.s:If the codec from KryoCodec into StringCodec or default codec(Jackson JSON) will not be an error.

**Comment by jackygurui** [comment]
Since the RMap.addAndGet is implemented on top of HINCRBYFLOAT only works for plain value. If you already had a value stored in a field and encoded with another codec then execute this command, it will fail.

**Comment by HorizonHero** [comment]
The RMap is empty before execute addAndGet.
RMap<String, Integer> rMap = redissonClient.getMap("redis");
rMap.clear();
rMap.addAndGet("mykey", 1);
Like this. Still being given exception.

**Comment by mrniko** [comment]
This method works only with StringCodec

**Comment by HorizonHero** [comment]
Ok.Thank you very much @jackygurui @mrniko . I have seen a new Issues # 871.
