### ISSUE TITLE
why excuted RAtomicLong.addAndGet(long delta), but Bucket.get() return Integer result?

### ISSUE THREAD

**Issue by sosojustdo** [redisson/redisson#875]
hello mrniko:

Config = ...
RedissonClient redisson = Redisson.create(config);
RAtomicLong  atomicLong = redisson.getAtomicLong(key);
Long result = atomicLong.addAndGet(10L);
//execute successful

RBucket bucket = redisson.getBucket(key)
But (bucket.get()) return Integer result? why?

**Comment by mrniko** [comment]
It's a bad idea to use mix objects type. You should use RAtomicLong object to get value and not RBucket

**Comment by sosojustdo** [comment]
Thank you for mrniko.
