### ISSUE TITLE
To search more than one live object by id or by attributes

### ISSUE THREAD

**Issue by superdexter** [redisson/redisson#876]
With present radisson is it possible to search more than one item by id or  other properties ?
for example :
<pre>
 RLiveObjectService liveObjectService = redisson.getLiveObjectService();
List<Long> ids = new ArrayList<>();
ids.add(12);
ids.add(13);
ids.add(14);
 List<Customer> customers = liveObjectService.get(Customer.class, ids );

</pre>

if not this way. are there any other ways to do this ?

Question 2:
Is it possible to search objects by property name?

for eg: searching customer by product id.

**Comment by jackygurui** [comment]
Q1, it is not possible to do this. If you wish to get a list of customers, why don't you create a RedissonList and put those customers in it?

Q2, it is not possible to do this either. What you should consider doing is to have a RedissonSet inside product and put customer into it. This will be much faster than trying to "search" for it. Obviously you can create your own index if you really want to "search" for it.
