### ISSUE TITLE
RBlockingQueue.pollLastAndOfferFirstTo does not block properly

### ISSUE THREAD

**Issue by rlamarche** [redisson/redisson#877]
This  bug could be a duplicate of #349 but this is not the same method.

The following code:
```
RBlockingQueue<Message> messageQueue = redissonClient.getBlockingQueue(Constants.MESSAGE_QUEUE);
Message message = messages.pollLastAndOfferFirstTo(Constants.PROCESSING_QUEUE);
```

Does not block until a message is available

In the documentation https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping, it is said that `BRPOPLPUSH` can be replaced by a call to `RBlockingQueue.pollLastAndOfferFirstTo()`.
So this call should bock until a message is available.

As a workaround, I can use `RBlockingQueue.pollLastAndOfferFirstToAsync()` or `pollLastAndOfferFirstTo(String queueName, long timeout, TimeUnit unit) throws InterruptedException`.

By the way,  Reddis is a fantastic framework and I love it :+1:

**Comment by mrniko** [comment]
> messages.pollLastAndOfferFirstTo(Constants.PROCESSING_QUEUE);

There is no method with queue name parameter only.

**Comment by rlamarche** [comment]
Wow fast answer :+1: thanks.
I'll use with timeout = 0 so.

**Comment by rlamarche** [comment]
Ok it works :+1:  thank you.
I think that you should precise the complete signature of the method we should use in the documentation https://github.com/redisson/redisson/wiki/11.-Redis-commands-mapping for `BRPOPLPUSH`.

Or override the `pollLastAndOfferFirstTo(String) to call `pollLastAndOfferFirstTo(String, long, TimeUnit)` but in this case we loose the possibility to have non-blocking call.
