### ISSUE TITLE
what about lazy connecte to redis?

### ISSUE THREAD

**Issue by athinboy** [redisson/redisson#878]
what about delay to  connect to redis  , by the first function call ?
rather than connect to redis immediately  when  application startup .

**Comment by jackygurui** [comment]
Redisson comes with a built-in elastic connection pool which expands the connection when the demand is required. It also has a configurable minimum size parameter for the pool, which the Redisson has to maintain. You may change it to a smaller value as it fits.

**Comment by athinboy** [comment]
as you say , set minimum to 0 ?

**Comment by athinboy** [comment]
thanks , may you  post the detail config info ?

**Comment by athinboy** [comment]
just ,i need the webapplication  can startup when Redis server be  shut  down .
