### ISSUE TITLE
How to listen for changes to an RMap (migrating from Hazelcast)?

### ISSUE THREAD

**Issue by stodge** [redisson/redisson#879]
I'm investigating moving from Hazelcast to Redisson and one question popped up that I can't seem to work out the answer for. Perhaps I'm trying to incorrectly compare functionality between the two?

Anyway, in our code that uses Hazelcast, we create a distributed IMap and add listeners so that each process (Hazelcast client) can listen for changes to that map. I can't seem to work out how to get the same functionality using the RMap. Is this possible or is this functionality only available using the LiveObject? Or do I have to mimic this functionality using a topic perhaps?

Thanks

**Comment by mrniko** [comment]
Hi!

Listeners are not implemented for RMap stucture yet. There two ways to overcome it:
1. Usage of JCache API implementation provided by Redisson.
2. Publish message to RTopic during each RMap change method invocation

**Comment by stodge** [comment]
Thanks @mrniko, I will investigate both of those solutions.

**Comment by mrniko** [comment]
Done. Please use RMapCache object

**Comment by stodge** [comment]
The latest version of Redisson in Maven is 3.2.0 (https://mavenrepository.com/artifact/org.redisson/redisson). You added this to the 2.9.3 milestone. Which branch should I use; 2.9.x or 3.x?

Thanks for implementing this.

**Comment by mrniko** [comment]
master (2.x) is current development branch which is always merged with 3.x branch before the release. So 3.x branch is not merged with master yet

**Comment by mrniko** [comment]
master (2.x) is current development branch which is always merged with 3.x branch before the release. So 3.x branch is not merged with master yet
