### ISSUE TITLE
Data serialization error 

### ISSUE THREAD

**Issue by mqian-sky** [redisson/redisson#883]
我用redission 集成tomcat中session共享的，项目用的是spring security。
对象序列化使用默认方式。
登录的时候 redis里能存入格式如下
`"SPRING_SECURITY_CONTEXT"
{
    "@class": "org.springframework.security.core.context.SecurityContextImpl",
    "authentication": {
        "@class": "org.springframework.security.authentication.UsernamePasswordAuthenticationToken",
        "authenticated": true,
        "authorities": [
            "java.util.ArrayList",
            [
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "ROLE_ADMIN"
                },
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "ROLE_BASE"
                },
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "ROLE_BASE_CHANNEL"
                },
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "ROLE_BASE_LOG"
                },
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "basic_admin_role"
                },
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "login_role"
                },
                {
                    "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                    "role": "um_admin_role"
                }
            ]
        ],
        "details": {
            "@class": "org.springframework.security.web.authentication.WebAuthenticationDetails",
            "remoteAddress": "10.100.40.192",
            "sessionId": "A39B28F397825AC625A6BEE61EC5CC43"
        },
        "principal": {
            "@class": "org.springframework.security.core.userdetails.User",
            "accountNonExpired": true,
            "accountNonLocked": true,
            "authorities": [
                "java.util.Collections$UnmodifiableSet",
                [
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "ROLE_ADMIN"
                    },
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "ROLE_BASE"
                    },
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "ROLE_BASE_CHANNEL"
                    },
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "ROLE_BASE_LOG"
                    },
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "basic_admin_role"
                    },
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "login_role"
                    },
                    {
                        "@class": "org.springframework.security.core.authority.GrantedAuthorityImpl",
                        "role": "um_admin_role"
                    }
                ]
            ],
            "credentialsNonExpired": true,
            "enabled": true,
            "username": "admin"
        }
    }
}`

`RMap<String,Object> map = localRedisson.getMap("redisson_tomcat_session:70F928E6F059B511C2F732DB6B56001E");
      System.out.println(map.get("SPRING_SECURITY_CONTEXT"));`

但是在取的时候报错，如下：
`org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:322)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:165)
	at org.redisson.RedissonObject.get(RedissonObject.java:69)
	at org.redisson.RedissonMap.get(RedissonMap.java:197)
	at org.test.Test.main(Test.java:54)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.springframework.security.authentication.UsernamePasswordAuthenticationToken]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: io.netty.buffer.ByteBufInputStream@1dbb35; line: 1, column: 183] (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
`
请问如果解决。

**Comment by jackygurui** [comment]
这是一个Jackson的问题。Jackson默认情况下不支持反序列化这种不带无参数构造器的类，你需要自己注册一个Mixin类来解决。或者换用其他的编码器。

**Comment by mqian-sky** [comment]
@jackygurui Mixin类什么意思 不太懂，
修改其他编码器
org.redisson.codec.SerializationCodec	JDK序列化编码
org.redisson.client.codec.StringCodec	纯字符串编码（无转换）
这两种也是有问题

**Comment by jackygurui** [comment]
Jackson的Mixin介绍在这里：
https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations

org.redisson.codec.StringCodec不适用你这种情况。

org.redisson.codec.SerializationCodec是没有问题的。
```java
RedissonClient r = Redisson.create();
r.getBucket("u", new SerializationCodec()).set(new UsernamePasswordAuthenticationToken("a", "b"));
UsernamePasswordAuthenticationToken t = (UsernamePasswordAuthenticationToken) r.getBucket("u", new SerializationCodec()).get();
```
需要注意的是用于UsernamePasswordAuthenticationToken的构造函数的两个参数的类必须是Serializable的。

**Comment by dalegaspi** [comment]
i'm having a similar problem on Spring Context object *deserialization* on multiple server setup (google translate ftw!).  on a single server (or multiple servers with sticky session enabled), i don't run into this problem, but once i use multiple servers without sticky session (so the session is created on one server, but accessed on another)...i get this error:

```
   com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.springframework.security.core.Authentication, 
problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with 
additional type information at [Source: io.netty.buffer.ByteBufInputStream@380c0706; line: 1, column: 152] 
 (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"])
 ...
```
using `org.redisson.codec.SerializationCodec` seems to have mitigated that but i would really prefer JSON serialization and I'm not entirely sure how to address this particular issue.

**Comment by jackygurui** [comment]
Again this is a Jackson problem, by default,  Jackson expect a class to have a default constructor and it will use it to create a blank object and then set its properties. The problem is In your case, the class doesn't have a default constructor, so you need to have some other ways to tell Jackson to use a none default constructor in a particular way. 

Mixin class does offer you this, or you can use a different codec to avoid it.

**Comment by dalegaspi** [comment]
thanks for the reply. is there a way to specify a mixin on the codec config?  or do i need to create my own Codec?  on that note...if i decide to write my own Codec..how do i "register" it?  or does my codec just need to be in the classpath to be recognized by redisson?  sorry for the questions. it's not clear to me how to make a custom codec recognized by redisson. thank you.

**Comment by mrniko** [comment]
@dalegaspi 

> is there a way to specify a mixin on the codec config? 

You can extend `JsonJacksonCodec` and overwrite `init(ObjectMapper objectMapper)` method to add Mixin object.

> how do i "register" it?

You can define it neither in Redisson config object or during object acquisition `redisson.getMap("mapMap", codec);`
