### ISSUE TITLE
Scan / getKeysByPattern infinite scan

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#885]
I am using version 2.2.24 of redisson and using getKeysByPattern command. It works fine if no keys are found in the redis. But, if at least one key is found then the code returns successfully. But the scan command keeps on running on the redis server.

Sample code:

Iterator<String> keysIterator = redissonClient.getKeys().getKeysByPattern(pattern).iterator();
        while (keysIterator.hasNext()) {
            String key = keysIterator.next();
            keysToDelete.add(key);
        }

Redis
1495458904.136225 [0 127.0.0.1:65465] "SCAN" "14" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136298 [0 127.0.0.1:65466] "SCAN" "7" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136359 [0 127.0.0.1:65467] "SCAN" "0" "MATCH" "*TeSt*""COUNT" "10"
1495458904.136432 [0 127.0.0.1:65468] "SCAN" "14" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136507 [0 127.0.0.1:65469] "SCAN" "7" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136579 [0 127.0.0.1:65470] "SCAN" "0" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136650 [0 127.0.0.1:65472] "SCAN" "14" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136726 [0 127.0.0.1:65471] "SCAN" "7" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136842 [0 127.0.0.1:65473] "SCAN" "0" "MATCH" "*TeSt*" "COUNT" "10"
1495458904.136958 [0 127.0.0.1:65474] "SCAN" "14" "MATCH" "*TeSt*""COUNT" "10"
1495458904.137054 [0 127.0.0.1:65465] "SCAN" "7" "MATCH" "*TeSt*""COUNT" "10"
1495458904.137149 [0 127.0.0.1:65466]

Please share the sample code of getKeysByPattern command.

**Comment by mrniko** [comment]
Are you able to reproduce it with latest Redisson version?

**Comment by Himanshu4** [comment]
I won't be able to upgrade to latest version as there are several breaking changes from 2.2.24 to 3.4.2 . Can you please tell me the minimum version in which this issue was fixed.

**Comment by Himanshu4** [comment]
Yes, this is reproducible with redisson version 3.4.2. Can you please check if there is a bug in my code. Also, check if I am using the iterator in write fashion. Basically, iterator.hasnext() never returns and continues to send command to the redis.

**Comment by Himanshu4** [comment]
I debugged and found out that "firstValues" in file "RedissonBaseIterator" never becomes empty and thus it is not returning from the hasnext() method. Please check when the keys are of type "strings". E.g. Set "test1" 2

Then use code: 

Iterator keysIterator = redissonClient.getKeys().getKeysByPattern("test*").iterator();
while (keysIterator.hasNext()) {
String key = keysIterator.next();
}

It will never return and will loop forever in hasnext() method.

**Comment by Himanshu4** [comment]
Also, the test case "testKeysIterable" in class "redissonKeysTest" is invalid. Please check.

**Comment by namit081** [comment]
👍 I am also facing the same issue. Looks like there is some bug in RedissonBaseIterator.java

**Comment by mrniko** [comment]
@Himanshu4 

> the test case "testKeysIterable" in class "redissonKeysTest" is invalid

Can you explain it?

**Comment by mrniko** [comment]
I made some patch and since I'm unable to reproduce it. Could anyone test it?

**Comment by abnkumar** [comment]
👍 I am also facing the same issue.

**Comment by Himanshu4** [comment]
@mrniko : The test case "testKeysIterable" is not modifying the set "keys" and then doing assertion on Assert.assertEquals(0, keys.size()); 
I am not sure of the purpose of the above assertion.

**Comment by mrniko** [comment]
@Himanshu4 it removes keys at RedissonKeysTest:75

**Comment by Himanshu4** [comment]
@mrniko : But it never adds any keys. So, the set was always empty. remove is not doing anything useful.

**Comment by mrniko** [comment]
Done

**Comment by Himanshu4** [comment]
This is again reproducible in version 3.6.2 when using scan by pattern and number of keys are ~2000.
The count passed to `SCAN` command is 200.

**Comment by mrniko** [comment]
Fixed
