### ISSUE TITLE
Composite Spring Cache resolution Bug

### ISSUE THREAD

**Issue by eksd** [redisson/redisson#886]
When I use CompositeCacheManager with many different CacheManagers, for example:

```CompositeCacheManager compositeCacheManager = new CompositeCacheManager();
        List<CacheManager> cacheManagers = new ArrayList<>();
        cacheManagers.add(commonCacheManager());
        cacheManagers.add(redissonCacheManager());
        compositeCacheManager.setCacheManagers(cacheManagers);
``` 

where commonCacheManager - is a  CaffeineCacheManager and redissonCacheManager is a RedissonSpringCacheManager, and when I try to use @Cacheable(value = "cacheName"), there is a bug in discovering a needed cache.

The deal is - spring trying to find cache by its name from @Cacheable and it's iterating through all registered caches in composite manager, calling  getCache(String name) in every cacheManager.

The problem is - in another cache managers there is an additional variable for dynamic getting cache and usual discovering. When you make a simple cacheManager.getCache("cache"), method getCache() creates a new cache if it's null and it's normal, but in dynamic resolving as in the @Cacheable annotation getCache() should return null.

Here is an example, how it's done in CaffeineCacheManager:

```
public Cache getCache(String name) {
    Cache cache = this.cacheMap.get(name);
    if (cache == null && this.dynamic) {
      synchronized (this.cacheMap) {
        cache = this.cacheMap.get(name);
	if (cache == null) {
	    cache = createCaffeineCache(name);
	    this.cacheMap.put(name, cache);
	}
      }
    }
    return cache;
}
```

**Comment by z0mb1ek** [comment]
is it not a bug?

**Comment by mrniko** [comment]
Done
