### ISSUE TITLE
Metrics with Redisson

### ISSUE THREAD

**Issue by alonshoshani** [redisson/redisson#887]
Is Redisson support querying metrics from Redis?
For example : 
redis-cli -h host ping
redis-cli -h host info [replication]
redis-benchmark -h host -c 10 -n 10000 -t set,get,inc -q

**Comment by jackygurui** [comment]
ping and info commands are supported. Redis-benchmark is a tool not part of the redis server function. For that purpose we have a our own benchmark project.

**Comment by mrniko** [comment]
Please use follow api :

```java
Collection<Node> nodes = (RedissonClient.getNodesGroup() or getClusterNodesGroup()).getNodes()
for (Node node : nodes) {
      node.ping();
      node.info(InfoSection.REPLICATION);
}
```
