### ISSUE TITLE
is someone use the Tomcat Session Manager ?

### ISSUE THREAD

**Issue by qq995586041** [redisson/redisson#888]
i got in trouble when i use it to share session  ,  i Configure it as the document and  create two pods with docker ,then i visit the webapp in docker , After I login successfully, I refresh the page, it  indicating that I am not logged in,Is there anyone like me? can someone tell me something ,please

**Comment by cloudhuang** [comment]
Today I'm try to config the redis session manager, but failed on tomcat7, tomcat8, tomcat8.5, could you send your configuration here - including server.xml, redssion jar files version, tomcat version? thanks.

**Comment by mrniko** [comment]
@cloudhuang 

It's easy. Here is configs examples: https://github.com/redisson/redisson/tree/master/redisson-tomcat/redisson-tomcat-8/src/test/webapp

**Comment by mrniko** [comment]
@qq995586041 

Please ensure both Redisson instances connected to the same database or use same configuration

**Comment by cloudhuang** [comment]
@marko-stankovic  thanks, I got the point.
