### ISSUE TITLE
Need some help to understand the cause of this error please.

### ISSUE THREAD

**Issue by mikimoyal** [redisson/redisson#890]
Details : Redisson (3.3.1) using cluster mode:

Exception:
com.revcontent.spark.streaming.exception.RedisClientAdaptorException: ERR Error running script (call to f_04ca52da6f32fea58a7378efe5e857fbdc376470): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0xafc7451e, /10.99.1.42:59157 => /10.120.42.238:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@32a8871[Not completed], command=(EVAL), params=[if redis.call('hexists', KEYS[1], ARGV[4]) == 0 then if tonumber(ARGV[1]) > 0 then redis.call('zadd'..., 3, campaign_widget_stats, redisson__timeout__set:{campaign_widget_stats}, redisson__idle__set:{campaign_widget_stats}, 1498161005083, 0, 0, impressions, 0], codec=org.redisson.client.codec.StringCodec@414979d2]

**Comment by mikimoyal** [comment]
Tried Redisson 3.4.2 and the error is very similar to 3.3.1:

Exception:org.redisson.client.RedisException: ERR Error running script (call to f_4164723172cc78dd2e6fca4904421598a76187e7): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x466279af, /10.99.1.42:56670 => /10.120.42.137:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@77347e3f[Not completed], command=(EVAL), params=[local insertable = false; local value = redis.call('hget', KEYS[1], ARGV[5]); if value == false then..., 3, algorithm_stats_v2, redisson__timeout__set:{algorithm_stats_v2}, redisson__idle__set:{algorithm_stats_v2}, 1495647392220, 1498239392220, 0, 0, impressions, ...], codec=org.redisson.client.codec.StringCodec@7085c7ca]
org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:267)
org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)

**Comment by mikimoyal** [comment]
RMapCache<Object, Object> map1 = redisson.getMapCache("campaign_widget_stats", StringCodec.INSTANCE);
        map1.forEach((k,v)->{
            System.out.println(k + "-->" +v);

        });     
Here is another example:

        org.redisson.client.RedisException: ERR Error running script (call to f_c0904432d8f06697982101c899fb869fc0682cbd): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0x86337f14, L:/10.99.1.42:65187 - R:/10.120.42.238:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@28920d83, command=(EVAL), params=[local result = {}; local idleKeys = {}; local res = redis.call('hscan', KEYS[1], ARGV[2]); local cur..., 3, campaign_widget_stats, redisson__timeout__set:{campaign_widget_stats}, redisson__idle__set:{campaign_widget_stats}, 1495725823821, 0], codec=org.redisson.client.codec.StringCodec@6491db94]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:267)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)

**Comment by mrniko** [comment]
What was the problem?

**Comment by mikimoyal** [comment]
versioning
