### ISSUE TITLE
RedissonBoundedBlockingQueue.pollAsync blocks if timeout is less than 1 second

### ISSUE THREAD

**Issue by komsit37** [redisson/redisson#896]
In `RedissonBoundedBlockingQueue.pollAsync`, if timeout is less than 1 second, it will be round to 0. 0 is interpreted as indefinite timeout. Thus, pollAsync never returns.
```
    @Override
    public RFuture<V> pollAsync(long timeout, TimeUnit unit) {
        RFuture<V> takeFuture = commandExecutor.writeAsync(getName(), codec, RedisCommands.BLPOP_VALUE, getName(), unit.toSeconds(timeout));
        return wrapTakeFuture(takeFuture);
    }
```
I understand timeout < 1 second is not supported in  `BLPOP` command, but at least, this behavior is a surprise for me who didn't know poll is map to `BLPOP` command.

I am not sure what is the best way to improve this, here are some ideas:
1. default behavior should round up to 1 second if not 0
2. do not allow time out less than 1 second
3. just mention this behavior in the documentation

**Comment by mrniko** [comment]
It's a bug. I will fix that by using method `RedissonQueue.toSeconds` to calculate time

**Comment by mrniko** [comment]
Fixed
