### ISSUE TITLE
redisson can use oracle jdk?

### ISSUE THREAD

**Issue by somnus-lin** [redisson/redisson#897]
redission can  use oracle jdk? there is a old project in my company, I use the redisson as a redis client in my project ,but the console like this:java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe, so I see the oracle jdk , it only sun.misc.Unsafe, thank you!

**Comment by mrniko** [comment]
Yes, it should work.

**Comment by somnus-lin** [comment]
thank you !
