### ISSUE TITLE
Data deserialization error after upgrade to version 2.9.2

### ISSUE THREAD

**Issue by diogonicoleti** [redisson/redisson#901]
I upgraded Redisson to `2.9.2` and several `JsonMappingException` occurred:
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: 
        No suitable constructor found for type
```
Looking for why it happened i discovered that it happens because support for `@ConstructorProperties` was added only in Jackson 2.7 version (https://github.com/FasterXML/jackson-databind/issues/905) and in this commit https://github.com/redisson/redisson/commit/c14e97c0688dfdadb89536cf2285c104d35138d7 jackson was downgraded to 2.6.7 to maintain JDK 1.6 compatibility.

According to Jackson release notes, still be possible to use Jackson 2.7 on Java 6: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7#changes-compatibility

@mrniko can i open a pull request to upgrade jackson to 2.7.6 again?

**Comment by mrniko** [comment]
> According to Jackson release notes, still be possible to use Jackson 2.7 on Java 6: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7#changes-compatibility

Only `jackson-core` and `jackson-annotations` modules are Java 6 compatible.

For now you can resolve it by replacing jackson version using maven or gradle dependency management.

**Comment by diogonicoleti** [comment]
@mrniko i already done this to solve this problem for now, but there is a quote that says:
> So it should still be possible to use Jackson 2.7 on Java 6, but not compile, build.

In this case, jackson 2.7.x is compatible with JDK 1.6 at runtime. For safety, i make some tests using redisson with jackson 2.7.6 dependencies running on JDK 1.6 and it's ok.

**Comment by mrniko** [comment]
Cool! Waiting for your PR
