### ISSUE TITLE
Port out of range:-1 when using 'redis://' to configure RedissonClient

### ISSUE THREAD

**Issue by cigano** [redisson/redisson#902]
I made the following test: 

    Config config = new Config();
    config.useSingleServer().setAddress("redis://127.0.0.1:6379");

I had an error message like this: 

    java.lang.IllegalArgumentException: port out of range:-1

Using like this:

    Config config = new Config();
    config.useSingleServer().setAddress("127.0.0.1:6379");

It works perfectly. 

Shouldn't be better to accept all the configuration formats without problems? Like using `config.useClusterServers().addNodeAddress("redis://127.0.0.1:7181");` (from Wiki).

**Comment by mrniko** [comment]
Yeah, master version hasn't been released yet.

**Comment by stodge** [comment]
I just tried this on master:

redisConfig.useSingleServer().setAddress("xxx.xx.xx.xxx:6379");

And I got:

java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: xxx.xx.xx.xxx:6379

**Comment by mrniko** [comment]
> Unable to connect to Redis server: /xxx.xx.xx.xxx:6379

tells that Redisson is unable to connect to your server. Please check it

**Comment by stodge** [comment]
That's what I thought but doesn't the "slash" in the address mean the URI is wrong?

**Comment by mrniko** [comment]
Nice. I hope to make a release during this week
