### ISSUE TITLE
Any way to get a list of all the map caches in Redisson?

### ISSUE THREAD

**Issue by stodge** [redisson/redisson#906]
I may have missed this, but is there a way to get a list of all the map caches in Redisson? I have this functionality in my hazelcast based code that I am trying to update and it's useful to use for logging.

Thinking about it, this feature would be useful for other collections and objects etc.

Thanks

**Comment by mrniko** [comment]
It's possible to do it with workaround like this:
```java
// each map cache has a name prefix
RMapCache cache = redisson.getMapCache("myMap:mapCache");

// find all caches
Iterable<String> allMapCacheNames = redisson.getKeys().getKeysByPattern("*:mapCache");
```

**Comment by stodge** [comment]
Ah, perfect, thanks!

**Comment by mrniko** [comment]
You're welcome!
