### ISSUE TITLE
Using locks to synchronize master/standby functionality?

### ISSUE THREAD

**Issue by stodge** [redisson/redisson#907]
I'm using a lock in Hazelcast to implement "single master" functionality for service applications. Hazelcast's lock is release when the owner dies.

So basically, say I have two applications that provide the same service, called A and B. A and B both start, but B grabs the lock for that service. B becomes ACTIVE and starts its processing. A becomes STANDBY and waits for that lock.

B dies, the lock is released. A grabs the lock and it becomes ACTIVE and starts its processing.

B restarts, tries to grab the lock but fails, so it becomes STANDBY and it waits for the lock.

Now I read in a ticket that a lock is still held when the owning process dies, which is counter to what I need.

Can you make any suggestions how to implement this functionality in Redisson?

Thanks again

**Comment by mrniko** [comment]
By default Redisson Lock is released if client is not responding during 30 seconds

**Comment by stodge** [comment]
Ah, so if the app dies, then the lock isn't released for 30s? That's too long for my needs - I need to activate the STANDBY within a second or two. Thanks again.

**Comment by mrniko** [comment]
Related to https://github.com/redisson/redisson/issues/775

**Comment by mrniko** [comment]
I have just added `lockWatchdogTimeout` parameter. Now you can set it to 3 seconds it should help

**Comment by stodge** [comment]
Thanks. Apologies for the comment after the issue was closed.

This still doesn't help me as when an app grabs the lock it needs to hold it forever (i.e. the watchdog isn't needed at this point). I only need the watchdog after the app dies. I'll re-read the Redisson docs to see if anything else will cover this requirement for me.
