### ISSUE TITLE
Simple example about how to retrieve object using RBucketReactive

### ISSUE THREAD

**Issue by cigano** [redisson/redisson#911]
I didn't find any simple examples about how to retrieve an object using `RBucketReactive`. Here's my example:

    RedissonReactiveClient reactiveClient = Redisson.createReactive();
    List<RBucketReactive<MyDTO>> buckets = reactiveClient.findBuckets("dtos::*");
    for (RBucketReactive<MyDTO> bucket: buckets)
    {
        // First I tried to obtain an object just with the `.get()` method, but the return is a Publisher<MyDTO>. 
        MyDTO test = bucket.get(); // conversion error

        // I found this: https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/BaseReactiveTest.java
        // Tried to do something similar:
        MyDTO test = ((Promise<MyDTO>)bucket.get()).poll(); // this gives java.lang.ClassCastException: org.redisson.reactive.NettyFuturePublisher cannot be cast to reactor.rx.Promise
    }

Can someone help?

**Comment by mrniko** [comment]
If you call methods in synchronous way. Why do you need to use RBucketReactive then? Because it's designed for `reactive` usage and not synchronous.

**Comment by mrniko** [comment]
In your case this should help:
```java
Promise<V> promise  = Streams.wrap(bucket.get()).next();
promise.poll()
```

**Comment by cigano** [comment]
> If you call methods in synchronous way. Why do you need to use RBucketReactive then? Because it's designed for reactive usage and not synchronous.

Because I need to use `reactiveClient.findBuckets("dtos::*");`. I didn't find this at synchronous client.

**Comment by mrniko** [comment]
Oh, it's easy: RedissonClient.getBuckets().find(`byPattern`)

**Comment by cigano** [comment]
I think the Wiki can be improved with more examples. Are you accepting suggestions for Wiki?

**Comment by mrniko** [comment]
Sure

**Comment by cigano** [comment]
Alright. Both approches worked. I'm closing this issue. Thanks!
