### ISSUE TITLE
Security vulnerability with jackson

### ISSUE THREAD

**Issue by Flo354** [redisson/redisson#912]
There is a deserialization security vulnerability in the **jackson-databind** version you are using.
See [Jackson Deserializer security vulnerability issue 1599](https://github.com/FasterXML/jackson-databind/issues/1599)

Fixed in [2.7.9.1](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.7.9.1)

**Comment by jackygurui** [comment]
We have employed a similar mitigation https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/codec/DefenceModule.java

**Comment by Flo354** [comment]
Seems good to me, thanks.
