### ISSUE TITLE
RScoredSortedSet<String> appends unexpected double quotes to the string value

### ISSUE THREAD

**Issue by zuanoc** [redisson/redisson#925]
RScoredSortedSet<String> always put the double quotes to the string value which stored in Redis. The following is how to reproduce the issue:

1. Add string value to RScoredSortedSet<String> in Java
```
RScoredSortedSet<String> set = redisson.getScoredSortedSet("test_score_set_1");
set.add(1d, "1:100");
```

2. List all the values in the ZSet via redis-cli
```
127.0.0.1:6379> zrange test_score_set_1 0 -1
1) "\"1:100\""
```

The listed value should be `"1:100"` instead of `"\"1:100\""`

**Comment by mrniko** [comment]
Because you're using json codec. I suggest you to use StringCodec either globally though Config object or define it during object acquisition: `redisson.getScoredSortedSet("mySet", StringCodec.INSTANCE);`
