### ISSUE TITLE
Sentinel: MasterConnectionPool no available Redis entries

### ISSUE THREAD

**Issue by archmisha** [redisson/redisson#926]
Hi,
I have 3 nodes of redis configured as sentinel.
This is my config:
```
                    SentinelServersConfig sentinelServersConfig = config.useSentinelServers();                    
                    sentinelServersConfig.setMasterName("redis-cluster");
                    for (String server : servers) {
                        sentinelServersConfig.addSentinelAddress("redis://" + server + ":" + port);
                    }
                    Redisson.create(config)
```

When terminating the master node, redis cluster allocated a new master but Redisson fails to recognize that and starts to fail with this error:
MasterConnectionPool no available Redis entries.  Disconnected hosts: [/100.127.5.18:6379]
Seems that it fails to recover and locate the new master.

**Comment by mrniko** [comment]
How many slave and master nodes do you have? Could you provide Redisson log? Keep in mind new master discovery takes some time, depending on your settings.

**Comment by archmisha** [comment]
I have 3 nodes total, 1 master and 3 slaves. 
I waited long and it never recovered. 
Which log you refer ro?

**Comment by mrniko** [comment]
Please set logger level for `org.redisson` package to `DEBUG` and share gathered log

**Comment by archmisha** [comment]
Seems now it is not reproduced for me
