### ISSUE TITLE
Can't cache methods resulting in Optional

### ISSUE THREAD

**Issue by thiago-negri** [redisson/redisson#928]
Using Spring + `RedissonSpringCacheManager`, I can't cache methods returning `Optional<T>`. Sample:

```java
@Service
public class MyService {
    @Cacheable("myCache")
    public Optional<String> testCache(int foo) {
        return Optional.empty();
    }
}
```

Spring automatically "unwraps" the result from `Optional` before sending it to cache manager, see `org.springframework.cache.interceptor.CacheAspectSupport#unwrapReturnValue`:

```java
private Object unwrapReturnValue(Object returnValue) {
	if (returnValue != null && returnValue.getClass() == javaUtilOptionalClass) {
		return OptionalUnwrapper.unwrap(returnValue);
	}
	return returnValue;
}
```

Which returns `null` when the optional is empty:

```java
public static Object unwrap(Object optionalObject) {
	Optional<?> optional = (Optional<?>) optionalObject;
	if (!optional.isPresent()) {
		return null;
	}
	Object result = optional.get();
	Assert.isTrue(!(result instanceof Optional), "Multi-level Optional usage not supported");
	return result;
}
```

Then `org.redisson.RedissonMap#fastPutAsync` doesn't support map's value being null, so I receive a `NullPointerException`.

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/853

**Comment by thiago-negri** [comment]
@mrniko Which version should I use to get the fix?

**Comment by mrniko** [comment]
2.9.x
