### ISSUE TITLE
Redisson (3.x.x) failed to initialize in Replicated connection with one of the nodes is not online

### ISSUE THREAD

**Issue by jackygurui** [redisson/redisson#932]
A connection refused exception is been thrown at [this line](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java#L131) when a node is offline during the initialization period. https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/ReplicatedConnectionManager.java#L131

Problem is only related to CompletableFuture

**Comment by mrniko** [comment]
Fixed

**Comment by jackygurui** [comment]
Thanks
