### ISSUE TITLE
URI Builder Issue in 3.4.3 jar- java.lang.IllegalArgumentException: Illegal character in scheme name at index 0:

### ISSUE THREAD

**Issue by Madhu147** [redisson/redisson#935]
aused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: [<<HOST>>]:<<PORT>>
        at java.net.URI.create(URI.java:852) ~[na:1.8.0_121]
        at org.redisson.misc.URIBuilder.create(URIBuilder.java:37) ~[redisson-3.4.3.jar:na]
        at org.redisson.config.ClusterServersConfig.addNodeAddress(ClusterServersConfig.java:57) ~[redisson-3.4.3.jar:na]

Host and Port removed. tried using the 3.4.3 redisson all jar and receiving the above issue, however, this was not observed with the 3.4.2 jar. Did the node address syntax change?

**Comment by jackygurui** [comment]
Yes. In order to incorporate the SSL capability, we've added the scheme to the URI, so for SSL connection you need to prefix it with rediss:// and for non SSL connection you need to use redis://

**Comment by Madhu147** [comment]
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
        at org.redisson.cluster.ClusterConnectionManager.<init>(md:276)
        at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:278)
        at org.redisson.Redisson.<init>(sq:26)
        at org.redisson.Redisson.create(sq:238)

I am receiving following error while using the rediss:// prefixed to the host. I used a pro version of 3.4.3-1 and also tried 3.4.3 now

**Comment by jackygurui** [comment]
Can you tell how did you run the SSL channel on the redis side ?

**Comment by Madhu147** [comment]
i am using the redis properties below is a snippet in my code
@Configuration
@AutoConfigureAfter(RedisAutoConfiguration.class)
public class RedissonConfiguration{
	@Autowired
    private RedisProperties redisProperties;
    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
       config.setRegistrationKey(<<Reg key>>);
        
        if(redisProperties.getCluster()!=null){
            	ClusterServersConfig clusterServersConfig = config.useClusterServers();
            	List<String> nodes = redisProperties.getCluster().getNodes();
            	
            	if(null!=nodes && nodes.size()>0){
            	clusterServersConfig.addNodeAddress(nodes.toArray(new String[nodes.size()]));
            	}
            	return Redisson.create(config);
         }
        return null;
    }

**Comment by jackygurui** [comment]
Sorry, I saw you have used `rediss://` as the URI scheme which indicates you are using a SSL connection on top of the Redis, this typically require some external setup as the standard redis cluster does not come with SSL support built in. It must done through a third party library.

The error message tells me there is a problem on the connection side, not related to how redisson is configured. So can you double check if you are really running the SSL proxy and is it configured properly?

If you are not using any SSL proxy please change the URI scheme to `redis://` (with only 1 `s`) and try it again.
