### ISSUE TITLE
SCAN command is not getting used in deleteByPattern

### ISSUE THREAD

**Issue by Himanshu4** [redisson/redisson#942]
#534 issue is not fixed. 

The code is still not fixed. I am using elasticache servers and redisson version 3.4.3

if (!commandExecutor.getConnectionManager().isClusterMode()) {
            return commandExecutor.evalWriteAsync((String)null, null, RedisCommands.EVAL_LONG, "local keys = redis.call('keys', ARGV[1]) "
                              + "local n = 0 "
                              + "for i=1, #keys,5000 do "
                                  + "n = n + redis.call('del', unpack(keys, i, math.min(i+4999, table.getn(keys)))) "
                              + "end "
                          + "return n;",Collections.emptyList(), pattern);
        }

**Comment by mrniko** [comment]
Done
