### ISSUE TITLE
Cannot connect using Sentinel and Database != 0 ("unknown Command SELECT")

### ISSUE THREAD

**Issue by wwurzer-twyn** [redisson/redisson#943]
final Config config = new Config();

        config.useSentinelServers()
                .setMasterName("master")
                .setDatabase(4)
                .setPassword(PASSWORD)
                .addSentinelAddress("redis://192.168.201.103:26380")
                .addSentinelAddress("redis://192.168.201.104:26380")
                .addSentinelAddress("redis://192.168.201.105:26380");

        redisson = Redisson.create(config);`

SentinelConnectionManager fails with 

` 
org.redisson.client.RedisConnectionException: Unable to connect to: /192.168.201.103:26380
` 

caused by

` 
org.redisson.client.RedisException: ERR unknown command 'SELECT'. channel: [id: 0x83dff48c, L:/192.168.3.125:43366 - R:/192.168.201.103:26380] command: CommandData [promise=org.redisson.misc.RedissonPromise@3bcac1f6[Not completed], command=(SELECT), params=[4], codec=null]
`

because Sentinel does not understand `SELECT`

should be fixed in org.redisson.connection.MasterSlaveConnectionManager#createRedisConfig

`setDatabase` should only be called for non-sentinel instances

**Comment by mrniko** [comment]
Fixed in https://github.com/redisson/redisson/issues/924
