### ISSUE TITLE
cloud not find redisson:client in config xml when server start

### ISSUE THREAD

**Issue by xiaocw** [redisson/redisson#950]
errorInfo:
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 26 in XML document from class path resource [application-service.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 26; columnNumber: 42; cvc-complex-type.2.4.c: 通配符的匹配很全面, 但无法找到元素 'redisson:client' 的声明。

The config header is copy from this project https://github.com/redisson/redisson/wiki/14.-%E7%AC%AC%E4%B8%89%E6%96%B9%E6%A1%86%E6%9E%B6%E6%95%B4%E5%90%88
my config as bellow:
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:mvc="http://www.springframework.org/schema/mvc"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:redisson="http://redisson.org/schema/redisson"
       xmlns:util="http://www.springframework.org/schema/util"
       xsi:schemaLocation="
        http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context-4.0.xsd
        http://www.springframework.org/schema/util
       http://www.springframework.org/schema/util/spring-util.xsd
        http://www.springframework.org/schema/mvc
        http://www.springframework.org/schema/mvc/spring-mvc-4.0.xsd
        http://www.springframework.org/schema/tx
        http://www.springframework.org/schema/tx/spring-tx-4.0.xsd
         http://redisson.org/schema/redisson
       http://redisson.org/schema/redisson/redisson.xsd
        ">
    <context:component-scan base-package="com.rqb.*.service" />
    
    <redisson:client id="redissonClient">
        <redisson:single-server address="192.168.0.32::6380"/>
    </redisson:client>
</beans>

**Comment by jackygurui** [comment]
你能不能把整个文件都转发一下呢？

**Comment by xiaocw** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:mvc="http://www.springframework.org/schema/mvc"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:redisson="http://redisson.org/schema/redisson"
       xmlns:util="http://www.springframework.org/schema/util"
       xsi:schemaLocation="
        http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context-4.0.xsd
        http://www.springframework.org/schema/util
       http://www.springframework.org/schema/util/spring-util.xsd
        http://www.springframework.org/schema/mvc
        http://www.springframework.org/schema/mvc/spring-mvc-4.0.xsd
        http://www.springframework.org/schema/tx
        http://www.springframework.org/schema/tx/spring-tx-4.0.xsd
         http://redisson.org/schema/redisson
       http://redisson.org/schema/redisson/redisson.xsd
        ">
    <context:component-scan base-package="com.rqb.*.service" />

    <redisson:client id="redissonClient">
        <redisson:single-server address="192.168.0.32:6380"/>
    </redisson:client>
</beans>


can you share a redission demo integerated with springmvc to me?

**Comment by jackygurui** [comment]
You can find plenty examples in the test package

XML files are located here:
https://github.com/redisson/redisson/tree/master/redisson/src/test/resources/org/redisson/spring/support

Source files are located here:
https://github.com/redisson/redisson/tree/master/redisson/src/test/java/org/redisson/spring/support

**Comment by MrH2H** [comment]
@jackygurui 
当与spring按照文档集成的时候,就直接报错:是还需增加额外的配置吗?谢谢~


   \<beans xmlns="http://www.springframework.org/schema/beans"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:context="http://www.springframework.org/schema/context"
       xmlns:redisson="http://redisson.org/schema/redisson"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans 
        http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
       http://www.springframework.org/schema/context 
      http://www.springframework.org/schema/context/spring-context-4.0.xsd
       http://redisson.org/schema/redisson http://redisson.org/schema/redisson/redisson.xsd
">
\<description>Redisson\</description>
   \<redisson:client>
    
   	 	\<redisson:single-server/>
	</redisson:client>

</beans>






Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://redisson.org/schema/redisson]


org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:spring/applicationContext-redisson.xml]
Offending resource: class path resource [spring/spring-context.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://redisson.org/schema/redisson]
Offending resource: class path resource [sprin
`
`````g/applicationContext-redisson.xml]

	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:240)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:191)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:176)

Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://redisson.org/schema/redisson]
Offending resource: class path resource [spring/applicationContext-redisson.xml]

**Comment by xiaocw** [comment]
@MrH2H 
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:redisson="http://redisson.org/schema/redisson"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd
       http://redisson.org/schema/redisson **classpath:org/redisson/spring/support/redisson-1.1.xsd**">
   
<context:annotation-config />
    <context:property-placeholder system-properties-mode="OVERRIDE"/>


	<redisson:client>
        <redisson:single-server address="redis://192.168.0.32:6379"/>
    </redisson:client>
    










    
</beans>

注意 是使用的jar包里面的xds文件，我终于跑起来了

**Comment by xiaocw** [comment]
classpath:org/redisson/spring/support/redisson-1.1.xsd

**Comment by jackygurui** [comment]
请确保http://redisson.org/schema/redisson/redisson.xsd这个地址能够正常访问。
