### ISSUE TITLE
can I use redisson with spring-session as a spring-xml config

### ISSUE THREAD

**Issue by Vcgoyo** [redisson/redisson#952]
I can't find the example how can i use redisson with spring-session as a spring-xml config 
this is my spring-xml 

    <bean class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory" >
		<constructor-arg name="poolConfig" ref="jedisPoolConfig"></constructor-arg>
		<property name="hostName" value="10.33.25.13"></property>
		<property name="port" value="6379"></property>
	 </bean>
	 
	<bean id="redisHttpSessionConfiguration" class="org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration" />

	<redisson:client>
    	<redisson:single-server address="redis://10.33.25.13:6379"/>
	</redisson:client> 

Now I config redis-server twice  and  i must  add spring-data-redis and jedis for the spring-session. the redisson's wiki show the code  we can config with java code to use this 2, but i don't know how can i use thsi 2 with  spring-xml config

**Comment by mrniko** [comment]
Just replace `org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration` bean in your configuration with `org.redisson.spring.session.config.RedissonHttpSessionConfiguration`

**Comment by Vcgoyo** [comment]
thanks a lot I will be try

**Comment by Vcgoyo** [comment]
Now it has other problem
1.  the property of this class  `RedissonHttpSessionConfiguration`    `maxInactiveIntervalInSeconds` don't have a  default value,I must Specify a value in spring bean xml config otherwise it will throw nullpointExpection
2. when I  do what is said above and startup tomcat  it will show me another expection 

```
 07, 2017 10:15:51 org.apache.catalina.core.ApplicationContext log
Initializing Spring FrameworkServlet 'springmvc'
2017 10:15:53 org.apache.coyote.AbstractProtocol start
Starting ProtocolHandler [http-nio-8080]
07, 2017 10:15:53  org.apache.coyote.AbstractProtocol start
Starting ProtocolHandler [ajp-nio-8009]
07, 2017 10:15:53 org.apache.catalina.startup.Catalina start
 Server startup in 42556 ms
Exception in thread "redisson-3-1" java.lang.NoSuchMethodError: org.springframework.context.ApplicationEventPublisher.publishEvent(Ljava/lang/Object;)V
	at org.redisson.spring.session.RedissonSessionRepository.publishEvent(RedissonSessionRepository.java:272)
	at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:256)
	at org.redisson.spring.session.RedissonSessionRepository.onMessage(RedissonSessionRepository.java:50)
	at org.redisson.PubSubPatternMessageListener.onPatternMessage(PubSubPatternMessageListener.java:80)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:87)
	at org.redisson.client.handler.CommandDecoder$1.run(CommandDecoder.java:368)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```
looks like this has some problem?

    private void publishEvent(Object event) {
     try {
        this.eventPublisher.publishEvent(event);
       } catch (Exception arg2) {
         log.error(arg2.getMessage(), arg2);
       }
     }


and my config 


	
    <context:annotation-config/>
	  
	<context:property-placeholder/>
	<redisson:client>
    	<redisson:single-server address="redis://10.33.25.13:6379"/>
	</redisson:client>

	 <bean id="redissonHttpSessionConfiguration"  class="org.redisson.spring.session.config.RedissonHttpSessionConfiguration" >
	 	<property name="maxInactiveIntervalInSeconds" value="1800"></property>
	 </bean>

**Comment by mrniko** [comment]
which spring version do you use?

**Comment by Vcgoyo** [comment]
@mrniko  spring 4.0.7  and spring-session 1.3.1

**Comment by Vcgoyo** [comment]
@mrniko I find the problem maybe because   I use redisson's  BoundedBlockingQueue  ,  I guess the class `RedissonSessionRepository'      and the      `onMessage`    this method should  judge the  params  when redis send a `__keyevent`  ?

**Comment by mrniko** [comment]
I think it's related to https://github.com/redisson/redisson/issues/959

**Comment by Vcgoyo** [comment]
I find the problem which which the interface `ApplicationEventPublisher`  add a  method from `spring4.2` and it's has this two , 'public abstract void publishEvent(ApplicationEvent paramApplicationEvent)'  `public abstract void publishEvent(Object paramObject);`  but below spinrg 4.2 ,it;s just have `public abstract void publishEvent(ApplicationEvent paramApplicationEvent)` So  Just modify  the method of `RedissonSessionRepository`    `private void publishEvent(Object event)` to  `private void publishEvent(ApplicationEvent event)` ,so that  compatible with all spring version,and I will have a pull request later

**Comment by mrniko** [comment]
Fixed
