### ISSUE TITLE
Parse URI error in 3.4.3

### ISSUE THREAD

**Issue by gotev** [redisson/redisson#953]
After updating to 3.4.3 I got a parse URI exception by setting my Redis address, which is in the form: `redis-instance.something.else.0001.euc3.cache.amazonaws.com`. Switching back to 3.4.2 everything works fine. The error relies in `org.redisson.misc.URLBuilder.create` which has been changed in 3.4.3

**Comment by jackygurui** [comment]
This is related to #935

**Comment by mrniko** [comment]
just specify "redis://" for your network address

**Comment by gotev** [comment]
I can confirm it works! Thank you!
