### ISSUE TITLE
[Question] Netty dependencies problems / shading 

### ISSUE THREAD

**Issue by kringol** [redisson/redisson#954]
Since netty keeps being a source of headaches sometimes, specially when using this library in combination with Play Framerwork or AsyncHttpClient or gRPC, as all of them use Netty, and netty seems to not play very nice with differences even on minor and hotfix versions.

Now i am testing with the newly release play 2.6 which has netty 4.0.x but since this version they shaded it, but i am still having issues when trying to use the nativeEpoll and including the dependency to redisson, I am still trying to figure out the cause, since the dependency is there but i still get 
java.lang.NoSuchMethodError: Method io.netty.channel.epoll.Native.recvFd0(I)I not found

I will be testing a few more things soon, but if anyone has observed anything like that using play 2.6, feel free to mention.

**Comment by johnou** [comment]
Perhaps SO would be a better suited place for a question like this.. I'd like to hear more about those headaches you have experienced between minor / hotfix versions. Perhaps you are including different versions of Netty on your class path in which case you should look into importing the Netty bom. To have Netty epoll work as a shaded dependency you need to specify the package prefix.. See https://github.com/netty/netty/issues/6665 for more details.

**Comment by kringol** [comment]
Hi @johnou.
Yes, i agree on that. The main reason i also posted this here as a question is about redisson thoughts on the netty side. As there are many cases where this lib is used in combination with other libs like, cassandra-driver, grpc, play framework, etc. And many of them use netty as well, but some of them uses for example netty 4.0.x while redisson (and others) use version 4.1.x since a many versions ago, and both versions are incompatible. I know that for instance play 2.6 decided to shade their netty dependency to avoid those issues. So this is more of policy kind of question about if redisson plans to do something similar at some point or not. 

Regarding the particular problem i have, i was trying with the shade config, but i believe the problem is on play side or config side, but i will figure it out somehow, meanwhile it works fine without native epoll ;)
