### ISSUE TITLE
Unable to locate Spring NamespaceHandler for XML schema namespace [http://redisson.org/schema/redisson]

### ISSUE THREAD

**Issue by blessworld** [redisson/redisson#961]
version:2.9.3
错误日志:
Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://redisson.org/schema/redisson]

3.4.3版本的jar里面是有spring.scheme和org.redisson.spring.support.RedissonNamespaceHandlerSupport这两个文件的
然而在2.9.3的jar包里面并没有xsd文件和spring.scheme相关文件
导致spring配置
http://redisson.org/schema/redisson http://redisson.org/schema/redisson/redisson.xsd会报错

**Comment by watchworld** [comment]
version3.4.3 also have this question

**Comment by jackygurui** [comment]
从[这里](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.redisson%22%20AND%20a%3A%22redisson%22)下载到的JAR包里面都有的这两个文件的。

**Comment by mrniko** [comment]
Hi, sorry about broken link. It works now.
