### ISSUE TITLE
Tomcat does not delete keys on Redis when session expires.

### ISSUE THREAD

**Issue by iakko** [redisson/redisson#972]
Hello,

I'm using Redisson with two Tomcat, each one in a virtual instance behind a Load Balancer on Azure, using Azure Redis PaaS as centralized database.

Everything works great, both Tomcat can create and store session on Redis (I can easily see keys/values serialized on Redis) and both can retrieve the stored session correctly.

My issue/question is: should Tomcat be able to delete keys automatically from Redis when the session expires? The sessionDestroyed() method on the SessionListener in correctly invoked, so I'm sure that Tomcat is destroying the session internally, but keys keep staying on Redis. I was assuming that Tomcat, through Redisson, whould be able to delete keys from Redis as well.

Thanks.
IP

**Comment by mrniko** [comment]
You discovered a serious bug. It works properly only for Tomcat 6.

**Comment by mrniko** [comment]
Fixed

**Comment by iakko** [comment]
Thanks for being so quick about that.

Do you know when the fixed version will be available?

**Comment by mrniko** [comment]
Thank you! During this week

**Comment by iakko** [comment]
Ok, as soon as you will release the fixed package, I'll test it and I'll let you know.
Thank to you!

**Comment by iakko** [comment]
Hello @mrniko, I can't wait to test the fix, do you know when it will be available?

**Comment by mrniko** [comment]
Cool. New release has just been published.

**Comment by vk185160** [comment]
Even I have come across with similar issue for tomcat 8. could you please have a look and let me know?

**Comment by mrniko** [comment]
@vk185160 

Can you share more details about the issue? Or improve the current test to reproduce it?

**Comment by vk185160** [comment]
okay basically we are using tomcat redisson session manager to use redis as a centralised database for session management

our tomcat config for the same looks like this
<Manager className="com.liferay.redis.redisson.integration.tomcat.LiferayRedissonSessionManager" configPath="${catalina.base}/redisson.conf"  readMode="MEMORY" updateMode="AFTER_REQUEST"  broadcastSessionEvents="true" broadcastSessionUpdates="true"/>

**Comment by mrniko** [comment]
Functionality works properly and covered by test https://github.com/redisson/redisson/blob/792fb792b84b3f0bac04efa2c1e8d509472d765a/redisson-tomcat/redisson-tomcat-8/src/test/java/org/redisson/tomcat/RedissonSessionManagerTest.java#LL267C52-L267C52

Let me know if you can change the test to reproduce your case.
