### ISSUE TITLE
Retrieve RMap keys by pattern

### ISSUE THREAD

**Issue by hans123456** [redisson/redisson#978]
Hi,

Redis has the feature HSCAN to retrieve the hash keys that matches the given pattern.
I will retrieve the values one by one through get after filtering the keys because some of the keys will contain objects that do not exists for the certain environment.

Is there a way to do this without modifying your code?

Thanks =)

**Comment by mrniko** [comment]
Hi, 

It's not implemented yet, but I plan to implement it.

**Comment by mrniko** [comment]
Done
