### ISSUE TITLE
Redisson执行命令超时，已设置超时时间为60s，是否存在bug？

### ISSUE THREAD

**Issue by fsindustry** [redisson/redisson#984]
redis集群规模：20个节点，10主、10从；

17:21:00 [pool-57-thread-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled
 task.                                                                                                          
org.redisson.client.RedisTimeoutException: Redis server response timeout (60000 ms) occured for command: (EVAL) 
with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('
pe..., 1, com.baidu.baixiao.dict.cache.CacheHandlerImpl, 30000, 296bce1e-7062-4778-88d0-6ac3c4819163:133] channe
l: [id: 0x42335488, L:/10.0.3.2:37336 - R:/10.150.177.11:8379]                                                  
        at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:646)                        
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)                  
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)           
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)                                 
        at java.lang.Thread.run(Thread.java:745)                                                                
17:21:01 [http-nio-8080-exec-17] INFO  c.b.g.s.i.AbsSecurityInterceptor - Intercept RateLimitInterceptor begin c
heck request /search.

**Comment by jackygurui** [comment]
你的retryAttempts和retryInterval设定的是多少？

**Comment by miriamccp** [comment]
請問你建議設定多少? 這個問題很困擾我,原本在lab環境都測試ok準備上線了,到了staging環境卻一直遇到這個timeout問題,但是,同樣是staging環境,用jedis就可以,jedis沒有timeout問題.非常需要有人幫忙解答.謝謝!!

**Comment by jackygurui** [comment]
产生这个timeout的原因除了服务器响应不过来以外，还有当一个命令无法获取一个空闲连接以后，经过几次努力都失败而抛出。因此这两个参数需要根据你自己的使用环境调节，并发量和网络繁忙程度等待因素都需要考虑。Jedis遇到这种问题连重试都不会，它会直接抛`redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool` 这个错误。

**Comment by fsindustry** [comment]
@jackygurui 
retryAttempts是5次；
retryInterval是30秒； 
另外，我们配置了20个redis实例，启动时，占用句柄数有好几千；请问这个有优化的办法吗？

**Comment by jackygurui** [comment]
@fsindustry 你看看你的slowlog以及redis的日志看是不是有什么异常

**Comment by jackygurui** [comment]
`Redis server response timeout` 表示命令已经发出去了，但是在规定的时间内没有收到回答。产生`Redis server response timeout`这个问题的原因有可能跟redis服务器有关，也有可能跟客户端解码出现问题有关。

**Comment by dannyxu2015** [comment]
我在开发服务器上也多次遇到这个Timeout问题，除了重新启动应用进程外似乎毫无办法。redisson不会自动进行重连吗？

**Comment by jackygurui** [comment]
@dannyxu2015 请看上面的解释。
