### ISSUE TITLE
RScoredSortedSet race condition with Redis cluster

### ISSUE THREAD

**Issue by johnou** [redisson/redisson#987]
We are running two redis servers in AWS, one master, and a replica. The read mode is the default (slave).

In our application code we have something like this..

```java
 redisSet.addAsync(latestScore, playerId)
                .thenAcceptAsync(r -> {
                    Integer newRank = redisSet.revRank(playerId);
```

The issue is that since reads go to the slave, addasync returns from master and before the data replicates to the other server it tries to pull the new revrank and returns null. imo the following api would make more sense and avoid that race condition..

```java
redisSet.addAndGetAsync(latestScore, playerId) 
                .thenAcceptAsync((r, newRank)) -> { <-- BiConsumer?
                    .....
```

In the meantime I will either add retry logic or change the read mode to master but that's not going to scale in the long run so it would be nice to have this addressed.

Cheers!

**Comment by johnou** [comment]
In the meantime I will either add retry logic or change the read mode to master but that's not going to scale in the long run so it would be nice to have this addressed, cheers!

**Comment by mrniko** [comment]
Redisson already provides similar method `RScoredSortedSetAsync.addScoreAsync`

**Comment by johnou** [comment]
@mrniko bad naming in my example, we'd need something like addScoreAndGetRankAsync

**Comment by johnou** [comment]
@mrniko any further thoughts?

**Comment by johnou** [comment]
@mrniko could we somehow force specific commands to read from master that way other redis operations scale when adding additional slaves.

**Comment by zuanoc** [comment]
This is limiting our application performance pretty badly. @mrniko any updates?

**Comment by mrniko** [comment]
@zuanoc it's already implemented in `RScoredSortedSetAsync.addScoreAsync` method

**Comment by johnou** [comment]
@mrniko add score returns the score, not the new rank? We would essentially require an atomic addScoreAndGetRankAsync.

**Comment by mrniko** [comment]
Done

**Comment by johnou** [comment]
@mrniko thanks!

**Comment by zuanoc** [comment]
@mrniko thank you!

**Comment by mrniko** [comment]
@johnou @johnou  You're welcome guys!
