### ISSUE TITLE
支持与spring boot整合么

### ISSUE THREAD

**Issue by yinjihuan** [redisson/redisson#989]
支持与spring boot整合么

**Comment by jackygurui** [comment]
目前还没有spring-boot-starter，不过在spring boot下用也应该很简单，请看这个测试：
https://github.com/redisson/redisson/blob/master/redisson/src/test/java/org/redisson/spring/cache/RedissonSpringCacheTest.java#L91

**Comment by yinjihuan** [comment]
ok，可以自己封装一个starter

**Comment by jackygurui** [comment]
@yinjihuan 好啊，到时候记得给我发个PR来啊。
