### ISSUE TITLE
Hibernate Cache with local cache support 

### ISSUE THREAD

**Issue by mrniko** [redisson/redisson#991]

**Comment by mrniko** [comment]
Done. Here is a [short description](https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks/#1431-hibernate-cache-local-cache)

**Comment by johnou** [comment]
@mrniko cheeky ;) does the cache in redis (RSet?) have support for remote bounded set too? https://github.com/redisson/redisson/pull/985
