### ISSUE TITLE
Android build issue Invalid class reference (redisson 2.9.4)

### ISSUE THREAD

**Issue by vladaman** [redisson/redisson#994]
While building for Android I get following error

**// Gradle**
compile 'org.redisson:redisson:2.9.4'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

**// Error**
`Error:Execution failed for task ':app:transformClassesWithNewClassShrinkerForFikDebug'.
com.android.build.gradle.shrinker.ClassLookupException: Invalid class reference: org/springframework/beans/support/ArgumentConvertingMethodInvoker
`

**Comment by mrniko** [comment]
Seems spring dependency has been missed. Are you building Redisson itself?
