### ISSUE TITLE
org.redisson.client.RedisTimeoutException: Subscribe timeout:超时？没有配置对吗？

### ISSUE THREAD

**Issue by yueyemisi** [redisson/redisson#995]
代码如下：
RLock lock = redis.getLock("test");
lock.lock(3,TimeUnit.SECONDS);

偶尔会报下面的错误：

org.redisson.client.RedisTimeoutException: Subscribe timeout: (9500ms)
	at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:125)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:121)
	at org.redisson.RedissonLock.lock(RedissonLock.java:99)

配置文件如下：
 "sentinelServersConfig":{
    "idleConnectionTimeout":10000,
    "pingTimeout":1000,
    "connectTimeout":10000,
    "timeout":5000,
    "retryAttempts":3,
    "retryInterval":1500,
    "reconnectionTimeout":3000,
    "failedAttempts":3,

jdk为1.8，Redisson版本为3.4.4，redis版本为3.0.6

是我配置的超时时间有问题吗？
应该配置多少合适呢

**Comment by jackygurui** [comment]
有可能你的连接数用完了。

**Comment by wuxuguang** [comment]
同样的问题，不知道为啥，改成tryLock试试

**Comment by jackygurui** [comment]
pubsub的连接用完了。

**Comment by zpczpczpc** [comment]
@jackygurui pubsub的连接用完了 这个是什么参数配置的？
