### ISSUE TITLE
Expiring a live object won't expire those fields that are distirbuted objects

### ISSUE THREAD

**Issue by lqhl** [redisson/redisson#996]
I define a live object like this:
```
@REntity
public class ExampleLiveObject {
    @RId(generator = LongGenerator.class)
    private Long id;
    @RCascade(RCascadeType.ALL)
    private Map<Integer, Integer> map;
}
```

Then try to expire a live object:
```
RLiveObjectSerivce service;
ExampleLiveObject liveObject;

service.asRExpirable(liveObject).expire(1, TimeUnit.SECONDS);
```

The live object will be removed after one second, but the map in the object won't. Is this behavior expected?
My current workaround is to expire each distributed object field in a live object explicitly.

**Comment by jackygurui** [comment]
At the moment, expiring is only associated to the underlying RMap. I guess this can be added as a new feature that expiration also cascades down too.

**Comment by elitalobo** [comment]
If I delete a live object having the following class structure using service.delete(Session.class, "sessionid"), won't the fields inside the object get deleted? Do I have to delete each field explicitly?

@REntity
public class Session {
    @RId
    private String id;
    private String api_key;
    private String userid;
    private String ip;
    private Long expirytime;
}

**Comment by jackygurui** [comment]
@elitalobo those fields will be deleted and cascading is working fine for persisting and deleting, only expiring is not yet supported.

**Comment by elitalobo** [comment]
@jackygurui, thanks for the fast reply!. I am saving sessions in redis using redission so I also need to set expiry for the Session live object. Since I don't have any distributed objects in my session class, expiring a live object of the same shouldn't be a problem right?

**Comment by elitalobo** [comment]
@jackygurui, thanks for the fast reply!. I am saving sessions in redis using redission so I also need to set expiry for the Session live object. Since I don't have any distributed objects in my session class, expiring a live object of the same shouldn't be a problem right?

**Comment by elitalobo** [comment]
@jackygurui, thanks for the fast reply :). I am storing session in redis and hence need to expire live Session objects. Since I do not have any distributed objects in my session class, expiring a Session live object shouldn't be a problem right?

**Comment by jackygurui** [comment]
@elitalobo you should be fine with expiring of the object if you don't have any nested expirables

**Comment by slyfer** [comment]
Why Is closed? The issue Is still presente! Maps and List inside a live object never expires. Also there are no referente into live_object_fileds to the patent love object, so actually Is not possible use a listner to clean up

**Comment by Petersoj** [comment]
Redisson still doesn't seem to clean up Redis/Valkey child objects of Live Objects fields in the latest version, but the following example demonstrates a simple, but manual, approach to expiring child objects. Just thought I'd shared this for future reference.
```java
@REntity
@SuppressWarnings("LombokSetterMayBeUsed") // Can't use Lombok with Redisson Live Object
public class SomeData {

    private @RId String id;
    private Set<String> someSet;

    /**
     * Sets the expiration of this {@link SomeData} live object and cascades the expiration to the
     * child object references.
     *
     * @param dataCache the {@link RedissonClient}
     * @param duration  the expiration {@link Duration}
     */
    public void expire(RedissonClient dataCache, Duration duration) {
        dataCache.getLiveObjectService().asLiveObject(this).expire(duration);
        ((RSet<String>) getSomeSet()).expire(duration);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Set<String> getSomeSet() {
        return someSet;
    }

    public void setSomeSet(Set<String> someSet) {
        this.someSet = someSet;
    }
}
```
