### ISSUE TITLE
redisson getkeys iterator got more keys than counts

### ISSUE THREAD

**Issue by LiPingjiang** [redisson/redisson#997]
Config config = new Config();
        RedissonClient client = Redisson.create(config);

        System.out.println("has keys: " + client.getKeys().count() );
        Iterator rkey =client.getKeys().getKeys().iterator();
        int count = 0;
        while (rkey.hasNext() ){
            count++;
            rkey.next();
        }
        System.out.println("count: "+ count);

The counts of keys are 3000 for example, but the iterator seem never stops counting. Why?

**Comment by mrniko** [comment]
I can't reproduce this. Which Redisson version do you use?

**Comment by LiPingjiang** [comment]
I use this one: compile group: 'org.redisson', name: 'redisson', version: '3.4.4'

**Comment by mrniko** [comment]
Can you provide complete test with code where you create objects?
