### ISSUE TITLE
Storing Redisson Live Object in RSetCache

### ISSUE THREAD

**Issue by elitalobo** [redisson/redisson#998]
Hi,

Is it possible to store Redisson Live Object in RSetCache such that when the live object expires, it is evicted from RSetCache as well? 
Also can we access the Live Objects from RSetCache?  While iterating over the live objects in RSetCache, I tried to assign the object to an instance of Live Object Class but I got an error stating that I cannot typecast object of type RedissonReference to object of type Class X.

**Comment by jackygurui** [comment]
You should be able put a live object into a RSet without issue. This works by creating a RedissonReference object and pointing it to the Live Object, and because it is not the actual object itself, so it won't be evicted when the Live Object is.

As to why you are getting the type case exception, can you provide me with a reproducible code snippet please?

**Comment by elitalobo** [comment]
`@REntity
public class Session {
    @RId
    private String id;
    private String api_key;
    private String userid;
    private String ip;
    private Long expirytime;
    private Long sessionexpirytime;
}


public RedissonClient client () throws IOException, ParseException, CustomException, JSONException, InterruptedException {

        ClassLoader classloader = Thread.currentThread().getContextClassLoader();

        InputStream sentinel_config = classloader.getResourceAsStream("sentinelserversconfig.json");


        String sentinel_config_str = IOUtils.toString(sentinel_config);
        Config config = Config.fromJSON(sentinel_config_str);
        RedissonClient redisson = Redisson.create(config);
        String uuid = UUID.randomUUID().toString();
        
        Session session = new Session(uuid,"abc","xyz","123",1234L,5678L);
        RLiveObjectService service = redisson.getLiveObjectService();
       

        session = service.persist(session);
        RSetCache<Session> set = redisson.getSetCache("MySet");
        set.add(session,60,TimeUnit.MINUTES);
       
       	Set<Session> sessions = set.readAll();
        Iterator iter = sessions.iterator();
        while(iter.hasNext()){
            RedissonReference reference = (RedissonReference) iter.next();
            System.out.println(reference.getKeyName());
	    //Session session_new = (Session) iter.next(); This throws error -> Cannot typecast object of type RedissonReference to Object of class Session
        }
        
     
        return redisson;

 }

`

How do I get the Live Object from the reference object ? And will the reference object will turn into something similar to a dangling pointer when the object it is pointing to expires?

**Comment by elitalobo** [comment]
@jackygurui ,  Can you please tell me how to get the live object from the RedissonReference object?

**Comment by mrniko** [comment]
Fixed
